### ISSUE TITLE
Expression.NotEqual causing an exception when using queryable projections 

### ISSUE THREAD

**Issue by mrahhal** [AutoMapper/AutoMapper#1001]
[Here is the repro repo](https://github.com/mrahhal/AutoMapperEFRepro).

First of all I'm not sure if this problem is ef (or even ef7) specific, but here goes.

We have two simple models with a one-to-many relationship between them, `Article` and `Category`. We also have two DTOs related to them. So we configure the mappings:
```c#
Mapper.Initialize(config =>
    {
        config.CreateMap<Category, CategoryDto>();
        config.CreateMap<Article, ArticleDto>();
    });
```

A simple query like the following directly throws an exception:
```c#
_context.Articles.ProjectTo<ArticleDto>().ToList()
```
```
InvalidOperationException: The binary operator NotEqual is not defined for the types 'System.Int32' and 'System.Object'.
```

I followed the problem to its source, the `MappedTypeExpressionBinder` is generating a condition on `Category` to "handle null source property so it will not create an object with possible non-nullable properties which would result in an exception". You can see the logic [here](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs#L31-L37).

This works for optional relationships but for a required one (like the one in my repro) this actually throws an exception because of an incorrect generated comparison logic between int (the table key) and object (null). Probably because ef is seeing that we're checking for null over the navigation property, so it figures that the relationship is "nullable".

One workaround is to set `Mapper.Configuration.AllowNullDestinationValues` to `false` but this is far from a solution because we might actually get into the situation that is described as a reason for the very same generated condition.

This might be a bug in ef7 itself, so I'm not sure but at least can't we provide a solution for this in AutoMapper?

**Comment by mrahhal** [comment]
As for a solution, we can augment `IMemberConfigurationExpression` with something like `AllowNull()` that will set a property on `PropertyMap`. We can then check against this with the check for `Mapper.Configuration.AllowNullDestinationValues` to opt out of the the generated condition that is causing an exception.

**Comment by lbargaoanu** [comment]
Close to #938 I believe. Actually initially I thought about types not being null, not only complex types. I guess here it's about the property, not the type.

**Comment by mrahhal** [comment]
Yes, pretty similar it seems. The solution is also similar to what I had in mind. I'm OK with a `[ComplexType]` solution. But one thing I noticed is that you're doing an `#if` on `NET40`, this won't work with dnx the way it is I think.

**Comment by mrahhal** [comment]
Yes, pretty similar. The solution is also similar to what I had in mind but it seems we'll have to add (or use) an attribute for the propery? Also one thing I noticed is that you're doing an `#if` on `NET40`, this won't work with dnx the way it is I think.

**Comment by mrahhal** [comment]
Oh, my bad. We should choose one way or the other. In #938 you already chose to use an attribute on the type itself instead of the property.

**Comment by lbargaoanu** [comment]
[This](https://gist.github.com/lbargaoanu/a8aa12e1ddc100c7aad0#file-notnullfk-cs) seems to work on EF6 so I think it's fair to blame it on EF7. At least for now :)

**Comment by mrahhal** [comment]
Thought so, never had the issue on EF6 :)
Are you planning on doing something about it soon? If not I'll have to stick with my edited AutoMapper for now (what I did is similar to #938 but works with dnx).

**Comment by lbargaoanu** [comment]
I would say no, the problem seems to be in EF7. @jbogard might disagree.

**Comment by mrahhal** [comment]
@lbargaoanu even if it's an EF7 problem, this effectively makes it impossible to use automapper for anyone working with the current EF7 and using complex DTOs. This "problem" may not be fixed in EF7 for a while, you really should make a workaround for this.
I already made a custom build that fixes this for me and my team so no harm there, but you should really consider it.

**Comment by lbargaoanu** [comment]
A check for value types might do the trick here. We'll see :)

**Comment by mrahhal** [comment]
This might be hard, since the navigation property itself is a `class` so it is nullable but the relationship is required (either by virtue of the key being a non-nullable type or by explicit fluent configuration). The easiest thing is to make it opt in like an `AllowNull` method (just like `Ignore`) that we can configure on the `PropertyMap`.
Anyway, I'm in for any solution that works :)

**Comment by jbogard** [comment]
Can you submit a PR for your changes? That way we could at least review it.

**Comment by lbargaoanu** [comment]
@jbogard We need an attribute or some other solution that works for properties and for types (#925).

**Comment by mrahhal** [comment]
Sure, right when I get some time.

**Comment by mrahhal** [comment]
@jbogard @lbargaoanu #1004

**Comment by jasonholloway** [comment]
Not too sure why EF7 is substituting an integer for an entity type in its expression parsing, but #1130 inadvertently fixes this by changing `MappedTypeExpressionBinder` to explicitly cast to object type in its null guard. I've tried it with your repo and it definitely makes the difference.

**Comment by jbogard** [comment]
This is working now without any changes. Well, ok then.
