### ISSUE TITLE
Mapping enum and int

### ISSUE THREAD

**Issue by pfiggins** [AutoMapper/AutoMapper#1003]
I upgraded from 4.0.4 to 4.1.1 and mapping between enums and ints is no longer working automatically. I have to explicitly map those fields with the type conversion. Is this a bug or am I missing a breaking change in the release?

**Comment by jbogard** [comment]
Do you have a gist or dotnetfiddle to show what you're trying to do?

**Comment by pfiggins** [comment]
Sorry, I jumped the gun! The issue was with another unrelated component.
