### ISSUE TITLE
Parameterization during normal mapping

### ISSUE THREAD

**Issue by mbcrawfo** [AutoMapper/AutoMapper#1005]
I have a situation like the following:

    class Data
    {
      public int ProductId { get; set; }
      public int ProductRevision { get; set; }
    }

    class DataDTO 
    {
      public int ProductId { get; set; }
    }

The DTO is carrying a product selected by the user, and the service layer needs to set the current product revision before storing the data.  Revision would be obtained via something like `data.ProductRevision = productRepository.FindById(dto.ProductId).Revision`.  I can of course set this using either code after calling `Map` or an explicit `AfterMap` callback, but I would prefer to make it part of the mapping so that it's less easily forgotten.

Parameterization seems perfect for this case, is there a reason why it's only supported on projection?

**Comment by jbogard** [comment]
It's supported, just in a different way. You have to use a custom resolver (or anything that has access to the ResolutionContext).

```
cfg.CreateMap<Foo, Bar>()
   .ForMember(dest => dest.Baz, opt => opt.ResolveUsing(res => res.Context.Options.Items["thing"]));

Mapper.Map<Foo, Bar>(foo, opt => opt.Items["thing"] = User.Name);
```

**Comment by mbcrawfo** [comment]
Awesome, thanks.

**Comment by mbcrawfo** [comment]
For anyone else who may be interested in this, I wrote a few extension methods to make this process more convenient.  With the extensions, the example provided by @jbogard  becomes:

    Mapper.CreateMap<Foo, Bar>()
        .ResolveFromItems(dst => dst.Baz)
        // --- OR ---
        .ForMember(dst => dst.Baz, opt => opt.FromItems("Baz");

    Mapper.Map<Foo, Bar>(foo, opt => opt.ItemFor(dst => dst.Baz, User.Name);

Extension methods:

    /// <summary>
    ///   Convenience method to resolve a member using the 
    ///   <see cref="IMappingOperationOptions.Items"/> dictionary,
    ///   with the name of the member as the key.
    /// </summary>
    /// <typeparam name="TSource"></typeparam>
    /// <typeparam name="TDestination"></typeparam>
    /// <typeparam name="TProperty"></typeparam>
    /// <param name="map"></param>
    /// <param name="selector"></param>
    /// <returns></returns>
    public static IMappingExpression<TSource, TDestination>
      ResolveFromItems<TSource, TDestination, TProperty>(
        this IMappingExpression<TSource, TDestination> map,
        Expression<Func<TDestination, TProperty>> selector)
    {
      var expression = selector.Body as MemberExpression;
      Debug.Assert(expression != null);
      var key = expression.Member.Name;

      return map.ForMember(key, opt => opt.FromItems(key));
    }

    /// <summary>
    ///   Convenience method to resolve a member using the 
    ///   <see cref="IMappingOperationOptions.Items"/> dictionary,
    ///   with a custom key name.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="opt"></param>
    /// <param name="key"></param>
    /// <returns></returns>
    /// <exception cref="ArgumentException">
    ///   key is null or empty.
    /// </exception>
    public static IMemberConfigurationExpression<T>
      FromItems<T>(this IMemberConfigurationExpression<T> opt,
        string key)
    {
      if (string.IsNullOrEmpty(key)) 
        throw new ArgumentException("Argument is null or empty", "key");

      opt.ResolveUsing(res => res.Context.Options.Items[key]);
      return opt;
    }

    /// <summary>
    ///   Convenience method to insert an item into the 
    ///   <see cref="IMappingOperationOptions.Items"/> dictionary,
    ///   using the name of the selected member as the key.
    /// </summary>
    /// <typeparam name="TSource"></typeparam>
    /// <typeparam name="TDestination"></typeparam>
    /// <typeparam name="TProperty"></typeparam>
    /// <param name="opt"></param>
    /// <param name="selector"></param>
    /// <param name="value"></param>
    public static void ItemFor<TSource, TDestination, TProperty>(
      this IMappingOperationOptions<TSource, TDestination> opt,
      Expression<Func<TDestination, TProperty>> selector,
      object value)
    {
      var expression = selector.Body as MemberExpression;
      Debug.Assert(expression != null);
      var key = expression.Member.Name;

      opt.Items[key] = value;
    }

**Comment by jbogard** [comment]
NICE! I'm going to roll this in to AutoMapper, would you mind opening another issue for these extension methods?
