### ISSUE TITLE
SubstitutionMapperStrategy NullReferenceException

### ISSUE THREAD

**Issue by antoinebj** [AutoMapper/AutoMapper#1009]
When using `CreateMap<,>.Substitute()`, if the delegate returns null, the call to `newSource.GetType()` in `SubstutitionMapperStrategy.Map()` generates a `NullReferenceException`.

https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/Mappers/TypeMapObjectMapperRegistry.cs#L39

At first glance this looks like an oversight and therefore a bug, but perhaps it is intentional?

I stumbled upon this while using such code:
```csharp
map.Substitute(src => src != null ? src.SomeField : null)
```
I wrote this code because the substitution delegate is called even though the source is null. Is that also intended behavior?

And by the way there is a typo in the class name: `SubstutitionMapperStrategy`

**Comment by lbargaoanu** [comment]
Is there any reason you're not using MapFrom or ResolveUsing?

**Comment by antoinebj** [comment]
Yes, to re-use the mapping logic of the substitute source without having to define the maps on all types where the members at source and destination have the same name.

Example:
Type A with property named "X" of type C
Type B with property named "X" of type D
Defining map from C to D removes the need of defining a property map for "X" on the type map for A to B. Simple convention is sufficient.

Does that make sense ?

**Comment by lbargaoanu** [comment]
A type converter can do that.

**Comment by antoinebj** [comment]
Then for whatever use case the Substitute method exists, if its behavior works as intended even in light of what was described in this issue, you may close this issue or request that I do so.

**Comment by lbargaoanu** [comment]
It does look like a bug. But it seems Substitute is intended for a specific use case (see the doc comment). I think you're better off using something more "mainstream". Anyway, it could be a while before a fix, yet another reason to try some other way.

**Comment by jbogard** [comment]
Substitute isn't meant to return null, you need to return *something*.
