### ISSUE TITLE
Inheritance in projections

### ISSUE THREAD

**Issue by LeanderKnol** [AutoMapper/AutoMapper#1011]
I am using automapper for a while. We are also using mapping inheritance. This is working perfectly. We wanted to make some performance improvements by using projections, using the ProjectTo function. What we have notices is that when using this method the inheritance is lost and only the base class is mapped. 
Is inheritance not implemented in the queryable extensions? Or do I have to do something special? 

Our mapping is like this:

   CreateMap\<Agreement, AgreementDto>()
                .Include\<Subscription, SubscriptionDto>()
                .Include\<OneOffAgreement, OneOffAgreementDto>();

   CreateMap\<Subscription, SubscriptionDto>();
   CreateMap\<OneOffAgreement, OneOffAgreementDto>();

This is working fine, and returns the DTO's matching the sub class:
Mapper.Map\<IEnumerable<Agreement>, IEnumerable\<AgreementDto>>(agreements).ToList();

When using this, it returns the same amount of agreements but all of them are of the type AgreementDto:
agreements.ProjectTo\<AgreementDto>().ToList();

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/842#issuecomment-139104798).

**Comment by LeanderKnol** [comment]
When starting up our application we are calling this:
 Mapper.Initialize(cfg =>           {              cfg.AddProfile(new AgreementAutoMapperProfile());            });

So it should be initialized. The agreements are retrieved from a database using EF6.

**Comment by lbargaoanu** [comment]
[Working example](https://gist.github.com/lbargaoanu/0ae26a08d1a7821c2c91#file-project-and-include-cs) with Include.

**Comment by lbargaoanu** [comment]
I think I see your point. ProjectTo will return objects of the same type, ignoring the types of the objects materialized. This seems complicated :)

**Comment by TylerCarlson1** [comment]
Actually see this. #948
EF6 doesn't support this scenario, unfortunately.

But that doesn't explain why things returned.  What should happen if you set this up is you should get an error from Entity Framework saying it can't convert multiple return types.

Either way it doesn't work and EF6 team left the fix up for grabs.

I guess the best workaround is return the classes then translate the DTO's after returned them.  Can't use AfterMap have to do it manually.  Not the most elegant solution, but you get the benefits of the ProjectTo in this scenario.

**Comment by TylerCarlson1** [comment]
Actually I wrong about the exception sorry, haven't looked at this issue in a while.  It was requested that AutoMapper make inheritance work in ProjectTo, but it was discovered that EF6 couldn't support this, so it was never implemented, ergo no exception.  So in order to add this feature into AutoMapper, the EF6 feature needs to work, or EF7 fixes this.

**Comment by lbargaoanu** [comment]
I see that too. So I think it's safe to say this is not going to happen with EF6.
