### ISSUE TITLE
Map does not recognize interface type coinfiguration when concrete type configuration is present

### ISSUE THREAD

**Issue by cglist** [AutoMapper/AutoMapper#1012]
I seem to have discovered an issue where the mapper uses the type of the object passed in even if you tell it to 
use a different type mapping  ...atleast when you tell it to use an interface type

Suppose we have:
```C#
    public interface IProduct
    { 
    	int Id {get; set;}
    	string Name { get; set; }
    }

   public class Product : IProduct
   { 
    	public int Id {get; set;}
    	public string Name { get; set; }
    	public DateTime CreatedOn { get; set; }
    }
```
... then you create a configuration:
```C#
    Mapper.CreateMap<IProduct, IProduct>();
```

... then map two Product OBJECTS, using that map...
```C#
    Mapper.Map<IProduct, IProduct>(source, destination);
```
As expected, the CreatedOn date will not be mapped from the source to the destination; and this is what we want, destination does not get it's CreatedOn value overwritten.
All is well.

Now, if you ALSO create this map (because sometimes you might want to map the whole object):
```C#
    Mapper.CreateMap<Product, Product>();
```
..and then run the same code, where you tell the mapper to use the INTERFACE type:
```C#
    Mapper.Map<IProduct, IProduct>(source, destination);
```
it will actually use the obeject type mapping and will map the CreatedOn value to the destination.

...it will do the same thing if you do the mapping this way:
```C#
    Mapper.Map(source, destination, typeof(IProduct), typeof(IProduct));
```
....or if you do it this way (which I think is to be expected because the object is still the same):
```C#
    Mapper.Map(source as IProduct, destination as IProduct, typeof(IProduct), typeof(IProduct));
```
This seems flawed to me - why would it not find the proper mapping to use? It should use the mapping based on the list of members in the interface since that's what we're telling it to use - no??

Thanks,
Chris

**Comment by TylerCarlson1** [comment]
I'm not sure about this situation, but I think since both object are the same type it uses assignable mapper which sets the destination.  Automapper isn't intended for cloning items.  Maybe try IProperty to IPropertyDTO for a better example.

If that case works out the same, I don't know if this is valid way of using AutoMapper.  With mapping automapper uses the type of the object as a basis of mapping, because if you map a base object with 3 inherited class types to another type that has matching inherited types, with matching mappings, you would want the inherited map to work and not the base map.  This is with Include function, but the idea is you would always want the highest level mapping.

The real question is in what scenario would YOU be using that you wanted the lower level mapping to work?

**Comment by lbargaoanu** [comment]
The type map mapper precedes the assignable mapper, but the point stands. AutoMapper will choose the type map based on the real types of the passed objects.

**Comment by cglist** [comment]
OK, I confess, I've not had much need for AutoMapper and haven't really used it much. I had a feeling I was going to get a "Why are you trying to do this?" response :)

To keep my answer short I'll just say that I'm lazy. I don't want to have put effort into crafting various class-specific mappings with a bunch of "ignores" - it's easier to define only the fields I want mapped as part of an interface, and then have my Entity class and my View-Model class implement that interface. That also make it easier for my service classes that are actually configuring and doing the mappings to be generics.

I can use a different method for my object cloning (which, to be honest is kind of an edge case and I only need a shallow clone) - but AutoMapper seemed like the way that would be the least amount of effort. After all, if something is made for mapping values between objects why not use it for cloning them?

I guess it just seems strange to me that you configure a mapping by specifying a pair of types, and then you tell it do the mapping by specifying a pair of types, but it ignores what you tell it. If it's going to use the type of the object that's passed in, then what's the point of having types as parameters to the Map function? I guess I still don't get how those parameters to the Map function would ever be used.

I've been able to get around the problem by simply not using the global static configuration store, but instead creating different static instances of the store and mapping engine for each of my type-pairs.

**Comment by TylerCarlson1** [comment]
This might be able to work for what you want

```
public class InterfaceProfile : Profile
        {
            protected override void Configure()
            {
                AddMemberConfiguration().NameMapper.GetMembers.AddCondition(mi => mi.DeclaringType.GetInterfaces().Any(i => i.GetProperty(mi.Name) != null));
                AddConditionalObjectMapper().Where((s, d) => d.GetInterfaces().Any(i => s.GetInterfaces().Contains(i)));
            }
        }
```
And where you do the mapping use this.
```
            Mapper.Initialize(cfg => cfg.AddProfile<InterfaceProfile>());
```

What this does is make a convention saying only map classes that share the same interface, and only use properties that are part of a backing interface.

That's the laziest solution I can think of.

Also if you are going to try ProjectTo I would recomend using the alpha builds from myGet, look at automapperdev build in the readme, cause there's a problem in 4.1.1 with projection and not mapping the object first, when it comes to conventions.
