### ISSUE TITLE
Incorrect Mapping Inheritance with existing destination object

### ISSUE THREAD

**Issue by christophe12sopra** [AutoMapper/AutoMapper#1016]
I automapping an interface in other new --> it's OK (find GOOD JOB in source code)
I automapping an interface in other existing --> it's NOT OK (find BAD JOB in source code)

here is my simple example source code to view the problem : 

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using AutoMapper;

namespace UIModelTest
{
    [TestClass]
    public class TestAutomapper
    {
        [TestMethod]
        public void automapperTest()
        {
            Mapper.CreateMap<iclass1, iclass1DTO>().Include<iclass2, iclass2DTO>().Include<iclass3, iclass3DTO>().Include<iclass4, iclass4DTO>();
            Mapper.CreateMap<iclass2, iclass2DTO>();
            Mapper.CreateMap<iclass3, iclass3DTO>();
            Mapper.CreateMap<iclass4, iclass4DTO>().ConstructUsing((ResolutionContext rc) => new class4DTO());
            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();

            iclass4 bo = new class4() ;
            bo.prop1 = "PROP1";
            bo.prop2 = "PROP2";
            bo.prop3 = "PROP3";
            bo.prop4 = "PROP4";
            iclass4DTO dto = new class4DTO();

            // BAD JOB : HS
            Mapper.Map<iclass4, iclass4DTO>(bo, dto);

           // GOOD JOB : OK !! 
            iclass4DTO dto2 = Mapper.Map<iclass4, iclass4DTO>(bo);
        }
    }

    public abstract class class1 : iclass1
    {
        public string prop1 { get;set;}
    }

    public class class2 : class1, iclass2
    {
        public string prop2 { get; set; }
    }

    public class class3 : class2, iclass3
    {
        public string prop3 { get; set; }
    }

    public class class4 : class3, iclass4
    {
        public string prop4 { get; set; }
    }

    public abstract class class1DTO : iclass1DTO
    {
        public string prop1 { get; set; }
    }

    public class class2DTO : class1DTO, iclass2DTO
    {
        public string prop2 { get; set; }
    }

    public class class3DTO : class2DTO, iclass3DTO
    {
        public string prop3 { get; set; }
    }

    public class class4DTO : class3DTO, iclass4DTO
    {
        public string prop4 { get; set; }
    }

    public interface iclass1
    {
        string prop1 { get; set; }
    }

    public interface iclass2 : iclass1
    {
        string prop2 { get; set; }
    }

    public interface iclass3 : iclass2
    {
        string prop3 { get; set; }
    }

    public interface iclass4 : iclass3
    {
        string prop4 { get; set; }
    }

    public interface iclass1DTO
    {
        string prop1 { get; set; }
    }

    public interface iclass2DTO : iclass1DTO
    {
        string prop2 { get; set; }
    }

    public interface iclass3DTO : iclass2DTO
    {
        string prop3 { get; set; }
    }

    public interface iclass4DTO : iclass3DTO
    {
        string prop4 { get; set; }
    }
}
```
Thank you in advance for your help

Best regards

Christophe

**Comment by christophe12sopra** [comment]
Hello,

I add a test case, similar to a previous but with IncludeBase instead of Include. 
The result is different... I don't understand, the problem is reversed. I undertood  the 2 ways are similar ! 

        public void automapperTest2()
        {
            Mapper.CreateMap<iclass1, iclass1DTO>();
            Mapper.CreateMap<iclass2, iclass2DTO>();
            Mapper.CreateMap<iclass3, iclass3DTO>();
            Mapper.CreateMap<iclass4, iclass4DTO>().ConstructUsing((ResolutionContext rc) => new class4DTO()).IncludeBase<iclass2, iclass2DTO>().IncludeBase<iclass3, iclass3DTO>().IncludeBase<iclass1, iclass1DTO>();
            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();

            iclass4 bo = new class4() ;
            bo.prop1 = "PROP1";
            bo.prop2 = "PROP2";
            bo.prop3 = "PROP3";
            bo.prop4 = "PROP4";
            iclass4DTO dto = new class4DTO();

            // BAD JOB : HS !!
            Mapper.Map<iclass4, iclass4DTO>(bo, dto);

            // GOOD JOB : OK !!
            iclass4DTO dto2 = Mapper.Map<iclass4, iclass4DTO>(bo);
        }

**Comment by lbargaoanu** [comment]
About the first case. It's about what type map is used. When you don't pass a destination, you map from iclass4 to iclass4DTO. When you do, you map from iclass1 to iclass1DTO. That's because AutoMapper treats all interfaces the same, it doesn't consider that class4DTO implements itself iclass4DTO and the others are implemented by base classes. I guess it could :)

**Comment by christophe12sopra** [comment]
Thank you for your explanation. What is the solution for correct execution? I don't understand the way.

**Comment by lbargaoanu** [comment]
Your code as it is won't work unless we change AutoMapper. A workaround is to create the maps for the classes, not the interfaces.

**Comment by lbargaoanu** [comment]
@jbogard Should we make this work?

**Comment by christophe12sopra** [comment]
Workaround is not possible because the real type are masked by the interfaces and innaccessibles. The objects are obtained from factories. if this development could be done, that would be real progress for use in enterprise modular applications.

**Comment by christophe12sopra** [comment]
Can you tell me when it will be decided as I have to decide if I thought about patient or another solution. Anyway, thank you for your help.

**Comment by lbargaoanu** [comment]
There are non-generic versions of CreateMap. It's not exactly clean, but you should be able to map non public types.

**Comment by christophe12sopra** [comment]
I run my small example with your indication and it's OK, but if it improves the example to be more real to the application, it does not work. For example, one interface have an attribute with type other interface : 

    public interface iclass4DTO : iclass3DTO
    {
        string prop4 { get; set; }
        iclass2DTO obj4 { get; set; }
    }

assertConfigurationIsValid is HS because, it can't map iclass2 to iclass2DTO but class2 to class2DTO. it not possible to define this mapping because the problem is the same.

**Comment by lbargaoanu** [comment]
AssertConfigurationIsValid is just a helper. What matters is if it works at runtime.

**Comment by christophe12sopra** [comment]
L'exception AutoMapper.AutoMapperMappingException n'a pas été gérée par le code utilisateur
  HResult=-2146233088
  Message=Missing type map configuration or unsupported mapping.

Mapping types:
class2 -> iclass2DTO
UIModelTest.class2 -> UIModelTest.iclass2DTO

Destination path:
class4DTO.obj4.obj4

Source value:
UIModelTest.class2
  Source=AutoMapper
  StackTrace:
       at UIModelTest.TestAutomapper.automapperTest2() in c:\Workspaces\TestAutomapper.cs:line 57
  InnerException:

**Comment by christophe12sopra** [comment]
I try this createmap solution and it's OK : interface mapping add (see below)
I don't understand why !! However, it's the same problem that  the first problem !
            Mapper.CreateMap<iclass1, iclass1DTO>();
            Mapper.CreateMap<iclass2, iclass2DTO>().IncludeBase<iclass1, iclass1DTO>();
            Mapper.CreateMap<iclass3, iclass3DTO>().IncludeBase<iclass1, iclass1DTO>().IncludeBase<iclass2, iclass2DTO>();
            Mapper.CreateMap<iclass4, iclass4DTO>().IncludeBase<iclass1, iclass1DTO>().IncludeBase<iclass2, iclass2DTO>().IncludeBase<iclass3, iclass3DTO>();
            Mapper.CreateMap<class1, class1DTO>();
            Mapper.CreateMap<class2, class2DTO>().ConstructUsing((ResolutionContext rc) => new class2DTO()).IncludeBase<class1, class1DTO>();
            Mapper.CreateMap<class3, class3DTO>().ConstructUsing((ResolutionContext rc) => new class3DTO()).IncludeBase<class1, class1DTO>().IncludeBase<class2, class2DTO>();
            Mapper.CreateMap<class4, class4DTO>().ConstructUsing((ResolutionContext rc) => new class4DTO()).IncludeBase<class1, class1DTO>().IncludeBase<class2, class2DTO>().IncludeBase<class3, class3DTO>();
            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();

**Comment by lbargaoanu** [comment]
[This] (https://gist.github.com/lbargaoanu/19e8ec659cb1d7e71df4#file-gistfile1-txt) works. It's a mess :) That ConstructUsing shouldn't be required. I believe that's a bug.

**Comment by lbargaoanu** [comment]
[Somewhat better](https://gist.github.com/lbargaoanu/454185b75ed017a8b81a#file-gistfile1-txt).

**Comment by christophe12sopra** [comment]
I try to apply your suggestion to my final example but it don't work. I attach my final example with part work and part don't work.
[finalExample.txt](https://github.com/AutoMapper/AutoMapper/files/92082/finalExample.txt)

**Comment by lbargaoanu** [comment]
You must run my example on the MyGet branch :)

**Comment by christophe12sopra** [comment]
Your example run, but with my final add in my exemple, don't run :(

**Comment by lbargaoanu** [comment]
Exactly which change breaks my example?

**Comment by christophe12sopra** [comment]
my example is more complex and take the real case in my application. 
with your strtegy example, the error is : (test case available in my finalExample.txt see above)

L'exception AutoMapper.AutoMapperMappingException n'a pas été gérée par le code utilisateur
  HResult=-2146233088
  Message=Missing type map configuration or unsupported mapping.

Mapping types:
class2 -> iclass2DTO
UIModelTest.class2 -> UIModelTest.iclass2DTO

Destination path:
class4DTO.obj4.obj4

Source value:
UIModelTest.class2
  Source=AutoMapper
  StackTrace:
       at UIModelTest.TestAutomapper.automapperTest() in c:\TestAutomapper.cs:line 76
  InnerException:

**Comment by lbargaoanu** [comment]
I understand that :) But I'm not going to dig through your example trying to find what doesn't work. Start from my example and make the smallest change that breaks it.
