### ISSUE TITLE
duplicate inheritance IProfileConfiguration ???

### ISSUE THREAD

**Issue by rdaddis** [AutoMapper/AutoMapper#1020]
public interface IConfigurationProvider : IConfiguration, IProfileExpression, IProfileConfiguration
public interface IProfileExpression : IProfileConfiguration

IProfileConfiguration - is it late or am I seeing double :-)

**Comment by lbargaoanu** [comment]
[Can you please close your issue?](https://github.com/AutoMapper/AutoMapper/blob/c83bc8e8fc1ad048231cc2dfa3f4e3e3a0cbec7a/src/AutoMapper/IConfigurationProvider.cs#L7)

**Comment by jbogard** [comment]
No, you're not crazy. I'm working on consolidating some of these, it's a
bit of a mess.
