### ISSUE TITLE
Using a profile to recognize postfixes not working

### ISSUE THREAD

**Issue by michael-x** [AutoMapper/AutoMapper#1021]
I'm trying to create a profile like

```C#
			Mapper
				.CreateProfile("ViewModelToBusiness")
				.RecognizePostfixes("Id");
```
I've got a converter that converts `int` to the corresponding business object with the proper Id. But when I say

```C#
			Mapper
				.CreateMap<MyViewModel, MyBusinessModel>()
				.WithProfile("ViewModelToBusiness")
				;
```

I get an exception that `MyProperty` is not mapped even though there is a corresponding `MyPropertyId` property on the source.

What am I doing wrong? (It works when setting `RecognizePostfixes` in `Mapper.Initialize` globally, but this may not always be appropriate!)

**Comment by TylerCarlson1** [comment]
Try making profile include all its mappings in its configure call.
Make sure all create maps use CreateMap and don't use Mapper.CreateMap
```
    public class ViewModelToBuisness : Profile
    {
        protected override void Configure()
        {
            RecognizePostfixes("Id");
            CreateMap<MyViewModel, MyBusinessModel>();
        }
    }
```
And
```
Mapper.Initialize(cfg =>
{
     // Other Mapping logic
     cfg.AddProfile<ViewModelToBuisness>();
});
```

If you CreateMap using the Profile it will be tied using the postfixes.
You can also do `profile.CreateMap<MyViewModel, MyBusinessModel>();`, but you would want to do that in Mapper.Initilize if you do this.
ViewModel, MyBusinessModel>();`, but you would want to do that in Mapper.Initilize if you do this.

I've never used WithProfile before, so it might be a valid bug.
By default Mapper.CreateMap is directly tied to the default profile, so I don't know how it can transfer the mapping to another profile.

**Comment by michael-x** [comment]
Thanks for the quick response.

I've tried the first approach above and it works.

I've also re-visited the attempt using the result of `Mapper.CreateProfile("ViewModelToBusiness")`. You need to beware though that you need to do that after `Mapper.Initialize` to automatically add the profile or that you have to call `cfg.AddProfile((Profile)profile);` in `Mapper.Initialize`. (It's a little annoying that you have to cast the `IProfileExpression` back to `Profile` as `CreateProfile` returns an `IProfileExpression` while `AddProfile` expects a `Profile`, but it works.)

You can also create the `Profile` directly by calling `new Profile("ViewModelToBusiness")` and add it with `cfg.AddProfile(profile)`. (This gets rid of the cast to `Profile` in `cfg.AddProfile`.)

That all said I've also re-visited my original attempt and it looks like the `.WithProfile` works as well. The problem actually was that I've used `Mapper.CreateProfile` before `Mapper.Initialize` and was incorrectly assuming that this should have added the profile automatically.

It might be good to update the documentation to better document the behavior. Using a simple named `Profile` instead of a custom profile class helps keeping mapping logic in one place. Although of course, when projects get bigger and you would like to modularize a little better, custom profile classes are great. My use case though was to just have a slightly modified configuration for a handful of mapped classes.
