### ISSUE TITLE
NullReferenceException using AddConditionalObjectMapper (not when using empty CreateMap) on SECOND attempt to map value

### ISSUE THREAD

**Issue by SweVictor** [AutoMapper/AutoMapper#1022]
Hi!
First: Automapper is GREAT and gets better all the time! We use it extensively and have now started using AddConditionalObjectMapper. However we have run in to a very strange problem.

Basically we have a DB model (EF6 based, code first) in this case with the type Schedule. We try to map this to ScheduleViewModel runtime using `Mapper.Map<Schedule, ScheduleViewModel>(await dbContext.FindAsync(id))`. Runtime the type is a dynamic proxy type, hence the explicit source type (otherwise we get a mapping not found).

This works fine using a default `CreateMap<Schedule, ScheduleViewModel>();`

However when using the conditional mapper: `AddConditionalObjectMapper().Where((s, d) => d.Name == s.Name + "ViewModel");` it works the *first* time but not the *second*.

To clarify, this code gives correct results for both s1 and s2 when using CreateMap, but exception on s2 (correct value for s1) when using ConditionalObjectMapper:

            var schedule = await dbContext.FindAsync(id);
            var s1 = Mapper.Map<Schedule, ScheduleViewModel>(schedule);
            var s2 = Mapper.Map<Schedule, ScheduleViewModel>(schedule);

ScheduleViewModel is simplest possible:

    public class ScheduleViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

Schedule is a typical EF code first model - copies of the properties above (with [Required] and [StringLength(..)] on the Name property, as well as a bunch of other properties, foreign keys and collections.

Exception is pasted below:

```
AutoMapper.AutoMapperMappingException occurred
  HResult=-2146233088
  Message=

Mapping types:
Schedule -> ScheduleViewModel

Destination path:
ScheduleViewModel

Source value:
[Custom ToString]  Source=AutoMapper
  StackTrace:
       at SchedulesController.<Get>d__4.MoveNext() in SchedulesController.cs:line 39
  InnerException: 
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=AutoMapper
       StackTrace:
            at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
            at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
       InnerException: 
```

Any ideas on why this would occur? Any help would be greatly appreciated!

We use the latest version, 4.1.1 as of this writing.

/Victor

**Comment by TylerCarlson1** [comment]
The exception is incomplete, could I get the rest of it to see what's going on?

Can you try the latest development build of AutoMapper? [Nuget feed](https://www.myget.org/F/automapperdev/api/v2)
There has been some improvements to conventions and some changes that might effect this.

I'm trying out on latest development build and can't seem to replicate.
I can map to an inherited object and see the base class mappings used, with conventions no problem.
Don't have proxy class, but inheritance class should be a valid substitute

Few things:
1. You shouldn't have to specify the source type when mapping.  It should try proxy type, then go into base types to find match.  (You can debug `d.Name == s.Name + "ViewModel"` while mapping for the first time to see what it does)  It should try proxy type name and fail then go into Schedule and pass and start the mapping.
2. When you call AddConditionalObjectMapper() where is this calling from?  Source relative to other mappings can have different effects.
3.  Are you using Mapper.Initialize() or Mapper.Seal()?

**Comment by SweVictor** [comment]
Thanks for the reply.

Starting off, let me answer the questions:

1. Removing source type gives the following exception below. Debugging the `s.Name ...` part shows `d.Name = Schedule` (which matches) when specifying source type, without source type `d.Name = Schedule_66DA969C3B3D0C34DD412709563C4AB28605F6D067A6F2B1FAF50E63426BC71E` which does not match. Breakpoint only hits once. Exception without source type:
```
AutoMapper.AutoMapperMappingException occurred
  HResult=-2146233088
  Message=Missing type map configuration or unsupported mapping.

Mapping types:
Schedule_66DA969C3B3D0C34DD412709563C4AB28605F6D067A6F2B1FAF50E63426BC71E -> ScheduleViewModel
System.Data.Entity.DynamicProxies.Schedule_66DA969C3B3D0C34DD412709563C4AB28605F6D067A6F2B1FAF50E63426BC71E -> Models.ScheduleViewModel

Destination path:
ScheduleViewModel

Source value:
[Custom ToString]
  Source=AutoMapper
  StackTrace:
       at Controller.SchedulesController.<Get>d__4.MoveNext() in C:\Development\Main\Src\Mindmancer.Services.RestApi\Controller\SchedulesController.cs:line 40
  InnerException: 
```

Changing back I get the original Exception. Not really sure how to best copy it here, this time I tried to serialize it to Json. If info is still missing, please tell me how to export the exception in a better way! (first try was VS2015's "Copy exception to clipboard" command)

```
{  
   "ClassName":"AutoMapper.AutoMapperMappingException",
   "Message":null,
   "Data":{  

   },
   "InnerException":{  
      "ClassName":"System.NullReferenceException",
      "Message":"Object reference not set to an instance of an object.",
      "Data":{  

      },
      "InnerException":null,
      "HelpURL":null,
      "StackTraceString":"   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)\\r\\n   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)",
      "RemoteStackTraceString":null,
      "RemoteStackIndex":0,
      "ExceptionMethod":"8\\nMap\\nAutoMapper, Version=4.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005\\nAutoMapper.Mappers.TypeMapMapper\\nSystem.Object Map(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner)",
      "HResult":-2147467261,
      "Source":"AutoMapper",
      "WatsonBuckets":null
   },
   "HelpURL":null,
   "StackTraceString":"   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)\\r\\n   at AutoMapper.MappingEn
gine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)\\r\\n   at AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType, Action`1 opts)\\r\\n   at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)\\r\\n   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source)\\r\\n   at Mindmancer.Services.RestApi.Controller.SchedulesController.<Get>d__4.MoveNext() in C:\\\\Development\\\\Main\\\\Src\\\\Mindmancer.Services.RestApi\\\\Controller\\\\SchedulesController.cs:line 41",
   "RemoteStackTraceString":null,
   "RemoteStackIndex":0,
   "ExceptionMethod":"8\\nAutoMapper.IMappingEngineRunner.Map\\nAutoMapper, Version=4.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005\\nAutoMapper.MappingEngine\\nSystem.Object AutoMapper.IMappingEngineRunner.Map(AutoMapper.ResolutionContext)",
   "HResult":-2146233088,
   "Source":"AutoMapper",
   "WatsonBuckets":null
}
```

(2). Regarding initialization, i created a Profile. Before I inlined the call, giving the same exception. Currently the code looks like this:
```
    public class ViewModelsProfile : Profile
    {
        protected override void Configure()
        {
            AddConditionalObjectMapper().Where((s, d) => d.Name == s.Name + "ViewModel");
        }
    }
```

(3). I use Mapper.Initialize, i have also tried adding Mapper.Seal (after Initialize)



I will try to switch to the MyGet version next.

/Victor

**Comment by SweVictor** [comment]
Huh!

v 4.2.0-ci-1040 seems to have solved the problem. Magic! :)

Interestingly the `Mapper.Map<ScheduleViewModel>` also works in the dev version (without excplicit source). 

Even more interestingly, the exception in `AddConditionalObjectMapper().Where((s, d) => d.Name == s.Name + "ViewModel");` is NOT hit anymore at all (it is set on the `d.Name == ...` part)! 

EVEN more interestingly the exception IS hit when again specifying the source type explicitly! It is actually hit TWICE, once for the proxy type and once for the actual class even though I am specifying source type explicitly here.

As a related question: What actually happens when calling `AddConditionalObjectMapper()`? I would have excepted the exact same behaviour as when doing one empty `Mapper.CreateMap<Schedule, ScheduleViewModel>()` per pair, obviously this is not the case...

So: The original problem is solved in v 4.2., however it to me behaves a bit strange. Since i'm not familiar with AutoMapper internals, I'm not sure that it actually behaves strangely...
/Victor

**Comment by TylerCarlson1** [comment]
What probably happens is when it gets to conventions it uses the sourceObject.GetType() instead of what you provided.  I assumed you wouldn't provide the source type explicitly and let the AutoMapper figure out what map should be created based on the convention.  Never considered if you explicitly provided the source type what would happen.  In most cases you wouldn't have to and expect it to work.

I think what it does is start at the highest type level and works down base classes using convention to see if valid to create map and the map be valid for mapping the objects passed.  The TypeMap used doesn't always share the types of its source and definition its mapping.

**Comment by SweVictor** [comment]
Thanks for the help on this! Just to clarify:
* The breakpoint not being hit on `.Where(s, d) => ...)` is expected moving forward? 
* The explicit source type is not supported when using `AddConditionalObjectMapper`?  (is there even a use case ever if the inheritance chain is walked upwards anyway?)

/Victor

**Comment by TylerCarlson1** [comment]
1.Breakpoints should only happen once per type pair.  Once a match is found it is cached, and from then on out mappings will used the cached version.  It runs through the where the first time because there is no matching Mapper cached.
2. Explicit source type is not supported.  I don't know of any use cases supporting either way on this.
