### ISSUE TITLE
Am I doing maps to constructors wrong?

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1023]
I have two types somewhat like this:

```
public class Foo
{
    public string Foo { get; }
    public int Bar { get; }

    public Foo(string foo, int bar)
    {
        Foo = foo;
        Bar = bar;
    }
}

public class Baz
{
    public string Foo { get; set; }
    public int Bar { get; set; }
}
```

For these, I create a mapping using a profile, in which I have

```
CreateMap<Baz, Foo>();
```

`Mapper.AssertConfigurationIsValid()` doesn't complain, but when I try to map a `Baz` instance to `Foo` I get an error stating 

> Type needs to have a constructor with 0 args or only optional args
> Parameter name: type.

I was under the impression that AutoMapper would be able to map the properties of `Baz` onto the constructor arguments of `Foo`, but apparently not. Am I doing something wrong or stupid here?

**Comment by lbargaoanu** [comment]
It should work. Did you try the latest from MyGet?

**Comment by tlycken** [comment]
Yes, this is on version 4.1.1.

**Comment by lbargaoanu** [comment]
So MyGet, not NuGet, right? :)

**Comment by tlycken** [comment]
Oh, sorry. No, NuGet. I can try MyGet when I get back to work tomorrow, if it matters.

**Comment by tlycken** [comment]
Back to work now. With version 4.2.0-ci-1038, I get the same behavior.

I'm trying to build a MWE that reproduces the problem, but I'm not getting the error there, so it's likely this is something in my actual mappings that's not working, and not an issue with AutoMapper. I'll keep trying and get back with the results, whether this is a bug or PEBKAC.

**Comment by tlycken** [comment]
OK, I found the culprit. This works:

```
// DTOs

public class Foo
{
    public string Bar { get; set; }
    public int Baz { get; set; }
}

public class Qux
{
    public string Bar { get; }
    public int Baz { get; }

    public Qux(string bar)
            : this(42, bar)
    {
    }

    public Qux(int baz, string bar)
    {
        Bar = bar;
        Baz = baz;
    }
}

// in mapping profile
CreateMap<Foo, Qux>();

// main program
Mapper.AddProfile<MapperProfile>();

var foo = new Foo
{
    Bar = "bar",
    Baz = 17
};
var qux = Mapper.Map<Qux>(foo);
```

If I remove the `Baz` property from the `Foo` DTO, it doesn't work anymore, even though there is a constructor for `Qux` where all arguments can be satisified.

**Comment by lbargaoanu** [comment]
Kind of subtle and you can easily workaround it. But I'll take a look.

**Comment by tlycken** [comment]
What's a good workaround? Is there one that still lets me have the optional argument first (since that really makes much more sense in my actual application)?

**Comment by lbargaoanu** [comment]
I would try ConstructUsing.

**Comment by tlycken** [comment]
I haven't found a way to use ConstructUsing that doesn't require me to explicitly specify all the parameters. If I have to do that, I might as well not use AutoMapper...

**Comment by lbargaoanu** [comment]
Hopefully you use it for other things too :)

**Comment by tlycken** [comment]
I do, which is why I want this to work too :)

The reason I'm trying to get this to work is that we want the types that I'm mapping to to be immutable, so we give them get-only properties which are initialized from the constructor. This specific type, and a few others like it, have an optional Id property, which should either be provided in a constructor argument, or be `null` (and stay `null`). All other properties are mandatory.

Since we do all other transformations of this kind in AutoMapper, it would be a shame if we couldn't do that here either - if for no other reason, then because of consistency across the code base. (And we're probably moving towards more such immutable types, so the scenarios where AutoMapper can be used will then become less and less if this isn't implemented...).

**Comment by lbargaoanu** [comment]
Apparently even a constructor with an optional parameter doesn't work so I think we have something here.

    public Qux(string bar, int baz=42)

**Comment by tlycken** [comment]
Yeah; I guess the error message is to be interpreted very literally. With some emphasis:

>  needs to have a constructor with *0 args* or *only* optional args

Without having inspected the internals, I guess this implies that AutoMapper *always* uses an argument-less constructor, and then fills in the blanks (with reflection if it has to). I think it would be very valuable to support also true mapping to constructor arguments, but I realize it might be more work than I thought this would be when I filed the issue.

**Comment by lbargaoanu** [comment]
No, it does the mapping, but not in this case.

**Comment by lbargaoanu** [comment]
So would optional parameters solve your case? Because this seems easy to do.

**Comment by tlycken** [comment]
Sure, if it's OK that not all parameters are optional :) In other words, requiring `public Qux(string foo, int bar = 17)` is perfect, requiring `public Qux(string foo = null, int bar = 17)` doesn't help.
