### ISSUE TITLE
Translating include properties from ViewModel to model include properties

### ISSUE THREAD

**Issue by vacho2** [AutoMapper/AutoMapper#1027]
Hi,

Is it possible to map `List<Expression<Func<TEntity, object>>> to List<Expression<Func<TViewModel, object>>>` ?

**Comment by TylerCarlson1** [comment]
You should be able to call `Mapper.Map<List<Expression<Func<TEntity, object>>>, List<Expression<Func<TViewModel, object>>>>(expressionList);` as long as there's a map for TEntity to TViewModel.

If not then you can call `expressionList.Select(Mapper.Map<Expression<Func<TViewModel, object>>>);`

If you are talking about EF's `Include(string property)` function I don't think it translates that.

**Comment by vacho2** [comment]
No, that does not work. I am still getting this exception.
`System.InvalidCastException: Unable to cast object 
of type 'System.Linq.Expressions.Expression`1[System.Func`2[EngageSales.Entities.Contests.Score,EngageSales.Entities.Users.User]]' 
to type 'System.Linq.Expressions.Expression`1[System.Func`2[EngageSales.Entities.Contests.Score,System.Object]]'.`
Am I missing somethig?

**Comment by vacho2** [comment]
I am still getting this Exception:
of type 'System.Linq.Expressions.Expression`1[System.Func`2[Score,User]]' 
to type 'System.Linq.Expressions.Expression`1[System.Func`2[Score,System.Object]]'.

**Comment by TylerCarlson1** [comment]
Can you provide an example of you code that's creating this exception?
Creating the maps for the objects and the mapping of expressions?

**Comment by vacho2** [comment]
Hier is sample application:
http://codepaste.net/kwh6ah
I hope you can help me

**Comment by TylerCarlson1** [comment]
If you do this it works
```
Expression<Func<ScoreVM, UserVM>> expressionVM = x => x.User;
var expression = Mapper.Map<Expression<Func<Score, User>>>(expressionVM);
```
Or this
```
Expression<Func<ScoreVM, object>> expressionVM = x => (object)x.User;
var expression = Mapper.Map<Expression<Func<Score, object>>>(expressionVM);
```

Also in 4.2 you won't need `var score = Mapper.Map<Score>(scoreVm);` in order to do the expression mapping.

And I'm curious why do you need to map Expressions to objects explicitly like this?
Most of times this Expression mapping is wrapped around other functions that use it.

**Comment by vacho2** [comment]
I need this to propage include properties for entity framework from service layer to GenericRepository.
It there any way to convert it automaticaly to object? I do not want to cast it to object for each include property

**Comment by TylerCarlson1** [comment]
Sorry I have no idea how you would do that.  I don't use Include myself.

Are you able to use `ProjectTo()`?  It might remove the need for Include in your queries

**Comment by vacho2** [comment]
No I not. At the service layer am working with IEnumerable. 
There am I already disconected from database.
Is there any way to tell automapper to cast it to object automaticaly?

**Comment by TylerCarlson1** [comment]
Not that I can think of.  This most likely is a bug.

**Comment by jbogard** [comment]
You might want to watch this:

https://vimeo.com/131633177

All those layers and abstractions are gonna be problems for you one day.

**Comment by vacho2** [comment]
It's about reusability. I don't want to write the same code hundert time.
Any idea how to accomplish my task?

**Comment by jbogard** [comment]
What code for the hundredth time? What I'm missing is what you're trying to do with a generic repository. What does that look like?

**Comment by vacho2** [comment]
I will prepare some sample solution for you. Just give me some time :)
