### ISSUE TITLE
UseAsDataSource and reverse mapping

### ISSUE THREAD

**Issue by liquidsnk** [AutoMapper/AutoMapper#1028]
Documentation on UseAsDataSource seems to imply that AutoMapper will figure out how to map an expression directed at (in the example) an OrderLineDTO to an expression meant for an OrderLine: https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)
And it will do so having only a mapping defined from OrderLine to OrderLineDTO and not the other way around.

However, my experience trying this is that it will fail, and even AutoMapper tests are mapping the reverse:
https://github.com/AutoMapper/AutoMapper/blob/develop/src/UnitTests/Query/SourceInjectedQuery.cs#L38

Am I missunderstanding the documentation or is this just a problem with it? Or the idea is that this scenario should work?

**Comment by TylerCarlson1** [comment]
I think you are right.  The documentation is incorrect.  For `UseAsDataSource` to work properly you need mapping both ways.
OrderLine to OrderLineDTO is for the Project.To part
OrderLineDTO to OrderLine is for Expression Translation

**Comment by jbogard** [comment]
Can you update that?

**Comment by TylerCarlson1** [comment]
Oh yea sorry did that already.  Made map both ways in the example.

**Comment by liquidsnk** [comment]
Thanks!

**Comment by liquidsnk** [comment]
I know that I've closed this already. But an additional minor suggestion for this at the moment would be to perform some extra validations on the expression translation source. 
Currently when the discussed required mapping is not present it throws NullReferenceException in some situations and other kind of internal exceptions that could be avoided by checking that the mapping exists.
Just to keep in mind. Thanks again!
