### ISSUE TITLE
Automated performance testing of user mapping configs?

### ISSUE THREAD

**Issue by platinumazure** [AutoMapper/AutoMapper#1032]
I was wondering if there existed any sort of performance benchmarking tool for checking performance of mapping configurations (conceptually similar to the `AssertConfigurationIsValid` method available for validating mapping configurations).

Ideally, this would manifest as a method which would iterate through the known config, generate fuzz values for model types, and runs each mapping configuration a few times, outputting the runtimes and mean runtime for each configuration. It would also be nice to be able to run this repeatedly on one mapping config which is being actively tuned, so that the user can get feedback quickly.

I'm aware that there are a few potential snags right off the bat, such as dealing with mapping profiles and the aforementioned fuzz generation (I can admit that's more nice to have). But surely this is still worth considering, even if it might take a while to fully implement? (Or, if I'm really lucky, this has already been done :smile:)

**Comment by TylerCarlson1** [comment]
Source code has a BenchMark project which should do something like this.

**Comment by platinumazure** [comment]
I've taken a quick look and will take a better look tonight.

The key question for me remains, "does that support testing user configurations?" The Program.cs class news up different mappers (I assume internal implementations of the mapper interface?) and runs benchmarks on those- again I'd love to see that done on user defined `Mapper.CreateMap()` configurations.

Anyway, thanks for the pointer. I will dig more in that area.

**Comment by platinumazure** [comment]
Sorry for dropping the ball on this.

I did take a look. Unfortunately, AutoMapper only tests hardcoded mapping configurations using specific mappers and value resolvers.

I would be very interested in seeing some functionality added for testing user configurations. Basically, it would work like this:

1. API would be something like `Mapper.TestMappingPerformance<TSource, TDestination>()`
1. Generate an instance of the source type
1. Start a Stopwatch
1. Map to the destination type
1. Stop the Stopwatch
1. Do this a few times and get min/max/average, per benchmarking best practices
1. Return an object with appropriate results

And it would also be nice to have an API, something like `Mapper.TestAllMappingsPerformance()` which iterates through the mapping config and runs the individual performance method, and returns a list or dictionary of results.

The challenge is to ensure that a meaningful mapping is done by supporting auto-generation of property values that are not just default values. This could be done using reflection-- simpler types, such as strings, just get random values (e.g., a GUID); more complex types would new up the object and recursively apply the same steps to its subtypes.

Would there be any interest whatsoever in exploring this further, in this project? Or should I look into creating a separate project for this?

**Comment by TylerCarlson1** [comment]
I don't know, maybe @jbogard might know.

What the benchmark does is goes against a gold standard, hard coded, to get a metric of Slowdown Automapper causes.  When you benchmark it to itself, what does that say other than it took a long time or short time to do?  It doesn't tell you if it's slow because it takes a long time, or it's slow because of AutoMapper's implementation.  Benchmark could be expanded on to cover more scenarios to get a metric of flattening, collection maps, ect.

I guess you can identify slow maps, and try re mapping to get better results, but at that point you might just want to hard code things, if performance is that much of an issue.

**Comment by jbogard** [comment]
Separate project would be a start, I think!
