### ISSUE TITLE
IMappingOperationOptions for DynamicMap?

### ISSUE THREAD

**Issue by cervengoc** [AutoMapper/AutoMapper#1033]
Hello, is it possible to support passing an `IMappingOperationOptions` initializer action when using the `DynamicMap` functions? Now the appropriate overloads are available only for standard `Map` functions.

Looking into the code it seems to be possible to implement easily, but before I might create a PR I'd like to know if it was intentional not to support it there, and if yes, why.

Also, it would be nice to have this customization ability in the non-generic mapping methods too, of course using the non-generic `IMappingOperationOptions` interface.

**Comment by lbargaoanu** [comment]
DynamicMap is Map with CreateMissingTypeMaps true, so you can use that instead. DynamicMap is being deprecated.

**Comment by cervengoc** [comment]
I see, thank you for the information. However, still there is no overload for non-generic `Map` functions which would take such an options initializer..

**Comment by lbargaoanu** [comment]
Perhaps you need to [upgrade](https://github.com/AutoMapper/AutoMapper/blob/94135637549f42e48d68dde95857738d5752b5b9/src/AutoMapper/Mapper.cs#L133)?

**Comment by cervengoc** [comment]
Sorry my eyes have tricked me in my IDE when reading through the overload list. Yes it's there indeed. Thank you for the answer again, I'm gonna close this now.
