### ISSUE TITLE
IDataRecord To Class Maps Default Values

### ISSUE THREAD

**Issue by MrGold** [AutoMapper/AutoMapper#1035]
I have been using AutoMapper  without any issues so far. However , currently  i am having  an issue  which i've spent quite much time to solve it, yet couldn't come up with a solution.   When I try to map IDataRecord to a custom class  , it  maps with default values only.It doesn't throw exception but it also doesn't map properly. Since it doesn't throw any exception, i cannot find the problem.Here is my code ;

Custom Class Definition 
```C#
//Custom Class Definition 
    public class PhoneMessage
    {
        public Guid MessageID { get; set; }
        public Guid UserID { get; set; }
        public string PhoneNumber { get; set; }
        public string MessageContent { get; set; }
        public DateTime CreatedOn { get; set; }

        public override string ToString()
        {
            return string.Format("MessageID:{0} , UserID:{1}, PhoneNumber:{2}, MessageContent:{3}, CreatedOn:{4}",
                MessageID, UserID, PhoneNumber, MessageContent, CreatedOn);
        }
    }
```

Here is the code to  fetch data and map to the class definition

```C#
 static void Main(string[] args)
        {
            Mapper.Reset();
            Mapper.CreateMap<IDataRecord, PhoneMessage>();
            DataSet ds = FetchData();

            IDataReader reader = ds.Tables[0].CreateDataReader();
            List<PhoneMessage> list = new List<PhoneMessage>();

            while (reader.Read())
            {
                //Here it maps, throws no exception but maps with default values
                PhoneMessage result = Mapper.Map<IDataRecord, PhoneMessage>(reader);
                list.Add(result);
            }

            foreach (PhoneMessage msg in list)
            {
                System.Console.WriteLine(msg.ToString());
            }

        }
        private static DataSet FetchData()
        {
            const string query = "SELECT *FROM [dbo].[AS.PhoneMessage](nolock)";
            Database db = DatabaseFactory.CreateDatabase();
            DataSet ds = null;

            using (DbCommand command = db.GetSqlStringCommand(query))
            {
                ds = db.ExecuteDataSet(command);
            }

            return ds;
        }
```

Even DataSet returns full, it is not able to map to class. Here is data ;

![2](https://cloud.githubusercontent.com/assets/1638228/12427464/2aab968c-bee8-11e5-9a73-3aa9dbcb2e31.PNG)

And Map Result

![1](https://cloud.githubusercontent.com/assets/1638228/12427459/1c229dea-bee8-11e5-85c2-6007192c146c.PNG)

Funny thing is , this was working before!

By the way i am using  AutoMapper version  4.1.1.0

**Comment by MrGold** [comment]
Ok, i think,  the reason is,  i've upgraded all the nuget packages including AutoMapper, in my project recently. After searching among issues,  others also faced same problem and going back to   version 3.3.1 fixed the problem for now. I hope , i don't miss any performance fixes by  downgrading to  older version.

**Comment by TylerCarlson1** [comment]
https://www.nuget.org/packages/AutoMapper.Data/  Functionality has been moved out to seperate dll

**Comment by MrGold** [comment]
Thanks, nice to know  that i can still use the newest version. However, i couldn't find any code sample to use AutoMapper.Data to adopt my code to new version. I mean, I used to use it like ;


```C#
Mapper.CreateMap<IDataRecord, PhoneMessage>();
.....
....
PhoneMessage result = Mapper.Map<IDataRecord, PhoneMessage>(reader);
```

How shall i change this code  if  i use AutoMapper.Data ?

Thanks,

**Comment by TylerCarlson1** [comment]
You need to add this to your code (as shown in https://github.com/AutoMapper/AutoMapper.Data)
```
Mapper.Initialize(cfg => {
   MapperRegistry.Mappers.Add(new DataReaderMapper { EnableYieldReturn = true });
   // Other config
});
```
Then it should work the same way.

**Comment by MrGold** [comment]
Yeah, my bad i didn't see it. It is all working now! 
Thank you.
