### ISSUE TITLE
An empty integer collection doesn't map over a collection with values.

### ISSUE THREAD

**Issue by dougdanger** [AutoMapper/AutoMapper#1040]
void Main()
	{
		Mapper.CreateMap<SourceObj, TargetObj>();
		var target = Mapper.Map(new SourceObj(), new TargetObj());
	}
	
	class SourceObj
	{
		public int[] IntCollection { get; set; } = new int[0];
	}
	
	class TargetObj
	{
		public IEnumerable<int> IntCollection { get; set; } = new[] {1,2,3,4,5};
	}

The expectation is that `TargetObj` will have an empty array after mapping. Instead it has an array of the original length, but all items are set to the default.

![automapper_output](https://cloud.githubusercontent.com/assets/11986285/12523284/e91fe072-c123-11e5-80a1-e4856aea806a.PNG)

**Comment by lbargaoanu** [comment]
As a workaround you can use int[] in the destination.

**Comment by lbargaoanu** [comment]
This seems to work on develop.
