### ISSUE TITLE
Mapping to base class does not work

### ISSUE THREAD

**Issue by sds88** [AutoMapper/AutoMapper#1046]
I have three classes and their maps set up as follows:

    public class Input {...}
    public class A {...}
    public class B : A {...}

    Mapper.CreateMap<Input, A>()
      .ForMember(...)
      .Include<Input, B>();
    Mapper.CreateMap<Input, B>()
      .ForMember(...);

Whenever I try to map to object A via `Mapper.Map<A>(input);`, I get back an object of type B.

**Comment by lbargaoanu** [comment]
This seems to work on develop.
