### ISSUE TITLE
CreateMapExpression doesn't handle inheritance

### ISSUE THREAD

**Issue by kierenj** [AutoMapper/AutoMapper#1051]
`CreateMapExpression` works great, but not when the source/destination classes are abstract base types and valid derived type maps exist.

(To clarify: it generates an expression which wants to create an instance of the abstract destination class, and populate the members.  It doesn't take into account derived classes.)

I wanted to check whether this was known/planned/obsolete behaviour?

My intention is to write a helper to generate expressions which will check the source object's type and involve the relevant subtype's map expression.  Would this be helpful to share when complete?

**Comment by lbargaoanu** [comment]
#1011 I suppose. If that's the case, you can close the issue.
