### ISSUE TITLE
CreateMap is depricated

### ISSUE THREAD

**Issue by Borgas77** [AutoMapper/AutoMapper#1052]
How do i migrate following code in best way!
F is from type T is To type

```
 AutoMapper.Mapper.CreateMap<F, T>();
```

**Comment by jbogard** [comment]
I'm writing that wiki page right now!

**Comment by Borgas77** [comment]
Can you post back when you have written the wiki

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Migrating-from-static-API
