### ISSUE TITLE
NuGet issue

### ISSUE THREAD

**Issue by HaukiDog** [AutoMapper/AutoMapper#1054]
Trying to install latest in VS2015:

Could not install package 'AutoMapper 4.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by TylerCarlson1** [comment]
You class is most likely .NET 4.0 or lower.  Those aren't supported anymore.  If you upgrade to 4.5 it should work.

**Comment by jbogard** [comment]
Yep, I couldn't support Profile259 because I didn't want to support Windows Phone Silverlight any more.

**Comment by jbogard** [comment]
Doing Net Standard Platform 1.1 now.
