### ISSUE TITLE
GetMemberType?

### ISSUE THREAD

**Issue by Mike-EEE** [AutoMapper/AutoMapper#1061]
I just upgraded to 4.2.0 and I am seeing an extension method that I was using "GetMemberType( MemberInfo )" is now missing and is my build is breaking as a result of it (the sads). I did a quick search on this and didn't see anything. Of course, I am not a very good searcher and am generally lazy so I am posting here now. :) Is there a reason why this was removed instead of deprecated with a message on how to reconcile?

**Comment by jbogard** [comment]
I had marked it internal (mostly because I'm trying to not pollute with extension methods). I can mark it not-internal.

**Comment by Michael-DST** [comment]
Oh yeah... I just realized it was exactly that (internal) -- had to clear ReSharper classes to see it.  Yeah, that is a handy method for PCLs if you don't mind. :)  However, I also am in agreement with your concern for pollution.  Maybe make a public adapter method/class?

**Comment by Michael-DST** [comment]
The other option, since it's such a minor method, is to copy/paste it and [duplicate it in a dependent code base](https://github.com/DevelopersWin/VoteReporter/blob/master/Framework/DragonSpark/Extensions/TypeExtensions.cs#L14-L23).  But that is technically breaking DRY, so whatever works for you.

**Comment by TylerCarlson1** [comment]
I've had my share of problems with things now becoming internal.  This is more of me getting fancy with Member expression conventions.  Example of CultureInfoLocilization member convention in #983 uses `GetMemberType()` so would need to copy code to make it work.

I can see the internals only being usefully if you try to make special member conventions or other extensions that get down and dirty into the internal stuff.
