### ISSUE TITLE
Nonstatic mapper architecture question

### ISSUE THREAD

**Issue by Scratch-net** [AutoMapper/AutoMapper#1063]
Hi!
Previously we had several projects and each of them had a startup section which registered its own mappings.
Now when I create an instance of MapperConfiguration I cannot add any more mappings to it.

So, how it should be done properly if we want to have a single mapper instance/multiple config sections per solution?

**Comment by lbargaoanu** [comment]
You can have a profile per module and then register all of them when you construct the mapper singleton.

**Comment by Scratch-net** [comment]
And how should it look like? Could you give an example please?

**Comment by lbargaoanu** [comment]
[They are easy to find.](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=addprofile)
You can do it explicitly or you can register the profiles with your DI container through a convention and then pass them to the MapperConfiguration with something like GetServices< Profile >() if your container supports this.

**Comment by Scratch-net** [comment]
Thanks a lot, I will give it a try

**Comment by lbargaoanu** [comment]
See also https://github.com/AutoMapper/AutoMapper/wiki/Migrating-from-static-API
