### ISSUE TITLE
Static API Removed?!?!

### ISSUE THREAD

**Issue by TonyValenti** [AutoMapper/AutoMapper#1064]
Hi AutoMapper Team,
I love what you do!  I'm looking forward to upgrading to V5 but I just learned that one of my favorite APIs is going away.  I am hoping that you have some guidance on how to migrate.

We have a ton of different classes in our project, and in order to make things easier for us to manage, we have decentralized our mappings.  Let me give you an example:

````
namespace ConsoleApplication17 {
    class Program {
        static void Main(string[] args) {
            var ret = GetDest();

        }

        public static DestClass GetDest() {
            var Source = new SourceClass() { Id = 37, Name = "Tony Valenti" };
            var Dest = new DestClass();

            var ret = AutoMapper.Mapper.Map(Source, Dest);
            return ret;
        }
    }

    public class SourceClass {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class DestClass {
        public int Id { get; set; }

        public string Name { get; set; }

        static DestClass() {
            AutoMapper.Mapper.CreateMap<SourceClass, DestClass>();
        }
    }
}
````

You'll notice that we're creating our mapper in DestClass's static initializer.
How can we implement this pattern in V5?

Also, as a side note, the one thing that we don't like about what we're doing now is that we have to do:
````
var Dest = new DestClass();
````
First before calling the Map that way the static initializer gets called first. It would be great if AutoMapper new'ed up the destination type first before searching for a map that way we could eliminate that line too.

**Comment by lbargaoanu** [comment]
See #1063 :)
You don't have to create the destination. AutoMapper will do that for you with Map< Destination >(source).

**Comment by jbogard** [comment]
It's back.
