### ISSUE TITLE
IncludeBase configuration fails in MapperConfiguration; passes in Mapper.Initialize

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#1069]
Consider the following setup:

	public abstract class BaseSource
	{
		public PropertyValue Properties { get; set; }
	}
	public class Source : BaseSource { }

	public class PropertyValue { }
	public class PropertyValueModel { }

	public abstract class BaseTarget
	{
		public PropertyValueModel PropertyValues { get; set; }
	}
	public class Target : BaseTarget { }

and the following mappings:

    cfg.CreateMap<PropertyValue, PropertyValueModel>();
    cfg.CreateMap<BaseSource, BaseTarget>()
        .ForMember(dest => dest.PropertyValues, opt => opt.MapFrom(src => src.Properties));
    cfg.CreateMap<Source, Target>()
	.IncludeBase<BaseSource, Target>();

Under 4.2.0, these mappings do not pass as valid using the new MapperConfiguration class, but do work using the old static Mapper.Initialize:

	[TestMethod]
	public void TestInstance()
	{
		var config = new MapperConfiguration(cfg =>
		{
			cfg.CreateMap<PropertyValue, PropertyValueModel>();
			cfg.CreateMap<BaseSource, BaseTarget>()
				.ForMember(dest => dest.PropertyValues, opt => opt.MapFrom(src => src.Properties));
			cfg.CreateMap<Source, Target>()
				.IncludeBase<BaseSource, Target>();
		});

		config.AssertConfigurationIsValid();
	}

	[TestMethod]
	public void TestStatic()
	{
		Mapper.Initialize(cfg =>
		{
			cfg.CreateMap<PropertyValue, PropertyValueModel>();
			cfg.CreateMap<BaseSource, BaseTarget>()
				.ForMember(dest => dest.PropertyValues, opt => opt.MapFrom(src => src.Properties));
			cfg.CreateMap<Source, Target>()
				.IncludeBase<BaseSource, BaseTarget>();
		});

		Mapper.AssertConfigurationIsValid();
	}

I'm not sure what it is about the mapping setup here that is causing the problem.  This example is a much-simplified version of my production code which broke when moving to 4.2 - I cut it down as much as possible to keep the test failing.  The mapping error is as follows:

```
AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
=======================================================
BaseSource -> Target (Destination member list)
UnitTestProject6.BaseSource -> UnitTestProject6.Target (Destination member list)

Unmapped properties:
PropertyValues
===================================================
Source -> Target (Destination member list)
UnitTestProject6.Source -> UnitTestProject6.Target (Destination member list)

Unmapped properties:
PropertyValues
```

**Comment by lbargaoanu** [comment]
It should be

        cfg.CreateMap<Source, Target>()
            .IncludeBase<BaseSource, BaseTarget>();

**Comment by richardlawley** [comment]
Hmm, Good spot.  The bug may still be present, my mapping code which worked in 4.1.1 definitely broke in 4.2.0 - I thought I'd narrowed it down to this.  I'll open another bug if I can pinpoint the problem.
