### ISSUE TITLE
Cannot specify Inner Mapping Using IMapperConfiguration

### ISSUE THREAD

**Issue by stricq** [AutoMapper/AutoMapper#1070]
Using the static API, I would do this:

`.ForMember(dest => dest.Value, opt => opt.ResolveUsing(src => Mapper.Map<DomainNameTableIndex>(src.Value)))`

Where Value is of type object  but is always a specific type on specific subclasses.  Using IMapperConfiguration, I cannot specify a map within the ResolveUsing.

Also, Value conflicts with a property on ResolutionResult and prevents me from using ResolveUsing.  The above line of code won't compile because src.Value is an ambiguous reference.

I used this code:

`.ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Value as NameTableIndex))`

But this does not perform any mapping on src.Value to get it mapped to the destination's property.

**Comment by lbargaoanu** [comment]
opt.ResolveUsing((ResolutionResult r)=>r.Context.Engine.Mapper.Map<PropertyValueModel>(new PropertyValue()));

**Comment by stricq** [comment]
That would seem to work but I keep getting conflicts on the Value property.  I can't cast it because it's never the right type between compile time and runtime.  Either it won't compile or it is a runtime error.

`.ForMember(dest => dest.Value, opt => opt.ResolveUsing(src => src.Context.Engine.Mapper.Map<DomainNameTableIndex>((NameTableIndex)src.Value)))`

At runtime `src.Value` is my source object, NOT the Value property of my source object.  And `(NameTableIndex)((ResolutionResult)src.Value).Value` still comes out to be the source object at runtime and not the Value property of my source object.

I really don't want to have to change all the subclasses (there are many) property of Value to a different name just to get around AutoMapper weirdness of combining two objects into o

**Comment by stricq** [comment]
I finally got the right cast in place.  This works:

`opt => opt.ResolveUsing(src => src.Context.Engine.Mapper.Map<DomainNameTableIndex>(((PropertyByteValue)src.Value).Value))`
