### ISSUE TITLE
Argument type 'IMapper' is not CLS-compliant

### ISSUE THREAD

**Issue by eddiepaz** [AutoMapper/AutoMapper#1072]
Any plans to make this CLS-compliant? I just added the IMapper to my ctor to inject my configuration, and this popped up.

**Comment by jbogard** [comment]
Ah, are you using different CLR languages or shipping a public library
marked as CLS compliant?

**Comment by jbogard** [comment]
Well nuts, I had the file in there but it looks like it was getting picked up by the compiler, not sure why. It's marked as CLS compliant for 5.0.

**Comment by jbogard** [comment]
Done!
