### ISSUE TITLE
Keep Mapper.Map static method

### ISSUE THREAD

**Issue by serbrech** [AutoMapper/AutoMapper#1074]
I just upgraded a solution to use 4.2.0 and it is very painful, as we treat warning as errors.
I understand that having the whole api on the static Mapper class was not ideal. And I myself don't like the Mapper.CreateMap api. It makes it too easy to write messy mapping configuration all over the system, and making it impossible to maintain over time on large solutions.

However, I don't think that the Mapper.Map method should go.

### Just create your own static class
Sure we can create our own static Mapper class. Unfortunately, when a project grows into multiple libraries, you have to make sure that you initialize AutoMapper at the root of the app (bootstrapper). but you also often map at lower layers in other libraries :

- **Root** : Entry point, references LibA and LibB. Finds all profiles, initialize AutoMapper, initialize the static Mapper.
     - **LibA**: has Profiles, and use Mapper.Map(...)
     - **LibB** : has some other profiles and use Mapper.Map()

Our static Mapper class must be initialized in Root, but LibA and LibB cannot reference Root. So we  have to create this in yet another library that everyone will reference (AutoMapper.Static?).
We dont want to have a static Mapper class in each library. if automapper provide the static class, it can control the initialization, and removes this pain point.

### Updating AutoMapper
The other issue with marking it obsolete, is with large projects that have been using AutoMapper for a while.
They are in the situation presented above, happily using Mapper.Map. Now they have to update thousands of lines from a static usage, and inject the mapper instead. This is a very invasive change that can potentially create _runtime_ bugs if not done carefully.
This will delay, or prevent an updates of AutoMapper.

## Suggestion
My suggestion is to remove, CreateMap to force a centralized configuration with the new api, but to keep the static Mapper.Map functions as helpers. It should be encouraged in the documentation and all exemples, to inject and create specific instances of IMapper.

Should there be a separate package for these helpers? _Automapper.Static_? That would certainly make it a second choice for new development.

I personally don't think that injecting mappers brings much value compared to a static Map call. mapping is supposed to be stateless, and I dont want to clutter my constructor with unnecessary dependencies

**Comment by TylerCarlson1** [comment]
I wouldn't be surprised if people started making their own AutoMapper.Static.dlls and putting them on nuget to keep old functionality working.

**Comment by TylerCarlson1** [comment]
I've have some instances where I use Mapper.Map inside a profile.  Had to make a static instance to work around them.  Those are some weird cases though, and not that many.  I don't know if that's a common use case or not, but a lot of them are pretty old when learning how to use AutoMapper.

I would think making AutoMapper.Static go the way of Automapper.Data would be the best option.  No ambiguity in AutoMapper and when you go AutoMapper.Static you know what you are using it for.

Oh and definitely no CreateMap implementation.

**Comment by MattHoneycutt** [comment]
I'll second that.  For many applications, a single IMapper is all that will ever be needed.  Rather than everyone having to invent their own static class to house the IMapper, I'd rather see a static version shipped with AutoMapper.  I'd also like to see overloads of ProjectTo that will use this static instance, rather than requiring me to pass around a MapperConfiguration manually.  :)

**Comment by bp74** [comment]
I was very surprised to see such major API changes going from 4.1 to 4.2. If you do such major changes you should call it 5.0 or provide the static Mapper in a 4.2 version with useful compiler warnings.

**Comment by jbogard** [comment]
I heard ya. So I put it back in #1090.

Caveats - you MUST use Mapper.Initialize. Config is initialized once. Then you can call Mapper.Map.

Will this work?

**Comment by serbrech** [comment]
Yes, I think that's a perfect compromise :+1:

**Comment by jbogard** [comment]
Done.
