### ISSUE TITLE
IncludeBase failure in 4.2 (worked in 4.1 and below)

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#1075]
Since I upgraded to 4.2, some of my unit tests have been breaking on an AssertConfigurationIsValid.  I've now managed to cut down my classes to a minimum example necessary to reproduce the problem

Classes:

	public abstract class BaseBaseSource {	}
	public class BaseSource : BaseBaseSource {
		public string Foo { get; set; }
	}
	public class Source : BaseSource { }

	public abstract class BaseBaseDest {
		public string Foo { get; set; }
	}
	public class BaseDest : BaseBaseDest {	}
	public class Dest : BaseDest { }

Mapping Profile:

	public class TestProfile : Profile {
		protected override void Configure() {
			CreateMap<BaseSource, BaseDest>();
			CreateMap<Source, Dest>()
				.IncludeBase<BaseSource, BaseDest>();
		}
	}

Unit Test:

	[TestMethod]
	public void IncludeBase_AutoMapper42() {
		var config = new MapperConfiguration(cfg => cfg.AddProfile<TestProfile>());
		config.AssertConfigurationIsValid();
	}

	// [TestMethod]
	// public void IncludeBase_AutoMapper41() {
	//	Mapper.Initialize(cfg => cfg.AddProfile<TestProfile>());
	//	Mapper.AssertConfigurationIsValid();
	// }

Mapping failure error message:

> BaseBaseSource -> BaseBaseDest (Destination member list)
> AutoMapper42.BaseBaseSource -> AutoMapper42.BaseBaseDest (Destination member list)
> 
> Unmapped properties:
> Foo
> 

This test fails in AutoMapper 4.2, but passes in 4.1.1.  To reproduce this, it seems to require multiple levels of inheritance, and for the property being matched NOT to be at the same level.  For example, if you move Foo fo BaseBaseSource, the property is at the same level and the mapping works.

The problem disappears if you remove `.IncludeBase` (which in this case works because Foo is the same on both sides, but my full example requires mapping statements).

**Comment by lbargaoanu** [comment]
Short answer

    CreateMap<BaseBaseSource, BaseBaseDest>().ForMember(d=>d.Foo, o=>o.Ignore());

**Comment by richardlawley** [comment]
This is a MUCH simplified example, the minimum necessary to reproduce the problem for the issue report.  As far as I can tell, this code *should* work, and indeed did work prior to 4.2

**Comment by lbargaoanu** [comment]
The problem is that IncludeBase will create the base mappings for you. That is, all the base mappings in 4.2. And in this case the mapping it creates is not valid and it complains. #1069 was also possible because it created the base mapping you said, not the base mapping you wanted.

**Comment by lbargaoanu** [comment]
#911 made sense so it was fixed. I'm not sure why IncludeBase _creates_ the base mappings. @jbogard should know. But if we assume both these things, it's the right behavior.

**Comment by richardlawley** [comment]
#1069 was a previous attempt to make a reproducible version of this bug - my code was wrong, I accepted that.

I'm going to update my code to use the same terminology as #911 before continuing the discussion.

**Comment by lbargaoanu** [comment]
That's not the point :) The point is that AutoMapper might have reported the missing map, but it didn't. It created a new one and that's why the error was even possible.

**Comment by richardlawley** [comment]
Classes:

	public abstract class SourceLevel0 { }
	public class SourceLevel1 : SourceLevel0 {
		public string SProperty1 { get; set; }
	}
	public class SourceLevel2 : SourceLevel1 { }

	public abstract class DestLevel0 {
		public string DProperty0 { get; set; }
	}
	public class DestLevel1 : DestLevel0 { }
	public class DestLevel2 : DestLevel1 { }

Mapping Profile:

	public class TestProfile : Profile {
		protected override void Configure() {
			CreateMap<SourceLevel1, DestLevel1>()
				.ForMember(dest => dest.DProperty0, opt => opt.MapFrom(src => src.SProperty1));
			CreateMap<SourceLevel2, DestLevel2>()
				.IncludeBase<SourceLevel1, DestLevel1>();
		}
	}

This is different from #911 in the following ways:
* No explicit mapping from SourceLevel0 to DestLevel0 as these are both abstract
* SProperty1 is mapped to DProperty0

It seems that before this behaviour changed, IncludeBase would happily flatten the SourceLevel1 - DestLevel1 mapping to include inherited properties - something that still happens if I map SourceLevel2 to DestLevel2 while specifying the individual property.

I don't understand what you mean by automapper creating the missing map - there is no missing map from what I can see, but it seems to WANT a map between the two abstract classes at level 0.

**Comment by lbargaoanu** [comment]
Foo is a member of Dest through level 0. The level 0 map is missing. If you create it, the issue disappears, otherwise AutoMapper creates a default one that is invalid.

**Comment by richardlawley** [comment]
Pre-4.2, the Level 0 map was not required.  Your reasoning would make sense to me if the Level1 mapping was the problem, but removing the Level2 mapping from the profile causes the test to pass.

Pre 4.2, using .IncludeBase would just include the valid mapping defined for Level1 (which already includes Level0).

Now it seems to need a mapping which appears to be redundant - I'll never try and map to DestLevel0 as it's abstract, and I have to explicitly Ignore the property and then re-map it later on.

**Comment by lbargaoanu** [comment]
You don't have to re-map. Add the missing map and it works.

**Comment by richardlawley** [comment]
I think we're going round in circles.  The Level0 map is not needed by the Level1 map (remove the Level2 map and the profile is valid).  The Level0 map IS needed by the Level2 map which is trying to include Level1.

Behaviour of `IncludeBase` has changed from "Include how to map SrcLevel1 to DestLevel1" to "Include how to map SrcLevel1 to DestLevel1 **except inherited properties**".  If this is intentional then I think this was a confusing decision to make.  If it was not intentional, then this is a bug.

**Comment by jbogard** [comment]
No it's not intentional, but I think I've restored the behavior in 5.0.

**Comment by Boychenko** [comment]
Looks like I've found issue related to this one. If it's not related I'll create separate one. Interesting that second map works without problems. Minimal example:
```
    [TestFixture]
    public class MappingTests
    {
        [Test]
        public void ShouldUseLevel0Mapping()
        {
            var config = new MapperConfiguration(
                cfg =>
                {
                    cfg.AddProfile<TestProfile>();
                });
            config.AssertConfigurationIsValid();
        }

        public class SourceLevel0
        {
        }

        public class DestinationLevel0
        {
            public int Ignored { get; set; }
        }

        public class DestinationLevel1 : DestinationLevel0
        {
        }

        public class SourceLevel1 : SourceLevel0
        {
        }

        public class SourceLevel2 : SourceLevel1
        {
        }

        public class TestProfile : Profile
        {
            protected override void Configure()
            {
                CreateMap<SourceLevel0, DestinationLevel1>()
                    .ForMember(x => x.Ignored, o => o.Ignore());
                CreateMap<SourceLevel1, DestinationLevel1>()
                    .IncludeBase<SourceLevel0, DestinationLevel1>();
                CreateMap<SourceLevel2, DestinationLevel1>()
                    .IncludeBase<SourceLevel1, DestinationLevel1>();
            }
        }
    }
```

**Comment by lbargaoanu** [comment]
@Boychenko It works with the MyGet build.

**Comment by Boychenko** [comment]
@lbargaoanu version 4.2?

**Comment by Boychenko** [comment]
As I understand MyGet version is 5.0. Am I right?

**Comment by lbargaoanu** [comment]
MyGet is always the latest version.

**Comment by mattzink** [comment]
We're seeing this as well, and I would expect almost any medium-large project to run into this. Is 5.0 imminent? If not, is the change @jbogard mentioned small enough to be backported for a patch release? I would be happy do a PR if somebody pointed out the 5.0 fix commit

**Comment by mueblo** [comment]
We have the same issue in our project. I agree with @mattzink, it would be nice to have this fix in a minor update.

**Comment by jbogard** [comment]
The fix is I completely rewrote the entire configuration code underneath
the covers. All the inheritance stuff was broken in many cases, working in
others, now it all works but with a rewrite. Stay on 4.1 for now I think.

**Comment by mattzink** [comment]
On 4.1.1, we're hitting a different IncludeBase related issue. We are currently on 3.3.1, but wanted to try newer versions since that version intermittently fails when mapping ISet<> to HashSet<>. I'll try the 5.0 prerelease bits next...

**Comment by sgwatgit** [comment]
I've run into this same issue. I'm going to be rolling back to 4.1.1 until 5.0 comes out because it would be a lot of work (that would be unnecessary on v5) to implement @lbargaoanu's fix.
