### ISSUE TITLE
Calling Map<T> from within a TypeConverter

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#1076]
Before 4.2, you could access the mapping engine from within a type converter:

    public TDest Convert(ResolutionContext context) 
    {
        TDest dest = new TDest();
        var temporaryResult = context.Engine.Map<Something>(context.Source.Prop1);
    }

Now that IMappingEngine no longer has the generic mapping methods, this code no longer works, and I can't see an easy way of calling Map<T> from within a type converter.  Is there a way of doing this?

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/1070#issuecomment-178484095).

**Comment by richardlawley** [comment]
That's actually not relevant here (I'm talking about use within a ITypeConverter).  However, I was looking at the wrong level (within context), I've found the Mapper on the IMapperEngine now, so I'll leave the solution here for anyone else who's missing it.  Might be worth adding to the 4.2 conversion wiki.

    var temporaryResult = context.Engine.Map<Something>(src.Prop1);

Changes to:

    var temporaryResult = context.Engine.Mapper.Map<Something>(src.Prop1);

**Comment by jbogard** [comment]
@richardlawley The wiki is editable by anyone, add away!
