### ISSUE TITLE
4.2.0 .Include<DerivedSourceType, DerivedTargetType> throws exception with base type names

### ISSUE THREAD

**Issue by PehrGit** [AutoMapper/AutoMapper#1077]
Creating a map and including a map which doesn't exist  throws an exception that doesn't really help find the missing map.

Consider the following:

`         

        public class SourceDerived
        {
        }

        public interface IMyInterface
        {
        }
       
        public class TargetDerived : IMyInterface
        {
        }

        [TestMethod]
        public void MyTestMethod()
        {
            var config = new MapperConfiguration(cfg =>
                cfg.CreateMap<object, IMyInterface>()
                    .Include<SourceDerived, TargetDerived>()
                );
        }
`
The test throws an exception with message : 

> System.InvalidOperationException: Missing map from Object to IMyInterface. Create using Mapper.CreateMap\<Object, IMyInterface>.

It is right to throw because I have not defined a map from SourceDerived to TargetDerived. 

In my opinion it would be much more helpful if the message read: 

> System.InvalidOperationException: Missing map from SourceDerived to TargetDerived. Create using Mapper.CreateMap\<SourceDerived , TargetDerived>.

@jbogard If you agree, I would happily provide a PR

**Comment by jbogard** [comment]
Anything that you "Include" has to include its own CreateMap call. Them's the rules.

**Comment by lbargaoanu** [comment]
@jbogard He means [this](https://github.com/AutoMapper/AutoMapper/blob/c8098f5591919abe13b480af659702c12a5da09c/src/UnitTests/Bug/ReportMissingInclude.cs#L14).

**Comment by jbogard** [comment]
![](http://i.imgur.com/tZOS8.gif)

**Comment by lbargaoanu** [comment]
:)

**Comment by PehrGit** [comment]
@lbargaoanu @jbogard That's sort of what I mean, but my point is actually that that test asserts that the message contains the names of the base type, not the derived type.

This: 

ex=>ex.Message.ShouldStartWith("Missing map from Object to **BaseType**."));

Should be, in my humble opinion:

ex=>ex.Message.ShouldStartWith("Missing map from Object to **ChildType**."));

**Comment by lbargaoanu** [comment]
Yes, the original test was wrong.

**Comment by PehrGit** [comment]
Yay I helped!
