### ISSUE TITLE
Dropped support for .NET 4.0 with 4.2.0

### ISSUE THREAD

**Issue by dittodhole** [AutoMapper/AutoMapper#1078]
With the recent "feature"-release, the support for .NET 4.0 was dropped. This really hurts projects that are stuck on .NET 4.0 (like the one I am working on), and furthermore ... it doesn't follow Semver.

Is there any chance to bring back the support?

**Comment by jbogard** [comment]
No, there isn't.

MS dropped support for .NET 4.0 last month. I also removed Silverlight 4 support. The reflection API completely changed from 4.0 to 4.5, and the shims I had added to support 4.0 were buggy and incorrect.

**Comment by dittodhole** [comment]
Unfortunately depending on Windows XP upwards, even Microsoft dropped support a while ago.
So, I am stuckon 4.1.1 :cry: 

Nevertheless, I would suggest you'd increased the major instead of the minor to reflect such breaking change. Even though the API kinda did not break.
