### ISSUE TITLE
How to construct MappingEngine?

### ISSUE THREAD

**Issue by gw79** [AutoMapper/AutoMapper#1080]
Hi Jimmy

I have some code that works OK with 4.1.1 constructing a ConfigurationStore, adding multiple profiles to it then passing it as a parameter to construct a MappingEngine.

I can switch out ConfigurationStore for MappingConfiguration OK but still no good...

MappingEngine's constructor has been changed in 4.2 to have an extra parameter of type IMapper in addition to an IConfigurationProvider. As far as I can tell, Mapper is the only implementation of IMapper, and it doesn't have a public constructor.

Please can you advise if there is a supported way to construct a MappingEngine in 4.2, and will things change further in version 5?  Can you expose the internal Mapper constructor, or even better reinstate the old MappingEngine constructor and have it create it's own Mapper?

Many thanks in advance, hope this makes sense.

Gareth

**Comment by lbargaoanu** [comment]
You should be able to replace the MappingEngine with a Mapper instance you get from MappingConfiguration.CreateMapper.

**Comment by gw79** [comment]
Sweet I'll try that in the morning thank you
