### ISSUE TITLE
Make create mapper more pure

### ISSUE THREAD

**Issue by scott-xu** [AutoMapper/AutoMapper#1081]
Hi @jbogard , what about removing the `CreateMapper` method from MapperConfiguration and make the Mapper's constructors public? Because it is the nature way to instantiate an object and is more convenient to be used in other DI frameworks.
Current: `config.CreateMapper()`
Expected: `new Mapper(config)`

**Comment by scott-xu** [comment]
Literally, config is config, it should not be a factory

**Comment by jbogard** [comment]
Yep, you can just do:

```
var config = new MapperConfiguration(cfg => { /* etc */ });

IMapper mapper = new Mapper(config);
```
