### ISSUE TITLE
Does AutoMapper.Data work by dependency AutoMapper 4.2

### ISSUE THREAD

**Issue by CyranoChen** [AutoMapper/AutoMapper#1082]
I had updated AutoMapper from 3.5.2 to 4.1.1 and separately with AutoMapper.Data 1.0.0-beta by Nuget a few month ago.

Now I try to update AutoMapper from 4.1.1 to latest version 4.2 for enjoying removing the static api. But I found that the usage of the AutoMapper.Data was obsolete and throw an exception when I ran the unit test of this.

Does AutoMapper.Data still work by dependency AutoMapper 4.2?

Any new extra suggestion on using AutoMapper.data by AutoMapper 4.2?

![screen shot 2016-02-04 at 20 31 32](https://cloud.githubusercontent.com/assets/6658407/12815002/4e9e27b0-cb7e-11e5-97f8-e6d58b9c3f17.png)

**Comment by AdamHayton** [comment]
Just updated an old project, have managed to get rid of all the statics, however I now face the same issue. Have managed to hack the code to get the record mapping working, MapPropertyValues method throws an error, I think this is because of the way CreateMissingTypeMaps works now. Any plans to update this? Thanks

**Comment by TylerCarlson1** [comment]
DataReaderMapper isn't compatible with 4.2's change IObjectMapper interface.

Changed from using ResolutionContext to TypePair, on IsMap, so it's incompatible.

P.S. @jbogard Accepts Pull Requests :)

**Comment by CyranoChen** [comment]
Any suggestions on this issue?

I have read an article on "Stop using Automapper in DataAccess Code." like this .http://www.devtrends.co.uk/blog/stop-using-automapper-in-your-data-access-code

So I think the Automapper.Data would probably not been updated in future.

The Automapper should be pure and just focus on in-memory object mapping.

**Comment by AdamHayton** [comment]
@CyranoChen I am currently updating the Automapper.Data, some of the tests are failing, once I have investigated and resolved why the are failing I will submit a pull request - provided I can work everything out. :)

**Comment by AdamHayton** [comment]
When mapping IDataRecord, the engine does not resolve the DataReaderMapper, if not mapped it will use the DataReaderMapper. Mapping an IDataReader does work, however the AssertConfigurationIsValid always fails as the members are unmapped.  So currently I am able to get it map an IDataReader providing that AssertConfigurationIsValid is not called. Does anyone have any pointers on what may need to be added / changed to get the configuration to validate?
