### ISSUE TITLE
Stackoverflow using AfterMap with custom collection types

### ISSUE THREAD

**Issue by long2know** [AutoMapper/AutoMapper#1083]
I have a custom collection that I use for pagination.  It inherits from `List<T>` like so:

```
public class PaginatedList<T> : List<T>
{
    public int PageNumber { get; set; }
    public int PageSize { get; set; }
    public int TotalCount { get; set; }
    public int TotalPages { get; set; }
    public string SortBy { get; set; }
    public string SortDirection { get; set; }
}
```

With version 3.x of AutoMapper, I would use an extension method to deal with instances of including a map of `PaginatedList<Src>` to `PaginatedList<Dest>` like this:

`Mapper.CreateMap<Type1, Type2>().IncludePagedResultMapping();`

The extension method code used AfterMap after specifying the paging members:

```
public static IMappingExpression<TSrc, TDest> IncludePagedResultMapping<TSrc, TDest>(this IMappingExpression<TSrc, TDest> expression)
{
    Mapper.CreateMap<PaginatedList<TSrc>, PaginatedList<TDest>>()
        .ForMember(dest => dest.PageNumber, opt => opt.MapFrom(src => src.PageNumber))
        .ForMember(dest => dest.PageSize, opt => opt.MapFrom(src => src.PageSize))
        .ForMember(dest => dest.TotalCount, opt => opt.MapFrom(src => src.TotalCount))
        .ForMember(dest => dest.TotalPages, opt => opt.MapFrom(src => src.TotalPages))
        .ForMember(dest => dest.SortBy, opt => opt.MapFrom(src => src.SortBy))
        .ForMember(dest => dest.SortDirection, opt => opt.MapFrom(src => src.SortDirection))
        .AfterMap((s, d) => AutoMapper.Mapper.Map<List<TSrc>, List<TDest>>(s, d));
    return expression;
}
```

With version 4.2 of AutoMapper, I have rewritten this extension method to take in the current configuration object and utilize a static reference to the config object in the AfterMap.  It looks like this now:

```
public static class AutoMapperConfig
{
	private static bool _mapped;
	private static IMapper _mapper;
	private static MapperConfiguration _config;
	public static IMapper Mapper { get { return _mapper; } }

	public static void RegisterMappings()
	{
		if (_mapped == false)
		{
			_mapped = true;
			_config = new MapperConfiguration(cfg => Configure(cfg));
			_mapper = _config.CreateMapper();
		}
	}
	
	private static void Configure(IMapperConfiguration cfg)
	{
		cfg.AllowNullCollections = true;
		cfg.CreateMap<Type1, Type2>().IncludePagedResultMapping(cfg);
	}
	
	public static IMappingExpression<TSrc, TDest> IncludePagedResultMapping<TSrc, TDest>(this IMappingExpression<TSrc, TDest> expression, IMapperConfiguration cfg)
	{
		cfg.CreateMap<PaginatedList<TSrc>, PaginatedList<TDest>>()
			.ForMember(dest => dest.PageNumber, opt => opt.MapFrom(src => src.PageNumber))
			.ForMember(dest => dest.PageSize, opt => opt.MapFrom(src => src.PageSize))
			.ForMember(dest => dest.TotalCount, opt => opt.MapFrom(src => src.TotalCount))
			.ForMember(dest => dest.TotalPages, opt => opt.MapFrom(src => src.TotalPages))
			.ForMember(dest => dest.SortBy, opt => opt.MapFrom(src => src.SortBy))
			.ForMember(dest => dest.SortDirection, opt => opt.MapFrom(src => src.SortDirection))
			.AfterMap((s, d) => Mapper.Map<List<TSrc>, List<TDest>>(s, d));
		return expression;
	}
}
```

Note the `Mapper ` static reference that replaces the older `AutoMapper.Mapper.Map` static method reference.  I have also tried `_config.CreateMap().Map(....)`.

The problem though is that once the AfterMap is executes reached, a stackoverflow exception occurs.  I'm currently at a loss to figure out how to approach or remedy this problem while still be being able to use AutoMapper 4.2 in the same manner as I  have been using 3.x.

**Comment by lbargaoanu** [comment]
Unless I'm missing something there is no easy way to do this. The StackOverflow happens because the Map call in AfterMap calls the map you're creating. The algorithm to find type maps changed to use the runtime types of the parameters. 
@jbogard I think the solution would be to find the type map explicitly and then map through the engine. So the mapper should expose it or the hook should receive the context. The latter makes sense, but it would be a breaking change.

**Comment by jbogard** [comment]
I don't think you need any of this, why don't you just create a type
converter?

cfg.CreateMap(typeof(PaginatedList<>),
typeof(PaginatedList<>)).ConvertUsing(typeof(PaginatedListMapper<>));

Then all that stuff you had in ForMember and AfterMap just goes into your
generic PaginatedListMapper. You don't need any of those extension methods.
Use the open generics to your advantage here.

**Comment by lbargaoanu** [comment]
The first problem is that the collection mapper has higher priority. But even if we solve this, we still have to map through the engine I believe. ITypeConverter passes the context, so that would be an advantage.

**Comment by jbogard** [comment]
Yep, it does, you shouldn't need to call outside the scope for a mapper.
Otherwise it should be similar to any of the other collection mappers -
don't map an IList, but loop through the items yourself.

**Comment by long2know** [comment]
OK. I'll give the open generics and type converter another try.

**Comment by long2know** [comment]
What does the signature of PaginatedListConvter<> need to look like for this to work?

I have tried a few variations of this, but the converter is never called:

```
cfg.CreateMap(typeof(PaginatedList<>), typeof(PaginatedList<>)).ConvertUsing(typeof(PagninatedListConverter<>));

public class PagninatedListConverter<T> : ITypeConverter<T, T>
{
    T ITypeConverter<T, T>.Convert(ResolutionContext context)
    {
        throw new NotImplementedException();
    }
}
```

I tried this too (type converter w/ src and dest type specification)

```
cfg.CreateMap(typeof(PaginatedList<>), typeof(PaginatedList<>)).ConvertUsing(typeof(PagninatedListConverter<,>));

public class PagninatedListConverter<T, V> : ITypeConverter<T, V>
{
    public V Convert(ResolutionContext context)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by lbargaoanu** [comment]
It won't be called. I think @jbogard was suggesting to map items one by one.

**Comment by long2know** [comment]
@jbogard suggested using an ITypeConverter w/ open generics like this (similar, I think, to what I pasted above):

```
cfg.CreateMap(typeof(PaginatedList<>),
typeof(PaginatedList<>)).ConvertUsing(typeof(PaginatedListMapper<>));
```

I was under the impression I would implement the converter.  Within the converter, the PaginatedList<Dest> would be instantiated, I would iterate over the items within the converter, use the mapper provided on the context to map src -> dest, add the mapped items to the collection, and then return the collection (PaginatedList<Dest>).

**Comment by jbogard** [comment]
Yeah, that's right, you would implement the converter. Is that not working?

**Comment by long2know** [comment]
@jbogard it's not working - but I am not entirely certain I have implemented the converter properly.  If you look at the two examples I posted above, using those class signatures, the converter is never executed.

**Comment by lbargaoanu** [comment]
I'll try this again :) The collection mapper has higher priority than the type map mapper which contains the converter. This means the converter will never be called. At least that's what I see :)

**Comment by lbargaoanu** [comment]
@jbogard I think the generic type map should come after the non generic one, before the object mappers and the rest.

**Comment by TylerCarlson1** [comment]
@lbargaoanu you can try changing the order of Object Mappers so that collection mapper comes after TypeMapMapper, but I worry it will have un-intended consequences.

**Comment by jbogard** [comment]
TypeMapMapper is dead brah

**Comment by lbargaoanu** [comment]
@long2know If you don't want to wait for #1110 and try again the converter solution you can use the new [AfterMap](https://github.com/AutoMapper/AutoMapper/blob/b8131db78bfd8df4d637b22a271ad80946b0d806/src/AutoMapper/IMappingExpression.cs#L313).
[One way to do it.](https://gist.github.com/lbargaoanu/dd0d23ffe2268639d65e#file-enumerablemapper-cs)
