### ISSUE TITLE
Breaking change from 4.1.1 -> 4.2.0

### ISSUE THREAD

**Issue by robertsimmons** [AutoMapper/AutoMapper#1084]
We were using IConfiguration.CreateMap<,>() very frequently. It appears this version of CreateMap (with no parameters) was actually coming from IProfileExpression, which IConfiguration used to also implement.

Was this an oversight, or permanent? If permanent, how do you recommend going forward? All this ties into conventions we have built in our application, where we were passing in Mapper.Configuration to these functions that took in IConfiguration, then they called CreateMap<,>() inside. I realize most (all?) of the static usages are going with 5.0.0, just wasn't expecting a breaking change going from 4.1.1 to 4.2.0

**Comment by jbogard** [comment]
I believe you need IMapperConfiguration now instead of IConfiguration.

A lot of those interfaces were...weird to say the least so I might have missed one or two.

**Comment by MattHoneycutt** [comment]
Doh, I guess I need to update Heroic.AutoMapper to account for this....  it uses IConfiguration.

**Comment by Draekane** [comment]
So, I am running into an issue along these lines....  We are trying to register our Mapper at the Startup of a Microservice.  the code inside the registerMapping function is:

`Mapper.Initialize(config =>
  {
       config.AddProfile<ProductCategoryProfile>();
   });`

This no longer seems to be a functional way of doing this....  What would be the correct way to update this?

**Comment by marko-baric-travcorp** [comment]
@Draekane I am having the same question... I can't seem to find the right way to use profiles in this non-static way. I would really appreciate an example with using profiles.

**Comment by jbogard** [comment]
@Draekane You've got it right there. FYI in the 5.0 branch, I've kept Mapper.Initialize and Mapper.Map. You can keep using those two and just ignore the compiler warnings.

Mapper.CreateMap is dead though.

For reference, the non-static version of the above is nearly exactly the same:

```
var cfg = new MapperConfiguration(config =>
  {
       config.AddProfile<ProductCategoryProfile>();
   });

App.Mapper = cfg.CreateMapper();

public override TM MapEntity(T entity)
{
    return App.Mapper.Map<TM>(entity);
}

```
Where `App` is just some static class you create.
