### ISSUE TITLE
After update to 4.2 -> Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by bp74** [AutoMapper/AutoMapper#1088]
After updating to 4.2 and converting my code to the new API, i got a very strange problem:

This is basically how i configure the mapper (simplified version):

    var mapperConfiguration = new MapperConfiguration(cfg => { 
        cfg.CreateMap<DeviceDto, Device>(); 
        cfg.CreateMap<Device, DeviceDto>(); 
    });
    mapperConfiguration.AssertConfigurationIsValid(); // WORKS FINE !!!
    var mapper = mapperConfiguration.CreateMapper();

And this is how i use it ... those are methods in a WCF service:

    public async Task<DeviceDto[]> GetDevices()
    {
        var result = await this.deviceController.GetDevices();
        return mapper.Map<Device[], DeviceDto[]>(result);
    }

    public Task<Boolean> UpdateDevices(DeviceDto[] deviceDtos)
    {
        var devices = mapper.Map<DeviceDto[], Device[]>(deviceDtos);
        return this.deviceController.UpdateDevices(devices);
    }

Converting the Device to DeviceDto (first method) works perfectly fine, but converting DeviceDto to Device (second method) throws a very strange exception:

> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.
> 
> Mapping types:
> Object -> Device
> System.Object -> Company.Server.Database.Entities.Device
> 

Needless to say that the code works fine with the older version if AutoMapper. For some strange reason it seems that AutoMapper does not recognize the source-type as DeviceDto.

**Comment by lbargaoanu** [comment]
Make a gist with a runnable example that fails.

**Comment by bp74** [comment]
I will try, probably it will be no simple repro case :(

**Comment by psoutner** [comment]
I'm experiencing the same situation. When I rerun the creation of the mapping before using it each time it works. Something is definitely broken.

**Comment by jbogard** [comment]
In the 5.0 line, I restored some of the static API. You still have to call Mapper.Initialize, Mapper.CreateMap is dead and not coming back.

**Comment by skoon** [comment]
> In the 5.0 line, I restored some of the static API. You still have to call Mapper.Initialize, Mapper.CreateMap is dead and not coming back

Wait, what? I'm having this problem in the 4.20 version. Mine is mapping a nullable decimal to a nullable decimal.

**Comment by skoon** [comment]
BUT, I did get a repo using this code.

`   class Program
    {
        static void Main(string[] args)
        {
            AutoMapper.Mapper.CreateMap<MyCrappyClass, dto>()
                .ForMember(dest => dest.MyNullableDecimal, opt => opt.ResolveUsing(src => src.MyCrappyNullValue))
                .ForMember(dest => dest.MyNullableDecimal, opt => opt.NullSubstitute(null));

            var f = new MyCrappyClass { MyCrappyNullValue = null };
            var result = AutoMapper.Mapper.Map<MyCrappyClass, dto>(f);
            Console.WriteLine("My dto was mapped right");

        }
    }

    public class dto
    {
        public decimal? MyNullableDecimal { get; set; }
    }

    public class MyCrappyClass
    {
        public decimal? MyCrappyNullValue { get; set; }
    }`

**Comment by jbogard** [comment]
@skoon Can you open a new issue? And god i hate nullables

**Comment by skoon** [comment]
New Issue: https://github.com/AutoMapper/AutoMapper/issues/1095

**Comment by abhishekbhalani** [comment]
Is it possible to Task<Model> mapping?
```
   public static void SetConfigurator(IMapperConfigurationExpression cfg)
        {
            cfg.CreateMap<Task<UserModel>, Task<UserServiceModel>>();
          }
```

**Comment by lbargaoanu** [comment]
Try a generic map:

     CreateMap(typeof(Task<>), typeof(Task<>));
