### ISSUE TITLE
Resolving a nullable decimal to a nullable decimal throws Missing type map configuration or unsupported mapping at runtime. version 4.2.0

### ISSUE THREAD

**Issue by skoon** [AutoMapper/AutoMapper#1095]
When I set up a mapping between two types, each containing a nullable decimal property, and I set the NullSubstitute option to use 'null', and "Missing type map configuration or unsupported mapping" exception is thrown at runtime.

Repro code below.

```
class Program
    {
        static void Main(string[] args)
        {
            AutoMapper.Mapper.CreateMap<MyCrappyClass, dto>()
                .ForMember(dest => dest.MyNullableDecimal, opt => opt.ResolveUsing(src => src.MyCrappyNullValue))
                .ForMember(dest => dest.MyNullableDecimal, opt => opt.NullSubstitute(null));

            var f = new MyCrappyClass { MyCrappyNullValue = null };
            var result = AutoMapper.Mapper.Map<MyCrappyClass, dto>(f);
            Console.WriteLine("My dto was mapped right");

        }
    }

    public class dto
    {
        public decimal? MyNullableDecimal { get; set; }
    }

    public class MyCrappyClass
    {
        public decimal? MyCrappyNullValue { get; set; }
    }
```

**Comment by skoon** [comment]
Honestly, I don't even know why they used the NullSubstitute and passed it a null. 

I guess when you really want a null, you REALLY want a null.

**Comment by lbargaoanu** [comment]
You can try the myget build.

**Comment by ericguthmann** [comment]
I don't know if it makes a difference, but this repros for us without the use of NullSubstitute.  It seems to be related to the use of ResolveUsing when a null is returned.  The example code below works fine with 4.1.1.  

We're kind of stuck here because we need the new 4.2 non-static implementation for dependency injection reasons, but this bug is preventing us from moving forward.  We're looking for a workaround, but if anyone has a suggestion, it would be appreciated.  Or maybe this is a bug that will be fixed quickly?

using AutoMapper;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<MyClass, MyClassDto>()
                .ForMember(dest => dest.Value, opt => opt.ResolveUsing(ResolveValue));
            Mapper.AssertConfigurationIsValid();
            
            var source = new MyClass { Value = null };
            var mapped = Mapper.Map<MyClass, MyClassDto>(source);
        }

        private static object ResolveValue(MyClass src)
        {
            return null;
        }
    }

    public class MyClass
    {
        public decimal? Value { get; set; }
    }

    public class MyClassDto
    {
        public decimal? Value { get; set; }
    }
}

**Comment by clafollett** [comment]
I've run into the same things as @ericguthmann above but my ResolveUsing mapped properties are of type Nullable<DateTime> and the value being mapped is null. Wish I had found this earlier. I would have saved myself some time.

**Comment by martinoss** [comment]
I had the same error using this mapping,

`.ForMember(dest => dest.Account, opt => opt.UseValue(null))`

but I got it to work this way:  

`.ForMember(dest => dest.Account, opt => opt.UseValue((AccountEntity)null))`

**Comment by Mds92** [comment]
I have the same problem in 4.2.1
How to resolve it?

**Comment by jbogard** [comment]
Use 5.0
