### ISSUE TITLE
v4.2.0 - ResolutionContext.New<TSource>() always throws NullReferenceException

### ISSUE THREAD

**Issue by tempusarcanus** [AutoMapper/AutoMapper#1097]
ResolutionContext.New<TSource>() invokes a constructor chain that always ends up throwing a NullReferenceException in TypePair.ctor(Type, Type).

ResolutionContext.New<TSource>() invokes ResolutionContext.ctor(TypeMap, object, Type, Type, MappingOperationOptions, IMappingEngine). That constructor invokes .ctor(TypeMap, object, object, Type, Type, MappingOperationsOption, IMappingEngine). That constructor invokes .ctor(ResolutionContext, object, object, Type, Type, TypeMap), which is where the implementation (primarily) resides. The destinationType parameter will always be null in this execution path, as will the typeMap argument. Consequently, the DestinationType property of ResolutionContext is never assigned. The last line of the constructor is to invoke TypePair.ctor(Type, Type), passing SourceType and DestinationType. The TypePair constructor doesn't valid either parameter, but assigns them to their corresponding properties and then immediately attempts to compute a hash code using the properties. This is where the NullReferenceException occurs.

**Comment by TylerCarlson1** [comment]
Where are you using ResolutionContext.New() where this exception is happening?

A Gist or code example showing this error would be very helpful in understanding what's going on.

**Comment by tempusarcanus** [comment]
I'm using it to unit test a TypeConverter. ITypeConverter.Convert() takes a ResolutionContext as an argument. Instead of newing up a ResolutionContext using one of the public constructors (which require quite a few arguments that are non-trivial to create, especially for such a simple use case), I'd rather just create a ResolutionContext and populate SourceItems because that's all my Convert implementation uses. Unfortunately, no ResolutionContext constructor is readily available to meet this need. ResolutionContext.New() was the closest thing to what I was looking for (sans the IMappingEngine parameter).

For the time being, I've simply used [PrivateType](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.privatetype.aspx) to get at the ResolutionContext.Empty field, but I hate doing anything (even in test code) that relies on implementation details rather than interface specs. For that same reason, it's more desirable to use ResolutionContext.New than to look at the implementations of the constructors, figure out what can safely be passed as null and what has to be constructed, and then new up a ResolutionContext.

Let me know if that doesn't adequately explain things.

The foregoing aside, the reason I opened the issue is because ResolutionContext.New() is flat-out broken right now. It will always throw a NullReferenceException in the TypePair constructor no matter what you pass to it. If you take a look at the implementation of ResolutionContext.New() and walk the execution path you'll see what I mean. Simply calling ResolutionContext.New() from the C# Interactive window in Visual Studio will raise the exception. The parameters you pass don't matter. Just execute the following in the C# Interactive window:

> #r "path to AutoMapper.dll"
> using AutoMapper;
> var ctx = ResolutionContext.New("foo", null);

**Comment by lbargaoanu** [comment]
In all fairness, you do pass null for the engine :)

**Comment by lbargaoanu** [comment]
This method is not used anywhere and it lacks a destination type parameter. I think we should remove it.

**Comment by tempusarcanus** [comment]
@lbargaoanu passing null for engine has no consequence in this particular case. You can observe the NullReferenceException regardless of what's passed for the engine parameter because it merely gets assigned to the Engine property of the ResolutionContext in .ctor(TypeMap, object, object, Type, Type, MappingOperationOptions, IMappingEngine).

I was afraid someone would suggest removing this method. I'd like to strongly make a case either for fixing it (perhaps by requiring a destinationType) or providing some other means of obtaining a ResolutionContext simply. The giant, complex public constructors of ResolutionContext are an impediment to unit testing ITypeConverters. I have several that use only ResolutionContext.SourceValue, so having to create all of the other types that ResolutionContext requires in its public constructors is both taxing and unnecessary. And as I said previously, it's bad design to go look at the implementation of the constructor chain, reverse engineer what can and cannot be passed null, and then do that. We should instead rely on the interfaces and specifications to define what's valid and what's not. (To that end, some XMLDoc on public and protected members would go a long way toward achieving this.)

I'd be happy to contribute a pull request with a suggested implementation (been using AutoMapper for years now, it's about time I started contributing back), but I've never contributed to GitHub or AutoMapper, so I'm not sure what the etiquette or protocol on that is.

**Comment by lbargaoanu** [comment]
You can easily do that in your own code. The method is broken because it's not needed. Anyway, it's @jbogard's decision.

Date: Wed, 10 Feb 2016 08:36:02 -0800

**Comment by tempusarcanus** [comment]
Sorry, easily do what in my own code? I don't understand what you're referencing.

Also, minor quibble, but the method isn't broken because it's unnecessary, it's broken because the implementation is wrong. :)

It might be unnecessary within the context of AutoMapper as a self-contained library, but it does fulfill a legitimate need to consumers of the library. I'm not opposed to getting rid of the New static method, but at least open up simpler ResolutionContext constructors. That's really what I'm getting at. Make it easier to construct ResolutionContext objects and assign their properties to simplify testing of ITypeConverters. Apart from that, I either need to create a giant graph of objects unnecessarily, guess what parameters I can pass as null (there's no documentation about what's required and not), or resort to reflection. All of these are significant usability issues from the perspective of a library consumer. 

That's not a criticism, it's just feedback. I've been using AutoMapper for years and I'm very grateful for all the effort that's put forward by the maintainers.

**Comment by TylerCarlson1** [comment]
I think this is up to @jbogard as well.  He might know why that New is there.  I haven't ever encountered anyone using resolution context outside of seeing debug messages, so it's completely foreign concept to me.

I would suggest making a PR for this.

**Comment by jbogard** [comment]
Honestly the context thing has gotten way too bloated. From my side I'd
like to simplify it, providing more information from configuration than
relying on tracking a ton of runtime information.

It's all a bit complicated.
