### ISSUE TITLE
AutoMapper 4.2.0 targeting dnxcore50 results in Errors about System.Linq.Queryable 4.0.0

### ISSUE THREAD

**Issue by markvincze** [AutoMapper/AutoMapper#1098]
If I'm trying to use AutoMapper 4.2.0 in an ASP.NET 5 project targeting the framework `dnxcore50`, I get the following build error:

    Error NU1002 The dependency System.Linq.Queryable 4.0.0 in project MyProject does not support framework DNXCore,Version=v5.0

However, version 4.0.0 works.

**Comment by lbargaoanu** [comment]
It works for me in VS 2015 Update 1. And that error doesn't make much [sense](https://www.nuget.org/packages/System.Linq.Queryable/) to me.

**Comment by markvincze** [comment]
@lbargaoanu,

Hmm, strange. I tried again now, I'm using VS 2015 Update 1 as well, and I still have the problem.

This is my project.json:

    {
      "version": "1.0.0-*",
      "compilationOptions": {
        "emitEntryPoint": true
      },

      "dependencies": {
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
        "Dapper": "1.50.0-beta7",
        "Npgsql": "3.1.0-alpha6",
        "AutoMapper": "4.2.0"
      },

      "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel"
      },

      "frameworks": {
        "dnxcore50": { }
      },

      "exclude": [
        "wwwroot",
        "node_modules"
      ],
      "publishExclude": [
        "**.user",
        "**.vspscc"
      ]
    }

And this is what I see in VS:

![image](https://cloud.githubusercontent.com/assets/1122274/12945059/5e772788-cfeb-11e5-9292-50143aecbdd7.png)

And I get the same thing as a build error.

That reference shows up without any error in your VS? Does it have the version 4.0.0 or something else?

**Comment by lbargaoanu** [comment]
It looks different because of some warning but it works. My project.json looks similar. Maybe reinstall your DNX. Not that I know how you would do that :)

**Comment by lbargaoanu** [comment]
I checked that in a newly created project, maybe you should try it that way.

**Comment by markvincze** [comment]
@lbargaoanu,

Thanks for the tips!

Clearing my C:\Users\USER_NAME\.dnx\packages folder solved the problem. I had the same issue with the Moq package, and I found the answer in this thread: https://github.com/aspnet/dnx/issues/3034

Cheers,
Mark
