### ISSUE TITLE
Inheritance Mapping Priorities

### ISSUE THREAD

**Issue by vk5880** [AutoMapper/AutoMapper#1100]
Hi,
I've read https://github.com/AutoMapper/AutoMapper/wiki/Mapping-inheritance Inheritance Mapping Priorities section and I still don't have clear understanding how automapper works.
There is stated that mapping source priorities are:
- Explicit Mapping (using .MapFrom())
- Inherited Explicit Mapping
- Ignore Property Mapping
- Convention Mapping (Properties that are matched via convention)

1. So what is the top? Explicit Mapping or Convention Mapping? Сommon sense is Explicit Mapping has higher priority. But example demonstrates that Ignore Property Mapping is overridden by Convention Mapping. How to treat this list then? 
2. Does Explicit Mapping priority relates to base type mapping or derived type mapping? Same question for all other sources? How to compare base type mapping source priorities with derived type mapping source priorities?

**Comment by jbogard** [comment]
Hmmm the docs look wrong. I'll fix them.

**Comment by bwegman** [comment]
@jbogard I'm looking at the docs and I'm still confused. The given unit test scenario fails right? I'm seeing the behaviour as described (Ignoring properties on base mapping overrules implicit mapping on subclass) but the unit test asserts the opposite.

**Comment by lbargaoanu** [comment]
Yes, a PR is welcome.

**Comment by bwegman** [comment]
Will do
