### ISSUE TITLE
What's the right way to do this?

### ISSUE THREAD

**Issue by TonyValenti** [AutoMapper/AutoMapper#1101]
Hi AutoMapper,
I've been using your tool for the past few weeks and I love it!  You guys have really made something awesome!

I'm reading through the docs and I'm not sure the right/best way to do this:
1.  I have a bunch of classes that derive from Entity.  Something like this:
````
public class Person : Entity {
  public string Name {get;set;}
}
public class Entity {
  public guid AuthorId {get;set;}
}
````

2.  I have a bunch of "response" classes that derive from EntityResponse.  Something like this:
````
public class PersonResponse : EntityResponse {
  public string Name {get; set;}
}
public class EntityResponse {
  public guid AuthorId {get;set;}
  public string AuthorName {get;set;}
}
````

When doing the mapping, I want AuthorName to be resolved by a function that gets either the whole EntityResponse object or just the AuthorId.  Should I use a ValueResolver or an AfterMap?  Also, how do I make all classes that derive from EntityResponse automatically get that mapping?

**Comment by lbargaoanu** [comment]
You can use [ResolveUsing](https://github.com/AutoMapper/AutoMapper/blob/13a0d8ed48ff581d52a52846d9248c7befc5b995/src/AutoMapper/IMemberConfigurationExpression.cs#L44) in your base mapping and [IncludeBase](https://github.com/AutoMapper/AutoMapper/blob/13a0d8ed48ff581d52a52846d9248c7befc5b995/src/AutoMapper/IMappingExpression.cs#L233) in your derived mappings to reuse the base resolver.

**Comment by TonyValenti** [comment]
Thanks @lbargaoanu !
I'm used to using the static instance for AutoMapper and one of the things I really liked about it was that it was "configuration free" for most use.  Is there a way for me to define this once and get it everywhere else for free or will I have to IncludeBase() on every single one of my definitions?

**Comment by lbargaoanu** [comment]
You can use IncludeBase in all the derived mappings only for the immediate base mapping, not ancestors. You can also use Include in your base mapping for all the derived mappings.
