### ISSUE TITLE
Interface without setter is not supported with dynamic proxy mapping

### ISSUE THREAD

**Issue by misiektg86** [AutoMapper/AutoMapper#1104]
If destination type is an interface and doesn't have setter the Automapper doesn't fill up dynamic proxy type with values.

**Comment by lbargaoanu** [comment]
That's by design.

**Comment by jbogard** [comment]
I asked them to open a GH issue to track it as a feature request.

I could probably dynamically create a sub-type of the interface that includes setters or something?

**Comment by lbargaoanu** [comment]
Maybe it would work somehow, but if you have a class with a read-only property, it will not set it. It seems weird that interfaces would behave differently.

**Comment by jbogard** [comment]
It already behaves differently in that it creates a proxy class for you and
adds in IPropertyChanged etc stuff

On Fri, Feb 12, 2016 at 10:08 AM, Lucian Bargaoanu <notifications@github.com

**Comment by matthewethomas** [comment]
I mentioned a possible solution to this  as a comment in #587, perhaps that will work for you?

**Comment by misiektg86** [comment]
That should be possible but then it is easier to create concrete type and still be able to use what automapper does better than I probably would do with reflection.
