### ISSUE TITLE
Nesting of complex types acorss various destination objects

### ISSUE THREAD

**Issue by dixitsuneel** [AutoMapper/AutoMapper#1107]
I have the following code structure for a back end entity
`public class Employee{
public Address Address{get;set;}
}`

`public class Address{
public string Line1{get;set;}
public string Line2{get;set;}
public string City{get;set;}
public string Zip{get;set;}
}`

My DTO objects have the following code structure

`class Provider{
public string AddressLine1{get;set;}
public string AddressLine2{get;set;}
public string City{get;set;}
public string Zip{get;set;}
}`

`class Admin{
public string AddressLine1{get;set;}
public string AddressLine2{get;set;}
public string City{get;set;}
public string Zip{get;set;}
}`

Now, Here's my auto mapper mapping

`Mapper.CreateMap<Employee,Provider>()
.ForMember(t=>t.City,opt=>opt.MapFrom(src=>src.Address.City))
.ForMember(t=>t.Zip,opt=>opt.MapFrom(src=>src.Address.Zip)

Mapper.CreateMap<Employee,Admin>()
.ForMember(t=>t.City,opt=>opt.MapFrom(src=>src.Address.City))
.ForMember(t=>t.Zip,opt=>opt.MapFrom(src=>src.Address.Zip)
`

I have various scenarios like these where a nested object needs to be flattended and majority of time the same complex type needs to be mapped to same properties in various destination objects.

Is there a better way writing this map? Currently I have to write this map for every new person type I have in the system.

**Comment by lbargaoanu** [comment]
You can have your entities implement an IHasAddress interface, do smth similar for you DTO-s and use Include or IncludeBase to reuse that mapping.
