### ISSUE TITLE
AutoMapper 4.2 Injection with Autofac

### ISSUE THREAD

**Issue by TDK1964** [AutoMapper/AutoMapper#1109]
Could anyone help make the following example work with Autofac?

```
public class AutoMapperRegistry : Registry
{
    public AutoMapperRegistry()
    {
        var profiles =
            from t in typeof (AutoMapperRegistry).Assembly.GetTypes()
            where typeof (Profile).IsAssignableFrom(t)
            select (Profile)Activator.CreateInstance(t);

        var config = new MapperConfiguration(cfg =>
        {
            foreach (var profile in profiles)
            {
                cfg.AddProfile(profile);
            }
        });

        For<MapperConfiguration>().Use(config);
        For<IMapper>().Use(ctx => ctx.GetInstance<MapperConfiguration>().CreateMapper(ctx.GetInstance));
    }
}

```

**Comment by jbogard** [comment]
No idea, I've never used AutoFac.

**Comment by mpetito** [comment]
@TDK1964: You'll need something along the lines of the following.

```
//register your profiles, or skip this if you don't want them in your container
builder.RegisterAssemblyTypes().AssignableTo(typeof (Profile));
            
//register your configuration as a single instance
builder.Register(c => new MapperConfiguration(cfg =>
{
    //add your profiles (either resolve from container or however else you acquire them)
    foreach (var profile in c.Resolve<IEnumerable<Profile>>())
    {
        cfg.AddProfile(profile);
    }
})).AsSelf().SingleInstance();

//register your mapper
builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve)).As<IMapper>().InstancePerLifetimeScope();
```

**Comment by TDK1964** [comment]
mpetito,

Thanks for the info but I'm still having problems. This is how I've configured by may mappings so far.

```
public class DomainToViewModelMappingProfile : Profile
    {
        public override string ProfileName
        {
            get { return "DomainToViewModelMappings"; }
        }
        protected override void Configure()
        {
            CreateMap<Training,TrainingViewModel>();
            CreateMap<Course, CourseViewModel>();
        }
    }

    public class ViewModelToDomainMappingProfile : Profile
    {
        public override string ProfileName
        {
            get { return "ViewModelToDomainMappings"; }
        }
        protected override void Configure()
        {
            CreateMap<TrainingViewModel, Training>();
            CreateMap<CourseViewModel, Course>();
        }
    }

public static class Bootstrapper
    {
        public static void Run()
        {
            SetAutofacContainer();
            AutoMapperConfiguration.Configure();
        }

        private static void SetAutofacContainer()
        {
            var builder = new ContainerBuilder();

            builder.RegisterControllers(Assembly.GetExecutingAssembly());
            builder.RegisterType<UnitOfWork>().As<IUnitOfWork>().InstancePerRequest();
            builder.RegisterType<DbFactory>().As<IDbFactory>().InstancePerRequest();

            // Repositories
            builder.RegisterAssemblyTypes(typeof(TrainingRepository).Assembly)
                .Where(t => t.Name.EndsWith("Repository"))
                .AsImplementedInterfaces().InstancePerRequest();

            // Services
            builder.RegisterAssemblyTypes(typeof(CourseService).Assembly)
               .Where(t => t.Name.EndsWith("Service"))
               .AsImplementedInterfaces().InstancePerRequest();

            // TODO AutoMapper registrations...


            IContainer container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
        }
    }
```

**Comment by mpetito** [comment]
@TDK1964 Where you have your TODO, you should be able to use my code example nearly verbatim.

The general steps are:

1. Register your `Profile` classes with the container so you can resolve them in the next step.  This could be done using assembly scanning, in very much the same way as the repositories and services in your code.
2. Register your `MapperConfiguration` as a singleton, and use a custom delegate to add the profiles to the configuration when it is constructed.
3. Register your `IMapper`, again using a custom delegate to acquire an instance from your singleton `MapperConfiguration`.
4. (Optional, not in my example..) Resolve your `MapperConfiguration` on application start and assert its validity.

**Comment by TDK1964** [comment]
@mpetito thanks for the update but my experience of AM and AF are very very limited so I really have no idea how to implement your suggestions :(

**Comment by TDK1964** [comment]
This is what I've done so far, but it's not working but I'm getting this error 

Missing type map configuration or unsupported mapping.
Mapping types:
TrainingViewModel -> Training
TrainingViewModel -> Training
Destination path:
Training

Source value:
TrainingViewModel

````
//register your profiles, or skip this if you don't want them in your container
builder.RegisterAssemblyTypes().AssignableTo(typeof(DomainToViewModelMappingProfile));
builder.RegisterAssemblyTypes().AssignableTo(typeof(ViewModelToDomainMappingProfile));

//register your configuration as a single instance
builder.Register(c => new MapperConfiguration(cfg =>
{
	//add your profiles (either resolve from container or however else you acquire them)
	foreach (var profile in c.Resolve<IEnumerable<Profile>>())
	{
		cfg.AddProfile(profile);
	}
})).AsSelf().SingleInstance();

//register your mapper
builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve)).As<IMapper>().InstancePerLifetimeScope();

```

**Comment by TDK1964** [comment]
@mpetito, you code doesn't work. The only way I got the injection to work was doing this..

```
builder.Register(c => new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new AppProfile());

            })).AsSelf().SingleInstance();

            builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve)).As<IMapper>().InstancePerLifetimeScope();


public class AppProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<Training, TrainingViewModel>().ReverseMap();
            CreateMap<Course, CourseViewModel>().ReverseMap();
        }
    }

```

**Comment by mpetito** [comment]
@TDK1964 The first step outlined above was:

> Register your Profile classes with the container so you can resolve them in the next step. This could be done using assembly scanning, in very much the same way as the repositories and services in your code.

You've explicitly added your profile in the `MapperConfiguration` which may be fine.  However, if you have many profiles, you may want to use assembly scanning.  This way your configuration looks like the following:

```
//register your profiles, or skip this if you don't want them in your container
builder.RegisterAssemblyTypes().AssignableTo(typeof (Profile)).As<Profile>();
```

Sorry, I originally missed the `As<Profile>()` call.  Note you may also need to specify which assembly (or assemblies) to scan for profiles.

Once your profiles are registered with the container, you should be able resolve all of your profiles in your configuration callback:

```
//add your profiles from the container, instead of cfg.AddProfile(new AppProfile());
foreach (var profile in c.Resolve<IEnumerable<Profile>>())
{
    cfg.AddProfile(profile);
}
```

**Comment by TDK1964** [comment]
@mpetito unfortunately is still doesn't work!

**Comment by Eonasdan** [comment]
@TDK1964 did you get this to work? Maybe my issue is different but I'm also trying to get 4.2 working with autofac.

My error is `Cannot resolve parameter 'AutoMapper.IMapper mapper'`

```
builder.Register(c => new MapperConfiguration(cfg =>
{
	cfg.CreateMap<IdentityUser, AspNetUser>().ReverseMap();
})).AsSelf().SingleInstance();

builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<IMapper>();
//or
builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve)).As<IMapper>().InstancePerLifetimeScope();
```

**Comment by TDK1964** [comment]
@Eonasdan the only way I got it to work was using the manual way (see earlier posts). Using the foreach way did not work at all.

I must say I find asking for any kind help with AF has been extremely frustrating, Especially when the first response for help was met with "No idea, I've never used AutoFac"

**Comment by Eonasdan** [comment]
@TDK1964 I understand, but autofac does at least register that way for you? Are you using `IMapper` int the ctro of your class then?

**Comment by Eonasdan** [comment]
@TDK1964 strange. I just tried this:

```
builder.RegisterAssemblyTypes().AssignableTo(typeof(Profile)).As<Profile>();

builder.Register(c => new MapperConfiguration(cfg =>
{
	foreach (var profile in c.Resolve<IEnumerable<Profile>>())
	{
		cfg.AddProfile(profile);
	}
})).AsSelf().SingleInstance();

builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve)).As<IMapper>().InstancePerLifetimeScope();
```

and it worked!

**Comment by Eonasdan** [comment]
@TDK1964 I got my code working (insert Picard facepalm). I'm happy to talk to you if you want some help solving your issue.

**Comment by TDK1964** [comment]
@Eonasdan  when I try the foreach way I just get "Missing type map configuration or unsupported mapping"

How are you defining your profiles?

**Comment by Eonasdan** [comment]
did you put `builder.RegisterAssemblyTypes().AssignableTo(typeof (Profile)).As<Profile>();` first?

At the moment I have one profile:

```
public class IdentityUserAspNetUserMapProfile : Profile
{
	protected override void Configure()
	{
		CreateMap<IdentityUser, AspNetUser>().ReverseMap();
		CreateMap<AspNetUser, IdentityUser>().ReverseMap();
	}
}
```

Maybe you've got a bad profile somewhere? Have you tried systematically trying them off and back on one at a time?

**Comment by Eonasdan** [comment]
@TDK1964 What version are you using? It appears the version 5 (the github version) is different from 4.2 (latest github) and I too get "Missing type map configuration or unsupported mapping" with v5.

@jbogard what's changed with the `Profile` class between 4.2 and 5?

**Comment by TDK1964** [comment]
This is my config. I don't think the profiles are working because cfg.AddProfile(profile); is never hit.


```
public static class Bootstrapper
    {
        public static void Run()
        {
            SetAutofacContainer();
            AutoMapperConfiguration.Configure();
        }

        private static void SetAutofacContainer()
        {
            var builder = new ContainerBuilder();

            builder.RegisterControllers(Assembly.GetExecutingAssembly());
            builder.RegisterType<UnitOfWork>().As<IUnitOfWork>().InstancePerRequest();
            builder.RegisterType<DbFactory>().As<IDbFactory>().InstancePerRequest();

            // Repositories
            builder.RegisterAssemblyTypes(typeof(TrainingRepository).Assembly)
                .Where(t => t.Name.EndsWith("Repository"))
                .AsImplementedInterfaces().InstancePerRequest();

            // Services
            builder.RegisterAssemblyTypes(typeof(CourseService).Assembly)
               .Where(t => t.Name.EndsWith("Service"))
               .AsImplementedInterfaces().InstancePerRequest();

            // AutoMapper
            // Register all the profiles
            builder.RegisterAssemblyTypes().AssignableTo(typeof(Profile)).As<Profile>();
            builder.Register(c => new MapperConfiguration(cfg =>
            {
                //cfg.AddProfile(new AppProfile());
                foreach (var profile in c.Resolve<IEnumerable<Profile>>())
                {
                    cfg.AddProfile(profile);
                }
            })).AsSelf().SingleInstance();
            builder.Register(c => c.Resolve<MapperConfiguration>()
                .CreateMapper(c.Resolve))
                .As<IMapper>()
                .InstancePerLifetimeScope();

            IContainer container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
        }

public class AutoMapperConfiguration
    {
        public static void Configure()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new AppProfile());
            });
        }
    }

    public class AppProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<Training, TrainingViewModel>().ReverseMap();
        }
    }
```

**Comment by kibner** [comment]
I was able to take the code from @mpetito and get it to work in my project. Here is my code:

```
public class AutoMapperModule : Module
{
	protected override void Load(ContainerBuilder builder)
	{
		builder.RegisterType<DomainToViewModelMappingProfile>().As<Profile>();
		builder.RegisterType<ViewModelToDomainMappingProfile>().As<Profile>();

		builder.Register(context => new MapperConfiguration(configuration =>
		{
			foreach (var profile in context.Resolve<IEnumerable<Profile>>())
			{
				configuration.AddProfile(profile);
			}
		}))
			.AsSelf()
			.SingleInstance();

		builder.Register(context => context.Resolve<MapperConfiguration>()
			.CreateMapper(context.Resolve))
			.As<IMapper>()
			.InstancePerLifetimeScope();
	}
}
```

I am using AutoMapper v4.2.1, AutoMapper.EF6 v0.3.0, Autofac v3.5.2, and Autofac.Mvc5 v3.3.4 from NuGet.

**Comment by Eonasdan** [comment]
@kibner but there's no point in registering every profile in autofac, you might as well just add each one to the `MapperConfiguration` part

**Comment by kibner** [comment]
@Eonasdan Then don't use the foreach loop and just add the ones you need inside the MapperConfiguration.

----

I think the issue @TDK1964 is experiencing may be because the wrong 'Register' method is being called. I took the code I posted and replaced the lines:

```
builder.RegisterType<DomainToViewModelMappingProfile>().As<Profile>();
builder.RegisterType<ViewModelToDomainMappingProfile>().As<Profile>();
```

with this:

```
builder.RegisterAssemblyTypes().AssignableTo(typeof(DomainToViewModelMappingProfile));
builder.RegisterAssemblyTypes().AssignableTo(typeof(ViewModelToDomainMappingProfile));
```

Doing that gave me a "Missing type map configuration or unsupported mapping." error like @TDK1964 was experiencing. I believe the problem lies with using `RegisterAssemblyTypes()` without loading from an assembly. When I have used that method, it usually looks like `builder.RegisterAssemblyTypes(Assembly.Load("<assembly name goes here>"))`.

I am not intimately familiar with AutoFac so my reasoning could very well be wrong, but I'm pretty sure my suggested fix should work.

**Comment by prunkster** [comment]
@TDK1964 
Does it work when you replace `builder.RegisterAssemblyTypes().AssignableTo(typeof(Profile)).As<Profile>();` with `builder.RegisterAssemblyTypes(AppDomain.CurrentDomain.GetAssemblies()).AssignableTo(typeof(Profile)).As<Profile>();`?

**Comment by ehimah** [comment]
This worked for me

```C#
public class AutoMapperModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
           builder.RegisterAssemblyTypes(typeof(AutoMapperModule).Assembly).As<Profile>();
            builder.Register(context => new MapperConfiguration(cfg =>
            {
                foreach (var profile in context.Resolve<IEnumerable<Profile>>())
                {
                    cfg.AddProfile(profile);
                }
            })).AsSelf().SingleInstance();

            builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve))
                .As<IMapper>()
                .InstancePerLifetimeScope();
        }

// ~/App_Start/AutofacConfig.cs
 public class AutofacConfig
    {
        public static void Register()
        {
            var builder = new ContainerBuilder();

            // .....
            builder.RegisterModule(new AutoMapperModule());
            
            var container = builder.Build();

            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
        }

// Global.asax
public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            //  ......
            AutofacConfig.Register();
        }
    }

//In my controller controllers

public class ProductLicensesController : Controller
    {
        
        private readonly IMapper mapper;

        public ProductLicensesController( IMapper mapper)
        {
            //. . .
            this.mapper = mapper;
        }

// then in some action method

var productLicense = mapper.Map<ProductLicense>(viewModel);

```

**Comment by badian96** [comment]
I used Eonasdan code and it worked like magic. Can anyone explain what is the meaning of c.Resolve taken as parameter in the CreateMapper method?

**Comment by badian96** [comment]
@Eonasdan The code works great, can you explain
this line of code: 
`builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve))`

**Comment by Eonasdan** [comment]
@badian96  the `c` is a lambda expression for the AutoFace context. So the code is supposed to go find all of the `Profile`s in the assembly and Resolve it into a Profile type. Is that what you're asking?

Also, if you got the `foreach` loop to work, it stopped working for me again.

**Comment by LoopDLoop** [comment]
I understand the part of resolving all the profiles and adding them. I
don't understand the part that comes after it.. What is the meaning of
c.Resolve inside the CreateMapper()? In general what ks c.Resolve?
בתאריך 7 במרץ 2016 21:30,‏ "Eonasdan" <notifications@github.com> כתב:

**Comment by LoopDLoop** [comment]
`CreateMapper(c.Resolve)`

I don't understand what is the `c.Resolve` here.
And the profiles are working just fine for me as you posted.

**Comment by mpetito** [comment]
`c.Resolve` is a method group for the Resolve method of the Autofac context.

You'll notice that the `CreateMapper` method accepts a parameter of type `Func<Type, object>`, a factory for dependencies by type.  An overload of the Resolve method matches this signature (there is an overload which accepts a single Type argument and returns an object of that Type).  This allows Autofac / mapping dependencies to be resolved from your container (following IoC principles).

To answer a couple of questions regarding the `foreach`:

1. Make sure if you're using assembly scanning to register your profiles, you name the correct assemblies to scan.  Otherwise, they won't appear within your `foreach` and you'll get the missing mapping error.
2. You don't need to register your profiles in your container.  This is just a convenient approach if you have many profiles.  If you don't register your profiles, you'll have to add them to your `MapperConfiguration` explicitly instead of using a `foreach` loop.

**Comment by LoopDLoop** [comment]
I have a problem when inside one of my profiles i use a nested mapping - meaning I use the static 
Mapper.Map<> inside my profile configuration.
In unit tests the mapping works perfectly, I guess it's something with Autofac, anyone knows?

**Comment by Sykomaniac** [comment]
Apologies as I know this is an old issue. However the following worked for me when trying to perform assembly scanning for all Mapping Profiles:

    protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterAssemblyTypes(Assembly.GetExecutingAssembly()).AssignableTo(typeof(Profile)).As<Profile>();

            builder.Register(c => new MapperConfiguration(cfg =>
            {
                foreach (var profile in c.Resolve<IEnumerable<Profile>>())
                {
                    cfg.AddProfile(profile);
                }
            })).AsSelf().SingleInstance();

            builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<IMapper>();
        }

**Comment by AlexAlexGoTO** [comment]
```
builder.Register(c => new MapperConfiguration(cfg =>
            {
                    cfg.AddProfile(typeof(AutoMapperProfile));
                
            })).AsSelf().SingleInstance();

            builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<AutoMapper.IMapper>();
```
` public class AutoMapperProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<SubscribersListModel, SubscribersListDto>().ReverseMap();
            CreateMap<SubscribersListDto, SubscribersListModel>().ReverseMap();
        }
    }`

Work fine for me 5.2.0 Mapper

**Comment by SamiAl90** [comment]
Anyone experienced problems with ValueResolvers? I am getting the message

> ObjectDisposedException: This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.

**Comment by Mayrond** [comment]
`builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve<IComponentContext>().Resolve)).As<IMapper>().InstancePerLifetimeScope();` @SamiAl90

**Comment by mpodonyi** [comment]
Any reason why in this code the Mapper is created InstancePerLifeTimeScope:

```
 builder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve))
                .As<IMapper>()
                .InstancePerLifetimeScope();
```

This could also be SingleInstance like for the MappingConfiguration?

**Comment by jbogard** [comment]
You want the `IMapper` to be scoped to whatever your per-request container
is scoped as. If you're using a nested/child container per request, then
the above is what you want.

I'm super careful about static/singletons, really only configuration should
be singleton.
