### ISSUE TITLE
It is not possible to ConvertUsing an explicitly implemented ITypeConverter between open generics and other types

### ISSUE THREAD

**Issue by jnm2** [AutoMapper/AutoMapper#1113]
The problem seems to be in [`MappingExpression.ConvertUsing`](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/Configuration/MappingExpression.cs#L35).

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/c8098f5591919abe13b480af659702c12a5da09c/src/UnitTests/Bug/GenericTypeConverter.cs

**Comment by jnm2** [comment]
I have a repro for this but it only happens between open generics and closed/nongenerics. It's probably covered by #1112 in that case.
