### ISSUE TITLE
UseAsDataSource / ProjectTo with multiple collections (NHibernate)

### ISSUE THREAD

**Issue by liquidsnk** [AutoMapper/AutoMapper#1114]
I´m running into an issue in which I have an entity with multiple collections which maps to a DTO that has representations for those.

I´m using NHibernate and the query generated by ProjectTo seems to be causing a cartesian product that, for each collection, returns the elements on the collections multiplied by the amount of elements in the other collections. This ends up in the DTO and I´m not finding a successful way to avoid it.

My actual scenario is that I´m exposing and OData endpoint with UseAsDataSource for querying through the DTO structure.

Anyway, I suppose this could be regarded as an anomaly of how NHibernate is executing the LINQ query, but I would really appreciate if anyone could give me any ideas on how to work around this.

I was thinking that one way would be to make use of the functionality of UseAsDataSource but without using the ProjectTo projection.
That is, having automapper map the entities from memory after hydrated by the ORM as it will usually do without ProjectTo while still using the expression translation.
This is not a supported scenario though, correct?

I would really appreciate any clues on finding a solution!, thanks.

**Comment by TylerCarlson1** [comment]
UseAsDataSource uses behind the scenes mappings of expressions like `Map<Expression<Func<IQueryable<Model>, IQueryable<Model>>>, Expression<Func<IQueryable<DTO>, IQueryable<DTO>>>>(expression)`.
You can use that to translate the expression and compile and invoke it on the query.  Or you can do `Func<Model,Bool> to Func<DTO, bool>` and pass the mapped expression into a Where clause.

Also UseAsDataSource only does ProjectTo's return type is the same as For.  If you do Select(m => new Model() as object), it might ignore projectTo and just translate your expression into Query statement.  I don't know if there's a scenario you can make work using this, as the Select statement might give you the same query problem with NHibernate.

**Comment by liquidsnk** [comment]
Hello Tyler, thanks!!
Regarding the three options you are mentioning, the first two are quite confusing to me to be honest, but here's what I gathered:

1) Mapping the expressions like so seems powerful!, although I will need more time to even start understanding how to make use of that. Wouldn't that make me basically replicate what UseAsDataSource is doing though?

2) Are you saying I can use AutoMapper to map a predicate meant for DTO to a predicate for Model directly using Map? That seems great, although I don't think I actually have access to the expressions on that way using Http.OData (although maybe I do!).

3) Admittedly this is not really nice, but it seems like the simplest option and a suitable work-around for now. Will see if it goes well in the long term but for now it seems to work properly: https://gist.github.com/liquidsnk/f61d82bdcd6661130aa7

**Comment by TylerCarlson1** [comment]
1 & 2 are hard, and yes you are basically replacing UseAsDataSource at this point.
If you look at unit tests in source code there's some in I believe MappingExpressions test that show how mapping expressions are done.

3 I meant more like `.Select(x => new ClientData{ value = x.value} as object)`

This will change the x.value from x being ClientData to ClientDataEntity and will still do the equivilent of projection, although manually.

All of them will be tough workarounds, but there's nothing Automapper can really do when the ORM has a bug or has limits on what it can do.

**Comment by liquidsnk** [comment]
I see. I understand that using the code I linked will cause NHibernate to load the entities and then perform the mapping in-memory defeating the purpose of ProjectTo in AutoMapper, but I'm fine with that, as it allows me to both translate the query from DTO to Entity and also to map Entity to DTO (and in addition, loads the collections properly of course).

Using the one you are proposing I'm afraid that I might end up with the same LINQ query that ProjectTo would have generated and have to work around the collections issue by modifying it in some way (if even possible). Also, will not be using AutoMapper to map to the DTO.

Well, thank you very much for your help!, and your conclusion is correct. Time to close this one :)
