### ISSUE TITLE
Map<S,D>(S source, D destination) ignoring specified type values

### ISSUE THREAD

**Issue by adamhathcock** [AutoMapper/AutoMapper#1115]
Hi,

I might be wrong in my config but here goes:

I'm asking the Mapper to Map types S and D to base types of each.  However, it always resolves the objects to S and D because it uses GetType() on the objects instead of looking at the types I actually specified.  I believe I found the problem line here:
https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/MapperConfiguration.cs#L218

Is there a reason GetType always overrides what I ask it to map?

**Comment by jbogard** [comment]
What do your types and mapping configuration look like?

**Comment by adamhathcock** [comment]
Here's a sample of the problem.  I want to force the usage of ObjectToStreamMapping as I specified that on the Map method but it uses StringToMemoryStreamMapping no matter what because of the call on GetType() on the passed parameters.

```
public class Program
{
	public static void Main()
	{
		var serviceCollection = new ServiceCollection();
		serviceCollection.TryAddSingleton(typeof(MapperConfiguration), x => new MapperConfiguration(cfg =>
		{
			cfg.ConstructServicesUsing(t => ActivatorUtilities.CreateInstance(x,t));
			cfg.CreateMap<object, Stream>().ConvertUsing<ObjectToStreamMapping>();
			cfg.CreateMap<string, MemoryStream>().ConvertUsing<StringToMemoryStreamMapping>();
		}));
		serviceCollection.TryAddSingleton(typeof(IMapper), x => x.GetService<MapperConfiguration>().CreateMapper());

		var provider = serviceCollection.BuildServiceProvider();

		var mapper = provider.GetService<IMapper>();
		var dt = mapper.Map<object, Stream>("test", new MemoryStream());
	}
}

public class ObjectToStreamMapping : ITypeConverter<object, Stream>
{
	private readonly IMapper mapper;


	public ObjectToStreamMapping(IMapper mapper)
	{
		this.mapper = mapper;
	}

	public Stream Convert(ResolutionContext context)
	{
		return Stream.Null;
	}
}

public class StringToMemoryStreamMapping : ITypeConverter<string, MemoryStream>
{
	private readonly IMapper mapper;


	public StringToMemoryStreamMapping(IMapper mapper)
	{
		this.mapper = mapper;
	}

	public MemoryStream Convert(ResolutionContext context)
	{
		return new MemoryStream();
	}
}
```

**Comment by lbargaoanu** [comment]
You can resolve the type map that you want and then map through the engine with Map(context), but you need to get an engine instance somehow.
