### ISSUE TITLE
Using profiles in non-static version (v4.2)

### ISSUE THREAD

**Issue by marko-baric-travcorp** [AutoMapper/AutoMapper#1116]
I am having trouble understanding how to properly use profiles in the new non-static scheme.

In the documentation, it says:

```
var config = new MapperConfiguration(cfg => {
    cfg.AddProfile<AppProfile>();
    cfg.CreateMap<Source, Dest>();
});

var mapper = config.CreateMapper();
```

This mapper configuration creates mapper by calling CreateMapper() on it. But the added profile has it's own MapperConfiguration inside, where you define mappings as part of the profile. 
So how to include those mappings from withing the profile to be added to this configuration when I call CreateMapper() here? It's the whole point of having profiles - not having to define all the mappings in one place.

I would appreciate any help since the documentation is very poor on using profiles for v4.2.

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Configuration#profile-instances

I added a few more things there. I'm not sure what you mean by profiles having their own MapperConfiguration inside, I didn't see that documented anywhere.

**Comment by marko-baric-travcorp** [comment]
Thanks for the quick reply.

What I meant is: 
Inside the profile, I need to configure mappings. To do so, I need to create new MapperConfiguration inside the profile and configure mappings on it. And later, when I want to use this profile, I add it to MapperConfiguration. Now, this "outer" mapper configuration does not know about the maps defined in the profile.

Am I doing something wrong here?

**Comment by jbogard** [comment]
Ah, yes you are. The Profile instance itself has configuration calls (CreateMap etc). I updated the docs again (and if it's still not clear, please add whatever would make sense, clearly I've not explained Profiles well).

**Comment by RobertLycksell** [comment]
Is this for IOC? Then how do I create a Mapper that has all configurations from all profiles?

**Comment by marko-baric-travcorp** [comment]
Ahaaa, I see. Thank you, @jbogard!

**Comment by marko-baric-travcorp** [comment]
@RobertLycksell You just define the mappings in profiles. The Profile class has CreateMap() method to do this. Than, just add all the profiles in the MapperConfiguration, as described in the documentation.
