### ISSUE TITLE
No Xamarin profile 78 support anymore?

### ISSUE THREAD

**Issue by xplatsolutions** [AutoMapper/AutoMapper#1117]
By default Xamarin creates a PCL Profile 78, and I've noticed that it is not possible to add the latest AutoMapper package. Is there any way to support Xamarin's default profile?

**Comment by jbogard** [comment]
I target profile 111, can you target that instead?

**Comment by xplatsolutions** [comment]
Yes, we could do this, we'll see if the solution permits. Thanks for the quick reply.

**Comment by gtas-verisk** [comment]
@jbogard I found out that AutoMapper works only in Profile 111, is that true? Couldn't make it work with Profile 259 for example.

Any thoughts?

**Comment by jcmm33** [comment]
I've just hit this as well. We have a solution with many assemblies, many profile 259.  Tried to upgrade from 4.1.1 to 4.2.1but it won't have it,saying package doesn't contain the necessary assembly references or content files that are compatible with that framework. I was hoping to try the fix around signing of assemblies for use with Android & PCLs but can't get past this error.

**Comment by jbogard** [comment]
Yes, all this goes away with the upcoming netstandard profile. I don't support Silverlight any more, which is profile 259.

This is all very annoying, I can't make everyone happy with PCL at the moment.

**Comment by jbogard** [comment]
Now supporting .net standard platform 1.1.
