### ISSUE TITLE
Issue while un flattening the object

### ISSUE THREAD

**Issue by lolekjohn** [AutoMapper/AutoMapper#1118]
I have two Models:

Source:

    public class EmployeeSrc
    {
        public CodeValue Type { get; set; }
    }

    public class CodeValue
    {
        public string Code { get; set; }

        public string Description { get; set; }
    }

Destination:
    
```
public class EmployeeDst
    {
        public string TypeCode { get; set; }

        public string TypeDescription { get; set; }
    }

```
While mapping the objects from Source to Destination, the values get mapped with just the create map statement - Mapper.CreateMap<EmployeeSrc, EmployeeDst>();

In case if i need to map it back from destination to source, is there a way where the values get automatically mapped from TypeCode -> Type.Code and TypeDescription -> Type.Description
I know that it works if i write explicity maps.

But we will have so many CodeValue objects of this kind and our requirement is to map any String with Code and Description suffix to Objects of CodeValue with the same name

**Comment by TylerCarlson1** [comment]
Currently there's no way of unflattening values by default.  Issue is you need extra maps from EmployeeDst to CodeValue which is a TypeMap altogether.  Need a prefix of Type for them to be autoresolved too.

With conventions you might be able make this scenario to work, but only for what you specify.  As far as an all encompassing convention goes I don't know.

Add a member configuration in where if the destination is if of type CodeValue and name is Type then map source to Code Type.  And add a convention that always makes a map if destination is CodeValue, and uses Type Prefix's, that way you don't have to map every destination to CodeValue.

I'm not sure how it would look in code right now, but making conventions to cover this scenario would be your best bet to make it work without having to explicitly map every class.

**Comment by lbargaoanu** [comment]
It can be done with interfaces or base classes as in #1107.
