### ISSUE TITLE
AutoMapper.Internal.PlatformAdapter.Resolve<AutoMapper.Internal.IDictionaryFactory>() return DictionaryFactory but should DictionaryFactoryOverride

### ISSUE THREAD

**Issue by emejibka** [AutoMapper/AutoMapper#1121]
Hello.
I found one strange think, in sources of class PlatformAdapter class DicrionaryFactoryOverride is registered for interface IDictionaryFactory. But i got DictionaryFactory instance if i install nuget package and get instance of IDictionaryFactory. In nuget package class DicrionaryFactoryOverride is not defined. I build automapper from sources in debug config and for DictionaryFactoryOverride. In release config i cant build automapper in visual studio because NET40 variable not defined in csproj. When i define NET40 variable and build automapper in release mode i got DictionaryFactoryOverride instance.
We use automapper v 4.1.1 and can use new version because our projects run on net 4 and we cant upgrade they. With DictionaryFactory we have a deadlock if we use automapper in multithread and load maps on demand.

**Comment by lbargaoanu** [comment]
.Net 4 is not supported anymore so I guess you should fork the version you want and fix it yourself.
