### ISSUE TITLE
dotnet5.4 support

### ISSUE THREAD

**Issue by igatanasov** [AutoMapper/AutoMapper#1124]
Is there any plans for dotnet5.4 support?

**Comment by jbogard** [comment]
Well, I support dotnet5.1 which is forward compatible to dotnet5.4 so it's supported today.

**Comment by lbargaoanu** [comment]
I cannot reference AutoMapper in a project targeting 5.4

**Comment by igatanasov** [comment]
Yes you can't because dotnet5.4 is not defined as supported framework. Meanwhile I have just forked your @jbogard repository and if you want just a help I can try to add support and then issue a pull request?

**Comment by jbogard** [comment]
Not really, the dotnet TFN is going away soon in favor of "netstandard". Or
I could add it, and remove it in a month or so when .NET Core RC2 drops.

**Comment by MikeJoyce19** [comment]
Where is this project at as far as supporting 5.4?  Are you waiting for the dust to settle on the framework and project overall before you provide support?

**Comment by jbogard** [comment]
I'm waiting for .NET Core 1.0 RC2 to drop.

**Comment by xperiandri** [comment]
Will you support `netstandardapp`?

**Comment by jbogard** [comment]
Well, yes, since I'll support netstandard1.1

**Comment by xperiandri** [comment]
Do you have any difficulties in enabling its support?

**Comment by jbogard** [comment]
No, I'm just waiting for something stable from RC2 nightlies to drop. I pulled down the nightlies a bit back and couldn't compile in VS.

**Comment by jbogard** [comment]
Now dropped, 5.0 beta supports netstandard1.1 TFN

**Comment by xperiandri** [comment]
At CI feed?
