### ISSUE TITLE
Can't find DynamicMap in 4.2

### ISSUE THREAD

**Issue by mgibas** [AutoMapper/AutoMapper#1125]
IMappingEngine.DynamicMap does not exist - was it moved somewhere else ? Was it obsolete and removed ? Cant find anything in docs about it

**Comment by lbargaoanu** [comment]
[Example](https://github.com/AutoMapper/AutoMapper/blob/c8098f5591919abe13b480af659702c12a5da09c/src/UnitTests/Bug/DestinationCtorCalledTwice.cs#L43).

**Comment by mgibas** [comment]
That is a major change - at least incompatible with previous 4.1.1

**Comment by manojSpant** [comment]
I am facing a similar problem, Need to apply automapper with Datatable , 

List<person> people = AutoMapper.Mapper.DynamicMap<idatareader, list<person="">>(sourceDataTable.CreateDataReader());

What code is use in place of above code for DynamicMap of Datatable into list 
into automapper 4.2.
