### ISSUE TITLE
Xamarin Android - Unable to upgrade NuGet package from 4.1.1 to 4.2.0

### ISSUE THREAD

**Issue by Cybrosys** [AutoMapper/AutoMapper#1126]
I have a Xamarin Android project that uses AutoMapper 4.1.1 . I'm trying to upgrade the package to 4.2.0 but I get the following error message.

> Could not install package 'System.Reflection.Extensions 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

From what I can tell, the 4.1.1 contained 11 folders depending on platform. 4.2.0 only contains 3 folders.

**Comment by jbogard** [comment]
It should pull in the PCL in there, I removed the others because they weren't necessary with the PCL profile I'm targeting. You might need to uninstall/install the package?

**Comment by Cybrosys** [comment]
I tried removing the package and adding it, but it didn't work. I got the same error message but regarding a dependency (the core problem remains the same. It's trying to find support for MonoAndroid 6, but the folder in the package specifies MonoAndroid 10):

> Could not install package 'System.Reflection.Extensions 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I don't know if it has anything to do with that I'm using the Shared project type for my shared code instead of a PCL project.

**Comment by jcmm33** [comment]
I've tried this on a brand new, empty android xamarin solution and it errors in the same way. I've also tried the v 5 releases on https://www.myget.org/F/automapperdev/api/v2 (i assume this is the correct place) and these too exhibit the same installation error.

**Comment by nbelley** [comment]
Any news on this? Trying to ugrade also and cannot do it...

**Comment by jbogard** [comment]
Here's the deal. I don't want to go back in and add an Android target - the tooling does not support project.json yet, and it was hell to make it a separate project. I want to create a "netstandard" package that Android apps can just reference.

But that depends on RC2, which is 2 weeks away from dropping.

**Comment by nbelley** [comment]
I understand, but, is it because of the way I used or created my PCL project? Am I doing something wrong or it's just like that for android pcl?

**Comment by jbogard** [comment]
Ah, it's because that package isn't defined for MonoAndroid 1.0. Compare this:

https://www.nuget.org/packages/System.Collections/4.0.11-beta-23516

With this:

https://www.nuget.org/packages/System.Reflection.Extensions/4.0.1-beta-23516

**Comment by jbogard** [comment]
And this will be fixed for RC2 it seems: https://github.com/dotnet/corefx/issues/5955

**Comment by nbelley** [comment]
Thanks! I guess I'll wait for the RC2 then.

**Comment by jbogard** [comment]
Working on the alpha channel.
