### ISSUE TITLE
Inconsistent Mapping for Arrays

### ISSUE THREAD

**Issue by kabua** [AutoMapper/AutoMapper#1127]
We have an array of enum values that we store in the database as an encoded byte array. Therefore our model looks like this:
```
enum Permission { Read, Write, Edit, etc }
class Domain
{
   ...
   public Permission[] Permissions {get; set; }
}

class DatabaseDto
{
   ...
   public byte[] Permissions { get; set }
}  
```

Our profile class (called TestMapper) defines the following:
```
protected override void Configure()
{
    CreateMap<Permission[], byte[]>()
        .ConvertUsing(permissions => permissions.ToBytes());

    CreateMap<byte[], Permission[]>()
        .ConvertUsing(bytes => bytes.ToPermissions());

    CreateMap<Domain, DatabaseDto>()...
    CreateMap<DatabaseDto, Domain>()...
}
```

Our start up code calls looks like this:
```
Mapper.Initialize(configuration =>
{
    configuration.AddProfile<TestMapper>();
});

Mapper.AssertConfigurationIsValid();
```
However, when we run our code we get an error stating the mapping for 'byte to Permission' is missing! We can't convert a byte to a Permission, we must convert the whole byte array to a set of Permissions.

`AssertConfigurationIsValid()`  doesn't complain about 'byte to Permission' mapping, it complains about 'byte[] to Permission[]' - which is what we expect. 

**Possible Bug**: however, the code that validates the model and the code that converts the model disagree on how the mapping should be performed.

Honestly, we would expect the mapping to first look for an exact type match of 'byte[] to Permission[]' and if no mapping exists, then check for 'byte to Permission'.

To work-a-round this issue we had: 1) leave the 'byte[] to Permission[]' mappings (so that the validate would pass) and 2) add two special `ValueResolver`s. Like so:
```
CreateMap<DatabaseDto, Domain>()
    .ForMember(dest => dest.Permissions, opt =>
    opt.ResolveUsing(src => src.Permissions.ToPermissions()))
```
A very verbose way of converting something that should have been very simple.

**Comment by lbargaoanu** [comment]
This seems to work on the MyGet build. If you disagree, make a gist with an executable example that fails.
