### ISSUE TITLE
Automapper with Datatable .

### ISSUE THREAD

**Issue by manojSpant** [AutoMapper/AutoMapper#1129]
List<person> people = AutoMapper.Mapper.DynamicMap<idatareader, list<person="">>(sourceDataTable.CreateDataReader());

What code is use in place of above code for DynamicMap of Datatable into list 
into automapper 4.2.

**Comment by TylerCarlson1** [comment]
Dynamic Map is replaces with IMapperConfiguration.CreateMissingTypeMaps.  When you set it to true it will make a map for an object if it doesn't exist.

**Comment by manojSpant** [comment]
Hello , 
I am using this below code : 
have one datatable dtUsers and need to map dtUsers   datatable field values into property of class "TrkUsers"   .

Dim config = New AutoMapper.MapperConfiguration(Function(cfg) InlineAssignHelper(cfg.CreateMissingTypeMaps, True))

Dim mapper = config.CreateMapper()
Dim people = mapper.Map(Of IDataReader, List(Of TrkUsers))(dtUser.CreateDataReader())

**Over third line "mapper.map" it is creating exception** : 
Missing type map configuration or unsupported mapping.
Mapping types:
IDataReader -> List`1
System.Data.IDataReader -> System.Collections.Generic.List`1[[AccountingLink.TrkUsers, AccountingLink, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
**Destination path**:
List`1
**Source value:**
System.Data.DataTableReader

**Comment by TylerCarlson1** [comment]
https://github.com/AutoMapper/AutoMapper.Data has the functionality for the data reader.

I believe it's having some issues from upgrading to 4.2.  If it doesn't work you might have to downgrade to 4.1.1 to get it working.

**Comment by manojSpant** [comment]
/ Create class /
Public Class Person
    Public Property FN As String
    Public Property LN As String
End Class

/ Create datatable 
  Dim table = New DataTable()       
     table.Columns.Add("FN", GetType(String))
     table.Columns.Add("LN", GetType(String))

           table.Rows.Add("Jeff", "Barnes")
            table.Rows.Add("George", "Costanza")
            table.Rows.Add("Stewie", "Griffin")
            table.Rows.Add("Stan", "Marsh")
            table.Rows.Add("Eric", "Cartman")

/ Need to map records of datatable into Person class properties .
  Dim people As List(Of Person) = AutoMapper.Mapper.DynamicMap(Of IDataReader, List(Of Person))(table.CreateDataReader())

/ But issue is that, I am not getting 0 count of people  list, Am I missing some thing in this code .

**Comment by gregorgretz** [comment]
i have the same issue and also tested the new version 4.2.1. 
i can not find a way to map a datatable or dictionary into a specific object.
