### ISSUE TITLE
Unable to install in windows 8.1 App

### ISSUE THREAD

**Issue by mbogaerts** [AutoMapper/AutoMapper#1132]
I'm unable to install Automapper in a Win8.1 project: following exception:
Error		Could not install package 'System.Runtime 4.0.20'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			
Only occurs if platform is Windows 8.1 only

**Comment by rsheptolut** [comment]
Same here. Is it a bug? Is there a workaround?

**Comment by Petezah** [comment]
+1

**Comment by jbogard** [comment]
Working in 5.0
