### ISSUE TITLE
Can't resolve this to Queryable Expression

### ISSUE THREAD

**Issue by pvranich** [AutoMapper/AutoMapper#1133]
Hi,

I have just implemented the latest version of AutoMapper and have moved away from the static API and have implemented the ProjectTo<T> extensions as well.

I am now getting the below error, which I wasn't before

**Can't resolve this to Queryable Expression**
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.ResolveExpression(PropertyMap propertyMap, Type currentType, Expression instanceParameter)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
>    at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
>    at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)
>    at DB.Eus.GSC.Services.Repository.Services.BaseRepositoryService`2.First(Expression`1 where, IConfigurationProvider config, Expression`1[] includeProperties) in d:\Source\GSC\DB.Eus.GSC.Services\trunk\DB.Eus.GSC.Services\Repository\Services\BaseRepositoryService.cs:line 296_

In my create map I am using a custom IValueResolver(s) which may return nullable DateTime.

Is it in any way related to this issue? https://github.com/AutoMapper/AutoMapper/issues/1123

or this issue?

http://stackoverflow.com/questions/26806629/automapper-system-exception-cant-resolve-this-to-queryable-expression

Does ProjectTo<T> work with ResolveUsing?

Thanks in advance
Pete

**Comment by lbargaoanu** [comment]
[No](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#custom-projection)

**Comment by jbogard** [comment]
Use MapFrom. Entity Framework can never and will never recognize any random Func, you have to supply it with an Expression, so use MapFrom. Not any custom value resolver (no query provider would know what to do with one), or any of the func-based extensions. Just expressions.

**Comment by pvranich** [comment]
lol.... fair point.... bad me for not reading the documentation properly!

Thanks for getting back so quickly

is there a way to resolve the issue of all fields in a object graph being queried? I have quite a deep and wide object hierarchy but in most cases my DTO's are quite light and usually map to a handful of fields

> When using an ORM such as NHibernate or Entity Framework with AutoMapper's standard  Mapper.Map  functions, you may notice that the ORM will query all the fields of all the objects within a graph when AutoMapper is attempting to map the results to a destination type.

and then call Map seperatley?

**Comment by TylerCarlson1** [comment]
That's the thing with Projections.  It will only query your DTO fields.  You don't have to do anything special just ProjectTo and whatever you have mapped between the Entity and DTO will be queried from the database.

**Comment by pvranich** [comment]
Got it

thanks for the clarification

**Comment by Worthy7** [comment]
@jbogard Can I revisit this?
I cannot understand why we couldn't develop this to make it work.

My setup is that I have a permission system that depends on the users session to decide if they are allowed to edit an entity (which will show buttons on the front end).

These permissions can be quite complex, so I am actually using the Specification Pattern, but basically I have code like this inside a class which depends on DI to get my permission manager (so this class HAS to be Injected):

```
public class EditableShipmentSpecification : MapableSpecification<ShipmentEntity>, ITransientDependency
    {
        private readonly IPermissionChecker _permiss;
        public EditableShipmentSpecification(IPermissionChecker permis)
        {
            _permiss = permis;
        }

        public override Expression<Func<ShipmentEntity, bool>> ToExpression()
        {
            //if this is true, we can edit regardless
            bool skipermission = _permiss.IsGranted(PermissionNames.AllowShipmentEditEvenIfInvoiced);

            //Admins
            if (_permiss.IsGranted(PermissionNames.FullEdit_Any_Shipment))
                return (shipment) => (!shipment.IsDeleted && true);


            //maintenance, or supplier.
            if (_permiss.IsGranted(PermissionNames.FullEdit_Last_OwnedShipments))
                return (shipment) => !shipment.IsDeleted &&
                    shipment.Order.IsDeleted == false &&
                    && shipment.Printed == false;


            //default
            return (shipment) => (false);
        }
    }
```


Essentially, calling the `ToExpression` of this class will return a function, which should be usable by EntityFramework.

So, why can't Automapper execute ToExpression at run time (on the users request for data) and feed the expression to EF? I don't see where the problem is?

Thanks

**Comment by lbargaoanu** [comment]
You can pass [parameters](http://docs.automapper.org/en/latest/Queryable-Extensions.html#parameterization).

**Comment by Worthy7** [comment]
@lbargaoanu But my parameters depend on the original entity.

**Comment by lbargaoanu** [comment]
I think maybe you need more queries (maps), one for each permission and then the expressions can be static, not chosen at runtime.
