### ISSUE TITLE
AfterMap order in inherited mapping

### ISSUE THREAD

**Issue by mueblo** [AutoMapper/AutoMapper#1137]
I would not call it a bug, but there is an inconsistency between versions of AutoMapper (tested on 3.3.1 and 4.2.0) regarding the execution order of AfterMap actions in inherited mapping.
Consider the following test:
```csharp
    public class SourceParent
    {
    }

    public class DestinationParent
    {
    }

    public class SourceChild : SourceParent
    {
    }

    public class DestinationChild : DestinationParent
    {
    }

    ...

    public void TestAfterMapInheritanceOrder()
    {
        var afterMapString = new StringBuilder();

        Mapper.CreateMap<SourceParent, DestinationParent>()
            .AfterMap((src, dest) => afterMapString.Append(" > parent"));
        Mapper.CreateMap<SourceChild, DestinationChild>()
            .IncludeBase<SourceParent, DestinationParent>()
            .AfterMap((src, dest) => afterMapString.Append(" > child"));

        var fooChild = new SourceChild();
        Mapper.Map<DestinationChild>(fooChild);
        Assert.Equal(" > parent > child", afterMapString.ToString());
    }
```
In version 3.3.1, the test pass. Parent's AfterMap actions are executed before child's AfterMap actions.
In version 4.2.0, the test fail (result is " > child > parent"). Child's AfterMaps are executed first.

When changing AutoMapper version in existing applications, this may cause subtle bugs.
It is not obvious which solution is right though (parent first or child first).
I think it should at least be documented, and maybe become an option somewhere in the mapping configuration.

I did not test it, but I assume it's the same with BeforeMap.

**Comment by jbogard** [comment]
In this case, you shouldn't assume any order, since there's no way to
control it.
