### ISSUE TITLE
ProjectTo in EntityFramework 7

### ISSUE THREAD

**Issue by gdoron** [AutoMapper/AutoMapper#1140]
Hi,

I'm trying to use `ProjectTo` in EntityFramework 7, but getting the error:

> System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryable`1..ctor(IAsyncQueryProvider provider)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor._CreateEntityQueryable[TResult](IAsyncQueryProvider entityQueryProvider)

This is the query I'm trying to execute:

```
var results = await _context.Posts.Include(x=> x.User)
                .Where(x => x.ForumId == forumId && x.ReplyToPostId == null)
                .Skip(pageSize*page)
                .Take(pageSize)
                .ProjectTo<PostListViewModel>(_mapperConfiguration)
                .ToListAsync();
```

And this is the mapping:

```
var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Post, PostListViewModel>()
                    .ForMember(d => d.UserName, options => options.MapFrom(x => x.User.UserName));
            });
```

Am I doing something wrong or Automapper simply doesn't support EF 7 as of now?

Thanks

**Comment by jbogard** [comment]
I have no idea. Have you tried NOT using Automapper, and replace ProjectTo
with Select? Doing a manual LINQ projection?

**Comment by gdoron** [comment]
Oops, this is such a basic query and the exception seemed so weird (null provider?) so I didn't if think it could be a bug in EF itself.
aspnet/EntityFramework#4637

Sorry.
