### ISSUE TITLE
Child -> parent conversion issue

### ISSUE THREAD

**Issue by kois** [AutoMapper/AutoMapper#1143]
Before 4.2.0 I used this code to convert my objects:

```
public static DTOParent ConvertDTOType(Type fromType, Type toType, DTOParent convertableDTO)
        {
            AutoMapper.Mapper.CreateMap(fromType, toType);
            return (DTOParent)AutoMapper.Mapper.Map(convertableDTO, fromType, toType);
        }
```

In the new 4.2.0/4.2.1 version I changed it to the following:
```
public static DTOParent ConvertDTOType(Type fromType, Type toType, DTOParent convertableDTO)
        {
            var mapper = new AutoMapper.MapperConfiguration(cfg => { cfg.CreateMap(fromType, toType); }).CreateMapper();
            return (DTOParent)mapper.Map(convertableDTO, fromType, toType);
        }
```
It is working fine but I always create a mapper object. That is why I changed it to the following:
```
private static AutoMapper.IMapper mapper = new AutoMapper.MapperConfiguration(cfg => { cfg.CreateMissingTypeMaps = true; }).CreateMapper();

public static DTOParent ConvertDTOType(Type fromType, Type toType, DTOParent convertableDTO)
        {
            return (DTOParent)mapper.Map(convertableDTO, fromType, toType);
        }
```
It is faster then the previous version but when I convert child object to parent object it returns child type object instead of the previous versions works. The previous version returns parent type object.

I need conversion parent to child and child to parent too and I have to use dynamic types.

**Comment by TylerCarlson1** [comment]
Maybe you should try [Conditional Object Map](https://github.com/AutoMapper/AutoMapper/wiki/Conventions#conditional-object-mapper) instead of CreateMissingTypeMaps = true.  There you can get two types and determine if they are allowed to map to each other.  So if it's dynamic you can make rules like namespace, or can't be the same type, or names with prefix/postfix, or whatever else you want to use.  Heck you can even say either source or destination type HAS to be DTOParent and both can't be the same and it would work for your scenario.

**Comment by kois** [comment]
When I use Conditional Object Map I got similar issue to the CreateMissingTypeMaps. So when I'm trying cast child object to parent object I got child type object.
This is what I am using:
MapperConfiguration(cfg => { cfg.AddConditionalObjectMapper().Conventions.Add((s) => { return true; }); })

**Comment by TylerCarlson1** [comment]
Sorry didn't notice this before, but why is DTOParent the source and destination value of the mapper?
AutoMapper isn't designed to map objects to themselves.

**Comment by kois** [comment]
Sorry my English is poor. Here is a sample what I want.

abstract class DTOParent
{
}

Class A : DTOParent
{
}

Class B : A
{
}

I need convert "B" class to "A" class. It's important, that the class type which has been returned is "A".

In the old version it is worked correctly.

public static DTOParent ConvertDTOType(Type fromType, Type toType, DTOParent convertableDTO)
{
AutoMapper.Mapper.CreateMap(fromType, toType);
return (DTOParent)AutoMapper.Mapper.Map(convertableDTO, fromType, toType);
}

**Comment by lbargaoanu** [comment]
@kois Please make a gist with a minimal executable example that fails and I'll take a look.

**Comment by kois** [comment]
The above sample what I posted is not good?

**Comment by kois** [comment]
Here is the executable example. I hope this can help.

[AutoMapper_Sample.zip](https://github.com/AutoMapper/AutoMapper/files/154675/AutoMapper_Sample.zip)

**Comment by lbargaoanu** [comment]
[This](https://gist.github.com/lbargaoanu/8263a9f001107ac6ae1b#file-gistfile1-txt) works. Because SampleChild is derived from Sample, AutoMapper just returns the input. That's by design. Creating a map would override this. But then I think you should create all the maps, mixing dynamic mapping with static mapping might not be the best thing.

**Comment by kois** [comment]
I know that I can declare mapping with CreateMap(), but I have more than 100 DTO. My problem is that I can not add new mapping in runtime just in the config declaration.

"AutoMapper.Mapper.CreateMap(fromType, toType);" worked fine because this did it runtime.

**Comment by lbargaoanu** [comment]
You don't have to do it by hand. You can have some reflection code to call CreateMap.

**Comment by jbogard** [comment]
Dynamic mapping is only intended for cases where you don't know the types at compile time. Not because you don't want to call CreateMap.

I suggest you take about 30 minutes to add in all those CreateMap calls if you know the types at compile time. You'll save yourself sooooo many headaches in the future.

**Comment by kois** [comment]
@jbogard thanks for nothing. "I suggest you take about 30 minutes to add in all those CreateMap calls if you know the types at compile time...".

The problem is that the new 4.2.x automapper versions functionality is different from the older version. The older versions worked dynamic mapping, but the new doesn't.

**Comment by jbogard** [comment]
Well, you're using it in a way that's not the way it was designed. That's
when stuff breaks. I have tests to cover the way the original intent was
conceived but I can't help scenarios I break that I'd never thought of or
never wanted to do.

Seriously though, you always should have used CreateMap. Dynamically
creating maps unless the type is unknown like anonymous types is a bad
idea. And if I can switch nearly 1000 tests over to an instance API from a
static one, a couple hundred CreateMap calls shouldn't be bad. Tedious,
yes, but a far better choice in the long run.

After all, you should be using AssertConfigurationIsValid, which is
impossible with DynamicMap. Your use, as I understand it, is an incorrect
and unsupported use. I accidentally break unsupported use cases sometimes,
it happens.

**Comment by kois** [comment]
@jbogard 
I added a new IsValid() method to my example. Please check the isValid results in the example. I think it is not good... Thank you for your answers.

[AutoMapper_Sample.zip](https://github.com/AutoMapper/AutoMapper/files/156698/AutoMapper_Sample.zip)
