### ISSUE TITLE
MapperConfiguration.CreateMissingTypeMaps overriding specific configuration 

### ISSUE THREAD

**Issue by OlafurD** [AutoMapper/AutoMapper#1147]
I have a mapping between a source type and a destination type, where the properties name differ:

`.ForMember(dest => dest.Comments, opt => opt.MapFrom(src => src.TransactionComments))`

When createMissingTypeMaps is set to false, the mapping works fine. But when I set it to true, the mapping fails and destination.Comments is null

**Comment by lbargaoanu** [comment]
With dynamic mapping AutoMapper doesn't know to map TransactionComments from Comments.

**Comment by jbogard** [comment]
Yeah I think I need to see more of the configuration besides just this one line. Are you still calling CreateMap?

**Comment by OlafurD** [comment]
```
CreateMap<TransactionComment, TransactionCommentModel>();
CreateMap<Transaction, TransactionModel>()
                .ForMember(dest => dest.Comments, opt => opt.MapFrom(src => src.TransactionComments))
```
dest.Comments is of type List\<TransactionCommentModel\> and src.TransactionComments is of type List\<TransactionComment\>.

**Comment by TylerCarlson1** [comment]
If you are explicitly creating every map yourself, then there's no reason to use CreateMissingTypeMaps.  It's more for dynamic mapping when you don't know what the source and destination might be until run time.  If you have no need for the functionality I wouldn't recommend using it.  If you need dynamic mapping of certain scenarios I would suggest conditional object mapping as a way to filter what should get mapped and not.

**Comment by OlafurD** [comment]
@TylerCarlson1  I was hoping to only explicitly declare mappings between types that differ in some ways (different naming conventions for example) while using the CreateMissingTypeMaps flag to map between  other types

**Comment by lbargaoanu** [comment]
@OlafurD Please make a gist with a minimal executable example that fails and I'll take a look.

**Comment by OlafurD** [comment]
The issue was on my end, I was mapping an entity with a dynamic proxy, thanks for the help :)
