### ISSUE TITLE
Support EF Self Referencing Model and ViewModel Mapping

### ISSUE THREAD

**Issue by rabbal** [AutoMapper/AutoMapper#1149]
hi,
thanks for this project .
In more senario we need to use Self Referencing Models for example Comment System. link following model:

```
public class BlogComment
{
    public int Id { set; get; }

    [MaxLength]
    public string Body { set; get; }

    public virtual BlogComment Reply { set; get; }
    public int? ReplyId { get; set; }
    public ICollection<BlogComment> Children { get; set; }
}    
```
and we can select just one list and then EF can make tree with linq to object like this:
```
using (var ctx = new MyContext())
            {
                var list = ctx.BlogComments
                          //.where ...
                          .ToList() // fills the childs list too
                          .Where(x => x.Reply == null) // for TreeViewHelper                        
                          .ToList();
            }
```

when using CommentViewModel for Select , and then make tree with linq to object , the dynamic Proxy that Generated by EF is destroyed .
Is Supported Mapping Between CommentViewModel that have ICollection<CommentViewModel> and Comment ?

thanks , 
gholamreza rabbal

**Comment by lbargaoanu** [comment]
@rabbal Please make a gist with a minimal executable example that fails and I'll take a look.

**Comment by jbogard** [comment]
So EF technically does not fill the child lists too. It's likely using lazy-loading to fill them in. How would this work with a single Select LINQ projection? Can you write this to work only using EF and LINQ?

**Comment by rabbal** [comment]
@jbogard EF using linq to object to fill this children ! if you profile this query by using [DNTProfiler](https://github.com/VahidN/DNTProfiler/releases) , even if lazyloadig is disabled but, the children are filled again.
[reference](http://www.dotnettips.info/post/977/%D9%85%D8%A8%D8%A7%D8%AD%D8%AB-%D8%AA%DA%A9%D9%85%DB%8C%D9%84%DB%8C-%D9%85%D8%AF%D9%84%E2%80%8C%D9%87%D8%A7%DB%8C-%D8%AE%D9%88%D8%AF-%D8%A7%D8%B1%D8%AC%D8%A7%D8%B9-%D8%AF%D9%87%D9%86%D8%AF%D9%87-%D8%AF%D8%B1-ef-code-first)

with first .ToList() , all comments fetch from database  and then then second .ToList() is linq to object and fill children (even the lazyloading is disabled). I tested it

**Comment by rabbal** [comment]
@jbogard  no just one level. We Select All Comments then for create Tree , We Are using Linq To Object . 
@lbargaoanu [this is one executable sample](http://1drv.ms/1WTA30I)

**Comment by jbogard** [comment]
Then in that case go with two separate DTO types, a parent and a child. The parent has a children, the child has no children properties. Currently your DTOs look like you can navigate any arbitrary depth. LINQ can't handle arbitrary depth, and AutoMapper infers the LINQ from the shape of your DTOs.

**Comment by rabbal** [comment]
this way no support for show multi level comments and is limited

**Comment by jbogard** [comment]
Wait - you said you only wanted one level? I'm confused now. Do you want arbitrary depth? If so, EF doesn't support that with LINQ. So AutoMapper can't support it either. Try and write that LINQ. Your example was just one level - that won't fetch the second level and so on. Execute this with a SQL profiler and you'll see what's going on.

Pretend you didn't have AutoMapper or DTOs or anything. Just your EF models. EF supports this recursion through lazy loading. Every time you access a child property, it fetches that second level through an additional query.

If you turn lazy loading off, you have to explicitly call Include with EF. But that only works at the level you specify, it won't just keep issuing queries for every leaf of the tree.

LINQ projections fetch everything all at once from everything I've seen. They skip any entities, just fill DTOs. If you try and do arbitrary depths, just with plain LINQ, you should see it doesn't work when you try and navigate to higher depths.

When I troubleshoot AutoMapper ProjectTo, the FIRST thing I do is construct the LINQ Select query to work the way I want. I don't know how to create a LINQ Select query to do what you describe.

**Comment by rabbal** [comment]
> Your example was just one level - that won't fetch the second level and so on. Execute this with a SQL profiler and you'll see what's going on.

Please note,I Discuss about showing comments to form of tree . so , I Select just one select without join for fetch all comments without pay attention to tree structure . when all comments are fetched from db , then by filter roots with .Where(a=>a.Parent==null) (linq to object) , the tree is generated . I mean the children are filled. 

I Know for recursive queries we should use CTEs ! but I Discuss about "adjacency list" anti pattern  and for this reason using linq to object for create this tree structure . I Tested this example and if you note I Disabled Lazyloading and didn't use .Include(...) (for join) . 
### result of DNTProfiler
![efprofilerlog](https://cloud.githubusercontent.com/assets/6818642/13441542/fa1396be-e00c-11e5-9a71-c759ede6c50d.PNG)

please test with DNTProfiler.

**Comment by jbogard** [comment]
So I think I'm not sure what you're asking then what AutoMapper supports? In your LINQ example you explicitly select the children. AutoMapper can do that just fine. However, it can't handle self-referencing DTOs in projections. It doesn't know when to stop building out a Select. It would build this:

```
.Select(a=>new { Children = a.Children.Select(b => new {
  Children = b.Children.Select(c => new {
      Children = c.Children.Select(
   /* etc etc etc to infinity */
},a.Body,a.Id,a.Reply,a.ReplyId}
```

And just keep going forever. Your DTOs have to explicitly represent a structure with a finite depth (or you can use MaxDepth to stop the recursion at N levels).

Are you looking to use Mapper.Map or ProjectTo? Mapper.Map handles this just fine.

**Comment by rabbal** [comment]
ah, sorry the select query is like following code 

```
 var list =
                    ctx.BlogComments
                    .ToList()
                    .Where(x => x.Reply == null)
                    .ToList();
```

please change code and then run again.

**Comment by jbogard** [comment]
Where's the Select LINQ projection? You'd need to include that to if you want to see how it would work with ProjectTo.

**Comment by rabbal** [comment]
### Comment Model 
```
 public class BlogComment
    {
        public virtual int Id { set; get; }

        [MaxLength]
        public virtual string Body { set; get; }

        public virtual BlogComment Reply { set; get; }
        public virtual int? ReplyId { get; set; }
        public virtual ICollection<BlogComment> Children { get; set; }
        public virtual string ExtraProperty { get; set; }
    }
```

### DbContext

```
public class MyContext : DbContext
    {
        public MyContext():base("DefaultConnection")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
        public DbSet<BlogComment> BlogComments { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Self Referencing Entity
            modelBuilder.Entity<BlogComment>()
                .HasOptional(x => x.Reply)
                .WithMany(x => x.Children)
                .HasForeignKey(x => x.ReplyId)
                .WillCascadeOnDelete(false);

            base.OnModelCreating(modelBuilder);
        }
    }
```

### Test Class

```
 public static class Test
    {
        public static void RunTests()
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<MyContext, Configuration>());
            using (var ctx = new MyContext())
            {
                var list =
                    ctx.BlogComments
                    .ToList()
                    .Where(x => x.Reply == null)
                    .ToList();
                
            }
        }
```

**Comment by jbogard** [comment]
Ha! I've done that enough times, hit the Close button.

So let's hit reset. I understand your EF model. I don't see your DTO, if you can update your comment with that I would understand what your treeview control needs.

What are you trying to get AutoMapper to do here? Use Mapper.Map? ProjectTo?

**Comment by TylerCarlson1** [comment]
Are you talking about [this](http://www.matthidinger.com/archive/2011/11/27/Writing-a-Fluent-ASP-NET-MVC-Recursive-TreeView-Helper.aspx).  I might be wrong but it looks like the tree viewer.  I think the problem is the tree viewer will recursively get the child classes through child elements, and the problem is that it's loaded through multiple calls to the database which Automapper stopped when you translate the object.
If you ProjectTo or Mapper.Map you go from a EF proxy object, which can load child elements when you access the property, to a ViewModel that looses this functionality.

So are you saying if you use Automapper, you can't recursively call ChildList over using the TreeViewHelper to get all the children and grand children?

**Comment by lbargaoanu** [comment]
@rabbal Maybe I'm missing your point, but [this](https://gist.github.com/lbargaoanu/b5f75a6ff289cbf4f98d) works.
