### ISSUE TITLE
byte[] to string & string to byte[]

### ISSUE THREAD

**Issue by suddenelfilio** [AutoMapper/AutoMapper#1153]
The latest Automapper broke our db timestamp version field mapping. which is byte[] to string => the mapping results in "System.Byte[]" where in previous versions we got a textual representation of the byte[]. 

We currently solved it by defining 2 custom type converter which casts byte[] to base64 string and the other way around. This was how it used to work.

Not sure if this is by design in the new version or just overlooked.

**Comment by jbogard** [comment]
What was the old version?

**Comment by Meertman** [comment]
@jbogard, we had the same problem.

The version of AutoMapper in which it still worked was version 4.2.1.
The version in which this functionality broke is version 5.0. Not sure if this was expected or not.

**Comment by lbargaoanu** [comment]
It's by design.

**Comment by lbargaoanu** [comment]
Of course we could add it back in, but I don't know. It's easy enough to implement outside AM and choosing Base64 does seem a bit arbitrary.

**Comment by Meertman** [comment]
@lbargaoanu, I just encountered the same problem and wanted to give additional information to @jbogard. I already fixed our code so the mapping was explicit, and agree that choosing base64 is a bit arbitrary.
