### ISSUE TITLE
Custom resolvers/convertors/... missing release/dispose, possible memory leak issue

### ISSUE THREAD

**Issue by rehoutm** [AutoMapper/AutoMapper#1154]
I have digged a bit into the AutoMapper code and it seems that custom resolvers/convertors etc., constructed by IoC containers via "ConstructServicesUsing" are not disposed in any way, which makes it practically impossible to release it from container.

In certain scenarios and container behaviours (i.e. default behaviour with Windsor Castle and IDisposable transient resolver) this issue can lead to massive memory leaks.

Is to possible to implement:

- Disposing of IDisposable resolvers,
- or, in addition to the "ConstructServicesUsing" also some "ReleaseServicesUsing" method?

**Comment by lbargaoanu** [comment]
You can solve this from your container. Return all these objects from a child container and dispose that when you know it's safe.

**Comment by jbogard** [comment]
This. Use a child container to create an IMapper. Then you're set.

**Comment by rehoutm** [comment]
I think a child container is an overkill, and actually it may get kind of really complicated with scoped/per web request depedencies on the resolver itself.

Altho your kind advices led me to another solution - right now, I have the automapper being resolved as a singleton. Instead of that, I will use some sort of wrapper around it, that will be Disposable and will take care of resolving and releasing resolvers.

**Comment by jbogard** [comment]
Ah yes, that's effectively the same. Hopefully this scenario becomes easier
in the future, as the Mapper instance has the factory callback scoped to
that instance.
