### ISSUE TITLE
Upgrade from 4.0.4 to 4.2.1 caused InvalidOperationException (sequence contains no elements)

### ISSUE THREAD

**Issue by nak2000** [AutoMapper/AutoMapper#1161]
the exception happens in AutoMapper.Internal.ReflectionHelper.<GetMemberPath>d__6.MoveNext()

it used to work ok in the earlier version
we have a repository that internally uses EF, and automapper, we pass the members to expand from odata into this repository as a parameter, now if no items have been selected for expansion in the odata query, an array with single item containing string.empty is passed, since just passing a null is not allowed , this used to work fine in the earlier version but has now stopped working, the array of members to expand is known only at runtime

**Comment by jbogard** [comment]
I'll need your source/destination types, configuration calls, and how you're calling Map.

**Comment by nak2000** [comment]
Hi
below are the code snippets for my controller, repository and helpers
		
		//Controller in Webapi ODATA
		[EnableQuery(PageSize = GlobalConstants.MaxPageSize, AllowedQueryOptions = AllowedQueryOptions.Supported)]
        [ODataRoute("Buckets")]
        public IQueryable<BucketDTO> GetBuckets([ODataQueryParameterBinding] ODataQueryOptions<BucketDTO> options)
        {
            return BucketRepository.GetAll(ODataHelper.GetExpandedItems(options));
        }
		
		//Helpers to get items to expand
		public static string[] GetExpandedItems(ODataQueryOptions options,string implicitCommaSeperatedExpands)
        {
            var expanded = GetExpanded(options);
            var implicitExpanded = ( !string.IsNullOrWhiteSpace(implicitCommaSeperatedExpands) )
                ? implicitCommaSeperatedExpands.Split(',')
                : new[] {string.Empty};
            string[] expandedItems = (expanded != null) ? expanded.Split(',') : new[] { string.Empty };
            return expandedItems.Union(implicitExpanded).ToArray();
        }		
		
        public static string GetExpanded(ODataQueryOptions options)
        {
            string expandedItems = null;
            var  expandBuilder = new StringBuilder();
            try
            {
                if (options.SelectExpand != null)
                {
                    SelectExpandClause expandClause = options.SelectExpand.SelectExpandClause;
                    ParseExpandedItems(expandClause, expandBuilder);
                    expandedItems = expandBuilder.ToString();
                }
                if (expandedItems != null && expandedItems.EndsWith(","))
                {
                    expandedItems = expandedItems.Remove(expandedItems.Length - 1);
                }
            }
            catch (ODataException)
            {
                
            }
            return expandedItems;
        }		
		
		
		//Repository

        //Mapping Config in repository
            CreateMap<Bucket, BucketSimpleDTO>().ReverseMap();
            CreateMap<Bucket, BucketDTO>()
                .ForMember(dest => dest.Loads, opts => opts.ExplicitExpansion())
                .ForMember(dest => dest.Configuration, opts => opts.ExplicitExpansion())
                .ForMember(dest => dest.Comments, opts => opts.ExplicitExpansion())
                .ForMember(dest => dest.Fleet, opts => opts.ExplicitExpansion())
                .ReverseMap();


		//this used to work in the past
        public IQueryable<BucketDTO> GetAll(string[] getExpandedItems)
        {
            return _db.Set<Bucket>().AsNoTracking().Project().To<BucketDTO>(null, getExpandedItems);
        }
		
		
		**//after upgrade to new automapper**
        public IQueryable<BucketDTO> GetAll(string[] getExpandedItems)
        {
            return _db.Set<Bucket>().AsNoTracking().ProjectTo<BucketDTO>(null, getExpandedItems); //now throws exception
        }

**Comment by lbargaoanu** [comment]
What about passing an empty array? :)

**Comment by nak2000** [comment]
Tried empty array and null as well, got similar exceptions

**Comment by lbargaoanu** [comment]
This seems to work with the MyGet build. If you disagree you'll have to make a gist with a minimal repro (using just EF) that I can copy paste and execute.

**Comment by nak2000** [comment]
Sorry it was my bad, I was sending in a null, instead of new string[0]
it's working now, so issue resolved with this workaround, thanks.

**Comment by nak2000** [comment]
one more question ,
if i had to do nested expand, in above example
.ForMember(dest => dest.Loads, opts => opts.ExplicitExpansion())
and the Load collection has 
.ForMember(dest => dest.Status, opts => opts.ExplicitExpansion())

could I pass in "Loads.Status", and would it do the nested expand, or I'll need to explicitly specify the expression

**Comment by lbargaoanu** [comment]
You can and with expressions it works with Select as in #979.

**Comment by kedirbedaso** [comment]
i have Interface Manager solution going to - Update Automapper  version 4.0.4 to version 4.2.1 how i may do changes ?
