### ISSUE TITLE
Can't access ResolutionContext.Mapper in custom object mapper

### ISSUE THREAD

**Issue by mrmashal** [AutoMapper/AutoMapper#1165]
In the source code of AutoMapper, there seems to be a public `Mapper` property in the `ResolutionContext` class, but I get a "Cannot resolve symbol 'Mapper'" when trying to access `context.Mapper`:

```
    public class MyMapper : IObjectMapper
    {
        public object Map(ResolutionContext context)
        {
            context.Mapper.Map(...);
        }
    }
```

I need to access the runtime mapper in my custom mapper, using the non-static API.

Thanks

**Comment by jbogard** [comment]
In 5.0 the Mapper property is there. And easier to use too. But you'll need to use the 5.0 beta builds to get at it.

**Comment by mrmashal** [comment]
Thanks for the reply. Actually I found a `context.Engine.Mapper` after posting this, and it seems to work fine (using v4.2.1). Let me know if there'll be some issues with this.

I'm closing the issue for now. Thanks for the great stuff :)
