### ISSUE TITLE
Do all mapping in one place with the new API changes?

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1167]
Before the change not to use the static API, I had just one static class with one method where I did all the mappings I needed. I called this method in Application_Start.

I also had an 'IgnoreUnmapped' extension which used Automapper's static FindTypeMapFor method.

So, for example, I had:
`
        public static void Map()
        {
            Mapper.CreateMap<CustomerModel, CustomerDto>().ReverseMap();
            Mapper.CreateMap<CustomerAddressModel, CustomerAddressDto>().ReverseMap();
            Mapper.CreateMap<CustomerBankModel, CustomerBankDto>().ReverseMap()
                .IgnoreUnmapped();
            Mapper.CreateMap<CustomerCourseModel, CustomerCourseDto>().ReverseMap()
                .ForMember(model => model.Field1, option => option.Ignore())
                .ForMember(model => model.Field2, option => option.Ignore());
        }
`

So now where am I going to place all my mapping?

**Comment by aoxue** [comment]
mark

**Comment by jslatts** [comment]
Create a mapping profile class (derived from Profile) and override Configure() with your mappings:

    public class CustomProfile : Profile
    {
      public CustomProfile() : base(nameof(CustomProfile)) { }

      protected override void Configure()
      {
        CreateMap<CustomerModel, CustomerDto>().ReverseMap(); 
        CreateMap<CustomerAddressModel, CustomerAddressDto>().ReverseMap(); 
        CreateMap<CustomerBankModel, CustomerBankDto>().ReverseMap().IgnoreUnmapped(); 
        CreateMap<CustomerCourseModel, CustomerCourseDto>().ReverseMap().ForMember(model => model.Field1, option => option.Ignore()).ForMember(model => model.Field2, option => option.Ignore());
      }
    }


Then, depending on how your app is set up, instantiate it and use it. In my case, I inject it with Ninject.

    var mapperConfig = new MapperConfiguration(config => config.AddProfile<CustomProfile>());
    mapperConfig.AssertConfigurationIsValid();

    // Ninject
    kernel.Bind<IMapper>().ToConstant(mapperConfig.CreateMapper());

    // Without ninject
    var mapper = mapperConfig.CreateMapper();
    CustomerDto dto = mapper.Map<CustomerModel>(model);
    
Not sure what to do about the extension. Maybe someone else can chime in.

**Comment by jbogard** [comment]
The static API is back in 4.2.1, just call Mapper.Initialize instead.

**Comment by cryo75** [comment]
Will the static API be still there in 5.0?

**Comment by jbogard** [comment]
Yep just Mapper.CreateMap is gone. 4.2.1 updated which API were obsolete.

**Comment by f135ta** [comment]
This works like an absolute dream! Nice one!
