### ISSUE TITLE
Map using intermediate object.

### ISSUE THREAD

**Issue by gibletto** [AutoMapper/AutoMapper#1173]
I have a very common pattern when mapping objects that use the source to generate a new object, which I then pull the Properties from to construct the object.

`CreateMap<Product, ProductViewModel>()
     .ForMember(x => x.Name, opt => opt.ResolveUsing<LocalizedProductNameResolver>))`

Usually, this would mean a custom localizer per localization of a property.

I tend to store them in a generic dictionary, so it would be nice to be able to resolve the dictionary instead in the mapping, so I can even have a generic resolver using a base class.

`CreateMap<Product, ProductViewModel>()         
     .ForMember(x => x.Name, opt => opt.Use<LocalizedResolver, Dictionary<string, object>>().From(x => x["Name"])` 

or something similar.

Maybe I am missing a trick here, but if it's possible another way, that would also be helpful.

**Comment by lbargaoanu** [comment]
Like in #1005?

**Comment by gibletto** [comment]
That is providing additional items to create the mapping with, but in this case, I have everything I need in the source already, and I provide ambient context to the valueresolver. I want to be able to write a generic mapper for this base class (LocalizedEntity<T> where T is Product in the above case and can be provided by opt.ResolveUsing<LocalizedEntityValueResolver<LocalizedEntity<Product>>()

I then what to use that as the new source.

**Comment by lbargaoanu** [comment]
TypeConverters could help. You can return the dictionary from your resolver and define a type converter from the dictionary to your destination property type. If this doesn't make sense, it's better to make a runnable gist with two examples and what you're trying to reuse between them.

**Comment by TylerCarlson1** [comment]
Maybe #983's example is what you are looking for.  It might not be exactly what you want but it's the general idea.  It supports a similar localization example, but the implementation is different, so the code wouldn't be exactly the same for you.
