### ISSUE TITLE
Can not map inherited property by its name

### ISSUE THREAD

**Issue by PaterSantyago** [AutoMapper/AutoMapper#1184]
This code works:
```
CreateMap<Models.IPhaseSource, BusinesObjects.IPhaseSource>()
                .ForMember(x => x.EditLevelAdded, opt => opt.Ignore())
                .Include<Models.MatrixPhaseSource, BusinesObjects.MatrixPhaseSource>()
                .Include<Models.SixtySecondsPhaseSource, BusinesObjects.SixtySecondsPhaseSource>();
```

This code throws ArgumentOutOfRange with message "Cannot find a field or property named EditLevelAdded"
```
CreateMap<Models.IPhaseSource, BusinesObjects.IPhaseSource>()
                .ForMember("EditLevelAdded", opt => opt.Ignore())
                .Include<Models.MatrixPhaseSource, BusinesObjects.MatrixPhaseSource>()
                .Include<Models.SixtySecondsPhaseSource, BusinesObjects.SixtySecondsPhaseSource>();
```

P.s. EditLevelAdded property is declared in base interface of BusinesObjects.IPhaseSource

**Comment by jbogard** [comment]
What version of AutoMapper?

**Comment by PaterSantyago** [comment]
4.2.1

**Comment by lbargaoanu** [comment]
@PaterSantyago  I don't see it. Can you try the MyGet build?

**Comment by PaterSantyago** [comment]
Same story with v5.0.0-ci-1037. Here is [link](https://yadi.sk/d/Js-wFozLqCHGb) for sample solution with reproduced issue.

**Comment by dougajmcdonald** [comment]
I'm still seeing this in 6.1.1

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
