### ISSUE TITLE
ConvertUsing does not work with nulls

### ISSUE THREAD

**Issue by pantonis** [AutoMapper/AutoMapper#1187]
I have following code:

` public class CustomTypeConverter : ITypeConverter<ItemPhoto, string>
    {
        public string Convert(ResolutionContext context)
        {
            if (context == null || context.IsSourceValueNull)
                return etccccc;

            ListingPhoto source = (ListingPhoto)context.SourceValue;

            return source.Path + etccccc;
        }
    }

   public class ItemPhoto
    {
        public long Id { get; set; }
        public string Path { get; set; }
    }`

And Im calling `CreateMap<ItemPhoto, string>().ConvertUsing<CustomTypeConverter>();`

Everything seems to be working fine only if the ItemPhoto is not null. If it is null is doesn't even go to Convert inside CustomTypeConverter. It seems like it is ignoring null value.

Any idea?

**Comment by lbargaoanu** [comment]
It depends on the Map overload you're calling. On the MyGet build the following does what you want:

    mapper.Map<ItemPhoto, string>(null)

**Comment by pantonis** [comment]
The ItemPhoto is an array and it is nested inside T.
If T has some value but T.ItemPhoto[] is nullI get the problem that the CustomTypeConverter does not get fired.

**Comment by lbargaoanu** [comment]
Make a gist that I can execute and see fail and I'll take a look.

**Comment by pantonis** [comment]
I got a workaround by using a T type as destination instead of string. 
Thanks anyway.

**Comment by lucky3** [comment]
I think there is a problem with mapping null to nullable type in version 4.2.1
I've created a gist to show the problem: https://gist.github.com/lucky3/117a4c0f24b8c262016c3aa7e44d1e10

**Comment by lbargaoanu** [comment]
@lucky3 Try the MyGet build.
