### ISSUE TITLE
ResolveUsing does not work in nested object

### ISSUE THREAD

**Issue by BruceCowan-AI** [AutoMapper/AutoMapper#1188]
ResolveUsing when in a nested object gives a mapping failure in 4.2.1. It worked fine in 3.2.1. See https://gist.github.com/BruceCowan-AI/c768eb04619c3a9101f3 for sample code complete with tests (it is kind of long to put here).

**Comment by lbargaoanu** [comment]
This works with the MyGet build.

**Comment by BruceCowan-AI** [comment]
Thanks, glad to know it is fixed.

**Comment by lbargaoanu** [comment]
You can close your issue.
