### ISSUE TITLE
System.Security.VerificationException: Operation could destabilize the runtime

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#119]
<b>bpipe[CodePlex]</b><br />Silverlight 4 project, Mapping from Class to Interface.<br /><br />Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GetTypeImplementerMapping&#40;Type&#91;&#93; interfaces, Type proxyTargetType, IEnumerable&#96;1&#38; contributors, INamingScope namingScope&#41;<br />Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType&#40;String typeName, Type proxyTargetType, Type&#91;&#93; interfaces, INamingScope namingScope&#41;<br />Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode&#40;Type proxyTargetType, Type&#91;&#93; interfaces, ProxyGenerationOptions options&#41;<br />Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget&#40;Type interfaceToProxy, Type&#91;&#93; additionalInterfacesToProxy, ProxyGenerationOptions options&#41;<br />Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget&#40;Type interfaceToProxy, Type&#91;&#93; additionalInterfacesToProxy, ProxyGenerationOptions options&#41;<br />Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget&#40;Type interfaceToProxy, Type&#91;&#93; additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor&#91;&#93; interceptors&#41;<br />Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget&#40;Type interfaceToProxy, IInterceptor interceptor&#41;<br />AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.CreateObject&#40;ResolutionContext context&#41;<br />AutoMapper.Mappers.TypeMapObjectMapperRegistry.NewObjectPropertyMapMappingStrategy.GetMappedObject&#40;ResolutionContext context, IMappingEngineRunner mapper&#41;<br />AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map&#40;ResolutionContext context, IMappingEngineRunner mapper&#41;<br />AutoMapper.Mappers.TypeMapMapper.Map&#40;ResolutionContext context, IMappingEngineRunner mapper&#41;<br />AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map&#40;ResolutionContext context&#41;

**Comment by mejustandrew** [comment]
This `Exception` is thrown now by the VSTests (ran under build pipelines with AzureDevOps) and it started from version 7.0.1. The last version working properly for VSTS (now AzureDevOps) is 6.2.2. The exception looks like this:
>System.Security.VerificationException: Operation could destabilize the runtime.
Stack Trace:
    at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 57
...

I could neither reproduce the exception locally nor isolate it from VSTests.

**Comment by mikeruhl** [comment]
I'm getting this too.  This just started happening in Azure DevOps and I can reproduce locally using vstest.console.
```
Failed   CachedCategoryResponseShouldConvertBaseType
Error Message:
 System.Security.VerificationException : Operation could destabilize the runtime.
Stack Trace:
   at AutoMapper.Mapper.Initialize(Action`1 config) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 46
   at BrevitySearchServiceTests.MappingTests.CreateMaps() in C:\Users\mrul\source\repos\BoardmakerServices\CoreServices\BrevitySearchService.Tests\MappingTests.cs:line 24
```
I'm using NUnit 3 and CreateMaps is my SetUp method.  I've tried with the MTest adapter too and I'm getting the same response.  Tests not using Automapper do not throw an exception.

I've tried one common solution to use ```[assembly: SecurityRules(SecurityRuleSet.Level1, SkipVerificationInFullTrust = true)]``` but that didn't help anything.

I've also tried converting the project to netstandard20.  Can't get past that error.  Running tests from inside Visual Studio works just fine.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by mikeruhl** [comment]
@lbargaoanu I made a sln with steps to reproduce and a solution, which will hopefully help you with insight as to why it's happening.
https://github.com/mikeruhl/AutoMapperAndVsTest.Console

**Comment by lbargaoanu** [comment]
That works for me. If I were you, I wouldn't focus on AM. There is smth in that stack that causes the error. But I would be surprised if it's AM itself.

**Comment by mejustandrew** [comment]
@lbargaoanu I tried this with multiple projects and later versions of AutoMapper than 6.2.2 cause this error. I mean when updating the AutoMapper to a newer version this error occurs, and going back to 6.2.2 makes the error disappear.

It is not a critical issue since there are few [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/) pipelines that involve AutoMapper and unit tests, and the fix is simple, which involves going to this stable AutoMapper version, but the bug exists for sure.

**Comment by lbargaoanu** [comment]
Code changes. But that doesn't mean much.

**Comment by SeanK1191** [comment]
Just experienced this issue after adding AutoMapper 8.0.0 to an ASP.NET project. Tests pass locally in VS fine but error in Azure Devops with this:

```
Unable to create instance of class... Error: System.Security.VerificationException: Operation could destabilize the runtime..

at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 57
```

Down-grading to 6.2.2 solved it for me.

**Comment by jbogard** [comment]
@SeanK1191 we can't reproduce this, if you have a new issue please open one.
