### ISSUE TITLE
some error occured in my project!

### ISSUE THREAD

**Issue by chenzhikang** [AutoMapper/AutoMapper#1191]
when i include automapper version4.2.1 in my aspnet mvc5  project.i convert Product type to ProductDto Type,but there was a issue occured.that is the property of the Product Type named MainPicture missing when convert to ProductDto Type.it was very strange.and it only in a certain time will appear. my code is following:
//this is the mapping code;
`   Mapper.Initialize(cfg =>
            {
                var mapping = cfg.CreateMap<Product, ProductDto>();
                mapping.ForMember(d => d.ProductName, opt => opt.MapFrom(s => s.ProductName));
                mapping.ForMember(d => d.Url, opt => opt.MapFrom(s => s.BuyUrl));
                mapping.ForMember(de => de.Abstract, opt => opt.MapFrom(s => s.ProAbstract));
                mapping.ForMember(d => d.StoreToken, opt => opt.MapFrom(s => s.Mall.Token));
                mapping.ForMember(d => d.OriginStoreName, opt => opt.MapFrom(s => s.Mall.Name));
                mapping.ForMember(d => d.Picture, opt => opt.MapFrom(s => s.MainPicture));
            });`
//this is the code where real convert  action;i convert Product(Domain Entity) to ProductDto object.
pagedlist.Select(s => s.MapTo(dto));

who can tell me the reason?is it the automapper's problem or myself ?

**Comment by chenzhikang** [comment]
Was the issue because the s.Mall.Token cause?the Mall may be null?and it trigger others?

**Comment by lbargaoanu** [comment]
Make a gist that I can execute and see fail and I'll take a look.
