### ISSUE TITLE
Missing Map Exception thrown when Map exists

### ISSUE THREAD

**Issue by davidsk** [AutoMapper/AutoMapper#1194]
I'm using Automapper in conjunction with Autofac and Breeze.  There doesn't appear to be any issue with the libraries other than when I attempt to project the entity to dto using the IQueryable extensions, I get the following error: 

> Missing map from GenericObject to Gadget. Create using Mapper.CreateMap<GenericObject, Gadget>;

Here's my configuration:

```
            builder.Register(ctx => new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<GenericObject, Gadget>();
            }))
            .AsSelf()
            .SingleInstance();

            // validate mappings    
            Mapper.AssertConfigurationIsValid();

            builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<IMapper>().InstancePerLifetimeScope();
```
the call I'm making in the controller looks like this:

`return _contextProvider.Context.GenericObjects.ProjectTo<Gadget>(_mapConfig);`

(_contextProvider is a breeze wrapper around context but I get the same error hitting the context directly)

_mapConfig is injected using AutoFac.  Inspecting this shows that the mapping is there.

![image](https://cloud.githubusercontent.com/assets/974827/13905366/9e73dbae-eeb5-11e5-8ba6-7383a2250833.png)

**Comment by TylerCarlson1** [comment]
`return _contextProvider.Context.GenericObjects.ProjectTo<Gadget>(_mapConfig.ConfigurationProvider);` should work.

It's weird I know

**Comment by davidsk** [comment]
Yup, that sorted it.  Thanks.

**Comment by dfaivre** [comment]
Any chance we can make the API more explicit so it doesn't take the configuration object?

**Comment by dfaivre** [comment]
Actually, using 4.2.1 I don't see a ConfigurationProvider on the MapperConfiguration object anymore.  It simply implements IConfigurationProvider.

**Comment by jbogard** [comment]
@dfaivre in 4.2.1 you can just use Mapper.Initialize and ProjectTo without any arguments. I restored some of the static API.

**Comment by dfaivre** [comment]
Thanks @jbogard.  I had rewritten to the non-static API, and was getting the same error as this issue talked about using the `ProjectTo<T>(config)` call.  It then magically went away -- may have been a dev server restart issue.  I'll keep an eye on it.

Thanks for the great work on this project.
