### ISSUE TITLE
Is it possible to set MaxDepth during runtime?

### ISSUE THREAD

**Issue by vipasane** [AutoMapper/AutoMapper#1196]
If a have a full existing mapping between DTOs and entities but in some cases I would like to enforce the depth of mapping during the run-time unlike with static mapping configuration. 
Is this possible to archieve with current version? And if so how can you accomplish this?
this would help a lot that I would only need one map/configuration for one domain model and decide only per business method how deep should you map?

example:
`mapper.Map<OrderDto>(order).MaxDepth(3);`

**Comment by jbogard** [comment]
Why do you need this to be dynamic? What do your models and DTOs look like?

**Comment by vipasane** [comment]
Both have been generated directly as well as map configuration from domain model. Thinking of a generic solution to reduce the need for several configurations one configuration per WCF or Web Api service should be enough.  

Since I would like my DTOs to be as flat as possible depending on a method that is called not by which return object is defined. Therefore to same a ton of code and time during the implementation phase for certain APIs.

Tried to fork and implement this year ago but was able to make it work only in some cases had issues with collections as I remember correctly.

**Comment by jbogard** [comment]
Can you post your models and DTOs?

**Comment by TylerCarlson1** [comment]
Can't you make 2 profiles?  One for WCF and one for Web Api and set the MaxDepth's for each of them (not sure about this one)?  Or even make 2 IMapper objects and map both seperately?

**Comment by vipasane** [comment]
Sorry since I'm being so unclear.  
Those are irrelevant in my case and couldnt post them since of NDA.

This is just a theory not a related to my current project:
Imagine that I have domain model with 237 classes. Respectively relations and DTOs derived from those objects.

I have several services lets say WCF for soap, Web Api for OData, WCF for some other protocol with multiple methods defined.

Now even with atomic and minimalistic case I would need to have CRUDL operations for each entity.
For soap service in worst case scenario I would need have 237 * 5 = 1185 mapping configuration instead of just one per service. Since I would need to define those mappings by method not by singe generic service specific DTOs.

Maybe another use case would be more easier to understand:
Similar kind of issues you could be facing when used with lazy loading (especially with full navigation and reverse navigation properties) you would not need to worry about recursion since mapping will stop at some level.

To make it short what I'm looking for is:
That would allow so much flexibility to have a static generic service level mapping instructions with full mapping from domain entity to sercice specific DTO that could choose during runtime how far it should map properties case by case. Just handle how deep mapping will reach in each service method instead of maintaining several maps per service. For me that would be more maintainable solution.

**Comment by jbogard** [comment]
I ask for the models because that provides me with some context on what
you're trying to do.

Why are you even using DTOs in the first place? If your persistence models
are the same as your DTOs, back and forth, what value does that mapping
provide?

**Comment by vipasane** [comment]
DTOs are service specific as I would like my mapping configuration to be and they differ from persistence models usually by flattening or removing unneeded properties or combining some values.
Also some DTOs carry IsDirty flags eg. added, changed, removed or unchanged to business layer. So that these values could be rejoined to object graph once they have returned.

**Comment by TylerCarlson1** [comment]
So why can't you make multiple profiles?  Like one for each service and have all the specifics there?  Also if they are mostly automatic, you might look into Conventions, where you can say if type goes to/from Persistance object to specific Service DTO object make mapping for you.  Would cut a lot of the cluttler.  And from there if you have specific rules you could set them up on a per profile base.

**Comment by jbogard** [comment]
So how many models *do* you have?

In general, I try very, very hard not to reuse models across scenarios. Even across a web API and MVC app, it's very difficult to share across those models. I would instead create different profiles and combine with conventions.

Runtime modifications typically mean you've made some mistake modeling somewhere. And not even getting into exposing CRUD entity operations across such a wide variety of protocols. SOAP, OData, WCF on top of TCP or whatever. *That* sounds like the bigger issue here.

**Comment by TylerCarlson1** [comment]
Another thing you can do with [Conventions](https://github.com/AutoMapper/AutoMapper/wiki/Conventions) is now it's completely configurable for both property maps and type maps.  You can clear out all the member configurations like, prefix/postfix, flattening, ect and make your own version to support what you want to do.  So on each Profile/IMapper you can specify your own custom rules to mapping properties that match by name, are/aren't navigation properties, attributes, or some other convention.  It's not exactly the easiest of solutions, but you get to make up your own rules on how things should and shouldn't be mapped.

**Comment by TylerCarlson1** [comment]
Oh and if you have outliers that don't really follow any rules and need to be mapped, you can just call CreateMap and set it up the missing maps, and the rest will follow your own custom rules.  Hopefully you don't have too create too many CreateMaps.
