### ISSUE TITLE
Condition override custom resolver defined in inherited mapping.

### ISSUE THREAD

**Issue by Paul-DS** [AutoMapper/AutoMapper#1197]
Hello,

I think I found an issue on mapping inheritance management.

My issue is the following :
- I have 2 level of inheritance on my object to map (`Base`, `Sub`, and `Specific` for example)
- I define a custom resolver for a property of my `Base` object
- I define a "Condition" mapping for the same property of my `Specific` object

The "Condition" mapping seems to override the custom resolver.
The strange thing is that the custom resolver works if this one is defined on the mapping of the `Sub` object (1 level inheritance).

You can find a fiddle [here](https://dotnetfiddle.net/XDvHMy)
In this fiddle, the test should be OK, but it's not. If you put the line 32 at the end of the line 35 (definition of the custom resolver on the parent class), it's works.

Tell me if the problem is clear enough.

**Comment by lbargaoanu** [comment]
A workaround

                cfg.CreateMap<SpecificEntity, ViewModel>()
                    .IncludeBase<BaseEntity, ViewModel>()
                    .IncludeBase<SubBaseEntity, ViewModel>()
                    .ForMember(vm => vm.Property2, opt => opt.Condition(e => e.Map));

**Comment by Paul-DS** [comment]
Ok, thanks.

There is no fix planned in the future versions ?

**Comment by lbargaoanu** [comment]
It should be fixed eventually.

**Comment by Paul-DS** [comment]
Ok, thanks for your quick answer !

**Comment by lbargaoanu** [comment]
Actually you better leave it open. It's not fixed yet :)
