### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by surifoll** [AutoMapper/AutoMapper#1199]
Pls. HELP. This error is just too frequent when i'm using after map i dont know the main cause.

Some of my Codes:

```
Mapper.CreateMap<SpecialtySubjectModel, SpecialtySubject>();
Mapper.CreateMap<TeacherSubject, TeacherSubjectModel>().AfterMap((src, dest) =>
{
   dest.FirstName = src.Teacher.UserProfile.FirstName;
   dest.LastName = src.Teacher.UserProfile.LastName;
});
Mapper.CreateMap<SpecialtySubject, SpecialtySubjectItem>().AfterMap((src, dest) =>
{
   dest.SubjectTeachers = Mapper.Map<IEnumerable<TeacherSubject>, IEnumerable<TeacherSubjectModel>>(src.Subject.TeacherSubjects.ToList());
});
           
Mapper.CreateMap<SpecialtySubject, SpecialtySubjectModel>().AfterMap((src, dest) =>
{
   dest.SubjectTeachers = Mapper.Map<IEnumerable<TeacherSubject>, IEnumerable<TeacherSubjectModel>>(src.Subject.TeacherSubjects.Where(c => c.SubjectId == src.SubjectId));
});

======================
return Mapper.Map<IEnumerable<SpecialtySubject>, IEnumerable<SpecialtySubjectItem>>(entity.ToList());
```

**Comment by lbargaoanu** [comment]
This usually indicates a threading issue. You must call CreateMap only on initialization, on a single thread. If you already do that, we need a repro.

**Comment by jbogard** [comment]
What collection was modified?

**Comment by surifoll** [comment]
![2016-03-23 2](https://cloud.githubusercontent.com/assets/10003545/13990151/8f2de2ce-f113-11e5-9062-b01feebf5663.png)

**Comment by surifoll** [comment]
That is the screenshot of the inner expression. Thanks in advance

**Comment by jbogard** [comment]
The stack trace is actually the most important part there

**Comment by surifoll** [comment]
ok, Thanks. This is the content of the stack trace::    at SilverEdgeProjects.EdLight.Logic.Implementation.SpecialtySubjectService.<.ctor>b__1(SpecialtySubject src, SpecialtySubjectItem dest) in c:\Projectss\edlight\Trunk\src\SilverEdgeProjects.EdLight.Logic\Implementation\SpecialtySubjectService.cs:line 55
![2016-03-23 1](https://cloud.githubusercontent.com/assets/10003545/13991180/6da6aab0-f117-11e5-9099-3dc604f75bbb.png)

**Comment by jbogard** [comment]
That looks like it's a problem inside your code, not AutoMapper. I don't see AutoMapper in that stack trace.

My guess is that you're missing some ToList calls on iterating collections. Perhaps remove AfterMap and just place the code directly after calling Mapper.Map? The first one I see is the Mapper.Map with a Where but no ToList.

**Comment by surifoll** [comment]
![2016-03-23 4](https://cloud.githubusercontent.com/assets/10003545/13992531/b93a5bb6-f11c-11e5-926c-a2fde323f83a.png)

i've added toList to almost all places. i still get this error can u pls. shed more light

**Comment by TylerCarlson1** [comment]
Can you try
```
Mapper.CreateMap<SpecialtySubject, SpecialtySubjectItem>().ForMember(d => d.SubjectTeachers, opt => opt.MapFrom(s => s.Subject.TeacherSubjects));
```
in place of
```
Mapper.CreateMap<SpecialtySubject, SpecialtySubjectItem>().AfterMap((src, dest) =>
{
   dest.SubjectTeachers = Mapper.Map<IEnumerable<TeacherSubject>, IEnumerable<TeacherSubjectModel>>(src.Subject.TeacherSubjects.ToList());
});
```

And do the same for all the other After Maps.  For member should be sufficient for what you want to accomplish.

**Comment by surifoll** [comment]
Thanks. I'm trying dat now
