### ISSUE TITLE
Conditional mapping MapFrom is executed even when the condition hasn't been met

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#120]
<b>raggamuffin2009[CodePlex]</b><br />Hello,<br /><br />I find it confusing that automapper still executes mapping code for objects that don&#39;t meet the specified condition. Shouldn&#39;t it skip trying to map the value in the first test&#63;<br />This forces me to handle properties that I&#39;m not even trying to map. For instance, null values on reference type properties.<br /><br />E.g&#58; For the mapping below, both tests hit the TestMapping method. <br />          Mapper.Initialize&#40;cfg &#61;&#62; <br />          &#123;<br />                    cfg.CreateMap&#60;Source, Destination&#62;&#40;&#41;.ForMember&#40;dest &#61;&#62; dest.Value, opt &#61;&#62;  &#123;  opt.Condition&#40;src &#61;&#62; src.Value &#62; 0&#41;&#59; &#125;  opt.MapFrom&#40;s &#61;&#62; TestMapping&#40;s.Value&#41;&#41;&#59;  &#125;&#41;&#59;<br />          &#125;&#41;&#59;<br />          <br />            int TestMapping&#40;int value&#41;   &#123;  return value &#43; 1&#59;  &#125;<br /><br />            &#91;Test&#93;<br />            public void Should_skip_the_mapping_when_the_condition_is_true&#40;&#41;<br />            &#123;<br />                var destination &#61; Mapper.Map&#60;Source, Destination&#62;&#40;new Source &#123;Value &#61; -1&#125;&#41;&#59;<br />                destination.Value.ShouldEqual&#40;0&#41;&#59;<br />            &#125;<br /><br />            &#91;Test&#93;<br />            public void Should_execute_the_mapping_when_the_condition_is_false&#40;&#41;<br />            &#123;<br />                var destination &#61; Mapper.Map&#60;Source, Destination&#62;&#40;new Source &#123; Value &#61; 7 &#125;&#41;&#59;<br />                destination.Value.ShouldEqual&#40;7&#41;&#59;<br />            &#125;

**Comment by nukec** [comment]
so this was never resolved?

**Comment by nukec** [comment]
yeah i see, thanks used that
