### ISSUE TITLE
CreateMap.ConstructUsing with profile +  AssertConfigurationIsValid

### ISSUE THREAD

**Issue by laurentKTR** [AutoMapper/AutoMapper#1202]
Hi
i was using the static version of CreateMap with .ConstructUsing(s => Mapper.Map<x>(s.y))
Since my update of the automapper lib i have converted my code to use 
var config = new MapperConfiguration(cfg =>
            
i have some class like this one
internal class DataFullXXX
    {
        public DataXXX DataXXX { get; set; }
        public DataYYY DataYYY { get; set; }
    }

where DataXXX and DataYYY maps to my db tables

cfg.CreateMap DataXXX, XXX();
cfg.CreateMap DataYYY, YYY();

cfg.CreateMap DataFullXXX, XXX()
	.ConstructUsing(s => Mapper.Map<XXX>(s.DataXXX))
	.AfterMap((s, d) => d.YYY = Mapper.Map<YYY>(s.DataYYY));

As i have quite a lot of mappers to do i have split them within profiles
but i have encountered 2 problems

a)
When i set those 3 definitions within a profile 
at runtime, automapper throw an exception within missing mapping between DataXXX and XXX;
and if i'm adding AssertConfigurationIsValid for this profile i have the exception as well
which is a bit strange as the declaration exists in this profile

b) 
when i keep the 2 first declarations within the profile 
and move the 3rd one inside 
var config = new MapperConfiguration(cfg =>
      cfg.AddProfile<XXXProfile>();

	   cfg.CreateMap<DataFullXXX, XXX>()
	   .ConstructUsing(s => Mapper.Map<XXX>(s.DataXXX))
	   .AfterMap((s, d) => d.YYY = Mapper.Map<YYY>(s.DataYYY));
	   
this time the mapper is done at runtime
but if i'm adding AssertConfigurationIsValid  i have the exception as well

What am'I doing wrong ?

regards
Laurent

**Comment by lbargaoanu** [comment]
A repro would be nice :)

**Comment by TylerCarlson1** [comment]
For `cfg.CreateMap<DataFullXXX, XXX>()` you could do `.ForMember(d => d.YYY, opt => opt.MapFrom(s => s.DataYYY))` instead of using AfterMap.

For ConstructUsing I'm not sure how exactly you can eliminate the mapping call.

When you make mapper configuration are you using Mapper.Initialize or generating an IMapper object?

I can see the exception happening if you use IMapper, but not as much with static

**Comment by laurentKTR** [comment]
Ok i will provide a small sln

thanks

**Comment by laurentKTR** [comment]
Yes in fact i have shortened my sample,

The aftermapp is used for an yyy property that belong to an zzz property of xxx object
For zzz property I’m using Formember

Laurent

**Comment by laurentKTR** [comment]
a small sample : you have to uncomment some parts within InitMapper.cs
for problem A or B
[MapSample.zip](https://github.com/AutoMapper/AutoMapper/files/187955/MapSample.zip)

**Comment by lbargaoanu** [comment]
@laurentKTR  Did you close this by accident?

**Comment by laurentKTR** [comment]
Yes sorry

**Comment by lbargaoanu** [comment]
The problem is not where you put the CreateMap-s. All in the profile is just fine. In your sample I see errors for unmapped members. You need to explicitly ignore those and then the errors will go away. But that may be a technicality. Because you're not really AutoMapping much :) The shapes of the objects are too different. This needs more thought.

**Comment by lbargaoanu** [comment]
Ok, I ignored the unmapped properties and what I see is usage of the static Mapper class. That's what causing the missing map errors. Remove the AfterMap (you replaced it with MapFrom) and the ConstructUsing and everything should map ok.

**Comment by laurentKTR** [comment]
not sure to understand your solution
even if i remove the aftermap i have the same problem

As i have called the IMapper property Mapper i didn't notice that within the profile i was using the static mapper class

**Comment by lbargaoanu** [comment]
CreateMap<DataXXX, XXX>().ForMember(d => d.YYY, o => o.Ignore());
            CreateMap<DataYYY, YYY>().ForMember(d=>d.ZZZ, o => o.Ignore());
            CreateMap<DataZZZ, ZZZ>();
            CreateMap<DataZZZ, YYY>().ForMember(d => d.ZZZ, o => o.Ignore());
            CreateMap<DataFullXXX, XXX>()
               .ForMember(d => d.Id, o => o.Ignore())
               .ForMember(d => d.Name, o => o.Ignore())
               .ForMember(dest => dest.YYY, opt => opt.MapFrom(s => s.DataZZZ));

**Comment by laurentKTR** [comment]
ok there are  no more errors but the result of InitMapper.Mapper.Map<XXX>(dataFull); 
is an empty object, all properties are unfilled !

**Comment by lbargaoanu** [comment]
Yes, because I ignored the values :) As I said, that last map is not useful, the objects are too different. Maybe it's better to map it by hand. You can use MapFrom for Id and Name, but AutoMapper cannot help you more in this case.

**Comment by laurentKTR** [comment]
ah ok :-)

In fact actually when i'm declaring the constructusing + aftermap within MapperConfiguration
automapper behave as i was expecting, all propeties are set and the 3 levels objects is correctly set

it's only the config.AssertConfigurationIsValid() which is failing

**Comment by lbargaoanu** [comment]
Well, _the right_ ConstructUsing is below (doesn't use the static Mapper class). But please don't write that :) Mapping by hand is best and MapFrom second.

     ConstructUsing((ResolutionContext c) => c.Engine.Mapper.Map<XXX>(((DataFullXXX)c.SourceValue).DataXXX))

**Comment by lbargaoanu** [comment]
@laurentKTR If everything is clear, you can close the issue.

**Comment by laurentKTR** [comment]
Thanks
