### ISSUE TITLE
Dynamic mapping in 4.2.1 not behaving as expected

### ISSUE THREAD

**Issue by barriestewart** [AutoMapper/AutoMapper#1203]
I'm not sure if I'm doing this wrong but here is a contrived example of a mapping from an ExpandoObject to an Author type (requires JSON.NET library to run):

```C#
    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true);
            var mapper = config.CreateMapper();

            Author a = new Author()
            {
                Name = "Charles Dickens",
                Books = new[]
                {
                    new Book()
                    {
                        Name = "Great Expectations",
                    },
                    new Book()
                    {
                        Name = "Oliver Twist"
                    }
                }
            };

            var jsonString = JsonConvert.SerializeObject(a);
            dynamic authorDynamic = JsonConvert.DeserializeObject<ExpandoObject>(jsonString, new ExpandoObjectConverter());
            Author mappedAuthor = mapper.Map<Author>(authorDynamic);
        }
    }

    public class Author
    {
        public string Name { get; set; }
        public Book[] Books { get; set; }
    }

    public class Book
    {
        public string Name { get; set; }
    }
```

The result of this is that `mappedAuthor` has the `Name` property set correctly. The `Books` array has 2 elements but for each book in there, the `Name` property is null. The mapping will work if I change my config to this:

```C#
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;
                cfg.CreateMap<ExpandoObject, Book>()
                    .ForMember(
                        dest => dest.Name,
                        opts => opts.MapFrom(src => ((IDictionary<string, object>) src)["Name"])
                    );
            });
```

This feature is new so I'm not sure if this is a bug or if my configuration is wrong.

**Comment by TylerCarlson1** [comment]
@jbogard Does this have something to do with moving out Automapper.Data?

There was another issue with name mappings not working for dynamic map and I couldn't figure out why.  Seeing as it uses `["Name"]` I'm inclined to think it's Automapper.Data that had the ability to map dynamic objects.

**Comment by lbargaoanu** [comment]
CreateMissingTypeMaps doesn't help. The problem is that authorDynamic.Books is IEnumerable<Object> and then it tries to map object to Book, not dynamic to Book. I don't have a quick fix :(

**Comment by lbargaoanu** [comment]
The only workaround I found is

            var config = new MapperConfiguration(cfg => cfg.CreateMap<List<object>, Book[]>().ConvertUsing((s, c)=>c.Mapper.Map<Book[]>(s.Cast<IDictionary<string, object>>())));

**Comment by lbargaoanu** [comment]
I'm not sure AutoMapper can do better in this case. It cannot know that List< object > is actually List< ExpandoObject > or something.

**Comment by lbargaoanu** [comment]
Unless we map each item according to its runtime type :)

**Comment by barriestewart** [comment]
@lbargaoanu Ah - you are completely correct. For some reason I thought Books in the expando was a `List<ExpandoObject>`. It makes sense that it doesn't know how to map from Object.

Anyway, I tried creating the expando object manually with Books being a `List<ExpandoObject>` and that mapped as I expected it to. Thanks very much for the feedback.

**Comment by lbargaoanu** [comment]
@barriestewart I think it can work by default the way you expected.
