### ISSUE TITLE
Nested Explicit Expand with Strings Not Producing Expected Results

### ISSUE THREAD

**Issue by bradosmond** [AutoMapper/AutoMapper#1205]
On the same or similar topic of #980, which that fix might have addressed; given the following pseudo-code scenario, where Level0, Level1, Level2, and Level3 are arranged into a hierarchy, mapping configurations are in order with ExplicitExpansion set for each of the nested classes, and using a dataStore which returns an IQueryable&lt;Level0&gt; from an EF DbSet, I've discovered that QueryableExtensions fail to hydrate the DTO with any navigation properties that are not direct decendants of the aggregate root 'Level0'; In short, nothing with a '.' seems to be traversed or materialized.

```
var includes = new string [] { "Level1", "Level1.Level2", "Level1.Level2.Level3" };

var queryable = dataStore<Level0>.GetAll().Include(includes);

var projected = queryable.ProjectTo<Level0Dto>(mapperConfig, null, includes);

var entity = projected.ToList().FirstOrDefault();

// shape of resulting entity //

Level0 {
  Name = "Level0",
  Level1 = {
      Name = "Level1",
      Level2 = null
  }
}

```
In reviewing this unit test, (which targets Net4), I expected that each level would be expanded. Am I misunderstanding the behavior?

https://github.com/AutoMapper/AutoMapper/blob/49e81dff7801259be2779f3054161c3a8b6cedaf/src/IntegrationTests.Net4/NestedExplicitExpandWithFields.cs#L61 

 Reference #980

**Comment by lbargaoanu** [comment]
You just need "Level1.Level2.Level3". Does that test work for you?

**Comment by bradosmond** [comment]
Thanks much for your quick response. 

Nested children still seem to turn up null;

```
// Include using EF Include Syntax

IQueryable<Level0> query = Repository
   .GetAll().Include("Level1", "Level1.Level2") 
   .Where(x => x.Id == id);

// After enumeration, Level0, Level1, and Level2 (TEntity) are populated
var entity0test1 = query.ToList();

// Include using AutoMapper Aggregated Syntax
var projected1 = query.ProjectTo<Level0Dto>(
MapperConfig, 
null, 
"Level1.Level2");

var projected2 = query.ProjectTo<Level0Dto>(
MapperConfig, 
null, 
""Level0.Level1", "Level1.Level2");

// After enumeration, Level0 and Level1 (TDto) are populated, Level2 (TDto) is NOT.
var entity0test2a = projected1.ToList();
var entity0test2b = projected2.ToList();
```

**Comment by lbargaoanu** [comment]
What I meant is that you should try the test you linked to :) That test works. You can also try your test with the MyGet build. If you still don't find anything, you'll have to write a similar test that fails.

**Comment by bradosmond** [comment]
Very good, thank you for your feedback. I'll give that over the whirl in the next 24hrs and close/comment.

**Comment by bradosmond** [comment]
It turns out that my MapperConfig wasn't arranged correctly. After running the integration tests you prescribed, I was able to duplicate the correct behavior in my application. Thanks again for your quick response and guidance. My app expected to depend quite heavily on this explicit string expansion and your pull was the ticket.
