### ISSUE TITLE
Leverage c# dynamic binding to dynamically infer destination type for mapping

### ISSUE THREAD

**Issue by rsheptolut** [AutoMapper/AutoMapper#1206]
I guess this is a feature request. This functionality may well be in Automapper and I've just missed it.

First of all, I'm new to Automapper, but I've instantly loved it! Although I felt that I would've wanted it to be **even simpler**. I want to perform a mapping **without actually specifying destination type**. I want it to be automatically inferred from the context of current statement. And I'm talking about regular, concrete to concrete mappings, not about mapping an object of a concrete type to dynamic object or vice versa.

Simple example: we want to map ORM object to a DTO object for whatever reason.

It would be great if the following would be possible:
```c#
public MyEntityDto ShowWhatIMean(MyEntity entity, IMapper mapper)
{
    // Here I don't specify explicitly what type I want it to be converted to
    return mapper.Map(entity); 
}
```

This **is possible to do** via the dynamic binding feature, the destination type could be inferred automatically. Not only from local variable type, but return type, property type, field type. Not parameter type, sadly, because dynamic overloading resolution just doesn't take into account the possibility that our dynamic could be converted to arbitrary type.

It may not seem like a huge improvement in this example, but it saves a lot of typing and repetition (specifying the destination type in multiple places violates DRY just a tiny amount).

To clarify, I already got that working in my project with a little bit of code. So, if someone's interested, for that code to work you need something like what I've quickly put together:
```c#
public static class AutoMapperIMapperExtensions
{
    internal static dynamic Map(this IMapper mapper, object source)
    {
        return source != null ? new DynamicMapper(mapper, source) : null;
    }
}

/*  Note: I could've just inherited from DynamicObject, but it has a feature in that it throws
    and swallows a RuntimeBinderException every time the binding is performed.
    It's normal and cannot be prevented without implementing IDynamicMetaObjectProvider 
    yourself, so I did just that */
public class DynamicMapper : IDynamicMetaObjectProvider
{
    private readonly IMapper mapper;
    private readonly object source;

    public DynamicMapper(IMapper mapper, object source)
    {
        this.mapper = mapper;
        this.source = source;
    }

    public DynamicMetaObject GetMetaObject(Expression parameter)
    {
        return new DynamicMapperMetaObject(parameter, this);
    }

    public virtual object Convert(ConvertBinder binder)
    {
        return mapper.Map(source, source.GetType(), binder.Type);
    }
}

public class DynamicMapperMetaObject : DynamicMetaObject
{
    internal DynamicMapperMetaObject(Expression expression, DynamicMapper value)
            : base(expression, BindingRestrictions.Empty, value)
    { }

    public override DynamicMetaObject BindConvert(ConvertBinder binder)
    {
        return new DynamicMetaObject(
            Expression.Convert(
                Expression.Call(
                    Expression.Convert(Expression, typeof(DynamicMapper)),
                    typeof(DynamicMapper).GetMethod("Convert"),
                    new Expression[] { Expression.Constant(binder) }
                ), binder.ReturnType),
            BindingRestrictions.GetTypeRestriction(Expression, LimitType)
        );
    }
}
```

At first, the `Map` method only gives off a dynamic object, which in turn has the capability to be cast to any type, leveraging AutoMapper. When CLR requests the conversion it specifies what type it would like to convert to, and that's what I carry over to Automapper.

That improvement is just a little thing that can help to simplify Automapper's "getting started" guide, maybe save some keystrokes for Automapper users and stop enraging the DRY gods.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Dynamic-and-ExpandoObject-Mapping

**Comment by rsheptolut** [comment]
@lbargaoanu: Thanks for the tip. The thing is, I'm not talking about mapping **to** dynamic or expando objects. I'm talking about the **regular, concrete to concrete** mapping (entity to dto, or dto to viewmodel). It could be simplified by a feature of C# and CLR: dynamic binding.

**Comment by lbargaoanu** [comment]
You should compare your thing with the regular case using the MyGet build, in terms of CPU and GC. I take it the benefit is omitting the destination type, but what does it cost?

**Comment by rsheptolut** [comment]
@lbargaoanu: Most of the instances of using Automapper are about code simplification and these places are not so critical in terms of performance. But you're right, it absolutely has a cost. I think it's rather small in most scenarios, but it definitely should be tested.
Omitting the destination type may be a silly little thing, but I experience pain when I need to spell things out and repeat myself (I would've killed myself if `var` wasn't available). @lbargaoanu: Most of the instances of using Automapper are about code simplification and these places are not so critical in terms of performance. But you're right, it absolutely has a cost. I think it is rather small in most scenarios, but it should be tested.
Omitting the destination type may be a silly little thing, but I experience pain when I need to spell things out and repeat myself in code (I would've killed myself if `var` wasn't available).

**Comment by lbargaoanu** [comment]
Anyway, interesting stuff :)

**Comment by jbogard** [comment]
I think this is a Roslyn feature request, to infer generic parameters better-er too.

I wouldn't replace the existing Map call, and an overload that returns a dynamic would confuse people (since people have long asked for actual ExpandoObject mapping).

Do you have any thoughts about how this would fold in to the existing API without confusing anyone?

**Comment by lbargaoanu** [comment]
And also the word "dynamic" should be off limits :)

**Comment by rsheptolut** [comment]
@jbogard: yes, it would be better if Roslyn team would implement this. There's an issue in Roslyn repository about it: https://github.com/dotnet/roslyn/issues/5429 , though I wait for this feature since generics were introduced, and have lost all hope :)
About the API: I actually thought about (and implemented it as) an overload (via an extension). But maybe you're right about it getting people confused. I can't think of any better alternative, though.
But wouldn't this dynamic also be converted to ExpandoObject when it is requested to? Itself it is not an ExpandoObject for sure, but though the magic of Automapper plus that dynamic binding trick there, it could become one. If that fails, the Map that only takes an object could return a dynamic, but this time it will actually also behave in all ways like an ExpandoObject. And also convert automatically to any type, including the actual ExpandoObject.
I know, not a one liner.

**Comment by rsheptolut** [comment]
Found out a caveat: this doesn't work with method parameters. Dynamic overload resolution just doesn't take into account that our dynamic object can be transformed to anything it needs.
