### ISSUE TITLE
Collection type can not mapping

### ISSUE THREAD

**Issue by gaojianzhuang** [AutoMapper/AutoMapper#1213]
I have this scenario:
`public class A { }`
`public class AS : List<A> { }`

`public class B { }`
`public class BS : List<A> { }`

`Mapper.CreateMap<A, B>();`
`Mapper.CreateMap<AS, BS>();`

` var a = new A() { id = "1" };`
` var aList = new AS();`
` aList.Add(a);`

`var s = Mapper.Map<AS, BS>(asList); -- failed`
`var b = Mapper.Map<A, B>(a); -- success`
`var bs = Mapper.Map<List<A>, List<B>>(aList); -- success`

Please help me, thx.
_PS: Autpmapper version:4.2.1_

**Comment by lbargaoanu** [comment]
Similar to #1083? If that's the case, you're in a bind :) You can try my last answer there.
