### ISSUE TITLE
Anyway to disable MethodGetters

### ISSUE THREAD

**Issue by Squirrel84** [AutoMapper/AutoMapper#1214]
I am finding that when mapping one of my objects, Automapper is calling a method to try to resolve the property to map to.

Example : -
Source = Object A { 
int question_id
Question Question() { return _question; }
 }

Destination = Object B {
int QuestionId
}

I do have a map declared to map from question_id to QuestionId
.ForMember(d => d.QuestionId, opt => opt.MapFrom(src => src.question_id))

I assumed because I have explicitly declared the mapping that there would be no reason to have multiple resolvers, however it appears automapper still tries to "guess" where to retrieve the data from to map to.
![automapper_multipleresolvers](https://cloud.githubusercontent.com/assets/4228072/14178468/b66b7d52-f752-11e5-8b94-20732b4b9450.png)

I didnt know if there was another configuration to set, so that automapper only uses the properties that have been explicitly declared rather than still trying to guess its way to resolve the mapping.

**Comment by jbogard** [comment]
I *believe* this will be fixed in 5.0. I only evaluate the destination
member if you add a condition around it.
