### ISSUE TITLE
Flatten nested children using ProjectTo

### ISSUE THREAD

**Issue by matt6502git** [AutoMapper/AutoMapper#1216]
Have been using AutoMapper for a couple of years but starting to dive deeper into the more advanced features of it and I'm having issues that I cannot resolve.

Simple example for demo purposes:  5 tables....grandparent, parent, child, and 2 relation tables, grandparentParent and parentChild.   What I want is a list of grandparentviewmodels that have only the grandparent name, but also has a list of grandchild objects....not a list of parent objects....ie...."give me the grandparent and all their grandchildren regardless of which parent they are a child of".

In order to try to get this working, I have used the ConvertUsing method and have created a class that implements the ITypeConverter interface.   Everything builds, but I can't get the mapping to work....the breakpoints I am setting in the TypeConverter class do not get hit and I can't figure out what I am doing wrong.

I created a stackoverflow question for this, but it isn't getting any action so hoping this forum helps.  [Here is the SO question] (http://stackoverflow.com/questions/36344338/flatten-linq-automapper-projectto-nested-children).  And below are snippets of the code I have:

```
public class GrandparentConverter : ITypeConverter<Grandparent, GrandparentViewModel>
{
    public GrandparentViewModel Convert(ResolutionContext context)
    {
        var entities = context.SourceValue as Grandparent;

        return entities
            .Select(x => new GrandparentViewModel
            {
                GrandparentId = x.GrandparentId,
                Name = x.Name,
                Grandchildren = AutoMapper.Mapper.Map<IEnumerable<Parent>, List<ChildViewModel>>(x.Parents)
            }).ToList();

        //return new GrandparentViewModel
        //{
        //    GrandparentId = entities.GrandparentId,
        //    Name = entities.Name,
        //    Grandchildren = entities.Parents.SelectMany(x => x.Children.Select(y => new ChildViewModel
        //    {
        //        ChildId = y.ChildId,
        //        Name = y.Name
        //    }).ToList()).ToList()
        //};
    }
}


public class ChildConverter : ITypeConverter<IEnumerable<Parent>, List<ChildViewModel>>
{
    public List<ChildViewModel> Convert(ResolutionContext context)
    {
        var entities = context.SourceValue as IEnumerable<Parent>;

        return entities
            .SelectMany(x => x.Children)
            .Select(x => new ChildViewModel
            {
                ChildId = x.ChildId,
                Name = x.Name
            }).ToList();
    }
} 

....surrounding code removed as it isn't relevant....
MapperConfiguration mapper = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Child, ChildViewModel>();
            cfg.CreateMap<IEnumerable<Parent>, List<ChildViewModel>>().ConvertUsing<ChildConverter>();

            cfg.CreateMap<Grandparent, GrandparentViewModel>();
            cfg.CreateMap<IEnumerable<Grandparent>, List<GrandparentViewModel>>().ConvertUsing<GrandparentConverter>();
        });

        FamilyEntities db = new FamilyEntities();
        List<GrandparentViewModel> entities = db.Set<Grandparent>()
            .Where(x => x.GrandparentId == 1)
            .ProjectTo<GrandparentViewModel>(mapper)
            .ToList();
```

**Comment by TylerCarlson1** [comment]
From my understanding ProjectTo doesn't use type converters because of the limitations of the Linq providers.

What you could try is ProjectUsing and that should be called when you run a projection.

**Comment by matt6502git** [comment]
Thanks Tyler....

I changed the code on CreateMap to call ProjectUsing so that it is like this:

```
cfg.CreateMap<Grandparent, GrandparentViewModel>().ProjectUsing(x => new
GrandparentViewModel
                {
                    GrandparentId = x.GrandparentId,
                    Name = x.Name,
                    Grandchildren = x.Parents.SelectMany(y => y.Children.Select(z => new ChildViewModel
                    {
                        ChildId = z.ChildId,
                        Name = z.Name
                    })).ToList()
                });
```

When do this thought the ProjectTo method call throws an exception stating that Grandparent (not the viewmodel) doesn't have a property named "Children".   I'm not sure if ForMember now needs to be in play to help AutoMapper with the linkage or if I am missing something on ProjectUsing.

**Comment by TylerCarlson1** [comment]
Not sure myself that might be a bug with the ProjectTo.  If you can try using the Select statement against the DB query directly like so.
```
List<GrandparentViewModel> entities = db.Set<Grandparent>()
            .Where(x => x.GrandparentId == 1)
            .Select(new
GrandparentViewModel
                {
                    GrandparentId = x.GrandparentId,
                    Name = x.Name,
                    Grandchildren = x.Parents.SelectMany(y => y.Children.Select(z => new ChildViewModel
                    {
                        ChildId = z.ChildId,
                        Name = z.Name
                    })).ToList()
                })
            .ToList();
```

If that gives the same exception then EntityFramework can't translate the query as is.  If passes then there's a bug in ProjectTo.  Either way I suspect the probably has to do with the y lambda

**Comment by matt6502git** [comment]
Yes, it works if I do not use AutoMapper's ProjectTo.  

This is how I have always used AutoMapper in the past, but the problem with this approach is that I have tried to abstract away the select logic so I can have multiple and different view model classes returned based on business function.   I was really hoping that this was going to be the savior to keep my away from the traditional method bloat that happens with returning nearly identical business objects.

**Comment by TylerCarlson1** [comment]
Ok this is definitely a bug with ProjectTo.  I know this can be solved cause UseAsDataSource doesn't have this problem (different code).

Issue is it's treating x and y the same way.  It's probably replacing x with like dto, and it's trying to replace y as well.  It's more than likely would try to replace z as well, but errors out before it gets there.
That's why Children doesn't exist for GrandParent, because y is now replaced with a dto pointing to GrandParent

**Comment by matt6502git** [comment]
That theory makes sense....any idea what turnaround time is like for the AutoMapper project if it is effectively marked as a defect?   I'm so close to having a very robust and powerful data access framework that I don't want to give up on this, but it isn't something I can hold long on without having to find an alternative.

**Comment by TylerCarlson1** [comment]
Think I found it, but as an alternative can you do something like
```
MapperConfiguration mapper = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Child, ChildViewModel>();
            cfg.CreateMap<Grandparent, GrandparentViewModel>().ForMember(d => d.Grandchildren, opt.MapFrom(s => s.Parents.SelectMany(x => x.Children));
         };
```
This should get the same effect.  As well as easier to read.

As for the fix I think I got it but I need to write a test and prove and submit a PR.  If accepted and merged it would be available on the pre-release of Automapper 5.0 on MyGet.

**Comment by matt6502git** [comment]
Thanks so much for your help....I've beat my head against the wall for 3 days trying to get this to work.   It looks like the workaround is working in my simplified example....I am going to translate over to my actual solution and make sure the projection/selection/mapping is all working there.

**Comment by TylerCarlson1** [comment]
No Problem.  Also just remember.  There's no reason for enumerables to be mapped explicitly, AutoMapper handles figuring out the types of the list and doing the proper sub mappings, and projection translations itself.  Also it gets rid of a lot of ugly boiler plate code :)

I'm still submiting a PR #1217 for this, cause it's still technically a bug, and should work.
