### ISSUE TITLE
LowerUnderscore/PascalCase naming convention not working

### ISSUE THREAD

**Issue by PJLTN** [AutoMapper/AutoMapper#1220]
I have 2 classes I want to map with Automapper:

    namespace AutoMapperApp
    {
        public class Class1
        {
            public string Test { get; set; }
            public string property_name { get; set; }
        }
    }

    namespace AutoMapperApp
    {
        public class Class2
        {
            public string Test { get; set; }
            public string PropertyName { get; set; }
        }
    }

This is my Automapper config:

    using AutoMapper;
    
    namespace AutoMapperApp
    {
        public static class AutoMapperConfig
        {
            public static MapperConfiguration MapperConfiguration;
    
            public static void RegisterMappings()
            {
                MapperConfiguration = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<Class1, Class2>();
                    cfg.SourceMemberNamingConvention = new LowerUnderscoreNamingConvention();
                    cfg.DestinationMemberNamingConvention = new PascalCaseNamingConvention();
                });
            }
        }
    }

According the Wiki of Automapper this should work:
https://github.com/AutoMapper/AutoMapper/wiki/Configuration

But my unittest fails:

    using Xunit;
    using AutoMapperApp;
    
    namespace AutoMapperTest
    {
        public class Test
        {
            [Fact]
            public void AssertConfigurationIsValid()
            {
                AutoMapperConfig.RegisterMappings();
                AutoMapperConfig.MapperConfiguration.AssertConfigurationIsValid();
            }
        }
    }

Exception:

    AutoMapper.AutoMapperConfigurationException: 
    Unmapped members were found. Review the types and members below.
    Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
    =============================================
    Class1 -> Class2 (Destination member list)
    AutoMapperApp.Class1 -> AutoMapperApp.Class2 (Destination member list)
    
    Unmapped properties:
    PropertyName

Why?

**Comment by lbargaoanu** [comment]
Try the CreateMap after you set the convention.

**Comment by PJLTN** [comment]
Now it's working, thnx.
I followed the [wiki](https://github.com/AutoMapper/AutoMapper/wiki/Configuration#naming-conventions), maybe change the order there?

**Comment by lbargaoanu** [comment]
Feel free to do that yourself :) I think this would work either way with the MyGet build.
