### ISSUE TITLE
RecognizeDestinationPrefixes for PascalCaseNamingConvention to LowerUnderscoreNamingConvention

### ISSUE THREAD

**Issue by alexander-ivanov** [AutoMapper/AutoMapper#1221]
AutoMapper has a feature to omit prefixes for destination names. I've done some test to convert PascalCase names to LowerUnderscore with RecognizeDestinationPrefixes set in LowerUnderscore format.

```
public class When_destination_members_contain_prefixes2 : AutoMapperSpecBase
{
    private Destination _destination;

    public class Source
    {
        public int Value { get; set; }
        public int FailValue { get; set; }
        public int PassValue { get; set; }
    }

    public class Destination
    {
        public int x_value { get; set; }
        public int x_fail_value { get; set; }
        public int pass_value { get; set; }
    }

    protected override MapperConfiguration Configuration { get; } = new MapperConfiguration(cfg =>
    {
        cfg.SourceMemberNamingConvention = new PascalCaseNamingConvention();
        cfg.DestinationMemberNamingConvention = new LowerUnderscoreNamingConvention();
        cfg.ClearPrefixes();
        cfg.RecognizeDestinationPrefixes("x_");
        cfg.CreateMap<Source, Destination>();
    });

    protected override void Because_of()
    {
        _destination = Mapper.Map<Source, Destination>(new Source { Value = 5, FailValue = 10, PassValue = 15});
    }

    [Fact]
    public void Registered_prefixes_ignored()
    {
        _destination.x_value.ShouldEqual(5); //PASS
        _destination.pass_value.ShouldEqual(15); //PASS
        _destination.x_fail_value.ShouldEqual(10); //FAIL
    }
}
```

It works for `x_value` and `pass_value` but fails for `x_fail_value`. It passes the test if I change `cfg.RecognizeDestinationPrefixes("x_");` to `cfg.RecognizeDestinationPrefixes("X");`. So the question is what naming convention should be used for `RecognizeDestinationPrefixes`?

**Comment by TylerCarlson1** [comment]
RecognizeDestinationPrefixes should be the SourceMemberNamingConvention `cfg.RecognizeDestinationPrefixes("X");`, because that's what is going to be converted to, to do the name split comparisons.  The reason the other x_value passed is because there is also a comparison between names without naming conventions applied that that one will pass in this case.
