### ISSUE TITLE
Need help getting this working

### ISSUE THREAD

**Issue by kdesai000** [AutoMapper/AutoMapper#1223]
I have the following code... and it throws and exception 👍 Method 'Map' in type 'AutoMapper.Data.DataReaderMapper' from assembly 'AutoMapper.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
this exception is thrown when I try to add the mapper....any idea how to solve this?

when I am trying to create a configuration like such.
` Mapper.Initialize(cfg => 
             { 
                 MapperRegistry.Mappers.Add(new DataReaderMapper(){ YieldReturnEnabled = true });
                 cfg.CreateMap<IDataReader, FileData>()
                     .ForMember(dest => dest.HourlyJobStartDateTime, opt => opt.MapFrom(src => !String.IsNullOrWhiteSpace(Convert.ToString(src["HourlyJobStartDateTime"])) ? (DateTime?)null : DateTime.Parse(Convert.ToString(src["HourlyJobStartDateTime"]))))
                    .ForMember(dest => dest.HourlyJobEndDateTime, opt => opt.MapFrom(src => !String.IsNullOrWhiteSpace(Convert.ToString(src["HourlyJobEndDateTime"])) ? (DateTime?)null : DateTime.Parse(Convert.ToString(src["HourlyJobEndDateTime"]))))
                    .ForMember(dest => dest.DOFlightTime, opt => opt.MapFrom(src => !String.IsNullOrWhiteSpace(Convert.ToString(src["DOFlightTime"])) ? (DateTime?)null : DateTime.Parse(Convert.ToString(src["DOFlightTime"]))))
                    .ForMember(dest => dest.PUFlightTime, opt => opt.MapFrom(src => !String.IsNullOrWhiteSpace(Convert.ToString(src["PUFlightTime"])) ? (DateTime?)null : DateTime.Parse(Convert.ToString(src["PUFlightTime"]))));
             });
             data = Mapper.Map<IDataReader, List<FileData>>(table.CreateDataReader()); `

**Comment by TylerCarlson1** [comment]
Might be [this](https://github.com/AutoMapper/AutoMapper.Data/issues/19) if you are using the latest version of AutoMapper.

**Comment by kdesai000** [comment]
let me try using that version.  Thanks
