### ISSUE TITLE
Support async operation in ValueResolver natively

### ISSUE THREAD

**Issue by abatishchev** [AutoMapper/AutoMapper#1226]
Currently I have the following code:

```csharp
public class OrderNumberResolver : ValueResolver<Order, int>
{
	private readonly IOrderService _service;

	public OrderNumberResolver(IOrderService service)
	{
		_service = service;
	}

	protected override int ResolveCore(Order order)
	{
		return Task.Run(async () => await _service.GetOrder(order.OrderId))
					.Result
					.OrderNumber;
	}
}
```

But it would be nice to have something like that:

```csharp
public class OrderNumberResolver : ValueResolver<Order, int>
{
	private readonly IOrderService _service;

	public OrderNumberResolver(IOrderService service)
	{
		_service = service;
	}

	protected override async Task<int> ResolveCoreAsync(Order order)
	{
		var order = await _service.GetOrder(order.OrderId);
		return order.OrderNumber;
	}
}
```

**Comment by jbogard** [comment]
This will likely never happen. It would require the entire API be async,
just for a value resolver.

**Comment by abatishchev** [comment]
Bummer.

**Comment by jbogard** [comment]
Yeah I know. Plus I'd have to mix async and sync because there's no
guarantee I have just one or the other. It would just get ugly.

**Comment by abatishchev** [comment]
Can you please evaluate this snippet? https://gist.github.com/JakeGinnivan/f345d34b7b8e9f04dc6d

**Comment by abatishchev** [comment]
Bump.

**Comment by jbogard** [comment]
Can you use that?

**Comment by abatishchev** [comment]
I'm not really familiar with the internal (context, etc.) so wondering is the right way to do async.

**Comment by jbogard** [comment]
Well that makes two of us!

**Comment by djl394922860** [comment]
Can give a specific example ！

**Comment by jbogard** [comment]
Of async? I can't help you there.

**Comment by adamhathcock** [comment]
That snippet won't work as it's based off of an older version.  I don't know enough about the AutoMapper context  I think but I can't get it to work.

I also need to get async values from other sources to map to my destination.  Using Value or Type converters results in the same problem.  Doing `.Result` seems to cause deadlocks.  Ugh.

**Comment by jbogard** [comment]
The only way I could support this is to have the entire Map call be async.
I can't see that happening.

**Comment by abatishchev** [comment]
The new version has a slight difference, you need to implement `IValueResolver<in TSource, in TDestination, TDestMember>` now, see https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers.

**Comment by adamhathcock** [comment]
It's not that simple.  

The async resolver used stuff that isn't there anymore in the resolution context.

I think I've decided to wrap automapper and use it as a fallback outside of my async mapping.  I'll post something when I have it.

**Comment by adamhathcock** [comment]
This is what I came up with: https://github.com/Narochno/Narochno.AsyncMapper

People seem to disagree that I should need to do this at all.  Composing a domain object from multiple sources feels like a valid use case and some of those sources would need to be async.

**Comment by j0nimost** [comment]
I am using ASP.NET Core where i would like to resolve for User GUID but since it's now async i cant resolve 

        var user = await this.userManager.FindById(ClaimTypes.NameIdentifier);
I can't resolve for the user

**Comment by mladenb** [comment]
I ended up using an await in the controller after calling _mapper.Map(), like this:
```
public async Task<IActionResult> Get(string id)
{
	var item = await _itemService.GetAsync(id);
	var model = _mapper.Map(item);
	model.UserName = (await _userService.GetAsync(item.UserId)).Name;
	...
}
```
