### ISSUE TITLE
4.2.1 ProjectTo - not mapping DateTime.Kind property?

### ISSUE THREAD

**Issue by lisamariet** [AutoMapper/AutoMapper#1233]
I have a case where I have a collection with DateTime properties that has DateTime.Kind = UTC.

When I do ProjectTo<myModelType>(myEntityCollection) the new returned IQueriable<myModelType> has DateTime properties with DateTime.Kind = Unspecified. And this is causing headaches.

**Comment by lbargaoanu** [comment]
I don't see it with the MyGet build. A repro would help. Make a gist that we can execute and see fail.

**Comment by lbargaoanu** [comment]
I see it now. It works in memory, it doesn't with a database.

**Comment by lbargaoanu** [comment]
If I make a query without involving AutoMapper, I get the same behavior.

**Comment by lisamariet** [comment]
Our issue is that in the SQL database we have columns => Datetime. Where we save UTC time value in that field. To make EntityFramework return this as DateTime with Kind = UTC. We use an Attribute on the property of the Entity class. And this attribute is applied in the context. See SO: http://stackoverflow.com/questions/4648540/entity-framework-datetime-and-utc

This works with normal Mapper.Map<MyModel>(MyEntity) but it does not work when we use ProjectTo<>

**Comment by jbogard** [comment]
Mapper.Map goes from EF -> Entity -> DTO. ProjectTo goes from EF -> LINQ Select -> DTO. Have you tried taking AutoMapper out of the equation and writing a Select LINQ projection yourself, in place of ProjectTo? This is what @lbargaoanu was saying. EF might not support what you're trying to do, so to troubleshoot I take AutoMapper out and do a hand-mapping in LINQ:

```
dbContext.Products.Select(p => new ProductDto { Name = p.Name, /* etc */ }
```

Try doing that, using LINQ.

**Comment by lisamariet** [comment]
Yes... I tried that.. and it workes :-) It is what brought me into thinking something was off with Automapper. It is a oData query with a complex objectstructure... so definetly not preferred to write it manually. It is really here we could benefit from Automapper :-) But I guess... you are saying it is impossible.

**Comment by lbargaoanu** [comment]
It works because _you_ made it work with that attribute :)

**Comment by jbogard** [comment]
No, not saying it's impossible. Just walking you through my troubleshooting process for ProjectTo.

If it works with a manual Select projection, then there's something different between the expression AutoMapper creates and the manual one. From there I compare the DebugView of the Select projection (you can see this if you debug and look at the expression itself) and the one from AutoMapper.

**Comment by jbogard** [comment]
@lbargaoanu if the manual Select projection works, shouldn't it work with AutoMapper? I'm not seeing types or the Select code so I'm guessing here

**Comment by lbargaoanu** [comment]
@jbogard It doesn't work with a manual projection. It's just that they fixed it somehow :) But their fix doesn't apply to ProjectTo.

**Comment by lisamariet** [comment]
I also tried using custom Typeconverter and add the DateTimeKind there.. but that did not work either.

**Comment by jbogard** [comment]
@lisamariet can you post the manual Select projection that you got to work?

And TypeConverters aren't used in ProjectTo, EF LINQ doesn't understand them. You can do ProjectUsing though.

**Comment by lisamariet** [comment]
UTC is only specified as that attribute on the Entity Class. No where in the database does it say UTC kind for DateTime. So the SQL select statement is Identical. The reason the reason it works doing it manually is because of the attribute that is described in the SO-article I linked earlier. 

SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Tittel] AS [Tittel], 
    [Extent1].[OpprettetUtc] AS [OpprettetUtc], 
    [Extent1].[OpprettetAv] AS [OpprettetAv], 
    [Extent1].[EndretUtc] AS [EndretUtc], 
    [Extent1].[EndretAv] AS [EndretAv], 
    [Extent1].[SlettetUtc] AS [SlettetUtc], 
    [Extent1].[SlettetAv] AS [SlettetAv]
    FROM [eArkiv].[Dokumentsett_View] AS [Extent1]
    WHERE [Extent1].[SlettetUtc] IS NULL

**Comment by jbogard** [comment]
That looks like Select as SQL, do you have the Select as LINQ you said you tried and it worked?

`dbContext.Foo.Select(/* this is the magic that I'm missing */)`

**Comment by TylerCarlson1** [comment]
With your attribute using `ObjectContext.ObjectMaterialize` event, do you know if it gets called on project to?  If not then you need an alternative solution.

If so, then the object you are making doesn't have your attribute.  You need to either put the attribute on the DTO object being projected to, or rewrite the attribute to find type maps back to your EF object and find property maps with that attribute.

I would suggest the putting the attribute in the DTO is easiest option if  `ObjectContext.ObjectMaterialize` gets called when you ProjectTo

**Comment by lisamariet** [comment]
Bugger... After checking again I see that no, manual select does not work either. :-(

**Comment by TylerCarlson1** [comment]
@lisamariet 
http://stackoverflow.com/questions/29778021/objectmaterialize-in-ef-not-firing-on-first-level-query
says it won't work cause the object is not an entity object. :(

**Comment by lisamariet** [comment]
Double bugger... but that explains it I guess. Thanks.

**Comment by jbogard** [comment]
As an aside, we're working very hard in AutoMapper 5.0 to improve its performance so that the decision between ProjectTo and Map is just based on whether you want LINQ or not, not based on any potential perf gains.

**Comment by TylerCarlson1** [comment]
Except for the cases of the N+1 of course.  But if, like your example, are only calling against one table that's not the case.

**Comment by jbogard** [comment]
Well I'll just assume that everyone knows about .Include and knows how and when to use it forever and ever

**Comment by lisamariet** [comment]
It is not only 1 table... there are multiple... as this is open for OData query so one can extend and filter and make this complex query. I just kept the code simple to the point :-)

**Comment by TylerCarlson1** [comment]
Something that might work is
`ForMember(d => d.EndretUtc, opt => opt.ProjectUsing(s => new DateTime(s.EndretUtc.Ticks, DateTimeKind.Utc)))`

**Comment by lisamariet** [comment]
There is no opt.ProjectUsing method?

**Comment by TylerCarlson1** [comment]
Sorry my bad use `MapFrom` instead of `ProjectUsing`

**Comment by lisamariet** [comment]
Nope. That does not work either. 
"Only parameterless constructors and initializers are supported in LINQ to Entities."
