### ISSUE TITLE
Problem loading two versions of AutoMapper into the same application

### ISSUE THREAD

**Issue by Kamarey** [AutoMapper/AutoMapper#1234]
I have an assembly (call it A1) that use some version of AutoMapper, say v4.
There is also a reference to a third party assembly (call it A2), which use another version of AutoMapper, say v3. 
I use the AppDomain.AssemblyResolve event to resolve missing/conflict assemblies (not only AutoMapper).

The problem is in the next flow:
* the main application is starting (none of AutoMapper assemblies are loaded at this point)
* A1 call some code within the A2 which cause the AutoMapper v3 to be loaded and several mapping are created
* A1 call some internal code, which cause the AutoMapper v4 to be loaded. This reset all previously created mappings.

Because of the AssemblyResolve it's possible to load both versions at the same time. In theory it shouldn't be a problem, as two assemblies don't share any of AutoMapper staff. In practice the last loaded AutoMapper assembly reset all existing configuration.
I know I can keep using the old v3 in the A1, but it's ugly.... just because of some old third party assembly

**Comment by lbargaoanu** [comment]
You can use a binding redirect and use only the new version.

**Comment by Kamarey** [comment]
It's not always an option to use only a new version. It's possible that the existing third party assembly contains a code, that will not work with a new version of an AutoMapper.
Also I'm trying to not use binding redirect configurations due complexity of its maintenance and synchronization. Instead I do you AssemblyResolve event, which can't help in this case.
In general I agree it's possible to find workarounds... but may be better to fix the problem itself... if possible

**Comment by lbargaoanu** [comment]
I don't think two versions of AutoMapper share anything. They are two different instances each with their own data. I don't see how one could reset the other.

**Comment by jbogard** [comment]
You should be able to use the new instance API too, instead of Mapper.Initialize.
