### ISSUE TITLE
Mixed use of direct mapping and projection in the same class?

### ISSUE THREAD

**Issue by crowbarsolutions** [AutoMapper/AutoMapper#1235]
I'm currently migrating away from the static API, and having my mapping config passed in through DI (autofac)

Suppose I have a class where I am using both linq projections and direct mapping. According to the blog post, I pass in a `MapperConfiguration` object to the `ProjectTo()` method for Linq projections, and I use an instance of `IMapper` created by doing `myMapperConfiguration.CreateMapper()` for my direct mapping.

Which of the following would be considered the best practice?

Option 1: Pass in the `MapperConfiguration` and `IMapper` as two seperate dependencies.
```
private readonly MapperConfiguration _mapperConfiguration;
private readonly IMapper _mapper;

public MyClass(MapperConfiguration mapperConfiguration, IMapper mapper)
{
	_mapperConfiguration = mapperConfiguration;
	_mapper = mapper;
}

public IEnumerable<FooVm> SomeProjection(IQueryable<Foo> fooModel)
{
	return fooModel.ProjectTo<FooVm>(_mapperConfiguration);
}

public FooVm SomeDirectMapping(Foo fooModel)
{
	return _mapper.Map<FooModel, FooVm>(fooModel);
}
```

Option 2: Only pass in the `MapperConfiguration` and create the IMapper object on every necessary instance of direct mapping.

```
private readonly MapperConfiguration _mapperConfiguration;

public MyClass(MapperConfiguration mapperConfiguration)
{
	_mapperConfiguration = mapperConfiguration;
}

public IEnumerable<FooVm> SomeProjection(IQueryable<Foo> fooModel)
{
	return fooModel.ProjectTo<FooVm>(_mapperConfiguration);
}

public FooVm SomeDirectMapping(Foo fooModel)
{
	return _mapperConfiguration.CreateMapper().Map<FooModel, FooVm>(fooModel);
}

```

Option 3: Only pass in the `IMapper` and access the `MapperConfiguration` when necessary using the `ConfigurationProvider` accessor.

```
private readonly IMapper _mapper;

public MyClass(IMapper mapper)
{
	_mapper = mapper;
}

public IEnumerable<FooVm> SomeProjection(IQueryable<Foo> fooModel)
{
	return fooModel.ProjectTo<FooVm>(_mapper.ConfigurationProvider);
}

public FooVm SomeDirectMapping(Foo fooModel)
{
	return _mapper.Map<FooModel, FooVm>(fooModel);
}
```

Any other options I'm missing?

If it matters this is how I'm configuring my DI:

```
containerBuilder.RegisterType<MappingProfile>().As<Profile>();
containerBuilder.Register(context => new MapperConfiguration(cfg =>
{
	foreach (var profile in context.Resolve<IEnumerable<Profile>>())
	{
		cfg.AddProfile(profile);
	}
})).AsSelf().SingleInstance();

containerBuilder.Register(c => c.Resolve<MapperConfiguration>().CreateMapper(c.Resolve))
	.As<IMapper>()
	.InstancePerLifetimeScope();
```

**Comment by lbargaoanu** [comment]
The mapper is thread safe and is designed to be reused so CreateMapper should be called only on initialization. If you use the same configuration for Map and ProjectTo, it's simpler to reuse IMapper.ConfigurationProvider. It makes sense to pass both only when they use different configuations.
