### ISSUE TITLE
MapFrom should include index when mapping

### ISSUE THREAD

**Issue by drusellers** [AutoMapper/AutoMapper#1238]
When mapping collections of objects, it would be valuable to have the index of the object being mapped much like is available with `Select((item, index) => {})`.

Currently, I have to create an Tuple<int, TMappedEntity> that is then passed into AutoMapper. This hides the mapping data and generally makes things less pleasant. 

I'd like to propose an overload to `MapFrom` that exposes `Expression<Func<TSource, int, TMember>>` as the mapping expression.

It would act as a short cut to 

```
  .ForMember(dest => dest.RecordNumber, opt => opt.ResolveUsing(res =>
                {
                    return res.Context.ArrayIndex;
                }))
```

**Comment by jbogard** [comment]
That would be a bit weird, as I'd have a map configuration that assumes it's part of a collection. And not all collections keep track of the index. Just use the resolution context bruh.

**Comment by drusellers** [comment]
Can do. :) I need to play around more with the context bits.
