### ISSUE TITLE
Mapping a list of ExpandoObjects

### ISSUE THREAD

**Issue by victorbotamedi** [AutoMapper/AutoMapper#1239]
If i try to map a list of `object` where all objects are Expando objects the properties are not being mapped, the objects are created but all property values are null.

For example:
```c#
class Foo
{
    public string A { get; set; }
    public string B { get; set; }
}
```

If i create a list of objects and try to map:
```c#
dynamic fooA = new ExpandoObject();
fooA.A = "a";
fooA.B = "b";
dynamic fooB = new ExpandoObject();
fooB.A = "c";
fooB.B = "d";

var fooList = new List<object>() { fooA, fooB };
var foos = Mapper.Map<List<Foo>>(fooList);
```
The `foos` list will have two elements, but all properties will be null.

I've found two workarounds for this, one is to create the List as `List<ExpandoObject>` instead of
`List<object>`, but in my case this is not possible since a third party library return its objects as `List<object>`.
Another solution is to explicitly declare the `ConvertUsing` inside mapper configuration:
```c#
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<ExpandoObject, Foo>()
        .ConvertUsing(obj =>
            {
                dynamic expando = obj;
                return new Foo
                {
                    A = expando.A,
                    B = expando.B
                };
            });
     });
```

Since dynamic objects can be mapped to any object without any explicit configuration (and it works perfectly), i want to know if i'm missing something here...

Any thoughts?

Thanks

**Comment by lbargaoanu** [comment]
Did you try the MyGet build?

**Comment by victorbotamedi** [comment]
@lbargaoanu it works perfectly with the myget build, thanks :)
i'll wait for a beta release then

Thanks!

**Comment by lbargaoanu** [comment]
You can close the issue.
