### ISSUE TITLE
How to Conditionally Set UseDestinationValue()?

### ISSUE THREAD

**Issue by kabua** [AutoMapper/AutoMapper#1242]
When mapping a source graph to an existing destination graph, we need to be able to control when the destination property is updated or replaced, depending on the state of _both_ the source property and the destination property, thus maintaining the integrity of the destination graph.

To maintain the integrity of the destination graph, reference objects and collections must be evaluated during the mapping process.

**Reference Objects**:
For example; let's say that we have a `Person` object that includes a `PhoneNumber` object and the `PhoneNumber` object contains an `int Id` property.

**Proposed Mapping**:
We would like to create a mapping something like this: 

    CreateMap<PersonDto, PersonDomain>()
        .ForMember(dest => dest.Phone, map => map.UseDestinationValue
        (ctx => ctx.Dest != null && ctx.Src != null && 
        (ctx.Dest.PhoneNumber.Id == 0  ||  ctx.Dest.PhoneNumber.Id == ctx.Src.PhoneNumber.Key)));

Or:
    
    CreateMap<PersonDto, PersonDomain>()
        .ForMember(dest => dest.Phone, map => map.UnqiueIdentify(
            destPhone => destPhone.Id, src => src.CellPhone.Key));

Or better yet:
    
    CreateMap<PersonDto, PersonDomain>()
        .ForMember(dest => dest.Phone, map => map.IsEqual(src, dest =>
            dest.Phone.Id == 0 || 
           (src.Phone.Id == dest.Phone.Key && src.SomthingElse == dest.SomethingDifferent)));

**Example Usage**:

    var rootEntity = // Existing domain graph
    var updatedDtoGraph = repo.Update(rootEntity.ToDto());  

    // Map the updated object graph to the existing domain object graph.
    Mapper.Map(updatedDtoGraph, rootEntity);

**Collections**:
We would like to extend this idea to items within a collection. Currently, new items are added and deleted items are removed from the destination collection - which is good. However, existing items are both removed and then re-added, as new objects - thus breaking the existing object graph.

**Expected Result**: 
Existing items, based upon some criteria (i.e. ID values), should be updated and not reconstituted. 

For example: let's say the `Person` class contains a `LivingChildren` property. If my daughter gets married, then only her last name should change. She should not be delete and then reconstitute as a new daughter. Otherwise, other objects, that are associated with my original daughter, wouldn't know about her name change; and the destination object graph will end up as a mess, especially if the update process is repeated.

**Proposed Mapping**:
Not sure, perhaps something like:

    CreateMap<PersonDto, PersonDomain>(map => 
        map.IsEqual(src, dest => src.Key == dest.Id));

Which would compare at the object level and not at the member level, thus making object comparison possible for collections.

**Full Example**:

    CreateMap<PersonDto, PersonDomain>(map => map.IsEqual(src, dest => src.Key == dest.Id)
        .ForMember(dest => dest.Phone, map =>  map.IsEqual(src, dest => dest.Phone.Id == 0 || (src.Phone.Id == dest.Phone.Key && src.SomthingElse == dest.SomethingDifferent)));

**Comment by TylerCarlson1** [comment]
What it  sounds like you want is [AutoMapper.Collection](https://github.com/TylerCarlson1/Automapper.Collection).

It's on Nuget as well and there's an EF and LinqToSQL version that will do the ID comparisons for you automaticly.  And also has extension methods to persist (insert/update/delete) to the database

**Comment by kabua** [comment]
It looks like it will solve my issue for collections but what about instance properties? E.g. ```Person.Father```. 

Will it update ```person.Father``` if ```person.Father.Id == 0 || person.Father.Id == dto.Father.Id``` and assign ```dto.Father``` to ```person.Father``` if ``Id```s don't match?

**Comment by TylerCarlson1** [comment]
Automapper.Collection won't handle the instances properties like you described.  What usually happens is if you are changing father you would want to update the FatherID and not update Father class.  If you are updating Father and never changing father you should map the Father property.  If you are doing both, especialy at the same time, then I don't know what you would do in that scenario.  I have never ran into it.

**Comment by TylerCarlson1** [comment]
Oh and if in your scenarios Father for both dto and person are the same class, then no it won't work.  You'll need to make DtoFather and Father in order for it to work, and you should.

Probably not the case but pointing it out if it is.
