### ISSUE TITLE
Mapper first item from List to Class

### ISSUE THREAD

**Issue by mintssoul** [AutoMapper/AutoMapper#1246]
Dear All

I got a object 'ProductA' which contains a list of 'ProductInformationA'
which I would like to map to another object 'ProductB' which contains AN OBJECT 'ProductInformationB' only instead of a list

The concept is just get the first item in list and map to another object
and ignore other items in the list

I guess is something like
 cfg.CreateMap<ProductInformaionA[], ProductInformationB>()
                        .ForMember(dest=>dest, opt=>opt.MapFrom(src=>src.FirstOrDefault()));

but it raise error, could anyone suggest how to do it?
Thanks
MS

**Comment by lbargaoanu** [comment]
Try ResolveUsing.
