### ISSUE TITLE
Mapping of two different enum types with same property name

### ISSUE THREAD

**Issue by gregbty** [AutoMapper/AutoMapper#1247]
I have two objects with two properties that have the same name but of different enum types:

```
Object1.EnumType (EnumType1) -> Object2.EnumType (EnumType2)
```

Is it possible to ignore these mappings automatically without explicitly doing so?

**Comment by jbogard** [comment]
What is the desired behavior here? Make it so where any time I have EnumType1 -> EnumType2 do nothing?

**Comment by gregbty** [comment]
Yes without explicitly doing:

```csharp
Mapper.CreateMap<Object1, Object2>()
   .ForMember(s => s.EnumType, d => d.Ignore());
```

The problem is that I have a bunch of types that have this similar structure and want to refrain from explicitly mapping them each time if possible.

**Comment by TylerCarlson1** [comment]
Might want to look into [Member Configurations](https://github.com/AutoMapper/AutoMapper/wiki/Conventions#member-configuration).  Although it's not going to be pretty to get it to work.

It's designed for making your own conventions for member mapping; Not modify the default name matching members.  You will have to tinker with it beyond what the wiki explains, and possibly look at source control, to remove the default name match resolver and replace it with one where you can put your logic to ignore enum type.

What you would need to do is remove DefaultName from the list and replace it with your own class that ignores if the types match your scenario.

Another option is to add a condition to the get members rules to exclude the properties you don't want mapped.
```
cfg.MemberConfigurations.First().NameMapper.GetMembers.AddCondition(m => !(m is PropertyInfo) || (m as PropertyInfo).PropertyType != typeof(EnumType1));
```
But with this you aren't mapping any properties of EnumType1 to anything.

Either solution is a little convoluted, but it should work in making a rule across the board to exclude your scenario you don't want mapped.

**Comment by jbogard** [comment]
I was looking at a TypeConverter, but what might be cool is to define a
conditional ForAllMembers at the Profile level. You get a Func<MemberInfo,
bool> etc

**Comment by TylerCarlson1** [comment]
I think the type converters wouldn't work cause the EnumMapper will override it.
You can do ForAllMembers at the DefaultMemberConfiguration as well, but that blocks all mapping options, where you might want just 2 types to never map to each other.

Maybe ForAllMaps could work with ignoring property maps perhaps.

**Comment by lbargaoanu** [comment]
A TypeConverter for the enum types would do the job.

**Comment by gregbty** [comment]
I'll just stick to the explicit mappings for now. I was more curious if there was a simple way to add ignore rules for all cases of my scenario. Thanks for the help guys.
