### ISSUE TITLE
IObjectMapper refactoring

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1249]
The `IObjectMapper` interface as it now stands is a bit limiting. At this point, `ITypeConverter` is more convenient for many scenarios as it is now fully generic and supports open generics with multiple parameters. Type converters aren't a great replacement for object mappers though as you can't really override a type map with totally different behavior, nor is there any precendence as there is with object mappers.

The other annoying thing about object mappers is there are some that can be classified as an inline mapping operation, like the string mapper. These are ones that can be most easily represented as an expression and doesn't need the full rigamoral of a new resolution context.

So I'm proposing two interfaces, one is a generic IObjectMapper, where the more complicated object mappers stay as is but can be an open generic type that gets closed. Like `ArrayMapper` gets converted to a generic one of `ArrayMapper<TSource[], TDestination[]>`. Then the string mapper wouldn't be generic since we'd be working with type objects inside the type map plan builder, and just builds an `Expression` based on the source, destination and context params passed in. Not even a lambda since it gets inlined.

I haven't fully thought this through but if these concepts are added it should be easy to convert he existing ones.

The precedence would be: TypeMap, INewFangledObjectMapper, IObjectMapper.

Unknown is how the inline expression mappers would overlap with the ones in LINQ or being accessed outside of the expression building spots in the type map expression builder.

Anyway, some initial thoughts @TylerCarlson1 @lbargaoanu

**Comment by TylerCarlson1** [comment]
I think you could build every expression with INewFangledObjectMapper, you just would have to pass in quite a few expressions to do so.  You need the source expression, destination expression, and resolution context expression.  Possibly the source and dest object parameters as well.  From there you should be able to mimic all the functionality of the Map function, although it will take a while to translate everything.

I'm working on converting them now, but theoretically it should work.  I need to keep converting every one to see how far I can go.  I know something like the Enum mapper has a bunch of if statements that can be taken out  and just build a single expression, so I'm pretty sure Collection Mappers can do the same.

As far as the overlap with LinqMappers I'm not sure as well.  But after all is said and done and we can re-use code I would suggest an attribute or interface to say ILinqExpression and only use ones of those types for ExpressionVisitor.  But for now I say keep them completely separate until all is said and done on IObjectMapper

**Comment by jbogard** [comment]
So one problem with making them all expressions is the compilation is
slooooooow. That's why I thought of two kinds, one where you get generics
so no boxing and converting, vs things like the ConvertMapper
EnumMapper etc that can all be broken out into single expression converters
per if.

**Comment by TylerCarlson1** [comment]
You wouldn't compile them all all the time, just once on seal.
Also maybe another way is make a Generic function that handles all the code and just call it.

So src, dest translate to `MapCollection<Source,Dest>` and `MapHashSet<Source,Dest>` ect.  That way no compilation on code on seal and you just call a static function and when you look at code generated you don't see the messy details and it's just a one liner.

That would mean all the others that assign values would need to return the assign function, but that could work out in both cases.

**Comment by TylerCarlson1** [comment]
Here's a rough idea of how it might work.  Haven't got to try it out though :(
```
public class HashSetMapper : IObjectMapper
    {
        public static ISet<TDestElement> CreateMap<TSource, TDest, TSourceElement, TDestElement>(TSource source, TDest dest, ResolutionContext context)
            where TDest : ISet<TDestElement>
            where TSource : IEnumerable<TSourceElement>
        {
            var collection = (ISet<TDestElement>)dest ?? (typeof (TDest).IsInterface()
                ? new HashSet<TDestElement>()
                : ObjectCreator.CreateDefaultValue(typeof (TDest)) as ISet<TDestElement>);

            collection.Clear();
            foreach (var item in source)
                collection.Add((TDestElement)context.Mapper.Map(item, null, typeof(TSourceElement), typeof(TDestElement), context));

            return collection;
        }
        
        public Expression Expresssion(Expression source, Expression destination, ParameterExpression resolutionContextExpression)
        {
            var srcType = source.Type;
            var destType = destination.Type;
            var srcElementType = srcType.GetElementType();
            var destElementType = destType.GetElementType();
            var createMap = typeof (HashSetMapper).GetMethod("CreateMap", BindingFlags.Static | BindingFlags.Public).MakeGenericMethod(srcType, destType, srcElementType, destElementType);
            return Expression.Call(Expression.Constant(null), createMap, source, destination, resolutionContextExpression);
        }

        public bool IsMatch(TypePair context) => context.SourceType.IsEnumerableType() && IsSetType(context.DestinationType);

        private static bool IsSetType(Type type)
        {
            if (type.IsGenericType() && type.GetGenericTypeDefinition() == typeof (ISet<>))
            {
                return true;
            }

            IEnumerable<Type> genericInterfaces = type.GetTypeInfo().ImplementedInterfaces.Where(t => t.IsGenericType());
            IEnumerable<Type> baseDefinitions = genericInterfaces.Select(t => t.GetGenericTypeDefinition());

            var isCollectionType = baseDefinitions.Any(t => t == typeof (ISet<>));

            return isCollectionType;
        }
}
```

If this works maybe it could be refactored to read better and easily copy pasted into other mappers, in which case they aren't so convoluted in how they work.

Anyways I think this is much more reasonable to maintain and not have the lists turn into some convoluted object casting nonsense that takes 2 hours to even understand.

In expression it might look like this for the property map
```
src.HashSet = HashSetMapper.CreateMap<HashSet<SrcElement>, IEnumerable<DestElement>, SrcElement, DestElement>(src.HashSet, dest.Enumerable, ctxt);
```
Maybe not what you expect but it doesn't bloat the TypeMap expression and you can debug the hash set mapping.

**Comment by jbogard** [comment]
So I'd rather avoid expressions on the IObjectMapper because it won't really offer any improvements in terms of speed. The TypeMap speed ups are there because we pre-wire decisions based on TypeMap configuration, but the amount of config that affects the IObjectMapper stuff is pretty small. There's just not an advantage (from looking at the profiler) that a compiled expression would show here. 

My thought was something like:

```
public interface IObjectMapper<in TSource, out TDestination>
{
    TDestination Convert(TSource source, ResolutionContext context);
}

public class HashSetMapper<TSource, TDestination> : IObjectMapper<ISet<TSource>, ISet<TDestination>>
{
    public ISet<TDestination> Convert(ISet<TSource> source, ResolutionContext context)
    {
        if (context.IsSourceValueNull && context.Mapper.ShouldMapSourceCollectionAsNull(context))
        {
            return null;
        }

        ISet<TDestination> destination = (ISet<TDestination>)context.SourceValue ?? new HashSet<TDestination>();

        destination.Clear();

        foreach (var item in source)
        {
            destination.Add(context.Mapper.Map(item, default(TDestination), context));
        }

        return destination;
    }
}
```

**Comment by jbogard** [comment]
You know looking at this `IObjectMapper` now has the same signature as `ITypeConverter`. But it looks clean as hell, no?

One improvement is that if this could be represented with an expression mapper is "should map source collection as null" part. That could be inlined. But it's a small improvement, and I really like that I can debug collection mapping as that's where I tend to get weird bugs.

**Comment by TylerCarlson1** [comment]
It seems the only difference between yours and mine is yours needs a new instance every time where mine is static and can be called without newing up an object.
Well there's just newing the object vs using reflection to new it up, but that's a minor detail.  And you should pass in the destination object so there's no casting call.

I know putting generic arguments in function and not a class is not the preferred way of programming, but if you do this then you won't have to new up a new HashSetMapper for every time you map, saving time and memory.  Else you would have to cache said mapper anyways.  Also if it's not static you are going to have to set a variable to make the mapping work in an Expression environment.

If you do expression with static you won't have to call Map and call IsMatch, so saves having to figure out which one to map to.

**Comment by jbogard** [comment]
Oh, I was still planning to wrap all this in an expression when you're matching it up in the ConfigurationProvider class. I was hesitant to pass it in though because it meant that you lose variance on the TDestination parameter. But perhaps that doesn't matter.

**Comment by TylerCarlson1** [comment]
The other thing that needs to be done is pass the Configuration provider into BuildMapperFun call, so that can compare conditions against object mapers that do expressions.

**Comment by jbogard** [comment]
The more I go into this I wonder if this might be a bit too much for this release. I'm going to switch gears and try to get the netstandard stuff going.

**Comment by TylerCarlson1** [comment]
@jbogard Is the .Net Standard stuff have an actual release date now?
I think with whatever implementation you go,mine or yours, just getting the Generic code to be called in a generic function call, that's debug-able is a step that can be added without completely destroying the current system.  Expressions can come later if that's the case
