### ISSUE TITLE
Mapper.GetAllTypeMaps() obsolete

### ISSUE THREAD

**Issue by rafakwolf** [AutoMapper/AutoMapper#1252]
This method is obsolete -> Mapper.GetAllTypeMaps()
What can i use instead ?
Sorry for the question here, thanks.

**Comment by jbogard** [comment]
Use `Mapper.Configuration.GetAllTypeMaps()`.

**Comment by rafakwolf** [comment]
@jbogard i'm sorry but , Mapper.Configuration is bosolete to, and the method GetAllTypeMaps() don't exists. :|

Thanks

**Comment by jbogard** [comment]
Have you tried the myget feed? It's not obsolete there, and the method does exist there too.

**Comment by rafakwolf** [comment]
OK, i will try myget, thanks

**Comment by MrDesjardins** [comment]
I had a similar problem after migrating with the new version that obsolete static methods. 

I was using Mapper.Engine.ConfigurationProvider.GetAllTypeMaps() which wasn't working after the update. I meant by not working that it wasn't able to get the type maps from the MapperConfiguration.

To fix it, I had to get the configuration and use 

```
            var config = new MapperConfiguration(cfg =>
            {
                foreach (var profile in profiles)
                {
                    cfg.AddProfile(profile);
                }
            });
            config.CreateMapper();
```

and use

`          config.GetAllTypeMaps()`

Hope it helps!
