### ISSUE TITLE
Recognize pre/postfixes in ctor args

### ISSUE THREAD

**Issue by epitka** [AutoMapper/AutoMapper#1253]
As per user group I am opening this as a improvement request.

Is there a way to map through a constructor while using a mappers for each of the parameters. For example if I have a dto

```
   public class CreateBid
   {
      public int ClientId { get; set; }
      public int RegulatoryBodyId {get;set;}
      public string Descripption {get;set;
    }
```
and command

```
   public class CreateBidCommand
   {
      public CreateBidCommand(Client client, 
             RegulatoryBody regulatoryBody, string description)
      {
           Client = client;
           RegulatoryBody = regulatoryBody;
           Description = description;
      }

      public Client Client {get;}
      public RegulatoryBody RegulatoryBody {get;}
      public string Description {get;}
  }

```
and I have setup automapping based on the suffix so that for example RegulatoryBodyId is mapped to instance RegualtoryBody,

I have all working if I make properties on my command public, which is not what I want.

What I want is for automapper to use constructor, and see that on source I have ClientId, in constructor I have a instance of Client, so use map to map int=>typeInstance. For all other members that are not in constructor use property mapping. Is this possible?

Just to re-iterate following works

`_mapper.Map<int,Client>(112313);`
or

`_mapper.Map<string,SomeType>("someCode");`

What I want is to apply this to every matching member in the constructor, based on the suffixes defined in the profile.

**Comment by epitka** [comment]
This is already working but there might be a bug also, or it just needs some more configuration options. Here is what is happening. It actually uses constructor, uses correct mapper based on the mapping set up using postfixes. But after that it uses also setter, even if the setter is private on the property. For me this is not an issue, as on commands all my required properties do not have setters, so not big deal. But if there are properties with setters than there is an issue as the value is set twice. This would be an issue also if there is a condition that value of the property cannot be set if there is already value in backing field etc.

 public class When_mapping_through_constructor_with_postfixes_on_source : AutoMapperSpecBase
        {
            public class MyType
            {
                public string ObjectId = Guid.NewGuid().ToString();
            }

            Destination _destination;
            public class Destination
            {
                private  MyType _myType;

                private Destination()
                {
                    
                }
                public Destination(MyType myType)
                {
                    _myType = myType;
                }

                public MyType MyType
                {
                    get { return _myType; }
                      //uncomment this to get an error
                    //private set
                    //{
                    //   throw new Exception("Should not set through setter.");  
                   // }
                }
            }

            public class Source
            {
                public int MyTypeId { get; set; }
            }

            protected override MapperConfiguration Configuration
            {
                get
                {
                    return new MapperConfiguration(cfg =>
                    {
                        cfg.RecognizePostfixes("Id");
                        cfg.CreateMap<Source, Destination>();
                        cfg.CreateMap<int, MyType>().ConstructProjectionUsing(id => new MyType());

                    });
                }
            }

            protected override void Because_of()
            {
                _destination = Mapper.Map<Destination>(new Source()); 
            }

            [Fact]
            public void Should_map_ok()
            {
                _destination.MyType.ShouldNotBeNull();
            }
        }

**Comment by jbogard** [comment]
So the prefixes work but the value is set through the constructor and the property?

**Comment by epitka** [comment]
Yes.  Also another "bug" I found it that optional parameter does not get set through constructor. I was able to switch 90% of commands, to be mapped through constructor, but the ones that have optional parameter, they don't get set, and it is not complex type, but boolean value.

**Comment by jbogard** [comment]
Can you open a new issue for that?

**Comment by jbogard** [comment]
Also, setting a property both in the constructor and property map is a tough one to fix. I'd have to build the logic based on source items only being mapped once. I can't make an assumption any way else - I don't want to assume that a constructor argument with a certain name just happens to line up with a property name. But I could assume that a source member Foo that matches with destination ctor arg "foo" then doesn't need to match up to the destination property "Foo".

You can see this gets quite complicated.

**Comment by epitka** [comment]
Yes sure, I thought about it also, it would be quite complex, maybe look for backing field, but a lot of assumptions, as you don't know what is happening in constructor. But as I said, i removed private setters from my commands and it all works quite good.

**Comment by lbargaoanu** [comment]
Ignoring that property is an easy workaround.

**Comment by lbargaoanu** [comment]
About optional arguments, we need a failing test with the MyGet build, because the tests we have are ok.

**Comment by epitka** [comment]
@jbogard: Actually, thinking more about it, it should not be that complicated. I would expect that you first look at the constructor, and match up the source members. All source members that are not matched up in constructor, would then be mapped through properties.  I would think that this would be a reasonable assumption. I have never seen code where a parameter in constructor has a name that is the same as property (casing aside) that is not mapped to a property through constructor.

**Comment by jbogard** [comment]
I haven't either, and I think your proposal makes sense. It's complicated slightly in that source members are flattened, so I'm not matching up one source member, but a chain of source members, Foo.Bar.Baz properties -> fooBarBaz ctor arg

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by lbargaoanu** [comment]
Actually no :) Prefixes don't work for constructor parameters. The test is misleading.
