### ISSUE TITLE
What is the best: Static or Non-static ?

### ISSUE THREAD

**Issue by webmaniak** [AutoMapper/AutoMapper#1255]
Hi !

I've been using AutoMapper for about one year now and I really enjoy this API. However, some breaking changes in 4.2 introduced some confusion in my head. The static API was flagged 'obsolete' for a few weeks and now it's not anymore so I'm wondering what the official roadmap is.

Some of my projects still use `AutoMapper.Mapper.Map<Object>()` and I'm wondering if I should migrate them to use the new non-static API instead. I'm planning a global migration to the latest (4.2.1) version for 5-6 projects, that's why.

**Is it better to use the static or the non-static API? What would be your advice on that point?**
Thanks a lot.

**Comment by jbogard** [comment]
I need to update the documentation on this, but I restored the static API where it made sense. What won't be supported is Mapper.CreateMap, but Mapper.Initialize and Mapper.Map ARE supported and will continue to be.

**Comment by webmaniak** [comment]
Thanks for your quick answer, that's all I wanted to know. :)
