### ISSUE TITLE
Calculated properties interfering with each other

### ISSUE THREAD

**Issue by levitatejay** [AutoMapper/AutoMapper#1256]
Starting a new project in .NET Core with EF7... I have the following configuration in my Startup.cs:

`                config.CreateMap<Product, ProductPartialDto>()
                    .ForMember(dto => dto.CustomerCount, opt => opt.MapFrom(src => src.LicenceProducts.Count))
                    .ForMember(dto => dto.UserCount, opt => opt.MapFrom(src => src.ProductUsers.Count))
                    .ReverseMap();`

When I use projection both properties (UserCount & CustomerCount) are set to whichever rule is last in the chain in the fluent syntax...

So for example if the CustomerCount map rule is after the UserCount map rule then both CustomerCount & UserCount will equal CustomerCount for every mapped entity.

**Comment by TylerCarlson1** [comment]
Is this projection or mapping.  Also does the same thing happen when using EF6?

**Comment by levitatejay** [comment]
Sorry I should have specified. This happens when using projection. I'm unable to test with EF6 at the moment.

**Comment by TylerCarlson1** [comment]
Yea with projection it might be an issue with EF7 not being able to handle it.  Can you try with an equivalent select statement and see if that works?  I might of seen it before with EF7 but that was a long time ago.

something like this I think
```
context.Products.Select(p => new ProductPartialDto { CustomerCount = p.LicenceProducts.Count, UserCount = p.ProductUsers.Count });
```
and if order causes the same thing to happen, then it's EF7 that has the problem.

**Comment by levitatejay** [comment]
Thanks, turns out it is an EF7 issue.

I opened an issue here: https://github.com/aspnet/EntityFramework/issues/5264

**Comment by jbogard** [comment]
"Created a project with .Net Core and EF7" all sorts of luck to you
