### ISSUE TITLE
Dynamic mapping with nested dynamic objects

### ISSUE THREAD

**Issue by barriestewart** [AutoMapper/AutoMapper#1257]
With AutoMapper 4.2.1, when mapping from a dynamic to an instance of an object, AutoMapper preserves top-level destination object properties with null/default values which do not have a corresponding property in the source object. For any nested properties which are dynamic objects, the same does not hold true. This is probably easiest to explain with an example:

```C#
    class SubSetting
    {
        public int SubTimeout { get; set; }
        public string SubColour { get; set; }
    }

    class Settings
    {
        public int Timeout { get; set; }
        public string Colour { get; set; }
        public SubSetting SubSettings { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // The SubSettings property is another ExpandoObject.
            dynamic baseSettings = new ExpandoObject();
            baseSettings.Timeout = 1;
            baseSettings.Colour = "Red";
            baseSettings.SubSettings = new ExpandoObject();
            baseSettings.SubSettings.SubTimeout = 11;
            baseSettings.SubSettings.SubColour = "Green";

            // Create another object we will map onto the one above. 
            // Notice that we do not set a Colour or SubColour property.
            dynamic overrideSettings = new ExpandoObject();
            overrideSettings.Timeout = 2;
            overrideSettings.SubSettings = new ExpandoObject();
            overrideSettings.SubSettings.SubTimeout = 22;

            var config = new MapperConfiguration(cfg => { });
            var mapper = config.CreateMapper();

            var settings = mapper.Map<Settings>(baseSettings);

            // After this next mapping, settings.Colour == "Red" but settings.SubSettings.SubColour == null.
            mapper.Map(overrideSettings, settings);
        }
    }
```
So as mentioned in the code comments, after the second mapping `settings.SubSettings.SubColour` is null. Is this the intended behaviour for dynamic mapping? I also tried upgrading to the latest MyGet build `5.0.0-ci-1057` to see if it made a difference but that throws the following exception when making the second call to `Map()`:

```
System.InvalidCastException

Unable to cast object of type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.Object]' to type 'System.Func`4[System.Dynamic.ExpandoObject,TestConsoleApp.Settings,AutoMapper.ResolutionContext,TestConsoleApp.Settings]'.
```

**Comment by lbargaoanu** [comment]
Workaround

    mapper.Map<IDictionary<string, object>, Settings>(overrideSettings, settings)

I'll have to dig a little deeper to see if we can do better.

**Comment by lbargaoanu** [comment]
SubColor is null in overrideSettings so it's null in settings, that's what you get with types too I believe. There is a [PR](https://github.com/AutoMapper/AutoMapper/pull/1122) with the behavior you want, but it seems neglected.
