### ISSUE TITLE
Unable to map data table to List<DTO> (version 4.2.1)

### ISSUE THREAD

**Issue by Sheji29** [AutoMapper/AutoMapper#1259]
Hi,

I am trying to map a data table to a list of DTO. PFB the sample code.

![image](https://cloud.githubusercontent.com/assets/17687632/15044099/227ecc16-12f0-11e6-8157-c52ced668652.png)

I am getting the below error 

"Missing type map configuration or unsupported mapping.
Mapping types:
IDataReader -> List`1
System.Data.IDataReader -> System.Collections.Generic.List`1[[ConsoleApp1.Tanks, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Destination path:
List`1
Source value:
System.Data.DataTableReader".

I can see this is a common issue. Does any one know if this has been addressed or please guide me if i am doing it all wrong.

**Comment by TylerCarlson1** [comment]
To Map to and from a data table you need [AutoMapper.Data](https://github.com/AutoMapper/AutoMapper.Data) but unfortunately no one has updated it to work with 4.2.1

So you would have to go back to possibly 4.0.x or 3.x to get the DataTable mapping functionality, or wait for someone to fix it in AutoMapper.Data : (
