### ISSUE TITLE
Automapper cant be packed as a dependency.

### ISSUE THREAD

**Issue by StuartBaker65** [AutoMapper/AutoMapper#1262]
I have had a few problems with AutoMapper when it's installed as a dependent on one of our projects. I originally thought this was NuGet and raised an issue with them: Ref #https://github.com/NuGet/Home/issues/2718 appears to be linked to use of Paket.exe.

Other than repackaging the contents myself or forcing all my project consumers to upgrade is there the possibility of repackaging these?

**Comment by jbogard** [comment]
What's the actual error you're getting?

**Comment by StuartBaker65** [comment]
OMG! I've posted this against the wrong project!
This should have been against StructureMap!! There's room only for one in that room of shame!

**Comment by jbogard** [comment]
lol no worries we've all done it!
