### ISSUE TITLE
Why List Mapping of 5.0.0-ci-1053+ is 8 times slower than 5.0.0-ci-1052?

### ISSUE THREAD

**Issue by yyjdelete** [AutoMapper/AutoMapper#1266]
Test with (some modify to match API of 5.0)
https://github.com/TinyMapper/TinyMapper/blob/master/Source/Benchmark/Benchmarks/CollectionBenchmark.cs

**Comment by lbargaoanu** [comment]
Try calling Map once in the init phase, before measuring.

**Comment by yyjdelete** [comment]
I have done this.

**Comment by lbargaoanu** [comment]
And? :) No difference?

**Comment by yyjdelete** [comment]
Yes. In fact, there is already a `Mapper.Map<Target>(source);` before `Stopwatch.StartNew()`

**Comment by lbargaoanu** [comment]
Sorry, I didn't see that :) I think this is a known issue that will be fixed eventually.
@jbogard I believe calling DynamicInvoke inside the loop is the cause.

**Comment by lbargaoanu** [comment]
A quick fix is to use dynamic.

**Comment by jbogard** [comment]
I had some issues getting dynamic to work, DynamicInvoke is a stopgap.

**Comment by lbargaoanu** [comment]
Not so quick then :)

**Comment by lbargaoanu** [comment]
@yyjdelete You can try the MyGet build.

**Comment by yyjdelete** [comment]
Yes, it works well.
