### ISSUE TITLE
StackOverflow exception in case of nested object mapping

### ISSUE THREAD

**Issue by furqansafdar** [AutoMapper/AutoMapper#1267]
I have these following class under two different namespaces, e.g. Source and Target.

```
public class Instance
{
    public Type Type { get; set; }
    public object Definition { get; set; }
}

public sealed class Class : Instance
{
    private IList<Property> m_Properties;
    public IList<Property> Properties
    {
        get { return m_Properties ?? (m_Properties = new List<Property>()); }
    }
}

public abstract class Member : Instance
{
    public string Name { get; set; }
}

public sealed class Parameter : Member
{
}

public sealed class Property : Member
{
}
```

The Instance class has Definition property of type object that will hold the Class reference so the nested hierarchy will start from here up to N levels deep.

```
IMapper memberMapper = null;
IMapper classMapper = null;

var classConfig = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source.Class, Target.Class>()
        .ForMember(t => t.Properties, opt => opt.MapFrom(s => memberMapper.Map<IList<Target.Property>>(s.Properties)))
        .ForMember(t => t.Definition, opt => opt.MapFrom(s => classMapper.Map<Source.Class, Target.Class>((Source.Class)s.Definition)));
    cfg.CreateMap<Source.Property, Target.Property>();
});            
classConfig.AssertConfigurationIsValid();            
classMapper = classConfig.CreateMapper();

var memberConfig = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source.Member, Target.Member>()
        .Include<Source.Property, Target.Property>()
        .Include<Source.Parameter, Target.Parameter>()
        .ForMember(t => t.Definition, opt => opt.MapFrom(s => classMapper.Map<Source.Class, Target.Class>((Source.Class)s.Definition)));

    cfg.CreateMap<Source.Property, Target.Property>();
    cfg.CreateMap<Source.Parameter, Target.Parameter>();
});
memberConfig.AssertConfigurationIsValid();            
memberMapper = memberConfig.CreateMapper();

var definitionLevel1 = new Source.Class();
definitionLevel1.Definition = definitionLevel1;
definitionLevel1.Properties.Add(new Source.Property() { Name = "PropertyLevel_1.1" });
definitionLevel1.Properties.Add(new Source.Property() { Name = "PropertyLevel_1.2" });

Source.Member sourceMember = new Source.Property()
{
    Name = "Some_Property_Name",
    Definition = definitionLevel1,
    Type = typeof(CompositeType)
};
IEnumerable<Source.Member> sourceMembers = new List<Source.Member>() { sourceMember };
var result = memberMapper.Map<IEnumerable<Target.Member>>(sourceMembers);
```

With following usage its giving StackOverflowException. Why?

**Comment by lbargaoanu** [comment]
Because the the Class->Class mapping calls itself.

**Comment by furqansafdar** [comment]
@lbargaoanu, any workaround to avoid this exception, yet making this transformation work?

**Comment by lbargaoanu** [comment]
Maybe I'm missing something, but I don't see why you would need two mappers or any ForMember customization.

**Comment by furqansafdar** [comment]
@lbargaoanu, If one mapper alone can transform, best, but how?

**Comment by lbargaoanu** [comment]
What's wrong with [this](https://gist.github.com/lbargaoanu/3d53df41e068da4ae2b8021b15733af0#file-gistfile1-txt)?

**Comment by furqansafdar** [comment]
The Definition property of type object inside Instance class is not transforming to Target.

**Comment by lbargaoanu** [comment]
It works for me, maybe you need to upgrade.

**Comment by furqansafdar** [comment]
The transformation is working fine but if you inspect the transformed object, the Definition property is still holding Source reference instead of Target. I am using AutoMapper version 4.2.1.

**Comment by lbargaoanu** [comment]
Yes, that's because object maps to object by assignment :) I've updated the gist.

**Comment by furqansafdar** [comment]
Still the same results, Definition has not changed to corresponding Target types.

**Comment by lbargaoanu** [comment]
Did you copy the class definitions?

**Comment by furqansafdar** [comment]
Yes with class definitions change its working, but i don't have leverage to change source because Source is external system objects that i am mapping to my target objects where i can do necessary changes.

**Comment by lbargaoanu** [comment]
That works too, but it's weird. See the gist.

**Comment by furqansafdar** [comment]
Great, it working now with object to Instance mapping but what if there had been two different objects then how to define explicit mapping configuration?

**Comment by lbargaoanu** [comment]
I don't follow.

**Comment by furqansafdar** [comment]
In this case there was only one property of type object so you defined <object, Instance> map. What if there are more than one property of type object then we might require to explicitly define the mapping. But how?

**Comment by lbargaoanu** [comment]
In a similar way :)

**Comment by furqansafdar** [comment]
@lbargaoanu, i have modified the gist you created adding Value property to Member class in Target namespace.Now i am trying to preserve values using UseDestinationValue() and Ignore() for which i gathered some help from this [post](http://stackoverflow.com/questions/7084346/automapper-and-usedestinationvalue). But its not preserving the values after after remapping. How it can be done?

    namespace Source
    {
        public class Instance
        {
            public Type Type { get; set; }
            public object Definition { get; set; }
        }

        public sealed class Class : Instance
        {
            private IList<Property> m_Properties;
            public IList<Property> Properties
            {
                get { return m_Properties ?? (m_Properties = new List<Property>()); }
            }
        }

        public abstract class Member : Instance
        {
            public string Name { get; set; }
        }

        public sealed class Parameter : Member
        {
        }

        public sealed class Property : Member
        {
        }
    }

    namespace Target
    {
        public class Instance
        {
            public Type Type { get; set; }
            public Instance Definition { get; set; }
        }

        public sealed class Class : Instance
        {
            private IList<Property> m_Properties;
            public IList<Property> Properties { get; set; }
            //{
            //    get { return m_Properties ?? (m_Properties = new List<Property>()); }
            //}
        }

        public abstract class Member : Instance
        {
            public string Name { get; set; }

            private object m_Value;
            public object Value
            {
                get { return m_Value; }
                set { m_Value = value; }
            }
        }

        public sealed class Parameter : Member
        {
        }

        public sealed class Property : Member
        {
        }
    }

            var classConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<object, Target.Instance>()
                    .ForMember(d => d.Definition, o => o.Ignore())
                    .ForMember(d => d.Type, o => o.Ignore());

                cfg.CreateMap<Source.Instance, Target.Instance>()
                    .Include<Source.Property, Target.Property>()
                    .Include<Source.Parameter, Target.Parameter>()
                    .Include<Source.Class, Target.Class>();

                cfg.CreateMap<Source.Class, Target.Class>();
                cfg.CreateMap<Source.Property, Target.Property>()
                    .ForMember(t => t.Value, opt => { opt.UseDestinationValue(); opt.Ignore(); });
                cfg.CreateMap<Source.Parameter, Target.Parameter>()
                    .ForMember(t => t.Value, opt => { opt.UseDestinationValue(); opt.Ignore(); });
            });
            classConfig.AssertConfigurationIsValid();
            var classMapper = classConfig.CreateMapper();

            var definitionLevel1 = new Source.Class { Properties = { new Source.Property { Name = "PropertyLevel_1.1" }, new Source.Property() { Name = "PropertyLevel_1.2" } } };
            definitionLevel1.Definition = definitionLevel1;

            var sourceMember = new Source.Property { Name = "Some_Property_Name", Definition = definitionLevel1, Type = typeof(int) };
            var result = classMapper.Map<Target.Member[]>(new[] { sourceMember });

            var @class = (result[0].Definition as Target.Class);
            @class.Properties[0].Value = "Value 1";
            @class.Properties[1].Value = "Value 2";

            var destinationMember = classMapper.Map<Source.Member[], Target.Member[]>(new[] { sourceMember }, result);

**Comment by lbargaoanu** [comment]
When mapping collections, the values in the destination are ignored.

**Comment by furqansafdar** [comment]
Any workaround?

**Comment by lbargaoanu** [comment]
AutoMapper can't help, you'll have to do it yourself. @TylerCarlson1 can AutoMapper.Collections help?

**Comment by TylerCarlson1** [comment]
Yea [AutoMapper.Collection](https://github.com/TylerCarlson1/Automapper.Collection) should.  Although I'm not 100% sure with all the inheritance going on will cause problems or not.

By default AutoMapper clears out collections and re-makes all the items.  Collections takes a comparison to know which items needs to match to what.  You will just have to provide Equivalency expression for Source.Member to Target.Member classes, so it knows which items match to which when it maps over.  like `(s, t) => s.Name == t.Name`

For mapping you have to make sure the class mapping too is ICollection and can be added and removed from.

```
var destinationMember = classMapper.Map<Source.Member[], Target.Member[]>(new[] { sourceMember }, result);
```
won't be able to Add or Remove items cause an array is a set size.  If you don't add or remove items it might work.

**Comment by furqansafdar** [comment]
@TylerCarlson1, thanks but how to setup Equivalency in above case where i want to ignore overriding Value property in Target.Member. If you can please provide concrete config example because i couldn't think of any solution yet and AutoMapper.Collection looks exciting but new to me :)

**Comment by TylerCarlson1** [comment]
```
var classConfig = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<object, Target.Instance>()
        .ForMember(d => d.Definition, o => o.Ignore())
        .ForMember(d => d.Type, o => o.Ignore());

    cfg.CreateMap<Source.Instance, Target.Instance>()
        .Include<Source.Property, Target.Property>()
        .Include<Source.Parameter, Target.Parameter>()
        .Include<Source.Class, Target.Class>();

    cfg.CreateMap<Source.Class, Target.Class>();
    cfg.CreateMap<Source.Property, Target.Property>()
        .ForMember(t => t.Value, opt => { opt.UseDestinationValue(); opt.Ignore(); });
    cfg.CreateMap<Source.Parameter, Target.Parameter>()
        .ForMember(t => t.Value, opt => { opt.UseDestinationValue(); opt.Ignore(); });

    // Add collection profile and equality comparison
    cfg.AddProfile<CollectionProfile>();
    cfg.CreateMap<Source.Member, Target.Member>().EqualityComparision((s, t) => s.Name == o.Name);
});
```
This is what I would change in the configuration to make it update items instead of completely generating a new list.  This assumes that Name is how you uniquely identify the items and it can never changes.

**Comment by furqansafdar** [comment]
**First attempt as it is:**

> "Unmapped members, Value"

**Second attempt with slight modification**

    cfg.AddProfile<CollectionProfile>();
    cfg.CreateMap<Source.Member, Target.Member>()
        .ForMember(t => t.Value, opt => opt.Ignore())
        .EqualityComparision((s, t) => s.Name == t.Name);

> "Instances of abstract classes cannot be created."

**Third attempt**

    var classConfig = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<object, Target.Instance>()
            .ForMember(d => d.Definition, o => o.Ignore())
            .ForMember(d => d.Type, o => o.Ignore());

        cfg.CreateMap<Source.Instance, Target.Instance>()
            .Include<Source.Property, Target.Property>()
            .Include<Source.Parameter, Target.Parameter>()
            .Include<Source.Class, Target.Class>();

        cfg.CreateMap<Source.Class, Target.Class>();
        cfg.CreateMap<Source.Property, Target.Property>()
            .ForMember(t => t.Value, opt => opt.Ignore())
            .EqualityComparision((s, t) => s.Name == t.Name);

        cfg.CreateMap<Source.Parameter, Target.Parameter>()
            .ForMember(t => t.Value, opt => opt.Ignore())
            .EqualityComparision((s, t) => s.Name == t.Name);

        // Add collection profile and equality comparison
        cfg.AddProfile<CollectionProfile>();
    });

Still no luck, unable to preserve Member Value while automapping.

**Comment by furqansafdar** [comment]
@lbargaoanu, slight changes to model stopped the working of automapper. I have changed the `IList<Property>` to `IList<Member>` inside `Class`. You advise to correct it please. Secondly, updating Automapper version to 5.0 cause the Stackoverflow exception again, why?

    namespace Source
    {
        public class Instance
        {
            public Type Type { get; set; }
            public object Definition { get; set; }
        }

        public sealed class Class : Instance
        {
            private IList<Member> m_Properties;
            public IList<Member> Properties
            {
                get { return m_Properties ?? (m_Properties = new List<Member>()); }
            }
        }

        public abstract class Member : Instance
        {
            public string Name { get; set; }
        }

        public sealed class Parameter : Member
        {
        }

        public sealed class Property : Member
        {
        }
    }

    namespace Target
    {
        public class Instance
        {
            public Type Type { get; set; }
            public Instance Definition { get; set; }
        }

        public sealed class Class : Instance
        {
            public IList<Member> Properties { get; set; }
        }

        public abstract class Member : Instance
        {
            public string Name { get; set; }
        }

        public sealed class Parameter : Member
        {
        }

        public sealed class Property : Member
        {
        }
    }

**Comment by lbargaoanu** [comment]
You need to set PreserveReferences for your maps.

**Comment by furqansafdar** [comment]
Where can i get the reference for using it? and what do you suggest to modify in map config against my model change from `IList<Property>` to `IList<Member>` inside `Class`?

Lastly, what is the best resource to learn Automapper currently the documentation is not comprehensive and merely touching the basic usage only.

**Comment by jbogard** [comment]
The wiki.

**Comment by furqansafdar** [comment]
Appreciate if you can help me sort out the issue that i am having after the slight model change as explained in my previous comments.

**Comment by jbogard** [comment]
Can you try 5.0.1? And I've included a 5.0 upgrade guide in the wiki.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by furqansafdar** [comment]
@lbargaoanu, I have updated Automapper from 5.0.2 to latest 6.1.1 and another issue popped up. It is difficult to explain here so I created a sample showing the problem with 6.1.1 and working fine with old version. How can I share for your review and correction in this matter?

**Comment by jbogard** [comment]
Can you open a new issue? Also we've fixed a number of those `PreserveReferences` to automatically detect them, you may not need them anymore.
