### ISSUE TITLE
Recommended way to manage memory in Wep API

### ISSUE THREAD

**Issue by chrismikec** [AutoMapper/AutoMapper#1270]
The title may be a little misleading. Ultimately, I appear to have a memory leak in my application, mostly within a Web API. I've been using some of the memory dump analysis tools in Visual Studio and it keeps mentioning AutoMapper all over the place. I don't know enough about the tools to confirm that it is definitely a memory leak related to AutoMapper, so I wanted to tell you my setup and perhaps you can tell me if I am doing it wrong!

In my Wep ABI I created a global.asax and put the following in:

    Sub Application_Start(sender As Object, e As EventArgs)

        Mappers.ConfigureTypeMappings()

    End Sub

I don't know if there is a better way to do it in Web API because the only thing this global.asax is used for is this! I don't need it otherwise.

Next, I configure using the following:

    Namespace Mappers

    Public Module AutomapperConfig

        Public Sub ConfigureTypeMappings()

            AutoMapper.Mapper.Initialize(Function(cfg)
                                             cfg.CreateMap( ...

Followed by about 60 different mappers for all of my types in the entire Web API.

Is this the right way to do it for a Web API?

I thought perhaps I should only be doing the configuration in a constructor for each controller so that when I hit the Web API it only configures the mappers it needs, but then I thought why am I doing this in application_start if it doesn't just do it once for me, but I wasn't sure then if it behaves differently for a Web API.

Also, is there some manual disposing of AutoMapper objects/memory I am supposed to be doing, or does that get taken care of automatically?

Thanks!

**Comment by jbogard** [comment]
No, there's not. What specifically does it mention?

**Comment by chrismikec** [comment]
So, my setup looks fine for how I am using it in the Web API? Is it OK to configure lots of mappers all at once like this, or should I on'y be doing the ones I need on this particular Web API call?

Here I grabbed a dump comparison by setting up a baseline, then called the same call on the Web API 5 times from the UI, then grabbed another dump. The attached is the view from visual studio comparing the two dumps.

They seem like significant numbers for such an insignificant action, but I might be wrong!

![memorydumpcapture](https://cloud.githubusercontent.com/assets/8548791/15218120/04423334-1839-11e6-8f27-77e201af2c04.JPG)

**Comment by chrismikec** [comment]
My apologies Jimmy, I double checked my setup and this is actually the dump from the ASP.NET MVC front-end.

I ran it again and I'm not seeing anything obvious jump out at me from the Web API side anymore, so now my concern shifts to the web front-end.

My setup is exactly the same in how I am setting it up (global.asax and static instance). Is there anything I should be doing differently from there?

**Comment by jbogard** [comment]
Nope, but keep in mind that AutoMapper caches a lot of execution plans for mapping, but they only get cached after the first map.

**Comment by chrismikec** [comment]
Thanks Jimmy. I was seeing memory issues on repetitive actions, so the first map would already be done. My big thing was to confirm that I'm not doing something stupid with AutoMapper, which it sounds like I'm not, so perhaps I need to keep searching for the culprit.

Thanks for the help! AutoMapper is awesome by the way, it has saved me a tremendous amount of time.

**Comment by jbogard** [comment]
Let me know if you find anything!
