### ISSUE TITLE
Mapping expressions - CreateMappingExpressions<X, Y>() is missing?

### ISSUE THREAD

**Issue by xplatsolutions** [AutoMapper/AutoMapper#1271]
Based on this answer http://stackoverflow.com/a/7425211/122769 and the comment "They moved CreateMapExpression to `Mapper.Engine.CreateMapExpression<Cat, Dog>();`" in how to map expressions using Automapper and this blog post, http://ahmadreza.com/2014/09/automapper-and-mapping-expressions/ I'm supposed to find the `Mapper.Engine.CreateMapExpression<X, Y>() `generic method which I can't. I can find the `Mapper.Engine.CreateMapExpression(Type, Type) `method instead.

Have in mind that I can't update to the latest version of Automapper due to incompatible PCL profile, I'm using Automapper 4.1.1.

Any ideas how to accomplish this?` Expression<Func<T, bool>> domainPredicate = Map<Expression<Func<T, bool>>>(predicate);`

The exception I'm getting trying the above.

> Mapping types:
> Expression`1 -> Expression`1
> System.Linq.Expressions.Expression`1[[System.Func`2[CharacteristicRiskDTO, Mobile.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[CharacteristicsRisk, Domain.Client.Sync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
> 
> Destination path:
> Expression`1
> 
> Source value:
> p => (p.ReportId == value(Data.Client.Sync.Services.LocalDataService+<>c__DisplayClass45_0).dto.ReportId)

Configuration.

```
Mapper.CreateMap<Expression<Func<CharacteristicsRisk, bool>>,
                Expression<Func<CharacteristicRiskDTO, bool>>>()
                .IgnoreAllNonExisting().ReverseMap().IgnoreAllNonExisting();

```

**Comment by TylerCarlson1** [comment]
If you are trying to do `Expression<Func<T, bool>> domainPredicate = Map<Expression<Func<T, bool>>>(predicate);` that might work as such in 4.1.1 perhapse.  I'm not 100% sure when this was implemented of the top of my head.

If it's there, then there's also another extension method called `UseAsDataSource<T>()` which basicly does your find method, but makes it easier to map back.  So instead of ProjectTo you do UseAsDataSource and it will translate the lambdas back to the base type and then call ProjectTo as the very last step.

Also if doing repository thing you might want to look at https://github.com/TylerCarlson1/Automapper.Collection.  It does some things to help persist easier.

**Comment by xplatsolutions** [comment]
@TylerCarlson1  I have a DataService wrapper on the Repository with the following method. TDto is what the consumer classes deals with, the DTOs and T is the local SQLite entities I pass down to the repository.

```
public async Task<IEnumerable<TDto>> GetAsync<TValue>(long workerId, 
            Expression<Func<TDto, bool>> predicate = null, 
            Expression<Func<TDto, TValue>> orderBy = null)
        {
            Expression<Func<T, bool>> domainPredicate = Map<Expression<Func<T, bool>>>(predicate);
            Expression<Func<T, TValue>> domainOrderBy = Map<Expression<Func<T, TValue>>>(orderBy);
            List<T> domains = await Repository.GetAsync(workerId, domainPredicate, domainOrderBy).ConfigureAwait(false);
            return Map<IEnumerable<TDto>>(domains);
        }
```

Problem is I can't convert the expressions and receive the above. I'll check the link you sent but I don't think it solves this problem right?

**Comment by TylerCarlson1** [comment]
Ok I see yea if you don't have IQueryable then UseAsDataSource isn't gong to help you.
What I was thinking is you do `var query = Db.Table<T>().UseAsDataSource<TDto>();` in which case you can use the TDto predicates without having to translate them.

The functionality is there for 4.1.1 for expression mapping and UseAsDataSource.  The only thing I can see that's wrong is that if you have a null for predicate or orderBy you need to check if null and then map them.  In the code if you try to map expressions and the source is null you will definitely get an ArgumentNullException.

Other than that it should work fine.
something like `Expression<Func<T, bool>> domainPredicate = predicate == null ? null : Map<Expression<Func<T, bool>>>(predicate);` should solve the problem.

**Comment by xplatsolutions** [comment]
Hmmm, predicate is not null, it's a very strange problem. Although orderby is null, I was having in mind to add the null check but I can't get there anyway.

**Comment by TylerCarlson1** [comment]
Can you give me a dump of the full exception then?

**Comment by xplatsolutions** [comment]
@TylerCarlson1 I forgot to post the inner exception here is the complete exception stacktraces and messages.

> StackTrace
> 
>    at FlightKit.Data.Client.Sync.Services.BaseLocalDataService`2.Map[TMap](Object source) in C:\APP_DATA\Verisk Repositories\ISPFLTKIT-1000-2\SyncAPIv2\FlightKit.Data.Client.Sync\Services\BaseLocalDataService.cs:line 44
>    at FlightKit.Data.Client.Sync.Services.LocalDataService`2.<GetAsync>d__5`1.MoveNext() in C:\APP_DATA\Verisk Repositories\ISPFLTKIT-1000-2\SyncAPIv2\FlightKit.Data.Client.Sync\Services\LocalDataService.cs:line 41
>    
>    Message
>    
>    
> 
> Mapping types:
> Expression`1 -> Expression`1
> System.Linq.Expressions.Expression`1[[System.Func`2[[Mobile.Application.DTO.WindEnhancedWindDataFormCommentsDTO, Mobile.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[Domain.Client.Sync.Domain.Wind_Comment, Domain.Client.Sync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
> 
> Destination path:
> Expression`1
> 
> Source value:
> p => (p.ReportId == value(FlightKit.Data.Client.Sync.Services.WindReportLocalDataService+<>c__DisplayClass46_0).dto.ReportId)
> 
> Inner Exception
> 
> StackTrace
> 
>    at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.PropertyMap(MemberExpression node)
>    at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node)
>    at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node)
>    at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>    at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitBinary(BinaryExpression node)
>    at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at AutoMapper.Mappers.ExpressionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
>    at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
>    
> Message
> 
> Object reference not set to an instance of an object.

**Comment by TylerCarlson1** [comment]
value(FlightKit.Data.Client.Sync.Services.WindReportLocalDataService+<>c__DisplayClass46_0).dto.ReportId
this is probably the problem.

You aren't passing the whole object over so it gets a null trying to get the dto value.

So you would need to redo your predicate like so
```
var reportID = class.dto.ReportID;
var predicate = p => p.ReportId == reportID;
```
instead of 
```
var predicate = p => p.ReportId == class.dto.ReportID;
```

**Comment by xplatsolutions** [comment]
It worked like a charm, I've seen this but didn't even think the cast is failing.

Thanks a lot @TylerCarlson1.

**Comment by xplatsolutions** [comment]
I guess classes consuming the dataservice will do the same thing and I will still get errors like this, do you have any suggestion working around this? @TylerCarlson1

**Comment by TylerCarlson1** [comment]
I think what you can do is if you make your classes serializable they can then be passed over with the expression and executed as such.  If somehow they are in the different namespaces between the two dlls you need to remove the full qualified name from the serialization before you de-serialize it, so that it works.  IDK exactly but you are going to have to tinker with the transfer or something like that to get it to work with classes.

**Comment by xplatsolutions** [comment]
I think the best is to expose the domain to the predicates and the consumer class will actually filter the domain directly but receive DTOs.
