### ISSUE TITLE
Incorrect Mapping Inheritance with existing destination object

### ISSUE THREAD

**Issue by christophe12sopra** [AutoMapper/AutoMapper#1276]
hello. 

I have one object BO with complex properties (others objects)
I map this BO object to another DTO object
After, I map the DTO object to the existing BO Object
I would like to retrieve the same memory reference for BO object and the properties in BO object.
BO Object has the same memory reference but the objects in BO object properties have differents references.
How can explain at Automapper use the same cluster objects ?
Exemple for my problem : 

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using AutoMapper;

namespace UIModelTest
{
    [TestClass]
    public class NestedObjectMapping
    {
        [TestMethod]
        public void TestMethod1()
        {
            IMappingExpression<Docu, DocuDTO> imi = Mapper.CreateMap<Docu, DocuDTO>()
            .ConstructUsing((ResolutionContext rc) => (new DocuDTO())).IncludeBase<Common, CommonDTO>();
            imi.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Docu());
            IMappingExpression<Coor, CoorDTO> imi2 = Mapper.CreateMap<Coor, CoorDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CoorDTO()));
            imi2.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Coor());
            IMappingExpression<Comp, CompDTO> imi3 = Mapper.CreateMap<Comp, CompDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CompDTO()));
            imi3.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Comp());
            IMappingExpression<Common, CommonDTO> imi4 = Mapper.CreateMap<Common, CommonDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CommonDTO()));
            imi4.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Common());

            Comp unComposant1 = new Comp();
            unComposant1.id = "COMP1";
            unComposant1.description = "THE comp 1";
            Comp unComposant2 = new Comp();
            unComposant2.id = "COMP2";
            unComposant2.description = "THE comp 2";
            Coor coor1 = new Coor();
            coor1.id = "COOR1";
            coor1.valCoor = 1;
            coor1.leComp = unComposant1;
            Coor coor2 = new Coor();
            coor2.id = "COOR2";
            coor2.valCoor = 2;
            coor2.leComp = unComposant2;
            Docu document = new Docu();
            document.coors = new List<Coor>();
            document.coors.Add(coor1);
            document.coors.Add(coor2);
            document.id = "DOCU";
            document.val = 9;

            DocuDTO documentDTO = Mapper.Map<Docu, DocuDTO>(document);

            // please note the reference of each Object unComposant1, unComposant2, unComposant3, coor1, coor2, document

            Mapper.Map<DocuDTO, Docu>(documentDTO, document);

            // please compare the reference of each Object unComposant1, unComposant2, unComposant3, coor1, coor2, document with old references see above

            // my problem : 
            // object documentDTO mapping in existing object document -> OK
            // but the properties of object documentDTO don't mapping in existing properties object document
            // why ?
            // What is the way to reach the goal ?
        }

    }

    public class Common
    {

    }
    
    public class Docu : Common
    {
        public String id; 
        public int val;
        public IList<Coor> coors;
    }

    public class Coor
    {
        public String id;
        public int valCoor;
        public Comp leComp;
    }

    public class Comp
    {
        public String id;
        public String description;
    }

    public class CommonDTO
    {

    }

    public class DocuDTO : CommonDTO
    {
        public String id;
        public int val;
        public IList<CoorDTO> coors;
    }

    public class CoorDTO
    {
        public String id;
        public int valCoor;
        public CompDTO leComp;
    }

    public class CompDTO
    {
        public String id;
        public String description;
    }
}

```

**Comment by lbargaoanu** [comment]
Github broke your code. Make a gist. Did you try the MyGet build?

**Comment by christophe12sopra** [comment]
I Attach my file source code
Thanks
[NestedObjectMapping.txt](https://github.com/AutoMapper/AutoMapper/files/265845/NestedObjectMapping.txt)

**Comment by lbargaoanu** [comment]
That doesn't even compile with the MyGet build. Test it with the MyGet build and if the problem remains, post the updated code.

**Comment by christophe12sopra** [comment]
sorry, it's  a testcase with NUnit. try this code with a simple main : 

using System;
using System.Collections.Generic;
using AutoMapper;

namespace UIModelTest
{
    public class NestedObjectMapping
    {
        public static void main(String[] args)
        {
            IMappingExpression<Docu, DocuDTO> imi = Mapper.CreateMap<Docu, DocuDTO>()
            .ConstructUsing((ResolutionContext rc) => (new DocuDTO())).IncludeBase<Common, CommonDTO>();
            imi.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Docu());
            IMappingExpression<Coor, CoorDTO> imi2 = Mapper.CreateMap<Coor, CoorDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CoorDTO()));
            imi2.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Coor());
            IMappingExpression<Comp, CompDTO> imi3 = Mapper.CreateMap<Comp, CompDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CompDTO()));
            imi3.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Comp());
            IMappingExpression<Common, CommonDTO> imi4 = Mapper.CreateMap<Common, CommonDTO>()
            .ConstructUsing((ResolutionContext rc) => (new CommonDTO()));
            imi4.ReverseMap();//.ConstructUsing((ResolutionContext rc) => new Common());

            Comp unComposant1 = new Comp();
            unComposant1.id = "COMP1";
            unComposant1.description = "THE comp 1";
            Comp unComposant2 = new Comp();
            unComposant2.id = "COMP2";
            unComposant2.description = "THE comp 2";
            Coor coor1 = new Coor();
            coor1.id = "COOR1";
            coor1.valCoor = 1;
            coor1.leComp = unComposant1;
            Coor coor2 = new Coor();
            coor2.id = "COOR2";
            coor2.valCoor = 2;
            coor2.leComp = unComposant2;
            Docu document = new Docu();
            document.coors = new List<Coor>();
            document.coors.Add(coor1);
            document.coors.Add(coor2);
            document.id = "DOCU";
            document.val = 9;

            DocuDTO documentDTO = Mapper.Map<Docu, DocuDTO>(document);

            // please note the reference of each Object unComposant1, unComposant2, unComposant3, coor1, coor2, document

            Mapper.Map<DocuDTO, Docu>(documentDTO, document);

            // please compare the reference of each Object unComposant1, unComposant2, unComposant3, coor1, coor2, document with old references see above

            // my problem : 
            // object documentDTO mapping in existing object document -> OK
            // but the properties of object documentDTO don't mapping in existing properties object document
            // why ?
            // What is the way to reach the goal ?
        }

    }

    public class Common
    {

    }
    
    public class Docu : Common
    {
        public String id; 
        public int val;
        public IList<Coor> coors;
    }

    public class Coor
    {
        public String id;
        public int valCoor;
        public Comp leComp;
    }

    public class Comp
    {
        public String id;
        public String description;
    }

    public class CommonDTO
    {

    }

    public class DocuDTO : CommonDTO
    {
        public String id;
        public int val;
        public IList<CoorDTO> coors;
    }

    public class CoorDTO
    {
        public String id;
        public int valCoor;
        public CompDTO leComp;
    }

    public class CompDTO
    {
        public String id;
        public String description;
    }
}

**Comment by lbargaoanu** [comment]
As I said, the code doesn't even compile with the MyGet build. Mapper.CreateMap doesn't exist anymore.

**Comment by christophe12sopra** [comment]
With automapper 4.1.1 compile

**Comment by TylerCarlson1** [comment]
UseDestinationValue should work for properties with class item.
Example: `ForMember.(d => d.leComp, opt => {opt.UseDestinationValue(); opt.MapFrom(s => s.leComp)})`

This won't work for lists though, because by default AutoMapp will clear out all the entries and re-make the objects inside of it.  You will keep the same list in memory with UseDestinationValue, but the item's won't.

**Comment by jbogard** [comment]
Also, unless you want to keep running into items like this, I wouldn't bother with reverse mapping. Or use the AutoMapper.Collections nuget package to help out.

**Comment by christophe12sopra** [comment]
Thank you for your help
