### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by Mds92** [AutoMapper/AutoMapper#1277]
I'm using `AutoMapper 4.2.1`, I've used 4.1.1.
In new version of AutoMapper, I use `ninject` to inject mapper object to classes.
```
private static void RegisterServices(IKernel kernel)
{
	kernel.Bind<IMapper>().ToMethod(context =>
	{
		var automapperConfiguration = new MapperConfiguration(cfg =>
		{
			cfg.AddProfile<WebViewModelMappings>();
		});
		return automapperConfiguration.CreateMapper(); ;
	}).InSingletonScope();
}
```
At the other hand, I wrote some extension on `AutoMapper` in previous version, In some of them I wanted to find custom mapping:
```
private static bool HasCustomMappping<TSource, TDestination>(string destinationPropertyName)
{
	//var mapper = MyDependencyResolver.Get<IMapper>();//StackOverflowException
	//TypeMap typeMap = mapper.ConfigurationProvider.FindTypeMapFor<TSource, TDestination>();
	TypeMap typeMap = Mapper.FindTypeMapFor<TSource, TDestination>();
	PropertyMap propertyMap =
		typeMap.GetPropertyMaps().FirstOrDefault(q => q.DestinationProperty != null && q.DestinationProperty.Name == destinationPropertyName);
	LambdaExpression customExpression = null;
	if (propertyMap != null) customExpression = propertyMap.CustomExpression;
	if (customExpression != null) return true;
	return false;
}
```
It worked on previous version of AutoMapper, but in 4.2.1, I get `StackOverflowException` if I use the following. because AutoMapper is not configured yet and it return to  `cfg.AddProfile<WebViewModelMappings>();` to configure AutoMapper.
```
	var mapper = MyDependencyResolver.Get<IMapper>();
	TypeMap typeMap = mapper.ConfigurationProvider.FindTypeMapFor<TSource, TDestination>();
```
and I get always `null`, if I use the following:
```TypeMap typeMap = Mapper.FindTypeMapFor<TSource, TDestination>();```
How do I write my code in this situation?

**Comment by lbargaoanu** [comment]
You don't need the mapper, you need the configuration. So try getting the configuration directly. Of course, it needs to be already initialized.

**Comment by Mds92** [comment]
Actually, My AutoMapper extensions are as the following:
```
AutoMapper.Mapper.CreateMap<AdvertisementModel, Advertisement>()
	.ForMember(m => m.StartDateTime, opt => opt.MapFrom(m => m.PersianStartDateTime))
	.ForMember(m => m.RegistrationDate, opt => opt.Ignore())
	.MyExtensionMethod()// this line
```
I want to get output of `FindTypeMapFor` in my AutoMapper extension method. `MyExtensionMethod`
So It is part of initializing.
As I mentioned, it was OK in 4.1.1 but in new version 4.2.1 I get exception.
So, How should I get  `FindTypeMapFor` in an AutoMapper extension method?

**Comment by lbargaoanu** [comment]
There is a ForAllOtherMembers method that could help.

**Comment by Mds92** [comment]
Where is `ForAllOtherMembers`? I couldn't find it.

**Comment by jbogard** [comment]
Well, it'll be out shortly, I'm pushing a 5.0.0 beta release tonight. As
soon as the build finishes, it'll be up.

On Mon, May 16, 2016 at 10:13 PM, Mohammmad Dayyan <notifications@github.com

**Comment by Mds92** [comment]
So, Can we access to mapped types in an AutoMapper extension method in new Version?

**Comment by jbogard** [comment]
No I meant the ForAllOtherMembers is coming in the next version.

On Mon, May 16, 2016 at 10:38 PM, Mohammmad Dayyan <notifications@github.com

**Comment by Mds92** [comment]
:-(
So how should I handle this situation that worked in 4.1.1.
I want to find properties with custom mapping (I mean `PropertyMap.CustomExpression`) in an AutoMapper extension method?

**Comment by jbogard** [comment]
Wait for 5.0? The beta is out now.
