### ISSUE TITLE
Mapping nested objects

### ISSUE THREAD

**Issue by ben-wallis** [AutoMapper/AutoMapper#1283]
We recently moved from the deprecated static `Mapper` class to dependency injecting `IMapper` on a project I'm currently working on and I'm wondering what the correct way to deal with mapping nested objects is. Previously we could do something like this:

```
CreateMap<Customer, CustomerDto>()
            .ForMember(dest => dest.Address, opts => opts.MapFrom(src => Mapper.Map<AddressDto>(src.Address)))
```

Which would map the `Customer` and it's child `Address` to a `CustomerDto` containing an `AddressDto`. When using a `Profile` however I'm not sure of the correct way to access the mapper to do nested mapping. I've come up with a dirty hack of setting a private property to the constructed mapper object after configuration but surely this isn't the correct way to do this. Example:

```

protected void Application_Start(object sender, EventArgs e)
{
    // .. snip .. //
    
    var fooProfile = new FooProfile();
    var autoMapperConfig = new MapperConfiguration(cfg => cfg.AddProfile(fooProfile));
    autoMapperConfig.AssertConfigurationIsValid();

    var mapper = autoMapperConfig.CreateMapper();

    fooProfile.Mapper = mapper;

    _container.Register(Component
        .For<IMapper>()
        .Instance(mapper)
        .LifeStyle.Singleton);
        
    // .. snip .. //
}
    
public class FooProfile : Profile
{
    public IMapper Mapper { private get; set; }

    protected override void Configure()
    {
        CreateMap<Address, AddressDto();
        CreateMap<Customer, CustomerDto>()
            .ForMember(dest => dest.Address, opts => opts.MapFrom(src => Mapper.Map<AddressDto>(src.Address)))
    }
}
```

**Comment by TylerCarlson1** [comment]
The correct way is to not have the ForMember at all.  Address is same name for source and destination and you have the map for Address to AddressDto, so you don't need the ForMember at all.  It figured it out for you AutoMappicly.

**Comment by ben-wallis** [comment]
Let's imagine it's not the same name for source and destination, how do you do it then?

**Comment by TylerCarlson1** [comment]
`.ForMember(dest => dest.DestProperty, opts => opts.MapFrom(src => src.SourceProperty));`
If you have the DestProperty type mapped to the SourceProperty type it will call the Map for you

**Comment by jbogard** [comment]
You can also use the ResolveUsing with the context's mapper instance
