### ISSUE TITLE
Duplicitous Use of Variable "source"

### ISSUE THREAD

**Issue by jasel-lewis** [AutoMapper/AutoMapper#1287]
The Wiki page for the [Custom Value Resolvers](https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers) has, possibly, a typo.  In the `IValueResolver` interface example, the variable `source` is used twice (first for type `TSource` and second for type `ResolutionResult`.

**Comment by lbargaoanu** [comment]
You can fix it yourself :)

**Comment by jbogard** [comment]
Fixed.
