### ISSUE TITLE
5.0 Beta1 will swallow exceptions

### ISSUE THREAD

**Issue by alexandru-calinoiu** [AutoMapper/AutoMapper#1293]
I have the following mapper configuration

```
mapping.ForMember(model => model.Type, e => e.ResolveUsing(dto => GetPropertyType(dto)));
```

And the implementation of `GetPropertyType` throws an InvalidArgumentException sometimes:

```
        private static PropertyAmenityTypeEnum GetPropertyType(PropertyAmenityDto dto)
        {
            if (Enum.IsDefined(typeof (PropertyAmenityTypeEnum), dto.Type))
            {
                return (PropertyAmenityTypeEnum) dto.Type;
            }

            throw new InvalidArgumentException("Invalid amenity type");
        }
```

I have a test that checks that the mapper is throwing a `AutoMapperMappingException` on o invalid type that is passing in v4 and failing on the latest beta release.

**Comment by lbargaoanu** [comment]
That's by design.

**Comment by lbargaoanu** [comment]
I guess it shouldn't catch _all_ exceptions...

**Comment by alexandru-calinoiu** [comment]
One will say that catching all exceptions is a code smell

**Comment by lbargaoanu** [comment]
@jbogard is to blame here :)

**Comment by jbogard** [comment]
Hm, I think the historical reason was it was how the flattening worked. But
I'm ok removing it, or at least just catching NRE. Though
swallowing nothing would be better.

**Comment by lbargaoanu** [comment]
Catching nothing is clearly better if you ask me. We'll just have to see how people react :)
