### ISSUE TITLE
lazy load entity

### ISSUE THREAD

**Issue by drake69** [AutoMapper/AutoMapper#1296]
I've a class BusinessPartner with a property as Country the country has thousands of city as child collection, I create a map

```
cfg.CreateMap<BusinessPartnernViewModel,BusinessPartner>()
.ForMember(d=>d.Country, s=>s.ResolveUsing<ResolveEntity<Country>>().MapFrom(x =>x.Country);
```

ResolveEntity use an NHibernate session to Load the entity. The entity is loaded as proxy but  when mapping seems AutoMapper load all entity impacting on performance,it takes 29 sec because of the thousand cities.
There is any way to leave the Country child as a proxy instead of eager loading it ?
many thanks

**Comment by jbogard** [comment]
Can you post your types?

**Comment by drake69** [comment]
Thank you for you response:
This the entity:

```
public class BusinessPartnerIdentification
    {
        public virtual long BaseId { get; set; }
        public virtual bool RequireValidation { get; set; }
        public virtual IdentificationDocumentType IdentificationDocumentType { get; set; }
        public virtual Country CountryOfIssue { get; set; }
        public virtual BusinessPartnerBase BusinessPartner { get; set; }
    }
```

   ```
 public class Country
    {
        public virtual string PostCodeRegex { get; set; }
        public virtual string PostCodeFormat { get; set; }
        public virtual string PhonePrefix { get; set; }
        public virtual SystemOfMeasure SystemOfMeasure { get; set; }
        public virtual AmountUOM AmountUOM { get; set; }
        private IList<CountryRegionLevelOne> _regionsLevelOne = new List<CountryRegionLevelOne>();
        public virtual IList<CountryRegionLevelOne> RegionsLevelOne
        {
            get { return _regionsLevelOne; }
            set { _regionsLevelOne = value; }
        }
        private IList<TaxRegion> _taxRegions = new List<TaxRegion>();
        public virtual IList<TaxRegion> TaxRegions
        {
            get { return _taxRegions; }
            set { _taxRegions = value; }
        }
        public virtual Continent Continent { get; set; }
        private IList<Culture> _cultures = new List<Culture>();
        public virtual IList<Culture> Cultures
        {
            get { return _cultures; }
            set { _cultures = value; }
        }
        private IList<City> _cities;
        public virtual IList<City> Cities
        {
            get { return _cities; }
            set { _cities = value; }
        }
         private IList<CountryRegionDefinition> _pCountryRegionDefinitions = new List<CountryRegionDefinition>();
        public virtual IList<CountryRegionDefinition> CountryRegionDefinitions
        {
            get { return _pCountryRegionDefinitions; }
            set { _pCountryRegionDefinitions = value; }
        }
        private IList<VehicleRegistrationNumberTemplate> _pVehicleRegistrationNumberTemplates = new       List<VehicleRegistrationNumberTemplate>();
        public virtual IList<VehicleRegistrationNumberTemplate> VehicleRegistrationNumberTemplates
        {
            get { return _pVehicleRegistrationNumberTemplates; }
            set { _pVehicleRegistrationNumberTemplates = value; }
        }
        private IList<Language> _pLanguage = new List<Language>();
        public virtual IList<Language> Languages
        {
            get { return _pLanguage; }
            set { _pLanguage = value; }
        }
    }
```

The used Map configuration

 ```
   public class BusinessPartnerIdentificationAutomapperB2F : Profile
    {
        [Obsolete]
        protected override void Configure()
        {
            CreateMap<BusinessPartnerIdentificationVM, BusinessPartnerIdentification>()
                .ForMember(dest => dest.IdentificationDocumentType, source => source.ResolveUsing<ResolveEntityFromId<IdentificationDocumentType>, long?>(s => s.DocumentType))
                .ForMember(dest => dest.CountryOfIssue, source => source.ResolveUsing<ResolveEntityFromId<Country>, long?>(s => s.CountryOfIssue))
                .ForMember(dest => dest.BusinessPartner, source => source.ResolveUsing<ResolveEntityFromId<BusinessPartnerBase>, long?>(s => s.BusinessPartner))
                .ForMember(dest => dest.Compliant, source => source.Ignore())
                .ForMember(dest => dest.RequireValidation, source => source.MapFrom(s => s.RequireValidation));
}
}
```
The view model
   ```
 public class BusinessPartnerIdentificationVM
    {
        [Required]
        public long? CountryOfIssue { get; set; }
        [Required]
        public long? DocumentType { get; set; }
        public long? BusinessPartner { get; set; }
        public bool Compliant { get; set; }
        public bool RequireValidation { get; set; }
    }

```

The resolver :

```
   public class ResolveEntityFromId<T> : IValueResolver<long?, T> /*where T : IDataObject*/
    {
        private readonly Session _session;


        public ResolveEntityFromId(Session session)
        {
            _session = session;
        }

        public T Resolve(long? id, ResolutionContext context)
        {
            T entity = _session.Get<T>(id ?? 0);
            //T entity = _session.Query<T>().Cacheable().CacheRegion("Short").CacheMode(CacheMode.Normal).Get<>( localId).ToList().FirstOrDefault();
            return entity;
        }
    }
```

Doing This take 30 seconds

`                BusinessPartnerIdentification businessPartnerIdentification = _mapper.Map<BusinessPartnerIdentificationVM, BusinessPartnerIdentification>(businessPartnerIdentificationVM);
`

Using this Map config:
 ```
   public class BusinessPartnerIdentificationAutomapperB2F : Profile
    {
        [Obsolete]
        protected override void Configure()
        {
            CreateMap<BusinessPartnerIdentificationVM, BusinessPartnerIdentification>()
                .ForMember(dest => dest.IdentificationDocumentType, source => source.ResolveUsing<ResolveEntityFromId<IdentificationDocumentType>, long?>(s => s.DocumentType))
                .ForMember(dest => dest.CountryOfIssue, source => source.Ignore()
                .ForMember(dest => dest.BusinessPartner, source => source.ResolveUsing<ResolveEntityFromId<BusinessPartnerBase>, long?>(s => s.BusinessPartner))
                .ForMember(dest => dest.Compliant, source => source.Ignore())
                .ForMember(dest => dest.RequireValidation, source => source.MapFrom(s => s.RequireValidation));
}
}
```

and doing this take less than 1 second

`                BusinessPartnerIdentification businessPartnerIdentification = _mapper.Map<BusinessPartnerIdentificationVM, BusinessPartnerIdentification>(businessPartnerIdentificationVM);
businessPartnerIdentification.CountryOfIssue = _session.Get<Country>(BusinessPartnerIdentificationVM.CountryOfIssue);
`

In the first case the Country child entity is loaded entirely, in the latter case is loaded as a proxy.

Thanks

Luigi

**Comment by jbogard** [comment]
Where is the lazy loading happening? Inside the resolver or afterwards?

**Comment by drake69** [comment]
Inside the resolver the entity is loaded lazy afterwards is loaded eagerly.

**Comment by jbogard** [comment]
Hm. Would it be possible to try the 5.0 beta?

**Comment by drake69** [comment]
I'm using this, because of this problem,hoping to pass to the 5 beta would improve, but nothing changed.

**Comment by TylerCarlson1** [comment]
I have a question.  Is see you are using `_session` in the resolver but also outside of the resolver.  Are you sure that both sessions are the same, or if not use the same settings configurations?  Like the session that goes into the resolver doesn't have lazy loading on, because I'm not sure how you actually set it in code, while the session you get outside has lazy loading on?

The other option could be they are both lazy loaded but since they are of different sessions they don't meld well and that's causing the full loading.

Note: I'm not familiar with NHIbernate, but EF can have 2 or more open connections can have problems when you mix and match elements from each of them.

**Comment by drake69** [comment]
No, in NHibernate the session is not thread safe,u must have only one session active, in my case I implemented IOC with NInject and I have only one session per request.

**Comment by TylerCarlson1** [comment]
Looking at code in the latest code base, and how you set it up it looks like it's calling `resolutionContext.Options.CreateInstance<ResolveEntityFromId<IdentificationDocumentType>>()`
which calls ObjectCreator.CreateObject by default.  If you didn't overwrite the serviceCtor in Mapping operations it's going to make a new session for all mappings using that resolver.  And I know that resolver knows nothing of your session object.

There's an option for serviceCtor in map as a second optional variable.  You can put it in there to define your resolvers constructor to use your session.

**Comment by drake69** [comment]
I think I've done what u say for all the Profile doing what follows:
`
            IEnumerable<Profile> profiles =
            from t in typeof(AutoMapperHelperInjecter).Assembly.GetTypes()
            where typeof(Profile).IsAssignableFrom(t)
            select (Profile)Activator.CreateInstance(t);

            MapperConfiguration injectedConfig = new MapperConfiguration(cfg =>
            {
                //YOU NEED IT, otherwise all resolver aren'tank able to catch the session and complaint about default constructor
                cfg.ConstructServicesUsing(t => Kernel.Get(t));
                foreach (Profile profile in profiles)
                {
                    cfg.AddProfile(profile);
                }
            });
`

Injected in the Ninject way the default constructor using the Ninject get of binded implementation, I did something wrong ?
With the 4.2.1 the change default constructor wasn't working any more, but with 5.0 beta is working again.

**Comment by TylerCarlson1** [comment]
So does it still take 30 seconds with this change in 5.0 beta?

**Comment by drake69** [comment]
Yes I opened this issue when I've already tested as you see in my description.

**Comment by TylerCarlson1** [comment]
My only other option is the one session per request with Ninject isn't working with AutoMapper and is making new instances somehow.  Can test to see if one call creates multiple instances of session with breakpoint or debug message.  If that's not the problems I don't have any other ideas right now.

**Comment by lbargaoanu** [comment]
If you can make a repro using just AutoMapper and show that it accesses that property then we can solve this.

**Comment by drake69** [comment]
sorry can you clarify what you mean. To do a little project with db and mapping ?

**Comment by lbargaoanu** [comment]
A gist is enough, but without any dependency besides AutoMapper. If the gist shows that AutoMapper accesses that property when it shouldn't, we have a repro. I've tried that and failed.

**Comment by drake69** [comment]
can you share the gist done ?

**Comment by lbargaoanu** [comment]
[Here](https://gist.github.com/lbargaoanu/6c1975904cdfee891f22d193f9c01155).
