### ISSUE TITLE
ANNOUNCEMENT: default branch now master

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1299]
I've simplified the CI a bit so that it all goes through AppVeyor. That means that we can develop/PR straight off of master, instead of having master/dev branches.

All master builds go to MyGet.

Only builds with tags go to NuGet.

@lbargaoanu @TylerCarlson1

**Comment by TylerCarlson1** [comment]
**makes PR with tag for 5.0.0-beta 2**
