### ISSUE TITLE
AutoMapper 4.2.1 CreateMap is ambiguous on VB.NET

### ISSUE THREAD

**Issue by pyrostrex** [AutoMapper/AutoMapper#1301]
```
Imports AutoMapper
Imports AnotherProject.Model 

Public Class AutoMapperConfig
    Public Shared Sub Configure()
        Mapper.Initialize( _
            Sub(cfg)
                cfg.CreateMap(Of ObjectA, ObjectB)()
            End Sub
        )
    End Sub
End Class
```

Raised:

`Error 'CreateMap' is ambiguous across the inherited interfaces 'AutoMapper.IProfileExpression' and 'AutoMapper.IConfiguration'.`

Causing build to fail.

**Comment by lbargaoanu** [comment]
You need to upgrade.

**Comment by pyrostrex** [comment]
weird. I just created the solution, never used automapper before, installed using nuget.

**Comment by lbargaoanu** [comment]
You need the 5.0 beta version from NuGet or the MyGet build.

**Comment by braalewi** [comment]
I just experienced the same error but with a possible nuance. I am using VS 2015 Community Edition. I did not experience the error but my colleague using VS 2013 did once he updated his code from our SVN repo after I checked in.

**Comment by jbogard** [comment]
Repro?

**Comment by braalewi** [comment]
Repo...repository. It's SubVersion Source Control Repository. I reverted to 4.1.1 and the issue does not exist which is fine for our needs.
