### ISSUE TITLE
Automapper 5.0.0-beta-1 map structs to class

### ISSUE THREAD

**Issue by Schaeri** [AutoMapper/AutoMapper#1307]
Currently we are testing if the new automapper 5 will work with our project and found the following problem with the new version. When we have the following code:
```
public struct matrixDigiInStruct1
{
   public ushort CNCinfo;
   public ushort Reg1;
   public ushort Reg2;
}
public class DigiIn1
{
   public ushort CncInfo { get; set; }
   public ushort Reg1 { get; set; }
   public ushort Reg2 { get; set; }
}

MapperConfiguration config = new MapperConfiguration(
 cfg => cfg.CreateMap<matrixDigiInStruct1, DigiIn1>()
 .ForMember(d => d.CncInfo, x => x.MapFrom(s => s.CNCinfo)));
```
When trying to map the struct an exception occurs: System.InvalidOperationException The binary operator Equal is not defined for the types

This sample works with 4.2.1 which we are currently using. The problem is that the struct is defined in an external component which we have no influence.

Is this a bug in the new automapper or do we something wrong?
Thanks for the support.

**Comment by lbargaoanu** [comment]
This was fixed. Try the MyGet build.
