### ISSUE TITLE
Ignoring Target Properties by Attribute?

### ISSUE THREAD

**Issue by travislaynewilson** [AutoMapper/AutoMapper#1309]
I have a desire to ignore any target properties that are decorated with a specific attribute. Is this possible today?

**Comment by jbogard** [comment]
Yep, you can use the IgnoreMap attribute that's built in to AutoMapper, or there's a ShouldMapProperty func that you can use:

```
Mapper.Initialize(cfg => {
    ShouldMapProperty = pi => pi.GetCustomAttribute<MyIgnoreAttribute>() == null;
    // CreateMap etc
});
```

**Comment by travislaynewilson** [comment]
This just saved me a ton of time! Thanks so much for everything you've done!

**Comment by jbogard** [comment]
Of course, no problem!
