### ISSUE TITLE
Cannot resolve top level service constructor

### ISSUE THREAD

**Issue by usarskyy** [AutoMapper/AutoMapper#1310]
Currently I can create a mapper transparently to application's code using, for example, one of the popular DI containers. During the mapper creation I can inject there some service through "serviceCtor" argument in "CreateMapper" method. So far, so good :)
My problem is that there is no possibility to access this service constructor in mapping options when you call Map<Source,Destination>(...) method. As a result, top level service constructor gets lost.

Here is a simple test that illustrates this issue:
```
[TestFixture]
  public class ServiceCtorTests
  {
    [Test]
    public void Test()
    {
      var cfg = new MapperConfiguration(x =>
      {
        x.CreateMap<ChildSource, ChildDestination>()
         .ConstructUsing(ctx =>
         {
           var source = (ChildSource)ctx.SourceValue;
           var rootService = (RootService) ctx.Options.ServiceCtor(typeof(RootService));
           var childService = (ChildService) ctx.Options.ServiceCtor(typeof(ChildService));

           if (rootService == null)
           {
             throw new Exception("RootService is missing");
           }

           if (childService == null)
           {
             throw new Exception("ChildService is missing");
           }

           return new ChildDestination {X = rootService.Calc(source.X, childService.Random())};
         })
         .ForAllMembers(m => m.Ignore());

        x.CreateMap<Source, Destination>()
         .ConstructUsing(context =>
         {
           var source = (Source) context.SourceValue;
           var child = context.Engine.Mapper.Map<ChildSource, ChildDestination>(source.Child,
             options =>
             {
               options.ConstructServicesUsing(type =>
               {
                 if (type == typeof(ChildService))
                 {
                   return new ChildService();
                 }

                 return context.Options.ServiceCtor(type);
               });
             });

           return new Destination {Child = child};
         })
         .ForAllMembers(a => a.Ignore());
      });

      // this is called somewhere in DI
      var mapper = cfg.CreateMapper(_topServiceCtor);

      // then, for example, mapper gets injected into my service by DI and I call mapper.Map<>() method
      var result = mapper.Map<Source, Destination>(new Source
      {
        Child = new ChildSource
        {
          X = 11
        }
      },
        options =>
        {
          // !!! PROBLEM !!!
          // HERE I should be able to pass _topServiceCtor further -> currently it is not possible
          options.Items["__TMP__"] = 123;
        });

      Assert.AreEqual(16, result.Child.X);
    }
    

    private static readonly Func<Type, object> _topServiceCtor = type =>
    {
      if (type == typeof(RootService))
      {
        return new RootService();
      }

      return null;
    };
  }

  class ChildService
  {
    public int Random()
    {
      // guaranted to be random
      return 5;
    }
  }

  class RootService
  {
    public int Calc(int x, int y)
    {
      return x + y;
    }
  }

  class Source
  {
    public ChildSource Child { get; set; }
  }

  class ChildSource
  {
    public int X { get; set; }
  }

  class Destination
  {
    public ChildDestination Child { get; set; }
  }

  class ChildDestination
  {
    public int X { get; set; }
  }
```

**Comment by usarskyy** [comment]
Affected version: 4.2.1

**Comment by jbogard** [comment]
OK I'm really confused here. You're calling ConstructServicesUsing in multiple places in multiple scopes. If you're using child containers, you should just be new'ing up a Mapper with the right constructor from the child container.

**Comment by usarskyy** [comment]
I cannot create new Mapper because only top level code (for example, DI) knows how to instantiate a mapper from mapper configuration.
In each new child scope I can only resolve (local) objects visible to this child scope and, if requested type is not one of these local objects, call parent service constructor.

I agree that my example might not be very clear because of the type names. But the problem is simple: you loose service constructor that is provided when mapper is created.

**Comment by usarskyy** [comment]
> If you're using child containers, you should just be new'ing up a Mapper with the right constructor from the child container.

BTW, this will work only in "ConstructUsing(...)" but not when you call Mapper.Map<>() because there mapping options do not contain "ServiceCtor" property (i.e., service constructor passed when mapper was created)

**Comment by jbogard** [comment]
Oh, yes you're right. There is no concept in AutoMapper of a preserved hierarchy of service constructors. You'd have to do that yourself inside your mapping options, modifying your Func to do the local check, then defer to the contextual DI, captured in a closure. The service ctor is global to the entire mapping operation (though you could get to the IMapper.ServiceCtor if you like).

**Comment by usarskyy** [comment]
I am completely fine with the fact that I have to maintain service ctor chain by myself :) I am just complaining that there is no way how I can chain calls to the very first service ctor. And "mapper.ConfigurationProvider.ServiceCtor" is something different, it does not point to "_topServiceCtor".

**Comment by jbogard** [comment]
No, but it doesn't look like you've set it. I would expect to see a "ConstructServicesUsing" inside your top-level MapperConfiguration ctor.

**Comment by usarskyy** [comment]
OK, lets add it:

```
var result = mapper.Map<Source, Destination>(new Source
      {
        Child = new ChildSource
        {
          X = 11
        }
      },
        options =>
        {

          options.ConstructServicesUsing(type =>
          {
            // ???
          });
          // !!! PROBLEM !!!
          // HERE I should be able to pass _topServiceCtor further
          options.Items["__TMP__"] = 123;
        });
```
What shall I write instead of "???" to return "RootService" that is resolved by "_topServiceCtor"?

**Comment by jbogard** [comment]
No I meant in your global mapper configuration. That will populate the
configurations' service ctor property.

**Comment by usarskyy** [comment]
OK, now I understand what you mean! :) And I must say that this is absolutely not obvious. Personally, I don't get how service ctor provided in CreateMapper(...) method call is different from one that is specified by calling ConstructServiceUsing(...) method.

Also, with ConstructServiceUsing(...) method approach is not possible to use DI container because the container does not exist on the moment when you create mapper configuration. You could, of course, create mapper configuration every time when IMapper instance is resolved but this is too expensive.


Here is updated code with highlighted changes:
```
[Test]
    public void Test()
    {
      var cfg = new MapperConfiguration(x =>
      {
        **x.ConstructServicesUsing(_topServiceCtor);**
        x.CreateMap<ChildSource, ChildDestination>()
         .ConstructUsing(ctx =>
         {
           var source = (ChildSource)ctx.SourceValue;
           var rootService = (RootService) ctx.Options.ServiceCtor(typeof(RootService));
           var childService = (ChildService) ctx.Options.ServiceCtor(typeof(ChildService));

           if (rootService == null)
           {
             throw new Exception("RootService is missing");
           }

           if (childService == null)
           {
             throw new Exception("ChildService is missing");
           }

           return new ChildDestination {X = rootService.Calc(source.X, childService.Random())};
         })
         .ForAllMembers(m => m.Ignore());

        x.CreateMap<Source, Destination>()
         .ConstructUsing(context =>
         {
           var source = (Source) context.SourceValue;
           var child = context.Engine.Mapper.Map<ChildSource, ChildDestination>(source.Child,
             options =>
             {
               options.ConstructServicesUsing(type =>
               {
                 if (type == typeof(ChildService))
                 {
                   return new ChildService();
                 }

                 return context.Options.ServiceCtor(type);
               });
             });

           return new Destination {Child = child};
         })
         .ForAllMembers(a => a.Ignore());
      });

      **var mapper = cfg.CreateMapper();**
      var result = mapper.Map<Source, Destination>(new Source
      {
        Child = new ChildSource
        {
          X = 11
        }
      },
        options =>
        {

          **options.ConstructServicesUsing(type => mapper.ConfigurationProvider.ServiceCtor(type));**
          // !!! PROBLEM !!!
          // HERE I should be able to pass _topServiceCtor further
          options.Items["__TMP__"] = 123;
        });

      Assert.AreEqual(16, result.Child.X);
    }
```

**Comment by jbogard** [comment]
No it's not obvious because no one has ever asked for a cascading fallback.
Usually people just use a DI container that supports child containers and
it handles all of this for you.

Your asterisk thing should work, as it's a closure and if you set that
variable after it will pick it up.

**Comment by usarskyy** [comment]
> No it's not obvious because no one has ever asked for a cascading fallback.

Once more, I don't ask for cascading fallback. I can manage it by myself. The problem is that I don't have access to service ctor that is provided as an argument in **cfg.CreateMapper(serviceCtor)**

> Usually people just use a DI container that supports child containers and
> it handles all of this for you.

How would child container help me here? I need to resolve a service before DI container is built. Obviously, in order to build the container I need to register Mapper but I cannot build Mapper configuration because service cannot not resolved (because DI container does not exist, because ...).
In case of Autofac DI, for example, I can solve this problem by registering a callback **BUT** in this callback I have to build mapper configuration first that is very expensive. 
Better approach is to build mapper configuration first and provide service ctor when you create a mapper (i.e., by calling cfg.CreateMapper(serviceCtor)).

> Your asterisk thing should work, as it's a closure and if you set that
> variable after it will pick it up.

Sorry, I didn't get it. Asterisks supposed to be a "highlight" of what has changed from original version.

**Comment by usarskyy** [comment]
Here is a simple Autofac code that would work fine if I could access top level service ctor:
```
      var builder = new ContainerBuilder();
      var mapperCfg = AutoMapperInitializer.Init();
      builder.Register(x =>
      {
        var context = x.Resolve<IComponentContext>();

        return mapperCfg.CreateMapper(t => context.ResolveOptional(t));
      })
             .As<IMapper>()
             .InstancePerLifetimeScope();

      var container = builder.Build();
```

As you can see, mapper configuration happens _before_ container is built. In order to make it working I need to change it like this:

```
      var builder = new ContainerBuilder();

      builder.Register(x =>
      {
        var context = x.Resolve<IComponentContext>();
        var mapperCfg = AutoMapperInitializer.Init(t => context.ResolveOptional(t));

        return mapperCfg.CreateMapper();
      })
             .As<IMapper>()
             .InstancePerLifetimeScope();

      var container = builder.Build();
```
But this is not wise because it will significantly impact performance.

**Comment by jbogard** [comment]
OK so I don't know AutoFac, here's how it would be accomplished with StructureMap:

```
var container = new Container(cfg =>
{
    cfg.ForSingletonOf<MapperConfiguration>()
        .Use("Mapper Initialization", ctx =>
        {
            var mapperConfig = new MapperConfiguration(x =>
            {
                x.CreateMap<ChildSource, ChildDestination>()
                    .ConstructUsing((source, res) =>
                    {
                        var rootService = (RootService) res.Options.ServiceCtor(typeof (RootService));
                        var childService = (ChildService) res.Options.ServiceCtor(typeof (ChildService));

                        return new ChildDestination {X = rootService.Calc(source.X, childService.Random())};
                    })
                    .ForAllMembers(m => m.Ignore());

                x.CreateMap<Source, Destination>();
            });

            return mapperConfig;
        });

    cfg.For<RootService>().Use<RootService>();
    cfg.For<ChildService>().Use(new ChildService(5));

    cfg.For<IMapper>().Use(ctx => new Mapper(ctx.GetInstance<MapperConfiguration>(), ctx.GetInstance));
});

var mapper = container.GetInstance<IMapper>();

var value = new Source {Child = new ChildSource {X = 5}};

var result = mapper.Map<Source, Destination>(value);

Console.WriteLine(result.Child.X);

var child = container.CreateChildContainer();

child.Configure(cfg =>
{
    cfg.For<ChildService>().Use(new ChildService(10));
});

mapper = child.GetInstance<IMapper>();

result = mapper.Map<Source, Destination>(value);

Console.WriteLine(result.Child.X);
```

This prints 10 then 15. It's accomplished because StructureMap lets you construct with a func that passes in a context. That context is not a static context, but the context of whatever is requesting the service. So it's the parent container, or the child container. I configure the IMapper instance to also come from the container, with a key difference - I pass in the `Func<Type, object>` into its constructor, so that every time I construct an IMapper, I get the correct context passed in. I can't use the MapperConfiguration, since that one is static.

The beauty of this approach is that I can create as many child containers as I want, and I don't need to any service overrides in the mapper options, I rely on my container hierarchy and configuration to supply correct instances.

**Comment by usarskyy** [comment]
It works for you because you wrote:

`result = mapper.Map<Source, Destination>(value);`

To reproduce the issue you have to provide mapping options as a second argument.

Autofac also have child containers but that's not important because I don't want to swap service instance.

**Comment by jbogard** [comment]
Exactly - I intentionally left that out because with child containers you don't need it. I don't want to have manual configuration of individual types inside of a Map call.

Using the "Options" to swap out the service constructor is only intended if you're using the static instance.

Otherwise, the preferred mode is to supply the correct service constructor to the Mapper object itself, in its constructor, as that is most easily accomplished from container configuration as I showed above. It's exactly what child containers are intended for in DI containers - take the base configuration, and modify it slightly for a specific profile/purpose.

**Comment by usarskyy** [comment]
`Exactly - I intentionally left that out because with child containers you don't need it. I don't want to have manual configuration of individual types inside of a Map call.`

In my case that's the only possible place where I can inject instance of the type that is required by other mapper down in hierarchy. So, unfortunately I cannot leave it out.

I am using AutoMapper in web application and DI container is used to build dependency resolver like this:

`config.DependencyResolver = new AutofacWebApiDependencyResolver(builder.Build());`

This call is made once when application starts and never repeated. Obviously, I cannot create any child containers.
Also, Autofac has a different resolution mechanism that is bound to http request in web application which makes it impossible to register singleton like you made it with "cfg.ForSingletonOf".

BTW, your example does not work if I try to resolve unique RootService for every call:

```
[Test]
    public void Test2()
    {
      var container = new Container(cfg =>
      {
        cfg.ForSingletonOf<MapperConfiguration>()
            .Use("Mapper Initialization", ctx =>
            {
              Console.WriteLine("Create mapping config");

              var mapperConfig = new MapperConfiguration(x =>
              {
                x.ConstructServicesUsing(ctx.GetInstance);

                x.CreateMap<Source, Destination>()
                 .ForMember(w => w.Child, f => f.MapFrom(o => o.Child));

                x.CreateMap<ChildSource, ChildDestination>()
                 .ConstructUsing(res =>
                 {
                   var source = (ChildSource) res.SourceValue;
                   var rootService = (RootService) res.Options.ServiceCtor(typeof(RootService));
                   var childService = (ChildService) res.Options.ServiceCtor(typeof(ChildService));

                   return new ChildDestination {X = rootService.Calc(source.X, childService.Random())};
                 })
                 .ForAllMembers(m => m.Ignore());

                x.CreateMap<Source, Destination>();
              });

              return mapperConfig;
            });

        cfg.For<RootService>().AlwaysUnique().Use(new RootService(DateTime.UtcNow.Second));
        cfg.For<ChildService>().Use(new ChildService(5));

        cfg.For<IMapper>().Use(ctx => ctx.GetInstance<MapperConfiguration>().CreateMapper());
      });

      var mapper = container.GetInstance<IMapper>();

      var value = new Source { Child = new ChildSource { X = 5 } };

      var result = mapper.Map<Source, Destination>(value
        , options =>
         {
           options.ConstructServicesUsing(type => mapper.ConfigurationProvider.ServiceCtor(type));
           options.Items["wqrwr"] = 1;
         }
        );

      Console.WriteLine(result.Child.X);

      System.Threading.Thread.Sleep(2000);

      var mapper2 = container.GetInstance<IMapper>();

      var result2 = mapper2.Map<Source, Destination>(value);

      Console.WriteLine(result2.Child.X);
    }
```

It prints out:

```
Create mapping config
8
10
8
10

```

But second "8" should be actually "10"

**Comment by jbogard** [comment]
Then I don't really know how to help here, if Autofac can't do what you need and you can't use child containers. Though I use child containers with ASP.NET MVC 5 and StructureMap...

Maybe a quick summary of what you want the API to look like but doesn't work today?

**Comment by usarskyy** [comment]
Basically, I need to map business entities (i.e., API contracts) to data entities. 
Since I use NHibernate, I need to have NHibernate session in my mapper to load data entity from DB. NHibernate session can be passed as an argument to CreateMapper(...) method when mapper is resolved  by DI container. 
Then each mapper "registers" its destination object using service ctor. This allows child mappers to access any type from the above hierarchy (for example, in order to set "Parent" property of the currently mapped child object). 
There is no place for child containers in my case. Actually, my mappers do not even know that there is DI container.

Anyway, I found another way to access parent objects without need to use service ctor. Problem is kind of solved :)
