### ISSUE TITLE
Mapping same object type properties in a class invokes Equals and GetHashCode

### ISSUE THREAD

**Issue by xplatsolutions** [AutoMapper/AutoMapper#1311]
I have this class.

```
public class ConflictItem<T> where T : new()
    {
        public T CurrentItem { get; set; }
        public T RequestedUpdateItem { get; set; }
    }
```

Where T implements bool Equals(object obj), int GetHashCode() and IEquatable<SyncObject>.

So let's say you have` IEnumerable<ConflictItem<Order>>` and map to `IEnumerable<ConflictItem<OrderDataObject>>`, this will invoke Equals and GetHashCode, which I don't understand the reason.

The problem is that the mapped result object `ConflictItem<OrderDataObject>` ends up with the same object instance in both CurrentItem and RequestedUpdateItem properties.

I understand when it comes to equality of objects in a list or between two objects but why Automapper will match equality for two different properties in another object? Is there any way to override this behavior with configuration?

**Comment by jbogard** [comment]
What version? I don't think this happens in 5.0.

**Comment by xplatsolutions** [comment]
I'm using 4.2.1, I see that 5.0 is in beta.

**Comment by jbogard** [comment]
Yes, any package targeting .NET Core RC2 is forced to be marked as pre-release per NuGet package rules. Do you see this happen with 5.0?

**Comment by xplatsolutions** [comment]
Updated to the latest Nuget package version and the effect doesn't apply.
