### ISSUE TITLE
Dynamic and ExpandoObject Mapping with Renaming Properties

### ISSUE THREAD

**Issue by lurifaxel** [AutoMapper/AutoMapper#1313]
So now it's possible to map between dynamic and static objects, which is fantastic! One thing that would make it even more so is if it were possible to rename properties of objects while mapping to a dynamic object.

I tried the following (which compiles and executes but doesn't actually rename any properties):

```
Mapper.Initialize(cfg =>
{
    cfg.ReplaceMemberName("FooIdentifier", "Foo");
    cfg.ReplaceMemberName("BarIdentifier", "Bar");
});

var someClass = new SomeClass();

dynamic expando = Mapper.Map<ExpandoObject>(someClass);
```

Perhaps this can be added in a future release ? :) Either by doing what I tried or by using some other syntax that I haven't thought of.

The context for my question is that I'm building a Web API and for some routes a lot of data has to just pass through the API layer down to the API consumers. The data can be hierarchical in nature and it doesn't really matter that much for the API what the data is, so explicitly typing it can be a bit overkill. However, the data still has to conform to the API consumers' expectations, which is where the renaming of certain properties would come in _very_ handy.

Edit: I wasn't sure if I were supposed to add labels to this post, but I didn't seem to be able to. So just to be clear, this is a feature request!

**Comment by jbogard** [comment]
Pull request! It would be easy to change, the dynamic mappers don't really
look at any config.

**Comment by lbargaoanu** [comment]
PR welcome.
