### ISSUE TITLE
access destination object with forAllMembers

### ISSUE THREAD

**Issue by christophe12sopra** [AutoMapper/AutoMapper#1316]
Hello.

I would like to have a conditional mapping with my  existing destination object.
I work with 4.1.1 Automapper

Exemple : 
```
class Sample {
int val1
string val2
}

class SampleDTO {
int val1
string val2
bool lock
}

IMappingExpression<Sample, SampleDTO> im = Mapper.CreateMap<Sample, SampleDTO>() ;
im.ForAllMembers(opt => opt.Condition(rc =>
            { return true ; })) ;
```
instead of "return true", I would like to put `return dest.lock != true ;`

How I can access to destination object ?

Thank in advance for your help.

Regards

Christophe

**Comment by christophe12sopra** [comment]
an other way for me has to cancel the mapping in before maps according to the condition lock == true ;

How cancel the entire mapping in before maps ?

Thanks

**Comment by jbogard** [comment]
Honestly this sounds like a feature request, but you're mapping to an existing object, right? It would only make sense to cancel a mapping if you were doing:

```
Mapper.Map(src, dest);
```
versus
```
var dest = Mapper.Map<Sample, SampleDTO>(src);
```
I'm not sure what "cancelling" would do for the second one.

**Comment by jbogard** [comment]
So I would add that this works for me just fine in the 5.0 beta:

```
cfg.CreateMap<Source, Destination>()
    .ForAllMembers(opt => opt.Condition((src, dest) => dest.lock != true));
```

I added a number of overloads for the condition, as well as made them strongly typed so you get access to the destination object.

**Comment by christophe12sopra** [comment]
unfortunaltely, I use automapper 4.1.1. I will update version later. But I have a workaround for my application.

In addition, In a future version of Automapper, I would like to use a cancel mapping in before maps instead of use forAllMember for cancel each mapping, My suggestion is for increase the automapper performance because ForAllMember is call for each property mapping.

Thank you for your help.

**Comment by christophe12sopra** [comment]
in addition your exemple can cause problem if
lock are true value in source object and false value in target object : the mapping is not complete.

**Comment by jbogard** [comment]
Yeah, that makes sense, I like the idea of a condition applied at the map level.

My question for you is, what should the behavior be? Are you mapping to an existing object today? Which of the two examples I showed are you using?
