### ISSUE TITLE
Custom converter documentation incorrect

### ISSUE THREAD

**Issue by nickcoad** [AutoMapper/AutoMapper#1318]
The interface for ITypeConverter<Source, Destination> shown in the custom converter documentation doesn't match the actual interface in the current version of AutoMapper available on Nuget.

The strange thing is it _does_ seem to match the interface in the src available here on Github. What's going on?

**Comment by lbargaoanu** [comment]
The latest build is the MyGet build.

**Comment by jbogard** [comment]
The current version being 5.0 beta? Pretty sure it matches that one.

**Comment by jbogard** [comment]
Yep, it matches 5.0.

**Comment by nickcoad** [comment]
I would argue that being marked as pre-release, you can't expect that many developers would be using that yet in a production environment. Is there somewhere that the current _stable_ version on Nuget is documented?

**Comment by nickcoad** [comment]
Also worth mentioning that the project home page instructs users to use "Install-Package AutoMapper" which will _not_ install the beta, so you can see why the documentation would be confusing (especially since it's not versioned).

**Comment by jbogard** [comment]
I'm open for ideas. My main goal is that any NuGet release is documented.
That and all NuGet releases are stable, to be deployed to production.

**Comment by nickcoad** [comment]
No problem - I guess what I'm saying is that while it's in pre-release (as it is now), it won't be the one that gets installed when someone runs your recommended install command. I wonder if a note one the documentation that just mentions that it is relevant to 5.0.0 or higher would do the trick?

I'm not trying to be difficult sorry, I can see where I got confused is all and I can see other people potentially having some confusion around it as well.
