### ISSUE TITLE
Error mapping enumerations on Xamarin iOS

### ISSUE THREAD

**Issue by ataparia** [AutoMapper/AutoMapper#1325]
I am getting an error while mapping a class having a enumeration property on Xamarin iOS only. It works perfectly on Android and Windows. I am using AutoMapper.4.1.1 version. I have tried using both the dlls located under Xamarin.iOS10 and MonoTouch directories.

Here is the error that I am seeing on the debugger.

Mapping types:
WorkMode -> WorkMode
Infor.Mobile.Core.Application.Preferences.WorkMode -> Infor.Mobile.Core.Application.Preferences.WorkMode

Destination path:
UserPreferences.WorkMode.WorkMode

Source value:
Online
-------------------------------------------------------------------------------------------------------------------------------

WorkMode is a enumeration having two values
a) Online 
b) Offline

**Comment by jbogard** [comment]
What about the 5.0 release?

**Comment by ataparia** [comment]
Havent tried that out.

**Comment by ataparia** [comment]
Sorry for the confusion. I just noticed that it works with 4.1.1. The issue I was having was I had a touch library project and touch startup project. I was referencing different versions of the automapper in those two projects. Once i had the same version in both projects, it started working for me. Closing this now.
