### ISSUE TITLE
Mapper and MapperConfiguration with default constructor (4.2)

### ISSUE THREAD

**Issue by generik0** [AutoMapper/AutoMapper#1326]
The "Profile" is good but i don't see why one should always have to  "new MapperConfiguration" because there is no default constructor.

You See, for structuremap and/or Castle (maybe any IoC) it would be easiest if one could just register IMapper to implement Mapper and MapperConfiguration to implement IMapperConfiguration (IConfigurationProvider in V5 i beleive?)

The create map can be done i a helper method, maybe even using some open/close princinple to create all classes that have a mapping class.
The the lifestyle will manage the correct injection for the mapper and configuration classes and there helper classes.

This would make TDD and IoC with Automapper much more powerful, and remove the need for this "painfull on the eyes" "new" or static Mapper.Initialize method?

Isn't it possible to create default constructor for MapperConfigurator, and configure the classes post construct?
Then the MapperConfurator can also be called a "factory" for IMapper/Mapper, and hence will fit with testing.

**Comment by jbogard** [comment]
The MyGet feed has a thing you can new up with config by itself. Not sure
how this helps with testing though, you'd never mock MapperConfiguration
and with IMapper it's easy to mock. Maybe you can show me a test that has
it the way you'd like it to work?

**Comment by generik0** [comment]
Hi Jimmy Thanks for your response. It is very appreciated I have been using automapper for a couple of years and enjoy it a lot. I was always a little sad about it being a static implementation, but v4 has fixed this. Now i am just looking for the final notch.

The mocking actually isn't the main thing with what i am trying to acheive. I try to develop using SOLID principles. And especially the "D" I.e. Dependency inversion principle (whereby constructor injection is very good for testing and mocking, hereby the link).
I do not find Automapper to be out of the box IoC freindly. Why, because of this:
"new MapperConfiguration(". IoC nothing should have to be newed. The IoC container / framework should new. A default constructor, or a constructor with objects that can be registered and injected are the go...

I am forced to have a wrapper, or make a resolver for the MapperConfiguration, which is a real pitty!
I could ofcause also have a empty configuration on initialization and "AddMemberConfiguration" later, but it really isn't clean.

So far in V4.2 i have made an Wrapper for MapperConfigurationWrapper (see attachement)
![2016-06-13_19-45-55](https://cloud.githubusercontent.com/assets/2411563/16017312/8a5b1be6-319f-11e6-947b-00336517453b.jpg)

Again the "new" it hearts my eyes :-)
He is the most simple Castle register/resolve. This should work, and would make all the IoC dudes out there so very happy!
![image](https://cloud.githubusercontent.com/assets/2411563/16017685/41ba6bec-31a1-11e6-9234-f34ddd82119c.png)

Castle.MicroKernel.Handlers.HandlerException : Can't create component 'AutoMapper.MapperConfiguration' as it has dependencies to be satisfied.

The default constructor and this needs to work before Automapper can truely be IoCed..
![image](https://cloud.githubusercontent.com/assets/2411563/16017726/6f5c36f2-31a1-11e6-9383-40b3a5b4c2dd.png)


Or did i missunderstand something?
I have read your https://lostechies.com/jimmybogard/2009/05/12/automapper-and-ioc/
I seams overly complicated... Is this the only option?

**Comment by jbogard** [comment]
"Nothing should be new'd" what about StringBuilder?

Anyway, today I new up AutoMapper inside my container config. That seems
adequate, and everyone only gets an IMapper instance. What does your
container config look like now?

**Comment by generik0** [comment]
Hi Again.
I don't use StringBuilder, but yes, I do use strings. And i guess they do get new'd... But we have alwyas wrapped things like datetime, timers and anything that needed to be new'd. Improving the unit testability of it. Difficult to make unit tests using e.g. date time, if yhou don't control what "Now" is..

Yes, i have read your very good post: https://lostechies.com/jimmybogard/2009/05/12/automapper-and-ioc/
And i have tried to do using castle:
![image](https://cloud.githubusercontent.com/assets/2411563/16018979/22d3afa8-31a7-11e6-8643-6831b9dd2ab6.png)
But no luck. But i do understand your comment. With structuremap it appears to be valid.
Righ now, with the wrapper, my registrationof the wrapper is just being done by the standard fluent installer:
![image](https://cloud.githubusercontent.com/assets/2411563/16019016/479f7290-31a7-11e6-8082-2ea7069eedd1.png)

And then i use some polymophism and Open/Close principle to make inject the mappings

**Comment by generik0** [comment]
Wops. The container holding the mapper instance is registered as singleton

![image](https://cloud.githubusercontent.com/assets/2411563/16019128/bd702ac8-31a7-11e6-8466-aef758ce4dbb.png)

**Comment by generik0** [comment]
..
All in all Jimmy, please don't think i am knocking automapper. It really is great. It is in my top 5 frameworks (including Dapper, Castle Windsor, Topshelf). And now that the static configuration is removed. Great.
Thanks again. I was only hoping for a little easier IoC :-)

**Comment by generik0** [comment]
Should we close this feed? I guess it it more a feature request than issue...

**Comment by jbogard** [comment]
OK so this might be made a bit easier with the NuGet pre-release. I've separated out config into a totally different object. Here's what you can do (and will be able to do in 5.0.0 release):

```
var configExpr = new MapperConfigurationExpression();
configExpr.CreateMap<Source, Dest>();

var config = new MapperConfiguration(configExpr);
var mapper = new Mapper(config);
```

About as DI as it gets, really.

**Comment by generik0** [comment]
Great! I Can definately work with that. Thanks Jimmy!!!
Can not wait to try it :-)

**Comment by jbogard** [comment]
Great! Someone else pointed this out to me to put this in, I think it's the
last little piece in the API config puzzle. Also allows you to share/reuse
config since the first object there just gathers config intent. The second
puts all the config together and the last can execute it.
