### ISSUE TITLE
ProjectTo overload with membersToExpand string[] not respecting inherited members

### ISSUE THREAD

**Issue by earloc** [AutoMapper/AutoMapper#1328]
When using the following overload of ProjectTo, the internal logic does not seem to respect members from derived Types:
ProjectTo<TDestination>(this IQueryable source, IConfigurationProvider configuration, IDictionary<string, object> parameters, params string[] membersToExpand);

e.g.:
given the following types

`public class Bar {
  public SomeOtherType BarProperty {get; set;}
}`
`public class Foo : Bar {
  public YetAnotherType FooProperty {get; set;}
}`

a call to 
`someQueryable.ProjectTo<Foo>(parameters:null, "BarProperty", "FooProperty")`

Only expands "FooProperty", as the internal ReflectionHelper doesn´t seem to search for members up the inheritance hierarchy

**Comment by lbargaoanu** [comment]
This can be closed.
