### ISSUE TITLE
IgnoreAllNonExisting() implementation in 5.0.0-beta-1

### ISSUE THREAD

**Issue by adaneam** [AutoMapper/AutoMapper#1331]
TypeMap is removed from IMappingExpression<TSource, TDestination>, hence following code is not working in latest beta.

```
        public static IMappingExpression<TSource, TDestination> IgnoreAllNonExisting<TSource, TDestination>(this IMappingExpression<TSource, TDestination> expression)
        {
            foreach (var property in expression.TypeMap.GetUnmappedPropertyNames())
            {
                expression.ForMember(property, opt => opt.Ignore());
            }

            return expression;
        }
```

How to get this working in new beta?

**Comment by lbargaoanu** [comment]
You can get the type map yourself from the configuration.

**Comment by pherbel** [comment]
Why was removed the TypeMap property from the expresssion?

No good solution to use the Mappa.Configuration, because I would like to use this for more type map.

**Comment by jbogard** [comment]
Because it doesn't exist yet.

**Comment by jbogard** [comment]
What's the point of IgnoreAllNonExisting? Why do you use it? I might find a better way to accomplish this if I understand what you're trying to do.

**Comment by pherbel** [comment]
e.g
I have DTO which come from the client side and also there is a stored entity.
I just want to map the DTO to the entity object.
XYObjectDTO -> XYObject
My entity has some properties which are auto generated (e.g created time, Id, etc.) and I don't need to map these properties because these are not exist in the DTO.
And I just want to call IgnorAllNonExisting method.

**Comment by jbogard** [comment]
And this is for configuration validation? You can also specify which side you want to validate, when you call CreateMap there's an overload that takes a MemberList to say you want to validate the destination type members (the default) or the source members.

**Comment by pherbel** [comment]
Hmm. Actually the Source side validation could work in this case.

**Comment by jbogard** [comment]
Great! That's why I added it, using Ignore like this seems hard.

**Comment by samiraguiar** [comment]
@jbogard What about adding an overload to `AssertConfigurationIsValid` to specify the member list? This way we could keep the mappings unchanged but still prevent exceptions. Also, if this overload would overwrite the `MemberList` set when mapping, it should be possible to assert using both sides.
