### ISSUE TITLE
Automapper 4.x incorrectly calls interface configuration when mapping an instance of that interface

### ISSUE THREAD

**Issue by Duracell1989** [AutoMapper/AutoMapper#1339]
I have the following classes:
```
FromParent
        public long ChildId { get; set; }
        public string ChildCode { get; set; }
        public long ParentId { get; internal set; }

ToParent
        public long ParentId { get; }
        internal virtual Child Child { get; set; }

Child : IChild
        public long Id { get; }
        public string Code { get; internal set; }

IChild
        long Id { get; }
```

And I have to following configurations:
```
AutoMapper.Mapper.CreateMap<IChild, Child>()
        .ConstructUsing(source => new Child(source.ChildId));

AutoMapper.Mapper.CreateMap<FromParent, ToParent>()
        .ConstructUsing(source=> new ToParent(source.ParentId))
        .ForMember(dest=> dest.Child, opts => opts.MapFrom(source=> MapChild(source)));

private static Child MapChild(FromParent source)
{
    return new Child(source.ChildId)
    {
        Code = source.ChildCode
    };
}
```

When I map the FromParent to the ToParent, it first calls my 'MapChild' function, it succesfully creates my Child with Id ánd Code.
But after that, AutoMapper (wrongfully) calls the ConstructUsing of my IChild->Child mapping in which I will lose my ChildCode.
The ToParent has the property 'Child' and in the configuration I also create a 'Child', thus it shouldn't call the IChild->Child mapping.

I've attached a sample test project which reproduces this problem.
[AutoMapperTest.zip](https://github.com/AutoMapper/AutoMapper/files/319951/AutoMapperTest.zip)

**Comment by lbargaoanu** [comment]
This works in 5.0. You can close the issue.
