### ISSUE TITLE
Map Automatic Property  to ExpandoObject causes many k__BackingField member

### ISSUE THREAD

**Issue by Ruikuan** [AutoMapper/AutoMapper#1342]
Hi.
I am using AutoMapper 4.2.1 in asp.net core 1.0.0 rc2 project.
I try to map object with Automatic Property to dynamic object, and serialize it to Json. This cause k__BackingField  in the Json.

My code is like this:
```csharp
class User
{
    public string UserName { get; set; }
}

User user = new User { UserName = "hello" };
dynamic d = Mapper.Map<ExpandoObject>(user);
string json = Json((ExpandoObject)d);
```
The result json like this
```json
{"UserName":"hello","<UserName>k__BackingField":"hello"}
```

If I just serialize the user object, it is OK.
```csharp
User user = new User { UserName = "hello" };
string json = Json(user);
```
result
```json
{"UserName":"hello"}
```
I try to use mapperconfiguration, but it doesn't help,even when I set false to those filter.
```csharp
User user = new User { UserName = "hello" };
Mapper.Initialize(cfg =>
{
    cfg.ShouldMapProperty = p => false;
    cfg.ShouldMapField = f => false;
});
dynamic d = Mapper.Map<ExpandoObject>(user);
string json = Json((ExpandoObject)d);
```
The result is still
```json
{"UserName":"hello","<UserName>k__BackingField":"hello"}
```
If I change the automatic property  to field, everything is well, but I think it's not  a good solution.
I don't know why the filter is not working. How should I do to remove  the k__BackingField members?
Thanks.

**Comment by Ruikuan** [comment]
After some Analysis.
I found the <UserName>k__BackingField using  reflection, only can be found with DeclaredMembers and DeclaredFields properties of TypeInfo, can't be found with GetMembers() and GetFields() methods.

It's a private field,does AutoMapper map private fields on default now?

**Comment by lbargaoanu** [comment]
It's a bug. As a workaround you can use

    Map<dynamic>(user);

**Comment by lbargaoanu** [comment]
You can also try the MyGet build.

**Comment by Ruikuan** [comment]
Thanks for reply!
Map<dynamic> may be not  help, because I do need a ExpandoObject, I need to add some additional properties to it after.
Map<dynamic> can't help, it return object is actual type User.
Finally I convert dynamic object to IDictionary, remove all the backingField keys,make  the problem solved.
