### ISSUE TITLE
ResolveUsing throws an exception if result is null

### ISSUE THREAD

**Issue by usarskyy** [AutoMapper/AutoMapper#1347]
After migration to Automapper 4.2.1 existing resolvers started throwing exceptions if result of the resolve method is null.

Exception:

> Missing type map configuration or unsupported mapping.
> 
> Mapping types:
> Object -> DealViewCounter
> System.Object -> Realty.BusinessEntities.DealViewCounter
> 
> Destination path:
> Deal.ViewCounter.ViewCounter
> 
> Source value:
> (null)

UPDATE:
BTW, if I call ResolutionResult.New(...) with type argument, it will not throw an exception. Example:
`resolutionResult.New(viewCounter, typeof(DealViewCounterDataEntity))`

**Comment by lbargaoanu** [comment]
You can try 5.0 or the MyGet build.

**Comment by usarskyy** [comment]
Unfortunately upgrade to fifth version is currently not an option for us.
I added type argument to every New(...) method call for now but it would be great if you could consider fix for this bug in 4.* branch.

**Comment by lbargaoanu** [comment]
I think your best bet is to fork and fix it yourself.

**Comment by jbogard** [comment]
Yeah, I'm not going back to the 4.x stuff. That code is dead to me.
