### ISSUE TITLE
'needs to have a constructor with 0 args or only optional args' In Version 5 beta

### ISSUE THREAD

**Issue by hrfarrokh** [AutoMapper/AutoMapper#1350]
Hi
This code works properly in version 4.2.1
BUT
Whenever i update to version 5 beta
it throws an exception and complains about a parameter-less ctor for CollectionController<,,>

```
    public class OrganizationDTO
    {
        public long? ID { get; set; }
        public string Name { get; set; }

        private CollectionDTOController<BranchDTO, short> _branchCollection;
        public CollectionDTOController<BranchDTO, short> BranchCollection
        {
            get
            {
                if (_branchCollection == null)
                    _branchCollection = new CollectionDTOController<BranchDTO, short>();

                return _branchCollection;
            }
            set { _branchCollection = value; }
        }
    }

    public class BranchDTO
    {
        public short? ID { get; set; }
        public string Name { get; set; }

    }

    public class CollectionDTOController<T, K>
       where T : class
       where K : struct
    {
        public IEnumerable<T> Models { get; set; }
        public K? SelectedID { get; set; }
    }

    public class Organization
    {
        public long? ID { get; set; }
        public string Name { get; set; }

        private CollectionController<Branch, short, EventArgs> _BranchCollection;
        public CollectionController<Branch, short, EventArgs> BranchCollection
        {
            get
            {
                if (_BranchCollection == null)
                    _BranchCollection = new CollectionController<Branch, short, EventArgs>(this);

                return _BranchCollection;
            }
            set { _BranchCollection = value; }
        }
    }

    public class Branch
    {
        public short? ID { get; set; }
        public string Name { get; set; }

    }

    public class CollectionController<T, K, Z>
        where T : class
        where K : struct
        where Z : EventArgs
    {
        private object _owner;
        public CollectionController(object owner)
        {
            _owner = owner;
        }
        public IEnumerable<T> Models { get; set; }
        public K? SelectedID { get; set; }
        public event EventHandler<Z> SelectionChanged;
    }

        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<OrganizationDTO, Organization>();
                cfg.CreateMap<BranchDTO, Branch>();
                cfg.CreateMap(typeof(CollectionDTOController<,>), typeof(CollectionController<,,>));


            });

            var branchDto = new BranchDTO { ID = 51, Name = "B1" };
            var orgDto = new OrganizationDTO { ID = 5, Name = "O1" };
            orgDto.BranchCollection.Models = new BranchDTO[] { branchDto };

            var obj = Mapper.Map<Organization>(orgDto);

            Console.ReadLine();
        }

```

CollectionController`3[Branch, Int16, EventArgs] needs to have a constructor with 0 args or only optional args Parameter name: type

**Comment by lbargaoanu** [comment]
Apparently UseDestinationValue is broken.

**Comment by hrfarrokh** [comment]
So what should i do?wait?

**Comment by lbargaoanu** [comment]
Unless you want to try a PR, yes, you should wait for a fix.

**Comment by jbogard** [comment]
Can you try the MyGet?

**Comment by jbogard** [comment]
@lbargaoanu the UseDestinationValue stuff was weird to begin with, I thought the latest MyGet made it do what it was supposed to do. Before, UseDestinationValue was always "true" which made zero sense.

**Comment by lbargaoanu** [comment]
I agree, but in this particular case it should work if you set it and it doesn't. I think it's a bug.

**Comment by jbogard** [comment]
Where is UseDestinationValue above? I didn't see it being used

**Comment by lbargaoanu** [comment]
It's not, probably because it was true by default. I've set it and expected it to work. How else would it be able to create it? I didn't debug it so maybe I'm missing something.

**Comment by jbogard** [comment]
@hrfarrokh where is the "owner" supposed to come from in the `CollectionController` class? AutoMapper needs a way to instantiate this class, and this parameter needs to come from somewhere.

**Comment by hrfarrokh** [comment]
Hi @jbogard 

1. "owner" come from the getter of the `BranchCollection` Property.
2. AutoMapper doesnt have to instantiate the `BranchCollection` Property Because it's NOT NULL, Whener AutoMapper wants to check that if  `BranchCollection` is NULL or not, The getter of the property will instantiate it (if is null).
3. In version 4.2.1 this code works properly but in 5 beta not
4. I think in the 4.2.1 version AutoMapper first check if it is null then tries to instantiate it (of course  `BranchCollection` cant be null ever), But in version 5 beta it tries to instantiate `BranchCollection` without checking if it is null

Sincerely.
