### ISSUE TITLE
project.json contains wrong json element for signed dll's

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper#1363]
The project.json file in AutoMapper contains the following buildOptions that is invalid and will not create signed dll's..
```
  "buildOptions": {
    "compilationOptions": { "keyFile": "..\\AutoMapper.snk" }
  },
```

To create the signed version or AutoMapper the buildOptions should be changed to  
```
  "buildOptions": {
    "keyFile": "..\\AutoMapper.snk"
  },
```

you also have non pre-release versions of System.* on https://www.myget.org/gallery/aspnetrelease if you wan't to prepare for the MS RTM release.

**Comment by lbargaoanu** [comment]
PR?

**Comment by Tasteful** [comment]
@lbargaoanu PR is added.

**Comment by lbargaoanu** [comment]
@jbogard does the review and merge. As soon as...
