### ISSUE TITLE
Method 'GetEnumerator' in type does not have an implementation.

### ISSUE THREAD

**Issue by tbqh511** [AutoMapper/AutoMapper#1368]
Hi,
i am program my website with EF 6 and automapper. And i have trouble with error :

`Method 'GetEnumerator' in type 'Proxy<System.Collections.Generic.IEnumerable`1[[Tbqh.Blog.BussinessEntitiesCF.PostEntity_Tbqh.Blog.BussinessEntitiesCF_Version=1.0.0.0_Culture=neutral_PublicKeyToken=null]]_mscorlib_Version=4.0.0.0_Culture=neutral_PublicKeyToken=b77a5c561934e089>' from assembly 'AutoMapper.Proxies, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' does not have an implementation.`

`var temp = Mapper.Map<IEnumerable<Post>, IEnumerable<PostEntity>>(allPostDBs);`

i'm very tired with this trouble two day age.....
Plz help me

**Comment by tbqh511** [comment]
Error code:

`Method 'GetEnumerator' in type 'Proxy<System.Collections.Generic.IEnumerable`1[[Tbqh.Blog.BussinessEntitiesCF.PostEntity_Tbqh.Blog.BussinessEntitiesCF_Version=1.0.0.0_Culture=neutral_PublicKeyToken=null]]_mscorlib_Version=4.0.0.0_Culture=neutral_PublicKeyToken=b77a5c561934e089>' from assembly 'AutoMapper.Proxies, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' does not have an implementation.`

**Comment by lbargaoanu** [comment]
Did you try 5.0 or the MyGet build?

**Comment by tbqh511** [comment]
@lbargaoanu : i use MyGet 

I had finded the cause... when i config for mapper

`Mapper.CreateMap<post,PostEntity>()`

And the error will be orrcus when i add below code

``Mapper.CreateMap<IEnumerable<Post>,IEnumerable<PostEntity>>()``

**Comment by lbargaoanu** [comment]
You don't need the second map, it's built in. If that works, you can close the issue.

**Comment by tbqh511** [comment]
Thanks
