### ISSUE TITLE
Value lost when mapping from Nullable<int> to Nullable<decimal>

### ISSUE THREAD

**Issue by jonbmul** [AutoMapper/AutoMapper#1372]
When mapping from `int?` to `decimal?`, I get NULL even when the source is not null, 
as shown in the example below. This is using Automapper 5.0-beta-1. 

`public class C1{public int? X { get; set; }}`
`public class C2{public decimal? X { get; set; }}`
....
`var config = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true);`
`var mapper = config.CreateMapper();`
`var c2 = mapper.Map<C2>(new C1 {X = 99});`
`Assert.That(c2.X == 99); // fails, because c2.X = null`

I also tried the same in Automapper 4.2.1 but that resulted in a AutoMapperMappingException.

Also, the problem only occurs when also the source property is nullable.

**Comment by lbargaoanu** [comment]
Try it with CreateMissingTypeMaps false, the default. Create the required maps and see if the behavior is the same.

**Comment by jonbmul** [comment]
I changed configuration to `new MapperConfiguration(cfg => cfg.CreateMap<C1, C2>())`.
Now I'm getting an exception:

> Missing type map configuration or unsupported mapping.
> 
> Mapping types:
> Nullable`1 -> Nullable`1
> System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Nullable`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
> 
> Destination path:
> C2.X
> 
> Source value:
> 99

Again, this only occurs when the source is nullable. I also tried with C1.X as int, and that worked fine

**Comment by lbargaoanu** [comment]
Yes, I see it too with the latest version. I guess it's a feature request, because there is no test for this case, so maybe it never worked.
