### ISSUE TITLE
MapFrom not applying Null Checking all of the way in 5.0

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#1382]
In <5.0.0, MapFrom would check for nulls all through an expression, and return null instead of throwing an exception.  The following mapping works in 4.2.1:

	CreateMap<Person, PersonDTO>()
		.ForMember(dest => dest.NameOfFirstBorn, opt => opt.MapFrom(src => src.Family.Children.FirstOrDefault().Name))
		;

If `src.Family` is null, `.FirstOrDefault()` is never called and the destination receives a null.  In 5.0.0, AssertConfigurationIsValid still succeed, but when called with a source object where Family is null, a MappingException is generated with the inner message being `ArgumentNullException` from `FirstOrDefault`.

**Comment by jbogard** [comment]
Yep, this is a bug. We removed the null checking for resolvers (from a number of requests) but looks like this one got rolled in with it.

**Comment by lbargaoanu** [comment]
@jbogard I think that's too much magic. Opt-in maybe?

**Comment by jbogard** [comment]
The idea was that MapFrom should work just like normal maps, except redirected. Normal member maps check for nulls, but we can easily wrap in a NRE check (trying to modify the expression tree would be a bit much).

**Comment by lbargaoanu** [comment]
I think people will replace ResolveUsing with MapFrom because MapFrom will catch everything :)

**Comment by jbogard** [comment]
That's OK, MapFrom still only allows expressions. ResolveUsing was meant for "I'm completely taking over responsibility". The intention was for MapFrom to be just like regular member maps, but redirected.

**Comment by jbogard** [comment]
@richardlawley btw if you're using EntityFramework in that example above, that query is going to look pretty awful. If it were me, I'd modify my parent model to actually have a FirstBorn Person property that you set.

**Comment by richardlawley** [comment]
It was a contrived example to try and illustrate the scenario - the failing unit test post upgrade which prompted this bug is not going to EF.  The more common case I use without the additional property DOES regularly go to EF:

    opt => opt.MapFrom(src => src.Children.FirstOrDefault().Name))  // NB: No ".Family."

**Comment by richardlawley** [comment]
This doesn't fix the problem.  I've modified the unit test included in the commit to demonstrate using the code from my initial post:

    public class Issue1382 : AutoMapperSpecBase
    {
        class Person
        {
            public Family Family { get; set; }
            public string Name { get; set; }
        }

        class Family
        {
            public List<Person> Children { get; set; } = new List<Person>();
        }

        class PersonDTO
        {
            public string Name { get; set; }
            public string NameOfFirstBorn { get; set; }
        }

        protected override MapperConfiguration Configuration => new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Person, PersonDTO>().ForMember(d => d.NameOfFirstBorn, o => o.MapFrom(p => p.Family.Children.FirstOrDefault().Name));
        });

        [Fact]
        public void We_should_catch_it()
        {
            Mapper.Map<PersonDTO>(new Person()).NameOfFirstBorn.ShouldBeNull();
        }
    }

I believe the problem still occurs because `FirstOrDefault()` throws `ArgumentNullException` when it is called on null, rather than `NullReferenceException` which is being caught in the code.

**Comment by lbargaoanu** [comment]
Swallowing exceptions is dangerous. And in this case even the default mapping crashes (without MapFrom). I'd rather let this be. @jbogard might disagree.
