### ISSUE TITLE
CreateMissingTypeMaps sets properties of complex objects to null

### ISSUE THREAD

**Issue by cornem** [AutoMapper/AutoMapper#1384]
I have just migrated from 4.2.0 to 5.0.0, and I ran into an issue. It appears that setting `CreateMissingTypeMaps = true` breaks custom value resolvers that return an object.

```c-sharp
class Program
{
    static void Main(string[] args)
    {
        Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<Original, Target>()
                .ForMember(t => t.Child, o => o.ResolveUsing<TargetResolver>());

            cfg.CreateMissingTypeMaps = true;
        });

        var original = new Original { Text = "Hello world from original!" };
        var mapped = Mapper.Map<Target>(original);
        // mapped.Child is not null, but its properties are
                        
        Console.ReadLine();
    }
}

public class Inner
{
    public string Content { get; set; }
}

public class Original
{
    public string Text { get; set; }
}

public class Target
{
    public string Text { get; set; }

    public Inner Child { get; set; }
}

public class TargetResolver : IValueResolver<Original, Inner>
{
    public Inner Resolve(Original source, Inner destination, ResolutionContext context)
    {
        return new Inner { Content = "Hello world from inner!" };
    }
}
```

`TargetResolver.Resolve` is actually called, but `mapped.Child.Content` will be null. If `cfg.CreateMissingTypeMaps` is not `true`, it works OK.

Is this intended? I know I shouldn't be using `CreateMissingTypeMaps` and I shouldn't need it in my codebase, but it looks to me like it should be mapping _missing_ types, not do something with types that are known.

**Comment by jbogard** [comment]
That's odd, but first, why are you using CreateMissingTypeMaps?

**Comment by cornem** [comment]
I guess somewhen we added `CreateMissingTypeMaps = true` just to be safe in case we had missed a mapping. Until we upgraded to 5.0.0, that did not lead to any problems. Now I've disabled it and added the missing mappings, which is of course better.

The example is just to demonstrate the problem.
