### ISSUE TITLE
ResolutionContext.Parent is missing!

### ISSUE THREAD

**Issue by mobius7777** [AutoMapper/AutoMapper#1390]
We have upgraded from Automapper 4.2.1 to 5.0 to get some of the bug fixes, as one of the bugs (1373 or 1372, I think) was biting us. So we have to upgrade to get this fix. Alas, there are too many changes! 

The big issue for us appears to be that the signature of ITypeConverter has radically changed and ResolutionContext is now missing Parent. 

We have a converter that converts from a DateTime to a DateTime, which does so to automatically adjust the datetime up or down for the user's TimeZone. That way, all DateTimes from the domain and converted to the user's TZ and all DateTimes originating from a non-domain ViewModel are coverted back to server time. 

Our 4.2.1 converter looked like this:

```
public class TimeZoneConverter : ITypeConverter<DateTime, DateTime>
    {
        public DateTime Convert(ResolutionContext source)
        {
            var sourceValue = (DateTime)source.SourceValue;
            string timezone = ApplicationCache.TimeZone;

            if (string.IsNullOrEmpty(timezone))
                return sourceValue;

            bool convertFrom = (source.Parent.DestinationType.Namespace.Contains("Domain") || ((source.Parent.Parent != null) && source.Parent.Parent.DestinationType.Namespace.Contains("Domain")));
            if (convertFrom)
            {
                //Convert the date from the user's time zone to the server/db time to copy back to domain
                return sourceValue.ConvertFromSpecifiedTimeZone(timezone);
            }
            else
            {
                //Convert the date to the specified timezone when returning from the domain
                return sourceValue.ConvertToSpecifiedTimeZone(timezone);
            }
        }
    }
```

I have manged to make the changes for 5.0 except for the missing Parent property. Here's what I have so far:

```
    public class TimeZoneConverter : ITypeConverter<DateTime, DateTime>
    {
        public DateTime Convert(DateTime source, ResolutionContext context)
        {
            string timezone = ApplicationCache.TimeZone;

            if (string.IsNullOrEmpty(timezone))
                return source;

            bool convertFrom = context.Parent.DestinationType.Namespace.Contains("Domain") || ((context.Parent.Parent != null) && context.Parent.Parent.DestinationType.Namespace.Contains("Domain")));
            if (convertFrom)
            {
                //Convert the date from the user's time zone to the server/db time to copy back to domain
                return source.ConvertFromSpecifiedTimeZone(timezone);
            }
            else
            {
                //Convert the date to the specified timezone when returning from the domain
                return source.ConvertToSpecifiedTimeZone(timezone);
            }
        }
    }
```

But context.Parent no longer exits. I have to be able to interrogate this to determine if the destination is in our Domain layer or not. But basically, I just need either the full namespace of the source or destination model to which the property belongs.

We also have a Nullable version of this, NullableTimeZoneConverter, which has the same issue, as well as the issue describe in issue #1389.

**Comment by jbogard** [comment]
I'm working on a post on the changes. Somethings:

IValueResolver does everything ValueResolver does. Just use it.

ITypeConverter now has everything you need. There is a bug here, though.

ResolutionContext was pared down to actual map context stuff (items, options, factory) and the minutiae of what's getting mapped is gone. It was only intended for exceptions, and now that's all captured in an exception.

If you need parent stuff, just make your actual object model track those things, and don't rely on AutoMapper to create a graph of your objects. It was insanely expensive, performance-wise, and really got abused. So I killed it with fire.

**Comment by TylerCarlson1** [comment]
Another thing that should work for this situation is make 2 profiles.  One Mapping to the domain and one mapping from the domain.  Then you can add each version of the type converter to each profile, so that each one maps the time zone correctly and you don't have to worry about checking domain type.

**Comment by mobius7777** [comment]
I'm not sure I follow. You say "ITypeConverter now has everything you need. There is a bug here." What's the bug, and how does it have everything I need if ResolutionContext no longer has what I need?

You said I can "make your actual object model track those things" but the object is just System.Datetime. I cannot make it track those things. 

Also, makign 2 profiles won't help, as the issue is determining which of the two Datatime originates from either the domain layer. I relied on ResolutionContext.Parent.DestinationType to tell me those things. 

All I need is a way to get the object's parent's Destination Type into the ITypeConverter, by whatever means.

**Comment by jbogard** [comment]
You need two type converters, not one.

**Comment by mobius7777** [comment]
Ok, let me explain more as to why I do not follow. Let's say I have 2 converters, TimeZoneToConverter and TimeZoneFromConverter. So then I create the Maps (I use Profiles)

CreateMap<System.DateTime, System.DateTime>().ConvertUsing<TimeZoneToConverter>();
CreateMap<System.DateTime, System.DateTime>().ConvertUsing<TimeZoneFromConverter>();

By how would there be any way for Automapper to know which one to use? You're idea would work if there were two different types for source and destination, but I am converting DateTime to DateTime in order to apply a Timezone shift to the destination, and the decision hinges on the destination DateTime's parent's object model.

**Comment by jbogard** [comment]
Sorry, two resolvers. Then only apply them in the correct spots.

**Comment by mobius7777** [comment]
Ok, I'll look at ValueResolver and see if that solves it.

**Comment by mobius7777** [comment]
I'm afraid I do see what you are saying now...

You are saying that we must specify the ValueResolver on each and every domainModel => viewModel and viewModel => domainModel mapping. We implemented our TimeZoneConverter "universally" so we wouldn't have to go to that trouble. Most of our mappings do not need to use any "resolveUsing" because our properties are mostly 1 to 1, and the same is true of our DateTime values. The domain model has a value of CreatedDate and the viewModel has a value of CreatedDate, so it all gets mapped "auto-magically". By injecting a DateTime to DateTime converter, they way we did originally, we were able to get away not having to specify resolvers for every DateTime on every model, in both directions, through our entire system, which has thousands of models (I do not exaggerate).

If I am understanding your suggesting, we now need to implement the TimeZone resolvers on every up and down mapping on for every model to model mapper in our entire system? I know you're thinking "well, that's how we should have done it it the first place", but that fact is, that's not how we did it because automapper allowed some cool tricks with ResolutionContext which we took full advantage of. Now this is going to take us an enormous time to implement and re-test (it is essentially a massive enterprise-scale system), and my boss (and client) is going to be absolutely furious.

I would revert back to 4.2.1, but 5.0 fixed several bugs that were biting us... And I do want to keep the application on the latest version, especially if there's a 10x performance improvement. This is not good...

**Comment by jbogard** [comment]
The type converter is just a bad fit to begin with, the intention is to have a single function always applied globally, but if you have conditional logic based on certain types, that kind of feature really needs to be in AutoMapper. My idea is to take that conditional that you have inside of your type converter and lift that into AutoMapper (I was planning on doing this for 5.1, but let's see if we can sneak it in).

You already have the ability to do `ForAllMaps`, something like:

```
Func<PropertyMap, bool> convertFrom = pm => pm.DestinationPropertyType == typeof(DateTime) 
&& pm.SourceMember.Type == typeof(DateTime) 
&& pm.TypeMap.SourceType.Namespace.Contains("foo");
Func<PropertyMap, bool> convertTo = pm => !convertFrom(pm);

cfg.ForAllMembers(convertTo, 
(pm, cfg) => cfg.ResolveUsing(typeof(ConvertToLocalTimeZoneResolver), opt => opt.FromMember(pm.SourceMember.Name)));

cfg.ForAllMembers(convertFrom, 
(pm, cfg) => cfg.ResolveUsing(typeof(ConvertFromLocalTimeZoneResolver), opt => opt.FromMember(pm.SourceMember.Name)));
```

**Comment by mobius7777** [comment]
Thanks, I'll pursue that solution and see where it leads.

**Comment by mobius7777** [comment]
I cannot get this to work because I do not know where pm (PropertyMap) is supposed to come from. Also, there is no method called ForAllMembers. If you mean ForAllMaps, the signature is different.

**Comment by jbogard** [comment]
@mobius7777 that solution doesn't exist yet :)

It also looks like you're trying to solve for a different sort of problem. You have a perfectly good DateTime -> DateTime mapping that can work OOTB, but you need to modify the result slightly to a new result. I used to have something similar called "formatters" but they only worked for strings so I took them out. Something that I'm thinking in the future, even better fit than resolvers or type converters, is a modifier. For types where A and B are the same, apply a modifier to it.

**Comment by mobius7777** [comment]
So, is there any thought to creating a 4.2.2 release to fix the bugs that were from 4.2.1?

**Comment by jbogard** [comment]
Nope. But I am trying to sneak this solution in above, the `ForAllMembers` one. It's not much to add, the other one is more complicated, modifiers, so that'll wait until 5.1.

**Comment by mobius7777** [comment]
It's not uncommon for projects to maintain a prior release branch for bug fixes, especially when there are such major changes in the new major version. We are having to upgrade to 5.0 just to get a a few bug fixes, but the severity of the changes introduce in the 5.0 are globally affecting our application. It is less than ideal.

**Comment by jbogard** [comment]
You're welcome to fork and add those bug fixes through PRs. There is a tag for each release, and my CI server is able to handle just fine releasing old things. But as this is completely unpaid work, it's too much for me to go back and apply bug fixes to two rather different codebases at this point.

Would the above solution be acceptable? The ForAllMembers?

**Comment by mobius7777** [comment]
I think ForAllMembers would work, but I won't know for certain until I try it.

**Comment by lbargaoanu** [comment]
A combination of ForAllMaps and ForAllMembers should do the trick with the current codebase.

**Comment by jbogard** [comment]
@lbargaoanu it won't because there's no property map, and for this ResolveUsing to work it needs it.

**Comment by mobius7777** [comment]
I have backed out to Automapper 4.1.1, and the bug we were seeking to avoid (from issue 1373 / 1372) is not present. We will still be updating to 5.0.x in the future, but only once ForAllMembers is present and we have time to perform a full integration test with our application.

I suppose this issue can be closed, unless you're keeping it open for the ForAllMembers change.

**Comment by jbogard** [comment]
I am, for the ForAllMembers (which is in now).

**Comment by TylerCarlson1** [comment]
Meaning it's in the MyGet feed (https://www.myget.org/F/automapperdev/api/v2), if you want to test it right now.

**Comment by mobius7777** [comment]
I'll give a try, but I think we'll be sticking with 4.1.1 until at least 5.0.1 or even 5.1 comes out, simply because of testing and stability concerns. Thanks.

**Comment by mobius7777** [comment]
Ok, I have tried this and run into a lot of issues. For one thing, it looks like I am to use ForAllPropertyMaps, not ForAllMembers. The signature for ForAllPropertyMaps matches your example above. Using that example, plus the example in your Unit Test, and modified for my situation, it almost works. However, I had to use pm.SourceType == typeof(DateTime) rather than pm.SourceMember.Type == typeof(DateTime). pm.SourceMember.Type is always equal to RuntimePropertyInfo.

The mappings work for a bit, but eventually I get exceptions from Automapper regarding "No coercion operator is defined between types ", usually involving one of our system's model classes and System.DateTime. For example ::"No coercion operator is defined between types 'Domain.Model.UserLogin' and 'System.DateTime'."

Here is the full stacktrace:

  at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)\r\n   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)\r\n   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)\r\n   at AutoMapper.ExpressionExtensions.ToType(Expression expression, Type type) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\ExpressionExtensions.cs:line 55\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.BuildValueResolverFunc(PropertyMap propertyMap, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, Expression destValueExpr, ParameterExpression ctxtParam) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 443\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 299\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 259\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass5_0.<CreateAssignmentFunc>b__1(PropertyMap pm) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 127\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 125\r\n   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Execution\\TypeMapPlanBuilder.cs:line 73\r\n   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\TypeMap.cs:line 228\r\n   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\MapperConfiguration.cs:line 241\r\n   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\MapperConfiguration.cs:line 45\r\n   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\MapperConfiguration.cs:line 53\r\n   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\MapperConfiguration.cs:line 48\r\n   at AutoMapper.Mapper.Initialize(Action`1 config) in C:\\Projects\\AutoMapper-master\\src\\AutoMapper\\Mapper.cs:line 52

**Comment by jbogard** [comment]
Well, that's definitely in the value resolver building. It looks like the value supplied to the value resolver is the model, not the date time property. What's the source/destination type look like in this case?

**Comment by mobius7777** [comment]
The call to ForAllPropertyMaps looks like this:

cfg.ForAllPropertyMaps(convertFromLocalDateTime, (pm, opt) => opt.ResolveUsing(typeof(ConvertFromLocalTimeZoneResolver), pm.SourceMember.Name));

Perhaps it is that pm.SourceMember.Name is wrong, but I was following the example. Should this also be pm.SourceType.Name instead?

**Comment by mobius7777** [comment]
Expression.Extension is getting an Expression of UserLogin (a class). That is called from BuildValueResolverFunc, which is getting the parameters PropertyMap = "LastLockedOutDate" (which is correct), a typeMapRegistry with nearly 1000 maps, a srcParam which is our User class (note, UserLogin is a child property of User, and UserLogin has the property LastLockedOutDate), destValueExpr is LastLockedOutDate, and ctxtParam appears to be the ResolutionContext.

I'm guessing the issue is the parent class is being passed because it has a datetime property? I don't know.

**Comment by jbogard** [comment]
The SourceMember.Name means "don't pass the containing object to the resolver, pass this property instead".

So it's getting src == User, and you have User.UserLogin.LastLockedOutDate, and the destination is LastLockedOutDate? You want to do dest.LastLockedOutDate = User.UserLogin.LastLackedOutDate?

**Comment by mobius7777** [comment]
Ok, but I'm not mapping anything explicitly. I'm using the function to determine the condition parameter for ForAllPropertyMaps, the just passing the rest of the ResolveUsing expression.

cfg.ForAllPropertyMaps(convertFromLocalDateTime, (pm, opt) => opt.ResolveUsing(typeof(ConvertFromLocalTimeZoneResolver), pm.SourceMember.Name));

The convertFromLocalDateTime conditional looks like this (I expanded it for debugging):

            Func<PropertyMap, bool> convertFromLocalDateTime = pm =>
            {
                if (pm.DestinationPropertyType == typeof(DateTime) && pm.SourceType == typeof(DateTime))
                {
                    if (pm.TypeMap.DestinationType.Namespace.Contains("Domain"))
                        return true;
                }
                return false;
            };

Maybe I have my source and destination backwards.

**Comment by mobius7777** [comment]
You mean explicit maps for the classes using ForMember ... MapFrom ? No. The whole point is that we had set up global type converters (pre-5.0) using CreateMap<System.DateTime, System.DateTime>().ConvertUsing<TimeZoneConverter>(), so that we didn't have to map thousands of DateTime properties across all our models, both ways. It was the "easy way out", which worked in pre-5.0. 

Now in 5.0, we either have to go back and setup explicit ForMember maps for every DateTime property on every single model in our system, which is thousands of models. 

Either that, or no use Automapper for converting timezones. I know that's not what it's for, but it was convenient at the time. Now I guess we just need to find another way. It's just very hard to explain to management why we now need to invest lots of time in making something that used to work now work differently because a third party library changed something.

I guess we'll just be sticking with 4.1.1 for a while.

**Comment by jbogard** [comment]
Nah, I meant are you redirecting any members. MapFrom lets you redirect members, but a type converter would still be used. A resolver would mess that up, though.

If you used a MapFrom, that would mean the original approach of using a resolver wouldn't work.

Anyway, I think you're probably better off waiting on upgrading, but do take a look at my proposal, I think that's a better solution than the type converter, which is just intended to convert types.

**Comment by mobius7777** [comment]
I see what you're saying now. And yes, in fact, we are. For that exact property too. That must be the culprit. It's from a flatterer map, that is pulling in the value from the child property to be on the parent. We do do that in several places, but not a lot.

The modifer concept from #1414 looks promising. I guess we'll just keep on the progress of 5.x, and revisit in the future. Thanks for your help.

**Comment by jbogard** [comment]
No worries, and thanks again for your patience and help in tracking down the issue.

**Comment by zaytsevvla** [comment]
It seems like most of topic is  unrelated.

`ResolutionContext.Parent` was really useful in my case, so i can't update to 5.x version.

Let me show:
```c#
internal static class ExternalKeyResolver
    {
        public static IValueResolver Create<T>(Func<T, object> keyExtractor) where T : class => new Resolver<T>(keyExtractor);

        private class Resolver<T> : IValueResolver where T : class
        {
            private readonly Func<T, object> _keyExtractor;

            public Resolver(Func<T, object> keyExtractor)
            {
                _keyExtractor = keyExtractor;
            }

            public ResolutionResult Resolve(ResolutionResult source)
            {
                if (source.Value == null)
                    return source.Ignore();

                var parent = GetKey(source.Context);
                if (parent == null)
                    throw new AutoMapperMappingException(
                        $"Need {typeof(T).Name} parant to get key id. Got {source.Context?.Parent?.SourceValue}");

                return source.New(_keyExtractor(parent));
            }

            private T GetKey(ResolutionContext source)
            {
                if (source?.Parent == null)
                    return default(T);
                var parent = source.Parent?.SourceValue as T;
                return parent ?? GetKey(source.Parent);
            }
        }
    }
```
And classes:
```c#
class DomainAggragate
    {
        public int Id { get; set; }

        private ICollection<DomainItem> Items { get; set; } = new List<DomainItem>();
    }

    class DomainItem
    {
        // it is a local key inside one aggregate
        public string Key { get; set; }
        public string Value { get; set; }
    }

    class DatabaseAggragate
    {
        [Key]
        public int Id { get; set; }

        private ICollection<DomainItem> Items { get; set; } = new List<DomainItem>();
    }

    class DatabaseItem
    {
        // so primary key is AggragateId, Key
        public int AggragateId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
```
so, when I map form DomainItem to DatabaseItem i need parent Id.

**Comment by lbargaoanu** [comment]
You should be able to use Context.Options.Items to achieve the same thing.

**Comment by pmiddleton** [comment]
Was there every a resolution for @mobius7777 original issue?

It just so happens that we are doing the exact same thing with regards to timezone conversions and have run into the same issue trying to upgrade from 4.0.4 to 6.0.

Looking at the 6.0 code I don't see either the ForAllMembers or Modifiers proposals, so I'm guessing both got shelved?
