### ISSUE TITLE
How to ignore all unmapped members for a mapping?

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1395]
With v4.2.1 I had the following extension:

```
public static IMappingExpression<TSource, TDestination> IgnoreUnmapped<TSource, TDestination>(this IMappingExpression<TSource, TDestination> expression)
{
    var typeMap = Mapper.FindTypeMapFor<TSource, TDestination>();
    if (typeMap != null)
    {
        foreach (var unmappedPropertyName in typeMap.GetUnmappedPropertyNames())
        {
            expression.ForMember(unmappedPropertyName, opt => opt.Ignore());
        }
    }

    return expression;
}
```

Now with v5.0.0 the method `FindTypeMapFor` has moved under `Mapper.Configuration`. With the new way of doing things using the static API as follows:

```
Mapper.Initialize(cfg => 
{
    cfg.CreateMap<MyModel, MyDto>().ReverseMap().IgnoreUnmapped();
});
```

An exception is thrown:
"Mapper not initialized. Call Initialize with appropriate configuration."

What is the alternative to ignored unmapped members without explicitly ignoring each and every member?

**Comment by lbargaoanu** [comment]
#1386?

**Comment by jbogard** [comment]
Yep. No idea this many people used that.

**Comment by cryo75** [comment]
This was a handy extensions when using the static API!!

I will close this issue because using the "MemberList" enum should do the trick.

**Comment by DimitryNechaev** [comment]
var mapperConfiguration = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new MyProfile());
                // ignore all unmapped properties globally
                cfg.ForAllMaps((map, exp) => exp.ForAllOtherMembers(opt => opt.Ignore()));
            });

**Comment by jbogard** [comment]
Oh please no don’t do this

**Comment by DimitryNechaev** [comment]
Yes, this contradict the automapper main purpose. But if you need to make explicit only mapping and let no single property to get mapped implicitly this will do the job.

**Comment by jbogard** [comment]
Then don’t use AutoMapper use manual mapper aka code.
