### ISSUE TITLE
StackOverflowException even with MaxDepth of 1

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1398]
After upgrading to v5.0.0 from 4.2.1 I'm getting a StackOverflowException when mapping the following model classes to their dto counterparts:
```
public class UserModel
{
    public virtual UserGroupModel Group { get; set; }
}

public class UserGroupModel
{
    public virtual ICollection<UserModel> Users { get; set; }
}
```

The mapping configuration is:
```
cfg.CreateMap<UserModel, UserDto>(MemberList.Destination).MaxDepth(1).ReverseMap();
cfg.CreateMap<UserGroupModel, UserGroupDto>(MemberList.Destination).MaxDepth(1).ReverseMap();
```

Why am I still getting the exception if MaxDepth is 1?

**Comment by lbargaoanu** [comment]
Try the MyGet buld. If it still doesn't work, make a gist that we can execute and see fail.

**Comment by cryo75** [comment]
The MyGet build didn't work either.

Here is the Gist:
[https://gist.github.com/cryo75/e4699b021d26820203e6896bd6532962](url)

**Comment by lbargaoanu** [comment]
I don't know what's the issue, but the gist runs ok for me. On .NET desktop, right :)? There is also a [PR](https://github.com/AutoMapper/AutoMapper/pull/1399) with a similar test passing.

**Comment by jbogard** [comment]
When are you getting this exception? Map? ProjectTo? Config time?

**Comment by khorvat** [comment]
I have a similar issue, but it only happens when I turn on the CreateMissingTypeMaps.

I have tried to use the CreateMissingTypeMaps on main configuration and on profiles (tested separately) and both. Every time I get StackOverflowException.

I have upgraded from 3.2.1, large app, and I'm getting exception when I try to Map.

**Comment by jbogard** [comment]
When do you get this exception?

**Comment by cryo75** [comment]
@jbogard The exception occurs on Map.

**Comment by khorvat** [comment]
Same here, as I mentioned.

**Comment by cryo75** [comment]
@jbogard @lbargaoanu I've reverted back to 4.2.1 (but keeping the same configuration setup as for 5.0.0). It works fine with or without using MaxDepth. 

So the problem must be in 5.0.0.

**Comment by khorvat** [comment]
@cryo75 do you have CreateMissingTypeMaps turned on ? Just to test few more things and be sure that we are talking about the same issue here ?

**Comment by lbargaoanu** [comment]
We still need a repro. About CreateMissingTypeMaps, that can cause a lot of issues, so if you know the types at compile time, just don't use it.

**Comment by cryo75** [comment]
@khorvat It works when "CreateMissingTypeMaps" is either on off. My issue is that when calling "Map" on an object that has reference looping, v5.0.0 throws a "StackOverflowException" but 4.2.1 not.

As a test, you should try downgrade to 4.2.1 and test it out.

**Comment by khorvat** [comment]
@lbargaoanu well I just upgraded a large app from 3.2.1 that has few thousands types, scattered across modules etc. In 3.2.1 I had lazy CreateMap custom functionality that was automatically creating maps for me. After the upgrade I had to remove that auto create map functionality and now I don't have many CreateMap calls. I tried to use _CreateMissingTypeMaps_ and I get _StackOverflowException_, I have created configuration and all profiles are loaded, when I hit first _Map_ I get the _StackOverflowException_.

@cryo75 I'll try to downgrade to 4.2.1 and test it.

**Comment by lbargaoanu** [comment]
@khorvat You can use the non generic version of CreateMap and create the needed maps with some reflection code.

**Comment by khorvat** [comment]
@lbargaoanu I had that, but I was hoping that I can remove my code and use _CreateMissingTypeMaps _ to do that for me in 4.x or 5.x version

**Comment by lbargaoanu** [comment]
What AutoMapper wants is not what it needs :) That's why CreateMissingTypeMaps is not that useful. It starts creating all the maps it thinks it needs, but many times that doesn't help. It's just a different problem.

**Comment by jbogard** [comment]
No no no, CreateMissingTypeMaps is when you don't know the types at compile time, nothing else. It is not a shortcut to not call CreateMap. Remove that CreateMap and now you have no idea if something doesn't match up, it just silently skips it. If you know the types you should be using CreateMap and AssertConfigurationIsValid otherwise you're in for a world of pain.

**Comment by khorvat** [comment]
@jbogard ok I see, then I'll try my luck with 5.x and try to kick in my old code for auto CreateMap, thanks.

**Comment by jbogard** [comment]
What was your code for "auto CreateMap"? Was it using CreateMissingTypeMaps or no?

Conventionally creating maps is OK, CreateMissingTypeMaps waits until execution time to create a map. The real value is AssertConfigurationIsValid.

**Comment by khorvat** [comment]
@jbogard no it wasn't using _CreateMissingTypeMaps_ it had our bizz logic to scan the objects and execute CreateMap, lazy when _Map_ is called by check for TypeMaps. Now in 4.x and 5.x architecture is different so I have to rewrite the code.

**Comment by jbogard** [comment]
That's OK to do that then. The only difference is in 5.0 instead of calling Mapper.CreateMap, you'll create a MapperConfigurationExpression and call CreateMap on that. Carry on!

**Comment by jbogard** [comment]
To be explicit:

```
var cfgExpr = new MapperConfigurationExpression();
cfgExpr.CreateMap<Source, Dest>();

BizzLogic.Scan(cfgExpr);

var config = new MapperConfiguration(cfgExpr);
IMapper mapper = new Mapper(config);
```

**Comment by jbogard** [comment]
@cryo75 what's the difference between your gist that fails and the PR that is currently passing?

**Comment by cryo75** [comment]
@jbogard The different between my actual code and the gist that I did (which is similar to the PR) is that both my models are much more complex than just a property each. However, it is these two particular properties which result in circular referencing.

And as I said, 4.2.1 works fine.

**Comment by TylerCarlson1** [comment]
@khorvat what you should be looking at is [Conventions](https://github.com/AutoMapper/AutoMapper/wiki/Conventions) to replace your lazy CreateMap code not CreateMissingMaps property.  The convention will give you both source type and dest type, so from there you can add your logic to scan the types and see if it should create a new TypeMap or not.

Unfortunately this probably won't solve the MaxDepth StackOverflowException problem.  It's just the recommended way of adding maps based on user set criteria.

**Comment by cryo75** [comment]
@jbogard Ok it turns out that it was a completely different member that's causing circular referencing. I've update the [gist](https://gist.github.com/cryo75/e4699b021d26820203e6896bd6532962) to reflect this.

In my actual code, using v5.0.0 and setting MaxDepth to 1 doesn't cause the exception. However, using v4.2.1 and no MaxDepth will not cause the exception.

**Comment by lbargaoanu** [comment]
In 5.0 PreserveReference is false by default (used to be true) and that's probably the root cause. Nothing to do here.

**Comment by jbogard** [comment]
@lbargaoanu I wonder if a better exception message would be appropriate? Catch a StackOverflow and add a better message?

**Comment by lbargaoanu** [comment]
There are exceptions that you catch and exceptions that you don't. SO is in the latter category :). But seriously, you're out of stack, there isn't much you can do reliably by then. But I see your point, it's frustrating to just crash. Maybe to detect it before it happens, but at zero cost. I guess it's not going to happen.

**Comment by jbogard** [comment]
@cryo75 can you try PreserveReferences? That was another insane perf killer I had to default to false.

**Comment by jbogard** [comment]
@lbargaoanu yeah you're right, just thinking through if there were a way to detect this for people at config time.

**Comment by cryo75** [comment]
@jbogard PreserveReferences doesn't affect the mapping. The member remains null. I guess the only solution is to rethink the model so I can keep on using 5.0.0.

**Comment by khorvat** [comment]
@jbogard I have tried the suggestion from @TylerCarlson1 about using _AddConditionalObjectMapper_ and added the code below to my configuration (same as on wiki), just to see if this is the right path to go, now I get _StackOverflowException _ same situation as @cryo75 and his gist. 

What is the preferred solution here ? Rethink the model or something else ?  In this part of the app my models are generated by the Entity Framework and the props causing this issue are navigation props, so I'm not sure I can rethink the whole model here.

```
var config = new MapperConfiguration(cfg => {
    cfg.AddConditionalObjectMapper().Where((s, d) => s.Name == d.Name + "Poco");
});
```

**Comment by khorvat** [comment]
BTW I have just downgraded to 4.2.1 and almost everything is working, as I have removed my auto create map logic (didn't put it back yet), I tried to turn on _CreateMissingTypeMaps_ and test, now TypeMaps are created automatically and there is no _StackOverflowException_ killing the app.

Will try 4.2.1 for a while and upgrade to 5.0 as soon as this issue if fixed. Eager to get 5.0 performance boost.

**Comment by lbargaoanu** [comment]
There will not be any fix without a repro.

**Comment by khorvat** [comment]
Did @cryo75 's [gist](https://gist.github.com/cryo75/e4699b021d26820203e6896bd6532962) reproduced the issue ?

**Comment by jbogard** [comment]
Nope :(

**Comment by khorvat** [comment]
Ok, will try to provide repro gist

**Comment by lbargaoanu** [comment]
And try PreserveReferences. Because that's not a bug, we wanted to change that one :)

**Comment by khorvat** [comment]
Here is the [gist](https://gist.github.com/khorvat/70007d92dad3abd89420835a23ee7bdb) _AutoMapper StackOverflowException issue related to CreateMissingTypeMaps and AddConditionalObjectMapper_ 

In both cases I get _StackOverflowException_ while this is working in 4.2.1

I don't know how to turn on _PreserveReferences_ on dynamically created TypeMaps when using _CreateMissingTypeMaps_ or _AddConditionalObjectMapper_ any suggestions ?

**Comment by TylerCarlson1** [comment]
Can you try `cfg.AllowNullDestinationValues = false;` and see if that helps.  Have similar issue #1352, but it's calling `ProjectTo()` with circular dependency that causes the StackOverflowException.

Also can you give a complete exception message with stack trace, that will help determine the exact source of the problem.

**Comment by jbogard** [comment]
This works:

https://gist.github.com/jbogard/b28a1d88e7ecb833544020a8d9d76173

**Comment by jbogard** [comment]
One thing we could look at is to detect circular references and throw during configuration validation.

**Comment by khorvat** [comment]
@jbogard is there a way to set _PreserveReferences_ when using _CreateMissingTypeMaps_ or _AddConditionalObjectMapper_ ?

**Comment by TylerCarlson1** [comment]
@khorvat Currently no.  It creates a new TypeMap and follows the conventions of the Profile.  There's nothing in the Profile that has the ability to get the TypeMap when a new TypeMap is generated.  This was a possible feature for Conventions, but since we didn't know what it might be used for we didn't add it.  If you want you can make a new Issue to request for modifying TypeMap after it's generated by AddConditionalObjectMapper/CreateMissingTypeMaps

**Comment by TylerCarlson1** [comment]
@khorvat Sorry I think miss-spoken.  `cfg.ForAllMaps()` should work on CreateMissingTypeMaps and AddConditionalObjectMapper.  I thought it only worked on TypeMaps defined in the configuration before.

**Comment by khorvat** [comment]
@TylerCarlson1 I have opened a separate issue #1422 thanks.
