### ISSUE TITLE
IMappingExpression TypeMap

### ISSUE THREAD

**Issue by jekcom** [AutoMapper/AutoMapper#1403]
Referencing this issue : #678 the property TypeMap is gone from IMappingExpression in 5.0 and now it doesn't compile

**Comment by lbargaoanu** [comment]
What are you trying to do?

**Comment by jbogard** [comment]
BTW this isn't coming back. The type map doesn't exist until after all the CreateMaps are processed.

**Comment by jekcom** [comment]
We have extension method for ignoring all not mapped properties when reversing the map. Without this method we would need to ignore each property one by one manually.

`        public static IMappingExpression<TSource, TDestination> IgnoreAllNonExisting<TSource, TDestination>(this IMappingExpression<TSource, TDestination> expression)
        {
            foreach (var property in expression.TypeMap.GetUnmappedPropertyNames())
            {
                expression.ForMember(property, opt => opt.Ignore());
            }
            return expression;
        }`

**Comment by lbargaoanu** [comment]
See #1386.

**Comment by jekcom** [comment]
@lbargaoanu ok. that seems like solved the issue. Than you.

**Comment by lbargaoanu** [comment]
You're welcome. You can close the issue.
