### ISSUE TITLE
AutoMapper custom type converter gives exceptions with nullable types.

### ISSUE THREAD

**Issue by vgpallis** [AutoMapper/AutoMapper#1404]
By doing this mapping creation :

`Mapper.Initialize(config => {
config.CreateMap<One.Dealer.Infrastructure.Proxies.Hana.IDMS_S_DashboardTiles,                      One.Dealer.Models.Entities.IDMS_S_TILE>();
config.CreateMap<int?, short?>().ConvertUsing<Int2ShortTypeConverter>();
});`

and having implemented the following type converter :

` public class Int2ShortTypeConverter : ITypeConverter<int?, short?>
    {
        public short? Convert(int? source, ResolutionContext context)
        {
            return source.HasValue ? (short?) System.Convert.ToInt16(source) : null;
        }
    }`

the Mapper.Initialize() method gives the following exception : 
" This operation is only valid on generic types."

If i change the type conversion method to :

`config.CreateMap<int?, short?>().ConvertUsing(new Int2ShortTypeConverter());`

the Mapper.Initialize() method gives the following exception : 
"Expression of type System.Nullable"1[System.Int16] cannot be used for parameter of type System.Nullable"1[System.Int32]"

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by vgpallis** [comment]
Hi!
How do I get this build? Is it on nuget ?

**Comment by jbogard** [comment]
No, myget: http://myget.org/gallery/automapperdev

**Comment by lbargaoanu** [comment]
This can be closed.
