### ISSUE TITLE
No replacement for IsSourceValueNull

### ISSUE THREAD

**Issue by SharpSeeEr** [AutoMapper/AutoMapper#1406]
In AutoMapper v5 conditions added to a map only receive the instance of the source object rather than a mapping context.  Configurations setup using `o.Condition(c => !c.IsSourceValueNull)` are no longer valid.  How is this option specified in v5?

**Comment by jbogard** [comment]
There's a ton of overloads for Condition, including one that accepts the
source object.

**Comment by vascofernandes** [comment]
I have this question as well.
Are these lines equivalent ?

.ForAllMembers(opt => opt.Condition(r => r != null));
 //.ForAllMembers(opt => opt.Condition(r => !r.IsSourceValueNull));


?

**Comment by jbogard** [comment]
Yes.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by sindilevich** [comment]
Hello @jbogard,

While using Automapper 4.2, I had defined two Automapper profiles, each of which defined a map, with a condition to ignore all the `null` source values. The code was something like this:
```C#
internal class ProfileA : Profile
{
	protected override void Configure()
	{
		Mapper.CreateMap<DtoA, EoA>()
			.ForAllMembers(option => option.Condition(condition => !condition.IsSourceValueNull));
	}
}

internal class ProfileB : Profile
{
	protected override void Configure()
	{
		Mapper.CreateMap<DtoB, EoB>()
			.ForAllMembers(option => option.Condition(condition => !condition.IsSourceValueNull));
	}
}

public class AutomapperConfig
{
	public static void Configure()
	{
		Mapper.Initialize(config =>
		{
			config.AddProfile<ProfileA>();
			config.AddProfile<ProfileB>();
		});
	}
}
```

As far as I understand, in Automapper v5 there is an option configuring the ignore for `null` source values for all the maps at once. So I came up with the code like below:
```C#
internal class ProfileA : Profile
{
	public ProfileA()
	{
		CreateMap<DtoA, EoA>();
	}
}

internal class ProfileB : Profile
{
	public ProfileB()
	{
		CreateMap<DtoB, EoB>();
	}
}

public class AutomapperConfig
{
	public static void Configure()
	{
		Mapper.Initialize(config =>
		{
			config.AddProfile<ProfileA>();
			config.AddProfile<ProfileB>();
			config.ForAllMaps((tm, me) => me.ForAllMembers(option => option.Condition(member => member != null)));
		});
	}
}
```

Can you please confirm the code above in Automapper v5 will cause that all the `null` source values in every map will be ignored?

**Comment by jbogard** [comment]
Looks good to me.

**Comment by Mike-EEE** [comment]
I do not know what I am doing wrong, but the option values are always null for me:

```
var source = new BasicClass { PropertyName = "Hello World!" };
var mapper = new MapperConfiguration( cfg =>
{
	cfg.CreateMap<BasicClass, BasicClass>().ForAllMembers( configurationExpression =>
	{
		configurationExpression.Condition( ( one, two, three, four, arg5 ) => three != null ); // three and four are always null. :( :( :(
	} );
}  ).CreateMapper();
var mapped = mapper.Map<BasicClass>( source );
```

Can someone take a second to help out this newb who is upgrading to 5.0?  Please and thank you. :)

**Comment by vascofernandes** [comment]
It seems that there is a bug here in 5.1.1.

Please see https://github.com/AutoMapper/AutoMapper/issues/1634

**Comment by Mike-EEE** [comment]
BIG bug, @vascofernandes ... thank you for that.  Going insane over here trying to figure out the most basic of functionality.

**Comment by nukec** [comment]
@Mike-EEE did you ever resolve this?

**Comment by Mike-EEE** [comment]
Oh man... I stopped using AutoMapper because of this and other (performance) issues, @nukec. 😞 I might check it out again sometime in the future, though.

**Comment by nukec** [comment]
@Mike-EEE what alternative do you use?

I had to use different model with only necessary fields so nulls were not mapped over. Doesn't work still.

**Comment by vascofernandes** [comment]
In [issues/1634](https://github.com/AutoMapper/AutoMapper/issues/1634) I describe an alternative.

But you can always use plain C# to write your mappings.
That is what I started to do.

```csharp
    public class MyClassDto 
    {
        public int Id {get; set;}

        public static MyClassDto MapFrom(MyClass param) {
            return new MyClassDto 
            {
                Id = param.Id,
            };
        }
    }
```

**Comment by Mike-EEE** [comment]
Yeah @nukec I just ended up using a custom-rolled implementation for my own scenario.
