### ISSUE TITLE
Defined Map not used when CreateMissingTypeMaps is turned on

### ISSUE THREAD

**Issue by khorvat** [AutoMapper/AutoMapper#1408]
In AutoMapper 3.3.1 we used CreateMap (_1st ref._) where binding is from interface to concrete type and in 3.3.1 that manually defined map was used and AfterMap was working correctly. Now we have upgraded to 4.2.1 (tried 5.0 hit the wall and downgraded #1398 ) and this mapping and AfterMap is not called any more. This only happens when _CreateMissingTypeMaps_ is turned on.  When Mapper.Map is called, actual mapping is using instance of _ArticlePoco_ that implements _IArticle_ and it is mapping to _Article_. If I add mapping from interface to poco object that manually defined map is used and AfterMap is called - everything is working fine. 

Is this is a bug or breaking change ? 

~~Also is this happening in 5.0 as I plan to upgrade as soon as it become a bit more stable ?~~
Also I can't test this on 5.0 because of #1422 I'll test this as soon as we have fix or workaround for that issue.

_1st ref._

```
var map = CreateMap<IArticle, Article>();
 map.AfterMap((s, d) =>
{
    //some logic
});
```

_2nd ref._

```
var map = CreateMap<ArticlePoco, Article>();
 map.AfterMap((s, d) =>
{
    //some logic
});
```

**Comment by khorvat** [comment]
I have add some more information to this issue and here is the [gist](https://gist.github.com/khorvat/db98a58b36971cb0734e961ed22bb54e).

**Comment by khorvat** [comment]
I can confirm that this is not related to _binding interface to concrete type_ but to _CreateMissingTypeMaps_.

When _CreateMissingTypeMaps_ is turned on manual bindings are not used, my gist is available for you to reproduce the issue and this issue *is present in 5.0 and in MyGet latest prerelease*.

**Comment by khorvat** [comment]
@TylerCarlson1 is there any other configuration switch that needs to be turned on in order for _CreateMissingTypeMaps_ to use manually created maps ?

**Comment by TylerCarlson1** [comment]
Nope CreateMissingTypeMaps just creates TypeMaps when a default isn't found.  What Most likely is happening is when you do the list it trys to map each item by getting its type.  4.2 and 5.0 are different in how they go about it in lists, but don't know if that changes final result.

I would suggest doing  `var result = roles.Select(mapper.Map<Role>).ToList();` and it should be called correctly.  If it's a property inside a class it might work as intended in 4.2 and 5.0.

**Comment by Muchiachio** [comment]
@TylerCarlson1 it's not that, after `CreateMissingTypeMaps` was introduced `AfterMap` started to not be called then a derived type is being used as a mapping source. [Here's](https://github.com/Muchiachio/CreateMissingMaps) a repro project.

You can see that I created a map for `CreateMap<Role, RoleView>()`, but if I map from `AdminRole` (derived type from `Role`), after map is not being called anymore.

This becomes clearly visible with EntityFramework's dynamic proxies.

**Comment by TylerCarlson1** [comment]
For you EF proxy generation see this https://github.com/AutoMapper/AutoMapper/pull/1621#issuecomment-240145612

**Comment by Muchiachio** [comment]
Nice tip, thanks!
