### ISSUE TITLE
Mapper.Initialize throws exceptions where static API did not

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1409]
I have a quite large project (100's, maybe 1000's, of mappings) where the bootstrapping was previously implemented like this (with AutoMapper 2.2.1):

```c#
public class Bootstrapper
{
    public static void Initialize() // called on start of application
    {
        ServiceABootstrapper.Initialize();
        ServiceBBootstrapper.Initialize();
        // etc...
    }
}

public class ServiceABootstrapper // and similar for ServiceBBootstrapper
{
    public static void Initialize()
    {
        AutoMapper.Mapper.CreateMap<Foo, Bar>();
        // etc...
    }
}
```

Now I'm attempting to upgrade to 4.2.1. In order to convert this to something that doesn't give compiler warnings about the static API being obsolete (we compile with warnings as errors...) I have changed this to

```c#
public class Bootstrapper
{
    public static void Initialize() // called on start of application
    {
        Mapper.Initialize(cfg => Initialize(cfg));
    }

    public static void Initialize(IMapperConfiguration cfg)
    {
        ServiceABootstrapper.Initialize(cfg);
        ServiceBBootstrapper.Initialize(cfg);
        // etc...
    }
}

public class ServiceABootstrapper // and similar for ServiceBBootstrapper
{
    public static void Initialize(IMapperConfiguration cfg)
    {
        cfg.CreateMap<Foo, Bar>();
        // etc...
    }
}
```

However, building the configuration now fails with an `InvalidOperationException`, with a significantly less helpful messagen than what I used to get from `AssertConfigurationIsValid()` (and it now fails for mappings that previously worked...).

Here is the error message, with identifying names substituted (but no logical parts removed):

```
Test method MyProject.SomeNamespace.AutoMapperTest.AutoMapperTest.TestAutomapperMappingsIsValid threw exception: 
System.InvalidOperationException: Missing map from Foo to Foo. Create using Mapper.CreateMap<Foo, Foo>.
    at AutoMapper.QueryableExtensions.Impl.QueryMapperHelper.MissingMapException(Type sourceType, Type destinationType)
   at AutoMapper.MapperConfiguration.<GetDerivedTypeMaps>d__89.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers, IEnumerable`1 typeMapObjectMappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at MyProject.SomeNamespace.Tests.AutoMapperTest.AutoMapperTest.TestAutomapperMappingsIsValid() in C:\Code\MyProject\MyProject.SomeNamespace.Tests\AutoMapperTest\AutoMapperTest.cs:line 12
```

I miss the old error message :) This one doesn't really give me much, as I don't even know in which direction a mapping is missing (no namespaces on the Foo classes are given...).

**Comment by lbargaoanu** [comment]
You should upgrade to 5.0.

**Comment by jbogard** [comment]
Yeah I have no idea on 4.2.1. Just skip that one and go straight for 5.0, the API broke enough.

Actually, wait for 5.0.1, I made a slight change to the static API config that will help you here:

```
var cfgExpr = new MapperConfigurationExpression();
cfgExpr.CreateMap<Foo, Bar>();
Bootstrappers.Bootstrap(cfgExpr);

Mapper.Initialize(cfgExpr);
```

**Comment by tlycken** [comment]
Thanks for the speedy response!

OK, upgraded to 5.0. To make it build, I basically just had to find-replace `IMapperConfiguration ` for `IMapperConfigurationExpression ` and re-implement a value resolver somewhere (apparently the base class disappeared, no biggie...).

There seems to be some more changes in how to correctly initialize and test a configuration still, though. I did this now:

```c#
var config = new MapperConfiguration(c => Bootstrapper.Initialize(c));
config.AssertConfigurationIsValid();
```

but it still throws a similar `InvalidOperationException` lacking namespace details etc. Is there a better way to get to `AssertConfigurationIsValid()` that won't throw exceptions?

**Comment by lbargaoanu** [comment]
No, the bug is that the error message doesn't have the full type name. Maybe you still have some static Mapper calls somewhere?

**Comment by tlycken** [comment]
Not in the configuration (all of those gave compiler errors before) but I haven't converted any of the actual mappings, so there are a few `Mapper.Map<T1, T2>(t)` calls out there.

(There might be a few of those actually used in admittedly pathological mapper configurations, i.e. things like `.ForMember(d => d.Foo, cfg => cfg.MapFrom(s => Mapper.Map<Bar>(s.Foo.Bar.Baz)`. I should be able to just remove those mapper calls, and let AutoMapper do that, right?)

**Comment by lbargaoanu** [comment]
Probably :) Anyway, you can't mix static calls with instance calls. Once you called CreateMapper, everything must go through that instance.

**Comment by jbogard** [comment]
Yeah, you really shouldn't be calling AutoMapper anywhere inside mapping configuration.

**Comment by tlycken** [comment]
Yeah, I was able to refactor those away pretty easily.

However, I do have a case where I need it - in a custom type converter. Does this usage seem OK?

```c#
private class FooConverter<T1, T2> : ITypeConverter<IFoo<T1>, FailableFoo<T2>>
{
    public FailableFoo<T2> Convert(IFoo<T1> source, ResolutionContext context)
    {
        return context.Mapper.Map<FooData<T2>>(source.AsSerializableData());
    }
}
```

**Comment by lbargaoanu** [comment]
Yes.

**Comment by tlycken** [comment]
Great, then I think I got my upgrade working. Thanks a lot for all the help!
