### ISSUE TITLE
Did mapping of class hierarchies change between 2.2.1 and 4.2.1?

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1410]
In #1409 I described my attempt to port our project from 2.2.1 to 4.2.1. The failing class is, I found when examining the problem closer, the base of a hierarchy. The mapping is implemented like this:

```c#
 cfg.CreateMap<FooBase, Dto.FooBase>()
                .Include<FooTypeOne, Dto.FooTypeOne>()
                .Include<FooTypeTwo, Dto.FooTypeTwo>()
                .Include<FooTypeThree, Dto.FooTypeThree>();
```

Is there some reason this mapping shouldn't work in 4.2.1? What should I do instead?

**Comment by jbogard** [comment]
Upgrade to 5.0, inheritance was basically jacked with complications until 5.0.

**Comment by tlycken** [comment]
OK, upgraded. Still have some issues, but let's deal with those under #1409. Thanks!

**Comment by tlycken** [comment]
Actually, it seems that the exception is thrown because there is no mapping between `FooTypeOne` and `Dto.FooTypeOne` (etc) configured; this didn't use to blow up and now it does (I guess as a consequence of #966).
