### ISSUE TITLE
Conditional Mapping Issue (vers 5.0)

### ISSUE THREAD

**Issue by CompositeID** [AutoMapper/AutoMapper#1413]
I noticed that the method signature(s) changed between 4.2 and 5.0.  After necessary alterations, I noticed that the mapping took place no matter what the result was.  A little background on the condition is that I have been using it to only map if the values have changed.  I've gone so far as to remove all of the conditional logic I had in place and just returned false but it still mapped it back to the destination object.  Any help would be greatly appreciated.

Thanks

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by CompositeID** [comment]
After putting together a simplistic way of representing the existing logic, I noticed what had been creating the issue.  Previously, it appears the member assignment would never be called when mapping if false; however, now it appears as though it still calls the member but passes in the original value.

It originally surfaced when mapping back to rows in a dataset and we noticed that the row state was listed as modified but our code that returns the columns which changed and logged was showing that nothing had changed leading to unnecessary updates to the database.

[Sample Gist](https://gist.github.com/CompositeID/2df8a83a840eb51693a024f52ea8aea3)

**Comment by jbogard** [comment]
Ahhh ok, most ORMs I know of only trigger updates when something is
actually modified from its original value, not when the value is merely set.

**Comment by jbogard** [comment]
Can we close this then?

**Comment by CompositeID** [comment]
If this was an intentional removal of functionality, I'll be more than happy to close it.  If so, was there a reason that this functionality removed in 5.0?  While I'd prefer that 4.2 wasn't the end of the road, it still works and I'd rather not go back to manually mapping with a bunch of "if" statements when moving data back to objects that track any type of object state or trigger other events - which is why this API has been a godsend up to this point.  Thanks

**Comment by jbogard** [comment]
Yeah, in order to make the mapping 20-50x faster, we compile an expression tree. This kind of condition, "don't do anything", is a little bit harder in an expression, but I think it's possible to only set based on a condition (vs. always set and the condition decides WHAT to set).
