### ISSUE TITLE
Opt-out configuration validation

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1416]
Today we do MemberList.Source for reverse mapping. I think we should add a MemberList.None option so that configuration validation can be skipped.

If you do A -> B and then B -> A, you've already validated the B members.

**Comment by jbogard** [comment]
Also, we'd make this the default for ReverseMap.

**Comment by ilmax** [comment]
Are there any specific reason to not allow specify a `MemberList` parameter in the `ReverseMap` method?

**Comment by jbogard** [comment]
It makes it the opposite first CreateMap call. If you don't want that
behavior, don't use ReverseMap, use CreateMap.

**Comment by ilmax** [comment]
:tada:
