### ISSUE TITLE
Not all members are being mapped

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1417]
After upgrading to 5.0.0 I have one model class (I've only tested this class so far) that has 4 members more than its dto class. Some members are other classes and some can be null or empty (if value types).

On mapping the model to the dto, only a couple of members are mapped. The remaining are all set to null.

On downgrading to 4.2.1, the mapping is successful. I've tried creating a gist for a repro but the gist works as expected with 5.0.0. However the test classes where not that complex as in my actual project.

As I cannot reproduce the error, would it be better to add Automapper into my project and debug the mapping?

**Comment by jbogard** [comment]
Yeah, I don't see any other choice.

One thing to look at is the TypeMap's MapExpression in debug mode. This is the map "plan" that will execute at runtime (you don't need to add the code directly).

**Comment by jbogard** [comment]
Also, use the AutoMapper.Net4 project if you're adding the code directly.

**Comment by TylerCarlson1** [comment]
You should be able to see the MapExpression without having to add AutoMapper.  You should be able to open up IMapper or Mapper.Instance then go to `Configuration._typeMapCache` and find the type map in question and see it's expression code.

Also you might want [ReadableExpressions.Visualizers](https://visualstudiogallery.msdn.microsoft.com/2d5de770-50e9-4dcf-87e9-ea1ed1b43b68) so you can actually read the expression generated.

**Comment by jbogard** [comment]
Or Configuration.FindTypeMapFor.

And THERES that visualizer I was looking for lol

**Comment by cryo75** [comment]
```
Ok. Done that and we're approaching the culprit. The MapExpression for this particular object has only 4 out of 16 members mapped. The destintation (dto) has 16 members in total. The source (model) has 20.

The MapExpression looks like this:

(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        var dest = dest ?? new Address();
        try
        {
            dest.ZipCode = ctxt.Map(src.ZipCode, null);
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException("Error mapping types.", ex, AutoMapper.TypePair, AutoMapper.TypeMap, AutoMapper.PropertyMap);
        }

        try
        {
            dest.HouseNumber = src.HouseNumber;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException("Error mapping types.", ex, AutoMapper.TypePair, AutoMapper.TypeMap, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Id = src.Id;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException("Error mapping types.", ex, AutoMapper.TypePair, AutoMapper.TypeMap, AutoMapper.PropertyMap);
        }

        return dest;
    }
}
```

The configuration is simply:

`cfg.CreateMap<AddressModel, AddressDto>(MemberList.Destination).ReverseMap();`

So obviously the next question is:
Why does the map has so little members to map?

**Comment by jbogard** [comment]
Hmmm and the source/dest types match? How about the reverse map?

**Comment by TylerCarlson1** [comment]
Why is it creating a new Address when the map types are AddressModel and AddressDto?  Is there some kind of Include call?

**Comment by cryo75** [comment]
@jbogard The reverse map looks correct as well.

@TylerCarlson1 There are no include calls. I'm actually creating a new AddressModel instance manually to skip EF:

```
                var model = new AddressModel()
                {
                    Id = 100,
                    Street = "str",
                    HouseNumber = "hn" //etc...
                };
                var dto= Mapper.Map<AddressDto>(model);
```

The actual mapping occurs in this method:

```
        TDestination IMapper.Map<TDestination>(object source)
        {
            if (source == null)
                return default(TDestination);

            var types = new TypePair(source.GetType(), typeof(TDestination));

            var func = _configurationProvider.GetUntypedMapperFunc(new MapRequest(types, types));

            //Added to debug...
            var map = _configurationProvider.FindTypeMapFor(types);

            return (TDestination) func(source, null, _defaultContext);
        }
```

The Target property of the func variable always includes less members than those expected.

**Comment by lbargaoanu** [comment]
What about a nice gist, and we'll do the debugging? :)

**Comment by cryo75** [comment]
@lbargaoanu Tried that but the mapping worked because I had only a couple of mappings. I will give it another try.

**Comment by qswinson** [comment]
I'm having a similar issue with 5.0. The mapping used to work with 4.2.1 but now doesn't. Here's the gist that reproduces the problem https://gist.github.com/qswinson/20262e54ff597b757d7500a82301f4a9

**Comment by lbargaoanu** [comment]
Where is GeoCoordinate?

**Comment by qswinson** [comment]
System.Device assembly. The example project contains a reference to it.

**Comment by lbargaoanu** [comment]
A quick workaround is to disable constructor mapping if you don't use it.

**Comment by TylerCarlson1** [comment]
@cryo75 So what is Address object and does it have any CreateMap in your configuration.  And if so can you tell us what they are.

**Comment by qswinson** [comment]
@lbargaoanu How do you disable constructor mapping? I'm not finding that in the documentation.

**Comment by lbargaoanu** [comment]
[Choose an example](https://github.com/search?q=org%3AAutoMapper+DisableConstructorMapping&type=Code) :)
