### ISSUE TITLE
[Feature Request] Add MemberList.Intersection

### ISSUE THREAD

**Issue by ilmax** [AutoMapper/AutoMapper#1419]
Times ago, a very popular extension method were born to make it easier to allow mapping objects with different shape and ignoring all unmapped properties. We can find [various](http://stackoverflow.com/questions/954480/automapper-ignore-the-rest) examples [around](http://stackoverflow.com/questions/4987872/ignore-mapping-one-property-with-automapper).

Those methods is supposed to be replaced by the `MemberList` enum which ATM has the `Destination` and `Source` values, but is lacking the option to only map the properties that exists on both source and destination type.

Does it make sense to add a 3rd option to the previous the `MemberList` enum to simplify mapping configuration for this scenario?

Regards, Max.

**Comment by jbogard** [comment]
Ignore is about configuration validation. I opened a separate issue to do
MemberList.None, which means don't validate either side. Whatever matches,
maps. No configuration validation occurs.

**Comment by jbogard** [comment]
This one! #1416 

I think both of our ideas are the same - map the matching members, but don't validate either side, right?

**Comment by ilmax** [comment]
Sorry, for opening a dupe, closing because #1416 already covers my needs!
