### ISSUE TITLE
Bug: conventional mapping of nullable source to non-nullable destination

### ISSUE THREAD

**Issue by dmccaffery** [AutoMapper/AutoMapper#1428]
The following code behaves differently between AutoMapper 4.2.1 and AutoMapper 5.0:

```csharp
// source class
    public class Source
    {
        public Guid? Value { get; set; }
    }

    // destination
    public class Destination
    {
        public Destination()
        {
            this.Value = Guid.NewGuid();
        }

        public Guid Value { get; set; }
    }

    // configuration (from a profile)
    this.CreateMap<Source, Destination>(MemberList.Source);

    // execute the mapping
    var source = new Source();

    // get the result
    var result = mapper.Map<Destination>(source);
```

In AutoMapper 4.2.1, the value of result is determined by the value created in the constructor. The source value of NULL is ignored during mapping, since it cannot be mapped successfully to the destination type (which is NOT nullable).

In AutoMapper 5.0, the value of result is the default value of a GUID. It would appear that GetValueOrDefault() is being mapped to the destination.

Is this intended? If so, is their a conventional approach that resolves the issue, or must it be managed through conditionals or some explicit alternative?

**Comment by lbargaoanu** [comment]
Would you please remove the caps from the title?

**Comment by lbargaoanu** [comment]
@jbogard Thanks :)

**Comment by jbogard** [comment]
Well, I don't know about the 4.2.1 behavior, I'd say that was incorrect behavior. Why would it skip a mapping if the source value was null?

In any case, here's how you should map it now:

```
cfg.ForAllPropertyMaps(pm => pm.SourceType == typeof(Guid?) && pm.DestinationPropertyType == typeof(Guid),
    (pm, opt) => opt.UseDestinationValue());
cfg.CreateMap<Guid?, Guid>().ConvertUsing((src, dest) => src ?? dest);

cfg.CreateMap<Source, Destination>();
```

**Comment by jbogard** [comment]
I'm saying "use destination value" for all guid?->guid property maps, since by default AutoMapper in 5.0 does not try to access the destination value (it could throw). Then, I create a global map between guid? and guid to use the source value if it exists (it's not null), otherwise, use dest. I could probably check for guid.empty, but whatever.

**Comment by dmccaffery** [comment]
Thanks. This will work, although I do think that it's odd behavior. Mapping from a nullable to a non-nullable by assuming that the default value should be great and overriding any constructor defaults is, well, conventionally weird. In the future, it would be great if automapper had an option to ignore null when null cannot be successfully mapped without side effects. (Null to non-null).

I appreciate the help!

**Comment by dmccaffery** [comment]
*used not great

That's what I get for posting to GH from an iPhone. :(

**Comment by hoofa** [comment]
But, How to convert int?->int use dest if src is null? I tailed

cfg.CreateMap<int?, int>().ConvertUsing((src,dest) => src==null?dest:(int)src);

but throw Expression of type “System.Int32”  cannot be used for parameter of type "System.Nullable`1[System.Int32]”

**Comment by lbargaoanu** [comment]
@hoofa That works for me. A repro would help. Make a gist that we can execute and see fail.
