### ISSUE TITLE
BindingFailure in MVC6 project

### ISSUE THREAD

**Issue by mafshin** [AutoMapper/AutoMapper#1431]
I have a MVC6 project with AutoMapper but during the startup even before the call to `ConfigureServices` I get the `FileLoadException`

`
Additional information: The assembly with display name 'AutoMapper' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileLoadException: Could not load file or assembly 'AutoMapper, Version=4.2.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`

**Comment by lbargaoanu** [comment]
Try upgrading.
