### ISSUE TITLE
ITypeConverter - where is the DestinationValue property for the ResolutionContext

### ISSUE THREAD

**Issue by Silthus** [AutoMapper/AutoMapper#1432]
I have couple of custom ITypeConverters that use the `DestinationValue` of the `ResolutionContext` to access an existing value. How can I access the DestinationValue in Automapper 5.0.0?

**Comment by TylerCarlson1** [comment]
That functionality has been removed completely from ResolutionContext.  There is a discussion on how to re-implement the functionality on #1414, #1420, and another similar issue to #1390.
Note:  These are mostly for ITypeConverters where the source and destination type are the same.

I would recommend checking them out and seeing if the possible solutions provided would work for you.
