### ISSUE TITLE
AutoMapper nuget package installation failed with Microsoft.NETCore.UniversalWindowsPlatform version 5.2.0

### ISSUE THREAD

**Issue by yeasin90** [AutoMapper/AutoMapper#1439]
I have a UWP class library with **Microsoft.NETCore.UniversalWindowsPlatform version 5.2.0** nuget package installed (released very recently by Microsoft). In that class library, I tried to install AutoMapper version 5.0.0 via pakage manager console, but getting the below error : 
![bug](https://cloud.githubusercontent.com/assets/8789577/16569480/c2643972-4258-11e6-93d7-687097c3045f.JPG)
My UWP class library project has the below project.json :
```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```
I had to reverted back to **Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"**, then AutoMapper got installed

**Comment by jbogard** [comment]
Can you try the MyGet build?

**Comment by yeasin90** [comment]
@jbogard thanks for the reply and suggestions. I know it would not sound good, but can you kindly give me some suggestions on how to  get/download it from MyGet and use it in Visual Studio? (I googled a bit, but could not getting into it :( )

**Comment by yeasin90** [comment]
@jbogard : thanks. I am giving it a try by downloading from MyGet build

**Comment by yeasin90** [comment]
@jbogard : MyGet build was able to install along with **Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"**. Thanks. I am closing this issue :+1:

**Comment by jbogard** [comment]
Does it run too, in release mode?

**Comment by yeasin90** [comment]
Runs in Debug mode : (both x86 and x64). Also runs perfectly in Release(x86). Tried with Release(x64) - seems taking a bit time to run, probably for my pc configuration. I will give an update for Release(x64)
