### ISSUE TITLE
Nullable Flag Enum throws exception

### ISSUE THREAD

**Issue by CJdeVos** [AutoMapper/AutoMapper#1440]
Source and target are the same. This used to work in version 3.3.

`
class Program
    {
        static void Main(string[] args)
        {
            var config = ConfigureMapping();

            var mapp = config.CreateMapper();
            var source = new Simple()
            {
                Some = SomeEnum.A
            };
            var target = new Simple()
            {
                Some = SomeEnum.D
            };
            mapp.Map(source, target);
        }

        public static MapperConfiguration ConfigureMapping()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Simple, Simple>();
            });
            return config;
        }

        [Flags]
        public enum SomeEnum : int
        {
            A = 0,
            B = 1,
            C = 2,
            D = 4
        }

        public class Simple
        {
            public SomeEnum? Some { get; set; }
        }
    }

`

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by CJdeVos** [comment]
Does not seem to make a difference from the NuGet version. Looking at the version it also seems like NuGet and MyGet contain the same version - right? They only differ by number of downloads.

**Comment by lbargaoanu** [comment]
No, MyGet is the daily build.

**Comment by CJdeVos** [comment]
Then I guess it is not fixed yet. Thank you for your prompt replies.

**Comment by lbargaoanu** [comment]
This works with the latest build. You can close the issue.

**Comment by CJdeVos** [comment]
More than happy to close the issue for you, but I cannot confirm it actually works. The daily MyGet build at least still gives me the issue.

**Comment by lbargaoanu** [comment]
I don't know :) Add an assert, maybe I misunderstood.

**Comment by CJdeVos** [comment]
If you tried it and there is no exception thrown like the following, then it should be okay :)


`Additional information: GenericArguments[1], 'System.Nullable`1[ConsoleApplication6.Program+SomeEnum]', on 'TDestination Map[TSource,TDestination](TSource, System.Func`1[TDestination])' violates the constraint of type 'TDestination'.`

**Comment by CJdeVos** [comment]
![consoleapplication](https://cloud.githubusercontent.com/assets/3908361/16583343/1f624f54-42b5-11e6-9d78-76cfb3a2a4b8.png)

Uploaded the zip file as a .png... please download and change file extension :)

**Comment by lbargaoanu** [comment]
Do you have the prerelease box checked when looking at the MyGet feed?

**Comment by lbargaoanu** [comment]
This can be closed.
