### ISSUE TITLE
Complete example for start working with autoMapper 5 with asp.net core

### ISSUE THREAD

**Issue by arielcloud** [AutoMapper/AutoMapper#1441]
I am trying hard to find any complete example. is there one anywhere?
thanks!

**Comment by lbargaoanu** [comment]
Try asking on StackOverflow.

**Comment by jbogard** [comment]
There's nothing really too with ASP.NET Core that you need to worry about. It's just Mapper.Initialize and Mapper.Map.

**Comment by arielcloud** [comment]
Thanks!
