### ISSUE TITLE
ResolveUsing<> not being inherited by IncludeBase<>

### ISSUE THREAD

**Issue by BradRem** [AutoMapper/AutoMapper#1444]
I've constructed a gist to reproduce the problem here in VS: https://gist.github.com/BradRem/ed8a35b7923ca081c39da5c3375e4b8c

In the following code there exists a base class that includes a ResolveUsing<> mapping. There is also a mapping for an inherited class that calls IncludeBase<> to pick up the mappings from the parent class.  This works for all the .MapFrom mappings, but it fails to pick up the ResolveUsing mapping.  Calling AssertConfigurationIsValid will throw and exception stating the base class property is unmapped.

    void Main()
    {
        Mapper.Initialize(cfg => {
            cfg.CreateMap<SourceDto, DestinationDto>()
                .ForMember(dest => dest.Ident, opt => opt.MapFrom(x => x.Id))
                .ForMember(dest => dest.Number, opt => opt.ResolveUsing<CustomResolver, string>(src => src.NumberValue))
                ;
            cfg.CreateMap<SourceChildDto, DestinationChildDto>()
                .IncludeBase<SourceDto, DestinationDto>()
                //.ForMember(dest => dest.Number, opt => opt.ResolveUsing<CustomResolver, string>(src => src.NumberValue))
                ;
        });
    
        // uncomment this out to see that the ResolveUsing is not picked up
        //Mapper.Configuration.AssertConfigurationIsValid();

        var sourceChild = new SourceChildDto
        {
            Id = 1,
            NumberValue = "13",
            ChildField = "alpha"
        };
    
        // destination = { Ident: 1, Number: 0 /* should be 13 */, ChildField: "alpha" }
        var destination = Mapper.Instance.Map<DestinationChildDto>(sourceChild);
    
        //destination.Dump();
    }
    
    public class SourceDto
    {
        public int Id { get; set; }
        public string NumberValue { get; set; }
    }
    
    public class SourceChildDto : SourceDto
    {
        public string ChildField { get; set; }
    }
    
    public class DestinationDto
    {
        public int Ident { get; set; }
        public int Number { get; set; }
    }
    
    public class DestinationChildDto : DestinationDto
    {
        public string ChildField { get; set; }
    }
    
    public class CustomResolver : IValueResolver<string, int>
    {
        public int Resolve(string source, int member, ResolutionContext context)
        {
            return int.Parse(source);
        }
    }

**Comment by lbargaoanu** [comment]
A quick workaround is to use the ResolveUsing overload that takes a Func.
