### ISSUE TITLE
Update to 5.0 broke existing maps

### ISSUE THREAD

**Issue by sschneider1207** [AutoMapper/AutoMapper#1446]
I updated from 4.1 and I get the following errors from two of our existing profiles when asserting the configration is valid:
```
No coercion operator is defined between types 'System.Nullable`1[System.DateTimeOffset]' and 'System.Nullable`1[System.DateTime]'.
```
```
Expression of type 'System.Nullable`1[System.Boolean]' cannot be used for parameter of type 'System.Nullable`1[System.DateTimeOffset]'
```
For the first one, we have a `DateTimeOffset? -> DateTime?` map (as well as the other way around) defined that previously worked fine, for the second I have no clue what it is talking about.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by sschneider1207** [comment]
Unfortunately I can't add an alpha package from a different nuget feed to this project.

**Comment by lbargaoanu** [comment]
Then I guess you'll have to wait...

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jbogard** [comment]
5.0.1 is released.

**Comment by sschneider1207** [comment]
@lbargaoanu this was not fixed with 5.0.1

**Comment by jbogard** [comment]
5.0.2?

**Comment by sschneider1207** [comment]
Sorry didn't notice 0.2 was out, updated to it and I'm still having the same issue.

**Comment by xrkolovos** [comment]
me too

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by Gaulomatic** [comment]
Does not work with 5.2.0-alpha-01226.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by apopovsky** [comment]
I have a repro for this issue:
https://gist.github.com/apopovsky/73e220c9cbeec4dd8d89bfdd7e4575d6

I have a similar scenario that was working before. In this case the problem is using 
o.NullSubstitute() on a child object.

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Null-substitution.html

**Comment by apopovsky** [comment]
In my case, me (or whoever wrote the mapping), misinterpreted the Null substitution, passing an instance of the destination type instead of the source. Changing the instantiated type fixed the mapping.
I wonder how this ever worked. 
Thanks!

**Comment by lbargaoanu** [comment]
There were some changes around that, so it's possible it worked in some version.
