### ISSUE TITLE
Resolver it's not inherited properly if using ResolveUsing<T>

### ISSUE THREAD

**Issue by mcliment** [AutoMapper/AutoMapper#1447]
When using ResolveUsing<T>(), being T an IResolver<,> and then inheriting the map using .IncludeBase() the resolver is not inherited (if using a lambda resolver works properly as expected).

See this gist for a full example: https://gist.github.com/mcliment/39882d316e5a57e07af7dd9ef289d671

The workingConfig is equivalent to the failingConfig but the latter will not validate unless the commented line is uncommented.

**Comment by lbargaoanu** [comment]
Duplicate of #1444. You can close it.
