### ISSUE TITLE
Mapper.Initialize throw ArgumentNullException

### ISSUE THREAD

**Issue by sky-code** [AutoMapper/AutoMapper#1453]
Steps to reproduce
Create ASP.NET Core Web Application (.NET Framework)
install automapper 5.0.0
add test classes 
```cs
    public class TestEntity
    {
        public string SomeData { get; set; }

        public int SomeCount { get; set; }

        public ICollection<string> Tags { get; set; }
    }

    public class TestViewModel
    {
        public string SomeData { get; set; }

        public int SomeCount { get; set; }

        public string Tags { get; set; }
    }
```
and add Initialize call as example into Startup.ConfigureServices
```cs
        public void ConfigureServices(IServiceCollection services)
        {
            Mapper.Initialize(c =>
            {
                c.CreateMap<TestEntity, TestViewModel>();
            });
            // Add framework services.
            services.AddMvc();
        }
```
Run it and you get System.ArgumentNullException, problem here is exception itself without any details about where is problem.
When I update AutoMapper in my project with 50+ mapping find what is real problem not so easy, add some human exception with details where and what produce exception

**Comment by sky-code** [comment]
Here problem in Tags property, if you add `ForMember(d => d.Tags, c => c.Ignore())` but in AutoMapper 4.X same code not throw any exception

**Comment by jbogard** [comment]
What type is Tags?

**Comment by sky-code** [comment]
in my project is `ICollection<Tag> Tags` custom entity, here for example `ICollection<string> Tags` get same exception, source type is `ICollection<T>` and dest `string` I think exception occurred because of type mismatch

**Comment by jbogard** [comment]
Stack trace?

**Comment by jbogard** [comment]
I'm looking to at least figure out where to put the exception logic here.
