### ISSUE TITLE
AutoMapper configuration became *really* slow on 5.0.0

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1455]
After all the help I got with upgrading AutoMapper to 5.0.0, I've got two problems that I might be able to work around, but that are really annoying. I'll file separate issues for them.

The first one is that configuration (i.e. the call to `Mapper.Initialize(cfg => ...)` now takes insane amounts of time compared to before. We have quite a lot of mappings (searching for `CreateMap` in the solutiong yields some 670 results - a lot of mappings from DTO's to entities and back again) but that was never a problem before; config time was negligible. Now it takes 7-10 seconds.

've not been able to reproduce this outside of our real code base, but I assume that's just because I haven't tried with a large enough set of mappings. Our bootstrapping routine is very simple; basically a static class with a static method, that is called on service instantiation.

```c#
public static class Bootstrapper
{
     // before upgrade
     public static void Initialize()
     {
         ServiceABootstrapper.Bootstrap();
         ServiceBBootstrapper.Bootstrap();
         // ...
     }

     // after upgrade
     public static void Initialize()
     {
         Mapper.Initialize(cfg => {
             ServiceABootstrapper.Bootstrap(cfg);
             ServiceBBootstrapper.Bootstrap(cfg);
             // ...
         });
     }
}
```

and the service bootstrappers were very similar:

```c#
public static class ServiceABootstrapper
{
    // before upgrade
    public static void Bootstrap()
    {
        Mapper.CreateMap<Foo, Bar>();
        // ...
    }

    // after upgrade
    public static void Bootstrap(IMapperConfigurationExpression cfg)
    {
        cfg.CreateMap<Foo, Bar>();
        // ...
     }
}
```

Is there something inherent in the way 5.0.0 does the configuration that becomes exponentially more slow with many mappings? Is there some "easy fix" I can apply to speed this up?

Even if we only have to do this once per app domain, adding 10 seconds to the cold-start time for no  apparent reason really doesn't feel good...

**Comment by lbargaoanu** [comment]
Profile it. If you see Lambda.Compile, that's more or less by design.

**Comment by tlycken** [comment]
OK. Is there any way to initialize AutoMapper 5.0.0 that doesn't rely on being slow?

**Comment by lbargaoanu** [comment]
:)

**Comment by jbogard** [comment]
We haven't profiled large configurations yet, just made the execution
faster.

**Comment by lbargaoanu** [comment]
@tlycken You can record an etl trace with something like PerfView or WPR (in release of course) and we could take a look at it. But a repro would be best. I'm able to make 2K random type maps in 1.3 seconds.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jbogard** [comment]
I did some benchmarking on a big project internally. This one has 211 maps defined, took roughly 8.5 seconds to call Mapper.Initialize in 4.x, and 8.5 seconds in 5.0.2. Just about the same, but I'd say still slow. @lbargaoanu since this was a client system, it has complex maps, resolvers, lots of MapFroms etc. Probably a more realistic example, but, something I can profile.

**Comment by lbargaoanu** [comment]
Yes, you need real data to do something about it.
