### ISSUE TITLE
AutoMapper 5.0.0 introduces runtime errors that AssertConfigurationIsValid doesn't catch

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1457]
I mentioned in #1455 that I have two issues since upgrading to 5.0.0. Here's the other one.

There are quite a lot of mappings in our project that are, by the standards of 5.0.0, pretty broken. For one thing, there are static calls to `Mapper.Map()` inside the configurations; those I'm working on removing.

But there are also mapping targets which have private constructors written explicitly to allow AutoMapper 2.2.1 to construct the objects and then map properties from some DTO. Many of these now throw runtime errors at mapping time with the pretty uninformative error message

> System.ArgumentException: MyProject.Foo.DestinationType needs to have a constructor with 0 args or only optional args

Since these errors aren't discovered by the configuration verification, we're pretty screwed; we don't have test coverage that excercises all possible mappings, so we won't find all of these until someone stumbles on them in production. Unless this can be resolved, this is pretty much a dealbreaker for our upgrade :(

**Comment by lbargaoanu** [comment]
Show me the code :)

**Comment by tlycken** [comment]
The code is part of our application, and I don't have the rights to show it verbatim.

But the problem I'm trying to report is not (only) that my mappings broke, but also that a) the test tooling doesn't discover this, and b) that the error message contains very little information. Before any specific classes or mapping configurations are relevant, I have to be able to find the ones that are broken...

**Comment by lbargaoanu** [comment]
A repro is all we need.

**Comment by tlycken** [comment]
Here's a program that shows the broken behavior of our config. I would have hoped that this test would fail on the call to `AssertConfigurationIsValid()`, but it doesn't - instead, it fails with an `ArgumentException` as the one above when the actual mapping is performed. No details on why the mapping configuration is insufficient are given.

```c#
public class Test
{
    [Fact]
    public void IllustrateProblem()
    {
        Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<Dto, Entity>();
        });

        Mapper.Configuration.AssertConfigurationIsValid();

        Console.WriteLine("Mapper test OK");

        Mapper.Map<Entity>(new Dto { Foo = "bar" });
    }
}

class Dto
{
    public string Foo { get; set; }
}

class Entity
{
    public string Foo { get; }
    public bool Bar { get; }

    public Entity(string foo, bool bar)
    {
        Foo = foo;
        Bar = bar;
    }
}
```

**Comment by lbargaoanu** [comment]
This fails because Bar is unmapped.

**Comment by tlycken** [comment]
I know. That's not the issue here :)

The issue is that neither `AssertConfigurationIsValid()` nor the exception message at runtime tells me that it's because `Bar` is unmapped.

**Comment by tlycken** [comment]
To be very explicit: here's the entire output I get from the test above:

```
System.ArgumentException
ConsoleApplication13.Entity needs to have a constructor with 0 args or only optional args
Parameter name: type
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at ConsoleApplication13.Test.IllustrateProblem() in C:\Users\TLY01\Documents\Visual Studio 2015\Projects\ConsoleApplication13\ConsoleApplication13\Program.cs:line 21
```

**Comment by lbargaoanu** [comment]
We've had this conversation before. The constructor doesn't match and that's not an error. Maybe you want a new feature or smth that would check this for you, but that's a different story, There is no bug here.

**Comment by jbogard** [comment]
Yep, that's a bug or missing feature here, I don't think configuration
validation checks ctors at the moment.

**Comment by lbargaoanu** [comment]
@jbogard In a default configuration, this cannot be an error. I can have all the constructors I want. They don't have to match from AutoMapper's perspective.

**Comment by tlycken** [comment]
@lbargaoanu If so, it's a regression that my mappings are no longer valid.

Either the constructors have to match, and then AutoMapper should be able to tell me why they don't, or they don't have to match, and then AutoMapper shouldn't complain when it tries to carry out the mapping.

**Comment by lbargaoanu** [comment]
It complains because it has to create an instance and it cannot. It could do it with a default constructor. You can also disable constructor mapping, but I'm not sure if that could help somehow.

**Comment by jbogard** [comment]
Right, and configuration validation today does not touch constructors, but there's no way to actually construct it. I don't think this is a regression - supporting constructors is rather new. Rather an oversight in validation.

**Comment by tlycken** [comment]
Well, if I turn off constructor mapping (with `cfg.DisableConstructorMapping()` before I do anything else), mapping still fails; with the same error as above if I keep everything as it was before the upgrade, and by not mapping anything (i.e. the behavior of #1456) if I add a private default constructor.

**Comment by lbargaoanu** [comment]
And that makes sense :)

**Comment by lbargaoanu** [comment]
The MyGet build has the fix now.

**Comment by tlycken** [comment]
Using the latest build from MyGet (5.0.1-alpha-01151) I had to fix some breaking changes on the `IValueResolver` interface (it takes an extra type parameter now), and after that I saw the same behavior as with 5.0.0.

On the plus side, bootstrapping time went down to just under 1.3 seconds (and this is debug mode), so I guess that problem is at least partly solved in the latest versions :)

**Comment by jbogard** [comment]
What same behavior? AssertConfigurationIsValid missing things?

**Comment by tlycken** [comment]
Yes, but that I expected.

But also the exception about constructors thrown mapping-time, which means that even with constructor mapping turned off, the old mappings are still invalid.

**Comment by jbogard** [comment]
Not anymore, this is fixed to catch at validation time

**Comment by tlycken** [comment]
Yeah, the new validation errors made it much easier to fix the invalidated mappings. It would have been even nicer if the validation also pointed out *why* the existing constructors weren't satisfiable (i.e. which parameters couldn't be mapped to) but that's definitely an improvement request :)

Thanks a lot for the speedy help on this!
