### ISSUE TITLE
Byte array conversion throw System.NotSupported Exception

### ISSUE THREAD

**Issue by atul221282** [AutoMapper/AutoMapper#1459]
In Entityframework code first I have classes with timestamp field to maintain coincurrency when I am trying to retrieve data  without AuotMapper mapping it work fibe but when I try to use mapping then it produce System.NotSupported Exception in my output window. My mapping code is below

 ```
Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<ClientPhone, ClientPhoneViewModel>();
                cfg.CreateMap<ClientRecord, ClientRecordViewModel>();
            });

            Mapper.Map<ClientPhone, ClientPhoneViewModel>(new ClientPhone());
            Mapper.Map<ClientRecord, ClientRecordViewModel>(new ClientRecord());

//My viewmodel classess
public abstract class BaseViewModel
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }

    }

 public class ClientRecordViewModel : BaseViewModel
    {
        public string Name { get; set; }
        public string Address { get; set; }

        public ICollection<ClientPhoneViewModel> ClientPhones { get; set; }
    }

 public class ClientPhoneViewModel:BaseViewModel
    {
        public string ClientRecordName { get; set; }
        public string PhoneNumberNumber { get; set; }

        public int ClientRecordId { get; set; }

        public int PhoneNumberId { get; set; }

    }



my query to access it which throws an exception
` sdUow.ClientRecords.GetAll().ProjectTo<ClientRecordViewModel>().ToList();`

If i remove  RowVersion from baseviewmodel it works then

Following is the error I am getting

LINQ to Entities does not recognize the method 'Byte[] ToArray[Byte](System.Collections.Generic.IEnumerable`1[System.Byte])' method, and this method cannot be translated into a store expression.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by atul221282** [comment]
@lbargaoanu Can you elaborate bit more as I have just started using Automapper

**Comment by ShenglinGuo** [comment]
I am experiencing the same issue, where I have a EF timestamp column RowVersion (byte[]) mapping to a model object RowVersion (byte[]). This used to work prior to upgrade to version 5.0

efDataContext.[MySourceObject].AsQueryable().ProjectTo<MyDestModel>(Mapper.ConfigurationProvider), 

Mapper is injected instance of IMapper

Error Message
LINQ to Entities does not recognize the method 'Byte[] ToArray[Byte]

**Comment by atul221282** [comment]
@ShenglinGuo I am using 5.0.0 also

**Comment by ShenglinGuo** [comment]
We are upgrading a median size project running AutoMapper 4.1.1 and it was using the static method model. I have applied 4.2.1 to another project with instance injection worked very well, decided to upgrade this bigger application as well. Then found v5 is release. Not worked out so well for us. I have just downgrade to 4.2.1 and kept most of the instance injection changes and the application is running happily again. Pretty sure this issue apply only to v5.0 .

**Comment by atul221282** [comment]
Just tested the same code with 4.2.1 and it works like a charm so this is an issue with latest release then

**Comment by jbogard** [comment]
It is, this is fixed in the MyGet build. 5.0.1 release to come very soon (this week, hopefully earlier).

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by atul221282** [comment]
well it should be once it is tested with latest release. Just asking?

**Comment by jbogard** [comment]
It's a duplicate.
