### ISSUE TITLE
Issue with null child objects with EF Core

### ISSUE THREAD

**Issue by maganuk** [AutoMapper/AutoMapper#1462]
I'm the midst of trying to upgrade an EF6 / ASP.Net (Automapper 4) application to EF Core (Automapper 5).

What used to work was:
```
public class Parent
{
    public int ID { get; set; }
    public string ParentTitle { get; set; }
    public int? ChildObjectID { get; set; }        //BREAKING CHANGE
    public Child ChildObject { get; set; }
}

public class Child
{
    public int ID { get; set; }
    public string ChildTitle { get; set; }
}

public class ChildDTO
{
    public int ID { get; set; }
    public string ChildTitle { get; set; }
}

public class ParentChildDTO
{
    public int ID { get; set; }
    public string ParentTitle { get; set; }
    public ChildDTO Child { get; set; }
}
```
In our configuration we would do:
```
cfg.CreateMap<Child, ChildDTO>();
cfg.CreateMap<Parent, ParentChildDTO>();
```
We would do:

`Query.ProjectTo<ParentChildDTO>()` on an `IQueryable<Parent>` and it would all work like magic. If the child object was null then `ParentChildDTO.Child` would be null.

Now with Automapper 5 and EF Core the same code gives an Argument types do not match exception.

This also happens if you are trying to map an ICollection of objects which is empty. (Value cannot be null exception).

What works is `.MapFrom(c=>c.ChildID ! = null ? c.Child : null)`. But we have about 500 mappings and it would be a no go to do this for each and every mapping.

I have also tried to get the nightly build to no avail.

Any suggestions? Thanks

**Comment by lbargaoanu** [comment]
GitHub ate your code. Make a gist that we can execute and see fail.

**Comment by lbargaoanu** [comment]
And you can try the MyGet build.

**Comment by maganuk** [comment]
[https://gist.github.com/maganuk/eb29c01777e32a505cde7cf6bc437651](url)

Heres the gist.

As mentioned, I've tried the MyGet build as well. That doesn't work either. 

Thanks

**Comment by lbargaoanu** [comment]
You certainly cannot execute that gist. If I fill in the blanks it works for me.

**Comment by maganuk** [comment]
Apologies, was just trying to give you an extract of the code. Will make an Net core and post it shortly.

**Comment by lbargaoanu** [comment]
Usually just executable code is enough.

**Comment by jbogard** [comment]
A dotnetfiddle also works well.

**Comment by jbogard** [comment]
Are you sure it's not EF Core that's broken here? There are a TON of things that don't work in there. Have you tried AutoMapper 5.0 and EF6?

**Comment by maganuk** [comment]
Updated the gist. Haven't tried with EF6. Let me give that a shot.

**Comment by maganuk** [comment]
Works fine with Automapper 5.0 and EF6 in .NET Core.

**Comment by jbogard** [comment]
Perhaps, but man you're brave to go with EF Core, you're not even supposed to use async!

My advice - if this is a production app, wait until EF Core bakes a little bit more unless you need EF to run in a Linux container or something crazy.

Do you know *what* would need to change?

**Comment by maganuk** [comment]
Not as yet. Trying the nightly builds for EF Core to see if that helps.

I managed to upgrade 99% of the application using a repository model to EF Core. Async indeed is slow but am hoping that'll get fixed in 1.0.1, and indeed wanted to run it in a linux container.

**Comment by jbogard** [comment]
Another option is to open a GH issue in the EF Core repo. They might already have something for this issue.

**Comment by jbogard** [comment]
One other thing - a stack trace would be helpful for the exception.

**Comment by maganuk** [comment]
Heres the stack trace. Was just thinking of opening an issue as well. Nightly build throws a different error.

**Comment by jbogard** [comment]
OK that's what I was afraid of. The exception comes from deep inside EF Core, not AutoMapper.

One thing to check is to try a manual Select in EF's LINQ. `context.People.Select(p => new PersonDto { /* your manual projection here */});` and make it match more or less what AutoMapper builds out. It's about the best I can do when a LINQ provider craps out on me.

**Comment by maganuk** [comment]
Yes the manual projection works and indeed it is an issue with EF core. I think I'll hold off for a bit to see if things are fixed with ef 1.0.1.

Thanks so much for your help. Will post the issue on EF as well. Closing the issue.

**Comment by jbogard** [comment]
In the meantime, you can still just use Mapper.Map. Not as fun, I know, but it can at least get you going.

Is there an issue I can point people to on EF Core if new folks have this problem?

**Comment by jbogard** [comment]
Well, EF Core doesn't support lazy loading atm, so you'll get an exception right quick.

**Comment by maganuk** [comment]
Yup.
