### ISSUE TITLE
Null flattening has changed in 5.0

### ISSUE THREAD

**Issue by kogir** [AutoMapper/AutoMapper#1469]
The following code works with 4.2.1 but not with 5, and I can't seem to figure out how to configure 5 to provide the old behavior. Is there a supported way to get the old behavior back, short of manually mapping every affected property in every affected type?

I've tried building from master, re-reading the docs and release notes, and even stepping into a debug build with symbols, but haven't been able to figure it out yet.

```C#
using System;
using AutoMapper;

namespace AutoMapperTest {
  public class Account {
    public long Id { get; set; }
  }

  public class Issue {
    public Account Assignee { get; set; }
  }

  public class IssueDTO {
    public long? AssigneeId { get; set; }
  }

  static class Program {
    static void Main(string[] args) {
      var config = new MapperConfiguration(cfg => {
        cfg.CreateMap<Issue, IssueDTO>(MemberList.Destination);
      });
      var mapper = config.CreateMapper();

      var source = new Issue();
      var result = mapper.Map<IssueDTO>(source);

      Console.WriteLine(typeof(MapperConfiguration).Assembly.FullName);

      string actual;
      if (result.AssigneeId == null) {
        actual = "null";
      } else {
        actual = result.AssigneeId.ToString();
      }
      Console.WriteLine($"Expected: null, Got: { actual }");
      Console.ReadKey();
    }
  }
}
```

**Comment by kogir** [comment]
Using `git bisect` I was able to narrow it down to (seemingly) commit 221e2af34958d0de3cf1121d9b95f36767d39c01

I'll see if I can determine if this is an intentional or accidental change in behavior.

**Comment by TylerCarlson1** [comment]
Yea this looks accidental when switching to expressions for performance gain.  Also there's appears to  be no unit test so that's why it wasn't caught.

**Comment by jbogard** [comment]
Yep, the expression does not take into account the destination type, it just does the default of the resolved type.

**Comment by kogir** [comment]
I'm still familiarizing myself with the codebase but may have some time tomorrow to try my hand at a PR. Thanks for the quick confirmation 😄

**Comment by TylerCarlson1** [comment]
@kogir I'm looking at it right now.

Looks doable just need to refactor a few things, and @jbogard it looks like some more obsolete code can be deleted :)

**Comment by jbogard** [comment]
lol great. Well I think this might be the last one we include in 5.0.1 to get it out the door.
