### ISSUE TITLE
Bug: AutoMapper 5.0 nuget doesn't contain xml files with documentation

### ISSUE THREAD

**Issue by IvanYur4enk0** [AutoMapper/AutoMapper#1473]
Following folders contains only dlls:

packages\AutoMapper.5.0.0\lib\net45
packages\AutoMapper.5.0.0\lib\netstandard1.1
packages\AutoMapper.5.0.0\lib\netstandard1.3

Xml files with documentation are missed.

**Comment by jbogard** [comment]
Sigh. The project.json schema changed *again* from RC2 to RTM preview 1 to preview 2 tooling.

**Comment by jbogard** [comment]
Fixed in 5.0.2! Thanks for the heads up!
