### ISSUE TITLE
Bug: Type converters interface in 5.0 differs with 4.x version and documentation

### ISSUE THREAD

**Issue by IvanYur4enk0** [AutoMapper/AutoMapper#1474]
Following [documentation](https://github.com/AutoMapper/AutoMapper/wiki/Custom-type-converters) contains destination in ITypeConverter interface

But I can't access current destination object if it is already exists from interface directly, like documentation says or from context object.

```
public class Source
{
}

public class Destination
{
}

public class SourceToDestinationConverter : ITypeConverter<Source, Destination>
{
	public Destination Convert(Source source, ResolutionContext context)
	{

	}
}
```

**Comment by lbargaoanu** [comment]
Feel free to update it.

**Comment by IvanYur4enk0** [comment]
I am using last nuget version 5.0.0, i can't see any new versions. Target platform -> .NetFramework, not Core.

**Comment by lbargaoanu** [comment]
Update the doc I mean :)

**Comment by IvanYur4enk0** [comment]
File 'AutoMapper/src/AutoMapper/ITypeConverter.cs' already have valid interface and it was committed 2 to days ago. And I think we should access already created destination object in ITypeConverter like we are doing it in 4.x version, but not from context -> from parameter directly. So documentation is correct i think.

**Comment by IvanYur4enk0** [comment]
But is very strange for me that this alpha version of auto mapper with some broken features was committed to public nuget.

**Comment by lbargaoanu** [comment]
Many things surprise me too :)

**Comment by jbogard** [comment]
Well it's quite hard to push a NuGet and immediately have all the docs
updated. So I update them slightly ahead of a release.

**Comment by jbogard** [comment]
5.0.1 released, matching docs.
