### ISSUE TITLE
   A problem to install version 5 on vs 2015

### ISSUE THREAD

**Issue by DavidOs55** [AutoMapper/AutoMapper#1477]
Hi,
I have a problem to install version 5.0 in vs 2015 but succeeded with version 4.2.1
![image](https://cloud.githubusercontent.com/assets/20335174/16648113/23fa2168-443b-11e6-8298-d758e32b0de2.png)

Thanks
David

**Comment by lbargaoanu** [comment]
It works for most people, so the problem may be on your end.

**Comment by jbogard** [comment]
What version of NuGet?

**Comment by DavidOs55** [comment]
Package Manager Console Host Version 3.0.0.0

**Comment by jbogard** [comment]
Hmmm that sounds really old. The latest NuGet for VS 2015 is 3.4.3, have you tried upgrading your NuGet extension inside VS?

**Comment by DavidOs55** [comment]
Thanks for your advice. That solved the problem
