### ISSUE TITLE
Automapper 5 and DynamicMap, I can't find its equivalent

### ISSUE THREAD

**Issue by fruitbatinshades** [AutoMapper/AutoMapper#1479]
I'm trying to map a DataTable to a list which I used DynamicMap<T,U> for previously. Is this functionality still available in 5?

**Comment by jbogard** [comment]
I didn't know you could go DataTable to List. But you need to create maps on the fly:

```
Mapper.Initialize(cfg => cfg.CreateMissingTypeMaps = true);
```

That way you don't have Mapper.Map and Mapper.DynamicMap, just Mapper.Map.

**Comment by fruitbatinshades** [comment]
Ahh! Thats the missing piece. I meant List<Dictionary<string,object>> ;)
