### ISSUE TITLE
Conditional mapping from int to int? causes error in 5.0.1

### ISSUE THREAD

**Issue by crowbarsolutions** [AutoMapper/AutoMapper#1481]
I have a mapping like this:

	CreateMap<Order, OrderVm>()
		.ForMember(dest => dest.CustomerId, opt => opt.MapFrom(src => (src.Customer != null) ? src.Customer.Id : (int?)null));

destination.CustomerId is of type int?
source.Customer.Id is of type int

Basically, if the Customer property in the source object is null, set the destination CustomerId property to null, otherwise set it to the Id property inside the source Customer object.

In version 5.0.0 and below this would fine but in 5.0.1 I get the following error:

> System.InvalidOperationException : Rewriting child expression from type 'System.Int32' to type 'System.Nullable`1[System.Int32]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite.

Is there a different way of achieving this?

**Comment by jbogard** [comment]
Yes, remove the MapFrom. It's not needed.

**Comment by crowbarsolutions** [comment]
So there are some smarts built in as far as navigating through objects, so if a NullReferenceException is hit it will simply set the destination property value to null?

If I have a mapping like this:

	.ForMember(dest => dest.VehicleType, opt => opt.MapFrom(src => (src.Vehicle != null) ? src.Vehicle.Type : null))

Where dest.VehicleType is a string and src.Vehicle.Type is a string, I can simplify it to:

	.ForMember(dest => dest.VehicleType, opt => opt.MapFrom(src => src.Vehicle.Type))

**Comment by TylerCarlson1** [comment]
@crowbarsolutions I think it would unless you have `cfg.AllowNullDestinationValues = false;`
#1469 is the reason it got changed, because it seemed to work before in a previous version.

**Comment by TylerCarlson1** [comment]
Oh and that's flattening functionality with navigating through object's properties.  What it does is navigate if names match, which is why you don't need the MapFrom call.  And for flattening properties and MapFrom calls, it auto adds the null check for you, so it doesn't throw a NullReferenceException.

**Comment by jbogard** [comment]
You can simplify it to nothing, AutoMapper automatically adds those null checks in for flattening.

**Comment by crowbarsolutions** [comment]
Thanks, it's working great now. I prefer to keep my explicit `MapFrom(...)` when having to navigate a few levels deep to get my source property. That way if any of the intermediate class names get changed in the future it'll prevent headaches . It's nice to know that the convenience is there though.

I imagine using the explicit `MapFrom(...)` is a touch faster than relying on AutoMapper to match the names when dealing with multi-level property navigation?

**Comment by TylerCarlson1** [comment]
@crowbarsolutions On Configuration Yes.  On Execution NO.

**Comment by jbogard** [comment]
@crowbarsolutions for the headaches, AssertConfigurationIsValid will find those issues. I designed AutoMapper explicitly for this scenario of flattening automatically.
