### ISSUE TITLE
Failure mapping from short? to short

### ISSUE THREAD

**Issue by ccbristo** [AutoMapper/AutoMapper#1483]
(I don't think this is a duplicate of [1481](https://github.com/AutoMapper/AutoMapper/issues/1481), this is going in the opposite direction.)

After upgrading from 5.0.0 to 5.0.1 (or 5.0.2), I am getting this error:

System.InvalidOperationException: Rewriting child expression from type 'System.Int16' to type 'System.Nullable`1[System.Int16]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite..

(As a side note, the issues I've run into during Seal have been somewhat difficult to diagnose, e.g. having to comment out mappings until I narrow in on the one that caused the problem. Is it possible to add more diagnostic information like source/dest type/member into the exceptions? I can create a separate issue for this if necessary.)

Here is an example mapping:
```
[TestClass]
public class UnitTest1
{
	static UnitTest1()
	{
		Mapper.Initialize(cfg =>
		{
			cfg.CreateMap<Source, Target>()
				.ForMember(t => t.X, opts => opts.MapFrom(s => s.X > 0 ? s.X : default(short?)));
		});
	}

	[TestMethod]
	public void IncludedMappings()
	{
		var src = new Source
		{
			X = 0
		};

		var dest = Mapper.Map<Source, Target>(src);

		Assert.AreEqual(src.X, dest.X);
	}
}

class Source
{
	public short X { get; set; }
}

class Target
{
	public short? X { get; set; }
}
```
Another interesting aside is that the exception is significantly different if mapping int instead of short:
```
System.InvalidOperationException: The binary operator GreaterThan is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Int32'..
    at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.GreaterThan(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
```

**Comment by jbogard** [comment]
That's an odd mapping. Have you tried ConvertUsing? I would think you'd want every short -> short? to have the same logic.

**Comment by TylerCarlson1** [comment]
@jbogard Yea looks like the Nullable change conflicts with MapFrom's expressions that aren't simple cases.

**Comment by ccbristo** [comment]
Yes, it is a strange mapping.  :)

I'll look to see how many cases we've got that fall into this to see if ConvertUsing is an option.

**Comment by jbogard** [comment]
Another option is to use ResolveUsing - that's Func based instead of Expression based. AutoMapper tries to rewrite the expressions to be null-safe, which doesn't look like what you want.

**Comment by TylerCarlson1** [comment]
@jbogard The fix to this would be something similar to #1482.  Have to change the (short)0 from to (short?)0. based on binary operator.

@ccbristo About seal having better diagnostics.  I don't think they should, since they are going deep into the internals and it's usually something wrong with AutoMapper that needs to be fixed vs something wrong with how user used it.  Seal should never fail, but obviously it did, so IDK.

**Comment by jbogard** [comment]
@TylerCarlson1 I wonder if the more obvious fix is to only rewrite the expression to handle nulls for flattening redirection. If it's only member access. I'm not sure.

**Comment by ccbristo** [comment]
@TylerCarlson1 I had similar thoughts, especially since one of the exceptions came from within the BCLs.  But during this initial upgrade, it would sure be nice!

**Comment by TylerCarlson1** [comment]
@jbogard I guess you could eliminate null checking for CustomExpressions, and then it's on the user to do their own null checking.
Or Possibly Better Yey.  Have the CustomExpresssions destination type be the source expression type vs the destination expected type.

Either way should work for both this and #1483.  It's just do you want to forgo adding null checks on custom expressions or not?

@ccbristo As @jbogard has said these things should of been caught in the beta, but no one tested it, so it shows up in initial release.

**Comment by jbogard** [comment]
With option number 2, #1469 would fail. It failed because the null was translated to a 0, then set on the nullable to 0 as opposed to null.

Part of the problem here are nullables, and that I can't use a null propagating operator in expressions. That would *greatly* simplify things, but alas, it isn't there.

**Comment by TylerCarlson1** [comment]
No option 2 wouldn't fail #1469 cause it's flattening and option 2 doesn't change flattening logic, just CustomExpressions eg. MapFrom, where these new issues are coming from.
CustomExpression will do null propagation like it did before #1469 where as flattening will keep it's fix for that PR.

Also as far as I know the Elvis operator is just shorthand for what we are doing now.  The REAL annoyance is that you can compare int to int? and the compiler can figure it out, but with expressions you have to manually do the conversions yourself.
