### ISSUE TITLE
Problem with mapping DTOs onto their POCO class in 5.02

### ISSUE THREAD

**Issue by levitatejay** [AutoMapper/AutoMapper#1486]
I've been using the following code successfully with Automapper to do entity updates in my service layer:
```
        public async Task<UserDto> UpdateAsync(UserDto dto)
        {
            var existingAccount = await _repo.Get()
                .Where(u => u.Id == dto.Id)
                .Include(u => u.Permissions)
                .FirstOrDefaultAsync();

            if (existingAccount != null)
            {
                Mapper.Map(dto, existingAccount);

                await _repo.SaveChangesAsync();
                return Mapper.Map<UserDto>(existingAccount);
            }
            return null;
        }
```
Basically I get the entity from the database, map the DTO onto it and then save the changes

I've just updated to 5.02 which fixed some issues I had but now the code above is throwing the following error when I call save changes:

> "The instance of entity type 'UserPermissions' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context."

All my update methods seem to work fine unless they have a one to one relationship with another entity. For example User's Permissions and Customer's Licence

I'm not sure if there is an intended change that broke this workflow or if its a bug...

**Comment by lbargaoanu** [comment]
Narrow it down and make a gist without the DB stuff that we can execute and see fail. We're interested in just what changed in the mapping that causes this for you.

**Comment by jbogard** [comment]
I don't map back into entities, so I haven't seen something like this. Can
you post your POCOs and DTOs? I can't really tell anything without them.

**Comment by levitatejay** [comment]
Here is an example of a POCO->DTO that is affected:

```
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public Licence Licence { get; set; }
        public List<ApplicationUser> Users { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public DateTimeOffset ModifiedOn { get; set; }
    }

    public class Licence
    {
        [Key]
        [ForeignKey("CustomerId")]
        [Required]
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }

        [Required]
        public DateTimeOffset ExpireDate { get; set; }
    }
```

The above maps to the following:
```
    public class CustomerDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public LicenceDto Licence { get; set; }
    }
    public class LicenceDto
    {
        [Required]
        public int CustomerId { get; set; }
        [Required]
        public DateTimeOffset ExpireDate { get; set; }
    }
```

I have the exact same issue with a similar mapping where an `ApplicationUser `has a one to one relationship with `UserPermissions` (just like the Customer & Licence relationship above) 

> Narrow it down and make a gist without the DB stuff that we can execute and see fail. We're interested in just what changed in the mapping that causes this for you.

The issue occurs with Entity Framework Core's change tracking so I can't replicate the issue without the DB stuff. The code in my original post works on `5.0.0-beta-1` which leads me to believe that something changed between `5.0.0-beta-1` and `5.02` related to one-to-one mappings that is causing the problem.

**Comment by lbargaoanu** [comment]
Try setting PreserveReferences on your map.

**Comment by marcoerni** [comment]
We have the same issue using NHibernate. If we map complex object trees into existing destination instances, child objects on the existing destination are getting recreated. This leads into issues when dealing with NHibernate sessions.
Using PreserveReferences() did not solve the issue. With the 5.0.0-Beta release it worked correctly with and without using PreserveReferences(). In version 4.2.1 it also worked as expected.
I have attached a solution containing three unit test projects illustrating the issue with all the mentioned versions of AutoMapper.
[AutoMapperIssue.zip](https://github.com/AutoMapper/AutoMapper/files/365509/AutoMapperIssue.zip)

**Comment by lbargaoanu** [comment]
PreserveReferences was just a wild guess :) But now that we have a repro...

**Comment by lbargaoanu** [comment]
UseDestinationValue is now false by default, so you can fix it, I'm not sure whether this should work without setting it.

     configuration.CreateMap<Source, Destination>().ForMember(d=>d.Child, o=>o.UseDestinationValue());

**Comment by jchannon** [comment]
I raised a question on SO - http://stackoverflow.com/questions/38696371/empty-property-value-after-automapper-v5-upgrade

And the fix was to use the `ForMember(d=>d.Child, o=>o.UseDestinationValue());` code but not sure this should be a requirement as it worked without it in v3 & v4.

Thoughts?

**Comment by lbargaoanu** [comment]
It's the right fix. When you pass the top destination value, you don't need to set it. In this case you do. It worked before because UseDestinationValue was true by default. But that was wrong.

**Comment by jchannon** [comment]
Actually I just pulled 5.1.0-alpha-01191 and it works as before, kinda.  My
code in the SO post works without UseDestinationValue but the code in the
docs still needs it. I'm not really sure of the diff between my code and
the docs code as they look pretty much the same

**Comment by lbargaoanu** [comment]
I see (true, null).

**Comment by jchannon** [comment]
Weird. Mine logs out True, "Title"

**Comment by jchannon** [comment]
After a thorough clean its still the same :)

**Comment by jchannon** [comment]
@lbargaoanu so you think I will have to update all my code to use `ForMember` and that it worked in v3 & v4 was a bug?

**Comment by lbargaoanu** [comment]
You don't have to set it by hand. If you have some rule, you can use ForAllMaps and ForAllMembers.

**Comment by SamiAl90** [comment]
Hello,

I am having the same issues with entities that have child objects / collections. 
I've seen they marked this bug for 5.1.0 to fix it which I am already using.
Is there something I have missed? I've found a lot of posts related to that matter on google but they all lead to workarounds.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by Hevzysq** [comment]
OMG.

```
 public class CustomerData
    {
        [StringLength(50)]
        public string Country { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(50)]
        public string Street { get; set; }
        public int? HouseNumber { get; set; }
        public int? Room { get; set; }
        [StringLength(10)]
        public string FirstPhoneNumber { get; set; }
        [StringLength(10)]
        public string SecondPhoneNumber { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        public int CustomerId { get; set; }
        public virtual Customer Customer { get; set; }
    }
```

```
public class Customer 
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public string ImgPath { get; set; }
        public DateTime? BirthDate { get; set; }
        public virtual CustomerData CustomerData { get; set; }
        public virtual Order Order { get; set; }
    }
```

```
 public override void Update(CustomerDTO domainObject)
        {
            Customer customer = GetCustomerByIdWithInclude(domainObject.Id);
            Mapper.Map(domainObject, customer);
            Repository.Update(customer);
        }
```
```
 public virtual void Update(TEntity entityToUpdate)
        {
            _dbSet.Attach(entityToUpdate);
            _context.Entry(entityToUpdate).State = EntityState.Modified;
            _context.SaveChanges();
        }
```

```
 public MappingProfile()
        {
            CreateMap<Customer, CustomerDTO>().ReverseMap().ForMember(c => c.CustomerData, o => o.UseDestinationValue());
            CreateMap<CustomerData, CustomerDataDTO>().ReverseMap().ForMember(c => c.Customer, o => o.UseDestinationValue());
        }
```

Why CustomerDataDTO in Customer is null?
When I map fields manualy - all is work.
