### ISSUE TITLE
Issue with One to Many mappings in 5.0.2

### ISSUE THREAD

**Issue by maganuk** [AutoMapper/AutoMapper#1491]
Hi,

https://gist.github.com/maganuk/84402cc7f0887629dc5f15cff22bea37

Please see the above gist.

This works fine with 5.0.0 but breaks with 5.0.2.

Thanks
Vishal

**Comment by jbogard** [comment]
Breaks? How?

**Comment by maganuk** [comment]
Throws an error.

Heres the stack trace:

AutoMapper.AutoMapperMappingException was unhandled
  HResult=-2146233088
  Message=Unable to create a map expression from Parent.Children (System.Collections.Generic.ICollection`1[Core.Children]) to ParentVM.Children (System.Collections.Generic.List`1[System.Int32])

Mapping types:
Parent -> ParentVM
Core.Parent -> Core.ParentVM

Type Map configuration:
Parent -> ParentVM
Core.Parent -> Core.ParentVM

Property:
Children
  Source=AutoMapper
  StackTrace:
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Core.Program.Main(String[] args) in C:\WebApplication1\src\WebApplication1\Program.cs:line 64
  InnerException:

**Comment by lbargaoanu** [comment]
My bad :)
