### ISSUE TITLE
'AutoMapper' already has a dependency defined for 'NETStandard.Library'.

### ISSUE THREAD

**Issue by Mehnock** [AutoMapper/AutoMapper#1492]
I tried to install Automapper just now (07/09/16) and got this error ('AutoMapper' already has a dependency defined for 'NETStandard.Library'.) in the Manage Nuget Packages for Solution screen in VS2013.

The package details state the version as 5.0.2, last published 7/7/2016

Any idea on how to get around this error?

**Comment by jbogard** [comment]
What version of NuGet are you using? What target framework are you installing into?

**Comment by Mehnock** [comment]
Oops sorry I jumped the gun!  I googled the error and saw that it's been resolved by installing the latest version of Nuget Package Manager.  AutoMapper installed after I installed Nuget and restarted VS.

Thanks for the prompt response!

**Comment by jbogard** [comment]
Sure, just for others if they see this, what version of NuGet did you have before?

**Comment by Mehnock** [comment]
I'm sorry for the delay, I was dealing with Ramsonware (Zepto) on a friend's computer  -- this is a nasty one!

I cannot get the exact version as I updated it before you asked me and did n;t look at the current version.  However I recently installed Windows 7 and VS13 on this PC and had not updated anything on VS so it should be the version it comes with out of the box.

**Comment by jbogard** [comment]
No worries, thanks!

**Comment by codepandy** [comment]
how to solve the problem?

**Comment by Thieum** [comment]
I guess VS2012 is not supported anymore considering the link provided by @codepandy , but you get this error when trying to install latest version of automapper in a clean VS2012 project, with up to date nuget extension (2.8.60318.667). 

Automapper 4.2.1 works fine on VS2012.

**Comment by lewisNotestine** [comment]
For posterity...

Initially tried to follow the advice in this thread by typing `Nuget Update -Self` in the Package Mgr Console .

This did not solve the problem. The problem was only solved by going into the VS2015 GUI and doing the uninstall and reinstall there:

Tools > Extensions and Updates

**Comment by okpoEkpenyong** [comment]
I had the same issue and had it resolved by following these procedures:
1. Right-click the project in the Solution Explorer and select the option 'Manage NuGet Packages'.
2. At the LHS pane, click 'Online' from the list, then type any package name you want on the upper
    right search field. 
3. Select and Install. If there are dependencies, the system will add them automaically (the right versions of course).
4. Restart VS if necessary.
Note: the listed procedures require an internet connection.
