### ISSUE TITLE
Automapper 5.0.2: Expression mapping

### ISSUE THREAD

**Issue by mkoutroupis** [AutoMapper/AutoMapper#1497]
Hi I am trying to map a predicate expression from VM to DTO but I get the following exception 

> Error mapping types. InnerException: {"Property 'System.String Name' is not defined for type 'XXX.Models.BU'"}

The configuration is : `cfg.CreateMap<Models.BU, ViewModels.BUVM>();
                cfg.CreateMap<ViewModels.BUVM, Models.BU>().ForMember(d => d.CostCenters, opt => opt.Ignore());
                cfg.CreateMap<Models.CostCenter, ViewModels.CostCenterVM>().MaxDepth(2);
                cfg.CreateMap<ViewModels.CostCenterVM, Models.CostCenter>().MaxDepth(2);
                `

and the predicate is ` _predicate = x => x.Name == "aa" && x.Id == 10 && x.AA == "bb" && x.BUId == 1 && x.BU.Id == 1 && x.BU.Name == "bb";`

The Models are: 
```
public abstract class BaseVM
    {
        public int Id { get; set; }
    }

 public class CostCenterVM : BaseVM
    {
        public string Name { get; set; }        
        public string AA { get; set; }
        public int BUId { get; set; }
        public virtual BUVM BU { get; set; }
    }
	
	
	public class BUVM : BaseVM
    {
        public string Name { get; set; }
        public string Code { get; set; }
    }

```
```
public abstract class AuditableEntity<T> 
    {
        public virtual T Id { get; set; }
    }

public class CostCenter : AuditableEntity<int>
    {
        public string Name { get; set; }
        public string AA { get; set; }
        public int BUId { get; set; }
        public virtual BU BU { get; set; }
    }

public class BU : AuditableEntity<int>
    {
        public string Name { get; set; }
        public string Code { get; set; } 
        public virtual ICollection<CostCenter> CostCenters { get; set; }
    }
`

```
Thank you in advance,
Kind regards,

M.

**Comment by TylerCarlson1** [comment]
Can you give the type of the predicate and the type it's mapping too?  Preferably in a gist that can replicate the problem.

Also there's UseAsDataSource that does the predicate translation and apply it to source.

**Comment by mkoutroupis** [comment]
Yes of course, so the predicate is:
` Expression<Func<CostCenterVM, bool>> _predicate = x => x.Name == "aa" && x.Id == 10 && x.AA == "bb" && x.BUId == 1 && x.BU.Id == 1 && x.BU.Name == "bb";`
and the exception is generate by this line:
`var newPredicate = _mapper.Map<Expression<Func<CostCenter, bool>>>(_predicate);`

In my project I have a Service Layer that converts predicates from VM to DTO and passes the predicates to the Data Layer using repository pattern which doesn't know anything about the VMs so the UseAsDataSource is not a good option.

**Comment by TylerCarlson1** [comment]
Issue stems from both classes having the same property name.

Workaround might be 
```
public abstract class AuditableEntity<T> 
    {
        public virtual T Id { get; set; }
        public string Name { get; set; }
    }
```
or changing name so it isn't the same name on both classes.

Looking at trying to resolve the issue right now.
