### ISSUE TITLE
Nuget Pack - 'AutoMapper' already has a dependency defined for 'NETStandard.Library'.

### ISSUE THREAD

**Issue by philcarbone** [AutoMapper/AutoMapper#1499]
I'm having an issue packaging my own nuget package, which includes AutoMapper 5.0.2. This is only producing an error within the Visual Studio Online (VSO) Build servers. 

My project is using .NET 4.6.1

Any ideas on how to fix?

Here is the error:

> 2016-07-08T23:46:44.5801667Z C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.102.0\agent\worker\tools\NuGet.exe pack "C:\a\1\s\Project.csproj" -OutputDirectory "C:\a\1\s\Project\bin\release" -Properties Configuration=release -IncludeReferencedProjects 
2016-07-08T23:46:45.0458195Z MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
2016-07-08T23:46:45.0468395Z Attempting to build package from 'Project.csproj'.
2016-07-08T23:46:45.1942694Z Packing files from 'C:\a\1\s\Project\bin\Release'.
2016-07-08T23:46:45.3942642Z ##[error]**'AutoMapper' already has a dependency defined for 'NETStandard.Library'.**
2016-07-08T23:46:45.4142626Z ##[error]System.Exception: Unexpected exit code 1 returned from tool NuGet.exe
2016-07-08T23:46:45.4152639Z ##[error] at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
2016-07-08T23:46:45.4152639Z ##[error] at System.Management.Automation.CommandProcessor.ProcessRecord()

I also posted on stackoverflow: http://stackoverflow.com/questions/38277654/when-running-the-nuget-pack-command-i-get-the-error-automapper-already-has-a-d

**Comment by jbogard** [comment]
What version of nuget?

**Comment by philcarbone** [comment]
I don't know how to find out. It is Microsoft's Hosted Build Servers in Visual Studio Online. I'm assuming it is the latest stable version, as all of their other tools are within that build environment. I also opened a ticket with MS about it.

**Comment by philcarbone** [comment]
I asked MS if they can tell me how to get the NuGet version

**Comment by philcarbone** [comment]
Looks like the Hosted Build Server is running NuGet 3.3.0.212

**Comment by philcarbone** [comment]
I was able to fix/workaround the issue by putting a PowerShell script in to download the latest NuGet. Then I pointed all of the NuGet tasks to this new nuget.exe. Pros: builds are working again, Cons: each build downloads NuGet again, causing unnecessary load on NuGet,org. 

Here is my PowerShell:

$sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
$targetNugetExe = "$(build.sourcesdirectory)/nuget.exe"
Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe
Set-Alias nuget $targetNugetExe -Scope Global -Verbose
nuget

**Comment by jbogard** [comment]
Ohhhh yeah you know I got so tired of things like this I actually include
nuget in my repos these days.

**Comment by kabua** [comment]
I'm having the same issue with AutoMapper 5.1.1 using nuget 3.4.4.1321

**Comment by jbogard** [comment]
@kabua open a new issue if you're still seeing this error if you can please

**Comment by mtrax** [comment]
@kabua @jbogard I've the same problem, so I created a new issue: [https://github.com/AutoMapper/AutoMapper/issues/1793](url)
