### ISSUE TITLE
Reopen of #463. Failed a unit tests with message AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by PivotalAnimal** [AutoMapper/AutoMapper#1500]
#463 is closed but I have been having the same issue.
When I run all tests, one of them fails. When I run that same test by itself, it works.My Repo: [https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore)

**Comment by lbargaoanu** [comment]
You should be calling Mapper.Initialize only once. Or have a different mapper per test. Check how our tests work.

**Comment by PivotalAnimal** [comment]
I could do away with all the fancy ToModel() and ToEntity() stuff and just call AutoMapper.Map directly. Not sure if this would help. I added the Mapper.Initialize method to the test in question per feedback from previous thread. It didn't seem to help. Were you able to get the test running from my repo? Which example are you referring to with regard to your tests? There are dozens of AutoMapper tests so I'm not sure. Thanks!

**Comment by lbargaoanu** [comment]
[This](https://github.com/AutoMapper/AutoMapper/blob/194e966245b10fe2d1fd9f9a26b3dda4038d269b/src/UnitTests/AutoMapperSpecBase.cs) is the base class. You just have to merge all that into a single class :)

**Comment by PivotalAnimal** [comment]
I played around with that some without success. The AutoMapper tests are easier to debug as they define creation / destruction in a single place, per test. Perhaps the fact that I am using a static constructor to create a single map inside the main project is causing an issue? Another thing is that it is failing on a generic conversion from Concrete Model to Generic Entity <TKEY>.

**Comment by PivotalAnimal** [comment]
I have a sneaky suspicion it has something to do with the static constructor. Instead of using it, how should I handle config separately? What do I do with it?
`        static ModelsMap()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.AddProfile<ModelsMapProfile<TKey>>();
            });

            //var config = new MapperConfiguration(cfg => {
            //    cfg.AddProfile<ModelsMapProfile<TKey>>();
            //});

            //Mapper.Configuration.AssertConfigurationIsValid();
        }`
[https://lostechies.com/jimmybogard/2016/01/21/removing-the-static-api-from-automapper/](https://lostechies.com/jimmybogard/2016/01/21/removing-the-static-api-from-automapper/)
[https://github.com/AutoMapper/AutoMapper/wiki/Configuration](https://github.com/AutoMapper/AutoMapper/wiki/Configuration)

**Comment by PivotalAnimal** [comment]
I'm keeping my fingers crossed but may have a solution. I'll try this out more at home.
Replace static Mapper.Initialize with this:
`        public static IMapper MapperInstance { get; set; }

        static ModelsMap()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<ModelsMapProfile<TKey>>();
            });

            MapperInstance = config.CreateMapper();

            //Mapper.Configuration.AssertConfigurationIsValid();
        }`

If any test still fails, add this:
            AutoMapper.Mapper.Initialize(cfg => { cfg.AddProfile<ModelsMapProfile<Guid>>(); });
            AutoMapper.Mapper.AssertConfigurationIsValid();

**Comment by PivotalAnimal** [comment]
Finally Update - All is good! Tests are passing and I removed the unnecessary AutoMapper.Mapper.Initialize static method from tests and elsewhere. Cheers!

**Comment by lbargaoanu** [comment]
This can be closed.
