### ISSUE TITLE
Overriding mapping after call to ignore all mapping

### ISSUE THREAD

**Issue by ericvb** [AutoMapper/AutoMapper#1501]
Hi,
I followed the stackoverflow answer : http://stackoverflow.com/questions/4367591/how-to-ignore-all-destination-members-except-the-ones-that-are-mapped

At the time it was probably working, today with version 5.0.2 I can't get it to work.
I created a new nunittest file in the automapper source project to be sure that I didn't have sideeffects in my own project, see attached file with a unittest, the second test is failing.

[CreateMapExpressionWithIgnoredAllAndOverwriteIgnoreAll.zip](https://github.com/AutoMapper/AutoMapper/files/356604/CreateMapExpressionWithIgnoredAllAndOverwriteIgnoreAll.zip)

**Comment by lbargaoanu** [comment]
This was discussed before. See #1395 for example.

**Comment by ericvb** [comment]
In my opinion, not really the same problem, but probably related. I do not use TypeMap, the extension is just ignoring all members.
I want to set the mappings that can be done, myself via the configuration profile (and not via Ignore attribute mapping directly in the mapping classes).

For the moment I'm just playing with the whole thing.
The two mapping classes, let's say PersonSource and PersonDestination are identical generated classes.
For the moment I want for example only one property mapped, let's say 'Name'.
I have a working example with the IgnoreMap attribute, but that's cumbersome to type all this attributes on the other properties.

` CreateMap<PersonSource, PersonDestination>().IgnoreAllMapping().ForMember(x => x.Name, opt => opt.MapFrom(s => s.Name)); //map only Name field`

**Comment by jbogard** [comment]
So you only want to map fields if you explicitly configure them?

**Comment by TylerCarlson1** [comment]
Could try adding this to your configuration
```
    cfg.ShouldMapProperty = p => false;
    cfg.ShouldMapField = f => false;
```
and that way no properties or fields will be attempted to be mapped, only your configured ones.
This will apply to every CreateMap you make on this configuration.  If you want the auto properties to work you'll have to create its own Profile to do so.

**Comment by ericvb** [comment]
@Jbogard, yes for some mapping classes, I want to specific set the fields that I want to map and ignore all the rest.
I can do that with the ignoremap attribute, but in the past, if I can trust the stackoverflow question answer, it was also possible to do that when creating the map and that is not working anymore.

@TylerCarlson1, I added the two proposed lines to my configuration, but that didn't work, automapper is mapping all the fields.
In my startup.cs (.net core), constructor I have the following
```
MapperConfiguration = new MapperConfiguration(cfg =>
            {
                cfg.ShouldMapProperty = p => false;
                cfg.ShouldMapField = f => false;
                cfg.AddProfile<AutoMapperProfileConfigurationDataBusiness>();
            });
```
My profile class
```
public class AutoMapperProfileConfigurationDataBusiness : Profile
    {
        public AutoMapperProfileConfigurationDataBusiness()
        {
                        CreateMap<Data.Models.DomainModels.OrganisationEntity, Models.BusinessModels.OrganisationEntity>()
                .ForMember(x => x.Name, opt => opt.MapFrom(s => s.Name));
       }
   }
```
In the ConfigureServices method in Startup.cs file : 
```
// automapper
            services.AddSingleton<IMapper>(sp => MapperConfiguration.CreateMapper());
```
The mapper is then injected by DI in my business service getting data from the database and mapping it to the business model.

**Comment by TylerCarlson1** [comment]
No you have to add it for the profile then and not the config.  But if you do that all CreateMaps in that profile will ignore all.

**Comment by ericvb** [comment]
Ok, that is working, thanks

So is that the way to go if we want this behavior?
And is the ignore() for all members not working anymore in version 5.x?
```
 CreateMap<PersonSource, PersonDestination>()
                 .IgnoreAllMapping()
                 .ForMember(x => x.Name, opt => opt.MapFrom(s => s.Name)); //map only Name field 
```

**Comment by TylerCarlson1** [comment]
If it works for you then yes :)

Doesn't make a diff performance wise and will save you a line of code every CreateMap call.
Just know that your profile will never set property or field maps at all, including constructors I believe.

You can always create a new profile if you need that functionality for other maps.

**Comment by lbargaoanu** [comment]
You can turn it around:

		c.CreateMap<Model, Dto>()
			.ForMember(d=>d.Date, o=>o.MapFrom(s=>s.Date))
			.ForMember(d=>d.FooId, o=>o.MapFrom(s=>s.FooId))
			.ForAllOtherMembers(o=>o.Ignore());

You can close the issue.

**Comment by ericvb** [comment]
That is of course also a valid path of thinking. I will try it out.

The question I still ask to myself, the proposed way for the older version don't work anymore: degression in new version or made voluntarily obsolete or did it work accidentally in the old version and it wasn't meant to work like that?

**Comment by lbargaoanu** [comment]
It was a hack. ForAllMembers is void because it is supposed to be called last.

**Comment by jbogard** [comment]
To be honest the behavior you're looking for is manual mapping in which
case I'd say don't use AutoMapper.

**Comment by ericvb** [comment]
@jbogard, that's true if all mappings are manual. In my case it are only some mapping classes, so the use of AutoMapper is still a valid choice.

Thanks to all to clarify the different things.
