### ISSUE TITLE
Breaking change, default constructor mapping changed between 4.x and 5.0

### ISSUE THREAD

**Issue by theroc** [AutoMapper/AutoMapper#1504]
I may have missed this in the migration guide but between the two versions 4.x and 5 I've noticed that maps now pick a different default constructor, specifically favouring a parameter name match on a class property over the default.

Example:

`cfg.CreateMap<MapLeft, MapRight>();`
```

        public interface IDefaultInterface
        {
            int Id { get; set; }
        }

        public class MapLeft : IDefaultInterface
        {
            public MapLeft()
            {
                // In 4.x this was always called.
            }

            public MapLeft(int id)
            {
                // In 4.x this was never called.    
                // In 5.x this is now the default.
                throw new Exception();
            }

            public int Id
            {
                get;
                set;
            }
        }

        public class MapRight : IDefaultInterface
        {
            public MapRight()
            {
                // In 4.x this was always called.
            }

            public MapRight(int id)
            {
                // In 4.x this was never called.    
                // In 5.x this is now the default.
                throw new Exception();
            }

            public int Id
            {
                get;
                set;
            }
        }
```
Then if we use the map, it will always pick the constructor with a parameter match (which I understand is helpful but it may be worth putting this in the upgrade guide so folks know to update their maps\code accordingly) 

```
            var left = new GlobalMappingConfiguration.MapLeft() { Id = 1 };

            var right =
                GlobalMapper.Mapper.Map<GlobalMappingConfiguration.MapLeft, GlobalMappingConfiguration.MapRight>(left);
```
This code throws the exception I raise above.
Changing the parameter name in the constructor from id to something that doesn't match any properties on the object resolves the issue.

My apologies if I missed something from the migration guide which already covers this.

**Comment by jbogard** [comment]
Ah, most people want this behavior. There's an upgrade guide in the wiki,
can you add something there that makes sense for you?

**Comment by theroc** [comment]
Hi Jimmy,
Thanks for the response, it is not so much that it does not make sense but rather something that could be added to the upgrade guide for those moving from 4 to 5 as it is a behavioural change that could catch many folks out :), granted that with unit tests it would pick this up but again only if the behavioural change was covered by such a test.

Primarily for such a case as below where it is assumed that because the id property is specified on the constructor that it will then be assigned to the property in said constructor. In the use case below because the constructor with id is picked the id on the RightSide object remains set to 0 even if an explicit mapping is specified.

 ```
       public class SimpleLeft
        {
            public int Id { get; set; }
        }

        public class SimpleRight
        {
            public SimpleRight()
            {

            }

            public SimpleRight(int id)
            {

            }

            public int Id { get; set; }
        }

            var map = new MapperConfiguration(expression =>
            {
                expression.CreateMap<SimpleLeft, SimpleRight>();
            }).CreateMapper();

            var leftSide = new SimpleLeft() {Id = 1};

var rightSide = map.Map<SimpleLeft, SimpleRight>(leftSide);
            // Id on the rightSide object will remain as 0 as the constructor never set the property.

Lets assume that we then make the mapping more explicit with a ForMember just to be extra sure :),
// Now if we make it more explicit.
            var map = new MapperConfiguration(expression =>
            {
                expression.CreateMap<SimpleLeft, SimpleRight>()
                .ForMember(src=> src.Id, trg => trg.MapFrom(src=> src.Id));
            }).CreateMapper();

When using this map the Id will still remain 0 as the constructor selected will not set the property.
```

**Comment by jbogard** [comment]
Yeah of course! Can you update the wiki to whatever makes sense for you?

**Comment by TylerCarlson1** [comment]
@theroc Anyone can update the Wiki whenever they want.  That's what @jbogard is asking you to do, since you know how to explain what's going on.

**Comment by theroc** [comment]
Thanks Jimmy, Tyler, I just wanted to make sure the behaviour I've outlined above is intentional before I update the wiki with potentially incorrect information. I've been looking at whether it would be possible to flag up so-called Superfluous .ForMember mappings as in the bottom of my sample above the ForMember is actually ignored entirely.

**Comment by jbogard** [comment]
yep, it's the correct behavior now. To turn off this behavior, you'd do "DisableConstructorMapping".
