### ISSUE TITLE
Exception when configuring mappings (worked in 4.2.1)

### ISSUE THREAD

**Issue by bodrick** [AutoMapper/AutoMapper#1505]
Since upgrading to 5.0.2 it seems one of my mappings in throwing the following exception - 
`Expression of type 'System.Nullable`1[System.DateTime]' cannot be used for return type 'System.DateTime'`

The destination property is a nullable date time and the mapping is as follows -
`ForMember(Function(dest) dest.EndDate, Sub(opt) opt.MapFrom(Function(src) If(src.ExamType = ExamType.Makeup, src.ExamSchedules.Max(Function(m) m.Schedule.DtEnd), src.ExamSchedules.Where(Function(f) f.Schedule.BHide = False).Max(Function(m) m.Schedule.DtEnd)))).`

If I try to change the destination to just Date then the configuration doesn't throw an exception but I will get an exception later on when my code is run that uses the mapping because there are times where there are no values and it should be null.

Not sure if there is something I'm missing or whether this is a bug or already discussed.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by TylerCarlson1** [comment]
If you cast the results to `Nullable<DateTime>` in you opt settings it should work.

This is a known issue #1483.  If you go back to 5.0.1 or before it doesn't happen.

**Comment by jbogard** [comment]
I think I have a repro, as I hit this in one of our clients. Basically you've got a complex MapFrom, and the MapFrom goes from a value type to a nullable type, that the gist of it?

**Comment by lbargaoanu** [comment]
...the gist of it.. :)

**Comment by bodrick** [comment]
Awesome, thanks for looking into this so quickly, your work is very much appreciated :+1:
