### ISSUE TITLE
Need Help or hint on Problem with List<> to List<> with Version 5 

### ISSUE THREAD

**Issue by Mer0winger** [AutoMapper/AutoMapper#1507]
Migrating to new Version 5.x 
i tried now a lot of how to make it work again but i am lost. 

But my Mapping into the generic TDto Class failed with 

>>Der Typ "AutoMapper.IMapperConfiguration" in der Assembly "AutoMapper, Version=5.0.2.0, >>Culture=neutral, PublicKeyToken=be96cd2c38ef1005" konnte nicht geladen werden.

in English like 

Type of  AutoMapper.IMapperConfiguration could not been loaded ? 

The Variable "entites" in Debug Mode includes all Records queried from DB. And the next step with ProjectionTo<TDto>... failed. 

....
            Mapper.Initialize(cfg => {cfg.CreateMap<TEntity, TDto>().ReverseMap();
                                      cfg.IgnoreUnmapped<TEntity, TDto>();
                                     }
                             );
            Mapper.AssertConfigurationIsValid();

            var entities = entity.Where(ViewModel.QueryFilter).ToList().AsQueryable<TEntity>();

            List<TDto> ilistDest = entities.ProjectTo<TDto>(MapConfig).ToList();
....

The IgnoreUnmapped Extensions is used from 
http://stackoverflow.com/questions/954480/automapper-ignore-the-rest
because only TDto has some more Attributes then  the Base TEntity has. 

Any hint please what i am doing wrong. 

thanks br thomas

**Comment by jbogard** [comment]
IgnoreUnmapped thingy is wrong. I assume IgnoreUnmapped means you don't want to validate that mapping, so you should use CreateMap with the MemberList option of None or Source, depending on how you want your validation to work.
