### ISSUE TITLE
Projecting EF queryables with AllowNullCollections throws exception

### ISSUE THREAD

**Issue by mcliment** [AutoMapper/AutoMapper#1509]
The exception thrown is the following:

    The 'TypeAs' expression with an input of type 'System.Collections.Generic.ISet`1[[Common.Bar, Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' and a check of type 'System.Object' is not supported. Only entity types and complex types are supported in LINQ to Entities queries.

I've set up a sample project with the same code working on Automapper 4.2.1 and failing on Automapper 5.0.2 here: https://github.com/mcliment/AutomapperNullCollections

**Comment by mcliment** [comment]
The code causing the error can be found here: https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs#L46-L51

I'm not sure I understand what this code is trying to do. The thing is that the EF LINQ provider does not support TypeAs.

**Comment by mcliment** [comment]
I confirm that using master branch works as expected and just as Automapper v4.x did.

**Comment by lbargaoanu** [comment]
For future reference, you don't have to make a whole solution to repro :) A runnable gist is all we need.

**Comment by mcliment** [comment]
@lbargaoanu I know but I had it already done for my own experimentation
