### ISSUE TITLE
Adding configuration for all types

### ISSUE THREAD

**Issue by Mds92** [AutoMapper/AutoMapper#1510]
I wanna add `MaxDepth(0)` to all mapped types as the followings:
```
CreateMap<AdvertisementStatistic, AdvertisementStatisticModel>().MaxDepth(0);
...
...
...
```
Is it an option to add this feature to all types simpler instead of adding `.MaxDepth(0);` at the end of each type in version 5?

**Comment by jbogard** [comment]
Have you looked at ForAllMaps?

**Comment by lbargaoanu** [comment]
And instead of MaxDepth, PreserverReferences might help.

**Comment by Mds92** [comment]
What is `PreserverReferences `?

**Comment by lbargaoanu** [comment]
It was a typo :) Fixed.

**Comment by jbogard** [comment]
It preserves references in case you have deep, circular maps.

You can do:

```
cfg.CreateMap<Foo, Bar>();
cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.MaxDepth(0));
```
