### ISSUE TITLE
In 5.0.2 mapping nullable source to non-nullable dest defaults the target.  In 4.2.1 the dest is unchanged.

### ISSUE THREAD

**Issue by checkinnuggets** [AutoMapper/AutoMapper#1513]
Simplified example of something I came across. Not sure that 5.0.2 is wrong, just highlighting for visibility since the change in behaviour was unexpected.

	using NUnit.Framework;
	using AutoMapper;

	namespace AutoMapper5Demo  
	{
		public class Src
		{
			public string SomeProperty { get; set; }  // same result if this is 'double?'.
		}

		public class Dst
		{
			public double SomeProperty { get; set; }
		}

		
		[TestFixture]
		public class AutoMapperUpgradeInvestigation
		{
			[Test]
			public void PropertyWithSameNameButDifferentTypeWasLeftUntouchedIn421()
			{
				Mapper.Initialize(cfg => { cfg.CreateMissingTypeMaps = true; });

				var src = new Src { SomeProperty = null };
				var dst = new Dst { SomeProperty = 123.45 };

				Mapper.Map(src, dst);
				
				Assert.AreEqual(123.45, dst.SomeProperty);  // in 4.2.1 (dst.SomeProperty is 123.45). In 5.0.2 (dst.SomeProperty is 0).
			}
		}
	}

**Comment by lbargaoanu** [comment]
#1428? If it's the same, you can close it,

**Comment by checkinnuggets** [comment]
Yes, looks like the same issue to me.  Thanks.
