### ISSUE TITLE
Member 'Bootstrapper.ApiMappings.Configure()' overrides obsolete member 'Profile.Configure()'.

### ISSUE THREAD

**Issue by niemyjski** [AutoMapper/AutoMapper#1515]
Any chance https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide could get updated for `Member 'Bootstrapper.ApiMappings.Configure()' overrides obsolete member 'Profile.Configure()'. Add the Obsolete attribute to 'Bootstrapper.ApiMappings.Configure()'.`

There are no overloads and it's not clear what needs to be done here.

**Comment by niemyjski** [comment]
After looking at the source code.. I see I'm supposed to use the constructor... I'm not sure why in 5.0.2 I'm getting this horrible warning...

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Profile.cs#L44-L45

**Comment by jbogard** [comment]
Ah yes, just override the ctor.

**Comment by niemyjski** [comment]
@jbogard want me to close this? The compiler warning wasn't very good. I'm not sure why it didn't match what's in the source unless that change was recently made.

**Comment by jbogard** [comment]
OK I updated the wiki and modified the language on the Obsolete attribute to be "Create a constructor and configure inside of your profile's constructor instead. Will be removed in 6.0". Is that better/more explicit?

**Comment by niemyjski** [comment]
yep!
