### ISSUE TITLE
Mapping IQueryable with SubQueries in ValueResolver fails

### ISSUE THREAD

**Issue by scherfa** [AutoMapper/AutoMapper#1517]
I Have an IQueryable like this:

`IQueryable<TNestedEntity> nestedEntities = repository.Where(e => e.Id == id).SelectMany(propertyExpression);
`
**Now i map this with** 
`nestedEntities.MapTo<TResult>()`

Inside the Map i use 2 Resolver like this

```
public class EntityDateResolver : IValueResolver<TEntity,EntityDestinationContract, DateTime>
    {
        public DateTime Resolve(TEntity source, EntityDestinationContract destination, DateTime destMember, ResolutionContext context)
        {
            IQuery<TEntity> kassenbuecher = ServiceLocator.Current.GetInstance<IQuery<TEntity>>();
            
            IQueryable<TNestedEntity> kassenbuchBewegungen = kassenbuecher.Where(kx => kx.Id == source.Id).SelectMany(kx => kx.Nested);

            ResultEntity result = kassenbuchBewegungen.Where(kb => !kb.BoolValue).OrderByDescending(kb => kb.Number).FirstOrDefault();

            return result == null ? source.Date : result.Date;
        }
    }
```

After upgrading to Automapper 5.0.2 i get an Exception telling me that 
**AutoMapper.AutoMapperMappingException: Error mapping types.**

Property:
Date---> System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.

**Was this my fault? Does i have to call ToList before Mapping the result?**
We dont use MARS in our SQLServer Configuration. If i turn it on it works, but i think that is not a solution.

**Comment by theroc** [comment]
Hi Scherfa,

I can confirm I am experiencing the same behaviour, when the result of the query is not materialised using ToList then the map will attempt to pull all navigation properties, this results in additional query which would then cause the behaviour experienced. SQL server has MARS (MultipleActiveResultSets) which may alleviate this, we are using PostgreSQL here and I can confirm this is reproducible in PostgreSQL on Automapper 5.x.

**Comment by jbogard** [comment]
Yes - you do need to map to results. This is because you're trying to map an IQueryable vs. an IEnumerable - and mixing the two just doesn't work well, really in any context. Make sure you actually execute the query with a ToList() before passing to AutoMapper.

I don't know about the MARS stuff. If you want to map querybables, you'll need to use ProjectTo, otherwise call ToList() or ToArray().

**Comment by scherfa** [comment]
Thanks. But i was confused, because this code works in previous automapper
versions.
For now I change every mapping call so that to List is called before.

Cheers
Andreas

Yes - you do need to map to results. This is because you're trying to map
an IQueryable vs. an IEnumerable - and mixing the two just doesn't work
well, really in any context. Make sure you actually execute the query with
a ToList() before passing to AutoMapper.

I don't know about the MARS stuff. If you want to map querybables, you'll
need to use ProjectTo, otherwise call ToList() or ToArray().

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AutoMapper/AutoMapper/issues/1517#issuecomment-232402888>,
or mute the thread
<https://github.com/notifications/unsubscribe/AG4xFNwtAi5jNshhmSzjiaBHVlmbkQXxks5qVQxSgaJpZM4JLhPA>
.

**Comment by jbogard** [comment]
Hmmm that was probably an accident, we've had quite a few problems with
ORMs and handing around IQueryables. We now explicitly enumerate the
results so that we know where the query happens.

**Comment by scherfa** [comment]
Sounds ok. I have to mention that I use an extension method around the
Mapper.Map call. This extension gets and returns an IEnnumerable and passes
this value to the mapper.

Thanks and good night
Andreas
Am 13.07.2016 21:02 schrieb "Jimmy Bogard" <notifications@github.com>:
