### ISSUE TITLE
Nuget Pack - 'AutoMapper' already has a dependency defined for 'NETStandard.Library' - VS2012

### ISSUE THREAD

**Issue by chadwixk** [AutoMapper/AutoMapper#1521]
There is a similar question here: [https://github.com/AutoMapper/AutoMapper/issues/1499](https://github.com/AutoMapper/AutoMapper/issues/1499), but it is related to Visual Studio Online.

I have Visual Studio 2012. I am running Nuget v2.8.6. My project is using .Net 4.5.2.

When looking at Tools > Extensions and Updates, it does not list any newer version of NuGet available.

Can I install a newer version manually some other way via PAckage MAnager Console? I see the there are newer versions listed on NuGet's site...not sure if they'd be compatible with VS2012 [https://dist.nuget.org/index.html](https://dist.nuget.org/index.html)

So how do I go about installing AutoMapper?

**Comment by jbogard** [comment]
You can install via nuget command line. The VS team have said they're not supporting older than VS 2013, so you can also upgrade VS :)

**Comment by chadwixk** [comment]
Ok, thank you. I'll research how to do that.

Yeah, I need to upgrade VS one of these days soon I guess.
