### ISSUE TITLE
Possible regression: AutoMapper 5.0.2 calls ToString() where 4.x didn't

### ISSUE THREAD

**Issue by thedmi** [AutoMapper/AutoMapper#1529]
During my attempt to update to 5.0.2 I came across what may be a regression. 

A combination of `cfg.CreateMap<T, string>().ProjectUsing(...)` and `T` being a base type of the member that is actually mapped causes the problem: AutoMapper 5 calls `ToString()` instead of the configured projection. AutoMapper 4, on the other hand, uses the projection.

The following test illustrates the problem:

    [Fact]
    public void Custom_string_mapping_is_used()
    {
        var config = new MapperConfiguration(
            cfg =>
            {
                cfg.CreateMap<Source, Destination>();
                cfg.CreateMap<IId, string>().ProjectUsing(id => id.Serialize());
            });

        var mapper = config.CreateMapper();

        var output = mapper.Map<Destination>(new Source { TheId = new Id { Prefix = "p", Value = "v" } });

        Assert.Equal("p_v", output.TheId);
    }

    class Source
    {
        public Id TheId { get; set; }
    }

    class Destination
    {
        public string TheId { get; set; }
    }

    interface IId
    {
        string Serialize();
    }

    class Id : IId
    {
        public string Prefix { get; set; }

        public string Value { get; set; }

        public string Serialize()
        {
            return Prefix + "_" + Value;
        }
    }

### Observations

- With AutoMapper 5, `output.TheId` is the FQN of the `Id` class, indicating that AutoMapper calls `ToString()`.
- When the interface `IId` is removed and the class `Id` is used directly, the mapping behaves as expected. This is however not flexible enough for my case, because I have many implementations of that interface.
- It doesn't matter whether `ProjectUsing` or `ConvertUsing` is used.

**Comment by lbargaoanu** [comment]
Can you try the MyGet build?

**Comment by thedmi** [comment]
Just tested, I can confirm that `5.1.0-alpha-01176` still has the issue.

**Comment by lbargaoanu** [comment]
Yes, it's a bug. ConvertUsing is the method to use for Map, ProjectUsing is for LINQ.

**Comment by jbogard** [comment]
Yep, and at one point ProjectUsing set ConvertUsing

**Comment by thedmi** [comment]
Ok, I'll change it to `ConvertUsing`. But just to clarify again: The bug exists with `ConvertUsing`, too.

**Comment by lbargaoanu** [comment]
:) Yes, that's more for future reference. The fix is easy enough, but we should merge another PR first.

**Comment by thedmi** [comment]
:+1:

**Comment by thedmi** [comment]
BTW, is it possible to disable the `ToString()` handling entirely? I don't use it at all, so I would prefer if AutoMapper reported a missing mapping from `T` to `string` instead of assuming that I want to call `T.ToString()`.

**Comment by lbargaoanu** [comment]
No easy way, but you can try something like that:

		c.CreateMap<object, string>().ConvertUsing(s =>
		{
			var stringSource = s as string;
			if(stringSource != null)
			{
				return stringSource;
			}
			throw new AutoMapperConfigurationException("Missing type map to string");
		});

**Comment by jbogard** [comment]
Yes, when you create the mapper configuration from a list of object
mappers, just remove the StringMapper from the list in MapperRegistry.

**Comment by lbargaoanu** [comment]
@jbogard I thought so too, but no :) That ToString is hard-coded now, I'm not sure the StringMapper does much anymore.

**Comment by thedmi** [comment]
Following the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) I would even suggest to make the string mapping opt-in in a future release. But that's a breaking change, and you probably had enough breaking changes just now :-)

**Comment by jbogard** [comment]
Yeah that's been a feature since probably the first couple of months. And
tbqh you're the first person that's been surprised about automatic string
mapping in the 8 or so years AutoMapper has been around. If I took away the
string mapping, I'd need to take away the close to 100 other automatic type
conversions that AutoMapper has that it uses based on built-in type
conversions already in .NET.

What I think we *could* (and probably need to do) is catalog the built-in
mappings and conversions. That's not really documented explicitly anywhere.

**Comment by lbargaoanu** [comment]
Well, opt-out would be nice :) But until someone is bothered enough...

**Comment by thedmi** [comment]
I'm easily surprised :-D . That would be perfectly fine for me, a list of the automatic mappings, and a guideline about how to disable some of them.
