### ISSUE TITLE
Installing AutoMapper in a Profile Based PCL

### ISSUE THREAD

**Issue by IlSocio** [AutoMapper/AutoMapper#1531]
Hi, 
I tried to install AutoMapper 5.0.2 in a Profile Based PCL (Profile 259)
but I got the error below:
`"Could not install package 'AutoMapper 5.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."`

I can successfully install AutoMapper 4.1.1 but I can't install any higher version due to the error above

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/1117#issuecomment-193441891

**Comment by jbogard** [comment]
Profile 259 is a Windows Phone Silverlight profile. AutoMapper 5.0 does not support that.

It supports anything on the .NET Standard 1.1 library, which is most everything released in the last 5 years.

**Comment by IlSocio** [comment]
Thank you Jimmy, it makes sense.
I changed my PCL to target Profile 111 and I've been able to install latest AutoMapper version.

But I noticed a different issue...
https://github.com/AutoMapper/AutoMapper/issues/1532
