### ISSUE TITLE
'AutoMapper' already has a dependency defined for 'NETStandard.Library' in VS2013 pro

### ISSUE THREAD

**Issue by TJHan** [AutoMapper/AutoMapper#1535]
The error message "'AutoMapper' already has a dependency defined for 'NETStandard.Library'" shown when i was trying to install the AutoMapper 5.0.2 on VS2013 pro.
my NuGet version is 2.12.0.817, and project using .net 4.5
please help. how do i installing AutoMapper?

**Comment by jbogard** [comment]
Upgrade NuGet.

**Comment by TJHan** [comment]
oh thx, it's work now.

**Comment by jbogard** [comment]
Nice!
