### ISSUE TITLE
How to add a new map in ForAllMaps

### ISSUE THREAD

**Issue by TomasHubelbauer** [AutoMapper/AutoMapper#1541]
I'm trying to integrate your advice from the comment on http://stackoverflow.com/a/38423860/2715716.

I replaced the original implementation in the answer with the following:

```cs
public static IMapperConfigurationExpression CreateWrapMap(this IMapperConfigurationExpression cfg)
{
    var wrapTypePair = new List<TypePair>();
    cfg.ForAllMaps((tm, _) =>
    {
        if (typeof(DestinationModelBase).IsAssignableFrom(tm.DestinationType) && !tm.DestinationType.IsAbstract)
        {
            wrapTypePair.Add(tm.Types);
        }
    });

    foreach (var typePair in wrapTypePair)
    {
        cfg
            .CreateMap(typePair.SourceType, typeof(Wrap<>).MakeGenericType(typePair.DestinationType))
            .ConvertUsing(typeof(MapAndWrapConverter<,>).MakeGenericType(typePair.SourceType, typePair.DestinationType));
    }

    return cfg;
}
```

The reason I take out the types into `wrapTypePair` is that I can't modify the collection while enumerating it at the same time (by calling `ForAllMaps`). Normally one would duplicate the enumerated collection by calling `ToArray` or something but this is impossible here since I'm only providing part of the enumeration implementation to `ForAllMaps`.

However this doesn't work, because after the call to `ForAllMaps` is done, the delegate hasn't been run yet, it is only run once I call `mapper.Map`, but at that point it's too late for me to add new maps thru any means.

What could be done to work around (or preferably work idiomatically with) this?

**Comment by lbargaoanu** [comment]
I think it could work with two mapper objects.

**Comment by jbogard** [comment]
What does your whole config call look like?

**Comment by lbargaoanu** [comment]
I think ForAllMaps is not a good fit here (two mappers seems complicated) and the solution on SO is bad too, because it creates another configuration object and that's expensive. I think the best way is to start from the types to map and make two passes. One to create the initial maps and one to create the wrapper maps, as needed. Otherwise the issue can be closed, nothing to do here I believe.
