### ISSUE TITLE
ProjectTo<T> throws uninformative error when unsupported mapping specified

### ISSUE THREAD

**Issue by CraigStuntz** [AutoMapper/AutoMapper#1544]
ProjectTo<T> [throws a very generic error](https://github.com/AutoMapper/AutoMapper/blob/3204815259c14294c2f62b892810a0f76a58ace4/src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs#L198) when a property is mapped that is [not a supported mapping](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions).

It would be nice if the error told you _which_ property/properties could not be mapped, and, ideally, why. Obviously it can't know the restrictions of the LINQ provider, though. 

I've opened [a related issue](https://github.com/AutoMapper/AutoMapper/issues/1543) for validation.

**Comment by lbargaoanu** [comment]
PR?

**Comment by CraigStuntz** [comment]
@lbargaoanu  I'm not sure what the specification is for this or how it should be implemented. I wrote the PRs because [Jimmy asked me to](https://twitter.com/jbogard/status/755414475142868993). I don't really use AutoMapper except when I'm asked to help with projects which already use it.

**Comment by lbargaoanu** [comment]
I thought you care :)

**Comment by lbargaoanu** [comment]
This was fixed.
