### ISSUE TITLE
AutoMapper 5.0.2 uses ToList when creating map expressions for IEnumerable<T>

### ISSUE THREAD

**Issue by dozer75** [AutoMapper/AutoMapper#1545]
When AutoMapper 5.0.2 creates map expressions for entity framework usage (using `ProjectTo<TDestination>)` it uses `ToList()` on mapping of properties of type `IEnumerable<T>`. 

While this works in newer Entity Framework versions, older like the one shipped with .NET 4 does not support `ToList()` in expressions and causes a `NotSupportedException` from Entity Framework.

> An exception of type 'System.NotSupportedException' occurred in System.Data.Entity.dll but was not handled in user code

> Additional information: LINQ to Entities does not recognize the method 'System.Collections.Generic.List`1[Foo] ToList[Foo](System.Collections.Generic.IEnumerable`1[Foo])' method, and this method cannot be translated into a store expression.

This worked in the last version I had before upgrading (4.1.1).

Can this be fixed? If the type of a property is `IEnumerable<T>` there should not be any `ToList()` call. It isn't any need for it either, since an `IEnumerable<T>` is only for traversing and not manipulation.

**Comment by jbogard** [comment]
What version of EF?

**Comment by dozer75** [comment]
Sorry, forgot, EF 4, the last one that came integrated in the .NET framework before it became NuGet package.

**Comment by dozer75** [comment]
Wrong button...

**Comment by jbogard** [comment]
So the best I can do for you here is to recommend creating your own expression visitor based on what AutoMapper returns, removing the ToList calls. Then you create your own wrapper extension methods. This is exactly what the AutoMapper.EF6 library does.

If you get something working, I'd be happy to create an AutoMapper.EF4 package that supports EF4-type expressions.

**Comment by dozer75** [comment]
Hmm.. Then we'll have to restructure the whole expression created by the ExpressionBuilder.CreateMapExpression methods. Feeling like it is a bit too much of performance impact doing that.

I think we'll stay on the 4.2.1 version then until we have been able to move the code from .NET 4 and EF 4 to 6.1.3 or more recent of EF.
