### ISSUE TITLE
Setting up type mappings from within "black box" libraries (without exposing clients to Automapper)

### ISSUE THREAD

**Issue by BenLewies** [AutoMapper/AutoMapper#1546]
Hi @jbogard 

I am by no means an Automapper power user, so perhaps I might be doing things in a less-than-optimal way, but here goes:

I have several libraries which I have constructed according to the principles of Onion architecture.  Within these libraries, I extensively make use of Automapper to map objects.  In the past, I used to be able to make use of DynamicMap to map objects to one another.  The distinct advantage thereof was that I did not have to set up type mappings explicitly, but more importantly, my client code did not have to involve setting up type mappings.  

However, after updating the automapper nuget package to version 4.2.1.0, a warning started to appear that the DynamicMap method was obsolete.  I did not experience any noteworthy performance issues with the use of DynamicMap.

So, to keep up to date with developments, I decided to drop the use of the DynamicMap method, and replace it with static mappings.  So, I continued to create the static type mappings for my libraries, and to invoke Mapper.Initialise from within a static method ResolveImplementation() in the infrastructure layer of the library (the purpose of which is to set up my IoC container and perform type mappings on behalf of client / calling code.

I started running into problems during runtime, though, as I would receive error messages such as these:

> [AutoMapperMappingException: Missing type map configuration or unsupported mapping.
> 
> Mapping types:
> Document -> DocumentSnapshot
> xxx.Runtime.Document -> xxx.Archival.Runtime.DocumentSnapshot

From my understanding, this is due to the fact that Mapper.Initialise can only be called once.  Each time you call it, it automatically erases previous type mappings.  However, in my case it is called multiple times: once for each one of my libraries referenced.  

I would essentially like to maintain the black box nature of these libraries and would not want to expose clients to having to set up type mappings in their calling code.

So, I would like to propose two things (if there isn't already a solution that I am not aware of):
1.  Keep the DynamicMap method.  I find it useful.
2.  Provide a way for us to turn off the default overriding behaviour for Mapper.Initialise (whereby it would remove previous mappings automatically).

Thanks

**Comment by lbargaoanu** [comment]
Profiles can help.

**Comment by jbogard** [comment]
DynamicMap is not coming back, ever. In fact, the only purpose of DynamicMap is that you don't know your mappings at compile-time. Looking at your use, you shouldn't be using DynamicMap, you completely lose configuration validation, which makes AutoMapper dangerous to use.

As @lbargaoanu said, you should look at Profiles. I don't buy into the whole "clients shouldn't know they're using AutoMapper", even public SDKs that use AutoMapper expose it directly. But if you insist on jumping through the endless Onion hoops, you can scan all assemblies for Profiles and load them via an Initialize call.

And I can't underscore this enough, dynamically creating mappings for anything but anonymous types is a really REALLY bad idea. You will have silent failures, missing data, and nothing letting you know this has happened. You should not use AutoMapper unless you can call AssertConfigurationIsValid on your mappings.

**Comment by TylerCarlson1** [comment]
If you want DynamicMap like functionality back you can call `Mapper.Initialize(cfg => cfg.CreateMissingMaps = true);` once at start up and just call Mapper.Map in place of Mapper.DynamicMap

I wouldn't suggest it for reasons @jbogard said though.

**Comment by BenLewies** [comment]
Dynamic mapping: dead.  Gotcha :)  All the reasons mentioned added weight at the time to go ahead, update the nuget package and do the static type mappings.

Wrt profiles and assembly scanning, I will take a look at that - I still have to figure out if and how I can apply it to my situation, but it does seem that it will involve, at least some AutoMapper-specific code in client code.  

However, it would help tremendously if, as mentioned in the second alternative, we could perhaps just pass in an optional boolean value to the Mapper.Initialise() method to turn of its default "overriding" behaviour.  

I have no idea how much work this would involve or what the implications of this would be, but it would solve this problem in the simplest possible way.  I don't know how many other devs have this issue, but if there are others and if it is technically feasible, then perhaps something to consider?

Thanks for the excellent library.

**Comment by jbogard** [comment]
That second alternative works today, although I've heavily considered removing it altogether as DynamicMap and its functionality have been abused *so much* beyond what it was intended for.

Mapper.CreateMap also is never coming back, which means Mapper.Initialize will always override configuration. Configuration now is pretty involved, I make several passes over the configuration model to build out the correct mapping plan based on the entire configuration.

Without that, AutoMapper would have to examine the entire configuration for every single type every single time, *just in case* something changed or was added. Which made mapping slooooooow and honestly really hard to understand behind the scenes.

If you haven't noticed yet, I absolutely loathe the onion architecture, at least its manifestation of creating abstractions around everything, saying "I can't reference XYZ library" from certain projects, creating solutions with giant project structures and so on. It's caused so much grief, the more you peel the layers the more it makes you cry. Here's how I escaped the onion mess:

https://vimeo.com/131633177

**Comment by BenLewies** [comment]
@jbogard Jimmy, thank you for the answers, it is much appreciated. 

Yes, indeed, I had a feeling you might not like it :)  

I was actually referring to the second alternative I listed and not the option mentioned by @TylerCarlson1  :  "Provide a way for us to turn off the default overriding behaviour for Mapper.Initialize (whereby it would remove previous mappings automatically).".  No dynamic mapping whatsoever.

So, perhaps have a method signature like this:

    public static void Initialize(System.Action<IMapperConfiguration> action, bool clearPreviousMappings = false)

Apologies for that - I should have been more explicit... I hope this clears up my last question.

PS.  I am definitely going to look at that presentation of yours - looks good!

**Comment by TylerCarlson1** [comment]
Can you do each library has a Profile and then using reflection find all the profiles in said libraries and add them all to your profile?  That would be at the top/application level only where you would initialize.

The other way is to make instances of IMapper and each library has their own that they use to do the mappings, but to do that you might be using a static class to hold that's most likely not an ideal scenario either.  Like LibraryA.Mapper.Map(item), LibraryB.Mapper.Map(item2), ect

**Comment by BenLewies** [comment]
So, here is what I currently have as a solution (and it seems to be working well):

In my library, create a public static method to set up the type mappings for that library:
```
    public static class Mappings
    {
        public static void InitialiseTypeMappings(IMapperConfiguration mapperConfiguration)
        {
            mapperConfiguration.ShouldMapProperty = p => p.GetMethod.IsPublic || p.GetMethod.IsAssembly || p.GetMethod.IsPrivate;
            mapperConfiguration.CreateMap<ChecklistTemplateBase, ChecklistTemplateSnapshotBase>().IgnoreAllNonExisting();
            mapperConfiguration.CreateMap<CheckpointClassBase, CheckpointClassSnapshotBase>().IgnoreAllNonExisting();
            // Etcetera...
        }

        public static IMappingExpression<TSource, TDestination> IgnoreAllNonExisting<TSource, TDestination>(this IMappingExpression<TSource, TDestination> expression)
        {
           // Details of this not important
            return expression;
        }
    }
```

In my client code (which is an Asp.Net MVC project), created the following static class, which calls these static methods from my libraries from within a single Mapper.Initialize invocation:

```
    public static class AutomapperConfig
    {
        public static void InitialiseTypeMappings()
        {
            Mapper.Initialize(i =>
            {
                DocmanTypeMapper.InitialiseMappings();
                ContractsTypeMapper.InitialiseMappings();
            });
        }
    }
```

And which is in turn called from Global.asax as follows:
```
        protected void Application_Start()
        {
            AutofacConfig.Register();
            AutomapperConfig.InitialiseTypeMappings();
            ViewEngines.Engines.Add(new RazorViewEngine());
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }    
```

So, yes, my client code is aware of automapper, but the amount of coding (and knowledge burden) is minimal.

**Comment by jbogard** [comment]
Yes, what @TylerCarlson1, have the client libraries define Profiles. Just like DI configuration, which only should be initialized once.
