### ISSUE TITLE
[aestethic] Missing newline in AssertConfigurationIsValid output

### ISSUE THREAD

**Issue by BrainCrumbz** [AutoMapper/AutoMapper#1547]
```
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters=================================================================================================================
```

Other classes with problems, following this first one, are all separated by a `=` line. So probably there should be a newline after `parameters`.

**Comment by BrainCrumbz** [comment]
BTW, not sure is intended: those `=` lines extend to the right just enough to cover the longest full type name, but not the final text `(Destination member list)`:

```
=================
xxx -> yyy (Destination member list)
aaaaaa -> bbbbbb (Destination member list)
```

**Comment by lbargaoanu** [comment]
PR?

**Comment by BrainCrumbz** [comment]
Yeah, ideally we'd do a PR. It's just that now we're fighting against an AutoMapperMappingException due to a NullReferenceException, and struggling to find the reason. Stacktrace is not really helping.

**Comment by lbargaoanu** [comment]
If it's the latest version, make a repro and we'll help.

**Comment by BrainCrumbz** [comment]
It's the latest stable. Managed to grab a stacktrace with linenumbers after swapping package DLLs with a debug build. Could that help?

At some point at runtime, after passing AssertConfigurationIsValid, when performing a mapping, `Mapper.Map` [here](https://github.com/AutoMapper/AutoMapper/blob/f3e345d958bb999a54c53e73660b51bf6e8c69ee/src/AutoMapper/Mapper.cs#L232) generates a null destination and passes that down to mapper function:

```
var destination = default(TDestination);
return func(source, destination, _defaultContext);
```

That value goes into `ResolutionContext.Map` [here](https://github.com/AutoMapper/AutoMapper/blob/f3e345d958bb999a54c53e73660b51bf6e8c69ee/src/AutoMapper/ResolutionContext.cs#L97):

```
a(source, destination, this);
```

and inside this call (no line number for that invoked code) a NullReferenceException is thrown, I guess because `destination` is null. Now we don't know how to proceed further with investigation.

**Comment by lbargaoanu** [comment]
I'm not that much into guessing :) I need a repro.

**Comment by BrainCrumbz** [comment]
Problem was due to IValueResolver implementation not being registered through DI. Do you know which part of the code is responsible for obtaining value resolvers out of service constructor? Maybe there's place for an exception when resolver cannot be obtained.

**Comment by lbargaoanu** [comment]
Probably [here](https://github.com/AutoMapper/AutoMapper/blob/23278c6128f6c9978c53c3af14a3eea217515b5b/src/AutoMapper/MappingOperationOptions.cs#L28).

**Comment by BrainCrumbz** [comment]
Thanks for initial pointer. It seems like [this bit](https://github.com/AutoMapper/AutoMapper/blob/23278c6128f6c9978c53c3af14a3eea217515b5b/src/AutoMapper/Execution/TypeMapPlanBuilder.cs#L400) in `TypeMapPlanBuilder` has something to do, but from first look it's reasonably convoluted (at the least to someone not used to the library). Will have to look at that again later, or take advantage of more hints.

**Comment by lbargaoanu** [comment]
That will eventually call the function I linked to :)

**Comment by BrainCrumbz** [comment]
Yes, sure. The point is when that function is **actually** called, because when someone will ask for a value resolver to it, that will return null. And maybe that is the cause of null ref. exception.

But it is not really ease (for me, of course) to see where actually the service constructor is invoked, where its return value is grabbed.
