### ISSUE TITLE
Custom value resolvers does not flexible in version 5.x

### ISSUE THREAD

**Issue by cuongdn** [AutoMapper/AutoMapper#1548]
Can you please update Custom value resolvers document for version 5.x?

After I upgrade to version 5.0, many my custom resolvers from one source to multi destination cannot reuse.

In version 5.x, new interface IValueResolver<in TSource, in TDestination, TDestMember> only resolves for one TDestination. So after upgrade, many custom resolvers (TSource => TMember) have to split to many  TSource, in TDestination, TDestMember resolver. 

In version 4.x, the resolver IValueResolver<in TSource, TMember>does not care about Destination, so I think it is more flexible than the latest version or did I miss something in the latest version?

**Comment by jbogard** [comment]
Updated!

**Comment by jbogard** [comment]
And no, you can just use "object" as the destination type. Because I removed the source/destination objects from ResolutionContext, I had to update the interface here.

**Comment by cuongdn** [comment]
I worked. Thank you
