### ISSUE TITLE
Update to 5.0.2 broke existing maps

### ISSUE THREAD

**Issue by sschneider1207** [AutoMapper/AutoMapper#1550]
After updating automapper I'm getting
```
Expression of type 'System.Nullable`1[System.DateTime]' cannot be used for return type 'System.DateTime'
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by jbogard** [comment]
5.0.2?

**Comment by sschneider1207** [comment]
@lbargaoanu Here's a gist of our maps.  There are quite a lot of them though so I don't know how helpful that is.  The error comes after loading the api profile:
https://gist.github.com/sschneider1207/4f099da99e25bf0e3f00b2578687be7a

**Comment by sschneider1207** [comment]
I found one map that was mapping a `DateTime` to a `DateTime?`, commenting that out seemed to get rid of the datetime error and instead throw a similar error for `int?` and `int`.  Seems like it can no longer map a value type to a nullable version

**Comment by lbargaoanu** [comment]
:) You'll have to isolate to smth I can run myself.

**Comment by hbcj** [comment]
Using 5.x, I'm getting the same error when I try to use the Date property of a DateTime property.

using System;
using NUnit.Framework;

namespace AutoMapper.Tests
{
    public class NullableProperty
    {
        public DateTime? Foo { get; set; }
    }

    public class NonNullableProperty
    {
        public DateTime Bar { get; set; }
    }

    public class SomeLogic
    {
        private static IMapper _mapper;

        static SomeLogic()
        {
            var config = new MapperConfiguration(m =>
            {
                // works fine
                //m.CreateMap<NonNullableProperty, NullableProperty>().ForMember(d => d.Foo, o => o.MapFrom(s => s.Bar));

                // System.ArgumentException : Property 'System.DateTime Date' is not defined for type 'System.Nullable`1[System.DateTime]'
                m.CreateMap<NonNullableProperty, NullableProperty>().ForMember(d => d.Foo, o => o.MapFrom(s => s.Bar.Date));
            });

            _mapper = config.CreateMapper();
        }
    }

    [TestFixture]
    public class SomeLogicTest
    {
        [Test]
        public void SomeTest()
        {
            var someLogic = new SomeLogic();
        }
    }
}

**Comment by lbargaoanu** [comment]
@hbcj That looks like a different problem, so please open another issue.

**Comment by sschneider1207** [comment]
@lbargaoanu I think thats the same issue.  I simplified the date mapping that seemed to be causing my issue to this:
```
public class Nullable
    {
        public DateTime? Foo { get; set; }
    }

    public class NonNullableWrapper
    {
        public NonNullableInner[] Bars { get; set; }
    }

    public class NonNullableInner
    {
        public DateTime Bar { get; set; }
    }

Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<NonNullableWrapper, Nullable>()
                .ForMember(m => m.Foo, opt =>
                {
                    opt.Condition(src => src.Bars != null && src.Bars.Length > 0);
                    opt.MapFrom(src => src.Bars.Min(b => b.Bar));
                });
            });

**Comment by lbargaoanu** [comment]
I don't know, but I see different error messages.

**Comment by sschneider1207** [comment]
Do you get an error from just the map I posted?  I thought I isolated the other maps when running that but I may have missed one :/

**Comment by hbcj** [comment]
Not sure if it's different or not, but as requested, I posted a new issue with the work-around I'm using for now.  #1552

**Comment by lbargaoanu** [comment]
@sschneider1207 This works with the MyGet build. You can close the issue.

**Comment by sschneider1207** [comment]
@lbargaoanu I get `Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.` when trying to install the MyGet build.  Have you seen this before?

**Comment by lbargaoanu** [comment]
Try upgrading Nuget.

**Comment by sschneider1207** [comment]
Im fairly sure I'm already at the most up to date version, I'm on NuGet 3.4.4.1321
