### ISSUE TITLE
Mapping same object second time returns reference to the object mapped earlier

### ISSUE THREAD

**Issue by PavelloCz** [AutoMapper/AutoMapper#1551]
Hello, maybe im missing something but that's big problem for my code.
Lets assume that we have Parent and Child objects - they refers to each other like
`public Parent`
`{`
`            public string name { get; set; }`
`            public ICollection<Child> children { get; set; }`
`}`
`public Child`
`{`
`            public string name { get; set; }`
`            public Parent parent { get; set; }`
`}`
And corresponding models ParentModel and ChildModel
So i created map with .PreserveReferences() like
`CreateMap<Parent, ParentModel>().PreserveReferences();`
`CreateMap<Child, ChildModel>().PreserveReferences();`
to avoid StackOverflowException while mapping. The issue is if i will map in example some Parent object twice, even with different data i'll get reference to the same object:
`Parent _testParent.name = new Parent() { name = "x" };`
`ParentModel _testParentModel1= Mapper.Map<ParentModel >(_testParent);`
`Parent _testParent.name = new Parent() { name = "xxx" };`
`ParentModel _testParentModel2= Mapper.Map<ParentModel >(_testParent);`

After this _testParentModel2 is reference to _testParentModel1.
Is it possible to map same object multiple times and get two separated objects when mapping without `.PreserveReferences()` causes StackOverflowException ?

**Comment by lbargaoanu** [comment]
This should be fixed by #1523.
