### ISSUE TITLE
.NET support

### ISSUE THREAD

**Issue by expand** [AutoMapper/AutoMapper#1553]
from what I see in the Nuget this framework does not utilize any of .NET4.5.2 features, so it would be great if you compile it against .NET4 so to have it in the endless XP and WinServer2003 machines out there which do not support .NET4.5.2

**Comment by jbogard** [comment]
It's not .NET 4.5.2, it's .NET 4.5
https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/project.json#L47

but you can certainly try to target .NET 4.0 if you pull down the code. The
last time I tried I think I hit some major problems in the reflection API.

**Comment by expand** [comment]
I can live with a slow .NET4 compatible version at the moment

**Comment by jbogard** [comment]
Just tried to build in .NET 4.0 got a bazillion compile errors. Sorry :(

More sorry that you have a bunch of Windows XP machines to deal with, yikes!

**Comment by expand** [comment]
I personally do not, however same as you I do support a framework
https://github.com/expand/eXpand/ and my users have such clients. I took a
bad decision upgrading to .NET452 lately and I am now downgrading.
