### ISSUE TITLE
ForSourceMember usage

### ISSUE THREAD

**Issue by ShawnWeaver** [AutoMapper/AutoMapper#1556]
I've been trying to figure out how to use the `ForSourceMember` mapping in AutoMapper to do something similar to this question on [StackOverflow](http://stackoverflow.com/questions/28382811/how-to-configure-automapper-to-automatically-ignore-properties-with-readonly-att). Unfortunately, the accepted answer there doesn't actually describe how to fix the problem using `ForSourceMember` - it uses the `ForMember` mapping which I think only works because the source and destination properties have the same name. I'm still left wondering how `ForSourceMember` _should_ work.

I've written several test cases to try to make something work the way I'd expect, and they all work something like this:

		[TestMethod]
		public void IgnoresIgnoredSourceMembersWhenMappingToExistingObject()
		{
			//ARRANGE
			var configuration = new MapperConfiguration(config =>
														{
															config.CreateMap<Source, Destination>()
																  .ForSourceMember(x => x.ReadOnlyValue, cfg => cfg.Ignore());
														});

			var mapper = configuration.CreateMapper();

			var source = new Source { Name = "John Doe", ReadOnlyValue = "Jane Doe" };
			var dest = new Destination { Name = "Steve", ReadOnlyValue = "Bob" };

			//ACT
			mapper.Map(source, dest);

			//ASSERT
			Assert.AreEqual(source.Name, dest.Name);
			Assert.AreEqual("Bob", dest.ReadOnlyValue); //Fails. Destination value is "Jane Doe"
		}

		private class Source
		{
			public string Name { get; set; }
			public string ReadOnlyValue { get; set; }
		}

		private class Destination
		{
			public string Name { get; set; }
			public string ReadOnlyValue { get; set; }
		}

I'm not familiar with how AutoMapper works internally, but I'd expect it to treat `Source.ReadOnlyValue` as "invisible" for the mapping; when it attempts to map that property, it wouldn't find a match for `Destination.ReadOnlyValue` since the source property has been ignored and leave whatever value is already on the destination (the default for a new object or the existing value on an existing object).

This case can be worked around using the method described in the StackOverflow question since the source and destination properties have the same name, but I'm running into an issue when it comes to AutoMapper's automatic flattening:

		[TestMethod]
		public void IgnoresIgnoredSourceMembersWhenMappingToExistingObject()
		{
			//ARRANGE
			var configuration = new MapperConfiguration(config =>
														{
															config.CreateMap<Source, Destination>()
																  .ForSourceMember(x => x.Child, cfg => cfg.Ignore());
														});

			var mapper = configuration.CreateMapper();

			var source = new Source { Name = "John Doe", Child = new Child { Name = "Jane Doe" } };
			var dest = new Destination { Name = "Steve", ChildName = "Bob" };

			//ACT
			var result = mapper.Map(source, dest);

			//ASSERT
			Assert.AreEqual("Bob", dest.ChildName); //Fails. ChildName = "Jane Doe"
		}

		private class Source
		{
			public string Name { get; set; }
			public Child Child { get; set; }
		}

		private class Destination
		{
			public string Name { get; set; }
			public string ChildName { get; set; }
		}

		private class Child
		{
			public string Name { get; set; }
		}
		
My goal here is to have the `Child` property on the source be ignored, so `ChildName` on the destination will be left unmapped. (With the end goal being an extension method approach as the StackOverflow question.)

Is this possible with AutoMapper? Is there a simpler way to design these mappings that I'm overlooking?

**Comment by jbogard** [comment]
ForSourceMember is only meant for reverse-mapping scenarios or for
situations where you're validating the source members. AutoMapper uses the
destination members as the target to map to by default. You should use
ForMember and Ignore.

**Comment by ShawnWeaver** [comment]
So how should it work in the case of a reverse map? The tests in the source all seem to be using it simply for validation, so I'm not sure what's expected (if anything) aside from affecting how validation is handled.

**Comment by jbogard** [comment]
Yep, it's just for validation. If you want something more, take a look at ForAllMembers.

**Comment by ShawnWeaver** [comment]
I'll see if I can make ForAllMembers work. If not, I'll simply handle the mappings explicitly. Thanks!

**Comment by matthiaslischka** [comment]
> ForSourceMember is only meant for reverse-mapping scenarios or for
situations where you're validating the source members.

I see, but unfortunately that's not what one would assume based on how the code reads. Is there a special reason why it shall not work with SourceMember ignore just as well? could be a easy fix to clean things up, couldn't it?

**Comment by jbogard** [comment]
What, if the names just happen to match up, then ignore the destination member of the same name?

**Comment by matthiaslischka** [comment]
Sry, I don't get your point.
However, simply spoken, what I mean: If something is "ForSourceMember-ignored" it should be ignored as data source. :/ Sounds to easy to satisfy your point - that I don't get yet. Maybe you could explain with an example?

I had added a very simple example at my duplicate (sorry) issue: https://github.com/AutoMapper/AutoMapper/issues/2000

BR,
Matthias

**Comment by Kukkimonsuta** [comment]
@jbogard I'd like to ask whether you'd consider reopening this issue for further discussion. We've got caught off guard by this as well as number of other people filling issues - from our point of view we've already ignored the property and we absolutely did not expect it to map since we've explicitly written to ignore it.

The documentation also says `Ignore this member for configuration validation and skip during mapping`, so even though this may be breaking change for some, it would be reasonable breaking change since it's documented with behavior we expect.

The current behavior could also be introduced with new `IgnoreValidation` or such (and may be beneficial even on the destination members) that would skip the property on `AssertConfigurationIsValid` and would have more representative name to what it does.

**Comment by mrpmorris** [comment]
I just got caught out by this. I am going to have to go and change my code where I have made this assumption and change it to ForMember. Perhaps this method should be marked Obsolete and a new one added called something like ForReverseMappedMember?

**Comment by RCP161** [comment]
Good idea. I was running in the same situation and was searching a while for this answer.

**Comment by BRM013** [comment]
I was running into an issue where I was using:

`CreateMap<TSource, TDest>(MemberList.Source)
.ForSourceMember(src => src.ArrayToIgnore, o => o.Ignore());`

and the exception that was getting raised was that the mapping from TSource => TDest was missing the ArrayToIgnore property. It actually took me a while to realise that my TDest source had the ArrayToIgnore property as well, therefore I needed to use .ForMember->Ignore... 

I'm a little confused now as to what the MemberList.Source does. I was hoping that it would only be mapping the TSource properties to the TDest entity where the .ForSourceMember was not ignored. The weird part is that the TDest actually has other members that the TSource doesn't, but AutoMapper doesn't complain about them not being ignored, only the Array property.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html#forsourcemember-ignore
