### ISSUE TITLE
Can't Install AutoMapper to a Xamarin Forms Portable Project

### ISSUE THREAD

**Issue by mrbiggred** [AutoMapper/AutoMapper#1561]
I'm trying to install AutoMapper 5.0.2 (the latest stable) via NuGet to a Xamarin Portable project and get the following error:

> Could not install package 'AutoMapper 5.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm using Visual Studio 2015 with Xamarin 4.1.1.3.  I'm using Xamarin Forms 2.3.0.107.  Finally my targets selected are:

- .NET Framework 4.5
- Windows 8
- Windows Phone Silverlight 8
- ASP.NET Core 1.0
- Xamarin.Android
- Xamarin.iOS
- Xamarin.iOS (Classic)

Thanks in advance.

**Comment by jbogard** [comment]
Try the MyGet build.

**Comment by mrbiggred** [comment]
I tried installing using the latest alpha build on MyGet and still get the same error:

> Could not install package 'AutoMapper 5.1.0-alpha-01190'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Anything else I can try?  Any other information I can provide to help you with this issue?  Is the problem on my end?  Thank you.

**Comment by jbogard** [comment]
Ah, I missed that you're targeting Windows Phone Silverlight 8. I don't
support Silverlight. I support Profile111, which is that list minus WP8

**Comment by mrbiggred** [comment]
Changing my profile fixed the problem.  Thank you.
