### ISSUE TITLE
Automapper custom type converter source and destination type

### ISSUE THREAD

**Issue by sjoerd222888** [AutoMapper/AutoMapper#1563]
With custom type converters that implement the inferface ITypeConverter<T1, T2> it is possible to make a custom conversion by type.

What I would like to access is the following. In a custom converter, let's say ITypeConverter<TInterfac1, TInterfac2> I know that I am converting a property of a class and I would like to know the exact type of the destination. For the source this would not be a problem because I can use reflection, for the destination I cannot because it is a null instance.

Is there some way in Automapper that I can learn about where the conversion is happen currently? For example to learn that he is currently mapping memberA of this instance to memberB of this other instance. That I can access the parent instance (source and destination) if it exists? Or can I somehow access the MemberInfo of source or destination? I am mainly in the real type of the the destination, so if you know how to access this in other means please tell (maybe there somewhere exists a DestinationType and SourceType variable I could access).

The reason why I am looking for such information is that I want to do some things in a generic way without having to write member based conversion by hand (and of course I will cache the reflection data to achieve higher performance).

**Comment by jbogard** [comment]
Take a look at this #1414 and let me know if it would fit for you.

Type converters are a bit of a sledgehammer, not a precision tool like you're asking for.

**Comment by lbargaoanu** [comment]
Right now, you have ForAllMaps, ForAllMembers and ForAllPropertyMaps that can help with generic mapping.

**Comment by sambauwens** [comment]
I have a similar problem, I need to know the destination type in a `ForAllOtherMembers(o => o.Condition((source, dest, sourceMember, destinationMember, context) => { ... }))` where the `destinationMember` passed to the `Condition` lambda is `null`, which means I can't use `GetType` on it. I looked in the ResolutionContext passed and couldn't get hold of the type of the destination member anywhere.

**Comment by lbargaoanu** [comment]
@sambauwens Upgrade and you'll get the destination.

**Comment by sambauwens** [comment]
I already have version 5.1.1 which seems to be the latest version, is there something new in that version that allows me to get the destination member type somehow?

**Comment by lbargaoanu** [comment]
My bad. You need the MyGet build. See #1634.
