### ISSUE TITLE
Feature request: constructor arguments for open generic resolver

### ISSUE THREAD

**Issue by sjoerd222888** [AutoMapper/AutoMapper#1564]
With open generics the following is possible:

    cfg.CreateMap(typeof(GenericSourceType<>), typeof(GenericDestType<>))
         .ConvertUsing(typeof(MyConverter<,>));

With `MyConverter` looking like this:

    public class MyConverter<TSource, TDest>
         : ITypeConverter<GenericSourceType<TSource>, GenericDestType<TDest>>
    {
        //..
    }

It is not possible to pass a constructor argument. To support this it would be nice to allow passing an existing converter instance, e.g. like this:

    cfg.CreateMap(typeof(GenericSourceType<>), typeof(GenericDestType<>))
         .ConvertUsing((MyConverter<,>, new object[]{myParam}));

such that `MyConverter` can look like this:

    public class MyConverter<TSource, TDest>
         : ITypeConverter<GenericSourceType<TSource>, GenericDestType<TDest>>
    {
        public MyConverter (object myParam){
             //..
        }

        //..
    }

Would this make sense? Would this be feasible?

**Comment by lbargaoanu** [comment]
You can simply pass the converter you construct yourself. There is an overload for that.

**Comment by sjoerd222888** [comment]
I don't see an overload for this. `ConvertUsing` has two overloads in this case. one taking no parameters and another one just taking the type. I am using Automapper 5.0.2.0.

**Comment by lbargaoanu** [comment]
Yes, for a concrete map, obviously :) For the generic case you can route it through your DI container.

**Comment by jbogard** [comment]
No.....you need to use dependency injection in this case. I can't supply an overload that only works for open generics, I'd need a totally separate one. Look at ConstructServicesUsing and control the instantiation via that.
