### ISSUE TITLE
ConvertUsing from value type to the same value type doesn't work

### ISSUE THREAD

**Issue by vgrokk** [AutoMapper/AutoMapper#1566]
In 4.2 this worked properly(to use ConvertUsing to configure map between struct to nullable struct ) and in the 5.0 it doesn't work

       static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<int, int?>()
                 .ConvertUsing<IntToNullableConverter>();

                cfg.CreateMap<Source, Target>();

            });
            Mapper.AssertConfigurationIsValid();
            var source = new Source();
            
            var result = Mapper.Map<Source, Target>(new Source());

            Assert.Null(result.Id);
        }
    }
  
     public class IntToNullableConverter : ITypeConverter<int, int?>
    {
        public int? Convert(int source, int? destination, ResolutionContext context)
        {
            if (source == default(int))
                return null;

            return source;
        }
    }

    public class Source
    {
        public int Id { get; set; }
    }

    public class Target
    {
        public int? Id { get; set; }
    }

I still get the default int

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by vgrokk** [comment]
Still the same

**Comment by lbargaoanu** [comment]
Yes, I see it too. The converter is not called.
