### ISSUE TITLE
ForAllMaps not working when using Mapper.Initialize()

### ISSUE THREAD

**Issue by JesperRisager** [AutoMapper/AutoMapper#1569]
Using AutoMapper 4.2.1 since 5.0 doesn't work without VS 2013 in our current nuget setup.

I recently upgraded to a new version of AutoMapper and noticed Mapper.Configuration is now marked Obsolete

The problem is that I can not get ForAllMaps() method to work if I am not using Mapper.Configuration.

Old code that works: 

(Is called after I configure all my mappings and adds a call to AfterMap on all objects that implement IViewObject)

```
private void ConfigureAutoMapperToCallAfterMappingForAllViewObjects()
        {
            Mapper.Configuration.ForAllMaps((typeMap, map) =>
                map.AfterMap((src, dest) =>
                {
                    IViewObject viewObj = dest as IViewObject;
                    if (viewObj == null)
                        return;

                    // We do not want to call AfterMapping when cloning objects.
                    // Besides not being needed it also leads to stackoverflows.
                    if (src.GetType() == dest.GetType())
                        return;

                    // All ViewObjects should automatically call AfterMapping after we map TO them.
                    viewObj.AfterMapping();
                }));
        }
```

new code that does not work:

```
protected virtual void ConfigureAutoMapper()
        {
            Mapper.Initialize(cfg =>
            {
                AddAutoMapperProfiles(cfg);
                ConfigureAutoMapperToCallAfterMappingForAllViewObjects(cfg);
            });
        }

protected virtual void AddAutoMapperProfiles(IMapperConfiguration cfg)
        {
            cfg.AddProfile<ApplicationLayerAutoMapperProfile>();
        }

protected void ConfigureAutoMapperToCallAfterMappingForAllViewObjects(IMapperConfiguration cfg)
        {
            cfg.ForAllMaps((typeMap, map) =>
                map.AfterMap((src, dest) =>
                {
                    var viewObj = dest as IViewObject;
                    if (viewObj == null)
                        return;

                    // We do not want to call AfterMapping when cloning objects.
                    // Besides not being needed it also leads to stackoverflows.
                    if (src.GetType() == dest.GetType())
                        return;

                    // All ViewObjects should automatically call AfterMapping after we map TO them.
                    viewObj.AfterMapping();
                }));
        }
```

The inner part of ForAllMaps never gets called and because of that Map.AfterMap() will not be added to the MapperConfiguration either.

Why is this? And what is actually the prefered way to add a call to AfterMapping() on all objects that implement IViewObject?

I have already spent a lot of hours looking for information on ForAllMaps or anything else that could help me out, but couldn't find any.

**Comment by TylerCarlson1** [comment]
you need to make `ConfigureAutoMapperToCallAfterMappingForAllViewObjects` call the profile `ApplicationLayerAutoMapperProfile` or add it to the profile not the configuration on top of it.

**Comment by jbogard** [comment]
@TylerCarlson1 the ForAllMaps in the root config is supposed to affect *all* maps

**Comment by TylerCarlson1** [comment]
Bug then?  It goes to the defaultProfile which is separate from all the other profiles.
All Profile expressions go to the default mapper in cfg.

There's also an override to provide the profile's name that will apply to that profile.

**Comment by JesperRisager** [comment]
I am currently using the following workarround:

```
protected void ConfigureAutoMapperToCallAfterMappingForAllViewObjects(IMapperConfiguration cfg)
{
    cfg.ForAllMaps((typeMap, map) =>
        map.AfterMap((src, dest) =>
        {
            var viewObj = dest as IViewObject;
            if (viewObj == null)
                return;

            // We do not want to call AfterMapping when cloning objects.
            // Besides not being needed it also leads to stackoverflows.
            if (src.GetType() == dest.GetType())
                return;

            // All ViewObjects should automatically call AfterMapping after we map TO them.
            viewObj.AfterMapping();
        }));
}

```

**Comment by JesperRisager** [comment]
Whoops closed it by mistake.

What I meant to write is that I am currently using the following workarround:

```
protected void ConfigureAutoMapperToCallAfterMappingForAllViewObjects(MapperConfiguration cfg)
        {
            var typeMaps = cfg.GetAllTypeMaps();
            foreach (var typeMap in typeMaps)
            {
                if (!typeof (IViewObject).IsAssignableFrom(typeMap.DestinationType)) 
                    continue;

                // We do not want to call AfterMapping when cloning objects.
                // Besides not being needed it also leads to stackoverflows.
                if (typeMap.SourceType == typeMap.DestinationType)
                    return;

                // All ViewObjects should automatically call AfterMapping after we map TO them.
                typeMap.AddAfterMapAction((src, dest) => ((IViewObject)dest).AfterMapping());
            }
        }
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by jbogard** [comment]
This fails:

```
    public class ForAllMaps_WithAfterMap : AutoMapperSpecBase
    {
        public interface IObject
        {
            int Value { get; }
        }

        public interface IViewObject : IObject
        {
            void AfterMapping();
        }

        public class Source
        {
            public int Value { get; set; }
        }

        public class Dest1 : IObject
        {
            public int Value { get; set; }
        }

        public class Dest2 : IViewObject
        {
            public void AfterMapping()
            {
                Value++;
            }

            public int Value { get; set; }
        }

        protected override MapperConfiguration Configuration { get; } = new MapperConfiguration(cfg =>
        {
            AddProfiles(cfg);
            ConfigureAutoMapperToCallAfterMappingForAllViewObjects(cfg);
        });

        private static void ConfigureAutoMapperToCallAfterMappingForAllViewObjects(IMapperConfigurationExpression cfg)
        {
            cfg.ForAllMaps((typeMap, map) =>
                map.AfterMap((src, dest) =>
                {
                    IViewObject viewObj = dest as IViewObject;
                    if (viewObj == null)
                        return;

                    // We do not want to call AfterMapping when cloning objects.
                    // Besides not being needed it also leads to stackoverflows.
                    if (src.GetType() == dest.GetType())
                        return;

                    // All ViewObjects should automatically call AfterMapping after we map TO them.
                    viewObj.AfterMapping();
                }));
        }

        private static void AddProfiles(IMapperConfigurationExpression cfg)
        {
            cfg.AddProfile<FooProfile>();
        }

        public class FooProfile : Profile
        {
            public FooProfile()
            {
                CreateMap<Source, Dest1>();
                CreateMap<Source, Dest2>();
            }
        }

        [Fact]
        public void Should_not_call_after_map_for_dest1()
        {
            var dest = Mapper.Map<Source, Dest1>(new Source {Value = 5});

            dest.Value.ShouldEqual(5);
        }

        [Fact]
        public void Should_call_after_map_for_dest2()
        {
            var dest = Mapper.Map<Source, Dest1>(new Source {Value = 5});

            dest.Value.ShouldEqual(6);
        }


    }

```

**Comment by lbargaoanu** [comment]
I think you have a typo in there. So if you really map to Dest2, the test passes. Right? :)

**Comment by jbogard** [comment]
Blarg

**Comment by lbargaoanu** [comment]
Nice try anyway. It's indestructible :) The dark art of the repro.

**Comment by jbogard** [comment]
@JesperRisager One difference between mine and yours is I'm using a `IMapperConfigurationExpression` to do configuration and you have `IMapperConfiguration` in your original example.

**Comment by lbargaoanu** [comment]
Maybe it would be easier to test with the MyGet build. Because if that works, there's nothing to fix :) Otherwise, a repro would help.

**Comment by jbogard** [comment]
No, I don't have a way of reproducing it. It looks like our examples are slightly off - you use something that isn't "IMapperConfigurationExpression" to configure the profiles etc. and my test passes.

**Comment by TylerCarlson1** [comment]
@jbogard maybe 4.2.1 has that interface and 5.0 has what you used.

Also the interface probably doesn't matter because both code bases, I think, Profile is the only class that implements ForAllMaps function.  And as I sad [before](https://github.com/AutoMapper/AutoMapper/issues/1569#issuecomment-235358268) call this against the profile that's created, or turn this into a bug stating that config options don't persist to sub profiles.

I personally see this as intended functionality, with cfg being a shortcut to creating a new profile, but when you create sub profiles they are completely independent of each other, and the config at the top.  When you make new profiles you should be using the function calls for them in their own configs and not at the top level anyways.

**Comment by TylerCarlson1** [comment]
Or to put it another way, the function in question is contract of `void IProfileExpression.ForAllMaps(Action<TypeMap, IMappingExpression> configuration)` and thus it's meant at the profile level.  There's also `void IConfiguration.ForAllMaps(string profileName, Action<TypeMap, IMappingExpression> configuration)` which is on an configuration overall level.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by JesperRisager** [comment]
Yeah I agree, since it seems like consensus now is, I could just use the above mentioned IMapperConfigurationExpression or my current workarround.
