### ISSUE TITLE
Automapper 5.x Issue with constructor

### ISSUE THREAD

**Issue by adoris** [AutoMapper/AutoMapper#1574]
I have issue with Version 5.x (tested with 5.0.2 and latest 5.1.-alpha):
if i map class with child class:

```
 public class ChildClassDTO
        {
            public int Id { set; get; }
        }

        public class ParentClassDTO
        {
            public int Id { set; get; }
            public ChildClassDTO Child { set; get; }
        }

        public class ChildClass
        {
            public int Id { set; get; }
        }

        public class ParentClassWithoutConstructor
        {
            public int Id { set; get; }
            public ChildClass Child { set; get; }
        }

        public class ParentClassWithConstructor
        {
            public ParentClassWithConstructor(ChildClass ch)
            {
            }

            public int Id { set; get; }
            public ChildClass Child { set; get; }
        }
           var childClassDto = new ChildClassDTO()
            {
                Id = 1,
            };
            var parentClassDto = new ParentClassDTO()
            {
                Id = 2,
                Child = childClassDto,
            };

            var childClass = mapper.Map<ChildClassDTO, ChildClass>(childClassDto);
            Assert.AreEqual(childClassDto.Id, childClass.Id);

            var parentClassWithConstructor = mapper.Map<ParentClassDTO, ParentClassWithConstructor>(parentClassDto);

            Assert.AreEqual(parentClassWithConstructor.Id, parentClassDto.Id);
            Assert.AreNotEqual(null, parentClassWithConstructor.Child); // Test fails

  var parentClassWithoutConstructor = mapper.Map<ParentClassDTO, ParentClassWithoutConstructor>(parentClassDto);

            Assert.AreEqual(parentClassWithoutConstructor.Id, parentClassDto.Id);
            Assert.AreNotEqual(null, parentClassWithoutConstructor.Child); // Test OK
```

What's wrong in this code?
Unit Test attached.

Thanks for great Mapper!

[AutoMapperTest3.zip](https://github.com/AutoMapper/AutoMapper/files/391129/AutoMapperTest3.zip)

**Comment by lbargaoanu** [comment]
How is AutoMapper supposed to create ParentClassWithConstructor? If you call AssertConfigurationIsValid it will complain.

**Comment by lbargaoanu** [comment]
OK, so the example in the zip is different :) That should work.

**Comment by lbargaoanu** [comment]
So in the real code, you don't set the patient in the constructor? :) If that's the case, just close the issue.

**Comment by adoris** [comment]
I use AutoMapper in production code. I prefere not to use a libraries with unpredictable behavior. This bahavior with constructor is inconsequent. Please fix this issue and include this unit test to list of tests.
What problem with the patient in the constructor? :)

**Comment by lbargaoanu** [comment]
AutoMapper calls your constructor expecting that it will set the patient property. It doesn't. That's the bug. AM behaves as expected. You can disable constructor mapping if you don't use it.

**Comment by adoris** [comment]
Why AutoMapper exect, that property will be set in constructor? It is possible, that only some infos from constructor parameter will be taken. 
Why is mapping priority of constructor is higher as property mapping? I would expect, that mapping with constructor must be set explizitly, and property mapping is used by default.
How can i disable constructor mapping? Can you please write a topic in wiki?

**Comment by masterpoi** [comment]
I agree, this behavior has changed from 4.x and is not documented here: https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide

**Comment by lbargaoanu** [comment]
It's a wiki guys, add something useful :)

**Comment by masterpoi** [comment]
Sure but
a) is this change intentional or not?
b) how exactly does the constructor selection work now?

And please don't tell me to go read the source code.

**Comment by lbargaoanu** [comment]
There's only one constructor here.

**Comment by masterpoi** [comment]
Yes in this case there is. But i also noticed where 4.x selected the default constructor, 5.0 uses a parameterized one (if there are multiple). But ic this is probably another issue altogether.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jbogard** [comment]
@adoris can you update the example above? I don't want to download a zip file to see what your config is.

**Comment by adoris** [comment]
example updated.
In version 5.1.0-alpha-01198 an parameterless constructor required. With parameterless constructor tests are OK.
