### ISSUE TITLE
Issue mapping to ExpandoObject in v5.0.2

### ISSUE THREAD

**Issue by JordanMarr** [AutoMapper/AutoMapper#1580]
Mapping an object to an ExpandoObject does not create a new ExpandoObject; instead, it simply passes the source object through to the target object.  The resulting bug is that the source object and the target object end up both being the same (source) object.  

Reverting to v4.2.1 fixed the issue.  

Pseduo code to recreate:
```
Person person = new Person { FName = "John" };
dynamic dynaDude = Mapper.Map<ExpandoObject>(person);
Assert.AreNotEqual(person.GetHashCode(), dynaDude.GetHashCode(), "SOURCE AND TARGET ARE THE SAME");
```

**Comment by lbargaoanu** [comment]
Map will return an ExpandoObject. Person is not an ExpandoObject. How could they possibly be the same object? :)

**Comment by lbargaoanu** [comment]
Or Person is actually an ExpandoObject?

**Comment by lbargaoanu** [comment]
No, ExpandoObject is sealed.

**Comment by JordanMarr** [comment]
Right!  It's _supposed_ to return an ExpandoObject, but it doesn't for me!
It still compiles because "dynaDude" is a dynamic, so it doesn't check the type.
That's the bug.  :)

**Comment by lbargaoanu** [comment]
Mapper.Map< ExpandoObject >(person) is not dynamically dispatched. The result is an ExpandoObject. You're missing something.

**Comment by JordanMarr** [comment]
According to this WIKI page, I should be able to map to a dynamic ExpandoObject:
https://github.com/AutoMapper/AutoMapper/wiki/Dynamic-and-ExpandoObject-Mapping

Here are my test projects (one for v4.2.1 and another for v5.0.2) so you can see for yourself.  _It works just fine in v4.2.1_.

**v4.2.1 PASSES**
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using AutoMapper;
using System.Dynamic;

namespace AutoMapperTests_421
{
	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestMethod1()
		{
			Person person = new Person { FName = "John" };
			dynamic dynaDude = Mapper.Map<ExpandoObject>(person);
			Assert.AreNotEqual(person.GetHashCode(), dynaDude.GetHashCode(), "SOURCE AND TARGET ARE THE SAME");
		}
	}

	public class Person
	{
		public string FName { get; set; }
	}
}
```
**v5.0.2 FAILS**
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Dynamic;
using AutoMapper;

namespace AutoMapperTests_502
{
	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestMethod1()
		{
			Person person = new Person { FName = "John" };
			Mapper.Initialize(cfg => { });
			dynamic dynaDude = Mapper.Map<ExpandoObject>(person);
			Assert.AreNotEqual(person.GetHashCode(), dynaDude.GetHashCode(), "SOURCE AND TARGET ARE THE SAME");
		}
	}

	public class Person
	{
		public string FName { get; set; }
	}
}
```

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by lbargaoanu** [comment]
Because of a fixed bug, your example doesn't even run with 5.0.2.

**Comment by JordanMarr** [comment]
Sorry, I forgot to mention that I had to manually add the Microsoft.CSharp library to the 5.0.2 version to get it to compile.

**Comment by lbargaoanu** [comment]
I guess it doesn't matter that we don't see the same behavior. If it works with the MyGet build, the issue can be closed.

**Comment by JordanMarr** [comment]
So you're saying that my tests give different results for you?

**Comment by lbargaoanu** [comment]
Exactly :) And they do make sense.

**Comment by JordanMarr** [comment]
> Exactly :) And they do make sense.

How is it possible that you got different results than me if we are both using the exact same versions?  I've never heard of MyGet before, but I got v5.0.2 off of NuGet.  But why would it even matter where I got it from?  v5.0.2 is v5.0.2 regardless of which repository I got it from.

**Comment by lbargaoanu** [comment]
Well, there is one thing I can say for sure. The problem is not with AutoMapper. Exactly what happens in your environment, I don't know.

**Comment by JordanMarr** [comment]
FYI, I just tried to get v5.0.2 from MyGet and it also fails for me.

**Comment by lbargaoanu** [comment]
Yes, but the latest works fine.

**Comment by JordanMarr** [comment]
Is there a version that is newer than 5.0.2?  I thought that was the latest.

**Comment by lbargaoanu** [comment]
5.1.0-alpha-01194

**Comment by JordanMarr** [comment]
Ahh I see.  The alpha version does indeed work for me.

Thanks!
