### ISSUE TITLE
Not very heplful exception when mapping from bool to bool?

### ISSUE THREAD

**Issue by zihotki** [AutoMapper/AutoMapper#1583]
The exception message is "System.InvalidOperationException: Rewriting child expression from type 'System.Boolean' to type 'System.Nullable`1[System.Boolean]' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite." 

It's easy to understand what happened and why but completely not possible to identify the place where it happened, for which models. Imagine situation, you have a big project which used some old version of AutoMapper, they decided to migrate to new version because of performance improvements and they've got that exception. There may be hundreds of mappings, good luck finding the one which fails. 

Probably it worth to catch the exception somewhere at the upper level in AutoMapper and wrap it in additional exception providing the information about models if possible.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by zihotki** [comment]
@lbargaoanu thanks for fast reply. Yes, it works without issues. Is there any estimate when 5.1 will be released?

**Comment by lbargaoanu** [comment]
@jbogard would know.

**Comment by jbogard** [comment]
5.1 is out!
