### ISSUE TITLE
Help - Convert from Func<Iqueryable<>, IOrderedQueryable>

### ISSUE THREAD

**Issue by roopeshkumar** [AutoMapper/AutoMapper#1585]
Hi,
  Am having hard time converting the below. Any help will be appreciated.

Convert From
```
Mapping Func<IQueryable<tblObjectPermissionViewModel>, IOrderedQueryable<tblObjectPermissionViewModel>
```
Convert to
```
Mapping Func<IQueryable<tblObjectPermission>, IOrderedQueryable<tblObjectPermission>
```
Thanks
Roopesh

**Comment by TylerCarlson1** [comment]
can you make a gist to replicate your problem?

Also the generics got taken out most likely in your post

**Comment by roopeshkumar** [comment]
Hi Tyler,
         Sorry about that. I have put it in gist. the below is the link
https://gist.github.com/roopeshkumar/c28e1b3be4c811ffc33e54e873abbfd3

I really appreciate your help
Thanks
Roopesh

**Comment by TylerCarlson1** [comment]
Hmm that looks complicated.  What version of AutoMapper are you using?  I see CreateMap which isn't available in the last few versions.

What you might want to look at it [UseAsDataSource](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)#useasdatasource), because it's meant to do these kinds of translations.

Ex:
```
Expression<Func<tblObjectPermissionViewModel, bool>> filter;
Expression<tblObjectPermissionViewModel, object> orderBy;
return db.tblObjectPermissions.UseAsDataSource().As<tblObjectPermissionViewModel>().Where(filter).OrderBy(orderBy);
```
Don't translate order by function but the expression passed into OrderBy.

**Comment by roopeshkumar** [comment]
Am using 3.2.1.0. I will try your ex. and keep you posted. Thanks again for your help.

Thanks
Roopesh

**Comment by TylerCarlson1** [comment]
3.2.1 probably doesn't use UseAsDataSource.  I would recommend upgrading if you can.  If you can't upgrade I would recommend converting the lambda in OrderBy using your Expression visitor you converted filter as the example I had before shows.

**Comment by roopeshkumar** [comment]
the db context is closed . Am using Generic repository pattern with Unit of work. I tried using the latest version of automapper but it's not installing successfully in VS 2013. I tried updating my NuGet Package manager, still couldn't install. I have used the older version 3.2.1 and it was working in my previous projects.That's why I'm using the older version. As suggested in Automapper documentation am using the below and it's throwing exception mapping "Missing type map configuration or unsupported mapping." Not sure what am making mistake.

Mapper.Initialize(cfg =>
{
    cfg.CreateMap<tblObjectPermissionViewModel, tblObjectPermission>();
    cfg.CreateMap<tblObjectPermission, tblObjectPermissionViewModel>();
});

Expression<Func<IQueryable<tblObjectPermissionViewModel>, IOrderedQueryable<tblObjectPermissionViewModel>>> dtoExpression = dtos => dtos.OrderBy(dto => orderBy);

 var expression = Mapper.Map<Expression<Func<IQueryable<tblObjectPermission>, IOrderedQueryable<tblObjectPermission>>>>(dtoExpression);

Any suggestions?

Thanks for your time and help.

Thanks
Roopesh

**Comment by TylerCarlson1** [comment]
You might be able to get 4.2.1 or another one of the 4.x series from nuget.  They will have UseAsDataSource.

If that doesn't work and you are still using 3.2.1 then try the following.

DON'T try to map IQueryable to IOrderedQueryable.  You can't easily map that, even in 4.x and 5.x can't handle that scenario.

orderby parameter should be like this
`Expression<Func<tblObjectPermissionViewModel, object>> orderBy` not the expression with IQueryable.

Then use converted filter and converted orderby as your lambdas for Where and OrderBy functions.
Like `db.tblObjectPermissions.Where(convertedFilter).OrderBy(convertedOrderBy)`

**Comment by roopeshkumar** [comment]
Ah. Let me try that and shall keep ypu posted. Thanks Tyler.

**Comment by roopeshkumar** [comment]
Thanks Tyler. It did work for me, but I have to change my solution as am not having the DBContext in my library. So I ended up changing my approach. I really appreciate your time and help.

Thanks
Roopesh
