### ISSUE TITLE
ExplicitExpansion in combination with ReverseMap

### ISSUE THREAD

**Issue by SeeUnsharp** [AutoMapper/AutoMapper#1586]
Hello, I have multiple circle references in my data model, so I use MaxDepth and additionally ExplicitExpansion / Ignore. It seems that if I use ReverseMap after the mapping, which includes ExplicitExpansion, the conditions are not applied to the reverse map -> I get an StackOverFlowException. If I do the reverse mapping manually it works -> I don't get that StackOverFlowException.

Here is a [gist ](https://gist.github.com/SeeUnsharp/e3d1b721797146e8697f3ee64f46d73c) where I could reproduce my scenario.

Is that a known limitation of ReverseMap and is it planed to add all conditions if you use ReverseMap ?

Thanks

**Comment by jbogard** [comment]
Yes, reverse map does not try to pull over all your configuration. It's literally CreateMap with the types reversed.

**Comment by SeeUnsharp** [comment]
Okay, thanks for clarification!

**Comment by lbargaoanu** [comment]
This can be closed.
