### ISSUE TITLE
Mapper.Map not working withing CreateMap

### ISSUE THREAD

**Issue by Zhobday** [AutoMapper/AutoMapper#1587]
```
config.CreateMap<StatuteDocument, StatuteViewModel>()
                    .ForMember(x => x.Title, y => y.MapFrom(x => x.OriginalTitle))
                    .ForMember(x => x.HasFullText, y => y.MapFrom(x => x.FulltextStatus == FulltextStatus.Available))
                    .ForMember(x => x.FullText,
                        y => y.MapFrom(x => (x == null || !x.XmlDoc.Any()) ? string.Empty : x.XmlDoc[0].XmlDoc))
                    .ForMember(x => x.ParallelCitations,
                        y => y.MapFrom(src => new List<CitationViewModel> { Mapper.Map<CitationViewModel>(src.Citation) }));
```
The last .ForMember for ParallelCitations causes issues in the code when i call the Map within the API, the map Citation to CitationViewModel was created earlier in the config, Anybody know how to refactor this for V.5. thanks.

**Comment by lbargaoanu** [comment]
Just remove Mapper.Map.

**Comment by Zhobday** [comment]
For some reason the code has changed in the preview section it actually looks like this, 

ForMember(x => x.ParallelCitations,
                        y => y.MapFrom(src => new List<CitationViewModel> { Mapper.Map<CitationViewModel>(src.Citation) }));

**Comment by Zhobday** [comment]
The remove mapper.map doesnt work as the src.Citation value is not the same type as the Parallel citations

**Comment by lbargaoanu** [comment]
Make a gist that shows it doesn't work.

**Comment by jbogard** [comment]
Can you post your models? It looks like you're trying to map a single property in the source model into a list in the destination model, is that right?

**Comment by Zhobday** [comment]
That is right yes, the models are basic and they were working in the 4.2 version but in this new update the error given complains about the ParralelCitations property.

**Comment by jbogard** [comment]
Ok, for using Mapper.Map, you need to use ResolveUsing and the overload that takes the resolution context. On that one is a mapper object that you'd use, not back to a static reference.

**Comment by lbargaoanu** [comment]
@jbogard But why do that? Just MapFrom the source expression would work.

**Comment by lbargaoanu** [comment]
This can be closed.
