### ISSUE TITLE
EFCore + AutoMapper Projections introduce SELECT N+1 problem

### ISSUE THREAD

**Issue by AnnejanBarelds** [AutoMapper/AutoMapper#1590]
Hi,

Today I've been fiddling around with AutoMapper and EFCore, and it seems that the behavior of projections is different when compared to AutoMapper + EF6. When dealing with one:many relations, the latter neatly wraps up everything in a single query - which is sort of the whole point of using projections. But when used in combination with EFCore, the SELECT N+1 problem seems to be back.

I'm by no means an expert on expressions, but this somehow feels related to the fact that EFCore not yet supports eager vs lazy loading. Is that correct? And whatever the cause, is there an alternative way to make this combo work as expected?

**Comment by jbogard** [comment]
Have you tried writing the projection without AutoMapper? That is, just using the Select method?

**Comment by AnnejanBarelds** [comment]
Hmm, should have thought about that myself ;). Sure enough, that yields the same query pattern. So, apparently EFCore is not (yet) optimized for querying one:many relations.
