### ISSUE TITLE
Nullable object Must Have value

### ISSUE THREAD

**Issue by PavelloCz** [AutoMapper/AutoMapper#1592]
I've updated Automapper to newest dev build, than out of nowhere 
I've been floded with:
An exception of type 'AutoMapper.AutoMapperMappingException' occurred in AutoMapper.dll but was not handled in user code.
Error mapping types.

Mapping types:
xxx-> xxxx

Type Map configuration:
xxx -> xxxx

Property:
p1

Inner exception:
Nullable object must have a value.

when mapping simple property 

`Nullable<int> xxx.p1` to `int? xxxx.p1`

Any idea what happened ? Or how to overcome this error ?

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by PavelloCz** [comment]
Having hard time to reproduce issue in any simple way.
Last working Automapper version in my project is version 5.1.0-alpha-01188.

Starting version 01189
When Initialize()
"An exception of type 'System.ArgumentException' occurred in System.Core.dll but was not handled in user code
Additional information: Expression of type 'System.Nullable`1[System.Int32]' cannot be used for parameter of type 'System.Int32'"
   
Starting version 01195 (Initialize() does not throw exception any more)
When Mapping Mapper.Map<List<foo1>, List<foo1>>
"An exception of type 'AutoMapper.AutoMapperMappingException' occurred in AutoMapper.dll but was not handled in user code
Additional information: Error mapping types."
Inner Exception: {"Nullable object must have a value."}
PropertyMap: x1
when x1 is mapped from EF6 persistent class (x1 is of type Nullable<int>) to model class property x1 of type int?

Currently working with 5.0.2.0, pretty well, except that we are waiting for fixes that came out with version 01186 :)

Im not sure if this helps in any way...

**Comment by lbargaoanu** [comment]
For a fix, someone will have to come up with a repro.
Do you have maps that involve primitive types, Nullable<int> or int? Did you customize the mapping for that column? These are the things that make your case special :)

**Comment by PavelloCz** [comment]
Thx for tips @lbargaoanu.
I have reviewed all mappings, and there was in fact some mapping defined for primitive types that are no longer needed (int <=> int?) when i deleted it everything works, or when i add mapping int? => int?.
