### ISSUE TITLE
Transforming bool to bool? fails

### ISSUE THREAD

**Issue by CurlingGeek** [AutoMapper/AutoMapper#1593]
This pattern fails due to what appears to be expression tree parsing issues:

        [TestMethod]
        public void ShouldCreateMapForBoolToNullableBool_UsingLocalBool()
        {
            bool localBool = true;

            AutoMapper.Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<SourceClass, TargetClass>()
                    .ForMember(d => d.targetNullableBool, opt => opt.MapFrom(s => localBool ? true : (bool?)null));
            });
        }

Throws exception: Argument must be boolean.

Failing solution attached, with a few relevant tests showing the issue. If localBool is defined as a bool?, it works.

[AutoMapper5Tests.zip](https://github.com/AutoMapper/AutoMapper/files/401822/AutoMapper5Tests.zip)

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by CurlingGeek** [comment]
Yes, the MyGet fixes it.
