### ISSUE TITLE
Is there any way to create the separate mapping file?

### ISSUE THREAD

**Issue by ArturRibeiro** [AutoMapper/AutoMapper#1594]
Hi friends , I am new here , and I'm Starting with autommaper .

Is there any way to create the separate mapping file ?
Here 's an example

```
public class DomainUserToUserViewModelMap
{
    public DomainUserToUserViewModelMap()
    {
        CreateMap<User, UserViewModel>();
    }
}

public class MappingProfile : Profile {
    public MappingProfile() {

    this.AddMap<User, UserViewModel>(new DomainUserToUserViewModelMap());

    }
}
```

Thank you!

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
You don't need that DomainUserToUserViewModelMap, just make that a profile. I don't know why you'd have an AddMap call, that just seems....pointless?

**Comment by ArturRibeiro** [comment]
Hi Jimmy, 
Sorry for this post, I did not understand how the automapper works.
Really useless.
Sorry

**Comment by jbogard** [comment]
No worries! Good luck!
