### ISSUE TITLE
Multiple Include calls lead to 'Missing Type Map' Exception

### ISSUE THREAD

**Issue by nicklbailey** [AutoMapper/AutoMapper#1595]
We have the following class hierarchy

```
//API response models
public abstract ProductModel

public FooProductModel : ProductModel

public BarProductModel : ProductModel

//Domain model
public Product
```
We need to be able to map from a Product to a FooProductModel or BarProductModel using the exact same logic. Things with differ between the two classes are handed in other methods.

Naturally we tried

```
Mapper.CreateMap<Product, ProductModel>().Include<Product, FooProductModel>()      .Include<Product, BarProductModel>()
             //Rest of Map config here
```

With this setup, calling
`Mapper.Map<Product, BarProductModel>(product);`
will throw:
```
AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

Mapping types:
Product -> BarProductModel
Namespace.Product -> OtherNamespace.BarProductModel

Destination path:
BarProductModel
```

Removing the map for FooProductModel leads to no exception, but obviously prevents us from mapping FooProductModels.

**Comment by TylerCarlson1** [comment]
When you do Include mapping you have to Create a map for the types you are including as well.  It doesn't automatically create a map for them.  It's more of a redirect.

**Comment by jbogard** [comment]
What version are you using?

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by bondsbw** [comment]
I'm seeing this behavior as well after upgrading to version 5.1.1 from 4.0.4.

https://gist.github.com/bondsbw/5e5b70873a7b67fe281efceade2a7e25

I also tested this with each intermediate version in NuGet:
- 4.0.4 and 4.1.1 work without error
- 4.2.0 and 4.2.1 throw InvalidOperationException: `Missing map from Base to String. Create using Mapper.CreateMap<Base, String>.`
- 5.0.2 and 5.1.1 throw InvalidOperationException: `Missing map from Derived to String. Create using Mapper.CreateMap<Derived, String>.`

**Comment by bondsbw** [comment]
I also tried using the constructor syntax instead of overriding Configure in newer versions, same result.

**Comment by lbargaoanu** [comment]
See @TylerCarlson1's answer. That's by design. Just create the missing map.

**Comment by bondsbw** [comment]
Understood on that point (even if it's different from previous versions).'

But even when I CreateMap, I have to specify the same ConvertUsing configuration again.  CreateMap isn't sufficient.

**Comment by lbargaoanu** [comment]
Is that your real code? What are you trying to do here?

**Comment by bondsbw** [comment]
The classes I'm mapping from are third party.  Basic data types are wrapped in classes that derive from a common base.  The base classes have a `Value` for the basic data type, and derived classes add various things like comments which I don't need.  There may be several wrapper classes that to wrap each data type.

The classes I map to just contain the basic data types directly instead of wrappers.  My mappings extract the value just like the example.

**Comment by lbargaoanu** [comment]
You don't need Include then. The base map will also match for the derived classes. If this doesn't make sense, just make a more complete example.

**Comment by bondsbw** [comment]
@lbargaoanu Thank you, I didn't realize Include wasn't needed in that case.
