### ISSUE TITLE
NUll Reference Exception with 5.0.2.0

### ISSUE THREAD

**Issue by jogibear9988** [AutoMapper/AutoMapper#1596]
I've the following code:

Mapper.Initialize(cfg => {
                    cfg.CreateMap(source.GetType(), destination.GetType());
                });

and I got this null ref exception (used reflector for debugging):
<img width="911" alt="bildschirmfoto 2016-08-05 um 00 42 37" src="https://cloud.githubusercontent.com/assets/364896/17420819/8e535374-5aa5-11e6-8711-9643ff0ca491.png">

**Comment by jbogard** [comment]
Why are you calling CreateMap with runtime objects?

**Comment by jogibear9988** [comment]
?? I did so in the old Version, where it worked. I know them firstly at runtime, not at build time.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by jogibear9988** [comment]
This Example will cause the error: (you need Castle.Core(3.3.3) and AutoMapper(5.0.2))


    public class aa
    {
        public string b1 { get; set; }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            var a1 = new aa();
            var proxy = new ProxyGenerator().CreateClassProxy(a1.GetType(), new[]{typeof (INotifyPropertyChanged)}, new NotifyPropertyChangedInterceptor(a1.GetType().FullName));

            Mapper.Initialize(cfg => {
                cfg.CreateMap(a1.GetType(), proxy.GetType());
            });
        }

        public class NotifyPropertyChangedInterceptor : IInterceptor
        {
            private readonly string typeName;
            private PropertyChangedEventHandler subscribers = delegate { };

            public NotifyPropertyChangedInterceptor(string typeName)
            {
                this.typeName = typeName;
            }

            public void Intercept(IInvocation invocation)
            {
            }
        }
    }

**Comment by jogibear9988** [comment]
Fixed with: https://github.com/AutoMapper/AutoMapper/pull/1597

**Comment by lbargaoanu** [comment]
Well yes, but I think the problem is with Castle, not with AutoMapper. A parameter name cannot be null.

**Comment by lbargaoanu** [comment]
A workaround is to disable constructor mapping.

**Comment by jogibear9988** [comment]
As you see it can be, but with my pull req it's fixed.

**Comment by lbargaoanu** [comment]
No, it cannot :) A parameter has a name. I think the bug is that it returns null, not that the check is missing. But I guess it doesn't matter much.

**Comment by jogibear9988** [comment]
if you compile, it has, but on dynamic codegen it may not be garantueed

**Comment by lbargaoanu** [comment]
I presume they're a bunch of numbered locals in the IL. But they could have the courtesy to return something, anything :) Noooo, null is the best.

**Comment by jbogard** [comment]
Back to your original snippet - Mapper.Initialize clears all the maps out. Is this what you want?

**Comment by jogibear9988** [comment]
Don't think so, i dont want to clear them out

**Comment by jbogard** [comment]
So this fix won't help you, will it? The mappings get cleared out.

I think you want "CreateMissingMaps = true".

**Comment by jogibear9988** [comment]
it will, i will create my own mapper config and mapper per instance

Von meinem iPhone gesendet

**Comment by jbogard** [comment]
Hmmm, that's not very efficient at all. AutoMapper creates a mapping plan and caches it in the configuration. Have you tried the create missing type maps option?

**Comment by jogibear9988** [comment]
why should it not be efficient? i dint throw away this config and mapper. i will do this only once. 
i only wanted that it works with the null in the parameter name.
andwhy does initialize throw away the old config?
is it not possible to create smth like mapper.add instead of initialize?
