### ISSUE TITLE
Mapping from Interface to concrete class no longer works as expected

### ISSUE THREAD

**Issue by jgilm** [AutoMapper/AutoMapper#1598]
In Automapper 4.2.1 mapping from an Interface to a concrete class worked so that if a `null` property defined as an Interface would map to a concrete class as `null`.

In Automapper 5.0.2 a null interface property maps to a default constructed concrete class. 

This is a breaking issue for my application. I have a lot of interface properties on source classes mapping to concrete class properties in the destination class. 

**Expectation:**
I would expect that null properties on the source would map to null properties on the destination.

**To test:**
[Gist](https://gist.github.com/jgilm/f73fb5ac2ea96aa0d7d8257ca1035f69)
- Make new console app, paste in gist
- install Automapper 4.2.1 package and run console app. Test passes. 
- install Automapper 5.0.2 package and run console app. Test fails. 

_Although test is a console app, issue also occurs in a UWP app._

4.2.1 output:
![image](https://cloud.githubusercontent.com/assets/2531809/17447534/cb62ebcc-5b03-11e6-8f06-cc1008cb6d6a.png)

5.0.2 output:
![image](https://cloud.githubusercontent.com/assets/2531809/17447600/399fe4f0-5b04-11e6-9e17-af1a922be476.png)

**Comment by jgilm** [comment]
Another person found this same issue and posted it on [StackOverflow](http://stackoverflow.com/questions/38594774/why-does-automapper-try-to-map-a-null-property-if-the-property-is-of-an-interfac), but no answers.

**Comment by alex-davidson** [comment]
Excellent, thank you! This issue was blocking our upgrade from Automapper 3.
