### ISSUE TITLE
Mapping to a List destination property without a setter in AutoMapper 5

### ISSUE THREAD

**Issue by PureWeen** [AutoMapper/AutoMapper#1599]
Was this changed or removed in AutoMapper 5? 

I upgraded to version 5 and now a bunch of my lists aren't getting populated when mapping over to a destination list

The case is when the destination has no setter like this
```
    public List<Destination> Destinations
            {
                get
                {
                    return _destinations;
                }
            }
```
Previouslly it seemed to add them into the list and now it seems like it doesn't do anything

I checked in a repro here
https://github.com/PureWeen/AutoMapper/blob/list_mapping_bug/src/UnitTests/ArraysAndLists.cs

```
  [Fact]
        public void Should_not_be_Empty()
        {
            _destination.Destinations2.ShouldNotBeEmpty();
            _destination.Destinations.ShouldNotBeEmpty(); //this fails
        }
```

Same thing passes here
https://github.com/PureWeen/AutoMapper/blob/4_2_1_list_mapping_bug/src/UnitTests/ArraysAndLists.cs

**Comment by lbargaoanu** [comment]
You should set UseDestinationValue for that member, that used to be true by default.
