### ISSUE TITLE
Various issues when mapping Expression<Func>

### ISSUE THREAD

**Issue by smax48** [AutoMapper/AutoMapper#1600]
I created a test project that reproduces all mentioned problems. Tested with both 4.2.1 & 5.0.2 versions of AutoMapper. Project url: https://github.com/smax48/AutoMapperTests.

1) Error when mapping an expression which references properties from class-typed variables:
See the TestExpressionMap.TestExpressionMapWithLocalVariables() test.

2) Error when mapping an expression which uses nested objects that have properties with the same name:
See the TestExpressionMap.TestExpressionMapWithMatchingPropertyNames() test

**Comment by smax48** [comment]
An update: 
Just tested with the latest dev build from myget (5.1.0-alpha-01199) - it seems that everything works fine with that new version!

**Comment by TylerCarlson1** [comment]
Yea #1497 Had a same name different type issue and 945c8dbc2e6d3b979a40606264524b044463f714 fixes it
