### ISSUE TITLE
IMemberValueResolver is created and called twice

### ISSUE THREAD

**Issue by mbcrawfo** [AutoMapper/AutoMapper#1607]
I have a DTO and view model that are essentially as follows:

    class ProductDTO
    {
      // ...
      
      public IEnumerable<int> Markets { get; set; }
    }
    
    class ProductViewModel
    {
      // ...
      
      public IEnumerable<MarketViewModel> { get; set; }
    }

A resolver that reaches out to a database to get the market info:

    public class MarketViewModelCollectionResolver
        : IMemberValueResolver<object, object, 
            IEnumerable<int>, IEnumerable<MarketViewModel>>
    {
      private readonly IReadOnlyMarketRepository _repository;
    
      public MarketViewModelCollectionResolver(
        IReadOnlyMarketRepository repository)
      {
        _repository = repository;
      }
    
      public IEnumerable<MarketViewModel> Resolve(
        object source, object destination, IEnumerable<int> sourceMember, 
        IEnumerable<MarketViewModel> destMember,
        ResolutionContext context)
      {
        var dtos = _repository.GetMarkets(sourceMember);
        return context.Mapper.Map<IEnumerable<MarketViewModel>>(dtos);
      }
    }

And mapping config:

    config.CreateMap<ProductDTO, ProductViewModel>()
      .ForMember(dst => dst.Markets, opt => 
        opt.ResolveUsing<MarketViewModelCollectionResolver, IEnumerable<int>>(
        src => src.Markets)); 

For reasons that I can't explain, the mapping operation creates the resolver, calls it, then immediately creates another resolver and calls it as well.

**Comment by TylerCarlson1** [comment]
Which version of AutoMapper are you using?

**Comment by mbcrawfo** [comment]
5.0.2

**Comment by TylerCarlson1** [comment]
There's an expression that's generated and when it's made it resolves the value resolver and uses it.  What might be happening is it's doing a null check and double resolving because of that.

**Comment by mbcrawfo** [comment]
More info - the issue only affects resolvers for enumerables.  Here's a reproduction:

    public class FirstDTO
    {
      public int SecondId { get; set; } = 10;
      public IEnumerable<int> ThirdIds { get; set; } = new[] { 1, 2, 3 };
    }

    public class FirstViewModel
    {
      public SecondViewModel SecondViewModel { get; set; }
      public IEnumerable<ThirdViewModel> ThirdViewModels { get; set; }
    }

    public class SecondViewModel
    {
      
    }

    public class ThirdViewModel
    {
      
    }

    public class SecondResolver
      : IMemberValueResolver<object, object, int, SecondViewModel>
    {
      public SecondViewModel Resolve(object source, object destination, 
        int sourceMember, SecondViewModel destMember,
        ResolutionContext context)
      {
        Console.WriteLine("SecondResolver");
        return new SecondViewModel();
      }
    }

    public class ThirdCollectionResolver
      : IMemberValueResolver<object, object, IEnumerable<int>, IEnumerable<ThirdViewModel>>
    {
      public IEnumerable<ThirdViewModel> Resolve(object source, object destination, 
        IEnumerable<int> sourceMember, IEnumerable<ThirdViewModel> destMember,
        ResolutionContext context)
      {
        Console.WriteLine("ThirdCollectionResolver");
        return Enumerable.Empty<ThirdViewModel>();
      }
    }

    static void Main(string[] args)
    {
      Mapper.Initialize(config =>
      {
        config.CreateMap<FirstDTO, FirstViewModel>()
          .ForMember(dst => dst.SecondViewModel,
            opt => opt.ResolveUsing<SecondResolver, int>(src => src.SecondId))
          .ForMember(dst => dst.ThirdViewModels,
            opt => opt.ResolveUsing<ThirdCollectionResolver, IEnumerable<int>>(src => src.ThirdIds));
      });

      Mapper.Map<FirstViewModel>(new FirstDTO());
    }

**Comment by TylerCarlson1** [comment]
Here's the expression made from your example
```
(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        var typeMapDestination = dest ?? new FirstViewModel();
        try
        {
            typeMapDestination.ThirdViewModels = (IEnumerable<ThirdViewModel>)if (ctxt.Options
                .CreateInstance<ThirdCollectionResolver>()
                .Resolve(src, typeMapDestination, src.ThirdIds, typeMapDestination.ThirdViewModels, ctxt) == null)
            {
                new List<ThirdViewModel>();
            }
            else
            {
                var d = new List<ThirdViewModel>();
                var enumerator = ctxt.Options
                    .CreateInstance<ThirdCollectionResolver>()
                    .Resolve(src, typeMapDestination, src.ThirdIds, typeMapDestination.ThirdViewModels, ctxt)
                    .GetEnumerator();
                while (true)
                {
                    if (enumerator.MoveNext())
                    {
                        var item = enumerator.Current;
                        d.Add(item);
                    }
                    else
                    {
                        break;
                    }
                }

                return d;
            };
        }
        catch
        {
            throw new AutoMapperMappingException("Error mapping types.", ex, AutoMapper.TypePair, AutoMapper.TypeMap, AutoMapper.PropertyMap);
        }

        try
        {
            typeMapDestination.SecondViewModel = ctxt.Options.CreateInstance<SecondResolver>().Resolve(src, typeMapDestination, src.SecondId, typeMapDestination.SecondViewModel, ctxt);
        }
        catch
        {
            throw new AutoMapperMappingException("Error mapping types.", ex, AutoMapper.TypePair, AutoMapper.TypeMap, AutoMapper.PropertyMap);
        }

        return typeMapDestination;
    }
}
```

It's clearly checking for null once and then calling it again to do the mapping.  And this IS specific to collections.  Definitely a bug

**Comment by jbogard** [comment]
Is it collections or resolvers here? And the solution would be to evaluate once, and store in a variable (but hopefully not every member mapping, that would stink to get such a perf hit just for this one case).

**Comment by TylerCarlson1** [comment]
not sure I would think it's all resolvers but @mbcrawfo says it's just collections.  Maybe if you redo IfNotNull to do the equivilent of the Elvis operator that would be best solution.  Elvis solution is basicly using variables and checking null at every stage, so performance hit wouldn't be THAT bad.

**Comment by lbargaoanu** [comment]
This works with the MyGet build.

**Comment by lbargaoanu** [comment]
@jbogard That local I introduced a while ago. What performance hit? Storing in a local variable? I don't think that would cost much. It could even be optimized away.

**Comment by jbogard** [comment]
Ah, I missed that @mbcrawfo was using 5.0.2. @mbcrawfo can you upgrade to 5.1.1?

**Comment by mbcrawfo** [comment]
Issue is indeed resolved.  Thanks.
