### ISSUE TITLE
CreateMap fails when source is not null, destination is nullable, and contains an operator

### ISSUE THREAD

**Issue by RyanHerbert** [AutoMapper/AutoMapper#1608]
This might be an obscure bug, but I'm going to post it here in case anybody else is affected with something similar.

I recently updated Automapper from 5.0.0 to 5.0.2.  
The configuration that worked in 5.0.0 threw the exception:
`Unhandled Exception: System.InvalidOperationException: The operands for operator 'Divide' do not match the parameters of method 'op_Division'.`

I finally tracked the error down to a mapping that looked like this:
`cfg.CreateMap<Source, Destination>().ForMember(dest => dest.ValueInMillions, opt => opt.MapFrom(src => src.Value / 1000000m));`

The property on Source was `decimal`, but the property on Destination was` decimal?`

Here is a gist of a Console application that will throw the error; https://gist.github.com/RyanHerbert/5337057406692f17c53a68bd3122e71a

**Comment by TylerCarlson1** [comment]
Can you try the MyGet/alpha version?

**Comment by RyanHerbert** [comment]
I grabbed AutoMapper.5.1.0-alpha-01199 and it looks like its working.
