### ISSUE TITLE
EnumToEnumMapper should throw exception when enums are not compatible

### ISSUE THREAD

**Issue by att741** [AutoMapper/AutoMapper#1609]
When there's no strict 1-1 mapping between enums an exception should be thrown or it should be configurable.

Strict 1-1 mapping:
- Value count match
- Value name match

**Comment by jbogard** [comment]
What should throw an exception?

**Comment by jbogard** [comment]
Fixed by #1919

**Comment by stevenxi** [comment]
Not sure why, but not getting exception when enums are not matching.
Using version 7.0.1
I think this issue should be reopen?

**Comment by jbogard** [comment]
Generally we don't re-open years-old issues. New issue with a repro is best.
