### ISSUE TITLE
Automapper is actually built with debug flags / non optimized when building in release mode.

### ISSUE THREAD

**Issue by jspuij** [AutoMapper/AutoMapper#1612]
Today I got a windows store app rejected because Automapper was built in debug mode.

![image](https://cloud.githubusercontent.com/assets/985974/17583340/cabf90ba-5fb0-11e6-8f49-50c340b67f14.png)

And indeed careful inspection of the downloaded 5.0.2 nuget pkg reveals that it is a debug DLL that is not optimized:

![image](https://cloud.githubusercontent.com/assets/985974/17583409/30da2fb8-5fb1-11e6-81a9-e9a83af6f1bd.png)

This was introduced with PR #1478 where a release configuration is added to project.json. However it seems that this configuration overwrites the default options for a release build. So either the release configuration needs to be removed, or needs to be adjusted to the values below to produce a release build again:

```javascript
"configurations": {
    "Release": {
      "buildOptions": {
        "debugType": "portable",
        "define": [ "RELEASE", "TRACE" ],
        "optimize": true
      }
    }
  },
```

However the section can be safely removed I guess because it's now the default option to generate portable PDB's:

https://github.com/dotnet/cli/issues/3421

Above configuration gives both PDB's and a release DLL again:

![image](https://cloud.githubusercontent.com/assets/985974/17583779/fcbf78bc-5fb2-11e6-9a69-d7251be9adb1.png)

**Comment by jbogard** [comment]
Buh. Thanks, this should be the last one for 5.1.0.

**Comment by jbogard** [comment]
Fixed.

**Comment by jspuij** [comment]
Thank you!
