### ISSUE TITLE
Invalid Reference to System.Collections in NuGet package 5.1.0

### ISSUE THREAD

**Issue by bunnu** [AutoMapper/AutoMapper#1614]
The installation of NuGet package 5.1.0 fails with following error message:

> Failed to add reference. The package 'AutoMapper' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance

My environment: Visual Studio 2015 Update 3 Prof. on Windows 10 64bit.

Steps to reproduce:

1. Create a new Visual C# Console Application
2. Try adding Automapper 5.1.0 via NuGet

**Comment by davidkiryazi** [comment]
I am getting a most likely related issue with "System.Rumtime" missing from the GAC. Same setup as bunnu.

**Comment by MarcMenghin** [comment]
Same problem as bunnu here. Installs fine on portable projects but not on .Net 4.6.1 or Xamarin Android/iOS projects.

**Comment by kevinharing** [comment]
I am also getting this message  as davidkiryazi when installing 5.1.0 via NuGet on VS2015 Update 3:

Failed to add reference. The package 'AutoMapper' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by ConPac** [comment]
Run into this problem with .Net 4.6.2 and found this old issue: Can't add AutoMapper 4.x to Xamarin.Forms project #856.
Waiting for a fix in the nuspec.

**Comment by msouphy** [comment]
Same error about the System.Runtime. My project is targetting 4.6.1

**Comment by jbogard** [comment]
Fixed! Either a dotnet pack or Nuget issue.

**Comment by bunnu** [comment]
Thanks @jbogard , Version 5.1.1 is working
