### ISSUE TITLE
Failed to add reference. The package 'AutoMapper' tried to add a framework reference to 'System.Runtime

### ISSUE THREAD

**Issue by rbmanian75** [AutoMapper/AutoMapper#1615]
When i try to upgrade the package from 4.x to 5.1 i get this error message

Failed to add reference. The package 'AutoMapper' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package

Thanks.

**Comment by geekcubed** [comment]
Also getting this error when trying to upgrade from 5.02 to 5.10.  [ C# project targeting .Net 4.6.1 in VS 2015 CE on Win10 Pro 14393.51 ]

**Comment by lzuk** [comment]
Same here. .NET 4.5.2, VS 2015 Enterprise Update 3

**Comment by adoris** [comment]
Update to 5.1.0: Same with System.Collections:
Error		Failed to add reference. The package 'AutoMapper' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by jbogard** [comment]
Hooray, we've all found a bug in the dotnet CLI! I'll get this fixed ASAP.

**Comment by w0pr** [comment]
That was quick! Another satisfied customer... ;)

**Comment by jbogard** [comment]
Lol well I know if there's a problem with the NuGet package, NO ONE will be able to use it.
