### ISSUE TITLE
how to ignore source's member if source's member is default value.

### ISSUE THREAD

**Issue by DCY2013** [AutoMapper/AutoMapper#1616]
# e.g. object=null ,int = 0 ect.

i want this feature substantially similar to PATCH, not  PUT.

http://stackoverflow.com/questions/37194731/ignore-mapping-properties-with-default-value-using-automapper
i've tried.it did'nt work.
context's member 'SourceType' and 'SourceValue' not found.

maybe that like a question, not a  issue.but i need a help,thanks.

**Comment by lbargaoanu** [comment]
It's the right idea, you just have to make it work.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by DCY2013** [comment]
@lbargaoanu how to make it work?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-250137782
