### ISSUE TITLE
Error when mapping an expression containing a (non-parameter) instance of the mapped type

### ISSUE THREAD

**Issue by smax48** [AutoMapper/AutoMapper#1617]
Simple test code illustrating the problem (tested with the latest 5.1.1):

```
using System;
using System.Linq.Expressions;
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestAutoMapper
{
    [TestClass]
    public class TestExpressionMap
    {
        [TestMethod]
        public void TestExpressionMapWithLocalVariables()
        {
            var mapper = new MapperConfiguration(config => config.CreateMap<TestModel, TestData>()).CreateMapper();

            //fails when a separate (non-parameter) instance of the mapped class is used in the condition:
            //System.NullReferenceException: Object reference not set to an instance of an object.
            var req = new TestData {Code = "DD"};
            Expression<Func<TestData, bool>> f = s => s.Code == req.Code;
            var result = mapper.Map(f, typeof(Expression<Func<TestData, bool>>), typeof(Expression<Func<TestModel, bool>>));
            Console.WriteLine(result);
        }
    }

    public class TestData 
    {
        public string Code { get; set; }
    }

    public class TestModel
    {
        public string Code { get; set; }
    }
}
```

**Comment by TylerCarlson1** [comment]
This is because EF can't read the constant into and SQL statement.  The workaround is to set the variable as a constant of a primitive type.
```
var code = req.Code;
Expression<Func<TestData, bool>> f = s => s.Code == code;
```

**Comment by smax48** [comment]
Well, first of all, I am not using EF :). I have a custom LINQ translator.
Secondly, it DOES work with a constant of a non-primitive type (starting from AutoMapper 5.1)
i.e. I can use instances of the following type in my conditions (instead of TestData in my original post) :
```
public class TestRequest {
  public string Code {get;set;}
}

```
So the problem only happens when you try to use instances of the *mapped* class in predicates :)
I know that there is a workaround (even two - primitive types and non-mapped types), but this looks like a bug that may affect something else.

**Comment by TylerCarlson1** [comment]
OIC now, it's been a while since this issue has come up and the workaround suggested.

So if that's the real issue then it should just a matter of not changing anything from constants when translating.
The other issue with constants is that if your type changes the constant doesn't change with it.  Like compare against a string but it translates to an int property and the constant doesn't change as well.

**Comment by smax48** [comment]
In our project, the original issue is definitely not a show-stopper, but it prevents from writing linq "queries by example", i.e when I want to load a data object which (partially) matches the existing one of the same type.
