### ISSUE TITLE
Profile.AllowNullCollections ignored?

### ISSUE THREAD

**Issue by WillRay** [AutoMapper/AutoMapper#1618]
The `Profile.AllowNullCollections` property seems to be being missed in 5.0.2 and beyond. Moving the code out of the `Configure` method into a constructor results in the same behavior.

```
class Program
{
    static void Main(string[] args)
    {
        var mapper = new MapperConfiguration(cfg =>
        {
            cfg.AddProfile(new TestMappingProfile());
        }).CreateMapper();

        var isNull = mapper.Map<Source, Destination>(new Source()).Ints == null;
        // "true" in 4.2.1
        // "false" in 5.0.2+
    }
}

class TestMappingProfile : Profile
{
    protected override void Configure()
    {
        AllowNullCollections = true;
        CreateMap<Source, Destination>();
    }
}

class Source
{
    public IEnumerable<int> Ints { get; set; }
}

class Destination
{
    public IEnumerable<int> Ints { get; set; }
}
```

**Comment by lbargaoanu** [comment]
@jbogard What about only a global AllowNullCollections?

**Comment by jbogard** [comment]
There already is one, I've made MapperConfigurationExpression inherit from Profile. We might just not enforce it that way.

**Comment by WillRay** [comment]
How would you propose one go about allowing null collections for all types in a specific Profile, if the property is removed?

**Comment by cjrogala** [comment]
Is there a status update on this issue?  I was able to set the global property, and this worked, but that is of course applied to all profiles.  For now, I have rolled back to 4.2.1.0.

**Comment by lundmikkel** [comment]
Are there any updates here? @cjrogala's solution doesn't seem suitable in the long run.

**Comment by jbogard** [comment]
Yeah, I'm working on a solution right now. Profiles are the last thing to get "fixed" from the configuration overhaul of 5.x

**Comment by lundmikkel** [comment]
Great. When do you expect the changes to be available?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
