### ISSUE TITLE
Mapping collection with same type in view model

### ISSUE THREAD

**Issue by idotnetdev** [AutoMapper/AutoMapper#1619]
Hi,
I want to map collection with same type in view model but I get StackOverFlowException.
Imagine I have some comments and this comments has some child comments. I want to show this comments.
1. comment
    2. comment - parent 1
    3. comment - parent 1
        4. comment - parent 3
5. comment
...

my properties and classes are here.
Are you have solution for my problem?

[NewsCommentViewModel.zip](https://github.com/AutoMapper/AutoMapper/files/419982/NewsCommentViewModel.zip)

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#circular-references).

**Comment by lbargaoanu** [comment]
This can be closed.
