### ISSUE TITLE
"Expression of type 'System.Guid' cannot be used for assignment to type  'System.Nullable`1[System.Guid]'"

### ISSUE THREAD

**Issue by vRITHNER** [AutoMapper/AutoMapper#1622]
Hello, I upgraded to version 5.1.1 and since, I get an error on some of my Mapper configs:
"Expression of type 'System.Guid' cannot be used for assignment to type  'System.Nullable`1[System.Guid]'"
 This was working fine with previous versions:

Here are some of my config in a profile:
```
      ForAllPropertyMaps(pm => pm.SourceType == typeof(Guid?) && pm.DestinationPropertyType == typeof(Guid), (pm, opt) => opt.UseDestinationValue());
      CreateMap<Guid?, Guid>().ConvertUsing((src, dest) => src ?? dest);
```

```
     CreateMap<SalesOrderLineItems_SOL, SolDto>()
        .ForMember(dest => dest.displayName_FIT, o => o.MapFrom(src => src.Item_FIT.displayName_FIT))
        .ForMember(dest => dest.inventoryBalance_FIT, o => o.MapFrom(src => src.Item_FIT.inventoryBalance_CIT_FIT))
        .ForMember(dest => dest.ean_SOL, o => o.MapFrom(src => src.ean_SOL.ToString().PadRight(' ')))
        .ForMember(dest => dest.serialNumber_SOL, o => o.MapFrom(src => src.serialNumber_SOL.ToString().PadRight(' ')));
```
The class SolDto contains a nullable Guid property        

 Do I need to change anything in my code to make it work ?
 Thanks in advance

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by vRITHNER** [comment]
I'll close this issue as you solve the last one I posted 1 hour ago;  my profiles was not added correctly but with new method AddProfiles(), it just run fine now.
