### ISSUE TITLE
CorrectI ITypeConverter is not called

### ISSUE THREAD

**Issue by rbmanian75** [AutoMapper/AutoMapper#1627]
See the attached following code we have specified decimal to decimal? itypeconverter but it is not being called. Auto Mapper calls decimal? to decimal? ITypeConverter. This was working fine with version 4.

Is there any breaking changes how it has to be coded.

[Program.zip](https://github.com/AutoMapper/AutoMapper/files/422519/Program.zip)

**Comment by lbargaoanu** [comment]
What are you trying to do here? Maybe there is an easier way.

**Comment by jbogard** [comment]
I think this was the original code:

```
class Program
{
static void Main(string[] args)
{
var config = new MapperConfiguration(a =>
{
a.AddProfile();
a.CreateMap().ConvertUsing();
a.CreateMap().ConvertUsing();
a.CreateMap().ConvertUsing();
});

        var mapper = config.CreateMapper();

        Test test = new Test();
        test.Value = decimal.MaxValue;

        var testDto = mapper.Map<TestDto>(test);

        Console.WriteLine(testDto.Value);

        Console.ReadKey();
    }
}


public class Test
{
    public decimal Value
    {
        get;
        set;
    }
}

public class TestDto
{
    public decimal? Value
    {
        get;
        set;
    }
}

public class TestProfile : Profile
{
    public TestProfile()
    {
        this.CreateMap<Test, TestDto>();
    }
}


public class DecimalConverter : AutoMapper.ITypeConverter<decimal?, decimal>
{
    public decimal Convert(decimal? source, decimal destination, ResolutionContext context)
    {
        if (source.HasValue)
        {
            return source.Value;
        }
        else
        {
            return decimal.MaxValue;
        }
    }
}

public class DecimalNullableConverter : AutoMapper.ITypeConverter<decimal, decimal?>
{
    public decimal? Convert(decimal source, decimal? destination, ResolutionContext context)
    {
        if (source == decimal.MaxValue)
        {
            return null;
        }
        else
        {
            return source;
        }
    }
}

public class NullableDecimalConverter : AutoMapper.ITypeConverter<decimal?, decimal?>
{
    public decimal? Convert(decimal? source, decimal? destination, ResolutionContext context)
    {
        return source;
    }
}
```

**Comment by jbogard** [comment]
@rbmanian75 you can use the three back ticks "```" to build code blocks, it's a bit easier than zip files for me

**Comment by rbmanian75** [comment]
Okey Here is the code.
```
using System;
using AutoMapper;

namespace AMTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(a =>
            {
                a.AddProfile<TestProfile>();
                a.CreateMap<decimal?, decimal>().ConvertUsing<DecimalConverter>();
                a.CreateMap<decimal, decimal?>().ConvertUsing<DecimalNullableConverter>();
                a.CreateMap<decimal?, decimal?>().ConvertUsing<NullableDecimalConverter>();
            });


            var mapper = config.CreateMapper();

            Test test = new Test();
            test.Value = decimal.MaxValue;

            var testDto = mapper.Map<TestDto>(test);

            Console.WriteLine(testDto.Value);

            Console.ReadKey();
        }
    }


    public class Test
    {
        public decimal Value
        {
            get;
            set;
        }
    }

    public class TestDto
    {
        public decimal? Value
        {
            get;
            set;
        }
    }

    public class TestProfile : Profile
    {
        public TestProfile()
        {
            this.CreateMap<Test, TestDto>();
        }
    }


    public class DecimalConverter : AutoMapper.ITypeConverter<decimal?, decimal>
    {
        public decimal Convert(decimal? source, decimal destination, ResolutionContext context)
        {
            if (source.HasValue)
            {
                return source.Value;
            }
            else
            {
                return decimal.MaxValue;
            }
        }
    }

    public class DecimalNullableConverter : AutoMapper.ITypeConverter<decimal, decimal?>
    {
        public decimal? Convert(decimal source, decimal? destination, ResolutionContext context)
        {
            if (source == decimal.MaxValue)
            {
                return null;
            }
            else
            {
                return source;
            }
        }
    }

    public class NullableDecimalConverter : AutoMapper.ITypeConverter<decimal?, decimal?>
    {
        public decimal? Convert(decimal? source, decimal? destination, ResolutionContext context)
        {
            return source;
        }
    }
}
```

**Comment by rbmanian75** [comment]
No it is not the real code...we have some checks inside the conversion functions and convert the source value.

when source property type is decimal and target property type is decimal?  the DecimalNullableConverter  should be invoked.

But automapper is invoking NullableDecimalConverter. Hope this helps.

**Comment by lbargaoanu** [comment]
Well, no :) But anyway, the reason _that_ converter is called is because of some built in null checks in AutoMapper; it actually maps from the nullable type. This generally is of no consequence, but in your case, with all those converters, the behavior is not what you would expect. I guess this could be fixed somehow, but I don't think this case warrants it. The solution is weird. @jbogard might disagree.

**Comment by rbmanian75** [comment]
This was working fine with the old version 4 automapper

**Comment by jbogard** [comment]
First: I hate nullables with a deep passion. `((int?)5).GetType()` returns `int`.

What happens when you get rid of the `decimal? -> decimal?` conversion? That seems extraneous.

@lbargaoanu the problem is that .NET converts a null decimal? value to 0, and above they want max value. They're trying to have different behavior than the .NET defaults, I don't think that's a bad use case (we had to do this for some serialization libraries).

**Comment by rbmanian75** [comment]
Thanks for reply. 

What happens when you get rid of the decimal? -> decimal? 

Everything works as expected.

But in some use cases we need this kind of operation. we have some custom checks inside.

**Comment by jbogard** [comment]
Ah ok, the example above looked kinda pointless. What kind of checks? Just so that we can have a repro that doesn't look pointless and I forget and delete a year from now :)

**Comment by rbmanian75** [comment]
If it is null we will return a default value.

**Comment by lbargaoanu** [comment]
@jbogard I see what you're saying, but really, three different conversions? :) I think decimal?->decimal? would match for all. And with a little logic change, you'd be home free.

**Comment by lbargaoanu** [comment]
Or maybe not. Decimal->decimal would match all, but that would not help.

**Comment by lbargaoanu** [comment]
Anyway, I'm pretty sure it could work with less converters. There are three because that's how it used to work.
