### ISSUE TITLE
Profile not working with DesktopApp

### ISSUE THREAD

**Issue by vRITHNER** [AutoMapper/AutoMapper#1637]
Hi,
I have a desktop app with a AutoMapperConfiguration class to add all profiles.
I'm using the method I found from a fellow user to do it automatically

```
`    public static void Configure()
    {
      Mapper.Initialize(cfg => { Assembly.GetExecutingAssembly().FindAllDerivedTypes<Profile>()
        .ForEach(match =>
        {
          var profile = Activator.CreateInstance(match) as Profile;
          Debug.WriteLine("Profile:" + profile.ProfileName);
          cfg.AddProfile(profile);
        }); });
```
  }`

I've added a trace inside the profile to see if it's really instantiate the profiles and it's working.

```
    protected override void Configure()
    {
       OdmLogHelper.Trace<DomainToViewModelMappingProfile>("START");
    ...
    }
```

DebugView displays the traces, so it is the proof the profile is loaded

[

> 30652] OdmSimWeb.Helpers.AutoMapperConfiguration.DomainToViewModelMappingProfile|Configure|START 
> [30652] OdmSimWeb.Helpers.AutoMapperConfiguration.DomainToViewModelMappingProfile|Configure|END 
> 

In my profile, my mapper is the following:

```
     CreateMap<ObjectReference_REF, ReasonDto>()
          .ForMember(dest => dest.Id, o => o.MapFrom(src => src.id_REF))
          .ForMember(dest => dest.Name, o => o.MapFrom(src => src.name_REF))
          .ForMember(dest => dest.Description, o => o.MapFrom(src => src.description_REF))
          .ForMember(dest => dest.Tag, o => o.MapFrom(src => src.tag_REF))
          .ForMember(dest => dest.Created, o => o.MapFrom(src => src.created_REF))
          .ForMember(dest => dest.Updated, o => o.MapFrom(src => src.updated_REF))
      ;
```

Now I load some data and map them and it's not working

To make a test, I have added the mapping with Mapper.Initialize(cfg => cfg.CreateMap ..... in the Configure method:

   ```
  public static void Configure()
    {
      OdmLogHelper.Trace<AutoMapperConfiguration>("START");

      Mapper.Initialize(cfg => { Assembly.GetExecutingAssembly().FindAllDerivedTypes<Profile>()
        .ForEach(match =>
        {
          var profile = Activator.CreateInstance(match) as Profile;
          cfg.AddProfile(profile);
          OdmLogHelper.Trace<AutoMapperConfiguration>($"Profile:[{profile.ProfileName}]");
        });
      });

      Mapper.Initialize(cfg => cfg.CreateMap<ObjectReference_REF, ReasonDto>()
        .ForMember(dest => dest.Id, o => o.MapFrom(src => src.id_REF))
        .ForMember(dest => dest.Name, o => o.MapFrom(src => src.name_REF))
        .ForMember(dest => dest.Description, o => o.MapFrom(src => src.description_REF))
        .ForMember(dest => dest.Tag, o => o.MapFrom(src => src.tag_REF))
        .ForMember(dest => dest.Created, o => o.MapFrom(src => src.created_REF))
        .ForMember(dest => dest.Updated, o => o.MapFrom(src => src.updated_REF))
        );

      OdmLogHelper.Trace<AutoMapperConfiguration>("END");
    }
```

Now I try again and it's working.

Can you help figure out why I can't make the profiles working ?

Thanks
-Vince

**Comment by lbargaoanu** [comment]
Try [AddProfiles](https://github.com/AutoMapper/AutoMapper/blob/1e7bbcf0fb167de423a95a0149b5c85b8f65f2d0/src/AutoMapper/IMapperConfigurationExpression.cs#L36) instead.

**Comment by jbogard** [comment]
You seem so have two Initialize calls, you should only have one.

Also, brand new in AutoMapper 5.1 is the ability to scan for profiles,
check out the AddProfiles method inside Initialize.

**Comment by vRITHNER** [comment]
Ok. I just tried and it is working much better :-)

Thanks a lot for the quick response.
Cheers

**Comment by jbogard** [comment]
Great! I don't know why I didn't add that method earlier, we've had
something like you had using reflection and profiles for years.

**Comment by vRITHNER** [comment]
To help other devs,

with 2 following lines, I moved my mapper profiles  in a shared dll and any projects in my solutions can  reuse the same mappers.

```
var assembly = typeof(OdmProfile).Assembly;
Mapper.Initialize(cfg => cfg.AddProfiles(assembly.FindAllDerivedTypes<Profile>()));
```

As type Profile will find assembly Automapper, I created OdmProfile to find the Right assembly

```
public class OdmProfile : Profile
  {  }
```

Now, the profile looks like:

```
public class DomainToViewModelMappingProfile : OdmProfile`
{
...
}
```

and the AutoMapperConfiguration class looks like:

    public static void Configure()
    {
      OdmLogHelper.Trace<AutoMapperConfiguration>("START");
      var assembly = typeof(OdmProfile).Assembly;
      Mapper.Initialize(cfg => cfg.AddProfiles(assembly.FindAllDerivedTypes<Profile>()));

      OdmLogHelper.Trace<AutoMapperConfiguration>("END");
    }

The method FindAllDerivedTypes

```
public static class AssemblyExtensions
  {
    public static List<Type> FindAllDerivedTypes<T>(this Assembly assembly)
    {
      var derivedType = typeof(T);
      return assembly.GetTypes()
        .Where(t => t != derivedType && derivedType.IsAssignableFrom(t))
        .ToList();

    }
  }
```

my 2 ct ;-)
Txs again
-Vince

**Comment by jbogard** [comment]
Why do you need that FindAllDerivedTypes? You should just be able to do:

```
Mapper.Initialize(cfg => cfg.AddProfiles(typeof(OdmProfile).Assembly))
// or
Mapper.Initialize(cfg => cfg.AddProfiles(typeof(OdmProfile)))
```
The AddProfiles method does all the assembly scanning, you shouldn't need that any more.
