### ISSUE TITLE
Automapper 5.1.1 StackOverflowException when mapping child entities which contains reference to parent

### ISSUE THREAD

**Issue by jakubbukaj** [AutoMapper/AutoMapper#1639]
Following example ends up with StackOverflowException when running under Automapper 5.1.1. Everything works OK if using Automapper 4.2.1
`   

    public class DbJobHistory
    {
        public long Oid { get; set; }
        public string Name { get; set; }
        public DateTime Start { get; set; }
        public DateTime? End { get; set; }
        public DbPerson Person { get; set; }
    }

    public class DbPerson
    {
        public long Oid { get; set; }
        public string Name { get; set; }
        public IList<DbJobHistory> JobHistories { get; set; }
    }

    public class PersonFlat
    {
        public long Oid { get; set; }
        public string Name { get; set; }
        public IList<JobHistoryFlat> JobHistories { get; set; }
    }

    public class JobHistoryFlat
    {
        public long Oid { get; set; }
        public string Name { get; set; }
        public DateTime Start { get; set; }
        public DateTime? End { get; set; }
        public PersonFlat Person { get; set; }
    }

        static void Main(string[] args)
        {
            Mapper.Initialize(Config);

            var person = new DbPerson
            {
                Name = "John Doe",
                Oid = 1,
                JobHistories = new List<DbJobHistory> { new DbJobHistory { Name = "Worker 1", Oid = 1 }, new DbJobHistory { Name = "Worker 2", Oid = 2 } }
            };

            person.JobHistories[0].Person = person;
            person.JobHistories[1].Person = person;

            var presonFlat = Mapper.Map<DbPerson, PersonFlat>(person);

        }

        private static void Config(IMapperConfigurationExpression cfg)
        {
            cfg.CreateMap<DbPerson, PersonFlat>();
            cfg.CreateMap<DbJobHistory, JobHistoryFlat>();
        }
`

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#circular-references).

**Comment by jakubbukaj** [comment]
We are using Automapper with NHibernate where entities contains Lists of objects from 1:N relations and from the other side of relation those objects reference referenced object, Thus according Automapper documentation we need to set 
cfg.CreateMap<User, UserDto>().PreserveReferences();
to all mappings we have? Is there some kind of "master" setting?

**Comment by lbargaoanu** [comment]
No, but you can use ForAllMaps to set it everywhere. That has a cost, but you have to do it, unless you give up the circular references. The issue can be closed.

**Comment by jakubbukaj** [comment]
Ok, I found this ForAllMap too. But I was not sure this is "The best way how to do that".

**Comment by jbogard** [comment]
No, it's not, you want to be very careful with circular maps. It's quite
expensive to preserve mappings "just in case", so I'd only enable it,
explicitly, on the maps where you have circular references. That's the best
way to do it.
