### ISSUE TITLE
CreateMissingTypeMaps = true Interferes with Dynamic Mapping

### ISSUE THREAD

**Issue by kcragin** [AutoMapper/AutoMapper#1640]
Based on my [SO question](http://stackoverflow.com/questions/39045758/why-is-automapper-not-mapping-from-npoco-dynamic-object-to-entity/39046614#39046614) and doing some more testing, whenever you set `CreateMissingTypeMaps` to true, mapping from a dynamic object (e.g. `ExpandoObject`) to a concrete one does not work (no exception thrown). I suppose some other mapper created under the covers is being used and that doesn't work.

I'd like to use both features.

**Comment by lbargaoanu** [comment]
You should not be using CreateMissingTypeMaps, you should just create the required maps, because as you've seen, stuff happens. That being said, instead of CreateMissingTypeMaps try AddConditionalObjectMapper and exclude the ExpandoObject (and anything else that's causing issues).

**Comment by lbargaoanu** [comment]
This can be closed.
