### ISSUE TITLE
Exception by same name Properties but different types

### ISSUE THREAD

**Issue by lammia07** [AutoMapper/AutoMapper#1643]
Hi. I've got a little Problem.
My DataModel looks like this:

        public class SourceChild<T>:ISourceChild
        {
            public T Data { get; set; }
        }

        public class Source
        {
            public SourceChild<Guid> Id { get; set; }
        }

        public class Destination
        {
            public Guid Id { get; set; }
        }

and my Mapping is this:

        CreateMap<Source, Destination>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id.Data));

Everytime I am trying to Map my SourceElement to my Destination Element I get an Exception:
         AutoMapperMappingException: Missing type map configuration or unsupported mapping.
Mapping types:
          SourceChild`1 -> Guid

The Problem ist the same name. If I rename SourceChild PropertyName it works.
Can you help me pls.

LG Michael

**Comment by lbargaoanu** [comment]
I don't see it. Try the latest from NuGet.

**Comment by lammia07** [comment]
I've already got version 5.1.1

The strange thing is, if i rename the SourceProperty it works just fine.

**Comment by lbargaoanu** [comment]
Then try the MyGet build. A repro would help. Make a gist that we can execute and see fail.

**Comment by lammia07** [comment]
Hi. 
I am really sorry. I tried to reconstruct the error with a test and a little program. but it works every time. There must be some strange constellation in my code, so i simply renamed it and the problem was solved.
Thank you for your help and quick replies.

BR Michael

**Comment by lbargaoanu** [comment]
No worries. You can close the issue.
