### ISSUE TITLE
Is there an ability to log the progress of the automatic scanning?

### ISSUE THREAD

**Issue by natiki** [AutoMapper/AutoMapper#1646]
Hi,

- WebForms .NET 4.61
- AutoMapper 5.1.1

I am looking to use the automatic [scanning functionality](https://github.com/AutoMapper/AutoMapper/wiki/Configuration#assembly-scanning-for-auto-configuration) and was wondering if there is an entry point where I can see progress of the scan?

Currently my application never runs up when I use automatic scanning by assembly name. No exceptions, nada. Works fine if I use the  manual pattern:

```c#
Mapper.Initialize(cfg =>
            {
                //Overall
                cfg.AddProfile<AppAutoMapperMappingProfile>();
});
```

Before I report this as a bug I want to see if I can track it down further.

**Comment by lbargaoanu** [comment]
Any first chance exceptions?

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by natiki** [comment]
There are no first chance exceptions. So how do I go about debugging this? Adding a logging option or at least a debug switch to the output window would be helpful.

**Comment by jbogard** [comment]
Have you tried a try catch just around the Initialize part?

**Comment by lbargaoanu** [comment]
There should be no need for logging. [The code](https://github.com/AutoMapper/AutoMapper/blob/c1013c3fde8b4d7e086c35c3895e32482b6b1ca4/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L65) is simple enough, but new. It should throw when something is wrong. Try a repro.

**Comment by natiki** [comment]
I managed to track this down to a dependent assembly not loading for one of the assemblies being scanned. This did thow an exception that for some reason was not being shown via the exception helper for some reason. Additional logging of exceptions nutted this out.
