### ISSUE TITLE
Can't update package via NuGet

### ISSUE THREAD

**Issue by LarsGardien** [AutoMapper/AutoMapper#1647]
Hello!

![image](https://cloud.githubusercontent.com/assets/15785664/17926746/b68dc2c8-69f2-11e6-9e46-b99676949674.png)

When I run `Install-Package AutoMapper` it fails and renders this problem. Am I doing something wrong?

**Comment by lbargaoanu** [comment]
Try upgrading NuGet.

**Comment by LarsGardien** [comment]
Thanks, that worked!
