### ISSUE TITLE
Mapper.Map() maps null values instead of ignoring by condition

### ISSUE THREAD

**Issue by adibenmat** [AutoMapper/AutoMapper#1648]
Mapper.Initialize(cfg =>
            {
cfg.CreateMap<ObjectDTO, Object>()
       .ForMember(obj => obj.Id, opt => opt.Condition(pre => pre.LastUpdateDate != null));
           }

obj.LastUpdateDate = Datetime.Now;
Mapper.map(objDTO,obj);

after mapping obj.LastUpdateDate will become null despite the condition I created.
happens for all members of the object.

Automapper 5.02
please help

**Comment by lbargaoanu** [comment]
Did you read the [docs](https://github.com/AutoMapper/AutoMapper/wiki/Conditional-mapping)? Because it seems you're expecting something else.

**Comment by lbargaoanu** [comment]
This can be closed.
