### ISSUE TITLE
Convert UTC DateTime to Local DateTime automatically for all mappings Server->Client. Convert Local DateTime to UTC DateTime automatically for all mappings Client->Server.

### ISSUE THREAD

**Issue by jakubbukaj** [AutoMapper/AutoMapper#1650]
Hello, 
**Problem**
in our database we are using DateTime in UTC kind. On client computer we need to display this value in Local kind. 
If client changes some DateTime property on his computer we need to pass it to server, convert to UTC and save it in database.
**Current solution**
We are running conversions by ourselves which is very annoying and leads to errors when we miss something to convert
**Possible automapper solution**
I found very similar question I have on StackOverflow which was answered by Jimmy Bogard in 2011 [(Globally apply value resolver with AutoMapper)](http://stackoverflow.com/questions/5666371/globally-apply-value-resolver-with-automapper)
**Question**
I would like to check with you whether suggested solution by Jimmy is still valid in 2016 with automapper 5.1.1 or whether there is better solution now.

Thanks,
Regards
jakubbukaj

**Comment by lbargaoanu** [comment]
Yes, pretty much. A converter is all you need. Better how? A converter seems pretty simple. Any issue with that?

**Comment by jakubbukaj** [comment]
Is it possible to get instance of object which is currently mapped?

`
ahojpublic class DateTimeConverter : ITypeConverter<DateTime, DateTime>
{
`

**Comment by jakubbukaj** [comment]
Is it possible to get instance of currently mapped object in ITypeConverter?
Says I have 
`var presonFlat = Mapper.Map<DbPerson, PersonFlat>(person);`
I would like to access person object (at least check its type) in ITypeConverter. I looked at available properties of ResolutionContext but there is no relevant property I could use.

In ITypeConverter I would like to do conversion of DateTime based on type of converting object.
E.g. if converting from Db object to Flat than convert datetime utc to local. If converting from Flat object to Db than convert local to utc. Of course I could use check Kind of datetime and do conversion to local/utc based on this value but I would rather have something more robust. 

Currently working solution is to create two mappers with specific DateTime conversion. Is this the best I can have?

**Comment by lbargaoanu** [comment]
I thought you would check DateTime.Kind, but you worry that in some cases you don't need to do the conversion. You can put something in Context.Items to let the converter know it has to translate. You can also try something more generic with ForAllPropertyMaps.

**Comment by jakubbukaj** [comment]
Great idea!

This can be now handled by following peace of code


```
cfg.ForAllPropertyMaps(map => map.TypeMap.SourceType is IDbType && (map.SourceType == typeof(DateTime?) || map.SourceType == typeof(DateTime)), (map, expression) =>
{
    expression.ResolveUsing(o => { return #DO_WHATEVER_YOU_NEED# });
});
```

Thank you

**Comment by lbargaoanu** [comment]
You can close the issue.
