### ISSUE TITLE
Complex flattening

### ISSUE THREAD

**Issue by kaminskid** [AutoMapper/AutoMapper#1651]
With the following class hierarchy:

        public class X { public X x { get; set; } public Y Y { get; set; } }
        public class Y { public int? Value { get; set; } }
        public class Z { public int? xYValue { get; set; } }

executing:

        new MapperConfiguration(o => o.CreateMap<X, Z>()).CreateMapper().Map<Z>(new X());

you get:

AutoMapper.AutoMapperMappingException : Error mapping types.
Mapping types:
X -> Z
[...]+X -> [...]+Z
Type Map configuration:
X -> Z
[...]+X -> [...]+Z
Property:
xYValue
  ----> System.NullReferenceException : Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w lambda_method(Closure , Object , Object , ResolutionContext )
   w AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
...

Am I doing something wrong?

AutoMapper Version 5.1.1

**Comment by gokussx4** [comment]
Change 
`public class Z { public int? xYValue { get; set; } }`
to
`public class Z { public int? YValue { get; set; } }`

The mapping does not expect the parent class type name to be in the field name, only the property names strung together. I hope that makes sense anyway :)

**Comment by kaminskid** [comment]
Thank you for the answer.

I cannot do that. Maybe the example is not clear enough but the the class X is self referenced through the property x. In my web application the situation is even a bit more complicated. Auto Mapper 3 and 4 works correctly with this case.

**Comment by kaminskid** [comment]
Thanks. I'll wait for the next version.
