### ISSUE TITLE
SymbolSource.org not up to date

### ISSUE THREAD

**Issue by gokussx4** [AutoMapper/AutoMapper#1652]
I am working with the 5.1.1 release and need to debug in order to find out why my configuration is invalid. The propertyMap is null in the exception that is thrown so trying to figure out what that is. 

I noticed in a previous issue you were having trouble getting symbol source updated past 4.0.4. Is there anything we can do to help out?

**Comment by lbargaoanu** [comment]
What's the error message?

**Comment by jbogard** [comment]
I upload symbols via NuGet's defaults:

https://ci.appveyor.com/project/jbogard/automapper/build/1204#L297

Publishing AutoMapper.5.1.1.symbols.nupkg to
https://nuget.smbsrc.net/api/v2/package...OK
<https://ci.appveyor.com/project/jbogard/automapper/build/1204#L298>Total
packages published: 2
<https://ci.appveyor.com/project/jbogard/automapper/build/1204#L299>

**Comment by ghuntley** [comment]
SymbolSource.org is _terrible_, highly recommend adopting https://github.com/GitTools/GitLink

**Comment by OzBob** [comment]
https://github.com/AutoMapper/AutoMapper/issues/1652
has links to 
https://ci.appveyor.com/project/jbogard/automapper/build/1204/artifacts

Presumambly download 
artifacts\AutoMapper.5.1.1.symbols.nupkg
to a local drive and add that drive as a new package source in Visual Studio, higher than nuget.
Then, install-package automapper -v 5.1.1
