### ISSUE TITLE
Is it possible to call Mapper.Map inside AfterMap?

### ISSUE THREAD

**Issue by thefenix1** [AutoMapper/AutoMapper#1653]
Is something like this allowed somehow?

```
CreateMap<UserViewModel, User>()
    .ForMember(u => u.Password, o => o.Ignore())
    .AfterMap((src, dest) => {
        ...
        var entity = Mapper.Map<Entity>(src.SomeProperty);
        ...
    });
```

Is not working for me, it says that mapping tried to use inside AfterMap doesn't exist

**Comment by lbargaoanu** [comment]
You need the overload that receives the context and use Context.Mapper.

**Comment by lbargaoanu** [comment]
You can close the issue.

**Comment by thefenix1** [comment]
@lbargaoanu: are you sure that overload exist? Could you point me to the documentation? I don't see it as part of the framework and I'm using a quite new version.

**Comment by lbargaoanu** [comment]
You'll just have to find the version that has it (the latest for example). Or use only the static Mapper.

**Comment by jbogard** [comment]
What version?
