### ISSUE TITLE
UWP 5.2.2 + AutoMapper 5.1.1 = Insanely long builds

### ISSUE THREAD

**Issue by allanrsmith** [AutoMapper/AutoMapper#1655]
With UWP 5.1.0 and AutoMapper 4.2.1 my release build time is 11 mins.
When bumping UWP 5.2.2 and AutoMapper 5.1.1 my release built time goes to 40 mins.

It looks like AutoMapper 5.1.1 has a dependency on UWP 5.2.2, otherwise I get the following
```Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.```

**Comment by lbargaoanu** [comment]
And why would AutoMapper be responsible? :)

**Comment by allanrsmith** [comment]
Because it only happens when I add Automapper nuget package.   Try it!

**Comment by allanrsmith** [comment]
I created a Universal Windows Application project.
Built it in release x64 = 18 seconds
Upgraded from UWP 5.1.0 to UWP 5.2.2
Built it in release x64 = 21 seconds

Added Automapper 5.1.1 via nuget.
Built it in release x64 = 20 MINUTES

I don't even have any code referencing the library, just have it added as a reference.

**Comment by lbargaoanu** [comment]
And if you add another package, comparable in size?

**Comment by jbogard** [comment]
I have no idea, I'm not a UWP developer.

**Comment by allanrsmith** [comment]
@lbargaoanu After adding Microsoft.EntityFramework.Core, and removing Automapper, the build time is 47 seconds.

@jbogard I've emailed this issue to dotnetnative@microsoft.com

**Comment by lbargaoanu** [comment]
Than I guess they don't like smth about AutoMapper :) I'm sure we can fix it once you let us know what it is.

**Comment by lbargaoanu** [comment]
Compiling expressions might have something to do with this, but I'm not sure what .NET Native does on build. Normally the compilation happens at runtime. Maybe it runs your app to see what it needs. It would make sense, but I'm guessing here.

**Comment by jbogard** [comment]
Well, I wonder if it's because AutoMapper references NetStandard.Library instead of individual packages. That's what was recommended, but I wonder if all of its implicit dependencies are being natively complied?

**Comment by allanrsmith** [comment]
Interesting... I suppose I could clone AutoMapper and give that a try.

**Comment by MattWhilden** [comment]
Hello! I work on the .NET Native runtime and compiler team and we can definitely take a look. This kind of rapid expansion of compile time to modified input is almost certainly something we'll need to fix. 

It looks like Alan has sent a mail to us directly and I'll use that to help sort through the initial triage but report back when we know more. If you don't hear back in a few days please feel free to ping me... sometimes things can be a bit hectic here and squeaky wheels definitely get the oil. :-)

**Comment by lbargaoanu** [comment]
Did you solve this?

**Comment by allanrsmith** [comment]
A workaround for now is to add the following to your Properties/Default.rd.xml file
<Type Name="AutoMapper.Mappers.ConvertMapper" DoNotOptimize="true" DoNotInline="true"/>

That class is what causes the optimizer to churn. Waiting on a response from the optimizer team at Msft.

**Comment by jbogard** [comment]
Good to know!

**Comment by MattWhilden** [comment]
The presence of all those lambdas makes the inliner go a bit bananas. We'll have a fix for this in the next version of the tools.

One thing that can keep other folks from having to bother you is to include an rd.xml file as a resource in the automapper library. The AOT compiler will see that and then not lose its mind. Alternately, applying an appropriate MethodImplAttribute is a source level change that should cause headaches for other consumers. The JIT compiler almost certainly avoids optimizing this method due to it's size...

Let me know if you have questions or see anything else odd. Always happy to help.

**Comment by lbargaoanu** [comment]
@MattWhilden ...should _not_ cause headaches for other consumers...? :)

**Comment by MattWhilden** [comment]
Ha. You're right. Good catch.
