### ISSUE TITLE
System.Collections.ObjectModel.Collection not Mapped

### ISSUE THREAD

**Issue by federicus79** [AutoMapper/AutoMapper#1657]
I try to map System.Collections.ObjectModel.Collection, but not working.
Thanks

Federico

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by federicus79** [comment]
Sorry, i thought that was a bug. It's wrong ?

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by federicus79** [comment]
namespace AssemblySource
{
    public class ClassTest0 : System.Collections.ObjectModel.Collection<ClassTest01>
    {

    }

    public class ClassTest01
    {
        public int Test { get; set; }
    }
}

namespace AssemblyDestination
{
    public class ClassTest0 : System.Collections.ObjectModel.Collection<ClassTest01>
    {

    }

    public class ClassTest01
    {
        public int Test { get; set; }
    }
}

[Test]
public void ExecuteTest()
{
    AssemblySource.ClassTest0 classTest0 = new AssemblySource.ClassTest0();
    classTest0.Add(new AssemblySource.ClassTest01() { Test = 1 });
    classTest0.Add(new AssemblySource.ClassTest01() { Test = 2 });

    var config = new AutoMapper.MapperConfiguration(cfg =>
    {
        cfg.CreateMap<AssemblySource.ClassTest0, AssemblyDestination.ClassTest0>();
        cfg.CreateMap<AssemblySource.ClassTest01, AssemblyDestination.ClassTest01>();
        cfg.AllowNullCollections = true;
        cfg.AllowNullDestinationValues = true;
     });

     AssemblyDestination.ClassTest0 destinationDyn = config.CreateMapper().Map<AssemblySource.ClassTest0, AssemblyDestination.ClassTest0>((AssemblySource.ClassTest0)classTest0);

     destinationDyn.Count.ShouldEqual(2);
}

**Comment by lbargaoanu** [comment]
You don't need the map for the collection, it's built in, just remove it.

**Comment by federicus79** [comment]
My classes are derived from collection, it's the same ?

**Comment by lbargaoanu** [comment]
Collections are handled by default and the behavior is to map the contents, not any custom properties you might have.

**Comment by federicus79** [comment]
Thanks for your information. If i don't map my derived class from Collection, all it's ok.

**Comment by lbargaoanu** [comment]
You can close the issue?

**Comment by niemyjski** [comment]
I think this may be broken in latest version on .net core (Getting unable to map from ICollection<T> instantiated with instance of System.Collections.ObjectModel.Collection<T> to ICollection<T>
