### ISSUE TITLE
Slow performance on debug

### ISSUE THREAD

**Issue by jparaya** [AutoMapper/AutoMapper#1658]
Greetings,

I'm using AutoMapper 4.0.2 (our project is conditioned to run on .Net 4.0), installed from nuget, on a Web MVC 4 application. This application maps from Entity to Model objects.

We have noticed the mapper takes a lot of time to map when we are debugging. For example, for 1000 Entities on memory, the mapper can take about 2.5 seconds on release mode, but if we debug, it takes almost 40 seconds.

Our big problem is that we need to debug some codes, and the mapper takes too much time to finish. Is there any chance to accelerate the mapping on debugging, like disabling symbols? 

Thanks in advance

**Comment by jbogard** [comment]
No idea. AutoMapper earlier than 5.x was slow, and on 5.x it's something
like 20-50x faster.

On Tue, Aug 30, 2016 at 10:14 AM, Juan Pablo Araya <notifications@github.com

**Comment by jparaya** [comment]
Is possible to run v5 on .Net4? If not, what's else can I do to reduce the mapping time? This only affects when debugging...

**Comment by lbargaoanu** [comment]
It's worth considering whether your own code runs during mapping and how it would affect running time. I say that because AutoMapper doesn't do tracing or something obvious that would affect the debugging experience. Anyway, if you're stuck with .NET 4, you're on your own.

**Comment by lbargaoanu** [comment]
You can also try 4.1.1, that's the last version to support .NET 4, from what I see on NuGet. But I doubt it would make a difference.

**Comment by jbogard** [comment]
Ha literally. Microsoft doesn't even support .NET 4 anymore
https://support.microsoft.com/en-us/lifecycle?p1=14380 not for over 6 months

**Comment by jparaya** [comment]
Now we're requesting permissions to migrate. Unfortunately, it depends on
the company's infrastructure.

Double clicking on the issue, I found something strange. We have some
mappings that use , for example

.ForMember(dest => dest.PropertyWithUnrelatedConvention, opt =>
opt.MapFrom(src=> src.MyProperty.AnotherProperty))

Seems MapFrom catches nullReferenceExceptions, which causes the slow
performance when we debug. When we just execute the app it works fine, but
on debug we have the problem, because much of our MyProperty objects are
null.

If the property matches the naming convention, the mapper works really
fast. The problem is with this lambda expressions.

The solution, I think, is to validate first the null check, but I don't
know if there is another way to take advantage of the naming convention on
this special cases.

**Comment by lbargaoanu** [comment]
That check was implemented in the new version. Throwing exceptions is always expensive, it's just even more so during debugging.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jparaya** [comment]
Thanks guys!
