### ISSUE TITLE
Enum to string mapping

### ISSUE THREAD

**Issue by teslavsedison** [AutoMapper/AutoMapper#1659]
Hi everyone. I updated my automapper to 5.1.1 but I got this error 

> Unmapped  members were found. Review the types and members below.
> Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
> For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
> =======================================================
> ServiceReqState -> String (Destination member list)
> Sinerp.Core.Model.Crm.ServiceReqState -> System.String (Destination member list)
> 
> No available constructor.
> Source Error: 
>      config.AssertConfigurationIsValid();
>      return config;
>  }

I tried different mapping techniques but same result.
When i remove the `config.AssertConfigurationIsValid();` line, this error gone.
I'm using Automapper quite a long time.
Sorry my poor English.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by teslavsedison** [comment]
Ooh Sorry guys. My fault
https://gist.github.com/teslavsedison/09c85973d944310f29c0eab0f95d9053#file-crmcustomerprofile-cs
