### ISSUE TITLE
ProjectTo vs Mapper.Map

### ISSUE THREAD

**Issue by Worthy7** [AutoMapper/AutoMapper#1660]
I have a mapping which works for Mapper.Map, but not ProjectTo. This seems really strange as I thought they were similar (except one is projecting in memory objects.

Specifically, the error is:

Cannot compare elements of type 'System.Collections.Generic.ICollection`1[[myapp.Models.Shipment, myapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. Only primitive types, enumeration types and entity types are supported.

I am literally changing one line from using ProjectTo<myVM> to Mapper.Map<myVM>, and it suddenly works. What gives?

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by Worthy7** [comment]
Not really got a lot of time right now sorry. If I encounter it again I'll
post some code but atm got a deadline to meet.

**Comment by jbogard** [comment]
They're similar in spirit but not in practice. It relies on the LINQ query
provider to do the mapping, which adds a layer of complexity. In general
the mapping in memory has many more features and we have complete control
over it. With LINQ we have to pare those back and simplify things for the
LINQ providers.
