### ISSUE TITLE
'AutoMapper' already has a dependency defined for 'NETStandard.Library'.

### ISSUE THREAD

**Issue by ChiakiYu** [AutoMapper/AutoMapper#1661]
i want to udpate 5.1.1
my ide is vs 2013 update5
nuget version is 2.8.60723.765

nuget command line also has the same error

**Comment by lbargaoanu** [comment]
Try upgrading nuget.

**Comment by jbogard** [comment]
Yeah, I'd at the very least use the 3.4 version of NuGet. In VS 2013, also
update the NuGet Package Manager extension (not just all of VS)

**Comment by MAOliver** [comment]
Yeah - this is 100% a nuget error, not an automapper error. Just experienced the same issue. Resolved it by upgrading the nuget.exe in the project and getting our devs that were still on vs2013 to upgrade their nuget package manager.

**Comment by ChiakiYu** [comment]
nuget can be upgraded to 2.12 Today.
it is ok to upgrade 5.11.
thanks

**Comment by gilles27** [comment]
Appreciate this is closed but hope someone can help. I'm trying to install PiranhaCMS.Mvc into a VS2012/NET45 ASP NET MVC project and getting this error. (Piranha has a dependency on AutoMapper).

I've upgraded nuget (the one in .nuget folder under the solution) to the latest version, but this doesn't make any difference. If I try to update nuget via the VS "Extensions and Updates" dialog, no updates are found. The Help, About dialog states NuGet Package Manager is on version 2.8.60318.667 whereas nuget.exe in the .nuget folder is on 4.3, which seems odd.

My question is, is my version of VS2012 simply too old to install Piranaha and AutoMapper? If not how do I get the package to install? Thanks.
