### ISSUE TITLE
Error saving Asp.Net core Ef Entity

### ISSUE THREAD

**Issue by lucamorelli** [AutoMapper/AutoMapper#1665]
Sorry for asking here, but I already asked in StackOverflow without success.

I have an asp.net core 1 app with ef core 1.0 and automapper 5.1.1.
I receive from the web page a viewmodel of an entity and I'm trying to map directly to the ed entity.

In the startup for the map I declare this rule

```
  cfg.CreateMap<AnagraficaVm, Anagrafiche>()
     .ForMember( dest => dest.Id, opt => opt.Ignore() );

```

The Id in both the en entity and viewmodel are identical. In the mvc controller I try to map the viewmodel this way:

```
var anagrafica = await _db.Anagrafiche.FirstOrDefaultAsync(r => r.Id == id);
if (anagrafica == null) return null;
    _mapper.Map(model, anagrafica);

```

when in the edn I call the SaveChangesAsync I receive the error message

`The instance of entity type 'Anagrafiche' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.`

How can I avoid this error message and map the data from view model to an existing object? There is something I missing?

**Comment by lbargaoanu** [comment]
Does this work with EF6?

**Comment by lucamorelli** [comment]
didn't try this code with ef 6

**Comment by lbargaoanu** [comment]
Try first without AutoMapper and see what exactly is the difference.

**Comment by lucamorelli** [comment]
I changed 

`_mapper.Map(model, anagrafica);
with`

```
                    anagrafica.RagioneSociale = model.RagioneSociale;
                    anagrafica.IndirizzoResidenza = model.IndirizzoResidenza;
                    anagrafica.LocalitaResidenza = model.LocalitaResidenza;
                    anagrafica.CapResidenza = model.CapResidenza;
                    anagrafica.IdProvincia = model.IdProvincia;
                    anagrafica.IdLocalita = model.IdLocalita;
                    anagrafica.IdCap = model.IdCap;
                    anagrafica.Telefono = model.Telefono;
                    anagrafica.Telefono2 = model.Telefono2;
                    anagrafica.Telefono3 = model.Telefono3;
                    anagrafica.Telefono4 = model.Telefono4;
                    anagrafica.Fax = model.Fax;
                    anagrafica.Fax2 = model.Fax2;
                    anagrafica.Email1 = model.Email1;
                    anagrafica.Email2 = model.Email2;
                    anagrafica.IdZona = model.IdZona;
                    anagrafica.IdSottoZona = model.IdSottoZona;
                    anagrafica.IdGruppoIstat = model.IdGruppoIstat;
                    anagrafica.IdCodiceIstat = model.IdCodiceIstat;

```
and it's working. I don't know what I'm missing

**Comment by lbargaoanu** [comment]
Well, it looks as if AutoMapper creates a new instance somehow, but I don't know. We need a repro. Maybe it's .Net Core only.

**Comment by lbargaoanu** [comment]
I've run some tests on .NET Core and everything works as expected. Without a repro, the issue can be closed.
