### ISSUE TITLE
Automapper 5.11 Not mapping / working

### ISSUE THREAD

**Issue by roopeshkumar** [AutoMapper/AutoMapper#1667]
Hi,
   I was using Automapper 3.11 and recently and has upgraded to 5.11. All my code was broken. Am trying to map the objects which are in a library like the below. Not sure where I was doing wrong.
The below code works perfectly fine with 3.11 version. Any help is appreciated.

                var mapperConfig = new MapperConfiguration(cfg =>
                {
                   cfg.CreateMap<PageView, PageViewViewModel>();
                    cfg.CreateMap<tblUser, tblUserViewModel>();
                    cfg.CreateMap<UserPageView, UserPageViewViewModel>();
                    });

                   mapperConfig.AssertConfigurationIsValid();
                  IMapper mapper = mapperConfig.CreateMapper();

 _lst = _apidataservice.GetAllUserPageView(pageIndex: pageIndex, pageSize: pageSize, _orderby: _orderby, includeProperties: "PageView,tblUser");

_vmlst = mapper.Map<IEnumerable<UserPageView>, IEnumerable<UserPageViewViewModel>>(_lst);

The below are my models

 public PageViewViewModel()
        {
            this.RolePageviews = new List<RolePageviewViewModel>();
            this.RolePageviews1 = new List<RolePageviewViewModel>();
            this.UserPageViews = new List<UserPageViewViewModel>();
        }

        public int PageviewID { get; set; }
        public string PageviewName { get; set; }
        public string PageviewDescription { get; set; }
        public Nullable<bool> IsMenuBarItem { get; set; }
        public string MenuBarName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string URL { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<bool> DeleteYN { get; set; }
        public byte[] RowVersion { get; set; }
        public virtual ICollection<RolePageviewViewModel> RolePageviews { get; set; }
        public virtual ICollection<RolePageviewViewModel> RolePageviews1 { get; set; }
        public virtual ICollection<UserPageViewViewModel> UserPageViews { get; set; }
    }

 public partial class tblUserViewModel
    {
        public tblUserViewModel()
        {
            this.tblHistoryUsers = new List<tblHistoryUserViewModel>();
            this.UserPageViews = new List<UserPageViewViewModel>();
            this.UserRoles = new List<UserRoleViewModel>();
        }

        public int UserID { get; set; }
        public bool DeleteYN { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string IM { get; set; }
        public string PhoneBusiness { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneMobile { get; set; }
        public string AddressStreet { get; set; }
        public string AddressCity { get; set; }
        public string AddressState { get; set; }
        public string AddressPostal { get; set; }
        public string CountryRegion { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public bool DaylightSavingsYN { get; set; }
        public Nullable<short> ChangeCount { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> ChangeUser { get; set; }
        public byte[] RowVersion { get; set; }
        public virtual ICollection<tblHistoryUserViewModel> tblHistoryUsers { get; set; }
        public virtual tblSubscriberViewModel tblSubscriber { get; set; }
        public virtual ICollection<UserPageViewViewModel> UserPageViews { get; set; }
        public virtual ICollection<UserRoleViewModel> UserRoles { get; set; }
    }

 public partial class UserPageViewViewModel
    {
        public int UserPageViewID { get; set; }
        public int UserID { get; set; }
        public int PageViewID { get; set; }
        public string SubscriberID { get; set; }
        public Nullable<bool> DeleteYN { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public virtual PageViewViewModel PageView { get; set; }
        public virtual tblUserViewModel tblUser { get; set; }
    }

**Comment by lbargaoanu** [comment]
So what exactly is the problem? Quote your code or make a separate guist.

**Comment by lbargaoanu** [comment]
There is an upgrade guide in the wiki.

**Comment by roopeshkumar** [comment]
I have followed the wiki https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide and I tried using profiles using Mapper.Initialize as well as using  var mapperConfig = new MapperConfiguration. No luck so far. Am getting the below exception

"The following property on CentelligenceViewModels.UserRoleViewModel cannot be mapped: \n\t\nAdd a custom mapping expression, ignore, add a custom resolver, or modify the destination type CentelligenceViewModels.UserRoleViewModel.\nContext:\n\tMapping from type CentelligenceEntityModels.Models.UserRole to CentelligenceViewModels.UserRoleViewModel\nException of type 'AutoMapper.AutoMapperConfigurationException' was thrown.".

Where am lost is the same mappings were working perfectly fine with 3.11 version and not with latest version. Am sure am doing something wrong. Thanks for your help.

Roopesh.

**Comment by roopeshkumar** [comment]
One dumb question, should we map all models and view models at one time or can we do mapping as required like in 3.11? Understand in 5.11 we have do define them in profiles. Can't we define as required?

**Comment by roopeshkumar** [comment]
After mapping all the models, the below is the exception I get.
"Error mapping types.\r\n\r\nMapping types:\r\nIEnumerable`1 -> IEnumerable`1\r\nSystem.Collections.Generic.IEnumerable".

Not sure how to resolve this now.

**Comment by lbargaoanu** [comment]
Your code is not readable. Use the GitHub notation or make a separate gist. Also post the full error message, that looks weird too.

**Comment by roopeshkumar** [comment]
I have created gist and here is the link
https://gist.github.com/roopeshkumar/c37daa24b47780b311df9acbfd9417f6

I also attached error screenshot. Appreciate your help.

Thanks
Roopesh

**Comment by lbargaoanu** [comment]
The inner exception says that map doesn't exist. Weird. What if you add the profile explicitly?

**Comment by roopeshkumar** [comment]
Same exception. Tried multiple ways.

**Comment by lbargaoanu** [comment]
Maybe some other map is missing?

**Comment by roopeshkumar** [comment]
Checked and counted all view models, didn't miss anything. The exception message is not really helpful.

Thanks
Roopesh

**Comment by lbargaoanu** [comment]
If you dig in the exception you should find the missing map.

**Comment by kkgorrepati** [comment]
Roopesh -I replicated your code and it worked successfully after
1. I passed on the profile name to the Mapper.Initialize
2. Added PreserveReferences to the CreateMap statement in the profile constructor.

Thanks
Kalyan

**Comment by roopeshkumar** [comment]
Awesome. It worked kalyan. Thank you very much.

Thanks
Roopesh

**Comment by lbargaoanu** [comment]
I didn't quite get it, but if everything works, you can close the issue.

**Comment by roopeshkumar** [comment]
PreserveReferences solved the problem for me.

 CreateMap<PageView, PageViewViewModel>().PreserveReferences();

Thanks
Roopesh

**Comment by lbargaoanu** [comment]
Then I never saw the root exception :) Bygones.
