### ISSUE TITLE
Multi-Level NullReferenceException Handling

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#1675]
I've found a change in behaviour introduced in 5.1.1.  This happens when using MapFrom to map from a deep property to a non-nullable property:

	public class MultiLevelNull  : AutoMapperSpecBase
	{
		class A
		{
			public B B { get; set; }
		}
		class B
		{
			public int Id { get; set; }
			public C C { get; set; }
		}
		class C
		{
			public int Id { get; set; }
		}

		class DTO
		{
			public int Id { get; set; }
		}

		protected override MapperConfiguration Configuration => new MapperConfiguration(cfg =>
		{
			cfg.CreateMap<A, DTO>().ForMember(d => d.Id, o => o.MapFrom(src => src.B.C.Id));
		});

		[Fact]
		public void Should_Not_Throw_NRE()
		{
			Should.NotThrow(() => Mapper.Map<DTO>(new A()));
		}

		[Fact]
		public void Should_Return_Default()
		{
			var result = Mapper.Map<DTO>(new A());
			result.Id.ShouldBe(default(int));
		}
	}

Notes:
* The problem does not occur if the destination property is Nullable
* The problem does not occur if one level is removed (i.e. `o.MapFrom(src => src.B.Id)`)

I'm aware that this code would cause a NRE as the destination is not nullable, but this code worked prior to 5.1.1, so I'd like to know whether this is intentional behaviour or not.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by richardlawley** [comment]
Same behaviour (myget appears to be same as release at this point).

**Comment by lbargaoanu** [comment]
This was fixed. MyGet should be ahead. The prerelease check?

**Comment by richardlawley** [comment]
My bad, forgot the pre bit. I'll verify over the weekend.

**Comment by richardlawley** [comment]
Confirmed as fixed in the 5.2.0-alpha build on myget.
