### ISSUE TITLE
Very slow UseAsDataSource() compared to ProjectTo()

### ISSUE THREAD

**Issue by MrPerun** [AutoMapper/AutoMapper#1676]
Hello,
I have simple mapping:
`CreateMap<VwReportResultFee, ReportResultFeeDto>();`

And then simple projection:
`var set = Context.VwReportResultFees.UseAsDataSource().For<ReportResultFeeDto>().Where(....).ToArray();`

But, this **query runs very slow**, even when returning 1 row. More than 30 seconds. Database returns the data in a few miliseconds.

If I use, the execution is fast (less than 1 second):
`var set = Context.VwReportResultFees.ProjectTo<ReportResultFeeDto>().Where(....).ToArray();`

The data objects are bigger, they have cca 50 properties, but almost all are decimals or integers. There are no long string values in the returned data.

I use mapper in many other places in the application with the UseAsDataSource(), but the performance in the other places is OK.

Do you have any idea what could be the cause of this poor performance?

Thanks,
Tomas

**Comment by TylerCarlson1** [comment]
Probably the translation of the where clause from ReportResultFeeDto to VwReportResultFee.  What is the difference between the where clauses of this and others that execute faster?

UseAsDataSource translates the where then calls ProjectTo, so it most likely has to do with that.

**Comment by MrPerun** [comment]
The Where part and the complete rest of the query is only this, for both UseAsDatasource as well as for the ProjectTo. Nothing different from other queries I do:

var set = Context.VwReportResultFees.ProjectTo<ReportResultFeeDto>().Where(x=>x.Period == new DateTime(2016,08,01)).OrderBy(x=>x.Id).Take(50).ToArray();

So nothing complicated what should increase the translation complexity.

**Comment by TylerCarlson1** [comment]
My suggestions would be to create the date time outside of the where statement and reference it as a variable, and also see if the OrderBy or Take have any effect on performance.

I have seen OrderBy, and that gets translated like Where, but not so sure if encountered Take as much.

If these don't seem to have much an effect, it might be the fact that there's 50 properties.
Or is this mapper made by some convention?  If so is the base map getting called before you call UseAsDataSource or are you not getting any exceptions when called?
