### ISSUE TITLE
Always get same value from previous mapping

### ISSUE THREAD

**Issue by HJLuecking** [AutoMapper/AutoMapper#1678]
**This are the settings:**
- A complex Class SourceClassA with a field of SourceClassB. Within SourceClassB if hav an Id (int) field
- A complex Class DestinationClassA with a field of DestinationClassB. Within DestinationClassB i have an Id (int) field.
- usinf Entity Framework 6
- using Automapper 5.0.2.0

**The Mapping looks like:**

`var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<SourceClassA, DestinationClassA>().PreserveReferences().ReverseMap();
                cfg.CreateMap<SourceClassB, DestinationClassB>().PreserveReferences().ReverseMap();
`

**This is the workfow:**
1. Read SourceClassA from database 
2. Map SourceClassA to DestinationClassA. DestinationClassA.DestinationClassB.Id has a value of eg. 1.
3. Change DestinationClassA.DestinationClassB.Id to some other value eg **42**
4. Mapping from DestinationClassA back to SourceClassA
5. Not saving to database jet!
6. Read SourceClassA again from Database. SourceClassA.SourceClassB.Id has the old value of 1.
7. Map SourceClassA to Dest.ClassA again.

**At step 7 DestinationClassA.DestinationClassB.Id should be 1 again. But instead its 42!.**

Thats not the answer of all my questions. Thats the Question. Why does Automapper map to a value used before and how can this be switched off?

**Comment by lbargaoanu** [comment]
Try the MyGet build. Or the latest from NuGet.

**Comment by HJLuecking** [comment]
Are there relevant changes?

**Comment by HJLuecking** [comment]
Thx. 
I gave the hint a change. 
An Update solved my Problem

**Comment by lbargaoanu** [comment]
This can be closed.
