### ISSUE TITLE
AfterMap on ConditionalObjectMapper?

### ISSUE THREAD

**Issue by pardahlman** [AutoMapper/AutoMapper#1679]
In one of my `Profiles` I have added a `ConditionalObjectMapper` as follows

``` csharp
AddConditionalObjectMapper().Where((src, dest) => dest.Name == $"{src?.Name}Model");
```

I would very much like it I could wire up an `AfterMap` (similar to what I can do when defining normal maps). Can this be done? The syntax I'd prefer would be something like below:

``` csharp
AddConditionalObjectMapper()
  .Where((src, dest) => dest.Name == $"{src?.Name}Model")
  .AfterMap((src, dest) => { /* do things here */});
```

**Comment by TylerCarlson1** [comment]
You can do `ForAllMaps(tm => tm.AddAfterMapAction(AfterMap))` in the profile and all generated maps will use the action.

**Comment by pardahlman** [comment]
Right, but that would be for _all_ maps in that profile, right? (Or is it even so that it would be for all maps in that mapper?)

**Comment by lbargaoanu** [comment]
You can put all the filters you want. Again :)

**Comment by TylerCarlson1** [comment]
It's for that profile only

**Comment by pardahlman** [comment]
Thanks @TylerCarlson1 and @lbargaoanu :+1: 
The work-around to put the dynamic mappings in a seperate profile might be enough for what I'm doing, but IMHO the `AfterMap` on the conditional mapper would be a cleaner solution. You may close this issue if you don't want to act on it.

:hand: Thanks for a great mapping library, I use it daily!
