### ISSUE TITLE
Can the configuration mapping be dynamic?

### ISSUE THREAD

**Issue by ericvb** [AutoMapper/AutoMapper#1681]
`Class A {
Property A1;
Property ForeignKeyNavigation1; /* for example to a class B */
Property ForeignKeyNavigation2; /* for example to a class C */
}`
`Class ADto {
Property A1;
Property ForeignKeyNavigation1; /* for example to a class BDto */
Property ForeignKeyNavigation2; /* for example to a class CDto */
}`

Consider following mapping configuration
`CreateMap<A, ADto>();`
With `Repository.GetQueryableResponse().ProjectTo<ADto>(Mapper.ConfigurationProvider);`
==> will map all properties, so class B and C will be retrieved from db and made available in class A and everything will be mapped on ADto

`CreateMap<A, ADto>.ForMember(dest => dest.A1, opt => opt.MapFrom(src => src.A1).ForMember(dest => dest.ForeignKeyNavigation1, opt => opt.MapFrom(src => src.ForeignKeyNavigation1).ForAllOtherMembers(dest => dest.Ignore());`
With `Repository.GetQueryableResponse().ProjectTo<ADto>(Mapper.ConfigurationProvider);`
==> this will map only A1 and class B, so only class B will be retrieved from db. Property ForeignKeyNavigation2 or class C will be null. In the mapped ADto we will only find A1 and class BDto.

Same if I do only a configuration for class C

Imagine that I have 3 screens, one screen with all the data (ADto, BDto and CDto), a screen with only ADto and BDto (not CDto) and a screen with only ADto and Cdto.
So when in the second screen I only want to load ADto and BDto, but because the configuration is not changeable on the fly (I have the first 'everything' mapping option because of screen 1) I will load always everything. (Don't consider caching possibilities or why 3 screens, it is just an example :-) )

In another project we used a selfmade mapper and we had the possibility to add the wanted retrieval depth to the request: "I want ADto and only BDto, CDto can be null, not needed"

Is there a way to have the same behaviour with Automapper?
Didn't find directly an indication for this in the wiki.

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#explicit-expansion).

**Comment by lbargaoanu** [comment]
If that's what you wanted, you can close the issue.

**Comment by ericvb** [comment]
I did some tests with the proposed solution.

First the example in the wiki should be adapted, because it is not correct.
```
dbContext.Orders.ProjectTo<OrderDto>(parameters = null, dest => dest.Customer, dest => dest.LineItems);
```
==> "parameters = null" will never work, named parameters must be of syntax 'parameters:null'

Two solutions:
```
object parameters = null;
dbContext.Orders.ProjectTo<OrderDto>(parameters, dest => dest.Customer, dest => dest.LineItems);
```
or
``` 
dbContext.Orders.ProjectTo<OrderDto>((object) null, dest => dest.Customer, dest => dest.LineItems);
```

When implementing the code, I get a null reference exception in the linq provider
```
                return Repository.GetQueryableResponse()
                    .Where(i => i.Id == listNameId)
                    .ProjectTo<Models.BusinessModels.ListName>((object)null, dest => dest.Name, dest => dest.Id, dest => dest.ListValues);
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)

When I use the mapper configuration, I get the data without problems.
```
                return Repository.GetQueryableResponse()
                    .Where(i => i.Id == listNameId)
                    .ProjectTo<Models.BusinessModels.ListName>(Mapper.ConfigurationProvider);
```
The defined mappings in the configuration provider:
```
            CreateMap<Data.Models.DomainModels.ListName, Models.BusinessModels.ListName>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.ListValues, opt => opt.MapFrom(src => src.ListValues))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForAllOtherMembers(dest => dest.Ignore());
            CreateMap<Models.BusinessModels.ListName, Data.Models.DomainModels.ListName>();
            CreateMap<Data.Models.DomainModels.ListValue, Models.BusinessModels.ListValue>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.IsDeleted, opt => opt.MapFrom(src => src.IsDeleted))
                .ForMember(dest => dest.ListNameId, opt => opt.MapFrom(src => src.ListNameId))
                .ForMember(dest => dest.Value, opt => opt.MapFrom(src => src.Value))
                .ForMember(dest => dest.TranslationProxyIdDescription, opt => opt.MapFrom(src => src.TranslationProxyIdDescription))
                .ForMember(dest => dest.TranslationProxyIdShortDescription, opt => opt.MapFrom(src => src.TranslationProxyIdShortDescription))
                .ForMember(dest => dest.TranslationProxyDescription, opt => opt.MapFrom(src => src.TranslationProxyDescription))
                .ForMember(dest => dest.TranslationProxyShortDescription, opt => opt.MapFrom(src => src.TranslationProxyShortDescription))
                .ForAllOtherMembers(dest => dest.Ignore());
            CreateMap<Models.BusinessModels.ListValue, Data.Models.DomainModels.ListValue>();
```
First I thought that it was the ListValues collection, because how he knows to map the ListValue class? Is automapper using then the mapping configuration via the provider, or is it mapping everything?
So I did the same test, only requesting the name and id
```
                return Repository.GetQueryableResponse()
                    .Where(i => i.Id == listNameId)
                    .ProjectTo<Models.BusinessModels.ListName>((object)null, dest => dest.Name, dest => dest.Id);
```
But same exception.
The problem is where to start to debug that?

Second, I have another question, if I get it working this way, how I will limit the retrieval of non wanted objects in the second class ListValue?
With our custom mapper, we can write:
```
        private static readonly IRetrievalDepth DefaultRetrievalDepthListValue =
            RetrievalDepth.Create<Data.Models.DomainModels.ListName>()
                .Include(e => e.ListValues)
                .ThenInclude(e => e.TranslationProxyDescription)
                .ThenInclude(e => e.TranslationTexts) // and so on, if object TranslationTexts did have again a foreignkey to another object, we can continue this way.
                .GetDepth();
```
==> this will only retrieve the object TranslationProxyDescription, but not the object TranslationProxyShortDescription.

**Comment by lbargaoanu** [comment]
I didn't follow all that, but you have to pass the configuration _and_ the members to expand :) See [this test](https://github.com/AutoMapper/AutoMapper/blob/master/src/IntegrationTests.Net4/ExpandCollections.cs) for an example with collections. You can update the wiki yourself with what makes more sense.

**Comment by ericvb** [comment]
Okay, I see, I was just looking in the code to get the meaning of this parameter 'parameters'...
I will report back next week.
Didn't know that I had the right to adapt the wiki ;-)

**Comment by lbargaoanu** [comment]
Choose the overload that fits :) Check the other tests if you need more examples.

**Comment by ericvb** [comment]
Important is to set the ExplicitExpansion() method in the mapping configuration for the members you don't want to load.
Also the stackoverflow question was helpfull : http://stackoverflow.com/questions/25898237/prevent-automapper-projections-from-forcing-related-data-loading.
Thanks for the help.

**Comment by lbargaoanu** [comment]
Yes, by default everything is fetched.
