### ISSUE TITLE
Error Mapping Types

### ISSUE THREAD

**Issue by amirventer** [AutoMapper/AutoMapper#1683]
Hi,

I have the following classes:

    public class OutgoingTransaction
    {
        public DateTime TransactionDate { get; set; }
        public int TruckId { get; set; }
        public virtual Truck Truck { get; set; }
        public OutgoingTransaction()
        {
            TransactionDate = DateTime.Now;
        }
    }

    public class Truck
    {
        public string RegistrationNumber { get; set; }
        public int HaulierId { get; set; }
        public virtual Haulier Haulier { get; set; }

        public bool IsActive { get; set; }

        public Truck()
        {
            IsActive = true;
        }
    }

    public class Haulier
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsInternal { get; set; }
        public bool IsActive { get; set; }

        public Haulier()
        {
            IsActive = true;
        }
    }
`

And I use them in a console app as follows:

`
class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg => cfg.CreateMap<OutgoingTransaction, OutgoingTransactionDto>());

            var transaction = new OutgoingTransaction();

            var dto = Mapper.Map<OutgoingTransactionDto>(transaction);

        }
    }
`

It results in the following exception message using automapper version 5.1.1:

Error mapping types.

Mapping types:
OutgoingTransaction -> OutgoingTransactionDto
AutomapperTest.Models.Transactions.OutgoingTransaction -> AutomapperTest.Dtos.OutgoingTransactionDto

Type Map configuration:
OutgoingTransaction -> OutgoingTransactionDto
AutomapperTest.Models.Transactions.OutgoingTransaction -> AutomapperTest.Dtos.OutgoingTransactionDto

Property:
TruckHaulierName

When I use automapper version 4.2.1 it works.

Regards,

**Comment by lbargaoanu** [comment]
The code doesn't show. A gist maybe?

**Comment by lbargaoanu** [comment]
And you're missing the root error message.

**Comment by amirventer** [comment]
Here are the exception details:

AutoMapper.AutoMapperMappingException was unhandled
  HResult=-2146233088
  Message=Error mapping types.

Mapping types:
OutgoingTransaction -> OutgoingTransactionDto
AutomapperTest.Models.Transactions.OutgoingTransaction -> AutomapperTest.Dtos.OutgoingTransactionDto

Type Map configuration:
OutgoingTransaction -> OutgoingTransactionDto
AutomapperTest.Models.Transactions.OutgoingTransaction -> AutomapperTest.Dtos.OutgoingTransactionDto

Property:
TruckHaulierName
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Object , Object , ResolutionContext )
       at AutomapperTest.Program.Main(String[] args) in C:\Projects\AutomapperTest\AutomapperTest\Program.cs:line 16
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=Anonymously Hosted DynamicMethods Assembly
       StackTrace:
            at lambda_method(Closure , Object , Object , ResolutionContext )
       InnerException:

**Comment by lbargaoanu** [comment]
Ok, smth is null. You can check the upgrade guide in the wiki for why that might happen, but if that doesn't help, I still need to see the code.

**Comment by amirventer** [comment]
Strange cause I did post the code when I opened the issue.

Here you go again:

These are my classes.

public class OutgoingTransaction
{
    public DateTime TransactionDate { get; set; }
    public int TruckId { get; set; }
    public virtual Truck Truck { get; set; }
    public OutgoingTransaction()
    {
        TransactionDate = DateTime.Now;
    }
}

public class Truck
{
    public string RegistrationNumber { get; set; }
    public int HaulierId { get; set; }
    public virtual Haulier Haulier { get; set; }

    public bool IsActive { get; set; }

    public Truck()
    {
        IsActive = true;
    }
}

public class Haulier
{
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsInternal { get; set; }
    public bool IsActive { get; set; }

    public Haulier()
    {
        IsActive = true;
    }
}

public class OutgoingTransactionDto
    {
        public DateTime TransactionDate { get; set; }
        public int TruckHaulierId { get; set; }
        public int TruckId { get; set; }
        public string TruckHaulierName { get; set; }
        public string TruckRegistrationNumber {get; set;)

        public OutgoingTransactionDto()
        {
            TransactionDate = DateTime.Now;
        }
    }

And here is my console app code:

class Program
{
static void Main(string[] args)
{
Mapper.Initialize(cfg => cfg.CreateMap());

        var transaction = new OutgoingTransaction();

        var dto = Mapper.Map<OutgoingTransactionDto>(transaction);

    }
}

In my OutgoingTransactionDto class I'm flattening TruckHaulierName via the Truck and Haulier class.
If I comment out TruckHaulierName then no exception occurs. I also have TruckRegistrationNumber that gets flattened via Truck.

So it seems flattening is only working one level deep...

**Comment by lbargaoanu** [comment]
That's not helpful. GitHub is messing with you. Anyway, better try the MyGet build. If that works, you can close the issue, otherwise make a separate gist with the code.

**Comment by amirventer** [comment]
The MyGet build did the trick.

Thanks.
