### ISSUE TITLE
"Object reference not set to an instance of an object." while using own Resolver

### ISSUE THREAD

**Issue by skorunka** [AutoMapper/AutoMapper#1684]
Microsoft.AspNetCore.Mvc 1.0.1 application, Automapper 5

	public class ApiAutoMapperProfile : Profile
	{
		public ApiAutoMapperProfile()
		{
			this.CreateMap<Services.Dtos.TestRow, TestRow>()
				.ForMember(d => d.IdFormatted, o => o.ResolveUsing<TestFormattedIdResolver>())
				;
		}
	}

	public class TestFormattedIdResolver : IValueResolver<Services.Dtos.TestRow, TestRow, string>
	{
		private readonly IIdFormatter _idFormatter;

		public TestFormattedIdResolver([NotNull] IIdFormatter idFormatter)
		{
			if (idFormatter == null)
			{
				throw new ArgumentNullException(nameof(idFormatter));
			}

			this._idFormatter = idFormatter;
		}

		public string Resolve(Services.Dtos.TestRow source, TestRow destination, string destMember, ResolutionContext context)
		{
			return this._idFormatter.Format<Test>(source.Id);
		}
	}

	public class IdFormatter : IIdFormatter
	{
		public string Format<TEntity>(int id)
			where TEntity : class
		{
			return this.Format(typeof(TEntity), id);
		}

		public string Format(Type type, int id)
		{
			var prefix = "??";

			if (type == typeof(Test))
			{
				prefix = "TST";
			}
			else if (type == typeof(StoresSelectionRequest))
			{
				prefix = "STS";
			}
			else if (type == typeof(TestPerformanceReportRequest))
			{
				prefix = "LRN";
			}

			return prefix + id.ToString("0000000");
		}
	}

In Startup.cs

		public static void AddAutoMapper(this IServiceCollection services, IEnumerable<Assembly> assembliesToScan)
		{
			assembliesToScan = assembliesToScan as Assembly[] ?? assembliesToScan.ToArray();

			var allTypes = assembliesToScan.SelectMany(a => a.ExportedTypes).ToArray();

			var profiles =
				allTypes
					.Where(t => typeof(Profile).GetTypeInfo().IsAssignableFrom(t.GetTypeInfo()))
					.Where(t => !t.GetTypeInfo().IsAbstract);

			Mapper.Initialize(cfg =>
							{
								foreach (var profile in profiles)
								{
									cfg.AddProfile(profile);
								}
							});

			services.AddSingleton(Mapper.Configuration);

			services.AddTransient<IValueResolver<Services.Dtos.TestRow, TestRow, string>, TestFormattedIdResolver>();

			services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<AutoMapper.IConfigurationProvider>(), sp.GetService));
		}

and

			services.AddAutoMapper(new[] { typeof(Startup).Assembly });

Mapping:

	public class TestController : ApiControllerBase
	{
		private readonly ITestManagementService _testManagementService;

		public TestController(ITestManagementService testManagementService, ILoggerFactory logerFactory, IRequestContext requestContext, IMapper mapper) : base(logerFactory, requestContext, mapper)
		{
			if (testManagementService == null)
			{
				throw new ArgumentNullException(nameof(testManagementService));
			}

			this._testManagementService = testManagementService;
		}

		[HttpGet]
		public IActionResult GetAll(DTParameters request)
		{
....
			var result = this.Mapper.Map<ICollection<Services.Dtos.TestRow>, ICollection<TestRow>>(table.Items).ToList(),

			return new ObjectResult(result);
		}

![image](https://cloud.githubusercontent.com/assets/218913/18609236/21fa1da8-7cf5-11e6-9bbb-42c25d340663.png)

AutoMapper.AutoMapperMappingException was unhandled by user code
  HResult=-2146233088
  Message=Error mapping types.

Mapping types:
ICollection`1 -> ICollection`1
System.Collections.Generic.ICollection`1[[Eyc.Solutions.TestAndLearn.Services.Dtos.TestRow, Eyc.Solutions.TestAndLearn.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.ICollection`1[[Eyc.Solutions.TestAndLearn.Ui.Web.Areas.Api.Models.TestRow, Eyc.Solutions.TestAndLearn.Ui.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , ICollection`1 , ICollection`1 , ResolutionContext )
       at Eyc.Solutions.TestAndLearn.Ui.Web.Areas.Api.Controllers.TestController.GetAll(DTParameters request) in C:\Projects\EYC\TestAndLearn\src\Eyc.Solutions.TestAndLearn.Ui.Web\Areas\Api\Controllers\TestController.cs:line 39
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: 
       HResult=-2146233088
       Message=Error mapping types.

Mapping types:
TestRow -> TestRow
Eyc.Solutions.TestAndLearn.Services.Dtos.TestRow -> Eyc.Solutions.TestAndLearn.Ui.Web.Areas.Api.Models.TestRow

Type Map configuration:
TestRow -> TestRow
Eyc.Solutions.TestAndLearn.Services.Dtos.TestRow -> Eyc.Solutions.TestAndLearn.Ui.Web.Areas.Api.Models.TestRow

Property:
IdFormatted
       Source=Anonymously Hosted DynamicMethods Assembly
       StackTrace:
            at lambda_method(Closure , ICollection`1 , ICollection`1 , ResolutionContext )
       InnerException: 
            HResult=-2147467261
            Message=Object reference not set to an instance of an object.
            Source=Anonymously Hosted DynamicMethods Assembly
            StackTrace:
                 at lambda_method(Closure , ICollection`1 , ICollection`1 , ResolutionContext )
            InnerException:

**Comment by lbargaoanu** [comment]
TestFormattedIdResolver needs to be resolved by your container, not by AutoMapper. Try ConstructServicesUsing instead.

**Comment by lbargaoanu** [comment]
I guess you already did that in a different way :) But you specified the concrete type for the resolver and that's not registered.

**Comment by lbargaoanu** [comment]
Anyway, all this is kind of complicated. Useful if you need scoped dependencies, but that's not the case here. Also, profile scanning is built in now.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jbogard** [comment]
Yeah, just use the other package, it works.

**Comment by skorunka** [comment]
Lovely, thank  you.
