### ISSUE TITLE
MethodAccessException: Windows Phone 8.1 (WinRT)

### ISSUE THREAD

**Issue by adamlysak** [AutoMapper/AutoMapper#1685]
I have PCL where I using AutoMapper 5.1.1 with code:

```
var mapperConfig = new MapperConfiguration(cfg =>
{
    cfg.AddProfile<TileProfile>();
    cfg.AddProfile<PictureProfile>();
    ...
});

var mapper = mapperConfig.CreateMapper();
```

Which working well with WinForms but when use my library with Windows Phone 8.1 (WinRT) then I get exception in **MapperConfiguration** constructor:

```
System.MethodAccessException was unhandled by user code
  HResult=-2146233072
  Message=Attempt by security transparent method 'AutoMapper.Profile..ctor()' to access security critical method 'System.Collections.Concurrent.ConcurrentDictionary`2<System.__Canon,System.__Canon>..ctor()' failed.
  Source=AutoMapper
  StackTrace:
       at AutoMapper.Profile..ctor()
       at AutoMapper.Configuration.MapperConfigurationExpression..ctor()
       at AutoMapper.MapperConfiguration.Build(Action`1 configure)
       at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
  InnerException: 
```

I also create blank Windows Phone 8.1 project for test with only Automapper nuget package and this code:

```
...
public MainPage()
{
    this.InitializeComponent();

    var mapperConfig = new MapperConfiguration(cfg => {});
}
...

```

with same result. Do anyone some experience with this issue? 
It looks like to me as bug in Automapper.

Thanks

Version: 
Automapper 5.1.1, portable-net45+win8+wpa81

**Comment by lbargaoanu** [comment]
Try googling that error.

**Comment by AKorpysz** [comment]
I've the same issue.
Unfortunately answers google answers are not working.
Could someone share any idea how to fix that error ?
Thank in advance

**Comment by adamlysak** [comment]
I fix the issue by recompiling Automapper from source and removing attribute:
`[assembly: AllowPartiallyTrustedCallers]`
from the AssemblyInfo.cs

**Comment by jbogard** [comment]
Seriously?!?

**Comment by adamlysak** [comment]
Yes, really

**Comment by jbogard** [comment]
Well that's an easy fix then. I can just include that for full .NET

**Comment by lbargaoanu** [comment]
@jbogard There's nothing wrong with that attribute (and it helps with performance, remember? :)). They just need to set smth in their app.

**Comment by lbargaoanu** [comment]
Oh, windows phone, ok :)

**Comment by lbargaoanu** [comment]
But the thing is, [MSDN](https://msdn.microsoft.com/en-us/library/system.security.allowpartiallytrustedcallersattribute%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) says it's supported.

**Comment by jbogard** [comment]
Do you have some repro steps? I want to make sure this can fix it.

**Comment by adamlysak** [comment]
Well, same steps as I wrote in my first post.
1. Create empty Windows Phone 8.1 project
2. Add Automapper 5.1.1 from nuget
3. Intialialize MapperConfiguration. For example Like:
`var mapperConfig = new MapperConfiguration(cfg => {});`

I can attach sample VS solution where problem occurs if you want.

**Comment by lbargaoanu** [comment]
What about AllowPartiallyTrustedCallers in the calling app? It worked for [us](https://github.com/AutoMapper/AutoMapper/blob/7b4d535af9208b904977ee11383c61ee8cb8a16c/src/Benchmark/Program.cs#L6).

**Comment by adamlysak** [comment]
On WP81 **AllowPartiallyTrustedCallers** attribute is not working.
It ends on exception:
`System.FieldAccessException
Attempt by method '*****.Program.Main(System.String[])' to access field '******.Program+<>c.<>9__0_0' failed.`

**Comment by lbargaoanu** [comment]
Weird. The docs must be wrong then.

**Comment by AKorpysz** [comment]
@adamlysak  thank you for your help, temporarly i'll compile from sources
