### ISSUE TITLE
Create a map configuration at runtime

### ISSUE THREAD

**Issue by aoancea** [AutoMapper/AutoMapper#1686]
I am wondering if there is a way of creating a mapping configuration at runtime. This can be used for situations where you want to **streamline** the mapping process which in this case can be a **1:1** match and otherwise you don't care.

**Having the following classes**

``` c#
public class FirstClass
{
    public int Int { get; set; }
}

public class SecondClass
{
    public int Int { get; set; }
}
```

**and this extension method**

``` c#
public static class AutoMapperExtension
{
    public static TDestination DeepCopyTo<TDestination>(this object source)
    {
        Type sourceType = source.GetType();

        // Create a mapping configuration(the question is this)

        return (TDestination)AutoMapper.Mapper.Map(source, sourceType, typeof(TDestination));
    }
}
```

**would it be possible for me to do something like**

``` c#
public void Process()
{
    FirstClass firstClass = new FirstClass() { Int = 5 };

    // no mapping going on in here and anywhere else for that matter(inside .DeepCopyTo<> only)

    SecondClass secondClass = firstClass.DeepCopyTo<SecondClass>(); 
}
```

I have a working implementation for what I described above which can be found [here](https://github.com/QubizSolutions/quiz-engine/blob/master/src/Infrastructure/Mapper.cs). Unit tests can also be found [here](https://github.com/QubizSolutions/quiz-engine/blob/master/src/UnitTesting/Infrastructure/MapperTest.cs).

I know that it lacks some caching so that it doesn't try to create a map which already exists :bomb:

If there isn't anything yet like this for **AutoMapper** I would gladly help place it in as I also need it badly in multiple projects. Having it through the NuGet package would make my life easier and probably others' as well.

@jbogard

**Comment by lbargaoanu** [comment]
Smth like this already exists and it causes more problems than it solves. Search the issues for CreateMissingTypeMaps.

**Comment by aoancea** [comment]
I had a look over mostly all issues involving `CreateMissingTypeMaps` and from what I understand it might get removed as it's causing some issues.

I'm still trying to understand why this runtime mapping configuration gives such an headache.
Is AutoMapper not intended to work this way as I still managed to trick him by using an extension which mimics the exact behavior of manual mapping. Was it never intended to work without manual mappings?

I'm asking this because if you have 100-200+ classes to map, which are mostly the same but with different namespace, it's a pain in manually configuring everything.

And the final question would be: Wouldn't an extension that automatically maps a configuration at runtime be a good idea? It can have access to mappings that already exist so it doesn't try and register them again(override them)

**Comment by lbargaoanu** [comment]
The right way to solve it is to write some reflection code that calls CreateMap (the non-generic version) for all those types. But you need to be explicit about what you map.

**Comment by aoancea** [comment]
Well yeah, I did just that, part from the non-generic method.

I just did a quick test and it seems it works with the non-generic version as well

```c#
typeof(AutoMapper.Mapper)
	.GetMethod("CreateMap", new Type[2] { typeof(Type), typeof(Type) })
	.Invoke(null, new object[] { actualSourceType, actualDestinationType });
```

**Comment by lbargaoanu** [comment]
:) No. What I meant is to do this at init time, in Mapper.Initialize for example.

**Comment by aoancea** [comment]
Sorry, but I still don't get why this can't be done at runtime. What's the actual case in which all hell breaks loose?

Or is it that the basic concept behind *AutoMapper* is to be used with a proper configuration prior to runtime? Because if that's the case, then I understand it partially.

**Comment by jbogard** [comment]
Just call CreateMap. Seriously. You're far, far better off with the safety
of configuration validation than without it.

CreateMissingTypeMaps is really about when you don't know the types at
compile time. If you do, there's no reason you should use dynamic
maps/create missing maps.

It might take you a half an hour to put in all those CreateMap calls. But
it's much better than accidentally misspelling something, and only finding
out about it at runtime.

Create profiles if you want to make it easier to manage, we do. But call
CreateMap.

Do it.

**Comment by aoancea** [comment]
Well ok then.

I do believe that the misspelling part can be handled elegantly by unit tests and we should not have cumbersome configuration just because mistakes can get it.

We are all humans, and we all do mistakes, simply because that.

If you ask me, I would go with:
- runtime configuration for streamline mappings only(source and destination have same property names, even when some properties might be missing from either - we simply don't map those)
- manual configuration when you need to map properties which have different names(this should probably be refactored so that streamlining is achieved - where possible ofc)

I believe we can close this as the conclusion is that the way to go is to initialize everything at the beginning.

**Comment by jbogard** [comment]
FYI the unit test is just one thing, Mapper.AssertConfigurationIsValid.
That covers all your mappings, instead of you writing tests per mapping.
That was another goal I had, easy testability.

I suggest explicit configuration because it's the safest option with the
least work using AutoMapper. I even go as far to recommend that if you
can't call the Assert configuration method, you shouldn't use AutoMapper,
there's just too much that can go wrong.

HOWEVER, you can be smart about calling CreateMap. Because mapping config
is additive, you can use some conventions for the 90% case and manual
config for the rest.

**Comment by aoancea** [comment]
Exactly about those 90% I'm suggesting this. And manually added configurations should not be overridden.

But then again, I believe it will end up a mammoth with everything that everyone dreamed last night.

And your argument is also perfectly valid since you state it very clear for which it is designed.

**Comment by jbogard** [comment]
I guess I just don't see the issue with being explicit. We configure
explicitly with a couple hundred mappings without any management issue. In
any case, the missing type map stuff isn't what you want. If you do get the
convention stuff working, would you mind posting what it looks like? I'm
trying to gather scenarios for supporting this directly.

**Comment by aoancea** [comment]
If I can let the machine do my work for me, I would always put in the extra effort to achieve that.

I am working on an implementation right now, backed with unit tests, and you can find it [here](https://github.com/QubizSolutions/quiz-engine/blob/master/src/Infrastructure/Mapper.cs) and tests [here](https://github.com/QubizSolutions/quiz-engine/blob/master/src/UnitTesting/Infrastructure/MapperTest.cs)

It might be a little messy atm, but it will be given a final touch in the end. The only thing that I don't like, but which is kinda necessary for certain scenarios, is regarding the `circular reference` and that's because here I need to construct the mapping of the whole object graph directly since **AutoMapper** won't be using internally my extension method which could be called from every lower level mappings which will also create the mapping configuration.

I'm also thinking to move this extension to a NuGet package since I'm it in several projects. Do you have any suggestions around that?(I haven't put anything before on NuGet so I would appreciate a tip even though I know it would prolly take 1h to get me started with the information on the internet :) )

**Comment by aoancea** [comment]
Would it be a viable option to create a new repository under **AutoMapper** named `AutoMapper.Extensions` which currently will have an `alpha` or `beta` version under which we can test if this is viable? And also to be placed in a nuget package.

**Comment by jbogard** [comment]
I dunno, if the feature seems useful enough I could just include it in the main project.

**Comment by jbogard** [comment]
But one thing off - you still call CreateMap every time - I wouldn't do that. I'd still have CreateMap called only once per AppDomain. But maybe be much smarter about how it figures out what to map to each other. `Mapper.CreateMap` is gone in 5.0, so this wouldn't work there.

**Comment by aoancea** [comment]
Right, the 5.0 is instance based now. I'll have a look these days to see how this can be adapted.

On the AppDomain part, I believe there should be then a shared collection with the mappings for that to happen since 5.0 is instance based.

**Comment by jbogard** [comment]
Well, kinda, there's still a static API, you just have to use
Mapper.Initialize.

**Comment by aoancea** [comment]
Oh ok. I'll have a look then.

Just a little bit angry cuz exactly 1 week ago I was to the doctor with a cold, and now it returned :(

**Comment by aoancea** [comment]
I managed to do some researched and came up with [this](https://github.com/aoancea/automapper-extensions/blob/master/src/AutoMapper.Extensions/AutoMapperExtensions.cs)

It seems like the implementation around it seals any new types to be added at runtime. I manage to get in but there is still an issue when you try to map to same type.

Considering the effort placed into making only this, I'm not sure how much is it worth investigating further. It would help though if the AutoMapper Api would let you at least register stuff inside the configuration and use it afterwards. Maybe a new implementation of the config class, but I'm not sure how much complexity is gonna be introduced by that for maintainance.

Let me know what you think :)

**Comment by jbogard** [comment]
Hmmmm, so that example still looks like it tries to add the map at runtime,
instead of at configuration time, am I reading that right?

What you'd really want is something inside of a Mapper.Initialize.

**Comment by aoancea** [comment]
Well yeah, I'm trying to get those configurations in at runtime inside the `AutoMapper.Configuration.MapperConfigurationExpression` so that they are shared.

But as I said above, the code seems to do something else, and that is `Seal` everything at **Startup** and by doing this I get what you mean in getting everything at `Mapper.Initialize`

I've also had a look if I could find a tool that could give us the references of a method inside the application. This would mean that we might be able to really map everything at startup.

I found this [reference](http://stackoverflow.com/questions/5490025/c-sharp-reflection-and-finding-all-references) but didn't had the time to play with it yet. It might seem viable.

**Comment by jbogard** [comment]
Ahhh, so now that is interesting. Find all places you're calling
Mapper.Map, and register maps for them.

It would get 90% of the cases, but not the inner class cases, where a sub
property contains a map.

Is there some naming convention you're already following for
source/destination types mapped? Or is it just the wild west, anything goes?

**Comment by aoancea** [comment]
Ok so, I believe I cracked it somehow and I got it to work. Basically we still need to handle all those aggregate classes inside the code when we build the mapping configuration and also need to account for the circular references. There might as well be other stuff that we'll have to handle, but I guess it can be coded pretty easy.

**Comment by jbogard** [comment]
Thanks for the update!
