### ISSUE TITLE
Mapping error when mapping to IReadOnlyDictionary

### ISSUE THREAD

**Issue by prochnowc** [AutoMapper/AutoMapper#1689]
Using AutoMapper 5.1.1 under .NET Core.

I have destination model which has IReadOnlyDictionary property. When mapping this property using ResolveUsing() an exception gets thrown:

```
class Source { IDictionary<string, SourceEntry> Data; }
class Destination { IReadOnlyDictionary<string, object> Data; }

mapper.CreateMap<Source,Destination>().ForMember(d => d.Data, s => s.ResolveUsing(v => ConvertDataDictionary(v.Data)));

mapper.Map<Destination>(source);

```

System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List1[System.Collections.Generic.KeyValuePair2[System.String,System.Object]]' to type 'System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Object]'.
at lambda_method(Closure , AuditEventModel , AuditEvent , ResolutionContext )
--- End of inner exception stack trace ---
at lambda_method(Closure , AuditEventModel , AuditEvent , ResolutionContext )
at AutoMapper.Mapper.AutoMapper.IMapper.MapTSource,TDestination

When i put separate converter mapping from source type to destination type it works:

```
c.CreateMap<IDictionary<string, SourceEntry>, IReadOnlyDictionary<string, object>>()
                     .ConvertUsing(ConvertDataDictionary);
```

**Comment by lbargaoanu** [comment]
Yes, AutoMapper doesn't consider IReadOnlyDictionary.

**Comment by prochnowc** [comment]
Ok, but why does it even try to convert when using ResolveUsing?
If this is intended behavior i would consider missing support for IReadOnly* types as a bug.

**Comment by lbargaoanu** [comment]
About ResolveUsing, I need to see all the code. About the read only interfaces, well, someone has to write the code. Feel free to pitch in.

**Comment by prochnowc** [comment]
```
using System.Collections.Generic;
using System.Collections.ObjectModel;
using AutoMapper;

namespace AutoMapperTest
{
    class DataItem
    {
        public string Type { get; set; }
        public string Value { get; set; }
    }

    class SourceModel
    {
        public IDictionary<string, DataItem> Data { get; set; }
    }

    class DestinationModel
    {
        public IReadOnlyDictionary<string, object> Data { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var configuration = new MapperConfiguration(
                c =>
                {
                    c.CreateMap<SourceModel, DestinationModel>()
                     .ForMember(d => d.Data, s => s.ResolveUsing(v => ConvertDataDictionary(v.Data)));
                });

            IMapper mapper = new Mapper(configuration);

            var source = new SourceModel
            {
                Data = new Dictionary<string, DataItem>
                {
                    { "item", new DataItem { Type = "itemType", Value = "itemValue" } }
                }
            };

            mapper.Map<DestinationModel>(source);
        }

        private static IReadOnlyDictionary<string, object> ConvertDataDictionary(IDictionary<string, DataItem> data)
        {
            return new ReadOnlyDictionary<string, object>(new Dictionary<string, object>());
        }
    }
}

```

**Comment by lbargaoanu** [comment]
IReadOnlyCollection is IEnumerable and AM tries to map it as such, but that doesn't work. It needs to be special cased. When you create the map, that prevails and it works.

**Comment by prochnowc** [comment]
If you point me to the right direction i can start implement support for read only collection interfaces.

**Comment by lbargaoanu** [comment]
The DictionaryMapper uses an extension method IsDictionaryType and that one could check also the read only interface. That's the first thing that comes to mind.

**Comment by thomaslevesque** [comment]
> The DictionaryMapper uses an extension method IsDictionaryType and that one could check also the read only interface. That's the first thing that comes to mind.

Unfortunately, that's not enough. You also need to change `GetDictionaryType`. But even then, it doesn't work, because AutoMapper creates an instance, then attempts to add elements to it, via the interface. Which of course doesn't work for `IReadOnlyDictionary`.

**Comment by lbargaoanu** [comment]
Dictionary implements IReadOnlyDictionary too (and other classes). So maybe you want ReadOnlyDictionary, the class. I guess you would need a separate mapper for that.
