### ISSUE TITLE
Use of AutoMapper and EF Core: What for queries EF Core is producing from AutoMapper ProjectTo?

### ISSUE THREAD

**Issue by ericvb** [AutoMapper/AutoMapper#1694]
This is probably a problem or 'a yet to do enhancement' inside EF Core, but I think it is good to mention it here.
I don't know enought about the inside code of AutoMapper to judge if it is totally a EF Core problem or not.
I did some tests with the IntegrationsTests.Net4 project inside the source solution of AutoMapper with EF 6 and the same with EF Core and the queries produced are quit different.
See my [issue](https://github.com/aspnet/EntityFramework/issues/6576) posted on the github EF Core to get the reproducing steps.

**Comment by lbargaoanu** [comment]
This doesn't seem to have much to do with AutoMapper. So I would say close this for now and reopen if it proves otherwise.

**Comment by ericvb** [comment]
I know, that's why it is just a reference to an issue on EF Core github.

But I wanted to grep the attention of Jimmy about this. He knows as the best the code of automapper so he can quickly judge if it is really a EF Core problem or maybe a different way of working with EF Core.

**Comment by jbogard** [comment]
What I do is create the Select expression manually with the query provider. All AutoMapper does is create a LINQ Select expression, so just do it yourself and see what happens.

**Comment by ericvb** [comment]
Ok, then it is an EF Core problem.
Attached to the EF Core issue, there is a Zip file with a project IntegrationTests.Core, a begin to include also a .NET Core test environment. Maybe interesting to include?
