### ISSUE TITLE
Mapping complex object to Entity Framework does not save Changes

### ISSUE THREAD

**Issue by HJLuecking** [AutoMapper/AutoMapper#1695]
This code does not save references to complex objects / does not save child object changes.

`var partner = _mapper.Map<PARTNER>(item); // the partner objects have complex objects`
`_context.Set<PARTNER>().Attach(partner );`
`_context.Entry<PARTNER>(part).State = EntityState.Modified;`
`_context.SaveChanges();`

Does there exist a solution  on how to map and (!) save complex objects using Entity Framework without coding each child object.?

**Comment by jbogard** [comment]
Sure! Just not using AutoMapper, I don't reverse map, it gets too
complicated.

**Comment by TylerCarlson1** [comment]
[AutoMapper.Collection](https://github.com/TylerCarlson1/Automapper.Collection) can handle saving child objects, but complex objects are always a problem

**Comment by Jenan** [comment]
@jbogard You mentioned - don't use automapper - but how solve mapping before updating an entity?
Thank you.

**Comment by chkien0911** [comment]
@Jenan I found a solution.
Instead of using:
// query to get the entity here
// then map data like this
entity = _mapper.Map<YourViewModel, YourEntity>(viewModel);

you just need to change the mapping data like this:
_mapper.Map<YourViewModel, YourEntity>(viewModel, entity);

and you just call dbContext.SaveChanges(), no need to attach entity anymore.

**Comment by Jenan** [comment]
@chkien0911 Thank you for your post. Is it required the entity load before update? How do you do it?

**Comment by chkien0911** [comment]
@Jenan yes, you have to get the entity by its id first
then map the data like this
_mapper.Map<YourViewModel, YourEntity>(viewModel, entity);
Finally, just call SaveChanges, no need to atttach & set state since DB has been tracking the changes.

**Comment by TylerCarlson1** [comment]
@Jenan @chkien0911 
https://github.com/AutoMapper/AutoMapper.Collection#what-about-comparing-to-a-single-existing-entity-for-updating

This will find and update the object for you by primary key from EF.  Also will add entity if it doesn't exist, so less lines of code needed.
