### ISSUE TITLE
Polymorphing apping Child[] to IList<Parent> produces error in CollectionMapperExtensions

### ISSUE THREAD

**Issue by exones** [AutoMapper/AutoMapper#1696]
## Description
(see reproduction code)
* Consider having empty classes Parent and Child (Child is a descendant of Parent) and Corresponding DTOs for them with the same inheritance
* Consider having class Things, containing property IList<**Parent**> Items 
* and corresponding DTO ThingsDto, containing property IList<**ChildDto**> Items 

## Reproduction code
``` 
    class Program {
        class Parent  {}
        class Child : Parent {}
        class Things       { public IList<Parent> Items { get; set; } }
        class ParentDto {} 
        class ChildDto : ParentDto {}
        class ThingsDto        { public ChildDto[] Items { get; set; } }

        static void Main(string[] args) {
            Mapper.Initialize(config =>
            {
                config.CreateMap<ParentDto, Parent>()
                    .Include<ChildDto, Child>();
                config.CreateMap<ChildDto, Child>();
                config.CreateMap<ThingsDto, Things>();
            });
        }
    }
```

## Expected behavior
Property ThingsDto.Items should be mapped to property Things.Items in the following manner (according to ):
* Create target list `Things.Items = new List<Parent>()`
* Clear target list: `Things.Items.Clear()` (using method `ICollection<Parent>.Clear()`) <- **the problem is here**
* foreach `ThingsDto.Items` convert `ChildDto`->`Child`, cast to `Parent` and add to `Things.Items` via ICollection<Parent>.Add()

## Actual behavior
Exception: 
> Unhandled Exception: System.ArgumentException: Method 'Void Add(Child)' declared on type 'System.Collections.Generic.ICollection'1[AutoMapper.CollectionMappingIssue.Program+Child]' cannot be called with instance of type 'System.Collections.Generic.IList'1[AutoMapper.CollectionMappingIssue.Program+Parent]'

## Analysis
Error occurs in CollectionMapperExtensions.MapCollectionExpression as following:
* It maps correctly list items ChildDto -> Parent and resolves the target class as Child (good)
* It creates an expression to create target list as `new List<Parent>()` to assign it to `Things.Items` of type `IList<Parent>` (good)
* But then it gets the method `void ICollection<Child>.Clear()`, not `void ICollection<Parent>.Clear()` (bad)
* It tries to call `void ICollection<Child>.Clear()` on an object of class `List<Parent>`, hence the exception (bad)
* **Also**, it does the same with the following methods, like `Add()` (bad)

The problem is on line 32 of `CollectionMapper.cs`:
```
var destinationElementType = itemExpr.Type;

//WRONG: should get element type from actual accepting property, not of the resolved type (Child in our case)
var destinationCollectionType = typeof(ICollection<>).MakeGenericType(destinationElementType); 

var clearMethod = destinationCollectionType.GetDeclaredMethod("Clear");
```

**Comment by lbargaoanu** [comment]
Duplicate of #1656. You can close the issue.

**Comment by exones** [comment]
Thank you, lbargaoan
