### ISSUE TITLE
Issue with the Custom Resolver

### ISSUE THREAD

**Issue by lolekjohn** [AutoMapper/AutoMapper#1699]
Hi,

We were using the automapper v5.0 in our code. In our create map statement, we had a statement ->
m.ResolveUsing((src, o, context) => (CodeObject)context.Options.Items["test"]))

When we upgraded the Automapper version to 5.1.1, we are getting build error in the above statement. 

Can you please suggest how to correct this with latest version.

Regards,
Lolek

**Comment by jbogard** [comment]
The overloads have changed slightly, if you check Intellisense you'll find the one you need. I don't remember what the old parameters were or I'd be able to point you exactly how to fix it.

**Comment by lolekjohn** [comment]
Finally i have got the answer after going through the automapper source code. We can do it this way:

> m => m.ResolveUsing((src, o, destMemb, context) => (CodeObject)context.Items["test"]))
