### ISSUE TITLE
using AutoMapper.Internal; 

### ISSUE THREAD

**Issue by karcshub** [AutoMapper/AutoMapper#1700]
Am trying to run an app but it brings an error that says "
The type or namespace name 'Internal' does not exist in the namespace 'AutoMapper' (are you missing an assembly reference?) What could be the problem?

**Comment by jbogard** [comment]
That namespace is gone. Remove the using statement.

**Comment by karcshub** [comment]
Thanks! I solved it by using a lower version nuget package,are there any issues with doing that

**Comment by jbogard** [comment]
Sure if you want the slow version.

**Comment by karcshub** [comment]
OOhw.. thats bad,so it has something to do with the speed of the application!
Are there any solutions that you would recommend?
Thanks!

**Comment by jbogard** [comment]
Well, remove the using statements. I assume you're using the 5.x version?
I've removed that namespace, it was too confusing.

What types are missing?

**Comment by karcshub** [comment]
Okay thanks!,its no longer complaining about it
