### ISSUE TITLE
Merge configurations

### ISSUE THREAD

**Issue by draepetan** [AutoMapper/AutoMapper#1701]
As an enhancement, I think it could be useful to have a first class ability to merge configurations.

Use Case:
I have several projects that have their own mapping responsibilities rather than having some monster mapping configuration class. Using an IoC container, when requesting IMapper, I'd like it to be able to visit other assemblies to pick up mapping configurations:

![image](https://cloud.githubusercontent.com/assets/3442089/18853347/82615e1c-83f9-11e6-8806-da946c29ed4f.png)

So basically, it would be useful to have the ability to take the configuration from an IMapper instance and merge in one or more other configurations. In my case here, the container would resolve the default instance of the mapper and then have it visit other assemblies, merging in their mapper configurations.

I realize this seems to imply some pretty wonky architecture, but not really. In most cases, the application layer might define the mapping because only it has both the source and destination type references, but in other cases (e.g. large solutions), both of those references might reside in a separate assembly, which is a scenario where the application could benefit by using that existing mapping.

For example: a data layer. The data layer assembly may be set up to map from DAO to service DTO directly rather than going through a domain mapping first, depending on the application architecture. In that case, the data layer will have both object types. If there were multiple data layer assemblies, you'd want to be able to reuse those mappings from different consumers of that assembly. If you were to configure the mappings in the consumer of the data assembly (e.g. a specific application layer), then a different consumer (or application) would have to have it's own configuration, which is just repeated work in this case.

I imagine the desired interface would be simple. Maybe something like this added to `IConfigurationProvider`:

`void Merge(IConfigurationProvider cfg);`

so that it could be used like:

``` csharp
IMapper mapper = configA.Configuration.CreateMapper():
mapper.ConfigurationProvider.Merge(configB);
mapper.ConfigurationProvider.Merge(configC);
```

**Comment by draepetan** [comment]
I think this might have been achievable with the old interface by simply passing the mapper around and having the external assemblies call CreateMap on the mapper instance.

**Comment by jbogard** [comment]
Profiles plus assembly scanning in 5.1, would that work?

**Comment by draepetan** [comment]
not sure what you're referring to?

**Comment by lbargaoanu** [comment]
@draepetan You can start from [here](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=addprofiles).
