### ISSUE TITLE
Version 5.1.1 Causes Run Issue in ASP.NET

### ISSUE THREAD

**Issue by RealDotNetDave** [AutoMapper/AutoMapper#1704]
I have a ASP.NET 4.6.2 web site that uses AutoMapper. When I installed 5.1.1, when I ran the site I got an error that AutoMapper would not load due to a missing reference.

I went back to the previous version and site runs fine.

**Comment by jbogard** [comment]
Do you have a stack trace? Or what the missing reference was? What kind of exception was it?

**Comment by RealDotNetDave** [comment]
I'm speaking at Silicon Valley Code Camp, so I can reproduce it and let you know next week. All I remember is that .NET could not load AutoMapper because of a reference.
