### ISSUE TITLE
Regression in Auomapper 5 with multiple reference to the same instance

### ISSUE THREAD

**Issue by fbeauche** [AutoMapper/AutoMapper#1706]
When mapping an object graph with multiple reference to same instance, Automapper 5 does not have the same behavior than version 4.2.1. 

I've created a small repro to illustrate the problem : 
https://github.com/fbeauche/Automapper5InstanceBug/tree/master/src

Consider the following object model with the matching DTO 
```
 public class OrderContainer
    {
        public Order A { get; set; }
        public Order B { get; set; }
    }

    public class Order
    {
        public int ID { get; set; }
        public OrderContainer Container { get; set; }
    }

```
If the same order is put in A & B of the container, Autommaper 5 create a new instance of the OrderDto where AutoMapper 4 was creating only one instance : 

 ```
        var orderContainer = new OrderContainer();
            order.Container = orderContainer;
            orderContainer.A = order; // A & B contains the same object instance
            orderContainer.B = order;

            var dto = mapper.Map<OrderContainerDto>(orderContainer);

            Assert.AreSame(dto.A, dto.B); // With 4.2.1, this is true
```

**Comment by lbargaoanu** [comment]
See [here](https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#circular-references).

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by fbeauche** [comment]
Indeed, my bad, I did not read the end of this upgrade guide  

Thanks a lot !
