### ISSUE TITLE
Upgrade AutoMapper 4.2.1 to 5.1.1

### ISSUE THREAD

**Issue by flowdopip** [AutoMapper/AutoMapper#1707]
Hi,

I have a lot of class´s that implements : Profile and use of override of Configure. I´ve changed to ctor of the class.

I´ve an Adapter for Autommaper and the migration doesn't have compilation Erros. On execution time the automapper map the objects but the values are not set. AssertConfigurationIsValid doesn't show any error.

Any idea?

**Comment by flowdopip** [comment]
I´ve found the issue.

Over my maps i allows put this .ForAllMembers(opt => opt.Ignore()); as the first mapping setting only then that i define the property maps.

I´ve change to .ForAllOtherMembers(opt => opt.Ignore());  at last and works.

thanks

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by flowdopip** [comment]
do you have this documented? because this behavior as changed!

**Comment by lbargaoanu** [comment]
ForAllMembers is void for a long time now :) But still, if you feel it's needed, add something useful in the upgrade guide.

**Comment by flowdopip** [comment]
I just ask for this because the behavior from 4.2.1 to 5.1 is different. 
Ok Thanks
