### ISSUE TITLE
Option to use AsNoTracking internally in ProjectTo method

### ISSUE THREAD

**Issue by noufionline** [AutoMapper/AutoMapper#1708]
Please provide a property to to facilitate calling AsNoTracking just before calling ProjectTo<T> method by providing a setting which can be set at the time of mapping.
Something like 
`CreateMap<Destination,Source>().WithoutTracking();`

**Comment by jbogard** [comment]
I don't know what AsNoTracking is. But in general, you shouldn't have
anything after ProjectTo except for materializing the results with ToArray
or ToList

**Comment by noufionline** [comment]
Thanks for your quick reply.
My suggestion is to call AsNoTracking before the ProjectTo call. In web applications line mvc controller there is no point in having entityframework change tracking and this feature can help

**Comment by jbogard** [comment]
AutoMapper has no reference to EF, and won't, so what would this do? Beyond
that, the EF query provider uses the Select projection to skip entities
entirely and execute raw SQL to populate DTOs.

Are you seeing entities getting loaded and tracked?

**Comment by lbargaoanu** [comment]
Those entities don't exist in memory, it's from SQL to DTOs, so I don't think it would help.

**Comment by noufionline** [comment]
Oh I see. If that is the case I can manage with an extension method to get my job done!

Thanks for your quick support.

**Comment by jbogard** [comment]
I don't think the extension method will do anything though. You shouldn't
need to call the no tracking thing at all with projections.

**Comment by noufionline** [comment]
Now I understand.
Thanks for your help.
Noufal

Get Outlook for iOS




On Fri, Sep 30, 2016 at 9:39 PM +0400, "Jimmy Bogard" <notifications@github.com> wrote:










I don't think the extension method will do anything though. You shouldn't

need to call the no tracking thing at all with projections.
