### ISSUE TITLE
RecognizePrefixes does not work

### ISSUE THREAD

**Issue by bitcruiser** [AutoMapper/AutoMapper#1710]
Hi, 
Using : `<package id="AutoMapper" version="5.1.1" targetFramework="net45" />`

I have a problem with ReconizePrefixes configuration.

in Mapper.Initialize :
```
cfg.RecognizePrefixes("f");
CreateMap<SourceModel, DestinationModel>();
CreateMap<DestinationModel, SourceModel>();
```

my classes:
```
public class SourceModel
{
	public string fName { get; set; } 
}

public class DestinationModel
{
	public string Name { get; set; }
}

```
calling code:

```
var source = new SourceModel{fName = "value"}
var dest = Mapper.Map<DestinationModel>(souce);

```
returns;

```
{
  "Name": null,
}
```

I don't know if is it an issue or I have problem with my config?
Any Help?
Thank you

**Comment by lbargaoanu** [comment]
AssertConfigurationIsValid reports errors. Call RecognizePrefixes on your profile.

**Comment by bitcruiser** [comment]
Thank you.
Now it working with: Call RecognizePrefixes on your profile

**Comment by lbargaoanu** [comment]
This can be closed.
