### ISSUE TITLE
AddGlobalIgnore is not applied

### ISSUE THREAD

**Issue by dorhost** [AutoMapper/AutoMapper#1712]
Hi ,

After migration to new version 5.1.1 my unit test (my maps validations) are failed.
The test :

```
var mapperConfig = new MapperConfigurationExpression();
                mapperConfig.AddGlobalIgnore("CreatedBy");
                mapperConfig.AddGlobalIgnore("CreatedDate");
                mapperConfig.AddGlobalIgnore("ModifiedBy");
                mapperConfig.AddGlobalIgnore("ModifiedDate");

                mapperConfig.AddProfiles(assembly);

                Mapper.Initialize(mapperConfig);

                Mapper.AssertConfigurationIsValid();
```

The AddGlobalIgnore is not applied. I tried with one Map like this:

`mapperConfig.CreateMap<MyMapProfile>();`

then it works, but when i use the AddProfiles then the AddGlobalIgnore will not be applied.

**Comment by lbargaoanu** [comment]
Try calling AddGlobalIgnore in your profiles.

**Comment by dorhost** [comment]
@lbargaoanu 

I have about 140 Profiles, then i have to call AddGlobalIgnore to all of the Profiles. I think it's not a clean way.

why it's not working anymore like before by initializing the mapper ? Is it a bug or there is something wrong in my code?

**Comment by lbargaoanu** [comment]
This is a known issue for some time. Find some way to set it, maybe a base class or reflection.

**Comment by jbogard** [comment]
It is a known issue? Do we have another open for this?

**Comment by TylerCarlson1** [comment]
@jbogard I guess some people knew about it for some time.  Guess no one brought it up.  More than likely this was a relic left over from the upgrade from a single static instance to IMapper.  Global no longer had the same meaning, as it's part of a Profile object, and no one had an issue with it until now.  Would need to become part of IMapperConfigurationExpression to give it same meaning again.

**Comment by lbargaoanu** [comment]
It's the same thing about global vs profile configuration. See #1629.

**Comment by dorhost** [comment]
**Instead of using this:**

`config.AddProfiles(assemblies);`

**I did this and it works**

`foreach (var assembly in assemblies)
            {
                var profiles = Assembly.Load(assembly).GetTypes().Where(x => typeof(Profile).IsAssignableFrom(x));
                foreach (var profile in profiles)
                {
                    var profileMap = Activator.CreateInstance(profile) as Profile;
                    if (profileMap != null)
                    {
                        profileMap.AddGlobalIgnore("CreatedBy");
                        profileMap.AddGlobalIgnore("CreatedBy");
                        profileMap.AddGlobalIgnore("CreatedDate");
                        profileMap.AddGlobalIgnore("ModifiedBy");
                        profileMap.AddGlobalIgnore("ModifiedDate");

                        config.AddProfile(profileMap);
                    }
                }
            }

            Mapper.Initialize(config);`

But i think it make sence to be able to Ignore some maps globaly by initializing.

**Comment by jbogard** [comment]
This is a bug, from my view. We have type map and property map actions for all maps, global ignores would make sense to apply globally, too. Principle of least surprise here.

I also think any configuration that affects matching members, if applied at the global profile, should apply globally.

**Comment by lbargaoanu** [comment]
I agree it's a bug, but the merging idea you had, between profiles and global, that seems messy to me.

**Comment by TylerCarlson1** [comment]
I think if it says global it should apply globally.  If it can be called in a profile it's just be applicable for that profile.

It gets too confusing having the configuration act as both a profile and a global settings for other profiles at the same time.  That's why I like the idea of treating config as a profile only and the profile functions only apply to itself.  Now the global ignore needs to change cause that's misleading, but if you want global ignore that should only be in IMapperConfiugrationExpression interface and not IProfileExpression interface.

Maybe you need to do `cfg.Default.CreateMap<Foo,Bar>` instead of `cfg.CreateMap<Foo,Bar>` and then it will be Much clearer what does what instead of melding 2 different configuration interfaces together.

**Comment by jbogard** [comment]
The way I saw profiles was a way to create maps, as well as a scope to apply mapping rules. The root profile is the "global" mapping rules, and profiles are for specific stuff.

We already do this today with property map actions/type map actions.

I'll spike out a PR and get some input.

**Comment by TylerCarlson1** [comment]
@jbogard If the root profile is the global mapping rules, does that mean conventions should apply to all sub profiles, along with things like global ignore?

**Comment by jbogard** [comment]
Yep. That was my idea. Basically all the members on IProfileConfiguration besides the methods, I'd have a way to combine those with the underlying config.

**Comment by TylerCarlson1** [comment]
If you do that I worry about race conditions or else you are going to have to have to global config be implemented last as far as configs go.  I'm thinking all actions that used to work on the default profile, except create map, will now have to be an action that you need to run to all profiles after initialize function is complete.  They will then apply to all sub profiles.  Maybe order might not matter that much for things like conventions and ignores.

**Comment by jbogard** [comment]
I think what I'll probably have to do is what I did with TypeMaps - make them super dumb, and build up intelligence around setting them up properly. Right now Profile is a bit too smart - especially around the CreateTypeDetails method.
