### ISSUE TITLE
Assert.AreEqual failed für System.Byte[]

### ISSUE THREAD

**Issue by HawkMG** [AutoMapper/AutoMapper#1713]
Hi,

I have updated from Version 4.2.0 to 5.1.1 and now my UnitTests failed für System.Byte[] types!

For example:

I have a POCO and a DTO:

```
public class POCO
{
    public byte[] Data { get; set; }
}

public class DTO
{
      public byte[] Key { get; set; }
}
```

And a profile:

```
public class POCOToDTOProfile : Profile
    {       
        public POCOToDTOProfile()
        {
            this.CreateMap<POCO, DTO>()
                .ForMember(destination => destination.Key, mapping => mapping.MapFrom(source => source.Data));
        }
    }
```

And the Textclass:

```
[TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Mapper.Initialize(config => config.AddProfile<POCOToDTOProfile>());

            var pocoData = new POCO
            {
                Data = Encoding.Default.GetBytes("E161FF81-8C22-4BAD-AFC9-9EDCA9160487")
            };

            var mappedPoco = Mapper.Map<POCO, DTO>(pocoData);

            Assert.AreEqual(pocoData.Data, mappedPoco.Key);
        }
    }

```

In Automapper 4.2.0 this Assert is ok, but in 5.1.1 not!!!

Best regards

**Comment by lbargaoanu** [comment]
Collections are mapped by content, so everything is copied in a new collection. @jbogard wanted the primitive arrays to behave the same way, hence this change.

**Comment by lbargaoanu** [comment]
Funny enough, the normal ArrayMapper doesn't behave this way, so a workaround is to exclude the PrimitiveArrayMapper:

	var c = new MapperConfiguration(config => config.AddProfile<POCOToDTOProfile>(), MapperRegistry.Mappers.Where(m=>!(m is PrimitiveArrayMapper)));

But I guess this is fragile stuff.

**Comment by jbogard** [comment]
I'm curious, what does Assert.AreEqual do for primitive byte arrays? Does
it actually loop through the contents?

**Comment by lbargaoanu** [comment]
@jbogard No.

**Comment by jbogard** [comment]
Ah, then the original test is wrong. I don't just copy the array reference, because arrays are reference types and the contents are mutable.

**Comment by HawkMG** [comment]
So, what is the best practice now! Take a loop and Assert all single bytes?

**Comment by lbargaoanu** [comment]
Try SequenceEqual.

**Comment by HawkMG** [comment]
Hi,
thx! I´m now using CollectionAssert.AreEqual!
