### ISSUE TITLE
Mapping from nullable enum stopped working in AutoMapper 5

### ISSUE THREAD

**Issue by Winkiel** [AutoMapper/AutoMapper#1717]
Mapping from nullable enum doesn't work anymore for general enum mapping (using Enum class).
Worked fine in 4.2.1.

`static void Main(string[] args)`
`{`
`    Mapper.Initialize(cfg =>`
`        {`
`            cfg.CreateMap<TestClass, TestResult>();`
`            cfg.CreateMap<Enum, string>().ConvertUsing((Enum src) => "Test mapping");`
`        });`
``
`    var result = Mapper.Instance.Map<TestResult>(new TestClass { Color = ConsoleColor.Black });`
``
`    Debug.Assert(result.Color == "Test mapping", result.Color);`
`}`
``
`public class TestClass`
`{`
`    public ConsoleColor? Color { get; set; }`
`}`
``
`public class TestResult`
`{`
`    public string Color { get; set; }`
`}`

**Comment by lbargaoanu** [comment]
Why not use the exact type you're mapping?

**Comment by Winkiel** [comment]
I'd rather use generic mapping for Enum to string rather than 40 mapping for every specific enum type doing the same (and remembering to add another one for every new enum because AutoMapper will not tell me that this kind of mapping is missing)...

**Comment by lbargaoanu** [comment]
So you're smth custom depending on the enum type? Because AM will map to string by default.
