### ISSUE TITLE
Pass in runtime arguments for mapping operations

### ISSUE THREAD

**Issue by marcels2204** [AutoMapper/AutoMapper#1720]
Before v5 i passed in some arguments for mapping.
`Action<IMappingOperationOptions> options = (context) =>
            {
                context.Items["positionen"] = command.Positionen;
            };

```
        Vorgang rechnung = _mapper.Map<Vorgang>(lieferung, options);
```

``.ForMember(p` => p.Positionen, o => o.ResolveUsing((source,resolutionContext) =>
                {
                    if (!resolutionContext.Options.Items.ContainsKey("positionen"))
                    {
                        resolutionContext.Options.Items["positionen"] = new Dictionary<int, decimal>();
                    }

```
                Dictionary<int, decimal> positions = (Dictionary<int, decimal>)resolutionContext.Options.Items["positionen"];

                if (positions.Any())
                {
                    var filteredPositions = source.Positionen.Where(p => positions.Keys.Contains(p.Id));

                    foreach (var p in filteredPositions)
                    {
                        p.Menge = positions[p.Id];
                    }

                    //return filteredPositions;
                    return new ChangeTrackingCollection<Vorgangsposition>(filteredPositions);
                }`
```

How to achieve this with v5?

**Comment by jbogard** [comment]
See the V5 upgrade guide on the wiki, the syntax is slightly changed, but it's still there.
