### ISSUE TITLE
System.Data.Entity.Core.EntityCommandExecutionException

### ISSUE THREAD

**Issue by dorhost** [AutoMapper/AutoMapper#1721]
It's strage but i am now pretty sure that after updating the Automapper i get the following exception. it's not happen by all pages, but for example the following line in my ApplicationService layer:

`UnitOfWork.Repository<Book>().Query().Get().ToList();`

**An exception of type 'System.Data.Entity.Core.EntityCommandExecutionException' occurred in EntityFramework.SqlServer.dll but was not handled in user code**

InnerException:
**There is already an open DataReader associated with this Command which must be closed first.**

I have investigated several hours and i tried different solutions to find out the issue, but no success.

Is there any relation between this issue and automapper update? Because i receive this exception exactly after upgrading the automapper to latest version.

Here is my profiles registration with AutoFac:

```
using Autofac;
using AutoMapper;

public class AutoMapperDiModule : Module
    {
        private readonly string[] _assemblies;

        public AutoMapperDiModule(string[] assemblies)
        {
            _assemblies = assemblies;
        }

        protected override void Load(ContainerBuilder builder)
        {
            AutomapperConfiguration config = new AutomapperConfiguration();
            var mapper = config.GetMapper(_assemblies);

            builder.RegisterInstance(mapper).As<IMapper>();
        }
    }

```

do you have any idea? 

I found a solution to ignore the issue somehow by adding the following to the connection string in web.config but it think it's not a good solution.

`MultipleActiveResultSets=True`

Regards

**Comment by jbogard** [comment]
No idea, I need some additional information, stack trace, configuration, something.
