### ISSUE TITLE
Issue after upgrading to 5.1.1 - Mapping object that contains list is appending instead of merging

### ISSUE THREAD

**Issue by joshuasanderson** [AutoMapper/AutoMapper#1722]
So we have a domain model object that contains a list of another domain model object. Both of these domain models map to data models in our database. 

Domain models:

```
CRModel { id, name, list<CRModelSummary> summaries }
CRModelSummary { crId, pId }
```

Data models:

```
CR { id, name, list<CRSummary> summaries }
CRSummary { crId, pId }
```

Everything below worked fine in version 5.0.2. After upgrading to 5.1.1 we noticed that: 

After loading up our CR domain model that contained a list of 1 CRModelSummary, made some updates to other properties that we needed to, then we were ready to update our database. So we made another variable, but this time a fresh copy of our database model. So we have:

```
var crDomainModel
var dbCRModel
```

Each of these has a list of 1 summary and we made no updates to those lists. We just made some updates to the primitive types in the domain model that we wanted merged into the data model.

After we ran this line of code:

`dbCRModel= _mapper.Map<CRModel, CR>( crDomainModel, dbCRModel );`

We had our primitive properties merged okay, but instead of only 1 summary being in the list, there were 2; and they were the same. So when we went to save changes to our db, we got a duplicate key error. 

In 5.0.2, we had no issues with this and when that line of code ran, dbCRModel correctly only had 1 summary in the list.

I attached a simple console app that you can run to see. It is shipped with version 5.1.1 in there. You can revert back to 5.0.2 and see that variable `dbCr`has only 1 summary in the list.
[AutoMapperTest.zip](https://github.com/AutoMapper/AutoMapper/files/516550/AutoMapperTest.zip)

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by joshuasanderson** [comment]
Version 5.2.0-alpha-01223 did work. Do you have any idea when this will be released in the main build?

Thank you!

**Comment by lbargaoanu** [comment]
This can be closed.
