### ISSUE TITLE
Mapping dynamic proxy property to a property with a different name doesn't work as expected

### ISSUE THREAD

**Issue by taylorgibb** [AutoMapper/AutoMapper#1725]
So i think its easiest if i show an example. 

```
class Company
  property string Name

class Invoice
  property class Company

class InvoiceViewModel
  property string CompanyName
```

Mapping is as follows

```
CreateMap<Invoice, InvoiceViewModel>()
             .ForMember( source => source.Company, dest => dest.MapFrom( x => x.Company.Name ) );
```

When you run this, the result is an `InvoiceViewModel` object with its `CompanyName` property set to `DynamicProxy3dg....`

If however, i change the property name from `CompanyName` to `Name` on the `InvoiceViewModel` the mapping works 100%

**Comment by lbargaoanu** [comment]
This should work without the MapFrom, by convention.

**Comment by lbargaoanu** [comment]
This can be closed.
