### ISSUE TITLE
Is automapper supported  Tuple?

### ISSUE THREAD

**Issue by gsh434541340** [AutoMapper/AutoMapper#1726]
Exception:
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.Mapping types:Tuple`2 -> Tuple`2System.Tuple`2[[Taolx.Common.Soa.Model.SoaShoppingServiceModel.Range, Taolx.Common.Soa.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Taolx.Common.Soa.Model.SoaShoppingServiceModel.Range, Taolx.Common.Soa.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Tuple`2[[Taolx.Soa.Wireless.Contract.Shopping.H5RangeSoaModel, Taolx.Soa.Wireless.Contract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Taolx.Soa.Wireless.Contract.Shopping.H5RangeSoaModel, Taolx.Soa.Wireless.Contract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]Destination path:H5GetProductRangeResponse.RangePairs.RangePairs.RangePairs0[0]Source value:(Taolx.Common.Soa.Model.SoaShoppingServiceModel.Range, Taolx.Common.Soa.Model.SoaShoppingServiceModel.Range) 在 AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) 在 AutoMapper.Mappers.EnumerableMapperBase`1.Map(ResolutionContext context, IMappingEngineRunner mapper) 在 AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) 在 AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap) 在 AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper) 在 AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) 在 AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source) 在 Taolx.Soa.Wireless.Business.Shopping.ProductRangeBll.Get(TaolxApiRequest`1 request) 在 Taolx.Soa.Wireless.Service.Controllers.ShoppingController.GetProductRange(TaolxApiRequest`1 request) 在 lambda_method(Closure , Object , Object[] ) 在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters) 在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)--- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()--- 引发异常的上一位置中堆栈跟踪的末尾 --- 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

**Comment by lbargaoanu** [comment]
AM doesn't handle Tuple in any way, you have to use it as any other class.

**Comment by gsh434541340** [comment]
But when I used the DynamicMap, It's no exception.

**Comment by lbargaoanu** [comment]
DynamicMap will get you into trouble. Just create the maps you need.

**Comment by gsh434541340** [comment]
Thanks!
