### ISSUE TITLE
Automapper v5.1.1 does not work with ObservableDictionary where Automapper 4 does

### ISSUE THREAD

**Issue by jogibear9988** [AutoMapper/AutoMapper#1727]
I've a DTO with the following Property:

    [DataContract(Name = "A")]
    public class TagDTO : BasicDTO
    {
       [DataMember(Name = "w")]
        public virtual ObservableDictionary<string, string> ReferencedTags { get; set; }
    }

When I trys to use Automapper to create a Map:

var config = new MapperConfiguration(cfg => cfg.CreateMap<TagDTO, TagDTO>());

then I got the following Exception:

"Ein Ausdruck vom Typ "System.Object" kann nicht für eine Zuweisung vom Typ "System.Collections.Generic.KeyValuePair`2[System.String,System.String]" verwendet werden."

In Line 37 of ExpressionExtension
Code:

           var loop = Block(new[] { enumeratorVar },
                enumeratorAssign,
                Loop(
                    IfThenElse(
                        Equal(moveNextCall, Constant(true)),
                        Block(new[] { loopVar },
                            Assign(loopVar, Property(enumeratorVar, "Current")),
                            loopContent
                        ),
                        Break(breakLabel)
                    ),
                breakLabel)
            );

**Comment by lbargaoanu** [comment]
You should try again when #1711 is merged.

**Comment by jogibear9988** [comment]
Pull Rq. #1711 does not solve my Issue! I still get the same error with this patched Version.

**Comment by lbargaoanu** [comment]
Then we need to see the code for the ObservableDictionary.

**Comment by jogibear9988** [comment]
If you change ExpressionExtension to  

               Assign(loopVar, Convert(Property(enumeratorVar, "Current"), loopVar.Type)),

it works

**Comment by jogibear9988** [comment]
Code is from Dr.WPF see: http://drwpf.com/blog/2007/09/16/can-i-bind-my-itemscontrol-to-a-dictionary/

**Comment by lbargaoanu** [comment]
I think that dictionary should be fixed. The public GetEnumerator should be specific and the explicitly implemented one object based. Then it would work as with the BCL dictionaries.

**Comment by jogibear9988** [comment]
Okay, I will fix, but I think we still can change this line:

     Assign(loopVar, Convert(Property(enumeratorVar, "Current"), loopVar.Type)),

We can look if the loopVar Type is Equal to the Enumerated one, when not, cast

**Comment by lbargaoanu** [comment]
No casting is necessary if people play by the rules. And adding it in might introduce inefficiencies for the normal case. You can always choose a different compile time type and guide AM to the right interface. As you would in a foreach by specifying the type for the loop variable.

**Comment by jogibear9988** [comment]
You are right, but the code worked with automapper v4, and it would be nice if it also works in v5

**Comment by jbogard** [comment]
AutoMapper 4 and earlier evaluated every type at runtime. It was horribly
innefficient. I covered as many cases as I could but ultimately it passed
all the tests and ran on all of our current dozen or so projects that use
it. That's about all I can do.

**Comment by jogibear9988** [comment]
what do you mean about my fix? we can additionaly only cast if the types are not assignable?
