### ISSUE TITLE
Automapper 5.1.1 ForAllMembers Ignore If null

### ISSUE THREAD

**Issue by MattHartz** [AutoMapper/AutoMapper#1728]
Hi, my team recently migrated from 4.2.1 to 5.1.1 and we noticed we had to move from IfSourceValueNull() for our ForAllMembers call in our update map from one dto object to another to 

`ForAllMembers(m => m.Condition((source, target, sourceValue, targetValue) => sourceValue != null))`

Now according to many issues I've seen posted, this change should solve the issue. But, it appears that through nuget, this only works for 5.0.2.  I wanted to contribute to Automapper and see if i could fix the issue, but after forking the code and writing a few unit tests, it appears that this issue has been resolved.

Here is a sample test I wrote that appears to work as designed.
`var destination = new Destination()
            {
                ValueOne = "Change",
                ValueTwo = "Remainthesame"
            };

            var source = new Source()
            {
                ValueOne = "newval"
            };

            Mapper.Map(source, destination);

            destination.ValueOne.ShouldEqual("newval");
            destination.ValueTwo.ShouldEqual("Remainthesame");`

Is there an update coming to nuget that includes these potential changes (if they don't already exist and something else is going on. :P).

**Comment by lbargaoanu** [comment]
Yes, it was fixed. You found out the hard way :) Other than checking existing issues, you can try the MyGet build. For future reference :)

**Comment by lbargaoanu** [comment]
This can be closed.
