### ISSUE TITLE
Upgrade to AutoMapper 5.1.1 and AutoMapper.Collection 2.1.0 issue

### ISSUE THREAD

**Issue by dmdymov** [AutoMapper/AutoMapper#1729]
I'm trying to upgrade my project from AutoMapper 4.1.1 / AutoMapper.Collection 1.1.2 to AutoMapper 5.1.1 / AutoMapper.Collection 2.1.0. I have a scenario which works fine with old dlls but I get an unexpected null as a result of mapping with new dlls.

[Gist with issue code.](https://gist.github.com/dmdymov/d94a094be72c86fc64b1ceb91ac65673)

At first I tried to create an AutoMapper.Collection issue, but as @TylerCarlson1 states [here](https://github.com/TylerCarlson1/Automapper.Collection/issues/18#issuecomment-252940157), this is an AutoMapper bug, 'cause AutoMapper doesn't use AutoMapper.Collection in the second case. Is he right?

**Comment by lbargaoanu** [comment]
Make a test that only depends on AM and I'll look into it.

**Comment by dmdymov** [comment]
It can't be done, 'cause there's no odd behavior without using CollectionProfile from AutoMapper.Collection, AM does mapping as it is expected to.

`Mapper.Map<List<ThingDto>, List<Thing>>(dtos, items)`
`Mapper.Map<List<Thing>>(dtos)`

But the author of AutoMapper.Collection says that in the second case (I get null result there) AM shouldn't use CollectionProfile at all, this should be regular mapping as if there's no CollectionProfile. What I am asking here is "Is he right and this is an AM issue? Is he wrong and this is an AM.Collection issue?"

**Comment by lbargaoanu** [comment]
Then I guess @TylerCarlson1 should help you here.
