### ISSUE TITLE
Mapping from nested value type fails if parent is null

### ISSUE THREAD

**Issue by Winkiel** [AutoMapper/AutoMapper#1730]
I get an exception when mapping from ValueType when its nested in object that is null.
It happens when there are at least two levels of null.

Unhandled Exception: AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
TestClass -> TestResult
ConsoleApplication.Program+TestClass -> ConsoleApplication.Program+TestResult

Type Map configuration:
TestClass -> TestResult
ConsoleApplication.Program+TestClass -> ConsoleApplication.Program+TestResult

Property:
Color ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , Object , Object , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at ConsoleApplication1.Program.Main(String[] args)

<pre>static void Main(string[] args)
{
    Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<TestClass, TestResult>()
                .ForMember(dst => dst.Color, opt => opt.MapFrom(src => src.Element.Element.Color));
        });

    Mapper.Instance.Map<TestResult>(new TestClass());
}

public class TestClass
{
    public TestClassInner Element { get; set; }

    public class TestClassInner
    {
        public TestClassMoreInner Element { get; set; }

        public class TestClassMoreInner
        {
            public ConsoleColor Color { get; set; }
        }
    }
}

public class TestResult
{
    public string Color { get; set; }
}</pre>

**Comment by lbargaoanu** [comment]
Try the latest from NuGet or the MyGet build,

**Comment by Winkiel** [comment]
It started to occur after update to version 5 of AutoMapper (tested on 5.1.1 - that's latest NuGet version)

Was working fine - without exception - for AutoMapper 4.2.1.

**Comment by lbargaoanu** [comment]
Then it's on MyGet.

**Comment by Winkiel** [comment]
Works like a charm for 5.2.0-alpha-01223 :+1: 
Looking forward to have it on NuGet :-)

**Comment by lbargaoanu** [comment]
This can be closed.
