### ISSUE TITLE
InvalidCastException Expression<Func<TDto, IEnumerable<C>>> to Expression<Func<TEntity, IEnumerable<C>>>

### ISSUE THREAD

**Issue by zhujinhu21** [AutoMapper/AutoMapper#1733]
use automapper 4.1.1.

```
public async virtual Task Pull<C>(string id, Expression<Func<TDto, IEnumerable<C>>> field, Expression<Func<C, bool>> expression)
        {

            Mapper.CreateMap<Expression<Func<TDto, IEnumerable<C>>>, Expression<Func<TEntity, IEnumerable<C>>>>();


            Mapper.CreateMap<Expression<Func<TEntity, IEnumerable<C>>>, Expression<Func<TDto, IEnumerable<C>>>>();

            var entityExpress = Mapper.Map<Expression<Func<TEntity, IEnumerable<C>>>>(field);//error InvalidCastException System.Linq.Expressions.Expression`1[System.Func`2[meixiaohu.Entities.MongoDB.Order,System.Collections.Generic.List`1[meixiaohu.Entities.MongoDB.ChildOrder]]]” to “System.Linq.Expressions.Expression`1[System.Func`2[meixiaohu.Entities.MongoDB.Order,System.Collections.Generic.IEnumerable`1[meixiaohu.Services.Dtos.ChildOrderDto]]]”。

            await Repository.Pull(id, entityExpress, expression);
        }
```

how to transfer Expression<Func<TDto, IEnumerable<C>> to Expression<Func<TEntity,IEnumerable<C>>

**Comment by jbogard** [comment]
AutoMapper 5.x supports mapping expressions without any configuration. My suggestion - upgrade.

**Comment by zhujinhu21** [comment]
automapper 5.x does not support on .net framework4.5.1, i can't install it in vs2013

**Comment by lbargaoanu** [comment]
Try upgrading Nuget.

**Comment by zhujinhu21** [comment]
upgrade to automapper5.1.1.
 public async virtual Task PushT(string id, Expression<Func<TDto, object>> field, object value)
        {
            var entityExpress = Mapper.Map<Expression<Func<TEntity, object>>>(field);

        }
var entityExpress = Mapper.Map<Expression<Func<TEntity, object>>>(field);
still throw exception .
i am already config CreateMap<Expression<Func<ChildOrderDto, object>>, Expression<Func<ChildOrder, object>>>() in Global.asax.
Error mapping types.

Mapping types:
Expression`1 -> Expression`1
System.Linq.Expressions.Expression`1[[System.Func`2[[meixiaohu.Services.Dtos.OrderDto, meixiaohu.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[meixiaohu.Entities.MongoDB.Order, meixiaohu.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

**Comment by zhujinhu21** [comment]
upgrade to automapper5.1.1.
 public async virtual Task PushT(string id, Expression<Func<TDto, IEnumerable<object>>> field, object value)
{

      var entityExpress = Mapper.Map<Expression<Func<TEntity, IEnumerable<object>>>>(field);
      
      await Repository._Push(id, entityExpress, value);
}

entityExpress parameter Member ={System.Collections.Generic.List`1[meixiaohu.Services.Dtos.ChildOrderDto] ChildOrder} not Tentity
