### ISSUE TITLE
5.1.1 performance differences when compared to 3.3.1

### ISSUE THREAD

**Issue by bryancrosby** [AutoMapper/AutoMapper#1737]
Recently exploring upgrading from AutoMapper 3.3.1 to AutoMapper 5.1.1 and noticed the following when performing some benchmarking.

I don't think `ConcurrentDictionary` is the bottleneck on it's own because when running the benchmark without AutoMapper, it performs very fast. Benchmarked using BenchmarkDotNet

This is my first time poking around with AutoMapper internals, so I'm just bringing this up in case anyone might have some quick insight.
## AutoMapper 3.3.1

``` ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6820HQ CPU 2.70GHz, ProcessorCount=8
Frequency=2648438 ticks, Resolution=377.5810 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0

Type=CachedMapBenchmark  Mode=Throughput  

```

| Method | Median | StdDev |
| --- | --- | --- |
| GetCountryForTranslationCached | 3.2514 us | 0.0539 us |
| GetCountryForTranslation | 8.0801 us | 0.2278 us |
## AutoMapper 3.3.1 Cached Benchmark Class

I didn't want to throw too much code here but the non cached version is the exact same, except that it calls `GetCountryForTranslation`

``` c#
public class CachedMapBenchmark
{
    private SampleSource sampleSource;

    [Setup]
    public void Setup()
    {
        sampleSource = new SampleSource()
        {
            Id = 2482,
            InterestingValue = "This job requires extra pluck and zeal from every young wage earner",
            Date = DateTime.Now,
            TranslatedValue = CountryEnum.UnitedStates
        };
        Mapper.CreateMap<SampleSource, SampleDestination>()
            .ForMember(dest => dest.TranslatedValue, opt => opt.MapFrom(src => src.TranslatedValue.GetCountryForTranslationCached()));
    }

    [Benchmark]
    public SampleDestination GetCountryForTranslationCached()
    {
        return Mapper.Map<SampleSource, SampleDestination>(sampleSource);
    }
}
```
## AutoMapper 5.1.1

``` ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6820HQ CPU 2.70GHz, ProcessorCount=8
Frequency=2648438 ticks, Resolution=377.5810 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0

Type=CachedMapBenchmark  Mode=Throughput  

```

| Method | Median | StdDev |
| --- | --- | --- |
| GetCountryForTranslationCached | 333.3515 ns | 10.4293 ns |
| GetCountryForTranslation | 3.6679 us | 0.1317 us |
## AutoMapper 5.1.1 Cached Benchmark Class

Again, I didn't want to throw too much code here but the non cached version is the exact same, except that it calls `GetCountryForTranslation`

``` c#
public class CachedMapBenchmark
{
    private SampleSource sampleSource;
    private IMapper mapper;

    [Setup]
    public void Setup()
    {
        sampleSource = new SampleSource()
        {
            Id = 2482,
            InterestingValue = "This job requires extra pluck and zeal from every young wage earner",
            Date = DateTime.Now,
            TranslatedValue = CountryEnum.UnitedStates
        };
        mapper = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<SampleSource, SampleDestination>()
                .ForMember(dest => dest.TranslatedValue, opt => opt.MapFrom(src => src.TranslatedValue.GetCountryForTranslationCached()));
        }).CreateMapper();
    }

    [Benchmark]
    public SampleDestination GetCountryForTranslationCached()
    {
        return mapper.Map<SampleSource, SampleDestination>(sampleSource);
    }
}
```
## No AutoMapper

``` ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6820HQ CPU 2.70GHz, ProcessorCount=8
Frequency=2648438 ticks, Resolution=377.5810 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1586.0

Type=NoAutoMapperBenchmark  Mode=Throughput  

```

| Method | Median | StdDev |
| --- | --- | --- |
| GetCountryForTranslation | 2,902.2193 ns | 79.4800 ns |
| GetCountryForTranslationCached | 54.4257 ns | 1.9376 ns |

Relevant Code in question

``` c#
public static class Extensions
{
    private static readonly ConcurrentDictionary<Enum, string> translationCache = new ConcurrentDictionary<Enum, string>();

    public static string GetCountryForTranslation(this Enum @enum)
    {
        var fi = @enum.GetType().GetField(@enum.ToString());
        var attributes = (TranslationAttribute[])fi.GetCustomAttributes(typeof(TranslationAttribute), false);
        if (attributes.Length == 0)
        {
            throw new ArgumentException($"TranslationAttribute was not present on enumeration type {@enum.GetType().FullName}, value {@enum}");
        }
        return attributes[0].Value;
    }

    public static string GetCountryForTranslationCached(this Enum @enum)
    {
        return translationCache.GetOrAdd(@enum, trans =>
        {
            var fi = @enum.GetType().GetField(@enum.ToString());
            var attributes = (TranslationAttribute[]) fi.GetCustomAttributes(typeof(TranslationAttribute), false);
            if (attributes.Length == 0)
            {
                throw new ArgumentException($"TranslationAttribute was not present on enumeration type {@enum.GetType().FullName}, value {@enum}");
            }
            return attributes[0].Value;
        });
    }
}

public enum CountryEnum
{
    [Translation("ESP")]
    Spain,

    [Translation("USA")]
    UnitedStates,

    [Translation("JPN")]
    Japan,

    [Translation("DEU")]
    Germany
}

public class TranslationAttribute : Attribute
{
    public string Value { get; set; }

    public TranslationAttribute(string value)
    {
        Value = value;
    }
}

public class SampleDestination
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public string InterestingValue { get; set; }

    public string TranslatedValue { get; set; }
}

public class SampleSource
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public string InterestingValue { get; set; }

    public CountryEnum TranslatedValue { get; set; }
}
```

**Comment by TylerCarlson1** [comment]
I don't know much about benchmark code, but the example they provide shows putting setup in the constructor not a function with SetupAttribute in it. Maybe it's calling setup all the time and AM creates a new map every time.

Also if you look at https://github.com/AutoMapper/AutoMapper/wiki/Conventions#expand-ability you can make member conventions in which you can say if it's enum to string and the enums have translation attributes, then to call this extention method when mapping.

@jbogard This gives me an idea.  Would it make sense to make a convention where you use Enum attributes as an extension of flattening?  Like you continue to look into the enum's attributes names and properties of the attribute to flatten the map down to that level?

**Comment by bryancrosby** [comment]
> I don't know much about benchmark code, but the example they provide shows putting setup in the constructor not a function with SetupAttribute in it. Maybe it's calling setup all the time and AM creates a new map every time.

I forgot to mention I have tried both -- they yield virtually identical results.

**Comment by TylerCarlson1** [comment]
Ok I got the ns vs us messed up.  I was thinking 5.1.1 was slower than 3.1.1 in your case.

Yea that's seems about on par with what we got on bench-marks for 5.x.
5.x has MASSIVE improvements in speed from 4.x and previous versions, but it can't be as fast as native code.  That was the biggest change for 5 was to optimize is as much as possible.

**Comment by bryancrosby** [comment]
> 5.x has MASSIVE improvements in speed from 4.x and previous versions, but it can't be as fast as native code. That was the biggest change for 5 was to optimize is as much as possible.

Any reason why it would be roughly 100x slower from 3.3.1 in this case? Was 3.3.1 doing something different in the way that mapping were handled? Sorry, didn't poke around the source at that time in the project's history.

**Comment by TylerCarlson1** [comment]
It went from running every mapper function with setting properties in slow reflection based code.  Now what it does is compile an expression, so it's like native code running the map.

[Jimmy](https://lostechies.com/jimmybogard/2016/06/24/automapper-5-0-speed-increases/
) explains the numbers better.

**Comment by jbogard** [comment]
Why what is slower? Sorry I'm kinda lost in the benchmark numbers here.

**Comment by TylerCarlson1** [comment]
@jbogard It's **not** slower it's faster.  Yes the numbers and the wording of everything in general confused me too.

@bryancrosby was asking why there was such a big difference in speed not that it was actually slower in 5.11 than it was in 3.1.1.

This should probably be closed

**Comment by bryancrosby** [comment]
@jbogard @TylerCarlson1  Sorry for the flood of text. 3.3.1 seems to be **faster** for the method `GetCountryForTranslationCached` -- in 3.3.1, it performs at 3.25µs but in 5.1.1 it's  ~100x slower 333.33µs -- with the only difference being AutoMapper itself

**Comment by lbargaoanu** [comment]
@bryancrosby I think @TylerCarlson1 had it right. You're mixing measurement units. I my tests 5.5.1 is 10 times faster. And that makes sense.

**Comment by bryancrosby** [comment]
@jbogard my eyes must be having trouble these days between the letter u and n ;)
