### ISSUE TITLE
Automapper - Assign Ranking in the Destination object

### ISSUE THREAD

**Issue by lolekjohn** [AutoMapper/AutoMapper#1738]
Hi,

I am having the below source and destination objects:

```
   public class Source
    {       
        public string Value1{ get; set; }

    }

    public class Destination 
    {
        public string Value1{ get; set; }
        public int Ranking { get; set; }
    }

```

I am trying to map the collection object of Source to Collection object of destination. My source collection is like this:

```
    var source = new List<Source>();
    source.Add(new Source(){ Value1= "test1" });
    source.Add(new Source(){ Value1= "test2" });
```

How can i write the mapper if the Ranking attribute in the destination object should correspond to the item index in the source collection. i.e. after mapping the destination ranking for the Source with Value1 = "test1" will be 1 and the next one will be 2.

**Comment by lbargaoanu** [comment]
There is nothing in AM to help you with that.
