### ISSUE TITLE
Issue With Mapping Dynamic Nested Elements

### ISSUE THREAD

**Issue by pournejati** [AutoMapper/AutoMapper#1739]
I've created an EF query similar to the following sample using expressions:

```
Expression<Func<MyModel, dynamic>> columns = x => new
{
        x.EncounterId,
        x.PatientId,
        x.Date,
        x.Time,
        Patient = x.PatientEntity
}
```

**PatientEntity** is an entity framework entity class with the following implementation:

```
public partial class PatientEntity
{
        public int PatientId { get; set; }        
        public string FullName { get; set; }
}
```

I have a DTO class similar to the **PatientEntity** class with the following implementation:

```
public class PatientModel
{
        public int PatientId { get; set; }        
        public string FullName { get; set; }
}
```

I also have a container class with the following implementation:

```
public class DashboardModel
{
        public int EncounterId { get; set; }
        public int PatientId { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan Time { get; set; }
        public PatientModel Patient { get; set; }
        public decimal RemainingBalance { get; set; }
}
```

I used to map these two using the following code. But I updated AutoMapper from 5.0.2 to 5.1.1 and the following code doesn't map the **Patient** property anymore (It returns null).

```
var dataModel = await Service.GetListAsync(columns);
var model = Mapper.Map<List<DashboardModel>>(dataModel);
```

I guess something changes in the configuration of mapper that prevents the mapper to map nested properties of a property. Anyway, how would I resolve this? 
**Thanks.**

**Comment by pournejati** [comment]
I've created a simple code to demonstrate what's happening.

```
dynamic dynamicObject = new
{
	Code = 5,
	FullName = "John",
	Patient = new Test
	{
		Id = 10,
		Name = "Roberts"
	}
};

var dynamicList = new List<dynamic> {dynamicObject, dynamicObject};

Mapper.Initialize(x =>
{
	x.CreateMissingTypeMaps = true;
});

var staticObject = Mapper.Map<List<ParentTestDto>>(dynamicList);
Console.WriteLine(staticObject.First().Code);
```

**Comment by lbargaoanu** [comment]
Remove CreateMissingTypeMaps and try again.

**Comment by lbargaoanu** [comment]
Oh, I see you also use an anonymous type. So you need CreateMissingTypeMaps.

**Comment by lbargaoanu** [comment]
This looks like a bug with CreateMissingTypeMaps. As a workaround, avoid CreateMissingTypeMaps and use ExpandoObject or smth similar instead of an anonymous type. That works.

**Comment by jbogard** [comment]
Why are you using the CreateMissingTypeMaps? It looks like you know the types at compile time.

**Comment by pournejati** [comment]
If I run it without , I get the following error. You can simply run it yourself and see the error.

```
AutoMapper.AutoMapperMappingException was unhandled
  HResult=-2146233088
  Message=Error mapping types.

Mapping types:
List`1 -> List`1
System.Collections.Generic.List`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Collections.Generic.List`1[[Benchmark.ParentTestDto, Benchmark, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Object , Object , ResolutionContext )
       at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\AutoMapper\src\AutoMapper\Mapper.cs:line 214
       at AutoMapper.Mapper.Map[TDestination](Object source) in C:\AutoMapper\src\AutoMapper\Mapper.cs:line 76
       at Benchmark.Program.Main(String[] args) in C:\AutoMapper\src\Benchmark\Program.cs:line 60
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Missing type map configuration or unsupported mapping.

Mapping types:
Object -> ParentTestDto
System.Object -> Benchmark.ParentTestDto
       Source=Anonymously Hosted DynamicMethods Assembly
       StackTrace:
            at lambda_method(Closure , Object , ParentTestDto , ResolutionContext )
            at AutoMapper.ResolutionContext.Map[TSource,TDestination](TSource source, TDestination destination) in C:\AutoMapper\src\AutoMapper\ResolutionContext.cs:line 108
            at lambda_method(Closure , Object , Object , ResolutionContext )
       InnerException: 
```

**Comment by lbargaoanu** [comment]
Yes, of course. I realized you need it and I updated my answer. Read again :)

**Comment by lbargaoanu** [comment]
@jbogard He uses an anonymous type. I missed it too at first.

**Comment by pournejati** [comment]
@lbargaoanu I tried your andwer, but it still not working. I mean replacing my list with the following:
```
var dynamicList = new []{dynamicObject, dynamicObject}.ToList();
```
But about ExpandoObject, yes it works with it, but I can't use it as the framework I'm using designed to return dynamic lists.

**Comment by lbargaoanu** [comment]
That works with the MyGet build. About ExpandoObject, it is a dynamic object, so I don't know what you're saying here :)

**Comment by pournejati** [comment]
Forget about my point on ExpandoObject. About the bug, it only happens when I try to case a list of dynamic elements. If I map one object, with CreateMissingTypeMaps = true, it works just fine. The following code works just fine:

```
var dynamicList = new List<dynamic> { dynamicObject, dynamicObject };
var dataSource = dynamicList.Select(Mapper.Map<ParentTestDto>).ToList();
```

**Comment by lbargaoanu** [comment]
My workaround seems easier, even if I say so myself :) There is also a possible fix in the PR above, so you should be fine.

**Comment by jbogard** [comment]
Dynamic object != anonymous object. I wouldn't think that CreateMissingTypeMaps should come into the equation if you're going to/from Expando.

**Comment by jbogard** [comment]
For example, the first query doesn't need a "dynamic" to work. You can do this:

http://stackoverflow.com/questions/16838136/create-a-lambda-expression-with-a-new-anonymous-type-at-runtime

That'd be my preferred way to go rather than mucking around with anonymous types. Though I'm not entirely sure why you're using anonymous types with AutoMapper.

**Comment by pournejati** [comment]
Other than my "Reason" for choosing anonymous types, I want to know if anonymous types are supported in AutoMapper. If the answer is yes, how I can achieve the code I posted in the current version? I used to run the same code, and it worked. It still working for single entity, but breaks when I try to map a list of anonymous types. And if it is not supported anymore, I think this issue should be closed.

**Comment by jbogard** [comment]
Well, the whole reason behind CreateMissingTypeMaps is explicitly for anonymous types and really nothing else. So yeah, this SHOULD work as it's the sole reason behind the feature.

**Comment by mustafajavid** [comment]
Hi @pournejati!!

I'm facing a similar problem in my project where i am also trying to map from a list of `dynamic `objects with the use of `CreateMissingTypeMaps ` . Any idea on how to solve this issue? My Automapper version is 6.2.2

**Comment by pournejati** [comment]
I honestly had this issue with the first release of Version 5. It resolved with the next release. So maybe your issue is different from what I experienced. If you use the static Mapper method, and all of your properties match, it should work just fine.
