### ISSUE TITLE
Nested Collection Mapping and Updates

### ISSUE THREAD

**Issue by LorenDorez** [AutoMapper/AutoMapper#1742]
I have an Object that has a ICollection list. The initial Mapping works fine for the Create Process in MVC.

However when i try to do my Edit Process when i call the Mapping the list is duplicated rather than updates.

Example

Object A
- Id: 1
- Shifts (ICollection List)
  - Id 1, Value 1.25
  - Id 2, Value 0.75

If i have a view Model with Shift 2 updated to a value of 5.25 then my mapped object becomes this, rather than override the values it duplicates everything..

Object A
- Id: 1
- Shifts (ICollection List)
  - Id 1, Value 1.25
  - Id 2, Value 0.75
  - Id 1, Value 1.25
  - Id 2, Value 5.25

Any ideas?

**Comment by lbargaoanu** [comment]
This was already fixed. Try the MyGet build.

**Comment by LorenDorez** [comment]
@lbargaoanu How do i do that. Im using Nuget via project.json and running version 5.1.1

**Comment by lbargaoanu** [comment]
You have to add the feed source in VS somehow. Use your Google-fu :)

**Comment by KasunKoswattha** [comment]
@LorenDorez In VS, go to tools -> Nuget PackageManager -> Package Manager settings. 
Then Select Package Sources. 
Then you can click on the big green "Plus" button to add new package source.

**Comment by LorenDorez** [comment]
Thanks guys. SOrry never used myGet before.

Is this the URL i add for the my Get Package Source 

https://www.myget.org/F/automapperdev/api/v2/package/AutoMapper/

**Comment by LorenDorez** [comment]
@lbargaoanu @KasunKoswattha 

Thanks guys. I managed to get he MyGet setup and confirmed it is fixed in the latest Alpha. Do either of you know why when AutoMapper Maps a Nested Property in EF Core that it throws an Tracking Error? Ill start a new issue once i can run some more tests first on it

**Comment by lbargaoanu** [comment]
This can be closed.
