### ISSUE TITLE
ReverseMap ignores mapping inheritance (AutoMapper 5.1.1)

### ISSUE THREAD

**Issue by dmdymov** [AutoMapper/AutoMapper#1743]
[Gist with issue code.](https://gist.github.com/dmdymov/11aab6658c6dbe2d5803ca5d6cefd24c)

ReverseMap ignores IncludeBase() calls. Everything works fine if you create separate reverse mapping.

**Comment by lbargaoanu** [comment]
That's the way to go. ReverseMap won't do that for you.

**Comment by dmdymov** [comment]
Won't do what? I mean what exactly does ReverseMap do then? My thought always was that it works exactly like separate reverse mapping and this code works fine with AutoMapper 4.1.1.

**Comment by lbargaoanu** [comment]
ReverseMap is just CreateMap with the reversed types, no configuration.

**Comment by lbargaoanu** [comment]
Well, it does copy some configuration, I'll investigate.

**Comment by dmdymov** [comment]
From gist:
`CreateMap<ConcreteThingDto, ConcreteThing>()`
`.IncludeBase<ThingDto, Thing>()`
`.ReverseMap()`
`.IncludeBase<Thing, ThingDto>();`

IncludeBase call after ReverseMap call is configuration here, isn't it?

**Comment by lbargaoanu** [comment]
Actually it will copy Includes for you, but not IncludeBase. So apparently your example should work with Include, without any explicit configuration for the reverse map. But why IncludeBase is not similar, I don't know. I would say it's a bug.

**Comment by dmdymov** [comment]
I am trying to upgrade my project to AM 5.1.1 and I have a lot of similar ReverseMap uses. Should I wait for a fix or CreateMap<B,A> is the solution?

**Comment by lbargaoanu** [comment]
Wait. I didn't figure it out yet, but unless @jbogard disagrees, we'll fix it.

**Comment by jbogard** [comment]
Nope, looks good.
