### ISSUE TITLE
Automapper Configure Gives Obsolete Error 

### ISSUE THREAD

**Issue by KusumSitecore** [AutoMapper/AutoMapper#1747]
protected override void Configure()
        {
            this.CreateMap<P1, P2>()
                .ForMember(d => d.Prop2, o => o.Ignore())
            ;
        }

How can I use Configure Profiles in Automapper for .NET Core

**Comment by lbargaoanu** [comment]
Try the constructor of you profile class.

**Comment by jbogard** [comment]
Use the constructor instead, I've marked the Configure method obsolete.

**Comment by KusumSitecore** [comment]
Thanks Jimmy
