### ISSUE TITLE
IgnoreAllNonExisting

### ISSUE THREAD

**Issue by Hamidnch** [AutoMapper/AutoMapper#1749]
Hi.
How to write IgnoreAllNoneExisting for Unmapped properties in Automapper 5.0.2 ?!
Thanks.
[Best Regards]

**Comment by jbogard** [comment]
Use the MemberList in the CreateMap options. You're likely wanting to assert against either the Source side, or no member options at all:

```
CreateMap<Foo, Bar>(MemberList.Source);
```

**Comment by Hamidnch** [comment]
Thank you so much for helping me out tonight.
