### ISSUE TITLE
ConstructedBy Missing?

### ISSUE THREAD

**Issue by mjames15** [AutoMapper/AutoMapper#1754]
This may have been intentional but the constructedby method appears to have been removed.  What are the alternatives that can be used?  This is used to properly read a XML file.

```
 .ForMember(dest => dest.Url,
                               opt => opt.ResolveUsing<XAttributeResolver<string>>()
                               .ConstructedBy(() => new XAttributeResolver<string>("url", "public", "1")))
```

**Comment by jbogard** [comment]
Yeah, it was redundant. You can just instantiate the resolver directly with ResolveUsing. There's an overload that takes a resolver instance - just use that.

**Comment by mjames15** [comment]
Thanks, that worked.  This can be closed
