### ISSUE TITLE
Automapper version 2.2 giving Access Violation exception on Windows Azure Website

### ISSUE THREAD

**Issue by TariqAshraf** [AutoMapper/AutoMapper#1756]
We are using automapper version 2.2 in our website which is hosted in windows azure websites . On October 21, 2016 automapper started throwing AccessViolation Exception on some places in our website, before that it was working fine. 
We need help in this regard.

**Comment by jbogard** [comment]
AutoMapper 2.2? That was released over 4 years ago! Do you have a stack trace or anything? Do you see this after you upgrade to the latest?

**Comment by TariqAshraf** [comment]
We had started using AutoMapper around 3.5 years ago, at that time version 2.2 was the available version. We had not updated the version as our code was working perfectly with it until Oct 21,2016 when it started throwing AccessViolation exception in windows azure hosted website. We are working on upgrading to the latest version but it seems latest version does not support IDataReader mapping.

Following is stack track 

01 1f79dc60 1e7be367 AutoMapper!AutoMapper.Mappers.DataReaderMapper.MapDataReaderToEnumerable(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner, System.Type, Boolean)+0xfa
02 1f79dc80 1e7be074 AutoMapper!AutoMapper.Mappers.DataReaderMapper.Map(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner)+0x4f
03 1f79dcd4 1e7bda03 AutoMapper!AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(AutoMapper.ResolutionContext)+0x164
04 1f79dcf0 1e7bd971 AutoMapper!AutoMapper.MappingEngine.Map(System.Object, System.Type, System.Type, System.Action`1<AutoMapper.IMappingOperationOptions>)+0x6b
05 1f79dd24 1e7bd346 AutoMapper!AutoMapper.MappingEngine.Map[[System.__Canon, mscorlib],[System.__Canon, mscorlib]](System.__Canon)+0xa1
06 1f79dd40 1f3aaf27 AutoMapper!AutoMapper.Mapper.Map[[System.__Canon, mscorlib],[System.__Canon, mscorlib]](System.__Canon)+0x46

**Comment by jbogard** [comment]
Oh DataReader even. No idea, I didn't write that code and I took it out because I had no idea what it was doing. Sorry!

**Comment by swatiAga** [comment]
We have the same issue.
