### ISSUE TITLE
Memeory leak 

### ISSUE THREAD

**Issue by leung85** [AutoMapper/AutoMapper#1759]
I use AutoMapper 5.1.1 in WebAPI

```
 var config = new MapperConfiguration(
                    cfg => cfg.CreateMap<Employee, EmployeeBindingModels>()
                );
  IMapper mapper = config.CreateMapper();
  EmployeeBindingModels model = mapper.Map<EmployeeBindingModels>(employee);
```

I make 1000 request to the API. The Heap size of some AutoMapper object accumulates and never drop.

![image](https://cloud.githubusercontent.com/assets/8042599/19712131/c5e01e5e-9b6d-11e6-8efe-2f710a8c8516.png)

However, using static Mapper does not have above problem. The Heap size is drop.

Is it the same issue #1691 ??

**Comment by jbogard** [comment]
Have you tried the MyGet package?

**Comment by leung85** [comment]
Thanks, Jimmy. I update to 5.2.0-alpha-01233 via MyGet

The problem solved.
