### ISSUE TITLE
How to configure automapper when Anonymous type returned from linq query

### ISSUE THREAD

**Issue by xiaoyc** [AutoMapper/AutoMapper#1760]
Hi.

I have the below query (it has a "Join " )which will query all columns in Post/PostTaxonomy Table and return Anonymous type .
var posts = from p in _postResository.GetAll()
join pt in _postTaxonomyResository.GetAll() on p.Id equals pt.PostId
select new { p, pt };

I found a post in AutoMapper site ( https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions) , The .ProjectTo() will tell AutoMapper's mapping engine to emit a select clause to the IQueryable that will inform entity framework that it only needs to query the Name column of the Item table, same as if you manually projected your IQueryable to an OrderLineDTO with a Select clause.

then i use it in my project

var pageItems = await posts.ProjectTo().ToListAsync();

but it throw the below exception.

Missing map from <>f__AnonymousType02[SuperCMS.Posts.Post,SuperCMS.PostTaxonomies.PostTaxonomyMapping] to SuperCMS.PostApp.DTO.PostDTO. Create using Mapper.CreateMap<<>f__AnonymousType02, PostDTO>.

So Could you please tell me where / how can i configure Automapper to use this feature ?
Thanks .

**Comment by lbargaoanu** [comment]
You're supposed to project from entities to DTOs, no anonymous type needed.

**Comment by xiaoyc** [comment]
Thanks for your reply .
Yes，it can work from entities to DTOs ,but  from some linq queries ,sometimes it will return Anonymous  type like " select new { ...}" ,how can i do with this ?   Must i  manually  write a Select clause  like " select new DTO { Name =t.name ...}" ?

**Comment by lbargaoanu** [comment]
Yes. Because hat would mean the DTO doesn't look anything like the anonymous type, so I would say AM can't help.

**Comment by jbogard** [comment]
No, you don't need that. Just create a composite source type like this:

```
public class JoinedPost {
   public Post Post { get; set; }
   public PostTaxonomy PostTaxonomy { get; set; }
}
```

Then in your query (I assume that your repositories are just a wrapper around a DbContext):

```
var posts = from p in db.Posts
join pt in db.PostTaxonomies on p.Id equals pt.PostId
select new JoinedPost { Post = p, PostTaxonomy = pt };
```

Finally, you'd create a map between JoinedPost and `SuperCMS.PostApp.DTO.PostDTO`. Then ProjectTo:

```
var dtos = await posts.ProjectTo<SuperCMS.PostApp.DTO.PostDTO>().ToListAsync();
```

If you have to pull multiple entities together to a single DTO, I always create the composite model on the source side, THEN map or project that composite model to my DTO.

**Comment by xiaoyc** [comment]
Thanks @jbogard  and @lbargaoanu .
I created a composite type like : 

   public class JoinedPost
        {
            public Post Post { get; set; }
            public PostTaxonomyMapping PostTaxonomy { get; set; }
        }


and created a map : mapper.CreateMap<JoinedPost, PostDTO>();

then use the blow code to test.
var posts = from p in _postResository.GetAll()
                           join pt in _postTaxonomyResository.GetAll() on p.Id equals pt.PostId
                           select new JoinedPost { Post= p , PostTaxonomy = pt };


 var posts2 = posts.ProjectTo<PostDTO>().ToList(); 


but the sql generated by ProjectTo<T>  seems **not correct** .

 **before ProjectTo the sql is :** 

posts	{SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Title] AS [Title], 
    ....
    [Extent2].[Id] AS [Id1], 
    ....
    [Extent2].[CreationTime] AS [CreationTime1], 
    FROM  [dbo].[Posts] AS [Extent1]
    INNER JOIN [dbo].[PostTaxonomyMappings] AS [Extent2] ON [Extent1].[Id] = [Extent2].[PostId]}	System.Linq.IQueryable<SuperCMS.Application.PostApp.PostService.JoinedPost> {System.Data.Entity.Infrastructure.DbQuery<SuperCMS.Application.PostApp.PostService.JoinedPost>}

**but after ProjectTo the sql is** 


+		posts.ProjectTo<PostDTO>()	{SELECT 
    1 AS [C1], 
    cast(1 as bit) AS [C2]
    FROM [dbo].[PostTaxonomyMappings] AS [Extent1]}	System.Linq.IQueryable<SuperCMS.PostApp.DTO.PostDTO> {System.Data.Entity.Infrastructure.DbQuery<SuperCMS.PostApp.DTO.PostDTO>}


the columns are lost , Is there something wrong with my code ?


Thanks

**Comment by xiaoyc** [comment]
var posts2 = posts.ProjectTo < PostDTO > ().ToList();

**Comment by jbogard** [comment]
I wonder, does EF not handle multiple projections? Instead of using AutoMapper, try writing another Select statement yourself and see if that produces the right thing.

**Comment by xiaoyc** [comment]
Thanks @jbogard .

**Comment by krptodr** [comment]
I'm having this issue as well. If I dont apply a where clause and I retrieve a list, the ProjectTo returns the records and Projects it into my DTO without a problem. However, when I want to specify a where clause and project to it, my query adds the 1 "C1" column in the SELECT statement.  I believe this is causing my result to not get mapped by AutoMapper because my result returned is null.
