### ISSUE TITLE
Mapping of string properties

### ISSUE THREAD

**Issue by sbradl** [AutoMapper/AutoMapper#1761]
When I map between two types which have a property of type string AutoMapper copies the real reference.

This means changing the property of the source object also changed the property on the second object. I think for strings this should not be the default behaviour.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by sbradl** [comment]
Sry,

forget the Issue. It was just a connection of two failures I made...
