### ISSUE TITLE
AutoMapper hangs on AddProfile

### ISSUE THREAD

**Issue by DeanSharp-Servelec** [AutoMapper/AutoMapper#1762]
Hi

I have tried updating from version 5.0.2 to 5.1.1 and now the application just hangs at the AddProfile stage.

The AssertConfigurationIsValid test just sees the memory usage keep climbing. 30 minutes in and 12 gig of memory later I killed off the process as it didn't feel like it was going to complete any time soon.

The application does the same thing at startup so it's unworkable at the moment. We do have 900+ mappings in a single profile with multiple levels of nesting so there is a lot to do but it's not been a problem until this upgrade and goes back to a few seconds if i revert AutoMapper to the 5.0.2 release.

Has this been encountered before?

Thanks

**Comment by lbargaoanu** [comment]
Unless you have e repro, you'll have to profile it to see what's going on.

**Comment by jbogard** [comment]
Yeah, I'd need to see a stack trace or something.
