### ISSUE TITLE
Question: ResolveUsing - property  instead of source

### ISSUE THREAD

**Issue by janvanhelvoort** [AutoMapper/AutoMapper#1763]
Hi,

I have something like the following code:

```cs    
public class Case
    {
        public int UserId { get; set; }
    }

    public class Task
    {
        public int CreatedById { get; set; }

        public int OwnerId { get; set; }
    }

    public class UserDto
    {
        public int Id { get; set; }
    }

    public class CaseDto
    {           
        public UserDto User { get; set; }
    }

    public class TaskDto
    { 
        public UserDto CreatedBy { get; set; }

        public UserDto Owner { get; set; }
    }
```

and want to map them something like this, where the parameter of ResolveCore of the ValueReolver is generic / dynamic:

```cs
Mapper.CreateMap<Case, CaseDto>()
    .ForMember(dest => dest.User, opt => opt.ResolveUsingProperty<UserResolver>(src => src.UserId));

Mapper.CreateMap<Task, TaskDto>()
    .ForMember(dest => dest.CreatedBy, opt => opt.ResolveUsingProperty<UserResolver>(src => src.CreatedById))
    .ForMember(dest => dest.CreatedBy, opt => opt.ResolveUsingProperty<UserResolver>(src => src.Owner));
```

I have tried with a custom ValueResolver, but they need the specific class, than i need to make 2/3 custom ValueResolvers.

How can i achieve this with one custom ValueResolver?

Thank you!

Jan

**Comment by jbogard** [comment]
What does that resolver look like?

**Comment by janvanhelvoort** [comment]
I haven't have one, because `ResolveUsingProperty` doesn't exist. `ResolveUsing` have no parameters and need a specific class implementation as source type. The `ResolveUsing` `ConstructedBy` isn't a option, because of dependency injection and I don't want the dependency container inside the `profile` class.

But what i tried:
```cs
    public class UserResolver : ValueResolver<int, UserDto>
    {
        // ctor with dependency injection

        protected override UserDto ResolveCore(int id)
        {
            UserDto user = // from cachemanager.

            return user;
        }
    }
```
But the parameter of the`ResolveCore` is of the type from the mapping source, e.g: `Case` or `Task`, Type `int` or `generic` isn't possible because of the `ValueResolver<TSource, UserDto>`

What a nice option is, when we can inject a property value of the source instance as parameter for the `ResolveCore` method instead of a non reusable source like `Case.UserId` and `Task.OwnerId`.

**Comment by janvanhelvoort** [comment]
Sorry,  I did not see the `FromMember` of `ResolveUsing`.
Current solution: 
`ForMember(dest => dest.User, opt => opt.ResolveUsing<UserResolver>().FromMember(src => src.UserId))`

**Comment by jbogard** [comment]
Just FYI, in 5.0, I introduced a breaking change around resolving from members, introducing a new interface distinct from the IValueResolver so that you can get full access to source/destination members.
