### ISSUE TITLE
MapFrom/ResolveUsing no longer support null assignment

### ISSUE THREAD

**Issue by mattzink** [AutoMapper/AutoMapper#1764]
We're migrating from AutoMapper 3.3.1 to 5.1.1. We have a member mapped using a custom resolver, which in some cases returns null, and therefore we expect the destination to be set to null. This appears to no longer work.

Here's a short contrived example:

```
class Entity
{
    public string Property { get; set; }
}

class Dto
{
    public string Property { get; set; }
}

static void Main(string[] args)
{
    Mapper.Initialize(config =>
    {
        config.CreateMap<Entity, Dto>()
            .ForMember(dest => dest.Property, opt => opt.ResolveUsing(src => (Dto) null));
    });
    Mapper.AssertConfigurationIsValid();

    var inst = new Entity {Property = "base"};
    var dto = Mapper.Map<Entity, Dto>(inst); // This throws in AutoMapper 5.1.1
}
```

The exception message is:

```
Error mapping types.

Mapping types:
Entity -> Dto
Automapper5Test.Program+Entity -> Automapper5Test.Program+Dto

Type Map configuration:
Entity -> Dto
Automapper5Test.Program+Entity -> Automapper5Test.Program+Dto

Property:
Property

Inner exception:
Object reference not set to an instance of an object.
```

I've tried specifying `opt.AllowNull()` and replacing with `opt.MapFrom(...)` but neither helped.

Is there a new way to provide a member mapping that should sometimes be assigned null?

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by jbogard** [comment]
Yep, works on MyGet.

**Comment by barakcaf** [comment]
this still happens on 6.X

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by kdub454** [comment]
https://gist.github.com/kdub454/f266dbeb37680cb388a6a275846365a1

**Comment by lbargaoanu** [comment]
See [this](http://docs.automapper.org/en/stable/Reverse-Mapping-and-Unflattening.html). If you don't like the results, just don't use ReverseMap.
