### ISSUE TITLE
Issue with Profile and custom ResolveUsing

### ISSUE THREAD

**Issue by aroemen** [AutoMapper/AutoMapper#1767]
```
public class Sample
{
    public IEnumerable<SomeObject> Alphas { get; set; }
    public IEnumerable<SomeOtherObject> Betas { get; set; }
}

public class SampleGroup
{
    public IEnumerable<SomeObjectDto> Alphas { get; set; }
    public IEnumerable<SomeOtherObjectDto> Betas { get; set; }
}

public class SampleDto
{
    public SampleGroup Group { get; set; }
}
```

Above are examples of objects that I need mapped. I've been migrating away from the static usage of AutoMapper, but am unable to find a way to map this correctly without the static instance of AutoMapper. Here is my Profile that maps this correctly using the static instance (assume that the some objects are already setup correctly in another map):

```
CreateMap<Sample, SampleDto>()
    .ForMember(dest => dest.Group, opt => opt.ResolveUsing(src => new SampleGroup
    {
        Alphas = Mapper.Map<IEnumerable<SomeObjectDto>>(src.Alphas),
        Betas = Mapper.Map<IEnumerable<SomeOtherObjectDto>>(src.Betas),
    }));
```

How can I implement this mapping without the static instance of AutoMapper?

**Comment by jbogard** [comment]
There's an overload of ResolveUsing that supplies a ResolutionContext object. That has the IMapper instance you're looking for:

```
CreateMap<Sample, SampleDto>()
    .ForMember(dest => dest.Group, opt => opt.ResolveUsing((src, dest, member, ctxt) => new SampleGroup
    {
        Alphas = ctxt.Mapper.Map<IEnumerable<SomeObjectDto>>(src.Alphas),
        Betas = ctxt.Mapper.Map<IEnumerable<SomeOtherObjectDto>>(src.Betas),
    }));
```

**Comment by lbargaoanu** [comment]
Of course if you have a map between Sample and SampleGroup, you don't need to map by hand.

**Comment by aroemen** [comment]
@jbogard perfect! That is what I was needing. @lbargaoanu, yes but the objects are more complex than what I posted here. Thanks for your help guys.
