### ISSUE TITLE
Adding Profiles after Mapper.Initialize was called

### ISSUE THREAD

**Issue by bnbaliga** [AutoMapper/AutoMapper#1768]
Hi All,

We have a requirement in our project where we have to register profiles which are spread across in multiple assemblies. Now instead of calling Mapper.Initiazie and pass a list of assembly names, we want to register these profile using chaining pattern, so that each assembly is responsible to register it's own profiles.

How do we do that as Mapper.Initalize can be called only once in the App domain? Is there a way to add profiles other than Mapper.Initiaze method?

Need your inputs.

Regards
Baliga

**Comment by jbogard** [comment]
Why do you want to do this? Each assembly should only *declare* its profiles, not register them. Are you building some kind of multi-tenant application?
