### ISSUE TITLE
ProjectTo Ignoring NullSubstitute ConfigurationExpression

### ISSUE THREAD

**Issue by treetopvt** [AutoMapper/AutoMapper#1771]
Using 5.1.1 with Query Extensions ProjectTo and EF6.
My mapping profile:
```
            CreateMap<PlatformModel, PlatformDTO>().ConstructUsingServiceLocator()
                .ForMember(dest => dest.PermissionLevel, opt =>
                  {
                      opt.NullSubstitute(levelService.General);
                      opt.MapFrom(o => o.PermissionLevel);
                  });
            CreateMap<PermissionModel, PermissionDTO>(MemberList.None)
                   .ForMember(dest => dest.Id,
                        opts => opts.MapFrom(src => src.Id))
                   .ForMember(dest => dest.SecurityName,
                    opts => opts.MapFrom(src => src.SecurityName));
```
My call to ProjectTo:
```
var mappedResult = matchingPlatforms.ProjectTo<PlatformDTO>(_mapper.ConfigurationProvider);
```
Mapper is using StructureMap IoC.

I expect that any null values for the PermissionLevel property should be replaced with the Unclassified property from the levelService.

Because I am using ProjectTo, I am rather limited in how I can replace/test for null values.  The Query Extensiosn documentation states that NullSubstitute is supported.

**Comment by lbargaoanu** [comment]
Maybe I'm missing your point, but the null substitute is a constant.

**Comment by jbogard** [comment]
That null substitute wouldn't really work in a projection - what is "levelService"?
