### ISSUE TITLE
Automapper Create Missing type causes exception

### ISSUE THREAD

**Issue by kamran-pervaiz** [AutoMapper/AutoMapper#1773]
hi guys,

please could you have a look at below stackoverflow question. I am not sure why its causing this behavior.

http://stackoverflow.com/questions/40404736/automapper-create-missing-type-causes-exception

any idea/suggestion?

**Comment by lbargaoanu** [comment]
You could use a different profile (or mapper) for the anonymous types.

**Comment by kamran-pervaiz** [comment]
I am not sure what do you mean? how can i write a mapper for Anonymus type? because i read somewhere that dynamic mapper is deprecated.

` select new
                         {
                             e.Id,
                             e.Name,
                             e.Alias,
                             o.Address.Line1,
                             o.Address.CountryId,,
                             ContactName = e.SupplierContacts.FirstOrDefault().Contact.Name
                         }).ProjectTo<SupplierDto>();`

how can I write a mapping for above anonymous type to SupplierDto?

**Comment by lbargaoanu** [comment]
In this particular case I would avoid the anonymous type and project directly to the DTO.

**Comment by kamran-pervaiz** [comment]
you mean create new SupplierDto object and assign properties? like...
`select new SupplierDto { Id = e.Id, Name = e.Name, Alias = e.Alias, Line1 = o.Address.Line1, CountryId=o.Address.CountryId, ContactName = e.SupplierContacts.FirstOrDefault().Contact.Name });`

**Comment by lbargaoanu** [comment]
The first choice would be to create a map between the entity and the final DTO.

**Comment by kamran-pervaiz** [comment]
ok will try that, thanks I have disable missingType and converted anonymous to concrete type. thanks for your suggestion.
