### ISSUE TITLE
Improve error message when constructor mapping fails

### ISSUE THREAD

**Issue by chrischu** [AutoMapper/AutoMapper#1777]
I recently bumped into a problem when mapping to an immutable type. I got this error message:

> Immutable needs to have a constructor with 0 args or only optional args

This at first lead me to believe that AutoMapper does not support immutable types, which after some more research turned out to be false.

However, I think it would be very valuable to get a better error message (maybe like the error message one gets when mapping to a mutable type) when something goes wrong to make it clearer what the actual problem is.

In the following example, the problem lies in the fact that Mutable.ValueB and Immutable.ctor(valueA, vB) don't fit together. A message pointing that error out would be very helpful when diagnosing such errors (and it would also help out new users that might be lead to believe that AutoMapper does not even support immutable type mapping).

    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => { cfg.CreateMap<Mutable, Immutable>(); });
            var mapper = config.CreateMapper();

            var mutable = new Mutable { ValueA = "valueA", ValueB = 7 };
            var immutable = mapper.Map<Immutable>(mutable);

            Console.WriteLine(immutable.ValueA);
            Console.WriteLine(immutable.ValueB);
        }

        public class Mutable
        {
            public string ValueA { get; set; }
            public int ValueB { get; set; }
        }

        public class Immutable
        {
            public string ValueA { get; }
            public string ValueB { get; }

            public Immutable(string valueA, string vB)
            {
                ValueA = valueA;
                ValueB = vB;
            }
        }
    }

**Comment by lbargaoanu** [comment]
PR?

**Comment by chrischu** [comment]
I looked at the code and frankly I don't think I have the necessary insight into it to actually make that change and unfortunately I currently don't have the time resources to devote several days to get me up to speed :(.

Also I think there are several questions that should be answered first:
What happens if there are multiple constructors? Only put out an error message for the "nearest" constructor? What if there are 2 "nearest" constructors (input: (string s, int i), ctor1: (string s, double d), ctor2: (string s, float f))?

**Comment by lbargaoanu** [comment]
Exactly :) Maybe it's not so easy to get a useful error message.

**Comment by chrischu** [comment]
I never claimed it was easy, that doesn't change the fact that the current error message is very misleading, though.

**Comment by lbargaoanu** [comment]
Well, someone has to write the code...

**Comment by chrischu** [comment]
Yeah, well the question is how AutoMapper as a project is run. It comes down to this question: Do you want to fix this issue yourself and potentially benefit all AutoMapper users as quickly as possible or do you want to wait until someone is bothered enough to warrant investing the time and fixing it themselves?

There is no right answer obviously, it's a question of project philisophy and also how important you judge the issue to be.

I'm just saying that I probably won't have the time and resources to fix it myself in the foreseeable future unfortunately.

**Comment by jbogard** [comment]
The problem is I don't know what a "good" error message is here, so I wouldn't know what "done" looks like for us.
