### ISSUE TITLE
System.DateTime mapping to DateTimeKind.Utc

### ISSUE THREAD

**Issue by demirag** [AutoMapper/AutoMapper#1779]
For almost all my projects I am having the following mapping. 

`CreateMap<DateTime, DateTime>().ConvertUsing(i => DateTime.SpecifyKind(i, DateTimeKind.Utc));`

This was working fine until I upgrade to version 5.1.1

Now I am getting the following error;

`> Expression of type 'System.DateTime' cannot be used for assignment to type 'System.Nullable`1[System.DateTime]'`

If I remove this mapping, everything else just works. Any idea or fixto this?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://www.google.com/search?q=automapper+"myget"+build) build.

**Comment by demirag** [comment]
Thanks @lbargaoanu. MyGet build works. Will Nuget builds work in the future? What is the difference between those builds?

**Comment by lbargaoanu** [comment]
See the discussion in #1770. And feel free to contribute if things seem unclear.
