### ISSUE TITLE
5.1.1: ProjectTo explicit expansion failing, working perfect without explicit

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#1780]
I have a simple model in which I Define a property mapping:

.ForMember(d => d.Portfolio, o => { o.MapFrom(s => s.CustomerPortfolio); o.ExplicitExpansion(); })

If I do not put up explicit expansion, then the mapping works fine - albeit, clearly, pulling irrelevant data from the database.

If I put "Porfolio" into the ProjectTo expansion:

 expand = new string[] { "Portfolio" };
var  q = query.ProjectTo<T>(expand);

then execution fails with the following stack trace:

Object reference not set to an instance of an object.
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Object parameters, Expression`1[] membersToExpand)
   at Red.Web.Api.Code.ODataExtensions.ProjectTo[S,T](IQueryable`1 query, ODataQueryOptions`1 options) in C:\Work\ObjectBrief\Red.Web.Api\Code\ODataExtensions.cs:line 31
   at Red.Web.Api.Controllers.CodPropertyController.Get(ODataQueryOptions`1 options) in C:\Work\ObjectBrief\Red.Web.Api\Controllers\CodPropertyController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

If I use explicit expansion, but do not pass in the expansion (with ProjectTo()) then it fails with:

"type":"System.InvalidOperationException","stacktrace":"","internalexception":{"message":"The specified type member 'Portfolio' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.","type":"System.NotSupportedException","stacktrace":"   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)\r\n   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()\r\n   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at **System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"}}}}

Again, it works flawless if I cann ProjectTo() and replace

.ForMember(d => d.Portfolio, o => { o.MapFrom(s => s.CustomerPortfolio); o.ExplicitExpansion(); })

with

.ForMember(d => d.Portfolio, o => { o.MapFrom(s => s.CustomerPortfolio); })

indicating that the error is NOT with the type or name.

**Comment by lbargaoanu** [comment]
Does it work with EF6?

**Comment by NetTecture** [comment]
That is EF6. he installed version is 6.1.3. This is a .NET "standard" OData application using the current libraries, not using .NET core - they seem to have refactored EF to have a core component now ;)

**Comment by lbargaoanu** [comment]
Aha, sorry about that :) It seems to work with the latest from Nuget or MyGet. If you see something else, we need a repro.

**Comment by NetTecture** [comment]
Please define latest from nuget - because that is likely what I use. Not on the MyGet for that (yet). How comples does the repro have to be (given EF is involved that may include database setup scripts?).

**Comment by lbargaoanu** [comment]
Make a gist that we can execute and see fail. Something like [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/IntegrationTests.Net4/ExpandCollections.cs) (ignore the base class). We don't need scripts, just the models.

**Comment by NetTecture** [comment]
No real problem getting an error....

Here is some code. Db connection string needed....


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using AutoMapper;
using AutoMapper.QueryableExtensions;

namespace AutoMapper1780 {
    class Program {
        static void Main(string[] args)
        {

            Mapper.Initialize (x => {
                x.CreateMap<Efo1, Dto1>()
                .ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
                .ForMember(d => d.Name, o => o.MapFrom(s => s.Name))
                .ForMember(d => d.Dto2Identity, o => o.MapFrom(s => s.Dto2.Identity))
                .ForMember(d => d.Dto2, o => { o.MapFrom(s => s.Dto2); o.ExplicitExpansion(); })
                //.ForMember(d => d.Dto2, o => o.MapFrom(s => s.Dto2))
                ;
                x.CreateMap<Efo2, Dto2>()
                .ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
                .ForMember(d => d.Name, o => o.MapFrom(s => s.Name))
                ;
            });
            Mapper.AssertConfigurationIsValid();
            var db = "xxxxx";
            var context = new EfContect(db);
            // Error: Object not found -> ok
            //var result = context.Efo1.ProjectTo<Dto1>().ToList();

            // Error: "Parameter count mismatch." ???? ERROR
            //var result = context.Efo1.ProjectTo<Dto1>("Dto2").ToList();


        }
    }

    [Table("Dto1")]
    public class Dto1 {

        [Key]
        public Guid Identity { get; set; }

        public Guid Dto2Identity { get; set; }

        [ForeignKey("Dto2Identity")]
        public Dto2 Dto2 { get; set; }

        public string Name { get; set; }

    }

    [Table("Dto2")]
    public class Dto2 {

        [Key]
        public Guid Identity { get; set; }

        public string Name { get; set; }

    }

    public class EfContect : DbContext {

        public EfContect(string db) : base(db) {            
            Database.Log = l => Debug.Print(l);
            Database.SetInitializer<EfContect>(null);
        }

        public IDbSet<Efo1> Efo1 { get; set; }

        public IDbSet<Efo2> Efo2 { get; set; }

    }

    public class Efo1 {

        [Key]
        public int Id { get; set; }

        public Guid Identity { get; set; }

        public string Name { get; set; }

        public virtual Dto2 Dto2 { get; set; }

    }

    public class Efo2 {

        [Key]
        public int Id { get; set; }

        public Guid Identity { get; set; }

        public string Name { get; set; }

    }
}

**Comment by NetTecture** [comment]
Oh, as side comment: if you replace:

var result = context.Efo1.ProjectTo<Dto1>("Dto2").ToList();

with

var result = context.Efo1.ProjectTo<Dto1>(x => x.Dto2).ToList();

i get a missing object -> sql is generated-

**Comment by lbargaoanu** [comment]
I don't see nothing wrong.
For the string case, you're choosing the wrong overload. It should be 

    ProjectTo<Dto1>(null, "Dto2")

For the expression case, that works, but it will do an inner join, so you need Dto2 in the db.

**Comment by NetTecture** [comment]
Ok, let's close it. I did have the wrong call ;(
