### ISSUE TITLE
Ninject autommaper configuration

### ISSUE THREAD

**Issue by juanpa07** [AutoMapper/AutoMapper#1782]
Hello gentlemen,

Rigth now, I working in a project that had the flollowing configuration.

one library that had all mapping class, like this: 

```
internal class CountryMapper : Profile
    {
        public CountryMapper()
        {
            CreateMap<Models.Core.Country, Models.Dtos.Core.CountryDTO>();
            CreateMap<Models.Dtos.Core.CountryDTO, Models.Core.Country>();
        }
    }
```

And one class that get the all Mappers and inject the configuration and bind it to IMapper for use in the project.

```
internal class AutoMapperBind : INinjectBinder
    {
        public void Register(IKernel container)
        {
            //Automapper configuration
            var profiles = GetType().Assembly.GetTypes().Where(t => typeof(Profile).IsAssignableFrom(t)).Select(t => (Profile)Activator.CreateInstance(t));

            var config = new MapperConfiguration(cfg =>
            {
                foreach (var profile in profiles)
                {
                    cfg.AddProfile(profile);
                }
                cfg.ForAllMaps((map, expresion) => expresion.ForAllMembers(options => options.Condition((source, destination, member) => member != null)));
            });
            var mapper = config.CreateMapper();
            container.Bind<MapperConfiguration>().ToConstant(config).InSingletonScope();
            container.Bind<IMapper>().ToConstant(mapper).InSingletonScope();
        }
    }
```

In automapper version 5.0.2 all worked fine, when instantiating IMapper configuration

```
public class CountryProcessor : ICountryProcessor
{
        private readonly IApplicationUnit _appUnit;
        private readonly IMapper _mapper;
       
        public CountryProcessor(IApplicationUnit appUnit, IMapper mapper)
        {
            _appUnit = appUnit;
            _mapper = mapper;          
        }

public async Task<IEnumerable<CountryDTO>> GetSitemapAsync(CancellationToken cancellationToken,  IFilterSettings settings)
        {
             var entities = await _appUnit.Country.GetByFilterAsync(cancellationToken, expression, settings.GetExpression);

            if (entities == null) throw new ElementNotFoundException(ExceptionMessage.NoElementFoundWithParameters);
        
            return _mapper.Map<List<SitemapDTO>>(entities);
        }
}
```

I upgrade automapper to 5.1.1 , and the injection of the configuration in IMapper inside the class AutoMapperBind  not work anymore

but if I put a MapperConfiguration inside of CountryProcessor this works.

```
public class CountryProcessor : ICountryProcessor
{
        private readonly IApplicationUnit _appUnit;
        private readonly IMapper _mapper;
       
        public CountryProcessor(IApplicationUnit appUnit, IMapper mapper)
        {
            _appUnit = appUnit;
            _mapper = mapper;          
        }

public async Task<IEnumerable<CountryDTO>> GetSitemapAsync(CancellationToken cancellationToken,  IFilterSettings settings)
        {
             var entities = await _appUnit.Country.GetByFilterAsync(cancellationToken, expression, settings.GetExpression);

            if (entities == null) throw new ElementNotFoundException(ExceptionMessage.NoElementFoundWithParameters);

var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Models.Core.Country, Models.Dtos.Core.CountryDTO>();
            });
        
            return return config.CreateMapper().Map<IQueryable<Models.Core.Sitemap.Sitemap> , List<SitemapDTO>>(entities);
        }
}
```

I would greatly appreciate the help you can give me.

**Comment by juanpa07** [comment]
Hello again,

I found the problem in the line

`
cfg.ForAllMaps((map, expresion) => expresion.ForAllMembers(options => options.Condition((source, destination, member) => member != null)))`

I will correct it.

**Comment by lbargaoanu** [comment]
So it's all good? :)

**Comment by juanpa07** [comment]
Yes Lucian, All it is good!, Thx.

**Comment by juanpa07** [comment]
@lbargaoanu , I see in the issue [#1634](https://github.com/AutoMapper/AutoMapper/issues/1634) the similar problem that I have.

the following line 

`cfg.ForAllMaps((map, expresion) => expresion.ForAllMembers(options => options.Condition((source, destination, member) => member != null)))`

Returns null values

```
[
  {
    "code": null,
    "parentId": null,
    "url": null,
    "iconUrl": null,
    "order": null,
    "target": null,
    "keywords": null,
    "name": null
  }
]
```
I try with diferents ways, and the result is the same. Can you help me?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/MyGet) build.

**Comment by juanpa07** [comment]
@lbargaoanu is done!
the problem is that ForAllMembers condition can't ignore the Null value properties from source object, when it found one, the mapper ignore the all source.


I expect 

{
    FirstName = "Gene",
    LastName = "Wilder",
    Code = 10
 }

**Comment by juanpa07** [comment]
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class AutomapperTests
    {
        public class Person
        {
            public int Code { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        public class PersonDTO
        {
            public int Code { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        [TestMethod]
        public void TestNullIgnore()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<PersonDTO, Person>()
                    .ForAllMembers(opt => opt.Condition((src, p, srvVal, destVal) => srvVal != null));

            });

            config.AssertConfigurationIsValid();

            var mapper = config.CreateMapper();
            
            var sourcePerson = new Person
            {
                FirstName = "Bill",
                LastName = "Gates",
                Code = 10
            };
            var destinationPersonDto = new PersonDTO
            {
                FirstName = null,
                LastName = "Smith",
                Code = 10
            };

            mapper.Map(destinationPersonDto, sourcePerson);

            Assert.AreNotEqual(sourcePerson.FirstName,null);
            Assert.AreEqual(sourcePerson.LastName, "Smith");
        }
    }
}

**Comment by lbargaoanu** [comment]
Yes, the link was broken, but I'm sure you can find it.

**Comment by juanpa07** [comment]
@lbargaoanu , but you help me how can skip null parameter?

before I used

`.ForAllMembers((map, expresion) => expresion.ForAllMembers(options => options.Condition((source, destination, member) => member != null)))`

and exlude only the null parameter inside the DTO model. Right now, with automapper 5.1.1, this exclude the all DTO model when find null paremeter.

I try with

```
var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<PersonDTO, Person>()
                .ForAllMembers(opt => opt.Condition((src, p, srvVal, destVal) => srvVal != null));

        });
```

and 

```
var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<PersonDTO, Person>()
               .ForAllMembers(opt => opt.Condition((source, destination, member) => member != null));

        });
```

**Comment by juanpa07** [comment]
@lbargaoanu if I understand well, the issue has already been fixed. I'm gonna get the last versión and validate my problem. 

I will tell you what happens

**Comment by juanpa07** [comment]
Hello @lbargaoanu again.

I get the last version Dev of [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build), but the problem persists.

How to ignore the null values in this new version?

I have the following code

```
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class AutomapperTests
    {
        public class Person
        {
            public int Code { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        public class PersonDTO
        {
            public int Code { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        [TestMethod]
        public void TestNullIgnore()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<PersonDTO, Person>();
                cfg.ForAllMaps(
                    (map, expresion) =>
                        expresion.ForAllMembers(
                            options => options.Condition((source, destination, member) => member != null)));

            });

            config.AssertConfigurationIsValid();

            var mapper = config.CreateMapper();
            
            var destinationPersonDto = new PersonDTO
            {
                FirstName = null,
                LastName = "Tesla",
                Code = 10
            };

            var sourcePerson = new Person
            {
                FirstName = "Nikola",
                LastName = "T",
                Code = 10
            };

            mapper.Map(destinationPersonDto, sourcePerson);

            Assert.AreNotEqual(sourcePerson.FirstName,null);
            Assert.AreEqual(sourcePerson.LastName, "Tesla");
        }
    }
}
```

And I wan to update the lastname of a person

```
{
  "code": 10,
  "firstName":"Nikola",
  "lastName":"T"
}

this is the dto:
{
  "code": 10,
  "firstName":null,
  "lastName":"Tesla"
}
```

And I expect the following result:

```
{
  "code": 10,
  "firstName":"Nikola",
  "lastName":"Tesla"
}
```

but it isn't work in the last version of "The MyGet build".

Thank you for all the help you can give me.

**Comment by lbargaoanu** [comment]
Your code work with the MyGet build. You're missing smth.

**Comment by juanpa07** [comment]
@lbargaoanu 
I'm not know what I doing wrong, I'm a little confused.

1. I create a new unit test project

2.  I get the last version of automapper 5.1.1 from   https://www.myget.org/F/automapperdev/api/v3/index.json

3.  I use the following code

```
var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<PersonDTO, Person>()
                .ForAllMembers(m => m.Condition((source, target, sourceValue, targetValue) => sourceValue != null));
              
            });

            //config.AssertConfigurationIsValid();

            var mapper = config.CreateMapper();
            
            /*Source*/
            var personDto = new PersonDTO()
            {
                LastName = "Tesla",
            };

            /*Destination*/
            var person = new Person()
            {
                FirstName = "Nikola",
                LastName = "T"
            };

            mapper.Map(personDto, person);

            Assert.AreNotEqual(person.FirstName,null); // result is Nikola
            Assert.AreEqual(person.LastName, "Tesla"); // result is T
```
 And the result is always the same.  I'm gonna tal with some developer friend for try it again in his laptop.

**Comment by lbargaoanu** [comment]
The pre-release check? 5.2.0-alpha-01242 is the latest.

**Comment by juanpa07** [comment]
@lbargaoanu is my mistak, with the version 5.2.0-alpha-01242 works! thank you and I'm sorry(i always install again the 5.1.1)
