### ISSUE TITLE
Automapper 5.1.1 Can't map Complex object, aways invalid

### ISSUE THREAD

**Issue by fals** [AutoMapper/AutoMapper#1783]
Here's my issue, I'm trying to map both this entities, and I aways get an exception, even if I take off every property from the Model.

```
public int IdCorpoGestor { get; private set; }
    public string Nome { get; private set; }
    public string Email { get; private set; }
    public string Federacao { get; private set; }
    public DateTime DataIniMandato { get; private set; }
    public DateTime DataFimMandato { get; private set; }
    public string Telefone1 { get; private set; }
    public string Telefone2 { get; private set; }
    public int IdConselho { get; private set; }
    [ForeignKey("IdConselho")]
    public Conselho Conselho { get; private set; }
    public int IdTipo { get; private set; }
    [ForeignKey("IdTipo")]
    public Indicador Tipo { get; private set; }
    public bool Ativo { get; private set; }
}
```

**To:**

```
public class CorpoGestorDTO
{
    public int IdCorpoGestor { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Federacao { get; set; }
    public DateTime DataIniMandato { get; set; }
    public DateTime DataFimMandato { get; set; }
    public string Telefone1 { get; set; }
    public string Telefone2 { get; set; }
    public int IdConselho { get; set; }
    public int IdTipo { get; set; }
    public bool Ativo { get; set; }
    public string Tipo { get; set; }
}
```
**Mapping:**

```
 Mapper.Initialize(cfg => cfg.CreateMap<CorpoGestor, CorpoGestorDTO>()
            .ForMember(x => x.Tipo, y => y.MapFrom(s => s.Tipo.Nome)));
Calling Mapper from DataBase result:
```

**Calling Mapper from DataBase result:**
```
Mapper.Map<IEnumerable<CorpoGestor>, List<CorpoGestorDTO>>(result);
Exception:
```
**Exception:**
> Missing type map configuration or unsupported mapping

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by jbogard** [comment]
At the least the full description of the error message. That exception tells you which maps are missing.

**Comment by fals** [comment]
@jbogard Thinks got even more crazyest! If I change the order of the Mapping.Initialize this mapping that I post above works, but the one that uses a list of CorpoGestorDTO does't. The exception is very generic

Exception:

`Missing type map configuration or unsupported mapping.

Mapping types:
Conselho -> ConselhoResponse
Sigop.Domain.Entities.Administracao.Conselhos.Conselho -> Sigop.ApplicationService.DTO.Response.ConselhoResponse`

Here's the gist: [GIST For the issue](https://gist.github.com/fals/a03c7a11c9df9721b43a3cb16072a3c7)

**Comment by fals** [comment]
@lbargaoanu and @jbogard I did omit lot of interfaces that my source class are using for domain logic, if It needed I will provide them!

**Comment by jbogard** [comment]
You need to call Mapper.Initialize once and only once. Initialization is a one-time operation.

**Comment by fals** [comment]
@lbargaoanu and @jbogard You got It!! Never notice that I should pass everything inside one Mapper.Initialize once. The new api is realy different from 3.x, which I have been using for a while. Thank you! Solved!

**Comment by lbargaoanu** [comment]
This can be closed.
