### ISSUE TITLE
AutoMapper.AutoMapperMappingException.ToString() throws exception when InnerException is present

### ISSUE THREAD

**Issue by asiegler** [AutoMapper/AutoMapper#1786]
Calling ToString() on AutoMapper.AutoMapperMappingException with an InnerException present results in the InnerException being thrown.

For Example if I catch and AutoMapper.AutoMapperMappingException and that exception contains a NullReferenceException, if I call ToString() on the AutoMapperMappingException within my catch block it results in an unhandled NullReferenceException.

**Comment by lbargaoanu** [comment]
You must be on an older version.

**Comment by lbargaoanu** [comment]
This can be closed.
