### ISSUE TITLE
The binary operator Equal is not defined

### ISSUE THREAD

**Issue by stricq** [AutoMapper/AutoMapper#1787]
I have a couple objects defined with a property like this:

    public Dictionary<string, Dictionary<string, List<string>>> Exports { get; set; } // Version => Type => Name List

I am getting this error when validating mappings:

The binary operator Equal is not defined for the types 'System.Collections.Generic.KeyValuePair`2[System.String,System.Collections.Generic.List`1[System.String]]' and 'System.Collections.Generic.KeyValuePair`2[System.String,System.Collections.Generic.List`1[System.String]]'.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by lbargaoanu** [comment]
This can be closed.
