### ISSUE TITLE
AutoMapper ProjectTo results with "Unknown column 'Project3.x' in 'where clause'"

### ISSUE THREAD

**Issue by ndenkha** [AutoMapper/AutoMapper#1789]
Hi the issue is reported at SOF.

http://stackoverflow.com/questions/40521656/ef-odata-mysql-unknown-column-project3-x-in-where-clause

And this is the current mapping that I have.

```
public static void InitMapper()
{
	Mapper.Initialize(x =>
	{
		x.CreateMap<Market, MarketView>();
		x.CreateMap<Application, ApplicationView>();
		x.CreateMap<Role, RoleView>();
		x.CreateMap<AppUser, AppUserView>();
	});
}
```

**Comment by lbargaoanu** [comment]
But if you get the error even without ProjectTo, why ask a question here? :)

**Comment by ndenkha** [comment]
Hi, I opened the bug based on Jimmy's request.

https://lostechies.com/jimmybogard/2016/08/17/automapper-5-1-released/#comment-9553

**Comment by jbogard** [comment]
Do you get the error without AutoMapper? Using just Select instead of ProjectTo?

**Comment by ndenkha** [comment]
I do get it without AutoMapper, i.e. without ProjectTo. Sorry I forgot to close this, it's unrelated to AutoMapper.
