### ISSUE TITLE
Collection mapping behaviour change

### ISSUE THREAD

**Issue by colin-resdiary** [AutoMapper/AutoMapper#1791]
Hi,

We've recently upgraded from AutoMapper 3.2.1 to 5.1.1 and have noticed a behaviour change when mapping between collections. I just wanted to check if what I'm seeing now is the correct behaviour and how we would work round this issue.

We have a source DTO which has a collection of strings (```IEnumerable<string>```) and a destination object which has a list of strings (```List<string>```). In 3.2.1 when mapping from DTO, the destination collection is overwritten with contents of the DTO. But in 5.1.1 the two collections appear to be merged. See example below:

```
using System;
using System.Collections.Generic;
using AutoMapper;

namespace ConsoleApplication3
{
    public class Person
    {
        public string Name { get; set; }
        public List<String> Emails { get; set; }
    }

    public class PersonDto
    {
        public string Name { get; set; }
        public IEnumerable<String> ForwardEmails { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(
                cfg =>
                    cfg.CreateMap<PersonDto, Person>()
                        .ForMember(p => p.Emails, opt => opt.MapFrom(d => d.ForwardEmails))
                        //.ForMember(p => p.Emails, opt => opt.UseDestinationValue())
                        );

            var person = new Person { Emails = new List<string> {"1", "2"}, Name = "provider"};
            var personDto = new PersonDto { ForwardEmails = new List<string> {"3", "4"}, Name = "providerDto"};

            Mapper.Map(personDto, person);

            Console.WriteLine(person.Emails.Count);

            Console.ReadLine();
        }
    }
}
```

Uncommenting the following line makes the behaviour consistent between versions but it doesn't seem quite right to me. 

```
                        //.ForMember(p => p.Emails, opt => opt.UseDestinationValue())
```

Any help appreciated.

Thanks
Colin

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by colin-resdiary** [comment]
I've already tried going back to 3.2.1 and the myget build using the example above. 5.1.1 and myget have the same behaviour which is different from 3.2.1.

Thanks

**Comment by lbargaoanu** [comment]
The latest version is 5.2.0-alpha-01243.

**Comment by colin-resdiary** [comment]
Yeah, I've already tried that and it has the same behaviour as 5.1.1. Is this something you expect to be fixed in 5.2.0-alpha-01243?

**Comment by colin-resdiary** [comment]
I've just tried changing the above example and if the source and destination properties are of the same type i.e. ```List<string>``` or ```IEnumerable<string>``` then we get the correct behaviour. If they're different then we get what I would say was the wrong behaviour. Surely as they are both ```IEnumerable<T>``` then it shouldn't matter?

**Comment by lbargaoanu** [comment]
The code works (prints 2). Break in VS, go to the Modules windows and check the version.

**Comment by colin-resdiary** [comment]
My mistake.  I couldn't have done a clean and rebuild between changing versions. 
So if it's fixed in 5.2.0-alpha-01243 then any suggestions what I can do for now? This version doesn't seem to be production-ready and we are looking at releasing our software over the next week or so.

**Comment by lbargaoanu** [comment]
It's as good as the version you're using.

**Comment by colin-resdiary** [comment]
OK. Thanks. Can you point me in the direction of the fix for this issue?

**Comment by lbargaoanu** [comment]
#1632

**Comment by lbargaoanu** [comment]
This can be closed.
