### ISSUE TITLE
Problems when updating Entities with EF Core

### ISSUE THREAD

**Issue by SamiAl90** [AutoMapper/AutoMapper#1792]
Hello,

I am having a problem for that I cannot find a "proper" solution. I spent hours googling it already but couldn't find anything that would make this work properly.

Let's say I have an entity that looks like this

```
 public class Vendor : TrackedEntity, IEntity
    {
        public Vendor()
        {
            Products = new List<Product>();
            Adjustments = new List<MaintenanceAdjustmentRate>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public ICollection<Product> Products { get; set; }

        public ICollection<MaintenanceAdjustmentRate> Adjustments { get; set; }
}
```

Now I use automapper to map it to the DTO and vice versa. When I create new entities, everything works fine. Even if I add new products to the collection of the vendor. When updating, it doesn't work because the objects entityframework receives, are not the same as in the databasecontext where the entities are tracked and ef core tries to create the products that are already in the database. I found some suggestions that say I should configure the mapper to either ignore nested objects/collections or call the use destination value in the mapping configuration so it doesn't map the nested collection / object back to the entitiy. 

Is there another way to make automapper and ef core work together propertly?

Thank you for this great tool though.

**Comment by lbargaoanu** [comment]
Duplicate of #1695.

**Comment by SamiAl90** [comment]
I see, there is no real solution. Thank you.

**Comment by lbargaoanu** [comment]
You can use AM in this case, but it won't handle the EF stuff for you. So you'd have to mix and match.

**Comment by jbogard** [comment]
And in general, don't use AutoMapper to reverse map into complex entities.
That problem is far more difficult (and limiting). Simple scenarios yes,
but anything past a single entity is just asking for trouble.
