### ISSUE TITLE
'AutoMapper' already has a dependency defined for 'NETStandard.Library' on VSO

### ISSUE THREAD

**Issue by mtrax** [AutoMapper/AutoMapper#1793]
Hi,

there is a problem in a build step when it's triggered on VSO. In my case, I receive this error message when the step tries to create a NuGet package:

`'AutoMapper' already has a dependency defined for 'NETStandard.Library'.
System.Exception: Unexpected exit code 1 returned from tool NuGet.exe`

`Preparing task execution handler.
Executing the powershell script: C:\a\_tasks\NuGetPackager_333b11bd-d341-40d9-afcf-b32d5ce6f24b\0.1.69\NuGetPackager.ps1
C:\LR\Mms\Services\Mms\TaskAgentProvisioner\Tools\agents\2.109.1\externals\nuget\NuGet.exe pack "C:\a\1\s\[Project]\[Project].csproj" -OutputDirectory "C:\a\1\s" -Properties Configuration=release -IncludeReferencedProjects 
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from '[Project].csproj'.
Packing files from 'C:\a\1\s\[Project]\bin\Release'.
'AutoMapper' already has a dependency defined for 'NETStandard.Library'.
System.Exception: Unexpected exit code 1 returned from tool NuGet.exe
   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.InvokeToolCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PowerShell script completed with 1 errors.`

I'm using:

**.NET 4.5.2**
**Nuget 3.3.0.212 / 3.3.0** (I get the same error with **3.4.4** too)

I hope this information helps.

Thanks in advance!

Mario

**Comment by jbogard** [comment]
What version of NuGet is VSO using?

**Comment by mtrax** [comment]
VSO is using Nuget 3.3.0.212

**Comment by jbogard** [comment]
http://stackoverflow.com/questions/39352013/nuget-fails-to-restore-netstandard-libary-for-netstandard1-2-in-vnext-build-agen

?

**Comment by mtrax** [comment]
I only have two 4.5.2 projects in my solution and I don't use any NetStandard library or reference. For example, I use SimpleInjector too and the build/packaging works fine.

**Comment by mtrax** [comment]
Yeah sure, 

I could reproduce on my second VS team services account. Here are the steps:

You need this extension: [Package Management](https://marketplace.visualstudio.com/items?itemName=ms.feed)

- Install Package Management extension
- Create a new Windows Class Library project for .NET 4.5.2
- Add Automapper through NuGet
- Push the code
- Create a new build definition(use the Visual Studio template)
- Add a new build step (select NuGet Packager) and save the build definition
- Trigger a new build

**Comment by jbogard** [comment]
Well I got the same error. But if I run NuGet pack locally, it runs just fine:

<img width="924" alt="screen shot 2016-11-18 at 4 15 39 pm" src="https://cloud.githubusercontent.com/assets/104498/20448571/f6487738-ade4-11e6-997c-74212e6b07d2.png">

But I get an error at the server:

<img width="1351" alt="screen shot 2016-11-18 at 4 16 53 pm" src="https://cloud.githubusercontent.com/assets/104498/20448595/2213a982-ade5-11e6-839f-46ca1ea8af5a.png">

I can't tell what version that specific nuget packager extension uses. I can tell you that on my local machine, I'm using version 3.4.4.1321.

I think the next course is to open a bug for that extension. On your side, I'd just include NuGet in your repository, and call out to it. That way you're not dependent on someone else's NuGet version.

**Comment by jbogard** [comment]
I got it to work! I included the NuGet client, the latest, and configured VSTS NuGet Packager step to point to the correct NuGet path:

<img width="1128" alt="screen shot 2016-11-18 at 4 44 20 pm" src="https://cloud.githubusercontent.com/assets/104498/20449346/6468b2c8-adae-11e6-8c85-0ffb4f876632.png">

Give this a shot, it's better than I think this other solution I saw, which was put NuGet on the agent somewhere:

http://blog.majcica.com/2016/11/02/custom-nuget-exe-for-tfs-2015-build/

Our teams do this anyway - the NuGet client *always* has problems.

**Comment by mtrax** [comment]
Yes man, you nailed it!

I followed your advice and now it works!

Thank you!

**Comment by joswalt** [comment]
This due to the version of the NuGet that you have installed or the version the build server has installed. If the NuGet version is older than 3.4, you will get this error because NuGet did not handle dependencies correctly broken out by the version .NET Framework. Before v3.4, if there were dependencies NuGet would try to install them whether your project targeted that version or not.
