### ISSUE TITLE
Cannot restrict mapping to base type

### ISSUE THREAD

**Issue by RobertBune** [AutoMapper/AutoMapper#1795]
I have been using AutoMapper 3.2.1 for some time and would like to upgrade so I can take advantage of new and improved feature, most notably improved inheritance handling using IncludeBase.

I have identified three breaking changes when upgrading to 4.1.1 or 5.1.1, the first of which is when I try to restrict the mapping to just the source base class.

In my scenario I have EF POCO classes which include child entities, I then have DTO classes for each entity and a derived class which extends the parent entity with its child entities.

```
namespace MapTests.POCO
{
    public class A
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public List<B> Children { get; set; }
    }

    public class B
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
    }
}
```

```
namespace MapTests.DTO
{
    public class A
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
    }

    public class B
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
    }

    public class AwithB: A
    {
        public List<B> Children { get; set; }
    }
}
```

When my API receives an updated instance of AwithB DTO I want to validate the parent and child entities in turn and update their respective EF POCO classes. I can do this in 3.2.1 by restricting the scope using the source type of the Map method.

```
namespace MapTests
{
    public class ABMapper
    {
        private readonly IMappingEngine _mapper;

        public ABMapper()
        {
            var config = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);

            config.CreateMap<POCO.A, DTO.A>()
                .ReverseMap();

            config.CreateMap<POCO.B, DTO.B>()
                .ReverseMap();

            config.CreateMap<POCO.A, DTO.AwithB>()
                .IncludeBase<POCO.A, DTO.A>()
                .ReverseMap();

            _mapper = new MappingEngine(config);
        }

        public TDestination Map<TSource, TDestination>(TSource source)
        {
            return _mapper.Map<TSource, TDestination>(source);
        }

        public void Map<TSource, TDestination>(TSource source, TDestination destination)
        {
            _mapper.Map<TSource, TDestination>(source, destination);
        }
    }
}
```

Then in my API controller do the following.

```
        mapper.Map<DTO.A, POCO.A>(dtoAwithB, pocoA);
```

In 3.2.1 the pocoA.Children are untouched as they are not a member of type DTO.A, but in 4.1.1 and 5.1.1 the TSource is ignored and instead the type of dtoAwithB is (DTO.AwithB) is used to determine the mapping to use.

Is thee any easy way to restrict this in the latest code?

**Comment by jbogard** [comment]
No, unfortunately at the moment. AutoMapper with the latest version maps based on the runtime type (which it needs to based on a whole host of other scenarios). The problem is there are scenarios where you want the runtime type (ORM proxy classes), and scenarios you don't (yours).

**Comment by lbargaoanu** [comment]
It's possible using a [custom object mapper](https://github.com/AutoMapper/AutoMapper/blob/d87bca14548bfbe90f694ec09f50bed8ce0d617b/src/UnitTests/Mappers/CustomMapperTests.cs#L95). But it's somewhat more complex.

**Comment by lbargaoanu** [comment]
I spoke too soon. You only receive the runtime types in the Match method, so it's the same. Unless we would change that to receive also the compile time types.

**Comment by RobertBune** [comment]
I appreciate the quick responses but it is disappointing to learn that AutoMapper can no longer support restricting the mapping to a base class. It looks like I am stuck on 3.2.1 for the time being, especially as I also have an issue with the removal of ResolutionContext.Parent ([#1390](https://github.com/AutoMapper/AutoMapper/issues/1390)) which I required to access property annotations which my DateTimeConverter needs.

@jbogard, it sounds like the implementation is not likely to change to accommodate my use case so should I just close this issue?

**Comment by lbargaoanu** [comment]
[ForAllPropertyMaps](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=ForAllPropertyMaps) would help for the property annotations.

**Comment by jbogard** [comment]
What are you actually trying to do in your resolver?

**Comment by RobertBune** [comment]
I thought I would post the whole gory details!

In the database I have whole date values and timestamps, the timestamps are typically stored as UTC and should be adjusted to the users time zone, but a few specialist cases should be treated as local time and displayed as stored in all time zones. Entity Framework maps all three types to DateTime with DateTimeKind.Unspecified. Our client application expects date only values to be in ISO 8601 format yyyy-MM-dd and timestamps as yyyy-MM-ddTHH:mm:ss.fff. If the timestamp is relative to UTC then it should also have a 'Z' suffix.

```
{
    "LastModified": "2016-11-18T20:00:57.344Z",
    "EffectiveDate": "2000-01-01",
    "EventDate":"2000-01-01T09:00:00",
}
```

To achieve this I map my Entity Framework generated POCO classes to DTOs with date only values converted to yyyy-MM-dd formatted strings and DateTime properties with DateTimeKind.Utc applied to timestamps which are stored as UTC. I use two custom converter classes classes for this.

DateStringTypeConverter which maps POCO DateTime to DTO string.

```
using System;
using System.Globalization;
using AutoMapper;

namespace MapTests
{
    public class DateStringTypeConverter :
        ITypeConverter<DateTime?, string>,
        ITypeConverter<DateTime, string>,
        ITypeConverter<string, DateTime?>,
        ITypeConverter<string, DateTime>
    {
        public string Convert(ResolutionContext context)
        {
            if (context.IsSourceValueNull)
                return default(string);
            var value = (DateTime) context.SourceValue;
            return value.Date.ToString("yyyy-MM-dd");
        }

        DateTime? ITypeConverter<string, DateTime?>.Convert(ResolutionContext context)
        {
            if (context.IsSourceValueNull || (context.SourceValue.ToString() == ""))
                return default(DateTime?);
            var value = context.SourceValue.ToString();
            return DateTime.ParseExact(value, "yyyy-MM-dd", CultureInfo.InvariantCulture);
        }

        DateTime ITypeConverter<string, DateTime>.Convert(ResolutionContext context)
        {
            if (context.IsSourceValueNull || (context.SourceValue.ToString() == ""))
                return default(DateTime);
            var value = context.SourceValue.ToString();
            return DateTime.ParseExact(value, "yyyy-MM-dd", CultureInfo.InvariantCulture);
        }
    }
}
```

And DateTimeConverter which tests the DTO properties for a DateTimeKindAttribute annotation and applies it to the mapped DateTime value.

```
using System;
using System.Reflection;
using AutoMapper;

namespace MapTests
{
    public class DateTimeConverter :
        ITypeConverter<DateTime?, DateTime?>,
        ITypeConverter<DateTime?, DateTime>,
        ITypeConverter<DateTime, DateTime?>,
        ITypeConverter<DateTime, DateTime>
    {
        DateTime? ITypeConverter<DateTime, DateTime?>.Convert(ResolutionContext context)
        {
            return Apply(context);
        }

        DateTime ITypeConverter<DateTime, DateTime>.Convert(ResolutionContext context)
        {
            return Apply(context);
        }

        DateTime? ITypeConverter<DateTime?, DateTime?>.Convert(ResolutionContext context)
        {
            return context.IsSourceValueNull ? default(DateTime?) : Apply(context);
        }

        DateTime ITypeConverter<DateTime?, DateTime>.Convert(ResolutionContext context)
        {
            return context.IsSourceValueNull ? default(DateTime) : Apply(context);
        }

        private static DateTime Apply(ResolutionContext context)
        {
            // Get source value.
            var dt = (DateTime) context.SourceValue;
            // Check whether these properties have the DateTimeKindAttribute.
            // DestinationType is not available in AutoMapper 5.x
            var attr = context.DestinationType.GetCustomAttribute<DateTimeKindAttribute>();
            // If no attribute simply return the SourceValue, else set the appropriate DateTimeKind.
            return attr == null ? dt : DateTime.SpecifyKind(dt, attr.Kind);
        }
    }
}
```

```
using System;
using System.Linq;
using System.Reflection;

namespace MapTests
{
    [AttributeUsage(AttributeTargets.Property)]
    public class DateTimeKindAttribute : Attribute
    {
        private readonly DateTimeKind _kind;

        public DateTimeKindAttribute(DateTimeKind kind)
        {
            _kind = kind;
        }

        public DateTimeKind Kind
        {
            get { return _kind; }
        }

        public static void Apply(object entity)
        {
            if (entity == null)
                return;

            // Find all properties that are of type DateTime or DateTime?;
            var properties = entity.GetType().GetProperties()
                .Where(x => (x.PropertyType == typeof(DateTime))
                            || (x.PropertyType == typeof(DateTime?)));

            foreach (var property in properties)
            {
                // Check whether these properties have the DateTimeKindAttribute;
                var attr = property.GetCustomAttribute<DateTimeKindAttribute>();
                if (attr == null)
                    continue;

                var dt = property.PropertyType == typeof(DateTime?)
                    ? (DateTime?) property.GetValue(entity)
                    : (DateTime) property.GetValue(entity);

                if (dt == null)
                    continue;

                // If the value is not null set the appropriate DateTimeKind;
                property.SetValue(entity, DateTime.SpecifyKind(dt.Value, attr.Kind));
            }
        }
    }
}
```

I configure these in my BaseMapper class which also provides a couple of overloads for the Map() method which support an optional effective date filter.

```
using System;
using AutoMapper;
using AutoMapper.Mappers;

namespace MapTests
{
    public class BaseMapper
    {
        protected IMappingEngine _mapper;
        protected ConfigurationStore _config;

        protected BaseMapper()
        {
            _config = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);

            // Handle mapping EF DateTime whole date fields to DTO string format yyyy-MM-dd
            _config.CreateMap<DateTime?, string>().ConvertUsing<DateStringTypeConverter>();
            _config.CreateMap<DateTime, string>().ConvertUsing<DateStringTypeConverter>();
            _config.CreateMap<string, DateTime?>().ConvertUsing<DateStringTypeConverter>();
            _config.CreateMap<string, DateTime>().ConvertUsing<DateStringTypeConverter>();

            // Handle applying DateTimeKind attribute to EF dates when mapping to DTO
            _config.CreateMap<DateTime?, DateTime?>().ConvertUsing<DateTimeConverter>();
            _config.CreateMap<DateTime?, DateTime>().ConvertUsing<DateTimeConverter>();
            _config.CreateMap<DateTime, DateTime?>().ConvertUsing<DateTimeConverter>();
            _config.CreateMap<DateTime, DateTime>().ConvertUsing<DateTimeConverter>();
        }

        public TDestination Map<TSource, TDestination>(TSource source, DateTime? effectiveDate = null)
        {
            if (effectiveDate != null)
                return _mapper.Map<TSource, TDestination>(source, opt => opt.Items["EffectiveDate"] = effectiveDate);
            return _mapper.Map<TSource, TDestination>(source);
        }

        public void Map<TSource, TDestination>(TSource source, TDestination destination, DateTime? effectiveDate = null)
        {
            if (effectiveDate != null)
                _mapper.Map(source, destination, opt => opt.Items["EffectiveDate"] = effectiveDate);
            else
                _mapper.Map(source, destination);
        }
    }
}
```

Below is a simplifed but typical scenario for an Event entity with SubEvent.

The physical DB model POCOs

```
using System;
using System.Collections.Generic;

namespace MapTests.POCO
{
    public class Event
    {
        public Event()
        {
            SubEvents = new List<SubEvent>();
        }

        public int Id { get; set; }
        public DateTime LastModified { get; set; }
        public DateTime EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public DateTime EventDate { get; set; }
        public IList<SubEvent> SubEvents { get; set; }
    }

    public class SubEvent
    {
        public int ParentId { get; set; }
        public int Id { get; set; }
        public DateTime LastModified { get; set; }
        public DateTime EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public DateTime SubEventDate { get; set; }
    }
}
```

The DTOs exposed by the public API and serialzed as JSON.

```
using System;
using System.Collections.Generic;

namespace MapTests.DTO
{
    public class Event
    {
        public int Id { get; set; }
        [DateTimeKind(DateTimeKind.Utc)]
        public DateTime LastModified { get; set; }
        public string EffectiveDate { get; set; }
        public string ExpirationDate { get; set; }
        public DateTime EventDate { get; set; }
    }

    public class EventInFull : Event
    {
        public IList<SubEvent> SubEvents { get; set; }
    }

    public class SubEvent
    {
        public int Id { get; set; }
        [DateTimeKind(DateTimeKind.Utc)]
        public DateTime LastModified { get; set; }
        public string EffectiveDate { get; set; }
        public string ExpirationDate { get; set; }
        public DateTime SubEventDate { get; set; }
    }
}
```

The EventMapper which 

```
using System;
using System.Linq;
using AutoMapper;

namespace MapTests
{
    public class EventMapper : BaseMapper
    {
        public EventMapper()
        {
            _config.CreateMap<POCO.Event, DTO.Event>();

            _config.CreateMap<DTO.Event, POCO.Event>();

            _config.CreateMap<POCO.Event, DTO.EventInFull>()
                .IncludeBase<POCO.Event, DTO.Event>()
                .ForMember(dest => dest.SubEvents, opt => opt.ResolveUsing(res =>
                {
                    var src = (POCO.Event) res.Context.SourceValue;
                    // Chech if effective date filter should be applied
                    if (res.Context.Options.Items.ContainsKey("EffectiveDate"))
                    {
                        var effectiveDate = (DateTime) res.Context.Options.Items["EffectiveDate"];
                        return
                            src.SubEvents.Where(
                                x =>
                                    (x.EffectiveDate <= effectiveDate) &&
                                    (!x.ExpirationDate.HasValue || (x.ExpirationDate.Value > effectiveDate)));
                    }
                    // Else only filter soft deleted records (expired on effective date)
                    return
                        src.SubEvents.Where(
                            x => !x.ExpirationDate.HasValue || (x.ExpirationDate.Value > x.EffectiveDate));
                }));

            _config.CreateMap<DTO.EventInFull, POCO.Event>()
                .IncludeBase<DTO.Event, POCO.Event>()
                // I would rather not do below opt.Ignore for every child in every POCO
                .ForMember(x => x.SubEvents, opt => opt.Ignore());

            _config.CreateMap<POCO.SubEvent, DTO.SubEvent>();

            _config.CreateMap<DTO.SubEvent, POCO.SubEvent>();

            _mapper = new MappingEngine(_config);
        }
    }
}
```

And finally the test program.

```
using System;
using System.Globalization;
using System.Linq;
using Newtonsoft.Json;

namespace MapTests
{
    public class Program
    {
        static void Main(string[] args)
        {
            // Build sample Event, in the real application this would POCO would be from Entity Framework
            var pocoEvent = new POCO.Event
            {
                Id = 71,
                LastModified = DateTime.UtcNow,
                EffectiveDate = DateTime.ParseExact("2000-01-01", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                ExpirationDate = null,
                EventDate = DateTime.ParseExact("2000-01-01T09:00", "yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
            };
            pocoEvent.SubEvents.Add(new POCO.SubEvent
            {
                ParentId = pocoEvent.Id,
                Id = 85,
                LastModified = DateTime.UtcNow,
                EffectiveDate = DateTime.ParseExact("2000-01-01", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                ExpirationDate = null,
                SubEventDate = DateTime.ParseExact("2000-01-01T12:00", "yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
            });
            pocoEvent.SubEvents.Add(new POCO.SubEvent
            {
                ParentId = pocoEvent.Id,
                Id = 97,
                LastModified = DateTime.UtcNow,
                EffectiveDate = DateTime.ParseExact("2000-01-05", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                ExpirationDate = DateTime.ParseExact("2000-01-05", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                SubEventDate = DateTime.ParseExact("2000-01-05T12:00", "yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
            });
            pocoEvent.SubEvents.Add(new POCO.SubEvent
            {
                ParentId = pocoEvent.Id,
                Id = 216,
                LastModified = DateTime.UtcNow,
                EffectiveDate = DateTime.ParseExact("2000-01-01", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                ExpirationDate = DateTime.ParseExact("2100-01-01", "yyyy-MM-dd", CultureInfo.InvariantCulture),
                SubEventDate = DateTime.ParseExact("2000-01-01T12:00", "yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture)
            });

            // Web API gets EF entities and maps to external DTOs for client processing
            var mapper = new EventMapper();
            var dtoEventOut = mapper.Map<POCO.Event, DTO.EventInFull>(pocoEvent, DateTime.Today);
            var jsonEvent = JsonConvert.SerializeObject(dtoEventOut);
            // Client side processing then return to Web API
            var dtoEventIn = JsonConvert.DeserializeObject<DTO.EventInFull>(jsonEvent);
            // Using base type in TSource does not restrict mapping in AutoMapper 4.x and 5.x, child entities will be overwritten.
            mapper.Map<DTO.Event, POCO.Event>(dtoEventIn, pocoEvent);
            // I want to validate and apply child entities individually
            foreach (var child in dtoEventIn.SubEvents)
            {
                var pocoChild = pocoEvent.SubEvents.FirstOrDefault(x => x.Id == child.Id);
                if (pocoChild == null)
                {
                    pocoChild = mapper.Map<DTO.SubEvent, POCO.SubEvent>(child);
                    pocoEvent.SubEvents.Add(pocoChild);
                }
                else
                {
                    mapper.Map<DTO.SubEvent, POCO.SubEvent>(child, pocoChild);
                }
            }
        }
    }
}
```

The test Program shows how I handle mapping the hierarchy entity by entity. I am using an opt.Ignore() to exclude the child SubEvents when mapping bach from the DTO to the POCO, this is workable but cumbersome for entities which have many child relationships. There is also a risk that a new DB relationship gets created and the mapper update forgotten resulting in possible data corruption.

The DateTimeConverter needs to be able to access the destination property annotations. This is no longer possible in 5.x now that DestinationType has been removed from the ResolutionContext.

I am also unsure in 5.x the best way to manage the base and derived mapper configuration. It appears that once created a MapperConfiguration instance cannot be amended. My current approach in 5.x is to use a BaseProfile and then extend this with EventProfile. I then remove the constructor from my BaseMapper and leave just the protected IMapper instance and overloaded Map methods. The EventMapper then becomes.

```
using AutoMapper;

namespace MapTests
{
    public class EventMapper : BaseMapper
    {
        public EventMapper()
        {
            var config = new MapperConfiguration(cfg => {
                cfg.AddProfile<EventProfile>();
            });

            _mapper = config.CreateMapper();
        }
    }
}
```

Hope that is not too much information!

**Comment by TylerCarlson1** [comment]
https://github.com/TylerCarlson1/Automapper.Collection can handle the SubEvent list updating for you.
Then maybe you don't have to ignore and do the manual mapping.

Or I could be wrong in what you are trying to achieve.  (I only read the thing 1.5 times)

**Comment by TylerCarlson1** [comment]
Ok the AutoMapper.Collection won't help cause it will do deletes and that's not what you need :(
Unless you want to fork and remove the delete element, then it should at least save you having to map children explicitly, if you want.

Another alternative is to use ForAllPropertyMaps and ignore maps that have collections going from DTO to EF which will replace your inherit class to ignore.
And with ForAllPropertyMaps you can get the annotation from the ProperyInfo and set up the map without having to read the attribute every time.  I will map over much faster because of that.

It should be possible to mess with the configuration to ignore based on rules you can set that should meet you requirements.  It's just a different way then what 3.2.1 could handle.

**Comment by RobertBune** [comment]
@TylerCarlson1 yes, I cannot use AutoMapper.Collections for a number of reasons. In some case the DTO child collection is partial and I would therefore not want it to delete the missing records; in other cases updates should be converted to a new record with the original having an expiration date applied; plus updates and creates often require additional validation and some post mapping adjustments.

I could possibly fork AutoMapper.Collection to try and meet my requirement but I would not want to take what are business rules and embedding them in AutoMapper extensions. This would obfuscate the business logic and diverge AutoMapper from what it does best.

@lbargaoanu also mention using ForAllPropertyMaps, I did take a look at this but I was not sure how I could apply it to solve my issue. Please could you provide an example of how to configure this.

I typically want child collections included when going from EF POCO to DTO, it is only on the return mapping I would typically avoid want to avoid these. It looks like ForAllPropertyMaps is a global configuration option. Can I filter this so it only applies to DTO to POCO mappings? I assume if I wanted to override this I can do using an explicit ForMember mapping?

p.s. The wiki documentation for [Custom type converters](https://github.com/AutoMapper/AutoMapper/wiki/Custom-type-converters) needs amending as this implies type information is still available in the RequestContext, The final example has context.SourceType which is not valid.

```
    public class TypeTypeConverter : ITypeConverter<string, Type>
    {
        public Type Convert(string source, Type destination, ResolutionContext context)
        {
              return context.SourceType;
        }
    }
```

**Comment by TylerCarlson1** [comment]
For AllPropertyMaps here's an example of how to do DateTime attributes and ignore poco collections
**Note:** This is by no means works for all cases, like DateTime?.
```
cfg.ForAllPropertyMaps(
    pm => pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
    (pm, expression) =>
    {
        var specifyKind = typeof(DateTime).GetMethod("SpecifyKind", BindingFlags.Static | BindingFlags.Public);
        var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
        var src = Expression.Parameter(typeof(object));
        var dateTime = Expression.PropertyOrField(Expression.TypeAs(src, pm.SourceMember.DeclaringType),
            pm.DestinationProperty.Name);
        var getSpecifyKind = Expression.Call(null, specifyKind, dateTime, Expression.Constant(kind));
        var mapFrom = Expression.Lambda(getSpecifyKind, src) as Expression<Func<object, DateTime>>;
        expression.MapFrom(mapFrom);
    });
cfg.ForAllPropertyMaps(pm =>
{
    var destProp = (pm.DestinationProperty as PropertyInfo).PropertyType;
    return destProp.GetInterfaces().Any(i => i.Name.Contains("ICollection")) &&
           destProp.GetGenericArguments()[0].Namespace.Contains("POCO");
}, (pm, epr) => epr.Ignore());
```

As far as the soft deletes with experation date [EF Filters](https://lostechies.com/jimmybogard/2014/05/29/missing-ef-feature-workarounds-filters/) might help you achieve that.
I've never used it myself, but it looks like a global filtering you would want for retrieving values.

**Comment by RobertBune** [comment]
@TylerCarlson1 many thanks for the example above also the link to EF Filters.

I have spent the day wrestling with implementing support for DateTime? and miserably failing. I have not used Linq expressions before and so far all my implementation attempts have failed. It all seems rather complex compared with my old converter.

Any chance you could show me how to handle DateTime? or point me towards some useful links?

**Comment by lbargaoanu** [comment]
There is no need for expressions. You can use ResolveUsing.

**Comment by TylerCarlson1** [comment]
@lbargaoanu is correct.  You can use your existing code and just call the resolver functions to handle the actual translation.  How you get the property maps to do what you want when you have a DateTime translated is up to you.  I just got a solution to work to show you.  I don't use ForAllPropertyMaps myself.

Yes expression generation is an absolute NIGHTMARE to work with.  But that's the price you pay for getting better overall performance in AutoMapper.

**Comment by RobertBune** [comment]
@lbargaoanu I have tried multiple implementations of ResolveUsing and cannot get it to pass the DateTimeKind paramerter to my custom IValueResolver or find a lambda function which will work. 

Here is my latest attempt which results in an ArgumentException.

```
ForAllPropertyMaps(
    pm => pm.DestinationPropertyType == typeof(DateTime) && pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
    (pm, expression) =>
        expression.ResolveUsing((src, dest, member, ctx) =>
        {
            var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
            return DateTime.SpecifyKind((DateTime) member, kind);
        })
    );
```

**Comment by lbargaoanu** [comment]
That looks like a bug. Try 

		c.ForAllPropertyMaps(
			pm => pm.DestinationPropertyType == typeof(DateTime) && pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
			(pm, expression) => 
			{
				var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
				var resolver = new Resolver(kind);
				expression.ResolveUsing<object, object, DateTime, DateTime>(resolver, pm.SourceMember.Name);
			}
		);
		
            class Resolver : IMemberValueResolver<object, object, DateTime, DateTime>
		{
			DateTimeKind _kind;
			
			public Resolver(DateTimeKind kind)
			{
				_kind = kind;
			}
			
			public DateTime Resolve(object source, object destination, DateTime sourceMember, DateTime destinationMember, ResolutionContext context)
			{
				return DateTime.SpecifyKind(sourceMember, _kind);
			}
		}

Or something like that :) We'll see about that bug.

**Comment by RobertBune** [comment]
@lbargaoanu fantastic, that works a charm for both my DateTime and DateTime?

I really appreciate yours and @TylerCarlson1 assistance.

**Comment by lbargaoanu** [comment]
What if the DateTime? is null? :)

**Comment by RobertBune** [comment]
I am using a second resolver and property map.

```
    ForAllPropertyMaps(
            pm => pm.DestinationPropertyType == typeof(DateTime?) && pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
            (pm, expression) =>
            {
                var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
                var resolver = new NullResolver(kind);
                expression.ResolveUsing<object, object, DateTime?, DateTime?>(resolver, pm.SourceMember.Name);
           }
        );

    class NullResolver : IMemberValueResolver<object, object, DateTime?, DateTime?>
    {
        DateTimeKind _kind;

        public NullResolver(DateTimeKind kind)
        {
            _kind = kind;
        }

        public DateTime? Resolve(object source, object destination, DateTime? sourceMember, DateTime? destinationMember, ResolutionContext context)
        {
            return sourceMember.HasValue ? DateTime.SpecifyKind(sourceMember.Value, _kind) : default(DateTime?);
        }
    }
```

I will probably play around a bit with it to see if I can combine the resolvers in some way. Initially I tried this by just adding the IMemberValueResolver<object, object, DateTime?, DateTime?> interface and its implementation method to your Resolver class but this gave an exception.

**Comment by RobertBune** [comment]
@lbargaoanu and @TylerCarlson1, as already stated I very much appreciate your assistance. I hope you don't mind me labouring this issue. I am nearly there but have another niggle with how best to combine my common base configuration with my functional mappers.

I have some common mapper methods which handle my effective date filter and some global configuration for DateTime and child POCO collections as described above. Because the MapperConfiguration is immutable and calling virtual methods in constructors is bad practice I have opted to split the configuration out in to a Profile. So my base looks like this.

```
    public abstract class BaseMapper
    {
        protected IMapper Mapper;

        public TDestination Map<TSource, TDestination>(TSource source)
        {
            return Mapper.Map<TSource, TDestination>(source);
        }

        public TDestination Map<TSource, TDestination>(TSource source, DateTime effectiveDate)
        {
            return Mapper.Map<TSource, TDestination>(source, opt => opt.Items["EffectiveDate"] = effectiveDate);
        }

        public void Map<TSource, TDestination>(TSource source, TDestination destination)
        {
            Mapper.Map(source, destination);
        }

        public void Map<TSource, TDestination>(TSource source, TDestination destination, DateTime effectiveDate)
        {
            Mapper.Map(source, destination, opt => opt.Items["EffectiveDate"] = effectiveDate);
        }
    }

    public class BaseProfile : Profile
    {
        public BaseProfile()
        {
            // Handle mapping EF DateTime whole date fields to DTO string format yyyy-MM-dd
            CreateMap<DateTime?, string>().ConvertUsing<DateStringTypeConverter>();
            CreateMap<DateTime, string>().ConvertUsing<DateStringTypeConverter>();
            CreateMap<string, DateTime?>().ConvertUsing<DateStringTypeConverter>();
            CreateMap<string, DateTime>().ConvertUsing<DateStringTypeConverter>();

            // Handle applying DateTimeKind attribute to EF dates when mapping to DTO
            ForAllPropertyMaps(
                    pm => pm.DestinationPropertyType == typeof(DateTime) && pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
                    (pm, expression) =>
                    {
                        var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
                        var resolver = new DateTimeResolver(kind);
                        expression.ResolveUsing(resolver, pm.SourceMember.Name);
                    }
                );

            ForAllPropertyMaps(
                    pm => pm.DestinationPropertyType == typeof(DateTime?) && pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>() != null,
                    (pm, expression) =>
                    {
                        var kind = pm.DestinationProperty.GetCustomAttribute<DateTimeKindAttribute>().Kind;
                        var resolver = new NullableDateTimeResolver(kind);
                        expression.ResolveUsing(resolver, pm.SourceMember.Name);
                    }
                );

            // Exclude child POCOs when mapping from DTO to POCO            
            ForAllPropertyMaps(pm =>
            {
                var destProp = (pm.DestinationProperty as PropertyInfo).PropertyType;
                return destProp.GetInterfaces().Any(i => i.Name.Contains("ICollection")) &&
                       destProp.GetGenericArguments()[0].Namespace.Contains("POCO");
            }, (pm, expression) => expression.Ignore());
        }
    }
```

Then taking my Event example I create the following derived mapper and profile classes.

```
    public class EventMapper : BaseMapper
    {
        public EventMapper()
        {
            var config = new MapperConfiguration(cfg => {
                cfg.AddProfile<BaseProfile>();
                cfg.AddProfile<EventProfile>();
            });

            Mapper = config.CreateMapper();
        }
    }

    public class EventProfile : Profile
    {
        public EventProfile()
        {
            CreateMap<Event, EventDto>()
                .ForMember(dest => dest.LastModified, opt => opt.MapFrom(src => src.ModifiedOn))
                .ForMember(dest => dest.LastReviewed, opt => opt.MapFrom(src => src.ReviewedOn));

            CreateMap<EventDto, Event>()
                .ForMember(dest => dest.ModifiedOn, opt => opt.MapFrom(src => src.LastModified))
                .ForMember(dest => dest.ReviewedOn, opt => opt.MapFrom(src => src.LastReviewed));

            CreateMap<Event, EventInFullDto>()
                .IncludeBase<Event, EventDto>()
                .ForMember(dest => dest.SubEvents, opt => opt.ResolveUsing((src, dest, destMem, ctx) =>
                {
                    // Check if effective date filter should be applied
                    if (ctx.Options.Items.ContainsKey("EffectiveDate"))
                    {
                        var effectiveDate = (DateTime)ctx.Options.Items["EffectiveDate"];
                        return
                            src.SubEvents.Where(
                                x =>
                                    (x.EffectiveDate <= effectiveDate) &&
                                    (!x.ExpirationDate.HasValue || (x.ExpirationDate.Value > effectiveDate)));
                    }
                    // Else only filter soft deleted records (expired on effective date)
                    return
                        src.SubEvents.Where(
                            x => !x.ExpirationDate.HasValue || (x.ExpirationDate.Value > x.EffectiveDate));
                }));

            CreateMap<SubEvent, SubEventDto>()
                .ForMember(dest => dest.LastModified, opt => opt.MapFrom(src => src.ModifiedOn))
                .ForMember(dest => dest.LastReviewed, opt => opt.MapFrom(src => src.ReviewedOn));

            CreateMap<SubEventDto, SubEvent>()
                .ForMember(dest => dest.ModifiedOn, opt => opt.MapFrom(src => src.LastModified))
                .ForMember(dest => dest.ReviewedOn, opt => opt.MapFrom(src => src.LastReviewed));
        }
    }
```

When I run my test program the Event mapping works but when I inspect the result I see the base Converters have worked but the ForAllPropertyMaps have been ignored. If however I amend the above so that EventProfile extends BaseProfile and then amend EventMapper to only apply the EventProfile all works fine.

```
    public class EventMapper : BaseMapper
    {
        public EventMapper()
        {
            var config = new MapperConfiguration(cfg => {
                cfg.AddProfile<EventProfile>();
            });

            Mapper = config.CreateMapper();
        }
    }

    public class EventProfile : BaseProfile
    {
        ...
    }
```

I was not expecting this, I thought I would be able to include multiple AddProfile in a single mapper. Is this a bug? Also is this the best way to handle extending MappingConfiguration?

**Comment by lbargaoanu** [comment]
ForAllPropertyMaps is a global thing, it should be called after everything else (including AddProfile).

**Comment by TylerCarlson1** [comment]
@lbargaoanu `ForAllPropertyMaps` is actually a profile specific thing.  There have been some changes to make it global where when you put it in the main config and not a profile it should work on all profiles as long as you don't overwrite it.  It's in the MyGet version of AutoMapper and I would have to look at the code to confirm.

But for 5.1.1 if you put the `ForAllPropertyMaps` in a profile it only applies to that profile, and if you put it in the main config it won't apply to anything I believe.

**Comment by lbargaoanu** [comment]
Aha :) Anyway, @RobertBune apply it only globally and see what happens.

**Comment by RobertBune** [comment]
@lbargaoanu and @TylerCarlson1, applying it globally works but is far from ideal. I want these configuration settings to be reusable and optional, I have many MappingConfiguration instances in my application most of which will want these ForAllPropertyMaps included. I do not want to have to maintain this logic in every instance.

It looks like my best option is to have a single Profile instance per MappingConfiguration instance and use inheritance to pull in the BaseProfile. I may have a few flavours of base but typically only one feature profile per MappingConfiguration instance, so this should be viable.

**Comment by lbargaoanu** [comment]
You can try the MyGet build to see if it helps.

**Comment by RobertBune** [comment]
I just tried with AutoMapper.5.2.0-alpha-01248 and still have the same issue.

**Comment by lbargaoanu** [comment]
So the thing applies per profile as @TylerCarlson1 said, but maybe that's exactly what mislead you. Because the types you map are in the other profile so ForAllPropertyMaps doesn't apply to them unless that profile derives from BaseProfile. In you first example EventProfile doesn't derive from BaseProfile.

**Comment by RobertBune** [comment]
Ok, I will go with deriving a single profile for each MappingConfiguration which inherit from base profiles as required. I think I now have viable solutions for all my scenarios so I will close this issue. Thanks.
