### ISSUE TITLE
In AutoMapper 5.1.1  MapFrom method does not ignore Null Reference Exception but throws it 

### ISSUE THREAD

**Issue by MaciejBryndza** [AutoMapper/AutoMapper#1798]
Hi, 

I have defined map
.ForMember(x => x.CoverSectionId, opts => opts.MapFrom(src => src.TemplateCoverSection.CoverSection.Id)

During runtime I have path in application where TemplateCoverSection is null (expected).
Everything was working fine with AutoMapper 4.2.1 but after upgrade to 5.1.1 it throws exception

MapFrom method description states that it should ignore Null Reference Exception. 
Was there a change in MapFrom method behaviour and documentation is wrong or there is a bug ?

P.S. I did not change in application anything else than AutoMapper version.
Am I missing something or there is actually a bug? 

Cheers 
Maciej

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by MaciejBryndza** [comment]
Hi, 
I did try and get the same results.

**Comment by lbargaoanu** [comment]
The latest is 5.2.0-alpha-01244.

**Comment by MaciejBryndza** [comment]
I did try exactly the build 5.2.0-alpha-01244 with the same result. 

Please confirm that 5.1.1 actually has described bug and this is not a intended (changed after release 4.2.1) behaviour.
I would like to also point out that although this bug is for me an upgrade showstopper I'm not interested in using any alpha build (unless to prove fix actually works) I will wait for next stable release. 

Cheers.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by MaciejBryndza** [comment]
I would love to, but this is a commercial project and i'm not able to share source code - sorry.
I will try to create something representative mock example

**Comment by MaciejBryndza** [comment]
Hi 
I've prepared sample code that prove what I wrote before:
Folowing unit tests are working on version 4.2.1 and are not working on 5.1.1 and latest 5.2.alpha

using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Shipowners.Behaviours.Tests
{
    [TestClass]
    public class MappingTests
    {
        private const int ModelId = 5;

        [TestMethod]
        public void TestSubModelMapping()
        {
            var config = new MapperConfiguration(cfg =>
                cfg.CreateMap<Model, ViewModel>()
                    .ForMember(x => x.SubModelId,
                        opts => opts.MapFrom(src => src.SubModels.FirstOrDefault().SubSubModels.FirstOrDefault().Id)));
            var mapper = config.CreateMapper();

            var model = new Model
            {
                SubModels =
                    new List<SubModel> { new SubModel { SubSubModels = new List<SubSubModel> { new SubSubModel { Id = ModelId } } } }
            };

            var viewModel = mapper.Map<ViewModel>(model);

            Assert.AreEqual(ModelId, viewModel.SubModelId);
        }

        [TestMethod]
        public void TestSubModelMapping_NullReferenceException_AreSwallowed()
        {
            var mapper = GetConfiguredMapperMapper();

            var model = new Model {SubModels = new List<SubModel>()};

            mapper.Map<ViewModel>(model);
        }

        private static IMapper GetConfiguredMapperMapper()
        {
            var config = new MapperConfiguration(cfg =>
                cfg.CreateMap<Model, ViewModel>()
                    .ForMember(x => x.SubModelId,
                        opts => opts.MapFrom(src => src.SubModels.FirstOrDefault().SubSubModels.FirstOrDefault().Id)));
            var mapper = config.CreateMapper();
            return mapper;
        }
    }

    public class Model
    {
        public List<SubModel> SubModels { get; set; }
    }

    public class SubModel
    {
        public List<SubSubModel> SubSubModels { get; set; }
    }

    public class SubSubModel
    {
        public int Id { get; set; }
    }

    public class ViewModel
    {
        public int SubModelId { get; set; }
    }
}

**Comment by lbargaoanu** [comment]
We had some issues with this particular case, but it should work.

**Comment by MaciejBryndza** [comment]
Hi I can confirm this fix issue (testesd on latest alpha) - wainting for final release
