### ISSUE TITLE
Support for Silverlight 5

### ISSUE THREAD

**Issue by SonOfPirate** [AutoMapper/AutoMapper#180]
Need a new version compiled against Silverlight 5.

We use MEF for composability and dependency injection, because the current version of AutoMapper is built against the SL4 assemblies, we are unable to compile our applications if we attempt to export IMappingEngine.  In fact, I have compilation issues using the current version in any SL5 application because the current assemblies reference the 2.0.5 versions of mscorlib, System and System.Core.

It took a little manipulating, but I was able to create my own SL5 build using the latest code in about 10 minutes. However, I still had issues getting it to work. Rather than spending more time on an unofficial version, it would be much better to have an official release.

**Comment by icnocop** [comment]
FWIW, the latest NuGet package with Silverlight support is version 2.1.267.
