### ISSUE TITLE
5.x TypeConverter does not return default value of destination  

### ISSUE THREAD

**Issue by NinoFloris** [AutoMapper/AutoMapper#1802]
Ok so I hoped to have an easy migration to 5.1.1 but got burned on a small issue. 

Somehow our default property value from the destination model is not coming through via the new `T destination` parameter on a super simple `ITypeConverter<Model, string>`. It's also not available in ResolutionContext anymore so our tests fail and we are stuck.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by NinoFloris** [comment]
Simplest repro ever, it's worrying that you have no test coverage for this. 

https://gist.github.com/NinoFloris/54dbb2bd3776156902336d6d7ea616b3
version 5.1.1

**Comment by lbargaoanu** [comment]
You get a value for the destination only when you pass a destination object. You don't, so you get null. That's expected.

**Comment by NinoFloris** [comment]
Ok... So the old behavior is out? As this just works in 4.x

How would I get the upper level object type (the parent of this string) to do reflection on to get the default value?

**Comment by jbogard** [comment]
Most of this backwards compatibility stuff is a bit accidental - we're trying to make things a bit more explicit. 

In this example, we've had just as many people complain that they DONT want the destination object evaluated for various reasons as do. To make it obvious and explicit, if you don't pass in the destination, we don't try to use a destination. Your example isn't obvious - why should the destination value ever get used? It would involve creating the destination object, then evaluating it. Doesn't really make sense.

**Comment by jbogard** [comment]
The most obvious behavior is that when you pass in a destination object, that's what you're given as the destination object parameter. A not-obvious, confusing behavior would be to make some sort of judgement on "sometimes pass in the destination object, sometimes pass in something just instantiated".

So far it seems you're using a TypeConverter incorrectly. A type converter is not supposed to know its surroundings. It just converts type A to type B. I think more appropriate is a value resolver here - it gets the parent object as well (and for member value resolvers, you get both the destination member and the destination object). I think you're just using the wrong extension point in AutoMapper.

**Comment by NinoFloris** [comment]
This does not seem to be what I want. As it requires intimate knowledge of the source and destination objects.

The only thing I want is to be able to keep the default value on the model intact if the typeconverter that blindly acts on it finds itself not able to return something useful.

**Comment by jbogard** [comment]
In the 5.0 timeframe we standardized the resolution flow. Passing the destination value around meant we'd evaluate the destination value, which could potentially throw exceptions. So we stopped - you only get the destination value if you pass in a destination value at the top level, to make it as obvious and explicit as possible.

So the type converters became simplified, and for individual members, extended with member value resolvers.

Have you tried to use a member value resolver? You can make the source/destination type "object", then it can be applied at will. Type converters are blanket, they go against *all* types. Generally type converters are intended to be very simple and straightforward, that's why the context stuff was removed.

**Comment by NinoFloris** [comment]
Hi Jimmy,

First of all, thanks for your detailed reply.

With regard to the usage of the type converter, yes I really want the full underlying object graph to use this conversion as it is at an api boundary where we go from our core to mvc. And it should affect all occurrences where this complex type is dumbed down to a string.

We actually don't care at all about the destination value but we really want the default string on the destination to stay if the converter encountered say a null as the source value. I don't have to see the destination value or interact with it in any way, I only have to be able to signal I want to 'discard' this conversion result so to keep that value.

I hope to show that this is really not a use case for a value resolver but if you need any more information please let me know.

**Comment by jbogard** [comment]
So we have a precondition and a condition config option, do either of those
work?

**Comment by NinoFloris** [comment]
Well yes that works for now, but not ideal as it pollutes the mapping configuration quite a lot. It also forces you to specify this condition per individual object mapping. Or is there a way to say, for every member of type T only map if condition X?

**Comment by TylerCarlson1** [comment]
ForAllMaps and ForAllPropertyMaps

**Comment by NinoFloris** [comment]
How to do this based on type? not on name?

**Comment by TylerCarlson1** [comment]
ForAllPropertyMaps you will have the source and destination member info.  From there you can get the reflected type for the parent type you want, then you can put the condition in.

**Comment by NinoFloris** [comment]
This sounds like it will bring performance back to 4.x levels... Or should I have to create plumbing for caching and things like that. 

Where can I find ForAllPropertyMaps? intellisense says no.

**Comment by TylerCarlson1** [comment]
It should be same place as ForAllMaps under configuration and profile.  Are you on the latests version?

Also it will add minor slowdown but just executing the pre-conditions.  You still get all the performance gain in 5.x it's just when you map you'll have to do these extra checks.  The problem with 4.x performance was it was always doing these checks plus a million others which all added up.  You are only adding the ones you need for the maps you require.

**Comment by jbogard** [comment]
And the conditions themselves, I would add them when you're adding the property map stuff. Only add the condition for the types you're concerned about. Then there's zero runtime perf difference.
