### ISSUE TITLE
string -> int? conversion returning 0 rather than null

### ISSUE THREAD

**Issue by adam-resdiary** [AutoMapper/AutoMapper#1804]
We have a situation where we're mapping between two objects, and the source object has a particular property as a string, but the destination uses a nullable int:

```
public class Model
{
	public string Max { get; set; }
}

public class Dto
{
	public int? Max { get; set; }
}
```

When we're mapping from a null string value, it's returning 0 instead of null. Here's a test that recreates the issue:

```
[Test]
public void Map_ReturnsNullIntForNullString()
{
	// Arrange
	var mapperConfig = new MapperConfiguration(cfg => cfg.CreateMap<Model, Dto>());
	var mapper = mapperConfig.CreateMapper();

	var model = new Model {Max = null};

	// Act
	var dto = mapper.Map<Dto>(model);

	// Assert
	Assert.IsNull(dto.Max);
}
```

I've tested this against 5.2.0-alpha-01245 and the issue still exists.

Here's a gist: https://gist.github.com/adam-resdiary/c69a75aebe644205e1301818ce011efb

**Comment by adam-resdiary** [comment]
@lbargaoanu thanks for sorting this.

After I raised this, I came across another potential related issue that we have. If you do:

```
Mapper.Map<string, int?>(string.Empty).ShouldBeNull();
```

The mapper throws a FormatException - presumably because you're using int.Parse or something like that under the hood. To be honest, it's a bit of an odd situation, and we wouldn't normally map from a string to an int like this, but I'm not sure throwing a FormatException seems right for an empty string.

Then again, you could argue that one either way. I just wonder what your thoughts are so I know how we need to deal with this.

**Comment by lbargaoanu** [comment]
I see an AutoMapperMappingException which wraps a FormatException. That's the right behavior I would say.

**Comment by adam-resdiary** [comment]
Ok thanks.
