### ISSUE TITLE
Are Mapper.Map generic types backwards when mapping Expressions?

### ISSUE THREAD

**Issue by 0lorak0** [AutoMapper/AutoMapper#1807]
Hello, 

My apologies in advance if this is just a case of me being a doofus and not knowing how to reference documentation  and examples correctly, BUT....

When defining a mapping like so (AutoMapper 5.1.1):
```
public class Model
{
    public int Id { get; set; }
}

public class Data
{
    public int Id { get; set; }
} 

public static class AutoMapperConfig
{
    public static IMapper Mapper;

    static AutoMapperConfig()
    {
        var config = new MapperConfiguration(c => {
            CreateMap<Model, Data>();  //This mapping definition lets me map from the Model to the Data object
        });

        Mapper = config.CreateMapper();
    }
}
```

I expect to use it like:
```
var model = new Model{ Id = 1 };
var mappedData = AutomapperConfig.Mapper.Map<Data>(model);
```

And because I created the mapping definition to be from Model to Data only, if I tried to map from Data to Model, I would get an error, as expected.

However, when I try to use the same mapping definition created above with an expression (reference [Expression Translation](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)) ):
```
Expression<Func<Model, bool>> modelExpr = x => x.Id == 1;
var dataExpr =  AutoMapperConfig.Mapper.Map<Expression<Func<Data,bool>>>(modelExpr);
```

I get an error:
```
[NullReferenceException: Object reference not set to an instance of an object.]
AutoMapper.Mappers.MappingVisitor.PropertyMap(MemberExpression node) +109
AutoMapper.Mappers.MappingVisitor.VisitMember(MemberExpression node) +95
System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor) +14
System.Linq.Expressions.ExpressionVisitor.Visit(Expression node) +22
AutoMapper.Mappers.MappingVisitor.VisitBinary(BinaryExpression node) +73
System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor) +14
System.Linq.Expressions.ExpressionVisitor.Visit(Expression node) +22
AutoMapper.Mappers.ExpressionMapper.Map(TSource expression, ResolutionContext context) +1534
lambda_method(Closure , Object , Object , ResolutionContext ) +183

[AutoMapperMappingException: Error mapping types.
```

If I actually want the expression map shown above to work correctly I have to create the mapping definition like:
```
  CreateMap<Data, Model>();  //This mapping definition lets me map from the Data to the Model object
```
However, that's the opposite direction that I want/need to map in.

The following will also allow the expression mapping above to work:
```
//The below definitions do NOT produce error
CreateMap<Model, Data>().ReverseMap();
//OR
CreateMap<Model, Data>();
CreateMap<Data, Model>();
//OR
CreateMap<Expression<Func<Model,bool>>, Expression<Func<Data,bool>>>();
```
Notice that the top two work because they create two way mapping, which is the "opposite direction I am trying to map" scenario.

Also, I looked through the AutoMapper Unit Tests for Expressions: 
[UnitTests/ExpressionConversion](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/ExpressionConversion.cs)

I noticed that all the tests in the file do indeed define the mapping definition to be in the opposite direction than the actual Mapper.Map is being used (line 35 for method Can_map_single_properties)
```
var config = new MapperConfiguration(cfg => cfg.CreateMap<Source, Dest>());

Expression<Func<Dest, bool>> expr = d => d.Value == 10;

var mapped = config.CreateMapper().Map<Expression<Func<Dest, bool>>, Expression<Func<Source, bool>>>(expr);
```

I.E. The mapping definition is to map from Source to Dest, but the actual mapping that is being done is from Dest to Source.

So.....

**QUESTION**:
Why is it that in order for my expression map to work (Model to Data), I have to define the map as being in the opposite direction (from Data to Model)? Is this by design? Have I totally misread the documentation and examples?

This has totally thrown me for a loop, and took me a while to figure out because when I initially created my mapping definition, I thought that there was some kind of incompatibility between the objects I was trying to map (they are more complicated than the example objects above), especially because I only needed to map in one direction. 

I think that if this whole setup is by design, it should be explicitly stated in the wiki to avoid further confusion for others (or am I the only one who was confused?).

Thank you for your help.

**Comment by TylerCarlson1** [comment]
Yes the order is backwards when doing expression translation.  The exact reason eludes me right now.  I would have to go look at the source code.  My best guess right now is has something to do with flattening complicating the expression, or at least in the begging.  Maybe it can be reversed, but I would have to double check and see what's going on.

The example provided has mappings going both ways so it is ambiguous which map actually causes the expression translation to work.

**Comment by 0lorak0** [comment]
Got it.  The order being backwards is, in my opinion, counter intuitive to how the rest of the AutoMapper mapping definitions work. I think the wiki should be updated to note this.

By "example provided" do you mean the one in the wiki? Or the one I outlined? Just want to clarify that I'm 99.9999% sure it is indeed the "opposite direction" mapping definition that allows the expression mapping to work. Both in the wiki and in the code that I provided above.

Also, the mapping definition below does NOT throw the error outlined above and is in the correct direction that I originally needed:
```
CreateMap<Expression<Func<Model,bool>>, Expression<Func<Data,bool>>>();
//.......
Expression<Func<Model, bool>> modelExpr = x => x.Id == 1;
var dataExpr =  AutoMapperConfig.Mapper.Map<Expression<Func<Data,bool>>>(modelExpr);
```

Is it curious to you that the definition above does NOT have to be in the opposite direction in order for the mapping to work? Does it affect your guess as to why the order is backwards when doing the expression translation? I don't think I know enough about AutoMapper and Expression Trees to determine myself, even after a look at the source code.

Thanks for your help.

**Comment by TylerCarlson1** [comment]
The wiki is the one I meant.

As for explicitly mapping the expression not throwing an exception, that has nothing to do with the expression translation in general.  They are two completely separate internal mappers that do their own things.
