### ISSUE TITLE
Map overwrites destination with default value if flattening from null object

### ISSUE THREAD

**Issue by adam-resdiary** [AutoMapper/AutoMapper#1810]
Disclaimer: I'm not completely sure if this is actually a bug, or if it's just a change of behaviour in version 5.

We've got a source object that looks like:

```csharp
public class CreditCardDto
{
	public int Id { get; set; }
}

public class BookingDto
{
	public CreditCardDto CreditCard { get; set; }
}
```

And a destination object that looks like:

```csharp
public class CreditCard
{
	public int Id { get; set; }
}

public class Booking
{
	public int CreditCardId { get; set; }
	public CreditCard CreditCard { get; set; }
}
```

What we're finding is that if the BookingDto has a null CreditCard object, the Booking.CreditCardId gets overwritten with 0, whereas previously it just wouldn't be mapped:

```csharp
[Test]
public void ShouldNotMapNullObject()
{
	// Arrange
	var config =
		new MapperConfiguration(
			cfg =>
			{
				cfg.CreateMap<BookingDto, Booking>().ForMember(b => b.CreditCard, o => o.Ignore());
			});
	var mapper = config.CreateMapper();
	var dto = new BookingDto {CreditCard = null};
	var existingBooking = new Booking {CreditCardId = 1234};

	// Act
	mapper.Map(dto, existingBooking);

	// Assert
	Assert.AreEqual(1234, existingBooking.CreditCardId);
}
```

We can sort it by ignoring CreditCardId.

I just want to point out that I know it's a bit of a strange scenario, and we'll probably look at refactoring the code at our end so we don't have a CreditCard property on the source object, and this becomes a non-issue, but I wanted to raise it in case this isn't your intended behaviour.

**Comment by lbargaoanu** [comment]
I don't see a problem.

**Comment by jbogard** [comment]
That makes sense, sounds like the original behavior was wrong. You have a property CreditCardId on the destination, and a CreditCard.Id member on the source. When the CreditCard member is null, the CreditCard.Id value is null, so the destination value gets the correct, default value.

You can ignore the CreditCardId property, or use UseDestinationValue as well.

**Comment by adam-resdiary** [comment]
Ok - thanks for verifying that. Luckily we don't typically do weird mappings like this, so hopefully there shouldn't be many if any other places with the same problem.
