### ISSUE TITLE
Perform base mapping using source member?

### ISSUE THREAD

**Issue by mbcrawfo** [AutoMapper/AutoMapper#1811]
Given a class hierarchy similar to the following...

    class Foo 
    { 
      // properties
    }
    
    class FooWithFlags
    {
      public Foo Foo { get; set; }
      public bool Flag { get; set; }
      // etc...
    }
    
    class FooDTO 
    { 
      // properties
    }
    
    class FlaggedFooDTO : FooDTO
    {
      public bool Flag { get; set; }
      // etc...
    }
    
    Mapper.Initialize(c => 
    {
      c.CreateMap<Foo, FooDTO>();
      c.CreateMap<FooWithFlags, FlaggedFooDTO>()
        // what here?
    }

Is there a way to use the existing `Foo` -> `FooDTO` mapping to map `FooWithFlags.Foo` to the base class of `FlaggedFooDTO`?  Or any method to set up this mapping that avoids having to manually set up each member of the base class for the `FlaggedFooDTO` mapping?

**Comment by lbargaoanu** [comment]
Include or IncludeBase would do the trick.

**Comment by mbcrawfo** [comment]
@lbargaoanu unfortunately they do not, since they lack the ability to say "map the base *from a property* of the source."  If you replace the "what here" comment in the sample code with `.IncludeBase<Foo, FooDTO>()`, you get an exceptions along the lines of, "Property {Foo Property Name Here} is not defined for type FooWithFlags."

**Comment by lbargaoanu** [comment]
If you're free to change the type definitions, you should be able to do it. You reuse configuration by reusing an existing mapping. The types just need inherit each other as required by Include/IncludeBase.

**Comment by mbcrawfo** [comment]
I don't have the option to restructure everything... that's why I'm asking the question...

**Comment by lbargaoanu** [comment]
Make a runnable gist. Comment with what can be changed and what cannot. Indicate what exactly you try to reuse. And I'll try to come up with something. Or wait for someone else to pitch in :)

**Comment by mbcrawfo** [comment]
I'm debating making a PR to add this functionality, but I have not idea when I will have time to do it, so closing for now.
