### ISSUE TITLE
Interfaces derived from IMemberValueResolver<,,,> break BuildValueResolverFunc 

### ISSUE THREAD

**Issue by pinkfloydx33** [AutoMapper/AutoMapper#1813]
If I specify my own interface:

`public interface IMyValueResolver<TSrcMember,TDestMember> : IMemberValueResolver<object,object,TSrcMember,TDestMember> {
  ...
}`
I cannot supply an implementing type to ResolveUsing().  `BuildValueResolverFunc ` throws an exception while building the expressions due to the interface types not having the same number of generic parameters.

This is caused by the below, which in my case is finding both the interface that I have defined myself as well as the generic implementation. While this may not be the best way for me to do things, the below should most likely be checking that the generic argument count matches when selecting the correct type

```
var iResolverType =
                        resolverType.GetTypeInfo()
                            .ImplementedInterfaces.First(t => t.ImplementsGenericInterface(typeof(IMemberValueResolver<,,,>)));
```

**Comment by lbargaoanu** [comment]
PR? The fix would be to search only for IMemberValueResolver, not for derived interfaces.
