### ISSUE TITLE
Automapper 5.x do not map collections defined with readonly properties (version 4.2.1 does)

### ISSUE THREAD

**Issue by mbacelo** [AutoMapper/AutoMapper#1815]
Details and sample code here: https://stackoverflow.com/questions/40773422/

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by TylerCarlson1** [comment]
I think this has changed and the MyGet build won't help.
This looks like lost functionality with the changes to 5.x

**Comment by lbargaoanu** [comment]
@TylerCarlson1 Give it a chance :)

**Comment by TylerCarlson1** [comment]
Checked code.  Looks like setting UseDestinationValue will fix the problem.

**Comment by lbargaoanu** [comment]
That's not needed. The code works as is with the MyGet build.

**Comment by lbargaoanu** [comment]
I was testing smth else. @TylerCarlson1 had it right. Rollback :)

**Comment by mbacelo** [comment]
Thanks for all the answers,

I tried the MyGet build using the command `Install-Package AutoMapper -Source https://www.myget.org/F/automapperdev/api/v3/index.json -IncludePrerelease`
but I get the same result in the code sample I provided (collection items are not mapped).

If you tried the sample code and it worked using the MyGet build please tell me. I might be doing something wrong.
I'm also interested in knowing if this is going to be included soon in a final release, because I'm using it in a commercial application and it may be risky to include a pre-release library.

**Comment by lbargaoanu** [comment]
As @TylerCarlson1 said, you need UseDestinationValue. That was true by default, but not anymore. Use 5.2.0 from NuGet instead.

**Comment by mbacelo** [comment]
Thanks, that worked!

I used this code: `.ForMember(x => x.MyList, opt =>   { opt.UseDestinationValue(); });`
Do you know if there is a way to set it globally instead of member by member to avoid reviewing all the code?

**Comment by lbargaoanu** [comment]
ForAllPropertyMaps would do the trick. You can close the issue.

**Comment by davidop** [comment]
http://stackoverflow.com/questions/28382811/how-to-configure-automapper-to-automatically-ignore-properties-with-readonly-att/28384511
