### ISSUE TITLE
Internal/Private Not Mapping

### ISSUE THREAD

**Issue by xom-pschiess** [AutoMapper/AutoMapper#1817]
I have a strange issue that i've never encountered.

I have 2 classes:

```
public class ParentClass
{
   private int? _clientType;

   internal int? Client_Type_ 
   {
      get { return _clientType; }
      set {  _clientType = value; }
   }

   public string Company_Name{ get; set; }

   public string Client_Type
   {
      get { return MyDictionary[_clientType.GetValueOrDefault(0)];
   }
}
```

```
public class ChildClass : ParentClass
{
   public string Full_Name { get; set; }
}
```

I am defining the mapping in my Unity IoC container as such:

```
var config = new MapperConfiguration(cfg =>
{
   cfg.CreateMap<ParentClass, ChildClass>();
}

IMapper mapper = config.CreateMapper();

container.RegisterInstance(mapper);
```

and in my code I am mapping as such:

```
var parentClass = GetParentClass();
var mappedClass = _mapper.Map<ChildClass>(parentClass);
```

The strange thing is... I can check the values of parentClass and all of the values that I have initnally passed into my model (parentClass) are there. However, when it maps to the new object (childClass) - Company Name sticks... but _clientType and Client_Type_ are null (which ultimately affects Client_Type).

Is this a bug?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by xom-pschiess** [comment]
It seems kinda like a bug to me … that’s why I posted it here.

**Comment by jbogard** [comment]
Yep, by default AutoMapper only maps public properties (similar to how serialization libraries work).
