### ISSUE TITLE
No parameter mapping for multilanguage use

### ISSUE THREAD

**Issue by TadeuszSobol** [AutoMapper/AutoMapper#1823]
For me, in great AutoMapper exists problem with just some required mappings.  If multilanguage user interface application requires typical ability to change UI language dynamically, there is lack of corresponding solutions in AutoMapper – i.e. no parameter to select which one of source properties (i.e. from set of table columns) to map to destination property.  The things are going even worse for us, when such flexibility is also typically required for related database tables.  For such sub-mappings, such as 1 to many relation (collection of texts) or many to 1 relation (i.e. dictionary description) similar selection is required or close one if exact do not exists.  There is also problem when the mapping requires many such dynamic selections at ones, i.e. UI interface have user selectable translation functionality (many parameters for mapping and sub-mappings?).  Because all of that, many partial, strange, or nasty “solutions” for such problems exist in ours projects by years.

**Comment by lbargaoanu** [comment]
See #1827 for inspiration.
