### ISSUE TITLE
How to map multiple list to a single list?

### ISSUE THREAD

**Issue by PrasadSudama** [AutoMapper/AutoMapper#1825]
Hi,
I have few classes and they have multiple list items like below:

--Request1--
public class Request1
{
public List<AdditionalApplicantData> AdditionalApplicantData { get; set; }
public List<ApplicantData> ApplicantData { get; set; }
}
--Request2--
public class Request2
{
    public List<ApplicantDetails> ApplicantDetails { get; set; }
}

I want to map Request1 to Request2 but List<ApplicantDetails> has to be mapped from multiple sources like List<AdditionalApplicantData>& List<ApplicantData>   but not sure how to achieve it can someone please help me here?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by PrasadSudama** [comment]
Thanks Lucian I have posted my question there also but didn't get any reply so far.

**Comment by PrasadSudama** [comment]
Just added answer but need some suggestions to improve it http://stackoverflow.com/questions/40880732/how-to-map-multiple-list-to-a-single-list/40901900#40901900

**Comment by lbargaoanu** [comment]
The names don't need to match.
