### ISSUE TITLE
Automapper throws exception with ProjectTo and EF6

### ISSUE THREAD

**Issue by jonnybee** [AutoMapper/AutoMapper#1827]
My code runs fine with Automapper 3.3.1 and 4.2.1 but breaks with 5.x and throws 
ArgumentException: "Type 'System.String' does not have a default constructor" in AutoMapper.QueryableExtensions.ExpressionBuilder.DestinationConstructorExpression.

We use a complex type in the entity model for multilingual values, based on this article: http://patrickdesjardins.com/blog/how-to-have-localized-string-with-mvc-and-entity-framework

I have put a small repo and solution at https://github.com/jonnybee/AutomapperIssue that fails only for Automapper 5.2.0 . This solution also includes same sample for 4.2.1 and 3.3.1 that runs fine.  

I also posted this as a question on SO: http://stackoverflow.com/questions/40875318/automapper-5-2-0-and-projections-with-ef6-throws-exception-bug

**Comment by lbargaoanu** [comment]
It works without ConvertUsing and the LocalizedString derived class. Now, these both look like fixable bugs, but that remains to be seen :)

**Comment by jonnybee** [comment]
The sad part is that this is just not possible for us. 

It doesn't work in the EF6 DbContext unless we create subclasses of LocalizedString. IE: We cannot use LocalizedString type on multiple objects or multiple times in same object.

And when I remove the ConvertUsing and use a subclass I get a new NotSupportedException from EF6: 
"Unable to cast the type 'DemoModel.Country+CountryNameCountryDomainLocalized' to type 'DemoModel.LocalizedString'. LINQ to Entities only supports casting EDM primitive or enumeration types." in System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ValidateAndAdjustCastTypes.

So there is clearly something wrong in Automapper. 

For now - I think we must stay on Automapper 4.2.1 and consider 5.x when/if the bugs has been fixed.

**Comment by lbargaoanu** [comment]
I don't think that ConvertUsing/ProjectUsing thing is even a bug. They are both void, so the API suggests they don't mix. You can make it work by reusing the CreateMap result, but that's weird (and better than what you have now). cc @jbogard

**Comment by lbargaoanu** [comment]
You can workaround the cast issue by declaring the property to be LocalizedString, even if you use derived types. I don't know if that would work with EF.
