### ISSUE TITLE
Not able to use MappingEngine

### ISSUE THREAD

**Issue by User0816** [AutoMapper/AutoMapper#1829]
What am I missing here?

![capture](https://cloud.githubusercontent.com/assets/19856101/20797619/80358ea2-b7d3-11e6-8a8d-0e8bde44a5a3.PNG)

I installed via NuGet and use code from:

https://gist.github.com/irontoby/b3564f336df4aa6405c5#gistcomment-1935320

**Comment by jbogard** [comment]
What version did you install? MappingEngine is gone in 5.0 (as you'd see in
the 5.0 upgrade guide).

**Comment by User0816** [comment]
Okay? I installed 5.2.0.
I did not realize that as I am completely new to this topic and wanted to use abandonned? code from the posted link..

**Comment by jbogard** [comment]
I don't know what that code you posted is, but it looks like code against
an older version of AutoMapper.

**Comment by User0816** [comment]
okay thanks anyway. I tried to use existing code promising to be able to create strongly typed data out of excel
