### ISSUE TITLE
Mapping Class to Derived DynamicObject gives NullReferenceException

### ISSUE THREAD

**Issue by HubertoKusters** [AutoMapper/AutoMapper#1830]
Hi,

I am using AutoMapper version 5.2.0.0!

I have a simple class:

    public class CarrierMode
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
        public DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifyDate { get; set; }
        public string ModifiedBy { get; set; }
    }

I want to map this to a class derived from _DynamicObject_ :

    public class DynamicDictionary : DynamicObject
    {
        private readonly Dictionary<string, object> _dictionary = new Dictionary<string, object>();

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            return _dictionary.TryGetValue(binder.Name, out result);
        }

        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            _dictionary[binder.Name] = value;
            return true;
        }

        public int Count => _dictionary.Count;
    }

I perform the following action:

        var config = new MapperConfiguration(cfg => { });
        var domainObject = config.CreateMapper().Map<DynamicDictionary>(new CarrierMode
        {
            Id = 100,
            Name = "HKUAIR",
            Description = "HKU Air",
            CreatedBy = "unittest",
            CreationDate = DateTime.UtcNow,
            ModifiedBy = "unittest",
            ModifyDate = DateTime.UtcNow,
            RowVersion = new byte[] { 0x00, 0x00, 0x00, 0x00, 0xfa, 0x23, 0x45, 0xf3 }
        });

This results in the following exception:

>   AutoMapper.AutoMapperMappingException: Error mapping types.
>   Mapping types:
>   CarrierMode -> DynamicDictionary
>   HazMat.Configuration.Test.CarrierMode -> HazMat.Configuration.Test.DynamicDictionary ---> System.NullReferenceException: Object reference not set to an instance of an object.
>      at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.InitializeCallingContext(DynamicMetaObjectBinder payload)
>      at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
>      at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
>      at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, IEnumerable`1 args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
>      at Microsoft.CSharp.RuntimeBinder.CSharpSetMemberBinder.FallbackSetMember(DynamicMetaObject target, DynamicMetaObject value, DynamicMetaObject errorSuggestion)
>      at System.Dynamic.DynamicObject.MetaDynamic.<>c__DisplayClass3_0.<BindSetMember>b__0(DynamicMetaObject e)
>      at System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast(String methodName, DynamicMetaObjectBinder binder, Expression[] args, Expression value, Fallback fallback)
>      at System.Dynamic.DynamicObject.MetaDynamic.BindSetMember(SetMemberBinder binder, DynamicMetaObject value)
>      at System.Dynamic.SetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
>      at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
>      at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
>      at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>      at AutoMapper.Mappers.ToDynamicMapper.SetDynamically(MemberInfo member, Object target, Object value)
>      at AutoMapper.Mappers.ToDynamicMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Func`1 ifNull)
>      at lambda_method(Closure , Object , Object , ResolutionContext )
>      --- End of inner exception stack trace ---
>      at lambda_method(Closure , Object , Object , ResolutionContext )
>      at HazMat.Configuration.Test.MappingTest.ShouldMapEntityPropertiesToDomain() in C:\Projects\HazMat2017\Development\Source\HazMat.Configuration.Test\DomainTest.cs:line 85

It turns out that when removing the RowVersion property from the class, everything works.

Any ideas?

TIA

**Comment by lbargaoanu** [comment]
As a workaround, use ```Map<ExpandoObject>```.

**Comment by HubertoKusters** [comment]
@lbargaoanu: 
That works, but it's not what I want. In the end I want a Class with fixed properties and the ability to add properties on the fly.

Thanks for your input.

**Comment by lbargaoanu** [comment]
I'll look into it, but that stack trace doesn't look good. You can check the code yourself, it's simple enough. I don't know if we'll be able to do smth about it.

**Comment by lbargaoanu** [comment]
I guess it wasn't that bad, just weird :)

**Comment by HubertoKusters** [comment]
Cool!!! Thanks for the quick fix.
