### ISSUE TITLE
Additional information: Could not load file or assembly 'System.Runtime.Serialization...

### ISSUE THREAD

**Issue by StoevIT** [AutoMapper/AutoMapper#1832]
Hi, I use AutoMapper in Xamarin project. When I build UWP, everything is fine. When I run UWP, I receive throw in line

MapperConfiguration MapperConfig = new MapperConfiguration(cfg =>
{
        cfg.AddProfile(new TestMappingProfile());
});

Throw:
Additional information: Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

In TestMappingProfile i use assembly which requires 'System.Runtime.Serialization, Version=4.0.0.0'.

In Andorid and iOS i recive warning but projects work well:
1>  No way to resolve conflict between "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by jbogard** [comment]
Is this a bug in UWP?

**Comment by StoevIT** [comment]
Yes, in UWP

**Comment by jbogard** [comment]
Well nuts, I don't know what to do about a UWP bug. Have you tried to ping the MS teams?

**Comment by jbogard** [comment]
🤷‍♂️
