### ISSUE TITLE
Auto-flattening null reference exception

### ISSUE THREAD

**Issue by markjhvt** [AutoMapper/AutoMapper#1833]
I have the following basic model structure:

	public class OrderModel
	{
		public VendorModel Vendor { get; set; }
		public string Number { get; set; }
	}

	public class VendorModel
	{
		public string Name { get; set; }
		public CurrencyModel Currency { get; set; }
	}

	public class CurrencyModel
	{
		public string Name { get; set; }
	}

	public class OrderDTO
	{
		public CurrencyDTO VendorCurrency { get; set; }
		public string VendorName { get; set; }
		public string Number { get; set; }
	}

	public class CurrencyDTO
	{
		public string Name { get; set; }
	}

With this code as a test:

	var config = new MapperConfiguration(c =>
	{
		c.CreateMap<OrderModel, OrderDTO>();
	});

	var orderModel = new OrderModel()
	{
		Number = "1",
		Vendor = null
	};

	var mapper = config.CreateMapper();
	var dto = mapper.Map<OrderDTO>(orderModel);

And it's throwing a NullReferenceException on the Map statement, and I think it's coming from the fact that it's trying to map OrderDTO.VendorCurrency -> Name from Vendor -> Currency -> Name based on the naming of the properties, and I guess it's not doing null checks with the multiple levels.  For instance, if I create a Vendor in the OrderModel (but not a Currency), it works:

	var orderModel = new OrderModel()
	{
		Number = "1",
		Vendor = new VendorModel() { Name = "vendor", Currency = null }
	};

**Comment by TylerCarlson1** [comment]
Does adding `c.CreateMap<CurrencyModel, CurrencyDTO>();` help?  Because the mapping isn't set.

Also can you give a complete stack trace of the exception?  Is it null reference exception by itself, or is it an inner exception of AutoMapper's exception?

**Comment by markjhvt** [comment]
Adding the additional CreateMap call doesn't help - same problem.

And you're right, the null ref exception is indeed the inner exception of an AutoMapper exception.  I had just been seeing NullReferenceException in the debugger.  Here's the full details from the AutoMapper exception:

```
AutoMapper.AutoMapperMappingException was unhandled
  HResult=-2146233088
  Message=Error mapping types.

Mapping types:
OrderModel -> OrderDTO
AutoMapperTest.OrderModel -> AutoMapperTest.OrderDTO

Type Map configuration:
OrderModel -> OrderDTO
AutoMapperTest.OrderModel -> AutoMapperTest.OrderDTO

Property:
VendorCurrency
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Object , Object , ResolutionContext )
       at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\development\Other\AutoMapper\src\AutoMapper\Mapper.cs:line 212
       at AutoMapperTestUT.UnitTest1.TestMethod2() in C:\Users\markjhvt\documents\visual studio 2015\Projects\AutoMapperTestUT\UnitTest1.cs:line 72
  InnerException: 
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=Anonymously Hosted DynamicMethods Assembly
       StackTrace:
            at lambda_method(Closure , Object , Object , ResolutionContext )
       InnerException: 
```

**Comment by lbargaoanu** [comment]
What version? 5.2.0 is the latest.

**Comment by markjhvt** [comment]
Yeah, this is with 5.2.0.

**Comment by TylerCarlson1** [comment]
Yea it's a bug.  It looks like null check doesn't like it when flattening where your final results are sub maps.

VendorName null checks fine while VendorCurrency does not.
