### ISSUE TITLE
Mapping Dynamic objects with a List of  Dynamic objects

### ISSUE THREAD

**Issue by HubertoKusters** [AutoMapper/AutoMapper#1836]
Hi,

I have two Entity classes:

        private class RouteEntity
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }
            public DateTime CreationDate { get; set; }
            public string CreatedBy { get; set; }
            public DateTime ModifyDate { get; set; }
            public string ModifiedBy { get; set; }
            public string RowVersion { get; set; } 
            // Rem: Will be byte[], but is not jet supported by AutoMapper
        }

        private class CarrierModeEntity
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }
            public DateTime CreationDate { get; set; }
            public string CreatedBy { get; set; }
            public DateTime ModifyDate { get; set; }
            public string ModifiedBy { get; set; }
            public string RowVersion { get; set; } 
            // Rem: Will be byte[], but is not jet supported by AutoMapper
            public List<RouteEntity>  Routes { get; set; }
        }

And two Domain Classes:

        private class RouteDomain : Expando
        {
            public string Name { get; set; }
            public string Description { get; set; }
        }

        private class CarrierModeDomain : Expando
        {
            public string Name { get; set; }
            public string Description { get; set; }
            public List<RouteDomain> Routes { get; set; }
        }

The Domain classes inherit from Rick Strahl's Expando object (https://github.com/RickStrahl/Expando), which in essence is a DynamicObject with some sugar. 

In a test I create the following instances for the Entity classes:

            var routeEntity1 = new RouteEntity
            {
                Name = "ROUTE1",
                Description = "Route 1",
                Id = 100,
                CreatedBy = "unittest",
                CreationDate = DateTime.UtcNow,
                ModifiedBy = "unittest",
                ModifyDate = DateTime.UtcNow,
                RowVersion = Convert.ToBase64String(
                                new byte[] {0x00, 0x00, 0x00, 0x00, 0xfa, 0x23, 0x45, 0xf3}),
            };

            var routeEntity2 = new RouteEntity
            {
                Name = "ROUTE2",
                Description = "Route 2",
                Id = 101,
                CreatedBy = "unittest",
                CreationDate = DateTime.UtcNow,
                ModifiedBy = "unittest",
                ModifyDate = DateTime.UtcNow,
                RowVersion = Convert.ToBase64String(
                                new byte[] {0x00, 0x00, 0x00, 0xff, 0xfa, 0x23, 0x45, 0xf3}),
            };

            var entityObject = new CarrierModeEntity
            {
                Id = 100,
                Name = "HKUAIR",
                Description = "HKU Air",
                CreatedBy = "unittest",
                CreationDate = DateTime.UtcNow,
                ModifiedBy = "unittest",
                ModifyDate = DateTime.UtcNow,
                RowVersion = Convert.ToBase64String(
                                new byte[] {0x23, 0x23, 0x23, 0x23, 0xfa, 0x23, 0x45, 0xf3}),
                Routes = new List<RouteEntity> { routeEntity1, routeEntity2 }
            };

I then want to map them with automapper:

            var domainObject = new MapperConfiguration(cfg => {})
                .CreateMapper()
                .Map<CarrierModeDomain>(entityObject);

When doing this I get the following error:

  AutoMapper.AutoMapperMappingException: Error mapping types.
  Mapping types:
  CarrierModeEntity -> CarrierModeDomain
  HazMat.Configuration.Test.MappingTest+CarrierModeEntity ->   HazMat.Configuration.Test.MappingTest+CarrierModeDomain --->   Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Westwind.Utilities.Dynamic.Expando' does   not contain a definition for 'Routes'
      at CallSite.Target(Closure , CallSite , Object , Object )
     at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
     at AutoMapper.Mappers.ToDynamicMapper.SetDynamically(MemberInfo member, Object target, Object value)
     at AutoMapper.Mappers.ToDynamicMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Func`1 ifNull)
     at lambda_method(Closure , Object , Object , ResolutionContext )
     --- End of inner exception stack trace ---
    at lambda_method(Closure , Object , Object , ResolutionContext )
    at HazMat.Configuration.Test.MappingTest.ShouldMapEntityPropertiesToDomain() in C:\Projects\HazMat2017\Development\Source\HazMat.Configuration.Test\MappingTest.cs:line 136

This is in fact understandable, because there is no property Routes to be found of type List&lt;RouteEntity&gt;. Instead there is a Routes property of type List&lt;RouteDomain&gt;. Automapper is not aware of how to map RouteEntity to RouteDomain. To overcome this, I added the following mapping:

            var domainObject = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<CarrierModeEntity, CarrierModeDomain>();
            })
                .CreateMapper()
                .Map<CarrierModeDomain>(entityObject);

It does somehow do the trick, however, now it does not treat the Domain Classes as dynamics, which means that it only maps the properties it knows of (Name, Description and Routes), but not the other properties (Id, CreatedBy, CreationDate, ModifiedBy, ModifyDate and RowVersion).

Any idea about how to overcome this?

TIA

**Comment by lbargaoanu** [comment]
It sounds like you want to have the cake and eat it too :) ```new Expando().Routes = null``` fails. You have to invoke it dynamically to succeed. With AutoMapper, you can declare Routes ```List<object>``` and it works. I'm not sure whether we could do better here.

**Comment by HubertoKusters** [comment]
It would have been great if we can create a mapping between the Entity and Domain class but explicitly specify to handle the source and/or destination as a dynamic during the Map.
Something like: 

            new MapperConfiguration(cfg =>{}).CreateMapper()
                .MapDynamic<CarrierModeDomain>(entityObject);

But I suppose it is one or the other.

**Comment by jbogard** [comment]
Pretty much, since the dynamic mapper does its own logic.

**Comment by HubertoKusters** [comment]
I have created a new ToDynamicMapper to overcome this. The changes are made in the static Map method:

        public static TDestination Map<TSource, TDestination>(TSource source, TDestination destination,
            ResolutionContext context, Func<TDestination> ifNull)
        {
            if (destination == null)
                destination = ifNull();
            var sourceTypeDetails = context.ConfigurationProvider.Configuration.CreateTypeDetails(typeof (TSource));
            var destinationTypeDetails =
                context.ConfigurationProvider.Configuration.CreateTypeDetails(typeof (TDestination));
            foreach (var sourceMember in sourceTypeDetails.PublicReadAccessors)
            {

                object sourceMemberValue;
                try
                {
                    sourceMemberValue = sourceMember.GetMemberValue(source);
                }
                catch (RuntimeBinderException)
                {
                    continue;
                }

                var destinationMember =
                    destinationTypeDetails.PublicWriteAccessors.SingleOrDefault(a => a.Name == sourceMember.Name);
                if (destinationMember != null)
                {
                    var destinationType = destinationMember.GetMemberType();
                    var sourceType = sourceMember.GetMemberType();
                    if (sourceType.IsCollectionType() && destinationType.IsCollectionType()
                        && sourceType.GetGenericArguments()[0] != destinationType.GetGenericArguments()[0])
                    {
                        var test = context.MapMember(destinationMember, sourceMemberValue);
                        SetDynamically(destinationMember, destination, test);
                        continue;
                    }
                }
                var destinationMemberValue = context.MapMember(sourceMember, sourceMemberValue);
                SetDynamically(sourceMember, destination, destinationMemberValue);
            }
            return destination;
        }

What I do here is check if there is a destination property of the same name. If that is found and both the source and destination properties are of type ICollection<> and the generic arguments are different, then I perform a new mapping.

Maybe this is something to be included?

Regards.
