### ISSUE TITLE
There is no error when trying to map value into property without setter

### ISSUE THREAD

**Issue by stawr93** [AutoMapper/AutoMapper#1837]
Hello! 
I've just found some strange behavior of automapper.
Output of the following code will be `0`:
```
class Program
{
    static void Main(string[] args)
    {
        var config = new MapperConfiguration(cfg => cfg.CreateMap<SourceClass, IDestination>());
        config.AssertConfigurationIsValid();

        var mapper = config.CreateMapper();

        var result = mapper.Map<IDestination>(new SourceClass
        {
            Value = 42
        });

        Console.WriteLine(result.Value);
        Console.ReadKey();
    }
}

public class SourceClass
{
    public int Value { get; set; }
}

public interface IDestination
{
    int Value { get; }
}
```
And no errors/exceptions. But if I do so, I expect some exception, for example, on `config.AssertConfigurationIsValid();`.

**Comment by lbargaoanu** [comment]
I think the reasoning here is if it's read-only, then it doesn't need to be mapped, so no error. Probably someone saw it this way and so it is.

**Comment by jbogard** [comment]
Yep, AutoMapper skips readonly properties. That's expected behavior - you shouldn't have to ignore readonly properties. A lot of people would get annoyed if that were the case.

Second question - do you expect this to be mapped automatically? AutoMapper doesn't support readonly properties for interfaces. Well, any readonly properties. It needs a setter, even it's a private setter.

**Comment by stawr93** [comment]
Well, my example is not correct, I think.
Yeah, in case when you did not explicitly configure mapping for read only property, automapper works perfect.
But if I added explicit mapping for some read only property, automapper still skips it. If mapper configuration looks like following, I expects some error or warning:
```
var config = new MapperConfiguration(
    cfg =>
        cfg.CreateMap<SourceClass, IDestination>()
            .ForMember(dst => dst.Value, opts => opts.MapFrom(src => src.Value)));
```
This problem not so important. However, if automapper will tell me smth like: "Hey, you probably doing some strange thing: you ask me to map value into read only property!", it would be great. 
And I don't expect automatic mapping of this value because probably this is just mistake (e.g. someone deleted setter from interface).
P.S. Sorry for my English :)

**Comment by jbogard** [comment]
Ah, I see. There are still occasionally cases you can map readonly properties - collections for example. When I run configuration validation, I just make sure everything is mapped, I don't actually execute a mapping. This one seems reasonable enough, though.

**Comment by stawr93** [comment]
You're right, there are may be some cases when read only property with complex type have some writable fields. I suppose, it is enough to show some warning in case when property (or field) is read only and it's type is simple. And this check can be performed on config validation, I think 😃

**Comment by tboby** [comment]
I've been toying with implementing this from time to time. Would a PR still be welcome if I get round to finishing it?

**Comment by lbargaoanu** [comment]
Yes, I closed it just because nobody seemed interested to write the code.
