### ISSUE TITLE
AutoMapper 5.2.0

### ISSUE THREAD

**Issue by ratnamchoudhary** [AutoMapper/AutoMapper#1840]
Dear Sir,
we are using Nuget to Install Automapper for our Project. But Last two days it is throwing error while installing AutoMapper 5.2.0. It is showing error message as not found. So please help us.

**Comment by jbogard** [comment]
What version of NuGet are you using? Is this on your local machine or on your build server? What is the full error message you're getting? Is this through Visual Studio or command line? Package manager console or VS UI?

**Comment by ratnamchoudhary** [comment]
Dear Sir, we are using Microsoft Visual Studio Enterprise 2015 with NuGet Package Manager   3.0.0. This error is coming in Local and Build server. we are attaching image in this context.
![image](https://cloud.githubusercontent.com/assets/24404031/20955100/6b157c3e-bc66-11e6-9c28-dbc3345c4363.png)

**Comment by jbogard** [comment]
Can you update your NuGet Package Manager inside of Visual Studio? When
people have this error, it's typically a NuGet client issue. Let's start
with that.

**Comment by ratnamchoudhary** [comment]
Hi Sir, Now its working after updating Nuget package for Visual Studio. Thanks for your help.
