### ISSUE TITLE
AutoMapper.Debugging

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#1842]
[AgileObjects.ReadableExpressions](https://github.com/agileobjects/ReadableExpressions), the package behind the VS extension we use, has a Expression.ToReadableString method. Maybe we could use that to allow people to see the execution plan. Of course they would need to know that the package exists :) Is it worth doing?

**Comment by jbogard** [comment]
It's MIT licensed too, so we could merge the relevant code (just making sure to include the license).

**Comment by lbargaoanu** [comment]
That might be a lot of code, but I'll check.

**Comment by lbargaoanu** [comment]
Actually I'm not sure it's worth making something more than exposing the execution plan. Just point people to the package should be enough.

**Comment by lbargaoanu** [comment]
I guess the advantage of having the method in AM would be discoverability. We could late bind to the method in the package and on error throw a message that they should add a reference to the package.
