### ISSUE TITLE
ForAllOtherMembers (Ignore) overwrites mapped member configurations

### ISSUE THREAD

**Issue by Chips100** [AutoMapper/AutoMapper#1843]
Below I put together a minimal example of a situation I am having trouble with.
Basically, I map some property explicitly (refactored into a helper method) and call `ForAllOtherMembers(x => x.Ignore())` afterwards. The problem arises when this helper method is generic and the type constraint is more general than the concrete type I am mapping to. To me, this looks like it treats the members mapped in the helper method like members from a base type, and when I call ForAllOtherMembers they are treated as unconfigured (for the concrete type in the mapping). 

I would appreciate if someone would help me wrap my head around this; I am unsure if this is a bug or expected behaviour. If this indeed is expected behaviour, is there some way to work around this? I could only imagine solutions that require duplicate code.
Thank you very much!

	interface MyInterface { string Test { get; set; } }
	class MyImplementation : MyInterface { public string Test { get; set; } }
	class MySource { public string SourceTest { get; set; } }

	// Maps MySource.SourceTest to TDest.Test
	// Remark: If type constraint is changed to MyImplementation, it works as I would expect.
	private static void MapTestProperty<TDest>(IMappingExpression<MySource, TDest> map)
		where TDest : MyInterface
	{
	    map.ForMember(dest => dest.Test, x => x.MapFrom(source => source.SourceTest));
	}

	static void Main(string[] args)
	{
	    IMapper mapper = new Mapper(new MapperConfiguration(cfg =>
	    {
	        var map = cfg.CreateMap<MySource, MyImplementation>();
	        MapTestProperty(map);

	        // If I remove this line, it works as I would expect.
	        map.ForAllOtherMembers(x => x.Ignore());
	    }));

	    var source = new MySource() {SourceTest = "ShouldMap"};
	    var target = new MyImplementation();
	    mapper.Map(source, target);

	    // Writes nothing; I expected it to write "ShouldMap".
	    Console.WriteLine("Result: {0}", target.Test);
	    Console.ReadLine();
	}

**Comment by lbargaoanu** [comment]
This is weird. You reuse configuration by reusing an existing mapping with Include/IncludeBase.

**Comment by Chips100** [comment]
I have tried that before, but it didn't work either - maybe I am doing something wrong here. You can change my example above by configuring the mapper like the following, using `IncludeBase` - it still ignores the member. Again, when I remove the `ForAllOtherMembers(x => x.Ignore())`, it maps the property correctly. 

	IMapper mapper = new Mapper(new MapperConfiguration(cfg =>
	{
	    cfg.CreateMap<MySource, MyInterface>()
	        .ForMember(dest => dest.Test, x => x.MapFrom(src => src.SourceTest));

	    cfg.CreateMap<MySource, MyImplementation>()
	        .IncludeBase<MySource, MyInterface>()
	        .ForAllOtherMembers(x => x.Ignore());
	}));

**Comment by lbargaoanu** [comment]
I thinks it's arguable, but I see it your way too. I'll try a fix.

**Comment by lbargaoanu** [comment]
It seems complicated. What about ```cfg.CreateMap<MySource, MyImplementation>(MemberList.None)``` instead? This will allow you to pass validation.

**Comment by Chips100** [comment]
Thank you for your quick responses; after fiddling around a little, I think I might have been a victim of the x-y problem. What I wanted to express was: "If I map some `MySource` onto something that implements `MyInterface`, I want these few properties mapped and nothing else.". In this situation, I guess it fits best to define the more general mapping **only** and define at that point that other members should be ignored (I was not aware that this works as I need it to). For the sake of completeness, I provide a full example that solves my problem.
Thanks for your help, I leave it up to you to decide if this issue can be closed or if you want to further investigate it (as you said, the original issue is still arguable IMO).

Solution that fixed my issue:

	interface MyInterface { string Test { get; set; } }

	class MyImplementation : MyInterface
	{
	    public string Test { get; set; }
	    public string Other { get; set; }
	}

	class MySource
	{
	    public string SourceTest { get; set; }
	    public string Other { get; set; }
	}

	static void Main(string[] args)
	{
		IMapper mapper = new Mapper(new MapperConfiguration(cfg =>
		{
		    cfg.CreateMap<MySource, MyInterface>()
			    .ForMember(dest => dest.Test, x => x.MapFrom(src => src.SourceTest))
			    .ForAllOtherMembers(x => x.Ignore());
		}));

		var source = new MySource() { SourceTest = "ShouldMap", Other = "ShouldNotMap" };
		var target = new MyImplementation() { Other = "KeepIt" };
		mapper.Map(source, target);

		// Writes nothing; I expected it to write "ShouldMap".
		Console.WriteLine("Result: {0} (Expected: ShouldMap)", target.Test);
		Console.WriteLine("Other: {0} (Expected: KeepIt)", target.Other);
		Console.ReadLine();
	}

**Comment by lbargaoanu** [comment]
It can be closed. We'll consider it again if another use case comes up.
