### ISSUE TITLE
confused of missing property of DTO 

### ISSUE THREAD

**Issue by chenzhikang** [AutoMapper/AutoMapper#1849]
Automapper version:4.2.1.0(nuget)
My mapping configuration code:
var mapping = cfg.CreateMap<Product, ProductDto>();
mapping.ForMember(de => de.Abstract, opt => opt.MapFrom(s => s.ProAbstract));

My call code:
     var   productDto = Mapper.Map<ProductDto>(product);//proudct is the entity 
something occurs:
I missing "Abstract" of productDto  occasionally ,and the value is null; but in other call method ,it comes right.wher i retry upload the dll ,it become OK.
I dont believe this is the automapper bug ,and my workmate never happened.but i was confused of this problem.
 can i solve this problem via upgrade the automapper?

**Comment by jbogard** [comment]
I'm guess it's a product of the threading problems of 4.2.1 and earlier. I'd suggest upgrading to the 5.x timeframe, where all the config model was overhauled to remove the threading issues.

**Comment by chenzhikang** [comment]
thanks
