### ISSUE TITLE
ResolveUsing ignores Condition (AutoMapper 5.2.0)

### ISSUE THREAD

**Issue by dmdymov** [AutoMapper/AutoMapper#1851]
[Gist with issue code](https://gist.github.com/dmdymov/dda231c096248b31134c50e3cbbc72b6).

Is it by design or is it a bug?

**Comment by lbargaoanu** [comment]
I think you want a precondition here.

**Comment by lbargaoanu** [comment]
We intend to expose the mapping execution plan and that will make this kind of thing easier to debug/understand.

**Comment by dmdymov** [comment]
Yes, you're right about precondition in my case. Thanks.
But why does [this page](https://github.com/AutoMapper/AutoMapper/wiki/Conditional-mapping) exist? It says clearly that mapping occurs **after** condition check, isn't it?

> AutoMapper allows you to add conditions to properties that must be met before that property will be mapped. 

And it would be very nice of you to reveal the mapping execution plan.

**Comment by lbargaoanu** [comment]
First we resolve the source value and then we map. The condition is executed after the source is resolved and before the destination is mapped. Feel free to change the wording to make it more clear.
