### ISSUE TITLE
 occurred in AutoMapper.dll but was not handled in user code

### ISSUE THREAD

**Issue by VentsislavDinev** [AutoMapper/AutoMapper#1852]
Hello, 
I use AutoMapper 4.2.1 and when I try to create a new item from my form. AutoMapper return this exception. "An exception of type 'AutoMapper.AutoMapperMappingException' occurred in AutoMapper.dll but was not handled in user code"
http://pastebin.com/WNCUxatu <- this is a my code with all info.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
Do you have the rest of the exception detail? This isn't really much to go on.
