### ISSUE TITLE
Property with same type and name is getting null value.

### ISSUE THREAD

**Issue by felipeoriani** [AutoMapper/AutoMapper#1853]
Hello. I am using autoMapper v5.2 in a project and I think I got an issue that I can't know how solve it.

I have the following classes:

```
public class User
{
    public virtual string Username { get; set; }
    // other properties
}

public class UserPrincipal
{
    public string Username { get; set; }
   // other properties
}
```

And map configuration:

```
config.CreateMap<User, UserPrincipal>(MemberList.None)
      .ForMember(x => Prop, opt => opt.Ignore(d => d.Prop);
```

I have written a unit test to check this mapping and everything works fine except the property Username.

```
var user = new User(); 
// fill up all properties..

var userPrincipal = Mapper.Map<UserPrincipal>(user);

// userPrincipal .Username is null
```

I get null value on the destination for the Username property. Other properties works fine. 
What am I doing wrong?
Thank you

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by felipeoriani** [comment]
I think I found the problem.

I have two constructors on the destionation. For sample:

public UserPrincipal() { }
public UserPrincipal(string username) { 
    this.Identity = new GenericPrincipal(username, "custom");
}

I just remove the first one and add the ConstructUsing on the Mapping rules and it works fine. I am not sure why it was happening but it works fine now. Close the issue.

Thakn you guys.

**Comment by jbogard** [comment]
You can close issues you create btw
