### ISSUE TITLE
Can auto mapper also create the new mapping DTO types

### ISSUE THREAD

**Issue by papyr** [AutoMapper/AutoMapper#1856]
Hi, I am new to DI, and really like the _autoness_ of this saving me writing a lot of mapping code, I need help in understanding if AutoMapper creates the DTO objects/types during the mapping as well.
 ```
  Mapper.Initialize(cfg => cfg.CreateMap<Dodge, DodgeDto>());
  Mapper.Initialize(cfg => cfg.CreateMap<Driver, DriverDto>());
```
Since the source  `Driver`  (an entity) the only place where I make changes, **can autoMapper create the target object type `DriverDTO`  automatically and what do I need to configure to do that?**, 

or do I need to predefine the `DriverDTO` before I create the mapping 
 ```
  //or do I need to predefine the `DriverDTO` before I create the mapping 
  public class DodgeDto {..}...
  .
  .
  Mapper.Initialize(cfg => cfg.CreateMap<Driver, DriverDto>());
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
I'd also start with the wiki - you're calling Initialize multiple times, it should only be called once.

**Comment by jbogard** [comment]
And no, it does not magically create destination types. You have to create types yourself.
