### ISSUE TITLE
Ignoring unmapped members after ConvertUsing

### ISSUE THREAD

**Issue by paradisehuman** [AutoMapper/AutoMapper#1859]
this is my code :
```c#
public class UserProfile:Profile
{
    public UserProfile()
    {
        CreateMap<UserViewModel, ApplicationUsers>().ConvertUsing<UserEncryptor>();
    }

}
public class UserEncryptor : ITypeConverter<UserViewModel, ApplicationUsers>
{
    private readonly IConfigurationRoot _configuration;
    public UserEncryptor(IConfigurationRoot configuration)
    {
        _configuration = configuration;
    }

    public ApplicationUsers Convert(UserViewModel source, ApplicationUsers destination, ResolutionContext context)
    {
        if (context==null||source == null) return null;
        var aes = new Common.EncryptionAes(_configuration[key: "Keys:AesKey"]);
        return new ApplicationUsers
        {
            UserName = aes.EncryptAes(source.Username),
            Email = aes.EncryptAes(source.Email),
            PhoneNumber = aes.EncryptAes(source.MobileNumber),
            User = new User
            {
                FirstName = aes.EncryptAes(source.FirstName),
                LastName = aes.EncryptAes(source.LastName),
                Gender = aes.EncryptAes(source.Gender.ToString()),
                ProfileImage = aes.EncryptAes(source.ProfileImage.FileName)
            }
        };
    }
}
```
**Note that ApplicationUsers is inherited from IdentityUser Class.**
When I tested this mapping,I got this error :

> System.NullReferenceException: Object reference not set to an instance of an object.

I know this error is for that some members are not ignored. Something like this
```c#
CreateMap<UserViewModel ,ApplicationUsers >()
.ConvertUsing(converter=> new ApplicationUsers(){
Email = converter.Email,
....
});
```
will help me because by default ignore rest of the members but the problem is that if I want to use this kind of code, I cant encrypt my members because I don't access to DI configuration for profile.Because profile is parameter less.

I need something similar to upper code that can implement in ITypeConverter functions.

Anyone has any solution ?

**Comment by jbogard** [comment]
I'm sorry, what's null exactly?

**Comment by paradisehuman** [comment]
@jbogard Some IdentityUser peroperties like NormalizedEmai, NormalizedUserName, PasswordHash and etc.

**Comment by lbargaoanu** [comment]
ITypeConverter is more flexible than a Func based converter so you should be able to write the code you need in your type converter. A repro would help. Make a gist that we can execute and see fail.

**Comment by paradisehuman** [comment]
@lbargaoanu 
**ApplicationUsers.cs:**
```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace PS.ModelBase.Models
{
    public class ApplicationUsers : IdentityUser<Guid>
    {
        [Column(TypeName = "nvarchar(max)")]
        public override string Email
        {
            get
            {
                return base.Email;
            }

            set
            {
                base.Email = value;
            }
        }
        [Column(TypeName = "nvarchar(max)")]
        public override string UserName
        {
            get
            {
                return base.UserName;
            }

            set
            {
                base.UserName = value;
            }
        }

    }
}

```
**ApplicationDBContext.cs**
```c#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace PS.Data
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUsers, Role, Guid>, IUnitOfWork
    {
        private readonly IConfigurationRoot _configuration;

        public ApplicationDbContext(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var useInMemoryDatabase = _configuration[key: "UseInMemoryDatabase"].Equals(value: "true",
                comparisonType: StringComparison.OrdinalIgnoreCase);
            if (useInMemoryDatabase)
                optionsBuilder.UseInMemoryDatabase();
            else
                optionsBuilder.UseSqlServer(
                    connectionString: _configuration[key: "ConnectionStrings:ApplicationDbContextConnection"]
                    , sqlServerOptionsAction: serverDbContextOptionsBuilder =>
                    {
                        var minutes = (int) TimeSpan.FromMinutes(3).TotalSeconds;
                        serverDbContextOptionsBuilder.CommandTimeout(commandTimeout: minutes);
                    });
        }

        protected override void OnModelCreating(ModelBuilder model)
        {
            base.OnModelCreating(builder: model);

        }
        public void AddRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        {
            Set<TEntity>().AddRange(entities: entities);
        }

        public void RemoveRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        {
            Set<TEntity>().RemoveRange(entities: entities);
        }

        public void MarkAsChanged<TEntity>(TEntity entity) where TEntity : class
        {
            Entry(entity: entity).State = EntityState.Modified; // Or use ---> this.Update(entity);
        }

        public void ExecuteSqlCommand(string query)
        {
            Database.ExecuteSqlCommand(sql: query);
        }

        public void ExecuteSqlCommand(string query, params object[] parameters)
        {
            Database.ExecuteSqlCommand(sql: query, parameters: parameters);
        }

        public int SaveAllChanges()
        {
            return SaveChanges();
        }

        public Task<int> SaveAllChangesAsync()
        {
            return SaveChangesAsync();
        }
    }
}
```
**IUnitOfWork,cs**
```c#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace PS.Data
{
    public interface IUnitOfWork : IDisposable
    {
        DbSet<TEntity> Set<TEntity>() where TEntity : class;

        void AddRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class;
        void RemoveRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class;

        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        void MarkAsChanged<TEntity>(TEntity entity) where TEntity : class;

        void ExecuteSqlCommand(string query);
        void ExecuteSqlCommand(string query, params object[] parameters);

        int SaveAllChanges();
        Task<int> SaveAllChangesAsync();
    }
}

```
**UserProfile.cs**
```c#
using System;
using AutoMapper;
using Microsoft.Extensions.Configuration;

namespace PS.ModelBase.MapperProfiles
{
    public class UserProfile:Profile
    {
        public UserProfile()
        {
            CreateMap<UserViewModel, ApplicationUsers>().ConvertUsing(source=>new ApplicationUsers
            {
                UserName = source.Username,
                Email = source.Email,
            });
        }
       
    }
}
```
upper code is worked perfectly... but something like this is not worked : 
```c#
using System;
using AutoMapper;
using Microsoft.Extensions.Configuration;

namespace PS.ModelBase.MapperProfiles
{
    public class UserProfile:Profile
    {
        public UserProfile()
        {
            CreateMap<UserViewModel, ApplicationUsers>().ConvertUsing<UserEncryptor>();
        }
       
    }
    public class UserEncryptor : ITypeConverter<UserViewModel, ApplicationUsers>
    {
        private readonly IConfigurationRoot _configuration;
        public UserEncryptor(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        public ApplicationUsers Convert(UserViewModel source, ApplicationUsers destination, ResolutionContext context)
        {
            if (context==null||source == null) return null;
            
            var aes = new Common.EncryptionAes(_configuration[key: "Keys:AesKey"]);
            return new ApplicationUsers
            {
                UserName = aes.EncryptAes(source.Username),
                Email = aes.EncryptAes(source.Email),
                PhoneNumber = aes.EncryptAes(source.MobileNumber)
            };
        }
    }
}
 
```
Even something like this also will not work : 
```c#
using System;
using AutoMapper;
using Microsoft.Extensions.Configuration;

namespace PS.ModelBase.MapperProfiles
{
    public class UserProfile:Profile
    {
        public UserProfile()
        {
            CreateMap<UserViewModel, ApplicationUsers>().ConvertUsing<UserEncryptor>();
        }
       
    }
    public class UserEncryptor : ITypeConverter<UserViewModel, ApplicationUsers>
    {
        private readonly IConfigurationRoot _configuration;
        public UserEncryptor(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        public ApplicationUsers Convert(UserViewModel source, ApplicationUsers destination, ResolutionContext context)
        {
            if (context==null||source == null) return null;
            
            return new ApplicationUsers
            {
                UserName = source.Username,
                Email = source.Email,
                PhoneNumber = source.MobileNumber
            };
        }
    }
}

```
**and this is the testclass :** 
```c#
 using System;
using System.Collections.Generic;
using System.IO;
using AutoMapper;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.AspNetCore.Http;

namespace PS.ModelBaseTest
{   [TestClass]
    public class UserProfileTest
    {
        private readonly IServiceProvider _serviceProvider;
        public UserProfileTest()
        {
            var services = new ServiceCollection();
            services.AddSingleton(provider => new ConfigurationBuilder()
                .AddInMemoryCollection(initialData: new[]
                {
                    new KeyValuePair<string, string>(key: "UseInMemoryDatabase", value: "true"),
                    new KeyValuePair<string, string>(key: "Keys:Aeskey",
                        value: "nF27vbvemMKNV4io5p6rhQRYS1S7uft6HRjgzPtoeKw=")
                })
                .Build());
            services.AddAutoMapper(cfg =>
            {
                cfg.AddProfile<UserProfile>();
            });
            _serviceProvider = services.BuildServiceProvider();
        }

        [TestMethod]
        public void Verify_AutoMapper_Encryption()
        {
            using (var serviceScope = _serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {

                var mapper = serviceScope.ServiceProvider.GetRequiredService<IMapper>();
                var user = new UserViewModel
                {
                    Email = "2424ddgas@yahoo.com",
                    MobileNumber = "test",
                    Password = "test",
                    ReTypePassword = "test",
                    Username = "test",

                };
               var result= mapper.Map<ApplicationUsers>(user);
                mapper.ConfigurationProvider.AssertConfigurationIsValid();
            }

        }
    }
}

```

**Comment by lbargaoanu** [comment]
I suppose what you mean is that DI is not working for you. See https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection. UserEncryptor is not registered with your container.

**Comment by lbargaoanu** [comment]
I guess I was wrong, the package should do that for you. So I'm missing your point. That's way too much code. Isolate things to a gist that depends only on AM.

**Comment by paradisehuman** [comment]
@lbargaoanu  I registered DI in my test constructor.
OK I will Please wait.

**Comment by paradisehuman** [comment]
@lbargaoanu I edited the previous code

**Comment by lbargaoanu** [comment]
I was able to run [smth](https://gist.github.com/lbargaoanu/d973807dc0ccd8f990675ef0f740a8b3#file-identityuser-cs) close to your code. What I see is that the members you set have the right values and the rest the defaults. So what's wrong? :) Modify my gist and add asserts to highlight the problem.

**Comment by paradisehuman** [comment]
Ok thank you for your code . I cant work perfectly with Github and I dont know how can I add assert to highlight your code . but the point of your code was this : 

> var mapper = config.CreateMapper(); 

When I modify my code and doing something like you do ,in my test I have one change: 

> var mapper = serviceScope.ServiceProvider.GetRequiredService<IMapper>().ConfigurationProvider.CreateMapper();

Every thing is going fine and you are right, But when I create a constructor for UserConvertor for adding configuration DI, I got another error :

```c#
public class UserConvertor : ITypeConverter<UserViewModel, ApplicationUsers>
    {
        private readonly IConfigurationRoot _configuration;
        public UserEncryptor(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        public ApplicationUsers Convert(UserViewModel source, ApplicationUsers destination, ResolutionContext context)
        {
            if (context==null||source == null) return null;
            
            var aes = new Common.EncryptionAes(_configuration[key: "Keys:AesKey"]);
            return new ApplicationUsers
            {
                UserName = aes.EncryptAes(source.Username),
                Email = aes.EncryptAes(source.Email),
                PhoneNumber = aes.EncryptAes(source.MobileNumber),
                User = new User
                {
                    FirstName = aes.EncryptAes(source.FirstName),
                    LastName = aes.EncryptAes(source.LastName),
                    Gender = aes.EncryptAes(source.Gender.ToString()),
                    ProfileImage = aes.EncryptAes(source.ProfileImage.FileName)
                }
            };
        }
	
```

> Result StackTrace:	
> at lambda_method(Closure )
>    at AutoMapper.Mappers.ObjectCreator.CreateObject(Type type)
>    at AutoMapper.MappingOperationOptions`2.CreateInstance[T]()
>    at lambda_method(Closure , Object , Object , ResolutionContext )
>    at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
>    at PS.ModelBaseTest.UserProfileTest.Verify_AutoMapper_Encryption() 
> 
> Result Message:	
> Test method PS.ModelBaseTest.UserProfileTest.Verify_AutoMapper_Encryption threw exception: 
> System.ArgumentException: PS.ModelBase.MapperProfiles.UserEncryptor needs to have a constructor with 0 args or only optional args
> Parameter name: type

**Comment by lbargaoanu** [comment]
So DI is the problem after all. The code you had initially with CreateScope looked reasonable. Doesn't that work?

**Comment by paradisehuman** [comment]
@lbargaoanu  for another scenarios DI worked without any problem, but when the target class is inherited from IdentityUser , does't work ....

**Comment by lbargaoanu** [comment]
It's still not clear what the actual error is.

**Comment by paradisehuman** [comment]
the last error was this : 

> System.ArgumentException: PS.ModelBase.MapperProfiles.UserConvertor needs to have a constructor with 0 args or only optional args
> Parameter name: type

the first error was this :

> System.NullReferenceException: Object reference not set to an instance of an object.

I'm getting mad of this :(

**Comment by paradisehuman** [comment]
@lbargaoanu  either I cant use DI in Profile constructor ....

**Comment by lbargaoanu** [comment]
That doesn't help. The first error is because that last code you posted is broken, it forces AM to create the resolver and that fails. The initial error is too generic. It's up to you to debug your app and isolate the issue. Anyway, at this point it's pretty clear the problem is not with AM. It's your code or the DI AM package. But again, it's hard to tell.

**Comment by jbogard** [comment]
Wait, you have this?

```
var mapper = serviceScope.ServiceProvider.GetRequiredService<IMapper>().ConfigurationProvider.CreateMapper()
```
?

**Comment by paradisehuman** [comment]
@jbogard Yes, after the guidance of @lbargaoanu,I add this to my code and I get another error :

> System.ArgumentException: PS.ModelBase.MapperProfiles.UserConvertor needs to have a constructor with 0 args or only optional args
> Parameter name: type

**Comment by jbogard** [comment]
You should only go from GetRequiredService, not IMapper.ConfigurationProvider.CreateMapper. Have you looked at the example in the AutoMapper DI repo? It shows this exact scenario.

**Comment by paradisehuman** [comment]
@jbogard In the first code,I didn't have the 'IMapper.ConfigurationProvider.CreateMapper', this worked for another scenarios but when the destination class is inherited from IdentetyUser, it doesn't work and this error shows :

> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by jbogard** [comment]
OK I'm getting totally confused about your isolated issue. Do you have a link to a VS solution with your original problem?

**Comment by paradisehuman** [comment]
@jbogard 
https://drive.google.com/open?id=0B6ty2MRAzdqkVFdrd3VXZ09LaGs

It's worked:
PS.Common->MappingProfiles->LogProfile.cs
PS.CommonTest->LogProfileTest.cs

It's not worked :
PS.ModelBase->MappingProfiles->UserProfile.cs
PS.ModelBaseTest->UserProfileTest.cs

**Comment by jbogard** [comment]
Yep, definitely not working for me locally. Just to eliminate some variables, I copied the registration code straight into the test so that I can debug locally.

**Comment by jbogard** [comment]
OK I found the issue - when you don't pass in the assemblies you want to scan for registering type converters, value resolvers etc. to AddAutoMapper, it will look in a special place to determine what assemblies to look for AutoMapper classes, a "DependencyContext" (by default, DependencyContext.Default). This replaces the AppDomain way of probing the current running context for "what assemblies are loaded".

I go through these assemblies and figure out which ones to search the types for AutoMapper types. Searching through EVERY type would be quite expensive, and in fact, in your app there are > 200 assemblies in the dependency context!

Instead, I try to be smart and look at the assembly's references to see if it references AutoMapper.

The problem is I only search one level deep, and your test project does not *directly* reference AutoMapper. Instead, it's a dependency of a dependency. And unfortunately, it would be pretty hard to trawl through that tree to figure out what references what and who actually uses AutoMapper.

There are two easy ways to fix this:

- Reference AutoMapper in your test assembly
- Explicitly pass in the array of assemblies to probe for AutoMapper config <- THIS IS THE MOST EXPLICIT AND OBVIOUS

One last thing - I probe and find Profiles automatically, so your "AddProfile" is redundant. I made the test pass by changing your config to:

```
services.AddAutoMapper(typeof(UserProfile));
```

**Comment by paradisehuman** [comment]
@jbogard Thank you for taking your time ....
Finally the problem was solved :))

**Comment by lbargaoanu** [comment]
@jbogard I've added a null check to CreateInstance for this exact scenario. Did I miss smth or the AM version is before that [fix](https://github.com/AutoMapper/AutoMapper/pull/1687)? 5.2.0 should have it I believe.

**Comment by jbogard** [comment]
It's 5.0.2 as that's what the DI package references. This is a bug in the DI extension library, so I can push out an update that uses the latest 5.2 version.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jbogard** [comment]
This issue was moved to AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#11
