### ISSUE TITLE
AutoMapper 5: Unit testing ValueResolvers and TypeConverters

### ISSUE THREAD

**Issue by thomasgalliker** [AutoMapper/AutoMapper#1864]
I'm about to upgrade an application from Automapper 4.2.1 to 5.2.0 and it turns out to be a huge effort to migrate the existing 110 Profiles, 130 ValueResolvers and 20 TypeConverters. Particularly when I try to adjust the unit tests. Hope there is someone who can give clarifications on these topics:

(1) In AutoMapper 4.x there was a way to define a ResolveUsing<ValueResolver> without specifying the destination property type. It seems as I strictly have to bind my value resolvers to a certain destination property? Correct? - I liked the ResolveUsing<Resolver> way of AutoMapper 4 because it allowed me to focus purely on resolving the desired value from the source object (e.g. a string value) while AutoMapper cared about converting the resolved value to the destination property's type (e.g. a decimal).

(2) In AutoMapper 4.x I could test ValueResolvers by simply instanciating them and calling their protected ResolveCore method with all kinds of test source values. What is the intended way of testing ValueResolvers in AutoMapper 5.x? Particularly: How can I pass a valid ResolutionContext to the fourth Parameter of Resolve method?

(3) Similar as question (2): How can I test TypeConverters? I wrote my own TypeConverterTestBase which sets up a new mapping using ConvertUsing<Converter> but there is maybe a better, official way of doing unit tests with TypeConverters?

Thanks for all hints & help in guiding me to the right direction.
Thomas

**Comment by lbargaoanu** [comment]
I think the best way would be to write testable code in the first place, code that doesn't depend on AM and test that, make the AM types just thin wrappers that don't need unit testing. One way to get a hold of a context is [here](https://github.com/AutoMapper/AutoMapper/blob/8980eb6a4d5f91a0fce38915684614f35e315143/src/UnitTests/BuildExecutionPlan.cs#L51). It won't work in all cases, but it will let you know :) You might want to check [the upgrade guide](https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide).

**Comment by jbogard** [comment]
I had the same effort on my side to update the tests in the 5.0 codebase. Wasn't terrible, took me about an hour or two.

1) No, your value resolvers can use "object" as its generic parameters if you don't want to bind to a specific source/destination type. Because those parameters are variant it all works out. Or you can make the custom resolver generic to fill in the type parameters, but "object" is the easiest path.

2) Just "new" one up. There's a "MappingOperationOptions" class to help with that, you have to pass in the mapper object and configuration. ResolutionContext is now more "MappingContext" but I thought changing the name would be pretty annoying.

3) Not really anything official. Just call Convert on your type converter, also passing in a ResolutionContext like before.

**Comment by lbargaoanu** [comment]
Of course converting value types to object causes some overhead, mainly allocations, but maybe that's not relevant.

**Comment by thomasgalliker** [comment]
Lucian and Jimmy, **thank you** both for your time and enthusiasm you put into AM!

I think the testing point is just a matter of time to solve it. We also had discussions in our company whether or not to test ValueResolvers, TypeConverters and Profiles. I think it pays off in our case to have a small-meshed test harness since we have a lot of (overly) complex, heavily nested classes to map from.

(1) I get your point but maybe I didn't fully arrive in the world of AM 5.x yet. Let's have a look at following example:

I have a simple FlagToBooleanResolver : ValueResolver<FLAG, bool>which aims to resolve a bool/bool? value from an enum FLAG (which has Undefined/True/False as values).
Now, I try to reuse this resolver to map to a destination property of type Nullable<bool> and to a property of type bool.

In AM 4.x, this is how the CreateMap code looked like:
```
.ForMember(dest => dest.NullableBoolProp, opt => opt.ResolveUsing<FlagToBooleanResolver>(src => src.FlagEnumProp))
.ForMember(dest => dest.BoolProp, opt => opt.ResolveUsing<FlagToBooleanResolver>(src => src.FlagEnumProp))
```

In AM 5.x, we have to specify the source property type and the destination property type otherwise the compiler doesn't eat it.
```
.ForMember(dest => dest.NullableBoolProp, opt => opt.ResolveUsing<FlagToBooleanResolver<bool?>, FLAG>(src => src.FlagEnumProp))
.ForMember(dest => dest.BoolProp, opt => opt.ResolveUsing<FlagToBooleanResolver<bool>, FLAG>(src => src.FlagEnumProp))
```
It seems as AM 4 was able to determine source and destination property types automatically, while I have to be very specific in AM 5?

**Comment by lbargaoanu** [comment]
For example you can do smth like [this](https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-265670132).

**Comment by jbogard** [comment]
I could try and make things a bit simpler by providing interfaces with those parts already filled in, I wonder if that would help? I wouldn't add more overloads though, there's enough of those.

**Comment by lbargaoanu** [comment]
@jbogard We want to make it clear that you can also use an object based resolver, but I don't think just adding an interface would help. For discoverability we would need some method to use it explicitly.

**Comment by jbogard** [comment]
What do you mean, like a config method?

**Comment by lbargaoanu** [comment]
No, another resolve method, something like ```UntypedResolve(IUntypedResolver)```.

**Comment by lbargaoanu** [comment]
Maybe forget about it and just add smth in the docs.

**Comment by lbargaoanu** [comment]
Maybe I should have checked the docs first :)
