### ISSUE TITLE
Mapping nullable does not use nullable map when called with a non-null value

### ISSUE THREAD

**Issue by lemvigh** [AutoMapper/AutoMapper#1865]
Hi,

After upgrading to 5.2.0 I am having issues with mapping nullables: A map configured for a nullable type does not seem to be used if map is called with a non-null value, even if the nullable type is explicitly stated in the map method. We have several cases where we have a nullable enum mapped to a regular enum with special handling of the null and some transformation of other values. For these all non-null values are mapped using the standard mapping. The below simplified example shows it also fails for nullable ints. This issue seems to have been introduced between 5.1.1 and 5.2.0. Is this change of behavior intentional, and will I have to split my mapping into two?

```C#
[TestClass]
public class NullableMappingTests
{
	public enum GreekLetters
	{
		Alpha = 11,
		Beta = 12,
		Gamma = 13
	}

	[TestMethod]
	public void Convert_using_is_not_called_when_mapping_nullable_ints()
	{
		var mapper = new MapperConfiguration(cfg => cfg
				.CreateMap<int?, GreekLetters>()
				.ConvertUsing(n => n == null ? GreekLetters.Beta : GreekLetters.Gamma))
			.CreateMapper();

		Assert.AreEqual(GreekLetters.Beta, mapper.Map<int?, GreekLetters>(null), "This passes");
		Assert.AreEqual(GreekLetters.Gamma, mapper.Map<int?, GreekLetters>(42), "This Fails");
	}
}
```

**Comment by lbargaoanu** [comment]
((int?)42).GetType() is int32. Two maps or one map and NullSubstitute I would say. By default null will map to 0.

**Comment by lemvigh** [comment]
Yes, but there are two types to choose from: the actual type as you point out, but the Map method says mapper.Map<int?, GreekLetters>(42) and typeof(int?) is after all int?. If we take a similar inheritance based example and do something like this:
```
var mapper = new MapperConfiguration(cfg => cfg
		.CreateMap<IList<string>, string>()
		.ConvertUsing(n => string.Join(",", n)))
	.CreateMapper();

var mapped = mapper.Map<IList<string>, string>(new [] {"a", "b", "c"});
```
I get "a,b,c", and not "System.String[]" that would be the default mapping - since new[] { "a", "b", "c" }.GetType() is "System.String[]" and not IList<string>...

**Comment by lbargaoanu** [comment]
You seem to be arguing my point :) Only the runtime type matters and that's int.

**Comment by lemvigh** [comment]
Please excuse me, I'm not trying to argue with your point, I'm just trying to highlight why I was confused, and from your reply I wasn't sure if that was clear. And I still think it is confusing. The runtime type in my second example is string[] but it still matches a more general mapping rule (IList<string>). Why couldn't the same be the case for int and Nullable<int>? The set of Nullable<int> include the set of int and if a mapping is defined for Nullable<int> and not for int - isn't it intuitive to think the Nullable<int> mapping would be used for mapping int - especially when the Map method is marked with the nullable type?

**Comment by lbargaoanu** [comment]
I was trying to say that your example just shows that only the runtime type matters. The generic type parameter dosn't matter unless the source object is null. What you expect might be reasonable, but it happens that the runtime type is int and that causes the behavior you see.

**Comment by lbargaoanu** [comment]
And, just to be precise, string[] **is** IList, but int **is not** int?. So it would have to be special cased to behave the same way. What actually happens is that null maps to the default value for the destination and for non nulls a map for the underlying type will match.

**Comment by lemvigh** [comment]
But in this example 42 is an int? - the implicit conversion makes sure of that. I get that GetType() of a nullable type returns the underlying type, but that just adds to the confusion. I've also noticed that for properties it seems the type of the property is used, not GetType() on the value of the property, so depending on context I get different results for the same types:
```
private class Source
        {
            public Source(int? value)
            {
                Field = value;
            }

            public int? Field { get; set; }
        }

        private class Target
        {
            public long Field { get; set; }
        }
        
        [TestMethod]
        public void AnotherTest()
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<int?, long>()
                    .ConvertUsing(s => 12);
                cfg.CreateMap<Source, Target>();
            }).CreateMapper();
                       
            Assert.AreEqual(5, mapper.Map<int?, long>(5));
            Assert.AreEqual(12, mapper.Map<Source, Target>(new Source(5)).Field);
        }
```

**Comment by lbargaoanu** [comment]
Yes, and probably that will always be the case. I think what happens here is that for the cases when it matters, for inheritance, eventually Map is called again and the runtime types are used.

**Comment by lbargaoanu** [comment]
@jbogard I think we could make this work by trying first to match on runtime types and, if that fails, on requested types, but I don't know...

**Comment by jbogard** [comment]
@lbargaoanu we could try. We had something similar a while back but the logic got weird with what types the runtime types were versus what we "thought" the types should be based on either the top-level generic arguments or examining member types.

I tried a while back in the 5.x codebase, but some tests failed and I more or less abandoned it. But if it's a common request, it could be worth re-examining.
