### ISSUE TITLE
Need to get ProfileConfiguration before sealed

### ISSUE THREAD

**Issue by TylerCarlson1** [AutoMapper/AutoMapper#1866]
AutoMapper.Collection.EF needs the configuration to get property maps for types so that it can auto generate comparisons.  If you use a convention to do mappings there's no problem, because the type maps are generated after the seal where AM.Collection.EF can resolve the type maps and get generated.

Problem is if you explicitly do the mappings they will get sealed and not be able to resolve equivalency using AutoMapper.Collection.EF.  It can't be used because by the time it can get set all the type maps have been sealed and can't be changed.

What I'm suggesting is have a pre-sealed eventhandler that passes IProfileConfiguration, so I can hook into to set up AutoMapper.Collection.EF to use it before types get sealed.  Or possibly an action that can be set in IMapperConfigurationExpression that gets called before sealed.  That way before the expressions are generated, AutoMapper.Collection.EF can be set up to use said maps to update collections.

Right now the work around is to create/initialize IMapper twice.  Once to make the maps in which AutoMapper.Collection.EF can use the configuration.  And a second time to re-do the mappings, but allowing AutoMapper.Collection.EF to do its thing.

In 4.2.x this wasn't a problem because of how the nature of AM worked before.  Type maps weren't sealed until used and that way you could put them after the configuration without issue.

I'm willing to make a PR for this,  I just wanted to explain what's going on first.

**Comment by jbogard** [comment]
What exactly are you doing in the comparison generation? 

I used to have an event a while back, but I thought there could be a better way of doing this, would the ForAllTypeMaps stuff not work?

**Comment by TylerCarlson1** [comment]
When generating the mapping expression of Parent to ParentDto and you get to a property that maps `IList<Child> -> IList<ChildDto>` I need to resolve the TypeMap Child->ChildDto so that I can identify primary keys in ChildDto and generate an equivalency expression based on that property maps.  Currently I resolve the type map by getting the IConfigurationProvider and calling ResolveMap and then seeing if it matches by keys.

Currently there's no way to make it work with the ForAllTypeMaps function.  I guess I could make it work to some extent though, given it gets executed before generating map expressions.

That's not how I intended it to work at all, but I might be able to do that.  Although right now it seems kind of a hack to get it to work with the public API as it stands now.

**Comment by jbogard** [comment]
Is there something we can do BESIDES an event? Those are just...icky which is why I took them out. Is there something in addition to ForAllTypeMaps, like a BeforeSeal or similar?

**Comment by TylerCarlson1** [comment]
I'm thinking adding BeforeSeal would be the best option.
Currently I'm looking into just trying to use ForAllTypeMaps and it might work. (Got it to build, haven't tested in app)  Don't know if going to have problems or not with types or execution generation until I try it out.

I think I'll look into using ForAllTypeMaps implementation first, and if it doesn't pan out I'll make a PR for BeforeSeal function.  I don't know what you think about BeforeSeal function in general, apart from not an event.  It would definitely be for Super Advance users only most likely.

**Comment by TylerCarlson1** [comment]
Yea looking at ForAllTypeMaps it solves the problem of existing maps, but now conventions don't work.  If I were to get it to work like this what I would need to do is pass IConfigurationProvider through the `IObjectMapper.IsMatch` interface.  If I had that there I could try resolving the TypeMap which will call ForAllTypeMaps and then see if there's a match afterwards.

I would probably prefer passing IConfigurationProvider over IsMatch call, over creating BeforeSeal method.  It seems more internal logic this way, and it seems less hacky to not have to make a new configuration method.  @jbogard do you have any issues with adding IConfigurationProvider to IsMatch call?  I know none of the current mappers use it but mine would need it.

Also in refactoring I eliminated some redundant code and I like the way the API is now all extension methods off of the configuration expression, so it's all within the configuration logic.  I can still go back and do BeforeSeal and keep same API though.

**Comment by TylerCarlson1** [comment]
bump

**Comment by jbogard** [comment]
It's still weird that you have to "try" to create the TypeMap first. If you have BeforeSeal, wouldn't that still run for convention-created type maps?

**Comment by TylerCarlson1** [comment]
If I had BeforeSeal it would.  It would work like it currently does, but now it's just I'm setting it up before any and all TypeMaps get generated convention or explicit.  Before the explicit type maps get created before I can do my setup.

And yes it is a little weird, but that's how it works if I use ForAllTypeMaps and not have BeforeSeal.  I have to resolve the type map no matter what because I need to know the property maps.  Also I really should know if a type map exists before trying to make an equivalency expression of it.

I just like ForAllTypeMaps now because it's more readable and easy to follow IMO then the old system was.

**Comment by jbogard** [comment]
Oh, well I'm OK with having BeforeSeal. I wonder though, it's weird to have this exposed as a top-level property, would it be worth doing something similar to RavenDB and do cfg.Advanced.BeforeSeal or like MVC Core and cfg.Extensions.BeforeSeal ?

**Comment by TylerCarlson1** [comment]
I like Advanced better, because you need to be an advanced user to know what to do with this, and I'm sure we can find more things to put into Advanced in the future for more complicated things.

Yea I didn't like BeforeSeal being at top level as well, and that was one of the big reasons I perfered the ForAllMaps approach.
