### ISSUE TITLE
Dynamic projection via ProjectTo Queryable Extension

### ISSUE THREAD

**Issue by MehdiSaeedifar** [AutoMapper/AutoMapper#1868]
Hi,

In our project, the user can select columns of datatable dynamically. Our question is how can we write configuration mappings that ignore properties that not selected by user.

I try some solutions, but because **Projections are only calculated once and cached** there isn't any chance for recalculating and projecting properties based on new parameter value.

For example we want to do something like this:

```
public class User
{
    public int Id { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
}
```

```
public class UserDto
{
    public string UserName { get; set; }
    public string Email { get; set; }
}
```
**Mapping Configurations:**
```
        configuration.CreateMap<User, UserDto>()
            .ForMember(domain => domain.UserName, opt =>
            {
                var param = (string[])opt.ProjectToParam(); // Imaginary method that return list of columns that sent by ProjectTo

                if (!param.Contains(nameof(UserName)))
                {
                    opt.Ignore();
                }

            }).ForMember(domain => domain.Email, opt =>
            {
                var param = (string[])opt.ProjectToParam(); // Imaginary method that return list of columns that sent by ProjectTo

                if (!param.Contains(nameof(Email)))
                {
                    opt.Ignore();
                }

            });
```

**Calling ProjectTo:**

```
var selectedFields = new[] { "User" };

query.AsNoTracking().ProjectTo<UserDto>(selectedFields); // but we cant pass paramater here
```

Thanks.

**Comment by lbargaoanu** [comment]
You can try explicit expansion and specify what to fetch when projecting.

**Comment by jbogard** [comment]
But that won't work if you're trying to do explicit field-by-field selection. I'm not sure AutoMapper would be a good fit for you if so. Why even use DTOs at that point?

**Comment by MehdiSaeedifar** [comment]
@iaingalloway 

It works like a charm. Thank you so much.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by felipedrumond** [comment]
@MehdiSaeedifar, would you mind sharing your implementation?

**Comment by MehdiSaeedifar** [comment]
@felipedrumond of course.

For example for UserDto you should use **IgnoreAllNonExisting** in your mapping configuration:

```
configuration.CreateMap<User, UserDto>()
    .ForMember(m => m.UserName, opt => opt.MapFrom(d => d.UserName))
    .ForMember(m => m.Email, opt => opt.MapFrom(d => d.Email))
    .IgnoreAllNonExisting();
```

Then when calling **ProjectTo** extension method, you should provide an array of  members name that you want fetch from database via **membersToExpand** parameter.

```

    query
    .ProjectTo<UserDto>(MappingEngine.ConfigurationProvider, new[] {"UserName"}));
```

**Comment by MehdiSaeedifar** [comment]
@felipedrumond of course.

For example for UserDto you should use **ForAllMembers** in your mapping configuration:

```
configuration.CreateMap<User, UserDto>()
    .ForMember(m => m.UserName, opt => opt.MapFrom(d => d.UserName))
    .ForMember(m => m.Email, opt => opt.MapFrom(d => d.Email))
    .ForAllMembers(x=> x.ExplicitExpansion());
```

Then when calling **ProjectTo** extension method, you should provide an array of  members name that you want fetch from database via **membersToExpand** parameter.

```
query
    .ProjectTo<UserDto>(MappingEngine.ConfigurationProvider, null, new[] {"UserName"}));
```

**Comment by felipedrumond** [comment]
Thanks @MehdiSaeedifar!

I thought it would work with any instance of T, but it actually seems to needs a IQueryable<T> to do the trick. Anyway, it is great to know that we can work together with EF to query only the fields we really need.
Where MappingEngine.ConfigurationProvider comes from? I couldn't compile my code because I wasn't able to find this name.

**Comment by MehdiSaeedifar** [comment]
@felipedrumond 

MappingEngine.ConfigurationProvider refers[ to this article](https://github.com/AutoMapper/AutoMapper/wiki/Static-and-Instance-API).

I'm using Instance API of automapper.
