### ISSUE TITLE
Enum Not Mapping in 5.2.0

### ISSUE THREAD

**Issue by phil000** [AutoMapper/AutoMapper#1870]
upgraded from 4.2.1 to 5.2.0 and what used to map no longer maps, the destination property is now null - although `AssertConfigurationIsValid` still passes. We made no changes to the mapping configuration.
source:
`public GroupScope Scope { get; set; }`
dest:
`public string Scope { get; set; }`
map:
`CreateMap<SecurityGroup, GroupResponse>();`

**Comment by phil000** [comment]
May duplicate #1862

**Comment by lbargaoanu** [comment]
It does, if you're mapping the default value.

**Comment by lbargaoanu** [comment]
This can be closed.
