### ISSUE TITLE
How to write an unit test that uses AutoMapper inside?

### ISSUE THREAD

**Issue by felipeoriani** [AutoMapper/AutoMapper#1871]
Hi, My team and me have a question about how to make some test using the autoMapper configuration I have for the application. we use the static scope.

I have the following mapping configuration:
```
config.CreateMap<State, StateViewModel>(MemberList.None)
      .ReverseMap()
      .AfterMap((vm, e) => { 
           // it is necessary because nhibernate will save this relation
           var cityRepository = container.Resolve<ICityRepository>(); 
           e.City = cityRepository.Load(vm.CityId);
       });
```	   
I call the Map method on the StateService class (business) which works fine to convert the ViewModel to State.
Now, we are trying to write a unit test for the Save method and we are mocking the repositories. 
The problem is that we have the AfterMap configured for this mapping which uses the IoC container to resolve City property.

We do no use the IoC container on the Unit Test and I would like to know how to resolve this item on the AfterMap. We have some possible solutions:

1. Remove this routine from the AfterMap and move to Service class. The problem with this is we have more than 400 mappings over the system and we should increase the complexity over the dependency injection on the constructor, just to use a simple .Load. We could moq this another repository.

2. Duplicate the AutoMapper configuration to Unit Test class. The problem with this is we will duplicate the code and we will be not testing a part of the real code. There are a lot of mappings configuration using ForMember method and would be difficult to keep both mappings aligned.

How could we take it done?

Maybe if we have a way to disable AfterMap on the Test project, but not sure if autoMapper has this option.

Thank you!

**Comment by jbogard** [comment]
OK first of all, you shouldn't be using AfterMap, you should use a custom resolver for that. Second, your resolver should take a dependency on ICityRepository.

Finally, you can inject your IMapper into whatever is calling Map, and configure the Mapper instance to get the container factory method passed in.

Then, if you wanted, you could mock the IMapper or ICityRepository call.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Dependency-injection

**Comment by felipeoriani** [comment]
Thank you guys. I tried what you said and tt is working as a sample for my unit test. Now I have the work to remove the AfterMap from my mappings and create the custom resolvers. I have a new question related with this.

I have more than 400 resolvers to create and most of them is used just to call the repository and Load method (to call session.Load passing the viewModel.id from nhibernate). Give most of my viewModels has a EntityId (long) and the Entity has the a reference to another Entity, is there any way to create a custom resolver to map "long" to "Entity", because I can have more entities with the same reference. See my code
```
// my viewModel
public class StateViewModel 
{
    // properties
   public long CityId { get; set; }
}

// my Domain-model
public class State
{
    public City City { get; set; }
}


Mapper.Initialize(config =>
{
  // I use mocks here to define my repositories
  // I will configure container on the system
  config.ConstructServicesUsing(ConstructResolvers); 

  config.CreateMap<StateViewModel, State>(MemberList.None)
		.ForMember(x => x.Country, opt => opt.ResolveUsing<CountryResolver>())
		.ReverseMap();
});

public class CountryResolver : IValueResolver<StateViewModel, State, City>
{
	private readonly ICountryRepository _countryRepository = null;

	public CountryResolver(ICountryRepository countryRepository)
	{
		_countryRepository = countryRepository;
	}

	public City Resolve(StateViewModel source, State destination, City destMember, ResolutionContext context)
	{
		return _countryRepository.Load(source.CountryId);
	}
}
```

My question is I have 

> IValueResolver<StateViewModel, State, City>

I have more viewModels where I need to map long to City and it is not on the StateViewModel/State. Is there any way to configure it to map from the City entity from a long?

Obs: desconsider City, it is about States and Countries (just to have a sample for more complex scenarios)

**Comment by lbargaoanu** [comment]
You can go with [the object version](https://github.com/AutoMapper/AutoMapper/issues/1864#issuecomment-268805067).

**Comment by jbogard** [comment]
I think for the "long -> Entity" version you can use a type converter w/ open generics:

```
public class EntityTypeConverter<TEntity> : ITypeConverter<long, TEntity> {
// Use the repository here and hopefully you have an IRepository<T>, else use ISession
}
```

Now comes the problem - registration. Right now this is...annoying, you have to use reflection to find all the "TEntity" closed types and call CreateMap:

```
foreach (var t in GetEntityTypes()) {
    cfg.CreateMap(typeof(long), t).ConvertUsing(typeof(EntityTypeConverter<>).MakeGenericType(t));
}
```

I think I can make this easier, but it would mean I'd need to add a way to add type converters without calling CreateMap.

**Comment by felipeoriani** [comment]
Jimmy, 

I think I am doing somthing wrong. How can I configure this like you said? I mean, the CountryId is a property inside my StateViewModel and I want to set it on Country object. How do I configure this converter? I worked with Custom Resolver but I need to do it for each mapping configuration where I use Country for sample (State, Project, Customer, Supplier, etc..).

I saw your suggestion to do the generic loop, but it seems that I am trying to convert long to entity, and not a long property to entity (resolving by context) Maybe a generic Resolver, I've tried it here, but no success. What I would like to have is a way to define a converstion from a long property (value) to aa complex object (like I did on AfterMap, but it is a wrong way). Is it difficult?

**Comment by felipeoriani** [comment]
Jimmy, I think I found a solution, but I am not sure if it is something good to do with AutoMapper.
I have a custom resolver now that works fine. Is it a correct way to do?

My mapping configuration for the property:
```
.ForMember(x => x.Country, opt => opt.ResolveUsing<CountryResolver>())
```

and my custom generic resolver:
```
public class CountryResolver : IValueResolver<object, object, Country>
{
	private readonly ICountryRepository _countryRepository = null;

	public CountryResolver(ICountryRepository countryRepository)
	{
		_countryRepository = countryRepository;
	}

	public Country Resolve(object source, object destination, Country destMember, ResolutionContext context)
	{
		// that is the hammer haha, but worked!
		var countryId = source.GetType().GetProperty("CountryId").GetValue(source);

		return _countryRepository.Load(countryId);
	}
}
```

Is it fine?


-----

I do not know how autoMapper does the magic internally, but, maybe a design to make complex conversions like this in the future versions would  be nice (just a sugestion):
```
config.CreateMap<TSource, TDestionation>()
  .ForMember(source => source.Entity, opt => opt.ConvertUsing<EntityConverter>(dest => dest.EntityId))

public class EntityConverter : ITypeConverter<long, Entity>
{
   public Entity Convert(long source, Entity destination, ResolutionContext context)
   {
      // custom logic here... 
   }
}
```
So the EntityId property should be passed to the convert as the first argument to Convert method and the logic should return the Entity. Keep the build of Converters by ConstructServicesUsing method (to be used with Mocks or IoC containers). It would be great :D haha

**Comment by jbogard** [comment]
So you have two things - one is a way to convert from "long" to "Some entity". That's best for a type converter.

The second is redirecting members. That's MapFrom. You would have something like:

```
cfg.CreateMap<long, City>().ConvertUsing<EntityConverter<City>>();
cfg.CreateMap<StateViewModel, State>().ForMember(d => d.City, opt = opt.MapFrom(src => src.CityId));
```

You still shouldn't use a resolver. You just need to redirect.

Also, you can use a RecognizeSourcePostfix for auto-detecting the "Id" prefix and you'd never need the MapFrom.

**Comment by jbogard** [comment]
And what I'm thinking on the first one to make it easier is to allow something like:

```
cfg.AddTypeConverter(typeof(EntityConverter<>));
```

**Comment by felipeoriani** [comment]
Thank you for the support Jimmy. AutoMapper is very nice tool. My final result:
```
config.ConstructServicesUsing(GetResolver);

// to map recognize that "EntityId" to map in "Entity"..  awesome!
config.RecognizePostfixes("Id");

// I will make a loop here on entities!
config.CreateMap<long, Country>().ConvertUsing<EntityConverter<Country>>();

config.CreateMap<StateViewModel, State>(MemberList.None)
          .ReverseMap(); // without MapFrom :D
```
And my EntityConvert take a repository resolved by GetResolver method. I will use different GetResolver method for unit tests (which will mock repositories) and another on the system to resolve them using the IoC container!

Thank you!

**Comment by jadidihosein68** [comment]
Hi, 

To use automapper in my test project, I use the following code, I did not use dependency injection for the mapper obj.

 [TestClass]
    public class SetupAssemblyInitializer
    {
        [AssemblyInitialize]
        public static void AssemblyInit(TestContext context)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<WP2PSmeFacilities, WP2PSmeFacilitieDTO>();
                cfg.CreateMap<WP2PSmeFacilitieDTO, WP2PSmeFacilities>();
                cfg.CreateMap<WP2PHomeLoanApplication, WP2PHomeLoanApplicationDTO>();
                cfg.CreateMap<WP2PHomeLoanApplicationDTO, WP2PHomeLoanApplication>();
            });

        }
    }

**Comment by TejalPatel56** [comment]
thanks jadidihosein68
