### ISSUE TITLE
Understanding-your-mapping with BuildExecutionPlan

### ISSUE THREAD

**Issue by phil000** [AutoMapper/AutoMapper#1873]
Where has BuildExecutionPlan() gone?

It's not on MapperConfiguration, or anywhere in Automapper.dll 5.2.0

https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping

**Comment by phil000** [comment]
I see this is in source and was merged from a pull request 9 days ago but has not been released yet on NuGet. Haven't checked 'dev build's on MyGet. 
Perhaps the public documentation should be in line with what is actually available, or tagged with the release it appears within ('Dev Builds', 'vNext', ...) to avoid documenting things we cannot do weeks or months in advance.
This can be closed.

**Comment by TylerCarlson1** [comment]
You can close the issue yourself

**Comment by phil000** [comment]
Yes I'm aware of that, but then the issue and comment would never be read by the project owners.

**Comment by jbogard** [comment]
Realistically I need a better solution for documentation.
