### ISSUE TITLE
ProjectTo() gives "Unable to create a null constant value of type 'DataContracts.StateContract'."

### ISSUE THREAD

**Issue by Vaccano** [AutoMapper/AutoMapper#1882]
I have the following method WebApi project. 
```
public IQueryable<OriginContract> Origins()
{
    return contextProvider.Origins.ProjectTo<OriginContract>(automapperConfiguration);
}
```
It query's `Origin` objects and their associated `State` object.

When I call it I get the following error:

>Unable to create a null constant value of type 'DataContracts.StateContract'. Only entity types, enumeration types or primitive types are supported in this context.

My classes look like this:
```
public class OriginContract
{
    public int OriginId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string City { get; set; }
    public int StateId { get; set; }
    public StateContract State { get; set; }
}

public class StateContract
{
    public int StateId { get; set; }
    public string Abbreviation { get; set; }
    public string Name { get; set; }
}
```

The entities have the same properties and names (I copied and pasted from one to the other.) You can see them [here](https://gist.github.com/Vaccano/c8ed812c807b0314c0cd41ac4f78f393) if you like.  And the sql for the [tables](https://gist.github.com/Vaccano/d8aca19388e017b279c7dd3d92c295d8) is here.

I have seen questions similar to this referring to this error when you have a nullable relationship.  But this is not a nullable relationship.

### Or failing that, is there another way to use AutoMapper and still return an IQueryable that is "attached" to the database (rather than an in-memory list)?

_Additional Info:_  
-
I have tried doing the projection manually via a select statement:
------
```
public IQueryable<OriginContract> Origins()
{
    var origins = contextProvider.Origins.Select(origin => new OriginContract
    {
        City = origin.City,
        Code = origin.Code,
        Name = origin.Name,
        OriginId = origin.OriginId,
        StateId = origin.StateId,
        State = new StateContract
        {
            StateId = origin.State.StateId,
            Name = origin.State.Name,
            Abbreviation = origin.State.Abbreviation
        }
    });

    return origins;
}
```
And that works perfectly.  (I get the data I want and the SQL Query that is generated is what I want as well.)  

But I don't get to use AutoMapper :(

Just to test my mapping, I tried this as well:
------
```
public IQueryable<OriginContract> Origins()
{
    var origins = contextProvider.Origins;
    var originContracts = origins.ToList().Select(origin => automapperConfiguration
              .CreateMapper().Map<Origin, OriginContract>(origin));
    return originContracts.AsQueryable();
}
```
This gives the correct data, but due to the "ToList", it generates many queries (bad).

But it proves that my mappings are correct (as far as the class names are concerned).

I also tried adding an explicit expansion:
-
`return contextProvider.Origins.ProjectTo<OriginContract>(automapperConfiguration, dest => dest.State);`

But it did not help (still get the error).

I tried removing the relationship to `State`
-
In an attempt to break this problem down, I tried to remove the relationship to the `State` entity (from the `Origin` entity).  Basically this took it from a two level hierarchy to a single level (just the `Origin` entity is projected and returned).

This worked fine.  But this is a very simple case.  Does this mean that `ProjectTo()` only support mapping to simple properties?  (I hope not.  Most entities have relationships with other entities.) 

In case it is relevant, this is what my mapping looks like:
-----
```
mapperConfigExpression.CreateMap<Origin, OriginContract>();
mapperConfigExpression.CreateMap<OriginContract, Origin>();

mapperConfigExpression.CreateMap<State, StateContract>();
mapperConfigExpression.CreateMap<StateContract, State>();
```
------
I am running AutoMapper 5.2.0 from NuGet.

I would be happy to supply any additional data that would help me get this working.

**Comment by TylerCarlson1** [comment]
```
public IQueryable<OriginContract> Origins()
{
    var mapper = automapperConfiguration.CreateMapper();
    return contextProvider.Origins.ProjectTo<OriginContract>(mapper.ConfigurationProvider);
}
```

Or if you want no confusion just use the static instance and then you don't need to pass in any arguements for ProjectTo

**Comment by Vaccano** [comment]
@TylerCarlson1 Thank you for the response.  I appreciate it!

I tried what you suggested and it made no difference.  (I still get the same error.)

I am imagining that the `mapper.ConfigurationProvider` is the same instance of `IConfigurationProvider` that is used to create the mapper (called `automapperConfiguration` in my case).  So, unless the `CreateMapper()` method sets up something in the IConfigurationProvider, I am not surprised that this change did not fix the bug...

Still, I am grateful for any idea to try.  If you have anything else that you think will work, I am happy to try it out.

**Comment by TylerCarlson1** [comment]
Can you try the [MyGet Build](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-build)?

And if that doesn't work can you make a repository that replicates this exception for us to build and test with?

The other wild guess is that State is a ComplexType and AutoMapper can't handle those.

**Comment by Vaccano** [comment]
@TylerCarlson1  I tried the MyGetBuild (version 5.3.0-alpha-01271).  The error is the same.

When you say "State is a ComplexType and AutoMapper can't handle those" what do you mean?

As shown in my question, `State` is a class and an Entity with its own properties.

**What you are saying seems to hint that the `ProjectTo()` method can only support a single "level".**  (meaning that a class as a destination is ok only if NONE of it's properties are another class.)

Is that what you are saying?

**Comment by TylerCarlson1** [comment]
Actually what I'm saying is it "should" work just fine and I have no clue why.  That's why I want something to replicate it so I can debug and figure out what's going wrong.

I've had multi level projections work just fine.  I use EF 6.1.3 and DbContext and it works.

I think complex types are Struct by default so they can't be null and gives an exception of some kind, possibly the same exception.

**Comment by Vaccano** [comment]
@TylerCarlson1 I have uploaded a repro of this issue.  It can be found here: https://github.com/Vaccano/WebApi2Template

The ReadMe.md file (found in the WebApi2Template project) has the repro steps.  I have added them below for your convenience:

>REPRO STEPS

>1. Setup, or use an existing, Sql Server Database (I am using Sql Server 2012)
>2. Run the script under solution items called "Database Setup Script.sql"
>3. Open WebApi2Template\Web.Config
>    3.1 Find the connection string section and replace the server name (Called "YourServerNameHere") with your server name.
>4. Repeat step 3 with DataAccessLayer\App.config (optional: This is a design time connection)
>5. Run (with the WebApi2Template project as the startup project) and navigate a Chrome to http://localhost:58723/api/WebApi2Template/Origins (Note your port will likely be different.)

>Result: "Unable to create a null constant value of type 'DataContracts.StateContract'. Only entity types, enumeration types or primitive types are supported in this context.",

>NOTE: The call to ProjectTo is in WebAPi2TemplateDataAccess.  It also has a commented out call that works fine without automapper.

Let me know if you have any problems reproducing the issue.

**Comment by TylerCarlson1** [comment]
Will have to look at this in more detail at a later time, but one thing I notice in your example is that your main application is EF 6.0.0 and the DB is 6.1.3.  When you build the application 6.0.0 is being used, and I know that has problems with these kinds of things.

**Comment by lbargaoanu** [comment]
[Working gist](https://gist.github.com/lbargaoanu/dd272fcdead462b0588f48e4a5a92575#file-fk_-1882-cs).

**Comment by lbargaoanu** [comment]
I think @TylerCarlson1 is right about the version. This can be closed.

**Comment by Vaccano** [comment]
@TylerCarlson1 Wow!  That was it!

Thank you so much for your help.  

I have to say, I have never seen a more responsive open source project in my life!  You guys are great!
