### ISSUE TITLE
How to use oDataOptions with AutoMapper

### ISSUE THREAD

**Issue by felipedrumond** [AutoMapper/AutoMapper#1884]
Hi guys, I was wondering how to reduce my API source code, and I'll explain in the following lines:

**Scenario:**
Currently, my client (an Angular 2 app) make requests to a C# Web API. In many scenarios, I request a product in a URI like this: "/products/1". This will make my Api to return a JSON which will contain ALL FIELDS of the product. In many cases, I just need its ID, Name and Price, instead of its dozens of properties. To solve this problem and reduce the bandwidth used and speed up the response, I use oDataOptions, therefore I can make a request like this: "/products/1?$select=id,name,price".
This implementation forces me to create tons of code, because I need to check if I need to copy the property value from the Domain class to the API model class. I'd like to get rid of this code, because I need to create them to all my Api model classes.

```
id       = select.Invoke("id") ? product.ID : default(int?); // if there is "id" in the select, copy the value
name = select.Invoke("name") ? product.Name : null;
// and so on for every property of my model class
```

**Using AutoMapper**
With AutoMapper I don't need to copy every single value from the domain class (which usually is an object that is returned by Entity Framework) to my class model (which will be transformed as a JSON and returned to the client). So the implementation is as easy as this:

```
var productFromDataBase = (... retrieve product from source)
var product = Mapper.Map<Domain.Product, Api.Model.Product>(productFromDataBase);
```

**The challenge**
I'd like to use the oDataOptions as a configuration to tell AutoMapper to copy or not a particular field, like this:

```
var _SELECT = "id,name,price";
var productFromDataBase = (... retrieve product from source)
var product = Mapper.Map
                       <Domain.Product, Api.Model.Product, _SELECT>(productFromDataBase);
```

Is there any resource in Automapper that I can use to create a generic code that will deal with the _SELECT and copy whatever I want without having to copy field by field?

**Comment by lbargaoanu** [comment]
#1868?

**Comment by felipedrumond** [comment]
I'm not sure it completely solves the scenario, but I'll give it a go, @lbargaoanu.

**Comment by TylerCarlson1** [comment]
Oh I realized this isn't going to help you.  Yea #1868 is best bet.
