### ISSUE TITLE
To support resolver that implements multiple IValueResolver interfaces

### ISSUE THREAD

**Issue by GeXiaoguo** [AutoMapper/AutoMapper#1887]
Not sure if this is a bug or simply an unsupported feature, if a resolver implements multiple IValueResovler interfaces, AutoMapper throws an "No coercion operator is defined between types" exception. The following code demonstrates the problem.
`

    public class A { }
    
    public class B { }

    public class C
    {
        public string property1 { get; set; }
    }
    
    public class MyTestResolver :
        IValueResolver<A, C, string>,
        IValueResolver<B, C, string>
    {
        public string Resolve(A source, C destination, string destMember, ResolutionContext context)
        {
            return "from A->C";
        }

        public string Resolve(B source, C destination, string destMember, ResolutionContext context)
        {
            return "from B->C";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            AutoMapper.Mapper.Initialize(x =>
            {
                x.CreateMap<B, C>()
                    .ForMember(dest => dest.property1, opt => opt.ResolveUsing<MyTestResolver>());
            });
        }
    }
`

**Comment by jbogard** [comment]
Yeah not just with this, but in general I try to not have my classes implement multiple extension interfaces like this. If there's common behavior, I'll put it in a base class, and have two concrete classes inherit and those concretions implement the interface.

**Comment by lbargaoanu** [comment]
It might be useful when you don't want to write logic in classes that implement AM interfaces and you only write a glue class that calls the logic.

**Comment by GeXiaoguo** [comment]
In this case, I want to group resolvers into a single class according to the destination property. This makes it easier to find out how a certain property in a certain class are assigned by automapper. In the above example, probably I should have named the resolver ClassCProperty1Resolver(instead of MyTestResolver) to make the intention clearer. If the resolver is logic heavy and have its own states, this would be a nice way to orgnaize everything into a single class.
