### ISSUE TITLE
System.NullReferenceException Mapping Expression<Func<T,bool>> with flattening

### ISSUE THREAD

**Issue by drjameshouse** [AutoMapper/AutoMapper#1893]
I'm trying to map an Expression<Func<T,bool>> where the source is a complex object that gets flattened in the destination.

Models:
```
public class OrderLine
{
	public int Id { get; set; }
	public string ItemName { get; set; }
	public int Quantity { get; set; }
}

public class OrderLineDTO
{
	public int Id { get; set; }
	public ItemDTO Item { get; set; }
	public int Quantity { get; set; }
}

public class ItemDTO
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

Configuration:
```
Mapper.Initialize(cfg =>
{
	cfg.CreateMap<OrderLine, ItemDTO>()
		.ForMember(dto => dto.Name, conf => conf.MapFrom(src => src.ItemName));
	cfg.CreateMap<OrderLine, OrderLineDTO>()
		.ForMember(dto => dto.Item, conf => conf.MapFrom(ol => ol));
	cfg.CreateMap<OrderLineDTO, OrderLine>()
		.ForMember(ol => ol.ItemName, conf => conf.MapFrom(dto => dto.Item.Name));
});
```

And finally the Expression:
```
Expression<Func<OrderLineDTO, bool>> dtoExpression = dto => dto.Item.Name == "Item #1";
var expression = Mapper.Map<Expression<Func<OrderLine, bool>>>(dtoExpression);
```

Exception:

> AutoMapper.AutoMapperMappingException was unhandled
>   HResult=-2146233088
>   Message=Error mapping types.
> 
> Mapping types:
> Expression`1 -> Expression`1
> System.Linq.Expressions.Expression`1[[System.Func`2[[AutoMapperIssue.Program+OrderLineDTO, AutoMapperIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[AutoMapperIssue.Program+OrderLine, AutoMapperIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
>   Source=Anonymously Hosted DynamicMethods Assembly
>   StackTrace:
>        at lambda_method(Closure , Object , Object , ResolutionContext )
>        at AutoMapperIssue.Program.Main(String[] args) in C:\Development\Sandbox\AutoMapperIssue\Program.cs:line 57
>   InnerException: 
>        HResult=-2147467261
>        Message=Object reference not set to an instance of an object.
>        Source=AutoMapper
>        StackTrace:
>             at AutoMapper.TypePair..ctor(Type sourceType, Type destinationType)
>             at AutoMapper.MapperConfiguration.FindTypeMapFor(Type sourceType, Type destinationType)
>             at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedSubMemberCall(MemberExpression node)
>             at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>             at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitBinary(BinaryExpression node)
>             at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
>             at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>             at AutoMapper.Mappers.ExpressionMapper.Map[TSource,TDestination](TSource expression, ResolutionContext context)
>             at lambda_method(Closure , Object , Object , ResolutionContext )

I'm using dotnet core, and AutoMapper 5.2.0.

If I map the same expression in reverse (Flatten to complex) like so:
```
Expression<Func<OrderLine, bool>> expression = x => x.ItemName == "Item #1";
var dtoExpression = Mapper.Map<Expression<Func<OrderLineDTO, bool>>>(expression);
```
it works fine.

**Comment by webpaul** [comment]
How sure are you that dto.Item isn't null? A null check there might be all you need.

**Comment by drjameshouse** [comment]
In the tests I ran, I set dto.Item myself.  The mapping between them works perfect.  When I issue:
`var dtoExpression = Mapper.Map<Expression<Func<OrderLineDTO, bool>>>(expression);`
is when I get the Null exception, it's not even trying to evaluate the expression against an object.

When I started debugging into AutoMapper, ExpressionMapper.GetConvertedSumMemberCall() gets the propertyMap for node expression {x.Item}, but the propertyMap doesn't have any SourceMembers, so the type passed into TypePair constructor is null.

I'm not really sure if I'm setting my configuration wrong where the SourceMembers don't get properly created, or if this is a real issue.

**Comment by TylerCarlson1** [comment]
```
cfg.CreateMap<OrderLine, OrderLineDTO>()
		.ForMember(dto => dto.Item, conf => conf.MapFrom(ol => ol));
```
is the issue.  And there's nothing you can really do except not use complex types going this way.

AutoMapper doesn't support De-Flattening, which is what this is doing.  Which is why you have to explicitly map Item to OrderLine insead of it De-Flattening.  It flattens the other way around just fine.

You can De-Flatten your maps by the code stated above to map back, BUT there's no way right now that AutoMapper can figure out you are de-flattening a map and build the expression to do what you want.

This would require a reworking of how automapper does things, or add de-flattening systems on top of what's there

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
