### ISSUE TITLE
AutoMapper select default implementation for ICollection<T>

### ISSUE THREAD

**Issue by AsValeO** [AutoMapper/AutoMapper#1896]
```
public class Foo
{
    public Foo()
    {
        Bar = new HashSet<int>();
        Bar2 = new HashSet<string>();
    }

    public virtual ICollection<int> Bar { get; set; }
    public virtual ICollection<string> Bar2 { get; set; }
}
```
When AutoMapper maps instance of this class, it maps `ICollection<T>` to `List<T>`. It should be `HashSet<T>.` How can I select default implementation for `ICollection<T>`? Class instance has properties of type `HashSet<T>` assigned in constructor.
[Unanswered question on SO](http://stackoverflow.com/questions/41520897/automapper-select-default-implementation-for-icollectiont)

**Comment by lbargaoanu** [comment]
You can type it as ISet or HashSet instead of ICollection.

**Comment by AsValeO** [comment]
I can not because the class is generated by Entity Framework Core.

**Comment by lbargaoanu** [comment]
Of course you can. You just have to keep them in sync.

**Comment by lbargaoanu** [comment]
UseDestinationValue for that property would work too.

**Comment by AsValeO** [comment]
I can not because program code needs these properties to be of type  `ICollection<T>`. Is there a way to tweak AutoMapper, not the class?

**Comment by jbogard** [comment]
Maybe ConstructedBy?

**Comment by lbargaoanu** [comment]
@jbogard You mean UseDestinationValue? :) It is already there.
