### ISSUE TITLE
AutoMapper throws dark error: Error type mapping

### ISSUE THREAD

**Issue by chivitc1** [AutoMapper/AutoMapper#1900]
Hi Jim, this a great tool but your version 5.2 drop something good in version 3.x:
When I have object like:
```
UserDto{
string username{get;set;}
string dateofbirth{get;set;}
}
GroupDto{
string name{get;set;}
IList<UserDto> users{get;set;}
}
```

When Run and fail with GroupDto mapping due to datetime conversion
- Version 5.2 say Error mapping type (dont know what going on)
- Version 3x say something like: 19/12/2016 is not a date (which I know the problem is datetime culture conversion)

Appreciate you rollback the feature

**Comment by chivitc1** [comment]
BTW my dev computer and server setting in diff System Datetime format (one France like style, one US style) => the AutoMapper run well with my dev environment but failed with Error mapping in server though Client (browser) sending the same format. Can we have a way to keep consistent to what client sending as it validated but not server setting.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.
