### ISSUE TITLE
Change in null collection behaviour between 3.2.1 and latest version

### ISSUE THREAD

**Issue by adam-resdiary** [AutoMapper/AutoMapper#1903]
I've noticed a change in behaviour between 3.2.1 and the latest version that's giving us grief. It seems that in version 3.2.1, if I return null from ResolveUsing for an IEnumerable<T> object it maps to null, whereas in the latest stable and pre-release versions it maps to an empty collection.

Here's a test case that illustrates the issue:

```csharp
public class Source
{
	public IEnumerable<int> Ints { get; set; }
}

public class Destination
{
	public IEnumerable<int> Ints { get; set; }
}

[Test]
public void Test()
{
	var config =
		new MapperConfiguration(
			cfg =>
				cfg.CreateMap<Source, Destination>()
					.ForMember(d => d.Ints, o => o.ResolveUsing((Func<Source, IEnumerable<int>>) (s => null))));
	var mapper = config.CreateMapper();

	var destination = mapper.Map<Destination>(new Source { Ints = null });

	Assert.IsNull(destination.Ints);
}
```

To me this behaviour seems odd, because as far as I understood it, when you use ResolveUsing you're basically saying that you want to be responsible for mapping the property yourself, and AutoMapper should use exactly the value you give it.

From what I've found, I've got two workarounds:

  1. Set AllowNullCollections on the AutoMapper configuration.
  2. Use AfterMap to manually set my collection null.

Option 1 is too risky for me to use because it impacts absolutely every mapping across the board, and there doesn't seem to be the option to do it on a per-map basis.

Option 2 works, but it seems odd that I'd need to do this.

Additionally, if I use the AfterMap approach, I have to also Ignore the property to get it to work:

```csharp
[Test]
public void TestAfterMap()
{
	var config =
		new MapperConfiguration(
			cfg =>
				cfg.CreateMap<Source, Destination>()
					.ForMember(d => d.Ints, o => o.Ignore())
					.AfterMap((d, context) =>
					{
						d.Ints = null;
					}));
	var mapper = config.CreateMapper();

	var destination = mapper.Map<Destination>(new Source { Ints = null });

	Assert.IsNull(destination.Ints);
}
```

This is counter-intuitive to me, because the name "AfterMap" indicates to me that it happens after AutoMapper has performed its mapping, so if I set the value of a property it seems odd to me that AutoMapper then seems to perform further work that then overwrites that unless I ignore the property.

I realise that it's a bit odd mapping an IEnumerable to null, which is why I really don't want to have to enable `AllowNullCollections` globally, but in the scenario where we do use it the object can have a null, empty or populated collection, each of which means a slightly different thing.

My personal opinion is that `ResolveUsing` should just use exactly the result that it gets from the mapping function, but failing that it would be good to be able to specify `AllowNullCollections` at the mapper level.

I've tested this against versions 3.2.1 (obviously with slightly different code because of the switch from the static config API), 5.2.0 and 5.3.0-alpha-01276.

**Comment by lbargaoanu** [comment]
AfterMap is called after mapping :) Check [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping). Just that it receives the source and the destination, you must set the destination collection, you were setting the source.
You can set AllowNullCollections per profile. You can put the maps that need it inside that profile.
What you return from Resolve gets mapped again, even if it could be assigned to the destination property. I'm with you on this one, but @jbogard is not :) Aside from tradition, the reason is probably consistency. Even if you don't use resolve, the mapping is a two step process, resolve and map. Resolve allows you to customize just the resolve part :)

**Comment by adam-resdiary** [comment]
Ah right - I feel like an idiot on the AfterMap one! I think I maybe got a bit confused when switching between the different version to check the behaviour.

We can maybe investigate using a profile for this then. The slight issue is that we have large existing code base that doesn't use profiles, so switching to using them might be tricky.

I still find the behaviour of ResolveUsing strange though!

Any idea if this was a deliberate change in behaviour or not? The reason I ask is that if not we're probably not the only people affected.

**Comment by lbargaoanu** [comment]
You can also try [null substitution](https://github.com/AutoMapper/AutoMapper/wiki/Null-substitution).
You can use profiles as needed, mixing with global configuration.
As far as I know Resolve always behaved this way.

**Comment by adam-resdiary** [comment]
Yeah - I think we can probably start switching to profiles. Thanks for the advice.

I'm not sure null substitution would work in our case, because we also need the ResolveUsing step to actually generate the correct value. Here's a more realistic example of what we're doing - maybe it'll make it seem less insane ;-):

```csharp
public class Source
{
  public IEnumerable<int> PromotionIdsFrom { get; set; }
  public IEnumerable<int> PromotionIdsTo { get; set; }
}

public class Destination
{
  public IEnumerable<int> PromotionIds { get; set; }
}

var config = new MapperConfiguration(cfg => cfg.CreateMap<Source, Destination>()
  .ForMember(d => d.PromotionIds, o => o.ResolveUsing(GetPromotionIds)));

public IEnumerable<int> GetPromotionIds(Source source)
{
    if (collectionsAreDifferent)
    {
      return source.PromotionIdsTo;
    }

    // Return null to indicate collections haven't changed
    return null;
}
```

So basically we're mapping from an object that has before and after properties, and mapping to an object that uses null to indicate that a property hasn't changed.

I'm pretty certain the behaviour of Resolve has changed. Like I say, I just tried version 3.2.1, and it seemed to behave differently than the current version (i.e. my destination collection ended up null rather than empty).

**Comment by lbargaoanu** [comment]
The whole thing behaves differently, that's smth else. You just need to tell it what you want through AllowNullCollections.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by adam-resdiary** [comment]
Ok - I'm happy to close this since I've got a solution now.

**Comment by lbargaoanu** [comment]
I know I didn't answer why the behavior changed, but it's not easy to tell and the behavior now seems correct (as designed), so I'm not sure it matters much.

**Comment by adam-resdiary** [comment]
Yeah - I think that's fair enough. That's why I didn't press the point.

I do find the behaviour of ResolveUsing slightly confusing, but that's pretty subjective, so I can live with it.
