### ISSUE TITLE
Reintroduced Castle.Proxies.[YourClass]Proxy mapping error.

### ISSUE THREAD

**Issue by crlsktr** [AutoMapper/AutoMapper#1904]
I noticed the error when using latest Moq (4.5.30.0). If you have an inherited class when trying to map the Proxy of the parent into the child it can't find a valid mapping.
[AutomapperBug.zip](https://github.com/AutoMapper/AutoMapper/files/702653/AutomapperBug.zip)

**Comment by lbargaoanu** [comment]
You should map from Square to Shape.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by crlsktr** [comment]
Thanks for your work guys.
