### ISSUE TITLE
AssertConfigurationIsValid should (or at least be able to) bring attention to enum type mismatches

### ISSUE THREAD

**Issue by JonathanLydall** [AutoMapper/AutoMapper#1907]
```csharp
public class Tests
{
    [Fact]
    public void TestCase()
    {
        Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<SourceType, DestinationType>();
        });

        // Would ideally throw an exception due to PropertyWithMatchingName having different
        // enum types on the source and destination types.
        Mapper.AssertConfigurationIsValid();

        // Works:
        var result0 = Mapper.Map<DestinationType>(new SourceType
        {
            PropertyWithMatchingName = SourceEnum.Common
        });

        // Results in an invalid enum value being assigned:
        var result1 = Mapper.Map<DestinationType>(new SourceType
        {
            PropertyWithMatchingName = SourceEnum.UniqueToSourceEnum
        });
    }
}

public class SourceType
{
    public SourceEnum PropertyWithMatchingName { get; set; }
}

public class DestinationType
{
    public DestinationEnum PropertyWithMatchingName { get; set; }
}

public enum SourceEnum
{
    Common = 0,
    UniqueToSourceEnum = 2,
}

public enum DestinationEnum
{
    Common = 0,
    UniqueToDestinationEnum = 3,
}
```

Possibly related to #1609.

It would be useful if `Mapper.AssertConfigurationIsValid()` could optionally throw an exception to bring attention to a mapping issue in cases like this.

There are two kinds of checks that could be performed:
1. Do the source and destination types match or otherwise have a mapping configured?
2. Are all enum values in the source type catered for on the destination enum?

Personally I would happy with just check `1`, even if it's an additional check which I have to explicitly opt into.

While I don't personally see a need for check `2`, it seems like issue #1609 wants something like it. What defines as "catered for" in check `2` might be something like checking if the field values and field names match, like the `SourceEnum.UniqueToSourceEnum` field in my example above has nothing corresponding on the `DestinationEnum` enum.

**Comment by lbargaoanu** [comment]
Maybe make validation extensible. AssertConfigurationIsValid could receive a delegate that would be called for each property map.

**Comment by JonathanLydall** [comment]
It also occurred to me that it would be useful to optionally be able to prevent automatic enum value to string conversions.

My current scenario is that I have a large object graph (200+ properties in total) being mapped to a practically identical object graph for 3rd party integration reasons, and I want to be able to leverage automapper's `AssertConfigurationIsValid` feature to bring attention to possible missed properties or mappings.

**Comment by lbargaoanu** [comment]
Right now you can disable _all_ to string conversions by removing the StringMapper. It would be easy to write an [object mapper](https://github.com/AutoMapper/AutoMapper/blob/094a2c1456c9a3e916726a9aa60ddb2dc07cf66d/src/UnitTests/Mappers/CustomMapperTests.cs#L131) that would convert only what you want.

**Comment by JonathanLydall** [comment]
After a lot of digging around, _finally_ worked out how to manipulate the `MapperRegistry` to remove the `StringMapper`, although I had to also remove the `TypeConverterMapper` before it would work the way I expected. I have also managed to work out a way to get my Enum to Enum mapping validation behaviour I was looking for:

```csharp
    public class Tests2
    {
        [Fact]
        public void TestCase()
        {
            MapperRegistry.Mappers.Remove(MapperRegistry.Mappers.Single(x => x is StringMapper));
            MapperRegistry.Mappers.Remove(MapperRegistry.Mappers.Single(x => x is EnumToEnumMapper));
            MapperRegistry.Mappers.Remove(MapperRegistry.Mappers.Single(x => x is TypeConverterMapper));

            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Src, Dst>();
            });

            // Correctly fails as there is no mapping from the enum to string
            Mapper.AssertConfigurationIsValid();
        }
    }

    public enum TestEnum
    {
    }

    public class Src
    {
        public TestEnum Prop { get; set; }
    }

    public class Dst
    {
        public string Prop { get; set; }
    }
```

**Comment by lbargaoanu** [comment]
The example I linked to showed how to do it with the latest build. Because that's the only way from now on. When you first upgrade, your code will break.

**Comment by JonathanLydall** [comment]
Is there a syntax which works with latest non-prerelease available on Nuget? Because the below doesn't work on 5.2.0:

```csharp
var mappingConfiguration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Src, Dst>();

    // Doesn't work, there is no field called Mappers on cfg
    cfg.Mappers.Insert(0, new EnumMapper());
});
```

And I was wrong in my previous comment (which I have now edited) about my manipulating the Mapper Registry to achieve my desired enum to enum mapping behaviour for `AssertConfigurationIsValid`.

**Comment by lbargaoanu** [comment]
Prerelease doesn't mean much in AM, it's just as good as the NuGet version.

**Comment by JonathanLydall** [comment]
It's not worth throwing away the convenience of NuGet managed packages just for this.

Fortunately I worked out how to do this with 5.2.0:
```csharp
var mappers = MapperRegistry.Mappers.ToList();
mappers.Insert(0, new EnumMapper());

var mappingConfiguration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<SourceType, DestinationType>();
}, mappers);

mappingConfiguration.AssertConfigurationIsValid();
```

**Comment by lbargaoanu** [comment]
You don't have to, there is the  [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by JonathanLydall** [comment]
Thank you, but I'll wait until the next (presumably) stable version is pushed to the official NuGet repository. For the kind of project I am working on, we avoid non-mainline builds/repositories on principal unless absolutely unavoidable.

**Comment by jbogard** [comment]
Fixed by #1919

**Comment by ValeraT1982** [comment]
Are there any examples how it should work?

**Comment by lbargaoanu** [comment]
See the test in that PR.
