### ISSUE TITLE
Automapper IValueResolver resolver fails for Nullable Guid

### ISSUE THREAD

**Issue by jayakaran1987** [AutoMapper/AutoMapper#1909]
Hi,

I tried to return nullable Guid from IValueResolver, unfortunately that doesn't seems work.

` public class TestResolver : IValueResolver<GanttCalendar, Calendar, Guid?>`
`{`
    `public Guid? Resolve(GanttCalendar source, Calendar destination, Guid? member, ResolutionContext context)`
   `{`
      `return null;`
   `}`
`}`

basically that works fine for other types like int? but not Guid?

More Information - http://stackoverflow.com/questions/41601850/automapper-ivalueresolver-does-not-support-nullable-type-guid

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#ignoreallnonexisting-extension
