### ISSUE TITLE
inheritedMapper for map to a existed object is not working right.

### ISSUE THREAD

**Issue by huoxudong125** [AutoMapper/AutoMapper#1910]
Demo  DB Entities:

    public class EntityA
    {
        public DateTime CreateTime { get; set; }
        public int PropertyA { get; set; }
        public int PropertyB { get; set; }
    }

    public class EntityB
    {
        public DateTime CreateTime { get; set; }
        public string PropertyAA { get; set; }

        public string PropertyBB { get; set; }

    }

Demo ViewModels:

    public abstract class BaseViewModel
    {
        public DateTime CreateTimeFromB { get; set; }
        public DateTime CreateTime { get; set; }
    }

    public class ViewModelA : BaseViewModel
    {
        public int PropertyA { get; set; }

        public string PropertyAA { get; set; }

    }

    public class ViewModelB : BaseViewModel
    {
        public int PropertyB { get; set; }

        public string PropertyBB { get; set; }

    }

 The Mapper Configuration:

     internal class AutoMapperConfig
    {
        public static void Config()
        {
            Mapper.Initialize(cfg => {
                cfg.AddProfile<EntityAToViewModelProfile>();
                cfg.AddProfile<EntityBToViewModelProfile>();
            });
        }
    }

    internal class EntityAToViewModelProfile : Profile
    {
        public EntityAToViewModelProfile()
        {
            CreateMap<EntityA, BaseViewModel>()
                .ForMember(d => d.CreateTimeFromB, x => x.Ignore());

            CreateMap<EntityA, ViewModelA>()
                .IncludeBase<EntityA,BaseViewModel>()
                .ForMember(d => d.PropertyA, x => x.MapFrom(s => s.PropertyA));

            CreateMap<EntityA, ViewModelB>()
                  .IncludeBase<EntityA, BaseViewModel>()
                .ForMember(d => d.PropertyB, x => x.MapFrom(s => s.PropertyB));
        }
    }

    internal class EntityBToViewModelProfile : Profile
    {
        public EntityBToViewModelProfile()
        {
            CreateMap<EntityB, BaseViewModel>()
                .ForMember(d => d.CreateTimeFromB, x => x.MapFrom(s=>s.CreateTime))
                .ForMember(d=>d.CreateTime,x=>x.Ignore());

            //CreateMap<EntityB, ViewModelA>()
            //      .IncludeBase<EntityB, BaseViewModel>()
            //    .ForMember(d => d.PropertyAA, x => x.MapFrom(s => s.PropertyAA));

            //CreateMap<EntityB, ViewModelB>()
            //      .IncludeBase<EntityB, BaseViewModel>()
            //    .ForMember(d => d.PropertyBB, x => x.MapFrom(s => s.PropertyBB));
        }
    }

Test Code:

     class Program
    {
        static void Main(string[] args)
        {
            AutoMapperConfig.Config();

            var entity=new EntityA()
            {
                PropertyA = 1,
                PropertyB = 2,
                CreateTime = DateTime.Parse("1970-02-01")
            };

            var viewA = Mapper.Instance.Map<ViewModelA>(entity);

            var viewB = Mapper.Instance.Map<ViewModelB>(entity);

            Console.WriteLine(viewA.PropertyA);

            Console.WriteLine(viewB.PropertyB);
            Console.WriteLine("viewA.CreateTimeFromB {0}", viewA.CreateTimeFromB);
            Console.WriteLine("viewA.CreateTime {0}", viewA.CreateTime);
            Console.WriteLine("viewB.CreateTimeFromB {0}", viewB.CreateTimeFromB);
            Console.WriteLine("viewB.CreateTime {0}", viewB.CreateTime);

            Console.WriteLine();

            var entityB=new EntityB()
            {
                CreateTime =DateTime.Parse("2007-07-07")
            };

             viewA = Mapper.Instance.Map(entityB,viewA);

             viewB = Mapper.Instance.Map(entityB,viewB);

            Console.WriteLine("viewA.CreateTimeFromB {0}", viewA.CreateTimeFromB);
            Console.WriteLine("viewA.CreateTime {0}", viewA.CreateTime);
            Console.WriteLine("viewB.CreateTimeFromB {0}", viewB.CreateTimeFromB);
            Console.WriteLine("viewB.CreateTime {0}", viewB.CreateTime);

            Console.Read();
        }
    }

The Result is not I want 

> viewA.CreateTimeFromB 0001/1/1 0:00:00
> viewA.CreateTime 1970/2/1 0:00:00
> viewB.CreateTimeFromB 0001/1/1 0:00:00
> viewB.CreateTime 1970/2/1 0:00:00
> 
> viewA.CreateTimeFromB 2007/7/7 0:00:00
> viewA.CreateTime 2007/7/7 0:00:00
> viewB.CreateTimeFromB 2007/7/7 0:00:00
> viewB.CreateTime 2007/7/7 0:00:00

**Comment by huoxudong125** [comment]
I should fix the problem add some code for `EntityBToViewModelProfile` as follow:

     internal class EntityBToViewModelProfile : Profile
    {
        public EntityBToViewModelProfile()
        {
            CreateMap<EntityB, BaseViewModel>()
                .ForMember(d => d.CreateTimeFromB, x => x.MapFrom(s=>s.CreateTime))
                .ForMember(d=>d.CreateTime,x=>x.Ignore());

            CreateMap<EntityB, ViewModelA>()
                  .IncludeBase<EntityB, BaseViewModel>()
                .ForMember(d => d.PropertyAA, x => x.MapFrom(s => s.PropertyAA))
                .ForMember(d => d.CreateTime, x => x.Ignore());

            CreateMap<EntityB, ViewModelB>()
                  .IncludeBase<EntityB, BaseViewModel>()
                .ForMember(d => d.PropertyBB, x => x.MapFrom(s => s.PropertyBB))
                .ForMember(d => d.CreateTime, x => x.Ignore());
        }
    }

**Comment by lbargaoanu** [comment]
#1732?

**Comment by huoxudong125** [comment]
@lbargaoanu  Yes,That's the same question,
I also think inheritance of `Map` can inherent all behaviors from parent `Map`. If don't want to inherent the behavior we can defined new in sub `Map`.

The role same as OOP is a good idea.and that can produce the cost for new guy to master AutoMapper.

**Comment by lbargaoanu** [comment]
@jbogard Do we want to change things here?

**Comment by jbogard** [comment]
Yeah, I think so. Enough people are confused about certain things not getting applied in inherited maps.
