### ISSUE TITLE
DataReader issue in 3.3.1

### ISSUE THREAD

**Issue by david20000** [AutoMapper/AutoMapper#1920]
Hi,
I am having a strange problem trying to map an IDataReader in version 3.3.1.

The mapping works when I run a unit test, but when I run the actually WCF service it does not work. It does not throw an exception - it just does not copy any data.

 I downloaded the source for 3.3.1 and set some breakpoints. 

What I found is that the libraries I built from the 3.3.1 source do not match the libraries from the NuGet package - and the libraries I built never map correctly. 

Although the source is different, I was able to set a breakpoint and noticed that MapperRegistry.Mappers has 17 entries entries when it does not work (17 from _initialMappers) and about 24 or so when it did work.

I'm not quite sure how the additional mappers are loaded.  I think I can resolve this if I could figure that out.

Any help is appreciated.

Thanks, David

**Comment by jbogard** [comment]
No idea, can you open this issue in the AutoMapper.Data repository? I removed all the stuff for IDataReader and put it in its own repo. You may need to upgrade too.

**Comment by david20000** [comment]
I'm not in a position to upgrade at this time. 

Any idea why the 3.3.1 source does not match the NuGet 3.3.1 binaries?

**Comment by jbogard** [comment]
Nope, no idea. I did it with tags so it all should match.
