### ISSUE TITLE
Can't get to work not nullable source converter

### ISSUE THREAD

**Issue by dziedrius** [AutoMapper/AutoMapper#1924]
We have converters, that adjust DateTime kind like this:
```
expression.CreateMap<DateTime?, DateTime>().ConvertUsing<SetUtcKindDateTimeNullableSourceConverter>();
expression.CreateMap<DateTime?, DateTime?>().ConvertUsing<NullableSetUtcKindDateTimeConverter>();

```
and they worked fine, till we needed to map source DateTime property to destination DateTime property:
```
CreateMap<Test, Test2>().ForMember(x => x.LogTime, x => x.MapFrom(y => y.Time));
```
unit tests still passed:
```
Mapper.AssertConfigurationIsValid();
```
but when using ProjectTo(), exception was thrown:

> System.ArgumentException : Argument types do not match
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, ConcurrentDictionary`2 typePairCount)

Although exception message is quite cryptic, I've pin pointed the issue - if I remove date time converters, mentioned at the start of issue description, it started to work, looks like those converters convert destination to nullable DateTime.

So I thought fix would be introduce one more converter, that is bound to non nullable source and destination:
```
CreateMap<DateTime, DateTime>().ConvertUsing<SetUtcKindDateTimeConverter>();
```
but that does not solve the issue, looks like NullableSetUtcKindDateTimeConverter is chosen anyway.

How this should be handled, I'm I misusing something?

**Comment by lbargaoanu** [comment]
ProjectTo doesn't use converters, maybe you want ProjectUsing?
