### ISSUE TITLE
How migrate of 4.1.1 to 5.2.0

### ISSUE THREAD

**Issue by davidop** [AutoMapper/AutoMapper#1925]
Hi!

I am using version 4.1.1 of AutoMapper in this service and I would like to make the update to version 5.2.0. Could you help me?
 
public class ViewModelMapperService
{

        private ConfigurationStore _configuration;
        private MappingEngine _engine;

        public ViewModelMapperService()
        {
            this._configuration = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);
            this._engine = new MappingEngine(_configuration);
        }

        public void Map<TSource, TTarget>(TSource source, TTarget target)
        {
            this.CreateMap<TSource, TTarget>();
            this._engine.Map(source, target);
        }

        public TTarget Map<TSource, TTarget>(TSource source)
        {
            this.CreateMap<TSource, TTarget>();
            return this._engine.Map<TSource, TTarget>(source);
        }

        public void MapToModel<TSource, TTarget>(TSource source, TTarget target) where TTarget : IBaseObject
        {
            this.CreateVmToModelMap<TSource, TTarget>();
            this._engine.Map(source, target);
        }

        public void MapToViewModel<TSource, TTarget>(TSource source, TTarget target) where TTarget : IViewModel
        {
            this.CreateModelToVmMap<TSource, TTarget>();
            this._engine.Map(source, target);
        }
        
        private void CreateMap<TSource, TTarget>()
        {
            this._configuration.CreateMap<TSource, TTarget>();
        }

        private void CreateModelToVmMap<TSource, TTarget>() where TTarget : IViewModel
        {
            this._configuration.CreateMap<TSource, TTarget>().ForMember(t => t.IsDirty, opt => opt.Ignore());
        }

        private void CreateVmToModelMap<TSource, TTarget>() where TTarget : IBaseObject
        {
            this._configuration.CreateMap<TSource, TTarget>().ForMember(t => t.IsDirty, opt => opt.Ignore());
        }
    }

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide

**Comment by davidop** [comment]
Thanks @lbargaoanu. I have already seen this guide but I am not able to adapt my service to version 4.2.0 of AutoMapper

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
Why? There really shouldn't be that many changes from 4.1.1 and 4.2.1
except for the obsolescence of the Mapper.CreateMap stuff.

**Comment by davidop** [comment]
Version 4.2.0 no longer exists in the ConfigurationStore class.

**Comment by jbogard** [comment]
Check out the wiki on static and instance based usage of AutoMapper.

**Comment by davidop** [comment]
Yo solo necesito la correspondencia de las clases ConfigurationStore y MappingEngine a partir de la versión 4.2.0.

`
    public ViewModelMapperService()
    {
        var configuration = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);
        var engine = new MappingEngine(configuration);
    }
`

**Comment by lbargaoanu** [comment]
That reminds me, yo necesito un burrito :)
