### ISSUE TITLE
how Use ProjectTo<selectListItem>() and Profile ?

### ISSUE THREAD

**Issue by kafinetetaha** [AutoMapper/AutoMapper#1926]
when use this code ,my dropdownlist value and text is null?
problem ?
`ProjectTo<SelectListItem>(_mapper.Configurations).Tolist();`

profile class:
`            CreateMap<LiveProgram, SelectListItem>()
                   .ForMember(d => d.Text, m => m.MapFrom(s => s.Title_Mosavab))
                   .ForMember(d => d.Value, m => m.MapFrom(s => s.ProPlan_FK.ToString()));`

value and Text in dropdownlist is null result

**Comment by lbargaoanu** [comment]
?

**Comment by kafinetetaha** [comment]
my problem is not ignoreallnoneextention !
pass data to drop downlist but null text and null value ,
i think is problem in projection ?

**Comment by lbargaoanu** [comment]
Try removing ToString.

**Comment by kafinetetaha** [comment]
again not work , yet null value and text

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.
