### ISSUE TITLE
[question] mapping delegates with unkown types, ex.: Func<t_model, ???>

### ISSUE THREAD

**Issue by rmszc81** [AutoMapper/AutoMapper#1927]
Good night (well, it's night here).

First of all, thanks for your wonderful job with automapper. It's a life saver.

On a second though, well, I have a doubt about how to do some kind of mappings.

I have a delegate type
`Func<t_model, t_field>`
that I use for dynamic order by on my database context and it works like a charm.

Before I ask my question, let me get some things straight.

(this is my t_model source type)
{Name = "Func`2" FullName = "System.Func`2[[application.model.classes.c_config, application.config.model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]"}

(this is my t_model destiny type)
{Name = "Func`2" FullName = "System.Func`2[[domain.model.classes.c_config, domain.config.model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]"}

(both t_model types (application and domain) have the same structure. they're repeated 'cause it's a DDD app by design.)

`Func<t_model, t_field> ef_order_by // this is the source delegate, it come from application tier`

**this is how I use the delegate**
`y => y.created_at // the created_at property is one of properties on the POCO class`

**the main problem here is that I don't know at runtime which property came from delegate use to map**

this is the question: how I create these dynamic mappings?
`CreateMap< Func<application.c_config, ???>, Func<domain.c_config, ???> >();`

(this is how I call the mapper function.)
`mapper.Map(ef_order_by, ef_order_by.GetType(), tp_func_type);`

> tp_func_type it's a func<t_model, t_value> created dynamically to support the mapping operation.

I have the same dynamic mapping with Expression trees
`Expression<Func<t_source, t_destiny>>`
but, in that case, the types are known and automapper map it like a charm.

Thanks a lot.

[].
Regards,

@rmszc81

**Comment by TylerCarlson1** [comment]
If what I understand what you are asking it's translating expressions.  Wiki explains it [here](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)).

My suggestion is to do something like
```
Expressions<Func<application.model.classes.c_config, object>> orderByExpression = passedInExpression;
// Will translate it into a domain expression and then into T-SQL query.
var orderByResult = db.c_configs.UseAsDataSource().For<application.model.classes.c_config>().OrderBy(orderByExpression);
```
or you can map the expressions yourself.

Also to clarify.  Mapping expression is done using the Type Maps of the source and destination types.  You don't have to explicitly create a Type Map for Expressions in order for them to work.

**Comment by rmszc81** [comment]
Good night Tyler.

It could be, but isn't an expression that I need, it's a func<,> delegate.

For entity framework, it's OK. But I'm using litebd (from @mbdavid) and
order by it's a delegate.

Btw, I really need to translate the delegates because the repository is
accessed through dependence injection, or, in another words, there's no
reference to application types, even the structure of models being the same
as domain.

I'm using DDD specification for my app design. When I use expression trees,
expression<func<,>> it works because I know even at runtime both types,
source and destiny.

But with a delegate, I can change which field I'll use in order by. I know
the type t_model from source and destiny, but I don't know what is the
t_value type.

Got it?

Thank u.

[],
Regards.

On Jan 29, 2017 03:12, "Tyler Carlson" <notifications@github.com> wrote:

If what I understand what you are asking it's translating expressions. Wiki
explains it here
<https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)>
.

My suggestion is to do something like

Expressions<Func<application.model.classes.c_config, object>>
orderByExpression = passedInExpression;
// Will translate it into a domain expression and then into T-SQL query.
var orderByResult =
db.c_configs.UseAsDataSource().For<application.model.classes.c_config>().OrderBy(orderByExpression);

or you can map the expressions yourself.

Also to clarify. Mapping expression is done using the Type Maps of the
source and destination types. You don't have to explicitly create a Type
Map for Expressions in order for them to work.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/AutoMapper/AutoMapper/issues/1927#issuecomment-275894464>,
or mute the thread

**Comment by TylerCarlson1** [comment]
AutoMapper can't handle Func<,> translation and I don't think you can.  You would have make expression and translate it, THEN compile it if you wanted AutoMapper handle translation.

If it's passed as a delegate AM should find it's type and map off of that.  And if you know that you should be able to get it to get the result type from it and then use that to map over to an expression.  You will have to use reflection to figure out what the field is.

You have to use expressions and you have to get the field type in order for it to translate.  Not sure what else you can do other than that.

**Comment by lbargaoanu** [comment]
You can try a generic map, but in the end, you'd have to write the mapping code yourself in a type converter, so I'm not sure how useful is that. Something like
     
     CreateMap(typeof(Func<>), typeof(Func<>));

**Comment by rmszc81** [comment]
hey Guys, sorry for delay on answer.

I had some problems here at home but now I can talk.

@lbargaoanu,
I tried this too without success.
`CreateMap(typeof(Func<>), typeof(Func<>));`

But I'll test now:
`CreateMap(typeof(Func<,>), typeof(Func<,>));`

Let's see what happens.

[],
Regards.

@rmszc81

**Comment by rmszc81** [comment]
No success guys, any ideas?

Thank u very much.

@rmszc81

**Comment by jbogard** [comment]
What exactly do you want this mapping to do? Pretend you don't have AutoMapper, what would that func translating code look like?

**Comment by lbargaoanu** [comment]
Because that's exactly what's missing, the type converter. I didn't say AM will do the mapping for you. I just said you can do it yourself and integrate with AM through a type converter.

**Comment by rmszc81** [comment]
Good afternoon guys,

sorry for delay.

I solved that another way, instead of func<t_model, t_field> I used the following example?

[http://stackoverflow.com/questions/14775658/how-to-use-func-with-iqueryable-that-returns-iorderedqueryable](http://stackoverflow.com/questions/14775658/how-to-use-func-with-iqueryable-that-returns-iorderedqueryable)

that way it's easier for me to handle my queries and mappings.

it works like a charm.

Thank u.

**Comment by rmszc81** [comment]
Good afternoon guys, I have now other issue with this question:

System.Func`2[System.Linq.IQueryable`1[domain.model.classes.c_config],System.Linq.IOrderedQueryable`1[domain.model.classes.c_config]] needs to have a constructor with 0 args or only optional args
Parameter name: type

when I do:

`var y = mapper.Map(ef_order, ef_order.GetType(), tp_func_type);`

where:

`ef_order = Func<IQueryable<application.model.classes.c_config>, IOrderedQueryable<application.model.classes.c_config>>`

`tp_func_type = typeof(Func<IQueryable<domain.model.classes.c_config>, IOrderedQueryable<domain.model.classes.c_config>>)`

Can anyone help me on this case?

Thank u very much.

**Comment by jbogard** [comment]
I literally have no idea what you're trying to do. A func that takes a `IQueryable<T>` and returns an `IOrderedQueryable<T>` where T is the same. I don't know why you'd want AutoMapper for that, the T types are the same. And you're trying to transform an IQueryable. Or cast it. Or something. Or you're trying to map a _func_ itself, which again, doesn't make much sense.

What's the code look like you're trying to write, _without_ AutoMapper. Pretend it doesn't exist. What does the hard-coded, manual mapping code look like?

**Comment by TylerCarlson1** [comment]
On top of what @jbogard said. Could you provide an example from your code base to show what you are trying to do?

What you want to do is not a currently supported scenario for AutoMapper, so having a more complete view of what you are doing would be helpful.

**Comment by rmszc81** [comment]
I'm trying to map that func from application model to domain model.

ok, let`s get thing straight.

the main question was about mapping a func<t_model, ???> from one tier to another but I noticed that won't solve my problem so, I changed that too Func<IQueryable<t_model>, IOrderedQueryable<t_model>>.

what I'm trying to do now is to map :

(from application tier)
Func<IQueryable<**application**.model.classes.c_config>, IOrderedQueryable<**application**.model.classes.c_config>>

(to domain tier)
Func<IQueryable<**domain**.model.classes.c_config>, IOrderedQueryable<**domain**.model.classes.c_config>>

let's see some code:

it begins here:
`var configs = i_config_application_service.list(x => x.dt_created_at >= DateTime.Now.Date, y => y.OrderBy(z => z.dt_created_at));`

**i_config_application_service** is a class from application tier from my app.

the 1st parameter, is an Expression<Func (use for where predicate on the db engine that I'm using)
`x => x.dt_created_at >= DateTime.Now.Date`

the 2nd parameter, is the Func<IQueryable<application_class>, IOrderedQueryable<application_class>> **that is where I'm facing problems on the mapping**
`y => y.OrderBy(z => z.dt_created_at)`

this is the application service tier method:
```
        public virtual List<t_model> list(Expression<Func<application_class, Boolean>> ef_where, Func<IQueryable<application_class>, IOrderedQueryable<application_class>> ef_orderby)
        {
            // returns typeof Expression<Func<domain_class, Boolean>> //
            Type tp_expr = new utility.application.service_base().create_expr(tp_domain_model);

            // returns typeof Func<IQueryable<domain_class>, IOrderedQueryable<domain_class>> //
            Type tp_func = new utility.application.service_base().create_func(tp_domain_model);

            // here it's where it fails //
            return 
mapper.Map<List<application_class>>(domain_service_base.list(mapper.Map(ef_where, ef_where.GetType(), tp_expr),
mapper.Map(ef_orderby, ef_orderby.GetType(), tp_func)));
        }
```

**the expression tree map works like a charm** BUT, the **Func<** delegate **is throwing the error as I mentioned before**:

System.Func`2[System.Linq.IQueryable`1[domain.model.classes.c_config],System.Linq.IOrderedQueryable`1[domain.model.classes.c_config]] needs to have a constructor with 0 args or only optional args
Parameter name: type

this is the domain method signature:

public virtual List<t_model> list(Expression<Func<domain_class, Boolean>> ef_where, Func<IQueryable<domain_class>, IOrderedQueryable<domain_class>> ef_orderby)

so, what I'm trying to do is to map that delegate through tiers, from application tier to domain tier.

The problem is that IQueryable and IOrderedQueryable have no constructors, auto-mapper is throwing that exception.

Did I made myself clear now? Sorry, I'm not really good on explaining things.

[],
Regards,

@rmszc81

**Comment by TylerCarlson1** [comment]
Here's a "working" [Gist](https://gist.github.com/TylerCarlson1/ddbbe07647d6aa2dda71061b0bbbb297) that will compile and run.
Hopefully this helps you as a workaround as I made a BUNCH of guesses of what you were trying to do.  Also your example list function doesn't even return the right type.

The whole mapping Func thing I wouldn't recommend, and try working around somewhere else.

**Comment by rmszc81** [comment]
Wonderful, it works but,

as I'm using DI (dependence injection), it will work with

`mapper.map(source_object, sourceType, destinyType)`

?

**Comment by TylerCarlson1** [comment]
You would have to cast your types to match what DI expects to go over I guess.

IDK why you wouldn't use generics if you knew the types before hand.  It just makes things un-necessarily harder.

**Comment by rmszc81** [comment]
The models are generics, so, when I try to map with

`mapper.map(source_object, sourceType, destinyType)`

I got that exception of IQueryable has no default constructor.

Have any ideas?

**Comment by TylerCarlson1** [comment]
Can't do it use expressions or not AutoMapper. End of story for me

**Comment by rmszc81** [comment]
Thank u.

Your help was very useful.

I'll research more and u opened my mind for doing the things the right way.

Once more, thank u.

**Comment by rmszc81** [comment]
Just to inform, I solved!

Using <Expression<Func to map and using .Compile() method as I see on @TylerCarlson1 gist made specially for me.

Man, you're the guy, save my life.

Thank u, and @jbogard, you're the best.

[],
Regards,

@rmszc81.
