### ISSUE TITLE
AutoMapper 4.1.1 -> 5.2.0 Dynamic Enum Mapping differences

### ISSUE THREAD

**Issue by hugoj-goncalves** [AutoMapper/AutoMapper#1931]
Just wondering if there's a way to keep the old results without changing my code (Not really a problem, tough)

We used to have a few functions like this (on our tests):

```csharp
public static Foo GetFoo(Enum myEnum) {
    dynamic src = new { Item = myEnum };
    return Mapper.DynamicMap<Foo>(src);
}
```
which worked as expected, filling the correct **Enum** value from **myEnum**.
As for v5.2.0, we changed .**DynamicMap** to simply .**Map**, however it fails to map those enums correctly.
It always generates the **default** enum value.

If I pass the correct **Enum** type on _GetFoo_ (_GetFoo(**CorrectEnumType** myEnum)_), it also works as expected.

Is there something I'm missing?

EDIT: Simple example
    https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue
EDIT2: Actually the problem apparently started in **4.2.0**.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by hugoj-goncalves** [comment]
Oh, my bad. Totally missed that one.
But...
Got the same results that 5.2.0. (as per 5.3.0-alpha-01284)

**Comment by lbargaoanu** [comment]
The old DynamicMap had nothing to do with the C# dynamic. The equivalent now is to set CreateMissingTypeMaps in the configuration.

**Comment by hugoj-goncalves** [comment]
Yes I know, that's implicity (without the **CreateMisisngTypeMaps** it would throw an exception).

**Comment by lbargaoanu** [comment]
The problem is that setting CreateMissingTypeMaps might cause issues elsewhere. So maybe just use a real dynamic object for this particular case.

**Comment by lbargaoanu** [comment]
Anyway, even with CreateMissingTypeMaps, I don't see it. A repro would help. Make a gist that we can execute and see fail.

**Comment by hugoj-goncalves** [comment]
I'm working atm. 
When I get home I'll try to generate a minmal example.

**Comment by hugoj-goncalves** [comment]
Updated with simple example -> https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue

**Comment by lbargaoanu** [comment]
typeof(Enum).IsEnum is false. And because of CreateMissingTypeMaps, a new type map will be created, so the enum is not mapped as an enum. A few ifs would fix it, but I'm not sure that's a good idea. You should stay away from CreateMissingTypeMaps. It should be easy to work around it, even with CreateMissingTypeMaps true.

**Comment by lbargaoanu** [comment]
I've found a fix that makes more sense, but my point stands, don't do it :)

**Comment by hugoj-goncalves** [comment]
Cool, as I said we have a few of these cases on our tests only (which makes our life a bit easier).
Anyway, thanks for the advise ;)

**Comment by hugoj-goncalves** [comment]
I have another odd situation. I didn't have the time to check if it has already been reported or something yet.
I updated this repo https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue with a sample
I'm wondering if you could take a quick look over it ( I'll check and open another issue when I get home otherwise )
