### ISSUE TITLE
Automapper cannot be loaded from electron-edge

### ISSUE THREAD

**Issue by Umplify** [AutoMapper/AutoMapper#1932]
Have had a C# library which uses Automapper to map between two objects. When the code is running in C# context only (for e.g. as a console application, windows or web application) the things work fine. Now, the need is to invoke the same C# library from electron-edge. Attempting to do so results in getting the error message below:

Error: Could not load file or assembly 'AutoMapper, Version=5.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))

How can we address this issue?

**Comment by lbargaoanu** [comment]
Maybe ask this in an electron-edge forum?

**Comment by jbogard** [comment]
Yeah I have no idea.

**Comment by Umplify** [comment]
What are the dependencies of Automapper in .NET 4.6?

**Comment by jbogard** [comment]
Listed here:

https://www.nuget.org/packages/AutoMapper/5.2.0
