### ISSUE TITLE
Upgrade from 3.3.1

### ISSUE THREAD

**Issue by rboarman** [AutoMapper/AutoMapper#1934]
I'm getting an AccessViolationException exception calling Mapper.Map using version 3.3.1:

> System.AccessViolationException was unhandled
> Message: An unhandled exception of type 'System.AccessViolationException' occurred in Unknown Module.
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Code:

```
            var table = dataSet.Tables[tableName];
            List<Asset> result;
            using (var reader = dataSet.CreateDataReader(table))
            {
                result = Mapper.Map<IList<Asset>>(reader).ToList();
            }

```
This code has been running for quite a long time. I suspect the issue is some weird data in the source table which is coming from Excel.

Question 1) Is it safe and easy to upgrade to 5.2 from 3.3.1? I don't want to spend a lot of time upgrading.

Question 2) How can I get a better error message that would help me pin point the exact source of the error?

Thanks!

**Comment by lbargaoanu** [comment]
You can try locking around your Map calls, but other than that, you should upgrade to any later version that works for you.

**Comment by rboarman** [comment]
Is the upgrade from 3.3.1 to 5.2 straight forward? Do I need any code changes or is the new version compatible?

Thanks!

**Comment by jbogard** [comment]
Check out the upgrade guide, it should be very similar for 3.3.1
