### ISSUE TITLE
Ignore if null

### ISSUE THREAD

**Issue by krishnandusarkar** [AutoMapper/AutoMapper#1935]
Hi, Can anyone please guide me on how to conditionally ignore mapping from source properties if 

- source property is null

- source property is an int and 0 (bu default)

- source property is string and empty

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-250137782 and https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-265670132 for ideas.
