### ISSUE TITLE
AutoMapper 4.1.1 -> 5.2.0 Mapping differences

### ISSUE THREAD

**Issue by hugoj-goncalves** [AutoMapper/AutoMapper#1936]
I don't really know how to explain the issue I guess, but I'll try (anyway I made a "minimal" example about it [here](https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue) - [important file](https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue/blob/master/AutoMapperTestTests/UnitTestInheritance.cs#L16).

Let's say we have something like this:
```csharp
public FooProfileMap()
{
    CreateMap<Foo, OtherOwner>()
        .ForMember(d => d.OtherProp, opt => opt.MapFrom(src => src));
 
    CreateMap<FooChildOne, Other>(); 
        //.IncludeBase<Foo, Other>(); // Test pass if I uncomment this line
 
    CreateMap<FooChildTwo, Other>()
        //.IncludeBase<Foo, Other>() // Test pass if I uncomment this line
        .ForMember(d => d.Something, opt => opt.MapFrom(src => src.MyStringProp)); 
 
    CreateMap<Foo, Other>(); // Test pass if I remove this line
}
```
```csharp
[TestMethod]
public void TestMethod()
{
    var foo = new FooChildTwo
    {
        MyStringProp = "why?"
    };

    var other = Mapper.Map<OtherOwner>(foo);

    Assert.AreEqual(foo.MyStringProp, other.OtherProp.Something);
}
```

We have a lot of cases like this, where we map two objects from one (using *opt.MapFrom(src => src)*).
I don't really undestand why but in some cases it simply stops at the *parent* mapping, even tough we passed the *child* type.

well, let me know if it's not clear enough (my english is not that great) 

I had posted a message [here](https://github.com/AutoMapper/AutoMapper/issues/1931#issuecomment-276459709), but I guess it's better to be in a separated issue.

**Comment by lbargaoanu** [comment]
You should map things in the base map:

		cfg.CreateMap<Foo, OtherOwner>().ForMember(d => d.OtherProp, opt => opt.MapFrom(src => src));
		cfg.CreateMap<Foo, Other>().ForMember(d => d.Something, opt => opt.MapFrom(src => src.MyStringProp));

If you need special config for the derived classes, you use IncludeBase to reuse the base map.

**Comment by hugoj-goncalves** [comment]
I know that, but only _FooChildTwo_ has _MyStringProp_ in this case.

**Comment by lbargaoanu** [comment]
What about updating the code then? :)

**Comment by hugoj-goncalves** [comment]
Ooh... I guess I made a mistake there my bad haha
Will do in a sec.

**Comment by lbargaoanu** [comment]
I think there is still smth missing from the repro. You need something like 

    cfg.CreateMap<Foo, Other>().ForMember(d => d.Something, opt => opt.Ignore());

Otherwise, you don't pass validation. And what happens is that in the derived map you MapFrom to override the ignore and that only works if you include the base map. Is that the issue?

**Comment by hugoj-goncalves** [comment]
Hmm, may be. I didn't validate the mappings yet cuz there's simply too many tests failing.
If I simply put _MemberList.None_ to suppress validation I would still need to put the _IncludeBase_?

And why does IncludingBase on the _FooChildOne_ affect the result?

Will do a few more tests after validating the mappings.

**Comment by lbargaoanu** [comment]
You should _always_ pass validation. MemberList.None is more of an escape hatch. What happens here is that the execution plan for the mapping is built beforehand using the type information available at compile time. So you map Foo to Other, not FooChildTwo to Other. And in that map, Something is ignored. The solution that makes sense here is 

    cfg.CreateMap<Foo, Other>().Include<FooChildTwo, Other>().ForMember(d => d.Something, opt => opt.Ignore());

So you need to tell the base map about the derived one, where Something is mapped again. Now AM has all the info to generate beforehand the mapping code you want.

**Comment by hugoj-goncalves** [comment]
I see, will make sure our mappings are passing validation before I continue _fixing_ the tests.
I'm going to close this for now as I think it will be resolved with a _valid_ mapping.
Thank you ;)

**Comment by hugoj-goncalves** [comment]
I don't know, I can't understand this yet...
I updated the [example](https://github.com/hugito00/AutoMapper-4.1.1---5.2.0-issue/blob/master/AutoMapperTestTests/UnitTestInheritance.cs#L37) with mapping validation and I still can't see why telling that **FooChildOne** _exists_ affects **FooChildTwo** mapping result.

Is this behaviour really intended?

Also I'm kinda sad, we have a lot of cenarios like this one.
I really want to upgrade because of the performance boost, but it will take quite some time until I can "fix" those cases to work with the new version.

**Comment by lbargaoanu** [comment]
Ok, so you have some config that works by accident, we'll fix it and then it won't work, by design. How is that helpful? :)

**Comment by hugoj-goncalves** [comment]
It'll make me feel happier haha
I mean I just like when things make sense ;x

**Comment by lbargaoanu** [comment]
:) Ok, one for science I guess...

**Comment by lbargaoanu** [comment]
What I said above applies in the usual case, without Include. Include causes runtime types to be used and now AM knows that it's mapping the derived type, so the MapFrom overrides the Ignore. I guess it's weird, but with inheritance, that's the way is supposed to work. So inheritance really matters when Include is involved.

**Comment by hugoj-goncalves** [comment]
Hm, let me see if I got this.
As long as I don't use _Include_ (or _IncludeBase_) it will only look into compile time types.
So I should avoid using _Includes_ _if I can_ for performance reasons.
Is that it?

**Comment by lbargaoanu** [comment]
It is, but probably that's not relevant. The main thing is to have a config that makes sense and gets the job done. You can fine tune things afterwards if you need it.

**Comment by hugoj-goncalves** [comment]
Okay, will start making those changes as time goes by.
Thanks for being so helpful and sorry for bothering you this much haha ;)
