### ISSUE TITLE
Projecting to (flattened) model with translation for current user

### ISSUE THREAD

**Issue by mycroes** [AutoMapper/AutoMapper#1937]
In one of our projects we support translated entities. We use an interface `ITranslateable<TTranslation>` which contains `ICollection<TTranslation> Locales`. We then have `Machine : ITranslateable<MachineLocale> {...}` and `MachineLocale { ..., string Label { get; set; } }` (some details left out for brevity). What we then need is to have the MachineLocale matching the current user locale used for displaying the machine label. We can actually achieve this with the following expression: `.ForMember(dest => dest.Label, opt => opt.MapFrom(src => src.Locales.FirstOrDefault(l => l.LanguageCode == Thread.CurrentThread.CurrentUICulture.TwoLetterIsoLanguageName).Label)`, but that's rather cumbersome to do in all of our mappings. It would be nice to have something similar like `ResolveUsing(...)` to contribute to the mapping expressions that would allow us to reduce all the member overrides for translated fields.

**Comment by mycroes** [comment]
Of course this feature should not be tied to translations in any way, but maybe it can be used in conjunction with [parameterization](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization).

**Comment by TylerCarlson1** [comment]
#670 is similar to what you have.  Uses an ICollection instead of ITranslateable but the principle is the same.
#983 in the first comment shows an example to solve the problem in #670.
From there you should be able to alter it to make it work for your situation.

**Warning** Some of the code might be outdated, and you will have to deal with reflection and expressions

I'll try to look later to see what might need changing to adapt to you

**Comment by mycroes** [comment]
Thanks, I think it's not that hard to adopt. I already have the advantage of being able to check if sourceType is `ITranslateable<>`, and then I know sourceType has `.Locales` with `string LanguageCode` in it. So then I only need to check if the destination property has a matching source property in TTranslation.

I think I'll have a go at it tomorrow, will get back here if I can't get it working.

**Comment by TylerCarlson1** [comment]
OK sorry that's no longer valid scenario anymore.  It uses member info instead of Resolvers.
You would have to use IChildMemberConfiguration but map it to property of `ICollection<TTranslation>`.

Then after that you need to call ForAllPropertyMaps and find these property maps.  When you find these property maps you can then change them to use MapFrom and that should work.

**Comment by TylerCarlson1** [comment]
You could also use a resolver to the translation, but at that point it's not supported with ProjectTo, but the way I described shouldn't have a problem.

**Comment by mycroes** [comment]
Managed to get it working. Created the following:

    public class TranslatedMemberMapper : IChildMemberConfiguration
    {
        public bool MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType,
            string nameToSearch, LinkedList<MemberInfo> resolvers, IMemberConfiguration parent)
        {
            var translateableType =
                sourceType.Type.GetInterfaces()
                    .FirstOrDefault(
                        iface => iface.IsGenericType && iface.GetGenericTypeDefinition() == typeof(ITranslateable<>));

            if (translateableType == null) return false;

            var translationType = translateableType.GetGenericArguments()[0];
            var pi = translationType.GetProperty(nameToSearch);
            if (pi == null) return false;

            resolvers.AddLast(sourceType.Type.GetProperty("Locales"));
            return true;
        }

        public static bool IsTranslatedPropertyMap(PropertyMap pm)
        {
            return pm.SourceMember.Name == "Locales" &&
                pm.SourceType.IsGenericType &&
                typeof(LocaleBase).IsAssignableFrom(pm.SourceType.GetGenericArguments()[0]) &&
                pm.DestinationPropertyType == typeof(string);
        }

        public static void MapTranslatedMember(PropertyMap pm, IMemberConfigurationExpression memberConfig)
        {
            var localesPropertyInfo = (PropertyInfo)pm.SourceMember;
            var itemType = localesPropertyInfo.PropertyType.GetGenericArguments()[0];

            var languageCodeMember = itemType.GetProperty(nameof(LocaleBase.LanguageCode));
            var translationProperty = itemType.GetProperty(pm.DestinationProperty.Name);
            var firstOrDefaultMethodInfo = typeof(Enumerable).GetMethods()
                .First(m => m.Name == nameof(Enumerable.FirstOrDefault) && m.GetParameters().Length == 2)
                .MakeGenericMethod(itemType);

            var currentThreadProperty = typeof(Thread).GetProperty(nameof(Thread.CurrentThread),
                BindingFlags.Public | BindingFlags.Static);
            var twoLetterLanguageNameExpression = Expression.Property(
                Expression.Property(
                    Expression.MakeMemberAccess(null, currentThreadProperty),
                    nameof(Thread.CurrentUICulture)),
                nameof(CultureInfo.TwoLetterISOLanguageName));

            var sourceParam = Expression.Parameter(typeof(object), "src");
            var convertedSource = Expression.Convert(sourceParam, localesPropertyInfo.ReflectedType);
            var localesMemberExpression = Expression.Property(convertedSource, localesPropertyInfo);
            var firstOrDefaultParam = Expression.Parameter(itemType, "translation");
            var callFirstOrDefaultExpr = Expression.Call(firstOrDefaultMethodInfo, localesMemberExpression,
                Expression.Lambda(
                    Expression.Equal(Expression.Property(firstOrDefaultParam, languageCodeMember),
                        twoLetterLanguageNameExpression), firstOrDefaultParam));

            var translatedPropertyExpression = Expression.Property(callFirstOrDefaultExpr, translationProperty);
            var lambda = Expression.Lambda(translatedPropertyExpression, sourceParam);

            memberConfig.MapFrom((Expression<Func<object, string>>)lambda);
        }
    }

Then I have configuration like this:

	new MapperConfiguration(cfg =>
	{
		cfg.AddMemberConfiguration().AddMember<NameSplitMember>().AddMember<TranslatedMemberMapper>();
		foreach (var profile in k.ResolveAll<Profile>())
			cfg.AddProfile(profile);

		cfg.ForAllPropertyMaps(TranslatedMemberMapper.IsTranslatedPropertyMap, TranslatedMemberMapper.MapTranslatedMember);
	})

And last but not least the only issue I'm facing:

    public class StatusDefinitionMappingProfile : Profile
    {
        public StatusDefinitionMappingProfile()
        {
            CreateMap<StatusDefinition, StatusDefinitionListDto>();

            DefaultMemberConfig.AddMember<TranslatedMemberMapper>();
        }
    }

If I don't have `DefaultMemberConfig.AddMember<TranslatedMemberMapper>()` it never uses the mapper. So if you could help me out with that, I got it all working.

**Comment by TylerCarlson1** [comment]
The profiles have there own Configurations that are completely independent of each other.  You are going to have to use them for all the profiles.

There might be a global config option that would work in 5.3 alpha on MyGet, but not sure if it is applicable for this.

Another option you could try is if you can you could write a profile like this
```
public class ToDtoObjectProfile : Profile
{
    public ToDtoObjectProfile ()
    {
        // Handles CreateMap<StatusDefinition, StatusDefinitionListDto>(); and everything like it
        AddConditionalObjectMapper().Where((s, d) => s.Name == d.Name + "ListDto");

        // Non-standard CreateMaps could be added here

        DefaultMemberConfig.AddMember<TranslatedMemberMapper>();
        ForAllPropertyMaps(TranslatedMemberMapper.IsTranslatedPropertyMap, TranslatedMemberMapper.MapTranslatedMember);
    }
}
```
and it would handle all the simple to Dto mappings for you.  You can make the condition more specific if you need it to be.  This will replace all your other Dto transfer profiles.
All non-generic profiles can either be kept or you can add them into this profile if there are only a very few of them.

Then MapperConfiguration goes to
```
new MapperConfiguration(cfg =>
{
	foreach (var profile in k.ResolveAll<Profile>())
		cfg.AddProfile(profile);
})
```

This is going with the theme of making a convention to handle all the mappings that follow certain rules.

**Comment by mycroes** [comment]
It seems like a good idea, leads to another question though... How does the `AddConditionalObjectMapper()` work (in conjunction with `ForAllPropertyMaps`). I've been going through the source for half an hour, but the only thing I seem to be able to figure from this is that it works lazily, I.E. only creating the map when the mapper for the types is requested. Does it work like that? Does it apply the callbacks passed into `ForAllPropertyMaps` at that point as well?

Anyway, I definitely need to move to conventional profiles, I'm still living in version-3 era considering those...

**Comment by TylerCarlson1** [comment]
You got it right.

`AddConditionalObjectMapper()` creates the map the first time it's requested. `ForAllPropertyMaps()` gets called for every type map created in the profile.  Both from CreateMap and AddConditionalObjectMapper's lazily generated TypeMaps.

After it's called the first time the TypeMap is cached and re-used, just like a CreateMap would be.

**Comment by mycroes** [comment]
Thanks again for your time and answers. Would be nice to have some of this information on the Wiki as well.

**Comment by TylerCarlson1** [comment]
The wiki has this information [here](https://github.com/AutoMapper/AutoMapper/wiki/Conventions) although it doesn't get super detailed about IChildMemberConfiguration because it's a pretty advanced feature to try to explain.

**Comment by mycroes** [comment]
Wanted to add that since I've refactored my code slightly. The above code doesn't support flattening, while that's actually not really hard to support. Probably the easiest way to go would be to declare an extension method (which has the same purpose with regards to selecting language) and replace the occurrence of the extension method in the collection of `PropertyMap.SourceMembers`.
