### ISSUE TITLE
[Question]Conditional mapping based on source property information

### ISSUE THREAD

**Issue by Dresel** [AutoMapper/AutoMapper#1938]
Hi,

how can I model conditional mapping based on source property information? I want something like this:

	CreateMap<SomeModel, SomeOtherModel>().ForAllMembers(x =>
	{
		x.Condition(
			(source, destination, sourceMember, destMember) =>
			{
				// If source property is marked with a custom attribute introduce custom logic
			} );
	});

Any hints?

**Comment by lbargaoanu** [comment]
ForAllPropertyMaps would allow you to do that.

**Comment by Dresel** [comment]
Thanks that's awesome, don't know how I could overlook this. If someone is interested this is the code I used to ignore source properties marked with `ReadOnly` attributes:

    configure.ForAllPropertyMaps(map =>
        map.SourceMember.GetCustomAttributes().OfType<ReadOnlyAttribute>().Any(x => x.IsReadOnly),
        (map, configuration) =>
        {
            configuration.Ignore();
        });

**Comment by BerdyPango** [comment]
@Dresel Hi, I just met the same problem here, but I want to do more other than just ignore, like calculating a value based on the given source value and set it to destination one. Do you have any idea about that? thanks.

**Comment by BerdyPango** [comment]
It's more like this:
```
                cfg.ForAllPropertyMaps(responseEecryptionFilter, (map, configuration) =>
                 {
                       // calculating value based on the source value and set it to destination value..
                 });
```
