### ISSUE TITLE
MapperConfigurationExpression.AddProfile<T> to use ServiceCtor instead of Activator

### ISSUE THREAD

**Issue by demoran23** [AutoMapper/AutoMapper#1939]
MapperConfigurationExpression.AddProfile<T> is using Activator to construct the profile, which necessitates T : new().  The ServiceCtor can be used to construct the profile, which can then use constructor injection.

**Comment by lbargaoanu** [comment]
You can work around it by using the overload that takes a profile instance.

**Comment by demoran23** [comment]
Quite true, that's what I'm doing right now.

**Comment by jbogard** [comment]
Noooooo profiles should not be constructed by DI. Any DI config should be
passed through runtime instances like resolvers or type converters.

**Comment by demoran23** [comment]
I'm actually new to using AutoMapper.    @jbogard, why is constructor injection okay for resolvers and type converters, but not okay for profiles?

**Comment by lbargaoanu** [comment]
I think @jbogard means that a profile it's a configuration (as opposed to executable), static thing and only singleton lifetime would really make sense, so maybe DI is not that useful. Not absurd or anything, just not that useful :)

**Comment by jbogard** [comment]
Profiles are about configuration and are singleton, and resolvers and type converters are about runtime mapping execution. I'll see people taking dependencies on repositories/DbContext inside your Profile, which was never its intention.

Although if it's static configuration passed in, I suppose that's OK.

**Comment by lbargaoanu** [comment]
@demoran23 If you still think this would useful, you should try a PR.
