### ISSUE TITLE
An error occurred while retrieving package metadata

### ISSUE THREAD

**Issue by Sam-Davis** [AutoMapper/AutoMapper#1941]
When trying to install another package using Nuget, I get this message: 

Install-Package : An error occurred while retrieving package metadata for 'AutoMapper.5.2.0' 
from source 'C:\..\Visual Studio 2015\Projects\MyProject\packages'

I then need to manually uninstall AutoMapper each time before installing another package. My Nuget version is 3.3.0

**Comment by jbogard** [comment]
Upgrade NuGet first.

**Comment by Sam-Davis** [comment]
The issue I was having was that Automapper was already installed by default so I was adding it in twice. This currently doesn't show an error until you try to use nuget afterwards
