### ISSUE TITLE
Unable to cast object to ITypeConverter?

### ISSUE THREAD

**Issue by DaveVdE** [AutoMapper/AutoMapper#1942]
Consider the following program: https://github.com/DaveVdE/AutofacProblem/blob/master/Program.cs

It produces the following (inner) exception:

> Unable to cast object of type 'ConsoleApp2.ImmutableDictionaryConverter`2[System.String,System.String]' to type 'AutoMapper.ITypeConverter`2[System.Collections.Immutable.ImmutableDictionary`2[System.String,System.String],System.Collections.Generic.Dictionary`2[System.String,System.String]]'.

What's going wrong?

**Comment by DaveVdE** [comment]
I did some more investigation, and it works if I don't use the open generics:

`configure.CreateMap<ImmutableDictionary<string, string>, IDictionary<string, string>>().ConvertUsing<ImmutableDictionaryConverter<string, string>>()`

**Comment by DaveVdE** [comment]
Thanks, I will give that a try as well!

**Comment by lbargaoanu** [comment]
I wouldn't call this a bug. The cast fails only because the property type and the destination type parameter in ITypeConverter don't match. I didn't notice at first.

**Comment by DaveVdE** [comment]
Didn't say it was. I was only following https://github.com/AutoMapper/AutoMapper/issues/1330.

Anyway, my problem is solved.
