### ISSUE TITLE
AutoMapper creates severe memory pressure

### ISSUE THREAD

**Issue by natiki** [AutoMapper/AutoMapper#1943]
Hi,

- AutoMapper 5.2.0
- .NET 4.61
- WebForms
- Visual Studio 2015

While debugging VS kept telling me I was running out of memory, and when I looked at the VS memory allocation it was huge. I have narrowed it down to AutoMapper but don't know how to proceed. Using dotMemory from JetBrains here is what the memory allocation looks like after a fresh run of the application without AutoMapper assembly scanning and around 3mins in:

![image](https://cloud.githubusercontent.com/assets/4738140/22645720/8ab3e78e-ecbc-11e6-876d-8ff32383611b.png)

So around ~720MB. Then I add back the following code:

```c#
/// <summary>
    ///     Class used at startup to register all the auto mapper mappings between the
    ///     various classes
    /// </summary>
    public static class MapperConfig
    {
        public static void RegisterMappingsV51()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.AddProfiles(
                    "MyApp.Application",
                    //"MyApp.Common",  -- No profiles in there
                    //"MyApp.Core",    -- No profiles in there
                    "MyApp.DataAccess",
                    //"MyApp.DataImport",       -- No profiles in there
                    //"MyApp.EntityFramework",  -- No profiles in there
                    "MyApp.Platform",
                    "MyApp.Reports"
                );
            });

            //**Mapper.Configuration.AssertConfigurationIsValid();
        }
    }
```

The above method call is made during the first request to the application, and now when I look at the memory allocation after 3 mins: (**nothing else changed except for the above code being commented in**):

![image](https://cloud.githubusercontent.com/assets/4738140/22645848/3fbd4d50-ecbd-11e6-832b-f757aea57064.png)

and now the memory is a whopping 1.5GB!!! I have around 70 profile classes that are very simplistic for the most part viz:

```c#
public class AoADboCnaToIndividualMappingsServiceAutomapperProfile : Profile
 {
     /// <summary>
     /// Override this method in a derived class and call the CreateMap method to associate that map with this profile.
     /// Avoid calling the <see cref="T:AutoMapper.Mapper" /> class from this method.
     /// </summary>
     protected override void Configure()
     {
          CreateMap<DboCnaToIndividualMappingsTableModel, AoADboCnaToIndividualMappingsRecordItem>();
     }
 }
```

and a few that have multiple CreateMap<> statements in them for say an all up 100 maps roughly. So any thoughts on why the memory spike? As I said if I take out the above AddProfiles() call then memory drops. In both cases the application is sitting at a login form so has not done much at all.

At this point trying to develop in the solution has become unworkable as VS keeps crashing or running out of memory. I am guessing this issue has "grown over time" and I have not noticed it till now.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by natiki** [comment]
I'll see what I can do. However this is a large production system so pulling stuff out will be hard and I am assuming there is something else at play here.

I am guessing that this is not expected and the unit tests cover this scenario?

**Comment by jbogard** [comment]
We do run benchmarks as part of every build, and have been doing our best to perf test mapping, including memory benchmarking.

Configuration though is something that's difficult to test for, since I've only reliably reproduced large mapping configurations just from client projects. I benchmark there, timing how long it takes to evaluate configuration etc.

**Comment by lbargaoanu** [comment]
A full memory dump of your application might help. Release and not under the debugger.

**Comment by natiki** [comment]
How do I generate the full memory dump?

**Comment by lbargaoanu** [comment]
Just google it.

**Comment by natiki** [comment]
Still using AutoMapper 5.2.0 here are the links to the dumps. Using exactly the same criteria as above:

- [Without AutoMapper](https://drive.google.com/file/d/0Bzy5VpxF6yWxREdDY2lFb19CdFE/view?usp=sharing)
- [With AutoMapper](https://drive.google.com/file/d/0Bzy5VpxF6yWxZ0E3bW05Z0RKUjA/view?usp=sharing)

**Comment by lbargaoanu** [comment]
I see 32 profiles with 141 maps. And that takes some memory that will remain allocated forever. Besides that, short term, probably it allocates a lot more memory. But if the config is quick enough, then it's not a big deal. That's my first impression.
To investigate deeper I need c:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll and c:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll from the same machine. They should have version 4.6.1586.00.

**Comment by lbargaoanu** [comment]
I've found the dlls myself eventually. Most of the heap is free space and strings, some very large. AutoMapper has nothing to do with it as far as I can tell.

**Comment by lbargaoanu** [comment]
For future reference, a 64 bit dump of a 32 bit process just makes things difficult.

**Comment by natiki** [comment]
Hi Lucian,

Appreciate you looking into this.

You say AM has nothing to do with it. So how come when I **don't** scan for profiles the memory profile is so different? That makes no sense when the application is unchanged other than that. How is AM influencing things to make the memory profile **DOUBLE.** At this point I am no closer to fixing this as I don't understand what is going on other than - don't use AM because it kills the memory profile. 

What else can I do to narrow this down?

If you would prefer dumps done another way then please let me know.

**Comment by lbargaoanu** [comment]
That's about your application. You have to track the objects that get allocated. Of course, if you can repro this outside your app, we'll take it up again.
