### ISSUE TITLE
TypePair.Create disregards declared source type.

### ISSUE THREAD

**Issue by BlackjacketMack** [AutoMapper/AutoMapper#1946]
The current behavior uses the type returned from the .GetType() method of the source instead of the declared type.  

This behavior inhibits polymorphic behavior of classes.  
 Sometimes we may want to map things in different ways, and interfaces nicely allow us to operate on an object as the interface and not on the object as a whole.

if User : IRestrictedUser
Map.Create<User,UserDTO>(user)...should possibly operate differently from...Map.Create<IRestrictedUser,UserDTO>(user).  They currently do not.  The TypePair class disregards the inbound declared source type.

![screen shot 2017-02-10 at 7 10 22 am](https://cloud.githubusercontent.com/assets/1722131/22826425/6011a178-ef60-11e6-8e00-5149a4fe7667.png)

![screen shot 2017-02-10 at 7 10 41 am](https://cloud.githubusercontent.com/assets/1722131/22826434/67efc730-ef60-11e6-90cc-18bd6e03acc5.png)

**Comment by lbargaoanu** [comment]
Try a restricted interface for the DTO and a map between the interfaces with As to specify the concrete destination.

**Comment by lbargaoanu** [comment]
That's by design. It was discussed many times before.
