### ISSUE TITLE
Resolver interfaces order is important during resolving nullable field

### ISSUE THREAD

**Issue by rmaziarka** [AutoMapper/AutoMapper#1949]
Hi,

I found strange error during refactoring my resolvers to new AutoMapper version. Let's assume that we have resolver which contains two resolve methods: object -> int? and object -> int:
https://gist.github.com/rmaziarka/ed9f090da11d3a68023872e2c6e8b6b0

And it maps object to nullable int. Then I replaced order of interfaces and put not nullable at the begining:
https://gist.github.com/rmaziarka/d7778d0ae7d3f2e58a1879f4678c4e2e

And it throws _Nullable object must have a value_ during mapping to nullable int. I think this is not a proper behaviour, am I right?

Could you tell me where in AutoMapper code there is a usage of these resolvers so I could investigate it and eventually create PR about it?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
