### ISSUE TITLE
TypeMapCreated Event 

### ISSUE THREAD

**Issue by Serenyrddraig** [AutoMapper/AutoMapper#1950]
I'm making a big upgrade from Automapper 3.3.1 to Automapper 5.x. The 'ancient' code had leveraged the event IConfiguationProvider.TypeMapCreated for a number of internal purposes. In each case, the code was working with the individual TypeMap for Source or Destination (or both), e.g. populating a KnownTypes collection for a DataContractSerializer.

It appears that the current option is to change this code to iterate the TypeMaps returned from IConfigurationProvider.GetAllTypeMaps(). Is there a better way? Any chance that the event will be added to IConfigurationProvider again?

**Comment by lbargaoanu** [comment]
GetAllTypeMaps should do it.

**Comment by TylerCarlson1** [comment]
Maybe ForAllTypeMaps which will be called every time a type map is being configured.  It might not have the mapper configuration finalized, but it should be called for every type map.
