### ISSUE TITLE
Mapping from DTO to DataRow (DataTable/DataSet)

### ISSUE THREAD

**Issue by flcdrg** [AutoMapper/AutoMapper#1951]
I need to map between a DTO and a row in a DataTable (part of a DataSet).

All the properties of the DTO class correspond to column names in the DataTable. Mapping in the reverse direction is straight forward as I can reference the property names, but I can't see a nice way to use the property names when the DataRow object is the destination. 

I'm currently resorting to using ConvertUsing and manually mapping each property to the corresponding column. Is that the only option?

Dave

**Comment by TylerCarlson1** [comment]
Have you tried https://github.com/AutoMapper/AutoMapper.Data?

**Comment by flcdrg** [comment]
I'd looked at it a little while back, but I see there's been some new activity this year. I'll check it out.

I'd also been starting down the rabbit hole of IChildMemberConfiguration, but I'd much prefer to leverage something that already exists.

Pity there's no myget builds that I can see for AutoMapper.Data :-(

**Comment by flcdrg** [comment]
Having said that, AutoMapper.Data does seem all about mapping From an IDataReader To a DTO. I want to go the other way - though maybe it will give me some clues.

**Comment by lbargaoanu** [comment]
I'm not saying it's a good idea, but it's [possible](https://gist.github.com/lbargaoanu/f23b61dd76ed5a40fb6d3926fb5d4201#file-datarow-cs) :)

**Comment by flcdrg** [comment]
Thanks @lbargaoanu, I know it's hacky but that is helpful. That might get me over the line.

But theoretically it should be possible to write a custom `IObjectMapper` or something that uses Expressions?

**Comment by TylerCarlson1** [comment]
It is possible but Expressions are a huge pain.  Make it call a static generic method would be the best option.  Look at the Collection Mappers that call a map expression to help make things easier.

**Comment by flcdrg** [comment]
Argh.. the IDictionary trick from @lbargaoanu was looking really promising, but because it's inside a ConvertUsing, then [I believe that prevents me from using Include/IncludeBase](http://stackoverflow.com/questions/37469929/automapper-inheritance-mapper-not-working-with-construct) to add special handling for particular entities.

**Comment by lbargaoanu** [comment]
You can make it work with a combination of Include/Base and As for example (ConstructUsing might work too), but at this point, maybe not use AM for this? :) I mean, does it really help?

**Comment by lbargaoanu** [comment]
An for future reference, usually a custom map is enough, but if needed, you can also write [a simple object mapper](https://github.com/AutoMapper/AutoMapper/blob/094a2c1456c9a3e916726a9aa60ddb2dc07cf66d/src/UnitTests/Mappers/CustomMapperTests.cs#L69), without expressions.

**Comment by flcdrg** [comment]
That `ObjectMapper` base class is nice. It appears to be pretty much an alternative to CreateUsing. I don't think I can use `IncludeBase` with it though.

I was hoping I could define the base mapping (eg via an implementation of ObjectMapper) and then provide specialised mappings for various entities to deal with parent/child relationships. 

eg. if I had Order and OrderDetail, then for mapping an Order I'd like to iterate through the Order.Details collection and map each child OrderDetail (as these would also be mapped to a corresponding DataTable in the DataSet)

**Comment by flcdrg** [comment]
Yes, I realise I'm possibly 'going against the grain' of what AM can do. 

So as I see it, I could go ahead with the `ObjectMapper` approach and implement custom classes for each specialised type that know what children or parents need to mapped..

OR I figure out how `Expression`s work and do it that way, so that I think I can then leverage the AfterMap/IncludeBase methods and just use CreateMap for each specialised type.

The latter seems potentially 'cleaner' as I won't end up with a bunch of extra classes, but on the other hand at least I can see the former actually being achievable by me in a reasonable amount of time :-)

**Comment by TylerCarlson1** [comment]
Oh I see AM's code doesn't have what I mentioned.  Here look at this example AM.Collections https://github.com/AutoMapper/AutoMapper.Collection/blob/master/src/AutoMapper.Collection/Mappers/EquivlentExpressionAddRemoveCollectionMapper.cs

This makes a static method that you can call from an expression and you can write plain old common code in there to do what you want.  The performance difference is practically non-existent and it's a million times easier to write.  And you can recursively call the function to map children collections easily enough.

**Comment by lbargaoanu** [comment]
You can go the CreateMap and Include route if you feel you're reusing design or smth :) But you don't need expressions for anything.

**Comment by lbargaoanu** [comment]
@TylerCarlson1 A simple object mapper is an elegant way to do what you say :)

**Comment by flcdrg** [comment]
FYI I've gone down the `ObjectMapper` route and it seems to be working quite nicely. I've add a hook so that I can do extra processing after the main mapping (the equivalent of `AfterMap`).

Thanks both for all your help and suggestions!
