### ISSUE TITLE
Parameterization not working when source field is untouched in MapFrom

### ISSUE THREAD

**Issue by epohknarf** [AutoMapper/AutoMapper#1952]
Hi,

I get an exception in my mapping when following your example for Parameterization;
[https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization](url)

    public static class MappingsForSomething
    {
        public static MapperConfigurationExpression ConfigureMappingsForSomething(this MapperConfigurationExpression configExpression)
        {
            string anotherString = null;

            configExpression.CreateMap<SourceClass, DestinationClass>()
                .ForMember(destination => destination.aString, c => c.MapFrom(source => anotherString));

            return configExpression;
        }

        public class SourceClass
        {
            public string aString { get; set; }
        }

        public class DestinationClass
        {
            public string aString { get; set; }
        }
    }

Running against EFCore with the following code:

    var somethings = await Context.Somethings
        .ProjectTo<DestinationClass>(MapperConfiguration, new { anotherString = "test" })
        .ToListAsync();

I get the following exception;

    System.Data.SqlClient.SqlException: An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.

If I touch the aString field inside MapFrom it works fine:

            configExpression.CreateMap<SourceClass, DestinationClass>()
                .ForMember(destination => destination.aString, c => c.MapFrom(source => source.aString == "" ? anotherString : anotherString));

I am currently using:

    AutoMapper 5.2.0
    Microsoft.EntityFrameworkCore 1.0.1

**Comment by jbogard** [comment]
Two things - can you post the expression from the result of ProjectTo, and second, try your projection and variable without AutoMapper. We get quite a few bugs reported to AutoMapper that are actually bugs in EFCore.

**Comment by lbargaoanu** [comment]
This works with EF6.

**Comment by jbogard** [comment]
@lbargaoanu of course it does lol
