### ISSUE TITLE
CreateMissingtypemaps  with  EF6 DynamicProxies

### ISSUE THREAD

**Issue by Gavinluo** [AutoMapper/AutoMapper#1954]
i used automapper 5.2 , Entity Framework 6 and use `CreateMissingTypeMaps=true ` to save my CreateMap code , and i also have special map, so Initialize code like this

     Mapper.Initialize(
                a =>
                    {
                        a.CreateMissingTypeMaps = true;
                        a.CreateMap<query_template, QtGridUdfSearchTemplate>()
                   .ForMember(dest => dest.GridId, opt => opt.MapFrom(src => src.GRID_ID))
                   .ForMember(dest => dest.Guid, opt => opt.MapFrom(src => src.QUERY_TEMPLATE_GUID))
                   .ForMember(dest => dest.TemplateName, opt => opt.MapFrom(src => src.TEMPLATE_NAME))
                   .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CREATED_BY))
                   .ForMember(dest => dest.IsDefault, opt => opt.MapFrom(src => src.IS_DEFAULT))
                   .ForMember(dest => dest.IsOffset, opt => opt.MapFrom(src => src.IS_OFFSET));
                    }
             ); 

and map code 

     var source = DbContext.Set<query_template>().Find(keyValue);
     var dest = Mapper.Map<query_template, QtGridUdfSearchTemplate>(source);
i get the `dest` all attribute is null ,when i remove `a.CreateMissingTypeMaps = true;` in Initialize , it is work , the `dest` all attribute can be map.then i found the `source` Type is `System.Data.Entity.DynamicProxies.query_template_80DE6B32EB08D5DFDD560580BB004DAD6A7FF27B94A3517A6BB4044B01FB8272` , so i think when i set CreateMissingTypeMaps , autoMapper auto create a map , not my create 

any config missing?

**Comment by TylerCarlson1** [comment]
Don't use CreateMissingTypeMaps unless you don't know the types at run time.  Look at https://github.com/AutoMapper/AutoMapper/wiki/Conventions#conditional-object-mapper to get a more restrictive map generation.  The proxy type is first used so it makes a type automatically.  The conventions will make sure that won't happen but the maps you want will be generated.

**Comment by Gavinluo** [comment]
Thanks TylerCarlson1.
