### ISSUE TITLE
AutoMapper ignore feature when doing mapping

### ISSUE THREAD

**Issue by sonphnt** [AutoMapper/AutoMapper#1955]
Hi Everyone,

I am thinking about how to do Ignore function of Automapper correctly. For example:
I have 1 entity class from Database with around 10 properties.
I make 1 new DTO class with exactly the same 10 properties + 3 more new properties to return to view.

If we use Mapper.CreateMap<Entity1, EntityDTO1>().ForMember(x=>x....Ignore()) then it will always Ignore that property when I use
var myDTO = Mapper.Map<Entity1, EntityDTO1>(item);

What if I have many cases returning data to client, sometimes I would like to return 7 properties or 9 properties? 

By creating 2 DTO classes, one EntityDTO1 with 7 properties, one EntityDTO2 with 9 properties, then AutoMapper Ignore() will not make sense any more. Because you can create a DTO class with a number of properties you want, and dont need to use AutoMapper Ignore(). So why/when do we have to use AutoMapper Ignore ?

Should we have a feature can do like this.
var myDTOIgnoreProperty1 = Mapper.Map<Entity1, EntityDTO1>(item).Ignore(x=>x.Property1);
var myDTOIgnoreProperty2 = Mapper.Map<Entity1, EntityDTO1>(item).Ignore(x=>x.Property2);

Thanks

**Comment by lbargaoanu** [comment]
One option is to map interfaces instead of concrete classes. Another is to simply reset the source properties before calling Map :)

**Comment by lbargaoanu** [comment]
If you feel it adds structure you can use the per call BeforeMap event.

**Comment by sonphnt** [comment]
BeforeMap does not solve the problem. The problem is how to handle dynamic Ignore at the time you want but still want to keep using 1 DTO class with 1 entity class

**Comment by lbargaoanu** [comment]
I said [per call](https://github.com/AutoMapper/AutoMapper/blob/c968f34e58eed73e7cb40e8e52849408693eddb6/src/UnitTests/BeforeAfterMapping.cs#L163). Of course, you don't really need that, you can simply write the code before calling Map.

**Comment by sonphnt** [comment]
Thank @lbargaoanu that seems to work but we have to write some more code in AfterMap event with a verbose lambra expresssion

**Comment by jbogard** [comment]
If you're using projections, you have a few more options there with ExplicitExpansion. That works with child objects too.

**Comment by sonphnt** [comment]
Hi @jbogard do you have an example about that ?

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#explicit-expansion

**Comment by sonphnt** [comment]
Hi @JakeGinnivan 

ExplicitExpansion is configured in CreateMap, so we can not control which properties should be ignored when calling mapping.

In my point of view, AutoMapper should only do a simple map like this and that is it:
Mapper.CreateMap<DomainEntity, DTOEntity>();

This will map everything between 2 classes with the same property name. And base on condition we will ignore properties later
Mapper.Map<DomainEntity, DTOEntity>(host).ForMember(........)

That would be easier if we can have ForMember() at this step, so we will have a generic DTOEntity class with 1 Entity class.

**Comment by jbogard** [comment]
Taking a step back, how exactly is this getting used? The class will still have all its properties, but some will just have nulls? How do you know what is ACTUALLY null vs. something that had properties cleared out with a conditional ignore?

**Comment by sonphnt** [comment]
For Example I have 2 classes: Team and Member

`public partial class Member
{
        public virtual Team Team {get;set;}
}

public partial class Team
{
        public virtual ICollection<Member> Member {get;set;}
}`

When I do a EF query like this
`dbContext.Member.Include(x=>x.Team).ToList();`

It will return 200 members with Team object and its Member List (because all member loaded will be added into its Team automatically by EF) like
`[
{
     Name: "John",
     Team: {
          Name: "Team 1",
          Member: [] **// I want to ignore this list when doing AutoMapper**
     }
}
]`

So Sometimes I want to ignore Member list of Team object to reduce the size when parsing to JSON before returning to client, sometimes I want to keep that Member list with the case less data as getting a single Member with Team included.

**Comment by jbogard** [comment]
OK so my typical recommendation here is don't build an API that returns a
generic result like this. If consumers sometimes do and sometimes don't
want certain information, use OData. If you can't do that, build
request-specific API endpoints with request-specific DTOs.

**Comment by sonphnt** [comment]
Hi @jbogard 

Build specific DTO will solve the problem easily. I mean it would be better if AutoMapper can support a feature like that.

**Comment by jbogard** [comment]
It does in terms of projections, specifically for OData. But for regular
mapping, I don't think I'll ever really have that feature.
