### ISSUE TITLE
ProjectTo<>(...,Expession<<>>[]membersToExpand): lambda for a Value Type causes NullReferenceException

### ISSUE THREAD

**Issue by moudrick** [AutoMapper/AutoMapper#1956]
ProjectTo method, 
membersToExpand parameter, 
Expession[] signature, 

lambda for a Value Type causes NullReferenceException

Details are at SO http://stackoverflow.com/questions/41945809/automapper-5-2-ignores-explicitexpansion-if-it-is-configured-in-base-dto-mapping

See section UPD2 of the Question, code snippet, 
`[TestMethod] public void ProjectAllWithMemberExpression_Exception() => _iq.ProjectTo<DtoDerived>(_ => _.Name, _ => _.Desc);`

**Comment by lbargaoanu** [comment]
What's the scenario here? It seems strange to use ExplicitExpansion with a value type.

**Comment by moudrick** [comment]
I agree it is strange for non-nullable types. In case of nullable, one may need skipping its expansion. As a matter of fact, int? and any nullable type is actually a value type, despite the fact that it can be null as reference type do.

**Comment by lbargaoanu** [comment]
ExplicitExpansion is used to avoid fetching a child object, but is it worth it for a simple value? :)

**Comment by moudrick** [comment]
Yes, if you want your projection to avoid generating additional joins on flattening db model. E.g. if you MapFrom a field like `_ => _.InnerObject.AnotherInnerObject.ScalarField`

**Comment by lbargaoanu** [comment]
Aha, that makes sense.

**Comment by moudrick** [comment]
Well, I updated the PR with more examples that illustrate optional mapping from int to int? with deep inner member flattening.

**Comment by lbargaoanu** [comment]
Another way to solve this would be to make the expression type-safe, but that is probably overkill.
