### ISSUE TITLE
Automapper 5.2 ignores ExplicitExpansion if it is configured in Base DTO mapping

### ISSUE THREAD

**Issue by moudrick** [AutoMapper/AutoMapper#1958]
comprehensive details and discussion in Q&A@SO: Automapper 5.2 ignores ExplicitExpansion if it is configured in Base DTO mapping

**Comment by lbargaoanu** [comment]
Include doesn't really work with EF, so why bother?

**Comment by moudrick** [comment]
Is it planned to make Include working with EF? If it is not a rocket science and if any hint where to do this, I could contribute it.

**Comment by lbargaoanu** [comment]
No. Search the older issues, it has been discussed a few times.

**Comment by jbogard** [comment]
EF can't work AFAIK. Unless you can produce a Select projection without AutoMapper against EF, we can't help.
