### ISSUE TITLE
5.2.0 Mapping 1st Enum value to string field always return null

### ISSUE THREAD

**Issue by Banzzouille** [AutoMapper/AutoMapper#1960]
Source class contains an enum type field .
Destination class contains a type string field .

When we map an instance of source type to the destination type it returns "null" when we use the first value of the enum type.

You can found in attachment a little solution that reproduces the issue.

[TestReproduce.zip](https://github.com/AutoMapper/AutoMapper/files/777497/TestReproduce.zip)

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by Banzzouille** [comment]
Hi, thank you for the quick response.
The 5.3 alpha version seems to correct this issue.
But i can't use this version in a production software.... 
So i'll do some shitty patch for the moment and pray to have a new version quickly ^^

Regards

**Comment by lbargaoanu** [comment]
There's no difference in the deployments of MyGet vs NuGet, same amount of testing goes into each build. NuGet is all about locking down the version.
