### ISSUE TITLE
Convention for mapping underscore separated property names

### ISSUE THREAD

**Issue by gusarov** [AutoMapper/AutoMapper#1961]
I have to use JavaScriptSerializer and sometimes it forces me to create a classes with underscore in property names, like this:

    internal class TradeResponse
    {
        // ReSharper disable once InconsistentNaming
        public ulong Order_Id { get; set; }

Because this is how field named in Json (Am I missed an ability to configure JavaScriptSerializer?). This forces me to explicitly declare AutoMapper config for each of such property when I mapping this to my DTO... Can you provide an ability to configure mapper with some convention?
Another example that comes in mind: what if I just want to map some internal fields named like _fieldName? Is it possible to automap them?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/c04f98f62f60ada3ca9285201324490bcc1a1ae5/src/UnitTests/ReverseMapping.cs

**Comment by lbargaoanu** [comment]
And [the docs](https://github.com/AutoMapper/AutoMapper/wiki/Configuration).
