### ISSUE TITLE
Mapping same type results in reference to source object instead of expected new object.

### ISSUE THREAD

**Issue by BlackjacketMack** [AutoMapper/AutoMapper#1962]
Basically, if the source and destination type are the same, AutoMapper does not create a new object, nor does it populate an existing object, unless you explicitly create a type map.  However, if CreateMissingTypeMaps is true, I would expect it to not be necessary to create that missing type map.

Previous comments have said that '.Clone()' is a better approach, but there are many use-cases for us where we need to copy to existing objects, specifically leaving context properties off which we were planning on doing with the AfterMap() functionality.

I would suggest (and be happy to try to write a pull request) the following:
* If 'CreateMissingTypeMaps' is false, throw an exception the way you would with any other type mapping.  Map<T,T>(s,d) would fail.
* If 'CreateMissingTypeMaps' is true, create the destination (or populate existing) the way it operates with any other type mapping. Map<T,T>(s,d) would populate 'd' with 's' (but be different refs).

There's nothing particularly special about mapping two objects of the same type, so I'm curious why the behavior is handled so differently.

```
private class Foo
        {
            public int ID { get; set; }
        }

        [TestMethod]
        public void TestMap()
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMissingTypeMaps = true;
            }
            );

            var source = new Foo { ID = 1234 };

            var destination = SupplyitMapper.Map<Foo>(source);

            Assert.AreNotSame(source, destination);     //fails...same object is returned...why?
        }

```

**Comment by TylerCarlson1** [comment]
Short answer AutoMapper is not a cloning project.

Longer answer is the IObjectMappers take priority over generating a new TypeMap.  Assignable map wins, which is meant for things like int -> int, string -> string, ect where the types are the same and there's no point to generating a new item.

Putting generating TypeMaps before IObjectMappers means when CreateMissingTypeMaps=true the default mapping functionality will never be called and AM will break Big League.

Best option is to have an attribute or use reflection or write a profile to manually map your code.  Or replace AssignableMapper and replace it with your own where you can ignore classes you want.

**Comment by BlackjacketMack** [comment]
Thanks.  I'll look into providing my own AssignableMapper.

**Comment by squarewave24** [comment]
@BlackjacketMack having the same issue. did you ever elaborate assignable mapper

**Comment by huancz** [comment]
@squarewave24 & anyone else who find this in the future: I did toy with replacing assignable mapper and got it working. Unfortunately, surprisingly many mappings in this project turned out to depend on old behaviour. If I knew automapper is returning original reference in this case (especially if I use CreateMissingTypeMaps=false) I would have restricted it at the start of the project. Now it would be too painful change, I'd have to write explicit mapping for many enum-based DTO classes or add all their references to .Ignore() mapping. I won't be using it in the end, but you can have the code anyway.

```c#
    class RestrictedAssignableMapper : IObjectMapper
    {
        public bool IsMatch(TypePair context) =>
            context.DestinationType.IsAssignableFrom(context.SourceType)
            && (context.SourceType.IsValueType || context.SourceType == typeof(string))
            ;

        public Expression MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
            => sourceExpression;
    }

    public static class TestMapperConfiguration
    {
        public static void ConfigureAutomapper()
        {
            var mce = new MapperConfigurationExpression();
            mce.CreateMissingTypeMaps = false;
            mce.AddProfile<StrictAutomapperProfile>();
            mce.AddProfile<LooseAutomapperProfile>();
            for (int i = 0; i < mce.Mappers.Count; ++i)
            {
                if (mce.Mappers[i].GetType() == typeof(AssignableMapper))
                {
                    mce.Mappers[i] = new RestrictedAssignableMapper();
                }
            }

            Mapper.Initialize(mce);
            Mapper.AssertConfigurationIsValid();
        }
   } 
```
