### ISSUE TITLE
AutoMapper 5.2.0 does not map nullable Types [long? -> Enum?]

### ISSUE THREAD

**Issue by MO2k4** [AutoMapper/AutoMapper#1963]
Hi,

we got a problem with mapping nullable-Types in Automapper 5.2.0. 

We got the following code working with version 5.1.1, but it is broken with 5.2.0

`
public class GrundMapping : Profile
    {
        public GrundMapping()
        {
            CreateMap<long?, Grund?>().ConvertUsing<GrundTypeConverter>();
        }
    }

public class GrundTypeConverter : ITypeConverter<long?, Grund?>
    {
        public Grund? Convert(long? source, Grund? destination, ResolutionContext context)
        {
            if (source.HasValue == false)
                return null;
            
            switch (source.Value)
            {
                case 7L:
                    return Grund.Test;
                case 11L:
                    return Grund.AnotherTest;
                case 16L:
                    return Grund.AndAnotherOne;
                default:
                    throw new ArgumentOutOfRangeException(nameof(source), source, "message");
            }
        }
    }
`

If we now start a unittest to map a nullable long to the Enum-Value, we got the following exception:

Mapping types:
Nullable`1 -> Nullable`1
System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Nullable`1[[lGrund, assemblyName, Version=1.109.0.0, Culture=neutral, PublicKeyToken=null]]
   bei lambda_method(Closure , Nullable`1 , Nullable`1 , ResolutionContext )
   bei AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source)
   bei AutoMapper.Mapper.Map[TSource,TDestination](TSource source)

What am i doing wrong?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build. If that doesn't work out, make a gist that we can execute and see fail. This one is broken and is missing types.

**Comment by MO2k4** [comment]
With the MyGet Build it's working, when will this version be published? 

And why is there a broken version published in Nuget?

**Comment by jbogard** [comment]
Believe it or not, some packages on NuGet do contain bugs.

The next version contains breaking changes in the API so will be 6.0.

**Comment by MO2k4** [comment]
Sorry if my last comment sounded rude but i was not expecting such a bug because it was not a problem in previous versions

**Comment by jbogard** [comment]
Nullables are a HUGE source of pain, since GetType() lies to you. Since we
completely overhauled the execution engine from code-based to
expression-based, I expected some bugs to creep in.

But since the MyGet feed is up, it's easy to get the latest and greatest.
