### ISSUE TITLE
Broken Reference IMapperConfiguration in update 5.2.0

### ISSUE THREAD

**Issue by dooziiinc** [AutoMapper/AutoMapper#1964]
There are several instances of IMapperConfiguration being referenced in Automapper.cs that are broken after the NuGet update to version 5.2.  

I looked through the source and do not see any reference this this interface.  How can this be fixed?

public delegate void AutoMapperConfiguration(**IMapperConfiguration** configuration, IMappingExpression<T1, T2> configT1ToT2, IMappingExpression<T2, T1> configT2ToT1);

public AutoMapping(Action<**IMapperConfiguration**> config) {
			this.MapperConfiguration = new MapperConfiguration(cfg => {
				if (config != null) {
					config(cfg);
				}
			});
			_mapper = new Lazy<IMapper>(this.CreateMapper);
		}

Thanks

**Comment by lbargaoanu** [comment]
The interface was renamed to IMapperConfigurationExpression.
