### ISSUE TITLE
Mapping Nested Collections modifies source

### ISSUE THREAD

**Issue by gdubz** [AutoMapper/AutoMapper#1966]
I have nested collections such that an Exam has ICollection<Question> and Question has ICollection<Standard>. There are mappings defined at each level such that ExamModel has ICollection<QuestionModel> and QuestionModel has ICollection<StandardModel>. The standard to standard model mapping works just fine. Mapping an individual question to QuestionModel works, but when mapping Exam to ExamModel the deeply nested *source* records are modified. If the nested collections are not supported, that's fine. I could live with missing data on the destination. I'm at a total loss for why the source records would be modified.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by gdubz** [comment]
I made a simplified version of the model and was not able to reproduce the problem. I'll post back if I can get a bite size repo together which reproduces the issue.
