### ISSUE TITLE
Project().To<T>() failed when mapping to List

### ISSUE THREAD

**Issue by sky3913** [AutoMapper/AutoMapper#1968]
I'm using AutoMapper 3.3.1 to map entity to dto:

```
return context.Orders
	.Include(o => o.OrderItems.Select(oi => oi.Item))
	.Where(o => o.OrderID == orderID)
	.Project().To<OrderDTO>()
	.SingleOrDefault();
```

and then I got the following error:

> LINQ to Entities does not recognize the method 
> 'System.Collections.Generic.List`1[DTO.OrderItemDTO] 
> ToList[OrderItemDTO](System.Collections.Generic.IEnumerable`1[DTO.OrderItemDTO])' method, 
> and this method cannot be translated into a store expression

the mapper configuration is:

```
Mapper.CreateMap<Order, OrderDTO>();
Mapper.CreateMap<OrderItem, OrderItemDTO>();
```

and here is the dto classes:
```
public class OrderDTO
{
	public Guid OrderID { get; set; }
	public DateTime OrderDate { get; set; }
	public List<OrderItemDTO> OrderItems
}

public class OrderItemDTO
{
	public string ItemName { get; set; }
	public int Quantity { get; set; }
	public decimal Price { get; set; }
}
```

it's failed when map to List<OrderItemDTO> because if I change to IEnumerable<OrderItemDTO>, it works. How to solve this?

**Comment by lbargaoanu** [comment]
Include is not needed here.

**Comment by sky3913** [comment]
Why it's not needed? What about if lazy loading is turned off?
With or without Include I still get the same error, could you help?

**Comment by lbargaoanu** [comment]
ProjectTo will fetch everything by default.

**Comment by lbargaoanu** [comment]
Anyway, your version is pretty old, so even if there is smth wrong, there is nothing we can do about it. It works with the latest. You can try IList, upgrade EF or AM.

**Comment by TylerCarlson1** [comment]
Another thing is what version of EF are you using?  Latest version is 6.1.3 and that fixes little problems like this.  If you are using EF.Core then you are going to have to wait for them to fix these things.

**Comment by sky3913** [comment]
I'm still using AutoMapper 3.3.1 and EF 5. 
Yeah I've tried using the new AutoMapper and Entity Framework, and it works. 
Seems that a lot of code must be changed, because some of AutoMapper's function has been deprecated.
Anyway, thanks for the help
