### ISSUE TITLE
Accessing mapper in profile

### ISSUE THREAD

**Issue by fleed** [AutoMapper/AutoMapper#1969]
How can I access the mapper in a custom `Profile`?

I'm configuring mapping for a class in a custom `Profile` using the `CreateMap` method. This class has a collection, and I'd need to map the items in the collection. I'd use `Linq Select(i => mapper.Map(i))`, but how can I access the `Mapper` or the configuration?

Is this the way to do it or am I missing the correct way to use a `Profile`?

Thank you

**Comment by TylerCarlson1** [comment]
Just map the collections properties to each other (No real reason to use Select).  AutoMapper will handle updating the collections for you.

**Comment by fleed** [comment]
Thank you for explanation
