### ISSUE TITLE
How To Initialize AutoMapper In Service Fabric WebAPI OWIN Selfhost

### ISSUE THREAD

**Issue by krishnandusarkar** [AutoMapper/AutoMapper#1970]
I have referred https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-webapi to selfhost WebAPI on Stateless Service Fabric.

But now I'm having a hardtime initializing AutoMapper. I have tried several options, but in the end when I call WebAPI, I always get the issue...

`"Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.",`

Any ideas or help would be really appriciated.

**Comment by jbogard** [comment]
Startup.cs is the place to put it.

**Comment by krishnandusarkar** [comment]
Well that's what I tried first @jbogard, but unfortunately it seems that on remote service calls to other services under Service Fabric it looses it's configuration due to it being Stateless.

Finally I was able to succeed by calling the initalizer on each Service constructor / Program.cs

**Comment by jbogard** [comment]
Sounds like I need to add some documentation!
