### ISSUE TITLE
AutoMapper

### ISSUE THREAD

**Issue by EliPedro** [AutoMapper/AutoMapper#1971]
An exception of type 'System.IO.FileLoadException' occurred in AutoMapper.dll but was not handled in user code

Additional information: Não foi possível carregar arquivo ou assembly 'AutoMapper, Version=5.2.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' ou uma de suas dependências. A definição do manifesto do assembly localizado não corresponde à referência do assembly. (Exceção de HRESULT: 0x80131040)

**Comment by lbargaoanu** [comment]
This is a problem in your app, not in AM.
