### ISSUE TITLE
Collection is read-only exception when try to map to ICollection with fixed size

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper#1973]
Try to set values on auto-initialized ICollection throws the following exception

Is this a correct behavior to not been able to update the properties that is ICollection but have a fixed size?

```
Error mapping types.

Mapping types:
B -> A
CollectionMappingTest+B -> CollectionMappingTest+A

Type Map configuration:
B -> A
CollectionMappingTest+B -> CollectionMappingTest+A

Property:
Items
Collection is read-only.
```

Following test code is used
```
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Xunit;

    public class CollectionMappingTest
    {
        [Fact]
        public void ReadOnlyCollectionTest()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<A, B>()
                   .ReverseMap();
                cfg.CreateMap<AA, BB>()
                   .ReverseMap();
            });

            var itemA = new A
            {
                Items = new []{ new AA { Value = "1" }, new AA { Value = "2" }, new AA { Value = "3" } }
            };
            Assert.Equal(3, itemA.Items.Count);
            Assert.True(itemA.Items is Array);

            var itemB = Mapper.Instance.Map<B>(itemA);
            Assert.Equal(3, itemB.Items.Count);

            Assert.False(itemB.Items is Array);
            itemB.Items.Remove(itemB.Items.Last());

            Assert.Equal(2, itemB.Items.Count);

            Mapper.Instance.Map(itemB, itemA);
            Assert.Equal(2, itemA.Items.Count);
        }
        public class A
        {
            public ICollection<AA> Items { get; set; }
        }
        public class B
        {
            public ICollection<BB> Items { get; set; }
        }
        public class AA
        {
            public string Value { get; set; }
        }
        public class BB
        {
            public string Value { get; set; }
        }
    }
```
AutoMapper version: 5.2.0

-----

In AutoMapper 4 I was using an own https://github.com/AutoMapper/AutoMapper/blob/v4.2.1/src/AutoMapper/Mappers/CollectionMapper.cs that make an override of the inner `EnumerableMapper<TCollection, TElement>` implementation with the following snippet to solve this.
```
            protected override object GetOrCreateDestinationObject(ResolutionContext context, Type destElementType, int sourceLength)
            {
                // If the source is an array, assume we can add to it...
                if (context.DestinationValue is Array)
                    return CreateDestinationObjectBase(destElementType, sourceLength);

                return base.GetOrCreateDestinationObject(context, destElementType, sourceLength);
            }
```

Is there any workaround like this in the new expression world of AutoMapper 5?

**Comment by lbargaoanu** [comment]
You can type A.Items as array or use

    cfg.CreateMap<A, B>().ReverseMap().ForMember(d=>d.Items, o=>o.Ignore()).AfterMap((s, d)=>d.Items=Mapper.Map<AA[]>(s.Items));

**Comment by lbargaoanu** [comment]
I'm not sure this is really a bug. When we build the execution plan, we only know it's a collection, and we're supposed to clear collections before mapping. It would be easy to check and simply not clear it, but that would be weird. I don't see an easy and corect way out.

**Comment by Tasteful** [comment]
@lbargaoanu  `AfterMap` is working but I should like a more generic way to solve it to not need to specify all the collection mappings like that.

I have not debug the collection mapping code to understand what that make it decide if it can use the current destination property-value or of that is null and need to be created before items can be cleared/added. If it is the https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Mappers/CollectionMapper.cs#L35 that need to be changes to not use the `passedDestination` if that is an `Array` i can made my own version pretty easy and include in my project.

**Comment by lbargaoanu** [comment]
Actually, not that mapper is really the problem. The array mapper should be used here, but it isn't because of ICollection. You can try a map or on object mapper, but then I'm not sure you need AM anymore.

**Comment by Tasteful** [comment]
Both the `ArrayMapper` and `CollectionMapper` is only verifying the defined type on the property, in this case is `ICollection<AA>` that matches for the `CollectionMapper`. 

The actual type of the created instance is `AA[]`. If `IObjectMapper.IsMatch` was verifying the actual instance type also and not only the defined type the `ArrayMapper` should have been used.

**Comment by lbargaoanu** [comment]
The whole idea is to build the mapping plan beforehand, so no runtime types for you :) You expect the resulting array to have two items, from the source, so it must be a new array. Maybe, as you've mentioned, not using the destination is the way out. An option DoNotUseDestination value would be an explicit way to do it.

**Comment by Tasteful** [comment]
- `.ForMember(d => d.Items, m => m.DoNotUseDestinationValue())` is not working
- `.ForMember(d => d.Items, m => m.UseValue((ICollection<AA>)null))` is not working
I populating an already existing item with changes from another. Mapping from `itemA -> itemB` is working as it should, the error will come when I mapp the changed data back.

it's working if `itemA.Items = null;` is executed before `Mapper.Instance.Map(itemB, itemA);` but that is not either a working solution.

I like the idea about having the mapping plan created during startup because we got better performance (that's the reason I'm upgrading) but in this case the typed mapping is saying that the mapping should handle the collection with Add/Remove items (it expect them to be there) but they are actually not there. 

If we see the `ReadOnlyCollectionMapper` that one is creating a new collection to insert that data into and that is probably a way to solve it in this case also. I will deep down in the code and see if I can understand where and how to create a new collection when it is needed.

**Comment by lbargaoanu** [comment]
DoNotUseDestinationValue was removed because it doesn't do anything.

**Comment by Tasteful** [comment]
I was able to update the collection mapping (see pull request) with the extra check if the destination type is Array. Make a review of the PR and decide if that should be tracked as a bug or not.

**Comment by lbargaoanu** [comment]
You can use MapAtRuntime (it's in the MyGet build) for that member and runtime types will be used.
