### ISSUE TITLE
AfterMap action for a collection mapping

### ISSUE THREAD

**Issue by KasunKoswattha** [AutoMapper/AutoMapper#1975]
Im trying to do a runtime aftermap action for a collection mapping. 

`  var test = Mapper.Map<List<someObjectType1>, List<someObjectType2>>(sourceCollection, opt =>
                {
                  opt.AfterMap((src, dest) =>
                });`

But the problem I'm facing dest is an object type. 

How can I do this for a collection? This method works fine If I have a single object.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by KasunKoswattha** [comment]
Is this a Pre-Release version? Is my problem above a known bug?

**Comment by jbogard** [comment]
It's the nightly version. This might already be fixed. Trying the nightly
version would confirm this.

**Comment by KasunKoswattha** [comment]
This is a production change, Im not allowed to change the package to a nightly version. Could you please let me know if this is a known bug?

**Comment by jbogard** [comment]
I don't know if it's a bug, I can't reproduce, this works for me just fine:

```
var values = Mapper.Map<List<Source>, List<Dest>>(new List<Source> { new Source
{
    Value = 5
}}, opt => opt.AfterMap((src, dest) => dest[0].Value += 10));
```

The source/destination parameters are the correct type. Maybe a little bigger gist so that we can execute and reproduce?
