### ISSUE TITLE
Error mapping Expression<Func<T,bool>> with inheritance

### ISSUE THREAD

**Issue by MiguelRemirez** [AutoMapper/AutoMapper#1978]
Say I have two types and these inherit from base. In the mapper i map the base and the type:

This is the DTOs

```
public class SourceBase : ISource
{
    public int Field01 { get; set; }

    public int Field02 { get; set; }

    public string Global01 { get; set; }
}

public  class TargetBase : ITarget
{

    public int Field01 { get; set; }

    public int Field02 { get; set; }

    public string Global01 { get; set; }
}

public class Source04 : SourceBase
{

    public string OnlySource04 { get; set; }

}

public class Target04 : TargetBase
{

    public bool Is04 { get; set; }

    public string OnlySource04 { get; set; }
}
```

This is the mapper conf.
In the mapper, I map the objects.

public class GlobalMapper : IGlobalMapper
{

    private readonly MapperConfiguration configurationMapper = null;
    private readonly IMapper mapper = null;

    public GlobalMapper()
    {
        configurationMapper = new MapperConfiguration(cfg =>
        {
            cfg.CreateMissingTypeMaps = false;

            MapEntities(ref cfg);
        });

        mapper = configurationMapper.CreateMapper();

        // Func<Source01, Target01> mappingFunc = Mapper.CreateMapExpression(Source01, Target01).Compile();

    }

    public void AssertConfigurationIsValid()
    {
        configurationMapper.AssertConfigurationIsValid();

    }

    public IConfigurationProvider GetConfigurationProvider()
    {
        return configurationMapper;
    }

    public T Map<T>(object source)
    {
        if (source == null)
        {
            return default(T);
        }

        return mapper.Map<T>(source);
    }

    private void MapEntities(ref IMapperConfigurationExpression configuration)
    {
        configuration.CreateMap<ISource, ITarget>()
        .ConstructUsing((ISource source) =>
        {
            if (source is Source01) return mapper.Map<Target01>(source);
            else if (source is Source02) return mapper.Map<Target02>(source);
            else if (source is Source04) return mapper.Map<Target04>(source);

            throw new Exception();
        });

        configuration.CreateMap<ITarget, ISource>()
            .ConstructUsing((ITarget target) =>
            {
                if (target is Target01) return mapper.Map<Source01>(target);
                else if (target is Target02) return mapper.Map<Source02>(target);
                else if (target is Target04) return mapper.Map<Source04>(target);

                throw new Exception();
            });

        configuration.CreateMap<SourceBase, TargetBase>()
            .ForMember(c => c.Field01, m => m.MapFrom(s => s.Field01))
            .ForMember(c => c.Field02, m => m.MapFrom(s => s.Field02))
            .ForMember(c => c.Global01, m => m.MapFrom(s => s.Global01))
            ;

        configuration.CreateMap<Source04, Target04>()
            .IncludeBase<SourceBase, TargetBase>()
            .ForMember(o => o.OnlySource04, m => m.MapFrom(s => s.OnlySource04));
            ;
    }
}

But when i try map the  Expression<Func<Source04, bool>> the mapper resolved the Expression but no correctly, the type of expression resolved is rigth but the member still is Source04. And when use the expression throw this exception:

{"Reference to variable 'x' of type 'System.Object' from scope '', but not defined"}

For examble this test throw exception in  `Assert.AreEqual(1, result02.Count()); `line

 [TestMethod]
        public void Expressions_Source04_To_Target04()
        {
            int iterations = 10;
            List<Source04> sources = new List<Source04>();
            List<Target04> targets = new List<Target04>();

            for (int i = 0; i < iterations; i++)
            {
                sources.Add(new Source04() { Field01 = i, Field02 = i });
                targets.Add(new Target04() { Field01 = i, Field02 = i });
            }

            IConfigurationProvider provider = mapper.GetConfigurationProvider();
            IMapper currentMapper = provider.CreateMapper();

            Expression<Func<object, bool>> whereExpressionSource = x => ((Source04)x).Field01 == 2;
            Expression<Func<Target04, bool>> whereExpressionTarget = currentMapper.Map<Expression<Func<Target04, bool>>>(whereExpressionSource);
            //Expression<Func<Target01, bool>> whereExpressionTargetExt = whereExpressionSource.ConvertExpression<Source01, Target01>();

            var result01 = sources.AsQueryable().Where(whereExpressionSource);
            var result02 = targets.AsQueryable().Where(whereExpressionTarget);
            //            var result03 = targets.AsQueryable().Where(whereExpressionTargetExt);

            Assert.AreEqual(1, result01.Count());
            Assert.AreEqual(1, result02.Count());
            //          Assert.AreEqual(1, result03.Count());
        }

I think that the map have a problem with the Herency in this case, could be possible?

**Comment by TylerCarlson1** [comment]
Casting objects hasn't ever been tested in Expression Translation.

@BlaiseD does #1916 handle casting translation?

**Comment by BlaiseD** [comment]
That should **not** work.  According to this: `Expression<Func<object, bool>> whereExpressionSource = x => ((Source04)x).Field01 == 2;` the parameter x is of type object i.e. object is not mapped to Target04.

**Comment by MiguelRemirez** [comment]
sorry, i copied other test.

This is the test:

     [TestMethod]
        public void Expressions_Source04_To_Target04()
        {
            int iterations = 10;
            List<Source04> sources = new List<Source04>();
            List<Target04> targets = new List<Target04>();

            for (int i = 0; i < iterations; i++)
            {
                sources.Add(new Source04() { Field01 = i, Field02 = i });
                targets.Add(new Target04() { Field01 = i, Field02 = i });
            }

            IConfigurationProvider provider = mapper.GetConfigurationProvider();
            IMapper currentMapper = provider.CreateMapper();

            Expression<Func<Source04, bool>> whereExpressionSource = x => x.Field01 == 2;
            Expression<Func<Target04, bool>> whereExpressionTarget = currentMapper.Map<Expression<Func<Target04, bool>>>(whereExpressionSource);
          
            var result01 = sources.AsQueryable().Where(whereExpressionSource);
            var result02 = targets.AsQueryable().Where(whereExpressionTarget);
          

            Assert.AreEqual(1, result01.Count());
            Assert.AreEqual(1, result02.Count());
          
        }

**Comment by BlaiseD** [comment]
Yes #1916 fixes the problem described here: "**the type of expression resolved is rigth but the member still is Source04**".

**Comment by TylerCarlson1** [comment]
#1916 got merged.

@MiguelRemirez Can you try the [MyGet Build](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-build) and see if that solves your issue?
