### ISSUE TITLE
Queryable-Extensions - Null Object Reference

### ISSUE THREAD

**Issue by cjrogala** [AutoMapper/AutoMapper#1979]
**Version: 5.2.0**
When attempting to map a view model to an entity, I noticed that the property in the entity is not being instantiated.

Reference this page's example: 
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions 

**First example (NHibernate or Entity Framework with AutoMapper)**
I have EF for my ORM, and my example is almost identical to the one here, where my view model has a property like Item (string) that needs to be mapped to the Item.Name in the OrderLine object.

In my profile, I have something that is identical to this (minus the actual property names):

`.ForMember(dto => dto.Item, conf => conf.MapFrom(ol => ol.Item.Name)));`

While writing Unit Tests to make sure everything is mapping correctly, I noticed the Item property is not set to an instance of an object.  The below line fails in the test:

`entity.Item.Should().NotBeNull();`

The structure of the entity class is the same as the example where there isn't a constructor that instantiates the Item object.

Unfortunately, I am unable to share the exact code.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by cjrogala** [comment]
@lbargaoanu - I attempted to replicate, but my models are a little more complex.  When I was replicating, I noticed I was using ReverseMap which looks like it is causing the issue.  Basically, I am mapping from data entity > business model > view model.  The business layer contains a model that is mapped to the Item entity.  This allowed the ReverseMap to work, but hide this other issue.  

Long story short, please mark this as not an issue.  My apologies.
