### ISSUE TITLE
Error when flattening whilst mapping in Automapper 4.2.1

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1980]
I have a DTO class which has 2 more properties and than the model class. These 2 properties are being mapped from properties of a nested class in the model.

So the config is:
`
cfg.CreateMap<model, dto>()
  .ForMember(dest => dest.Property1, opt => opt.MapFrom(src => src.Nested.Property1))
  .ForMember(dest => dest.Property2, opt => opt.MapFrom(src => src.Nested.Property2))
  .ReverseMap();
`

However, I'm getting the error:

> Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type

Why is Automapper not mapping the properties correctly?

**Comment by lbargaoanu** [comment]
Try it without ReverseMap.

**Comment by cryo75** [comment]
It still doesn't work, however now I'm getting a weirder error. Still, I need to use ReverseMap

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by cryo75** [comment]
[Gist](https://gist.github.com/cryo75/ea78d9251b9159137a5fd038a83b160b)

**Comment by lbargaoanu** [comment]
Apparently this was a bug in 4.2.1. It works now.
