### ISSUE TITLE
Move all documentation from the wiki to readthedocs.io

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1982]
No one reads the wiki and it's hard to organize.

**Comment by TylerCarlson1** [comment]
Having branch/tag based documentation would be amazing, especially for pre-releases.  Not sure how/whom would re-organize it to be better than what it is now.  Although a change in venue could be a way to get us more motivated to fix things

**Comment by stehlikio** [comment]
I can probably take a stab at this. 

Is there anything specific we're looking for when it comes to a new organization strategy or content? I was thinking that I could just move the documents over from the wiki as a phase one.

**Comment by jbogard** [comment]
That sounds like a brilliant phase one.

**Comment by KoditkarVedant** [comment]
@jbogard @stehlikio I would also love to work on this.
