### ISSUE TITLE
Couldnt find ResolutionResult 

### ISSUE THREAD

**Issue by dewelloper** [AutoMapper/AutoMapper#1983]
I have used AutoMapper from Nuget 5.2.0 version in my projects.
I could not find **ResolutionResult** object anywhere for**IValueResolver** implementation.
Is the nuget version is different from this one?.

appericiate all helps
thanks

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide
