### ISSUE TITLE
Consolidate nullable logic out of IObjectMappers

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1987]
We have nullable logic all over the place. Both in terms of checking types and doing mapping junk. I want to move the nullable stuff that's junking up our IObjectMappers out.

Here's the basic logic for two values:

Source | Dest | Src Value | Dest Value
--------|-------|-------|------
T|U?|T|Map(T, U)
T|U?|default(T)|Map(T, U)
T?|U|T|Map(T, U)
T?|U|null|default(U)
T?|U?|T|Map(T, U)
T?|U?|null|default(U?)
V|U|V|Map(V, U)
V|U|null|default(U)
V|U?|V|Map(V, U)
V|U?|null|default(U?)

where T: struct, V: class

I think we could wrap this logic in one place for top-level maps and member-level maps.

**Comment by TylerCarlson1** [comment]
Don't forget about Expression Translation (which is called by an IObjectMapper, but I think seperate) and ProjectTo making queries.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/pull/780#issuecomment-120387333 :)

**Comment by jbogard** [comment]
Lol well we do have that NullableSource mapper. But tbqh I didn't want to
add any more IObjectMappers. The order dependency of those is already
confusing!

Looking over the code though this would require a broader refactoring
around the expression building. The TypeMapPlanBuilder class already has
too much exposed publicly (and public static).

**Comment by monaFarshidi** [comment]
Hi every one
I have a strange problem in my web App. I used Mapper for mapped class to each other, But sometimes I get a error and after IIS stop and start every thing work fine.
this happens cause of GetVersionID that refers to primary key in GetVersion property that is NotNull.
I use code like that :
Mapper.CreateMap<GetVersion, JsonGetVersion>();

Can somebody help me ????

**Comment by jbogard** [comment]
Generally you don't ask unrelated questions on issues closed months ago. If you have a new issue, create one.
