### ISSUE TITLE
Mapping Expression of Type X to Type T and finding by predicate.

### ISSUE THREAD

**Issue by JeanBrand** [AutoMapper/AutoMapper#1989]
We have a situation where we need to map from one type of Expression to another, which we can do, using:

cfg.CreateMap<Expression<Func<X, bool>>, Expression<Func<T, bool>>>().ReverseMap();

But, when we try to run a predicate on a Enum value, we get the following exception:

Outer Exception: An exception of type 'AutoMapper.AutoMapperMappingException' occurred in AutoMapper.dll but was not handled in user code

Inner: Rewriting child expression from type 'X' to type 'System.Int32' is not allowed, because it would change the meaning of the operation. If this is intentional, override 'VisitUnary' and change it to allow this rewrite.

Could you please shed some light on this?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by JeanBrand** [comment]
I tried that, but the issue still persists.

**Comment by BlaiseD** [comment]
@JeanBrand Can you post the smallest possible sample which can reproduce the error?
