### ISSUE TITLE
Projecting string to enum

### ISSUE THREAD

**Issue by FilipFilipov** [AutoMapper/AutoMapper#1994]
What is the correct way to do this? Normally you'd use `Enum.Parse()`, but with `ProjectTo` EntityFramework will complain that it can't translate the method to sql.

**Comment by lbargaoanu** [comment]
ProjectTo relies on EF doing the work. You can use Map instead.

**Comment by lbargaoanu** [comment]
There are ways to work around it that you can try. See https://blogs.msdn.microsoft.com/dotnet/2017/02/28/the-week-in-net-on-net-with-eric-mellino-happy-birthday-from-scott-hunter-ozcode/. Search for NeinLinq. They might work with ProjectTo.
