### ISSUE TITLE
Parameter-based conditional mapping

### ISSUE THREAD

**Issue by FilipFilipov** [AutoMapper/AutoMapper#1995]
I have an entity that I sometimes want mapped with and sometimes without its related entities. Is there a way to do this by passing a parameter to `ProjectTo`? What kind of mapping rules would that require?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#explicit-expansion
