### ISSUE TITLE
ProjectTo with parameter not setting variables

### ISSUE THREAD

**Issue by noah-potter** [AutoMapper/AutoMapper#1996]
This was working in 4.2.1 but doesn't seem to be working in 5.2.0

Here's an example of what I'm attempting to do

```
Mapper.Initialize(cfg =>
{
	MyDatabaseContext db = null;

	cfg.CreateMap<my_model, MyModelDTO>()
		.ForMember(dest => dest.filtered_child_models, opt => opt.MapFrom(src => <filter out child models using db connection>));
}

MyDatabaseContext db = new MyDatabaseContext();

db.my_models.ProjectTo<MyModelDTO>(new { db = db });
```

But I'm getting the exception `Object reference not set to an instance of an object` when trying to use `db` in `CreateMap`. 

The only difference now is that I upgrade to 5.2.0 and am using `cfg.CreateMap` instead of `Mapper.CreateMap`

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by jbogard** [comment]
That `<>` part is the most important part. You just Yada-yada-yada'd a GH issue

**Comment by noah-potter** [comment]
Okay let me mess around with it a bit more and see if I can come up with more details and a repo.

**Comment by noah-potter** [comment]
So I narrowed it down.

This occurs when you create a variable outside `Mapper.Initialize` and use it inside `ForMember`

Here's a repo: https://github.com/noah-potter/AutoMapperOutsideValueSet
The last commit contains the relevant code

Running the project and navigating to /api/values will return the model with `setInside` as nil
Commenting out the second `ForMember` will then correctly return the model with `setInside` as "inside"

**Comment by jbogard** [comment]
Well the "inside" one is the correct way to do it. You're just declaring a variable to capture a closure strictly as a marker. The value should ONLY be a default value (null for any reference type). We scan these and replace but they have to look very specific in order to do so. Basically we're scanning for captured closures in the expression tree and replacing them with a value at projection time.

In your first example, that context should be set to null and never accessed directly again.

**Comment by noah-potter** [comment]
Okay. I was just surprised that referencing a variable defined outside the closure would cause all variables defined inside the closure to always be null. Since this changed from 4.2.1 maybe this should be noted in the migration guide?

**Comment by jbogard** [comment]
Did not know that it had changed - we fixed a bug is all I can remember.

It's a wiki though, feel free to fix it!
