### ISSUE TITLE
How to mock IMapper in Test Project using Moq

### ISSUE THREAD

**Issue by manojkgarg** [AutoMapper/AutoMapper#1998]
I am using MStest Project. Please advise how i can mock IMapper  in test project.

----

 public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateMap<entity, EntityModel>()
                .ForMember(m => m.GroupName, opt => opt.MapFrom(entity => entity.group.name))
                 .ForMember(m => m.Url, opt => opt.ResolveUsing<EntityUrlResolver>());
        }
    }
---
controller constructor
---
 public EntitiesController(IEntityRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
-----
Startup.cs
--
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<JMTEntities>(_ => new JMTEntities());

            AddRepositories(services);

            // Add framework services.
            services.AddMvc();
            services.AddAutoMapper();
        }

**Comment by lbargaoanu** [comment]
This sounds like a Mock question.
