### ISSUE TITLE
Heavy memory usage and huge performance hit results in OutOfMemoryException

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#2001]
I have about 150 mappings which I try to keep 1:1 between model and dto and using `MemberList.Destination` on most. Some are custom mappings and on nearly all mappings I use `ReverseMap`.

I have an object such as:

```
public class UserModel
{
        public UserModel()
        {
            this.Areas= new List<AreaModel>();
            this.Departments = new List<UserDepartmentModel>();
        }

        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int? UserGroupId { get; set; }
        public string Name { get; set; }
        public string Position{ get; set; }
        public bool IsActive { get; set; }

        public virtual CompanyModel Company { get; set; }
        public virtual UserGroupModel UserGroup { get; set; }
        public virtual ICollection<AreaModel> Areas { get; set; }
        public virtual ICollection<UserDepartmentModel> Departments { get; set; }
}

public class UserDto
{
        public UserDto()
        {
            this.Areas= new List<AreaDto>();
            this.Departments = new List<UserDepartmentDto>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Position{ get; set; }
        public bool IsActive { get; set; }

        public CompanyDto Company { get; set; }
        public UserGroupDto UserGroup { get; set; }
        public ICollection<AreaDto> Areas { get; set; }
        public ICollection<UserDepartmentDto> Departments { get; set; }
}
```
The other classes can be quite complex. For example, `UserGroup` has 3 primitive properties and 3 collections, whilst `Company` has many different primitive properties and around 10 collections. All collections are of further models.

The mapping for the above and other classes is simply:

`cfg.CreateMap<UserModel, UserDto>(MemberList.Destination).ReverseMap();`

For the `UserDepartment` model->dto mapping I have:

```
cfg.CreateMap<UserDepartmentModel, UserDepartmentDto>()
    .ForMember(dto => dto.DepartmentId, option => option.MapFrom(model => model.Department.Id))
    .ForMember(dto => dto.DepartmentName, option => option.MapFrom(model => model.Department.Name))
    .ForMember(dto => dto.DepartmentName, option => option.Ignore())
    .ReverseMap()
    .ForMember(model => model.UserId, option => option.Ignore())
    .ForMember(model => model.DepartmentId, option => option.Ignore())
    .ForMember(model => model.Department, option => option.MapFrom(dto => new DepartmentModel { Id = dto.DepartmentId, Name = dto.DepartmentName }));
```

Problems:
When mapping a user model to dto, the mapping just throws `OutOfMemoryException` after a while (I see memory usage rise to over 2GB before it crashes).

When mapping individually and I create a user dto manually, each mapping takes no less than 20s and the first mapping doubles memory usage. Once memory usage doubles, it stays the same for the remaining mappings. Doing so causes no `OutOfMemoryException`. This is however not a solution.

All of the above mappings work fine in 4.2.1 and there is no memory usage or performance hit. It's actually very fast, as expected.

Note: I'm testing in debug mode.

At first I thought I might have circular references so I checked my dto classes and I don't have any.

As I cannot pinpoint the location of the problem and it would be near to impossible to create a gist with over 20 models and corresponding dto's, I need suggestions on how and what to debug this problem as I need to upgrade to the latest version (if the problems above are solved).

**Comment by jbogard** [comment]
Only 20 models??? That can't be right. So I profiled with a real world app against version 5.2.0:

```
var timer = new Stopwatch();

timer.Start();
Mapper.Initialize(cfg =>
{
    cfg.AddProfiles(typeof(Entity<>), typeof(Startup));
});
timer.Stop();

Console.WriteLine($"Total time to configure: {timer.Elapsed}");
Console.WriteLine($"Total # of maps: {Mapper.Configuration.GetAllTypeMaps().Length}");
```

And the timings I got:

```
Total time to configure: 00:00:02.1675867
Total # of maps: 235
```

So 2-ish seconds to configure 235 maps.

**Comment by jbogard** [comment]
One other thing - your map configurations look a bit weird. Redundant MapFrom, and then an Ignore.

**Comment by jbogard** [comment]
I pulled some more numbers, including the size of the expressions generated:

```
var timer = new Stopwatch();

timer.Start();
Mapper.Initialize(cfg =>
{
    cfg.AddProfiles(typeof(Entity<>), typeof(Startup));
});
timer.Stop();

Console.WriteLine($"Total time to configure: {timer.Elapsed}");
Console.WriteLine($"Total # of maps: {Mapper.Configuration.GetAllTypeMaps().Length}");

var expressions = Mapper.Configuration.GetAllTypeMaps().Select(tm => tm.MapExpression);

var counts = expressions.Select(expr =>
{
    var visitor = new NodeCountVisitor();
    visitor.Visit(expr);
    return visitor.NodeCount;
}).ToArray();

Console.WriteLine($"Expression size: {counts.Average()} (avg) {counts.OrderBy(x => x).Skip(counts.Length/2).First()} (med)");
```

thing that counts nodes:
```
private class NodeCountVisitor : ExpressionVisitor
{
    public int NodeCount { get; private set; }
    public override Expression Visit(Expression expression)
    {
        NodeCount++;

        return base.Visit(expression);
    }
}
```

And my totals:

```
Total time to configure: 00:00:02.3810227
Total # of maps: 235
Expression size: 536.48085106383 (avg) 387 (med)
```

Memory size is pretty negligible as far as I can see, around 40MB.

Would it be possible to create a .ZIP file that just has the models/DTOs in a console app or something?

**Comment by jbogard** [comment]
Just for fun I added to the mix compiling all mappings up front:

```
timer.Restart();
Mapper.Configuration.CompileMappings();
timer.Stop();
```

And the timings:

```
Total time to compile mappings: 00:00:01.1237748
```

**Comment by cryo75** [comment]
@jbogard The app has some more models than the mappings, ie. 150-170. I was referring to the 20 models as an approximate that are used for the particular mapping that's failing.

That redundant Ignore is because in 4.2.1 I get an exception that members are not mapped even though I'm using MapFrom. One of the reason that I need to upgrade to the latest version.

I will create a copy of my models and dto for this particular mapping and prepare a ZIP.

**Comment by cryo75** [comment]
Attached is a sample console app which I tried to keep true to the actual app. The actual app has much more models and mappings.

In this console app, the model->dto mapping takes about 1min to complete. In the actual app (asp.net), it runs out of control till I get `OutOfMemoryException`. I couldn't manage to replicate this same exception but at least it should be a starting point in checking why it takes so long to map.

[TestAutomapper.zip](https://github.com/AutoMapper/AutoMapper/files/844006/TestAutomapper.zip)

**Comment by jbogard** [comment]
OK so I ran some tests. First, vanilla without any config changes:

```
Total time to configure: 00:00:00.3950619
Total # of maps: 100
TestAutomapper.Dto.User
Total time to map one thing: 00:00:29.9563273
```

Super fast to configure (I removed the AssertConfigurationIsValid), but the first map took 30 seconds.

Then, I compiled all mappings before the map:

```
Total time to configure: 00:00:00.4406502
Total # of maps: 100
Expression size: 4727.19 (avg) 127722 (max) 273 (med)
Total time to compile mappings: 00:00:25.0108151
TestAutomapper.Dto.User
Total time to map one thing: 00:00:17.9386447
```

One thing to see is that your maps are HUUUUUUUGE, the expressions are very large, on average about 10x larger than the average size of my application and the max is huuuuuuuuge. I believe this is because my applications create single view models per view/API call, so it's not a 1:1 of DTO:Model. Instead it's 1:1 of View:DTO. So my DTOs are much smaller and much more targeted. 

SO. One last time, this time making all properties map at runtime. This means that I won't inline sub-mappings (collections and complex properties). With 6.0 alpha, I configure it like:

```
cfg.ForAllPropertyMaps(pm => true, (pm, m) => m.MapAtRuntime());
```

And well quite a bit better numbers:

```
Total time to configure: 00:00:00.3365277
Total # of maps: 100
Expression size: 530.45 (avg) 3829 (max) 282 (med)
Total time to compile mappings: 00:00:00.3831557
TestAutomapper.Dto.User
Total time to map one thing: 00:00:00.1420607
```

That's probably more the numbers that you're looking for.

In our tests, inlining the mappings were always significantly faster - but we didn't test with expressions of this size. Nowhere near, which is why we didn't see it.

**Comment by jbogard** [comment]
One last thing, in the second example, if I call Map again, it's much faster:

```
Total time to map one thing: 00:00:00.0002690
```

This is because the expression is compiled AND it's been executed and JIT'd.

**Comment by lbargaoanu** [comment]
Was this trip really necessary? :)

**Comment by jbogard** [comment]
@lbargaoanu I have a feeling that we might want to be smarter about inlining expressions at some point. Some of these expressions people generate are huuuuuuge it seems. I don't know what that would look like, though.

**Comment by lbargaoanu** [comment]
It's [possible](https://github.com/AutoMapper/AutoMapper/pull/1876#issuecomment-270897598), but it's more work.
