### ISSUE TITLE
Error after upgrade to AutoMapper 5

### ISSUE THREAD

**Issue by TMaga80** [AutoMapper/AutoMapper#2002]
I just updated to AutoMapper v5 from v4 and managed to update most of most of my methods except this one involving Lists. Herewith the error message:
**

> 'Wcf.EmployeeToUserPermissionCollectionConverter' does not implement interface member AutoMapper.ITypeConverter<System.Collections.Generic.IEnumerable<Common.Entities.Employee>, System.Collections.Generic.IEnumerable<Common.Entities.UserPermission>>.Convert(System.Collections.Generic.IEnumerable<Common.Entities.Employee>, System.Collections.Generic.IEnumerable<Common.Entities.UserPermission>, AutoMapper.ResolutionContext)'

**

This is the original code from v4 that was working:

```
internal class EmployeeToUserPermissionCollectionConverter : ITypeConverter<IEnumerable<Employee>, IEnumerable<UserPermission>>
 {
 
     public IEnumerable<UserPermission> Convert(ResolutionContext context)
     {
         IEnumerable<Employee> source = (IEnumerable<Employee>)context.SourceValue;
         IList<UserPermission> destination = new List<UserPermission>();
         foreach (Employee emp in source)
         {
             foreach (UserLogin item in emp.Logins)
             {
                 User user = new User();
                 user.Id = emp.Id;
                 user.Name = emp.Code;
                 user.FullName = emp.Name;
                 user.Username = item.Username;
                 user.IsPersonalAccount = item.IsPersonalAccount;
                 destination.Add(new UserPermission(user, emp.Roles.Select(x => x.Role.Name).ToList()));
             }
         }
         return destination;
     }
 }
```

And this is teh code in v5 that's causing issues:

```
internal class EmployeeToUserPermissionCollectionConverter : ITypeConverter<IEnumerable<Employee>, IEnumerable<UserPermission>>
 {
     public IEnumerable<UserPermission> Convert(IEnumerable<Employee> source, IList<UserPermission> destination, ResolutionContext context)
     {
         foreach (Employee emp in source)
         {
             foreach (UserLogin item in emp.Logins)
             {
                 User user = new User();
                 user.Id = emp.Id;
                 user.Name = emp.Code;
                 user.FullName = emp.Name;
                 user.Username = item.Username;
                 user.IsPersonalAccount = item.IsPersonalAccount;
                 destination.Add(new UserPermission(user, emp.Roles.Select(x => x.Role.Name).ToList()));
             }
         }
         return destination;
     }
 }

```

Please can you point me to how to implement the same in v5, many thanks

**Comment by lbargaoanu** [comment]
Replace ```IList<UserPermission>``` with ```IEnumerable<UserPermission>.```

**Comment by lbargaoanu** [comment]
@jbogard This is caused by ITypeConverter being contravariant in TSource. I think we should drop that.

**Comment by jbogard** [comment]
I don't think this will work anyway - the first converter creates a new list, the second one takes it in. In any case, your method needs to implement the interface correctly, using IEnumerable and not IList - kinda surprised this compiles in the first place.

**Comment by TMaga80** [comment]
Thanks @lbargaoanu, @jbogard this is the final code that works on v5:

**Comment by TMaga80** [comment]
The upgrade has improved my queries by about 60% 👍
