### ISSUE TITLE
Missing map created when mapping to inherited class object

### ISSUE THREAD

**Issue by rmaziarka** [AutoMapper/AutoMapper#2004]
Hi guys,

I upgraded Automapper to version 5 and had to remove DynamicMaps in favor of create missing type maps in runtime. But it lead me to strange behaviour with mapping to objects which are from derived class.

I created two gists: first [with CreateMissingTypeMaps set](https://gist.github.com/rmaziarka/cb64757fcdfc3f341336bf0fe6767895) and second [without CreateMissingTypeMaps set](https://gist.github.com/rmaziarka/5527c959e698ebcf32a4baacb35c4de4). In first case Automapper creates map because it does not contains map from Source to SpecificDestination. In second case Automapper magically finds map and maps value.

In my opinion it should either use existing map in first case or throw exception in second case. Right now the result is unpredictable and pushed me to really hard debugging problem. In my case it wasn't so obvious because i use Entity Framework proxies and these derived objects were created in the fly.

What do you think? I can try to fix it if you decide it's a bug.

**Comment by jbogard** [comment]
My first instinct is to say - don't use CreateMissingTypeMaps unless you've got types you don't know until runtime. If you know all your types (EF proxies don't count - we handle those automatically), you should call CreateMap for all of them.

**Comment by lbargaoanu** [comment]
And there is backward compatibility...

**Comment by lbargaoanu** [comment]
The fix makes sense to me, but it might break a lot of people.

**Comment by drewlederman** [comment]
I'm having the same sort of issue due to EF proxies, even when calling the explicit mapping method like this:

`Mapper.Map(viewModel, entity, typeof(ViewModel), typeof(Entity))`

I've created a map between the two types, however, AutoMapper seems to be using the auto-created map for the proxy type instead.

I would prefer keeping CreateMissingTypeMaps enabled to avoid having to create a bunch of empty mapping configurations.

I'm using the latest stable 6.0.2.

Thanks

**Comment by TylerCarlson1** [comment]
Use below instead of `CreateMissingTypeMaps = true` to ignore dynamic proxies
```
AddConditionalObjectMapper().Where((s, d) => s.NameSpace != "System.Data.Entity.DynamicProxies" && d.NameSpace != "System.Data.Entity.DynamicProxies");
```

Sigh ... Maybe we should kill CreateMissingTypeMaps and just explain Conditional mapping equivilent in the Wiki, so people have to be smarter when they use this.

**Comment by drewlederman** [comment]
@TylerCarlson1 Thanks, that works as expected. And I agree, this should be explained in the Wiki. :)

**Comment by jbogard** [comment]
@TylerCarlson1 perhaps we should just make that the default behavior for CreateMissingTypeMaps?

**Comment by jbogard** [comment]
I also wonder if there's a way to detect auto-generated proxies automatically, something in the type metadata.

**Comment by TylerCarlson1** [comment]
@jbogard The only way I know is `NameSpace == "System.Data.Entity.DynamicProxies"`  Don't think there's much other way to know if it was created at run time or dynamic or anything like that.  The rules are tailored to the scenario you are working in.  The most common would be the EF Proxies, but I wouldn't want to default that because it's kind of secrete.

**Comment by StefanoChiodino** [comment]
Can you please explain how to do this? I've been reading docs and trying various things but nothing seems to work for me.
```
                    .AddConditionalObjectMapper()
                    .Where(
                        (s, d) => s.Namespace != "System.Data.Entity.DynamicProxies"
                            && d.Namespace != "System.Data.Entity.DynamicProxies");
```

Solved the problem of automapper ignoring dynamic proxies, however it then throws when I try to map one of them:

```

AutoMapper.AutoMapperConfigurationException : 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
================================================================
HrContinent -> ContinentPageProxy (Destination member list)
Migration.Continent -> Castle.Proxies.ContinentPageProxy (Destination member list)
[...]
```

Thanks

**Comment by StefanoChiodino** [comment]
Nevermind, In my case the proxies were not the Entity Framework ones, but the Mock ones. I tried to make them work in the same manner but couldn't and just switched to fixtures rather than mocks!
