### ISSUE TITLE
aggregate mapping

### ISSUE THREAD

**Issue by thdotnet** [AutoMapper/AutoMapper#2005]
I'm trying to map from a List of List<Foo> to a single object, something like:

```
public class Foo
{
       public int Quantity { get;set;}
       public decimal Amount {get;set;}
}

public class FooSummary
{
      public decimal Total {get;set;} //sum of quantity * amount of the entire list.
}
```

Is it possible using AutoMapper? I could not find any sample about that. Thanks

**Comment by jbogard** [comment]
List of List to a single object? I don't see the lists, what would that look like?

**Comment by thdotnet** [comment]
Yes, from List to a single object (applying aggreagates)

**Comment by lbargaoanu** [comment]
If your top mapping is from list to a single item, there is nothing in AM to help with that, just use LINQ.
