### ISSUE TITLE
6.0 release notes and breaking changes

### ISSUE THREAD

**Issue by niemyjski** [AutoMapper/AutoMapper#2007]
It would be nice to know what's all breaking changes that went into it.

I'm compiling and now getting

```
    public class PersistentEventValidator : AbstractValidator<PersistentEvent> {
        public override ValidationResult Validate(PersistentEvent ev) {
```

'PersistentEventValidator.Validate(PersistentEvent)': cannot override inherited member 'AbstractValidator<PersistentEvent>.Validate(PersistentEvent)' because it is not marked virtual, abstract, or override	Exceptionless.Core	C:\Code\Exceptionless\src\Exceptionless.Core\Validation\PersistentEventValidator.cs	11	Active

which is assuming one of the breaking changes

**Comment by lbargaoanu** [comment]
Wrong repository? :)

**Comment by niemyjski** [comment]
awe dammit :\ sorry..

**Comment by niemyjski** [comment]
Still would be nice to know what the breaking changes were :)

**Comment by jbogard** [comment]
I'm writing the release notes today. Hard to coordinate all this.

**Comment by memark** [comment]
I actually have the same question. I have read the release notes for AutoMapper 6.0. Is everything under Features a breaking change, or are there in fact zero breaking changes?

**Comment by jbogard** [comment]
I've updated the release notes to include a link to breaking API changes. Shouldn't be too much for folks.

**Comment by memark** [comment]
Excellent, thanks a ton!

**Comment by szalapski** [comment]
Where are the release notes?

**Comment by jbogard** [comment]
In the Releases tab in GitHub
