### ISSUE TITLE
The type initializer for 'AutoMapper.ServiceCollectionExtensions' threw an exception

### ISSUE THREAD

**Issue by fravezzimattia** [AutoMapper/AutoMapper#2009]
LIBs : AutoMapper.Extensions.Microsoft.DependencyInjection 1.2.0
Error when is call services.AddAutoMapper();

FileLoadException: Could not load file or assembly 'AutoMapper, Version=5.0.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Error after update Automapper 5.2.0 => 6.0.0

**Comment by lbargaoanu** [comment]
That'a different repository.
