### ISSUE TITLE
Nuget Version Issue?

### ISSUE THREAD

**Issue by henderni** [AutoMapper/AutoMapper#2010]
When installing NuGet package the Version displays as 0.0.0.0 instead of 6.0.0.0
![automapperversion](https://cloud.githubusercontent.com/assets/1411052/24053316/e8350b2a-0af5-11e7-92ed-4bff8e2fe614.PNG)

**Comment by jbogard** [comment]
.....sigh

**Comment by jbogard** [comment]
Fixed, pull 6.0.1
