### ISSUE TITLE
Help with mapping

### ISSUE THREAD

**Issue by manojkgarg** [AutoMapper/AutoMapper#2017]
Please advise how i can map ProjectStructure to Job.
Here are my classes.
--
    public class ProjectStructure
    {
        public CustomerInfo CustomerInformation { get; set; }
        public int JobInformationID { get; set; }
    }

    public class CustomerInfo
    {
        public DateTime PreferredMeasureTime { get; set; }
        public DateTime DueDate { get; set; }
        public ContactDetail ContactDetails { get; set; }
    }

    public class ContactDetail
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UnitNo { get; set; }
        public string StreetNo { get; set; }
    }

    public class job
    {
        public int jobID { get; set; }
        public virtual ICollection<address> addresses { get; set; }

    }

    public partial class address
    {

        public long id { get; set; }

        public string unitNumber { get; set; }

        public string streetNumber { get; set; }
    }}

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
