### ISSUE TITLE
Nullable object must have a value error on two properties named with one having 'Value' at the end

### ISSUE THREAD

**Issue by markball99** [AutoMapper/AutoMapper#2019]
Consider the following code (simplified):

```
namespace ViewModels
{
    public class TestSource
    {
        public int? Prop1 { get; set; }

    }

    public class TestDest
    {
        public int? Prop1Value { get; set; }

    }
}

namespace Controllers
{
	public void test()
	{
		TestSource TestSource = new TestSource();
		TestDest TestDest = new TestDest();
		TestDest = Mapping.AutoMapper.AutoMap<TestSource, TestDest>(TestSource);
	}
}

namespace Mapping
{
	public class AutoMapper
    {
	    public static TDestination AutoMap<TSource, TDestination>(TSource source)
                        where TDestination : new()
        {
            TDestination destination = new TDestination();
            MapperConfiguration config = new MapperConfiguration(cfg => {
                cfg.CreateMissingTypeMaps = true;
                cfg.ForAllMaps((t, c) =>
                {
                    c.PreserveReferences();
                });
            });

            IMapper mapper = new Mapper(config);
            mapper.Map<TSource, TDestination>(source, destination);

            return destination;
        }
	}
}
```

The following error is thrown:

{"Nullable object must have a value."}

Error mapping types.

Mapping types:
TestSource -> TestDest
ViewModels.TestSource -> ViewModels.TestDest

Type Map configuration:
TestSource -> TestDest
ViewModels.TestSource -> ViewModels.TestDest

Property:
Prop1Value

This only happens when the property is nullable and the destination property named the same as the source but with Value appended.

I've submitted this as a bug but not sure if it can be classified as an AutoMapper bug or MS behaviour causing this - Auto-Implemented properties have fields in the background to contain the actual values and I'm sure they are the property name with 'Value' appended.

For your consideration...

**Comment by lbargaoanu** [comment]
Nullable has a property named Value so it's the default naming convention that's causing this. By design.

**Comment by markball99** [comment]
Just to be clear, I dont mean the second property being called prop1.Value but prop1Value (no dot).

My problem is with the none simplified code where I have prop1 and prop1value in the destination and the prop1value is generating the error - I'm going to use this as an excuse to name the properties better, rather that put in a fix. Cheers for the guidance.
