### ISSUE TITLE
Automapper Exceptions Cause APIs to Hang

### ISSUE THREAD

**Issue by MattHartz** [AutoMapper/AutoMapper#2020]
Not sure if this is related to Automapper, but in our codebase whenever we have automapper exceptions, the calling function will "retry".  It's a behavior I've never seen before with any other codebase, and I can't seem to find anything on stackoverflow.  

Is this a behavior that is caused to mal-use of automapper?
Has anyone seen this before?

It makes debugging automapper issues pretty simple to diagnose... if API hangs, it's an automapper issue (by us).
Thanks!

**Comment by lbargaoanu** [comment]
That doesn't make sense :)

**Comment by MattHartz** [comment]
@lbargaoanu I know ><. Normal exceptions are handled properly in the code, just not these.

**Comment by lbargaoanu** [comment]
One thing you should know is that in certain cases AM catches NREs, for example with flattening or MapFrom. And throwing a lot of exceptions is expensive, even more so during debugging.
