### ISSUE TITLE
Construct the value resolver with the supplied constructor function not working with latest version

### ISSUE THREAD

**Issue by AnshulMehta187** [AutoMapper/AutoMapper#2021]
Hi guys

I am working on VS 2013 and was currently using AutoMapper version 3.2.1 ,I have upgraded to the latest version 6.0.1 and updating my code base as per new features available with the latest version.

I am using CustomValue Resolver named BaseSectionNameResolver to resolve value for destination member name ,please see code below

```
config.CreateMap<TemplateTabRootTemplateTabSection, DTO.TabRender.Section>()
  .ForMember(dest1 => dest1.Name, opt => opt.ResolveUsing<BaseSectionNameResolver>().ConstructedBy(() => new BaseSectionNameResolver(translationCoordinator, cache, rc, request)))
```

Now as per the latest version ,I am not able to access the ConstructedBy method here to supply a constructor function .Is it possible for me to pass something like below to resolve this

```
Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<TemplateTabRootTemplateTabSection, DTO.TabRender.Section>() 
                .ForMember(dest1 => dest1.Name, opt => opt.ResolveUsing<BaseSectionNameResolver>()).ConstructedBy(() => new BaseSectionNameResolver(translationCoordinator, cache, rc, request)))});
            });
```

I found one method called ConstructUsing but it is used to provide custom instantiation for the destination type and not for the Custom Value Resolver .
Please suggest .

**Comment by lbargaoanu** [comment]
I'm guessing the resolver cannot be a singleton. Then you can use the Mapper constructor that takes a service constructor. You can use your container to create the resolver or you cand do it by hand.

**Comment by lbargaoanu** [comment]
See also https://github.com/AutoMapper/AutoMapper/issues/1724.

**Comment by jbogard** [comment]
You can use a constructor function still. I just consolidated the API:

```
config.CreateMap<TemplateTabRootTemplateTabSection, DTO.TabRender.Section>()
  .ForMember(dest1 => dest1.Name, opt => opt.ResolveUsing(new BaseSectionNameResolver(translationCoordinator, cache, rc, request)))
```

**Comment by jbogard** [comment]
I wouldn't recommend this, however. Generally configuration should be static and not taking in contextual parameters, you should instead look at dependency injection.

**Comment by nukec** [comment]
Problem is that when we want to use IMemberValueResolver for resolver reusability with different types, when we want to pass Enum through constructor(so we can do different operations based on enum type) then we don't have an option to use ResolveUsing with passing parameter in constructor + telling which parameter we want to pass as sourceMember. Massive failure.
