### ISSUE TITLE
AutoMapper declares unused dependency on System.ValueTuple for .NET4.5

### ISSUE THREAD

**Issue by patrykbuzowicz** [AutoMapper/AutoMapper#2022]
I tried upgrading AutoMapper from 5.2 to 6.0.1 and noticed it had the dependency on System.ValueTuple. It appeared that the System.ValueTuple itself added the DLL dependency to .netstandard while the projects are all targeting .NET4.5.

I know the above is not a problem of AutoMapper itself, however this prevents us from upgrading now. I investigated the nuget package manifest and while

https://github.com/AutoMapper/AutoMapper/blob/master/AutoMapper.nuspec

says it has no dependencies in .NET4.5, I still see 

![image](https://cloud.githubusercontent.com/assets/5390091/24196371/d88da0b8-0efd-11e7-9189-bb3a6625d1de.png)

in VS nuget window. After deploying the solution with AutoMapper 6 and manually removing the System.ValueTuple DLL from the bin folder the app works without problems.

Would it be possible to update package manifest in nuget.org so that it doesn't require System.ValueTuple? That would be really appreciated because the AutoMapper 5.2 might be causing some random problems in our unit tests and we hope AutoMapper 6 will be fine

**Comment by jbogard** [comment]
Gah. Yes, it was getting used for tuple support, but there's a bug so I took it out.

**Comment by patrykbuzowicz** [comment]
what about the dependency on nuget.org? is it going to be removed?

**Comment by jbogard** [comment]
Yes. https://github.com/AutoMapper/AutoMapper/releases/tag/v6.0.2
