### ISSUE TITLE
On-Board project to the .NET Foundation

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2026]
We're getting ready to bring the project into the .NET Foundation, but before we
do we need to do the following:

## Getting into the .NET Foundation
- [x] Make sure the project has a good name that is easy to remember and 
 spell. Check that it doesn't [conflict with another existing project](http://ivantomic.com/projects/ospnc/)
- [x] Make sure the people involved in the project want to join the .NET Foundation
- [x] Make sure the project has a clear understanding about how it accepts contributions and the process
     it follows when selecting new committers to the project.
- [x] [Register an interest](https://dotnetfoundation.org/get-involved) in joining the .NET Foundation
- [x] Work with the .NET Foundation to fill out an On-Boarding Questionaire
- [x] .NET Foundation sends out completed questionaire to .NET Foundation Advisory Council for comments
- [x] .NET Foundation Executive Director submits new project proposal to the .NET Foundation Board
- [x] Configure a CI build for the project and ensure build status badges are available from the README

## Once accepted into the .NET Foundation
- [x] Sign the contribution / assignment agreement
- [x] Agree a date to move into the .NET Foundation
- [x] Prepare a guest blog post announcing the move on the .NET Foundation Blog
- [x] Read the [code of conduct](https://dotnetfoundation.org/code-of-conduct), 
      [link to it in your code](be-nice.md) and 
      understand what to do if you are concerned about any behaviour or have
      concerns reported to you.
- [x] Tell the world we have joined!
- [x] Get CLA Automation enabled to ensure contributors can easily sign the 
      [Contribution License Agreement](https://cla2.dotnetfoundation.org/cladoc/net-foundation-contribution-license-agreement.pdf)
- [x] Send a PR to add the Project into the .NET Foundation 
      [list](https://github.com/dotnet/home/tree/master/projects)
- [x] Ensure the repo contents are up to date with [.NET Foundation guidance](repo-guide.md)
- [x] Review the [README guidance](readme-guide.md) and update if necessary
- [x] If applicable [update the LICENSE file](copyright.md) to show Copyright has been assigned to the .NET Foundation
      and look to update any file headers.
- [x] If applicable, update any copyright statements in websites owned by the project to reflect 
      assignment to the .NET Foundation
- [x] If applicable, update any websites associated with the project to include
      "Supported by the <a href="https://dotnetfoundation.org">.NET Foundation</a>" or
      similar link back to the .NET Foundation in the footer. If applicable, please
      include image links from [our swag repo](http://github.com/dotnet/swag). (We think a link in the footer using the horizontal logo looks very nice.)
- [x] [Sign up for Project Leader news](http://eepurl.com/bOCfJP)
- [x] Configure any resources requested from the .NET Foundation (SSL Certs, Code Signing,
      Secret Management, Build Servers etc)

**Comment by jbogard** [comment]
@TylerCarlson1 @lbargaoanu any questions/comments/concerns? I had a call w/ MS on what it meant and really the biggest thing would be a CLA if we decide to go that route.

**Comment by lbargaoanu** [comment]
I'm good :)

**Comment by TylerCarlson1** [comment]
My main concern, other than the CLA and possibly standardizing it, is what about the other projects that are based off AutoMapper. Do those have to follow these rules or do they remain outside the scope?

**Comment by jbogard** [comment]
Good question, @jongalloway I forgot to ask you this one. This is just for the main project, right? Not the ancillary ones under the AutoMapper org?

**Comment by lbargaoanu** [comment]
I guess the CLA thing would add an extra hurdle for first time contributors.

**Comment by jongalloway** [comment]
@jbogard You'd be welcome to move the other project, but you don't have to.

@lbargaoanu The CLA isn't required. Most projects do end up using it, because with the CLA bot it's pretty low impact and you can have more confidence in the source of contributions, but you don't have to if you think it's a blocker.

**Comment by jbogard** [comment]
@lbargaoanu having gone through the process it's pretty easy. When you submit a PR the CLA bot will send you a link to a docusign thingy that you e-sign. I thought it would be a huge pain but tbqh it was kinda impressive how it all is automated.

**Comment by jbogard** [comment]
@TylerCarlson1 since the Collection project is yours, it's your choice, I'm leaving the others out for now. They're so small anyway (EF6 and Data etc)

**Comment by TylerCarlson1** [comment]
@jbogard Ok that's fine with me.  I guess we'll see how AM goes and I'll decide from there.  Not necessarily opposed to it just wanted to know how all that would work.

**Comment by jbogard** [comment]
@jongalloway ping

**Comment by jongalloway** [comment]
Project was accepted by .NET Foundation directors. Next step is for significant contributors (I believe that's @jbogard @ChrisMissal @lbargaoanu @TylerCarlson1 correct?) to sign the contribution agreement. I'll need e-mail addresses so I can send via docusign. Can you send via e-mail / DM and I'll get the contribution agreement out to you?

**Comment by lbargaoanu** [comment]
My email domain is hotmail.com and my user name is the same as on github.

**Comment by TylerCarlson1** [comment]
Email is on github account page

**Comment by lbargaoanu** [comment]
@jongalloway I'm not sure where you draw the line, but @BlaiseD belongs on the list and @ChrisMissal doesn't. I think :) https://github.com/AutoMapper/AutoMapper/graphs/contributors

**Comment by ChrisMissal** [comment]
Seems fine. I think he was just looking at the organization's members: https://github.com/orgs/AutoMapper/people

**Comment by jbogard** [comment]
@BlaiseD can you update with email?

**Comment by BlaiseD** [comment]
Yep - done - now on my [profile page](https://github.com/blaised).  Thanks.

**Comment by jbogard** [comment]
@jongalloway that looks like everyone here!

**Comment by jongalloway** [comment]
Great, I'll get the agreement out to you today then.

**Comment by jbogard** [comment]
@jongalloway ping :)

**Comment by jongalloway** [comment]
Sent 

![](https://media.giphy.com/media/JWhwT0H8Kkw24/giphy.gif)

**Comment by BlaiseD** [comment]
Signed.  @lbargaoanu - appreciate the plug (https://github.com/AutoMapper/AutoMapper/issues/2026#issuecomment-314835098) BTW. Thanks.

**Comment by jbogard** [comment]
Signed!

**Comment by jongalloway** [comment]
Thanks everyone for the quick review and signature. There are a few more things that can be checked off the list above. The next step is to agree on a date to announce and if you've got any specific announcement requirements. Generally we've just been posting a quick announcement on http://dotnetfoundation.org/blog and publicizing via twitter (@dotnetfdn).

If you add the @dnfadmin account as a contributor on the project I can help keep the checklist up to date.

Congrats on making it through the grueling onboarding process. :) Sincerely, welcome!

**Comment by jbogard** [comment]
@jongalloway added @dnfadmin !

**Comment by jbogard** [comment]
@jongalloway as far as announcement requirements, I really don't have anything specific. I'll blog about it too on whatever date we agree. What's the lead time there? It won't take long for me to write a post up.

**Comment by jongalloway** [comment]
One day lead time is fine - you can see the recent announcement posts on https://dotnetfoundation.org/blog, they're just quick announcements. How about Wednesday Aug 2 at 12 PM Pacific time?

Also, to get the project listed on the our project list, can you submit a pull request to github.com/dotnet/home similar to this one: https://github.com/dotnet/home/pull/57/files

**Comment by jbogard** [comment]
That works for me! I'll get something hwhipped up

**Comment by jbogard** [comment]
OK I've got a blog post ready on my side and created that PR. Ready when you are!

**Comment by jbogard** [comment]
Oh one other thing @jongalloway - what do I need to do to get CLA automation going?

**Comment by jongalloway** [comment]
@jbogard I'm working on getting CLA automation set up. It is arduous but still, I will persist.

**Comment by jbogard** [comment]
@jongalloway ping :)

**Comment by jbogard** [comment]
All complete!
