### ISSUE TITLE
Destination constructor parameter should also match type, not only name.

### ISSUE THREAD

**Issue by torsten-github** [AutoMapper/AutoMapper#2027]
The default behavior (v. 5) prefers constructors with parameters over default constructor.

If a destination constructor parameter matches the name of a source property, that constructor is used. Ignoring any explicit `ForMember` configuration. If the types mismatch the call fails with an `AutoMapperMappingException (Missin type map configuration or unsupported mapping)`.

May be AutoMapper should also check if the types are compatible. (e.g. derived)

### BTW:
Choosing the constructor with the most parameters over default, makes sense in a lot of scenarios. Also I wouldn't expect it. All other classes I've seen in .NET (e.g. XMl serialization) even rely on a default constructor. But I'm sure this has been well discussed, and there are good reasons for this as a default behavior.

A nasty situation can rise up quickly. And the problem is not really obviously. Especially when the classes get bigger. Just renaming the constructor parameter `id` will fix or break the code.

```
public class A {
    public A() { }                  // Default constr. used by most magic classes
    public A(Guid id) { Id = id; }  // Rename id will fix AutoMapper issue.

    public Guid Id { get; set; }
}

public class B {
    public int Id { get; set; }     // New type forced by e.g. code-first
    public Guid Uid { get; set; }   // Property for GUID.
}

Mapper.Initialize(c => { 
    c.CreateMap<B, A>()
    .ForMember(m => m.Id, o => o.MapFrom(s => s.Uid));  // not working... (WTF)
    
    // ----
    //.ForSourceMember(s => s.Id, o => o.Ignore())      // To be sure, but useless (WTF)
    //.ConstructUsing(r => new A())                     // 8h research: This is the solution.
});

```

**Comment by lbargaoanu** [comment]
Try ForCtorParam.

**Comment by lbargaoanu** [comment]
The types don't have to match. AM will try to map from the source property to the constructor parameter.

**Comment by torsten-github** [comment]
Yes, I got it. Thanks for your answers. 

The question is, why not also let AM check the type of the source and destination? 
Any reason for that? It would make life much easier. Or am I missing something?

**Comment by lbargaoanu** [comment]
It considers the types and it complains it cannot map between them. What would you have it do?

**Comment by torsten-github** [comment]
From my point of view, **AM does not** consider the _types_.  It **only consider** the _names_.

AM chooses a constructor that has a parameter with the same _name_. But the _types_ miss match.
That's why an exception is thrown during run time. :(

**AM should** consider also the _types_. 
It *should not* try to use a constructor with a parameter _type_ that does not match. Even if the parameter _name_ matches. 

In this case, **AM should use the default constructor**.

**Comment by lbargaoanu** [comment]
And what if a map applies, or a built in mapper?

**Comment by torsten-github** [comment]
Sorry, i don't get what you mean. Maybe because I'm not so deep in AM.

I like AM, but this was really confusing me. And I'm afraid, this could happen more often, when some one in the project adds an constructor or does some renaming. I'll just write some more unit tests for our mappings.

thanks.

**Comment by lbargaoanu** [comment]
You can simply disable constructor mapping if you don't use it.
