### ISSUE TITLE
How to specify DateTime kind when using Projection

### ISSUE THREAD

**Issue by chris-eaton** [AutoMapper/AutoMapper#2029]
I want all my `DateTime` fields to be `Utc`.  I have tried numerous options but none seem to work.  Can someone please help me.  The clocks have just gone forward in the UK and now everything is broken :)

So far I've tried this:

```
cfg.CreateMap<DateTime, DateTime>().ProjectUsing(i => new DateTime(i.Year, i.Month, i.Day, i.Hour, i.Minute, i.Second, DateTimeKind.Utc));
cfg.CreateMap<DateTime?, DateTime?>().ProjectUsing(i => new DateTime(i.Value.Year, i.Value.Month, i.Value.Day, i.Value.Hour, i.Value.Minute, i.Value.Second, DateTimeKind.Utc));
```
And this
```
cfg.CreateMap<DateTime, DateTime>().ConstructProjectionUsing(i => new DateTime(i.Year, i.Month, i.Day, i.Hour, i.Minute, i.Second, DateTimeKind.Utc));
cfg.CreateMap<DateTime?, DateTime?>().ConstructProjectionUsing(i => new DateTime(i.Value.Year, i.Value.Month, i.Value.Day, i.Value.Hour, i.Value.Minute, i.Value.Second, DateTimeKind.Utc));
```

**Comment by lbargaoanu** [comment]
The first ProjectUsing should do it. That is, the result would be UTC, I don't know about the value :)

**Comment by chris-eaton** [comment]
Yeah unfortunately it's not working!! ;/

**Comment by lbargaoanu** [comment]
You're missing something. 
A repro would help. Make a gist that we can execute and see fail.

**Comment by chris-eaton** [comment]
Heres the preceeding code if that helps

```
cfg.CreateMap<GpsEntityLib.Models.Plot, MyCompany.Common.Models.Plot>()
    .ForMember(plot => plot.DriverId, opt => opt.Ignore())
    .ForMember(plot => plot.VehicleId, opt => opt.Ignore())
    .ReverseMap();
```

**Comment by lbargaoanu** [comment]
I'll try again :) Make a gist that we can execute and see fail. Like [this](https://gist.github.com/lbargaoanu/dd272fcdead462b0588f48e4a5a92575).

**Comment by chris-eaton** [comment]
@lbargaoanu Ah ok, thank you for the template...

So heres an interesting thing.. I created a Gist [[here](https://gist.github.com/chris-eaton/bdcade5ed8c4e3d2124fce5ea1615410)] but running that gives me one of two errors depending on which ProjectUsing I use [note one is commented out]:

> An unhandled exception of type 'System.NotSupportedException' occurred in EntityFramework.SqlServer.dll
> 
> Additional information: LINQ to Entities does not recognize the method 'System.DateTime SpecifyKind(System.DateTime, System.DateTimeKind)' method, and this method cannot be translated into a store expression.
and
> An unhandled exception of type 'System.NotSupportedException' occurred in EntityFramework.SqlServer.dll
> 
> Additional information: Only parameterless constructors and initializers are supported in LINQ to Entities.

So the first one makes sense as AutoMapper is trying to push that onto EF but the second error doesnt.  Also it doesn't make sense to me that this error happens in the test project but not my main one... In my main one I get no errors thrown.  The only difference is I use repos [that return IQueryable]

**Comment by lbargaoanu** [comment]
Ok, so EF doesn't support it. So you must use Map instead or try to work around it. See https://blogs.msdn.microsoft.com/dotnet/2017/02/28/the-week-in-net-on-net-with-eric-mellino-happy-birthday-from-scott-hunter-ozcode/. Search for NeinLinq. That might work with ProjectTo.

**Comment by chris-eaton** [comment]
Any idea why it doesn't fail in my normal app?

**Comment by lbargaoanu** [comment]
If you're really evaluating the IQueryable then I guess the config is different, the repro is not really a repro :) You might be able to solve this in EF by switching to DateTimeOffset.

**Comment by chris-eaton** [comment]
Ok thanks for your help, I guess my only real solution then is to write custom getter/setters on my DTO that specifies the Kind when set

**Comment by lbargaoanu** [comment]
I think they do, but they solve it in EF, probably with DateTimeOffset.

**Comment by chris-eaton** [comment]
Ah - might be a bit late for me then, we already have a huge database with DateTimes in so I doubt we can move can we?

**Comment by lbargaoanu** [comment]
I don't know :) Didn't really look into it.

**Comment by KuroThing** [comment]
Is there no reason why you couldn't do something like ```cfg.CreateMap<DateTime, DateTime>().ProjectUsing(d => d.ToUniversalTime())```
