### ISSUE TITLE
Not correct mapping when custom mapping between Enums (ConstructUsing)

### ISSUE THREAD

**Issue by lisamariet** [AutoMapper/AutoMapper#2030]
I am struggling to get Automapper to map my enums correctly. I have created a sample project with the failing tests to better explain the case. Please tell me what is wrong. 

https://github.com/lisamariet/MyAutoMapperIssues

Regards,

**Comment by lbargaoanu** [comment]
I don't use NUnit, a simple gist is more helpful. But it should map by numeric value and if that is not possible by string value.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/Enumerations.cs

**Comment by lbargaoanu** [comment]
Try ConvertUsing instead of ConstructUsing.

**Comment by lisamariet** [comment]
Doh!!! That worked like a charm... :-)
