### ISSUE TITLE
Null source collection emptying destination collection

### ISSUE THREAD

**Issue by lestersconyers** [AutoMapper/AutoMapper#2031]
I'm attempting to merge 3 objects into a single object. Each object is the same class with multiple List<T> members, one of which is named Columns. The first object's Columns member is null. The 2nd is a List with 9 items. The 3rd is null.

During the merge the List<T> members go from null (expected), 9 items (expected), 0 items (wth?) when the 3rd source object has a null member. Am I missing something?
`
var config = new AutoMapper.MapperConfiguration(cfg => {
                cfg.AllowNullCollections = true;
                cfg.AllowNullDestinationValues = true;

                cfg.CreateMap<ConfigurationInfo, ConfigurationInfo>()
                    .ForAllMembers(option => {
                        option.Condition((source, destination, sourceMember, destMember) => sourceMember != null);
                    });

            });

            var mapper = config.CreateMapper();
            
            ConfigurationInfo finalTemplate = new ConfigurationInfo();

            foreach (ConfigurationInfo template in templates) {
                mapper.Map(template, finalTemplate);

                Console.WriteLine(template.Columns == null ? "It's null" : template.Columns.Count + " items");
            }
`

**Comment by lbargaoanu** [comment]
Try a PreCondition instead. See #1918 and #1940.
