### ISSUE TITLE
Graph not being mapped completely

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#2032]
I have the following models and their corresponding dto's:

```
    public class Parent
    {
        public ICollection<Child> Children {get; set;}
    }

    public class Child
    {
        public virtual Entity Entity {get; set;}
    }
```

The above is to simply show how the graph is structured. The classes include much more properties (primitive and complex).

I have the mappings set up accordingly and I also do:

`    cfg.ForAllPropertyMaps(pm => true, (pm, m) => m.MapAtRuntime());`

I map a list of Parents so I do:

`    var dtoList = Mapper.Map<ICollection<ParentDto>>();`

The list gets mapped, however Entity is not mapped and so it's always null. To test, I mapped just one child by doing:

```
    var list = myService.GetParents();
    var e = Mapper.Map<EntityDto>(list.First().Children.First().Entity);
```

The above test works and the Entity is mapped as expected. I'm using the latest version of Automapper (6.0.2)

So why does the mapping of the parent collection not work as expected?

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by cryo75** [comment]
Attached is a complete project where the entity is not being mapped. The entity in case is `Outlet` of the `Children` items.

[TestAutomapper.zip](https://github.com/AutoMapper/AutoMapper/files/874867/TestAutomapper.zip)

**Comment by lbargaoanu** [comment]
this.Outlet = Outlet;

Really? :)
