### ISSUE TITLE
Reversed mappings do not validate

### ISSUE THREAD

**Issue by 4ux-nbIx** [AutoMapper/AutoMapper#2034]
Hi,
I wanted to use ReverseMap method instead of creating two separate mappings but it seems like reversed maps do not validate properly.

Here's what I mean:
```C#
public class A
{
    public string One { get; set; }
    public string Two { get; set; }
}

public class B
{
    public string One { get; set; }
}

// works
configuration.CreateMap<A, B>();
configuration.CreateMap<B, A>();

// doesn't work
configuration.CreateMap<A, B>().ReverseMap();
```

Calling AssertConfigurationIsValid should fail in case with ReverseMap, because it's not possible to fully map B to A, because B doesn't have property Two.

Is it a bug or a feature I wonder?

Cheers,
Roman

**Comment by cryo75** [comment]
You can use:

`configuration.CreateMap<A, B>(MemberList.Destination).ReverseMap();`

To map only propeties found in B.

**Comment by lbargaoanu** [comment]
You example works with the latest build. You should upgrade.

**Comment by 4ux-nbIx** [comment]
lbargaoanu, no it doesn't work. Package update was the first thing I did today...

**Comment by 4ux-nbIx** [comment]
Here's the test:
```C#
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ReverseMapTest
{
    public class A
    {
        public string One { get; set; }
        public string Two { get; set; }
    }

    public class B
    {
        public string One { get; set; }
    }

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        [ExpectedException(typeof(AutoMapperConfigurationException))]
        public void ShouldFailOnMissingPropertyMappingInSeparateMappingConfig()
        {
            Mapper.Initialize(c =>
            {
                c.CreateMap<A, B>();
                c.CreateMap<B, A>();
            });

            Mapper.AssertConfigurationIsValid();
        }

        [TestMethod]
        [ExpectedException(typeof(AutoMapperConfigurationException))]
        public void ShouldFailOnMissingPropertyMappingInReversedMap()
        {
            Mapper.Initialize(c =>
            {
                c.CreateMap<A, B>().ReverseMap();
            });

            Mapper.AssertConfigurationIsValid();
        }
    }
}
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build. But I would think the fix is on Nuget. The prerelease check?

**Comment by 4ux-nbIx** [comment]
Tried checking prerelease, but 6.0.2 is the latest one...

**Comment by lbargaoanu** [comment]
It works bot with MyGet and NuGet. You're missing something I believe. ShouldFailOnMissingPropertyMappingInReversedMap fails because it doesn't throw :)

**Comment by lbargaoanu** [comment]
Or maybe I misunderstood your point. Your problem is that is doesn't throw? That's by design. Search the older issues.
