### ISSUE TITLE
Parameterized projections and child entities

### ISSUE THREAD

**Issue by FilipFilipov** [AutoMapper/AutoMapper#2036]
Is there any way to do a database projection where an inner map gets a parameter injected from an outer map? I tried with `ForMember(map => map.ChildMap, opt => opt.MapFrom(parent => parent.Child.AsQueryable().ProjectTo<ChildMap>(new { param = true })`, but LINQ can't translate that to sql.

**Comment by lbargaoanu** [comment]
What are you trying to do?

**Comment by lbargaoanu** [comment]
What would the resulting LINQ statement would look like? All AM can do is write that statement for you. So it would help to know what the end result would be.

**Comment by FilipFilipov** [comment]
Now that I think about it, uniting the two results in the database may not be possible. I'll just make two models with different maps and a third calculated property that will concatenate the two resulting collections after the mapping.
