### ISSUE TITLE
Changes between version 4.2 and 6.0

### ISSUE THREAD

**Issue by webpaul** [AutoMapper/AutoMapper#2039]
I recently upgraded from 4.2 to 6.0 to get the performance gains, which are very nice, thanks! But after a few days we found a difference in behavior that affects many of our mappings dealing with how constructors and properties are handled. The below test passes in 4.2 but not in 6.0. The actual mapping made use of "!IsSourceValueNull" which I originally thought was the issue and makes more sense than the below code but I found that I could simplify it down to this so that it was the exact same code in 4.2 and 6.0 where one passes and one fails.

Is there a configuration option I can set somewhere to make it behave like 4.2?

        private class AddressModel
        {
            public AddressModel()
            {
                Configuration = new AddressModelConfiguration();
            }

            public AddressModelConfiguration Configuration { get; set; }

            public bool AddressIsRequired
            {
                get
                {
                    return Configuration.AddressIsRequired;
                }
            }
        }

        private class AddressModelConfiguration
        {
            public AddressModelConfiguration()
            {
                AddressIsRequired = true;
            }

            public bool AddressIsRequired { get; set; }
        }

        private class InternalUserModel
        {
            public InternalUserModel()
            {
                Address = new AddressModel
                {
                    Configuration = new AddressModelConfiguration
                    {
                        AddressIsRequired = false,
                    }
                };
            }
            public AddressModel Address { get; set; }
        }

        private class TestObj
        {

        }

        [TestMethod]
        public void CanMapAddressModelConfiguration()
        {
            Assert.IsFalse(new InternalUserModel().Address.AddressIsRequired);

            var mapper = new MapperConfiguration(mapConfig =>
            {
                mapConfig.CreateMap<TestObj, InternalUserModel>()
                    .ForMember(dest => dest.Address, opt => opt.MapFrom(x => x));

                mapConfig.CreateMap<TestObj, AddressModel>();
            }).CreateMapper();

            var vm = mapper.Map<TestObj, InternalUserModel>(new TestObj { });
            Assert.IsFalse(vm.Address.AddressIsRequired);
        }

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#usedestinationvalue

**Comment by webpaul** [comment]
Adding that to the Address field did indeed fix it, thanks!
