### ISSUE TITLE
Is there a way to detect changes on the destination object ?

### ISSUE THREAD

**Issue by AnthonyBr** [AutoMapper/AutoMapper#2040]
I map two objects of the same types where only null values of the source type are ignored:

 cfg.CreateMap<Intervention, Intervention>().ForAllMembers(opt => opt.Condition(rc => rc.SourceValue != null));

... 

Mapper.Map(newData, current );

I could like to know if a change has been made on the newData object: is there a way to achieve this ?

Thank you

**Comment by jbogard** [comment]
.....why? ORMs do this for you, what are you trying to do? AutoMapper isn't a cloning/diff library.

**Comment by AnthonyBr** [comment]
I don't use it to clone/diff but to merge data structures the same type. The library seams to be useful to include merging rules.

**Comment by lbargaoanu** [comment]
You might be able to do it using a member value resolver because that one receives the source and destination members.

**Comment by AnthonyBr** [comment]
I see the resolver is set globally: how are we able to know a map/merge has changed my destination object ?

**Comment by lbargaoanu** [comment]
A resolver is set per member.

**Comment by lbargaoanu** [comment]
You can use Context.Items per Map call to pass results.

**Comment by AnthonyBr** [comment]
I added a resolver for all members, I have the following error:

AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

Here are the resolver I tried:

```
    public class CustomResolver : IValueResolver
    {
        public ResolutionResult Resolve(ResolutionResult source)
        {
            return source;
        }
    }
```
```
        public object Resolver(ResolutionResult resolutionResult)
        {
            // Log.Debug( resolutionResult.Value );
            return resolutionResult.Value;
        }
```

Remark: I'm limited to AutoMapper 4.2 as still using Visual Stuidio 2012
