### ISSUE TITLE
MemberInfo for Source and Destination properties in ResolutionContext's PropertyMap

### ISSUE THREAD

**Issue by vgotra** [AutoMapper/AutoMapper#2041]
Is it possible to add PropertyMap to ResolutionContext with possibility to retrieve MemberInfo for Source and Destination properties, similar to v.4* (**context.PropertyMap.DestinationProperty.MemberInfo**)?

Thanks

**Comment by TylerCarlson1** [comment]
You could use ForAllPropertyMaps and get property info for each mapping there for the expression generated and make changes there.

**Comment by lbargaoanu** [comment]
You might also be able to pass it yourself, depending on what exactly you're doing.

**Comment by lbargaoanu** [comment]
See the discussion [here](https://github.com/AutoMapper/AutoMapper/pull/1753) for example.
