### ISSUE TITLE
Convert DateTime to string in Entity Framework with LINQ

### ISSUE THREAD

**Issue by efftronicsit** [AutoMapper/AutoMapper#2044]
Hi, i am using Automapper & Entity Framework with LINQ recently for improving performance of our system. 

I got an error (Type 'System.String' does not have a default constructor) while converting DateTime to string (see above image)

![code](https://cloud.githubusercontent.com/assets/26621482/24539520/a6c7b9e0-160c-11e7-8e0d-dbe92eb98bc7.PNG)

I was tried with two scenarios :
**scenario :- 1**
    **config.CreateMap<DateTime, string>().ConvertUsing(dt => dt.ToString());**
![error](https://cloud.githubusercontent.com/assets/26621482/24539314/95c83da0-160b-11e7-8c60-2547c96a07e2.PNG)

**Scneraio :- 2**
      **config.CreateMap<DateTime, string>().ConvertUsing(new StringToDateTimeTypeConverter());**
![error 2](https://cloud.githubusercontent.com/assets/26621482/24539402/fd724676-160b-11e7-85e2-89ae6f41743e.PNG)

in both cases gives as error.

Thanks in advance.

**Comment by lbargaoanu** [comment]
ConvertUsing works with Map, ProjectUsing with ProjectTo.

**Comment by efftronicsit** [comment]
I was tried with ProjectUsing, even though i got an error "**LINQ to Entities does not recognize the method 'System.String ToString(System.String)' method, and this method cannot be translated into a store expression.**"

Code Snippet :- 
![code2](https://cloud.githubusercontent.com/assets/26621482/24540413/c12f3e76-1610-11e7-8ab4-cd0e6b870ba6.PNG)

Mapping using ProjectUsing 
![error3](https://cloud.githubusercontent.com/assets/26621482/24540436/ddcddc36-1610-11e7-8934-a0ddc5d40c9b.PNG)

I am using Entity Framework with LINQ and Automapper combination.

Thanks in advance..

**Comment by lbargaoanu** [comment]
Yes, but that's an EF issue. Try upgrading EF.

**Comment by efftronicsit** [comment]
i am using latest version 6.1.3, 
Can u suggest to me any alternative solution.
Thanks in advance.

**Comment by lbargaoanu** [comment]
That's an EF question. But I would guess you can only use the ToString without parameters, remember, your code runs inside the database.

**Comment by efftronicsit** [comment]
Not compiled when ToString mentioned without parameters.
Thank you.

**Comment by lbargaoanu** [comment]
It works for me without doing anything. Just type it as string.

**Comment by efftronicsit** [comment]
ToString() is working properly,  i want convert DateTime to string in specified format (yyyy-MM-dd HH:mm:ss).

**Comment by lbargaoanu** [comment]
Yes, that's because you cannot run that .NET code in the database. You can either use Map or a workaround. See https://blogs.msdn.microsoft.com/dotnet/2017/02/28/the-week-in-net-on-net-with-eric-mellino-happy-birthday-from-scott-hunter-ozcode/. Search for NeinLinq. That might work with ProjectTo.

**Comment by efftronicsit** [comment]
Thank you
