### ISSUE TITLE
Issue with Entity Framework proxies

### ISSUE THREAD

**Issue by couellet** [AutoMapper/AutoMapper#2046]
I am retrieving an entity from my DbContext:

```chsarp
var order = Context.Set<Order>().Find(id);
```

It returns a `DynamicProxies` class to enable lazy loading and things like that.

I created this extension method to map my object to a DTO:

```csharp
public static T Map<T>(this object source)
{
    if (source.GetType().FullName.Contains("System.Data.Entity.DynamicProxies"))
    {
        var baseType = ObjectContext.GetObjectType(source.GetType());
        
        var obj =  (T) Mapper.Map(source, baseType, typeof(T));

        return obj;
    }

    return Mapper.Map<T>(source);
}
```

I validated that the base type is correctly extracted from the proxy.

My mapping looks like this:

```csharp
CreateMap<Order, OrderDto>()
  .ForMember(...);
```

Then to map my object:

```csharp
var dto = order.Map<OrderDto>();
```

I would expect this mapping to be used as I specify the types explicitly but it is not.

Please note that I set `CreateMissingTypeMaps` to `true`.

**Comment by lbargaoanu** [comment]
This was discussed many times [before](#2004).
