### ISSUE TITLE
Inheritance mapping, inconsistent documentation.

### ISSUE THREAD

**Issue by jnapier** [AutoMapper/AutoMapper#2048]
The demonstration provided with the documentation for inheritance mapping, https://github.com/AutoMapper/AutoMapper/wiki/Mapping-inheritance, does not seem to hold true if IncludeBase is used instead of Include.  I am seeing that if I ignore a property on the base then it will only be mapped on the derived class if I explicitly map the property. If i rely on convention then the property will not be mapped.

The example can be changed to
```
Mapper.Initialize(cfg => {
    cfg.CreateMap<Order, OrderDto>()
          .ForMember(o=>o.Referrer, m=>m.Ignore());
    cfg.CreateMap<OnlineOrder, OrderDto>()
       .IncludeBase<Order, OrderDto>();
    cfg.CreateMap<MailOrder, OrderDto>()
        .IncludeBase<Order, OrderDto>();
    });

// Perform Mapping
var order = new OnlineOrder { Referrer = "google" };
var mapped = Mapper.Map(order, order.GetType(), typeof(OrderDto));
Assert.Equals("google", mapped.Referrer);
```
This Assertion will fail. According to the priorities list i would think that Ignore would take precedence and the result should be expected. However, the demonstration in the documentation seems to imply that convention in the derived class should have a higher priority than a property ignored in the base.   Can you please clarify exactly how this is supposed to work?

**Comment by lbargaoanu** [comment]
Yes, this was changed recently and the docs were left behind. The ignore is inherited. Would you please fix it? :)

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/issues/1732.

**Comment by michaelaird** [comment]
We recently upgraded to 6.1 (from 5.2) and now many of our mappings are not working as expected. Our mappings used to have many "ignores" on the base class mapping which the convention would then take care of overriding to map properly for the sub-classes.

What's the correct syntax to get the pre-6.0 behaviour? (we have quite a few mappings and going through each one to explicitly map all the things that used to be mapped by convention will be time consuming...)

**Comment by lbargaoanu** [comment]
It was decided that the old behavior was wrong. If you want it, you'll have to implement it yourself.

**Comment by jbogard** [comment]
Do you have an example?

**Comment by michaelaird** [comment]
It's a bit long but here's an example the shows the issue:

```c#

public abstract class FormElement
    {
        public Guid Id { get; set; }
        public int Order { get; set; }
    }

    public class CommentControl : FormElement
    {
        public string Label { get; set; }
    }

    public abstract class FieldControl : FormElement
    {
        public string Label { get; set; }
        public string Trailer { get; set; }
    }

    public abstract class TextFieldControl : FieldControl
    {
        public string DefaultValue { get; set; }
        public int Size { get;  set; }
    }

    public class TextBoxControl : TextFieldControl
    {
        public int Rows { get; set; }
    }

    public enum FormElementType
    {
        TextBox = 3,
        Comment = 7,
    }

    public abstract class FormControlBaseDTO
    {
        public Guid Id { get; set; }
        public int Order { get; set; }
    }

    public class FormElementDTO : FormControlBaseDTO
    {
        public FormElementType ElementType { get; set; }
        public string Label { get; set; }
        public string Trailer { get; set; }

        public string DefaultValue { get; set; }
        public int Size { get; set; }
        public int Rows { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<FormElement, FormElementDTO>()
               .Include<CommentControl, FormElementDTO>()
               .Include<TextBoxControl, FormElementDTO>()
               .ForMember(dto => dto.ElementType, opt => opt.Ignore())
               .ForMember(dto => dto.Label, opt => opt.Ignore())
               .ForMember(dto => dto.Trailer, opt => opt.Ignore())
               .ForMember(dto => dto.DefaultValue, opt => opt.Ignore())
               .ForMember(dto => dto.Size, opt => opt.Ignore())
               .ForMember(dto => dto.Rows, opt => opt.Ignore());

                cfg.CreateMap<CommentControl, FormElementDTO>()
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.Comment));

                cfg.CreateMap<TextBoxControl, FormElementDTO>()
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.TextBox));
            });

            TextBoxControl textbox = new TextBoxControl()
            {
                Id = Guid.NewGuid(),
                Order = 12,
                Label = "Enter Name",
                Trailer = "Thanks",
                DefaultValue = "name",
                Size = 10,
                Rows = 2
            };

            FormElementDTO output = Mapper.Map<TextBoxControl, FormElementDTO>(textbox);
            Debug.Assert(output.Label == textbox.Label);
        }
    }
```

I've tried to cut this down from our real code. We have a hierarchy of various form control elements that all get projected to a single DTO with a broad set of properties and and enum to tell the client code which type of control it is.

With Automapper 5.2, the above code works perfectly and the concrete type of  TextBoxControl gets all of the its properties mapped to the FormElementDTO by convention. Since 6.0+, the .Ignore()'s on the base class mapping have a higher precedence than the convention mapping so all those properties are not mapped.

I read through the comments on some of the issues that lead to this change and, while I personally think the original behaviour made sense, I see why this confused some people. Since this is a very large breaking change, would it be possible to choose old vs new precedence when the mappings are being configured?

**Comment by lbargaoanu** [comment]
You can apply the Ignore in the derived map with ForAllOtherMembers, but this will ignore all the inherited members too, so you would map only what is specified explicitly in the derived map.

**Comment by jbogard** [comment]
Why are the ignores there in the first place?

**Comment by michaelaird** [comment]
@jbogard : without the ignores, Mapper.AssertConfigurationIsValid() throws exceptions about unmapped members. Is there a better/different way to go about this that I totally missed?

**Comment by jbogard** [comment]
Ah I see it now, the destination types don't match the source types in their inheritance structure. I think for this one, since you really want to have a class that's a superset of all properties, you want to tweak the configuration validation just for the base. Try this:


```c#
            Mapper.Initialize(cfg => {
                cfg.CreateMap<FormElement, FormElementDTO>(MemberList.None)
               .Include<CommentControl, FormElementDTO>()
               .Include<TextBoxControl, FormElementDTO>();

                cfg.CreateMap<CommentControl, FormElementDTO>()
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.Comment));

                cfg.CreateMap<TextBoxControl, FormElementDTO>()
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.TextBox));
            });
```

**Comment by jbogard** [comment]
I think that'll be a bit cleaner and explicit about what you were intending to do with all those Ignores. Ignore has 2 purposes - skip an unmapped property during validation, and skip a mapped property during mapping.

**Comment by michaelaird** [comment]
Ok! This works. I did have to make one small change:

```c#
                cfg.CreateMap<CommentControl, FormElementDTO>(MemberList.Source)
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.Comment));

                cfg.CreateMap<TextBoxControl, FormElementDTO>(MemberList.Source)
                .ForMember(dto => dto.ElementType, opt => opt.UseValue(FormElementType.TextBox));
```

Adding Memberlist.Source to the derived classes did the convention mapping properly. Without it, AssertConfigurationIsValid complained on missing mapping for CommentControl->FormElementDTO

**Comment by lbargaoanu** [comment]
Yes, but this means giving up validation.

**Comment by michaelaird** [comment]
@lbargaoanu do the derived mappings still get validated? I think that's sufficient.

**Comment by lbargaoanu** [comment]
No, you need MemberList.Destination, the default.

**Comment by michaelaird** [comment]
Ok. Just to clarify my understanding based on the docs here : https://github.com/AutoMapper/AutoMapper/wiki/Configuration-validation

MemberList.None on the "root" object says "don't do any validation on this mapping at all.
Memberlist.Source on the "leaf" object in the inheritance tree says "validate that all the properties on the source object are mapped.

For our specific case, I think this is correct. The destination object has a large list of properties that match some of the source properties. We want to make sure all of the source properties get mapped

**Comment by lbargaoanu** [comment]
:) If that's what you want then I guess you should specify that for all the maps and take it from there. You might have no need for Ignore.

**Comment by jbogard** [comment]
I think the ideal would be no Ignore's in this scenario. A ton of Ignore's usually means there's something you want to tweak on the validation side

**Comment by michaelaird** [comment]
Agreed. that's what @jbogard  recommended above and seems to be working correctly now. (as far as i can tell).

Slightly related question: should the inheritance and precedence order mapping work the same with .ForSourceMember and MemberList.Source? I'm trying to ignore a source property on the "root" object but AssertConfigurationIsValid  is complaining that the source field is not mapped on the leaf object. ( I can post another example and/or open a separate issue if this is going too far off the rails)

**Comment by lbargaoanu** [comment]
I guess it should, but few people use it, so I don't think it does.
