### ISSUE TITLE
Failure when trying to unit test query that uses Project().To<T> Queryable extension

### ISSUE THREAD

**Issue by va20ych** [AutoMapper/AutoMapper#2049]
Hi guys! I'm trying to unit test a query that uses .Project().To<T> with defined automapper configuration. (Please see https://msdn.microsoft.com/en-us/library/dn314429%28v=vs.113%29.aspx?f=255&MSPPError=-2147217396). But unfortunatly query execution with mocked DbContext fails (it works when supplying standard Select projection). What can I do to succesfully test queries with  .Project().To<T> usage? 

Thanks, Volodymyr

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/tree/master/src/IntegrationTests.Net4. You need a LINQ provider that translates to SQL, not LINQ to objects. We use Sql Server LocalDB. Sql Server compact should also work. Or SqlLite. SqlLite has an in memory option that's pretty fast. You can look [here](https://github.com/lbargaoanu/KendoUIMvcApplication) for inspiration. See also https://www.nuget.org/packages/SQLite.CodeFirst/.

**Comment by va20ych** [comment]
As I understand I can't make Project().To work successfully based on my in-memory provider mock? The point here is that I don't want to involve integration testing with some external database. What I would like to unit test is filter predicates, proper fields mappings etc. I understand that this test is not so close to reality, but it will cover a lot of code pieces without external dependency.

**Comment by lbargaoanu** [comment]
It should work in memory too. You just need to start from some IQueryable.

**Comment by lbargaoanu** [comment]
[Examples](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=asqueryable&type=).

**Comment by va20ych** [comment]
Thanks! it was helpful.
