### ISSUE TITLE
DateTime Timezone Issues

### ISSUE THREAD

**Issue by Tobysauce77** [AutoMapper/AutoMapper#2052]
After updating from a very old version, I noticed a change with DateTime mapping. Even with a DateTime converter that changes the Kind of DateTime, something in AutoMapper changes it to UTC time. So for example, let's say I want the DateTime to be specified as Local time like this:

```
public class DateTimeAutoMapperResolver : AutoMapper.ITypeConverter<DateTime, DateTime>
    {
        public DateTime Convert(DateTime source, DateTime destination, ResolutionContext context)
        {
            destination = DateTime.SpecifyKind(new DateTime(source.Ticks), DateTimeKind.Local);
            return destination;
        }
    }
```

Even with this, the dates come back converted to UTC time. I cannot find a setting to stop it from doing this. I do not want AutoMapper to modify DateTimes.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by Tobysauce77** [comment]
Sorry, no time for making a stand alone project, please just use the DateTime converter that I posted above, and you will notice the same thing happening - that all DateTimes will have the Kind of UTC.

**Comment by lbargaoanu** [comment]
I don't see it.

**Comment by Tobysauce77** [comment]
Look at what happens to the DateTime from the source object to the mapped destination object in the before and after images of AutoMapper running. It adjusted the date to be Utc which affected the time.
![beforeautomapper](https://cloud.githubusercontent.com/assets/5116755/24724296/97f7251c-1a18-11e7-97e8-16cd8fd7b15c.png)

![afterautomapper](https://cloud.githubusercontent.com/assets/5116755/24724299/9b334f08-1a18-11e7-88dc-f5782d575816.png)

**Comment by lbargaoanu** [comment]
That's not helpful. A repro would do it.

**Comment by jbogard** [comment]
@Tobysauce77 so we don't need a complete program. Just:

- Source type
- Destination type
- Mapping configuration
- Mapping execution showing expected behavior

Without this we're flying a bit blind
