### ISSUE TITLE
Having multiple IValueResolver implementations on a single class fails

### ISSUE THREAD

**Issue by NinoFloris** [AutoMapper/AutoMapper#2053]
Automapper only considers the first Resolve method and then fails with 

```
System.InvalidOperationException : No coercion operator is defined between types 'X' and 'Y'
```

Fix is to take into account the types and resolve the correct method based on that

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/0f29418497958dd3eeff9a5145fd446fb0e3baf8/src/UnitTests/CustomMapping.cs#L21

**Comment by lbargaoanu** [comment]
Duplicate of https://github.com/AutoMapper/AutoMapper/issues/1887.
