### ISSUE TITLE
ICtorParamConfigurationExpression.ResolveUsing<TValueResolver>

### ISSUE THREAD

**Issue by DaveVdE** [AutoMapper/AutoMapper#2056]
I have a couple of places where I want to use a value resolver to do some kind of transformation, but I can't because my destination models are immutable. Right now this forces me to use type converters for these immutable models, because there's no `ResolveUsing` method on the interface to configure constructor members, like there is on the interface to configure property members.

**Comment by DaveVdE** [comment]
Specifically, the method that allows me to configure to use a custom value resolver across a number of mappings by redirecting the source model would be useful.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/8dd104aa7390c12c97c4195cce6f6ff66de24f51/src/AutoMapper/ICtorParamConfigurationExpression.cs#L21
If you're missing some other overload, PR-s are welcome.
