### ISSUE TITLE
Ignore() isn't working as expected

### ISSUE THREAD

**Issue by hoda9801** [AutoMapper/AutoMapper#2061]
We recently updated from version 3.0 to 6.0.2 and ran into an issue. I'm not sure if this is a bug or a breaking change from v3 to v6. We need to set a property of a property and ignore it. This worked in version 3, and I'm trying to figure out how we go about fixing it in v6. I put together a test to show as an example. 

```csharp
    [TestClass]
    public class TestInitializer
    {
        public enum MyEnum
        {
            First,
            Second
        }

        [TestMethod]
        public void AuotmapperTest()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<TestObjectA, TestObjectB>();
                cfg.CreateMap<SubObjectC, SubObjectD>().ForMember(m => m.SubProp2, c => c.Ignore());
            });

            var temp = new TestObjectA() {
                Prop1 = "Hello",
                Prop2 = MyEnum.First,
                Prop3 = new SubObjectC() { SubProp1 = "Good"}
            };
            var mytest = Mapper.Map<TestObjectB>(temp);
            Assert.AreEqual(true, mytest.Prop3.SubProp2);
        }
    }

    public class TestObjectA
    {
        public string Prop1 { get; set; }
        public TestInitializer.MyEnum Prop2 { get; set; }

        public SubObjectC Prop3 { get; set; }
    }

    public class TestObjectB
    {
        public string Prop1 { get; set; }
        public string Prop2 { get; set; }

        public SubObjectD Prop3 { get; set; }

        public TestObjectB()
        {
            Prop3 = new SubObjectD() { SubProp2 = true };
        }
    }

    public class SubObjectC
    {
        public string SubProp1 { get; set; }
    }

    public class SubObjectD
    {
        public string SubProp1 { get; set; }
        public bool SubProp2 { get; set; }
    }
```

In this example we want to set TestObjectB.Prop3.SubProp2 to be true when TestObjectB gets instantiated. In the test mytest.Prop3.SubProp2 turns out to be false. Is this a change in the ignore behavior from version 3 to 6?

**Comment by jbogard** [comment]
You're ignoring the `SubProp2` property, and since it doesn't have a source property, it won't have anything attached to it.

However, in your parent mapping, TestObjectA -> TestObjectB, when it maps Prop3 -> Prop3, it will instantiate a new SubObjectD and map SubProp1.

In 3.0, it would check the destination value everywhere. That's super expensive. If you want to use the destination value for SubObjectD, you'll need to configure the parent mapping:

```
CreateMap<TestObjectA, TestObjectB>()
    .ForMember(dest => dest.Prop3, opt => opt.UseDestinationValue());
```

**Comment by hoda9801** [comment]
Yep, that does it. Thank you for helping us out!

**Comment by hoda9801** [comment]
I cam across a slight variation to this and that is when Prop3 is a List<SubObjectC>. This then fails again. I tried...

`cfg.CreateMap<List<SubObjectC>, List<SubObjectD>>()
                   .ForAllMembers(c => c.UseDestinationValue());`

But that doesn't map any of the properties. So, how do I utilize UseDestinationSource on lists of objects?

**Comment by lbargaoanu** [comment]
You don't need to create a map for lists, they are handled automatically.

**Comment by hoda9801** [comment]
That's what I thought. But, in my test, if you change the Prop3 to a list of SubObjectD objects my test fails.

`Assert.AreEqual(true, mytest.Prop3.First().SubProp3);` 

I expected this to pass without changing the mappings, but it fails.

**Comment by jbogard** [comment]
Remember, UseDestinationValue is about the properties themselves. So you'd apply that to the parent object that contains the list.

**Comment by hoda9801** [comment]
If I'm understanding you correctly this test should pass, but it's failing. So, maybe I'm misunderstanding something. 

`    [TestClass]
    public class TestInitializer
    {
        public enum MyEnum
        {
            First,
            Second
        }

        [TestMethod]
        public void AuotmapperTest()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<TestObjectA, TestObjectB>()
                    .ForMember(m => m.Prop3, c => c.UseDestinationValue());
                cfg.CreateMap<SubObjectC, SubObjectD>()
                    .ForMember(m => m.SubProp2, c => c.Ignore());
            });

            var temp = new TestObjectA() {
                Prop1 = "Hello",
                Prop2 = MyEnum.First,
                Prop3 = new List<SubObjectC>() { new SubObjectC() { SubProp1 = "Good" } }
            };

            var mytest = Mapper.Map<TestObjectB>(temp);
            Assert.AreEqual(true, mytest.Prop3.First().SubProp2);
        }
    }

    public class TestObjectA
    {
        public string Prop1 { get; set; }
        public TestInitializer.MyEnum Prop2 { get; set; }
        public List<SubObjectC> Prop3 { get; set; }
    }

    public class TestObjectB
    {
        public string Prop1 { get; set; }
        public string Prop2 { get; set; }
        public List<SubObjectD> Prop3 { get; set; }

        public TestObjectB()
        {
            Prop3 = new List<SubObjectD>() { new SubObjectD() { SubProp2 = true }};
        }
    }

    public class SubObjectC
    {
        public string SubProp1 { get; set; }
    }

    public class SubObjectD
    {
        public string SubProp1 { get; set; }
        public bool SubProp2 { get; set; }
    }`

**Comment by lbargaoanu** [comment]
The collection itself should be the same object, not its contents.
