### ISSUE TITLE
AddProfiles() should be able to include internal profiles

### ISSUE THREAD

**Issue by asherber** [AutoMapper/AutoMapper#2063]
Currently, the Code for `AddProfilesCore()` calls `GetExportedTypes()` for all assemblies, which only looks at public types. This means that if my current assembly has profiles declared as `internal`, this won't work:
```csharp
var config = new MapperConfiguration(cfg => {
    cfg.AddProfiles(Assembly.GetExecutingAssembly());
});
```
It would be nice to be able to include internal profiles in some way.

**Comment by lbargaoanu** [comment]
You can use your DI container for that, or try a PR.

**Comment by danielsvr** [comment]
I would like to submit a PR for this issue, but I can't find the project on the Contributor License Agreement site.

disclaimer: this is the first time contributing to an open source project.

**Comment by lbargaoanu** [comment]
You don't have to do anything at the moment. Just a PR.

**Comment by danielsvr** [comment]
Thanks for the reply.

**Comment by Capellan29** [comment]
How can I stop receiving emails from this thread? I unsubscribed from this thread and a keep receiving mails anyway. Please help me :(
