### ISSUE TITLE
ReverseMap() - Working with complex types

### ISSUE THREAD

**Issue by StefanKert** [AutoMapper/AutoMapper#2067]
Like mentioned in #359 I think the default behavior of ReverseMap() is not really obvious. Right now it only works bidirectional for mappings that are implicit like so:

```C#
class A {
 string Member { get; set; }
}

class B {
 string Member { get; set; }
}

cfg.CreateMap<A, B>() .ReverseMap();
```

In this scenario where both classes have members that are named equally ReverseMapping works perfect. But if classes contain members that are different and not mapped via the default (per naming) mapping this doesn´t work properly.

```C#
class A {
 string Member { get; set; }
 string OtherMember { get; set; }
}

class B {
 string Member { get; set; }
 string NonMember { get; set; }
}

cfg.CreateMap<A, B>() .ReverseMap();
```
The way to go to make this work in one direction is to ad the Mapping via `ForMember`.

```C#
cfg.CreateMap<A, B>()
    .ForMember(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ReverseMap();
```

This now works properly in one direction, but adding `ReverseMap()` doesn´t make it work in both directions so you have to make the mapping similar to this:

```C#
cfg.CreateMap<A, B>()
    .ForMember(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ReverseMap()
            .ForMember(x => x.OtherMember, m => m.MapFrom(a => a.NonMember));
```
So basically this might lead to some issues. First of all this is code duplication and will duplication will always be error prone. Next I think the default behavior of `ReverseMap()` is not really clear for everyone that uses AutoMapper. 

With this issue I wanted to state a few questions:

* Why is this behavior not implemented? Are there any specific reasons that are not obvious for us right now? Would be great to here about those reasons because I can´t imagine an issue with this right now.

* How can this behavior be achieved? I think there are 3 possible solutions for this:
  1. Add this behavior to `ReverseMap()` per Default (or via config, or param)
  2. Add another Method like `ForMember` for example `MapFromWithReverse`
  3. Add another Method like `MapFrom`  for example `MapFromWithReverse`

Maybe we can use this issue to discuss the if we should, or if we should not implement this behavior and also if we should do so how´s the best way to get this to work.

**Comment by lbargaoanu** [comment]
Search the old issues. It was discussed many times.

**Comment by StefanKert** [comment]
@lbargaoanu Can you refer me to those issues? I can only find the one I already mentioned (#359) that discusses this topic and it got closed without any comment. Also @jbogard wanted me to create another issue regarding this topic. So if you´ve already discussed this many times maybe you can point me to those Issues.

**Comment by lbargaoanu** [comment]
What was discussed it's ReverseMap and why it's not exactly Reverse. That's what I meant.

**Comment by StefanKert** [comment]
But this doesn´t target the topic of this issue? I can imagine why it works the way it works right now, but the topic of this issue is to discuss whether it is possible to improve on this behavior and if we should improve or change this behavior.

**Comment by lbargaoanu** [comment]
:) It's certainly important if we are to change the default behavior.

**Comment by lbargaoanu** [comment]
I think you would have to be explicit about it so maybe an enum parameter to ReverseMap, ApplyMapFroms. And I guess ignore more complex source expressions. Throwing seems excessive.

**Comment by StefanKert** [comment]
Agreed. I think we should leave the default behavior as it is.  `ReverseMap()` should only reverse the mappings for those where an implicit mapping can be made (Equal names or config). 

Enum Params seem a bit gross for me and it doesn´t apply to the default way to do configuration in AutoMapper too, so I guess it would be better to add a method like `ReverseMapForMapFroms()` to define the complexer scenarios that should be reverse mapped. 

As you state we should proceed the way as it worked until now: For mappings that aren´t reversed explicitly or aren´t reversed implicit should be ignored. Throwing exceptions would lead to really big pain for all the people updating their libs to a version that includes this change so this is a no go.

**Comment by lbargaoanu** [comment]
We use enums elsewhere, MemberList for example. It's more terse.

**Comment by StefanKert** [comment]
For the scenarios where `MemberList` is used i think this fits perfectly. Indeed I´d like to add that I would prefer to use a Fluent API instead of an enum paramter but this is another topic.

Basically the difference between the places where `MemberList` is used and this one, is that for `Memberlist` we only have three different values that are exclusive so you can have only one at a time. For `ReverseMap()` we´ll have many enum members that also will come in together. So let me just throw in a little example here:

```C#
cfg.CreateMap<A, B>()
    .ForMember(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ForMember(x => x.SecondNonMember, m => m.ResolveUsing(a => a.SecondOtherMember))
    .ReverseMap(ReverseMappings.ApplyMapFroms | ReverseMappings.ResolveUsings);
```
Does this add up to the version you are talking about?

What I would prefer is that you can configure this through a Fluent API like so:

```C#
cfg.CreateMap<A, B>()
    .ForMember(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ForMember(x => x.SecondNonMember, m => m.ResolveUsing(a => a.SecondOtherMember))
    .ReverseMap()
    .ReverseMapFroms()
    .ReverseMapUsings();
```

Or, and this is the version I really like, with a config parameter for `ReverseMap()`

```C#
cfg.CreateMap<A, B>()
    .ForMember(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ForMember(x => x.SecondNonMember, m => m.ResolveUsing(a => a.SecondOtherMember))
    .ReverseMap(cfg => {
       cfg.ReverseMapFroms();
       cfg.ReverseMapUsings();
        // or simple for using all Reversemappings
       cfg.ReverseAll(); 
    })
```
Another possible solution would be to leave it to the definition of the mapping in the first place to decide whether to reverse or not. Here is an example:

```C#
cfg.CreateMap<A, B>()
    .ForMemberWithReverse(x => x.NonMember, m => m.MapFrom(a => a.OtherMember))
    .ForMemberWithReverse(x => x.SecondNonMember, m => m.ResolveUsing(a => a.SecondOtherMember));
```

All examples are just to start the discussion. These are in no way final solutions, just considerations and if one of these solutions would fit we should definitely find some better names.

**Comment by lbargaoanu** [comment]
I guess that depends on how many settings there are. I don't think ResolveUsing should be a part of this conversation. Even for MapFrom, only simple top level member accesses would work.

**Comment by StefanKert** [comment]
I agree on the fact that `MapFrom()` would be a great way to start, but I  guess if this behavior is implemented it will be needed for other mapping types too. Maybe we can get @jbogard into the discussion to get some input from his side for this topic.

**Comment by jbogard** [comment]
Resolvers would never be able to be reversable. You can also have the issue of MapFrom, that although it expects an expression, you can do any kind of valid expression in there:

```
ForMember(dest => dest.Foo, opt => opt.MapFrom(src => src.Bar * 42));
```

I think we could detect the easy case - maps where we are just mapping from one top-level property to another. But what happens when you reverse map an expression that we don't support? At the moment, it would silently skip it. That's probably fine for expressions where it's completely obvious it's not just member redirection.

But since un-flattening isn't supported at the moment, a less obvious silent skip would be:

```
ForMember(dest => dest.Foo, opt => opt.MapFrom(src => src.Bar.Baz.Buzz));
```

The question is - is it valuable to reverse map simple property redirection, but without unflattening?

**Comment by lbargaoanu** [comment]
If we did smth like ForMemberWithReverse (ugly as it is) we could throw instead of skipping.

**Comment by jbogard** [comment]
The thing is though if people call ReverseMap they really want that behavior. I added a new issue to support path mapping, which I think is more appropriate. #2068

**Comment by StefanKert** [comment]
Well I guess in first place it would be cool to get this basic version up and running that makes it possible to Reverse Mappings for MapFrom on top level members only.
