### ISSUE TITLE
Converting from string to byte[] fails with exception

### ISSUE THREAD

**Issue by rbluethl** [AutoMapper/AutoMapper#2071]
Hello,

I'm having a problem converting from a `string` to a `byte[]`.
I tried using `ForMember` to achieve custom transformation, however the mapping fails with an exception I can't explain.

Could it be that I'm missing a parameterless constructor on my `AssetResourceInfo` class?
I also tried using `ConstructUsing` which didn't work either.

Note: The other way round (converting from byte[] to string), however, works perfectly.

### Exception
```
Test method 
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Char -> Byte
System.Char -> System.Byte
```

### Source/destination types

```csharp
// Source
public class AssetModel
{
    public long ForeignKeyLandingPage { get; set; }
    public string Name { get; set; }
    public string Data { get; set; }
    public string MediaType { get; set; }
    public bool Exists { get; set; }
    public bool Update { get; set; }
    public bool Delete { get; set; }
}

// Destination
public class AssetResourceInfo
{
    public string Name { get; private set; }
    public byte[] Data { get; private set; }
    public AssetResourceInfo(string name, byte[] data)
    { 
        this.Name = name;
        this.Data = data;
    }
}

```

### Mapping configuration

```csharp
Mapper.Initialize(config =>
{
    config.CreateMap<AssetModel, AssetResourceInfo>()
        .ForMember(dest => dest.Data, opt => opt.MapFrom(src =>System.Convert.FromBase64String(src.Data)));
});
```

**Comment by lbargaoanu** [comment]
Constructor mapping fails because there is no default mapping from string to byte array. You can disable it if you don't use it.

**Comment by rbluethl** [comment]
Thanks for the quick answer, but I can't really follow along.
What do you mean by "You can disable it if you don't use it."?

I see that there is no default mapping and therefore I'm explicitly defining the way it should be converted using `ForMember`. Isn't that the way to go?

I also tried adding a parameterless constructor - still no difference.

Thanks and best regards,
Ronald

**Comment by lbargaoanu** [comment]
Maybe something like #2045 would have helped.

**Comment by lbargaoanu** [comment]
https://github.com/search?q=org%3AAutoMapper+DisableConstructorMapping&type=Code

**Comment by lbargaoanu** [comment]
If you want to use that constructor then you need ForCtorParam, not ForMember.

**Comment by rbluethl** [comment]
Alright, that works perfectly - thanks for pointing me into the right direction.

Ronald
