### ISSUE TITLE
Automapper ignores "CreateMap" rule for generic type parameters 

### ISSUE THREAD

**Issue by Usaga** [AutoMapper/AutoMapper#2072]
I using opened generic mapping based on this article:
 https://github.com/AutoMapper/AutoMapper/wiki/Open-Generics and its working well. But I found that Automapper uses default mapping convention for types used as parameters for generic type and ignores explicit CreateMap mapping.

Example:
```C#
...
Mapper.CreateMap<UserAccess, UserAccessViewModel>()
    .ForMember(x => x.FirstName, opt => opt.ResolveUsing(y => y.IsTemplate ? y.Alias : y.FirstName))
    .ForMember(x => x.LastName, opt => opt.ResolveUsing(y => y.IsTemplate ? y.Alias : y.LastName))
    .ForMember(x => x.FullName, opt => opt.ResolveUsing(y => y.GetDisplayName()));
...
Mapper.CreateMap(typeof(PagedList<>), typeof(PagedList<>));
... 
// Somewhere in code...
var userAccessesViewModel = Mapper.Map<PagedList<UserAccessViewModel>>(usersAccesses);
```

Automapper ignores mapping rule for UserAccess and UserAccessViewModel and uses its default behaviour. Do I make it wrong or it is by desing?

**Comment by lbargaoanu** [comment]
Lists are handled by default, no need for a map.

**Comment by Usaga** [comment]
Its not a list - custom generic class (with list inside, yes). And I need custom rule for mapping items stored in this custom generic list (as I shown above).

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by Usaga** [comment]
I double checked and found that it was second mapping rule reside in another configuration profile! 

All works fine! Sorry for this. Thanks for fast response.
