### ISSUE TITLE
IncludeBase doesn't work for interface inheritance

### ISSUE THREAD

**Issue by ilya-on-github** [AutoMapper/AutoMapper#2073]
Hello

I use AutoMapper 5.0.2 and I there is a strange behaviour when using IncludeBase and interfaces inheritance. Seems like IncludeBase doesn't work with interfaces.

I have 2 assemblies with 2 sets of models:
1) "API" with model interfaces and DTOs: 
```c#
public interface IBase
{
    ...
}
public interface IDerived: IBase
{
    ...
}
```
and a parallel hierarchy of DTOs: 
```c#
public class ApiBaseDto: IBase
{
    ...
}
public class ApiDerivedDto: IDerived
{
    ...
}
```
2) "Persistence" with ORM DTOs:
```c#
internal class OrmBaseDto: IBase
{
    ...
}
internal class OrmDerivedDto: IDerived
{
    ...
}
```

In API I call data access layer, it returns IBase (instance is OrmDerivedDto) and then I call Map<IDerived, ApiDerivedDto>(base)
```c#
...
    IDerived model = _query.Execute(); // returns OrmDerivedDto
    return AutoMapper.Map<IDerived, ApiDerivedDto>(model);
...
```

In AutoMapper I have following mapping:

```c#
CreateMap<IBase, ApiBaseDto>()
    .ForMember(trg => trg.Prop, cfg => cfg.MapFrom(src => src.AnotherProp);

CreateMap<IDerived, ApiDerivedDto>()
    .IncludeBase<IBase, ApiBaseDto>();
```

So I expect AutoMapper would map OrmDerivedDto using ForMember(trg => trg.Prop, cfg => cfg.MapFrom(src => src.AnotherProp) from base type map, but it didn't.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by ilya-on-github** [comment]
sorry, my fault, found a model namespace mismatch in CreateMap.
Wrote a test, it was green, so I rechecked every single member with its namespace and found a mismatch. It was CreateMap<CommandStack.Model...> instead of CreateMap<QueryStack.Model...>
