### ISSUE TITLE
How to use: DestinationDto needs additional property populated.

### ISSUE THREAD

**Issue by mhsimkin** [AutoMapper/AutoMapper#2076]
Environment: C#, AutoMapper 6.0.2, AutoMapper.EF6 1.0.0

Problem: DestinationDto needs additional property populated.

Details:

I have some code similar to this to retrieve the SourceDto from the database and transform it to the DestinationDto:

    context.GetAuditEntries(entity).ProjectToList<DestinationDto>()

I have configured the mapping for these classes as:
    
    cfg.CreateMap<PdsAuditEntry, WebAuditEntry>()
    	.ForMember(dest => dest.State, opt => opt.MapFrom(src => src.StateName))
    	.ForMember(dest => dest.ChangeSetId,
			 opt => opt.MapFrom(src => src.ChangeSetID.ToString("N")));
    
The source and destination class are defined as:
    
    public class DestinationDto
    {
      public int AuditEntryID { get; set; }
      public string CreatedBy { get; set; }
      public DateTime CreatedDate { get; set; }
      public string EntitySetName { get; set; }
      public string EntityTypeName { get; set; }
      public string State { get; set; }
      public string ChangeSetId { get; set; }
      public string EntityKey { get; set; }
    }
    
    public class SourceDto
    {
      public int AuditEntryID { get; set; }
      public string CreatedBy { get; set; }
      public DateTime CreatedDate { get; set; }
      public string EntitySetName { get; set; }
      public string EntityTypeName { get; set; }
      public List<AuditEntryProperty> Properties { get; set; }
      public AuditEntryState State { get; set; }
      public string StateName { get; set; }
      public string ChangeSetId { get; set; }
    }

At the time I'm retrieving the SourceDto, I know the value that needs to be stored in the DestinationDto::EntityKey property.

From what I've been able to determine, I need to create a custom IValueResolver.  In that code, I can look at the resolution ResolutionContext::Items array to find the EntityKey.

What I can't seem to figure out is how to pass in my EntityKey so that it ends up in the resolution context.

Thank you for your help.

-marc

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers#passing-in-key-value-to-mapper

**Comment by mhsimkin** [comment]
Thank you.  

I can make that work.  It would be nice if on the next release if you could add a queryable map extension that would have an Action<IMappingOperationOptions> as a parameter.

-marc

**Comment by jbogard** [comment]
?
