### ISSUE TITLE
Mapping a collection with a single parent object creates multiple parent object instances.

### ISSUE THREAD

**Issue by torsten-github** [AutoMapper/AutoMapper#2078]
### Source/destination types
```csharp
    public class Foo {
        public FooDad Dad { get; set; }
    }

    public class FooDad { }

    public class DestFoo {
        public DestFooDad Dad { get; set; }
    }

    public class DestFooDad { }
```

### Mapping configuration
```csharp
            Mapper.Initialize(c => {
                c.CreateMap<Foo, DestFoo>();
                c.CreateMap<FooDad, DestFooDad>();
            });
```

### Version: x.y.z
6.0.2.0

### Expected behavior
The destination list should also contain only one single `DestFooDad` instance.
Because the source list contains one single `FooDad` instance.

### Actual behavior
The destination list contains multiple `DestFooDad` instances.

### Steps to reproduce

```csharp
            var dad = new FooDad();
            var foos = new List<Foo> {
                new Foo {Dad = dad},
                new Foo {Dad = dad}
            };

            var destFoos = Mapper.Map<IList<DestFoo>>(foos);

            if (destFoos[0].Dad != destFoos[1].Dad)
                throw new Exception("Parrent objects are not the same instances.");
```

[MapperTest.zip](https://github.com/AutoMapper/AutoMapper/files/928022/MapperTest.zip)

**Comment by lbargaoanu** [comment]
You have to set PreserveReferences. Check the upgrade guide in the wiki.

**Comment by torsten-github** [comment]
Yes. Thanks.

I was searching the web a hole day for this without success.
You can run into this very quickly with Entity Frameworks Navigation Properties.

Hope this thread will help some others.

**Comment by jbogard** [comment]
@lbargaoanu see I wonder if this is where we can start to put more intelligence into ReverseMap. Doing things like preserving references, reverse flattening (creating a PathMap from a PropertyMap etc)

**Comment by lbargaoanu** [comment]
Yes, I guess so :) So your initial view was that ReverseMap was for mapping from the view model to the entity and that's why it was not the mirror image of the original map. But people expected just that so we started fixing their issues. And now it seems like we should go all the way. Right? And about unflattening. I guess that would also have to cover the default flattening, based on the naming convention.

**Comment by jbogard** [comment]
I'm going to track this as a group of issues in the unflattening GH issue.
