### ISSUE TITLE
Issue using naming conventions and prefixes

### ISSUE THREAD

**Issue by NickBehrends** [AutoMapper/AutoMapper#2079]
### Source/destination types

I'm trying to convert:

	public class User
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
	}
	
To:

	public class user_dto
	{
		public string ud_first_name { get; set; }
		public string ud_lastname { get; set; }
	}

And back again.

### Mapping configuration

    public static class AutoMapperConfig
    {
        public static void RegisterMappings()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.RecognizeDestinationPrefixes(new []{"ud_"});
                cfg.RecognizePrefixes(new[] { "ud_" });
                cfg.DestinationMemberNamingConvention = new LowerUnderscoreNamingConvention();
                cfg.SourceMemberNamingConvention = new PascalCaseNamingConvention();

                cfg.CreateMap<User, user_dto>().ReverseMap();
            });
        }
    }

### Behavior

This works fine for converting the last name, but not the first name. Per the docs the naming convention being setup as I have it should convert `ud_first_name` -> `FirstName`, but it silently fails and only the `lastname` is converted.

Interestingly enough, if I remove the prefix lines in the config and also remove the leading `ud_` from the `user_dto` and run the application, John Doe's whole name is converted, but only Marry's last name is converted. Are you not able to remove prefixis and use the naming conventions to convert with automapper? Is there supposed to be a different/better way to achieve what I'm trying?

### Steps to reproduce
Console application:

	static void Main(string[] args)
	{
		AutoMapperConfig.RegisterMappings();

		var newUser = new User
		{
			FirstName = "John",
			LastName = "Doe"
		};

		var newUser2 = new user_dto
		{
			ud_first_name = "Marry",
			ud_lastname = "Jane"
		};

		var newUserDTO = AutoMapper.Mapper.Map<user_dto>(newUser);

		Console.Write(newUserDTO.ud_first_name + " " + newUserDTO.ud_lastname);

		var newUserViewModel = AutoMapper.Mapper.Map<User>(newUser2);

		Console.Write(newUserViewModel.FirstName + " " + newUserViewModel.LastName);
		Thread.Sleep(100); //breakpoint here
	}
[Also a SO with more detail and trouble shooting](http://stackoverflow.com/questions/43497334/issue-using-naming-conventions-and-prefixes-in-automapper/43497888?noredirect=1#comment74052576_43497888)

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/blob/c968f34e58eed73e7cb40e8e52849408693eddb6/src/UnitTests/Bug/NamingConventions.cs. And you need
     
    cfg.RecognizeDestinationPrefixes("ud");

**Comment by NickBehrends** [comment]
So the change to the prefeix was a good change, thank you. I refactored my config to use profiles similar to the link you suggested, and i can now convert from `User` to `user_dto` however, when converting `user_dto` to `User` the `ud_lastname` is the only field that converts, `ud_first_name` does not convert. (The `ud_` seems necessary for User -> dto)

    Mapper.Initialize(cfg =>
            {
                cfg.CreateProfile("UserViewModelToDto", prf =>
                {
                    cfg.RecognizeDestinationPrefixes(new[] { "ud" });
                    prf.DestinationMemberNamingConvention = new LowerUnderscoreNamingConvention();
                    cfg.CreateMap<User, user_dto>();
                });

                cfg.CreateProfile("UserDtoToViewModel", prf =>
                {
                    cfg.RecognizePrefixes(new[] { "ud_" });
                    prf.SourceMemberNamingConvention = new LowerUnderscoreNamingConvention();
                    cfg.CreateMap<user_dto, User>();
                });
            });

**Comment by NickBehrends** [comment]
Holy shit it works. You're the man :1st_place_medal:
