### ISSUE TITLE
Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)

### ISSUE THREAD

**Issue by rajasekharkatakam** [AutoMapper/AutoMapper#2082]
I am having 2 classes and i had mapped it. 
### Source/destination types

```csharp
 public partial class Person : BaseEntity
    {
       
        [Key]
        public long PKPersonID { get; set; }

        public long? FKContactTypeID { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [StringLength(50)]
        public string MiddleName { get; set; }
}
public class RelatedPersonDTO:BaseEntity
    {
        public long PKPersonID { get; set; }

        public long FKContactTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

    }
```
Is there any other way apart from making public long FKContactTypeID { get; set; } to public long ?FKContactTypeID { get; set; } in RelatedPersonDTO class
### Mapping configuration

```csharp
 CreateMap<Person, RelatedPersonDTO>()              
            .ForMember(dto => dto.Mode, conf => conf.Ignore());

 baseEntity class  having mode i am ignoring it.
```

### Version: x.y.z
6.0.2 

### Expected behavior

it should map to FKContactTypeID even if it is null but iam getting issue 
Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)

### Actual behavior

Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
Workaround ```...ForMember(d=>d.FKContactTypeID, o=>o.NullSubstitute(0))```.
@jbogard Is there some reason why this is not the default behavior?

**Comment by rajasekharkatakam** [comment]
@lbargaoanu thank you for quick response. Its working if i keep  NullSubstitute

**Comment by rajasekharkatakam** [comment]
@lbargaoanu HI i am facing another issue can you please tell me the solution on that Please look in to this link https://github.com/AutoMapper/AutoMapper/issues/2083

**Comment by jbogard** [comment]
@lbargaoanu no that should work. We have paths to detect nullable -> not-nullable, and use default(TSource) when source is null. I think this is a bug.

**Comment by jbogard** [comment]
This works for me just fine:

https://gistlyn.com/?gist=626038060f09fc45e1a4d3ae4c2f5d91

I'm not seeing this behavior.

**Comment by lbargaoanu** [comment]
It's not Map, it's ProjectTo, I had to guess that :) And I don't see that path for ProjectTo,

**Comment by jbogard** [comment]
Sigh. And I thought the "Steps to reproduce" would help point people to including it...

**Comment by lbargaoanu** [comment]
Noooo, that would be too easy...
