### ISSUE TITLE
Cannot compare 'member 'PersonAddresses' of type 'FINAPI.DTO.PersonDTO''. Only primitive types, enumeration types and entity types are supported.

### ISSUE THREAD

**Issue by rajasekharkatakam** [AutoMapper/AutoMapper#2086]
I am getting error while mapping while mapping PersonDTO to PersonBO

Error: "Cannot compare 'member 'PersonAddresses' of type 'FINAPI.DTO.PersonDTO''. Only primitive types, enumeration types and entity types are supported."

### Source/destination types

```csharp
public class PersonBO 
 {
  public long id { get; set; }
public Guid guid { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public List<AddressBO> addresses { get; set; }
}

 public class PersonDTO
    {
        public long PKPersonID { get; set; }
        public Guid PersonGUID { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        
         public List<PersonAddressDTO> PersonAddresses { get; set; }
       

    }
 public class AddressBO
    {
               public long id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
}
   public class PersonAddressDTO:BaseEntity
    {
        public long PKPersonAddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
}
public IQueryable<IBusinessObject<PersonDTO>> GetLoanContactsByLoanGuid(Guid loanGuid)
        {
           
            
            return _loanQuery.getPersonDTO(loanGuid).ProjectTo<PersonBO >(_lmsBOMapper.Mapper.ConfigurationProvider);
        }
```

### Mapping configuration

   

CreateMap<PersonDTO, PersonBO>()
          .ForMember(bo => bo.id, conf => conf.MapFrom(ol => ol.PKPersonID))
          .ForMember(bo => bo.guid, conf => conf.MapFrom(ol => ol.PersonGUID))
 .ForMember(bo => bo.addresses, conf => conf.MapFrom(ol => ol.PersonAddresses));    
  CreateMap<PersonAddressDTO, AddressBO>()
            .ForMember(bo => bo.id, conf => conf.MapFrom(ol => ol.PKPersonAddressID))
            .ForMember(bo => bo.address1, conf => conf.MapFrom(ol => ol.AddressLine1))
            .ForMember(bo => bo.address2, conf => conf.MapFrom(ol => ol.AddressLine2));
```

### Version: x.y.z
6.0.2 

### Expected behavior

<!-- What did you expect to happen? Or what used to happen in an older version? -->

### Actual behavior

<!-- What happened instead? -->

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
I don't see it. A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail. Like [this](https://gist.github.com/lbargaoanu/dd272fcdead462b0588f48e4a5a92575).

**Comment by rajasekharkatakam** [comment]
@lbargaoanu https://gist.github.com/rajasekharkatakam/b713fb0d6a195c5c1f31bed48e401448

**Comment by lbargaoanu** [comment]
That's not a repro.
