### ISSUE TITLE
Long Static Constructor Causes Serious Performance Issues

### ISSUE THREAD

**Issue by DerekScheller** [AutoMapper/AutoMapper#2087]
have a significant amount of models that I am using Automapper with ~150. Having all of these in the static constructor causes this class to crawl in VS. Intellisense really does not work and the class when edited responds slowly in the editor and is causing me a lot of issues. Is there a better way of doing my mapping configuration that I am missing? Is this a known issue with having a long static constructor? If so what is the best way to break apart my constructor to alleviate these issues?

Also I would like to note that I am working on a P50 with 32gb RAM, SSD, I7quad 2.72ghz. This is not a hardware issue I do many other tasks that are significantly more taxing to this machine however my Automapper constructors constantly cause this lag. 

Here is an example of my general set up.

`public static class Mapper
    {
        public static MapperConfiguration Config { get; }
        public static IMapper GetMapper()
        {
            return Config.CreateMapper();
        }

        static Mapper()
        {
            Config = new MapperConfiguration(cfg =>
            {
                
                cfg.CreateMap<Models.ChangeOrders.ChangeOrderStatus, ChangeEventStatus>()
                    .ForMember(dest => dest.ShowInSelected, opt => opt.Ignore())
                    .IgnoreAllSdbBaseSource()
                    .ReverseMap();
}`

**Comment by lbargaoanu** [comment]
Maybe smth like https://github.com/AutoMapper/AutoMapper/issues/1693#issuecomment-270148644. But you should profile it to confirm.
DontInline was renamed to MapAtRuntime.

**Comment by lbargaoanu** [comment]
But now I see that your problem is while editing your code, not at runtime? :) If that's the case you should ask your question in a VS forum.

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/wiki/Configuration#profile-instances.

**Comment by jbogard** [comment]
I've had this happen in WinForms projects with InitializeComponent being too large. Not really an AutoMapper problem as much as it is Roslyn and VS.

**Comment by DerekScheller** [comment]
So I have split all of my mappings into Profiles and added them to the
Repository that they belong to. I then used cfg.AddProfile() to add them to
my static constructor. Now all of my repositories are having the same issue
that my Static constructor previously had when the mappings were all
contained in it.
