### ISSUE TITLE
The type appears in two structurally incompatible initializations within a single LINQ to Entities query

### ISSUE THREAD

**Issue by nim84** [AutoMapper/AutoMapper#2090]
I'm Trying to map the entity from the parent entity which has same properties. 
Ex:
Product.CS
```
public string Name{get;set;}
public Supplier Supplier {get;set;}
```

Supplier .CS
```
Public string Name{get;set;}
Public string Id{get;set;}
```

Due to the project requirement I'm in the situation to duplicate the same Product and Supplier entity with different namespace. The Product and supplier entity populates the data from database using EF. 

Currently I'm using Automapper to map the object. The only difference between objects is just the namespace. 

Code:
```
Mapper.CreateMap<namespace1.Product, namespace2.Product>();

IQueryable<Product> products= context.Products;
products.ProjectTo<Product>();
```

When I execute the code it throws,
The type 'namespace2.Product' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order.

After referred couple of blogs I have used  ExplicitExpansion,
Mapper.CreateMap<namespace1.Product, namespace2.Product>()
.ForMember(src => src.Supplier, conf => conf.ExplicitExpansion());

It resolved the issue but I have tried expanding the /Products?$expand=Supplier the same issue occurred again. What could be the potential issue? Any suggestion..

**Comment by lbargaoanu** [comment]
The suggestion is to not have two structurally incompatible initializations... :) If you feel that there should be only one and AM is to blame, just look at the ProjectTo expression in the debugger and you'll have your answer. I can do that for you if you can provide a repro, a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by nim84** [comment]
I referred the issue #790 and my case is also same. When data pulled from EF we don't have any issues even if there is a circular dependency.

We have to simulate the same DTO object in another project in the same solution which is going to be exposed as a service. So, if I have a WidgetDto in namespace1 and have to replicate the same in namespace2. We haven't created sub Dto as mentioned in #790 and it's loading the data using <IQueryable>. The issue is happening when there is a mapping from namespace1 to namespace2.

Mapper.CreateMap<Widget,namepace1.WidgetDto>() - doesn't throw an error.

But,
Mapper.CreateMap<namespace1.WidgetDto, namespace2.WidgetDto>(); - throws an error. We haven't changed anything on namespace2.WidgetDto. It's same like namespace1.WidgetDto. I can create a sub Dto as mentioned in #790, but namepace1.WidgetDto is loading without sub Dto. 

What could be the reason for "The type 'namespace2.WidgetDto' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order."?
