### ISSUE TITLE
Nested Interface types not Mapped.

### ISSUE THREAD

**Issue by ErikPhilips** [AutoMapper/AutoMapper#2091]
### Source/destination types

	public interface IPersonDest
	{
		string Name { get; }
	}

	public interface IPersonSrc
	{
		string Name { get; }
	}

	public interface IVehicleDest
	{
		IPersonDest Owner { get; }
	}

	public interface IVehicleSrc
	{
		IPersonSrc Owner { get; }
	}

	public class PersonDest : IPersonDest
	{
		public string Name { get; set; }
	}

	public class PersonSrc : IPersonSrc
	{
		public string Name { get; set; }
	}

	public class VehicleDest : IVehicleDest
	{
		public IPersonDest Owner { get; set; }
	}

	public class VehicleSrc : IVehicleSrc
	{
		public IPersonSrc Owner { get; set; }
	}

### Mapping configuration

	var config = new MapperConfiguration(cfg =>
	{
		cfg.CreateMap<IPersonSrc, IPersonDest>().As<PersonDest>();
		cfg.CreateMap<IVehicleSrc, IVehicleDest>().As<VehicleDest>();
	});
	config.AssertConfigurationIsValid();
	var mapper = config.CreateMapper();

### Expected behavior

I would expect `vehicleDest.Owner` to not be null and be of Type `VehicleDest`.  This works for concrete types but (works erratically in my personal code) does not work as expected in this example.

### Actual behavior

`vehicleDest.Owner` is null.

### Steps to reproduce

	var personSrc = new PersonSrc { Name = "George Washington" };
	var vehicleSrc = new VehicleSrc { Owner = personSrc };

	var vehicleDest = mapper.Map<IVehicleDest>(vehicleSrc);

**Comment by lbargaoanu** [comment]
You need setters on the properties in the interfaces.

**Comment by lbargaoanu** [comment]
It would also work if you had maps between the source interfaces and the destination classes, but I'm guessing that's not what you want.

**Comment by ErikPhilips** [comment]
Not sure what happened.  I swear I added...

    cfg.CreateMap<IPersonSrc, PersonDest>();
    cfg.CreateMap<IVehicleSrc, VehicleDest>();

And had the same unsuccessful result.  However, this does work as intended.
