### ISSUE TITLE
Mapping between two nullable enums doesn't work in some cases

### ISSUE THREAD

**Issue by ademchenko** [AutoMapper/AutoMapper#2093]
Suppose we have two enums - EntityEnum and EntityEnumDto and we want to map nullable EntityEnum property to nullable EntityEnumDto property.  

### Source/destination types

```csharp
 public enum EntityEnum
    {
        Item1,
        Item2
    }

    public class Entity
    {
        public EntityEnum? Prop1 { get; set; }
    }

    public enum EntityEnumDto
    {
        Item1,
        Item2
    }

    public class EntityDto
    {
        public EntityEnumDto? Prop1 { get; set; }
    }
```

### Tests

```csharp
  [Test]
        public void EnumMappingTests_Failed()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<EntityEnum?, EntityEnumDto?>();
                cfg.CreateMap<Entity, EntityDto>();
            });

            configuration.AssertConfigurationIsValid();

            var mapper = configuration.CreateMapper();

            var result = mapper.Map<EntityDto>(new Entity { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }

 [Test]
        public void EnumMappingTests_Success()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                //Removed enum map
                //cfg.CreateMap<EntityEnum?, EntityEnumDto?>();
                cfg.CreateMap<Entity, EntityDto>();
            });

            configuration.AssertConfigurationIsValid();

            var mapper = configuration.CreateMapper();

            var result = mapper.Map<EntityDto>(new Entity { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }
```

### Actual behavior

If we create map from EntityEnum? to EntityEnumDto? then the mapping from Prop1 to Prop2 stops work (EnumMappingTests_Failed test prints):
 Expected: Item1
  But was:  null

if we do not create that map then mapping from Prop1 to Prop2 works (see EnumMappingTests_Success).

### Expected behavior

In both cases mapping should work properly.

### Additional info

I know that there's no need to create mapping between enums but in my real case Prop1 is a property of generic class and I don't actually know if that is a enum or not while creating mapper configuration.

**Comment by lbargaoanu** [comment]
You don't need the map between the enums.

**Comment by lbargaoanu** [comment]
Again, you don't need the map between the enums. Because if you create that map, you need a type converter to map between the enum values. That's the way things work.

**Comment by ademchenko** [comment]
lbargaoanu, especially to pay attention on my case I have written Additional info where I say that I don't have an ability to decide whether it's a enum or not since the type is a generic paramater. I am not following the idea why things work so.

**Comment by lbargaoanu** [comment]
You can [tell](https://msdn.microsoft.com/en-us/library/system.type.isenum(v=vs.110).aspx) if it's an enum.

**Comment by ademchenko** [comment]
I don't want to create mapping override for every of my concrete classes. 
Please, see the example:
 ```
public enum EntityEnum
    {
        Item1,
        Item2
    }

    public class Entity<TProp>
    {
        public TProp Prop1 { get; set; }
    }

    public enum EntityEnumDto
    {
        Item1,
        Item2
    }

    public class EntityDto<TProp>
    {
        public TProp Prop1 { get; set; }
    }
```
I have lots of implementations of Entity<TProp> where sometimes TProp is a enum, sometimes is a class, sometimes is a nullable enum.

And I can't understand from the user perspective while the first test works and the second is not:
```
  [Test]
        public void EnumMappingTests_Success_WhenEnum()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<EntityEnum, EntityEnumDto>();
                cfg.CreateMap(typeof(Entity<>), typeof(EntityDto<>));
            });

            configuration.AssertConfigurationIsValid();

            var mapper = configuration.CreateMapper();

            var result = mapper.Map<EntityDto<EntityEnumDto>>(new Entity<EntityEnum> { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }

```
and 
 ```
[Test]
        public void EnumMappingTests_Failed_WhenNullableEnum()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<EntityEnum?, EntityEnumDto?>();
                cfg.CreateMap(typeof(Entity<>), typeof(EntityDto<>));
            });

            configuration.AssertConfigurationIsValid();

            var mapper = configuration.CreateMapper();

            var result = mapper.Map<EntityDto<EntityEnumDto?>>(new Entity<EntityEnum?> { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }
```
Do you really think it's a correct and consistent behaviour?

**Comment by lbargaoanu** [comment]
A generic map seems a good idea.

**Comment by ademchenko** [comment]
This idea doesn't work, it's exactly the bug I am talking about:
```
public class Tests
    {
        [Test]
        public void EnumMappingTests_Failed_WhenNullableEnum()
        {
            var mapper = CreateMapper<EntityEnum?, EntityEnumDto?>();

            var result = mapper.Map<EntityDto<EntityEnumDto?>>(new Entity<EntityEnum?> { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }

        [Test]
        public void EnumMappingTests_Success_WhenEnum()
        {
            var mapper = CreateMapper<EntityEnum, EntityEnumDto>();

            var result = mapper.Map<EntityDto<EntityEnumDto>>(new Entity<EntityEnum> { Prop1 = EntityEnum.Item1 });

            Assert.AreEqual(EntityEnumDto.Item1, result.Prop1);
        }

        private static IMapper CreateMapper<TProp, TPropDto>()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<TProp, TPropDto>();
                cfg.CreateMap(typeof(Entity<>), typeof(EntityDto<>));
            });

            configuration.AssertConfigurationIsValid();

            return configuration.CreateMapper();
        }
    }
```

**Comment by lbargaoanu** [comment]
It would, but the enum map ruins everything :)

**Comment by ademchenko** [comment]
It works with enum map when enum is not nullable. So, could you reopen this issue?

**Comment by lbargaoanu** [comment]
What you're doing is not a supported use case, there is no bug here. @jbogard will reopen it if he disagrees.

**Comment by ademchenko** [comment]
Okay, thanks, waiting @jbogard then since it's look like very inconsistent and limiting behaviour.

**Comment by jbogard** [comment]
I'm still not understanding why you can't remove the CreateMap from the enum values. Do you just have the open map defined in your actual app? Are you actually creating the MapperConfiguration all the time, or is this just for a test?

**Comment by ademchenko** [comment]
I have a generic infrastructure. Roughly saying, for any type _TProp_ I have a singleton converter, say, EntityConverter<T>. So, then I convert any Entity<TProp> like EntityConverter<TProp>.ConvertToDto(). But the issue is that in that infrastructure I don't have prior knowledge regarding TProp. CreateMap<TProp, TPropDto> works fine and is necessary for all types except enums and nullable enums. But it works fine for enums as well (it's not necessary but at least not buggy). The only issue is that it stops working with nullable enums which is strange to me from the perspective of consistency.

**Comment by jbogard** [comment]
Keep in mind you're really not supposed to call CreateMap for primitives unless you're doing a custom conversion or projection. CreateMap means "don't use built-in mappers, use property-by-property mapping"

And nullables are tricky of course, as the types lie at runtime.

So I'd still say - don't call CreateMap except for when you know those types are classes that you actually intend to map. Don't call it for collections, don't call it for enums, don't call it for primitives/strings. Behavior when you call CreateMap with primitive types and rely on the internal property mapping behavior is unknown, unpredictable, and unsupported. Don't do it.

We could try to detect it by comparing the types you're calling CreateMap with against previously defined IObjectMappers (the things that do enum -> enum mapping, collections etc.) but it's better to assume that when someone calls CreateMap, they're intending to Create A Map and wouldn't call CreateMap unless they wanted to Create A Map.

I would still suggest not calling CreateMap for the aforementioned types. How can you do this? What about detecting on your side and not calling CreateMap for the property types?

```csharp
        private static IMapper CreateMapper<TProp, TPropDto>()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                if (!typeof(TProp).IsEnum)) /* etc */
                     cfg.CreateMap<TProp, TPropDto>();
                cfg.CreateMap(typeof(Entity<>), typeof(EntityDto<>));
            });

            configuration.AssertConfigurationIsValid();

            return configuration.CreateMapper();
        }

```

**Comment by ademchenko** [comment]
Okay, Jimmy, thanks, I'll do as you advise, but I don't find the API with creating maps straightforward then. It doesn't take into account generic cases. And your example is not complete, because I need:

> Don't call it for collections, don't call it for enums, don't call it for primitives/strings.

I think, it's not a good way.

**Comment by jbogard** [comment]
No, it does not take into account generic cases, it's meant to be called imperatively. What you're really looking for is a different API meant for generic cases. CreateMap was never meant for the scenario you're looking at.

**Comment by ademchenko** [comment]
Okay, is there such API or is it going to be?

**Comment by jbogard** [comment]
Is there an API? No. Is there going to be? We've thought about it but don't have concrete plans. We'd thought about some sort of "scanning" API to automatically register maps, and @TylerCarlson1 added an API for conventions but I don't know if it fits.

Realistically, I would want a proposal for an API to come from the community. I wouldn't use it/don't need it so I don't want to build something based off a guess.

**Comment by TylerCarlson1** [comment]
First off you shouldn't keep making the mapper each time.  It's a waste.
You should make a mapper like the example below and just pass that around
```
var mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;
            }).CreateMapper();
```
Or use Mapper.Initialize and use the `Mapper.Map` function call.
You are creating the maps when needed, so this just tells AutoMapper to make the mappings that are needed when you first call them and will cache and re-use them.
