### ISSUE TITLE
ProjectTo issue when using NotMapped/Computed property in Source.

### ISSUE THREAD

**Issue by Harish-Sundaram** [AutoMapper/AutoMapper#2094]
I am getting the error only when I am using ProjectTo, I could not understand the underlying issue.
"The specified type member 'Tags' is not supported in LINQ to Entities. 
		Only initializers, entity members, and entity navigation properties are supported."
We could do this manipulation in DTO as well, but I should stick to doing the manipulation in entity side only. Do let me know the ways or work around I could handle this without upgrading the version. TIA

### Source/destination types
Source Entity:
```csharp
 public class Template : IEntity<int>
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public string _Tags { get; set; }

        [NotMapped]
        public List<string> Tags
        {
            get { return _Tags == null ? null : JsonConvert.DeserializeObject<List<string>>(_Tags); }
            set { _Tags = JsonConvert.SerializeObject(value); }
        }       
    }
```
Entity Config:
```csharp
internal sealed class TemplateConfig : EntityTypeConfiguration<Template>
    {
        public TemplateConfig()
        {
            Ignore(x => x.Tags);
            HasKey(x => x.Id)
                .Map(m =>
                {
                    m.ToTable("Template");
                    m.Property(x => x.Id).HasColumnName("ID");
                    m.Property(x => x.Name).HasColumnName("Name");
                    m.Property(x => x._Tags).HasColumnName("Tags");
                });
        }
    }
```

Destination DTO:
```csharp
public class Template
    {
        public int Id { get; set; }

        public string Name { get; set; }
		
        public List<string> Tags { get; set; }
    }
```

### Mapping configuration

```csharp
Mapper.CreateMap<Template, DTO.Template>();               

Mapper.CreateMap<DTO.Template, Template>(); 
```

### Expected behavior

The computed value of Tags property of entity needs to be mapped to the Tags property of the DTO, but this works fine when I am doing the normal way, but it doesn't when I am trying to use ProjectTo

### Actual behavior

I am getting the error only when I am using ProjectTo, I could not understand the underlying issue.
"The specified type member 'Tags' is not supported in LINQ to Entities. 
		Only initializers, entity members, and entity navigation properties are supported."

### Steps to reproduce
//These are just for information, but getting error only when using ProjectTo. (Ignore about the OData thing)
```csharp
public virtual async Task<IQueryable<TDto>> Get(ODataQueryOptions<TDto> query)
        {
            try
            {
                var expands = query.GetExpandedPropertyNames();
                //Assume the collection has the data from db
                var test = Collection.ToList();
                //getting the exception here
                return await Collection.ProjectTo<TDto>(null, expands).AsTask();
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

//Controller method
public override async Task<IQueryable<Template>> Get(ODataQueryOptions<Template> query)
        {
            try
            {
               List<Template> result = (await base.Get(query)).ToList();

                return result.AsEnumerable().AsQueryable();
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
```

**Comment by TylerCarlson1** [comment]
Move your JsonConvert to the DTO Tags property and map _Tags over with projection, and block _Tags from serializing.  That's the only way I see it cause EF won't play nice with what you have now, so you have to put it in the Dto.  ProjectTo will not support JsonConvert at all

**Comment by Harish-Sundaram** [comment]
Even I thought the same, so to confirm if that is causing the issue I did try removing the serialization part from that property just kept it as 
`
[NotMapped]
public List<string> Tags { get; set;} ` 
Did not work either. Got the same error.
@TylerCarlson1 
Moving that to DTO works fine I had tried, but I want this to happen at the entity level. 
So, is there other ways? TIA

**Comment by lbargaoanu** [comment]
You need to tell AM explicitly to ignore Tags in the Dto. Maybe it should consider NotMapped by default, but it doesn't right now.

**Comment by Harish-Sundaram** [comment]
I actually tried ignoring the Tags in Dto, in that case I don't get the error, but I don't get any data in the Tags List, it is just an empty list. Like this. My problem is only when using ProjectTo, in other case without even using Ignore it works fine.
```
Mapper.CreateMap<Template, DTO.Template>()
.ForMember(dest => dest.Tags, opts => opts.Ignore());
```

**Comment by lbargaoanu** [comment]
Yes, of course :) You need the same trick as in your entity.

**Comment by Harish-Sundaram** [comment]
@lbargaoanu 
I did not get you, could you please explain what is that I need to do? TIA

**Comment by lbargaoanu** [comment]
Forget about AM. Try writing a query like this

    context.Entities.Select(e=>new Dto { Property = e.Property });

When you're done, we'll see how we can get AM to write that for you.

**Comment by Harish-Sundaram** [comment]
@lbargaoanu Yeah, querying it does not have a problem at all, it works fine. Issue only when ProjectTo

**Comment by lbargaoanu** [comment]
OK, show us the LINQ query.

**Comment by Harish-Sundaram** [comment]
Something like this works . With the same configuration as mentioned above.
``` csharp
var result = portalUow.Repository<Template>().ToList();
return result.Map<Template>().AsEnumerable().AsQueryable();
```
Result:
[
  {
    "Id": 1,
     "Name": "Temp1",
    "_Tags": "[\"Tag1\", \"Tag2\"]",
    "Tags": [
      "Tag1",
      "Tag2"
    ]
  },
  {
    "Id": 2,
    "Name": "Temp2",
    "_Tags": "[\"Tag3\", \"Tag4\"]",
    "Tags": [
      "Tag3",
      "Tag4"
    ]
  }
]

But this fails, gives same error as automapper
`var result = portalUow.Repository<Template>().Select(x => x.Tags).ToList();`

@lbargaoanu Is this what you asked me, or had I misunderstood ur question?

**Comment by lbargaoanu** [comment]
You misunderstood.

    portalUow.Repository<Template>().Select(x => new DTO.Template { ??? });

**Comment by TylerCarlson1** [comment]
Tags will never work in EF ProjectTo, or Select statements, because it doesn't follow the rules, as the exception message says.  You will have to get rid of Tags property from EF Entity and move it into your DTO is the only way to support ProjectTo.

**Comment by Harish-Sundaram** [comment]
@lbargaoanu Am sorry, I still didn't understand :(
```
var result = _portalunitofWork.Repository<Template>().Select(x => new DTO.Template{ Tags = x.Tags })
                      .ToList();
```
Do you mean this, it throws error .

**Comment by Harish-Sundaram** [comment]
@TylerCarlson1 I can do this thing in DTO, I had tried it works, but I must stick to keeping in the entity. If doing this in the entity is not plausible at all, then Please do share me the link at least. I need to justify to others, I searched could not find a solid proof.

**Comment by lbargaoanu** [comment]
Well, yes :) That's exactly my point. So write a query that works without AM and does what you want and then we'll translate that to work with AM.

**Comment by TylerCarlson1** [comment]
@Harish-Sundaram I think the exception message and the fact that your select test getting the same exception is all the proof you need.  It just strait up isn't supported in EF. (Test repeated below)
```
var result = _portalunitofWork.Repository<Template>().Select(x => new DTO.Template{ Tags = x.Tags })
                      .ToList();
```

This is clearly an EntityFramework issue, and you would need to take it up with them.  I think they have all but stopped EF 6 to work on EF-Core.  If you want to make a pull request to fix this in EF you can I guess but I don't see this being fixed.  Maybe EF-Core might fix it eventually but I doubt it.

**Comment by Harish-Sundaram** [comment]
@TylerCarlson1 @lbargaoanu Thanks for your comments. I solved the issue by adding a ToList before using ProjectTo. Something like this worked. I guess there is no issue with the auto mapper in dealing with a computed value or a Json serialization.

```
public virtual async Task<IQueryable<TDto>> Get(ODataQueryOptions<TDto> query)
        {
            try
            {
                var expands = query.GetExpandedPropertyNames();
                //Assume the collection has the data from db
                var test = Collection.ToList().AsQueryable();
                //getting the exception here
                return await test.ProjectTo<TDto>(null, expands).AsTask();
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }
```

**Comment by lbargaoanu** [comment]
You should simply use Map instead. ToList followed by ProjectTo doesn't really make sense.
