### ISSUE TITLE
Interfaces not supported?

### ISSUE THREAD

**Issue by maurosampietro** [AutoMapper/AutoMapper#2095]
### Source/destination types

```csharp
    public class IA : I
    {
        public int MyProperty { get; set; }
    }

    public class IB : I
    {
        public int MyProperty { get; set; }
    }

    public class MyType
    {
        public I Interface { get; set; }
    }
```

### Mapping configuration

```csharp
   var source = new MyType() { Interface = new IB() { MyProperty = 1 } };

   AutoMapper.Mapper.Initialize( cfg => { cfg.CreateMissingTypeMaps = true; } );
   var target = AutoMapper.Mapper.Map<MyType>( source );
```

### Expected behavior

A deep copy of source

### Actual behavior

'target', which should be a deep copy of 'source', shares the same references with 'source'.
```csharp
Object.ReferenceEquals( source.Interface, target.Interface ) == true; //this should be false
```

**Comment by lbargaoanu** [comment]
Try it without CreateMissingTypeMaps.

**Comment by maurosampietro** [comment]
Setting CreateMissingTypeMaps=false does not change the actual behavior

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by maurosampietro** [comment]
Something like this? https://gist.github.com/maurosampietro/7d95ccc1ccdd040169e5fe303b87e60d

**Comment by lbargaoanu** [comment]
Yes, just wanted to make sure. You didn't create any maps :) So mapping to self is just an assignment. Creating the required maps will get you the behavior you want. But keep in mind that self mapping is not exactly what AM is for, so you'll just have to live with whatever works.

**Comment by maurosampietro** [comment]
If I manually create a map, still i don't get the result.
How did you get my gist to work properly?

````csharp
   AutoMapper.Mapper.Initialize( cfg => cfg.CreateMap<MyType, MyType>() );
````
(Sorry but what's CreateMissingTypeMaps= true is for if I still have to map manually?!)

**Comment by lbargaoanu** [comment]
You shouldn't be using CreateMissingTypeMaps. Search the issues for reasons why. You also need to map that interface somehow. For example:

     cfg.CreateMap<I, I>().As<IA>();

**Comment by maurosampietro** [comment]
Telling the mapper what concrete type to use make perfect sense .
Thank you, it works now.
