### ISSUE TITLE
ArgumentException when trying to map a ViewModel List to Domain List

### ISSUE THREAD

**Issue by ryanbuening** [AutoMapper/AutoMapper#2096]
I'm trying to map my view model list that contains updated values to my existing domain list. I'm trying the following:

```csharp
var outbuildings = await api.GetOutbuildings(quoteId); //returns List<Domain.Models.Outbuilding>
var outbuildingsIEnumberable = _mapper.Map<IEnumerable<Outbuilding>, IEnumerable<Domain.Models.Outbuilding>>(viewModel.Outbuilding, outbuildings);
```
Maybe I'm going about this incorrectly, but it appears to map correctly if the outbuildings do not have values in the Limit. 

### Source/destination types

```csharp
// source
public class Outbuilding
{
	public string Id { get; set; }

	[DisplayName("Other Structure Description"), MaxLength(42)]
	public string Description { get; set; }

	[DisplayName("Type of Construction")]
	public Domain.Models.Outbuilding.ConstructionTypes? ConstructionType { get; set; }
}

// domain/destination
public class Outbuilding
{
	public string Id;
	public ConstructionTypes? ConstructionType;
	public int? Limit;
	public string Description;

	public enum ConstructionTypes
	{
		Frame, Masonry, MasonryVeneer
	}
}
```

### Mapping configuration

```csharp
CreateMap<Domain.Models.Outbuilding, Features.AdditionalInfo.Outbuilding>().ReverseMap();
```

### Expected behavior

I expected it to map.

### Actual behavior

ArgumentException: Method 'Int32 Add(System.Object)' declared on type 'System.Collections.IList' cannot be called with instance of type 'System.Collections.Generic.IEnumerable`1[VacantRating.Domain.Models.Outbuilding]'

### Steps to reproduce
Errors on this line:
```csharp
var outbuildingsIEnumberable = _mapper.Map<IEnumerable<Outbuilding>, IEnumerable<Domain.Models.Outbuilding>>(viewModel.Outbuilding, outbuildings);
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by TylerCarlson1** [comment]
Problem is it can't map because outbuildings is an Enumerable instead of an IList.

AM's default behavior with lists is to clear out existing list, or make a new one, and add the items to the list.  Since it's enumerable it's trying to Add to it and can't and that's your exception method.

Mapping back to the outbuildings won't update the existing objects, and will just create new ones even if you get past this exception. AutoMapper.Collections can help with this by identifying which map to which by ID if that's what you are trying to achieve.

**Comment by ryanbuening** [comment]
Thanks. Will look into alternative methods.

**Comment by lbargaoanu** [comment]
I think it should use the runtime types, it uses them for matching so it should use them when mapping.

**Comment by ryanbuening** [comment]
@TylerCarlson1 - Does AutoMapper.Collections work with ASP.NET Core? I tried adding it to my project, but I'm not able to reference cfg.AddCollectionMappers()

**Comment by TylerCarlson1** [comment]
It has .Net Core support; .NET standard v1.1 & v1.3 just like AutoMapper has on nuget.  Maybe it's not up to date.  I don't use .Net Core personally and someone else added it.  Also 3.0.0 should be what you are using for 6.0.2
Another issue was here https://github.com/AutoMapper/AutoMapper.Collection/issues/34.

@jbogard any insights on what might be up with the .NET Core issue?

**Comment by jbogard** [comment]
I just tried it with a new ASP.NET Core app. This works just fine for me:

```
services.AddAutoMapper(cfg => {
    cfg.AddCollectionMappers();
});
```

I had to add the right "using" statements of course. But works just fine for me, targeting `netcoreapp1.0`.

**Comment by ryanbuening** [comment]
@TylerCarlson1 , @jbogard - Sorry for the delayed response but AutoMapper.Collection is working perfectly in my ASP.NET Core app targeting .NETCoreApp 1.1. I just needed to add the code outlined above in my Startup.cs. Thank you.
