### ISSUE TITLE
ResolveUsing problem

### ISSUE THREAD

**Issue by lockedscope** [AutoMapper/AutoMapper#2102]
Using the version 6.0.2.
With a scenario similar to following, if return value of ResolveUsing is null, exception(Missing type map configuration or unsupported mapping) is raised.
It works fine when non-null object is returned.
So should i assign to destination member if it will be null or what should i do?
```
var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<Source, Dest>()
                        .ForMember(d => d.Value1, opt => opt.ResolveUsing((source, d, dMember, context) => (int)context.Options.Items["Item"] + source.Value1));
                });
```
https://github.com/AutoMapper/AutoMapper/blob/c968f34e58eed73e7cb40e8e52849408693eddb6/src/UnitTests/ContextItems.cs

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by lockedscope** [comment]
I actually find the problem. One of the field is Dictionary<string, string>and not explicitly casting causes the problem.
Check the following, 
https://gist.github.com/lockedscope/6d9ed9b9e61edf45bfed11585cadda82

**Comment by lbargaoanu** [comment]
I see it now. It's a declared vs runtime type thing. I'm guessing it could be fixed. You already have a workaround :)

**Comment by lockedscope** [comment]
Actually it works with null string without explicit casting. I will dig deep the automapper source to find out reason.

**Comment by lbargaoanu** [comment]
It's not a question of types after all. When the source is null, the type to use is the one you specify, object. IMO the fix would be another null check. When no map is found, null could be mapped to the default destination value. Something like this already happens for some Map overload, but it doesn't cover this case.
