### ISSUE TITLE
Map a List to a Grouped DTO

### ISSUE THREAD

**Issue by piyey** [AutoMapper/AutoMapper#2103]
I have a list of entities and I need to map it to a DTO, but grouped.

My entity Class:
```
Class myEntity
{
      public int id {get;set;}
      public double cost {get;set;}
}
```
My DTO Class
```
Class myEntityDTO
{
      public int id {get;set;}
      public double cost {get;set;}
}
```

My mapping:
```
CreateMap<myEntity, myEntityDTO>()
                //register all properties mapped
                ;
```

```
var entities = new List<myEntity>();
// fill the list
//  [
//          {1,50},
//          {1,30},
//          {1,25},
//          {2,80},
//          {2,20},
//          {2,45},
//          {2,38},
//          {3,10},
//          {3,15}
//   ]
Mapper.Map<List<myEntityDTO>>(entities);
```

I need to group my list of myEntity (by id for example, and sum cost), so, my DTO should be like this:
[
    {id: 1, cost: 105},
    {id: 2, cost: 183},
    {id: 3, cost: 25}
]

I hope I made myself clear, my english is not good.

Thanks in advance.
Regards!

**Comment by lbargaoanu** [comment]
You don't need AM for that, just use LINQ.

**Comment by piyey** [comment]
I can do all projection with linq, but the idea is to use AM. Maybe You didn't understand my question. I do the grouping with linq, what I need to know is How to map that grouped result to my DTO.

**Comment by jbogard** [comment]
Have you tried creating a map from the IGrouping to your DTO?

If you do the projection without AutoMapper that should tell you what map
to create.

**Comment by lbargaoanu** [comment]
Even for mapping the grouping to the DTO, I still think AM wouldn't be that useful because then you would have to customize the default map and it's not auto anymore, is it? Just LINQ seems the best.

**Comment by piyey** [comment]
@lbargaoanu , I do customize the default map for every DTO, my goal is to project automatically, not to create the map automatically. Anyway, thanks for your help.

Regards!

**Comment by lbargaoanu** [comment]
The more you customize the default map, the less useful AM is. For IGrouping you would use nothing from the default map. That's why I think simply using LINQ makes more sense.

**Comment by piyey** [comment]
@lbargaoanu , what do you mean with "default map"?

**Comment by lbargaoanu** [comment]
The result of CreateMap :) Without any map specific customizations (MapFrom for example).

**Comment by piyey** [comment]
I have all my Mapping with specific customizations.
As I mentioned before, I use AM for automatic projection, not for automatic map.

Anyway, I solved my problem, just specifying the CreateMissingTypeMaps property to  true:

`CreateMissingTypeMaps = true;`

Thanks for your attemption.
Regards!

**Comment by jbogard** [comment]
In the future, with ProjectTo, if you find it's not working, try it WITHOUT
AutoMapper first with a manual Select. That should point you in the right
direction.

**Comment by piyey** [comment]
I don't use ProjectTo method, My Application layer doesn't know about EF nor AM.

**Comment by jbogard** [comment]
Ah, I think I'd still try to write the Select without AutoMapper. That
tells you what types to map, and how.

CreateMissingTypeMaps here would be a bit of a hack.

**Comment by piyey** [comment]
Yes @jbogard, I do the Select with Linq, then I project to my DTO where it profile use CreateMissingTypeMaps = true;
