### ISSUE TITLE
What about UseSourceValue ?

### ISSUE THREAD

**Issue by cdie** [AutoMapper/AutoMapper#2104]
I'm currently using AutoMapper between Domain and Persistence layers for some contexts.

In some other of our contexts, we use basic CRUD system (it means that Domain = Persistence).
This kind of objects are a kind of SharedKernel for our other context, so we would like to use a sort of 
.UseSourceValue, to use the current object reference.

Actually, we've found a kind of workaround like

`.ForMember(a => a.LettreCle, opt => opt.ResolveUsing(s => s.LettreCle))`

However, what it's really strange, is when I do a
`object.ReferenceEquals(object1.Ref1, object1.InnerObj.Ref1)`, I have a true value, and when I do a `object.Reference(mappedObject1.Ref1, mappedObject1.InnerObj.Ref1)`, I have a false value, whereas `object.ReferenceEquals(object1.Ref1, mappedObject1.Ref1)` is true ...

This kind of behavior is currently making EF Core complaining

Is there something I'm doing wrong here ? 
Can you consider that `opt.UseSourceValue()` method to use same reference value ?

**Comment by lbargaoanu** [comment]
Try PreserveReferences.

**Comment by cdie** [comment]
@lbargaoanu Thanks for this quick answer.
I'll try it tomorrow morning and let you know

**Comment by cdie** [comment]
Hey, it seems to work as expected for my issue.

However, it was not really obvious and I haven't seen any references of this method into the wiki.
Have I missed something ?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#circular-references
Feel free to add it elsewhere.
