### ISSUE TITLE
IQueryable and AutoMapper

### ISSUE THREAD

**Issue by gargimitra** [AutoMapper/AutoMapper#2105]
Hi,
I am using AutoMapper 6.0.2. I am trying to use AutoMapper to map my DTO to external model. 
I created the mapping config to map both the models as below:
var mappingConfig = new MappingConfiguration(
cfg =>
cfg.CreateMap<ModelA, ModelB>().ForMember(...)
);
IMapper mapper = mappingConfig.CreateMapper();

Then in my controller code, I apply the mapping as follows:
var query = GetDataasModelA().AsQueryable();
var modelB = query.ProjectTo<ModelB>(mappingConfig);

This line, just creates a new instance of ModelB instead of mapping the values in query to ModelB.
What am I missing here? Need urgent help.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by gargimitra** [comment]
The reason I posted here was I was unable to find a document which goes through the details of how to deal with IQueryables for AutoMapper. If you could have pointed out to any such doc, it would have been helpful

**Comment by jbogard** [comment]
Doing AsQueryable then ProjectTo is pointless, just do Mapper.Map.
