### ISSUE TITLE
ReverseMap MemberList differs from Documentation

### ISSUE THREAD

**Issue by pfeigl** [AutoMapper/AutoMapper#2106]
The documentation at https://github.com/AutoMapper/AutoMapper/wiki/Configuration-validation says, that ReverseMap always defaults to MemberList.None

And while the MappingExpression<TSource, TDestination> does so, the non-generic MappingExpression does not.

See https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Configuration/MappingExpression.cs#L93

Is there any specific reason behind this? Also the MemberList is only defined as a Getter in the object and not described in the interface, which makes it practically impossible to disable or change MemberList validation when using ReverseMap

**Comment by lbargaoanu** [comment]
It seems to be an omission. A PR (with a relevant test) is welcome.

**Comment by jbogard** [comment]
Yeah I think originally it was as the docs said, but then I changed it to
MemberList.None. The idea being you've already validated the one direction,
why do it twice?

**Comment by pfeigl** [comment]
The docs actually say "MemberList.None", so this is all fine. It's just there is a little code left, which uses "MemberList.Source".

I checked the changes today, the actual change from Source to None came with a commit, which supposedly just fixed tabs vs white-spaces ;-) Anyways, this change was only applied to the generic MappingExpression, but not the non-generic one.

I'll work on a PR and send it as soon as I have some time for it.

**Comment by jbogard** [comment]
SNEAKY

**Comment by jbogard** [comment]
Fixed the wiki.
