### ISSUE TITLE
Lazy Loading after mapping

### ISSUE THREAD

**Issue by chrysikos** [AutoMapper/AutoMapper#2113]
I use Entity Framework and I want to map navigation properties to my DTO's.
So, my question is EF's navigation properties by default have Lazy loading, its possible  with auto mapper 
after mapping to have the same functionality of lazy loading to my DTO's.

Here is my DTO's : 
```csharp
    public class CustomerDTO
    {
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public ICollection<Order> Orders { get; set; }
     }

    public class OrderDTO
    {
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public int? EmployeeID { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public Employee Employee { get; set; }
        public Customer Customer { get; set; }
        public  ICollection<OrderDetail> OrderDetails { get; set; }
    }

    public class OrderDetailDTO
    {
        public int OrderID { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public Order Order { get; set; }
    }
    
     public class EmployeeDTO
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public ICollection<Order> Orders { get; set; }
    }
```

Persistent Models:
```csharp
    public class Customer
    {
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public ICollection<Order> Orders { get; set; }
     }

    public class Order
    {
        public int OrderID { get; set; }
        public string CustomerID { get; set; }
        public int? EmployeeID { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public Employee Employee { get; set; }
        public Customer Customer { get; set; }
        public  ICollection<OrderDetail> OrderDetails { get; set; }
    }

    public class OrderDetail
    {
        public int OrderID { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public Order Order { get; set; }
    }
    
     public class Employee
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public ICollection<Order> Orders { get; set; }
    }
```

**Comment by lbargaoanu** [comment]
But if you could do smth like that, those wouldn't be DTO-s anymore, because they would need the DB connection. What are you trying to do?

**Comment by chrysikos** [comment]
My intention is to separate completely the ORM Layer from my model. One reason to do this is because maybe in the future the Project Leader will decide to change the ORM. So, to achieve this, I don't want my repositories to return or take Persistent Model directly but Domain Model which will mapped to PM and after submitted for the specific job to the ORM?

**Comment by lbargaoanu** [comment]
Having DTO-s lazy load stuff goes against the decoupling you're trying to achieve. Adding another layer over your ORM complicates things. And it only makes sense if this extra layer adds real value. And if it's able to do that, certainly the shape of those objects would not be close to the shape of your DB, so AutoMapper would be of little use. I think you're on the wrong track here.

**Comment by jbogard** [comment]
I've changed ORMs several times on various projects, and I promise you,
layering and indirection makes it MUCH harder to do so, even impossible.

**Comment by chrysikos** [comment]
So what you suggest? Just to use the DAL directly to Business Logic?

**Comment by lbargaoanu** [comment]
Yes, for most projects. Of course no advice applies everywhere. For more architecture stuff, check @jbogard's blog, old and new, and his sample app Contoso University.
