### ISSUE TITLE
Inefficient query produced

### ISSUE THREAD

**Issue by Wufe** [AutoMapper/AutoMapper#2114]
### Source/destination types
Source:
```csharp
namespace DatabaseEntities{
        public partial class Article
	{
		public int Id { get; set; }
		public int ProductId { get; set; }
		public bool IsDefault { get; set; }
		public short NationId { get; set; }
		public virtual Product Product { get; set; }
	}

	public partial class Product
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public bool ECommercePublished { get; set; }
		public virtual ICollection<Article> Articles { get; set; }

	}
}
```

Destination:
```csharp
namespace DomainModels{
        public class Price
        {
		public int Id { get; set; }
		public short RegionId { get; set; }
		public bool IsDefault { get; set; }
	}

	public class Product
	{
		public int Id { get; set; }
		public Price Price { get; set; }
	}
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
	cfg.CreateMap<DatabaseEntities.Product, DomainModels.Product>()
		.ForMember(d => d.Price,
			o => o.MapFrom(
				source => source.Articles
					.Where(
						x => x.IsDefault &&
							x.NationId == 1 &&
							source.ECommercePublished
					)
					.FirstOrDefault()
			)
		);

	cfg.CreateMap<DatabaseEntities.Article, DomainModels.Price>()
		.ForMember(d => d.RegionId, o => o.MapFrom(s => s.NationId));
});
```

### Expected behavior
The expected behavior should be a simple LINQ-generated query, like the one below. 
Using a EF projection, it generates one outer apply:
```sql
SELECT
    [Extent1].[Id] AS [Id],
    [Extent1].[Name] AS [Name],
    [Limit1].[ProductId] AS [ProductId],
    [Limit1].[Id] AS [Id1],
    [Limit1].[NationId] AS [NationId]
    FROM  [dbo].[Products] AS [Extent1]
    OUTER APPLY  (SELECT TOP (1)
        [Extent2].[ProductId] AS [ProductId],
        [Extent2].[Id] AS [Id],
        [Extent2].[NationId] AS [NationId]
        FROM [dbo].[Article] AS [Extent2]
        WHERE ([Extent1].[Id] = [Extent2].[ProductId]) AND ([Extent2].[IsDefault] = 1) AND (1 = [Extent2].[NationId]) AND ([Extent1].[ECommercePublished] = 1) ) AS [Limit1]
```

### Actual behavior
The query created by Queryable Extensions ( ProjectTo ), produces this instead, using 4 outer apply:
```sql
SELECT
    [Extent1].[Id] AS [Id],
    CASE WHEN ( NOT (([Limit1].[ProductId] IS NULL) AND ([Limit1].[Id] IS NULL))) THEN 1 END AS [C1],
    [Limit2].[Id] AS [Id1],
    [Limit3].[IsDefault] AS [IsDefault],
    [Limit4].[NationId] AS [NationId]
    FROM     [dbo].[Products] AS [Extent1]
    OUTER APPLY  (SELECT TOP (1)
        [Extent2].[ProductId] AS [ProductId],
        [Extent2].[Id] AS [Id]
        FROM [dbo].[Article] AS [Extent2]
        WHERE ([Extent1].[Id] = [Extent2].[ProductId]) AND ([Extent2].[IsDefault] = 1) AND (1 = [Extent2].[NationId]) AND ([Extent1].[ECommercePublished] = 1) ) AS [Limit1]
    OUTER APPLY  (SELECT TOP (1)
        [Extent3].[Id] AS [Id]
        FROM [dbo].[Article] AS [Extent3]
        WHERE ([Extent1].[Id] = [Extent3].[ProductId]) AND ([Extent3].[IsDefault] = 1) AND (1 = [Extent3].[NationId]) AND ([Extent1].[ECommercePublished] = 1) ) AS [Limit2]
    OUTER APPLY  (SELECT TOP (1)
        [Extent4].[IsDefault] AS [IsDefault]
        FROM [dbo].[Article] AS [Extent4]
        WHERE ([Extent1].[Id] = [Extent4].[ProductId]) AND ([Extent4].[IsDefault] = 1) AND (1 = [Extent4].[NationId]) AND ([Extent1].[ECommercePublished] = 1) ) AS [Limit3]
    OUTER APPLY  (SELECT TOP (1)
        [Extent5].[NationId] AS [NationId]
        FROM [dbo].[Article] AS [Extent5]
        WHERE ([Extent1].[Id] = [Extent5].[ProductId]) AND ([Extent5].[IsDefault] = 1) AND (1 = [Extent5].[NationId]) AND ([Extent1].[ECommercePublished] = 1) ) AS [Limit4]
    WHERE  NOT (([Limit1].[ProductId] IS NULL) AND ([Limit1].[Id] IS NULL))
```

### Steps to reproduce

```csharp
var products = context.Products.ProjectTo<DomainModels.Product>();
```

Can't figure out what makes this query, because *a EF projection that obtains the same data doesn't generate a long/complex query*.

Please let me know what I am missing or what should I do to keep the domain models and the database entities the same as the example and produce a simpler query.  
I also created a sample repository. You can find it **[here](https://github.com/Wufe/automapper-test).**

**Comment by lbargaoanu** [comment]
Show us the query without AM.

**Comment by Wufe** [comment]
I used a simple projection like this one:
```csharp
var products = context
    .Products
    .Select(
        p => new {
            Name = p.Name,
            Articles = p.Articles
                .Where(a => a.IsDefault && a.NationId == 1 && p.ECommercePublished)
                .Select(b => new { b.ProductId, b.Id, b.NationId })
                .FirstOrDefault()
        }
    );
```

Obviously it requires manual mapping, but produces a simpler query.

**Comment by lbargaoanu** [comment]
Yes, it makes sense, but that's not the query we generate. I guess this can be fixed.

**Comment by Wufe** [comment]
How?

**Comment by lbargaoanu** [comment]
I think we would need something like a let clause. So first a select that fetches once the needed data and then a select to fill the DTO, like we have now. A problem is the type for the first select. Generating types on the fly seems overkill, but it might be the best option. A tuple or something close to it is another option. It's not easy to do.

**Comment by lbargaoanu** [comment]
[Here](https://gist.github.com/lbargaoanu/0cbc531306223f7ffc5468becf2642d6) is a workaround. Ideally this would happen inside AM.
@jbogard Do we want to do this by generating types at runtime? And if so, would the new reference be a problem as in #2075?

**Comment by lbargaoanu** [comment]
@jbogard So just leave this be at the moment?

**Comment by jbogard** [comment]
@lbargaoanu I'd like to see what query we generate - I know his query has anonymous types, but those could have been substituted for the DTOs he made.

**Comment by lbargaoanu** [comment]
I don't think you can use the existing DTO-s. If you take a look at my gist, you need to put the MapFrom expression somewhere. We generate an assignment for each member of the DTO and the right hand side contains the MapFrom expression, hence the repeated query. Hopefully the database will optimize that, but it's not pretty.

**Comment by lbargaoanu** [comment]
From what I can tell, SQL Server doesn't optimize it. @Wufe Do you have enough data to compare the performance of the two queries?

**Comment by Wufe** [comment]
I'll provide a performance comparation asap.

**Comment by Wufe** [comment]
Results of the query of products.  
Each result is the average of 10 iterations.  

| n. of products | single ProjectTo (ms) | double ProjectTo - workaround (ms) |
|----|--------------------|---------------------|
| 10 | 9 | 6 |
| 50 | 51 | 18 |
| 100 | 376 | 28 |
| 200 | 343 | 44 |
| 500 | 78 | 54 |
| 1000 | 114 | 77 |
| 2000 | 200 | 137 |
| 5000 | 547 | 274 |
| 10000 | 948 | 490 |
| 20000 | 1342 | 676 |

**Comment by lbargaoanu** [comment]
It's not as bad as it looks, but it does matter.

**Comment by Wufe** [comment]
The test has been done on a simple example. The time difference grows with the complexity of the model and the entities.
A real world use case would produce worst results.
