### ISSUE TITLE
Cannot convert lambda expression to type 'string' because it is not a delegate type 

### ISSUE THREAD

**Issue by KasunKoswattha** [AutoMapper/AutoMapper#2116]
Im trying to map two types in different namespaces. I'm trying to update Automapper from 3.2 to 6.2. Now im getting  "**Cannot convert lambda expression to type 'string' because it is not a delegate type** "
### Mapping configuration

```csharp
     private void InitializeMeterReadingMapping(IMapperConfigurationExpression mapperConfiguration)
        {          
           
            mapperConfiguration.CreateMap<VehicleStatus, MeterReading>()                   
                   .ForMember(dest => dest.MeterId, opt => opt.UseValue(null))
        }
```
This is just one field. I know lot of things have changed. I couldn't find proper documentation of all the breaking changes. I appreciate If someone could point me to the right direction.

Also, I need to create custom value revolvers. I did create one using **IMemberValueResolver** because I will be calling it "**ForMember ResolveUsing**"
I need to pass values ti its constructor. Could you show me how to do that?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
