### ISSUE TITLE
Mapping Nullable<long> to long in .ProjectTo

### ISSUE THREAD

**Issue by kobelev-dev** [AutoMapper/AutoMapper#2117]
I have structures:

    public class Language
    {
        public long? ParentId { get; set; }
    }
    public class LanguageDto
    {
        public long ParentId { get; set; }
    }

and code:

            return this.PerformWithCache(
                async () => (await this.DBContextScope.Context.Languages
                    .ProjectTo<LanguageDto>(MapperConfig.Default)
                    .ToListAsync());

I tried multiple variants of mapping configuration. Nothing works. I always get exception:

Result Message:	
Test method XXXXXX threw exception: 
System.AggregateException: One or more errors occurred. ---> AutoMapper.AutoMapperMappingException: Unable to create a map expression from Language.ParentId (System.Nullable`1[System.Int64]) to LanguageDto.ParentId (System.Int64)

Mapping types:
Language -> LanguageDto
XXXXXX.Persistence.Entities.Language -> XXXXXX.DataContracts.LanguageDto

Type Map configuration:
Language -> LanguageDto
XXXXXX.Persistence.Entities.Language -> XXXXXX.DataContracts.LanguageDto

I also tried small standalone test. The mapper.Map with these types works fine, .ProjectTo fails with exception (similar to above) while I am using the same mapping configuration.

I am curious is this possible to achieve at all?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by kobelev-dev** [comment]
I tried this build. It works for me. When this 6.1.x build is planned to be released? (weeks? months?)

**Comment by jbogard** [comment]
Releases are every 3-4 months or so. Sounds like yours is working now!
