### ISSUE TITLE
N+1 Queries

### ISSUE THREAD

**Issue by maganuk** [AutoMapper/AutoMapper#2118]
### Source/destination types

```csharp
public class Country
    {
        public int ID { get; set; }
        public string Title { get; set; }

        public ICollection<State> States { get; set; }
    }

public class State
    {
        public int ID { get; set; }
        public string Title { get; set; }
        
        public Country Country { get; set; }
    }

public class CountryDTO
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public List<int> States { get; set; }
    }
```
### Mapping configuration

```csharp
    cfg.CreateMap<Country, CountryDTO>();

    cfg.CreateMap<State, int>()
        .ProjectUsing(c=>c.id);
```

### Version: x.y.z
 
6.0.2
### Expected behavior

Using EF Core, this should generate a single query to get all the countries along with all the IDs for the states in each country. In EF6 this working as expected.
### Actual behavior

EF Core is generating a single query to get all the country and then generation a query for each country to get the states id.
### Steps to reproduce

```csharp
Tried both:

_context.Countries.ProjectTo<CountryDTO>().ToList();

or

_context.Countries.Include(x=>x.States).ProjectTo<CountryDTO>().ToList();
```

**Comment by lbargaoanu** [comment]
Probably an EF Core bug. It should work without Include, as in EF6.
