### ISSUE TITLE
No option to convert object to type for Expression to avoid in memory filter

### ISSUE THREAD

**Issue by ghanchiasif** [AutoMapper/AutoMapper#2120]
We have defined the primary key property as object in BAL and created below mapper to map with DAL. Here, Id is GUID in Engagements.

```
 cfg.CreateMap<Engagements, EngagementBAL>()
                    .ConstructUsing(x => new EngagementBAL(new EngagementId(x.Id)))
                    .ForMember(b => b.EngagementId, m => m.MapFrom(d => new EngagementId(d.Id)));
```

And converting the lamda expression using below code. Here, we have return the expression on BAL layer and passing to DAL.

```
Expression<Func<EngagementTitle, bool>> fc1 = e => e.EngagementId.Equals(id);
            var fc2 = Mapper.Map<Expression<Func<Engagements, bool>>>(fc1);
```

**Internally, it executing the expression as below and going for in memory filter after retrieving all the records from DB and causing the performance issue..**
`e=> new EngagementId(e.Id).Equals(key);`

Here, we are looking some option to generate the expression as below to avoid performance issue.
`e=> e.Id.Equals(key);`

You might have suggestion to change the EngagementId from Object to Guid to resolve but we have some implementation so we can go for that option so looking for some option using AutoMapper.

In 6.02 version, we tried to change the mapper as below because we are already initialize the primary key through ConstructUsing.
` .ForMember(b => b.EngagementId, m => m.MapFrom(d => new EngagementId(d.Id)));`
And failed with below error
**"The source and destination types must be the same for expression mapping between value types."**

In 5.2.0 version, we created operator overloading as below

```
 public static bool operator ==(TypedId typedIdA, Guid typedIdB)
 {
            return typedIdA.Value == typedIdB;
 }
```

And implicit operator as below.
```
public static implicit operator EngagementId(Guid v)
{
            return new EngagementId(v)
}
```

It worked for below (Note: Allowing to compare with Guid)
`Expression<Func<EngagementTitle, bool>> fc1 = e => e.EngagementId == id.ToGuid();`

**Here, It's not allowing to directly to compare with EngagementId.**

**Comment by jbogard** [comment]
Have you tried creating a mapping directly for the two expressions?

**Comment by BlaiseD** [comment]
Can you attach a complete sample to reproduce the problem please?  That exception prevents less meaningful exceptions e.g. when mapping Nullable<int> to int.

**Comment by BlaiseD** [comment]
> You might have suggestion to change the EngagementId from Object to Guid 

Consider casting object to Guid in the CreateMap expression.
