### ISSUE TITLE
Error in Member Configuration Expression<NullSubstitute>

### ISSUE THREAD

**Issue by CNogueira92** [AutoMapper/AutoMapper#2121]
NullSubistitute show an error ( There is no coercive operation defined between the 'System.String' and 'System.Int32' types.), when Register Mappings.

### Source/destination types

```csharp
 CreateMap<Products, ProductsModel>().ForAllMembers(prop => prop.NullSubstitute("")); 
```

### Mapping configuration

```csharp
    Mapper.Initialize(cfg =>
            {
                cfg.AddProfile<DomainToViewModelMappingProfile>();
                cfg.AddProfile<ViewModelToDomainMappingProfile>();
            });
```

**Comment by lbargaoanu** [comment]
It's a type mismatch. Check the [docs](https://github.com/AutoMapper/AutoMapper/wiki/Null-substitution).

**Comment by lbargaoanu** [comment]
Other ways to achieve what you want. Set AllowNullDestinationValues to false or try ForAllPropertyMaps with the right filter.
