### ISSUE TITLE
Defined CreateMap<List<T>, List<K>>, it can't map

### ISSUE THREAD

**Issue by xlebenny** [AutoMapper/AutoMapper#2122]
Sorry for my English

Source:
```csharp
        public class Source
        {
            public int Scores { get; set; }
        }
```

Source:
```csharp
        public class Destination
        {
            public int Scores { get; set; }
            public int Rank { get; set; }
        }
```

### Mapping configuration

```csharp
            Mapper.Initialize(cfg =>
            {
                cfg
                    .CreateMap<Source, Destination>()
                    .AfterMap((source, destination) =>
                    {
                        Console.WriteLine($"source: { source.Scores }  destination: { destination.Scores }");
                    });
                cfg
                    .CreateMap<List<Source>, List<Destination>>()
                    .AfterMap((sources, destinations) =>
                    {
                        Console.WriteLine($"sources.Count: { sources.Count() }  destinations.Count: { destinations.Count() }");
                         //some logic for "desctionations.Rank"
                    });
            });
```

### Expected behavior
Can do some logic after `List `mapped

**Expected Result:**
source: 100  destination: 100 <-- from AfterMap<Source, Destination>
source: 60  destination: 60 <-- from AfterMap<Source, Destination>
sources.Count: 2  destinations.Count: 2 <-- from .AfterMap<List<Source>, List<Destination>>

### Actual behavior

Haven't map anything, then execute AfterMap<List<Source>, List<Destination>>

**Actual Result:**
sources.Count: 2  destinations.Count: 0 <-- from .CreateMap<List<Source>, List<Destination>>

### Steps to reproduce

```csharp
Mapper.Map(foos, bars);
```

All Code:
[Program.txt](https://github.com/AutoMapper/AutoMapper/files/1028520/Program.txt)

**Comment by lbargaoanu** [comment]
You don't need the List map, collections are handled by default.

**Comment by xlebenny** [comment]
I know, but i need write some value to Destination.Rank after mapping.

I don't want call some method after mapping manually like this
```
Mapper.Map(foos, bars);
bars.ForEach(x =>
    x.Rank = bars.Count(y => y.Scores > x.Scores) +1
);
```

**Comment by lbargaoanu** [comment]
OK, but the problem is that if you create the map list, you replace the default behavior, so nothing gets mapped. You can try something like this instead:
    
    Mapper.Map(new List<Source>(), new List<Destination>(), o=>o.AfterMap((s,d)=>Console.WriteLine("AfterMap")))

**Comment by xlebenny** [comment]
It work, thanks  👍
