### ISSUE TITLE
Mapping to child properties defined with auto-property pattern silently fails

### ISSUE THREAD

**Issue by pchasco** [AutoMapper/AutoMapper#2126]
### Source/destination types

```csharp
        class Child { }
        class ChildViewModel { }

        class Parent
        {
            public Parent()
            {
                Children = new List<Child>();
                NeglectedChildren = new List<Child>();
            }

            public ICollection<Child> Children { get; private set; }
            public ICollection<Child> NeglectedChildren { get; private set; }
        }

        class ParentViewModel
        {
            public ParentViewModel()
            {
                Children = new List<ChildViewModel>();
            }

            public ICollection<ChildViewModel> Children { get; private set; }
            public ICollection<ChildViewModel> NeglectedChildren { get; } = new List<ChildViewModel>();
        }
```

### Mapping configuration

```csharp
        private class TestProfile : Profile
        {
            public TestProfile()
            {
                CreateMap<Child, ChildViewModel>();
                CreateMap<Parent, ParentViewModel>();
            }
        }
```

### Version: x.y.z
6.0.2

### Expected behavior

I expect the ParentViewModel.NegelectedChildren collection to contain the same number of elements as source Parent.NeglectedChildren.

### Actual behavior

ParentViewModel.NegelectedChildren is empty regardless of the number of elements in the source Parent.NegelectedChildren collection.

### Steps to reproduce

Given a class with both a collection property defined with { get; private set; } and a collection property using the auto-property with initializer pattern:

```csharp

        private IMapper _mapper;

        [TestInitialize]
        public void TestInitialize()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<TestProfile>();
            });

            _mapper = config.CreateMapper();
        }

        [TestMethod]
        public void WillPopulateAllElementsIntoChildrenCollection_WhenSourceChildrenIsNotEmpty()
        {
            // Arrange
            var packet = new Parent();
            packet.Children.Add(new Child());
            packet.Children.Add(new Child());
            packet.NeglectedChildren.Add(new Child());
            packet.NeglectedChildren.Add(new Child());
            
            // Act
            var result = _mapper.Map<ParentViewModel>(packet);

            // Assert
            result.ShouldSatisfyAllConditions(
                () => result.ShouldNotBeNull(),
                () => result.Children.Count.ShouldBe(2),
                () => result.NeglectedChildren.Count.ShouldBe(2));
        }
```

The test fails:

```
Test method WillPopulateAllElementsIntoChildrenCollection_WhenSourceChildrenIsNotEmpty threw exception: 
Shouldly.ShouldAssertException: result
    should satisfy all the conditions specified, but does not.
The following errors were found ...
--------------- Error 1 ---------------
    result.NeglectedChildren.Count
        should be
    2
        but was
    0
```

**Comment by jbogard** [comment]
That collection is skipped because it's not settable. Try:
```
        private class TestProfile : Profile
        {
            public TestProfile()
            {
                CreateMap<Child, ChildViewModel>();
                CreateMap<Parent, ParentViewModel>()
                     .ForMember(d => d.NeglectedChildren, opt => opt.UseDestinationValue());
            }
        }
```

**Comment by pchasco** [comment]
Moving the initializer into the constructor makes no difference:

```csharp
        class ParentViewModel
        {
            public ParentViewModel()
            {
                Children = new List<ChildViewModel>();
                NeglectedChildren = new List<ChildViewModel>();
            }

            public ICollection<ChildViewModel> Children { get; private set; }
            public ICollection<ChildViewModel> NeglectedChildren { get; }
        }
```

**Comment by jbogard** [comment]
Right, because the property has no setter. Without any additional config, AutoMapper skips properties without a setter. AutoMapper wants to set things. With this it can't (likewise, most serialization libraries can't either, like JSON.Net and MVC model binding).

**Comment by lbargaoanu** [comment]
This should work for collections without a setter, just use the existing instance.

**Comment by jbogard** [comment]
But we don't know that the existing instance is there or should be used.

Unless we add a special case - *if* the destination type is an enumerable and has no setter, then automatically configure to use the destination value and map normally from there.

**Comment by lbargaoanu** [comment]
No, what I meant is that it doesn't work even with UseDestinationValue set.

**Comment by jbogard** [comment]
Ah ok, I thought that once you do ForMember it adds that PropertyMap into the list, but I think it's still not map-able.

**Comment by jbogard** [comment]
I wonder, would adding a MapFrom along with UseDestinationValue work?

An aside, maybe it's a bit weird that we just skip adding property maps that don't have a setter vs. adding them and then deciding how to deal with it.

**Comment by lbargaoanu** [comment]
I'll investigate, but I think this used to work without UseDestinationValue. But then the question is why the tests pass? :)

**Comment by pchasco** [comment]
OK. That totally makes sense. I think it's probably the best behavior to leave it alone for implicit maps, but maybe when the property is mapped explicity with ForMember(dest => dest.Children, opt => opt.MapFrom(src => src.Children)) it should throw a configuration exception. This is the first thing I tried when I was troubleshooting and of course this didn't work either. If the property is explicitly mapped and that map can never work, I would think that it would be appropriate to throw in that case.

**Comment by lbargaoanu** [comment]
@jbogard Spot on. As in #2064.
