### ISSUE TITLE
Add lazy mapping to the 3.x codebase

### ISSUE THREAD

**Issue by dplaskon** [AutoMapper/AutoMapper#2130]
I have a very large legacy application that makes use of Automapper 3.3.1 that would benefit greatly from having lazy mapping available to it (https://github.com/AutoMapper/AutoMapper/issues/718).

Is there any chance this functionality could be back-ported to 3.X?

**Comment by lbargaoanu** [comment]
No, you'll have to do that yourself.

**Comment by jbogard** [comment]
Looking at 3.3.1, it's a lot different than how #718 did things, and how 5.x eventually rewrote everything. Maybe I can go at this a different way - what things did you run into that prevented an upgrade of the package? That PR even had a number of problems so it'd be difficult to track down everything that needs to be backported.

**Comment by dplaskon** [comment]
No problem @jbogard -- I really appreciate you looking into this.

As I recall, we ran into a lot of issues with linq projections from NHibernate when we attempted the update to 6.X.

Perhaps I'll take another stab at this later in the summer and post about the specific issues with encounter with the update.

**Comment by jbogard** [comment]
If it's NHibernate then the issue was likely it couldn't handle null propagation for LINQ. Check out the `EnableNullPropagationForQueryMapping` option and try turning it off.
