### ISSUE TITLE
do we support List<T> to List<T>?

### ISSUE THREAD

**Issue by lhp620** [AutoMapper/AutoMapper#2132]
I have two classes T1 and T2, I want to do Mapper.map<List<T1>, List<T2>>(source ,destination) map but get empty.

I initial them like:
            AutoMapper.Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<List<T1>, List<T2>>();
            });

and then use it as 
Mapper.map<T2>(source)
and 
Mapper.map<List<T1>, List<T2>>(source ,destination)
but the return is empty (count = 0)

from WIKI, looks only support: 
List<Destination> listDest = Mapper.Map<Source[], List<Destination>>(sources);

I changed it to 
Mapper.Map<T1[], List<T2>>(sources.ToArray());

Then it works. So looks I do not know why LIst<T1> to List<T2> does not work here.

**Comment by TylerCarlson1** [comment]
Just do `cfg.CreateMap<T1, T2>()`.
Lists are handled automaticly
`List<T2> destination = Mapper.Map(new List<T1>{new T1});`
