### ISSUE TITLE
Mapping nested object parent null

### ISSUE THREAD

**Issue by dangthetai** [AutoMapper/AutoMapper#2135]
public class A {
public long Id {get;set;}
public virtual A Parent {get;set;}
}

public class ADto {
public long Id {get;set;}
public ADto Parent {get;set;}
}

I use ProjectTo<ADto> but object Parent null. Please help me.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.
