### ISSUE TITLE
6.1.0 readiness

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2137]
Looking at making a release cut. Any objections @AutoMapper/developers ?

**Comment by lbargaoanu** [comment]
No. #2075 is still blocked I suppose.

**Comment by jbogard** [comment]
Yeah i tried to do the experimental NuGet branch but thought better of it.
Wait until the next NuGet drop.

**Comment by lbargaoanu** [comment]
I guess some extra docs would help :) I added a line about PreserveReferences in the upgrade guide.

**Comment by TylerCarlson1** [comment]
Not really.  Looks good enough.
