### ISSUE TITLE
ArgumentOutOfRangeException with IgnoreMap attribute on inherited base class

### ISSUE THREAD

**Issue by idfarm** [AutoMapper/AutoMapper#2139]
### Source/destination types

```csharp
public class Source<T> : List<T>
{
  public String PropertyToMap { get; set; }
  public String PropertyToIgnore { get; set; } = "I am not ignored";
}

public class Destination : DestinationBase<String>
{
}

public abstract class DestinationBase<T> : DestinationBaseBase, IDestinationBase<T>
{
  private String m_PropertyToIgnore;

  public virtual String PropertyToMap { get; set; }

  [IgnoreMap]
  public override String PropertyToIgnore
  {
    get
    {
      return m_PropertyToIgnore ?? (m_PropertyToIgnore = "Ignore me");
    }
    set
    {
      m_PropertyToIgnore = value;
    }
  }

  public virtual List<T> Items { get; set; }
}

public abstract class DestinationBaseBase
{
  [IgnoreMap]
  public virtual String PropertyToIgnore { get; set; }
}

public interface IDestinationBase<T>
{
  String PropertyToMap { get; set; }
  List<T> Items { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(config => config.AddProfile<AutomapperProfile>());

public AutomapperProfile()
{
  CreateMap(typeof (IList<>), typeof (IDestinationBase<>))
    .ForMember(nameof(IDestinationBase<Object>.Items), p_Expression => p_Expression.MapFrom(p_Source => p_Source));
}
```

### Expected behavior

The source object mapped to the destination object, except the property 'PropertyToIgnore' and no exceptions or test failures.

### Actual behavior

ArgumentOutOfRangeException on Mapper.Map.
Has similarities with issue https://github.com/AutoMapper/AutoMapper/issues/844.

### Steps to reproduce

```csharp
var l_Source = new Source<String>
{
  "Cat",
  "Dog",
};
l_Source.PropertyToMap = "Hello World";
var l_Destination = Mapper.Map<Destination>(l_Source);

Debug.Assert(l_Destination.PropertyToIgnore == "Ignore me", "Destination property 'PropertyToIgnore' is invalid.");
```

### Example Project
[Examples.AutomapperIgnoreMapIgnored.zip](https://github.com/AutoMapper/AutoMapper/files/1078038/Examples.AutomapperIgnoreMapIgnored.zip) (updated)

**Comment by lbargaoanu** [comment]
Uncomment the attribute in the generic class.

**Comment by idfarm** [comment]
The example does indeed run without errors if you remove the attributes, but I made an error in the example. I have updated the tests in the Example Project.

The expected result should not have 'PropertyToIgnore' mapped.

**Comment by lbargaoanu** [comment]
Please update the example in the post.

**Comment by idfarm** [comment]
I have updated the example and added some extra info to the expected behaviour.

**Comment by lbargaoanu** [comment]
In my view the right behavior here is to return a proxy, because the map is for the interface, not the concrete class. The attribute is not applied to a member of the mapped interface, so the crash doesn't make sense. Otherwise, yet another hack is needed to work around it.

**Comment by lbargaoanu** [comment]
@idfarm Are you sure you updated the example in the post? I still get the right result when I remove both attributes.

**Comment by idfarm** [comment]
I did, but i have updated the project file to be sure. 
I don't understand why you remove the attributes. The property 'PropertyToIgnore' should not be mapped. That's why the attributes are there. Removing the attributes does not solve the issue, it changes the functionality.

**Comment by lbargaoanu** [comment]
Yes, my bad. I didn't see any difference with or without them, that's why :) So I see your point now, but see https://github.com/AutoMapper/AutoMapper/issues/2139#issuecomment-308757794.

**Comment by idfarm** [comment]
I understand now that mapping of open generic interfaces is not supported. I just assumed it was, because open generics are supported. 
I will have to define all the mappings for the concrete classes then, :(

Thank you for the support.

**Comment by lbargaoanu** [comment]
It is supported, but I'm not sure how well it works. For non generic interfaces, you need As or Include/IncludeBase to tell AM about the derived types. That might work for generic interfaces too, you just have to try it. But the way your maps are now, AM doesn't know about the concrete type, that's why I think returning a proxy is the right thing to do and what happens now is a hack.

**Comment by lbargaoanu** [comment]
[Here](https://github.com/AutoMapper/AutoMapper/blob/eb1a445b373acfac3895e9fd308c43e070db546e/src/UnitTests/MappingInheritance/ShouldSupportOnlyDestinationTypeBeingDerived.cs) are some As examples.

**Comment by lbargaoanu** [comment]
@jbogard Can we fix this as I said above https://github.com/AutoMapper/AutoMapper/issues/2139#issuecomment-308757794?

**Comment by jbogard** [comment]
Yeah I think so, proxy makes sense.
