### ISSUE TITLE
Using abstract ValueResolver with .Net Core DI?

### ISSUE THREAD

**Issue by gdahlin** [AutoMapper/AutoMapper#2140]
I'm using AutoMapper and AutoMapper.Microsoft.Extensions.DependencyInjection in my .Net Core project, and have a number of custom ValueResolvers.

Due to the nature of the projects model, I would like to inject a different implementation of a specific ValueResolver in my test project than the ordinary project.

I have used the documented approach for having services injected in my ValueResolver, which basically solves my problem, but since we're now using the built in DI in .Net Core, would it be possible to instead inject use an interface for my ValueResolver and tell the DI-framework which class to use for the interface.

I'm thinking something such as:

```csharp
public abstract class CustomResolver : IValueResolver<object, object, DateTime>
{
    public abstract DateTime Resolve(object source, object dest, DateTime destMember, ResolutionContext context);
}


public class DefaultCustomResolver : CustomResolver
{   
    public override DateTime Resolve(object source, object dest, DateTime destMember, ResolutionContext context)
    {
        return DateTime.Now;
    }
}
```

Where my mapping config looks like:

```csharp
...
.ForMember(dest => dest.SomeDate, opt => opt.ResolveUsing<CustomResolver>())
```

In Startup.cs I would then like to do:

```csharp
services.AddAutoMapper();
services.AddScoped<CustomResolver, DefaultCustomResolver>();
```

whereas in my tests I would use something different from the DefaultCustomResolver

Would this be possible? From the above approach It seems that AutoMapper tries to instantiate whatever type specified in the mapping config without checking if there is a real instance available in the service collection for the interface/abstract type supplied in the config?

Or have missed something in the documentation?

**Comment by lbargaoanu** [comment]
Try it :)

**Comment by gdahlin** [comment]
I have :) The example above generates this error:

`Property:
      SomeDate Cannot create an abstract class.`

**Comment by lbargaoanu** [comment]
Then use an interface.

**Comment by gdahlin** [comment]
Aside from using empty interfaces (therefore the example above uses an abstract class), I've tried that as well, replacing the abstract class with an interface (all names the same), same thing happens:

`Property:
      SomeDate Cannot create an instance of an interface.`

**Comment by lbargaoanu** [comment]
It would seem the DI package is not working at all :) So maybe you're not telling it what it needs to know, the assemblies where your types reside.

**Comment by gdahlin** [comment]
The .Net Core DI is certainly working for all other purposes of the application. (Where I for instance rely on the DI heavily to customise IdentityServer 4, that uses the exact same approach as in my example above)

In this case it's obviously not working since I don't have the details of how AutoMapper actually tries to get an instance of the CustomResolver above. 
The CustomResolver resides in the same assembly as all other ordinary Resolvers, so it's not related to missing assemblies in the configuration.

In the AutoMapper.Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.cs it adds transient services of all types referenced in the config, but not the abstract class/interface above due to the following code in the AddAutoMapperClasses method:

```csharp
foreach (var type in openTypes.SelectMany(openType => allTypes
                .Where(t => t.IsClass)
                .Where(t => !t.IsAbstract)
                .Where(t => t.AsType().ImplementsGenericInterface(openType))))
            {
                services.AddTransient(type.AsType());
            }
```

Therefore I tried to add the implementing class myself to the service collection with a reference to the abstract class/interface, but it its not picked up by AutoMapper

So I guess AutoMapper tries to pick up an instance of the exact type in the mapping config from the service collection when mapping instead of trying to get the implementing instance in my example above.

So again, would my initial suggestion be possible to get as a feature from AutoMapper? ;)

**Comment by lbargaoanu** [comment]
OK, so I guess we made progress :) So you need a change in AM.DI. Just open an issue there, it's a different repository.

**Comment by gdahlin** [comment]
Thx!

Did some more investigation, and the initial approach DO work, but not with the static mapper.

If someone have the same problem: AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#23
