### ISSUE TITLE
Calling Map of the mapper of a ResolutionContext creates a new context

### ISSUE THREAD

**Issue by fubar-coder** [AutoMapper/AutoMapper#2146]
We stumbled on a problem in `AutoMapper.Collection` where a `context.Mapper.Map(...)` was called *without* passing the `context` to the `Map` function. This resulted in a the undesired behavior that - even though we specified the `PreserveReferences`, the same source object got mapped into two separate destination objects due to the implicit creation of a new context.

The fix was quite simple (AutoMapper/AutoMapper.Collection#41), but this behavior seems counter-intuitive, because when I use a mapper from a context, then I assume that this context is reused. Is this behavior really wanted or did nobody ever fell into this trap before?

Changing this behavior will definitely be a breaking change, but I guess that it's one with a low risk.

**Comment by lbargaoanu** [comment]
We need a failing test without AM.Collections.

**Comment by fubar-coder** [comment]
I created the PR #2148 that contains the test showing this behaviour.

**Comment by lbargaoanu** [comment]
That works as intended. As of 6.1.0, you don't need PreserveReferences in most cases.
