### ISSUE TITLE
Only parameterless constructors and initializers are supported in LINQ to Entities.

### ISSUE THREAD

**Issue by patroza** [AutoMapper/AutoMapper#2149]
```
class Parent {
    protected Parent() {} // for EF
    public Parent(string name) { Name = name; };
    public ICollection<Child> Children {get; set;}
    public string Name {get; set;}
}

class ParentDto {
    public ChildDto FirstChild {get; set;}
    public string Name {get; set;}
}

class Child {
    protected Child() {} // for EF
    public Child(string name) { Name = name; };
    public string Name {get; set;}
}

class ChildDto {
    public string Name {get; set;}
}

CreateMap<Parent, ParentDto>(cfg =>
    cfg.ForMember(x =>x.FirstChild, opt =>
        opt.MapFrom(src => src.Children.FirstOrDefault())));
CreateMap<Child, ChildDto>();

Context.Set<Parent>().Take(10).ProjectTo<ParentDto>().ToList();
```
EF 6. If I remove Child/ChildDto, the problem goes away.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/) that we can execute and see fail.

**Comment by zach-snell** [comment]
Here is a repo with a reproduction solution.
https://github.com/zach-snell/EF6_AutoMapper_Issue

**Comment by lbargaoanu** [comment]
I don't see it. Maybe you forgot to check it in? :)

**Comment by zach-snell** [comment]
@lbargaoanu It is definitely there ha. Its a full Solution with a Console Project in it that will incur the issue.

**Comment by lbargaoanu** [comment]
That code doesn't even call ProjectTo. So it cannot possibly throw the exception in this issue.

**Comment by zach-snell** [comment]
I am highlighting that an error occurs in general mapping a object to an entity in the new 6.1

I should have been more explicit. This is a smaller version that still encounters the error.

Maybe I am misunderstanding/relating the issues. Feel free to inform me if I am wrong.

**Comment by lbargaoanu** [comment]
Your issue is unrelated. You should pass the assemblies that contain profiles, not all the assemblies.

**Comment by zach-snell** [comment]
Sure, it can be unrelated I misunderstood.

However, passing all of the assemblies, if lazy, worked prior to 6.1.
Feel free to follow up

Thanks Anyways,
Zach

**Comment by zach-snell** [comment]
My apologies, thanks for following up anyways.

Zach

**Comment by rmagruder** [comment]
I do have a property to a child Dto.  Reading the code above makes me very suspicious.  The main difference between this code and my code is that neither the parent nor the child class have ANY constructors.  Adding them did not make the exception disappear
