### ISSUE TITLE
How to define a type be atom (replace when mapping rather than nested map)

### ISSUE THREAD

**Issue by PMExtra** [AutoMapper/AutoMapper#2157]
I have two similar `Point` Type:

```C#
class Wgs84Point {
    public double X { get; set; }
    public double Y { get; set; }
}

class PostgisPoint {
    public double X { get; set; }
    public double Y { get; set; }
    public int SRID { get; set; }
}
```

And I create a map with them:

```C#
CreateMap<PostgisPoint, Wgs84Point>().BeforeMap((postgis, wgs84) =>
{
    if (postgis.SRID != Epsg4326)
    {
        throw new ArgumentException($"Not support coordinate systems: {postgis.SRID}, support only WGS84.");
    }
});
CreateMap<Wgs84Point, PostgisPoint>()
    .ForMember(postgis => postgis.SRID, options => options.UseValue(Epsg4326));
```

It's awesome. Then, I have an entity type and DTO.

```C#
class Entity {
    public PostgisPoint Position { get; set; }
}
class EntityDto {
    public Wgs84Point Position { get; set; }
}
```

A problem has arisen. When I use `mapper.Map(dto, entity)` to update a entity. The automapper will nested map the inner properties ( X and Y ) with the Position. And then the ORM (like EntityFramework Core) will not tracked this change.

I may tell automapper, the `PostgisPoint` type is an atom, the smallest unit, indivisible whole. It's should be replaced with a new instance rather than map inner properties.

How can I do it?

**Comment by PMExtra** [comment]
I have a try with

```C#
CreateMap<PostgisPoint, Wgs84Point>().BeforeMap((postgis, wgs84) =>
    {
        if (postgis.SRID != Epsg4326)
        {
            throw new ArgumentException($"Not support coordinate systems: {postgis.SRID}, support only WGS84.");
        }
    })
    .ConvertUsing(postgis => new Wgs84Point(postgis.X, postgis.Y));
CreateMap<Wgs84Point, PostgisPoint>()
    .ConvertUsing(wgs84 => new PostgisPoint(wgs84.X, wgs84.Y) { SRID = Epsg4326 });
```

It's works great. But I still want to know is there any other solution.

**Comment by lbargaoanu** [comment]
What happens if you make Point a struct?

**Comment by PMExtra** [comment]
@lbargaoanu I have not tried yet. The PostgisPoint is defined by `Npgsql` (PostgreSQL DB Driver), It's a class instead of struct.

**Comment by lbargaoanu** [comment]
You can use MapFrom or ResolveUsing in a similar way, but I have no other idea.

**Comment by PMExtra** [comment]
What difference between MapFrom and ResolveUsing?

**Comment by PMExtra** [comment]
I think both of the MapFrom and ResolveUsing are used in Entity/DTO map. But I want to define the rule in `Point` type.
