### ISSUE TITLE
How to map dynamic object to static type

### ISSUE THREAD

**Issue by stefanosandes** [AutoMapper/AutoMapper#2159]
I'm trying to learn how convert an dynamic value that I get from dapper query to static type.

My test destination object is:

```csharp
    class MyObject {
        public string Name { get; set; }
        public int Version { get; set; }
        public DateTime CreatedAt { get; set; }
        public Child Child { get; set; }
    }

    class Child {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
```

It's a simples example. I have more complex dynamic objects that parent has child and child have a collection of other types. For now, I'm trying with an more simple example. 

My dynamic object:

```csharp
dynamic obj = new ExpandoObject();

obj.Id = Guid.NewGuid();
obj.Version = 1;
obj.Name = "My Object";
obj.CreatedAt = DateTime.Now;
obj.ChildId = Guid.NewGuid();
obj.ChildName = "My Children";
```

I try this way:

```csharp
var dest = new MyObject();
var myObejct = mapper.Map<dynamic, MyObject>(obj, dest);
```

The ```dest``` and ```myObject``` Child property is empty. Other properties are filled correctly.

With the Slapper.AutoMapper, I can do that with a default convention, but the project is not compatible with .net core yet.

What's the best way to do this mapping?

**Comment by jbogard** [comment]
This should be supported OOTB, what's not working?

**Comment by lbargaoanu** [comment]
From what I understand, you want to customize the mapping, so you can map the Child destination property from some values in your source object. The built in mapping is general, so you cannot customize that. You can create a map between ExpandoObject and your destination object and customize that. Or use the per Map call AfterMap event to do the extra work. The former seems more elegant, but it seems difficult to call the built in mapping to do its work. The latter should just work.

**Comment by lbargaoanu** [comment]
The first idea would [work](https://gist.github.com/lbargaoanu/34a397a5ced65d8d2547c4440893a0ee), but it's weird. The second seems the way to go.
