### ISSUE TITLE
6.1.1 readiness

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2163]
Any other outstanding regressions we want to get out for 6.1.1 @lbargaoanu @TylerCarlson1 ? It doesn't seem that we can reproduce #2149 

And if anyone wonders, because very few people download pre-release, a release version is the only way to really capture regression bugs

**Comment by lbargaoanu** [comment]
I think it's good to go.

**Comment by TylerCarlson1** [comment]
I think it's good as well.

**Comment by jbogard** [comment]
6.1.1 released
