### ISSUE TITLE
GetMapExpression<TSource, TDest> throws cast exception

### ISSUE THREAD

**Issue by Wufe** [AutoMapper/AutoMapper#2164]
### Version: 6.1.1

Using `GetMapExpression<TSource, TDest>` a cast exception is thrown, using the same entities & models of #2114.

The reason might be because `GetMapExpression<TSource, TDest>` uses the `GetMapExpression(Type, Type)` function, then gets its *first element* and casts it to `Expression<Func<TSource, TDest>>` [here](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs#L550) while the type of the first function in the LambdaExpression array is of type `Expression<Func<TSource, TProxy>>` and the second element is `Expression<Func<TProxy, TDest>>`.

This only happens with *complex* objects treated in [this](https://github.com/AutoMapper/AutoMapper/pull/2131) PR.

Is there a way to get a predicate that maps a TSource entity to a TDest model with complex models?

**Comment by lbargaoanu** [comment]
Why do you call GetMapExpression?

**Comment by Wufe** [comment]
To obtain a predicate that maps a TSource entity to a TDest model

**Comment by lbargaoanu** [comment]
:) Hacking your way around is not going to lead to good things. Just call Mapper.Map.

**Comment by Wufe** [comment]
The predicate is needed to create just a cache key, the cache is based on TDest types.

**Comment by lbargaoanu** [comment]
That's not helpful. You cannot call random methods in AM. Mapper.Map is the API, or ProjectTo. See [here](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)). And if that throws the same exception, I need a failing test and we'll take it from there.

**Comment by lbargaoanu** [comment]
And anyway, I'd say the whole idea is not feasible. It's expensive to create such expressions and I'm not sure you would get any benefit if you have to do it every time you check the cache. Be sure to measure, but it doesn't sound good.

**Comment by Wufe** [comment]
The method seems not to be random: it is public indeed. It worked until 6.0.2, named CreateMapExpression. 
I will consider your suggestion to not to use the predicate to create the cache key, but the method itself still may need to be fixed: the cast will always raise an exception if there are more of one lambda expressions in the returning array, even if the method is only for internal purposes.

The issue can be closed if the issue wont be fixed.

**Comment by lbargaoanu** [comment]
The fact that is public is of no consequence. It is not an API. If you want to use it, you're free to do so, but you're on your own. And if you want to fix it to work for your case, you're welcome to do so. But the way I see it, it works for us.

**Comment by resnyanskiy** [comment]
Please correct me if i'm wrong.
As I understand, `AutoMapper.QueryableExtensions.ExpressionBuilder` not an API, and by design, it shouldn't be used as an API.
So, if i want to get `projection expression` from AM, I need to create my custom extension. Something like this
```
static class MapperExtensions
{
  public static Expression<Func<S, T>> GetMapExpression<S, T>(this IMapper mapper)
  {
    var expressions = mapper.ConfigurationProvider.ExpressionBuilder.GetMapExpression(typeof(S), typeof(T), new Dictionary<string, object>(), new MemberInfo[0]);
    return expressions.FirstOrDefault() as Expression<Func<S, T>>;
  }
}
```
And there is no reason now or in the future AM will have such API?

**Comment by jbogard** [comment]
Typically I only want to support what I want to document.

**Comment by resnyanskiy** [comment]
@jbogard, i'm not sure i understand you. You mean AM doesn't support things like `projection` for single entity, only for `IQueryable`, and there is no reason for such feature?

**Comment by jbogard** [comment]
No I meant that AutoMapper has a lot of public methods, but I only really support what's been publicly documented, otherwise you're kinda on your own.

**Comment by jbogard** [comment]
@resnyanskiy what does it look like to do projection for a single entity? I only do `dbContext.Foos.Where(f = f.Id == id).ProjectTo<FooDto>().SingleOrDefault();`

**Comment by resnyanskiy** [comment]
@jbogard well, may be it's just only in my case.
For example, I have a 'repository' (in fact i have a 'repository layer'). Repository has several `Get` methods with a limited number of predicates (by id, by name, etc).
```
class Repository
{
  Entity Get(int id);
  Entity Get(string name);
  ...
}
```
Entity has dozens of properties (database columns), but the repository client needs only several of them, or it needs only value of some 'navigation property'. So I added projection to the method signature.
```
T Get<T>(int id, Expression<Func<Entity, T>> projection).
```
Every public `Get` method is just a decorator of a private generic method (simple decorator in simple case, more complex in others cases).
```
T Get<T>(Expression<Func<Entity, bool>> predicate, Expression<Func<Entity, T>> projection)
{
  return dbContext.Entities.Where(predicate).Select(projection).SingleOrDefault();
}
```
I want to create projection based on DTO. And that is when I need projection for a single entity.
```
class Service
{
  Dto.Entity GetEntity(int id) => _repository.Get(id, _mapper.GetMapExpression<Entity, Dto.Entity>());
}
```

**Comment by JoeGannon** [comment]
@resnyanskiy use ProjectTo to project to a specific DTO

```c#
public TDto Get<TDto>(Expression<Func<Entity, bool>> predicate)
{
	using (var db = new Context())
	{
		var result = db.Entities
						.Where(predicate)
						.ProjectTo<TDto>()
						.SingleOrDefault();

		return result;
	}
}
```

**Comment by resnyanskiy** [comment]
@JoeGannon 
- This will create dependency from AM in assembly with Repository.
- AM is just another one way to define projection. I don't want it as the only way.

**Comment by jbogard** [comment]
Ah, you’ve got a layered project architecture. Yeah it’ll be a bit harder
to put together but it’s possible.

**Comment by TylerCarlson1** [comment]
@resnyanskiy [UseAsDataSource](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)) might be useful for your situation.

Make class like this
```
public class Repository<T,TDTO> 
{
    public IQueryable<TDTO> Query
    {
        using (var db = new Context())
	{
            return db.DbSet<T>().UseAsDataSource().For<TDTO>();
        }
    }
}
```

Then your call can look something like this
```
class Service
{
  Dto.Entity GetEntity(int id) => _repository.Query.SingleOrDefault(q => q.ID == id);
  string GetEntityName(int id) => _repository.Query.Where(q => q.ID == id).Select(q => q.Name).SingleOrDefault();
}
```

And all the expression translation and projection is done behind the scenes.  And will use projection, or pass selects strait to SQL or whatever the situation is called for.

Yes you still reference Automapper in Repository but I guess you could pass a static `Func<IQueryable<T>, IQueryable<TDTO>>` which would call `_ => _.UseAsDataSource().For<TDTO>()`.

**Comment by resnyanskiy** [comment]
@TylerCarlson1 
* This will transform my 'Entity Repository' into 'DTO Repository'. Means, my predicates becomes 'DTO-based'
```
class Entity
{
 int Id { get; } 
 string Name { get; }
}

class EntityDto
{
 string Name { get; set; }
}

Repository<Entity, EntityDTO>.Query().Where(dto => dto.Id == id); // error, no Id in EntityDto
```
* Predicates (and its construction process) are a bit more complicated than just comparing of IDs in my case, so I use `Get` methods. By the way, proposed repository implementation (with `Query` method) seems useless (IMHO) when you use EntityFramework as ORM.
* I want to be able to define a projection not only with AM. For example, I want to use anonymous types.

**Comment by jbogard** [comment]
Or just don’t do repositories and just use the EF directly.

**Comment by resnyanskiy** [comment]
@jbogard, very strange advice. You think, somebody will design solution architecture depending on AM API limitations?

**Comment by jbogard** [comment]
Nah just ditch the abstractions that force you to go through these hoops :)

**Comment by resnyanskiy** [comment]
@jbogard 
I could ask 'Why you call Automapper an abstraction?", but I won't.

**Comment by jbogard** [comment]
AutoMapper is an abstraction?

Now I'm confused...

**Comment by TylerCarlson1** [comment]
@resnyanskiy I'm with @jbogard with just using EF directly.  Use AM when you need projection and use anon types from select as needed.  It gets rid of the hassle of trying to map expressions to one another which is confusing.

But if you really want to abstract it out then with UseAsDataSource you can abstract EF out of the repository as well.  So now you are only using DTOs and not Entities, your repository interface is completely decoupled from AutoMapper and Entity Framework.  Takes a bit more work than what I explained before to do it but you can do that if that's your goal.

As for your concerns, you would have to add things you were searching for into the DTO like ID.  As for anonymous types that works perfectly fine with UseAsDataSource.  It will convert `Expression<Func<DTO, anon>>` to `Expression<Func<Entity, anon>>` and EF will query directly from that from the database.
