### ISSUE TITLE
ITypeConverter now passing in null, instead of object?

### ISSUE THREAD

**Issue by Gillardo** [AutoMapper/AutoMapper#2165]
Not sure if this is something simple, in that things have changed between versions, but i have upgraded to version 6.1.1 from 4.2.1 and now my custom convertor isnt working.

In my profile, i have this simple line

```
this.CreateMap<ModuleData, ModuleDataModel>().ConvertUsing(new ModuleDataToModelTypeConverter());
```

Then i have my ModuleDataToModelTypeConvertor, like so

```
private class ModuleDataToModelTypeConverter : ITypeConverter<ModuleData, ModuleDataModel>
{
	public ModuleDataModel Convert(ModuleData source, ModuleDataModel destination, ResolutionContext context)
	{ 
		// some code here, but WHY IS destination now NULL???

		return destination;
	}
}
```

As you can see above, the problem i am having is that my destination object is now null?  Before it would be a new ModuleDataModel object.  This is the same for the reverse TypeConvertor, in that the destination is now NULL, but before it would be a new object.

Here is my code that i am using to Map... which i believe is ok.

```
// get object from db
var entity = await _dataService.GetAsync(Module, id);

// convert object to view model
var model = _mapper.Map<ModuleDataModel>(entity);
```

Can someone tell me if maybe something has changed between versions, or whether this is a bug?

**Comment by lbargaoanu** [comment]
Destination is not null only when you pass the destination in the Map call.

**Comment by Gillardo** [comment]
So this change works for when i am converting a single object

`var model = _mapper.Map(entity, new ModuleDataModel());`

But what about when i am trying to convert a collection of the objects??  This doesnt work (result is a Collection<ModuleData>)

`var model = _mapper.Map(result, new Collection<ModuleDataModel>());`

**Comment by lbargaoanu** [comment]
If you mean that in the second case, the destination is null in the converter above, that's expected. The collection is cleared before mapping, you're not mapping into existing objects. Only the list itself is reused.

**Comment by Gillardo** [comment]
So how do i get it to be not NULL in the destination of the convertor when converting to a collection? Or are you going to say i have to iterate through the collection and convert each object, then add it too the new collection manually?

**Comment by lbargaoanu** [comment]
Yes, or try AutoMapper.Collections. AM doesn't support this.

**Comment by TylerCarlson1** [comment]
You could do 
```
var model = result.Select(r => _mapper.Map(r, new ModuleDataModel()).ToList();
```
And not worry about Destination being null.

**Comment by lbargaoanu** [comment]
Yes, of course :) The idea is that you have to create the destination objects yourself.
