### ISSUE TITLE
Issue with MapExpression when expression checks if a string equals null

### ISSUE THREAD

**Issue by ghost** [AutoMapper/AutoMapper#2166]
When I try to map an expression where there is a check if a string property equals null, I receive the following error:

"InvalidOperationException: The operands for operator 'Equal' do not match the parameters of method 'op_Equality'."

Example:
===================================================================
protected virtual IMapper CreateDefaultMapper<TEntity, TMappedEntity>()
{
      return new MapperConfiguration(cfg =>
      {
                cfg.CreateMap<TEntity, TMappedEntity>().ReverseMap();

                cfg.CreateMissingTypeMaps = true;
      }).CreateMapper();
}
var mapper = CreateDefaultMapper<Order, OrderDto>();
TestMapToDto(mapper, x => x.ShipAddress == null);

void TestMapToDto(IMapper mapper, Expression<Func<OrderDto, bool>> expression)
{
            var mappedExpression = mapper.MapExpression<Expression<Func<Order, bool>>>(expression);
}

===================================================================

I would like to fix it myself, but I'm not really familiar with how to do this, so I'll try and explain what (in my opinion) is the issue.

The error occurs in the class 'XpressionMapperVisitor', in the method "protected override Expression VisitBinary(BinaryExpression node)"

When is change this method so it looks like this;
===================================================================
        protected override Expression VisitBinary(BinaryExpression node)
        {
            if (node.Right is ConstantExpression constantExpression)
            {
                if (constantExpression.Value == null)
                {
                    return base.VisitBinary(node.Left.Type.GetTypeInfo().IsValueType || node.Left.Type == typeof(string)
                        ? node.Update(node.Left, node.Conversion, Expression.Constant(null, node.Left.Type))
                        : node.Update(node.Left, node.Conversion, Expression.Constant(null, typeof(object))));
                }
            }

            constantExpression = node.Left as ConstantExpression;
            if (constantExpression != null)
            {
                if (constantExpression.Value == null)
                {
                    return base.VisitBinary(node.Right.Type.GetTypeInfo().IsValueType || node.Right.Type == typeof(string)
                        ? node.Update(Expression.Constant(null, node.Right.Type), node.Conversion, node.Right)
                        : node.Update(Expression.Constant(null, typeof(object)), node.Conversion, node.Right));
                }
            }

            var newLeft = Visit(node.Left);
            var newRight = Visit(node.Right);
            if ((newLeft.Type.GetTypeInfo().IsGenericType && newLeft.Type.GetGenericTypeDefinition() == typeof(Nullable<>)) ^ (newRight.Type.GetTypeInfo().IsGenericType && newRight.Type.GetGenericTypeDefinition() == typeof(Nullable<>)))
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, Resource.cannotCreateBinaryExpressionFormat, newLeft.ToString(), newLeft.Type.Name, newRight.ToString(), newRight.Type.Name));

            return base.VisitBinary(node);
        }
===================================================================

Then the issue is solved.

I added:
-  || node.Left.Type == typeof(string)
and
-  || node.Right.Type == typeof(string)

in the call to the base.VisitBinary(...) method.

**Comment by lbargaoanu** [comment]
Your best bet is to do it yourself. You need to make a PR, add a failing test, put in your fix and make sure all the tests pass. There's nothing to it :)
