### ISSUE TITLE
AssertConfigurationIsValid with MemberList.Source doesn't recognize inherited ForMember mapping

### ISSUE THREAD

**Issue by michaelaird** [AutoMapper/AutoMapper#2172]
Given the scenario in this gist https://gist.github.com/michaelaird/df1c79d944a8e9ce0fde51f149879bf0 
(note the source field name is an intentional mis-spelling, this is a real example from our code)

### Expected behavior

Configuration should be valid

### Actual behavior

AssertConfigurationIsValid claims Prepopulate is not mapped

**Comment by lbargaoanu** [comment]
ForMember is for destination members. You need ForSourceMember.

**Comment by lbargaoanu** [comment]
I see you're not using Ignore anymore :) But the MapFrom is not in the base map, it's in the other, unrelated map.

**Comment by michaelaird** [comment]
Hey. Sorry. I totally mistyped the title of this case. I meant
ForSourceMember.

**Comment by lbargaoanu** [comment]
OK, so update the repro? :)

**Comment by michaelaird** [comment]
The repro should show the issue but it has extra stuff. I'll try to slim it
down over the weekend.

**Comment by lbargaoanu** [comment]
I don't see ForSourceMember in the repro.

**Comment by michaelaird** [comment]
Ok. My apologies. It's possible I copied and pasted the wrong scenario. I'm
writing this from the road. Let's leave this issue closed. I will review
and repost.

**Comment by lbargaoanu** [comment]
Yes, I closed it because we're not going to do anything about it without a repro.

**Comment by michaelaird** [comment]
OK. I had a chance to review this and I've simplified and updated the gist.  My original description of the issue is actually correct, ForMember on a base class is not getting recognized as mapping source properties.

Here's what's happening:

FieldControl2 => FormElementDTO2 specifies the mapping for the renamed field (Prepoluate => Prepopulate) but the MemberList.Source validation on the "leaf" class (TextBoxControl2) fails and claims that Prepoluate is not mapped.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2172#issuecomment-312185035

**Comment by michaelaird** [comment]
There's an inheritance hierarchy:

1. FormElement2
2. FieldControl2 
3. TextFieldControl2 
4. TextBoxControl2 

So I believe the mapping of 
```c#
cfg.CreateMap<FieldControl2, FormElementDTO2>(MemberList.None)
                    .ForMember(dto => dto.Prepopulate, opt => opt.MapFrom(src => src.Prepoluate));
```

should be valid for all children of FieldControl2, shouldn't it?

**Comment by lbargaoanu** [comment]
No. You need Include or IncludeBase.

**Comment by michaelaird** [comment]
I added this include (updated in gist)
```
.Include<FieldControl2, FormElementDTO2>()
```

and I get the same result. The validation of the configuration still fails.

**Comment by lbargaoanu** [comment]
That doesn't make sense. You're supposed to Include the other map :)

**Comment by michaelaird** [comment]
I'm definitely confused by this. I've now tried updating the FieldControl2 to "include" TextBoxControl2 (updated gist). Still doesn't work. 

I appreciate your help on this cause I'm clearly missing something fundamental about how these inherited mappings are supposed to be configured.

**Comment by lbargaoanu** [comment]
Well, this last version makes sense to me. Maybe there is an extra include, but who's counting. You have included the MapFrom in the derived map. That should work. @jbogard?

**Comment by lbargaoanu** [comment]
Other than validation, the mapping works, so I think it's safe to say this is a validation bug.

**Comment by lbargaoanu** [comment]
Two Include-s should be enough, check the test.

**Comment by michaelaird** [comment]
Great! I think  the same behaviour exists for a .ForSourceMember => Ignore on the base class. Does this fix handle that as well? Should I open a separate issue?

**Comment by lbargaoanu** [comment]
I'd say wait for this to get merged and try it then. Or try the branch.
