### ISSUE TITLE
Replacement of 6.0.2 Automapper's ReverseMap functionality in 6.1

### ISSUE THREAD

**Issue by jakubbukaj** [AutoMapper/AutoMapper#2176]
Hello,
I am using ReverseMap as shortcut for both direction mapping.

Instead of 
`cfg.CreateMap<Person, PersonFlat>();
cfg.CreateMap<PersonFlat, Person>();`

just
`cfg.CreateMap<Person, PersonFlat>().ReverseMap();
`

I noticed breaking change in 6.1 which is also discussed in 
https://github.com/AutoMapper/AutoMapper/issues/2151
thread. I use ReverseMap in same way as Protonix:

> @jbogard We were using ReverseMap() as a shorthand so we didn't have to create another map explicitly, but now the behavior has changed to include un-flattening logic. Though I agree that most cases would want to have this logic included, it does represent a breaking change in the behavior of ReverseMap. It might be worth adding a warning in the release notes.

Before I will replace all occurrences or ReverseMap in our code I would like to know whether there is an existing or in next release planned functionality I could use for same functionality as ReverseMap() had in previous releases.

My test case:
` 
   
    class Program
     {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {

                cfg.CreateMap<Person, PersonFlat>()
                    .ForMember(dest => dest.IdCardOid, opt => opt.ResolveUsing(x => x.IdCard?.Oid));
                cfg.CreateMap<PersonFlat, Person>();
                cfg.CreateMap<IdCard, IdCardFlat>();
                cfg.CreateMap<IdCardFlat, IdCard>();
                cfg.CreateMap<Car, CarFlat>()
                    .ForMember(dest => dest.ManufacturedFactoryOid, opt => opt.ResolveUsing(x => x.ManufacturedFactory?.Oid))
                    .ReverseMap();
                cfg.CreateMap<Factory, FactoryFlat>()
                    .ReverseMap();
            });

            var personFlat = new PersonFlat { Oid = 1, Name = "Joe" };
            var person = Mapper.Map<PersonFlat, Person>(personFlat);

            Debug.Assert(person.IdCard == null, "person.IdCard == null - same as in 6.0.2 version");

            var carFlat = new CarFlat { Oid = 1, Brand = "Ford" };
            var car = Mapper.Map<CarFlat, Car>(carFlat);
            Debug.Assert(car.ManufacturedFactory == null, "car.ManufacturedFactory == null - same as in 6.0.2 version");

        }
    }

    class Person
    {
        public long? Oid { get; set; }
        public string Name { get; set; }
        public IdCard IdCard { get; set; }
    }
    class IdCard
    {
        public long? Oid { get; set; }
        public string Id { get; set; }
    }
    class Car
    {
        public long? Oid { get; set; }
        public string Brand { get; set; }
        public Factory ManufacturedFactory { get; set; }
    }
    class Factory
    {
        public long? Oid { get; set; }
        public string Name { get; set; }
    }
    class PersonFlat
    {
        public long? Oid { get; set; }
        public string Name { get; set; }
        public long? IdCardOid { get; set; }
    }

    class IdCardFlat
    {
        public long? Oid { get; set; }
        public string Id { get; set; }
    }

    class CarFlat
    {
        public long? Oid { get; set; }
        public string Brand { get; set; }
        public long? ManufacturedFactoryOid { get; set; }
    }

    class FactoryFlat
    {
        public long? Oid { get; set; }
        public string Name { get; set; }
    }`

Thanks

Regards,
Jakub

**Comment by lbargaoanu** [comment]
No, as it says over there, you can easily write that yourself.
