### ISSUE TITLE
Make the test projects SDK style and xplat

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2179]
And also execute tests on all supported platforms.

This will mean we need to get off of Fixie and onto xUnit.

**Comment by jbogard** [comment]
This should make it easier for people to contribute by using xunit.

**Comment by lbargaoanu** [comment]
Proptobuf-net does it. But I had to run them using dotnet test. I found that frustrating. It would be nice to do it in VS. xUnit seems to have smth in preview that's able to do that.
