### ISSUE TITLE
ProjectTo with Aggregate Collection Expansion against (Dot Net Core + EF Core Sqlite) 2.0 Preview 2 Hangs

### ISSUE THREAD

**Issue by bridgesquared** [AutoMapper/AutoMapper#2184]
Have just upgraded to Dot Net Core 2.0 Preview 2 and found that a `ProjectTo` operation is **hanging** when there is an aggregate collection involved and we use either SQLite or SQL Server.

- [Gist for Dot Net Core 2.0 Preview 1](https://gist.github.com/bridgesquared/4ffd3caaf9c6aa2e9cf234d35efde061) passes

- [Gist for Dot Net Core 2.0 Preview 2](https://gist.github.com/bridgesquared/36fa042c70363b1486ebde18dfc27789) hangs under Visual Studio test runner.

We are seeing the same behaviour in an actual WEB API project. We're getting timeouts all over the place, and as a result have reverted back to Preview 1.

I have repeated the tests using EF Core's In Memory provider, and without EF Core at all and the tests pass in both versions, so it's probably something to do with the EF Core  Relational layer having changed and something's going wrong once the query that's constructed by the `ProjectTo` is completed (the logs shows it completing)? If I take out the `ProjectTo` the query returns happily.

To recreate the scenario, you need both SDK 2.0.0-preview1-005977 and 2.0.0-preview2-006497 installed and use the `global.json` files to ensure that the correct SDK is being targeted. If using Visual Studio you need VS2017 Preview, I'm running Version 15.3.0 Preview 3.0.

I understand that this is probably either the Dot Net Core team's or the EF Core team's issue (in that there's a breaking change) but it seems to be only during the `ProjectTo` operation that we experience an issue. And at this point I'm not sure how I would debug it any further, though would happily take guidance if you have an idea where it could be happening in the AutoMapper code. Or perhaps you might know who to ping at Microsoft to get their view?

Hope this helps, sorry it's a bit fiddly to recreate. Look forward to any pointers, thoughts etc. Many thanks. CB

**Comment by lbargaoanu** [comment]
This works with EF6, report it to the EF Core team.

**Comment by slubowsky** [comment]
I am finding the same thing. AutoMapper is basically unusable in .NET 2.0 preview 2. Any mapping that includes a child collection may  deadlock.

See https://github.com/aspnet/EntityFramework/issues/8208 which may be the cause and https://github.com/aspnet/EntityFramework/issues/9029 where there is discussion of this problem -  but not in a dedicated issue.

**Comment by lbargaoanu** [comment]
You can easily remove AM from the discussion by making a repro with the generated query.

**Comment by bridgesquared** [comment]
@lbargaoanu Not sure what you mean. If you strip out the `ProjectTo`, and use an include, the test passes in both preview 1 & 2 and doesn't hang:

```
                    using (var context = new Context(options))
                    {
                        var result = await context
                            .Documents
                            //.ProjectTo<DocumentDTO>()
                            .Include(e => e.Items)
                            .FirstAsync();
                        result.Should().NotBeNull();
                        result.Items.Should().NotBeNull();
                        result.Items.Should().HaveCount(2);
                    }
```
@slubowsky Just got back from work, so haven't had time, but will look at those two issues. Thanks for the pointers...

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping).

**Comment by bridgesquared** [comment]
Fair play, will do... thanks

**Comment by bridgesquared** [comment]
The expression generated in both Preview 1 and Preview 2 is the same

```
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AutoMapperTests.DocumentEntity]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AutoMapperTests.DocumentEntity]),
    '(.Lambda #Lambda1<System.Func`2[AutoMapperTests.DocumentEntity,AutoMapperTests.DocumentDTO]>))

.Lambda #Lambda1<System.Func`2[AutoMapperTests.DocumentEntity,AutoMapperTests.DocumentDTO]>(AutoMapperTests.DocumentEntity $dto)
{
    .New AutoMapperTests.DocumentDTO(){
        Reference = $dto.Reference,
        Items = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $dto.Items,
                .Lambda #Lambda2<System.Func`2[AutoMapperTests.DocumentItemEntity,AutoMapperTests.DocumentItemDTO]>))
    }
}

.Lambda #Lambda2<System.Func`2[AutoMapperTests.DocumentItemEntity,AutoMapperTests.DocumentItemDTO]>(AutoMapperTests.DocumentItemEntity $dto)
{
    .New AutoMapperTests.DocumentItemDTO(){
        Reference = $dto.Reference
    }
}
```
The interesting thing is that in the child collection, the expansion of the items is done using a ToList, no sign of async. 

I re-ran the test as **synchronous** and it **passes!**

Went through the issues spotted by @slubowsky  to discover that this is a can of worms. Agree that it's probably [aspnet/EntityFramework#8208](https://github.com/aspnet/EntityFramework/issues/8208). Looks like there might be a fix in 2.0.0 final? if not I'm mindful of [#2114](https://github.com/AutoMapper/AutoMapper/issues/2114) and will probably refactor into two separate `ProjectTo` queries, or worse case go synchronous... no can't do that, will have to refactor, maybe use a helper function in the `Profile`?

Anyway thanks for your help, cheers.

**Comment by slubowsky** [comment]
@bridgesquared I'd suggest opening an issue in entity framework repo. You've got a simple reproducible use case that works in 2.0 preview 1 and earlier but not later. I'm hoping that will convince them it needs to be fixed and not "punted'.

**Comment by bridgesquared** [comment]
@slubowsky I followed your suggestion, thought it through and reckoned EF Core **should** be able to handle it, especially given that it's a breaking change, so have created [aspnet/EntityFramework/issues/9128](https://github.com/aspnet/EntityFramework/issues/9128). Thanks for your help.

**Comment by luisms89** [comment]
I have the same issue with EF 6.1.3

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by paultechguy** [comment]
This is hanging for me.  As of Oct. 10, 2017, using EF 2.0 and ASPNET Core 2.0.  If I remove the await and ToListAync, then the query with .ProjectTo works fine.
