### ISSUE TITLE
Unexpected behaviour with inheritance mapping, where base class is abstract

### ISSUE THREAD

**Issue by ds1709** [AutoMapper/AutoMapper#2186]
I'm trying to create A to A object mapping with list of B, where B is abstract base class an there two derived classes B1 and B2.

### Source/destination types
```csharp
sealed class A { public List<B> ListOfB { get; } = new List<B>(); }

abstract class B { }

sealed class B1 : B { }
sealed class B2 : B { }
```

### Mapping configuration

```csharp
CreateMap<A, A>().ForMember(a => a.ListOfB, e => e.UseDestinationValue());
CreateMap<B, B>(); // Mapping for B1 and B2 purposely missing.
```

### Expected behavior
Exception when trying to map object A to A because of try to cteate instance of abstract class B. Same for mapping B1 to B1 or B2 to B2 (result value is null).

### Actual behavior
Successfuly create new object A, but ListOfB populated by nulls.
```
source_a.ListOfB
Count = 4
    [0]: {MapperTestApp.Program.B1}
    [1]: {MapperTestApp.Program.B1}
    [2]: {MapperTestApp.Program.B2}
    [3]: {MapperTestApp.Program.B2}

target_a.ListOfB
Count = 4
    [0]: null
    [1]: null
    [2]: null
    [3]: null
```

### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<A, A>().ForMember(_ => _.ListOfB, _ => _.UseDestinationValue());
    cfg.CreateMap<B, B>();
});
config.AssertConfigurationIsValid();
var mapper = config.CreateMapper();

var source_a = new A();
var b1 = new B1();
var b2 = new B2();

source_a.ListOfB.AddRange(new B[] { b1, b1, b2, b2 });

var target_a = mapper.Map<A>(source_a); // Success, but ListOfB populated by nulls.

var target_b1 = mapper.Map<B1>(b1); // Success, but target_b1 is null.
var target_b2 = mapper.Map<B2>(b2); // Success, but target_b2 is null.
```

**Comment by lbargaoanu** [comment]
What about a repro without self mapping?

**Comment by jbogard** [comment]
In your B -> B mapping, I'm assuming you want to just bring the value over, and not actually map into new instances?

If so, try this:

```c#
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<A, A>().ForMember(_ => _.ListOfB, _ => _.UseDestinationValue());
    cfg.CreateMap<B, B>().ConvertUsing(src => src);
});
```

**Comment by ds1709** [comment]
Behaviour is same when I mapping `A` to `ADto`.
### Model
```csharp
sealed class A { public List<B> ListOfB { get; } = new List<B>(); }
abstract class B { }
sealed class B1 : B { }
```
### Dto
```csharp
sealed class ADto { public List<BDto> ListOfB { get; } = new List<BDto>(); }
abstract class BDto { }
sealed class B1Dto : BDto { }
```
### Mapping
```csharp
CreateMap<A, ADto>().ForMember(a => a.ListOfB, e => e.UseDestinationValue());
CreateMap<B, BDto>();
```

**Comment by lbargaoanu** [comment]
I think the only way this can work is if you define the map between the concrete types and use Include. I'll get back to it when I have a chance.

**Comment by ds1709** [comment]
Anyway, i think it should be registred as bug. Behaviour is unexpepted and differs from early version, where in this situation exception was generated.

**Comment by lbargaoanu** [comment]
That's not exactly high priority, throwing instead of null :)

**Comment by lbargaoanu** [comment]
@jbogard Any reason for [this](https://github.com/AutoMapper/AutoMapper/blob/cee13baf8d0c32cca89d3fc50150c852685d7275/src/AutoMapper/Execution/TypeMapPlanBuilder.cs#L324)? :)

**Comment by jbogard** [comment]
I'm still struggling with the original example of self-maps, this looks like a cloning question.

**Comment by lbargaoanu** [comment]
Not really, that's just a distraction :) There is an incomplete example above without self mapping. I'm guessing we'll have to remove those checks and throw.
