### ISSUE TITLE
Validation success when TSourceBase or TDestinationBase in IncludeBase<TSourceBase, TDestinationBase>() are not actual base types

### ISSUE THREAD

**Issue by ds1709** [AutoMapper/AutoMapper#2192]
### Source/destination classes
```csharp
class A { }
class A1 : A { }
class B { }

class ADto { }
class A1Dto : ADto { }
class BDto { }
```
### Mapping configuration
```csharp
CreateMap<A1, A1Dto>().IncludeBase<B, BDto>(); // B is not base class for A1 and BDto is not for A1Dto
```

### Expected behavior
Validation error if `TSourceBase` is not `TSource` or base class for `TSource` (same for `TDestinationBase` and `TDestination`), in this case, `B` is not base for `A1` and `BDto` is not base for `A1Dto`.

### Actual behavior
Validation successfully passed, target object successfully mapped.

### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<A1, A1Dto>().IncludeBase<B, BDto>();
});
config.AssertConfigurationIsValid();
var mapper = config.CreateMapper();

var source_a = new A1();
var target_a = mapper.Map<A1Dto>(source_a);
```

**Comment by jbogard** [comment]
I don't know why they're not there. Seems reasonable.

**Comment by lbargaoanu** [comment]
@ds1709 PR?

**Comment by ds1709** [comment]
@lbargaoanu Sorry, can't understand you. What you meen?

**Comment by lbargaoanu** [comment]
If you want this fixed, your best bet is to do it yourself.
