### ISSUE TITLE
Postfix doesn't work in the opposite direction

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [AutoMapper/AutoMapper#2193]
This seems like it could be intentional and not a bug, so I'm hoping for a way to solve this.

### Source/destination types

```csharp
    public class X
    {
        public MarketUi Market { get; set; }
    }

    public class Y
    {
        public int MarketFk { get; set; }
    }

```

### Mapping configuration

```csharp
AutoMapper.Mapper.Initialize(cfg =>
{
    cfg.CreateMap<X, Y>(); // works as expected
    cfg.CreateMap<Y, X>(); // doesn't work as expected

    cfg.RecognizePostfixes("Fk");
    cfg.CreateMap<int, MarketUi>().ConvertUsing(i => ResolveMarket(i)?.Map()); // is used
    cfg.CreateMap<MarketUi, int>().ConvertUsing(x => x?.Id ?? -1); // is not used
});
```

### Version: x.y.z
6.1.1

### Expected behavior

Y to X should map "MarketUi" to "int" correctly using the given custom converter (x.?Id ?? -1)

### Actual behavior

the "int" property is not set at all and stay 0.

**Comment by TylerCarlson1** [comment]
It doesn't reverse, because how are you suppose to know which way is which.

There's `cfg.RecognizeDestinationPostfixes("Fk");` when you want postfixes going the opposite direction.

**Comment by jbogard** [comment]
Also you can use ReverseMap if you want those semantics.

**Comment by SpaceMonkeyForever** [comment]
Thank you very much!
