### ISSUE TITLE
Non-generic IQueryProvider.CreateQuery call causes problem inside ProjectTo<TElement>

### ISSUE THREAD

**Issue by detoxhby** [AutoMapper/AutoMapper#2196]
### Source/destination types

irrelevant (but, different types)

### Mapping configuration

irrelevant

### Version: x.y.z

6.1.*

### Expected behavior

`ProjectTo<TElement>()` could call internally the IQueryable _source's typed version of `CreateQuery(...)` (e.g. `_source.Provider.CreateQuery<TElement>(...)`)

### Actual behavior

`ProjectTo<TElement>()` now calls the non-typed `CreateQuery(...)` ... causing casting errors and so.

### Steps to reproduce

Caused by a recent change: https://github.com/AutoMapper/AutoMapper/commit/75c96b1a1dfbe53905cb4662a6f10005d2e44bb1#diff-d367020de263e9918b8fdabe8a79e91d

**Comment by detoxhby** [comment]
Ping

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by detoxhby** [comment]
Please examine the [IQueryProvider](https://msdn.microsoft.com/en-us/library/system.linq.iqueryprovider(v=vs.150).aspx) interface.

I've attached a screenshot of the exact code lines which are causing the problem from the previously linked diff (https://github.com/AutoMapper/AutoMapper/commit/75c96b1a1dfbe53905cb4662a6f10005d2e44bb1#diff-d367020de263e9918b8fdabe8a79e91d).  
We have to know what type we would need to handle/cast the object to when calling `.ProjectTo<TElement>(...)`. We cannot rely on the non-generic provider call because we need internal type safety (against predefined type) ... and forcing out runtime type check/cast is a huge performance killer in this situation (+ completely unnecessary).
![image](https://user-images.githubusercontent.com/1679462/28137344-3f9dac60-674d-11e7-9205-e08aa22fff84.png)

**Let me know** if you still need sample code, and I will write a hello-world query provider to demonstrate it.

**Comment by lbargaoanu** [comment]
I want to see the code :)

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/44807618/automapper-unable-to-cast-testdbasyncenumerable-to-iqueryable/45769447#45769447. The problem is in the provider.

**Comment by detoxhby** [comment]
It was trivial to use the element type, but still doesn't make any sense to force everyone use reflection if AutoMapper is able to call the generic `CreateQuery` method there (as it has the `TResult` coming in for the `.ProjectTo<>` call. Are there any internal decision why it had to be changed this way? It worked fine for many years...)
