### ISSUE TITLE
Error when mapping expressions with array members

### ISSUE THREAD

**Issue by smax48** [AutoMapper/AutoMapper#2201]
When I try to map nested expressions, AutoMapper throws an exception.

### Expected behavior
Correctly mapped expression

### Actual behavior
Exception

### Steps to reproduce

I created a gist that reproduces the error: 
https://gist.github.com/smax48/005e3121206b69dcb666978fd418c7c0

## Update
It seems that the problem is not in nested expressions, but rather in the used collection type. When it is IEnumerable<T> or IList<T>, it works OK. When it's array - it doesn't ...

**Comment by BlaiseD** [comment]
@smax48 - thanks for reporting this. Please find the proposed fix at #2202.
