### ISSUE TITLE
Feature: Use ContextItems to simplify parametrization

### ISSUE THREAD

**Issue by thiagomajesk** [AutoMapper/AutoMapper#2204]
Hi, I just became aware of [parametrization](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization) in AutoMapper and I was wondering why the default way of setting and getting the values is not through `ContextItems`, like so:

```c#
mapper.Map<Source, Dest>(source, opt => opt.Items["Key"] = 10);

config.CreateMap<Source, Dest>()
.ForMember(d => d.Value, opt => opt.ResolveUsing((src, dest, member, ctx) => ctx.Items["Key"]));
``` 

And for projections (instead of faking a local var):
```c#
dbContext.Courses.ProjectTo<CourseModel>(new { UserName = Request.User.Name });
dbContext.Courses.ProjectTo<CourseModel>(new Dictionary<string, object> { ["UserName"] = Request.User.Name });

config.CreateMap<Course, CourseModel>()
    .ForMember(m => m.CurrentUserName, 
        opt => opt.ResolveUsing((src, dest, member, ctx) => ctx.Items["UserName"]));
```

**Comment by lbargaoanu** [comment]
Probably because EF doesn't support that. If you disagree, make an example with EF and without AM.

**Comment by thiagomajesk** [comment]
Wow, I think that was a bit rush, don't you think? Can someone else provide an technical explanation rather than _"Probably because EF doesn't support that"_ ? 
Well, its seems to me as a AutoMapper legalist that if you can use a "fake" variable on the projection, the same thing could be done for an dictionary value, as internally you have access to `ContextItems`.

**Comment by lbargaoanu** [comment]
Why suppose, I explicitly asked for some code :)

**Comment by thiagomajesk** [comment]
@lbargaoanu I don't know if my question wasn't clear enough or if it's just a missunderstanding. 
Anyway, I'm only asking for a 'tecnhical' explanation whether this can or can't be done. 
As I'm not an AutoMapper expert, I'm bringing this discussion here, to someone that might validate this. Moreover, I'm just 'supposing' it can be done because currently there's no way (as far as I know) to pass an `IMappingOperationOptions` into a `ProjectTo()` call.

**Comment by lbargaoanu** [comment]
I've already answered. There are things that can be done in an EF query, things that can be translated to SQL, and things that cannot, because EF doesn't know how to. That's the explanation. So again, work a little with your idea. Make a gist with EF that does what you want. Once we have that, we can talk about how that could be achieved with AM. That's the best way I can explain it in a few phrases :)

**Comment by thiagomajesk** [comment]
@lbargaoanu It seems you'r misunderstanding what I'm saying here... 
How am I supposed to emulate that behaviour only with EF? 
The whole point is if AutoMapper can get a value from a dict instead of using the "fake" parametrized variable. Is not about whether EF can translate the expression or not.

 IMHO I can't belive that [this](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization) could be handled so much differently on AM internals that you can't pull a value from a dictionary.

```
This works by capturing the name of the closure's field name in the original expression, then using an anonymous object/dictionary to apply the value to the parameter value before the query is sent to the query provider.
```
That's why I'm assuming you could simply cut out the middleman and take the dictionary directly from the user input and then pass it on to the query provider.
