### ISSUE TITLE
Map ThreadSafe Problem v6.0.2

### ISSUE THREAD

**Issue by caozhiyuan** [AutoMapper/AutoMapper#2206]
error info:
{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at AutoMapper.Configuration.Conventions.SourceToDestinationNameMapperAttributesMember.GetMatchingMemberInfo(IGetTypeInfoMembers getTypeInfoMembers, TypeDetails typeInfo, Type destType, Type destMemberType, String nameToSearch)\r\n   at AutoMapper.Configuration.Conventions.ParentSourceToDestinationNameMapper.GetMatchingMemberInfo(TypeDetails typeInfo, Type destType, Type destMemberType, String nameToSearch)\r\n   at AutoMapper.Configuration.Conventions.DefaultMember.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers, IMemberConfiguration parent)\r\n   at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers)\r\n   at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _)\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options, MemberList memberList)\r\n   at AutoMapper.ProfileMap.ConfigureConventionTypeMap(TypeMapRegistry typeMapRegistry, TypePair types)\r\n   at AutoMapper.MapperConfiguration.<>c__DisplayClass55_0.<FindConventionTypeMapFor>b__0(ProfileMap p)\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at AutoMapper.MapperConfiguration.FindConventionTypeMapFor(TypePair typePair)\r\n   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)\r\n   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)\r\n   at AutoMapper.MapperConfiguration.BuildExecutionPlan(MapRequest mapRequest)\r\n   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)\r\n   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()\r\n   at System.Lazy`1.CreateValue()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Lazy`1.get_Value()\r\n   at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)\r\n   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)\r\n   at Suiyi.Phone.Infrastructure.Helper.AutoMapperHelper.MapTo[T](Object obj)\r\n   at Suiyi.Phone.Services.Logs.LogService.<AddLogStatistics>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Suiyi.Phone.WebApi.Logs.LogEventHandler.<Handler>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Suiyi.Msg.EventBus.<>c__DisplayClass8_0`1.<<Publish>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Suiyi.Msg.EventBus.<Publish>d__8`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Suiyi.Msg.Handlers.MessageHandler`2.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Suiyi.Msg.Handlers.AuthorizationHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at HttpDispatcher.Http.CommandHandler`1.<ProcessAsyncCore>d__3.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nInsert\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Collections.Generic.Dictionary`2\nVoid Insert(TKey, TValue, Boolean)","HResult":-2147467261,"Source":"mscorlib","WatsonBuckets":null}

**Comment by lbargaoanu** [comment]
What version and how are we supposed to repro this?

**Comment by lbargaoanu** [comment]
Try the latest from Nuget or Myget.

**Comment by caozhiyuan** [comment]
@lbargaoanu  this bug occurrence  chance is very low,program run one month only this time occur.

**Comment by lbargaoanu** [comment]
The chances of this getting fixed without a repro are slim. I think the best course of action here might be to avoid convention mapping.

**Comment by lbargaoanu** [comment]
For future reference. The problem here seems to be that FindConventionTypeMapFor is not properly synchronized. It runs under a lock for the initial type pair. But if two different initial type pairs lead to FindConventionTypeMapFor being called for the same related type pair, then it can run on different threads. But a repro seems to be a lot of work starting just with this theory.
