### ISSUE TITLE
Constructor mapping with struct

### ISSUE THREAD

**Issue by rlordcardano** [AutoMapper/AutoMapper#2207]
### Source/destination types

```csharp
    public class Dto
    {
        public double Value { get; set; }
    }

    public class Entity
    {
        public double Value { get; set; }
    }

    public struct Source
    {
        public Dto Property { get; set; }
    }

    public struct Destination
    {
        public Destination(Entity property)
        {
            Property = property;
        }

        public Entity Property { get; }
    }
```

### Mapping configuration

```csharp
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Dto, Entity>().ReverseMap();
                cfg.CreateMap<Source, Destination>().ReverseMap();
            });

            var mapper = config.CreateMapper();
```

### Version: 6.1.1

Targeting .NET framework v.4.6.2.

### Expected behavior

I expect all mappings to work properly

### Actual behavior

Mapping from Source to Destination works fine, however from Destination to Source is more problematic. The test included in the gist below reproduces the exact failure. If Destination is not a struct, but a class, the test passes.

### Steps to reproduce

See this [gist](https://gist.github.com/rlordcardano/37c6f8574f249e146d7b50fcc3b09f2d).

**Comment by lbargaoanu** [comment]
As a workaround, you can add a private setter for Destination.Property.

**Comment by rlordcardano** [comment]
Correct, noticed that works too (as well as making it a class) - this is a known issue then?
A private setter is not really an option as the property only needs to be initialised at creation.

**Comment by lbargaoanu** [comment]
Well, a PR is welcome :)
