### ISSUE TITLE
Feature request: IoC in AddProfiles()

### ISSUE THREAD

**Issue by asherber** [AutoMapper/AutoMapper#2208]
Currently, using `AddProfiles()` will result in the profiles being instantiated with the paramterless constructor. It would be nice to be able to pass in a type resolver, similar to `ConstructServicesUsing()`, so that other constructor parameters can be injected.

**Comment by lbargaoanu** [comment]
Maybe that's a sign you should use your DI container for that :)

**Comment by asherber** [comment]
Well, sure! You could say the same thing about `AddProfiles()` and `ConstructServicesUsing()` -- both of those could be done by hand as well. I'm just saying that it would be nice if the syntactic sugar that AutoMapper provides extended to DI for profile constructors.

**Comment by jbogard** [comment]
Noooooo don't do this, Profiles should be stateless including services. If
things need DI AutoMapper explicitly supports that.

**Comment by asherber** [comment]
It looks like AutoMapper supports DI only for providing custom value resolvers. (Or am I missing something?) I could accomplish what I want that way, but it's more code -- injecting directly into the profile would be simpler. But I do take your architectural point about profiles being stateless.

**Comment by jbogard** [comment]
Injecting what exactly?

**Comment by asherber** [comment]
I have a couple of different use cases. One is injecting a class which holds application variables; the mapper needs to combine a field value with a BaseUri in the injected class to get a full URL. A second is injecting a repository class to populate a child object from a provided ID.

I know there are other ways to accomplish both of these that may be more in line with your design goals for AutoMapper. I still think DI is useful here, but I understand if you just want to close this as Won't Do.

**Comment by jbogard** [comment]
Do you have an example of the config you're talking about, I have an idea but want to make sure.

**Comment by asherber** [comment]
My two use cases look something like this:
```csharp
public class MyProfile: Profile
{
    public MyProfile(MySettings settings, MyRepo repo)
    {
        CreateMap<Foo, FooDto>()
            .ForMember(d => d.URL, o => o.ResolveUsing(s => settings.BaseUri + s.ID))
            .ForMember(d => d.ChildClass, o => o.ResolveUsing(s => repo.GetChildClass(s.ChildID)));
    }
}
```

**Comment by jbogard** [comment]
The first one I can see, the second one not. Profiles are static/singleton (and don't even figure in to final configuration, those are now ProfileMaps). You really don't want data access happening buried in a singleton, that's better for a DI-resolved value resolver.

The first one, yeah, I can see that, though I'd still likely prefer DI just to make things consistent.

**Comment by asherber** [comment]
Right, I see where you're coming from. I'll close this, since it doesn't fit in with your design.

**Comment by jbogard** [comment]
Speaking from experience, we used to do this and wound up working to remove it all because of memory leaks etc.
