### ISSUE TITLE
Feature request: Transforms in mapping expressions

### ISSUE THREAD

**Issue by asherber** [AutoMapper/AutoMapper#2209]
I have two classes with identically named properties, so that `CreateMap()` is a simple one-line call. But I want all of the strings in the destination object to be lowercased. I think this means that for each of these properties, I need to do something like:
```csharp
.ForMember(d => d.Foo, o => o.MapFrom(s => s.Foo.ToLower()
```
This seems like a lot of extra typing, a `MapFrom()` for each property just to get the `ToLower()` transform, and I need to remember to add new lines if my classes get bigger.

What I'd like to be able to do is something like:
```csharp
.ForAllMembers(o => o.ApplyTransform(destField => destField.GetType() == typeof(string) ? destField.ToLower() : destField)
```

**Comment by TylerCarlson1** [comment]
If you are ok with it you can do something like
`CreateMap<string, string>().ConvertUsing(s => s.ToLower());`
to achieve the same effect.

Also if they are for one line CreateMap you might want to look at [Conventions](https://github.com/AutoMapper/AutoMapper/wiki/Conventions#conditional-object-mapper) if they all follow some pattern.  Then you have 2 lines instead of one for each map.

**Comment by asherber** [comment]
I'm not sure those solve this issue. For starters, my project has a whole bunch of  different maps, and I only want to lowercase strings in one of them. If I do `CreateMap<string, string>()`, that will apply to every string property in every map. (And maybe I'd like to have a more complicated transform that I selectively apply to only certain properties.)

And unless I'm misreading, that page on Conventions has to do with class names and property names -- not property values.

**Comment by TylerCarlson1** [comment]
From your example that's what it looked like at first glance.  I must of miss-read it as for multiple CreatMaps and not just something for a single CreateMap.

There was some talk about something like this in #1414 but there was no real queries into something like this.

**Comment by asherber** [comment]
Yes, that's similar. @jbogard 's comment at https://github.com/AutoMapper/AutoMapper/issues/1414#issuecomment-229947079 is right on point. I'd like to be able to combine a transform with `MapFrom()`. I'd also like to be able to apply a transform directly to `ForMember()`, without having to specify a source field (assuming the source field has the same name as the destination field). And I'd like to be able to apply a transform in `ForAllMembers()` and `ForAllOtherMembers()`.

**Comment by lbargaoanu** [comment]
You can do that with ForAllMembers, you have the destination member.

**Comment by asherber** [comment]
@lbargaoanu I may have missed a variant of that method -- can you give an example?

**Comment by lbargaoanu** [comment]
You receive a parameter and a member of its interface is the destination member.

**Comment by asherber** [comment]
Yes, thanks, I missed that. That may mean that I can implement what I want as an extension method on `IMemberConfigurationExpression`. I'll play with it and report back.

**Comment by asherber** [comment]
`DestinationMember` is `MemberInfo`, not the member itself, so while I can tell if something is a string, it doesn't look like I have any any way of retrieving the actual mapped value from there. I can do what I want in `AfterMap()`, using reflection to loop over the completed destination object, but I still think it would be  nice to have a transform method that can be used as described above.

**Comment by lbargaoanu** [comment]
What you can do is to set up a resolver to do what you want.

**Comment by asherber** [comment]
In certain cases, yes, but it doesn't cover as many use cases. For example, you can't combine a resolver with `MapFrom()`. The benefit of something like `ApplyTransform()` is that it separates the transformation from the field mapping.

**Comment by lbargaoanu** [comment]
MapFrom is a simplified resolver, so I don't know why you would want to combine them.

**Comment by asherber** [comment]
We're going a little bit in circles here, and maybe I'm not being clear on the use case. Here's some pseudocode:
```csharp
public class Foo
{
  public string Bar { get; set; }
  public string Baz { get; set; }
}

public class FooDto
{
  public string Bar { get; set; }
  public string Fizz { get; set; }
}

CreateMap<Foo, FooDto>()
  .ForMember(d => d.Fizz, o => o.MapFrom(s => s.Baz));
```
How do I apply some kind of transform, like lowercasing, to both fields, without superfluous coding? 

If I simply use `ToLower()`, then I need to add an explicit map for `FooDto.Bar`, which right now gets its source field assigned automatically. Same thing if I use a resolver for each member. And a resolver in `ForAllMembers()` would need to be somehow be told the source field for `FooDto.Bar` as well.

But if I had something like `ApplyTransform()` available, I could use it in `ForAllMembers()`. I could also do something like this:
```csharp
CreateMap<Foo, FooDto>()
  .ForMember(d => d.Bar, o => o.ApplyTransform(lcTransform))
  .ForMember(d => d.Fizz, o => o.MapFrom(s => s.Baz));
```
Here I'm applying the transform just to the one field, but I _don't need to repeat the field mapping_ -- since AutoMapper does that for me.

My point is that one of the main benefits of AutoMapper is the auto mapping -- fields with the same name automatically get wired up. I'd like to be able to apply some transforms without discarding that benefit.

**Comment by lbargaoanu** [comment]
This can be done with ForAllMembers and a resolver, nothing new is needed. It might look best with a member value resolver.

**Comment by asherber** [comment]
Can you give a concise example?

**Comment by asherber** [comment]
Well, I wasn't looking for the feature back then, but I did cite some of this discussion above!

**Comment by jbogard** [comment]
I can re-open it, what did you think of the API discussion? Any feedback there?

**Comment by asherber** [comment]
I only skimmed that thread, didn't read in detail. Would you like me to read and comment there, or comment here?

**Comment by jbogard** [comment]
I re-opened it. Part of that discussion was more detail on how it would work, both from a behavioral perspective and an API perspective.

If that issue captures what we're looking for, then I'll just close this one in lieu of that one.

**Comment by asherber** [comment]
Yes, #1414 captures what I have in mind. I'll comment further over there.
