### ISSUE TITLE
Issue in Mapping through Projection for child object property in Second level in while both property name are different

### ISSUE THREAD

**Issue by sandeepjakhmola** [AutoMapper/AutoMapper#2211]
Child Object Property are not mapping at second level of object. 
 Customer.CustomerMaster. Credit_Limit  
```
public class CustomerVM 
    {
        public CustomerMasterVM CustomerMasterVM { get; set; }
        public CustomerPersonalInfoVM CustomerPersonalInfoVM { get; set; }
    }
 public class Customer
    {
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual CustomerPersonalInfo CustomerPersonalInfo { get; set; }
    }
public class CustomerMaster 
    {
       public int CustomerID { get; set; }
       public bool BlockCashAdvance { get; set; }
        public DateTime? CreatedDate { get; set; }
        **public decimal Credit_Limit { get; set; }**
    }
public class CustomerPersonalInfo 
    {
         public int? CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ID_No { get; set; }
        public string SSN { get; set; }

    }
 public class CustomerMasterVM
    {
        public int CustomerId { get; set; }
        public bool BlockCashAdvance { get; set; }
        public DateTime? CreatedDate { get; set; }
        **public decimal CreditLimit { get; set; }**
    }
 public class CustomerPersonalInfoVM
    {      
        public int? CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; } 
        public string IdNumber { get; set; }
        public string SSN { get; set; }
    }
```
Mapping :
```
   CreateMap<CustomerMaster, CustomerMasterVM>()
                .ForMember(dest => dest.EmailSubscription, opt => opt.MapFrom(src => src.email_subscription))
                .ForMember(dest => dest.LastLogin, opt => opt.MapFrom(src => src.Last_Login))
                .ForMember(dest => dest.CustomerAccountNumber, opt => opt.MapFrom(src => src.Cust_Acc_No))
                .ForMember(dest => dest.EStatementSubscription, opt => opt.MapFrom(src => src.eStatement_subscription))
                .ForMember(dest => dest.MStatementSubscription, opt => opt.MapFrom(src => src.mStatement_subscription))
                .ForMember(dest => dest.CreditLimit, opt => opt.MapFrom(src => src.Credit_Limit));
       CreateMap<CustomerPersonalInfo, CustomerPersonalInfoVM>()
                .ForMember(dest => dest.IdNumber, opt => opt.MapFrom(src => src.ID_No));
```         

Using Autofac DI framework
```
   containerBuilder.Register(c => new MapperConfiguration(mapper =>
            {
                mapper.AddProfile(new ViewModelToDomainMappingProfile());
                mapper.AddProfile(new DomainToViewModelMappingProfile());
            })).InstancePerRequest();
            containerBuilder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<AutoMapper.IMapper>();
```

Version: 6.0.2 version i am using currently
### Expected behavior
```
  .ForMember(dest => dest.CreditLimit, opt => opt.MapFrom(src => src.Credit_Limit));
Credit_Limit value need to map to CreditLimit but it not mapping . Its set 0 always.
```
### Steps to reproduce
 Pleae create object of Customer class and set the value of CustomerMaster .Credit_Limit property 
map the same with CustomerVM object.

I am using Mapper.Map

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by sandeepjakhmola** [comment]
Will add sample code soon  here for better clarity. 
Thanks

**Comment by jbogard** [comment]
Do you mean you're using the static `Mapper.Map` method?

**Comment by sandeepjakhmola** [comment]
No. I am not using Static method. We just recently implemented NonStatic Automapper in our code.
currently I am using  6.0.2 version. We created Instance using  Autofac DI framework as below

  containerBuilder.Register(c => new MapperConfiguration(mapper =>
            {
                mapper.AddProfile(new ViewModelToDomainMappingProfile());
                mapper.AddProfile(new DomainToViewModelMappingProfile());
            })).InstancePerRequest();
            containerBuilder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper()).As<AutoMapper.IMapper>();

**Our Controller Code is like as below. So I think its the object of the MapperConfiguration class using that we calling Map method.**
  public class CustomerController : ApiController
    {
        private IMapper Mapper;  
        public CustomerController(IMapper Mapper)
        {            
            this.Mapper = Mapper;
        }

        public IHttpActionResult Get()
        {
            Customer curCustomer = GetCustomer();
            CustomerVM customerVM = new CustomerVM();
            Mapper.Map(curCustomer, customerVM);
            return Ok(customerVM);
        }
    }
**Do you see any Issue in that ?** Please suggest.

Thanks

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
