### ISSUE TITLE
Request to indicate in the wiki that public setters are necessary for automapper to copy "values" to the destination object..

### ISSUE THREAD

**Issue by gitfortee** [AutoMapper/AutoMapper#2212]
Though it is fundamental, I would request the wiki be updated with an indication(s) that public setters are necessary for automapper to copy "values" to the destination object. 

Public setters even though fundamental can often be overlooked and people may end up spending lot of time before they realize they missed it (happened to me today). 

If it is already mentioned, please ignore this request & it can be closed as you know.

thanks!

**Comment by TylerCarlson1** [comment]
Anyone can edit the wiki. :)

**Comment by gitfortee** [comment]
did that. thanks!

**Comment by lbargaoanu** [comment]
http://lmgtfy.com/?q=automapper+public+setters
