### ISSUE TITLE
Conditional in ConstructProjectionUsing always evaluates to false

### ISSUE THREAD

**Issue by norachuga** [AutoMapper/AutoMapper#2213]
### Expected behavior

When using a conditional in ConstructProjectionUsing, it should evaluate and return the appropriate value when ProjectTo is called. 

### Actual behavior

The false condition is always returned. Rearranging the order of the true and false values or even negating the conditional has no effect.

The only time the true condition can possibly be returned is using an explicit `(true) ? ... : ...`

This behavior is replicated both when using Entity Framework and an in-memory IQueryable.

### Steps to reproduce

https://gist.github.com/norachuga/4ce94ee9a1373e40991b47cff0a197ba

**Comment by lbargaoanu** [comment]
Forget about AM. Try to write a query that does what you want in EF6.
