### ISSUE TITLE
An expression tree may not contain an assignment operator

### ISSUE THREAD

**Issue by ranouf** [AutoMapper/AutoMapper#2214]
Hi,

I want to use this:
https://github.com/AutoMapper/AutoMapper/wiki/Before-and-after-map-actions
Or this:
http://codebuckets.com/2016/09/24/passing-parameters-with-automapper/

Each time i have this error:
 error CS0832: An expression tree may not contain an assignment operator

```
                .Select(t =>
                    Mapper.Map<Shop, ShopDto>(
                        t, opts => opts.Items["CustomerType"] = "test"
                    )
                )
```

I use Asp.net Core, the pb come from the framework? Did I miss something?

**Comment by TylerCarlson1** [comment]
Need a more complete example.  Like a [gist](https://gist.github.com/) that we can run and reproduce the exception.
Also the full exception message would be nice as well.

**Comment by ranouf** [comment]
I found the problem.

First i Had to do a .ToListAsync() and then i can use .Map with opts :)
