### ISSUE TITLE
AutoMapper 6.1.1 very slow .cs file in Visual Studio Professional 2017 15.2 (26430.15)

### ISSUE THREAD

**Issue by Ogglas** [AutoMapper/AutoMapper#2217]
Hello,

I have a problem with my mapping file /configuration being very slow and lagging when adding new mappings to it. It contains around 40 mappings and I have seen this behavior before when the configuration file grows. VS does not lag in any other file even though they can consist of more lines of code.

With lagging I mean that it literally can take a second or two before what I type is displayed in Visual Studio. Before any Intellisense shows up it can take 5-10 seconds when it is normally instant. 

I use ReSharper (Ultimate 2017.1.3) and when I disable ReSharper Intellisense it becomes a bit faster but still slow. 

Do you have any fix for this? 

Found one SO thread but it did not contain a good fix.

https://stackoverflow.com/questions/37513032/automapper-cs-file-extremely-slow-in-visual-studio-2015

**Comment by lbargaoanu** [comment]
That's a question for a VS forum. You can split your config using profiles, that might help.

**Comment by Ogglas** [comment]
@lbargaoanu I think a lot of your users actually use Visual Studio and it only happens in a file containing AutoMapper configuration, I disagree this should only be a VS forum question and not something to look into.

**Comment by mchint01** [comment]
I am facing the same issue.
