### ISSUE TITLE
Error creating abstract member that should be ignored

### ISSUE THREAD

**Issue by dmdymov** [AutoMapper/AutoMapper#2220]
### Source/destination types

```csharp
public abstract class BaseClass
{
    public Guid ID { get; set; }
}

public class Thing
{
    public BaseClass Entity { get; set; }
}

public class ThingDto
{
    public Guid EntityID { get; set; }
}
```

### Mapping configuration

```csharp
public class ThingProfile : Profile
{
    public ThingProfile()
    {
        CreateMap<Thing, ThingDto>()
            .ReverseMap()
            .ForMember(dest => dest.Entity, conf => conf.Ignore());
    }
}
```

### Expected behavior

We don't want `Entity` to be mapped at this stage, it stays null and we map it later in parent mapping. We didn't have any issues with this scenario in older versions.

### Actual behavior

ArgumentException - "Cannot create an instance of abstract type BaseClass".

### Steps to reproduce

```csharp
Mapper.Initialize(x =>
    {
        x.AddProfile(new ThingProfile());
    });
Mapper.Map<Thing>(new ThingDto());
```

**Comment by lbargaoanu** [comment]
MapFrom-s (including the default unflattening) are reversed now. You can drop ReverseMap and create the maps or ignore the offending path.
```C#
        CreateMap<Thing, ThingDto>()
            .ReverseMap()
            .ForPath(d=>d.Entity.ID, o=>o.Ignore())
            .ForMember(dest => dest.Entity, conf => conf.Ignore());
```

**Comment by lbargaoanu** [comment]
See also #2199.
