### ISSUE TITLE
Revamp our issue reporting

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2226]
For @AutoMapper/developers , should we amend the website and perhaps the issue template to be more like how EmberJS does it, where we point people to StackOverflow first for general questions, and that GH is strictly for bugs? See:

https://emberjs.com/community/

I don't like gitter for general questions/discussions, so I might leave a community slack off the list. But I like the "stuck? Need help?" idea.

Thoughts?

**Comment by lbargaoanu** [comment]
It sounds good.

**Comment by TylerCarlson1** [comment]
Yea it could use a revamp.  Right now it has something similar but it's only 2 lines at the very bottom.  Doesn't stand out too much.
