### ISSUE TITLE
Replace our mailing list with Discourse?

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2228]
I generally hate our mailing list. But it would be nice to have something like it between GH issues and SO questions (which close discussions).

Discourse would be an option, we'd have to host it (either on my Azure or in Digital Ocean)

**Comment by TylerCarlson1** [comment]
Never used Discourse but willing to learn.

I hate the mailing list as well.

**Comment by m-henderson** [comment]
if you need help setting up Discourse on Digital Ocean, let me know. I don't mind helping out.
