### ISSUE TITLE
No generic method 'ProjectTo' on type 'AutoMapper.QueryableExtensions.Extensions' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic

### ISSUE THREAD

**Issue by hrfarrokh** [AutoMapper/AutoMapper#2234]
hi 
i want to call ProjectTo dynamically
for example this overload
public static IQueryable<TDestination> ProjectTo<TDestination>(this IQueryable source, params Expression<Func<TDestination, object>>[] membersToExpand);

like this
 Expression.Call(typeof(AutoMapper.QueryableExtensions.Extensions), "ProjectTo", new[] { DtoType },
'What goes here as arguments???')

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by hrfarrokh** [comment]
https://stackoverflow.com/questions/45269849/expression-call-on-projectto?noredirect=1#comment77990358_45269849

**Comment by lbargaoanu** [comment]
But if this code is difficult to write, why not try smth easier, like dynamic or reflection?

**Comment by hrfarrokh** [comment]
Thank you for the reply i updated the question to reproduce the problem.
To reproduce the problem Just copy and Paste and then Run.

Sincerely.
