### ISSUE TITLE
Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by hanslai** [AutoMapper/AutoMapper#2237]
I had checked out [463](https://github.com/AutoMapper/AutoMapper/issues/463) and [1500](https://github.com/AutoMapper/AutoMapper/issues/1500) but still having the same issue.

### Source/destination types
 ```
public sealed class Department : EntityId
    {      
        public string Name { get; private set; }
        public string Description { get; private set; }
        public ICollection<Position> Positions { get; } = new List<Position>();
    }
```
```
 public class DepartmentDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ICollection<PositionDto> Positions { get; set; } = new List<PositionDto>();
    }
```
### Mapping configuration

```
public class HRModelMappingProfile : Profile
    {
        public HRModelMappingProfile()
        {
            CreateMap<Department, DepartmentDto>().ReverseMap();
        }
    }
```
I tried both of the following configurations, both came out the same error message output

```
public void Make_Sure_Department_Map_to_DepartmentDto_is_define_in_MappingProfile_1()
        {
            IEnumerable<Department> department = getTestDepartmentList();
            department.FirstOrDefault();

            Mapper.Initialize(m => m.AddProfile<HRModelMappingProfile>());
            DepartmentDto dto = Mapper.Map<DepartmentDto>(department);

            Assert.True(Guid.TryParse(dto.Name, out _));
        }
```
```
 public void Make_Sure_Department_Map_to_DepartmentDto_is_define_in_MappingProfile_2()
        {
            IEnumerable<Department> department = getTestDepartmentList();
            department.FirstOrDefault();

            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<HRModelMappingProfile>();
            });

            var mapper = config.CreateMapper();

            DepartmentDto dto = mapper.Map<DepartmentDto>(department);

            Assert.True(Guid.TryParse(dto.Name, out _));
        }
```

### Version: x.y.z
"AutoMapper.Extensions.Microsoft.DependencyInjection" Version="2.0.1"
"xunit" Version="2.2.0"
Visual Studio 2017 

### Expected behavior

The test should pass

### Actual behavior

Got the following error message:

Message: AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

Mapping types:
Department[] -> DepartmentDto
AIS.HR.Domain.Entities.Department[] -> AIS.HR.API.Models.DepartmentDto

### Steps to reproduce

Just run the Unit Test
```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by hanslai** [comment]
@lbargaoanu I have repo the issue with the attached solution.  Please refer to the attached zip file.

Thanks you.

[AutoMapperIssue_2237_Repo.zip](https://github.com/AutoMapper/AutoMapper/files/1177082/AutoMapperIssue_2237_Repo.zip)

**Comment by lbargaoanu** [comment]
Well, there is no default mapping between a collection and an object. There is no way AM could know what to do in this case. So you either use LINQ to do the mapping (without AM) or you can tell AM what to to by creating the missing map. You can also mix the two if you want.

**Comment by hanslai** [comment]
@lbargaoanu O, Thanks!!  It was a careless mistake on my code.
