### ISSUE TITLE
ignore list property fail.

### ISSUE THREAD

**Issue by irowbin** [AutoMapper/AutoMapper#2239]
I am trying to ignore some list properties but unable to make it work.  Am i doing wrong here? However wiki docs doesn't help me. Thanks.

### Source/destination types

```csharp
   // dest model
    public class ClaimsDto
    {
        public int Id { get; set; }
        public int Sn { get; set; } // ignore success
        public string ExtensionName { get; set; }
        public string ClaimType { get; set; }
        public List<ResourceActions> ClaimValue { get; set; } // ignore  failed. need help here.
        public DropdownDto StatusDto { get; set; } //  ignore success
    }

    public class ResourceActions
    {
        public string Action { get; set; }
        public string Status { get; set; }
    }

    // The source model
    public class Claims
    {        
        public int Id { get; set; }
        public string ExtensionName { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; } // failed
        public short? Status { get; set; } // source  ignore success
    }

``` 

### Mapping configuration

```csharp
 CreateMap<Claims, ClaimsDto>()
                .ForMember(dto => dto.StatusDto, o => o.Ignore())  // success
                .ForMember(dto => dto.ClaimValue, o => o.Ignore())  // failed
                .ForSourceMember(dto => dto.ClaimValue, o => o.Ignore()) // failed
                .ForSourceMember(src => src.Status, o => o.Ignore()) //success
                .ReverseMap();
```

### Expected behavior

The ignored property should be ignore.
### Actual behavior

Keep complaining about that ignored list property. 

### Steps to reproduce

- Create a destination model with a `List<Model>` property.

- Ignore the property in the `Profile`

- Map the source to destination.

How can i ignore or resolve that list property?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by irowbin** [comment]
Hi! @lbargaoanu  If i change the property name `ClaimValue` to `ClaimValues` then the destination ignored but with same name, the exception occurred. Why is that?

 I have source json value `ClaimValue`
```javascript
 [{"Action":"read","Status":"active"},{"Action":"update","Status":"active"}]
```

and then i have generic type in destination `List<ResourceActions> ClaimValue`

I did something like this in my AM profile, All properties are filled with value but this one is `null`.
```c#
// null
.ForMember(dto => dto.ClaimValue,
 opt => opt.MapFrom(src => JsonConvert.DeserializeObject<List<ResourceActions>>( src.ClaimValue )));

// also null
.ForMember(dto => dto.ClaimValue, opt => opt.ResolveUsing<CustomResolver , string>(src =>src.ClaimValue )) 

```

**member value resolver**

```c#
public class CustomResolver : IMemberValueResolver<Claims , ClaimsDto, string, List<ResourceActions>>
{
    public List<ResourceActions> Resolve(Claims source, ClaimsDto destination, string value, List<ResourceActions> destinationMember, ResolutionContext context)
    {
        return JsonConvert.DeserializeObject<List<ResourceActions>>( value );
    }
}
```
how can i map that source `json` value to dest `List<T>`? 
I also ask at Stack but no luck. https://stackoverflow.com/questions/45385458/automapper-serialize-deserialize-source-string-to-list-using-resolver 

Thanks!

**Comment by lbargaoanu** [comment]
Repro.
