### ISSUE TITLE
Unflattening feature work only with single way of configuration and fails with all other (see ut)

### ISSUE THREAD

**Issue by ivankarpey** [AutoMapper/AutoMapper#2241]
public class Order
    {
        public decimal Total { get; set; }
        public Geo Customer { get; set; }
    }

    public class Geo
    {
        public string Name { get; set; }
    }

    public class OrderDto
    {
        public decimal Total { get; set; }
        public string CustomerName { get; set; }
    }

    public class Test
    {
        public Test()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Order, OrderDto>().ReverseMap();  //this is only working

                // cfg.CreateMap<OrderDto, Order>().ReverseMap(); that config not working

                // cfg.CreateMap<Order, OrderDto>();  this pair of config also not working
                // cfg.CreateMap<OrderDto, Order>();

                // cfg.CreateMap<OrderDto, Order>();  and this not working once again
                // cfg.CreateMap<Order, OrderDto>();
            });
        }
        
        [Fact]
        public void Test1()
        {
            var orderDto = new OrderDto(){CustomerName = "Joe"};
            var order = Mapper.Map<Order>(orderDto);
            Assert.Equal(order.Customer.Name,"Joe");
        }
    }

Expected behaviour - all this configs allow test to pass`

**Comment by lbargaoanu** [comment]
Well, that's how it is supposed to work :) You need ForPath. There is no default unflattening. Mainly because the main use case is entity to dto, not the other way around. That's why we have only default flattening.

**Comment by ivankarpey** [comment]
@lbargaoanu what is the difference between `cfg.CreateMap<Order, OrderDto>().ReverseMap()` and `cfg.CreateMap<OrderDto, Order>().ReverseMap()` than?

**Comment by jbogard** [comment]
`ReverseMap` un-flattens. It's the only way to unflatten. We did this because it would be very big breaking changes just to introduce un-flattening everywhere. So most of the time people create maps with `Entity` -> `Dto` then `ReverseMap` that. Making `ReverseMap` the only map that unflattens mimicked as much as possible the usage we saw in the wild.

**Comment by jbogard** [comment]
I also updated the wiki to reflect this behavior (it was a little too implied).

**Comment by ivankarpey** [comment]
Ok, got it. Don't realized it's works that way.

**Comment by jbogard** [comment]
If the wiki is still not clear please fix it to what would make sense if
you don't mind.

**Comment by ivankarpey** [comment]
@jbogard I think now it's looks super clear.
