### ISSUE TITLE
Missing Exception on Mapping Objects to itself

### ISSUE THREAD

**Issue by glatzert** [AutoMapper/AutoMapper#2242]
We stumbled upon an interesting behaviour in Automapper today:
Upon mapping a non configured type to another instance of itself, Automapper will do nothing.
Neither will it map the data (due to missing configuration) nor will it throw an Exception, telling that the configuration is missing.

### GIST
https://gist.github.com/glatzert/4ba25f28029688f46cab8146b7816c2d

### Version
Version used was: 6.1.0

### Expected behavior
Automapper should probably throw an exception.

### Actual behavior
Instead automapper doesn't do anything.

**Comment by lbargaoanu** [comment]
That's by design. Objects that can be assigned are mapped this way.

**Comment by glatzert** [comment]
I just got confused about the mapper doing it this way - and only thing I found about that was some old issue about `Model m2 = Mapper.Map<Model>(m1);`.
We used Mapper.Map(m1, m2) after seeing the behaviour and were wondering that something still went wrong.

Do you think it's the right thing to define the mapping to the type itself, if I do want to use Automapper for such a mapping, or will that also end in "undefined" behavior?

**Comment by lbargaoanu** [comment]
That should work. It's not exactly a use case we care about, but it's not forbidden either :)

**Comment by glatzert** [comment]
Well, then thanks for your advice and your time 👍

**Comment by TylerCarlson1** [comment]
@glatzert I have uses `CreateMap<T,T>()` myself and it works fine.  The only thing that's kind of annoying is that you have to use CreateMap and can't use a convention, or CreateMissingTypeMaps.  Else it uses assignable.
