### ISSUE TITLE
Fix Automapper's ReverseMap functionality in 6.1

### ISSUE THREAD

**Issue by hVostt** [AutoMapper/AutoMapper#2244]
Is there any plan for fixing the bug that is described in issue https://github.com/AutoMapper/AutoMapper/issues/2176?

**Comment by jbogard** [comment]
What bug?

**Comment by hVostt** [comment]
Here: https://github.com/AutoMapper/AutoMapper/issues/2151

**Comment by jbogard** [comment]
That issue was closed as fixed, see #2161

**Comment by hVostt** [comment]
Ah, its workaround? Ok.

**Comment by jbogard** [comment]
Or if you don't want reverse mapping, don't call ReverseMap.
