### ISSUE TITLE
NullReferenceException with UseAsDataSource

### ISSUE THREAD

**Issue by darkcamper** [AutoMapper/AutoMapper#2246]
Hi. I've having some trouble using "UseAsDataSource" to query a model queryable with a DTO based where clause. These are the details ([GIST provided](https://gist.github.com/darkcamper/9b6ec4109662a24d3b09069579991090))

### Source/destination types

```csharp
class DTO
{
  public class DTONested
  {
    public bool AnotherBoolean { get; set; }
  }

  public DTONested Nested { get; set; }
}

class Model
{
  public bool ABoolean { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Model, DTO>()
       .ForMember(d => d.Nested, opt => opt.MapFrom(s => s));
cfg.CreateMap<Model, DTO.DTONested>()
       .ForMember(d => d.AnotherBoolean, opt => opt.MapFrom(s => s.ABoolean));
cfg.CreateMap<DTO, Model>()
       .ForMember(d => d.ABoolean, opt => opt.MapFrom(s => s.Nested.AnotherBoolean));
```

### What's happening
If I create an Expression<Func<DTO,bool>> , map it to Expression<Func<Model,bool>> and use it in a Where() call it succeeds as expected

```csharp
Expression<Func<DTO, bool>> expOverDTO = (dto) => dto.Nested.AnotherBoolean;
Expression<Func<Model, bool>> expOverModel = 
     mapper.Map<Expression<Func<DTO, bool>>, Expression<Func<Model, bool>>>(expOverDTO);

var result1 = queryable.Where(expOverModel).ToList();
```
But if I try a similar approach with "UseAsDataSource"  in this way:

```csharp
var result2 = queryable.UseAsDataSource(mapper).For<DTO>().Where(expOverDTO).ToList();
```
A NullReference exception is thrown with the following stack trace:

```
AutoMapper.HashCodeCombiner.Combine[T1,T2](T1 obj1, T2 obj2)
   en System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   en System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   en System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   en AutoMapper.MapperConfiguration.FindTypeMapFor(Type sourceType, Type destinationType)
   en AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedSubMemberCall(MemberExpression node)
...
```

I've tried looking in the docs and browsing some old issues but I haven't found any clue about it. Any idea what I'm doing wrong?

Thanks.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by lbargaoanu** [comment]
Never mind, it's the same.

**Comment by lbargaoanu** [comment]
@darkcamper In case you want to try a PR. This is just an educated guess, but the fix might be replacing [this](https://github.com/AutoMapper/AutoMapper/blob/8ebec63d5814cc1d45d5e2409901d01f7b3f3317/src/AutoMapper/Mappers/ExpressionMapper.cs#L235) with 

    var sourceType = propertyMap.SourceType;

And a null check I guess.

**Comment by darkcamper** [comment]
@lbargaoanu Thanks a lot! I'll try your suggestion after I come back from work and see how it goes.

**Comment by dnikolovv** [comment]
@lbargaoanu I think your guess has worked. I've submitted a PR.
