### ISSUE TITLE
Reversed MapFrom cannot be ignored

### ISSUE THREAD

**Issue by pfeigl** [AutoMapper/AutoMapper#2248]
### Source/destination types

```csharp
           profile.CreateMap<PlotEntity, Plot>()
                .ForMember(dest => dest.CreationUserName, opt => opt.MapFrom(src => src.CreationUser.Username))

                .ReverseMap()
                    .ForMember(dest => dest.CreationUser, opt => opt.Ignore())
                    .ForSourceMember(src => src.CreationUserName, opt => opt.Ignore());
```

### Expected behavior

I'm able to ignore an automatically generated reverse of MapFrom

### Actual behavior

The reversed MapFrom is always executed - and in this specific case, an empty "UserEntity" is created in the PlotEntity with only the Username set.

Neither ignoring the destination property nore ignoring the source member does help.

This feature was integrated earlier this year with (see https://github.com/AutoMapper/AutoMapper/issues/2067 and https://github.com/AutoMapper/AutoMapper/pull/2080). While the concept is nice and a good improvement, it's bad, that it's impossible to ignore the automatically generated reversed MapFrom.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
