### ISSUE TITLE
Add PreCondition overload

### ISSUE THREAD

**Issue by ESPNSTI** [AutoMapper/AutoMapper#2251]
In IMemberConfigurationExpression there is a PreCondition method that passes source, and there is a PreCondition method that passes ResolutionContext, however there isn't one that passes both.

____

Internally, in the MemberConfigurationExpression implementation, both the existing PreCondition methods set an expression property that takes both the source and ResolutionContext as parameters.

It also appears that TypeMapPlanBuilder passes both parameters to the internal PreCondition expression property.

So I don't think much would need to change to implement this.

**Comment by lbargaoanu** [comment]
Yes, just do it :)

**Comment by ESPNSTI** [comment]
Ok, I will make a pull request.
