### ISSUE TITLE
Mapping src to dest child under parent type based on src data value

### ISSUE THREAD

**Issue by yshahin** [AutoMapper/AutoMapper#2253]
Hi,

I have a object that contains all the information need to to disambiguate different types.
I have a DTO BaseObject with multiple ChildObjects inheriting from BaseObject.
I want BaseObject to be abstract and always convert to one of the children.

I am looking for a way to do Map<Data, BaseObject> and get one of the children based on an IsMatch() method that is contained in the conversion code.

I know I can group the isMatch Methods and call them before selecting which Map<Data, Child> but I need to encapsulate this logic with the Child mapping and some way to tell Map<Data, BaseObject> that you are their Map<Data, ChildObject1>, Map<Data, ChildObject2>, Map<Data, ChildObject3> and you can check which one you are using the IsMatch function.

Is there a way to achieve this using the current implementation? if not, is there a way to extend this library to support such functionality?

Thanks

**Comment by lbargaoanu** [comment]
AM relies on types and the way this works is described [here](https://github.com/AutoMapper/AutoMapper/wiki/Mapping-inheritance). Other solutions are more ore less hacks. You can customize construction with ConstructUsing. You can take over the mapping and redirect to the desired map. You could tell us what you're trying to achieve and we might have other ideas.

**Comment by yshahin** [comment]
My scenario is as follows I have an EF table that contains multiple types of records.
I want to map each row to the correct type, each record type DTO has the same parent.

Lets say that I have a table of Equipment, My DTO objects are Equipment as the parent class and Hammer, Screwdriver, etc. as children.

The logic to determine which row corresponds to which type is complex, so not a single column represents the type (legacy code).

I have controllers that manage each Child DTO class, which is easy since I just so a Map<Equipment, Hammer> where i already filtered the DB call with the logic needed to get only Hammer rows.

1) In a controller I need to manage the entire tool box, so I need to do a GetAll on the DB and Map each one using the generic Map<Equipment, EquipmentDTO>. While this returns a list of EquipmentDTO but the instance is of the correct child type.
2) I want a way to store the complex matching logic so that I dont have a factory, instead I would like to have each Equipment know how to filter its type.

I was able to solve my problem with the ConvertUsing but if you have a better way then I would love to hear it.

Thanks

**Comment by lbargaoanu** [comment]
Well, I don't see it your way. I think that's exactly what you should do. Encapsulate the construction logic :) And mapping into that new object would obviously choose the right map. I don't think spreading that logic in derived classes is helpful.

**Comment by yshahin** [comment]
This is a good solution but doesn't fulfill one of the OpenClosed design principle.
Also adding new equipment will be difficult since I will have to modify the converter.
I think I would prefer extending the Profile class to include a property for the Filter expression. Then I can add a method to the Mapper class, IsMatch<Type>, this way I will be able to check on the type and keep the code cleanly encapsulated.

From the source I see that you have the Profile methods populate an IMapperExpressions, can I do something similar for IMatchExpressions? which then the Mapper would pick up (Probably I would inherit from he Mapper and add that). This way I can just call Mapper.IsMatch<Type>() and it would return bool.

Any hints how I might do this?

**Comment by lbargaoanu** [comment]
You're making a simple problem difficult. Yes, you can put together a bunch of classes that the way you want. But is it worth it? I don't think so. As for making this work with AM, I don't think that's feasible. @jbogard will weigh in if he has a better idea.

**Comment by yshahin** [comment]
Sure, thanks for the help.

**Comment by jbogard** [comment]
Nope not really. We've had this question in the past, which was basically "I want polymorphic mappings based on some discriminator/matcher". And my answer was in the past - that's what ORMs do. AutoMapper matches on types.

**Comment by yshahin** [comment]
Makes sense, thanks
