### ISSUE TITLE
Help: AutoMapper.Mapper.CreateMap is obsolet

### ISSUE THREAD

**Issue by kergee** [AutoMapper/AutoMapper#2254]
When I read 'ASP_NET-MVC-5-with-Bootstrap-and-Knockout_js', the blew code can't be compiled

> AutoMapper.Mapper.CreateMap(_sourceType, _destinationType);

can anyone help me give some advice?

> namespace BootstrapIntroduction.Filters
{
[AttributeUsage(AttributeTargets.Method)]
public class GenerateResultListFilterAttribute : FilterAttribute, IResultFilter
{
    private readonly Type _sourceType;
    private readonly Type _destinationType;

    public GenerateResultListFilterAttribute(Type sourceType, Type destinationType)
    {
        _sourceType = sourceType;
        _destinationType = destinationType;
    }

    public void OnResultExecuting(ResultExecutingContext filterContext)
    {
        var model = filterContext.Controller.ViewData.Model;

        var resultListGenericType = typeof(ResultList<>).MakeGenericType(new Type[] { _destinationType });
        var srcGenericType = typeof(List<>).MakeGenericType(new Type[] { _sourceType });
        var destGenericType = typeof(List<>).MakeGenericType(new Type[] { _destinationType });

        AutoMapper.Mapper.CreateMap(_sourceType, _destinationType);
        var viewModel = AutoMapper.Mapper.Map(model, srcGenericType, destGenericType);

        var queryOptions = filterContext.Controller.ViewData.ContainsKey("QueryOptions") ? 
            filterContext.Controller.ViewData["QueryOptions"] : 
            new QueryOptions();

        var resultList = Activator.CreateInstance(resultListGenericType, viewModel, queryOptions);

        filterContext.Controller.ViewData.Model = resultList;
    }

    public void OnResultExecuted(ResultExecutedContext filterContext)
    {
    }
}

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide
