### ISSUE TITLE
Custom mapping for object, based on value 

### ISSUE THREAD

**Issue by PramodBhosle** [AutoMapper/AutoMapper#2260]
I want to create custom mapping for my object. Mapping should be done based on the value passed to it. 
Below is the code which I have implimented.
CreateMap<DocumentDto, Document>()
.ForMember(d => d.CPADescription, opt => opt.ResolveUsing((source, dest, arg3, arg4) => Convert.ToBoolean(arg4.Options.Items[UserType.FirmAdmin].ToString()) ? source.Description : string.Empty))
Considering above code I have to check the condition for all the parameters that is for the CPA side description, admin side description and client side description. If i don't want to make such case is there any other way?

Also If the Document model have another object that is Note that is attached to the document.  By using above code it is unable to covert the Note model which is also check the condition and create mapping for model to DTO. 
So if the Object is inside other Object the custom mapper is not working. Can you please help me out for this?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by PramodBhosle** [comment]
Is there any way which I have missed anything.


Thanks & Regards,
Pramod U Bhosle
Mobile No - 9175195764
