### ISSUE TITLE
UseAsDataSource: System.InvalidCastException when mapping A->B->C

### ISSUE THREAD

**Issue by prochnowc** [AutoMapper/AutoMapper#2262]
`UseAsDataSource` throws `System.InvalidCastException` when mapping IQueryable multiple times.

We map two times because we have three layers in the application:
- Data Layer
- Business Layer
- REST API Layer

Each layer uses own data types.

### Version: x.y.z
6.1.0

### Expected behavior
IQueryable translation should work when mapping `IQueryable<A>` to `IQueryable<B>` to `IQueryable<C>` 
This worked perfectly in version 4

### Actual behavior

```
System.InvalidCastException: 'Unable to cast object of type 'AutoMapper.QueryableExtensions.Impl.SourceSourceInjectedQuery`2[Data.ClassA,Data.ClassB]' to type 'System.Linq.IQueryable`1[Data.ClassC]'.'

   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at AutoMapper.QueryableExtensions.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutomapperTest1.Program.Main(String[] args) in C:\Users\prochnowc\Downloads\AutomapperUpdateTest\AutomapperUpdateTest\AutomapperTest\Program.cs:line 22
```

### Steps to reproduce

[AutomapperUpdateTest.zip](https://github.com/AutoMapper/AutoMapper/files/1213781/AutomapperUpdateTest.zip)

**Comment by lbargaoanu** [comment]
Can you make a repro only using ProjectTo?

**Comment by prochnowc** [comment]
Using `ProjectTo<T>()` it works fine. But as far as i can remember we need to use `UseAsDataSource()` because we expose the `IQueryable` using OData. `ProjectTo<T>()` caused many problems and did not work (at least with version 4).

**Comment by prochnowc** [comment]
### More simple repro with UseAsDataSource, throws InvalidCastException

```
var mapper = new Mapper(new MapperConfiguration(c =>
{
                c.CreateMap<A, B>();
                c.CreateMap<B, C>();
}));

var queryableOfA = new List<A> {new A()}.AsQueryable();
var queryableOfB = queryableOfA.UseAsDataSource(mapper).For<B>();
var queryableOfC = queryableOfB.UseAsDataSource(mapper).For<C>();
var listOfC = queryableOfC.ToList();
```

### Works with ProjectTo

```
IMapper mapper = new Mapper(new MapperConfiguration(c =>
{
                c.CreateMap<A, B>();
                c.CreateMap<B, C>();
}));

var queryableOfA = new List<A> {new A()}.AsQueryable();
var queryableOfB = queryableOfA.ProjectTo<B>(mapper.ConfigurationProvider);
var queryableOfC = queryableOfB.ProjectTo<C>(mapper.ConfigurationProvider);
var listOfC = queryableOfC.ToList();
```

**Comment by lbargaoanu** [comment]
@prochnowc If you want to fix this yourself, we'll try to help.

**Comment by prochnowc** [comment]
Hmm .. if you can tell me what the issue is .. i can try. Didnt have a look on the IQueryable mapping code by now.

**Comment by lbargaoanu** [comment]
The issue is that it throws :) I've no idea why, but usually you can guess something starting from an exception and if we have some ideas, you might be able to fix it.

**Comment by prochnowc** [comment]
:) i thought you already have some idea .. i'll have a look ..
maybe you roughly remember what was changed in queryable mapping between v4 and v6 ?

**Comment by lbargaoanu** [comment]
Too much to mention here.

**Comment by prochnowc** [comment]
Sorry we dont have any clue after few hours digging. the mapping of queryables is slightly complex. should be fixed by someone who is into the code.

**Comment by lbargaoanu** [comment]
PR welcome.

**Comment by newclaus** [comment]
I have the same error. I think it'd be better use AsQueryable<T>() instead of the direct type cast in ProjectionExpression.To<TResult>(IDictionary<string, object> parameters, IEnumerable<IEnumerable<MemberInfo>> memberPathsToExpand)

**Comment by aaaabcv** [comment]
Hm, why is this issue closed? I still have the same Problem with AutoMapper 8.0. 
My Workaround is to use consistently ProjectTo(). But same as OP, a multilayer mapping crashed my Application and took me several Hours to investigate.
It appears that the Underlying QueryProvider is stacked and cannot use it's inner Provider correctly. But since I do not know about the design on how it should work I cannot figure out the error.
Btw. also the chain DbContext -> UseAsDataSource -> ProjectTo does not work.

**Comment by lbargaoanu** [comment]
Expression mapping was moved to a different [repo](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping). A PR is welcome there.
