### ISSUE TITLE
not available  on .netcore2.0

### ISSUE THREAD

**Issue by qingask** [AutoMapper/AutoMapper#2263]
not support .netcore2.0 ?

**Comment by lbargaoanu** [comment]
We support .NET standard 1.3, that should work.

**Comment by jbogard** [comment]
And netstandard1.1. We technically don't target .NET Core 1.0/1.1/2.0, just
like we don't target Mono, Xamarin.Mac etc. The whole point of .NET
Standard is you target the standard and it's implemented in multiple
implementations of different versions of the standard.
