### ISSUE TITLE
VB samples with Dynamic instantiation  

### ISSUE THREAD

**Issue by didier99** [AutoMapper/AutoMapper#2269]
Hello ,

I m'llogking for example with automapper with Dynamic instantiation  ..
Ihave some problem to translate c# sample .
x:
Dim mapperConf = New MapperConfiguration(Sub(Config)
										 Config.CreateMap(Of wsOfficeReport.ClsClient, ClsClient)()
										 End Sub)
Dim mapp = mapperConf.CreateMapper()
myObj = mapp .Map(Of ClsClient)(wsLstClients)

I have a error  of  missing configuration

**Comment by lbargaoanu** [comment]
There are websites that translate between the two. I don't think anybody here talks VB.

**Comment by didier99** [comment]
I Think  that is a professionnal anwser..
