### ISSUE TITLE
A lambda expression with a statement body cannot be converted to an expression tree

### ISSUE THREAD

**Issue by jsamm** [AutoMapper/AutoMapper#227]
Tried to upgrade to version 2.0 and found this "A lambda expression with a statement body cannot be converted to an expression tree".  I have a ton of mappings, some of which are complex enough to warrant a statement body.  Is there a way to make this version backward compatible?  Is there a trick that could help ease the pain of upgrading these mappings?

**Comment by unjuken** [comment]
You don't know how this post saved me... Thanks!!!!!

**Comment by seun035** [comment]
ResolveUsing not available in Version 6.0.0

**Comment by lbargaoanu** [comment]
Check [the upgrade guide](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html).
