### ISSUE TITLE
Performance issues after upgrade from 4.1.1 to 6.1.x

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [AutoMapper/AutoMapper#2271]
I was carrying out an upgrade from 4.1.1 to 6.1.x and I'm having severe performance issues. The project is using EntityFramework (with lazy loading disabled) mapping 1:1 to models, and vice versa. When querying using .Include() or .Select(child entity) what used to take a small number of milliseconds on 4.1.1 started crashing with a StackOverflowException.

I tried all of these, separately:
cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.PreserveReferences().ReverseMap());
cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.PreserveReferences());
cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.MaxDepth(0));
cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.MaxDepth(1));

... which fixed the StackOverflowExceptions.

I tried initializing inside my IoC initializer, as well as initializing within the method doing the mapping. With any of the above, the result is the same... it matches that of 4.1.1 but it takes FAR more time. An IList of 2 items is taking 6 seconds in 6.1.0/6.1.1 as opposed to 45ms on 4.1.1.

Then I tried removing all maps and doing a cfg.CreateMissingTypeMaps = true; instead. That made the mapping shoot up to circa 30 seconds.

Any pointers please?

**Comment by lbargaoanu** [comment]
The things you tried, I'm not surprised they didn't help :) So please remove all that. The only similar problem we know of is [here](https://github.com/AutoMapper/AutoMapper/issues/1693#issuecomment-270148644). But please spend some time and investigate, as opposed to guessing. Because otherwise you'll get yourself in trouble. DontInline was renamed to MapAtRuntime.

**Comment by lbargaoanu** [comment]
About PreserveReferences, I assume you read [this](https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide#circular-references). An issue was fixed recently (the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build has it), that might apply. It's not necessary anymore.

**Comment by MarkCiliaVincenti** [comment]
I ran some timings on each version. The code is only different in version 4.1.1 but is identical between tests from 5.0.2 to 6.1.1:

4.1.1: 55ms
5.0.2: 31ms
5.1.1: 920ms
5.2.0: 1130ms
6.0.2: 1134ms
6.1.0: 1723ms
6.1.1: 1633ms

**Comment by MarkCiliaVincenti** [comment]
As regards to PreserveReferences, when I tested with version 6.1.0 I had to put it in manually otherwise I would get a StackOverflowException. I will test the MapAtRuntime.

**Comment by lbargaoanu** [comment]
Remember the MyGet build? :)

**Comment by MarkCiliaVincenti** [comment]
Tried the MapAtRuntime with 6.1.1, i.e.:

cfg.ForAllPropertyMaps(p => p.SourceType != null && !p.SourceType.IsValueType, (pm, o) => o.MapAtRuntime());

It took 1634ms (1633ms when I tested without), so no difference.

**Comment by lbargaoanu** [comment]
The results make sense, you did that to yourself by setting PreserveReferences everywhere.

**Comment by lbargaoanu** [comment]
I can see how much you investigated if MapAtRuntime even applies to your case :)

**Comment by MarkCiliaVincenti** [comment]
Tried with MapAtRuntime and 6.2.0-ci-01374 and it took 1691ms.

**Comment by lbargaoanu** [comment]
OK, and the same code runs in 31ms with 5.0? :) Only a repro would convince me.

**Comment by MarkCiliaVincenti** [comment]
My bad, I updated the wrong mapping.

With MapAtRuntime, no setting of preservereferences, no setting of maxdepth and used the MyGet version 6.2.0-ci-01374 it took 65ms :)

Downgrading to 6.1.1 gives a StackOverflowException due to PreserveReferences not being set.

**Comment by MarkCiliaVincenti** [comment]
So, when will 6.2.0 be released as stable please?

**Comment by lbargaoanu** [comment]
Yes, and you're not supposed to set MapAtRuntime everywhere. Because that will decrease performance and cause subtle bugs. There's no difference in the deployments of MyGet vs NuGet, same amount of testing goes into each build. NuGet is all about locking down the version.

**Comment by lbargaoanu** [comment]
For anything else, we need a repro and we'll investigate.

**Comment by MarkCiliaVincenti** [comment]
Is there a best practices guide for when you're supposed to use MapAtRuntime and when you're not supposed to? It's increasing performance in my tests.

Tested with 6.2.0-ci-01374:
With MapAtRuntime ForAllPropertyMaps - 65ms
Without MapAtRuntime - 1465ms

**Comment by lbargaoanu** [comment]
You need to actually read and try to understand that comment I linked to above.

**Comment by MarkCiliaVincenti** [comment]
I did, but I didn't get a definite answer. It was suggested for when one was getting StackOverflowExceptions but I'm not getting those anymore with 6.2.0 and the code _is_ working without MapAtRuntime, but it's terribly slow. If I enable MapAtRuntime for all property maps, you told me I can cause subtle bugs.

In essence,
Without MapAtRuntime => slow
With MapAtRuntime on all property maps => "subtle bugs"

The only 2 options then would be to:
A) Apply MapAtRuntime only on some models, and reading the comment above didn't help me discertain which ones should be applied and which one shouldn't
B) Downgrade to 5.0.2 with PreserveReferences because the mapping was super-fast in that build.

**Comment by lbargaoanu** [comment]
There are no simple rules that I know of. But after a certain size, the compilation time increases non linearly. That's why you need to break the plan apart. If you choose a few strategic places the compilation time will decrease, again non linearly, and the mapping performance will be optimal, the largest plan will small enough :) You can also compile beforehand, otherwise the plan is compiled just in time. But you do need to measure (ideally compile and mapping separately) and understand the execution plan. That is, if you want optimal performance.

**Comment by lbargaoanu** [comment]
And no, MapAtRuntime has nothing to do with SO, it has everything to to with making the execution plan smaller and speeding up compilation. But this increases the mapping time and can cause subtle differences in mapping behavior, that might affect you or not :)

**Comment by lbargaoanu** [comment]
Clear enough? :)

**Comment by MarkCiliaVincenti** [comment]
I don't need super optimal performance as I don't have the time at the moment. I just want comparable performance to 4.1.1 with no risk of subtle bugs. The code that provides great performance in 5.0.2 is generally getting slower with every release. I'd like to keep updated with AutoMapper but not if I have to do something differently with a new release to stop getting caught in some performance issue.

Unfortunately from 5.1.1+ AutoMapper requires in-depth analysis and tweaking to get comparable performance to 5.0.2. Unless, of course, there's something I missed.

**Comment by MarkCiliaVincenti** [comment]
The "increases in mapping time" with using MapAtRuntime doesn't match my benchmarks. On the contrary, with MapAtRuntime on all property maps it's reducing mapping time by almost 96%!

**Comment by lbargaoanu** [comment]
That's just compiling time, not mapping time. You're trying to fix things in a hurry, but it doesn't work that way.

**Comment by MarkCiliaVincenti** [comment]
I left work now so I can't test anymore until Monday but if I understood
you correctly only the first mapping would be slow since it would be
compiling at that time not during Mapper.Initialize but subsequent mappings
would be faster. I was only mapping once in my unit test.

**Comment by lbargaoanu** [comment]
The changes after 5.1.1 actually improved performance in most cases. Your model is large and interconnected, and that's the root cause. And it can be fixed, but you need to understand how AM maps your model.

**Comment by lbargaoanu** [comment]
Yes, just in time means when it first maps a type pair.

**Comment by MarkCiliaVincenti** [comment]
Great! Thanks for your incredibly responsive support! Have a good weekend!

**Comment by MarkCiliaVincenti** [comment]
So I've run a few more tests with 6.2.0-ci-01374:

- If I don't set CreateTypeMaps = true, the following cryptic error is thrown in AssertConfigurationIsValid:

> AutoMapper.AutoMapperConfigurationException: The following property on System.Collections.Generic.ICollection`1[[RemsReachWebServices.Models.ViewModel, RemsReachWebServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] cannot be mapped: 
	View 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type System.Collections.Generic.ICollection`1[[RemsReachWebServices.Models.ViewModel, RemsReachWebServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
Context:
	Mapping to property View from RemsReachWebData.DBRemsReachDatabase.View to System.Collections.Generic.ICollection`1[[RemsReachWebServices.Models.ViewModel, RemsReachWebServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.

- Without PreserveReferences for all maps a particular Unit test is giving a StackOverflowException
- Without MapAtRuntime for all property maps (how do I set individual maps please?) the first time takes over 44 seconds to run the unit test in its entirety.
- With MapAtRuntime for all property maps the first time takes 700ms to run the unit test in its entirety.

**Comment by lbargaoanu** [comment]
Repro.

**Comment by MarkCiliaVincenti** [comment]
Found the issue with the collection and that seems to have fixed my other problems, for now. I'll test some more, thanks :)

For the record, would you recommend that I remove preservereferences and mapatruntime if everything works?

**Comment by lbargaoanu** [comment]
You should definitely remove PreserveReferences. AM should be able to set it for you to prevent SOs. You should also remove MapAtRuntime when/if #2275 or something like that gets merged. That's a compromise to have things work by default. In the interim I guess, whatever works for you. If you trust your tests, setting it everywhere is an suboptimal option. For best performance, you have to set MapAtRuntime in a clever way as I said above and disable the future default mechanism. I don't think AM will ever try to set MapAtRuntime in an optimal way.

**Comment by MarkCiliaVincenti** [comment]
The code was working with 4.1.1 which didn't have MapAtRuntime, so given that all my unit tests are now also working, I'll go without using MapAtRuntime anywhere. Thanks!

**Comment by lbargaoanu** [comment]
Can you please try the latest from MyGet? #2275 got merged and it should greatly improve the compile time and hopefully leave the mapping time more or less the same.

**Comment by MarkCiliaVincenti** [comment]
Hi,

Thanks for the update. When will this be released on NuGet as a stable build please?

**Comment by MarkCiliaVincenti** [comment]
Good morning,

Any news please? We're a bit wary about going to production using a prerelease version of AutoMapper.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2271#issuecomment-321837856

**Comment by MarkCiliaVincenti** [comment]
Let me ask the question a bit differently then please :)
When will this make it to NuGet please? We're dealing with APIs by 3rd parties too and it would be a bit easier if we just ask them to update their NuGet version.

**Comment by lbargaoanu** [comment]
That's for @jbogard.

**Comment by jbogard** [comment]
We release about once a quarter. You can track the milestone for progress.
