### ISSUE TITLE
AutoMapper calls extension methods with absent (null) source object

### ISSUE THREAD

**Issue by satfx** [AutoMapper/AutoMapper#2276]
### Source/destination types
```
public class Foo
{
	public Bar Bar { get; set; }
}

public class Bar
{
	public string Name { get; set; }
}

public class FooDto
{
	public string BarSimpleName { get; set; }
}

public static class BarExtensions
{
	public static string GetSimpleName( this Bar source )
	{
		if (source == null)
			throw new ArgumentNullException(nameof(source));
		return "SimpleName";
	}
}
```
### Mapping configuration
```
Mapper.Initialize(v => {
	v.IncludeSourceExtensionMethods(typeof(BarExtensions));
	v.CreateMap<Foo, FooDto>();
});
```
### Expected behavior
Receive null (default value) in property BarSimpleName of the type FooDto.

### Actual behavior
ArgumentNullException in BarExtensions.GetSimpleName method (source equals to null). Why AutoMapper (AM) calls this method for the absent (null) source object? In AM 3.2.1 (I'm not checked any higher versions after it) it is worked all fine.

### Steps to reproduce
```
var input = new Foo {
	/* Works fine when uncommented.
	Bar = new Bar {
		Name = "Name"
	}
	*/
};
var output = Mapper.Map<FooDto>(input);
```

**Comment by lbargaoanu** [comment]
3.2.1 is a long time ago. I'd say it's more relevant what was the behavior in the version before 5. Because people might depend on that.

**Comment by satfx** [comment]
Mb you are right, but it is common to check for null the first argument in extension methods. And very uncommon to add changes to existing extension methods so they work with AutoMapper. For example, take a look on Enumerable static class AM adds extension methods from by default.

**Comment by lbargaoanu** [comment]
So what's the behavior in the last version before 5?

**Comment by satfx** [comment]
v3.2.1	null (as expected)
v3.3.1	null (as expected)
v4.0.4	null (as expected)
v4.1.1	null (as expected)
v4.2.1	null (as expected)
v5.0.2	exception
