### ISSUE TITLE
Processing Get-Only Properties

### ISSUE THREAD

**Issue by rog1039** [AutoMapper/AutoMapper#2277]
So this is probably more of a feature request, rather than a bug, but I am wondering how I can handle the mapping from the source class to the target class in the code below. 

I like to map from simple properties in my source types to "wrapper-like" properties in my target types. So that I do not overwrite the target "wrapper-like" properties, I like to make them getter-only.

In this example, the "wrapper-like" property is of type ```ReactiveProperty<T>```. So those target properties are ```{ get; }``` only and not ```{ get; private set; }``` so that it is not possible to overwrite it. I didn't include all the code for ReactiveProperty<T> since it would just pollute the sample code and included the only relevant property, the Value property.

I initially thought AfterMap would work, however, if the property is getter-only, then it seems to be totally skipped by Automapper and my AfterMap code is never called. I tried to work around this by adding the following to my mapping configuration: ``` c.ShouldMapProperty = info => true; ``` however, the get-only property is still skipped.

I then thought that perhaps an ITypeConverter might work since it seems the destination property value is passed in the mapping function, however, again the property is skipped if it is getter-only. If I make the destination property ``` private set; ``` then it will work only if I create a ReactiveProperty<T> in the converter, assign its Value property, and then return the ReactiveProperty.

So I guess my question is basically if it is possible to have Automapper do the mapping somehow while the target property is get-only. If there was a way for AfterMap to be configured so that get-only properties were included then my code would work great.

Has anyone else run into a similar situation? Thanks!

### Source/destination types

```csharp
    public class PersonDto
    {
        public string FullName { get; set; }
    }

    public class PersonViewModel
    {
        public ReactiveProperty<string> FullName { get; } = new ReactiveProperty<string>();
    }

    public class ReactiveProperty<T>
    {
        public T Value { get; set; }
    }
```

### Mapping configuration

```csharp
var cfg = new MapperConfiguration(c =>
            {
                //Two methods, neither works when the PersonViewModel.FullName property is a get-only property. 
                //If the target property is either "set;" or "private set", then mapping using either method below works.
                //The destination ReactiveProperty must have a setter of some type, otherwise, automapper will skip it.
                
                //Method 1: Type Converter
                c.CreateMap<string, ReactiveProperty<string>>().ConvertUsing<ReactivePropertyTypeConverter<string>>();

                //Method 2: AfterMap method
                //c.CreateMap<string, ReactiveProperty<string>>().AfterMap((prop, reprop) =>
                //{
                //    reprop.Value = prop;
                //});
                c.CreateMap<PersonDto, PersonViewModel>();
            });



    public class ReactivePropertyTypeConverter<T> : ITypeConverter<T, ReactiveProperty<T>>
    {
        public ReactiveProperty<T> Convert(T source, ReactiveProperty<T> destination, ResolutionContext context)
        {
            destination = new ReactiveProperty<T>();
            destination.Value = source;
            return destination;
        }
    }
```

### Version: x.y.z
AutoMapper.6.1.1

### Expected behavior

See my beginning explanation, basically to be able to perform some action against a get-only property.

### Actual behavior

See my beginning explanation, basically the get-only target property is ignored.

### Steps to reproduce

Here is all the code including the unit test:

```csharp
public class ReactivePropertyTypeConverterTests
    {
        [Fact()]
        [Trait("Category", "Instant")]
        public void Test()
        {
            var cfg = new MapperConfiguration(c =>
            {
                //Two methods, neither works when the PersonViewModel.FullName property is a get-only property. 
                //If the target property is either "set;" or "private set", then mapping using either method below works.
                //The destination ReactiveProperty must have a setter of some type, otherwise, automapper will skip it.

                //Method 1: Type Converter
                //c.CreateMap<string, ReactiveProperty<string>>().ConvertUsing<ReactivePropertyTypeConverter<string>>();

                //Method 2: AfterMap method
                c.CreateMap<string, ReactiveProperty<string>>().AfterMap((prop, reprop) =>
                {
                    reprop.Value = prop;
                });
                c.CreateMap<PersonDto, PersonViewModel>();
            });

            var mapper = cfg.CreateMapper();

            var personDto = new PersonDto(){FullName = "hello world"};
            var personViewModel = mapper.Map<PersonViewModel>(personDto);

            Assert.Equal(personViewModel.FullName.Value, personDto.FullName);
        }
    }

    public class PersonDto
    {
        public string FullName { get; set; }
    }

    public class PersonViewModel
    {
        public ReactiveProperty<string> FullName { get; } = new ReactiveProperty<string>();
    }

    public class ReactivePropertyTypeConverter<T> : ITypeConverter<T, ReactiveProperty<T>>
    {
        public ReactiveProperty<T> Convert(T source, ReactiveProperty<T> destination, ResolutionContext context)
        {
            destination = new ReactiveProperty<T>();
            destination.Value = source;
            return destination;
        }
    }

    public class ReactiveProperty<T>
    {
        public T Value { get; set; }
    }
```

**Comment by lbargaoanu** [comment]
This works through [constructor mapping](https://github.com/AutoMapper/AutoMapper/wiki/Construction).

**Comment by rog1039** [comment]
Hi lbargaoanu!

I thought about constructor mapping but hoped there was some other way. Constructor mapping is not as useful in my case because my source/target objects can have a great many properties. 

To support the mapping via constructor mapping I would have a constructor with 10+ parameters and my constructor would have 10+ assignment statements like PropA.Value = propA. So what I would end up writing is essentially the same as a static convert method I could write if I wasn't using Automapper at all.

Using Constructor mapping:
```csharp
public PersonViewModel(string fullName, string address1, .... string zip)
{
    FullName.Value = fullName;
    Address1.Value = address1;
    .....
    Zip.Value = zip;
}
```

Using static Convert method
```csharp
public static PersonViewModel Convert(PersonDto dto)
{
    var vm = new PersonViewModel();
    vm.FullName.Value = dto.FullName;
    vm.Address1.Value = dto.Address1;
    .....
    vm.Zip.Value = dto.Zip;
}
```

I understand if what I am asking is outside of what Automapper is built to support. I can write my own reflection-based "mapper" to do this step for me. I was just hoping I was unaware of some built-in Automapper feature.

If future plans ever make it possible for the AfterMap feature to work on properties/fields that are get-only then an ITypeConverter like I showed in my first post would work perfectly and I would not have to do anything. That would be very useful in my case.

Thanks for your help!

**Comment by lbargaoanu** [comment]
You can create a map between string and your type and it will be called for your constructor parameters. But you still have to assign the fields. I think you should be able to map to get only properties by using UseDestinationValue (as in #2126), overriding the default behavior. But you would have to do it in a generic way with ForAllMembers or ForAllPropertyMaps.

**Comment by lbargaoanu** [comment]
[Existing destination](https://github.com/AutoMapper/AutoMapper/blob/859612d672a45c62f3cce5c8b236be796497c916/src/UnitTests/CollectionMapping.cs#L26) and [new destination](https://github.com/AutoMapper/AutoMapper/blob/859612d672a45c62f3cce5c8b236be796497c916/src/UnitTests/CollectionMapping.cs#L55).

**Comment by rog1039** [comment]
Yes, as you say, the constructor parameters and assigning the fields are still necessary, which in this specific case takes about as much work as the static Convert function I would code by hand without AutoMapper.

I didn't consider what was suggested in #2126 . That does work if I change my CreateMap call to look as follows:
```csharp
            var cfg = new MapperConfiguration(c =>
            {
                c.CreateMap<string, ReactiveProperty<string>>().AfterMap((prop, reprop) =>
                {
                    reprop.Value = prop;
                });
                c.CreateMap<PersonDto, PersonViewModel>()
                    .ForMember(z => z.FullName, opt =>
                    {
                        opt.MapFrom(z => z.FullName);
                        opt.UseDestinationValue();
                    });
            });
```
Of course, as you also mentioned, I would really need to do this using ```ForAllMembers```. And to make it such that I didn't have to do this for every DTO->ViewModel mapping, I am guessing I would need to do something more **generic** by using the ```ForAllMaps()``` method.

So to make it generic for a given map and for that map's properties, I changed the config code to the following:
```csharp
c.ForAllMaps((map, mapExpression) =>
  {
    mapExpression.ForAllOtherMembers(memberExpression =>
      {
        if (memberExpression.DestinationMember is PropertyInfo pi && pi.PropertyType.Name == "ReactiveProperty`1")
        {
          memberExpression.MapFrom(pi.Name);
          memberExpression.UseDestinationValue();
         }
      });
  });
```

This works quite well. This gets me most of the way towards what I am looking for. I lose out on some automapper features (or rather, I have to re-implement them myself-such as property name matching since I hard-code in the line ```memberExpression.MapFrom(pi.Name);```).

Reading through issue #2126 I saw @jbogard comment https://github.com/AutoMapper/AutoMapper/issues/2126#issuecomment-304319053 where he said 

> An aside, maybe it's a bit weird that we just skip adding property maps that don't have a setter vs. adding them and then deciding how to deal with it.

I would add a +1 to that idea so that we would have a way to hook into AutoMapper to configure the handling of get-only properties. If that were possible then it seems likely that my original 
```csharp
c.CreateMap<string, ReactiveProperty<string>>().AfterMap((prop, reprop) =>
                {
                    reprop.Value = prop;
                });
```
would have worked fine since that property would not have been skipped by AutoMapper.

That capability would make AutoMapper even more powerful. If you guys are looking for features to add in future versions of AutoMapper, this would certainly get my vote.

Thanks for your help!
