### ISSUE TITLE
Unable to map serialized types with Min or Max property names

### ISSUE THREAD

**Issue by ymiao45** [AutoMapper/AutoMapper#2281]
### Source/destination types

```csharp
public class Serialized
{
    public double Min { get; set; }
    public double Max { get; set; }
}

public class From
{
    public Serialized Test { get; set; }
}

public class To
{
    public string Test { get; set; }
}
```

### Mapping configuration

```csharp
var builder = new MapperConfiguration(x =>
{
    x.CreateMap<To, From>()
        .ReverseMap();

    x.CreateMap<string, Serialized>()
        .ConstructUsing(y => JsonConvert.DeserializeObject<Serialized>(y))
        .ReverseMap()
        .ConstructUsing(y => JsonConvert.SerializeObject(y));

    x.CreateMissingTypeMaps = true;
});
var mapper = builder.CreateMapper();
```

### Expected behavior

Correct console output:

{"Min":1.23,"Max":2.34}
1.23
2.34

### Actual behavior

Actual console output:

{"Min":1.23,"Max":2.34}
0
0

### Steps to reproduce

```csharp
var test = new From
{
    Test = new Serialized
    {
        Min = 1.23,
        Max = 2.34
    }
};

var test2 = mapper.Map<To>(test);
Console.WriteLine(test2.Test);

var test3 = mapper.Map<From>(test2);
Console.WriteLine(test3.Test.Min);
Console.WriteLine(test3.Test.Max);
```

**Comment by lbargaoanu** [comment]
What happens if you remove CreateMissingTypeMaps and just create what you need?

**Comment by lbargaoanu** [comment]
[Working gist](https://gist.github.com/lbargaoanu/4d617a932e7412d0fd2be7afd55df888).

**Comment by ymiao45** [comment]
It throws an exception on the second map from string to Serialized type.

It will work if I change the property names to Min1 and Max1, so it's some kind of problem with the names.

However, I have found that using ConvertUsing instead will work.

``
x.CreateMap<string, Serialized>().ConvertUsing(y => JsonConvert.DeserializeObject<Serialized>(y));
``

**Comment by lbargaoanu** [comment]
Exactly :) ConstructUsing just constructs, when in fact you want  to do the mapping yourself, that's ConvertUsing. The Min/Max thing is about the default naming conventions and LINQ. String is ```IEnumerable<char>```. So min and max get mapped to those extension methods by default.

**Comment by ymiao45** [comment]
Oh, I see. I didn't know this distinction between ConstructUsing and ConvertUsing. Thanks!
