### ISSUE TITLE
Member Ignore Should Apply to Unflattening

### ISSUE THREAD

**Issue by L45eMy** [AutoMapper/AutoMapper#2284]
### Source/destination types

```csharp
class SourceClass
{
    public string Name { get; set; }
    public ChildClass Child { get; set; }
}

class ChildClass
{
    public string Name { get; set; }
}

class DestinationClass
{
    public string Name { get; set; }
    public string ChildName { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<SourceClass, DestinationClass>()
    .ReverseMap()
    .ForMember(m => m.Child, o => o.Ignore());
// The following line is needed for expected behavior
//  .ForPath(m => m.Child.Name, o => o.Ignore());
```

### Version: x.y.z
6.1.1

### Expected behavior

When ignoring the `Child` property, unflattening for the `ChildName` property is also ignored.

### Actual behavior

A new object is created in the `Child` property with `Name = "abc"`.

### Steps to reproduce

```csharp
var destination = new DestinationClass { Name = "abc", ChildName = "def" };
var source = Mapper.Map<SourceClass>(destination);
source.Child.ShouldBeNull();
```
See [Gist](https://gist.github.com/L45eMy/179008f896bc97c7f593b9fa94418f41) for complete code.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
