### ISSUE TITLE
Property or indexer  cannot be assigned error

### ISSUE THREAD

**Issue by lesiano** [AutoMapper/AutoMapper#2289]
Hello,
I'm using AutoMapper  for to classes, for example:

```
class a {
int Id {get;set;}
string b {get;set;}
}

class b {
int Id {get;}
string b {get;set;}
}
```
and I'm trying to map the two classes like:

` Mapper.Map(a, b)`;

I also add the the configuration:
  `cfg.CreateMap<a, b>().ForMember(x => x.Id, opt => opt.Ignore() );`

In other classes is working fine, but for this one I don't understand whats the problem: It's returning the error: 

> Property or indexer 'b.Id' cannot be assigned to -- it is read only"

Can someone have a clue what's is going on?

Thanks

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lesiano** [comment]
Hi @lbargaoanu 

Thanks for your help.  I saw where is the problem. Because its module work I use Mapper.Initialize twice. And seems that its override each other so this why it is giving an error. Is this possible to add a CreateMap configuration without overrides what exists already?

Thanks

**Comment by lbargaoanu** [comment]
Yes. See [this](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=AllowAdditiveTypeMapCreation). But it won't help with calling Initialize twice :) Also, properties without setters are ignored by default.
