### ISSUE TITLE
Mapper.Map throwing exception when a null is returned from ConstructUsing and source have nullable prop

### ISSUE THREAD

**Issue by reazhaq** [AutoMapper/AutoMapper#2290]
### Biz Rule
with source with some valid properties; create a destination with that and/or some other values; else return NULL (don't create any destination object)

### Source/destination types
```csharp
public class Source
{
	public int? SomeId1 { get; set; }
	public int? SomeId2 { get; set; }
}

public class Destination
{
	public int? SomeId1 { get; set; }
}
```

### Mapping configuration
```csharp
static void Main(string[] args)
{
	Mapper.Initialize(cfg =>
	{
		cfg.CreateMap<Source, Destination>()
			.ConstructUsing(source =>
			{
				if (source.SomeId2.HasValue)
					return new Destination
					{
						SomeId1 = source.SomeId2
					};
				return null;
			});
	});
	Mapper.AssertConfigurationIsValid();

	var s = new Source();
///////// this throws exception 
	var d = Mapper.Map<Destination>(s);
	Console.WriteLine($"d is null: {d==null}");
}
```

### Version: x.y.z
AutoMapper: 6.1.1
Console: .net core 1.1
IDE: VS 2017 Pro

### Expected behavior
null destination object

### Actual behavior
exception thrown.  Looks like it is trying to access source properties after returning from ConstructUsing.

### Steps to reproduce

```csharp
	var s = new Source();
///////// this throws exception 
	var d = Mapper.Map<Destination>(s);
```

**Comment by lbargaoanu** [comment]
ConstructUsing must return smth. Try ConvertUsing or test before calling Map.

**Comment by reazhaq** [comment]
Thanks - interesting distinction; semantically makes sense.  ConvertUsing is working for me
```
                cfg.CreateMap<Source, Destination>()
                    .ConvertUsing(source => source.SomeId2.HasValue
                        ? new Destination { SomeId1 = source.SomeId2 }
                        : null);
```

**Comment by lbargaoanu** [comment]
You can see the difference yourself in [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping).

**Comment by reazhaq** [comment]
Thx - I shall give it a try
