### ISSUE TITLE
Throw Exception When Mapping To/From Same Instance

### ISSUE THREAD

**Issue by ardalis** [AutoMapper/AutoMapper#2302]
Ran into a scenario today where *sometimes* we were trying to map to and from the same instance of a type. The scenario is that we have an instance of an entity, and we don't know if it's tracked by the ORM (EF), so we grab an instance from EF and map the modified instance to the existing instance. This pattern works fine if the modified instance isn't tracked by EF, since EF will return a new instance:
```
public void Save(SomeEntity entity)
{
  var existingEntity = db.SomeEntities.First(e => e.Id == entity.Id);
  mapper.Map(entity, existingEntity);
  db.SaveChanges();
}
```
When `ReferenceEquals(entity,existingEntity)` we shouldn't map. It just causes problems, especially since the entity has a collection property which either throws a "can't modify collection while enumerating" exception or (if we tell it to MapFrom the ToList of the collection) it makes copies of all items in the collection and adds them in.

Is it a valid scenario for AutoMapper to attempt to map from an instance to itself? Assuming not, can we have it throw an exception when this is detected? Since this would be a breaking change, maybe it could be something specified in config?

**Comment by lbargaoanu** [comment]
Mapping between instances of the same type just causes problems and you shouldn't be doing it. You can avoid mapping to the same instance by checking for this in BeforeMap. You can even try to apply that wherever you want with ForAllMaps.

**Comment by ardalis** [comment]
Good to know. Thoughts on building this behavior in (via throwing an exception, for instance)?

**Comment by lbargaoanu** [comment]
The way I see it, we shouldn't be making it easier for people to do things we advise against :)

**Comment by ardalis** [comment]
Meaning you agree with me AM should throw if it sees someone attempting this...

**Comment by lbargaoanu** [comment]
You're missing my point. You shouldn't be mapping between objects of the same type (regardless if they are the same instance or not). This causes problems and it's not an interesting use case.

**Comment by ardalis** [comment]
Fair enough. Normally I would map from a DTO to an Entity and this would never be an issue. The code in question is something found in a client's codebase where they're not using a DTO for their source. One way to "fix" the issue is to see if I can refactor the code to use a DTO (which I plan to look into in any case). You don't see any scenario where it makes sense to use AM to map two things of the same type?

**Comment by jbogard** [comment]
We get this question now and again, not really in EF cases but when someone
is trying to use AutoMapper for cloning. For non-cloning cases, it'll be
some other ORM framework and I'll get asked to do things like "only call
the setter if the values are different" because that ORM framework will
raise events etc. They're wanting to kinda merge things together. Although
it might be possible, I've never tried to make AutoMapper a cloning or
object merging library. It might be somewhat possible.

In these cases where it's outside our normal use case, but still possible,
and there's no clear correct default behavior based on the different
scenarios raised, you're pretty much left to the existing config.

**Comment by ardalis** [comment]
Question remains regarding AM mapping (inadvertently or not) from and to the same instance of an object. Should this be supported, or should it throw since it's likely indicating the user is trying to do something they probably don't mean to be?

Answer either way and close if plan is to do nothing. Thanks!

**Comment by jbogard** [comment]
Don't think we'll throw an exception, that'll break people. Just understand
that it's not really a supported scenario (but you can do it if you want).
