### ISSUE TITLE
SELECT N+1 problem in .net core?

### ISSUE THREAD

**Issue by fabich** [AutoMapper/AutoMapper#2305]
Hi

I'm trying to query my database over two tables.
Unfortunately, I'm running in a select n+1 problem.
Is this a general problem with ef core?

Thanks
Fabian

### Source/destination types

```csharp
    public class TblFlightschedule
    {
        public int Id { get; set; }
        public string Flightnumber { get; set; }
        public virtual ICollection<TblFlightcabinconfigurations> TblFlightcabinconfigurations { get; set; }
    }
    public class FlightReadDTO
    {
      public int Id { get; set; }
      public string Flightnumber { get; set; }
      public List<FlightCabinConfigurationCreateDTO> CabinConfigurations { get; set; }
    }

```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
    CreateMap<TblFlightschedule, FlightReadDTO>()
            .ForMember(dest => dest.CabinConfigurations, opt => opt.MapFrom(src => src.TblFlightcabinconfigurations));
```

### Version: x.y.z
.net core 1.1
AutoMapper 6.1.1
AutoMapper.Extensions.Microsoft.DependencyInjection 2.0.1

### Expected behavior

I expected one DB query with a join

### Actual behavior

One query for all flights and then one query per single flight for cabinconfigurations

### Steps to reproduce

```csharp
    var test2 = Db.TblFlightschedule
                .ProjectTo<FlightReadDTO>()
```
### Expression
```csharp
    Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[myproject.DAL.Models.TblFlightschedule].Select(

    // Quoted to induce a closure:
    dto => new FlightReadDTO
    {
            Id = dto.Id,
            CabinConfigurations = dto.TblFlightcabinconfigurations.Select(dto => new FlightCabinConfigurationReadDTO
                {
                    Id = dto.Id,
                    FkTravelclass = dto.FkTravelclass
                }).ToList()
     })
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by fabich** [comment]
you are right, this looks like an ef core issue.
https://github.com/aspnet/EntityFrameworkCore/issues/4007

**Comment by fabich** [comment]
would it be possible to add a workaround to automapper until this is fixed?
first call would map to entity, second call maps to dto

**Comment by jbogard** [comment]
EF Core doesn't know how to do this (yet). You'll need to still have an
Include.

**Comment by fabich** [comment]
As far as I understand the include only works if I map to the entity type.
So for each query I have to first write a normal LINQ query to the db and then I can use AutoMapper to map the table entity to the dto.
Otherwise the include will be ignored.

Am I understanding this correctly?

**Comment by lbargaoanu** [comment]
```csharp
    var test2 = Db.TblFlightschedule
                .Include(e=>e.TblFlightcabinconfigurations)
                .ProjectTo<FlightReadDTO>()
```

**Comment by jbogard** [comment]
That's right. EF Core can figure out FK navigation properties' Include right, but not collections.

Also if you look at the SQL query EF Core also doesn't know how to filter out columns, it'll bring back the whole entity.
