### ISSUE TITLE
Automapper slow performance in first use

### ISSUE THREAD

**Issue by irajchardoli** [AutoMapper/AutoMapper#2310]
Hi , I have a mvc core project with ef core 1.1.2 . i using automapper for mapping between entity and view model , but when map per entity to viewmodel , in first time is very slow . 

is this normal?
how to improve performance in first map?

Mvc Core 1.1.2
Ef Core 1.1.2
I use AutoMapper 6.1.1 .

**Comment by jbogard** [comment]
You can call CompileMappings to compile all the expressions up front. It's
a trade off.

https://github.com/AutoMapper/AutoMapper/wiki/Configuration#configuration-compilation

**Comment by lbargaoanu** [comment]
You can also try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build. That should fix it. If it doesn't, we need a repro.

**Comment by irajchardoli** [comment]
I use MyGet build , and also call CompileMappings , but still first map is very slow.

This is my automapper configuration in startup of mvc core project:


`  
 
            var config = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new BuyWell.ViewModels.AutoMapperProfileConfiguration());
                //cfg.AddProfile(new BuyWell.ViewModels.AutoMapperCustom());
                cfg.AllowNullCollections = true;
                cfg.ForAllMaps((mapType, mapperExpression) => { mapperExpression.MaxDepth(1); } );
            });

            //config.CompileMappings();
            var mapper = config.CreateMapper();
            mapper.ConfigurationProvider.CompileMappings();

            services.AddSingleton(mapper);`

**Comment by lbargaoanu** [comment]
You don't need CompileMappings anymore with the MyGet build. 
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
And remove that ForAllMaps. That couldn't possibly help :)

**Comment by irajchardoli** [comment]
In profile configuration  , if i comment all other map configuration ,the performance will be good.

**Comment by lbargaoanu** [comment]
I'm not sure what that means, but without a repro we can't help.

**Comment by irajchardoli** [comment]
@lbargaoanu I Remove ForAllMaps and now performance is much better than before. thanks.

**Comment by lbargaoanu** [comment]
Good to know :)
