### ISSUE TITLE
Does this project already support .NET Standard or .NET Core?

### ISSUE THREAD

**Issue by marcofranssen** [AutoMapper/AutoMapper#2312]
Does this project already support .NET Standard or .NET Core?

We are looking for a solution which runs .NET standard or .NET core.

If not what would be the required investment to make it compatible with .NET Core or .NET Standard. I have been using this framework in a project 8 years ago and I really loved it. Would be awesome if we can use it again in this new project.

**Comment by lbargaoanu** [comment]
Yes. See [here](https://github.com/AutoMapper/AutoMapper/blob/01a4010e252f4a5763848c70313491854f9ba74c/src/AutoMapper/AutoMapper.csproj#L8).

**Comment by marcofranssen** [comment]
Awesome.... I should have figured this myself. Thanks for the quick reply.
