### ISSUE TITLE
dot net standard 2 support?

### ISSUE THREAD

**Issue by drminor** [AutoMapper/AutoMapper#2314]
Have you considered targeting .NET Standard 2.0?
I am preparing to contribute a few updates to AutoMapper that will allow mapping from a regular class to a dictionary<string, object> where name matching is performed using the 
ISourceToDestinationNameMapper interface, by creating MemberInfo entries on the fly.

I think that .NET Standard 2.0 has support for some of the things I need where PCL and .NET Standard 1.3 does not.

**Comment by jbogard** [comment]
Yeah I don't care just add the conditional compilation entries as you need.
I don't want to drop support of 1.3

**Comment by lbargaoanu** [comment]
I think a better way to handle this is to change that interface to not use MemberInfo, but some other structure you could try to fill also when doing dynamic mapping.

**Comment by drminor** [comment]
jbogard, thank you. I agree keeping 1.3 support is important. I actually was able to do what I needed without any changes to the targeted platforms. The caller is responsible for creating the property or field info structures.

**Comment by drminor** [comment]
lbargaoanu, Updating the ISourceToDestinationNameMapper interface to use something other than MemberInfo would be quite a bit of work. I do think that it would be nice to create a custom interface that addresses the exact needs of the classes that inspect and use the type details, however this may slow things down since one would have to create an instances that implement the interface from instances of PropertyInfo and FieldInfo quite often -- or am I missing something.

Perhaps it would be better if I let you review my proposed changes and then we could discuss further.

**Comment by lbargaoanu** [comment]
It wouldn't matter much because that would happen only at config time. Config is slow. Yes, open a PR.
