### ISSUE TITLE
Request for a new "ExtraMembers" branch

### ISSUE THREAD

**Issue by drminor** [AutoMapper/AutoMapper#2315]
Please create a new branch named: "ExtraMembers". I would like to for you to see my proposed changes to about a dozen files. I've got the code working well and have a self contained unit test.

I'm new to GitHub, so please forgive me if this is not the proper protocol.

**Comment by lbargaoanu** [comment]
It isn't :) You fork the repository, you create a feature branch and from that you create a PR. There must be a getting started doc on github.
