### ISSUE TITLE
Turn Null Checks Off

### ISSUE THREAD

**Issue by chrispepper1989** [AutoMapper/AutoMapper#2316]
Hi, 

Our code broke when updating to 6.1.0 from 6.0.2 and I am pretty sure the reason is this change:
https://github.com/AutoMapper/AutoMapper/pull/2115

We map from a Nullable bool to a class and originally it invoked the following:
```csharp
 public QuestionState(bool? asBool) : this(StateFromNullBool(asBool))
        {
            
        }
```

Where we set an internal enum based on the setting of the bool:
```csharp
       public static QuestionStates StateFromNullBool(bool? asBool)
        {
   
            if (asBool == null)
            {
                return QuestionStates.Na;
            }

            return asBool.Value ? QuestionStates.Yes : QuestionStates.No;
        }
```
However now, I think due to the change above, it never goes into that constructor,  when the bool is null, instead it appears to be setting the Question State itself to null. Which we don't want, is there any way we can override this behavior? 

-Thanks, Chris

### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
You can create a map from bool and use NullSubstitute instead.

**Comment by lbargaoanu** [comment]
Another way:
```c#
static void Main(string[] args)
{
	Mapper.Initialize(cfg =>
	{
		cfg.CreateMap<bool?, Destination>().ConvertUsing(s=>s == null ? new Destination { Product = "null"} : new Destination { Product = "not null"});
	});
	Mapper.AssertConfigurationIsValid();
	
	Mapper.Map<bool?, Destination>(null).Dump();
}

public class Destination
{
    public string Product {get;set;}
    public string Description {get;set;}
}
