### ISSUE TITLE
Bug - condition not working  as expected

### ISSUE THREAD

**Issue by avindor** [AutoMapper/AutoMapper#2318]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration
    .ForMember(d => d.LicenseNumber, o =>
                {
                    o.Condition(s => !string.IsNullOrEmpty(s.LicenseNumber?.FirstPart) &&
                                     !string.IsNullOrEmpty(s.LicenseNumber.SecondPart) &&
                                     !string.IsNullOrEmpty(s.LicenseNumber.ThirdPart));

                    o.ResolveUsing(carData =>
                    {
                        string licenseNumber = $"{carData.LicenseNumber.ThirdPart}-{carData.LicenseNumber.SecondPart}-{carData.LicenseNumber.FirstPart}";
                        return licenseNumber;
                    });
                })
```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Expected behavior
Auto mapper should ignore this property when s.LicenseNumber == null

In previous version (5.??), It worked as expected, but after upgrading to 6.1.1 - An exception is being
thrown (null reference) when automapper tries to map the property even when it is null
### Actual behavior
The condition code never executes and therefore a null reference exception is being thrown

### Steps to reproduce

```csharp

Condition is not working at all - for all the properties I've configured.
First I define a condition, then I use resolve using 


```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
Most likely a PreCondition would fix it.

**Comment by avindor** [comment]
Thanks for the very quick reply. You were right, the Precondition did fix it. Thanks.
