### ISSUE TITLE
Nested mapping question.

### ISSUE THREAD

**Issue by caloggins** [AutoMapper/AutoMapper#2319]
[Here's my gist](https://gist.github.com/caloggins/c9b1139a3ab6d269571e788032c1ea1c)

I'm not sure this is an issue as much as it is a question. I'm looking for a way to map nested objects which do not follow naming conventions. I could swear, many moons ago, there was way to do this.

### Source/destination types

```csharp
    public class Foo
    {
        public string LastChanged { get; set; }
        public Bar Bar { get; set; }
    }

    public class Bar
    {
        public bool IsSystemData { get; set; }
    }

    public class Flat
    {
        public string LastChanged { get; set; }
        public bool IsSystemData { get; set; }
    }
```

### Mapping configuration

```csharp
    public class Mapper : Profile
    {
        public Mapper()
        {
            
            // *** works, but feels clunky
            //CreateMap<Foo, Flat>()
            //    .AfterMap((foo, flat, context) => context.Mapper.Map(foo.Bar, flat));
            //CreateMap<Bar, Flat>();

            // *** works, but seems very coupled (foo to bar) :(
            //CreateMap<Foo, Flat>()
            //    .ForMember(dest => dest.IsSystemData, _ => _.MapFrom(src => src.Bar.IsSystemData));

            // *** doesn't work, but seems to be the nicest
            CreateMap<Foo, Flat>();
            CreateMap<Bar, Flat>();
        }
    }
```

### Expected behavior

I expect the last mapping profile config to work.

### Actual behavior

It doesn't work. I need to use one of the other two configurations.

### Steps to reproduce

```csharp
        [SetUp]
        public void SetUp()
        {
            var configuration = new MapperConfiguration(with => with.AddProfile<Mapper>());
            mapper = configuration.CreateMapper();
        }

        [Test]
        public void ItShouldMapIsSystemData()
        {
            var foo = GetSource();

            var result = mapper.Map<Flat>(foo);

            Assert.That(result.IsSystemData, Is.True);
        }
```

**Comment by lbargaoanu** [comment]
Naming convention or MapFrom. The AfterMap is a hack. The coupling is in the model, not in the mapping :) An aside. "_" means I don't care about that parameter, but you do care, you use it, so give it a name, I don't know, maybe source :)

**Comment by caloggins** [comment]
Thanks for the response. We've been flying w/ the middle option (`MapFrom()`).

I believe I hint in the question and the gist that naming conventions are not an option.

Agreed about `AfterMap()`. It's just one of the options that does work.

Thanks for the note about the underscore. I was intentionally emphasizing the source and destination mappings over using a config:, "For member `dest.IsSystemData`, map from `src.Bar.IsSystemData`," over, "For member `dest.IsSystemData`, use `configuration` to map from `src.Bar.IsSystemData.`

The coupling I was referring to was that a config now knows that IsSystemData is a property of Bar, *and* Bar is a property of Foo. The last option (which is the way I thought I remembered it working around v4) sidesteps that. Though, it's probably not really that important.

**Comment by lbargaoanu** [comment]
As far as I know AM never did smth like that.
