### ISSUE TITLE
Eager loading with ProjectTo and Computed properties

### ISSUE THREAD

**Issue by ajbeaven** [AutoMapper/AutoMapper#2321]
I'm attempting to use ProjectTo with EF Core (1.1.2) to map a NotMapped/Computed property that needs to make use of eager loading in order to return the correct result.

While my actual use case is obviously more complicated, I've added a cut down example below.

### Source/destination types

```csharp
public class Library
{
	public int Id { get; set; }
	public List<Book> Books { get; set; }
	
	[NotMapped]
	public int NumberOfBooks => Books.Count();

	private Library()
	{
		Books = new List<Book>();
	}
}

public class Book
{
	public int Id { get; set; }
}

public class LibraryDto
{
	public int Id { get; set; }
	public int NumberOfBooks { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
	cfg.CreateMap<Library, LibraryDto>();
});
```

### Version: x.y.z
6.1.1

### Expected behavior
When Automapper goes to map the computed property, that the resources are correctly loaded in order to return the correct result.

### Actual behavior
Adding a breakpoint inside the `NumberOfBooks` property shows that the `Books` navigation property has not been eagerly loaded, so `NumberOfBooks` is always 0.

### Steps to reproduce

```csharp
var libraryDto = context.Libraries
	.Include(l => l.Books)
	.Where(l => l.Id == libraryId)
	.ProjectTo<LibraryDto>(mappingConfiguration)
	.Single();
```

**Comment by ajbeaven** [comment]
Ahh, I see [here](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions) that it mentions that queryable extensions do not support calculated property on the domain object.

For those that come after me struggling with this, I resolved it by using expressions:

```csharp
Mapper.Initialize(cfg =>
{
	cfg.CreateMap<Library, LibraryDto>()
		.ForMember(dest => dest.NumberOfBooks, opts => opts.MapFrom(GetNumberOfBooks());
});

public static Expression<Func<Library, int>> GetNumberOfBooks()
{
	return l => !l.Books.Count();
}
```

**Comment by lbargaoanu** [comment]
[Gist](https://gist.github.com/lbargaoanu/e97aac49d7b333c515cb89886f22ba11).

**Comment by jbogard** [comment]
Also EF Core may not support this scenario. Try without AutoMapper too to
see what works. I've had to write Include quite a bit too for EF Core
projections, it's not as simple as EF6

**Comment by ajbeaven** [comment]
Thanks for that @lbargaoanu, sorry should have done that myself.

Doing this with `.Select()` had the same result. `Books` is not loaded at the time the computed property is evaluated. Would you expect this to work with EF6? That'd surprise me based on the aforementioned comment in the docs...

**Comment by lbargaoanu** [comment]
The gist works with EF6. But note that I removed the book count from the entity, it's just in the DTO.

**Comment by ajbeaven** [comment]
Oh, sorry no I didn't notice that. To clarify, `Select()` does not work with the _computed property_ (as expected) and I haven't tested that gist on EF Core. I've found the AutoMapper projections to work flawlessly with EF Core, so good job on the re-write front!

**Comment by jbogard** [comment]
The reason projections work flawlessly in EF Core is that EF Core pulls the entire graph into memory and then does in-memory projection. You'll need to make sure you have the right `Include`'s. See my ContosoUniversityDotNetCore app for more details.
