### ISSUE TITLE
Links to https://github.com/AutoMapper/AutoMapper/wiki/Migrating-from-static-API not working

### ISSUE THREAD

**Issue by merrickjeff** [AutoMapper/AutoMapper#2326]
Where can I find the Migrating from static API document? 

There are links to https://github.com/AutoMapper/AutoMapper/wiki/Migrating-from-static-API all over the place but there's nothing there.

Thanks

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Static-and-Instance-API

There is no need to migrate from anything. The static API is still there and will continue to be there. It's just a choice you can have now.
