### ISSUE TITLE
Mapper.Configuration.AssertConfigurationIsValid() falsely passing when using ReverseMap()

### ISSUE THREAD

**Issue by leandro-fernandez** [AutoMapper/AutoMapper#2327]
### Source/destination types

```csharp
public class SourceObject {
  public long Id { get; set; }
  public string SomeProperty { get; set; }
}

public class TargetObject {
  public string TargetProperty { get; set; }
}
```

### Mapping configuration

```csharp
public class MappingProfile : Profile
{
  public MappingProfile()
  {
    CreateMap<SourceObject, TargetObject>()
       .ForMember(t => t.TargetProperty, opt => opt.MapFrom(s => s.SomeProperty))
       .ReverseMap()
       .ForMember(s => s.SomeProperty, opt => opt.MapFrom(t => t.TargetProperty));
  }
}
```

### Version: x.y.z

`<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="2.0.1" />`

### Expected behavior

We expect the Mapper Configuration Assertion to fail, as `SourceObject`'s `Id` is being neither mapped nor ignored in any `ForMember` after `ReverseMap()`.

In other words, we expect the behavior to match that of:

```csharp
CreateMap<SourceObject, TargetObject>()
  .ForMember(t => t.TargetProperty, opt => opt.MapFrom(s => s.SomeProperty));

CreateMap<TargetObject, SourceObject>()
  .ForMember(s => s.SomeProperty, opt => opt.MapFrom(t => t.TargetProperty));
```

### Actual behavior

The assertion appears to pass.

### Steps to reproduce
```csharp
Mapper.Initialize(cfg =>
{
  cfg.AddProfile<MappingProfile>();
});

Mapper.Configuration.AssertConfigurationIsValid();
```

**Comment by jbogard** [comment]
Ah, this is the expected behavior. ReverseMap is different, it assumes you're literally flattening and un-flattening. For un-flattening, you'd want to assert that the *source* side is all mapped, not the destination. Reverse map doesn't assume you want to assert anything, since you've already validated the Source -> Destination mapping.

In short, ReverseMap is now "special" and not merely a short cut for two CreateMap calls.

**Comment by martanko** [comment]
Just a note for anybody who lands here in search for how to enable validation on reverse rules as I did - When creating reverse map, use `.ReverseMap().ValidateMemberList(MemberList.Destination)` or alternatively before asserting configuration, do something like this: `foreach (var map in mapCfg.GetAllTypeMaps().Where(m => m.ConfiguredMemberList == MemberList.None)) map.ConfiguredMemberList = MemberList.Destination;`
