### ISSUE TITLE
A new CreateMap ignore all previous CreateMap in version 5+

### ISSUE THREAD

**Issue by jsgoupil** [AutoMapper/AutoMapper#2330]
### Source/destination types

```csharp
    public class Source
    {
        public int Id { get; set; }
        public string CodeName { get; set; }
        public string Nickname { get; set; }
    }

    public class Destination
    {
        public int Id { get; set; }
        public string CodeName { get; private set; }
        public string Nickname { get; set; }
    }
```

### Mapping configuration

```csharp
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Source, Destination>()
                    .ForAllMembers(opt => opt.Ignore());
                cfg.CreateMap<Source, Destination>()
                    .ForMember(dest => dest.CodeName, opt =>
                    {
                        opt.MapFrom(src => src.CodeName);
                        opt.PreCondition((context) =>
                        { // Not called in 5.0
                            var x = context.ConfigurationProvider;
                            return false;
                        });
                    });
                cfg.CreateMap<Source, Destination>()
                    .ForMember(dest => dest.Nickname, opt =>
                    {
                        opt.MapFrom(src => src.Nickname);
                        opt.PreCondition((context) =>
                        {
                            var x = context.ConfigurationProvider;
                            return true;
                        });
                    });
            });
            IMapper mapper = config.CreateMapper();
```

### Steps to reproduce
```csharp
            var _destination = mapper.Map<Source, Destination>(new Source { Id = 5, CodeName = "007", Nickname = "Jimmy" });

            Console.WriteLine(_destination.Id);
            Console.WriteLine(_destination.CodeName);
            Console.WriteLine(_destination.Nickname);
```

### Expected behavior
In version 4.2.1
0

Jimmy

### Actual behavior
In version 5.0.0+
5
007
Jimmy

### Behavior change
I seem to understand that doing multiple CreateMap will erase what was previously entered. I don't think this is captured on the upgrade guide of 5.0

https://github.com/AutoMapper/AutoMapper/wiki/5.0-Upgrade-Guide

Now I can chain my two `ForMember`, but `ForAllMembers` returns void. Which means this nifty trick right presented here: http://stackoverflow.com/questions/4367591/how-to-ignore-all-destination-members-except-the-ones-that-are-mapped

Is not working anymore.

I had to chain everything and finish with `ForAllOtherMembers(opt => opt.Ignore());`

can we mention this in the upgrade guide?

The biggest takeaway here is that there are a lot of people on the old AutoMapper, and starting version 5, you cannot use `CreateMap` multiple time on the same Destination/Source
A quick example in the upgrade guide would help a lot. Because you can find a lot of old CreateMap on StackOverflow

**Comment by jbogard** [comment]
Why are you calling ForAllMembers.Ignore()? That seems odd to me, what behavior are you trying to get here?

**Comment by jsgoupil** [comment]
Check the Stackoverflow link.
It was proposed a while ago to call ForAllMembers.Ignore() first, then call ForMember to override that ignore.

**Comment by jbogard** [comment]
I don't understand why you'd want to use AutoMapper in this case? You want to not map anything *except* what you've explicitly map? That's like the complete opposite of Auto-Mapping, why not just manually map (or call ConvertUsing) ?

**Comment by jsgoupil** [comment]
I didn't post my entire code here, but basically I was doing IgnoreAll except the one that had a [SpecialAttribute] on each of them.

I am not looking for a workaround anymore, I found it... but as you can see I am not the only one trying to do this. You can search on stackoverflow and this question and other similar questions got a lot of attention.

The biggest concern that took me a while to figure out was

cfg.CreateMap<Destination, Source>().ForMember(...);
cfg.CreateMap<Destination, Source>().ForMember(...); // This will erase the previous one. That was not the case in AutoMapper 4-

**Comment by jbogard** [comment]
What we'll likely do in the future is throw an exception, it's not obvious what should happen and no one would agree about the right behavior.

**Comment by jbogard** [comment]
Looks like we'll start doing this in 6.3
