### ISSUE TITLE
OneTimeSetUp: AutoMapper.DuplicateTypeMapConfigurationException

### ISSUE THREAD

**Issue by jigneshkvp** [AutoMapper/AutoMapper#2331]
After upgrading to 6.1.1 from 6.0.2, I have started getting OneTimeSetUp: AutoMapper.DuplicateTypeMapConfigurationException exception. 

Example: I have the following scenario:
There are two object with the same name but in different namespaces (all in one assembly).
Project folder structure:
**Project Folder** contains
- **_Test_** Folder
-----Peron.cs (namespace: Com.Data.Test)
- Person.cs (file is outside the test folder, namespace Com.Data)

### Source/destination types
```csharp
// First object
namespace Com.Data
{
    public class Person
    {
        [DataMember]
        public string FirstName{ get; set; }
        [DataMember]
        public string LastName { get; set; }
    }
}

// Second object
namespace Com.Data.Test
{
    public class Person
    {
        public string FirstName{ get; set; }
        public string LastName { get; set; }
        public string GivenName { get; set; }
    }
}
```

### Mapping configuration

```csharp
// Com.Data.PersonProfile.cs
using System;
using Com.Data;

namespace Com.Data.Mapping
{
    public class PersonProfile : Profile
    {
        CreateMap<Person, Com.Data.Test.Person>()
                .ForMember(destinationMember => destinationMember.GivenName, opt => opt.Ignore())
                .ReverseMap();
    }
}
```

### Expected behavior

In the older version (6.0.2) there was no exception and Mapper.AssertConfigurationIsValid() went OK.

In the new version (6.1.1), it should also work as it did before.
### Actual behavior

Exception is raised with the following message:

OneTimeSetUp: AutoMapper.DuplicateTypeMapConfigurationException : The following type maps were found in multiple profiles:

Com.Data.Person to
  Com.Data.Test.Person defined in profiles:

Com.Data.PersonProfile
Com.Data.PersonProfile

### Steps to reproduce
Create the basic setup as described above and just assert the configuration.

**Comment by dmaterowski** [comment]
hey @jigneshkvp, have you managed to fix it? I'm facing the same issue

**Comment by jigneshkvp** [comment]
Hello Daniel, 
I am not facing this issue any more. I identified the cause, I added the same profile twice in my code flow.
