### ISSUE TITLE
Mapping to an existing list gives new list, instead of reusing the destination.

### ISSUE THREAD

**Issue by joelluijmes** [AutoMapper/AutoMapper#2332]
### Source/destination types

```csharp
private sealed class SourceObject
{
    public int UniqueId { get; set; }

    public string Name { get; set; }
}

private sealed class TargetObject
{
    public int Id { get; set; }

    public int UniqueId { get; set; }

    public string Name { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<SourceObject, TargetObject>()
        .ForMember(dst => dst.Id, opts => opts.Ignore());
});
```

### Version: 
6.2.0-ci-01390; 6.1.1

### Expected behavior
The same behavior when you use Automapper on a single instance, where I can find the original target object in the target collection, with an Id of 42 but with an overwritten Name.

### Actual behavior
Result collection is a new colleciton where TargetObject Id has been defaulted.

### Steps to reproduce
```csharp
var sourceObjects = new[]
{
    new SourceObject
    {
        UniqueId = 10,
        Name = "Foo"
    }
};
var targetObjects = new[]
{
    new TargetObject
    {
        Id = 42,
        UniqueId = 10,
        Name = "Bar"
    }
};
targetObjects = mapper.Map(sourceObjects, targetObjects);
        
var sourceObject = new SourceObject
{
    UniqueId = 10,
    Name = "Foo"
};
var targetObject = new TargetObject
{
    Id = 42,
    UniqueId = 10,
    Name = "Bar"
};
targetObject = mapper.Map(sourceObject, targetObject);
```

### Desciption
When looking at the execution plan of the collection, I see the following:
```csharp
(IList<Program.TargetObject>)var passedDestination = mapperDestination;
            var collectionDestination = ((passedDestination == null) || ((ICollection<Program.TargetObject>)passedDestination).IsReadOnly)
    ? (IList<Program.TargetObject>)new List<Program.TargetObject>()
    : passedDestination;

collectionDestination.Clear();
```

Why does the destination collection gets cleared if there is one?* What I expect is to reuse the destination collection and then perform the mapping. This would be inline with the behavior of mapping to a single destination (where it overwrites the properties in the destination but leaves ignored properties intact.)

\* while writing this, an explanation came up; what should be done if the collections are not ordered or worse, are not equal in size. I can imagine that this is the reason a new collection is created, but on the other hand wouldn't it be more logical if it just worked like I did? And if the user has a mismatch of collections, isn't their fault? (The user could just pass a new collection in it for the original behavior.)

Maybe this could be a new feature to allow for the same collection be used? Or maybe if it already exists, I'd be happy to hear it.

_Full gist: https://gist.github.com/joelluijmes/c72c4cefcdc7f78eba791ba7069980da_

**Comment by TylerCarlson1** [comment]
[AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection) does exactly this.

You will have to provide AM.Collections the way to identify equality between the two items.
There is support for EF in AutoMapper.Collections.EntityFramework that supports comparing classes by your Primary Keys in EF.  Also supports things like persistance with Insert/Update/Delete so you don't have to write the search by ID code.
