### ISSUE TITLE
InvalidOperationException when using .ProjectTo() on map with .ResolveUsing(Func)

### ISSUE THREAD

**Issue by whimzee** [AutoMapper/AutoMapper#2334]
.ResolveUsing(Func) does not seem to map correctly when using .ProjectTo() on a IQueryable. I expect the example below to run without issue but I am instead greeted with an exception with very little detail on the problem when calling this method, making me think this is internal. Without using .ProjectTo() this does not happen at all. The issue does also not occur with .MapTo(), so it seems to be specific to just .ResolveUsing(Func).

```csharp
var model = db.Errands
    .ProjectTo<ErrandDTO>()
    .ToList();
```

`System.InvalidOperationException: 'No generic method 'ToList' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.`

### Source/destination types

```csharp

public class Errand
{
    public int Id { get; set; }
    public string CustomerName { get; set; }
    public ICollection<Checkbox> Checkboxes { get; set; }
}

public class ErrandDTO
{
    public int Id { get; set; }
    public string CustomerName { get; set; }
    public ICollection<CheckboxDTO> Checkboxes { get; set; }
}

public class Checkbox
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Value { get; set; }
    public virtual ICollection<Errand> Errand { get; set; }
}

public class CheckboxDTO
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Value { get; set; }
    public bool Checked { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => {
    cfg.CreateMap<Errand, ErrandDTO>()
        .ForMember(src => src.Checkboxes, conf => conf.ResolveUsing(f =>
        {
            var checkboxes = db.Checkboxes
                .ProjectTo<CheckboxesDTO>()
                .ToList();

            checkboxes.Where(x => f.Checkboxes.Any(c => x.Id == c.Id))
                .ForEach(x => x.Checked = true);

            return checkboxes;
        }
    ));
    cfg.CreateMap<Checkbox, CheckboxDTO>()
        .ForMember(src => src.Checked, conf => conf.UseValue(false));
});
```

**Comment by jbogard** [comment]
ResolveUsing is not supported for projections, see the wiki on LINQ projections for supported operations.

Also, you've got a closure there, you're reaching outside the ResolveUsing function to grab a DbContext - don't do that, your configuration should not have dependencies. If you need that, there are specific ways to do DI and AutoMapper (check the wiki).
