### ISSUE TITLE
ForAllMembers causes to overwrite with empty array when configured to not overwrite with nulls

### ISSUE THREAD

**Issue by michalkorecki** [AutoMapper/AutoMapper#2335]
The behavior to not overwrite with null values seems to be broken for arrays when using `ForAllMembers` method. When source array is `null`, destination will have empty array assigned. 

Example: https://gist.github.com/michalkorecki/07668a48e8252866b54acda76ef6f689

### Source/destination types

```csharp
public class Source
{
	public int? Id { get; set; }
	public int[] Foos { get; set; }
	public int[] Bars { get; set; }
}

public class Destination
{
	public int? Id { get; set; }
	public int[] Foos { get; set; }
	public int[] Bars { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(configuration =>
{
	configuration
		.CreateMap<Source, Destination>()
		.ForAllMembers(opt => opt.Condition((s, d, sv, dv) => sv != null));
});

var origin = new Destination { Foos = new[] { 1 }, Bars = new[] { 2 }, Id = 5 };
var source = new Source { Foos = new[] { 1, 2, 3 }, Bars = null, Id = null };
var destination = Mapper.Map<Source, Destination>(source, origin);
```

### Expected behavior

`Bars` array remains the same as in `origin` instance and program prints:

 ```
Foos =
  not null
    1
    2
    3
Bars =
  not null
    2
Id =
  5
```

This behavior can be achieved when each property is configured separately (using `ForMember(d => d.Bars, opt => opt.Condition(s => s.Bars != null))`).

### Actual behavior

`Bars` array is replaced with empty array even though it was `null` in source instance:

```
Foos =
  not null
    1
    2
    3
Bars =
  not null
Id =
  5
```

Nullabe `Id` property works as expected.

**Comment by jbogard** [comment]
Have you tried `AllowNullDestinationCollections` ? AutoMapper assumes that destination collections should have *something* instead of null.

**Comment by michalkorecki** [comment]
Setting `configuration.AllowNullCollections` to true does indeed make it work as expected, although it feels like a hack -- that's exactly opposite of what I am trying to do, unless it was meant to be `AllowNullSourceCollections` vs _replace null source collections with empty_, which seems to be the default. `DoNotReplaceNullSourceCollectionsWithEmpty` would be horrible, but more explicit name :-)
