### ISSUE TITLE
`ProjectTo` Cannot Project to `get`-only Collection Property

### ISSUE THREAD

**Issue by chrisoverzero** [AutoMapper/AutoMapper#2336]
### Source/destination types

```csharp
class Source
{
  public List<int> Values { get; } = new List<int>();
}

class Destination
{
  public List<int> Values { get; } = new List<int>();
}
```

### Mapping configuration

```csharp
e.CreateMap<Source, Destination>()
  .ForMember(dto => dto.Values, c => c.UseDestinationValue());
```

### Expected behavior

When projecting to a `get`-only collection property (irrespective of whether the source property is `get` or `get`-`set`), the members of the source collection property are projected to the destination collection property.

Given that `Map` can do this and EF Core can do this, I expected the combination of the two to be able to do this. (Though the behavior is also exhibited when EF Core is removed from the picture – see repro.)

### Actual behavior

In **6.1.0**, this throws an exception.

Since #2205 fixed #2155 (tested specifically with **6.2.0-ci-01390**), the destination property is empty.

### Steps to reproduce

See [gist][].

[gist]: https://gist.github.com/chrisoverzero/2b861a07722cc5850e76379e7a701252

Thank you.

**Comment by jbogard** [comment]
The easiest thing would be to add a setter.

EF Core does this because it doesn't really support LINQ projection. It still hydrates entities and then uses in-memory execution to fill your destination objects. Basically ProjectTo is useless for EF Core (you may have noticed you still need to do Include, you can't project child collections etc.)

**Comment by chrisoverzero** [comment]
> The easiest thing would be to add a setter.

I understand.

> Basically ProjectTo is useless for EF Core [...]

Nevertheless, it is surprising behavior.

But if it's not gonna be, then it's not gonna be. Thank you.

**Comment by jbogard** [comment]
Many things in EF Core are surprising! Right now our target for projections is EF6, it's the most robust projection support. EF Core is still a fairly immature product in this area.
