### ISSUE TITLE
Extra property mapping with member access for Reverse Map

### ISSUE THREAD

**Issue by AndreyYurashevich** [AutoMapper/AutoMapper#2340]
### Expected behavior

I admit it's quite debatable but I'd expect that in the case when there is a mapping for some extra property the property with the same name will be used for the reverse map.

### Actual behavior
In reality, AutoMapper skips destination's property with the same name and uses an extra property.
### Steps to reproduce
See [unit test gist](https://gist.github.com/AndreyYurashevich/45d06c881b57cade8b19e0c97ced0327) for details.

**Comment by lbargaoanu** [comment]
The MapFrom is reversed, just don't use ReverseMap if you don't want it.
