### ISSUE TITLE
 Ignore all null properties of all types on the source object from overwriting destination 

### ISSUE THREAD

**Issue by doktrova** [AutoMapper/AutoMapper#2341]
I would like to see a global configuration for  Ignoring all null properties of all types on the source object from overwriting destination. That should include numbers, collections and all other types.

The case for this would be Patching a record on the database. If the user provides only the properties they want to update on the DTO when that DTO gets mapped to the actual model it should only update the provided properties. 

```
//Models     
class User {       
public string Name {get; set;}      
 public string Email {get; set;}      
 public string Password {get; set;}    
 }      

class UserDto {      
 public string Name {get; set;}       
public string Email {get; set;}     
}  

//Start instances      
var user = new User { Name = "John", Email = "john@live.com", Password = "123"};       
var userDto = new UserDto { Name = "Tim" }; //Notice that we left the Email null on the DTO  

 //Mapping     
Mapper.Map(userDto, user);

```

The result ends up with the user having a null email and password. I know how to write optional mapping for a few types but it would be nice to have a property that does it for every type. I want the user email to not be changed unless a new email is provided on the source (userDto). In other words **ignore all null properties of all types on the source object from overwriting destination** (User)

**Comment by lbargaoanu** [comment]
You can do that yourself. One way would be to use ForAllPropertyMaps. There is some complexity with nullables, but it can be done. This was discussed in some form many times before, usually related to conditions.

**Comment by doktrova** [comment]
I'm stuck at the collections part

`cfg.AllowNullCollections = true`
doesn't seem to work.

**Comment by jbogard** [comment]
What happens if the user actually clears out a value?

**Comment by doktrova** [comment]
@jbogard 

Then it will be empty not null on the source.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2335

**Comment by TylerCarlson1** [comment]
@doktrova 
For updating collections AM doesn't handle updating collections back to the ORM by default.  https://github.com/AutoMapper/AutoMapper.Collection is designed to handle these situations.

Although I don't think it will handle your null check collection issue you have.  Maybe it does I've never tried.
If you **REALLY** want to get around this problem you can create your own IObjectMapper and call that check the null and skip else default back to AM.Collections mapping.

**Comment by doktrova** [comment]
@TylerCarlson1 Thank you. I don't think the collections one works for my need. I just thought it will be good to have this feature as a on/off switch on the config because it seems very useful, at least to me.

**Comment by doktrova** [comment]
My work around until a fix comes.


`var patchInput = new ExpandoObject() as IDictionary<string, object>;  foreach (var property in userDto.GetType().GetProperties())     if (property.GetValue(userDto) is var propertyValue && !propertyValue.IsNullOrDefault())         patchInput.Add(property.Name, propertyValue);  Mapper.Map(patchInput, user);`
--

**Comment by jayrosen1576** [comment]
I wrote a small extension for the `IMapperConfigurationExpression` to handle this scenario (also creates a reverse mapping):

```
    public static class IMapperConfigurationExtensions
    {
        public static void CreateDualMapping<TSource, TDestination>(this IMapperConfigurationExpression cfg)
        {
            cfg.CreateMap<TSource, TDestination>().ForAllMembers(opt => opt.Condition((source, dest, sourceMember, destMember) => (sourceMember != null)));
            cfg.CreateMap<TDestination, TSource>().ForAllMembers(opt => opt.Condition((source, dest, sourceMember, destMember) => (sourceMember != null)));
        }
    }
```

I call it like this:
```
AutoMapper.Mapper.Initialize(cfg => {
    cfg.CreateDualMapping<MyClass1DTO, MyClass1>();
    cfg.CreateDualMapping<MyClass2DTO, MyClass2>();
    ...
});
```

Your destination object will retain any non-null property values that are not specified or are null in the source object. I'm not sure if this is the best way to accomplish this but I have the same use case and it works.

**Comment by doktrova** [comment]
@jayrosen1576  Have you tried it with collections and value types?

**Comment by jayrosen1576** [comment]
@doktrova Yes and it *was* working, however since upgrading to the latest version on Friday it no longer appears to be. I found another solution that shows promise although I have not fully tested it yet:

https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-265670132

It's a bit frustrating since it would seem this would be a basic requirement for a mapper at least in the web API world. Doesn't make sense to have to pass the entire object back and forth if updating only one or two properties.

**Comment by doktrova** [comment]
Did this get resolved or simply closed. I don't have an answer that works yet.

**Comment by chadwackerman** [comment]
New to AutoMapper and I don't know who @lbargaoanu is. But he appears to be an arrogant prick who has no interest in fixing this obvious use case.

I just read through a half dozen ignored and silently-closed bugs, plus weird sample code from him that doesn't work.

Make a Product with a decimal price field. Write a PATCH method taking an object with a decimal? field. AutoMapper proudly sets the product price to 0 and the only recourse is to abandon ship because the workarounds are frankly nonsense. Same for bools, ints, and any other simple type because of a default() bug introduced in 5.x.

**Comment by jbogard** [comment]
@jayrosen1576  It got closed. This isn't a use case I want to support. I don't use PATCH in the Web API world. I don't expose database entities directly through HTTP. I really only want to support use cases that I  can make judgement calls on whether the behavior makes sense or not. If I would never use a behavior I would have to support someone else's opinion, forever.
