### ISSUE TITLE
Why is the .NET Core Benchmark so Fast?

### ISSUE THREAD

**Issue by RehanSaeed** [AutoMapper/AutoMapper#2345]
I wrote a benchmark to test Automapper against a raw manual mapping (The Baseline below) and also a couple of extension methods I wrote to help with manual mapping. Automapper is slower when mapping a single object and collections but there is one exception. Automapper is considerably faster when mapping a `List<T>` of objects on .NET Core (It's still slower on full .NET Framework).

|             Method |  Job | Runtime |      Mean |     Error |    StdDev |       Min |       Max | Scaled | ScaledSD |  Gen 0 | Allocated |
 |------------------- |----- |-------- |----------:|----------:|----------:|----------:|----------:|-------:|---------:|-------:|----------:|
 |           Baseline |  Clr |     Clr |  1.969 us | 0.0354 us | 0.0332 us |  1.927 us |  2.027 us |   1.00 |     0.00 | 2.0523 |   6.31 KB |
 |      My Mapper |  Clr |     Clr |  9.016 us | 0.1753 us | 0.2019 us |  8.545 us |  9.419 us |   4.58 |     0.12 | 2.0447 |   6.31 KB |
 |         Automapper |  Clr |     Clr | 12.185 us | 0.1717 us | 0.1606 us | 11.883 us | 12.414 us |   6.19 |     0.13 | 2.4719 |   7.62 KB |
 |           Baseline | Core |    Core |  1.820 us | 0.0346 us | 0.0355 us |  1.777 us |  1.902 us |   1.00 |     0.00 | 2.0542 |   6.31 KB |
 |      My Mapper | Core |    Core |  9.043 us | 0.1725 us | 0.1613 us |  8.764 us |  9.294 us |   4.97 |     0.13 | 2.0447 |   6.31 KB |
 |         Automapper | Core |    Core |  3.673 us | 0.0785 us | 0.1940 us |  3.399 us |  4.304 us |   2.02 |     0.11 | 2.4757 |   7.62 KB |

I was totally surprised and interested in understanding why Automapper is so fast in that one benchmark. I've also included the entirety of my custom mapper below if anyone is interested:

```
public interface IMapper<in TSource, in TDestination>
{
    void Map(TSource source, TDestination destination);
}

public static TDestination Map<TSource, TDestination>(
    this IMapper<TSource, TDestination> translator,
    TSource source)
    where TDestination : new()
{
    var destination = new TDestination();
    translator.Map(source, destination);
    return destination;
}

public static List<TDestination> MapList<TSource, TDestination>(
    this IMapper<TSource, TDestination> translator,
    List<TSource> source)
    where TDestination : new()
{
    var destinationCollection = new List<TDestination>(source.Count);
    foreach (var item in source)
    {
        var destination = new TDestination();
        translator.Map(item, destination);
        destinationCollection.Add(destination);
    }
    return destinationCollection;
}
```

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping). But other than that, we want to know too :) Hopefully it's our carefully crafted code, and not a benchmark oversight.

**Comment by RehanSaeed** [comment]
Will give that a try. You can find my benchmark in my GitHub repo at https://github.com/ASP-NET-Core-Boilerplate/Framework Just run the benchmark project (I'm using Benchmark.NET).

**Comment by lbargaoanu** [comment]
For best performance, you need to set [this](https://github.com/AutoMapper/AutoMapper/blob/8f2e43f586066e35ec59cafff426932fc059a8c6/src/Benchmark/Program.cs#L6). I don't care about the rest, but the AM part in your benchmark looks good to me.

**Comment by jbogard** [comment]
How many times are you calling Map in this benchmark?

**Comment by lbargaoanu** [comment]
@jbogard It's Benchmark.NET, it does its thing.

**Comment by RehanSaeed** [comment]
It sounds like you're not aware of writing any code to make .NET Core faster, so it must be the platform improvements that Microsoft blogged about not too long ago.

**Comment by lbargaoanu** [comment]
You don't have to guess :) Profile it.
