### ISSUE TITLE
Upgrading from 2.1.267 to 6.1.1, site won't load

### ISSUE THREAD

**Issue by cblaze22** [AutoMapper/AutoMapper#2346]
I have held this off for a while, but I am trying to upgrade 2.1.267 to 6.1.1.  I was able to get it to compile and made the syntax corrections.

When I run the ASP.NET website, the site just never loads, like it's in an infinite loop.  Could there be a code or configuration in this new version that is causing a circular reference that may of not been in the previous version?

How can I diagnose this or find out more information?

```
Mapper.Initialize(cfg =>
            {

});
```

**Comment by cblaze22** [comment]
Found the actual problem, stackoverflow on a Entity Framework entity to a datamodel.   Why would this work in the older version and not this newest version?

```return Mapper.Map<List<Event>, List<EventModel>>(_eventsRepository.GetMany```

**Comment by cblaze22** [comment]
Adding this below worked.  Hopefully there are no consequences for my other 500 mappings.

 ```cfg.ForAllMaps((typeMap, mapConfig) => mapConfig.PreserveReferences());```

**Comment by lbargaoanu** [comment]
Don't. Remove all calls to PreserveReferences and upgrade to the latest from MyGet.

**Comment by cblaze22** [comment]
What do you mean upgrade to MyGet? What is that?

**Comment by lbargaoanu** [comment]
Google it.

**Comment by cblaze22** [comment]
What will downloading this do? I use NuGet, why do I need that?

**Comment by jbogard** [comment]
MyGet is the CI build that has some of these issues fixed for you.
Instructions on the wiki and the readme.

**Comment by cblaze22** [comment]
Oh ok, please use context when stating to do something.  Am I assuming my question here has a fix in this latest build or not?  I hate to go through this whole ordeal if it won't fix my issue and I am fine waiting for the NuGet package if so.

**Comment by jbogard** [comment]
Yes, we've put in work in the 6.2 release to detect when you need to
preserve references and automatically do so. Would like feedback to see if
this fixes your issues.

**Comment by cblaze22** [comment]
Will do

**Comment by cblaze22** [comment]
Well the newest build worked like a charm, at least on the load of the site.  Ill do some more testing, and when adding features, use this setup so I can catch any issues.  I assume this build is not production ready at all and I should wait for a stable, probably NuGet download?

**Comment by jbogard** [comment]
Every build is production ready, releases are just about locking in SemVer
for public API.

**Comment by cblaze22** [comment]
Great Ill play around with this version.  Thanks for the help.
