### ISSUE TITLE
Extremely slow mapping on client's 64-bit backend

### ISSUE THREAD

**Issue by Gamingdevil** [AutoMapper/AutoMapper#2349]
I'll start off with explaining the situation. We used to have AutoMapper 4.X, which worked fine, we recently upgraded to 5.2.0 which still worked fine for several months. Even though some views were relatively slow the first time they were opened because the compilation of the mapping happens on first use. I know this to be a feature and we were fine with it. Our slowest initial mapping, with many complex sub objects, at the time was about 6 seconds.

Now we have just deployed it, for the first time since the AutoMapper upgrade to the test environment of a big client and everything is much slower. Suddenly mapping compilations take ages, exponentially more than both our local DEV machines, or other production clients and our own test environments. That slow mapping mentioned above now takes ~1.5 minutes.

To remedy this initially, we used the the Configuration.ComileMappings, this made the startup slightly slower on our own environments, but now it takes several minutes on the clients test environment. However, it did help, a bit, though it seems that initial mappings are still slower than consecutive ones, apparently due to some form of CompileMappings still happening.

There was however one situation were the time spent mapping was still abhorrent. It had lazy loading turned on (entity framework, without AutoMapper extensions), so the mapping of course did a bunch of fetches, but when profiling the bottle neck was still mapping compilation. It happens to be on the same type as the slowest mapping mentioned above. The lazy loading has since been removed, but the fact remains that for some reason mapping compilation is still incredibly slow.

On a hunch, I tried changing the pool of the backend from 64-bit to 32-bit and suddenly everything behaves like it would on our own environments: just a few seconds the first time (or about 30 for CompileMappings) This is however not accepted as a permanent solution.

Our own backends are also generally 64 bit and we have test environments in both x86 and x64, it is really only this on premise client server that is causing trouble. It's also unlikely that the machine is simply too weak, if anything it is simply too strong (double octa-core and 64 GB RAM) That's really the only thing we can see different between their machine and ours.

Is there anything that you can think of that could cause this, or better yet, that could fix it? I have a dotTrace timeline dump available of the difficult method, with lazy loading on, in both 32-bit, but the zip file is too large to attach.

### Source/destination types
Long and convoluted. Know that it is multiple (5+) levels of complex objects deep.

### Mapping configuration
Too much to really paste

### Version: 5.2.0
I tried changing the dll's to version 6.1.1 but the issue remains

### Expected behavior
Expected that the behaviour would be the same across environments.

### Actual behavior
Extremely slow mapping compilations on this particular machine, not reproducible anywhere else.

### Steps to reproduce
Only running the mapping on the client's server has been causing issues.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by lbargaoanu** [comment]
Even if you call CompileMappings, some compilation still takes place if you use an object based Map overload. The most likely culprit is ```Map<Destination>(source)```. The alternative is ```Map<Source, Destination>(source)```. I guess this could be changed, but then CompileMappings will probably take twice as long.

**Comment by jbogard** [comment]
Do you have some more information about the client machine? Specs? Version of .NET Framework installed?

**Comment by jbogard** [comment]
What version of the .NET Framework is on that machine? I've never heard of this issue, and mapping compilation is CPU-bound.

**Comment by Gamingdevil** [comment]
@jbogard 
According to the registry on the server, the .NET version is 4.5.2
Specs are Intel Xeon CPU E5-2640 v3 @2.60GHz, 2 of them so total of 16 cores and 32 threads, 64 GB RAM, Windows Server 2012 R2 Standard.

I'm in the process or testing with the 6.2 version. At first sight, recycling the app pool takes twice as long for 64-bit as on 32-bit (1:42 vs 51s), presumably mostly because of the mapping compilation, but this is  hard to profile as there is of course a new thread starting. 

@lbargaoanu I'm not entirely sure why the culprit is Map<Destination>(source), does that cause some mappings to recompile?

**Comment by lbargaoanu** [comment]
First try the MyGet build, that should solve it.

**Comment by Gamingdevil** [comment]
I just tested some setups with the old and new dll. Since the lazy loading has been removed from our code, I just tested startup times of the pool, when the mappings are first compiled (done by hitting recycle and timing how long the page load of the backend takes), with the MyGet version startup is significantly faster in 64 bit, it took "only" 1m42s compared to the ~4m30s on version 5.2.0. Both are still significantly slower than 32-bit startup though, which took 51s on the MyGet version and a minute on 5.2.0.

Is there any discernible reason for this?

**Comment by jbogard** [comment]
Not that I know of, we compile for Any CPU and it's literally just expression compilation. What CPU architecture is this?

**Comment by lbargaoanu** [comment]
I would guess it's the 64 bit JIT vs the 32 bit one. But you would have to verify that indeed the time is spent jit compiling.

**Comment by lbargaoanu** [comment]
@jbogard When we call Compile and get a delegate, we get executable code, for the respective platform.

**Comment by Gamingdevil** [comment]
Our backend is also built for Any CPU if that helps. That's why I could freely change the pool between 32-bit and 64-bit.

I would be surprised if you would do anything significantly different based on the architecture, so perhaps it's the .NET internals that do something wonky.

However, remember that our normal clients, as well as our own dev machines and test environments are 64-bit as well, so it must be something specific on that server.

**Comment by lbargaoanu** [comment]
So when we call Compile on a lambda we get the IL back, but actually the problem with a big execution plan is the JIT compiling.

**Comment by jbogard** [comment]
Is it a Xeon processor on the server?

**Comment by Gamingdevil** [comment]
@jbogard , yes Intel Xeon CPU E5-2640 v3

**Comment by lbargaoanu** [comment]
I think as far as AM is concerned this issue is solved. With the MyGet build you don't need CompileMappings anymore. The compile should be fast enough to be made just in time.

**Comment by jbogard** [comment]
Ah I missed that.

Yeah, don't do CompileMappings if you have a ton of mappings or they're very large.

**Comment by Gamingdevil** [comment]
@lbargaoanu @jbogard , we put in CompileMappings initially because the initial mapping took way too long, much longer than it would on our own environments. (the client can't be expected to wait for over a minute the first time they open a screen) Are you saying this will be significantly faster in the next version, without a disparity between the environments?

**Comment by lbargaoanu** [comment]
I'm afraid the difference between environments is your problem to solve. We've changed the way compilation happens so it only depends on how many properties you have. If you still have issues with the MyGet build, a repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by jbogard** [comment]
And I can only think it's related to the Xeon processor and .NET Framework in that environment. Of course we could try a faster expression compiler https://github.com/dadhi/FastExpressionCompiler but I don't know if that's going to fix it. I also don't know if it's actually expression compilation that's slow, or the JIT taking the dynamic assembly and compiling it.

I don't have any spare dual octo-core Xeon servers to test either :)

**Comment by lbargaoanu** [comment]
Well, the last time I investigated a similar issue, it was the JIT, that's why I keep bringing it up :)

**Comment by Gamingdevil** [comment]
@lbargaoanu I was also afraid that it would be my problem to fix, it was kind of a long shot to ask you for help based on hypothesis.

Just to clarify, with the pull request you opened today, this issue will be "fixed" the same way that it's better on the MyGet version? 

If we disable CompileMappings at the start, will the first mapping take ridiculously long on this server again or be within acceptable ranges? (I can't access the server for testing right now)

And to summarise: you're basically saying that the processor architecture has some sort of influence on the way the mappings are compiled, but you're not entirely sure why. Am I understanding this right?

@jbogard: we all need more dual octa-core processors in our lives ;)

**Comment by lbargaoanu** [comment]
No, the PR today is almost unrelated :) The MyGet build should be ok. When the mappings are compiled, the last step is JIT compiling, that means compiling to the target architecture. So this makes it the first suspect. But real life tends to be complicated, so there could be many other reasons that would make the compile slow. That's why we have profilers and stuff :)

**Comment by Gamingdevil** [comment]
So when I get the chance, I can do some additional testing without CompileMappings at the start and get you some profiles on both architectures if it's still slow?

**Comment by lbargaoanu** [comment]
No, if the time is spent JIT compiling and it's slow on one architecture, but works on another, then it's either a problem with your server or a problem with the JIT compiler. Either way, there is little we can do about it. A repro is something else :)

**Comment by jayrosen1576** [comment]
@Gamingdevil is your client using a VM or is the OS installed on the bare hardware? I am encountering a similar result here. I can run the CompileMappings locally on my dev PC (Windows 7 64-bit) for ~200 mappings in about 13 seconds. The exact same app takes about 3 min 30 secs on the production VM (Windows 2012 R2, 64-bit). The CPU spikes at 100% during the compile process. It also is using a Xeon processor.

**Comment by Gamingdevil** [comment]
@jayrosen1576 Yes, the servers are installed on a VM, with VMWare to be exact. So perhaps it is a combination of the OS with that processor architecture being on a VM?

Do you also see a dramatic increase in performance when forcing the pool to 32-bit?

**Comment by jayrosen1576** [comment]
The mapper is part of a WCF service hosted in a Windows Service (or a console app when testing). I could try compiling it as a 32-bit app to see if that makes a difference. I have a feeling that the VM environment may be the common culprit somehow.

**Comment by jayrosen1576** [comment]
@Gamingdevil So I recompiled the app as a 32-bit console app and the initial mapping time went from ~35 secs to ~5 secs. This makes no sense to me. I even boosted the Virtual CPUs to 4 from 1 on the vm before recompiling and it made no difference. Why would a 64bit architecture *reduce* mapping performance? I think @jbogard may want to investigate this further.

**Comment by jbogard** [comment]
How can I investigate further?

**Comment by jayrosen1576** [comment]
I'm not sure really but it definitely has something to do with the 64-bit architecture. If I run the app in 32-bit or Any CPU the results of the JIT map compile are similar (5 secs and 7 secs, respectively). I also ran this on a hardware installed OS (non-VM) and the result is the same. Switching to a 64-bit compiled app results in a JIT map compile time of 35+ secs. I don't know what part of the JIT map compile would be causing this but since @Gamingdevil and I see similar results it's not just an isolated incident. Any info would be greatly appreciated.

**Comment by Gamingdevil** [comment]
I was finally able to do some more tests, with different configurations. I did not see the huge CPU spikes, but memory is pretty bad, though much better with the 6.2 (MyGet) version. The MyGet version is much better in general, but still seems to slow to a crawl when used on a 64-bit configuration.

![image](https://user-images.githubusercontent.com/11741578/31725554-ed4aa07e-b424-11e7-8790-db79cd48214b.png)

**Comment by jayrosen1576** [comment]
@Gamingdevil The CPU spike I saw was on the VM with only 1 configured virtual processor. Setting it to 4 reduced the CPU usage to 25% which makes sense. I get similar result using the Compile Mappings but I still take a hit (~20 secs) on the first trip to the endpoint. What doesn't make any sense is the fact that I see almost no performance hit when running the same code on my 64-bit Windows 7 workstation. I can hit the first endpoint and get a response in about 3 secs even without compile mappings whereas on the server the first hit is about 35 secs to return. Maybe it's due to something in Windows Server 2012? I am out of ideas.

**Comment by lbargaoanu** [comment]
I guess we could take a look at a repro and run it on 64 bit. We'll probably see the time is spent jitting, so I'm not sure what to do next, but we'll see once we have that repro. Meanwhile, you can solve the problem yourself with MapAtRuntime. There are a few issues that discuss this. Probably the most detailed is #2271.
