### ISSUE TITLE
ProjectTo converting Enum to integer/string with EF Core 2.0.0

### ISSUE THREAD

**Issue by kkalitowski** [AutoMapper/AutoMapper#2351]
This worked with Automapper:  6.0.2 / EF Core 1.1.1.
It also works with Automapper: 6.1.1. / EF Core 1.1.1.

I believe what caused this issue is EF Core 2.0.0.

### Source/destination types
```csharp
    // Source
    public class Extract
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ExtractId { get; set; }

        [Column("ExtractStatusId")]
        public ExtractStatus ExtractStatus { get; set; }

        [Column("ExtractTypeId")]
        public ExtractType ExtractType { get; set; }
    }

    //Destination
    public class ExtractDto
    {
        public int ExtractId { get; set; }
        public string ExtractStatus { get; set; }
        public string ExtractType { get; set; }
    }
```

### Mapping configuration

```csharp
CreateMap<Extract, ExtractDto>().ReverseMap();
```

### Version: x.y.z
6.1.1 (w/ Entity Framework Core 2.0.0)

### Expected behavior
Mapping occurs as described in the [String Conversion](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#string-conversion) documentation

Given a SQL Server table with an int field, an EF entity class with an Enum type, and a destination C# object with a string property...

When using ProjectTo<>, the C# object is set to a string of **"Complete"**.

### Actual behavior
When using ProjectTo<>, the C# object is set to a string of **"1"**.

### Steps to reproduce

```csharp
return dbContext.Extracts
                .AsNoTracking()
                .OrderByDescending(e => e.ExtractId)
                .Take(numberOfRows)
                .ProjectTo<ExtractDto>()
                .ToListAsync();
```

### Findings
EF Core 1.1.1 generates the following SQL
```SQL
exec sp_executesql N'SELECT [t].[ExtractId], [t].[ExtractStatusId], [t].[ExtractTypeId]
FROM (
    SELECT TOP(@__p_0) [e0].*
    FROM [Extract] AS [e0]
    ORDER BY [e0].[ExtractId] DESC
) AS [t]',N'@__p_0 int',@__p_0=250
````

EF Core 2.0.0 generates the following SQL.  Note the _CONVERT(VARCHAR(11)...)_. I suspect that this has something to do with the issue.
```SQL
exec sp_executesql N'SELECT TOP(@__p_0) [e].[ExtractId], CONVERT(VARCHAR(11), [e].[ExtractStatusId]) AS [ExtractStatus], CONVERT(VARCHAR(11), [e].[ExtractTypeId]) AS [ExtractType]
FROM [Extract] AS [e]
ORDER BY [e].[ExtractId] DESC',N'@__p_0 int',@__p_0=250
```

**Comment by jbogard** [comment]
Rewrite your projection using just a LINQ Select statement. If the issue still persists, you'll need to open an issue on the EF repository.

**Comment by kkalitowski** [comment]
@jbogard I'm having trouble parsing your reply. Are you saying to not use ProjectTo<>? Or are you saying try ProjectTo<> but without OrderBy and Take?

**Comment by jbogard** [comment]
Yes, ProjectTo merely creates a "select" LINQ call, so replace your auto-projection with a manual one (but still use LINQ w/ EF, don't call ToList THEN Select):

```
return dbContext.Extracts
                .AsNoTracking()
                .OrderByDescending(e => e.ExtractId)
                .Take(numberOfRows)
                .Select(e => new ExtractDto { /* set props here */
                 });
                .ToListAsync();
```

**Comment by kkalitowski** [comment]
I did try that and it does work.  I felt that it was not an acceptable solution because I can no longer use ProjectTo for most any of my queries/maps.

I was under the impression AutoMapper would nfortunately have to deal with the issue EF created for it. However, I just now found an open issue on the EF Core repo and it looks like they plan to fix it for EF Core 2.0.1.  aspnet/EntityFrameworkCore#9894.

**Comment by lbargaoanu** [comment]
@kkalitowski Well, no :) Not at this time, anyway. If it works with EF6, we blame EF Core :)

**Comment by baoduy** [comment]
I'm facing the same issue. Any workaround?

**Comment by lbargaoanu** [comment]
@baoduy A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
