### ISSUE TITLE
Linq's Distinct() not working with ProjectTo<>

### ISSUE THREAD

**Issue by AmonDoni** [AutoMapper/AutoMapper#2352]
Version: 6.1.1 and EF Core 1.1.0

Description and steps to reproduce
I have two model: DetailModel and ListModel. DetailModel have all properies of ListModel and other extra fields (left joined fieds)
I done:
```
_context.Source
.ProjectTo<DetailModel>()
.Filter(md => { /*custom filtration code without calling tolist()*/ })
.ProjectTo<ListModel>()
.Distinct()
.ToList();
```

Expected behavior

I would expect the distincted result set

Actual behavior

result set without distinct

Current workaround

Just replaced `.ProjectTo<ListModel>()` with selecting anonymous object: `.Select(dm => new { })`

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
As far as I can tell, this works with EF6. EF Core is another story altogether :)
