### ISSUE TITLE
AutoMapper Profile Configurations doesn't override

### ISSUE THREAD

**Issue by thqnhat** [AutoMapper/AutoMapper#2353]
Hello,

I had a problem when I try to override some mappings configurations using Profile.
I would like to ignore a mapping in one profile but do that mapping in another profile.

### Source/destination types

**In OrderProfile.cs:** I don't want to mapping the warehousestock. So I declare:

`
public OrderProfile()
        {

            CreateMap<Product, ProductModel>()
                .ForMember(dest => dest.WarehouseStock, opt => opt.Ignore());

        }
`

But I want do that mapping in **ProductProfile.cs:**

`
  public ProductProfile()
        {

            CreateMap<Product, ProductModel>()
                .ForMember(dest => dest.WarehouseStock, opt => opt.MapFrom(src => src.WarehouseStock));

        }
`

### Mapping configuration

**In Global.asax.cs:**
If I put OrderProfile above ProductProfile: the mappings configurations of ProductProfile was applied.

`
Mapper.Initialize(config => 
            {

                config.AddProfile<WarehouseStockProfile>();

                config.AddProfile<OrderProfile>();

                config.AddProfile<ProductProfile>();

            });
`

If I put OrderProfile under ProductProfile: the mappings configurations of OrderProfile was applied but they was applied at global (I don't want it applies for ProductProfile).

`
Mapper.Initialize(config => 
            
             {

                config.AddProfile<WarehouseStockProfile>();

                config.AddProfile<ProductProfile>();

                config.AddProfile<OrderProfile>();

              });
`

### Version: x.y.z

Version: 6.1.1

### Expected behavior

The WarehouseStock mappings shoud be applied in ProductProfile and be ignored in OrderProfile.

### Actual behavior

It doesn't work (apply mappings at global or doesn't apply at all).

Can you help me please ?

Thanks

**Comment by lbargaoanu** [comment]
There is only one map, so it's not a good idea to have the same map in multiple profiles because you would just override the one map, as you've noticed. Actually in the latest version this use case is not allowed. If you _really_ want that, you can use two separate configurations. But I'd say what you need here is a resolver for that property. You check your condition in the resolver and act accordingly.

**Comment by thqnhat** [comment]
Thanks for your reply.

Yes. I _really_ want that. I encountered some problems with OrderProfile _(something like: Cannot compare member WarehouseStock of type XYZ... Only primitive types, enumeration types and entity types are supported.)_ So I decided to not do that mapping when I query my Order.

You mentioned **Resolver** or **Separate Configurations**. How I can use that ?

Many thanks,

**Comment by lbargaoanu** [comment]
I think I want to see what's causing your error, and we'll take it from there. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by thqnhat** [comment]
The problem is similar what you have seen in this post: https://github.com/AutoMapper/AutoMapper/issues/925 

Here is my model:
**OrderModel.cs**
`
public class OrderModel {
	public IList<OrderDetailModel> Details { get; set; }
}
`
**OrderDetailModel.cs:**
`
public class OrderDetailModel {
	public ProductModel Product { get; set; }
}
`
**ProductModel.cs:**
`
public class ProductModel {
	public IList<WarehouseStockModel> WarehouseStock { get; set; }
}
`

Here is my query: **http://localhost:1178/order?$expand=Platform,Details($expand=Product;$filter=Active eq false)**

**Order API:**
`
[EnableQuery]
        public IQueryable<OrderModel> Get()
        {
            return _orderService.GetAll().ProjectTo<OrderModel>();
        }
`

**Error:**
 "Message": "An error has occurred.",
 "ExceptionMessage": "Cannot compare 'member 'WarehouseStock' of type 'PR.Octopus.API.Models.ProductModel''. Only primitive types, enumeration types and entity types are supported.",
  "ExceptionType": "System.NotSupportedException"

I can ignore the WarehouseStock mapping in OrderProfile:
```
 CreateMap<Product, ProductModel>()
                .ForMember(dest => dest.WarehouseStock, opt => opt.Ignore());
```
 => the query execute no problem.

But in Product API, I cann't see anymore WarehouseStock.
**[EnableQuery]
        public IQueryable<ProductModel> Get()
        {
            return _productService.GetAll().ProjectTo<ProductModel>();
        }**


I tried your suggestion **Mapper.AllowNullDestinationValues = false;** 
or **config.AllowNullCollections = true;**
but it seem doesn't working.

Is there possible workaround ? 

Thanks,

**Comment by lbargaoanu** [comment]
Then I guess it's not the same problem. Without a repro there is nothing we can do for you.
