### ISSUE TITLE
ConstructProjectionUsing is not working

### ISSUE THREAD

**Issue by shaukatwaqarangular** [AutoMapper/AutoMapper#2354]
Hi Guys
I have the following scenario:

Entities:
```C#
public class Jobclass
	{
                string Classcode { get; set; }
                List<Jobtype> JobType { get; set; }
	}
public class Jobtype
	{
        int? Jobclass { get; set; }
        Area FromArea { get; set; }
        Area ToArea { get; set; }
	}

public class JobModel 
    {
        public string Classcode { get; set; }
        public int? Jobclass { get; set; }
    }

public class JobModelProfile : Profile
    {
        public JobModelProfile()
        {
            CreateMap<Jobclass, List<JobModel>>()
                .ConstructProjectionUsing(jc => jc.JobType.Select(t => new JobModel {
                    Jobclass = t.Jobclass,
                    Classcode = jc.Classcode
                }).ToList());
        }
    }

Controller:
public class JobController : ApiController
    {
...
        [HttpGet]
        public List<JobModel> GetJobTypes()
        {

            var r = jobClassService.GetJobTypes()
                .ProjectTo<List<JobModel>>();

            return null;
        }
    }
```
Gives the following error:
Unable to cast object of type 'System.Linq.EnumerableQuery`1[JobModel]' to type 'System.Linq.IQueryable`1[System.Collections.Generic.List`1[JobModel]]'.

Dont know how to fix this issue. Get a reference from this link:
https://stackoverflow.com/questions/39804746/automapper-one-to-many-mapping

**Comment by lbargaoanu** [comment]
Why use AM at all? It seems easier to write a LINQ query that would achieve what you want.

**Comment by shaukatwaqarangular** [comment]
i am using automapper to map between models and entities. AM is designed to do this kind of mapping and i would like to be consistant across. If there is any better suggestion please let me know. Are you saying dont use automapper for mapping and use simple linq ?

**Comment by lbargaoanu** [comment]
Yes.

**Comment by shaukatwaqarangular** [comment]
do you have any sample example for that kind of mapping?

**Comment by lbargaoanu** [comment]
Yes, right there in your ConstructProjectionUsing :) You're already mapping it by hand.

**Comment by shaukatwaqarangular** [comment]
how come this ticket get closed :) issue is not resolved yet because this mapping i posted is giving me an error:
Unable to cast object of type 'System.Linq.EnumerableQuery1[JobModel]' to type 'System.Linq.IQueryable1[System.Collections.Generic.List`1[JobModel]]'.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by shaukatwaqarangular** [comment]
hmm
