### ISSUE TITLE
opt.Condition(src => src.CollectionXzy != null); still attempting to map

### ISSUE THREAD

**Issue by generik0** [AutoMapper/AutoMapper#2355]
Hi
I am AUTOMAPPER 6.1.1.
The opt=>opt.Conditions  for a member does not seam to be doing what i expect.

I would expect that this collection is ignored when it is Null:

`.ForMember(dest => dest.FeatureGroups, opt =>
                {
                    opt.MapFrom(src => MapFeatureGroups(src.FeatureGroups));
                    opt.Condition(src => src.FeatureGroups != null);
                })`

But it isn't being ignored. And since i have objects reflecting each other, i get a circluar mapping. continually mapping null:

![image](https://user-images.githubusercontent.com/2411563/31306591-914cceca-ab53-11e7-8204-81e9390bf799.png)

![image](https://user-images.githubusercontent.com/2411563/31306596-ab7e0d7c-ab53-11e7-8861-1d38718cee45.png)

Should this not be working?

Thanks

**Comment by lbargaoanu** [comment]
You need a [PreCondition](https://github.com/AutoMapper/AutoMapper/wiki/Conditional-mapping#preconditions) instead.
