### ISSUE TITLE
Mapping base and derived class with extending and overriding property maps

### ISSUE THREAD

**Issue by DimitryNechaev** [AutoMapper/AutoMapper#2357]
Hi guys.

I'm having issues with inheritance mapping. Need help as my project falls apart.

1. If base class mapping declares a mapping for a property, and derived class mapping ends up with .ForAllOtherMembers(opt => opt.Ignore());
...The base class properties are not mapped. 

```csharp
            CreateMap<Loan.AddressRecord, Lixi.AddressDetails>()
                .Include<Loan.ApplicantAddressRecord, Lixi.AddressDetails>()
                .ForMember(dst => dst.Item1, opt => opt.ResolveUsing((src, dst, member, ctx) => 
                    new Lixi.StartAndEndDates()
                    {
                        StartDate = ctx.Mapper.Map<Lixi.StartDate>(src.DateMovedIn),
                        Item = ctx.Mapper.Map<Lixi.EndDate>(src.DateMovedOut)
                    }))


            CreateMap<Loan.ApplicantAddressRecord, Lixi.AddressDetails>()
                .<include mapping for props in this derived class>
                .ForAllOtherMembers(opt => opt.Ignore());
```

In the sample above ForMember(dst => dst.Item1..) will never hit until ForAllOtherMembers is removed from the derived class mapping.

The derived type mapping is ending on .ForAllOtherMembers(opt => opt.Ignore()) because there are plenty of props with matching names must not be mapped. I have to make explicit mapping only for these entities.

2. Override the same property in derived class mapping.
I have a base class AddressRef, which maps to data object with a property Item of specific type.
A derived class Address creates the same property Item of different type.

If I declare this mapping on base class with Condition() & ResolveUsing(), then I have to use Condition & ResolveUsing in derived type mapping. If I use Condition & MapFrom in derived class, the property is not mapped at all (ignored).

```csharp
            CreateMap<Loan.SimpleTypes.AddressRef, Lixi.AddressDetails>()
                .Include<Loan.SimpleTypes.Address, Lixi.AddressDetails>()
                .ForMember(dst => dst.Item, opt => opt.Condition(src => src.IsReference));
                .ForMember(dst => dst.Item, opt => opt.ResolveUsing(src => MakeReference(src.Id)));

            CreateMap<Loan.SimpleTypes.Address, Lixi.AddressDetails>()
                .ForMember(dst => dst.Item, opt => opt.Condition(src => true))
                .ForMember(dst => dst.Item, opt => opt.ResolveUsing((src, dst, member, ctx) => ctx.Mapper.Map(src, (Lixi.Address)dst.Item)))

```

This makes hard to specify an explicit set of properties should be mapped on a base class and another set (overlapping with base class) on derived class. 

Could you please share ideas on the best use of automapper for this?

**Comment by lbargaoanu** [comment]
See #1843. Just use MemberList.None to pass validation.

**Comment by lbargaoanu** [comment]
Inherited properties are matched by name indeed. I don't remember now why, it might have smth to do with generics. But it's weird to have a different property with the same name in a derived class. So maybe you should take another look at your design.

**Comment by DimitryNechaev** [comment]
@lbargaoanu 

The the sample for the property Item. It might explain the idea.
![image](https://user-images.githubusercontent.com/12892631/31361124-74f9fb84-ad9d-11e7-9341-c71235c0566b.png)

The target model is a 3rd party xml schema.

**Comment by lbargaoanu** [comment]
If you want to take over the mapping, you should use ConvertUsing, not ConstructUsing, that one is just for construction.

**Comment by lbargaoanu** [comment]
If you're interested in a PR. The matching by name happens [here](https://github.com/AutoMapper/AutoMapper/blob/932c078256b0d4699f7d13fe923249ff0ec88507/src/AutoMapper/TypeMap.cs#L363). You can try to match by MemberInfo. I'm guessing some test will fail. Or by name and type, that might work. Of course it would be a good idea to first check if that solves your problem :)

**Comment by DimitryNechaev** [comment]
thanks @lbargaoanu.

These inherited properties are not too common, so workaround for the few cases solves the issue.

There was another one, with execution of mapping of the base class. I had an issue when mapping a derived class explicitly as Map<TargetDerivedClass>(SourceDerivedClass) it didn't execute a map for <TargetBaseClass, SourceBaseClass>()
.Include<TargetDerivedClass, SourceDerivedClass>()
So I had to map explicitly specifying source object as SourceBaseClass, then it passed though all the mappings, from base escalating to derived ones.
Then, all of a sudden, the problem disappeared. I suspect ConstructUsing in the base class mapping was the reason.
All in all, I was able to tune up mapping that they produce expected result. Essentially thanks to MemberList.None. 

I'm closing this as all now works as expected.

**Comment by DimitryNechaev** [comment]
Hi

There is an issue with MemberList.None not preventing property types on checking in compatibility, even for properties which are not mapped.

I use map:
![image](https://user-images.githubusercontent.com/12892631/31424583-ba63af94-aea6-11e7-8340-9752ad449ef7.png)

And it ends up with exception
`The following property on LIXI.EstimatedValue cannot be mapped: 
	EstimatedValue 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type LIXI.EstimatedValue.
Context:
	Mapping to property EstimatedValue from System.Decimal to LIXI.EstimatedValue
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.`

Disclaimer: I don't need ConvertUsing, as I always create a new entity in the mapping, and ConstructUsing works just fine. 

So there is a property on both entities (Property & RealEstate) named _EstimatedValue_
**I don't want it to be mapped**.
The pair of types only happen to meet in this mapping. Nowhere else.


I can see this property _EstimatedValue_ is added in TypeMapFactory.CreateTypeMap
It executes typeMap.AddPropertyMap for it.
![image](https://user-images.githubusercontent.com/12892631/31424758-b361b29e-aea7-11e7-9de8-843b324d1e2b.png)

Then in ConfigurationValidator.DryRunTypeMap it calls CheckPropertyMaps => DryRunTypeMap => CheckPropertyMaps and throws an exception as there is no mapping between the types.

Looks like "MemberList.None" is not preventing property mapping to be added & validated in regards to types.

In result, I have to create a mapping for the types pair of these properties which I don't need.
As workaround I can add .ForMember(dst => dst.EstimatedValue, opt => opt.Ignore()) and it will work.

If "MemberList.None" could prevent this from happening would be more convenient and make much more sense.

Thanks

**Comment by lbargaoanu** [comment]
But the thing is, if you use ConstructUsing, it means that you want other things mapped (and you might get validation errors, bug or no bug), with ConvertUsing, you're doing it all yourself (and you shouldn't get any validation errors). Which is it? :)
