### ISSUE TITLE
What should we do with the existing wiki?

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2359]
Docs are in readthedocs, what should we do with the existing wiki?

 - Delete?
 - Point to the new docs at the top of every page?
 - Both (remove the page contents and point to the new docs site)?

**Comment by lbargaoanu** [comment]
They should redirect :) But other than that, option three I guess.

**Comment by TylerCarlson1** [comment]
I say redirect option 3 would probably be best

**Comment by lbargaoanu** [comment]
Meanwhile maybe make it [readonly](https://help.github.com/articles/changing-access-permissions-for-wikis/)?

**Comment by jbogard** [comment]
I've done option 2 since I can't really do the redirect.
