### ISSUE TITLE
Mappingprofiles with inheritance tree AutoMapper 2

### ISSUE THREAD

**Issue by kraakwg** [AutoMapper/AutoMapper#2361]
My client uses AutoMapper for several years now in a WCF integration landscape. I have to make the mapping features more testable. Isolation of profiles is done in separate class libraries inheriting from Profile. I run into an issue where a call to AssertConfigurationIsValid does not result in an exception. Yet, when performing a map between objects (with inheritance), an AutoMapperMappingException occurs. The inheritance object tree looks like this: Source: SourceBaseClass --> SourceDerivedDto --> SourceDerivedDerivedDto. Target: TargetBaseClass --> TargetDerivedClass. Yes, the levels of inheritance tree from source to target are not the same. My profile looks like the following:

```
CreateMap<sourcebaseclass, targetbaseclass="">
.Include<sourcederiveddto, targetderivedclass="">()
.Include<sourcederivedderiveddto, targetderivedclass="">()

CreateMap<sourcederivedderiveddto, targetderivedclass="">();
CreateMap<sourcederiveddto, targetderivedclass="">();
```

I'm using AutoMapper 2.0.0.0 (Yes, an very old version).

**Comment by jbogard** [comment]
In general, configuration validation only works for maps it knows about (and can't exercise all paths). It doesn't test "will any instance that we call Map actually work". You'll likely still want to have regular tests that at least exercise the maps as part of a suite of overall integration tests.

We exercise our maps through integration tests, see my ContosoUniversity projects on my GitHub.
