### ISSUE TITLE
ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by SteveHobs** [AutoMapper/AutoMapper#2363]
[Gist https://gist.github.com/SteveHobs/fd6ecfeabfe7ca0b116b4a8df27d2fc3](https://gist.github.com/SteveHobs/fd6ecfeabfe7ca0b116b4a8df27d2fc3)

### Source/destination types

```csharp
    public class ParentDTO
    {
        public List<ChildDTO> Children { get; set; } = new List<ChildDTO>();
        public int Id { get; set; }
    }

    public class ChildDTO
    {
        public int Id { get; set; }
        public ParentDTO Parent { get; set; }
    }

    public class ParentModel
    {
        public List<ChildModel> Children { get; set; } = new List<ChildModel>();
        public int Id { get; set; }
    }

    public class ChildModel
    {
        public ChildModel(ParentModel parent) // This causes the exception.
        {
            Parent = parent;
        }

        public int Id { get; set; }
        public ParentModel Parent { get; set; }
    }
```

### Mapping configuration

```csharp
             Mapper.Initialize(
                cfg =>
                {
                    cfg.CreateMap<ParentDTO, ParentModel>()
                        .PreserveReferences();

                    cfg.CreateMap<ChildDTO, ChildModel>()
                        .ForMember(c => c.Parent, o => o.Ignore())
                        .PreserveReferences();
                });

            Mapper.AssertConfigurationIsValid();
```

### Actual behavior

Throws an exception when using a constructor on the ChildModel class.

### Steps to reproduce

```csharp
var parentDto = new ParentDTO {Id = 1};
            for (var i = 0; i < 5; i++)
            {
                parentDto.Children.Add(new ChildDTO {Id = i, Parent = parentDto});
            }

            var children = Mapper.Map<List<ChildDTO>, List<ChildModel>>(parentDto.Children);
```

**Comment by lbargaoanu** [comment]
This should work without explicitly setting PreserveReferences or ignoring Parent. Other than removing the constructor, you can use MaxDepth as a workaround.

**Comment by lbargaoanu** [comment]
Even easier, removing PreserveReferences and the Ignore works for me with the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by SteveHobs** [comment]
Tried the MyGet build.

Setting MaxDepth to 1 works, but this prevents the Parent objects' Children from being populated.

Removing PreserveReferences and Ignore works, however we end up with 35 objects (5 parents and 30 children) instead of 6 (1 parent and 5 children).

Are there any other options or is removing the constructor the only one?

[Updated Gist](https://gist.github.com/SteveHobs/b845751c591038f7717cdb2e345dea02)

**Comment by lbargaoanu** [comment]
You don't have to set MaxDepth to 1 :)

**Comment by SteveHobs** [comment]
Setting MaxDepth to 2 works better, however we end up with 10 children objects. The outer "var children" list holds different references than the "children[0].Parent.Children" property.

[Updated Gist](https://gist.github.com/SteveHobs/aa46198e51d11d95e34e6c0c80de6b74)

**Comment by lbargaoanu** [comment]
I see it, but I ran out of ideas. I guess we need to fix the bug.

**Comment by g-un--** [comment]
There is a problem with the execution plan

Pseudo execution plan
```
map = childDTO -> 
               if(!contextCache.GetDestination(childDto, typeof(ChildModel)))
               {
                   //cache will update while mapping parent
                   var dest = new ChildViewModel($context.Map(childDto.Parent));
                  
                   //here is not safe anymore to assume that contextCache doesn't contains the key
                   contextCache.SetDestination(childDto, typeof(ChildModel), dest);

                   return dest;
               })
```
The issue seems to be that while mapping childDto.Parent the cache is updated with all the children,
so by the time when first childDto { Id = 0 } parent is mapped, the cache will allready contain all the keys for children (0, 1, 2, 3, 4) and then another call to SetDestination is made for 0

**Comment by lbargaoanu** [comment]
@g-un-- It makes sense. PR?

**Comment by lbargaoanu** [comment]
I think simply replacing Add with the indexer in SetDestinationValue is enough.

**Comment by lbargaoanu** [comment]
The workaround is to map the parent instead of the children.
