### ISSUE TITLE
An exception of type 'AutoMapper.AutoMapperMappingException' occurred in AutoMapper.dll but was not handled in user code

### ISSUE THREAD

**Issue by gsmtcnr** [AutoMapper/AutoMapper#2364]
Hi,

I use LLBLGEN, I want to map the entity class with the c # class.

            Mapper.CreateMap<Model.Location, EntityClasses.LocationEntity>();
            Mapper.CreateMap<EntityClasses.LocationEntity, Model.Location>();

         EntityClasses.LocationEntity loEntity = LocationEntity.Query.Where(s => s.Id == 1).FirstOrDefault();
          Model.Location model = Mapper.Map<Model.Location>(loEntity);
model fills no problem. but model  map entity object error
 LocationEntity locationEntity = Mapper.Map<LocationEntity>(model);
Missing type map configuration or unsupported mapping.

Mapping types:
Location -> IPrefetchPath
Model.Location -> SD.LLBLGen.Pro.ORMSupportClasses.IPrefetchPath

Destination path:
LocationEntity

Source value:
Model.Location

What is a problem ?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by gsmtcnr** [comment]
Your example EntityFramework, i use ORM LLBLGEN. I can map entity framework, not map LLBLGEN entity class.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
