### ISSUE TITLE
Value Transformers v2

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2367]
Moving some of the extra items out

- [ ] Overloads for contextual information
- [ ] Inheriting value transformers
- [ ] Transformer objects (including DI) - an IValueTransformer interface

See how people use the value transformers now and what we need to support in the future. Really to get us to a 6.2 release.

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/47560076/automapper-is-it-possible-to-access-the-source-object-in-addtransform?s=5|0.0000

**Comment by jbogard** [comment]
I'm going to close this one for now. Value converters covered most of these cases, imo
