### ISSUE TITLE
Mapper.Map<T>(obj) returns reference to obj

### ISSUE THREAD

**Issue by kheino** [AutoMapper/AutoMapper#2369]
I stumbled on a specific circumstance where `Mapper.Map<T>(obj)` returns a reference to `obj`. This is unexpected given that normal behavior of this `Map` overload is to return a new instance of `T`. I have not been able to find this behavior described in the documentation, and I suspect it is not by design. Basically, calling `Mapper.Map<T>(obj)` where `obj` is of type `T`, and no `T` -> `T` map has been created (though other maps using `T` do exist), a reference to `obj` is returned. Adding the `T` -> `T` map, a new instance of `T` is returned as expected. See [gist for an executable demo](https://gist.github.com/kheino/0771b69b4ee9a9169a07ae00dca0cf49).

### Source/destination types

```csharp
class Alice { }
class Bob { }
```

### Mapping configuration

```csharp
Mapper.Initialize(
    cfg => cfg.CreateMap<Alice, Bob>());
```

### Expected behavior

Calling `Mapper.Map<Alice>(alice)` without having created the `Alice` -> `Alice` map, I would expect either

1. a new instance of `Alice` to be returned, i.e. a "clone" of `alice`, or
2. an exception thrown regarding the missing map.

### Actual behavior

A reference to the existing `alice` instance is returned.

### Steps to reproduce

```csharp
var alice = new Alice();

// Map Alice -> Alice
var clone = Mapper.Map<Alice>(alice);

// Output: True
Console.WriteLine(clone == alice);
```

**Comment by lbargaoanu** [comment]
That's by design, if it can be assigned, that's the return value.

**Comment by kheino** [comment]
I see. I would argue it seems counterintuitive with respect to the intention of calling `Map`. Also, you lose the safety of causing an exception in case you forget to create the corresponding map, leaving you with strange behavior if your code assumes a new instance is returned.

**Comment by jbogard** [comment]
You can remove the AssignableMapper to not have this behavior.

**Comment by kheino** [comment]
Right, got it. Thank you.
