### ISSUE TITLE
Cannot map base properties with ExplicitExpansion

### ISSUE THREAD

**Issue by thiagorizzo** [AutoMapper/AutoMapper#2371]
### Source/destination types

```csharp
/*********** Source Types ***********/
public class ParentBaseModel
{
	public virtual AnotherModel Another { get; set; }
}

public class ChildModel : ParentBaseModel
{
	public string PropertyChild { get; set; }
}

/*********** Destination Types ***********/
public class ParentBaseViewModel
{
	public AnotherModel Another { get; set; }
}

public class ChildViewModel : ParentBaseViewModel
{
	public string PropertyChild { get; set; }
}

```

### Mapping configuration

```csharp
cfg.CreateMap<ChildModel, ChieldViewmodel>()
.MaxDepth(1)
.ForMember(d = > d.Another, o => o.ExplicitExpansion())
.ReverseMap();
```

### Expected behavior
Expected to map from ChildModel to ChieldViewModel with navigation properties from base model, _Another_ property, which is an Explicit Expansion member.
### Actual behavior
Its does not map _Another_ property even expliciting it through expanding member parameter in _projectTo_.  It only works when I dont configure _Another_ as Explicit Expansion.

### Steps to reproduce

```csharp
objSource.ProjectoTo<ChieldViewModel>(null, new string[] { "Another" });
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by JobaDiniz** [comment]
Hi, I've created a repro of this issue: https://1drv.ms/u/s!AhH0QYI81F61gtIx0q27BZ05EM-xQA

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by JobaDiniz** [comment]
sorry @lbargaoanu but this is a **bug**. I even created a repro showing... _gist_ is no help because we need a database to use `ProjectTo` extension method.

**Comment by lbargaoanu** [comment]
I've spent some time looking at the repro and I think it's about how you use AM. So please ask your question on SO. If the conclusion there is that it's a bug in AM, please come back with a better repro.

**Comment by TylerCarlson1** [comment]
In both examples shown you aren't creating a map for The child mapping.
There's no `CreateMap<AnotherModel, AnotherModel>` in the example above.  I don't know if the assignable mapper works when it comes to expressions like this.
Also in the repo there's no `CreateMap<User, UserModel>` so there's no way it can be made in projection.

**Comment by JobaDiniz** [comment]
Oh, sorry, I forgot to mention that I've also tried these configurations:
```
Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<EntityBase, EntityBaseModel>();
                cfg.CreateMap<User, UserModel>();
                cfg.CreateMap<Script, ScriptModel>()
                .MaxDepth(1)
                .ForMember(d => d.ModifiedBy, o => o.ExplicitExpansion())
                .ForMember(d => d.CreatedBy, o => o.ExplicitExpansion());
            });
```
```
Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<EntityBase, EntityBaseModel>();
                cfg.CreateMap<User, UserModel>();
                cfg.CreateMap<Script, ScriptModel>()
                .IncludeBase<EntityBase, EntityBaseModel>()
                .MaxDepth(1)
                .ForMember(d => d.ModifiedBy, o => o.ExplicitExpansion())
                .ForMember(d => d.CreatedBy, o => o.ExplicitExpansion());
            });
```

But it doesn't work either.

**Comment by JobaDiniz** [comment]
I've created a question in stackoverflow [Mapping properties from base class doesn't work using ExplicitExpansion](https://stackoverflow.com/questions/46914089/mapping-properties-from-base-class-doesnt-work-using-explicitexpansion).
Using the *expression* overload of `ProjectTo`, it works, but using the [string](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/Extensions.cs#L56) it [fails](https://stackoverflow.com/questions/46914089/mapping-properties-from-base-class-doesnt-work-using-explicitexpansion#comment80928724_46989750):
