### ISSUE TITLE
Error when using CustomProjectionUsing when EF is involved as the source and mapping to a DTO (NO EF)

### ISSUE THREAD

**Issue by krptodr** [AutoMapper/AutoMapper#2373]
### Source/destination types

```csharp
//SOURCE
public partial class ORDER
 {
	public long PRIMARYKEY { get; set; }
	public long ORDERTYPEKEY { get; set; }
	public long OPROPERTYTYPEKEY { get; set; }}
	public string ORDERREFERENCE { get; set; }
	public string NAME { get; set; }
	public string ORDERDESCRIPTION{ get; set; }
	public Nullable<long> STATUSKEY { get; set; }
}


//DESTINATION
public class TransactionDTO:  Entity<long>, IMatter
	{

public TransactionDTO() : base(new long())
{
	//parameterless constructur is required for EF.
}
public TransactionDTO(long key): base(key)
{
}

public string Title
{
	get; set;
}

public string ReferenceNumber
{
	get; set;
}

public IStatus Status
{
	get; set;
}

public void GenerateStatus<TEntity, TCastTo>(IMatter Dest)
{
	Dest.Status = new TransactionStatus { Key = 123, Name = "Testing Status" };
}

}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => {
cfg.CreateMap<Data.ORDER, TransactionDTO>()
	//.AfterMap((s, d) => d.GenerateStatus(s, d))//opts.Ignore())////dest => dest.Status, opts => opts.ResolveUsing<StatusTypeConverter>()															
	.ForMember(dest => dest.Title, opts => opts.MapFrom(t => t.ORDERDESCRIPTION))
	.ForMember(dest => dest.ReferenceNumber, opts => opts.MapFrom(t => t.ORDERREFERENCE))
	.ForMember(dest => dest.Key, opts => opts.MapFrom(t => t.PRIMARYKEY))
	.ForMember(dest => dest.Status, opts => opts.Ignore())
	.ConstructProjectionUsing(src=>new TransactionDTO(src.PRIMARYKEY));
```

### Version: x.y.z
AutoMapper: 6.1.1
AutoMapper.EF6: 1.0.0
EntityFramework: 6.1.3

### Expected behavior
I want to map from ORDER to TransactionDTO and instantiate a new TransactionDTO passing in the ORDER.PRIMARYKEY. 

I am using a generic repository to ProjectTo<TransactionDTO> from ORDER. When Projecting to TransactionDTO is when an error is generated.

### Actual behavior

An error is throw: Only parameterless constructors and initializers are supported in LINQ to Entities.

However, EF has nothing to do with TransactionDTO. 

### Steps to reproduce

```csharp
public async Task<IList<TCastTo>> FindById<TEntity, TCastTo>(Expression<Func<TEntity, bool>> filter = null,
Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>> orderBy = null,
string includeProperties = null,
int? skip = null,
int? take = null) where TEntity : class where TCastTo : class
{

var query = GetQueryable<TEntity>(filter, orderBy, includeProperties, skip, take).AsQueryable();

return await query.ProjectToListAsync<TCastTo>(Mapper.Configuration, ((dest) =>	{
					var test = (IMatter)dest;

					test.GenerateStatus<TEntity, TCastTo>(test);
				}));

}

//EXTENSION - ProjectToListAsync
public static async Task<List<TDestination>> ProjectToListAsync<TDestination>(this IQueryable queryable,
IConfigurationProvider config, Action<TDestination> postAction)
{
var projectToListAsync =
  await queryable.ProjectTo(config, new Expression<Func<TDestination, object>>[0]).DecompileAsync().ToListAsync();

if (projectToListAsync.Any())
{
	projectToListAsync.ForEach(postAction);
}

return projectToListAsync;
}

```

**Comment by lbargaoanu** [comment]
As the error says, EF doesn't support that.

**Comment by krptodr** [comment]
I understand, but EF is not touching my constructor for TransactionDTO

**Comment by TylerCarlson1** [comment]
Your code stating `.ConstructProjectionUsing(src=>new TransactionDTO(src.PRIMARYKEY))` says you told AutoMapper to touch your Non-Parameterless constructor when Projecting to EF which is why it's complaining about it.

**Comment by krptodr** [comment]
Ok so it's specifying that the CreateMap<**ORDER**, TransactionDTO> is having the constructor applied to it?

Because while I am using ProjectTo, I am doing so with 
```csharp
TransactionDTO trans = context.ORDERs.ProjectTo<TransactionDTO>.ToList();
```
I guess I still dont understand why ProjectTo is taking my TransactionDTO and is complaining about my `ConstructProjectionUsing(src=>new TransactionDTO(src.PRIMARYKEY))`

Perhaps the documentation is misleading.

**Comment by TylerCarlson1** [comment]
It can't use something that doesn't exist.  It's using the only parameter less constructor you gave it which is the TransactionDTO constructor.  THAT'S the problem and that's what EF is complaining about.  Comment our that line and it should stop throwing the exception and work.
