### ISSUE TITLE
Behavior modification : Equals override is not hit on source object

### ISSUE THREAD

**Issue by bNobo** [AutoMapper/AutoMapper#2374]
Hello,

on many of our DTOs we override Equals and GetHashCode because we can have several instances representing the same object. With AutoMapper 3.3.1 it was working fine, all of these were mapped to the same destination instance. Now that we have migrated to 6.1.1 it does not work anymore. I would like to know if this behavior is expected or is a bug. Below a unit test that passes with 3.3.1 but fails with 6.1.1.

Remark : if we override Equals on the destination type then the test passes, but doing so breaks NHibernate.

### Source/destination types

```csharp
        public class Model
        {
            public int Id { get; set; }
            public string Value { get; set; }
        }

        public class Dto
        {
            public int Id { get; set; }
            public string Value { get; set; }

            public override bool Equals(object obj)
            {
                return (obj as Dto).Id == Id;
            }

            public override int GetHashCode()
            {
                return Id;
            }
        }
```

### Mapping configuration

```csharp
        // AutoMapper 6.1.1 config
        var config = new MapperConfigurationExpression();
        config.CreateMap<Dto, Model>().PreserveReferences();
        Mapper.Initialize(config);

        // AutoMapper 3.3.1 config
        Mapper.CreateMap<Dto, Model>();
```

### Expected behavior
Should have only one instance of destination type in the list

### Actual behavior
Have as many instances as in the source list

### Steps to reproduce

```csharp
            var dto1 = new Dto { Id = 1, Value = "blabla" };
            var dto2 = new Dto { Id = 1, Value = "blabla" };
            var listDto = new List<Dto> { dto1, dto2 };
            var list = Mapper.Map<List<Model>>(listDto);

            Assert.Equal(list[0], list[1]);
```

**Comment by lbargaoanu** [comment]
@jbogard should know the history, but I think if it's called PreserveReferences, it should do just that.
