### ISSUE TITLE
Expression mapping with coalesce operator is extremely slow or just hangs up

### ISSUE THREAD

**Issue by urasaber** [AutoMapper/AutoMapper#2378]
### Source/destination types

```csharp
public class Entity1
{
    public int? FolderId { get; set; }
}

public class Entity2
{
    public int FolderId { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Entity1, Entity2>()
.ForMember(d => d.FolderId, o => o.MapFrom(s => s.FolderId ?? 0));
```

### Expected behavior
Expression maps successfully. At least at 4.1.1 it worked nicely and fast enough.

### Actual behavior
Mapping of ~15 conditions in one expression(Lambda debug view in VS: https://i.imgur.com/Sabxuhw.png) takes 3-6seconds
If I add one more OrElse to lambda expression then it takes ~12seconds
One more again - ~23seconds
64 items(Lambda debug view in VS: https://i.imgur.com/GPnif14.png) - never ends

### Steps to reproduce

```csharp
Mapper.Map<Expression<Func<Entity2, bool>>, Expression<Func<Entity1, bool>>>(expression)
```

We are updating our project from 4.1.1 to 6.1.1 and faced this issue. Am I missing something?
This is how it looks in dotTracer: https://i.imgur.com/OUFDPT0.png

**Comment by lbargaoanu** [comment]
cc @BlaiseD

**Comment by lbargaoanu** [comment]
@urasaber What happens is you remove the MapFrom. That should be a default conversion. If that fails, maybe ProjectTo could be used instead?

**Comment by urasaber** [comment]
@lbargaoanu Well, if you remove the MapFrom it'll say that the type of source and dest differs, one is Nullable<> and other is Int32.

You know what, I think that creating such an expressions using OrElse is a bad anyway.
I have tried to create Expression using MethodCall on "Contains" of FolderIds array and now it works flawlessly.

Just wonder why expression visitor is such slow for an expression that mentioned in this issue.

**Comment by BlaiseD** [comment]
@urasaber thanks for bringing this up.  I've called Visit a couple of time in VisitBinary just to check for compatibility - which is causing the preformance problem. It probably makes sense to just check the TypeMappings dictionary instead.  Please leave this open @lbargaoanu .  I'll create a PR.

**Comment by lbargaoanu** [comment]
OK :)
