### ISSUE TITLE
Please provide option to Map unmapped object to a new cloned object

### ISSUE THREAD

**Issue by noufionline** [AutoMapper/AutoMapper#2381]
### Source/destination types

```csharp

  var emp1 = new Employee();
  

```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
				   {
					//cfg.CreateMap<Employee,Employee>();

				   });

  var mapper=config.CreateMapper();

var emp2=mapper.Map<Employee>(emp1);

```
Since the Employee is not registered Automapper gives the exact Employee reference.

What I need is an option to get a cloned employee even if I don't specify any mapping.

If not possible by default then give an extension point some thing like this.

```csharp
var emp2=mapper.Map<Employee>(emp1,opt=> opt.CloneIfNotMapped);
```

Can you help?

**Comment by jbogard** [comment]
Yes, AutoMapper is not a cloning library so you need to explicitly call
CreateMap.

**Comment by noufionline** [comment]
Thanks @jbogard,

Wouldn’t it be nice if you try to map something which is not mapper creates mapping and returns the mapped result?

Is it possible to create an overload to CreateMap high accepts only one type for self mapping?

**Comment by jbogard** [comment]
It would be nice probably for your specific case, but remember, in AutoMapper's eyes, this *is* mapped. One of the mappers is an assignable mapper. If the source value can be assigned to the destination value, it simply assigns the value.

If you want to OOTB support cloning behavior, you can remove that mapper from the list of mappers (search AssignableMapper in the issues).

That overload already exists that you're referring to, for a simpler purpose - inferring the source type from the source object. `var dest = Mapper.Map<Dest>(src);`

And AutoMapper is not a cloning library, nor will its design ever be optimized for that purpose. There are far better cloning mechanisms out there.

**Comment by makeit-mh** [comment]
Could you show some smart place to register own version of AssignableMapper ? ;)

**Comment by lbargaoanu** [comment]
The safe way would be to simply replace the default.

**Comment by makeit-mh** [comment]
<lol2> Fast answer... I'm impressed ;-)

**Comment by lbargaoanu** [comment]
That's why we do it :)

**Comment by makeit-mh** [comment]
@jbogard @lbargaoanu   I know Automapper isn't cloning library. I changed AssignableMapper to
...
     public bool IsMatch(TypePair context)
        {
            return context.DestinationType.IsAssignableFrom(context.SourceType)
                   &&
                   !(context.DestinationType.IsClass
                     && context.SourceType.IsClass
                     && context.DestinationType == context.SourceType);
        }
...
I think it works for me...
What i broke down ? 
Sorry for my English.

**Comment by lbargaoanu** [comment]
Time will tell :)

**Comment by makeit-mh** [comment]
I know "expect unexpected", but in project "the show must go on" ;-)

**Comment by lbargaoanu** [comment]
One idea is to use a separate MapperConfiguration for cloning. You can customize that one anyway you want. CreateMissingTypeMaps is true by default so that might help. You wold isolate the impact.

**Comment by makeit-mh** [comment]
I will try. Thank you for the clue.
