### ISSUE TITLE
PCL: Could not install package 'AutoMapper 6.1.1'

### ISSUE THREAD

**Issue by stesvis** [AutoMapper/AutoMapper#2384]
### Expected behavior
Install the package on a PCL project (Xamarin Forms)

### Actual behavior

> Error		Could not install package 'AutoMapper 6.1.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Steps to reproduce

Try to install the latest version to a Xamarin Forms PCL project

**Comment by jbogard** [comment]
Don’t use PCLs. Use the netstandard library and make sure your NuGet is up
to date.

**Comment by stesvis** [comment]
Hi thanks for the reply @jbogard 
In Xamarin Forms I have to use a PCL, I don't have a choice...

**Comment by jbogard** [comment]
In that case you’re using an old profile that targets Windows Phone
Silverlight. Don’t use that profile.
