### ISSUE TITLE
How can map from two source model to a datamodel？？？

### ISSUE THREAD

**Issue by andyliyuze** [AutoMapper/AutoMapper#2386]
`  public class User
    {
        public string RealName { get; set; }
        public string Age { get; set; }
    }

    public class Post
    {
        public Guid Id { get; set; }
        public string Content { get; set; }
    }
    public class PostInfo
    {
        public Guid Id { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }
    }`

How can I use User typre and  Post type map to  PostInfo ？？？Thanks

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
