### ISSUE TITLE
ReverseMap unflattening

### ISSUE THREAD

**Issue by Siddhanntarora** [AutoMapper/AutoMapper#2388]
### Expected behavior

During unflattening the default values from target object should be picked up if the source child object is null

### Actual behavior

Every time the source child object is null, new target object is mapped without the default value

### Steps to reproduce
```C#
using System;
using AutoMapper;
using Newtonsoft.Json;

					
public class Program
{
	public class Vehicle
	{
		public string Price {get;set;}
		public string Mileage {get;set;}
		
		public VehicleType Vehicletype {get;set;}
		
		public Vehicle()
		{
			Price= "30k"; Mileage ="30KMPH"; 
			
			Vehicletype = new VehicleType (){Name ="Car"};
		}
	}
	
	public class VehicleType
	{
		public string Name {get;set;}
	}
	
	public class VehicleDto
	{
		public string Price {get;set;}
		public string Mileage {get;set;}
		public string VehicletypeName {get;set;}
	}
	
	
	
	
	public static void Main()
	{
			
		var configuration = new MapperConfiguration(config => { 
						  
						 config.AllowNullCollections = true;
			
						 config.CreateMap<Vehicle,VehicleDto>()
						  .ReverseMap()
						  .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null ));
						  
						  
		});
		
		var mapper = configuration.CreateMapper();
		
		var objVehicleDto = new VehicleDto();
		
		var vehicle = mapper.Map<VehicleDto,Vehicle>(objVehicleDto);
		
		Console.WriteLine("Name: " + vehicle.Vehicletype.Name);
		
	}
}
```

**Comment by lbargaoanu** [comment]
ForAllMember doesn't apply to paths.

		config.CreateMap<Vehicle,VehicleDto>()
			.ReverseMap()
			.ForPath(d=>d.Vehicletype.Name, o=>o.Condition(c=>c.SourceMember != null))
			.ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

**Comment by Siddhanntarora** [comment]
I have a lot of child objects with multiple properties, is there another way of doing this, i dont want to add ForPath multiple times, for lot of properties

**Comment by lbargaoanu** [comment]
No.

**Comment by Siddhanntarora** [comment]
But even if its trying to Map a null object, when it is creating a new object on the target, why is it not picking up the default values in the constructor, the defaul values are picked up if you are not using reverse map

**Comment by lbargaoanu** [comment]
Don't use ReverseMap if you don't like what it's doing.

**Comment by Siddhanntarora** [comment]
Also, after trying your condition, i am getting the below error 
'AutoMapper.IPathConfigurationExpression<Program.VehicleDto,Program.Vehicle>' does not contain a definition for 'Condition' and no extension method 'Condition' accepting a first argument of type 'AutoMapper.IPathConfigurationExpression<Program.VehicleDto,Program.Vehicle>' could be found (are you missing a using directive or an assembly reference?)

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by Siddhanntarora** [comment]
I like reverse map and its providing unflattening, just in this particular case if the source is null the traget's default value is not picked up, is this something that can be handled by an extension method or something? Any pointers would be appreciated as i love using automapper.

**Comment by lbargaoanu** [comment]
VehicletypeName is null so that is the value assigned to the destination, that makes perfect sense to me.

**Comment by Siddhanntarora** [comment]
But its not assigning a null instead creating a new object of Vehicletype on the target with the name as null, so its still creating an object of Vehicletype on target just without the default values provided in cosntructor of Vehicle()

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping).

**Comment by Siddhanntarora** [comment]
Can i handle this scenario by writing an extension method or soemthing, could you give any pointers for the same?
The other thing is i dont use reverse map and handle unflattening in a condition for every member, which i dont want to do as i have lots of map and it would make it more complicated

**Comment by lbargaoanu** [comment]
I guess you want smth like ForAllPaths. It doesn't exist. You can write it yourself using ForAllMaps and TypeMap.PathMaps.

**Comment by Siddhanntarora** [comment]
Could you please elaborate a bit more how can i do it, if you could give a small example it would be really helpful

**Comment by Siddhanntarora** [comment]
Could you please elaborate the suggested solution
