### ISSUE TITLE
`Mapper.Map` incorrectly using maps for runtime types rather than static types

### ISSUE THREAD

**Issue by burns47** [AutoMapper/AutoMapper#2391]
### Source/destination types

```csharp
        interface IMyInterface
        {
            string InterfaceProperty { get; set; }
        }

        class ImplementsMyInterface : IMyInterface
        {
            public string InterfaceProperty { get; set; }
            public string AdditionalProperty { get; set; }
        }

        class MapTarget
        {
            public string InterfaceProperty { get; set; }
            public string AdditionalProperty { get; set; }
        }

```

### Mapping configuration

```csharp
            var config = new MapperConfiguration(exp =>
            {
                exp.CreateMap<IMyInterface, MapTarget>();
                exp.CreateMap<ImplementsMyInterface, MapTarget>();
            });
```

### Version: x.y.z
Verified this bug in 4.1.1 and 6.1.1.  This bug didn't exist in 1.0, which is the version I'm upgrading from.

### Expected behavior

Calling `mapper.Map<IMyInterface, MapTarget>(sourceObject)` incorrectly maps `MapTarget.AdditionalProperty` when no such property exists in `IMyInterface`.  In other words, the wrong map (the `ImplementsMyInterface` map) is used.  This is contrary to the documentation on `mapper.Map`:
https://github.com/AutoMapper/AutoMapper/blob/e1b9716a5bf0b5de6b483595c76552f815d1e818/src/AutoMapper/Mapper.cs#L75-L83
which states that the first type parameter is the "Source type to use, _regardless of the runtime type_".  Since I've specified that the source type is `IMyInterface`, I expect the `IMyInterface` mapping would be used.

### Steps to reproduce

```csharp
            ImplementsMyInterface source = new ImplementsMyInterface { InterfaceProperty = "Interface", AdditionalProperty = "Additional" };

            var mapResult = mapper.Map<IMyInterface, MapTarget>(source);
            Debug.Assert(mapResult.AdditionalProperty == null); //this assertion shouldn't fail, but it does

```

**Comment by lbargaoanu** [comment]
That's by design, the most derived map is chosen, and there is no way that I'm aware of to override this behavior.

**Comment by burns47** [comment]
That's alright I mostly needed confirmation - it'd probably be a good idea to update that doc comment though.  I might be missing something but I can't find a meaning of:
```csharp
<typeparam name="TSource">Source type to use, regardless of the runtime type</typeparam> 
```
that is consistent with this behavior...

**Comment by lbargaoanu** [comment]
Feel free to add smth useful.
