### ISSUE TITLE
The binary operator NotEqual is not defined for the types...

### ISSUE THREAD

**Issue by Andy65** [AutoMapper/AutoMapper#2395]
Message: SetUp : System.TypeInitializationException : The type initializer for 'ClockManager.Plugin.Clock.Rest.Services.UserRestService' threw an exception.
  ----> System.InvalidOperationException : The binary operator NotEqual is not defined for the types 'System.Collections.Generic.KeyValuePair`2[System.Int32,System.Collections.Generic.List`1[Clocks.Shared.Model.FingerprintDto]]' and 'System.Object'.

The attached project mimics the structure we have, however, it does not unfortunately reproduce the issue.  In practice the Service class has a number of constructor arguments.

[AutoMapperTypeInitializationIssue.zip](https://github.com/AutoMapper/AutoMapper/files/1462083/AutoMapperTypeInitializationIssue.zip)

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by Andy65** [comment]
If you didn't fix it then it is still a bug and I can definitely repo it with our production code - which I am unable to give you, just not with a sample, sorry.

**Comment by lbargaoanu** [comment]
Without a repro, there is nothing we can do about it. You can try setting CreateMissingTypeMaps to false, but other than that, you need to isolate the issue.

**Comment by CRidge** [comment]
We're seeing this same error when mapping a dictionary (from Dictionary<Guid, X[]> to Dictionary<Guid, Y[]>), but like @Andy65, I cannot reproduce it in a minimal solution. This doesn't help pin down the bug - but at least we know it's not a one off.
