### ISSUE TITLE
Mapping between different ICollection implementations fails

### ISSUE THREAD

**Issue by FilipFilipov** [AutoMapper/AutoMapper#2397]
When creating entities from database, Entity Framework will initialize related ICollections as HashSets. For the analogous ICollections in the view models I use Lists instead. When I want to create/edit entities I map a model to the entity as shown in this [gist](https://gist.github.com/FilipFilipov/edb282c2b2bb6a49faf420a3c9b8f104). In previous versions the HashSet would be replaced a List and the database operation would proceed without issue, but since 6.2 you get an AutoMapperMappingException.

**Comment by lbargaoanu** [comment]
Workaround:

      cfg.CreateMap<ParentViewModel, Parent>()
		.ForMember(d=>d.Children, o=>o.UseDestinationValue())
        .ForMember(dest => dest.Id, opt => opt.Ignore());

**Comment by lbargaoanu** [comment]
@jbogard I guess the root cause here is the fact that I made the collection mapper return an expression of a concrete type, to keep that logic inside the mapper. A fix seems difficult and the workaround reasonable.

**Comment by FilipFilipov** [comment]
Works for me, I guess.

**Comment by negberts** [comment]
@lbargaoanu do we have to add the `.ForMember(d=>d.Children, o=>o.UseDestinationValue()) ` for each collection in the DB? Or is there some global setting that we can use for this? Seems like a lot of mappings to adjust...

**Comment by lbargaoanu** [comment]
Are you sure your situation is the same? The whole thing seems pretty weird to me. You can use ForAllPropertMaps or a combination of ForAllMaps and ForAllMembers. The workaround was for this particular case. Usually things just work.

**Comment by negberts** [comment]
Yes, we are mapping collections from Entity Framework to Lists. Getting a lot of cannot map Hashset to List exceptions and I don't want to add a rule for every child collection...

**Comment by ristogod** [comment]
Wow. This seems horrifically excessive. We have hundreds of mappings that we now have to go through and examine each one checking for collections and adding this hack-around?

**Comment by jbogard** [comment]
@lbargaoanu what was the change that broke this behavior?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2397#issuecomment-344011562 If the collection mapper has ISet, it knows it's HashSet, if UseDestinationValue is set, the concrete type doesn't matter. If it's ICollection it must be List. [Here](https://github.com/AutoMapper/AutoMapper/blame/096e58a5385093bd0db727125141731393630d4e/src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs#L49). I guess it worked before because the collection mapper didn't decide the concrete type.
