### ISSUE TITLE
CreateMissingTypeMaps doesn't work in version 6.2.0

### ISSUE THREAD

**Issue by haison8x** [AutoMapper/AutoMapper#2398]
I have two following DTO

` class SourceDTO`
  ` {`
        `public int Diff1 { get; set; }`
        `public int Mapped { get; set; }`
   ` }`

and 
`class DestDTO`
   ` {`
        `public int Diff2 { get; set; }`
        `public int Mapped { get; set; }`
    `}`

With version 6.1.1 I can map those two DTO without creating mapping profile, I just need to initialize the mapper as following 
` Mapper.Initialize(cfg => cfg.CreateMissingTypeMaps = true);`

However, with version 6.2.0, it doesn't work, it throws an exception:

> Unmapped members were found. Review the types and members below.
> Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
> For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
> SourceDTO -> DestDTO (Destination member list)
> ConsoleApplication1.TestMapper.SourceDTO -> ConsoleApplication1.TestMapper.DestDTO (Destination member list)
> 
> Unmapped properties: Diff2

**Comment by lbargaoanu** [comment]
[By design](http://docs.automapper.org/en/stable/Inline-Mapping.html).

**Comment by ahedreville** [comment]
but this really what I wan't.
I want to get it mapped despite of having different members
I want that same member names get mapped and the rest get ignored
Who can I achieve this?
