### ISSUE TITLE
After upgrade to 6.2.0  -  xUnit test fixtures throw exception

### ISSUE THREAD

**Issue by petertsu** [AutoMapper/AutoMapper#2399]
Hi ,
After upgrade  from 6.1.1 to 6.2.0 i get the following "Mapper already initialized. You must call Initialize once per application domain/process.".

I have a xunit  test fixture for Microsoft.AspNetCore.TestHost.TestServer  and it used in many tests

   at AutoMapper.Mapper.set_Configuration(IConfigurationProvider value)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at My.Startup.ConfigureServices(IServiceCollection services) in C:\My\src\My\Startup.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at My.Tests.Fixtures.TestServerFixture`1..ctor() in C:\My\src\My\Tests\Fixtures\TestServerFixture.cs:line 27

**Comment by petertsu** [comment]
Could you help me with link ? Thanks

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Configuration.html

**Comment by petertsu** [comment]
I  have replaced the  call  services.AddAutoMapper(cfg => cfg.AddProfile<DefaultMapperProfile>()); in the Startup.cs

with  following 

 _mapperConfiguration = new MapperConfiguration(cfg => cfg.AddProfile<DefaultMapperProfile>());
   services.AddAutoMapper();


where  _mapperConfiguration  is private static field in the Startup .

Still get the same error in tests.   Where is my mistake ?

**Comment by lbargaoanu** [comment]
I think AddAutoMapper uses the static Mapper to do its job, you need to create a mapper using the newly created configuration.

**Comment by petertsu** [comment]
You're right .   

services.AddSingleton<IMapper>(
                new Mapper(new MapperConfiguration(cfg => cfg.AddProfile<DefaultMapperProfile>())));

works as a magic .
So there is an issue is with AutoMapper.Extensions.Microsoft.DependencyInjection .

Thank your help.

**Comment by lbargaoanu** [comment]
@jbogard I think AM.DI should be able to work with a MapperConfiguration object.

**Comment by jbogard** [comment]
You shouldn’t call services.AddAutoMapper multiple times. That should just
be called once at the start of all your tests.

**Comment by petertsu** [comment]
I call the services.AddAutoMappe one time in the Startup.cs. 
In my test project , I have used the Microsoft.AspNetCore.TestHost.TestServer to test an api .  I have created the  xUnit TestFixture  which creates Microsoft.AspNetCore.TestHost.TestServer . The TestFixture is shared between tests in the same test class . Bottom line the  TestFixture is created per test class and this is Ok by me , since  I would like to inject different mocks in the different tests

**Comment by jbogard** [comment]
Hmmmm I’ve done this before with child containers instead of this...since
calling configure is expensive.

Does their DI let you do that?

**Comment by petertsu** [comment]
As far as I know the default DI of the .NET Core doesn't support child containers

**Comment by hkosmidi** [comment]
Sorry for not understanding, but how did you solve the problem? Can you use autoMapper and run all test ?

**Comment by linuxninja39** [comment]
I'm running into this issue only when I'm using services.AddAutoMapper(typeof(Startup)) in Startup. I'm only calling it once. This works great when just running the server. However, when I try to use entity framework core database and migrations commands it dies with the "Initialize once" error. If I then remove that line, the database and migrations work fine, but the service will fail with a not initialized error

**Comment by mquelcutti** [comment]
Hi Linuxninja39 I was having the exact same issue as you . If you have a profile set up then you can do the following as stated above as this worked for me not ideal but hey

 services.AddSingleton(new Mapper(new MapperConfiguration(cfg => cfg.AddProfile<DutchMappingProfile>())));

Where DutchMappingProfile is the class for your profile you have set up eg

using AutoMapper;
using DutchTreat.Data.Entities;
using DutchTreat.ViewModels;

namespace DutchTreat.Data
{
    public class DutchMappingProfile : Profile
    {
        public DutchMappingProfile()
        {
            CreateMap<Order, OrderViewModel>()
                .ForMember(o => o.OrderId, ex => ex.MapFrom(o => o.Id));

            CreateMap<OrderViewModel, OrderItemViewModel>()
                .ReverseMap();
        }
    }
}

**Comment by john-luke-laue** [comment]
@mquelcutti Your solution worked for me. Except I suspect most people will be injecting IMapper, so this is what I have:

`services.AddSingleton<IMapper>(new Mapper(new MapperConfiguration(cfg => cfg.AddProfile<OneOfMyProfileClasses>())));
`

The major downside is that you'll have to manually add the profiles (with cfg.AddProfile) yourself instead of AutoMapper discovering/adding them for you like it does with `services.AddAutoMapper();`

**Comment by jbogard** [comment]
You don't have to do that any more, the
AutoMapper.Extensions.Microsoft.DependencyInjection project has
configuration for this:

`AutoMapper.ServiceCollectionExtensions.UseStaticRegistration = false;`

That will then do all the other stuff.

Or you can call `Mapper.Reset` right before you do `services.AddAutoMapper`

**Comment by mquelcutti** [comment]
Ok thanks will give it a go

**Comment by mrmkamranmalik** [comment]
i am using 1700 places where i use

**Comment by david-waterworth** [comment]
We're seeing the same behaviour. Running multiple xunit test fixtures services.AddAutoMapper(); throws already initialized exception regardless of whether Mapper.Reset() is called before services.AddAutoMapper() or not.

**Comment by david-waterworth** [comment]
The issue is we're running xunit to test an dotnet core aspnet project and the TestServer is being created each time a test runs so the aspnet service startup gets called multiple times. I think the workaround might be to create the TestServer and TestClients as statics in the test assembly

**Comment by jbogard** [comment]
The other option is to not use the static version.

**Comment by david-waterworth** [comment]
I didn't think we were, originally we just called services.AddAutoMapper() which I assumed was creating it's own instance. But then it started failing so we added Mapper.Reset() before it. Is there an example of how to configure AutoMapper to not use the static version in aspnet core 2.0?

**Comment by Henry-Keys** [comment]
Calling "AutoMapper.ServiceCollectionExtensions.UseStaticRegistration = false;" before services.AddAutoMapper solved the issue for me.

Without that my integration tests with TestServer using fixtures throws this:

> Failed   Taksapp.Web.IntegrationTests.Api.v1.Controllers.PassengerControllerTests.SignUpShould.ReturnForbiddenGivenIncorrectVerificationCode
> Error Message:
>  System.AggregateException : One or more errors occurred. (Mapper already initialized. You must call Initialize once per application domain/process.) (The following constructor parameters did not have matching fixture data: Fixture`2 fixture)
> ---- System.InvalidOperationException : Mapper already initialized. You must call Initialize once per application domain/process.
> ---- The following constructor parameters did not have matching fixture data: Fixture`2 fixture
> Stack Trace:
> 
> ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
>    at AutoMapper.Mapper.set_Configuration(IConfigurationProvider value)
>    at AutoMapper.Mapper.Initialize(Action`1 config)
>    at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
>    at Taksapp.Web.Startup.ConfigureServices(IServiceCollection services) in /Users/henrick/Projects/Taksapp/Taksapp.Web/Startup.cs:line 45
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
>    at Taksapp.Web.IntegrationTests.Fixtures.Fixture`2..ctor() in /Users/henrick/Projects/Taksapp/Taksapp.Web.IntegrationTests/Fixtures/Fixture.cs:line 51
> ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

**Comment by VictorioBerra** [comment]
I am having the exact same issue as @david-waterworth I am also using XUnit which I suspect may be the culprit. We need to find a way to fix this.

**Comment by david-waterworth** [comment]
@VictorioBerra I think you're right - we switched from XUnit to MSTest to work around this

**Comment by VictorioBerra** [comment]
@david-waterworth check this out, I was able to finally understand it all and get it working.

https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/55#issuecomment-405654121
