### ISSUE TITLE
ProjectTo overload which takes IMapper

### ISSUE THREAD

**Issue by kierenj** [AutoMapper/AutoMapper#2401]
Hi - I'm just integrating AutoMapper into our new app framework (.NET Core 2.0, EF Core 2.0, finally using non-static mapper).

I'm trying to keep boilerplate at a minimum, and was wondering if it there would be a downside to allowing an `IMapper` to be passed to a new overload of `ProjectTo`, with having to use `_mapper.ConfigurationProvider`. 

It's a minor point I know, but I'm already injecting an `IMapper`, and it would be super neat and clean.

What do you think? :)

**Comment by lbargaoanu** [comment]
You could easily write an extension method that does just that.

**Comment by kierenj** [comment]
You are quite right of course. I'm also seeing if it's useful enough to be a viable feature request.

**Comment by lbargaoanu** [comment]
ProjectTo needs a configuration, not a mapper. I think it would only create confusion. It takes a mapper, so it must be calling Map on it, right? :)

**Comment by kierenj** [comment]
I know it's subjective, but for me, it would be clearer and more concise.  Injecting the generically-named `IConfigurationProvider` into every query handler is not as clear as `IMapper`.

I get it's a design decision, I'm just providing my angle - for all I know as an API consumer, the `ProjectTo` could very well use members on an `IMapper`, and I would prefer something simpler and more self-descriptive than is there currently.

**Comment by lbargaoanu** [comment]
I disagree, so I'll close this, @jbogard will reopen it if he sees it your way.

**Comment by jbogard** [comment]
Yeah, it doesn't use mapping, it uses configuration. To me that's the most
explicit thing to do. It makes it clear that "this does not use any
in-memory mapping, only your mapping configuration".

Which already confuses people today, I don't want to make it more confusing.

**Comment by kierenj** [comment]
Ok, I can understand that.  I suppose it would be way too big of a change to consider renaming `IConfigurationProvider` to something like `IMapConfiguration`? :)
There's another ICP in Microsoft.Extensions.Configuration nowadays.  Not a big deal, but again just waving my little flag
