### ISSUE TITLE
Add Mapper.Reset back

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2404]
To support calling `Mapper.Initialize` multiple times, explicitly allow `Reset`

See discussion on #2399

**Comment by jbogard** [comment]
See also https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/36

**Comment by urasaber** [comment]
@jbogard so why did you guys implemented it that way that the Instance or Configuration properties throw exceptions from getter? Just return nulls if mapper is not initialized and then everyone can just check Instance == null to call Initialize once

Currently there's no way to check or ensure that mapper is not initialized except using try-catch

**Comment by lbargaoanu** [comment]
It was a convenience thing (for us), but anyway, there is no need for that check. In theory, after that check, somebody else could have called initialize, so the check is useless. It should be easy to ensure Initialize is only called once using smth like Lazy.

**Comment by mrmkamranmalik** [comment]
Thanks for Adding Mapper.Reset(), it make my life easy :-)
