### ISSUE TITLE
Mapping behaviour changed between 6.0.2 and 6.2.1

### ISSUE THREAD

**Issue by henrik-cp** [AutoMapper/AutoMapper#2408]
Hi,
When upgrading from 6.0.2 to 6.2.1 I found a change in the mapping behaviour that I found somewhat confusing. See the attached code for a runnable example

[AutoMappingTests.zip](https://github.com/AutoMapper/AutoMapper/files/1481626/AutoMappingTests.zip)

The difference is when mapping from a class that has only the Id of an object to a class that has both an Id and the object (DtoObject.Country in the example).

With the older version the dtoObject.Country was null in the mapped object, with the newer version dtoObject.Country is an empty Country object.

Is this by design or have I stumbled on a bug?

For this to happen the classes must look like in the example, if you change Country.Name to i.e. Country.CountryName or ViewModel.CountryName to ViewModel.NameOfCountry this will not happen.

Best regards,

Henrik

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html

**Comment by henrik-cp** [comment]
Hi lbargaoanu,

It seems that I have not fully grasped the concept of unflattening. A little fiddling with my classes makes the mapped object contain what I want. 

Many thanks for your help.

Best regards,
Henrik
