### ISSUE TITLE
Mapping a List to a larger List error

### ISSUE THREAD

**Issue by CJM3407** [AutoMapper/AutoMapper#241]
To start, in a real run of my application this probably wouldn't happen, but I wanted to understand why this is happening and if there is a workaround.

I have a mapping that is from a List of hourly weather data objects (forecast time, temperature, humidity, cloud cover, etc.).  I am mapping to a List of SOAP message objects that can only handle one data type at a time.  So I have to create a List of message objects for each weather attribute (temp, humidity, etc.).  There can be multiple hours in each message, they just have to correspond to the same attribute.  This creates for any size list an output list of 6 (# of weather attributes) message objects.  

So, I could be mapping 2 hours of weather forecasts into 6 message objects, where each object contains 2 hours.  Obviously, I am going to be getting around 24-48 hours of forecast data, so the source list is much larger than the 6 output.  But when unit testing, I am only testing a few hours for quickness.  This revealed an error in Automapper.  It would appear Automapper makes the assumption that the destination list will be the same size or smaller than the source.  Is there way to flag a mapping to not make this assumption?

Thank you for any assistance

Here is the error and the mapping code:
Destination property: Capacity
Exception of type 'AutoMapper.AutoMapperMappingException' was thrown. ---> System.ArgumentOutOfRangeException: capacity was less than the current size.
Parameter name: value

top of stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
System.Collections.Generic.List`1.set_Capacity(Int32 value)
SetCapacity(Object , Object )
AutoMapper.Internal.PropertyAccessor.SetValue(Object destination, Object value)

// Don't worry about syntax, this is a very cut down version of my mapping, but this covers the logic I explained up top
// Also, there is no issue with my mapping logic because I pull out everything inside the construct using and run directly in the unit test it works perfect.  My assumption is automapper assumes the list is going to get smaller
Mapper.CreateMap<List<WeatherInstance>, PowerSystemDataType>()
                .ConstructUsing(src =>
                                    {
                                        var psds = new PowerSystemDataType(); // collection object of type List<PSD>
                                        psds.Add(new PSD(Type="TempF", Value=src.Temperature));
                                        psds.Add(new PSD(Type="Humidity", Value=src.Humidity));
                                        psds.Add(new PSD(Type="Cloud Cover", Value=src.CloudCover));
                                                                                 ....  more weather attributes
                                        return psds;
                                    });

**Comment by riiight** [comment]
FYI, I ended up going this route because determining the Capacity before the mapping would not be straightforward in my code:
`.ForMember(dest => dest.Capacity, opts => opts.Ignore())`
It seems to work though I'm guessing there may be some sort of minor performance penalty.
