### ISSUE TITLE
Ignore inheritance when mapping

### ISSUE THREAD

**Issue by samiraguiar** [AutoMapper/AutoMapper#2410]
Say that I have the following:
```csharp
class A {}
class B : A {}

var automapperConfig = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true);
var mapper = automapperConfig.CreateMapper();

var a = mapper.Map<A>(new B());
```

Since `B` inherits from `A`, Automapper doesn't need to do any mapping since polymorphism is happening here. However I need to *force* the mapping to happen since I need the runtime type of `a` to be `A`, and not `B`.

Any way to workaround this issue?

**Comment by jbogard** [comment]
Create an explicit map from B to A. That tells AutoMapper “I want you to
explicitly map”

**Comment by samiraguiar** [comment]
Thanks, @jbogard, it worked (and I feel kinda dumb now).

**Comment by jbogard** [comment]
Lol it’s a common mistake.
