### ISSUE TITLE
UseValue doesn't seem to actually use the value I provide

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#2412]
I have a mapping which takes a bunch of lists of objects and puts them in a set during the `AfterMap`-phase. I need to use a custom equality comparer, so I initialize the target set with `UsingValue`, but it seems that it gets a generic `ObjectEqualityComparer` instead.

Here's the mapping configuration I use:

```
cfg.CreateMap<StuffSource, StuffDest>()
    .ForMember(dest => dest.Things,
        opt => opt.UseValue(new HashSet<IResource>(new ResourceEqualityComparer<IResource>())))
    .AfterMap((src, dest) =>
    {
        dest.Things.UnionWith(src.Foos);
        dest.Things.UnionWith(src.Bars);
    });
```

Now, given `var foos = new[] { new Foo {Id = "1"}, new Foo {Id = "2"},  new Foo {Id = "1"} };` and `var bars = new[] { new Bar {Id = "1"}, new Bar {Id = "1"} };` I would have expected the resulting set to contain two `Foo`s and one `Bar`, but it actually contains three `Foo`s and two `Bar`s.

There is an entire runnable program [here](https://gist.github.com/tlycken/e00dbae3deabcdf95a7ab07f9c308db7) that the current behavior, as well as the behavior I expect.

Is it my usage of `UseValue/AfterMap` that's incorrect, or is this a bug somewhere?

**Comment by lbargaoanu** [comment]
UseValue needs a constant and that constant is mapped to the destination. That should explain what you're seeing. I didn't try you example, so you might want to check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). I don't think you need AfterMap here. You need a resolver that does both things. So please try that and get back to us.

**Comment by tlycken** [comment]
@lbargaoanu Performing the exact same mapping with a custom resolver turned out to be much cleaner. Thanks for the quick response! :)
