### ISSUE TITLE
Service Fabric + Automapper 

### ISSUE THREAD

**Issue by EvilAvenger** [AutoMapper/AutoMapper#2413]
Currently we have almost the same problem, that is described here #2399.

Service Fabric tries to initialize an application and it has already executed ConfigureServices() method successfully and is trying to execute Configure().

In rare cases Configure method can throw an exception. (and it still is fine, as our service will be restarted by SF) So SF restarts the app  and is doing it just in the same process. Which means it is trying to execute ConfigureServices() method again.
And here we go:

> Mapper already initialized. You must call Initialize once per application domain/process.
   at AutoMapper.Mapper.set_Configuration(IConfigurationProvider value)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at myITprocess.StrategyApi.Startup.ConfigureServices(IServiceCollection services)

We've fixed it by setting 
`Mapper.Reset(); 
services.AddAutoMapper();`

but the solution seems to be a bit of a hack.

**Comment by lbargaoanu** [comment]
You should switch to the instance based API. See [this](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/11f0eca3d768885b9e691e7736f6612b3e664b1a/test/AutoMapper.Extensions.Microsoft.DependencyInjection.Tests/RegistrationTests.cs).

**Comment by EvilAvenger** [comment]
Haven't seen this yet. Thanks a lot

**Comment by dmitry-pavlov** [comment]
`Mapper.Reset()` tries to set `null` to the instance properties and fails as they are instantiated already. I would suggest by the way to add these improvements: 

1. Provide a really safe way to reset Mapper
2. Provide a way to "initialize mapper if not initialized yet" or "re-initialize mapper" 
3. Provide the property "if the mapper is already initialized" at least

**Comment by lbargaoanu** [comment]
There is no safe way to reset the mapper. You should switch to the instance based API.

**Comment by mihaj** [comment]
How then to setup Automapper in Test Environment in the startup.cs? I have the code here:
`            if (_env.EnvironmentName == "Test")
            {
                //this returns Mapper already initialized in my tests.
                services.AddAutoMapper(typeof(Startup));
            }
            else
            {
                services.AddAutoMapper(typeof(Startup));
            }`

**Comment by jbogard** [comment]
A static constructor works.

**Comment by mihaj** [comment]
I tried with

```
Mapper.Initialize(cfg => {
    cfg.AddProfile<MyProfile>();
});
```
The same thing. I also tried to add Mapper.Reset() before it.

**Comment by mihaj** [comment]
in my startup.cs in MVC solution I have:

```         
            if (_env.EnvironmentName == "Test")
            {
                Mapper.Reset();
                Mapper.Initialize(cfg =>
                {
                    cfg.AddProfile<ApiMapperProfile>();
                });
            }
            else
            {
                services.AddAutoMapper(typeof(Startup));
            }
```
And in xUnit TestFixture:
```
        public readonly TestServer _testServer;

        public HttpClient Client { get; }

        public TestServerFixture()
        {
            _testServer = new TestServer(new WebHostBuilder()
                .UseContentRoot(GetContentRootPath())
                .UseEnvironment("Test")
                .UseStartup<API.Startup>());

            Client = _testServer.CreateClient();
            Client.BaseAddress = new Uri("http://localhost");
        }

        public void Dispose()
        {
            Client.Dispose();
            _testServer.Dispose();
        }
```

And I still get the error, of `(Mapper already initialized. You must call Initialize once per application domain/process.) (The following constructor parameters did not have matching fixture data: TestServerFixture fixture`
