### ISSUE TITLE
Collection to List Mapping Breaks with newer version

### ISSUE THREAD

**Issue by cblaze22** [AutoMapper/AutoMapper#2414]
I am using 6.2.1 version of Automapper, up from 2.1.267 and am getting the error below which I didn't with the older version.  Is this a bug of something I need to work around?

``{"Unable to cast object of type 'System.Collections.ObjectModel.Collection`1[Tournaments.Data.Entities.EventEmailTemplate]' to type 'System.Collections.Generic.List`1[Tournaments.Data.Entities.EventEmailTemplate]'."}	System.Exception {System.InvalidCastException}```

**Comment by lbargaoanu** [comment]
You can try setting UseDestinationValue, but other than that, a repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by cblaze22** [comment]
It's just a mapping of Collection to List does not work and you may want to look into it.  I just changed the Collection to List, and it's working fine now but this didnt happen before.
