### ISSUE TITLE
ResolveUsing with resolution context boxing problem when upgrading from 6.1.1 to 6.2.1

### ISSUE THREAD

**Issue by dziedrius** [AutoMapper/AutoMapper#2416]
### Source/destination types

```csharp
    public class Item
    {
        public Guid Id { get; set; }
        public Guid? ParentItemId { get; set; }
    }
```

### Mapping configuration
```csharp
CreateMap<Item, Item>()
.ForMember(x => x.Id, x => x.MapFrom(s => SequentialGuid.New()))
.ForMember(x => x.ParentItemId, x => x.ResolveUsing((sourceItem, destinationItem, value, resolutionContext) => resolutionContext.Items[ParameterNames.ParentItemId]))
```

### Expected behavior

We were mapping like this:
```csharp
var newItem = Mapper.Map<Item>(Item, x =>
                {
                    x.Items.Add(EntityAutoMapperProfile.ParameterNames.ParentItemId, destinationFolder.Id);                  
                });
```
and in 6.1.1 it was working fine.

### Actual behavior

In 6.2.1 it crashes with quite obscure exception:

```
AutoMapper.AutoMapperMappingException : Error mapping types.

Mapping types:
Item -> Item
Models.Item -> Models.Item

Type Map configuration:
Item -> Item
Models.Item -> Models.Item

Property:
ParentItemId
  ----> System.InvalidOperationException : Nullable object must have a value.
   at lambda_method(Closure , Item_8532568509AC442361ABA46B56C8513DC8C78FA207EC0CBF7BBBC3EE226DB66A , Item , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
```

The reason is, that when you add value to resolution context, it is boxed to object and then I guess ResolveUsing is trying to assign that boxed value to nullable Guid and fails with paradoxical exception (the very reason for existence of nullable types is ability for such instances not to have value :) So if I cast value from resolution context to Guid? before returning, it works fine.

Now I'm fine with the fact, that value from resolution context would need to be casted to destination type and to be fair by filling this issue I'm more trying to help others facing the issue find solution faster, but there are couple points too:
1) It looks like a breaking change for minor version update
2) If we could make the exception be not so cryptic, that would help a lot
3) If we could catch this when validating mappings would be great. That might be not so easy, so may be we could solve this by not exposing resolutionContext.Items directly, rather use something like 
``` csharp
resolutionContext.GetItem<T>(key).
```

**Comment by lbargaoanu** [comment]
Casting is the way to go (null doesn't have a useful type). If you mind that,

    exp.CreateMap<object, Guid?>().ConvertUsing(s=>((Guid?)s).GetValueOrDefault());
