### ISSUE TITLE
Sql time(7) type to C# TimeSpan type mapping error

### ISSUE THREAD

**Issue by promikhail** [AutoMapper/AutoMapper#2417]
Hello!

I have a class:
`public class Calendar
    {
        public string Building { get; set; }
        public string Category { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public string Fio { get; set; }
        public string FullDescription { get; set; }
        public int PersonId { get; set; }
        public string Room { get; set; }
        public TimeSpan TimeBegin { get; set; }
        public TimeSpan TimeEnd { get; set; }
        public string TypeWorkName { get; set; }
    }`

DataReader returns columns with corresponding types:
`
NVarChar -> String,
Int -> Int,
Time(7) -> TimeSpan
`

Trying to map with:
`config.CreateMap<IDataReader, Calendar>();`

But I got error:
> Value cannot be null. Parameter name: con

This error throws only when class has properties with TimeSpan type.

Help! How to workaround this problem?

DotNetCore 2.0
AutoMapper version 6.2.1,
AutoMapper.Data version 1.0.0

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by promikhail** [comment]
Even so, I think this problem refers to AutoMapper internal error. No?
Cuz, DataReader returns correct TimeSpan, but AutoMapper cannot map to class property.

**Comment by lbargaoanu** [comment]
If you can make a repro only with AM, without AM.Data, we'll take a look. Smth like [this](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9), a gist that we can execute and see fail.
