### ISSUE TITLE
Moving to Windows 8 get “InvalidProgramException: Common Language Runtime detected an invalid program”

### ISSUE THREAD

**Issue by fongx** [AutoMapper/AutoMapper#242]
I'm developing a .NET 4.0 application with AutoMapper(https://github.com/AutoMapper) on Windows 7. Today I get the source code from SVN to a new Windows 8 machine, build and then run the app, it throws me "InvalidProgramException: Common Language Runtime detected an invalid program". I rebuild the source codes and it runs well on all other three Windows 7 machines. I guess it does matter with Windows 8. I write the following small console application. I build the source code on Windows 8 and it does run well on Windows 7 but doesn't on Windows 8. So it's something about the runtime on Windows 8. It seems only something wrong with the enum type whose underlying type is not the default type, Int32.

After googling, people say it's about JIT compiler but I still have no idea. I use VS 2010 targeted .NET 4.0 on both Windows 7 and Windows 8. Does any change about this in Windows 8? I'm reading the Source code of AutoMapper. I think it really something wrong with C# or CLI. Hope you give some clue. Thanks.

class Program
{
    enum PriorityModel  { High, Normal, Low }
    enum PriorityDto { High, Normal, Low }

```
enum PriorityModel2 : byte { High, Normal, Low }
enum PriorityDto2 : byte { High, Normal, Low }

enum PriorityModel3 : short { High, Normal, Low }
enum PriorityDto3 : short { High, Normal, Low }


static void Main(string[] args)
{
    Mapper.CreateMap<PriorityModel, PriorityDto>();  // OK
    Mapper.CreateMap<PriorityModel2, PriorityDto2>();  // [InvalidProgramException: Common Language Runtime detected an invalid program.]
    Mapper.CreateMap<PriorityModel3, PriorityDto3>();  // [InvalidProgramException: Common Language Runtime detected an invalid program.]

    Console.Read();
}
```

}

exception stacktrace:

[InvalidProgramException: Common Language Runtime detected an invalid program.]
   System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method) +0
   System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target) +43
   System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate() +81
   System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator) +205
   AutoMapper.DelegateFactory.CreateGet(FieldInfo field) +156
   AutoMapper.Internal.FieldGetter..ctor(FieldInfo fieldInfo) +60
   AutoMapper.ReflectionHelper.ToMemberAccessor(MemberInfo accessorCandidate) +124
   AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, IMappingOptions options, MemberList memberList) +269
   AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) +86
   AutoMapper.ConfigurationStore.CreateMap(String profileName, MemberList memberList) +45
   AutoMapper.ConfigurationStore.CreateMap() +13
   AutoMapper.Mapper.CreateMap() +51

**Comment by jumas45** [comment]
I am having a similar issue on Windows 2012 R2. The application works fine under IIS Express (Running Visual studio on the server) But when I deploy the application in IIS I get the Automapper error. :-(

I tried installing the patch but apparently it says, its not applicable for Win 2012 even though the microsoft article says its applicable.

Is there any way around this.
-----------------------

{"Message":"An error has occurred.","ExceptionMessage":"\r\n\r\nMapping types:\r\nIDataReader -> IList`1\r\nSystem.Data.IDataReader -> System.Collections.Generic.IList`1[[.SncSubCategoryInfo, , Version=0.9.5582.23112, Culture=neutral, PublicKeyToken=null]]\r\n\r\nDestination path:\r\nIList`1\r\n\r\nSource value:\r\nSystem.Data.DataTableReader","ExceptionType":"AutoMapper.AutoMapperMappingException","StackTrace":"\r\nServer stack trace: \r\n at Services.SncSubCategoryInfoServiceAccess.GetAllSncSubCategoryInformation(Int32 companyId)\r\n\r\nException rethrown at [0]: \r\n at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)\r\n at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)\r\n at .ISncSubCategoryInfoService.GetAllSncSubCategoryInformation()\r\n at BESOWebApi.Controllers.SncSubcategoriesController.Get() in c:\\TFS\\Enterprise Library\\BESO Root\\BESO Web Api\\Main\\Source\\BESOWebApi\\BESOWebApi\\Controllers\\SncSubcategoriesController.cs:line 36\r\n at lambda_method(Closure , Object , Object[] )\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)\r\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.AuthenticationFilterResult.d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Common Language Runtime detected an invalid program.","ExceptionType":"System.InvalidProgramException","StackTrace":" at DynamicCreate(IDataRecord )\r\n at AutoMapper.Mappers.DataReaderMapper.LoadDataReaderViaList(IDataReader dataReader, IMappingEngineRunner mapper, Build buildFrom, ResolutionContext resolveUsingContext, Type elementType) in c:\\dev\\AutoMapper\\src\\AutoMapper\\Mappers\\DataReaderMapper.cs:line 78\r\n at AutoMapper.Mappers.DataReaderMapper.MapDataReaderToEnumerable(ResolutionContext context, IMappingEngineRunner mapper, Type destinationElementType, Boolean useYieldReturn) in c:\\dev\\AutoMapper\\src\\AutoMapper\\Mappers\\DataReaderMapper.cs:line 69\r\n at AutoMapper.Mappers.DataReaderMapper.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\\dev\\AutoMapper\\src\\AutoMapper\\Mappers\\DataReaderMapper.cs:line 29\r\n at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\\dev\\AutoMapper\\src\\AutoMapper\\MappingEngine.cs:line 246"}}

-----------------------
