### ISSUE TITLE
6.2.1 doesn't map properties of specific implementation of interfaces

### ISSUE THREAD

**Issue by swisszeni** [AutoMapper/AutoMapper#2420]
### MCVE

[See gist](https://gist.github.com/swisszeni/2fe024507571d5f59ac18e49b8a2ed08)

### Expected behavior

With 6.2.0, the `Name` property of `BarDto` gets Mapped to the same property in `Bar`

### Actual behavior

With 6.2.1, the `Name` property doesn't get mapped and is `null` in `Bar`

### Steps to reproduce

Use the gist as a console App with AutoMapper 6.2.0 and 6.2.1. Don't forget to clean the solution between version change.

**Comment by lbargaoanu** [comment]
@jbogard I'm guessing #2403, if it works in 6.2.0, but not in 6.2.1.

**Comment by lbargaoanu** [comment]
As far as I can tell this used to work more or less by accident. No map matches. When matching <IBarDto, IBar>, only base types are considered, so <BarDto, IBar> won't fit. So there was a fallback to match runtime types and _then_ <BarDto, IBar> fits the bill. But now, with dynamic maps, a default map is created and that doesn't help. So I don't know about a fix. But you can set CreateMissingTypeMaps to false or MapAtRuntime for BarObject to get the old behavior.
