### ISSUE TITLE
The error messages for failed inline maps could be more helpful

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#2423]
I like the new inline mapping feature when it works, but when I get an auto-generated inline map that doesn't work, I find the error message a little confusing, since it's the same as if I had created a map that's invalid. For example, given the following types,

```csharp
public class Foo
{
	public string Baz { get; set; }
}

public class Bar
{
	public string Qux { get; set; }
}
```
mapping configuration, and call

```csharp
var mapper = new AutoMapper.MapperConfiguration(cfg => {}).CreateMapper();
mapper.Map<Bar>(new Foo { Baz = "hello"})
```

the error message is

>AutoMapperConfigurationException: 
>Unmapped members were found. Review the types and members below.
>Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type. For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
>\===============================
>Foo -> Bar (Destination member list)
>UserQuery+Foo -> UserQuery+Bar (Destination member list)
>
>Unmapped properties:
>Qux

This sends me down a goose chase for a mapping between these types, where I can re-configure how to map to the `Qux` property. If I suppress inline mappnig (using `CreateMissingTypeMaps = false`), I instead get the following message, which more accurately tells me what I need to do:

> AutoMapperMappingException: Missing type map configuration or unsupported mapping.
> 
> Mapping types:
> Foo -> Bar
> UserQuery+Foo -> UserQuery+Bar

With this error message, it's clear to me that I haven't configured a mapping from `Foo` to `Bar`, and that I need to do so manually.

Tested in version 6.2.1.

**Comment by lbargaoanu** [comment]
It creates a map for you and that map is invalid. It says that maybe when you said Qux, you meant Baz. Such are the joys of automatic mappings. It cannot guess what you meant.

**Comment by tlycken** [comment]
I'm not saying it shouldn't fail - of course there's no way for it to figure out what I want.

What I'm trying to say is that I find it confusing that it complains about a mapping I didn't create, rather than complain that I didn't create the mapping :)

**Comment by lbargaoanu** [comment]
And I've tried to explain why. It seems silly for it to complain that you didn't create the map, because that's what it does, it automatically creates the map for you, trusting you that indeed the mapping can just work. It assumes that you made a spelling error or something. It doesn't say, you know man, that wasn't even close, so just create that map already. I think :)

**Comment by tlycken** [comment]
But the resolution to the problem is to either rename the property, in case there's a spelling mistake, or - more likely, to create the map and add a customization.

But even if we don't want to show the "missing map" message, even an indication at the top of the error message that it concerns an inline map would be helpful. What I'm after is really something in the error message that tells me that the error is not in a map that I have created and configured, but somewhere else (either a spelling mistake in the property names, or the fact that I haven't created a map that needs to be manually configured).

**Comment by lbargaoanu** [comment]
I agree, it seems helpful for it to say that the map is automatically created. You can try a PR.
