### ISSUE TITLE
Mapping from AnonymousType in 6.2.1

### ISSUE THREAD

**Issue by Tsve** [AutoMapper/AutoMapper#2424]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
var mappingConfig = new MapperConfiguration(cfg => {                
                cfg.CreateMissingTypeMaps = true;
            });

            m_Mapper = mappingConfig.CreateMapper();
```

### Expected behavior

Work

### Actual behavior

throw Exception

### Steps to reproduce

Im map some anonymous type with property A and B to type with only A property.
In 6.1.1 is work perfect, but 6.2.0 and 6.2.1 im get error like 

Message	"\nUnmapped members were found. Review the types and members below.\nAdd a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type\nFor no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters\n\r\n<>f__AnonymousType15`5 -> User (Destination member list)

```csharp
 var result = m_Mapper.Map<List<AccountDto>>(acc);
```

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/stable/Inline-Mapping.html#inline-validation
