### ISSUE TITLE
How To Set all Properties of a given Name to the value of a Static?

### ISSUE THREAD

**Issue by BoasE** [AutoMapper/AutoMapper#2426]
I'm using automapper in a project of mine.
But currently i'm stuck with one usecase.

I want that whenever a target model has a Property with the name ```CurrentUserId``` it is Set to ```ClaimsPrincipal.Current.GetUserId()```.

I tried to use  ```cfg.ForAllPropertyMaps``` but there i've only found UseValue which doesn't accept a delegate. 

What am I missing ? or is it just not working this way`?

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/47440313/automapper-map-userid-property-by-name-to-static-value?noredirect=1#comment81881166_47440313
