### ISSUE TITLE
Conditional property mapping in Automapper not working

### ISSUE THREAD

**Issue by pkmetski** [AutoMapper/AutoMapper#2429]
### Source/destination types

```csharp
public class User
{
    public Address Address { get; set; }
}

public class Address
{
    public string Street { get; set; }
}

public class UserDto
{
    public string AddressStreet { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<UserDto, User>()
            .ForPath(dest => dest.Address.Street, opt => opt.Condition(cond => !string.IsNullOrEmpty(cond.Source.AddressStreet)))
            .ForPath(dest => dest.Address.Street, opt => opt.MapFrom(src => src.AddressStreet));
```

### Version: x.y.z
6.2.0

### Expected behavior

User.Address remains null in case UserDto.AddressStreet is null

### Actual behavior

Automapper creates an instance of User.Address regardless whether the condition/precondition is met or not
### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg =>
 {
       cfg.AddProfiles(typeof(UserProfile));
 });
config.AssertConfigurationIsValid();
var mapper = config.CreateMapper();

var userDto = new UserDto{ AddressStreet = null };
var user = mapper.Map<User>(userDto);
var address = user.Address;//I expect the prop to be null, since the mapping condition is not met...

**Comment by lbargaoanu** [comment]
The condition controls only the assignment to that property. There might be another ForPath that needs Address.

**Comment by pkmetski** [comment]
@lbargaoanu Not sure what you mean by 'There might be another ForPath that needs Address.'
The code I have provided does not have another ForPath and yet Address is instantiated. Clearly the instantiation phase takes at the beginning of the mapping, rather than when a property is accessed. My question here was if it is possible to change that behavior, or is this by design (why would that be?), or if this is a bug (looks like it).

**Comment by lbargaoanu** [comment]
In the general case you can have an instance created regardless of any conditions, because another ForPath might need it. So I don't mind the current behavior.
