### ISSUE TITLE
Always null value IMemberValueResolver aspnet core

### ISSUE THREAD

**Issue by irowbin** [AutoMapper/AutoMapper#2431]
I am trying to resolve `UsersDto` using `IMemberValueResolver` but I am getting nothing but null.

### Source/destination types

```csharp

// Destination
public class ItemDto
{
   // other members are skipped
   // produce {id:1, text:'user name'}
   public List<UsersDto> UsersDto {get; set;} 
}

// Source
public class ItemSource
{
    // other members are skipped
   // contains user Identities [1,2,3,4,5,6] for logic
   public string UsersKeys {get; set;} 
}


```

### Mapping configuration

```csharp

// mapping profile
public class ManagingUserProfile : Profile
{
   public ManagingUserProfile ( )
   {
     CreateMap<ItemSource, ItemDto>()
        .ForMember(x => x.UsersDto , opt => 
                   opt.ResolveUsing<ResolveUsers, string>(src => src.UsersKeys ))
   }
}

// added to the startup class service collection
 services.AddAutoMapper(cf =>
 {
       cf.AddProfiles(  "MyProject.Users" );
 });

// i was trying to resolve using IMemberValueResolver
public class ResolveUsers : IMemberValueResolver<ItemSource , ItemDto , string, List<UsersDto>>
    {    
        public List<UsersDto> Resolve(ItemSource source, ItemDto destination, string sourceMember,
                                          List<UsersDto> destMember, ResolutionContext context)
        {
            if (string.IsNullOrEmpty(sourceMember))
                return null;
            // logic to get users from repository
      

            return new List<DropdownDto> { new DropdownDto { Id = 1, Text = "a" } };
        }
    }

```

### Version: x.y.z
 
**6.2.1**

### Expected behavior

The list of `UserDto` should be resolved.

### Actual behavior
The list of `UserDto` always null.

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
 
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by irowbin** [comment]
@lbargaoanu Yeah you think it is but, I did the exact same thing on the above code followed by here [How to use the new IValueResolver of AutoMapper](https://stackoverflow.com/a/38308705/4444844)  and I thought it was an issue. 

if I ask this in there, that'll be a duplicate so they'll keep pointing me to the same place again.

**Comment by irowbin** [comment]
@lbargaoanu  The same code above works with a single map but didn't work with a list. 

```c#
// did not worked
var dto = _mapper.Map<List<ItemDto>>(entity);

// worked
var dto = _mapper.Map<ItemDto>(entity);
```
Any idea or i missed something here? Thanks.

**Comment by lbargaoanu** [comment]
// logic to get users from repository
Just a wild guess, maybe that's where the problem lies? :) Because I don't see a repro yet.

**Comment by irowbin** [comment]
@lbargaoanu Sorry for not creating repro but, It did hit the breakpoint when using `_mapper.Map<ItemDto>(entity)`  and when I use the generic `List<ItemDto>`, the resolver class never hit by the breakpoint. I've removed all the logic from there to debug properly so I came up with the problem that it won't execute the resolver for type `List<ItemDto>`, only works with single instance `Map<ItemDto>(entity)` and I got no exceptions too but null value for type `List<ItemDto>`. I must have missed something so if you think that I am missing something, please advice me otherwise I will create a repro for you. Thanks!
