### ISSUE TITLE
ReverseMap not ignoring source member as instructed

### ISSUE THREAD

**Issue by mrpmorris** [AutoMapper/AutoMapper#2432]
### Source/destination types

```csharp
// Put your source/destination types here
```

C# Core

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```
            CreateMap<VehicleData, Vehicle>(MemberList.Source)
                .ForSourceMember(src => src.FleetId, opts => opts.Ignore())
                .ReverseMap();

### Version: x.y.z
 
6.2.1

### Expected behavior
FleetId should not be mapped

### Actual behavior
FleetId is being mapped

### Steps to reproduce

    public class VehicleData
    {
        public Guid FleetId { get; set; }
        public string Registration { get; set; }
    }

    public class Vehicle
    {
        public Guid FleetId { get; set; }
        public string Registration { get; set; }
    }

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```
            var mapperConfig = new MapperConfiguration(cfg => cfg.AddProfile<AutoMapperProfile>());
            mapperConfig.AssertConfigurationIsValid();
            IMapper mapper = mapperConfig.CreateMapper();

            var newVehicle = new Vehicle
            {
                FleetId = Guid.NewGuid()
            };
            VehicleData newVehicleData = mapper.Map<VehicleData>(newVehicle);
            if (newVehicleData.FleetId != Guid.Empty)
                throw new InvalidOperationException("FleetId should not be set");

**Comment by lbargaoanu** [comment]
I'll close this as this is the expected behavior and I see you opened another issue about changing it.
