### ISSUE TITLE
Make ForSourceMember's behaviour more obvious (and consistent)

### ISSUE THREAD

**Issue by mrpmorris** [AutoMapper/AutoMapper#2433]
Take the following example, 
```
public class SourceClass
{
  public string CommonMember { get; set; }
  public string SpecialMember { get; set; }
}

public class DestClass 
{
  public string CommonMember { get; set; }
}

public class AutoMapperProfile : Profile
{
    public AutoMapperProfile()
    {
        CreateMap<SourceClass, DestClass>(MemberList.Source);
    }
}
```

When calling AssertConfigurationIsValid this will complain that SourceClass.SpecialMember has no mapping. The solution to this is to tell AutoMapper to ignore it

```
CreateMap<SourceClass, DestClass>(MemberList.Source)
    .ForSourceMember(src => src.SpecialMember, opts => opts.Ignore());
```

This explicitly associates ForSourceMember with forward mapping behaviour, as there is no other way to specify this source member should not be mapped forward due to it having no equivalent destination member.

However, if we now add a SpecialMember property to the DestClass we see that ForMemberSource only applies when doing a ReverseMap, and the value is copied from Source to Dest.

So, in one case it applies to mapping Source to Dest and in another it applies only to reverse mapping Dest to Source and has no effect the other way around. This isn't intuitive, and is quite confusing. In fact, I am not even certain it is supposed to work this way for ReverseMap, because it still seems to map in both directions anyway (I have just raised a bug for that).

Would it be possible to mark some methods as Obsolete and encourage people to use a new naming scheme? I'd like to propose the following:

.ReverseMap() => .AllowReverseMapping(); - This makes it clear you aren't creating only a reverse map, but additionally allowing reverse mapping (not important, just nice).

opts.Ignore() => opts.DoNotMap( ...options...); - Where options is MapOptions.Forward, MapOptions.Reverse;

No replacement for ForSourceMember, instead add

AlwaysIgnoreSourceMember(src => src.SomeName);
AlwaysIgnoreDestinationMember(dst => dst.SomeName);

I think this would make everything very clear.

**Comment by lbargaoanu** [comment]
cc @jbogard

**Comment by mrpmorris** [comment]
@jbogard Is this closed as "won't do"? I think the way to ignore source members is very confusing.
