### ISSUE TITLE
Automapper in Xamarin.iOS can't build

### ISSUE THREAD

**Issue by topfunet** [AutoMapper/AutoMapper#2434]
I use automapper in xamarin.forms, but Xamarin.iOS project can't build.
It seems like System.Reflection.Emit.dll has two version, one in
C:\Users\user\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll
and another in
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Reflection.Emit.dll
It says i have to remove one of the duplicate references.

**Comment by topfunet** [comment]
[Deployments.zip](https://github.com/AutoMapper/AutoMapper/files/1505720/Deployments.zip)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by cmcginty84** [comment]
I had the same build error with AutoMapper 6.2.2 and Xamarin Forms 2.5.0.121934 in my Xamarin.iOS application. Simply removing AutoMapper's nuget package from the Netstandard 2.0 library referenced by the Xamarin.iOS project fixed the build error.

**Comment by topfunet** [comment]
Have you found solution?

**Comment by cmcginty84** [comment]
No not yet - I am just focusing on Android development at the moment with Xamarin forms.

**Comment by mwo-dk** [comment]
.iOS projects do not allow packages depending on System.Reflection.Emit
