### ISSUE TITLE
NullReferenceException when mapping List to ObservableCollection and CollectionChanged event not fired

### ISSUE THREAD

**Issue by morawiec88** [AutoMapper/AutoMapper#2437]
### Source/destination types

Source:
```csharp
    class CollectionHolderDto
    {
        public CollectionHolderDto()
        {
            Col1 = new List<List<int>>();
        }

        public List<List<int>> Col1 { get; set; }
    }
```

Destination:
```csharp
    class CollectionHolder
    {
        public CollectionHolder()
        {
            Col1 = new ObservableCollection<List<int>>();
            Col1.CollectionChanged += Col1_CollectionChanged;
        }

        private void Col1_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            Console.WriteLine("Changed");
        }

        public ObservableCollection<List<int>> Col1 { get; set; }
    }
```

### Mapping configuration

```csharp
            AutoMapper.Mapper.Initialize(cfg => cfg.CreateMap<CollectionHolderDto, CollectionHolder>()
                .ForMember(a => a.Col1, opt => opt.UseDestinationValue())
            );
```

### Version: x.y.z
6.2.1

### Expected behavior

1. No Exception on mapping
2. CollectionChanged event fired on mapping without UseDestinationValue - it was working in version 4.2.1

### Actual behavior

NullReferenceException was thrown when using UseDestinationValue or CollectionChanged event was not fired without UseDestinationValue

### Steps to reproduce

```csharp
            CollectionHolderDto ch = new CollectionHolderDto();
            ch.Col1.Add(new List<int>() { 5, 6 });
            var mapped = AutoMapper.Mapper.Map<CollectionHolder>(ch);
```

**Comment by lbargaoanu** [comment]
As a workaround, you can omit UseDestinationValue.

**Comment by morawiec88** [comment]
If I do that, then my original issue comes:

CollectionChanged event fired on mapping without UseDestinationValue - it was working in version 4.2.1

The code in 4.2.1 was covering this situation like that:

```csharp
            var sourceLength = enumerableValue.Count;
            var destination = GetOrCreateDestinationObject(context, destElementType, sourceLength);
            var enumerable = GetEnumerableFor(destination);

            ClearEnumerable(enumerable);
```

so ClearEnumerable was firing event on _the same_ object that was originally attached to the property.
Currently the reference is changed so events are not fired on the same object.

Any hints how to fix that?

**Comment by lbargaoanu** [comment]
You can pass the destination in the Map call. Or wait for a fix :)

**Comment by morawiec88** [comment]
Perfect, thanks! When do you expect fix to be released? :)

**Comment by lbargaoanu** [comment]
Not soon :)

**Comment by lbargaoanu** [comment]
But there is always the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by morawiec88** [comment]
Got it via MyGet. Thanks again!
