### ISSUE TITLE
AssertConfigurationIsValid() should fail for map to primitive type when mapping is not known

### ISSUE THREAD

**Issue by nphmuller** [AutoMapper/AutoMapper#2439]
### Source/destination types

```csharp
public class Source
{
    public int Id { get; set; }
}
```

### Mapping configuration

```csharp
new MapperConfiguration(cfg => cfg.CreateMap<Source, int>())
```

### Version: x.y.z
6.2.1

### Expected behavior
Calling `AssertConfigurationIsValid()` should throw an `AutoMapperConfigurationException` with a message indicating that the primitive type destination (int) mapping is not known.

### Actual behavior

`AssertConfigurationIsValid()` succeeds.

### Steps to reproduce

```csharp
public class MapperConfigurationTests
{
    [Fact] // This fails
    public void MapOfUnconfiguredPrimitiveShouldBeInvalid()
    {
        var config = new AutoMapper.MapperConfiguration(cfg => cfg.CreateMap<Source, int>());
        Assert.Throws<AutoMapperConfigurationException>(() => config.AssertConfigurationIsValid());
    }

    [Fact] // This succeeds
    public void MapOfUnconfiguredPrimitiveShouldNotMap()
    {
        var config = new AutoMapper.MapperConfiguration(cfg => cfg.CreateMap<Source, int>());
        var res = config.CreateMapper().Map<int>(new Source() { Id = 5 });
        Assert.NotEqual(5, res);
    }

    public class Source
    {
        public int Id { get; set; }
    }
}
```

This is probably due to ConfigurationValidator not explicitely checking for unmapped primitive destination types. It only checks for unmapped properties and if it can be constructed.

**Comment by lbargaoanu** [comment]
CreateMap in this case means you're taking over the mapping, so what you're missing is ConvertUsing, the map itself exists. This is further complicated in the latest version by the fact that CreateMissingTypeMaps is true by default and probably creates a default map at runtime. It's true that the default map doesn't have a converter either. Also this might break people. It's tricky.

**Comment by lbargaoanu** [comment]
You can do that yourself using [custom validation](https://github.com/AutoMapper/AutoMapper/blob/7a00700de61cd3234b6a6eb4bf0f6bbe402369b1/src/UnitTests/ConfigurationValidation.cs#L30).

**Comment by nphmuller** [comment]
@lbargaoanu Ok, I'll give it a shot later. Will update this comment if I find something.

**Comment by lbargaoanu** [comment]
There might be other ways to make that mapping work besides type converters. ConstructUsing, ProjectUsing, ConstructProjectionUsing.

**Comment by nphmuller** [comment]
Oh sure. The problem is not that I can't get the mapping to work. I just want AssertConfigurationIsValid() to throw if I forgot to configure the mapping properly.

Haven't had the time yet to try custom validation. Will probably try sometime next week.

**Comment by lbargaoanu** [comment]
I know, I was just thinking it through and realizing that it could be tricky for this validation to work in the general case. I believe custom validation is the way to go here.
