### ISSUE TITLE
ProjectTo exception: Argument types do not match

### ISSUE THREAD

**Issue by jamieide** [AutoMapper/AutoMapper#2440]
I have been unable to get ProjectTo working in even simple scenarios in a class library that targets .NET Standard 2.0. I first encountered this issue on a more complex scenario but can repro it on a basic scenario. I tried a few changes without success: remove protected setter, remove aliased property, remove inheritance.

### Source/destination types

```csharp
   // source
    public class CompanyType : Auditable
    {
        public int CompanyTypeId { get; protected set; }

        public string Description { get; set; }

        public string Code { get; set; }

        [Column("PushToMarketPlaceFlag")]
        public bool PushToMarketPlace { get; set; }

        public bool IsActive { get; set; }
    }

   // destination
    public class CompanyType
    {
        public int CompanyTypeId { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        public bool PushToMarketPlace { get; set; }

        public bool IsActive { get; set; }
    }
```

### Mapping configuration

```csharp
            CreateMap<CompanyType, AppModels.Companies.CompanyType>();
```

### Expected behavior
Exception not thrown
I've used ProjectTo extensively in other applications without encountering this error

### Actual behavior

Exception thrown, stack trace attached.
[automapper stack trace.txt](https://github.com/AutoMapper/AutoMapper/files/1514374/automapper.stack.trace.txt)

### Steps to reproduce

```csharp
        public async Task<IEnumerable<AppCompanies.CompanyType>> GetCompanyTypes()
        {
            // works
            return await _companiesDbContext.CompanyType
                .Where(x => x.IsActive)
                .OrderBy(x => x.Description)
                .Select(x => new AppCompanies.CompanyType
                {
                    CompanyTypeId = x.CompanyTypeId,
                    Code = x.Code,
                    Description = x.Description,
                    IsActive = x.IsActive,
                    PushToMarketPlace = x.PushToMarketPlace
                }).ToListAsync();

            // throws System.ArgumentException: Argument types do not match
            //return await _companiesDbContext.CompanyType
            //    .Where(x => x.IsActive)
            //    .OrderBy(x => x.Description)
            //    .ProjectTo<AppCompanies.CompanyType>()
            //    .ToListAsync();
        }

```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by jamieide** [comment]
So far I have been unable to reproduce it outside of the project it's failing in. The only things I have to add are that the exception occurs before a query is issued to the database and this works:

```c#
            var temp =  await _companiesDbContext.CompanyType.ToListAsync();
            return Mapper.Map<IEnumerable<AppCompanies.CompanyType>>(temp);
```

**Comment by TylerCarlson1** [comment]
Looking through code briefly my best guess would be you have a `CreateMap<string,string>()` somewhere and that's what's causing the problem.  Should assigned strings to each other but didn't cause there's a property map for it, and the next option is enumerable mapping which will change `string` into `List<char>` causing the exception.

Possible fix would be to add custom projection for that string to string map if that's the case and it should use that for projection.
