### ISSUE TITLE
ObjectSubstitution Unit Test does not execute CastToEntity method

### ISSUE THREAD

**Issue by bsgiovanini** [AutoMapper/AutoMapper#2441]
when I debug the test as is, it does not run the CastToEntity method

If I change the mapping to:

cfg.CreateMap<Animal, AnimalDto>()
                    .Include<Cat, CatDto>()
                    .Include<Dog, DogDto>();
                cfg.CreateMap<Cat, CatDto>().Substitute(CastToEntity);
                cfg.CreateMap<Dog, DogDto>();

The method runs, however I get a exception:

Message: System.InvalidCastException : Can not convert from type 'AutoMapper.UnitTests.ObjectSubstitution.Cat' to type 'AutoMapper.UnitTests.ObjectSubstitution.AnimalDto'.

Besides, I would like to use Substitute() and AfterMap() methods. Does it work?

**Comment by lbargaoanu** [comment]
What are you trying to achieve?

**Comment by bsgiovanini** [comment]
My problem is related to Nhibernate Proxys that NHibernate only knows the correct type in execution time. 
So, I would like to make use of Substitute() method to substitute  Proxy for the corresponding implementation. Besides, I want to manipulate the mapped object using the AfterMap().  Does it possible?
But, first, as I mentioned before, I could not see the ObjectSubstitution Unit Test from AutoMapper source code run as I was expecting.

**Comment by lbargaoanu** [comment]
Yes, the test is broken, the substitute is not inherited and that's why it's not called. The proxy is the destination of you map or the source?

**Comment by lbargaoanu** [comment]
I'm guessing it's the destination. You have a few options. You can pass an existing object to Map, you can use ConstructUsing, As or Include. As and Include work with inheritance and have overloads that take type objects (no generics).

**Comment by lbargaoanu** [comment]
@jbogard Maybe deprecate this method? There is only one test and that's broken.

**Comment by bsgiovanini** [comment]
Proxy is the source and I need to convert it to its implementation and map to the destination. The problem is I only could substitute the Proxy by its implementation through Substitute() method. Besides I need to transform the destination manipulating some fields via Reflection.

**Comment by lbargaoanu** [comment]
The whole thing sounds complicated. Maybe mapping by hand is easier. Otherwise, I need a simple gist with what you're trying to do.

**Comment by bsgiovanini** [comment]
The second part is working well when I do not have "the proxy problem". Substitute() will resolve my problem if calling Substitute() does not evict the aftermap to work. I attached the test with an AfterMap()  method which I expect to work.
[ObjectSubstitution.txt](https://github.com/AutoMapper/AutoMapper/files/1515170/ObjectSubstitution.txt)

**Comment by lbargaoanu** [comment]
I lost you here. Substitute is not called in that example, so how could it possibly help?

**Comment by bsgiovanini** [comment]
Yes... on mapping

cfg.CreateMap<Animal, AnimalDto>()
                    .Substitute(CastToEntity).AfterMap(TransformDestination)
                    .Include<Cat, CatDto>()
                    .Include<Dog, DogDto>();
                cfg.CreateMap<Cat, CatDto>();
                cfg.CreateMap<Dog, DogDto>();

**Comment by bsgiovanini** [comment]
Sorry.. but there is not solution?

**Comment by lbargaoanu** [comment]
Once I see a repro with what the problem is, we can talk about how it could be solved.

**Comment by bsgiovanini** [comment]
A repro to this problem is to execute the test ObjectSubstitution.txt that I sent you before. If you run the test it fails. 

When I map using the Substitute function on mapping:

cfg.CreateMap<Animal, AnimalDto>()
.Substitute(CastToEntity).AfterMap(TransformDestination)
.Include<Cat, CatDto>()
.Include<Dog, DogDto>();
cfg.CreateMap<Cat, CatDto>();
cfg.CreateMap<Dog, DogDto>();

the function TransformDestination does not execute. If I remove the .Substitute(CastToEntity). it executes.
Is desired that TransformDestination on AfterMap executes anyway.

**Comment by jbogard** [comment]
When I run the test it passes:

#2462

**Comment by lbargaoanu** [comment]
@jbogard Try removing CastToEntity.
