### ISSUE TITLE
Add a netstardard2.0 target

### ISSUE THREAD

**Issue by RichiCoder1** [AutoMapper/AutoMapper#2443]
Howdy! Would be awesome if Ya'll could add a `netstardard2.0` target. Should be equivalent of either the 4.5 target assuming everything is mostly correct.

**Comment by lbargaoanu** [comment]
If we support 1.6, we support 2.0. So why?

**Comment by RichiCoder1** [comment]
Mostly? Considerably less dependencies. W/ netstandard2.0, all AutoMapper needs (after an initial investigation) is 
```xml
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
```

**Comment by lbargaoanu** [comment]
I don't see the advantage. @jbogard might.

**Comment by jbogard** [comment]
Fewer dependencies doesn’t really matter, they’re still there just implied.

What problem are you trying to solve?
