### ISSUE TITLE
Using AutoMapper with Microsoft.AspNet.OData will fail when you try the expand nested objects.

### ISSUE THREAD

**Issue by JohanKlijn** [AutoMapper/AutoMapper#2445]
Using AutoMapper with Microsoft.AspNet.OData will fail when you try the expand nested objects.

I am using Microsoft.AspNet.OData and you AutoMapper to map my Db Entities to Dto's which are returned to the client. When I perform a query in which I expand nested object, an error occurs like: 

"Cannot compare 'member 'Participants' of type 'ODataWebApplication.Entities.Dto.InteractionDto''. Only primitive types, enumeration types and entity types are supported."

The OData query looks like:
http://localhost:59383/odata/ReviewQueues(1)/ReviewQueueItems?$expand=Interaction($expand=Participants)

It only happens when I use Entity Framework for my backend. When I just using in-memory lists every thing is working fine. I suspect AutoMapper is doing something different when you have nested objects.

A full example of this can be found on github: https://github.com/JohanKlijn/ODataWithDto

**Comment by jbogard** [comment]
If you're using OData, you should check out the UseAsDataSource extension:

http://docs.automapper.org/en/stable/Expression-Translation-(UseAsDataSource).html

**Comment by JohanKlijn** [comment]
Hi Jimmy,

I don't understand how UseAsDataSource can help me. Because currently I just map my EF Entities one to one to my DTO objects. And both have exactly the same properties., so no complex mapping at all.

Johan.

**Comment by lbargaoanu** [comment]
Can you make a repro only with ProjectTo?

**Comment by JohanKlijn** [comment]
Hi Lucian,

Unfortunately that's not possible, because it looks like it only happens in combination of OData -> AutoMapper->EF.

The example in my githup repo is as small as possible to reproduce the problem.

**Comment by lbargaoanu** [comment]
Then you're not going to get much help here. You should try StackOverflow too.

**Comment by TylerCarlson1** [comment]
UseAsDataSource helps with handling OData translation of Dto Queries to EF queries.

The exception is your query is against a DTO object and not a Entity object and UseAsDataSource will turn the EF Queryable into a DTO Queryable in which case your expansion case should work.  Although you shouldn't need to expand since it should be mapped over automatically anyways.

Also not sure if expand even works that way, but things like Where and Select clauses will need UseAsDataSource to be translated from Dto to EF to return back.

That's about all I know is it has been tested to be used with OData and works in translating query calls over.

**Comment by JohanKlijn** [comment]
I tried to use UseAsDataSource. When I only retrieve a single entity it's working, but as soon I use an expand an error occurs. 

`
{
    "error": {
        "code": "",
        "message": "An error has occurred.",
        "innererror": {
            "message": "Exception has been thrown by the target of an invocation.",
            "type": "System.Reflection.TargetInvocationException",
            "stacktrace": "   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean& resultsLimited)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at System.Web.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\r\n   at System.Web.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor, ODataQueryContext queryContext)\r\n   at System.Web.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
            "internalexception": {
                "message": "Argument types do not match",
                "type": "System.ArgumentException",
                "stacktrace": "   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)\r\n   at System.Linq.Expressions.MemberAssignment.Update(Expression expression)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)\r\n   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression[T](Expression`1 expression)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 expression)\r\n   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.<>c__23`1.<VisitAllParametersExpression>b__23_9(Expression e, ExpressionVisitor v)\r\n   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitAllParametersExpression[T](Expression`1 expression)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 expression)\r\n   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)\r\n   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)\r\n   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQueryProvider`2.ConvertDestinationExpressionToSourceExpression(Expression expression)\r\n   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)\r\n   at AutoMapper.QueryableExtensions.Impl.SourceSourceInjectedQuery`2.GetEnumerator()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Web.OData.Query.TruncatedCollection`1..ctor(IQueryable`1 source, Int32 pageSize)\r\n   at System.Web.OData.Query.ODataQueryOptions.LimitResults[T](IQueryable`1 queryable, Int32 limit, Boolean& resultsLimited)"
            }
        }
    }
}
`

**Comment by TylerCarlson1** [comment]
I guess UseAsDataSource doesn't support expand then. :(

**Comment by BlaiseD** [comment]
This seems to work:
```csharp
        [ODataRoute("ReviewQueues({id})/ReviewQueueItems")]
        [EnableQuery(PageSize = 50)]
        [HttpGet]
        public IHttpActionResult Get([FromODataUri] long id)
        {
            IQueryable<ReviewQueueItem> reviewQueueItems = _repositoryInMemoryDb.Get().Where(rqi => rqi.ReviewQueueId == id);

            IMapper mapper = DomainEntityToDtoMappingProfile.GetConfiguration().CreateMapper();

            IEnumerable<ReviewQueueItemDto> reviewQueueItemDtos = mapper.Map<IEnumerable<ReviewQueueItem>, IEnumerable<ReviewQueueItemDto>>(reviewQueueItems);
            //IQueryable<ReviewQueueItemDto> reviewQueueItemDtos = reviewQueueItems.ProjectTo<ReviewQueueItemDto>(mapper.ConfigurationProvider);
            
            return Ok(reviewQueueItemDtos);
        }
```

What am I missing?

```
{
	"@odata.context": "http://localhost:59383/odata/$metadata#ReviewQueueItems",
	"value": [
		{
			"ReviewQueueId": 1,
			"InteractionId": 1,
			"Assignee": "51101d5a-3d5e-44d3-bfd1-15aee62f6703",
			"SelectionDate": "0001-01-01T00:00:00-05:00",
			"Interaction": {
				"Id": 1,
				"SourceIdentifier": "abc-1",
				"Title": "abc-1",
				"StartDate": "2017-12-01T14:16:20.0913647-05:00",
				"IngestDate": "2017-12-01T14:16:20.0913647-05:00",
				"Type": "abc-1",
				"RiskScore": 7,
				"Participants": [
					{
						"InteractionID": 1,
						"Value": "Participant1",
						"TypeID": 1
					}
				]
			}
		},
		{
			"ReviewQueueId": 1,
			"InteractionId": 2,
			"Assignee": "ecd9d933-c4fe-4041-af69-155ed44e8e70",
			"SelectionDate": "0001-01-01T00:00:00-05:00",
			"Interaction": {
				"Id": 2,
				"SourceIdentifier": "abc-11",
				"Title": "abc-11",
				"StartDate": "2017-12-01T14:16:20.0923645-05:00",
				"IngestDate": "2017-12-01T14:16:20.0923645-05:00",
				"Type": "abc-11",
				"RiskScore": 7,
				"Participants": [
					{
						"InteractionID": 2,
						"Value": "Participant2",
						"TypeID": 1
					}
				]
			}
		},
		{
			"ReviewQueueId": 1,
			"InteractionId": 3,
			"Assignee": "c76d6271-9ae6-4067-8754-355093aa9ee7",
			"SelectionDate": "0001-01-01T00:00:00-05:00",
			"Interaction": {
				"Id": 3,
				"SourceIdentifier": "abc-11",
				"Title": "abc-11",
				"StartDate": "2017-12-01T14:16:20.0923645-05:00",
				"IngestDate": "2017-12-01T14:16:20.0923645-05:00",
				"Type": "abc-11",
				"RiskScore": 7,
				"Participants": [
					{
						"InteractionID": 3,
						"Value": "Participant1",
						"TypeID": 1
					},
					{
						"InteractionID": 3,
						"Value": "Participant2",
						"TypeID": 1
					}
				]
			}
		}
	]
}
```

**Comment by JohanKlijn** [comment]
Hi @BlaiseD, 

the code you suggest is indeed working, but in that case you miss all the advantages of OData using the IQueryable returned from the Entity Framework. In other words you will send a lot of queries to the database and not sending the OData parameters to you back-end (in this case sql statements).

So this is not an option.

Johan.

**Comment by BlaiseD** [comment]
ok

**Comment by lbargaoanu** [comment]
I think the fix here would be to make UseAsDataSource support expand (as in #1953). PR welcome.
