### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'System.Collections.ObjectModel.Collection`1[T]' to type 'System.Collections.Generic.List`1[T]'.

### ISSUE THREAD

**Issue by niemyjski** [AutoMapper/AutoMapper#2449]
I think this may be broken in latest version using dynamic mapping on .net core (Getting unable to map from `ICollection<T>` instantiated with instance of `System.Collections.ObjectModel.Collection<T>` to `ICollection<T>`

```
InvalidCastException: Unable to cast object of type 'System.Collections.ObjectModel.Collection`1[T]' to type 'System.Collections.Generic.List`1[T]'.
```

**Comment by lbargaoanu** [comment]
The same as #2447. Set UseDestinationValue.
