### ISSUE TITLE
Automapping generic lists in 6.2.1 unmapped property Capacity

### ISSUE THREAD

**Issue by mikedunham** [AutoMapper/AutoMapper#2454]
I cannot seem to figure out where the Capacity property is coming from. I cannot ignore it via ForMember because it does not exist on the object. In previous versions of AutoMapper, I would create an IList<destination T>, IList<source T> mapping and that was all that was needed.

### Source/destination types

Source types:

    public class BranchOutputData
    {
        public List<Branch> Branches { get; set; }
    }

    public class Branch
    {
        public int BranchId { get; set; }

        public string BranchCode { get; set; }

        public bool IsListVisible { get; set; }
    }

Destinations types:

 [DataContract(Name = "GetBranchListResponse")]
    public class GetBranchListResponseDataContract
    {
        [DataMember]
        public List<BranchDataContract> Branches { get; set; }
    }

    [DataContract(Name = "Branch")]
    public class BranchDataContract
    {
        [DataMember]
        public int BranchId { get; set; }

        [DataMember]
        public string BranchCode { get; set; }

    }

### Mapping configuration

Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<GetBranchListRequestDataContract, BranchInputData>();
                cfg.CreateMap<BranchOutputData, GetBranchListResponseDataContract>();
            });

### Version: x.y.z
 
6.2.1
### Expected behavior

Map the lists

### Actual behavior

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=============================================================================================================================================================================================================================
BranchOutputData -> List`1 (Destination member list)
Domain.Lookup.Entities.BranchOutputData -> System.Collections.Generic.List`1[[IServices.Data.DataContracts.LookupService.BranchDataContract, Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] (Destination member list)

Unmapped properties:
Capacity

### Steps to reproduce
//data access via dapper
var branches = _getBranchListTransactionScript.PerformTransaction(Mapper.Map<BranchInputData>(request));
                return new GetBranchListResponseDataContract { Branches = Mapper.Map<List<BranchDataContract>>(branches) };

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
