### ISSUE TITLE
With VS15.50 release, Automapper is not working

### ISSUE THREAD

**Issue by topfunet** [AutoMapper/AutoMapper#2455]
A few days ago, I posted a issue about Xamarin.iOS and Automapper.
Now with vs15.5.0 release, Xamarin.Forms project template use .net standard and PackageReference, if I add Automapper nuget package to shared project, Xamarin.iOS project won't build.

**Comment by pleb** [comment]
The exact error is 

    Error CS1703

    Multiple assemblies with equivalent identity have been imported: 
	'C:\Users\plebm\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll' 
	and 
	'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Reflection.Emit.dll'.
    Remove one of the duplicate references.

I don't think this is an Automapper error. However, I'm not certain and I'm not sure how to investigate it further. Does anybody have any advice?

-----
To reproduce, using VS 15.5.1

1. Create Xamarin Cross-Plat App (Xam.Forms)
2. Select iOS and .net standard from the create options
3. Add Automapper (6.2.2) to the .net standard project
4. Build the iOS project -> Error

**Comment by pleb** [comment]
Version | Result
-------- | -------
6.2.2 | ❌ 
6.2.1 | ❌ 
6.2.0 | ❌
6.1.1 | ✔️
5.2.0 | ✔️ 

My guess is the addition of the `System.Runtime.Serialization.Primitives.4.3.0` dependency in 6.2.0 is the cause.

Although, again, I'm still not sure if it's a Xamarin or AutoMapper issue

**Comment by lbargaoanu** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=57849?

**Comment by pleb** [comment]
@lbargaoanu I did see that bug report. I don't think these are related because a) it's been fixed and b) it's for Android (not iOS)

**Comment by lbargaoanu** [comment]
Are you sure the version you're using includes that fix? Anyway, I think you should ask this in an Xamarin forum. Maybe it's us, maybe it's them :)

**Comment by pleb** [comment]
I'm thinking them. Simply, because a dependency shouldn't break the build the way it does. It seems very similar to the bugzilla bug, but for the iOS project. I'll open a ticket

**Comment by lbargaoanu** [comment]
Thanks. And please let us know :)

**Comment by pleb** [comment]
Xamarin forms ticket for reference https://github.com/xamarin/Xamarin.Forms/issues/1380

**Comment by pleb** [comment]
@lbargaoanu The Xamarin team have marked the ticket I submitted as invalid. But, I feel they may have jumped the gun. They're claiming the error is because Automapper is probably calling Reflection.Emit, which I have my doubts because of the trouble it cases in non-trusted environments etc. Additionally, even if Automapper does, I would expect a runtime error and not a build error.

**Comment by lbargaoanu** [comment]
As @jbogard commented over there, it should work at build time.

**Comment by jbogard** [comment]
I'm going to try and reproduce this with a small project to see what references are causing it to fail. Still shouldn't fail at build time.

**Comment by pleb** [comment]
@jbogard I've created a bare minimum solution that on build produces this bug

https://github.com/pleb/XamAutoMapperBugExample

**Comment by jbogard** [comment]
I was able to reproduce with an even smaller example, without AutoMapper:

ClassLibrary.sln:
 - ClassLibrary.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
  </ItemGroup>

</Project>
```

Push that out as a nuget package using `dotnet pack`

Then in a second solution as you have it, just reference the library as a NuGet package and you get:

```
error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\JimmyBogard\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll' and 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Reflection.Emit.dll'. Remove one of the duplicate references.
```

**Comment by topfunet** [comment]
Any good news?

**Comment by pleb** [comment]
I've requested a re-review of the Xam.Forms GH issue. Hopefully, they respond nd not ignore it, like they did my other comment/question for them
