### ISSUE TITLE
Self-maps are broken with auto-configured map?

### ISSUE THREAD

**Issue by szalapski** [AutoMapper/AutoMapper#2456]
### Source/destination types
any

### Mapping configuration
none

### Version: x.y.z
6.2.2 and 6.2.0

### Expected behavior
Using the auto-map configuration, mapping a type to itself should work to do a copy of all the values/properties.  The test below should pass.

### Actual behavior

The copy does nothing, apparently. The test below is failing for me.

### Steps to reproduce
```csharp
        public class MyType
        {
            public int Baz { get; set; }
        }
       
        [TestMethod]
        public void AutoMapperSelfTest()
        {
            var foo = new MyType() { Baz = 5 };
            var bar = new MyType() { Baz = 11 };
            Mapper.Map(foo, bar);
            Assert.AreEqual(5, bar.Baz);
        }
```

**Comment by jbogard** [comment]
This is because AutoMapper is not a cloning library, so it does not assume this is what you are trying to do. If you want to clone or self map you have to explicitly tell AutoMapper through CreateMap.

**Comment by szalapski** [comment]
Wait, so mapping with identical types Foo and Bar works great, but mapping something even simpler and also identical doesn't work?  Please reconsider.  Cloning is a subset of Mapping.

**Comment by jbogard** [comment]
No it’s not. There are better cloning libraries out there like
BinaryFormatter. I really, really don’t want to support cloning scenarios
which get far more complicated than mapping.

**Comment by szalapski** [comment]
Could you support the exact behavior that it would do if it were mapping?

**Comment by jbogard** [comment]
Yes we already do. Either call CreateMap, or remove the AssignableMapper
from the list of mappers. The latter may have unintended side effects since
that would make every type get mapped like string -> string.
