### ISSUE TITLE
How I can use dynamic mapper for version 6.2.2

### ISSUE THREAD

**Issue by haisaco** [AutoMapper/AutoMapper#2458]
Before Automapper version 4.1.1
and Automapper.Data version 1.0.0-beta
I can use Dynamic mapper like this
`using (var reader = command.ExecuteReader())
                {
                    MapperRegistry.Mappers.Add(new DataReaderMapper());
                    Mapper.CreateMap<IDataReader, T>();
                    ret = Mapper.Map<IDataReader, List<T>>(reader);
                    connection.Close();
                }`
But now, Automapper version 6.2.2 and Automapper version 1.0.0
I can't use that
So, how I can use auomapper for this version
Thanks

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Data

**Comment by haisaco** [comment]
why you close when it not working?
`Mapper.Initialize(cfg =>
                    {
                        cfg.Mappers.Add(new DataReaderMapper());
                        cfg.AddDataReaderMapping();
                        cfg.CreateMap<IDataReader, T>();
                    });
                    ret = Mapper.Map<IDataReader, List<T>>(reader);`

**Comment by jbogard** [comment]
That’s not what the wiki says to do. If you do what the wiki says and it’s
still not working you need to provide some way to reproduce.
