### ISSUE TITLE
Suggestion to improve use of mappings 

### ISSUE THREAD

**Issue by widec** [AutoMapper/AutoMapper#2460]
When setting duplicate mappings an exeption should be thrown since only one has influence on the mapping. This would prevent searching for errors in large files.

this.SetMapping<TX, TY>(). ....
....
....
this.SetMapping<TX, TY>(). ...

**Comment by lbargaoanu** [comment]
I presume you're on an older version. This throws now. And it can be [configured](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=AllowAdditiveTypeMapCreation&type=).
