### ISSUE TITLE
Question: config for auto map exact property names and types only?

### ISSUE THREAD

**Issue by wgross** [AutoMapper/AutoMapper#2463]
I would like to create an auto mapper which auto-maps only if the property names and types are exactly the same and therefore considers differences as 'invalid' which have to be mapped explicitly.

I've fiddled around a bit in LinqPad and came out with this Mapper profile:

```csharp
public class ExactNamesMapperProfile : Profile
{
	public ExactNamesMapperProfile()
	{
		this.DefaultMemberConfig.MemberMappers.Clear();
		this.DefaultMemberConfig.NameMapper.NamedMappers.Clear();

		this.AddMemberConfiguration().AddName<CaseSensitiveName>();
		
		this.CreateMap<Source, Destination>();
	}
}
```

This seems to work fine with identical names but i would like to extend this to identical types as well. This mapper for example would still map a double source property to an int destination property with the same name.

Is this possible?

**Comment by lbargaoanu** [comment]
You can go through the list of mappers and remove those you don't want, but at this point it seems easier to write some custom code that does what you want.
