### ISSUE TITLE
Question: Upgrade to .netstandard 2.0

### ISSUE THREAD

**Issue by codeplay87** [AutoMapper/AutoMapper#2464]
Wondering if there was any information if the repo would be upgraded to .netstandard 2.0 so it can be used with .net 4.7.1 projects.

**Comment by lbargaoanu** [comment]
We support 1.3 so we support 2.0. You should be able to use it.

**Comment by codeplay87** [comment]
ok great thanks. apologies getting my head around standard library and compatability
