### ISSUE TITLE
CustomResover instances issue

### ISSUE THREAD

**Issue by costa100** [AutoMapper/AutoMapper#2465]
Hi:

I have the following little program:

```
  class Program
  {


    public class SourceDto
    {
      public int Id { get; set; }
      public string Value1 { get; set; }
      public string Value2 { get; set; }
    }

    public class SourceOverrideDto: SourceDto
    {
      public string Value1Override { get; set; }
      public string Value2Override { get; set; }
    }

    public class DestinationDto
    {
      public int Ident { get; set; }
      public string Value1 { get; set; }
      public string Value2 { get; set; }
    }

    public class CustomResolver : IMemberValueResolver<object, object, string, string>
    {
      public string Resolve(object src, object dest, string source, string member, ResolutionContext context)
      {
        return member != source ? source: null;
      }
    }

    static void Main(string[] args)    
    {
      SourceOverrideDto overrideDto = new SourceOverrideDto
      {
        Id = 1,
        Value1 = "200",
        Value2 = "400",
        Value1Override = "200",
        Value2Override = "400"
      };

      DestinationDto destinationDto = new DestinationDto
      {
        Ident = 3,
        Value1 = "200",
        Value2 = "500"
      };

     
      IMapper mapper = Cfg.CreateMapper();

      mapper.Map(overrideDto, destinationDto);

      Console.WriteLine("Value1={0}, Value2={1}", destinationDto.Value1, destinationDto.Value2);
      Console.ReadKey();

    }


    private static MapperConfiguration Cfg { get; } = new MapperConfiguration(cfg =>
    {

      cfg.CreateMap<SourceOverrideDto, DestinationDto>()
        .ForMember(dest => dest.Ident, opt => opt.MapFrom(x => x.Id))
        .ForMember(dest => dest.Value1, opt => opt.ResolveUsing<CustomResolver, string>(src => src.Value1Override))
        .ForMember(dest => dest.Value2, opt => opt.ResolveUsing<CustomResolver, string>(src => src.Value2Override))
        ;
    });
  }
```
The example is contrived, but just to give you a background on what I am doing, the idea behind this mapping is to detect differences between the source and destination values and store null in the destination if the value didn't change. I actually have one more class which is not present in this code which stores values updated by one group of users. Then the second group of users can override these values and the app saves the overrides, however, if a value doesn't change, I store null in the Destination object.

The program prints:
`Value1=, Value2=`

I expected to print:
`Value1=, Value2=400`

The problem seems to be in the instantiation of the CustomResolver class.

It is possible that I am missing something here and I am not sure it is a bug.

I tested it with version 5.2.0, .Net 4.5.

Any ideas?

Thanks

Update: It seems that I made a mistake. I updated the program and it works as expected. My real world program doesn't work though and I haven't been able to reproduce the issue outside the project.

**Comment by irowbin** [comment]
@costa100 Does the above example works with the generic too?  Mine isn't working with generic.
Works well with a single instance from the example above.

@jbogard  
```c#
// working
 mapper.Map<overrideDto, destinationDto>(sourceDto);

// not working
 mapper.Map<List<overrideDto>, List<destinationDto>>(sourceDto);
```
Thanks.

**Comment by costa100** [comment]
@irowbin I haven't tried it for generics. My real world test case fails, while this program works. This is one of the weirdest issues I've had, and I still didn't solve it. I cannot reproduce it outside my project. I was wondering if there are any exceptions thrown inside the library code and silently absorbed which might affect the normal behavior of the mappings. I am going to take a look tomorrow at the automapper source code.
