### ISSUE TITLE
Validation fails on unmapped members with protected setters

### ISSUE THREAD

**Issue by tl24** [AutoMapper/AutoMapper#2474]
### Source/destination types

```csharp
   // source
    public abstract class ScheduledTask : EntityBase
    {
          /// other members omitted
    }
   // destination
    public abstract class ScheduledTask : Projection
    {
        protected ScheduledTask()
        {
            IsReadonly = true;
            CanCompleteManually = false;
        }        
        public bool CanCompleteManually { get; protected set; }
        public bool IsReadonly { get; protected set; }
        public int TaskType { get; set; }
        public int GroupNumber { get; set; }
        public string Group { get; set; }
          /// other members omitted
    }

```

### Mapping configuration

```csharp
            CreateMap<Models.ScheduledTask, Projections.ScheduledTask>()
                .ForMember(d => d.TaskType, cfg => cfg.Ignore())
                .ForMember(d => d.Group, cfg => cfg.Ignore())
                .ForMember(d => d.GroupNumber, cfg => cfg.Ignore());
```

### Expected behavior
This should validate cleanly.  I shouldn't have to specify mappings for protected/private setters

### Actual behavior
Error occurred:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
====================================================================
ScheduledTask -> ScheduledTask (Destination member list)
Models.ScheduledTask -> Projections.ScheduledTask (Destination member list)

Unmapped properties:
CanCompleteManually
IsReadonly

### Steps to reproduce
1. Initialize a profile with the mappings above
2. Call AssertConfigurationIsValid on the profile

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=IgnoreAllPropertiesWithAnInaccessibleSetter&type=
