### ISSUE TITLE
Include<,> and IncludeBase<,> is not creating equal TypeMap.IncludedBaseTypes

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper#2475]
This is a cross post of https://github.com/AutoMapper/AutoMapper.Collection/pull/73 where runnable code + test exists for AutoMapper 6.2.1.

Adding mapping with `.Include<,>()` from base type
```
cfg.CreateMap<OrderDomain, OrderEf>()
    .EqualityComparison((oo, dto) => BaseEquals(oo, dto))
    .Include<MailOrderDomain, MailOrderEf>()
    .Include<OnlineOrderDomain, OnlineOrderEf>()
    ;

cfg.CreateMap<OnlineOrderDomain, OnlineOrderEf>()
    .EqualityComparison((ood, ooe) => DerivedEquals(ood, ooe))
    ;

cfg.CreateMap<MailOrderDomain, MailOrderEf>()
    ;
```

or with `.IncludeBase<,>()` from derived typ
```
cfg.CreateMap<OrderDomain, OrderEf>()
    .EqualityComparison((oo, dto) => BaseEquals(oo, dto))
    ;

cfg.CreateMap<OnlineOrderDomain, OnlineOrderEf>()
    .EqualityComparison((ood, ooe) => DerivedEquals(ood, ooe))
    .IncludeBase<OrderDomain, OrderEf>()
    ;

cfg.CreateMap<MailOrderDomain, MailOrderEf>()
    .IncludeBase<OrderDomain, OrderEf>()
    ;
```
the generated `TypeMap` is different. 

The `typeMap.IncludeDerivedTypes` is working correctly in both case with this test
```
public void TypeMap_Should_include_derivied_types()
{
    var mapper = CreateMapper();
    var typeMap = mapper.ConfigurationProvider.ResolveTypeMap(typeof(OrderDomain), typeof(OrderEf));

    var typePairs = new[]{
            new TypePair(typeof(OnlineOrderDomain), typeof(OnlineOrderEf)),
            new TypePair(typeof(MailOrderDomain), typeof(MailOrderEf))
    };
    typeMap.IncludedDerivedTypes.ShouldBeEquivalentTo(typePairs);
}
```
The `typeMap.IncludedBaseTypes` is only working correctly if the mapping is on the derived
```
public void TypeMap_Should_include_base_types()
{
    var mapper = CreateMapper();
    var typeMap = mapper.ConfigurationProvider.ResolveTypeMap(typeof(MailOrderDomain), typeof(OrderEf));

    var typePairs = new[]{
            new TypePair(typeof(OrderDomain), typeof(OrderEf))
    };
    typeMap.IncludedBaseTypes.ShouldBeEquivalentTo(typePairs);
}
```

Is this an expected behaviour or missing line in https://github.com/AutoMapper/AutoMapper/blob/877d917a2d2a20e8b6ab49d7436747a75a67e7b4/src/AutoMapper/ProfileMap.cs#L253

**Comment by lbargaoanu** [comment]
What TypeMap does is really an internal concern. Do you have a failing test using the API?

**Comment by Tasteful** [comment]
@lbargaoanu You have all the classes from the failing test in the linked PR from AutoMapper.Collection, the testitself is in the description.

Should the `TypeMap.IncludedBaseTypes` be the same either the base mapping is configured on the derivied type with `IncludeBase<>` or from the base with the `Include<>`?

If we look at ttps://github.com/AutoMapper/AutoMapper/blob/877d917a2d2a20e8b6ab49d7436747a75a67e7b4/src/AutoMapper/ProfileMap.cs 

Method `ApplyBaseMaps` we can see the excplicit call to `baseMap.IncludeDerivedTypes(currentMap.SourceType, currentMap.DestinationType);` 

Method `ApplyDerivedMaps` we are missing this explicit call.

**Comment by lbargaoanu** [comment]
You're missing my point. If the public API works as expected, why would any of that matter?

**Comment by Tasteful** [comment]
With AutoMapper.Collection we are finding the correct type to map between and when the configuration is using the `Include<>` the base types are not included in the `TypeMap.IncludedBaseTypes` which make the `EqualityComparison` from AutoMapper.Collection to fail.

If the expected behaviour is that it not should be included there we need to try to find another way to find the base mappings in AutoMapper.Collection. 

If the expected behaviour is that it should be included then that issue need to be solved before the AutoMapper.Collection issue can be solved.

**Comment by lbargaoanu** [comment]
The way I see it, TypeMap is an internal thing and AM.Collection should live with any behavior that works for us. Unless @jbogard wants to make this part of some advanced API and then we could have special tests for it.

**Comment by lbargaoanu** [comment]
AM.Collection doesn't use IncludedBaseTypes. So there's no issue here. @jbogard will decide about the PR.

**Comment by Tasteful** [comment]
@lbargaoanu I don't think you check the latest code because it is used here https://github.com/AutoMapper/AutoMapper.Collection/blob/75536f9401569af8df1edf7eac48d98b8dddb014/src/AutoMapper.Collection/EquivalencyExpression/EquivalentExpressions.cs#L63 to solve one mapping issue but is only solving half of the issue.

**Comment by lbargaoanu** [comment]
I was checking master, that's in development. OK.

**Comment by rizi** [comment]
@lbargaoanu when typemap is an internal type and not part of the "public API" then why it's a public type and not an internal type? Br

**Comment by jbogard** [comment]
It’s internal in that it’s an intermediary to creating a mapping plan. More of an implementation detail than anything else.

Different mapping strategies look at different parts to figure out the mapping plan. Check out how Include and IncludeBase actually sets up the TypeMaps and how they are used. TypeMaps are generally a collection of how you’ve set things up in the configuration API, then interpreted as a whole (all type maps) to determine how to actually map. Not one type map in isolation.
