### ISSUE TITLE
Can the wiki be deleted so it stops polluting google search results?

### ISSUE THREAD

**Issue by SimonCropp** [AutoMapper/AutoMapper#2480]

**Comment by jbogard** [comment]
Ah yeah. We can’t do redirects but I guess we’ll just have to delete them.

**Comment by SimonCropp** [comment]
yeah been through this scenario a few times. and the sooner they are deleted the sooner search engines and downstreams can detect 404 and fix links.

**Comment by jbogard** [comment]
Removed wiki.

**Comment by SimonCropp** [comment]
@jbogard awesome. thanks
