### ISSUE TITLE
 Type is not derived from error with IncludeBase

### ISSUE THREAD

**Issue by fabich** [AutoMapper/AutoMapper#2481]
Hi
After upgrading AutoMapper from 6.1.1 to 6.2.x we are getting an error when using IncludeBase<>.

We went through the change log and found some changes for IncludeBase<> but we don't understand why/how these changes are affecting our code.

### Source/destination types

```csharp
public class TblAllocationruleactypes : IElementWithVersionedReference<TblAllocationrules>
    {
    }
public interface IElementWithVersionedReference<T> where T : class, IVersionedDbEntity
    {
    }
```

### Mapping configuration

```csharp
CreateMap<TblAllocationruleactypes, TblAllocationruleactypes>()
                .IncludeBase<IElementWithVersionedReference<IVersionedDbEntity>, IElementWithVersionedReference<IVersionedDbEntity>>();
```

### Version: x.y.z
6.1.1 to 6.2.0 / 6.2.2

### Expected behavior

Same as in 6.1.1

### Actual behavior

VS throws exception:
System.ArgumentOutOfRangeException:
TblAllocationruleactypes is not derived from IElementWithVersionedReference`1[IVersionedDbEntity].'

**Comment by lbargaoanu** [comment]
Try ```IElementWithVersionedReference<TblAllocationrules>``` instead.

**Comment by fabich** [comment]
Dear @lbargaoanu, thank you for your reply.

We are aware of this solution and it works as well.
However, using the specific entity instead of IVersionedDbEntity would generate new mappings for each versioned DB entity and would generate a lot of new and redundant mappings.
This change would result in approx. 100 more mappings.
This is exactly the reason why we are using IVersionedDbEntity.

Any other ideas?
Thanks

**Comment by lbargaoanu** [comment]
Try ```public interface IElementWithVersionedReference<out T> where T : class, IVersionedDbEntity```.

**Comment by fabich** [comment]
This doesn't work either.
I'm working on an example so you can test it.

**Comment by fabich** [comment]
Please find an example below:
https://gist.github.com/fabich/852e8970644c2fc1cde5d1385a3eb2bf

**Comment by lbargaoanu** [comment]
Try ```T FkVersionNavigation { get; }``` in IElementWithVersionedReference.

**Comment by fabich** [comment]
That won't work.
FkVersionNavigation is not always read only

**Comment by lbargaoanu** [comment]
It has to be readonly only in the interface.

**Comment by fabich** [comment]
As I was saying before. This won't work.
Or not without major changes to the generic versioning classes.

My question is: What did changed around IncludeBase from 6.1.1 to 6.2.0?
And why does the existing code no longer compile?

**Comment by lbargaoanu** [comment]
The problem is that ```IElementWithVersionedReference<IVersionedDbEntity>``` is not a base class of TblAllocationruleactypes :) I tried to show you ways you could make it work, but other than that, I don't see a problem with AM here.

**Comment by lbargaoanu** [comment]
Another idea is to use open generic maps. Then that check does not apply.

**Comment by jbogard** [comment]
What changed? This: #2192 and this: #2333

We started validating that when you do base type maps that the base type maps are actually base types. That seems logical.
