### ISSUE TITLE
Issue after upgrading to 6.1.1 (or above) from 6.0.0

### ISSUE THREAD

**Issue by lokirangers** [AutoMapper/AutoMapper#2482]
### Source/destination types

```csharp
// Put your source/destination types here

 public class VehicleDriverModel
    {
        [Required]
        public int DriverID { get; set; }

        public string Name { get; set; } // Name (length: 50)

        public int? ShiftPatternID { get; set; }
        public string ShiftPattern_Description { get; set; } // Name (length: 50)

    }

 public partial class ResourceAllocation: Entity
    {
        [Required]
        [Key]
        public int ResourceAllocationID { get; set; } // ResourceAllocationID (Primary key)

        public int? VehicleID { get; set; } // VehicleID

        public int? DriverID { get; set; } // DriverID

        public int? VehicleUnavailableID { get; set; } // VehicleUnavailableID

        public int? DriverUnavailableID { get; set; } // DriverUnavailableID

        public int? ReplacementDriverID { get; set; } // ReplacementDriverID

        public int? OverLapsWithID { get; set; } // OverLapsWithID

        public System.DateTime? StartDate { get; set; } // StartDate

        public System.DateTime? EndDate { get; set; } // EndDate

        public System.DateTime? OrigStartDate { get; set; } // OrigStartDate

        public System.DateTime? OrigEndDate { get; set; } // OrigEndDate

        public bool? ManualAllocation { get; set; } // ManualAllocation

        [Required]
        public bool Deleted { get; set; } // Deleted

        [Required]
        public System.DateTime CreatedDate { get; set; } // CreatedDate

        [Required]
        public System.DateTime UpdatedDate { get; set; } // UpdatedDate

        [Required]
        public int UserIDLastUpdate { get; set; } // UserIDLastUpdate

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<OverAllocation> Child { get; set; } // OverAllocation.FK_ChildResourceAllocation_OverAllocation
        public virtual System.Collections.Generic.ICollection<OverAllocation> Parent { get; set; } // OverAllocation.FK_ParentResourceAllocation_OverAllocation
        public virtual System.Collections.Generic.ICollection<ResourceAllocation> ResourceAllocations { get; set; } // ResourceAllocation.FK_ResourceAllocation_OverLapsWith

        // Foreign keys
        public virtual Driver AllocatedDriver { get; set; } // FK_Driver_ResourceAllocation
        public virtual Driver ReplacementDriver { get; set; } // FK_ReplacementDriver_ResourceAllocation
        public virtual DriverUnavailable DriverUnavailable { get; set; } // FK_DriverUnavailable_ResourceAllocation
        public virtual ResourceAllocation OverLapsWith { get; set; } // FK_ResourceAllocation_OverLapsWith
        public virtual Vehicle Vehicle { get; set; } // FK_Vehicle_ResourceAllocation
        public virtual VehicleUnavailable VehicleUnavailable { get; set; } // FK_VehicleUnavailable_ResourceAllocation

        public ResourceAllocation()
        {
            Child = new System.Collections.Generic.List<OverAllocation>();
            Parent = new System.Collections.Generic.List<OverAllocation>();
            ResourceAllocations = new System.Collections.Generic.List<ResourceAllocation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }
```

The entity AllocatedDriver is derived using the foreign key on the DriverID column.  We are using the EF Reverse POCO generator, and the URF framework.

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
 public class VehicleDriverMappingProfile : Profile
    {


        public VehicleDriverMappingProfile()
        {

            CreateMap<ResourceAllocation, VehicleDriverModel>()
                .ForMember(t => t.Name, opt => opt.MapFrom(s => s.AllocatedDriver.Name))
                .ForMember(t => t.ShiftPattern_Description, opt => opt.MapFrom(s => s.AllocatedDriver.ShiftPattern.Description))
                .ForMember(t => t.ShiftPatternID, opt => opt.MapFrom(s => s.AllocatedDriver.ShiftPatternID))
                .ReverseMap();

            CreateMap<IEnumerable<VehicleDriverModel>, List<ResourceAllocation>>().ConvertUsing<VehicleDriverListConverter>();
        }
    }

    public class VehicleDriverListConverter : ITypeConverter<IEnumerable<VehicleDriverModel>, List<ResourceAllocation>>
    {
        private IResourceAllocationService _service;
        private IMapper _mapper;
        private ISessionInfo _sessinfo;
        private IDataContextAsync _context;
        public VehicleDriverListConverter(IResourceAllocationService service, IMapper mapper, ISessionInfo sessinfo, IDataContextAsync context)
        {
            _service = service;
            _mapper = mapper;
            _sessinfo = sessinfo;
            _context = context;
        }

        public List<ResourceAllocation> Convert(IEnumerable<VehicleDriverModel> source, List<ResourceAllocation> destination, ResolutionContext context)
        {
            List<ResourceAllocation> _list = new List<ResourceAllocation>();
            var _dellist = new List<ResourceAllocation>();

            Vehicle _vehicle = context.Items["vehicle"] as Vehicle;

            if (destination != null)
                _list = destination;

            foreach (var _iterdest in _list)
            {
                var _dest = _iterdest;
                VehicleDriverModel _source = null;
                if (source != null)
                    _source = source.Where(x => x.DriverID == _dest.DriverID).FirstOrDefault();

                if (_source == null)
                {
                    _service.Delete(_dest);
                    _dellist.Add(_dest);
                }
                else
                {
                    // nothing to do, already in the list
                }
            }
            if (source != null)
            {
                foreach (var _itersource in source)
                {
                    var _source = _itersource;
                    var _dest = _list.Where(x => x.DriverID == _source.DriverID).FirstOrDefault();
                    if (_dest == null)
                    {
                        _dest = _mapper.Map<ResourceAllocation>(_source);
                        _dest.Vehicle = _vehicle;
                        _dest.VehicleID = _vehicle.VehicleID;
                        _vehicle.ResourceAllocations.Add(_dest);
                        _service.Insert(_dest);
                        _list.Add(_dest);
                    }
                }
            }
            foreach (var _iterdel in _dellist)
            {
                var _del = _iterdel;
                _list.Remove(_del);
            }
            return _list;
        }
    }

```

### Version: x.y.z
 
6.1.1

### Expected behavior

In the line _dest = _mapper.Map<ResourceAllocation>(_source); it mapped the _dest.AllocatedDriver property as null in v6.0.0.

I'm not actually sure why it maps as null, as when mapping other entities with foreign key entities, where we have queried the entity concerned during the validation phase, using the same data context, those entities map as the correctly queried entity from the database, with the object state set to 'Unchanged'.  However, null causes no problems as the DriverID remains set on the mapped entity and EF uses this when performing the insert operation.

### Actual behavior

It mapped the _dest.AllocatedDriver property as a new Driver entity (with ID of 0), because of this EF resets the DriverID to 0 when inserting the DB record and I get a foreign key constraint error.

I'd either like it to map as null, as before, or to understand why this particular EF foreign key relationship might be mapping as null / new whereas my other ones map as the entity queried from the DB,

I tried using .UseDestinationValue() and also .MapFrom<Driver>(null) in the reverse map and both of these were ignored, still resulting in a fresh Driver entity being created in the AllocatedDriver property.

### Steps to reproduce

As this is from our full production app with database etc... this is likely to prove difficult in the extreme to create a suitable reproduction project, so I'm hoping you may have come across issues like this before and have some pointers as to where I'm going wrong.

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
See #2220 and related issues, here and on SO.

**Comment by lokirangers** [comment]
Hi, I've tried the following, after upgrading to 6.2.2 to make sure I'm on the latest:

 CreateMap<ResourceAllocation, VehicleDriverModel>()
                .ForMember(t => t.Name, opt => opt.MapFrom(s => s.AllocatedDriver.Name))
                .ForMember(t => t.ShiftPattern_Description, opt => opt.MapFrom(s => s.AllocatedDriver.ShiftPattern.Description))
                .ForMember(t => t.ShiftPatternID, opt => opt.MapFrom(s => s.AllocatedDriver.ShiftPatternID))
                .ReverseMap()
                .ForPath(t => t.AllocatedDriver, opt => opt.Ignore());

it made no difference, my EF entity of type ResourceAllocation was still created with a populated AllocatedDriver property set to a new instance of EF Entity type Driver.  If I add the line .ForPath(t => t.AllocatedDriver.DriverID, opt => opt.MapFrom(s => s.DriverID)) I can get it to map the DriverID over but I then get an EF error complaining about 2 driver instances with the same ID.  I have also tried getting it to Ignore the Paths t.AllocatedDriver.DriverID and t.AllocatedDriver.Name, with no success

In most of my mappings going from MVC controller models to Entity DTO's it maps the foreign key entity correctly to the existing entry from the db (which was queried using the data context when validating the model using FluentValidation), or if the foreign key entity was not queried (by skipping under debug) it maps it as null, which again is fine.

It's only this mapping that used to map the foreign key entity across as null regardless of the fact that the Driver entity concerned had been queried from the database, and which now maps it across as a new Driver entity, no matter what I do.

I don't understand how my other mappings are correctly pulling out the queried foreign key entities from the data context and using them but this specific one never does?  If there is something I have defined incorrectly in terms of how automapper knows to map related EF entities on the basis of their foreign key relationships I can fix it, but my EF model is working perfectly fine other than this.

Any pointers you can give would be greatly appreciated.

**Comment by lbargaoanu** [comment]
Remove the ReverseMap, just create the needed maps. If that works, you can either keep it, or return to ReverseMap and find the right ignore.

**Comment by lokirangers** [comment]
But the map IS needed, it's the reverse map that I'm using in the code above.  The map itself is from our database/EF entity to the model used in our REST api, and the reverse map is from the REST api back to our database/EF entity.

If I remove the reverse map it throws an exception:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type.

It then goes on to list what appears to be every property in the ResourceAllocation entity, which is what I would expect, as I've just removed the line telling it to create a reverse map from VehicleDriverModel to ResourceAllocation, which is what I'm actually attempting to do?

This code worked fine in v6.0.0, although as I've mentioned above, I'm not sure why this particular map was assigning a null value for this property when mapping rather than mapping it correctly to the EF entity concerned, as my other maps do with other similar one to one foreign key properties.

**Comment by lbargaoanu** [comment]
Replace ReverseMap with two CreateMaps, one from source to destination and one from destination to source.

**Comment by lokirangers** [comment]
Ok, I've tried that, and it has worked.  Would it be possible for you to explain why this would have worked?  I have a lot of maps from EF entity to REST model with .ReverseMap() method and then additional mapping entries for the reverse map operation.  I'd like to understand what the difference is between creating a new specific reverse map and using the .ReverseMap() method, before I potentially go and modify them all to have specific reverse maps using CreateMap.

Thanks.

**Comment by lbargaoanu** [comment]
The docs are [here](http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html) and I've already linked to the relevant issues. But this is really an SO kind of question.

**Comment by lokirangers** [comment]
Thank you, after reading the unflattening section I understand now.  Given that we were already using the product and it was working I did not re-read the entire documentation set, just the upgrade guide, which did not mention that this was a breaking change that required code changes to preserve previous functionality.
