### ISSUE TITLE
MergeInto

### ISSUE THREAD

**Issue by SimonCropp** [AutoMapper/AutoMapper#2483]
I find myself regularly using these helper methods

```
        public static TResult MergeInto<TResult>(this IMapper mapper, object item1, object item2)
        {
            var firstMap = mapper.Map<TResult>(item1);
            return mapper.Map(item2, firstMap);
        }

        public static TResult MergeInto<TResult>(object item1, object item2)
        {
            return MergeInto<TResult>(Mapper.Instance, item1, item2);
        }

        public static TResult MergeInto<TResult>(this IMapper mapper, params object[] objects)
        {
            var result = mapper.Map<TResult>(objects.First());
            return objects.Skip(1).Aggregate(result, (r, obj) => mapper.Map(obj, r));
        }

        public static TResult MergeInto<TResult>(params object[] objects)
        {
            return MergeInto<TResult>(Mapper.Instance, objects);
        }
```

should this be something that in in the automapper core? and if so do you want a PR?

**Comment by lbargaoanu** [comment]
I believe people would expect more from Merge. For example skipping null properties in the source. And that is more involved.

**Comment by jbogard** [comment]
`Merge` does imply some additional behavior. MultiMap, MergeInto, Fill.

But yes, this has been asked.

What  does this look like on the validation side?

**Comment by lbargaoanu** [comment]
@jbogard Maybe we could have a project AutoMapper.Contrib for stuff like this?

**Comment by SimonCropp** [comment]
@lbargaoanu 

from my observations Contrib projects tend to become a dumping ground for too my unnecessary features and generally get abandoned in the long term. Not saying this would necessarily happen here but worth keeping in mind.

> What does this look like on the validation side?

@jbogard what do you mean by this?

**Comment by jbogard** [comment]
@SimonCropp when you do `AssertConfigurationIsValid`, this merging tends to blow up with the default validation mode (validating all the destination members are filled by a single map).

Would you have some sort of configuration validation that a destination type `Foo` is actually filled with several types? Or just skip validation?
