### ISSUE TITLE
Map to interface with concrete mapping declaration

### ISSUE THREAD

**Issue by mtdaniels** [AutoMapper/AutoMapper#2484]
If a map is configured with a concrete destination class, the mapper will not map to an interface that the destination class implements.  As a result of that, you end up having to declare one mapping for each interface / superclass that you might want to map to - even though the mappings would all have the same configuration (member mappings, etc), and would return the same concrete type.

When evaluating the map path, would it be possible to check if the destination of the map implements / inherits from the desired destination type?

https://stackoverflow.com/questions/13075588/configure-automapper-to-map-to-concrete-types-but-allow-interfaces-in-the-defini

The solution/workaround suggested above is to use `As` and create a separate mapping for every interface / superclass you might want to target.  I think this limits the mapping configuration (for instance, if you have `.CreateMap<Source, IDestination>().As<Destination>()` you cannot use `ForMember` and modify how things are set on Destination because you'd have to call `ForMember` before the `As`, thus your destination type within the `ForMember` is `IDestination`.  I believe this also prevents you from using `.ReverseMap()`.

**Comment by lbargaoanu** [comment]
Did you try the answer there? :)

**Comment by mtdaniels** [comment]
Sorry - updated my original comment with reasons why that is less-than-ideal.

**Comment by lbargaoanu** [comment]
When you map to an interface AM needs to know what's the concrete type unless you pass the destination yourself. Otherwise a proxy is created. That makes sense to me. How could AM possibly know what concrete type you want?

**Comment by mtdaniels** [comment]
Agreed - my hopes and dreams are that I can create a concrete mapping, then AutoMapper would pick it when I try to map to an interface that matches it.  As I understand, I need to explicitly create the mapping with the concrete type _and_ the interface.

I did create a simple / contrived example to test my understanding and expectations.

```
using System.ComponentModel.Design;
using AutoMapper;
using System.Diagnostics;

namespace AutoMapperTest {
    public class Program {
        static void Main(string[] args) {
            var cfg = new MapperConfiguration(c => {
                c.CreateMap<Dog, DogViewModel>().ForMember(dest => dest.Color, opt => opt.MapFrom(d => d.HairColor));
                c.CreateMap<Dog, INameViewModel>().As<DogViewModel>();
                c.CreateMap<Person, PersonViewModel>();
                c.CreateMap<Person, INameViewModel>().As<PersonViewModel>();
            });

            var mapper = cfg.CreateMapper();

            var source = new IName[] {
                new Dog {
                    Name = "dog",
                    HairColor = "color"
                },
                new Person {
                    Name = "person"
                }
            };

            // Simple mapping
            Debug.Assert(mapper.Map<DogViewModel>(source[0]) != null, "Condition 1");
            Debug.Assert(mapper.Map<DogViewModel>(source[0]).Color == "color", "Condition 2");
            Debug.Assert(mapper.Map<INameViewModel>(source[0]) is DogViewModel, "Condition 3");
            Debug.Assert(((DogViewModel)mapper.Map<INameViewModel>(source[0])).Color == "color", "Condition 4");
            Debug.Assert(mapper.Map<INameViewModel[]>(source)[0] is DogViewModel, "Condition 5");
        }

        public interface IName {
             string Name { get; set; }
        }

        public interface INameViewModel {
            string Name { get; set; }
        }

        public class Person : IName {
            public string Name { get; set; }
        }

        public class Dog : IName {
            public string Name { get; set; }
            public string HairColor { get; set; }
        }

        public class PersonViewModel : INameViewModel {
            public string Name { get; set; }
        }

        public class DogViewModel : INameViewModel {
            public string Name { get; set; }
            public string Color { get; set; }
        }
    }
}
```

The only condition failing currently is `condition 5` - I had expected 4 to fail also, but it works :-)

**Comment by lbargaoanu** [comment]
c.CreateMap<Dog, DogViewModel>().ForMember(dest => dest.Color, opt => opt.MapFrom(d => d.HairColor));
      c.CreateMap<IName, INameViewModel>()
	  	.Include<Person, PersonViewModel>()
		.Include<Dog, DogViewModel>();
      c.CreateMap<Person, PersonViewModel>();

**Comment by mtdaniels** [comment]
That's fairly indicative of the problem I'm pointing out.  If you had multiple interfaces that becomes messy pretty quick.  Is there a reason this type checking can't happen under the hood?

That aside, is there anyway to have the Includes in multiple places?  I was planning on using Profile instances to configure individual mappings.  If all of the Includes have to happen inline, extensibility is limited.

**Comment by lbargaoanu** [comment]
You didn't answer my question. How can AM know the concrete type?

**Comment by lbargaoanu** [comment]
Includes across profiles? :) I guess that could work, but it seems difficult to understand. You would have to look through all the profiles to understand what's going on.

**Comment by mtdaniels** [comment]
AM would know the concrete type because that's how the mapping is created.
```
c.CreateMap<Dog, DogViewModel>().ForMember(dest => dest.Color, opt => opt.MapFrom(d => d.HairColor));
```

That should be all the information AM needs to handle `mapper.Map<INameViewModel>(new Dog());` because the destination type of the configured map implements `INameViewModel`.

It is also sort of interesting to me that collections are handled a little differently with respect to the source type.  Specifically, 
```
IName source = new Dog();
mapper.Map<INameViewModel>(source);
```
I believe the above will look for a Dog -> INameViewModel map.
```
IName[] source = new IName[]{new Dog()};
mapper.Map<INameViewModel[]>(source);
```
but that would look for a IName -> INameViewModel map.

Are you saying that you can declare the Includes in multiple places currently, and each would not overwrite the mapping?

**Comment by mtdaniels** [comment]
One more question - while I'm pestering you incessantly - is there a way to prevent proxy objects from being created, and instead throw an exception if a mapping has not been created?

**Comment by lbargaoanu** [comment]
So AM should look around your maps looking for types that implement INameViewModel and choose one of them? :) That doesn't seem like a good idea to me. Yes, top level maps work with runtime types and the rest with compile time types (because they are precomputed), but the Include example works. I think you'll be the first to try Include/IncludeBase across profiles, but I don't see why it wouldn't work. It's definitely a bad idea, but it should work :) About proxies. You can write a custom configuration validator and check for this case.

**Comment by mtdaniels** [comment]
In my opinion - yes.  I can't think of a case where you'd want a different map for Dog -> INamedViewModel than Dog -> DogViewModel.

I still don't see why it's a bad idea to have the Include with the concrete map declaration - but perhaps I'm missing something.  It sounds like you're arguing that all maps should be in a single file, which would contradict the pattern of profile instances.

**Comment by lbargaoanu** [comment]
No, profiles are intended to separate configuration per module. It's expected that they aren't coupled to each other. They are useful because they can be understood in isolation. [Custom validation](https://github.com/AutoMapper/AutoMapper/blob/7a00700de61cd3234b6a6eb4bf0f6bbe402369b1/src/UnitTests/ConfigurationValidation.cs#L30).

**Comment by mtdaniels** [comment]
Ah - per module.  I had envisioned profiles per map.  Thanks for that clarification.
