### ISSUE TITLE
AutoMapperMappingException for object hierarchy with IEnumerable members

### ISSUE THREAD

**Issue by MrKrypto** [AutoMapper/AutoMapper#2486]
### Source/destination types

```csharp
public class SourceItem { }
public class DestItem { }
public class SourceA
{
	public IEnumerable<SourceItem> Items { get; set; }
	public IEnumerable<SourceB> Bs { get; set; } // Problem
}

public class SourceB
{
	public IEnumerable<SourceItem> Items { get; set; }
}

public class DestA
{
	public IEnumerable<DestItem> Items { get; set; }
	public IEnumerable<DestB> Bs { get; set; } // Problem
}

public class DestB
{
	public IEnumerable<DestItem> Items { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => {
	cfg.CreateMap<SourceA, DestA>();
	cfg.CreateMap<SourceB, DestB>();
});
```

### Version: x.y.z
6.2.2

### Expected behavior
Worked in 6.1.1.

### Actual behavior
AutoMapperMappingException:

> Error mapping types.
> 
> Mapping types:
> SourceB -> DestB
> AuthorTests.SourceB -> AuthorTests.DestB
> 
> Type Map configuration:
> SourceB -> DestB
> AuthorTests.SourceB -> AuthorTests.DestB
> 
>
> Property:
> Items

...and inner exception is:

> Cannot create an instance of interface type System.Collections.Generic.IEnumerable`1[AuthorTests.DestItem]
### Steps to reproduce
Problem occurs when you try to map SourceB...

```csharp
var destFoo = Mapper.Map<DestB>(new SourceB());
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by MrKrypto** [comment]
I am getting the same result with the MyGet build...

**Comment by MrKrypto** [comment]
Sorry, my bad... it's fixed in 6.2.2-ci-01426

**Comment by lbargaoanu** [comment]
I think we need a test here.

**Comment by AlekseiRusanov** [comment]
I'm having the exact same problem (6.2.2-ci-01426 fixes it)
When can we expect the fix to be rolled out?
Thanks.
