### ISSUE TITLE
Feature request: simplify flattening of nested objects

### ISSUE THREAD

**Issue by RudeySH** [AutoMapper/AutoMapper#2489]
My current usage is similar to the following:

    class Source {
        public int Id { get; set; }
        public SourceInfo Info { get; set; }
    }
    class SourceInfo {
        public string Name { get; set; }
    }
    class Destination {
        public int Id { get; set; }
        public string InfoName { get; set; }
    }
    
    cfg.CreateMap<Source, Destination>(); // flattens Source.Info.Name to Destination.InfoName

But ideally, I wouldn't want to use the name `InfoName`, just `Name`. This isn't currently possible, but in my case it would be extremely helpful if it worked something like this:

    class Destination {
        public int Id { get; set; }
        public string Name { get; set; } // just "Name"
    }
    
    cfg.CreateMap<SourceInfo, Destination>(); // first, establish mapping from nested class to destination
    // proposal
    cfg.CreateMap<Source, Destination>()
        .Flatten(src => src.Info); // implementation should re-use mapping between SourceInfo and Destination

[Here's an implementation](https://stackoverflow.com/a/37389057/1185136) of what I'm trying to achieve but this is no longer possible with newer versions of AutoMapper because the `TypeMap` isn't available anymore until after initialization.

**Comment by lbargaoanu** [comment]
See [this](https://gist.github.com/lbargaoanu/8e15798a8b4facd292feb5fcfbf1e3f7).

**Comment by RudeySH** [comment]
Wow! That's exactly what I needed. Honestly this should really be included with AutoMapper.
