### ISSUE TITLE
Generic MemberValueResolver

### ISSUE THREAD

**Issue by jonoliver82** [AutoMapper/AutoMapper#2492]
I am using AutoMapper 6.2.2 on ASP .NET Core 1.1 with .NET Framework Full 4.5.2 and standard ASP NET Core Dependency Injection.

I have an interface INameable that multiple objects implement
```csharp
public interface INameable<T>
{
    string GetName(int id);
}
```
My DTOs typically have an int Id field, and View Models a string Name field that needs to be looked up from the identifier:
```csharp
public class UserDTO
{
    public int SiteId { get; set; }
}

public class UserDetailsViewModel
{
    public string SiteName { get; set; }
}
```
I created a generic member value resolver so I could use the same resolver with multiple types
```csharp
public class NameableMemberValueResolver<TNameable> : IMemberValueResolver<object, object, int, string>
{
    private readonly INameable<TNameable> _nameable;

    public NameableMemberValueResolver(INameable<TNameable> nameable)
    {
        _nameable = nameable;
    }

    public string Resolve(object source, object destination, int sourceMember, string destMember, ResolutionContext context)
    {
        return _nameable.GetName(sourceMember);
    }
}
```
 My IOC Container is configured with a suitable object for the INameable parameter, eg
```csharp
services.AddScoped<INameable<SiteDTO>, SiteRepository>();
```
In my mapping profile I specify the ResolveUsing with the required generic type parameter.

```csharp
CreateMap<UserDTO, UserDetailsViewModel>()
    .ForMember(dst => dst.SiteName, opt => opt.ResolveUsing<NameableMemberValueResolver<SiteDTO>, int>(src => src.SiteId));
```
At runtime I get an exception:
```csharp
Error mapping types.

Mapping types:
UserDTO -> UserDetailsViewModel
Data.Models.UserDTO -> PortalWebsiteCore.ViewModels.UserDetailsViewModel

Type Map configuration:
UserDTO -> UserDetailsViewModel
Data.Models.UserDTO -> PortalWebsiteCore.ViewModels.UserDetailsViewModel

Property:
SiteName

InnerException:
Cannot create an instance of type Common.Resolvers.NameableMemberValueResolver`1[Data.Models.SiteDTO]
```

I have created and used other Resolvers with constructor parameters obtained from the IOC container without issue, so I think the issue is related to the use of the generics but I'm not sure why it doesn't work and how to correct it? I shouldn't have to create a resolver for each concrete type.

**Comment by lbargaoanu** [comment]
See [this](http://automapperdocs.readthedocs.io/en/latest/Dependency-injection.html#asp-net-core).

**Comment by jonoliver82** [comment]
I am already using AutoMapper.Extensions.Microsoft.DependencyInjection 2.0.1 and have multiple non-generic resolvers with dependencies being injected as expected.

**Comment by lbargaoanu** [comment]
Then you're doing it wrong. You should request the interface, not the concrete class. ```ResolveUsing<Interface>```.
