### ISSUE TITLE
ExpressionBuilder can't create expression of Ctor with different parameter name

### ISSUE THREAD

**Issue by javiercampos** [AutoMapper/AutoMapper#2493]
For some reasons I'm using the projecting expressions generated by Automapper (using the `IExpressionBuilder` returned by `MapperConfiguration`). Everything seems to work great so far, except when I use a constructor (using `ForCtorParam`) and one of the parameters has a different name than the property it maps to.

### MCVE
https://gist.github.com/javiercampos/dbf1fb1e17e143e2b693b56711301ee2

### Source/destination types
```csharp
public class ClassA
{
  public string PropertyA { get; set; }
  public string PropertyB { get; set; }
}

public class ClassB
{
  public string PropertyA { get; }
  public string PropertyB { get; }

  public ClassB(string propertyA, string propertyBWithDifferentName)
  {
    PropertyA = propertyA;
    PropertyB = propertyBWithDifferentName;
  }
}
```

### Mapping Configuration
```csharp
.CreateMap<ClassA, ClassB>()
  .ForCtorParam("propertyA", x => x.MapFrom(y => y.PropertyA))
  .ForCtorParam("propertyBWithDifferentName", x => x.MapFrom(y => y.PropertyB))
```

### Expected behavior
Calling:
```csharp
mapperConfig.ExpressionBuilder.GetMapExpression<ClassA, ClassB>()
```
Should return an expression like: 
```csharp
{dto => new ClassB(dto.PropertyA, dto.PropertyB) {}}
```
### Actual behavior
`GetMapExpression` throws an `AutoMapper.AutoMapperMappingException` exception, with the message:
```
Unable to generate the instantiation expression for the constructor Void .ctor(System.String, System.String): no expression could be mapped for constructor parameter 'System.String propertyBWithDifferentName'.
```

### Remarks
If the constructor parameter is called `propertyB` (same name as a known property), the call succeeds and I get back the correct expression.

I'm not sure if the `ExpressionBuilder` is a public API or whether I should use it at all, or this is a supported scenario. Again, if this is not a supported scenario... is there any supported one so where I can get a configured projection expression?

**Comment by lbargaoanu** [comment]
It's not an API, ProjectTo is the API.  EF doesn't work with constructors so that's probably why it fails. But if you want to fix it, I think @jbogard wouldn't mind :)

**Comment by javiercampos** [comment]
I'm not going to use it with EF, just plain linq `Select` on enumerables (not queryables). Thing is, with the `ExpressionBuilder` I can just store that expression and don't need a dependency on automapper on all my projects (just the ones where I set up the mapping profiles), so having a public API that exposes that projection predicate would be nice to have.

About the PR, honestly, I wouldn't even know where to start looking 😢

**Comment by lbargaoanu** [comment]
You can try expression mapping.
