### ISSUE TITLE
Conditional unflattening object initialization 

### ISSUE THREAD

**Issue by kpinette** [AutoMapper/AutoMapper#2498]
When unflattening via ReverseMap, it would be helpful to be able to specify a condition that prevents the destination object from being initialized unless met. For example:

```
cfg.CreateMap<Entity, DTO>()
    .ReverseMap()
        .ForMember(d => d.UnflattenedType, o => o.Condition(s => s.FlattenedId.HasValue));
```

This currently results in object initialization though. The only succinct workaround that I've found, without specifying each property that needs to be unflattened, is to use AfterMap like so: 

```
cfg.CreateMap<Entity, DTO>()
    .ReverseMap()
        .AfterMap((s, d) => d.UnflattenedType = s.FlattenedId.HasValue ? d.UnflattenedType : null);
```

I'd prefer to accomplish this without resorting to bandaging the issue after the mapping though. 

[My stackoverflow question](https://stackoverflow.com/questions/48233824/automapper-6-2-2-conditional-unflattening)

**Comment by lbargaoanu** [comment]
The ForMember would work with a map from Entity to UnflattenedType.

**Comment by kpinette** [comment]
@lbargaoanu I tried both Condition and Precondition and even when the condition is false, a destination object is still initialized. How do I prevent initialization if there are no values to map to that object?

**Comment by lbargaoanu** [comment]
No, I meant that you give up unflattening and just map UnflattenedType from the source.

**Comment by kpinette** [comment]
Oh sorry, I misunderstood. I definitely need to be able to use ReverseMap, so for now I'll just have to do the extra work in AfterMap to null it out as I'm doing in my example up top. I guess that makes this a feature request then? I think that if a property isn't being mapped to, it shouldn't be initialized. I just don't see the sense in that. If I'm mapping between 2 complex types and I add a condition to not map that property, or the source is null, it doesn't still initialize the destination object, so if I add a condition to ignore UnflattenedType I would think it should leave that destination property null.

**Comment by lbargaoanu** [comment]
Yes, but this is flattening and unflattening, not the default mapping. It doesn't rely on a map being there. It would work the way you want if you relied only on maps and give up the default flattening. So it's a feature request. I, for one, find the existing behavior entirely reasonable :)

**Comment by lbargaoanu** [comment]
Related to #2429 I suppose.

**Comment by lbargaoanu** [comment]
PR welcome.
