### ISSUE TITLE
Mapping with generic type causes mapping issue with null IEnumerable properties

### ISSUE THREAD

**Issue by TomJMaher** [AutoMapper/AutoMapper#2500]
### Source/destination types

```csharp
Dummies.Dc.ParentDummy dc;
Dummies.Dto.ParentDummy dto;

dto = new Dummies.Dto.ParentDummy()
{
    Children = null
};
```
The following file contains the full source code listing of the types (6 in total) used
[Types.txt](https://github.com/AutoMapper/AutoMapper/files/1639474/Types.txt)

### Mapping configuration

```csharp
mapper = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Dummies.Dto.Container<Dummies.Dto.ParentDummy>, Dummies.Dc.Container>();
    cfg.CreateMap<Dummies.Dto.ParentDummy, Dummies.Dc.ParentDummy>();
    cfg.CreateMap<Dummies.Dto.ChildDummy, Dummies.Dc.ChildDummy>();
}).CreateMapper();

```

### Expected behavior

The Dto.ParentDummy class should be mapped to an instance of Dc.ParentDummy with the Children property being null.

### Actual behavior

The following error was thrown:
> Cannot create an instance of interface type System.Collections.Generic.IEnumerable`1[Test.Dummies.Dc.ChildDummy].
> Parameter name: type
> 
> Error mapping types.
> 
> Mapping types:
> ParentDummy -> ParentDummy
> Test.Dummies.Dto.ParentDummy -> Test.Dummies.Dc.ParentDummy
> 
> Type Map configuration:
> ParentDummy -> ParentDummy
> Test.Dummies.Dto.ParentDummy -> Test.Dummies.Dc.ParentDummy
> 
> Property:
> Children

### Steps to reproduce
```csharp
dc = mapper.Map<Dummies.Dc.ParentDummy>(dto);
```
The following file contains the full unit:
[UnitTest.txt](https://github.com/AutoMapper/AutoMapper/files/1639501/UnitTest.txt)

The unit test shows that the ordering of the configuration is important. When the CreateMap for the generic Container class is defined first then the Map method fails. If the CreateMap for the generic Container class is defined last or not defined at all then the Map method works. 

Also if the Children property is seems only to fail when it is set to null on the source object.

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by TomJMaher** [comment]
Thanks. I can confirm this works with the latest continuous integration build: 6.2.2-ci-01430
