### ISSUE TITLE
The type initializer for 'AutoMapper.Mappers.EnumToEnumMapper' threw an exception

### ISSUE THREAD

**Issue by hugoterelle** [AutoMapper/AutoMapper#2505]
Just trying to use AutoMapper in my Xamarin Forms IOS application (it works under Android and UWP) 

### Source/destination types
Xamarin Forms 2.5.0.122203
IOS SDK 11.2

### Mapping configuration

Nothing special, just 
Mapper.Initialize(cfg => {});

### Version: x.y.z
AutoMapper 6.2.2.

### Expected behavior

Launch the initialization process.

### Actual behavior

It throws an exception : 
The type initializer for 'AutoMapper.Mappers.EnumToEnumMapper' threw an exception

Inner Exception:

System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.3/src/mono/external/corefx/src/System.Linq/src/System/Linq/First.cs:31 
  at AutoMapper.Mappers.EnumToEnumMapper..cctor () [0x0000f] in <f127440147884adc9e84e28dcdde1719>:0 }

### Steps to reproduce

Mapper.Initialize(cfg => {});
You can add mapping inside lambda, it has the same behaviour

**Comment by lbargaoanu** [comment]
It's saying that ```typeof(EnumToEnumMapper).GetRuntimeMethods().First(m => m.IsStatic)``` doesn't find anything. But the method is there. Maybe smth in Xamarin is removing it because it seems it's not used.

**Comment by hugoterelle** [comment]
You're right.  Before calling the Mapper.Initialize(...), I just call the EnumToEnumMapper with fake values and the Mapper.Initialize(...) works.  Thanks a lot!

**Comment by stesvis** [comment]
I am sorry @hugoterelle how do you do that?
I've never used EnumToEnumMapper...but i have the same problem. Thanks!

**Comment by jbogard** [comment]
It’s the linker removing methods. You have to refer to the types somehow. I
usually have a file like LinkerPleaseInclude.cs and just refer to the
missing types in some way.

**Comment by stesvis** [comment]
I am so sorry but I am not understanding.
Could you show a code snippet of what you mean?

**Comment by hugoterelle** [comment]
@stesvis  
Here is the code I call before any other call to AutoMapper

AutoMapper.Mappers.EnumToEnumMapper.Map<MyEnumeration, MyEnumeration>(MyEnumeration.MyValue);
           
Where "MyEnumeration" is one of the enum in your source code.  
It will tell the C# linker to not forget the EnumToEnumMapper
