### ISSUE TITLE
Add a MapFromAttribute for when mapping to an external type

### ISSUE THREAD

**Issue by harryremon** [AutoMapper/AutoMapper#2506]
### Explanation
MapToAttribute is great but to work both ways you have to add it to both Source and Destination properties, but sometimes you're mapping to/from a type in an external library(or in another scenario, an auto generated class) in which case you can't add the "Map To" attribute to the other class. Making MapTo reversible or adding a "Map From" attribute would be a great addition .

### Example:
Issue #1993 Explains this perfectly, Imagine that Class "Thing1" in this issue is not editable for the reasons mentioned above, using attributes to map will not work.

**Comment by harryremon** [comment]
for those searching for a temp solution I've created an extension method that would have the same effect in the below gist:
[ReverseAttributes](https://gist.github.com/harryremon/b86fb1a31f8b22d57202992f240b9876#file-reverseattributes-cs)

**Comment by lbargaoanu** [comment]
You can also use ForAllMaps with ForAllMembers. That would help with MapFromAttribute as well.

**Comment by lbargaoanu** [comment]
PR welcome.
