### ISSUE TITLE
Mapping of null to IEnumerable fails with exception System.ArgumentException: Cannot create an instance of interface 

### ISSUE THREAD

**Issue by grassgit** [AutoMapper/AutoMapper#2507]
### Source/destination types

```csharp
public class TestTypeA
{
    public string Test { get; set; }
}
public class TestTypeB
{
    public string Test { get; set; }
}
```

### Mapping configuration

```csharp
var config = new AutoMapper.MapperConfiguration(x =>
{
    x.CreateMap<TestTypeA, TestTypeB>();
});
var mapper = config.CreateMapper();
```

### Version: 6.2.0
Fails on 6.2.0, 6.2.1, 6.2.2
Last version it succeeds on 6.1.1 

### Expected behavior

Mapping of null should return null

### Actual behavior

**Exception**
System.ArgumentException: Cannot create an instance of interface type System.Collections.Generic.IEnumerable`1[TestClass+TestTypeB].
Parameter name: type

**StackTrace**
at lambda_method(Closure , IEnumerable\`1 , IEnumerable\`1 , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source)

### Steps to reproduce

This mapping fails with the exception above. On version 6.1.1 this succeeds and Map returns null as expected
```csharp
TestTypeA[] source = null;
mapper.Map<IEnumerable<TestTypeA>, IEnumerable<TestTypeB>>(source);
```

This succeeds and correctly maps, the only difference is the source data is actually assigned.
```csharp
TestTypeA[] source = new[] {
    new TestTypeA() { Test = "1" },
    new TestTypeA() { Test = "2" },
};
mapper.Map<IEnumerable<TestTypeA>, IEnumerable<TestTypeB>>(source);
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by hades200082** [comment]
I have this same issue.  The MyGet build is the same as the NuGet build - 6.2.2

**Comment by lbargaoanu** [comment]
No, it isn't.

**Comment by jbogard** [comment]
Make sure you're pulling in the prerelease version :)

**Comment by hades200082** [comment]
I did.

I ran the command `Install-Package AutoMapper -Source https://www.myget.org/F/automapperdev/api/v3/index.json -IncludePrerelease` in Package Manager Console in Visual Studio 2017 for my .Net Core 2.0 project and it downloaded 6.2.2.

https://myget.org/gallery/automapperdev shows the latest version as 6.2.2 also.

**Comment by lbargaoanu** [comment]
https://myget.org/feed/automapperdev/package/nuget/AutoMapper
That's new. Maybe it's a MyGet issue. Anyway, just take the newest version :)

**Comment by hades200082** [comment]
The link you gave also shows 6.2.2 as the latest version.

**Comment by jbogard** [comment]
Ahhhh because we haven't bumped the project version

**Comment by lbargaoanu** [comment]
That makes sense, but the date is there, today.

**Comment by jbogard** [comment]
@lbargaoanu the problem is the NuGet client wouldnt install the "newer" versions unless you explicitly specified the version which is something I rarely do for pre-release. SemVer saw the new versions as old. I need to make sure to bump the version immediately after release.

**Comment by jochenvangasse** [comment]
So were best to install v6.x from the myget feed, and not from the official nuget feed.
Bit confusing, no?

**Comment by jbogard** [comment]
No, that’s how CI builds work.

**Comment by lbargaoanu** [comment]
Null maps to null.

**Comment by kaiza** [comment]
@lbargaoanu Not exactly. If `AllowNullCollections` is false (which it is by default) then null maps to an empty collection for collection types. This seems to work fine for IList but fails for ISet. As a workaround I've had to declare the ISet as a concrete type HashSet on the target type. Or a custom mapping for that property would probably work too. Anyway, sounds like a bug to me.

**Comment by niemyjski** [comment]
I'm also running into this with ISet<string>

**Comment by lbargaoanu** [comment]
The fix is in the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build, but read [this](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html) before thinking about upgrading.
