### ISSUE TITLE
Obtaining IMapperConfigurationExpression from within Profile

### ISSUE THREAD

**Issue by bonsailimited** [AutoMapper/AutoMapper#2509]
Hi,

I have been using the pattern described by many, including [here](https://ppolyzos.com/2015/09/29/map-one-object-to-another-using-automapper/) and [here](https://garywoodfine.com/using-automapper-domain-objects-dotnet-core/) for quite a long time.

In short, I create the following and attach where necessary to my Domain Models, ViewModels, DTOs, etc.:
```csharp
public interface IMapTo<T> { };
public interface IMapFrom<T> { }
public interface IMapCustom { void CreateMappings(IMapperConfigurationExpression config); }
```

I have migrated successfully to the latest (AutoMapper 6.2.2, .NETCORE2.0, ASPNETCORE2.0) and have removed the static implementations. Where the static class/method in the above examples would be called, I have replaced with a class inheriting `AutoMapper.Profile`:
```csharp
public class DomainProfile : Profile
{
	public DomainProfile()
	{
		var assemblies = AppDomain.CurrentDomain.GetAssemblies()
			.Where(a => !a.IsDynamic)
			.ToArray();
		var types = assemblies.SelectMany(a => a.GetExportedTypes()).ToArray();

		LoadIMapFromMappings(types);
		LoadIMapToMappings(types);
		LoadIMapCustomMappings(types);
	}

	private void LoadIMapCustomMappings(IEnumerable<Type> types)
	{
		var maps = (from t in types
					from i in t.GetInterfaces()
					where typeof(IMapCustom).IsAssignableFrom(t) &&
						  !t.IsAbstract &&
						  !t.IsInterface
					select (IMapCustom)Activator.CreateInstance(t)).ToArray();
			
		var cfg = new AutoMapper.Configuration.MapperConfigurationExpression();
		foreach (var map in maps)
			map.CreateMappings(cfg); // TODO (ch): This will NOT work. Only here for compilability. Need to figure out how to get to the cfg instance
	}
	private void LoadIMapFromMappings(IEnumerable<Type> types)
	{
		var maps = (from t in types
					from i in t.GetInterfaces()
					where i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMapFrom<>) &&
						  !t.IsAbstract &&
						  !t.IsInterface
					select new
					{
						Source = i.GetGenericArguments()[0],
						Destination = t
					}).ToArray();
			
		foreach (var map in maps)
			CreateMap(map.Source, map.Destination);
	}
	private void LoadIMapToMappings(IEnumerable<Type> types)
	{
		var maps = (from t in types
					from i in t.GetInterfaces()
					where i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IMapTo<>) &&
						  !t.IsAbstract &&
						  !t.IsInterface
					select new
					{
						Destination = i.GetGenericArguments()[0],
						Source = t
					}).ToArray();

		foreach (var map in maps)
			CreateMap(map.Source, map.Destination);
	}
}
```

And then in an ASPNETCORE2.0 WebApi I am calling `services.AddAutoMapper();`. This works perfectly - and when the code lands in my Profile class constructor I can easily reflect and add mappings for all of the `IMapTo<T>` and `IMapFrom<T>` domain objects. 

My problem is how to map the `IMapCustom` objects. I cannot find any way to access the `IMapperConfigurationExpression` to hand to the CreateMappings methods. I would previously create this object while calling `Mapper.Initialize` - but as I am moving to the DI pattern I cannot call this any longer (without reverting everything back to static).

The problematic lines, excerpted here:
```csharp
var cfg = new AutoMapper.Configuration.MapperConfigurationExpression();
foreach (var map in maps)
	map.CreateMappings(cfg); // TODO (ch): This will NOT work. Only here for compilability. Need to figure out how to get to the cfg instance
```

Is there a way to get at this in the Profile class in the latest versions? 

Thanks!

**Comment by lbargaoanu** [comment]
There are other interfaces the Profile class implements. Maybe that CreateMappings method should work with those. And then you could simply pass this inside your profile.

**Comment by bonsailimited** [comment]
@lbargaoanu Thank you. I had considered passing `this`; or using some type of delegate - but it seemed a little less than ideal to hand the entire profile (or a portion thereof). But I hadn't considered examining the other interfaces. I will have a look at those - thank you!

**Comment by bonsailimited** [comment]
The other interfaces seemed to be the key, thank you again @lbargaoanu !

Changing the `IMapCustom` interface to this:
```csharp
public interface IMapCustom { void CreateMappings(IMappingExpression mapExp); }
```

... and then simply doing this in the `Profile`:
```csharp
foreach (var map in maps)
	map.CreateMappings((IMappingExpression)this);
```

And I'm off and running again. It does seem a little bulky to pass the entire Profile around though. This is a greenfield and so unfortunately I am not anywhere close to performance testing - but if this presents as a problem I can come back and add further observations.
