### ISSUE TITLE
On a Profile, CreateMap<S, D>().ConvertUsing(Method) not working

### ISSUE THREAD

**Issue by KenBonny** [AutoMapper/AutoMapper#2510]
I'm working with a legacy system that handles the translations and I want to map a simple type with all translations to a newer type that converts it into a list of translations.

### Source/destination types

```csharp
class OldTranslation
{
  string En;
  string Fr;
  // etc.
}
class NewTranslation
{
  string Culture;
  string Translation;
}
```

### Mapping configuration

```csharp
class MyProfile : Profile
{
  CreateMap<OldTranslation, List<NewTranslation>().ConvertUsing(MyFunction);
}
private NewTranslation MyFunction(OldTranslation t)
{
  return new List<NewTranslation>
  {
    new NewTranslation("en", t.En),
    new NewTranslation("fr", t.Fr),
    // etc...
  }
}
```

### Expected behavior
A list of NewTranslation objects in the containing object (like order.Translations).

### Actual behavior
The translation properties are null.

### Steps to reproduce

```csharp
IMapper mapper; // injected through IOC
var orderDto = mapper.Map(orderDbEntity);
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by KenBonny** [comment]
That I will have to do this weekend (if I can find the time this weekend) because this is an issue at work and I'm not allowed to distribute that code. 😄

**Comment by lbargaoanu** [comment]
Until then...
