### ISSUE TITLE
MaxDepth on list sets the containing objects to null

### ISSUE THREAD

**Issue by JonnyMattsson** [AutoMapper/AutoMapper#2511]
When having a maxdepth setting the behaviour is different depending on if it is a single object or a list. 
A single object is set to null which is fine, but a list contains of null elements instead of being an empty list.

### Mapping configuration

```csharp
CreateMap<Company, CompanyResponse>().MaxDepth(2);
```

### Version: x.y.z
6.2.2

### Expected behavior

  "parentCompany": null,
    "subCompanies": [ ]

### Actual behavior

  "parentCompany": null,
    "subCompanies": [
      null,
      null,
      null,
      null,
      null,
      null
    ]

**Comment by lbargaoanu** [comment]
Try setting it to 1 or 3.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
Another thing is, this seems to be [the desired behavior](https://github.com/AutoMapper/AutoMapper/blob/16d508a120a5f3a2df402e58497e789d85fd8979/src/UnitTests/MaxDepthTests.cs#L65) :) cc @jbogard

**Comment by jbogard** [comment]
Yep, I don't think we'll ever have consensus on how to count the depth.
