### ISSUE TITLE
Bug in mapping derived classes

### ISSUE THREAD

**Issue by muhanov-apps** [AutoMapper/AutoMapper#2512]
I found a regression since 6.1.1
If we map a SrcClass to DestBaseClass and than  map a SrcClass to DestDerivedClass - > it fails
 
### Source/destination types

```csharp
 public class SrcClass
    {
        public string user { get; set; }
    }

    public class DestBaseClass
    {
        public string user { get; set; }
    }

    public class DestDerivedClass: DestBaseClass
    {
        public string user2 { get; set; }
    }
```

### Mapping configuration

```csharp
 AutoMapper.Mapper.Initialize(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;
                cfg.ValidateInlineMaps = false;
            });
```

### Actual behavior
Exception:
Unable to cast object of type 'DestBaseClass' to type 'DestDerivedClass'.

### Steps to reproduce

 var ret1 = Mapper.Map< DestBaseClass >(new SrcClass(){user = "123"});
var ret2 = Mapper.Map< DestDerivedClass >(new SrcClass() { user = "123" });

### Workaround 

I found a workaround by deleting this fragment
 in MapperConfiguration.cs GetTypeMap(TypePair initialTypes)

```csharp
 if (types != initialTypes && _typeMapPlanCache.TryGetValue(types, out var typeMap))
                {
                    if (typeMap != null)
                    {
                        return typeMap;
                    }
                }
```

because it returns wrong typeMap for SrcClass->DestBaseClass but not SrcClass->DestDerivedClass

**Comment by lbargaoanu** [comment]
It cannot work with CreateMissingTypeMaps true. The base map will match.

**Comment by lbargaoanu** [comment]
I think this only worked because CreateMissingTypeMaps was false by default.

**Comment by muhanov-apps** [comment]
I never used explicit way with CreateMap methonds in project... just called static Mapper.Map<>()  and it worked )) so in some way missing typemaps generated automatically after all

**Comment by lbargaoanu** [comment]
I could be wrong :) cc @jbogard
