### ISSUE TITLE
Open generics in combination with mapping inheritance do not work

### ISSUE THREAD

**Issue by pfeigl** [AutoMapper/AutoMapper#2513]
This is probably a very rare case but hit's us with the .net core Identity classes because they reflect just this setup.

When trying to define mapping rules for open generics and re-use them on the concrete implementation using IncludeBase, no errors appear while setting the mapping up, but the defined rules are not applied.

Given the following example:

```csharp
using AutoMapper;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap(typeof(BaseUserDto<>), typeof(BaseUserEntity<>))
                    .ForMember("Id", opt => opt.Ignore());

                cfg.CreateMap(typeof(ConcreteUserDto), typeof(ConcreteUserEntity))
                    .IncludeBase(typeof(BaseUserDto<>), typeof(BaseUserEntity<>));
            });

            var user = new ConcreteUserDto
            {
                Id = "my-id",
                Name = "my-User"
            };

            var userEntity = Mapper.Map<ConcreteUserEntity>(user);
        }
    }

    public abstract class BaseUserDto<TIdType>
    {
        public TIdType Id { get; set; }
        public string Name { get; set; }
    }

    public class ConcreteUserDto : BaseUserDto<string>
    {
    }

    public abstract class BaseUserEntity<TIdType>
    {
        public TIdType Id { get; set; }
        public string Name { get; set; }
    }

    public class ConcreteUserEntity : BaseUserEntity<string>
    {
    }
}
```

The expectation would be, that the resulting `userEntity` object has it's `Id` property set to null, however it is copied over from the DTO.

When changing the example to hardcode all generics to `int`, everything works as expected.

**Comment by pfeigl** [comment]
Also found this (which seems to be very closely related): https://github.com/AutoMapper/AutoMapper/issues/2333

I used the latest version from here and my problem is still reproduceable:
https://myget.org/feed/automapperdev/package/nuget/AutoMapper/6.2.2-ci-01434

**Comment by lbargaoanu** [comment]
You can try working around it by using the typed version of ForMember with a non generic interface.

**Comment by pfeigl** [comment]
Unfortunately you cannot use typed Methods with open generics. We have been using the typed versions only sofar, but that wouldn't work here.

**Comment by lbargaoanu** [comment]
I said with a non generic interface :)

**Comment by pfeigl** [comment]
doh - should have read until the last word, sorry.

Unfortunately this aint gonna work either in our use-case, because the property we actually want to Ignore is only defined with the generic, so it wouldn't be available in the generic ForMember<>.

I also tried the generic CreateMap<> with the non-generic ForMember with a string based PropertyName, but the internal validation fails with an exception, that the member is not available.

**Comment by lbargaoanu** [comment]
https://gist.github.com/lbargaoanu/31d8236589f29f2e530ada5dbeccdaf6

**Comment by pfeigl** [comment]
Try to setup something on the Id property in the base mapping - that's what we actually are trying to do. Sorry for the missleading initial example which just works on a property which has a static type, it was only thought as a reproduceable initially.

**Comment by lbargaoanu** [comment]
:)

**Comment by pfeigl** [comment]
I updated the initial issue text to better reflect what we are doing.

**Comment by lbargaoanu** [comment]
```BaseUserDto<>``` is not a base class of ```ConcreteUserDto```, but ```BaseUserDto<string>``` is. That's what the PR addresses.

**Comment by pfeigl** [comment]
Thanks for this super fast fix btw 👍 Is there any info on when the next release will happen which is going to include the fix?
