### ISSUE TITLE
6.1.1 -> 6.2.2 broke int -> int? mapping

### ISSUE THREAD

**Issue by snebjorn** [AutoMapper/AutoMapper#2514]
### Source/destination types
```csharp
public class Source {}

public class Destination
{
    public int? SomeId { get; set; }
}
```

### Mapping configuration
```csharp
CreateMap<Source, Destination>()
    .ForMember(dest => dest.SomeId, 
        opts => opts.ResolveUsing((src, dst, dstMember, res) => res.Items["foo"]));
```

### Version: 6.2.2
Targeting .NET framework v.4.6.1.

### Expected behavior
Successful map where `Destination.SomeId == 123`

### Actual behavior
Throws `AutoMapperMappingException`

> Mapping types:
> Source -> Destination
> 
> Type Map configuration:
> Source -> Destination
> 
> Property:
> SomeId
> ---- System.InvalidOperationException : Nullable object must have a value.
> 

### Steps to reproduce

1. Install AutoMapper 6.1.1.
2. Observe it works.
3. Upgrade to AutoMapper 6.2.2
4. Observe exception.

```csharp
_mapper.Map<Destination>(source, options => options.Items["foo"] = 123);
```

To fix this exception I have to cast the value.

```csharp
CreateMap<Source, Destination>()
    .ForMember(dest => dest.SomeId, 
        opts => opts.ResolveUsing((src, dst, dstMember, res) => (int?) res.Items["foo"]));
```

**Comment by lbargaoanu** [comment]
Yes, you need the cast.

**Comment by lbargaoanu** [comment]
If for some reason you don't want the cast, you can set MapAtRuntime for that member.

**Comment by snebjorn** [comment]
Okay so it's the intended behavior, good to know :)
Also thanks for the tip about MapAtRuntime
