### ISSUE TITLE
Reference mapping `Profile` in AutoMapperMappingException

### ISSUE THREAD

**Issue by snebjorn** [AutoMapper/AutoMapper#2517]
I was wondering if it is possible to include a reference to the mapping `Profile` relevant to a thrown `AutoMapperMappingException`.

Could look something like this:
> Mapping types:
> Source -> Destination
> 
> Type Map configuration:
> Source -> Destination
>
> Mapping profile:
> Namespace.MappingProfile (clickable link)
> 
> Property:
> SomeProperty: Text

It would help a lot when you split your mappings into many profiles as it can take some digging to find the correct `Profile`. Example: [ContosoUniversity](https://github.com/jbogard/ContosoUniversity)
If a `Profile` isn't used then this is ignored.

**Comment by lbargaoanu** [comment]
If you know the type, you know the profile, but PR welcome :)

**Comment by jbogard** [comment]
The exception already includes the TypeMap involved so the information is
there. And a clickable link?

PR welcome!

**Comment by snebjorn** [comment]
In my case "Mapping types" and "Type Map configuration" had the exact same info. Yes they're clickable links to the Source and Destination types.

So my suggestion is purely a quality of life change as you can find the relevant mapping profile from the Source and Destination types, thought not as easily as clicking a link in the exception message.

But I hear you, I'll try to cook up a PR :)

**Comment by jbogard** [comment]
Go for it!
