### ISSUE TITLE
ProjectTo not mapping properties to derived types, although the mapping configuration is set up to only know derived types

### ISSUE THREAD

**Issue by TomWouters** [AutoMapper/AutoMapper#2519]
### Source/destination types

```csharp
#region DestinationTypes
        private class A
        {
            public List<B> Bs { get; set; }
        }

        private class B
        {
            public string Id { get; set; }
        }

        private class C : B
        {
            public string TestC { get; set; }
        }

        #endregion DestinationTypes

        #region SourceTypes
        private class D
        {
            public List<E> Bs { get; set; }
        }

        private class E
        {
            public string Id { get; set; }
            public string TestC { get; set; }
        }
        #endregion SourceTypes
```

### Mapping configuration

```csharp
var _cfg =new MapperConfigurationExpression();            
            _cfg.CreateMap<E, C>();            
            _cfg.CreateMap<D, A>();
            
            var _config = new MapperConfiguration(_cfg);
```

### Expected behavior

I expected an iqueryable<A> where the List<B> Bs is filled with instances of type C.

### Actual behavior

The List<B> Bs is filled with instances of type B, instead of with type C.

### Steps to reproduce

```csharp
[TestMethod]
        public void TestProjection()
        {
            int _total = 10;
            var _listOfD = new List<D>();
            for (int _i = 0; _i < 10; _i++)
            {
                var _d = new D();
                _d.Bs = new List<E>();
                for (int _j = 0; _j < _total; _j++)
                {
                    var _e = new E();
                    _e.Id = $"{_i}_{_j}";
                    _e.TestC = $"C{_i}_{_j}";
                    _d.Bs.Add(_e);
                }
                _listOfD.Add(_d);
            }
            var _cfg =new MapperConfigurationExpression();            
            _cfg.CreateMap<E, C>();            
            _cfg.CreateMap<D, A>();
            
            var _config = new MapperConfiguration(_cfg);
            //_config.ResolveTypeMap(typeof(E), typeof(C));
            //_config.CompileMappings();
            var _x = _listOfD.AsQueryable().ProjectTo<A>(_config);
            foreach (var _z in _x)
            {
                var _item = (C)_z.Bs.FirstOrDefault();
                Debug.Assert(_item.TestC != null && _item.Id != null);
            }
        }
```

**Comment by lbargaoanu** [comment]
Set CreateMissingTypeMaps to false.

**Comment by TomWouters** [comment]
I included 
changed the test method to 
 so the first statement after var _cfg =new MapperConfigurationExpression();   is now
_cfg.CreateMissingTypeMaps = false;

If i run it, it still doesn't give the desired outcome:


The resulting error on the projection statement is that there is no map from E to B
"
Missing map from UnitTest.Storage.Sqlite.SelfContained.SelfContainedUnitTest+E to UnitTest.Storage.Sqlite.SelfContained.SelfContainedUnitTest+B. Create using Mapper.CreateMap<E, B>.
"

If I add a _cfg.CreateMap<E,B> then the instances are of B type, and not of C type.

So just setting the createmissingtypemaps to false isn't enough to solve the issue.

**Comment by lbargaoanu** [comment]
Of course not :) You've to make it work. But I'm not sure how much sense it makes. Because ProjectTo doesn't really work with inheritance because EF doesn't. Some simple things do work, but you have to discover that for yourself. Using Map is an alternative.

**Comment by TomWouters** [comment]
Actually, in the setup I have, Entity framework only knows the inherited objects (so a set of DB objects), where the instances in the code are non db objects.  So basically, the inheritence part is already handled on db side, but the conversion (as you see in the example, there is no EF) is what I'm interested in.  Do you have an example or something to look at so I can replace the new B with a new C, or a directive to tell automapper it should instantiate C instead of B  (I actually don't understand why automapper creates an instance of B, because the only thing it should know is that E is mapped to C)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by MattHartz** [comment]
Hi @TomWouters and @lbargaoanu .  Any solution on this? I implemented a Table-By-Inheritance set up for Entity framework, and when I query off the abstract base type, I get the derived type as hoped.  But if I try utilizing ProjectTo, all I get in response is the BaseDTO type.

If not, this can be solved with 2 queries instead of 1, nothing too crazy.

Thanks!

**Comment by jbogard** [comment]
@MattHartz try writing your projection without AutoMapper. Just using a `Select` after `dbContext.Foos` or whatever.

If you can make it work with LINQ then you can make it work with `ProjectTo`.

**Comment by MattHartz** [comment]
@jbogard Yeah, this doesn't seem like a do-able task, or at least within reason.  Thanks for the response.

**Comment by TylerCarlson1** [comment]
Last I recalled EF6 doesn't support it and has no plans to.  Proper Query gives `NotSupportedException`

AutoMapper doesn't support this either with ProjectTo, because there's no benefit in it.

**Comment by TomWouters** [comment]
Basically if it is an entity framework only thing, then my solution is:  Create objects (not entities), create derived objects (not entities), create entities from the derived objects (I dynamically created my dbcontext and sets class with those entity objects).  Keep a relation between the 3 types (eg a registration system), and now your queries will hold all data.  Then afterwards, map them to the derived objects  (I made my own iqueryable mapper for it)

**Comment by MattHartz** [comment]
@TomWouters Does that mean some sort of joining table? Like some of the objects try to join on other different tables so I would hate in my query to outer join on a ton of unnecessary tables. Basically I do one pass to get the types, then i run subsequent queries to load the needed data to those types, then remap back to the base type.  That's the best way I see atm.

**Comment by TomWouters** [comment]
@MattHartz I am very aware of the queryies being built, because they are the result of a mapping.  So only tables and fields which are necessary are being used.  I even have the possibility to apply joining filters for related objects and so on.. so no unnecessary date is being retrieved.  Also for delayed loading, the subqueries can be stored inside an IList/List deferred implementation, which stores it's part of the iqueryable, and only executes it/retrieves data when it's called/used, so even those bases are covered.
It did take some time to be aware at this level of whatever is going on...  But scope wise, the software we're developing is dynamic mapping based, so if you have the mappings that need to be applied, it's quite easy to limit the data requests to whatever is necessary.
