### ISSUE TITLE
AutoMapper GUI VS Extension

### ISSUE THREAD

**Issue by vbjay** [AutoMapper/AutoMapper#2523]
I propose a vs extension that lets us visually generate map code in the current project language.  Think the same idea as relationship designers for databases, but using your classes in your project.

It lets you visually design the maps and see things like, missing properties, mismatched types. The output of the app is the map code. Think the same idea as foreign key relationship gui but classes instead of tables. Since the expressions of AutoMapper are accessible, generating the correct map code in c# or vb would be dead simple.

**Comment by jbogard** [comment]
Sounds like a great startup idea! I look forward to your first round of funding ;)

**Comment by vbjay** [comment]
LMAO!  I just had the brain flash.  Had to get the idea out there.  I am
thinking about it being a personal project to make it happen.
