### ISSUE TITLE
Profiles and RecognizePrefixes with instance mapper

### ISSUE THREAD

**Issue by krisnds** [AutoMapper/AutoMapper#2524]
Similar to https://github.com/AutoMapper/AutoMapper/issues/421,

I am not able to get RecognizeDestinationPrefixes to work in a profile using the instance mapper (with dependency injection in my solution). What is odd is that AssertConfigurationIsValid() does not complain right after configuration, but when I later actually try the mapping in my code, it throws the "Unmapped members were found" exception. Other mappings that are not reliant on RecognizeDestinationPrefixes  work fine.

    public class MyProfile : Profile
    {
        public MyProfile() 
        {
            RecognizeDestinationPrefixes("pre_");
            CreateMap<A, B>();
         }
      }
 
    public static class AutoMapperConfig
    {
        public static MapperConfiguration ConfigureMappings()
        {
            try
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.AddProfile<MyProfile>();
                });
                config.AssertConfigurationIsValid();
                return config;
            }
            catch (Exception ex)
            {
            }
            return null;
        }
    }

Later in the code...
            var dest= mapper.Map<A, B>(src);
=> throws "Unmapped members were found" exception 

I also tried putting RecognizeDestinationPrefixes("pre_") outside of the profile, before calling cfg.AddProfile<MyProfile>() but that doesn't work either.

AutoMapper version 6.2.2
.NET 4.6.1

```

**Comment by lbargaoanu** [comment]
See #2079.

**Comment by krisnds** [comment]
Thank you!!! I just needed to add the new[] when adding the prefixes!
