### ISSUE TITLE
MapFrom with static function inside does not always work properly

### ISSUE THREAD

**Issue by ilya-git** [AutoMapper/AutoMapper#2526]
I use a MapFrom with a call to a static function inside that takes a string parameter. When the passed parameter is null, then mapping does not occur, it's just ignored. There is no exception or anything it's just "skipped". This worked in version 6.1.1 and stopped working in 6.2.0 and is still not working. I guess it has something to do with the change of interface from Func to Expression<Func>. There are a number of things that can help: accepting object instead of string, casting string to string (which is kind of stupid), removing static from the method, using ResolveFrom. I don't really know if the ResolveUsing is meant for such thing and it was wrong to use MapFrom? If that is the case, so what is the difference between ResolveUsing and MapFrom, or otherwise this looks like a hidden breaking change.

```csharp
class Program
{
    static void Main(string[] args)
    {
        var configuration = new MapperConfiguration(c => { c.AddProfile<AutoMapperProfile>(); });
        var mapper = configuration.CreateMapper();

        var foo = new Foo {Text = null};
        var bar = mapper.Map<Foo, Bar>(foo);

        Console.WriteLine(bar.Text);
        Console.ReadLine();
    }
}

public class Foo
{
   public string Text { get; set; }
}

public class Bar    
{
    public string Text { get; set; }
}
```

### Mapping configuration

```csharp
public class AutoMapperProfile : Profile
{
    public AutoMapperProfile()
    {
        CreateMap<Foo, Bar>().ForMember(f => f.Text, o => o.MapFrom(b => Transform(b.Text)));
    }

    private static string Transform(string text)
    {
       return text + " test";
    }
 }
```

### Version: 6.2.0
Version 6.1.1 works fine, it seems that adding the expression broke it.

### Expected behavior

Static and non static methods should not differ

### Actual behavior

When string null is passed to a static method, it is being ignored/nothing happens. I.e. mapping does not occur, when string is not null or method is not static, everything works as expected.

### Steps to reproduce

Run the example program with given profile

**Comment by lbargaoanu** [comment]
Yes, that's by design. Just switch to ResolveUsing.

**Comment by lbargaoanu** [comment]
If you don't use ProjectTo you can switch to ResolveUsing, it's more flexible, you get more control. MapFrom is more like the built in mapping.

**Comment by ilya-git** [comment]
Thanks for answer, none of those 2 offer any performance benefit over the other either I assume?

**Comment by lbargaoanu** [comment]
It all depends on what your code does. The idea is that MapFrom is for simple and quick stuff and ResolveUsing for the rest. But if the MapFrom is a method call, there is no difference.

**Comment by ilya-git** [comment]
I see, thank you!
