### ISSUE TITLE
Automapper doesn't report property mapping error

### ISSUE THREAD

**Issue by zhyy2008z** [AutoMapper/AutoMapper#2528]
Please forgive me for my poor English!

### Source/destination types

Base Types:
```cssharp
        public class Request<T>
        {
            public T MyProperty { get; set; }
        }
        public class ViewModel
        {
            public int A { get; set; }
            public int[] B { get; set; }
        }
        public class DTO
        {
            public int A { get; set; }
            public int B { get; set; }
            public int C { get; set; }
            public int D { get; set; }
        }
```

Source Type：
```csharp
Request<ViewModel>
```
Destination Type：
```csharp
Request<DTO>
```
### Mapping configuration

```csharp
Mapper.Initialize(config => { });
```

### Version: 6.2.1-6.2.2
version 6.2.0 has my expected hehavior!

### Expected behavior

Throw an exception that missing properties and have wrong types.

### Actual behavior

Success mapped, and every property value is 0.

### Steps to reproduce

```csharp
            var sourceProperty = new ViewModel();
            sourceProperty.B =new int[] { 11111 };
            var source = new Request<ViewModel>() { MyProperty = sourceProperty };
            var target = Mapper.Map<Request<ViewModel>, Request<DTO>>(source);
```

**Comment by lbargaoanu** [comment]
Set CreateMissingTypeMaps to false.

**Comment by zhyy2008z** [comment]
Should  it report that property B have the wrong mapping type?

**Comment by lbargaoanu** [comment]
Maybe I misunderstood. If you want validation for the automatically created map, then I'm not sure you can do that when mapping ```Request```. But it does work when mapping the ViewModel and DTO. See [this](http://docs.automapper.org/en/stable/Inline-Mapping.html).

**Comment by lbargaoanu** [comment]
@jbogard 6.2.0 does throw as @zhyy2008z said.

**Comment by PeymanGhadiri** [comment]
I have the same issue

**Comment by lbargaoanu** [comment]
PR welcome.
