### ISSUE TITLE
Unrelated DateTime property throws string format ex

### ISSUE THREAD

**Issue by bigteejay** [AutoMapper/AutoMapper#2529]
### Source/destination types

```csharp
// Source
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleApp1.ViewModels
{
    public class RegistrationViewModel
    {
		[Required]
		[Display(Name = "Organization")]
		public string OrganizationName { get; set; }

		public List<string> Organizations { get; set; }

		[StringLength(20, MinimumLength = 1)]
		public string Gender { get; set; }

		[Required]
		[Display(Name = "Month")]
		public string BirthdayMonth { get; set; }

		[Required]
		[Display(Name = "Day")]
		public int BirthdayDay { get; set; }

		[Required]
		[Display(Name = "Year")]
		public int BirthdayYear { get; set; }

		[Required]
		public int Experience { get; set; }

		[Required]
		public string Ethnicity { get; set; }
	}
}


// Dest
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleApp1.Models
{
	public class RegistrationData
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int Id { get; set; }

		[Required]
		public Guid UserId { get; set; }

		[Required]
		public string OrganizationName { get; set; }

		public string Gender { get; set; }

		[Required]
		[DataType(DataType.Date)]
		public DateTime Birthday { get; set; }

		[Required]
		public int Experience { get; set; }

		[Required]
		public string Ethnicity { get; set; }

		[Required]
		public DateTime RegistrationDate { get; set; } = DateTime.UtcNow;
	}
}

```

### Mapping configuration

```csharp
			Mapper.Initialize(config =>
			{
				config.CreateMap<RegistrationData, RegistrationViewModel>().ReverseMap();
			});
```

### Version: x.y.z

Introduced between versions v6.0.2 and v6.1.0

### Expected behavior

I expect the mapping to occur successfully (as it does in earlier versions, or if I remove the unrelated code and use a more recent version.)

### Actual behavior

System.FormatException: 'Input string was not in a correct format.'

### Steps to reproduce

1. Clone https://github.com/bigteejay/MapperCoreStringEx
2. Compile, run, exception here, https://github.com/bigteejay/MapperCoreStringEx/blob/ee3299dcfdbca6ffdc66515cdab580acfdba1239/ConsoleApp1/Program.cs#L29
3. Edit (comment out) these lines, https://github.com/bigteejay/MapperCoreStringEx/blob/ee3299dcfdbca6ffdc66515cdab580acfdba1239/ConsoleApp1/Models/RegistrationData.cs#L21, https://github.com/bigteejay/MapperCoreStringEx/blob/ee3299dcfdbca6ffdc66515cdab580acfdba1239/ConsoleApp1/Models/RegistrationData.cs#L23
4. Compile, run, no issue
5. With original source (L21-23 **not** commented out), lower referenced version of AutoMapper to v6.0.2 or earlier, and it will again run without issue.

**Comment by lbargaoanu** [comment]
The same cause as #2482.

**Comment by bigteejay** [comment]
For any who may end up here, the answer is [here](http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html#customizing-reverse-mapping).  As of AutoMapper v6.1 it will flatten/unflatten fields that aren't in from/to when `ReverseMap()` is also used.  The fix is to just duplicate the mapping config with one for each direction.
