### ISSUE TITLE
Currently is impossible to have CreateMapper create anything other than IMapper

### ISSUE THREAD

**Issue by tessierp** [AutoMapper/AutoMapper#2530]
Hi,

At the moment there is no way to create our own customer mapper since the MapperConfiguration's CreateMapper doesn't support the custom creation of an interface that inherits from IMapper. This would be ideal in the case you want to do a modular design, using Autofac for example, where you define your own customer MapperConfiguration, that loads its own Profiles and creates its own interface which is only known inside a module.

At the moment, we are forced to load all profiles in all of the application and to recreate the MapperConfiguration anywhere we would have a module.

Would it be possible to overload CreateMapper by allowing the passage of a Template interface that would inherit from IMapper, i.e CreateMapper<T>() where T: IMapper ?

**Comment by lbargaoanu** [comment]
You can have a MapperConfiguration by module and expose any interface you want.

**Comment by jbogard** [comment]
Right and for DI you probably shouldn’t be using CreateMapper itself. Just
use the concrete type.

**Comment by tessierp** [comment]
In order to make the module in question more efficiently testable, calling CreateMapper and getting an interface (in this case IMapper since there is no other option) is that we want.

Also, I would like you to consider these 2 code sequences, both of which you can easily find search 👍 

Code sequence 1:

`public class MapperInstaller : Module {
    protected override void Load(ContainerBuilder builder) {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        builder.RegisterAssemblyTypes(assemblies)
            .Where(t => typeof(Profile).IsAssignableFrom(t) && !t.IsAbstract && t.IsPublic)
            .As<Profile>();

        builder.Register(c => new MapperConfiguration(cfg => {
            foreach (var profile in c.Resolve<IEnumerable<Profile>>()) {
                cfg.AddProfile(profile);
            }
        })).AsSelf().SingleInstance();

        builder.Register(c => c.Resolve<MapperConfiguration>()
            .CreateMapper(c.Resolve))
            .As<IMapper>()
            .InstancePerLifetimeScope();
    }
}`

Sequence code sequence : 
`public class MyModule : Module
{
	protected override void Load(ContainerBuilder builder)
	{
		builder.RegisterType<MyDtoEntityMappingProfile>();
		builder.Register(context =>
		{
		    var profile = context.Resolve<MyDtoEntityMappingProfile>();
		    var config = new DtoEntityMapperConfiguration(x =>
		    {
		            x.AddProfile(profile);
		    });

		    return config;
		})
		.SingleInstance()
		.AsSelf();

		builder.Register(tempContext =>
		{
		    var ctx = tempContext.Resolve<IComponentContext>();
		    var config = ctx.Resolve<DtoEntityMapperConfiguration>();
		    config.
		    return config.CreateMapper<IDtoEntityMapper>();
		}).As<IDtoEntityMapper>()
	}
}`

In the first piece of code, lets imagine you have multiple modules placed in different libraries that perform each a different task, with their own profiles.  If we look at the first sequence of code which is done by many everywhere with slight variations but is currently the only way, you could end up traversing  your assemblies many times and recreating MapperConfiguration and reinjecting it. 

Now for the second piece of code, again we are in a scenario with multiple  modules that needs to define their own profile. Keep in mind here I simplified and only using 1 profile but there could be more. Each would have their own mapper configuration and mapper interface. The advantage here is you load per module exactly what you need without having this responsibility fall back to some other component (the application), or to load all the assemblies. Furthermore, your own module will consume a very specific Mapper that accomplishes the job needed. In this approach  you have separation of concerns and your customize each module to do something very specific.

All I ask is that you consider adding the extra flexibility of having CreateMapper return a specific interface. I tried to do it by having an interface inherit from IMapper but Autofac simply will not have it.

**Comment by lbargaoanu** [comment]
In your first example, each module should add only the profiles it needs.

**Comment by tessierp** [comment]
It was an example taken from the net and it is beside the point. And also, if that piece of code would load only the profiles it needs, once it hits the second module which would do the same thing, the "new MapperConfiguration" would wipe out what was done previously. Hence, this is the only way to do it to get all the profiles found everywhere which is very inefficient but there is no other way at the moment. The solution is the second piece of code.

**Comment by lbargaoanu** [comment]
You can either have one configuration per app component or you can have a global one. How you achieve that with Autofac is a question for another forum.

**Comment by tessierp** [comment]
So I suppose this means there is no chance my proposal will be implemented in a future version.

Thanks anyways.

**Comment by jbogard** [comment]
No the CreateMapper method is merely a convenience. You want to have
separate named MapperConfiguration instances.

**Comment by tessierp** [comment]
This is actually what I did but wanted to declare my own Mapper derived from IMapper to pass around. However that didn't work because the config returns IMapper which Autofac declines.

I will actually trying something different by passing the configuration and have a custom interface and have my configuration referencing it to create the mapper. That may be a solution that will work.

Thanks.
