### ISSUE TITLE
Mapping of SubClass-Properties defined via ForAllMaps fails

### ISSUE THREAD

**Issue by glatzert** [AutoMapper/AutoMapper#2534]
I got a case where Mapping of some properties of a subclass will fail.

Since it started with a StackOverflow querstion (for Reference: https://stackoverflow.com/questions/48769492/map-properties-by-nameing-convention?noredirect=1#comment84540558_48769492), I created a GIST:
https://gist.github.com/anonymous/511a1b69b795aa2bc7e7cd261fcb98b1

Despite the commenter telling it works for him, we could not get it to work on different machines here.
The AutoMapper Version affected was 6.2.2 on .NET Core 2.0 as well as .NET 4.6.2

**Comment by lbargaoanu** [comment]
It only fails on .NET Core, that's why it worked for me.

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by glatzert** [comment]
A sorry, i was not aware, that you are contributor and wanted to bring a possible bug to attention here

**Comment by glatzert** [comment]
The myget build does not change the behavior. I think this is still a valid bug.
Also it will fail independently of the targeted framwork.

**Comment by lbargaoanu** [comment]
What can I say, I don't see it. Make a PR with a failing test.

**Comment by glatzert** [comment]
Well, I forked the Autmapper, looked into the testprojects, created a ForAllMembers-Integration Test, where it .. worked .. if you like, I'll still provide the PR.

So appearantly that bug was already fixed.
BUT - if I remove all Dlls from Automapper from my Project and reinstall it via myget, it'll still fail.
If I build Automapper myself and copy the dll over to my Project to reference that one - it'll work.

Now I'm a little confused, as well as a little embarrased for wasting your time.

**Comment by lbargaoanu** [comment]
:) Well, weirder things have happened. You can always check the AM version and location in the modules window. The test has to fail one some platform in order to be useful :) But you can create the PR and if the test passes, just close it.

**Comment by glatzert** [comment]
Then I'll just remove my fork - I don't see it being useful in that case.
Do you think we might get a "6.2.3" myGet Prerelease? 👼

**Comment by lbargaoanu** [comment]
The MyGet build is based on master, so you can use the latest.

**Comment by glatzert** [comment]
Now I see, where I should have watched a littlebit better - It didn't use the myget source, it just went to nuget and I did not read careful enough to see, that it ignored the source parameter.
Seems that, if you do it right (dotnet add package AutoMapper --source ..myget.. --version 6.2.2-cli-* ) it will work as you described.
