### ISSUE TITLE
How do I correctly use EF Core with AutoMapper ProjectTo and Unions?

### ISSUE THREAD

**Issue by philcarbone** [AutoMapper/AutoMapper#2537]
Also posted on Stackoverflow here: 
https://stackoverflow.com/questions/48847744/how-do-i-correctly-use-ef-core-with-automapper-projectto

My Setup
-------

 - ASP.NET Core 2.0
 - EntityFrameworkCore 2.0.1
 - AutoMapper 6.2.2

----------

Problem
-------

I have a project with a DTO called `PersonDetail` and an Entity called `Person`. 
When I call 

    db.People.Where(p => p.FirstName == "Joe").Union(db.People.Where(p => Age > 30)).ProjectTo<PersonDetail>(mapperConfig).ToList(); 

I do not get the `PersonDetail` DTOs and Entity Framework (Core) throws an exception with the message:

> ArgumentException: The input sequence must have items of type 'Test.Module.Entities.Person', but it has items of type 'Test.Module.Dtos.PersonDetail'.

----------

Example without the problem
---------------------------

When I run the code:

     db.People.Where(p => p.FirstName == "Joe").Union(db.People.Where(p => Age > 30)).ToList(); 

I get the `Person` entities with no exceptions.

----------

The Execution Plans
---------------------------

Here is a working plan (with a union):
> {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable\`1[Test.Module.Entities.Person]).Where(entity => ((entity != null) And ((63ed0ebd-2c02-4496-ac8d-b836cbf13259 == entity.CreatedBy) Or (393a6bb0-b437-4664-beb0-6800f509451b == entity.CreatedBy)))).Union(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Test.Module.Entities.Person]))}

Now here is the same plan but with automapper projections too: 

> {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable\`1[Test.Module.Entities.Person]).Where(entity => ((entity != null) And ((63ed0ebd-2c02-4496-ac8d-b836cbf13259 == entity.CreatedBy) Or (393a6bb0-b437-4664-beb0-6800f509451b == entity.CreatedBy)))).Union(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Test.Module.Entities.Person])).Select(dto => new PersonDetail() {FirstName = dto.FirstName, LastName = dto.LastName, Deleted = dto.Deleted, Age = dto.Age, CreatedUtc = dto.CreatedUtc, CreatedBy = dto.CreatedBy, Id = dto.Id, RecordVersion = dto.RecordVersion, DisplayLabel = ((dto.FirstName + " ") + dto.LastName)})}

----------

Note:
-----

I'm only calling ToList to reduce this problem to it's smallest form. I understand that this doesn't seem like I need to use ProjectTo in this example. In my actual code, we are using OData and we need the final result to be a projected query with the DTOs as Queryable objects. I also understand that this Union is not really a good union example, bu again, just for simplification of the Union problem.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by jbogard** [comment]
Also you don’t need the AsNoTracking with projections.

**Comment by philcarbone** [comment]
@jbogard  Thanks for the advice on the AsNoTracking. @lbargaoanu I did some more investigation and I was mistaken, my query did have other stuff being applied to it. After the advice on StackOverflow to look at the ExecutionPlan I was able to see that. The issue seems to be when there is a Union.

Here is a working plan:
> {System.Collections.Generic.List`1[Test.Module.Entities.Person].Select(dto => new PersonDetail() {FirstName = dto.FirstName, LastName = dto.LastName, Deleted = dto.Deleted, Age = dto.Age, CreatedUtc = dto.CreatedUtc, CreatedBy = dto.CreatedBy, Id = dto.Id, RecordVersion = dto.RecordVersion, DisplayLabel = ((dto.FirstName + " ") + dto.LastName)})}

Now here is the same plan but with a union too: 

> {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable\`1[Test.Module.Entities.Person]).Where(entity => ((entity != null) And ((9b3ee07d-717b-43d8-a5c8-3b0a617f7411 == entity.CreatedBy) Or (1a591861-3ef9-48e1-908d-a94ffc2e37e0 == entity.CreatedBy)))).Union(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Test.Module.Entities.Person])).Select(dto => new PersonDetail() {FirstName = dto.FirstName, LastName = dto.LastName, Deleted = dto.Deleted, Age = dto.Age, CreatedUtc = dto.CreatedUtc, CreatedBy = dto.CreatedBy, Id = dto.Id, RecordVersion = dto.RecordVersion, DisplayLabel = ((dto.FirstName + " ") + dto.LastName)})}

**Comment by lbargaoanu** [comment]
If it works with EF6 then I'm afraid it's an EF Core issue, otherwise  give us a repro and we'll look into it.

**Comment by philcarbone** [comment]
Ok, that's cool. So I should open an issue in the EF Core repo? 

I can post that link back here if anyone else runs into this. I appreciate the help!

**Comment by philcarbone** [comment]
Issue opened with the EntityFrameworkCore project: https://github.com/aspnet/EntityFrameworkCore/issues/11033

**Comment by philcarbone** [comment]
It does work in EF6, by the way

**Comment by philcarbone** [comment]
Just an FYI - This was an EF Core bug and it has been fixed in EF Core 2.1 https://github.com/aspnet/EntityFrameworkCore/issues/11033
