### ISSUE TITLE
Expression Projection with different types

### ISSUE THREAD

**Issue by HRasch** [AutoMapper/AutoMapper#2538]
### Source/destination types

```csharp
// Put your source/destination types here
public class Model
{
	public Guid? Id { get; set; }
	public MyString FullDescription { get; set; }
	public MyString ShortDescription { get; set; }
}

public class Dto
{
	public Guid? Id { get; set; }
	public string FullDescription { get; set; }
	public string ShortDescription { get; set; }
}
```
### Custom Struct type

```csharp
public struct MyString : IComparable, IConvertible
{
	private string value;
	private bool isNull;

	public MyString(string value)
	{
		this.isNull = string.IsNullOrEmpty(value);
		this.value = value ?? string.Empty;
	}

	public string Value
	{
		get
		{
			if (IsNull || value == null)
				return string.Empty;
			return value;
		}
		set
		{
			if (Value == value && !IsNull)
				return;

			if (string.IsNullOrEmpty(value) && !isNull)
			{
				isNull = true;
			}
					
			this.value = value ?? string.Empty;
		}
	}

	public bool IsNull
	{
		get
		{
			return isNull;
		}
		set
		{
			if (isNull == value) return;
			isNull = value;
		}
	}

	public static implicit operator MyString(string a)
	{
		return new MyString(a);
	}

	public static implicit operator string(MyString a)
	{
		return a.Value;
	}

	public static bool operator ==(MyString a, MyString b)
	{
		return a.Value == b.Value;
	}

	public static bool operator ==(MyString a, string b)
	{
		return a.Value == b;
	}

	public static bool operator ==(string a, MyString b)
	{
		return a == b.Value;
	}

	public static bool operator !=(MyString a, MyString b)
	{
		return a.Value != b.Value;
	}

	public static bool operator !=(MyString a, string b)
	{
		return a.Value != b;
	}

	public static bool operator !=(string a, MyString b)
	{
		return a != b.Value;
	}

	public static bool operator <(MyString a, MyString b)
	{
		return a.CompareTo(b) < 0;
	}

	public static bool operator >(MyString a, MyString b)
	{
		return a.CompareTo(b) > 0;
	}

	public static bool operator <=(MyString a, MyString b)
	{
		return a.CompareTo(b) <= 0;
	}

	public static bool operator >=(MyString a, MyString b)
	{
		return a.CompareTo(b) >= 0;
	}

	public override int GetHashCode()
	{
		return this.Value.GetHashCode();
	}

	public override bool Equals(object obj)
	{
		if (obj is MyString)
			return this == (MyString)obj;
		if (obj is string)
			return this == (MyString)((string)obj);
		return false;
	}


	public int CompareTo(object obj)
	{
		if (!(obj is MyString))
			return -1;
		return CompareTo((MyString)obj);
	}

	public TypeCode GetTypeCode()
	{
		if (this.IsNull)
			return TypeCode.String;
		return this.Value.GetTypeCode();
	}

	public bool EqualsValue(string obj)
	{
		return this.Equals((object)obj);
	}

	public override string ToString()
	{
		if (IsNull)
			return string.Empty;
		return Value;
	}

	public bool ToBoolean(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToBoolean(provider);
	}

	public byte ToByte(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToByte(provider);
	}

	public char ToChar(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToChar(provider);
	}

	public DateTime ToDateTime(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToDateTime(provider);
	}

	public decimal ToDecimal(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToDecimal(provider);
	}

	public double ToDouble(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToDouble(provider);
	}

	public short ToInt16(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToInt16(provider);
	}

	public int ToInt32(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToInt32(provider);
	}

	public long ToInt64(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToInt64(provider);
	}

	public sbyte ToSByte(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToSByte(provider);
	}

	public float ToSingle(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToSingle(provider);
	}

	public string ToString(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToString(provider);
	}

	public object ToType(Type conversionType, IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToType(conversionType, provider);
	}

	public ushort ToUInt16(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToUInt16(provider);
	}

	public uint ToUInt32(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToUInt32(provider);
	}

	public ulong ToUInt64(IFormatProvider provider)
	{
		return ((IConvertible)this.Value).ToUInt64(provider);
	}
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(c =>
{
	c.CreateMap<Model, Dto>();
});

config.AssertConfigurationIsValid();

var mapper = config.CreateMapper();

var source = new List<Model> {
	new Model
	{
		Id = Guid.NewGuid(),
		ShortDescription = "Model 1",
		FullDescription = "Deluxe Foo Manufactured by Yoyodyne, Inc.",
	},
	new Model
	{
		Id = Guid.NewGuid(),
		ShortDescription = "Model 2",
		FullDescription = "Deluxe Foo Manufactured by Yoyodyne, Inc.",
	}
};

var source2 = source.AsQueryable().UseAsDataSource(mapper).For<Dto>();
```

### Expected behavior
The datasource should allow queries to the injected query provider.

### Actual behavior
An ArgumentException is thrown because automapper tries to assign a property of type MyString to a Property of type String

### Steps to reproduce

```csharp
try
{
	var output = source2.ToList(); // => Success
  	var output2 = source2.Select(x => x.ShortDescription).ToList(); // Fail
}
catch (Exception ex)
{
	ex.ToString();
}
```

I tried a little bit around, and my best solution is to change ExpressionMapper.MappingVisitor.VisitMember 

from
```csharp
if (propertyMap.CustomExpression != null)
         return propertyMap.CustomExpression.ReplaceParameters(replacedExpression);
```
to
```csharp
if (propertyMap.CustomExpression != null)
{
         replacedExpression = propertyMap.CustomExpression.ReplaceParameters(replacedExpression);

         if (!node.Type.IsAssignableFrom(replacedExpression.Type))
         {
                    replacedExpression = Convert(replacedExpression, node.Type);
         }

         return replacedExpression;
}
```

but i think there's a better solution respecting all registered propertyMaps / projections. Maybe I did also something wrong with the registration of the projection?

**Comment by lbargaoanu** [comment]
cc @BlaiseD

**Comment by BlaiseD** [comment]
This should work as a workaround. Replace:
```
var config = new MapperConfiguration(c =>
            {
                c.CreateMap<Model, Dto>();
            });
```
with:
```
var config = new MapperConfiguration(c =>
            {
                c.CreateMap<Model, Dto>()
                .ForMember(d => d.ShortDescription, opt => opt.MapFrom(s => s.ShortDescription.Value));
            });
```

@lbargaoanu BTW UseAsDataSource does  not use XpressionMapper.  @TylerCarlson1   knows more about UseAsDataSource.  XpressionMapper does have a related problem - I'll open an issue and PR and thanks for the cc.

**Comment by lbargaoanu** [comment]
@BlaiseD I keep forgetting :) Sorry about that and thanks.

**Comment by lbargaoanu** [comment]
@HRasch A PR is welcome :)

**Comment by HRasch** [comment]
@lbargaoanu I fear I'm not a contributor yet, so i'm not allowed to push my PR or to create a new branch :-(. But in the end it's just one line of code to change. The suggested conversion using

`
replacedExpression = ExpressionFactory.ToType(replacedExpression, node.Type);
`
does the same Job. 👍

**Comment by lbargaoanu** [comment]
There is a guide somewhere on github about how to start a PR. It's not difficult :)

**Comment by HRasch** [comment]
Here are my latest infos about the mapping problem. It seems, this kind of conversion has never been testet. 

The background for my issue is that i try to create an odata-provider for a custom datasource (based on webapi, odata, restier). Most of the datatypes in my custom datasource are definied with custom struct types, as mentioned. The idea of mapping the odata-query directly to my custom datasource sounds fantastic to me, and I think AutoMapper is the right tool to translate the queries.

This task should not be to complicated, cause Automapper already works perfect, if the source and destination-properties have the same type.

My prototype can currently load data from my source and convert it to the odata-result. Also the select-parameter works correct after my last commit.

**BUT: There are much more cases, where this change is not enough!**

I updated my fork with my latest changes. There are Unit-Tests that fail, because I couldn't figure out how to handle them in the correct way.

These failing tests are not existing tests, but new tests with custom struct types. These Test-Cases are relevant, because OData builds projections on the select-param.

AutoMapper ignores the use case that the propert-types may differ. I spend 2 days to find out how the ExpressionMapper.MappingVisitor.VisitMember-Method must be modified to meet all requirements, but i think it's not possible to have a general solution, cause the visitor sometimes expect that a not-converted expression is returned (of course, the current version is not aware of different struct-types and implicit casts)

My changes on the VisitMember-Method presume that the node-expression defines the type that is expected from outside, so the return-type should be converted to this type. This is not correct in all cases. The existing code breaks, if I always return a converted expression. Can someone please help me to 

- find out, when the return type should be changed
- what's the best way to convert the expression to the return type (have a suggest in my code)
- extend the functionality to full support of odata-parameters $select, $filter, $orderby

My defined Unit-Tests may help to understand what I'm try'in to achieve.

**Comment by lbargaoanu** [comment]
Could try mapping expressions instead of UseAsDataSource, so you could use the new XpressionMapper? It also supports mapping [IQueryable](https://github.com/AutoMapper/AutoMapper/blob/25c2429b467717b7469ab3490648830a9deb411b/src/UnitTests/XpressionMapperTests.cs#L387).
