### ISSUE TITLE
Automapper with Tuples

### ISSUE THREAD

**Issue by empitegayan** [AutoMapper/AutoMapper#2545]
I'm Trying to map object in to tuple which returns three objects i have added configuration as below

```
CreateMap<JobDto, (Job Job, JobDetail JobDetail, Location Location)>()
    .ForMember(des => des.Job,
        exp => exp.MapFrom(src => new Job
        {
            UserId = src.UserId,
            CategoryId = src.CategoryId,
            Title = src.Title,
            Description = src.Description
        }))
    .ForMember(des => des.JobDetail, exp => exp.MapFrom(src => new JobDetail
    {
        Duration = src.Duration,
        DurationType = src.DurationType,
        PayAmount = src.Amount,
        PayType = src.PayType
    }))
    .ForMember(des => des.Location, exp => exp.MapFrom(src => new Location
    {
        Latitude = src.Latitude,
        Longitude = src.Longitude,
        Address = src.Address
    })).ReverseMap();
```

but when I try to map object:

`var map = _mapper.Map<(Job Job, JobDetail JobDetail, Location Location)>(obj);`

> Unmapped properties: Item1 Item2 Item3
> 
> at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable1
>   typeMaps)    at lambda_method(Closure , JobDto , ValueTuple3 , ResolutionContext ) at lambda_method(Closure , Object , Object , ResolutionContext ) at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)

and then i tried with this

```
(Job Job, JobDetail JobDetail, Location location) map = (null, null,null);
var newMap = _mapper.Map(obj, map);
```

worked perfectly.. why?

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by empitegayan** [comment]
@lbargaoanu  thanks i will try
