### ISSUE TITLE
Understanding Mapper.Initialize and CreateMap in Automapper(6.2.2)

### ISSUE THREAD

**Issue by PrithviPalSingh** [AutoMapper/AutoMapper#2547]
Hi Team,

I am writing to understand Mapper.Intialize and CreateMap related changes in Automapper version 6.2.2.

I am using Automapper 6.2.2 and Mapping **CityDtO** to **City** entity class. Below are their respective definitions:

public class CityDto
{
        
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }        
}

public class City
{
  
       public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }        
}

In Startup class i am initializing Mapper just once. I have not specified any CreateMap function call and configuring initialize as mentioned below:
**Mapper.Initialize(cfg => { });**

At my presentation layer, i am calling Map function as:
**var city = _cityInforepository.GetCity();
var cityResult = Mapper.Map<CityDto>(city);**

And to my surprise cityResult was successfully populated and i was able to retrieve the repespective city info.

![image](https://user-images.githubusercontent.com/22608038/36838253-ae0e7264-1d79-11e8-80fd-b0fdae80d84a.png)

I am puzzled that without even calling CREATEMAP over CITYDTO and CITY classes in **Startup class** how is this mapping possible?

Are there some new amendments in Automapper which i am not aware of? Please guide.

Apart from generic updates and changes, explanation from this specific scenario will be helpful and appreciated.

Regards,
Prithvi Pal Singh

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/stable/Inline-Mapping.html
