### ISSUE TITLE
Tweak Exception Message When Map Not Declared

### ISSUE THREAD

**Issue by markolbert** [AutoMapper/AutoMapper#2548]
I'm learning AutoMapper, and am rapidly coming to appreciate it's power and simplicity. But I've run into a number of problems where changing the error message that gets produced would save time, by pointing people in the right direction.

Here's the situation: when you call Map() on a defined mapper, but the source and/or destination are not "known" to AutoMapper -- meaning no map was defined in, say, a Profile-derived class -- you get an exception that lists all the public properties of the destination object that AutoMapper doesn't know how to map.

But the real problem is that no map was ever defined. So, of course, there's no detail on how to map the individual destination properties.

If, instead, the error message said something like "no map was defined for the relationship SourceObject -> DestinationObject", that would, I think, point someone more directly at the problem, and hence the solution (i.e., define a mapping).

It's possible that this problem only occurs when the classes involved are known to AutoMapper, but in different contexts (i.e., they are referenced in other mappings). That was the case in my situation. But the change would still be beneficial, I think.

**Comment by lbargaoanu** [comment]
PR welcome.

**Comment by lbargaoanu** [comment]
Also, setting CreateMissingTypeMaps to false might help.

**Comment by markolbert** [comment]
Lol! Why close the issue? FWIW, while changing that default might generate a different message, it isn’t at all obvious that one should consider changing the default.

**Comment by jbogard** [comment]
We can't reproduce this. Without some way to reproduce, we can't make it better.

**Comment by lbargaoanu** [comment]
Yes, it is not obvious. As I've said in that issue, it might help to mention in the message that the map was created by AM. If you want to do that, it shouldn't be difficult to change that message.
