### ISSUE TITLE
Is there a way to initialize the mapper using a collection of IMapperConfigurationExpression?

### ISSUE THREAD

**Issue by CrestApps** [AutoMapper/AutoMapper#2550]
I am trying to use reflection to initialize my automapper on application start up.

I created the following 3 interfaces

```
public interface IMap
{
}

public interface IMapFrom<T> : IMap
{
}

public interface IMapFrom : IMap
{
    void CreateMap(IMapperConfigurationExpression config);
}
```

When the application starts, any class the implements `IMapFrom<T>` I want to register it like so

```
foreach (Type type in types)
{
    if (type.IsGenericType && typeof(IMapFrom<>).IsAssignableFrom(type))
    {
        CreateMap(type.GetGenericArguments()[0], type);
    }
}
```

That above code work great for any object that follows the standard naming conventions. However, for classes that need inline-configuration, I need to be able to write the `IMapperConfigurationExpression` to handle my non-standard mapping configuration. Using reflection, I want to loop over every class the implements `IMapFrom` and for each `IMapperConfigurationExpression` provided by the class, I want to add it to registered instance or pass the `MapperConfiguration` to my `CreateMap` and let it define its own.

The above setup will also allow me to keep my custom mapping directly in the destination class so I can directly change my configuration for that class from with in it instead of having to go to a profiler class to add more configurations.

**Question**
Is there a way to pass a collection of `IMapperConfigurationExpression` to initialize AutoMapper? Or, is there a way I can use `MapperConfiguration` to create the the inline-config for each class?

**Comment by TylerCarlson1** [comment]
I would recommend AddProfiles function call when doing MapperConfiguration.  Then in all the classes you want mapped you can make a private class Based on Profile that does your mapping and you can configure it anyway you like.  AutoMapper will do the reflection to find all Profile types and you can make a base map class that does what `IMapFrom<T>` does and stick it in base classes.

You should be able to achieve your goals with this method, even if it's more lines of code overall.  If you want to just use IMapFrom then you can make a convention to identify and create maps that meet that criteria.

**Comment by CrestApps** [comment]
@TylerCarlson1 that does not sound bad but may be an over kill, don't you think? Instead of simply add my logic in a method, now I have to add a class and each class must inhiret the base class. I am hoping there is a way where I can just call a method on my class to do this.

**Comment by TylerCarlson1** [comment]
well you can just do the IMapFrom as you do now and use profile for more detailed mappings.

Else just cast your type to IMapFrom cast to that and call the config with mapping expression passed in the Configuration method call

**Comment by CrestApps** [comment]
I am struggling in to what object do I pass to my IMapFrom.CreateMap? Also in the implementation method how do I treat current class as destination?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/894412e72e98cb0d6da957b5a5be52f888fc6cd5/src/AutoMapper/Mapper.cs#L50
