### ISSUE TITLE
Xamarin Forms release exception

### ISSUE THREAD

**Issue by stesvis** [AutoMapper/AutoMapper#2551]
I have a Xamarin Forms app (.Net Standard 2.0) and installed AutoMapper, the 6.1.1 version.
In Debug mode everything runs fine.
In Release mode, only in android, I get an exception as soon as I run the app.

### Mapping configuration

```csharp
public MappingProfile()
        {
            AutoMapper.Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<User, UserDTO>().ReverseMap();
            });
        }
```

### Version: 6.1.1
(If i upgrade to 6.2.2 it gives me build errors)

### Expected behavior

It should work without exceptions.

### Actual behavior

I get this exception as soon as the app launches, I assume it happens when it hits the AutoMapper.Mapper.Initialize() method.

> Unhandled Exception:
> 
> System.TypeInitializationException: The type initializer for 'AutoMapper.Mappers.EnumToEnumMapper' threw an exception.

### Steps to reproduce

Start a Xamarin Forms application, set the android project as startup project and initialize AutoMapper, then run the app in release mode.

**Comment by lbargaoanu** [comment]
You have the answer in that other issue. If things are not clear, you should ask on SO or another Xamarin forum. The latest doesn't work with Xamarin, see https://github.com/xamarin/Xamarin.Forms/issues/1380.
