### ISSUE TITLE
Nullable Type conversion

### ISSUE THREAD

**Issue by matthiaszoellner** [AutoMapper/AutoMapper#2554]
### Source/destination types

```csharp

    class SourceContainer
    {
        public SourceItem MyItem { get; set; }
    }

    class SourceItem
    {
        public long Id1 { get; set; }
        public int Id2 { get; set; }
    }

    class DestContainer
    {
        public int? MyItemId1 { get; set; }
        public int? MyItemId2 { get; set; }
    }
```

### Mapping configuration

```csharp
    var mapper = new AutoMapper.MapperConfiguration(conf =>
    {
        conf.CreateMap<SourceContainer, DestContainer>();
    }).CreateMapper();
```

### Version:
6.2.2

### Expected behavior

When `SourceContainer.MyItem` is `null`, both `DestContainer.MyItemId1` and `DestContainer.MyItemId2` should be `null`.

### Actual behavior

When `SourceContainer.MyItem` is `null`, `DestContainer.MyItemId1` is `0` and `DestContainer.MyItemId2` is `null`.

So the flattening with `long` -> `Nullable<int>` is different from the flattening with `int` -> `Nullable<int>`

### Steps to reproduce

```csharp

var cont = new SourceContainer();
var test = mapper.Map<DestContainer>(cont);

// test.MyItemId1 and test.MyItemId2 should be null

```

**Comment by lbargaoanu** [comment]
Yes, I would workaround it, unless you want to try and fix it yourself. @jbogard This one seems tricky and for little benefit.
