### ISSUE TITLE
Possible regression with inheritance mapping

### ISSUE THREAD

**Issue by justintconroy** [AutoMapper/AutoMapper#2556]
This seems like it's similar to older issues like #842, #948, and #1011. In this case the problem crops up even without EF. See [gist](https://gist.github.com/justintconroy/2f9f1028dde49daaaa216378d69674ba) for an example. I found that this is an issue in versions 6.2.0-6.2.2, but not in 6.1.1.

### Source/destination types
source:
```csharp
IEnumerable<SomeObject>
```
destination:
```csharp
public class CollectionDto<T> where T : class
{
    public int Count => Records.Count;
    public ICollection<T> Records { get; set; }
}

// Some custom attributes here that only apply to
// SomeObjectDto things.
public class SomeObjectCollectionDto : CollectionDto<SomeObjectDto>
{ }

```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap(typeof(IEnumerable<>), typeof(CollectionDto<>))
        .ForMember("Records", opt => opt.MapFrom(src => src));
    cfg.CreateMap<SomeObject, SomeObjectDto>();
 });
```

### Version: x.y.z
 
Affected versions: **6.2.0**, **6.2.1**, **6.2.2**

Version **6.1.1** and earlier do not have this problem.
### Expected behavior

`IEnumerable<SomeObject>` is converted to `SomeObjectCollectionDto`.

### Actual behavior

An exception is thrown when trying to map claiming there's an invalid cast:

```
System.InvalidCastException: 'Unable to cast object of type 'TestAutoMapperInheritanceMapping.CollectionDto`1[TestAutoMapperInheritanceMapping.SomeObjectDto]' to type 'TestAutoMapperInheritanceMapping.SomeObjectCollectionDto'.'
```

### Steps to reproduce
Run the [gist](https://gist.github.com/justintconroy/2f9f1028dde49daaaa216378d69674ba) with any of the affected versions of AutoMapper listed above. Run the same code with version 6.1.1 to see it working as expected.

**Comment by lbargaoanu** [comment]
The old behavior is wrong. You have to tell AM about your destination type at configuration time. For example ```As(typeof(SomeObjectCollectionDto))```, or anything else that works for you.

**Comment by justintconroy** [comment]
That's unfortunate. I'd like it if I could just do one mapping that applied to all the derived types without having to add something for every new type I add. I guess we'll be stuck on 6.1.1 until we have time to update those mappings.

**Comment by lbargaoanu** [comment]
Inline maps are closer to what you want, but I'm not sure you want to go there  :)
