### ISSUE TITLE
Support additive configuration

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2557]
`Mapper.Initialize` in its old form wiped all configuration and applied new. Now it throws an exception. You can do `Mapper.Reset` but that will also wipe all configuration.

The idea is to add a `Mapper.Configure` that will "re-apply" configuration, and instead of wiping what's already there, either replace or apply on top of what is there.

It could either replace type maps/profile maps etc. or it could just use what's already here, but this would let you call `Mapper.Configure` multiple times with the same configuration, helping us get around some of the issues of `services.AddAutoMapper()` without forcing people to have the instance-based version.

**Comment by jbogard** [comment]
Funnily enough this could re-enable `Mapper.CreateMap` for simple scenarios :P

**Comment by lbargaoanu** [comment]
Why even [bother](https://stackoverflow.com/questions/49437212/automapper-inline-mapping-throwing-mapper-not-initialized?s=5|0.0000) with Initialize? :)

**Comment by jbogard** [comment]
I looked into this for about 10 minutes or so. It would not be easy, at all. You'd have to have a set of defaults, then something like Initialize to reset global defaults, perhaps Configure to add new config, and none of the configuration containers really let you do this. You have to instantiate them and then they're configured.

**Comment by jbogard** [comment]
Meh. not worth it. Too confusing.
