### ISSUE TITLE
AutoMapper raises an exception on Projects with COM-Register true attribute

### ISSUE THREAD

**Issue by miracle152004** [AutoMapper/AutoMapper#2559]
Hi,

Visual studio raises an exception in projects with the setting "Register for COM Interop" set to true (i.e. Office Addins).

This issues asks the developer to register AutoMapper using regasm even though AutoMapper does not contain any com interop code. This happen because the .net 4.5 assembly is marked as com visible.

The source for this issue is that the COMVisible attribute is not set in the AssemblyInfo.cs and if the attribute is not explicitly set to false in the AssemblyInfo.cs the compiler will use ComVisible(true) as tje standard and compile the assembly as com visible.

I can provide a PullRequest fixing this issue if that is wished.

Best regards
miracle152004

**Comment by lbargaoanu** [comment]
Yes, please :)
