### ISSUE TITLE
optimize Automapper as class  

### ISSUE THREAD

**Issue by Forever851** [AutoMapper/AutoMapper#2561]
I'm trying to optimize Automapper as the class  so I can lunch it from any other class in the project, but I have an issue once we createMap with dynamic value:

public class CoolMapper
  {
      private static readonly IMapper GenericMapper = new MapperConfiguration(cfg =>
      {
          cfg.CreateMissingTypeMaps = true;
          cfg.DestinationMemberNamingConvention = new LowerUnderscoreNamingConvention();
          cfg.CreateMap<Object1,Object2>(); // here what I'm missing but how i can make the two object dynamic...?
      }).CreateMapper();

      public TDest Convert<TSource, TDest>(TSource source)
      {
          return GenericMapper.Map<TSource, TDest>(source);
      }
  }

So I can access this class by:
var user = new CoolMapper().Convert<Staff, User>(staff);

Any ideas..?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
