### ISSUE TITLE
Dynamic object

### ISSUE THREAD

**Issue by mohsenMohamadi** [AutoMapper/AutoMapper#2565]
hi 
I have a dynamic var with nested object values,
 Use auto mapper for convert to object, 
but dont convert int variable and return all int value with zero
??

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
