### ISSUE TITLE
Error "NU1108: Cycle detected" when trying to add AutoMapper package to .Net Core 2.0 console application

### ISSUE THREAD

**Issue by gfgw** [AutoMapper/AutoMapper#2566]
For testing pusposes I want to add the NuGet package Automapper v6.2.2 to a new console application, targeting .Net Core 2.0. I get the following error message:

> Restoring packages for c:\users\george\ontw\Test\AutoMapper\AutoMapper\AutoMapper.csproj...
NU1108: Cycle detected. 
  AutoMapper -> AutoMapper (>= 6.2.2).
Package restore failed. Rolling back package changes for 'AutoMapper'.
Time Elapsed: 00:00:00.3122113
========== Finished ==========

The only other package installed is Microsoft.NETCore.App v2.0.6.

**Comment by lbargaoanu** [comment]
:) Rename you project to smth other than AutoMapper. It's a NuGet thing.
