### ISSUE TITLE
Support for Role-based mapping?

### ISSUE THREAD

**Issue by Psypher9** [AutoMapper/AutoMapper#2567]
Hello!

I'm curious to know if there are any plans to support role-based mapping through the use of Data Annotations. For an example of what I'm meaning, let's say that I have two roles one being `Instructor` and another being `Student`. I want to keep my ViewModels simply and just need to keep the correct answers from the Student. I'm thinking that I would have the `AnswerViewModel` and `QuestionViewModel` look like this 

```csharp
public class QuestionViewModel
{
    // Other properties
    public List<AnswerViewModel> AnswerSelections { get; set; }
}

public class AnswerViewModel
{
    public QuestionViewModel Question { get; set; }
    public string AnswerSelectionText { get; set; }
    public bool IsCorrect { get; set; }
}
```

Then adding an annotation on the `IsCorrect` property, I'm struggling to come up with a very insightful name right now, but named `[AllowMapOnRole()]`. Then the `AnswerViewModel` would look like this

 ```csharp
public class AnswerViewModel
{
    public QuestionViewModel Question { get; set; }
    public string AnswerSelectionText { get; set; }
    [AllowMapOnRole("Instructor")]
    public bool IsCorrect { get; set; }
}
```

To then only map the property if the user is from that role, and if not, ignoring that property altogether so that someone not in that role could only receive the `Question` and `AnswerSelectionText` properties?

I'm really just interested to know if a feature like this would fit into the scope of AutoMapper and if so, would be helpful to more cases than this example. Thank you!

**Comment by TylerCarlson1** [comment]
You might be able to do this right now with ForAllPropertyMaps and then writing code to check roles as a condition or precondition.

Example Below
```
Mapper.Initialize(cfg =>
            {
                cfg.ForAllPropertyMaps(
                    pm => pm.DestinationProperty.GetCustomAttributes(typeof(AllowMapOnRoleAttribute), true).Any(),
                    (pm, config) =>
                    {
                        var attributeRole = (pm.DestinationProperty.GetCustomAttributes(typeof(AllowMapOnRoleAttribute), true)[0] as AllowMapOnRoleAttribute).Role;
                        config.Condition(o => CurrentUser.Role == attributeRole);
                    });
            });
```

If you need to inject the role you can into the map or projection if it's not some kind of global setting you are able to access.  I honestly don't know much about web roles but you should be able to configure it however you want.

@jbogard might have a better example of how it's implemented in more detail but this is the general concept of what you are asking.

**Comment by lbargaoanu** [comment]
That doesn't seem general enough to be useful and also attributes are not exactly flexible because they are set at compile time.

**Comment by Psypher9** [comment]
Okay, actually both of these comments have been immensely helpful for my understanding of AutoMapper and has gotten me thinking about some different approaches for how to tackle the different role based solutions I need. Thank you both!
