### ISSUE TITLE
Error occurs when mapping ImmutableList<T>

### ISSUE THREAD

**Issue by PeymanGhadiri** [AutoMapper/AutoMapper#2570]
Looks like Automapper cannot map ImmutableList<T> properly.

### Source/destination types

```csharp
public class Foo
{
    public IImmutableList<Bar> Bars { get;private set; }
    
    public Foo(IList<Bar> bars)
    {
        Bars = ImmutableList<Bar>.Empty.AddRange(bars);
    }
}

public class FooDto
{
    public IImmutableList<Bar> FooBars { get;private set; }
    // used for mapping 
    private FooDto()
    {
        FooBars = ImmutableList<Bar>.Empty;
    }
    public FooDto(IList<Bar> bars)
    {
        FooBars = ImmutableList<Bar>.Empty.AddRange(bars);
    }
}

public class Bar
{
    public string Name { get;private set; }

    public Bar(string name)
    {
        Name = name;
    }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.DisableConstructorMapping();
    cfg.CreateMap<Foo, FooDto>()
        .ForMember(d => d.FooBars, o => o.ResolveUsing(s => ImmutableList<Bar>.Empty.AddRange(s.Bars)));
});

var mapper = config.CreateMapper();
```

### Version: 
 Automapper 6.2.0
System.Collections.Immutable 1.4.0

### Expected behavior
Map source to destination properly

### Actual behavior
Error mapping types.

Mapping types:
Foo -> FooDto
Foo -> FooDto

Type Map configuration:
Foo -> FooDto
Foo -> FooDto

Property:
FooBars

inner exception:
Unable to cast object of type 'System.Collections.Generic.List`1[Bar]' to type 'System.Collections.Immutable.IImmutableList`1[Bar]'.
### Steps to reproduce

```csharp
var foo = new Foo(new List<Bar>{new Bar("A"), new Bar("B")});

var dto = mapper.Map<Foo,FooDto>(foo);
```

**Comment by lbargaoanu** [comment]
Yes. You're welcome to add support for it or you can work around it by using the concrete type instead.

**Comment by jbogard** [comment]
It looks like all the immutable collections have [static factory methods to create one](https://msdn.microsoft.com/en-us/library/dn456042(v=vs.111).aspx). To support them, I'd rather not add support to the base library since immutable collections are an additional NuGet package, and it's not in any base framework (.NET, .NET Standard etc.). This would need an additional NuGet package.

**Comment by PeymanGhadiri** [comment]
@lbargaoanu  Thanks for your response. I added the following line to the config and it solved the issue for now.
```
cfg.CreateMap<IImmutableList<Bar>, IImmutableList<Bar>>().ConstructUsing(s => s);
```

 `ResolveUsing` returns the correct value and I expected it to work without the need to the new config but looks like the result of that function gets converted into `List<Bar>` at some point.
Is that a bug or it's by design?

**Comment by lbargaoanu** [comment]
It's by design, but your map doesn't make any sense :) You should create a map from IEnumerable to ImutableList and use ConvertUsing. Then you don't need the resolver anymore.
