### ISSUE TITLE
Question: How to use ForAllMembers to Condition to exclude properties dynamically

### ISSUE THREAD

**Issue by JonPSmith** [AutoMapper/AutoMapper#2571]
I am building a library that uses AutoMapper, and I want to use the same DTO/ViewModel for both a read and a write. I want  to allow the developer to mark some properties as ReadOnly, i.e. the read mapping will fill them in but the Reverse mapping will not copy those properties to the database class.

I did this in a previous library using AutoMapper 4.2.1, but I can't find a way to do the same thing in AutoMapper 6.2.2. 

Here is what I am trying to do with AutoMapper 6.2.2. I am just unit testing at the moment, so the code comes from that

### Source/destination types

```csharp
//.. source DTO
public class WriteAuthorReadOnlyDto
{
    [ReadOnly(true)]
    public int AuthorId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
}
//... destination entity class
public class Author
{
    public int AuthorId { get;  set; }
    public string Name { get;  set; }
    public string Email { get; set; }

    public ICollection<BookAuthor> BooksLink { get; set; }
}
```

### Mapping configuration

```csharp
private IMappingExpression<WriteAuthorReadOnlyDto, Author> IgnoreReadOnlyProperties
    (IMappingExpression<WriteAuthorReadOnlyDto, Author> mappingExpression)
{
    mappingExpression
        .ForAllMembers(x => x.Condition((source, dest, inMember) 
        => Filter(inMember)));
    return mappingExpression;
}

private bool Filter(object member)
{
    // NOTE: The code below does NOT find the ReadOnlyAttribute
    var readOnlyAttr = member?.GetType().GetCustomAttribute<ReadOnlyAttribute>();
    var isReadOnly = readOnlyAttr?.IsReadOnly ?? false;
    return !isReadOnly;
}

//... config taken from unit test, which is shown in full below
    var config = new MapperConfiguration(cfg =>
    {
        IgnoreReadOnlyProperties(cfg.CreateMap<WriteAuthorReadOnlyDto, Author>());
    });
```

### Version: x.y.z
6.2.2

### Expected behavior

I would like it to find the `ReadOnlyAttribute` on the member so I can use that to ignore that property. in AutoMapper 4.2.1 I had the following code

```csharp
public static IMappingExpression<TDto, TEntity> IgnoreMarkedProperties<TDto, TEntity>
    (this IMappingExpression<TDto, TEntity> mappingExpression)
{
    mappingExpression.ForAllMembers(x => x.Condition(mapContext => mapContext.PropertyMap.SourceMember != null &&
           mapContext.PropertyMap.SourceMember.GetCustomAttribute<DoNotCopyBackToDatabaseAttribute>() == null));
    return mappingExpression;
}
```

### Actual behavior

The `Condition` should allow me to know what property in the class I am dealing with so that I can decide what to do (Ideally I would have the property name or PropertyInfo so I could handle cases where the source is null).

### Steps to reproduce

```csharp
[Fact]
public void TestIgnoreReadOnlyProperties()
{
    //SETUP
    var entity = new Author{AuthorId = 1, Name = "Start Name", Email = "me@nospam.com"};
    var config = new MapperConfiguration(cfg =>
    {
        IgnoreReadOnlyProperties(cfg.CreateMap<WriteAuthorReadOnlyDto, Author>());
    });

    //ATTEMPT
    var dto = new WriteAuthorReadOnlyDto { AuthorId = 123, Name = "New Name"};
    var mapper = config.CreateMapper();
    var data = mapper.Map(dto, entity);

    //VERIFY
    data.Name.ShouldEqual("New Name");
    data.AuthorId.ShouldEqual(1);    //THIS FAILS, as the AuthorId is copied
}
```

Any thoughts/suggestions gratefully received

**Comment by lbargaoanu** [comment]
Wouldn't the [IgnoreMap attribute](https://github.com/AutoMapper/AutoMapper/search?utf8=%E2%9C%93&q=ignoremap&type=) help?

**Comment by JonPSmith** [comment]
Nice idea, but the IgnoreMap attribute has go on the destination. I need something that goes on the source. I can control/define what happens on the DTO (destination), but not on the source class.

**Comment by lbargaoanu** [comment]
Try ForAllPropertyMaps.

**Comment by JonPSmith** [comment]
Yep. That works! Thanks for pointing that out.

Can I ask some questions on the `ForAllPropertyMaps` method, as there isn't much documentation on it.
* I assume it applies to all the mapping in a MapperConfiguration - correct? 
* If I build profiles I will need to add it to each profile - correct?

**Comment by lbargaoanu** [comment]
The general logic here is that things set for the MapperConfiguration apply everywhere, but you can override by setting things per profile. So the answers are yes and no :) But do check.

**Comment by JonPSmith** [comment]
OK. I'll do some digging but `ForAllPropertyMaps` looks like a nice solution. I will therefore close this for now.

Thanks for the very quick response - much appreciated.

**Comment by JonPSmith** [comment]
Hi @lbargaoanu,

OK, I checked and `ForAllPropertyMaps` applies the rule to all property maps, **even if they are in completely different configurations**. I though different configurations were separate, but obviously not.

This means I can't use `ForAllPropertyMaps` because I don't want my library to alter any existing usage of AutoMapper that the developer is using. 

So, its back to the drawing board - any other suggestions?

**Comment by lbargaoanu** [comment]
I want to see a test that fails with the latest.

**Comment by JonPSmith** [comment]
The unit test is below
```csharp
[Fact]
public void TestUsingProfileWithIgnoreDoesntAffectOtherProfiles()
{
    //SETUP
    var profile1 = new UnitTestProfile(true);
    profile1.AddWriteMap<WriteAuthorReadOnlyDto, Author>();
    var config1 = new MapperConfiguration(cfg => cfg.AddProfile(profile1));
    var profile2 = new UnitTestProfile(false);
    profile2.AddWriteMap<WriteAuthorReadOnlyDto, Author>();
    var config2 = new MapperConfiguration(cfg => cfg.AddProfile(profile1));

    //ATTEMPT
    var dto = new WriteAuthorReadOnlyDto { AuthorId = 123, Name = "New Name", Email = "youhavechanged@gmail.com" };
    var entity1 = new Author { AuthorId = 1, Name = "Start Name", Email = "me@nospam.com" };
    config1.CreateMapper().Map(dto, entity1);
    var entity2 = new Author { AuthorId = 1, Name = "Start Name", Email = "me@nospam.com" };
    config2.CreateMapper().Map(dto, entity2);

    //VERIFY
    entity1.Email.ShouldEqual("me@nospam.com");                  //not changed - ReadOnly
    entity2.Email.ShouldEqual("youhavechanged@gmail.com"); //changed, because using diff cofig
}
```
The test fails on the last assert, with the error
```
Assert.Equal() Failure
Expected: youhavechanged@gmail.com
Actual:   me@nospam.com
```
The class `WriteAuthorReadOnlyDto` is
```csharp
public class WriteAuthorReadOnlyDto
{
    public int AuthorId { get; set; }

    public string Name { get; set; }

    [ReadOnly(true)]
    public string Email { get; set; }
}
```

The `UnitTestProfile` class used in the text is given below
```csharp
public class UnitTestProfile : Profile
{
    public UnitTestProfile(bool addIgnoreParts)
    {
        if (addIgnoreParts)
            ForAllPropertyMaps(pm => Filter(pm.SourceMember), (pm, opt) => opt.Ignore());
    }
    public void AddWriteMap<TIn, TOut>()
    {
         CreateMap<TIn, TOut>().IgnoreAllPropertiesWithAnInaccessibleSetter();
    }
    private bool Filter(MemberInfo member)
    {
        var readOnlyAttr = member.GetCustomAttribute<ReadOnlyAttribute>();
        var isReadOnly = readOnlyAttr?.IsReadOnly ?? false;
        return isReadOnly;
    }
}
```

**Comment by lbargaoanu** [comment]
Maybe 

    var config2 = new MapperConfiguration(cfg => cfg.AddProfile(profile2));

**Comment by JonPSmith** [comment]
Doh! Yep, my bad. Really sorry to have bothered you.

Good news for me. It means `ForAllPropertyMaps` works!
