### ISSUE TITLE
Mapping an object and one item from it's children to a single object

### ISSUE THREAD

**Issue by ismcagdas** [AutoMapper/AutoMapper#2574]
### Source/destination types

```csharp

public class Product
{
	public decimal Price { get; set; }

	public ICollection<ProductTranslation> Translations { get; set; }
}

public class ProductTranslation
{
	public string Name { get; set; }

	public string LanguageCode { get; set; }
}

public class ProductListDto
{
	public decimal Price { get; set; }

	public string Name { get; set; }

	public string LanguageCode { get; set; }
}

```

### Mapping configuration

```csharp
configuration.CreateMap<Product, ProductListDto>().ConvertUsing<ProductToDtoTypeConverter>();
```

### Custom type converter

```csharp
public class ProductToDtoTypeConverter : ITypeConverter<Product, ProductListDto>
{
	public ProductListDto Convert(Product source, ProductListDto destination, ResolutionContext context)
	{
		if (destination == null)
		{
			destination = new ProductListDto();
		}
                
                // Calls ProductToDtoTypeConverter and causes a stackoverflow exception
		destination = context.Mapper.Map(source, destination);

		if (source.Translations != null && source.Translations.Any(pt => pt.Language == "en"))
		{
			var productTranlation = source.Translations.Single(pt => pt.Language == "en");
			destination = context.Mapper.Map(productTranlation, destination);
		}

		return destination;
	}
}
```

### Version: 6.2.2

Hi,

I want to map my Product class and a single item from it's Translations collection to a dto class. I have managed to do this using AfterMap action but it is not possible to use dependency injection in AfterMap action as far as I can see. I need to resolve some classes to decide which item to select from Translations list.

As a second option I have tried to use custom type converter (ProductToDtoTypeConverter) but when I use `context.Mapper.Map(source, destination)` it calls itself and it causes a stackOverflow exception.

So, I have two questions.

1. Is there any possibility to ignore my custom type converter when calling `context.Mapper.Map(source, destination)` inside itself ?

2. Is there any possibility to use dependency injection when using AfterMap action ?

Any other solution would be appriciated.

Or am I totally in the wrong direction ?

Thanks.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/b6737c92113dac4be96956a46d9562358b84c215/docs/Before-and-after-map-actions.md#using-imappingaction

**Comment by lbargaoanu** [comment]
@jbogard The docs don't seem updated.

**Comment by ismcagdas** [comment]
@lbargaoanu Thanks a lot for your fast response.

So can I use dependency injetion if I use IMappingAction ?
Also the type I will use as a source in the IMappingAction will be generic. Can I access ResolutionContext in IMappingAction implementation ? This is possible if I use AfterMap action.

**Comment by lbargaoanu** [comment]
Yes, that's the point.
Apparently not, but you can add an overload if you want.

**Comment by ismcagdas** [comment]
Thanks @lbargaoanu I will give it a try.
