### ISSUE TITLE
AutoMapper Fails to Resolve Optional Constructor Parameters

### ISSUE THREAD

**Issue by tghanem** [AutoMapper/AutoMapper#2577]
### Source/destination types

```csharp
public class Source
{
    public int Property1 { get; set; }
    public int Property2 { get; set; }
}

public class Destination
{
    public int Property1 { get; }
    public int Property2 { get; }

    public Destination(int property1, int property2 = 5)
    {
        Property1 = property1;
        Property2 = property2;
    }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Source, Destination>()
```

### Expected behavior

Should correctly map the optional parameter (i.e. property2) when a different value is passed (e.g. 2)

### Actual behavior

It resolves the optional value (i.e. 5) instead of the passed value (e.g. 2)

### Steps to reproduce

```csharp
var instance = new Source { Property1 = 1, Property2 = 2 };

var mappedInstance = mapper.Map<Destination>(instance);

var equalTo2 = mappedInstance.Property2 == 2; //This evaluates to false
```

**Comment by lbargaoanu** [comment]
Self mapping is not an interesting use case for us, try with different types.

**Comment by tghanem** [comment]
Thanks... for my use case i can go without self-mapping. I just used it for the example.
But is it that difficult to support self-mapping that fixes this problem?

**Comment by lbargaoanu** [comment]
It's possible if you remove the AssignableMapper, we just don't want to support this particular use case.

**Comment by jbogard** [comment]
@tghanem in general we're not interested in building a cloning library, but a mapping library. If I were to build a cloning library it'd look much, much different.

**Comment by tghanem** [comment]
Ok. I think i got the problem back with two different types, please see the updated problem description.

**Comment by lbargaoanu** [comment]
Yes, because there is no setter :)
