### ISSUE TITLE
Is it possible to create a mapping per type discriminator?

### ISSUE THREAD

**Issue by fabrikater** [AutoMapper/AutoMapper#258]
Something like this:

Mapper.CreateMap\<DTO.Party, Party\>();
Mapper.CreateMap\<DTO.Party, SomeParty\>().Where(source => source.PartyTypeDiscriminatorValue == 1);
Mapper.CreateMap\<DTO.Party, SomeOtherParty\>().Where(source => source.PartyTypeDiscriminatorValue == 2);

var party = new DTO.Party() { PartyTypeDiscriminatorValue = 2 };

var result = Mapper.Map\<DTO.Party, Party\>(party);

Assert.IsTrue(result is SomeOtherParty)

**Comment by julealgon** [comment]
I just posted a question on StackOverflow related to the problems I'm having with mapping based on a property of the original model in a inheritance scenario.

http://stackoverflow.com/questions/30128551/how-do-i-leverage-constructusing-in-a-mapping-with-inherited-types

Jimmy, I'm sure my problem is related to this. Could you perhaps take a look at that and suggest some workaround?

**Comment by TylerCarlson1** [comment]
It is related to this and unfortunately there's nothing you can do with includes to make this work.
Issue is when you include one class the logic will then check every class that inherits from the base and use the highest derived ones for it.  Regardless if you included it or not.

Fix for this issue in code shown here 3ed6d8af5ccc12d0990e7a8bb57d02612006070a as part of #590
