### ISSUE TITLE
Unmapped members were found

### ISSUE THREAD

**Issue by bahar-1396** [AutoMapper/AutoMapper#2583]
hi
how to resolve it in ver 6.2.2
 my viewmodel is:
`public class ViewModel : IHaveCustomMappings
    {

        public int Id { get; set; }
        public int One{ get; set; }
        public int Two{ get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Model, ViewModel>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => Id));
                    }
    }`
exception:
`Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
========================================================================================
Model-> ViewModel (Destination member list)
Model -> ViewModel (Destination member list)

Unmapped properties:
One
Two`
i using StructureMap for di

` public class AutoMapperRegistry : Registry
    {
        public AutoMapperRegistry()
        {
            this.Scan(scan =>
            {
                scan.TheCallingAssembly();
                scan.AssemblyContainingType<DomainServices.Interfaces.IHaveCustomMappings>(); // for other asms, if any.

                scan.WithDefaultConventions();
              
                scan.AddAllTypesOf<IHaveCustomMappings>().NameBy(item => item.FullName);
            });

            this.For<MapperConfiguration>().Singleton().Use("", ctx =>
            {
                var config = new MapperConfiguration(cfg =>
                {
                    
                    cfg.CreateMissingTypeMaps = true; // It will connect `Person` & `PersonViewModel` automatically.
                    AddAllCustomAutoMapperProfiles(ctx, cfg);
                    AddAllIHaveCustomMappings(ctx, cfg);
                });
                config.AssertConfigurationIsValid();
              
                return config;
            });

            this.For<IMapper>().Singleton().Use(ctx => ctx.GetInstance<MapperConfiguration>().CreateMapper(ctx.GetInstance));
        }
     private void AddAllIHaveCustomMappings(IContext ctx, IMapperConfigurationExpression cfg)
        {
            
            var profiles = ctx.GetAllInstances<IHaveCustomMappings>().ToList();
         
            foreach (var profile in profiles)
            {
               
                profile.CreateMappings(cfg);
            }
        }
    }`
thanks

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
