### ISSUE TITLE
ReverseMap and MapFrom

### ISSUE THREAD

**Issue by dschuermans** [AutoMapper/AutoMapper#2584]
### Expected behavior

The same behaviour from workingConfig in nonWorkingConfig

### Actual behavior

The nonWorkingConfig seems to apply the default mapping defined for the unit, after the resolver has been called.
Inside the resolver, the submodel object is mapped properly in all cases but in the non working case, it gets altered after the resolver ran.
I think this is because of the additional fuctionality in the MapFrom with the deviating unit in combination with the default conversion mapping (double -> ForcePerLength) which sets the value to kN/m instead of MN/m on the submodel force property

For the semi-working mapper, i removed the deviating unit functionality in the MapFrom() for IHasSubmodel -> SubModel, member Force

### Steps to reproduce
Run the gist.
Required dependencies: AutoMapper 6.2.2 and UnitsNet 3.94

**Comment by lbargaoanu** [comment]
Try creating the maps explicitly instead of ReverseMap. The maps with MapFrom first.

**Comment by dschuermans** [comment]
@lbargaoanu - As you can see, that's what I did in the working config. Or did you mean something else?

**Comment by lbargaoanu** [comment]
Right :) See [this](http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html). The MapFrom-s are reversed.

**Comment by dschuermans** [comment]
@lbargaoanu so it's by design then, this behaviour i'm encountering?

**Comment by lbargaoanu** [comment]
The reversing of the MapFrom-s is, I don't know about the rest.

**Comment by dschuermans** [comment]
@lbargaoanu Ah :-)
The reverse mapping is working as expected. Although i expected that if I define custom mapping behaviour it would overwritten the reverse mapping generated...

**Comment by lbargaoanu** [comment]
So you want the ResolveUsing to overwrite the reversed MapFrom. I don't know :) 
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.

**Comment by lbargaoanu** [comment]
The ResolveUsing should indeed override the reversed MapFrom, but that was fixed a long time ago. I cannot execute you gist. And anyway the whole thing is too complicated for me to follow. So please simplify it or ask the people on SO for help with it and get back here if AM seems to be the culprit.

**Comment by dschuermans** [comment]
@lbargaoanu - The gist can't get any simpler... Add those 3 files to a console application, through Nuget install **AutoMapper** and **UnitsNet** and run...
I'll ask on SO

**Comment by lbargaoanu** [comment]
What you can do is to check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by dschuermans** [comment]
So when people report a bug they're supposed to investigate and solve it themselves?

@jbogard i'm disappointed.

I've updated the Gist, removed the UnitsNet dependency. Everything is in 1 file now.
To clarify the goal here:

When mapping `FlatModel` to `Model`, if the data of `SubModel` is the same we want to have the **same object reference** to the `SubModel` property in the mapped `Model`'s.  
Imagine reading data from an excel file and several rows have the same data filled out for those properties.

By default, we have this mapping defined:  
```
CreateMap<Weight, double>().ConvertUsing(s => s.Kilograms);
CreateMap<double, Weight>().ConvertUsing(Weight.FromKilograms);
```  
When mapping from `Weight` to `double`, we use the `Kilogram` value of the weight.
Consecutively, when mapping from `double` to `Weight`, we create a new `Weight` object using the value as kilograms.
There is however a special property on `Submodel`, `ObjectWeightInPounds`, that requires the `Weight` type to be expressed **in Pounds instead of Kilograms.**
Because of that reason, we explicitly tell using MapFrom() that ObjectWeightInPounds should be mapped using Weight.FromPounds(value) instead of the default Weight.FromKilograms as specified in the  double -> Weight mapping:  
`.ForMember(x => x.ObjectWeightInPounds, opt => opt.MapFrom(x => Weight.FromPounds(x.SubModelObjectWeightInPounds)))`

Breakdown where it goes wrong:
Configuration:
```
MapperConfiguration config = new MapperConfiguration(mce =>
{
    // Setup default conversion for units
    mce.CreateMap<Weight, double>()
        .ConvertUsing(s => s.Kilograms);
    mce.CreateMap<double, Weight>()
        .ConvertUsing(Weight.FromKilograms);


    mce.CreateMap<Model, FlatModel>()
        .ForMember(x => x.SubModelObjectWeightInPounds, opt => opt.MapFrom(x => x.SubModel.ObjectWeightInPounds.Pounds))
        .ReverseMap()
        .ForMember(x => x.SubModel, opt => opt.ResolveUsing(new Resolver()));

    // Setup mapping for submodel, used by resolver
    mce.CreateMap<IHasSubModel, SubModel>()
        .ForMember(x => x.Name, opt => opt.MapFrom(x => x.SubModelName))
        .ForMember(x => x.ObjectWeightInPounds, opt => opt.MapFrom(x => Weight.FromPounds(x.SubModelObjectWeightInPounds))) //This is expressed in Pounds, so it can't use the default mapping (double -> Weight)
        .ForMember(x => x.TotalWeightInKilograms, opt => opt.MapFrom(x => x.SubModelTotalWeightInKilograms)) // This is expressed in Kilograms, so the default mapping (double -> Weight) is used)
        .ReverseMap()
        ; 
    
});
```
Output:
```
## TEST DATA
{ Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }
{ Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }

## Using .ReverseMap() with MapFrom() that overrides CreateMap<double, Weight>:
Mapping Model -> FlatModel for "Model1"
Mapping result: { Name: 'Model1', Weight: 100, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping Model -> FlatModel for "Model2"
Mapping result: { Name: 'Model2', Weight: 50, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping FlatModel -> Model for "Model1"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] Empty
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: NULL
[RESOLVER] -------
Mapping result: { Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } } }
Mapping FlatModel -> Model for "Model2"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] [0]: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: NULL
[RESOLVER] -------
Mapping result: { Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } } }
Submodel are same object reference: False
```
As shown above, `Resolver` maps IHasSubModel to SubModel correctly. The `ObjectWeightInPounds` property is indeed in Pounds:  
`[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }`
However, when mapping "Model2" we see that the previously mapped `SubModel` has indeed been added to the `ResolutionContext.Items` however, the `ObjectWeightInPounds` property is no longer in pounds, but in kilograms:
`[RESOLVER] [0]: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }`
When debugging, I can tell that the correct item is added to the list, but after the resolver - AM sets the ObjectWeightInPounds property again, but this time with Kilograms as unit...
This means that AM applied the mapping `CreateMap<double, Weight>().ConvertUsing(Weight.FromKilograms)` **after** the resolver ran to the previously mapped object.

Breakdown where it works using ReverseMap(), but not with the wanted results (no pounds)
Configuration:
```
MapperConfiguration config = new MapperConfiguration(mce =>
{
    // Setup default mapping for Weight (to and from)
    mce.CreateMap<Weight, double>().ConvertUsing(s => s.Kilograms);
    mce.CreateMap<double, Weight>().ConvertUsing(Weight.FromKilograms);

    // Setup mapping for Model to FlatModel and reverse it
    mce.CreateMap<Model, FlatModel>()
        .ForMember(x => x.SubModelObjectWeightInPounds, opt => opt.MapFrom(x => x.SubModel.ObjectWeightInPounds.Pounds))
        .ReverseMap()
        .ForMember(x => x.SubModel, opt => opt.ResolveUsing(new Resolver()));

    // Setup mapping for submodel, used by resolver but do not explicitly specify mapping for ObjectWeightInPounds to use pounds instead of kilograms
    mce.CreateMap<IHasSubModel, SubModel>()
        .ForMember(x => x.Name, opt => opt.MapFrom(x => x.SubModelName))
        .ForMember(x => x.ObjectWeightInPounds, opt => opt.MapFrom(x => x.SubModelObjectWeightInPounds)) // This is now expressed in Kilograms (instead of Pounds), so it'll work
        .ForMember(x => x.TotalWeightInKilograms, opt => opt.MapFrom(x => x.SubModelTotalWeightInKilograms)); // This is express in Kilograms, so the default mapping (double -> Weight) is used)
});
```
Output:
```
## TEST DATA
{ Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }
{ Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }

## Using .ReverseMap() with MapFrom() that does not override CreateMap<double, Weight>:
Mapping Model -> FlatModel for "Model1"
Mapping result: { Name: 'Model1', Weight: 100, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping Model -> FlatModel for "Model2"
Mapping result: { Name: 'Model2', Weight: 50, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping FlatModel -> Model for "Model1"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] Empty
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: NULL
[RESOLVER] -------
Mapping result: { Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } } }
Mapping FlatModel -> Model for "Model2"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] [0]: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] -------
Mapping result: { Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 kg }, TotalWeightInKilograms: { 150 kg } } }
Submodel are same object reference: True
```
As you can see, it is immediately mapped to **Kilograms** as specified by the default double -> Weight mapping.
In the end, the resolver was able to find the same `SubModel` from the context items and return that instance instead of a new one.

However, when we create seperate mappings and no longer use one mapping with ReverseMap(), it all works correctly:
Configuration:
```
MapperConfiguration config = new MapperConfiguration(mce =>
{
    // Setup default conversion for units
    mce.CreateMap<Weight, double>()
        .ConvertUsing(s => s.Kilograms);
    mce.CreateMap<double, Weight>()
        .ConvertUsing(Weight.FromKilograms);

    // Setup model mapping
    mce.CreateMap<Model, FlatModel>()
        .ForMember(x => x.SubModelObjectWeightInPounds, opt => opt.MapFrom(x => x.SubModel.ObjectWeightInPounds.Pounds));
    mce.CreateMap<FlatModel, Model>()
        .ForMember(x => x.SubModel, opt => opt.ResolveUsing(new Resolver()));

    // Setup mapping for submodel, used by resolver
    mce.CreateMap<IHasSubModel, SubModel>()
        .ForMember(x => x.Name, opt => opt.MapFrom(x => x.SubModelName))
        .ForMember(x => x.ObjectWeightInPounds,
            opt => opt.MapFrom(x => Weight.FromPounds(x.SubModelObjectWeightInPounds))) // This unit does not use default unit
        .ForMember(x => x.TotalWeightInKilograms, opt => opt.MapFrom(x => x.SubModelTotalWeightInKilograms)); // This unit uses default unit, so the default conversion map will be used (double -> SpecificWeight)
});
```
Output:
```
## TEST DATA
{ Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }
{ Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }

## Using no .ReverseMap() but seperate CreateMap<> statements, one of which uses MapFrom() that overrides CreateMap<double, Weight>
Mapping Model -> FlatModel for "Model1"
Mapping result: { Name: 'Model1', Weight: 100, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping Model -> FlatModel for "Model2"
Mapping result: { Name: 'Model2', Weight: 50, SubModelName: 'RootSubModel', SubModelObjectWeightInPounds: 10, SubModelTotalWeightInKilograms: 150 }
Mapping FlatModel -> Model for "Model1"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] Empty
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: NULL
[RESOLVER] -------
Mapping result: { Name: 'Model1', Weight: { 100 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }
Mapping FlatModel -> Model for "Model2"
[RESOLVER] ResolutionContext.Items["Submodels"]:
[RESOLVER] [0]: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Mapped: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] Existing: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } }
[RESOLVER] -------
Mapping result: { Name: 'Model2', Weight: { 50 kg }, Submodel: { Name: 'RootSubModel', ObjectWeightInPounds: { 10 lbs }, TotalWeightInKilograms: { 150 kg } } }
Submodel are same object reference: True
```

The SubModel reference is the same in both models after mapping and the ObjectWeightInPounds is in pounds and not in kilograms.

**Comment by jbogard** [comment]
If for any reason you're unsatisfied with the service, please contact the refund department ;)

We do our best to solve your issue ourselves, but for something like this that's pretty complicated, we just don't have time to investigate. However, since it is an open source project, you have all the tools that we do in order to debug what is going on.

The best we can do is point to the execution plan (as @lbargaoanu pointed out), and see what is wrong with the expression tree we generate. Then if you see something wrong, trace it back to the class that creates the expression tree based on your `TypeMap`. That's exactly what we would do to debug this.
