### ISSUE TITLE
ProjectTo not working the same as Mapper.Map

### ISSUE THREAD

**Issue by RudyvdLinden** [AutoMapper/AutoMapper#2585]
Gist [here](https://gist.github.com/RudyvdLinden/74bf519fba6af779a7ddb0e1ea480401).

We have nullable objects that should remain nullable, for instance ObjectA has an ObjectB that might be null. That's why we set AllowNullCollections and AllowNullDestinationValues to true. When using Mapper.Map all goes as we expect. When we use ProjectTo however, we get a NullReferenceException. 

We would expect ProjectTo and Mapper.Map to behave the same way.

We use version 6.2.2 of AutoMapper.

Our Mapper Configuration:
```C#
            config.AllowNullCollections = true;
            config.AllowNullDestinationValues = true;

            config.CreateMap<ObjectA, ModelA>()
                .ForMember(d => d.Id, o => o.MapFrom(s => s.Id))
                .ForMember(d => d.ObjectB, o => o.MapFrom(s => s != null ? $"{s.MyObjectB.Name} ({s.MyObjectB.Value})" : null));
```

Our objects and models:
```C#
    public class ObjectB
    {
        public int Value { get; set; }
        public string Name { get; set; }
    }

    public class ObjectA
    {
        public int Id { get; set; }
        public ObjectB MyObjectB { get; set; }
    }

    public class ModelA
    {
        public int Id { get; set; }
        public string ObjectB { get; set; }
    }
```

And the code that runs it all:
```C#
            Mapper.Initialize(AutoMapperTest.Map);
            var objectAList = new List<ObjectA> {new ObjectA() {Id = 1, MyObjectB = null}};
            var queryable = objectAList.AsQueryable();
            var map = Mapper.Map<List<ModelA>>(objectAList);
            var projectTo = queryable.ProjectTo<ModelA>().ToList();
```

The last line throws a NullReferenceException, whereas the line before that has a ModelA with an ObjectB that is null.

**Comment by lbargaoanu** [comment]
Well, ProjectTo and Map are very different as you might know already :) We null check MapFrom-s for you, but doing the same for ProjectTo doesn't seem a good idea. EF6 doesn't allow just any expression in there. There is already an option to skip some null checks in ProjectTo for this very reason.
