### ISSUE TITLE
AutoMapper throw mapper already initialize exception after updating it to 6.x version.

### ISSUE THREAD

**Issue by mrmkamranmalik** [AutoMapper/AutoMapper#2587]
AutoMapper throw mapper already initialize exception after updating it to 6.x version, and I was using inline mapping. I have above 1700 places in my mvc appliation where i use Mapper.Initialize(). Please help i dont want to go through all line of code.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/stable/Inline-Mapping.html

**Comment by mrmkamranmalik** [comment]
Thanks for sending reference link. I got a solution through https://github.com/AutoMapper/AutoMapper/issues/2404
