### ISSUE TITLE
Sub mapping operation with the ResolutionContext.Mapper doesn't carry through the context's Items

### ISSUE THREAD

**Issue by Shazwazza** [AutoMapper/AutoMapper#2588]
When using a class of type `ITypeConverter<in TSource, TDestination>` and then in your `TDestination Convert(TSource source, TDestination destination, ResolutionContext context)` method, if you map using the `ResolutionContext`, for example :

```csharp
return context.Mapper.Map<ClassA, ClassB>(classA);
```

This will map, however the context's `Items` collection is not carried through. If you first mapped with something like:

```csharp
Mapper.Map<ClassA, ClassB>(classA , opt => opt.Items["foo"] = "bar");
```

and then if you map one of your properties with an `ITypeConverter` using the above syntax, the `Items` collection will be empty. The only way to maintain your `Items` collection is to manually re-add them all in your sub mapping which is odd since this wasn't the case in previous versions. Like:

```csharp
return context.Mapper.Map<ClassA, ClassB>(classA,
    options =>  {
        foreach (var contextItem in context.Items) {
            options.Items[contextItem.Key] = contextItem.Value;
        }
    });
```

### Version: x.y.z
6.1.1

### Expected behavior

I would expect when mapping with the mapper assigned to the context, that the context `Items` collection would be carried through. In previous versions, even using the static `Mapper.Map` would carry through the `Items` collection somehow

### Actual behavior

It's not carried through at all, `Items` is reset

### Steps to reproduce

I hope the above explanation is clear enough, but if there's a unit test covering this, etc... I can provide repro steps if needed. I'll see if i can get the source and checkout the tests and submit a PR, but that will have to wait until tomorrow.

Let me know if you think it's something I'm doing wrong :)

**Comment by lbargaoanu** [comment]
No. There's one context per Map call, that's all.

**Comment by Shazwazza** [comment]
Update, ok so there's a slightly nicer way to do this but still seems like passing in the `parent` context is odd if you are already using the parent context to do that mapping.  Plus this overload requires that you pass in `null` to indicate you want a new object. Example that works:

```csharp
return context.Mapper.Map<ClassA, ClassB>(classA, null, context);
```

I would expect that doing either of these would still work and implicitly pass the parent context:

```csharp
return context.Mapper.Map<ClassA, ClassB>(classA);
```

or

```csharp
return context.Mapper.Map<ClassB>(classA);
```
