### ISSUE TITLE
Bug with CreateMissingTypeMaps = true and inheritance

### ISSUE THREAD

**Issue by tbolon** [AutoMapper/AutoMapper#2589]
There is a bug when:
* using CreateMissingTypeMaps = true (default value)
* using two types with an inheritance relation
* mapping first a type which contains the parent type
* then mapping a type which contains the child type

In this case, you will receive an InvalidCastException when mapping the second type.

(For a complete example, see [this gist](https://gist.github.com/tbolon/515c531afd27e5d6d3aa310f311dd8fc))

### Source/destination types

```csharp
/* Simple inheritance */

class SrcParent { }
class SrcChild : SrcParent { }

class DestParent { }
class DestChild : DestParent { }

/* First graph where the parent type is used */

class SrcApple { public SrcParent First { get; set; } }
class DestApple { public DestParent First { get; set; } }

/* Second case where the child type is used. */

class SrcOrange { public SrcChild Second { get; set; } }
class DestOrange { public DestChild Second { get; set; } }
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(c => c.CreateMissingTypeMaps = true);
var mapper = config.CreateMapper(); 
```

### Expected behavior

When `CreateMissingTypeMaps` is `true`, I expect that the mapping succeed when a simple inheritance graph is used (no polymorphism, only defined types).

### Actual behavior

I receive an InvalidCastException when trying to map a type with `CreateMissingTypeMaps = true` *only when* I have already used a mapping where the parent class is used.

### Steps to reproduce

```csharp
// we first map with a case where the parent type is used (SrcParent)
mapper.Map(new SrcApple { First = new SrcParent() }, new DestApple());

// we map with a case where the child type is used (SrcChild)
// InvalidCastException: Unable to cast object of type 'ConsoleApp15.DestParent' to type 'ConsoleApp15.DestChild'.
mapper.Map(new SrcOrange { Second = new SrcChild() }, new DestOrange());
```

### Notes

If you comment the first Map (apples), the exception is not raised.

If you reverse the Map(...) order, the exception is not raised.

I have tried to compare the execution plan with/without the previous mapping without spotting any difference.

I will try to clone the code and reproduce the problem in a test case.

**Comment by lbargaoanu** [comment]
I would not mix inheritance with dynamic maps. Try moving those types in another profile with CreateMissingTypeMaps false and see how it goes.

**Comment by tbolon** [comment]
I have already tried this, which works:

```csharp
var config = new MapperConfiguration(c =>
{
    c.CreateMissingTypeMaps = true;
    //c.CreateMap<SrcParent, DestParent>().Include<SrcChild, DestChild>();
    c.CreateMap<SrcChild, DestChild>();
});
```

As soon as I create an explicit map between the two child types (even without the inheritance declaration), the mapping succeed.

**Comment by thomaslevesque** [comment]
I'm having the same problem. 
@lbargaoanu why was this issue closed? Is this by design? It really looks like a bug to me...

**Comment by thomaslevesque** [comment]
My repro:

```csharp
void Main()
{
    var config = new MapperConfiguration(c =>
    {
        c.CreateMissingTypeMaps = true;
    });
    
    var mapper = config.CreateMapper();

    var foo = new Foo { X = 1, Y = 2, Z = 3 };
    mapper.Map<BasicFooDto>(foo).Dump();
    mapper.Map<FullFooDto>(foo).Dump();
}

class Foo
{
    public int X { get; set; }
    public int Y { get; set; }
    public int Z { get; set; }
}

class BasicFooDto
{
    public int X { get; set; }
}

class FullFooDto : BasicFooDto
{
    public int Y { get; set; }
    public int Z { get; set; }
}
```

The code above fails with the following exception:

> Unable to cast object of type 'BasicFooDto' to type 'FullFooDto'.

However if I map to `FullFooDto` *before* mapping to `BasicFooDto`:

```csharp
    mapper.Map<FullFooDto>(foo).Dump();
    mapper.Map<BasicFooDto>(foo).Dump();
```csharp

then it works...

The behavior should be consistent, regardless of the order of operations.

It looks like the type map created for `Foo` => `BasicFooDto` is considered usable for `Foo` => `FullFooDto`, which is wrong.

**Comment by thomaslevesque** [comment]
The problem seems to be here:

https://github.com/AutoMapper/AutoMapper/blob/b5abe42f017350b0e7658250572f483a8122c26d/src/AutoMapper/MapperConfiguration.cs#L229-L235

`GetRelatedTypePairs` returns (among other things) `("Source", "BaseDestination")`, for which a `TypeMap` exists, and it's the one that is picked, although it can't map `Source` to `BaseDestination`.
