### ISSUE TITLE
Automapper should not wrap exceptions from destination type

### ISSUE THREAD

**Issue by alewmt** [AutoMapper/AutoMapper#2590]
My destination type perform value validation and throw business logic exception if constraints are violated. Right now I get AutoMapperMappingException that is absolutely wrong. I need to catch infrastructure exception and unwrap actual exception that lead to writing a lot of code.

### Destination type

```csharp
Property
set
{
    if (value == null || !new Regex(VALID_PATTERN).IsMatch(value) || value.Length > ShortNameLength)
    {
        throw new BusinessLogicException(ErrorCodes.Asset.InvalidShortName);
    }
    shortName = value;
}
```

**Comment by jbogard** [comment]
Ewwww why would you do that.

**Comment by alewmt** [comment]
Because my entities validate itself.

I think nothing should changes after switch from handmade mapping.
```
try 
{            
   dto.Fill(entity)
}
catch (BusinessLogicException)
{
}
```
but it changes
```
try 
{            
   Mapper.Map(dto, entity);
}
catch (AutoMapperMappingException ex)
{
    if(ex.InnerException is BusinessLogicException e)
    {
    }
}
```

**Comment by jbogard** [comment]
You should be validating actions, not entities. Using setters as validation, and throwing exceptions, I see as an anti-pattern. If I were you, I'd switch to an actual validation framework, exceptions should be exceptional, not for validation. In my systems, I use actual methods `entity.DoThing(dto)` then inside of there check for conditions and return a success/fail result see https://jimmybogard.com/domain-command-patterns-validation/.

The reason why we wrap exceptions is to provide context about what you were doing. In `dto.Fill` you get a normal stack trace. With ours, it's a compiled expression and you have zero stack trace inside the compiled expression. So if something goes wrong, we capture context information around where were trying to map, the hierarchy of objects, the property, type map metadata etc.

So for your code, I just don't see proper use of exceptions based on standard .NET guidelines https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing so I don't see this as a valid scenario.

**Comment by alewmt** [comment]
I don't know why this is an anti-pattern. I always thought that encapsulation is very valuable OOP concept. The object doesn't allow to bring itself to invalid state without any additional help.

All the things about context are right if there are mapping problems. My problem is not about mapping. So I cant think a way how BL exception wrapping can help. Automapper cant add any value to BL exception.

I use exceptions to indicate invalid input and didn't get why it is not a valid scenario.

Anyway, thank you for such an elaborate answer.

**Comment by jbogard** [comment]
That's not the problem - it's the use of exceptions for non-exceptional
behavior. Another way to approach this is to validate BEFORE anything tries
to get set (or through a method that returns a result). See the blog link
above.

We assume that just normal mapping will not result in exceptions. That's a
reasonable assumption to make.
