### ISSUE TITLE
Exception Message for DuplicateTypeMapConfigurationException

### ISSUE THREAD

**Issue by KlemensE** [AutoMapper/AutoMapper#2594]
Using following [Snippet](https://gist.github.com/KlemensE/26900d183d0da23b1a346919372bb800) a DuplicateTypeMapConfigurationException will be thrown by AssertConfigurationIsValid.

### Expected behavior

An exception message which does not contain an empty line for typemaps created in a MappingConfigurationExpression.

Maybe Anonymous Profile or ConfigurationExpression could be used instead.

### Actual behavior

The following exception message:

> The following type maps were found in multiple profiles:
> AutoMapperTest.Test1 to AutoMapperTest.Test2 defined in profiles:
> 
> AutoMapperTest.TestProfile
> This can cause configuration collisions and inconsistent mapping.
> Consolidate the CreateMap calls into one profile, or set the root Advanced.AllowAdditiveTypeMapCreation configuration value to 'true'.

**Comment by lbargaoanu** [comment]
PR welcome.
