### ISSUE TITLE
Automapper 6.2 fails when using .Net Native within an UWP 6.0.8 app

### ISSUE THREAD

**Issue by jersiovic** [AutoMapper/AutoMapper#2597]
I get following error after upgrading a UWP app from version 5 to version 6 of Automapper when compilation is done for .Net Native (release config).

```Type 'System.Reflection.Emit.FieldBuilder' from assembly 'System.Reflection.Emit' was not included in compilation, but was referenced in type 'AutoMapper.Execution.PropertyEmitter'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.	Preventa.Win8```

This issue seem similar experience in the past for version 5 https://github.com/AutoMapper/AutoMapper/issues/1131

I fixed the issue downgrading to version 5.2.0 but it doesn't look best solution.

**Comment by lbargaoanu** [comment]
I believe this has little to do with AM itself. You should be asking this in a forum where people have some .Net native expertise.

**Comment by jersiovic** [comment]
So, do you mean that the fact that downgrading Automapper without changing any line on my app code was the solution is not a clear clue that shows the problem is in Automapper. I don't agree.
IMO it looks like sth fixable ot default.rd.xml

**Comment by jbogard** [comment]
Have you tried the alpha? It targets netstandard2.0

**Comment by jersiovic** [comment]
Finally it looks sth wrong at my side. Today after upgrading to v7.0.0-alpha-001 it worked, but also it worked if I downgrade to v6.2.2.
O_o
Thank you guys and sorry for this fake bug report.

**Comment by jbogard** [comment]
I’ve seen the same phantom stuff with Xamarin too.
