### ISSUE TITLE
AutoMapper Profiles Overriding CreateMissingMappingTypes

### ISSUE THREAD

**Issue by ajkuntz** [AutoMapper/AutoMapper#2598]
Hi, I'm experiencing some unexpected behavior from the AutoMapper and perhaps I'm doing something wrong.  By default, I don't want AutoMapper to create missing type mappings.  However, when I add a profile it seems to override the default behavior of CreateMissingTypeMaps even though it is explicitly defined.  If you create the I created a couple of small unit tests to illustrate.  I'd expect all three of these to throw an exception, but only the first and third do:

```
public interface ITest
{
	string Name { get; set; }
}

public class Test1 : ITest
{
	public string Name { get; set; }
}

public class Test2 : ITest
{
	public string Name { get; set; }
}

public class AutoMapperProfile : Profile
{
	public AutoMapperProfile()
	{
		this.CreateMissingTypeMaps = false;
	}
}

public class AutoMapperTest
{
	[Fact]
	public void ShouldThrowErrorOnMissingMapping()
	{
		// Works fine
		IMapper mapper = new Mapper(new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = false));

		var test1 = new Test1() { Name = "Test1" };
		Assert.Throws<AutoMapperMappingException>(() => mapper.Map<Test1, Test2>(test1));
	}

	[Fact]
	public void ShouldThrowErrorOnProfileMapping()
	{
		// Does not pass even though the default for CreateMissingTypeMaps should be used and it is set explicitly in the profile
		IMapper mapper = new Mapper(new MapperConfiguration(cfg => cfg.AddProfile<AutoMapperProfile>()));

		var test1 = new Test1() { Name = "Test1" };
		Assert.Throws<AutoMapperMappingException>(() => mapper.Map<Test1, Test2>(test1));
	}
	
	[Fact]
	public void ShouldThrowErrorOnProfileMappingAndConfig()
	{
		// Passes because the configuration is set explicitly
		IMapper mapper = new Mapper(new MapperConfiguration(cfg => 
		{
			cfg.CreateMissingTypeMaps = false;
			cfg.AddProfile<AutoMapperProfile>();
		}));

		var test1 = new Test1() { Name = "Test1" };
		Assert.Throws<AutoMapperMappingException>(() => mapper.Map<Test1, Test2>(test1));
	}
}
```

**Comment by lbargaoanu** [comment]
In your second test, you can set it only once, in the global configuration, and the profile will inherit it.

**Comment by ajkuntz** [comment]
So, just so I am clear, you are saying 1. that setting the CreateMissingTypeMaps in the profile has no bearing and 2. that _not_ setting CreateMissingTypeMaps in the global configuration and adding any profile (even if you specify CreateMissingTypeMaps = false within the profile) completely overrides the global default behavior of CreateMissingTypeMaps = false to actually create missing type maps (my second test).  This doesn't seem very logical, but if you insist that is how it is supposed to function, I'll have to accept it.

**Comment by lbargaoanu** [comment]
Profiles make sense with static maps, because a map is defined in a certain profile. They don't make much sense with dynamic maps, because they are not explicitly defined anywhere. So the tests involving profiles don't make sense to me.

**Comment by ajkuntz** [comment]
My use case is actually different where I actually have mappings defined in the profile, but want to safeguard against anything dynamically created.

But, after looking at this deeper, it appears that the default value for CreateMissingTypeMaps switched from false to true between versions 6.1.1 and 6.2 (https://github.com/AutoMapper/AutoMapper/blob/v6.2.0/src/AutoMapper/ProfileMap.cs).  This was causing me confusion as I was used to AutoMapper not creating maps dynamically by default.

However, it still seems odd that some configuration settings such as CreateMissingTypeMaps have no bearing within profiles.  It might be better if they weren't even available.  Just a thought.  Overall though, I think this can be closed and thank you for your help.
