### ISSUE TITLE
DateTimeOffset to DateTime conversion trims the last 10000 ticks

### ISSUE THREAD

**Issue by ObadahFahmy** [AutoMapper/AutoMapper#2599]
### Expected behavior

When mapping a DateTimeOffset (DTO) to a DateTime (DT) it would be expected that the DateTime would have the same value as the (DTO) in terms of number of Ticks

### Actual behavior

When mapped the DateTime that is created is trimmed to the last millisecond, if the DTO has 636107698591699575 ticks, then the DT will have 636107698591690000 ticks

### Steps to reproduce

```csharp

        [TestMethod]
        public void DateTimeOffset_To_DateTime_TicksAreEqual()
        {
            var dateTimeOffset = DateTimeOffset.Now;
            var dateTime = Mapper.Map<DateTime>(dateTimeOffset);
            Assert.AreEqual(dateTimeOffset.Ticks, dateTime.Ticks);
        }
```

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by ObadahFahmy** [comment]
Looking at the execution plan, it is using the constructor New System.DateTime($year, $month, $day, $hour, $minute, $second, $millisecond). There is another more appropriate constructor which would be New System.DateTime($ticks). How that would be done by default though I am not quite sure. I haven't looked into how the constructor is chosen, but I assume it is the most detailed constructor that can be filled? If that is the case then I can see how New System.DateTime($year, $month, $day, $hour, $minute, $second, $millisecond) has prevelance over New System.DateTime($ticks)

**Comment by lbargaoanu** [comment]
Yes, we're greedy :) I think a type converter is the way to go here. The reverse map should work by default just fine because there is a conversion operator.
