### ISSUE TITLE
Mapping of same type

### ISSUE THREAD

**Issue by icnocop** [AutoMapper/AutoMapper#260]
I'd like to request that AutoMapper support mapping of the same type.

```
    [Test]
    public void Map_OfSameType_Succeeds()
    {
        Source source = new Source
        {
            ShouldBeMapped = "Value1",
        };

        Source destination = new Source
        {
            ShouldBeMapped = "Value2",
        };

        Mapper.Map<Source, Source>(source, destination);
        destination.ShouldBeMapped.ShouldEqual("Value1");
    }
```

Thank you.

**Comment by nour-s** [comment]
Hi, I wonder if you can at least throw an exception that the map is not defined for the same type!
Because mapping is not happening however no error is shown ! which makes a confusion.

Thanks.

**Comment by jbogard** [comment]
So today, AutoMapper supports this, but through assignables. If type A is assignable to type B, then AutoMapper will just assign the objects, no mappings needed.
