### ISSUE TITLE
Exception while initialize with assemblies scanning

### ISSUE THREAD

**Issue by lkurzyniec** [AutoMapper/AutoMapper#2600]
Created empty project, added AutoMapper 6.2.2, initialize with assemblies scanning and got an error: 
`System.MissingMethodException: 'No parameterless constructor defined for this object.`

### Source/destination types
```csharp
public class TestA
{ }

public class TestB
{ }
```

### Mapping configuration
```csharp
Mapper.Initialize(x => x.AddProfiles(AppDomain.CurrentDomain.GetAssemblies()));

public class MyProfile : Profile
{
    public MyProfile()
    {
        CreateMap<TestA, TestB>().ReverseMap();
    }
}
```

### Expected behavior
No exception

### Actual behavior
`System.MissingMethodException: 'No parameterless constructor defined for this object.`

![image](https://user-images.githubusercontent.com/5943484/38541711-37f30a04-3ca0-11e8-9ed7-ecc9706dfd32.png)

### Steps to reproduce
```csharp
var a = new TestA();
var b = Mapper.Map<TestB>(a);
```

**Comment by lbargaoanu** [comment]
Just specify explicitly the assemblies you need. If you want to fix the underlying cause, a PR is welcome.
