### ISSUE TITLE
Mapping multiple objects into one

### ISSUE THREAD

**Issue by krisnds** [AutoMapper/AutoMapper#2601]
### Source/destination types

Source type: a composite object (using suggestion from https://github.com/AutoMapper/AutoMapper/issues/389)

public class JoinedJob 
{
    public JobInfo job { get; set; }
    public LocationInfo loc { get; set; }
}

Destination type: 
public class JobDetailsModel
{
    public int JobID { get; set; }
    public string JobType { get; set; }
}

For testing purposes, I am using this very simple destination class, ignoring the source loc fields completely for now.

### Mapping configuration
            CreateMap<JoinedJob, JobDetailsModel>()
                .ForMember(dest => dest.JobID, opt => opt.MapFrom(src => src.job.JobID))
                .ForMember(dest => dest.JobType, opt => opt.MapFrom(src => src.job.JTName));

### Expected behavior
I expect the JoinedJob object to get properly mapped to the JobDetailsModel object.

### Actual behavior
This doesn't work at all when using ProjectTo<>. The objects I got back had null and zero values.

### Steps to reproduce
So I tested a single instance:
var testDetail = _mapper.Map<JoinedJob, JobDetailsModel>(testJob);

and this code throws this exception:

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=====================================================================================================
JoinedJob -> JobDetailsModel (Destination member list)
NDSWebAPI.Modules.Core.BusinessLogic.JobRetrieval+JoinedJob -> NDSWebAPI.Models.Core.JobDetailsModel (Destination member list)

Unmapped properties:
JobID
JobType

It's as if AutoMapper doesn't recognize the .ForMember mappings I defined?

Should this work?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by krisnds** [comment]
OK, I posted it [here](https://stackoverflow.com/questions/49782899/automapper-not-mapping-composite-object)
