### ISSUE TITLE
Copying A1.IList<B1> objects to B0 objects with an A0 property

### ISSUE THREAD

**Issue by mazloumi** [AutoMapper/AutoMapper#2608]
Hi,

I have the following scenario, where I need to copy from classes A1 and B1 to classes A0 and A0, where the classes have the following definition:

From:
class A1 {
IList<B1> Bs {get;set;}
}

class B1 {
A1 A1 {get;set;}
}

To; 
class A0 {
IQueryable<B0> Bs {get;}
}

class B0 {
A0 A0 {get;set;}
}

Now the copy process is as such: For every A1 create an A0 and for every B1 objects in the IList property where there is a corresponding IQueryable create a B0 object and set the property A0 to the value of A1.

Any thoughts?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
