### ISSUE TITLE
Following Issue #1839 with child collections

### ISSUE THREAD

**Issue by crkjl** [AutoMapper/AutoMapper#2609]
I'm not sure if this is an error or missconfiguration issue.
Following issue #1839 I'm able to ignore missing properties in destination object. The problem appear when some of these properties are child collections with also some properties missing in destination child collection. Take the sample of Customer / CustomerViewModel where not all properties in Customer appears in CustomerViewModel (i.e.: tracking properties) and Contact / ContactViewModel, where Contact / ContactViewModel are child collections in Customer / CustomerViewModel.
The problem: properties missing in ContactViewmodel are overwritten in Contacts (with null values) when mapping happends.

### Source/destination types
```
    public class Customer : BaseEntity
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CommercialName { get; set; }
        public string Cif { get; set; }
        public decimal Vat { get; set; }
        public bool TaxFree { get; set; }

        public int PaymentTermId { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }

        public virtual ICollection<Contact> Contacts { get; set; }
    }
```
```
    public class Contact : BaseEntity
    {
        public int ContactId { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }

        public int CustomerId { get; set; }
        public virtual Customer Customer { get; set; }
    }
```
```
    public class CustomerViewModel
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CommercialName { get; set; }
        public string Cif { get; set; }
        public decimal Vat { get; set; }
        public bool TaxFree { get; set; }
        public int PaymentTermId { get; set; }
        public virtual ICollection<ContactViewModel> Contacts { get; set; }
    }
```
```
    public class ContactViewModel
    {
        public int ContactId { get; set; }
        public int CustomerId { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
```

### Mapping configuration
```
            CreateMap<CustomerViewModel, Customer>(MemberList.Source);
            CreateMap<ContactViewModel, Contact>(MemberList.Source);
            CreateMap<AddressViewModel, Address>(MemberList.Source);

```

### Version: x.y.z
AutoMapper 6.2.2

### Expected behavior
Ignore missing properties in destination including child collections.

### Actual behavior
Properties missing in destination in child collections are initialized with default values.

### Steps to reproduce
`customer = _mapper.Map<CustomerViewModel, Customer>(model, customer);
`

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by crkjl** [comment]
Hi, Agree with you. I've opened the same question in [StackOverflow](https://stackoverflow.com/questions/49927047/automapper-how-to-ignore-missing-properties-in-destination-child-properties)
But, please, could you explain why this behavior is not a bug from AutoMapper?
Why MemberList.Source works fine in parent properties and not in child properties?

**Comment by lbargaoanu** [comment]
MemberList is just for [validation](http://automapperdocs.readthedocs.io/en/latest/search.html?q=memberlist&check_keywords=yes&area=default). It doesn't to anything for mapping.
