### ISSUE TITLE
Support async operation in ValueResolver 

### ISSUE THREAD

**Issue by j0nimost** [AutoMapper/AutoMapper#2615]
I  am using ASP.NET Core where am trying to resolve a User identity i.e ```Usermanager```

       var user = await this.userManager.FindByIdAsync(ClaimTypes.NameIdentifier);
but ValueResolver doesn't have an async method; since a good number of ASP.NET Core methods are ***ONLY*** Async is it possible to make ValueResolver  have Async methods?

**Comment by nukec** [comment]
I would like to join to this request

**Comment by jbogard** [comment]
Duplicate of #1226

**Comment by jbogard** [comment]
This would a *ton* of work. We'd have to build a completely parallel execution plan to the in-memory version, as anything that maps would need an async version. It wouldn't be just resolvers, either, from `Map` to resolvers, type converters, transformers, before/after map...it's a lot. Then on top of this, our core means of building out a mapping delegate, using expression trees, does not support async/await. 

So.... 🤷‍♂️
