### ISSUE TITLE
IMemberValueResolver issue with constructor with parameters

### ISSUE THREAD

**Issue by nukec** [AutoMapper/AutoMapper#2617]
For instance if I have IMemberValueResolver type:

    Mapper.Initialize(cfg => {
    cfg.CreateMap<Source, Destination>()
        .ForMember(dest => dest.Total,
            opt => opt.ResolveUsing<CustomResolver, decimal>(src => src.SubTotal));
    cfg.CreateMap<OtherSource, OtherDest>()
        .ForMember(dest => dest.OtherTotal,
            opt => opt.ResolveUsing<CustomResolver, decimal>(src => src.OtherSubTotal));
    });
    
    public class CustomResolver : IMemberValueResolver<object, object, decimal, decimal> {
        public decimal Resolve(object source, object destination, decimal sourceMember, decimal destinationMember, ResolutionContext context) {
    // logic here
        }
    }

What if my MemberValueResolver is accepting parameter in constructor like:

    public class CustomResolver : IMemberValueResolver<object, object, decimal, decimal> {
        public CustomResolver(string text){
        }
        public decimal Resolve(object source, object destination, decimal sourceMember, decimal destinationMember, ResolutionContext context) {
    // logic here
        }
    }

How do I then create map for custom resolver of type IMemberValueResolver?
We can try and supply instance directly:

    Mapper.Initialize(cfg => cfg.CreateMap<Source, Destination>()
        .ForMember(dest => dest.Total,
            opt => opt.ResolveUsing(new CustomResolver("Text"))
        );

But how in this case do we pass which source parameter do we want to use for mapping in resolver?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by nukec** [comment]
@lbargaoanu https://stackoverflow.com/questions/50097467/how-to-use-imembervalueresolver-with-constructor-argument can you contribute there then please?

**Comment by nukec** [comment]
Solution:
```
.ForMember(dest => dest.Total,
        opt => opt.ResolveUsing(new CustomResolver("argument"), src => src.SubTotal));
```
