### ISSUE TITLE
Transformator Services and extended DI capabilities

### ISSUE THREAD

**Issue by gromanev** [AutoMapper/AutoMapper#2619]
Hello. My suggestion to developers.
Once I had the need for a large number of Model-ViewModel transformations and vice versa. For this I used services that tagged with Postfix "Transformator", for example "UserTransformator".

I couldn't find your library immediately of such functionality and therefore decided to create a small addition to my way which will automatically find and use appropriate Transformator is. Example: _mapper. Map<User, userDto>(user);

I wrote a library and put it on Github and after some time I wrote my friend and say that you have something like that and has set an example, and Yes, there really was something similar to what I sold, but I have a few differences that can make it easier to work.
I will list them:
1. Maximum flexibility DI (no restrictions).
2. Service-Transormator contains not one method of converter and several that allows you to group methods in service-transformers.
3. Good speed.
4. Usability is absolutely the same as the Automapper.

My proposal is not to replace existing functionality and complement to the user had a choice.

Below I have attached a link to the source code of my project, and if you become interested, I could make PR.

Ready to hear your opinion about this idea. Sincerely, gromanev.

LynxMapper: https://github.com/gromanev/LynxMapper

**Comment by lbargaoanu** [comment]
We already have #1414 and plans for #2367. We also have value resolvers and type converters. Maybe you have some concrete proposals to improve one of the existing features.

**Comment by gromanev** [comment]
My way is alternative and involves manual conversion, which gives more flexibility, but works differently than your product.

**Comment by lbargaoanu** [comment]
OK, then I'm not sure there is a way forward here. cc @jbogard

**Comment by jbogard** [comment]
Yeah, I'm not sure either, this looks like pure manual mapping, instead of Auto-mapping.
