### ISSUE TITLE
Automapper tries to create instance of abstract class when the source property is null

### ISSUE THREAD

**Issue by joostjens** [AutoMapper/AutoMapper#2620]
In the attached code, I am mapping a Class to a DTO. One of the properties (and abstract class) is null, but AutoMapper tries to instantiate it anyway and I have no idea why since other properties in the class that are null as well do not get instantiated and I explicitly set the cfg.AllowNullDestinationValues to true. (which is the default anyway).

### Expected behaviour
Destination property value is null;

### Actual behavior
AutoMapper tries to instantiate and abstract class.

### Steps to reproduce

Attached is a code sample to reproduce the issue.
[AutomapperTest.zip](https://github.com/AutoMapper/AutoMapper/files/1964668/AutomapperTest.zip)

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by lbargaoanu** [comment]
The default naming convention combined with [reverse mapping](http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html) is causing this. You can give up ReverseMap (explicitly create the reverse map) or actually isolate the issue and skip that step.

**Comment by lbargaoanu** [comment]
Regarding the docs, a PR is welcome.

**Comment by joostjens** [comment]
I am not sure what you mean by that (Sorry, English is not my main language). Do you mean "proof read"?

**Comment by lbargaoanu** [comment]
Github lingo, pull request. You can easily change the docs to make things clearer.

**Comment by joostjens** [comment]
I am not sure how to do it, so to prevent messing things up I rather don't.
Thanks for your assistance once again though, it's invaluable.
