### ISSUE TITLE
Automapper Unit Testing " Mapper not initialized." Issue

### ISSUE THREAD

**Issue by KaboomPT** [AutoMapper/AutoMapper#2623]
Hello,

We are having an issue using Mapper.Map inside "AfterMap" when running unit tests as specified in this SO question https://stackoverflow.com/questions/50288088/automapper-flattening-common-nested-relationship.

This probably isn't a bug. It's more of a question that we would appreciate if you could provide some insights.

Best Regards

**Comment by lbargaoanu** [comment]
I'll respond over there.
