### ISSUE TITLE
Map Constructors automatically

### ISSUE THREAD

**Issue by endeffects** [AutoMapper/AutoMapper#2625]
Do you have any plans to map custom constructors automatically without the need to specify them by using .ConstructUsing(e => new Something(e.One, e.Two)

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Construction.html

**Comment by endeffects** [comment]
Oh thanks, i thought it is not possible. It was not working because of a complex parameter type on the destination.
