### ISSUE TITLE
DateTime? = null field in Expando Source Type will not update Destination

### ISSUE THREAD

**Issue by cli-iftaft** [AutoMapper/AutoMapper#2629]
### Source/destination types

Source Type = ExpandoObject
Destination Type = Static Class

### Mapping configuration

Default Config

### Version: x.y.z
6.2.2

### Expected behavior

Destination should be set to null

### Actual behavior

Source is ignored and destination keeps its original value

### Steps to reproduce
`public class Dates
{
      public DateTime NormalDate;
      public DateTime? NullableDate;
}

dynamic source = new System.Dynamic.ExpandoObject();
source.NormalDate = new DateTime(1, 1, 1);
source.NullableDate = null;

Dates destination = new Dates();
destination.NormalDate = new DateTime(2, 2, 2);
destination.NullableDate = new DateTime(2, 2, 2);

var result = Mapper.Map(source,destination);

Console.WriteLine(result.NomalDate); // {1/1/0001 12:00:00 AM} gets updated as expected
Console.WriteLine(result.NullableDate); //{2/2/0002 12:00:00 AM} should be null`

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build or the latest from [NuGet](https://www.nuget.org/packages/AutoMapper/7.0.0-alpha-0001).
