### ISSUE TITLE
Add repository information to nuget package

### ISSUE THREAD

**Issue by samneirinck** [AutoMapper/AutoMapper#2631]
Nuget provides elements to specify where the source code repository is for a nuget package, by specifying a [repository element](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L67).

It would be great if we had this information straight into the .nuspec, which would allow tooling such as [renovate](https://renovatebot.com/) to fetch detailed information about releases (what specifically has been fixed).

I can create a PR for this if this sounds ok.

**Comment by lbargaoanu** [comment]
Some quick feedback. If I were to guess, I'd say @jbogard wouldn't mind it :) But if you want to be sure, you should wait till he gets a chance to respond.

**Comment by jbogard** [comment]
Fine by me!
