### ISSUE TITLE
Exception when mapping from an ExpandoObject.

### ISSUE THREAD

**Issue by ericrey85** [AutoMapper/AutoMapper#2633]
Version 6.2.2.0

When mapping from a source ExpandoObject that contains a property that is a Value Type in the destination type, like int, if the value of that property in the ExpandoObject is null, AutoMapper throws an "Object not set to an instance of an object" exception. If you change the int to int? the problem goes away.

**Comment by lbargaoanu** [comment]
That doesn't sound that bad. But other than that, a PR is welcome.
