### ISSUE TITLE
Order issue with nested types

### ISSUE THREAD

**Issue by IvelinM** [AutoMapper/AutoMapper#2638]
Description:
- TableDbEntity has CupDbEntity
- CupDbEntity has FormulaDbEntity
- States representations have the same relations
With the following configuration I don't have a problem on Automapper version 6.1.1 but when upgrading on 6.2.2. I get mapping exception for a property in FormulaDbEntity saying: 

> Unmapped members were found. Review the types and members below. Add a custom mapping expression, ignore, add a custom resolver, ...

But this is not true - I have all the needed mappings and when I reorder the mapping configuration 
with the FormulaDbEntity above CupDbEntity and CupDbEntity above TableDbEntity it starts working. When downgrading to 6.1.1. also works without this reorder.

Mapping configuration:
```
cfg.CreateMap<CupDbEntity, CupState>();
cfg.CreateMap<CupDbEntity, ICupState>()
                .As<CupState>();
cfg.CreateMap<TableDbEntity, TableState>();
cfg.CreateMap<TableDbEntity, ITableState>()
                .As<TableState>();
cfg.CreateMap<FormulaDbEntity, FormulaState>();
cfg.CreateMap<FormulaDbEntity, IFormulaState>()
                .As<FormulaState>();
```

Version: 
6.2.2

Expected behavior:
Map nested types without depending on configurations order

Actual behavior
Upgrading to 6.2.2. starts exception throwing because of missing mappings and when ordered differently, exceptions stop from being thrown.

### Steps to reproduce

1. Install Automapper 6.2.2.
2. Map at least three nested types
3. Order them with the parent on the upper row

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
One thing you can try is setting CreateMissingTypeMaps to false.
