### ISSUE TITLE
N+1 issue on EF Core 2.1.x

### ISSUE THREAD

**Issue by benmccallum** [AutoMapper/AutoMapper#2639]
### Source/destination types

```csharp
[Table("Booking")]
public class Booking
{
    public Booking()
    {
        BookingItems = new HashSet<BookingItem>();
    } 

    public int Id { get; set; }
    public virtual ICollection<BookingItem> BookingItems { get; set; }
}

[Table("BookingItem")]
public class BookingItem
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class BookingDto
{
    public int Id { get; set; }    
    public ICollection<BookingItemDto> BookingItems { get; set; }
}

public class BookingItemDto
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Booking, BookingDto>()
    .ForAllMembers(x => x.ExplicitExpansion());
cfg.CreateMap<BookingItem, BookingItemDto>();
```

### Version: x.y.z

```xml
<PackageReference Include="AutoMapper" Version="6.2.2" />
<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.2.0" />
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-rc1-final" />
```

### Expected behavior

I'd expect that when executing the map code (see lower section) that EF Core would run a single SELECT statement to the DB. 

I've read some other issues here that mention:
1) That you need to manually call `.Include(x => x.BookingItems)` as EF Core doesn't support that, but when I do it there is no difference, and I believe it's because I see an EF Core log of: `Microsoft.EntityFrameworkCore.Query:Warning: The Include operation for navigation '[dto].BookingItems' is unnecessary and was ignored because the navigation is not reachable in the final query results. See [https://go.microsoft.com/fwlink/?linkid=850303](https://go.microsoft.com/fwlink/?linkid=850303) for more information.` So it's looking like this is an EF Core issue, and I can raise it there if that's the case, just wanted to get some feedback here first.

2) The nested projection won't be optimised but call all fields (seems to be addressed by [this](https://github.com/aspnet/EntityFrameworkCore/issues/4007) now and in version I'm using)

### Actual behavior

EF Core runs an N+1, like this:

```
...
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (23ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT TOP(@__p_0) [dto].[Id],
FROM [Booking] AS [dto]
ORDER BY [dto].[Id]
...
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (6ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [dto.BookingItems].[Id], [dto.BookingItems].[Name]
FROM [BookingItem] AS [dto.BookingItems]
INNER JOIN (
    SELECT TOP(@__p_0) [dto0].[Id]
    FROM [Booking] AS [dto0]
    ORDER BY [dto0].[Id]
) AS [t] ON [dto.BookingItems].[BookingId] = [t].[Id]
ORDER BY [t].[Id]
...
```

### Steps to reproduce

```csharp
_dbContext.Bookings
    .AsNoTracking()
    .Take(1)
    .ProjectTo<BookingDto>(null, new [] { "Id", "BookingItems" })
    .ToArrayAsync();
```

### Other notes

It seems strange as well because EF Core logs the following (and some other similar stuff but that's the basic gist). So it's almost as if it's aware but still goes and does N+1 queries.

```
Microsoft.EntityFrameworkCore.Query:Debug: Optimized query model: 
'(from Booking dto in DbSet<Booking>
select new BookingDto{ 
    Id = [dto].Id, 
    BookingItems = List<BookingItemDto> ToList(
            from BookingItem dto in DbSet<BookingItem>
            where  ?= Property([dto], "Id") == Property([dto], "Id") =? 
            select new BookingItemDto{ 
                Id= [dto].Id, 
                Name= [dto].Name
            }
    ) 
}
).Take(__p_0)'
```

**Comment by lbargaoanu** [comment]
Try it with EF6, or try the select without AM.

**Comment by benmccallum** [comment]
Will do just that shortly, thx.

**Comment by benmccallum** [comment]
Repro sln .zip file uploaded here: [EfAutomapperTroubleshooting.zip](https://github.com/AutoMapper/AutoMapper/files/2024473/EfAutomapperTroubleshooting.zip)

So basically there's two problems when running on EF Core 2.1.x:
1. The JOIN required isn't "figured out" automatically.
2. Trying to force the JOIN with `.Include(b => b.BookingItems)` doesn't work either as EF Core is trying to be clever and save us the JOIN even though we know better :wink:

Obviously issue 2 is with EF Core, but without knowing AutoMapper's internals confirmation on where issue 1 lies would be great. My assumption is EF Core but would be great to get an expert's opinion.

**Comment by benmccallum** [comment]
I also tried the following LINQ query and there is the same 2 queries generated. Have logged with EF Core team as well.

```csharp
bookingDtos = db.Bookings
    .AsNoTracking()
    .Select(b => new BookingDto
    {
        Id = b.Id,
        Name = b.Name,
        BookingItems = b.BookingItems.Select(bi => new BookingItemDto
        {
            Id = bi.Id,
            Name = bi.Name
        }).ToList()
    })
    .ToArray();
```

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [b].[Id], [b].[Name]
      FROM [Booking] AS [b]
      ORDER BY [b].[Id]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [b.BookingItems].[Id] AS [Id0], [b.BookingItems].[Name], [b.BookingItems].[BookingId]
      FROM [BookingItem] AS [b.BookingItems]
      INNER JOIN (
          SELECT [b0].[Id]
          FROM [Booking] AS [b0]
      ) AS [t] ON [b.BookingItems].[BookingId] = [t].[Id]
      ORDER BY [t].[Id]
```

**Comment by lbargaoanu** [comment]
It's EF Core. We just generate the LINQ statement. So if the LINQ statement looks good, our job ends here. Anyway, nice to see someone taking the time to make a thorough investigation.

**Comment by benmccallum** [comment]
They came back to me and said it's by design. Full comments on their ticket. Tend to agree with their choice on this one. Thanks nonetheless.

**Comment by VictorioBerra** [comment]
@benmccallum When you said they came back to me, what avenue did you contact them through? Just the EF issue tracker?

**Comment by benmccallum** [comment]
@VictorioBerra, yea exactly. See the auto issue reference further up.
