### ISSUE TITLE
ProjectTo seems to generate a massive number of queries

### ISSUE THREAD

**Issue by VictorioBerra** [AutoMapper/AutoMapper#2643]
I have a simple many-to-many relationship and a very minimal AutoMapper Configuration. When I execute a `ProjectTo<InventoryServerViewModel>()` I get a separate query for every single row found, this is NOT the case when doing:

```csharp
query
    .Include(x => x.InventoryServerProductLines)
        .ThenInclude(x => x.Product);
```

### Profile
```csharp
CreateMap<WuitInventoryServer, InventoryServerPageJsonViewModel>(MemberList.Destination);
```
### EF Classes
```csharp
public class InventoryServer
{
    public WuitInventoryServer()
    {
        this.InventoryServerProductLines = new HashSet<InventoryServerProductLine>();
    }

    public int Id { get; set; }
    public ICollection<InventoryServerProductLine> InventoryServerProductLines { get; set; }
}

public class WuitInventoryServerProductLine
{

    // Composite Key
    public virtual int InventoryServerId { get; set; }
    public virtual int ProductId { get; set; }

    public InventoryServer InventoryServer { get; set; }
    public Product Product { get; set; }
}

public class Product
{
    public Product()
    {
        this.InventoryProductLines = new HashSet<InventoryServerProductLine>();
    }

    public ICollection<InventoryServerProductLine> InventoryProductLines { get; set; }
}
```

The ViewModels are identical to the EF entities. I have tried passing an include expression to ProjectTo and this does not seem to change a thing. 

For completeness here is one of the many separate queries out to get a Product, I have redacted a few columns for brevity.

```sql
exec sp_executesql N'SELECT [dto0].[Id], [dto0].[InventoryServerId], [dto0].[ProductId] AS [Id0], CASE
    WHEN [dto0].[ProductId] IS NOT NULL
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
FROM [InventoryProduct] AS [dto0]
INNER JOIN [Product] AS [dto.Product] ON [dto0].[ProductId] = [dto.Product].[Id]
WHERE @_outer_Id = [dto0].[InventoryServerId]',N'@_outer_Id int',@_outer_Id=22
```

**Comment by TylerCarlson1** [comment]
If the view models are identical to EF then what you have is a circular dependency going back from Product to InventoryServer.  That might be calling the extra mappings, because when you include you are only going down to product and not back up.

If you remove InventoryProductLines from the VM or ignore it then it won't have the circular reference and won't have the extra calls.  Your view models should not have circular dependencies cause it causes so many problems handling those situations

**Comment by VictorioBerra** [comment]
@TylerCarlson1 I was careful to avoid that and commented out `InventoryServerProductLine.InventoryServer` on my ViewModel.

I need all products associated with an inventory hence the need for `InventoryServerProductLine.Product`. If you can think of anything else that might be the issue I would appreciate it. First thing tomorrow I will try and create a minimal EF Core app that replicates the issue.

I also tested commenting out BOTH `InventoryServer` and `Product` from the many-to-many table `WuitInventoryServerProductLine` and it still created a call for every single record. It now generates this query:

```sql
exec sp_executesql N'SELECT [dto].[Id], [dto].[InventoryServerId], [dto].[ProductId]
FROM [InventoryServerProduct] AS [dto]
WHERE @_outer_Id = [dto].[InventoryServerId]',N'@_outer_Id int',@_outer_Id=5
```

**Comment by TylerCarlson1** [comment]
The other thing you can do is try to replicate the call using Select statement and see if that works the way you intended.  What ProjectTo does is makes a select statement and that gets translated into queries that will call to the Database.  If you make a select statement of what you want and it still gives multiple calls then it's something with EF.Core.  If not then there might be some way the query was generated that would cause this to happen.

**Comment by TylerCarlson1** [comment]
Oh sorry one more thing I see.  Are you using SingleOrDefault or FirstOrDefault?  What I think ProjectTo does in a single instance is map over the value instead of generating the SQL statement.  I could be wrong on that I'm not 100% sure, but try to list then First or default and maybe that will help.

Another thing could be how the query is set up and it depends on where you do your filtering at.  Before or after the projection.  This is another shot in the dark.

**Comment by VictorioBerra** [comment]
I appreciate the shots in the dark, I had to clean up a lot of the code around the query to isolate it enough before I wanted to post here looking for help.

I just switched everything to a select and the query turned into one single query. So tomorrow I guess i will have to get you guys a sample app so we can isolate and explore further.

**Comment by VictorioBerra** [comment]
```csharp
            var responseViewModel = query
                .AsNoTracking()
                .ProjectTo<InventoryServerPageJsonViewModel>()
                //.Select(x => new InventoryServerPageJsonViewModel() {
                //    InventoryServerProductLines = x.InventoryServerProductLines.Select(y => new InventoryServerProductLineViewModel() {
                //        Product = new ProductViewModel() {
                //            Id = y.Product.Id
                //        }
                //    })
                //})
```

The commented code results in a single query

**Comment by lbargaoanu** [comment]
If it's EF Core, you need the Includes. Otherwise we need a repro.

**Comment by VictorioBerra** [comment]
@TylerCarlson1 @lbargaoanu  https://github.com/VictorioBerra/AutoMapper.QueryableExtensions.Issue2643

I have created a minimal example showing the issue I am having. This is a Console netcoreapp2.0. It uses LocalDb via `UseSqlServer()` and you can create the DB with `dotnet ef database update -c MyDbContext`. It will also self-seed.

`git clone https://github.com/VictorioBerra/AutoMapper.QueryableExtensions.Issue2643.git`

### I show three examples:

- **Program.cs Example A**
  - Regular `ProjectTo()` - Results in a second query per parent record.
- **Program.cs Example C**
  - `Include()`, `ThenInclude()` - same issue as above
- **Program.cs Example D**
  - Manually projecting with `.Select()`s - same issue as above
- **Program.cs Example E**
  - No projections at all. - Much better, only generates two queries no matter how many records there are. I am not sure why there are two still though.

**Comment by lbargaoanu** [comment]
Related to #2639. As long the manual LINQ statement generates the same SQL, there is nothing to do here as far as AM is concerned.

**Comment by VictorioBerra** [comment]
Thanks for letting me know about the related issue.

**Comment by VictorioBerra** [comment]
For anyone using EF Core https://github.com/aspnet/EntityFrameworkCore/issues/9282
