### ISSUE TITLE
cfg.Condition is not being respected

### ISSUE THREAD

**Issue by mrpmorris** [AutoMapper/AutoMapper#2644]
Gist: https://gist.github.com/mrpmorris/5804406dddcd9f015ef05aee8a68e877

### Source/destination types

```csharp
  public class Source
  {
    public string Codes { get; set; }
  }

  public class Dest
  {
    public List<string> Codes { get; set; }
  }
```

### Mapping configuration

```csharp
      Mapper.Initialize(cfg =>
      {
        cfg.CreateMap<Source, Dest>()
           .ForMember(target => target.Codes, config =>
           {
             config.Condition(source => !string.IsNullOrWhiteSpace(source.Codes));
             config.ResolveUsing(source => source.Codes.Split(',').Select(code => code.Trim()));
           });
      });
```

### Expected behavior

ResolveUsing should not be executed

### Actual behavior

ResolveUsing is executed, resulting in a NullReferenceException

### Steps to reproduce

```csharp
      Source s = new Source() { Codes = "1" };
      Dest d = Mapper.Instance.Map<Dest>(s);
```

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Conditional-mapping.html#preconditions

**Comment by mrpmorris** [comment]
I can't make sense of the docs linked. Would you mind explaining it? If so then I will change the docs and submit a pull-request.

**Comment by lbargaoanu** [comment]
The thing is, I wrote that myself and is the best I can do. A PR is welcome. There is also [this](https://github.com/AutoMapper/AutoMapper/blob/master/docs/Editing-Resolvers-and-Conditions.md), but that seems to be missing from the published docs. At least I'm unable to find it. So if that's better we can try to have that published too.

**Comment by mrpmorris** [comment]
To be clear (sorry). "You need to check for null values in the ResolveUsing code because ResolveUsing is executed first, and then the Condition is evaluated to determine whether or not to assign the resulting value to the destination" - Is that correct? If so, am I correct in assuming it is also the case for MapFrom?

**Comment by lbargaoanu** [comment]
Yes, or use a PreCondition.

**Comment by mrpmorris** [comment]
Pull request added for the docs.
https://github.com/AutoMapper/AutoMapper/pull/2650
