### ISSUE TITLE
Entity Framework Core 2.1.0-rc1-final breaks ProjectTo

### ISSUE THREAD

**Issue by VictorioBerra** [AutoMapper/AutoMapper#2645]
I recently created a [sample app](https://github.com/VictorioBerra/AutoMapper.QueryableExtensions.Issue2643) for another [issue](https://github.com/AutoMapper/AutoMapper/issues/2643) I posted, essentially, [EF Core has optimized correlated collections so that they don't result in N+1 database queries](https://github.com/aspnet/EntityFrameworkCore/issues/9282).

Now, testing this was as easy as updating all the EF Core NuGet packages to pre-release in the above sample app. The reason I am creating this issue now is that this works:

```csharp
// Example C: This is supposed to be effectively what `ProjectTo()` does. However, this still generates extra queries.
//
var records = context
.InventoryServer
.Select(x => new InventoryServerDto()
{
    Id = x.Id,
    Name = x.Name,
    InventoryServerProductLines = x.InventoryServerProductLines.Select(y => new InventoryServerProductLineDto()
    {
        InventoryServerId = y.InventoryServerId,
        ProductId = y.ProductId,
        Product = new ProductDto()
        {
            Id = y.Product.Id,
            Name = y.Product.Name
        }
    }).ToList()
})
.ToList();
```

But this does not:

```csharp
// Example A: This generates a seperate query PER InventoryServer row.
// See README.md
//
var records = context
.InventoryServer
.ProjectTo<InventoryServerDto>()
.ToList();
```

The resulting error is:

> System.InvalidOperationException: 'No mapping to a relational type can be found for the CLR type 'ProductDto'.'

It sounds to me like EF Core does not like whatever `ProjectTo` hands it when it does to execute the query via the `ToList` call. I believe that this will become a larger issue once EF Core 2.1 is released which is coming very soon.

**Comment by jbogard** [comment]
What is the LINQ Select projection that's created? And can you hand-make a Select projection that works?

**Comment by VictorioBerra** [comment]
@jbogard In the example project linked above, if I comment out the `ProjectTo` and un-comment the hand made selection, the code works.

How do I determine what LINQ Select Projection is created from `ProjectTo`?

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by VictorioBerra** [comment]
@jbogard @lbargaoanu this is everything from the DebugView:

```
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer]),
    '(.Lambda #Lambda1<System.Func`2[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer,AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerDto]>))

.Lambda #Lambda1<System.Func`2[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer,AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerDto]>(AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer $dto)
{
    .New AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerDto(){
        Id = $dto.Id,
        Name = $dto.Name,
        InventoryServerProductLines = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $dto.InventoryServerProductLines,
                .Lambda #Lambda2<System.Func`2[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServerProductLine,AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerProductLineDto]>)
        )
    }
}

.Lambda #Lambda2<System.Func`2[AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServerProductLine,AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerProductLineDto]>(AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServerProductLine $dto)
{
    .New AutoMapper.QueryableExtensions.Issue2643.DTOs.InventoryServerProductLineDto(){
        InventoryServerId = $dto.InventoryServerId,
        ProductId = $dto.ProductId,
        Product = .If ($dto.Product != null) {
            .New AutoMapper.QueryableExtensions.Issue2643.DTOs.ProductDto(){
                Id = ($dto.Product).Id,
                Name = ($dto.Product).Name
            }
        } .Else {
            null
        }
    }
}
```

**Comment by lbargaoanu** [comment]
You either install that VS extension or you write a readable query by hand :)

**Comment by lbargaoanu** [comment]
You should modify the query you wrote above to look as close as possible to the one in DebugView. The result should be that you get the same exception, but AM is not involved.

**Comment by VictorioBerra** [comment]
Okay @lbargaoanu so the only difference between my query and the generated query from `ProjectTo` was that you guys generate some type of nullable conditional. The code below emits the error:

```csharp
var query = context
.InventoryServer
.Select(x => new InventoryServerDto()
{
    Id = x.Id,
    Name = x.Name,
    InventoryServerProductLines = x.InventoryServerProductLines.Select(y => new InventoryServerProductLineDto()
    {
        InventoryServerId = y.InventoryServerId,
        ProductId = y.ProductId,
        Product = y.Product == null ? new ProductDto()
        {
            Id = y.Product.Id,
            Name = y.Product.Name
        } : null
    }).ToList()
});
var records = query.ToList();
```

## Comparison (`ProjectTo()` vs Manual Select)
![image](https://user-images.githubusercontent.com/2934507/40497695-808b88bc-5f42-11e8-9518-7d95ac2e0bf2.png)

So how do we go about fixing this? How can I tell ProjectTo not to add that conditional, and maybe more importantly, why does EF Core blow up when we do this? Would we consider that a bug?

**Comment by VictorioBerra** [comment]
I created a new issue https://github.com/aspnet/EntityFrameworkCore/issues/12136

turns out its a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/11937

the issue will be fixed before release.

**Comment by lbargaoanu** [comment]
You can set [AllowNull](https://github.com/AutoMapper/AutoMapper/blob/01a4010e252f4a5763848c70313491854f9ba74c/src/AutoMapper/IMemberConfigurationExpression.cs#L125l) on the property to work around the issue.

**Comment by VictorioBerra** [comment]
Thanks for letting me know. I may just wait for the official 2.1 release and deal with slow performance as a trade off of using that + pre releases of EF.
