### ISSUE TITLE
AutoMapper inherintance with "new" modifier

### ISSUE THREAD

**Issue by gbaccianti** [AutoMapper/AutoMapper#2646]
I'm updating my project from AutoMapper version 4.2.1 to 6 and, in the new version, I get an unexpected behaviour.

### Classes

```csharp
class Opportunity : OpportunityLite
{
}

class OpportunityLite
{
	public DealerOpportunityLite DealerOpportunity { get; set; }
}

class DealerOpportunity : DealerOpportunityLite
{
	public new string BranchCode { get; set; }
}

class DealerOpportunityLite
{
	public string BranchCode { get; set; }
}
```

### Mapping configuration

```csharp
	AutoMapper.Mapper.Initialize(cfg =>
	{
		cfg.CreateMap<Opportunity, OpportunityLite>();
		cfg.CreateMap<DealerOpportunity, DealerOpportunityLite>();
	});
```

### Version: 4.2.1
If I execute the following Map:

```csharp
	Opportunity oppLite = new Opportunity
	{
		DealerOpportunity = new DealerOpportunity
		{
			BranchCode = "00168"
		}
	};

	var opp = AutoMapper.Mapper.Map<Opportunity, OpportunityLite>(oppLite);
```
The property value of "opp.DealerOpportunity.BranchCode" is: 00168

### From Version 5.0.2 to 6.2.2
In these versions the value of the same property is: null

How can I update AutoMapper to get the same result of version 4.2.1 without adding "ForMember" in the mapping configuration?
Unfortunately, I have so many cases of this classes schema.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
