### ISSUE TITLE
Initial load is very slow.

### ISSUE THREAD

**Issue by shashi20171008** [AutoMapper/AutoMapper#2647]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration
namespace *****.****.App_Start
{
    using AutoMapper;
    using *****.****.Authorization;
    using DTOs = *****.****.DTO;
    using Models = *****.****.Core.Models;

    /// <summary>
    /// Automapper config.
    /// </summary>
    public class AutoMapperConfig
    {
        /// <summary>
        /// Creates mappings for automapper.
        /// </summary>
        /// <returns>Mapping configuration.</returns>
        public static IMapper GetMapperInstance()
        {
            var config = new MapperConfiguration(cfg =>
            {
                GetDTOModelMappings(cfg);
                //GetModelEntityMappings(cfg);
            });

            IMapper mapper = config.CreateMapper();
            return mapper;
        }

        private static void GetDTOModelMappings(IMapperConfigurationExpression config)
        {
            // dto model mappings: //source to dest

            config.CreateMap<Models.UserCredentials, UserClaim>()
            .ForMember(x => x.GssCodesUserId, y => y.MapFrom(z => z.UserId))
            .ForMember(x => x.GallupClientId, y => y.MapFrom(z => z.ClientId))
            .ForMember(x => x.Id, y => y.MapFrom(z => z.GssUserId))
            .ForMember(x => x.ClientName, y => y.MapFrom(z => z.OmsClientName))
            .ForMember(x => x.Name, y => y.MapFrom(z => z.FirstName))
            .ForMember(x => x.FamilyName, y => y.MapFrom(z => z.LastName))
            .ForMember(x => x.HasTop5, y => y.MapFrom(z => z.HasTop5Role))
            .ForMember(x => x.HasAll34, y => y.MapFrom(z => z.HasAll34Role))
            .ReverseMap();

            config.CreateMap<DTOs.AccessCode, Models.AccessCodeModel>()
            .ReverseMap();

            config.CreateMap<DTOs.AddPermissionToUser, Models.BucketPermissionModel>()
            .ForMember(x => x.PermissionTypeId, y => y.MapFrom(z => z.PermissionId))
            .ReverseMap();

            config.CreateMap<DTOs.CreateBucketRequest, Models.CreateBucketModel>()
            .ReverseMap();

            config.CreateMap<DTOs.Bucket, Models.BucketModel>()
            .ReverseMap();

            config.CreateMap<DTOs.UpdateBucketRequest, Models.UpdateBucketModel>()
            .ReverseMap();

            config.CreateMap<DTOs.AddSeatsFromPurchaseRequest, Models.AddSeatsByTypeModel>()
            .ReverseMap();

            config.CreateMap<DTOs.InviteUser, Models.InviteUserModel>()
            .ReverseMap();

            config.CreateMap<DTOs.Invite, Models.InviteModel>()
            .ReverseMap();

            config.CreateMap<DTOs.BucketInfo, Models.BucketSeatModel>()
            .IncludeBase<DTOs.Bucket, Models.BucketSeatModel>()
            .ReverseMap();

            config.CreateMap<Models.AddPermissionModel, DTOs.AddPermissionToUser>()
            .ForMember(x => x.PermissionId, y => y.MapFrom(z => z.PermissionTypeId))
            .ReverseMap();

            //all transfer related mappings
            config.CreateMap<Models.AddSeatsByTypeModel, DTOs.AddSeatsRequest>()
            .IncludeBase<Models.AddSeatsModel, DTOs.AddSeatsRequest>()
            .ForMember(x => x.NumberOfSeats, y => y.MapFrom(z => z.Quantity))
            .ForMember(x => x.CodeType, y => y.MapFrom(z => z.CodeTypeId))
            .ReverseMap();

            config.CreateMap<Models.AddSeatsToBucketModel, DTOs.AddSeatsRequest>()
            .IncludeBase<Models.AddSeatsModel, DTOs.AddSeatsRequest>()
            .ForMember(x => x.NumberOfSeats, y => y.MapFrom(z => z.Quantity))
            .ForMember(x => x.BucketId, y => y.MapFrom(z => z.ToBucketId))
            .ReverseMap();

            config.CreateMap<Models.TransferSeatsModel, DTOs.AddSeatsRequest>()
            .IncludeBase<Models.AddSeatsToBucketModel, DTOs.AddSeatsRequest>()
            .IncludeBase<Models.AddSeatsModel, DTOs.AddSeatsRequest>()
            .ForMember(x => x.BucketId, y => y.MapFrom(z => z.ToBucketId))
            .ReverseMap();

            config.CreateMap<Models.TransferSeatsModel, DTOs.TransferSeatsRequest>()
            .IncludeBase<Models.AddSeatsToBucketModel, DTOs.TransferSeatsRequest>()
            .IncludeBase<Models.AddSeatsModel, DTOs.TransferSeatsRequest>()
            .ForMember(x => x.NumSeats, y => y.MapFrom(z => z.Quantity))
            .ReverseMap();

            //End transfer mappings
            config.CreateMap<DTOs.User, Models.UserModel>()
            .ReverseMap();

            config.CreateMap<DTOs.ClientCodeResponse, Models.ValidAccessCode>()
            .ForMember(x => x.CodeTypeId, y => y.MapFrom(z => z.Type))
            .ReverseMap();
        }
    }
}
```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
Upgrade. If you're on the latest, we need a repro.

**Comment by shashi20171008** [comment]
@lbargaoanu  I am on version 6.  Are you suggesting to upgrade to v7?
