### ISSUE TITLE
How can I add new mapper to the already Initialized Mapper?

### ISSUE THREAD

**Issue by OneOfBestMan** [AutoMapper/AutoMapper#2648]
As methioned in the title, I have several libs, each of them call   Mapper.Initialize to initalize the mapper,but this will cause error  "Mapper already initialized.". So  how can add the new mapper to a exist mapper?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/stable/Configuration.html#profile-instances

**Comment by ramos41** [comment]
I studied the document but could not understand it. Could you please share some more detailed example?
