### ISSUE TITLE
ReverseMap creates object for navigation property #2151

### ISSUE THREAD

**Issue by Kaushik1987** [AutoMapper/AutoMapper#2649]
### Version: x.y.z
 6.2.2.0

### Expected behavior

I have the same issue but bit strange, I have 2 different model & their 2 different viewmodel. One is working fine and for another one automapper creates instance of null navigation property.

Isn't it weird? that it has different behaviour for 2 similar entities under same project.

I am using automapper version. 6.2.2.0

### Actual behavior

 I have 2 different model & their 2 different viewmodel. One is working fine and for another one automapper creates instance of null navigation property.

**Comment by lbargaoanu** [comment]
See [this](http://automapperdocs.readthedocs.io/en/latest/Reverse-Mapping-and-Unflattening.html). If you don't want that, just don't use ReverseMap, create by hand the reverse map.
