### ISSUE TITLE
Queryable extension and NotMapped, EF6

### ISSUE THREAD

**Issue by JanDrozen** [AutoMapper/AutoMapper#2653]
### Source/destination types

```csharp
public class TestReadModel
    {
        public string TestPayload { get; set; }
        [NotMapped]
        public string ComputedProperty => "I am not persisted!";
    }
public class TestDto
    {
        public string TestPayload { get; set; }
        public string ComputedProperty { get; set; }
    }
```

### Mapping configuration

```csharp
config.CreateMap<TestReadModel, TestDto>();
```

### Version: 6.2.2
 
6.2.2
### Expected behavior

I expect in the result DTO will be the actual value of the TestPayload property and in the ComputedProperty will be the value "I am not persisted!" and the query generated in background will not inspect the ComputedProperty at all.
### Actual behavior

System.NotSupportedException: 'The specified type member 'ComputedProperty' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.'

The query obviously tries to load the ComputedProperty from the database.
### Steps to reproduce

```csharp
var x = crudRepo.FindAll<TestReadModel>().ToList(); //OK
var xx = crudRepo.FindAll<TestReadModel>().ToList().Select(Mapper.Map<TestDto>).ToList();//OK
var xxx = crudRepo.FindAll<TestReadModel>().ProjectTo<TestDto>().ToList(); //<--- here comes the exception
```

**Comment by lbargaoanu** [comment]
The only way out is to ignore TestDto.ComputedProperty.
