### ISSUE TITLE
Map fails when profile is added

### ISSUE THREAD

**Issue by Nodios** [AutoMapper/AutoMapper#2654]
I am using mapping by convention and have issues when adding profile to the configuration. Consider configuration below. I am using AutoFac to resolve profiles in CoreMapper and the profiles are correctly injected.

### Source/destination types
Not required

### Mapping configuration

```csharp
public CoreMapper(IEnumerable<Profile> profiles)
{
    MapperConfiguration = new MapperConfiguration(cfg =>
    {
        cfg.CreateMissingTypeMaps = true;
        cfg.AllowNullCollections = true;
	cfg.AllowNullDestinationValues = true;
        cfg.ForAllMaps((mapType, mapperExpression) =>
        {
		mapperExpression.PreserveReferences();
		mapperExpression.MaxDepth(10);
        });
		cfg.IgnoreUnmapped();
        foreach (var profile in profiles)
        {
            cfg.AddProfile(profile);
        }
	cfg.CreateMap<string, string>().ConvertUsing(str => string.IsNullOrEmpty(str) ? null : str);
    });
    Mapper = MapperConfiguration.CreateMapper();
}
```

IgnoreUnmapped is as follows:
```csharp
private static void IgnoreUnmappedProps(TypeMap map, IMappingExpression expression)
{
	foreach(var propName in map.GetUnmappedPropertyNames())
	{
		if (map.SourceType.GetProperty(propName) != null)
			expression.ForSourceMember(propName, opt => opt.Ignore());
		if (map.DestinationType.GetProperty(propName) != null)
			expression.ForMember(propName, opt => opt.Ignore());
	}
}

public static void IgnoreUnmapped(this IProfileExpression profile)
{
	profile.ForAllMaps(IgnoreUnmappedProps);
}
```

In my code I have a generic class implementation with the line like this:
```csharp
mapper.Map<TPoco>(entity);
```
**Note**: mapper is an instance of CoreMapper from above.
where TPoco is POCO model defined like:
```csharp
public class ModelPoco : IModel {
    // props
}
```
and entity is database entity model.

The mapping works fine. The result of _mapper.Map<TPoco>(entity)_ is correct.

I then proceed and add a profile for a specific map **that is not at all related** to the _ModelPoco_ being mapped before.

The profile being added:
```csharp
public class  RepositoryLayerProfile : AutoMapper.Profile {
    public RepositoryLayerProfile() {
        CreateMap<SomeOtherEntity, ISomeOtherModelInterface>();
    }
}
```

### Expected behavior

Mapping of ModelEntity to ModelPoco should happen normally.

### Actual behavior

The mapping breaks with the message:
Unable to cast object of type 'Proxy<IModel>' to type 'ModelPoco'. on line _mapper.Map<TPoco>(entity);_

I am not sure why does it create Proxy class for IModel interface and then tries to cast to concrete implementation?
I explicitly set that I want to map _entity_ to a concrete implementation.

If I remove CreateMap from the profile it works fine, but the first time I define CreateMap in the said profile, it breaks.
It seems to me like it forgets about the configuration for some reason even tho it has nothing to do with it.

### Steps to reproduce
I am attempting to create a repro, will update this if I'm successful.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by thomaslevesque** [comment]
I just hit this too. This really looks like a bug. I'll post a simpler repro.

**Comment by thomaslevesque** [comment]
Here it is:
https://gist.github.com/thomaslevesque/1c18407f77b49b22b9f1fbd3e6b3f9dd#file-automapperinlinevsprofile-cs

Basically the same configuration works when it's defined inline, but fails when it's defined in a profile.

**Comment by lbargaoanu** [comment]
No, it's not the same configuration. See [this](https://github.com/AutoMapper/AutoMapper/issues/2598#issuecomment-380440789).

**Comment by thomaslevesque** [comment]
Ah, I see. That makes sense. Thanks!
