### ISSUE TITLE
Ignore Members in Dynamic Source and Destination

### ISSUE THREAD

**Issue by ramos41** [AutoMapper/AutoMapper#2655]
Hello everyone,
When i did this

```csharp
TypeMap typeMap = (TypeMap)mappingExpression.GetType().GetField("_typeMap", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(mappingExpression);
```

AutoMapper 4.0.4 was getting the typeMap successfully. But in the automapper 6.2.2 this does not work.

```csharp
GetField("_typeMap", BindingFlags.NonPublic | BindingFlags.Instance) 
```
function returns null.

**Comment by lbargaoanu** [comment]
What are you trying to do?

**Comment by ramos41** [comment]
What I want to do is return an object of type TypeMap. So I could ignore the members I gave parameter strings. It was in the way of finding the TypeMap. That's how I solved my problem.

`TypeMap typeMap = mapperConfiguration.CheckIfMapExists (sourceType, destinationType);`

**Comment by lbargaoanu** [comment]
ForMember, Ignore. There is a ForMember overload that works with strings.
