### ISSUE TITLE
ReflectionTypeLoadException error at start time with dotnet core version after 2.1.0-preview1-final

### ISSUE THREAD

**Issue by vRITHNER** [AutoMapper/AutoMapper#2656]
Hi, after having modified my package references in my aspnet.core mvc web solution with latest dotnet 2.1 preview, I got an error when I add **AutoMapper** to the services in startup.cs

` <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview2-30475" />`

With version 2.1.0-preview1-final, everything was working fine.

### Source/destination types

`services.AddAutoMapper();`

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Version: 6.2.2
`    <PackageReference Include="AutoMapper" Version="6.2.2" /> `

### Actual behavior

```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'System.Buffers.OwnedMemory`1' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
```

Thanks
-Vince

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build or the latest from NuGet.

**Comment by irowbin** [comment]
@vRITHNER  I got the same error;

**Comment by vRITHNER** [comment]
I tried the MyGet build or the latest from NuGet but same result

**Comment by lbargaoanu** [comment]
Most likely this is an issue with the .Net Core preview. Will reopen if we determine that's not the case.

**Comment by jbogard** [comment]
.NET Core 2.1 just RTM'd yesterday.
