### ISSUE TITLE
Error converting byte[] to string

### ISSUE THREAD

**Issue by pwelter34** [AutoMapper/AutoMapper#2657]
### Source/destination types

```csharp
public class Test
{
    public Byte[] RowVersion { get; set; }
}

public class TestReadModel
{
    public string RowVersion { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<byte[], string>().ConvertUsing(Convert.ToBase64String);
CreateMap<Test, TestReadModel>();
```

### Version: x.y.z
6.2.2

### Expected behavior

the byte[] to be converted to a base64 string.

### Actual behavior

System.InvalidOperationException: Missing map from System.Byte to System.Char. Create using Mapper.CreateMap<Byte, Char>

### Steps to reproduce

```csharp
var entity = new Test();
var model = _mapper.Map<TestReadModel>(entity);
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
