### ISSUE TITLE
AutoMapper cannot handle the Jsonobject data type properly

### ISSUE THREAD

**Issue by huxiany** [AutoMapper/AutoMapper#2660]
If the source has a JsonObject object, the value in the JsonObject that AutoMapper obtains is the default value of the property's data type, not the actual value.

 https://github.com/huxiany/AutoMapperIssue
![automapperissuecode](https://user-images.githubusercontent.com/28701403/41015782-642912f2-697e-11e8-92c2-8cdfc9e00de8.png)

**Comment by lbargaoanu** [comment]
Actually that json thing cannot handle nulls. Try ```var isNull = student.UserInfo == null;```. 
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And then break on exceptions in the debugger.
You can work around it with ResolveUsing instead of MapFrom.
