### ISSUE TITLE
v7 - UseAsDataSource... where did it go?

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#2663]
Simple as it is. Documentation has no update that it is removed. Can not find it.

It is still referenced like... here:

https://github.com/AutoMapper/AutoMapper/blob/master/docs/Expression-Translation-(UseAsDataSource).md

but that is about it.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping
