### ISSUE TITLE
Does not map JValues if they are not strings

### ISSUE THREAD

**Issue by tocsi-hun** [AutoMapper/AutoMapper#2668]
I am using AutoMapper in a WebApi binder. Have to map from posted json to an object. I know there is a way with newtonsoft's ToObject, but I can't use that. The posted data is a random partial of the full object, so the fact that a property is missing from the json means I should use the original value from database.
Therefore I tried to use AutoMapper to map from a JObject to the original object from database (overwrite the properties of an existing object if the value exists in the json).  First it looked OK, Until I used only strings. But then I noticed it does not work with bools. Then I tried with integers - same.

### Source/destination types
From JObject, or a Dictionary<string, object> where the values ar JTokens or from a multi level Dictionary<string,object> where the value is either the expected .net type (string, int or bool) or another Dictionary<string,object>

Destination type:
```csharp
    public class Config
    {
        public Config()
        {
            Mailbox = new MailboxInfo();
        }
        public MailboxInfo Mailbox { get; set; }
        public string Name { get; set; }
        public bool RootBool { get; set; }
    }

    public class MailboxInfo
    {
        public MailboxInfo()
        {
            OutboxConfiguration = new OutboxConfiguration();
        }

        public bool SendContinuously { get; set; }
        public bool TestBool { get; set; }
        public int TestInt { get; set; }
        public OutboxConfiguration OutboxConfiguration { get; set; }
        public string InBox { get; set; }
    }

    public class OutboxConfiguration
    {
        public bool TestBool { get; set; }
        public string FileNamePatterns { get; set; }
        public int? WaitTimeout { get; set; } 
    }
```

### Mapping configuration
No extra mapping configuration is used

### Expected behavior

Should always map all the properties in the json.

### Actual behavior

It maps everything only if the source is a Dictionary which might contain other dictionaries but it does not work correctly if there are JTokens there

### Steps to reproduce

```csharp
using AutoMapper;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoMapperBool
{
    class Program
    {
        static void Main(string[] args)
        {
            var json = @"{
""RootBool"": true,
""Mailbox"": {
""SendContinuously"": true,
""TestBool"": true,
""TestInt"": 12,
""InBox"": ""zaza"",
""OutboxConfiguration"": {
""TestBool"": true,
""FileNamePatterns"": ""*.zaza""
}
}
}";


            var hostObject = JObject.Parse(json);


            var hostJsonDict = JsonConvert.DeserializeObject<Dictionary<string, object>>(json);


            var hostDict = new Dictionary<string, object> {
                        { "RootBool", true },
                    { "Mailbox", new Dictionary<string, object> {
                            { "SendContinuously", true },
                            { "InBox", "zaza"},
                            { "TestInt", 12},
                            { "TestBool", true },
                            { "OutboxConfiguration", new Dictionary<string,object> {
                                { "TestBool",true },
                                { "FileNamePatterns", "*.zaza"} } } } } };


            AutoMapper.Mapper.Initialize(cfg => { });

            var testJObject = new Config();
            TestConfig((Config)AutoMapper.Mapper.Map(hostObject, testJObject, typeof(JObject), typeof(Config)),"JObject test");

            var testJsonDict = new Config();
            TestConfig((Config)AutoMapper.Mapper.Map(hostJsonDict, testJsonDict, typeof(Dictionary<string, object>), typeof(Config)), "Dictionary from JObject test");

            var testRealDict = new Config();
            TestConfig((Config)AutoMapper.Mapper.Map(hostDict, testRealDict, typeof(Dictionary<string, object>), typeof(Config)), "Real Dictionary<string,object> test");


        }


        private static void TestConfig(Config testConfig, string testName)
        {
            Console.WriteLine(testName);

            Console.WriteLine($"boolean at root {testConfig.RootBool == true}");
            Console.WriteLine($"boolean at 1st {testConfig.Mailbox.SendContinuously == true}");
            Console.WriteLine($"boolean at 2ndt {testConfig.Mailbox.OutboxConfiguration.TestBool == true}");

            Console.WriteLine($"integer at 1st {testConfig.Mailbox.TestInt != 0}");
            Console.WriteLine($"string at 1st {!string.IsNullOrWhiteSpace(testConfig.Mailbox.InBox)}");

            Console.WriteLine();
        }

    }
}

```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by tocsi-hun** [comment]
Well, you might be right. But since it is a clear misbehavior from AutoMapper I would rather consider it as an issue. 
It should either throw, saying that "I do not map JObjects" or it should map correctly. Currently it does a half work. In silence, like everything was ok, And if you check only string values you can still think it was ok. But it just missed a lot of data. And since a string is also in a JValue it looks like it takes care of the JValue, but it doesn't.

**Comment by lbargaoanu** [comment]
Try setting CreateMissingTypeMaps to false.

**Comment by jbogard** [comment]
PR is welcome.

**Comment by tocsi-hun** [comment]
Thanks, but no difference. Still only strings are mapped. Regardless if it is true or false.
AutoMapper.Mapper.Initialize(cfg => cfg.CreateMissingTypeMaps = false);

**Comment by jbogard** [comment]
We won’t take a dependency on JSON.NET. If there’s another way, a PR is
welcome.
