### ISSUE TITLE
CreateMap(MemberList.None) on ReverseMap

### ISSUE THREAD

**Issue by guramiqiashvili** [AutoMapper/AutoMapper#2674]
Hello,
I have mappings, with ReverseMap(). I need to ignore all unmapped members using MemberList.None.
It works on first use - CreateMap(MemberList.None), but is not working on ReverseMap - ReverseMap(MemberList.None) (there is no constructor like this).
So I have to write new mapping with reverse types:

``` csharp
CreateMap<TypeA, TypeB>(MemberList.None);
CreateMap<TypeB, TypeA>(MemberList.None);
```

After this, ignoring, on not mapped members, works on both mappings.

There is .ValidateMemberList(MemberList.None) function, I wrote it after ReverseMap, but ignoring is not working on reverse mapping. It would be better, if there will be reversing with ignoring:
``` csharp
.ReverseMap(MemberList.None)
```

Thanks

**Comment by lbargaoanu** [comment]
I think the default [here](https://github.com/AutoMapper/AutoMapper/blob/835261c00c072f3e08232f0cd86d40750e109690/src/AutoMapper/Configuration/MappingExpression.cs#L98) should be ```MemberList.None```. PR welcome.

**Comment by guramiqiashvili** [comment]
Thanks for reply.

Are you going to add .ReverseMap(MemberList.None) in the future?

**Comment by lbargaoanu** [comment]
No, but somebody else might.

**Comment by jbogard** [comment]
I think this is a bug, it's inconsistent with the other version: https://github.com/AutoMapper/AutoMapper/blob/835261c00c072f3e08232f0cd86d40750e109690/src/AutoMapper/Configuration/MappingExpression.cs#L183

**Comment by lbargaoanu** [comment]
Yes, but it's the non generic version, so maybe it has nothing to do with the original point :)

**Comment by lbargaoanu** [comment]
See also https://github.com/AutoMapper/AutoMapper/issues/2106.

**Comment by jbogard** [comment]
@guramiqiashvili also `MemberList.None` means that validation is a no-op. You're now completely relying on runtime mapping.

**Comment by lbargaoanu** [comment]
[Passing test](https://gist.github.com/lbargaoanu/07f21a442a2889e7b9d3f82270136a9a#file-reversemapmemberlistnone-cs) for the original issue.

**Comment by petersmax** [comment]
Prior to upgrading to the latest version 7.0.1, I was using 6.1.1 and after I upgrade I got an exception `Unmapped members were found. Review the types and members below. Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters ====================================================================================================== AutoMapper created this type map for you, but your types cannot be mapped using the current configuration. SubscriberViewModel -> LoginViewModel (Destination member list) LowryResearchCorporation.Models.SubscriberViewModel -> LowryResearchCorporation.Models.LoginViewModel (Destination member list) Unmapped properties: RememberMe`

I had never had that issue before upgrading to 7.0.1. I went ahead and read [Configuration-validation.md](https://github.com/AutoMapper/AutoMapper/blob/master/docs/Configuration-validation.md) to try and determine if there was some changes (in global settings) but I am not sure I understand, if the enforcement seems sudden between 6.1.1 and 7.0.1. I reverted back to 6.1.1 to try and reproduce the problem and it does seem affected. I have an automapper and a simple customer resolver. These 2 type specifically are inline mapped [CreateMissingTypeMaps](http://docs.automapper.org/en/latest/Inline-Mapping.html?highlight=CreateMissingTypeMaps)

```
public static void RegisterMappings()
        {
            Mapper.Initialize(config =>
            {
                config.ForAllPropertyMaps(pm => pm.SourceType.UnderlyingSystemType == pm.DestinationPropertyType,
                    (pm, c) => c.ResolveUsing(new CustomResolver(), pm.SourceMember.Name));
                // Create missing types/maps by default aka Inline Mapping: http://docs.automapper.org/en/latest/Inline-Mapping.html?highlight=CreateMissingTypeMaps
                config.CreateMissingTypeMaps = true;

                // special maps here....
			}
		}
```

So if I wrote too much and too long didn't read blah blah.... Did Configuration validation get enforced sometime between 6.1.1 and 7.0.1?

**Comment by lbargaoanu** [comment]
Yes :)

**Comment by petersmax** [comment]
Ok, so now my follow-up question(s): will `config.ValidateInlineMaps = false;` restore me original position? Off the top of your head, are there any side effects, that I may encounter as a result of doing this?
Also, I have added a pull request to update the documentation lol I am assuming it was yes to everything.

**Comment by lbargaoanu** [comment]
Yes, you can disable validation, and that means you mappings will fail silently, because of a typo for example. It seems to me that in 6.1.1 the default for CreateMissingTypeMaps is false. The change was done [here](https://github.com/AutoMapper/AutoMapper/pull/2379/files#diff-ecd009a857b81494ec133130081f8c99R40) for 6.2.0.

**Comment by petersmax** [comment]
ahh the language was not clear....  I understood that that feature was added in 6.2.0...
