### ISSUE TITLE
Where can I find the current version of the pdb file?

### ISSUE THREAD

**Issue by ramos41** [AutoMapper/AutoMapper#2676]
I can not find the current version of the pdb file. Can you show me where I can download it?

**Comment by ramos41** [comment]
@lbargaoanu

**Comment by jbogard** [comment]
I think we should implement https://github.com/jbogard/MediatR/pull/278

It seems that the current method of embedding PDBs is a bit broken.

**Comment by ramos41** [comment]
I could not find the last version of the pfb files.
