### ISSUE TITLE
System.Reflection.Emit is a deprecated package

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2680]
We should remove it and replace with the correct packages:

https://www.nuget.org/packages/System.Reflection.Emit/

**Comment by Tornhoof** [comment]
Afaik there is no direct replacement package, the package is either included in the full framework or in netcoreapp, there is no netstandard target anymore. This might impact the current Automapper targets.
See https://github.com/dotnet/corefx/issues/29365 for discussion.

**Comment by jbogard** [comment]
Welp, that's what it looks like based on the linked repos there
