### ISSUE TITLE
How do I dynamically map nested classes in Automapper?

### ISSUE THREAD

**Issue by ramos41** [AutoMapper/AutoMapper#2683]
Hi,
I have an issue when mapping nested classes. I want to write a method which maps classes with nested classes dynamically. For example,

 ```
public void UpdateObject_CreateMap<S, T>()
    {
      Mapper.Initialize(cfg =>
      {
       cfg.CreateMap<S, T>();
      });
    }
```

S and T dynamic classes. So I do not know what they are and what subclasses they may have. I could do this in the previous version (4x). I upgraded to version 7x and now I can not do it because the basic settings have changed. When I try to do it the old way, I get an error because Mapper is not initialized.

Regards,

Ramos.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by ramos41** [comment]
I asked but only 9 people in 2 hours. Here is the link

> https://stackoverflow.com/questions/50836450/how-do-i-dynamically-map-nested-classes-in-automapper

**Comment by ramos41** [comment]
I asked, but I did not get the right answer. @lbargaoanu
