### ISSUE TITLE
Drop netstandard1.3 support

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2684]
It is annoying

**Comment by akasexdev** [comment]
Maybe, but it's used by a lot of people

**Comment by jbogard** [comment]
I’d keep .NET 4.5 support but I’m not sure what I’d lose here:

https://github.com/dotnet/standard/blob/master/docs/versions.md

.NET Core 1.x is the biggest one I guess?

**Comment by NetTecture** [comment]
I doubt many people will even mid term use anything prioer to 2.0 Remember, you most of the  time need data access and Entity Frameowrk Core before 2.1 is EXTREMELY limited. .NET Core 1.x... how many people are really using this?

**Comment by lbargaoanu** [comment]
MS plans to support .NET Core 1.0 for [another year](https://www.microsoft.com/net/support/policy).

**Comment by NetTecture** [comment]
Yeah, but i standd to my word - noone will use it for real new development. It is extremely limited thanks to mostly the EntityFramework Core functionality issues. Support here means bugfixes, and that is IMHO what most people will also publish for THEIR code only. Somehow this smells like a "ms is the last one to jump ship" situation.

**Comment by jbogard** [comment]
Fixed with #2804
