### ISSUE TITLE
'Mapper not initialized. Call Initialize with appropriate configuration.' exception when calling .Map()

### ISSUE THREAD

**Issue by MrClyfar** [AutoMapper/AutoMapper#2685]
I'm using a custom mapping provider, based on the `Simple Injector` example given here

[Automapper Documentation - Dependency Injection](http://docs.automapper.org/en/stable/Dependency-injection.html)

In our case we use Microsoft Unity for our IoC.

### Mapping configuration

```csharp
public class MyMappingProvider : IMappingProvider
{
    private readonly IUnityContainer _container;
    private readonly ILogger _logger;

    public CarfusedMappingProvider(IUnityContainer container, ILogger logger)
    {
        _container = container;
        _logger = logger;
    }

    public IMapper GetMapper()
    {
        try
        {
            //var mce = new MapperConfigurationExpression();

            //mce.ConstructServicesUsing(t => _container.Resolve(t));

            //cfg\.AddProfile<Type1Profile>();
            //cfg\.AddProfile<Type2Profile>();
         
            //var mc = new MapperConfiguration(mce);

            ////mc.AssertConfigurationIsValid();

            //return mc.CreateMapper(t => _container.Resolve(t));

            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<Type1Profile>();
                cfg.AddProfile<Type2Profile>();         
            });

            config.AssertConfigurationIsValid();
            return config.CreateMapper(t => _container.Resolve(t));
        }
        catch (Exception ex)
        {
            _logger.Log($"Unable to complete AutoMapper profile configuration.\r\n{ex.ToString()}");
            return null;
        }
    }
} 
```

### Expected behavior

Calling `_mappingProvider.GetMapper().Map<MyType>(sourceObject)` returns an instance of `MyType` with mapped properties from `sourceObject` copied across.

### Actual behavior

When calling `_mappingProvider.GetMapper().Map<MyType>(sourceObject)` an exception is thrown

> Message: Unhandled exception caught:
> System.InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
>    at AutoMapper.Mapper.get_Instance()
>    at AutoMapper.Mapper.Map[TDestination](Object source)
>    at lambda_method(Closure , ListingItem , Index , ResolutionContext )
> Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.

It's not clear to me what I've missed in the setup code found in `MyMappingProvider.GetMapper()` that results in this exception.

Notice the commented out code in GetMapper(), which uses a `MapperConfigurationExpression` instance. Using that section of code did not help, as I received the same exception being thrown on the same call the `.Map()`.

**Comment by jbogard** [comment]
Why are you configuring AutoMapper every single time you use it? And your stack trace looks a little odd, you're calling the static `Mapper.Map` method somewhere there.

**Comment by MrClyfar** [comment]
Damn it, I forgot about that. Yeah I had a TODO note to move that config code, so that it's only called once. Oops, I didn't get round to doing that before I posted this issue.

I'll do that first and then see what the result is.

**Comment by MrClyfar** [comment]
Here is the new code for `MyMappingProvider`

```csharp
public class MyMappingProvider
{
    private readonly IUnityContainer _container;
    private readonly ILogger _logger;

    public MyMappingProvider(IUnityContainer container, ILogger logger)
    {
        _container = container;
        _logger = logger;
    }

    public IMapper GetMapper()
    {
        try
        {
            var mce = new MapperConfigurationExpression();
            mce.ConstructServicesUsing(type => _container.Resolve(type));

            mce.AddProfiles(typeof(MyTypeProfile).Assembly);

            var mc = new MapperConfiguration(mce);
            mc.AssertConfigurationIsValid();

            return new Mapper(mc);
        }
        catch (Exception ex)
        {
            _logger.Log($"Unable to complete AutoMapper profile configuration.\r\n{ex.ToString()}");
            return null;
        }
    }
}
```

The provider is configured, via Unity, like so:

`container.RegisterSingleton<IMapper>(new InjectionFactory(uc => GetMapper(container)));`

```csharp
private static IMapper GetMapper(IUnityContainer container)
{
    var mp = container.Resolve<MyMappingProvider>();
    return mp.GetMapper();
}

```

So now, the Mapper instance is configured once only.

However, I still encounter the exception when making further calls to `mapper.Map()`, but I do not get this exception the first time `mapper.Map()` is called.

> Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.

Using OzCode's compare feature, I took a snapshot of a mapper instance after the first call to resolve `IMapper`. I compared that instance to the instance where the exception is being thrown, and there is a difference between the two objects.

![2018-06-14_15-14-48](https://user-images.githubusercontent.com/700064/41455989-0d00e798-7077-11e8-9e65-3ca96f0dbcab.png)

It seems the service constructor method is now null for some reason. I'm pretty sure my Unity config is correct, in that the same mapper instance should be returned on each `Resolve<IMapper>()` call. A second opinion on this would be great, if that's OK?

**Comment by MrClyfar** [comment]
A colleague of mine is experiencing weird Unity issues too, on a different matter. We did update Unity recently, so the finger of blame is pointing towards it. Right, will need to change focus, as it looks to be an IoC problem.
