### ISSUE TITLE
Feature Request: Deep Object Comparison

### ISSUE THREAD

**Issue by glowysourworm** [AutoMapper/AutoMapper#2686]
Feature Request: Deep Object Comparison (Something like CompareNETObjects

Would like to have object comparison features along side object mapping / copying. Would be
very useful to maintain both as mapper configuration.

Example:  Type1 maps to Type1 (Deep Comparison for members by configuration)

Example:  Type1 maps to Type2 (Deep Comparison for members by mapper configuration)

**Comment by lbargaoanu** [comment]
A PR is welcome.
