### ISSUE TITLE
Automapper 6.2.2 fails to map nullable double

### ISSUE THREAD

**Issue by AnkHansen** [AutoMapper/AutoMapper#2689]
See https://gist.github.com/AnkHansen/9e1e1b4d3f3f333e82983b0ffc85bc91

### Source/destination types

```csharp
public class JobSparePartView
{
    public double? SparePartStock { get; set; }
}

public class JobItem
{
    public double? ItemStock { get; set; }
}
```

### Mapping configuration
In production I have a profile that looks for Objects in my assembly with a ViewObject attribute, and based on attribute metadata maps from View to DTO object. (See gist for commented out version of this profile. Gist reproduces the error with a more simple AutomapperProfile on just the two types in Gist.

```csharp
public class ModelsAutoMapperProfile : AutoMapper.Profile
{
    public ModelsAutoMapperProfile()
    {
        var dtoType = typeof(JobItem);
        var reflectMap = CreateMap(typeof(JobSparePartView), dtoType);

        var sourceProp = typeof(JobSparePartView).GetProperty("SparePartStock");
        reflectMap.ForMember("ItemStock", x => x.ResolveUsing((source) => sourceProp.GetGetMethod().Invoke(source, null)));

    }
}
```

### Version: 
Is broken in 6.2.2 - worked fine in 6.1.1 and works again in 7.0.0

### Expected behavior

I've had my site(s) running for almost a year with this Automapper profile - and it used to just work. 
In 6.1.1, the version I used last release (11/5-2018) it worked. 
For this version I have upgraded our API to use .Net Core 2.1, and upgraded Automapper to 6.2.2. 
When I did my final testing a few mappings threw "Nullable object must have a value" exception.
After making the Gist to reproduce, I checked Nuget for a new version, tried with 7.0.0 in the Gist and it worked again.

So this is more a question, than an actual bugreport, about whether or not I am doing something wrong in the Gist - and about which versions this was broken in - and which worked as expected. 

I expect my mapping to work (of course) - since it is pretty simple and between two properties with same type, double?.

### Actual behavior

6.2.2 threw Invalid Operation Exception with "Nullable object must have a value"

> Error mapping types.
> 
> Mapping types:
> JobSparePartView -> JobItem
> ConsoleApp1.Program+JobSparePartView -> ConsoleApp1.Program+JobItem
> 
> Type Map configuration:
> JobSparePartView -> JobItem
> ConsoleApp1.Program+JobSparePartView -> ConsoleApp1.Program+JobItem
> 
> Property:
> ItemStock

### Steps to reproduce
See Gist. 
```csharp
static void Main(string[] args)
{
    var config = new AutoMapper.MapperConfiguration(cfg =>
    {
        cfg.AddProfile(new ModelsAutoMapperProfile());

    });

    var mapper = config.CreateMapper();

    var works = mapper.Map<JobItem>(new JobSparePartView { SparePartStock = null });

    //breaks with 6.2.2;
    var breaks = mapper.Map<JobItem>(new JobSparePartView { SparePartStock = 12.2 });
}
```

Again, my solution seems to work now, I am just interested in knowing whether or not I am doing something wrong since I hit the error in 6.2.2 - and if I should improve my Automapper profile to be more bulletproof. ;-)

Best regards 
/Anders

**Comment by lbargaoanu** [comment]
That's a question about your own code, so you should investigate why it doesn't work on 6.2.2 and then we'll have a better idea whether its assumptions are reasonable and it's likely to work in later versions.

**Comment by lbargaoanu** [comment]
Try

    reflectMap.ForMember("ItemStock", x => x.MapFrom("SparePartStock"));

**Comment by AnkHansen** [comment]
Hi Lucian 

Thanks for your suggestion. 

My AutoMapperProfile seems to work with the x.MapFrom solution you suggest - both in 6.2.2 and 7.0.0. 

And it makes my own code simpler. And lets AutoMapper handle the mapping logic. 

I like. :-) 

Added a comment on the gist on what I've changed (just for reference) 

Thanks for your quick reply.
