### ISSUE TITLE
Limit which constructors can be used

### ISSUE THREAD

**Issue by lxalln** [AutoMapper/AutoMapper#2691]
AutoMapper will quite happily use any/all constructors when determining how to construct an object, even private/internal ones.

I propose a setting (however deeply buried), that allows the setting of a required minimum scope. There are times where I have an empty private/internal constructor and really don't want that to be called.

I don't want to have explicity set the constructor to use in all of my mappings.

Is there any appetite for this, if so, I'll take a look at putting a PR together.

**Comment by lbargaoanu** [comment]
We have [ConstructUsingServiceLocator](https://github.com/AutoMapper/AutoMapper/search?q=ConstructUsingServiceLocator&unscoped_q=ConstructUsingServiceLocator). Does that help?

**Comment by lbargaoanu** [comment]
Another option is ForAllMaps with ConstructUsing.

**Comment by lxalln** [comment]
@lbargaoanu I don't see how. How would that allow me to tell AutoMapper to leave my private constructors alone?

I'll add a little more information. I have added a property to a destination constructor, and I want a unit test to tell me that the source hasn't been updated. But the destination has an empty constructor, so `PassesCtorValidation()` returns true.

```csharp
public class Destination 
{
    public Destination(int a, string b /* newly added */)
    {
    }

    public int A { get; }

    public string B { get; }

    private Destination()
    {
    }
}

public class Source
{
    public int A { get; set; }
}
```

I then have a unit test that is asserting that all of my mappings have valid constructors. However, AutoMapper will fall back to the private `Destination()` constructor.

**Comment by lxalln** [comment]
@lbargaoanu I see no `ConstructUsing` on `TypeMap` which is what is available in `ForAllMaps`

**Comment by lbargaoanu** [comment]
You can add custom validations through an extension point. See [here](https://github.com/AutoMapper/AutoMapper/blob/7a00700de61cd3234b6a6eb4bf0f6bbe402369b1/src/UnitTests/ConfigurationValidation.cs#L30).

**Comment by lxalln** [comment]
@lbargaoanu How would the validator know that AutoMapper found a constructor that it couldn't satisfy and fell back to an empty one?

The validator just get's given the `TypeMap` which has a `ConstructorMap` property, with no further information about how/why the decision was made.

**Comment by lbargaoanu** [comment]
Well, you do have to write _some_ of the code yourself :)

**Comment by lxalln** [comment]
Ha, yes. I just figured the code might be best placed inside AutoMapper. It'd be less code and hopefully benefit others too.

I'm happy to submit a PR, just wanted to judge the mood.

**Comment by lbargaoanu** [comment]
In my opinion anything more complicated than a predicate of ConstructorInfo is best done outside AM. @jbogard might see it differently.

**Comment by lbargaoanu** [comment]
We already have http://docs.automapper.org/en/stable/Configuration.html#global-property-field-filtering.

**Comment by lxalln** [comment]
So, a `ShouldMapCtor` in there would fit in nicely :smile:

**Comment by jbogard** [comment]
@lbargaoanu @lxalln nope a new method `ShouldMapCtor` would fit great.
