### ISSUE TITLE
Mapping creates unwanted empty object instance

### ISSUE THREAD

**Issue by evantrimboli** [AutoMapper/AutoMapper#2693]
### Source/destination types

```csharp
private class User {
    public Guid Id { get; set; }

    public Guid? AvatarId { get; set; }

    public Image Avatar { get; set; }
}

private class Image {
    public Guid Id { get; set; }
}

private class UserModel {
    public Guid Id { get; set; }
    public ImageModel Avatar { get; set; }
}

        
private class ImageModel {
    public Guid Id { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => {
    cfg.CreateMap<UserModel, User>().ReverseMap();
    cfg.CreateMap<ImageModel, Image>().ReverseMap();
});
```

### Version: x.y.z
7.0.1

### Expected behavior

The expected behaviour is that `userModel.Avatar` would be null.

### Actual behavior

`userModel.Avatar` has an empty `ImageModel` instance created and assigned to it.

### Steps to reproduce

```csharp
var user = new User();
var userModel = Mapper.Map<User, UserModel>(user);
Console.WriteLine(userModel.Avatar == null);
```

### Workarounds
- If the `AvatarId` property is removed from the `User` class, then the problematic behaviour no longer occurs. It could be a naming convention kind thing that I'm not aware of.
- If I remove the calls to `ReverseMap` and instead manually map each of the types as below, then the issue is also resolved.

```csharp
cfg.CreateMap<UserModel, User>();
cfg.CreateMap<User, UserModel>();
cfg.CreateMap<ImageModel, Image>();
cfg.CreateMap<Image, ImageModel>();
```

Thanks for your help.

**Comment by lbargaoanu** [comment]
Unless you want to try to fix it yourself, just don't use ReverseMap. See also [this](http://docs.automapper.org/en/stable/Reverse-Mapping-and-Unflattening.html).

**Comment by evantrimboli** [comment]
Fair enough. Maybe it could be made more explicit in the documentation that `ReverseMap` isn't just a shortcut for defining the mapping in both ways.

Thanks for your response.

**Comment by lbargaoanu** [comment]
That kind of PR should be easy to do, you just need to find the right words :) ReverseMap does a lot, you can use Ignore to disable some things.
