### ISSUE TITLE
General Question: Anonymous nested Object to flatted

### ISSUE THREAD

**Issue by Fruchuxs** [AutoMapper/AutoMapper#2695]
Hello, I want to use ProjectTo<TDestination> to map multiple Row-Objects from the Database (using Linq2DB) to one Model. I enabled automatic typemap creation, but I assume that automapper doesn't analyze my anonymous object in depth which contains the rows-Objects.

Example:
```c#
(from foo in fooRows 
join bar in barRows 
on foo.Id equals bar.id
select {
foo,
bar
}).ProjectTo<FooBar>();
```

Automapper generates only an empty select:
`.Select(dto => new FooBar())`

I write an own basic mapper, which also creates automatic typemap for anonymous objects. By myself I show which members are not mapped and look if I find a map for the datatype of the not mapped one to the destination type and continue the mapping (flattening). But I prefer to use automapper. There are ways to achiev this behavior with automapper without switching to a not anonymous object?

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper/issues/1760#issuecomment-256352105.

**Comment by Fruchuxs** [comment]
I think you misunderstand my intentions.
I want to map this two Rows:

```c#
class FooRow {
  public int Id {get;set;}
  public string FooString {get;set;}
  public string OtherFooString {get;set;}
}

class BarRow {
  public int Id {get;set;}
  public string BarString {get;set;}
  public string OtherBarString {get;set;}
}
```


to just one Model:
```c#
class FooBar {
  public string FooString {get;set;}
  public string OtherFooString {get;set;}
  public string BarString {get;set;}
  public string OtherBarString {get;set;}
}
```

Yes, I can create another composity type to wrap them, but in my opinion this ist uncessary because c# gives us anonymous objects for this purpose.

**Comment by lbargaoanu** [comment]
You can try mapping the query results using the default flattening.

**Comment by Fruchuxs** [comment]
You mean to iterate over the results and execute the mapper per item? Otherwise I don't know how the default flattening behavior shall help.

**Comment by lbargaoanu** [comment]
Yes.

**Comment by Fruchuxs** [comment]
Seems a performance overkill.

**Comment by jbogard** [comment]
Yes, but remember the original type is a class with two properties named `foo` and `bar`, neither of which match your destination type. The mapping wouldn't even be flattening, it would be losing the members `foo` and `bar`. That's a big assumption for AutoMapper to make.
