### ISSUE TITLE
ProjectTo<>(struct type) is not supported

### ISSUE THREAD

**Issue by jarizast** [AutoMapper/AutoMapper#2696]
### Source/destination types

```csharp
public class Address
{
	public string Street { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string Zip { get; set; }
}

public struct AddressDTO
{
	public string Street { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string Zip { get; set; }
}
```

### Mapping configuration

```csharp
config.CreateMap<Address, AddressDTO>()
```

### Version: x.y.z
6.2.2, 7.0.1

### Expected behavior

Get the list of DTOs.

### Actual behavior

it threw a System.ArgumentException "Argument types do not match"

### Steps to reproduce

```csharp
var mapperConfig = Mapper.Configuration;
var dtos = addresses.ProjectTo<AddressDTO>(mapperConfig).ToList();
```

**Comment by lbargaoanu** [comment]
Try a manual query instead of using AM. EF6 doesn't support structs either.

**Comment by jbogard** [comment]
If you change `public struct AddressDTO` to `public class AddressDTO` it works great ;)

I'm not sure what using a struct gives you exactly.
