### ISSUE TITLE
BindingFlags'a ne oldu?

### ISSUE THREAD

**Issue by ramos41** [AutoMapper/AutoMapper#2697]
Hi,

`PropertyInfo[] sourceProperties = sourceType.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Default);`

I could only get the property that has at least one of these proteties . What do I have to do now?
Look at the other open topics

 ` config.ShouldMapProperty = p => p.GetMethod.IsPublic;`

I found how to get the public ones using, but I still do not know how to get the inheritance and defaults. Can you help me?

Best regards.

Ramos

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by ramos41** [comment]
As you wish :) https://stackoverflow.com/questions/50985732/what-happend-the-bindingflags
