### ISSUE TITLE
Get a string from an array on mapping

### ISSUE THREAD

**Issue by Tbd19** [AutoMapper/AutoMapper#2699]
I have the following configuration on the Automapper 6

CreateMap<A, B>()
   .ForMember(dest => dest.Property, opt => opt.MapFrom(src => src.Array.FirstOrDefault(a => a.BooleanValue).Property))

I have updated to Automapper 7 and now I get the error
System.InvalidOperationException: Nullable object must have a value.

How can I make this work also in Automapper 7?

**Comment by lbargaoanu** [comment]
Try the latest from NuGet.

**Comment by Tbd19** [comment]
I have the latest version AutoMapper 7.0.1
I also have the AutoMapper.Extensions.Microfot.DependencyInjection 4.0.1

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by Tbd19** [comment]
I think I have found where might be the problem.

So the project also use some other nuget that I want to update
Microsoft.EntityFrameworkCore v2.0.3 to v2.1.1
Microsoft.Extensions.DependencyInjection v2.0.0 to v2.1.1

After I updated the two dependencies I get the above error.

Question: Is this problem related to Automapper or EntityFramework?

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by Tbd19** [comment]
I have checked the execution plan and it is the same before and after the EF update

**Comment by lbargaoanu** [comment]
If it worked before the EF Core update, then it's probably EF Core. Is the stack trace in EF Core?

**Comment by Tbd19** [comment]
Here is the Stack Trace
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.AsyncEnumerable.AsyncEnumerableAdapter`1.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

and the link to the EF issue
https://github.com/aspnet/EntityFrameworkCore/issues/12471

**Comment by jbogard** [comment]
What is the Select expression generated in this case?

EF Core also doesn't tend to like null checks, you may need to set `AllowNullCollections = true`.

**Comment by maganuk** [comment]
I'm having the same issue as mentioned above. The following is throwing a System.InvalidOperationException: Nullable object must have a value

    .ForMember(d => d.Cars, opt => opt.MapFrom(c => c.Vehicles.Where(x => x.CarType == CarType.VAN).FirstOrDefault()))

However if I map it to a collection without the FirstOrDefault it works.

**Comment by lbargaoanu** [comment]
If it's the same issue, why don't you follow the link and help the EF Core team with a repro.

**Comment by maganuk** [comment]
I don't think it is an Ef Core issue, seems more like an automapper issue since the query is working fine if I do a select query.

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And then run the query you find there. That will give you the same error. So this way AM is not involved anymore.

**Comment by maganuk** [comment]
Following is the code which is failing. I am posting the same in the EF Core repo as well:

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Vehicle, VehicleDTO>()
                    .ForMember(d => d.Target, opt => opt.MapFrom(c => c.CarCollections.Where(x => x.CarType == CarType.VAN).FirstOrDefault()));
                cfg.CreateMap<CarCollection, CarCollectionDTO>();
                cfg.CreateMap<Car, CarDTO>();
                cfg.CreateMissingTypeMaps = false;
            });
            Mapper.AssertConfigurationIsValid();
            Mapper.Configuration.CompileMappings();
            var optionsBuilder = new DbContextOptionsBuilder<TestContext>();
            optionsBuilder.UseSqlServer("Server=(LocalDb)\\MSSQLLocalDB;Database=TestingCore;Trusted_Connection=true;MultipleActiveResultSets=true");
            var dbContext = new TestContext(optionsBuilder.Options);
            dbContext.Database.EnsureDeleted();
            dbContext.Database.EnsureCreated();
            dbContext.Vehicles.Add(new Vehicle { CarCollections = new List<CarCollection> { new CarCollection { Car= new Car() { Title = "test" }, CarType = CarType.VAN } } });
            dbContext.SaveChanges();
            var result = dbContext.Vehicles.Where(x => x.ID == 1).ProjectTo<VehicleDTO>().ToList();
        }
    }

    public class TestContext : DbContext
    {
        public TestContext(DbContextOptions<TestContext> options) : base(options)
        {
        }

        public DbSet<Vehicle> Vehicles { get; set; }
    }

    public enum CarType
    {
        VAN
    }

    public class Car
    {
        public int ID { get; set; }
        public string Title { get; set; }
    }

    public class CarCollection
    {
        public int ID { get; set; }
        public Car Car { get; set; }
        public CarType CarType { get; set; }
    }

    public class Vehicle
    {
        public int ID { get; set; }
        public virtual ICollection<CarCollection> CarCollections { get; set; }
    }

    public class VehicleDTO
    {
        public int ID { get; set; }
        public CarCollectionDTO Target { get; set; }
    }

    public class CarDTO
    {
        public string Title { get; set; }
    }

    public class CarCollectionDTO
    {
        public CarDTO Car { get; set; }
    }

**Comment by maganuk** [comment]
Surprisingly the following works:

            var res = dbContext.Vehicles.Where(x => x.ID == 1).Select(x => new VehicleDTO()
            {
                ID = x.ID,
                Target = Mapper.Map<CarCollectionDTO>(x.CarCollections.Where(y => y.CarType == CarType.VAN).FirstOrDefault())
            }).ToList();

**Comment by lbargaoanu** [comment]
This works with EF6.
