### ISSUE TITLE
Post Member Mapping Actions

### ISSUE THREAD

**Issue by easygoingalex** [AutoMapper/AutoMapper#2700]
Hi there,

I guess this isn't so much an 'issue' (it is for me right now) more a question on AutoMapper and granular mapping.

The problem domain is such that I have a source object, a plain POCO and a destination object, also a plain POCO but with the addition of having, for some of the fields, a ...Specified property.

### Source/Destination type example

```csharp

public class Poco
{
  public int Wibble { get; set; }
}

public class SpecifiedPoco
{
  public int Wibble { get; set; }
  public bool WibbleSpecified { get; set; }
}
```

My issue is that I'm not sure how I can leverage AutoMapper to set the specified version to true, if a value is present/has been copied. I don't have a .ForMember mapping on each property as all the names and types typically match, so having to write .ForMember for each is not an elegant solution to this problem.

My alternative is to create some kind of intermediary POCO which makes the assignment to ...Specified within the setter of the base property, but this also is not an elegant solution.

Is there some kind of AutoMapper functionality that can do this already, for example:

```csharp

.PerMemberMapped(object sourceValue, PropertyInfo source, PropertyInfo dest)

```

Thanks in advance.

Kind Regards,
Alex

**Comment by lbargaoanu** [comment]
ForAllMembers should do it. And I think people already wrote the code because I've seen this before, probably on SO.

**Comment by lbargaoanu** [comment]
See also http://docs.automapper.org/en/stable/Before-and-after-map-actions.html.

**Comment by easygoingalex** [comment]
It's not as simple as that, but I think I may have a solution using the ResolveUsing ISourceResolver function. Still working through it at the moment.
