### ISSUE TITLE
Inconsistent Mapper.Map<base>(child) behaviour

### ISSUE THREAD

**Issue by Gerboa** [AutoMapper/AutoMapper#2702]
I'm seeing inconsistent behaviour in code I've inherited where a derived child class object is mapped to 
a base class.

I can't share actual code but I've reproduced the behaviour in LINQPad (query attached).

It seems that using the "instance" version of map:
```csharp
var config = new MapperConfiguration(cfg => cfg.CreateMap<Child,Base>());
var mapper = config.CreateMapper();
```
Mapping a child object to the base class returns a base object:
```csharp
var m = mapper.Map<Base>(c);
// m is Base == true && m is Child == fase
```

But using the "static" version of map:
```csharp
Mapper.Initialize(cfg => cfg.CreateMap<Child,Base>());
```
Has the _same_ behaviour the first time, after which is returns the _actual_ child object:
```csharp
var n = Mapper.Map<Base>(c);
// n is Base == true && n is Child == true
// Object.ReferenceEquals(n, c) == true
```

The query attached shows this behaviour. The first time it's run `n` is a `Base` object, the second time it's run (after commenting out the `Mapper.Initialize` because it's already run in the app domain) `n` is a `Child` object!?

[AutoMapper bug.linq.txt](https://github.com/AutoMapper/AutoMapper/files/2133146/AutoMapper.bug.linq.txt)

**Comment by lbargaoanu** [comment]
If I call Mapper.Map twice, I get the same result. Upgrade maybe?

**Comment by Gerboa** [comment]
I'm using the latest (7.0.1) from NuGet.

It's not just simply calling Mapper.Map twice one after the other in the same function. There seems to be something else going on. My example LINQPad query shows this issue, have you tried using that?

**Comment by Gerboa** [comment]
Wow. Didn't give me long to reply!

**Comment by lbargaoanu** [comment]
That's not relevant as a test. What are we testing here, appdomain unload? Write a relevant test and we'll take it from there.

**Comment by Gerboa** [comment]
So a bug doesn't exist unless I can provide a test in "straight" C# code to prove it exists even though you can see the bug using LINQPad and the query I've provided?

**Comment by lbargaoanu** [comment]
Well, a PR is welcome if you think you understand the problem. But any fix needs a test.

**Comment by jbogard** [comment]
LINQPad is OK to show a problem, but it's difficult to speculatively write a test for behavior like this. A failing test gives us a concrete target to fix.
