### ISSUE TITLE
Maps are autocreated regardless of CreateMissingTypeMaps setting

### ISSUE THREAD

**Issue by tl24** [AutoMapper/AutoMapper#2707]
### Source/destination types

```csharp
public class Class1 {
  public string Foo {get; set; }
}

public class Class2 {
   public string foo {get; set; }
}
```

### Mapping configuration

```csharp
public class MyProfile : Profile {

	public MyProfile() {
                // behavior is the same regardless of what I set this to or if I don't set it at all
		CreateMissingTypeMaps = false; 
		// No maps defined
	}
}
```

### Expected behavior

I expected the map to fail because I didn't define any mappings.  I can't trust unit testing my mapping configurations if I'm not forced to define them.  They will just potentially fail at runtime if not defined correctly.

### Actual behavior
The mapping succeeded.

### Steps to reproduce

```csharp
    IMapper mapper = new Mapper(new MapperConfiguration(cfe =>
    {
        cfe.AddProfile<MyProfile>();
    }));
	var cls1 = new Class1 { Foo = "bar" };
	var cls2 = mapper.Map<Class2>(cls1);
	Console.WriteLine(cls2.foo);
```

**Comment by lbargaoanu** [comment]
Set CreateMissingTypeMaps on the global configuration.

**Comment by tl24** [comment]
So like this?
```
    IMapper mapper = new Mapper(new MapperConfiguration(cfe =>
    {
            cfe.AddProfile<MyProfile>();
	    cfe.CreateMissingTypeMaps = false;
    }));
```

Isn't the default a change from previous versions?  I thought all type maps had to be explicitly created before.

**Comment by lbargaoanu** [comment]
Yes, the default is true now.
