### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json with target netcoreapp2.1

### ISSUE THREAD

**Issue by rcollette** [AutoMapper/AutoMapper#2708]
### Version: 7.0.1
AutoMapper.Extensions.Microsoft.DependencyInjection 4.0.1

### Expected behavior
Should configure at runtime
### Actual behavior
Runtime failure in 
C:\projects\automapper\src\AutoMapper\Configuration\MappingExpression.cs(569,0): at AutoMapper.Configuration.MappingExpression`2.Configure(TypeMap typeMap)

System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

### Steps to reproduce
Upgrade the target from netcoreapp2.0 to netcoreapp2.1
Upgrade the package reference for Microsoft.AspNetCore.All from 2.0.7 to 2.1.0

**Comment by lbargaoanu** [comment]
This is the core package repository. But other than that, neither package refers Newtonsoft.Json, so maybe you should look at your own code.

**Comment by rcollette** [comment]
This appears to be an issue with xunit.   When running `dotnet test` things are great.   When running with `dotnet xunit -parallel collections` it runs into the the issue.

This issue can be closed.  Sorry for the distraction.
