### ISSUE TITLE
Aftermap does not seem to allow me to set a destination property.

### ISSUE THREAD

**Issue by foobarred1** [AutoMapper/AutoMapper#2709]
### Source/destination types

```
Public Class sourceEntity
    Public Property Foo As String
End Class
Public Class DTO
    Public Property Foo As String
    Public Property Bar As String
End Class

```
### Mapping configuration

`CreateMap(Of sourceEntity, DTO)(AutoMapper.MemberList.None).AfterMap(Function(src, dest) dest.Bar = dest.Foo)`

### Version: x.y.z
Version 7.0.1

### Expected behavior

This is a crude example designed to test the aftermap behavior:

        Dim theSource As New sourceEntity With {.Foo = "test"}
        Dim theDTO As DTO = AutoMapper.Mapper.Map(theSource, theSource.GetType, GetType(DTO))

When executing the map, I was expecting theDTO.Bar to be "test"; however, it remains a null after the AfterMap.  theDTO.Foo is "test" as expected.

Am I misunderstanding how AfterMap should be used?

Thanks!

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by foobarred1** [comment]
So, am I to assume that AfterMap is working as intended and what I am observing is not a bug?

I put it here because it looked like a bug to me.  In fact I had modified my code to 

`CreateMap(Of sourceEntity, DTO)(AutoMapper.MemberList.None).AfterMap(Function(src, dest) dest.Bar = "test2")`

and still dest.Bar was still null.

**Comment by lbargaoanu** [comment]
I don't see that. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by foobarred1** [comment]
I created a gist here:

https://gist.github.com/foobarred1/d9d44537bd9285869a75e6f14902bafb

To be quite honest, I've never created a gist before, so I'm not sure if this is what you're looking for.  I appreciate your patience in this.  Thanks.

**Comment by lbargaoanu** [comment]
I don't use VB, but I'm sure some people on SO do.

**Comment by foobarred1** [comment]
Okay.  I figured it out after translating into C#.

AfterMap(sub(src,dest) dest.Bar="test2") instead of AfterMap(function(src,dest) dest.Bar="test2") works.
