### ISSUE TITLE
Mapping exception for UWP project - Cannot create an instance of interface 

### ISSUE THREAD

**Issue by ranandLandmark** [AutoMapper/AutoMapper#2714]
### Source/destination types

```csharp
public class Source
{
}
public interface IDestination
{
}
public class Destination : IDestination
{
}
```

### Mapping configuration

```csharp
 Mapper.Initialize(
cfg =>
{
    cfg.CreateMap<Source, IDestination>();
    cfg.CreateMap<Source, Destination>()
        .IncludeBase<Source, IDestination>();
});
```

### Expected behavior

Should map without any errors. Which it does in a .net console application. But in UWP app this fails with mapping exception. 
Tried with ver 7.0.0 (alpha) and 6.2.2 and it maps fine with no errors. But not in 7.0.1.

### Actual behavior

Exception while mapping 
```csharp
var dest = Mapper.Map<Source, IDestination>(source);
```
System.ArgumentException: 'Cannot create an instance of interface type AutoMapperApp.IDestination.'

### Steps to reproduce

```csharp
            var source = new Source();
            var dest = Mapper.Map<Source, IDestination>(source);
```

1. Create a Blank App (Universal Windows) from VS2017
2. Choose Windows 10 Fall Creators Update as min and target version
3. Add Automapper 7.0.1 from nuget. (Works fine with 7.0.0 and 6.2.2)
4. Add the above code to MainPage.xaml.cs (OnNavigateTo)

The latest Myget build(12/07/2018) also has the same issue.

**Comment by lbargaoanu** [comment]
I think you want ```cfg.CreateMap<Source, IDestination>().As<Destination>()```. Because your mapping works on the full framework only because it returns a proxy to IDestination. That feature is disabled now for UWP.

**Comment by ranandLandmark** [comment]
Yes, that fixed it. Thanks for your quick response.
