### ISSUE TITLE
No way to gracefully handle null conversion to value type, without actually writing to the destination object.

### ISSUE THREAD

**Issue by easygoingalex** [AutoMapper/AutoMapper#2717]
I have a specific problem domain, however, this is a real problem for what I'm trying to do, that, I now only one resolution, remove AutoMapper as the mapping component.

In mapping from one POCO to another WSDL generated POCO, I wanted to use INotifyPropertyChanged to manage where properties that have an adjacent "...Specified" boolean property and set that property to true when the value has been successfully mapped.

However, the source is Nullable<T> and the destination is typically a value type, including a custom one for managing boolean values (no idea why the 3rd party would want to do such a thing, but this is where we are!)

Without something like having a condition that can make use of IsSourceValueNull(), this means that, I can't apply a condition that gracefully handles the null values without writing a value to the destination and firing the PropertyChanged event.

Really needed a mechanism to determine the source value (including Nullable<T>) is null, and therefore .. DO NOTHING.

**If there are any examples that can perform this I would be extremely grateful, but for now, it is back to manual wiring.**

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
[Here's](https://gist.github.com/lbargaoanu/534b00577399dffa6ef463c88de001b9) an idea for those "specified" fields.

**Comment by easygoingalex** [comment]
Thanks @lbargaoanu. I'll take a close look tomorrow to see how it fares with our solution.
