### ISSUE TITLE
ProjectTo returns only 1 row for my child objects

### ISSUE THREAD

**Issue by arnvanhoutte** [AutoMapper/AutoMapper#2718]
#### DB Models
```csharp
    public class TestParent : Entity<int>
    {
        public virtual IList<TestChild> TestChildren { get; set; }
    }

    public class TestParentMap : EntityMap<TestParent, int>
    {
        public TestParentMap()
        {
            Id(x => x.Id).GeneratedBy.Identity();
            HasMany(x => x.TestChildren);
        }
    }

    public class TestChild : Entity<int>
    {
        public virtual TestParent Parent { get; set; }
    }

    public class TestChildMap : EntityMap<TestChild, int>
    {
        public TestChildMap()
        {
            Id(x => x.Id).GeneratedBy.Identity();
            References(x => x.Parent);
        }
    }
```

#### DTO's
```csharp
    public class TestParent
    {
        public int Id { get; set; }
        public List<TestChild> Children { get; set; }
    }

    public class TestChild
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
    }
```

### Mapping configuration

```csharp
            CreateMap<DataAccess.Entities.TestParent, Domain.ViewModels.TestParent>()
                .ForMember(x => x.Id, y => y.MapFrom(z => z.Id))
                .ForMember(x => x.Children, y => y.MapFrom(z => z.TestChildren))
                .ForAllOtherMembers(x => x.Ignore());
            CreateMap<DataAccess.Entities.TestChild, Domain.ViewModels.TestChild>()
                .ForMember(x => x.Id, y => y.MapFrom(z => z.Id))
                .ForMember(x => x.ParentId, y => y.MapFrom(z => z.Parent.Id))
                .ForAllOtherMembers(x => x.Ignore());
```

### Expected behavior
I have already seeded my DB with 1 TestParent and 3 TestChild objects, all those 3 TestChild objects are referencing to that 1 TestParent.  
When running ` await _session.Query<DataAccess.Entities.TestParent>().Where(expression).ProjectTo<Domain.ViewModels.TestParent>(_mapper.ConfigurationProvider).FirstOrDefaultAsync();` it should query my DB, and return a TestParent DTO object with 3 TestChild DTO objects in it.

### Actual behavior

It returns 1 TestParent; but the Children property only reveals 1 TestChild property. Running the same query without ProjectTo however does show me that there are 3 children.

The generated SQL looks like this:

```select testchildr1_.Id as col_0_0_, testchildr1_.Id as col_1_0_, testchildr1_.Parent_id as col_2_0_, testparent0_.Id as col_3_0_, testparent0_.Id as col_4_0_ from [TestParent] testparent0_ left outer join [TestChild] testchildr1_ on testparent0_.Id=testchildr1_.Parent_id where testparent0_.Id=1 ORDER BY CURRENT_TIMESTAMP OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY```

I assume this issue is related to the FETCH FIRST 1 ROWS ONLY part.

**Comment by lbargaoanu** [comment]
That works with EF6, so it's more likely a problem with NHibernate. You can always use Map instead for a single row.

**Comment by arnvanhoutte** [comment]
For those who still have this issue, it is fixed when you use SingleOrDefault in NHibernate
