### ISSUE TITLE
Mapping long -> enum returns default value

### ISSUE THREAD

**Issue by adrianjord** [AutoMapper/AutoMapper#2719]
### Expected behavior
Mapping long to enum should return the proper enum.
Using the map.Map<Source, Destination>(source, destination) overload shouldn't overload the enum to the default enum value.

### Actual behavior

The enum gets mapped to the default value
When using the overload the property gets overwritten to the default enum value

### Steps to reproduce
https://dotnetfiddle.net/EZwVlM

Note: It seems even when mapping an int to an enum the enum gets overwritten when using the overload regardless of the destination's value.

**Comment by lbargaoanu** [comment]
Make the underlying type of the enum long.

**Comment by lbargaoanu** [comment]
If you want to skip values when mapping you have to configure conditions to do so.
