### ISSUE TITLE
ProjectTo() seems to fail with enums?

### ISSUE THREAD

**Issue by RobThree** [AutoMapper/AutoMapper#2723]
### Source/destination types

```c#
public enum MyEnum
{
    Night,
    Day,
    Other
}

class Foo
{
    public string Name { get; set; }
    public MyEnum Value { get; set; }
}

class Bar
{
    public string Name { get; set; }
    public string Value { get; set; }
}
```

### Mapping configuration

```c#
CreateMap<MyEnum, string>().ConvertUsing(s => s.ToString().ToLowerInvariant());
CreateMap<string, MyEnum>().ConvertUsing(s =>
{
    if (Enum.TryParse(s, true, out MyEnum result))
        return result;
    return MyEnum.Day;
});

CreateMap<Foo, Bar>().ReverseMap();
```

### Expected behavior

I expect a bunch of foo's to be mapped to bars and vice versa using the `ProjectTo()` method. Instead, AutoMapper throws an exception both ways.

### Actual behavior

Exceptions thrown.

### Steps to reproduce

A gist to reproduce the issue is provided here: https://gist.github.com/RobThree/170022cd422936da400fa9605b439e67

When I map an object with an enum property to an object with a string property (and vice versa) this works just fine. However, when I do this on an `IQueryable` using the `ProjectTo` method this fails.

The exception thrown (when mapping from object with enum to object with string property) is **`System.ArgumentException: 'Argument types do not match'`** and is thrown on [this line](https://github.com/AutoMapper/AutoMapper/blob/8a4e0bcc3f0cbb2337fd5b99e44432b2f415cfae/src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs#L27) in the `MappedTypeExpressionBinder`.

The exception thrown (when mapping from object with string to object with enum property) is **System.ArgumentException: 'Type 'System.String' does not have a default constructor'** and is thrown on [this line](https://github.com/AutoMapper/AutoMapper/blob/8a4e0bcc3f0cbb2337fd5b99e44432b2f415cfae/src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs#L240) in the `ExpressionBuilder`.

It does work, however, when mapping a single item also demonstrated in the provided program. I'm sure I'm doing something wrong but maybe someone can tell me what? (Or did I actually find a bug)?

**Comment by lbargaoanu** [comment]
ProjectTo only supports what the db provider supports. How would you do this with an EF query?

**Comment by RobThree** [comment]
My understanding was that `ProjectTo` would map each instance of `Foo` to `Bar` (or vice versa)?

In actuality (I stripped down the code to provide a clear testcase) I am using EF and have entities that have the string property that I want to be mapped to an enum (and vice versa when updating the database).

**Comment by RobThree** [comment]
See [my update](https://github.com/AutoMapper/AutoMapper/issues/2723#issuecomment-406315285).

I think I understood `ProjectTo...()` wrong. I understood it did something like:

`myQueryable.Select(e => Mapper.Map<m.Tenant>(e)).ToListAsync();`

But I guess I'm mistaken on that then.

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). Map handles collections by default, but ProjectTo is a whole different beast :)

**Comment by RobThree** [comment]
It was my bad. I thought ProjectTo was intended for what i was trying to do but it's a something different alltogether. Sorry.

**Comment by lbargaoanu** [comment]
No worries :)
