### ISSUE TITLE
Regarding Conditional Mapping

### ISSUE THREAD

**Issue by zhang-yf** [AutoMapper/AutoMapper#2725]
Nested Mapping behavior is not as expected:

class A
{
public C propertyname1
}
class B
{
 public D propertyname2
}
class C
{
 public string innerProperty1
}

class D
{
  public string innerProperty2
}

///Profile:

this.createMap <A,B>()
.ForMember(dest=> dest.propertyname2,  opt=>
    {
         opt.Condition(src=>src.propertyname1?.innerProperty1.Length>10);
         opt.MapFrom(src => src.propertyname1);
    }
);

this.createMap<C,D>()

.ForMember(dest=> dest.innerProperty2, opt=> opt.MapFrom(src => src.innerProperty1.subString(10)));

/// invocation:
A a //// some fully populated A object
B b //// some fully populated B object
Mapper.Map(a,b);

/// code end.

Now I encountered a very interesting case in my code such that the opt.Condition() is not what I think it should behave. 

So, Let's consider the we are dealing with fully populated objects, so ignore null expections.

I want to map  object A.propertyname1 to B.propertyname2 by nested mapping their innerproperties.

However I only want the mapping to execute when the inner property is Length>10

So that in my mapping profile for C to D I can define mapping that rely on the fact that I know the string length is greater than 10, here the example using substring.

So I expected that the second mapping was never executed when the condition isn't met.

However in reality the substring() will throw an Exception says the starting point is larger than string length when passing an C object with shorter inner property.

So I figured out that the C,D mapping is actually executed first before checking if the condition is met. It will then commit the mapping if it was met or abort the mapping if not.

So I wonder, is this the better design choice for its behavior? I intended to implement my lower level mapping so it can depends on some conditions (in this case, string length is greater than 10).

I know I can always work around this issue, but I just like to ask if this is intended opt.condition() behavior or is there other out of box functions that facilitate such requirement.

Thank you.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Custom-value-resolvers.html#resolvers-and-conditions

**Comment by zhang-yf** [comment]
Ah I see,  thank you.
