### ISSUE TITLE
Project shadow property

### ISSUE THREAD

**Issue by Deilan** [AutoMapper/AutoMapper#2729]
Having an issue with projecting a [shadow property](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties) while using with Entity Framework Core 2.1. Shadow property named `CreatedAt` in a database needs to be projected to `Created` property.

### Source/destination types

```csharp
// source
public class Student
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

// destination
public class StudentDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public DateTimeOffset Created { get; set; }
}
```

### Mapping configuration

```csharp
public class StudentMappingProfile : Profile
{
    public StudentMappingProfile()
    {
        CreateMap<Student, Index.StudentDto>()
            .ForMember(dest => dest.Created, opt => opt.MapFrom("CreatedAt"));
    }
}
```

### Expected behavior
The property `CreatedAt` gets projected to `Created`.

### Actual behavior
Exception on registering `StudentMappingProfile`
```
System.ArgumentOutOfRangeException: 'Cannot find member CreatedAt of type EkoPoint.Feeding.Domain.Ingredient.'
```

### Steps to reproduce

```csharp
await _db.Students.ProjectTo<StudentDto>().ToListAsync();
```

**Comment by lbargaoanu** [comment]
You'll have to provide that value yourself.

**Comment by lbargaoanu** [comment]
How would you do that in a linq query without AM? And then we'll see how you can do the same with AM.

**Comment by voroninp** [comment]
@lbargaoanu 

> How would you do that in a [linq query without AM](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ef.property?view=efcore-2.1)?

```CSharp
EF.Property<Datetime>(entity, "CreatedAt")
```

**Comment by lbargaoanu** [comment]
OK, what you can do is try to generate an expression for that call and use that in MapFrom.
