### ISSUE TITLE
Unmapped members were found. Review the types and members below

### ISSUE THREAD

**Issue by francisminu** [AutoMapper/AutoMapper#2731]
Hi,
I have upgraded to 7.0.1.0 and I am trying to make changes as per the new implementation (we had a very old version earlier, so had breaking changes).
I have added a Profile with all the mappings and then when I run the code, for one of the mapper.map calls, I get the below error:
Unmapped members were found. Review the types and members below

My Source Class is: OrderJobMessageHeader

public class OrderJobMessageHeader : IOrderJobMessageHeader
    {
        public string CustomerId { get; set; }
        public string Facility { get; set; }
        public string EventType { get; set; }
        public string JobId { get; set; }
        public DateTime JobDate { get; set; }
        public string RequestId { get; set; }
        public long TaskId { get; set; }

        public override string ToString()
        {
            return $"OrderJobTriggerMessage CustomerId: {CustomerId} Facility: {Facility} EventType: {EventType} JobId: {JobId} JobDate: {JobDate} ";
        }

    }

And the destination class is:

public class OrderJob : IOrderJob
    {
        private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);

        public OrderJob()
        {
            MessageId = "";
            MessageType = "";
            MessageName = "";
            CorrelationId = NewId.Next().ToString();
            TimeStamp = (long)Math.Floor((DateTime.Now.ToUniversalTime() - UnixEpoch).TotalMilliseconds);
        }

        public long SequenceNumber { get; set; }
        public string MessageName { get; set; }
        public string MessageId { get; set; }
        public string MessageType { get; set; }
        public string CorrelationId { get; set; }
        public long TimeStamp { get; set; }
        public string EventType { get; set; }
        public string JobId { get; set; }
        public DateTime JobDate { get; set; }
        public int JobPriority { get; set; }
        public string JobPriorityGroup { get; set; }
        public string RequestId { get; set; }
        public string ToteId { get; set; }
        public bool SingleUnit { get; set; }
        public string NextWorkArea { get; set; }
        public JobTasks JobTasks { get; set; }

        public override string ToString()
        {
            return $"OrderJob Message:- EventType: {EventType} JobId: {JobId} JobDate: {JobDate} JobPriority: {JobPriority} JobPriorityGroup: {JobPriorityGroup} RequestId: {RequestId} SingleUnit: {SingleUnit} ";
            //return $"New Message:- ";
        }
    }

public class MappingProfile: Profile
    {
        public MappingProfile()
        {
            CreateMap<OrderJobMessageHeader,OrderJob>();
        }
    }

Mapping Call:
    var obj = _mapper.Map<OrderJobMessageHeader, OrderJob>(orderJobMessageHeader);

I get the below error:

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
============================================================================================================================================
AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
OrderJobMessageHeader -> OrderJob (Destination member list)
SynapseMiddleware.WMS.WMSMessages.LocusRobotics.Lego.OrderJobMessageHeader -> SynapseMiddleware.WMS.WMSMessages.LocusRobotics.Lego.OrderJob (Destination member list)

Unmapped properties:
SequenceNumber
MessageName
MessageId
MessageType
CorrelationId
TimeStamp
JobPriority
JobPriorityGroup
ToteId
SingleUnit
NextWorkArea
JobTasks

I tried giving MemberList.Source, but that did not solve the problem. I still keep getting the same error. Please let me know if I can get this done somehow.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. You might understand things easier if you set CreateMissingTypeMaps to false.
