### ISSUE TITLE
Expression Mapping causes ArgumentException

### ISSUE THREAD

**Issue by soerensoerenson** [AutoMapper/AutoMapper#2733]
In version 7.0.1 there is an bug in the expression mapping. 

For example the mapping is

Expression<Func<UserDTO, bool>> dtoExpression = dto=> u => u.Email == "test@test.de";
var expression = Mapper.Map<Expression<Func<User, bool>>>(dtoExpression);

Then in version 6.2.2 the mapped expression looked in the debug view

{.Lambda #Lambda1<System.Func`2[User,System.Boolean]>(**User** $u)
{
    .Call ($u.Email).ToLower() == .Constant<UserRepository+<>c__DisplayClass7_0>(UserRepository+<>c__DisplayClass7_0).email
}

Then in version 7.0.1 the mapped expression looked in the debug view

{.Lambda #Lambda1<System.Func`2[User,System.Boolean]>(**UserDTO** $u)
{
    .Call ($u.Email).ToLower() == .Constant<UserRepository+<>c__DisplayClass7_0>(UserRepository+<>c__DisplayClass7_0).email
}

which causes an exception if for example you compile the expression.

System.ArgumentException: 'Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.'

**Comment by lbargaoanu** [comment]
That's another repository now.
