### ISSUE TITLE
Undesired mapping is executed

### ISSUE THREAD

**Issue by guylando** [AutoMapper/AutoMapper#2737]
I have an interface IBook and a class Book implementing the interface and a class BigBook inheriting from Book. I have <IBook, BookVML> mapping and <BigBook, BookVML> mapping.
When I have a variable x of type BigBook. How to I apply the <IBook, BookVML> mapping on it?
Tried to pass typeof(IBook) to .Map(..) and tried other things and nothing worked, it always applied the <BigBook, BookVML> mapping.
Without questioning if this scenario is logical or not, is it possible somehow to apply the <IBook, BookVML> mapping on a variable of type BigBook?
Thanks!

Note: I know this can be solved by using two configurations and putting the different mappings in different configurations, but can this be solved with one single configuration?

**Comment by lbargaoanu** [comment]
There is no easy way to do that. You could write a custom mapper for this, but it's overkill.

**Comment by guylando** [comment]
@lbargaoanu That sounds to me like an undesired behavior\bug if the Map(object, type1, type2) overload is not using the <type1,type2> mapping and is using another mapping instead.

**Comment by lbargaoanu** [comment]
No, that's by design. Runtime types are always preferred, so the most derived maps are used.

**Comment by guylando** [comment]
Wouldn't it make sense to respect the user choice when he passed the specific type parameter? if he wanted another mapping he could pass another type as parameter

**Comment by guylando** [comment]
I agree that by default in the other overloads, using runtime type is logical. But in this specific overload it makes less sense.

**Comment by guylando** [comment]
Also another nice thing would be if there would be another optional parameter which allows to choose the mapping to be used. But that's another thing.

**Comment by lbargaoanu** [comment]
If you want to look into it, a PR is welcome.
