### ISSUE TITLE
AlwaysEncrypted columns are not working with ProjectTo extention

### ISSUE THREAD

**Issue by slavapvf** [AutoMapper/AutoMapper#2739]
Hello,

steps:
1. create a table with AlwaysEncrypted  columns
2. create a EF model and the a class (A1 ) with the same proiperties
3. create an app where table records are mapped to class A1 by ProjectTo extention
4. insert data, run app

Actual result:
Encryption scheme mismatch for columns/variables 'prop1'. The encryption scheme for the columns/variables is (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'key1', column_encryption_key_database_name = 'db1') and the expression near line '8' expects it to be (encryption_type = 'PLAINTEXT') (or weaker). 

Queering Entity framework model is fine, but ProjectTo returns error

thanks

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by slavapvf** [comment]
just noticed that a query 
SELECT 
	[Project1].[ID],
    [Project1].[AlwaysEncrColumn1] AS [AlwaysEncrColumn1]
    FROM ( SELECT 
		[Extent1].[ID],
		[Extent1].[AlwaysEncrColumn1] AS [AlwaysEncrColumn1]
        FROM [dbo].[CustomerProductUrl] AS [Extent1]
    )  AS [Project1]
    
while a query

SELECT 
		[Extent1].[ID],
		[Extent1].[AlwaysEncrColumn1] AS [AlwaysEncrColumn1]
        FROM [dbo].[CustomerProductUrl] AS [Extent1]

is ok. It seems AlwaysEncripted columns are not supported in subqueries. So ProjectTo is using a such subquery

**Comment by lbargaoanu** [comment]
Write the query you need by hand and then you'll be able to get AM to do the same.
