### ISSUE TITLE
IgnoreAllPropertiesWithAnInaccessibleSetter not working with base classes

### ISSUE THREAD

**Issue by JoesGab** [AutoMapper/AutoMapper#2740]
### Source/destination types

```csharp
    public class Source
    {
        public int IgnoreMe { get; set; }
    }

    public class Destination : DestinationBase
    {
    }

    public class DestinationBase
    {
        public int IgnoreMe { get; private set; }
    }
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Source, Destination>()
                    .IgnoreAllPropertiesWithAnInaccessibleSetter();
            });
```

### Expected behavior

The `IgnoreMe` member of the `Destination` object should be ignored when mapping.

### Actual behavior

The `IgnoreMe` member of the `Destination` object is *not* ignored and mapped without issues.

### Steps to reproduce

https://gist.github.com/JoesGab/48f136622234c9ef0ab6f26eb164d449

Note the `DestinationBase`! The test only fails in this case, passes if you put the `IgnoreMe` in the derived type.

**Comment by lbargaoanu** [comment]
A PR is welcome. [Here](https://github.com/AutoMapper/AutoMapper/blob/f456fcf2472d3e517bb408a924ad67311a2ed73f/src/AutoMapper/TypeExtensions.cs#L84) it should probably use GetRuntimeProperties. One complication is that it's a breaking change. It would ignore things that are mapped now.
