### ISSUE TITLE
IncludeBase doesn't work with a generic map

### ISSUE THREAD

**Issue by bordecal** [AutoMapper/AutoMapper#2742]
Prior to version 7, it was possible to map objects with an inheritance hierarchy like the following: `Base -> Base<T> -> Derived`.  However, this is no longer the case in 7.0.1.

Here is a unit test class that demonstrates the problem:

```csharp
namespace AutoMapper.UnitTests.MappingInheritance
{
    public class OpenGenericIncludeBase : AutoMapperSpecBase
    {
        public abstract class Entity
        {
            public string BaseMember { get; set; }
        }

        public abstract class Model
        {
            public string BaseMember { get; set; }
        }

        public abstract class Entity<TId> : Entity
        {
            public TId Id { get; set; }
        }

        public abstract class Model<TId> : Model
        {
            public TId Id { get; set; }
        }

        public class SubEntity : Entity<int>
        {
            public string SubMember { get; set; }
        }

        public class SubModel : Model<int>
        {
            public string SubMember { get; set; }
        }

        protected override MapperConfiguration Configuration => new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Entity, Model>();

            cfg.CreateMap(typeof(Entity<>), typeof(Model<>))
                .IncludeBase(typeof(Entity), typeof(Model));


            cfg.CreateMap<SubEntity, SubModel>()
                .IncludeBase<Entity<int>, Model<int>>()
                .IncludeBase<Entity, Model>();
        });

        [Fact]
        public void Should_work()
        {
            var entity = new SubEntity { BaseMember = "foo", Id = 695, SubMember = "bar" };

            var model = this.Mapper.Map<SubModel>(entity);

            model.BaseMember.ShouldBe("foo");
            model.Id.ShouldBe(695);
            model.SubMember.ShouldBe("bar");
        }
    }
}
```

The above works as expected in 6.2.2, but not in 7.0.1 (or the current master branch).

### Source/destination types

See above.

### Mapping configuration

See above.

### Expected behavior

Members of both base classes and the derived class should be mapped.

### Actual behavior

An `InvalidOperationException` with the following message is thrown:

> Missing map from ``AutoMapper.UnitTests.MappingInheritance.OpenGenericIncludeBase+Entity`1[System.Int32]`` to ``AutoMapper.UnitTests.MappingInheritance.OpenGenericIncludeBase+Model`1[System.Int32]``. Create using ``Mapper.CreateMap<Entity`1, Model`1>``.

### Steps to reproduce

See above.

**Comment by lbargaoanu** [comment]
As a workaround, if you can omit the first IncludeBase, that seems to work.

**Comment by bordecal** [comment]
Omitting the first `IncludeBase` did indeed work.  At least that's one upgrade blocker down...
