### ISSUE TITLE
UseDestinationValue mapping does not work for interface-valued readonly collection properties

### ISSUE THREAD

**Issue by bordecal** [AutoMapper/AutoMapper#2743]
When a read-only collection property is declared using an interface type rather than a concrete class (e.g.: `IList<T>` instead of `List<T>`), the destination collection is not filled.

Here is a modification of an existing test class that demonstrates the problem:

```csharp
public class When_mapping_to_a_collection_with_instantiation_managed_by_the_destination : AutoMapperSpecBase
{
    private Destination _destination;
    private Source _source;

    public class SourceItem
    {
        public int Value { get; set; }
    }

    public class DestItem
    {
        public int Value { get; set; }
    }

    public class Source
    {
        public IList<SourceItem> Values { get; set; }
    }

    public class Destination
    {
        private List<DestItem> _values = new List<DestItem>();

        public IList<DestItem> Values
        {
            get { return _values; }
        }
    }

    protected override MapperConfiguration Configuration { get; } = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<Source, Destination>()
            .ForMember(dest => dest.Values, opt => opt.UseDestinationValue());
        cfg.CreateMap<SourceItem, DestItem>();
    });

    protected override void Because_of()
    {
        _source = new Source { Values = new List<SourceItem> { new SourceItem { Value = 5 }, new SourceItem { Value = 10 } } };
        _destination = Mapper.Map<Source, Destination>(_source);
    }

    [Fact]
    public void Should_assign_the_value_directly()
    {
        _destination.Values.Count.ShouldBe(2);
        _destination.Values.ElementAt(0).Value.ShouldBe(5);
        _destination.Values.ElementAt(1).Value.ShouldBe(10);
    }
}
```

The same problem is seen if `ICollection<T>` is used instead of `IList<T>`.

### Source/destination types

See above.

### Mapping configuration

See above.

### Expected behavior

The destination collection should be filled.

### Actual behavior

The destination collection remains empty.  No exceptions are raised to the caller.

### Steps to reproduce

See above.

**Comment by lbargaoanu** [comment]
As a workaround, use ```MapFrom(s=>s.Values)```.

**Comment by lbargaoanu** [comment]
@jbogard Actually the workaround makes a lot of sense. You need the MapFrom for properties without setters. Without debugging, I cannot tell why the List test works. Maybe a backward compatibility thing, because UseDestinationValue used to be true by default?
