### ISSUE TITLE
AutoMapper.Data update?

### ISSUE THREAD

**Issue by bordecal** [AutoMapper/AutoMapper#2744]
AutoMapper.Data is currently incompatible with versions 6.2.2 and higher (including 7.0.1) of AutoMapper (due to breaking changes in AutoMapper).  There has been an open issue regarding this problem in the AutoMapper.Data project since January 24th ( AutoMapper/AutoMapper.Data#30) but without any apparent sign of recognition or other activity from any project contributors.

Is the AutoMapper.Data project still a going concern?  If so, is there a plan for keeping it synced with AutoMapper versions?

**Comment by lbargaoanu** [comment]
Discussions about AM.Data belong in that repository.
