### ISSUE TITLE
Can't get Expression Translation example working

### ISSUE THREAD

**Issue by artemvalmus** [AutoMapper/AutoMapper#2747]
### Source/destination types

```csharp
public class OrderLine
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public Item Item { get; set; }
    public decimal Quantity { get; set; }
}

public class Item
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class OrderLineDTO
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public string Item { get; set; }
    public decimal Quantity { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<OrderLine, OrderLineDTO>()
      .ForMember(dto => dto.Item, conf => conf.MapFrom(ol => ol.Item.Name));
    cfg.CreateMap<OrderLineDTO, OrderLine>()
      .ForMember(ol => ol.Item, conf => conf.MapFrom(dto => dto));
    cfg.CreateMap<OrderLineDTO, Item>()
      .ForMember(i => i.Name, conf => conf.MapFrom(dto => dto.Item));
});
```

### Version
```
.NET Core 2.1
<PackageReference Include="AutoMapper" Version="7.0.1" />
<PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="1.0.2" />
```
### Expected behavior

Expression over OrderLineDTO should be mapped to an expression over OrderLine.

### Actual behavior

But it's not. In the result expression debug view the property selector is wrong because it takes **Item** instead of **Item.Name** - http://prntscr.com/kfe7a3. Probably I am missing something? I copied the code from the documentation. The project is just a simple .NET Core console application.

**Comment by lbargaoanu** [comment]
That's a different repository now.

**Comment by artemvalmus** [comment]
What do you mean? The doc is from this repository - https://github.com/AutoMapper/AutoMapper/blob/master/docs/Expression-Translation-(UseAsDataSource).md.

**Comment by TylerCarlson1** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping is where this functionality goes

**Comment by artemvalmus** [comment]
Thanks. Probably it would make sense to put the link on that page?

**Comment by lbargaoanu** [comment]
There is a link to the package. If you feel smth else is needed, it's easy to add it yourself.
