### ISSUE TITLE
AutoMapper.Extensions.Microsoft.DependencyInjection error after upgrading from 4.0.1 to 5.0.1

### ISSUE THREAD

**Issue by SimplerSoftware** [AutoMapper/AutoMapper#2749]
After updating the AutoMapper.Extensions.Microsoft.DependencyInjection from 4.0.1 to 5.0.1 I receive the following error during startup:

System.InvalidOperationException
  HResult=0x80131509
  Message=Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
  Source=AutoMapper
  StackTrace:
   at AutoMapper.Mapper.get_Configuration()
   at AutoMapper.Mapper.AssertConfigurationIsValid()
   at R365.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider serviceProvider) in C:\GIT\R365New\Application\R365.Web\Startup.cs:line 105

If I change back to 4.0.1 the error goes away.

Is there something else that needs to be done when using the new version?  Or is this a bug?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#mappermap-usage
