### ISSUE TITLE
Substitute doesn't work as suggested

### ISSUE THREAD

**Issue by danielcweber** [AutoMapper/AutoMapper#2753]
For a repro (a failing unit test), see #2752.

From the docs on the `Substitute` method, when mapping a `Parent` to a sequence of `ChildDto`s, I would expect the original source (a `Parent`) to be substituted by it's children (`IEnumerable<Child>`) which would then be mapped to an `IEnumerable<ChildDto>` (since there is a mapping for `Child` to `ChildDto`). However, the test fails.

It seems that `TSubstitution` is expected to inherit from `TSource` which the type constraints on `Substitute` don't enforce.

If this is not a bug, what is the real purpose of `Substitute`? There is little documentation for it.

**Comment by lbargaoanu** [comment]
I for one think Substitute should be removed (@jbogard disagrees). I would look for another way.

**Comment by danielcweber** [comment]
Do you know of another way?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by danielcweber** [comment]
Does that mean that `Substitute` behaves as expected? Then I will close this and look for a solution elsewhere. The docs should probably be fixed though.

**Comment by lbargaoanu** [comment]
As far as I am concerned Substitute is useless and it should be removed.

**Comment by danielcweber** [comment]
Really? You got this method in the library, there's virtually no docs on it, you get an issue on a possible bug, you figure that 'it should be removed', however, don't remove it, and don't comment on how that method behaves currently, or whether it's really a bug, or anything else?

**Comment by lbargaoanu** [comment]
That's @jbogard's decision.

**Comment by jbogard** [comment]
I honestly don't remember what `Substitute` was for originally. Was it something about some ORM edge case? But if it's not working properly, we should either remove it or fix it. I'm not sure what the behavior is supposed to be though.

**Comment by danielcweber** [comment]
Intuitively, and from what Intellisense suggested, if a mapping from `TSource` to `TTarget` is defined with the use of 'Substitue', where a `Func<TSource, TSubstitue>` is passed in, I would expect Automapper to replace the instance of `TSource` by the substituted instance of `TSubstitute`, and go on by mapping `TSubstitute` to `TResult`.

It currently seems to work if `TSubstitute` derives from `TSource`.

**Comment by danielcweber** [comment]
I found it very useful for one scenario I had to solve recently. If the descision would be to keep it, I could have a look into it and try to fix it.

**Comment by jbogard** [comment]
PRs for thing that are broken - are always welcome. I'd default to keeping it, but since I don't use this feature, I have a hard time figuring out what the behavior *should* be.

**Comment by danielcweber** [comment]
Alright, gonna tackle it tonight.
