### ISSUE TITLE
ResolveUsing triggers another map Object -> TType

### ISSUE THREAD

**Issue by DimitryNechaev** [AutoMapper/AutoMapper#2756]
Hi folks

I have mapping of a property with type IEnumerable<MyType>, which value I create in ResolveUsing.
When I add another mapping between <object> and <MyType>, it is hit after that ResolveUsing is executed.
For some reason, it tries to map the created value to itself in that second map. Look example below:

### Source/destination types

Target property type: IEnumerable<MyType>
Source type: MyType[] created in ResolveUsing. Can be also IEnumerable<MyType>, same behaviour.

### Mapping configuration

```csharp
// map 1
CreateMap<>()
.ForMember(dst => dst.MyProp, opt => opt.ResolveUsing((src, dst, member, ctx) => 
  new[] { 
     new MyType() 
}); // I can add .ToEnumerable() there to return exact type of the property, but mapping 2 is being hit anyway.

// map 2
CreateMap<object, MyType>()
.ConvertUsing((src, dst, ctx =>
{
// I'm hitting this line executing map1
// src is MyType value, created in ResolveUsing above
// so it is mapping MyType into MyType
})
```

### Version: x.y.z
7.0.1

### Expected behavior

A value created in ResolveUsing will be just assigned to the target member, not pulled though mapping to itself.

### PS

I map from object, because source is autogenerated from wsdl with some properties defined as object or object[].

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). That's by design. You can use a type converter instead of a resolver. Or a value transformer.
