### ISSUE TITLE
ResolveUsing, ProjectTo and using DI injected IMapper

### ISSUE THREAD

**Issue by jmalczak** [AutoMapper/AutoMapper#2763]
Hi Guys

We have following setup:

Profile class:
```
CreateMap<Location, LocationListViewModel>()
    .ForMember(dest => dest.CurrentWeight, opt => opt.MapFrom(l => GetCurrentWeightInfo(l)));
``` 

Where GetCurrentWeightInfo was using Mapper.Map<> inside to map one of the properties of Location.

That was working fine when we were using static Mapper methods. We have switched to injecting IMapper from DI container and now we need to pass IMapper instance to GetCurrentWeightInfo method. I have found that this is possible by using ResolveUsing method. But we also use ProjectTo<LocationListViewModel>(context) and ResolveUsing is not supported in mappings when when used together with ProjectTo. 

So my question would be how to access mapper instance inside GetCurrentWeightInfo and not use static Mapper.Map, when above mapping will be used in ProjectTo? 

### Version: 7.0.1

**Comment by lbargaoanu** [comment]
ProjectTo runs in the database so it cannot possibly call your method.

**Comment by jbogard** [comment]
How would you do this using pure EF or LINQ? Short answer is a
parameterized query:

http://docs.automapper.org/en/stable/Queryable-Extensions.html#parameterization

**Comment by jmalczak** [comment]
Thanks guys. 

Regarding ProjectTo and database. So if you pass expression like that which requires mapping to run on the server side EF will pull properties required to calculate it on server side and then run in when query is materialized, so this is still kind of OK.

In case of parametrized query. I will give it a try. Is there a specific reason why there is no overload for MapFrom which pass context, like ResolveUsing? 

In case of EF or LINQ I would explicitly require IMapper in my service class constructor, but here when using parametrized queries requirement to pass IMapper is not enforced during compile time so it's really easy to forget about it.

The same case is regarding ProjectTo and passing mapping context. First of all it's not required in API but when you use DI registered mapper it's really required. Second thing is that since ProjectTo accept object as parameter it's easy to for example pass mapping configuration instead of context and compiler won't complain.

Anyway, thanks a lot for the library and for your help!

**Comment by lbargaoanu** [comment]
I don't know about EF Core, but EF6 doesn't support any of that. That's why the context doesn't make sense for MapFrom. ProjectTo worked for years with the static configuration and it still does, that's why the configuration is not required.
