### ISSUE TITLE
Add overloaded method to IPathConfigurationExpression that includes the ResolutionContext similar to the IMemberConfigurationExpression.Condition method

### ISSUE THREAD

**Issue by SimplerSoftware** [AutoMapper/AutoMapper#2769]
I have a .Net Core project where I rely upon DI for access to the IMapper object.  I found myself in a situation where I need access to the IMapper instance during the IPathConfigurationExpression.Condition method.  I am doing something similar in the IMemberConfiguration.Condition method, which has an overload that includes the ResolutionContext so that I can access the IMapper instance but unfortunately it doesn't look like there is a similar overload for the IPathConfigurationExpression.  

Are you able to provide this?  Looking at the source it seems pretty straight forward to implement. Let me know if you would like a PR for this and I'll see what I can do to help out. Thanks!

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by SimplerSoftware** [comment]
When I started to work on the PR I noticed that the 'Condition' method passes a parameter of type 'ConditionParameters' which apparently contains the ResolutionContext so I guess I already have what I need.  I'll go ahead and close this. Thanks!
