### ISSUE TITLE
c# AutoMapper Mapping Condition

### ISSUE THREAD

**Issue by RajendraKhandekar** [AutoMapper/AutoMapper#2772]
**i just want to get Communities count, if its community delete flag its true then count will be minus. i had wrote below code, its return all count. any suggestion fot that** 
- Code - 

Mapper.CreateMap< VPS_Entity.Brand, ZillowBrandViewEntity >()
              .ForMember(e => e.CommunityCount, ex => ex.MapFrom(s => s.Communities.Count))
                .ForSourceMember(e => e.Builder, ex => ex.Ignore());

class file - Brand data model class file have -  ```public virtual ICollection<Community> Communities { get; set; },``` in between Community class file have - ```public bool Deleted { get; set; }```

thanks.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
