### ISSUE TITLE
Proposal: Member-Scoped Type Converters

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2773]
I'm in the middle of upgrading an old application that uses 2.2.1, and the old value formatters pretty heavily.

Those were a bad idea, for a number of reasons, but I do find myself wanting the ability to apply a type converter to an individual member.

We can apply type converters to a TypeMap level, but *not* to an individual member. The reason this is useful is I would want to apply some sort of conversion, but only on specific members. It would look something like:

```c#
cfg.CreateMap<Foo, FooDto>()
    .ForMember(dest => dest.Bar, opt => opt.ConvertUsing<BarValueConverter>())
    .ForMember(dest => dest.Baz, opt => opt.MapFrom(src => src.Buzz).ConvertUsing<BazConverter>());
```

The mapping operation would be similar to other type converters, except it's localized to a single member.

**Comment by lbargaoanu** [comment]
So like a value resolver that doesn't get mapped to the destination type?

**Comment by lbargaoanu** [comment]
But if it's a resolver, so it's mapped to the destination type, then it should be called a resolver, not a converter.

**Comment by jbogard** [comment]
So Member Resolver? I don't want to confuse concepts - this is something that only concerns itself with source/destination types and values, but the source/destination types/values happen to be scoped to source/destination members.

**Comment by jbogard** [comment]
Yeah there isn’t a mapping that happens. It’s purely a converter scoped to
a member. Naming is a different thing.
