### ISSUE TITLE
Automapper.Extensions.Microsoft.DependencyInjection 5.0.1 causing AutoMapperMappingException: Cannot create an instance of type 

### ISSUE THREAD

**Issue by Gilbertvan** [AutoMapper/AutoMapper#2775]
### Description 

We had a functioning mapping configuration until we updated the Automapper.Extensions.Microsoft.DependencyInjection package to version 5.0.1

We got the AutoMapperMappingException: Cannot create an instance of type PhotoConverter exception after the update.

When reverting back to 4.0.1 everything worked again.

### Source/destination types

```csharp
    public class PhotoConverter : ITypeConverter<IOrderedPhoto, PhotoData>
    {
        private readonly ICommandDispatcher _commandDispatcher;

        public PhotoConverter(ICommandDispatcher commandDispatcher)
        {
            _commandDispatcher = commandDispatcher;
        }

        public PhotoData Convert(IOrderedPhoto source, PhotoData destination, ResolutionContext context)
        {
            var request = new RequestDto { PhotoId = source.PhotoId };
            var response = _commandDispatcher.Dispatch<RequestDto, ResponseDto>(request).Result;
            if (response != null)
            {
                return new PhotoData
                {
                       // some magic here.
                };
            }

            return null;
        }
    }
```

### Mapping configuration

```csharp
profile.CreateMap<IOrderedPhoto, PhotoData>().ConvertUsing<PhotoConverter>();
```

### Version: 
AutoMapper v7.0.1
AutoMapper.Extensions.Microsoft.DependencyInjection v5.0.1
Microsoft.Extensions.DependencyInjection v2.1.1
Microsoft.Extensions.DependencyInjection.Abstractions v2.1.1

### Expected behavior

Should use implementation of ITypeConverter<,>

### Actual behavior

AutoMapperMappingException: Cannot create an instance of type PhotoConverter

### Steps to reproduce

update AutoMapper.Extensions.Microsoft.DependencyInjection from version 4.0.1 to 5.0.1

### Steps to resolve

Revert AutoMapper.Extensions.Microsoft.DependencyInjection back to 4.0.1

**Comment by lbargaoanu** [comment]
Using the static Mapper is no longer supported. [The docs](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md).

**Comment by lbargaoanu** [comment]
If you cannot make it work you should open an issue with a repro in the DI repository.

**Comment by Gilbertvan** [comment]
Thanks, wil have a look at it
