### ISSUE TITLE
Automapper use Map and ProjectTo with parameters on same DTO

### ISSUE THREAD

**Issue by Tbd19** [AutoMapper/AutoMapper#2781]
I have a DTO that requires a custom mapping based on a parameter.

For getting one DTO I use Map so the custom mapping that works is like this: 

```c#
.ForMember(dest => dest.Field, opt => opt.ResolveUsing((src, dest, destMember, resContext) => dest.Field = (string)resContext.Items["param"] == "value" ? src.Field1 : src.Field2))
```
and the mapping is done like:
```c#
Mapper.Map<DTO>(entity, opts => opts.Items["param"] = value);
```

For getting a list of DTO I use ProjectTo so the custom mapping that works is like this:
```c#
.ForMember(dest => dest.Field, opt => opt.MapFrom(src => param == "value" ? src.Field1 : src.Field2))
```
and the mapping is done like:
```c#
queryable.ProjectTo<DTO>(Mapper.ConfigurationProvider, new Dictionary<string, object> { { "param", value } }
```c#

Besides creating two DTOs is there a way to make both ProjectTo and Map use the same mapping? (I should mention that the mapping is done through a Profile)

**Comment by lbargaoanu** [comment]
Not really. You could have an extra property in the source just for this purpose. In principle, Map could also support parameters ProjectTo style, but you would have to implement that yourself.

**Comment by Tbd19** [comment]
Do you have an example on how to implement the support parameters of ProjectTo style in the Map also?

**Comment by lbargaoanu** [comment]
Maybe I was not clear. What I meant is that if you need the feature you might want to open a PR and implement it yourself. The model is ProjectTo. It would work only for MapFrom, the same implementation as ProjectTo. You can start [here](https://github.com/AutoMapper/AutoMapper/blob/dbffa1d11d67d044bbfbf35ceb72cf2296821b47/src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs#L106).

**Comment by jbogard** [comment]
That'd probably be the only way. It's not too pretty, but about the only way we can make it work for `ProjectTo`

**Comment by lbargaoanu** [comment]
I think we could still use Context.Items to pass the values.

**Comment by lbargaoanu** [comment]
I guess this could work by having smth at config time that says use projectto style parameters that would replace the constants with Context.Items getters, but it seems messy.
