### ISSUE TITLE
Feature request: Validate mapping of read-only collection-typed properties

### ISSUE THREAD

**Issue by antoinebj** [AutoMapper/AutoMapper#2782]
Hi,

The project I'm working on uses read-only properties of type IList<> for collections both in source and destination types.
By default, AutoMapper ignores those properties because of their lack of a public setter. We therefore use the explicit MapFrom and UseDestinationValue to force the mapping to happen.
It would be nice if we didn't have to do that, but it works, so I can live with it.

However, if one of those collection properties is not mapped, the AssertConfigurationIsValid() method does **not** throw an exception, also because the lack of a public setter. And for that, there does not seem to be any workaround.

After looking at the source code, it appears that at one point there must have been some intent to consider read-only list/collection properties the same way as regular read/write properties.
I'm referring to this line of code in TypeDetails.BuildPublicAccessors:
```csharp
.Where(pi => pi.CanWrite || pi.PropertyType.IsListOrDictionaryType())
```

IsListOrDictionaryType() calls IsListType():
```csharp
public static bool IsListType(Type type)
    => typeof(IList).IsAssignableFrom(type);
```

Now, I don't know if that's intentional, but if it also checked for ICollection<> and not just the non-generic IList (BTW why not ICollection?), it appears that it would fix having to use MapFrom + UseDestinationValue, and also make the configuration validator take these kinds of properties into consideration.

Are there any reasons not to go in that direction?

**Comment by lbargaoanu** [comment]
See #2743. It's just a hack. If you want to "improve" it, a PR is welcome. About validation, I guess it's not anything a few extra checks won't solve. But it might break people. The workaround would  be to use [the extension point](https://github.com/AutoMapper/AutoMapper/blob/dfce8185d2ed468b55e8a96708f0fd3aed2e7d88/src/UnitTests/ConfigurationValidation.cs#L30).
