### ISSUE TITLE
ProjectTo with nested projections containing FirstOrDefault throws InvalidOperationException 

### ISSUE THREAD

**Issue by jcemoller** [AutoMapper/AutoMapper#2784]
With nested entities such as A -> B -> C, the ProjectTo will fail for A if entity B configuration uses FirstOrDefault to select a single entity based on some filter. If I project B instead (using the same config), it works all right.

### AutoMapper Version: 7.0.1

EF Core 2.1.x (also reproducible using 2.2.0 preview)

### Expected behavior

The entities should be mapped successfully.

### Actual behavior

InvalidOperationException is thrown: "No mapping to a relational type can be found for the CLR type 'object'."

### Workarounds

By using .Take(1) and projecting into an ICollection<C> it works. It also works using InMemory database provider.

### Steps to reproduce

See the following gist:
https://gist.github.com/jcemoller/51c2ecc07369f4c4b706df006be67633

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And then try the query without AM. You should get the same result. If the plan looks good, then it's an EF Core issue.

**Comment by jcemoller** [comment]
@lbargaoanu So I tried executing directly what AM generates;

```c#
dtoAd.Offers.Select(dtoOffer => new
                    {
                        __LastAction = dtoOffer.Actions.OrderByDescending(a => a.TimeCreatedUtc).FirstOrDefault(),
                        Id = dtoOffer.Id
                    })
                    .Select(dtoLet => new OfferDetails()
                    {
                        Id = dtoLet.Id,
                        LastAction = dtoLet.__LastAction == null ? null : new OfferActionDetails()
                        {
                            Action = dtoLet.__LastAction.Action,
                            TimeCreatedUtc = dtoLet.__LastAction.TimeCreatedUtc
                        }
                    })
                    .ToList()
                })
```

This throws the same exception. If I remove the null check on LastAction it does work. Might be related to the issue here: https://github.com/aspnet/EntityFrameworkCore/issues/12148. Trying to get some help there, thanks.

**Comment by lbargaoanu** [comment]
As a workaround, try [this](https://github.com/AutoMapper/AutoMapper/blob/7e77cd4461a748c94c2de6e4463df5e9e5fb4747/src/AutoMapper/IMemberConfigurationExpression.cs#L125).

**Comment by jcemoller** [comment]
@lbargaoanu How do I combine that with MapFrom?

**Comment by jcemoller** [comment]
@lbargaoanu still, it is very likely that the entity is null if there are no items - therefore the FirstOrDefault in the first place

**Comment by lbargaoanu** [comment]
We cannot help you with that one, talk to the EF Core team.
