### ISSUE TITLE
Mapper already initialized exception when running multiple integration tests

### ISSUE THREAD

**Issue by ngruson** [AutoMapper/AutoMapper#2788]
Hi,

I'm getting a 'Mapper already initialized' exception when running multiple xUnit integration tests at once. When running the tests independently, the exception doesn't get thrown.
The tests are for an ASP.NET Core 2.0 Web API project.
I'm not initializing AutoMapper myself, this is handled by the dependency injection framework of ASP.NET Core (see Startup.cs). I just pass in a very simple mapping profile.
The test class gets an instance of the web application factory passed in its constructor. The factory uses the Startup class in which AutoMapper is initialized.

Not sure how to go about this. Any ideas/approaches?

### Mapping configuration
In Startup.cs:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddAutoMapper(new Type[] { typeof(MappingProfile) });
    ...
}
```
An example of an integration test:
```csharp
public class ProductBrandControllerIntegrationTests : IClassFixture<CustomWebApplicationFactory<Startup>>
    {
        private readonly HttpClient client;

        public ProductBrandControllerIntegrationTests(CustomWebApplicationFactory<Startup> factory)
        {
            //Arrange
            client = factory.CreateClient();
        }

        [Fact]
        public async void ProductBrandController_Get_ReturnsOk()
        {
            //Act
            var response = await client.GetAsync("/api/ProductBrands");
            response.EnsureSuccessStatusCode();
            var responseString = await response.Content.ReadAsStringAsync();

            //Assert
            var brands = JsonConvert.DeserializeObject<IEnumerable<ProductBrandModel>>(responseString);
            brands.Count().Should().Be(5);
        }
    }
```

Code of the CustomWebApplicationFactory. No AutoMapper related code in here.
```csharp
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
               ...
            }
        }
    }
```

### Version: x.y.z
AutoMapper: 7.0.0
AutoMapper.Extensions.Microsoft.DependencyInjection: 4.0.0

**Comment by ngruson** [comment]
Workaround for now:
In Startup.cs, use AddSingleton instead of AddAutoMapper.

```csharp
services.AddSingleton(MapperBuilder.Build());
```
MapperBuilder.cs:
```csharp
public class MapperBuilder
    {
        public static IMapper Build()
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile(new MappingProfile()));
            return new AutoMapper.Mapper(configuration);
        }
    }
```

**Comment by lbargaoanu** [comment]
Upgrade the DI package. The idea is to move away from the static API. Tests shouldn't share state.

**Comment by KellyR-STCU** [comment]
> Upgrade the DI package. The idea is to move away from the static API. Tests shouldn't share state.

@lbargaoanu 
can you explain that further? Do you mean no longer do AddAutoMapper() in startup.cs ?

**Comment by lbargaoanu** [comment]
The DI package no longer uses the static Mapper, see [this](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md).
