### ISSUE TITLE
Ability to log validation errors without catching exception.

### ISSUE THREAD

**Issue by MNF** [AutoMapper/AutoMapper#2789]
AssertConfigurationIsValid does validation, but throw exception in case if some fields are not mapped.

If I have many classes with many properties to ignore, I don't want to have exception when call AssertConfigurationIsValid(), but prefer to report it in a log and just review are all unmapped properties missed intentionally.  I also do not want to use IgnoreUnmapped extension, as it will hide any future fields, that are added but unmapped. The logic to do validation inside AssertConfigurationIsValid is not exposed by AutoMapper, I have to catch AssertConfigurationIsValid and return error message as string.

```
public string ValidateUnmappedConfiguration(IMapper mapper)
    {
        try
        {
            mapper.ConfigurationProvider.AssertConfigurationIsValid();
        }
        catch (AutoMapperConfigurationException e)
        {
              return e.Message;
        }
        return "";
    }
```
It will be nice if validation inside AssertConfigurationIsValid will be exposed as separate method, and users will be able to log validation result  instead of getting exception.
Related SO question:
https://stackoverflow.com/questions/13360712/can-you-tell-automapper-to-globally-ignore-missing-properties-when-mapping/52232712#52232712

**Comment by lbargaoanu** [comment]
A PR is welcome.
