### ISSUE TITLE
InvalidCastException when mapping IReadOnlyDictionary<int, int> to the same type

### ISSUE THREAD

**Issue by thomaslevesque** [AutoMapper/AutoMapper#2791]
### Source/destination types

```csharp
public class Source
{
    public IReadOnlyDictionary<int, int> Values { get; set; }
}

public class Destination
{
    public IReadOnlyDictionary<int, int> Values { get; set; }
}
```

### Mapping configuration

```csharp
    var mapper = new MapperConfiguration(config =>
    {
        config.CreateMap<Source, Destination>();
    }).CreateMapper();
```

### Expected behavior

Should successfully map `Source.Values` to `Destination.Values`.

### Actual behavior

Throws `AutoMapperMappingException`:

> Error mapping types.
> 
> Mapping types:
> Source -> Destination
> UserQuery+Source -> UserQuery+Destination
> 
> Type Map configuration:
> Source -> Destination
> UserQuery+Source -> UserQuery+Destination
> 
> Property:
> Values

(`UserQuery` is the root class in a LINQPad query)

Inner exception: `InvalidCastException`:

> Unable to cast object of type 'System.Collections.Generic.List`1[System.Collections.Generic.KeyValuePair`2[System.Int32,System.Int32]]' to type 'System.Collections.Generic.IReadOnlyDictionary`2[System.Int32,System.Int32]'.

### Steps to reproduce

```csharp
    var source = new Source
    {
        Values = new Dictionary<int, int> { [1] = 42 }
    };
    
    var destination = mapper.Map<Destination>(source);
```

**Comment by thomaslevesque** [comment]
Even simpler repro:

```csharp
    var mapper = new MapperConfiguration(config =>
    {
    }).CreateMapper();
    
    IReadOnlyDictionary<int, int> source = new Dictionary<int, int> { [1] = 42 };
    var destination = mapper.Map<IReadOnlyDictionary<int, int>>(source);
```

If I change `IReadOnlyDictionary` to `IDictionary` as the destination type, it works.

**Comment by thomaslevesque** [comment]
Already raised before (#1689, #2553), but closed without resolution.

**Comment by lbargaoanu** [comment]
The resolution is that a PR is welcome.

**Comment by thomaslevesque** [comment]
> The resolution is that a PR is welcome.

I'm not sure I'd call that a resolution... This is a bug, you should at least leave it open to keep track of it.
Anyway, I'll give it a try, but as a maintainer, you're probably more able than I to fix it.

**Comment by jbogard** [comment]
It's not a bug, it's a use case we've never seen before :)

The feature request would be "support read-only dictionaries". I also suspect that the other read-only collections may have similar problems.

**Comment by thomaslevesque** [comment]
I started looking into it, but I got lost in pretty hardcore Linq expression generation in [`CollectionMapperExpressionFactory`](https://github.com/AutoMapper/AutoMapper/blob/dbffa1d11d67d044bbfbf35ceb72cf2296821b47/src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs#L22)...

**Comment by lbargaoanu** [comment]
There is already a ReadOnlyCollectionMapper. That's why it works. Maybe you should take that as a model.

**Comment by thomaslevesque** [comment]
> There is already a ReadOnlyCollectionMapper. That's why it works. Maybe you should take that as a model.

Are you sure? It seems to apply only to the concrete `ReadOnlyCollection<T>` class:

https://github.com/AutoMapper/AutoMapper/blob/dbffa1d11d67d044bbfbf35ceb72cf2296821b47/src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs#L22

I see no mention of `IReadOnlyList` or `IReadOnlyCollection`, so I assume they're handled implicitly as `IEnumerable`

**Comment by lbargaoanu** [comment]
Then I guess that would only help for ReadOnlyDictionary, not for the interface.

**Comment by jbogard** [comment]
To put this another way, if this feature were added to support read-only
enumerables, we'd label this as a "Feature" in our release notes. I only
label "bugs" for broken behavior in known or supported features. That also
changes our priority - we fix bugs very quickly. Feature requests are a mix
of those added by us or submitted via PRs.

This is an example of a case that seems like it should work, but it's not
currently supported behavior.

**Comment by thomaslevesque** [comment]
@jbogard I see.

> Feature requests are a mix of those added by us or submitted via PRs.

Well, I'll keep trying, but I'm not sure I'll manage to submit a PR for this; it seems pretty involved and probably requires advanced knowledge of the library's internals. Anyway, if I don't succeed, I hope you'll consider implementing the feature anyway :wink:

**Comment by lbargaoanu** [comment]
I doubt it. If you'll give it some thought it should easy to do.
