### ISSUE TITLE
ProjectTo, EFCore and SelectMany results in InvalidOperationException

### ISSUE THREAD

**Issue by gius** [AutoMapper/AutoMapper#2793]
When using `ProjectTo` on an EF Core query created with `SelectMany` and projecting to an entity with a child collection, an exception is thrown.

```csharp
    var query = context.Masters
        .SelectMany(x => x.Details)
        .ProjectTo<DetailDto>();
```

See the full code [here](https://gist.github.com/gius/507aa74bddf18ccd239b07a35d5b7c2e)

### Source/destination types

```csharp
// source

    public class Master
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public List<Detail> Details { get; set; }
    }

    public class Detail
    {
        public int ID { get; set; }
        public int MasterID { get; set; }

        public decimal Value { get; set; }

        public Master Master { get; set; }
        public List<SubChild> SubChildren { get; set; }
    }

    public class SubChild
    {
        public int ID { get; set; }
        public int DetailID { get; set; }

        public TimeSpan Time { get; set; }

        public Detail Detail { get; set; }
    }

// target 

    public class DetailDto
    {
        public decimal Value { get; set; }

        public List<SubChildDto> SubChildren { get; set; }
    }

    public class SubChildDto
    {
        public TimeSpan Time { get; set; }
    }
```

### Mapping configuration

```csharp
    Mapper.Initialize(config =>
    {
        config.CreateMap<Detail, DetailDto>();
    });
```

### Version: 7.0.1
Automapper 7.0.1
EF Core 2.1.3

### Expected behavior
Source should be properly mapped. Mapping works when trying to Project on a materialized list (`.ToList().AsQueryable().ProjectTo<DetailDto>();`).

### Actual behavior
Exception is thrown: 
`System.InvalidOperationException: 'The property '' on entity type 'Detail' could not be found. Ensure that the property exists and has been included in the model.'`

### Steps to reproduce
Just run the code from the gist. Add following NuGet packages: `AutoMapper v7.0.1`, `Microsoft.EntityFrameworkCore.SqlServer v2.1.3`.
The database does not need to be created.

**Comment by lbargaoanu** [comment]
This works in EF6. It looks like an EF Core issue.

**Comment by gius** [comment]
I am sorry for the false alarm - I've tried to write the projection by hand and it seemed to work so I assumed that the issue might be with AutoMapper.
However, it seems to be really caused by EF Core: https://github.com/aspnet/EntityFrameworkCore/issues/13140

Sorry again.

**Comment by lbargaoanu** [comment]
No worries :)
