### ISSUE TITLE
Support readonly collection types

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2794]
See #2791 

The generic collection types also implement readonly versions of themselves. 

 - `List<T> : IReadOnlyCollection<T>, IReadOnlyList<T>`
 - `Collection<T> : IReadOnlyCollection<T>`
 - `Dictionary<TKey, TValue> : IReadOnlyCollection<KeyValuePair<TKey,TValue>>, IReadOnlyDictionary<TKey,TValue>`
- `HashSet<T> : IReadOnlyCollection<T>`
- `LinkedList<T> : IReadOnlyCollection<T>`
- `Queue<T> : IReadOnlyCollection<T>`

etc

**Comment by dreamboy789** [comment]
T







At 2018-09-15 12:24:47, "Jimmy Bogard" <notifications@github.com> wrote:


See #2791

The generic collection types also implement readonly versions of themselves.

List<T> : IReadOnlyCollection<T>, IReadOnlyList<T>
Collection<T> : IReadOnlyCollection<T>
Dictionary<TKey, TValue> : IReadOnlyCollection<KeyValuePair<TKey,TValue>>, IReadOnlyDictionary<TKey,TValue>
HashSet<T> : IReadOnlyCollection<T>
LinkedList<T> : IReadOnlyCollection<T>
Queue<T> : IReadOnlyCollection<T>

etc

**Comment by lbargaoanu** [comment]
There is also the class ReadOnlyDictionary. ReadOnlyCollection is already considered.

**Comment by thomaslevesque** [comment]
Note that mapping to `IReadOnlyCollection<T>` or `IReadOnlyList<T>` already works. Only `IReadOnlyDictionary<TKey, TValue>` is missing, as far as I can tell.
