### ISSUE TITLE
Feature request: Object comparation, differences, etc, ....

### ISSUE THREAD

**Issue by sebitsi** [AutoMapper/AutoMapper#2796]
I have read a lot of comments how to implement object comparation and
how we can use already made libraries.

We are using automapper to map our objetcs. There are all configuration implemented already.
We just want to compare object using this configurations.

Have you any plans to implement this feature in automapper  ?

If this feature is not in any plans are there any hooks available we can use to detect it and store diferences in our lists and then using it ?

Thanks for advance.

**Comment by lbargaoanu** [comment]
No, but a PR is welcome.
