### ISSUE TITLE
Generated expression is different for int? and string typed source properties

### ISSUE THREAD

**Issue by gschuager** [AutoMapper/AutoMapper#2797]
### Reproduction:

https://gist.github.com/gschuager/bd54c4dd3acf048a98542302d58be395

### Version: x.y.z
7.0.1

### Expected behavior
Generated mapping expressions for both target properties (CityId and CityName) should be equal: both with conditional null checking.

### Actual behavior
The mapping expression seems to depend on the source property type:

```
    .New ConsoleApp1.PersonModel(){
        CityId = .If ($dtoPerson.City == null) {
            null
        } .Else {
            (System.Nullable`1[System.Int32])($dtoPerson.City).Id
        },
        CityName = ($dtoPerson.City).Name
    }
```

Moreover, I tried using `AllowNull()` on CityId mapping but it seems to be ignored (I need this to get rid of unnecessary CASE statements when using ProjectTo along with NHibernate Linq provider)

### Steps to reproduce
Run reproduction and observe expr.DebugView on the debugger

**Comment by gschuager** [comment]
That's one issue, the other would be that `AllowNull()` is ignored when used on CityId; as I understand, AutoMapper shouldn't generate the conditional expression in that case, right?

**Comment by lbargaoanu** [comment]
AllowNull is just an ad-hoc thing someone added to skip some null checks. Other null checks :) It could be extended to apply to this case. A PR is welcome.

**Comment by gschuager** [comment]
I will take a look into submitting a PR.
About the typing issue, the proposed types are semantically correct: I cannot have a City without an Id, but I can have a Person without a City and I pretend to map that case as a null CityId; your workaround of changing types wouldn't apply for this case.
Also, just being curious, if these are valid concerns and there is room for improvement, why close the issue without resolution?

**Comment by lbargaoanu** [comment]
A simple change would get you the behavior you want. As far as I'm concerned, the issue is solved. About AllowNull, we're not going to do anything about it. About having null checks by default for all cases, that seems too big of a change, it might break a lot of people. So if you want to look deeper into things, you're welcome to do so. And we can discuss what can be done.

**Comment by lbargaoanu** [comment]
And most things ProjectTo does can be customized from [outside AM](https://github.com/AutoMapper/AutoMapper/blob/88a7c788124c184ca570d21f4dda4da32cb17a3b/src/UnitTests/Projection/BindersAndResultConverters.cs). [An example](https://stackoverflow.com/questions/52218340/automapper-projectto-adds-tolist-into-child-properties/52227560#52227560) in the wild.
