### ISSUE TITLE
AssertConfigurationIsValid doesn't throw when inner types cannot be mapped

### ISSUE THREAD

**Issue by DmitryFillo** [AutoMapper/AutoMapper#2799]
### Source/destination types

```csharp
// Source
public class UserInfoV1
{
    public string Data { get; set; }
}

public class UserV1
{
    public string Name { get; set; }
    public UserInfoV1 Info { get; set; }
}

// Destination
public class UserInfoV2
{
    public int Age { get; set; }
    public int Iq { get; set; }
}

public class UserV2
{
    public string Name { get; set; }
    public UserInfoV2 Info { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<UserV1, UserV2>();
});
var mapper = config.CreateMapper();
```

### Expected behavior

`config.AssertConfigurationIsValid()` should throw exception, because `UserInfoV1` cannot be mapped to the `UserInfoV2` without custom mapping configuration.

### Actual behavior

No exceptions by `config.AssertConfigurationIsValid()` call, also no fails at runtime.

### Steps to reproduce

```csharp
config.AssertConfigurationIsValid(); // will not throw

var userV1 = new UserV1
{
    Name = "SomeName",
    Info = new UserInfoV1
    {
        Data = "45_100"
    }
};

// result.Info.Age and result.Info.Iq will be 0
var result = mapper.Map<UserV2>(userV1);
```
### Additional information
Version 5.1.1 works OK: `config.AssertConfigurationIsValid()` will throw exception in the case described above. Seems like it's broken from 6.2.1 (thanks to @akscheglov for determining first broken version).

**Comment by lbargaoanu** [comment]
The workaround is to not use dynamic maps, set CreateMissingTypeMaps to false.
