### ISSUE TITLE
When a target type property is of ISet<T>, the CollectionMapper incorrectly attempts to set it to a List<T>

### ISSUE THREAD

**Issue by codekaizen** [AutoMapper/AutoMapper#28]
A target type may have a property with type of ISet, and the source may be an IEnumerable. AutoMapper detects that the ISet is an ICollection, but assumes that all ICollection instances can be satisfied with a List. This is not true with ISet.

This is a duplicate of issue #27, which was accidentally closed (how?) and cannot, apparently, be reopened.

**Comment by mueblo** [comment]
The fix has been reverted since the commit 61ddd30d119c12ccb160ef2a8dcfceeabd1f64d7.
Could this be re-open ?

**Comment by jbogard** [comment]
Well nuts.

**Comment by lbargaoanu** [comment]
It seems to work now.

**Comment by jbogard** [comment]
Fixed.
