### ISSUE TITLE
Arrugument1 : Cannot Convert from Model.Class to ServiceRefference.Class

### ISSUE THREAD

**Issue by AjayJagtap** [AutoMapper/AutoMapper#2803]
this is my class 1
 public class GOICustValidation
    {
        [RegularExpression(@"^[A-Z]{5}[\d]{4}[A-Z]{1}$", ErrorMessage = "Invalid Format")]
        [Required(ErrorMessage = "Required")]
        [Display(Name = "PAN No.")]
        public string Pan_Number { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Date Of Birth")]
        public string DOB { get; set; }

        public string Error { get; set; }

        public bool NewInvest { get; set; }

        public bool FurtherInvest { get; set; }

        public string redirectAction { get; set; }

        public long? PersonalDId { get; set; } 

        public int? ProductID { get; set; }

        public bool isPanVerify { get; set; } = true;

        public string Client_FirstName { get; set; }
        public string Client_MiddleName { get; set; }
        public string Client_LastName { get; set; }
        
        public long personalDetailId { get; set; }
        public string LastLoginId { get; set; }
        public bool GOI_Bond { get; set; }

    }

this is my class 2 we use wcf service class

[DataContract]
    public class GOICustValidation
    {
        [DataMember]
        public string Pan_Number { get; set; }

        [DataMember]
        public string DOB { get; set; }

        [DataMember]
        public string Error { get; set; }

        [DataMember]
        public bool NewInvest { get; set; }

        [DataMember]
        public bool FurtherInvest { get; set; }

        [DataMember]
        public string redirectAction { get; set; }

        [DataMember]
        public long? PersonalDId { get; set; } = 0;

        [DataMember]
        public int? ProductID { get; set; }

        [DataMember]
        public bool isPanVerify { get; set; } = true;

        [DataMember]
        public string Client_FirstName { get; set; }
        [DataMember]
        public string Client_MiddleName { get; set; }
        [DataMember]
        public string Client_LastName { get; set; }

        [DataMember]
        public long personalDetailId { get; set; }
        [DataMember]
        public string LastLoginId { get; set; }
        [DataMember]
        public bool GOI_Bond { get; set; } = true;
    }
GOICustValidation clsobj = new GOICustValidation();
GOI_ServiceReference.GOICustValidation UCMPanVerifyObj = new GOI_ServiceReference.GOICustValidation();
                            var config = new MapperConfiguration(cfg => { cfg.CreateMap<GOI_ServiceReference.GOICustValidation, GOICustValidation>(); });
                            IMapper mapper = config.CreateMapper();
                            UCMPanVerifyObj = mapper.Map<GOI_ServiceReference.GOICustValidation, GOICustValidation>(clsobj);
                            long? result = GOIDBObj.USP_GOI_CREATE_UCM_ID(UCMPanVerifyObj);

We are getting  Arrugument1 : Cannot Convert from Model.Class to ServiceRefference.Class error on below line **UCMPanVerifyObj = mapper.Map<GOI_ServiceReference.GOICustValidation, GOICustValidation>(**clsobj**);** for clsobj this object 

Please give me solution for above error

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
