### ISSUE TITLE
ProjectTo fail if source and destination have the same property's name

### ISSUE THREAD

**Issue by bielu000** [AutoMapper/AutoMapper#2805]
Source code: https://gist.github.com/bielu000/92fd86c5fc7c0ca35de4f91d2f52ba5f

### Mapping configuration
CreateMap<User, UserModel>();
CreateMap<UsernameAlias, UsernameAliasModel>();

### Version: x.y.z
7.0.1

### Expected behavior
Auto mapper should map properly UserModel to user
### Actual behavior

Mapping fails with comment: 'ArgumentException: Expression of type 'FUII.Storage.Models.UserModel' cannot be used for constructor parameter of type 'FUII.Services.Users.Domain.User'
Parameter name: arguments[0]'

It happes because both User and UserModel have the same property's name which is UsernameAliases. When one of them is renamed it works properly.

### Steps to reproduce
var z = _contex.Users.ProjectTo<UserDto>().ToList(); //it works
var c = _contex.Users.ProjectTo<User>().ToList(); // it doesn't work

**Comment by lbargaoanu** [comment]
It doesn't make sense to project to the same type.

**Comment by bielu000** [comment]
This is not the same type.

**Comment by lbargaoanu** [comment]
Well, it'hard to tell :) Anyway, this kind of question is better suited for StackOverflow.
