### ISSUE TITLE
ProjectTo Adds an inner ToList() on 2 level-deep where

### ISSUE THREAD

**Issue by nlz242** [AutoMapper/AutoMapper#2812]
Hi,

I'm having performance issues which I've tracked to a specific query that is mapped by AutoMapper.
Context:
Mapping is required because we are exposing DTOs thru a webapi that uses OData, we'd rather not expose EF's Entities directly. In the problematic use case, a user tries to get every customer that reside on a specific street, giving an OData query similar to $filter=AdressList.any(o: o.StreetName eq 'SomeStreet')

To isolate the issues, I've created a new console dotnet core 2.1 project and reproduced it with Microsoft's Northwind Database. I also installed ReadableExpressions to see what's going on. 
If I run the projection before my Where clause, i get a pretty funky query with an inner ToList(), which then hits a known limitation of EF Core 2.1 (https://github.com/aspnet/EntityFrameworkCore/commit/b95f23ffa4fbba305b3f0ea4c864fe53f456ad58) that ends up doing 1+N queries to SQL Server.
> - doesn't work if inner query is correlated with query two (or more) levels up, (e.g. customers.Select(c > => c.Orders.Select(o => o.OrderDetails.Where(od => od.Name == c.Name).ToList()).ToList())

If i run the projection after my Where clause, i get a nice simple query which runs in 2 queries .

Obviously, in my real-world scenario, if i wanted to add my Where clause before the projection, i'd have to parse the OData myself and emit an OData targetting my EF Entity, which seems both impractical and risky.

I'm not sure this is a bug/issue or if i'm not using AutoMapper properly. Thanks in advance!

#### Source
```csharp
   public partial class Orders
    {
        public Orders()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int OrderId { get; set; }
        public string CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        public decimal? Freight { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipRegion { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }

        public ICollection<OrderDetails> OrderDetails { get; set; }
    }

    public partial class OrderDetails
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }

        public Orders Order { get; set; }
        public Products Product { get; set; }
    }

    public partial class Products
    {
        public Products()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? SupplierId { get; set; }
        public int? CategoryId { get; set; }
        public string QuantityPerUnit { get; set; }
        public decimal? UnitPrice { get; set; }
        public short? UnitsInStock { get; set; }
        public short? UnitsOnOrder { get; set; }
        public short? ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        public ICollection<OrderDetails> OrderDetails { get; set; }
    }

```
#### Destination 

```csharp
    public class OrdersDto
    {

        public int OrderId { get; set; }
        public string CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        public decimal? Freight { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipRegion { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }

        public ICollection<OrderDetailsDto> OrderDetails { get; set; }

    }

    public class ProductsDto
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? SupplierId { get; set; }
        public int? CategoryId { get; set; }
        public string QuantityPerUnit { get; set; }
        public decimal? UnitPrice { get; set; }
        public short? UnitsInStock { get; set; }
        public short? UnitsOnOrder { get; set; }
        public short? ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    }

    public class OrderDetailsDto
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }

        public ProductsDto Product { get; set; }
    }
```
### Mapping configuration

```csharp
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Orders, OrdersDto>().ReverseMap();
                cfg.CreateMap<OrderDetails, OrderDetailsDto>().ReverseMap();
                cfg.CreateMap<Products, ProductsDto>().ReverseMap();
            });
```

### Version: x.y.z
    <PackageReference Include="AutoMapper" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.3" />

### Expected behavior

I expected a query expression similar to what querying directly EF with Linq gives, without an inner ToLost().
Something similar to this : 
```csharp
EntityQueryable<Orders>
    .Include(x => x.OrderDetails)
    .ThenInclude(x => x.Product)
    .Where(x => x.OrderDetails.Any(od => od.Product.ProductName == "Chai"))
```
### Actual behavior

I get a query expression with an inner ToList() which triggers 1+N queries to the Database, similar to this :
```csharp
EntityQueryable<Orders>
    .Include(x => x.OrderDetails)
    .ThenInclude(x => x.Product)
    .Select(dtoOrders => new OrdersDto
    {
        CustomerId = dtoOrders.CustomerId,
        EmployeeId = dtoOrders.EmployeeId,
        Freight = dtoOrders.Freight,
        OrderDate = dtoOrders.OrderDate,
        OrderDetails = dtoOrders.OrderDetails.Select(dtoOrderDetails => new OrderDetailsDto
            {
                Discount = dtoOrderDetails.Discount,
                OrderId = dtoOrderDetails.OrderId,
                Product = (dtoOrderDetails.Product == null)
                    ? null
                    : new ProductsDto
                    {
                        CategoryId = dtoOrderDetails.Product.CategoryId,
                        Discontinued = dtoOrderDetails.Product.Discontinued,
                        ProductId = dtoOrderDetails.Product.ProductId,
                        ProductName = dtoOrderDetails.Product.ProductName,
                        QuantityPerUnit = dtoOrderDetails.Product.QuantityPerUnit,
                        ReorderLevel = dtoOrderDetails.Product.ReorderLevel,
                        SupplierId = dtoOrderDetails.Product.SupplierId,
                        UnitPrice = dtoOrderDetails.Product.UnitPrice,
                        UnitsInStock = dtoOrderDetails.Product.UnitsInStock,
                        UnitsOnOrder = dtoOrderDetails.Product.UnitsOnOrder
                    },
                ProductId = dtoOrderDetails.ProductId,
                Quantity = dtoOrderDetails.Quantity,
                UnitPrice = dtoOrderDetails.UnitPrice
            }).ToList(),
        OrderId = dtoOrders.OrderId,
        RequiredDate = dtoOrders.RequiredDate,
        ShipAddress = dtoOrders.ShipAddress,
        ShipCity = dtoOrders.ShipCity,
        ShipCountry = dtoOrders.ShipCountry,
        ShipName = dtoOrders.ShipName,
        ShippedDate = dtoOrders.ShippedDate,
        ShipPostalCode = dtoOrders.ShipPostalCode,
        ShipRegion = dtoOrders.ShipRegion,
        ShipVia = dtoOrders.ShipVia
    })
    .Where(x => x.OrderDetails.Any(od => od.Product.ProductName == "Chai"))
```
### Steps to reproduce

Repro : [ProjectToQueries.zip](https://github.com/AutoMapper/AutoMapper/files/2428452/ProjectToQueries.zip)
Create database "standard" Northwind database (script included in zip) and modify the connection string on NorthwindContext.cs line 28.

OR 

```csharp
            // Simple Expression
            using (var context = new NorthwindContext())
            {
                var o = context.Orders;
                var query = o
                    .Include(x => x.OrderDetails).ThenInclude(x => x.Product)
                    .Where(x => x.OrderDetails.Any(od => od.Product.ProductName == "Chai"));

                var projectedQuery = query.ProjectTo<OrdersDto>();

                string readable = query.Expression.ToReadableString();

                var data = projectedQuery.ToList();
            }
            // Problematic Expression
            using (var context = new NorthwindContext())
            {
                var o = context.Orders;

                var query = o
                    .Include(x => x.OrderDetails).ThenInclude(x => x.Product);

                var projectedQuery = query.ProjectTo<OrdersDto>()
                    .Where(x => x.OrderDetails.Any(od => od.Product.ProductName == "Chai"));

                string readable = projectedQuery.Expression.ToReadableString();

                var data = projectedQuery.ToList();
            }
```

**Comment by lbargaoanu** [comment]
I think so.

**Comment by nlz242** [comment]
Ok, i understand the difference and i think i get why it goes south like that.

Having the .Where after .Select, the Where is applied to my projection's result (the DTO). Impossible for EF to know how to deal it, so i think it has to enumerate and run that last Where in memory.

Whereas having the .Where before .Select, the Where is applied to the Database Entities and EF knows how to deal with that efficently.

So i guess this is a bug with AutoMapper where it should map Where clauses to the database entity and not to the projection, thus giving EF what it needs to do it's work efficently.

Am i wrong ?

**Comment by lbargaoanu** [comment]
You decide where to put the Where :) ProjectTo should be last and then the where would be on the entity. If it's not the last, then the where must be on the DTO and EF will decide what to do. That would work in EF6.

**Comment by nlz242** [comment]
Yeah, in the repro, i do decide, however in my real-life use case where the where comes from an OData $filter on the DTO, i really have no choice but to use odata's ApplyFilter on an IQueryable of my DTO to generate the query.

I was under the impression that using AutoMapper's ProjectTo was gonna lead to the query being mapped (including it's wheres), not just being added on top.

For example, i expected that both the following queries would give the same request : 
cfg.CreateMap<Employees, EmployeesDto>().ForMember(dto => dto.First_Name, conf => conf.MapFrom(ent => ent.FirstName)).ReverseMap();
o.ProjectTo<EmployeesDto>().Where(x => x.First_Name == "Janet");
context.Employees.Where(x => x.FirstName == "Janet");

But after testing them and look at the Expression result, i understand they are not.
My assumption that it would map everything (including queries's where) to the target was wrong. 

So i guess this is not a bug but rather a feature that does not exist, eh.

Thanks for the input

**Comment by nlz242** [comment]
Turns out the feature i was looking for does exist. it's just not part of the main project.
UseAsDatasource().For<MyDto> from the AutoMapper.Extensions.ExpressionMapping seems to do what i want. I only tested it in my repro, but i'll go full scale with it to see what happens.

Thanks again for the input, while it did not fix my issue, it did set me on the right track !

**Comment by lbargaoanu** [comment]
Yes, ProjectTo is not really designed for OData.

**Comment by lbargaoanu** [comment]
I've just tested again and indeed in EF6 a filter for the DTO is applied in the database. EF Core is different :)
