### ISSUE TITLE
Guidance wanted: How to use automapper with Odata Delta<T>

### ISSUE THREAD

**Issue by brijeshb** [AutoMapper/AutoMapper#2816]
### Source/destination types

```csharp
// Put your source/destination types here
public class TPublicEntity
{
    public string Name {get;set;}
}

public class TInternalEntity
{
    public string Name {get;set;}
}
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
CreateMap<TPublicEntity,TInternalEntity>();
```

### Version: 
Latest

### Expected behavior
var deltaOfTInternalEntity = Mapper.Map<TInternalEntity>(DeltaOfTPublicEntity);

After searching around found really old posts about how this is supposed to be supported now.
Wanted to know if this is supported and how to achieve it. Seems like a common use case for anyone using automapper with odata.

**Comment by lbargaoanu** [comment]
There is no explicit support in AM for this.

**Comment by lbargaoanu** [comment]
There is some OData support in the expressions package, but not for the delta thing.

**Comment by brijeshb** [comment]
Thanks for confirming
