### ISSUE TITLE
'Nullable object Must Have value' exception when using ProjectTo with some conditions

### ISSUE THREAD

**Issue by klaussj** [AutoMapper/AutoMapper#2819]
### Source/destination types

```csharp
public class Entity
{
	public int Id { get; set; }
	public int? RefEntityId { get; set; }
	public RefEntity RefEntity { get; set; }
}

public class RefEntity
{
	public int Id { get; set; }
}

public class EntityDto
{
	public int Id { get; set; }
	public int? RefEntityId { get; set; }
	public RefEntityDto RefEntity { get; set; }
}

public class RefEntityDto
{
	public int Id { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Entity, EntityDto>();
CreateMap<RefEntity, RefEntityDto>();
```

### Version: x.y.z
7.0.1 or 8.0.0-ci-01495

### Actual behavior
```csharp
db.Set<Entity>().ProjectTo<EntityDto>(null, "RefEntity "); // throws 'Nullable object Must Have value'
```

### Expected behavior
Same result as when you remove the ProjectTo : FK should be not null and navigation property should be null if not found

### Steps to reproduce
In the Entity table remove the FK contraint on RefEntityId and put a value that is not referencing any value from EntityRef.
In my case it's happening because an EF query filter is filtering the referenced entity.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
I don't see anything wrong with AM here. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And try that query without AM. If the query looks good to you and it crashes, you have a repro without AM. So maybe it's an EF Core issue.

**Comment by klaussj** [comment]
It is an EF Core issue. I'm closing this, thanks for the help.
