### ISSUE TITLE
Mapping Data Reader to Business entity "CODE"

### ISSUE THREAD

**Issue by Hamaresha** [AutoMapper/AutoMapper#282]
An issue when trying to map a custom business entity that contains a property as CODE, the AutoMapper can't resolve the whole entity and the whole object is broken !

example 

public class CustomEntity
{
   public string CODE {get; set;}
   public string Name {get; set;}
}

and on mapping :

 AutoMapper.Mapper.Reset();
 AutoMapper.Mapper.CreateMap&lt;IDataReader, CustomEntity&gt;();
 result = AutoMapper.Mapper.Map&lt;IDataReader, CustomEntity&gt;(myReader);

the value for 
result.CODE = ??
result.Name = ?? 

and when trying to access the property an exception is thrown ! 

after digging into the mapper i realize that it uses ILGenerator in case of data reader, the CODE keyword is a reserved word and that was my issue, i changed the Code propty to something else, i hop i will not face any issue in future, can you let me know of the reserved keywords like this ?

**Comment by jbogard** [comment]
@ewaschenko yes it does!
