### ISSUE TITLE
MemberList.None doesn't work

### ISSUE THREAD

**Issue by lusocoding** [AutoMapper/AutoMapper#2824]
Hi. I have a weird business case here and I'm using Automapper. 
I have to map between some very similar, not to say identical, classes that live in different assemblies.
Since the real project have a lot of classes, I was trying to avoid having to add Ignore property declarations, one by one, so I come up with the below code and tried to dynamically create mappings and enforce no validation passing the MemberList.None enum to the CreateMap method.
Issue here is that I'm always getting unmapped property exceptions. Shouldn't the MemberList.None enum resolve this and avoid this kind of validations?

### Source/destination types

```csharp

namespace AutomapperDynamicMapCreation.Domain
{
    public class Request
    {
        public int TransactionId { get; set; }

        public Person PersonData { get; set; }
    }

    public class Response
    {
        public int TransactionID { get; set; }

        public Person PersonData { get; set; }
    }

    public class Person
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public Address HomeAddress { get; set; }
    }

    public class Address
    {
        public string Line01 { get; set; }

        public string Line02 { get; set; }

        public string ZipCode { get; set; }
    }
}

namespace AutomapperDynamicMapCreation.Data
{
    public class Message
    {
        public Guid ID { get; set; }

        public int TransactionId { get; set; }

        public Person PersonData { get; set; }
    }

    public class Person
    {
        public Guid ID { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public Address HomeAddress { get; set; }
    }

    public class Address
    {
        public Guid ID { get; set; }

        public string Line01 { get; set; }

        public string Line02 { get; set; }

        public string ZipCode { get; set; }
    }
}
```

### Mapping configuration

```csharp
AutoMapper.Mapper.Initialize(m =>
            {
                m.CreateMissingTypeMaps = false;

                var domainAssembly = Assembly.GetAssembly(typeof(Domain.Request));
                var dataAssembly = Assembly.GetAssembly(typeof(Data.Message));

                foreach (var domainType in domainAssembly.GetExportedTypes())
                {
                    var dataType = dataAssembly.GetType($"AutomapperDynamicMapCreation.Data.{domainType.Name}");
                    if (dataType != null)
                    {
                        m.CreateMap(domainType.GetType(), dataType.GetType(), AutoMapper.MemberList.None);
                        m.CreateMap(dataType.GetType(), domainType.GetType(), AutoMapper.MemberList.None);
                    }
                }

                m.CreateMap<Domain.Request, Data.Message>(AutoMapper.MemberList.None);
                m.CreateMap<Data.Message, Domain.Response>(AutoMapper.MemberList.None);
            });
```

### Expected behavior

Mapping should occur from Domain.Request to Data.Message and from Data.Message to Domain.Response without any exceptions and without validating if there are any unmapped properties.

### Actual behavior

Mapping throws exception due to unmapped properties:

Error mapping types.

Mapping types:
Request -> Message
AutomapperDynamicMapCreation.Domain.Request -> AutomapperDynamicMapCreation.Data.Message

Type Map configuration:
Request -> Message
AutomapperDynamicMapCreation.Domain.Request -> AutomapperDynamicMapCreation.Data.Message

Property:
PersonData

### Steps to reproduce

```csharp
            var request = new Domain.Request()
            {
                TransactionId = 100,
                PersonData = new Domain.Person
                {
                    FirstName = "Foo",
                    LastName = "Bar",
                    HomeAddress = new Domain.Address
                    {
                        Line01 = "Sesame",
                        Line02 = "Street",
                        ZipCode = "1000"
                    }
                }
            };

            var dataMessage = AutoMapper.Mapper.Map<Data.Message>(request);
            var domainResponse = AutoMapper.Mapper.Map<Domain.Response>(dataMessage);
```

**Comment by lbargaoanu** [comment]
You need to further isolate the issue.

**Comment by lusocoding** [comment]
@lbargaoanu I've checked and same thing happens regardless of the MemberList option I pass to the constructor. Exact same issue when using MemberList.Source for example.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lusocoding** [comment]
@lbargaoanu I have all the code in a github repo: https://github.com/lusocoding/samples-and-experiments/tree/master/dotnet/AutomapperDynamicMapCreation
you can use that one to test for yourself.

**Comment by lbargaoanu** [comment]
This is not a validation error. It complains about a missing map or smth. I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
You're not calling AssertConfigurationIsValid anywhere. That's supposed to help.

**Comment by lusocoding** [comment]
Hi @lbargaoanu, thanks for the tip of the AssertConfigurationIsValid. I totally forgot of that one. 
I found out the issue. It was the extra ".GetType" that was in each of the CreateMap calls, since the domainType and dataType already contained the desired types to be mapped and the extra GetType would create various mappings between System.RuntimeType to System.RuntimeType which would invalidate the configurations.
