### ISSUE TITLE
InvalidCastException when using implicit mapping and mapping a derived model after first mapping its base model

### ISSUE THREAD

**Issue by samueldjack** [AutoMapper/AutoMapper#2828]
### Source/destination types

```csharp
 public class Customer
        {
            public Customer()
            {
            }

            [Key]
            public int Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        public class CustomerViewModel
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string Address { get; set; }
        }

        public class DerivedCustomerViewModel : CustomerViewModel
        {

        }
```

### Mapping configuration

Using implicitly created maps.

### Version: x.y.z
7.0.1

### Expected behavior

Calling the following two lines in order should work:

```csharp
var customerVm = context.Customers.ProjectTo<CustomerViewModel>(configuration).First();
var derivedCustomerVm = context.Customers.ProjectTo<DerivedCustomerViewModel(configuration).First();
```

### Actual behavior

Instead I get the exception

    System.InvalidCastException
    Unable to cast object of type 'System.Data.Entity.Infrastructure.DbQuery`1[AutoMapper.IntegrationTests.AutoMapCreationBug+CustomerViewModel]' to type 'System.Linq.IQueryable`1[AutoMapper.IntegrationTests.AutoMapCreationBug+DerivedCustomerViewModel]'.
       at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)

### Steps to reproduce

Please see the complete failing test (named Can_automap_derived_model_after_base_model) in this [gist](https://gist.github.com/samueldjack/f14833111290c0da7f96a825edb26e40)

### More info

It seems that the problem is in MapperConfiguration.GetTypeMap. When this is called with an initialPair of (Customer, DerivedCustomerViewModel) it returns (Customer, CustomerViewModel) as the resolved type map.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2589#issuecomment-378591481

**Comment by samueldjack** [comment]
I'm puzzled as to why this issue has been closed so swiftly.

@lbargaoanu, I've noted your comment in the other thread (which I agree is a duplicate of this issue) where you recommend not mixing inheritance with dynamic maps. But you haven't explained why. It doesn't seem an unreasonable thing to me, and I've not noticed anything in the documentation to say why it shouldn't work.

It seems to me that there is a bug here because the code works correctly if I happen to use the mappings in one order, but not in another. 

@jbogard Any thoughts on this?

**Comment by lbargaoanu** [comment]
So when a map is missing, AM will create one for you. This same map will also apply for the derived type. But it will not work. So it happens that the other way around it works. That's just an accident.
