### ISSUE TITLE
Wrong number of elements returned by ProjectTo

### ISSUE THREAD

**Issue by Tbd19** [AutoMapper/AutoMapper#2830]
I have an application where I use ProjectTo with configuration provider and some parameters. 
I am running some unit tests and I discovered something bothersome

Even though the IQueryable contains one element appying ProjectTo returns an IQueryable with 0 elements.
Is this function as design? If the error is swallowed by some code is there a way to log that error and determine what is the problem?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by Tbd19** [comment]
Sorry for the late response .
After further investigation I have found the issue.

The mapping had a line like this
.ForMember(dest => dest.Property, opt => opt.MapFrom(src => src.Child.Child.Name))

and the mapped object had the Child null (Both child properties should not be null).

It seems that the new AutoMapper is swallowing the errors and returns the incorect number of results.

**Comment by lbargaoanu** [comment]
I get the same result (an outer join and null for that column) without AM. So it seems EF is doing this.
