### ISSUE TITLE
Use dependency injection in object mappers

### ISSUE THREAD

**Issue by gtaylor1981** [AutoMapper/AutoMapper#2835]
A great feature of AutoMapper is the ability to use dependency injection from value resolvers and type converters (with the AutoMapper.Extensions.Microsoft.DependencyInjection package).
In a similar way, I would like to extend the `ObjectMapper<object, string>` to use an internal service to convert string values to model objects and vice versa.
However, I cannot find a way to inject this service into my object mapper neatly.

It might be possible using the `ResolutionContext` in the `Map` overload, i.e. `context.Options.CreateInstance<IService>()` but this is not available in the IsMatch() function.

Is using a service via dependency injection in an ObjectMapper object possible?

**Comment by jbogard** [comment]
No. The object mappers are static, and IsMatch is cached for performance.
Since it’s all static, you can use service locator instead.

**Comment by lbargaoanu** [comment]
So a type map from object to string is not good enough?

**Comment by gtaylor1981** [comment]
Thanks for the quick replies. I already had a `ConverterService` which I wanted to reuse by wrapping it in an `ObjectMapper`.
In fact, I also have the option to use .NET `TypeConverters`, but the `TypeConverterMapper` is never called, as the `StringMapper` has a slightly higher priority. Is there a specific reason that the `StringMapper` has this higher priority? Could I just swap it with the `TypeConverterMapper`?

**Comment by lbargaoanu** [comment]
Well, we could say it's more specific so it should have a chance to run first, but really, the order of the mappers is a tricky subject. So we'd rather not mess with that. We didn't change it for some time now, so I guess it's the right order :) You can insert your own mapper wherever you want. In theory you can alter anything about the mappers collection, but as I've said, it's tricky.
