### ISSUE TITLE
ProjectTo fails on mapping child entity guid property

### ISSUE THREAD

**Issue by avalon456** [AutoMapper/AutoMapper#2836]
### Source/destination types

```csharp
public abstract class Entity
    {
        public Guid Id { get; set; }
    }
public class Correspondent: Entity
    {
        public virtual Company Company { get; set; }
    }
public class Company: Entity
    {
        public string Name { get; set; }
        public virtual IList<Correspondent> Correspondents { get; set; } = new List<Correspondent>();
    }
public class CreatorModel
    {
        public string Id { get; set; }
        public CompanyModel Company { get; set; }
    }
 public class CompanyModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
```

### Mapping configuration

```csharp
CreateMap<Company, CompanyModel>();
CreateMap<Correspondent, CreatorModel>();
```

### Version: x.y.z
Automapper 7.0.1

### Expected behavior

List of CreatorModel Objects

### Actual behavior

Error 
![image](https://user-images.githubusercontent.com/31688327/47135634-e31b9180-d2d2-11e8-8238-fbec8f609f99.png)
### Steps to reproduce

```csharp
private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public ValuesController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
[HttpGet]
        public ActionResult<IEnumerable<CreatorModel>> Get()
        {
            return _context.Correspondents.ProjectTo<CreatorModel>(_mapper.ConfigurationProvider).ToList();
        }
```
When mapping like this all works as expected
```
_mapper.Map<IList<CreatorModel>>(_context.Correspondents.ToList())
```
Also when i change models Id type to Guid, all works.

```
public class CompanyModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
```

**Comment by avalon456** [comment]
Also when i change models Id type to Guid, all works.

```
public class CompanyModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
```

**Comment by lbargaoanu** [comment]
I don't see it. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by avalon456** [comment]
> I don't see it. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

https://gist.github.com/avalon456/bbf2ef4c5a4ea91e02ac3fa217a566ce

**Comment by lbargaoanu** [comment]
This works with EF6. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And run that query without AM. If the query looks good and it still fails, then it's an EF Core issue.

**Comment by avalon456** [comment]
> This works with EF6. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And run that query without AM. If the query looks good and it still fails, then it's an EF Core issue.

Could you please tell me how to run this?
`
var expression = context.Correspondents.ProjectTo<CreatorModel>(mapper.ConfigurationProvider).Expression;
`

**Comment by lbargaoanu** [comment]
It's just a linq query. That expression tells you what exactly it's in the query AM generates for you.

**Comment by avalon456** [comment]
```
.Lambda #Lambda2<System.Func`2[TestProject.Program+Correspondent,TestProject.Program+CreatorModel]>(TestProject.Program+Correspondent $dtoCorrespondent)
{
    .New TestProject.Program+CreatorModel(){
        Company = .If ($dtoCorrespondent.Company == null) {
            null
        } .Else {
            .New TestProject.Program+CompanyModel(){
                Id = .Call (($dtoCorrespondent.Company).Id).ToString(),
                Name = ($dtoCorrespondent.Company).Name
            }
        },
        Id = .Call ($dtoCorrespondent.Id).ToString()
    }
}
```
I extracted this expression  from DebugView of Expression and built on its basis next request
```
var query = context.Correspondents.Select(c => new CreatorModel
            {
                Company = c.Company == null ? null : new CompanyModel { Id = c.Company.Id.ToString(), Name = c.Company.Name},
                Id = c.Id.ToString()
            });
            var result = query.ToList();
```
It works

**Comment by avalon456** [comment]
> This works with EF6. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). And run that query without AM. If the query looks good and it still fails, then it's an EF Core issue.

```
.Lambda #Lambda2<System.Func`2[TestProject.Program+Correspondent,TestProject.Program+CreatorModel]>(TestProject.Program+Correspondent $dtoCorrespondent)
{
    .New TestProject.Program+CreatorModel(){
        Company = .If ($dtoCorrespondent.Company == null) {
            null
        } .Else {
            .New TestProject.Program+CompanyModel(){
                Id = .Call (($dtoCorrespondent.Company).Id).ToString(),
                Name = ($dtoCorrespondent.Company).Name
            }
        },
        Id = .Call ($dtoCorrespondent.Id).ToString()
    }
}
```
I extracted this expression  from DebugView of Expression and built on its basis next request
```
var query = context.Correspondents.Select(c => new CreatorModel
            {
                Company = c.Company == null ? null : new CompanyModel { Id = c.Company.Id.ToString(), Name = c.Company.Name},
                Id = c.Id.ToString()
            });
            var result = query.ToList();
```
It works

**Comment by avalon456** [comment]
Mapping works if i add Foreign key property into parent entity
```
public class Correspondent: Entity
    {
        public virtual Company Company { get; set; }
        public Guid CompanyId { get; set; }
    }
```

**Comment by lbargaoanu** [comment]
Weird. But it only confirms it's an EF Core issue. What's also weird is that we are unable to repro it without AM. But I, for one, don't see anything wrong with the AM part here. @jbogard Do you agree?

**Comment by jbogard** [comment]
*Something* is different though, if there's that nullable Guid thrown in the mix. Can you output the actual expression from the manual version?

**Comment by lbargaoanu** [comment]
You would think :) But there's no nullable in the code. EF is probably doing smth. The expressions look the same to me.
```.Lambda #Lambda1<System.Func`2[AMProjectTo.Correspondent,AMProjectTo.CreatorModel]>(AMProjectTo.Correspondent $dtoCorrespondent)
{
    .New AMProjectTo.CreatorModel(){
        Company = .If ($dtoCorrespondent.Company == null) {
            null
        } .Else {
            .New AMProjectTo.CompanyModel(){
                Id = .Call (($dtoCorrespondent.Company).Id).ToString(),
                Name = ($dtoCorrespondent.Company).Name
            }
        },
        Id = .Call ($dtoCorrespondent.Id).ToString()
    }
}```

**Comment by jbogard** [comment]
If the expressions were equivalent, they'd be interpreted the same, right? Is there some weird cast or something thrown in?

**Comment by lbargaoanu** [comment]
I agree there must be a difference somewhere between the two calls, but I don't see it.

**Comment by avalon456** [comment]
Why AM tries to map Nullable Guid?

**Comment by lbargaoanu** [comment]
It doesn't. That's EF code.

**Comment by lbargaoanu** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/10284#issuecomment-363242431

**Comment by avalon456** [comment]
Seems that should be fixed in 2.2.0. Waiting for release version

**Comment by avalon456** [comment]
Seems that should be fixed in 2.2.0. Waiting for release version

**Comment by lbargaoanu** [comment]
No, I see the same with 2.2.0-preview3-35497. But it looks like that's the cause.

**Comment by lbargaoanu** [comment]
:) I'm afraid you'll have to ask the EF Core team about this one.

**Comment by avalon456** [comment]
@lbargaoanu, Shouldn't they be notified that you referenced to the issue

**Comment by BlaiseD** [comment]
One difference is that the ToString method `Call ($dtoCorrespondent.Id).ToString()` has a declaring type of System.Guid in the ProjectTo expression vs System.Object in the "Without AM" expression.

The following configuration does work (also results in a System.Object declaring type for Id.ToString()):

```c#
            var config = new MapperConfiguration(c =>
            {
                c.CreateMap<Company, CompanyModel>()
                .ForMember(dest => dest.Id, opts => opts.MapFrom(x => x.Id.ToString()));
                c.CreateMap<Correspondent, CreatorModel>()
                .ForMember(dest => dest.Id, opts => opts.MapFrom(x => x.Id.ToString()));
            });
```

**Comment by lbargaoanu** [comment]
Thanks! Didn't notice that. It's still an EF Core issue. There's no nullable Guid in the AM expression, right? :)

**Comment by BlaiseD** [comment]
Possibly - but that last part of the error message could be a decoy.  It is trying to call Guid.ToString on a string.  I'm not familiar with the ProjectTo code though.
