### ISSUE TITLE
Nested ExplicitExpansion with 1:many sub-property

### ISSUE THREAD

**Issue by benmccallum** [AutoMapper/AutoMapper#2845]
Say I have an Account type that can have many Users, then corresponding DTOs for them, and for both relations Account > AccountDto and User > UserDto I have enforced explicit expansion for all properties...

How would I use the `ProjectTo<AccountDto>` overload with `params Expression<Func<TDestination, object>>[] membersToExpand` to select a property that I want on a User?

I've tried the following but it doesn't work. I end up with `accounts.Users` being `null`.
```cs
var accounts = await _dbContext.Accounts
    .ProjectTo<AccountDto>(_mapperConfig,
        a => a.AccountID,
        a => a.Users,
        a => a.Users.Select(u => u.UserID))
    .ToArrayAsync();
```

This does, and if that's the only option it'll do, but just wondering if above was supposed to be supported or isn't/can't be:
```cs
var accounts = await _dbContext.Accounts
    .ProjectTo<AccountDto>(_mapperConfig, null, new [] { "AccountID", "Users", "Users.UserID" })
    .ToArrayAsync();

// Note: would use nameof(Account.AccountID) to build these and at least have some type checking.
```

Cheers!

**Comment by benmccallum** [comment]
FYI, I've have a peruse in the docs and the tests but couldn't find anything specifically with this scenario. The nested properties are 1:1, so no need to build an expression that digs into a 1:many.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/2a6cc1cb055064e241a3ef191886d10d3fef1a82/src/IntegrationTests/ExplicitExpansion/ExpandCollections.cs#L29

**Comment by benmccallum** [comment]
🤦‍♂️ . Lemme look again. I think I've just rubber duck debugged it. I'm doing my original query on a join table and not selecting the Account before doing the projection, so it seems like some props are being set and not others but that's pure coincidence.

**Comment by benmccallum** [comment]
Yep, nevermind me. Thx for pointing out the test though!
