### ISSUE TITLE
Expression could not be translated after using ProjectTo

### ISSUE THREAD

**Issue by Mansu12135** [AutoMapper/AutoMapper#2847]
Hi,

I have two entities Parent and child with appropriate Dto.
```
public class Parent {
 public string Name {get;set;}
 
 public int ChildId {get;set;}
 
 public virtual Child Child {get;set;}
}

public class Child {
  public int Id {get;set}
  public int Age {get;set;}
}
```
 When I write query like this:
 `context.Parents.ProjectTo<ParentDto>.Where(item => item.Child.Age > 8).ToList();`
my query are evaluated locally.  Queries without ProjectTo evaluated on Sql server side. Can you help me resolve it? Thank you.

**Comment by lbargaoanu** [comment]
ProjectTo has to be before Where.

**Comment by Mansu12135** [comment]
I want to create query on dto object's and translate it to db. For this reason, I must write ProjectTo before where or another expression.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. You might want to try expression mapping.
