### ISSUE TITLE
Is ProjectTo and DI mutually exclusive?

### ISSUE THREAD

**Issue by DDtMM** [AutoMapper/AutoMapper#2851]
I'm confused about the relationship between ProjectTo and DI.  Please see the [Dependency Injection Guide ](http://docs.automapper.org/en/latest/Dependency-injection.html?highlight=Gotchas).  In it, it says ProjectTo and DI are mutually exclusive and suggests to use `IEnumerable.Select(_mapper.Map<DestinationType>).ToList()`.

1. `Select(_mapper.Map<DestinationType>)` doesn't work with IQueryables.
2. Isn't this statement false, as I can just pass the ConfigurationProvider from my mapper instance by calling `.ProjectTo<TEntity>(mapper.ConfigurationProvider)`?

Is there something wrong with passing configurationProvider?  If there isn't, may I suggest providing a convenient overload where mapper is passed instead - just to keep down the verbosity, as well as updating the documentation appropriately.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/pull/2850#pullrequestreview-168783359 I don't think passing IMapper is a good idea, but feel free to write your own convenience overload.

**Comment by DDtMM** [comment]
Thanks for the response, @lbargaoanu, I will do that.

But is passing mapper.Configuration to ProjectTo a bad idea, or should the documentation be changed to reflect that this is a possibility?

If this is the wrong direction, then what is best practice when using DI and EntityFramework?   I feel I'm not unique in wanting to stay consistent by not having a mixture of static and injected dependencies with a preference towards DI.

Thank you.

**Comment by lbargaoanu** [comment]
Did you follow that link? What else can we add to make things more clear?
