### ISSUE TITLE
Scalar function mapping not supported

### ISSUE THREAD

**Issue by Tbd19** [AutoMapper/AutoMapper#2854]
The EF Core 2.0 has introduced the Scalar function mapping.

I have the following configuration
 CreateMap<Device, DeviceEditViewModel>()
	 .ForMember(dest => dest.TotalCosts, opt => opt.MapFrom(src => DbContextFunctions.GetDeviceTotalCosts(src.ID)));

However this will throw the exception

Exception: Exception of type 'System.Exception' was thrown.

....DbContextFunctions.GetDeviceTotalCosts(int deviceId) in DbContextFunctions.cs

AutoMapperMappingException: Error mapping types.

 Mapping types:
 Device -> DeviceEditViewModel
 Schaeffler.Entities.Models.Device -> Schaeffler.Entities.ViewModels.DeviceEditViewModel

 Type Map configuration:
 Device -> DeviceEditViewModel
 Schaeffler.Entities.Models.Device -> Schaeffler.Entities.ViewModels.DeviceEditViewModel

 Property:
 TotalCosts

lambda_method(Closure , Device , DeviceEditViewModel , ResolutionContext )

**Comment by lbargaoanu** [comment]
A PR is welcome.
