### ISSUE TITLE
Feature Req: Lazy load the mapping configurations?

### ISSUE THREAD

**Issue by sjuranek** [AutoMapper/AutoMapper#2855]
We have a large web project with 900+ screens and currently 1524 mappings that we configure in AutoMapper. We use reflection to find and configure all the mappings. On application startup it is taking about 15-16 seconds for the mapping work to finish. No big deal for production but for devs that build many times a day we are waiting for a slow ASP.NET site to load (still on .NET 4.6). I'm not sure the answer is lazy loading but that came to mind. And maybe this many mappings is a code smell but I think it would be typical of many large projects with a many view models and DTOs. Thank you for any ideas/input you have.

**Comment by huferry** [comment]
We're facing the same issue. Do you have any solution to yours, @sjuranek ?

**Comment by sjuranek** [comment]
@huferry  - Unfortunately no. We made the mistake of using AutoMapper directly throughout the code (e.g. ProjectTo) instead of putting it behind our own abstraction as well. An ideal solution for us is generating the mappings at build/compile time but we have yet to explore that and see if someone has done that or how we would do it.

**Comment by jbogard** [comment]
Abstraction wouldn’t have helped swap anything out. Have you profiled to
see where the time is spent?

**Comment by sjuranek** [comment]
We didn't profile it yet. AutoMapper feels fast and great at what it does. But over time as our project grew it is now just doing thousands of mappings.  We have a convention on POCOd to add IMapTo<>, IMapFrom<>, ICustomMapTo<>, ICustomMapFrom<> so that developers on the team mark what should get loaded into AutoMapper at startup. On the ICustomXXX interfaces they then add custom mapping code. If I dug into deeper I suspect we are doing "custom" mapping when we don't need to. Also we have mappings that probably aren't used anymore but still being loaded (need to figure out a good way to find them). Its a large ASP.NET 4.7.2 application so there are a lot of other slow aspects when spinning up the app locally, like a big EF Context, StructureMap load time, and just the slowness of ASP.NET. Sometime we will get back to this and my plan was to look at AutoMapper source and see if there is a way, at least during local development, that we can lazy load so that we aren't loading thousands of mappings when generally a developer is working in on an area and will only use a small number of them. Also doing less custom mapping, etc. We are following the recent guidelines you published in general, but I'm guessing there are some spots we don't and need to not try to use AutoMapper there. (more code reviews)

I'm just brainstorming but if I had an abstraction in place then I could do things differently from local dev  vs QA/staging/prod. E.g. I wish we had OurMapFunction<TDest>(src); Then inside OurMapFunction<> we can call AutoMapper directly (if prod) or if dev then check if that mapping exists and if not define a new inline map. I remember now - I closed this request because I read about CreateMissingTypeMaps shortly after, which is a way to support lazy loading of maps. It just doesn't fit our need because I don't have a place to 'hook' into it.

Thanks for all you do in providing AutoMapper!
