### ISSUE TITLE
IMapper.ProjectTo

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#2857]
It would certainly make sense for the people using DI. It fits with the move away from static. It would blur a little more the difference between Map and ProjectTo, but I guess we can live with that. We would probably have to keep the existing extensions, we do have a static Mapper class after all. So we would have two ways of doing the same thing. Not great, but maybe it's worth it.

**Comment by jbogard** [comment]
How would that work? `ProjectTo` is an extension method. Or we add an overload to `ProjectTo` to allow `IMapper`?

**Comment by lbargaoanu** [comment]
A new IMapper method called ProjectTo.

**Comment by jbogard** [comment]
How would that work though? What would the method signature look like?

**Comment by lbargaoanu** [comment]
IQueryable<TDestination> ProjectTo<TDestination>(IQueryable source, params Expression<Func<TDestination, object>>[] membersToExpand)

**Comment by lbargaoanu** [comment]
We could also cleanup the new overloads, maybe omit the dictionary based parameters, but the main selling point is playing nice with DI and avoiding static.

**Comment by jbogard** [comment]
So you'd do something like:

```c#
var items = await mapper
    .ProjectTo<OrderDto>(dbContext.Orders.Where(o => o.Status == Status.Approved))
    .ToListAsync();
```

?

**Comment by lbargaoanu** [comment]
Yes.

**Comment by jbogard** [comment]
Makes sense to me. Keeps things consistent.

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/53528967/how-to-use-projectto-with-automapper-8-0-dependency-injection Can we get rid of that other URL, or at least keep them in sync?
