### ISSUE TITLE
[Feature request] Get list of XPaths from mapping

### ISSUE THREAD

**Issue by Nikkelmann** [AutoMapper/AutoMapper#2861]
In our use-case we are using the full model from the api and mapping it to a slim model using AutoMapper.

When calling our api we are defining the properties (fields) that we want to include in the json using the same syntax as defined by https://developers.google.com/drive/api/v3/performance#partial.

It would be awesome to have an automatic approach to generating the XPath-like syntax for the fields. Possibly an extension to AutoMapper?

With the types below the XPaths would be: `"Title,Price,Author/Name"`

### Source/destination types

```csharp
public class Book
{
	public string Title { get; set; }
	public decimal Price { get; set; }
	public Author Author { get; set; }
}
public class Author
{
	public string Name { get; set; }
	public int Age { get; set; }
	public string Country { get; set; }
}
public class SlimBook
{
	public string Title { get; set; }
	public decimal Price { get; set; }
	public string AuthorName { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg => {
    cfg.CreateMap<Book, SlimBook>();
});
var mapper = config.CreateMapper();
```

### Example

```csharp
 // An auto-generated strongly-typed client used to interface with the api.
public class BookClient
{
	public async Task<Book> GetBookAsync(int id, string fields = null)
	{
		var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, $"https://bookapi.tempuri.org/V1/Books/{id}?fields={fields}");
		...
	}
}
var bookClient = new BookClient();
var fields = string.Join(",", mapper.GetMappingAsXPaths<Book, SlimBook>()); // Returns "Title,Price,Author/Name"
var book = await bookClient.GetBookAsync(1, fields);
var slimBook = mapper.Map<SlimBook>(book);
```

**Comment by lbargaoanu** [comment]
You can dig into TypeMap/PropertyMap/TypeDetails etc and see what you can find. But that really is not an API, so you would be using it at your own risk.

**Comment by Nikkelmann** [comment]
I'm not that familiar with AutoMapper yet, but searching for TypeMap revealed the http://docs.automapper.org/en/latest/Queryable-Extensions.html, which I guess is pretty close to what I need.

Maybe the underlying expression-tree could be used to output the XPaths?

I also updated my example to better illustrate my idea for a possible extension to the mapper instance.

**Comment by lbargaoanu** [comment]
I don't think that's the right direction. I'd rather say you should start with the building blocks we use to build the expression tree (what I mentioned above) and build your paths from that.

**Comment by lbargaoanu** [comment]
I'll close this as it will not be a part of this repository, but feel free to ask any questions you might have when trying to implement this.
