### ISSUE TITLE
ProjectTo Expression Mapping error with one to many relationship

### ISSUE THREAD

**Issue by aesuther** [AutoMapper/AutoMapper#2862]
I am having a issue with using `ProjectTo()` for expression mapping.  
If I `ProjectTo()` after a where clause which checks for null everything works correctly. However if I `ProjectTo()` before my where clause I get the following exception: `System.NotSupportedException: 'Cannot compare 'member 'Locations' of type 'ConsoleApp1.Program+EmployeeDto''. Only primitive types, enumeration types and entity types are supported.'` This only seems to occur when a have an entity which contains a member that has a one to many relationship with another entity. 

### Source/destination types

```csharp
    public class LabourDto
    {
        public int Id { get; set; }
        public EmployeeDto Employee { get; set; }
    }

    public class EmployeeDto
    {
        public int Id { get; set; }
        public LabourDto Labour { get; set; }
        public List<LocationDto> Locations { get; set; }
    }

    public class LocationDto
    {
        public int Id { get; set; }
    }

    public class Labour
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public virtual Employee Employee { get; set; }
    }

    public class Employee
    {
        [Key, ForeignKey("Labour")]
        public int Id { get; set; }
        [Required]
        public virtual Labour Labour { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }

    public class Location
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }

```

### Version: 7.0.0
Automapper: 7.0.0
Entity Framework: 6.1.3

### Expected behavior

The expression to be mapped successfully.

### Actual behavior

`System.NotSupportedException: 'Cannot compare 'member 'Locations' of type 'ConsoleApp1.Program+EmployeeDto''. Only primitive types, enumeration types and entity types are supported.'` 

### Steps to reproduce
[gist](https://gist.github.com/aesuther/edcc6b4a676d243c1be6c2c5ba5cd347)

**Comment by lbargaoanu** [comment]
ProjectTo is not designed for this. You should look into expression mapping. That was moved to another repo.

**Comment by lbargaoanu** [comment]
See also [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/Extensions.cs#L22), but to be honest, other than it's smth about OData, I don't know much about it.
