### ISSUE TITLE
Mapping from Data Tables to Object

### ISSUE THREAD

**Issue by citybear01** [AutoMapper/AutoMapper#2863]
I'm a newbie here and have a few questions.
I am trying to retrofit a conventional ASP .NET page and server access to using Entity Framework.  This ASP .NET page uses a lot of data tables to bind to controls on the page, manipulate data, and to perform CRUD actions.  How would I do that with AutoMapper?

**Comment by lbargaoanu** [comment]
AM doesn't have any specific logic for DataTable. But it does support [lists](http://docs.automapper.org/en/latest/Lists-and-arrays.html) and dictionaries. Other than that, I think this is better suited for StackOverflow.
