### ISSUE TITLE
Mapper.AssertConfigurationIsValid() doesn't throw exception about enum not matching

### ISSUE THREAD

**Issue by stevenxi** [AutoMapper/AutoMapper#2864]
### Source/destination types

```csharp
Source 
enum SourceEnum
{
 a,
 b
}

Destination
enum DestinationEnum
{
 b
}

```

### Mapping configuration

```csharp

       
        public class MappingProfile : Profile
        {
            public MappingProfile()
            {
                CreateMap<SourceEnum, DestinationEnum>();
            }
        }

            Mapper.Initialize(cfg =>
            {
                cfg.AddProfile(new MappingProfile());
            });




```

### Version: x.y.z
7.0.1

### Expected behavior

Mapper.AssertConfigurationIsValid(); //Should throw exception

### Actual behavior

Mapper.AssertConfigurationIsValid(); //No exception

### Steps to reproduce

```csharp

        enum SourceEnum
        {
            a,
            b
        }

        enum DestinationEnum
        {
            b
        }

        public class MappingProfile : Profile
        {
            public MappingProfile()
            {
                CreateMap<SourceEnum, DestinationEnum>();
            }
        }

            Mapper.Initialize(cfg =>
            {
                cfg.AddProfile(new MappingProfile());
            });

            Mapper.AssertConfigurationIsValid();


```

**Comment by lbargaoanu** [comment]
A PR is welcome. You can also implement the validation in [your own code](http://docs.automapper.org/en/latest/Configuration-validation.html#custom-validations).

**Comment by lbargaoanu** [comment]
The existing behavior is [by design](https://github.com/AutoMapper/AutoMapper/blob/949258c397fbc8fa59611c0a83b99c7fee23ded2/src/AutoMapper/Mappers/EnumToEnumMapper.cs#L17) and changing it would break existing code. So your own custom validation seems the way to go here.

**Comment by lbargaoanu** [comment]
Look at the code, it considers the "error" cases and it handles them accordingly. If you want smth different you have what you need to make it happen. As for the why, clearly the code is trying to avoid errors, it tries to make the mapping work as best as it can.

**Comment by stevenxi** [comment]
@lbargaoanu Clearly the Mapper.AssertConfigurationIsValid(); should be mostly used for unit testing.
I do agree the code trying to avoid errors during runtime, but it's not a good idea to hide errors during unit testing.

**Comment by lbargaoanu** [comment]
I don't see it that way. But if you can convince @jbogard, I'm sure he'll accept a PR.

**Comment by stevenxi** [comment]
@lbargaoanu In fact he's the one suggest to open this new issue. in #1609 .

**Comment by jbogard** [comment]
Yeah, you'll need a custom validator for this case. The default behavior is to *try* to match values up. It does not try to do strict matching enforcement, since we rely on .NET to convert enum values.

In your example, you can do this:

```c#
var source = SourceEnum.a;
int srcInt = (int)source;
var dest = (DestinationEnum)srcInt;
Console.WriteLine(dest);
```

This outputs `b`. We try to make a best guess on how to map, but because .NET is so forgiving with enums, we fall back onto .NET's behavior rather than trying to impose our own restrictions.

You can replace the enum mapper too, if you want to strictly enforce the behavior you're looking for.

**Comment by stevenxi** [comment]
@jbogard Yes, I'm currently using a custom validator, well, actually it's validated out of AutoMapper's validation.

The problem is "Mapper.AssertConfigurationIsValid()" is somehow misleading of anyone else thought it would validate enum mappings too, just like #1609.  
What I believe is AutoMapper should do what you suggested "try to make a best guess on how to map" and avoid throwing exception during production usage.  But there should be an way to validate it during the unit testing.  Although you're right about it can be done by a custom validator, but I'm sure I'm not the only one expect it to validate the enum mappings.

**Comment by lbargaoanu** [comment]
I think people relying on the existing behavior should have priority here.

**Comment by stevenxi** [comment]
@lbargaoanu that sounds...

**Comment by jbogard** [comment]
The purpose is to check that members are mapped and that types have a map. Not that the map may break during runtime.

**Comment by stevenxi** [comment]
@jbogard Exactly! 
Let's say the use case is there's an internal enum that used all around in the application itself. 
And there's another enum that used as part of interface/contract that expose to external system, etc restful API.

To ensure each internal one updates, the external will update to match, this should be guarded by the check.

Funny enough, the fields in enum does count as "field member" in .net. In this case, "The purpose is to check that members are mapped and that types have a map" does require to check the fields are matching...

**Comment by jbogard** [comment]
No, not quite, I think you misunderstood "members". When we say "members" we mean "destination members on a type in which AutoMapper will execute an individual map for". These are typically members with MemberInfo, but not always (like constructors).

Another way to think of it - a value that can be set. You cannot set an individual field of an enum. You can set something else that has a value of an enum, however.

So AutoMapper checks "do all members have a mapping plan" and then "for each member, do those types have a plan" but never "do the potential values have a plan".

If you need a check beyond "members are mapped and types have a plan" then that is what custom validation is for.
