### ISSUE TITLE
Not mapping JObject's Int Field

### ISSUE THREAD

**Issue by p0onage** [AutoMapper/AutoMapper#2865]
### Code 

```
        [Test]
        public void Map_Call_Id_Issue()
        {
            JToken json = JObject.Parse(
                " {\"Url\": \"www.fakeUrl.com\",\"CallId\": 12}");

            var poco = mapper.Map<CallData>(json);
            Console.WriteLine(json);
            Console.WriteLine(poco.Url + " " + poco.CallId);
        }
```

```

   public class CallData
    {
        public int CallId { get; set; }
        public string Url { get; set; }
    }
```
### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Version: x.y.z
Automapper V7.0.1
.Net-Core-2.1

### Expected behavior

{ "Url": "www.fakeUrl.com", "CallId": 12 }

www.fakeUrl.com 12

### Actual behavior

{ "Url": "www.fakeUrl.com", "CallId": 12 }

www.fakeUrl.com 0

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by p0onage** [comment]
I believed this to be a bug with Automapper as it should be able to map the integer value without any additional configuration?

**Comment by lbargaoanu** [comment]
I'm sure if you change the test to use some random dynamic object it will work. It's smth Newtonsoft.Json does differently and similar questions were answered before here and on SO.

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/47473087/using-automapper-to-map-from-dynamic-jobject-to-arbitrary-types-without-creating/47497389#47497389

**Comment by p0onage** [comment]
Thanks @lbargaoanu, I get the InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32' exception using that approach. I have a workaround I've used just isn't ideal. 

https://stackoverflow.com/questions/53223797/automapper-not-mapping-jobject-to-poco-not-mapping-int

**Comment by stevenxi** [comment]
@p0onage  I think how this place work is "when it's not working, it must be you're doing it wrong " ;)
