### ISSUE TITLE
Read only properties

### ISSUE THREAD

**Issue by rheone** [AutoMapper/AutoMapper#2871]
Automapper silently fails to set property via `ValueResolver` on a destination Interface, when said property on the interface is readonly, but its AutoMapper known concrete implementation’s property is writable.

See the reproduction example within the following [gist](https://gist.github.com/rheone/c0f51753881bdf43b82fc7309576d5fb) for entire source file with xUnit test.

### Source/destination types

```csharp
public class Source
{
    public int Id { get; set; }
}

public interface IDestination
{
    string ValueFromValueResolver { get; }
}

public class Destination : IDestination
{
    public string ValueFromValueResolver { get; set; }
}
```

### Mapping configuration

```csharp
new MapperConfiguration(_ =>
 {
     _.CreateMap<Source, IDestination>()
      .ForMember(d => d.ValueFromValueResolver, o => o.ResolveUsing<DestinationValueResolver>());

     _.CreateMap<Source, IDestination>()
      .As<Destination>();
 }).CreateMapper();
```
### Value Resolver

```csharp
public class DestinationValueResolver : IValueResolver<Source, IDestination, string>
{
    public string Resolve(Source source,
                          IDestination destination,
                          string destMember,
                          ResolutionContext context)
    {
        return $"Value from source \"{source.Id}\".";
    }
}
```

### Expected behavior

Automapper should either 
 - throw an exception / fail non-silently
 - recognize, as it is aware it is treating `IDestination` as a `Destination`, and set the value of `Destination.ValueFromValueResolver`

### Actual behavior

The resulting value returned from the mad does not have its `ValueFromValueResolver` value set, and AutoMapper raises no issues

### Steps to reproduce

```csharp
mapper.Map<IDestination>(source)
```

See [gist](https://gist.github.com/rheone/c0f51753881bdf43b82fc7309576d5fb)

**Comment by lbargaoanu** [comment]
Set the Resolver on the concrete map. If you want that validation to happen, you can write your own custom validator.

**Comment by rheone** [comment]
Setting the ValueResolver on the concrete mapping is my present fix, but it seems as if it should be possible to do it on the interface mapping, especially given multiple possible concrete mappings.

**Comment by lbargaoanu** [comment]
I disagree, on the interface it's read-only, so it's not mapped. If you're interested in doing a PR on the validation, we can discuss it, otherwise a custom validator would achieve the same thing.

**Comment by rheone** [comment]
Was this closed as it is not seen as an issue, or that there is a lack of resources / priority to work on it?

Eg. If I do get the time to do a deep dive and investigate a "fix" for this is there possibility of a PR being considered, or is this functionality "by design", and need not be fixed?

**Comment by lbargaoanu** [comment]
A PR will be considered, as things could be better. But some read-only properties can be mapped. Collections come to mind. It would also be a breaking change. So proceed with care :)
