### ISSUE TITLE
Unflattening with constructor parameters doesn't work

### ISSUE THREAD

**Issue by piteerus** [AutoMapper/AutoMapper#2872]
Unflattening with constructor parameters doesn't work.
Getting error message:
automapertest.models.LookupValue needs to have a constructor with 0 args or only optional args.
Parameter name: type

### Source/destination types

```csharp
// Request
public class Request
{
        public Request(int id)
        {
            Id = id;
        }
        public int Id { get; }
        public LookupValue ReportingUnit { get; set; }
}

// LookupValue
public class LookupValue
{
        public LookupValue(string value)
        {
            Value = value;
        }
        public string Value { get; }
    }
}

// RequestDTO
public class RequestDto
{
        public int Id { get; set; }
        public string ReportingUnitValue { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Request, RequestDto>().ReverseMap();
```

### Expected behavior

Request object created successfully with filled property ReportingUnit.

### Actual behavior

Error message.

### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg => cfg.AddProfile<AutomapperProfile>());
config.AssertConfigurationIsValid();
var mapper = config.CreateMapper();

var model = new Request(1)
{
       ReportingUnit = new LookupValue("test")
};
var dto = mapper.Map<RequestDto>(model);
var model2 = mapper.Map<Request>(dto);
```
Flattening/Unflattening is not consistent in behaviour. There is no issue when flattening to DTO object. The problem occures when I try to unflatten DTO object to my domain object. Automapper cannot create LookupValue instance with provided flattened properties.

Are there other possibilites other than instructing Automapper how to create LookupValue like:
```csharp
CreateMap<Request, RequestDto>()
    .ReverseMap()
    .ForMember(x => x.ReportingUnit, opt => opt.MapFrom(s => new LookupValue(s.ReportingUnitValue)));
```
I don't whant to do that (above example) since my DTO object will contain a lot of LookupValue properties and I have to specify manual mapping for every property.

I need some generic solution that will create destination object's properties of type LookupValue from naming convention in DTO: <target_property>Value

Tried to use custom ValueResolver but the problem with it is that I have to instruct Automapper which properties will be used to construct LookupValue:
```csharp
 public class LookupValueResolver : IValueResolver<Request, RequestDto, LookupValue>
    {
        public LookupValue Resolve(Request source, RequestDto destination, LookupValue destMember, ResolutionContext context)
        {
            return new LookupValue(destination.ReportingUnitValue);
        }
    }
```
It's not generic. It's not reusable. I have to write ValueResolver for each property ;(

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Custom-type-converters.html

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Construction.html
