### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MadeoIT** [AutoMapper/AutoMapper#2875]
### Source/destination types
Source: 

```
 public class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        //Other props
    }

```

Destination:
```
public class CustomerGetAllViewModel
    {
        public IEnumerable<Customer> Customers { get; set; }
    }
```

### Mapping configuration

```
config.CreateMap<List<Customer>, CustomerGetAllViewModel>();
```

### Version: x.y.z
7.0.1

### Expected behavior
With manual mapping works fine.
Others Auto mappings are working fine

### Actual behavior

Should return the expected type

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
