### ISSUE TITLE
UseDestinationValue is not inherited

### ISSUE THREAD

**Issue by antoinebj** [AutoMapper/AutoMapper#2880]
I'm creating this issue as a follow-up to my participation in a [similar named one](https://github.com/AutoMapper/AutoMapper/issues/2194#issuecomment-439707662).

I volunteer to make a PR that will add inheritance of `UseDestinationValue` and introduce a `inherit the setting and DontUseDestinationValue()` method.

### Source/destination types

```csharp
public class SubObject
{
    public string Value { get; set; }
}

public class SourceBase
{
    public SubObject SubObject { get; } = new SubObject();
}

public class Source : SourceBase
{
}

public class DestinationBase
{
    public SubObject InnerObject { get; } = new SubObject();
}

public class Destination : DestinationBase
{
}
```

### Mapping configuration

```csharp
new MapperConfiguration(cfg =>
{
    cfg.CreateMap<SubObject, SubObject>();

    cfg.CreateMap<SourceBase, DestinationBase>()
        .ForMember(dest => dest.InnerObject, opt =>
        {
            opt.MapFrom(src => src.SubObject);
            opt.UseDestinationValue();
        });

    cfg.CreateMap<Source, Destination>()
        .IncludeBase<SourceBase, DestinationBase>();
});
```

### Expected behavior

The `Value` property in `Destination.InnerObject` should be mapped correctly.

### Actual behavior

It remains null.

### Steps to reproduce

```csharp
var source = new Source { SubObject = { Value = "Success" } };
var destination = mapper.Map<Source, Destination>(source);
```

**Comment by lbargaoanu** [comment]
Yes, it's a breaking change. I think it's a minor one and we don't need the version bump. cc @jbogard

**Comment by jbogard** [comment]
Yeah it’s a minor behavior change. No need to bump the major, but I’d bump
the minor.

**Comment by lbargaoanu** [comment]
It think we can go further here and set UseDestinationValue every time someone adds a resolver for a read-only property.

**Comment by antoinebj** [comment]
BTW I only have time during the week-ends, so I'll take care of it in a couple of days or so. I'll take into account the suggestions you make in the meantime.

**Comment by lbargaoanu** [comment]
We'll take the PR whenever it's ready.
