### ISSUE TITLE
Feature request: unify context injection

### ISSUE THREAD

**Issue by vhe1** [AutoMapper/AutoMapper#2881]
Hi!
Currently there are two different ways to provide context, depending on whether I use the QueryableExtensions or not.

With the Queryable extension, the mapping looks like
```c#
public class InterestingPointMapperProfile: Profile
{
    public InterestingPointMapperProfile()
    {
        string lang = "en-US";
        CreateMap<Point, InterestingPoint>()
            .ForMember(dest => dest.WhatsThere, opt => opt.MapFrom(src => src.Description+"/"+lang))
            ;
    }
}
```
and I use it like
```c#
await interestingPointMapper.ProjectTo<InterestingPoint>(ctx.Points, new {lang = "de-DE"})
```

In the "normal" mode, the mapping looks like
```c#
.ForMember(dest => dest.WhatsThere, opt => opt.MapFrom((src,tgt,whatever,ctx) => src.Description+"/"+ctx.Items["lang"]))
```

and I use it like
```c#
interestingPointMapper.Map<InterestingPoint>(pe, opts=>opts.Items["lang"]="de-DE");
```

It would be great if there were just one mechanism, so that I can reuse the mappings regardless of inside or outside of a database query.

**Comment by lbargaoanu** [comment]
That makes perfect sense. But we're not sure we have a clean solution here. See #2781. But if you want to give it a shot, a PR is most welcome.
