### ISSUE TITLE
Bug after switching to V8

### ISSUE THREAD

**Issue by jogibear9988** [AutoMapper/AutoMapper#2882]
Following Code wored in Automapper 7:

       IMapper mapper;
            mappers.TryGetValue(key, out mapper);
            if (mapper == null)
            {
                var config = new MapperConfiguration(cfg => {
                    cfg.CreateMap(source.GetType(), destination.GetType());
                    cfg.AllowNullCollections = true;
                    cfg.AllowNullDestinationValues = true;
                });
                mapper = config.CreateMapper();
                mappers.Add(key, mapper);
            }

now I get the following Exception:

![automapper](https://user-images.githubusercontent.com/364896/48679628-f0a68e80-eb92-11e8-970f-099a874f1b04.png)

stacktrace:

![automapper2](https://user-images.githubusercontent.com/364896/48679630-f7cd9c80-eb92-11e8-85be-08793db1ec2c.png)

calling code:

![automapper3](https://user-images.githubusercontent.com/364896/48679631-fdc37d80-eb92-11e8-8604-8166645bdf03.png)

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by jogibear9988** [comment]
I've created a Test. It's a issue using Automapper with Castle Dyanmic Proxy  Classes
