### ISSUE TITLE
AutoMapper 8.0.0 + AutoMapper.Data 2.0.0 = Not Implemented Exception

### ISSUE THREAD

**Issue by jose-machado** [AutoMapper/AutoMapper#2883]
### Mapping configuration

Mapper.Initialize(cfg => {
                cfg.AddDataReaderMapping();
}

### Expected behavior

No issue before with AutoMapper v7.0.1 and AutoMapper.Data v2.0.0.

### Actual behavior

System.TypeLoadException: Method 'MapExpression' in type 'AutoMapper.Data.Mappers.DataReaderMapper' from assembly 'AutoMapper.Data, Version=2.0.0.0, Culture=neutral, PubliccKeyToken=null' does not have an implementation.

### Steps to reproduce
Just setup AutoMapper v8.0.0 and AutoMapper.Data v2.0.0 and initialize it.

**Comment by lbargaoanu** [comment]
This belongs in the AutoMapper.Data repo. A PR is welcome.
