### ISSUE TITLE
InvalidOperationException: Code supposed to be unreachable occur when mapping between expressions

### ISSUE THREAD

**Issue by shaybenh7** [AutoMapper/AutoMapper#2885]
Hi, 
Im trying to use your expression nugget. when mapping an expression with type Expression<Func<T,bool>> to Expression<Func<V,bool>> Im getting an InvalidOperationException: Code supposed to be unreachable when executing the mapped expression. I have the mapping between T and V do you maybe have any idea what could cause it or what am I missing? 
Thanks

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/2767#issuecomment-414060736).
