### ISSUE TITLE
How to use "ConstructUsing" with LambdaExpression after update to 8.0.0? (or what instead)

### ISSUE THREAD

**Issue by whizzzkey** [AutoMapper/AutoMapper#2886]
Got an Issue after update to new version v 8.0.0. from 7.0.1, this simple lines of code in my project can't be compiled due error : 
**"a lambda expression with a statement body cannot be converted to an expression tree"**

```
 cfg.CreateMap<DistrictDbDto, District>().ConstructUsing(x =>
                {               
                    var distr = District.NewInstance(x.Id, x.Name);
                    var distrDesc = DistrictDesc.NewInstance(x.ShortName, x.ShortEngName);
                    distr.DistrictDesc = distrDesc;
                    return distr;
                })
```
What should I use instead "ConstructUsing" in v8?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html

**Comment by sunnydayforyou** [comment]
Hi, could anyone write there how solved this problem? Thank you.

**Comment by jbogard** [comment]
Read the link above.
