### ISSUE TITLE
Type.GetType in Profile always return null

### ISSUE THREAD

**Issue by ranouf** [AutoMapper/AutoMapper#2890]
"AutoMapper" Version="7.0.1"

Hi,

issue: Type.GetType always return null.

Here is my profile:

```
        public NotificationProfile()
        {
            CreateMap<Notification, NotificationDto>()
                .ForMember(
                    dest => dest.Discriminator,
                    opts => opts.MapFrom(src => Type.GetType(src.EntityType).Name)
                );
        }
```

In debug, In immediate windows, It works when I do:

`Type.GetType("MyProject.Api.Controllers.Samples.Dtos.SampleDetailsDto").Name =>SampleDetailsDto`

But the property value of Discriminator is always Null here:

` Mapper.Map<GroupedResult<Notification>, GroupedResult<NotificationDto, Guid?>>(result) `

Is there a way to use "_Type.GetType_" in Profile binding?

Thanks

**Comment by ranouf** [comment]
I tried to add a new property to Notification:

       ```
 private string _discriminator;
        [NotMapped]
        public object Discriminator
        {
            get
            {
                if (!string.IsNullOrEmpty(_discriminator))
                {
                    return _discriminator;
                }
                _discriminator = Type.GetType(EntityType).Name;
                return _discriminator;
            }
        }
```

But Type.GetType(EntityType).Name faile.

Error message from Automapper is:

Error mapping types.

Mapping types:
Notification -> NotificationDto
XX.Core.Notifications.Entities.Notification -> XX.Api.Controllers.Notifications.Dtos.NotificationDto

Type Map configuration:
Notification -> NotificationDto
XX.Core.Notifications.Entities.Notification -> XX.Api.Controllers.Notifications.Dtos.NotificationDto

Property:
Discriminator

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
