### ISSUE TITLE
Ignore() doesn't work for nested classes

### ISSUE THREAD

**Issue by StillLearnin** [AutoMapper/AutoMapper#2896]
### Full repro code

Create a new console app and use [this code](https://gist.github.com/StillLearnin/754108825f82647e8f2e85bb073e34bf) in program.cs.

### Source/destination types

```csharp
    class PersonDTO
    {
        public string Name { get; set; }
    }

    class Person
    {
        public string Name { get; set; }
        public List<Person> Siblings { get; set; }
    }

    class FamilyDTO
    {
        public PersonDTO Father { get; set; }
        public PersonDTO Mother { get; set; }
        public List<PersonDTO> Children { get; set; }
    }

    class Family
    {
        public Person Father { get; set; }
        public Person Mother { get; set; }
        public List<Person> Children { get; set; }
    }
```

### Mapping configuration

```csharp
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Person, PersonDTO>()
                    .ReverseMap()
                    .ForMember(props => props.Siblings, opts => opts.Ignore());

                cfg.CreateMap<Family, FamilyDTO>()
                    .ReverseMap();
            });
```

### Expected behavior

In mapping a `FamilyDTO` to a `Family` when `Family.Children[0].Siblings` is already populated, `Siblings` should not be cleared because there is no source property for `Siblings` in `PersonDTO` and because ~`UseDestinationValue`~ `Ignore` has been called for the `Siblings` property.

### Actual behavior

`Siblings` list is cleared even though ~`UseDestinationValue`~ `Ignore` has been called.

**Comment by lbargaoanu** [comment]
When mapping to an existing collection, the destination collection is cleared first. If this is not what you want, take a look at AutoMapper.Collection. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).

**Comment by StillLearnin** [comment]
Clearing the destination collection first makes sense as a default operation but not when `UseDestinationValue` is  set as it is in this case.

Furthermore, with the maps created as shown above, the destination collection isn't cleared when I map a `PersonDTO` to a `Person` but it IS cleared when I map a `FamilyDTO` to a `Family`.

To me, this operation seems very inconsistent. Maybe that is just because I'm not understanding something?

**Comment by lbargaoanu** [comment]
If they are mapped, they are cleared. The execution plan shows exactly what happens.

**Comment by jbogard** [comment]
Clearing the collection is the most consistent option for us. Any other
option would be different than default behavior, so that’s why you should
look at the packages that have additional logic.

Remember, out of the box, we’re creating new objects or overwriting your
values. Clearing a collection is consistent with overriding values with the
source.

**Comment by StillLearnin** [comment]
@jbogard yes, clearing is consistent, but is it still consistent when `UseDestinationValue` has been called?

**Comment by StillLearnin** [comment]
@lbargaoanu yes, the execution plan does show exactly what happens. I have looked at it. I'm suggesting that the execution plan is incorrect when `UseDestinationValue` has been called.

**Comment by lbargaoanu** [comment]
That's not the intent. UseDestinationValue has no special effect on collections.

**Comment by jbogard** [comment]
Exactly. That configuration only means “don’t call the setter”

**Comment by StillLearnin** [comment]
Ah! It's `UseDestinationValue` not `UseDestinationCollection` 😃

**Comment by StillLearnin** [comment]
Ok, so there's no built in `UseDestinationCollection` functionality?

**Comment by jbogard** [comment]
No because that behavior is much more complicated. Clear? Don’t clear?
Merge? Only add new ones? For existing ones, map? This is why the other
package exists - it’s much more complicated and depends on your ORM.

**Comment by StillLearnin** [comment]
Um, seems to me that `UseDestinationCollection` would simply mean don't touch the destination property, just leave it as it is.

**Comment by jbogard** [comment]
That’s what Ignore does.

**Comment by StillLearnin** [comment]
I thought you might say that. Then the issue title should be changed to focus on `Ignore` instead because it also doesn't work. I had tried `Ignore` also.  I just tried it again and it doesn't ignore the `Siblings` property even though I tell it to.

**Comment by lbargaoanu** [comment]
Look at that plan again. AM doesn't touch Siblings. Because Siblings is not mapped. There is no need to Ignore it.

**Comment by lbargaoanu** [comment]
You can do that yourself. Take the execution plan, copy paste it in a console app and in a few minutes you should be able to debug it and find out.

**Comment by StillLearnin** [comment]
Is the answer that AutoMapper can't do a collection within a collection because it has no way of accurately determining object equality?

**Comment by lbargaoanu** [comment]
That's true about any collection. Your particular case is just a consequence. I didn't debug it, but if the parent object is recreated and the child collection is not mapped, it will have the value set in the constructor.
