### ISSUE TITLE
CreateMissingTypeMaps works only globally

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#2897]
I think we should remove it from Profile. We can make it throw initially.

**Comment by TylerCarlson1** [comment]
The only use case I can see for keeping this is if you want a certain profile to create type maps, but it's specific rules are to be followed.  Like a profile specifically for Convention maps, but ForAllPropertyMap is used and you have prefixes and postfixes that will be handled by some kind of convention.

But this is probably a very obscure case that doesn't happen without deep knowledge of the system, in which case using Conventions are a better alternative.

**Comment by lbargaoanu** [comment]
@jbogard Thoughts?

**Comment by jbogard** [comment]
I think the only reason I put it on the Profile is so that scanning could pick up the configuration. But that would be weird for a Profile to stomp on global config. I'm fine with moving it - are there any others like this?

**Comment by lbargaoanu** [comment]
Good question :)
