### ISSUE TITLE
Documentation error (Passing in key-value to Mapper)

### ISSUE THREAD

**Issue by timmi4sa** [AutoMapper/AutoMapper#2899]
### Documentation error

Section: “Custom Value Resolvers”
Subsection: “Passing in key-value to Mapper”

```csharp
cfg.CreateMap<Source, Dest>()
    .ForMember(dest => dest.Foo, opt => opt.MapFrom((src, dest, destMember, context) => context.Items["Foo"]));
```

## Expected code 
(making use of the opt.ResolveUsing method instead of opt.MapFrom)

```csharp
cfg.CreateMap<Source, Dest>()
    .ForMember(dest => dest.Foo, opt => opt.ResolveUsing((src, dest, destMember, context) => context.Items["Foo"]));
```

Please update the documentation. Thanks.

**Comment by lbargaoanu** [comment]
Check [the upgrade guide](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html).
