### ISSUE TITLE
Question > Scoping Profiles

### ISSUE THREAD

**Issue by ckapatch** [AutoMapper/AutoMapper#2905]
Hello everyone,

We're using two of Jimmy's great tools: AutoMapper and Mediatr.

We've adopted a structure in which a command/query is completely self-contained in a parent class:
```csharp
public class GetSomething
{
   public class Query : IRequest<Response> {}
   public class Handler: IRequestHandler<Query, Response> {}
   public class MappingProfile: Profile {}
   public class Response {}
}
```

Inside the Handler, we inject IMapper which in our current implementation assumes that the root has registered the profiles. We want to ensure that only the Profile inside of the GetSomething is being used and not being done somewhere else. Because we use the assembly scanning feature we aren't certain that the profile in this class is the only one that is being used to construct the mapping profile. 

Can we scope the profile here? We were thinking something along the lines of:
```csharp
public class Handler: IRequestHandler<Query, Response>
{
    private IMapper _mapper = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<Source, Destination>();
    }).CreateMapper(); 
}
```

But we're unsure if this would cause performance issues etc...

Any guidance or suggestions would be fantastic. Thank you.

**Comment by lbargaoanu** [comment]
You can do that, use MapperConfiguration as scope, but then you need to cache those per appdomain/process (not per request as in your code). But maybe what you want is that separation in your object model and then the AM configuration is not relevant anymore.

**Comment by ckapatch** [comment]
Thank you for the quick reply! Yeah I was hoping there would be a best of both worlds somehow here, using the cached map but scoped to the particular mapper. I know this is a bit of an unfair question but are we looking at massive performance implications in doing a per request creation? Did you have any internal stats on cached vs non-cached. Again thank you for your incredible work.

**Comment by ckapatch** [comment]
Thank you all for your insights.
