### ISSUE TITLE
What is the (default) value for a destination property that doesn't exist in the source object?

### ISSUE THREAD

**Issue by jhenderson2099** [AutoMapper/AutoMapper#2906]
### Source/destination types

```csharp
    public class Source
    {
        public double? Balance { get; set; }

    }


    public class Destination
    {
        public double Balance { get; set; }   // Not nullable!
    }
```

### Mapping configuration
```csharp
CreateMap<Source, Destination>(); // Implicit property-to-property mapping
```

or

```csharp
// Explicit property-to-property mapping
CreateMap<Source, Destination>()
    .ForMember(dest => dest.Balance, opt => opt.MapFrom(src => src.Balance))
```

### Version: x.y.z
7.0.0

### Expected behavior
Unknown?

- If Source.Balance == null, then what will be the value of Destination.Balance?
- Does AutoMapper convert the null to zero, or does the instance of Destination simply get initialized to 0 and no mapping occurs?
- What would happen in this scenario if the two property names did not match and there was no explicit mapping?  What would be the value of Destination.Balance?

I think it works like this: if you have a nullable source property and the value of the source property is `null`and a non-nullable destination property (based upon my testing):
- If you have a mapping (explicit or implicit), then you get the default value for that type (e.g., `default(int)`)
- If you don't supply a mapping, and there is no implicit automapping that will work, and you **don't** supply a value in the Destination class's constructor, then you get the default value for that type
- If you don't supply a mapping, and there is no implicit automapping that will work, and you **do** supply a value in the Destination class's constructor, then you get the value that you specified in the constructor

### Actual behavior

Should be the default value of that data type.  Refer to thread in [https://groups.google.com/forum/#!topic/automapper-users/UX-liQGboMY](https://groups.google.com/forum/#!topic/automapper-users/UX-liQGboMY)

**The request is that this behavior be documented.**  (Basically, "This is how it works if you works if the mapping is/isn't explicit/implicit and what you get as a default)

### Steps to reproduce

N/A

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). I don't think we really we want to document things at this level of detail.
