### ISSUE TITLE
update to 8.0 error about ResolveUsing method and lambda expressions

### ISSUE THREAD

**Issue by hjkl950217** [AutoMapper/AutoMapper#2907]
### Mapping configuration

```csharp
  var config = new AutoMapper.MapperConfiguration(cfg =>
           {
               cfg.AddProfile(new AutoMapProFile());

               cfg.ShouldMapProperty = p =>
                  p.GetMethod != null
                  && ( p.GetMethod.IsPublic || p.GetMethod.IsAssembly );


               cfg.CreateMissingTypeMaps = true;

           });

            config.AssertConfigurationIsValid();

            var mapper = config.CreateMapper();
```

### Expected behavior

Easy migration from 7.0.1 to 8.0.0

### Actual behavior

An error occurred: 
``` csharp
    // in  Profile class file

//class:   AutoMapProFile : Profile

//code:
       base.CreateMap<SellerBasicInfo, Seller_BasicInfoOut>()
                .ForMember(
                   dest => dest.SellerID
                   , opt => opt.MapFrom(src => src?.SellerID?.Trim())  // error
                   )

```

### Why did you use one before?
In previous versions, for destination member, handling of null pointer exceptions use capture `Exception`,else use `resolveUsing` custom processing the such problems.For better performance

but for ` MapFrom<TValueResolver, TSourceMember>(Expression<Func<TSource, TSourceMember>> sourceMember)`, Can't use the word "?.",   Because it can't be converted to an `LambdaExpression`.

**what should I do?**

I have already viewed [8.0 Upgrade Guide](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html).Did not find a **suitable solution**

The main problem is convert '?.' code to Expression

**Comment by lbargaoanu** [comment]
Existing ResolveUsing usages

The change from Func to Expression may break some existing usages. Namely:

    ResolveUsing using lambda statements, method groups, or delegates
    Dual configuration of ResolveUsing and MapFrom

For the first case, you may either:

    Convert to a lambda expression
    Move to the Func-based overloads

The Func-based overloads accept more parameters, so you may have to add the parameters to your delegates.

**Comment by hjkl950217** [comment]
@lbargaoanu  plase view me description！！

Or give a sample code?

**Comment by hjkl950217** [comment]
```
opt => opt.MapFrom((src,d) => src?.SellerID?.Trim())
```
This seems to only solve the problem, not the best usage.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. You just need to use a Func based overload, as the guide says.

**Comment by hjkl950217** [comment]
Is the above code the correct solution?

**Comment by lbargaoanu** [comment]
Whatever works for you. Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html) to see what will happen at runtime.

**Comment by hjkl950217** [comment]
Even if I look at this plan, I still don't know what is right.

**Comment by hjkl950217** [comment]
use extension method:
```
   public static void MapFrom<TSource, TDestination, TMember, TResult>(
           this IMemberConfigurationExpression<TSource, TDestination, TMember> mapConfig,
           Func<TSource, TResult> mappingFunction)
        {
            mapConfig.MapFrom<TResult>((src, d) => mappingFunction(src));
            // Func<TSource, TDestination, TResult> map = (src, d) => mappingFunction(src);
        }
```
Looking through `BuildExecutionPlan`, it seems that this and the previous logic have not changed.

@lbargaoanu  Thank you for telling me this method.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2409#issuecomment-442572423 You can use any extension method works for you, but only the names changed, the behavior is still there with the right overload.

**Comment by lbargaoanu** [comment]
I guess the right answer here is that you don't need the null checks or an extension method. When you use an expression based MapFrom, we add the null checks for you.

**Comment by hjkl950217** [comment]
OK
