### ISSUE TITLE
Map List to Dictionary

### ISSUE THREAD

**Issue by domdeger** [AutoMapper/AutoMapper#2914]
### Source/destination types

```csharp
    public class ReportCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IList<ReportSection> Sections { get; set; } = new List<ReportSection>();
    }

    public class ReportCategoryDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IDictionary<string, ReportSectionDto> Sections { get; set; } = new Dictionary<string, ReportSectionDto>();
    }
```

### Mapping configuration

```csharp
            CreateMap<ReportSection, KeyValuePair<string, ReportSectionDto>>().ConvertUsing<ReportSectionTypeConverter>();
            
            CreateMap<ReportSection, ReportSectionDto>()
```

### Actual behavior
I want to use the shown setup together with EFCore and ProjectTo like this:
```csharp 
return await this._reportContext.Categories
                                            .ProjectTo<ReportCategoryDto>()
                                            .ToListAsync();
```
Then i get an System.ArgumentException "Argument types do not match" @AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression Line 37. I digged into the code myself and found that the DestinationType is IDictionary<string, ReportSectionDto> and the ExpressionType is IEnumerable<KeyValuePair<string, ReportSectionDto>> which are not compatible indeed. 

If i use Mapper.Map<ReportCategoryDto>(await this._reportContext.Categories
                                            .ToListAsync());
The mapping works correctly. Can you help me?

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
How would you write that without AM, just with a EF LINQ query? Does EF Core really support that, because I'm pretty sure EF6 doesn't.

**Comment by domdeger** [comment]
Thanks for your quick reply! As a LINQ query i'd write it like this. I tested it with my codebase and it is working as expected:
´´´csharp return await this._reportContext.Categories
                                            .Include(x => x.Sections)
                                            .Select
                                            (
                                                x => 
                                                    new ReportCategoryDto
                                                    {
                                                        Id = x.Id, Name = x.Name,
                                                        Sections = new Dictionary<string, ReportSectionDto>
                                                        (
                                                            x.Sections.Select(y => new KeyValuePair<string, ReportSectionDto>(y.Name, new ReportSectionDto { Id = y.Id, Name = y.Name }))
                                                        )
                                                    }
                                            )
                                            .ToListAsync(); ´´´

**Comment by domdeger** [comment]
Ah yes ofc it is using client side evaluation. I wasn't aware that ProjectTo was meant to be used only for cases where a Mapping can be realized via SQL.
So If it is like that i'll just proceed and map it completly client-side as i was just concerned about simplicity.
Thanks again so much! 

Best regards,
Dominik
