### ISSUE TITLE
Custom Value Resolvers and ResolveUsing

### ISSUE THREAD

**Issue by spottedmahn** [AutoMapper/AutoMapper#2916]
I was reviewing this [SO Post](https://stackoverflow.com/a/11555920/185123) that talked about using `ResolveUsing()` and referenced [Custom Value Resolvers](https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers) which redirected me [here (docs.automapper.org)](http://docs.automapper.org/en/stable/Custom-value-resolvers.html).  On the current doc page I **don't** see any references to `ResolveUsing`.

I'm guessing `ResolveUsing()` is no longer a thing and `IValueResolver<TSource, TDestination, TDestMember>` and `IMemberValueResolver<in TSource, in TDestination, in TSourceMember, TDestMember>` replaces it?

### Version: 8

**Comment by lbargaoanu** [comment]
Check [the upgrade guide](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html).

**Comment by spottedmahn** [comment]
Thanks! 👍

Found it: [8.0 Upgrade Guide -> ResolveUsing](http://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html#resolveusing)

>The `ResolveUsing` method consolidated with `MapFrom`
