### ISSUE TITLE
ProjectTo doesn't limit fields in SQL query for basic projections

### ISSUE THREAD

**Issue by statler** [AutoMapper/AutoMapper#2917]
I use ProjectTo extensively in my efcore application. Checking through the SQL generated for the different projections, I have noticed that for simple maps (e.g. the projection is just a subset of the original class) the full member list is queried and the projection performed in memory. Where I have more complex projections the SQL query is correctly limited to just the fields in the DTO. Is this by design? How can I force the simpler projections to just retrieve the fields from the DTO?

e.g.

    CreateMap<Photo, PhotoListDto>();

    _context.Photo.Where(x => x.ProjectId == _userService.Project_ID) .ProjectTo<PhotoListDto>(_mapper.ConfigurationProvider)

    public partial class Photo
    {
        public Photo()
        {
            Cnphoto = new HashSet<Cnphoto>();
            PhotoChecklistItem = new HashSet<PhotoChecklistItem>();
            PhotoIncident = new HashSet<PhotoIncident>();
            PhotoLot = new HashSet<PhotoLot>();
            PhotoNcr = new HashSet<PhotoNcr>();
            PhotoVariation = new HashSet<PhotoVariation>();
        }

        public Guid? UniqueId { get; set; }
        public string Hrid { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int PhotoId { get; set; }
        public int? SiteDiaryId { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
        public DateTime? PhotoDate { get; set; }
        public int? ProjectId { get; set; }
        public string PhotoSource { get; set; }
        public bool? IsPromo { get; set; }
        public int? OptimisticLockField { get; set; }

        public Project Project { get; set; }
        public SiteDiary SiteDiary { get; set; }
        public ICollection<Cnphoto> Cnphoto { get; set; }
        public ICollection<PhotoChecklistItem> PhotoChecklistItem { get; set; }
        public ICollection<PhotoIncident> PhotoIncident { get; set; }
        public ICollection<PhotoLot> PhotoLot { get; set; }
        public ICollection<PhotoNcr> PhotoNcr { get; set; }
        public ICollection<PhotoVariation> PhotoVariation { get; set; }
    }

    public class PhotoListDto
    {
        public int PhotoId { get; set; }
        public int? SiteDiaryId { get; set; }
        public string Description { get; set; }
        public DateTime? PhotoDate { get; set; }
        public string PhotoImage { get; set; }
    }

Generates

    SELECT [p].[PhotoID], [p].[CreatedBy], [p].[CreatedOn], [p].[Description], [p].[HRid], [p].[isPromo], [p].[ModifiedBy], [p].[ModifiedOn], [p].[OptimisticLockField], [p].[PhotoDate], [p].[PhotoPath], [p].[PhotoSource], [p].[ProjectID], [p].[SiteDiaryId], [p].[UniqueID]
    FROM [Photo] AS [p]

Note the columns are all the Photo object columns, not just PhotoDto which was my expected result. The eventual projection is correct, but it is performed in memory, not in the SQL query.

For my more complex projections, it works at the SQL level e.g. this works

    _context.Ncr.Where(x => x.ProjectId == _userService.Project_ID).Include(x => x.ApprovalNcrlink).ProjectTo<NcrListDto>(_mapper.ConfigurationProvider)

     CreateMap<Ncr, NcrListDto>()
                .ForMember(dest => dest.RequestsCount, opt => opt.MapFrom(src => src.ApprovalNcrlink == null || src.ApprovalNcrlink.Count == 0 ? 0 : src.ApprovalNcrlink.Count))
                .ForMember(dest => dest.ApprovalsCount, opt => opt.MapFrom(src => src.ApprovalNcrlink == null || src.ApprovalNcrlink.Count == 0 ? 0 : src.ApprovalNcrlink.Where(x => x.ApprovalStatusTypeId != null && x.ApprovalStatusTypeId <= 2).Count()))
                .ForMember(dest => dest.ApprovalsCount, opt => opt.MapFrom(src => src.ApprovalNcrlink == null || src.ApprovalNcrlink.Count == 0 ? 0 : src.ApprovalNcrlink.Where(x => x.ApprovalStatusTypeId != null && x.ApprovalStatusTypeId == 3).Count()))

    public partial class Ncr
    {
        public Ncr()
        {
            ApprovalCloseOutNcrNavigation = new HashSet<Approval>();
            ApprovalNcrlink = new HashSet<Approval>();
            Fsncr = new HashSet<Fsncr>();
            LotItpdetail = new HashSet<LotItpdetail>();
            LotQuantity = new HashSet<LotQuantity>();
            NcrDocument = new HashSet<NcrDocument>();
            Ncrlot = new HashSet<Ncrlot>();
            PhotoNcr = new HashSet<PhotoNcr>();
            ProgressClaimSnapshot = new HashSet<ProgressClaimSnapshot>();
        }

        public Guid? UniqueId { get; set; }
        public string Hrid { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int NcrId { get; set; }
        public int? ProjectId { get; set; }
        public int? NcrNo { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Disposition { get; set; }
        public string PreventativeAction { get; set; }
        public DateTime? DateRaised { get; set; }
        public int? RaisedById { get; set; }
        public int? ActionType { get; set; }
        public string RelatedParties { get; set; }
        public int? Severity { get; set; }
        public int? ThirdPartyAppReqd { get; set; }
        public string Notes { get; set; }
        public int? ApprovalById { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public string ApprovalDetails { get; set; }
        public int? CloseOutById { get; set; }
        public DateTime? CloseOutDate { get; set; }
        public string CloseOutDetails { get; set; }
        public decimal? NcrCost { get; set; }
        public string RootCause { get; set; }
        public int? OptimisticLockField { get; set; }

        public User ApprovalByUser { get; set; }
        public User CloseOutByUser { get; set; }
        public Project Project { get; set; }
        public User RaisedByUser { get; set; }
        public ICollection<Approval> ApprovalCloseOutNcrNavigation { get; set; }
        public ICollection<Approval> ApprovalNcrlink { get; set; }
        public ICollection<Fsncr> Fsncr { get; set; }
        public ICollection<LotItpdetail> LotItpdetail { get; set; }
        public ICollection<LotQuantity> LotQuantity { get; set; }
        public ICollection<NcrDocument> NcrDocument { get; set; }
        public ICollection<Ncrlot> Ncrlot { get; set; }
        public ICollection<PhotoNcr> PhotoNcr { get; set; }
        public ICollection<ProgressClaimSnapshot> ProgressClaimSnapshot { get; set; }
    }

    public class NcrListDto
    {
        public int NcrId { get; set; }
        public int? NcrNo { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public DateTime? DateRaised { get; set; }
        public int? RaisedById { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public DateTime? CloseOutDate { get; set; }
        
        public int RequestsCount { get; set; }
        public int ApprovalsCount { get; set; }
        public int RejectionsCount { get; set; }
        public bool IsApproved
        {
            get
            {
                return (ApprovalDate != null || ApprovalsCount > 0);
            }
        }
        public bool IsClosedOut
        {
            get
            {
                return CloseOutDate != null;
            }
        }
    }

It generates

	SELECT TOP(@__p_1) [x].[ApprovalDate], CASE
		WHEN [x].[NCRID] IS NULL OR ((
			SELECT COUNT(*)
			FROM [Approval] AS [a]
			WHERE [x].[NCRID] = [a].[NCRLink]
		) = 0)
		THEN 0 ELSE (
			SELECT COUNT(*)
			FROM [Approval] AS [x0]
			WHERE ([x0].[approvalStatusTypeID] IS NOT NULL AND ([x0].[approvalStatusTypeID] = 3)) AND ([x].[NCRID] = [x0].[NCRLink])
		)
	END AS [ApprovalsCount], [x].[CloseOutDate], [x].[DateRaised], [x].[Description], [x].[Location], [x].[NCRID], [x].[NCRNo], [x].[RaisedBy] AS [RaisedById], CASE
		WHEN [x].[NCRID] IS NULL OR ((
			SELECT COUNT(*)
			FROM [Approval] AS [a0]
			WHERE [x].[NCRID] = [a0].[NCRLink]
		) = 0)
		THEN 0 ELSE (
			SELECT COUNT(*)
			FROM [Approval] AS [a1]
			WHERE [x].[NCRID] = [a1].[NCRLink]
		)
	END AS [RequestsCount]
	FROM [NCR] AS [x]
	WHERE [x].[ProjectID] = @___userService_Project_ID_0
	ORDER BY [x].[DateRaised] DESC, [x].[NCRNo] DESC, [x].[NCRID] DESC',N'@__p_1 int,@___userService_Project_ID_0 int',@__p_1=20,@___userService_Project_ID_0=1

In this query, only the columns from NCRListDto are included in the SQL query which is the expected result.

This behaviour is consistent in all my simple projections that don't have a collection mapping. This is important because some of my projections are made to avoid retrieving large data columns from the server - they are just a glorified select.

Am I doing something wrong?

**Comment by lbargaoanu** [comment]
It's EF Core. But if the same happens with EF6, we'll take a look.

**Comment by statler** [comment]
Hi lbargaoanu, can you explain where you are at with this?

Are you saying it only happens with EF Core, and there is nothing you can/will do to change it? Or is there something more here.

**Comment by lbargaoanu** [comment]
Yes. Try it with EF6 and you'll see the difference.
