### ISSUE TITLE
Add net472 target

### ISSUE THREAD

**Issue by phatcher** [AutoMapper/AutoMapper#2924]
I know this sounds trivial but my projects that target net472 have a yellow triangle due to AutoMapper only targeting net461.

I think this would also remove the dependency on System.Tuple since net472 is the level at which all the shim assemblies required for netstandard2.0 compatibility go away.

**Comment by lbargaoanu** [comment]
We'll eventually drop 4.6.1 and target .Net Standard 2.0.
