### ISSUE TITLE
 Pass a parameter to destination contructor when using .ProjectTo

### ISSUE THREAD

**Issue by zoinkydoink** [AutoMapper/AutoMapper#2925]
I posted a question on SO but has not gotten a proper response on the correct course of action, please let me know what the best way to do tis

https://stackoverflow.com/questions/53908522/automapper-pass-a-parameter-to-destination-contructor-when-using-projectto?noredirect=1#comment94675340_53908522

The parameter I wanna pass has nothing to do with mapping, my object constructor requires a object that is not used for mapping, just internally required for when the properties are mapped.

**Comment by lbargaoanu** [comment]
I've already answered on SO.
