### ISSUE TITLE
MapperConfigurationExpression does not use a service provided by ConstructServicesUsing

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#2929]
### Mapping configuration

```csharp
services.AddAutoMapper(
        ce =>
        {
            var serviceProvider = services.BuildServiceProvider();
            // 1
            ce.ConstructServicesUsing(serviceProvider.GetService);
            // 2
            foreach (var t in profileTypes)
                  ce.AddProfile(serviceProvider.GetService(t) as Profile);
        }, new Assembly[] { }); 
```

### Version: 7.0.1
There is no change in this file in 8.0.0, so the error is still there.

### Expected behavior
An object constructor provided is used (MapperConfigurationExpression.cs, line 44). So set up in line (1) shall be sufficient, and line (2) as well as an empty Assembly array should not be necessary.

### Actual behavior
Hard-coded to Activator.CreateInstance.

**Comment by lbargaoanu** [comment]
[This](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md) is the intended usage. So if you want smth else, you should write your own.

**Comment by mc0re** [comment]
Then what is the use scenario for ConstructServicesUsing?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Dependency-injection.html

**Comment by mc0re** [comment]
From that page:
```
mce.ConstructServicesUsing(_container.GetInstance);
mce.AddProfiles(typeof(SomeProfile).Assembly);
```
The last line goes exactly to line 44 in `MapperConfigurationExpression.cs`, which calles `Activator`, and not `ServiceCtor`.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by mc0re** [comment]
I believe this is a bug, not a usability question.

**Comment by mc0re** [comment]
I mean, you suggested the documentation page, which describes the intended usage of ConstructServicesUsing, but it won't work as expected.

**Comment by lbargaoanu** [comment]
Whatever else you need, you'll have to implement it yourself.

**Comment by mc0re** [comment]
The question is, if I submit a pull request where I change the mentioned line to use `ServiceCtor` - will it break anything?

**Comment by lbargaoanu** [comment]
That's by design, I'm sure a little research will tell you why.

**Comment by mc0re** [comment]
I'm not sure why, as `ServiceCtor` is initialized to `Activator.CreateInstance`...

**Comment by jbogard** [comment]
Just to follow up here - you're using `AddAutoMapper` very wrongly. The `services.AddAutoMapper` call will set up all the stuff you're trying to do manually here. That's why you're getting weird stuff. You're using it wrong. Just call `services.AddAutoMapper` with the assemblies you want to scan for `Profile` types.

**Comment by mc0re** [comment]
I'm afraid you've overseen, that the `Profile`s I'm trying to instantiate have dependency injection in their constructors. Like `void MyProfile(ISomeRepository repo)`. This is needed for the mappings - to map from a name/ID of an external object to the actual object from the repository.
In order to get this dependencies injected, I need to use .NET Core's "services" object to instantiate the `Profile`s, not `Activator`.
And I found a possible clean way of doing it - `ConstructServicesUsing` - albeit it's not working, because the actual code creating the objects does not use `ServiceCtor`, as would be expected.

**Comment by jbogard** [comment]
Oh no, you really don’t want to do that. You want to take advantage of
existing extensions to do DI. Otherwise very unexpected things may happen.

Use resolvers, type converters etc that are all correctly wired to DI.

**Comment by mc0re** [comment]
What could possibly go wrong? ;-)

Okay, you know this code like no one. I'd like to ask you two things then.
1) What suits my case best, and where do I start on it?
2) What is the use case for `ConstructServicesUsing`?
