### ISSUE TITLE
Support creating maps via attributes

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2930]
Folks in the community have created marker interfaces like "`IAutoMapFrom<TSource>`" to facilitate conventional creation of maps with scanning. We've got conventions but nothing that builds in via attributes.

For simple mappings, rather than relying on dynamic mapping, this would let you create a map instead of using a profile. Something like:

```c#
[AutoMap(SourceType = typeof(Foo)]
[AutoMap(typeof(Foo))]
[AutoMap(typeof(Foo), ReverseMap = true)]
public class FooDto {
}
```

**Comment by jbogard** [comment]
Originally a feature idea from @JonPSmith using marker interfaces

**Comment by TylerCarlson1** [comment]
This test would get the desired effect from current conventions.

The question is would this be settable convention that we can make, or is it an always on kind of feature?
Also same convention could be made with `IAutoMapFrom<TSource>` in this manner.

I would want to make it configurable, for any reason people want to disable it, and possibly on by default.

```
public class AttributeUsage : AutoMapperSpecBase
    {
        protected override MapperConfiguration Configuration { get; } = new MapperConfiguration(cfg =>
        {
            // Not sure why has to be false in order to pass but does
            cfg.CreateMissingTypeMaps = false;
            cfg.AddConditionalObjectMapper().Where((s, d) =>
            {
                var fromReverseMap = d.GetCustomAttribute<MapToAttribute>();
                return d.IsAssignableFrom(s.GetCustomAttribute<MapToAttribute>()?.ToType) ||
                       (fromReverseMap?.ReverseMap == true && s.IsAssignableFrom(fromReverseMap.ToType));
            });
        });

        public class To
        {
            public int I { get; set; }
        }

        [MapTo(typeof(To))]
        public class From
        {
            public int I { get; set; }
        }

        [MapTo(typeof(From), ReverseMap = true)]
        public class ToBack
        {
            public int I { get; set; }
        }

        [Fact]
        public void Main()
        {
            Mapper.Map<To>(new From{I = 5}).I.ShouldBe(5);
            Mapper.Map<ToBack>(new From { I = 5 }).I.ShouldBe(5);

            Should.Throw<AutoMapperMappingException>(() => Mapper.Map<From>(new To()));
        }

        [AttributeUsage(AttributeTargets.Class)]
        public class MapToAttribute : Attribute
        {
            public Type ToType { get; }
            public bool ReverseMap { get; set; }

            public MapToAttribute(Type toType)
            {
                ToType = toType;
            }
        }
    }
```

**Comment by JonPSmith** [comment]
Obviously I like this type of approach of as I use it in my [EfCore.GenericServices](https://github.com/JonPSmith/EfCore.GenericServices) library, which uses AutoMapper. I wanted to make the library really quick and simple to use, but also extensible, which is hard to get right (I got it wrong in previous libraries!). I used a generic interface `ILinkToEntity<TEntity>`, but I think Attributes is a better idea for AutoMapper. Here is what I did.

1. My interface setup up everything, including a default AutoMapper mapping (see [my default setting](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#ilinetoentitytentity---tells-genericservices-what-entity-the-dto-links-to)).
2. Once I need to change anything, then the user has to provide a config class (see [my advanced setting](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#perdtoconfigtdto-tentity---optional-configuration-for-a-specific-dto)).

My main point is: **make it easy for people to understand and use** - that helps people who are new to programming, and helps us old hands to write our code quicker. That means not over complicating the default mapping attribute - just keep it to a few, obvious parameters and a very obvious name, e.g. `AutoMapTo(TDestination)`. Then either have a more complicated version of the attribute with a different name, or use extra attributes that handle more complex situations.

**Comment by jbogard** [comment]
@TylerCarlson1 I would make it always-on, just like the current couple of attributes are. Though I think as part of this, I'd move the attributes to use whatever method this does.

I'm not sure I'd use conditional mappers, however, since those only get added at `Map` time. I'd rather do some sort of scanning like we do for profiles.

**Comment by jbogard** [comment]
I think this would require us to modify our scanning right now. We only scan for profiles, and the name is `AddProfiles`. Maybe something better would be `AddMapsFrom` or `AddMaps`?

**Comment by JonPSmith** [comment]
> I think this would require us to modify our scanning right now. We only scan for profiles, and the name is `AddProfiles`. Maybe something better would be `AddMapsFrom` or `AddMaps`?

I was assuming you would still scan for profiles (so that existing systems still work), but now also scan for classes that are decorated with your new attributes. The classes where mapping is defined by attributes would add to any profile provided mappings.

**Comment by TylerCarlson1** [comment]
If you do scanning. It would not be always on like your other attribute is. You would have to scan every class.  Wait times for that might irk people on their websites if you left it always on. 

They way I provided is the simlplest way to extend automapper with as little clutter as possible. You can make the conditional mapper an extension method and make a separate dll that extends off Automapper and not have to deal with all the internals.

If you want it fully integrated into auto mapped that’s fine. You can bypass scanning by having another check when seeing if type pairs can make a map. 

My solution was a quick and dirty solution to the problem with minimal code changes

**Comment by jbogard** [comment]
@JonPSmith yeah, I'd extend the existing profile scanning to also scan for attribute-defined maps. So it would pick up easy-mode maps and complex-mode maps.

**Comment by jbogard** [comment]
@TylerCarlson1 scanning is already happening for most folks using AutoMapper these days, because they're using `services.AddAutoMapper(typeof(Startup));`

To me, conditional mappers/conventions make most sense when you'd have to scan *all* types for source/destination pairs that might match, making it O(N^2). For scanning just the attributes, I'm already O(N) for looking for profiles, adding this extra match won't add much imo.

**Comment by lbargaoanu** [comment]
@jbogard OK, but having two similar attributes that work very differently seems quite misleading to me.

**Comment by lbargaoanu** [comment]
The new one and MapTo.

**Comment by lbargaoanu** [comment]
Surely some people wouldn't even notice the different namespace :) But maybe it's all theoretical. We can always wait and see.

**Comment by lbargaoanu** [comment]
I would go for the simplest option in the beginning. It should be exclusive. Either attributes or code.

**Comment by jbogard** [comment]
Another option could be to use an interface to configure type maps, something like @JonPSmith 's [extra config class ](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#perdtoconfigtdto-tentity---optional-configuration-for-a-specific-dto).

You could have the destination type implement this, but it'd require a no-arg ctor. This would be *yet another* way to configure maps, so that could clutter things.

**Comment by jbogard** [comment]
The exception for duplicate type maps is a bit confusing in the current case, I'll create a separate check for this scenario.

**Comment by jbogard** [comment]
Fixed by #2933

**Comment by JonPSmith** [comment]
Hi @jbogard,

Looking good on supporting creating maps via attributes - simple and clean. I assume you will put some documentation out when you release it.

Two questions:
1. I'm not that clear how you set the  `ApplyConfiguration` part of the map. Is there an example of that somewhere?
2. What's the timeline for the release of v.next with the attribute?

**Comment by jbogard** [comment]
Yeah, we will. I'm looking at the attributes for simple member configuration too. I might have one page for attribute-based maps, then for each config option that can be done via code, include the attribute option too.

1. What part? In the attribute?
2. I suppose when the member attributes get more or less finalized.

**Comment by JonPSmith** [comment]
OK, thanks for the quick feedback. I am updating [one of my libraries](https://github.com/JonPSmith/EfCore.GenericBizRunner) that uses AutoMapper (the one where I got the config of AutoMapper 'wrong') and I want it to support `AutoMap`. I can wait.

Going through the discussion it looks like you keeping the  `AutoMap` attribute only for default mapping classes and anything else is done via the existing Profile etc. That is nice and simple, which I applaud. 

I do think a optional, per-class IMappingExpression configuration would be nice (following the single responsibility pattern), but not if it complicates the  `AutoMap` attribute approach. 

My [PerDtoConfig<TDto, TEntity>](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#perdtoconfigtdto-tentity---optional-configuration-for-a-specific-dto) is one way, but it isn't simple. I [scan the assembly](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/GenericServices/Setup/Internal/RegisterOneDtoType.cs#L43-L66) where the class to be mapped for a class with the right `PerDtoConfig<TDto, TEntity>` type and extract any mapping data from the class.

PS. I dug around and found were the `ApplyConfiguration` method is used, so I get that now.

**Comment by jerone** [comment]
I was using [**AutoMapper.Attributes**](https://github.com/schneidenbach/AutoMapper.Attributes) package. But it's developer discontinued it's maintenance. What is being discussed and created here looks a lot like the basics of AutoMapper.Attributes. I might be interesting to look into that package. Also, will AutoMapper itself be extended like that, in a way that I can drop AutoMapper.Attributes?
