### ISSUE TITLE
System.ValueTuple error then System.InvalidOperationException after adding binding redirect.

### ISSUE THREAD

**Issue by wesley-pattison** [AutoMapper/AutoMapper#2932]
It's the classic story where locally my code works but once we deploy the project to our test environment, I start to see two different errors depending on some binding redirects.

Some background of our projects. We're currently targeting `v4.7 (latest major)` for all of our  except for one is in `.netstandard2.0`.

### Mapping configuration

```csharp
            Mapper.Initialize(config =>
            {
                config.CreateMap<Policy, PolicyRequestModel>();
                config.CreateMap<Claim, ClaimRequestModel>();
                config.CreateMap<Person, PersonRequestModel>();
                config.CreateMap<Vehicle, AutomobileRequestModel>();
            });
```

### Expected behavior

No error to appear. Mapping successfully happens.

### Actual behavior
**Without Binding Redirect**

> System.IO.FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> File name: 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
> 

**With Binding Redirect**

> System.InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
>    at AutoMapper.Mapper.get_Instance()
>    at AutoMapper.Mapper.Map[TDestination](Object source)

### Steps to reproduce

```csharp
Mapper.Map<TRequestEntity>(entityParsed.Entity);
```

Things I've tried...

- Upgrading from 7.0.1 to 8.0.0 - Same error
- Removing System.ValueTuple after upgrade to 8.0.0 - Unable to, AutoMapper is dependent on this package and Visual Studio refuses to uninstall System.ValueTuple.
- Binding Redirect in my web config for AutoMapper and System.ValueTuple
```
      <dependentAssembly>
        <assemblyIdentity name="AutoMapper" publicKeyToken="be96cd2c38ef1005" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.1.0" newVersion="7.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
```

**Comment by lbargaoanu** [comment]
@jbogard Target only .net standard 2.0?

**Comment by wesley-pattison** [comment]
That's quite the change on our side to change our targets to .netstandard 2.0

**Comment by lbargaoanu** [comment]
@wesley-pattison I was talking about AM itself. The current version will only work with the right redirect. You need to investigate and find out what that is in your particular case.

**Comment by wesley-pattison** [comment]
@lbargaoanu Is this `Mapper not initialized. Call Initialize with appropriate configuration. ` a known side effect of this? I'm using SimpleInjector and AutoMapper in a very basic matter.

**Comment by lbargaoanu** [comment]
No. You're doing smth wrong. I think this is better suited for StackOverflow.

**Comment by wesley-pattison** [comment]
Solved.

**Comment by jbogard** [comment]
....how?

**Comment by wesley-pattison** [comment]
I made two significant changes:

- Changed where mapping initialize occurs. This was on Application_Start at first for our service, however, we due to legacy code we have different entry points into our system and I'm certain that this block of code wasn't being hit.
- Inject IMapper instead of using the static implementation
