### ISSUE TITLE
Missing sample code

### ISSUE THREAD

**Issue by StephanWolf** [AutoMapper/AutoMapper#2934]
What happened to the sample code?
The [link](https://github.com/AutoMapper/AutoMapper/tree/master/src/AutoMapperSamples) in the documents no longer works.

**Comment by jbogard** [comment]
What link in the documents?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/master/docs/index.rst#samples

**Comment by jbogard** [comment]
Ah, I'd just remove that section. The docs already have samples. They ARE the samples, besides the unit tests.
