### ISSUE TITLE
Support configuring attribute maps with additional properties

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2936]
Follow up to #2930, the initial implementation only does reverse map configuration.

There are a number of configuration options that we could include as part of the `AutoMapAttribute` configuration.

Easy ones:

 - ConstructUsingServiceLocator (bool)
 - MaxDepth (int)
 - PreserveReferences (bool)
 - DisableCtorValidation (bool)
 - MemberList (enum)
 - IncludeAllDerived (bool)
 - TypeConverter (Type)

Not-so-easy-ones:

 - Value transformers
 - Expression/func-based type converters
 - Before/after map
 - Include/IncludeBase

I'd lean towards if you're trying to do the "hard ones", then you should use the API because any attribute-based configuration would be ugly.

**Comment by gmilani** [comment]
Hello @jbogard @lbargaoanu 
I want to start contributing to AutoMapper project. Can I start with the easy configuration options?

**Comment by lbargaoanu** [comment]
Sure, but do look at https://github.com/AutoMapper/AutoMapper/pull/2944 first.

**Comment by gmilani** [comment]
We are configuring the mapping directly in the class, the properties are configured from annotations. So I can not imagine a situation where it would be necessary to use `IncludeAllDerived`, since the configuration is already explicitly in the property of the base class. Can you show me an example if I'm mistaken?

**Comment by lbargaoanu** [comment]
A MapFrom will be inherited by default, which is nice, but [runtime polymorphism](http://docs.automapper.org/en/latest/Mapping-inheritance.html#runtime-polymorphism) does't work by default.
