### ISSUE TITLE
OData groupby not working when using UseAsDataSource

### ISSUE THREAD

**Issue by StephanWolf** [AutoMapper/AutoMapper#2939]
### Version: x.y.z

    AutoMapper 8.0.0
    AutoMapper.Extensions.ExpessionMapping 2.0.0
    EntityFramework 6.2.0
    Microsoft.AspNet.OData 7.1.0
    Microsoft.AspNet.WebApi 5.2.7
    Microsoft.AspNet.WebApi.Core 5.2.7
    Microsoft.OData.Core 7.5.3

### Expected behavior

 groupby should not error when using the UseAsDataSource method.

### Actual behavior

Getting an error when making an OData groupby call on an entity 

### Steps to reproduce

```csharp
// http://localhost/Entities?$apply=groupby((EntityStatusCode),aggregate(EntityId with countdistinct as total))
// This works when calling OData with groupby
    return db.entity.AsQueryable().ProjectTo<Entity>();

// However, this returns an error.
    return db.entity.UseAsDataSource().For<Entity>();

```

**Comment by lbargaoanu** [comment]
Expression mapping was moved to a different [repo](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping). But without a PR, nothing is going to happen.
