### ISSUE TITLE
AddProfiles() overload that takes an IEnumerable<Profile> ?

### ISSUE THREAD

**Issue by norachuga** [AutoMapper/AutoMapper#2942]
Is there a reason why there is no overload of AddProfiles that just takes a collection of Profiles?

I recognize this is a minor quibble, but it seems like a silly omission. I can either add a single Profile at a time, or I can scan any number of assemblies to auto-add multiple profiles. I was surprised to find there's no built-in way to add multiples without going all the way into assembly scanning.

I feel like this should have come up years ago, so I'm surprised that I'm having to make this request!

To put it specifically, I'd simply like to be able to do this:
```
IEnumerable<Profile> profiles = GetProfilesFromSomewhere();
foreach (Profile profile in profiles)
{
  cfg.AddProfile(profile);
}
```

Like this:
```
IEnumerable<Profile> profiles = GetProfilesFromSomewhere();
cfg.AddProfiles(profiles);
```

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by jbogard** [comment]
AddProfiles will be obsoleted soon in favor of AddMaps, which is explicitly
for assembly scanning.

**Comment by norachuga** [comment]
> A PR is welcome.

Certainly! I just wanted to be sure there wasn't some obvious reason or alternative I was overlooking first.

> AddProfiles will be obsoleted soon in favor of AddMaps, which is explicitly for assembly scanning.

Cool. Having a distinct name like that will be great for clarifying that the big difference between the two.

**Comment by jbogard** [comment]
Let's keep this open if it's a feature request
