### ISSUE TITLE
Strict validation of mapping types.

### ISSUE THREAD

**Issue by Temppus** [AutoMapper/AutoMapper#2943]
### Source/destination types

How can I set some kind of global configuration that would trigger exception if mapping types of properties are not the same  ? Example below.

```csharp
        public class UserData1
        {
            public int Id { get; set; }
        }

        public class UserData2
        {
            public string Id { get; set; }
        }
```

### Mapping configuration

```csharp
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<UserData1, UserData2>();
            });
```

### Expected behavior

Either AssertConfigurationIsValid or Map should trigger some kind of validation exception when types od mapping properties are not same.

### Actual behavior

int property is mapped to string without exception.

### Steps to reproduce

```csharp
            // Passes OK
            Mapper.Configuration.AssertConfigurationIsValid();
 
            // Mapping is successfull
            var user2 = Mapper.Map<UserData2>(new UserData1 { Id = 156 });
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
