### ISSUE TITLE
MapFrom mapping function receives the destination member value

### ISSUE THREAD

**Issue by dejvid-smth** [AutoMapper/AutoMapper#2947]
### Source/destination types

```csharp
class Source 
{
    public string Value { get; set; }
}

class Dest
{
    public string Value { get; set; }
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(e 
                => e.CreateMap<Source, Dest>()
                        .ForMember(s => s.Value, cfg => cfg.MapFrom((s, d, v, ctx) => { Debug.Assert(s.Value == v); return v; }))
                ).CreateMapper();
```

### Expected behavior

As per documentation for the `MapFrom` overload used:
```
// Summary:
//     Map destination member using a custom function. Access the source, destination
//     object, source member, and context.
//
// Parameters:
//   mappingFunction:
//     Function to map to destination member
//
// Remarks:
//     Not used for LINQ projection (ProjectTo)
```
I expected third parameter `v` in my configuration to have value of the member on the source instance. Therefore the debugger should not break at Debug.Assert call.

### Actual behavior

The debugger broke on Debug.Assert call and the value of `v` was **dest_val** - from destination instance.

### Steps to reproduce

```csharp
mapper.Map(new Source { Value = "source_val" }, new Dest { Value = "dest_val" }))
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
@dejvid-smth Try a [value converter](http://docs.automapper.org/en/latest/Value-converters.html) or a [member value resolver](http://docs.automapper.org/en/latest/Custom-value-resolvers.html#customizing-the-source-value-supplied-to-the-resolver).
