### ISSUE TITLE
Chain mapping through a property on TSource

### ISSUE THREAD

**Issue by Titansmasher** [AutoMapper/AutoMapper#2948]
Hi, I have an object structure like below:
```csharp
class Outer
{
    public int Id { get; set; }
    public Inner Inner { get; set; }
}
class Inner
{
    public string Foo { get; set; }
}
class Dto
{
    public int Id { get; set; }
    public string Foo { get; set; }
}
```
I wish to have a bi-directional mapping between `Outer` and `Dto`. When going from `Dto` to `Outer`, this is easy. I can just do:
```csharp
cfg.CreateMap<Dto, Outer>()
   .ForMember(dest => dest.Inner, m => m.MapFrom(src => src));
cfg.CreateMap<Dto, Inner>();
```
And everything maps perfectly fine. The issue is the other direction, from `Outer` to `Dto`.
```csharp
// AutoMapper.AutoMapperConfigurationException: Custom configuration for members is only supported for top-level individual members on a type.
cfg.CreateMap<Outer, Dto>()
   .ForMember(dest => dest, m => m.MapFrom(src => src.Inner));
cfg.CreateMap<Inner, Dto>();

// Not leveraging mapping by convention, and is unmanagable when dealing with large amounts of properties
cfg.CreateMap<Outer, Dto>()
   .ForMember(dest => dest.Foo, m => m.MapFrom(src => src.Inner.Foo))

// Not using an expression tree, so cannot work with ProjectOnto
cfg.CreateMap<Outer, Dto>()
   .AfterMap((src, dest, context) => context.Mapper.Map(src.Inner, dest));
cfg.CreateMap<Inner, Dto>();
``` 
The key thing for me is that whatever mapping I use, I need it to work with the `.ProjectOnto<TDestination>(IQueryable source, ...)` method in a way that is compatible with LINQ to SQL.

One potential solution I can think of is to allow the use of `dest => dest` like mappings in the `ForMember` method.
Alternatively an overload of the `.Include` method could be added to `IMappingExpression<TSource, TDestination>`
```csharp
IMappingExpression<TSource, TDestination> Include<TMember>(Expression<Func<TSource, TMember>> includedMember)
```
And the usage would look like:
```csharp
cfg.CreateMap<Outer, Dto>()
   .Include(src => src.Inner);
cfg.CreateMap<Inner, Dto>();
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
I'll add a new issue as a feature request.

**Comment by Titansmasher** [comment]
Thanks, this was intended to be a feature request, i just wasnt sure which approach would make most sense

**Comment by lbargaoanu** [comment]
Most of the things you want can be done today, but indeed, there is smth missing here, as the only way to reuse configuration is with Include. And probably that could be used here too, but the end result might not be pretty.
