### ISSUE TITLE
Include member mappings

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#2949]
Like in #2948. We can do flattening, but this one would allow you to reuse the configuration.
```csharp
cfg.CreateMap<Inner, Dto>();
cfg.CreateMap<Outer, Dto>().Include(src => src.Inner);
``` 
We could have things map to the same destination members, maybe just throw then.
We could start by not supporting cyclical dependencies.
It doesn't seem simple.

**Comment by lbargaoanu** [comment]
Related, if you have a mapping like `MapFrom(s=>s)` the reverse map will not use that. Maybe smth like Merge would be a better approach here. Or just let people do it themselves with AfterMap :)

**Comment by lbargaoanu** [comment]
That Merge thing is supposed to be used instead of Map (taking multiple source objects). So it wouldn't work with ProjecTo either. But the problem remains that conflicts can happen and other than throwing there is no good default behavior. Only the caller knows how conflicts should be resolved. So maybe not having this feature is not the worst thing that can happen :)

**Comment by Titansmasher** [comment]
Isnt conflict resolution already part of the current `.IncludeBase` and `.Include` handling? An inherited member could be mapped by both a mapping for the base class and the parent class. I think what would make the most sense would be for the top level mapping to take priority over the mapping of the included member.

```csharp
CreateMap<Outer, Dto>()
  .ForMember(dest => dest.Foo, m => m.MapFrom(src => src.Bar))
  .Include(src => src.Inner)

CreateMap<Inner, Dto>()
  .ForMember(dest => dest.Foo, m => m.MapFrom(src => src.Xyz))
```
The `dest.Foo = src.Bar` mapping should take priority over `dest.Foo = src.Inner.Xyz`

**Comment by lbargaoanu** [comment]
Yes, but that seems complicated and error prone. The existing Include seems a lot more natural because of inheritance.

**Comment by lbargaoanu** [comment]
Maybe the order thing would make more sense with smth like

     cfg.CreateMap<Outer, Dto>().IncludeMembers(src => src.Inner, src => src.OtherInner);

**Comment by jbogard** [comment]
I like the idea - the naming is bothering me a little bit. Right now `Include` is about inheriting configuration base/sub types. This isn't just inherting configuration, it's also redirecting members. Instead of flattening, we're kinda "pulling" members up from a child property to a parent property.

**Comment by lbargaoanu** [comment]
Well, yes, but only if those members aren't already mapped through the parent object.

**Comment by jbogard** [comment]
Right, it's just the name that's throwing me off. We're adding an overload that provides quite different behavior. I don't have another idea for a name though.

**Comment by lbargaoanu** [comment]
Not technically an overload, it's IncludeMembers :) Flatten seems confusing. Maybe there's smth similar somewhere...

**Comment by lbargaoanu** [comment]
Merge was another idea, but I'm not sure that's what people have in mind when they think about merging multiple objects into one destination.

**Comment by jbogard** [comment]
Ah so it is! Yeah, merge doesn't fit.
