### ISSUE TITLE
Mapper not initialized. Call Initialize with appropriate configuration

### ISSUE THREAD

**Issue by TDK1964** [AutoMapper/AutoMapper#2951]
After upgrading to v8 if get this error. I have read the upgrade doc but still nothing works.

InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by TDK1964** [comment]
That's not very helpful!

**Comment by TDK1964** [comment]
It only happens when I use .ProjectTo<MyModel>()

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#projectto-usage

**Comment by jbogard** [comment]
And https://docs.automapper.org/en/stable/Static-and-Instance-API.html#linq-projections

**Comment by TDK1964** [comment]
Looks like that's the end for us and AutoMapper. V8 is causing far to many problems..

InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.

**Comment by jbogard** [comment]
🤷‍♂️ 🤷‍♂️ 🤷‍♂️ 🤷‍♂️
