### ISSUE TITLE
Expression Translation (UseAsDataSource) incomplete documentation

### ISSUE THREAD

**Issue by cristiangiagante** [AutoMapper/AutoMapper#2954]
I will be very short, the documentation related to UseAsDataSource is incomplete, not give information about requirements of Configuration provider on its arguments.

https://github.com/AutoMapper/AutoMapper/blob/af60a492aba1d8d24ef807450b904cfa30282dee/docs/Expression-Translation-(UseAsDataSource).md

**Comment by lbargaoanu** [comment]
Expression mapping was moved to a different [repo](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping).
