### ISSUE TITLE
New Error Mapping types

### ISSUE THREAD

**Issue by stesvis** [AutoMapper/AutoMapper#2955]
I am using AutoMapper v8.0.0 and I am getting random Error Mapping Types exceptions.

This is one:

>  Exception Type: AutoMapper.AutoMapperMappingException
>  Exception Message: Error mapping types.
> 
> Mapping types:
> DbQuery`1 -> IEnumerable`1
> System.Data.Entity.Infrastructure.DbQuery`1[[LiveDispatch.Web.Models.WorkOrder, LiveDispatch.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IEnumerable`1[[LiveDispatch.Web.DTOs.WorkOrderDTO, LiveDispatch.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
>  Stack Trace:    at lambda_method(Closure , DbQuery`1 , IEnumerable`1 , ResolutionContext )
>    at lambda_method(Closure , Object , Object , ResolutionContext )

That happened here:
`var workOrderDTOs = AutoMapper.Mapper.Map<IEnumerable<WorkOrderDTO>>(workOrders);`

Where **workOrders** is an **IQueryable<WorkOrder>** type.

Here's my mapping profile:
```
                cfg.CreateMap<WorkOrder, WorkOrderDTO>()
                    .ForMember(
                        dest => dest.CustomerName,
                        opt => opt.MapFrom(src => src.Customer.Company)
                    );

```

What could be wrong? If i run that code it works most of the time, but i get random exceptions like that in the logs.
* Could it be related to child entities?
* Should I add .MaxDepth(1)?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
