### ISSUE TITLE
Profiles and mapping primitive types differently

### ISSUE THREAD

**Issue by ossicoinc** [AutoMapper/AutoMapper#2957]
I think that profiles are not working as I would expect them to. In the documentation it states:

> Configuration inside a profile only applies to maps inside the profile. Configuration applied to the root configuration applies to all maps created.

So, I have a use case: For one set of objects, I would like DateTime instances to be specified as UTC. For another set of obejcts, I want them to be specified as Local.

I set up two profiles, and applied the DateTime map to one of them:

### Source/destination types

```vb
DateTime? -> DateTime?
```
### Mapping configuration

Inside UTC profile:
```csharp
CreateMap<Nullable<DateTime>, Nullable<DateTime>>.ConvertUsing(x =>
    {
        if (x.HasValue)
            return DateTime.SpecifyKind(x, DateTimeKind.Utc);
        return x;
    });
CreateMap<ObjectA ObjectBUtc>()
```
where ObjectA and ObjectBUtc contain DateTime properties

### Expected behavior

I would expect that if the object I am mapping to is in the UTC profile, then it would apply the UTC conversion. I would also expect that if the object being mapping is NOT in the UTC profile, no DateTime conversion would happen.

### Actual behavior

Regardless of profile the mapped object is in, the DateTime mapper gets called. Only the UTC profile objects should be mapped that way.

### Steps to reproduce
Create two profiles, one with a DateTime mapping inside of it as above, and map something in the profile WITHOUT the DateTime mapping. The mapping will still get called.

Am I missing something?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Value-transformers.html
