### ISSUE TITLE
Add skip or exception ability in ForAllMembers so that some members can be skipped

### ISSUE THREAD

**Issue by isaacadams** [AutoMapper/AutoMapper#2958]
### Feature Request

I would like to be able to do something like the following
```csharp
.ForAllMembersExcept(dest => {dest.Member1, dest.Member2}, opt => opt.Ignore() )
```

**Comment by isaacadams** [comment]
@lbargaoanu could you possibly suggest what a custom implementation would look like?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
