### ISSUE TITLE
Add support to skip scanning some methods when building TypeDetails

### ISSUE THREAD

**Issue by bfcamara** [AutoMapper/AutoMapper#2959]
From a .net core lib I am consuming a legacy lib written in .net 3.5. I am configuring some mappings with classes that live in that lib. Some of these classes are exposing some non-static public methods that returns or receives as arguments non-compatible types with .net core (types residing in System.Web or System.Web.Services). Even though, I am sure that these methods won't be used from the code I am building, I am getting an error in startup because of the following method that runs when creating internally the type details

```csharp
        private MethodInfo[] BuildPublicNoArgMethods()
        {
            return Type.GetAllMethods()
                .Where(mi => mi.IsPublic && !mi.IsStatic && mi.DeclaringType != typeof(object))
                .Where(m => (m.ReturnType != typeof(void)) && (m.GetParameters().Length == 0))
                .ToArray();
        }
```

Since the return or parameter type cannot be loaded, the initialization process stops with a TypeLoadException.

Changing the legacy assembly is not an option because is out of my control. And I am trying to avoid to add a reference to System.Web or System.Web.Services just for the purpose to fool the initialization mapping.

To prevent this issue, it would be great if we could limit what is being scanned during type details creation. I can think of several solutions
1. Add new config property `SkipScanPublicNoArgMethods` - In this case non-static public methods won't be scanned at all
2. Add new config property `IgnoreTypeLoadErrorsInPublicMethods`
3. Add a new config property `ShouldScanPublicMethod` (`Func<MethodInfo, bool>`)

I think 1) is very simple. Do you think any of these solutions is reasonable?

Please let me know yout thoughts.

**Comment by bfcamara** [comment]
Solution 3 will work as long as we apply function  `shouldScan`  before checking the return type and parameters. Something like 

```csharp
        private MethodInfo[] BuildPublicNoArgMethods(Func<MethodInfo, bool> shouldScanNonStaticPublicMethod)
        {
            return Type.GetAllMethods()
                .Where(mi => mi.IsPublic && !mi.IsStatic && mi.DeclaringType != typeof(object))
                .Where(shouldScanNonStaticPublicMethod)
                .Where(m => (m.ReturnType != typeof(void)) && (m.GetParameters().Length == 0))
                .ToArray();
        }
```` 

My Initialization would become something like
```csharp
            AutoMapper.Mapper.Initialize(cfg => {

                cfg.ShouldScanNonStaticPublicMethod = mi => false;

                cfg.CreateMap<MyClass, MyClassDto>();

            });
```

What do you think? May I propose a PR?

**Comment by lbargaoanu** [comment]
NonStaticPublicMethod sounds arbitrary to me. It should apply for all members, or at least for all methods.

**Comment by bfcamara** [comment]
Do you think `shouldScanMethod`  is better? Probably you'r right. My only concern here is to make it clear what this function will filter, and if applied before or after some conditions that is already in place.

My initial though for this new prop was to just filter from public, non static methods, which are the one that are being checked for no-arguments. Probably it's just a matter of making the docs clear.

**Comment by lbargaoanu** [comment]
I think the new filter should apply before any filter AM uses, in BuildPublicNoArgExtensionMethods and BuildPublicNoArgMethods.

**Comment by jbogard** [comment]
And match our convention, ShouldMapXyz
