### ISSUE TITLE
Mapping parameters in VB not working

### ISSUE THREAD

**Issue by CalinLeafshade** [AutoMapper/AutoMapper#2961]
Related to #1748

I've just updated Automapper to 8.0 (and .Net to 4.6.1, which i think might be the cause of the issue) and paramterised mappings now fail with the error:

```
Field 'Taploma.EventTemplateProfile+_Closure$__1-0.$VB$Local_userID' is not defined for type 'Taploma.EventInstance'
```

Looking at the previous issue i raised it seems like the newer version of .NET may have changed the name of closure variables.

### Mapping configuration

```VB.NET

  Dim userID = 0

        CreateMap(Of EventTemplate, MyEventsDto).
            ForMember(Function(dest As MyEventsDto) dest.Template,
                      Sub(opts) opts.MapFrom(Function(src As EventTemplate) src)).
            ForMember(Function(dest As MyEventsDto) dest.Instances,
                      Sub(opts) opts.MapFrom(Function(src As EventTemplate) src.Instances.
                                                 Where(Function(x) x.Invites.Any(Function(i) i.SentToID = userID))))

```

### Version: x.y.z
Automapper: 8.0.0
EF: 6.2.0

**Comment by CalinLeafshade** [comment]
I can confirm that downgrading Automapper to 5.2.0 fixes the issue. Downgrading to 7.0.0 does not.

**Comment by CalinLeafshade** [comment]
Also can confirm there's not difference between .NET 4.5.0 and 4.6.1. So it must be a regression in AutoMapper.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by lbargaoanu** [comment]
@CalinLeafshade If @bodrick is correct, the [MyGet](https://docs.automapper.org/en/stable/The-MyGet-build.html) should fix your issue.
