### ISSUE TITLE
Upgrade to 8.0 from 3.3.1

### ISSUE THREAD

**Issue by h4d3s2004** [AutoMapper/AutoMapper#2963]
We have Automapper version 3.3.1 in a project and we have decided to upgrade to version 8.0.
The initialization was changed to use Profile  as specified in  the upgrade guide) - pls see bellow.
The first problem is that Mapper.AssertConfigurationIsValid(); fails with error that 
several (not all) properties are not mapped, but they were mapped. 

### Source/destination types

```csharp
public class User {
 
 public List<UserSsoId> SSOIDs { get; set; }
 
}

public sealed class UserSsoId : Entity
    {
      
        public Guid UserId { get; set; }


        public string SsoId { get; set; }
}
[Serializable]
    public class UserDto
    {
 
  public string SSOID { get; set; }
}

	
```csharp
// Put your source/destination types here
```

### Mapping configuration
   Mapper.Initialize(cfg =>
                {
                    cfg.Advanced.AllowAdditiveTypeMapCreation = true;
                    foreach (var module in mapsModules)
                    {
                        foreach (var map in module.Maps)
                        {
                            Profile profile = (Profile)map.Value;
                            cfg.AddProfile(profile);
                        }
                    }                    
                }); // mapsModules inherit from Profile and injected by DI

```csharp
 // In the init map code bellow the properties 	CountLineItemsFlatWithoutSystems and CreatedTimestamp  are considered as not mapped and the other properties are ok.

            CreateMap<Quote, QuoteDto>(MemberList.None)
                .ForMember(target => target.CreatorUser, opt => opt.MapFrom(source => new UserDto { Id = source.GlobalCreateModifyTrack.CreatorId }))
                .ForMember(target => target.ModifierUser, opt => opt.MapFrom(source => new UserDto { Id = source.GlobalCreateModifyTrack.ModifierId }))
                .ForMember(target => target.CreatedTimestamp, opt => opt.MapFrom(source => source.GlobalCreateModifyTrack.CreatedTimestamp))
                .ForMember(target => target.CountLineItemsFlatWithoutSystems, opt => opt.Ignore())
                .ForMember(target => target.IsFavoriteOfUser, opt => opt.Ignore());

		
```

### Expected behavior
Mapping from a list to a string should work and all the mapped properties are detected.

### Actual behavior

The second problem is that a mapping like this .ForMember(target => target.SSOID, opt => opt.MapFrom(source => (source.SSOIDs != null && source.SSOIDs.Any()) ? source.SSOIDs.First().SsoId : string.Empty))	returns null  in target.SSOID  when  source.SSOIDs != null && source.SSOIDs.Count > 0

### Steps to reproduce
Upgrade to 8.0.0 from 3.3.1

```csharp
 Mapper.Map<TSource, TTarget>(source);
```

I've tried to upgrade to an intermediate version (4.1.1 and 4.0.1) but some units tests failed because List<FooSrc> did not map to List<FooDest> anymore ( we have mappings from FooSrc to FooDest).
Any hints or help are welcome. 

Thank you.

Sorry for the long post.

**Comment by lbargaoanu** [comment]
Check [the upgrade guide](https://docs.automapper.org/en/latest/8.0-Upgrade-Guide.html). And http://docs.automapper.org/en/latest/5.0-Upgrade-Guide.html.

**Comment by h4d3s2004** [comment]
I've already did.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by h4d3s2004** [comment]
It's missing details or too strange ?

**Comment by lbargaoanu** [comment]
3.3.1 was a long time ago. You just have some mappings that don't work. You need to change them so they work on the current version. SO is the right place to ask for help with your code.
