### ISSUE TITLE
AutoMapper Manager Tool

### ISSUE THREAD

**Issue by giorgiozoppi** [AutoMapper/AutoMapper#2968]
Hello ,
i need a tool for mantaining my maps in my stacks. It shall be able to generate a MapperFactory class, in which i use the maps. It might be web or desktop UI.
Req. The user shall be able to add remove fields.
The system shall be able to generate maps foreach layer: BusinessLayer, DataLayer etc.
Anyone is already working on this? Before i start?
Best Regards,
Giorgio.

**Comment by lbargaoanu** [comment]
No. Good luck!
