### ISSUE TITLE
Scoped IMapper is bad idea

### ISSUE THREAD

**Issue by ZOXEXIVO** [AutoMapper/AutoMapper#2970]
Related to https://github.com/AutoMapper/AutoMapper/issues/2569
Scopes lifetime flows into application services and it very annoying behaviour.
Turns out, that mapper change behaviour of our services.
It's just mapper, not HttpContext, DbContext or other contexts. 
Maybe Automapper takes on too much ?

**Comment by lbargaoanu** [comment]
That's for the DI repository.
