### ISSUE TITLE
Map class from generic property

### ISSUE THREAD

**Issue by huysentruitw** [AutoMapper/AutoMapper#2975]
How would I go and setup a map for mapping `source`, which is of type `NonNull<Source>` to `Dest` without wrapper class? (I want to avoid passing `source.Value` to the map function, but I'd like to just pass `source` instead).

```csharp
class Source
{
    public string Val1 { get; set; }
    public string Val2 { get; set; }
}

class Dest
{
    public string Val1 { get; set; }
    public string Val2 { get; set; }
}

class NonNull<T>
{
    T Value { get; set; }
}

var source = new NonNull<Source>
{
    Value = new Source { Val1 = "A", Val2 = "B" }
};
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. But I would try http://docs.automapper.org/en/latest/Flattening.html.

**Comment by lbargaoanu** [comment]
On the opposite end of the spectrum (complexity wise) you have [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Mappers/NullableSourceMapper.cs) but I'm sure there are a few options in between.

**Comment by huysentruitw** [comment]
Full question is here https://stackoverflow.com/questions/54588481/how-to-map-from-wrapped-source-properties-to-unwrapped-destination
