### ISSUE TITLE
CompileMappings fails with generic maps

### ISSUE THREAD

**Issue by Stannieman** [AutoMapper/AutoMapper#2976]
Hi,
I think I've found an issue with generic mappings in AutoMapper 7 and above.
```
public partial class App : Application
    {
        public App()
        {
            Mapper.Initialize(x => x.CreateMap(typeof(IList<>), typeof(IEnumerable<>)).ConvertUsing(typeof(Converter<>)));
            Mapper.AssertConfigurationIsValid();

            var list = new List<int> { 1, 2, 3 };
            var mapped = Mapper.Map<IEnumerable<int>>(list);

            Mapper.Configuration.CompileMappings();
        }
    }

    public class Converter<T> : ITypeConverter<IList<T>, IEnumerable<T>>
    {
        public IEnumerable<T> Convert(IList<T> source, IEnumerable<T> destination, ResolutionContext context)
        {
            return source;
        }
    }
```
The mapping itself works: mapped gets assigned the list and I hit a breakpoint in the converter just fine, proving that the mapping also calls it.

However Mapper.Configuration.CompileMappings() throws a null reference exception from the MapperConfiguration.GenerateTypeMapExpression method.
Any idea?

Regards
Stan

**Comment by lbargaoanu** [comment]
Why create a map for the list? You can simply create a map for the element types.

**Comment by Stannieman** [comment]
@lbargaoanu it is a minimal repro, we have other generic types where we used this for.

**Comment by lbargaoanu** [comment]
You can workaround it by not calling CompileMappings or by writing your own version that skips generic maps.
