### ISSUE TITLE
When destination and source models are completely equal and a constructor is defined with all fields as parameters, a defined profile gets ignored

### ISSUE THREAD

**Issue by CharlieBP** [AutoMapper/AutoMapper#2979]
### Source/destination types

```csharp
namespace AutomapperTest
{
    class Model1
    {
        public string Field1 { get; set; }
        public string Field2 { get; set; }
    }
}

namespace Namespace2
{
    class DestinationModel
    {
        public string Field1 { get; set; }
        public string Field2 { get; set; }

        public DestinationModel(){}
        public DestinationModel(string field1, string field2)
        {
            this.Field1 = field1;
            this.Field2 = field2;
        }
    }   
}
```

### Mapping configuration

```csharp
namespace AutomapperTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => cfg.AddProfile<Profile1>());
            var mapper = new Mapper(config);
            var model1 = new SourceModel(){Field1 = "oldValue1", Field2 = "oldValue2"};
            var destinationModel = mapper.DefaultContext.Mapper.Map<Namespace2.DestinationModel>(model1);
        }
    }

     class Profile1 : Profile
     {
         public Profile1()
         {
             this.CreateMap<SourceModel, Namespace2.DestinationModel>()
                 .ForMember(x => x.Field1, o => o.MapFrom(s => "newValue1"));
         }
     }
}
```

### Version: x.y.z
 

Version 8.0.0

### Expected behavior
destinationModel.Field2 to be "newValue1"

### Actual behavior
destinationModel.Field2 actually gets the value of "oldValue2". In fact, it seems that in cases such as this one, where the destination and source models have completely equal field definitions and a constructor having all fields as paramters, the complete profile gets ignored. When you remove the constructor with parameters, the profile does not get ignored.

Also when you change the name of a constructor parameter to not represent the fieldname, it also seems to work fine, like so:
```csharp
public DestinationModel(string field3, string field2)
{
    this.Field1 = field3;
    this.Field2 = field2;
}
```
I spent about 4 hours yesterday to figure out this was the case, so although it's not a bug and people will not tend to be facing it quickly, it is very annoying and unexpected behaviour when you do.

Glad to help out and provide more information if necessary.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Construction.html
