### ISSUE TITLE
AssertConfigurationIsValid doesn't throw when simple types cannot be mapped

### ISSUE THREAD

**Issue by dayDragon** [AutoMapper/AutoMapper#2984]
I create mapping from string to int like this:
### Mapping configuration

            Mapper.Initialize(
                cfg =>
                {
                    cfg.CreateMissingTypeMaps = false;
                });

and then check Mapping:
  Mapper.Configuration.AssertConfigurationIsValid();

### Expected behavior

using workaround from #2799 I expect to get Exception, but it seens that simple types are just always converted with System.Convert
### Steps to reproduce

            Mapper.Initialize(
                cfg =>
                {
                    cfg.CreateMissingTypeMaps = false;
                });

            Mapper.Configuration.AssertConfigurationIsValid();

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by dayDragon** [comment]
it has a question on SO, but we also have documentation which says that AssertConfigurationIsValid Must throw exception
"For example, suppose we have a source type of:

public class Source
{
    public string Value1 { get; set; }
    public string Value2 { get; set; }
    public string Value3 { get; set; }
}
But you would like to map it to:

public class Destination
{
    public int Value1 { get; set; }
    public DateTime Value2 { get; set; }
    public Type Value3 { get; set; }
}
If we were to try and map these two types as-is, AutoMapper would throw an exception (at map time and configuration-checking time), as AutoMapper does not know about any mapping from string to int, DateTime or Type."

And  ur workaround for custom types does not work for simple types, so it IS an Issue

**Comment by lbargaoanu** [comment]
Built-in types are not mapped using type maps so they are not affected by CreateMissingTypeMaps. They are mapped using the mappers in config.Mappers collection. You're free to modify that anyway you want, but that's not a supported configuration, so you're on your own.
