### ISSUE TITLE
Startup time slow

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2985]
From https://groups.google.com/forum/#!topic/automapper-users/rSrvhrAFic8

I have a trace that has a repro, related to #2870

**Comment by jbogard** [comment]
It could be a lot of the LINQ we do during initialization. That allocates a lot with the lambdas and can slow things down. We can try unwinding a lot of the LINQ in `TypeMapFactory` and `PrePostfixName`.

**Comment by lbargaoanu** [comment]
I doubt it. Can you share that trace with me somehow?

**Comment by jbogard** [comment]
And `NameSplitMember`, that's another one. I can also see we're re-evaluating a lot of configuration options for each match - checking for pre/postfix names *every time*.

**Comment by jbogard** [comment]
@lbargaoanu yeah, I sent you a note on LinkedIn.

**Comment by lbargaoanu** [comment]
I was expecting a trace for a Xamarin app :) I'm sure a lot of things could be faster during configuration. But I would think the Xamarin problem is specific. Because the exact same config is fast enough on the regular framework. So we still don't know what happens on Xamarin.

**Comment by jbogard** [comment]
No, you're right - these are two separate issues.

**Comment by huferry** [comment]
I did some profiling and at one point the MapperConfiguration.Seal() gets too slow on profile.Register() call. In my case, on average profile.Register() does it in 350ms and it's being called 135 times. In total it takes like 45 seconds to finished registering all profiles.

Is it possible to register the profile in parallel?

        ... (MapperConfiguration.cs)
        private void Seal()
        {
            var derivedMaps = new List<Tuple<TypePair, TypeMap>>();
            var redirectedTypes = new List<Tuple<TypePair, TypePair>>();

            foreach (var profile in Profiles) // <-- can we loop this in parallel?
            {
                profile.Register(this); 
            }

**Comment by lbargaoanu** [comment]
That means you have 135 profiles. How many maps per profile? 350ms is a long time. AM is just a small part of a given app. Implementation issues aside, I'm not sure you'd want AM init taking more than one CPU. The first step should be to run multiple unrelated init taks in parallel. Unrelated tasks will not need any locking, so the overall logic should be simple enough.

**Comment by lbargaoanu** [comment]
One thing to note, profiles are not isolated things. All the maps are global, the separation is just at compile time. If your profiles are really unrelated, you can always create separate configuration objects and run init in parallel however you see fit.

**Comment by huferry** [comment]
> That means you have 135 profiles. How many maps per profile? 350ms is a long time. AM is just a small part of a given app. Implementation issues aside, I'm not sure you'd want AM init taking more than one CPU. The first step should be to run multiple unrelated init taks in parallel. Unrelated tasks will not need any locking between them, so the overall logic should be simple enough.

Yes. We have a large project. Among others we have lots of enums that needs to be mapped either to int or string (with special values, where casting won't work, that's why we use AutoMapper). For each type of enum we also variate using nullable values, so it grows quite quickly.

It's quite impossible for me to use multiple configuration objects since this means that maintaining the configuration will be too hard; specially to sort out which enums to include/exclude.

**Comment by jbogard** [comment]
Do you have profiling that shows where exactly the time is being spent?
That method does quite a bit. A recent profiling showed that it wasn’t
AutoMapper that was slow but all the custom MapFrom’s that used expression
trees for config.

**Comment by lbargaoanu** [comment]
Closing as I'm not sure what to do about this one. About Android, somebody needs to open a PR.
