### ISSUE TITLE
Resolving AutoMapper issue

### ISSUE THREAD

**Issue by jelwp** [AutoMapper/AutoMapper#2986]
I am getting a run-time error in a simple console app using Unity IOC and Automapper.

I have reproduced this same issue with console apps targeting...

    .NET Framework 4.6.1
    .NET Core 2.2
    .NET Core 2.0

### Nuget Packages
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="Unity" Version="5.9.4" />

### Code
    using System;
    using AutoMapper;
    using Unity;

    namespace ConsoleApp2
    {
        class Program
        {
            static void Main(string[] args)
            {
                var container = new UnityContainer();
                container.RegisterInstance<IMapper>(MapperManager.RegisterMappings());
                container.RegisterType<ICar, Car>();
                container.AddExtension(new Diagnostic());

                var car = container.Resolve<ICar>();
            }
        }

        public interface ICar { }

        public class Car : ICar
        {
            public Car(IMapper mapper) { }
        }

        public class MapperManager
        {
            public static IMapper RegisterMappings()
            {
                var config = new MapperConfiguration(cfg => { });
                return config.CreateMapper();
            }
        }
    }

### Error
![image](https://user-images.githubusercontent.com/46698841/52890533-dad14700-314a-11e9-93ca-6e87f32c18fb.png)

Any idea on how to fix this?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
