### ISSUE TITLE
IObjectMapper using IConfigurationProvider.ResolveTypeMap throws Exception

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper#2987]
Original issue: https://github.com/AutoMapper/AutoMapper.Collection.EFCore/issues/13

When an registered `IObjectMapper` is using the `IConfiguraitonProvider.ResolveTypeMap` an circular dependency chain can throw exception `System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.`.

Adding failing test as a draft PR and another draft PR with a solution that not is ready for shipment yet (its a hack :) ).

**Comment by lbargaoanu** [comment]
That's just weird. Use FindTypeMapFor instead.

**Comment by Tasteful** [comment]
Whats the different between `ResolveTypeMap` and `FindTypeMapFor` and when should each of them be used?

**Comment by lbargaoanu** [comment]
Resolve will create the type map for you, Find will just check whether the user created it. I don't think it makes much sense for a mapper to create a type map.

**Comment by Tasteful** [comment]
One difference I can see (after testing) is that the `FindTypeMapFor` if matching on exact type, the `ResolveTypeMap` is also matching on base classes.

When I try to change to use the `FindTypeMapFor` I got exception that the current test `Map_FromEfToDomain_And_AddAnOnlineOrderInTheDomainObject_And_ThenMapBackToEf_Should_UseTheSameReferenceInTheEfCollection` in `InheritanceWithCollectionTests` not is working. I have hard to see if that is because of anything wrong in the mapping or because of any type that not is created yet.

**Comment by Tasteful** [comment]
I have debug little more and I can see that the `FindTypeMapperFor` only uses the types that is directly registered from `cfg.CreateMap<TSource, TDest>()` into the `_typeMapRegistry`. When using the `ResolveTypeMap` AM also checks and creating mapping for the `.Include<TSourceDerevied, TTargetDeriviedType>()`

![image](https://user-images.githubusercontent.com/357589/52919889-43652300-3307-11e9-8f96-a547549cfc6d.png)

In the failing case we have `TypePair<OnlineOrderDomain, OrderEf>` that not will find any explicit created `FindTypeMapperFor`.

I tested the method to get all related types but that will only build the graph on base so not hit in that either.
```
new TypePair(sourceType, destinationType).GetRelatedTypePairs().ToList()
Count = 6
    [0]: "OnlineOrderDomain", "OrderEf"
    [1]: "OrderDomain", "OrderEf"
    [2]: "Object", "OrderEf"
    [3]: "OnlineOrderDomain", "Object"
    [4]: "OrderDomain", "Object"
    [5]: "Object", "Object"
```

Does it exists any way get the `TypeMap` from the `_typeMapPlanCache` instead of `_typeMapRegistry` without creating non existing items?

**Comment by lbargaoanu** [comment]
Implementation aside, it seems to me that Mapper.IsMatch is a low level thing and it shouldn't ask this kind of questions. It should decide whether it applies based on the type pair it receives. So if FindTypeMap is not good enough, maybe try to postpone the decision and do it in Mapper.Map?

**Comment by Tasteful** [comment]
I have manage to rewrite the AM.Collection to use the `FindTypeMapFor` instead. It should be good if the `ResolveTypeMap` at-least will get a documentation comment that says that it should be used in `IObjectMapper.IsMatch`-method.

The rewrite of AM.Collection usage exists here: https://github.com/AutoMapper/AutoMapper.Collection/pull/121/files#diff-f05d8fe6ffef3ffc993688e83297431e

**Comment by lbargaoanu** [comment]
You mean _it should not_ be used in IsMatch :)

**Comment by lbargaoanu** [comment]
@jbogard Maybe we should have a way to find a matching map without creating it, but I'd say Mapper.IsMatch is not the right use case for it.

**Comment by Tasteful** [comment]
Added more verification check in the https://github.com/AutoMapper/AutoMapper.Collection/pull/121 and then it fails. Do you have another suggestion how we can go around and not need to call the `ReolveTypeMap` to check if the object mapper can be used? Or can we reconsider to add check to avoid the circular reference exception?

**Comment by lbargaoanu** [comment]
I was suggesting to postpone the decision. Assume it's true in IsMatch, and later, during mapping, generate an expression that does the right thing.

**Comment by Tasteful** [comment]
And in the case that `IsMatch` is returning `true` and then it realize it not is able to create the mapping. 

What is the best way in that case to get the next `IObjectMapper` or let AM dynamic create the entity if the `CreateMissingTypeMaps=true` in configuration is set?

cc @TylerCarlson1

**Comment by lbargaoanu** [comment]
Not able to create the mapping? I'm not sure what that means, other than an error.
