### ISSUE TITLE
reliable way determining all used src-members

### ISSUE THREAD

**Issue by Treborius** [AutoMapper/AutoMapper#2990]
for a given mapping configuration, i try to find all source-members that are used in the mapping

some background-info:
- i am trying to implement a crude ORM
- the mapping from datebase-object to business-object is done via automapper
- most of the time, only a subset of the dbo-members are used
- so i need a realiable way of finding all dbo-properties, that are "touched" by the mapping

here is a short example, that shows were i am unable to determine the src-properties

```csharp
public class Line
{
      public int No { get; set; }
      public string Text { get; set; }
}

public class Target
{
      public string Name { get; set; }
      public Line Line { get; set; }
}

public class Src
{
      public int No { get; set; }
      public string Text { get; set; }
      public string Name { get; set; }
}
```

### Mapping configuration
```csharp
private class MapperProfile : Profile
{
      public MapperProfile()
      {
        CreateMap<Src, Target>()
          .ForMember(t => t.Line, opt => opt.ResolveUsing(src => new Line { No = src.No, Text = src.Text }));
      }
}
```

```csharp
    [TestMethod]
    public void FindingReferencedMembers()
    {
      var config = new MapperConfiguration(cfg => cfg.AddProfile<MapperProfile>());
      IMapper mapper = new Mapper(config);

      var typeMap = config.FindTypeMapFor(typeof(Src), typeof(Target));
      var maps = typeMap.GetPropertyMaps();
// for trivial 1-1 mappings this works
//
// but here I find a typemap for the Line property
// without any hint that the origins are src.No and src.Text
    }
```

can you please tell me, if this is somehow possible?
I tried visiting the mappingExpression with an ExpressionVisitor, but that wasn't helpful at all

Thanks in advance, Treb

**Comment by lbargaoanu** [comment]
That's not possible in the general case. If you only use expressions in the mapping, a visitor can do that. But a lot of mapping options are not based on expressions.
