### ISSUE TITLE
Please update Documentation with Steps to get working in ASP.NET Core

### ISSUE THREAD

**Issue by DaleCam** [AutoMapper/AutoMapper#2993]
The documentation is quite lacking with the steps to get working properly in asp.net core.
For example, what do we put in our startup class? With the lack of direction here, there are a few attempts here to get it right:
https://stackoverflow.com/questions/40275195/how-to-setup-automapper-in-asp-net-core

So a really simple example of how to correctly setup Automapper AND the MapperConfiguration for DI in the Startup class for an ASP.NET core project would go a really long way!

For example i tried this as per a combination of your documentation and the SO article in my startup class:
```          
var mapperConfig = new MapperConfiguration(AutoMapperConfig.GetAutomapperConfig());
IMapper mapper = new Mapper(mapperConfig);
services.AddAutoMapper();
```
However it doesnt resolve the MapperConfiguration in DI...

Im so sorry - i know its very likely super simple, but im sure 5 mins of help time would save those like me and in the SO article hours and hours!

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md) and [this](https://github.com/jbogard/ContosoUniversityCore/blob/07bb0f75a616881b7e513a25f6d0d6b4f0cf664c/src/ContosoUniversityCore/Startup.cs#L42). This has been answered many times before, here and on SO.

**Comment by lbargaoanu** [comment]
If you want to add smth to the docs, [this](http://docs.automapper.org/en/latest/Dependency-injection.html#asp-net-core) is the place.

**Comment by DaleCam** [comment]
Thank you! The link was exactly what was needed.
 I still think we should add this to the "Getting Started" part of your documentation however even as a link, as any new comers will likely be looking how to get started with ASP.NET core. 
I will propose a link anyway, you can always reject it in GitHub :)
Thanks heaps for the link!
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md






---- On Tue, 19 Feb 2019 00:20:00 -0600 Lucian Bargaoanu <notifications@github.com> wrote ----




If you want to add smth to the docs, http://docs.automapper.org/en/latest/Dependency-injection.html#asp-net-core is the place.
