### ISSUE TITLE
Performing mapping on IEnumerable\ICollection source collection.

### ISSUE THREAD

**Issue by achobanov** [AutoMapper/AutoMapper#2998]
This is a question, rather than feature/issue.

I want to use `ProjectTo<T>` but on `IEnumerable`\\`ICollection` instead on `IQueryable`. 

### Scenario
API backend, with several service layers:
1. API action - returns `ResponseModel`. 
2. Business service - performs validation, for example. It returns `ServiceModel`
3. Data service - LINQ query to the database, which ends in `ProjectTo<ServiceModel>().ToList()`

As you can see, the data services consume their query and thus they can return `IEnumerable<ServiceModel>` and `ICollection<ServiceModel>` types. 

The question arises in the controller: How to map from `ServiceModel` to `ResponseModel`. This seems like something that should be easily handled by **AutoMapper**. 

The obvious approach is calling `AsQueryable`:
```
// API action
var responseModels = this.businessService
    .Work() // returns ICollection<ServiceModel>
    .AsQueryable()
    .ProjectTo<ResponseModel>();
```

So I guess, my core question is:  can this be done without overhead from calling `AsQueryable` and is `AsQueryable` something I should worry about at all. 

I could easily make a custom extension, which calls `AsQueryable` internally, but I am not sure if it would be a good option, since it would see a lot of use and performance is important. 

Thanks.

**Comment by jbogard** [comment]
You want to use `ProjectTo` against an in-memory collection? Don't. Use `Map`.

`ProjectTo` is for LINQ query providers to use. If you want a handy method to do collection mapping, you can easily write an extension method yourself.

`ProjectTo` has many limitations over in-memory mapping. We only support what query providers can support, mostly EF6. Using `ProjectTo` for in-memory mapping gives you the worst of both worlds. Slower than LINQ `ProjectTo`, and slower than `IMapper.Map`.
