### ISSUE TITLE
Throw if unknown reference type encountered

### ISSUE THREAD

**Issue by famoser** [AutoMapper/AutoMapper#3002]
### Version: 8.0

Is there a way to get AutoMapper to throw if unknown reference types are encountered?
I want to get as much safety from the mappings as possible; hence I am using `AssertConfigurationIsValid`. But this check misses two cases:

- Classes I forgot to include in a profile completely; then I want AutoMapper to crash when I call `Map<>`
- Classes where I forgot to Map a subtype; then I want `AssertConfigurationIsValid` to crash

In short, I want these two unit tests to pass (I used the naming from `ChildClassTests`):

	[Fact]
	public void TestMapperThrowsIfNoMappingDefined()
	{
		var mapper = new MapperConfiguration(cfg => { }).CreateMapper();
		Assert.ThrowsAny<Exception>(() => mapper.Map<SubDTO>(new Sub { BaseId = 1, Sub1 = "1" }));
	}

	[Fact]
	public void TestAssertConfigurationIsValidIfReferenceTypeInMappedHierarchyNotMapped()
	{
		var configuration = new MapperConfiguration(cfg =>
		{
			cfg.AddProfile<BaseProfile>();
		});
		Assert.ThrowsAny<Exception>(() => configuration.AssertConfigurationIsValid());
	}

	private class BaseProfile : Profile
	{
		public BaseProfile()
		{
			this.CreateMap<Base, BaseDTO>();
		}
	}

	public class Base
	{
		public int BaseID { get; set; }

		[Required]
		public virtual Sub Sub { get; set; }
	}

	public class BaseDTO
	{
		public int BaseID { get; set; }
		public virtual SubDTO Sub { get; set; }
	}

	public class Sub
	{
		[Key]
		public int BaseId { get; set; }

		[Required]
		public string Sub1 { get; set; }
	}

	public class SubDTO
	{
		public string Sub1 { get; set; }
	}
	
I have looked through the code base, what I understood so far is that `TestMapperThrowsIfNoMappingDefined` is probably not possible at the moment because of `getOrAdd` used [here](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/MapperConfiguration.cs#L107).
Furthermore, `TestAssertConfigurationIsValidIfReferenceTypeInMappedHierarchyNotMapped` is not passing because it uses the same `getOrAdd` via [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/ConfigurationValidator.cs#L64) call.

Have I missed something, or is my proposal even unwanted behaviour for `AutoMapper`?
If not, would you be open to a contribution which adds a config parameter, and throws in the case that a unconfigured reference type is tried to be mapped?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/stable/Inline-Mapping.html#disabling-inline-maps

**Comment by famoser** [comment]
For furture reference, to get the tests to pass:

```c-sharp
[Fact]
public void TestMapperThrowsIfNoMappingDefined()
{
	var mapper = new MapperConfiguration(cfg => { cfg.CreateMissingTypeMaps = false; }).CreateMapper();
	Assert.ThrowsAny<Exception>(() => mapper.Map<SubDTO>(new Sub { BaseId = 1, Sub1 = "1" }));
}

[Fact]
public void TestAssertConfigurationIsValidIfReferenceTypeInMappedHierarchyNotMapped()
{
	var configuration = new MapperConfiguration(cfg =>
	{
		cfg.AddProfile<BaseProfile>();
		cfg.CreateMissingTypeMaps = false;
	});
	Assert.ThrowsAny<Exception>(() => configuration.AssertConfigurationIsValid());
}

private class BaseProfile : Profile
{
	public BaseProfile()
	{
		this.CreateMap<Base, BaseDTO>();
	}
}
```
