### ISSUE TITLE
ProjectTo should take into account Include in Linq Query

### ISSUE THREAD

**Issue by elvince** [AutoMapper/AutoMapper#3005]
Hi,

We started using ProjectTo, and the eager load behavior is a bit diffucult to control.
In fact, when you have a lot of sub class that are mapped, the amount of data that is retrieved from the database can be huge.

I know from the docs that we can "constraint" the mapping to some properties (Explicit expansion), but we can't just "unmap" just 1 property without doing a new configuration.

My suggestion is to use the "include" statement on a linq query to constrain the Map and if the navigation property is not part of the include, you don't include it in the final query.

```csharp
var request = context.Table1.include(r => r.Table2).projectTo<MyObject>();
```
If on Table2 mapping, you have a Table 3 link, you should not taking them into account as it is not part of the include statements.

Can this be part of a feature request?

Thanks,

**Comment by lbargaoanu** [comment]
That's the purpose of ExplicitExpansion and you should use that. You get to control per ProjectTo call what gets fetched.

**Comment by elvince** [comment]
In fact the explication expansion is great when you want a smal subset of your maping. 
In my case, my mapping include around 80 properties, and I need to ignore 1.

As of today, this feature doesn't allow to "ignore" a small subset of your mappings.

This is the purpose of the request.
1 - Propose a way to ignore a subset of property from the configuration in project to function
2 - Use the include to ignore some "navigation" property.

I would say that option 1 is the best as you can ignore NavProperty as Property, but it might be more difficult to implement.

**Comment by elvince** [comment]
My bad, I didn't understood properly the explicit expansion and how it works.

I didn't understood that you have to set the property to be ExplicitExpansion, so you can use retrieved it or not.

Thanks,
