### ISSUE TITLE
ProjectTo Question with .Net Core

### ISSUE THREAD

**Issue by tspayne87** [AutoMapper/AutoMapper#3006]
### Source/destination types
```csharp
    // Entities
    public class TestCollection
    {
        public string Name { get; set; }
        public ICollection<TestCollectionItem> Items { get; set; }
    }

    public class TestCollectionItem
    {
        public string Name { get; set; }
        public int TestCollectionId { get; set; }
    }

    // Models
    public class TestCollectionModel
    {
        public string Name { get; set; }
        public List<TestCollectionItemModel> Items { get; set; }
    }

    public class TestCollectionItemModel
    {
        public string Name { get; set; }
    }
```

### Mapping configuration
```csharp
    CreateMap<TestCollection, TestCollectionModel()
        .ForMember(prop.Items, o => o.ExplicitExpansion());
    CreateMap<TestCollection, TestCollectionModel()
        .ForMember(x => x.Items, o => o.Ignore());
```

### Version: 8.0.0
Microsoft.EntityFrameworkCore.SqlServer 2.0.1

### Expected behavior
To prevent N+1 behavior

### Actual behavior
N+1 on the Items when loading

### Steps to reproduce
_repository gets a blank query from the current context based on the type passed in.

```csharp
    public List<TestCollectionModel> Test()
    {
        return _repository.Get<TestCollection>()
            .Include(x => x.Items)
            .ProjectTo<TestCollectionModel>(x => x.Items)
            .ToList();
    }
```

### Extra Information
I am unsure if I am doing this correctly but based on the documentation if I eager load the items it should not try to get each of them on load and not call a seperate query for each right?

**Comment by lbargaoanu** [comment]
That works with EF6, so it must be an EF Core issue. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). Run that as a LINQ statement, without AM. You should get the same result.

**Comment by tspayne87** [comment]
Ok, looks like it was something I was doing poorly but got it working fine now.  Just a quick question though, If I had a navigation property on the TestCollectionItem that went to another object and I wanted to set that as ExplicitExpansion as well how would I expand that in the projection query?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Queryable-Extensions.html#explicit-expansion

**Comment by tspayne87** [comment]
This library is amazing btw, I figured it out but I had to dig into the test cases to find my solution, I would think asking for connections inside a collection would be a good example to add to this page.  Also, I was able to get it done by passing in a string to get the connections on the collection is there another way other than passing in strings.

**Comment by lbargaoanu** [comment]
You just have to find the relevant test. Once you do, a PR is welcome for the docs.
