### ISSUE TITLE
ProjectTo fail to resolve property when using custom ValueResolver. 

### ISSUE THREAD

**Issue by CrestApps** [AutoMapper/AutoMapper#3008]
### Source/destination types

I have the following source and destination that I want to get using `.ProjectTo()` method. My sources is an entity-model.
```csharp
// Source
public class User 
{ 
    [Key]
    public int Id { get; set; }
    public string Username { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string FullName
    {
        get
        {
	        var fullname = Str.Merge(user.FirstName, user.MiddleName, user.LastName);

	        return fullname;
        }
    }
}

// Destenation
public class DisplayUserViewModel
{
    public int Id { get; set; }

    public string FullName { get; set; }
    public string Username { get; set; }
}
```

Then I created the following custom resolver

```csharp
public class FullNameResolver : IValueResolver<User, object, string>, IMemberValueResolver<User, object, User, string>
{
    public string Resolve(User source, object destination, string destMember, ResolutionContext context)
    {
        return GetFullName(source);
    }

    public string Resolve(User source, object destination, User sourceMember, string destMember, ResolutionContext context)
    {
        return GetFullName(sourceMember);
    }

    private static string GetFullName(User user)
    {
        if (user == null)
        {
            return string.Empty;
        }

        var fullname = Str.Merge(user.FirstName, user.MiddleName, user.LastName);

        return fullname;
    }
}

```

### Mapping configuration

```csharp
// Here is how I am using my mapper.
expression.CreateMap<User, DisplayUserViewModel>()
            .ForMember(viewModel => viewModel.FullName, opts => opts.MapFrom<FullNameResolver>());
```

### Expected behavior

I am expected the `FullName` property get set using the logic listed in the `FullNameResolver` since I am  explicitly setting a map from the `FullName` property, 

### Actual behavior

It is trying to map User.FullName to DisplayUserViewModel.FullName which causes Entity Framework 6.2 to throw an exception because FullName is not a valid column on the database.

The `.ProjectTo()` method seems to ignore the mapping when using custom-resolver.

`.ProjectTo()` method should use the logic in the Custom-Resolver to resolve the property and should ignore the `User.FullName` property completely.

### Steps to reproduce

```csharp

Mapper.ProjectTo(dbContext.Users)
```

I did another test where I changed the property name on my ViewModel from `FullName` to `UserFullName` thinking maybe this way AutoMapper will use the custom resolver instead of the property map. So my map config changed to the following
```csharp
 expression.CreateMap<CompanyUser, DisplayUserViewModel>()
                .ForMember(viewModel => viewModel.UserFullName, opts => opts.MapFrom<FullNameResolver>());
```

But that throws the following exception 

```
 Can't resolve this to Queryable Expression 
```

Is AutoMapper ignoring my Custom Resolver or it just can't use custom resolvers when using a `ProjectTo()`?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Queryable-Extensions.html#supported-mapping-options
