### ISSUE TITLE
Startup in Xamarin.Forms is slow

### ISSUE THREAD

**Issue by Raystorm7** [AutoMapper/AutoMapper#3012]
Hi!

I have a Xamarin.Forms application that uses AutoMapper plugin to transform some our framework model to a more lightweight mobile model.

I use many profiles and resolvers to do this, but the application takes 16 seconds to starts!

[Here](https://ufile.io/06a97) all the AutoMapper files that I use in the application.

What I am doing wrong?

Thank you to all in advice :smile:

**Comment by lbargaoanu** [comment]
You'll have to profile it and find out exactly where that time is spent.

**Comment by lbargaoanu** [comment]
You can ask for help from your colleagues or on StackOverflow.
