### ISSUE TITLE
Automapper not mapping all child entities within child collection

### ISSUE THREAD

**Issue by cheesegrate** [AutoMapper/AutoMapper#3015]
I already have the following mappings where GearLevels has 6 Gear.

When i map the entities, if the Gear has multiple entities with the same name it only maps one of them.
Should i be doing something else in my mappings to overcome this and if so how do i configure it.            
CreateMap<HeroViewModel, Hero>();
CreateMap<TagViewModel, Tag>();
CreateMap<AbilityViewModel, Ability>();
CreateMap<StatViewModel, Stat>();
CreateMap<GearLevelViewModel, GearLevel>();
CreateMap<GearViewModel, Gear>();

CreateMap<HeroViewModel, RegisterNewHeroCommand>()
                .ConstructUsing(c => new RegisterNewHeroCommand(c.Name, c.MaxDamage))
                .ForMember(dest => dest.Tags, opt => opt.MapFrom(src => src.Tags))
                .ForMember(dest => dest.Abilities, opt => opt.MapFrom(src => src.Abilities))
                .ForMember(dest => dest.Stats, opt => opt.MapFrom(src => src.Stats))
                .ForMember(dest => dest.GearLevels, opt => opt.MapFrom(src => src.GearLevels));

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by cheesegrate** [comment]
ok, will post it there
