### ISSUE TITLE
[Feature Request] MemberList.All

### ISSUE THREAD

**Issue by BalassaMarton** [AutoMapper/AutoMapper#3016]
It would be handy to do a complete, two-way validation in some cases.
Real-world example: the type `TSnapshot<TEntity>` is a backup/snapshot variant for type `TEntity`. `TSnapshot` has a few extra properties that should be ignored, and `TEntity` also has properties that are left out from `TSnapshot` on purpose. What I want to do, is validate that all properties of `TEntity` and `TSnapshot` are either mapped or ignored explicitly.

**Comment by lbargaoanu** [comment]
That can be easily done with an extension method.

**Comment by lbargaoanu** [comment]
But if you really want it built in, a PR is welcome.

**Comment by BalassaMarton** [comment]
Oh OK, documentation simpley says 'Specify which member list to validate', I thought that meant this call overwrites any previous configuration.

**Comment by lbargaoanu** [comment]
`CreateMap().ReverseMap().ValidateMemberList(MemberList.Destination)`
