### ISSUE TITLE
Save and load state of AutoMapper as binary

### ISSUE THREAD

**Issue by Flashed96** [AutoMapper/AutoMapper#3017]
Hi, 

we've got the problem, that AutoMapper got pretty slow when mapping objects for the first time. Our project includes several hundred maps and all of them have PreserveReferences set. The object hierarchy is also pretty deep (around 100 levels) and recursive at multiple levels.

When mapping for the first time it takes > 30 seconds to map an object (including referenced objects). 
When mapping the exact same object a second time it takes about 2 seconds.
We've already executed Mapper.Configuration.CompileMappings before our first mapping operation. 

The actual question: We had the idea to binary serialize the internal objectgraph of AutoMapper that has been built after mapping the first object to a file.
Upon start of our application we'd load that file again and use it in some way to initialize AutoMapper by setting the dezerialized objectgraph.

Do you think this possible in any way?

Thank you in advance

**Comment by lbargaoanu** [comment]
Are you on the latest version? If not, upgrade. Remove all PreserveReferences. We set that for you to avoid SO. If that doesn't help, we need a repro.

**Comment by Flashed96** [comment]
PreserveReferences is set by default? The app relies on getting the same objects after mapping. We're using version 7.0.1 right now.

**Comment by lbargaoanu** [comment]
It's set only to avoid SO. Other than that, of course you need to set it yourself.

**Comment by Flashed96** [comment]
Could you please provide a statement regarding the question about serializing the current state of automapper?

**Comment by lbargaoanu** [comment]
It's just IL, there is nothing to serialize. You need to give us a repro or solve the problem yourself.
