### ISSUE TITLE
How to map "params Expression<Func"

### ISSUE THREAD

**Issue by sturlath** [AutoMapper/AutoMapper#3018]
This is a usage issue.

I have tried various things without luck andI can´t find any documentation on how to do this. 
 
My question is:

> How can I mapp 
**params** Expression<Func<**T**,object>
 to 
**params** Expression<Func<**U**,object>?

```csharp
/// <summary>
/// I like to be able to use multiple Expression with params like this. (this code is in my controller)
/// </summary>
public void GetModel()
{
    var model = GetById(id, x=> x.User, x => x.Destination, x => x.Info);
}

/// <summary>
/// Where I map the params Expression. It works without params. (This code is in my service)
/// </summary>
public MyModelDto GetById(int id, params Expression<Func<MyModelDto,object>> includeExpressions)
{
    Expresssion<Func<MyModel,object> mappedExpression = MyConfig.MapToType<Expression<Func<MyModel, object>>>(includeExpressions);
    
... use mappedExpression  in my repository and return MyModelDto...
}

/// <summary>
///  My config class containing the following
/// </summary>
cfg.AddExpressionMapping();
and
public TDest MapToType<TDest>(object obj) => Mapper.Map<TDest>(obj);

``` 

It might even just be a C# issue but I just can´t crack it.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by sturlath** [comment]
Just to follow up for future readers. I did create a  [question on StackOverflow](https://stackoverflow.com/questions/55440167/how-to-merge-object-expressions?noredirect=1#comment97597118_55440167) and added a test repo on GitHub where the [my mapping error](https://github.com/sturlath/CombineObjectExpressionsTest/blob/02338fa9ef5a81987ee57988acf403857f4ea8e0/CombineObjectExpressions/ExpressionMethods.cs#L40) can bee seen. I will be following this up on SO. 

Thanks
