### ISSUE TITLE
Localization problem when using IMapper in a scoped MediatR IRequestHandler

### ISSUE THREAD

**Issue by Neuroglia** [AutoMapper/AutoMapper#3023]
Hey all!

Im currently working on an API which I equipped with two of my favorite libraries, namely Automapper and MediatR, and I'm facing a small culture-related problem.

Better than a thousands words, a small code snippet follows to illustrate the problem I'm facing as best and simply I can.

How can I get the expected culture ('fr') at step 3, without using the MappingOptions, which would no doubt ask a consequent refactor of all my ITypeConverters and IValueResolvers? 

Thanks in advance for your time/help!

### Steps to reproduce

From within an MVC Controller Action, with request localization to 'fr' culture, say:
```csharp

public class MyController
     : Controller
{

     public MyController(IMediator mediator)
     {
           this.Mediator = mediator;
     }

     protected IMediator Mediator { get; private set; }

     [HttpPost]
     public async Task<IActionResult> Post([FromBody]MyCommand model)
     {
          //1. Here, a CultureInfo.CurrentUICulture would return me the 'fr' culture, as expected
          await this.Mediator.Send(command));
          return this.Ok();
     }

}

public class MyCommandHandler
     : IRequestHandler<MyCommand>
{
   
     public MyCommandHandler(IMapper mapper)
     {
          this.Mapper = mapper;
     }

     protected IMapper Mapper { get; private set; }

     public async Task<Unit> Handle(MyCommand request, CancellationToken cancellationToken)
     {
          //2. Here, a CultureInfo.CurrentUICulture would return me the 'fr' culture, as expected
          var myEntity = new MyEntity();
          var myMappedEntity = this.Mapper.Map<MyMappedEntity>(entity);
     }

}

public class MyEntityConverter
   : ITypeConverter<MyEntity, MyMappedEntity>
{

     public ProductItemInfo Convert(MyEntity source, MyMappedEntity destination, ResolutionContext context)
     {
           //3. Here, a CultureInfo.CurrentUICulture would return me the 'en' culture, meaning the same than CultureInfo.DefaultThreadCurrentUICulture, instead of 'fr'
     }

}

```

### Expected behavior

Matching cultures at step 1, 2 and 3.

Could have accepted different cultures between step 1 and 2 because of the async call.

### Actual behavior

Cultures at step 1 and 2 match, but not 3, which is set to **CultureInfo.DefaultThreadCurrentUICulture**

### Remarks

When injecting and using the IMapper directly in the Controller, the Culture in MyTypeConverter is the expected one, 'fr'

**Comment by lbargaoanu** [comment]
You can receive parameters from the source/destination, an injected service or the resolution context.

**Comment by Neuroglia** [comment]
Yes, I know I can, but I dont understand the behavior. Why is Automapper switching the Culture (so the thread, I guess) in that context and not in the Controller's?

**Comment by lbargaoanu** [comment]
Your problem has little to do with AM. Of course AM doesn't touch the culture/thread. I think this is better suited for StackOverflow.

**Comment by Neuroglia** [comment]
Fair enough. Thanks for your time anyways
