### ISSUE TITLE
The dependency injection in resolver

### ISSUE THREAD

**Issue by kcomin** [AutoMapper/AutoMapper#3027]
Hello,

I set up a resolver to map my BrandId property directly. My DTO CarCreateDTO has only the brand of the car and my entity wants the identifier of this brand.

Here is my profile mapper :

```
public class CarCreateProfile : Profile
    {
        /// <Summary>
        /// Constructor
        /// </Summary>
        public CarCreateProfile()
        {
            CreateMap<CarCreateDTO, CarEntity>()
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
            **.ForMember(dest => dest.BrandId, opt => opt.MapFrom<CarBrandResolver>())**
            .ForAllOtherMembers(opt => opt.Ignore());
        }
    }
```

I call my resolver : 

```
public class CarBrandResolver : IValueResolver<CarCreateDTO, CarEntity, int>
    {
        private readonly ICarsRepository _carsRepository;

        public CarBrandResolver(ICarsRepository carsRepository)
        {
            _carsRepository = carsRepository;
        }

        public int Resolve(CarCreateDTO source, CarEntity destination, int destMember, ResolutionContext context)
        {
            return _carsRepository.GetBrandIdByBrandNameAsync(source.BrandName);
        }
    }
```

My configuration is as follows : 

```
public void ConfigureServices(IServiceCollection services)
        {
            // Add AutoMapper.
            services.AddAutoMapper();           
        }
```

```
public class AutoMapperConfiguration
    {
        /// <summary>
        /// Mapper configuration.
        /// </summary>
        public static MapperConfiguration RegisterMappings()
        {
            return new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new CarCreateProfile());
                
            });
        }
    }
```

and I have the following error :  
```
Error Message:
AutoMapper.AutoMapperMappingException : Error mapping types.

Mapping types:
CarCreateDTO -> CarEntity
CarCreateDTO -> CarEntity

Type Map configuration:
CarCreateDTO -> CarEntity
CarCreateDTO -> CarEntity

Destination Member:
BrandId

**---- System.MissingMethodException : No parameterless constructor defined for this object.**
```

I did many tests. I added my profile mapper directly into my ConfigureServices.
I followed the following example as well: 
[https://medium.com/@sergiobarriel/how-to-read-user-claims-from-automapper-value-resolver-1051d54235f2](url)

**I find that it does not take into account the dependency injection of CarRepository**. Because if I do not fill my constructor in the resolver and return the integer 2 in the Resolve method, it works.

I installed these nugets as well :  
    Automapper
    Automapper.Extensions.Microsoft.DependencyInjection

How could I make my dependency injection work ?

Thanks,
Kevin

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Dependency-injection.html#asp-net-core

**Comment by aborderon** [comment]
Hi,

@lbargaoanu  I also have the same problem on a Web project .NET Core API.

I realized the configuration recommended by the documentation of automapper.

I get the same result as @kcomin when I try to inject a Repository into my Resolver.

Can you direct us on the resolution of this problem because the documentation of Automapper on the dependency injection is really not very clear ...

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. The documentation seems clear enough to me. There is also a link to a working project. Whatever you think it's missing, a PR is welcome.

**Comment by lbargaoanu** [comment]
See also [the tests](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/tree/master/test/AutoMapper.Extensions.Microsoft.DependencyInjection.Tests).

**Comment by aborderon** [comment]
I looked at the test, I use the same configuration for the resolver for and for the dependency injection.

Is there anything special to do to register the resolver?

Possibly in Startup.cs other than services.AddAutoMapper() ?

**Comment by lbargaoanu** [comment]
No, just what the docs say.
