### ISSUE TITLE
AssertConfiguratioIsValid fails on UseDestinationValue()

### ISSUE THREAD

**Issue by Tachionstrahl** [AutoMapper/AutoMapper#3028]
### Source/destination types

```csharp
class Test1
    {
        public int Id { get; set; }
        public Test3 Test2 { get; set; }
        public string Message { get; set; }
    }

    class Test2
    {
        public int Id { get; set; }

        public string Text { get; set; }

        public Test4 Test4 { get; set; }
    }

    class Test3
    {
        public string Title { get; set; }
    }

    class Test4
    {
        public int Nr { get; set; }
    }
```

### Mapping configuration

```csharp
var mapperConfig = new MapperConfiguration(conf => 
                conf.CreateMap<Test1, Test2>()
                .ForMember(d => d.Test4, c => c.UseDestinationValue())
                .ForMember(d => d.Text, c => c.MapFrom(s => s.Message)));
            mapperConfig.AssertConfigurationIsValid();
```

### Expected behavior

The Validation should not throw an exception.

### Actual behavior

Following Exception is thrown:

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=======================================
Test1 -> Test2 (Destination member list)
ConsoleApp1.Test1 -> ConsoleApp1.Test2 (Destination member list)

Unmapped properties:
Test4

### Steps to reproduce

Copy the classes and MapperConfiguration in a ConsoleApp and Run it.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by Tachionstrahl** [comment]
> 
> 
> I think this is better suited for StackOverflow.

Could you please explain why?

**Comment by lbargaoanu** [comment]
Because this is the expected behavior and the message tells what to do about it.

**Comment by Tachionstrahl** [comment]
Why is this the expected behavior, when i explicit want to use the destination value?
And why is the behavior different to the Ignore()-Method, which does nearly the same thing?
