### ISSUE TITLE
The ForPath does not work  with DynamicData.SourceList.

### ISSUE THREAD

**Issue by offan** [AutoMapper/AutoMapper#3029]
The ForPath does not work  with DynamicData.SourceList. Will AutoMapper support https://github.com/RolandPheasant/DynamicData reactive extensions (Rx) for the SourceList and SourceCache collections?

example:

namespace ConsoleAppAutomapperAndDynamicList
{
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<OrderDto, Order>()
                    .ForPath(x => x.MyList.Items, x => x.MapFrom(o => o.MyListDto));
            });

            var obj = new OrderDto
            {
                MyListDto = new List<int> { 2 }
            };
         
            var dest = Mapper.Map<OrderDto, Order>(obj);
            var c = dest.MyList.Count;   // c=0
        }
    }
    public class Order
    {
        public DynamicData.SourceList<int> MyList { get; set; }
    }

    public class OrderDto
    {
        public IList<int> MyListDto { get; set; }
    }
}

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
