### ISSUE TITLE
How to map a parent root class having multiple list classes?

### ISSUE THREAD

**Issue by gautampatluri** [AutoMapper/AutoMapper#3031]
I am able to create successful mapping but only one list class of parent root class gets mapped. From below code only Designation class gets mapped while Customfield fails.

`Source class:
`public class RootObjectSource
        {
            public List<Emp> employments{ get; set; }
        }`
`public class Emp
        {
            public string Id{ get; set; }
            public string Firstname{ get; set; }
            public string Lastname{ get; set; }
            public List<Desig> Desigs{ get; set; }
        }`
public class Desig
   {             
                  public string role{ get; set; }
                  public string salary{ get; set; }
   }

Destination class:
 public class RootObjectDest
        {
           public string principal{ get; set; }
           public List<Designation> designations{ get; set; }
           public List<Customfield> Customfield { get; set; }
        }
 public class Designation
   {             
                  public List<Employment> employment { get; set; }
                  public string role{ get; set; }
                  public string salary{ get; set; }
   }
`public class Employment
        {
            public string Firstname{ get; set; }
            public string Lastname{ get; set; }
        }`
   public class Customfield
   { 
                  public string stringfield{ get; set; }
              
   }`

  Mapping :
cfg.CreateMap<Emp,Designation>()
              
              .ForMember(a => a.desigs, b => b.ResolveUsing(c => c.designations));

                cfg.CreateMap<Emp, Employment>()
                .ForMember(a => a.role, b => b.ResolveUsing(c => c..firstname));

cfg.CreateMap<RootObjectSource, RootObjectDest>()
                 .ForMember(a => a.Customfield, b => b.ResolveUsing(c => c.Emp));

                cfg.CreateMap<Emp, Customfield>()
                .ForMember(x => x.Customfield, y => y.MapFrom(x => x.Id));

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
