### ISSUE TITLE
Cannot convert byte enum to nullable int

### ISSUE THREAD

**Issue by t03apt** [AutoMapper/AutoMapper#3033]
Cannot convert byte enum to nullable int.
I created a failing unit test to reproduce this issue: https://github.com/AutoMapper/AutoMapper/pull/3032/commits/8643542129be3619cad0ba87b737237b3bba6799

```
[xUnit.net 00:00:08.87]     AutoMapper.UnitTests.Bug.CannotConvertByteEnumToNullable.Should_map_byte_enum_to_nullable_int [FAIL]
Failed   AutoMapper.UnitTests.Bug.CannotConvertByteEnumToNullable.Should_map_byte_enum_to_nullable_int
Error Message:
 Shouldly.ShouldAssertException : 0
    should be
2
    but was not
```

**Comment by lbargaoanu** [comment]
Set CreateMissingTypeMaps to false and validation will fail. That's not supported. It will work with byte?. But you have more conversions here. Try a type converter instead. Or you can try to investigate whether there is a simple fix inside AM.

**Comment by t03apt** [comment]
`CreateMissingTypeMaps:false` is great!
Thanks!
