### ISSUE TITLE
ForAllOtherMembers rewrites mapping of properties.

### ISSUE THREAD

**Issue by fancyplot** [AutoMapper/AutoMapper#3038]
Hello, I have a problem that ForAllOtherMember rewrites my configuration for mapping properties. I made a simple example? that illustrates the problem.

### Source/destination types
I have Interface1 in dll Interface1.dll 
```csharp
namespace Interfaces
{
    public interface Interface1
    {
	    string Name { get; }
    }
}
```
Interface2 in dll Interface2.dll 
```csharp
namespace Interfaces
{
    public interface Interface2 : Interface1
    {	
	    new string Name { get; set; }
    }
}
```
Interface3 in dll Interface3.dll 
```csharp
namespace Interfaces
{
	public interface Interface3 : Interface1, Interface2
	{
		string Code { get; set; }
	}
}
```
Source class in testApplication
```csharp
namespace TestApplication
{
	class SourceClass
	{
		public string Name { get; set; }
		public string Code { get; set; }
	}
}
```
Target class in testApplication
```csharp
namespace TestApplication
{
	class TargetClass : Interface3
	{
		public string Name { get; set; }
		public string Code { get; set; }
	}
}
```
### Mapping configuration
I created the following configuration for mapping property Name and not to map property Code.
```csharp
var config = new MapperConfiguration(cfg =>
			{
				cfg.CreateMap<SourceClass, Interface3>(MemberList.None)
					.ForMember(trg => trg.Name, opt => opt.MapFrom(src => src.Name))
					.ForAllOtherMembers(opt => opt.Ignore());
			});
```

### Version: x.y.z
8.0.0
Test project example:
[Automapper test error.zip](https://github.com/AutoMapper/AutoMapper/files/3103445/Automapper.test.error.zip)

### Expected behavior

I expected that in destination class Name equals  "SourceName".

### Actual behavior

Field Name was not passed to destination class and it equals  "TargetName".

### Steps to reproduce

```csharp
IMapper mapper = new Mapper(config);

var source = new SourceClass()
{
	Name = "SourceName",
	Code = "SourceCode"
};

Interface3 dest = new TargetClass()
{
	Name = "TargetName",
	Code = "TargetCode"
};
mapper.Map(source, dest);

Console.WriteLine($"source.Name = {source.Name}  source.Code = {source.Code}");
Console.WriteLine($"dest.Name = {dest.Name} dest.Name = {dest.Code}");

Console.ReadKey();
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
