### ISSUE TITLE
AddOrUpdateFeature extensions needed?

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#3039]
I don't think we need the FeatureExtensions class - instead, like with ASP.NET Core, those feature implementors will call `Features.Set` themselves.

**Comment by jbogard** [comment]
Or at least, we should have consistent naming between those and `Features.Set`. `SetFeature` or `ApplyFeature`.

**Comment by lbargaoanu** [comment]
It seems like they should be able to call them fluently, as they did in the tests. And if they are here, they can be reused. I forgot to rename them. @Tasteful Are they needed in real life, or just for the tests?

**Comment by Tasteful** [comment]
Is always nice to have fluently extensions methods, without I think it can be some extra line of code.

For my part it's not needed.
