### ISSUE TITLE
Automapper Source and NestedSouce to Destination

### ISSUE THREAD

**Issue by Toso82** [AutoMapper/AutoMapper#3042]
### Source/destination types

```csharp

    public class Source
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public NestedSource nestedSources { get; set; }
    }

    public class NestedSource
    {
        public string val1 { get; set; }
        public string val2 { get; set; }
    }

    public class Destination
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string val1 { get; set; }
        public string val2 { get; set; }
    }


```

### Mapping configuration

```csharp
Mapper.Initialize(cfg=> {

                cfg.CreateMap<Source, Destination>()
                //.AfterMap((src,dest)=>Mapper.Map(src.nestedSources,dest));
                .ConvertUsing(s=> Mapper.Map<NestedSource,Destination>(s.nestedSources));                    
                //cfg.CreateMap<NestedSource, Destination>();
            });

```

### Expected behavior

I want to map to create a mapping from Source and NestedSource to Destinazion class.
What is the best do this?

### Actual behavior

with **ConvertUsing**  and **AfterMap**

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters

AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
NestedSource -> Destination (Destination member list)
TestAutoMapper.NestedSource -> TestAutoMapper.Destination (Destination member list)

Unmapped properties:
Name
Surname

### Steps to reproduce

```csharp
Destination destination = Mapper.Map<Source, Destination>(source);
```
@jbogard

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
