### ISSUE TITLE
Allow multiple uses of AutoMapAttribute

### ISSUE THREAD

**Issue by Sharkwald** [AutoMapper/AutoMapper#3049]
We frequently define maps from multiple sources to a single destination. It'd be great, and clean up our code substantially, to be able to do so using the new attribute mapping, but the `AutoMapAttribute` class doesn't allow multiple usage as the relevant flag in `AttributeUsage` is not set.

As an example, we may wish to instantiate a Command class from either an API call model, or a UI View Model:

```csharp
public class Command()
{
    // members

    public class AutoMapperProfile : Profile
    {
        public AutoMapperProfile()
        {
            CreateMap<ApiModel, Command>();
            CreateMap<ViewModel, Command>();
        }
    }
}
```

Ideally, we'd like to be able to do

```csharp
[AutoMap(typeof(ApiModel))]
[AutoMap(typeof(ViewModel))]
public class Command()
{
    // members
}
```

I've had a very quick look, and it appears that setting the appropriate flag on the `AutoMapAttribute.cs` class and changing how those attributes are loaded in `MapperConfigurationExpression.cs` is what's required to allow this.

**Comment by lbargaoanu** [comment]
A PR is welcome.
