### ISSUE TITLE
ProjectTo: Argument types do not match 

### ISSUE THREAD

**Issue by kakins** [AutoMapper/AutoMapper#3051]
Gist here:
https://gist.github.com/kakins/c9c881154efb9df4642a15a23ae82395

### Version: x.y.z
.NET Core 2.2
AutoMapper 8.0

### Expected behavior

`ProjectTo` should work in my example, I have a large object model but my mapping config is not complex.

### Actual behavior

Calling `IQueryable ProjectTo<PositionViewModel>` fails with an "Argument types do not match" error.

### Steps to reproduce
See gist.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
