### ISSUE TITLE
.ProjectToList<T>() throws System.InvalidOperationException exception if the source and destination are the same object type.

### ISSUE THREAD

**Issue by mike-rowley** [AutoMapper/AutoMapper#3052]
I am using .ProjectToList<T>() in a generic type function, if I happen to want the same type the function is already working with (no conversion necessary) I get a System.InvalidOperationException.

Automapper 8.1.0
EF Core 2.2

### Expected behavior

I expect it not to throw an exception and give me the OrderTypes class back.

### Actual behavior

System.InvalidOperationException: 'Missing map from PaintSystems_Portal.Areas.OrderPad.Data.OrderTypes to PaintSystems_Portal.Areas.OrderPad.Data.OrderTypes. Create using Mapper.CreateMap<OrderTypes, OrderTypes>.'

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
