### ISSUE TITLE
InvalidCastException inheritance mapping with explicit destination

### ISSUE THREAD

**Issue by NinoFloris** [AutoMapper/AutoMapper#3054]
Automapper 8.1

Models and config:

```cs
class Animal { }
class AnimalDto { }  
class CatDto: AnimalDto { }

profile.CreateMap<Animal, AnimalDto>();
```

Automapper call: 
```cs
mapper.Map<CatDto>(new Animal());
```

Results in:
```cs
   An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'AnimalDto' to type 'CatDto'.
   at lambda_method(Closure , Comment , CommentModel , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 211
```

The 'fix' is to add `profile.CreateMap<Animal, CatDto>();`
Came across this ugly exception when a refactor inadvertently removed that mapping.

This should be a neatly formatted mapping exception instead right?

**Comment by lbargaoanu** [comment]
Maybe it could be :) A PR is welcome.

**Comment by NinoFloris** [comment]
@lbargaoanu question is, why does it try to map that input with an incompatible mapping function anyway?

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by NinoFloris** [comment]
Will do!
