### ISSUE TITLE
IgnoreMap attribute and Ignore expression result in different execution plans

### ISSUE THREAD

**Issue by tboby** [AutoMapper/AutoMapper#3055]
I'm trying to build a MCVE for a problem I'm having with ignored properties being mapped onto EF proxies. While working on that I ran into this confusing example where the plan is still being created for ignored properties.

Gist: https://gist.github.com/tboby/069c56a54b40dbea6d7651f79e90a9a1

### Source/destination types

```csharp
public class UserView {
	public int UserID {get; set;}
}
public class User {
	public int UserID { get; set; }
}

public class UserChild : User {
	
}

public class Case
{
// 1: Works
//	[IgnoreMap]
//
	public virtual User User {get; set;}
	public int? UserID {get; set;}
}

public class CaseView
{
	public UserView User {get; set;}
	public int? UserID {get; set;}
}
```

### Mapping configuration

```csharp
public class CaseProfile : Profile {
	public CaseProfile()
	{
		CreateMap<CaseView, Case>()
// 2 doesn't work
//			.ForMember(x => x.User, opts => opts.Ignore())
// 3 doesn't work
//			.ForMember(x => x.User, opts => opts.MapFrom(src => (User)null))
			.ForMember(x => x.UserID, opts => opts.MapFrom (src => src.User.UserID));
		CreateMap<UserView, User>();
	}
	
}
```
```csharp
	Mapper.Initialize(cfg =>
	{

		cfg.AddProfiles(new Profile[] { new CaseProfile()});
	});

```

### Expected behavior
0. The plan generated without any Ignores should map the User property
1. The plan generated with (1 - IgnoreMap) should not map User at all
2. The plan generated with (2 - Fluent ignore) should not map User at all (and should have the same map as 1?)
3. The plan generated with (3 - Set to null) should map to null

### Actual behavior

See gist for maps.
1. This plan correctly ignores User
2/3. These plans are unchanged to the plan without any ignores

The ignore behaviour seems to work fine when you actually map, but the plans don't seem to show the ignore behaviour. It seems very odd to me that it generates the subplan for mapping User when it should never use it.

Sorry if this is expected behaviour, but i'm trying to diagnose a more complicated problem and afaik the execution plan is the source of truth.

### Steps to reproduce
See gist, Comment out either 1, 2 or 3. Gist should work in Linqpad with Automapper 8.1.0 and ReadableExpressions

```csharp
	var configuration = new MapperConfiguration(cfg => cfg.CreateMap<CaseView, Case>());
	var executionPlan = configuration.BuildExecutionPlan(typeof(CaseView), typeof(Case));
	// Compare execution plans
	executionPlan.ToReadableString().Dump();
```

**Comment by lbargaoanu** [comment]
Everything seems ok to me. If you have a failing test, I'll take a look.

**Comment by tboby** [comment]
In the following gist: https://gist.github.com/tboby/72c77dee76ce5deda6de1c883f6a23d3

```
	// Compare execution plans
	// Either the plans are the same, and the values are the same:
	executionPlan.ShouldBe(executionPlan2);
	((int?)(result2?.User?.UserID)).ShouldBe((int?)(result1?.User.UserID));

	// Or the plans are different
	executionPlan.ShouldNotBe(executionPlan2);
```

For the following two profiles:
```
public class CaseProfileDefaultMap : Profile {
	public CaseProfileDefaultMap()
	{
		CreateMap<CaseView, Case>();
		CreateMap<UserView, User>();
	}
}


public class CaseProfileWithNull : Profile
{
	public CaseProfileWithNull()
	{
		CreateMap<CaseView, Case>()
			.ForMember(x => x.User, opts => opts.MapFrom(src => (User)null));
		CreateMap<UserView, User>();
	}
}
```

If the execution plans are identical, the behaviour should be the same?

**Comment by lbargaoanu** [comment]
Again, I don't see anything wrong. For help with your code please use StackOverflow. If the people there decide it's an AM issue, please come back here with a simple failing test.
