### ISSUE TITLE
MapFrom returns null when it calls a static method which has first parameter null

### ISSUE THREAD

**Issue by dvkudr** [AutoMapper/AutoMapper#3058]
### Link to sample code
https://github.com/dvkudr/AutoMapperIssue

### Source/destination types

```csharp
    class FirstName
    {
        public string Name;
    }

    class LastName
    {
        public string Name;
    }

    class FullName
    {
        public string Name;
    }

    class CombinedNames
    {
        public FirstName First;

        public LastName Last;
    }
```

### Mapping configuration

```csharp
            CreateMap<CombinedNames, FullName>()
                .ForMember(dst => dst.Name,
                           cfg => cfg.MapFrom(src => string.Concat(src.First.Name, " ", src.Last.Name)));
```

### Version: x.y.z
8.1.0

### Expected behavior

full.Name should be " Doe"

### Actual behavior

full.Name is null

### Steps to reproduce

```csharp
var combinedNames = new CombinedNames
            {
                First = new FirstName { Name = null },
                Last = new LastName { Name = "Doe" }
            };
var full = mapper.Map<FullName>(combinedNames)
```

**Comment by lbargaoanu** [comment]
As a workaround, use a Func based resolver.

**Comment by parys** [comment]
Faced with same issue when calling static method with null object as first param. Static method even not called.

` class FirstName
    {
        public string Name;
    }

    class LastName
    {
        public string Name;
    }

    class FullName
    {
        public string Name;
    }

    class CombinedNames
    {
        public FirstName First;

        public LastName Last;
    }

in mapperProfile:

private static string **StaticMethod**(string first, string last)
{
   return first + last;
}

CreateMap<CombinedNames, FullName>()
                .ForMember(dst => dst.Name,
                           cfg => cfg.MapFrom(src => **StaticMethod**(src.First.Name,  src.Last.Name)));`
