### ISSUE TITLE
Problem with sorting when using ProjectTo with EF Core and complex DTOs

### ISSUE THREAD

**Issue by stromsky** [AutoMapper/AutoMapper#3059]
I have following entity and DTO models:

### Source/destination types

```csharp
// entities
public class Record {
  public int Id {get;set;}
  public string Name {get;set;}
  public string Description {get;set;}
  public DateTime CreationTime {get;set;}
  public RecordType Type {get;set;}
}

public class RecordType {
  public int Id {get;set;}
  public string Name {get;set;}
  public string Description {get;set;}
}

// DTOs
public class RecordDto {
  public int Id {get;set;}
  public string Name {get;set;}
  public DateTime CreationTime {get;set;}
  public LookupDto Type {get;set;}
}
public class LookupDto {
  public int Id {get;set;}
  public string Name {get;set;}
}
```

### Mapping configuration

```csharp
CreateMap<Record, RecordDto>();
CreateMap<RecordType, LookupDto>();
```

### Expected behavior

When I use following projection
```csharp
Context.Records.ProjectTo<RecordDto>().OrderBy(x => x.Type.Name).Take(10).ToList();
```
I would expect that query will be execute in SQL server. 

### Actual behavior

Instead, only projection part is translated to SQL. Sorting and paging is done in memory. This is obviously a bug in EF Core (possibly this issue https://github.com/aspnet/EntityFrameworkCore/issues/13413 ). When I was investigating this problem, I've noticed this happens only when select expression contains If-Else condition and at the same time query is ordered by `x.Type.Name` sub-property. 

I was able to reproduce the problem even without AutoMapper when using following select:

```csharp
.Select(x => new RecordDto
{
  Id = x.Id,
  Name = x.Name,
  CreationTime = x.CreationTime,
  Type = x.Type == null ? null : new LookupDto
  {
    Id = x.Type.Id,
    Name = x.Type.Name
  }
})
```

Expression tree for this and what AutoMapper creates is the same. Problem lies in null-check ternary operator. When I remove it, entire query is translated to SQL correctly.

### Question:
Is it possible to somehow tell AutoMapper, that it does not have to (should not) use null-check in select expression, because FK is mandatory and `Type` property will never by NULL?

This will _probably_ be fixed in EF Core 3.0, but release date is pretty far in the future, so I am looking for any workaround that would work. 

Possible solution whould be to flatten the DTO structure. That is actually something I am trying to avoid since we use LookupDto class across entire system.

**Comment by lbargaoanu** [comment]
ForMember, AllowNull.
