### ISSUE TITLE
A way to check is mapper already initialized

### ISSUE THREAD

**Issue by maxkoshevoi** [AutoMapper/AutoMapper#3062]
Hi, I'm using AutoMapper in Xamarin Forms app, and as far as I can see, there is no way to initialize mapper exactly once since every part of the application could be called more then once (for example, even OnStart method could be called several times). 

### Expected behavior

It could be great if there was a way to check whether AutoMapper was initialized. For example, Mapper.IsInitialized property

### Actual behavior

For now I just going to wrap Mapper.Initialize(...) method in try...catch

**Comment by lbargaoanu** [comment]
I think this is more suited for a xamarin forum. But you can always not use the static mapper.

**Comment by maxkoshevoi** [comment]
Yes, but what am I suppose to do in situations like this (when I cannot guarantee that mapper will be initialized exactly once)? Don't use static mapper at all? It seems like Mapper.IsInitialized property wouldn't be hard to implement.

Moreover it will be useful in unit tests as seen here: https://stackoverflow.com/questions/48952525/how-do-i-know-if-automapper-has-already-been-initialized

**Comment by jbogard** [comment]
PR?

**Comment by lbargaoanu** [comment]
@jbogard A static property doesn't make much sense because of concurrency issue. A new method TryInitialize would work, but it seems trivial to implement that in user code. And about Xamarin, are you sure there is no init method or smth similar built in? I would be surprised :)

**Comment by lbargaoanu** [comment]
@maxkoshevoi Why would you use the static mapper? Use DI and inject an IMapper instance. Or create IMapper by hand. The static mapper exists mainly for backward compatibility.

**Comment by maxkoshevoi** [comment]
@lbargaoanu I didn't know static mapper exist for backward compatibility. Tutorials I found use it and I thought it was the right way. Maybe you should mark it with [Obsolete] attribute then.

**Comment by lbargaoanu** [comment]
I, for one, think it's a good idea.

**Comment by maxkoshevoi** [comment]
@lbargaoanu But it will take more time to initialize mapper each time I need to use it than initialize it once, won't it?

**Comment by lbargaoanu** [comment]
Nobody said that. You still should initialize it once.
