### ISSUE TITLE
AssertConfigurationIsValid does not fail when mapping from nullable type to non-nullable type

### ISSUE THREAD

**Issue by JoasE** [AutoMapper/AutoMapper#3071]
### Source/destination types

```csharp
public class Source
{
    public Guid? OptionalRelationId { get; set; }
}

public class Destination
{
    public Guid OptionalRelationId { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>();
```

### Expected behavior

`Mapper.AssertConfigurationIsValid();` throws an `AutoMapperConfigurationException`

### Actual behavior

The configuration is asserted to be valid.

### Steps to reproduce

```csharp
class Program
{
    static void Main(string[] args)
    {
        Mapper.Initialize(x => x.AddProfile<Mappings>());

        try
        {
            Mapper.AssertConfigurationIsValid(); // Does not throw
        }
        catch (AutoMapperConfigurationException e)
        {
            Console.WriteLine(e);
            throw;
        }
    }
}
```

**Comment by lbargaoanu** [comment]
That's by design. You can customize the configuration validation. Or create a map that throws.

**Comment by JoasE** [comment]
So the question you need to ask yourself here is: Is assigning `null` to a non-nullable property a valid configuration?

For me, the answer is pretty obvious.

This might be by design but it does not mean it isn't unexpected behavior, nor does it mean it should not be changed.

I'd like to see some more discussion on this subject than declaring the design objectively perfect and closing issues with that philosophy.

Why do you think trying to assigning `null` to a non-nullable property is a valid configuration?

**Comment by lbargaoanu** [comment]
But if you can have that by writing the code yourself, why not just do that? :)

**Comment by JoasE** [comment]
What I am trying to say is that I think it should be the default behavior, as IMO assigning null to a non-nullable property shouldn't be a valid configuration.

**Comment by lbargaoanu** [comment]
I think it's kind of late to be having this discussion as a lot of people already rely on this behavior.

**Comment by JoasE** [comment]
I understand this would be a breaking change, but 9.0.0 has got to release sometime. I think this would be a nice addition to the major release.

**Comment by lbargaoanu** [comment]
I disagree, I think the actual behavior fits with how AM works, trying to make the mapping work if there is a reasonable default. Most people want to ignore validations, not add new ones :) cc @jbogard

**Comment by JoasE** [comment]
Thank you for sharing your opinion on the subject @lbargaoanu . This response is something I could relate to and is something we can have a discussion about. 👍 

I'd like to hear @jbogard 's opinion on this.
If he agrees with this behavior fitting AM more I will trust you two to know what's best, even tho I disagree.

Following up, the `AssertConfigurationIsValid` also doesn't throw this case (which is different but similar):

```csharp
public class Source
{
    public Guid OptionalRelationId { get; set; }
}

public class Destination
{
    public int OptionalRelationId { get; set; }
}
```
Which I also think is not a valid configuration since there's no valid present mapping from `Guid` to `int`.

**To clarify my point of view: I think the `AssertConfigurationIsValid` does too little and its behavior should be changed.**

If someone made this mistake in a companies production code, I think they would want the unit test to fail.

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).
