### ISSUE TITLE
Mapper.Map(source, destination) maps to Enum default value instead of skipping if null

### ISSUE THREAD

**Issue by ms-lemos** [AutoMapper/AutoMapper#3074]
Hello there,

I'm using automapper to update an object values, merging two objects but only if the source member it's != null. 
Here you can find the example: https://gist.github.com/ms-lemos/ba48540c6bdb21b2582f7d5f9d1423da

The issue: It does not work with Enums. After calling MergeObject method, it maps to the enum default's value (Pending) instead of not mapping at all, because it's null. 

When debugging, if I set a breakpoint on the condition (member != null), it'll show member = Pending, even when Source.Status is null. 

### Steps to reproduce

1 - Initialize mapper on Global.asax 
2- Initialize one instance of ViewModel having Stauts = null; 
3- Initialize one instance of Model having e.g. Status = Completed 
4- Call MergeObject 
5- Model's Status will be set to Pending

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by ms-lemos** [comment]
It doesn't feel like I'm doing anything wrong, It seems like a bug to me, but to whom it may concern here it is: 
https://stackoverflow.com/questions/56081198/automapper-maps-to-enum-default-value-instead-of-skipping-if-null

**Comment by lbargaoanu** [comment]
You're not doing anything wrong. But this is well known behavior at this point. You'll just have to workaround it as many people already did.

**Comment by ms-lemos** [comment]
Oh... Okay. I couldn't find any workaround, maybe I'm searching it wrong? 
Do you have any workaround example?
