### ISSUE TITLE
.Net Core Preview 5 Issue

### ISSUE THREAD

**Issue by endeffects** [AutoMapper/AutoMapper#3076]
With the current .net core preview 5 i got an exception when building the automapper.

Exception

> InvalidOperationException: No constructor for type 'AutoMapper.Configuration.MapperConfigurationExpression+NamedProfile' can be instantiated using services from the service container and default values.

Startup

```
            services.AddScoped(e => e.GetRequiredService<MapperConfiguration>().CreateMapper());

            services.AddSingleton(e => new MapperConfiguration(c =>
            {
                foreach (var profile in e.GetServices<Profile>())
                {
                    c.AddProfile(profile);
                }
            }));
```

I also tried to use your extension, which fails too.

Exception

> InvalidOperationException: Unable to resolve service for type 'System.IO.DirectoryInfo' while attempting to activate 'Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository'.

Startup

`services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());`

Maybe this is not directly related to the automapper itself. But the question for me is, is there any plan to improve the wireup? Whouldn't it be easier if the MapperConfiguration resolves the profiles at runtime itself via constructor injection?

**Comment by lbargaoanu** [comment]
As it has been discussed many times before, profiles are singletons and allowing DI for them would be easily abused. Other than that, AM itself doesn't do DI, only the extension does. About the error itself, feel free to investigate.

**Comment by jbogard** [comment]
Also, we got rid of AppDomain scanning because of this reason. You should
explicitly tell AutoMapper where to look for Profiles.

**Comment by endeffects** [comment]
Thanks, but this doesn't work for me as well. The call that fails is:
`services.AddScoped(e => e.GetRequiredService<MapperConfiguration>().CreateMapper());`

I removed all the other "Profil-Adding" to confirm this.

**Comment by jbogard** [comment]
I think we’re missing a lot of context here. If you’re using the
AddAutoMapper extension, you don’t need that line below. You just pass in
the explicit assemblies to search for Profiles in, and you’re done.

**Comment by endeffects** [comment]
Yes, i know. I just tried to explain that i tried all samples available on your wiki.

**Comment by jbogard** [comment]
What samples did you try? Do you have a link?
