### ISSUE TITLE
Deadlock with dynamic mapping, two-way relation and concurrent call

### ISSUE THREAD

**Issue by MMG-Bas** [AutoMapper/AutoMapper#3077]
The follow issue occured in a very specific scenario and is easy to work around, but it seemed a good idea to post it anyway since it could lead to hard to track bugs.

The issue seems to be related to a combination of three factors:
- Types are dynamically mapped
- Mapped Types have a two-way relation
- First calls to map of both types are concurrent

The issue showed up in an ASP.NET Core application where two controllers were called concurrently and both had related mapping types. In the reproduction scenario below the issue has been minimized in a console setting.

### Source/destination types

```csharp
class OriginalA
{
    public OriginalB B { get; set; }
}

class OriginalB
{
    public OriginalA Parent { get; set; }
}

class TargetA
{
    public TargetB B { get; set; }
}

class TargetB
{
    public TargetA Parent { get; set; }
}
```

### Mapping configuration

```csharp
new MapperConfiguration(cfg => {
})
```

### Version: 8.1.1 (latest)
also verified on 8.0.0 and 8.1.0
 

### Expected behavior
Expected same behaviour as the non-concurrent case, or when mapping is explicitly defined, or when mapping was already determined by earlier calls

### Actual behavior
A deadlock occurred on all calls to Map and both `Task`s never end

### Steps to reproduce

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var config = new MapperConfiguration(cfg => {
        });
        Console.WriteLine("Starting");
        Task mappingATask = Task.Run(() =>
        {
            Console.WriteLine("start t1");
            var mapper = config.CreateMapper();
            var col = mapper.Map<IEnumerable<TargetA>>(Enumerable.Empty<OriginalA>());
            Console.WriteLine("end t1");
        });
        Task mappingBTask = Task.Run(() =>
        {
            Console.WriteLine("start t2");
            var mapper = config.CreateMapper();
            var col = mapper.Map<IEnumerable<TargetB>>(Enumerable.Empty<OriginalB>());
            Console.WriteLine("end t2");
        });

        await Task.WhenAll(mappingATask, mappingBTask);

        Console.WriteLine("End");
    }
}

class OriginalA
{
    public OriginalB B { get; set; }
}

class OriginalB
{
    public OriginalA Parent { get; set; }
}

class TargetA
{
    public TargetB B { get; set; }
}

class TargetB
{
    public TargetA Parent { get; set; }
}
```
Can also been seen in the following gist:
https://gist.github.com/MMG-Bas/a70f2577801b9700a9d23f8d85811873

**Comment by lbargaoanu** [comment]
See #3063. Dynamic mapping creates more problems than it solves.
