### ISSUE TITLE
ConstructUsing not working

### ISSUE THREAD

**Issue by BetimShala** [AutoMapper/AutoMapper#3078]
Hi there, I'm having trouble with ConstructUsing method. The field 'Thumbnail' is not changing even after resolving the context. Any suggesstion please?

`
 var command = Mapper.Map<CreateDeviceApp.Command>(model, opt =>
            {
                opt.Items["Thumbnail"] = uploadImageResponse.Uri;
            });
`

`
CreateMap<CreateDeviceAppViewModel, CreateDeviceApp.Command>().ConstructUsing((src, ctxt) => new CreateDeviceApp.Command() { Thumbnail = ctxt.Options.Items["Thumbnail"].ToString() });
`

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by BetimShala** [comment]
> I think this is better suited for StackOverflow.

I have posted also in StackOverflow, but I think that I have found where's the problem, the Thumbnail property is part of CreateDeviceApp.Command and also part of CreateDeviceAppViewModel so what's going on here is that the AutoMapper is ignoring the ConstructUsing method because it just mapped all the properties (including 'Thumbnail' property). 
@lbargaoanu What's your comment on this, do you think this is happening or maybe it be something else?

Thank you.
