### ISSUE TITLE
FlagsEnumMapper sometimes throws an exception

### ISSUE THREAD

**Issue by pdudnikov** [AutoMapper/AutoMapper#3079]
### Source/destination types

```csharp
public class A
{
	public Flag F { get; set; }
}

public class B
{
	public Flag F { get; set; }
}

[Flags]
public enum Flag
{
	O = 0,
	A = 1,
	B = 2
}
```

### Mapping configuration

```csharp
var mapper = new Mapper(new MapperConfiguration(config =>
{
	config.CreateMap<A, B>();
}));
```

### Version: 8.1.0
 
.net 4.6.2

### Expected behavior

Works as expected.

### Actual behavior

**Sometimes** exception is thrown
```csharp
System.ArgumentException: Incorrect number of arguments supplied for call to method 'System.String ToString(System.String, System.IFormatProvider)' at
System.Linq.Expressions.Expression.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis) at
System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments) at
System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments) at
AutoMapper.Mappers.FlagsEnumMapper.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, IMemberMap memberMap, Expression sourceExpression, Expression destExpression, Expression contextExpression) at
AutoMapper.Execution.ExpressionBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, IMemberMap propertyMap, Expression destinationParameter) at
...
```
### Steps to reproduce

The problem is in **FlagsEnumMapper**, namelly, in following call
```csharp
Call(sourceExpression, sourceExpression.Type.GetDeclaredMethod("ToString"))
```
GetDeclaredMethod calls extension method GetRuntimeMethods to get list of methods
```csharp
public static IEnumerable<MethodInfo> GetRuntimeMethods(this Type type)
{
   RuntimeReflectionExtensions.CheckAndThrow(type);
   return (IEnumerable<MethodInfo>) type.GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
}
```
GetMethods documentation https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=netframework-4.6.2
> The GetMethods method does not return methods in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which methods are returned, because that order varies.

So sometimes GetDeclaredMethod("ToString") returns other method than expected(e.g. ToString(string format, IFormatProvider provider) instead of ToString()) and 
 **Incorrect number of arguments supplied for call to method** exception is thrown.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by lbargaoanu** [comment]
This works for me on develop. So the idea here is that it fails only on .net 4.6.2?

**Comment by pdudnikov** [comment]
I'm not sure that it fails only on 4.6.2 or another version, I've got that exception only a few times - usually, all works fine
