### ISSUE TITLE
No se encuentra el paquete AutoMapper.Extensions.Microsoft.DependencyInjection

### ISSUE THREAD

**Issue by Robinl2018** [AutoMapper/AutoMapper#3081]
Hi, i'm trying to create a web api with Visual Studio Code, but when i try to add the package AutoMapper.Extensions.Microsoft.DependencyInjection i get this error:

error: No se encuentra el paquete AutoMapper.Extensions.Microsoft.DependencyInjection. No existe ningún paquete con este id. en los orígenes: Microsoft Visual Studio Offline Packages
error: El paquete "AutoMapper.Extensions.Microsoft.DependencyInjection" no es compatible con los marcos de trabajo de "all" del proyecto "C:\Robin\Fuentes\ASPNetApi\aspnetapi.csproj".

This is my aspnetapi.csproj

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.7" />
  </ItemGroup>

</Project>

The command that i am using is this: 
dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection -v 6.1.0

I´ve tried with all versión of the package, and with all of them i get the same error.

Thanks a lot

**Comment by Robinl2018** [comment]
This is my aspnetapi.csproj

![image](https://user-images.githubusercontent.com/39069169/57892517-d1688100-7804-11e9-87ae-615038df84c7.png)


This is the error:

![image](https://user-images.githubusercontent.com/39069169/57892531-da595280-7804-11e9-9eab-97de7e93ca45.png)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
