### ISSUE TITLE
Automapper Throws "Service Provider Disposed" Exception After Awaiting a Task

### ISSUE THREAD

**Issue by bleepzter** [AutoMapper/AutoMapper#3083]
I am using the following setup in a .NET Core MVC application which was recently upgraded from .NET Core 2.1 to .NET Core 2.2:

### Current Version (.NET Core 2.2):
**Dependencies**
.NET Core App 2.2.5
AutoMapper 8.1.0
AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.0

**Mapper Registration in Startup.cs:**
```csharp
services.AddAutoMapper(
  typeof(ViewModelsToEntitiesMappingProfile).GetTypeInfo().Assembly
);
```

### Old Version (.NET Core 2.1):
**Dependencies**
.NET Core APP 2.1.0
AutoMapper 7.1.0
AutoMapper.Extensions.Microsoft.DependencyInjection 5.1.0

**Mapper Registration in Startup.cs:**
```csharp
services.AddAutoMapper(x =>
  x.AddProfile<ViewModelsToEntitiesMappingProfile>();
  x.ValidateInlineMaps = false;
);
```

So the issue stems from awaiting a task. My controllers, each gets a service which is a wrapper for a bunch of creational logic. The service also gets an instance of IMapper injected into it as described in the sample code.

I won't bore you with the entity and the view model. Suffice to say that the mappings of those work and have been extensively unit tested. 

**The error occurs if a task is awaited. As soon as this happens, any subsequent calls to Mapper.Map<>() causes exceptions with a message stating that the underlying service provider has been disposed!**

Please help!

**Sample Service Injected Into a Controller**
```csharp

public interface ISampleService {
  Task<SampleViewModel> Create(SampleViewModel input);
}

public class SampleService : ISampleService {

  private readonly IMapper mapper; 
  private readonly ILogger<SampleService> logger;

  public SampleService(IMapper mapper, ILogger<SampleService> logger){
    this.mapper = mapper;
    this.logger = logger;
  }

  public async Task<SampleViewModel> Create(SampleViewModel input){
     //this call to Map works because it is before an await statement.
     var entity = this.mapper.Map<SampleEntity>(input);

     await Task.Delay(TimeSpan.FromSeconds(60));
     
     //--> error. This call to Map fails because the service provider used by the mapper 
     // gets disposed and the mapper throws exception. 
     // It only happens if an await has been called prior to a Map call.
     var entity = this.mapper.Map<SampleEntity>(input);      
  }
}
```

All of my controllers use the same service pattern. The service gets injected into the constructor using the ASP.NET Core's DI container and encapsulates business logic specific to each controller.

**Sample Controller**

```csharp
public class SampleController : Controller {

  private readonly ISampleService service;
  
  public SampleController(ISampleService service){
    this.service = service;
  }

  [HttpPost]
  public IActionResult Create([FromBody]SampleViewModel input){
     var result = await this.service.Create(input).ConfigureAwait(false);
     return Ok(result);
  }
}
```

**Comment by lbargaoanu** [comment]
That's a different repo.

**Comment by bleepzter** [comment]
Can you elaborate on the bug? What repo should this bug be reported to?
