### ISSUE TITLE
Issue when calling static method with null object as first param not invoked. StaticMethod not called during mapping. In case if moving 

### ISSUE THREAD

**Issue by parys** [AutoMapper/AutoMapper#3084]
Faced with same issue when calling static method with null object as first param. Static method even not called.

`class FullName
    {
        public string Name;
    }

    class CombinedNames
    {
        public string FirstName;

        public string LastName;
    }

//in mapperProfile:

private static string StaticMethod(string first, string last)
{
   return first + last;
}

//when firstName is null, mapping method will not be called. If first param is not null everything is fine.

CreateMap<CombinedNames, FullName>()
                .ForMember(dst => dst.Name,
                           cfg => cfg.MapFrom(src => StaticMethod(src.FirstName,  src.LastName)));`

_Originally posted by @parys in https://github.com/AutoMapper/AutoMapper/issues/3058#issuecomment-493661201_

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by parys** [comment]
@lbargaoanu yes, with this preRelease build (8.1.1-ci-01561) it works as expected now and worked before on 6.1.1.
