### ISSUE TITLE
Mapping configuration for readonly list properties got broken after upgrade from 8.0.0 to 8.1.0

### ISSUE THREAD

**Issue by greendimka** [AutoMapper/AutoMapper#3085]
After upgrade **from 8.0.0 to 8.1.0** my mappings for readonly list properties became broken.
[Here is the demo gist](https://gist.github.com/greendimka/4fa78aeb37938f46343cfd3e4cc1f028).
Minimal demo project: [https://github.com/greendimka/AutoMapper81_ListFail](https://github.com/greendimka/AutoMapper81_ListFail).
It works fine with 8.0.0 (output is "1|2|3") and does not work with 8.1.0 (output is ""). List property gets replaces with an empty list.

### Source/destination types

```csharp
// source/destination types

class SourceClass
{
	public SourceClass()
	{
		Vals = new List<int> { 1, 2, 3 };
	}

	public List<int> Vals { get; set; }
}

class TargetClass
{
	private List<int> _vals = new List<int>();

	public List<int> Vals => _vals;
}
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
c.CreateMap<SourceClass, TargetClass>()
	.ForMember(x => x.Vals, o => o.MapFrom((srcCls, trgCls) =>
	{
		trgCls.Vals.Clear();
		trgCls.Vals.AddRange(srcCls.Vals);
		return trgCls.Vals;
	}));
```

### Expected behavior

I expect trgCls.Vals to be filled with values from srcCls.Vals.

### Actual behavior

Actually trgCls.Vals gets filled but then it gets replaced with an empty list.

### Steps to reproduce

Simply run the code. Use AutoMapper 8.0.0 for the correct behavior. Use 8.1.0 for failing behavior.
Minimal running project (confgured with AutoMapper v8.0.0) may be obtained here: [https://github.com/greendimka/AutoMapper81_ListFail](https://github.com/greendimka/AutoMapper81_ListFail).

**Comment by lbargaoanu** [comment]
Yes, there were some changes here. You need
     
     c.CreateMap<SourceClass, TargetClass>().ForMember(x => x.Vals, o => o.MapFrom(s=>s.Vals));
