### ISSUE TITLE
Provide straightforward API for member convention

### ISSUE THREAD

**Issue by czmirek** [AutoMapper/AutoMapper#3086]
I want to use Automapper to convert DTOs to business models and the other way around.

My DTOs have uppercase names with underscores. Business models are pascal case.
DTOs are also prefixed with "T_".

Yes uppercase underscore properties are horrible but it's what I must work with.

```csharp
// DTO
public class T_ACCOUNT
{
    public int ID { get; set; }
    public int? PROFILE_ID { get; set; }
    public int DELETED { get; set; }
    public string EMAIL { get; set; }
    public int IS_EMAIL_CONFIRMED { get; set; }
    public DateTime TIME { get; set; }
}

// Business model
public class Account
{
    public AccountId Id { get; set; }
    public ProfileId? ProfileId { get; set; }
    public bool Deleted { get; set; }
    public string Email { get; set; }
    public bool IsEmailConfirmed { get; set; }
    public DateTime Time { get; set; }
}
```

I can't get it to work using the INamingConvention interface. The complete code is here if anyone would like to help me: https://github.com/czmirek/AutomapperConventionTest

This is a proposal to add some simpler API for member naming convention where at one end you get the property source name and you return the target name.

In my case, I'd simply use http://humanizr.net/ for conversions.
```csharp
    // For converting members from DTO to Bussiness models.
    AddMemberConfiguration()
                   .MapByName(sourceName => sourceName.Pascalize());

    // For converting members from Business models to DTO.
    AddMemberConfiguration()
                   .MapByName(sourceName => sourceName.Underscore().ToUpperInvariant());
```

**Comment by lbargaoanu** [comment]
Until then you have ForAllMaps and ForAllMembers, and you can try smth with those.

**Comment by lbargaoanu** [comment]
There is also an special API for prefixes.

**Comment by czmirek** [comment]
I tried `ForAllPropertyMaps` but the properties `int? PROFILE_ID` and `int IS_EMAIL_CONFIRMED` are for some reason ignored in the lambda for matching the properties.

https://github.com/czmirek/AutomapperConventionTest/blob/master/AutomapperConventionTest/test/DtoToBusinessProfile.cs

**Comment by lbargaoanu** [comment]
That won't work because a property map doesn't exist unless the properties match.

**Comment by czmirek** [comment]
Oh. So how would you do this then? Looking at `ForAllMaps` now.

I'm using this for matching the classes e.g. from "T_ACCOUNT" to "Account".

```csharp
AddConditionalObjectMapper()
                .Where((s, d) =>
                {
                    return s.Name == d.Name.Substring(2).Pascalize();
                });
```
Now I'd like to somehow say that for matching source to destination property, remove underscores and pascalize (or simply `string.Pascalize()` when using Humanizr).

How do I do this with ForAllMaps ... ?

```csharp
ForAllMaps((t, m) =>
{
    // ???
});
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. But you can look for examples in this repo to understand how those API work.

**Comment by czmirek** [comment]
Created.

https://stackoverflow.com/questions/56221446/automapper-definition-by-convention-without-explicit-createmap
