### ISSUE TITLE
Using base profile with generic + flattening: Only member accesses are allowed

### ISSUE THREAD

**Issue by kvloover** [AutoMapper/AutoMapper#3090]
### Source/destination types

```csharp
public interface IEntity<TId> : IEntity where TId : IEntityKey
{
TId Key {get;set;}
}

public interface IEntityKey
{
}

public class Entity : IEntity<EntityKey>
{
public EntityKey Key {get;set;}
public string Description {get;set;}
}

public class EntityKey : IEntityKey
{
public int Id {get;set;}
}

public class EntityModel 
{
public int Id {get;set;}
public string Description {get;set;}
}
```

### Mapping configuration

```csharp
    public class EntityProfile : EntityProfileBase<Entity, EntityKey, EntityModel>
    {
        public EntityProfile(): base()
        {
        }
    }

    public abstract class EntityProfileBase<Tent, Tkey, Tmodel> : Profile where Tent : IEntity<Tkey> where Tkey : IEntityKey
    {
        public EntityProfileBase()
        {
            CreateMap<Tkey, Tmodel>();
            CreateMap<Tent, Tmodel>().IncludeMembers(s => s.Key);

            CreateMap<Tmodel, Tent>()
                .ForMember(dest => dest.Key, member => member.MapFrom(src => src));
        }
    }
```

### Version: x.y.z
8.1.0

### Expected behavior
I have this entity + key setup on alot of classes due to a custom ORM I use. This is forcing me to create individual profiles for each case just to flatten the the entity into the model.

I used to flatten these manually with individual profiles. But I am trying to use the flatten mechanism with IncludeMembers to make a base profile I only have to inherit from.

The result should be that the model receives the 'Description' from the Entity and the 'Id' from the EntityKey on the Entity.

### Actual behavior

I've tested the mapping without the base profile. But when I use a base profile it throws an error on the IncludeMembers saying that "Only member accesses are allowed". However the Key is part of the entity. 

Is this a bug or is my methodology incorrect, if the latter what would be a correct way to avoid repeating too much code accross multiple entities ?

### Steps to reproduce

```csharp
var ent = new Entity() { Description = "Test", Key = new EntityKey() {Id = 1}};
Mapper.Map<EntityModel>(ent); 
```

**Comment by lbargaoanu** [comment]
You reuse configuration is with Include. Introduce a base class/interface for the destination, create a base map for it (use `IncludeMembers` for flattening) and include that in the derived maps. See http://docs.automapper.org/en/latest/Mapping-inheritance.html.

**Comment by kvloover** [comment]
I've tried that just now, but doing that with a generic does not allow the use of a lambda expression in the IncludeMembers. This means the key is not flattened. 

Would this even flatten into the end Entity if the flattened value (Id) is not in the base model ?
Basicly my Key object for a 'set' might be Id, but another might be called differently, it might even be more than one field (Its basicly the primary key fields of the database). It will always be matched with the fields (count + names) on the models though.

Base class:
```csharp
public class EntityModel : EntityModelBase
{
public int Id {get;set;}
public string Description {get;set;}
}

public class EntityModelBase { }
```

Base profile:
```csharp
    public class EntityProfileBase : Profile
    {
        public EntityProfileBase()
        {
            CreateMap<IEntityKey, EntityModel>();
            CreateMap(typeof(IEntity<>), typeof(EntityModelBase)).IncludeMembers(); // Lambda argument not found, only takes params
        }
    }
```

Instance profile:
```csharp
    public class EntityProfile : Profile
    {
        public EntityProfile()
        {
            CreateMap<Entity, EntityModel>()
             .IncludeBase(typeof(IEntity<>), typeof(EntityModelBase));
        }
    }
```

**Comment by lbargaoanu** [comment]
Yes, that's by design. Check the tests. Generic maps work with strings, not with lambdas. Your initial example would work that way. But it's weird. Not a use case we're interested in supporting. We have `Include` to reuse configuration. I understand that your destination might have keys with different names. But the whole thing seems needlessly complicated to me. So if you go that way and you really hit a roadblock, a PR is welcome. You're off the beaten path here.

**Comment by kvloover** [comment]
Ok, I'll have to live with the repeated code than for now. 
Thanks for the support 👍

**Comment by lbargaoanu** [comment]
So this works

    public EntityProfileBase()
    {
        CreateMap<Tkey, Tmodel>(MemberList.None);
        CreateMap(typeof(Tent), typeof(Tmodel)).IncludeMembers(nameof(IEntity<IEntityKey>.Key)).ReverseMap();
    }
But again, I'm not sure it's such a good idea :)
