### ISSUE TITLE
AutoMapper dll auto-deleted after I run my dotnetcore 2.2 API

### ISSUE THREAD

**Issue by wabixia** [AutoMapper/AutoMapper#3091]
When i use Dotnetcore 2.2 and AutoMapper dll AutoMapper.Extensions.Microsoft.DependencyInjection which version is 6.1.0  to create my web api project, then I run this application, my application delete this reference from my nuget package after running, my visual studio version is 2019, has anyone met this issue before? thanks.
![image](https://user-images.githubusercontent.com/35483536/58161578-15e79700-7cb3-11e9-8a88-a941080e6d86.png)
, if i don't run my application, the error would not occur.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
