### ISSUE TITLE
Ignore a property of nested object list

### ISSUE THREAD

**Issue by kodithuwa** [AutoMapper/AutoMapper#3092]
Hi,
Is it possible to ignore a property of  child object list?
I want to ignore UserPostComment  of UserPostCommentAttachments of below example.
Ex: 
Source Class
    public class UserPostComment : IEntity, IModifyStamp
    {
        public UserPostComment()
        {
            this.UserPostCommentAttachments = new List<UserPostCommentAttachment>();
        }
      
        public int Id{get;set;}
        public virtual UserPost UserPost { get; set; }
        public virtual ICollection<UserPostCommentAttachment> UserPostCommentAttachments { get; set; }
    }

Destination Class
 public UserPostComment()
        {
            this.UserPostCommentAttachments = new List<UserPostCommentAttachment>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }
        public ICollection<UserPostCommentAttachment> UserPostCommentAttachments { get; set; }

Nested Object Class
public class UserPostCommentAttachment
{
 public int? UserPostCommentId { get; set; }
  public UserPostComment UserPostComment { get; set; }
}

Thanks
Chaminda

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
