### ISSUE TITLE
Conditional inheritance with AutoMapper

### ISSUE THREAD

**Issue by aborderon** [AutoMapper/AutoMapper#3099]
Hello,

I have a small problem regarding the use conditional inheritance with AutoMapper in the DTO to Entity direction.

I have inheritance (TPH) between my entities, namely an abstract mother class "**ConnectorBaseEntity**".

And two children classes:
"**ConnectorOracleEntity**" and "**ConnectorMySQLEntity**"

To add a new connector, I go through a end point POST type that takes as parameter a "**ConnectorCreateDTO**" which contains all the properties of children.

I defined my mapping between my DTO and my classes like this:

```csharp
CreateMap<ConnectorCreateDTO, ConnectorBaseEntity>().As<ConnectorOracleEntity>();
CreateMap<ConnectorCreateDTO, ConnectorOracleEntity>();

CreateMap<ConnectorCreateDTO, ConnectorBaseEntity>().As<ConnectorMySQLEntity>();
CreateMap<ConnectorCreateDTO, ConnectorMySQLEntity>();
 ```

I use the "**As**" because my mother entity is abstract, I can not use it, so I use the derived type as a base.       

Then in my controller I map:

```csharp
_mapper.Map <ConnectorBaseEntity> (connectorCreateDTO)
 ```

The problem is that I do not know how to tell AutoMapper to use the right child based on the "**type**" property in my "ConnectorCreateDTO".

I have to make a big "if" or a "switch" to handle all the mapping cases in my controller?
```csharp
if(connectorCreateDTO.Type == ProviderTypeEnum.ORACLE){
       _mapper.Map<ConnectorOracleEntity>(connectorCreateDTO)
}
if(connectorCreateDTO.Type == ProviderTypeEnum.MYSQL){
       _mapper.Map<ConnectorMySQLEntity>(connectorCreateDTO)
}
 ```

Is there not a cleaner way to handle inheritance conditions directly in the map?

What do you recommend ?

Thank you.

### Version: 
AutoMapper 8.1.0
Pomelo.EntityFrameworkCore.MySql 2.2.0

**Comment by lbargaoanu** [comment]
There is nothing built in to help you with that. This has been discussed many times before, here and on SO. You'll have to choose one of the solutions people used before. If all you need is to create the destination object, `ConstructUsing` can help.

**Comment by aborderon** [comment]
Thank you for this orientation, I solved my problem with ConstrucUsing and a Factory.
