### ISSUE TITLE
byte to int error

### ISSUE THREAD

**Issue by xyfy** [AutoMapper/AutoMapper#3104]
I use AutoMapper.Data 2.0  & AutoMapper 7.0.1，and net framework 4.5
I have a property in my dest class, but the field in sqlserver has the type "tinyint".
``` 
  public int click{get;set;}
```

I try some code like below, it works. 
but when I remove the "ForMember "，I got an error: cast type error. 
I use the automapper source to debug it,  I found I got a [byte] value from datarecord.when try to set value to dest class. cast type error occur!
why [byte] cannot auto cast to [int]?
```
 var config = new MapperConfiguration(cfg =>
                {
                    cfg.AddDataReaderMapping();
                    cfg.CreateMissingTypeMaps = true;
                    cfg.CreateMap<IDataRecord, ModelWithFoundingGroup>()
                        .ForMember(dest => dest.click,
                            options => options.MapFrom(src =>
                                src.GetByte(src.GetOrdinal(nameof(ModelWithFoundingGroup.click)))))
                   
                });
                var mapper = config.CreateMapper();
                model = mapper.Map<IDataRecord, ModelWithFoundingGroup>(dataRecord);
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by xyfy** [comment]
int i = 1;
            byte m = 1;
            i = m;

the code above can work well.

why in automapper , it got a  cast type error?
