### ISSUE TITLE
ResolutionContext unavailable in IMappingAction

### ISSUE THREAD

**Issue by hallidev** [AutoMapper/AutoMapper#3105]
Consider the following .NET Core 2.2 Console App:

```
    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<SomePersonObject, SomeOtherPersonObject>()
                    .AfterMap<NameMeJohnAction>();
            });

            var bob = new SomePersonObject {Name = "Bob"};

            var mapper = config.CreateMapper();

            // I want the name "Pete" available in AfterMap
            var john = mapper.Map<SomeOtherPersonObject>(bob, opt => opt.Items["OverrideName"] = "Pete");
            
        }
    }

    public class SomePersonObject
    {
        public string Name { get; set; }
    }

    public class SomeOtherPersonObject
    {
        public string Name { get; set; }
    }

    public class NameMeJohnAction : IMappingAction<SomePersonObject, SomeOtherPersonObject>
    {
        public void Process(SomePersonObject source, SomeOtherPersonObject destination)
        {
            // I want to check "OverrideName" and change the name to "Pete", but I can't!
            destination.Name = "John";
        }
    }
```

### Version: x.y.z
AutoMapper 8.0+

### Expected behavior
Some way to access ResolutionContext in AfterMap

### Actual behavior
No way to access ResolutionContext in AfterMap

### Steps to reproduce
Paste above class into blank .NET Core Console App and run

**Comment by lbargaoanu** [comment]
A PR is welcome. Otherwise, you'll have to use a version of AfterMap that does receive the context.

**Comment by hallidev** [comment]
Is there currently a version of AfterMap that allows for DI as well as
ResolutionContext?

In my actual use case, I'm using DI but also need access to
ResolutionContext.

If not, I can try to put a PR together, but my initial thought is to add a
third parameter to IMappingAction.Process(), which would be a breaking
change to the interface. Any idea on how you'd want it to work?

**Comment by lbargaoanu** [comment]
Not that I'm aware of, but you can always workaround it. I don't think a breaking change is a good idea, but @jbogard might disagree. I would add a new interface that takes a structure as parameter. That structure would have as members all the parameters. The way the ForPath->Condition works. Then adding another parameter would not be a breaking change.

**Comment by jbogard** [comment]
Ugh, this was just an oversight really. I'm happy to take a PR, but it'd have to wait for the next major release.

**Comment by hallidev** [comment]
I've submitted a PR. Any suggestions for how to workaround this in the meantime? The whole AfterMap mechanic is ideal for my use case (rather than a customer Resolver), I just have no way to pass arguments via IMapper.Map(). I understand that my PR is a breaking change that will require a major version, so I'm just hoping to come up with something in the meantime, even if it's a hack.
