### ISSUE TITLE
Consider releasing 8.1.1

### ISSUE THREAD

**Issue by nphmuller** [AutoMapper/AutoMapper#3107]
Would you consider releasing version 8.1.1?
There are a couple of bugs which are fixed in dev, but haven't been released yet. (Personally waiting for https://github.com/AutoMapper/AutoMapper/issues/3095 and https://github.com/AutoMapper/AutoMapper/issues/3069)

Of course I can use the dev build in the meantime, but I'd prefer to use the NuGet packages. Especially since one of the bugs has been fixed about a month ago.

Sorry to be a bother :)

**Comment by lbargaoanu** [comment]
The way I see it, those are minor issues. But @jbogard will make a decision and reopen the issue if he needs a reminder.

**Comment by jbogard** [comment]
Sure, let's get one out.

**Comment by lbargaoanu** [comment]
@jbogard Don't forget to bump the version after release.

**Comment by jbogard** [comment]
@lbargaoanu will bump to 9.0 so we can start our new breakages.

**Comment by lbargaoanu** [comment]
Cool :)

**Comment by nphmuller** [comment]
Thanks. And looking forward to the breakages! 
Always disabled CreateMissingTypeMaps etc. anyway.

**Comment by jbogard** [comment]
Done https://github.com/AutoMapper/AutoMapper/releases/tag/v8.1.1
