### ISSUE TITLE
Access property setter in IValueResolver

### ISSUE THREAD

**Issue by twsouthwick** [AutoMapper/AutoMapper#3108]
I'm looking at supporting async operations in custom resolvers and have it working in the type converter. However, the `IValueResolver<,,>` doesn't support a way to set the property after the fact (ie asynchronously). Is there a way to access a method similar to what was on `ResolutionResult.Context.PropertyMap.DestinationProperty.SetValue(property, value)`? If that were available, an async wrapper can sit on top of AutoMapper very nicely (at least the scenarios I'm interested in).

**Comment by lbargaoanu** [comment]
If you want to use reflection to set properties, I think you'd better off writing your own thing. You don't have much use for AM. But here it is
https://github.com/AutoMapper/AutoMapper/blob/2084b1af4c62061734a0339c1b25ecdf97a786a1/src/AutoMapper/IMemberConfigurationExpression.cs#L186

**Comment by twsouthwick** [comment]
I want to be able to defer setting the property and would rather not use reflection. AM already handles setting the value, and would prefer to use the same mechanism so I'm not mucking about with my own reflection/expressions. Is this possible?

**Comment by lbargaoanu** [comment]
Once the Map call exits, AM is out of the picture, so I'm not sure how could AM help here.

**Comment by twsouthwick** [comment]
In my scenario, the actual setting of the property needs to be done at some point in the future (the Task for this can be managed and controlled outside of AM). The thing I'm looking for is a method that allows setting the property so when the async call is completed, I can set it. I could create this myself, but since AM has already done so (I am assuming it's doing some expression/ref-emit magic to make property setting efficient) and I'm utilizing the AM infrastructure, I'm hoping I won't have to duplicate it.

So, the ask is if there is a way to access an efficient property setter that can be used to set the property value or if I need to manage that myself.

**Comment by lbargaoanu** [comment]
I'm sure you could use some part of what we do, but you'd have to look into that yourself, there is no API for that.

**Comment by twsouthwick** [comment]
Ok. Thanks for the help. I'll see what I can find :)
