### ISSUE TITLE
Global solution for managing nullable types

### ISSUE THREAD

**Issue by jasenf** [AutoMapper/AutoMapper#3109]
Using v8.1  I still can't find a consistent simple way to deal with nullable types in the source object.   If a source property is nullable its almost always because it was optional.  Which means if it isn't supplied we shouldn't be overriding an existing value.  However, Automapper's default preference is to use the default value -- and I get at this point you don't want that changed, but feel this isn't typical in a real-world situation.  Some much better documentation on how to override this default behavior would be great.
 
I have seen limited documentation and have read a ton of threads but nothing is clear or coplete and none of the solutions seem to be working.

This:

```
class Source {
   int? price { get; set; }
}

class Destination {
   int price { get;set; }
}

CreateMap<Source, Destination>()
     .ForAllMembers(o => o.Condition((source, destination, member) => 
              (member != null) ));
```

is not sufficient as it only deals with null values, not nullable types.   I'm a little dumbfounded as to the  difficulty of finding the answer on this one as I would think it would be needed almost all the time when passing optional Dto properties.   

Any specific directions (instead of links that half answer the problem) would be incredibly appreciated. 

thank you,
jasen

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jasenf** [comment]
Well I also think its a documentation issue, but StackOverflow didn't provide any help..

https://stackoverflow.com/questions/56383615/how-do-we-ignore-source-properties-of-nullable-types-such-as-int

**Comment by jbogard** [comment]
It's not an easy problem to solve, unfortunately, and is quite application-specific.

The most obvious "default" is `dest.Value = src.Value ?? default(T)` instead of `dest.Value = src.Value ?? dest.Value`.

If we wanted 1st class support for this switching behavior, we'd have to have some global/profile setting, similar to `AllowNullCollections`.

**Comment by jbogard** [comment]
Also, conditions are problematic since they're not supported in `ProjectTo`. The only way we'd really be able to support this is to have a switch in the expression generation.

**Comment by jasenf** [comment]
I know Automapper has a TON of great use cases, but converting Dto view objects to entity objects is a pretty common one and nullable types to make properties optional are pretty much how they are used.  

If we can do this per-property:

```
  CreateMap<MyDto, MyEntity>()
                .ForMember(d => d.MyNullableProperty, y => y.MapFrom((s,d) => 
                    s.MyNullableProperty.HasValue? s.MyNullableProperty: d.MyNullableProperty
                ));
```
I just would have thought there should be a way to say do this for all Nullable types globally.

**Comment by jbogard** [comment]
Your function is specific to a single property. It's one thing to build a single function for a single property, supporting this globally and generically is something else altogether.

**Comment by jasenf** [comment]
So basically that line has to be replicated for every optional (nullable) property across all our Dto's.  Ugh.

Thanks for the quick response guys.  Appreciated.

**Comment by jbogard** [comment]
You can also open a new issue for a feature request, if you like.
