### ISSUE TITLE
ProjectTo() -> Expression of type cannot be used for constructor parameter of type 

### ISSUE THREAD

**Issue by pfaustinopt** [AutoMapper/AutoMapper#3110]
### Source/destination types

```csharp
public class A
{
   public int? i { get; set; }
}

public class B
{	
   public int i { get; set; }

   public B (int i)
   {
      this.i = i;
   }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<A, B>();
```

### Version
Automapper: 6.2.2.0
EFCore: 2.2.4.0

### Expected behavior
`var b = list.AsQueryable().ProjectTo<B>(mapper.ConfigurationProvider).First();` should have the same result as `var b = mapper.Map<B>(a);`, 

### Actual behavior
`ProjectTo()` is throwing the following exception, while `mapper.Map` is working as expected:
> ArgumentException
> Expression of type 'System.Nullable`1[System.Int32]' cannot be used for constructor parameter of type 'System.Int32'

### Steps to reproduce

```csharp
void Main()
{
   var mapperConfiguration = new MapperConfiguration(cfg =>
   {
      cfg.CreateMap<A, B>();
    });
	
   var mapper = mapperConfiguration.CreateMapper();
	
   A a = new A{ i = 5};
   var list = new List<A>{a};
   var b = list.AsQueryable().ProjectTo<B>(mapper.ConfigurationProvider).First();
   b.Dump();
}
```

**Comment by pfaustinopt** [comment]
A possible solution is to use `DisableConstructorMapping()` and create a parameterless constructor on `B`.

Example:
```
var mapperConfiguration = new MapperConfiguration(cfg =>
{
   cfg.DisableConstructorMapping();
   cfg.CreateMap<A, B>();
});
```

```
public class B
{	
   public int i { get; set; }

   private B() { }

   public B (int i)
   {
      this.i = i;
   }
}
```

Is this the only way to solve this problem?

**Comment by lbargaoanu** [comment]
EF6, our main use case, doesn't support constructor mapping. So it's no surprise things don't work. But if you want to look into it, a PR is welcome.

**Comment by pfaustinopt** [comment]
In this case I'm not even using EF since I'm just doing `list.AsQueryable()`, so this shouldn't be related to the fact that EF doest not support constructor mapping, right?

**Comment by lbargaoanu** [comment]
ProjectTo is not some generic expression mapping mechanism. It's mainly a way to write SQL queries with EF6. Which reminds me, you might want to try expression mapping.

**Comment by pfaustinopt** [comment]
You mean using `opt.MapFrom()`?

**Comment by lbargaoanu** [comment]
Expression mapping was moved to a different [repo](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping).

**Comment by jbogard** [comment]
@pfaustinopt `ProjectTo` builds LINQ select projection to pass to a query provider.

Going the `AsQueryable().ProjectTo()` is incredibly wasteful because there is no "query provider" for in-memory per se, instead it does a lousy compilation and tries to map at runtime.

We build up expression trees and compile them in a much more efficient manner than `AsQueryable` would. Don't use `AsQueryable` unless you *know* the underlying enumerable is already a query provider.

**Comment by pfaustinopt** [comment]
I was just using `AsQueryable` for test purposes (I was testing my mappings using Linq). 

My use case is with EF Core, but I was wasting too much time between modifying the mappings and compiling the changes (I'm working on a quite big project). 

@jbogard is there any other way besides `DisableConstructorMapping()` to achieve what I'm attempting?

**Comment by jbogard** [comment]
Remove the constructor :)

EF Core won't support that query, so we can't either. Try without AutoMapper using just `Select` to see what's actually possible.
