### ISSUE TITLE
Link to demo in Getting Started goes to a 403 page

### ISSUE THREAD

**Issue by akeeton** [AutoMapper/AutoMapper#3111]
The link at https://github.com/AutoMapper/AutoMapper/blame/6c15a867861d579427c76a6529ee8d3dbff3aa74/docs/Getting-started.md#L63, http://www.dnrtv.com/default.aspx?showNum=155, goes to a 403 page.

**Comment by lbargaoanu** [comment]
I guess we should delete that link. A PR is welcome.
