### ISSUE TITLE
afterthe nuget package upgrade to 8.1.1, it appears "Mapper.Initialize  outmoded", seems cant use the static to Initialize

### ISSUE THREAD

**Issue by WenRuonan** [AutoMapper/AutoMapper#3113]
How can I fix the codes in 8.1.1 with the static Initialize, thanks.
public class AutoMapperConfig
    {
        static AutoMapperConfig()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Domain.Entities.OrderRoot, IApp.DTO.OrderRoot>(); 
            });
        }
    }

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by WenRuonan** [comment]
but the warning appeared after upgrading the 'AutoMapper' to 8.1.1, 
and maybe it is  from the upgrade change about 'Obsolete Mapper.Initialize #3082' for the warning with  [Obsolete("Switch to the instance based API, preferably using dependency injection. See http://docs.automapper.org/en/latest/Static-and-Instance-API.html and http://docs.automapper.org/en/latest/Dependency-injection.html.")]

**Comment by lbargaoanu** [comment]
Well yes, and if you don't want to follow that advice, don't upgrade. But how you use the instance based API is well known at this point so if you need assistance with that, SO is the place to be.

**Comment by TheSoulsKing** [comment]
You should do the following:
```
var cfg = new MapperConfigurationExpression();
cfg.CreateMap<Domain.Entities.OrderRoot, IApp.DTO.OrderRoot>();
Mapper.Initialize(cfg);

```
Hope it helps you.

**Comment by vasicvuk** [comment]
You should document this change since this is not a Major version update. Also the documentation still talks about static configuration. 

Anyway what is the main reason for Obsoleting the Static configuration?

**Comment by jbogard** [comment]
In any case, it’s gone in the next release.

**Comment by vasicvuk** [comment]
Obsolete is gone or static configuration is gone. Where is the document describing why this is done?

**Comment by jbogard** [comment]
#3135

**Comment by vasicvuk** [comment]
Still no answer why it should not be used

**Comment by jbogard** [comment]
Because it’s static.

https://lostechies.com/jimmybogard/2016/01/21/removing-the-static-api-from-automapper/
