### ISSUE TITLE
Register ValueResolver with Parameterized Constructor (Service as a parameter)

### ISSUE THREAD

**Issue by keerthimaryala18** [AutoMapper/AutoMapper#3114]
I have a custom IMemberValueResolver in my .NET Core 2.2 App that takes in a service and translates the source member to the destination member. 

    public class ContentResolver : IMemberValueResolver<object, object, string, string>
    {
        private readonly ITranslationService _translationService;
        public ContentResolver(ITranslationService translationService)
        {
            _translationService = translationService;
        }
        public string Resolve(Object source, object destination, string srcMember, string destMember, 
       ResolutionContext context)
        {
            return _translationService.GetTranslation(srcMember);
        }
    }

I use this in the mapper profile

`
.ForMember(destination => destination.StatusDescription,
                    options => options.MapFrom<ContentResolver, string>(src => src.Status));
`

I create a mapper and register the Profiles and ValueResolvers using the MapperConfiguration
               
              protected override void RegisterDependencies(ContainerBuilder containerBuilder)
              {
                    var mapperConfiguration = new MapperConfiguration(configuration =>
                    {
                        configuration.ConstructServicesUsing(componentContext.Resolve);
                        configuration.AddProfiles(assemblies.Select(assembly => assembly.FullName));
                    });

                    containerBuilder.RegisterInstance(mapperConfiguration).As<MapperConfiguration>().SingleInstance();

                var valueResolvers = assemblies.SelectMany(
                    assembly => assembly.GetTypes().Where(type => type.IsClass && !type.IsAbstract && type.IsClosedTypeOf(typeof(IMemberValueResolver<,,,>)))
                );

                foreach (var valueResolver in valueResolvers)
                {
                    containerBuilder.RegisterType(valueResolver)
                        .AsSelf()
                        .AsImplementedInterfaces();
                }
           }

The Custom Resolver doesn't get called and the reason is it is unable to resolve the service DI. How can I register this in the startup? If I remove the service from the resolver, I can see the Resolver being called. I need to use this service in the Resolver

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Dependency-injection.html#asp-net-core
