### ISSUE TITLE
Unable to map identical types without CreateMap/Profile in 8.1.1

### ISSUE THREAD

**Issue by NickBarrett** [AutoMapper/AutoMapper#3115]
First off, thanks for AutoMapper and all the time and effort spent developing and maintaining it.

I have an issue which seems related to #3112. I'm afraid I'm too green to know though.

### Source/destination types

```csharp
class BusinessClass // Source
{
    public int MyProperty { get; set; }
}

class ApiClass // Destination
{
    public int MyProperty { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg => { });
var mapper = config.CreateMapper();
```

### Expected behavior

```csharp
var apiClass = mapper.Map<ApiClass>(new BusinessClass() { MyProperty = 1 });
```
I expected that the above code would have returned an ApiClass with MyProperty == 1

### Actual behavior

Calling the above code throws AutoMapper.AutoMapperMappingException with the message 'Missing type map configuration or unsupported mapping.'

### Steps to reproduce

```csharp
using AutoMapper;

namespace ConsoleApp1
{
    class BusinessClass
    {
        public int MyProperty { get; set; }
    }

    class ApiClass
    {
        public int MyProperty { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg => { });
            var mapper = config.CreateMapper();

            var apiClass = mapper.Map<ApiClass>(new BusinessClass() { MyProperty = 1 });
        }
    }
}
```

### Solution

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<BusinessClass, ApiClass>();
});
```

The solution is to explicitly declare the map between the two types as above.
This hasn't been the case in earlier versions of AutoMapper. Is this the way it will be from 8.1.1 onward?

Thanks again =)

**Comment by jbogard** [comment]
Yeah with 8.1.1 you have to turn on dynamic maps. Warning though, we’re
obsoleting this behavior and will remove it in 9.0.

**Comment by NickBarrett** [comment]
All good. We'll switch to explicitly declaring all mappings as we update our project dependencies over time.

Thanks again =)
