### ISSUE TITLE
AllowNullCollections not honored by context.Mapper

### ISSUE THREAD

**Issue by MathiasRonnblom** [AutoMapper/AutoMapper#3116]
### Note
This might be related to #3057

### Source/destination types

```csharp
    public class Main
    {
        public Main(IEnumerable<Sub> subs)
        {
            Subs = subs;
        }

        public IEnumerable<Sub> Subs { get; }
    }

    public class Sub { }

    public class MainDto
    {
        public IEnumerable<SubDto> Subs { get; set; }
    }

    public class SubDto { }
```

### Mapping configuration

```csharp
    public class MyMappingProfile : Profile
    {
        public MyMappingProfile()
        {
            AllowNullCollections = true;

            CreateMap<SubDto, Sub>()
                .ConvertUsing((source, dest, context) =>
                {
                    return new Sub();
                });

            CreateMap<MainDto, Main>()
                .ConvertUsing((source, dest, context) =>
                {
                    return new Main(
                        context.Mapper.Map<IEnumerable<Sub>>(source.Subs)
                        );
                });
        }
    }
```

### Expected behavior

main.Subs should be null after mapping, since AllowNullCollections is true. Works with 8.0.0.

### Actual behavior

main.Subs is an empty list.

### Steps to reproduce

```csharp
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile<MyMappingProfile>());
            IMapper mapper = new Mapper(configuration);

            var dto = new MainDto();
            Assert.IsNull(dto.Subs);

            var main = mapper.Map<Main>(dto);

            Assert.IsNull(main.Subs);
        }
    }
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build. But also, the mapping itself is kind of weird. Constructor mapping would fit better.

**Comment by lbargaoanu** [comment]
But there is no new commit since 8.1.1, are you sure this is the right test?

**Comment by lbargaoanu** [comment]
OK, so this doesn't really work the way you want in 8.0. It just returns null whenever the source is null. I find that arbitrary (historical reasons probably), so I, for one, am not interested in adding another special case. Now, as for the expectation that you're inside a profile and the settings should apply to the context.Mapper call, that's more of a feature request. It doesn't seem obvious to me how that would be implemented. It does work by default with constructor mapping because we are careful to maintain this context when calling Map at each step. So I would go that way. cc @jbogard

**Comment by MathiasRonnblom** [comment]
@lbargaoanu No, I want it to work as I configure it.

If I configure my Profile with:
AllowNullCollections = false
I would expect all instances of IMapper, including context.Mapper, to honor that, and return an empty list given a null IEnumerable.

If I configure my Profile with:
AllowNullCollections = true
I would expect all instances of IMapper, including context.Mapper, to honor that, and return null given a null IEnumerable.

It feels both unintuitive and unpredictable if context.Mapper uses the CreateMaps from my Profile, but not the AllowNullCollections (and other) configs from the same Profile! If context.Mapper didn't use my Profile _at all_, maybe this would be an acceptable behavior, but using _a part of_ my Profile is not, IMHO.

**Comment by lbargaoanu** [comment]
It doesn't and it never did. Making the context.Mapper behave as the built in mapping is not simple. That's why it's better to avoid it if you can. And you can in this case.

**Comment by MathiasRonnblom** [comment]
@lbargaoanu I see. That is unfortunate.

How would this example look if using constructor mapping instead?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Construction.html

**Comment by MathiasRonnblom** [comment]
@lbargaoanu I tried constructor mapping, but it does not seem to work for constructor parameters with a default value (they always become the default). Is there any way around that?


```
    public class Main
    {
        public Main(IEnumerable<Sub> subs = null)
        {
            Subs = subs;
        }

        public IEnumerable<Sub> Subs { get; }
    }

    public class Sub
    {
        public Sub(int id = 0)
        {
            if (id == 0)
            {
                throw new ArgumentException("Invalid id.");
            }

            Id = id;
        }

        public int Id { get; }
    }

    public class MainDto
    {
        public IEnumerable<SubDto> Subs { get; set; }
    }

    public class SubDto
    {
        public int Id { get; set; }
    }

    public class MyMappingProfile : Profile
    {
        public MyMappingProfile()
        {
            AllowNullCollections = true;

            CreateMap<SubDto, Sub>();
            CreateMap<MainDto, Main>();
        }
    }

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void MapNullCollectionToNull()
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile<MyMappingProfile>());
            IMapper mapper = new Mapper(configuration);

            var dto = new MainDto();
            Assert.IsNull(dto.Subs);

            var main = mapper.Map<Main>(dto);

            Assert.IsNull(main.Subs);
        }

        [TestMethod]
        public void MapEmptyCollectionToEmpty()
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile<MyMappingProfile>());
            IMapper mapper = new Mapper(configuration);

            var dto = new MainDto();
            dto.Subs = new List<SubDto>();
            Assert.IsNotNull(dto.Subs);
            Assert.IsFalse(dto.Subs.Any());

            var main = mapper.Map<Main>(dto);

            Assert.IsNotNull(main.Subs);
            Assert.IsFalse(main.Subs.Any());
        }

        [TestMethod]
        public void MapNonEmptyCollectionToNonEmptyCollection()
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile<MyMappingProfile>());
            IMapper mapper = new Mapper(configuration);

            var dto = new MainDto();
            dto.Subs = new List<SubDto>
            {
                new SubDto { Id = 3 }
            };

            Assert.IsNotNull(dto.Subs);
            Assert.AreEqual(1, dto.Subs.Count());

            var main = mapper.Map<Main>(dto);

            Assert.IsNotNull(main.Subs);
            Assert.AreEqual(1, main.Subs.Count());
            Assert.AreEqual(3, main.Subs.Single().Id);
        }
```

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by lbargaoanu** [comment]
Apparently someone wanted this behavior, so default values take priority. You can have two contructors instead.

**Comment by MathiasRonnblom** [comment]
I thought I would summarize how I ended up solving this, for any others with the same issue. Also, I do believe that the AutoMapper documentation should include a BIG WARNING that context.Mapper behaves differently than the "normal" IMapper instance.

Replacing optional parameters with extra constructors might work if you only have one or two parameters. We have more, so that wasn't an option for us.
Also, constructor mapping feels a bit unpredictable to me. In a DDD solution, I want to be 100% sure that my domain objects cannot be created without running all validation - which is in the constructor.

So, I instead kept the existing mapping (ConvertUsing and context.Mapper) but wrote an extension method that returns null for empty IEnumerables. For the simplified example above, this would become:

```
    public class MyMappingProfile : Profile
    {
        public MyMappingProfile()
        {
            AllowNullCollections = true;

            CreateMap<SubDto, Sub>()
                .ConvertUsing((source, dest, context) =>
                {
                    return new Sub();
                });

            CreateMap<MainDto, Main>()
                .ConvertUsing((source, dest, context) =>
                {
                    return new Main(
                        context.Mapper.Map<IEnumerable<Sub>>(source.Subs).ValueOrNull()
                        );
                });
        }
    }

-----

public static IEnumerable<T> ValueOrNull<T>(this IEnumerable<T> enumerable)
{
	return enumerable.HasElements() ? enumerable : null;
}

public static bool HasElements<T>(this IEnumerable<T> enumerable)
{
	if (enumerable == null)
	{
		return false;
	}

	return enumerable.Any();
}

```

**Comment by lbargaoanu** [comment]
AM will have to choose some constructor. But by having default parameters, you're in fact saying that's a valid way to construct your object. So, while I agree this behavior is a little weird, maybe your constructor design is not exactly right.
