### ISSUE TITLE
Breaking changes in between minor version updates

### ISSUE THREAD

**Issue by gingters** [AutoMapper/AutoMapper#3117]
Hi there,

I just wanted to bring your attention to something:
In between AutoMapper 8.0.0 and 8.1.0 you introduced a _breaking_ change.

To be specific, the IdentityServer4.EntityFramework package references AutoMapper 8.0.0, and uses this code to initialize a mapper: 
```
CreateMap<Entities.Client, Models.Client>()
   .ForMember(dest => dest.ProtocolType, opt => opt.Condition(srs => srs != null))
   .ReverseMap();
```

See also full source: https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/Mappers/ClientMapperProfile.cs

Now, I consume that package, and also use AutoMapper, and by default NuGet installs 8.1.1.

Now, the mentioned IdSrv code breaks at runtime with this Exception:
```
MissingMethodException: Method not found: 'AutoMapper.IMappingExpression`2<!0,!1> AutoMapper.IMappingExpression`2.ConstructUsing(System.Linq.Expressions.Expression`1<System.Func`2<!0,!1>>)'.
```

I have to downgrade my project to AutoMapper 8.0.0 and can't update to 8.1.0 unless IdentityServer also ships new packages that update to AutoMapper 8.1.

**Request**:
I know that maintaining open source projects is hard, and changing stuff is necessary.
But *please* stick to semantic versioning. If you have to introduce these kinds of breaking changes, please bump the major version.

AutoMapper is a project that is used a lot, and chances are, that I take a dependency onto something that already depends on AutoMapper. Now, if I update the package within the same major (8.0.0 to 8.1.0), I honestly expect new features to be added only, and not old ones to be broken.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by gingters** [comment]
Simply create a project referencing IdentityServer3.EntityFramework, make that same project reference AutoMapper 8.1.x and then make the static ctor of `IdentityServer4.EntityFramework.Mappers.ClientMappers` execute. This will be enough.

**Comment by lbargaoanu** [comment]
Ok, your point is noted. I'm guessing you already solved your issue.

**Comment by gingters** [comment]
This issue cannot be solved. It's impossible.
You can't unpublish 8.1.x and re-publish the packages reverting the breaking change.

Thus we are forced to stick to 8.0.0 and from now on every time we update our dependencies we must make sure not to update AutoMapper unless the dependent package updates too.

This is the same baseline as #3112 was: It really is no good to introduce breaking and/or behaviour changes in minor or even bugfix updates.

@jbogard **Pretty please** make sure to bump majors when you introduce breaking changes.

We already discussed similar issues in between 6.x.x bugfix updates, where an argument type of a public method call changed (actually was made broader to accept more types), but that still broke at runtime for precompiled assemblies from nuget packages as the method with the old signature was completely removed. Also from 6.0 to 6.1 the ReverseMap behaviour changed and caused a lot of issues with a lot of people.

These are just a few examples of a lot of issues that are completely avoidable by bumping the major version. 

When upgrading to a new major version you expect breaking changes. When upgrading a minor version you only expect new features to come up (and maybe get a few new non-breaking(!) compiler warnings for newly obsolete-attributed methods/properties), and you certainly do not expect anything to go sideways when updating to a new bugfix release.

**Comment by lbargaoanu** [comment]
The default PackageReference means >=8.0, so it will always use a higher version, even 11.0. This has little to do with semantic versioning. It's your job to ensure that all the projects in your solution will work with the version resolved in the end. That's just your everyday dependencies problem.

**Comment by jbogard** [comment]
@gingters I try, but things slip through. I don't have an automated way to handle this. I'm open to ideas.

🤷‍♂ 

Behavior changes aren't covered by SemVer, though. Just API-level things.

**Comment by lbargaoanu** [comment]
@jbogard This is in fact an API change, just a subtle one :) Moving things from the derived interface to the new base interface broke code referencing the existing interface. I guess what we want is to run the tests of the previous release using the new AM version. But I'm not sure how to do that.

**Comment by Tasteful** [comment]
The behavior changes is hard to catch by a tool but API changes can easily be found and by example 
https://github.com/aspnet/BuildTools/wiki/Api-Check (nuget downloaded from https://dotnet.myget.org/feed/aspnetcore-tools/package/nuget/Microsoft.AspNetCore.BuildTools.ApiCheck) that will make comparison files and will track with json-files in each project the baseline and changes.

**Comment by lbargaoanu** [comment]
So where is that used? I get a 404 when I follow the link.

**Comment by SimonCropp** [comment]
there is also this https://github.com/JakeGinnivan/ApiApprover  which helps u visualize you api changes and their impact
