### ISSUE TITLE
AssertConfigurationIsValid does not handle ForCtorParam with 8.1.1

### ISSUE THREAD

**Issue by danstur** [AutoMapper/AutoMapper#3119]
It seems a bug was introduced with version 8.1.1 (the same code works fine with 8.1.0) for the `AssertConfigurationIsValid` functionality when dealing with `ForCtorParam`.

### Source/destination types

```csharp
public sealed class Source
{
}

public sealed class Destination
{
	public Destination(int foo)
	{
		Foo = foo;
	}
	public int Foo { get; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => cfg.AddProfile<FooProfile>());
		
public sealed class FooProfile : Profile
{
	public FooProfile()
	{
		CreateMap<Source, Destination>()
			.ForCtorParam("foo", x => x.MapFrom(src => 5));
	}
}
```

### Expected behavior
No exception should be thrown by `AssertConfigurationIsValid` for the given configuration.

### Actual behavior
The following exception is thrown:
```
AutoMapper.AutoMapperConfigurationException
The following member on TestProject.Destination cannot be mapped: 
	TestProject.Destination.Void .ctor(Int32).parameter foo 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type TestProject.Destination.
Context:
	Mapping to member TestProject.Destination.Void .ctor(Int32).parameter foo from TestProject.Source to TestProject.Destination
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
   at TestProject.Tests.Test()
```

This seems to only affect the validation, the runtime correctly handles the case as with 8.0.

### Steps to reproduce

```csharp
Mapper.AssertConfigurationIsValid();
```

Without having debugged it, the ConfigurationValidator class was changed for 8.1.1 with this [commit](https://github.com/AutoMapper/AutoMapper/commit/123134c5056140a90d77a7fc8d88d3e2d4a038c2#diff-48dfb17d7a85c9ce795680ae844ce186).

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by danstur** [comment]
So the problem isn't that something was broken during refactoring, but that additional checks were built-in with 8.1.1 and this case wasn't considered? 

Seems reasonably easy to fix, I might just give it a try tomorrow if I find time.

**Comment by jbogard** [comment]
Yep, I’m actually running into this when trying to rip out dynamic maps.

**Comment by lbargaoanu** [comment]
Seems related to https://github.com/AutoMapper/AutoMapper/issues/2745.

**Comment by lbargaoanu** [comment]
As a workaround, you can simply use ConstructUsing.
