### ISSUE TITLE
Problem with mapping if the maps are in separate classes

### ISSUE THREAD

**Issue by Tomaszczubaszek** [AutoMapper/AutoMapper#3125]
AutoMapper versions: 8.1.1
The previous version worked!

Let's look at the code below:

```
    public class A
    {
        public int P1 { get; set; }
    }

    public class B
    {
        public int P1 { get; set; }
    }

    public class C
    {
        public List<A> List { get; set; }
    }

    public class D
    {
        public List<B> List { get; set; }
    }

    public sealed class C_To_D : MapperConfigurationExpression
    {
        public C_To_D()
        {
             // ↓ it would work ↓
            //CreateMap<A, B>()
            //    .ForMember(_ => _.P1, _ => _.MapFrom(v => v.P1));

            CreateMap<C, D>()
                .ForMember(_ => _.List, _ => _.MapFrom(v => v.List));
        }
    }

    public sealed class A_To_B : MapperConfigurationExpression
    {
        public A_To_B()
        {
             // ↓ it does not work ↓
            CreateMap<A, B>()
                .ForMember(_ => _.P1, _ => _.MapFrom(v => v.P1));
        }
    }
```
If the map from A to B is in a separate class then:

**Message: AutoMapper.AutoMapperConfigurationException : The following member on ...D cannot be mapped: 
	List 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type ...D.
Context:
	Mapping to member List from ...C to ...D
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.**

The project is so large that it is impossible to have maps in this way. Please help.

**Comment by jbogard** [comment]
Why are your classes inheriting from `MapperConfigurationExpression`? That's the class that performs configuration once for the entire mapper.

Typically you use `Profile` classes to segregate configuration.

**Comment by Tomaszczubaszek** [comment]
Thanks, correcting this solves the problem.
