### ISSUE TITLE
Bug: unable to convert from IDataReader to List<POCO> in v8.1.1

### ISSUE THREAD

**Issue by roblugt** [AutoMapper/AutoMapper#3131]
### Source/destination types

```csharp
  SqlDataReader
```

### Mapping configuration

```csharp
			var config = new MapperConfiguration(cfg =>
			{
				cfg.AddDataReaderMapping();
			});

			config.AssertConfigurationIsValid();
			return config.CreateMapper();
```

### Version: 8.1.1
AutoMapper.Data 3.0.0
.Net Framework 4.6.1
 

### Expected behavior

When using AutoMapper.Data it should be possible to map from an IDataReader to a list of C# objects without any further mapping required.

This works in version 8.0.0 but throws an exception in v8.1.1

### Actual behavior

Exception thrown: 

AutoMapper.AutoMapperMappingException
 Message=Error mapping types.

Inner Exception:
Missing type map configuration or unsupported mapping.
Mapping types: IDataRecord -> POCO

### Steps to reproduce

```csharp
var sqlReader = GetDatabaseObjects();
var pocos = mapper.map<List<POCO>>(sqlReader)

// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
That's a different repo.

**Comment by roblugt** [comment]
> That's a different repo.

What is? Do you mean the error is in AutoMapper.Data?  How can you be sure?  And are you also saying that a minor version change in AutoMapper can break other components?
