### ISSUE TITLE
ProjectTo failing with self-relationship

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#3132]
EF Core Mapping problem:

I have a class Event that has a property Parent. Basically Events form a hierarchy. This is normally limited (2-3 levels deep), so loading them all is not a problem.

    public class Event : IIdentityEntity
    {

        [Key]
        public Guid Identity { get; set; }

        public Int32 Id { get; set; }

        public Event Parent { get; set; }

    }

There obviously are a lot more data properties, but I leave them out as they are not relevant here. I load them with EF Core from tables with funny naming ;)

The 1:1 mapping from Event to the parent works, which is confirmed by a direct test:

                var incidents = await repository.OBTIncident
                    .Include(x => x.OBTIncident_FkParentID)
                    .Where(x => x.OBTIncident_FkParentID != null)
                    .ToArrayAsync();

I have this in a unit test and this will get all events (in their OBTIncident table) that have a parent. Works like a charm.

Now, I try to do the same with the events that are going through mapping.

I pull them through my standard generic mapping code:

                        var query = Repository.Set<T>()
                            // No tracking. 
                            .AsNoTracking()
                            .ProjectTo<P>(EmptyParams, includes)
                        ;

and the includes include the "Parent" property.

In my event mappings I ahve defined:

            CreateMap<Data.Core.OBTIncident, Api.Odata.Event>()
               .ForMember(d => d.Identity, o => o.MapFrom(s => s.GIdentity))
               .ForMember(d => d.Id, o => o.MapFrom(s => s.PkIncidentID))
               .ForMember(d => d.Parent, o => { o.MapFrom(s => s.OBTIncident_FkParentID);  o.ExplicitExpansion(); })                
               .ForAllOtherMembers(o => o.Ignore())

I look at the generated  SQL and there is no attempt to load the parent - and parents are not loaded in the output.

I have a ton of other mappings in this project, which work perfectly. I ahve a TON of relationships, and they ALSO work perfect. This is the only one failing - and it is also the only self-reference (i.e. all other relationships go between different mapped classes, i.e. x -> a, x->b->a, not x->parentwhichisx)

A look at the geneated expression:

.Call System.Linq.Queryable.Select(
    .Call Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking(.Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.OBTIncident]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Data.Core.OBTIncident]))
    ,
    '(.Lambda #Lambda1<System.Func`2[Data.Core.OBTIncident,Api.Odata.Event]>))

.Lambda #Lambda1<System.Func`2[Data.Core.OBTIncident,Api.Odata.Event]>(Data.Core.OBTIncident $dtoOBTIncident) {
    .New Api.Odata.Event(){
        Id = $dtoOBTIncident.PkIncidentID,
        Identity = $dtoOBTIncident.GIdentity,
    }
}

shows (I removed all data properties except id and identity) that parent is simply not mapped at all to the output.

**Comment by lbargaoanu** [comment]
Write a LINQ statement that does what you want.

**Comment by NetTecture** [comment]
You mean "do not use automapper"? Yeah, looks like an idea.

See, the whole problem is that we DO write linq statements in front of automapper, but they do not make it throug hthe project to.

                var incidents = await repository.OBTIncident
                    .ProjectTo<OdataApi.Event>(new Dictionary<String, Object>(), "Parent")
                    .Where(x=>x.Parent != null)
                    .ToArrayAsync();

is the direct simple way and it results in this SQL:

SELECT [dtoOBTIncident].[dCreateDate] AS [Created], [dtoOBTIncident].[pkIncidentID] AS [Id], [dtoOBTIncident].[gIdentity] AS [Identity]
FROM [dbo].[OB_TIncident] AS [dtoOBTIncident]

The including parent and the filter are simply removed.

**Comment by lbargaoanu** [comment]
No, I mean just that. Forget about AM and write a LINQ query that does what you want. Once you've done that and that query returns the correct data, we can see how you can write that with ProjectTo.

**Comment by NetTecture** [comment]
Already done that?

            var incidents = await repository.OBTIncident
                .Include(x => x.OBTIncident_FkParentID)
                .Where(x => x.OBTIncident_FkParentID != null)
                .ToArrayAsync();

from the first code example in my original post.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by NetTecture** [comment]
Really? So, even with a fully repro you would say "ok, just swallowing queries is not a bug because hey, it works in any other case, so there is no chance this is a bug". See.

**Comment by lbargaoanu** [comment]
It seems to me like you don't understand the problem you're trying to solve. And that's alright, but SO is the place for this kind of questions.

**Comment by NetTecture** [comment]
Given how many obvious bugs are closed as questions, and how many open bugs this apparently perfect product has - ever considered a logical disability?

Let me give you a full unit test for that in the next days.
