### ISSUE TITLE
TFS throws "AutoMapper.pdb Symbol indexes could not be retrieved."

### ISSUE THREAD

**Issue by namrastanov** [AutoMapper/AutoMapper#3133]
Error on TFS build.

### Version: 8.1.0
package id="AutoMapper" version="8.1.0" targetFramework="net461"

### Expected behavior
No errors

### Actual behavior
TFS build error:
Indexed source information could not be retrieved from 
bin\Release\AutoMapper.pdb'. Symbol indexes could not be retrieved.

### Steps to reproduce
Class library project with .net 4.6.1
TFS build throws error.

**Comment by lbargaoanu** [comment]
Probably because we have portable pdb-s. I don't think those work so well on 4.6.1. A PR is welcome.
