### ISSUE TITLE
“MemberList.Source” not throwing exception when it should

### ISSUE THREAD

**Issue by hakankurcenlivivense** [AutoMapper/AutoMapper#3137]
I have the following models:

    public class A
    {
        public int a1;
        public int a2;
        public int a3;
        public int a4;
        public B b;
    }

    public class B
    {
        public int b1;
        public int b2;
        public C c;
    }

    public class C
    {
        public int c1;
        public int c2;
    }

    public class A_DTO
    {
        public int a1;
        public int a2;
        public int a3;
        public B_DTO b;
    }

    public class B_DTO
    {
        public int b1x;
        public int b2;
        public C_DTO c;
    }

    public class C_DTO
    {
        public int c1;
    }

And here are my objectives:

 1. Map each member in source to the member in destination with the same name (including inheritance)
 2. Create custom map for A.b.b1 --> A_DTO.b.b1x
 3. Explicitly say that there is no mapping for A.b.c.c2
 4. If there is an unmapped property in source that is not explicitly mapped AND cannot be mapped based on same name, throw exception

And here is the configuration I am using for that:

            var config = new MapperConfiguration(
                cfg => {
                    cfg.CreateMap<A, A_DTO>(MemberList.Source);
                    cfg.CreateMap<B, B_DTO>(MemberList.Source)
                    .ForMember(dest => dest.b1x, opt => opt.MapFrom(src => src.b1));
                    cfg.CreateMap<C, C_DTO>(MemberList.Source)
                    .ForSourceMember(src => src.c2, opt => opt.DoNotValidate());
                }
            );

And here is the test data I used:

            var mapper = config.CreateMapper();
            A a = new A()
            {
                a1 = 1,
                a2 = 2,
                a3 = 3,
                a4 = 10,
                b = new B
                {
                    b1 = 4,
                    b2 = 5,
                    c = new C
                    {
                        c1 = 6,
                        c2 = 7
                    }
                }
            };

            A_DTO aDto = new A_DTO();

            mapper.Map(a, aDto);

This meets all the conditions I listed above except the last one because `a4` does not exist on `A_DTO` and I still do not get an exception. (Whereas if I remove `.ForSourceMember(src => src.c2, opt => opt.DoNotValidate())`, it does throw exception for `c2`.)

**Comment by lbargaoanu** [comment]
Let'c continue on SO.
