### ISSUE TITLE
Ignore certain members mapping if object was created with ConstructUsing

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [AutoMapper/AutoMapper#3139]
It's not clear for me if I should use ConstructUsing() together with ForMember().
It's seems like i have to do something like this:
`CreateMap<AddFeedbackCommand, SetDataValueCommand>()`
`.ConstructUsing(x => new SetDataValueCommand($"{cfg.prefix}{Guid.NewGuid()}", JsonConvert.SerializeObject(x as FeedbackElement)))`
`.ForMember(x => x.Key, o => o.MapFrom(e => $"{cfg.prefix}{Guid.NewGuid()}"))`
`.ForMember(x => x.Value, o => o.MapFrom(e => JsonConvert.SerializeObject(e as FeedbackElement)));`
But as I understand AutoMapper doesnt know which property was mapped from ctor and will process mapping again. 
Feels like there must be some method in IMemberConfigurationExpression to ignore mapping if used ctor in first place. Am I wrong?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Construction.html

**Comment by CaCTuCaTu4ECKuu** [comment]
@lbargaoanu Correct me if I wrong.
Proper way is to use private parameterless constructor and map fields with `ForMember()`?

**Comment by lbargaoanu** [comment]
If you want to map through that constructor, the link explains how. ConstructUsing is more of a last resort thing. But if you map through constructors, it doesn't make much sense to use property mapping for the same members. It's confusing. So you can make the properties read only or use ConvertUsing instead, if all the properties are mapped through the constructor. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).
