### ISSUE TITLE
Circular References Problem

### ISSUE THREAD

**Issue by bahadirarslan** [AutoMapper/AutoMapper#314]
Hi,

I have got some EF models like below
public class Model {
public int ModelID {get;set;}
public virtual IEnumerable<ModelProperty> ModelProperties {get;set;}
}
public class ModelProperty
{
public int ModelPropertyID {get; set;}
public virtual Model Model {get; set;}
public int ModelID {get;set;}
}
and DTO models like below 
public class ModelInfo {
public int ModelID {get;set;}
public IEnumerable<ModelPropertyInfo> ModelProperties {get;set;}
}
public class ModelPropertyInfo
{
public int ModelPropertyID {get; set;}
public virtual ModelInfo Model {get; set;}
public int ModelID {get;set;}
}

EF Lazy Loading is enabled so after i query ModelProperty from DB i give it to Autommapper and convert to Info versions. But Automapper digs into the end until OutOfMemory exception occurs. 

Because there is no end in this model, i am using ModelProperty collection and Model property in both of Info classses. But i couldn't find a way to keep from endless loop.

Original question can be found here.
http://stackoverflow.com/questions/15455866/entity-framework-5-cyclic-lazy-loading-cause-outofmemoryexception

**Comment by sjoerd222888** [comment]
@jbogard: Overloading Equals with what? Comparing Ids?
