### ISSUE TITLE
PreserveReference with IEqualityComparer

### ISSUE THREAD

**Issue by DaRochaRomain** [AutoMapper/AutoMapper#3143]
Do you think it is possible, in the future, to be able to specify an equalitycomparer to the PreserveReference method, in order to specify automapper how to compare object in the InstanceCache?

**Comment by lbargaoanu** [comment]
Try it with `ConstructUsing`. If you find an equal object there, you return that one, otherwise you create a new one. That should stop the recursion.

**Comment by DaRochaRomain** [comment]
My issue, doing that, is that even though I can access the InstanceCache and their ContextCacheKey, I can't access the object inside since the **_source** field is private.

**Comment by lbargaoanu** [comment]
I don't think making it public is a problem. You can open a PR. But the instance cache is an implementation detail. So you depend on it on your own risk. This might not seem a big deal now, but you might think differently some time in the future :) You can always have your own dictionary using `Context.Items`.

**Comment by DaRochaRomain** [comment]
Context.Items doesn't seem to be cleared after each Mapper.Map call when I tried. I don't know if it's intended or not but it was kinda problematic for me.

I would like to do and think differently, but my i'm depending on the third library that didn't implement the Equals method for most of their class, even though they all have an id.

I'll try to open a PR once I find the time for it 😄

**Comment by lbargaoanu** [comment]
You have to use an overload that takes `Action<IMappingOperation>`. It should have reported an error.

**Comment by DaRochaRomain** [comment]
Sorry to bother you again, but when can I expect a nugget package update with the fix?

**Comment by lbargaoanu** [comment]
cc @jbogard

**Comment by jbogard** [comment]
@DaRochaRomain all commits to master are on the CI nuget feed. See the readme.

**Comment by DaRochaRomain** [comment]
@jbogard I can't find my change with the 9.0.0-ci-01581 version on the myget feed. Is it because the last build failed with my PR : https://ci.appveyor.com/project/jbogard/automapper/branch/master

**Comment by DaRochaRomain** [comment]
@lbargaoanu @jbogard could you restart the build and package generation?
