### ISSUE TITLE
Documentation: Add concrete example to the ASP.NET Core dependency injection with the types.

### ISSUE THREAD

**Issue by SeppPenner** [AutoMapper/AutoMapper#3146]
I would add a concrete example to the https://automapper.readthedocs.io/en/latest/Dependency-injection.html#asp-net-core section with marker types.

Current:
> or marker types:
> `services.AddAutoMapper(type1, type2 /*, ...*/);`

Changed:
> or marker types:
> `services.AddAutoMapper(type1, type2 /*, ...*/);`
> Example:
> `services.AddAutoMapper(typeof(YourDto), typeof(WhateverDto) /*, ...*/);`

or similar to state that you need to use `typeof` to get this working with custom types.

**Comment by lbargaoanu** [comment]
I don't know :) I mean what you need is a type object from the right assembly. `typeof` is just one way to get such a type. Also, it can be any type, not necessarily a DTO type. So I'm not sure how useful is that. But you can open a PR and @jbogard will merge it if he feels it's useful.

**Comment by SeppPenner** [comment]
> I don't know :) I mean what you need is a type object from the right assembly. `typeof` is just one way to get such a type. Also, it can be any type, not necessarily a DTO type. So I'm not sure how useful is that. But you can open a PR and @jbogard will merge it if he feels it's useful.

You can also use `.GetType()` of course^^

**Comment by jbogard** [comment]
I dunno, whatever is most explicit? Maybe not "DTO" though, maybe
"TypeFromAssemblyA", "TypeFromAssemblyB" etc.

**Comment by SeppPenner** [comment]
@jbogard I have changed this according to your proposals.
