### ISSUE TITLE
about reset

### ISSUE THREAD

**Issue by samchenws** [AutoMapper/AutoMapper#3152]
hello,I use this code 
  public static T MapTo<T>(this object obj)
        {
            Mapper.Reset();
            if (obj == null) return default(T);
            Mapper.Initialize(x => x.CreateMap(obj.GetType(), typeof(T)));
            return Mapper.Map<T>(obj);
        }
in the Quartz task 
![image](https://user-images.githubusercontent.com/37535153/60416292-09d6e980-9c10-11e9-98e4-8f0fde3f29b2.png)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
