### ISSUE TITLE
AutoMapperMappingException is thrown when mapping generic classes

### ISSUE THREAD

**Issue by ebejko** [AutoMapper/AutoMapper#3155]
### Source/destination types

```csharp
public class User
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class UserViewModel
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class Result<T>
{
	public int Reference { get; set; }
	public T Model { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(cfg =>
{
	cfg.CreateMap<User, UserViewModel>();
});
```

### Expected behavior

No exception to be thrown

### Actual behavior

Exception is thrown after upgrading from 8.1.0 to 8.1.1

### Steps to reproduce

```csharp
var source = new Result<User>
{
	Reference = 1,
	Model = new User { Id = 5, Name = "Marco" }
};

var target = mapper.Map<Result<UserViewModel>>(source);
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by ebejko** [comment]
Not trying to argue here but it's a breaking change coming from a patch (everything worked fine in 8.1.0). One would not expect breaking changes from such updates.

**Comment by lbargaoanu** [comment]
And the result would be not upgrading. You can always do that.

**Comment by ebejko** [comment]
Is the project following semantic versioning or the numbers are just random?
