### ISSUE TITLE
[Feature request] GRPC setting

### ISSUE THREAD

**Issue by bigbak** [AutoMapper/AutoMapper#3157]
Just a cheeky couple.

Is it possible to have a setting to say the target class is a GRPC Tools generated one?

Two things I've had to do when mapping from an object to GRPC ones are:

- Strings can't be Null in the GRPC target.  This requires adding lots of .ForMember(dest => dest.Postcode, opt => opt.NullSubstitute("")) to ensure it doesn't raise an exception

- The repeated items are generated as a type of RepeatedField<T>. This prevents the lists being populated without adding something like the following;
                .AfterMap((src, dest, context) =>
                {
                    foreach(var item in src.Items)
                    {
                        dest.Items.Add(context.Mapper.Map<AddressItem>(item));
                    }
                });

Not the end of the world if not. It looks less elegant than other AutoMapper code,

**Comment by lbargaoanu** [comment]
You'll have to implement that yourself.

**Comment by bigbak** [comment]
Ok.
GRPC is new for .net core 3 so I didn’t think it was unreasonable.

**Comment by jbogard** [comment]
Maybe a separate package? I dunno what all would be involved but if it’s
types specific to Core 3 then a separate package might be best.
