### ISSUE TITLE
MapFrom doesn't resolve constructor parameters that have no matching source property

### ISSUE THREAD

**Issue by spydacarnage** [AutoMapper/AutoMapper#3159]
Re-opening issue #2745 with additional details.

### Source/destination types

```csharp
public class Source
{
    public string Result { get; }

    public Source(string result)
    {
        Result = result;
    }
}

public class Dest
{
    public string Result{ get; }
    public dynamic Details { get; }

    public Dest(string result, DestInner1 inner1)
    {
        Result = result;
        Details = inner1;
    }
    public Dest(string result, DestInner2 inner2)
    {
        Result = result;
        Details = inner2;
    }

    public class DestInner1
    {
        public int Value { get; }

        public DestInner1(int value)
        {
            Value = value;
        }
    }

    public class DestInner2
    {
        public int Value { get; }

        public DestInner2(int value)
        {
            Value = value;
        }
    }
}
```

### Mapping configuration

```csharp
protected override MapperConfiguration Configuration { get; } = new MapperConfiguration(config =>
{
    config.CreateMap<Source, Dest>()
        .ForCtorParam("inner2", cfg => cfg.MapFrom(_ => new Dest.DestInner2(100)));
});
```

### Expected behavior

Destination.Details should contain an instance of DestInner2.

### Actual behavior

AutoMapper.AutoMapperConfigurationException: 'Dest does not have a constructor with a parameter named 'inner2'.

### Steps to reproduce

```csharp
public void Should_redirect_value()
{
    var dest = Mapper.Map<Source, Dest>(new Source("Success"));

    dest.ShouldNotBeNull();
}
```

I have been looking into this issue, and following the comments in #2745, I added a dummy "inner2" parameter to the `Source` object, which causes `MapDestinationPropertyToSource` in `TypeMapFactory` to pass.

However, because `Dest` has two constructors, one accepting an instance of `inner1` and the other `inner2`, I would need to have both dummy parameters in `Source`.

Unfortunately, due to the way that constructor mapping is achieved, the first constructor always passes, so it always hits the "cannot find a constructor with parameter 'inner2'" error.

I note that the previous person to report this was asked to submit a PR last August and hasn't done so, so I have looked into it myself.  I have a working prototype, but I don't know the codebase anywhere near well enough to know if I'm missing things.

All existing tests still pass, as does the one I have added to Constructor.cs.

Any assistance would be appreciated.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by spydacarnage** [comment]
No change.  Without the workaround properties, it works for "inner2" but not "inner1"; with the workaround properties, it works for "inner1" but not "inner2".

**Comment by lbargaoanu** [comment]
I've executed the code you posted and it works for me. So write smth I can execute and assert _exactly_ what doesn't work.

**Comment by spydacarnage** [comment]
As I've downloaded the MyGet build into my main project (as opposed to running this against the source), so I've had to rewrite the tests slightly (I'm using xUnit), but they still achieve the same goals.  I've included all 4 possible scenarios - going from the original Source to Destination1 and 2, and then from the SourceWithWorkaround (the dummy properties) to Destination1 and 2.  Tests `Source_to_Destination_2` and `Workaround_to_Destination_1` work, the other two don't.

```
public class AutoMapperTest
{
	public class Source
	{
		public string Result { get; }

		public Source(string result)
		{
			Result = result;
		}
	}
	public class SourceWithWorkaround
	{
		public string Result { get; }
		public object Inner1 => null;
		public object Inner2 => null;

		public SourceWithWorkaround(string result)
		{
			Result = result;
		}
	}

	public class Dest
	{
		public string Result { get; }
		public dynamic Details { get; }

		public Dest(string result, DestInner1 inner1)
		{
			Result = result;
			Details = inner1;
		}
		public Dest(string result, DestInner2 inner2)
		{
			Result = result;
			Details = inner2;
		}

		public class DestInner1
		{
			public int Value { get; }

			public DestInner1(int value)
			{
				Value = value;
			}
		}

		public class DestInner2
		{
			public int Value { get; }

			public DestInner2(int value)
			{
				Value = value;
			}
		}
	}

	[Fact]
	public void Source_to_Destination_1()
	{
		var mapperConfig = new MapperConfiguration(config =>
		{
			config.CreateMap<Source, Dest>().ForCtorParam("inner1", cfg => cfg.MapFrom(_ => new Dest.DestInner1(100)));
		});
		IMapper mapper = mapperConfig.CreateMapper();
		var dest = mapper.Map<Dest>(new Source("Success"));

		Assert.Equal(typeof(Dest.DestInner1).FullName, dest.Details.GetType().FullName);
	}

	[Fact]
	public void Source_to_Destination_2()
	{
		var mapperConfig = new MapperConfiguration(config =>
		{
			config.CreateMap<Source, Dest>().ForCtorParam("inner2", cfg => cfg.MapFrom(_ => new Dest.DestInner2(100)));
		});
		IMapper mapper = mapperConfig.CreateMapper();
		var dest = mapper.Map<Dest>(new Source("Success"));

		Assert.Equal(typeof(Dest.DestInner2).FullName, dest.Details.GetType().FullName);
	}

	[Fact]
	public void Workaround_to_Destination_1()
	{
		var mapperConfig = new MapperConfiguration(config =>
		{
			config.CreateMap<SourceWithWorkaround, Dest>().ForCtorParam("inner1", cfg => cfg.MapFrom(_ => new Dest.DestInner1(100)));
		});
		IMapper mapper = mapperConfig.CreateMapper();
		var dest = mapper.Map<Dest>(new SourceWithWorkaround("Success"));

		Assert.Equal(typeof(Dest.DestInner1).FullName, dest.Details.GetType().FullName);
	}

	[Fact]
	public void Workaround_to_Destination_2()
	{
		var mapperConfig = new MapperConfiguration(config =>
		{
			config.CreateMap<SourceWithWorkaround, Dest>().ForCtorParam("inner2", cfg => cfg.MapFrom(_ => new Dest.DestInner2(100)));
		});
		IMapper mapper = mapperConfig.CreateMapper();
		var dest = mapper.Map<Dest>(new SourceWithWorkaround("Success"));

		Assert.Equal(typeof(Dest.DestInner2).FullName, dest.Details.GetType().FullName);
	}
}
```

**Comment by lbargaoanu** [comment]
OK, I see the failing tests. The Dest constructor doesn't match, but you want to say that you have ForCtorParam and now it should match. Isn't it simpler to just use ConstructUsing?

**Comment by spydacarnage** [comment]
Unfortunately, this two-property constructor is a highly simplified version of the actual code to demonstrate what is failing - the full version is much longer, and if I wanted to manually write the full constructor, I could just run the constructor directly.

In the original issue, you suggested that code could be added to the `TypeMapFactory` class to fix this problem - is that not still the case?  I mean, I can understand why it hasn't been done - ForCtorParam entries are buried in a web of interfaces and non-public properties.

I'll submit what I've done for you to critique and offer improvements, as you obviously know the codebase a lot better than I do!

**Comment by lbargaoanu** [comment]
Closing in favor of the PR.
