### ISSUE TITLE
Issue with nullsubstitution on multiple members

### ISSUE THREAD

**Issue by Niyol** [AutoMapper/AutoMapper#3161]
### Source/destination types

```csharp
class Coordinate {
    int x;
    int y;
}

class Destination {
    public string name;
    public Coordinate coordinate;
}

class Source {
    public string name;
    public int x;
    public int y;
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<Source, Coordinate>();
                cfg.CreateMap<Source, Destination>()
                    .ForMember(x => x.coordinate, opts => opts.MapFrom(source => source))
                    .ForAllMembers(x=>x.NullSubstitute(string.Empty));
            }); 
```

### Version: x.y.z
 
Automapper 8.1.1
EF Core

### Expected behavior

I wanted to use AutoMapper on different classes where i sometimes have null values on strings. My goal is to map all values, which are strings from null to empty. If i have only datatypes like strings my solution with ForAllMembers and NullSubstitute works. 

### Actual behavior

Sometimes i have a nested class like in my example which causes an Error: 'No coercion operator is defined between types 'System.String' and 'Source'.'

### Steps to reproduce

```csharp
var mapper = config.CreateMapper();

            var src = new Source {
                name = null,
                x = 1,
                y = 1,
            };

            var dst = mapper.Map<Destination>(src);
```

Is there a simple solution to tell the mapper to convert all null strings to empty and leave all other types untouched?

Automapper only improves my project if i needn't protect every string property by a single line, like if i'd use ForMember on every property.

Thanks for your help! :-)

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Value-transformers.html
