### ISSUE TITLE
Using AutoMapper for deep copy of object returns same instance

### ISSUE THREAD

**Issue by voloda** [AutoMapper/AutoMapper#3163]
### Source/destination types

```csharp
// Put your source/destination types here
```
class TDao
{
  public Guid Id {get;set;}
}
### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Expected behavior

According to documentation this should create a new object.

### Actual behavior

If the source and target type are the same then all Map methods seem to return the source object.

### Steps to reproduce

```csharp
TDao dao = _mapper.Map<TDao>(source);

if (dao == source) {
 // this should not happen and new instance should be returned
}

```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. About the documentation, a PR is welcome.
