### ISSUE TITLE
Null mapping error 8.1.1

### ISSUE THREAD

**Issue by chadwescott** [AutoMapper/AutoMapper#3164]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
            mapperConfig.CreateMap<DataRow, EventSummaryResource>()
                .ForMember(x => x.Count, o => o.MapFrom(y => y["EventCount"]))
                .ForMember(x => x.Quantity, o => o.MapFrom(y => y["Quantity"]))
                .ForMember(x => x.StartDate, o => o.MapFrom(y => y["StartDate"]))
                .ForMember(x => x.EndDate, o => o.MapFrom(y => y["EndDate"]));
```

### Expected behavior

In 8.1.0 the mapping logic would handle nulls and with 8.1.1 it gives me a missing mapping exception instead.

### Actual behavior

A mapping exception was thrown:

```
Message: Test method CooperVision.Jda.Moca.Tests.Commands.Impl.GetInventorySummaryMocaCommandTests.GetInventorySummary_PackageLotFoundNoData_ShouldReturnNull threw exception: 
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
EnumerableRowCollection`1 -> EventSummaryResource[]
System.Data.EnumerableRowCollection`1[[System.Data.DataRow, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> CooperVision.Jda.Moca.Models.EventSummaryResource[] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
DataRow -> EventSummaryResource
System.Data.DataRow -> CooperVision.Jda.Moca.Models.EventSummaryResource

Type Map configuration:
DataRow -> EventSummaryResource
System.Data.DataRow -> CooperVision.Jda.Moca.Models.EventSummaryResource

Destination Member:
Quantity
 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Object -> Int32
System.Object -> System.Int32
```

### Steps to reproduce

I am retrieving a DataTable that returns 2 date fields and 2 int fields. One of the int fields and both date fields are null. I hard coded values into the null fields to test and it doesn't matter if the int or date fields are null, it throws the exception either way. When all fields have values the mapping works fine. 8.1.0 did not throw this error and downgrading resolves the issue. There was a Null check bug fix that may have inadvertently introduced this bug: https://github.com/AutoMapper/AutoMapper/pull/3061

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
            _client.Execute(command, out var results);
            return Mapper.Map<T[]>(results.AsEnumerable()).ToArray();
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. But you can always not upgrade.

**Comment by chadwescott** [comment]
@lbargaoanu How is StackOverflow going to help in this situation? My code has not changed other than upgrading AutoMapper and now the mapping fails. You closed this only a few minutes after I created it and didn't even consider it to be a real bug, which I have a hard time believing it isn't. Have you tried mapping a DataRow with null columns after you made the changes for https://github.com/AutoMapper/AutoMapper/pull/3061?

**Comment by lbargaoanu** [comment]
OK, so you can either try to make the mapping work, or you can stay on 8.0.0. Whatever works for you.

**Comment by chadwescott** [comment]
I can get it to work by updating my mapping as such:

```
            mapperConfig.CreateMap<DataRow, EventSummaryResource>()
                .ForMember(x => x.Count, o => o.MapFrom(y => y["EventCount"].ToString() == "" ? 0 : y["EventCount"]))
                .ForMember(x => x.Quantity, o => o.MapFrom(y => y["Quantity"].ToString() == "" ? 0 : y["Quantity"]))
                .ForMember(x => x.StartDate, o => o.MapFrom(y => y["StartDate"].ToString() == "" ? null : y["StartDate"]))
                .ForMember(x => x.EndDate, o => o.MapFrom(y => y["EndDate"].ToString() == "" ? null : y["EndDate"]));
```
I feel like this is a bit convoluted and unfortunately will require me to review all may `DataRow` mappings for null checking...

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). Compare 8.1.0 with 8.1.1. What changed?

**Comment by chadwescott** [comment]
I'm not 100% sure how to evaluate the execution plan, but I have gone ahead and written a couple of unit tests for data table mapping and ran them against 8.1.0 and 8.1.1 and in 8.1.0 the null date field is being set to the default date, not null as expected, and in 8.1.1 a mapping exception is thrown, so at least the behavior I am seeing is testable.

Anyhow, when I get the execution plan and inspect it in the debugger I'm not sure what I should be focusing on. I looked at `Body.Expressions[0].DebugView`, but that's the same between both branches.

I think I'm at the point where I'm just going to bite the bullet and enhance my mappings as I did above. If your interested in the unit tests I wrote for mapping to data tables I'll paste the code below.

**Comment by chadwescott** [comment]
Here's the unit tests I wrote. _Please note that I had to install the NuGet package `System.Data.DataSetExtensions` to get the `dataset.AsEnumerable()` extension method used below_.

```
using Shouldly;
using System;
using System.Data;
using Xunit;

namespace AutoMapper.UnitTests
{
    public class When_mapping_DataTable_with_null_row_values : AutoMapperSpecBase
    {
        protected override MapperConfiguration Configuration => new MapperConfiguration(cfg => cfg.CreateMap<DataRow, Destination>()
            .ForMember(d => d.DateValue, o => o.MapFrom(x => x["date_field"]))
            .ForMember(d => d.IntValue, o => o.MapFrom(x => x["int_field"])));

        DataTable source = new DataTable();

        class Destination
        {
            public DateTime? DateValue { get; set; }
            public int IntValue { get; set; }
        }

        [Fact]
        public void Should_map_values_correctly()
        {
            var targetDate = DateTime.Parse("1/1/2019");
            var source = new DataTable();
            source.Columns.Add(new DataColumn { ColumnName = "date_field" });
            source.Columns.Add(new DataColumn { ColumnName = "int_field" });
            source.Rows.Add(new object[] { targetDate, 10 });

            var destination = Mapper.Map<Destination[]>(source.AsEnumerable());
            destination.Length.ShouldBe(1);
            destination[0].DateValue.ShouldBe(targetDate);
            destination[0].IntValue.ShouldBe(10);
        }

        [Fact]
        public void Should_map_null_values_to_null()
        {
            var source = new DataTable();
            source.Columns.Add(new DataColumn { ColumnName = "date_field" });
            source.Columns.Add(new DataColumn { ColumnName = "int_field" });
            source.Rows.Add(new object[] { null, null });

            var destination = Mapper.Map<Destination[]>(source.AsEnumerable());
            destination.Length.ShouldBe(1);
            destination[0].DateValue.ShouldBe(DateTime.Parse("1/1/0001 12:00:00 AM"));
            destination[0].IntValue.ShouldBe(0);
        }
    }
}
```

**Comment by lbargaoanu** [comment]
The error message you get makes sense to me. I don't see how that mapping did anything useful in 8.1.0.

**Comment by chadwescott** [comment]
Some examples for mapping to a data table suggested doing it that way (https://stackoverflow.com/questions/35414228/using-automapper-to-map-a-datatable-to-an-object-dto).

Obviously I can put more logic in my mapping expression, as I demonstrate above, but up until this point AutoMapper was doing a decent job. It never handled nulls very well, as it would set the value to the default value for the data type instead of null, but it wasn't throwing exceptions when a value was null and now it does for both `int`s and `DateTime`s and likely all null values.

I'll work on improving my mapping configuration. Thanks for your help on this. Perhaps someday I'll get some time to dig into this further, but in the meantime I at least have a path forward.

**Comment by lbargaoanu** [comment]
Maybe we should find a way to make this work without dynamic mapping. We'll see :)
