### ISSUE TITLE
Multiple beforemaps.

### ISSUE THREAD

**Issue by foobarred1** [AutoMapper/AutoMapper#3165]
I've extended Automapper to explicitly load collections in EFCore.  This routine uses BeforeMap.

I've also mapped objects using BeforeMap.  So, the mapping essentially includes two BeforeMaps.  The order of operations becomes important here.

I've discovered that the last "beforemap" in the mapping definition ends up executing first.

My question is whether this behavior is something I can count on for future releases or there could be an OrderOfExecution parameter at some point to govern this behavior?

For example:
```
.BeforeMap((src, dest) =>
{
   //code here
})
.LoadDestinationCollections(ent => new { ent.<collection1>, ent.<collection2>});  //this ends up executing first.

```

Thanks!

**Comment by lbargaoanu** [comment]
Maybe you should use ProjectTo. Or a single BeforeMap.

**Comment by foobarred1** [comment]
So, to be clear, multiple BeforeMaps are not officially supported.  Correct?

**Comment by lbargaoanu** [comment]
To be honest I was surprised that's even possible for the same map. But I believe the intent was for it to work as an event, no order implied.

**Comment by foobarred1** [comment]
Okay, thanks.  I suppose it would be great for me if this was supported, but if not, I think I can live with it, and figure out a workaround.  Maybe if others chime in and request the same you could consider it.

**Comment by foobarred1** [comment]
Just as an FYI, I solved this issue by modifying my extension to accept a second parameter so that:

.LoadDestinationCollections(ent => new { ent.<collection1>, ent.<collection2>}, (src,dest,context) => {
  //beforemap code.
});

The extension will then Invoke the "beforemap" code guaranteeing the order of execution.
