### ISSUE TITLE
How to resolve a map with the new IObjectMapper API

### ISSUE THREAD

**Issue by shoe-diamente** [AutoMapper/AutoMapper#3167]
There doesn't seem to be a clear way to map an expression to a destination type inside the `MapExpression` method of an `IObjectMapper` instantiation.

All previous examples seem to display `MapExpression` taking a `ResolutionContext` as opposed to having this signature:

```c#
public Expression MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, IMemberMap memberMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
```

The closest I got to the solution was via:

```c#
var mappedValue = configurationProvider
                    .FindMapper(new TypePair(sourceInnerType, destInnerType))
                    .MapExpression(...);
```

but it's not clear to me what I would need to pass as a `destExpression` or as a `contextExpression` there.

Is there any documentation that I've missed that explains this?

<hr>

Overall I'm trying to create a custom `IObjectMapper` to deal with wrapped types like `NonNull<T>` so that:

 - `NonNull<T> -> V`
 - `NonNull<T> -> NonNull<V>`
 - `T -> NonNull<V>`

are mapped correctly.

<hr>

I'm using Automapper 8.1.1.

**Comment by lbargaoanu** [comment]
Why not use open generic maps instead?

**Comment by shoe-diamente** [comment]
@lbargaoanu I wasn't able to get it to work and then I stumbled upon a similar question about wrapper types where the author, IIRC, said that mapping `NonNull<T> -> NonNull<V>` is not supported.

**Comment by lbargaoanu** [comment]
Yes, if T and V are different, that won't work. But the next thing to try is [an object based mapper](https://github.com/AutoMapper/AutoMapper/search?q=objectmapper&unscoped_q=objectmapper) that doesn't need expression skills.

**Comment by shoe-diamente** [comment]
@lbargaoanu It seems that `ObjectMapper` requires the two generic type arguments. At the same time the list of `IObjectMapper` requires no templated argument which seems to imply that I would need to add a mapper for each `SourceType, DestType` type pair, is that correct?

**Comment by lbargaoanu** [comment]
No, you can use object. There is a test for that.

**Comment by jbogard** [comment]
You can also check out the existing object mappers, some of which do
similar to what you’re trying to do.

**Comment by shoe-diamente** [comment]
Seems like I managed. Thanks

**Comment by jlnostr** [comment]
@shoe-diamente Stumbling across the same issue right now, it would be kind of you if you could provide your solution with us. Thanks in advance!
