### ISSUE TITLE
Automapper v8.1.1 cannot map JsonPatchDocument

### ISSUE THREAD

**Issue by keymatic** [AutoMapper/AutoMapper#3168]
I'm using Automapper v. 8.1.0 in ASP.Net Core 2.2 project and it works well. When I tried to update Automapper from 8.1.0 to 8.1.1 then I start getting and error:

```
AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

Mapping types:
JsonPatchDocument -> JsonPatchDocument
```

You can find sample project here: https://github.com/keymatic/AutomapperIssue

Note that it uses Automapper 8.1.1 and it produces an error. If you change Automapper package to Automapper 8.1.0 then it will work as expected.

**Comment by lbargaoanu** [comment]
You can either do what the message says, or stick with 8.1. Whatever works for you.

**Comment by keymatic** [comment]
I've added the following mapping to profile according to error message:

```
CreateMap<JsonPatchDocument<UserNoteDto>, JsonPatchDocument<UserNote>>();
```

but I still get the same error.

**Comment by lbargaoanu** [comment]
Yes, but the thing is, this is your code, not AM. AM doesn't handle JsonPatchDocument in any way.

**Comment by irriss** [comment]
I am having the same issue. Seems new version of AM introduced a breaking change. Not sure how to fix it now.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by freerider7777** [comment]
adding .ReverseMap() seems to help... but it really is a breaking change - code stopped working after package update

Missing map from Wallet.Core.Models.ETCard.Amount to Wallet.Core.Domain.JnlOperation. Create using Mapper.CreateMap<Amount, JnlOperation>.System.InvalidOperationException: Missing map from Wallet.Core.Models.ETCard.Amount to Wallet.Core.Domain.JnlOperation. Create using Mapper.CreateMap<Amount, JnlOperation>.
