### ISSUE TITLE
Unflatten from View to DTO

### ISSUE THREAD

**Issue by szavoda** [AutoMapper/AutoMapper#3171]
Given this entity that we get back from a database view:

 public class TestEntity
    {
        public string MyProp { get; set; }
        public string MyProp2 { get; set; }
        public string MyChildProp { get; set; }
        public string MyChildProp2 { get; set; }
    }

Which maps to these models:

    public class TestModel
    {
        public string MyProp { get; set; }
        public string MyProp2 { get; set; }
        public List<TestChildModel> TestChildModels { get; set; }
    }
    public class TestChildModel
    {
        public string MyChildProp { get; set; }
        public string MyChildProp2 { get; set; }
    }

Given this result set:

            var entities = new List<TestEntity>
            {
                new TestEntity
                {
                    MyProp = "1",
                    MyProp2 = "2",
                    MyChildProp = "c-1",
                    MyChildProp2 = "c-2"
                },
                new TestEntity
                {
                    MyProp = "1",
                    MyProp2 = "2",
                    MyChildProp = "c-1",
                    MyChildProp2 = "c-2"
                }
            };

Is there any way to use automapper to map to the models where the result would be a single TestModel with two TestChildModels?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
