### ISSUE TITLE
"Migrating from static API" docs removed? "migrating from Static API is no longer necessary."

### ISSUE THREAD

**Issue by douglasg14b** [AutoMapper/AutoMapper#3174]
This seems in direct conflict with the decision to remove the static API in 9.0, and have it deprecated in 8.1.1

Deprecation Announcement Issue:

- https://github.com/AutoMapper/AutoMapper/issues/3135

Doc that says It's not necessary: https://docs.automapper.org/en/v8.0.0/Migrating-from-static-API.html

Doc that doesn't exist: https://docs.automapper.org/en/v8.1.1/Migrating-from-static-API.html

**Comment by lbargaoanu** [comment]
I'm not sure what you're saying here, but if you wanna add smth to the docs, a PR is welcome.

**Comment by jbogard** [comment]
We’ll have API migration docs as part of the specific version migration
docs in the next major release.

**Comment by douglasg14b** [comment]
@lbargaoanu I mean the docs used to be there, but where removed. Not that I want to write new ones.

@jbogard  Gotcha. It would be handy to have such docs alongside the deprecation, as users may want to move away or avoid the static API right now, not when v9 is released. And having instructions and explanations documented now facilitates that.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/9.0-Upgrade-Guide.html
