### ISSUE TITLE
Updated to latest version, no longer can map without a profile

### ISSUE THREAD

**Issue by gdodd1977** [AutoMapper/AutoMapper#3176]
I tried updating to 8.1.1 today and after reading the upgrade guide, I'm still having issues.

I have a call to mapper.Map<Dest>(source Obj) that I don't have defined in a Profile. This has been working fine as I assume it's just using auto mapping of properties. But once I moved to 8.1.1, it throws an error saying it can't find a mapping definition for it.  Is there some new way to do this in the latest version?

**Comment by lbargaoanu** [comment]
The sole purpose of this release is to start moving people away from dynamic maps and static. So if you don't want to do that, just stick with the version you have.

**Comment by lewinskimaciej** [comment]
You admit you've made insane breaking changes yet you marked it as only a patch version. I understand the change, I don't understand the reasoning behind the versioning(if there is any).
