### ISSUE TITLE
Constructor parameters must not have default values

### ISSUE THREAD

**Issue by MarcusWichelmann** [AutoMapper/AutoMapper#3177]
### Source/destination types

```csharp
public class Source {
    public string A { get; set; }
    public string B { get; set; }
}

public class Destination {
    public string A { get; }
    public string B { get; }

    public Destination(string a, string b = null) {
        A = a ?? throw new ArgumentNullException(nameof(a));
        B = b;
    }
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>();
```

### Expected behavior

When both A and B in my `Source` object are **not** null, I'd expect, that they are both mapped to `Destination`.

### Actual behavior

Because of `string b = null`, the default value is used to call the constructor instead of mapping `B` from `Source` to `Destination`. This results in `Destination.B` being always null.

### Steps to reproduce

```csharp
[Fact]
public void MapsAllProperties()
{
    var configuration = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<Source, Destination>();
    });

    configuration.AssertConfigurationIsValid();

    IMapper mapper = configuration.CreateMapper();

    var source = new Source {A = "foo", B = "bar"};
    var dest = mapper.Map<Destination>(source);

    Assert.Equal(source.A, dest.A); // succeeds
    Assert.Equal(source.B, dest.B); // fails because dest.B is null
}
```

**Comment by lbargaoanu** [comment]
Yes, default values have priority.

**Comment by MarcusWichelmann** [comment]
@lbargaoanu Okay, why is that? Could you please point me to some use case where this behaviour is makes sense and is expected?

**Comment by lbargaoanu** [comment]
No. But if you change it, some tests will fail. I wasn't around when that was implemented. If you're interested in opening a PR, you must first convince @jbogard that your use case is more relevant than the existing tests. Otherwise, just work around it.

**Comment by MarcusWichelmann** [comment]
It would be a breaking change, yes, but because the current behaviour is IMO not obvious and completely unexpected, maybe this would be a good thing to change for the next major release?

**Comment by spydacarnage** [comment]
You could add a configuration flag to `IMappingExpression` to override the default behaviour:
```csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Destination>()
        .OverrideConstructorDefaults();
});
```

When performing the mapping, this flag could be consulted to see which value has priority?

**Comment by lbargaoanu** [comment]
No for the configuration option. About the change, a PR is welcome.
