### ISSUE TITLE
Reduntant call to ValueResolver

### ISSUE THREAD

**Issue by sm-g** [AutoMapper/AutoMapper#3178]
repro repo: https://github.com/sm-g/AutoMapperValueResolverRepro/blob/master/AutoMapperRepro/Program.cs

### Expected behavior

ApplicationValueResolver runs ones, during `context.Mapper.Map<T>(connection)` inside ConnectionValueResolver.

### Actual behavior

After expected mapping ApplicationValueResolver runs again with source == result of ConnectionValueResolver resolving.

But [execution plan](https://github.com/sm-g/AutoMapperValueResolverRepro/blob/master/AutoMapperRepro/ExecutionPlan.txt) contains only one call to ApplicationValueResolver 

The issue is gone if I remove interface from `ConnectionPart : IConnection`.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
You might want to try type converters instead of resolvers.
