### ISSUE TITLE
Question: Is AutoMapper Compitable with .NET Core 2.2 ?

### ISSUE THREAD

**Issue by HakamFostok** [AutoMapper/AutoMapper#3179]
Just a small question.
I have new .NET Core project 2.2, And I want to add AutoMapper to it.
I do not want to install `AutoMapper.Extensions.Microsoft.DependencyInjection` package.
The AutoMapper library is enough for my case.

My question is: Can I use the AutoMapper package safely with .NET Core 2.2, Is the library has been tested in .NET Core 2.2 so I can safely add it and start working with it

Thank you

**Comment by lbargaoanu** [comment]
Yes.
