### ISSUE TITLE
Match docs.microsoft.com layout for docs

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#3185]
If you look at the docs.microsoft.com site, they've got a consistent layout for documentation:

 - Title
 - Overview
 - Quickstarts
 - Tutorials
 - Samples
 - Concepts
 - How-to guides
 - Reference
 - Troubleshooting
 - Resources

I don't think all of these apply to us, but given the number of SO questions around docs and GH issues around docs, maybe it's time for a bit of an organizational makeover?

Some example sites:

https://docs.microsoft.com/en-us/azure/cosmos-db/
https://docs.microsoft.com/en-us/nuget/what-is-nuget

We've got a lot of docs that describe a feature, but nothing really guiding when to use what.

**Comment by lbargaoanu** [comment]
Yes, but that tree on the left is different, in that some entries are simply for structure. Our tree is made from the entries in the content itself.

**Comment by jbogard** [comment]
I think that's OK...I'm just thinking of having a consistent layout with something that's more familiar.

**Comment by lbargaoanu** [comment]
What about existing links to the docs?

**Comment by niemyjski** [comment]
When viewing the docs (https://github.com/AutoMapper/AutoMapper/blob/master/docs/9.0-Upgrade-Guide.md) the two links are dead when viewing from GitHub) Is this expected?

**Comment by lbargaoanu** [comment]
Yes.
