### ISSUE TITLE
ProjectTo error when using ConvertUsing in combination with HasConversion (.NET Core 3.0)

### ISSUE THREAD

**Issue by BalintBanyasz** [AutoMapper/AutoMapper#3188]
### Source/destination types

```csharp
public class Entity
{
    public int Id { get; set; }
    public MySmartEnum SmartEnum { get; set; }
}

public class MySmartEnum
{
    public string Value { get; set; }
}

public class Dto
{
    public int Id { get; set; }
    public MyEnum Enum { get; set; }
}

public enum MyEnum
{
    A,
    B,
    C,
    D
}
```

### Mapping configuration

```csharp
CreateMap<MySmartEnum, MyEnum>()
     .ConvertUsing(x => Enum.Parse<MyEnum>(x.Value));

CreateMap<Entity, Dto>()
    .ForMember(dto => dto.Enum,
        m => m.MapFrom(d => d.SmartEnum));
```

### Version: 8.1.1
netcoreapp3.0
Microsoft.EntityFrameworkCore 3.0.0-preview9.19411.1
Microsoft.EntityFrameworkCore.SqlServer 3.0.0-preview9.19411.1

### Expected behavior

ProjectTo should work correctly in this scenario as it worked with the following:
netcoreapp2.2
Microsoft.EntityFrameworkCore 2.2.6
Microsoft.EntityFrameworkCore.SqlServer 2.2.6

### Actual behavior

The following exception is thrown:
```
System.InvalidOperationException: 'No coercion operator is defined between types 'ProjectToConvertUsingIssue.MySmartEnum' and 'System.String'.'
```

### Steps to reproduce

```csharp
public class TestContext : DbContext
    {
        public TestContext()
        { }

        public TestContext(DbContextOptions<TestContext> options)
            : base(options)
        { }

        public virtual DbSet<Entity> Entities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entity>()
                .Property(e => e.SmartEnum)
                .HasConversion(v => v.Value, v => new MySmartEnum { Value = v });
        }
    }

using (var context = new TestContext(options))
{
    var dtos = context.Entities.AsNoTracking()
        .ProjectTo<Dto>(config)
        .ToList();
}
```
The generated expression is the same as before:
```csharp
EntityQueryable<Entity>.AsNoTracking().Select(
    dtoEntity => new Dto
    {
        Enum = Enum.Parse<MyEnum>(dtoEntity.SmartEnum.Value),
        Id = dtoEntity.Id
    })
```
Executing the query manually results in the same exception:
```csharp
var dtos = context.Entities.AsNoTracking()
     .Select(
        x => new Dto
        {
            Enum = Enum.Parse<MyEnum>(x.SmartEnum.Value),
            Id = x.Id
        })
    .ToList();
```

The issue might be related to the following breaking change in EF Core 3.0:
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client

**Comment by lbargaoanu** [comment]
You should change your code to no longer require client evaluation. Or switch to `Map`.

**Comment by BalintBanyasz** [comment]
> You should change your code to no longer require client evaluation. Or switch to `Map`.

Thanks for the reply. Unfortunately, server side only evaluation is not an option in this case and switching to `Map` would take away the advantage of `ProjectTo` selecting only the required fields (my actual entity/mapping is more complex than the example posted).

After the official .NET Core 3.0/EF Core 3.0 release, this could introduce issues for other users as well. Do you think that somehow the execution could be split into two (server and client)?

I would imagine something like this:

```csharp
// Specify client conversion
CreateMap<MySmartEnum, MyEnum>()
                .ConvertClientUsing(x => Enum.Parse<MyEnum>(x.Value));
```

Then AutoMapper could evaluate it like this:
```csharp
var dtos = context.Entities.AsNoTracking()
// executed on server, temporary anonymous type holds only the required data
     .Select(
        x => new
        { // perform server side conversions here
            x.SmartEnum,
            x.Id
        })
     .AsEnumerable() // bring data back to the client
// executed on client side
     .Select(
        x => new Dto
        { // perform client conversions here
             Enum = Enum.Parse<MyEnum>(x.SmartEnum.Value),
             Id = x.Id
        })
     .AsQueryable()
```

**Comment by lbargaoanu** [comment]
There are no plans for this, but of course you can do it yourself by calling first `ProjecTo` and then `Map`.
