### ISSUE TITLE
Breaking change between v8.1.0 and v8.1.1 when mapping to a dictionary

### ISSUE THREAD

**Issue by ChristopherHaws** [AutoMapper/AutoMapper#3190]
Hello,

I meant to post this a while ago when 8.1.1 was released but I got caught up in things at work so I never got a chance. I'm not sure if this was an intentional breaking change or not, but there was a breaking change in 8.1.1 when mapping from a collection of Key/Values to a Dictionary (the Key/Value type is not `KeyValuePair` because it is an EF entity).

### Expected behavior
In 8.1.0 of AutoMapper, this mapping worked without any issues. It would map the Key/Values into the Dictionary.

### Actual behavior
In 8.1.1, the following error is thrown:

```
AutoMapperMappingException: Error mapping types.

Mapping types:
Order -> OrderModel
UserQuery+Order -> UserQuery+OrderModel

Type Map configuration:
Order -> OrderModel
UserQuery+Order -> UserQuery+OrderModel

Destination Member:
Attributes
```

### Steps to reproduce

```csharp
void Main()
{
    var services = new ServiceCollection();
    services.AddAutoMapper(this.GetType().Assembly);
    
    using var root = services.BuildServiceProvider();
    var mapper = root.GetRequiredService<IMapper>();
    
    var model = mapper.Map<OrderModel>(new Order
    {
        OrderNumber = "PO1001",
        Attributes =
        {
            new Order.Attribute { Key = "Key1", Value = "Value1" },
            new Order.Attribute { Key = "Key2", Value = "Value2" },
        }
    });
}

public class Order
{
    public String OrderNumber { get; set; }
    public ICollection<Attribute> Attributes { get; set; } = new HashSet<Attribute>();

    public class Attribute
    {
        public String Key { get; set; }
        public String Value { get; set; }
    }
}

public class OrderModel
{
    public String OrderNumber { get; set; }
    public IDictionary<String, String> Attributes { get; set; } = new Dictionary<String, String>();
}

public class Profile : AutoMapper.Profile
{
    public Profile()
    {
        this.CreateMap<Order, OrderModel>();
    }
}
```

**Comment by lbargaoanu** [comment]
9.0 was just released. So use that or stick with the version you have.

**Comment by ChristopherHaws** [comment]
This issue still occurs in v9.

**Comment by lbargaoanu** [comment]
You can either do what the message says, or keep the version you have.

**Comment by ChristopherHaws** [comment]
Was this an intentional breaking change? If so, then that is fine, I just didn't see any notes about this breaking change anywhere. I don't see the need to be rude to someone who is reporting a bug... I am running fine on v9 with the following workaround:

```
this.CreateMap<Order, OrderModel>()
    .ForMember(x => x.Attributes, x => x.MapFrom(y => y.Attributes.ToDictionary(a => a.Key, a => a.Value)));
```

**Comment by jbogard** [comment]
The `Order.Attribute` type is unknown to AutoMapper. Previously, we would create dynamic maps on the fly. We turned that off, then removed dynamic maps, since you could have misspelled or changed the `Order.Attribute` type and your mapping would silently skip those properties.

You need to create a map from your custom type to the KeyValuePair type:

```c#
public class Profile : AutoMapper.Profile
{
    public Profile()
    {
        this.CreateMap<Order, OrderModel>();
        this.CreateMap<Order.Attribute, KeyValuePair<string, string>>();
    }
}
```

**Comment by ChristopherHaws** [comment]
Ah, I didn't realize that it was being dynamically mapped. Thanks for the clarification!
