### ISSUE TITLE
Static API remove

### ISSUE THREAD

**Issue by andmattia** [AutoMapper/AutoMapper#3191]
Version AutoMap 8.1.1

We use AutoMap.Map to update object from DTO to EF. In 9.0.0 the static API will be removed how can cover this operation?

es code from stackoverflow [Using Automapper to update an existing Entity POCO](url)
```cs
    Patient patient = db.Patients.Find(viewModel.Id); 
    Mapper.Map(viewModel, patient);
    ...
    db.SaveChanges();
```

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/9.0-Upgrade-Guide.html

**Comment by andmattia** [comment]
@lbargaoanu the doc explain to use AutoMap attribute. Sorry but I can't understand how can call mapping my DTO object into a EF entity to update.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
