### ISSUE TITLE
Project from anonymous object

### ISSUE THREAD

**Issue by John0King** [AutoMapper/AutoMapper#3194]
### Source/destination types

```csharp
class BlogDto
{
  public int Id{get;set;}
  public string BlogName{get;set;}
  public DateTimeOffset CreateTime{ get;set;}
  public int PostCount{get;set;}
}

class Blog
{
    public string BlogName{get;set;}
    public DateTimeOffset CreateTime{ get;set;}
}

class Post
{
    public int Id{get;set;}
    public intBlogId{get;set;}
   public string Title{get;set;}
}

db.Blogs.Where(b=>b.Id = 1).Select(b=>new { Blog = b, PostCount = db.Post.Where(p=>p.BlogId == b.Id).Count()} )
    .ProjectTo<BlogDto>(config)
```
How to use AutoMaper  when there is a additional field?

**Comment by lbargaoanu** [comment]
There is no need for that. Just project directly to the dto.

**Comment by John0King** [comment]
@lbargaoanu What do you mean ?  do not use `.ProjectTo<T>()` ?

**Comment by lbargaoanu** [comment]
`db.Blogs.ProjecTo<BlogDto>(config)`

**Comment by John0King** [comment]
@lbargaoanu  There is a `PostCount = db.Post.Where(p=>p.BlogId == b.Id).Count()` property thire,  how to add the additional property value to the map ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by MRMokwa** [comment]
Hey @John0King, if you got the solution, do you mind sharing it?
I'm having the same issue

**Comment by John0King** [comment]
@MRMokwa    one way it to use DI to inject a `IMappingAction`  but it wil alsol try to use EF when u in Object to Object mapping.
Maybe this is the right answer https://docs.automapper.org/en/stable/Custom-value-resolvers.html#passing-in-key-value-to-mapper , I'm not try it yet , (I  switched  to use manully project 😂)
