### ISSUE TITLE
Automapper in ARM iot core Windows

### ISSUE THREAD

**Issue by M2xAy** [AutoMapper/AutoMapper#3196]
Hi
I am using Automapper in .net core app with netstandard projekt for model and Automapper, if I publish with this: dotnet publish -r ubuntu.16.04-arm I do not receive error but if I run this dotnet publish  -r win10-arm I receive downgrade error NU1605

Can you help me ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
