### ISSUE TITLE
public field of the property implemented PropertyChanged causes exception in ProjectTo

### ISSUE THREAD

**Issue by Tao-lol** [AutoMapper/AutoMapper#3197]
I have an Asp.Net Core Web Api project, and there is a model's property implements INotifyPropertyChanged because it's shared with my desktop client project.

Asp.Net Core 2.2 ,       AutoMapper 9.0 ,      Entityframework Core 2.2.6

Here is a simple example: [example](https://github.com/Tao-lol/AutoMapperTest)
##### Database model property
```csharp
private string _Name = string.Empty;
public string Name
{
    get
    {
        return _Name;
    }
    set
    
        if (value != _Name)
        {
            _Name = value;
            OnPropertyChanged(nameof(Name));
            }
        }
}
```
##### View model property
```csharp
//TODO: Here is the reason of the exception. If the "public" is "private", then it works well.
public string _Name;
public string Name
{
    get
    {
        return this._Name;
    }
    set
    {
        if (value != this.Name)
        {
            this._Name = value;
            OnPropertyChanged(nameof(Name));
        }
     }
}
```
##### ProjectTo
```csharp
var config = _mapper.ConfigurationProvider;
var query = _context.DbModels.AsQueryable();
var map = query.ProjectTo<ViewModel>(config);
var list = await map.ToListAsync();
```
### Exception
Obviously, the field should be private. The public field causes an exception: **"Static method requires null instance, non-static method requires non-null instance."** If the field is public, then there is no problem.

I don't know if it is a bug.

**Comment by lbargaoanu** [comment]
You already know what to do about it.
