### ISSUE TITLE
Partial mapping

### ISSUE THREAD

**Issue by benmccallum** [AutoMapper/AutoMapper#3198]
I've got a situation where it makes sense for me to use the power of `ProjectTo<TDto>()` with explicit expansion and passing the members I need expanded outside the context of `Queryable`.

I have two cases:
1. `IEnumerable<T>`
2. `T`

I can achieve my needs with the following for each:
1. `myEnumerable.ToQueryable().ProjectTo<TDto>(...)`
2.  `(new [] { myObject }).ToQueryable().ProjectTo<TDto>(...).First()`

Just querying whether we could have a more direct way in, off `IMapper` I guess, that is easier and optimized.

Thanks!

**Comment by benmccallum** [comment]
Currently getting around it with some wrapping extensions:

```
public static class IMapperExtensions
{
    public static TTargetType ProjectTo<TSourceType, TTargetType>(this IMapper mapper, TSourceType source, params string[] membersToExpand)
    {
        return mapper.ProjectTo<TTargetType>((new[] { source }).AsQueryable(), null, membersToExpand).First();
    }

    public static List<TTargetType> ProjectTo<TSourceType, TTargetType>(this IMapper mapper, IEnumerable<TSourceType> source, params string[] membersToExpand)
    {
        return mapper.ProjectTo<TTargetType>(source.AsQueryable(), null, membersToExpand).ToList();
    }
}
```

**Comment by lbargaoanu** [comment]
That doesn't look so bad :) We also have expression mapping that might help here. But why not just use Map?

**Comment by benmccallum** [comment]
I couldn't see a Map overload that took a `membersToExpand` and provided the same functionality. Is there one?

**Comment by lbargaoanu** [comment]
That's  because it doesn't make sense for IEnumerable, only for IQueryable.

**Comment by benmccallum** [comment]
Because it requires an IQueryable and expressions to be able to operate I take it?

In my situation I have a caller who knows what fields it wants, but the API responding is limited in how it can pull the underlying data (CMS APIs), so it returns full objects. Nevertheless, ideally what goes back over the wire should only be data on the fields requested. So in my case the membersToExpand isn't about optimising an underlying DB query, but just about stripping data off already loaded entities. 

I'm ok with doing the above, but really just wonder if we could bake in something a little more direct. 

Is there a Map overload that allows just-in-time passing of property configurations? It's all configure once globally isn't it? Hmm...

**Comment by lbargaoanu** [comment]
You can do smth like that for Map using conditional mapping. It might even be interesting to have it built in. But you would have to implement that yourself.

**Comment by lbargaoanu** [comment]
See also #3151.

**Comment by lbargaoanu** [comment]
See also #3151.

**Comment by benmccallum** [comment]
@robin-thoni FYI here's what I'm doing. I use ProjectTo<T> down to my DB for GraphQL but for an API I have less control of (wrapping a CMS) I use the above technique to "trim" it before it goes back out over the wire. Seems to be working well.

@lbargaoanu, if I understand it correctly, conditional mapping would need to know about the fields I want mapped (which could vary each time the method is called, because of a GraphQL request), but there's no way to pass that in at each Map-time, the configuration is kind of singleton. Unless I put a FieldsToMap on all my source objects and set that just before I called Map. Would work I guess but isn't super clean.

**Comment by lbargaoanu** [comment]
You pass things in Context.Items.

**Comment by benmccallum** [comment]
One day I'll get to this :P
