### ISSUE TITLE
ProjectTo IReadOnlyCollection

### ISSUE THREAD

**Issue by kilinskim** [AutoMapper/AutoMapper#3199]
After migration to latest version of AutoMapper(from v8 to v9) I have issue with ProjectTo method. When projecting from ICollection to IReadOnlyCollection I get System.ArgumentException: 'Argument types do not match'.

Some code:
```c#
public class Source
{
    public ICollection<int> Collection { get; set; } = new HashSet<int>();
}

public class Destination
{
    public IReadOnlyCollection<int> Collection { get; set; } = new HashSet<int>();
}

public class Profile : AutoMapper.Profile
{
    public Profile() { CreateMap<Source, Destination>(); }
}

//This line throws exception
var mapped = mapper.ProjectTo<Destination>(src);
```

I just wonder if this is expected behavior or bug. I did not find any related changes in changelog.

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html) in v8.

**Comment by lbargaoanu** [comment]
One thing to try. Set CreateMissingTypeMaps to false in v8. If you get the same error, you just need to figure out what automatically created map was helping you before and explicitly create it in v9.

**Comment by kilinskim** [comment]
I checked v8 with CreateMissingTypMaps set to false. There was no exception. 
Also in v9 when you use Map instead of ProjectTo everything is fine.

**Comment by lbargaoanu** [comment]
Then it's most likely a bug caused by #3187. Try ICollection instead.

**Comment by jbogard** [comment]
Yeah I don't think we explicitly support projecting to an `IReadOnlyCollection`.

To get around this, you can project to one of the supported types:

 - `T[]`
 - `ICollection<T>`
 - `IEnumerable<T>`

Basically we call:

 - `Select().ToArray()`
 - `Select().ToList()`
 - `Select()`

I'm not aware of any LINQ-enabled `ToReadOnlyCollection` or similar. Also, your destination object initializes things - that will be ignored by LINQ query providers, I'd remove that.

`ProjectTo` is designed for LINQ query providers, not in-memory providers (i.e. `enumerable.AsQueryable()`)

**Comment by jbogard** [comment]
I think the way we'd fix this is to change our logic to be;

 1. `T[]` - call `ToArray()`
 2. `IEnumerable<T>` - leave as just `Select`
 3. Else call `ToList`

We could probably do a bit more checks to say we can only map to any type `List<T>` supports to prevent people doing wacky stuff like mapping to a concurrent or immutable list.

**Comment by jbogard** [comment]
I'm getting this in a manual LINQ statement:

```c#
public class Customer
{
    [Key]
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public ICollection<Item> Items { get; set; }
}

public class Item
{
    public int Id { get; set; }
    public int Code { get; set; }
}

public class ItemModel
{
    public int Id { get; set; }
    public int Code { get; set; }
}

public class CustomerViewModel
{
    public IReadOnlyCollection<ItemModel> Items { get; set; }
}
public class Context : DbContext
{
    public Context()
    {
        Database.SetInitializer<Context>(new DatabaseInitializer());
    }

    public DbSet<Customer> Customers { get; set; }
}

public class DatabaseInitializer : DropCreateDatabaseAlways<Context>
{
    protected override void Seed(Context context)
    {
        context.Customers.Add(new Customer
        {
            Id = 1,
            FirstName = "Bob",
            LastName = "Smith",
            Items = new[] { new Item { Code = 1 }, new Item { Code = 3 }, new Item { Code = 5 } }
        });

        base.Seed(context);
    }
}

[Fact]
public void Can_manually_map_to_readonly_collection()
{
    using (var context = new Context())
    {
        var result = context.Customers.Select(c => new CustomerViewModel
        {
            Items = c.Items.Select(i => new ItemModel
            {
                Code = i.Code,
                Id = i.Id
            }).ToList()
        }).Single();

        result.Items.Count.ShouldBe(3);
    }
}
```

This fails with an "argument types do not match" exception...even more curious how this was supposed to work before? I can't get it to work without AutoMapper with `IReadOnlyCollection`.

**Comment by kilinskim** [comment]
> Also, your destination object initializes things - that will be ignored by LINQ query providers, I'd remove that.

Good to know. Thanks!

I forgot to mention my orignal issue was with EFCore. 

About manual mapping, it works with EFCore(2.2.6) but fails with classic version(6.2.0).

If I may ask, why mapping to concurrent or immutable list is bad idea?

**Comment by jbogard** [comment]
Check the SQL that runs when you do that on EF Core. EF Core has an...interesting behavior that when it sees LINQ expressions it can't interpret or understand, it flips to using in-memory projections, losing any benefit of `ProjectTo`. It does this silently.

Mapping to those collection types is fine. *Projecting* to them via LINQ is not. You should only use types that your LINQ provider can support.

As an example, the MongoDB LINQ provider doesn't support lists, because those imply additional behaviors, so it only supports `IEnumerable`.

**Comment by lbargaoanu** [comment]
@jbogard I don't use EF Core, but from what I hear they no longer do that. You opt in now to client evaluation, with AsEnumerable.

**Comment by jbogard** [comment]
@lbargaoanu It looks like EF Core 3.0 is when those changes come in?

**Comment by lbargaoanu** [comment]
Yes, I think so. They have previews out.

**Comment by kilinskim** [comment]
I was sure that our EF configuration forbids (just like EF Core 3.0) in-memory evaluation. I'll check it asap. 

Anyway thank you guys. For your answers and your work!

**Comment by lbargaoanu** [comment]
As far as I can tell the latest 3.0 preview supports `IReadOnlyCollection`.

**Comment by BryanSan** [comment]
@lbargaoanu where did you see the support for `IReadOnlyCollection`?

**Comment by lbargaoanu** [comment]
I wrote a test and it passed :)
