### ISSUE TITLE
Map overload without Action

### ISSUE THREAD

**Issue by lucabellaviadev** [AutoMapper/AutoMapper#3206]
After migration to latest version of AutoMapper(from v8 to v9). I have issue with mapper.Map<T> method. When mapping an object to another one I get System.InvalidOperationException: 'You must use a Map overload that takes Action<IMappingOperationOptions>!'.

Some code:

THEN:

[...]
    //This line throws exception
    conversation.CreatedBy = mapper.Map<UserLight>(usr);
[...]

NOW (to fix the bug momentarily):

[...]
    //It's ok
    conversation.CreatedBy = mapper.Map<UserLight>(usr, ctx => ctx.Items["UserId"] = null);
[...]

I just wonder if this is expected behavior or bug. Do I have to pass items of context to the method every time from v9 on? Or there is any way to not do it?

**Comment by lbargaoanu** [comment]
Yes, you need to tell us that you need the context. That allows us to avoid creating it in all the other cases. You don't have to do anything in the Action parameter (`_=>{}` would do). It is a little clumsy. But adding a new method, just for this purpose, I don't know... You could easily write an `IMapper` extension method if you want.

**Comment by dstj** [comment]
@lbargaoanu Why is the `Map(src)` method still present then if it will always throw an error?

Having to write `_=>{}` everywhere seems extra work for no reason... I must be missing something, right?

**Comment by dstj** [comment]
@lbargaoanu I thought about it some more.  I need to add the `_ => {}` dummy function in many many places because I'm using the `ResolutionContext.Items` to optionally put a `Dictionary` indicating if a field should be mapped or not (i.e. a sparse fieldset).

In my mapping function, I first check if the field should be mapped with the following extensions method. If the `Items` key is missing, that it means that everything should be mapped.

		public static bool ShouldMapField(this ResolutionContext ctx, string type, string fieldName)
		{
			if (!ctx.Items.TryGetValue(FieldsKey, out var fieldsPerTypeObj))
				return true;

			var fieldsPerType = (IDictionary<string, HashSet<string>>) fieldsPerTypeObj;
			if (!fieldsPerType.TryGetValue(type, out var fields))
				return true;

			return fields.Contains(fieldName);
		}

There should maybe be a way to say `if (ctx.NoContextProvided || !ctx.Items.TryGetValue(.....` to avoid having to specify a dummy context...

**Comment by lbargaoanu** [comment]
It seems to me like your own code is to blame because it doesn't initialize the values in the context. You use it without initializing it and without telling us you need it by using the right overload.

**Comment by dstj** [comment]
Yes, exactly, a non-initialized (i.e. no values in the context) is a valid scenario for me. It just means that nothing special was requested and to proceed with the default behavior...

Now, with v9, I have to always specify "use the default behavior"... that is all.

**Comment by lbargaoanu** [comment]
That seems fair to me. cc @jbogard
