### ISSUE TITLE
ValueConverters page has incorrect examples

### ISSUE THREAD

**Issue by docrinehart** [AutoMapper/AutoMapper#3208]
http://docs.automapper.org/en/stable/Value-converters.html

Examples show `IValueConverter<,>.Convert()` having only one arg. In reality, the signature also contains an arg for `ResolutionContext`

Example from docs:
```
public class CurrencyFormatter : IValueConverter<decimal, string> {
    public string Convert(decimal source)
        => source.ToString("c");
}
```

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by docrinehart** [comment]
@lbargaoanu I see you closed this issue, but it doesn't appear the documentation has been updated. I'd be happy to correct it myself (assuming I can make the time), but I don't think the issue should be closed until the docs are corrected.
