### ISSUE TITLE
Issue with generating nested collections

### ISSUE THREAD

**Issue by Olorin92** [AutoMapper/AutoMapper#3209]
### Source/destination types

These are just the DTO classes I'm trying to map to - the domain objects are identical save for a few extra properties, so I'm going to leave them out.

```csharp
    public class NoteDTO
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public string Conclusion { get; set; }
        public string Title { get; set; }
        
        public ManagerDTO Manager { get; set; }
    }

    public class ManagerDTO
    {
        public int Id { get; set; }
        
        public List<ProductDto> Products { get; set; }
    }

    public class ProductDto
    {
        public int Id { get; set; }
    }
```

### Mapping configuration

While I test, I'm keeping the mapping extremely simple and just doing inline with my Controller

```csharp
var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Note, NoteDTO>();
                cfg.CreateMap<Product, ProductDto>();
                cfg.CreateMap<Manager, ManagerDTO>()
                    .ForMember(md => md.Products, conf => conf.MapFrom(m => m.Products));
            });
```

### Version: 9.0.0

AutoMapper 9.0.0, using Entity Framework Core 2.2.6

### Expected behavior

I am utilizing OData in my test project in order to provide flexibility in the way my API can be called and queried. A sample query that I am trying is as follows:

https://localhost:5001/api/Notes?$select=Id,Body,Conclusion&$top=5&$expand=Manager($select=Id;$expand=Products($select=Id))

I would expect this to return the specified properties of the NoteDto object (calling into the Note model and utilizing EF), and then also include the nested ManagerDto, and it's nested ProductDtos.

### Actual behavior

Similar to issue #2853, I am met with an exception which seems to indicate that somewhere along the line, the List<NoteDto> property is trying to be mapped to an IEnumerable of type tuple.

I tried the suggestion by @spasarto but still couldn't get this to work.

There seemed to be indications that this issue lies with Entity Framework Core as opposed to AutoMapper, but I wanted to raise this again in an attempt to get clarity on this and potential next steps to try and resolve it.

I've also posted this to SO here: https://stackoverflow.com/questions/57691577/unable-to-map-list-navigational-properties-using-odata-ef-core-and-automapper, but given this seems to be a pretty uncommon use case and there was already an issue describing the same behavior, I thought I'd post here too for visibility.

### Steps to reproduce

The below is the test API method I have for producing this error.

```csharp
        [HttpGet]
        [EnableQuery]
        public IQueryable<NoteDTO> GetMeeting(ODataQueryOptions<NoteDTO> q)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Note, NoteDTO>();
                cfg.CreateMap<Product, ProductDto>();
                cfg.CreateMap<Manager, ManagerDTO>()
                    .ForMember(md => md.Products, conf => conf.MapFrom(m => m.Products));
            });

            return _context.Notes.ProjectTo<NoteDTO>(config);
        }
```

Any help here is much appreciated - the mapping seems to work fine as long as there isn't an IEnumerable<> in any of the object graphs.

**Comment by lbargaoanu** [comment]
Expression mapping was moved to a different [repo](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping).

**Comment by lbargaoanu** [comment]
But if you have a repro with EF6, without OData, we'll look into it.
