### ISSUE TITLE
Add IgnoreMapAttribute to documentation

### ISSUE THREAD

**Issue by eduherminio** [AutoMapper/AutoMapper#3210]
### Expected behavior

`IgnoreMapAttribute` behavior and usage described in [documentation](https://docs.automapper.org/en/stable/), as [`IgnoreAttribute`](https://docs.automapper.org/en/stable/Attribute-mapping.html?highlight=ignore#member-configuration).

### Actual behavior

No mention to `IgnoreMapAttribute`  in documentation, which can lead to incorrectly try to use `IgnoreAttribute` to ignore mappings.

### Steps to reproduce

[Search link](https://docs.automapper.org/en/stable/search.html?q=ignoremap&check_keywords=yes&area=default#).

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by eduherminio** [comment]
I'll consider it whenever I have some time.
Shouldn't the issue remain open until that moment?
