### ISSUE TITLE
ProjectTo fails mapping

### ISSUE THREAD

**Issue by ordinarytype** [AutoMapper/AutoMapper#3212]
Hi all,

I have two mappings:

        private Expression<Func<Patient, string>> GetCurrentWardTitle()
        {
            return src => src.BedHistoryEntries.FirstOrDefault(x => !x.DateEnd.HasValue).Bed.Ward.Title;
        }

        private Expression<Func<Patient, string>> GetCurrentBedTitle()
        {
            return src => src.BedHistoryEntries.FirstOrDefault(x => !x.DateEnd.HasValue).Bed.Title;
        }
Second one is working fine and maps property to null, if bed is null. First one throws null reference exception. Would be nice to have both of them null, if bed isn't presented.

Sample project is attached.
Thanks!

[SampleProject.zip](https://github.com/AutoMapper/AutoMapper/files/3575198/SampleProject.zip)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
