### ISSUE TITLE
Incorrect property mapping

### ISSUE THREAD

**Issue by WalissonPires** [AutoMapper/AutoMapper#3213]
I am mapping an object using an explicit construct. When automapper creates the object the property values are correct.
However, after EF returns the object some properties have different values.

I noticed that this happens only with properties that have the same name in both objects (destination and source), in the case of example are: Id and Tags.
Apparently, I'm not sure, EF reassigns these properties with the value of the searched object.
That is, instead of keeping the Blog Id and Tags as defined in autommaper. The object gets the Post Id and Tags.

[Project Test](https://drive.google.com/file/d/1PQJQeskKkAfPqCGeKVOAoTh5xsNfX_Lh/view?usp=sharing)

### Source/destination types

```csharp
class Blog
{
        public Guid Id { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }

        public virtual List<Post> Posts { get; set; }
}

class Post
{
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }

        public Guid BlogId { get; set; }
        public virtual Blog Blog { get; set; }
}

class BlogInfoModel
{
        public Guid Id { get; set; }
        public Guid PostId { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string PostTags { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
	cfg.CreateMap<Post, BlogInfoModel>()
		.ConstructUsing((post, ctx) =>
		{
			var model = new BlogInfoModel
			{
				PostId = post.Id,
				Id = post.Blog.Id,                                                        
				Description = post.Blog.Description,
				Tags = post.Blog.Tags,
				PostTags = post.Tags
			};
		   
			var correctId = model.Id != model.PostId;       //expect TRUE. is TRUE
			var correctTags = model.Tags != model.PostTags; //expect TRUE, is TRUE

			return model;
		});
});
```

### Version: 9.0.0 
Microsoft.EntityFrameworkCore 3.0.0-preview8.19405.11
Npgsql.EntityFrameworkCore.PostgreSQL 3.0.0-preview8

### Expected behavior

The object is expected to be created with the values assigned in the mapping function.

### Actual behavior

Some properties have overridden values.

### Steps to reproduce

```csharp
var mapper = config.CreateMapper();

var model = context.Posts.AsNoTracking().Include(x => x.Blog).Select(x => mapper.Map<BlogInfoModel>(x)).FirstOrDefault();            

var correctId = model.Id != model.PostId;           //expect TRUE, is FALSE
var correctTags = model.Tags != model.PostTags;     //expect TRUE, is FALSE
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by WalissonPires** [comment]
It is not a doubt. It is a bug.

**Comment by jbogard** [comment]
No, `ConstructUsing` is not for mapping - it is for constructing. After constructing, next comes mapping. You shouldn't be using an object initialization expression in `ConstructUsing` - at most, a constructor.

If you want to override the mapping behavior, you want `ConvertUsing`. Check the mapping plan and you can confirm.
