### ISSUE TITLE
MemberList.Source validation fails when used with flattening

### ISSUE THREAD

**Issue by bcallaghan-et** [AutoMapper/AutoMapper#3215]
### Source/destination types

```csharp
public class TestSource {
  public NestedSource Nested { get; set; }
}

public class NestedSource {
  public int TestInt { get; set; }
  public string TestString { get; set; }
}

public class TestDestination {
  public int? Nested_TestInt { get; set; }
  public string Nested_TestString { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(config => {
  config.CreateMap<TestSource, TestDestination>(MemberList.Source);
});
```

### Expected behavior

`AssertConfigurationIsValid` should pass without throwing an exception. The destination object should contain `Nested_TestInt=7` and `Nested_TestString="Foo"`.

### Actual behavior

`AssertConfigurationIsValid` throws the following exception:

```
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
==========================================================================
TestSource -> TestDestination (Source member list)
Etogy.Visa.Downloader.TestSource -> Etogy.Visa.Downloader.TestDestination (Source member list)

Unmapped properties:
Nested
```

If the validation is changed to `MemberList.Destination`, then no exception is thrown, and the destination object is mapped correctly.

### Steps to reproduce

```csharp
configuration.AssertConfigurationIsValid();
var mapper = configuration.CreateMapper();
var source = new TestSource {
  Nested = new NestedSource {
    TestInt = 7,
    TestString = "Foo"
  }
};
var destination = mapper.Map<TestDestination>(source);
```

**Comment by lbargaoanu** [comment]
Use `IncludeMembers` instead.

**Comment by bcallaghan-et** [comment]
Like this?
```
config.CreateMap<TestSource, TestDestination>(MemberList.Source).IncludeMembers(src => src.Nested);
config.CreateMap<NestedSource, TestDestination>(MemberList.Source);
```

That doesn't seem to work with Source or Destination mode. With Source validation, I get the following exception:
```
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
============================================================================
NestedSource -> TestDestination (Source member list)
Etogy.Visa.Downloader.NestedSource -> Etogy.Visa.Downloader.TestDestination (Source member list)

Unmapped properties:
TestInt
TestString
```

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Flattening.html#includemembers

**Comment by bcallaghan-et** [comment]
The following map partially worked. I had to disable validation for the nested object, otherwise it would throw an exception as well. The example in the linked documentation also disables validation for nested objects, but the docs do not give a reason why that would not work.
```csharp
config.CreateMap<TestSource, TestDestination>(MemberList.Source).IncludeMembers(s => s.Nested);
config.CreateMap<NestedSource, TestDestination>(MemberList.None);
```

I still want validation for the nested object. For example, if I were to change my objects to the following, I still want to receive validation that the property `Missing` was not included in the destination object.
```csharp
public class TestSource {
  public NestedSource Nested { get; set; }
}

public class NestedSource {
  public int TestInt { get; set; }
  public string TestString { get; set; }
  public string Missing { get; set; }
}

public class TestDestination {
  public int? Nested_TestInt { get; set; }
  public string Nested_TestString { get; set; }
}
```

**Comment by lbargaoanu** [comment]
There is no need to disable validation. But if there are no members other than Nested that you want mapped from TestSource, maybe just forget about it and just map NestedSource?

**Comment by bcallaghan-et** [comment]
`TestSource` is a contrived example to show the flattening behavior. My real model is quite large (100+ properties) and outside of my control. It includes top-level, nested, and deeply nested objects. My ultimate goal is to flatten that model so I can save it into a SQL database with Dapper. So far, I have tried three different mapping configurations. Each of them performs the mapping correctly, if I exclude the call to `AssertConfigurationIsValid`.

This mapping produces incorrect validation that `Nested` has not been mapped.
```csharp
config.CreateMap<TestSource, TestDestination>(MemberList.Source);
```
This mapping produces incorrect validation that `TestInt` and `TestString` have not been mapped.
```csharp
config.CreateMap<TestSource, TestDestination>(MemberList.Source).IncludeMembers(s => s.Nested);
config.CreateMap<NestedSource, TestDestination>(MemberList.Source);
```
This mapping does not throw any validation errors, but it also doesn't catch nested properties that are missing from the destination.
```csharp
config.CreateMap<TestSource, TestDestination>(MemberList.Source).IncludeMembers(s => s.Nested);
config.CreateMap<NestedSource, TestDestination>(MemberList.None);
```

**Comment by lbargaoanu** [comment]
As far as I can tell everything works as it should. So perhaps look for existing tests and docs and try to understand what's the purpose of the different settings. It's debatable what should happen with the default flattening and source validation. But I see you point about that (hence the PR) and, if @jbogard agrees, we'll change the behavior so a flattened member is consider mapped.
