### ISSUE TITLE
ResolutionContext uses Default in Nested Mappings

### ISSUE THREAD

**Issue by stamoun** [AutoMapper/AutoMapper#3218]
[gist](https://gist.github.com/stamoun/5f0762f50ee1d66cfed67fd2e5633712)

### Source/destination types

```csharp
public class Outer
{
    public Inner Inner { get; set; }
}

public class Inner
{
    public int Value1 { get; set; }
    public int Value2 { get; set; }
}

public class Destination
{
    public int Total { get; set; }
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Outer, Destination>()
        .ConvertUsing((src, dest, ctx) =>
        {
            dest = ctx.Mapper.Map(src.Inner, dest ?? new Destination(), options => { options.Items["op"] = "add"; });
            Console.WriteLine($"Total with options: {dest.Total}");

            dest = ctx.Mapper.Map(src.Inner, dest);
            Console.WriteLine($"Total: {dest.Total}");

            return dest;
        });
    cfg.CreateMap<Inner, Destination>()
        .ConvertUsing((src, dest, ctx) =>
        {
            ctx.Items.TryGetValue("op", out var returnedObject);
            dest.Total = returnedObject?.ToString() == "add"
                ? src.Value1 + src.Value2
                : src.Value1 * src.Value2;

            return dest;
        });
}).CreateMapper();

```

### Expected behavior

The nested mapper call should use its own resolution context. I also feel that a copy of the provided `MappingOperationOptions` should be made per context when `Map` is called, the original context options should be immutable.

### Actual behavior

An `InvalidOperationException` is thrown
> You must use a Map overload that takes Action<IMappingOperationOptions>!

### Steps to reproduce

```csharp
var outer = new Outer
{
    Inner = new Inner
    {
        Value1 = 5,
        Value2 = 5
    }
};
// expects to print the following:
// Total with options: 10
// Total: 25
mapper.Map<Destination>(outer);
```

**Comment by lbargaoanu** [comment]
Actually now the context flows by default. That's what some people expected. If you don't want that, cast to `IRuntimeMapper` and pass a new context.

**Comment by lbargaoanu** [comment]
See also https://github.com/AutoMapper/AutoMapper/issues/3206.

**Comment by stamoun** [comment]
Thanks for the quick reply, although I feel that it should be the responsibility of the mapper to generate a new context, not the caller. Providing options to certain methods will modify the default context's options (the behaviour is different whether you use the generic version or not).

Furthermore, why is the ResolutionContext calling the Before/AfterMap, why not leave this entirely in the hands of Mapper?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2937
