### ISSUE TITLE
Update from 8.1.1 to 9

### ISSUE THREAD

**Issue by cgountanis** [AutoMapper/AutoMapper#3219]
I have been putting this off for awhile. Wondering if you can guide me to the right breaking changes upgrade path documentation. I could not find anything and found us just staying on 8.1.1 which means it will eventually just get removed.

![image](https://user-images.githubusercontent.com/14899817/64891721-54c1a400-d638-11e9-9684-3d7d58bba37f.png)

**Comment by jbogard** [comment]
http://docs.automapper.org/en/stable/9.0-Upgrade-Guide.html

**Comment by jbogard** [comment]
We've also got upgrade guides for all the other very major breaking changes in the docs.
