### ISSUE TITLE
Mapping an empty string to a nullable enum default to 0 instead of null

### ISSUE THREAD

**Issue by BryanSan** [AutoMapper/AutoMapper#3220]
### Source/destination types

```csharp
class MyClass
{
    public string StringEnum { get; set; }
}

class MyClass2
{
     public MyEnum? Enum { get; set; }
}

enum MyEnum
{
     Ok = 1,
     NoOk = 2
}
```
### Mapping configuration

```csharp
var mapperConf = new MapperConfiguration(conf =>
{
      conf.CreateMap<MyClass, MyClass2>()
           .ForMember(x => x.Enum, x => x.MapFrom(r => r.StringEnum));
});
```

### Version: 

I tried with 9.0.0, 8.1.1 and 7.0.1 and it didnt work as expected
It works as expected with the version 6.1.1

### Expected behavior

I was expecting a null value in the enum nullable property after the mapping 
In version 6.1.1 when you mapped an empty string property to a nullable enum property it mapped a null value

### Actual behavior

It is mapped a 0

### Steps to reproduce

```csharp
var mapperConf = new MapperConfiguration(conf =>
{
    conf.CreateMap<MyClass, MyClass2>()
         ForMember(x => x.Enum, x => x.MapFrom(r => r.StringEnum));
});

var mapper = mapperConf.CreateMapper();

var myclass = new MyClass
{
   StringEnum = ""
};

var mappedObject = mapper.Map<MyClass2>(myclass);
Debug.Assert(mappedObject.Enum.HasValue == false) // This has the value of 0 instead of null;
```

I couldn't find any information related to this change of behaviour. Is it intented? And if so, could you give me some ideas of what I could change to have the old behavior?

**Comment by jbogard** [comment]
Empty string is not null though?

**Comment by BryanSan** [comment]
When I am referring to ”empty string” I mean ”” or string.empty. Sorry for the confusion

________________________________

**Comment by lbargaoanu** [comment]
What @jbogard is saying is that `null` is special cased in AM, "" not so much.

**Comment by BryanSan** [comment]
Oh I see! So, any ideas what could have happened with the behaviour of the 6.1.1 version?

**Comment by lbargaoanu** [comment]
I think that you should implement this in your own code.

**Comment by BryanSan** [comment]
Do you know if there is a way of configuring a special Resolver for every enum? So I can handle this scenario manually?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/6354d80c51f31f3bdb36002b5f360ebdab55b4db/src/UnitTests/Mappers/CustomMapperTests.cs#L134

**Comment by BryanSan** [comment]
Thank you very much, sorry for the inconvenience. Have a nice day!
