### ISSUE TITLE
the encode of file "Internationalization.cs" is right?

### ISSUE THREAD

**Issue by frankbsd** [AutoMapper/AutoMapper#3221]
the codepage of the source file named "Internationalization.cs" in UnitTests directory is ISO-8859-2, is it right?

**Comment by lbargaoanu** [comment]
Why would that be relevant?

**Comment by frankbsd** [comment]
Visual studio 2019 complains, it can't work

**Comment by lbargaoanu** [comment]
It works for us. Try StackOverflow or a VS forum.

**Comment by frankbsd** [comment]
OK!Thanks!
