### ISSUE TITLE
Test on all mapper.Map<>() calls in project

### ISSUE THREAD

**Issue by AlexanderVlassov** [AutoMapper/AutoMapper#3222]
### Problem:
By calling the
```csharp
mapper.Map<TDest>(tSourceObject)
```
method, you can try to map an object of absolutely any type to any other type. And this is not limited by the compiler and is not covered by the mapper configuration test.

### Suggestion/Idea:
A test that would find all the `.Map<>()` calls. Create a hash table of `TSource-> TDest` on them and check mapping ability.

My idea was to perform each mapping:
```csharp
mapper.Map<TDest>(fixture.Create<TSourse>()));
```
But finding all the `.Map<>()` calls turned out to be too complicated for me.
I see the one solution with `CSharpSyntaxTree.ParceText("mySourceFile.sc")`.

On the other hand, this seems to be a cool feature for the mapper - to have a test for all the mapping attempts in the project next to the configuration test.

### ps:
AutoMapper is cool, thank you for it )

**Comment by jbogard** [comment]
It's an interesting idea, filling a gap in `AssertConfigurationIsValid`, how would this work, though?

For our clients, we also have tests covering every `Map` call through some unit/integration test. It's not testing `Map` directly, but the method that `Map` is in. So this:

https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity/Pages/Students/Index.cshtml.cs#L126

Is covered by this:

https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity.IntegrationTests/Features/Students/IndexTests.cs#L15

**Comment by lbargaoanu** [comment]
Someone could write a Roslyn analyzer for this, but this is way outside the scope of AM itself :)
