### ISSUE TITLE
ReplaceMemberName with RecognizeDestinationPostfixes

### ISSUE THREAD

**Issue by bcallaghan-et** [AutoMapper/AutoMapper#3224]
### Source/destination types

```csharp
public class TestSource {
  public string IndustryCd { get; set; }
}
public class TestDestination {
  public string PrefixIndustryCode { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(config => {
    config.ReplaceMemberName("Cd", "Code");
    config.RecognizeDestinationPrefixes("Prefix");
    config.CreateMap<TestSource, TestDestination>();
});
configuration.AssertConfigurationIsValid();
var mapper = configuration.CreateMapper();
```

### Expected behavior

AutoMapper should have expanded the segment `Cd` into `Code` and ignored the prefix `Prefix` on the destination property. The value of `IndustryCd` should be copied into `PrefixIndustryCode`.

### Actual behavior

A validation exception is thrown stating that no value could be mapped into `PrefixIndustryCode`. If validation is disabled for that map, then the property is left `null`.

### Steps to reproduce

```csharp
var source = new TestSource { IndustryCd= "Hello World" };
var destination = mapper.Map<TestDestination>(source);
```

**Comment by lbargaoanu** [comment]
Apparently they don't mix. But you can achieve what you want by using only one of them.

**Comment by lbargaoanu** [comment]
As far as I can tell, that's the intent of the current implementation. If you want to investigate this further, you're welcome to do so.

**Comment by bcallaghan-et** [comment]
@lbargaoanu What settings do I need to produce the results I'm looking for? This scenario is replicated many times through my system, and I would rather not map all of those properties explicitly. In addition, I have many properties that use the same ReplaceMemberName rule (without prefixes) and many properties that use the same Prefix rule (without ReplaceMemberName). Since I already had both rules in place, I assumed AutoMapper would apply both at the same time.

**Comment by lbargaoanu** [comment]
Well, as I've said, it doesn't, so you should write your code so you use only one of them.

**Comment by TylerCarlson1** [comment]
One option is to use `config.ReplaceMemberName("Prefix", "");` to use at the same level as the other replace, but it will replace everywhere not just in the front.

**Comment by bcallaghan-et** [comment]
@TylerCarlson1 That may be an option for me, but won't that replace Source prefixes? Or does ReplaceMemberName work in both directions?
