### ISSUE TITLE
Crash when using AddDataReaderMapping

### ISSUE THREAD

**Issue by iulian0512** [AutoMapper/AutoMapper#3226]
https://gist.github.com/iulian0512/b8a36633eca9dfa91a88fd94ae2dbac8

using AutoMapper;
using AutoMapper.Data;
using System;
using System.Collections.Generic;
using System.Data;

namespace automappercrash
{

    public interface dummyinterface
    {
        string test();
    }

    public class dummy1
    {
        public string name { get; set; }
        public dummyinterface tintf { get; set; }
    }

    public class dummy2
    {
        public string aaa { get; set; }
        public dummy1 test { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                //this causes the crash, without it this example runs without any exceptions
                cfg.AddDataReaderMapping();

                cfg.CreateMap<IDataRecord, dummy2>()
                .ForMember(dto => dto.aaa, o => o.MapFrom(a => a["test"]))
                .ForAllOtherMembers(a => a.Ignore());
                

            });
        }
    }
}

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Data/
