### ISSUE TITLE
Global ReplaceMemberName does not apply to Profiles

### ISSUE THREAD

**Issue by bcallaghan-et** [AutoMapper/AutoMapper#3227]
### Source/destination types

```csharp
public class TestSource {
  public string OrgName { get; set; }
}
public class TestDestination {
  public string OrganizationName { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(config => {
  config.ReplaceMemberName("Org", "Organization");
  config.AddProfile<TestProfile>();
});

public class TestProfile : Profile {
  public TestProfile() {
    CreateMap<TestSource, TestDestination>();
  }
}
```

### Expected behavior

The source property `OrgName` should be mapped to the destination property `OrganizationName`. The configured replacement should apply to all maps created, even those created in separate profiles. This behavior is specified in the documentation.

> Configuration inside a profile only applies to maps inside the profile. Configuration applied to the root configuration applies to _all_ maps created. (emphasis in original, [Documentation](http://docs.automapper.org/en/stable/Configuration.html))

### Actual behavior

When validated, an exception is thrown stating that `OrganizationName` is not mapped. Similarly, validating the source members throws an exception that `OrgName` is not mapped. Disabling validation produces a `null` result in the destination object. If the map is moved up to the global configuration, or if `ReplaceMemberName` is moved down into the profile, the mapping and validation complete as expected.

### Steps to reproduce

```csharp
configuration.AssertConfigurationIsValid();
var mapper = configuration.CreateMapper();
var source = new TestSource { OrgName = "Hello World" };
var destination = mapper.Map<TestDestination>(source);
```

**Comment by lbargaoanu** [comment]
A PR is welcome. The inheriting of the global configuration should happen [here](https://github.com/AutoMapper/AutoMapper/blob/5c52df3a37b6c104ac5b01c4cf7cd10b8730b2bf/src/AutoMapper/ProfileMap.cs#L40).
