### ISSUE TITLE
IgnoreMap didn't work  when i used static api in v8.1.0

### ISSUE THREAD

**Issue by aixinjueluogu** [AutoMapper/AutoMapper#3232]
### Source/destination types

```csharp
// Put your source/destination types here


    public class PageList<T>
    {
        public int totalCount { get; set; }
        public IEnumerable<T> datas { get; set; }

    }

    public class Destination
    {
        public int id { get; set; }
        [IgnoreMap]
        public string RoleNames { get; set; }

        public string ProductName { get; set; }
    }


    public class Source
    {
        public int id { get; set; }
        public string ProductName { get; set; }
    }

 Source source = new Source { id = 1, ProductName = "123" };
            PageList<Source> modelList = new PageList<Source>();
            var list = new List<Source>();
            list.Add(source);
            modelList.datas = list;

            PageList<Destination> model2 = modelList.MapTo<PageList<Destination>>();

```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```
   Mapper.Initialize( config => {
                            config.CreateMap( sourceType, destinationType ).ReverseMap();
                        } );
 return Mapper.Configuration.ResolveTypeMap( sourceType, destinationType );
### Expected behavior

datas
 ---> AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
==================================================================================================================================================
AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
Source -> Destination(Destination member list)
Console1.Source -> Console1.Destination(Destination member list)

Unmapped properties:
RoleNames

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
