### ISSUE TITLE
IncludeBase vs ForAllOtherMembers again

### ISSUE THREAD

**Issue by Fluttercom** [AutoMapper/AutoMapper#3235]
I need to map a lot of classes from IDataReader and I'd like to escape boilerplating all props.
So my code mostly look like this:

```csharp
CreateMap<IDataReader, Dest>()
                .IncludeBase<IDataReader, Base>()
                .ForMember(d => d.Name, opt => opt.MapFrom(src => src["AnotherName"]))
                .ForAllOtherMembers(opt => opt.MapFrom(src => src[opt.DestinationMember.Name]));
```

### Expected behavior

ForAllOtherMembers doesn't ignore IncludeBase

### Actual behavior

It does, and I saw discussions saying this not a bug, but feature. So is there anything else I can do to map without explicitly configuring every property?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Data
