### ISSUE TITLE
Enum value mapping and assertion

### ISSUE THREAD

**Issue by HenkKin** [AutoMapper/AutoMapper#3244]
A few years ago I implemented an extension to AutoMapper to handle enum value mapping. Especially having control about the enum values by AssertConfigurationIsValid would be nice. 

I created a github with a working example: https://github.com/HenkKin/Enums.Extensions.AutoMapper

### Source/destination types

```csharp
public enum Source
{
    Default = 0,
    First = 1,
    Second = 2
}

public enum Destination
{
    Default = 0,
    Second = 2
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>()
     .AsEnumMap(EnumMappingType.Value) // OR EnumMappingType.Name
     .MapFromEnumValue(Source.First, Destination.Default); 
```

### Testing

```csharp
[Fact]
public void WhenProfilesAreConfigured_ItShouldNotThrowException()
{
    // Arrange
    var config = new MapperConfiguration(configuration =>
    {
        configuration.AddMaps(typeof(AssemblyInfo).GetTypeInfo().Assembly);
    });

    // default automapper assertions
    config.AssertConfigurationIsValid();

    // Assert
    config.AssertEnumConfigurationIsValid(); // this line asserts all enum value mapping configs
}
```
### Feature request
It would be nice when the mapping functionality will become default functionality of AutoMapper. 
- CreateMap -> should support enum mapping directly without calling AsEnumMap
- AssertConfigurationIsValid -> should include validating enum mapping too.

**Comment by lbargaoanu** [comment]
You can add custom validations through an extension point. See [here](https://github.com/AutoMapper/AutoMapper/blob/7a00700de61cd3234b6a6eb4bf0f6bbe402369b1/src/UnitTests/ConfigurationValidation.cs#L30).

**Comment by HenkKin** [comment]
> You can add custom validations through an extension point. See here.

This is not working for TypeMaps with ConvertUsing (ITypeConverter). These TypeMaps will bypas this validation extions point. I've  already tried it.

**Comment by lbargaoanu** [comment]
Well, you write the code there, so you can do whatever. Other than that, I guess it could. A PR is welcome.
