### ISSUE TITLE
ProjectTo doesn't work with EF Core 3 and GroupBy

### ISSUE THREAD

**Issue by MihaMarkic** [AutoMapper/AutoMapper#3245]
### Source/destination types

```csharp
// Entity
public class Party {
  public int Id { get; set; }
  public string Name { get; set; }
  public byte[] RowVersion { get; set; } // timestamp type in SQL Server
}

// Model is the same
public class PartyEditModel {
  public int Id { get; set; }
  public string Name { get; set; }
  public byte[] RowVersion { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Party, PartyEditModel>();
```

### Version: x.y.z
Automapper 9.0.0
EF Core 3.0.0

### Expected behavior

```csharp
db.Party.ProjectTo<PartyEditModel>(mapper.ConfigurationProvider).GroupBy(p => p.LastName).Select(g => new { g.Key, count = g.Count() }).ToArray();
```

Should group normally.

### Actual behavior

An exception is thrown
`System.InvalidCastException: 'Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.ColumnExpression' to type 'System.Linq.Expressions.ConstantExpression'.'`

### Steps to reproduce

Run this statement
```csharp
`db.Party.ProjectTo<PartyEditModel>(mapper.ConfigurationProvider).GroupBy(p => p.LastName).Select(g => new { g.Key, count = g.Count() }).ToArray();`
```

Note that byte[] mapping is causing problems. When removed on model, the grouping works.

**Comment by lbargaoanu** [comment]
`ProjectTo` should be the last call in the chain.

**Comment by MihaMarkic** [comment]
@lbargaoanu Nope, why would it? EF Core can deal with projections as long as they are executed on serer side. And again, the problem is mapping of byte[] property (RowVersion in my sample) only, not with projections in general.

**Comment by lbargaoanu** [comment]
If it can deal with them, than just forget about AM and simply write that query using LINQ.

**Comment by MihaMarkic** [comment]
So, instead of fixing what seems to be a bug, you are proposing to ditch AM instead?

**Comment by lbargaoanu** [comment]
No, I'm explaining how to remove AM from the equation.

**Comment by MihaMarkic** [comment]
Sorry, I don't follow. Why would I remove it? It's a great tool. Yet it somehow produces wrong mapping for byte array.

**Comment by jbogard** [comment]
Try mapping without AutoMapper to see if it works.

**Comment by MihaMarkic** [comment]
If it didn't work, I wouldn't be reporting it. I'll be triple checking it, but I'm pretty confident that it works if I do a projection without AM.
I'll try comparing expressions of possible as well.

**Comment by jbogard** [comment]
That’s what you’ll need to do because EF Core has a funny habit of
evaluating expressions it doesn’t understand client-side.

**Comment by MihaMarkic** [comment]
Guys, sorry, was my fault afterall. After digging around, it was my custom ITypeConverter<byte[], byte[]> that is causing these problems. Which I added because of another problem regarding EF row versioning, but I'll create another ticket for it.

**Comment by MihaMarkic** [comment]
I case you wonder why I went with custom type converter, here is the possible issue with [EF Core](https://github.com/aspnet/EntityFrameworkCore/issues/18505) and here is my [stackoverflow question](https://stackoverflow.com/questions/58500007/copy-array-instead-of-simply-assigning-a-reference-on-projection).
