### ISSUE TITLE
EF Core Null Check Navigation Property

### ISSUE THREAD

**Issue by MattHartz** [AutoMapper/AutoMapper#3246]
Hi,

First off, if this is not an Automapper and is an EF Core issue, if there is no way around this, this will mean EF Core is a no go. If there are alternative ways to solve this issue, insight would be truly appreciated.

I am experiencing an issue when trying to map a nested database model into a (mostly) flattened DTO object and default all null navigation properties.  Unfortunately, there are situations where a database model might be 5 levels deep, this.that.something.whatever.ok that might have "something" as null.

When using the same database model with EF6, this is handled perfectly fine, and resolves the whole map to null. But now, i am getting "nullable object must have a value" or if i enable "EnableNullPropagationForQueryMapping" I get "Object reference not set to an instance of an object."

I can post a gist if needed, and the expression tree. It appears with "EnableNullPropagationForQueryMapping" it does add the null checks which makes sense,  but from the warning that it provides, it seems like this may be a known issue... but i'm not finding much help via Google searches.

Thanks for the help!

**Comment by lbargaoanu** [comment]
If it works with EF6, then most likely it's an EF Core issue and you should take it to them.
