### ISSUE TITLE
Mocking the context mapper

### ISSUE THREAD

**Issue by joao29a** [AutoMapper/AutoMapper#3251]
There was a change in AutoMapper 9 where the Mapper property from the ResolutionContext class returns the class itself as a IRuntimeMapper. With this change I'm unable to mock the return of Map on my tests. 

This is how I was doing:
```csharp
_mappingOperationOptions = Substitute.For<IMappingOperationOptions>();
_runtimeMapper = Substitute.For<IRuntimeMapper>();
_resolutionContext = new ResolutionContext(_mappingOperationOptions, _runtimeMapper);

_runtimeMapper.Map<List<Dto>>(Arg.Is(dto))
                .Returns(listOfDtos);
```

Before, the Mapper property was returning the instance I was injecting in the constructor, so I was able to unit tests my classes that implemented ITypeConverter. Is there any way to add a new method on ITypeConverter changing the ResolutionContext parameter to IRuntimeMapper? This way I'll be able to mock the context and unit test my converters.

**Comment by lbargaoanu** [comment]
There is no need to mock `IMapper`. You should just use the real mapper instance.

**Comment by joao29a** [comment]
I get it what I have to do. I have to mock the IRuntimeMapper methods instead of IMapper, like this:

```csharp
_runtimeMapper.Map(
                    Arg.Is(dto),
                    Arg.Any<object>(),
                    Arg.Any<Type>(),
                    Arg.Any<Type>(),
                    Arg.Is(_resolutionContext))
                .Returns(listOfDto);
```
