### ISSUE TITLE
Mapper not initialized. Call Initialize with appropriate configuration

### ISSUE THREAD

**Issue by MrChriZ** [AutoMapper/AutoMapper#3255]
I'm trying to make use of an extension described in this question here originally made by SuperJMN and then updated by David Bond for Automapper version 8 (which is the version I have installed):

https://stackoverflow.com/questions/49799389/how-to-make-automapper-truncate-strings-according-to-maxlength-attribute

The extension truncates strings according to the Entity Framework MaxLength attribute.

However I'm running into a problem where with the extension hooked up to the createMap
I get an exception:
'Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance'

I think I can see why - I think  Mapper.Configuration.GetAllTypeMaps() is essentially being used before the Mapper instance has been initialized - because it's part of the initialization.  I just have no idea if it's possible to fix it or how to go about doing so.
I've found similar issues here but the resolutions are quite different to what's I'm trying to achieve.

I've also tried using both static and non-static instances of AutoMapper - but this didn't make any difference.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
