### ISSUE TITLE
Mapping of ICollection property with inheritance and IMemberValueResolver

### ISSUE THREAD

**Issue by Spitfire90** [AutoMapper/AutoMapper#3256]
Hello,

I try to migrate my project from 3.3.1 to 9.0.0 (mainly because we faced unexplainable missing mapping exceptions at run time after few days of uptime)
I face a lot of difficulties with the version 9 to understand why the mapping of ICollection properties works in some use cases and why it does not work for other. The documentation seems to be only about simple use cases.

My feeling is that there is a regression regarding these features compared to the version 3.
Previously, declaring the mapping for the base models was enough to have the mapping applied on the derived models for ICollection properties
With the new version, it's really difficult to understand why the mapping is not applied to the derived models.

I have done some tests with ICollection properties associated to inheritance and customer resolver (through IMemberValueResolver). I tried to force the UseDestinationValue as well but the mapping behavior is even not the same depending on the fact that both target and source have or not the same property name.

```csharp
// All these mappings declared on base types are ignored for the derived types (Model & CollectionModel):
this.CreateMap<DomainModelBase, ModelBase>()
    .Include<DomainModel, Model>()
    .ForMember(sp => sp.CodeList, x => x.MapFrom(sp => sp.CodeList))
    .ForMember(sp => sp.KeyValues, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues))
    .ForMember(sp => sp.KeyValuesOtherName, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues));

this.CreateMap<DomainModelBase, CollectionModelBase>()
    .Include<DomainModel, CollectionModel>()
    .ForMember(sp => sp.CodeList, x => x.MapFrom(sp => sp.CodeList))
    .ForMember(sp => sp.KeyValues, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues))
    .ForMember(sp => sp.KeyValuesOtherName, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues));

this.CreateMap<DomainModel, Model>();

this.CreateMap<DomainModel, CollectionModel>();

```

```csharp
public class ModelBase
{
    public string Code { get; set; }

    public ICollection<KeyValueModel> KeyValues { get; } = new List<KeyValueModel>();

    public ICollection<KeyValueModel> KeyValuesOtherName { get; } = new List<KeyValueModel>();

    public ICollection<string> CodeList { get; } = new List<string>();
}

public class Model : ModelBase
{
}

```

Please see the full example and results of my tests on [Gist](https://gist.github.com/Spitfire90/974ff43ecfc15996a76632753a5857b4)

Any explanations are welcome to understand the behavior :)

(Note that the version where the mapping is declared for all derived types works for all use cases but I don't want to do that due to the repetition - use case when I have 6 derived types)

Thanks.

```csharp
// Number of items in the destination object after mapping:
MappingBaseOnlyConfiguration - Without Forcing UseDestinationValue
Model - CodeList: 0
Model - KeyValues: 0
Model - KeyValuesOtherName: 0
CollectionModel - CodeList: 0
CollectionModel - KeyValues: 0
CollectionModel - KeyValuesOtherName: 0
MappingBaseOnlyConfiguration - With Forcing UseDestinationValue
Model - CodeList: 0
Model - KeyValues: 0
Model - KeyValuesOtherName: 0
CollectionModel - CodeList: 1
CollectionModel - KeyValues: 1
CollectionModel - KeyValuesOtherName: 0
MappingDerivedConfiguration - Without Forcing UseDestinationValue
Model - CodeList: 1
Model - KeyValues: 1
Model - KeyValuesOtherName: 1
CollectionModel - CodeList: 1
CollectionModel - KeyValues: 1
CollectionModel - KeyValuesOtherName: 1
MappingDerivedConfiguration - With Forcing UseDestinationValue
Model - CodeList: 1
Model - KeyValues: 1
Model - KeyValuesOtherName: 1
CollectionModel - CodeList: 1
CollectionModel - KeyValues: 1
CollectionModel - KeyValuesOtherName: 1
```

**Comment by lbargaoanu** [comment]
3.0 was a long time ago. Read carefully all the upgrade guides and you'll have an idea what I mean. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html) and [the docs](http://docs.automapper.org/en/latest/Mapping-inheritance.html).

**Comment by Spitfire90** [comment]
Indeed, 3.0 was a long time ago :)

I read carefully all the upgrade guides and almost of the pages of the documentation.
But there is nothing describing the behavior / the convention for inheritance except this part:

- Explicit Mapping (using .MapFrom())
- Inherited Explicit Mapping
- Ignore Property Mapping
- Convention Mapping (Properties that are matched via convention)

And in my example, I have an explicit mapping (using .MapFrom()) on my base class, but still the mapping is ignored on the derived class.

````csharp
public abstract class DomainModelBase
{
    public string KeyValues { get; set; }
}

public class DomainModel : DomainModelBase
{
}

public class ModelBase
{
    public ICollection<KeyValueModel> KeyValuesOtherName { get; } = new List<KeyValueModel>();
}

public class Model : ModelBase
{
}
````

````csharp
this.CreateMap<DomainModelBase, ModelBase>()
    .Include<DomainModel, Model>()
    .ForMember(sp => sp.KeyValuesOtherName, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues));

this.CreateMap<DomainModel, Model>();
````

In the above (simplified) example, the _KeyValuesOtherName_ property of my destination model is not mapped whereas the mapping for base models is defined. Bug ?

Regarding the execution plan, I tried to check but it's pretty difficult to read.

**Comment by lbargaoanu** [comment]
I doubt it. Your example is way too complicated for me to follow. If you can make a basic repro, like [this](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9), I'll take a look.

**Comment by Spitfire90** [comment]
I tried to simplify the most possible my first example.
This is the new version of the [repo](https://gist.github.com/Spitfire90/46bbb64dcd41a8b299fdb52b7eadb0c1)

It's about a abstract class that contains 2 ICollection properties where one of the 2 uses a custom resolver. The target never contains the item of the source object after mapping due to the fact that the mapping is only declared for the abstract models.

Thank you :)

**Comment by lbargaoanu** [comment]
Remove the dependency on json and ForAllPropertyMaps.

**Comment by Spitfire90** [comment]
Sorry, what do you mean ? The dependency on json (Newtonsoft) is required by the custom resolver to deserialize a string (OK it's one example of an usage of a IMemberValueResolver).
About ForAllPropertyMaps, it's ignored for the first test cases and used only for the second test cases.

**Comment by lbargaoanu** [comment]
Reimplement things so that none of that code is needed.

**Comment by Spitfire90** [comment]
I removed the dependency to Newtonsoft.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2194#issuecomment-313434740
Workaround it.

**Comment by Spitfire90** [comment]
Sorry, I don't understand. The comment you mention is about UseDestinationValue which was not inherited but a PR has been created to fix that.

What is the link with my example where the mapping is not inherited ?

**Comment by lbargaoanu** [comment]
I don't know about very old versions, but since UseDestinationValue is false by default, your use case never worked . And the issue I've linked to and a few others explain why.

**Comment by Spitfire90** [comment]
It was working with version 3 because I'm facing this issue only since I have started the migration to version 9. I think UseDestinationValue was not existing in version 3.

I don't blame the fact there are breaking changes between 3 and 9 (I understand because it's a gap !) but I'm disappointed that there is no solution/option to apply the base mapping on derived types that works whatever the use case (same or different property names, with or without IMemberValueResolver).

Finally I have only 2 possibilities:
- Repeat the mapping definition which was on my base mapping to all derived mappings (heavy !)
- Add a private setter to all ICollection properties (break the [CA1811](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1811?view=vs-2019) rule)

Not good solution regarding good practices and maintenability...

Anyway, thank you for the time you spent reading and analyzing my problem ;)

**Comment by lbargaoanu** [comment]
All you need is to set `UseDestinationValue`.

**Comment by Spitfire90** [comment]
No sorry, it does not work (see my previous gist example with and without UseDestinationValue scenario).
See as well the following example with UseDestinationValue explicitly declared for the base mapping:

````csharp
 this.CreateMap<DomainModelBase, ModelBase>()
     .Include<DomainModel, Model>()
     .ForMember(sp => sp.CodeList, x => x.MapFrom(sp => sp.CodeList))
     .ForMember(sp => sp.CodeList, x => x.UseDestinationValue())
     .ForMember(sp => sp.KeyValuesOtherName, x => x.UseDestinationValue())
     .ForMember(sp => sp.KeyValuesOtherName, x => x.MapFrom<JsonMemberValueResolver, string>(sp => sp.KeyValues));

 this.CreateMap<DomainModel, Model>();
````

All collection properties of the target are empty.
UseDestinationValue() does not work or it's not inherited.

````
Model - CodeList: 0
Model - KeyValuesOtherName: 0
````

**Comment by lbargaoanu** [comment]
Of course it's not inherited, that's what my answer linked to.

**Comment by Spitfire90** [comment]
Do you know why this change (issue [2880](https://github.com/AutoMapper/AutoMapper/issues/2880)) was initiated but never implemented ?

Or do you know a workaround to avoid to repeat UseDestinationValue() for all Collection properties of all derived types mappings ?
I have one use case with 6 derived types + a base class with 8 Collection properties, I need to repeat `.ForMember(s => s.[PropertyName], x => x.UseDestinationValue())` 6 times for 8 properties.
