### ISSUE TITLE
How to conditionally ignore mapping for a member

### ISSUE THREAD

**Issue by fingers10** [AutoMapper/AutoMapper#3258]
Dear Team, 

Thanks for this wonderful project. I'm asking here this after doing lots of search. I'm still not able to achieve conditional ignore.

I need to conditionally ignore mapping for two members if the user is not in a specific role. I'm not sure on how to handle this.  Please can you assist me on this? 

### Source/destination types

```csharp

public class BranchViewModel
{
    public bool Lock { get; set; }
    public DateTime ExpireOn { get; set; }
}

public class Branch
{
    public string Lock { get; set; }
    public string ExpireOn { get; set; }
}

```

### Mapping configuration

```csharp
public class BranchProfile : Profile
{
    private readonly HttpContext _httpContext;

    public BranchProfile(IHttpContextAccessor httpContextAccessor)
    {
        _httpContext = httpContextAccessor.HttpContext;

        CreateMap<Branch, BranchViewModel>()
            .ForMember(dest => dest.Lock, opt => opt.Condition(src => _httpContext.User.IsInRole(UserRoles.Master.ToString())))
            .ForMember(dest => dest.ExpireOn, opt => opt.Condition(src => _httpContext.User.IsInRole(UserRoles.Master.ToString())));
    }
}
```

### Version: 7.0.0
 I'm using `AutoMapper.Extensions.Microsoft.DependencyInjection 7.0.0` in my `Asp.Net Core 3.0` project

### Expected behavior

I would like to ignore the mapping if the user is not in a master role.

### Actual behavior

>No parameterless constructor defined for type 'BranchProfile'

If I remove the deoendency injection in profile how can I get access to `HttpContext`? Do I need to write a separate class and have the logic's there? Please assist

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by fingers10** [comment]
Here is how I achieved my requirement. Posting the answer here so that this might help someone. More details can be found in [StackOverflow](https://stackoverflow.com/questions/58760104/how-to-conditionally-map-ignore-properties-based-on-user-role-in-automapper-in-a).

I used `IMappingAction` because it supports DI and I injected `IHttpContextAccessor` and used `AfterMap` to map/reject(reset to original values) mappings based on user role.

**Mapping Profile:**
```c#
public class BranchProfile : Profile
{
    public BranchProfile()
    {
        CreateMap<Branch, BranchEditViewModel>()
            .AfterMap<MapOnlyForMasterUserAction>();;
    }
}
```

**IMappingAction:**

```c#
public class MapOnlyForMasterUserAction : IMappingAction<BranchEditViewModel, Branch>
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public MapOnlyForMasterUserAction(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
    }

    public void Process(BranchEditViewModel source, Branch destination, ResolutionContext context)
    {
        if (!_httpContextAccessor.HttpContext.User.IsInRole(IdentityEnums.UserRoles.Master.ToString()))
        {
            destination.Lock = source.Lock.ToString();
            destination.ExpireOn = source.ExpireOn.ToShortDateString();
        }
    }
}
```
