### ISSUE TITLE
Outdated API

### ISSUE THREAD

**Issue by CasperWSchmidt** [AutoMapper/AutoMapper#3260]
The documentation for [Simple Injector](http://docs.automapper.org/en/stable/Dependency-injection.html#simple-injector) and [Assembly scanning](http://docs.automapper.org/en/stable/Configuration.html#assembly-scanning-for-auto-configuration) mentions a method `MapperConfigurationExpression.AddProfiles(typeof(SomeProfile).Assembly)` but this does not exist (I checked 8.1.1 sourcecode as well and nothing there either). Instead AddMaps should be used.

**Comment by lbargaoanu** [comment]
A PR is welcome.
