### ISSUE TITLE
Misleading error message in IncludeMembers()

### ISSUE THREAD

**Issue by glatzert** [AutoMapper/AutoMapper#3261]
If you use `IncludeMembers()`, which supports direct members only, you'll get a misleading error message, if you attempt to do a path expression.

> System.ArgumentException: Property 'Leaf Leaf' is not defined for type 'Root' (Parameter 'property')

I think, there should either be a clear error message, that IncludeMembers does not support Path-Expressions, or that Path-Expressions should be supported here.

See gist for a reproduction: https://gist.github.com/glatzert/973b777784b80237ce2ccd0e73870066

**Comment by lbargaoanu** [comment]
I don't see it. Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build. Or change the repro.

**Comment by glatzert** [comment]
Ah well, you fixed it via 1b27cefc70289159f1f8be229611847e0b8b3051
Thanks for your outstanding work :)

**Comment by lbargaoanu** [comment]
You're welcome :)
