### ISSUE TITLE
Add custom configuration support (e.g., RecognizePostfixes) for mapping from Dictionary<string, object> and ExpandoObject

### ISSUE THREAD

**Issue by NeoXtreem** [AutoMapper/AutoMapper#3262]
Take a scenario where a `Dictionary<string, object>` (or `ExpandoObject`) is to be mapped to a class `Bar` where the source keys (or property names) have postfixes which are configured in AutoMapper using `RecognizePostfixes`:

    var mapper = new Mapper(new MapperConfiguration(cfg =>
    {
        cfg.RecognizePostfixes("Postfix");
    }));
    
    var foo = new Dictionary<string, object> {{"XPostfix", 1}, {"YPostfix", 2}};
    var bar = mapper.Map<Bar>(foo);

`Bar` is defined as:

    class Bar
    {
        public int X;
        public int Y;
    }

Currently, the properties are not mapped unless the source keys and destination property names match. AutoMapper supports both `Dictionary<string, object>` and `ExpandoObject` (as per [here](http://docs.automapper.org/en/stable/Dynamic-and-ExpandoObject-Mapping.html)), but seemingly without support for configuration options such as `RecognizePostfixes`.

Could configuration support be added for `Dictionary<string, object>` and `ExpandoObject` just as with regular types?

**Comment by NeoXtreem** [comment]
@ploeh @moodmosaic Apologies, I accidentally created this issue on this project when it should have been created under AutoMapper.  Please could you delete this issue (not just close it, but delete completely so it's removed from my profile history)?  Thanks!

**Comment by lbargaoanu** [comment]
We're not going to implement that.

**Comment by NeoXtreem** [comment]
@jbogard Please could you take a proper look at this and provide a more considered response. I took the time to put this issue together, and @lbargaoanu has been rude on [more than one occasion](https://stackoverflow.com/questions/58847135/how-to-add-custom-configuration-such-as-recognizepostfixes-to-automapper-for-map?noredirect=1#comment104083672_58847135) without providing any reasonable response or explanation. This is not how contributors or members of the community should be spoken to or dealt with when they are spending their own time trying to help your project. It's the height of disrespect.

**Comment by jbogard** [comment]
There are a l-o-o-o-t of configuration options that don't work/make sense for dictionary/expando. Really, I'd like to move those out of the core project and into an extensions library like we did for AutoMapper.Data.

I don't use the dictionary/expando support, either, so maybe the best thing is to move it out so that people that do care about that stuff can contribute directly?

**Comment by lbargaoanu** [comment]
Perhaps. But I would guess then people will ask for an AM API for the matching logic. And we're back to square one.

**Comment by jbogard** [comment]
Sure but like AutoMapper.Data, rely on people using the feature to extend it. I don’t use it so I don’t really have any motivation to support it.
