### ISSUE TITLE
Custom validator for custom converters

### ISSUE THREAD

**Issue by radistmorse** [AutoMapper/AutoMapper#3263]
Right now ```AssertConfigurationIsValid``` omits all the mappers defined with the custom type converters. It would be nice to be able to write such converters together with the validation code, something like
```csharp
public interface ITypeConverterWithValidation<TSource, TDestination> : ITypeConverter<TSource, TDestination>
{
    void Validate(ValidationContext context);
}

public class MyTypeConverter : ITypeConverterWithValidation<FromType, ToType>
{
    public ToType Convert(FromType source, ToType destination, ResolutionContext context)
    {
        // conversion code goes here
    }

    public void Validate(ValidationContext context)
    {
        // validation code goes here
    }
}

var configuration = new MapperConfiguration(cfg => cfg.CreateMap<FromType, ToType>()
     .ConvertUsing<MyTypeConverter>());

configuration.AssertConfigurationIsValid(); // custom validation code is run
```

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by lbargaoanu** [comment]
Actually I'm not sure this is such a good idea. Rather I think this case should be covered by the general extension point and then you could implement this outside AM.

**Comment by radistmorse** [comment]
The general extension point is inaccessible if you use Profiles and DI. The only place where you access the configuration expression is Startup (in case of ASP core) and that is definitely not the place to deal with mapper validators. Another extension point in profiles would solve this though.

**Comment by radistmorse** [comment]
@lbargaoanu can I make a suggestion to move the AdvancedConfiguration field from MapperConfigurationExpression to Profile. Most of the stuff in there are lists, so it'll be easy to just combine all of them during the construction of MapperConfiguration. The only non-combinable items are AllowAdditiveTypeMapCreation and MaxExecutionPlanDepth. The values from there can be ignored, or some special logic introduced.
This will allow to set the advanced behavior together with the mappers when the profile-based configuration is used

```csharp
    public class MapperProfile : Profile
    {
        public MapperProfile()
        {
             CreateMap<Source, Dest>()
                 .ConvertUsing<MyTypeConverter>();
             Advanced.Validator(MyTypeConverter.Validate);
        }
    }

    var configuration = new MapperConfiguration(cfg => cfg.AddProfile<MapperProfile>());
    configuration.AssertConfigurationIsValid();
```
