### ISSUE TITLE
Dead links in exception comments

### ISSUE THREAD

**Issue by Bouke** [AutoMapper/AutoMapper#3264]
I came across a comment in `AutoMapperMappingException.cs`:

https://github.com/AutoMapper/AutoMapper/blob/7928353a40bc806eaa8d83ab2e371ab4a1f6390e/src/AutoMapper/AutoMapperMappingException.cs#L12-L17

I tried looking up those links, but both are dead now. I was able to track the first link to: [the new docs site](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/8ey5ey87(v=vs.71)) using the Wayback Machine. However for the second link, I [had no such luck](https://web.archive.org/web/20080101000000*/http://msdn.microsoft.com/library/default.asp?url=/library/en-us/dncscol/html/csharp07192001.asp). Any ideas if there's a new home for the latter URL?

Would you like a PR to clean up this comment?

**Comment by lbargaoanu** [comment]
Yes, please. I would simply remove those comments. What would help I think is some hint to look at `Exception.ToString()` for the full error message.

**Comment by lbargaoanu** [comment]
A XML doc for the type would work.
