### ISSUE TITLE
.Ignore() doesn't work in second level collection mapping

### ISSUE THREAD

**Issue by SnrVnnd** [AutoMapper/AutoMapper#3265]
public class EmployeeEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public List<TaskEntity> Tasks { get; set; }
    }
    public class EmployeeModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public List<int> Salary { get; set; }

        public List<TaskModel> Tasks { get; set; }
    }

    public class TaskModel
    {
        public int TaskId { get; set; }
        public string Name { get; set; }
        public ICollection<TaskUserModel> Users { get; set; }
    }
    public class TaskUserModel
    {
        public int TaskId { get; set; }
        public int UserId { get; set; }
    }

    public class TaskEntity
    {
        public int TaskId { get; set; }
        public string Name { get; set; }
        public ICollection<TaskUserEntity> Users { get; set; }
    }

    public class TaskUserEntity
    {
        public int TaskId { get; set; }
        public int UserId { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg =>
            {

                cfg.CreateMap<EmployeeEntity, EmployeeModel>();
                cfg.CreateMap<EmployeeModel, EmployeeEntity>();

                cfg.CreateMap<TaskEntity, TaskModel>();
                cfg.CreateMap<TaskModel, TaskEntity>().ForMember(z => z.Users, opt => opt.Ignore());

                cfg.CreateMap<TaskUserEntity, TaskUserModel>();
                cfg.CreateMap<TaskUserModel, TaskUserEntity>();
            });
            var entity = new EmployeeEntity()
            {
                Id = 1,
                Age = 5,
                Name = "Joseph",
                Tasks = new List<TaskEntity>() {
                new TaskEntity()
                {
                    Name="X",
                    TaskId=1,
                    Users=new List<TaskUserEntity>() { new TaskUserEntity() {TaskId=1,UserId=2 } }
                }
            }
            };
            var model = new EmployeeModel()
            {
                Id = 1,
                Age = 5,
                Name = null,
                Tasks = new List<TaskModel>() {
                new TaskModel()
                {
                    Name="X",
                    TaskId=1,
                    Users=null // In model i am making it null, but it should brng me taskusers list anyhow.
                } }

            };

            var mapper = config.CreateMapper();
            var updatedEntity = mapper.Map(model, entity);

        }
    }

I am having trouble with .Ignore().
i have employee entity,inside Employee entity i have List_TaskEntity, and inside List_TaskEntity i have List_TaskUserEntity.
and i have dto model of all entities.
What i can't do is, i dont want to allow client to edit List_TaskUserEntity though EmployeeModel, 
so in mapping i want to Ignore 'List_TaskUser' like this;

cfg.CreateMap<TaskModel, TaskEntity>().ForMember(z => z.Users, opt => opt.Ignore()); //doesnt work,
cfg.CreateMap<TaskModel, TaskEntity>().ForMember(z => z.Users, opt => opt.UseDestinationValue()); //doesnt work

Desired result;
whether i edit User collection in Employee model or not, always it should bring me unmodified user entity list after mapping.

Thanks a lot.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
