### ISSUE TITLE
.Net Framework 4.0 support

### ISSUE THREAD

**Issue by ds1709** [AutoMapper/AutoMapper#3269]
The latest version compatible with .Net Framework 4.0 is 6.2.2, but it's behaviour is differ then 9.0.0. Particularly, if constructor of target object has parameters, then for parameter new instanse of parameter will be created on mapping process, despite the fact that parameter object was mapped erlier in this mapping process. It leads to multiple mapped instacnces of original object after map. Such problems are solved in later versions of AutoMapper, but they are incomatible with .Net Framework 4.0. So, is it posible to add .Net Framework 4.0 support in latest version of AutoMapper?

Heare example of configuration, which has different result in versions 6.2.2 and 9.0.0:
# Source class
```csharp
    public sealed class Foo
    {
        public Foo(Foo related)
        {
            Related = related;
        }

        public Foo Related { get; }
    }
```
# Target class
```csharp
    public sealed class Bar
    {
        public Bar(Bar related)
        {
            Related = related;
        }

        public Bar Related { get; }
    }
```
# Test code
```csharp
            var mcfg = new MapperConfiguration(configuration =>
            {
                configuration
                    .CreateMap<Foo, Bar>();
            });

            mcfg.AssertConfigurationIsValid();
            var m = mcfg.CreateMapper();

            var foo1 = new Foo(null);
            var foo2 = new Foo(foo1);
            var fooDto = m.Map<Bar[]>(new[] { foo1, foo2 });

            Console.WriteLine(fooDto[1].Related == fooDto[0]);
            // Writes "False" for version 6.2.2 and "True" for version 9.0.0
```

**Comment by lbargaoanu** [comment]
No. Search the old issues about the back and forth on this.
