### ISSUE TITLE
Mapping to an interface with a read-only property

### ISSUE THREAD

**Issue by Minx-SigEp** [AutoMapper/AutoMapper#3272]
I would like to revive issue #587, and #1104 and create a Pull Request for this feature. This is a desirable feature for a project I am working on, and a feature I think the AutoMapper community would benefit from. 

Before I being work on a pull request I want to get some feedback and ensure I am not overlooking anything

**Goal:**
 - Enhance AutoMapper with the ability to map values to a destination proxy that implements an interface with read-only properties.

**Acceptance Criteria:** 
- Mapping to read-only interface properties must be an opt-in feature to ensure backwards compatibility. 

**Questions:** 
1. Is there a need for this feature to be an opt-in feature? Is there value in continuing to support the current behavior? 
2. Currently `ProxyGenerator.GetProxyType(Type interfaceType)` creates a type with a default (empty constructor) and getters and setters based on the properties defined in the interface. Is there a reason why the ProxyGenerator could not create the proxy with getters and setters all the time? So given the below interface. If the ProxyGenerator creates the proxy as follows would AutoMapper work as expected? If so is this an acceptable solution?  
```C#
public interface IMyData { 
    int Id {get;}
    string Name {get;}
}

public sealed class Proxy_IMyData_1394895904_ : IMyData {
    public int Id {get;set;}
    public string Name {get; set;}
}
```

**Comment by lbargaoanu** [comment]
Interface mapping works by restricting the mapping to what the interface specifies. I think the existing behavior makes a lot of sense. That's the default in AM. Readonly members are ignored. You can always implement this outside AM.

**Comment by lbargaoanu** [comment]
A setting per map for generating a matching constructor seems better. That's the standard way to map readonly members.

**Comment by Minx-SigEp** [comment]
The reason for doing this is to be able to take advantage of the rich feature set AutoMapper provides (flattening, Value Converters, Value Resolvers, Type Converters, etc). While ignoring read-only members is the default and I agree it makes alot of sense I also see value in this workflow as well. 

My use case for this is mapping domain models (concrete types) to Mass-transit immutable messages contracts (interfaces). 
```C#
namespace Application.Contracts
{
    public interface ProductUpdatedIntegrationEvent
    {
        Product Product { get; }
    }
    public interface Product
    {
        /* This is an abridged version of the actual contract. The actual 
           contract is much more verbose. 30 plus properties, with 
           nested objects and collections multiple levels deep */
        long Id { get; }
        string Name { get; }
        ProductStatus Status { get; }
    }
    public enum ProductStatus 
    {
        Hidden,
        Discontinued,
        Inactive,
        Active,
    }
}

public void ExampleMethod(Application.Domain.Models.Product source) {
    var product = _mapper.Map<Application.Contracts.Product>(source);
    await _bus.Publish<Application.Contracts.ProductUpdatedIntegrationEvent>(new { Product = product }, cancellationToken);
}
```

While Mass-transit has the ability to generate proxies for your messages contracts and map data from your source model to the generated proxy it is super basic and inadequate for anything other than happy path. I also would not expect Mass-transit to build a mapper of the same caliber as AutoMapper into their package. things like mapping between enums, flattening, are the value add in this case. 


https://masstransit-project.com/MassTransit/usage/messages.html#messages

**Comment by Minx-SigEp** [comment]
> A setting per map for generating a matching constructor seems better. That's the standard way to map readonly members.

Can you expand on this a little more. I am not sure what you are suggesting

**Comment by lbargaoanu** [comment]
I'd say let's start with a custom solution, outside AM. You can use [`As`](http://docs.automapper.org/en/latest/Mapping-inheritance.html#as) to specify a type implementing your interface. You can customize `ProxyGenerator` to generate [the right constructor](http://docs.automapper.org/en/latest/Construction.html). If that goes smoothly, we'll get @jbogard's input on having this inside AM.

**Comment by Minx-SigEp** [comment]
Sounds good. Will start working on this next week
