### ISSUE TITLE
Issue while installing using Nuget in VS2019 and dotnet core 3.0

### ISSUE THREAD

**Issue by mahitosh** [AutoMapper/AutoMapper#3273]
I want to installing AutomMapper using nuget package manager. I am using VisualStudio 2019 and the project framework is core 3.0
I am getting following error on the console while installing.
**_install-package : Found invalid data while decoding._**

`PM> install-package AutoMapper.Extensions.Microsoft.DependencyInjection -version 6.1.1 -Verbose
Running restore with 12 concurrent jobs.
Reading project file D:\XXX\XXX.Mappings\XXX.Mappings.csproj.
Persisting no-op dg to D:\xxx\obj\EvoWeb.Mappings.csproj.nuget.dgspec.json
Restoring packages for D:\xxx\yyy\EvoWeb.Mappings.csproj...
Restoring packages for .NETCoreApp,Version=v3.0...
  GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json
  OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json 943ms
  GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.1/automapper.extensions.microsoft.dependencyinjection.6.1.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.1/automapper.extensions.microsoft.dependencyinjection.6.1.1.nupkg 12ms
  GET https://api.nuget.org/v3-flatcontainer/automapper/index.json
  OK https://api.nuget.org/v3-flatcontainer/automapper/index.json 235ms
  GET https://api.nuget.org/v3-flatcontainer/automapper/8.1.1/automapper.8.1.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/automapper/8.1.1/automapper.8.1.1.nupkg 13ms
Resolving conflicts for .NETCoreApp,Version=v3.0...
Acquiring lock for the installation of AutoMapper 8.1.1
Acquired lock for the installation of AutoMapper 8.1.1
Installing AutoMapper 8.1.1.
Acquiring lock for the installation of AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.1
Acquired lock for the installation of AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.1
Installing AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.1.
PackageSignatureVerificationLog: PackageIdentity: AutoMapper.Extensions.Microsoft.DependencyInjection.6.1.1 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: True
PackageSignatureVerificationLog: PackageIdentity: AutoMapper.8.1.1 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: True
Completed installation of AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.1
Completed installation of AutoMapper 8.1.1
**_install-package : Found invalid data while decoding._**
At line:1 char:1
+ install-package AutoMapper.Extensions.Microsoft.DependencyInjection - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`

Please note I have tried installing the latest version as well but I am getting same error. Other packages are installing perfectly.
Is there any issue with AutoMapper nuget package? Please guide me how can I resolve this issue.

**Comment by lbargaoanu** [comment]
It works for me. Try StackOverflow.

**Comment by mahitosh** [comment]
Congratulations @lbargaoanu .
