### ISSUE TITLE
IncludeMembers with value type

### ISSUE THREAD

**Issue by antoinebj** [AutoMapper/AutoMapper#3276]
I'm following up on the issue #3090 which was closed with only a workaround.

Unfortunately I cannot use that workaround because I need to provide the equality expressions to AutoMapper.Collection, and they require the generic `IMappingExpression<TSource, TDestination>`, which does not provide the option to specify the member names as strings.

I have identified the cause of that issue that throws the exception "Only member accesses are allowed."
It happens when the members are of value types, or generic types which are unconstrained to reference types (`class` constraint). In the case of the generic types, the `IncludeMembers` needs to be called from a method that is unaware of the actual types assigned to the type parameters.

The expression objects generated are then not of type `MemberExpression`, but of type `UnaryExpression`. That is because the compiler wants to box the value types (or potential value types) into an `object`, as that is the return type of the lambda expressions taken as parameter of `IncludeMembers`.

Basically, the following method is incomplete, and should be amended to look into a `UnaryExpression` when it doesn't find a `MemberExpression`:
```csharp
public static bool IsMemberPath(this LambdaExpression exp) => exp.Body.GetMembers().FirstOrDefault()?.Expression == exp.Parameters.First();
```

### Steps to reproduce

I modified the existing unit test to reproduce the issue. You can copy paste that in the solution.
Adding the `class` constraint to the generic type and changing the struct to a class will make the test pass again. If either of those 2 things isn't done, the test will fail.

```csharp
public class IncludeMembers : AutoMapperSpecBase
{
    class Source<TInner> // where TInner : class
    {
        public string Name { get; set; }
        public TInner InnerSource { get; set; }
        public OtherInnerSource OtherInnerSource { get; set; }
    }
    class InnerSource
    {
        public string Name { get; set; }
        public string Description { get; set; }
    }
    struct OtherInnerSource // replace with class
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
    }
    class Destination
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
    }
    protected override MapperConfiguration Configuration => new MapperConfiguration(cfg=>
    {
        var map = cfg.CreateMap<Source<InnerSource>, Destination>();
        SetupMap(map);
        cfg.CreateMap<InnerSource, Destination>(MemberList.None);
        cfg.CreateMap<OtherInnerSource, Destination>(MemberList.None);
    });
    [Fact]
    public void Should_flatten()
    {
        var source = new Source<InnerSource> { Name = "name", InnerSource = new InnerSource { Description = "description" }, OtherInnerSource = new OtherInnerSource { Title = "title" } };
        var destination = Mapper.Map<Destination>(source);
        destination.Name.ShouldBe("name");
        destination.Description.ShouldBe("description");
        destination.Title.ShouldBe("title");
    }
    private static void SetupMap<TInner>(IMappingExpression<Source<TInner>, Destination> map) // where TInner: class
    {
        map.IncludeMembers(src => src.InnerSource, src => src.OtherInnerSource);
    }
}

```

On a side note, some while ago I submitted a PR for AutoMapper.Collection, which fixed an oversight also related to value types. Those poor value types are begging for attention 😉

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by antoinebj** [comment]
Alright I have a bit of time, I'm taking it, starting to work on it now.
