### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Rendering.SelectList needs to have a constructor with 0 args or only optional args.

### ISSUE THREAD

**Issue by TanvirArjel** [AutoMapper/AutoMapper#3277]
I have two types as follows:

    public class ScheduleALessonInfoDto
    {
        public SelectList LanguageSelectList { get; set; }
        public SelectList LessonTypeSelectList { get; set; }
        public SelectList LessonNameSelectList { get; set; }
        public SelectList LessonOptionSelectList { get; set; }
        public SelectList LessonToolSelectList { get; set; }
    }

    public class ScheduleALessonViewModel
    {
        public SelectList LanguageSelectList { get; set; }
        public SelectList LessonTypeSelectList { get; set; }
        public SelectList LessonNameSelectList { get; set; }
        public SelectList LessonOptionSelectList { get; set; }
        public SelectList LessonToolSelectList { get; set; }
    }

I am trying to map `ScheduleALessonInfoDto` to `ScheduleALessonViewModel`. But if any of the property, for say `LanguageSelectList`, is null in `ScheduleALessonInfoDto` then its not setting null value to the property (`LanguageSelectList`) in `ScheduleALessonViewModel` rather throwing the following exception:

> An unhandled exception occurred while processing the request.
> ArgumentException: Microsoft.AspNetCore.Mvc.Rendering.SelectList needs to have a constructor with 0 args or only optional args.
> Parameter name: type
> lambda_method(Closure , ScheduleALessonInfoDto , ScheduleALessonViewModel , ResolutionContext )

> AutoMapperMappingException: Error mapping types.
> 
> Mapping types:
> ScheduleALessonInfoDto -> ScheduleALessonViewModel
> GlotsALot.Application.DataTransferObjects.LessonScheduleDtos.ScheduleALessonInfoDto -> GlotsALot.Web.ViewModels.LessonScheduleViewModels.ScheduleALessonViewModel
> 
> Type Map configuration:
> ScheduleALessonInfoDto -> ScheduleALessonViewModel
> GlotsALot.Application.DataTransferObjects.LessonScheduleDtos.ScheduleALessonInfoDto -> GlotsALot.Web.ViewModels.LessonScheduleViewModels.ScheduleALessonViewModel
> 
> Destination Member:
> LessonNameSelectList
> lambda_method(Closure , ScheduleALessonInfoDto , ScheduleALessonViewModel , ResolutionContext )

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
