### ISSUE TITLE
Read the Docs Issue.  

### ISSUE THREAD

**Issue by justin-orange** [AutoMapper/AutoMapper#3278]
Can't seem to get anywhere past a single page on read the docs for Auto mapper, that simply has an intro paragraph, a couple of lines about examples and some housekeeping. Is there some sort of docs cotents pages somewhere? The search does work, but isn't there some way to work through the docs in some sort of order?

![image](https://user-images.githubusercontent.com/56176413/70001348-ebf82100-15c1-11ea-8de8-bc9a6e1dffa2.png)

**Comment by lbargaoanu** [comment]
Try again.
