### ISSUE TITLE
Error when doing mulitple ProjectTo layers with EfCore

### ISSUE THREAD

**Issue by Angelinsky7** [AutoMapper/AutoMapper#3280]
Hello,
i'm trying to create an "design guide" for building rest apis in my company and i wanted to have a 3 layers structure.

```
Database Layer : DbSet Entities
Business Layer : Application Models
Api/Rest/External Layer : Dto Object
```

I've successfully manage to do that with the following gist : https://gist.github.com/Angelinsky7/49c86333584e3f9cece44a88e7febd4e

but as you can see i need to use a hack to make this work... (https://gist.github.com/Angelinsky7/49c86333584e3f9cece44a88e7febd4e#file-automapper_bug_lambda_projection-cs-L23-L24), (https://gist.github.com/Angelinsky7/49c86333584e3f9cece44a88e7febd4e#file-automapper_bug_lambda_projection-cs-L89) and (https://gist.github.com/Angelinsky7/49c86333584e3f9cece44a88e7febd4e#file-automapper_bug_lambda_projection-cs-L93)

```
public IEnumerable<SubLayer2> _Subs { get; set; } = new HashSet<SubLayer2>();
public ICollection<SubLayer2> Subs => (ICollection<SubLayer2>)_Subs;

cfg.CreateMap<Layer1, Layer2>()
  .ForMember(p => p._Subs, opt => opt.MapFrom(src => src.Subs));
cfg.CreateMap<Layer2, Layer3>()
  .ForMember(p => p.Subs, opt => opt.MapFrom(src => src._Subs));
```

and i very don't like it (because even if this is working like that, in more complex senarii, it's not working anymore)

if i don't do the hack : https://gist.github.com/Angelinsky7/0e26507c07c066376d5a4de8726dd1f2

In the InMemory EfCore Case with Layer3 as IEnumerable: (i dind't have this one before creating the issue)
`Unhandled exception. System.InvalidOperationException: The LINQ expression 'dtoSubLayer2' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync()`

In the SqlServer EfCore Case with Layer3 as IEnumerable: (what i would like to use)
`InvalidOperationException: When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.`

In all EfCore with Layer3 as ICollection:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.`

What am I doing wrong ? is this totally not possible to do ? Is there a way for me to find NullReferenceException or VisitLambda that pop up the exception and customize this behavior ? It would be perfect to have this kind of solution because i would have exactly what i would like to build my rest api...

### Source/destination types

```csharp
internal class Layer1 {
  public Int64 Id { get; set; }
  public ICollection<SubLayer1> Subs { get; set; } = new HashSet<SubLayer1>();
}

internal class SubLayer1 {
  public Int64 Id { get; set; }
  public Int64 LayerId { get; set; }
}

internal class Layer2 {
  public Int64 Id { get; set; }
  public ICollection<SubLayer2> Subs { get; set; } = new HashSet<SubLayer2>();
}

internal class SubLayer2 {
  public Int64 Id { get; set; }
}

internal class Layer3 {
  public Int64 Id { get; set; }
  public IEnumerable<SubLayer3> Subs { get; set; } = new HashSet<SubLayer3>();
}

internal class SubLayer3 {
  public Int64 Id { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Layer1, Layer2>();
cfg.CreateMap<SubLayer1, SubLayer2>();

cfg.CreateMap<Layer2, Layer3>();
cfg.CreateMap<SubLayer2, SubLayer3>();
```

### Version: x.y.z
```
<PackageReference Include="AutoMapper" Version="9.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
```

### Expected behavior

I should be able to use ProjectTo Multiple time to change layers without having to use a trick to do it. And i should be able to choose between ICollection and IEnumerable when i would like

### Actual behavior

Depending on the implementation one the 3 exceptions rises (most of the time it's the 'VisitLambda' lambda one

### Steps to reproduce

https://gist.github.com/Angelinsky7/0e26507c07c066376d5a4de8726dd1f2

thanks for all the help and thanks for taking the time !!!
(and sorry if this is a efcore issue but i was thinking : "because i can create a "hack" in automapper it's maybe here")

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by Angelinsky7** [comment]
I don't understand, certainly a bug on your part is better suited for so ? I thought that it was for question....
But thanks anyway

**Comment by jbogard** [comment]
As a first step, you should project using "Select" to make sure all this
actually works.

In general, multiple projections is discouraged, just like it would be ...
weird to see multiple "Select" statements in a LINQ query.

You need to isolate if this is an EF Core problem.

**Comment by jbogard** [comment]
And on first glance, I'd say this isn't possible in EF Core, you're trying to map to readonly collections.

For LINQ, you really need to try via a normal `Select` and see if that query makes sense at all. Mapping to readonly collections doesn't make sense for LINQ.

**Comment by Angelinsky7** [comment]
@jbogard thanks for your answer ! i'm not sure i understand why you mean with "you should project using select" but i'll look into it.
If you look at the generated expression with the hack it's working excactly as it should, but if i don't do it "automapper" (not sure about that) create a bad expression three (with too many layers, easier if you see directly the expression debug view)

i don't understand why you say that i map readonly collections...  {get;set;} are public

**Comment by jbogard** [comment]
To debug ProjectTo, first, remove it and replace with `Select` to see if can still work. ProjectTo uncovers lots of problems in the underlying query provider since we do many things that folks don't typically do.

**Comment by Angelinsky7** [comment]
@jbogard thanks for your explanation, it make sense !
so i created this select query : 
```
IQueryable<Layer3> query = ctx.Layer1s.Include(p => p.Subs).Select(p => new Layer2 {
  Id = p.Id,
  Subs = p.Subs.Select(a => new SubLayer2 {
    Id = a.Id
  }).ToList()
}).Select(p => new Layer3 {
  Id = p.Id,
  Subs = p.Subs.Select(a => new SubLayer3 {
    Id = p.Id
  })
});

var resultNotWorking = query.ToList();
```

the created expression :
```
.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.Select(
        .Call Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Include(
            .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[automapper_bug_lambda_projection.Layer1]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[automapper_bug_lambda_projection.Layer1]),
            '(.Lambda #Lambda1<System.Func`2[automapper_bug_lambda_projection.Layer1,System.Collections.Generic.ICollection`1[automapper_bug_lambda_projection.SubLayer1]]>))
        ,
        '(.Lambda #Lambda2<System.Func`2[automapper_bug_lambda_projection.Layer1,automapper_bug_lambda_projection.Layer2]>)),
    '(.Lambda #Lambda3<System.Func`2[automapper_bug_lambda_projection.Layer2,automapper_bug_lambda_projection.Layer3]>))

.Lambda #Lambda1<System.Func`2[automapper_bug_lambda_projection.Layer1,System.Collections.Generic.ICollection`1[automapper_bug_lambda_projection.SubLayer1]]>(automapper_bug_lambda_projection.Layer1 $p)
{
    $p.Subs
}

.Lambda #Lambda2<System.Func`2[automapper_bug_lambda_projection.Layer1,automapper_bug_lambda_projection.Layer2]>(automapper_bug_lambda_projection.Layer1 $p)
{
    .New automapper_bug_lambda_projection.Layer2(){
        Id = $p.Id,
        Subs = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select(
                $p.Subs,
                .Lambda #Lambda4<System.Func`2[automapper_bug_lambda_projection.SubLayer1,automapper_bug_lambda_projection.SubLayer2]>)
        )
    }
}

.Lambda #Lambda3<System.Func`2[automapper_bug_lambda_projection.Layer2,automapper_bug_lambda_projection.Layer3]>(automapper_bug_lambda_projection.Layer2 $p)
{
    .New automapper_bug_lambda_projection.Layer3(){
        Id = $p.Id,
        Subs = .Call System.Linq.Enumerable.Select(
            $p.Subs,
            .Lambda #Lambda5<System.Func`2[automapper_bug_lambda_projection.SubLayer2,automapper_bug_lambda_projection.SubLayer3]>)
    }
}

.Lambda #Lambda4<System.Func`2[automapper_bug_lambda_projection.SubLayer1,automapper_bug_lambda_projection.SubLayer2]>(automapper_bug_lambda_projection.SubLayer1 $a)
{
    .New automapper_bug_lambda_projection.SubLayer2(){
        Id = $a.Id
    }
}

.Lambda #Lambda5<System.Func`2[automapper_bug_lambda_projection.SubLayer2,automapper_bug_lambda_projection.SubLayer3]>(automapper_bug_lambda_projection.SubLayer2 $a)
{
    .New automapper_bug_lambda_projection.SubLayer3(){
        Id = $p.Id
    }
}
```

the culprit seems to be : `Subs = .Call System.Linq.Enumerable.ToList(.Call System.Linq.Enumerable.Select( ` and create the error, instead of being `.Call System.Linq.Enumerable.Select(` and in fact why i need to have the "hack"

and i've got exactly the same result in both case, so in fact this is not an automapper issue, but mine
I'm really sorry for the bad noise.

**Comment by Angelinsky7** [comment]
if i change the Layer2.Sub to an IEnumerable the query is working correctly thought, so there might be something but it's not doing what i would like
