### ISSUE TITLE
New library for AutoMapper.Extensions.EnumMapping

### ISSUE THREAD

**Issue by HenkKin** [AutoMapper/AutoMapper#3282]
Recently i created a pull request to add support for enum value mapping into AutoMapper. This pull request is closed now. I was advised to create an extension library to AutoMapper.

That extension library is ready now: https://github.com/HenkKin/AutoMapper.Extensions.EnumMapping

@jbogard, @lbargaoanu  Please can you create a github repository "AutoMapper.Extensions.EnumMapping" into AutoMapper project?

Then i can create a fork and send a pull request for that extension. 

Same way as AutoMapper.Extensions.ExpressionMapping.

**Comment by jbogard** [comment]
Will do - look for it in the next day or two

**Comment by HenkKin** [comment]
Perfect! Thnx.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping
