### ISSUE TITLE
Feature request: Constructor parameter match using a case-insensitive comparison

### ISSUE THREAD

**Issue by strawd** [AutoMapper/AutoMapper#3283]
Currently in order to override a constructor parameter mapping, one has to introduce a hard-coded string with the name of the constructor parameter:

```C#
.ForCtorParam("paramName", opt => ...)
```

If this was changed or another method was introduced to allow a case-insensitive comparison on the parameter name, then a better approach w.r.t. maintainability could be used in the case where the parameter name matches a property name in all but case:

```C#
.ForCtorParam(nameof(Dog.Name), opt => ...)
```
```C#
class Dog
{
    public Dog(string name)
    {
        Name = name;
    }

    public string Name { get; }
}
```

**Comment by lbargaoanu** [comment]
AM is case insensitive so `name` will be matched from `Name`.

**Comment by strawd** [comment]
@lbargaoanu using AutoMapper 9.0, I get this exception when I try to run the example above:

```
AutoMapper.AutoMapperConfigurationException: 'Dog does not have a constructor with a parameter named 'Name'.
AutoMapperConstructorStuff.Dog'
```

I do not get the exception if I use the string `"name"`

**Comment by strawd** [comment]
The line of code that does the case-sensitive check is here:

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Configuration/CtorParamConfigurationExpression.cs#L34

**Comment by lbargaoanu** [comment]
OK, I thought you were talking about the source object property. You should write your own extension method that takes `Name`, turns it into `name`, and calls `ForCtorParam`.

**Comment by strawd** [comment]
@lbargaoanu there is no 100% reliable way to convert PascalCase to camelCase without using a dictionary. IMHO that's an awfully big requirement to work around something that would be so simple to do within AutoMapper.

**Comment by lbargaoanu** [comment]
@jbogard will re-open the issue if he sees it your way.

**Comment by jbogard** [comment]
Ugh, I don't like this solution. Our "ForMember" has always been case sensitive to avoid ambiguity, and I don't really want to do fuzzy matching on constructor parameters as a one-off. Yes the """"fix"""" is simple but the potential bugs are not.

If there were an idiomatic way to refer to method parameters outside of the method, that would be ideal. I don't want workarounds for missing C# features, though.

**Comment by jbogard** [comment]
Can you post that if possible?

**Comment by strawd** [comment]
```C#
public static class IMappingExpressionExtensions
{
    public static IMappingExpression<TSource, TDestination> ForCtorParam<TSource, TDestination, TMember>(
        this IMappingExpression<TSource, TDestination> mappingExpression,
        Expression<Func<TDestination, TMember>> destinationMember,
        Action<ICtorParamConfigurationExpression<TSource>> paramOptions)
    {
        string memberName = ReflectionHelper.FindProperty(destinationMember).Name;
        ConstructorInfo[] constructors = typeof(TDestination).GetConstructors();

        var matchingConstructorParameterNames = constructors
            .SelectMany(ctor => ctor.GetParameters())
            .Select(param => param.Name)
            .Where(name => string.Equals(name, memberName, StringComparison.OrdinalIgnoreCase))
            .ToHashSet();

        if (matchingConstructorParameterNames.Count == 0)
            throw new ArgumentException($"No constructor parameter names found matching destination member name '{memberName}'", nameof(destinationMember));

        if (matchingConstructorParameterNames.Count > 1)
            throw new ArgumentException($"Multiple conflicting constructor parameter names found matching destination member name '{memberName}'", nameof(destinationMember));

        return mappingExpression.ForCtorParam(matchingConstructorParameterNames.First(), paramOptions);
    }
}
```
