### ISSUE TITLE
Attribute Mapping strategy in a DDD Environment (question / best practices)

### ISSUE THREAD

**Issue by lixaotec** [AutoMapper/AutoMapper#3289]
Dear @jbogard and fellows,

I´m strugglin to adopt Attribute mapping strategy (latest versions feature).

In a DDD scenario I have all my entities in a domain 'layer', and my DTO were moved to a crosscutting layer (in order to share with appservices and repository), i´ll picture it bellow.

However to adopt mapping strategy I would have to reference my domain in the crosscutting layer, what leads me to a circular reference, once mt domain already references my crosscutting.

So what would should be done in this case? How to order my dependencies?

```
1-Api Controllers                                           --> 5 - CrossCutting
                V
2-App Services                                              --> 5 - CrossCutting
                V             |        V
3-Domain Services (entities)   4. Repository                --> 5 - CrossCutting (both 3 and 4 needs)

```

So my DTO are moved to 5.Crosscutting in order to have their translation at app and projections at repository.

My entities are definied at 3.Domain Services.

When I try to reference domain to crosscuttin so I can use attribute mapping I get stuck. 
Should I move my entities to CrossCutting?

[AutoMap(typeof(Order))] <-- 3.Domain
public class OrderDto { <-- 5-Crosscutting
   [SourceMember("OrderTotal")]
   public decimal Total { get; set; }

Thanks in advance.

**Comment by lixaotec** [comment]
Totally non-sense what I have done, 

DTO should never be at CrossCutting, they must stay at appservices, where domain is known.

Hovewer how could repository know appservices?

**Comment by jbogard** [comment]
This sounds like a lot of layers - I just use AutoMapper to project from domain model to DTO. More than that is overkill for a single application.
