### ISSUE TITLE
ProjectTo doe not support runtime polymorphism

### ISSUE THREAD

**Issue by v-pidoplichko** [AutoMapper/AutoMapper#3293]
Hi, we are trying to use ProjectTo<> for entities with runtime polymorphism and getting an error "**Can't compile a NewExpression with a constructor declared on an abstract class**"

We have tried different .NET Core (2.1, 3.1), but the result is the same
AutoMapper: 9.0.0

Code to reproduce

> using AutoMapper;
> 
> using AutoMapper.QueryableExtensions;
> using System;
> using System.Diagnostics;
> using System.Linq;
> 
> namespace RuntimePolymorphism
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             var configuration = new MapperConfiguration(cfg => {
>                 cfg.CreateMap<Order, OrderDto>()
>                     .Include<OnlineOrder, OnlineOrderDto>()
>                     .Include<MailOrder, MailOrderDto>();
> 
>                 cfg.CreateMap<OnlineOrder, OnlineOrderDto>();
>                 cfg.CreateMap<MailOrder, MailOrderDto>();
>             });
> 
>             var mapper = configuration.CreateMapper();
> 
>             var not_mapped = new Order[] {
>                     new OnlineOrder(),
>                     new MailOrder()
>             }
>             .AsQueryable();
> 
>             OrderDto[] mapped1 = mapper.Map<Order[], OrderDto[]>(not_mapped.ToArray());
>             Debug.Assert(mapped1[0].GetType() == typeof(OnlineOrderDto));
>             Debug.Assert(mapped1[1].GetType() == typeof(MailOrderDto));
>             Console.WriteLine("OK");
> 
>             OrderDto[] mapped2 = not_mapped.ProjectTo<OrderDto>(configuration).ToArray();
>             Debug.Assert(mapped2[0].GetType() == typeof(OnlineOrderDto));
>             Debug.Assert(mapped2[1].GetType() == typeof(MailOrderDto));
>             Console.WriteLine("OK");
>         }
>     }
> 
>     public abstract class Order { }
>     public class OnlineOrder : Order { }
>     public class MailOrder : Order { }
> 
>     public abstract class OrderDto { }
>     public class OnlineOrderDto : OrderDto { }
>     public class MailOrderDto : OrderDto { }
> }

Is there any workaround or fix for this?
Thank you!

**Comment by lbargaoanu** [comment]
No, ProjectTo only supports what the EF provider can do.

**Comment by Tasteful** [comment]
@lbargaoanu I think this is supported by both EF and EFCore (https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance) that using discriminator column in database to be able to create the correct concrete type when recreating the object. From the above report it's hard to tell if it is AM or EF that generates the above exception due to lack of callstack.

I haven't check any code in AM about how projections work but I guess that the NewExpression can do conditional findings when the target type is an abstract class to see what the real target type should be dependent on source type and the used configuration.

**Comment by jbogard** [comment]
Try this *without* AutoMapper first. Only some things are supported
directly in LINQ

**Comment by lbargaoanu** [comment]
@Tasteful That's not the same thing as AM polymorphism. That's not supported in EF6. The exact reason why is somewhere in the old issues.
