### ISSUE TITLE
Map and ProjectTo have different behaviors for Guid mapping

### ISSUE THREAD

**Issue by hugoterelle** [AutoMapper/AutoMapper#3294]
I'm not sure that's a bug or a problem due to LINQ.
I have a simple mapping between 2 classes and a query executed with Entityframework Core.

### Source/destination types

```csharp

	public class Category 
	{
		public Guid Id { get; set; }
		public string Label { get; set; }
		/* other properties */
        }

        public class Result
        {
            public string CategoryId { get; set; }
            public string Label { get; set; }
        }

```

### Mapping configuration

```csharp
 public class MappingProfile : Profile
        {
            public MappingProfile()
            {
                CreateMap<Category, Result>()
                    .ForMember(x => x.CategoryId, opt => opt.MapFrom(x => x.Id));
            }
        }
```

### Version: 9.0

EF Core: 2.2.6

### Behavior

When using "ProjectTo" all Ids are returned uppercase (example: 5C7549DA-42A8-4CA1-B41F-256490D77ECC)

When using "Map" all ids are returned lowercase (example: 5c7549da-42a8-4ca1-b41f-256490d77Ecc)

Sometimes, I need to use Map, and sometimes, it's easier to use ProjectTo.
In the client application using all results (a JS frontend), we need always to convert Ids ToLower in order to match ids between datasets.

### Steps to reproduce

With Map: 

```csharp

var list = await _repository.GetAll()
                    .OrderBy(x => x.Label)
                    .ToListAsync(cancellationToken);
return _mapper.Map<IEnumerable<Result>>(list);

```

With ProjectTo:

```csharp

return await _repository.GetAll()
                    .OrderBy(x => x.Label)
                    .ProjectTo<Result>(_mapper.ConfigurationProvider)
                    .ToListAsync(cancellationToken);


```

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). But you can always customize Map to have the case you need.
