### ISSUE TITLE
Ignore Attribute with AutoMap Reverse Attribute not working? 

### ISSUE THREAD

**Issue by lixaotec** [AutoMapper/AutoMapper#3298]
Dear fellows and @jbogard ,

I´m struggling to get a mapping works.

I have a property that is Ignored with Ignore Attribute in a DTO with AutoMap Reverse.

When I try to get from DTO to entity, seem like the ignored attribute is being copied to destiny Entity, wouldn´t it be left on copy when source (dto) has the ignore map?

[AutoMap(typeof(User))] 
public class UserDto { 
public string Name { get; set; }
[Ignore]
public string Password { get; set; }
}
_mapper.Map(dto,user); <-- Password is being copy to user, should that happens?

Thanks in advance

**Comment by lbargaoanu** [comment]
Make a test without attributes. That's the intended behavior.
