### ISSUE TITLE
Automapper and null dictionaries.

### ISSUE THREAD

**Issue by alec-lieberman-ef** [AutoMapper/AutoMapper#3299]
I am using Automapper to patch an object onto itself.

I want to ignore null values from the source object when doing the mapping. This works for collections by using AllowNullCollections = true;. When I have a destination object that contains a dictionary with some elements and I try to map a source object that contains a null dictionary, I expect the null dictionary to be ignored because I am ignoring null collections.

But on my destination object, the Dictionary wind up empty. Is this the expected behavior for Dictionaries?

### Mapping configuration

```csharp
public class PatchProfile<T> : Profile
    {
        public PatchProfile()
        {
            AllowNullCollections = true;

            CreateMap<T, T>()
                .ForAllOtherMembers(o => o.Condition((s, d, value) => value != null));
        }
    }
```

### Expected behavior

I expect that the dictionary in the destination object remains the same. I expect that it is not mapped to an empty dictionary.

### Actual behavior

The dictionary in the destination object is mapped into an empty dictionary.

### Steps to reproduce

```csharp
        [Fact]
        public void TestEntityPatch_NullCollection_DoesNotPatchCollection()
        {
           //Just a helper context to create the mapper for testing purposes.
            var context = PatcherProfileContext.Create();

            var originalEntity = new TestEntity
            {
                Dictionary = new Dictionary<string, object> { { "key", "value" } }
            };

            var patchEntity = new TestEntity
            {
                Dictionary = null
            };

            context.Mapper.Map(patchEntity, originalEntity);

            originalEntity.Dictionary.ShouldHaveSingleItem();
        }

```

I have also create a stackoverflow post here: https://stackoverflow.com/questions/59685356/automapper-and-null-dictionaries

Any help is appreciated. Thank you!

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by alec-lieberman-ef** [comment]
@lbargaoanu Why does it behave differently for Lists and Dictionaries? When I have the same test for mapping a null list, if I allow null collections, the destination list is not empty, it remains null as I would expect.

**Comment by lbargaoanu** [comment]
The execution plan shows the difference. But I wouldn't expect any.

**Comment by alec-lieberman-ef** [comment]
@lbargaoanu Right, I can see that for a list it checks if the source value is null and immediately returns the null value, but for a dictionary it doesn't return null. It checks to see if the destination is null or readonly and if not, it clears the collection. Since you don't expect this behavior, wouldn't this be a bug then? We'd expect it to behave like the list.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. You have to show the difference, of course.

**Comment by alec-lieberman-ef** [comment]
@lbargaoanu Here is a [gist](https://gist.github.com/alec-lieberman-ef/e3261185c3d5f0600e9f33f3c05d6f81) highlighting the issue. You can see the destination list remains intact with one element while the dictionary is cleared out.

**Comment by lbargaoanu** [comment]
The destination "list" is not a `List`, hence it cannot be cleared :)

**Comment by alec-lieberman-ef** [comment]
Ah, I suppose it was by luck then that I typed the list as an IEnumerable and it worked. I see what you mean now. Thank you, I will look into Automapper collections and how to configure the map so I can achieve what I actually want.

**Comment by alec-lieberman-ef** [comment]
I found this old stackoverflow that is pretty much what I want to do. Looks like you were part of this discussion also lol. https://stackoverflow.com/questions/47834970/automapper-does-not-map-properly-null-list-member-when-the-condition-null-is

**Comment by lbargaoanu** [comment]
:) Well, there are some corner cases that come up all of the time. Perhaps what made it more difficult for you was that you thought dictionaries are special. They are not, they are treated as most other collections.
