### ISSUE TITLE
Exception when mapping from List to IReadOnlyDictionary

### ISSUE THREAD

**Issue by demensh** [AutoMapper/AutoMapper#3300]
### Source/destination types

```csharp
public class Source
{
    public List<int> Field;
}
public class Target
{
    public IReadOnlyDictionary<int, int> Field;

}
```

### Mapping configuration

```csharp
new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Target>();
});
```

### Expected behavior

Exception with a readable message that a mapping can't build between the types and an explanation of the issue

### Actual behavior

System.IndexOutOfRangeException is thrown

### Steps to reproduce

No additional steps

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by demensh** [comment]
@lbargaoanu may it be a fix for 8.* version? I would like to look at the bug and fix this to get rid of a derived issue I've faced in the project code, but fixing it for 9.* would be worthless as that version has no support for `CreateMissingTypeMaps` feature we are using

**Comment by lbargaoanu** [comment]
You can do that in your own fork.

**Comment by mrzammit** [comment]
I'd like to take a stab at this. 

I've determined that when the source is a List and the target is an IReadOnlyDictionary it is being mapped by the ReadOnlyDictionaryMapper and the exception is thrown. If I change the target to an IDictionary it is using the EnumerableToDictionaryMapper, and the mapping is created, but an AutoMapper.AutoMapperMappingException is thrown during mapping (Missing type map configuration or unsupported mapping). 

Is that the desired handling in the case of an IDictionary, and is that how we'd like to handle the IReadOnlyDictionary?

**Comment by lbargaoanu** [comment]
The source could be `IDictionary` or `IReadOnlyDictionary`. That applies to both mappers I guess.

**Comment by mrzammit** [comment]
I'm not going to be able to fix this at the moment. Thanks.
