### ISSUE TITLE
Different behaviour when mapping collection and single object

### ISSUE THREAD

**Issue by NQuirmbach** [AutoMapper/AutoMapper#3302]
Hello,

when mapping a collection of objects and mapping the object manually the behaviour is different and it overwrites ignored properties

Testproject can be found here:

https://github.com/NQuirmbach/AutoMapperCollectionTest

### Version: 9.0.0

**Comment by lbargaoanu** [comment]
When mapping to an existing collection, the destination collection is cleared first. If this is not what you want, take a look at AutoMapper.Collection.
