### ISSUE TITLE
automapper in netcore

### ISSUE THREAD

**Issue by jiwenbu** [AutoMapper/AutoMapper#3303]
public class A{
 public GUID ID{get;set;}
}
public class B{
 public GUID ID{get;set;}
 public String a_id{get;set;}
}

CreateMap<A, B>();

result:
B.ID equal A.ID
B.a_id equal A.ID

why?
how to solve?
B.a_id should be null

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Flattening.html
