### ISSUE TITLE
Nullable source property values are provided as default when using condition?

### ISSUE THREAD

**Issue by StefH** [AutoMapper/AutoMapper#3304]
Linked to https://github.com/AutoMapper/AutoMapper/issues/3109

### Source/destination types

```csharp
public class S
{
	public int? X { get; set; }
}

public class D
{
	public int X { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
	cfg.CreateMap<S, D>()
		.ForAllMembers(opt =>
		{
			opt.Condition((src, dest, srcVal, dstVal, x) =>
			{
				return srcVal != null;
			});
		});
});

config.AssertConfigurationIsValid();

var mapper = new Mapper(config);
```

### Expected behavior

The nullable int on the S-class is not mapped

### Actual behavior

The D-class has X set to 0 ?

### Steps to reproduce

```csharp
var s = new S();
var d = new D { X = 42 };
	
mapper.Map(s,d);
// d has X set to 0 ?
```

I noticed that the `srcVal` is 0 instead of null?
![image](https://user-images.githubusercontent.com/249938/72750828-2f344080-3bbe-11ea-96b3-0ef2e3d68e27.png)

**Comment by lbargaoanu** [comment]
Yes, you'll have to workaround it. This has been discussed many times before, here and on SO.
