### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by haseeb200** [AutoMapper/AutoMapper#3308]
I have recently upgraded to **Automapper from 4.0 to 9.0.** and **I am using .Net framework 4.8**

> But I am having performance issues. CPU is spiking to 100% and then hang the system. 

I am unable to understand how to resolve this issue with Automapper 9.0

> After upgrading to 9.0. I have created a mapping profile and using Autofac for DI. Here is the sample of my code.

**First I have created  a Mapper Config which contains all the mapping profiles**

```
 public class MapperConfig
    {
        public static MapperConfiguration Configure()
        {
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new AffiliateProfile());
                cfg.AddProfile(new BlogCategoryProfile());
                cfg.AddProfile(new BlogPostProfile());
                cfg.AddProfile(new CertificatetProfile());
                cfg.AddProfile(new PricingScheduleProfile());
                cfg.AddProfile(new ProductProfile());
                cfg.AddProfile(new TransactionProfile());
            });
            return configuration;
        }
    } 
```
**One of the Mapping profile looks like this**

```
 class TransactionProfile : Profile
    {
        public TransactionProfile()
        {
            CreateMap<Transaction, TransactionLog>()
                .ForMember(dest => dest.OrderDetail, opt => opt.MapFrom(src => src.OrderDetailJson)); ;
            CreateMap<TransactionLog, Transaction>()
                 .ForMember(dest => dest.OrderDetailJson, opt => opt.MapFrom(src => src.OrderDetail))
                 .ForMember(dest => dest.OrderDetail, opt => opt.Ignore());
        }
    }
```

**After creating all of the Mapping Profiles I register the Mapper Config using Autofac along with other services ** 

 ```
public class AutofacConfig
    {
        public static void RegisterComponents()
        {
            var builder = new ContainerBuilder();
            //registering automapper
            builder.Register(ctx => MapperConfig.Configure());
            builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper())
                .As<IMapper>();
            //create container and set dependecy resolver
            var container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
        }
    }
```

After all those configurations when I run the application and do the stress testing My CPU spikes and hangs, But when I was using Automapper 4.0 my application easily handles stress testing without spiking the CPU.

Any Idea how to resolve CPU spiking while using Automapper 9.0? I even use MyGet build of Automapper but still no luck

**Comment by lbargaoanu** [comment]
Profile it. Or narrow it down by hand. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. Of course the repro should be minimal and depend _only_ on AutoMapper.

**Comment by lbargaoanu** [comment]
See also [the docs](http://docs.automapper.org/en/latest/Dependency-injection.html#autofac).

**Comment by haseeb200** [comment]
OK. I am creating a simple repo and will post here

**Comment by haseeb200** [comment]
I have found a solution.  As I am using Autofac for DI. SO when I Resolve the MapperConfiguration I was doing this
```
builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper())
               .As<IMapper>();
```

Instead, I need to use the same line but with **InstancePerLifeTimeScope**

```
 builder.Register(ctx => ctx.Resolve<MapperConfiguration>().CreateMapper())
                .As<IMapper>().InstancePerLifetimeScope();
```

> Although I have understood somehow. But if you can explain the difference in both in both line, please

**Comment by haseeb200** [comment]
Also, I need to understand how to configure Automapper with DI properly? I mean which service has which Lifetime scope? For example

**Will MapperConfiguration always has InstancePerLifeTimeScope?
What should be the scope of IMapper always?**

**Comment by lbargaoanu** [comment]
I've already posted a link to the docs. Use an existing implementation. The `MapperConfiguration` must be singleton. The mapper can be whatever.
