### ISSUE TITLE
TypeConverter using a 2nd TypeConverter to map an enum fails under unit tests

### ISSUE THREAD

**Issue by Rans4ckeR** [AutoMapper/AutoMapper#3312]
I had to disable many unit tests after upgrading from 8.0.0 to 8.1.0 and the issue is still present in 9.0.0.
When a TypeConverter internally calls Map() to convert an enum, and this mapping is using a 2nd TypeConverter, the following exception is observed when running from an MSTest unit test project. In a non-unit test project this issue is not observed.

System.NullReferenceException: 'Object reference not set to an instance of an object.'
at AutoMapper.Mapper.Map(Object source, Object destination, Type sourceType, Type destinationType, ResolutionContext context, IMemberMap memberMap)
at AutoMapper.ResolutionContext.AutoMapper.IMapper.Map[TDestination](Object source)
at UnitTestProject1.EntityTypeConverter.Convert(TestEntity source, String destination, ResolutionContext context) in C:\Users\c00270\source\repos\UnitTestProject1\EntityTypeConverter.cs:line 11
at UnitTestProject1.UnitTest1.TestMethod1() in C:\Users\c00270\source\repos\UnitTestProject1\UnitTest1.cs:line 14

An example unit test project is attached.
[UnitTestProject1.zip](https://github.com/AutoMapper/AutoMapper/files/4128268/UnitTestProject1.zip)

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. Of course the repro must depend _only_ on AM.

**Comment by Rans4ckeR** [comment]
The gist would succeed as I only notice this when running the code from an MSTest project. If I downgrade to 8.0.0 or earlier everything works however.

**Comment by lbargaoanu** [comment]
Well, that doesn't mean much. Code changes. You can either stick to 8.0.0 or update your code to the new version. The general idea is that you don't need to mock AM in tests. Just use the real thing. If you implemented AM extension points and your own code needs mocking, of course you have to mock that.

**Comment by Rans4ckeR** [comment]
Could you have a look at the attached project of the first post? There is no mocking or anything and the code did not need any changes to work on 9.0.0.

**Comment by lbargaoanu** [comment]
You're mocking AM's context.
