### ISSUE TITLE
Mapping from interface to concrete class not working

### ISSUE THREAD

**Issue by viswateja499** [AutoMapper/AutoMapper#3313]
Hi,

Below are my sample code

public void Interface IPerson
{
 DateTimeOffset DOB { get; set ;}
}

public class Person : IPerson
{
public string Name { get; set; }

public DateTimeOffset DOB { get; set; }
}

Public class Man
{
public string Name { get; set; }

public DateTime DOB { get; set; }
}

Above are the example classes in my project. Now, I am trying to Map between IPerson to Man. Unfortunately DOB is not getting mapped.
Please check below mapping configuration.

public class PersonProfile : Profile
    {
        public PersonProfile()
        {
            this.CreateMap<IPerson, Man>()
                .ForMember(dest => dest.DOB, opt => opt.MapFrom(src => src.DOB.UtcDateTime));
        }
    }

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
