### ISSUE TITLE
Inconsistent Mappings when using ProjectTo

### ISSUE THREAD

**Issue by Cubelaster** [AutoMapper/AutoMapper#3315]
### Source/destination types

```csharp
public class Offer
    {
        public int Id { get; set; }
        public List<OfferItem> OfferItems { get; set; }
    }

public class OfferItem
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        public Offer Offer { get; set; }
        public List<OfferItem> OfferItems { get; set; }
        public int? OfferItemId { get; set; }
        public OfferItem OfferItem { get; set; }
    }


public class OfferViewModel
    {
        public int Id { get; set; }

        public decimal Price { get; set; }

        public int? OfferId { get; set; }

        public List<OfferItemViewModel> OfferItems { get; set; }
}

public class OfferItemViewModel
    {
        public int Id { get; set; }
        public int OfferId { get; set; }

        public int? OfferItemId { get; set; }

        public List<OfferItemViewModel> OfferItems { get; set; } = new List<OfferItemViewModel>();
}
```
** Not original classes, but this is the gist of it
Basically, each Offer has a list of OfferItems and each OfferItem can have multiple OfferItems attached to it (but also to Offer at the same time). 
So, if an OfferItem has OfferItemId, it definetily has OfferId as well. 

Realistic case: 
```json
Offer: {
    "Id": 1
};

OfferItem: {
    "Id": 1,
    "OfferId": 1
}

OfferItem: {
    "Id": 2,
    "OfferId": 1,
    "OfferItemId": 1
}
```

### Mapping configuration

```csharp
CreateMap<Offer, OfferViewModel>()
                .ForMember(dest => dest.OfferItems, opt => opt.MapFrom(src => src.OfferItems.Where(oi => oi.Active)));

CreateMap<OfferItem, OfferItemViewModel>()
                .ForMember(dest => dest.OfferItems, opt => opt.MapFrom(src => src.OfferItems.Where(oi => oi.Active)));
```

### Expected behavior

My expectation was that each map happens on its own.
For instance, I would get Offer, containing it's OfferItems, but also OfferItems would contain their own OfferItems.

```json
Offer: {
    "OfferItems": [
         { 
            "Id": 1, 
            "OfferItems": [ 
                { 
                    "Id": 2 
                }
             ] 
         },
         { 
            "Id": 2, 
            "OfferItems": [ ] 
         }
    ]
}
```

### Actual behavior

But when I was using 
```csharp
var offer = mapper.ProjectTo<OfferViewModel>(query).Single();
```
I got every OfferItem in first list, but none in related list. 
```json
Offer: {
    "OfferItems": [
         { 
            "Id": 1, 
            "OfferItems": [ ] 
         },
         { 
            "Id": 2, 
            "OfferItems": [ ] 
         }
    ]
}
```json

### Steps to reproduce

```csharp
var offer = mapper.ProjectTo<OfferViewModel>(query).Single();
```

If I use the 
```csharp
var offerItems = mapper.ProjectTo<OfferItemViewModel>(itemsQuery).ToList();
```
then everything is correctly mapped. 

Am I doing something wrong, or is it a bug?

**Comment by Cubelaster** [comment]
Aha, so, I have figured out that, if I leave out the 
```csharp
CreateMap<Offer, OfferViewModel>()
                **.ForMember(dest => dest.OfferItems, opt => opt.MapFrom(src => src.OfferItems.Where(oi => oi.Active)));**
```
.ForMember part and let it handle itself, it maps All the correct members, but it seems as if using .ForMember makes AutoMapper stop resolving the tree?

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). 
I think this is better suited for StackOverflow.

**Comment by Cubelaster** [comment]
I would really like to have this answered. 
Also, I believe this is either a bug, or really poorly documented. 
I've run into another issue, very similar.
So, I'm using Lists of Parent => Child relations and it looks kinda like this: 
Parent has 3 different lists of children, and each of the children is basically a same Base Class that contains the same 3 lists. Lets say it's circular, but in reality it isn't. 
And first level works fine, everything is mapped correctly. 
The second level is there.
But the third level, which should be mapped in exactly the same way has no children. 
To me, it appears as if the parents are being resolved before the children. 
I'm using ProjectTo and am expecting it to work out of the box. 

Is this problem possible to fix using SetMappingOrder or something else?
