### ISSUE TITLE
Why is ForAllOtherMembers void?

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#3316]
### Actual behavior

`ForAllMembers` and `ForAllOtherMembers` are really helpful things, but they do not return an `IMappingExpression` like all the other methods do. Which makes it impossible to call `ReverseMap` after them. Is this behaviour intentional or an oversight?

If intentional - can I call `ReverseMap` on the expression passed on to `ForAllOtherMembers`?

**Comment by lbargaoanu** [comment]
It's intentional. They don't compose with most other configuration. You cannot call `ForMember` again. You can call `ReverseMap` as you've said. Or just create that map yourself, without `ReverseMap`.
