### ISSUE TITLE
Mapping IEnumerables with UseDestinationValue Not Working

### ISSUE THREAD

**Issue by Gogims** [AutoMapper/AutoMapper#3320]
### Source/destination types

```csharp
public class Source
{
    public int Id;
}
public class Target
{
    public int Id;
    public string UnchangedField;
}
```

### Mapping configuration

```csharp
new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Target>()
        .ForMember(dest => dest.UnchangedField, opt => opt.UseDestinationValue());
});
```

### Expected behavior
Mapping two IEnumerables<T> with one property set to "UseDestinationValue" should keep the property as it originally was

### Actual behavior
Mapping two IEnumerables<T> with one property set to "UseDestinationValue" sets the property to the default value for the type (string = null, int = 0, etc.)

### Steps to reproduce
- Add "UseDestinationValue" to one property in the mapping profile
- Map two IEnumerables

```csharp
using System.Linq;

targets = targets.Select(t =>new Target
{
    UnchangedField = "Test"
});
var mappedTarget = mapper.Map(sources, targets);
mappedTarget.All(t => t.UnchangedField == "Test") // false.
targets.All(t => t.UnchangedField == "Test") // false.
```
**NOTE: This works if I don't map them as IEnumerable.** 
```csharp
using System.Linq;

targets = targets.Select(t =>new Target
{
    UnchangedField = "Test"
});
var mappedTarget = mapper.Map(sources.First(), targets.First());
//mappedTarget.UnchangedField  == "Test"
```

**Comment by lbargaoanu** [comment]
When mapping to an existing collection, the destination collection is cleared first. If this is not what you want, take a look at AutoMapper.Collection.
