### ISSUE TITLE
AutoMapper.AutoMapperMappingException: System.InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by sumit2016** [AutoMapper/AutoMapper#3321]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```
Mapper.CreateMap<Product, ProductBO>().
                    ForMember(dest => dest.LotAttribute, opt => opt.MapFrom(src => Mapper.DynamicMap<ProductAttributeBO>(src.product_attribute)))
                       .AfterMap(

                    (src, target) =>
                    { ..

### Version: x.y.z
 Automapper version 4.1.1.0

### Expected behavior

No error was present in on premise version with same concurrent user base accessing the application (EF 6 + Automapper 4.1.1.0)

### Actual behavior
This application throws error intermittently specially when more number of records are fetched and / or more number of concurrent users are operating on this application.

Error details:

System.Data.Entity.DynamicProxies.Product_8AFB94389ADEA7181732D39AAE7B3AAB16F6979897F600C1B5E2A8F50A0AFDFDError Token:637170760073663598
AutoMapper.AutoMapperMappingException: 

Mapping types:
Product -> ProductBO
Org.app.Entity.DataModel.Inventory.Product -> Org.app.BusinessObjects.Models.ProductBO

Destination path:
List`1[35]

Source value:
System.Data.Entity.DynamicProxies.Product_8AFB94389ADEA7181732D39AAE7B3AAB16F6979897F600C1B5E2A8F50A0AFDFD ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at AutoMapper.TypeMap.<get_AfterMap>b__40_0(Object src, Object dest)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   --- End of inner exception stack trace ---

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```The search API calls

products.Result = Mapper.Map<List<ProductBO>>(ProductList.ToList())
It has a custom automapper configuration class

  public static class AutoMapperConfiguration
    {

        public static void Configure()

        {
                Mapper.CreateMap<Product, ProductBO>()
..
This is called from Startup.cs AutoMapperConfiguration.Configure();

**Comment by lbargaoanu** [comment]
I've already answered on StackOverflow.

**Comment by sumit2016** [comment]
@lbargaoanu Can you please share the specific link to your answer in StackOverFlow?
