### ISSUE TITLE
AutoMapper defaults to calling ToString() when converting DateTime

### ISSUE THREAD

**Issue by vivainio** [AutoMapper/AutoMapper#3322]
### Source/destination types

```csharp
// Put your source/destination types here
DateTime? source;
string destination = mapper.Map<string>(source);

```

### Mapping configuration

```csharp

// No mapping

```

### Version: x.y.z

6.1.1

### Expected behavior

Automapper should emit a date in a round-trippable format like ISO-8601 Zulu time

### Actual behavior

Automapper calls date.ToString(), which emits a date using current locale. This string is unusable outside UI code.

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
DateTime? source = DateTime.Now;
string destination = mapper.Map<string>(source);

```

**Comment by vivainio** [comment]
You can avoid this by creating an explicit mapping like:

```csharp
cfg.CreateMap<DateTime?, string>().ConvertUsing<DateTimeToPlainStringConverter>();
```

... but current behavior is potentially dangerous

**Comment by lbargaoanu** [comment]
I see your point, but I'm not convinced. There's no contract here. cc @jbogard

**Comment by jbogard** [comment]
Let's open a discussion on this one - I don't want to revisit every `ToString` but it's a warning that R# pops up to supply a culture.

This is potentially a breaking change to alter the default behavior, though.

I don't know how one could decide the "correct" one, even round-trip versus one of the other standards is debatable

**Comment by lbargaoanu** [comment]
Yes, and it dead easy to change the default. You can even replace the default `StringMapper` with a custom version. The default seems reasonable to me. After all it's the default in the BCL too.

**Comment by vivainio** [comment]
"Obviously" correct format is the one used by JSON, I.e. ToString("o"). Likewise, you would expect AutoMapper to use invariant culture in other places where formatting happens.

I have no idea how format changes across versions can be done in AutoMapper though. Maybe some "contrib" package that opts in to most sensible defaults?

**Comment by lbargaoanu** [comment]
Maybe for serialization, but certainly not for UI. What about all the people relying on this? It's not exactly a common complaint. After all the main AM scenario is DB entity to UI.

**Comment by vivainio** [comment]
The behavior certainly seems more accidental than intentional.

We use AutoMapper to map between DB entities to DTOs. It's not up to DTOs to contain the "final rendering", this should happen based on end user locale (browser locale?), not the locale the server happens to be running in.

It may be that users rarely use string as target type, hence people haven't complained about this earlier. I stumbled on this while serializing between db entities and gRPC, taking the first stab by converting both dates and decimals to strings.

**Comment by lbargaoanu** [comment]
It makes sense for the end user culture to be set on the thread serving the request. This seems a more reasonable default than what you're proposing. The breaking change makes it even clearer to me. But I guess AM cannot know what the right conversion is. Hence the extensibility.

**Comment by jbogard** [comment]
To me the only other "reasonable" default is `ToString(CultureInfo.InvariantCulture)`.

**Comment by lbargaoanu** [comment]
I disagree :) I think the UI people should have priority. I would guess there are more of them too. The BCL made the same choice by having the no params overload use the current culture. Also, you can set the current culture to the invariant culture, but once you hard-code it in AM, they'll need type converters.

**Comment by vivainio** [comment]
For dates, InvariantCulture gives

"05/21/2014 22:09:28" 

i.e. the US formatting which, among other things, is not sortable and doesn't preserve time zone information.

When BCL made the choices it was a different time (.net was made for desktop applications), and those choices are probably not compatible with what people do nowadays.

Maybe AutoMapper could bundle a "formatter pack" that would use invariant culture everywhere? This would make AutoMapper safer/eavier for server application developers, and you could opt into it by running a command.

**Comment by lbargaoanu** [comment]
For web UI-s it's the same and .Net Core made the same choice.

**Comment by vivainio** [comment]
Web UI's often consume json and the format of DateTime in both system.text.json and newtonsoft (i.e. both old aspnet and aspnetcore) is ToString("o"), i.e. conforming to ISO 8601 standard.

Netcore couldn't break compatibility there for obvious reasons.

**Comment by lbargaoanu** [comment]
It's not about json here, it's about .net types, any serializer can do its own stuff. And yes, backward compatibility :)

**Comment by vivainio** [comment]
Serializer cannot behave sensibly if data is not in normalized format. Culture sensitive rendering  of data is essentially corrupt and only useful for showing to the end user. IMHO of course.

That being said, do you still see value for culture insensitive mappers as an add-on to default behavior? What would that API look like?

**Comment by lbargaoanu** [comment]
You should let the serializer convert objects to string and use AM to map .net types. I think ad-hoc solutions are best here. AM is not a serialization library and it's general enough that it couldn't possibly cover all cases. @jbogard might see it differently :)
