### ISSUE TITLE
ProjectTo and parents of the same type - any way?

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#3323]
I have a case where an objec (let's call it Event) has a Property Parent that points to another Event. THis is NOT a recursion of "indetermined depth" - any object either has a child or CAN have parent, period. The hierarchy stops at this point (i.e. in one level). This is simple to map in SQL with a join.

I can not get ProjectTo to create this join.

if I subclass Event (into EventParent) and turn the ParentProperty in Event from Event to EventParent
(
 i.e.
Event -> (property Parent) -> Event
turns into
Event -> (property Parent) -> EventParent
)
then it works like a charm.

is there any way without exposing EventParent? Right now, because I use ProjectTo to generate odata DTO, I am / must expose EventParent in the odata object model, which is something I would prefer to avoid.

In the documentation I only find:
http://docs.automapper.org/en/stable/Queryable-Extensions.html

Additionally, recursive or self-referencing destination types are not supported as LINQ providers do not support this. Typically hierarchical relational data models require common table expressions (CTEs) to correctly resolve a recursive join.

As I said - this is not the case here. A simple join would work well enough and IS supported. Even in a classical hierarchy, given 
* A depth limitation
* Support for simple Joins
I do not see why CTE would be required. Yes, they may (to avoid complex SQL) if you expand other properties (which would have to be expanded on every level of the hierarchy).

Please allow recursiveness - I see no reason (the result is valid LINQ and basically "some sources have problems" can be said for a LOT of LINQ statements.

**Comment by Cubelaster** [comment]
I have a similar problem. 
For me, ProjectTo stops fetching after first level, IF THE PARENT AND THE CHILD are the SAME CLASS. 
However, if I just switch the class, everything works. This seems to me like a n*(n+1) guard attempt that bugged out. 
So, if you just make a VM that has 2 different classes everything should work with ProjectTo way.

**Comment by jbogard** [comment]
Yep, that's it. If you want recursive joins, use common table expressions and SQL.

**Comment by Cubelaster** [comment]
> Yep, that's it. If you want recursive joins, use common table expressions and SQL.

Could we maybe request a OptIn Recursive Joins feature in AutoMapper?
Like, a way to signal AutoMapper: Hey man, I know it's not really OK, but I know what I'm doing and I really want to do it?
