### ISSUE TITLE
UWP Native Compile - This object cannot be invoked because it was metadata-enabled for browsing only

### ISSUE THREAD

**Issue by premiaware** [AutoMapper/AutoMapper#3324]
With UWP Native compile, my sample is attached and have incredibile results:

1.	Unzip attached sample
2.	Rebuild all with VS 2019 in release mode native compile
3.	All Working Well!! 
4.	Now
5.	Stop debug
6.	Enter in the Manage Nutget package for TestAutomapper Project
7.	Remove “MyToolkit.Extended” package from project (this package is not used in the solution but it is crucial to make App work)
8.	Now REBUILD ALL 
9.	Start the App
10.	Exception is throw:

This object cannot be invoked because it was metadata-enabled for browsing only: 'System.Func<ClassLibrary3.AnagraficaBridge,ClassLibrary3.AnagraficheSinteticheBridge,System.Collections.Generic.List<ClassLibrary3.TelefonoEmailBridge>,AutoMapper.ResolutionContext,System.Collections.Generic.List<ClassLibrary3.TelefonoEmailBridge>>.Invoke(ClassLibrary3.AnagraficaBridge,ClassLibrary3.AnagraficheSinteticheBridge,System.Collections.Generic.List<ClassLibrary3.TelefonoEmailBridge>,AutoMapper.ResolutionContext)' For more information, please visit  http://go.microsoft.com/fwlink/?LinkID=616867'

I have try to modify my default.rd.xml for without positive results.
[UwpDotNativeIssues-master.zip](https://github.com/AutoMapper/AutoMapper/files/4224730/UwpDotNativeIssues-master.zip)

How can i fix this problem ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
