### ISSUE TITLE
Protobuf/gRPC RepeatedField support

### ISSUE THREAD

**Issue by vivainio** [AutoMapper/AutoMapper#3325]
This was previously raised in now-closed ticket https://github.com/AutoMapper/AutoMapper/issues/3157

I am using Google.Protobuf (and gRPC, but that is not important).

Protobuf RepeatedField properties are implemented as readonly fields with getter only.

Current code generated for populating RepeatedField's doesn't work, as you need to "Add" to RepeatedField collection instead of assigning a new value to it. This is a series of tedious foreach loops in AfterMap (one for each property).

There should be a way to specify to automapper that you need to "Add" to pre-instantiated collection instead of instantiating a new one. This would not require physical dependency to Google.Protobuf

**Comment by vivainio** [comment]
Possible api could be:

```csharp
// now RepeatedField is only ever Add():ed to, never assigned
cfg.TreatCollectionAsReadOnly<RepeatedField>()
```

**Comment by vivainio** [comment]
This could be relevant: https://github.com/AutoMapper/AutoMapper/pull/3275

**Comment by jbogard** [comment]
I thought we supported readonly collections. What does your destination type look like? Gist?

**Comment by vivainio** [comment]
Destination type is the one generated from proto files: https://gist.github.com/vivainio/e1129348d38f061856b28b35d4fd830d

You can build it yourself by doing "dotnet new grpc", then editing greet.proto to convert property to repeated:

```protobuf
message HelloRequest {
  repeated string name = 1;
}
```

After dotnet build, the generated file will be in obj\Debug\netcoreapp3.1\Greet.cs

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by vivainio** [comment]
This was a feature suggestion, not a question

**Comment by nsalikhov** [comment]
Because in generated c# classes from proto all collection are `RepeatedField` properties with `get` only backing fields which always `readonly` and initialized on construction, found this workaround, works for me:
```
            var config = new MapperConfiguration(
                cfg =>
                {
                    cfg.ForAllPropertyMaps(
                        map => map.DestinationType.IsGenericType && map.DestinationType.GetGenericTypeDefinition() == typeof(RepeatedField<>),
                        (map, options) => options.UseDestinationValue());
                });
```
@vivainio maybe it helps

**Comment by cinaradem** [comment]
@nsalikhov  thanks, work it. :)
