### ISSUE TITLE
ExecutionEngineException when projecting value type to object

### ISSUE THREAD

**Issue by Prologh** [AutoMapper/AutoMapper#3328]
### Source/destination types

```cs
class Model
{
    public int Id { get; set; }
}

class Dto
{
    public object Id { get; set; }
}
```

### Mapping configuration

```cs
var configuration = new MapperConfiguration(options =>
{
    options.CreateMap<Model, Dto>();
});
```

### Expected behavior

Filling `Id` property of `Dto` with values from `Id` property of `Model`.

### Actual behavior

Mapping seemingly succeeds, but any calls made on properties of mapped objects result in `ExecutionEngineException` that will put whole application in a break mode, closing it immediately. Inspecting mapping results in VS 2019 debbugger shows literally nothing when mapping from Model class with Id property of `int` type:

![](https://i.imgur.com/3rvl4M8.png)

For `float` or `double` source types, the exception does not occur, but mapping results have little sense to me. Weird recursive structure of arrays and objects appears:

![](https://i.imgur.com/aGl9okX.png)

### Steps to reproduce

```cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AutoMapperTests
{
    class Program
    {
        static void Main(string[] args)
        {
            var source = new[]
            {
                new Model
                {
                    Id = 1,
                },
                new Model
                {
                    Id = 2,
                },
            }.AsQueryable();
            var mapper = new MapperConfiguration(options =>
            {
                options.CreateMap<Model, Dto>();
                //.ConvertUsing(level => new Dto
                //{
                //    Value = level.Id,
                //});
            }).CreateMapper();

            // Mapping via instance works, as well .Select()
            //var result = mapper.Map<List<Dto>>(source);
            var result = source
                //.Select(model => new Dto
                //{
                //    Id = model.Id,
                //})
                .ProjectTo<Dto>(mapper.ConfigurationProvider)
                .ToList();

            // Exception below:
            result.ForEach(dto => Console.WriteLine(dto.Id));
        }
    }

    class Model
    {
        public int Id { get; set; }
    }

    class Dto
    {
        public object Id { get; set; }
    }
}

```

### Notes
 - problem seems to concern only queryable extensions as mapping via instance works fine. Executing `var result = mapper.Map<List<Dto>>(source);` gives me valid results for every option I try;
 - mapping from `object` to `object` works fine;
 - mapping from non-primitive data types (e.g. string) to object doesn't show the issue;
 - mapping from 0 gives `null` in destination property when mapping from int;
 - using `ConvertUsing()` for manual mapping to destination object property gives valid mapping results;
 - changing the type of destination collection doesn't affect the problem. Array, dictionary, `IEnumerable<T>`, all show the same issue.

**Comment by lbargaoanu** [comment]
Weird :) But it works for me with EF6 (the main use case for `ProjectTo`), so not exactly interesting. A PR is welcome.

**Comment by Prologh** [comment]
I encountered such problem while using projections with EF Core 3.1.1.

**Comment by lbargaoanu** [comment]
Workaround:
    
    cfg.CreateMap<Model, Dto>().ForMember(d=>d.Id, o=>o.MapFrom(s=>(object)s.Id));

**Comment by lbargaoanu** [comment]
I'll close this as I don't see how we can solve it and not break EF6. `ProjectTo` is extensible and you can always solve this generically outside AM.
