### ISSUE TITLE
Combining an attribute map with an explicit map

### ISSUE THREAD

**Issue by mrahhal** [AutoMapper/AutoMapper#3330]
I'm using attribute mapping in all of my app by default. But then, sometimes, I would add a property on my dto that will need some complex mapping, which I'll need fluent mapping for. I thought that `[AutoMap]` and fluent mapping supplement each other automatically, but then it seems whenever I use `[AutoMap]`, fluent maps aren't being read at all.

### Source/destination types

```csharp
// Source
public class User
{
	public string Id { get; set; }
}

// Destination
[AutoMap(typeof(User))]
public class UserDto
{
	public string Id { get; set; }

	[SourceMember(nameof(Id))]
	public string Id2 { get; set; }

	public string Some { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<User, UserDto>()
	.ForMember(x => x.Some, c => c.MapFrom(x => "data"));
```

### Expected behavior

```
{ "Id":  "42", "Id2": "42", "Some": "data" }
```

### Actual behavior

```
{ "Id":  "42", "Id2": "42", "Some": null }
```

With the `[AutoMap]` attribute removed, it becomes:

```
{ "Id":  "42", "Id2": null, "Some": "data" }
```

### Steps to reproduce

```csharp
var users = await AppDbContext.Users
	.ProjectTo<UserDto>(Mapper.ConfigurationProvider)
	.ToListAsync();

return Ok(users);
```

Same thing happens with `Mapper.Map`.

When I remove `[AutoMap]`, fluent map starts working correctly and provides the expected `"Some"` field. Of course, I do need `[AutoMap]` too since I use attribute mapping by default for all my maps. It'll be beyond inconenient if I'll have to convert an `AutoMap` to an explicit map the moment I add a property that needs complex config. I expect that I can, in some way, use `AutoMap` by default, and then simply add the fluent configuration to configure a complex property, and that would be the same as adding a -fictional- complex configuration attribute above that property.

**Comment by lbargaoanu** [comment]
That was not the original intent. And I'm not sure we want that. It seems misleading to me.

**Comment by jbogard** [comment]
Correct, it is not the intent to allow combining attribute maps and fluent
maps. It’s too confusing.

**Comment by mrahhal** [comment]
In [this](https://docs.automapper.org/en/stable/Attribute-mapping.html) document about attribute mapping, there's the following:

> Attribute maps can **supplement** or replace fluent mapping configuration.

Then:

> If the attribute-based configuration is not available or will not work, you can **combine both attribute and profile-based maps** (though this may be confusing).

I now know that this means combining them in the project as a whole, and not for the same map, but this was misleading, at least to my team.

The new Attribute maps are great, but I thought covering what they lack in configuring complex props (because of C# attribute limitation) through using fluent maps would have been the best combination. I know I'm repeating myself, but it renders them useless the moment we have to configure even a single complex property in the hierarchy of some Dto.

**Comment by lbargaoanu** [comment]
About the docs, a PR is welcome.

**Comment by jbogard** [comment]
Yes, this is supposed to be for different maps, not individual maps.
