### ISSUE TITLE
Properties of type T[][] work with Mapper.Map but not Mapper.ProjectTo

### ISSUE THREAD

**Issue by NorfAlrin** [AutoMapper/AutoMapper#3331]
### Source/destination types
```csharp
public class Source
{
    public SrcValue[][] Value { get; set; }
}
public class SrcValue
{
    public int Value { get; set; }
}

public class Destination
{
    public DestValue[][] Value { get; set; }
}
public class DestValue
{
    public int Value { get; set; }
}
```

### Mapping configuration
```csharp
cfg.CreateMap<Source, Destination>();
cfg.CreateMap<SrcValue, DestValue>();
```

### Expected behavior

Mapper.Map and Mapper.ProjectTo should behave the same way when mapping a source type to a destination type.

### Actual behavior
Mapper.Map behaves as expected with the value property mapped correctly.

An Error is thrown when calling Mapper.ProjectTo
_"Missing map from SrcValue[] to DestValue[]. Create using CreateMap<SrcValue[], DestValue[]>"_
_"at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)"_

### Steps to reproduce

```csharp
// setup
var source = new Source{ Value = new[] { new[] { new SrcValue{Value = 2} } }};
var queryableSource = new[] {source}.AsQueryable();

// destination maps correctly
var destination = Mapper.Map<Destination>(source);

// Error is thrown
destination = Mapper.ProjectTo<Destination>(queryableSource).First();
```

**Comment by lbargaoanu** [comment]
For the most part `ProjectTo` only supports what EF6 supports, so that's expected.
