### ISSUE TITLE
AutoMapper not working as expected

### ISSUE THREAD

**Issue by fairking** [AutoMapper/AutoMapper#3332]
I am going crazy with the AutoMapper and cannnot understand what is going on. Could someone please look if there is any error? Thanks.

### Source/destination types
Se example bellow

### Mapping configuration
See example bellow

### Version
9.0

### Expected behavior
Must be "Ref 1: Name 1";

### Actual behavior
It is "Name 1";

### Steps to reproduce
```csharp
using AutoMapper;
using Xunit;

namespace MyProject.Tests
{
    public class Order
    {
        protected Order() { }
        public Order(string refNumber, string name)
        {
            RefNumber = refNumber;
            Name = name;
        }
        public string RefNumber { get; set; }
        public string Name { get; set; }
    }

    public class OrderLookupVm
    {
        public OrderLookupVm() { }
        public OrderLookupVm(string name)
        {
            Name = name;
        }
        public string Name { get; set; }
    }

    public class AutoMapperTests
    {
        [Fact]
        public void SimpleMappingTest()
        {
            var mapper = new MapperConfiguration(
                cfg => cfg.CreateMap<Order, OrderLookupVm>().ForMember(
                    dest => dest.Name, opt => opt.MapFrom(src => src.RefNumber + ": " + src.Name))
                )
                .CreateMapper();
            var result = mapper.Map<OrderLookupVm>(new Order("Ref 1", "Name 1"));
            Assert.Equal("Ref 1: Name 1", result.Name);
        }
    }
}
```
The code above fails: Assert.Equal() Failure, Expected: "Ref 1: Name 1", Actual:  "Name 1".

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Construction.html

**Comment by fairking** [comment]
Thanks guys, but I still could not understand how property mapping related to constructor mapping.
¯\_(ツ)_/¯

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by spydacarnage** [comment]
You need to use .ForCtorParam, not .ForMember (at least, that's what I use
all the time and it works)
