### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by TDK1964** [AutoMapper/AutoMapper#3335]
This is not an issue merely a question on usage.
Some of my colleagues have started doing this which I believe is the wrong thing to do, I would have thought it better to do this in the model or the handler (Mediatr)?
What are your thoughts?
```
   .ForMember(x => x.CreatedDate, opt => opt.MapFrom(x => DateTime.UtcNow))
   .ForMember(x => x.ModifiedDate, opt => opt.MapFrom(x => DateTime.UtcNow))
   .ForMember(x => x.ModifiedBy, opt => opt.MapFrom(x => x.CreatedBy))
   .ForMember(x => x.CreatedBy, opt => opt.MapFrom(x => x.CreatedBy))
```

**Comment by lbargaoanu** [comment]
The first two should be in the constructor, the third looks like mapping and the last should be deleted. https://jimmybogard.com/automapper-usage-guidelines/
