### ISSUE TITLE
ProjectTo initializes null objects for optional one-to-one relationships mapped with AllowNull()

### ISSUE THREAD

**Issue by Prologh** [AutoMapper/AutoMapper#3338]
### Source/destination types

```csharp
public class Car
{
    public int Id { get; set; }
    public string Model { get; set; }
}

public class Owner
{
    public int Id { get; set; }
    public Car Car { get; set; }
    public int? CarId { get; set; }
    public string Name { get; set; }
}

public class CarDto
{
    public int Id { get; set; }
    public string Model { get; set; }
}

public class OwnerDto
{
    public int Id { get; set; }
    public CarDto Car { get; set; }
    public int? CarId { get; set; }
    public string Name { get; set; }
}
```

### Mapping configuration

```csharp
new MapperConfiguration(settings =>
{
    settings.CreateMap<Owner, OwnerDto>()
        .ForMember(ownerDto => ownerDto.Car, options => options.AllowNull());
    settings.CreateMap<Car, CarDto>();
});
```

### Expected behavior

AutoMapper maps nested object only if it is not null. In my example owner's `Car` should be mapped only if it is not null. If it is null, persist the null.

### Actual behavior

AutoMapper initializes objects that are null in source. In my example it initializes owner's `Car` even when `Owner` has no `Car`, so it is null.

### Steps to reproduce

[GitHub Gist](https://gist.github.com/Prologh/f2e41ce891c6295883898a32a23f4dfc)

Inspect `result` variable, best before cleanup section.

### Notes

I'm using `AllowNull()` only because, I have integration tests based on EF Core with in memory database that doesn't work well with relationships and AutoMapper queryable extensions `ProjectTo()`. It throws exceptions like [that](https://github.com/dotnet/efcore/issues/19726). There are few open issues on this. As a temporary work-around I use `AllowNull()` which I saw amidst AutoMapper issues on GitHub as I recall correctly. If it weren't for that issue with in memory db, I wouldn't use `AllowNull()`. Still, I think that shouldn't result in such behavior.

 - problem occurs only when using `.AllowNull()`, not using it doesn't produce the issue
 - tested both on EF 6.4.0 and EF Core 3.1.2, same issue
 - using `NullSubstitute(null)` acts well as a temporary workaround
 - mapping via instance works as expected

**Comment by lbargaoanu** [comment]
EF Core should fix that. `AllowNull` is just a hack to remove a null check somewhere inside AM. It was not intended to do what you're saying. Other than `NullSubstitute`, `AllowNullDestinationValues` is a setting for that, but that's all. @jbogard will reopen the issue if he wants a PR in that direction.

**Comment by jbogard** [comment]
Yeah, `AllowNullDestinationValues` does exactly this, no?

**Comment by lbargaoanu** [comment]
Yes, but it's per profile.
