### ISSUE TITLE
Argument types do not match when mapping from ICollection to IReadOnlyList

### ISSUE THREAD

**Issue by Baune8D** [AutoMapper/AutoMapper#3340]
### Source/destination types

See exception repository

### Mapping configuration

See exception repository

### Version: x.y.z
AutoMapper 9.0.0
AutoMapper.Collection.EntityFrameworkCore 1.0.1
AutoMapper.Extensions.Microsoft.DependencyInjection 7.0.0

### Expected behavior

Mapping should work. If you change ```IReadOnlyList``` in ```TestProjectedEntity``` to ```List```, then mapping works.

### Actual behavior

Mapping using ```ProjectTo``` fails with exception ```ArgumentException: Argument types do not match```

### Steps to reproduce

https://github.com/Baune8D/AutoMapper_IReadOnlyList_ArgumentTypesDoNotMatch

Just run the project and error will trigger.

**Comment by lbargaoanu** [comment]
Our main use case is EF6 and EF6 doesn't support it. If you want to fix it for EF Core, a PR is welcome. This can also be done outside AM.

**Comment by Baune8D** [comment]
> Our main use case is EF6 and EF6 doesn't support it. If you want to fix it for EF Core, a PR is welcome. This can also be done outside AM.

I just find it strange that primitive values seems to work fine this way. If i do:
```csharp
.ForMember(dest => dest.TestChildEntityIds, opt => opt.MapFrom(src => src.TestChildEntities.Select(x => x.Id).ToList()))
```
It will map to IReadOnlyList just fine. So it seems to only be a problem for mapping objects.

Do you have any suggested workarounds? I really do not want to expose the collection as a List as i want it to remain immutable.

**Comment by lbargaoanu** [comment]
How would you do it without AM, in an EF linq query? Does that even work?

**Comment by Baune8D** [comment]
> How would you do it without AM, in an EF linq query? Does that even work?

```csharp
var working = _context.TestDbEntities
    .Select(e => new TestProjectedEntity
    {
        Id = e.Id,
        TestChildEntities = e.TestChildEntities
            .Select(c => new TestProjectedChildEntity
            {
                Id = c.Id
            })
            .ToList()
    });
```

Using the linked example repo as example, the above query works.

**Comment by lbargaoanu** [comment]
Well, that's what AM does too, so perhaps this didn't come up before simply because EF6 doesn't support it. I would guess it's an easy fix :)

**Comment by Baune8D** [comment]
> Well, that's what AM does too, so perhaps this didn't come up before simply because EF6 doesn't support it. I would guess it's an easy fix :)

I hope so :) I am rewriting some code and would really like to keep the collection read-only in the projected model, but i will set it to List for now to workaround the issue. If this is something that is fixable in AM, could you reopen the ticket?

**Comment by lbargaoanu** [comment]
We need a PR, not an issue. I'm not going to do anything about it because EF6 doesn't support it. @jbogard will reopen the issue if he's so inclined.

**Comment by jbogard** [comment]
I suppose we might want to start caring more about EF Core?

**Comment by lbargaoanu** [comment]
I don't know. I mean, in a different package, certainly. But here, with the same code base, it could be tricky. Sometimes the providers are simply different. Until now we did some minor things that didn't break EF6, but surely that's not always possible.

**Comment by lbargaoanu** [comment]
For example, #3328.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/pull/3223

**Comment by Baune8D** [comment]
> #3223

Just tried newest AutoMapper package from MyGet and the problems is solved. Hoping for a new release soon :)
