### ISSUE TITLE
Unable to use TypeCode in Destination

### ISSUE THREAD

**Issue by chen365409389** [AutoMapper/AutoMapper#3343]
I got a very strange problem,when i add a property named [IdTypeCode] with decimal type in 
 Destination,the Map method will throw an exception. Does anyone know how to solve it? Thanks.

    public class Source
    {
        public int Id { get; set; }
    }

    public class Destination
    {
        public int Id { get; set; }
        public decimal? IdTypeCode { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var configuration = new MapperConfiguration(c => c.CreateMap<Source, Destination>());
            var mapper = configuration.CreateMapper();
            //will throw an exception
            var dest = mapper.Map<Destination>(new Source
            {
                Id = 1
            });
        }
    }

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).
