### ISSUE TITLE
8.1.1 Upgrade guide

### ISSUE THREAD

**Issue by tboby** [AutoMapper/AutoMapper#3344]
Would you be open to a PR adding a paragraph about the 8.1.1 breaking changes to https://docs.automapper.org/en/stable/8.0-Upgrade-Guide.html ?

I've spent 30 minutes trying to work out why on earth my mapping were broken, would like to prevent others having the same problem!

I've seen responses saying "Just update straight to 9.0", but on large projects I much prefer upgrading one breaking change at a time. In 2/3 years when we're at version 12 with "10.0 upgrade guide" and "12.0" upgrade guide it might not be practical to go straight from 6 to 12.

**Comment by lbargaoanu** [comment]
You get an error message that tells you that a map is missing. How is that difficult to fix?

**Comment by tboby** [comment]
The error made no sense from my understanding of (and the documented behaviour) of 8.0.
I'm not in the habit of blindly fixing an error that I don't understand, and I could see no reason validation was failing. 

There are a number of github issues from people who have been caught out by this change.
What's the harm in documenting it?

Would you accept a PR adding a brief explanation that 8.1.1 had a breaking change and to either upgrade to 8.1.0 or skip to 9.0?

**Comment by lbargaoanu** [comment]
Fire away.

**Comment by lbargaoanu** [comment]
But add a new doc for 8.1.1. Make it obvious.
