### ISSUE TITLE
Automapper overwriting property with a setter.

### ISSUE THREAD

**Issue by tommymh** [AutoMapper/AutoMapper#3346]
Automapper is overwriting a public property without a setter, from the documentation I believe this is not the expected behavior.  Is this a bug or am doing something wrong?

`public Instant Created { get; }`

Just to be clear, I want this property to be read by Automapper, but not written to.  It is in a BaseEntity class, so I would like to not have to Ignore() it explicitly in all the child class maps, and it seems like something that shouldn't require an extension method or something along those lines to accomplish.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by tommymh** [comment]
I disagree, I've searched StackOverflow and this is not the expected behavior described by the author in the documentation or in the other related issues.  It was a simple question, is this a bug or do you believe I am doing something wrong?  I believe that merits a better answer than just outsourcing the question to a third party.

**Comment by jbogard** [comment]
Are you mapping to an existing item? In that case we will not override the object, but we will override that object's properties. That's normal and expected behavior.

**Comment by tommymh** [comment]
No, to a new item where the property in question is set in the constructor.

**Comment by jbogard** [comment]
AutoMapper maps to constructors too - I think any further help, we'd need to see your source/destination types and usage.

**Comment by tommymh** [comment]
I will have to adjust my code a bit so I'm not exposing anything sensitive, I will update this issue with a code example shortly.
