### ISSUE TITLE
Bug with recursive resolving

### ISSUE THREAD

**Issue by Cubelaster** [AutoMapper/AutoMapper#3348]
### Source/destination types

Removed a large part of code for abbreviation.

```csharp
// Put your source/destination types here

    public class OfferItemGridViewModel
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        
        public List<OfferItemGridViewModel> OfferItems { get; set; } = new List<OfferItemGridViewModel>();
     }
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
CreateMap<Offer, OfferGridViewModel>().ForMember(dest => dest.OfferItems, opt => opt.MapFrom(src => src.Where(FirstCondition)));

CreateMap<OfferItem, OfferItemGridViewModel>().ForMember(dest => dest.OfferItems, opt => opt.MapFrom(src => src.Where(SecondCondition)));

```

### Expected behavior

I expect the AutoMapper <3 to resolve all the Parent <-> Child relations.

### Actual behavior

The bug seems to come if I put the SAME class as a List of child classes inside child class. 
So, what happens is next: I have a ParentClass that contains a List of ChildClass-es, which in turn contain a List of ChildClass-es. Kinda like recursion. 
Anyways, the ProjectTo bugs out while resolving the query. 
If I want to have the same classes as children, then it resolves the query only ONCE, with filters and params from first level. So, If I say that I want an Item with a certain ParentId, then when the query comes to projecting the children of first items, it will return empty array, because nothing matches the FirstCondition. 
Also, if I just switch the model inside Child collection to some other model, it seems to do another, seperated query for those and everything works ok. 

This might be just me not understanding what's going on but it's strange anyway. MapTo works just fine, but that requires me to materialize everything before mapping it and I don't want that. 

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed

mapper.ProjectTo<OfferNewViewModel>(query).ToList();
```

**Comment by lbargaoanu** [comment]
This was discussed many times before, here and on SO. EF6 doesn't support it, so we don't support it.

**Comment by Cubelaster** [comment]
> This was discussed many times before, here and on SO. EF6 doesn't support it, so we don't support it.

This is all I needed to hear. 
I thought I was doing something wrong. 
In any case, I have found a workaround.
Thank you for the info and your time. 
AutoMapper rocks! <3
