### ISSUE TITLE
ReverseMap() doesn't reverse naming conventions

### ISSUE THREAD

**Issue by jez9999** [AutoMapper/AutoMapper#3351]
I'm aware that this bug has been submitted a couple of times before, but I don't understand why a fix hasn't been put in place.  Looking at this recent report of the issue:
https://github.com/AutoMapper/AutoMapper/issues/3259

The conclusion is:
> "I had to use two different profiles for mapping the models' bidirectionally based on a naming convention. Can't the ReverseMap() do this for us?"
> 
> "I don't see how. But a PR is welcome."

Don't see how?  How about, when generating the mappings during `ReverseMap`, have the option to pass in a boolean to `ReverseMap` that swaps `SourceMemberNamingConvention` and `DestinationMemberNamingConvention` for the mappings that it sets up?  Why is that so impossible?

**Comment by lbargaoanu** [comment]
Well, give it a shot then.

**Comment by jez9999** [comment]
@lbargaoanu Why close this, then?  Leave it open a while for me to submit a pull request?!

**Comment by jez9999** [comment]
@jbogard What do you think about this?  If you're using naming conventions to map A to B, I can't really think of a circumstance where you wouldn't want to reverse those conventions when going the other way.  As it stands, I'd say `ReverseMap` is only useful right now if the naming conventions are the same for both objects.

**Comment by lbargaoanu** [comment]
We don't need an issue, we need a PR. Feel free to discuss :)

**Comment by jez9999** [comment]
You keep issues open when you acknowledge that something is a valid bug or feature request, but doesn't yet have a PR.  Almost all projects I've seen have taken this approach.  It's how you track stuff that is open for development, but hasn't yet been developed.  You don't close it if it's a valid request.
