### ISSUE TITLE
Dynamic ProjectTo

### ISSUE THREAD

**Issue by jods4** [AutoMapper/AutoMapper#3352]
Unlike, `Map`, `ProjectTo` doesn't have a non-generic version:
```cs
IQueryable ProjectTo(IQueryable source, Type target, ...);
```

It's an edge case but it is useful when writing dynamic code.

**Comment by lbargaoanu** [comment]
Explain a little more about your use case. What are you trying to achieve?

**Comment by jods4** [comment]
Writing code that projects to a type determined at runtime.

Basically it's the same reason why you have `Map<Target>(object source)` and `Map(object source, Type target)`: the first one is nice to use in statically typed code, the second one is required when the target type is dynamically known at runtime.

`ProjectTo` only has a generic version, so it's impossible to use a target type determined at runtime (unless you do some ugly reflection to instantiate the generic type).

Example use case: a web api filter
```cs
class MyLittlePonyApiController {
  [HttpGet()]
  [ProjectTo(typeof(LittlePonyDto))]
  IQueryable<LittlePony> GetAllPonies() 
  {
    return db.Query<LittlePony>();
  }
}
```

**Comment by lbargaoanu** [comment]
I don't know :) If you're willing to implement it yourself, perhaps @jbogard will take a PR.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/4733ea8b1306cdee2484cde5891701eabca3f659/src/AutoMapper/QueryableExtensions/ProjectionExpression.cs#L35

**Comment by jods4** [comment]
Yes, this is exactly what I did.
I copied that line + `Select` + `FindQueryableSelectMethod` into my project and so I have my own non-generic `ProjectTo`.

Note that these APIs are private, which is why I had to copy-paste them and very ugly, which is why I'd rather use `Automapper` and not code that myself.

In this file it's clear that exposing a public `IQueryable ProjectTo()` is trivial, everything's already there, and that's what I'm asking for in this issue.

**Comment by lbargaoanu** [comment]
OK, if it's trivial, then PR away and we'll see. Or whatever works for you.

**Comment by jods4** [comment]
@lbargaoanu Why did you close this? 
Did you fix it (I don't see a commit) or are you opposed to adding this feature?
If you're awaiting a PR I can do it (it's trivial the API already exist, it's just not public) but I don't have time right, too much work.

**Comment by lbargaoanu** [comment]
We'll take a look at that PR whenever it's ready.

**Comment by jods4** [comment]
So maybe reopen, add a tag pr-welcome?
Closing hides the issue from anyone who may want to contribute (and closing without a message is a strange OSS etiquette).

I understand cleaning up old issues that nobody talks or acts upon, but 1 week is hardly old.

**Comment by jbogard** [comment]
Let's keep this open @lbargaoanu, perhaps we need a stale issue bot integration? https://github.com/apps/stale we can set it to something reasonable (2 months?)

**Comment by lbargaoanu** [comment]
How many users would this feature have? More than five? :)
