### ISSUE TITLE
Business logic with ProjectTo. Is it real?

### ISSUE THREAD

**Issue by bretbas** [AutoMapper/AutoMapper#3358]
Hello. I like to use ProjectTo with EF Core.
But I don't know how to solve that problem:

I have some business logic, let's say I have a `Post`, and I map it in the `PostListReadModel`. Each `PostListReadModel` has the `IsLiked` property, which identifies whether the current user liked the post or not. If I used `Select`, it would look something like this:
```
var userId = securityService.GetUserId();

var posts= await appContext.Posts
	.Select(x => new PostListReadModel()
	{
		// Other mapping...
		IsLiked = x.Likes.Any(x => x.UserId == userId)
		// Other mapping...
	})
	.ToListAsync();
```
But with `ProjectTo` I can't do that.
Or another example:
I have a `Post`, and I also map it in the `PostListReadModel`. Each `Post` have `Publisher` property, and I want map that property only if the `Post.IsAnonymous = false` or if the current user is Admin.
With `Select` I do that:
```
var userId = securityService.GetUserId();
var role = userManager.GetUserRole(userId);
var posts= await appContext.Posts
	.Select(x => new PostListReadModel()
	{
		// Other mapping...
		Publisher = role == RoleType.Admin || !x.IsAnonymous ?
			new PostPublisherReadModel()
			{
				// Other mapping for post publisher...
			} :
			null
		// Other mapping...
	})
	.ToListAsync();
```
But with `ProjectTo` I also don't know how to do that!

So, maybe you can tell me how to combine business logic with projection in the form of `ProjectTo`

**Comment by lbargaoanu** [comment]
Would you write it in SQL? Then I guess you can write it in`ProjectTo`. But that would mean it's pretty trivial. Because if it isn't, it deserves a prominent place in your app, not the AM configuration. AM is not a business rules engine.

**Comment by bretbas** [comment]
> Would you write it in SQL? Then I guess you can write it in`ProjectTo`. But that would mean it's pretty trivial. Because if it isn't, it deserves a prominent place in your app, not the AM configuration. AM is not a business rules engine.

I didn’t say that there should be any business rules in the map configuration. 
I asked how `ProjectTo` can be combined with business rules. I had two problems that I described above. And their solution is only to abandon the use of `ProjectTo`.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by bretbas** [comment]
> I think this is better suited for StackOverflow.

I asked a question on SO:
https://stackoverflow.com/questions/60864762/business-logic-with-projectto

**Comment by lixaotec** [comment]
I have the same need.

I understand that business logic isn´t apropriated for ProjectTo, because business logic means change data essencially.

But this is retrieving needs, so it would be nice if projectto could accept resolvers on the go
