### ISSUE TITLE
PreCondition does not work with ProjectTo

### ISSUE THREAD

**Issue by Cubelaster** [AutoMapper/AutoMapper#3360]
### Source/destination types

```csharp
// Put your source/destination types here
```

Doesn't really matter, so I'm gonna skip this step.
The only thing that is important is that a Parent class has a list of Child objects.

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 

            CreateMap<Note, NoteGridViewModel>()
                .ForMember(dest => dest.NoteItems, opt =>
                {
                    opt.PreCondition(src => src.NoteTypeId != (int)NoteTypeEnum.MedicalRecord);
                    opt.MapFrom(src => src.NoteItems.Where(ni => ni.Active));
                });
```

### Version: x.y.z
 
Installed version: 9.0.0

### Expected behavior

I expected that the PreCondition would kick in and stop the Map from happening.

### Actual behavior

It maps everything, like the PreCondition does not exist.
Identical to this problem. 
https://stackoverflow.com/questions/40658582/automapper-whats-difference-between-condition-and-precondition

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
mapper.ProjectTo<NoteGridViewModel>(query.OrderByDescending(e => e.CreationDate)).ToList()
```

**Comment by jbogard** [comment]
`ProjectTo` generates a LINQ `Select` expression. How would you accomplish this with just expressions and your query provider? I assume you're using EF6 or EF Core, try to do this without AutoMapper.

**Comment by Cubelaster** [comment]
Yes, I'm using EF Core. I know how I could do it without AutoMapper, no problem at all, however, I prefer AutoMapper because it's simpler and cleaner. 
The query in question would be huge without AutoMapper, that's the main reason I prefer AutoMapper. 
If I used a query, I'd select an empty list instead of a query below, which is supposed to happen according to AutoMapper documentation.
But I can't make PreCondition to work and now I can't even make a 
```csharp
CreateMap<Note, NoteGridViewModel>()
                .ForMember(dest => dest.NoteItems, opt => opt.MapFrom(src => src.NoteTypeId == (int)NoteTypeEnum.MedicalRecord ? src.NoteItems.Where(ni => ni.Active) : Enumerable.Empty<NoteItem>()));
```
because it says that "Argument types do not match".
This weirds me out, but obviously I'm doing something wrong. However, I can't find the correct way to do it at the moment.

**Comment by jbogard** [comment]
Show code that uses EF Core with projections WITHOUT AutoMapper. I don't know how to do conditions like this in LINQ, so now I'm curious how you got it to work with EF Core.

**Comment by Cubelaster** [comment]
```csharp
                var bla = query
                    .Include(src => src.NoteItems)
                    .Select(x => new Note
                    {
                        Id = x.Id,
                        NoteTypeId = x.NoteTypeId,
                        NoteItems = x.NoteTypeId == (int)NoteTypeEnum.MedicalRecord ? x.NoteItems.Where(ni => ni.Active).ToList() : Enumerable.Empty<NoteItem>().ToList()
                    })
                    .ToList();
```

This is a bit simplified, but gets the job done.
If I wanted to do the complete thing, I'd have to make another IQueryable that would be triggered if true. 
It would work, because that's the way I used it before AutoMapper.

Did I missunderstand?

**Comment by jbogard** [comment]
So conditions are *not* supported for queryable extensions:

https://docs.automapper.org/en/stable/Queryable-Extensions.html#supported-mapping-options

Mainly because our target is what EF can support. Conditions are used to skip a mapping altogether, whereas the condition you have is to provide an alternate value.

If the conditional expression throws an exception in `MapFrom`, that's a different issue altogether, and you an open a separate one for that.

We won't support Condition, however, because its purpose is to be able to skip a mapping which just isn't possible.

**Comment by Cubelaster** [comment]
Oh, I see now. I apologize. 
I actually read through this part of the documentation, just obviously didn't completely understand it. 
Although, what I want to do is to skip a mapping altogether, just like in this example.
https://docs.automapper.org/en/stable/Conditional-mapping.html#preconditions
I obviously failed to understand that this is not supported in ProjectTo mode. 

Anyway, thank you for your time and once again I apologize.

**Comment by Cubelaster** [comment]
I'd like to add that I prefer using AutoMapper only one way: either Map or ProjectTo. 
Having the same Profile working for Map, but not ProjectTo makes it extremely prone to runtime errors. 
As can be seen in my case. 
I see you opened a feature request and I believe that is a step in right direction. Maybe more detailed documentation is a great first step. 
If anything, it would be great if IntelliSense would somehow error out if we're using ProjectTo with something that it can't support. I believe that at this point it is unrealistic. 
Anyway, thank you a lot!

**Comment by jbogard** [comment]
Oh, it's more complicated than that.

Dictionary/dynamic/DataReader all read the configuration and perform their own mapping strategy.

The only way around this is different configuration and validation for different kinds of maps. That way we only expose and validate the mapping you intend. That'd be almost impossible at this point, since you can mix projections and in-memory and all the mappings in a single codebase.
