### ISSUE TITLE
Attribute-based reverse map customization

### ISSUE THREAD

**Issue by jods4** [AutoMapper/AutoMapper#3362]
### Feature description
You can automatically map classes with `[AutoMap]` and the mapping itself can be customized through attributes on fields.

Additionnally, `[AutoMap(ReverseMap = true)]` will call `ReverseMap` on the mapping and, well, create the reverse map.

That reverse map is not configurable though, you have to be ok with all the defaults. My use case for example is that I want to ignore some members when reversing a map.

### Possible syntax
Maybe have a `Reverse` property on `IMemberConfigurationProvider` that indicate the customization applies to a reverse map:

```csharp
[AutoMap(typeof(SomeModel), ReverseMap = true)]
class SomeDto
{
  [Ignore(Reverse = true)]
  public string OneWayProperty { get; set; }
}
```

Note: adding a property to an interface is a breaking change for users who created their own attributes based on that interface. 
This breaking change could be avoided by introducing a new derived interface instead:
```csharp
interface IReverseMemberConfigurationProvider : IMemberConfigurationProvider
{
  bool Reverse { get; set; }
}
```

### Implementation
Every `IMemberConfigurationProvider` is collected and applied here:
https://github.com/AutoMapper/AutoMapper/blob/0189c1e09ab7f60026317bb792ef8f61b72f2e96/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L97

And then the reverse map is created inside this call:
https://github.com/AutoMapper/AutoMapper/blob/0189c1e09ab7f60026317bb792ef8f61b72f2e96/src/AutoMapper/Configuration/MapperConfigurationExpression.cs#L103

One would need to collect and put aside providers that apply to the reverse map and apply them once the reverse map is created.

### Alternatives
When using attributes and auto mapping discovery, customizing the reverse map is practically impossible.

The alternative is to map by writing and discovering profiles in code.

**Comment by jods4** [comment]
@lbargaoanu 
I could have a shot at this if the AutoMapper team told me what would be an acceptable design?

Add a `Reverse` bool to all attributes indicating they apply to reverse map?
- Would you be ok breaking `IMemberConfigurationProvider` in a major update?
- Would you rather a derived interface implemented by all built-in attributes, `IReverseMemberConfigurationProvider`, or maybe `IMemberConfigurationProvider9` (because it's introduced in v9), or another name? Would that mark the old attribute obsolete?

Do you have another idea for the api design?

**Comment by jods4** [comment]
I'm having a go at this.
The tricky bit is that configuration uses `ForMember(destinationMember)` but when it is the reverse map attribute would be on the source member.

What's the best way to find a `destinationMember` (assuming there's such a member) for the reverse map given a the destination member of the forward map?

**Comment by jbogard** [comment]
So you want to ignore members only in one direction?

**Comment by jods4** [comment]
My specific use-case here was a DTO that included some readonly fields.

```csharp
class Model 
{
  int P1 { get; set; }
  int P2 { get; set; }
}

// This DTO is mapped both ways so that one API can send it to client (Model -> Dto)
// And another API receives the DTO back for update (Dto -> Model)
[AutoMap(typeof(Model), ReverseMap = true)]
class Dto
{
  // This is sent to client and can be updated back.
  int P1 { get; set; }
  // This is sent to client but it is forbidden to attempt a modification
  [Ignore(Reverse = true)]
  int P2 { get; set; }
}
```
