### ISSUE TITLE
Accessing contextual target type

### ISSUE THREAD

**Issue by jods4** [AutoMapper/AutoMapper#3363]
### Use case
Let's say you're writing a mapping based on an interface. You want every `INamed` (which is an interface with a `string Name` property) to be mappable to a `string`. Easy enough:

```csharp
config.CreateMap<INamed, string>().ConvertUsing(source => source.Name);
```

So far, so good but now I would like to create the reverse map.
It does work but not in a way that helps me. AutoMapper creates its own dynamic class implementing `INamed` and returns that.

What I would like is being able to instantiate the interface by using the contextual target type:
```csharp
class Model
{
  // Person is INamed. 
  public Person Manager { get; set; }
}

[AutoMap(typeof(Model), ReverseMap = true)]
class DTO
{
  public string Manager { get; set; }
}
```
Going Model -> DTO works as expected, now I would like to be able to got DTO -> Model as well.
It crashes at runtime because AutoMapper tries to cast its dynamic `INamed` class into `Person`.

### Proposal
The problem is that AutoMapper doesn't seem to have a concept of contextual target type. It doesn't automatically try to instantiate a `Person` instead of `INamed`, nor does it expose this information in any API such as `ConvertUsing`.

I would be totally fine with this:
```csharp
config.CreateMap<string, INamed>()
      .ConvertUsing((name, context) => 
      {
        var type = context.ContextualTargetType;  // Person
        var result = Activator.CreateInstance(type) as INamed;
        result.Name = name;
        return result;
      });
```

### Alternatives
This can be worked around by creating a specific map for every `INamed` class that you want to reverse map to.

In a situation where mappings are discovered and registered automatically this isn't very convenient.

**Comment by jods4** [comment]
@lbargaoanu I am a bit surprised to see you added the "up for grabs", given how little design has been discussed for such a complex feature.

Any idea from AutoMapper team if this is even possible and how it should be done? 

It would be a nifty thing to have, e.g. when mapping to interfaces or base classes, but honestly I have no idea where to start on this one.

**Comment by jbogard** [comment]
I don’t either. I think you’ll need to poke around to see where it makes sense.

**Comment by lbargaoanu** [comment]
@jbogard Dumping things on the context again is not a good idea. Been there, done that :)
