### ISSUE TITLE
Support conditional operators

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#3364]
Per #3361 and #3360 perhaps we need something that can handle conditional operators:

```
var posts = await appContext.Posts
	.Select(x => new PostListReadModel()
	{
		IsAnonymous = x.IsAnonymous,
		Publisher = !x.IsAnonymous ?
			new PostPublisherReadModel()
			{
				Id = x.PublisherId,
				Nick = x.Publisher.Nick,
				PhoneNumber = x.Publisher.PhoneNumber,
				Avatar = x.Publisher.Avatar
			} :
			null
	})
	.ToListAsync();
```

If that works with EF Core, we should be able to do something very similar with:

```csharp
Condition(Expression<Func<TSource, bool>> condition,
    Expression<Func<TSource, TMember>> ifFalse)
```

**Comment by lbargaoanu** [comment]
But isn't the initial code more readable? :)

**Comment by lbargaoanu** [comment]
And I don't see the difference from EF6.

**Comment by jbogard** [comment]
EF6 supports this?

**Comment by lbargaoanu** [comment]
I don't see why it wouldn't. My test:

    ForMember(d=>d.Id, o=>o.MapFrom(s=>s.Name == "P3" ? s.Id : 2323))

**Comment by jbogard** [comment]
Ohhhhh so we can already support this just with `MapFrom` and not `Condition`. Maybe we just need something in the docs as a clarification?

**Comment by lbargaoanu** [comment]
You could add a paragraph at the end, but I don't know, there are _a lot_ of differences between `Map` and `ProjectTo`. I feel like that's what people are missing. The principle. Once you know that, it's easy to guess that probably `ProjectTo` doesn't support it and check that section if you can find it :)

**Comment by jbogard** [comment]
I think we just need a much more prominent set of docs around `ProjectTo`. Right now it's just a single menu item alongside the others.
