### ISSUE TITLE
Mapping to Enumerable.Empty<T> throws in netcoreapp3.1

### ISSUE THREAD

**Issue by natehitze** [AutoMapper/AutoMapper#3365]
I believe it is related to this issue: https://github.com/dotnet/runtime/issues/27552
```csharp
public class SourceClass
{
    public IEnumerable<string> Values { get; set; }
}
public class TargetClass
{
    public IEnumerable<string> Values { get; set; }
}
var config = new MapperConfiguration(cfg => cfg.CreateMap<SourceClass, TargetClass>());
var mapper = new Mapper(config);
var source = new SourceClass { Values = new string[0] };
var existingTarget = new TargetClass { Values = Enumerable.Empty<string>() };
// This line throws in netcoreapp3.1 but not in netcoreapp2.2
mapper.Map(source, existingTarget);
```
### Expected behavior

Not to throw an exception.
### Actual behavior
```
Unable to cast object of type 'System.Linq.EmptyPartition`1[System.String]' to type 'System.Collections.Generic.IList`1[System.String]'.
```

**Comment by lbargaoanu** [comment]
But the thing is, this mapping can't possibly succeed. You cannot map into an existing destination that's not `IList`. Removing the setter would make this clear.

**Comment by lbargaoanu** [comment]
I guess the fix would be to silently ignore the mapping. Nothing that can't be done with an extra check. We are enabling this kind of use case by checking the runtime type instead of the compile time type. But that ship has sailed :) A PR is welcome.

**Comment by natehitze** [comment]
I'm a little confused on why `IList` is required. If the destination type is `IEnumerable<T>` couldn't we just map the source items to a new list and assign that to the destination? It seems like `CollectionMapperExpressionFactory.MapCollectionExpression` does something similar for read only collections. Or maybe call `.ToList()` on the destination type and use that as the destination instead of using a cast?

My use case is mapping an update request to a database object that eager loads related data. If there is not any related data objects the database mapper assigns the related data property `Enumerable.Empty<T>`. I'm "lucky" enough that I control how the database mapping works so I could assign something else (like `Array.Empty<T>`). 

What would you suggest changing in the example code going forward? Should I manually `.ToList()` the related data collections on my destination object before mapping over it? Or change all of my related data collections to `IList<T>` instead of `IEnumerable<T>`?

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).  And compare with not passing a destination object.

**Comment by lbargaoanu** [comment]
@jbogard I tend to see this as an usage error.

**Comment by jbogard** [comment]
Oh this is very weird. That logic is incorrect in the mapper, though. We test for `IEnumerable` || `IList` but then assume `IList`. We shouldn't.

**Comment by natehitze** [comment]
I've been trying to work up a solution but I'm not sure what I'm missing here.

Here's my rough current version of EnumerableMapper. It seems like the `.ToList()` and filling the list work fine but the result never gets assigned to the destination property.
https://gist.github.com/natehitze/174b8835e7d73d3c4a65d0acbbcd9aca

**Comment by lbargaoanu** [comment]
@jbogard How else would you clear it?

**Comment by jbogard** [comment]
We don't - if it's got a setter, we replace it.

**Comment by lbargaoanu** [comment]
You cannot replace it when mapping to an existing instance.

**Comment by jbogard** [comment]
Ah, I see that now. It is a usage error - @natehitze for mapping to existing objects, we don't replace destination collections. This is because ORMs don't really like you to do that, they want you to interact with the existing collection object. In your case, we can't.

@lbargaoanu if we want, we could make this a stricter check in configuration validation. As-is, it's a bit of an internal assumption.

**Comment by lbargaoanu** [comment]
Yes, that makes sense. But potentially a huge breaking change :) That's what I was hinting at above.

**Comment by jbogard** [comment]
Oof. Right. I don't know if we even want to do a runtime check in that case - it'll just add overhead.

**Comment by lbargaoanu** [comment]
OK, so in conclusion, when mapping to an existing instance you have to pass a type that can be cleared. `Enumerable.Empty<T>` isn't clear-able anymore, so it's unsuitable for the task.

**Comment by natehitze** [comment]
Destination collections do get replaced if the destination collection is read only (e.g. arrays). Could AutoMapper treat all `IEnumerable<T>` destination collections as read only and not necessarily a list type until proven otherwise - perhaps by a runtime check that the type implements IList and then checking the type's `IsReadOnly == false`? 
Or if that's too much overhead leave the existing mapper as is and add a second mapper that can be enabled via option that treats all `IEnumerable<T>` destinations as read only and maps by replacement without any checks? In my case that kind of global behavior would be acceptable.

**Comment by lbargaoanu** [comment]
You can always replace the existing mapper with your own. There is even an option to write it without expressions.

**Comment by Tasteful** [comment]
Sounds that you more or less run into the same problem as I in https://github.com/AutoMapper/AutoMapper/issues/1973 where the destination value is an readonly instance. In my case it was an array that was assigned to the ICollection and sounds as the same problem.

**Comment by natehitze** [comment]
The option to write it without expressions would be [Type Converters](https://automapper.readthedocs.io/en/latest/Custom-type-converters.html), correct? Can you point in the direction of how to accomplish that? 

I tried adding the following Type Converter to the configuration from the start of the issue:
```csharp
cfg.CreateMap(typeof(IEnumerable<>), typeof(IEnumerable<>)).ConvertUsing(typeof(EnumerableTypeConverter<,>));
```
```csharp
public class EnumerableTypeConverter<TEnumerableSource, TEnumerableDestination> : ITypeConverter<TEnumerableSource, TEnumerableDestination>
{
    public TEnumerableDestination Convert(TEnumerableSource source, TEnumerableDestination destination, ResolutionContext context)
    {
        return destination;
    }
}
```

But I get an exception when executing the mapping:
```
System.InvalidCastException: Unable to cast object of type 'EnumerableTypeConverter`2[System.String,System.String]' to type 'AutoMapper.ITypeConverter`2[System.Collections.Generic.IEnumerable`1[System.String],System.Collections.Generic.IEnumerable`1[System.String]]'.
   at lambda_method(Closure , SourceClass , TargetClass , ResolutionContext )
```
