### ISSUE TITLE
ProjectTo generates constant expressions from parameters

### ISSUE THREAD

**Issue by dejvid-smth** [AutoMapper/AutoMapper#3370]
### Source/destination types

```csharp
class FromModel
{
    public int Id { get; set; }
}

class ToModel
{
    public int Id { get; set; }

    public ToModel(int ctorParamValue)
    {
        
    }
}
```

### Mapping configuration

```csharp
new AutoMapper.MapperConfiguration(e =>
    {
        var ctorParamValue = 0;
        e.CreateMap<FromModel, ToModel>()
            .ConstructUsing(from => new ToModel(ctorParamValue));
    })
```

### Version: 9.0.0
AutoMapper 9.0.0
Microsoft.EntityFrameworkCore 3.1.3

### Expected behavior

I would expect the test to pass. I have used similar code with AutoMapper 8 and EF Core 2.2. 
I am not sure if this can be achieved. 
From what I understand AutoMapper translates the constructor parameter to constant expression which EF does not like since it would cache it. But I want the query to always use the (new) provided instance of the parameter value. 
I think that would require AutoMapper to translate the parameter value to something else than constant expression.

### Actual behavior

I get an exception:
```
System.InvalidOperationException : Client projection contains reference to constant expression of '.<>f__AnonymousType0<int>'. This could potentially cause memory leak. Consider assigning this constant to local variable and using the variable in the query instead. See https://go.microsoft.com/fwlink/?linkid=2103067 for more information.
```

### Steps to reproduce

```csharp
class TestContext : DbContext
{
    public DbSet<FromModel> Froms { get; set; }
}

class FromModel
{
    public int Id { get; set; }
}

class ToModel
{
    public int Id { get; set; }

    public ToModel(int ctorParamValue)
    {
        
    }
}

[Fact]
public void ProveIssue()
{
    var cfg = BuildConfig();

    using var ctx = new TestContext();

    var ctorParamValue = 10;
    var entity = ctx.Froms
        .AsNoTracking()
        .ProjectTo<ToModel>(cfg, new { ctorParamValue })
        .First();

    //the above code should have not thrown an exception
    Assert.True(true);
}

private AutoMapper.IConfigurationProvider BuildConfig()
{
    return new AutoMapper.MapperConfiguration(e =>
    {
        var ctorParamValue = 0;
        e.CreateMap<FromModel, ToModel>()
            .ConstructUsing(from => new ToModel(ctorParamValue));
    });
}
```

**Comment by lbargaoanu** [comment]
Use the other overload for passing parameters.

**Comment by lbargaoanu** [comment]
Actually no, it seems the object one is the right overload.

**Comment by lbargaoanu** [comment]
Actually I don't see anything wrong in the expression. So look at the EF Core part. I have no idea what it's saying, but try to do that :) Our main use case is EF6 and it doesn't support constructor parameters. Also try that without AM, just with an EF LINQ query. How would you do that?

**Comment by dejvid-smth** [comment]
I have tried to rewrite the code to work without AutoMapper like you suggested. It still threw that exception but that seemed weird to me since I have remembered that I have used constructor parameter with EF Core without AutoMapper before. 

I have found out that when the target object's constructor directly requires a parameter that causes the exception to be thrown by EF Core. Although, when we construct different object in the expression which accepts a parameter in ctor then it works. See below example.

```csharp
class FromModel
{
    public int Id { get; set; }
}

class ToModel
{
    public int Id { get; set; }

    public WithParam WithParam { get; set; }

    public ToModel()
    {
        
    }
}

class WithParam
{
    public WithParam(object us)
    {
            
    }
}

private static Expression<Func<FromModel, ToModel>> CreateMapper(object value) => 
    //if we passed `value` to ToModel ctor EF Core would throw the exception
    x => new ToModel
    {
        Skey = x.Skey,
        //EF Core has no problem with this constructor parameter being a reference to arbitrary object
        WithParam = new WithParam(value)
    };

[Fact]
public async Task NoAutoMapper()
{
    using var ctx = new TestContext();

    var v = new object();
    _ = await ctx.Froms
        .AsNoTracking()
        .Select(CreateMapper(v))
        .FirstOrDefaultAsync();

    Assert.True(true);
}
```

 I don't quite understand why it works like that but I will ask this over at EF repo. Thanks for making me realize that.

**Comment by lbargaoanu** [comment]
You could workaround it by using the dictionary overload to pass parameters. But the the problem with that one is that it just embeds a constant in a query so it generates a different query every time, as opposed a parameterized query. At least that's what happens in EF6.
