### ISSUE TITLE
Constructor mapping is not working for 'immutable' class.

### ISSUE THREAD

**Issue by gongdo** [AutoMapper/AutoMapper#3372]
All code bellow, is on https://gist.github.com/gongdo/5dac34a73421628cc82ad92102995440

### Source/destination types

```csharp
public struct Source
{
    public string Property { get; set; }
}
// readonly struct version---------------------------
public readonly struct Destination
{
    public Destination(string property)
    {
        Property = property;
    }
    public string Property { get; }
}
// class version---------------------------
public class DestinationClass
{
    public DestinationClass(string property)
    {
        Property = property;
    }
    public string Property { get; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Destination>();
    cfg.CreateMap<Source, DestinationClass>();
});
```

### Expected behavior

The `source` is merged to `previous` destination and creates a new merged instance of destination, when the destination is 'immutable' that doesn't have any settable properties but constructor parameters.

### Actual behavior

It works for `struct` destination, even `readonly struct` works.
But same code doesn't work for `class` destination.

### Steps to reproduce
```csharp
var mapper = configuration.CreateMapper();
var source = new Source { Property = "value" };

// even readonly struct is ok
var prev = new Destination("prev");
var destination = mapper.Map(source, prev);
Debug.Assert(destination.Property == "value");

// but class, no luck.
var prevClass = new DestinationClass("prev");
var destinationClass = mapper.Map(source, prevClass);
Debug.Assert(destinationClass.Property == "value");
```

I'm not sure if this behavior is designed or not.
However, if a mapping works for `struct`, it should be worked for `class` too, IMHO.

**Comment by lbargaoanu** [comment]
Let's continue on SO.
