### ISSUE TITLE
Adjust collection mapping matching?

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#3376]
More of a question - the collection initializer syntax for C# is rather loose in its rules to have maximum flexibility:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers

Should we implement something similar? Basically separate out:

- What collection types to create for interface source types
- How to map them

Instead of forcing us down a path of supporting all these collection types, I wonder if we can genericize it a bit:

- Source/destination type must implement `IEnumerable`
- If destination type is an interface, we must know how to create it
- Otherwise, destination type must have an "Add" method
- For mapping to an existing value, destination type must have a "Clear" method ("IsReadOnly" might be optional here?)

Generic types with more than 1 argument are trickier of course, those might be exempt from this (dictionaries basically).

Thoughts?

**Comment by lbargaoanu** [comment]
I think it's easier for the compiler :) Doing it at runtime seems more complicated. Choosing between multiple `Add` methods comes to mind. Clearly more flexible, but perhaps more useful for advanced scenarios than for the everyday scenario of existing collection types. And being able to map into an existing `IEnumerable` wouldn't change.

**Comment by lbargaoanu** [comment]
I guess the only way this would work is with dynamic :)
