### ISSUE TITLE
 Unmapped properties: Capacity

### ISSUE THREAD

**Issue by andry85mae** [AutoMapper/AutoMapper#3377]
hello

i try to use AutoMapper for a project but whit this code

`AutoMapper.Mapper.CreateMap<IDataReader, List<TResult>>();
 AutoMapper.Mapper.AssertConfigurationIsValid();
`

i have this error

> AutoMapperConfigurationException: Unmapped members were found. Review the types and members below. Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type ==================================================================================================================================================================================================================================================== IDataReader -> List`1 (Destination member list) System.Data.IDataReader -> System.Collections.Generic.List`1[[Databook.Services.DocumentiContabili.Controllers.WeatherForecastController+PivotResult, Databook.Services.DocumentiContabili, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] (Destination member list) Unmapped properties: Capacity

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
