### ISSUE TITLE
MemberList.Source doesn't work with referenced objects

### ISSUE THREAD

**Issue by btihanyi** [AutoMapper/AutoMapper#3386]
### Source/destination types

```csharp
public class A
{
    public string Text { get; set; }
}

public class B
{
    public string Text { get; set; }

    public string NotMapped { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<A, B>(MemberList.Source)
       .ForMember(b => b.Text, x => x.MapFrom(a => a.Text ?? string.Empty));
});
```

### Expected behavior

`config.AssertConfigurationIsValid()` should not throw an exception.

### Actual behavior

`AutoMapperConfigurationException` was thrown with the following text:

> Unmapped members were found. Review the types and members below. (...)
=================================================
A -> B (Source member list)
Unmapped properties:
Text

### Steps to reproduce

If I change `x.MapFrom(a => a.Text ?? string.Empty)` to `x.MapFrom(a => a.Text ?? "")`, it works without any problems.

So to reproduce the issue, a `MemberList.Source` must be used, then in a `ForMember` declaration an "outside" object should be used, even if it's a simple static member or a variable in the same scope.

**Comment by lbargaoanu** [comment]
I see your point, but that expression could be a lot more complicated, even involve more source members. I don't think we want to go there. If it's important to you, workaround it. Use a simple `MapFrom` and use some other way to implement the logic you need. `AllowNullDestinationValues`, `NullSubstitute`, value transformers, type converters or anything else might fit :)
