### ISSUE TITLE
SetMappingOrder / Condition statement not evaluated on Included child objects

### ISSUE THREAD

**Issue by robvangeloven** [AutoMapper/AutoMapper#339]
The SetMappingOrder statement and the Condition statement do not propagate to child objects as the code demonstrates below.
This makes it difficult to use the inheritance structure provided by AutoMapper as the mapping order has to be specified for each field in each child object (where needed of course)

//SetMappingOrder demo
public class Source
    {
        public string ClientID
        {
            get;
            set;
        }

```
    public string Foo
    {
        get;
        set;
    }
}

class Dest
{
    public Dest()
    {
    }

    private string id;
    public string ID
    {
        get
        {
            return id;
        }
        set
        {
            id = string.Concat(ID, value);
        }
    }

    private string foo;
    public string Foo
    {
        get
        {
            return foo;
        }
        set
        {
            foo = value;
            ID = value;
        }
    }
}

class ChildDest : Dest
{
    public string Bar
    {
        get;
        set;
    }
}

class Program
{
    static void Main(string[] args)
    {
        Mapper.CreateMap<Source, Dest>()
            .ForMember(dest => dest.ID, opt =>
                {
                    opt.Condition(src => !string.IsNullOrWhiteSpace(src.ClientID));
                    opt.SetMappingOrder(-1000);
                    opt.MapFrom(src => src.ClientID);
                })
            .Include<Source, ChildDest>();

        Mapper.CreateMap<Source, ChildDest>()
            .ForMember(dest => dest.Bar, opt => opt.Ignore());

        var source = new Source()
        {
            ClientID = "Test",
            Foo = "Bar"
        };

        var parentDest = Mapper.Map<Dest>(source);
        var childDest = Mapper.Map<ChildDest>(source);

        Debug.Assert(parentDest.ID == "TestBar");
        Debug.Assert(childDest.ID == "TestBar");
    }
}
```

//Condition demo
class Source
{
public string ClientID
{
get;
set;
}

```
public string Foo
{
    get;
    set;
}
```

}

class Dest
{
    public Dest()
    {
        ID = "12345";
    }

```
public string ID
{
    get;
    set;
}

public string Foo
{
    get;
    set;
}
```

}

class ChildDest : Dest
{
    public string Bar
    {
        get;
        set;
    }
}

class Program
{
    static void Main(string[] args)
    {
        Mapper.CreateMap<Source, Dest>()
            .ForMember(dest => dest.ID, opt =>
                {
                    opt.Condition(src => !string.IsNullOrWhiteSpace(src.ClientID));
                    opt.MapFrom(src => src.ClientID);
                })
            .Include<Source, ChildDest>();

```
    Mapper.CreateMap<Source, ChildDest>()
        .ForMember(dest => dest.Bar, opt => opt.Ignore());

    var source = new Source()
    {
        ClientID = "",
        Foo = "Bar"
    };

    var parentDest = Mapper.Map<Dest>(source);
    var childDest = Mapper.Map<ChildDest>(source);

    Debug.Assert(parentDest.ID == "12345");
    Debug.Assert(childDest.ID == "12345");
}
```

}

**Comment by philvx** [comment]
The mapping order still seems not to be inherited. At least the following unit test fails with the current automapper version:

`namespace AutomapperTest
{
    using AutoMapper;
    using NUnit.Framework;
    using Should;

    [TestFixture]    
    public class SetMappingOrderTest
    {
        class Source
        {
            public string One { get; set; }

            public string Two { get; set; }
        }

        class SourceChild : Source
        {

        }

        class Destination
        {
            // must be defined before property "One" to fail
            public string Two { get; set; }

            private string one;

            public string One
            {
                get
                {
                    return this.one;
                }

                set
                {
                    this.one = value;
                    this.Two = value;
                }
            }
        }

        [Test]
        // passing test
        public void TestMappingOrder_SourceToDestionation()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Source, Destination>()
                .Include<SourceChild, Destination>()
                .ForMember(dest => dest.One, opt => opt.SetMappingOrder(-500))
                .ForMember(dest => dest.Two, opt => opt.SetMappingOrder(600));

                cfg.CreateMap<SourceChild, Destination>();
            });

            var source = new Source() { One = "first", Two = "second" };

            source.One.ShouldEqual("first", "precondintion fails");
            source.Two.ShouldEqual("second", "precondintion fails");

            var mapper = config.CreateMapper();
            var destination = mapper.Map<Destination>(source);

            destination.One.ShouldEqual("first");
            destination.Two.ShouldEqual("second");
        }

        [Test]
        // failing test
        public void TestMappingOrder_SourceChildToDestionation()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Source, Destination>()
                .Include<SourceChild, Destination>()
                .ForMember(dest => dest.One, opt => opt.SetMappingOrder(-500))
                .ForMember(dest => dest.Two, opt => opt.SetMappingOrder(600));

                cfg.CreateMap<SourceChild, Destination>();
            });

            var source = new SourceChild() { One = "first", Two = "second" };

            source.One.ShouldEqual("first", "precondintion fails");
            source.Two.ShouldEqual("second", "precondintion fails");

            var mapper = config.CreateMapper();
            var destination = mapper.Map<Destination>(source);

            destination.One.ShouldEqual("first");
            destination.Two.ShouldEqual("second");
        }

        [Test]
        // failing test if the above one passes for random reasons
        public void TestMappingOrder_SourceChildToDestionation_ReverseOrder()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Source, Destination>()
                .Include<SourceChild, Destination>()
                .ForMember(dest => dest.One, opt => opt.SetMappingOrder(600))
                .ForMember(dest => dest.Two, opt => opt.SetMappingOrder(-500));

                cfg.CreateMap<SourceChild, Destination>();
            });

            var source = new SourceChild() { One = "first", Two = "second" };

            source.One.ShouldEqual("first", "precondintion fails");
            source.Two.ShouldEqual("second", "precondintion fails");

            var mapper = config.CreateMapper();
            var destination = mapper.Map<Destination>(source);

            destination.One.ShouldEqual("first");
            destination.Two.ShouldEqual("first");
        }
    }
}
`

**Comment by lbargaoanu** [comment]
@philvx You can try the MyGet build when #1230 is merged.
