### ISSUE TITLE
Option to disable ForAllOtherMembers extension

### ISSUE THREAD

**Issue by tomgruszowski** [AutoMapper/AutoMapper#3394]
Add the option to disable the ForAllOtherMembers extension, perhaps crash at runtime during startup.

This option has the potential to be abused, thus violating some AutoMapper best practices. I realize this is an odd request, but I'd rather leave a strict 'do not remove' comment around a single configuration line that disables this feature vs enforcing multiple mapping rules which get poorly mapped.

Yes this is a process problem on the team, but the reality is people forget and this keeps cropping up.

Any other suggestions on how to enforce this dangerous usage?

### Version: 9.x.x

**Comment by lbargaoanu** [comment]
:) I would write a Roslyn analyzer.

**Comment by lbargaoanu** [comment]
Perhaps you want to add smth useful in the documentation/xml docs.
