### ISSUE TITLE
Issue Mapping Inherited Classes to EF POCO Proxy

### ISSUE THREAD

**Issue by bhavens17** [AutoMapper/AutoMapper#3395]
See SO post [here](https://stackoverflow.com/questions/61397145/automapper-entity-framework-proxy-inherited-class-mapping-issue)

### Source/destination types

```csharp
//Source classes
public class PostDTO
{
    public DateTime PostDate { get; set; }
    public string Content { get; set; }
}

public class PostWithKeywordsDTO : PostDTO
{
    public string Keywords { get; set; }
}

//Destination Classes
public class Blog
{
    [Key]
    public int Id { get; set; }
    public string Title { get; set; }
}

public class Post
{
    [Key]
    public int Id { get; set; }
    public DateTime PostDate { get; set; }
    public string Content { get; set; }
    public string Keywords { get; set; }
    public virtual Blog Blog { get; set; }
}

public class MyDbContext : DbContext
{
    public MyDbContext()
    {
        base.Configuration.ProxyCreationEnabled = true;
    }

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }
}
```

### Mapping configuration

```csharp
//Mapping
var config = new AutoMapper.MapperConfiguration(cfg =>
{
    cfg.CreateMap<PostDTO, Post>()
        .ForMember(dest => dest.Keywords, opt => opt.MapFrom(src => "No Keywords Specified"))
        .ForMember(dest => dest.Content, opt => opt.MapFrom((src, dest) =>
        {
            return src.Content;
        }))
        ;

    cfg.CreateMap<PostWithKeywordsDTO, Post>()
        .ForMember(dest => dest.Keywords, opt => opt.MapFrom(src => src.Keywords))
        .ForMember(dest => dest.Content, opt => opt.MapFrom((src, dest) =>
        {
            return src.Content;
        }))
        ;
});
```

### Expected behavior

When mapping to a proxy class of the Post POCO (generated by EF either as a result of a DbSet<Post>.Create() command or by fetching an existing Post record from the database), if you first map from PostDTO -> Post, and then later from PostWithKeywordsDTO -> Post, the 'Keywords' property would be expected to be populated with the corresponding 'Keywords' value from the mapping (should be 'No Keywords Specified' in the case of a PostDTO, and the corresponding 'Keywords' value in the case of a PostWithKeywordsDTO source).

### Actual behavior

Instead, both the PostDTO -> Post and PostWithKeywordsDTO -> Post mappings result in the 'Keywords' field being populated with 'No Keywords Specified'.  By adding breakpoints to the 'Content' value resolvers in each mapping, you can observe that the PostDTO -> Post mapping is being used in both cases and the PostWithKeywordsDTO -> Post mapping is ignored.  

When doing the mapping in the opposite order (PostWithKeywordsDTO -> Post first, then PostDTO -> Post second), the results are as expected and the correct corresponding mappings are used.  This seems to suggest some kind of type map cache issue.

### Steps to reproduce

```csharp
var postDTO = new PostDTO
{
    PostDate = DateTime.Parse("1/1/2000"),
    Content = "Post #1"
};
var postWithKeywordsDTO = new PostWithKeywordsDTO
{
    PostDate = DateTime.Parse("6/30/2005"),
    Content = "Post #2",
    Keywords = "C#, Automapper, Proxy"
};

//PostDTO -> Post
mapper.Map(postDTO, dbContext.Posts.Create());//.Dump();
//Results in Post proxy object w/ 'No Keywords Specified' value in the 'Keywords' property

//PostWithKeywordsDTO -> Post
mapper.Map(postWithKeywordsDTO, dbContext.Posts.Create());//.Dump();
//Results in Post proxy object w/ 'No Keywords Specified' value in the 'Keywords' property instead of 'C#, Automapper, Proxy'
```
See full gist [here](https://gist.github.com/bhavens17/c2021893d0b87cd1cf9ddddc9538ad57)

**Comment by lbargaoanu** [comment]
I already answered on SO.
