### ISSUE TITLE
How to inject a service into a type converter (ASP .NET Core)?

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#3397]
This is probably a documentation question. There is an example here https://docs.automapper.org/en/stable/Dependency-injection.html?highlight=dependency%20injection , but it uses type Container, not present in ASP .NET Core (probably Ninject code mentioned before in the article). How to do that in ASP .NET Core?

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Dependency-injection.html#asp-net-core

**Comment by mc0re** [comment]
That link has no example of a type or value converter using an injected service in its constructor.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
