### ISSUE TITLE
Projects are not working for some reason

### ISSUE THREAD

**Issue by granthoff1107** [AutoMapper/AutoMapper#3398]
I just Upgraded to .Net-Core 3.1, I'm using the latest Automapper.   My Projections are not working at all (sql and in memory).   This is my testing project and I'm connecting to a local MDF as a DB

I'm trying to make a framework to abstract my Entity Layers,  However for this to work I need automapper projects to work so I can Query my DTO's instead of Querying the Entities

    [TestMethod]
    public async Task Verify_Mapping_Projection_Behavior()
    {
        var projectionModifier = "Alabastar";
        var services = this.GetRegisteredRestEzServiceCollection();
        var serviceProvider = services.BuildServiceProvider();
        var context = (AstootContext)serviceProvider.GetService<DbContext>();

        var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<User, UserDTO>().ForMember(x => x.FirstName, 
                o => o.MapFrom((entity, dto) => entity.FirstName + projectionModifier));
        });

        var mapper = config.CreateMapper();

        // Hack: we'll verify exeuction happens in sql
        // using the behavioral differene between in memory and sql (case insensitivity)
        var sqlOnlyModifier = projectionModifier.ToUpper();
        var userDTO = mapper.ProjectTo<UserDTO>(context.Users)
            .Where(x => x.FirstName.Contains(sqlOnlyModifier))
            .FirstOrDefault();

        Assert.IsNotNull(userDTO);
    }

My test failed, so I decided to materialize the projection directly. When I materialize I can see that my  `projectionModifier` is not being added to the firstName property.

How can I get the project to map my modifier, so that I can use my DTO's as Sql Queryables?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by granthoff1107** [comment]
I didn't know you were part of the Automapper team, Thanks for the help on Stackoverflow
