### ISSUE TITLE
ProjectTo returns null under Xunit execution

### ISSUE THREAD

**Issue by achobanov** [AutoMapper/AutoMapper#3399]
The mapping only fails with `ProjectTo` and only during test execution. In [this post](https://stackoverflow.com/questions/54097208/automapper-projectto-does-not-work-when-called-in-unit-tests) I read people have "solved" their problem by not using it. Obviously this is not ideal when working with `IQueryable`.

### Mapping configuration
```csharp
var configurationProvider = new MapperConfiguration(cfg =>
{
    cfg.AddProfile<ApplicationMappingProfile>();
});
```
`ApplicationMappingProfile` uses reflection to create maps from all types that implement `IMapCreator` interface. The loaded assembly is correct, since standard `object` and `IEnumerable` maps are working in the context of tests.

### Version: 9.0.0
EF Core: 3.1.1

### Expected behavior
I expect `ProjectTo` to transform my collection to `TDestination`. 

### Actual behavior
Consuming the queryable after `ProjectTo` call returns null or empty collection.

### Steps to reproduce
The easiest way would be to start the project, since it's not private. I have created a [snapshot branch](https://github.com/achobanov/web-application/tree/automapper-issue-snapshot) which I will not modify. Start `GetArticleDetailsTests.HandleReturnsCorrectArticleDetails` to run the prepared demo. You can inspect the query results in `GetArticleDetailsHandler`. 

To clarify on my AutoMapper setup - I have isolated AutoMapper calls behind `MappingApi` extension class, which is provided with `IMapper` instance via `MappingApi.Configure`. This method is called in my `BaseTests` class for tests and `WebInitialization` for the actual server.

**Comment by lbargaoanu** [comment]
You'll have to isolate _a lot_ more. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
