### ISSUE TITLE
Conditional CreateMap

### ISSUE THREAD

**Issue by dlopezb93** [AutoMapper/AutoMapper#3402]
### Feature description

Let's suppose that we have to make an object mapping, this mapping has to be made based on a property of the source entity: type, for example. When the mapping is done through _mapper.Map<DestObj>(SrcObj) the condition should be evaluated and the mapping that fulfills this condition should be applied. In this way, the condition mapping of objects is facilitated.

This we can achive applying strategy pattern

### Possible syntax

When we are going to define the profiles:

```csharp
this.CreateMap<SrcObj, DestObj>(src => src.Type == EnumType.Type1);
this.CreateMap<SrcObj, DestObj>(src => src.Type == EnumType.Type1);
```

When the Mapper.Map<DestObj>(srcObj) method is going to be executed it will check if there are mapping conditions available and will choose the one that fulfills that expression

### Implementation

I think the most appropriate way to implement it is to apply a strategic pattern.

 modifying the Profile.CreateMap method and the 'MappingExpression' class to allow adding an evaluation function:

```csharp
Func<SrcObj, bool>
```

Multiple mappers are recorded that are the same but with different conditions will be added to a list of function expressions for when the IMapper method is executed.Map retrieve this list of functions and execute it: 

```csharp
var profile = conditions.FirstOrDefault(p => p.Invoke(srcObj))
```

This is my opinion, I would like to know what you think about this functionality and the proposed implementation.

**Comment by lbargaoanu** [comment]
This doesn't really fit. Maps depend only on the types, so they can be cached. But there's nothing stopping you from implementing that yourself, outside AM.
