### ISSUE TITLE
AutoMapperMappingException when mapping EF Core lazy loaded proxy objects

### ISSUE THREAD

**Issue by ngruson** [AutoMapper/AutoMapper#3404]
Hi,

I'm using AutoMapper, Mediatr and EF Core in an .NET Core 3.1 API project.
For my EF Core DbContext, I configured lazy loading in Startup.cs:
```csharp
services.AddDbContext<IMyDbContext, MyDbContext>(options =>
options
  .UseLazyLoadingProxies()
  .UseSqlServer(Configuration.GetConnectionString("MyConnStr")));
```
In a Mediatr command handler, I retrieve an entity from the db, alter it, save it to the db and map it to a DTO.
```csharp
await context.SaveChangesAsync(cancellationToken);
return mapper.Map<MyDto>(entity);
```
I'm getting a mapping error (AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping) because the entity variable contains a proxy object in the form of an Castle.Proxies.MyEntityProxy object instead of a MyEntity object that I have a map for.
I don't use projections here because I need to the entity object in order to change it.

How should I handle this optimally?
I don't think I can add a map for the proxy object as it's created in runtime.
I could retrieve the data again from the db, but that would mean an extra roundtrip.

Tia,
Nils

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
