### ISSUE TITLE
AutoMapperMappingException Serialization Failure

### ISSUE THREAD

**Issue by robertbeuligmann** [AutoMapper/AutoMapper#3406]
[AutoMapperMappingException](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/AutoMapperMappingException.cs) will fail to serialize (tested using Newtonsoft.Json) when AutoMapperMappingException.TypeMap is populated. 

Microsoft's [C# Programing Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions#defining-exception-classes) States:
> New exception classes should be serializable

Potential fixes:
1. Make TypeMap a private class variable. 
2. Use .Net [[NonSerialized()]](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netcore-3.1) Attribute

### Reproduction Gist 
https://gist.github.com/robertbeuligmann/a92357df9e289abeafaf9d07fd1066c9

### Source/destination types

```csharp
    class FromDto
    {
        public string Prop { get; set; } = "something";
        public InnerFromDto Inner { get; set; } = new InnerFromDto();
    }

    class ToDto
    {
        public string Prop { get; set; } = string.Empty;
        public InnerToDto Inner { get; set; }
    }

    class InnerFromDto
    {
        public string Prop { get; set; } = string.Empty;
    }

    class InnerToDto
    {
        public string Prop { get; set; } = string.Empty;
    }
```

### Mapping configuration

```csharp
            var config = new MapperConfiguration(c =>
            {
                c.CreateMap<FromDto, ToDto>();
            });
            var mapper = config.CreateMapper();
```

### Version: 
.Net Core 3.1 
AutoMapper 9.0.0
Newtonsoft.Json 12.0.3

### Expected behavior

Exception should serialize without throwing exception.

### Actual behavior
```
Newtonsoft.Json.JsonSerializationException
Message=Self referencing loop detected for property 'Module' with type 'System.Reflection.RuntimeModule'.
Path 'TypeMap.MapExpression.Body.Expressions[0].IfFalse.Expressions[0].Right.Right.Constructor.Module.Assembly.EntryPoint'.
```
### Steps to reproduce

```csharp
            try
            {
                var dest = mapper.Map<ToDto>(from);
                Console.Out.WriteLine(dest.Prop);
            }
            catch (Exception ex)
            {
                var json = JsonConvert.SerializeObject(ex);
                Console.Error.WriteLine(json);
            }
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
That guideline is out-of-date, the `SerializableAttribute` is only used in the `BinaryFormatter`. If you want to serialize the exception, then you need to provide a hook in your serializer to do it. It is not the responsibility of library developers to support arbitrary serialization.

A background - `BinaryFormatter` was necessary for AppDomain communication, to serialize types across AppDomains. We don't do that any more, so you just need to provide your own serialization mechanism.

If a serializer decides to honor `SerializerAttribute`, fine, but the .NET team has made it pretty clear they're not trying to support generic serialization responsibilities (aka, `ISerializable` interface) as part of the standard. This attribute is around for back compat reasons.

**Comment by lbargaoanu** [comment]
And that guideline has nothing to do with Newtsonsoft.Json.
