### ISSUE TITLE
DuplicateTypeMapConfigurationException due to MapperConfigurationExpression.AddMap(IEnumerable<Type>)

### ISSUE THREAD

**Issue by gcsizmadia** [AutoMapper/AutoMapper#3407]
I have multiple assemblies and each has multiple types derived from `AutoMapper.Profile` so that mappings are nicely organized.

When creating the `MapperConfiguration` I used the `AddMaps(IEnumerable<Type>)` overload and passed all those derived types that are available in the current `AppDomain`.

Then calling `AssertConfigurationIsValid()` throws `DuplicateTypeMapConfigurationException`.

### Mapping configuration

```csharp
public class DependencyModule : Module
{
    protected override void Load(ContainerBuilder builder)
    {
        // Here we collect all types that are
        // - derived from AutoMapper.Profile and
        // - loaded into the current AppDomain.
        IEnumerable<Type> profileTypes = GetAutoMapperProfileTypes();

        var mapperConfiguration =
            new MapperConfiguration(
                config =>
                {
                    config.AllowNullCollections = true;
                    config.AddMaps(profileTypes);
                }
            );

        // This throws DuplicateTypeMapConfigurationException.
        mapperConfiguration.AssertConfigurationIsValid();

        IMapper mapper = mapperConfiguration.CreateMapper();

        builder.RegisterInstance(mapper);
    }
}
```

### Expected behavior

The expected behavior is `DuplicateTypeMapConfigurationException` not to be thrown.

### Actual behavior

`DuplicateTypeMapConfigurationException` was thrown and based on the exception message it seemed that the same assembly is loaded exactly `n` times where `n` is the number of types derived from `AutoMapper.Profile` in that specific assembly.

If skipping `mapperConfiguration.AssertConfigurationIsValid();` then no `Exception` is thrown.

### Steps to reproduce

```csharp
    private IEnumerable<Type> GetAutoMapperProfileTypes()
    {
        return new Type[]
        {
            typeof(CustomProfile1),
            typeof(CustomProfile2)
        };
    }
    
    public class Entity1 { }
    
    public class Entity2 { }
    
    public class Model1 { }
    
    public class Model2 { }
    
    public class CustomProfile1 : AutoMapper.Profile
    {
        public CustomProfile1()
        {
            CreateMap<Entity1, Model1>();
        }
    }
    
    public class CustomProfile2 : AutoMapper.Profile
    {
        public CustomProfile2()
        {
            CreateMap<Entity2, Model2>();
        }
    }

```

### Suggested change

Change `MapperConfigurationExpression.cs` as below:

In `AddMaps(IEnumerable<Type>)` method call `.Distinct()` after calling `.Select()`.

Similarly in `AddMapsCore(IEnumerable<Assembly>)` method call `.Distinct()` in between `.Where()` and `.SelectMany()`.

### Remarks

As for `AddMaps(IEnumerable<Type>)` I might misused/misunderstood it but it might not be 100% obvious that to you should pass *only one type per assembly*. Otherwise, you risk `DuplicateTypeMapConfigurationException` to be thrown.

Adding the above suggested `.Distinct()` calls help avoid `DuplicateTypeMapConfigurationException` that I think is worth thinking about.

If you like this idea then I would happily make this minor change.

**Comment by jbogard** [comment]
Why are you adding the same assembly multiple times? It seems that you can call `Distinct` on your side before calling into AutoMapper.

I don't like our code making those sorts of assumptions.

**Comment by gcsizmadia** [comment]
I don't add the same assembly multiple times. 

I add different types derived from `AutoMapper.Profile` that are in the same assembly hence your `AddMaps(IEnumerable<Type>)` overload selects the same assembly multiple times in the 74th line:
`.Select(t => t.GetTypeInfo().Assembly)`

**Comment by jbogard** [comment]
Oh, don't do that. Those types you pass in are types to match assemblies.

@lbargaoanu I wonder if this is more confusing than helpful, should we only have methods that accept Assembly objects? It'll just force you to do `typeof(MyProfile).Assembly`.

**Comment by lbargaoanu** [comment]
A lot of things can be confusing :) I vote to keep them. I'm sure I've seen this in some other library and I would guess it's pretty useful.

**Comment by lbargaoanu** [comment]
The name of the parameter seems well chosen to me. But I guess we could rename it if there's a better idea.

**Comment by jbogard** [comment]
"MarkerTypesForAssembliesButOnlyOneMarkerTypePerAssemblyPlease"

**Comment by gcsizmadia** [comment]
I suspected I misunderstood the purpose of that method. :)

As for me I now use the `AddMaps(IEnumerable<Assembly>)` overload and it works well.

Regarding the subject I'd suggest
- either extending the XML comment for that method to make it clear(er) - should pass only one type per assembly!
- or adding that `.Distinct()` call as a guard

The parameter name could remain as it is now.

**Comment by lbargaoanu** [comment]
About the docs, a PR is welcome.
