### ISSUE TITLE
ProjectTo constructor mapping

### ISSUE THREAD

**Issue by prochnowc** [AutoMapper/AutoMapper#3410]
This issue is probably related to #3110 .
But i dont get the reason, if i write the Select-Projection by hand everything is fine.

### Source/destination types

```csharp
    public class A
    {
        public int Id { get; set; }

        public B B { get; set; }
    }

    public class B
    {
        public int I { get; }
    }

    public class DtoA
    {
        public DtoB B { get; }

        public DtoA(DtoB b)
        {
            B = b;
        }
    }

    public class DtoB
    {
        public int I { get; }

        public DtoB(int i)
        {
            I = i;
        }
    }
```

### Mapping configuration

```csharp
c.CreateMap<A, DtoA>();
c.CreateMap<B, DtoB>();
```

### Version

Automapper: 9.0.0 
EFCore: 3.1.3

### Expected behavior

```csharp
await context.Set<A>().AsNoTracking().ProjectTo<DtoA>(Mapper.ConfigurationProvider).FirstAsync();
```
 should have the same result as
```csharp
var a = mapper.Map<DtoA>(a);
```

### Actual behavior

`ProjectTo()` is throwing the following exception, while `mapper.Map` is working as expected:

```
System.ArgumentException : Expression of type 'B' cannot be used for constructor parameter of type 'DtoB' (Parameter 'arguments[0]')
```

Gist to reproduce:

https://gist.github.com/prochnowc/901b53f5fb2b9549d4f152d7b54e2c67

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by prochnowc** [comment]
@lbargaoanu Updated the issue description and added link to a gist.

**Comment by lbargaoanu** [comment]
That doesn't work because EF6 doesn't support that. So, until further notice, you can either use `Map` or don't use property mapping instead.

**Comment by prochnowc** [comment]
@lbargaoanu I'm using EF Core in this test.
Also, if EF core doenst support it, why does the handwritten projection using Select work ?
Or do you mean AutoMapper implements projections in a way which EF core doesnt support ? 
Thanks for your help.

**Comment by lbargaoanu** [comment]
But I see you tested with the InMemory provider. Does that really work with a real database?

**Comment by prochnowc** [comment]
Yes, this also works with SqlServer provider. I can update the Gist if you want.

**Comment by prochnowc** [comment]
Thanks for improving the usability of constructor mapping. I prefer initializing my domain objects via ctor - it's easier to ensure the object is in a valid state.
