### ISSUE TITLE
IgnoreAllPropertiesWithAnInaccessibleSetter interferes with ForCtorParam

### ISSUE THREAD

**Issue by mronnblom-cint** [AutoMapper/AutoMapper#3412]
### Expected behavior

Maybe I have misunderstood the intention of `IgnoreAllPropertiesWithAnInaccessibleSetter`, but my interpretation of it is to safeguard against AutoMapper constructing the destination object using the default constructor and then mapping to a private/protected setter. This is especially important to ensure encapsulation and valid invariants, i.e. that all validation in the destination object's constructor are run. So I would like to set `IgnoreAllPropertiesWithAnInaccessibleSetter` globally to ensure this never happens, but still be able to map to constructor parameters by name with `ForCtorParam`.

### Actual behavior

Exception is thrown, with message `Destination needs to have a constructor with 0 args or only optional args`.

### Steps to reproduce

You can reproduce this with the existing unit test below. Just add `IgnoreAllPropertiesWithAnInaccessibleSetter` to it's config.

```csharp
    public class When_renaming_class_constructor_parameter : AutoMapperSpecBase
    {
        Destination _destination;

        public class Source
        {
            public InnerSource InnerSource { get; set; }
        }

        public class InnerSource
        {
            public string Name { get; set; }
        }

        public class Destination
        {
            public Destination(InnerDestination inner)
            {
                InnerDestination = inner;
            }

            public InnerDestination InnerDestination { get; }
        }

        public class InnerDestination
        {
            public string Name { get; set; }
        }

        protected override MapperConfiguration Configuration => new MapperConfiguration(c =>
        {
            // Line below added
            c.ForAllMaps((tm, me) => me.IgnoreAllPropertiesWithAnInaccessibleSetter());

            c.CreateMap<Source, Destination>().ForCtorParam("inner", o => o.MapFrom(s => s.InnerSource));
            c.CreateMap<InnerSource, InnerDestination>();
        });

        protected override void Because_of()
        {
            _destination = Mapper.Map<Destination>(new Source { InnerSource = new InnerSource { Name = "Core" } });
        }

        [Fact]
        public void Should_map_ok()
        {
            _destination.InnerDestination.Name.ShouldBe("Core");
        }
    }
```

**Comment by lbargaoanu** [comment]
If you don't want to use default constructors, don't have default constructors.

**Comment by mronnblom-cint** [comment]
> If you don't want to use default constructors, don't have default constructors.

I don't. But I was under the impression that AutoMapper can magically construct "empty" objects even when there is no default constructor? But if not, then it should be safe to assume that my single non-default constructor is always run, and no mappings occur to the properties of the class even when not setting `IgnoreAllPropertiesWithAnInaccessibleSetter`? What is the point then of having `IgnoreAllPropertiesWithAnInaccessibleSetter`? Is that some other use case?

**Comment by lbargaoanu** [comment]
No, AM doesn't do such thing :) I have no insight on `IgnoreAllPropertiesWithAnInaccessibleSetter`. Perhaps find the initial PR.

**Comment by mronnblom-cint** [comment]
Ok! Thanks for the quick reply! :)
