### ISSUE TITLE
Argument types do not match not enough information

### ISSUE THREAD

**Issue by pantonis** [AutoMapper/AutoMapper#3414]
I am using AutoMapper 9 with .net core 3.1
When I use ProjectTo<Destin>(mapper.ConfigurationProvider) in an EF Core 3.1 query I get 

```Argument types do not match ```

I checked the exception message and the stacktrace but they don't give much information just the above message. I have a model with over 25 properties. How can I find what is the actual field that is causing the issue. The exception itself is not giving much apart from a generic error.

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by lbargaoanu** [comment]
If the stack trace is inside EF Core, there's nothing else to do.

**Comment by pantonis** [comment]
@lbargaoanu This execution plan does not work. It still throws the same exception
```
Expression expres = genericRepository.GetAll().ProjectTo<Destination>(mapper.ConfigurationProvider).Expression;
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by pantonis** [comment]
I get 
```
Install-Package : NU1102: Unable to find package AutoMapper with version (>= 9.1.0-ci-01641)
  - Found 214 version(s) in api.nuget.org [ Nearest version: 9.0.0 ]
  - Found 0 version(s) in Local Nuget
At line:1 char:1
+ Install-Package AutoMapper -Source https://www.myget.org/F/automapper ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

It is impossible to make a gist. My project is huge and the projection I am trying to make contains dozens of navigation models.

**Comment by pantonis** [comment]
Still getting the same error no further information.

**Comment by lbargaoanu** [comment]
Of course it's possible, it just might take a while. If you want people to guess, you can try SO. When you have a repro, let us know.

**Comment by pantonis** [comment]
The error is coming from EF Core or from Automapper?

**Comment by jbogard** [comment]
You'll have to debug this, unfortunately. That's an error with the expression generation, but you'd need the debugger to understand exactly what expression is causing this error.

**Comment by pantonis** [comment]
@lbargaoanu I just started migrating from mapper.Map to ProjectTo. I will try to convert my project to use ProjectTo. This is the first case I tried and I got this error. Imagine if I get this error every time. I have to open a ticket every time.  That does not work man sorry.

**Comment by pantonis** [comment]
@jbogard Can you give more info please on how I am going to debug it? Thanks

**Comment by lbargaoanu** [comment]
No, you don't get that every time. Most likely it happens _because_ it wasn't written for `ProjectTo`. Research how Source Link works.

**Comment by pantonis** [comment]
what is wasn't written for ProjectTo?
