### ISSUE TITLE
One unusual mapping case

### ISSUE THREAD

**Issue by iamhere2** [AutoMapper/AutoMapper#3416]
Hi, all!

Would you mind helping me to solve this quiz:

### Source/destination types

```csharp
        public class SourceA
        {
            public int EntityId { get; set; }
            public int Id { get; set; }
            public int Other { get; set; }
        }

        public class DestinationA
        {
            public int Id { get; set; }
            public int Other { get; set; }
        }

        public class SourceB { ... }
        public class DestinationB { ... }
        ...
        public class SourceZ { ... }
        public class DestinationZ { ... }
```
I have a dozen of Source and Destination classes, which follow the same property naming scheme: each Source has `Id` and `EntityId`, and each Destination has just `Id`.
All other properties (a lot) are named equally in Sources and Destinations.

The task is to completely omit `Id` value from `Source`, but use instead a value from `EntityId`! And, of course, all Other properties should be mapped as usual.

I've been trying to configure AutoMapper Profile using out-of-box Conventions, custom `ISourceToDestinationNameMapper`, and so on, but neither of my approaches were success. 

Is there any way to ask AutoMapper to use some `SpecialEntityIdNameMapper` about that unusual `EntityId -> Id` mapping, which would have the highest priority among the all default mappers/conventions?

### Expected behavior

Custom convention tells AutoMapper how to map `EntityId` into `Id`, and all other properties are mapped using default conventions.

### Actual behavior

All my attempts to write such convention (`ISourceToDestinationNameMapper`) ended with the same result: AutoMapper uses only its default conventions (`Id -> Id`), and my mapper event don't receive control.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
