### ISSUE TITLE
AfterProjectionFrom<TSource>() extension method idea

### ISSUE THREAD

**Issue by snappyfoo** [AutoMapper/AutoMapper#3419]
I know discussion around AfterMap and ProjectTo has come up a few times, and I think I understand most of the reasons why it's not possible, but I have an idea and I was wondering if you think it makes sense, if it's workable or something you would consider. I will walk through the specific angle I coming from.

Problem:
I have created a map between from TSource to TDestination. This mapping profile is used in a few places, both in memory with IMapper.Map and in SQL with the ProjectTo extension.

One member on TDestination is ignored as I want to populate it with a service after the mapping. I can use AfterMap and an IMappingAction to achieve this, but that won't work for ProjectTo. As a workaround, I can simply take the final TDestination or `List<TDestination>` after it's been materialised by EF and set the extra member(s) manually.

However, I want to centralise the action performed after mapping in the map configuration/IMappingAction. However, I don't think there is a way to easily plug into that at the moment. How it might be used:

```
dbContext
    .Products
    .ProjectTo<ProductDto>
    .ToList()
    .AfterProjectionFrom<Product>()
```

An AfterProjectionFrom extension would need to take the source type as that would be lost by the time we ToList(). The source type would allow it to look up the correct mapping configuration for the destination (which may be configured to be mapped from multiple source types). It would return the same type as it takes, e.g. in this case `List<ProductDto>()`

This could only support AfterMaps that only use the destination, as the source may never have been materialised in memory in such a query. Therefore a new mapping configuration method would be needed, e.g. AfterMapOrProjection, a more limited version of AfterMap which is compatible with both but which only lets you work against the destination object. Supporting that you'd need a new interface for implementing those actions where dependency injection is needed, e.g. IMappingOrProjectionAction, where again, the Process method doesn't have the source object as an argument.

It's still an extra step you have to take after using ProjectTo, but you don't need to know the specifics of the action at that point, just that you need to hook into AutoMapper again and let it handle it. This is particularly useful where you have a common generic method that lots of areas of your app use, and your query code actually looks more like:

```
dbContext
    .Set<TSource>
    .ProjectTo<TDestination>
    .ToList();
```

So being able to tag on an extra `AfterProjectionFrom<TSource>()` extension method in the shared generic query code means lots of areas that use it would no longer need to take those extra steps themselves. It centralises the actions taken in the mapping configuration, which are also performed when mapping is done in memory too.

**Comment by lbargaoanu** [comment]
You can write your own `ProjectTo` that calls AM and _then_ does what you need.

**Comment by snappyfoo** [comment]
> You can write your own `ProjectTo` that calls AM and _then_ does what you need.

That’s not what I suggested though. Am I right in assuming AutoMapper is dead? No new features?
