### ISSUE TITLE
Ignore only the last property in ForPath

### ISSUE THREAD

**Issue by tomasfabian** [AutoMapper/AutoMapper#3421]
Ignore only the last property in ForPath

```C#
  public class Book
  {
    public string Title { get; set; }    
    public Publisher Publisher { get; set; }
  }

  public class Publisher
  {
    public Publisher()
    {
      Books = new List<Book>();
    }

    public string Name { get; set; }    
    public List<Book> Books { get; set; }
  }

  public class BookProfile : Profile
  {
    public BookProfile()
    {
      CreateMap<Book, BookDto>()
        .ForPath(c => c.Publisher.Books, c => c.Ignore());
    }
  }
```

In this use case `bookDto.Publisher` should be mapped and only the `bookDto.Publisher.Books` property should be ignored. 
Related issue:
https://github.com/AutoMapper/AutoMapper/issues/2199

EF 6.4 complains without this mapping:
```C#
    public IQueryable<BookDto> GetAll()
    {
      return booksRepository.GetAll().ProjectTo<BookDto>(mapper.ConfigurationProvider);
    }
```

_The type 'Sample.Domain.DTO.BookDto' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order._

**Proposal:**
```C#
      CreateMap<Book, BookDto>()
        .ForPath(c => c.Publisher.Books, c => c.IgnoreLast());
```

Thank you, Tomas

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Queryable-Extensions.html#supported-mapping-options

**Comment by tomasfabian** [comment]
EF 6.4 Queryable was just an example. This feature request is valuable also for object mappings.

**Comment by lbargaoanu** [comment]
That's the intended behavior. If you're not happy with it, just avoid `ForPath`. You can always create the inner map.
