### ISSUE TITLE
Map To Immutable Object With Differently Named Constructor Args

### ISSUE THREAD

**Issue by danadesrosiers** [AutoMapper/AutoMapper#3423]
Currently, when mapping objects using a constructor, the constructor arguments must match the source property name.  I have found this unintuitive.  Intuitively, I would expect that AutoMapper would look at the source object and my configurations and find an appropriate constructor without having to do any additional configuration.

### Source/destination types

```csharp
class Source
{
    public Source(int one, string two)
    {
        One = one;
        Two = two;
    }

    public int One { get; private set; }
    public string Two { get; private set; }
}

class Destination
{
    public Destination(int one, string two2)
    {
        One = one;
        Two2 = two2;
    }

    public int One { get; private set; }
    public string Two2 { get; private set; }
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>()
      .ForMember(dest => dest.Two2, opt => opt.MapFrom(src => src.Two))
```

### Expected behavior

`Destination` object is created using the available `Destination` constructor.

### Actual behavior

I have to either:
1. Create a default constructor (or constructor with all optional args).
2. Change the name of `two2` in the Destination constructor to `two` so it matches `Source.Two`.  Or create another constructor just for AutoMapper.
3. Add `ForCtorParam()` call in my configuration.

I would rather not have to do any of these.  It seems like AutoMapper should be able to figure it out without this.  Maybe it's not as straight forward as it seems, but if it can be done, I think it would go a long way to improve usability and be more intuitive for those of us who like to use immutable types.

### Steps to reproduce

```csharp
mapper.Map<Destination>(new Source(1, "two"));
```

**Comment by lbargaoanu** [comment]
If you have a private setter, you don't need the constructor anymore. AM will use the setter. Without a setter, you can write an extension method that calls both `ForMember` and `ForCtorParam`.

**Comment by danadesrosiers** [comment]
Thank you for the quick response!

> If you have a private setter, you don't need the constructor anymore.

This is only an option if the object never needs to be instantiated manually.  Also, when using nullable reference types in C# 8.0, you get warnings that non-nullable reference types are not instantiated.  For both of these reasons, this solution doesn't work for me.

> you can write an extension method that calls both ForMember and ForCtorParam.

That sounds like a reasonable work around.  I'm going to move forward with that.  

I still suggest updating the library to make this easier.  I know it would have saved me a lot of time and confusion.

**Comment by jbogard** [comment]
I'm not too concerned with nullable reference types, because you're far more likely to use C# 9.0 record types instead for those. We'll see what we need to do to support those :)
