### ISSUE TITLE
ProjectTo: support null properties in nested mappings

### ISSUE THREAD

**Issue by guidupuy** [AutoMapper/AutoMapper#3426]
### Source/destination types

```csharp
// Sources
public class KeyRelationship{
    public int Id { get; set; }
    public Contact Contact { get; set; }
}

public class Contact{
    public int Id { get; set; }
    public Employee Owner { get; set; }
}

public class Employee{
    public int Id { get; set; }
}

// Destinations
public class KeyRelationshipDTO{
    public int Id { get; set; }
    public ContactDTO Contact { get; set; }
}

public class ContactDTO{
    public int Id { get; set; }
    public int? OwnerId { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Contact, ContactDTO>();
CreateMap<KeyRelationship, KeyRelationshipDTO>();
```

### Version
`AutoMapper.Extensions.Microsoft.DependencyInjection 7.0.0`
`EF Core 2.1`

### Expected behavior

Some `Contact` entities have no `Owner` set on them (`Owner = null`). When doing:
```csharp
db.KeyRelationships.ProjectTo<KeyRelationshipDTO>().ToList()
```
It would be nice for AutoMapper to set the value of `OwnerId` to null on the `ContactDTO` property of the mapped result.

### Actual behavior

I get the following error: `System.InvalidOperationException: Nullable object must have a value`.

This error disappears if I explicitly do a null check in the mapping configuration as follows:
```csharp
CreateMap<Contact, ContactDTO>()
    .ForMember(c => c.OwnerId, opts => opts.MapFrom(c => c.Owner == null ? (int?)null : c.Owner.Id));
```

### Steps to reproduce

```csharp
db.KeyRelationships.ProjectTo<KeyRelationshipDTO>().ToList()
```

**Comment by lbargaoanu** [comment]
Try upgrading to the latest EF.

**Comment by lbargaoanu** [comment]
The null checks are there. So it must be EF. Let us know.

**Comment by guidupuy** [comment]
I’m stuck with 2.1 for now, unfortunately.

Are you sure the null checks extend to nested mappings though?

As far as I’m concerned I only have a couple of nested mappings, so in the
meantime I guess I can add the null checks manually where needed.

**Comment by lbargaoanu** [comment]
As I've said, you can see for yourself.
