### ISSUE TITLE
Clarify ReverseMap docstring

### ISSUE THREAD

**Issue by Sti2nd** [AutoMapper/AutoMapper#3431]
https://github.com/AutoMapper/AutoMapper/blob/51e917a2b2ec2bf44a473cead46cb23bb2dcffe5/src/AutoMapper/IMappingExpression.cs#L19-L23

Because the function is called `ReverseMap` and because of the documentation I initially believed this function simply reversed the map I created with `CreateMap`. It wasn't until I now googled 'automapper two-way map' that I read a StackOverflow post that stated ReverseMap can be used to create a two-way mapping.

I suggest updating the docstring to mention two-way mapping or that the reverse map is in addition. E.g.:

> Create **an additional** type mapping from the destination to the source type, using the destination members as validation.

Or

> Create a type mapping from the destination to the source type, using the destination members as validation. **This allows for two-way mapping.**

**Comment by lbargaoanu** [comment]
> I initially believed this function simply reversed the map I created with CreateMap
That's what it does, that's what the docs say and I'm not sure what you mean :)

**Comment by lbargaoanu** [comment]
Anyway, we'll take a PR with docs improvement if it's helpful. But I don't see it here.

**Comment by Sti2nd** [comment]
> That's what it does, that's what the docs say and I'm not sure what you mean :)

I'll try to explain. As far as I understand from the following sources [ [1], [2], [3] ], AutoMapper supports bidirectional mapping by using ReverseMap. If ReverseMap simply reversed the mapper I created with `CreateMap`, I wouldn't end up with a bidirectional mapping.

If I have the code: 
```csharp
Mapper.CreateMap<Src, Dest>()
    .ReverseMap();
```
I first expected it to be equal to the code (note the reversed mapping):
```csharp
Mapper.CreateMap<Dest, Src>();
```
But it seems that it is equal to the following code:
```csharp
Mapper.CreateMap<Dest, Src>();
Mapper.CreateMap<Src, Dest>();
```
So as an end user, it seems ReverseMap isn't just specifying the map I created, it creates a new map the opposite way, leaving me with two way mapping.

I didn't understand that simply based on the docstring and method name; I can create a PR if you agree that it might clear out some confusion.

[1]: https://stackoverflow.com/questions/13490456/automapper-bidirectional-mapping-with-reversemap-and-formember
[2]: https://dotnettutorials.net/lesson/reverse-mapping-using-automapper/
[3]: https://stackoverflow.com/a/28238077

**Comment by lbargaoanu** [comment]
Oh, I see. I think it's just a misunderstanding, but I'll use the second version in a PR I have open.

**Comment by Sti2nd** [comment]
Nice! 
Instead of adding "This allows for two-way mapping" it would be even better to write "This creates a two-way mapping", because that leaves no doubt. In the latter I assume that ReverseMap is always used to create a bidirectional mapping and I don't know if it always does that, so you must decide which is correct!
