### ISSUE TITLE
ProjectTo does not work with enum types

### ISSUE THREAD

**Issue by subseqenz** [AutoMapper/AutoMapper#3433]
### Source/destination types

```csharp

public class AbortReason : ExtendableDto
{
        public AbortReasonValue Reason { get; set; }
}

public class AbortReasonDto : ExtendableDto
{
        [JsonProperty(PropertyName = "value")]
        [JsonConverter(typeof(StringEnumConverter))]
        public AbortReasonValueDto Reason { get; set; }
}

public enum AbortReasonValueDto
{
        [EnumMember(Value = "none")]
        None = 0,

        [EnumMember(Value = "otherReason")]
        OtherReason = 1,

        [EnumMember(Value = "abortedByApplicant")]
        AbortedByApplicant = 2,

        [EnumMember(Value = "applicantAbandoned")]
        ApplicantAbandoned = 3
}

public enum AbortReasonValue
{
        None = 0,
        OtherReason = 1,
        AbortedByApplicant = 2,
        ApplicantAbandoned = 3
 }
```

### Mapping configuration

```csharp
CreateMap<AbortReasonValueDto, AbortReasonValue>();
CreateMap<AbortReasonValue, AbortReasonValueDto>();

CreateMap<AbortReasonDto, AbortReason>();
CreateMap<AbortReason, AbortReasonDto>();
```

### Expected behavior

Mapping enums should work properly when using QueryableExtension's ProjectTo<>().

### Actual behavior

**Whenever** `ConstantExpression.Constant(object value, Type type)` is called for enum types with `null` as first parameter, a ArgumentException ("Argument types do not match.") is thrown as `null` can't be interpreted as an actual enum value. For expample, this code is broken:
```csharp
private static MemberAssignment BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary<ExpressionRequest, int> typePairCount, LetPropertyMaps letPropertyMaps)
{
    var transformedExpression = configuration.ExpressionBuilder.CreateMapExpression(request, result.ResolutionExpression, typePairCount, letPropertyMaps);
    if (transformedExpression == null)
    {
        return null;
    }

     // Handles null source property so it will not create an object with possible non-nullable properties 
    // which would result in an exception.
    if (propertyMap.TypeMap.Profile.AllowNullDestinationValues && !propertyMap.AllowNull && !(result.ResolutionExpression is ParameterExpression) && !result.ResolutionExpression.Type.IsCollectionType())
    {
         // ! the next line throws the ex !
         transformedExpression = result.ResolutionExpression.IfNullElse(Constant(null, transformedExpression.Type), transformedExpression); 
    }

     // ! same here !
    return Bind(propertyMap.DestinationMember, transformedExpression);
}
```
### Steps to reproduce

- Create a unit test
- Try to call `ConstantExpression.Constant(null, typeof(StringSplitOptions));`

**Comment by lbargaoanu** [comment]
Write an EF LINQ query that does what you want.

**Comment by subseqenz** [comment]
How does writing a linq query fix this issue? I still need to do a IQueriable transformation across multiple layers. Also, i run against a CosmosDB.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by subseqenz** [comment]
So i reported a bug that can be reproduced and you tell me to discuss this on stackoverflow ... When there is no bugfixing at all shouldn't this project then be marked as deprecated?

**Comment by erik-neumann** [comment]
Hi @lbargaoanu ,

thanks for promptly closing the issue. But I have 3 additional questions:

1. How is EF related to that issue?
2. Why is reporting a potential bug better suited for StackOverflow than by repo issues?
3. Would additional retro steps help to understand the issue?

**Comment by jbogard** [comment]
When debugging LINQ expressions, you MUST first confirm that the query works WITHOUT AutoMapper involved whatsoever. LINQ query expressions are very complex to work with, and we often find bugs in the LINQ query provider themselves.

To understand if this is AutoMapper's generation of the LINQ expression, or the query providers *interpretation* of the expression, you MUST isolate the expression first against the query provider.

Hence, "write an EF query to do what you want". If that EF query works, it's AutoMapper's bug. If it does not work, it's with the query provider.

**Comment by erik-neumann** [comment]
Ok, thanks for the clarification

**Comment by subseqenz** [comment]
Hi @jbogard,

thanks for your feedback. As i tried to explain: **this bug does not relate to entity framework or to specific automapper logic** but occours when calling `ConstantExpression.Constant(null, typeof(StringSplitOptions));` 

This call simply cannot work on a technical level. It took me some time to debug Automapper to find this specific spot where the ArgumentException is thrown.

I don't use entity framework at all. Also, as i use CosmosDB in a Repository pattern, there would be a different stack trace and a different exception when this would relate to

**Comment by jbogard** [comment]
Before we fix a bug in the LINQ expression creation stuff, we have to confirm that the expression we're targeting is able to be executed in the first place. Part of what we're trying to do is build LINQ expressions that query providers can actually interpret successfully.

For this example, we could fix the bug but it results in an expression not possible to execute, so that's why we're looking for viable LINQ expression that does work. Our main target is EF Core's query provider, also, repository pattern or not.

So if you can, post an example that uses the Cosmos DB query provider with a manual `.Select` projection to validate that Cosmos DB at least can handle the manual projection. We then reverse engineer a successful projection's expression tree into how AutoMapper builds out an expression.

**Comment by subseqenz** [comment]
Hi @jbogard ,

thanks again for having a look on this.

Im not quite sure what you mean by "manual projection". At least the Cosmos DB provider is working as expected, pls see screen:

![image](https://user-images.githubusercontent.com/25926538/83548044-6ff47c80-a503-11ea-861e-72e0a595d026.png)

And i cannot call ProjectTo without the ArgumentException to be thrown ...

Look, lets not overcomplicate things by searching for a hypothetical issue in a provider considered well tested. Lets rather focus on a very real error caused by calling `ConstantExpression.Constant`: 

1#
![image](https://user-images.githubusercontent.com/25926538/83547445-82ba8180-a502-11ea-8953-ebd9a84947c8.png)

2#
![image](https://user-images.githubusercontent.com/25926538/83547539-af6e9900-a502-11ea-9c19-929e5e1c632c.png)

3#
![image](https://user-images.githubusercontent.com/25926538/83547365-6585b300-a502-11ea-95f3-ca1e47f3bae9.png)

**Comment by jbogard** [comment]
> Look, lets not overcomplicate things by searching for a hypothetical issue in a provider considered well tested.

Oh you sweet summer child :) AutoMapper finds TONS of bugs in LINQ query providers. LINQ query providers are very often, if not always, the most complex areas of code for database SDK providers.

A "manual projection" is you calling into the Cosmos DB, removing AutoMapper COMPLETELY from the mix.

Replace your code that calls `ProjectTo` with `Select`. Also, something looks quite wonky, you're calling `await Task.FromResult`, that looks very very odd. Your method there shouldn't return a `Task<IQueryable>`, it should only return `IQueryable` and then your calling code would materialize and await the query with `ToListAsync` etc.

I'm familiar with the repository pattern, I use it with Mongo and Cosmos DB as well. Typically, my repo exposes the provider-specific queryable, and then I do my additional filtering/projection in application code.

So, replace your `ProjectTo` with `Select` and confirm that it works.

**Comment by subseqenz** [comment]
Ok, i did some further investigation on this after updating the OData and CosmosDB packages to the latest versions. Then, i bypassed the service-class, injected the repository directy to the controller and removed all Automapper calls:

![OData Controller Update](https://user-images.githubusercontent.com/25926538/83729932-a556b280-a648-11ea-882d-105472890394.png)

Calling CosmosDB with .Where or .Select works as expected. So i think the query provider is fine, at least for `DocumentClient.CreateDocumentQuery`. Doing the same on the OData-Level by setting up the arguments on the URL only works for `$filter`:

![OData Test Filter](https://user-images.githubusercontent.com/25926538/83728929-39c01580-a647-11ea-920d-d66653f9192c.png)

A `$select` will always result in an exception beeing thrown, as described here: https://github.com/OData/WebApi/issues/2118

However, when i re-activate the .ProjetctTo i would then expect the code to work for the happy case with `$filter`. Instead, i always get the ArgumentException from above, no matter what URL parameter is used.
