### ISSUE TITLE
Cannot auto map ImmutableArray to regular array

### ISSUE THREAD

**Issue by qrjo** [AutoMapper/AutoMapper#3434]
### Source/destination types

```csharp
ImmutableArray<string>
string[]
```

### Expected behavior

`ImmutableArray` should be automatically mapped to a regular array.

### Actual behavior

An exception is thrown: ``System.ArgumentException: Expression of type 'System.Collections.Immutable.ImmutableArray`1[System.String]' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable`1[System.String]' of method 'Int32 Count[String](System.Collections.Generic.IEnumerable`1[System.String])' (Parameter 'arg0')``

### Steps to reproduce

Any mapping from an ImmutableArray property to a regular array property.

Workaround is to add a `ForMember` to the map and call `.ToArray()` on the source property, but I'd rather not have to do this.

**Comment by lbargaoanu** [comment]
AM doesn't consider `ImmutableArray`. You'll have to handle that yourself.

**Comment by qrjo** [comment]
I noticed that. If possible, it should. It's a built-in type of .NET Core 3.1 and will be in .NET 5.
