### ISSUE TITLE
Unable to find package 'AutoMapper.Extensions.EnumMapping'

### ISSUE THREAD

**Issue by yabli** [AutoMapper/AutoMapper#3435]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 

Install-Package AutoMapper.Extensions.EnumMapping
```

### Expected behavior

AutoMapper.Extensions.EnumMapping pkg is installed

### Actual behavior

Install-Package : Unable to find package 'AutoMapper.Extensions.EnumMapping'
At line:1 char:1
+ Install-Package AutoMapper.Extensions.EnumMapping
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/issues/2
