### ISSUE TITLE
Conditionally block reverse map unflattening of a member?

### ISSUE THREAD

**Issue by jez9999** [AutoMapper/AutoMapper#3436]
I want to block the reverse map unflattening of a destination member based on the value of a source member.  I thought I'd be able to do it like this:

```
    class TestEntity {
        public int Id { get; set; }
        public TestSubEntity SubEntity { get; set; }
    }
    class TestSubEntity {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    class TestDto {
        public int Id { get; set; }
        public int SubEntityId { get; set; }
        public string SubEntityName { get; set; }
    }

    public void TestMap() {
        IMapper mapper = new MapperConfiguration(cfg => {
            cfg
                .CreateMap<TestEntity, TestDto>()
                .ReverseMap()
                .ForMember(ent => ent.SubEntity, opt => opt.Condition(dto => false)); // marker
        }).CreateMapper();
        var result = mapper.Map<TestEntity>(new TestDto {
            Id = 123,
            SubEntityId = 987,
            SubEntityName = "I'm a SubEntity!"
        }); // result.SubEntity is non-null; wanted null
    }
```

... but as you can see, `SubEntity` gets mapped to a non-null value even though the condition is false.  Replacing the 'marker' line with the following gets the same result:

```
    .ForMember(ent => ent.SubEntity, opt => opt.PreCondition((Func<TestDto, bool>)(dto => false)));
```

... however replacing it with this does indeed cause `SubEntity` to be null (though allows no condition to be provided):

```
    .ForMember(ent => ent.SubEntity, opt => opt.Ignore());
```

Is there a way I can get it to be null on a certain condition?

**Comment by jalvarezca** [comment]
When this happens to me I had to remove the `.ReverseMap()` option and add another CreateMap() on the other direcction manually, otherwise I will get a new instance of the subentity.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
