### ISSUE TITLE
Inconsistant behaviour when doing await query.OrderBy().ProjectTo<T>().ToListAsync()

### ISSUE THREAD

**Issue by stevenxi** [AutoMapper/AutoMapper#3439]
### Source/destination types

```csharp
 public class TenderCalendarEventEntry //Source
    {
        public int TenderCalendarEventId { get; set; }

        public int TenderId { get; set; }
        public virtual TenderEntry Tender { get; set; }

        public int? TenderCalendarEventTemplateId { get; set; }
        public virtual TenderCalendarEventTemplateEntry TenderCalendarEventTemplate { get; set; }

        public int TenderCalendarEventTypeId { get; set; }
        public virtual TenderCalendarEventTypeEntry TenderCalendarEventType { get; set; }

        public string EventName { get; set; }

        public string Note { get; set; }

        public DateTime InitialInvoke { get; set; }

        public DateTime NextInvoke { get; set; }

        public DateTime? EndDate { get; set; }

        public bool AllowModification { get; set; }

        public bool AllowSnooze { get; set; }

        public bool Dismissed { get; set; }

        public DateTime UpdatedOn { get; set; }

        public int PersonId { get; set; }
        public virtual PersonEntry Person { get; set; }

    }


    public class TenderCalendarEventModel //Destination
    {
        public int TenderCalendarEventId { get; set; }
        public int TenderId { get; set; }
        public string TenderName { get; set; }
        public TenderCalendarEventType CalEventType { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string EventName { get; set; }
        public string Note { get; set; }
        public bool DateRange { get; set; }
        public bool AllowSnooze { get; set; }
        public bool AllowModification { get; set; }
    }

```

### Mapping configuration

```csharp

            CreateMap<TenderCalendarEventEntry, TenderCalendarEventModel>()
                .ForMember(x => x.TenderName, s => s.MapFrom(x => x.Tender.Name))
                .ForMember(d => d.CalEventType, s => s.MapFrom(x => (TenderCalendarEventType) x.TenderCalendarEventTypeId))
                .ForMember(d => d.StartDate, s => s.MapFrom(x => x.NextInvoke))
                .ForMember(d => d.EndDate, s => s.MapFrom(x => x.EndDate))
                .ForMember(d => d.EventName, s => s.MapFrom(x => x.EventName))
                .ForMember(d => d.Note, s => s.MapFrom(x => x.Note))
                .ForMember(d => d.DateRange, s => s.MapFrom(x => x.TenderCalendarEventTemplate.DateRange));

```

### Expected behavior

The exception of **System.InvalidOperationException: The source IQueryable doesn't implement IDbAsyncEnumerable<Nettuno.Service.Interface.Models.Tender.TenderCalendarEventModel>. Only sources that implement IDbAsyncEnumerable can be used for Entity Framework asynchronous operations. For more details see http://go.microsoft.com/fwlink/?LinkId=287068.** been thrown when invokes the .ToListAsync() **sometimes**.

The behaviour should be consistent: either it doesn't support .ToListAsync(), or it supports.

### Actual behavior

There're 2 endpoints in my asp.netcore porject.  When placing the following .ProjectTo<>().ToListAsync() query in both of them, 100% same (as copy/paste). One always works, one throws the InvalidOperationException exception.

I can accept the fact that (if) AutoMapper doesn't support ToListAsync(), but what I don't understand is why exactly same query would give different behaviour.  

### Steps to reproduce

```csharp

var list = await context.TenderEvent.Project.OrderBy(x => x.NextInvoke)
                .ProjectTo<TenderCalendarEventModel>(NettunoMapper.Mapper.ConfigurationProvider)
                .ToListAsync();

```

**Comment by lbargaoanu** [comment]
That's outside AM. AM doesn't implement either interface.

**Comment by stevenxi** [comment]
hi @lbargaoanu,
You probably didn't read the issue before you close it.

As said, if AM doesn't implement "either"(I'm not sure why you said either, there're only one interface) why there's one query works one doesn't. (They're actually same query).

Does AutoMapper suppose to support ProjectTo<>().ToListAsync()?

**Comment by stevenxi** [comment]
hi @lbargaoanu,
You probably didn't read the issue before you close it.

As said, if AM doesn't implement "either"(I'm not sure why you said either, there're only one interface) why there's one query works one doesn't. (They're actually same query).

Does AutoMapper suppose to support ProjectTo<>().ToListAsync()?
