### ISSUE TITLE
Only map changed data?

### ISSUE THREAD

**Issue by VisualMicro** [AutoMapper/AutoMapper#3444]
Hi,

Is it possible to only apply mappigs where data (Member Value) has actually changed?

Sorry if there is an obvious answer. Solutions on stackoverflow appear to only apply to <= v6. 

If possible, a global flag for a map would be great as opposed to having to test every member with some sort of Condition.

Does this make sense?

Thanks for the great work!

**Comment by lbargaoanu** [comment]
There isn't anything built in. You'll have to choose from the things people did before.
