### ISSUE TITLE
Read-only collection properties on the destination type are not automatically ignored

### ISSUE THREAD

**Issue by BrettJaner** [AutoMapper/AutoMapper#3449]
Hey Jimmy and AutoMapper Contributors,

Since non-collection read only properties (properties with getters only) are automatically ignored on the destination type, I was expecting the same behavior to be true for collection properties. However, an exception is thrown when asserting the mapper configuration.  Is this by design or is this a bug?

### Gist w/ Repro

https://gist.github.com/BrettJaner/748c2b99bf0b578847a851852560539b

### Source/destination types

```csharp
class SourceType { }

class DestinationTypeWithGetterOnlyArray
{
    public string[] CalculatedArray => new string[0];
}

class DestinationTypeWithGetterOnly
{
    public string CalculatedProperty => string.Empty;
}
```

### Mapping configuration

```csharp
var config = new AutoMapper.MapperConfiguration(cfg =>
{
    cfg.CreateMap<SourceType, DestinationTypeWithGetterOnly>();
});

//valid
config.AssertConfigurationIsValid();

config = new AutoMapper.MapperConfiguration(cfg =>
{
    cfg.CreateMap<SourceType, DestinationTypeWithGetterOnlyArray>();
});

//throws exception Unmapped properties: CalculatedArray
config.AssertConfigurationIsValid();
```

### Expected behavior

I did not expect to have to explicitly Ignore() collection read-only properties.

### Actual behavior

AssertConfigurationIsValid() throws exception when collection read-only properties are not explicitly Ignored() on destination types.

### Steps to reproduce

The Gist contains a sample Program.cs file that can be copy and pasted into an .NET Core Console application.

Please let me know if you need additional information.

Thanks!

**Comment by lbargaoanu** [comment]
By design. You can use `ForAllPropertyMaps` to achieve what you want.
