### ISSUE TITLE
ServiceCtor not available in IRuntimeMapper after 10.0 upgrade

### ISSUE THREAD

**Issue by tomgallard** [AutoMapper/AutoMapper#3456]
In the past (versions 9 and before) I have been able to use the ServiceCtor method to instantiate objects within my 'MapFrom' method. After upgrade to 10.0.0 , this method is no longer present. It seems to be on IMapper, but not on IRuntimeMapper or IMapperBase.

If this is a design decision- is there another approach I should be using?

### Mapping configuration

```csharp
/// from within MapFrom method 
var lookedUpItem = (IRepository<Item>)context.Mapper.ServiceCtor(typeof(IRepository<Item>));
```

### Expected behavior
I'd expect still to be able to use the ServiceCtor method on IRuntimeMapper

### Actual behavior

ServiceCtor no longer present on this interface. Seems to be present on IMapper but not IMapperBase or IRunTimeMapper

**Comment by lbargaoanu** [comment]
You should use DI in your resolvers, you're just doing a service locator thing there.

**Comment by tomgallard** [comment]
Sure and I do. But I had been able to avoid writing custom resolvers for simple things. This seems to have been am accepted approach e.g. https://www.google.com/amp/s/jimmybogard.com/automapper-usage-guidelines/amp/ . This change is also  ot documented anywhere?

**Comment by jbogard** [comment]
Ah, I should fix that. No, you should use DI instead of service location for these things. That guidance needs some tweaking, it still mentions `Mapper.Initialize` which is dead.
