### ISSUE TITLE
Keep API stable

### ISSUE THREAD

**Issue by Brunni** [AutoMapper/AutoMapper#3457]
I don't get it: I install the version 10 of automapper and my build fails.

I would prefer: Use deprecation and don't just remove methods, which are considered not useful.

e.g. https://docs.automapper.org/en/latest/10.0-Upgrade-Guide.html#context-mapper-map-overloads-that-receive-a-context-were-removed

We used this overload, we even had to use it at some places. Now it is just gone without any hints on how to do a workaround and without deprecation phase. I can just recommend to not use Automapper at all.

```
 CreateMap<A, B>()
                .ForMember(a=> a.eye, opt => opt.MapFrom(
                    (aa, _, __, context) =>
                    {
                        return new[]
                        {
                            context.Mapper.Map<PrescriptionSide>(aa.right, optRight => optRight.Items["side"] = Side.Right),
                            context.Mapper.Map<PrescriptionSide>(aa.left, optLeft => optLeft.Items["side"] = Side.Left)
                        };
                    }));
```

**Comment by lbargaoanu** [comment]
Just add an extension method with the required signature.

**Comment by jbogard** [comment]
There's no good way to obsolete an API, unfortunately. Even adding the `[Obsolete]` attribute will break your build if you treat warnings as errors. So we consolidate APIs to simplify our maintenance, and document them, and make sure we release a major version when the API breaks.

**Comment by Brunni** [comment]
I just have the feeling, that when we update our nuget packages in our project, all packages update without issues except for Automapper. There we always have compatibility issues in terms of API or behavioral changes.
And I'm asking, if there is a way to keep the API more stable to decrease the amount of work we have, when updating.
