### ISSUE TITLE
Automatic mapping of Tuples, ValueTuples and anonymous types

### ISSUE THREAD

**Issue by CollinAlpert** [AutoMapper/AutoMapper#3459]
### Source/destination types

```csharp
public class Person
{
    public string Name { get; set; }
    public int Age { get; set; }
}

public class PersonDto
{
    public string Name { get; set; }
    public int Age { get; set; }
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(m =>
{
    m.CreateMap<Person, PersonDto>().ReverseMap();
}).CreateMapper();
```

### Version: x.y.z
 
10.0.0

### Expected behavior

I would expect the `Tuple` as well as the `ValueTuple` to be mapped accordingly.

### Actual behavior

An `AutoMapperMappingException` was thrown saying the `Tuple` could not be mapped.

### Steps to reproduce

```csharp
var tuple = Tuple.Create(_person1, _person2);
var mappedTuple = mapper.Map<Tuple<PersonDto, PersonDto>>(tuple);
var mappedValueTuple = mapper.Map<(string value1, int value2)>(
    new
    {
        value1 = "Hello World",
        value2 = 10
    });
```

It would be great to be able to map `Tuple`s without having their exact signatures defined in a `CreateMap` statement but only the types they contain. This used to be possible. Same thing with anonymous types and mapping them to `ValueTuple`s. If this turns out not to be possible, I would be interested in knowing what the best practice approach would be in these cases.

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Open-Generics.html

**Comment by CollinAlpert** [comment]
That's a good hint, thanks! What about anonymous types? @lbargaoanu

**Comment by CollinAlpert** [comment]
So I just tried to apply the examples in the documentation to my code, but the same exception is thrown.
```csharp
var mapper = new MapperConfiguration(m =>
{
    m.CreateMap<Person, PersonDto>().ReverseMap();
    m.CreateMap(typeof(Tuple<>), typeof(Tuple<>)).ReverseMap();
}).CreateMapper();

var tuple = Tuple.Create(_person1, _person2);
var mappedTuple = mapper.Map<Tuple<PersonDto, PersonDto>>(tuple);
```

Am I missing anything?

**Comment by lbargaoanu** [comment]
Instead of using an anonymous type, directly create the destination type.

**Comment by CollinAlpert** [comment]
Why did you close this? Usng the open generics did not work for me. I still got the same mapping exception.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
