### ISSUE TITLE
Question: Updated Documentation and Feature Request

### ISSUE THREAD

**Issue by Cubelaster** [AutoMapper/AutoMapper#3460]
### Source/destination types

I basically want to use something like this:

```csharp
JsonConvert.DeserializeObject<TDestination>(source);
```

### Mapping configuration

```csharp
        public MetaProfile()
        {
            CreateMap<string, EntityAttachmentMeta>().ConvertUsing(typeof(MetaConverter<string, EntityAttachmentMeta>));
        }
```

### Expected behavior

I expect it to work. 
Now, I lost quite some time figuring out what I did wrong, but it seems I did nothing wrong. 
This configuration works as it should in Map<TDestination>(source) but it does not work with ProjectTo<TDestination>(source).
Is there a way to use the "Extensibility" functionalities in ProjectTo mode? 
[Documentation](https://docs.automapper.org/en/stable/Custom-type-converters.html#)

As far as I've worked with AutoMapper, ProjectTo is really superior to Map but it lacks all of these Extensibility features. 
Is there a way to use them with ProjectTo? 

### Actual behavior

It's even stranger that it would produce default value of object and not even hit debug point in ProjectTo mode, while in Map mode it works exactly as it should.

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by jbogard** [comment]
https://docs.automapper.org/en/stable/Queryable-Extensions.html#supported-mapping-options

**Comment by jbogard** [comment]
To expand on that - only operations that can be supported by a query provider are supported for LINQ. That severely limits the possibilities, and nothing we can do about it as those LINQ query execution pipelines are all proprietary and either no extension points or no common ones.

**Comment by Cubelaster** [comment]
OK, I understand that and i figured as much. 
However, I used a different approach in one of my previous applications, where I first materialized everything in lists, stored it in Cache and after that used AutoMapper to Map from 'Dto' to 'ViewModel'.
I avoided using ProjectTo in such a way but as you can imagine, that was not optimal for small queries and also required a lot of BE resources.
The main issue is the amount of code required for such process. Also, the maintenance cost. 
I needed manual Includes for pretty much every ViewModel call if I wanted to keep everything optimized. 
Not including Cache calls, because those were pretty much 1:1 to EF models anyway.

I am thinking that it may be possible to install this functionality in AutoMapper itself? 
Like, could it be possible that AutoMapper uses ProjectTo to materialize the Data itself and after it has done that, it can continue to Map to real Destination Type? 

Some kind of override to ProjectTo, which could be something like this: 
```csharp
    mapper.ProjectTo<TDestination>(IQueryable<TSource> query, typeof(TMaterializationType))
```
Or

```csharp
    mapper.ProjectTo<TDestination, TMaterialization, TSource>(IQueryable<TSource> query)
```

There is nothing stopping AutoMapper from saying, OK, sure, I'll first materialize everything in some kind of Midway model (why not EF model?) and after that, I'll just unpack it to destination. 

In such way, the ProjectTo would automatically use all the includes and all query optimizations and also be able to use such *filtered* data to map to destination type. 

I mean, sure, we could do it all manually but it would require a LOT of work and if it would be possible via AutoMapper, the cost of refactoring an old App would be minimal. 

This is just a Quality of Life suggestion. 
I have absolutely no idea if this is even possible, though it sounds so.

Thank you for your time and sorry to bother you :D
