### ISSUE TITLE
Calculated mapping failed if matching constructor parameters are present

### ISSUE THREAD

**Issue by aureole82** [AutoMapper/AutoMapper#3461]
I have a generated Destination model (WebApi proxy generation). That's why I get a default constructor and a full-fledged constructor on my generate `Destination` class. Unfortunately if matching constructor parameters are present the computed `MapFrom(s => s.StartDate.Date + s.StartTime)` isn't working anymore:

```csharp
// Models
public class Source
{
    public DateTime StartDate { get; set; }
    public TimeSpan StartTime { get; set; }
}
public class Destination
{
    public Destination() { }
    public Destination(DateTime startDate) { StartDate = startDate; }
    public DateTime StartDate { get; set; }
}

// Mapping configuration
var config = new MapperConfigurationExpression();
config.CreateMap<Source, Destination>()
    .ForMember(
        d => d.StartDate,
        options => options.MapFrom(s => s.StartDate.Date + s.StartTime))
    ;
var mapper = new Mapper(new MapperConfiguration(config));

// Mapping 
var source = new Source
{
    StartDate = new DateTime(2020, 7, 1),
    StartTime = new TimeSpan(0, 23, 59, 59, 999)
};
var destination = mapper.Map<Destination>(source);
```

### Version: Automapper 10
.NET Framework 4.7.1

### Expected behavior
`destination.StartDate = 2020-07-01T23:59:59.9990000`
(< Automapper 5)

### Actual behavior
`destination.StartDate = 2020-07-01T00:00:00.0000000`
(=> Automapper 5)

**Comment by lbargaoanu** [comment]
That's by design. It was already mapped by construction, so the property mapping is skipped.

**Comment by lbargaoanu** [comment]
I'm sure there are many ways to rewrite the mapping. One of them:

    c.CreateMap<Source, Destination>().ForCtorParam("startDate", options => options.MapFrom(s => s.StartDate.Date + s.StartTime));

**Comment by aureole82** [comment]
I got it! Thanks for the hint!
Here's my solution to point to the default constructor:
```cs
internal static class MappingExtensions
{
    /// <summary> Will use the default constructor if the model has more than one. </summary>
    public static IMappingExpression<TSource, TDestination> ConstructUsingDefaultConstructor<TSource, TDestination>(
        this IMappingExpression<TSource, TDestination> config) where TDestination : new()
    {
        return config.ConstructUsing((source, _) => new TDestination());
    }
}
```

Use like this:
```cs
config.CreateMap<Source, Destination>()
    .ConstructUsingDefaultConstructor()
    .ForMember(
        d => d.StartDate,
        options => options.MapFrom(s => s.StartDate.Date + s.StartTime))
    ;
```
