### ISSUE TITLE
Attribute Mapping: "Use This Constructor" Attribute

### ISSUE THREAD

**Issue by markm77** [AutoMapper/AutoMapper#3462]
Would it be possible to have an attribute which can be added to the preferred constructor to ensure that it is the one used by AutoMapper when creating a destination object?

**Comment by lbargaoanu** [comment]
You can implement that yourself. Check https://github.com/AutoMapper/AutoMapper/search?q=shoulduseconstructor&unscoped_q=shoulduseconstructor.

**Comment by markm77** [comment]
Okay, will look at the effort required here but to me seems this would be a useful addition to the current set of standard attributes.

**Comment by jbogard** [comment]
It would be interesting to add for the attribute-based maps. But I don't want to add it for the code config-based maps.

**Comment by markm77** [comment]
Sure, makes sense. BTW I noticed when debugging that AutoMapper calls constructors multiple times unexpectedly (breakpoints get hit multiple times). I was testing your cool new feature for over-riding constructor parameter defaults. I haven't had time to write up a full issue but just thought might be interesting for you to know.
