### ISSUE TITLE
Missing ConfigurationProvider in Automapper 10.0.0

### ISSUE THREAD

**Issue by GoNextGroup** [AutoMapper/AutoMapper#3463]
Hello.

In earlier versions of Automapper I can use `context.Mapper.ConfigurationProvider.GetAllTypeMaps();` 
Now `ResolutionContext` doesn't contain `ConfigurationProvider`. I can't get `TypeMap[]` array and skip mapping unmapped pairs. And also I can't use `GetService/GetRequiredService` in the `ConstructUsing/ConvertUsing` methods for, for example, `MapperConfiguration` resolving.
Could you explain the way to get `TypeMap[]` array now?

Thank you.

**Comment by lbargaoanu** [comment]
If you don't want validation, you should say so when creating the map.

**Comment by lbargaoanu** [comment]
Anyway, you can always inject `IConfigurationProvider`, although you probably shouldn't.

**Comment by GoNextGroup** [comment]
> `r`, although you probably shouldn't.

I'm sorry, but could you give me a little example of how to do this in the concrete `CreateMap` in a `Profile`?

thank you.

**Comment by jbogard** [comment]
What exactly are you trying to do here?

**Comment by GoNextGroup** [comment]
> What exactly are you trying to do here?

I had this code:

```
            CreateMap<ICollection<UserProfile>, ShortLegalEntityInformationResponse>()
                     .IncludeAllDerived()
                     .ConvertUsing  ((src, dest, context) =>
                     {
                         if (dest == null) { dest = new ShortLegalEntityInformationResponse(); }

                         var mapTypes = context.Mapper.ConfigurationProvider.GetAllTypeMaps();

                         src.ForEach(elem =>
                         {
                             if (mapTypes.Any(x => x.SourceType.Equals(elem.GetType()) && x.DestinationType.Equals(dest.GetType())))
                             {
                                 context.Mapper.Map(elem, dest, elem.GetType(), dest.GetType());
                             }
                         });

                         return dest;
                     });
```

It works in Automapper 9.0.0 but not in 10.0.0
I need this code because I have a partial mapping for `UserProfile` derived classes. For example, I have only one mapping like this: `CreateMap<LegalEntityProfile, ShortLegalEntityInformationResponse>()`, but not for, for example, `DriverProfile` which both are derived from `UserProfile`. An `ICollection<UserProfile>` may contains both of `DriverProfile` and `LegalEntityProfile` objects. If I won't use check like this, I will get mapping error for unmapped `DriverProfile` to `ShortLegalEntityInformationResponse`.

**Comment by lbargaoanu** [comment]
Just create a map from `UserProfile` to `ShortLegalEntityInformationResponse`. It doesn't have to do much, but it will simplify things.

**Comment by GoNextGroup** [comment]
https://github.com/lbargaoanu Thank you. It's so sad that there is no available `ConfigurationProvider` and `ServiceProvider` (for `GetRequiredService`) now... (((((
