### ISSUE TITLE
Standardise APIs between type converters, value resolvers, and value converters

### ISSUE THREAD

**Issue by IanKemp** [AutoMapper/AutoMapper#3464]
Type converters:

* allow the conversion operation to be specified either via an instance of an implementation of `ITypeConverter`, or a type parameter referring to an implementation of `ITypeConverter`, or an inline delegate

Value resolvers:

* allow the resolution operation to be specified either via an instance of an implementation of `IValueResolver`, or a type parameter referring to an implementation of `IValueResolver`, or a type (that may or may not implement `IValueResolver`)

Value converters:

* allow the conversion operation to be specified either via an instance of an implementation of `IValueConverter`, or a type parameter referring to an implementation of `IValueConverter`
* states that it can be instantiated by the services locator by specifying a type parameter - is this identical to how it works with type converters?

As you can see, while all of these mechanisms share similarities in the way they are applied, there are also differences that make switching between them more difficult than it has to be (unnecessarily, IMO). For example, while I can define an inline delegate for a type converter, I cannot do the same for a value resolver.

I'd like to understand the reason(s) for the differences in these APIs - is it due to performance concerns, the fact that they evolved separately, or...?

Depending on the reasoning, I'd like to propose that the API for all three of these be standardised so that they behave like type converters.

**Comment by lbargaoanu** [comment]
What's the specific problem you're having? If smth is missing, we'll take a PR to add it.

**Comment by lbargaoanu** [comment]
About the existing API-s, we've just released a major version, so no change there anytime soon.
