### ISSUE TITLE
AutoMapper 10.0 - IReadOnlyCollection<T> mapped by default

### ISSUE THREAD

**Issue by kakone** [AutoMapper/AutoMapper#3465]
With AutoMapper 10.0, all collections are mapped by default, even read only collections (that implements [IReadOnlyCollection\<T>](https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.generic.ireadonlycollection-1)).

Shouldn't these properties be ignored by default ?

As a workaround, I did this to ignore these properties :
```csharp
var readOnlyCollectionType = typeof(IReadOnlyCollection<>);
services.AddAutoMapper(cfg => cfg.ForAllMaps((m, e) =>
{
    foreach (var p in m.DestinationType.GetProperties())
    {
        if (p.PropertyType.IsGenericType(readOnlyCollectionType))
        {
            m.FindOrCreatePropertyMapFor(p).Ignored = true;
        }
    }
})
```

### Source/destination types

```csharp
public class Source
{
    public bool Property { get; set; }
}

public class Destination
{
    public bool Property { get; set; }

    private readonly List<int> _collection = new List<int>();
    public IReadOnlyCollection<int> ReadOnlyCollection => _collection.AsReadOnly();
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>();
```

### Expected behavior

Ignore properties declared as [IReadOnlyCollection\<T>](https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.generic.ireadonlycollection-1), or [ReadOnlyCollection\<T>](https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.objectmodel.readonlycollection-1), or [ReadOnlyDictionary\<TKey, TValue>](https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.objectmodel.readonlydictionary-2), ...

**Comment by lbargaoanu** [comment]
`List` implements `IReadOnlyCollection`. And we do map `IEnumerable`. It seems easier at this point to just map everything. And then people should set their own defaults.
