### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by olsh** [AutoMapper/AutoMapper#3466]
### Source/destination types

Source types EF Core models:
```csharp
    public partial class Addresses
    {
        public Addresses()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string Address { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }

    public partial class Users
    {
        public int Id { get; set; }
        public int FkAddressId { get; set; }

        public virtual Addresses FkAddress { get; set; }
    }
```

Target types:
```csharp
    public class AddressDto
    {
        public int Id { get; }
        public string Address { get; }

        public AddressDto(int id, string address)
        {
            Id = id;
            Address = address;
        }
    }

    public class UserDto
    {
        public int Id { get; set; }
        public AddressDto AddressDto { get; set; }
    }
```

### Mapping configuration

```csharp
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {

            CreateMap<Users, UserDto>()
                .ForMember(d => d.Id, e => e.MapFrom(s => s.Id))
                .ForMember(d => d.AddressDto, e => e.MapFrom(s => s.FkAddress));

            CreateMap<Addresses, AddressDto>()
                .ConstructUsing(a => new AddressDto(a.Id, a.Address));
        }
    }

    var config = new MapperConfiguration(cfg => cfg.AddProfile(typeof(MappingProfile)));
    var mapper = config.CreateMapper();
```

### Version: 
Autmapper 10.0.0 (reproducible on 9.0.0 too)
EF Core 3.1.6

### Expected behavior
User retrieved from DB with filled address
```chsarp
var user = mapper.ProjectTo<UserDto>(this.Users).First();
```

### Actual behavior
Exception message: `The given key 'a' was not present in the dictionary.`
StackTrace
```
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.GetParameterValue[T](QueryContext queryContext, String parameterName)   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)   at System.Linq.Queryable.First[TSource](IQueryable`1 source)   at UserQuery.Main() in C:\Users\olsh\AppData\Local\Temp\LINQPad6\_bpulzfxa\uqzfhz\LINQPadQuery:line 5   at LINQPad.ExecutionModel.ClrQueryRunner.Run()   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```

### Steps to reproduce

```chsarp
var user = mapper.ProjectTo<UserDto>(this.Users).First();
```

### Additional info
I tried inspecting an expression generated by Automapper as described here https://docs.automapper.org/en/stable/Understanding-your-mapping.html
```
dtoUsers => new UserDto() {AddressDto = IIF((dtoUsers.FkAddress == null), null, new AddressDto(a.Id, a.Address) {}), Id = dtoUsers.Id}
```
and it works fine with the context if I code the expression manually. 
So I'm not sure if it's an EF Core bug or bug in my code.

**Comment by lbargaoanu** [comment]
This looks like an EF Core issue. Try another version, including the daily.

**Comment by olsh** [comment]
Hi @lbargaoanu ,

Thanks for the quick reply.

I've tried this example with EF `2.2.6` version. This throws a similar exception:
`variable 'a' of type 'AutomapperTests.Models.Addresses' referenced from scope '', but it is not defined`

Version `5.0.0-preview.3.20181.2` throws the same exception as 3.1.6
`The given key 'a' was not present in the dictionary`

I was unable to test it with the latest preview version `5.0.0-preview.6.20312.4` because of packages conflicts:
```
Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 5.0.0-preview.3.20215.2 directly to project AutomapperTests to resolve this issue.  
 AutomapperTests -> Microsoft.EntityFrameworkCore.SqlServer 5.0.0-preview.6.20312.4 -> Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.6.20312.4 -> Microsoft.EntityFrameworkCore 5.0.0-preview.6.20312.4 -> Microsoft.Extensions.Logging 5.0.0-preview.3.20215.2 -> Microsoft.Extensions.Options 5.0.0-preview.3.20215.2 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0.0-preview.3.20215.2)  
 AutomapperTests -> AutoMapper.Extensions.Microsoft.DependencyInjection 8.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.0.0 && < 4.0.0).  
```

**Comment by lbargaoanu** [comment]
I could be wrong :) But the stack trace seems to be inside EF Core. You should be able to make a repro without AM.

**Comment by olsh** [comment]
Here is hand-coded example which works:
```csharp
this.Users.Select(u => new UserDto { Id = u.Id, AddressDto = u.FkAddress == null ? null : new AddressDto(u.FkAddress.Id, u.FkAddress.Address) });
```

I played with mapping a little and found that if I change `ConstructUsing` to `MapFrom` then everything works fine, here is the expression which generates AM with `MapFrom` approach:
```csharp
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Select(dtoUsers => new UserDto() {AddressDto = IIF((dtoUsers.FkAddress == null), null, new AddressDto(dtoUsers.FkAddress.Id, dtoUsers.FkAddress.Address) {Address = dtoUsers.FkAddress.Address, Id = dtoUsers.FkAddress.Id}), Id = dtoUsers.Id})
```

If I revert mapping to `ConstructUsing` then the expression looks like this
```csharp
[Microsoft.EntityFrameworkCore.Query.QueryRootExpression].Select(dtoUsers => new UserDto() {AddressDto = IIF((dtoUsers.FkAddress == null), null, new AddressDto(a.Id, a.Address) {}), Id = dtoUsers.Id})
```

I'm not sure, but it seems like AM generates variable `a` in the expression which doesn't exist in the context.

**Comment by lbargaoanu** [comment]
Remove the `ConstructUsing`.

**Comment by olsh** [comment]
Well, this will solve the issue, but it looks like a workaround.

I didn't find that AM doesn't support `ConstructUsing` in `ProjectTo`.
https://docs.automapper.org/en/stable/Queryable-Extensions.html#supported-mapping-options

**Comment by lbargaoanu** [comment]
Certainly the code is better without `ConstructUsing` :) and does the same thing. The problem is that EF6 doesn't support constructor parameters, that's why this doesn't work.

**Comment by lbargaoanu** [comment]
You don't need the `MapFrom`, constructor mapping should work.

**Comment by olsh** [comment]
> Certainly the code is better without ConstructUsing :) and does the same thing.

Yes, if I remove both `ConstructUsing` and `MapFrom`, everything works, but we have naming mismatching in a real application. That's why we need to use `ConstructUsing`.

> The problem is that EF6 doesn't support constructor parameters, that's why this doesn't work.

Please note, that we are using EF Core.

**Comment by lbargaoanu** [comment]
`ForCtorParam` allows you to handle the mismatch.

**Comment by olsh** [comment]
Nice, I didn't know about the method, thank you! It solves the issue for us. 👍
Except that it's weakly typed parameter appears here which error-prone to refactoring.

But still, is it an AM bug that I cannot use `ConstructUsing` or it's just a lack of documentation?

**Comment by lbargaoanu** [comment]
I guess it could work, but it's only relevant now because of .Net Core. A PR is welcome.

**Comment by olsh** [comment]
Hi @lbargaoanu 
Sorry for bothering you. Why did you close the issue?

**Comment by lbargaoanu** [comment]
Because nobody is interested in writing the code.

**Comment by jbogard** [comment]
If this is a feature request, let’s leave it open. The auto-close stuff will take care of it if no one wants to add the feature.

**Comment by lbargaoanu** [comment]
As far as I'm aware only closed issues are handled that way.

**Comment by olsh** [comment]
Actually, it seems like a bug from a user perspective.
Automapper documentation states that Automapper supports the feature for projections. 
But it turned that it doesn't support it in some cases. I think that either the documentation should be updated (or at least add an appropriate exception ) or the bug should be fixed.

I'll try to find some time to fix it, but no guarantees.

Bot, please, do not delete the comment ❤️
