### ISSUE TITLE
Support for IAsyncEnumerable<T> .NET Core 30

### ISSUE THREAD

**Issue by yorickdewid** [AutoMapper/AutoMapper#3469]
I am trying to map a `IAsyncEnumerable<T>` list of entities to a regular `List<T>` without any database or IQueryable. The source entities come from an async cache store which does not support `IQueryable`. But there are more use cases when one wants to map an `IAsyncEnumerable<T>` to a non async enumerable.

# Source/destination types

### Mapping setup
```csharp

class Source
{
    public int MyProperty { get; set; }
}

class Dest
{
    public int MyProperty { get; set; }
}

IAsyncEnumerable<Source> asyncEnumerable = GetAllItemsAsync(...);

```

### Desired behavior

```csharp
List<Dest> result = _mapper.Map<IAsyncEnumerable<Source>, List<Dest>>(asyncEnumerable);
```

However this is not possible.

### Workaround 1
```csharp
List<Dest> result = new List<Dest>();
await foreach (var item in asyncEnumerable)
{
    result.Add(_mapper.Map<Dest>(item));
}
```

### Workaround 2
```csharp
List<Source> result = new List<Source>();
await foreach (var item in asyncEnumerable)
{
    result.Add(item);
}
List<Dest> result_new = _mapper.Map<List<Dest>>(result);
```

Neither one is clean enough. This is a mapping one might want to do in a single line.

**Comment by lbargaoanu** [comment]
`Map` is sync, so write your own extension method? :)

**Comment by yorickdewid** [comment]
Yeah already did that. Should did not be part of AutoMapper?

**Comment by lbargaoanu** [comment]
No, there is nothing async in AM.
