### ISSUE TITLE
Hot to get a result by executing custom function using db session context

### ISSUE THREAD

**Issue by fairking** [AutoMapper/AutoMapper#3474]
I am using `NHibernate`. We all know that the expression `order.Items.Count` will pull all items out of the database which is very expensive for the app performance. The preferred way to get any count is to run a separate query.
The question is is there any way to run a custom function with db session context (or any other service) when mapping a dto.
If not, bellow is my proposition how it can be implemented in AutoMapper. So I can use the `SessionResolver` to get count or any other data without writing it separately for every situation.

ISession is a scoped service. So the instance of `SessionResolver` must be created when `Mapper.Map<>` is called.

### Source/destination types

```csharp
// Source
public class Order
{
  public IList<OrderItem> Items { get; protected set; }
}

public class OrderItem
{
  public Order Order { get; protected set; }
}

// Destination
public class OrderDto
{
  public int ItemCount { get; set; }
}
```

### Mapping configuration

```csharp

// A new Resolver in AutoMapper project needs to be implemented
public interface IProviderResolver<TSource, TDest, TProvider, TDestMember>
{
    TDestMember Resolve(TSource source, TDest destination, TDestMember destMember, Func<TSource, TDest, TProvider, TDestMember> function);
}

// Implementation in my project
public class SessionResolver<TSource, TDest, TDestMember> : IProviderResolver<TSource, TDest, ISession, TDestMember>
{
    private readonly ISession _session;

    public SessionResolver(ISession session)
    {
        _session = session;
    }

    #region IProviderResolver

    public TDestMember Resolve(TSource source, TDest destination, TDestMember destMember, Func<TSource, TDest, ISession, TDestMember> function)
    {
        return function.Invoke(source, destination, _session);
    }

    #endregion IProviderResolver
}

// Profiler in my project
CreateMap<Order, OrderDto>()
    .ForMember(d => d.ItemCount, map => map.MapFrom<SessionResolver<Order, OrderDto, int>>((src, dest, session) =>
    {
        return session.Query<OrderItem>().Where(x => x.Order == src).Count();
    }
));

// Example in my code
var order = await _session.GetAsync<Order>(orderId);
var dto = Mapper.Map<OrderDto>(order);
```

### Expected behavior

Be able to run custom queries by injecting `ISession` or any other service into resolver with the logic in custom function.
Also would be nice to use `async`
```
// Profiler in my project
CreateMap<Order, OrderDto>()
    .ForMember(d => d.ItemCount, map => map.MapFrom<SessionResolver<Order, OrderDto, int>>((src, dest, session) =>
    {
        return await session.Query<OrderItem>().Where(x => x.Order == src).CountAsync();
    }
));

// Example in my code
var order = await _session.GetAsync<Order>(orderId);
var dto = await Mapper.MapAsync<OrderDto>(order);
```

### Actual behavior

Not implemented

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
Check https://docs.automapper.org/en/latest/Dependency-injection.html. You don't need `async` to map between two objects. But I guess that's not what you're doing here :)

**Comment by fairking** [comment]
@lbargaoanu 
Sorry but I aware of existing DI functionality in AutoMapper and I assume you are pointing out the following example:
![image](https://user-images.githubusercontent.com/13495631/88392205-860c1400-cdb3-11ea-9714-567502a7bd27.png)

But my poit is I have to implement as many Custom Resolvers as many times I would need it in my code.
The question is if I can use a custom function (see title).

**Comment by lbargaoanu** [comment]
DI works with classes and AM does the same. If that's not what you want, you can always pass things through `Context.Items`.

**Comment by fairking** [comment]
So you mean I can pass `ISession` to the context like that?
```
public class SessionResolver<TSource, TDest, TDestMember> : IValueResolver<TSource, TDest, TDestMember>
{
    private readonly ISession _session;

    public SessionResolver(ISession session)
    {
        _session = session;
    }

    #region IProviderResolver

    public TDestMember Resolve(TSource source, TDest destination, TDestMember destMember, ResolutionContext context)
    {
        context.Items.Add("session", _session);
        return destMember;
    }

    #endregion IProviderResolver
}
```

How the mapping will look like?

Sorry I am confused. Can you please provide some example. Would be nice to include it into the documentation.

**Comment by jbogard** [comment]
There's a much easier way to do this, `Ignore` the items count property and issue that in a separate query after you map. Don't try to do this inside of your mapping operation.

That way you can do things like NHibernate Future Queries and async which are going to be more efficient than whatever you're doing here.

**Comment by fairking** [comment]
Thanks guys for your time and for all your suggestions.
I created a resolver which allows me to do what I needed.

**CustomResolver.cs**:
```
public class CustomResolver<TSource, TDest, TService, TDestMember> : IValueResolver<TSource, TDest, TDestMember>
{
    private readonly Func<TSource, TDest, TService, TDestMember> _func;

    public CustomResolver(Func<TSource, TDest, TService, TDestMember> func)
    {
        _func = func ?? throw new ArgumentNullException(nameof(func));
    }

    #region IProviderResolver

    public TDestMember Resolve(TSource src, TDest dest, TDestMember destMember, ResolutionContext context)
    {
        var service = (TService)context.Options.ServiceCtor(typeof(TService));
        return _func.Invoke(src, dest, service);
    }

    #endregion IProviderResolver
}
```

Mapping:
```
CreateMap<Order, OrderDto>()
    .ForMember(d => d.ItemCount, map => map.MapFrom(new CustomResolver<Order, OrderDto, ISession, int>((src, dest, session) =>
        {
            return session.Query<OrderItem>().Where(x => x.Order == src).Count();
        })
    ));
```

And then just use map:
```
var dto = mapper.Map<OrderDto>(order);
```

Everything is working so far. 🥇 

Please feel free to include it into the docs so other people can use it.

**Comment by fairking** [comment]
@jbogard Sorry I don't understand why you removed my comment. If you think DI should not be used in AutoMapper but outside of it:
> @jbogard There's a much easier way to do this, Ignore the items count property and issue that in a separate query after you map. Don't try to do this inside of your mapping operation.

Then why DI functionality exists in AutoMapper at all?

**Comment by lbargaoanu** [comment]
I removed your comment. It's a poor usage of AM and I don't want new comers to think we're recommending that kind of code.

**Comment by jbogard** [comment]
DI is best for things like getting the current user or grabbing something from cache. This approach could result in some bad performing code if it’s done in a loop for example.
