### ISSUE TITLE
AssertConfigurationIsValid constructor validation and static properties 

### ISSUE THREAD

**Issue by aristovg** [AutoMapper/AutoMapper#3476]
Hi team, it seems that introducing static properties to a destination member alters `AssertConfigurationIsValid` behavior when validating constructor arguments mapping. 

### Source/destination types

```csharp
class Source
{
    public string Prop { get; set; }
}

class Destination
{
    public string NotMatched { get; }
    public Destination(string notMatched) => (NotMatched) = (notMatched);
}

class Destination2
{
    public static string Prop2 { get; } = "A";
    //or public static readonly string Field2 = "A";
    public string NotMatched { get; }
    public Destination2(string notMatched) => (NotMatched) = (notMatched);
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(c =>
{
    c.CreateMap<Source, Destination>(); //throws 
    c.CreateMap<Source, Destination2>(); //passes
});
config.AssertConfigurationIsValid();
```

### Expected behavior

`AssertConfigurationIsValid` should fail for `Destination2`

### Actual behavior

`AssertConfigurationIsValid` passes

I assume this is not expected behavior?

**Comment by lbargaoanu** [comment]
Yeah, I don't know what's that about :) A PR is welcome.
