### ISSUE TITLE
Null substitution rules are not inherited

### ISSUE THREAD

**Issue by fsateler** [AutoMapper/AutoMapper#348]
With the following class hierarchy:

```
class Source {
    public int? i { get; set; }
};

class Source2 : Source {
    public int a { get; set; }
}

class Dest {
    public string i { get; set; }
    public string a { get; set; }
    public string unmapped { get; set; }
    public string acopy { get; set; }
}
```

And the following mapping rules:

```
Mapper.CreateMap<Source, Dest>()
    .Include<Source2, Dest>()
    .ForMember(d => d.a, conf => conf.UseValue("N/E"))
    .ForMember(d => d.acopy, conf => conf.UseValue("N/E"))
    .ForMember(d => d.unmapped, conf => conf.UseValue("StaticValue"))
    .ForMember(d => d.i, conf => conf.NullSubstitute("N/A"));
    ;
Mapper.CreateMap<Source2, Dest>()
    .ForMember(d => d.acopy, conf => conf.MapFrom(s => s.a))
    ;
```

Given the following source objects and mapping them:

```
var sources = new Source[] {
    new Source{
        i = null
    },
    new Source2 {
        i = null,
        a = 2
    }
};

sources.Select(o => Mapper.Map(o, o.GetType(), typeof(Dest))).Dump();
```

Results in the following:

```
|i      |a      |unmapped    |acopy
---------------------------------------------
|N/A   |N/E     |StaticValue |N/E
|null  |N/E     |StaticValue |2
```

So, for the first object of type `Source`, everything is mapped correctly. In the second case (type `Source2`) we have the property `i` mapped incorrectly, since it didn't substitute the null value for "N/A". Note how UseValue gets inherited, as shown by the `a` property, but gets properly overriden in the `acopy` property.

I think NullSubstitute should have the same inheritance rules as UseValue, and these rules should be inherited.

**Comment by fsateler** [comment]
I can still reproduce this issue with 3.3.1

**Comment by lbargaoanu** [comment]
@fsateler If it still doesn't work, please reopen the issue.

**Comment by fsateler** [comment]
I can't reopen it. Or at least I don't see where I could do so.

**Comment by lbargaoanu** [comment]
Apparently you cannot open your own issue if you didn't close it yourself. @jbogard can you please reopen this?
