### ISSUE TITLE
Missing type mapping (type to itself) does not throw an exception

### ISSUE THREAD

**Issue by StefanOssendorf** [AutoMapper/AutoMapper#3480]
### Source/destination types

```csharp
public class Foo
{
    public String Name { get; set; }
    public Int32 Age { get; set; }
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(c => {}).CreateMapper();
```

### Expected behavior

`Map<Foo,Foo>()` should throw since no mapping is configured.

### Actual behavior

`Map<Foo,Foo>()` executes and does nothing since no mapping was configured.

### Steps to reproduce

It does not matter if I provide a destination or not to have this behavior.

https://gist.github.com/StefanOssendorf/277f36c441178a3515f42a3aefb8140f

**Comment by lbargaoanu** [comment]
That's by design. But check https://docs.automapper.org/en/latest/Configuration-validation.html#custom-validations.

**Comment by vratojr** [comment]
@lbargaoanu could you please explain better why did you do this design choice for something that really looks like a user mistake? (forgetting to define the mapping). It's not always easy to check automapper configuration and I think that having this kind of errors, helps.

**Comment by jbogard** [comment]
This is such an edge case, it's not worth the effort is why.
