### ISSUE TITLE
Global variables in ResolutionContext 

### ISSUE THREAD

**Issue by RebelionTheGrey** [AutoMapper/AutoMapper#3481]
Hello.

Sometimes in my projects, I need to have some variables to be globally set - each time I resolve the Mapper class object, I want to have these variables added in the ResolutionContext because now I need to add these variables in each mapping in my code with opts => opts.Items.Add(...). 
For example, I have the IMemoryCache cache variable which I want to have in each ResolutionContext too.
But there is no mechanism to add it in the MapperConfiguration or Profile (or in the mapper object created at runtime) - no methods which allow to implement this.
Is it any way to realize this behavior indirectly?

Thank you.

**Comment by lbargaoanu** [comment]
This sounds like a job for the DI engine.

**Comment by RebelionTheGrey** [comment]
> This sounds like a job for the DI engine.

One problem - MapFrom and ConverUsing do not implement ServiceLocator pattern...

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Dependency-injection.html

**Comment by RebelionTheGrey** [comment]
> https://docs.automapper.org/en/latest/Dependency-injection.html

But It cannot allow me to add this variables directrly in the ResolutionContext, only in IMemoryCache which I will resolve with DI...

**Comment by lbargaoanu** [comment]
I would look into how the DI engine can help with passing those values. I don't think AM should have any special features for smth like that.

**Comment by RebelionTheGrey** [comment]
I'm so sorry, but is it possible to scale up Dependency Injection example for this situation? I really have no idea how to resolve `IMemoryCache` in the `MapFrom` or `ConstructUsing`/`ConvertUsing` methods with DI. I use a built-in .net core container. (((sorry to disturb you...

**Comment by jbogard** [comment]
Well, you used to be able to get that from the `ResolutionContext` but I think that's broken. @lbargaoanu I think the refactoring for `IRuntimeMapper` missed the `ServiceCtor` part. That should be moved up to the base interface.

**Comment by lbargaoanu** [comment]
I meant to do that. Why would we encourage an anti-pattern (service locator)? If you need DI, you declare a class with constructor injection and that's that. That's how DI is supposed to be used after all.

**Comment by jbogard** [comment]
Ah I misunderstood the question. Yes, you should just create the classes that allow you to inject those services.

**Comment by GoNextGroup** [comment]
https://github.com/lbargaoanu

Okay, let's check a simple example.

I have `IMemoryCache` realization. So, each time I need to use memory cache in my mappings, I should do the dumb thing like this:

`var response = mapper.Map<SameResponse>(request, opts => opts.Items.Add("MemoryCache", memoryCache));`

And in the each mapping I need to do the same: 

```
.MapFrom(s => s.SomeField, f => f.MapFrom((src, _, _, ctx) =>
{
     var memoryCache = (IMemoryCache)ctx.Options.Items["MemoryCache"];
...

}
```

And the same for any other services and `.ConstructUsing/ConvertUsing`.

**Comment by RebelionTheGrey** [comment]
Okay, let's check a simple example.

I have IMemoryCache realization. So, each time I need to use memory cache in my mappings, I should do the dumb thing like this:

var response = mapper.Map<SameResponse>(request, opts => opts.Items.Add("MemoryCache", memoryCache));

And in the each mapping I need to do the same:

.MapFrom(s => s.SomeField, f => f.MapFrom((src, _, _, ctx) =>
{
     var memoryCache = (IMemoryCache)ctx.Options.Items["MemoryCache"];
...

}
And the same for any other services and .ConstructUsing/ConvertUsing.

**Comment by jbogard** [comment]
Where does the `IMemoryCache` variable come from?

**Comment by RebelionTheGrey** [comment]
jbogard, it can be resolved from IServiceProvider, of course. But, I can't find a clear solution for DI for the `MapFrom` and `ConvertUsing`. It's not so easy to understand the information block, connected with DI usage in the Automapper documentation, sorry.(((

**Comment by jbogard** [comment]
https://docs.automapper.org/en/stable/Dependency-injection.html#dependency-injection

Note the section that talks about which extensions are DI-enabled. If you're using https://github.com/automapper/automapper.extensions.microsoft.dependencyinjection then those dependencies are automatically registered in your container.

To use DI for `MapFrom` or `ConvertUsing`, use the overloads that take an object that is DI-enabled:

```csharp
cfg.CreateMap<Src, Dest>().ConvertUsing<SrcToDestConverter>();
cfg.CreateMap<Src2, Dest2>().ForMember(src => src.Foo, opt => opt.MapFrom<FooValueResolver>());
```

Those objects will be instantiated by the container, and if you declare them with dependencies in their constructors, will have the dependencies injected.

**Comment by RebelionTheGrey** [comment]
Hm... Sounds like something interesting, but there are no applicable overloads for the `.MapFrom`, I can't find applicable overload which allows using `IValueResolver<>` and has `Func<TSource, TDestination, TMember, TResult>` / ``Func<TSource, TDestination, TMember, ResolutionContext, TResult>` parameter. 
So, should I write ValueResolver each time (for each mapping)?

**Comment by jbogard** [comment]
Those value resolvers and member value resolvers and value converters can be reused if you want. It's by design that you can declare the generic parameters to be able to be used across multiple mappings (for example, use `object` if you don't care about the source type).

**Comment by RebelionTheGrey** [comment]
Ah, understand. I'll try to realize one for today. But have no idea yet how to pass lambdas in it. Hope, I'm on the right way. Thank you.

**Comment by jbogard** [comment]
You don't pass lambdas into a resolver. The resolver's method *is* the implementation for your mapping.

We took away the "Service Location" way of doing things because it's confusing and not obvious where the service is located from (also the lambdas would get big and ugly).

**Comment by RebelionTheGrey** [comment]
Hm... Even so, I need to write local resolvers for each mapping realizes its own logic If I want to use DI in it.

For example, this code cannot be implemented without own ValueResolver:

```
...
.ForMember(e => e.SomeField, f => f.MapFrom((src, _, _, ctx) =>
{
     var memCache = (IMemoryCache)ctx.Options.Items["MemoryCache"];  //<-- here can be passed IServiceProvider in general or ServiceScope for scoped/transient services
     return 42 + src.SomeAnotherField * memCache.Get("SomeValueToMultiply");
}));
```
}
