### ISSUE TITLE
Consider trimming keys when mapping from dictionaries

### ISSUE THREAD

**Issue by dim5** [AutoMapper/AutoMapper#3483]
Consider improving the matching algorithm when mapping from dictionaries. The [docs](https://docs.automapper.org/en/latest/Dynamic-and-ExpandoObject-Mapping.html) states that 

> You can map straight from Dictionary<string, object> to objects, AutoMapper will line up the keys with property names.

..but white-spaces prevent the mapping, even though they're not legal characters in member names. Trimming white-spaces from these strings could help avoid some silent bugs.

### Steps to reproduce

```csharp
class Foo
{
    public string Bar { get; set; }
    public int Baz { get; set; }
}

void Example()
{
    var input = new Dictionary<string, object>
    {
        {" Bar", "test"},
        {"Baz ", 1213}
    };

    var mapper = new MapperConfiguration(_ => { }).CreateMapper();

    var mapped = mapper.Map<Foo>(input);
}
```

### Expected behavior

I'd expect `mapped` to contain "test" and 1213.

### Actual behavior

 `mapped` contains just the defaults.

**Comment by lbargaoanu** [comment]
A PR is welcome. See [here](https://github.com/AutoMapper/AutoMapper/blob/09b79d84674f9ed174ebbd788408cc3043a4c418/src/AutoMapper/Mappers/FromStringDictionaryMapper.cs#L37).

**Comment by dim5** [comment]
Thanks, I'll open a PR later this week.

**Comment by lbargaoanu** [comment]
The tests are [here](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/Mappers/StringDictionaryMapperTests.cs).
