### ISSUE TITLE
Broken link in https://automapper.org/

### ISSUE THREAD

**Issue by PalashBansal** [AutoMapper/AutoMapper#3484]
dnrTV episode Full walkthrough - http://www.dnrtv.com/default.aspx?showNum=155 link "404" error.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by PalashBansal** [comment]
duplicate of https://github.com/AutoMapper/AutoMapper.website/issues/7

**Comment by lbargaoanu** [comment]
Right, thanks!
