### ISSUE TITLE
Fluent options

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#3492]
```csharp
CreateMap().ForMember(d => d.A, o => o.MapFrom(s => s.B).NullSubstitute("null"));
```
looks nicer, than bulky
```csharp
o =>
{
    o.MapFrom(s => s.B);
    o.NullSubstitute("null");
}
```
:-)

**Comment by jbogard** [comment]
I think this is more possible now - originally several config methods had other ones chaining off of them - `o.MapFrom().FromSourceMember().Etc().Etc()` that made the interface you described impossible.
