### ISSUE TITLE
Code example for AutoFac integration needs a small update

### ISSUE THREAD

**Issue by quetzalcoatl** [AutoMapper/AutoMapper#3494]
File:
docs/Dependency-injection.md

Fragment:
```
builder.Register<IMapper>(ctx => new Mapper(ctx.Resolve<IConfigurationProvider>(), ctx.Resolve)).InstancePerDependency();
```

Should be:
```
builder.Register(c =>
    c.Resolve<AutoMapper.IConfigurationProvider>()
      .CreateMapper(c.Resolve<IComponentContext>().Resolve))
      .As<AutoMapper.IMapper>().InstancePerLifetimeScope();
```

Summary: changed bound `ctx.Resolve` to late-bound `c.Resolve<IComponentContext>().Resolve` to properly support resolving IValueResolvers in MapperProfiles; `ctx.Resolve` binds the resolution to the resolution of AutoMapper's IMapper object, which is not OK because when user tries to use IMapper object to .Map something, the resolution of IMapper is already finished and cannot be 'reused'. That caused resolving IValueMappers in .Map to fail. Any calls to .Map on already-resolved IMapper must have their own resolution context. Hence the change.

Originally reported by: https://github.com/AutoMapper/AutoMapper/issues/1109#issuecomment-330029654  
Original solution: https://github.com/AutoMapper/AutoMapper/issues/1109#issuecomment-343668871

**Comment by lbargaoanu** [comment]
I think you should simply use the existing package. That's just an example to get the general idea. I'll remove all that code and keep the link to the original blog.

**Comment by quetzalcoatl** [comment]
Please reconsider - I just HAD to use that code (and I'm totally grateful for everyone posting it) - because I work on legacy project with AutoMapper 8.0 and (1) cant upgrade (2) that nuget pulls AutoMapper 8.1.1 - but, of course, we could also ask nuget's mantainer to add a version for 8.0 :) I thought it's easier to swap a line here in docs.

**Comment by lbargaoanu** [comment]
@jbogard I'd rather not maintain that example. The links seem enough to me.
