### ISSUE TITLE
Projection with inheritance tree based on abstract class

### ISSUE THREAD

**Issue by Angelinsky7** [AutoMapper/AutoMapper#3497]
Hi,
i'm trying to project an IQueryable datasource composed of multiple different types based on the same abstract class.
When trying to call the `ToList` method, i'm hitting `Can't compile a NewExpression with a constructor declared on an abstract class`.
It seems normal because i'm asking `Automapper` to `ProjectTo<>` the base class. But what it would seem more usable, would be that the projection is made on each item real class of the IQueryable.

I was (maybe naively) thinking that when issuing `Include<SubClass, SubDto>()` call it will handle this case.

### Source/destination types

```csharp
public abstract class MainEntity {
  public Guid Id { get; set; } = Guid.NewGuid();
  public String Property0 { get; set; }
}

public class SubEntity1 : MainEntity {
  public String Property1 { get; set; }
}

public class SubEntity2 : MainEntity {
  public String Property2 { get; set; }
}
```

```csharp
public abstract class MainDto {
  public Guid Id { get; set; }
  public String Property0 { get; set; }
}

public class SubDto1 : MainDto {
  public String Property1 { get; set; }
}

public class SubDto2 : MainDto {
  public String Property2 { get; set; }
}
```

### Mapping configuration

```csharp
public AutoMapperProfile() {
  CreateMap<MainEntity, MainDto>()
    .Include<SubEntity1, SubDto1>()
    .Include<SubEntity2, SubDto2>()

    .ForMember(p => p.Id, opt => opt.MapFrom(src => src.Id))
    .ForMember(p => p.Property0, opt => opt.MapFrom(src => src.Property0));

  CreateMap<SubEntity1, SubDto1>()
    .ForMember(p => p.Property1, opt => opt.MapFrom(src => src.Property1));

  CreateMap<SubEntity2, SubDto2>()
    .ForMember(p => p.Property2, opt => opt.MapFrom(src => src.Property2));

}
```

### Version
Automapper@10.0.0
EfCore@3.1.0 and EfCore@5.0.0-preview8

### Expected behavior

I would except that the projection of each item is done depending on each "real" type. Now, each item in `IQueryable<MainDto>` are either `SubEntity1` or `SubEntity2` but when using `ProjectTo<MainDto>`, `Automapper` is only trying to create `MainDto`.

### Actual behavior

`Automapper` crash with `Can't compile a NewExpression with a constructor declared on an abstract class` because it's trying to project the base-class instead of the sub-classes.

### Steps to reproduce

[AutoMapperInheritance.zip](https://github.com/AutoMapper/AutoMapper/files/5217450/AutoMapperInheritance.zip)

```csharp
IQueryable<MainDto> query = context.Entities.ProjectTo<MainDto>(mapper.ConfigurationProvider);
// This call crash with Can't compile a NewExpression with a constructor declared on an abstract class
IEnumerable <MainDto> entites = query.ToList();
```

**Comment by lbargaoanu** [comment]
That's not possible in EF6, our main use case. I don't know about EF Core. You can try to write a LINQ query that does what you want, without AM. If that works, you're welcome to try to implement that in AM. But perhaps it would be easier to use `Map` instead.

**Comment by Angelinsky7** [comment]
@lbargaoanu Thanks for you answer, i'll investigate and come back if i find a solution.
