### ISSUE TITLE
C# 9 Records support?

### ISSUE THREAD

**Issue by lloydjatkinson** [AutoMapper/AutoMapper#3499]
Will AutoMapper support records? How would that work?

**Comment by jbogard** [comment]
shrug.gif

**Comment by spydacarnage** [comment]
Positional records should work with a constructor.  Nominal ones are
something you can test right now if you download a preview of C#9.

**Comment by lbargaoanu** [comment]
Records are more about syntactic sugar. People have been writing such classes for years. AM works at runtime so it's not really relevant.

**Comment by spydacarnage** [comment]
The relevance I was wondering about is whether an init property would cause
issues. Not sure how the object is created and then assigned, hence the
suggestion to test it.

**Comment by jbogard** [comment]
Feel free to give it a go and let us know what you find!

**Comment by lbargaoanu** [comment]
All init properties must be set in the constructor.

**Comment by lbargaoanu** [comment]
I guess constructor mapping could be extended for init only properties. Today we don't use object initializers with `Map`.

**Comment by spydacarnage** [comment]
Well, for whatever reason, I can confirm that a map works for both
positional and nominal records, at least at the most basic level - I've not
gone into more complex scenarios, but I rarely need to use those, so I'll
leave other people to do that if they wish :)

**Comment by lbargaoanu** [comment]
Good to know!
