### ISSUE TITLE
comment: poor documentation

### ISSUE THREAD

**Issue by ruwentos** [AutoMapper/AutoMapper#3506]
I don't have a question (anymore), but a comment.

You guys have a very nice and handy product but your documentation is the worst I have seen for a long time.
Fortunately, it's not the only source of information, otherwise one would definitely miss out parts of the features.

The approach can be explained very clean, as demonstrated here: https://www.codementor.io/@zedotech/how-to-using-automapper-on-asp-net-core-3-0-via-dependencyinjection-zq497lzsq.

Please don't sell yourself short.

**Comment by lbargaoanu** [comment]
A PR is welcome.
