### ISSUE TITLE
Automapper 8.0 migration to Automapper 10.0 has breaking changes for Map method

### ISSUE THREAD

**Issue by zinov** [AutoMapper/AutoMapper#3508]
I am migrating a project to .Net Core 3.1, as part of the migration I needed to upgrade Automapper packages. I am passing parameters via Items property to some of my Mappers but now that option is no longer available.

`Claims = mapper.Map<List<UserClaimModel>>(source.Claims, options => { options.Items["createdBy"] = createdBy; options.Items["updatedBy"] = updatedBy; })`

But now the method Map is not receiving 2 arguments: **No overload for method 'Map' takes 2 arguments**

This is part of my ITypeConverter implementation

`public class UserForCreationDto22UserModel : ITypeConverter<UserForCreationDto2, UserModel>
    {
        IUserAppService _userAppService;
        private IHashingService _hashingService;

        public UserForCreationDto22UserModel(IUserAppService userAppService, IHashingService hashingService)
        {
            _userAppService = userAppService;
            _hashingService = hashingService;
        }

        public UserModel Convert(UserForCreationDto2 source, UserModel destination, ResolutionContext context)
        {
            try
            {
                var mapper = context.Mapper;
                var createdBy = context.Items["createdBy"] as string;
                var updatedBy = createdBy;
                var time = DateTime.Today;

                var username = source.Claims.First(x => x.ClaimType == AppClaimTypes.Username).ClaimValue;

                destination = new UserModel
                {
                    CreatedBy = createdBy,
                    UpdatedBy = updatedBy,
                    CreatedOn = time,
                    UpdatedOn = time,

                    Username = username,
                    Password = _hashingService.CreateHash(Guid.NewGuid().ToString()),
                    
                    Claims = mapper.Map<List<UserClaimModel>>(source.Claims, options => { options.Items["createdBy"] = createdBy; options.Items["updatedBy"] = updatedBy; })
                };
            }
            catch
            {
                return null;
            }

            return destination;
        }
    }`

Any advice on how can I accomplish the same thing with Automapper 10.0?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by zinov** [comment]
There is no clear documentation for each Automapper upgrades that points to the correct way

**Comment by lbargaoanu** [comment]
A PR is welcome.
