### ISSUE TITLE
ImappingAction IQueryAble

### ISSUE THREAD

**Issue by MEnzio** [AutoMapper/AutoMapper#3511]
hello there

im using  ImappingAction for di but face an issuse

my ImappingAction is below

```
  public class ArticleCommentVmMappingActions : IMappingAction<ArticleComment, ArticleCommentVm>
    {
        private readonly IApplicationUserManager _applicationUserManager;
        public ArticleCommentVmMappingActions(IApplicationUserManager applicationUserManager)
        {
            _applicationUserManager = applicationUserManager;
        }
        public void Process(ArticleComment source, ArticleCommentVm destination, ResolutionContext context)
        {
            var currentUserId = _applicationUserManager.CurrentUserId;
            if (currentUserId != null)
            {
                destination.createdByCurrentUser = source.CreatedUserId == currentUserId;
                destination.UserHasLiked = source.CommentLikes.Any(x => !x.IsDeleted && x.UserId == currentUserId);
            }
        }
    }
```

and im used it in my autommaper profilee

the problem i have is when i trying to map an` IQueryAble<ArticleComment>` with `ProjectTo<ArticleCommentVm>` Function the  auto mapper doest call my  ImappingAction

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Queryable-Extensions.html#supported-mapping-options

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Queryable-Extensions.html#parameterization

**Comment by MEnzio** [comment]
thank u

if i use parametrization  i need to change destination prop value base on other destination value how can i do this in automapper profile

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
