### ISSUE TITLE
UseDestinationValue() not working in in List<T>

### ISSUE THREAD

**Issue by tamirzamo** [AutoMapper/AutoMapper#3513]
I have in a mapper profile of
CreateMap<A_DTO, A> with UseDestinationValue for specific members.

When trying to Mapper.Map<List<A_DTO>, List<A>>(source, value), 
The UseDestinationValue() does not work. It simply sets with default of the type.

After adding a CreateMap<List<A_DTO>, List<A>> it returned to work as expected.

I don't know if it's a feature, but it feels like a bug...

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by tamirzamo** [comment]
Why? It seems to be a bug.
It stated in the documentation that we don't have to give List<T> Mapping config, only the T mapping config...
