### ISSUE TITLE
Add expected exceptions

### ISSUE THREAD

**Issue by MiBuena** [AutoMapper/AutoMapper#3515]
### Expected behavior

When I open to see AutoMapper method signatures, I would like to see what Exceptions the method might throw. 

### Actual behavior

Currently, the tag Exceptions does not exist for the following AutoMapper methods which I am currently using.

        TDestination Map<TSource, TDestination>(TSource source);
        IQueryable<TDestination> ProjectTo<TDestination>(IQueryable source, object parameters = null, params Expression<Func<TDestination, object>>[] membersToExpand);

### Steps to reproduce

```csharp
Just navigate to the method signature with F12.
```

**Comment by lbargaoanu** [comment]
A PR is welcome.
