### ISSUE TITLE
Operation could destabilize the runtime with ProjectTo and NHibernate

### ISSUE THREAD

**Issue by jameshollandusa** [AutoMapper/AutoMapper#3517]
This is a crazy one, but after upgrading from 10.0.0 to 10.1.0 a bunch of my ProjectTo calls starting throwing "Operation could destabilize the runtime" from within NHibernate. I've spent some time narrowing it down to a simple(ish) repro:

### Source/destination types

```csharp
public class NormalizationSegment
{
    public virtual long Id { get; set; }
    // When this is decimal I get the error, when it's decimal? it works
    public virtual decimal StartCharge { get; set; }
}

public class NormalizationSegmentModel
{
    public long Id { get; set; }
    public decimal? StartCharge { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<NormalizationSegment, NormalizationSegmentModel>();
});

config.AssertConfigurationIsValid();
```

### Expected behavior

No exception

### Actual behavior

A VerificationException is thrown with the text "Operation could destabilize the runtime." from the depths of NHibernate.

### Steps to reproduce

When the code executes, and there is data returned by the query, the exception is thrown during the materialization of the results. Changing the source type of the problematic property to be decimal? to match the destination type does not throw the exception.

```csharp
var mapper = config.CreateMapper();

using (var sessionFactory = CreateSessionFactory())
using (var session = sessionFactory.OpenSession())
using (var tx = session.BeginTransaction())
{
    var segments = session.Query<NormalizationSegment>();

    // This call throws VerificationError "Operation could destabilize the runtime"
    // (so long as rows are returned from the database)
    var results = mapper.ProjectTo<NormalizationSegmentModel>(segments)
        .ToList();

    tx.Commit();
}
```

### Additional configuration needed

```csharp
public static ISessionFactory CreateSessionFactory()
{
    return Fluently.Configure()
        .Database(MsSqlConfiguration.MsSql2012
            .ConnectionString(c => c.FromConnectionStringWithKey("TestDB")))
        .Mappings(m =>
            m.FluentMappings
                .AddFromAssemblyOf<Program>()
                .Conventions.AddFromAssemblyOf<Program>())
        .BuildSessionFactory();
}

public class NormalizationSegmentMap : ClassMap<NormalizationSegment>
{
    public NormalizationSegmentMap()
    {
        Id(x => x.Id);
        Map(x => x.StartCharge);
    }
}
```

**Comment by jameshollandusa** [comment]
Gist for the whole repro here: https://gist.github.com/jameshollandusa/6f2b713fb0213ce7ab91e36b8baea193

**Comment by lbargaoanu** [comment]
This looks like a problem with NHibernate. This works with EF6. It does fail in memory, but that's irrelevant. I can workaround it with `cfg.CreateMap<decimal, decimal?>().ConvertUsing(s=>s);`. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). It looks fine to me.
I guess we used to workaround it in our code. Maybe @jbogard  wants to keep doing that.

**Comment by lbargaoanu** [comment]
Or maybe it's a convenience feature in EF6 that NHibernate doesn't have. I'm guessing the query without AM works in NHibernate, because the compiler seems to add the cast. It's still a NHibernate specific workaround in the AM code, so I don't know.

**Comment by KostadinDoichev** [comment]
Something similar is happening when using automapper 10.1 in unit tests with XUnit and EfCore InMemory. I get an exception 

**System.InvalidProgramException : Common Language Runtime detected an invalid program**
It works ok with version 10.0. 

The problem doesn't show when tested with Npgsql and EfCore

**Comment by lbargaoanu** [comment]
Closing in favor of #3519.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by jameshollandusa** [comment]
Amazing -- you folks are stars :-) I can confirm the issue is resolved with the MyGet build.
