### ISSUE TITLE
EF Core integration tests

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#3521]
Anybody interested in EF Core is welcome to add a test project similar to AutoMapper.IntegrationTests. All existing integration tests use EF6. [Here](https://github.com/AutoMapper/AutoMapper/blob/f31e398a596438a939bf19d5bb97ed218124731d/src/IntegrationTests/IncludeMembers.cs#L13) is an example. Ideally, all existing tests would run on EF Core too.

**Comment by hannan-m** [comment]
Hey @lbargaoanu , would you please take a look [here](https://github.com/hannan-m/AutoMapper/tree/EfCore-Tests/src/IntegrationTests.Corel)? If this looks good I will create the pull request.

**Comment by jinjiulong** [comment]
test
