### ISSUE TITLE
Multiple matches for a destination property

### ISSUE THREAD

**Issue by BartjeD** [AutoMapper/AutoMapper#3523]
I've added a Github reproduction: https://github.com/BartjeD/Automapper_Bug_Report_10_1_1

The problem:
What happens is that since version 10.1.1 several mappings started reporting `mapping exceptions` in my unittests. Where in the previous version they didn't. And shouldn't.

Investigating:
In this case automapper reports a `mapping exception` because of an arbitrary value it gets from running an instance **method**. That is: A method named `GetXYZ` which it isn't supposed to execute during mapping. It's not supposed to be executed by the mapper because it's not tied to a property being mapped. It's just a regular instance method.

Seeing this I got curious. I posited that it might have something to do with the **method's name starting with `Get`**. Which might cause Automapper to mistakenly assume that the method is a property. 

Turns out that was the case.

Work-around:
After I changed the method name to `GenerateXYZ` the exception was remedied. 

Community notes:
If you updated and are encountering new mapping exceptions: verify whether Automapper is calling any methods whose names start with `Get` and consider renaming those methods until a patch is issued. 
This is obviously not feasible in many environments, in which case it would be better to postpone updating until a patch is issued.

**Comment by lbargaoanu** [comment]
That's by design.

**Comment by BartjeD** [comment]
Have you looked at the repro and issue?

Because as I wrote: It's certainly not expected behaviour for me, and isn't how automapper worked in the past either.
Nor did I see this change documented anywhere. Hence me taking the time to report an issue.

@lbargaoanu @jbogard

**Comment by lbargaoanu** [comment]
We have method mapping since forever, but I think your point is that when both a property and a method match, it seems the method is preferred. You can disable method mapping with `ShouldMapMethod`.
@jbogard That seems to me like an invalid configuration. I think we should just throw.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
