### ISSUE TITLE
Suggestion: Rename IConfigurationProvider interface to prevent confusion

### ISSUE THREAD

**Issue by IanKemp** [AutoMapper/AutoMapper#3524]
It's named identically to the [`Microsoft.Extensions.Configuration.IConfigurationProvider`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.configuration.iconfigurationprovider) interface, which most people are going to be far more familiar with.

I suggest `IMappingConfigurationProvider` or even just `IMappingConfiguration`.

**Comment by lbargaoanu** [comment]
That seems like too big of a breaking change. You can just use the class instead.
