### ISSUE TITLE
Expression of type 'TInterface' cannot be used for parameter of type 'TConcrete' (Parameter 'arg1')

### ISSUE THREAD

**Issue by anuith** [AutoMapper/AutoMapper#3526]
### Bug report

After updated the NuGet package to version 8.1.0 the call of method `IMapper.map<TInterface>()` for type `TInterface` that was mapped with `IMappingExpression<TModel, TInterface>.As<TConcrete>()` breaks and throws exception.

#### To Reproduce
1. Install NuGet package `AutoMapper.Extensions.Microsoft.DependencyInjection` version **8.1.0**
2. Create two classes `TConcrete`, `TInterface` and an interface `TInterface` with `TConcrete` implements `TInterface`
3. Create mapping in a profile class with `CreateMap<TModel, TInterface>().As<TConcrete>();`
4. Use `IMapper.Map<TInterface>(model)` where `model` is an instance of `TModel`.

#### Expected Behavior
The output of `IMapper.Map<TInterface>(model)` should be an instance of `TConcrete`.

#### Actual Behavior
The program throws `ArgumentException` with message :

> Expression of type 'TInterface' cannot be used for parameter of type 'TConcrete' (Parameter 'arg1')

#### Notes
The program runs correctly when revert the NuGet package to version **8.0.1**

**Comment by lbargaoanu** [comment]
Also try the [MyGet](https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.Microsoft.DependencyInjection) build.

**Comment by anuith** [comment]
> A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

Please try running my code on [.NET Fiddle](https://dotnetfiddle.net/S824xK)

----
> Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

I tried installing the package from MyGet and the result is the same.

----
I also tried using only [AutoMapper](https://www.nuget.org/packages/AutoMapper) version 10.1.1 and it's also break. But with version 10.0.0 it works correctly.

**Comment by lbargaoanu** [comment]
`As` redirects the map, but you're missing the map to redirect to, `TModel` => `TConcrete`. If you don't need the second map, just use `CostructUsing`.

**Comment by lbargaoanu** [comment]
@jbogard I say let's throw here in 11.0.

**Comment by jbogard** [comment]
@lbargaoanu I agree, this looks like accidental behavior
