### ISSUE TITLE
Primary keys not being mapped correctly

### ISSUE THREAD

**Issue by zyofeng** [AutoMapper/AutoMapper#3527]
ClientApplicationId comes back different from original id, downgrading to 8.0.1 resolves the issue.

    public class AutoMapperTests : TestBase
    {
        [Fact]
        public async Task MappingTest()
        {
            var mapper = ServiceProvider.GetRequiredService<IMapper>();
            var id = Guid.NewGuid();
            await ApplicationDbContext.ClientApplications.AddAsync(new ClientApplication { ClientApplicationId = id });
            await ApplicationDbContext.SaveChangesAsync();
            var mappedApplication = await ApplicationDbContext.ClientApplications.ProjectTo<ClientApplicationTestModel>(mapper.ConfigurationProvider).FirstOrDefaultAsync();

            Assert.Equal(mappedApplication.ClientApplicationId, id);
        }
    }

    public class ClientApplicationTestModel
    {
        public Guid? ClientApplicationId { get; set; }
    }

    public class ClientApplicationProfile : Profile
    {
        public ClientApplicationProfile()
        {
            CreateMap<ClientApplication, ClientApplicationTestModel>();
        }
    }

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.Microsoft.DependencyInjection) build. If that doesn't work, see #3521. Open a PR with a failing test.

**Comment by lbargaoanu** [comment]
We''ll take a look again with a proper repro.
