### ISSUE TITLE
Simpler Mapping

### ISSUE THREAD

**Issue by eluchsinger** [AutoMapper/AutoMapper#3528]
I usually want to simply map a source property to a destination property. To achieve this, I believe I will have to write the following code or similar:

```csharp
CreateMap<SrcObject, DestObject>()
                .ForMember(dest => dest.DestProperty, 
                           opts => opts.MapFrom(src => src.SrcProperty));
```

Now, in my opinion, that's quite verbose (the `opts => opts.MapFrom` part) for an action I have to do almost all of the time. Isn't it possible to adjust the Syntax for this Use Case? You don't have to change the whole API for this, but you could offer an extension method like this one to provide a cleaner and less verbose way to simply map a property `A` to a property `B`*:

```csharp
public static class MappingExtensions
{
    public static IMappingExpression<TSrc, TDest> SimplyMapTo<TSrc, TDes, TMember>(this IMappingExpression<TSrc, TDest> mappingExpression, Expression<Func<TDest, TMember>> destinationExpression, Expression<Func<TSrc, TMember>> sourceExpression)
    {
        return mappingExpression.ForMember(destinationExpression, opts => opts.MapFrom(sourceExpression));
    }
}
```

```csharp
 CreateMap<SrcObject, DestObject>()
       .SimplyMapTo(dest => dest.DestProperty, src => src.SrcProperty);
```

\* This is a quick mockup and maybe you can find a better way to do this and a better name (or maybe not a new name at all).

**Comment by lbargaoanu** [comment]
I my view, not every little helper needs to be inside AM, but @jbogard might see it differently.

**Comment by eluchsinger** [comment]
@lbargaoanu of course, it seems like a little helper. But this is probably the most used function of this library, and if we have hundreds of lines of simply mapping property A to property B, that makes a huge difference in speed, in readability and simplicity.

Imagine you would have to initialize every string in C# with `new string("blabla")`. Of course you can do that. The same could be said about the new `record` keyword in C# 9. It's a little helper with a big impact. It's all about usability.

**Comment by lbargaoanu** [comment]
@jbogard will reopen it if he sees it your way.

**Comment by jbogard** [comment]
Yeah I'm not sure, it's a simpler syntax to be sure, but questions *will* inevitably come up:

- Can I combine this with the more complex version?
- What if the types are different? This uses the same generic parameter for both members
- What about other simplifications?

I'd rather not introduce ambiguity in the configuration API, even if it simplifies the syntax.

**Comment by floppydisken** [comment]
I was about to create a PR suggesting simplifications like this. I've done my own implementation of Ignoring a member as well as easy mappings for members. I've seen examples around the great big interwebs doing the same. 

Could we perhaps provide a separate "simplification" nuget package with simplications like this, and leave the core be?

**Comment by lbargaoanu** [comment]
You should start one. When you have more than a few, we can add a link to it and point people with similar requests that way.

**Comment by floppydisken** [comment]
Deal
