### ISSUE TITLE
Method mapping instead of property mapping

### ISSUE THREAD

**Issue by ArnaudB88** [AutoMapper/AutoMapper#3530]
Hi,
Since a recent release we get different behavior when mapping two types:

### Source/destination types

```csharp
public class WFDelegation //Source type (of external dll)
{
   //other properties
   public string ProcDefIDS { get; set; }

   public string[] GetProcDefIDs();//implementation invisible of this method
}

public class DelegationDto //Destination type
{
   //other properties
   public string ProcDefIDS { get; set; }
}

```

### Mapping configuration

```csharp
CreateMap<WFDelegation, DelegationDto>();
```

### Expected behavior

The source object has ProcDefIDS as an empty string.
We expect destination object ProcDefIDS to be also an empty string.
I would assume the property -> property mapping has a higher priority than the GetProperty() -> property mapping.

### Actual behavior
Using version 10.1.1

destinationDto.ProcDefIDS = "System.String[]"

### Steps to reproduce

```csharp
var result = Mapper.Map(wfDelegation, delegationDto);
```

PS: please don't judge me on the naming in the source class, I am not the developer of that code ;)

**Comment by lbargaoanu** [comment]
#3523
