### ISSUE TITLE
Mapping to nullable Guid field does not seem to work in 8.1.0

### ISSUE THREAD

**Issue by zyofeng** [AutoMapper/AutoMapper#3534]
Repo to replicate the issue, the same code works in 8.0.1

https://github.com/zyofeng/AutoMapper.Tests

**Comment by lbargaoanu** [comment]
That works for me. Try clearing the nuget cache.

**Comment by zyofeng** [comment]
Are you sure? It doesn't work I have production build in Azure that returns invalid guid as IDs. Reverting the 
AutoMapper.Extensions.Microsoft.DependencyInjection from 8.1.0 to 8.0.1 worked

**Comment by lbargaoanu** [comment]
Again, clear the nuget cache. Or add AM 10.1.1 explicitly to your project. @jbogard Maybe a new release for the DI package?

**Comment by zyofeng** [comment]
Tried clearing the cache in Visual Studio 2019 and still fails
![image](https://user-images.githubusercontent.com/23351416/98776799-8577b600-2454-11eb-8841-bfca600f8cc0.png)

Adding reference to AM10.1.1 does solve the problem but not really ideal :(

**Comment by lbargaoanu** [comment]
Meanwhile, you can use the MyGet build https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.Microsoft.DependencyInjection.

**Comment by zyofeng** [comment]
Thanks, I will manually add reference for now, I don't want to alter my Azure Pipelines and introduce myget feed.
