### ISSUE TITLE
CreateProjection

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#3537]
To be used instead of `CreateMap` for the subset of the configuration API that works with `ProjectTo`. Calling `Map` for those types would throw. This would allow to skip building the map expression on `Seal`. Alternatively, skip the API part and just have a flag on the map.

**Comment by jbogard** [comment]
I think that makes sense, it's quite confusing for folks to have to remember which APIs work or not. I wonder if this would also be needed for say dictionary/dynamic maps

**Comment by lbargaoanu** [comment]
Well, those are _dynamic_, right? :)
