### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by klahnakoski** [AutoMapper/AutoMapper#3538]
### Version: x.y.z

10.1.1

### Expected behavior

`AssertConfigurationIsValid()` will either run silently, or raise a descriptive exception. 

### Actual behavior

```
System.AggregateException
  HResult=0x80131300
  Message=One or more errors occured
  Source=AutoMapper
  StackTrace:
    at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
    at AutoMapper.ConfigurationValidator.AssertConfigurationExpressionIsValid(IEnumerable`1 typeMaps)
    at AutoMapper.MapperConfiguration.AssertConfigurationIsValid()
    at <removed>

  This exception was originally throw at this call stack:
     [External Code]
```

(I had to type the above manually, please forgive typos)

### Steps to reproduce

Can not say, my apologies.

**Comment by klahnakoski** [comment]
My C# is still a bit rusty:  I am guessing breaking down the AggregateException into the exceptions it contains will be sufficient.  It seems [the Linq query](https://github.com/AutoMapper/AutoMapper/blob/565c9634e2a0b487c9b25bca20f67a43e0ee06a3/src/AutoMapper/ConfigurationValidator.cs#L55) has no try/catch to perform the breakdown.

**Comment by lbargaoanu** [comment]
That's the standard way of throwing more than one exception.

**Comment by klahnakoski** [comment]
>  the standard way of throwing more than one exception

@lbargaoanu is there a plan to unpack those exceptions so AutoMapper can tell me what they are?  Or is the next step for me to bring in the AutoMapper source code so I may use the debugger?

**Comment by jbogard** [comment]
The `AggregateException` already allows you to do this as a user. It contains a collection of exceptions.
