### ISSUE TITLE
Automapper for .Net 5

### ISSUE THREAD

**Issue by wiwichu** [AutoMapper/AutoMapper#3539]
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by wiwichu** [comment]
When will automapper support .Net 5.0?

**Comment by jbogard** [comment]
It already does, and has supported it ever since `netstandard2.0`. So technically, it has since the first alpha 😆
