### ISSUE TITLE
Slow mapping on initial load

### ISSUE THREAD

**Issue by deep8317** [AutoMapper/AutoMapper#3540]
I have an Asp.Net Core 3.1 API project with more than 162 maps (with .ReverseMap()). All maps are defined in `MappingProfile` class and registered using `services.AddAutoMapper(typeof(Startup).Assembly);`

 `_mapper.Map<List<DataModel>>(models)` takes about 25 seconds to complete the mapping of a very small collection (hardly 1o items) when the first request is received. On consecutive request(s), it works fines without any problem.

Am I missing something or it's by design?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build. But other than that, we need a repro. Like [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/Bug/MapAtRuntimeWithCollections/MapAtRuntimeWithCollections.cs).

**Comment by jbogard** [comment]
I think you'd need to profile this to see where the time is being spent.

**Comment by deep8317** [comment]
@jbogard Do you mean to write `CreateMap<Source, Destination>()` in a constructor of a derived class of `Profile`?

**Comment by jbogard** [comment]
No, use a profiler tool like DotTrace to see where the slowdown is. I can't debug or profile this myself.

**Comment by deep8317** [comment]
@jbogard thanks. I did it for two calls which are comparatively very slow. Please see the below screenshots. 

![Mapper issue 1](https://user-images.githubusercontent.com/59237447/100534425-ad00a980-31dc-11eb-9612-e6e568117abe.PNG)

![Mapper issue 2](https://user-images.githubusercontent.com/59237447/100534430-b12cc700-31dc-11eb-9de1-e5ddbcabaee3.PNG)

**Comment by lbargaoanu** [comment]
Compare the execution plans. What's the difference, is it size or smth else? If it's size, it's the number of properties or smth else?

**Comment by deep8317** [comment]
@lbargaoanu Can you please elaborate a little bit more on how to compare execution plans? Thanks!

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by deep8317** [comment]
@lbargaoanu compared the execution plans before and after initial load, they look the same in size (with the same number of lines of code). Any idea what else could this issue?

**Comment by lbargaoanu** [comment]
Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by deep8317** [comment]
@lbargaoanu For this project, an entity may have 65+ navigation properties (as collections) and other 80+ properties. It wouldn't feasible to make a gist using the client's code. 

I have approximately 165+ CreateMap() calls for various combinations. Had some of those been commented out (maybe half), the performance seems to improve. Do you feel number maps can cause the issue? If so, how can that be managed if AutoMapper needs to be integrated with a giant API project?

**Comment by lbargaoanu** [comment]
You "model" is clearly broken and of no use to a human being :) Of course you can make a repro, as some fellow did [here](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/Bug/MapAtRuntimeWithCollections/MapAtRuntimeWithCollections.cs). I did not say it's easy. You can try setting `MaxExecutionPlanDepth` to 0. How you handle a situation such as yours has been discussed at length before, search the older issues.

**Comment by deep8317** [comment]
@lbargaoanu Well, some models with only four properties also seem to be very slow on initial load (about 18sec). Setting up `MaxExecutionPlanDepth` to 0 didn't make any difference. Can you please share some of those issues that I can refer to? I went over a couple but didn't find any solution regarding my situation.

**Comment by lbargaoanu** [comment]
Repro. Otherwise ask a question on SO or get a more experienced colleague to help you.

**Comment by jbogard** [comment]
You’ll need to get a profiler involved at this point. Something like DotTrace can tell you where the slowdown is.

**Comment by lbargaoanu** [comment]
@jbogard It's the JIT. Check the picture above. It's the same old issue, you can always break AM with a big enough execution plan. But I don't see how you could do that with a model that actually makes sense. Generating smth from a DB, yes, that could do it.

**Comment by deep8317** [comment]
@jbogard I did it. I have attached the screenshots above. I am not sure what else could be done at this point. Do you suggest anything else to resolve this further?

**Comment by jbogard** [comment]
Oh yeah there it is...yeah that's not our code at this point, it's .NET. Nothing we can do, except see how big the execution plan is and see if there's ways to simplify it.
