### ISSUE TITLE
Nested relationships

### ISSUE THREAD

**Issue by Joellao** [AutoMapper/AutoMapper#3541]
### Version: 10.1.1
 
.NET 5
AutoMapper 10.1.1
AutoMapper.Extensions.Microsoft.DependencyInjection 8.1.0

### Expected behavior

When projecting, it should fetch only the columns refered in the DTO like in **.net core 3.1**
### Actual behavior
All the columns are being fetched and then mapped

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
