### ISSUE TITLE
Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by wensaint** [AutoMapper/AutoMapper#3542]
after update to v10.1.1, error happen at times.
roll back to 10.0.0, the error gone

AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Object -> biHallDto
System.Object -> Wensaint.MuseAppointment.Services.biHallDto
   at lambda_method(Closure , Object , biHallDto , ResolutionContext )

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by Atalaybars** [comment]
I'm having the same issue as well

**Comment by Atalaybars** [comment]
Have a look at this: https://gist.github.com/Atalaybars/6272540eb374bb8ccb1b961c0e5a1926

**Comment by gstrit** [comment]
I have the issue :
Mapping types:
Object -> PagedResultViewModel`1

Rollback fixed the issue
