### ISSUE TITLE
Referencing AutoMapper in Xamarin.Forms application causes MSB3277 to appear.

### ISSUE THREAD

**Issue by maxkoshevoi** [AutoMapper/AutoMapper#3543]
Adding this NuGet to Xamarin.Forms application causes warning to appear when building Android project

### Expected behavior

Project can be built without warnings

### Actual behavior

Warning appears:
```
MSB3277: Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.
```

### Steps to reproduce

1) Create blank Xamarin.Forms project and update all NuGets
2) Build `.Android` project. No warnings will appear.
3) Add `AutoMapper` NuGet
4) Build `.Android` project. `MSB3277` will appear

From binlog:
![image](https://user-images.githubusercontent.com/6609929/101266949-56efb100-375c-11eb-9b8a-8256dddf71a0.png)

[Sample app.zip](https://github.com/AutoMapper/AutoMapper/files/5647976/App5.zip)

**Comment by lbargaoanu** [comment]
We use the latest so I don't know what to tell you about that. Maybe try a Xamarin forum.

**Comment by Tasteful** [comment]
I havent work anyting with Xamarin, but this sounds like a binding-redirects problem. See https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions
