### ISSUE TITLE
 ICollection<> to List<> default mapping

### ISSUE THREAD

**Issue by fialo4ka** [AutoMapper/AutoMapper#3544]
### Source/destination types

```csharp

// source
    public class SomeSourceModel
    {
        public virtual ICollection<PsaCode> PsaCodes { get; set; }
    }
//destination types here
    public class Model
    {
        public List<Code> Codes { get; set; }
    }

```

### Mapping configuration

```csharp

CreateMap<SomeSourceModel, Model>()
//I add it now, to have mapping :(
                .ForMember(dest => dest.Codes, opt => opt.MapFrom(src => src.Codes.ToList()))

```
### Expected behavior

Early worked perfectly mapping from ICollection<> to List<> without any additional code...

### Actual behavior

After update to c# 9 mapping from ICollection<> to List<> not work any more by default, only with additional ToList() mapping...

### Steps to reproduce

```csharp

//work with addition defined mapping without give null value
var mappedModel = Mapper.Map<Model>(getFromDBSomeSourceModel(id));

```
With ProjectTo work ok...

**Comment by lbargaoanu** [comment]
I don't see it. 
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by fialo4ka** [comment]
Hello, sorry for so long unswer.
I found the problem:
using DbContextOptionsBuilder optionsBuilder I add

`   optionsBuilder.UseLazyLoadingProxies();`

then mapping has behavior as I describe,
removed it. all again work correctly.
