### ISSUE TITLE
Mapping with a constructor doesn't work if a target property is mapped using MapFrom

### ISSUE THREAD

**Issue by thomaslevesque** [AutoMapper/AutoMapper#3545]
### Source/destination types

```csharp
record Foo(int Id, string Name, string Description);

record FooDto(int Id, string Name, string Text);
```

(I'm using records here, but I don't think it matters)

### Mapping configuration

```csharp
    var mapper = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<Foo, FooDto>()
            .ForMember(dto => dto.Text, o => o.MapFrom(f => f.Description));
    }).CreateMapper();
```

### Expected behavior

Should map successfully

### Actual behavior

> **ArgumentException**: FooDto needs to have a constructor with 0 args or only optional args. (Parameter 'type')

### Steps to reproduce

```csharp
    var foo = new Foo(123, "hello", "test");
    var dto = mapper.Map<FooDto>(foo);
```

### Additional remarks

It works fine if `FooDto.Text` is renamed to `Description` and I remove the `ForMember(... MapFrom(...))` configuration, so I'm pretty sure that's what causing the problem.

**Comment by lbargaoanu** [comment]
You need `ForCtorParam`.

**Comment by thomaslevesque** [comment]
Oh! I had never noticed that method before. Thanks!
