### ISSUE TITLE
Indicate which Profile doesn't have a parameterless constructor

### ISSUE THREAD

**Issue by icnocop** [AutoMapper/AutoMapper#3546]
When scanning an assembly to add multiple `Profile` classes when configuring AutoMapper, and a `MissingMethodException` is thrown because a `Profile` doesn't have  parameterless constructor, I'd like to know which `Profile` type caused the exception.

```csharp
[TestMethod]
public void TestMethod1()
{
	var config = new MapperConfiguration(c =>
	{
		c.AddMaps(typeof(TestProfile));
	});
}

public class TestProfile : Profile
{
	public TestProfile(IMapper mapper)
	{
	}
}
```

In this example, the following exception is thrown:
```
System.MissingMethodException: No parameterless constructor defined for this object.
  Stack Trace: 
    RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
    RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
    RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
    Activator.CreateInstance(Type type, Boolean nonPublic)
    Activator.CreateInstance(Type type)
    MapperConfigurationExpression.AddProfile(Type profileType)
    MapperConfigurationExpression.AddMapsCore(IEnumerable`1 assembliesToScan)
    MapperConfigurationExpression.AddMaps(IEnumerable`1 typesFromAssembliesContainingMappingDefinitions)
    MapperConfigurationExpression.AddMaps(Type[] typesFromAssembliesContainingMappingDefinitions)
    <>c.<TestMethod1>b__0_0(IMapperConfigurationExpression c) line 15
    MapperConfiguration.Build(Action`1 configure)
    MapperConfiguration.ctor(Action`1 configure)
    UnitTest1.TestMethod1() line 13
```

`MissingMethodException`'s `ClassName` and `MemberName` properties are inaccessible (and are actually null).

If the caller catches the exception, the exception doesn't contain the full type and assembly file path that caused the issue.

The full type and assembly file path would help narrow down which specific class caused the error, especially in the case with many Profiles in many assemblies.

I'm using .NET Framework 4.7.2 and AutoMapper 10.1.2-alpha.0.2.

Thank you. 🤟

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by icnocop** [comment]
You are correct; I ran the same test in `.netcoreapp3.1` and the exception's message indicates the type:

`System.MissingMethodException: No parameterless constructor defined for type 'MyUnitTestProject.UnitTest1+TestProfile'.`

Thank you. 🙌
