### ISSUE TITLE
Extend mapping for interfaces

### ISSUE THREAD

**Issue by kovman** [AutoMapper/AutoMapper#3549]
Hi,

Thank you for the great library.

Please, **consider this scenario**
The domain of application is for me a black box. I have only access to domain interfaces. Interfaces have in many cases only getters. I need to map an object with multiple levels of nested objects including collections where objects are also represented only by interfaces.

**What have I tried**
I found out, it is possible to convert to and from an interface. Automapper creates a proxy class. Great. But setters are not part of the interface. This doesn't help me.
I have my own implementations of interfaces. Those classes have public setters. I can use `.ConstructUsing`. Works, but I have to manage all mapping myself. Not a big advantage to use Automapper here.
I've tried mapping class to class and casting each object after conversion in the collection into the interface... and it went to really dirty solution.

**My suggestions**
1. Introduce `.ReturnAs<{class},{interface}>()`
```
class A {public string Name {get;set;}}
interface IB {public string Name {get;}}
class B : IB {public string Name {get;set;}}
...
CreateMap<A,B>().ReturnAs<B,IB>()
```
The user might have a possibility to specify `ReturnAs` multiple times, as your class can implement multiple interfaces.

2. Introduce `Create<{interface},{class}>()`.
```
class A {public string Name {get;set;}}
interface IB {public string Name {get;}}
class B : IB {public string Name {get;set;}}
...
CreateMap<A,IB>().Create<IB,B>()
```
Mapping is then driven by a class definition, but the interface is used for mapping.

Thanks
Lubomir

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow. But check [the docs](https://docs.automapper.org/en/latest/Mapping-inheritance.html#as).

**Comment by jbogard** [comment]
I wouldn't use AutoMapper for this. If you didn't use AutoMapper, how would the domain be mutated? If everything is a read-only interface?
