### ISSUE TITLE
Proposal for mapping to members initialized to Enumerable.Empty<T>

### ISSUE THREAD

**Issue by wagich** [AutoMapper/AutoMapper#3550]
This is a second look at the problem in #3365 and proposing a simple fix for it.

To summarize: in .NET Core 3.1, `Enumerable.Empty<T>` returns an `System.Linq.EmptyPartition<T>` which does not implement `ICollection<T>`. Since existing values for enumerable destinations are cast to `ICollection<T>`, an exception is thrown.

If we change the generated expression tree to not do a hard cast (`(T)value` represented by `Expression.Convert`) on the destination, but instead do `value as T`, represented by `Expression.TypeAs`, the destination will have a value of `null` if it's not assignable to `ICollection<T>`. From there we'll take the same code-path as if we didn't initialize the property at all, which means initializing it with a new list and then adding the values.

You can see the change in context here: https://github.com/wagich/AutoMapper/commit/b6b24b554eda014baff3a22894d6dd8c6a73e065. I'd be happy to create a PR…

### Source/destination types

```csharp
public class Source
{
    public int[] Values { get; set; } = Array.Empty<int>();
}

public class Destination
{
    public IEnumerable<int> Values { get; set; } = Enumerable.Empty<int>();
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>();
```

### Expected behavior

Mapping to a property that was initialized to `Enumerable.Empty<T>()` in .NET Core 3.1 should work.

### Actual behavior

Throws an `InvalidCastException`:
Unable to cast object of type 'System.Linq.EmptyPartition\`1[System.Int32]' to type 'System.Collections.Generic.ICollection\`1[System.Int32]'.

### Steps to reproduce

```csharp
var config = new MapperConfiguration(config =>
{
    config.CreateMap<Source, Destination>();
});
var mapper = config.CreateMapper();

var src = new Source
{
    Values = new[] { 1, 2 }
};
var existingDest = new Destination();
existingDest = mapper.Map(src, existingDest);
```

**Comment by lbargaoanu** [comment]
We're not going to work around in AM for problems elsewhere. But of course you can do that in your own code.

**Comment by wagich** [comment]
@lbargaoanu 
However I look at it, I can't see where this is a problem in the Framework and not a problem in AutoMapper… 

The only guarantee `IEnumerable` makes is that it's enumerable – by accident `Enumerable.Empty` returned something that could be cast to an `ICollection` but that is completely internal behaviour that shouldn't and obviously can't be depended on.

So IMO AutoMapper can and should try its best to use an existing collection, but a property of type `IEnumerable<T>` can only ever be reliably replaced whole-sale, therefore it should fall back to this behaviour if the other assumptions failed. This fallback behaviour is already present (by checking `IsReadOnly`), it just doesn't handle all cases correctly.

Compounding the problem, this error occurs at runtime after the map validation indicated no errors (`config.AssertConfigurationIsValid()` didn't throw). If this is really the problem of AutoMapper not being able to reliably map to `IEnumerable` properties, maybe this could be catched in mapping validation?

**Comment by lbargaoanu** [comment]
Read again more carefully the issue you linked to.

**Comment by wagich** [comment]
I did. The problem is that the conclusion seems to me to be incorrect…

Compare these two property declarations on the destination:
- `public IEnumerable<int> Values { get; set; } = Enumerable.Empty<int>(); // throws InvalidCastException` 
- `public IEnumerable<int> Values { get; set; } = Array.Empty<int>(); // maps correctly` 

There is no difference in API surface _and_ there is no difference in mapping behaviour/execution plan. Both "collections" can't be changed – but one works and one doesn't. 
- The array one works because there is a fallback detecting that an existing collection can't be changed, it is then recreated as a `List<T>`. 
- The empty enumerable doesn't work because the fallback is not detecting it.

I propose we extend the fallback behaviour to any class that can't be cast to `ICollection<T>` which would prevent this kind of runtime error entirely. If the scope of this is too broad, one could even check for `EmptyPartition<T>` in particular…

**Comment by lbargaoanu** [comment]
That's technically wrong (but backward compatibility). You cannot map _into_ a read-only collection. And you propose to add even more weirdness. You pass the wrong parameters to a function and instead of changing the parameters you want to change the function. And that's because you don't want to pass `null` or `Array.Empty`. You want to pass a read-only collection so AM can replace it for you. _Really?_ Come on...

**Comment by wagich** [comment]
I see, so your position is that you don't want to have the functionality of mapping to readonly collections (or similar collections) at all, it's just there because you can't remove it because of backcompat? If so I see your point more clearly. 

The issue is cropping up because with non-nullable types, you really need to initialize non-null properties to something – and the recommendation, as I understand it, is to use `Enumerable.Empty` as a kind of "null value for enumerables". There also seems to be an effort to special-case this throughout LINQ etc. so to me it makes sense from a performance perspective.

**Comment by wagich** [comment]
In any case, thank you for taking a look and expanding on your reasoning!

**Comment by lbargaoanu** [comment]
cc @jbogard

**Comment by Tasteful** [comment]
Sounds as the same issue that I was having with the readonly collections, see #1973

**Comment by wagich** [comment]
@Tasteful It looks like mapping to readonly collections (or to be exact, replacing them if neccessary) is working since bf2bf918a497735f967d8d2fba1ac12088ed38e8 where a check for `ICollection<T>.IsReadOnly` with a fallback was introduced. This is very closely related, in essence the fallback doesn't cover all enumerable types.

**Comment by jbogard** [comment]
The proposed changed is small (we have to make an assumption that if you want to map into `IEnumerable<T>` that you REALLY have an `ICollection<T>`), I don't have a problem with that.

However, I still don't quite understand the point of initializing to an empty enumerable. Are you getting compiler warnings that values can be null because they're getting populated by LINQ providers and not code? This seems like a problem with the tooling, not AutoMapper

**Comment by lbargaoanu** [comment]
In fact a significant part of AM is dedicated to some kind of null checking. If you have both `AllowNullDestinationValues` and `AllowNullCollections` set to `false`, you'll never have `null` in the destination. So, in this context, the guideline is meaningless.

**Comment by wagich** [comment]
@jbogard If I declare a property `public IEnumerable<int> Values { get; set; }` and I'm using nullable types, I need to either initialize it using `default!` (which goes against the non-nullability) or by assigning an empty collection. And to my knowledge, the most lightweight and preferred way is to use `Enumerable.Empty`.

I chose `IEnumerable<T>` for the property because I really want the client code to just foreach over it and not do anything else. When AutoMapper creates the object for me with `mapper.Map<Destination>(src)` it works already, but sometimes I have an instance that I need to map into and this is where I'm getting hung up. 

There is also the bit of weirdness there in that changing the implementation type IMHO shouldn't break the mapping at runtime.

In essence, I'm proposing to extend the fallback that is already present to cover all possible cases that `EnumerableMapper` says it can handle – because it checks for enumerability of the target, not whether it implements `ICollection<T>`.

**Comment by lbargaoanu** [comment]
A better way forward in my view would be to never map _into_ `IEnumerable`. You'd have to set `UseDestinationValue`. Why bother at all with these runtime checks.

**Comment by jbogard** [comment]
I like that better - stop making any assumptions about the value set. It's odd that the `IsMatch` type does not match the value checked in `MapExpression`.

**Comment by lbargaoanu** [comment]
I'll look into it. A PR on master as this time is not terribly useful.

**Comment by wagich** [comment]
Not mapping at all seems to me to be a bit excessive and not that user-friendly – but it certainly would clear up the situation :)

**Comment by jbogard** [comment]
@wagich mapping *into* `IEnumerable` means we stop making an assumption about what you initialized the field to. We only map to a new collection. In your case, we would always replace the `IEnumerable`.

The proposed change has the potential problem of breaking folks that exposed say `IEnumerable` but had `List<T>` as the initialized value and expected us to be able to use the field value. But I'm OK with that.

One other thing to consider is `IEnumerable` is not that useful by itself - you can iterate over it but to do anything else you pull in LINQ. Why not `ReadOnlyList` etc

**Comment by wagich** [comment]
Actually, it wouldn't change existing non-throwing/working behaviour at all, it would only allow things to work that previously threw an `InvalidCastException`.

Right now, when the target is an interface and `EnumerableMapper` is used, the generated expression contains this:
```c#
var passedDestination = (ICollection<int>)(dest == null ? null : typeMapDestination.Values);
var collectionDestination = (passedDestination == null || passedDestination.IsReadOnly)
    ? (ICollection<int>)new List<int>()
    : passedDestination;
```

With my proposed change, the first line would instead be
```c#
var passedDestination = (dest == null) ? null : typeMapDestination.Values as ICollection<Foo>;
```
so if the target collection wasn't assignable to `ICollection<T>`, `passedDestination` would get a value of `null` (instead of throwing). After that, the null-check in the second statement would create a new `List<T>` and populate it. Anything that was already castable to `ICollection<T>` passes through as normal.

Full mapping expression for reference (ReadableExpressions output):
````c#
(src, dest, ctxt) =>
{
    Destination typeMapDestination;
    return (src == null)
        ? null
        : {
            typeMapDestination = dest ?? new Destination();
            try
            {
                var resolvedValue =
                {
                    Source src;
                    return (((src = src) == null) || false) ? null : src.Values;
                };

                var propertyValue = (IEnumerable<Foo>)((resolvedValue == null)
                    ? (ICollection<Foo>)new List<Foo>()
                    : {
                        var passedDestination = (ICollection<int>)(dest == null ? null : typeMapDestination.Values);
                        var collectionDestination = ((passedDestination == null) || passedDestination.IsReadOnly)
                            ? (ICollection<Foo>)new List<Foo>()
                            : passedDestination;
                        collectionDestination.Clear();

                        var sourceArrayIndex = 0;
                        while (true)
                        {
                            if (sourceArrayIndex < resolvedValue.Length)
                            {
                                var item = resolvedValue[sourceArrayIndex];
                                collectionDestination.Add((item == null) ? (null == null) ? null : null : item);
                                sourceArrayIndex++;
                            }
                            else
                            {
                                break;
                            }
                        }

                        return collectionDestination;
                    });
                typeMapDestination.Values = propertyValue;
            }
            catch (Exception ex)
            {
                throw new AutoMapperMappingException(
                    "Error mapping types.",
                    ex,
                    AutoMapper.TypePair,
                    TypeMap,
                    PropertyMap);

                return null;
            }

            return typeMapDestination;
        };
}
````
