### ISSUE TITLE
ProjectTo it does not work anymore with NH 5.3 (at least in some scenario)

### ISSUE THREAD

**Issue by pasqualedante** [AutoMapper/AutoMapper#3551]
I have migrated my projects from NHibernate 5.2.6 to NHibernate 5.3.5 and from Automapper 9.0.0 to Automapper 10.1.1 and now ProjectTo not retun the same records of NHibernate query. In particular, this happens when the DTO in use uses the same naming conventions (of automapper) that I have always used. I am attaching a NUnit testcase here for fast review. I have read the various release notes from version 9.0 onwards and have not found any related breacking change mentioned: did I miss something?

[Automapper.zip](https://github.com/AutoMapper/AutoMapper/files/5760462/Automapper.zip)

**Comment by lbargaoanu** [comment]
I don't see anything wrong. If you really think there's smth wrong, open a PR with a failing test. Look for tests with `ProjectTo` and write smth similar for your use case. Without NH, of course.

**Comment by pasqualedante** [comment]
@lbargaoanu sorry, did you see the failing unit test that I attached? Why you don't see anything wrong? You think that the issue is on NHibernate side?
Thanks in advance!

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by pasqualedante** [comment]
Ok I check.
Thanks!
