### ISSUE TITLE
Flattening complex object not works in ProjectTo when the flattened property is null

### ISSUE THREAD

**Issue by pasqualedante** [AutoMapper/AutoMapper#3553]
I use Automapper 10.1.1.
I have the scenario listed under:

```
    public class Task
    {
        public virtual int Id { get; set; }
        public virtual Customer Customer { get; set; }
    }

    public class Customer
    {
        public virtual string Id { get; set; }
        public virtual string Name { get; set; }
    }

    public class DTOTask
    {
        public virtual int Id { get; set; }
        public virtual string CustomerName { get; set; }
    }
```

I want to flattening complex object Task.Customer.Name in the property CustomerName of the DTOTask.
This works when I make a simple mapping using Map. It works also when I make a ProjectTo and Custumer is not null, but not works if ProjectTo is executed when Task.Customer == null.
I attach here a simple unit test to show the issue in action. If I revert Automapper to 9.0, all works fine.
[FlatteningWithProjectTo.zip](https://github.com/AutoMapper/AutoMapper/files/5765468/FlatteningWithProjectTo.zip)

Thanks in advance.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
