### ISSUE TITLE
Record types

### ISSUE THREAD

**Issue by jameswoodley** [AutoMapper/AutoMapper#3554]
Just trying to map record types and it seems Automapper sees them as Object. Am I right in assuming it's a bit too early to think Automapper should map record types successfully?

For instance:
```
// command.Scopes is of type Scope[]
var mapS = _mapper.Map<Scope>(command.Scopes);
```
throws
```
Missing type map configuration or unsupported mapping.

Mapping types:
Object -> Scope
System.Object -> Scope
```

I have `CreateMap<Scope, Scope>();` in my Mapping profile so this in theory should work?

**Comment by lbargaoanu** [comment]
It should work. Check the older discussion about it.

**Comment by jbogard** [comment]
Records are just classes with compile time sugar. Otherwise they look like normal classes with private setters and/or a constructor.

Records work with serialization, EF Core, anything that uses reflection/expression trees/Reflection.Emit.

**Comment by jbogard** [comment]
Also above it looks like you're trying to map something to itself? And then an array of something to a single thing at runtime? All that is a bit weird.

**Comment by jameswoodley** [comment]
I'll give the full story:

I have a record that has multiple properties within it, one of which is another record.
```
public record Scope(string Description, string Value);

public record ApiCreateRequest(string Name, string Identifier, Scope[] Scopes,
        bool IncludePermissionsInScopeClaim, bool SkipConsentIfFirstParty, bool AllowOfflineAccess,
        int? TokenLifetimeSeconds);
```

I then have a MediatR command object that I'd like to map to the ApiCreateRequest record
```
public class CreateApiCommand : IRequest<ApiReadModel>
{
    public string Name { get; init; } = default!;
    public string Identifier { get; init; } = default!;
    public Scope[] Scopes { get; init; } = Array.Empty<Scope>();
    public bool IncludePermissionsInScopeClaim { get; init; } = true;
    public bool SkipConsentIfFirstParty { get; init; } = true;
    public bool AllowOfflineAccess { get; init; }
    public int? TokenLifetimeSeconds { get; init; }
}
```
and my mapping profile
```
CreateMap<CreateApiCommand, ApiCreateRequest>();
```

When running my unit tests, I noticed that equality wasn't preserved even though both records should be equal value, so:
```
var map = _mapper.Map<ApiCreateRequest>(command);
var map1 = _mapper.Map<ApiCreateRequest>(command);
var equality = map.Equals(map1);      <-- False
```

I took out the inner Scope[] and then it was preserved. So I thought OK I'll try mapping just the scopes and checking that for equality, so added
```
CreateMap<Scope, Scope>()
``` 
to my profile (as the docs say you don't need to worry about enumerator, arrays, lists etc?) and tried again. This time I got the Object -> Scope exception

My end goal here really is to be able to run map twice on the same source, get 2 different result objects, call .Equals on it and get a true.

**Comment by jbogard** [comment]
Your command class isn't declared as a record, is that intentional?

**Comment by jameswoodley** [comment]
Got an email with a new comment @jbogard but it seems to have disappeared on here, anyway in terms of the Command not being a record, not intentional per se, could probably just be a standard POCO. No real business need for immutability there I don't think

**Comment by jbogard** [comment]
Record equality isn't doing what you think it's doing:

```csharp
var request1 = new ApiCreateRequest(
    Name: "Joe",
    Identifier: "1234",
    Scopes: new[]
    {
        new Scope(
            Description: "Description1",
            Value: "Value1"),
        new Scope(
            Description: "Description2",
            Value: "Value2")
    },
    IncludePermissionsInScopeClaim: true,
    SkipConsentIfFirstParty: false,
    AllowOfflineAccess: true,
    TokenLifetimeSeconds: 10
);
var request2 = new ApiCreateRequest(
    Name: "Joe",
    Identifier: "1234",
    Scopes: new[]
    {
        new Scope(
            Description: "Description1",
            Value: "Value1"),
        new Scope(
            Description: "Description2",
            Value: "Value2")
    },
    IncludePermissionsInScopeClaim: true,
    SkipConsentIfFirstParty: false,
    AllowOfflineAccess: true,
    TokenLifetimeSeconds: 10
);
Console.WriteLine(request1.Equals(request2)); // prints false
```

```csharp
var scopes = new[]
{
    new Scope(
        Description: "Description1",
        Value: "Value1"),
    new Scope(
        Description: "Description2",
        Value: "Value2")
};
var request1 = new ApiCreateRequest(
    Name: "Joe",
    Identifier: "1234",
    Scopes: scopes,
    IncludePermissionsInScopeClaim: true,
    SkipConsentIfFirstParty: false,
    AllowOfflineAccess: true,
    TokenLifetimeSeconds: 10
);
var request2 = new ApiCreateRequest(
    Name: "Joe",
    Identifier: "1234",
    Scopes: scopes,
    IncludePermissionsInScopeClaim: true,
    SkipConsentIfFirstParty: false,
    AllowOfflineAccess: true,
    TokenLifetimeSeconds: 10
);
Console.WriteLine(request1.Equals(request2));
```

This is because it's using `EqualityComparer<T>` for each member. Arrays do not implement `IEquatable<T>`. So it'll use the default `Equals` method, which is reference equality.

Womp womp

**Comment by jameswoodley** [comment]
Makes so much sense now you spell it out, and I feel foolish. Thanks so much!

**Comment by jbogard** [comment]
I had to pull it up in DotPeek to see what was happening, but it makes sense now.

**Comment by jameswoodley** [comment]
Is there something clever I can do in a .ForMember config to help this, or should I map without the scopes and manually copy?

**Comment by jbogard** [comment]
Fundamentally, records do not support the behavior you want (removing AutoMapper from the equation). You have some options:

- Use a collection type that DOES implement `IEquatable<T>` and uses `Enumerable.SequenceEquals`. I don't see one offhand so you'll likely need to create this yourself.
- Override `Equals` and do what the decompiled stuff does, replacing the `EqualityComparer<T>.Default` part of the collection `SequenceEquals`

Don't use AutoMapper to try to work around the design of Records, though, that's super confusing to anyone using it. You'd have to "UseDestinationValue" then mutate the array contents, which I DON'T think you'd want to do, that's super weird. Say you want to use `ReadOnlyCollection<T>` instead? This would all break.

**Comment by jameswoodley** [comment]
Yup I'm with you, I was hoping for a silver bullet that isn't there. All good. I'll find a way.

Thanks again for the help and digging into the framework, really appreciate it
