### ISSUE TITLE
Flattening makes unnecessary join when used with EF/ProjectTo

### ISSUE THREAD

**Issue by robin-thoni** [AutoMapper/AutoMapper#3555]
When a field `AddressId` is present in the destination object, AM will use `address.id`, rather than `address_id`, resulting in useless join when using EF/ProjectTo.

### Source/destination types

```csharp
public class AddressModel
    {
        public Guid id { get; set; }

        public string zip { get; set; }

        // [..]
    }

public class CustomerModel
  {
    public Guid id { get; set; }

    public Guid address_id { get; set; }

    public AddressModel address { get; set; }

    public string name { get; set; }

    // [..]
  }


public class AddressDTO
    {
        public string Id { get; set; }

        public string Zip { get; set; }

        // [..]
    }

public class CustomerDTO
  {
    public string Id { get; set; }

    public string AddressId { get; set; }

    public AddressDTO Address { get; set; }

    public string Name { get; set; }

    // [..]
  }
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(cfg =>
      {
        cfg.CreateMap<AddressModel, AddressDTO>();
        cfg.CreateMap<CustomerModel, CustomerDTO>();
      });
```

### Expected behavior

Use the "closest" available field to map from.

### Actual behavior

AM chooses a sub-object field.

### Steps to reproduce

A simple repro can be found [here](https://github.com/robin-thoni/automapper-flattening): when simply running the app as-is, you'll see that `AddressModel.Id` is accessed twice:
```
GET AddressModel.id
GET AddressModel.id
```
But if you uncomment the `ForMember` line `Program.cs`, you'll get the desired behavior:
```
GEt CustomerModel.address_id
GET AddressModel.id
```

**Comment by lbargaoanu** [comment]
`address_id` is not a match for `AddressId`, but `address.id` is, so that one is used.
