### ISSUE TITLE
Multiple matches with IncludeMembers

### ISSUE THREAD

**Issue by thomas-oliver-cko** [AutoMapper/AutoMapper#3558]
### Source/destination types

```csharp
public class Source
{
    public Inner Inner { get; set; }
}

public class Inner
{
    public string Value { get; set; }
}

public class Destination
{
    public string InnerValue { get; set; }
}
```

### Mapping configuration

``` csharp
cfg.CreateMap<Source, Destination>().IncludeMembers(src => src.Inner);

cfg.CreateMap<Inner, Destination>()
    .ForMember(dest => dest.InnerValue, opt => opt.MapFrom(src => "This is my value"));
```

### Version: 8.1.0
.NET Core 3.1
xUnit 2.4.1

### Expected behavior
when calling 

```csharp
var instrument = new Source
{
    Inner = new Inner
    {
        Value= "Value"
    }
};

var destination = mapper.Map<Destination>(instrument);
```

Then `destination.InnerValue` should be `This is my value`

### Actual behavior

Then `destination.InnerValue` is `Value`

### Steps to reproduce

This issue occurs when the destination property has the same name as the source property concatenated with the inner source property being used in the `IncludeMembers`. In this case that is `InnerValue`. This also occurs when the destination property is called `Value`, regardless of the order the maps are registered

No Errors occur when the destination is named any of the following:
- InneValue
- InnerValu
- Value
- ValueInner

We have two contracts which follow this pattern, and mapping should work for them.

For reference, here is an xUnit test class:

```csharp 
  public class MappingTests
  {
      [Fact]
      public void Map_HandlesEnumsCorrectly()
      {
          var mapper = new MapperConfiguration(cfg =>
              {
                  cfg.CreateMap<Source, Destination>()
                      .IncludeMembers(src => src.Inner);

                  cfg.CreateMap<Inner, Destination>()
                      .ForMember(dest => dest.InnerValue, opt => opt.MapFrom(src => "This is my value"));
              })
              .CreateMapper();

          var instrument = new Source
          {
              Inner = new Inner
              {
                  Value = "Value"
              }
          };

          var result = mapper.Map<Destination>(instrument);

          Assert.Equal("This is my value", result.InnerValue);
      }
      
      public class Source
      {
          public Inner Inner { get; set; }
      }

      public class Inner
      {
          public string Value { get; set; }
      }

      public class Destination
      {
          public string InnerValue { get; set; }
      }
  }
```

**Comment by lbargaoanu** [comment]
Just disable the default naming convention. Or don't use `IncludeMembers`. Source mappings have priority and the default flattening is one of them.

**Comment by thomas-oliver-cko** [comment]
I understand flattening would cause issues for destination properties with the **same name** as source properties (i.e. if the destination property had the same name a source property). That is an described in the [automapper documentation](https://docs.automapper.org/en/stable/Flattening.html#includemembers). However, in this case the destination property is a combination of the source and inner property names. It **does not** have the same name as any of the source properties. Automapper shouldn't be configuring mappings for a property with name InnerValue at all. If this is expected behavior, then the documentation should be updated to reflect this. Something like:

> The order of the parameters in the `IncludeMembers` call is relevant. When mapping a destination member, the first match wins, starting with the source object itself and then with the included child objects in the order you specified. So in the example above, `Name` is mapped from the source object itself and `Description` from `InnerSource` because it’s the first match. 
> 
> Mappings for combinations of source and inner property names also lose out to mappings of source property names. So in the example above, if the `Destination` property `Name` was called `InnerSourceName`, then it would be automatically mapped from `Source.Name`. Explicitly configuring maps from `InnerSource.Name` to `Destination.Name` would be ignored. 

Regarding disabling the default naming convention, do you mean using `.ForAllMembers(opt => opt.Ignore())`? We opted for a `ITypeConverter` instead as it is more readable and performant.

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Configuration.html#naming-conventions

**Comment by thomas-oliver-cko** [comment]
The page link has no mention of this behavior or how to configure nested naming conventions. No map should be registered for `Destination.InverValue` when the source properties are `Source.Inner` and `Inner.Value`. Why is `Inner.Value` mapped to `InnerValue`?

**Comment by lbargaoanu** [comment]
More is explained in the flattening page you linked to. Strange or not, this has been the default for a long time now, documented and everything.

**Comment by thomas-oliver-cko** [comment]
Ah I see that now! Sorry for the confusion and thanks for the help 😄
