### ISSUE TITLE
Breaking changes in v10.1.1

### ISSUE THREAD

**Issue by rikrak** [AutoMapper/AutoMapper#3559]
I've noticed that there appear to be breaking changes in v10.1.1 in the way that "Get" methods now take precedence over default Property Maps.  It would probably be worth documenting this in an upgrade guide as it is likely to catch people out

ref: [https://github.com/AutoMapper/AutoMapper/issues/3523#issuecomment-711150765](https://github.com/AutoMapper/AutoMapper/issues/3523#issuecomment-711150765)

### Source/destination types

```csharp
class Source
{
	public string FirstName{ get; set; }
	public string Surname { get; set; }
	public string EmailAddress { get; set; }
	public string GetEmailAddress() => $"\"{this.FirstName} {this.Surname}\" <{this.EmailAddress}>";
}

class Target
{
	public string FirstName{ get; set; }
	public string Surname { get; set; }
	public string EmailAddress { get; set; }
}

var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Target>();
});
var mapper = new Mapper(config);

var src = new Source()
{
    FirstName = "Aaron",
    Surname = "Alpha",
    EmailAddress = "AA@example.org"
};

var result = mapper.Map<Target>(src);

// V10 outputs: "AA@example.org" - Target.EmailAddress is mapped from the property Source.EmailAddress
// V10.1.1 outputs: "Aaron Alpha" <AA@example.org>"- Target.EmailAddress is mapped from the method Source.GetEmailAddress()
Console.Log(result.EmailAddress);

```
To persist in the previous behaviour it is necessary to override the selection of Methods for mapping by using `ShouldMapMethod`:

```
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Target>();
    
    // configure this to return false to prevent the default use of "Get" methods
    cfg.ShouldMapMethod = methodInfo => false;
});
var mapper = new Mapper(config);

### Version: 10.1.1

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by rikrak** [comment]
Is this behaviour going to change in the next release?

**Comment by lbargaoanu** [comment]
Yes, but that's not coming soon, hence the MyGet build.

**Comment by rikrak** [comment]
Thanks for the feedback.
