### ISSUE TITLE
Automapper access the getter of destination in mapping

### ISSUE THREAD

**Issue by redxeagle** [AutoMapper/AutoMapper#356]
After upgrading from version 2.0.0 to 2.2.1 we had some failing tests.
The behavior of mapping was changed. Now Automapper call the getter of the destination. In my opinion it shouldnt cause if has to set it. For example a getter could contains a access to a service when a private property is still null, for lazy loading.

Here a failing test for Version 2.2.1 which works fine in Version 2.0.0

```
public class AutomapperTestClass
        {


            [Test]
            public void should_ignore_the_getter_of_destination()
            {
                Mapper.CreateMap<Source, Destination>();

                var result = Mapper.Map<Destination>(new Source() {Foo = "Bar"});
            }

            private class Source
            {
                public string Foo { get; set; }
            }

            private class Destination
            {
                private string _foo;

                public string Foo
                {
                    get { throw new Exception(); }
                    set { _foo = value; }
                }
            }
        }
```

**Comment by KevinDjordjevic** [comment]
I am noticing the getter of my destination object being called in 5.0.0-ci-1049, and it is causing problems!
