### ISSUE TITLE
Queryable projection on entities with composite keys can break with EF core 5 

### ISSUE THREAD

**Issue by Erythnul** [AutoMapper/AutoMapper#3561]
After raising an issue with the EF Core, I've been directed here. 
With EF Core 5, a part of queryable projection was broken by the EF Core team when combined with composite keys on the database side. Though I believe this is something that is not correct on their side, I'm also coming here to see if you will be able to fix.
A repro github and more information can be found in the EF core issue:

https://github.com/dotnet/efcore/issues/23898

**Comment by lbargaoanu** [comment]
That's not going to happen. You can probably skip the null check with `AllowNull`.

**Comment by Erythnul** [comment]
Alright, I'll give that a try, thanks for your advice :)

**Comment by Erythnul** [comment]
@lbargaoanu That does indeed fix my issue, we will most likely implement AllowNullDestinationValues = false on all of our mapper initializations for the time being. Thanks again and sorry for bothering you with this.

**Comment by lbargaoanu** [comment]
No worries :)
