### ISSUE TITLE
Don't fallback to mapping by numeric values for enums

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#3562]
It's confusing. You can always opt in to mapping by numeric values by creating a map (an interesting execution plan, but it works). So just throw when the names don't match. I don't know about validation. Maybe let people write their own.

**Comment by earloc** [comment]
I see your point, as this can get very confusing!

However, care needs to be taken while rolling this out, as there may be many clients out there (unknowingly) depending on this.

Maybe this could be introduced via an opt-in mechanism?

Putting this in place would also obsolete the need for this
[PR over here](https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/pull/9) (less code to maintain´s always good ;))

**Comment by lbargaoanu** [comment]
No, the next version is a major version and this is a minor change that can be easily overiden with a map or a custom mapper. cc @jbogard

**Comment by earloc** [comment]
I´d personally very welcome this kind of behavior, even as the new default behavior.

However, folks out there might not be aware of this kind of change. 
And "easily overriding it" can quickly become a rather time-consuming task - depending on the quality of error-messages, number of mappings to be take in place, etc..

Why not provide a rather global opt-out-mechnism for this, and re-use the previous mapping logic in this case, at least for the next major-release? 
So to make people aware of these issues and to give them enough time to migrate their codebases, if needed.

**Comment by earloc** [comment]
Especially, as (sadly) not everyone out their is acutally validating their AM-configs in a proper way. 
And would this even fail with this change, anyway, without explicitly enabling enum-validation?

Or may this introduce runtime-exceptions only?

**Comment by lbargaoanu** [comment]
That's why we have upgrade guides. Settings are for the most part a design failure. They bring complexity and make things hard to understand. Not changing things is a lot better than adding an arbitrary setting. But I think we should do this.

**Comment by earloc** [comment]
Do what? 

A- Change the current behaviour without providing a (transiotional) opt-in /  - out?

B - Give people something so they can adopt their codebases a bit smoother?

Just sayin, that this kind of considerations should definitely be part of the final design-decision. I don't have exact numbers, but I'll guess AM is used in many projects out there.
