### ISSUE TITLE
AutoMapper 10.1.1 don't ignore generic types with UseDestinationValue()

### ISSUE THREAD

**Issue by zornic84** [AutoMapper/AutoMapper#3566]
### Source/destination types
I have problems with AutoMapper copying the values from the ViewModel to the Entity. I've an ViewModel like this:

`public class BusinessPartnerAppModel<TKey> : TableBaseDefault<TKey> where TKey : IEquatable<TKey>{ 
   public string CardCode { get; set; } = string.Empty;
   public string CardName { get; set; } = string.Empty;
   public List<AccessDbModel<TKey>> AccessDatas { get; set; } = new List<AccessDbModel<TKey>>();
}

public class AccessAppModel<TKey> : TableBaseLines<TKey> where TKey : IEquatable<TKey>
{
    public TKey BusinessPartnerId { get; set; }
    public string URL { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string UserName { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
}`

An i've an DbModel like this:

`public class BusinessPartnerDbModel<TKey> : TableBaseDefault<TKey> where TKey : IEquatable<TKey>{ 
   public string CardCode { get; set; } = string.Empty;
   public string CardName { get; set; } = string.Empty;
   public List<AccessDbModel<TKey>> AccessDatas { get; set; } = new List<AccessDbModel<TKey>>();
}

public class AccessDbModel<TKey> : TableBaseLines<TKey> where TKey : IEquatable<TKey>
{
    public TKey BusinessPartnerId { get; set; }
    [ForeignKey("BusinessPartnerId")]
    public BusinessPartnerModel<TKey> BusinessPartner { get; set; }
    public string URL { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string UserName { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
}`

### Mapping configuration
TKey is in my case "GUID"

 public override TResult Save(BusinessPartnerAppModel entity)

`var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<AccessAppModel<TKey>, AccessDbModel<TKey>>()
            .ForMember(dest => dest.BusinessPartner, opt => opt.UseDestinationValue());
            cfg.CreateMap<BusinessPartnerAppModel<TKey>, BusinessPartnerDbModel<TKey>>();
        });
        IMapper iMapper = config.CreateMapper();
        
        BusinessPartnerModel<TKey> dbEntity = _businessPartnerManager.FindByKey(entity.Id);
        _businessPartnerManager.Attach(dbEntity);
        
        iMapper.Map(entity, dbEntity);
        
        this._businessPartnerManager.Save();
}`

### Version: 10.1.1
I use .Net 5 with Microsoft.EntityFrameworkCore 5.0.2

### Expected behavior

I expect the "BusinessPartner" attribute to be ignored and not set to the value "null" 

### Actual behavior

The "BusinessPartner" attribute has the value "null" after the execution of "iMapper.Map"

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by zornic84** [comment]
No, that looks like a bug in AutoMapper

**Comment by zornic84** [comment]
No, that looks like a bug in AutoMapper
