### ISSUE TITLE
Projection from string to object with EF6

### ISSUE THREAD

**Issue by konstantin-kuda** [AutoMapper/AutoMapper#3585]
### Source/destination types

```csharp
    public partial class ref_case_default_folders_def
    {
        public ref_case_default_folders_def()
        {
            ref_case_default_folders_lang = new HashSet<ref_case_default_folders_lang>();
        }

        [Key]
        [StringLength(3)]
        public string case_folder_id { get; set; }

        [Required]
        [StringLength(6)]
        public string obj_type_cod { get; set; }

        public byte? flag_top_in_ddown { get; set; }

        [Required]
        [StringLength(255)]
        public string sys_nam { get; set; }

        [StringLength(1)]
        public string flag_sys_cod { get; set; }

        [StringLength(500)]
        public string rem_txt { get; set; }

        public DateTime cr_dat { get; set; }

        [Required]
        [StringLength(12)]
        public string cr_usr { get; set; }

        public DateTime? rv_dat { get; set; }

        [StringLength(12)]
        public string rv_usr { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public Guid rowguid { get; set; }

        public virtual ICollection<ref_case_default_folders_lang> ref_case_default_folders_lang { get; set; }
    }


    public class ref_def_DTO : RefTableBaseDto
    {
        public object parent_code { get; set; }

        public string value5 { get; set; }

        public string value6 { get; set; }

        public bool? boolean { get; set; }

        public DateTime? date { get; set; }

        public byte[] bytes { get; set; }

        public byte? flag_top_in_ddown { get; set; }

        [StringLength(1)]
        public string flag_sys_cod { get; set; }

        public string type { get; set; }

        public string subtype { get; set; }
        
        public int num { get; set; }

        public decimal dec { get; set; }

        [Unique(Property = "lang_cod")]

        public ICollection<ref_lang_DTO> ref_lang { get; set; }

        public ref_def_DTO()
        {
            ref_lang = new HashSet<ref_lang_DTO>();
        }
    }

    public class RefTableBaseDto : DBObjectBaseDto
    {
        [StringLength(500)]
        public string rem_txt { get; set; }

        public object code { get; set; }
        public string value { get; set; }
        public string value2 { get; set; }
        public string value3 { get; set; }
        public string value4 { get; set; }
        public bool dirty { get; set; }
        public Type RefTableType { get; set; }
    }

    public class DBObjectBaseDto : IEditableObject
    {
        public DateTime cr_dat { get; set; }

        [StringLength(12)]
        public string cr_usr { get; set; }

        public DateTime? rv_dat { get; set; }

        [StringLength(12)]
        public string rv_usr { get; set; }

        public Guid rowguid { get; set; }
        public bool IsNew { get; set; }
        public bool IsDirty { get; set; }
        public bool IsDeleted { get; set; }
    }
```

### Mapping configuration

```csharp
var mapperConfiguration = new MapperConfiguration(cfg =>
            {
                
                    cfg.CreateMap<ref_case_default_folders_def, ref_def_DTO>()
                        .ForMember(t => t.code, opt => opt.MapFrom(s => s.case_folder_id));
            });
```

### Version: 10.1.1
EF6.4 version

### Expected behavior
ProjectTo method should generate below expression for SQL Server (like it was in v.9)

.Lambda #Lambda1<System.Func`2[goCASEWeb.RefTables.ref_case_default_folders_def,goCASEWeb.DTO.RefTables.ref_def_DTO]>(goCASEWeb.RefTables.ref_case_default_folders_def $dtoref_case_default_folders_def)
{
    .New goCASEWeb.DTO.RefTables.ref_def_DTO(){
        code = $dtoref_case_default_folders_def.case_folder_id,
        cr_dat = $dtoref_case_default_folders_def.cr_dat,
        cr_usr = $dtoref_case_default_folders_def.cr_usr,
        flag_sys_cod = $dtoref_case_default_folders_def.flag_sys_cod,
        flag_top_in_ddown = $dtoref_case_default_folders_def.flag_top_in_ddown,
        rem_txt = $dtoref_case_default_folders_def.rem_txt,
        rowguid = $dtoref_case_default_folders_def.rowguid,
        rv_dat = $dtoref_case_default_folders_def.rv_dat,
        rv_usr = $dtoref_case_default_folders_def.rv_usr
    }
}

### Actual behavior

In the version 10.1.1 Mapper generates the below expression

.New goCASEWeb.DTO.RefTables.ref_def_DTO(){
    code = **(System.Object)**$dtoref_case_default_folders_def.case_folder_id,
    cr_dat = $dtoref_case_default_folders_def.cr_dat,
    cr_usr = $dtoref_case_default_folders_def.cr_usr,
    flag_sys_cod = $dtoref_case_default_folders_def.flag_sys_cod,
    flag_top_in_ddown = $dtoref_case_default_folders_def.flag_top_in_ddown,
    rem_txt = $dtoref_case_default_folders_def.rem_txt,
    rowguid = $dtoref_case_default_folders_def.rowguid,
    rv_dat = $dtoref_case_default_folders_def.rv_dat,
    rv_usr = $dtoref_case_default_folders_def.rv_usr
}

The problem is that mapper adds **(System.Object)**$dtoref_case_default_folders_def.case_folder_id

In this case SQL Server generates below exception:
System.NotSupportedException: 'Unable to cast the type 'System.String' to type 'System.Object'. LINQ to Entities only supports casting EDM primitive or enumeration types.'

![image](https://user-images.githubusercontent.com/13768165/108707660-a69a7900-7510-11eb-8866-b601c11bb1cc.png)

### Steps to reproduce

```csharp
var a = Db.Set(typeof(ref_case_default_folders_def));
var b = a.ProjectTo<ref_def_DTO>(mapperConfiguration);
var c = b.ToList();
```

**Comment by lbargaoanu** [comment]
You can PR the branch https://github.com/AutoMapper/AutoMapper/tree/explicit_expand.

**Comment by lbargaoanu** [comment]
Going forward our main target will be EF Core. So EF6 specific issues are best handled in your own code.
The obvious workaround is to not use `object` as property type. If you're trying to reuse DTOs, just don't.
