### ISSUE TITLE
10.1.1 broke mapping in special cases

### ISSUE THREAD

**Issue by mortan** [AutoMapper/AutoMapper#3614]
Hi guys! I'm afraid but you broke something in the most recent version 10.1.1 or 10.1.0 :smiley:

After upgrading from **10.0.0** to **10.1.1** (Nuget doesn't offer 10.1.0, so I can't test that version) one of our mapping profiles stopped working, i. e. one property didn't get mapped at all and our main test that calls AssertConfigurationIsValid() failed.

It took me quite a while to figure out what's actually going on: **if your mapping source class has two properties with the same name but different capitalisation (i. e. Foo and FOO) mapping will break**!

The reason is that if your destination class has a property Destination.FOO and you want to map from Source.FOO, AutoMapper actually tries to map from Source.Foo. I've provided a working (in terms of not working :smirk:) example in form of a unit test. If you copy paste that into a test project with AutoMapper 10.1.1 you can reproduce the behaviour.

### Source/destination types

```csharp
class Documenttype { }

class Source
{
	public short? DOCUMENTTYPE { get; set; }
	public Documenttype Documenttype { get; set; }
}

class Destination
{
	public short? DOCUMENTTYPE { get; set; }
}
```

### Mapping configuration

```csharp
class MappingProfile : Profile
{
	public MappingProfile()
	{
		CreateMap<Source, Destination>(MemberList.Destination);
	}
}
```

### Test

```csharp
[Test]
public void ShouldMapFromCorrectProperty()
{
	MapperConfiguration configuration = new MapperConfiguration(cfg =>
	{
		cfg.AddProfile(typeof(MappingProfile));
	});

	Mapper mapper = new Mapper(configuration);
	
	// Notice how Destination.DOCUMENTTYPE is null
	Destination destination = mapper.Map<Destination>(new Source { DOCUMENTTYPE = 99 });
	
	// Exception thrown because "destination member DOCUMENTTYPE could not be found in source type".
	// This is nonsense, the underlying error is that AutoMapper tries to map from
	// Source.Documenttype -> Destination.DOCUMENTTYPE (notice the capitalisation, it's the wrong property!)
	configuration.AssertConfigurationIsValid();
}
```

### Expected behavior

Test should pass, in older Versions <= 10.0.0 the correct property would have been taken for mapping (DOCUMENTTYPE).

### Actual behavior

Test fails with a misleading error "destination member DOCUMENTTYPE could not be found in source type".

### Steps to reproduce

Execute the unit test I provided.

**Comment by jbogard** [comment]
This is an odd edge case we have no unit tests for. PR is welcome!

**Comment by lbargaoanu** [comment]
We are case insensitive, so what happens in such a case is not relevant.

**Comment by buddde** [comment]
Can you check names and types or check the names case sensitive?

**Comment by lbargaoanu** [comment]
In a case like this you have to explicitly say what you want, you cannot relay on the default matching.

**Comment by jbogard** [comment]
You can alter the naming convention if you don't like these defaults, to ignore all upper case or something.

**Comment by mortan** [comment]
I don't know why you are case-insensitive (while C# is case sensitive and having two properties with the same name but different capitalisation is perfectly valid - not to argue that this is good practice), but what about the misleading error message? That's probably what bugs me most:

```csharp
AutoMapper.AutoMapperConfigurationException : The following member on XXX.WebTests.Destination cannot be mapped: 
	DOCUMENTTYPE 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type XXX.Destination.
Context:
	Mapping to member DOCUMENTTYPE from XXX.WebTests.Source to XXX.WebTests.Destination
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
   at XXX.WebTests.MappingProfileTests.ShouldMapFromCorrectProperty() in YYY\Web.UnitTests\MappingProfileTests.cs:line 86
```
That is the same message you would get if the property does not exist in the Source type. That AutoMapper finds "Documenttype" instead of "DOCUMENTYPE" and can not map because the former is a **complex type** (if it wasn't a complex type it would straight up map from the wrong property without notice!) is not clear at all. Again, it took me quite a while to figure that out in our code base because "Documenttyp" is in a different spot.

Is there a way to get a check for such a case or at least a better error message? Also  @lbargaoanu could you elaborate why AutoMapper is case-insensitive?

@jbogard Would it be possible to override the naming convention as you suggested and check for a property in the Source type with the exact name and capitalisation and if not found delegate to the normal AutoMapper naming convention code?

Greetings

**Comment by jbogard** [comment]
That the mapping worked in the first place was just coincidence, it was never intentional. AutoMapper does its member configuration by first matching member names, then later trying to figure out the type conversion. Because a later map could add a conversion, we don't make any kind of type conversion comparisons or assumptions in the first member mapping phase. Any more complex and we'd be a compiler.
