### ISSUE TITLE
ProjectTo overload that accepts an IMapper

### ISSUE THREAD

**Issue by grosch** [AutoMapper/AutoMapper#3646]
A very common use case for AutoMapper is to inject the mapper into a constructor. When I'm projecting from a linq query I then always add the `.ProjectTo<MyClass>(Mapper.ConfigurationProvider)`. 

Would it be possible to have a `ProjectTo<T>` overload that takes an `IMapper` instead?

**Comment by jbogard** [comment]
We had an overload but it was confusing to some folks that the things the Mapper has would be used during projection - but it is not. So to make the API crystal-clear, we took the object that was needed. You can add that yourself in your own codebase, though.

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/Dependency-injection.html#queryable-extensions
