### ISSUE TITLE
Run that as a LINQ statement, without AM. You should get the same result.

### ISSUE THREAD

**Issue by amilcar-dev** [AutoMapper/AutoMapper#3673]
Run that as a LINQ statement, without AM. You should get the same result.

Thanks, but what do you mena by without AM

_Originally posted by @lbargaoanu in https://github.com/AutoMapper/AutoMapper/discussions/3669#discussioncomment-879388_

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
