### ISSUE TITLE
Undocumented breaking change on v10: Property and method source mapping ambiguity exception

### ISSUE THREAD

**Issue by julealgon** [AutoMapper/AutoMapper#3705]
Gist: https://gist.github.com/julealgon/ca2b03a6afba13a65f7441d6f2a4e41e

### Source/destination types

```csharp
    class MyDto
    {
        public MyDependentDto MyProperty { get; set; }
    }

    class MyDependentDto
    {
    }

    abstract class MyBaseDomainEntity
    {
        public abstract MyBaseDependentDomainEntity GetMyProperty();
    }

    class MyDomainEntity : MyBaseDomainEntity
    {
        public MyDependentDomainEntity MyProperty { get; set; }

        public override MyBaseDependentDomainEntity GetMyProperty() => default;
    }

    abstract class MyBaseDependentDomainEntity
    {
    }

    class MyDependentDomainEntity : MyBaseDependentDomainEntity
    {
    }
```

### Mapping configuration

```csharp
    class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateMap<MyDomainEntity, MyDto>();
            CreateMap<MyDependentDomainEntity, MyDependentDto>();
        }
    }
```

### Expected behavior

v9 used to pass validation, and then map the value from the property with the matching name. The `GetX` method was ignored.

### Actual behavior
`AutoMapperConfigurationException` is throw with the following message:

> The following member on ConsoleApp1.MyDto cannot be mapped: 
	MyProperty 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type ConsoleApp1.MyDto.
Context:
	Mapping to member MyProperty from ConsoleApp1.MyDomainEntity to ConsoleApp1.MyDto
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.

### Steps to reproduce

```csharp
            var mapperConfiguration = new MapperConfiguration(c => c.AddProfile<MappingProfile>());
            mapperConfiguration.AssertConfigurationIsValid();
            var mapper = mapperConfiguration.CreateMapper();

            var entity = new MyDomainEntity { MyProperty = new MyDependentDomainEntity() };
            var mappedEntity = mapper.Map<MyDto>(entity);
```

If I then explicitly configure the mapping expression on the `CreateMap` call, it works as before:
```csharp
            CreateMap<MyDomainEntity, MyDto>()
                .ForMember(target => target.MyProperty, options => options.MapFrom(source => source.MyProperty));
```

This is a breaking change from 9.0.0 that is not documented in the migration guide and has caused a few hours of debugging on my end due to how barebones the error message is (i.e. no mention of "ambiguity", for example).

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by julealgon** [comment]
> Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

Latest build fixes the problem indeed. Apologies on my end for not noticing that suggestion in the issue template text.

Can you link to the actual issue where this was fixed @lbargaoanu ?

**Comment by lbargaoanu** [comment]
It was fixed a long time ago and reported a few times more :)

**Comment by julealgon** [comment]
> It was fixed a long time ago and reported a few times more :)

If it was fixed a long time ago, why hasn't a patch release being made with the fix yet?

**Comment by jbogard** [comment]
Hmmm it's probably about that time...
