### ISSUE TITLE
Source type is missing in the "Missing type map configuration error"

### ISSUE THREAD

**Issue by sergevic** [AutoMapper/AutoMapper#3750]
### Source/destination types

```csharp
class Source
{
    public int FieldA { get; set; }
}

class Destination
{
    public int FieldA { get; set; }
}
```

### Mapping configuration

```csharp
class MappingProfile : Profile
{
    public MappingProfile()
    {
        //CreateMap<Source, Destination>(); // this line is commented to demonstrate exception message
    }
}
```

### Expected behavior

In the previous version (9.0.0) for the code line

```csharp
var destination = mapper.Map<Destination>(source);
```

the error message looked like

Mapping types:
**Source** -> Destination
TestMapping.Source -> TestMapping.Destination

### Actual behavior

Mapping types:
**Object** -> Destination
System.Object -> TestMapping.Destination

### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg => { cfg.AddProfile<MappingProfile>(); });
var mapper = config.CreateMapper();

var source = new Source { FieldA = 1 };
try
{
    var destination = mapper.Map<Destination>(source);
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```

Reproducible in .Net 5, Also checked in .Net Framework 4.6.2
Solution: [TestMapping.zip](https://github.com/AutoMapper/AutoMapper/files/7285835/TestMapping.zip)

I could not find any information about such behavior in 10.0-Upgrade-Guide

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by sergevic** [comment]
Confirm it works as expected in 10.1.2-alpha.0.4
