### ISSUE TITLE
not enough examples

### ISSUE THREAD

**Issue by nhhockeyplayer** [AutoMapper/AutoMapper#3799]
thanks for work on this its always good to see some core stuff

can someone provide more real world examples all the public blips of this show few and we really need to see WHY this is good to have on deck... all the docs on this are lacking for numerous examples. We get the generics stuff.

QUES: is this just a type casting mechanism? 

If we say 

```
const employee: EmployeeEntity = new EmployeeEntity()
const dto: EmployeeDTO = employee as EmployeeDTO
```

assuming EmployeeEntity implements EmployeeDTO

1. why is the above code not good enough?
2. why is this library not part of standard typescript for type casting/coercian and an operator(s) just added to typescript language?
3. what is typescript NOT doing that this is a huge need for?

I would like to employ this but not seeing the immediate need I use alot of DTO and ENTITIES

elaboration on this would be very gracious

conceptually Im thinking this needs to be tucked away within the CORE typescript language and mechanisms implemented with the language itself... no?

Im an object oriented modeler and when classes and interfaces are modeled properly there is no need for any of this, they get casted to their interface as appropriate as depicted above.

**Comment by lbargaoanu** [comment]
Wrong repo!
