### ISSUE TITLE
QUESTION: .Net Framework support

### ISSUE THREAD

**Issue by alexander-lysenko-88** [AutoMapper/AutoMapper#3824]
Hello!

I've tried to upgrade to the latest version `11.0.0` and noticed that it requires `.netstandard 2.1`, which, as you might know, **is not compatible** with `.Net Framework 4.8`.

Does this mean that .Net Framework won't be supported by AutoMapper from now on?

**Comment by lbargaoanu** [comment]
Indeed. Check [the upgrade guide](https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html).
