### ISSUE TITLE
"Argument types do not match" after upgrade to v11

### ISSUE THREAD

**Issue by joakimriedel** [AutoMapper/AutoMapper#3826]
### Source/destination types

(note the abstract class)

(lots of unrelated properties removed)

(in reality PersonProfile have multiple implementations)

```csharp
    public abstract class PersonProfile
    {
    }

    public class UserProfile : PersonProfile
    {
    }

    public class BusinessCard
    {
        public PersonProfile Person { get; set; } = null!;
    }
```

### Mapping configuration

(note the cast since base is abstract)

(lots of unrelated ForMember/MapFrom removed)

(in reality both PersonProfile and BusinessCard have multiple different sources)

```csharp
            CreateMap<ApplicationUser, PersonProfile>()
                .As<UserProfile>();

            CreateMap<ApplicationUser, UserProfile>()
                .IncludeBase<ApplicationUser, PersonProfile>();

            CreateMap<ApplicationUser, BusinessCard>()
                .ForMember(m => (UserProfile)m.Person, opt => opt.MapFrom(m => m));
```

### Expected behavior

The above configuration worked in v10. Expected my existing maps to work without modifications after upgrade to v11.

### Actual behavior

```
Message: 
    System.ArgumentException : Argument types do not match

  Stack Trace: 
    Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
    TypeMapPlanBuilder.<CreatePropertyMapFunc>g__DestinationMemberValue|27_0(MemberMap memberMap, Expression destinationMemberGetter, Boolean destinationMemberReadOnly)
    TypeMapPlanBuilder.CreatePropertyMapFunc(MemberMap memberMap, Expression destination, MemberInfo destinationMember)
    TypeMapPlanBuilder.CreateAssignmentFunc(Expression createDestination)
    TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
    TypeMap.Seal(IGlobalConfiguration configurationProvider, HashSet`1 typeMapsPath)
    MapperConfiguration.Seal()
    MapperConfiguration.ctor(MapperConfigurationExpression configurationExpression)
```

### Steps to reproduce

Error above is returned when constructing MapperConfiguration. 

### Workaround

```csharp
            CreateProjection<ApplicationUser, BusinessCard>()
                .ForMember(m => (UserProfile)m.Person, opt => opt.MapFrom(m => m));
```

After reading the upgrade docs I just tried using the new CreateProjection method instead of CreateMap to map my configuration as pointed out in the documentation, and surprisingly this works fine. Why am I not allowed to use CreateMap in v11?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by joakimriedel** [comment]
That cast is necessary to construct the derived type, otherwise I will get an error due to abstract class cannot be constructed.

**Comment by lbargaoanu** [comment]
No, it isn't :) I can remove the cast and `As` and have the same functionality. So, while I understand that the mapping used to work, it seems like there is an easy way to fix your mappings. So I need to see a mapping that makes sense and doesn't work.

**Comment by joakimriedel** [comment]
Spent the last hour trying to backtrace to when I had to put the cast there, it was some previous version of AutoMapper but I cannot seem to reproduce any more with v11. It just works without the cast now in v11, so I'm happy with that. Thanks!
