### ISSUE TITLE
Extension method "ForAllOtherMembers" is missing in version 11.0.0

### ISSUE THREAD

**Issue by AnFa1978** [AutoMapper/AutoMapper#3848]
I've tried to update "AutoMapper.Extensions.Microsoft.DependencyInjection" from 8.1.1 to 11.0.0. Now compilations is failing because extension method doesn't exist. Please look in following code snippet:

CreateMap<ContrastProtocol, ContrastProtocolDto>()
  .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
  .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
  .ForAllOtherMembers(x => x.Ignore());
               
What is replacement for it? Can you please give support.

**Comment by lbargaoanu** [comment]
Check [the upgrade guide](https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html).
https://github.com/AutoMapper/AutoMapper/discussions/3833
