### ISSUE TITLE
Automapper 11 throws System.ArgumentException when mapping Enum using ConvertUsing

### ISSUE THREAD

**Issue by stepkillah** [AutoMapper/AutoMapper#3849]
### Source/destination types

```csharp
// Put your source/destination types here
 public enum WorkMode
 {
        OneDirection = 0,
        TwoDirection = 1,
        TurrnstileMode = 2
 }

 public class WorkModeVm : BaseTypeBindableBase<WorkMode>
 {
     public WorkModeVm(WorkMode code) : base(code, code.ToTextResource(), code.ToDescriptionResource())
     {
         RaisePropertyChanged(nameof(FormattedTitle));
     }
  }
```

### Mapping configuration

```csharp
CreateMap<WorkMode, WorkModeVm>().ConvertUsing(x => new WorkModeVm(x));
```

### Expected behavior

It should map using provided `ConvertUsing`, but fails without hitting the expression

### Actual behavior

Exception throw
`System.ArgumentException: Expression of type 'WorkMode' cannot be used for assignment to type 'System.Int32'`

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed

var keyTypes = Enum.GetValues(typeof(WorkMode)).Cast<WorkMode>();
Types = new ObservableCollection<WorkModeVm>(Mapper.Map<IEnumerable<WorkModeVm>>(keyTypes));
```

UPD:
works fine when using direct mapping 

```csharp
Mapper.Map<WorkModeVm>(WorkMode.OneDirection )
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
If that still fails, make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
