### ISSUE TITLE
IncludeMembers doesn't work with positional record

### ISSUE THREAD

**Issue by killergege** [AutoMapper/AutoMapper#3864]
Taking your example for flattening with IncludeMembers in the [documentation](https://docs.automapper.org/en/stable/Flattening.html#includemembers), if I transform the objects to positional records, I get the classic error `Destination needs to have a constructor with 0 args or only optional args`

### Source/destination types

```csharp
 record Source
(
    string Name,
    InnerSource InnerSource,
    OtherInnerSource OtherInnerSource
);

 record InnerSource
(
    string Name,
    string Description
);

 record OtherInnerSource
(
    string Name,
    string Description,
    string Title
);

 record Destination
(
    string Name,
    string Description,
    string Title
);
```

### Mapping configuration

```csharp
            cfg.CreateMap<Source, Destination>().IncludeMembers(s => s.InnerSource, s => s.OtherInnerSource);
            cfg.CreateMap<InnerSource, Destination>(MemberList.None);
            cfg.CreateMap<OtherInnerSource, Destination>();
```

### Expected behavior

I would expect the behavior for IncludeMembers to be the same with classes and positional records

```csharp
        var source = new Source("name",
                                new InnerSource(null, "description"),
                                new OtherInnerSource(null, null, "title"));

        var destination = mapper.Map<Destination>(source);
        Assert.That(destination.Name, Is.EqualTo("name"));
        Assert.That(destination.Description, Is.EqualTo("description"));
        Assert.That(destination.Title, Is.EqualTo("title"));
```

### Actual behavior

Exception `Destination needs to have a constructor with 0 args or only optional args`

### Steps to reproduce

```csharp
        var config = new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Source, Destination>().IncludeMembers(s => s.InnerSource, s => s.OtherInnerSource);
            cfg.CreateMap<InnerSource, Destination>(MemberList.None);
            cfg.CreateMap<OtherInnerSource, Destination>();
        });

        var source = new Source("name",
                                new InnerSource(null, "description"),
                                new OtherInnerSource(null, null, "title"));
        var mapper      = config.CreateMapper();
        var destination = mapper.Map<Destination>(source);
        Assert.That(destination.Name, Is.EqualTo("name"));
        Assert.That(destination.Description, Is.EqualTo("description"));
        Assert.That(destination.Title, Is.EqualTo("title"));
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/ad5a6f84bdeec91af12a3f9e6947ad404ca54530/src/UnitTests/IMappingExpression/IncludeMembers.cs#L1692

**Comment by killergege** [comment]
It works, thanks.

Maybe consider adding it to the documentation related to IncludeMembers ?

I see that this option is mentioned in the [Construction](https://docs.automapper.org/en/latest/Construction.html?highlight=shoulduseconstructor) chapter but not really related to the IncludeMembers feature.
As I have a lot of mappings with records which work perfectly without this option, only when I needed to use IncludeMembers it didn't work.

Thanks again.

**Comment by lbargaoanu** [comment]
A PR is welcome.
