### ISSUE TITLE
v11 InvalidOperationException: Stack Empty on mapping which used to generate a subquery

### ISSUE THREAD

**Issue by Erythnul** [AutoMapper/AutoMapper#3869]
### Gist
https://gist.github.com/Erythnul/38a29c9012a3fdcc77fe117c51386ce9

### Summary
Hi!

I've been reworking some of our more interesting mappers to start our upgrade to 11.0.0 and have run into the problem outlined in the gist. I can open a PR with a failing unit or integration test if necessary.

Looking forward to hearing from you!

Kind regards.

### Expected behavior

In 10.1.1 this would generate an expression like

```csharp
EnumerableQuery<AEntity>.Select(
    dtoAEntity => new Object_1451902296___DtoSubWrapper#DtoSub_Id
    {
        __DtoSubWrapper#DtoSub = dtoAEntity.BEntity.CEntities.FirstOrDefault(x => x.Id == dtoAEntity.CEntityId),
        Id = dtoAEntity.Id
    }).Select(
    dtoLet => new Dto
    {
        DtoSubWrapper = new DtoSubWrapper
        {
            DtoSub = (dtoLet.__DtoSubWrapper#DtoSub == null)
                ? null
                : new DtoSub
                {
                    Id = dtoLet.__DtoSubWrapper#DtoSub.Id,
                    SubString = dtoLet.__DtoSubWrapper#DtoSub.SubString
                }
        },
        Id = dtoLet.Id
    })
```

Not sure if that should be different with the reworked pipeline in 11.0.0, but something like this?

### Actual behavior

System.InvalidOperationException: Stack Empty

Stacktrace: 
```
    Stack`1.ThrowForEmptyStack()
    Stack`1.Peek()
    <> c.< GetSourceExpression > b__4_1(Expression left, Expression right) line 269
    Enumerable.Aggregate[TSource, TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
    SubQueryPath.GetSourceExpression(Expression parameter) line 268
    <> c__DisplayClass11_0.< GetSubQueryExpression > b__0(SubQueryPath path) line 230
    SelectListIterator`2.ToArray()
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    FirstPassLetPropertyMaps.GetSubQueryExpression(ProjectionBuilder builder, Expression projection, TypeMap typeMap, ProjectionRequest & request, ParameterExpression instanceParameter) line 229
    ProjectionBuilder.CreateProjection(ProjectionRequest & request, LetPropertyMaps letPropertyMaps) line 69
```

**Comment by lbargaoanu** [comment]
I could use some help to get the query to actually return smth. `BEntity` is `null`  for some reason.  I don't use EF much :)

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by Erythnul** [comment]
Hi Lucian!

Sorry I didn't get back to you earlier and thanks for the quick response! Code looks good (I'd been looking around a bit before making an issue, but wasn't sure how to make a nice-working fix) and the MyGet build works great as well!

Still having some issues with how EF core reacts to the way these expressions work, but I think that's more my problem than an issue with the way AutoMapper works. I'll post in discussions about that.

Thanks again, looking forward to seeing it in stable.


Kind regards

**Comment by lbargaoanu** [comment]
Can you help with [my problem](https://github.com/AutoMapper/AutoMapper/issues/3869#issuecomment-1022359236)? :)

**Comment by Erythnul** [comment]
I'll have a look asap! Sorry, thought with the commits that you'd figured it out :)

**Comment by Erythnul** [comment]
@lbargaoanu Got it fixed up, original code was based on an in-memory unittest, so the integration test style was fundamentally broken, apologies!

**Comment by lbargaoanu** [comment]
Looks good, if the CI agrees, we have a proper test :)

**Comment by jbogard** [comment]
@lbargaoanu any other issues we're waiting on? I'm OK pushing out the 11.0.1 release out. @jrmoreno1 typically we batch up a few bugs before the patch releases go out.

**Comment by lbargaoanu** [comment]
We're good to go :)

**Comment by jbogard** [comment]
11.0.1 is out now on NuGet
