### ISSUE TITLE
Ambiguous match found exception in .NET6

### ISSUE THREAD

**Issue by Maxmyd** [AutoMapper/AutoMapper#3884]
Hi,

After migrating project from .NET5 to .NET6 I discovered that AutoMapper in .NET6 application throws an exception when trying to map any IEnumerable<> to List<>. This works fine in .NET5.
Below is one of mappings which won't work. Same situation with other types.

### Source/destination types

```csharp
// Source
public class SportKind 
    {
        public long Id { get; set; }
        public long ExternalId { get; set; }
        public string Name { get; set; }
    }
// Destination
public class SportKindDto
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }
```

### Mapping configuration

```csharp
CreateMap<SportKind, SportKindDto>().ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.ExternalId));
```

### Version: x.y.z
Version 11.0.0

### Expected behavior
 AutoMapper must return List<> when IEnumerable or IOrderedEnumerable passed as arguments.

### Actual behavior

Automapper throws an AmbiguousMatchException

### Steps to reproduce

```csharp
// this doesn't work
var result = _mapper.Map<List<SportKindDto>>(sportKinds.OrderBy(z => z.Name));

// this works
var result = _mapper.Map<List<SportKindDto>>(sportKinds.OrderBy(z => z.Name).ToList());
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/3817
