### ISSUE TITLE
Derived interfaces are no longer mapped in 11.0.1

### ISSUE THREAD

**Issue by jobwttraining** [AutoMapper/AutoMapper#3886]
### Source/destination types

```csharp
// Put your source/destination types here
public class Source
{
	public string PropertyA {get; set;}
	public string PropertyB {get; set;}
	public string Name {get; set;}	
}

public class Target : IProperties
{
	public string PropertyA { get; set; }
	public string PropertyB { get; set; }
	public string Name {get; set;}	
}

public interface IProperties : IPropertyA, IPropertyB
{
	string Name {get; set;}	
}

public interface IPropertyA
{
	string PropertyA {get; set;}
}

public interface IPropertyB
{
	string PropertyB {get; set;}
}
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
public class MyProfile : Profile
{
	public MyProfile()
	{
		CreateMap<Source, IProperties>()
			.IncludeBase<Source, IPropertyA>()
			.IncludeBase<Source, IPropertyB>()
			;

		CreateMap<Source, IPropertyA>()
		;

		CreateMap<Source, IPropertyB>()
		;
	}
}

```

### Expected behavior

I expect all properties of the target object to be mapped. This was still the case with version 11.0.0

### Actual behavior

Only PropertyB is mapped, Name and PropertyA are null

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed

	MapperConfiguration mapperConfiguration = new MapperConfiguration(cfg =>
	{
		cfg.AddProfile<MyProfile>();
	});

	IMapper mapper = new Mapper(mapperConfiguration);

	Source source = new Source
	{
		Name = "Name",
		PropertyA = "PropertyA",
		PropertyB = "PropertyB"
	};

	Target target = new Target();

	mapper.Map(source, target);


```

**Comment by lbargaoanu** [comment]
But why the `Include`? Why not have a single map for `IProperties`?

**Comment by jobwttraining** [comment]
This is a very simplified version of a mapping we use to map fields from a ClaimsIdentity to numerous target classes. We use the individual mappings for various properties when we don't need all properties and a single mapping with the included base mappings when we need all. We have some unit tests running which gave an error with the newest version. I tried to create a simple example to see where things went wrong. Not all of our target classes implement the main interface.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by jobwttraining** [comment]
I tried both the sample and the original code which gave an error with the latest MyGet build. Both are working again. Thanks for the quick help! When can we expect a release for this fix?

**Comment by jobwttraining** [comment]
I will see if I can rewrite the mappings so they do not depend on derived interfaces anymore. We use Automapper a lot in all our code base and rely on mappings and included base mappings when we work with derived objects and interfaces to avoid writing the same mapping multiple times when we need to ignore certain base properties. Is this bad design?

**Comment by lbargaoanu** [comment]
Not necessarily. But in this particular case, you ask AM to map between `Source` and `Target`, and no map matches exactly, hence the uncertainty. You can either create a map to the concrete class or to the interface and use `As`. But you want to make the decision in your own code, not rely on some corner case inside AM.

**Comment by jobwttraining** [comment]
All right. Thanks for the insight and quick responses.
I will create some direct mappings for that situation.
