### ISSUE TITLE
ProjectTo doesn't adhere to Filtered Includes (.EfCore 6)

### ISSUE THREAD

**Issue by Allann** [AutoMapper/AutoMapper#3900]
### Source/destination types

```csharp
        var entity = await _dbContext
            .Users
            .Include(u => u.UserRoles.Where(ur => ur.Active))
            .Where(u => u.SignInName == request.SignInName)
            .ProjectTo<UserGetBySignInNameResponse>(_mapper.ConfigurationProvider)
            .FirstOrDefaultAsync();
```

### Mapping configuration

```csharp
        CreateMap<DbUser, UserGetBySignInNameResponse>()
            .ConstructUsing(u=>new UserGetBySignInNameResponse(u.Id, u.UserOrganisation))
            .ForMember(d=>d.Roles, cfg=>cfg.MapFrom(s=>s.UserRoles));
        CreateMap<DbUserRole, Endpoints.Users.UserRole>()
            .ConstructUsing(r => new Endpoints.Users.UserRole(r.Name, UserRoleCategoryTypes.FromValue(r.CategoryId).Name, r.Active));
```

### Version: 11.0.0
using ProjectTo, the EF Core v6.0.2
--> 

### Expected behavior

Include Filter is maintained

### Actual behavior

I get back all associated items.

### explanation

I'll attempt to create a GIST soon if needed, but this appears to be straight forward.  If I remove the ProjectTo above and just view the raw DB entities I only have 1 user role.  Add the ProjectTo line back in and I have 2, an active role and their previous now inactive role.

**Comment by jbogard** [comment]
Try doing this projection without AutoMapper (using Select). EF Core might not support this behavior.

**Comment by Allann** [comment]
From the release notes:
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#filtered-include

But you are correct, Select does not work either.  I'm happy for you to close.

btw, I tried Map after the fetch and it works fine.  Not a big deal in my scenario, only ever doing a single record.

**Comment by Allann** [comment]
I found the root cause, it was that I had not added .AsNoTracking() on the query.  There is a Caution in the full doco regarding this exact scenario.  RTM I suppose.

**Comment by jbogard** [comment]
Oh that's interesting, because I never bother with `AsNoTracking` when using `ProjectTo` because I assumed that once you have a `Select` that EF knows not to track since it's going straight to DTO.

TIL

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/discussions/3713#discussioncomment-1141771
