### ISSUE TITLE
Breaking changes in nullable int to string mapping in version 11 when value is null

### ISSUE THREAD

**Issue by alexandrepepin-boxoffice** [AutoMapper/AutoMapper#3906]
### Source/destination types

```csharp
public class PersonDTO
{
    public int? AgeNullableInt { get; set; }
}

public class Person
{
    public string AgeString { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<PersonDTO, Person>()
    .ForMember(dest => dest.AgeString,
        opt => opt.MapFrom(src => src.AgeNullableInt.ToString()));
```

### Expected behavior

- When AgeNullableInt is null, I expect AgeString to be empty string
- Version 10.1.1 was returning empty string
- Manually doing AgeNullableInto.ToString() when null returns empty string

### Actual behavior

- Version 11.0.0 now returns null instead of empty string

### Steps to reproduce

```csharp
var mapperConfiguration = new MapperConfiguration(o =>
{
    o.AddProfile<PersonProfile>();
});

var mapper = mapperConfiguration.CreateMapper();

var personDTO = new PersonDTO
{
    AgeNullableInt = null
};

// actual.AgeString is null here. Should be empty string
var actual = mapper.Map<Person>(personDTO);

// Manually doing ToString like in my mapping profile returns empty string. value here is empty string
var value = personDTO.AgeNullableInt.ToString();
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/discussions/3902

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/discussions/3899

**Comment by alexandrepepin-boxoffice** [comment]
Thanks for the workaround.
IMO, I would argue that AutoMapper should run my mapping code. It is really sneaky that it doesn't run the ToString when it works when doing it manually on the nullable int. It might generates a lot of unnoticed breaking change when upgrading to version 11

What is the reasoning behind this decision?
