### ISSUE TITLE
Regression when mapping to valuetypes from Nullable<T>.GetValueOrDefault()

### ISSUE THREAD

**Issue by ovska** [AutoMapper/AutoMapper#3931]
### Source/destination types

```csharp
public class Source
{
    public bool? Enabled { get; set; }
}

public class Destination
{
    public bool Enabled { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Source, Destination>()
    .ForMember(
        dst => dst.Enabled,
        x => x.MapFrom(src => src.Enabled.GetValueOrDefault()));
```

### Version: >=11.0.0

Reproducible on `11.0.0` and `11.0.1`, works correctly on `10.1.1`.

### Expected behavior

Destination property should always be mapped. If source property is null, `GetValueOrDefault()` should ensure that the valuetype's default value is used, but it looks like nulls are ignored altogether in this case.

### Actual behavior

Destination property is not modified if source property is null.
Using `src => src.Enabled ?? default` works, while `GetValueOrDefault` does not. This can be used as a "workaround" (and can be argued is more readable), but nevertheless this is a regression in 11.0.0 that was luckily caught in unit tests.
Reproducible on all nullable types I've tried.

### Steps to reproduce

```csharp
var src = new Source { Enabled = true };
var dst = new Destination();
mapper.Map(src, dst);
Console.WriteLine(
    "Source is {0}, destination is {1}",
    src.Enabled.GetValueOrDefault(), 
    dst.Enabled);

src.Enabled = null;
mapper.Map(src, dst);
Console.WriteLine(
    "Source is {0}, destination is {1}",
    src.Enabled.GetValueOrDefault(),
    dst.Enabled);
```
Prints:
```
Source is True, destination is True
Source is False, destination is True
```
A full gist to copypaste into a NET6 console app Program.cs can be found here: https://gist.github.com/ovska/96595ff3b5927d0333cf49bfb169b97f

**Comment by ovska** [comment]
From the top of my head, this could have something to do with the fact that the property can equal null but `GetValueOrDefault`-method can still be called.

**Comment by alexandrepepin-boxoffice** [comment]
We have a similar behavior when calling a nullable int ToString method. If the int is null, ToString returns string empty. Not null. With AutoMapper 11.0, it no longer calls the ToString method and just set it to null.

You are making a potentially dangerous breaking changing by not calling our code that doesn't throw NRE even if the value is null and just arbitrary map it to null.

**Comment by ovska** [comment]
I agree, a big non-documented change that breaks valid code for seemingly no reason at all (why even null check structs?). The [dev response](https://github.com/AutoMapper/AutoMapper/discussions/3899#discussioncomment-2316370) for reports of obvious bugs in 11+ also seems apathetic at best.
