### ISSUE TITLE
AutoMapper.Extensions.Microsoft.DependencyInjection is still 11.0.0

### ISSUE THREAD

**Issue by americanslon** [AutoMapper/AutoMapper#3975]
https://github.com/AutoMapper/AutoMapper/issues/3817 - This is still happening in AutoMapper.Extensions.Microsoft.DependencyInjection as there seems to be no 11.0.1 of this package. 

Any chance it can get updated to use 11.0.1 AutoMapper? Thanks!

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/164
