### ISSUE TITLE
Property is not updated, if .MapFrom expression returns null

### ISSUE THREAD

**Issue by Peter-B-** [AutoMapper/AutoMapper#4030]
Hi,

I think there is a different, maybe broken, behavior in AutoMapper 11, which I cannot find in the upgrade guide.

When I map a property using a .MapFrom() expression, which contains a method call or a child property accessor, and the returned value is `null`, the target value is not updated to `null` but stays unmodified.

Is this expected behavior or an "issue"?

Kind regards
Peter

### Source/destination types

Source types
```csharp
public class Source
{
	public string? Text { get; set; }
}

public class ParentSource
{
	public ChildSource? Child { get; set; }
}

public class ChildSource
{
	public string? Text { get; set; }
}
```

Target Type
```csharp
public class Target
{
	public string? Text { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Source, Target>()
    .ForMember(x => x.Text, c => c.MapFrom(x => x.Text.NullIfEmpty()))
```

```csharp
cfg.CreateMap<ParentSource, Target>()
    .ForMember(x => x.Text, c => c.MapFrom(x => x.Child.Text))
```

### Expected behavior

```csharp
var source = new Source { Text = null };
var target = new Target { Text = "should be removed" };

mapper.Map(source, target);
```

Expected: `target.Text` should be `null`.

```csharp
var source = new ParentSource { Child = null };
var target = new Target { Text = "should be removed" };

mapper.Map(source, target);
```

Expected: `target.Text` should be `null`.

### Actual behavior

`target.Text` is still `"should be removed"`.

### Steps to reproduce

Run [Gist](https://gist.github.com/Peter-B-/098ca645c16be649268d314c7d534abc)

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by Peter-B-** [comment]
Hi Lucian,

thanks for your prompt reply and sorry for having bothered you. I even tried the nuget feed, but forgot to check "include Prerelease" in LinqPad.

Thanks a lot for your support
Peter
