### ISSUE TITLE
Behaviour of IgnoreAllPropertiesWithAnInaccessibleSetter changed between versions 10 and 11

### ISSUE THREAD

**Issue by mikenorgate** [AutoMapper/AutoMapper#4034]
In version 11 of Automapper the `IgnoreAllPropertiesWithAnInaccessibleSetter` behaviour has changed to now ignore properties with an internal setter.

In version 10 the `nonPublic` argument of `GetSetMethod` was set to true when checking if a properties setter is accessible https://github.com/AutoMapper/AutoMapper/blob/f31e398a596438a939bf19d5bb97ed218124731d/src/AutoMapper/Internal/ReflectionHelper.cs#L31

In version 11 the `nonPublic` argument has not been set and defaults to false, returning only the public setters https://github.com/AutoMapper/AutoMapper/blob/b8f8546da66cccbe8c274358f5448feac993fee7/src/AutoMapper/Configuration/MappingExpressionBase.cs#L469

Was this change intentional?

**Comment by lbargaoanu** [comment]
Yes. If it's not public it's ignored.
