### ISSUE TITLE
Can't Install Latest Version on .NET Framework

### ISSUE THREAD

**Issue by InteXX** [AutoMapper/AutoMapper#4045]
I'm getting an error when attempting to install the latest version:

>Could not install package 'AutoMapper 11.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Have you for some reason been forced to exclude those working with the .NET Framework from being able to use AutoMapper?

From what I can glean from the .NET Standard tables ([link](https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions)), by upgrading to .NET Standard 2.1 you gained nothing and in turn forfeited support for .NET Framework apps.

It would seem that you're unnecessarily alienating a lot of developers by going with .NET Standard 2.1.

Are you able to downgrade?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/discussions/3873
