### ISSUE TITLE
Reversing order of interface list in MapperConfiguration.GetTypeInheritance is a breaking change

### ISSUE THREAD

**Issue by ercquest** [AutoMapper/AutoMapper#4063]
### Source/destination types

        public void Interface_mapping_test()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.Internal().ForAllMaps((x, y) =>
                {
                    if (x.DestinationType.IsInterface)
                        y.AsProxy();
                });
                cfg.CreateMap<IMapTestInterfaceParent, ClassToMapTo>(MemberList.Destination);
                cfg.CreateMap<IMapTestInterfaceChild, ClassToMapTo>(MemberList.Destination);

            });
            var mapper = config.CreateMapper();
            var mapTestDto = new MapTestDto
            {
                WillBeMapped = 1,
                WontBeMapped = 2
            };

            var classToMapTo = mapper.Map<ClassToMapTo>(mapTestDto);
            var classToMapToExplicitSourceType = mapper.Map<IMapTestInterfaceParent, ClassToMapTo>(mapTestDto);
            classToMapTo.WillBeMapped.ShouldBe(1);
            classToMapToExplicitSourceType.WillBeMapped.ShouldBe(1);

            classToMapTo.WontBeMapped.ShouldBe(2);
            classToMapToExplicitSourceType.WontBeMapped.ShouldBe(2);

        }
        internal class MapTestDto : IMapTestInterfaceParent
        {
            public int WillBeMapped { get; set; }
            public int WontBeMapped { get; set; }
        }

        public interface IMapTestInterfaceParent : IMapTestInterfaceChild
        {
            int WontBeMapped { get; set; }
        }

        public interface IMapTestInterfaceChild
        {
            int WillBeMapped { get; set; }
        }

        public class ClassToMapTo
        {
            public int WontBeMapped { get; set; }
            public int WillBeMapped { get; set; }
        }

### Expected behavior

Run the test above. I expect it to use the map to IMapTestInterfaceParent.

### Actual behavior

It uses the map to IMapTestInterfaceChild, which is causing us to have unmapped properties
### Steps to reproduce

See test. It fails on both of these lines:
classToMapTo.WontBeMapped.ShouldBe(2);
        classToMapToExplicitSourceType.WontBeMapped.ShouldBe(2);

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by lbargaoanu** [comment]
The way I see it, nobody should write this kind of code. See https://github.com/AutoMapper/AutoMapper/issues/3886#issuecomment-1033747916 for s similar discussion.

**Comment by ercquest** [comment]
It makes a lot of sense to me to expect that if I have an interface A that implements interface B, then a mapping like `_mapper.Map<A>` will use the A interface mapping, and not the B mapping. Are you saying that mapping should never be expected to work with inheritance? Because version 11 doesn't break this logic for class objects, just interfaces. But if I shouldn't expect that to work with classes either, there's even more redesign we have to consider.

**Comment by jbogard** [comment]
It might make sense to you that it uses the interface mapping, but enough people did not want that behavior that AutoMapper standardized on strictly using the runtime types. That also fixes a lot of other scenarios such as proxy types, polymorphism etc. Things get even more complicated when you define collections of interfaces and the items in the collection are different implementations.

We also did not want different behavior for calling `mapper.Map` versus mapping done internally. That's also confusing and not obvious.

**Comment by ercquest** [comment]
Thanks for the responses. What you're saying then, is that changing the direction of the for loop back would break other things?
