### ISSUE TITLE
IncludeBase open generic map

### ISSUE THREAD

**Issue by ExLuzZziVo** [AutoMapper/AutoMapper#4065]
Hi, I'm getting the `System.ArgumentException` when initializing the `MapperConfiguration` with the configuration below.
The exception says that the property `OrderNumber` is not defined for type 'InternetOrder', but this property is defined in its parent class.

```csharp
Property 'System.String OrderNumber' is not defined for type 'InternetOrder' (Parameter 'property')

   in System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   in AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(MemberMap memberMap, Expression destination, MemberInfo destinationMember)
   in AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression createDestination)
   in AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
   in AutoMapper.TypeMap.Seal(IGlobalConfiguration configurationProvider, HashSet`1 typeMapsPath)
   in AutoMapper.MapperConfiguration.Seal()
   in AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
```

### Source/destination types

```csharp
// Source types

public abstract class OrderModel<T>
{
    public string Number { get; set; }
}

public class InternetOrderModel: OrderModel<int>
{
}

//Destination types

public abstract class Order<T>
{
    public string OrderNumber { get; set; }
}

public class InternetOrder : Order<int>
{
}
```

### Mapping configuration

```csharp
var mapper = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap(typeof(OrderModel<>), typeof(Order<>))
            .ForMember("OrderNumber", o => o.MapFrom(s => s.GetType().GetProperty("Number").GetValue(s, null)));

        cfg.CreateMap<InternetOrderModel, InternetOrder>()
            .IncludeBase(typeof(OrderModel<>), typeof(Order<>));
    }).CreateMapper();
```

### Version: x.y.z

Target framework: net6.0
AutoMapper version: 11.0.1

### Expected behavior

The base class has property with such name, so it is defined

### Actual behavior

Creating the instance of `MapperConfiguration` class throws the `System.ArgumentException` saying that the property 'System.String OrderNumber' is not defined for type 'InternetOrder'

**Comment by lbargaoanu** [comment]
A PR is welcome.
The workaround is to avoid including open generics.

**Comment by lbargaoanu** [comment]
I don't see why you would need to include an open generic here. Just use

     
        cfg.CreateMap<InternetOrderModel, InternetOrder>()
            .IncludeBase(typeof(OrderModel<int>), typeof(Order<int>));

**Comment by ExLuzZziVo** [comment]
@lbargaoanu, I have provided VERY simplified example to show the problem. In my project I have abstract generic classes that have many inherited classes that can be abstract and generic too

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
And if thet doesn't work, make another repro.
And as I've said, a PR is welcome.

**Comment by ExLuzZziVo** [comment]
@lbargaoanu, there is no issue with the MyGet build. Thank you
