### ISSUE TITLE
Empty string to nullable types conversion using Automapper.

### ISSUE THREAD

**Issue by Mady007** [AutoMapper/AutoMapper#408]
I'm trying to convert properties on source object of strings to destination object properties of nullable datatypes(int?,bool?,DateTime?). properties of type string on my source can be empty and when they are empty an equivalent null should be mapped on destination property.It works fine when property has value but when it is empty
It throws an exception {"String was not recognized as a valid Boolean."}

```
public class SourceTestString
{
  public string IsEmptyString {get; set;}
}

public class DestinationTestBool
{
  public bool? IsEmptyString {get; set;}
}
```

My Converter class

```
public class StringToNullableBooleanConverter : ITypeConverter<string,bool?>
 {
     public bool? Convert(ResolutionContext context) 
     {
        if(String.IsNullOrEmpty(System.Convert.ToString(context.SourceValue)) ||  String.IsNullOrWhiteSpace(System.Convert.ToString(context.SourceValue)))
         {
            return default(bool?);
         }
         else
         {
            return bool.Parse(context.SourceValue.ToString()); 
         }
      }
  }
```

Create Map 

```
AutoMapper.Mapper.CreateMap<string,bool?>().ConvertUsing(
     new  StringToNullableBooleanConverter());
AutoMapper.Mapper.CreateMap<SourceTestString,DestinationTestBool>();
```

Map Method

```
SourceTestString source = SourceTestString();
source.IsEmptyString = ""; 
var destination = Mapper.Map<SourceTestString,DestinationTestBool>(source);
```

**Comment by ahatwadkar** [comment]
I am getting this error while using your above code.

'ResolutionContext' does not contain a definition for 'SourceValue' and no extension method 'SourceValue' accepting a first argument of type 'ResolutionContext' could be found (are you missing a using directive or an assembly reference?)

**Comment by Mady007** [comment]
From Automapper 5.0 the implementation has changed. Please see answer from Jimmy Bogard 
[here](https://stackoverflow.com/questions/38716326/itypeconverterpizzavm-pizza-convertpizzavm-pizza-resolutioncontext#answer-38776407). Please review the documentation [here](https://github.com/AutoMapper/AutoMapper/blob/master/docs/5.0-Upgrade-Guide.md)

Hope this helps!
