### ISSUE TITLE
Warning	NU1608	Detected package version outside of dependency constraint: AutoMapper.Extensions.EnumMapping 2.0.1 requires AutoMapper (>= 11.0.0 && < 12.0.0) but version AutoMapper 12.0.0 was resolved.

### ISSUE THREAD

**Issue by aluty** [AutoMapper/AutoMapper#4089]
Automapper 12.0.0 just released: https://www.nuget.org/packages/AutoMapper

Manage Nuget packages for [Visual Studio 2022] solution -> Update

BEFORE:
    PackageReference Include="AutoMapper" Version="11.0.1"
    PackageReference Include="AutoMapper.AspNetCore.OData.EFCore" Version="3.0.5"
    PackageReference Include="AutoMapper.Extensions.EnumMapping" Version="2.0.1"
    PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="5.1.0"
    PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0"
AFTER:
    PackageReference Include="AutoMapper" Version="12.0.0"
    PackageReference Include="AutoMapper.AspNetCore.OData.EFCore" Version="4.0.0"
    PackageReference Include="AutoMapper.Extensions.EnumMapping" Version="2.0.1"
    PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="6.0.0"
    PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0"

### Expected behavior
Smooth upgrade: AutoMapper.11.0.1 -> AutoMapper.12.0.0
AutoMapper.Extensions.EnumMapping needs updating too?

### Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1608	Detected package version outside of dependency constraint: AutoMapper.Extensions.EnumMapping 2.0.1 requires AutoMapper (>= 11.0.0 && < 12.0.0) but version AutoMapper 12.0.0 was resolved.

### Steps to reproduce
Updates:
AutoMapper.11.0.1 -> AutoMapper.12.0.0
AutoMapper.AspNetCore.OData.EFCore.3.0.5 -> AutoMapper.AspNetCore.OData.EFCore.4.0.0
AutoMapper.Extensions.ExpressionMapping.5.1.0 -> AutoMapper.Extensions.ExpressionMapping.6.0.0
AutoMapper.Extensions.Microsoft.DependencyInjection.11.0.0 -> AutoMapper.Extensions.Microsoft.DependencyInjection.12.0.0

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/issues/17
