### ISSUE TITLE
Mapping throws if nested type is null and it has members included.

### ISSUE THREAD

**Issue by fiseni** [AutoMapper/AutoMapper#4103]
Hi,

There is a new behavior in version `12.0.0` regarding the nested types that break existing code. If this is by design, then I apologize. Perhaps we can list it as a breaking change in the release notes?

**Scenario:**
- The Source has a nested type which in turn has another nested type.
- The Destination has a nested type that is flattened.
- If the source's nested type is null, instead of just setting the destination value to null it throws an exception.

The last major version `11.0.1` correctly sets the destination member to null.

**Full Sample:**
```c#
using AutoMapper;

Console.WriteLine();

var config = new MapperConfiguration(x => x.AddProfile(new MappingProfile()));
var mapper = new Mapper(config);

Works();
Throws();

void Works()
{
    var customer = new Customer();
    var customerDto = mapper!.Map<CustomerDto>(customer);
}

void Throws()
{
    var customer = new Customer()
    {
        Foo = null
    };

    // If IncludeMembers section is removed from the profile, it works.
    var customerDto = mapper!.Map<CustomerDto>(customer);
}

class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<Bar, FooDto>();
        CreateMap<Foo, FooDto>()
            .IncludeMembers(x => x.Bar);
        CreateMap<Customer, CustomerDto>();
    }
}
class CustomerDto
{
    public string? Name { get; set; }
    public FooDto? Foo { get; set; }

}
class FooDto
{
    public string? FooName { get; set; }
    public string? BarName { get; set; }
}
class Customer
{
    public string Name { get; set; } = "Name1";
    public Foo? Foo { get; set; } = new();
}
class Foo
{
    public string FooName { get; set; } = "FooName1";
    public Bar? Bar { get; set; } = new();
}
class Bar
{
    public string BarName { get; set; } = "BarName1";
}
```

**Comment by lbargaoanu** [comment]
You either use the default flattening or IncludeMembers. Both at the same time makes no sense.

**Comment by fiseni** [comment]
I'm sorry I didn't understand. I'm not using default flattening. In the above cases, for both scenarios, I'm using `IncludeMembers`.

To simplify, I want to use `IncludeMembers`, and the source's inner type can be null. It's a valid code.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by fiseni** [comment]
I just tried it. It works correctly, it sets the destination member to null.
