### ISSUE TITLE
12.0 breaks filtering calls after projectto for record types

### ISSUE THREAD

**Issue by cm-andrews** [AutoMapper/AutoMapper#4104]
Issue was reported before in #4098, but discussion was closed before i could add my repro gist:
https://gist.github.com/cm-andrews/edcc54c118417ca0d6974fac64d5ee63

The issue arises if any kind of filtering or ordering is applied after ProjectTo is called for record types, e.g., OrderBy or SingleOrDefaultAsync.
Switching to a class or applying the operations before the ProjectTo call works as always.

**Comment by jbogard** [comment]
Yeah this does look like a regression if it worked before - what was the LINQ in v11 vs v12?

**Comment by cm-andrews** [comment]
In V12 the LINQ for
`Objects.ProjectTo<DoesNotWorkDto>(mapperConfiguration).Where(x => x.Id == 1)`
with the record
`public record DoesNotWorkDto(int Id);`
is:
`DbSet<MyObject>().Select(dtoMyObject => new DoesNotWorkDto{ }).Where(x => x.Id == 1)`
in V11 the LINQ is
`DbSet<MyObject>().Select(dtoMyObject => new DoesNotWorkDto{ Id = dtoMyObject.Id }).Where(x => x.Id == 1)`

**Comment by jbogard** [comment]
Does it work with the `Where` is before `ProjectTo`? Generally we recommend putting `ProjectTo` last because LINQ providers can have all sorts of problems projecting earlier.

**Comment by lbargaoanu** [comment]
The mapping works fine.

**Comment by cm-andrews** [comment]
Yes, calling ProjectTo after filtering works in all cases. Guess I will move around our code a little, shouldn't be a problem. It's just a weird issue as it only seems to affect records in v12.

**Comment by jbogard** [comment]
I've seen many weird issues putting `Select` before `Where` for LINQ providers in general, so I've tended to put them last anyway. We can update the docs to make this clear.

**Comment by jbogard** [comment]
It's in the docs, but I'll highlight it more.

**Comment by cm-andrews** [comment]
Thanks, from reading the docs i thought you were stating that you can't filter on properties of the entities after projection, which is obvious, did not know about the random other issues.

**Comment by cm-andrews** [comment]
Thanks, that's a great example!

**Comment by stevendarby** [comment]
@jbogard I know there are other providers, but fwiw, it isn't really the case with EF Core. It's been very good at handling all sorts of operations after projection since EF Core 5.

A simple example:

```C#
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

{ 
    var mapper = new MapperConfiguration(x => x.CreateMap<Blog, BlogDto>()).CreateMapper();
    using var context = new MyContext();
    context.Database.EnsureCreated();

    var blogs = context.Blogs.ProjectTo<BlogDto>(mapper.ConfigurationProvider)
        .Where(x => x.Title == "AutoMapper")
        .ToList();
}
public class MyContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     => optionsBuilder
        .UseSqlServer("Server=dev-sd-mssql-deployment,31433;User Id=sa;Password=gandalf456$;Database=Projection")
        .LogTo(Console.WriteLine, LogLevel.Information);    
}
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
}
public class BlogDto
{
    public string Title { get; set; }
    public string Content { get; set; }
}
```

Produces SQL:

```SQL
SELECT [b].[Title], [b].[Content]
FROM [Blogs] AS [b]
WHERE [b].[Title] = N'AutoMapper'
```

Filtering and ordering after projection is important for us as we use OData and don't want to expose the entities. I have seen packages like `AutoMapper.Extensions.OData` which do expression mapping and so on- which genuinely helped for some scenarios in EF Core 3.1 and earlier, but I've found EF Core 5.0+ to be pretty robust without it. Thought it was worth sharing that.

**Comment by lbargaoanu** [comment]
https://github.com/dotnet/efcore/issues/27281

**Comment by SerhiyBalan** [comment]
Well everything worked well in Automapper 11

To make it comparable with Automapper 12 I had to make changes everywhere from

```
   .ProjectTo<SomeDtoModel>(_mapper.ConfigurationProvider)
   .FirstOrDefaultAsync(entity => entity.Id == id);
```

to

```
   .Where(entity => entity.Id == id)
   .ProjectTo<SomeDtoModel>(_mapper.ConfigurationProvider)
   .FirstOrDefaultAsync();
```

**Comment by lbargaoanu** [comment]
And that's the right change to make. You shouldn't have written that code in the first place :) You can get the old behaviour by disabling constructor mapping. But of course that's not a good idea. AM 11 mapped members twice with `ProjectTo`, once with the constructor and then with the coresponding property.
The fact that EF Core cannot filter when using constructor mapping has little to do with AM. But it's yet another reason to always filter entities.
