### ISSUE TITLE
Issue in 12.0.0

### ISSUE THREAD

**Issue by patricsjoo** [AutoMapper/AutoMapper#4121]
### Source/destination types

```csharp
// Put your source/destination types here
sourceObject = null;
destinationObject = new();
Mapper.Map<SourceObject, DestinationObject>(sourceObject, destinationObject);
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
CreateMap<SourceObject, DestinationObject>().ReverseMap();
```

### Version: x.y.z
AutoMapper:  11.0.1 -> 12.0.0
EfCore: 6.0.10

### Expected behavior
destinationObject should be null.

### Actual behavior
destinationObject is still new().

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by patricsjoo** [comment]
Since we don't using MyGet, I need to wait on preRelease in Nuget.org then.

**Comment by jbogard** [comment]
MyGet IS our prerelease builds. We don't prerelease on NuGet.
