### ISSUE TITLE
Null source object no longer sets destination property null if property type has a map 

### ISSUE THREAD

**Issue by npbenjohnson** [AutoMapper/AutoMapper#4130]
### Source/destination types and Mapping configuration

```csharp
[AutoMap(typeof(Test1Update))]
public class Test1 { public Test2? Test2 { get; set; } }
public class Test1Update { public Test2Update? Test2 { get; set; } }
[AutoMap(typeof(Test2Update))]
public class Test2 { }
public class Test2Update { }
```

### Version: x.y.z
Behavior change from Automapper 11.0.1 -> 12.0.0
 

### Expected behavior
Mapping a Test1 object with a null Test2 property onto an existing Test1 object should set the property null.

### Actual behavior
Test1.Test2 remains unchanged.
Note - If the map for Test2 `[AutoMap(typeof(Test2Update))]` is removed, this works as expected.

### Steps to reproduce

```csharp
        [TestMethod]
        public async Task Test()
        {
            var test1 = new Test1 { Test2 = new Test2() };
            var mapper = new Mapper(new MapperConfiguration((o) => o.AddMaps(Assembly.GetExecutingAssembly())));
            var result = mapper.Map(new Test1Update(), test1);
            Assert.IsNull(result.Test2);
        }
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
