### ISSUE TITLE
Suppress generic constraint exceptions in GetPublicNoArgExtensionMethods in 6.2.x

### ISSUE THREAD

**Issue by dingmeng-xue** [AutoMapper/AutoMapper#4135]
Hi AutoMapper team,

Our product is on .NET standard 2.0 and using AutoMapper 6.2.2. I know you have suppressed exception by #3999. Is it possible to back port fix to old version? We cannot upgrade version because it will block lots of customers.

If no, can we fork AutoMapper 6.2.2 and try to fix it by ourselves? I hope to solicit your thought before taking action.

P.S. I didn't find good place to raise the question and have to post it here.

**Comment by lbargaoanu** [comment]
Definitely have your own fork.

**Comment by lbargaoanu** [comment]
Another option is to upgrade to 8.1.0 and then you can use `ShouldMapMethod`.
