### ISSUE TITLE
ProjectTo<T> with OData

### ISSUE THREAD

**Issue by kinglinglive** [AutoMapper/AutoMapper#4140]
![image](https://user-images.githubusercontent.com/50543168/201273774-489fea5d-2da9-40f6-9c1c-cef859b1cc73.png)
![Uploading image.png…]()

The ExplicitExpansion() feature is used, changing the behavior of its default expanded query. But OData Expand is also affected by it.
What can I do to not expand the navigation property by default and have OData Expand work properly?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
