### ISSUE TITLE
Using both As and IncludeBase no long works with AutoMapper v12.0.0

### ISSUE THREAD

**Issue by blemasle** [AutoMapper/AutoMapper#4164]
Using `As` to choose the concrete type to use in a mapping and including this very mapping in an `IncludeBase` fails on AutoMapper v12.0.0 where it succeeds with AutoMapper v11.0.1

I did not find anything related to this behavior change in either the changelog or the upgrade guide.

### Source/destination types

```csharp
class Source { }
abstract class Dest { }
class DestA : Dest { }
```

### Mapping configuration

```csharp
CreateMap<Source, Dest>()
    .As<DestA>();

CreateMap<Source, DestA>()
    .IncludeBase<Source, Dest>();
```

### Expected behavior

The mapper configuration should succeeds, and the resulting mapper should be able to map `Source` to `DestA`.

### Actual behavior

> System.InvalidOperationException: 'Missing map from Source to Dest. Create using CreateMap<Source, Dest>.'

### Steps to reproduce

Just create the mapper to see it fails.  
Also, the following call works with AutoMapper v11 and the mapping described above.  
It fails with AutoMapper v12 because the only way to get the mapper configuration to work is to remove the `As`, which obviously leads to "Cannot create instance of abstract type Dest".

```csharp
var dest = mapper.Map<Dest>(new Source());
```

**Comment by lbargaoanu** [comment]
No, you should remove `IncludeBase`. I don't think the initial config made much sense. You redirected the map, so the target map will be used. Then you want to go back and include the initial map. That worked by accident.
You can also drop `As`, use `IncludeBase` and map to the concrete type.

**Comment by blemasle** [comment]
Well in this very simple example I agree it does not make much sense.

But consider the case where `CreateMap<Source, Dest>()` has some custom mapping configuration and you want to share those mappings between several subclasses of `Dest`.

The `As` part cannot just be removed as you suggested in cases where you do not know the concrete type at compile time. In those cases, you need the `As` part to be able to ask AutoMapper to map to the abstract type and let it choose the concrete type.

So at first glance both parts appear to be redondant but there are not and serve two very distinct purposes : sharing mapping configuration, and deciding which type to use at runtime.

I can provide a more thorough example if you wish 🙂

**Comment by blemasle** [comment]
Here is an almost real-world example of what I have at hand.
I just omitted the custom mapping configuration of `CreateMap<Source<TSource>, Dest>()` for brievety.

With AutoMapper v11, mapping to `Dest` without knowing the destination type at runtime works as a charm, and the correct type is selected as intended.

With AutoMapper v12, either the MapperConfiguration throw an exception or the mapping itself fail to run.
If I remove the `As<TDest>()` I get `: 'Cannot create an instance of abstract type Dest.'` and would be forced to map using the concrete type, which I can not.
If I remove the `IncludeBase` I would lose the custom mapping for the `Test` property.

```csharp
using AutoMapper;

var config = new MapperConfiguration(cfg =>
{
    cfg.AddProfiles(new Profile[] { new StringSourceDestProfile(), new IntSourceDestProfile() });
});

var mapper = config.CreateMapper();
var dest1 = mapper.Map<Dest>(new Source<string>());
var dest2 = mapper.Map<Dest>(new Source<int>());

class SourceDestProfile<TSource, TDest> : Profile
    where TDest : Dest
{
    public SourceDestProfile()
    {
        CreateMap<Source<TSource>, Dest>()
            .ForMember(d => d.Test, opt => opt.MapFrom(s => "Hello World !"))
            .As<TDest>();
    }
}

class StringSourceDestProfile : SourceDestProfile<string, DestA>
{
    public StringSourceDestProfile()
    {
        CreateMap<Source<string>, DestA>()
            .IncludeBase<Source<string>, Dest>();
    }
}

class IntSourceDestProfile : SourceDestProfile<int, DestB>
{
    public IntSourceDestProfile()
    {
        CreateMap<Source<int>, DestB>()
            .IncludeBase<Source<int>, Dest>();
    }
}


class Source<TSource> { }
abstract class Dest 
{
    public string Test { get; set; }
}
class DestA : Dest { }
class DestB : Dest { }
```

**Comment by lbargaoanu** [comment]
`As` is not `ConstructUsing`. You seem to need `ConstructUsing`, not `As`.

**Comment by lbargaoanu** [comment]
`As` does redirect the map, But that doesn't mean that it should support a case such as yours. I suggest that you rewrite your mappings. You can reuse some other map, use only one map or whatever works for you.

**Comment by blemasle** [comment]
Well, I disagree but you have the final word here obviously 😛 I see this won't be fixed despite the fact that is used to work with v11. Hopefully I'll find another way to write those mappings. 

This has become more difficult beginning with v11 as a `CreateMap<x, y>` cannot be called twice because it triggers `You cannot include a TypeMap into itself`, thus reducing the possibilities to share or split mappings into several independant parts.

**Comment by lbargaoanu** [comment]
I'm ready to say that as long as `As` redirected the map, its job is done. I'm sure you'll find a way to rewrite your mappings. You'll be replacing some complicated code with some other complicated code. Not much of a difference if you ask me. Maybe you should consider that profiles and maps do have a cost and it might benefit you to simplify things. An `As` map is now cheap and that's the change that broke your use case.
Calling `CreateMap` twice for the exact same types is possible, but equally weird. That error means exactly what it says, you're doing smth wrong. Unless you have a test that proves otherwise.
