### ISSUE TITLE
Provide a method/property to check if options are set on ResolutionContext

### ISSUE THREAD

**Issue by wojtek-abakus** [AutoMapper/AutoMapper#4165]
After upgrading to AutoMapper 12.0.0 i've read the upgrade guide and changed ResolutionContext.Options.Items to ResolutionContext.Items . Unfortunatelly this property throws an exception if options aren't set.

Could you provide a method to check if you can call ResolutionContext.Items safetly (HasOptions or HasItems) ?

In my scenario I have added common configuration for all type maps and I'm checking if another developer passed options or not.
Checking it by catching exceptions isn't the best for performance, nor checking for _options set via reflection.

**Comment by lbargaoanu** [comment]
Check the previous discussions.
