### ISSUE TITLE
ResolutionContext.Items throws an exception after upgrade to Automapper 12

### ISSUE THREAD

**Issue by maxiptah** [AutoMapper/AutoMapper#4175]
With the upgrade to Automapper 12 Options in the ResolutionContext has been made private. Now when I access ResolutionContext.Items in my converter, it throws an InvalidOperation exception. In fact I just want to check, if Items are there and initialized or not. Before Automapper 12 I was using this code:

```
private class MyConverter : ITypeConverter<MyClass, MyDto>
    {
        public MayDto Convert(MyClass source, MyDto destination, ResolutionContext context)
        {
           if (context.Options?.Items == null || !context.Options.Items.ContainsKey("myKey"))
           {
              return null; // No mapping is possible
           }

           // Do mapping based on context
           return mappedResult;
        }
    }
```

Now I though that this would work:
`if (context.Items == null || !context.Items.ContainsKey("myKey"))`
but this throws exception even if I try to compare Items to null. 

There should be some way to check without an exception if ResolutionContext has options (and therefore Items collection is accessible) or not.

I don't know in a TypeConverter, whether it was called with the `Action<IMappingOperationOptions>` parameter or not, I need to check the context when I'm already in the TypeConverter. It's not an option just to provide a `_=>{}` everywhere, as proposed e.g. here https://github.com/AutoMapper/AutoMapper/issues/3206, because I cannot know in the caller, that calling `mapper.Map` without providing an optional parameter could cause an exception in the mapper.

Migration guide here https://docs.automapper.org/en/latest/12.0-Upgrade-Guide.html#resolutioncontext-options-was-removed does not provide guidance on how to deal with this scenario.

**Comment by lbargaoanu** [comment]
Check the previous discussions.
