### ISSUE TITLE
Behavior change for mapping from null in version 12 and above

### ISSUE THREAD

**Issue by marcovr** [AutoMapper/AutoMapper#4180]
### Source/destination types

```csharp
public class A {}
public class B {}
```

### Mapping configuration

```csharp
var mapper = new Mapper(new MapperConfiguration(c => c.CreateMap<A, B>()));
```

### Expected behavior

In version 11.0.1 this is the observed behavior:
```csharp
var result = mapper.Map<A, B>(null, new B());
result == null; // true
```
=> the result is null as expected

### Actual behavior

In version 12.0.0 and 12.0.1-preview.0.3 this happens instead:
```csharp
var result = mapper.Map<A, B>(null, new B());
result == null; // false
```
=> the result is not null, why?

### Steps to reproduce

```csharp
using AutoMapper;

var mapper = new Mapper(new MapperConfiguration(c => c.CreateMap<A, B>()));
var result = mapper.Map<A, B>(null, new B());
Console.WriteLine("Result is null?: " + (result == null));

public class A {}
public class B {}

```

**Comment by marcovr** [comment]
Please note that **I did try the latest preview version from MyGet** and that didn't solve the problem.
This seems to be a different case than https://github.com/AutoMapper/AutoMapper/issues/4082

**Comment by lbargaoanu** [comment]
Hmmm.... Interesting :) Mapping null to an _existing_ object. That doesn't exactly make sense. I guess the null check in 11.0.1 did that. But `Map` should return the destination which, of course, is that exact object you passed. The new behaviour seems correct.

**Comment by marcovr** [comment]
While I agree that the example doesn't make much sense, it seems a bit inconsistent to me.

When members of an object (which can be complex objects themselves) are mapped to null (as discussed in https://github.com/AutoMapper/AutoMapper/issues/4082) then I would expect that an entire object will also be mapped to null.

**Comment by lbargaoanu** [comment]
That makes sense, _unless_ you provide an existing destination :)
