### ISSUE TITLE
Ignoring the "null" sent value with automapper.

### ISSUE THREAD

**Issue by turkdoktoru42** [AutoMapper/AutoMapper#4186]
Hello,

I am using .net core 7 and Automapper library. I am sending a json object, it updates all rows when some values are "null". So I want to ignore values that are null. But a structure like below doesn't work. Can you help me ?

### Source/destination types

```
builder.Services.AddAutoMapper(typeof(AutoMapperProfile));
```

### Mapping configuration

```
using AutoMapper;
using InventoryManagement.Core.DTOs.BrandModel;
using InventoryManagement.Core.DTOs.Category;
using InventoryManagement.Core.DTOs.Company;
using InventoryManagement.Core.Models;

namespace InventoryManagement.Services.Mapping
{
    public class AutoMapperProfile : Profile
    {

        public AutoMapperProfile()
        {
            AllowNullCollections = true;

            CreateMap<Company, CompanyUpdateDto>().ReverseMap().ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
        }
    }
}

```

### Version:

    net core 7, 
    Automapper.Extensions 12

### Controller Code
    public async Task<IActionResult> Update([FromBody] CompanyUpdateDto updateCompany)
        {
            await _service.UpdateAsync(_mapper.Map<Company>(updateCompany));
            return CreateActionResult(CustomResponseDto<CompanyUpdateDto>.Success(204));
        }

###CompanyDTO
       public class CompanyUpdateDto
       {
        public int Id { get; set; }

        public string? Name { get; set; }

        public string? Description { get; set; }

        public DateTime? UpdatedDate { get; set; }
      }

##I am sending a json object as below. I am sending only the "ID, NAME" fields for the update process. I don't want to send other fields. but it updates as "null" in database
```
{
  "id": 1002,
  "name": "xcv"
}
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
