### ISSUE TITLE
AutoMapper 12 is not mapping null correctly

### ISSUE THREAD

**Issue by duncan-G** [AutoMapper/AutoMapper#4187]
### Source/destination types

```csharp
    public class Source
    {
        public int Id { get; set; }

        public InnerSource? InnerSource { get; set; }
    }

    public class InnerSource
    {
        public string Description { get; set; }
    }

    public class Destination
    {
        public int Id { get; set; }

        public InnerDestination? InnerDestination { get; set; }
    }

    public class InnerDestination
    {
        public string Description { get; set; }
    }
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
    var mapper = new Mapper(new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<Source, Destination>()
            .ForMember(dest => dest.InnerDestination, opts => opts.MapFrom(src => src.InnerSource));
        cfg.CreateMap<InnerSource, InnerDestination>();
    }));
```

### Version: 12.0.0
 
.NET 7

### Expected behavior

I expect when `Source.InnerSource` is null and `Destination.InnerDestination` is not null, then when mapping source to destination, `Destination.InnerDestination` will become null. This is how it used to work.

### Actual behavior
Current behavior is that `Destination.InnerDestination` does not become null.

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
      var source = new Source
      {
          Id = 1,
          InnerSource = null,
      };

      var destination = new Destination
      {
          Id = 1,
          InnerDestination = new InnerDestination
          {
              Description = "Hello World",
          },
      };

      mapper.Map(source, destination);

      Assert.Null(destination.InnerDestination); // Should be true
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by duncan-G** [comment]
MyGet build is working, when's that getting released to NuGet?

**Comment by danadesrosiers** [comment]
@lbargaoanu, thanks for fixing this bug!  This is a blocker for me, and I'm sure many others.  **When can we expect a patch release on Nuget?**  MyGet is useful for verification purposes, but I need a proper release for production code.

**Comment by lbargaoanu** [comment]
Releasing on NuGet has _nothing_ to to with the quality of the code. It's all about a fixed version.
