### ISSUE TITLE
AutoMapper Validate

### ISSUE THREAD

**Issue by r-ising** [AutoMapper/AutoMapper#4188]
https://gist.github.com/r-ising/39dcc0a3b6b2f14f08eb739b2e5043dc

### Expected behavior

No error

### Actual behavior

I get the following error on validate:

```
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
===============
Source -> Dest (Source member list)
Source -> Dest (Source member list)

Unmapped properties:
License
```

### Steps to reproduce

Execute the given sample file

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/discussions/4119
