### ISSUE TITLE
nuget restore gives a version error on .NET 7

### ISSUE THREAD

**Issue by HUSKUT** [AutoMapper/AutoMapper#4192]
Hiya, after converting a project to .NET 7 which included Automapper (updated to 12) I noticed that in the build script it refused to restore, even though in the normal restore it worked just fine. It turned out the build script used nuget restore.

The error:
```
nuget : NU1202: Package AutoMapper 12.0.0 is not compatible with net70 (.NETFramework,Version=v7.0). Package AutoMapper 12.0.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)
At line:1 char:1
+ nuget restore
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (NU1202: Package...d,Version=v2.1):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Steps to reproduce:
>Get/Make a project to .NET 7
>Install Automapper
>restore it via nuget (package manager console)

This error also happened on a colleague's computer, not only on my computer.

This issue persists on 11.0.1 and 12.0.1-preview.0.3.

if you require any more information,

Please let me know.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by HUSKUT** [comment]
Wouldn't you think this is a package issue...?

I mean the easy alternative is to not use `Nuget restore`, but that's also quite hacky in my opinion.
