### ISSUE TITLE
.NET 7 AssertConfigurationIsValid not works properly

### ISSUE THREAD

**Issue by pampua84** [AutoMapper/AutoMapper#4194]
Hi all, 
after updating my application to .NET 7 and updating AutoMapper to version 12.0.0 the following unit test:

```
public class AutomapperProfilesTests
{
    private readonly MapperConfiguration _mapperConfiguration;

    public AutomapperProfilesTests()
    {
        _mapperConfiguration = new MapperConfiguration(configuration =>
        {
            configuration.AddMaps(typeof(UserMapperProfile).Assembly);
        });
    }

    [Fact]
    public void ProfileConfigurationMustBeValid()
    {
        _mapperConfiguration.AssertConfigurationIsValid();
    }
}
```

fails, raising the following exception:

> 
> AutoMapper.AutoMapperConfigurationException
> 
> Unmapped members were found. Review the types and members below.
> Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
> For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
> 
> AddApiResourceRequest -> ApiScope (Source member list)
> Requests.ApiResources.AddApiResourceRequest -> Entities.AuthZ.ApiScope (Source member list)
> 
> Unmapped properties:
> Name
> 

 which did not happen with the previous version 11.0.1 and with .NET 6. 
If I examine my mapping actually the property is mapped:

```
CreateMap<AddApiResourceRequest, ApiScope>(MemberList.Source)
  .ForMember(dest => dest.Created, opt => opt.MapFrom(_ => DateTime.UtcNow))
  .ForMember(dest => dest.Name,
      opt =>
      {
          opt.MapFrom(request => request.Name.Contains(' ') ? request.Name.Replace(" ", "") : request.Name);
      });
```

Is this a bug or am I doing something wrong?
Thanks

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/10.0-Upgrade-Guide.html#source-validation

**Comment by lbargaoanu** [comment]
I suggest that you remove the `MapFrom` and use a value transformer instead.

**Comment by pampua84** [comment]
But with version 11.0.0 it worked
