### ISSUE TITLE
Invalid Cast when mapping to derived class

### ISSUE THREAD

**Issue by americanslon** [AutoMapper/AutoMapper#4195]
### Source/destination types

```csharp
Source

`ClaimsPrincipal`

Destination

`public class ExtendedClaimsPrincipal : ClaimsPrincipal
{
    public int ParentId { get { return int.Parse(GetClaimValue("Extension_LabIds")); } }
    public int Id { get { return int.Parse(GetClaimValue("Extension_DbID")); } }
    public string? DisplayName { get { return !string.IsNullOrWhiteSpace(GetClaimValue("Given Name")) ? GetClaimValue("Surname") + ", " + GetClaimValue("Given Name") : GetClaimValue("Surname"); } }
    public string? DisplayNameTitle { get { return !string.IsNullOrWhiteSpace(GetClaimValue("Given Name")) ? GetClaimValue("Surname") + ", " + GetClaimValue("Given Name") : GetClaimValue("Surname") + (!string.IsNullOrWhiteSpace(GetClaimValue("Job Title")) ? " (" + GetClaimValue("Job Title") + ")" : ""); } }

    public Roles Roles { get; }

    private string GetClaimValue(string type)
    {
        return this.Claims.Where(x => x.Type.ToLower() == type.ToLower()).Select(x => x.Value).FirstOrDefault();
    }
} `
```

### Mapping configuration

```csharp
`CreateMap<ClaimsPrincipal, ExtendedClaimsPrincipal>();`
```

### Version: x.y.z
12.0.0

### Expected behavior

The inhereting object `ExtendedClaimsPrincipal` to have all the base properties from `ClaimsPrincipal`

### Actual behavior

`AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ClaimsPrincipal -> ExtendedClaimsPrincipal
System.Security.Claims.ClaimsPrincipal -> TPL.Shared.Auth.ExtendedClaimsPrincipal

Type Map configuration:
ClaimsPrincipal -> ExtendedClaimsPrincipal
System.Security.Claims.ClaimsPrincipal -> TPL.Shared.Auth.ExtendedClaimsPrincipal

Destination Member:
Claims

---> System.InvalidCastException: Specified cast is not valid.`

### Steps to reproduce

```csharp
`ExtendedClaimsPrincipal uu = Mapper.Map<ExtendedClaimsPrincipal>(authState.User);`
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by americanslon** [comment]
This already was an stackoverflow to no avail.
