### ISSUE TITLE
Suppress generic constraint exception in automapper version 10.x

### ISSUE THREAD

**Issue by CopyPasteRepeat** [AutoMapper/AutoMapper#4198]
We are migrating our applications to .NET 7 and run into the already known issue linked below, which seems to be already fixed in automapper version 12. Since we are are currently forced to use version 10.x because of some .NET Framework applications using our shared libraries, we are still facing this issue. 

Could this be fixed in version 10.x as well? We would really appreciate that. 

`MaxInteger[T](System.Collections.Generic.IEnumerable1[T])' violates the constraint of type parameter 'T' `
https://github.com/dotnet/runtime/issues/69119

This is the corresponding Pull Request which fixed it for automapper version 12
https://github.com/AutoMapper/AutoMapper/pull/3999

**Comment by lbargaoanu** [comment]
You'll have to do that in your own fork.
