### ISSUE TITLE
ProjectTo dont include parent entity

### ISSUE THREAD

**Issue by kvpt** [AutoMapper/AutoMapper#4203]
Hi,

I try to map a hierarchical entity (parent => childs) and the ProjectTo is only working with childs but not with the parent.
I don't need to do recursive mapping, just the first level (the parent).

### Source/destination types
See LinqPad reproduction in attachment.

### Mapping configuration
See LinqPad reproduction in attachment.

### Version: 12.0.1
[ProjectToIssue.txt](https://github.com/AutoMapper/AutoMapper/files/10438523/ProjectToIssue.txt)

AutoMapper version  : 12.0.1
EFcore version : either 5.x or 6.x or 7.x (not Efcore dependant)

### Expected behavior
The ProjectTo method map the parent entity.

### Actual behavior
If I do the request directly with EfCore and explicitly doing the include the parent entity is included, with the ProjectTo the Entity is null.

### Steps to reproduce
LinqPad reproduction in attachment, drop it to LinqPad to execute.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by kvpt** [comment]
@lbargaoanu  Have you tried the reproduction ?
For me it's not a configuration problem it's a bug.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/blob/ed8bb627f8915c044963b1f155e2536cee7cb2df/docs/Queryable-Extensions.md#recursive-models

**Comment by kvpt** [comment]
Thanks @lbargaoanu,
I found this setting by searching in the project code.
But I save your link for future reference because it's not anywhere in the [documentation website](https://docs.automapper.org/en/latest/search.html?q=RecursiveQueriesMaxDepth).
