### ISSUE TITLE
ConvertMapper potentially dangerous default behaviour?

### ISSUE THREAD

**Issue by robvangeloven** [AutoMapper/AutoMapper#4204]
### Source/destination types

```csharp
string source = "5,5";
decimal destination;
```

### Mapping configuration

```csharp
var mapperConfiguration = new MapperConfiguration(x => { });
```

### Expected behavior

This is more of a question: the string to decimal conversion is one of the "built in" mappings, however it uses whatever culture the current thread is with no way to influence that (from the mapping configuration) that I could find.

This results in some weird behaviour when the string input is a valid decimal but in the "wrong" culture. I couldn't find anything in the docs describing this, potentially causing unexpected bugs.

This could especially be troublesome if, for whatever reason, the culture changes on a machine where the software was already deployed. Or if the machine where the software was developed and the build environment matched so the automated tests succeeded, but the target machine had an incompatible culture.

### Actual behavior

Safest would be if the ConvertMapper would exclude decimal and double as target types for conversion.

### Steps to reproduce

```csharp
using AutoMapper;
using FluentAssertions;

Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");

var mapperConfiguration = new MapperConfiguration(x => { });

var mapper = mapperConfiguration.CreateMapper();

var result = mapper.Map<decimal>("5,5"); // Dutch decimal notation

result.Should().Be(5.5M); // Will fail, because the output is 55
```

**Comment by lbargaoanu** [comment]
We're not going to change the default, but you can do that in your own code.

**Comment by robvangeloven** [comment]
Fair enough! Would it add value to add something to the docs to explain the working of ConvertMapper? The docs don't mention there are out-of-the-box conversions for (mostly) primitive types that have the caveat they might use the current thread culture for the conversion. I'd be willing to create PR for that if needed.

**Comment by lbargaoanu** [comment]
I don't think so. That's also the default for a lot of .Net methods that do the same, including the `Convert` class. AM doesn't do anything special in this regard.
