### ISSUE TITLE
Upgrade from 12.0.0 to 12.0.1 throws Exception constructing `MapperConfiguration`

### ISSUE THREAD

**Issue by pinkfloydx33** [AutoMapper/AutoMapper#4206]
After upgrading from `12.0.0` to `12.0.1` we have been unable to even construct a `MapperConfiguration` from our existing profiles. I've been able to isolate the problem down to a combination of:

1. An `enum` that uses `ConvertUsing` in combination with `CreateProjection`
2. A call to `CreateProjection` for a class that has a property of the  `enum` 
3. A call to `ForAllMaps`

The exception does not occur if you remove any **one** of the above items. It also does not occur if you remove the enum property from the class in `2`.

 See the More Details section below for an explanation.

### Source/destination types

```csharp
public class Source
{
    public string Name { get; set; }
    public SourceEnum Value { get; set; }
}

public class Dest
{
    public string Name { get; set; }
    public DestEnum Value { get; set; }
}

public enum SourceEnum { A, B }
public enum DestEnum   { A, B }
```

### Mapping configuration

```csharp
var cfgExp = new MapperConfigurationExpression();
cfgExp.AddProfile<ExampleProfile>();

_ = new MapperConfiguration(cfgExp); // exception thrown here, but see below

public class ExampleProfile : Profile
{
    public ExampleProfile()
    {
        CreateProjection<SourceEnum, DestEnum>() // 1; Necessary for Postgres-style Enums which are not int-based
            .ConvertUsing(
                  src => src == SourceEnum.A ? DestEnum.A : DestEnum.B
            );

        CreateProjection<Source, Dest>(); // 2

        this.Internal().ForAllMaps(static (_, _) => { });  // 3; don't need to do anything in the callback
    }
}
```

### Version: 12.0.1
Fails on Version 12.0.1
Works on Version 12.0.0

Also using EF7 but that really doesn't matter as the exception can be reproduced without it.

### Expected behavior
Does not throw an exception creating the map/configuration and can be successfully used. Works correctly in `12.0.0`

### Actual behavior
An Exception is thrown when constructing the mapper expression. It's impossible to use this profile to create a Mapper. The Exception occurs after the final invocation of the `ForAllMaps` method.

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=Incorrect number of arguments supplied for lambda invocation
>   Source=System.Linq.Expressions
>   StackTrace:
>    at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(MethodBase method, ExpressionType nodeKind, Int32 count, ParameterInfo[] pis)
>    at System.Linq.Expressions.Expression.Invoke(Expression expression, Expression arg0, Expression arg1, Expression arg2)
>    at System.Linq.Expressions.Expression.Invoke(Expression expression, IEnumerable\`1 arguments)
>    at AutoMapper.TypeMap.Invoke(Expression source, Expression destination)
>    at AutoMapper.Execution.ExpressionBuilder.MapExpression(IGlobalConfiguration configuration, ProfileMap profileMap, TypePair typePair, Expression source, MemberMap memberMap, Expression destination)
>    at AutoMapper.Execution.TypeMapPlanBuilder.MapMember(MemberMap memberMap, ParameterExpression resolvedValue, Expression destinationMemberValue)
>    at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(MemberMap memberMap, Expression destination, MemberInfo destinationMember)
>    at AutoMapper.Execution.TypeMapPlanBuilder.AddPropertyMaps(List`1 actions)
>    at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression createDestination)
>    at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
>    at AutoMapper.TypeMap.CreateMapperLambda(IGlobalConfiguration configuration)
>    at AutoMapper.TypeMap.Seal(IGlobalConfiguration configuration)
>    at AutoMapper.MapperConfiguration.<.ctor>g__Seal|20_0()
>    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
>    at Program.<Main>$(String[] args) in C:\Users\pinkfloyx33\source\repos\AutoMapperBug\AutoMapperBug\Program.cs:line 7

Note that the Exception is not thrown if you remove **any** of lines `1`, `2`, or `3` in the `ExampleProfile` above.

### Steps to reproduce

Create `MapperConfiguration` from attached profile (see above)

### More Details

We are using native Postgres enums in our project which is based on EFcore7. A native Postgres enum is not number-based and as such a _direct_ projection cannot be performed (based on the name/value) and will throw an error at runtime (from npgsql). To get around this you need to create a projection for the enum types and use `ConvertUsing` with (nested) ternary expressions to account for all cases. This has always worked properly for us. 

`ForAllMaps` - I realize this in the `Internal` namespace, so why do we use it? We have a common set of audit fields (create/modify date/user) across all of our Db and API models. Unfortunately:
- the names aren't exact matches to each other (even accounting for prefixes) thanks to different sets of company-wide conventions 
- the date fields are `DateTimeOffset` in the API model and `DateTime` at the db-level
  - Postgres doesn't support `DateTimeOffset` in the classic sense (ie. time+offset) and will normalize the offset _on read_ to the server's local time. `DateTime` is preferred and always tracks UTC
  - Additionally, the modified date is nullable which requires a cast in the mapping/projection expressions

Rather than specifying the two sets of member mappings/nullable casts for _every_ map, in _every_ profile, we have an extension method that calls `ForAllMaps`  which in turn checks the target/destination types for the audit-related interfaces and adds the 4 member maps as required. This has cleaned up our profiles a great deal and we'd prefer to keep it this way if possible. 

For the purposes of this report however, it is not necessary to perform any action within the callback. Calling the method is enough to trigger the exception. 

Removing any one line from the profile will prevent the exception--at the expense of an incorrect profile. Removing the `Value` property from the `Source`/`Dest` classes will also prevent the exception, though this is obviously _also_ incorrect.

**Comment by lbargaoanu** [comment]
Using `CreateMap` instead of `CreateProjection` for the enum seems to work.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by lbargaoanu** [comment]
The underlying bug here is that `ForAllMaps` overwrites the `Projection` flag on the map. So keeping your existing code would slowdown your startup. Unless you set the flag again in `ForAllMaps`. That applies for 12.0 too.

**Comment by pinkfloydx33** [comment]
I'm away from my desk until tomorrow but can try the MyGet build then. However I don't understand/am confused by your comments. **Must** I make a change or is the underlying issue corrected? Or do I need to set the flag myself?

A new extension method could work I guess for those cases, but then we'd have to consciously apply it. At least as-is we didn't even have to think about it (we map for other models that don't have such fields). I'm not saying it's the best way about things either and am happy to explore alternatives. 

I figured there's a bug here nonetheless hence the report. 

Also: I'm pretty sure I had _once_ tried using CreateMap for the enum instead of CreateProjection but that it then failed at projection time. It's been a long time though so I might be misremembering that. Happy to double check that as well. 

Thanks

**Comment by lbargaoanu** [comment]
The fix is in the MyGet build. I was just thinking about workarounds.
