### ISSUE TITLE
Issue when mapping to an existing read-only collection

### ISSUE THREAD

**Issue by DamienLaw** [AutoMapper/AutoMapper#4207]
### Problem statement

According to https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html#mapping-into-existing-collections

> When calling `Map` with an existing readonly collection, such as `IEnumerable<>`, <ins>the setter will be used to replace it</ins>.

but an exception is thrown instead.

### Source/destination types

```
public class Source
{
	public ICollection<string>? Names { get; set; }
}

public class Destination
{
	public ICollection<string>? Names { get; set; } // take note that this has a public setter
}
```

### Mapping configuration

```
var config = new MapperConfiguration(cfg => cfg.CreateMap<Source, Destination>());		
var mapper = config.CreateMapper();
```

### Expected behavior

The source collection property is mapped to the destination's collection property with the same items.

### Actual behavior

An exception was thrown:

```
Unhandled exception. AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Source -> Destination
Source -> Destination

Type Map configuration:
Source -> Destination
Source -> Destination

Destination Member:
Names

 ---> System.NotSupportedException: Collection is read-only.
   at System.SZArrayHelper.Clear[T]()
   at lambda_method1(Closure, Source, Destination, ResolutionContext)
   --- End of inner exception stack trace ---
   at lambda_method1(Closure, Source, Destination, ResolutionContext)
   at Program.Main()
Command terminated by signal 6
```

### Steps to reproduce

You can skip below and jump straight to the fiddler https://dotnetfiddle.net/CjUWa0
Click on the `Run` button and you'll get the exception.
```
var source = new Source
{
	Names = new [] {
		"John Smith",
		"Rebecca Olsen"
	}
};

var destination = new Destination
{
	Names = Array.Empty<string>() // existing read-only collection
};

// map from source into an existing destination
destination = mapper.Map(source, destination);
```

**Comment by lbargaoanu** [comment]
Then it goes on to say that `ICollection` is a writable collection. That's the expected behaviour and that'd what the docs say.

**Comment by DamienLaw** [comment]
So the writability of a collection is not only determined by its underlying implementation (concrete type such as `List<T>`, `T[]`, etc) but also by its interface as well - `IEnumerable<T>` is read-only, `ICollection<T>` and `IList<T>` are writables?

So in order for a collection to be writable, it has to have a writable design-time type (interface) as well as a writable underlying runtime type (implementation)?

**Comment by lbargaoanu** [comment]
Yes, because while some decisions are made at design-time, in the end the mapping has to work.
