### ISSUE TITLE
IncludeBase / AssertConfigurationIsValid fail in version 12.0.1

### ISSUE THREAD

**Issue by kakone** [AutoMapper/AutoMapper#4213]
With the new version 12.0.1, some mappings with IncludeBase fail. It worked well in version 12.0.0.
When configuration.AssertConfigurationIsValid(); is called, I get the message : `Unmapped properties: Date` although the date is well mapped.
You can reproduce the problem with this code : https://github.com/kakone/AutoMapperIncludeBase

### Mapping configuration

```csharp
cfg.CreateMap<Foo, FooDto>()
    .IncludeBase<FooBase, FooDtoBase>();

cfg.CreateMap<FooBase, FooDtoBase>()
    .IncludeBase<FooBaseBase, FooDtoBaseBase>();

cfg.CreateMap<FooBaseBase, FooDtoBaseBase>()
   .ForMember(d => d.Date, o => o.MapFrom(s => s.Today ? (DateTime?)DateTime.Today : null));
```

### Expected behavior

No exception when AssertConfigurationIsValid is called

### Actual behavior

AssertConfigurationIsValid fail with unmapped properties message

### Steps to reproduce

https://gist.github.com/kakone/ad2c0607f69b618d9527c92031cb9f57

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. Translate your code in the required format.

**Comment by kakone** [comment]
https://gist.github.com/kakone/ad2c0607f69b618d9527c92031cb9f57

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by kakone** [comment]
> Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

Tried and approved
