### ISSUE TITLE
ProjectTo doesn't work on FromSql

### ISSUE THREAD

**Issue by jxwaters** [AutoMapper/AutoMapper#4217]
When I call this method of mine 

```
    public async Task<List<TEntityDto>> ListFromSqlAsync(FormattableString sql, CancellationToken ct)
    {
        var res = await
            Repo.Context.Set<TEntity>().FromSql(sql)
                .IgnoreQueryFilters()
                .AsNoTracking()
                .ProjectTo<TEntityDto>(Mapper.ConfigurationProvider)
                .ToListAsync(ct);
        return res;
    }

```
Like this:

`await _queryService.ListFromSqlAsync( $"EXEC chronos.RecentStaffCompanies", cancellationToken);
`
I get 

FromSql' or 'SqlQuery' was called with non-composable SQL and with a query composing over it. Consider calling 'AsEnumerable' after the method to perform the composition on the client side.

If I comment out the ProjectTo and map in memory after ToList using Mapper.Map it works

The procedure returns the full object that is DbSet<TEntity>

I hate to have to read the full object to memory to return a subset of the fields. Any way to make this work (DB is SQL Server)

The sproc is

```
CREATE PROCEDURE chronos.RecentStaffCompanies
AS
	select *
	from chronos.Company c
	where c.CompanyTypeId in (0, 4) 
	and c.IsDeleted=0
	and exists(
		select * from chronos.staff s
		join chronos.office o on o.id = s.OfficeId
		where o.CompanyId = c.Id
		and s.IsDeleted=0
		and exists (
			select * from chronos.Journal j where j.StaffId = s.Id and j.IsDeleted = 0 and j.Date >= DATEADD( YEAR, -1, GETUTCDATE() )
		)
	)
	order by c.Name
GO

```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jxwaters** [comment]
https://stackoverflow.com/questions/75328073/is-there-a-way-to-use-automappers-projectto-with-entity-framework-cores-fromsq
