### ISSUE TITLE
How can we validate ReverseMaps now that GetAllTypeMaps is inaccessible (internal)?

### ISSUE THREAD

**Issue by sjd2021** [AutoMapper/AutoMapper#4224]
Below is a post on an old thread that had a workaround so that we could ensure we were validating reverse maps as well. This doesn't seem to apply anymore, but I'm not sure what the workaround is.

              Just a note for anybody who lands here in search for how to enable validation on reverse rules as I did - When creating reverse map, use `.ReverseMap().ValidateMemberList(MemberList.Destination)` or alternatively before asserting configuration, do something like this: `foreach (var map in mapCfg.GetAllTypeMaps().Where(m => m.ConfiguredMemberList == MemberList.None)) map.ConfiguredMemberList = MemberList.Destination;`

_Originally posted by @adamartin in https://github.com/AutoMapper/AutoMapper/issues/2327#issuecomment-462243473_

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
