### ISSUE TITLE
Documentation update for ReverseMap not being included in mapping validation

### ISSUE THREAD

**Issue by sjd2021** [AutoMapper/AutoMapper#4225]
The [documentation](https://github.com/AutoMapper/AutoMapper/blob/master/docs/Configuration-validation.md) makes no mention that ReverseMap is not automatically validated. Can this please be updated? I haven't worked anywhere yet that hasn't made use of ReverseMap, and no one knew that this was an issue until we recently ran into some issues that we thought were checked.

**Comment by lbargaoanu** [comment]
A PR is welcome.
