### ISSUE TITLE
Bad Projection/Expression produced with Enums and custom mapping extension 

### ISSUE THREAD

**Issue by pinkfloydx33** [AutoMapper/AutoMapper#4226]
AutoMapper creates an invalid/bad projection under some very specific circumstances:
- Mapping/Projecting an Enum using `ConvertUsing`
- Mapping the Enum property to an "external" value
  -  Static value, i.e. `SourceEnum.A`, or
  - A method call, i.e. `StaticClass.GetEnum()`
- Using an extension method to replace `MapFrom` with a generic constraint for an unrelated property

The invalid projection that is produced includes a reference to a closure variable from an intermediary `Select` created by AutoMapper. While I am using `ProjectTo`, this can be recreated with Linq2Objects. See below for more information.

### Source/destination types

```csharp
public interface IName {
    public string Name { get; }
}

public class Source  : IName {
    public int Id { get; set; }
    public string Name { get; set; }
    public SourceEnum Value { get; set; }
}

public class Dest {
    public int Id { get; set; }
    public string Name { get; set; }
    public DestEnum Value { get; set; }
}

public enum SourceEnum { A, B }
public enum DestEnum { A, B }
```

### Mapping configuration

```csharp
public class BrokenProfile : Profile {
    public BrokenProfile()  {
        CreateProjection<Source, Dest>() 
            .MyForName(s => s.Name) // 1a  See below
            .ForMember(s => s.Value, s => s.MapFrom(d => SourceEnum.B)); // 2 static-like value

        CreateProjection<SourceEnum, DestEnum>() // 3; Necessary for Postgres-style Enums which are not int-based
            .ConvertUsing(
                src => src == SourceEnum.A
                    ? DestEnum.A
                    : DestEnum.B
            );
    }
}

public static class Ext
{
   public static IProjectionExpression<TSource, TDestination> MyForName<TSource, TDestination>(
        this IProjectionExpression<TSource, TDestination> expr, Expression<Func<TDestination, string>> destinationMember) where TSource: IName {
        return expr.ForMember(destinationMember, s => s.MapFrom(d => d.Name));
    }
}
```

### Version: 
`12.0.0` but verified on `12.0.1` and `12.0.2-preview.0.2`

### Expected behavior

Expression is projected correctly

### Actual behavior

An invalid expression is produced with a reference to a closure variable from a previous projection (also created by AM). When using EF, the expression will fail to produce a valid SQL expression. When using Linq2Objects, attempting to execute the query throws an exception:

> System.InvalidOperationException: variable 'dtoSource' of type 'Source' referenced from scope '', but it is not defined

### Steps to reproduce

```csharp
IMapper badMapper = new Mapper(new MapperConfiguration(s => s.AddProfile<BrokenProfile>()));
var query = new List<Source>().AsQueryable();
var badResult = badMapper.ProjectTo<Dest>(query);
Console.WriteLine(badResult.Expression);
```

The output of the above is the following:
> System.Collections.Generic.List`1[Source].Select(dtoSource => new Object_-321105606___Value_Id() {Id = dtoSource.Id, __Value = B}).Select(dtoLet => new Dest() {Id = dtoLet.Id, Name = Convert(dtoSource, IName).Name, Value = IIF((Convert(dtoLet.__Value, Int32) == 0), A, B)})

Running this through ReadableExpression Visualizer you can see the problem more easily (note Name property in the second projection):

```csharp
EnumerableQuery<Source>.Select<Source, Object_-919630871___Value_Id>(
    // Quoted to induce a closure:
    (Source dtoSource) => new Object_-919630871___Value_Id
    {
        Id = dtoSource.Id,
        __Value = SourceEnum.B
    }).Select<Object_-919630871___Value_Id, Dest>(

    // Quoted to induce a closure:
    (Object_-919630871___Value_Id dtoLet) => new Dest
    {
        Id = dtoLet.Id,
        Name = ((IName)dtoSource).Name,   // <----------------- bad variable!
        Value = (((int)dtoLet.__Value) == 0) ? DestEnum.A : DestEnum.B
    })
```

Removing the call to the `MyForName` method and replacing it with a direct mapping produces the correct results:

```csharp
public class GoodProfile : Profile {
    public GoodProfile() {
        CreateProjection<Source, Dest>() 
            .ForMember(s => s.Name, s => s.MapFrom(d => d.Name)) // 1b
            .ForMember(s => s.Value, s => s.MapFrom(d => SourceEnum.B));

        CreateProjection<SourceEnum, DestEnum>()
            .ConvertUsing(
                src => src == SourceEnum.A
                    ? DestEnum.A
                    : DestEnum.B
            );
    }
}

IMapper goodMapper = new Mapper(new MapperConfiguration(s => s.AddProfile<GoodProfile>()));
var goodResult = goodMapper.ProjectTo<Dest>(query);
Console.WriteLine("GOOD:");
Console.WriteLine(goodResult.Expression);
```
With output:

> System.Collections.Generic.List`1[Source].Select(dtoSource => new Object_-967705056___Value_Id_Name() {Name = dtoSource.Name, Id = dtoSource.Id, __Value = B}).Select(dtoLet => new Dest() {Id = dtoLet.Id, Name = dtoLet.Name, Value = IIF((Convert(dtoLet.__Value, Int32) == 0), A, B)})

Or via expression visualizer:

```csharp
EnumerableQuery<Source>.Select<Source, Object_-1579328977___Value_Id_Name>(
    // Quoted to induce a closure:
    (Source dtoSource) => new Object_-1579328977___Value_Id_Name
    {
        Name = dtoSource.Name,
        Id = dtoSource.Id,
        __Value = SourceEnum.B
    }).Select<Object_-1579328977___Value_Id_Name, Dest>(

    // Quoted to induce a closure:
    (Object_-1579328977___Value_Id_Name dtoLet) => new Dest
    {
        Id = dtoLet.Id,
        Name = dtoLet.Name,  // <------- Correct!
        Value = (((int)dtoLet.__Value) == 0) ? DestEnum.A : DestEnum.B
    })
```

Similarly, mapping the `Value` property to a matching member does not produce the problem. However in our case this is part of a Projection with Entity Framework. The _real_ source type does not have a property of the Enum value;  `MapFrom` invokes a `static` method that EF translates into a database function call. 

We have a few helper extension methods for various interface types both for source/destination. They aren't always just a simple mapping (some casts and/or null coalescing). If we move the logic directly into the profile without the extension methods then everything is correct. While the code above uses `CreateProjection<>`, the same behavior is exhibited with `CreateMap<>` and extension methods for IMappingExpression instead.

**Comment by lbargaoanu** [comment]
Remove `MyForName` and make a gist as requested.

**Comment by lbargaoanu** [comment]
I'm guessing smth like `MapFrom(s=>DestEnum.B)` would work.

**Comment by lbargaoanu** [comment]
Ok, so ditching the extension method works. You have multiple workaround then.

**Comment by lbargaoanu** [comment]
The way to reuse configuration is with `Include` and mapping inheritance, not `MyForName`. Hopefully that works :)

**Comment by pinkfloydx33** [comment]
While `MapFrom(src => DestEnum.B)` does work, in our case the expression is actually `MapFrom(src => Some.DbFunction(src.Id))` where `Some.DbFunction` is a static method that EF translates into a corresponding database function. Mapping to a static value wouldn't solve things. It was the simplest reproduction I could provide.

The extension method in the repro is again just a minimal example. The work-around only works if dealing with interfaces that can be Included with inheritence mapping. If you notice, the destination type in the repro does not include an interface so there would be no type mapping to create to inherit from. We don't own all the types in question so we can't add it everywhere. Obviously the example repro is contrived, it's a minimal repro after all. The extension methods do more than a simple member map, such as ugly casting of `DateTime?` to `DateTimeOffset?`, or GetValueOrDefault on a `bool?`

It doesn't make sense that an extension method which performs the same exact mapping as the long-form/manually specified version would create an invalid expression tree. The extension method itself isn't even part of the tree so shouldn't really matter..it seems perhaps the the generic constraint is what breaks things, but that is just a guess.

And yes, you are correct I do have a work around. I can repeat (ugly) mapping/casting code rather than using a helper method. I'd have preferred not to, but I guess that's all we can do. Thanks anyways.
