### ISSUE TITLE
AssertConfigurationIsValid fails with error "Unmapped members were found", even though the member is declared as ignored

### ISSUE THREAD

**Issue by supertramp8** [AutoMapper/AutoMapper#4227]
### Source/destination types

```csharp
public class SourceModel
{
    public object Json { get; set; }
}

public class DestinationModel
{
    public string Json { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(c =>
{
    c.CreateMap<SourceModel, DestinationModel>(MemberList.Source)
        .ForMember(d => d.Json, y => y.Ignore());
});
```

### Expected behavior
AssertConfigurationIsValid() should pass

### Actual behavior

AssertConfigurationIsValid() fails with error:

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
================================
SourceModel -> DestinationModel (Source member list)
SourceModel -> DestinationModel (Source member list)

Unmapped properties:
Json

### Steps to reproduce

```csharp
using AutoMapper;

var config = new MapperConfiguration(c =>
{
    c.CreateMap<SourceModel, DestinationModel>(MemberList.Source)
        .ForMember(d => d.Json, y => y.Ignore());
});

config.AssertConfigurationIsValid();

var source = new SourceModel
{
    Json = new { Value = "Text" }
};

public class SourceModel
{
    public object Json { get; set; }
}

public class DestinationModel
{
    public string Json { get; set; }
}
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by supertramp8** [comment]
It is a behavior that has changed between versions 11.0.0 and 12.0.0, hence most likely a introduced bug.
