### ISSUE TITLE
Weird naming conventions behaviour

### ISSUE THREAD

**Issue by sj-lt** [AutoMapper/AutoMapper#4229]
Hello,

I found funny thing when using NamingConventions.
Checked in 12.0.1 but also previous versions.
So the setup to reproduce is 
```
class Program
    {
        public class Inner
        {
            public Guid? id { get; set; }  // this value is being mapped rather then inner_id
        }
        public class MappedFrom
        {
            public Guid? inner_id { get; set; }
            public Inner inner { get; set; }
        }
        public class MappedTo
        {
            public Guid? InnerId { get; set; }
        }
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.SourceMemberNamingConvention = LowerUnderscoreNamingConvention.Instance;
                cfg.DestinationMemberNamingConvention = PascalCaseNamingConvention.Instance;
                cfg.CreateMap<MappedFrom, MappedTo>();
            });
            var mapper = config.CreateMapper();
            var from = new MappedFrom { inner_id = Guid.NewGuid() };
            var to = mapper.Map<MappedTo>(from);
            Console.WriteLine($"id: {to.InnerId}");
        }
    }
```

Value that is assigned to InnerId is null.
As in comment value is coming from Inner.id.

And if we remove the convention naming and change all the naming to Pascal then we are receiving InnerId from InnerId field.
Hope it is clear enough.
Thanks in advance.

**Comment by lbargaoanu** [comment]
Obviously, just don't do that :)
But I see your point. On the other hand, this has been happening for a long time. So I'm not sure about changing it now.

**Comment by sj-lt** [comment]
Thanks for so fast response.
As for the answer it's a shame guess will need to go with some explicit MapFrom.
But of course would prefer to work same in every scenario :)
