### ISSUE TITLE
The EntityCollection has already been initialized in automapper since 2.2.0 version

### ISSUE THREAD

**Issue by v-glushkov** [AutoMapper/AutoMapper#425]
Hello!

Starting with 2.2.0 version of automapper I'm getting "The EntityCollection has already been initialized" exception while trying to map from data model into an EntityObject from edmx model (generated by EF DB first method) containing EntityCollection field with "((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection" method in setter.

I tried filling the EntityCollection property using add() method and .AfterMap in Map configuration. It works ok in such way, except for it creates a problem with relationships recursion.

I tried looking for the commit which have broken this stuff and found it: https://github.com/AutoMapper/AutoMapper/commit/6c38546861288d28add8d2073b91a68ce5dc5ff9

So it turned out that changing

```
object destinationValue = propertyMap.GetDestinationValue (mappedObject);
```

to

```
object destinationValue = null;

 if (propertyMap.UseDestinationValue)
 {
 destinationValue = propertyMap.GetDestinationValue(mappedObject);
 }
```

fixed 2.2.0, 2.2.1, 3.0.. This "fix" was working untill this commit: https://github.com/AutoMapper/AutoMapper/commit/1b3a1c5773457ee903e15d318a56b10812414604

In the same way as before I tried reverting these changes in the last commit to get a working 3.1 version, but I'm still getting the mentioned exception. Since we need to maintain our project in future stucking with 3.0 is a bad idea, so I'm looking for some solution.

Thx.

**Comment by aquabib** [comment]
Hi, I'm using version 4.1.1 but still have this issue when mapping to an EntityCollection in EF. I tried using UseDestinationValue but it doesn't solve the issue. Has this bug re-occured?
Thanks
