### ISSUE TITLE
ProjectTo does not reflect Include Filters

### ISSUE THREAD

**Issue by vocko** [AutoMapper/AutoMapper#4260]
### Source/destination types

(truncated to the involved properties)

```csharp
public class Conversation
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    public virtual ICollection<Comment> Comments { get; set; }
}

public class Comment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    [Required]
    public string Comment { get; set; }

    [Required]
    public Guid ConversationId { get; set; }

    public virtual ICollection<User> PermittedUsers { get; set; }
}

public class User
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }
    
    public string Name { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<Comment, CommentDto>()
    .ForMember(c => c.ConversationId, opts => opts.MapFrom(c => c.Conversation.Id));

CreateMap<Conversation, ConversationDto>();
```

### Version: x.y.z
Automapper 12.0.1
Automapper.Collection 9.0.0
AutoMapper.Collection.EntityFramework 9.0.0
Automapper.Extensions.Microsoft.DependencyInjection 12.0.0
Microsoft.EntityFrameworkCore 7.0.4

### Expected behavior

The resulting destination dto should be the same for the same query regardless whether `_mapper.Map<DestinationDto>` or `ProjectTo<DestinationDto>` will be used.

### Actual behavior

I'm getting different results for the same query for each of the methods above.

### Steps to reproduce

I'm trying to get a comments in a conversation that are visible to a particular user. Each conversation has comments and each comment has a table of users who can see the comment.

When I perform the EF Core query, the comments are filtered as expected, however, if I use pro `ProjectTo` mapping, the filter in the include clause seems to be ignored and all comments are returned instead.

If I get the data using pure query and then use the mapper to map the result set, the results are correct.

I have truncated the objects and the query as my case is obviously much more sophisticated, but I have also tried to comment out all the other includes and was still getting the same result. There 

```csharp
var userId = "calling user id";
var conversationId = "requested conversation id";

var query = _dbContext.Conversations
                       .AsNoTracking()           
                       .Include(c => c.Comments.Where(c => c.PermittedUsers.Any(pu => pu.Id == userId)))
                           .ThenInclude(c => c.PermittedUsers)
                       .Where(c => c.Id == conversationId);
// This works correctly
var dbConversation = await query.SingleOrDefaultAsync();
var conversationDto = _mapper.Map<ConversationDto>(dbConversation);

// This does not
var dbConversationProjected = await query
    .ProjectTo<ConversationDto>(_mapper.ConfigurationProvider)
    .SingleOrDefaultAsync();

```

I have noticed that there was a similar issue before which has been closed with no feedback: https://github.com/AutoMapper/AutoMapper/issues/3743

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
