### ISSUE TITLE
ReverseMap validation doesn't work since 12.0.0

### ISSUE THREAD

**Issue by killergege** [AutoMapper/AutoMapper#4291]
We used to use `CreateMap<>(MemberList.Destination).ReverseMap().ValidateMemberList(MemberList.Destination));` to make sure that the objects are identical.
This technique was working in 11.0.1 (and it is mentioned several times here and on SO), but it stopped working in 12.0.0. The Reverse validation doesn't seem to occur.

### Source/destination types

```csharp
    public class Source
    {
        public int SomeValue  { get; set; }
        public int SomeValue2 { get; set; }
    }

    public class Destination
    {
        public int SomeValue  { get; set; }
    }
```

### Mapping configuration

```csharp
        var configuration = new MapperConfiguration(cfg =>
                                    cfg.CreateMap<Source, Destination>(MemberList.Destination)
                                       .ReverseMap()
                                       .ValidateMemberList(MemberList.Destination));
        configuration.AssertConfigurationIsValid();
```

### Expected behavior

AssertConfigurationIsValid() should throw, as `SomeValue2` is missing from the reverse mapping `<Destination, Source>` and we ask to validate the destination.
And it throws in 11.0.1

### Actual behavior

AssertConfigurationIsValid() doesn't throw.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by killergege** [comment]
Ok, I found the issue...
Although, I'm not comfortable with the fix I have. All the tests pass (and also mine with the example above).
But I cannot find how the issue has been introduced between v11 & v12, and why the code has been written that way.
As the tests continue to pass, it should be ok, but I'll let you be the judge of that.

The issue is there :
```
public MemberList ConfiguredMemberList
    {
        get => (_details?.ConfiguredMemberList).GetValueOrDefault();
        set
        {
            if (value == default)
            {
                return;
            }
            Details.ConfiguredMemberList = value;
        }
    }
```
If the value is the default, it is ignored.
But `Destination` is the default, and the ReverseMap initializes the field with `None`. 
So the value is not changed when running the `TypeMapActions`
A basic fix would be to remove the
```
            if (value == default)
            {
                return;
            }
```
But I guess this is there for a reason, and it was there for v11.
