### ISSUE TITLE
AssertConfigurationIsValid() throws an exception on correct map with .ConstructUsing()

### ISSUE THREAD

**Issue by modemaizer** [AutoMapper/AutoMapper#4294]
### Source/destination types

```csharp
    public class ItemRequestModel
    {
        public string Id { get; set; }

        public string Action { get; set; }

        public PlaceRequestModel Place { get; set; }
    }
    
    public class PlaceRequestModel
    {
        public List<AddressRequestModel> Addresses { get; set; }
    }
    
    public class Item
    {
        public Item(string id, string action, List<ItemAddress> addresses)
        {
            Id = id;
            Action = action;
            Addresses = addresses;
        }

        public string Id { get; }

        public string Action { get; }

        public List<ItemAddress> Addresses { get; }
    }
```

### Mapping configuration

```csharp
CreateMap<ItemRequestModel, Item>().ConstructUsing((src, context) =>
                new Item(
                    src.Id,
                    src.Action,
                    context.Mapper.Map<List<ItemAddress>>(src.Place.Addresses)));
```

### Expected behavior

AssertConfigurationIsValid() runs without exceptions.

### Actual behavior

AssertConfigurationIsValid() throws following:
Message: 
    AutoMapper.AutoMapperConfigurationException : 
    Unmapped members were found. Review the types and members below.
    Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
    For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
    =====================================================================================================================
    ItemRequestModel -> Item (Destination member list)
        
    Unmapped properties:
    Addresses

### Steps to reproduce

Just call 
```csharp
_config.AssertConfigurationIsValid();
```
in unit test.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
