### ISSUE TITLE
MemberList.Source and .ForMember()

### ISSUE THREAD

**Issue by juliancarrivick** [AutoMapper/AutoMapper#4303]
### Source/destination types

```csharp
class Source
{
    public required string A { get; set; }

    public required string B { get; set; }
}

class Dest
{
    public required string A { get; set; }

    public required Inner Inner { get; set; }
}

class Inner
{
    public required string B { get; set; }
}
```

### Mapping configuration

```csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Dest>(MemberList.Source)
        .ForMember(dst => dst.Inner, opt => opt.MapFrom(src => src));
    cfg.CreateMap<Source, Inner>(MemberList.None);
});
```

### Expected behavior

I expect `configuration.AssertConfigurationIsValid();` to not throw as all members of `Source` are correctly mapped to the destination. e.g. 

``` csharp
var d = mapper.Map<Dest>(new Source
{
    A = "a",
    B = "b",
});
Console.WriteLine($"A={d.A};B={d.Inner.B}");
``` 

Outputs `A=a;B=b` as expected.

### Actual behavior

`configuration.AssertConfigurationIsValid();` throws with:

```
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
===============
Source -> Dest (Source member list)
Source -> Dest (Source member list)

Unmapped properties:
B
```

### Steps to reproduce

```csharp
configuration.AssertConfigurationIsValid();
```

### Other

I found #3000 which seems to be related (except for using `.ForPath()` instead), and the comments plus associated PR #3001 leads me to believe what I'm doing should work.

**Comment by lbargaoanu** [comment]
#3000 just says that `.ForPath(dst => dst.Inner.B, opt => opt.MapFrom(src => src.B));` should work and it does. Your case is different. `B` is mapped in the inner map, not in the main one, so validation complains. That seems fair.

**Comment by juliancarrivick** [comment]
Alright then, so have I misunderstood what `AssertConfigurationIsValid()` is for then? In #3000 @jbogard says that:

> Configuration validation is NOT about "will this mapping work at runtime". Configuration validation is about "I've now introduce a library that may introduce a bunch of magic, let me make sure the magic is doing what I want."

In this case I have specified `MemberList.Source` which my understanding is to verify that all source members get mapped to _somewhere_, which is what the documentation specifies (`Member list to check for configuration validation`). In my case here, it is saying the source property `B` is not mapped, when in reality it is.

I guess what has confused me is that the reverse configuration is asserted/validated correctly (maybe should have named Source->DTO and Dest->Entity to reduce confusion in this opposite direction). i.e.

``` csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Dest, Source>(MemberList.Destination)
        .IncludeMembers(e => e.Inner);
    cfg.CreateMap<Inner, Source>(MemberList.None);
});
configuration.AssertConfigurationIsValid(); // This doesn't throw
```

**Comment by lbargaoanu** [comment]
You're dancing around the issue :) You're welcome to look deeper into it and try to come up with a proposal. Worst case scenario, you'll see the point I'm trying to make.
