### ISSUE TITLE
"Index was outside the bounds of the array." Error

### ISSUE THREAD

**Issue by mertmtn** [AutoMapper/AutoMapper#4306]
.NET Framework 4.7.2 project, while mapping from source to destination gives
"Index was outside the bounds of the array." but occurs rarely.

Related stachoverflow question: https://stackoverflow.com/questions/76514918/automapper-gives-index-was-outside-the-bounds-of-the-array-error 

### Source/destination types

```
PoliceYenilemeRepository pyrep = new PoliceYenilemeRepository();
PoliceYenileme oldModel = pyrep.GetById(py.Id);
PoliceYenilemeIslemLog model = new PoliceYenilemeIslemLog();
```

### Mapping configuration

```
Mapper.Initialize(x => x.CreateMap<PoliceYenileme, PoliceYenilemeIslemLog>());
model = Mapper.Map<PoliceYenilemeIslemLog>(oldModel);
```

### Expected behavior

Expected result: Should not give any error.

### Actual behavior
Given stack trace

```
at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.Clear()
   at AutoMapper.Mappers.MapperRegistry.Reset()
   at AutoMapper.Mapper.Reset()
   at AutoMapper.Mapper.Initialize(Action`1 action)
   at Hms.Business.Yenileme.BussPoliceYenileme.InsertPoliceYenilemeIslemLogBilgi(PoliceYenileme py) in C:\Azure\HealthManagementSystem\HMS.Business\Yenileme\BussPoliceYenileme.cs:line 2088 
```

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/v7.0.0/Getting-started.html#where-do-i-configure-automapper

**Comment by mertmtn** [comment]
@lbargaoanu thanks for your document but i used below code as you can see on Mapping configuration part but given this error. 
Could you please give detail explanation about your answer?

Mapper.Initialize(cfg => cfg.CreateMap<Order, OrderDto>());
OrderDto dto = mapper.Map<OrderDto>(order);

**Comment by mertmtn** [comment]
I also applied below method. I can not be sure that it is a solution.

![image](https://github.com/AutoMapper/AutoMapper/assets/37337606/53879a8e-7cb7-4284-917b-cdd3a036dc1d)
