### ISSUE TITLE
Potential breaking change in MyGet version with added support for null reference types

### ISSUE THREAD

**Issue by killergege** [AutoMapper/AutoMapper#4310]
MyGet v12.0.2-preview.0.4

Be careful that [this change](https://github.com/AutoMapper/AutoMapper/pull/4202/files#diff-78c7b2d0b1cb8cb4a749f96ad4dfe22974ce035670784500115a9954d9bd18d1) will be a breaking change for projects that enforce proper handling of null types :
`TDestination? Map<TDestination>(object? source);`

Because even if we provide not null objects as input parameters, the compiler now thinks that the output can be null.

Could you consider adding the attribute `NotNullIfNotNullAttribute` ?

**Comment by lbargaoanu** [comment]
This has been discused before.
