### ISSUE TITLE
Mapping broke when upgrading from 12.0.0 to 12.0.1

### ISSUE THREAD

**Issue by ahmednfwela** [AutoMapper/AutoMapper#4316]
### Mapping configuration

```csharp
//Mappings for properties A,B,C, ...
CreateMap<ProjectBase, SimpleProjectInfoVMBase>();
//Mappings for some extra properties (E,F,G) + the base (A,B,C,...)
CreateMap<ProjectBase, SimpleProjectInfoWithCommsVMBase>()
    .IncludeBase<ProjectBase, SimpleProjectInfoVMBase>();
//Mappings for some extra properties (X,Y,Z) + the base (A,B,C,...) + (E,F,G)
CreateMap<ProjectBase, SimpleProjectInfoWithCommsVM<ObjectId>>()
    //.IncludeBase<ProjectBase, SimpleProjectInfoVMBase>()
    .IncludeBase<ProjectBase, SimpleProjectInfoWithCommsVMBase>();
```

### Expected behavior

Version 12.0.0 used to work without the commented line
```csharp
//.IncludeBase<ProjectBase, SimpleProjectInfoVMBase>()
```

### Actual behavior

Version 12.0.1 fails to validate (when calling `AssertConfigurationIsValid`) without the commented line
saying it can't find mappings for the base class for properties A,B,C, ...

---
Looking at the changes introduced in 12.0.1, I think this bug might be because of https://github.com/AutoMapper/AutoMapper/pull/4097 , but I have no idea why

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
