### ISSUE TITLE
Upgrade to 12.0.1

### ISSUE THREAD

**Issue by werebear73** [AutoMapper/AutoMapper#4318]
I have been using Automapper for awhile and enjoy.

I keep getting this strange issue when trying to upgrade to 12.0.1.  I tried to upgrade on .net 6 and got the same error.  Upgrade the application to 7.0 (it is small) to see if that resolved the issue but it didn't.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1100	Unable to resolve 'AutoMapper (>= 12.0.1)' for 'net7.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org, skyetel/Skyetel.DataStructures.Trie.	Skyetel.SH.Vendors.RateCache.Application	C:\Users\User\source\repos\xxx.xxx.xxx.xxx\src\Core\xxx.xxx.xxx.xxx.Application\xxx.xxx.xxx.xxx.Application.csproj	1

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
