### ISSUE TITLE
I am getting 'Could not load type 'AutoMapper.Configuration.MappingExpressionBase' 

### ISSUE THREAD

**Issue by archanaj39** [AutoMapper/AutoMapper#4319]
Hello Team, I have updated version to 12 and now I am getting error like : 'Could not load type 'AutoMapper.Configuration.MappingExpressionBase' from assembly 'AutoMapper 
![image](https://github.com/AutoMapper/AutoMapper/assets/48048329/c3572451-1d1b-4521-a5b9-8811f5edfc6d)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
