### ISSUE TITLE
Confusing behaviour when mapping to an existing instance

### ISSUE THREAD

**Issue by tscheler** [AutoMapper/AutoMapper#4342]
Version: 12.0.1 (and below)

### Expected behavior

I would expect, that the `Map` method, that takes an existing destination, will always return the very same destination.

### Actual behavior

When using an empty mapping configuration, the `Map` method creates a new instance and returns it.
It does not touch the given destination instance.

However, with the following config everything works: 
```csharp
MapperConfiguration config = new MapperConfiguration(o => { o.CreateMap<Poco, Poco>(); });
```
For me this behaviour is unexpected and the error was hard to debug.

### Steps to reproduce
```csharp
public class UnitTest1
{
    [Fact]
    public void Test()
    {
        MapperConfiguration config = new MapperConfiguration(o => { });
        var mapper = new Mapper(config);
        
        var e1 = new Poco() { FirstName = "Tom" };
        var e2 = new Poco() { FirstName = "Frank" };

        var e3 = mapper.Map(e1, e2);

        e3.FirstName.Should().Be(e1.FirstName); // OK
        e3.Should().BeSameAs(e2); // FAIL
        e2.FirstName.Should().Be(e1.FirstName); // FAIL
    }

    class Poco
    {
        public string? FirstName { get; set; }
    }
}
```

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).

**Comment by Dev-Craftsman** [comment]
Thank you for your quick response. 👍
In my opinion the comment on the IMapperBase-Map-Method is misleading.
See Picture attached, please.
Maybe it should be updated.

![RW2j9guJEp](https://github.com/AutoMapper/AutoMapper/assets/63975372/01667d67-8d83-41a0-8d07-7463c3396df0)

**Comment by lbargaoanu** [comment]
I don't know :) Is _really_ this corner case worth the extra line(s)? I'm thinking it would just add complexity for the casual reader. But you're welcome to give it a shot.

**Comment by tscheler** [comment]
I think the method should throw an error instead of ignoring the destination object.
The whole point of the method is updating the destination and *not* creating a new instance.
Isn't it?
