### ISSUE TITLE
Record mapping broken

### ISSUE THREAD

**Issue by spaasis** [AutoMapper/AutoMapper#4344]
Since #4098 is closed an cannot be commented, just letting you know that it's still broken in 12.0.1.

In some cases with Records AutoMapper generates expressions such as:
```
...
.OrderBy(a => new AccessRequestOutput{ }
    .Sent)
```

Which of course fails since the creation block of the `AccessRequestOutput` is empty.

The linked item has more details.

Hoping to see this fixed soon, since we've already had to migrate a lot of records to classes just to work around this broken behavior.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
