### ISSUE TITLE
Result is not null when mapping null source object to an existing not null destination object

### ISSUE THREAD

**Issue by koljada** [AutoMapper/AutoMapper#4355]
### Source/destination types

```csharp
record Entity(int Id);//source
record Dto(int Id);//destination
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg => cfg.CreateMap<Entity, Dto>());
IMapper mapper = config.CreateMapper();
```

### Expected behavior (match behavior in previous version)

Result is `null` when mapping `null` source object to an existing not `null` destination object.
`mappedDto` should be `null` in my example.

### Actual behavior

Result is not `null` when mapping `null` source object to an existing not `null` destination object.
`mappedDto` is not `null` in my example.

### Steps to reproduce

```csharp
Dto dto = new(1);
Entity entity = null;
Dto mappedDto = mapper.Map(entity, dto);//is null in 11.0.1 but is not null in 12.0.1
```

Is it a bug or not documented breaking change? I was trying to update to net 8 and as part of that also update `AutoMapper` from 11 to 12. I could not find any related breaking changes in docs so decided to raise this issue.

**Comment by lbargaoanu** [comment]
This has been discussed before. `Map` is supposed to return the destination object and it does that whenever possible.

**Comment by koljada** [comment]
Ok, that makes sense. But shouldn't it be mentioned in docs? It's a breaking change which caused bugs for my app.

**Comment by lbargaoanu** [comment]
I'd rather not spend my time documenting every little change, but a PR is welcome.
