### ISSUE TITLE
Validation fails when using flatenning with MemberList.Source

### ISSUE THREAD

**Issue by Ivan2016** [AutoMapper/AutoMapper#4358]
Example below fails AutoMapper validation but it shouldn't.
The exception is thrown when custom function is used for mapping. If you remove the call to ToString(CultureInfo.InvariantCulture) - validation succeeds.

### Source/destination types

```csharp
public sealed class Source
{
    public string Title { get; set; }
    public Nested Nested { get; set; }
}
public sealed class Nested
{
    public long TestLong { get; set; }
    public string TestString { get; set; }
}

public sealed class Destination
{
    public string Title { get; set; }
    public string TestLongString { get; set; }
    public string TestString { get; set; }
}
```

### Mapping configuration

```csharp
            CreateMap<Nested, Destination>(MemberList.Source)
                .ForMember(d => d.TestLongString, o => o.MapFrom(s => s.TestLong.ToString(CultureInfo.InvariantCulture)))
                .ForMember(d => d.TestString, o => o.MapFrom(s => s.TestString));

            CreateMap<Source, Destination>()
                .IncludeMembers(s => s.Nested)
                .ForMember(d => d.Title, o => o.MapFrom(s => s.Title));
```

### Expected behavior

No exception is thrown because all Nested properties are mapped.

### Actual behavior

Unhandled exception. AutoMapper.AutoMapperConfigurationException:
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
====================================================
Nested -> Destination (Source member list)
AutoMapperTest.Nested -> AutoMapperTest.Destination (Source member list)

Unmapped properties:
TestLong

### Steps to reproduce

```csharp
var configuration = new MapperConfiguration(cfg =>
{
    cfg.AddMaps(typeof(Source));
});

configuration.AssertConfigurationIsValid();
```

**Comment by ahmednfwela** [comment]
I am facing this as well, this beats the purpose of using `IncludeMembers`, since now we have to duplicate EVERY mapping

**Comment by lbargaoanu** [comment]
Thats's certainly wrong. I suggest asking a question on SO.
