### ISSUE TITLE
MapperAction with DI and without using DI extension 

### ISSUE THREAD

**Issue by nmase88** [AutoMapper/AutoMapper#4360]
The current documentation [here  ](https://docs.automapper.org/en/v12.0.1/Before-and-after-map-actions.html) says to use the below for DI which is part of the extension AutoMapper.Extensions.Microsoft.DependencyInjection:

```services.AddAutoMapper(typeof(Startup).Assembly)```

However, that extension states it is now deprecated and is now folded into AutoMapper but there doesn't appear to be any way to use DI in this instance without services.AddAutoMapper. Every attempt I have made to do this results in the usual 'unable to find parameterless constructor' error. 

Please could you advice? Is there something I am missing? If the extension is now deprecated why is it still being referenced as the correct approach in the documentation.

**Comment by lbargaoanu** [comment]
The DI package is deprecated in AM 13.

**Comment by nmase88** [comment]
I'm sorry but that doesn't really answer my question.

Are you saying dependency injection is no longer possible in auto mapper? Do you plan on updating the documentation to reflect this?
