### ISSUE TITLE
Wrong maps being picked up

### ISSUE THREAD

**Issue by pdurchev** [AutoMapper/AutoMapper#4365]
Hello,

For an unknown reason our projects are picking the wrong maps. I wasn't able to reproduce the issue in a test project but here is simple example of the situation: 

### Source/destination types

```csharp
public interface IVehicle
{
    string Registration { get; set; }
    string OwnerName { get; set; }
}

public interface ICar : IVehicle
{
    decimal Weight { get; set; }
    string Make { get; }
    string Model { get; set; }
}

public class VehicleDto : IVehicle
{
    public string Registration { get; set; }
    public string OwnerName { get; set; }
}

public class FordCar : VehicleDto, ICar
{
    public decimal Weight { get; set; }
    public string Make => "Ford";
    public string Model { get; set; }
}

public class FordVm : ICar
{
    public string Registration { get; set; }
    public string OwnerName { get; set; }
    public decimal Weight { get; set; }
    public string Make => "Ford";
    public string Model { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<IVehicle, FordVm>();
CreateMap<ICar, FordVm>();
```

### Expected behavior

All properties to be mapped because auto mapper will pick the <ICar, FordVm> map.

### Actual behavior

Auto mapper picks the <IVehicle, FordVm> map and only Registration and OwnerName fields are mapped.

### Steps to reproduce

```csharp
ICar ford = new FordCar
{
    Registration = "ABC123",
    OwnerName = "John Doe",
    Model = "Focus",
    Weight = 1200
};

var fordVm = new FordVm();

_mapper.Map(ford, fordVm);
```

I was able to fix that issue in a very simple way by just ordering the interfaces in ```csharp GetTypeInheritance(List<Type> types, Type type)```:
```csharp

private class TypeInheritanceComparer : IComparer<Type>
{
    public int Compare(Type x, Type y)
    {
        if (x == y)
        {
            return 0;
        }
        if (x.IsAssignableFrom(y))
        {
            return 1;
        }
        else if (y.IsAssignableFrom(x))
        {
            return -1;
        }
        return 0;
    }
}
...

static void GetTypeInheritance(List<Type> types, Type type)
{
    var interfaces = type.GetInterfaces()
        .OrderBy(x => x, new TypeInheritanceComparer()).ToArray();            

    var lastIndex = interfaces.Length - 1;
    types.Add(type);
    Type baseType = type;
    ...
}
```

After this change all AutoMapper unit tests passed and our main solution was fixed. I'm still not sure what is different in our main project to cause the different order of .GetInterfaces() but I think the proposed solution cannot harm in any way and is extra insurance in case something is changed in future .net versions.

Thanks,
Pavel

**Comment by jbogard** [comment]
Oooof. I think in general the design shouldn't be affected by the order of `GetInterfaces` here. That seems flaky.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
