### ISSUE TITLE
About NetFramework 4.8 support

### ISSUE THREAD

**Issue by koyuyesil** [AutoMapper/AutoMapper#4376]
I initiated a .NET 8 project, and halfway through, I realized that AutoMapper is not supported. Is there a solution? What are the targeted versions, .NET 4 and .NET 5, 6, 7, 8? Will it target .NET Standard, or are there dependencies? I tried to compile it only for 4.8, but couldn't succeed.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by jbogard** [comment]
AutoMapper absolutely supports .NET 8, FYI.

**Comment by koyuyesil** [comment]
My mistake, I had requested version 4.8, but I discovered that it is supported in the previous version.
