### ISSUE TITLE
ProjectTo Throws Exception with ComplexProperties

### ISSUE THREAD

**Issue by rgordey** [AutoMapper/AutoMapper#4377]
Owned Property works but Complex Property throws with ProjectTo.

Error message System.InvalidOperationException: 'Comparing complex types to null is not supported.'

_mapper.Map works in both cases.

[My Demo](https://github.com/rgordey/AutoMapperDemo) demonstrating this issue.

AutoMapper 12.0.2-preview.0.4
Ef Core 8.0.1

**Comment by lbargaoanu** [comment]
You can remove that null check with `AllowNull`.

**Comment by rgordey** [comment]
@lbargaoanu I added AllowNull but still the same error.

**Comment by lbargaoanu** [comment]
`DoNotAllowNull`?

**Comment by rgordey** [comment]
@lbargaoanu  DoNotAllowNull doesn't throw. I'll test further.
