### ISSUE TITLE
ReadTheDocs builds failing

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#4379]
We need to upgrade to V2:

https://blog.readthedocs.com/migrate-configuration-v2/

I'm working on this in a branch, but this is to track the work.

**Comment by lbargaoanu** [comment]
Fixed?

**Comment by jbogard** [comment]
Well I fixed it but unfortunately the docs are tied to tags, so v13.0.0 will forever be broken. Whoops.
