### ISSUE TITLE
No AutoMapper support for .NET 8?

### ISSUE THREAD

**Issue by Kolbein** [AutoMapper/AutoMapper#4391]
Hi,

After having upgraded my .NET project from .NET 6 to .NET 8, I can't install the latest version of AutoMapper 13.0.1.
It seems that .netstandard 2.1 was removed in this version and now only supports .NET 6.

### Steps to reproduce

Use .NET 8 and try to install AutoMapper 13.0.1

**Comment by jbogard** [comment]
Yeah this is something on your side, .NET 6 is forward compatible to .NET 8. I installed on a fresh project just fine. Maybe you're running into the deprecated package of the `AutoMapper.Extensions.Microsoft.DependencyInjection` package? You'll need to remove that before upgrading.
