### ISSUE TITLE
Projecting a single entity | How to use `ProjectTo` with `GroupBy` | Producing `Expression<Func<TSource, TDestination>>`

### ISSUE THREAD

**Issue by FelixZY** [AutoMapper/AutoMapper#4398]
This is a theoretical scenario based on an actual use case which I am not able to share.

Consider a scenario where I have the following data classes (in reality they each contain far more data but let's keep it simple):

```csharp
public class Employment {
  public required Person Person { get; set; }
  public required Company Company { get; set; }
  public required string Title { get; set; }
}

public class Person {
  public required List<Employment> Jobs { get; set; }
}

public class Company {
  public required List<Employment> Employees { get; set; }
}
```

Now, in my repository I want to expose a method like this:

```csharp
public IQueryable<IGrouping<string, Person>> GetPersonsByTitle();
```

However, there does not seem to be an easy way to do this:

*Fails to translate into SQL:*

```csharp
dbContext.Employments.GroupBy(
  it => it.Title,
  it => mapper.Map<Person>(it)
);
```

*Title is not available in GroupBy:*

```csharp
dbContext.Employments
  .ProjectTo<Person>(mapper.ConfigurationProvider)
  .GroupBy(
    it => it.Title
  );
```

*Wrong return type - probably does not even work (not tested)?*

```csharp
dbContext.Employments
  .GroupBy(
    it => it.Title
  )
  .ProjectTo<Person>(mapper.ConfigurationProvider)
```

---

What I *have* been able to do, based on reading the source code for `ProjectTo`, is the following. However, it's not very pretty.

```csharp
dbContext.Employments.GroupBy(
    it => it.Title,
    (Expression<Func<Employment, Person>>)
        mapper
            .ConfigurationProvider.Internal()
            .ProjectionBuilder.GetProjection(
                typeof(Employment),
                typeof(Person),
                null,
                []
            )
            .Projection
);
```

Have I missed something or could this be exposed in a more flattering form, e.g.

```csharp
dbContext.Employments.GroupBy(
    it => it.Title,
    mapper.Projection<Employment, Person>()
);
```

where the return type of `Projection` would be `Expression<Func<TSource, TDestination>>`?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
