### ISSUE TITLE
Unable to map between a list and an model that derives from the list

### ISSUE THREAD

**Issue by TrueMoniker** [AutoMapper/AutoMapper#4400]
When I map an object that derives from a list, I receive an error 'Incorrect number of arguments supplied for call to method System.String get_Item(Int32)'.
However, if I use the fix from #3597, the mapper will run but the result is empty.

### Source/destination types

```csharp
public class ListExtension : List<string>
  {
  }
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<ListExtension, List<string>>()
        .ForMember("Item", op => op.Ignore());
    cfg.CreateMap<List<string>, ListExtension>()
        .ForMember("Item", op => op.Ignore());
});

IMapper mapper = config.CreateMapper();
```

### Expected behavior
The list maps into the 'ListExtension', which derives from the same type as the list. In the reproduction example, I would expect the test to pass.

### Actual behavior
When I map the list, I receive an error 'Incorrect number of arguments supplied for call to method System.String get_Item(Int32)'.

However, I use the fix from #3597, the mapper will run but the result is empty. In the reproduction example, the test does not pass.

### Steps to reproduce

```csharp
[Fact]
public void Issue1()
{
    var config = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<ListExtension, List<string>>()
            .ForMember("Item", op => op.Ignore());
        cfg.CreateMap<List<string>, ListExtension>()
            .ForMember("Item", op => op.Ignore());
    });

    IMapper mapper = config.CreateMapper();

    List<string> myList = new List<string> { "0", "1", "2" };

    var afterMap = mapper.Map<ListExtension>(myList);
    Assert.Equal(myList.Count, afterMap.Count);
}
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
