### ISSUE TITLE
Version 13 Upgrade Compiler Error

### ISSUE THREAD

**Issue by JoeYong** [AutoMapper/AutoMapper#4401]
// Mapper.Initialize 
services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

### Expected behavior
No error from upgrading

### Actual behavior
Compiler Error.

I upgraded from AutoMapper 12 to 13.0.1 and received this strange error in Startup - 
The call is ambiguous between the following methods or properties: 
'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapper(Microsoft.Extensions.DependencyInjection.IServiceCollection, params System.Reflection.Assembly[])' and 
'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapper(Microsoft.Extensions.DependencyInjection.IServiceCollection, params System.Reflection.Assembly[])'

I have already uninstalled AutoMapper.Extensions.Microsoft.DependencyInjection package.

I read the upgrade documentation and I saw nothing different. Is there something that I missed as I am using the Core 3 style of services instead of Core 6 builder.services ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
