### ISSUE TITLE
Sealed Mapper class in 13.x

### ISSUE THREAD

**Issue by YandyZaldivar** [AutoMapper/AutoMapper#4404]
Consider the following reproducible xunit test case:
https://gist.github.com/YandyZaldivar/ed5f4b2b03aed60c863a0326dc8fc3c1

This works fine with Automapper 12.0.1 but fails with Automapper 13.0.1.

Most likely Automapper 13.0.1 is introducing a breaking change by making the `Mapper` class `sealed`:
`public sealed class Mapper : IMapper, IMapperBase, IInternalRuntimeMapper, IRuntimeMapper`

I already read https://www.jimmybogard.com/automapper-13-0-released/ and https://docs.automapper.org/en/stable/13.0-Upgrade-Guide.html.

What do you suggest for many broken tests?

**Comment by lbargaoanu** [comment]
You should not mock `Mapper`, you should use the real thing.
