### ISSUE TITLE
may i must create CreateMap<Source, Dest>(); every time?

### ISSUE THREAD

**Issue by quliting** [AutoMapper/AutoMapper#4411]
when i user automapper in my project. i have many dto、entity,i want to use mapper.Map<Dest2>(new Source2()); rather then CreateMap<Source, Dest>(); every time.
### Source/destination types

```csharp
// Put your source/destination types here
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by quliting** [comment]
if i use my special mapper.i should use CreateMap<Source, Dest>().ForMember....;
thanks

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
