### ISSUE TITLE
`ProjectTo` throws if nested type is null and it has members included

### ISSUE THREAD

**Issue by OronDF343** [AutoMapper/AutoMapper#4418]
### Source/destination types

```csharp
public class MyObjectSrc
{
    public int Id { get; set; }
    public virtual MyObjectSrcInner? Inner { get; set; }
}

public class MyObjectSrcInner
{
    public string? InnerThing { get; set; }
}

public class MyObjectDest
{
    public int Id { get; set; }
    public string? InnerThing { get; set; }
}
```

### Mapping configuration

```csharp
var mapperCfg = new AutoMapper.MapperConfiguration(e =>
{
    e.CreateMap<MyObjectSrcInner, MyObjectDest>();
    e.CreateMap<MyObjectSrc, MyObjectDest>()
     .IncludeMembers(s => s.Inner);
});
var mapper = new AutoMapper.Mapper(mapperCfg);
```

### Version: 13.0.1
Tested with EF Core 8.0.3 (not required for repro)

### Expected behavior

Including members of a property should not cause the mapping to fail when the property is null.

### Actual behavior

When `Inner` is null, `Map` succeeds but `ProjectTo` throws:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method3(Closure, MyObjectSrc)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\Dev\Test\Test_AutoMapperCollection\Test_AutoMapperCollection\Program.cs:line 20
```

### Steps to reproduce

```csharp
// Inner is null
var src = new[] { new MyObjectSrc { Id = 123, Inner = null } };

// Map succeeds:
var destA = mapper.Map<List<MyObjectDest>>(src);

// ProjectTo throws:
var destAq = src.AsQueryable().ProjectTo<MyObjectDest>(mapper.ConfigurationProvider).ToList();
```

**Comment by lbargaoanu** [comment]
We need a test with a real database. 
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by OronDF343** [comment]
[Full gist here](https://gist.github.com/OronDF343/562b34fb8a01be2745dcdc6790a66646)

**Comment by lbargaoanu** [comment]
Your test is irelevant. Make a repro as sugested.

**Comment by OronDF343** [comment]
Updated first post with DB example

**Comment by lbargaoanu** [comment]
That looks like an EF Core issue. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). Run that as a LINQ statement, without AM. You should get the same result.
