### ISSUE TITLE
ConvertUsing affects projections

### ISSUE THREAD

**Issue by verback2308** [AutoMapper/AutoMapper#4419]
### Description

We have a type converter for DateTime?/DateTime? for some legacy stuff, and it worked fine with usual mappings, but not for projections.
The **ConvertUsing** remark says, "Not used for LINQ projection (ProjectTo)"; however, when the auto mapper tries to project one class (with nullable DateTime with value) to another (with nullable DateTime with value), we receive only null instead of a date value.
But in-memory mapping works fine.
All other types (strings, integers, etc.) map fine.

The issue was gone after disabling the converter:

```csharp
cfg.CreateMap<DateTime?, DateTime?>().ConvertUsing(new DateTimeNullableConverter());
```
Or, I've found a workaround that fixes issue for projections, but loses in-memory mappings:

```csharp
cfg.CreateProjection<Notification, NotificationDto>().ConvertUsing(x=> new NotificationDto
            {
                CreateDate = x.CreateDate,
                Email = x.Email,
                Status = x.Status,
                Id = x.Id,
                Subject = x.Subject,
                SentDate = x.SendDate,
                DelayIntervalSeconds = x.DelayIntervalSeconds
            });
```

### Source/destination types

```csharp
DateTime?/DateTime?
```

### Mapping configuration

```csharp
 public static void Init(IMapperConfigurationExpression cfg)
        {
            cfg.CreateMap<DateTime?, DateTime?>().ConvertUsing(new DateTimeNullableConverter());

            cfg.CreateMap<Notification, NotificationDto>()
               .ForMember(x => x.SentDate, opt => opt.MapFrom(c => c.ProcessedDate));
        }

        public class DateTimeNullableConverter : ITypeConverter<DateTime?, DateTime?>
        {
            public DateTime? Convert(DateTime? source, DateTime? destination, ResolutionContext context)
            {
                if (source == DateTime.MinValue)
                {
                    return null;
                }

                return source;
            }
        }
```

### Version: x.y.z
Project Versions:
AutoMapper 12.0.1, 13.0.1
NHibernate 5.4.6
Fluent Nhibernate 3.2.1

Versions in gist:
Microsoft.EntityFrameworkCore.Sqlite 8.0.3
AutoMapper 13.0.1

### Expected behavior

DateTime? value in the target object is the same as in source object
Like: Email: test@my.com; Subject: Subject 1; Sent: 3/16/2024 3:33:14 PM

### Actual behavior

Value in target object is null
Like: Email: test@my.com; Subject: Subject 1; Sent: null

### Steps to reproduce

This issue reproduces on any ORM and for 2 latest major versions on AutoMapper.
I've prepared a sample for reproduce.

[Sample in gist](https://gist.github.com/verback2308/38e055299b100c6e411eb35c34243e41)

```csharp

//1. Create  converter for DateTime?
        public class DateTimeNullableConverter : ITypeConverter<DateTime?, DateTime?>
        {
            public DateTime? Convert(DateTime? source, DateTime? destination, ResolutionContext context)
            {
                return source == DateTime.MinValue ? null : source;
            }
        }

//2. Init mapping configs and converter
public static void Init(IMapperConfigurationExpression cfg)
        {
            cfg.CreateMap<DateTime?, DateTime?>().ConvertUsing(new DateTimeNullableConverter());

            cfg.CreateMap<Notification, NotificationDto>()
               .ForMember(x => x.SentDate, opt => opt.MapFrom(c => c.ProcessedDate));
        }

//3. Use projections
 var query = context.Notifications.AsQueryable();
 var mappedQuery = query.ProjectTo<NotificationDto>(_mapper.ConfigurationProvider);
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
