### ISSUE TITLE
Upgrade from 6.2.2 to 13.0.1

### ISSUE THREAD

**Issue by erankurgoel** [AutoMapper/AutoMapper#4422]
Hi Team,

I am trying to upgrade AutoMapper from 6.2.2 to 13.0.1 in my project which it based on .net8.0. I could not find any documentation for the upgrade and I am able to see there are lots of breaking change like Mapper class does not has AssertConfigurationIsValid(), Initialize(), cannot use Mapper.Map<T>(request) method as it complains about static access.

![image](https://github.com/AutoMapper/AutoMapper/assets/10261956/52461cd7-26e2-4122-ac3b-d1528cf7b18a)

Do you have any documentation available for this upgrade?

Thanks,
Ankur

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/
