### ISSUE TITLE
stackoverflow exception raised from IValueResolver!

### ISSUE THREAD

**Issue by HppZ** [AutoMapper/AutoMapper#4426]
https://github.com/HppZ/AutoMapperStackoverflowException

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by HppZ** [comment]
I added a repo, hope you can help.

**Comment by lbargaoanu** [comment]
No, follow the link I gave you and make a similar repro.

**Comment by HppZ** [comment]
@lbargaoanu https://gist.github.com/HppZ/cda345b11fee32ce41c86f7854a33494

**Comment by lbargaoanu** [comment]
It's your own code that causes the SO by calling `Map`.

**Comment by HppZ** [comment]
I don't understand. Did I use `IValueResolver` or `Map` incorrectly? 
Actually there should have been some instance reuse logic before the `Map` call, what I want to do is to map `A` instance into `AModel` instance using custom `IValueResolver` and handle the `circular reference` correctly.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
