### ISSUE TITLE
Underscore split destination properties not mapping from complex source entity

### ISSUE THREAD

**Issue by lokirangers42** [AutoMapper/AutoMapper#4427]
### Source/destination types

```csharp
// Put your source/destination types here
```
public class SomeOutputModel
{
    public string TypeAttribute_Label { get; set; }
}
 public class SomeOutputModelMappingProfile : Profile
 {

     public SomeOutputModelMappingProfile()
     {
         //DestinationMemberNamingConvention = LowerUnderscoreNamingConvention.Instance;
         CreateMap<TypeAttributeValue, SomeOutputModel>();
     }
 }
### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
```

In ConfigureServices method of Startup.cs

services.AddAutoMapper(cfg => 
    {
        cfg.DestinationMemberNamingConvention = LowerUnderscoreNamingConvention.Instance;
    }, Assembly.GetExecutingAssembly());
### Expected behavior

Expected the "_" in the destination property name to automatically cause the property to be mapped from the TypeAttribute.Label property on the instance of type TypeAttributeValue.

### Actual behavior

The property with "_" in the name did not map as per previous versions of automapper.

The attempt to define global config in Startup.cs to use LowerUnderscoreNamingConvention was ignored, and the property did not map until I added the line currently commented out in the individual mapping profile.

We have several hundreds of input and output models with properties using "_".  We really need a global config option to make them behave as before.

### Steps to reproduce

simplified version:

TypeAttributeValue _tav = GetTypeAttributeValue();
var _outmodel = _mapper.Map<SomeOutputModel>(_tav);
```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lokirangers42** [comment]
wow, you're helpful arent you.  Not even a comment on why an .AddAutoMapper with config in it doesn't work, instead of having the same config statement in an individual profile, or why target properties with "_" splitting them used to map from complex properties automatically and don't now?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
