### ISSUE TITLE
ProjectTo<T> should support excluding [NotMapped] or explicitly provided entity properties

### ISSUE THREAD

**Issue by soloham** [AutoMapper/AutoMapper#4429]
### Source/destination types

**Entity:**
```csharp
public class TestStepRun : MultiTenantEntity
{
    public int TestStepId { get; set; }

    public TestStep TestStep { get; set; }

	[NotMapped]
    public NetworkEvent NetworkEvent { get; set; }

	[NotMapped]
    public ConsoleLogEvent ConsoleLogEvent { get; set; }

    public bool? Passed { get; set; }
}
```

**DTO:**
```csharp
public class TestStepRunDto
{
    public int? Id { get; set; }

    public int TestStepId { get; set; }

    public bool? Passed { get; set; }

    public NetworkEventDto NetworkEvent { get; set; }

    public ConsoleLogEventDto ConsoleLogEvent { get; set; }
}
```

### Mapping configuration

```csharp
mapper.CreateMap<TestStepRun, TestStepRunDto>();
```

### Version: 12.0.0.0
EF 6.0.1.0

### Expected behavior

The mapper to work out that `NetworkEvent` and `ConsoleLogEvent` are not actually part of the entity in the DB and exclude these from the projection expression.

My use case here is that the two NotMapped properties are part of my domain model however not part of a relational DB, these are persisted in blob storage and my repository is responsible for handling the persistence and retrieval/hydration of my entity from the two data sources.

### Actual behavior

EF tries to project these NotMapped properties using the mapping configuration and fails stating it cannot translate the query, likely due to the fact that it can't find a table for those properties to translate the expression to.

### Steps to reproduce

```csharp
public async Task<TData> GetLastWithDetailsAsync<TData>(int testCaseId, IConfigurationProvider configurationProvider)
{
    var result = await this.DbContext.Set<TestCaseRun>()
        .Where(x => x.TestCaseId == testCaseId)
        .OrderByDescending(x => x.Id)
        .ProjectTo<TData>(configurationProvider)
        .FirstOrDefaultAsync()
        .ConfigureAwait(false); 

    return result;
}
```

**Comment by lbargaoanu** [comment]
You can `Ignore` those.
