### ISSUE TITLE
AutoMapper v12/13 on .Net8 do not honor C# class indexer

### ISSUE THREAD

**Issue by ndenkha** [AutoMapper/AutoMapper#4431]
The previously reported issue: [4430](https://github.com/AutoMapper/AutoMapper/issues/4430)
turned out to be as described here: [stackoverflow](https://stackoverflow.com/questions/78296175/automapper-with-net-8-system-argumentexception-incorrect-number-of-arguments/78296769#78296769)

This is an AutoMapper bug that used to work but failed in the latest version 12.0.0 - 13.0.0

I hope this helps shed light on fixing this issue.

Thanks,

Ninos

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
