### ISSUE TITLE
IgnoreMap alternative implementation does not work alongside IncludeMembers

### ISSUE THREAD

**Issue by MajidAtl** [AutoMapper/AutoMapper#4433]
Hi, the suggested IgnoreMap alternative implementation which has posted here: https://github.com/AutoMapper/AutoMapper/discussions/4041
and exists in repository here:
https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/AutoMapperSpecBase.cs
does not work alongside IncludeMembers when the main object has child list properties.
The attached project shows this issue minimally.
[AutoMapperTest.zip](https://github.com/AutoMapper/AutoMapper/files/14970437/AutoMapperTest.zip)

**Comment by lbargaoanu** [comment]
Then you should write your own version.
