### ISSUE TITLE
Mapping to `DateOnly` and `TimeOnly` doesn't work

### ISSUE THREAD

**Issue by ahmednfwela** [AutoMapper/AutoMapper#4441]
I am trying to convert `DateOnly`/`TimeOnly` structs to/from grpc `Date`/`TimeOfDay` types from https://www.nuget.org/packages/Google.Api.CommonProtos

My approach was writing a two-way converter

### Converter

```csharp
public class DateOnlyTypeConverter :
    ITypeConverter<DateOnly, Google.Type.Date>,
    ITypeConverter<Google.Type.Date, DateOnly>

{
    public Google.Type.Date Convert(DateOnly source, Google.Type.Date destination, ResolutionContext context)
    {
        return new() { Day = source.Day, Month = source.Month, Year = source.Year };
    }

    public DateOnly Convert(Google.Type.Date source, DateOnly destination, ResolutionContext context)
    {
        var res = new DateOnly(source.Year, source.Month, source.Day);
        return res;
    }
}
```

### Mapping configuration

```csharp
CreateMap<DateOnly, Google.Type.Date>()
    .ConvertUsing<DateOnlyTypeConverter>();
CreateMap<Google.Type.Date, DateOnly>()
    .ConvertUsing<DateOnlyTypeConverter>();
```

### Steps to reproduce

```csharp
[Fact]
public void TestDateOnlyMapping()
{
    // Do round-trip mapping
    var date = new DateOnly(2020, 5, 13);
    var dateMapped = _mapper.Map<DateOnly, Google.Type.Date>(date);
    var reverted = _mapper.Map<Google.Type.Date, DateOnly>(dateMapped);
    reverted.ShouldBe(date);
}
```

### Expected behavior

I would expect `reverted` variable in the example above to be the same as the `date` variable.

### Actual behavior

1. `reverted` is equal to `new DateOnly(0001, 01, 01)` 
2. The method `DateOnly Convert(Google.Type.Date source, DateOnly destination, ResolutionContext context)` is never called
3. The method `Google.Type.Date Convert(DateOnly source, Google.Type.Date destination, ResolutionContext context)` is called normally and the mapping is applied.

![image](https://github.com/AutoMapper/AutoMapper/assets/63286031/775f8fff-11f4-4a2d-9197-902f46191a87)

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
