### ISSUE TITLE
Missing configuration validation error when mapping exists between interfaces but not between concrete types

### ISSUE THREAD

**Issue by cervengoc** [AutoMapper/AutoMapper#4442]
### Source/destination types

```csharp

public interface IA
{
  int A { get; set; }
}

public interface IB
{
  int B { get; set; }
}

public class A : IA
{
  public int A { get; set; }
  public string AA { get; set; }
}

public class B : IB
{
  public int B { get; set; }
  public string BB { get; set; }
}

public class ParentOfA
{
  public A Child { get; set; }
}

public class ParentOfB
{
  public B Child { get; set; }
}

```

### Mapping configuration

```csharp

this.CreateMap<IA, IB>()
  .ForMember(e => e.B, o => o.MapFrom(e => e.A))
  .IncludeAllDerived();

this.CreateMap<ParentOfA, ParentOfB>();

// Note, that no mapping is defined between A and B

```

### Expected behavior

I would expect a configuration error, as the mapper will obviously fail at runtime due to not being able to instantiate an interface.

### Actual behavior

No configuration error is raised, configuration is claimed to be valid.

**Comment by cervengoc** [comment]
Hi @lbargaoanu ,

Thank you for the reply. While I do understand that there is indeed a base map here, I still do think that there is an issue. 

According to my understanding, configuration validation has the main purpose of helping users to avoid runtime errors and/or mistakenly not mapped members. Using the setup above gives an obvious runtime error during mapping and it is due to missing configuration in this case. If the base map was between base classes which can be instatiated, then you're point is perfectly valid. But in this case the base map is between interfaces, which will never get successfully instantiated. I think this can be and should be detected by the configuration validation engine.

Thank you in advance if you have the time for a another look and consideration.

**Comment by lbargaoanu** [comment]
That's irrelevant, you can simply pass an already instantiated destination and the map is still useful. So I don't see how AM could possibly do smth here at validation time. But you you can always write your own validator that does what you want. Once you've done that, we'll consider a PR with the enhancement.

**Comment by cervengoc** [comment]
I understand the case when we have an existing destination object. However, in my real example I have a collection of `A`s and `B`s in the source and destination types, and I'm using the `AutoMapper.Collection` package. It was my mistake to not emphasize that. So in that case it basically always fails. For now I'll try to implement it in a custom validator callback, and I'll see if I have time for a PR to add something like an opt-in validation for this in general.
Thank you.
