### ISSUE TITLE
Global DisableExplicitExpansion so all ProjectTo expansions need to be explicit.

### ISSUE THREAD

**Issue by malylemireflo** [AutoMapper/AutoMapper#4447]
Add a global configuration to disable ExplicitExpansion even if the call has a collection of sub elements.
Also if the collection is non nullable, simply don't fill the collection with anything.

This will allow to use ProjectTo with the same behavior as EF includes.

**Comment by malylemireflo** [comment]
How can I without setting all properties to ExplicitExpansion? Also this does not seem to work with non-nullable sub collection. They are expanded event when ExplicitExpansion is set.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
