### ISSUE TITLE
Source object re-used when mapping to same type without .CreateMap.

### ISSUE THREAD

**Issue by liquidbarcodes-magnus** [AutoMapper/AutoMapper#4449]
I've tried using `IMapper.Map<X>(anotherX)` to copy an object to another independent object.
This seems to re-use the source object (anotherX).
Is it the expected logic?

### Mapping configuration

```c#
using System;
using AutoMapper;

public class Dto 
{
	public decimal Quantity { get; set; }
}	

public class Program
{
	public static void Main()
	{
		TestMapper("Blank config", new MapperConfiguration(cfg => { }).CreateMapper());
		TestMapper("Dto->Dto config", new MapperConfiguration(cfg => { cfg.CreateMap<Dto,Dto>(); }).CreateMapper());
	}
	
	public static void TestMapper(string description, IMapper mapper) {
		var a = new Dto { Quantity = 1 };
		var b = mapper.Map<Dto>(a);
		b.Quantity = -1;
		if (a.Quantity == -1)
    			Console.WriteLine($"{description}: Source object was re-used!");
		else
			Console.WriteLine($"{description}: OK!");
	}
}
```

Please see this fiddle https://dotnetfiddle.net/c7Vrka

### Expected behavior

My understanding is that that the mapper with blank configuration should work the same as the mapper configured with `.CreateMap<Dto, Dto>()` , however I've not found any documentation that explains that.

May be safer to somehow visibly fail to map (null / exception?) instead of re-using the source object?

### Actual behavior

Source-object is returned from `.Map()` when the mapper isn't explicitly configured to map it.

### Steps to reproduce

Please see this fiddle https://dotnetfiddle.net/c7Vrka

**Comment by lbargaoanu** [comment]
This is the expected behaviour.
