### ISSUE TITLE
Many broken links in the documentation

### ISSUE THREAD

**Issue by mikeKuester** [AutoMapper/AutoMapper#4450]
Hi,

in the page content all links are broken in the documentation at https://docs.automapper.org/

Move to https://docs.automapper.org/en/latest/Getting-started.html and check the URLs:
Flattening => https://docs.automapper.org/en/latest/Getting-started.html#Flattening.html
custom value resolvers => https://docs.automapper.org/en/latest/Getting-started.html#Custom-value-resolvers.html

All links are creates as anchors on the same page with the "#":

```html
AutoMapper also supports <a class="reference internal" href="#Flattening.html"><span class="xref myst">Flattening</span></a>
```

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by DavidFidge** [comment]
I feel like this should not be closed as completed as it is an open problem and nobody will create a pull request without an open issue.
