### ISSUE TITLE
List Mapping: ForMember configuration when mapping is conditional for DateTime properties , destination object DateTime properties always has value DateTime.MinValue 

### ISSUE THREAD

**Issue by veizx** [AutoMapper/AutoMapper#4456]
### Source/destination types

```csharp
Source type:

public class ATest
{
    /// <summary>
    /// 
    /// </summary>
    public int Id { get; set; }
}


Destination type:

public class ATest2
{
    /// <summary>
    /// 
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 
    /// </summary>
    public DateTime DateCreated { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<ATest, ATest2>()
    .ForMember(x => x.DateCreated, opt => opt.MapFrom((src, dest) 
        =>
    {
        return dest.Id <= 0 ? DateTime.UtcNow : dest.DateCreated;
    }))
    .EqualityComparison((source, destination) => source.Id == destination.Id);
```

### Version: x.y.z
Automapper => 12.0.1
Automapper.Collection => 9.0.0
EF Core => 8.0.3

### Expected behavior

This mapping was provided for mapping List of entites defined above. My expectation is that when I will check if it is existing entity or not (has database Id or not), based on this condition I can leave the DateCreated value of existing item as it is and just set the DateCreated value for new items.

### Actual behavior
But after mapping the lists, existing items DateCreated value is always set to DateTime.MinValue.  I debugged and I saw that I am not getting the destination object values for DateTime. 

I already tried the ```.Condition()``` and ```.PreCondition()``` methods but the same happens.

See images below:

**Image1**:
![s1](https://github.com/AutoMapper/AutoMapper/assets/50356904/05667fe3-bbbe-4733-96a3-b7d4f25bc74b)

**Image2**:
![s2](https://github.com/AutoMapper/AutoMapper/assets/50356904/cc7fde74-f79a-424d-83ba-d0f0990e4bd5)

**Image3**:
![s3](https://github.com/AutoMapper/AutoMapper/assets/50356904/9ff631d8-72f0-4b55-82d8-26941a18ac69)

**Image4**:
![s4](https://github.com/AutoMapper/AutoMapper/assets/50356904/bd37f7b0-0172-434e-8e9e-546eb0c538c0)

Is my expectation wrong or is it a bug ?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
