### ISSUE TITLE
Automapper  ReverseMap not working as expected while using IValueConverter

### ISSUE THREAD

**Issue by ji2026** [AutoMapper/AutoMapper#4458]
Automapper  ReverseMap not working as expected 
see below example 

            ParentA ssssssss = new ParentA { Id = 1, isActive = "Y", Name = "test" };
            var response = automapper.Map<ParentB>(ssssssss);
            response.Value = 500;
            var yyyy = automapper.Map<ParentA>(response);

    public class ParentA
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string isActive { get; set; }
    }

    [AutoMap(typeof(ParentA), ReverseMap = true)]
    public class ParentB
    {
        public int Id { get; set; }

        public string Name { get; set; }

        [ValueConverter(typeof(IntConverter))]
        [SourceMember("isActive")]
        public int Value { get; set; } 
    }

    public class IntConverter : IValueConverter<string, int>/*, IValueConverter<int, string>*/
    {
        public int Convert(string sourceMember, ResolutionContext context)
        {
            if (sourceMember == "Y") return 100;
            if (sourceMember == "N") return 200;
            if (sourceMember == "P") return 500;

            return 1000;
        }
     
        public string Convert(int sourceMember, ResolutionContext context)
        {
            throw new NotImplementedException();
        }
    }

}

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
