### ISSUE TITLE
Conditional mapping of a null source value no longer works with AutoMapper 13.0.1 and dotnet 8

### ISSUE THREAD

**Issue by TonyLinnabery** [AutoMapper/AutoMapper#4460]
We had a group of developers who implemented some auto mapper profiles to help "merge" two objects of the same type together. Prior to migrating from dotnet 6 to dotnet 8 this code used to work without any issues. Moving to dotnet 8, the following code now errors out when trying to conditionally exclude a null source member.

```csharp
            .ForAllMembers(o => o.Condition((src,dest, member) => member != null));
```

### Source/destination types

```csharp
public class HomeInformationModel
{
    public IEnumerable<POCO1> ChangeSubmissions { get; set; }
    public POCO2 PropertyNumber { get; set; }
    public POCO2 HouseName { get; set; }
    public POCO2 Subdivision { get; set; }
    public POCO2 Location { get; set; }
    public POCO2 CheckinDay { get; set; }
    public POCO2 Bedrooms { get; set; }
    public POCO2 MasterBedrooms { get; set; }
    public POCO2 InsideBaths { get; set; }
    public POCO2 OutsideBaths { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<HomeInformationModel, HomeInformationModel>()
            .ForMember(d => d.HouseName, o => o.Ignore())
            .ForMember(d => d.PropertyNumber, o => o.Ignore())
            .ForMember(d => d.Subdivision, o => o.Ignore())
            .ForMember(d => d.Location, o => o.Ignore())
            .ForAllMembers(o => o.Condition((src,dest, member) => member != null));
```

### Version: 13.0.1
dotnet 8

### Expected behavior

AutoMapper should ignore the null members on the source.

### Actual behavior

Application throws the following error:

> AutoMapper.AutoMapperMappingException: Error mapping types.
> 
> Mapping types:
> HomeInformationModel-> HomeInformationModel
> Namespace.HomeInformationModel-> Namespace.HomeInformationModel
> 
> Type Map configuration:
> HomeInformationModel-> HomeInformationModel
> Namespace.HomeInformationModel-> Namespace.HomeInformationModel
> 
> Destination Member:
> CheckinDay
>
> ---> System.NullReferenceException: Object reference not set to an instance of an object.

### Steps to reproduce

```csharp
var homeInfo = _mapper.Map(notSubmittedChanges.HomeInfo ?? new HomeInformationModel(),
                prefilledChanges.HomeInfo);
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by TonyLinnabery** [comment]
Wait... so I put in several hours of troubleshooting and debugging this issue, follow the guidelines for opening an issue for this problem and it just gets closed with the comment "prove it"? I can create a gist showing this, but man, come on... closing an issue for the sake of having no open issues is pretty weak...

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
