### ISSUE TITLE
Order of properties are wrong - projectTo same type and concat it

### ISSUE THREAD

**Issue by cyril-iselin** [AutoMapper/AutoMapper#4463]
### Mapping
`CreateMap<Entity, DTO>();
CreateMap<Entity2, DTO>();
`

### Expected behavior

The property order should be as defined in the mapping or have at least the same order for the same dto type ;)
`m_mapper.ProjectTo<DTO>(query).Concat(m_mapper.ProjectTo<DTO>(query2))
`

### Actual behavior

In Version 12.1 it works, in Version 13.1 the order of the property are not the same!  (which leads in the not supported exception)

`System.NotSupportedException: The type 'DTO' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order.`

### Steps to reproduce

`m_mapper.ProjectTo<DTO>(query).Concat(m_mapper.ProjectTo<DTO>(query2))
`

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
