### ISSUE TITLE
EnumToEnumMapper maps by number, ignoring the name

### ISSUE THREAD

**Issue by RomanSoloweow** [AutoMapper/AutoMapper#4467]
Version: 12.0.1

Potencially it's can be enought just be able configure behavior for EnumToEnumMapper : Any, ByValue, ByName

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).
If you want anything different, you'll have to replace it with your version.

**Comment by RomanSoloweow** [comment]
How EnumToEnumMapper related with expression tree?
