### ISSUE TITLE
NullReferenceException not being handled inside MapFrom when thrown from Linq expression tree

### ISSUE THREAD

**Issue by chrisheil** [AutoMapper/AutoMapper#4468]
### Source/destination types

```csharp
public class SourceObject
{
    public List<string> Models { get; set; }
}

public class DestinationObject
{
    public int LengthOfString { get; set; }
}
```

### Mapping configuration

```csharp

var mapperConfiguration = new MapperConfiguration(x =>
{
    x.CreateMap<SourceObject, DestinationObject>()
        .ForMember(dest => dest.LengthOfString, opt => opt.MapFrom(src => src.Models.First(i => i.Length > 0).Length));
});
var mapper = mapperConfiguration.CreateMapper();
```

### Version: 11.0.0 through 13.0.1

Version 10.1.1 and below not affected. Tests were run on .NET 6 and .NET 8

### Expected behavior

When `src.Models` is a list of `null` strings, a `NullReferenceException` should be thrown inside of the `.First(i => i.Length > 0)` expression tree. This should be ignored and set the value to default (0) as mentioned in the [Getting Started Guide](https://docs.automapper.org/en/stable/Getting-started.html#how-do-i-use-automapper)

### Actual behavior

An `AutoMapperMappingException` is thrown indicating a failure to map the destination member `LengthOfString`.

### Steps to reproduce

I have set up an Xunit test to demonstrate this in a Gist here: https://gist.github.com/chrisheil/a34e7e6b3beeac4001d831a877aadef5

* Create a new Xunit project
* Install AutoMapper v10.1.1, run the test and it will pass
* Upgrade to 11.0.0 or higher and it will fail.

I also included two alternative mapping rules which both demonstrate throwing `NullReferenceException`s at different points but result in a passing test.

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html).
The purpose of our null checking is to prevent silly checks as in `source?.Property?.InnerProperty`, not to prevent any possible NRE. Granted, somettimes it actually does that, as it falls back to a try catch when it cannot rewrite the expression. I think that's unfortunate, but backward compatibility. I'd rather tolerate a small number of breaking changes than going further in this direction.

**Comment by chrisheil** [comment]
@lbargaoanu Thank you for the explanation. I'll revisit my code to see if I can handle this in a better way as well, I just wanted to point out what might be a bug.

Would it be worth adding to the v11 Migration documentation?

To make it easier for people in the future to see my test example I'm going to copy the gist into this comment so I can be free to drop that gist in the future.

``` csharp
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace AutoMapperTest;

public class SourceObject
{
    public List<string> Models { get; set; }
}

public class DestinationObject
{
    public int LengthOfString { get; set; }
}

public class Tests
{
    [Fact]
    public void Test()
    {
        var mapperConfiguration = new MapperConfiguration(x =>
        {
            x.CreateMap<SourceObject, DestinationObject>()

                // This throws NullReferenceException within `.First()` when `i` is null
                // In v10 this returns the expected default of 0.
                // In v11+ this fails the mapping and throws an exception
                .ForMember(dest => dest.LengthOfString, opt => opt.MapFrom(src => src.Models.First(i => i.Length > 0).Length));

                // Both of these throw NullReferenceException, but this is caught by AutoMapper and set to a default of 0
                //.ForMember(dest => dest.LengthOfString, opt => opt.MapFrom(src => src.Models.First().Length));
                //.ForMember(dest => dest.LengthOfString, opt => opt.MapFrom(src => HasStringWithLength(src).Length));
        });
        var mapper = mapperConfiguration.CreateMapper();

        var from = new SourceObject
        {
            Models = [null, null]
        };

        var to = mapper.Map<DestinationObject>(from);

        Assert.True(to.LengthOfString == 0);
    }

    // Workaround, move the Linq expression to a static method
    private static string HasStringWithLength(SourceObject src)
    {
        return src.Models.First(i => i.Length > 0);
    }
}
```
