### ISSUE TITLE
Issues with Bidirectional Mapping Configuration and Generic 'Count' Method Error in AutoMapper v6

### ISSUE THREAD

**Issue by jordidalmauokay** [AutoMapper/AutoMapper#4469]
When I want to map an expression on TSource to TTarget, it makes sense that my mapping configuration defines a map from TSource to TTarget. However, it also needs a map from TTarget to TSource. Why is that?

Also, mapping a certain expression, that worked on AM v6, now gives me this error, but I have no idea how to fix this: 

```
No generic method 'Count' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
