### ISSUE TITLE
Caching of shared custom collection within Dependency Injection causes 500 error

### ISSUE THREAD

**Issue by CGitBeaver** [AutoMapper/AutoMapper#4471]
I made a webapp with Swagger so the bug can easily be reproduced. As it uses Dependency Injection as well as multiple projects I am not sure I could use a gist. I have created a repository instead under the following link: [https://github.com/CGitBeaver/AutoMapperBug/tree/main](https://github.com/CGitBeaver/AutoMapperBug/tree/main).
Please let me know if there are issues with the solution or with me providing a full repository instead of a gist. I am fairly new to using github.

### Source/destination types

Source: AutoMappingClassBLarge, AutoMappingClassB, AutoMappingSharedCollection, AutoMappingSharedClass

Destination: AutoMappingClassBLargeMapped, AutoMappingClassBMapped, List<AutoMappingSharedClassMapped>, AutoMappingSharedClassMapped

### Mapping configuration

    public AutoMappingWeb()
    {
        CreateMap<AutoMappingClassALarge, AutoMappingClassALargeMapped>()
           .ForMember(
              dest => dest.ClassAMappedList,
              opt => opt.MapFrom(src => src.ClassAList));

        CreateMap<AutoMappingClassA, AutoMappingClassAMapped>()
          .ForMember(
             dest => dest.Data,
              opt => opt.MapFrom(src => src.Data));

        CreateMap<AutoMappingSharedClass, AutoMappingSharedClassMapped>()
             .ForMember(
                dest => dest.Name,
                opt => opt.MapFrom(src => src.Name));

        CreateMap<AutoMappingClassBLarge, AutoMappingClassBLargeMapped>();

        CreateMap<AutoMappingClassB, AutoMappingClassBMapped>();
    }

### Versions

AutoMapper 12.0.1
AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.1

### Steps to reproduce

- Perform an IIIReset
- Call function A
- Call function B

### Expected behavior

Both calls A and B should return the correct object that are being created in the AutoMapper.Bugfix.Web.AutoMappingController.

### Actual behavior

Call B fails with a 500 server error and the following details within Visual Studio:
"AutoMapper.AutoMapperMappingException
  HResult=0x80131500
  Message=Error mapping types.
  Source=Cannot evaluate the exception source
  StackTrace:
Cannot evaluate the exception stack trace

  This exception was originally thrown at this call stack:

Inner Exception 1:
AutoMapperMappingException: Error mapping types.

Inner Exception 2:
AutoMapperMappingException: Error mapping types.

Inner Exception 3:
NullReferenceException: Object reference not set to an instance of an object."

### Further Information

The steps for reproduction of the bug have to be done in specifically that order as calling B first will lead to both calls working fine afterwards. Meaning IISReset -> B -> A -> B and any other similar order works completely fine.

The error does not occur if the injected _mapper within the controller is created locally instead like this:

MapperConfiguration config = new(cfg => cfg.AddProfile<AutoMappingWeb>());
var mapper = config.CreateMapper();

Another fix/workaround, the one we are temporarily using in our actual solution, is to not use the AutoMappingSharedCollection within AutoMappingClassB and using a simple List<AutoMappingSharedClassMapped> instead.

These two possible workarounds alongside the fact that the error only occurs if A is called first after an IISReset leads us to believe that the error is likely some sort of caching interaction between AutoMapper and Dependency Injection but where exactly the bug comes from is beyond my colleagues and I.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
