### ISSUE TITLE
Please remove the sealed keyword from MapperConfiguration.cs

### ISSUE THREAD

**Issue by pfeigl** [AutoMapper/AutoMapper#4473]
We have a kind of large code base with alot of microservices.

To enforce consistency throughout all of those microservices, we established a code base with various internal nuget packages.
One of them contains a streamlined `MapperConfiguration`  which looks pretty much like this:

```csharp
    public abstract class MapperConfigurationBase : MapperConfiguration
    {
        protected MapperConfigurationBase(Action<IMapperConfigurationExpression> configure) : base(configure)
        {
            ValidateConfiguration();
        }

        private void ValidateConfiguration()
        {
            // do some custom validation stuff, we want to have on every mapper config
            // ... removed for better readability

            AssertConfigurationIsValid();
        }
    }
```

This allows us to have an enforced call to `AssertConfigurationIsValid` in all of our mapper configs.

With the change to making this object sealed, this approach is no longer viable and put's us into a situation, where we would have to change unnecessary code in all of our code bases.

Thanks for considering this :-)
Philipp

**Comment by lbargaoanu** [comment]
`AssertConfigurationIsValid` is designed to be called only during development. You're not supposed to derive from `MapperConfiguration`. But you can write custom validators.
