### ISSUE TITLE
AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by arc1997** [AutoMapper/AutoMapper#4475]
When Running All Test Cases Gettting error as AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.
Same tests are running when ran seperately.
need to understand what can be issue with automapper
using Version=3.2.1.0

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
