### ISSUE TITLE
IEnumerable<T> mistakenly trying to map to Order property in dest

### ISSUE THREAD

**Issue by TylerBurnett** [AutoMapper/AutoMapper#4479]
Although this looks like _intended behaviour_, from a DX perspective it's a bit of a PITA since it's fairly common to map collection types, all of which now have this `Order()` behaviour.

I lost a fair bit of time trying to figure this out when migrating to DotNet 8 so I thought it was worth chucking up in case someone else has had a similar issue.

### Source/destination types

```csharp
  public class TestObject
  {
      public List<CollectionObject> Collection { get; set; } = new();
      
      public int Order { get; set; }
  }
  
  public class CollectionObject;
```

### Mapping configuration

```csharp
  var mapperConfiguration = new MapperConfiguration(
      cfg => cfg.CreateMap<IEnumerable<CollectionObject>, TestObject>()
          .ForMember(s => s.Collection, o => o.MapFrom(s => s)));
```

### Version: x.y.z
It affects all Dotnet versions from 7 onwards

### Expected behaviour

You would expect that like the versions before 7, the `IEnumerable` would be placed into the `Collection` Property, specifically as the mapping prescribes.

### Actual behaviour
AutoMapper is getting caught up with the new method, `IEnumerable.Order()` which is mistakenly trying to map to the Order property in the destination object.

### Steps to reproduce

```csharp
// Minimal repro

using AutoMapper;

var mapperConfiguration = new MapperConfiguration(
    cfg => cfg.CreateMap<IEnumerable<CollectionObject>, TestObject>()
        .ForMember(s => s.Collection, o => o.MapFrom(s => s)));

var mapper = mapperConfiguration.CreateMapper();

IEnumerable<CollectionObject> collection = Enumerable.Range(0, 5).Select(_ => new CollectionObject());
mapper.Map<TestObject>(collection);

// Objects
public class TestObject
{
    public List<CollectionObject> Collection { get; set; } = new();
    
    public int Order { get; set; }
}

public class CollectionObject;

```

**Comment by lbargaoanu** [comment]
You need a type converter, not `ForMember`.
