### ISSUE TITLE
Links don't seem to work in latest stable ReadTheDocs

### ISSUE THREAD

**Issue by gortok** [AutoMapper/AutoMapper#4482]
The [ReadTheDocs site for Automapper](https://docs.automapper.org/) anchor links do not seem to link to the places they should.

Examples:

From the [Getting Started Guide]():

> For ASP.NET Core the [Dependency Injection](https://docs.automapper.org/en/stable/Getting-started.html#Dependency-injection.html#asp-net-core) article shows how to configure AutoMapper in your application.

The substance of that link when clicked is:

```
https://docs.automapper.org/en/stable/Getting-started.html#Dependency-injection.html#asp-net-core
```

When in reality it should be:

```
https://docs.automapper.org/en/stable/Dependency-injection.html#asp-net-core
```

I assume (but don't know) that perhaps a leading slash on the URL generation will resolve the issue. All the main page links I've clicked exhibit this issue.

**Comment by lbargaoanu** [comment]
We'll take a PR to fix those.
But any fix would need to be tested beforehand. Maybe in a playground repo or smth.

**Comment by lbargaoanu** [comment]
Ses also https://github.com/AutoMapper/AutoMapper/pull/4420#issuecomment-2007734541

**Comment by gortok** [comment]
Why did you close the issue?  That doesn't make any sense at all.

The issue is still going to exist, whether or not I even know how to fix it.
