### ISSUE TITLE
ProjectTo throws System.InvalidCastException when source is of type Moq.EntityFrameworkCore.DbAsyncQueryProvider.InMemoryAsyncEnumerable

### ISSUE THREAD

**Issue by ismijgelijk** [AutoMapper/AutoMapper#4485]
I'm writing unit tests and use Moq.EntityFrameworkCore.DbAsyncQueryProvider.InMemoryAsyncEnumerable when mocking repositories. 
This works fine until ProjectTo is called, then a System.InvalidCastException is thrown.
To make sure the issue was not with my code, I downloaded the automapper source, and changed a unittest, to see if I could reproduce the issue.
I added 2 tests, and noticed that one failed, the other did not.
These tests are copied under "Steps to reproduce"

### Source/destination types
Unchanged - same as the other unittests

### Mapping configuration
Unchanged - same as the other unittests

### Version: x.y.z
My project uses 13.0.1, the tests were done on the current master branch

### Expected behavior
both unittests to succeed

### Actual behavior
ProjectToShouldWork1 succeeds

ProjectToShouldWork2 fails with exception System.InvalidCastException
Unable to cast object of type 'Moq.EntityFrameworkCore.DbAsyncQueryProvider.InMemoryAsyncEnumerable`1[AutoMapper.UnitTests.Projection.ProjectTest+Customer]' to type 'System.Linq.IQueryable`1[AutoMapper.UnitTests.Projection.ProjectTest+CustomerDto]'.

### Steps to reproduce

In the unittest AutoMapper.UnitTests.Projection.ProjectWithFields:
 - add nuget package Moq.EntityFrameworkCore (I used 8.0.1.2)
 - add the following 2 tests

```csharp
    [Fact]
    public void ProjectToShouldWork()
    {
        var customers = new InMemoryAsyncEnumerable<Customer>(new List<Customer>
        {
            new Customer { FirstName = "Bill", LastName = "White", Address = new Address("Street1") }
        } );

        IQueryable projected = customers.ProjectTo(typeof(CustomerDto), _config);

        projected.Cast<CustomerDto>().Single().FirstName.ShouldBe("Bill");
    }

    [Fact]
    public void ProjectToShouldWork2()
    {
        var customers = new InMemoryAsyncEnumerable<Customer>(new List<Customer>
        {
            new Customer { FirstName = "Bill", LastName = "White", Address = new Address("Street1") }
        });

        var projected = customers.ProjectTo<CustomerDto>(_config);

        projected.Single().FirstName.ShouldBe("Bill");
    }
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
