### ISSUE TITLE
Could not install package 'AutoMapper 13.0.1'.

### ISSUE THREAD

**Issue by vsrcoccanada** [AutoMapper/AutoMapper#4486]
Install-Package : Could not install package 'AutoMapper 13.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8.1', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package AutoMapper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
