### ISSUE TITLE
Map<A, B>(null, b) returns b

### ISSUE THREAD

**Issue by pmulinka** [AutoMapper/AutoMapper#4490]
### Source/destination types

```csharp
	class A {
		public int prop {get; set;}
	}
	
	class B {
		public int prop {get; set;}
	}
```

### Mapping configuration

```csharp
		var config = new MapperConfiguration(cfg => {
			cfg.CreateMap<A, B>();
		});
```

### Expected behavior

When source is null, Map(source, destination) should return null. This was behavior in version 11.0.1 and prior.

### Actual behavior

When source is null, unchanged instance of destination is returned

### Steps to reproduce

```csharp
		A a = null;
		B b = new() { prop = 10 };
		var mapper = new Mapper(config);
		b = mapper.Map<A, B>(a, b);
```

### my 2 cents
It looks to me that in ExpressionBuilder.NullCheckSource:
```csharp
var ifSourceNull = memberMap == null ?
    destination.IfNullElse(DefaultDestination(), ClearDestinationCollection()) :
    mustUseDestination ? ClearDestinationCollection() : DefaultDestination();
```
is not alright. If source is null and destination is not null, ClearDestinationCollection() is called but in my example, destination is not collection and therefore ClearDestinationCollection() just returns destination.

**Comment by lbargaoanu** [comment]
Thet's the intended behaviour.
