### ISSUE TITLE
Using built in EF7 string.join in Config

### ISSUE THREAD

**Issue by statler** [AutoMapper/AutoMapper#4494]
Is it possible to create a config that will implement the built in EF7 string.join?

Pre my recent closed ticket, the method only works on IEnumberable which essentially requires a group (refer https://github.com/dotnet/efcore/issues/28264). 

Basically a version of the following that is evaluated using the built in string_agg rather than querying a redundant join and compiling clientside.

```
var configuration = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<SalesOrderHeader, SalesOrderHeaderDto>()
        .ForMember(dest => dest.SalesInfoCSV, opt => opt.MapFrom(src => string.Join(", ", src.SalesOrderDetail.Select(x => x.SalesOrderId.ToString())))).IncludeAllDerived();
});
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
