### ISSUE TITLE
many hyperlinks don't work in the documentation

### ISSUE THREAD

**Issue by WellspringCS** [AutoMapper/AutoMapper#4498]
I'm using a relatively current version of Chrome.

If I navigate to here...
https://docs.automapper.org/en/stable/Getting-started.html

...then find a link for Flattening and click on it....
https://docs.automapper.org/en/stable/Getting-started.html#Flattening.html

I get nowhere because the above url is bogus. If I have an inspiration and fix the url manually to:
https://docs.automapper.org/en/stable/Flattening.html

...I can get to the intended page.

This issue is seemingly all over the site. Seems like everything I click on is broken in this way.

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/4482
