### ISSUE TITLE
Feature request: derive source / destionation types from type converter

### ISSUE THREAD

**Issue by vzam** [AutoMapper/AutoMapper#4500]
### Source/destination types

```csharp
public class Optional<T> {
  public bool HasValue { get; set; }
  public T Value { get; set; }
}

public class Source {
  public Optional<bool> Flag { get; set; }
}

public class Destination {
  public bool Flag { get; set; }
}
```

### Mapping configuration

```csharp
public class OptionalTypeConverter<T> : ITypeConverter<Optional<T>, T>
{
  public T Convert(Optional<T> source, T destination, ResolutionContext context)
  {
    return source.HasValue ? source.Value : default;
  }
}

var config = new MapperConfiguration(cfg => {
  cfg.CreateMap(typeof(Optional<>), typeof(object)).ConvertUsing(typeof(OptionalTypeConverter<>));
  cfg.CreateMap<Foo, Bar>();
});
```

### Description

I do not expect this to work because the invalid cast from `ITypeConverter<Optional<T>, T>` to `ITypeConverter<Optional<T>, object>`, but would it be possible to derive the type from the type arguments of the `ITypeConverter`? For example like:

```csharp
var config = new MapperConfiguration(cfg => {
  cfg.CreateMapUsing(typeof(OptionalTypeConverter<>));
});
```

In the current situation, my options are:
- replace the second `T` with `object` and do boxing for all the value types
- register a separate mapper for every possible `T` like in `cfg.CreateMap(typeof(Optional<bool>), typeof(bool)).ConvertUsing(typeof(OptionalTypeConverter<bool>))`

I would like use this together with `ForAllMembers` to overwrite values of `Bar` based on the condition if the `Optional` value is present, so usually the members are configured implicitly through that rule.

**Comment by lbargaoanu** [comment]
You can replace the map with a conversion operator to `T` in `Optional`. Or use a custom object mapper.
