### ISSUE TITLE
AssertConfigurationIsValid reports no error if property is not mapped, but mentioned in via IncludeBase

### ISSUE THREAD

**Issue by PashaPash** [AutoMapper/AutoMapper#4514]
When the readonly property is mapped in the destination interface, the corresponding property is not mapped in the implementing destination class, and no error is thrown during validation.

Gist: https://gist.github.com/PashaPash/d169b2256b3c4075056e8c34defd0811

### Source/destination types

```csharp
interface IDestination
{
    int SomeProp { get; }
}

class Destination : IDestination
{
    public int SomeProp { get; set; }
}

class Source 
{
    public int SomeOther { get; set; } = 42;
}
```

### Mapping configuration

```csharp
var configurationNotMapped = new MapperConfiguration(cfg => 
{
    cfg.CreateMap<Source, IDestination>()
        .ForMember(d => d.SomeProp, o => o.MapFrom(s => s.SomeOther));

    cfg.CreateMap<Source, Destination>()
        // any mention of target property will make it mapped
        //.ForMember(d => d.SomeProp, o => {})
        .IncludeBase<Source, IDestination>();
});
```

### Expected behavior

Either property value is set or `AssertConfigurationIsValid()` throws an exception

### Actual behavior

Property is not set and no exception on `AssertConfigurationIsValid()`

### Steps to reproduce

```csharp
// no exception
configurationNotMapped.AssertConfigurationIsValid();

// will output 0
Console.WriteLine(configurationNotMapped.CreateMapper()
    .Map<Destination>(source).SomeProp);
```

Any mention of the property in the Destination class map enables the mapping, for example:

```csharp
cfg.CreateMap<Source, Destination>()
    // enables the property to be mapped as defined in IDestination map
    .ForMember(d => d.SomeProp, o => {})
    .IncludeBase<Source, IDestination>();
```

The real use case for us was when the property was made read-only after the mapping was in place, causing the mapping to stop working without a validation error.

**Comment by lbargaoanu** [comment]
Readonly properties are ignored by validation. If tha's a problem, you can write a custom validator.

**Comment by PashaPash** [comment]
@lbargaoanu could you please check the example again:
the problem is:
- there is a setter
- property not mapped
- `AssertConfigurationIsValid` throws no exception

**Comment by lbargaoanu** [comment]
The setter is irrelevant because there is no match there, there is a match in the base map because of the resolver, but no setter.
