### ISSUE TITLE
Failed a lot unit tests with message AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by Ciget** [AutoMapper/AutoMapper#463]
Hi guys,

I have a problem. First time when i run unit test for a project most tests failed because AutoMapper.AutoMapperMappingException: AutoMapper.AutoMapperMappingException : Missing type map configuration or unsupported mapping.

I have all profilers to map all necessary type. When i run these tests for second time - everything is good.

Could you help me with identifing the problem?

Thanks in advance.

**Comment by centur** [comment]
It might be that the issue exists but it's very elusive. 
I'm on XUnit 2.1.0 and Automapper 4.0.4. Using Resharper runner.
Just run into "sounds similar" issue:
Unit testing WebAPI controllers and because my mapper profile was loaded inside autofac configuration - to properly setup controller SUTs I had to run automapper initialization in unit test class ctor like this:

```
AutoMapper.Mapper.Reset();
AutoMapper.Mapper.Initialize(cfg => {cfg.AddProfile<AutoMapperProfile>();});
AutoMapper.Mapper.AssertConfigurationIsValid();
```

Initially I was running it in non-static ctor and when I have to run multiple unit tests  in parallel ( about 50) -  I got flux of few tests failing randomly with same error message. When ran 1 by 1 - they always green. It looks like race condition and appears once per 3-5-7 successful-all-green runs. Very ocassionally

Follow up investigation discovered:
1. This initialization code should be run in the static ctor. 

Cool, now all tests for a single controller are always green. Except when they being ran in a batch with other controller tests - it fails even more seldom, but still.

It feels that there is a potential very rare race condition around ```AutoMapper.Mapper.Reset();``` when it's called often (in non-static ctor = for each test, in static ctor - once per class initialization).
Commenting this line out and moving test setup into static ctor for each test made my test results "always green" within 20 consequent runs. But I still suspect that it's because my initialization is now in static ctor and not in object ctor.

**Comment by jbogard** [comment]
One thing - Mapper.Initialize calls Mapper.Reset - so that's redundant.

**Comment by centur** [comment]
This is a good point. Do you still think it's worth to chase and repro the race condition in mapper static calls or its unlikely there?

**Comment by jmurret** [comment]
I had a similar issue as described here and found that I had other tests calling Initialize outside of my one centralized base class for Automapper profile tests.  Once I changed them to all use the same thread safe static constructor (similar to @Ciget) that loads all profiles needed across all tests, my issues went away.  Taking into account what @jbogard said, the parallelism of the xunit runner seemed to be causing the outlying Mapper.Initialize calls to most likely call Reset on the Mapper and stomp on the configuration of other tests and cause them to fail.  @centur, have you looked at how many different Mapper.Initialize calls are being called across all of your tests in one of your batches?  You may want to check and see if have some random outliers that may be stomping on your tests when the parallelism of the test runner executes them.

**Comment by centur** [comment]
@jmurret I have one in each static constructor of the test class which now feels fine - working without issues, but this just rings the bell for me that Initialize method is not a thread-safe one.

**Comment by mklaber** [comment]
I also came across this issue in a DNX ASP.NET 5 test project. I'm providing my solution here for posterity--perhaps it'll help someone else.

I moved the call to `Initialize(cfg => { cfg.CreateMap...` to static constructors and my tests ran slightly more reliably, but still not completely consistently. I ended up setting up my [configuration class](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started#where-do-i-configure-automapper) like so:

```csharp
    public class MapperConfiguration
    {
        public static void Configure()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.AddProfile<ApiModelProfile>();
            });

        }

        public static void ConfigureForTests()
        {
            Mapper.AddProfile<ApiModelProfile>();
        }

        public class ApiModelProfile : Profile
        {
            protected override void Configure()
            {
                this.CreateMap<Order, OrderDto>();
            }
        }
    }
```

And then called `MapperConfiguration.ConfigureForTests()` in static constructors. (Well, actually, I got it to work reliably enough that I put it in an `AutomapFixture` class and implemented `IClassFixture<AutomapFixture>` on all classes that I had previously been using static constructors.)

Note that I'm also using the `IgnoreAllNonExisiting` extension described here: [AutoMapper: "Ignore the rest"?](http://stackoverflow.com/a/26760463/612166) which may have been contributing to the issue though didn't have a good way to test.

**Comment by PivotalAnimal** [comment]
I am experiencing the same problem and it is very annoying. When I run all tests, one of them fails. When I run that same test by itself, it works. Please help! My Repo:
[https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore)

**Comment by sfmskywalker** [comment]
This issue happens for me too. Would there be a way to instantiate a `Mapper` without having its configuration be stored statically? That way, each unit test can create its own instance.

**Comment by sfmskywalker** [comment]
Turns out that's actually possible - instantiating my own mapper per unit test works like a charm.

**Comment by VinS101** [comment]
@sfmskywalker Could you elaborate a little bit more? Do you instantiate a mapper instance per test and inject it into your system under test?

**Comment by sfmskywalker** [comment]
@VinS101 That's exactly right. For example, this is what I do in the constructor of my xUnit tests:

```csharp

public class MyServiceTests
{
   private readonly IMapper _mapper;

   public MyServiceTests()
   {
       _mapper = new MapperConfiguration(cfg => cfg.AddProfile<MyMappingProfile>()).CreateMapper();
   }
}

```

This will cause a new mapper instance to be created for each individual test.

**Comment by VinS101** [comment]
Thanks for your clarification, @sfmskywalker. Seems like the dependency on Automapper is loosely coupled in your codebase. In my case, my codebase has a dependency on the static Automapper, (which is obviously not good).

Currently, I am configuring the Automapper in a lock statement for every test fixture. However, the deadlocks still happen from time to time.

**Comment by sfmskywalker** [comment]
Correct @VinS101 , I basically inject `IMapper` via constructors of the classes that require mapping, and configured DI as follows:

```csharp
services
   .AddAutoMapper()
   .AddAutoMapperProfile<PaymentMappingProfile>()
```

The above two extension methods are my own implementations, as follows:

```csharp
using System;
using AutoMapper;
using Microsoft.Extensions.DependencyInjection;

namespace AutoMapper.Extensions.DependencyInjection
{
    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddAutoMapper(this IServiceCollection services, ServiceLifetime lifetime = ServiceLifetime.Singleton)
        {
            services.AddSingleton(CreateConfigurationProvider);
            services.Add(new ServiceDescriptor(typeof(IMapper), sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService), lifetime));

            return services;
        }

        public static IServiceCollection AddAutoMapperProfile<TProfile>(this IServiceCollection services)
            where TProfile : Profile
        {
            return services.AddTransient<Profile, TProfile>();
        }

        private static IConfigurationProvider CreateConfigurationProvider(IServiceProvider serviceProvider)
        {
            var profiles = serviceProvider.GetServices<Profile>();

            var configuration = new MapperConfiguration(x =>
            {
                foreach (var profile in profiles)
                {
                    x.AddProfile(profile);
                }
            });

            return configuration;
        }
    }
}
```

As you can see, this enables you to choose what lifetime scope you want to use for `IMapper`, be it `Singleton` or `Scoped`.
