### ISSUE TITLE
Mapper.AssertConfigurationIsValid<TProfile>()

### ISSUE THREAD

**Issue by magnusbakken** [AutoMapper/AutoMapper#482]
I like to have one unit test for each profile I've defined, so I use the overload of `Mapper.AssertConfigurationIsValid()` that takes a profile name. However, I'd rather have a type-safe reference to the profile than a string, since if I happen to have misspelled the profile name in the test, my test will always pass.

I would therefore suggest the addition of the following method to the `Mapper` class:

```
public static void AssertConfigurationIsValid<TProfile>()
    where TProfile : Profile, new()
{
    AssertConfigurationIsValid(new TProfile().ProfileName);
}
```

As far as I can tell that's all it would take.

**Comment by JackUkleja** [comment]
I seem to be having strange behaviour with this.

If I use:

        [Test]
        public void AssertConfigurationIsValid()
        {
            Mapper.AssertConfigurationIsValid<MyMappingProfile>();
        }

I get no exceptions even though I have purposely created a mapping profile that leaves some properties unmapped.

If I use: 

        [Test]
        public void AssertConfigurationIsValid()
        {
        var cfg = new MapperConfiguration(_cfg => { _cfg.AddProfile(new MyMappingProfile()); });
        cfg.AssertConfigurationIsValid();
        }

Then I do see the correct mapping exceptions. So to me it looks like `Mapper.AssertConfigurationIsValid<TProfile>()` is broken in 4.2.1

**Comment by lbargaoanu** [comment]
@JackUkleja Try the MyGet build and if it's the same, please make a gist with your example.

**Comment by jbogard** [comment]
Or the 5.0 beta, all this stuff was changed underneath the covers. If it's still a problem, create a new issue if you could!
