### ISSUE TITLE
Project.To is Loading Navigaton Properties

### ISSUE THREAD

**Issue by damooooooooooh** [AutoMapper/AutoMapper#486]
I have navigation properties mapped as sub collections in my mapping configuration.  However, even though I have not issued a LINQ include on my expression to retreive the domain objects, Automapper seems to load them anyway.  This is inefficient and I though Automapper should only map properties presented by the underlying iqueryable.

**Comment by VesperDev** [comment]
Thanks @diehardguy for you example.
