### ISSUE TITLE
String to Guid

### ISSUE THREAD

**Issue by kavengagne** [AutoMapper/AutoMapper#523]
Hi,

Yesterday, we faced a weird problem with AutoMapper 3.2.1.
We have a database which contains some Guid values.
When reading those with entity framework, it maps to a string in the entity model.
When using AutoMapper to map to an object that contains a property with the same name but of type Guid, we have different behavior.

On win 7, .net 4.5, It works out of the box without creating a mapping from String --> Guid explicitely.

On Windows 2008 R2, .Net 4.5.1, it does not work and yield a missing type map error.

If i define a mapping with convertusing to create the guid using the string value, it works.

We planned on installing .NET 4.5 on the 2008 box to see if the problem goes away.

Any help or advice would be appreciated.

Thank you,

**Comment by abargstaedt** [comment]
Had the same problem and ConvertUsing helped me out. Thx @kavengagne
