### ISSUE TITLE
Expose TypeMap in MappingExpression

### ISSUE THREAD

**Issue by softlion** [AutoMapper/AutoMapper#531]
In AutoMapper source you will find this:

```
public class MappingExpression : IMappingExpression, IMemberConfigurationExpression
    {
        private readonly TypeMap _typeMap;
```

There are some useful extension methods on stackoverflow, like InheritMappingFromBaseDestinationType or IgnoreAllNonExisting, which receives an IMappingExpression argument, but can not get its current TypeMap, and have to search for it using an inefficient seach algorithm, like FindTypeMapFor.

**Comment by jekcom** [comment]
This property is gone again in 5.0

**Comment by jbogard** [comment]
And will never, ever return.

**Comment by leadensky** [comment]
Can you recommend an alternative then, if TypeMap is gone forever?

**Comment by jbogard** [comment]
@leadensky don't use IgnoreNonAllExisting, that was a hack. Instead, use `CreateMap<FooDto, Foo>(MemberList.Source);` or use `CreateMap<Foo, FooDto>().ReverseMap();`

**Comment by leadensky** [comment]
Thanks for the quick response @jbogard. For reference, I wound up doing the following:

`CreateMap<Calculation, CalculationChecklist>(MemberList.Source)
                .ForMember(x => x.ProjectName, opts => opts.MapFrom(src => src.Project.ShortDescription))
                .ForMember(x => x.ProjectNumber, opts => opts.MapFrom(src => src.Project.ProjectNumber))
                .ForMember(x => x.ClientName, opts => opts.MapFrom(src => src.Project.Client.Name))
                .ForSourceMember(x => x.Specification, opts => opts.Ignore())
                .ForSourceMember(x => x.Specification_ID, opts => opts.Ignore());`

explicitly ignoring each of the source members I didn't want to map. Would love to know if there's an easier way.

**Comment by jbogard** [comment]
An easier way to do what? You WANT to explicitly ignore. You can also decorate those members with the IgnoreAttribute.

**Comment by leadensky** [comment]
OK, it just felt painful having to add in all the explicit Ignore statements after having used the IgnoreAllNonExisting hack. Thanks for the IgnoreAttribute suggestion. I'll consider that for future use.

**Comment by jbogard** [comment]
The reason you want to be explicit is that leaving it implicit with IgnoreAllNonExisting means you'll miss when something is renamed.

Another thought though, if you do ReverseMap, I would think you could even skip configuration validation for those maps.

**Comment by jbogard** [comment]
Or if we had MemberList.Source/MemberList.Destination/MemberList.None
