### ISSUE TITLE
Ignoring All Non Existing

### ISSUE THREAD

**Issue by loudsteve** [AutoMapper/AutoMapper#540]
how can i IgnoreAllNonExisting when i have something like this Mapper.CreateMap(type1, type2);

i have large database so i made a convention to add all the model to convert to json

**Comment by myingxue** [comment]
so far we can't use IgnoreAllNonExisting and CreateNestedMappers extension function in the same time.

**Comment by jbogard** [comment]
Why not?

**Comment by myingxue** [comment]
because Mapper.CreateMap<TFrom, TTo>() got overwrote to become Mapper.CreateMap(tFrom, tTo).

**Comment by lbargaoanu** [comment]
[This can be closed.](https://github.com/AutoMapper/AutoMapper/blob/167f3fe690e18945f2d75ba957247ba3d74c15bf/src/UnitTests/IMappingExpression/NonGenericReverseMapping.cs#L134)
