### ISSUE TITLE
Related to issue #91, Source has no property named Type, Target does have property name Type

### ISSUE THREAD

**Issue by greyalien007** [AutoMapper/AutoMapper#542]
If your source object does not have a property named "Type" but your target does have a property named "Type" TypeMap.GetUnmappedPropertyNames does not return this as unmapped which can cause weirdness.  If your target Type property happens to be of string type you end up with the Type.ToString() (guess) filling the property during mapping.  If it's not a string and there's no valid conversion, it blows up.  I added the following code to my project to avoid the issue, it may add clarity if this paragraph doesn't make sense.

            if (sourceType.GetProperty("Type") == null && destinationType.GetProperty("Type") != null)
            {
                expression.ForMember("Type", opt => opt.Ignore());
            }

This is not blocking me, no rush.

**Comment by jbogard** [comment]
Fixed!
