### ISSUE TITLE
Debug Symbols

### ISSUE THREAD

**Issue by bartsipes** [AutoMapper/AutoMapper#544]
Please include debug symbols (.pdb) with each GitHub release so if a problem is found we can more easily debug the issue.

**Comment by zakyvr** [comment]
Is it possible to update SymbolSource.org? It does not seem to have anything newer than 4.0.4.

**Comment by jbogard** [comment]
SymbolSource keeps rejecting my NuGet package.

**Comment by mkoutroupis** [comment]
Any updates regarding the symbol files?

**Comment by jbogard** [comment]
So project.json won't do it so symbols are on the symbol server.

**Comment by aplocher** [comment]
No 5.0.2 up there yet?

**Comment by OzBob** [comment]
http://www.symbolsource.org/Public/Metadata/NuGet/Project/AutoMapper
highest Symbols are for 4.04

**Comment by Larswa** [comment]
Are there alternative locations where we can find the pdb's for 5.0.2?

**Comment by OzBob** [comment]
https://github.com/AutoMapper/AutoMapper/issues/1652
has links to 
https://ci.appveyor.com/project/jbogard/automapper/build/1204/artifacts

Presumambly download 
artifacts\AutoMapper.5.1.1.symbols.nupkg
to a local drive and add that drive as a new package source in Visual Studio, higher than nuget.
Then, install-package automapper -v 5.1.1
