### ISSUE TITLE
Avoid assembly probing

### ISSUE THREAD

**Issue by guillaume-fr** [AutoMapper/AutoMapper#546]
Each time we start our application, Automapper probes for platform specific assemblies using PlatformAdapter.KnownPlatformNames.
I'd like to improve startup time. We could for instance call a setup method on the platform's assembly that clears KnownPlatformNames on the portable assembly or having a different version of the portable assembly in the package for each platform containing only the current Platform (compiled using preconditions or something like that...).

Let me know what you think about that and if you'd like me to contribute.

**Comment by lbargaoanu** [comment]
@jbogard This seems solved now.

**Comment by jbogard** [comment]
This is solved by having just one assembly now
