### ISSUE TITLE
Behaviour changed in 3.2.1, DestinationValue not null when no Destination object passed

### ISSUE THREAD

**Issue by wwwlicious** [AutoMapper/AutoMapper#557]
The following ValueResolver worked in 3.1.1 but does not in 3.2.1.

Below is the code and our tests, they both used to pass, now only the second one passes. 

The Context.DestinationValue in the resolver used to be null when no destination object was supplied to the mapping, now it is not null and defaulting to the int type default of 0.

the value resolver 

    public class IgnoreExistingValueResolver : IValueResolver
    {
        public ResolutionResult Resolve(ResolutionResult source)
        {
            // no previous object passed in, we should map
            if (source.Context.DestinationValue != null)
            {
                source.ShouldIgnore = true;
            }
            return source;
        }
    }

sample map

    Mapper.CreateMap<TestSource, TestDestination>().ForMember(
                dest => dest.Id, opt => opt.ResolveUsing<IgnoreExistingValueResolver>().FromMember(src => src.Id));

The tests

        [Fact]
        public void CanMapInsertType()
        {
            var source = new TestSource { Id = 1 };
            var insert = Mapper.Map<TestSource, TestDestination>(source);

            Assert.NotNull(insert);
            Assert.Equal(1, insert.Id);
        }

        [Fact]
        public void CanMapUpdateType()
        {
            var source = new TestSource { Id = 2 };
            var update = new TestDestination { Id = 1 };

            Mapper.Map(source, update);

            Assert.Equal(1, update.Id);
        }

**Comment by lbargaoanu** [comment]
@jbogard Initially the ResolutionContext was immutable and the previous values could be found by chaining through Parent. Now this is no longer true because DestinationValue can be changed and the old value lost. So perhaps keep the original design and make a new context with the new value for DestinationValue or, more of a hack, keep just the initial destination value in another property.

**Comment by jbogard** [comment]
Yep, this was a regression introduced. Gonna roll back the previous dude until I figure out a better way.

**Comment by lbargaoanu** [comment]
One problem with the immutable ResolutionContext is the lack of a Copy method to be used by all those constructors. Or anyway, some other way to make it easy to change just one field. Because otherwise the temptation is to simply make the field mutable.
