### ISSUE TITLE
Guidance on configuration is fractured

### ISSUE THREAD

**Issue by breyed** [AutoMapper/AutoMapper#565]
The various tidbits of documentation regarding configuration leave a muddled message of the best practice that developers should follow.

----

The [Getting Started Guide](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started) only mentions the static `Mapper` method and shows this example:

    Mapper.CreateMap<Order, OrderDto>();

The guide doesn't mention `Mapper.Initialize`; however, the summary for that method says it is "the preferred means to configure AutoMapper."

----

The [Configuration](https://github.com/AutoMapper/AutoMapper/wiki/Configuration) shows this code in the `OrganizationProfile` sample:

    protected override void Configure() 
    {
      //Put your Mapper.CreateMap... Etc.. here
    }

However, the summary for `Profile.Configure` says, "Avoid calling the AutoMapper.Mapper class from this method." So the comment to call `Mapper.CreateMap` in `Configure` looks like bad advice.

----

What is really needed is an API and documentation that is both easy and optimized at the same time. And of course it should be consistent. Hopefully the API is already sufficient; if not, consider adding the necessary shortcuts to make the simple, common case easy but still optimized

For example, consider an `Initialize` overload that takes an unnamed `Profile` directly, so that the quick-start sample code can be like the following, with the result being an AutoMapper configuration that is validated and sealed automatically.

>Call this method when your project starts up.

    Mapper.Initialize(new AppAutoMapperProfile);

>`Initialize` references a profile that you define like this:

    class AppAutoMapperProfile : Profile
    {
        protected override void Configure() 
        {
            CreateMap<Order, OrderDto>();
        }
    }

**Comment by jbogard** [comment]
Done!
