### ISSUE TITLE
Previously preserved destination value with UseDestinationValue() now overwritten.

### ISSUE THREAD

**Issue by bcanzanella** [AutoMapper/AutoMapper#568]
After upgrading from v3.0.0 to v3.2.1 the following example test returns a null 'Nested' object even though opt.UseDestinationValue() is specified. Is this a bug or as designed? Any ideas on a work-around?

    [TestFixture]
    public class AutomapperDestinationIssueTest
    {
        [Test]
        public void Nested_object_should_not_be_null_Test()
        {
            Mapper.CreateMap<Source, Destination>().ForMember(dest => dest.Nested, opt => opt.UseDestinationValue());
            var source = new Source() {Id = 123};
            var destination = new Destination() {Nested = new Nested() {Value = "not null!"}};
            var result = Mapper.Map(source, destination);
            Assert.IsNotNull(result.Nested);
        }
    }

    public class Nested
    {
        public string Value { get; set; }

    }
    public class Source
    {
        public int Id { get; set; }
        public Nested Nested { get; set; }
    }

    public class Destination
    {
        public int Id { get; set; }
        public Nested Nested { get; set; }
    }

**Comment by Laban1** [comment]
@jbogard We are having the same issue.  I tried 3.3.0, 3.2.0, 4.0.0-ci1007 to no avail.  Had to downgrade to 3.0.0.  Is there an ETA for a fix?

**Comment by lbargaoanu** [comment]
@jbogard UseDestinationValue is true by default. This causes reasonable fixes to break a lot of tests. One strategy would be to make it false by default and try to solve the remaining cases. Or I'm just missing something :)

**Comment by jbogard** [comment]
Ohhh yeah this one is a little weird. Gonna have to use the workaround. God I hate mapping to existing objects.
