### ISSUE TITLE
AutoMapperMappingException.Message can throw Exception

### ISSUE THREAD

**Issue by wilbit** [AutoMapper/AutoMapper#573]
Implicit call Context.SourceValue.ToString() can throw an exception.
If it occurs, the call to Message throws an exception that unexpectedly when reading the error message. I had such a situation with a third-party library.

See: https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/AutoMapperMappingException.cs#L69

**Comment by lbargaoanu** [comment]
I guess this is solved [now] (https://github.com/AutoMapper/AutoMapper/blob/88edc99e42d53e0f0f1ba269eb6a9f32520066fc/src/AutoMapper/AutoMapperMappingException.cs#L71).

**Comment by wilbit** [comment]
I'll test it again tomorrow.

**Comment by wilbit** [comment]
I tried to test today, but develop branch wants Win8.1 & C# 6.0 and I use Win7 & VS 2013.
I'm afraid, test will take more time =(

**Comment by lbargaoanu** [comment]
Yes, C# 6.0 is required, but Win 8.1 no. Just ignore the projects that don't build or cannot load. I use Win7 myself and I can build AutoMapper.Net4 in VS 2015.

**Comment by wilbit** [comment]
OK, I understood. But I wait VS 2015 release on July 20th before I install it. ;)

**Comment by lbargaoanu** [comment]
:thumbsup:

**Comment by jbogard** [comment]
Looks good from here!
