### ISSUE TITLE
Missing Include (and others helper methods) in non-generic IMappingExpression interface

### ISSUE THREAD

**Issue by dario-l** [AutoMapper/AutoMapper#575]
In my current project mappings via AutoMapper are done in the infrastructure. All mapped view models inherits from IMapFrom<T>, where T is source type. I don't need to create any line of code like CreateMap<>.

For scanning and auto-mapping I use StructureMap and non-generic AutoMapper.CreateMap().

Everything works fine but only for simple types. Unfortunately complex types with inheritance requires **including** derived types but non-generic IMappingExpression returned from CreateMap doesn't provide such a method.

**Comment by josh-compeat** [comment]
Would be nice to have these, especially include. Can just do run-time checking of subclasses to replace the generic constraints of the IMappingExpression<TSource, TDestination> versions.

**Comment by lbargaoanu** [comment]
@jbogard I think this would require some refactoring for the generic and non-generic MappingExpression. In cases like this usually the generic version uses the non-generic implementation. I don't know if it has been tried before and didn't work out.

**Comment by jbogard** [comment]
I think I could do that, but the interfaces couldn't inherit so I don't
think that would solve the problem?

**Comment by lbargaoanu** [comment]
Well, no, they would have equivalent methods. But a shared implementation would make it easier to implement both interfaces.

**Comment by jbogard** [comment]
I started the refactoring here but would take a bit longer, gonna push this off for the next dot release.

**Comment by lbargaoanu** [comment]
@jbogard This can be closed.
