### ISSUE TITLE
Support public readonly fields

### ISSUE THREAD

**Issue by togakangaroo** [AutoMapper/AutoMapper#592]
[As cited in this SO question](http://stackoverflow.com/questions/19681768/automapper-ignore-readonly-properties)

I have the following class

	public class SlideEvaluationInput
	{
		public readonly string Identifier;
		public IDictionary<string, object> AdditionalInfo = new Dictionary<string, object>();
                ..
		public SlideEvaluationInput() : this(Guid.NewGuid().ToString()) { }
		public SlideEvaluationInput(string identifier) { Identifier = identifier; }
	}

with a map

       Mapper.CreateMap<SlideEvaluationInput, SlideEvaluationInput>()
				.ConstructUsing(old => new SlideEvaluationInput(old.Identifier))
				.ForMember(x => x.AdditionalInfo, x => x.MapFrom(inpt => inpt.AdditionalInfo.Clone()));

This produces an error. Is there a reason why public readonly fields are not supported or is an oversite that is just waiting for a PR?

**Comment by lbargaoanu** [comment]
#766 might help with this. And also #785.

**Comment by jbogard** [comment]
Yep.
