### ISSUE TITLE
FR: ForAllOtherMembers

### ISSUE THREAD

**Issue by codegecko** [AutoMapper/AutoMapper#602]
ForAllOtherMembers is a useful feature to enable mapping of defaults (such as prop => prop.Ignore()) for remaining properties on a type where you have already called ForMember and don't want the resultant mapping overwritten.
PR following shortly.

**Comment by jbogard** [comment]
PR?

**Comment by jdacorr** [comment]
hi @jbogard, I also think the ForAllOtherMembers is a good and useful feature. Is it in your plans for the next release? Or it is something that you are not planing to integrate?

**Comment by jbogard** [comment]
@jdacorr I'm waiting for a PR from anyone that wants this feature.

**Comment by lbargaoanu** [comment]
What's wrong with #1049? :)
