### ISSUE TITLE
Threading Issue when CreateMissingTypeMaps option is true

### ISSUE THREAD

**Issue by adeel41** [AutoMapper/AutoMapper#620]
Hi,
Just spotted an issue in automapper. When you are mapping and also specified CreateMissionTypeMaps = true then sometimes it causes an issue and throws AutoMapperMappingException. I am posting the source code as well so that you can replicate the issue on your machine. since this is a threading issue so it happens sometimes so you need to execute the code few times in order to see the error message. FYI  I installed AutoMapper v3.2.1 from package manager console.

```

using System;
using System.Threading;

namespace AutoMapperDynamicMappingIssue
{
	public class UserViewModel
	{
		public string EmailAddress { get; set; }

		public string LastName { get; set; }

		public string FirstName { get; set; }

		public int Id { get; set; }

		public UserViewModel()
		{
			Id = 1;
			FirstName = "Dummy";
			LastName = "User";
			EmailAddress = "dummy.user@testing.co.uk";
		}
	}

	public class UserDto
	{
		public string EmailAddress { get; set; }

		public string LastName { get; set; }

		public string FirstName { get; set; }

		public int Id { get; set; }
	}


	internal class Program
	{
		private static void Main( string[] args )
		{
			var startTime = DateTime.Now;
			var endTime = startTime.AddSeconds( 2 );

			while ( endTime.Ticks > DateTime.Now.Ticks )
			{
				for ( var i = 0; i < 200; i++ )
				{
					//Works fine
					//AutoMapper.Mapper.Map<UserViewModel, UserDto>( new UserViewModel(), opt => opt.CreateMissingTypeMaps = true );


					// Threading issue.
					new Thread( () => AutoMapper.Mapper.Map<UserViewModel, UserDto>( new UserViewModel(), opt => opt.CreateMissingTypeMaps = true ) ).Start();
				}
			}

			Console.WriteLine( "Enter anything to quit" );
			Console.Read();
		}
	}
}

```

**Comment by lbargaoanu** [comment]
On my machine it complains with a NullReferenceException [here](https://github.com/AutoMapper/AutoMapper/blob/587ce3fc38d6319f1d9050d5b73b7fd7e0fc6bd8/src/AutoMapper/Mappers/TypeMapMapper.cs#L17). This is related to #781. In that branch it works. The cache needs updating when we create the new map.

**Comment by jbogard** [comment]
Yep works for me now.
