### ISSUE TITLE
DynamicMap doesn't map arrays

### ISSUE THREAD

**Issue by macpak** [AutoMapper/AutoMapper#628]
Hi,

The test below doesn't pass. I think it should.

                [Test]
               public void  GivenArrayOfFoo_WhenMappingToArrayofBar_ShouldGetTheSameNumberOfItemsInArray()
               {
                               var arrayOfFoo = new[] {new Foo() {Name = "aaa"}};
                               var arrayOfBar = Mapper.DynamicMap<Bar[]>(arrayOfFoo);

                               Assert.AreEqual(arrayOfFoo.Length, arrayOfBar.Length);
               }

                public class Foo
                {
                                public string Name { get; set; }
                }

                public class Bar
                {
                                public string Name { get; set; }
                }

**Comment by jbogard** [comment]
Fixed!
