### ISSUE TITLE
Mapping an array which is null becomes an empty array

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#63]
<b>boswald[CodePlex]</b><br />Hey Guys,<br /><br />I am mapping an array in a class. In my source class it is null but when it gets mapped it becomes an array of 0 size.<br /><br />I have tried the &#58;<br /><br />            Mapper.Initialize&#40;c &#61;&#62;<br />            &#123;<br />                c.AllowNullDestinationValues &#61; true&#59;<br />            &#125;&#41;&#59;<br /><br />option but this does not keep the array as a null value and instead creates the array of empty size.<br /><br />Is there a way I can get the array to stay null&#63; or is this a bug&#63;

**Comment by tpatel11** [comment]
Replying pretty late but these two works fine.

```
                        cfg.AllowNullCollections = true;
                        cfg.AllowNullDestinationValues = true;
```

**Comment by smiles2424** [comment]
your comment helped me so its never too late!

**Comment by doktrova** [comment]
I agree that there is a strong case for null collections. If you are trying to do a Patch (update a few members of  a model) you can ignore everything that is left null on the request and update only fields that were provided.
