### ISSUE TITLE
IQueryable extentions. Project Method

### ISSUE THREAD

**Issue by VVildVVolf** [AutoMapper/AutoMapper#630]
Hello, the AutoMapper has
```
public static IProjectionExpression Project<TSource>(this IQueryable<TSource> source);
```
Do you plan to develop Project<TSource>(this IQueryable source) version?
thanx

**Comment by satfx** [comment]
You can find the solution here https://github.com/AutoMapper/AutoMapper/issues/561, but Jimmy ignored it.

**Comment by jbogard** [comment]
@satfx Not ignored, ruminating :)

**Comment by satfx** [comment]
Jimmy, I don't think that one reflection-call per AppDomain (in FindQueryableSelectMethod method) ruins AutoMapper's performance  :) Moreover, hazzik's suggestion of "static reflection" is a little bit faster than mine.
