### ISSUE TITLE
Nested Project().To<T>(null, params string[] membersToExpand). How to?

### ISSUE THREAD

**Issue by Schlurcher** [AutoMapper/AutoMapper#646]
Given the following class hierarchy and ExplicitInclude() enabled on each navigation property.
```
Root {
  Nested
  Stuff
}

Nested {
  Stuff
}
```
calling `source.Project().To<Root>(null, "Nested.Stuff")` will not properly expand the nav property `Root.Nested.Stuff`. Curiosly calling `To<Entity>(null, "Nested", "Stuff")` will do so, but will also expand `Root.Stuff`, which is not always desirable. 

I searched the interwebs for a good while on how to use Project().To() and ExplicitInclude() , but since 3.3 is pretty new there is hardly any information to be found. :(

Am I doing something wrong, is this by design or did I stumble upon a bug?

**Comment by jbogard** [comment]
Fixed!
