### ISSUE TITLE
Win8.1 Store app inherit from Automapper.Profile generates warning CS1684

### ISSUE THREAD

**Issue by AndyDBell** [AutoMapper/AutoMapper#658]
Hi,

I am building a Win8.1 Store app and have generated a custom profile class by inheriting from the **Automapper.Profile** class.

Compiling the app generates three instances of this warning message:
*.\packages\AutoMapper.3.3.0\lib\windows8\AutoMapper.dll : warning CS1684: Reference to type 'System.Reflection.BindingFlags' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1\mscorlib.dll', but it could not be found.*

I am also employing **Code Contracts** in my app and this problem further results in a **ccrewrite error**  *Rewrite aborted due to metadata errors.*

Is it possible to fix this problem in the Win8.1 Automapper implementation or should I simply remove my dependency on Automapper.Profile.

**Comment by jbogard** [comment]
Well that's really bizarre, I don't get any compile errors when targeting Win 8.1 on my side. The PCL is supposed to just take care of all this. I'm going to confirm on my side.

**Comment by AndyDBell** [comment]
Hi Jimmy,

Were you able to re-produce this problem?

The following will generate the CS1684 warnings in VisualStudio 2013.

Create a new project *Visual C#->Store Apps->Windows Apps->Blank App*

Package Manager Console> *install-package AutoMapper*   (version="3.3.0")

Add a class sub-classed from AutoMapper.Profile
`public class MyAutoMapperProfile : AutoMapper.Profile{   }`

Build the project. 

In the *Build Output* I get 6 instances of warning CS1684

*e:\Visual Studio\Projects\AutoMapperIssue\packages\AutoMapper.3.3.0\lib\windows8\AutoMapper.dll : warning CS1684: Reference to type 'System.Reflection.BindingFlags' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1\mscorlib.dll', but it could not be found*

FYI my environment is:
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51641

Regards Andy

**Comment by nelsonghezzi** [comment]
I'm also receiving this kind of warnings. In my case I've two different warnings:

*Reference to type 'System.Reflection.BindingFlags' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhoneApp\v8.1\mscorlib.dll', but it could not be found*

*Reference to type 'System.Reflection.BindingFlags' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1\mscorlib.dll', but it could not be found*

The compiler emits six instances of each warning, but I suppose it's somehow related to the number of projects in which Automapper is installed/referenced (currently it's installed in four projects).

I can confirm that removing the class that inherits from *Automapper.Profile* causes the warnings to disappear.

The solution consists of an Universal App project and a set of PCL projects that targets Windows 8.1 and Windows Phone 8.1.

I also have the Code Contracts extension installed in Visual Studio, but currently not in use in any project of the aforementioned solution.

Environment:
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version **4.5.51650**

Regards.

**Comment by jbogard** [comment]
I found the issue, will be pushing out a hotfix soon. Has to do with BindingFlags not being actually available. Sigh.
