### ISSUE TITLE
AssertConfigurationIsValid collect all errors rather than throw first one

### ISSUE THREAD

**Issue by hazzik** [AutoMapper/AutoMapper#660]
It would be useful to see all mapping validation errors at one go http://martinfowler.com/articles/replaceThrowWithNotification.html

**Comment by hazzik** [comment]
In DryRun

**Comment by jbogard** [comment]
So currently I do a two step operation - first find unmapped members, then find unmapped types. This is to do both in one go?

**Comment by hazzik** [comment]
Not in one go, but in one exception. Currently if you have unmapped types, AM will throw one exception for each unmapped type usage.

Consider following situation
```csharp
class A {} 
class B {} // A => B is NOT mapped
class Source 
{
    public A P1 {get; set;}
    public A P2 {get; set;}
    public A P3 {get; set;}
}
class Dest
{
    public B P1 {get; set;}
    public B P2 {get; set;}
    public B P3 {get; set;}
}
```
So the sequence of events would be like this:

1. AM throws that Source.P1 => Dest.P1 using unmapped A => B
2. Fix by doing something about this, but do not map A=>B & Recompile & Run
3. Repeat for next unmapped class
