### ISSUE TITLE
Issue when trying to run with Microsoft.Owin.Testing

### ISSUE THREAD

**Issue by gep13** [AutoMapper/AutoMapper#662]
I have recently started using AutoMapper, in conjunction with AutoFac and WebAPI.

I have a situation where in my AutoMapper Profile, I want to use a Custom Type Resolver, I have set this up as follows:

```
    public class DateTimeConverter : ITypeConverter<DateTime, string>
    {
        private IApplicationSettingService applicationSettingService;
        private string reportDateTimeFormat = "dd-MMM-yyyy";

        public DateTimeConverter(IApplicationSettingService applicationSettingService)
        {
            this.applicationSettingService = applicationSettingService;

            var applicationSettingsResponse = this.applicationSettingService.GetApplicationSettings();
            if (applicationSettingsResponse.Result != null)
            {
                this.reportDateTimeFormat = applicationSettingsResponse.Result.DateTimeFormatString;
            }
        }

        public string Convert(ResolutionContext context)
        {
            return context.IsSourceValueNull ? string.Empty : ((DateTime)context.SourceValue).ToString(this.reportDateTimeFormat);
        }
    }
```

As you can see, I am taking a dependency on IApplicationSettingsService.  In order to get this to work, I used a suggestion which was spelled out here:

http://stackoverflow.com/questions/18732448/having-automapper-use-services-constructed-by-a-autofac-with-webapi

i.e. to make use of the ConstructServiceUsing in order to get access to the Type, and resolve it's dependencies.  The AutoFac definition for it is:

```
containerBuilder.RegisterType<DateTimeConverter>().AsSelf().InstancePerApiRequest();
```

This all works great when I run the application through IIS Express.

However, when I try to run my Integration Tests, which is using an in-memory Owin TestServer, HttpContext.Current is coming back as null, which means that the Mapping is not set up.

@jbogard are you able to make any suggestions as to how to move past this.  Am I doing something completely off on a tangent?

Thanks!

**Comment by jbogard** [comment]
I updated the SO question with a couple of options:

1) use the mapping options to specify a service ctor per Map call

2) use DI to inject an IMappingEngine, which takes a `Func<Type, object>` ctor parameter
