### ISSUE TITLE
exclude viewmodel property in projection

### ISSUE THREAD

**Issue by banibal** [AutoMapper/AutoMapper#663]
Hi,

I have a property in my viewmodel that i use in grid to represent some text. The text is set depending on boolean value that comes from the database. the text property that iam using in the grid is not in the database.  when i try to Project.To() it includes that property and i get the error: " The specified type member 'PropertyName' is not supported in LINQ to Entities."
i have tried ignore the property in the CreateMap but thats not working. how can i exclude properties that are not present in the database?

**Comment by jbogard** [comment]
What do your source/destination types look like?
