### ISSUE TITLE
Error while building web application and class library using msbuild 

### ISSUE THREAD

**Issue by qetza** [AutoMapper/AutoMapper#667]
Hi,
When you have a web application project and a class library both having a reference to AutoMapper and the web application references the class library, when building with msbuild (command line) and redirecting the output directory you get the following error:
"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplication.targets(194,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items. C:\Sources\Local\WebApplication2\WebApplication2\WebApplication2.csproj]"

Here's the command line used:
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe /nologo "C:\Sources\Local\WebApplication2\WebApplication2.sln" /m:1 /clp:"verbosity=minimal" /fl /flp:"logfile=C:\Temp\build\WebApplication2.log;encoding=Unicode;verbosity=diag" /p:SkipInvalidConfigurations=true /p:VisualStudioVersion=12.0 /p:OutDir="C:\Temp\build\Binaries\WebApplication2\\" /p:Configuration="Release" /p:Platform="Any CPU" /t:Rebuild"

This seems to be due to the AutoMapper.targets file because when commenting the <ItemGroup> it works.

**Comment by jbogard** [comment]
What version of AutoMapper is this?

**Comment by qetza** [comment]
This is happening with version 3.2.1 and 3.3.0

**Comment by holwerda** [comment]
This sounds very similar to the issue I have - #666 .  It is using MSBuild in TFS.

**Comment by jbogard** [comment]
Looks similar, @qetza from File-New Project, can you go through repro steps?

**Comment by qetza** [comment]
Sure:
- File, New Project, Class Library 'ClassLibray1'
- Add NuGet package AutoMapper to 'ClassLibrary1'
- Add New Project to solution, ASP.NET MVC 'MvcApplication1'
- Add NuGet package AutoMapper to 'MvcApplication1'
- Add reference to 'ClassLibrary1' on 'MvcApplication1'
- Compile under VS => OK

Open command prompt and compile using msbuild.exe:
'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe /nologo "_path to .sln_" /m:1 /p:VisualStudioVersion=12.0 /p:OutDir="C:\Temp\build\" /p:Configuration="Release" /p:Platform="Any CPU" /t:Rebuild'

You should have the error. Note that as Chris is started having the issue with TFS build and after doing some investigation found what could be the source (OutDir redirection with 2 projects using AutoMapper)

Guillaume

**Comment by jbogard** [comment]
Can you try the 4.0 preview? I believe I have this fixed by eliminating everything but a single DLL.

**Comment by jbogard** [comment]
Fixed with the one assembly
