### ISSUE TITLE
Support AutoMapper on CoreCLR

### ISSUE THREAD

**Issue by yishaigalatzer** [AutoMapper/AutoMapper#668]
Would be very nice if we could use Auto Mapper on CoreCLR.
In the following sample we have to work around the fact that Auto Mapper is not available in CoreCLR, by doing some very basic replacement. 

https://github.com/aspnet/MusicStore/blob/557a2057a806e49c0e491d5a0083cb71bdcd3915/src/MusicStore.Spa/Infrastructure/SimpleMapper.cs

But we would like to change the sample do fully utilize AutoMapper for both the Desktop CLR and Core CLR.

**Comment by jbogard** [comment]
Do you have any documentation on how to do this? I have VS 2015 preview, and that checkbox to create a NuGet package for CoreCLR doesn't exist.

**Comment by yishaigalatzer** [comment]
What you want to do is build an ASP.NET class library, the nuget package will be created automatically. And for now you still have to unzip/rezip to combine the other targets you might have. We plan to come up with a better solution at some point.

Couple of notes:
At beta2 if the packages supports phone it will mostly work with coreCLR, but this is going to break very shortly after, so the method above is more in the right direction to go. We are going through a similar exercise with System.Net.Http.Formatting at the moment.

Although live bits are Beta2, we are locking down the beta3 branch, so it might be a good idea to start from there (https://github.com/aspnet/home). 

Let me know if we can help more in getting started (Fill free to reach out directly).

**Comment by jbogard** [comment]
I don't have the full build going, but I do have a build, and a package with aspnet50/aspnetcore50 support. You'll need to have this *exact* package:

http://www.nuget.org/packages/AutoMapper/4.0.0-ci1020
