### ISSUE TITLE
Does AutoMapper support conventions?

### ISSUE THREAD

**Issue by Sebazzz** [AutoMapper/AutoMapper#670]
In our domain model we may have a class like this:
```C#
class Question {
     // ...
     public virtual ICollection<QuestionLocalization> Localizations {get;set;}
     // ...
}
class QuestionLocalization {
    public string Text {get;set;}
}
```
And a DTO like this:
```C#
class Question {
   // ... 
   public string Text {get;set;}
```

And we map this using AutoMapper like:
```C#
.ForMember(d => d.Text, a => a.MapFrom(e => e.Localizations.First(loc => loc.Culture == CultureContext.CurrentCulture).Text)
```

Which works great!

Is there any way to plug in a convention in AutoMapper that allows automatic conversion like this to happen, while keeping the possibility to keep the Expression Tree like in this example?

**Comment by jbogard** [comment]
I wish it did. This is my big 4.0 push, to add conventions.

**Comment by Sebazzz** [comment]
Ah, right. I'd be happy to contribute if you need any help.

**Comment by jbogard** [comment]
Any more examples of what you'd like to do? That would help in figuring out what needs to be supported.

**Comment by Sebazzz** [comment]
Not entirely the same problem as this one, but something like this as well: Automapping many types to a default DTO. For example, for a drop down list, one might create a 'IdNameProjection' class:
```C#
public class IdNameProjection {
    public int Id {get;set;}
    public string Name {get;set;}
}
```
Sorry for the vague explanation, I hope it makes sense.

**Comment by TylerCarlson1** [comment]
@Sebazzz I submitted #983 with an example to make a convention that covers your example in using Localization info.
