### ISSUE TITLE
Problem With Entity Framework 6

### ISSUE THREAD

**Issue by Toso82** [AutoMapper/AutoMapper#673]
Sorry for the stupid question but i have a old code with automapper. This is work correct with the old version of Entity Framework. With the new version with DbContext I don't know how change code to work with Proxy Object. Can you help me?

**Comment by jbogard** [comment]
What problems are you having?

**Comment by Toso82** [comment]
This is my code:

List<Caratteristica> caratteristicheMCA = _db.Caratteristiche.Where(o => o.IdQualita == "00010"
                                                                                & o.IMUtilizzato == true
                                                                                & o.IMFormula.Length != 0).ToList();


            
Mapper.CreateMap<Caratteristica, CaratteristicheDTO>()
                .ForMember(dest => dest.UnitaMisuraIM, opt => opt.ResolveUsing(src => src.UnitaMisuraIM.Nome==null?src.UnitaMisuraIM.Nome:""))
                .ForMember(dest => dest.UnitaMisura, opt => opt.MapFrom(src => src.UnitaMisura.Nome))
                .ForMember(dest => dest.Nomenclatori, opt => opt.MapFrom(src => src.CaratteristicheNomenclatori));

            Mapper.CreateMap<CaratteristicaNomenclatore, CaratteristicaNomenclatoreDTO>()
                  .ForMember(dest => dest.Presentato, opt => opt.MapFrom(src => src.ValorePredefinito));

            List<CaratteristicheDTO> caratteristicheMCADTO = Mapper.Map<List<Caratteristica>, List<CaratteristicheDTO>>(caratteristicheMCA);


This is the Exception:

"\r\n\r\nMapping types:\r\nCaratteristica_1157B2AE0B4A0857F88CDD034373860977772124DE48997E52399E8BDC08BB09 -> String\r\nSystem.Data.Entity.DynamicProxies.Caratteristica_1157B2AE0B4A0857F88CDD034373860977772124DE48997E52399E8BDC08BB09 -> System.String\r\n\r\nDestination path:\r\nList`1[76].UnitaMisuraIM.UnitaMisuraIM\r\n\r\nSource 
value:\r\nSystem.Data.Entity.DynamicProxies.Caratteristica_1157B2AE0B4A0857F88CDD034373860977772124DE48997E52399E8BDC08BB09"}


I think that the problem is Proxy Poco Object

**Comment by jbogard** [comment]
Not seeing anything off the bat, I'm not sure why it things you're mapping an EF entity to a string though. One tiny thing - your "ResolveUsing" doesn't need to be a ResolveUsing, it can be MapFrom.

I also notice it's an issue with one item in your collection, the item at index 76. Is that data different somehow than others?

**Comment by Toso82** [comment]
Thanks I don't undestand why but change ResolveUsing with MapFrom now work.

**Comment by jbogard** [comment]
It depends on what you're doing inside ResolveUsing. ResolveUsing lets you use a Func or a resolver class. But how does EF know how to interpret some random Func or class and translate it into SQL?

It doesn't!

It CAN however interpret a C# Expression and translate that into SQL. ResolveUsing lets you do absolutely anything under the sun, call web services, make other DB calls, anything. MapFrom constrains you - you don't create `Func<TSource, TMember>', you create an `Expression<Func<TSource, TMember>>`.

I could go further, but really it's just LINQ that you'd need to read up on. AutoMapper plugs into LINQ, so you only get what's available in LINQ query providers.

Does that help? And, without seeing your resolver, I can't tell you if you're using something that's available or not.
