### ISSUE TITLE
after map action with nested objects

### ISSUE THREAD

**Issue by fastfasterfastest** [AutoMapper/AutoMapper#674]
Using AutoMapper 3.3.1

While mapping the outer object, and passing an after-map action, I expected the after-map action to be called when the mapping of the outer object had completed.  But, it seems like the after-map action is also called during/after the mapping of a nested inner object of the outer object.  And this results in an exception being thrown: InnerException {"Unable to cast object of type 'AutoMapperTest.Inner' to type 'AutoMapperTest.Outer'."}

Am I doing something wrong or misunderstanding how .AfterMap works?

Here is a distilled example showing what I am running into.  If I comment out the .AfterMap line, the mapping completes without any error.

```
namespace AutoMapperTest
{
    public class Inner
    {
        public string Prop1 { get; set; }
    }
    public class Outer
    {
        public Outer()
        {
            Inner = new Inner() { Prop1 = "Prop1" };
        }
        public Inner Inner { get; set; }
    };

    public class InnerDTO
    {
        public string Prop1 { get; set; }
    }
    public class OuterDTO
    {
        public InnerDTO Inner { get; set; }
    }


    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<Inner, InnerDTO>().ForMember(dst => dst.Prop1, opt => opt.Ignore());
            Mapper.CreateMap<Outer, OuterDTO>();
            Mapper.AssertConfigurationIsValid();

            var outer = new Outer();
            var outerDTO = Mapper.Map<Outer, OuterDTO>(outer, mappingOperationOptions =>
                {
                    //InnerException {"Unable to cast object of type 'AutoMapperTest.Inner' to type 'AutoMapperTest.Outer'."}
                    mappingOperationOptions.AfterMap((src, dst) => dst.Inner.Prop1 = "by AfterMap");
                });

            var x = outerDTO.Inner.Prop1;
        }
    }
}
```

**Comment by jbogard** [comment]
That is most definitely a bug! Tagging for 4.0.

**Comment by fastfasterfastest** [comment]
Thanks for confirming.
This bug, I guess, currently makes .AfterMap useless if the object you are mapping contains any sub-objects that are also mapped - useless in the sense that .AfterMap will throw.

To avoid this issue I think I will abandon using .AfterMap and instead pass a context/parameter to the mapping as described at https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization - that seems like a more attractive option, to be able to pass a parameter to the mapping operation, vs. doing post-map processing.  .Project().To<T>(...) requires  a Queryable and although my collection isn't a Queryable it can easlily be turned into one using AsQueryable().  I don't know if there are any other gotchas using this approach.
We don't have the ability to pass such a context/parameter to Mapper.Map(), do we?

**Comment by jbogard** [comment]
There's other parameterization for runtime mapping, it's in those options
you saw. You then get at the parameter values from a value resolver.

**Comment by jbogard** [comment]
Fixed.
