### ISSUE TITLE
AutoMapper Project().To<T> not support ResolveUsing

### ISSUE THREAD

**Issue by yuezhongxin** [AutoMapper/AutoMapper#675]
Hi, Test code:

```cssharp
public List<OrderLineDTO> GetLinesForOrder(int orderId)
{
    Mapper.CreateMap<OrderLine, OrderLineDTO>()
            .ForMember(dto => dto.Item, conf => conf.MapFrom(ol => ol.Item.Name)
            .ForMember(dto => dto.Name, opt => opt.ResolveUsing<NameCustomResolver>());

    using (var context = new orderEntities())
    {
        return context.OrderLines.Where(ol => ol.OrderId == orderId)
                .Project().To<OrderLineDTO>().ToList();
    }
}
public class NameCustomResolver : ValueResolver<OrderLine, string>
{
    protected override string ResolveCore(OrderLine source)
    {
        //to do...
        return source.Name;
    }
}
```

However, this is wrong, how can I fix it?

**Comment by jbogard** [comment]
You can't use custom resolvers for ProjectUsing, you need to use MapFrom or similar. Your EF provider can't interpret a custom resolver so you have to use one of the expression-based configurations.

https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions

**Comment by yuezhongxin** [comment]
When I use `Mapper.Map<,>`, custom resolvers for ProjectUsing is works.

> Your EF provider can't interpret a custom resolver

You mean EF provider does not support(Including the latest EF7)? now, I this is the way to replace `Project().To<T>`:

```cssharp
using (var context = new orderEntities())
{
	var query = from ol in context.OrderLines
				where ol.OrderId == orderId
				select new OrderLineDTO
				{
					///to do...you know(custom resolvers)
					Name = ol.Name
				};
	return await query.ToListAsync();
}
```

But the reality is more complicated than it would, if I had to use custom resolvers for ProjectUsing, how do I solve this problem better, or would like you said(similar)?

**Comment by jbogard** [comment]
I would try to keep with Project.To, but honestly, without seeing what your resolver actually does, I can't tell you if it could be supported with projections.

EF can only support things in Expressions, EF, and any LINQ provider. Personally, I try to stay with projections as looooooooooong as I can :)

**Comment by yuezhongxin** [comment]
@jbogard 

Sorry, the above code is just an example, and can not accurately express what.

In this [Supported mapping options](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#supported-mapping-options), I can get the answer, thank you very much for your answer.

Finally, I loooooooooooooove AutoMapper!!!

**Comment by jbogard** [comment]
Thanks!
