### ISSUE TITLE
Database column selected twice when using ProjectUsing on nullable DateTime

### ISSUE THREAD

**Issue by jamieide** [AutoMapper/AutoMapper#676]
I am mapping class Site

    public class Site {
        public int SiteId { get; set; }
        public DateTime? ConstructionStart { get; set: }
    }

to SiteViewModel

    public class SiteViewModel {
        public int SiteId { get; set; }
        public string ConstructionStart { get; set: }
    }

and I want the ConstructionStart property in SiteViewModel to be empty string instead of null using projections. By default the issued query is

    select SiteId, cast(ConstructionStart as nvarchar(50)) ...

If I add a global projection to convert nullable DateTime to empty string

    Mapper.CreateMap<DateTime?, string>()
                .ProjectUsing(x => x.HasValue ? x.Value.ToShortDateString() : string.Empty);

The ConstructionStart column is added to the select list twice

    select SiteId, ConstructionStart, ConstructionStart ...

This is using .NET 4.5 and NHibernate 3.3.3. It's not a big issue but I'm not sure if it's by design somehow, a bug, or an issue with NHibernate's LINQ interpreter. Ideally it would use coalesce but that's a lot to ask. Better yet, it would be great if there were a global AutoMapper option to always convert nulls to empty string.

**Comment by mwpowellhtx** [comment]
I'm assuming you've tried boxing x?

**Comment by jamieide** [comment]
Can you explain what you mean by that? I know what boxing is but I'm not sure how it would be applied here.

**Comment by mwpowellhtx** [comment]
You should look it up for yourself. Good luck.

**Comment by jbogard** [comment]
One way to try to diagnose this is to perform the projection manually. Use NH LINQ, but instead of AutoMapper doing the projection, write the Select part yourself. Then look to see what the SQL looks like. This is exactly what I do when I'm trying to figure out what expressions work and which don't with the underlying LINQ provider.

**Comment by mwpowellhtx** [comment]
Think it through. Think about what NH is doing with the domain model. It introduces a proxy class that can potentially trigger SQL upon *reference*. When you box the value, you have the value, not the proxy reference. You'd have to try it to know for sure.

**Comment by jbogard** [comment]
Projection skips all this, no domain model ever gets loaded. If you use Project.To(), you don't load any proxy objects, you feed a Select projection to the LINQ provider and NH/EF modifies the underlying SQL to load straight into the DTO.

**Comment by jamieide** [comment]
@mwpowellhtx I'm using Projections I'm not loading a domain model first. Anyway, this model isn't subclassed so NHibernate returns a concrete type not a proxy.

Jimmy, thanks for the answer and I should have thought to do that before creating an issue.

    var site = session.Query<Site>()
                    .Where(s => s.ConstructionStartDate == null)
                    .Select(s => new SiteDetailsViewModel()
                    {
                        SiteId = s.SiteId,
                        ConstructionStartDate = s.ConstructionStartDate.HasValue ? s.ConstructionStartDate.Value.ToShortDateString() : string.Empty
                    }).Take(1).Single();

                Assert.IsNotNull(site);
                Assert.AreEqual(string.Empty, site.ConstructionStartDate);

issues

    select TOP (1) site0_.SiteId            as col_0_0_,
                 site0_.ConstructionStart as col_1_0_,
                 site0_.ConstructionStart as col_2_0_
    from   Nucleus.Site site0_
    where  site0_.ConstructionStart is null

**Comment by jbogard** [comment]
No problem! I've had to do this countless times when I was building out the LINQ support, so it's kinda second nature to me.
