### ISSUE TITLE
ProjectUsing is not called.

### ISSUE THREAD

**Issue by RyanONeill1970** [AutoMapper/AutoMapper#677]
In the following unit test the expression inside ProjectUsing is never called (AlternateId is not set), this is the same when executed via Entity Framework. Should this work or is there something missing from my example?

    class MapFrom
    {
        public int Id { get; set; }
    }
    class MapTo
    {
        public int AlternateId { get; set; }
    }

    [TestMethod]
    public void Automapper_projectusing_test()
    {
        AutoMapper
            .Mapper
            .CreateMap<MapFrom, MapTo>()
            .ProjectUsing(src => new MapTo { AlternateId = 88 });
        var products = new List<MapFrom>();
        products.Add(new MapFrom());

        var mapped = products
            .AsQueryable()    // Just in case ProjectUsing only works with IQueryable.
            .Project()
            .To<MapTo>()
            .ToList();

        Assert.AreEqual(88, mapped.Single().AlternateId); // Fails, AlternateId equals 0.
    }

**Comment by jbogard** [comment]
This works as designed, you want ConstructUsing.
