### ISSUE TITLE
Expose TypeMap and PropertyMap in IMemberConfigurationExpression

### ISSUE THREAD

**Issue by strawd** [AutoMapper/AutoMapper#678]
Similar to issue #531, it would be useful to be able to extend property maps using extension methods on an IMemberConfigurationExpression. However this interface does not expose the underlying TypeMap and PropertyMap, nor even the TDestination type, so it is difficult to create such extensions.

Further it would be useful to have a general bag of properties that can be stored on a PropertyMap for custom extensions so that extra data doesn't have to be stored separately.

**Comment by jbogard** [comment]
So the most I can do right now (and exists in 5.0) is to expose the destination member and the list of property map actions. This is because the property map is not created until after all the config is gathered and executed.
