### ISSUE TITLE
AutoMapper Conditional mapping take too many seconds to map?

### ISSUE THREAD

**Issue by Mds92** [AutoMapper/AutoMapper#679]
I'm using AutoMapper for mapping in a MVC5 project.
I have a config as the following:

<pre>Mapper.CreateMap<Employee, EmployeeModel>()
.ForMember(destination => destination.ServiceNoString, opt =>
{
    opt.Condition(source => source.Service != null);
    opt.MapFrom(source => source.Service.Title);
});</pre>

`Service` is a Employee's Navigation Property
Whenever my code receive to the following code and `Service` navigation property is null, it take too much seconds around 120 seconds to map employee, without any exceptions. It seems to loop many times.

<pre>viewModel.Employee = Mapper.Map<Employee, EmployeeModel>(employee);</pre>
But if Service has a value everything is OK.
I removed ` opt.Condition(source => source.Service != null);` from mapper config for testing, but nothing changed.

What's wrong?

**Edit:**<br>
I changed the config as the following:
    <pre>Mapper.CreateMap<Employee, EmployeeModel>()
    	.ForMember(m => m.ServiceNoString, opt => opt.ResolveUsing<AutoMapperResolvers.EmployeeServiceResolver>())</pre>

Resolver:
    <pre>public class EmployeeServiceResolver : ValueResolver<Employee, string>
    {
    	protected override string ResolveCore(Employee source)
    	{
    		if (source.Service == null) return string.Empty;//loop around 200 times
    		return source.Service.Title;
    	}
    }</pre>

I found resolver calls around 200 times !!!! But I have just set one resolver for one property !

**Comment by jbogard** [comment]
Can you post your source/destination types?

**Comment by Mds92** [comment]
I could find the problem,
It's because of number of entity in another navigation property, around 2300 entity.
AutoMapper is OK.
Sorry for bothering.
