### ISSUE TITLE
Error when Deploying Release/ARM to device

### ISSUE THREAD

**Issue by curelom** [AutoMapper/AutoMapper#680]
When trying to deploy to a physical phone using options Device/Release/ARM, I get this error stating the MDILXapCompile failed with error code 2001

CrossGen failed
Error processing assembly C:\Source\Repos\ScriptureMemoryUniversal\ScriptureMemory\ScriptureMemory.WindowsPhone\obj\ARM\Release\MSIL\AutoMapper.dll
Raw error code: 2148733978

If I deploy in debug mode, it deploys correctly.

**Comment by jbogard** [comment]
What version of AutoMapper? And, what is your target platform, Windows Phone/iOS/Android?

**Comment by curelom** [comment]
Both 3.3.1 and 4.0.0-ci1032 on nuget.  Platform is windows phone 8.1

**Comment by curelom** [comment]
And this only happens with ARM deploying to an actual device.  If deploying to a x86 emulator, it works fine.

**Comment by jbogard** [comment]
Can you try the latest from MyGet? I've made sure I'm targeting "AnyCPU".

**Comment by avorobjovs** [comment]
Hi,
I have the same problem.

I have Visual Studio 2015 in Windows 10.
I have a Xamarin multiplatform project for Androd, iOS, WinPhone 8.1, and Windows 8.1.
And I have AutoMapper package of the latest 4.0.4 version in my PCL project.

But when I try to debug my project on the WinPhone device on ARM platform I get the same error:

CrossGen failed
Error processing assembly ...\obj\ARM\Debug\MSIL\AutoMapper.dll
Raw error code: 2148733978

How can I fix this problem? Can you help me?

Best Regards,
Aleksandrs

**Comment by lbryczek** [comment]
Hi Guys,
someone found a solution for this problem?
thx

**Comment by avorobjovs** [comment]
Now I just deploy my application with Windows Phone Application Deployment Tool
http://social.technet.microsoft.com/wiki/contents/articles/24119.windows-phone-8-1-app-deployment-how-to-deploy-appx-file-with-application-development-tool.aspx

But of course you cannot debug with this option. :(

**Comment by avorobjovs** [comment]
Hi all,

Please read this issue and the solution
https://github.com/AutoMapper/AutoMapper/issues/930

**Comment by jbogard** [comment]
Closing, we seem to have found a solution.
