### ISSUE TITLE
Map between non-generic and generic types

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#681]
One can create a map between two generic types (Model<> and Presenter<>).

What I'd like to have is that one of these classes is non-generic. So I have a single Model class, which can be mapped to a number of generic classes (e.g. Presenter<int> and Presenter<string>).

Could it be possible to adjust AutoMapper such that one could use a CreateMap(typeof(Model), typeof(Presenter<>))?

**Comment by jbogard** [comment]
Do you have a few types to show as an example?

**Comment by mc0re** [comment]
Classes:

	#region Model classes

	public class ModelClass
	{
		public int Number { get; set; }

		public int Value { get; set; }
	}


	public class GenericModelClass<T>
	{
		public int Number { get; set; }

		public T Value { get; set; }
	}

	#endregion


	#region Interface classes

	public class GenericInterfaceClass<T>
    {
	    public int Number { get; set; }

		public T Value { get; set; }
    }


	public class StringInterfaceClass : GenericInterfaceClass<string>
	{ }

	#endregion

**Comment by mc0re** [comment]
Desired mapping:

	Mapper.CreateMap<int, double>().ConvertUsing(Convert.ToDouble);
	Mapper.CreateMap<int, string>().ConvertUsing(Convert.ToString);

	Mapper.CreateMap(typeof(ModelClass), typeof(GenericInterfaceClass<>));

**Comment by jbogard** [comment]
Hmmm, that's a pretty weird situation. What's the real-world scenario you're working with here? I'm trying to imagine a codebase in which I would decide to do something like this.

**Comment by mc0re** [comment]
The real-world situation is as follows.

There is a model class, which should be accessible through REST interface. The class contains a number of fields, which are user-translatable (the user can change the translation for any language available in the system).

In some cases, the model shall be presented in a view-only way, thus only a "string" type is needed, which is populated with the current language.
In other cases, the model shall be editable, thus all languages must be present (and sent back), hence a Dictionary<language-code, string> is needed.
Therefore, there is a number of presentation classes, which differ only by this parameter (string / Dictionary). And a single model class.

**Comment by jbogard** [comment]
The workaround today is to create maps for each closed type, right?

**Comment by mc0re** [comment]
Right. But it's prettier to have them glued together :-)

**Comment by jbogard** [comment]
I think the way I might approach this is part of a larger effort to do some sort of scanning, similar to how IoC containers provide this capability. Otherwise, I'm not sure how I would explain this sort of feature if it were hard-coded.

**Comment by jbogard** [comment]
Or you can send me a pull request ;)

**Comment by mc0re** [comment]
"part of a larger effort to do some sort of scanning"

I'm not sure I follow you...

**Comment by jbogard** [comment]
Instead of mapping these on the fly, scanning assemblies/types for rules and building out the mapping configurations explicitly. You have those closed types already defined - the existing open generic mapping is about the situation where you *don't* have closed types defined in your app, only open ones.

**Comment by mc0re** [comment]
I can't claim I understood what you're saying, but you know better :-)
 
If this is about the implementation, one can check, whether a type given to Map(), is a specialization of a known generic type.
If this is about design, I am not with you.
 
Date: Fri, 27 Feb 2015 06:54:28 -0800
