### ISSUE TITLE
IncludeBase must come before base overrides

### ISSUE THREAD

**Issue by strawd** [AutoMapper/AutoMapper#683]
The documentation at https://github.com/AutoMapper/AutoMapper/wiki/Mapping-inheritance specifies that the precedence of resolving properties is:
*Explicit Mapping (using .MapFrom())
*Inherited Explicit Mapping
*Ignore Property Mapping
*Convention Mapping (Properties that are matched via convention)

In practice I have found that the order of the first two items above relies on the application declaring the IncludeBase before specifying explicit mappings in the inheritor type map. Either AutoMapper should be changed to make the order not matter or the documentation should be updated to include this requirement.

**Comment by jbogard** [comment]
Yeah....this is getting addressed in 4.0
