### ISSUE TITLE
[3.3.1] DelegateBasedResolver causes NullReferenceException on nested mapping of inner property, which is null

### ISSUE THREAD

**Issue by Deilan** [AutoMapper/AutoMapper#684]
Looks like a 3.3.1 specific issue because if I downgrade to 3.3.0 it does not reproduce. If I upgrade back to 3.3.1 from 3.3.0, it wil reproduce again.

Unfortunately I couldn't reproduce it outside of my project in a sample project with similar conditions. Probably it's some sort of an edge case, which does not reproduce generally.

Here is a context and some details about the issue:
1. It's a nested & flatenning mapping. So I have Outer and Inner classes. One of outer class's property "points" to an object of Inner class.
2. Mapping configuration looks like this:
AllowNullCollections = true;
CreateMap<Outer, OuterDto>()
.ForMember(dest => dest.Property, opt => opt.MapFrom(src => src.Inner.Property));
2. Exception occurs when the outer object's Inner property is null
3. Exception occurs in DelegateBasedResolver class on the line 22:
var result = _method((TSource) source.Value);

where 'source.Value' is an instance of Outer class.

I am ready to provide more details and artifacts if you tell me what exactly do you need and how may I extract required info.

![untitled](https://cloud.githubusercontent.com/assets/4777512/6467605/7b1f64b4-c1e0-11e4-839e-342c5168f61b.png)

**Comment by lbargaoanu** [comment]
I believe you are seeing a [first chance exception](http://blogs.msdn.com/b/davidklinems/archive/2005/07/12/438061.aspx). Aside from this debugger notification, does the mapping behave as expected?
