### ISSUE TITLE
Cannot map Expression<Func<T, bool>>

### ISSUE THREAD

**Issue by frenc** [AutoMapper/AutoMapper#685]
Hi, 

I have some problem when i try map expression, below is sample code:

      public IEnumerable<TBusinessObject> Get(Expression<Func<TBusinessObject,bool>> expression)
        {
            using (var dbContext = new NewagDBContext())
            {
                var dtoExpression = Mapper.Map<Expression<Func<TBusinessObject, bool>>, Expression<Func<TDTOObjetc, bool>>>(expression);
                var dtoObject = dbContext.Set<TDTOObjetc>().Where(x => !x.IsArchival).Where(dtoExpression);
                return Mapper.Map<IEnumerable<TBusinessObject>>(dtoObject);
            }
        }

When I run this code,'AutomapperMappingException' will be thrown

<pre>

Mapping types:
Expression`1 -> Expression`1
System.Linq.Expressions.Expression`1[[System.Func`2[[Newag.Domain.BusinessObjects.User, Newag.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[Newag.DataLayer.DTO.UserDTO, Newag.DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

Destination path:
Expression`1

Source value:
user => (user.Login == Convert(value(Newag.Domain.Services.UserService+<>c__DisplayClass0).login))
</pre>

I use  AutoMapper 3.3.1. I read that this version supports expression maping.

**Comment by TylerCarlson1** [comment]
There should be more information from the AutomapperMappingException.
Either below text provided or in the inner exception.
Also can you give what the expression passed that cause the error was?

**Comment by frenc** [comment]
In the inner exception I got something like this :

<pre>
{"Object reference not set to an instance of an object."}
</pre>

StackTrace:

<pre>
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node) in c:\dev\AutoMapper\src\AutoMapper\Mappers\ExpressionMapper.cs:line 80
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Mappers.ExpressionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\dev\AutoMapper\src\AutoMapper\Mappers\ExpressionMapper.cs:line 41
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:line 246
</pre>

I pass below lambda into Get method and it causes exception. UserRepository contains Get method, which I showed you yesterday, 

<pre>
string login = "Admin";
return this.userRepository.Get(u => u.Login == login);
</pre>
but when I try execute something like this, It works and doesn't throw exception

<pre>
this.userRepository.Get(u => u.Login == "Admin");
</pre>

**Comment by TylerCarlson1** [comment]
Both lambda examples you provided should work.
From the error message you provided earlier it looks like the lambda should look more like 
```
UserService service = new UserService();
this.userRepository.get(u => u.Login == service.Login);
```

The exact lamdba statement used would be best.

**Comment by mysnphit** [comment]
I have the same issue, this throws a **AutoMapperMappingException**:
*CallProvider*
```csharp
 public CallViewModel GetCall(int callId)
 {
            var domainModel = CallService.Get(x => x.Id == callId);

            return Mapper.Map<CallViewModel>(domainModel);
}
```

While this works fine: 
*CallProvider*
```csharp
 public CallViewModel GetCall(int callId)
 {
            var domainModel = CallService.Get(x => x.Id == 1); //Replaced callId with 1

            return Mapper.Map<CallViewModel>(domainModel);
}
```

*CallService*
```csharp
public TDomain Get(Expression<Func<TDomain, bool>> @where, params Expression<Func<TDomain, object>>[] includes)
{
            var set = EntityRepository
                .Queryable()
                .Where(MapDomainModelExpression(@where))
                .Include(includes);

            return MapEntity(set.SingleOrDefault());
}

private static Expression<Func<TEntity, TType>> MapDomainModelExpression<TType>(Expression<Func<TDomain, TType>> expression)
{
            return Mapper.Map<Expression<Func<TDomain, TType>>, Expression<Func<TEntity, TType>>>(expression);
}
```


Detailed Exception:
```
AutoMapper.AutoMapperMappingException was unhandled by user code
  HResult=-2146233088
  Message=

Mapping types:
Expression`1 -> Expression`1
System.Linq.Expressions.Expression`1[[System.Func`2[[Project.Domain.Models.Call, Project.Domain.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[Project.Data.Entities.Call, Project.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

Destination path:
Expression`1

Source value:
x => (x.Id == value(Project.Application.Web.CallProvider+<>c__DisplayClass0).callId)
  Source=AutoMapper
  StackTrace:
       bij AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:regel 254
       bij AutoMapper.MappingEngine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:regel 131
       bij AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType, Action`1 opts) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:regel 122
       bij AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:regel 81
       bij AutoMapper.Mapper.Map[TSource,TDestination](TSource source) in c:\dev\AutoMapper\src\AutoMapper\Mapper.cs:regel 73
       bij Library.Patterns.Repository.EF6.ServiceBase`3.MapDomainModelExpression[TType](Expression`1 expression) in c:\Users\Dev\Source\Workspaces\Company\Company\LibrarySuite\Branches\dev\Library.Patterns.EntityFramework\ServiceBase.cs:regel 251
       bij Library.Patterns.Repository.EF6.ServiceBase`3.Get(Expression`1 where, Expression`1[] includes) in c:\Users\Dev\Source\Workspaces\Company\Company\LibrarySuite\Branches\dev\Library.Patterns.EntityFramework\ServiceBase.cs:regel 113
       bij Project.Application.Web.CallProvider.GetCall(Int32 callId) in c:\Users\Dev\Source\Workspaces\Company\Company\Project\Branches\dev\Project\Application\Project.Application.Web\CallProvider.cs:regel 65
       bij Project.Controllers.CallController.GetCall(Int32 id) in c:\Users\Dev\Source\Workspaces\Company\Company\Project\Branches\dev\Project\Project\Controllers\CallController.cs:regel 71
       bij lambda_method(Closure , ControllerBase , Object[] )
       bij System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       bij System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       bij System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       bij System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
       bij System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       bij System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       bij System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       bij System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
       bij System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       bij System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       bij System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException: System.NullReferenceException
       HResult=-2147467261
       Message=De objectverwijzing is niet op een exemplaar van een object ingesteld.
       Source=AutoMapper
       StackTrace:
            bij AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node) in c:\dev\AutoMapper\src\AutoMapper\Mappers\ExpressionMapper.cs:regel 80
            bij System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
            bij System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
            bij System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
            bij System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
            bij System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
            bij AutoMapper.Mappers.ExpressionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\dev\AutoMapper\src\AutoMapper\Mappers\ExpressionMapper.cs:regel 41
            bij AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:regel 246
       InnerException: 
```

**Comment by TylerCarlson1** [comment]
If you try code below it should work..
```
 public CallViewModel GetCall(int callId)
 {
            var c = callId;
            var domainModel = CallService.Get(x => x.Id == c);

            return Mapper.Map<CallViewModel>(domainModel);
}
```
