### ISSUE TITLE
No .pdb files in nuget package

### ISSUE THREAD

**Issue by Muchiachio** [AutoMapper/AutoMapper#687]
Most of the libraries don't include their pdb files to nuget packages and I believe AutoMapper should not include them too, because of problems like:
- Test coverage frameworks including assemblies with .pdb files to their coverage results by default, resulting in inaccurate test coverage results.
- Debugger trying to step into, but not being able to find source files to step into.
- Larger Nuget package.

If there is still a need to include them [symbol package](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-symbol-package) should be created instead?

**Comment by jbogard** [comment]
Hmm...hmmm....I do create symbol packages but I think something is screwed up with them now that I check it out. Yeah I don't have a problem with it, I think I included them to get better stack traces or something.
