### ISSUE TITLE
FR: Intermediate stage in projections

### ISSUE THREAD

**Issue by alexfoxgill** [AutoMapper/AutoMapper#691]
Sometimes it's not possible to stay in the `IQueryable` paradigm when mapping from DB entities to DTOs, and we need to materialize the query before doing additional processing. For example:

	query.Set<Person>()
		.Where(p => p.Id == id)
		.Select(p => new
		{
			Name = p.FirstName + " " + p.LastName,
			Phone = p.PhoneNumber
		})
		.AsEnumerable()
		.Select(p => new PersonDto
		{
			Name = p.Name,
			Phone = p.Phone.Replace(" ", "")
		});

Here we can't use the `String.Replace()` method inside the LINQ query, as it cannot be translated into SQL.

At the moment there is no way in AutoMapper to perform this kind of two-stage projection. I can imagine an overload of `ProjectUsing` with this signature:

    ProjectUsing<TIn, TIntermediate, TOut>(
        Expression<Func<TIn, TIntermediate>> queryExpr,
        Func<TIntermediate, TOut> mapFunc)

So the above sample could be expressed as:

	ProjectUsing(
		p => new
		{
			Name = p.FirstName + " " + p.LastName,
			Phone = p.PhoneNumber
		},
		p => new PersonDto
		{
			Name = p.Name,
			Phone = p.Phone.Replace(" ", "")
		})

The main issue is that the `Project().To<>()` syntax returns an `IQueryable`, which would not be possible with the above approach. Would a new `Project().ToEnumerable<>()` method work?

**Comment by jbogard** [comment]
I'm in the process of removing the separate To() call, so there's only ProjectTo().

Why not do this?

```
query.Set<Person>()
    .Where(p => p.Id == id)
    .Project().To<PersonDto>();
    .ToList().Each(dto => dto.Phone = dto.Phone.Replace(" ", "")
```

The first one you do should be done through MapFrom. The second, might be able to as well.

**Comment by alexfoxgill** [comment]
You're right in that case - I should have used a heterogenous example:

	query.Set<Person>()
		.Where(p => p.Id == id)
		.Select(p => new
		{
			Name = p.FirstName + " " + p.LastName,
			Title = p.Title
		})
		.AsEnumerable()
		.Select(p => new PersonDto
		{
			Name = p.Name,
			Title = Enum.Parse(typeof(Titles), p.Title)
		});

The main reason I'm interested in this is to avoid creating an intermediate class. In the instance above I'd have to introduce `PersonIntermediate`:

	class Person
	{
		public int Id { get; set; }
		public string Title { get; set; }
		(other irrelevant stuff)
	}

	class PersonIntermediate
	{
		public int Id { get; set; }
		public string Title { get; set; }
	}

	class PersonDto
	{
		public int Id { get; set; }
		public Titles Title { get; set; }
	}

**Comment by jbogard** [comment]
I think you'd be able to get this from an Each method, where instead of you creating a new thing, you can mutate the thing.

**Comment by alexfoxgill** [comment]
What would you project to?

**Comment by jbogard** [comment]
Sure you could:
```
query.Set<Person>()
    .Where(p => p.Id == id)
    .Project().To<PersonDto>()
    .ToList()
    .Each(p => p.Title = Enum.Parse(typeof(Titles), p.TitleRaw));
```
Just pass the raw string in there. So EF doesn't do string enum -> enum?

**Comment by BlaiseD** [comment]
Also how about a custom DbFunction:
Mapper.CreateMap<Person, PersonDto>()
                .ForMember(d => d.Phone, opt => opt.MapFrom(s => MappingHelpers.Replace(s.PhoneNumber, " ", "")));

and

    public static class MappingHelpers
    {
        [DbFunction("Edm", "Replace")]
        public static string Replace(string original, string oldValue, string newValue)
        {
            return original.Replace(oldValue, newValue);
        }
    }

unless I'm misunderstanding the problem.
