### ISSUE TITLE
AutoMapper 3.3.1 From ViewModel to Model Ignore Property Not Working

### ISSUE THREAD

**Issue by julian20** [AutoMapper/AutoMapper#692]
Hello,

I have a viewModel and model with a property:
```
public virtual List<Imagen> Imagenes {get;set;}
```
In AutoMapperConfiguration:
```
Mapper.CreateMap<ViewModel, Model>().ForSourceMember("Imagenes", x => x.Ignore());
```
or 
```
Mapper.CreateMap<ViewModel, Model>().ForMember(x=>x.Imagenes, y => y.Ignore()); -> Here resharper not recognize the first parameter
```
Please, help me!

Thanks.

Julián.

**Comment by jbogard** [comment]
ViewModel and Model both have the property? Have you tried just ForMember?

**Comment by julian20** [comment]
Yes. I tried.

The method ignore () puts the prop null destination or maintains the original value?

Thanks!

Julián.

**Comment by jbogard** [comment]
Ignore says two things:
- For members whose names don't match up, ignore this during configuration validation
- For members whose names DO match up, don't map the source value to the destination value

**Comment by julian20** [comment]
My object has a list full of images, then I run:

objModel var = Mapper.Map <ViewModel, Model> (objViewModel)

The image property is null. Maybe I'm not using AutoMapper correctly.

Thank you very much.

Julian.

**Comment by julian20** [comment]
My object has a list full of images, then I run:

var objModel = Mapper.Map<ViewModel, Model>(objViewModel);

The image property is null. Maybe I'm not using AutoMapper correctly.

Thank you very much.

Julian.

**Comment by lbargaoanu** [comment]
@julian20 Can you provide a failing test?

**Comment by jbogard** [comment]
:neutral_face:
