### ISSUE TITLE
Any generic way to wrap a object in a new object?

### ISSUE THREAD

**Issue by sstorie** [AutoMapper/AutoMapper#694]
I see there is support for open generics, but I'm not sure how to handle this specific case where I want to wrap an object in a generic "response" object. So with the following classes (just for example):

    class Foo { 
        public int Value {get;set;}
    }

    class Response<T> {
        T Data {get; set;}
        List<string> Errors {get; set;}
    }

    // I can imagine writing something like this to map Foo into a new Response<Foo> object
    //
    Mapper.CreateMap<T, Response<T>>(...code to set the source object to the 'Data' property of a new Reponse<T> object...);

I'd like to use Automapper to automatically handle this type of conversion, but do so generically so I don't to create mappings for every type that might get wrapped in a response. Is that possible?

**Comment by jbogard** [comment]
No unfortunately not :(

**Comment by TomasHubelbauer** [comment]
@jbogard Does you closing this mean it's not on a short-term roadmap or it's not considered as a feature at all at this point? Either way, someone coming here looking for a workaround at least can check out the *awesome* answer on my SO question regarding this topic.

http://stackoverflow.com/q/38353918/2715716

**Comment by jbogard** [comment]
@TomasHubelbauer features that I don't use or plan to use are not going to get implemented by myself. If someone requests something and also submits a PR to include that functionality, then I'm happy to consider it.

**Comment by TomasHubelbauer** [comment]
Cool, I'll look into preparing a PR for this hopefully sometime soon, I think it would be a neat addition.

**Comment by jbogard** [comment]
I left a comment on SO, but one thing to potentially look at is the ForAllMaps extension to help ease this. You can loop through all the maps and go from there.

**Comment by TomasHubelbauer** [comment]
That's awesome! Thank you. I'm still tweaking the SO solution to fully meet my needs (yesterday I had a quick moment to confirm it correctly wraps collection items and tomorrow I will hopefully have time to check if it still works if the source object itself is a collection/array and why not potentially) but when I get there I'll take a look at proposing a PR for it.
