### ISSUE TITLE
Can I reuse mappings in projections?

### ISSUE THREAD

**Issue by Korijn** [AutoMapper/AutoMapper#695]
Assume the following code...

    class Foobar {
        public string Foo { get; set; }
        public string Bar { get; set; }
    }

    class ViewModelA {
        public string Foo { get; set; }
    }
    class ViewModelB {
        public string Foo { get; set; }
        public string Bar { get; set; }
    }

    Mapper.CreateMap<Foobar, ViewModelA>();
    Mapper.CreateMap<Foobar, ViewModelB>();

If I understand correctly, with this setup, I can now use the following projections:

    var aModels = context.Foobars.Project().To<ViewModelA>().ToList();
    var bModels = context.Foobars.Project().To<ViewModelB>().ToList();

So now imagine I want to show both viewmodels on some page, because they are both viewmodels for partial views. Can I then do this? Will this work as I expect it to?

    class ViewModelC {
        public ViewModelA A { get; set; }
        public ViewModelB B { get; set; }
    }

    Mapper.CreateMap<Foobar, ViewModelC>();

    var cModels = context.Foobars.Project().To<ViewModelC>().ToList();
    // every element in cModels should have populated A and B properties

Or do I have to specify MapFrom for both properties before it will work?

    Mapper.CreateMap<Foobar, ViewModelC>()
        .ForMember(c => c.A, conf => conf.MapFrom(f => f))
        .ForMember(c => c.B, conf => conf.MapFrom(f => f));

**Comment by jbogard** [comment]
Is there a model object C? If so, it's straight forward.

If not, then EF likely won't support this, and AutoMapper won't really help one way or the other. It is rather strange to project the same objects onto two separate models. Usually I project 2 or more different navigation properties onto different models and combine them up later.

**Comment by Korijn** [comment]
No, there is no model object C. In this example, the only source model object is "Foobar".

I was just wondering if it was possible. :) Thanks for the quick reply.

**Comment by jbogard** [comment]
Yep, EF won't let you do it in one call. I just make multiple calls to project different pieces.
