### ISSUE TITLE
NullReferenceException used to be swallowed

### ISSUE THREAD

**Issue by katlimruiz** [AutoMapper/AutoMapper#696]
Having this line before:
`.ForMember(d => d.CityDistrictId, o => o.MapFrom(s => s.CityDistrict.DistrictId))

When CityDistrict object was null, this used to work magically and not error. It seems that the old version of Automapper swallowed the exception and did not touch the destination property.

But with the new version, this throws a NullReferenceException because CityDistrict was null.

There is a NullReferenceExceptionSwallowingResolver class, I dont know much of the code, but it seems it is not used for all scenarios.

I;m not saying this should be changed, **I believe it is better this way because is more explicit on the app side and not some magic inside Automapper. BUT**, where is the release log where you announce the breaking changes?

**Comment by jbogard** [comment]
It is published here:

https://github.com/AutoMapper/AutoMapper/releases/tag/v3.1.0

What version did you upgrade from?
