### ISSUE TITLE
Please support Windows 10 with Automapper 

### ISSUE THREAD

**Issue by Gilligan128** [AutoMapper/AutoMapper#697]
Because reasons. 
https://twitter.com/jbogard/status/580738873501700097

**Comment by jbogard** [comment]
Sigh.

**Comment by ChrisMcKee** [comment]
:+1:

**Comment by jbogard** [comment]
Lol why closed? Someone else is going to create this anyway.

**Comment by Gilligan128** [comment]
ah ok. I am surprised it wouldn't work as is though? Does Windows 10 come with .net vnext as its default or something?

**Comment by dvdstelt** [comment]
It's because of the new old start menu. Jimmy Bogard didn't see that one coming, and it's a lot of work and he needs to prepare for NDC Oslo. Maybe you can do a pull request?

**Comment by Gilligan128** [comment]
The new old start menu?

**Comment by dvdstelt** [comment]
Yeah, they brought the Start Menu from Windows 8 back, but it's also new. Because it didn't exist in Windows 9, you know.

**Comment by Gilligan128** [comment]
Oh, man, that's pretty crazy!

**Comment by dvdstelt** [comment]
I know! Right? It's, like, they're messing with us, dude! Like, and it gets crazier, even! Like, they have put this tiny photo of some dude in, like, the top-left corner. But I can't see who it is! And I'm, like, what's that dude in the corner of my new old start menu?

**Comment by Gilligan128** [comment]
He is the wizard behind the curtain...of the new old start menu

**Comment by jbogard** [comment]
Supported.
