### ISSUE TITLE
Project.To<DTO> and OrderBy

### ISSUE THREAD

**Issue by shaneray** [AutoMapper/AutoMapper#700]
in my mapping I have ```.ForMember(dest => dest.PaymentId, src => src.MapFrom(x => x.PymtID));```
I am using DynamicLinq to do an order by
```
if (!string.IsNullOrWhiteSpace(pagedRequestFilter.OrderBy))
{
                data = data.OrderBy(pagedRequestFilter.Descending
                    ? string.Format("{0} descending", pagedRequestFilter.OrderBy)
                    : pagedRequestFilter.OrderBy);
}
```
This is resulting in an excpetion... ```"ExceptionMessage": "No property or field 'PaymentID' exists in type 'Payment'"```

I was expecting Automapper and Project.To<> to see that I mapped PymtID to PaymentId and do the orderby based off the proper property name...  Is this a bad assumption, or is something wrong here..

**Comment by jbogard** [comment]
You need to put your OrderBy before Project.To:

```
dbContext.OrderBy("PymtID descending").Project.To<FooDTO>();
```

**Comment by shaneray** [comment]
Thanks for the quick response!

To be honest I kind of jumped the gun on this...  It may just be a case of me expecting it to work in a way that it is not designed to work.  I will look over the source code more and dig a bit deeper, but in the meantime let me provide a little more info..

The OrderBy is in fact before the Project.To<> in my code.  We are using the mediator pattern and the OrderBy, Skip, Take, etc.. is part of our paged request pipeline.  We are then using Project.To<> on the IQueryable later on.

Since the end user does not know the column is actually named *PymtID*, They are going to provide the name from the view model *PaymentId*.  The hope was AutoMapper magic would handle this, but did not seem to be the case.  If this is not expected behavior I will close this issue out.

**Comment by jbogard** [comment]
No, it doesn't but maybe create a new issue? This sounds like a valid use case.

**Comment by TylerCarlson1** [comment]
If you can get your order by to use expression instead of text then you should be able to map to expression of db object.
```
Expression<Func<DTO,int>> orderByExpression = q => q.PaymentId;
var orderByDBExpression = Mapper.Map<Expression<Func<DB,int>>>(orderByExpression);
data = data.OrderByDesc(orderByDBExpression);
```
Getting from string to Expression from function is pretty tricky but if you can, then Automapper will handle that magic to transfer it into an expression of the database object.  Just so long as your return values are exactly the same type.  No int to int? mappings.  Also should work for double, string, DateTime, ect.

**Comment by Venzhyk** [comment]
It seems your case is very simular to my pull request #659

**Comment by shaneray** [comment]
Sorry for the long delay.  I was researching and coming up with a new solution.  First, I would like to apologize for opening the issue... as it is not an issue with AutoMapper, but the DynamicLinq assembly.

I have modified the DynamicLinq assembly to work with AutoMapper and it can be found here:
Nuget: https://www.nuget.org/packages/ShaneSpace.ProjectedDynamicLinq/
GitHub: https://github.com/shaneray/ShaneSpace.ProjectedDynamicLinq

Data:
```
class Foo {
   public FirstName {get; set; }
   public LastName {get; set; }
}
class FooDTO {
   public FullName { get; set; }
}
```

Mapping
 ```
Create.Map<Foo, FooDTO>().ForMember(dest => dest.FullName, src => src.MapFrom(x => x.FirstName + " " + x.LastName));
```

Before
 ```
IQueryable<Foo>.Where("FullName == \"John Doe\"").Project.To<FooDTO>;
```
The above would fail because the FullName does not exist in the Foo object.

Now
```
IQueryable<Foo>.Where<Foo, FooDTO>("FullName == \"John Doe\"").Project.To<FooDTO>;
```
Using my library you can now use member names from the DTO in your query.  It will not only work on simple renames, but also calculated properties.

**Comment by shaneray** [comment]
Forgot to mention... the updated library also works on the OrderBy which the original question was asking about.  I had requirements to have dynamic orderby and where on mapped/projected object, this updated library handles both.
