### ISSUE TITLE
Project().To<> and polymorphism

### ISSUE THREAD

**Issue by cherrydev** [AutoMapper/AutoMapper#701]
This is obviously related to #570, but I'm a bit confused why that issue was closed.
Incidentally, this is unrelated to EF completely because it fails even if it's in memory.

I have some mappings that follow the pattern, where Container has a list of AbstractBase and ContainerDto has a list of AbstractBaseDto:
```
Mapper.CreateMap<Container, ContainerDto>();

Mapper.CreateMap<AbstractBase, AbstractBaseDto>()
.Include<SubA, SubADto>()
.Include<SubB, SubBDto>();

Mapper.CreateMap<SubA, SubADto>();
Mapper.CreateMap<SubB, SubBDto>();
```
Now, in #570 @jbogard asks, "How would you do this projection manually?"

Well, say that I'd already created my mappings in Automapper as above.
If I map Container to ContainerDto, automapper successfully maps the list of AbstractBase to AbstractBaseDto.

I can (mostly) manually create a projection expression like this:

```
var subAMap = engine.CreateMapExpression<SubA, SubADto>().Compile();
var subBMap = engine.CreateMapExpression<SubB, SubBDto>().Compile();

var projected =
  fields.Select( x => 
x is SubA ? (AbstractBaseDto) subAMap((SubA)x) :
x is SubB ? (AbstractBaseDto) subBMap((SubB)x) : null);
```

Currently, doing a Project().To<> results in an exception of not being able to instantiate an abstract type.
Curiously, if I do `engine.CreateMapExpression<AbstractBase, AbstractBaseDto>().Compile()` I also get the same exception on `Compile()` even if I don't even run the delegate.

**Comment by hazzik** [comment]
Could work. :+1:

**Comment by cherrydev** [comment]
Ya, it appears that the expression returned by `engine.CreateMapExpression<AbstractBase, AbstractBaseDto>()` is "dumb" and completely ignores the Include() statements.

**Comment by TylerCarlson1** [comment]
The issue was closed because even if you could get a manually mapped expression, it wouldn't give you any benefit because EF couldn't translate it to a SQL query, giving you a benefit of using ProjectTo.

If you have another use case that benefits from Projection using inheritance then it would be worth opening back up again.

Also the manual mapping example is pretty much dead on but I don't think you can compile the expressions and still have the function work in EF.

**Comment by jbogard** [comment]
I wonder if I should just try to create the expression anyway? The problem I have is I don't know what expression each ORM would want/need to signal polymorphism. I have the same issue with enums, they all want something slightly different.

**Comment by cherrydev** [comment]
Nope…
```
Select(x => x is SubA ? new SubADto() : x is SubB ? (AbstractBaseDto) new SubBDto() : null);
```
Results in:
Unable to cast the type SubADto to AbstractBaseDto. LINQ to Entities only supports casting EDM primitive or enumeration types.

**Comment by cherrydev** [comment]
…which now I see is exactly why #570 was closed.
On the other hand, even though this won't work on the EF Linq provider, I still sorta consider it a bug that CreateMapExpression creates the wrong expression for types that have Include()s. If CreateMapExpression checked the source type for its includes, it could create an expression that includes checks for the subtypes and then just wrap those mapping expressions.

**Comment by cherrydev** [comment]
For those interested, I've created an issue on CodePlex to vote for (somehow I couldn't find an existing issue about this):  https://entityframework.codeplex.com/workitem/2730

**Comment by futurechan** [comment]
I just got bit by this one too!
