### ISSUE TITLE
Missed type map configuration when use IoC to initialize profiles

### ISSUE THREAD

**Issue by Ciget** [AutoMapper/AutoMapper#702]
Hi guys,

Found strange behaviour of Automapper 3.3.1 - if i use Bootstrap to initialize profiles (Add to mapper configuration) i got:
Missing type map configuration or unsupported mapping.

Mapping types:
IdeaModel -> AddIdea
CityZen.Service.Models.Ideas.IdeaModel -> CityZen.Service.Commands.Ideas.AddIdea

So, here is my models:
```
public class IdeaModel
    {
        public string Title { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Body { get; set; }
        public string Author { get; set; }
}

public class AddIdea 
    {
        public string Title { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Body { get; set; }
        public string Author { get; set; }
    }
```

My IdeaProfile:
```
public class IdeaProfile : Profile
    {
        protected override void Configure()
        {
            base.Configure();
            Mapper.CreateMap<IdeaModel, AddIdea>()
                .ForMember(x=>x.Author, y=>y.MapFrom(t=>t.Author));
        }
    }
```

Here is how in Unit test project i initialize mapper:
```
var info = new DirectoryInfo(Environment.CurrentDirectory);
            var files = info.EnumerateFiles("CityZen.*.dll")
                .Where(x => !x.Name.StartsWith("CityZen.Tests"));
var _assemblies= files.Select(file => Assembly.LoadFile(file.FullName)).ToArray();

 Mapper.Initialize(cfg =>
            {
                foreach (var assembly in _assemblies)
                {
                var profiles = (assembly.GetTypes())
                        .Where(t => (t.IsSubclassOf(typeof (Profile)) && t.GetConstructor(Type.EmptyTypes) != null))
                        .Select(x=>(Profile)Activator.CreateInstance(x));

                    foreach (var item in profiles)
                    {
                        cfg.AddProfile(item);
                    }
                }

                cfg.AllowNullDestinationValues = true;
            });
```

Then i call exactly mapping that throw me an exception:
```
var model = new IdeaModel();
var converted = Mapper.Engine.Map<AddIdea>(model);
```

What`s wrong with my code?
Root of problem was in cfg.AddProfile(some type); and if i replace it with cfg.AddProfile(new IdeaProfile());  everything will works fine.

Could you please help me with it?
Thanks in advance.

**Comment by TylerCarlson1** [comment]
I think `t.IsSubclassOf(typeof(Profile))` needs to be `typeof(Profile).IsAssignableFrom(t)`

Taken from
https://msdn.microsoft.com/en-us/library/system.type.issubclassof%28v=vs.110%29.aspx

**Comment by Ciget** [comment]
Actually, no. I tried ```t.BaseClass == typeof(Profile)``` - nothing. I have no problem with filtering types to use in initialized.
As understand main problem - or in create nested Profile instances or in use Mapper.Initialize().

**Comment by Ciget** [comment]
I found the root of an issue -
Resharper options menu Tools->Unit testing
disable check box shadow-copy assemblies being tested.

Sorry for false alarm.
