### ISSUE TITLE
Visual Studio tries to locate PrimitiveExtensions.cs

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#706]
I have a model that I'm mapping to DTO. All the mapping should be set up correctly. I'm using:

`Mapper.AssertConfigurationIsValid();`

I retrieve the model from the db. Its properties, including its child entities are correct and they are exactly what is found in the tables.

However, when I try to map it to DTO:

`var entity = myService.Get(id)`
`var dto = Mapper.Map<myDTO>(entity);`

Visual Studio shows the Open File dialog and tries to open the file PrimitiveExtensions.cs. I can't stop the app, and I need to end Visual Studio from the Task Manager.

This problem occurs for only one particular model (and it's child entities). Does it occur because the mapping is not set up correctly?

**Comment by jbogard** [comment]
Make sure you're set up to only allow breakpoints on uncaught exceptions, that's likely what you're seeing.

**Comment by cryo75** [comment]
The problem was that one particular entity was referencing itself and AutoMapper threw a StackOverflowException.

in this particular case  Iset MaxDepth(1) and now it works fine.
