### ISSUE TITLE
calling ConstructUsing before every Mapping

### ISSUE THREAD

**Issue by daberni** [AutoMapper/AutoMapper#708]
We used AutoMapper since years now and were very happy with it.
Some time ago we updated it from a very old version (2.1.0). Everything was fine but we had one Problem.
We use AutoMapper to map from Entities (NHibernate) to DTO's and back. 

Entites
```
class Foo
{
    public int Id { get; set; }
    public string SomeValue { get; set; }
    public Bar Bar { get; set; }
}

class Bar
{
    public int Id { get; set; }
    public string SomeValue { get; set; }
}
```
and according DTOS
```
class FooDTO
{
    public int Id { get; set; }
    public BarDTO Bar { get; set; }
}

class BarDTO
{
    public int Id { get; set; }
}
```

our Mapping was like:
```
configuration.CreateMap<Foo, FooDTO>();
configuration.CreateMap<FooDTO, Foo>()
    .ConstructUsing(source => source.Id > 0 ? FooService.Load(source.Id) : new Foo());

configuration.CreateMap<Bar, BarDTO>();
configuration.CreateMap<BarDTO, Bar>()
    .ConstructUsing(source => source.Id > 0 ? BarService.Load(source.Id) : new Bar());
```

we first loaded the current Version of the Entity from Database (if it exists, else create a new one) and then all Properties got mapped.
ConstructUsing was called everytime, before mapping of Properties started.
But then the behaviour changed and ConstructUsing was only called, when the Value on the destination Object was null.

that broke our system:
when the Reference to Bar changes, first Foo is loaded from Database with old Bar as reference.
because Foo.Bar is not null, ConstructUsing isn't called anymore, and the old Bar object is overwritten with the Properties of the new Bar object, which causes errors with NHibernated, because the Id shouldn't change.
We simply need to load the new Bar Reference from DB according to it's Id.

Now my Question:
Does AutoMapper support our requested behaviour somehow?
Currently we use `ForMember(dest => dest.Bar, opt => opt.DoNotUseDestinationValue())` so that ConstructUsing is called everytime again.
but we would like to define this on the Type level instead of Property level.

**Comment by jbogard** [comment]
With NHibernate, you shouldn't need the ConstructUsing, since it will use the existing object. However, you'll need the UseDestinationValue piece:

```
configuration.CreateMap<FooDto, Foo>()
    .FormMember(f => f.Bar, opt => opt.UseDestinationValue());
```

**Comment by da-berni** [comment]
the problem is, when the reference in the DTO changes to another Object (e.g. BarDTO[id=3] to BarDTO[id=6]) first Bar[id=3] is loaded because it's referenced by Foo, and then only the properties get mapped, overwriting the id with 6, which causes an error.
before mapping the properties, the new entity Bar[id=6] should get loaded and referenced in the Foo-Entity. currently we use
```
configuration.CreateMap<FooDto, Foo>()
    .FormMember(f => f.Bar, opt => opt.DoNotUseDestinationValue());
```
so ConstructUsing is called, and the Bar-Entity is loaded from DB.
but we would like to define this in the `configuration.CreateMap<BarDTO, Bar>()` instead of the `Foo` mapping
