### ISSUE TITLE
Source code for 3.3.1

### ISSUE THREAD

**Issue by AndrewSav** [AutoMapper/AutoMapper#713]
There are source code archive given on this page for 3.3.1
https://github.com/AutoMapper/AutoMapper/releases/tag/3.3.1

However the same version number downloaded from nuget here
https://www.nuget.org/packages/AutoMapper/

apparently built from different source. I stumbled across this while debugging an issue with DataReaderMapper. This class is included into nuget package but it is not present in source archive.

While I can easily find the class [in the history](https://github.com/AutoMapper/AutoMapper/commit/33831e3b53ed1cd698558daa2db483906ec5c13a) I'd like to get the version that nuget was build from if possible.

Would it be possible to make sure that the source archive matches the actual nuget binaries?

**Comment by jbogard** [comment]
Whoops! I tagged the wrong commit with this release. Fixed the tag, thanks for the heads up!
