### ISSUE TITLE
AutoMapper 4.0 Roadmap

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#714]
A set of things I want to *finally* get done in AutoMapper 4.0. The main thing I'm looking at is revamping the configuration model. Today, the configuration API directly modifies the execution model. That means you have to do things in your config in a very specific order. The way you get around this is to either make two models:
- Configuration Model
- Execution Model

Or make the configuration API just collect actions to perform against the execution model. When you build the execution model, you just build it in the correct order based on the actions to perform.

The action based model is nice because you can apply conventions as actions (all properties matching XYZ do ABC).

**Comment by MattHoneycutt** [comment]
On the grounds of "things that change together should live together," I'd like to see a way to move the configuration closer to the model.  I've implemented my own solution for this, and found it to be much easier to maintain than keeping mapping configuration elsewhere.  

Basically, view models have two options.  If they don't require custom mapping configuration, they can simply implement the IMapFrom<TEntity> marker interface, where TEntity is (usually) the domain type the model should be mapped from.

For cases where the mapping doesn't follow the default conventions or requires some magic, view models can implement the IHaveCustomMapping interface, which defines a single method, CreateMappings(IConfiguration configuration).  This allows the model to do whatever crazy things it needs to in its config.

A typical use might look like this:

	public class WidgetViewModel : IMapFrom<Widget>
	{
		public int Id { get; set; }
		public int Name {get; set; }
	}

	public class WidgetFactoryViewModel : IMapFrom<WidgetFactory>, IHaveCustomMappings
	{
		public Address Address { get; set; }
		
		public IList<WidgetViewModel> ActiveWidgets { get; set; }
		
		void IHaveCustomMappings.CreateMappings(IConfiguration configuration) 
		{
			configuration.CreateMap<WidgetFactory, WidgetFactoryViewModel>()
				.ForMember(x => x.ActiveWidgets, opt => opt.MapFrom(x => x.Widgets.Where(w => w.IsActive)));
		}
	}

This mapping approach is available on NuGet via the Heroic.AutoMapper package.  I haven't gotten around to publishing the source as a public repo yet, but plan to.   I'd be happy to contribute this or adapt it if it fits what you have in mind for v4.

**Comment by jbogard** [comment]
Yeah, configuration scanning was a big one I wanted to add too. I also wanted to add convention support like Fluent NHibernate and others.

**Comment by MattHoneycutt** [comment]
Conventions would be great, too.  Did you have ideas on what the config
scanning or conventions setup might look like?

**Comment by jbogard** [comment]
Config scanning is pretty straightforward. I'm looking at a couple levels of things:

- Things that contain groups of type maps
- Things that contain config for one type map (like you have above)
- Conventions

Right now I'm planning on breaking out config for Profile and things it uses to just capture config settings before actually building up TypeMaps, that would allow for conventions.

**Comment by shatl** [comment]
Hi Jimmy
Is it possible to make AutoMapper avoid loading all navigation properties when mapping EF or NHibernate entities? 
Currently all navigation properties are loaded even if they are marked with Ignore.

**Comment by TylerCarlson1** [comment]
So for actions and fluent api would member mappings go something like this?
```
new ParentSourceToDestinationMemberMapper().AddMember<NameSplitMember>().SetMemberInfo<FieldProperty>();
new ParentSourceToDestinationMemberMapper().AddName<PrePostfixName>(_ => _.SetPrefixs("Get")).SetMemberInfo<MethodsMemberInfo>();
new ParentSourceToDestinationMemberMapper().SetMemberInfo<ExtensionMethodsMemberInfo>();
```
Map properties and split names further down for Fields/Properties.
Map Methods with possible prefix "Get" and don't split names further down
Map Extension Methods and don't split names further down

I assume this is the default behavior you would want in automapper but it's more like
```
new ParentSourceToDestinationMemberMapper().AddMember<NameSplitMember>().AddName<PrePostfixName>(_ => _.SetPrefixs("Get")).SetMemberInfo<AllMemberInfo>()
```
which uses prefix "Get" and name split fields,properties, methods, and extension methods
