### ISSUE TITLE
DynamicMap method not mapping IDataReader to generic list

### ISSUE THREAD

**Issue by anotheroke** [AutoMapper/AutoMapper#715]
I am unable to get the following code to work using the latest NuGet 3.2.0 package:

    DataTable dt = RetrievalProcedures.GetFxrates(ServerId,adp);
    List<FxRate> fx = AutoMapper.Mapper.DynamicMap<IDataReader, List<FxRate>>(dt.CreateDataReader());

No exception is thrown but the fx list is not populated. This code definitely used to work as we have a deployed code base which is working fine. It just no longer works in our solution. I also tried the above snippet in LinqPad and loaded the AutoMapper package via NuGet. Same result.

**Comment by jbogard** [comment]
What previous version did you use?

**Comment by anotheroke** [comment]
Also 3.2.0.0 - only difference is the date they were installed from NuGet. I got the source from here and only thing obvious was that I don't have the .NET 4.5.3 components installed.

**Comment by jbogard** [comment]
That shouldn't matter - 3.2 isn't compiled against 4.5.3.

**Comment by anotheroke** [comment]
I've managed to get it working now. Deleting the Packages folders and then using the Visual Studio NuGet Packages Manager to remove and then add the AutoMapper package seems to have fixed it. A binary comparison between the working folder and non-working one didn't show any differences. But always failed to map at runtime.

**Comment by rallister** [comment]
Hi there not sure if I should comment on a closed issue but I am having exactly the same issue after upgrading to 4.0.4 from 3.3.1. Tried other versions 4.0.0+ none of which worked, in the end had to downgrade back to 3.3.1. 

Connections are made to SQL Server 2012, all properties are strings (adding explicit convert of resulting fields did help)
Regards,
