### ISSUE TITLE
AutoMapper 3.3.1 - Error while executing AutoMapper.Mapper.CreateMap<SimpleClass, SimpleDTOClass>

### ISSUE THREAD

**Issue by VR9980** [AutoMapper/AutoMapper#716]
In AutoMapper 3.3.1 , getting the below error while calling CreateMap

The runtime has encountered a fatal error. The address of the error was at 0x74e7153a, on thread 0x2764. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

Can someone please help

**Comment by jbogard** [comment]
Can you post your source/destination types and the specific configuration you're calling, including any MapFrom etc things?

**Comment by VR9980** [comment]
Hi jbogard, 

Thanks for your reply! Source and destination types are simple objects with 2-3 properties. This was working till yesterday, until I upgrade AutoMapper to 3.3.1 using nugget package

However, here is the snippet
   public class User
    {
       public long UserID { get; set; }
        public long ProfileID { get; set; }
        public string Name { get; set; }
   }
   public class UserDTO
    {
       public long UserID { get; set; }
        public long ProfileID { get; set; }
        public string Name { get; set; }
   }
there are no MapFrom from this mapping. No additional configurations - all defaults.

Mapper.CreateMap is the first statement in Application_Start and it is failing there with the above error

Thanks,
VR

**Comment by jbogard** [comment]
What server version/.NET version are you using in production?

**Comment by VR9980** [comment]
Hi Jimmy,

Its not prod. Its Development machine. it has 4.5 .net F/W and also installed VS 2015 RC. Could that be because of this

Thanks,
VR

-----Original Message-----

**Comment by lbargaoanu** [comment]
@VR9980 It works for me. Most likely the error has nothing to do with AutoMapper, but if you can provide a failing test, I'll look into it.

**Comment by VR9980** [comment]
Thanks Lucian! I will give it a try again and post if I get the error ...
Have a great day!!

-----Original Message-----

**Comment by VR9980** [comment]
I'm still getting the issue at CreateMap, which is almost first statement in globals.asax.cs Error: Fatal Error - cannot evaluate expression - PFA for more details
Same project it's working in another machine

-----Original Message-----

**Comment by lbargaoanu** [comment]
To investigate further I need a full memory dump at crash time. Or a repro :)
