### ISSUE TITLE
Auto Mapper not mapping randomly

### ISSUE THREAD

**Issue by vmanne** [AutoMapper/AutoMapper#717]
I configured automapper for my asp.net MVC/Web API project in the method definition as follows.

```
 Mapper.CreateMap<UserLicenses, UserLicenseResponseModel>()
                    .ForMember(dest => dest.State, opt => opt.MapFrom(src => src.States.StateCode))
                    .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                    .ForMember(dest => dest.FullName, opt => opt.MapFrom(src => (src.UserProfile != null) ? (src.UserProfile.FirstName + ' ' + src.UserProfile.LastName) : " "));

Mapper.CreateMap<AdditionalExpenses, AdditionalExpensesResponseModel>();
```
We are noticing that api is randomly not mapping these values and response json is returning null values.

When this happens I'm recycling the app pool and it seems to work for a period of time and we run into the issue again.

Documentation refers to storing all the mappings in Application_Start in Global.asax. However,  we are setting them in the method definition - Is that why we are seeing this issue? Please advise. Thanks

**Comment by jbogard** [comment]
Yes, put this in your Application_Start.
