### ISSUE TITLE
ValueResolver not called when resolving with inherited mapping

### ISSUE THREAD

**Issue by mattsmith-au** [AutoMapper/AutoMapper#719]
When utilizing `IncludeBase` to inherit mapping I have run into an issue where a custom ValueResolver defined in a base mapping is not invoked. 

    class Order
    {
        public int A { get; set; }
        public int B { get; set; }
    }

    class OrderADto
    {
        public int A { get; set; }
    }

    class OrderBDto : OrderADto
    {
        public int B { get; set; }
    }

    class CustomResolver : ValueResolver<int, int>
    {
        public static bool WasExecuted = false;

        protected override int ResolveCore(int source)
        {
            WasExecuted = true;
            return source;
        }
    }

    [TestFixture]
    public class DtoMappingTest
    {
        Order _order;

        [TestFixtureSetUp]
        public void InitMapping()
        {
            Mapper.CreateMap<Order, OrderADto>()
                .ForMember(dto => dto.A,
                    opt => opt.ResolveUsing<CustomResolver>().FromMember(src => src.A));

            Mapper.CreateMap<Order, OrderBDto>()
                .IncludeBase<Order, OrderADto>();
                
            Mapper.AssertConfigurationIsValid();
        }

        [SetUp]
        public void SetUp()
        {
            CustomResolver.WasExecuted = false;

            _order = new Order
            {
                A = 1,
                B = 2
            };
        }

        [Test]
        public void TestOrderMappingToOrderADto()
        {
            var orderDto = Mapper.Map<Order, OrderADto>(_order);
            Assert.IsTrue(CustomResolver.WasExecuted);
        }

        [Test]
        public void TestOrderMappingToOrderBDto()
        {
            var orderDto = Mapper.Map<Order, OrderBDto>(_order);
            Assert.IsTrue(CustomResolver.WasExecuted);
        }
    }

It appears the conventional mapping is being used over the custom ValueResolver defined in the base mapping. If the name of the fields do not match, ie rename 'B' to 'X' in OrderBDto the resolver is invoked as expected.

Is this the expected behaviour?

**Comment by mattsmith-au** [comment]
Any thoughts?

**Comment by jbogard** [comment]
Value resolvers aren't inherited right now, that's all. You'll have to redefine them.
