### ISSUE TITLE
Polymorphic mapping broken between 4.0.0-ci1052 and 4.0.0-ci1053

### ISSUE THREAD

**Issue by rmja** [AutoMapper/AutoMapper#722]
Hi,

The following works perfectly in 4.0.0-ci1052, but throws in in 4.0.0-ci1053:

    Mapper.CreateMap<Order, OrderDto>()
          .Include<OnlineOrder, OnlineOrderDto>()
          .Include<MailOrder, MailOrderDto>();

    var x = new OnlineOrder();
    Mapper.Map<OrderDto>(x);

The Map() line throws `AutoMapperMappingException` with the message: "Instances of abstract classes cannot be created".

**Comment by TylerCarlson1** [comment]
Did you call Mapper.Initialize()?

These are needed now in order for inheritance to work now.

**Comment by rmja** [comment]
Yes. After I have setup the mappings with `Mapper.CreateMap()`, I am running the following before I use `Mapper.Map()`:

    Mapper.Initialize(config =>
            {
                config.ConstructServicesUsing(type =>
                {
                    return serviceProvider.GetService(type);
                });
            });
    Mapper.AssertConfigurationIsValid();

**Comment by jbogard** [comment]
So Initialize resets the configuration. Put those CreateMap calls inside
Initialize, config.CreateMap

**Comment by rmja** [comment]
Ahh, got it. It works, thanks!

**Comment by mikebridge** [comment]
Should the [documentation](https://github.com/AutoMapper/AutoMapper/wiki/Configuration) be updated so it says that Initialize() is mandatory, not "preferred"?
