### ISSUE TITLE
.Include<> regression between 4.0-cli1052 and 4.0-cli1053 for dynamic proxies

### ISSUE THREAD

**Issue by cherrydev** [AutoMapper/AutoMapper#723]
So, first of all, I discovered that you now have to `Seal()` your configuration (or use `Mapper.Initialize` if you're using the static configuration) otherwise you get `Instances of abstract classes cannot be created.` errors with inheritance mapping now.  After I fixed that, I'm still getting the same error, but now only when the source object is an EF6 dynamic proxy.  Using the full `Map<TSource,TDest>()` invocation instead of the shortcut `Map<TDest>()` does not fix it.  So, as of now, cli1053 and newer are broken with no known workaround I can find.

**Comment by cherrydev** [comment]
This is caused by issue #724.

**Comment by jbogard** [comment]
Is this one good now? And I'm not sure about Seal - I think that's only in the case of inherited mappings.

**Comment by jbogard** [comment]
Looks good for me.
