### ISSUE TITLE
Automapper access the getter of destination in mapping

### ISSUE THREAD

**Issue by mcsdodo** [AutoMapper/AutoMapper#726]
The issue mentioned in https://github.com/AutoMapper/AutoMapper/issues/356 still persists. Is there any workaround in Automapper v3.2 ?

**Comment by jbogard** [comment]
Does DoNotUseDestinationValue workaround not work?

**Comment by mcsdodo** [comment]
Ah yes, my fault. Just a question: should not this be the default behaviour?

**Comment by jbogard** [comment]
Flip a coin I think. Lots of people like it, lots of people don't.

**Comment by mcsdodo** [comment]
Question remains, what's the default ... if I say map, I expect copy-paste-like' behavior without any surprises around. The less 'unexpected magic' the tool does, the better.

Anyway, thanks for the help.

**Comment by jbogard** [comment]
What do you mean copy paste?

So half the users expect one thing, half the other. Well, less than half,
since if you're using conditions or resolvers you expect to be able to
examine both sides.

**Comment by mcsdodo** [comment]
I mean getting from one object, setting to another object (without any intermediate actions, if not required).

**Comment by jbogard** [comment]
Ah, yes. That's actually something I'm looking at - not doing these extra
steps if you haven't added anything to the pipeline that would require it.

**Comment by KevinDjordjevic** [comment]
So what is the default behavior as of 5.0.0-ci-1049? I am noticing the getters of my destination object are being called, and it is causing me grief.

**Comment by jbogard** [comment]
Just curious, why is calling getters of DTO causing you grief?

**Comment by KevinDjordjevic** [comment]
Here is the situation:

I'm mapping SourceDTO to DestinationDTO.

```
    public class BaseClass
    {
        
    }

    public class DerivedClass : BaseClass
    {
        
    }

    public class DestinationDTO : SourceDTO
    {
        public new DerivedClass Property
        {
            get { return (DerivedClass)base.Property; }
            set { base.Property = value; }
        }
    }

    public class SourceDTO
    {
        public BaseClass Property { get; set; }
    }
```

When the getter is called, I get a System.InvalidCastException. For some reason base.Property has been set as type BaseClass, which is not possible if using the setter of DestinationDTO to set the value of the property.

**Comment by KevinDjordjevic** [comment]
I thought I may be able to work around the problem with the following:

```
new MapperConfiguration(cfg =>
{
     cfg
     .CreateMap<SourceDTO, DestinationDTO>()
     .ForAllMembers(opt => opt.DoNotUseDestinationValue());
}
```
But it throws an exception when the action is invoked. Has anybody been having problems with .ForAllMembers or DoNotUseDestinationValue( )?
