### ISSUE TITLE
Nullable child objects while using Project<>

### ISSUE THREAD

**Issue by kyberias** [AutoMapper/AutoMapper#728]
The following StackOverflow question summarizes this issue well:

http://stackoverflow.com/questions/25295404/can-automapper-handle-nullable-child-objects-in-a-mapped-source-model-using-ef

Are there some fundamental reasons why this isn't supported or any plans to support it?

My example is the following:

Entity framework:
```
class MainEntity
{
  ChildEntity Child { get; set;}
}
```
Mapping target type:
```
class Main
{
   Child { get; set; }
}
```
Mappings:
```
CreateMap<MainEntity,Main>()
  .ForMember(m => m.Child, o => o.MapFrom(t => t.Child));

CreateMap<ChildEntity,Child>()
  .ForMember(m => ... };
```
If we now do `mapper.Project<MainEntity,Main>(...)` we probably get the following error from EF:

Unable to create a null constant value of type '...'. Only entity types, enumeration types or primitive types are supported in this context.

**Comment by jbogard** [comment]
First of all, you don't need that MapFrom. If the names are the same, MapFrom is redundant.

I do this sort of mapping all the time. However, nearly all of the time I flatten child entities:

```
public class Main {
    public string ChildValue { get; set; }
}
```

My first suggestion would be to prefer flattening your child entities. I flatten everything as much as I can, except for child collections. Everything else, flatten.

**Comment by kyberias** [comment]
I'm aware of MapFrom redundancy in the example. However, it's not relevant to the issue.

Also, I understand that flattening is possible and might be preferable, but I'm asking whether the approach in my example could be made possible as well. There seems to be a limitation in AutoMapper with regards to this approach.

In certain cases where the child entity contains a lot of fields and the inclusion to the parent entity is optional, I think it would be clearer to have a child entity in the target type as well. This makes it possible to have a null value to notate missing child entity.

**Comment by jbogard** [comment]
Here's what I do to test this - create a Select projection without AutoMapper. Replace the Project().To with just a Select(), manually projecting your source entities to your DTO. Can you try that?

**Comment by GusGus2008** [comment]
Did anyone fix this bug or make a plan? It's really annoying!

**Comment by jbogard** [comment]
Do this - create a Select projection WITHOUT AutoMapper. If you get one that works, post it here.

`DbContext.Employees.Where(e => e.Something == "Foo").Select(e => new EmployeeDto {
   //magic.gif
}).ToList();`

That's literally the only way I can debug this. Give me source/destination types, and a Select projection that works.

**Comment by jbogard** [comment]
:panda_face:

**Comment by sanderd** [comment]
@jbogard sorry for posting on this issue, as it's been closed.
I've had to deal with very similar issues on a current project using EF5 (with dreaded edmx), just days ago.

See for an example below.
Upgrading to EF6 does seems to fix the issue, but unfortunately, not realistic for my case.

EF5: https://github.com/sanderd/automapper-issue-728/tree/master
EF6: https://github.com/sanderd/automapper-issue-728/tree/ef6

**Comment by tashen247** [comment]
upgrading to EF6 hasnt help me overcome this issue. Please help

**Comment by jbogard** [comment]
@tashen247 if you have a new issue please open one
