### ISSUE TITLE
nuget version update

### ISSUE THREAD

**Issue by d4e666** [AutoMapper/AutoMapper#729]
When I install automapper using nuget, I get version 2.2.1 installed. If I use the version tag, I get the message that this version is not available. Can you please update the nuget installer to match the latest version. The latest release already installed as a package is 3.2.0

**Comment by jbogard** [comment]
What version of .NET and NuGet are you using?

**Comment by d4e666** [comment]
I use VS2015 with .NET 4.6 and the latest nuget version
