### ISSUE TITLE
 IDataRecord sources and Mapper.AssertConfigurationIsValid()

### ISSUE THREAD

**Issue by thollowell** [AutoMapper/AutoMapper#730]
We have several DTO types we are mapping from IDataRecords. After we wire up our maps, we call Mapper.AssertConfigurationIsValid(). This throws an exception, noting that all of our properties are unmapped from type IDataRecord to T, where T is our DTO type.

Looking at the source code in IDictionary.cs code, the IsDataRecordType Func<> always returns false. This method is invoked from the ConfigurationStore.ShouldCheckMap() call, and it appears the intent was to bypass map configuration validation on a IDataRecord source. 

Is Mapper.AssertConfigurationIsValid() supported when the map definitions contain IDataRecord sources?

**Comment by jbogard** [comment]
No, it's not.
