### ISSUE TITLE
unable to map type with default guid value?

### ISSUE THREAD

**Issue by elran** [AutoMapper/AutoMapper#731]
if you have such a constructor 

public Test3(Guid guid = default(Guid))
        {
            _someMember = guid;
        }

the AutoMapper is Throwing an exception upon Map or when trying to
build a Constructor map.

**Comment by jbogard** [comment]
Yep, default parameter values are a compiler trick. All AutoMapper sees in the type metadata is a single constructor that expects a Guid as a parameter.

**Comment by elran** [comment]
Thanks jbogard
so any ideas to get over this problem?

**Comment by jbogard** [comment]
What would the intended behavior be? To use a no-arg constructor with a default value?

**Comment by elran** [comment]
no, but to take the optional value that defined in ctor

**Comment by jbogard** [comment]
So something like this:
```
Mapper.CreateMap<Foo, FooDto>().ConstructUsing(src => new FooDto());
```
? That uses the optional value defined in the ctor.

**Comment by elran** [comment]
Thanks,
i will try that.
