### ISSUE TITLE
Better error message when cannot find property

### ISSUE THREAD

**Issue by JakeGinnivan** [AutoMapper/AutoMapper#733]
I am mapping to a type which has properties with no getters, so I have to use strings to specify the property names.

`.MapFrom("Foo", ...);`

When `Foo` doesn't exist there is a null reference exception, it would be great to catch this and wrap it so I know which property no longer exists.

**Comment by lbargaoanu** [comment]
ArgumentOutOfRangeException seems appropriate.

**Comment by jbogard** [comment]
Fixed!
