### ISSUE TITLE
AssertConfigurationIsValid hangs on recursive classes.

### ISSUE THREAD

**Issue by KenVanGilbergen** [AutoMapper/AutoMapper#734]
We are mapping a data model and it turns out there are some class that reference in a circular manner. We do not need all the mappings, but when we try to assert I assume it turns in circles and therefor the test never ends.

How do I prevent the test from running forever?
Or does the AssertConfigurationIsValid needs updating to check cases like this?
```
public class MyRecursiveClass
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
        public MyRecursiveClass MyClass { get; set; }
    }

    public class MyOtherRecursiveClass
    {
        public int MyInt { get; set; }
        public string MyString { get; set; }
        public MyOtherRecursiveClass MyRecursiveClass { get; set; }
    }

 [Fact]
        public void ShouldHandleRecursiveMapping()
        {
            Mapper.CreateMap<MyRecursiveClass, MyOtherRecursiveClass>();
            Mapper.AssertConfigurationIsValid();
        }
```

**Comment by lbargaoanu** [comment]
I'm unable to reproduce your result using the develop branch. Your example as it is breaks with a mapping error and if I rename MyOtherRecursiveClass.MyRecursiveClass to MyClass, the test passes. Maybe I'm missing something.

**Comment by KenVanGilbergen** [comment]
I now also get the mapping errors I expected instead of the test hanging. Maybe it was an issue with the runner.
