### ISSUE TITLE
DataRow to Object conversion

### ISSUE THREAD

**Issue by hanu412** [AutoMapper/AutoMapper#735]
Will I be able to use AutoMapper to convert a datarow into an object of a class? 

Currently I am using this code.. I have some fields as required. If these fields are NULL in the database,I want to safely discard that particular row.  Any thoughts/suggestions?

public static class CommonUtility<TEntity> where TEntity : new()
        {

        /// <summary>
        /// Use this to get the entity.
        /// This method will fail,if there property value is a null.
        /// </summary>
        /// <param name="dataRow"></param>
        /// <returns>"Tentity"</returns>
        public static TEntity GetEntity(DataRow dataRow)
            {

            TEntity tentity = new TEntity();
            Type entityType = typeof(TEntity);
            PropertyInfo[] propertyInfo = entityType.GetProperties();
            foreach (PropertyInfo property in propertyInfo)
                {
                if (!string.Equals(property.Name.ToUpper(), "FILLER"))
                    {
                    tentity.GetType().GetProperty(property.Name.ToString()).SetValue(tentity, dataRow[property.Name.ToString()]);
                    }
                }
            return tentity;
            }

        /// <summary>
        /// Use this method if database null values are to be handled.
        /// </summary>
        /// <param name="dataRow"></param>
        /// <param name="handleDataBaseNull"></param>
        /// <returns>"Tentity"</returns>
        public static TEntity GetEntity(DataRow dataRow, bool handleDataBaseNull)
            {
            TEntity tentity = new TEntity();
            if (handleDataBaseNull)
                {
                Type entityType = typeof(TEntity);
                PropertyInfo[] propertyInfo = entityType.GetProperties();
                foreach (PropertyInfo property in propertyInfo)
                    {
                    tentity.GetType().GetProperty(property.Name.ToString()).SetValue(tentity, ApplyValue(dataRow, property));

                    }
                }

            else
                {

                tentity = GetEntity(dataRow);
                }

            return tentity;
            }

        //This method needs to be re-looked.
        /// <summary>
        /// This method will check if the values is a NULL.
        /// If it is null,it will return an empty string/default value of the type else the value.
        /// </summary>
        /// <param name="dataRow"></param>
        /// <param name="property"></param>
        /// <returns>Property Value</returns>
        private static object ApplyValue(DataRow dataRow, PropertyInfo property)
            {
            if (dataRow[property.Name.ToString()] == DBNull.Value || string.IsNullOrWhiteSpace(dataRow[property.Name.ToString()].ToString()))
                {
                var value = DBNull.Value;
                var type = property.PropertyType;

                if (type.Name.ToUpper() == "STRING")
                    {
                    return "0";
                    }
                else if (type.Name.ToUpper() == "INT32")
                    {
                    return 0;
                    }
                else if (type.Name.ToUpper() == "DECIMAL")
                    {
                    return 0;
                    }
                else if (type.Name.ToUpper() == "DATETIME")
                    {

                    return DateTime.Now.Date.ToShortDateString();

                    }
                else
                    {
                    return 0;
                    }

                }
            else
                {
                return dataRow[property.Name];
                }
            }
}

**Comment by jbogard** [comment]
No, AutoMapper doesn't support this scenario.
