### ISSUE TITLE
Unexpected behavior of AllowNullDestinationValues and Map<T>(object)

### ISSUE THREAD

**Issue by Serenyrddraig** [AutoMapper/AutoMapper#737]
I discovered the following unexpected (by me) behavior, but I have not yet debugged Automapper itself. Consider the following.

var ConfigurationStore = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);
// add maps for types To and From
var engine = new MappingEngine(ConfigurationStore);
ConfigurationStore.AllowNullDestinationValues = false;

var result1 = engine.Map<From, To>(null); // produces a To
var result2 = engine.Map<To>(null); // produces a null; I expected a To

**Comment by lbargaoanu** [comment]
A full, executable example would be useful.

**Comment by Serenyrddraig** [comment]
No problem. Should I send it directly to you or attach it to the issue?

BTW: I’ve subsequently looked at the source and the implementation of these two methods is quite different. In the two argument case (Map<TS,TD>) an attempt to find the matching TypeMap is made, and if found, normal mapping occurs. In the one argument case the default constructor logic appears to use unconditionally.

**Comment by lbargaoanu** [comment]
Just please post here a message with the source code.

**Comment by Serenyrddraig** [comment]
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using AutoMapper;
using AutoMapper.Mappers;

namespace NullSourceInstance
{
    public class From
    {
        public string Member { get; set; }
    }

    public class To
    {

        public string Member { get; set; }
    }
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestNullSourceInstance()
        {
            var store = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);
            store.AllowNullDestinationValues = false;
            store.CreateMap<From, To>();

            var factory = new MappingEngine(store);
            var result = factory.Map<From, To>(null);
            Assert.IsNotNull(result);
            Assert.IsInstanceOfType(result, typeof(To));
            var result1 = factory.Map<To>(null);
            Assert.IsNotNull(result);  // fails here
            Assert.IsInstanceOfType(result, typeof(To));
        }
    }
}

**Comment by lbargaoanu** [comment]
I see your point now. The Map<TDestination> takes object as its parameter so when it receives null it has no way of knowing the type you intended, that's why it doesn't go the usual route. The test could work as expected if TDestination has a default constructor, but it would need to called through reflection. I'm not sure if it's worth the trouble. @jbogard should decide.

**Comment by Serenyrddraig** [comment]
I ran into this issue while I was creating an Automapper backed object factory. In my particular case, I resolved this issue by selecting a TypeMap with the appropriate destination and then reflectively calling Map<TS, TD>(null) from the implementation of my version of Map<TD>. This may not work in the general case since there may be more than one such map and some may have opts controlling the population of TD; in my case there is only one such TypeMap.

**Comment by jbogard** [comment]
Weird case. I'm actually cool with this failing. In fact, I'd almost say I should throw an exception because the source value is null.

**Comment by lbargaoanu** [comment]
@jbogard Weird indeed. But it's not consistent. When you know the source type does one thing, when you don't another. Not sure it's worth wasting more cycles on this, but the man has a point :)

**Comment by jbogard** [comment]
Just thinking it's more obvious behavior for `Mapper.Map<TDestination>(object source)` should throw an `ArgumentNullException` when the source object, which is used to determine source type, is missing. I don't do many argument checks.

**Comment by lbargaoanu** [comment]
@jbogard Now I get it. So we want to say that the behavior is different because we have to know both the source and the destination type. But how many people would this break, if we add the check now? :) Than I guess the wise thing to do is to close the issue.

**Comment by Serenyrddraig** [comment]
Consistency is a b__ch. Personally, I'd vote for calling the default constructor of TDestination (if possible) depending on the setting of AllowNullDestinationValues before resorting to an exception. Alternatively, under the covers, you could call the Map with two generic arguments, i.e. 
Map<TDestination>(source) { ... if (null == source) { return Map<object, TDestination>(source); }  which appears to respect the AllowNullDestinationValues already.

**Comment by jbogard** [comment]
@Serenyrddraig And to me that behavior seems nonsensical - you're trying to perform a mapping, and you've provided insufficient information to do so. Don't use the overload that requires a source object to map if you don't have a source object.

**Comment by Serenyrddraig** [comment]
From the point of view of Map, I concede the point. I guess I'm expecting too much 'factory' behavior in this case. BTW my suggestion above has a typo (... if (null==source) return Map<object, TDestination>(source);  ) was what I intended. 

Thanks.
