### ISSUE TITLE
Latest pre-release build on NuGet has invalid dependency versions in Visual Studio 2015 RC1.

### ISSUE THREAD

**Issue by hybridview** [AutoMapper/AutoMapper#739]
Build is 4.4.0-ci1058

I am building an ASP.NET MVC 6 project using Visual Studio 2015 RC1.

On loading the latest pre-release from Nuget, the package failed to find any of the dependencies because NuGet could not resolve versions "*-beta-22822" of those dependencies. I manually loaded a list of "latest" versions of these dependencies from NUGET (The urls were nicely dumped into my output console) to find the versions that were available. The latest version of all of these dependencies at this time are "*-beta-22816". 

I opened the AutoMapper NuGet package and manually modified the dependency versions to 22816. This resolved the issue. I suppose there must be a better way to resolve these beta dependencies, but this worked for me as a temporary fix.

NOTE: I had a ton of trouble getting my solution to use my "hacked" nuget package instead of the  cached version. In the end, I just incremented the version of the nuget package to get it to work, which means I might have to uninstall first before updating to a working version of AutoMapper from NUGET.

**Comment by jbogard** [comment]
Alpha1 goes against the official pre-release versions.
