### ISSUE TITLE
MapFrom subquery unexpected (incorrect) result

### ISSUE THREAD

**Issue by mnemanov** [AutoMapper/AutoMapper#742]
see this question in StackOverflow:
http://stackoverflow.com/questions/30873041/automapper-mapfrom-subquery

it was suggested in the comments that I should post here as it may be a bug.

TY

**Comment by TylerCarlson1** [comment]
It looks like the parameter replacement visitor is replacing all parameters, not specifically the src implementation.  u is a parameter, all be it from a sub lambda, but that's getting replaced along with src.

Definitely a bug imo.

**Comment by jbogard** [comment]
Yeah, bug. Derp.

**Comment by jbogard** [comment]
Fixed!

**Comment by mnemanov** [comment]
Thank you.

Noticed your commit says 'fixed 752', perhaps you intended to write 742?

Not sure where to put this feature request, but it's relevant here: if we could reference the dbcontext in the automapper config without resorting to a parameterized query it would be nice.

And dumb question number 1: do I now just update the automapper in my project via nuget and I'll have the fix? (I checked and it has version 4.0.0 available, can I just update my version 3.3 to version 4, I assume it should be fully backwards compatible, is there anything I should read before moving to version 4?)

Thanks again.

MN

**Comment by jbogard** [comment]
Yeah I messed up the commit message. I'm writing up release notes right now - no breaking changes though.

As for the DBContext thing - AutoMapper has no reference/knowledge to DBContext.
