### ISSUE TITLE
Update EF collection related entities

### ISSUE THREAD

**Issue by oswaldomilet** [AutoMapper/AutoMapper#746]
I found this very interesting article: http://bzbetty.blogspot.com.br/2012/06/updating-collections-using-automapper.html showing how to update entities children.

However, I'm lost in the missing part about creating an IObjectMapper, could someone help me?

Thanks

**Comment by TylerCarlson1** [comment]
I allready have a PR of implementation is #528
Wasn't changing so moved it to https://github.com/TylerCarlson1/Automapper.Collection

ReadMe explains how to use and can do things like use Primary Key of the EF object to determine equivalency between a DTO and an EF object using the property maps.
Also you can overwrite it with your own equivalency between the DTO and EF object if you need to.

**Comment by TylerCarlson1** [comment]
So was this help full?

**Comment by oswaldomilet** [comment]
@TylerCarlson1 Sorry for late response, it's in my pending list to test and as soon as possible I'll give a feedback to this Issue ok? As I guess you did a great job I'll close this Issue and reopen if any problem in future with your code ok? tks
