### ISSUE TITLE
Mapping Class and Base Class to ViewModels

### ISSUE THREAD

**Issue by TDK1964** [AutoMapper/AutoMapper#748]
I am using AutoMapper to map between my models and view models then back again when I'm updating. When I edit an item the mapping appears to work and the CreatedDate is returned and displayed on the page. However, when that edited item is saved I get a SQL error basically saying the CreatedDate must be a date between x and y because the view models CreatedDate is missing. So I'm guessing the mappings aren't correct. Any help would be appreciated. Here's my example.
```
// Entities
public class Audit {
    public DateTime DateCreated { get; set; }
    public int CreatedBy { get; set; }
    public DateTime? DateModified { get; set; }
    public int? Modifiedby { get; set; }  
}

public class Course : Audit {
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal? Duration { get; set; }
}

//ViewModels
public class AuditViewModel {
    public DateTime DateCreated { get; set; }
    public int CreatedBy { get; set; }
    public DateTime? DateModified { get; set; }
    public int? Modifiedby { get; set; }    
}

public class CourseViewModel : AuditViewModel {
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Duration { get; set; }
}

// Mappings
Mapper.CreateMap<Course, CourseViewModel>();
Mapper.CreateMap<Audit, AuditViewModel>()
    .Include<Course, CourseViewModel>();

Mapper.CreateMap<CourseViewModel, Course>();
Mapper.CreateMap<AuditViewModel, Audit>()
    .Include<CourseViewModel, Course>();
    
// Usage
public ActionResult Edit(int id)
{
    var course = _courseRepository.GetById(id);
    var mapped = Mapper.Map<Course, CourseViewModel>(course);  
    return View(mapped);
}

[HttpPost]
public ActionResult Edit(int id, CourseViewModel viewModel)
{
    var course = _courseRepository.GetById(viewModel.Id);
    Mapper.Map(viewModel, course);
    _courseRepository.Update(course);
    return RedirectToAction("List");
}
```

**Comment by jbogard** [comment]
You shouldn't need the Include for one - that's for inheriting base config options like MapFrom. Is the course view model really supposed to fill in all that stuff for auditing? Typically my auditing data gets filled in via infrastructure (like overriding SaveChanges in DbContext).

**Comment by TDK1964** [comment]
Jimmy, thanks for the reply. Maybe I did explain very well. My audit class has the common properties used with all other classes. When I display the course details on the screen I also want to display the four properties from audit. When editing I use the CourseViewModel object and map Course to CourseViewModel but doing this on it's own would exclude the Audit properties. So my edit view should have course and audit properties available to it.

**Comment by jbogard** [comment]
So not on the POST side? I wouldn't expect to have those posted up.

**Comment by jbogard** [comment]
So you should be able to use Ignore here on the mappings back to the actual persisted entities.
