### ISSUE TITLE
AutoMapper.targets causing duplicate item error using Web Publishing

### ISSUE THREAD

**Issue by flcdrg** [AutoMapper/AutoMapper#749]
Given an ASP.NET project that references the AutoMaper NuGet package.
Compile the project using the following:

`msbuild /p:DeployOnBuild=true /p:EnablePackageProcessLoggingAndAssert=true`

Results in an error being logged similar to the following (error reformatted for your viewing pleasure!)

        (PipelineCollectFilesPhase target) -> 
    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(1289,5): error : The following two items have duplicate item metadata %(DestinationRelativePath). The two items data are 

    <Item Name="C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll">
        <DestinationRelativePath>bin\AutoMapper.Net4.dll</DestinationRelativePath>
        <Exclude>False</Exclude>
        <FromTarget>CollectFilesFromReference</FromTarget>
        <Category>Run</Category>
        <ProjectFileType>Default</ProjectFileType>
        <ResolvedFrom>{HintPathFromItem}</ResolvedFrom>
        <CopyLocal>true</CopyLocal>
        <FusionName>AutoMapper.Net4, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005</FusionName>
        <ImageRuntime>v4.0.30319</ImageRuntime>
        <SpecificVersion>False</SpecificVersion>
        <HintPath>..\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll</HintPath>
        <OriginalItemSpec>AutoMapper.Net4, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, processorArchitecture=MSIL</OriginalItemSpec>
        <Version>3.3.1.0</Version>
        <ReferenceSourceTarget>ResolveAssemblyReference</ReferenceSourceTarget>
        <FullPath>C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll</FullPath>
        <RootDir>C:\</RootDir>
        <Filename>AutoMapper.Net4</Filename>
        <Extension>.dll</Extension>
        <RelativeDir>C:\Example\packages\AutoMapper.3.3.1\lib\net40\</RelativeDir>
        <Directory>Example\packages\AutoMapper.3.3.1\lib\net40\</Directory>
        <RecursiveDir/>
        <Identity>C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll</Identity>
        <ModifiedTime>2015-03-04 14:04:57.7495849</ModifiedTime>
        <CreatedTime>2015-03-04 14:04:57.7495849</CreatedTime>
        <AccessedTime>2015-03-04 14:04:57.7495849</AccessedTime>
        <DefiningProjectFullPath>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\CollectFiles\Microsoft.Web.Publishing.OnlyFilesToRunTheApp.targets</DefiningProjectFullPath>
        <DefiningProjectDirectory>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\CollectFiles\</DefiningProjectDirectory>
        <DefiningProjectName>Microsoft.Web.Publishing.OnlyFilesToRunTheApp</DefiningProjectName>
        <DefiningProjectExtension>.targets</DefiningProjectExtension>
    </Item> and <Item Name="C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll">
        <DestinationRelativePath>bin\AutoMapper.Net4.dll</DestinationRelativePath>
        <Exclude>False</Exclude>
        <FromTarget>CollectFilesFrom_SourceItemsToCopyToOutputDirectory</FromTarget>
        <Category>Run</Category>
        <ProjectFileType>Default</ProjectFileType>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <TargetPath>AutoMapper.Net4.dll</TargetPath>
        <FullPath>C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll</FullPath>
        <RootDir>C:\</RootDir>
        <Filename>AutoMapper.Net4</Filename>
        <Extension>.dll</Extension>
        <RelativeDir>C:\Example\packages\AutoMapper.3.3.1\lib\net40\</RelativeDir>
        <Directory>Example\packages\AutoMapper.3.3.1\lib\net40\</Directory>
        <RecursiveDir/>
        <Identity>C:\Example\packages\AutoMapper.3.3.1\lib\net40\AutoMapper.Net4.dll</Identity>
        <ModifiedTime>2015-03-04 14:04:57.7495849</ModifiedTime>
        <CreatedTime>2015-03-04 14:04:57.7495849</CreatedTime>
        <AccessedTime>2015-03-04 14:04:57.7495849</AccessedTime>
        <DefiningProjectFullPath>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\CollectFiles\Microsoft.Web.Publishing.OnlyFilesToRunTheApp.targets</DefiningProjectFullPath>
        <DefiningProjectDirectory>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\CollectFiles\</DefiningProjectDirectory>
        <DefiningProjectName>Microsoft.Web.Publishing.OnlyFilesToRunTheApp</DefiningProjectName>
        <DefiningProjectExtension>.targets</DefiningProjectExtension>
    </Item>.

**Comment by jbogard** [comment]
This is all going away in 4.0 since I'm collapsing assemblies and removing
the install.ps1. You can try the prerelease, I'm also releasing an alpha
shortly.

**Comment by flcdrg** [comment]
Sounds good.

I'm curious as to what the purpose of the AutoMapper.targets was - did it do anything different to what the builtin .targets files were doing to copy references?

**Comment by jbogard** [comment]
Yes - msbuild doesn't copy references you add but don't have code that directly uses it. Highly annoying.

**Comment by jbogard** [comment]
Fixed with one assembly
