### ISSUE TITLE
Map List<Foo> to List<FooModel> fails

### ISSUE THREAD

**Issue by xplatsolutions** [AutoMapper/AutoMapper#752]
I have a configuration like below. 

The constructor of the FooModel object takes one parameter and I instruct this when mapping from class to class, but I don't know if this the problem and how to instruct the mapper to construct when trying to map `List<Foo>` to `List<FooModel>`.

    Mapper.CreateMap<Foo, FooModel>()
                   .ConstructUsing((Func<Foo, FooModel>)(l => new FooModel(this)));
    Mapper.CreateMap<FooModel, Foo>();
    Mapper.CreateMap<List<Foo>, List<FooModel>>();

Somewhere in the code (not really far in a galaxy though).

    IEnumerable<Foo> fooEnumerable = await _fooRepository.FindAsync(expression);
    List<Foo> fooList = new List<Foo>(fooEnumerable); // 2 items count
    List<FooModel> fooModels =
    Mapper.Map<List<Foo>, List<FooModel>>(fooList); // Here I get 0 items count
    return new ObservableCollection<FooModel>(fooModels); // return Observable, as far as I know, it's not supported.

**Comment by lbargaoanu** [comment]
Just remove the List mapping.

    Mapper.CreateMap<List<Foo>, List<FooModel>>();

**Comment by jbogard** [comment]
^ this

Lists and most other collection types are mapped automatically.

**Comment by xplatsolutions** [comment]
Yeah, I guess when I was trying this solution it didn't work due to a clean/rebuild needed!

**Comment by lbargaoanu** [comment]
@jbogard A mix-up of issue numbers? I think this should be closed, the fix was for #742.

**Comment by jbogard** [comment]
Yep. I don't know why I reopened it, probably wonky click.
