### ISSUE TITLE
nuget of VS2015 RC crashes with AutoMapper

### ISSUE THREAD

**Issue by yyjdelete** [AutoMapper/AutoMapper#754]
Tested with 4.0.0-ci1061/3.3.1
When Install AutoMapper or update any nuget package in an project which using AutoMapper(install in VS2013), the VS crash...

**Comment by garora** [comment]
@yyjdelete - where did you get the issue. I believe I've the latest version and its working fine. Although I just pushed my NugetPackage to Nuget.org.

**Comment by yyjdelete** [comment]
```
Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package AutoMapper
Attempting to gather dependencies information for package 'AutoMapper.3.3.1' with respect to project 
targeting '.NETFramework, Version=v4.5.2'
```
It just crash with no msg.

----
But it's interesting that I found when I disable the default package sources in VS2015
[api.nuget.org](https://api.nuget.org/v3/index.json), and enable the old source [nuget.org](https://www.nuget.org/api/v2/), it works well...

**Comment by garora** [comment]
Its weird! It should work in any case. Lets wait if other faced this issue. 
Good to know that its working for you now :)

**Comment by yyjdelete** [comment]
Capture with Fiddler, and finally found it failed with
http://api.nuget.org/v3/registration0/automapper/index.json
->
http://api.nuget.org/v3/registration0/automapper/page/1.1.0.118/3.1.0-ci1035.json
->
automapper/2.2.1-ci4
catalogEntry/dependencyGroups/.NETFramework3.5, which has an dependency with the same id as AutoMapper itself.

===
Unknown why that it works with Nuget 2.x but crash 3.x, just leave this as some info.

**Comment by jbogard** [comment]
Turn off the V3 Nuget API in VS. That should fix it.

**Comment by jsk** [comment]
>Lets wait if other faced this issue. 
I can confirm this issue as well - VS 2015 RC.
As jbogard suggested, turning of V3 Nuget API fixed the issue.

**Comment by jbogard** [comment]
So V3 of the NuGet API is just jacked up. Confirmed!

**Comment by yyjdelete** [comment]
Seems resolved in VS 2015 rel.
