### ISSUE TITLE
Mapping inheritance doesn't seem to work with same source object mapped to ViewModels with inheritance

### ISSUE THREAD

**Issue by mrchief** [AutoMapper/AutoMapper#756]
In the [documentation](https://github.com/AutoMapper/AutoMapper/wiki/Mapping-inheritance), both source and destination have base classes and derived ones too. However in the following case, inheritance mapping seems to fail:

```csharp

// src
public class Child
{	
    public long Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    public bool IsInDayCare { get; set; }
    public string Allergy { get; set; }
    public DateTime? CheckInTime { get; set; }
    public DateTime? CheckOutTime { get; set; }
}

// view models
public class MinimalChildViewModel
{	
    public long Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class FullChildViewModel : MinimalChildViewModel
{	
    public bool IsInDayCare { get; set; }
    public string Allergy { get; set; }
    public DateTime? CheckInTime { get; set; }
    public DateTime? CheckOutTime { get; set; }
}


// mappers

CreateMap<Child, MinimalChildViewModel>();

CreateMap<Child, FullChildViewModel >()
                .IncludeBase<Child, MinimalChildViewModel>();
```
Running a `Mapper.AssertConfigurationIsValid();` complains about unmapped members (`Id`, `FirstName`, `LastName`).

So my guess is that unless both src/dest have bases, mapper inheritance doesn't seem to work.

Thoughts?

**Comment by jbogard** [comment]
This works for me just fine:

https://dotnetfiddle.net/xE8iq1

**Comment by mrchief** [comment]
The fiddle page doesn't load. Temporary issue with the site?

**Comment by mrchief** [comment]
So the fiddle runs indeed. I'll have to check what else is different in my codebase then. Thanks for this. Will re-open if needed.
