### ISSUE TITLE
ResolutionContext needs to be DI friendly

### ISSUE THREAD

**Issue by hosadoya** [AutoMapper/AutoMapper#761]
In order to unit test converters in isolation, currently we have to construct real ResolutionContext object instead of being able to mock one, and register and use the Mapper. This forces us to test more than what we need to test (the converter).

Can we have ResolutionContext inherit an interface IResolutionContext to comply with DIP (Dependency Inversion Principle)?

Either of those options should work:

Option 1:
interface IResolutionContext : IEquatable&lt;IResolutionContext&gt;
class ResolutionContext : IResolutionContext

Option 2: (this is preferred since it complies with ISP (Interface Segregation Principle))
interface IResolutionContext
class ResolutionContext : IResolutionContext, IEquatable&lt;IResolutionContext&gt;

**Comment by jbogard** [comment]
Mock resolution context? It's a value object, you don't mock it. It's like mocking `string` or `int` or `Tuple`. It's not a service, it just holds data. You should just "new" it up and use that.
