### ISSUE TITLE
Is this a bug or by design?.

### ISSUE THREAD

**Issue by deltajesus** [AutoMapper/AutoMapper#764]
Hi.

I am about to write code that Merge an object into another object. Most of the logic will be only mapping between the 2 objects, but for some cases there need to be more business logic 
Implemented to validate data in the new and the old object to verify if data should be overwritten.

So I have written a generic MergeConverter that looks like this…

    public class MergeConverter<TSource, TDestination> : ITypeConverter<TSource, TDestination>
        where TSource : class
        where TDestination : IMerge<TSource, TDestination>, new()
    {
        //-- Methods
        private TDestination Convert(ResolutionContext context)
        {
            var destination = context.DestinationValue as IMerge<TSource, TDestination>;
            var source = context.SourceValue as TSource;

            if (destination == null)
                destination = new TDestination();
         
            return destination.Merge(source);            
        }

        //-- ITypeConverter<TSource, TDestination> interface implementation
        TDestination ITypeConverter<TSource, TDestination>.Convert(ResolutionContext context)
        {
            return this.Convert(context);
        }
    }

            AutoMapper.Mapper.CreateMap<CDMSharedModel.Address, ODSSharedModel.Address>().ConvertUsing<MergeConverter<CDMSharedModel.Address, ODSSharedModel.Address>>();

So when automapper should map from CDMSharedModel.Address to ODSSharedModel.Address it should use my MergeConverter.

The problem I see is that my destinationValue is always NULL even if there is data supplied to it. Check the below example.

Here I can see that the up in the chain I have a collection of “Party” (4 items) and if I check the first one I can see that it has value in the ‘Address’ property, also the ‘References’ and ‘Role’

![img1](https://cloud.githubusercontent.com/assets/4499283/8496513/0094a812-2176-11e5-81ce-a3f7d95e4bb1.png)

But if I go down one level to when it should map Party to Party I can see that my destination Party now has NULL as value in all its properties except the ID.

![img2](https://cloud.githubusercontent.com/assets/4499283/8496523/19c4d938-2176-11e5-9a13-0db90c8a9f3f.png)

Is the some kind of bug. Or shouldn’t I expect that the destinationValue has any value down the chain when I do a mapping from some top level object.

I have tried to a mapping like this

AutoMapper.Mapper.Map(sourceAddress, destinationAddress)

And I could see that the ‘destinationValue’ in the context was instanced.. But I don’t want to specify that on each object, only make some custom mapping with the MergeConverter() where is needed.

**Comment by jbogard** [comment]
Would it be possible to create a dotnetfiddle for this so that I can debug?

**Comment by deltajesus** [comment]
I think that could be a bit hard, there is a lot of company dll's that I am not sure that it's okay to do public... I was more curios if it was suppose to be NULL or that should have a values... It could be that I can try to track it more if I know that the value shouldn't be NULL.
