### ISSUE TITLE
Internal properties mapping and BindingFlags

### ISSUE THREAD

**Issue by chumakov-ilya** [AutoMapper/AutoMapper#767]
Hi! AutoMapper is a great tool!

BindingFlags feature is used to map internal properties. It was in 3.3.0 and disappeared in 3.3.1 but it is still in docs: https://github.com/AutoMapper/AutoMapper/wiki/Configuration#configuring-visibility

Does anybody know a workaround to map internal properties in 3.3.1?

Also is the using of BindingFlags not recommended, or it was removed for another reason? I mean may I stay on 3.3.0 and hope BindingFlags will return in future?

**Comment by jbogard** [comment]
I had to remove it since it wasn't supported in all platforms. I'm looking for an alternative in the meantime.

**Comment by risogolo** [comment]
Also there in 3.3.0 was one "issue", if you had not parameterless contsructor in your class, then it did not work, what I had to do, was to add a private constructor to that class. But I may be wrong and there is BindingFlags enum which will set the mapping the way that it will map the class even there is non parameterless contructor. I'm not sure...

**Comment by jbogard** [comment]
Fixed!

**Comment by chlang76** [comment]
This doesn't appear to be in the code base, or has it moved?
