### ISSUE TITLE
IDataReader, Mapping smallint to bool no error is thrown, bool value incorrect

### ISSUE THREAD

**Issue by whymatter** [AutoMapper/AutoMapper#775]
Hello,

first let me say, great project and perfect functionality.
But i have struggled with one "bug".
AutoMapper is using dynamic generated MSIL code to read from the IDataReader.
In out Database bool are representated by smallint (-1 = true, 0 = false) normaly no problem, when we cast the -1 or 0 to a bit (CAST(-1 AS Bit)).
But if we will not do that, than Automapper or. the generated MSIL recognize that the source (database-column) is a smallint (int16 in .net). The issue in this point is that no exception gets thrown!
The "callvirt" in MSIL writes the int16 -1 to the bool property! No Exception! But if you look in the memory, then the bool is not 0x01 or  0x00, its 0xFF, because the representation of -1 in binary is 0xFFFF. When comparing the resulting bool with the == operator then all works fine. But when we are comparing by "PropertyOnEntity".Equals(true) then the result is false even if "PropertyOnEntity" is true! The reason of that is the MSIL of the .Equals in the Boolean Class. Its convertig the bool to in Int32 and comparing it by 1. Really you really have to see this!

MSIL og Boolean.Equals(true):

	.method public hidebysig newslot virtual final 
			instance bool  Equals(bool obj) cil managed
	{
	  .custom instance void __DynamicallyInvokableAttribute::.ctor() = ( 01 00 00 00 ) 
	  // Code size       6 (0x6)
	  .maxstack  8
	  IL_0000:  ldarg.0
	  IL_0001:  ldind.u1
	  IL_0002:  ldarg.1
	  IL_0003:  ceq
	  IL_0005:  ret
	} // end of method Boolean::Equals

**Comment by lbargaoanu** [comment]
A minimal failing test would be nice :)

**Comment by whymatter** [comment]
Sure here the test:

            const string connectionString =
                "server=****;user id=****;password=****;database=****;MultipleActiveResultSets=True";

            using (var connection = new SqlConnection(connectionString))
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                
                command.CommandText =
                    "SELECT -1 AS CheckDispo";

                var sqlDataReader = (IDataReader) command.ExecuteReader();

                var resultList = Mapper.DynamicMap<List<Item>>(sqlDataReader);

                var a = resultList[0].CheckDispo.Equals(true); // false
                var b = resultList[0].CheckDispo == true; // true

                b.Should().BeTrue(); // works
                a.Should().BeTrue(); // fails
            }

![image](https://cloud.githubusercontent.com/assets/5569949/8596163/da01ca18-264d-11e5-8dbd-d355642c9f6e.png)

![image](https://cloud.githubusercontent.com/assets/5569949/8596180/f4e90e7c-264d-11e5-8ef5-3fee116e6efe.png)

![image](https://cloud.githubusercontent.com/assets/5569949/8596216/13b28bee-264e-11e5-8e98-39e22f58db96.png)

![image](https://cloud.githubusercontent.com/assets/5569949/8596256/534a886a-264e-11e5-953c-5594c7fd3325.png)

**Comment by jbogard** [comment]
Can you open this issue on the AutoMapper.Data repo? The IDataReader stuff is moving there.

**Comment by whymatter** [comment]
I have moved the issue to https://github.com/AutoMapper/AutoMapper.Data/issues/12.

**Comment by lbargaoanu** [comment]
I guess this should be closed.
