### ISSUE TITLE
Automapper Issue

### ISSUE THREAD

**Issue by ANIVEN97** [AutoMapper/AutoMapper#783]
Hi, I need hep with an Automapper issue on my machine. I have been getting mapping errors since 7/8/2015(seems to coincide with release of new version) for the mappings that were working fine before. Basically it's failing when mapping field type doesn't match to what is described in DTO. e.g: If DTO has a field declared as Guid and mapping field is set to String, it used to work but not anymore. I checked my references and it seems to be using the same version that I was using before(3.2.1.0).

If I change the field type to match with DTO it works. But the problem is that in order for the app to work on my local, I have to change all the references for all field types etc...which is impossible. So, wondering if I could get any help ASAP from Automapper team.

Thanks
AP

**Comment by lbargaoanu** [comment]
A failing test would be nice :)

**Comment by jbogard** [comment]
What was the old version and the new version? Do you have any code you can show?

**Comment by jbogard** [comment]
Closing without further details
