### ISSUE TITLE
Deep copy, reference issue

### ISSUE THREAD

**Issue by Mech0z** [AutoMapper/AutoMapper#787]
I wanted to make a deep copy so I did

```
public MyType Map(MyType objectInstance)
{
       return Engine.Map<MyType , MyType >(objectInstance);
}
```
but calling this just returned a reference to the same object

To fix this I had to do
```
configurationStore.CreateMap<MyType , MyType >();
```
Which makes sense, but I would like it to throw an exception instead of just returning a reference, I cant see how that would be useful? it just creates an illusion that your code is working.

**Comment by jbogard** [comment]
AutoMapper is not a deep copy/cloning library.

If one object is assignable to another, automapper simply assigns the
object, that's the most obvious and performant behavior.
