### ISSUE TITLE
IQueryable Extensions Exception

### ISSUE THREAD

**Issue by SamL1** [AutoMapper/AutoMapper#790]
I've been trying to implement a project with automapper for the first time, and I keep running into the same issue when writing queries and using the IQueriable extensions.

This is a simplified Dto model.
```
public class WidgetDto
{
    public int Id { get; set; }
    public string WidgetName { get; set; }
    public string Description { get; set; }
    public List&lt;WidgetCategoryDto&gt; WidgetCategories { get; set; }
}

public class CategoryDto
{
    public int Id { get; set; }
    public string CategoryName { get; set; }
    public List&lt;WidgetCategoryDto&gt; WidgetCategories { get; set; }
}

public class WidgetCategoryDto
{
    public int Id { get; set; }
    public int WidgetId { get; set; }
    public int CategoryId { get; set; }
    public CategoryDto Category { get; set; }
    public WidgetDto Widget { get; set; }
}
```
With a very simple mapping configuration.
```
Mapper.CreateMap<Widget, WidgetDto>.MaxDepth(3);
Mapper.CreateMap<WidgetCategory, WidgetCategoryDto>.MaxDepth(3);
Mapper.CreateMap<Category, CategoryDto>.MaxDepth(3);
```
If I write a very simple query then the exception occurs.
```
var db = new DbContext();

var query = db.Widgets
    .Project()
    .To&lt;WidgetDto&gt;()
    .ToList();
```
Additional information: The type 'Widget.WidgetCategoryDto' appears in two structurally incompatible initializations within a single LINQ to Entities query. A type can be initialized in two places in the same query, but only if the same properties are set in both places and those properties are set in the same order.

From what I've read, the expected behaviour is to eager load related mapped types to  recursive depth of 3.

However, I can't get the query to work without it throwing the above exception.

I would actually like to optionally expand sub types using a mapping configuration like so...
```
Mapper.CreateMap<Widget, WidgetDto>()
    .MaxDepth(3)
    .ForMember(dto => dto.WidgetCategories, opt => opt.ExplicitExpansion());

Mapper.CreateMap<WidgetCategory, WidgetCategoryDto>()
    .MaxDepth(3)
    .ForMember(dto => dto.Category, opt => opt.ExplicitExpansion())
    .ForMember(dto => dto.Widget, opt => opt.ExplicitExpansion());

Mapper.CreateMap<Category, CategoryDto>()
    .MaxDepth(3)
    .ForMember(dto => dto.WidgetCategories, opt => opt.ExplicitExpansion());

However, the following query also throws the same exception

var db = new DbContext();

var query = db.Widgets
    .Project()
    .To<WidgetDto>(null, 
         dto => dto.WidgetCategories, 
         dto => dto.WidgetCategories.Select(x => x.Category))
    .ToList();

Am I missing something?

**Comment by jbogard** [comment]
The way I would go about this is to create explicit DTO types for each
level of depth. It gets too confusing otherwise, and then your model shows
the depth level you want, not some AutoMapper config.

**Comment by SamL1** [comment]
Thanks for the quick response Jimmy.

My application domain model is obviously more complex that the example given, and I'd like to keep DTO maintenance to a minimum.

Is the solution you've described a 'standard' pattern in situations such as this, or is there something wrong about the way I'm designing my models?

Another question I have is, the plain entity framework equivalent to this query....

var query = db.Widgets

.Project()
.To<WidgetDto>(null, 
dto => dto.WidgetCategories, 
dto => dto.WidgetCategories.Select(x => x.Category))
.ToList();

Would be....

var db = new DbContext();

var query = db.Widgets
        .Include("WidgetCategories")
        .Include("WidgetCategories.Category")
        .ToList();

This works without issue, and only loads the requested items.

Is there an underlying reason why resulting expression are different?

**Comment by TylerCarlson1** [comment]
If you make your Dto objects like so
```
public class WidgetDto
{
public int Id { get; set; }
public string WidgetName { get; set; }
public string Description { get; set; }
public List<WidgetCategoryDto> WidgetCategories { get; set; }
}

public class CategoryDto
{
public int Id { get; set; }
public string CategoryName { get; set; }
//public List<WidgetCategoryDto> WidgetCategories { get; set; }
}

public class WidgetCategoryDto
{
public int Id { get; set; }
public int WidgetId { get; set; }
public int CategoryId { get; set; }
public CategoryDto Category { get; set; }
//public WidgetDto Widget { get; set; }
}
```
It should work.  The problem is commented out properties will cause an infinite loop when trying to Project.
Project makes a select statement, and DON'T use Include(), and you would have an infinitely long select statement.

IF you need those properties you need to make them separate Dto class for one level down and so on and so forth until you want to stop recursively going down the list,  where you wouldn't have the child property.

**Comment by SamL1** [comment]
Hi TylerCarlson1.

Isn't the MaxDepth method designed to limit recursive loads?

e.g. 

Mapper.CreateMap<Category, CategoryDto>()
.MaxDepth(3)
.ForMember(dto => dto.WidgetCategories, opt => opt.ExplicitExpansion());

**Comment by TylerCarlson1** [comment]
Don't know if max depth applies to Project()

But also if it does stop projection, then WidgetCategoryDto will have a different new statement with not all the same property setters, as a sub property of Catagory.  That's what the error is saying, so it sounds like the recursive nature of the mapping in general is the problem, not the amount of times it's recursively mapped.
Use a different type and there won't be 2 new WidgetCategoryDto statements made by project and won't get error.

**Comment by SamL1** [comment]
Will this work if the new type inherits from the primary DTO?

**Comment by TylerCarlson1** [comment]
No it can't because it still has infinite loops back onto itself.
The new class types can't have the looping properties.

For project to you shouldn't need to pass the lambdas, cause AutoMapper should handle that for you based on your mappings.

**Comment by SamL1** [comment]
I think I've got to grips with it now.

It is possible to use inheritance. The following model works for one additional level.

    public class WidgetDto
    {
        public int Id { get; set; }
        public string WidgetName { get; set; }
        public string Description { get; set; }
        public List<WidgetCategorySubDto> WidgetCategories { get; set; }
    }

    public class CategoryDto
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public List<WidgetCategorySubDto> WidgetCategories { get; set; }
    }

    public class WidgetCategoryDto
    {
        public int Id { get; set; }
        public int WidgetId { get; set; }
        public int CategoryId { get; set; }
        public CategorySubDto Category { get; set; }
        public WidgetSubDto Widget { get; set; }
    }

    public class CategorySubDto : CategoryDto
    {        
    }

    public class WidgetCategorySubDto : WidgetCategoryDto
    {
    }

    public class WidgetSubDto : WidgetDto
    {        
    }

When using the following mapping configuration

    Mapper.CreateMap<Widget, WidgetDto>();

    Mapper.CreateMap<Widget, WidgetSubDto>()
        .ForMember(dto => dto.WidgetCategories, opt => opt.Ignore());

    Mapper.CreateMap<WidgetCategory, WidgetCategoryDto>();

    Mapper.CreateMap<WidgetCategory, WidgetCategorySubDto>()
        .ForMember(dto => dto.Category, opt => opt.Ignore())
        .ForMember(dto => dto.Widget, opt => opt.Ignore());

    Mapper.CreateMap<Category, CategoryDto>();

    Mapper.CreateMap<Category, CategorySubDto>()
        .ForMember(dto => dto.WidgetCategories, opt => opt.Ignore());


And this query

    var query2 = db.Widgets
                .Project()
                .To<WidgetDto>()
                .ToList();

The reason for the lambdas, was I really wanted more control over what properties are being expanded. Expanding all properties all of the time seems overkill. As does creating a different mapping for all possible scenarios.

    Mapper.CreateMap<Widget, WidgetDto>()                
        .ForMember(dto => dto.WidgetCategories, opt => opt.ExplicitExpansion());

    Mapper.CreateMap<Widget, WidgetSubDto>()
        .ForMember(dto => dto.WidgetCategories, opt => opt.Ignore());

    Mapper.CreateMap<WidgetCategory, WidgetCategoryDto>()                
        .ForMember(dto => dto.Category, opt => opt.ExplicitExpansion())
        .ForMember(dto => dto.Widget, opt => opt.ExplicitExpansion());

    Mapper.CreateMap<Category, CategoryDto>()
        .ForMember(dto => dto.WidgetCategories, opt => opt.ExplicitExpansion());

    Mapper.CreateMap<Category, CategorySubDto>()
        .ForMember(dto => dto.WidgetCategories, opt => opt.Ignore());


I can now write my query like so, and I don't get the exceptions

    var query3 = db.Widgets
                .Project()
                .To<WidgetDto>(
                    null, 
                    dto => dto.WidgetCategories, 
                    dto => dto.WidgetCategories.Select(i => i.Category), 
                    dto => dto.WidgetCategories.Select(i => i.Widget))
                .ToList();

Are there any shortcomings to this approach?

**Comment by jbogard** [comment]
No, this is *by far* the preferable choice. It's a lot more obvious to what's going on.

**Comment by SamL1** [comment]
Great, thanks for your help.
