### ISSUE TITLE
FYI: unresolved System.Core 2.0.5.0 is back

### ISSUE THREAD

**Issue by Serenyrddraig** [AutoMapper/AutoMapper#795]
This is more of an alert than a bug report.

I currently have an issue open with Microsoft Premier Support on MSBuild. The problem appeared when I added AutoMapper 3.1.0 as a dependency to an assembly for a WPF custom control assembly, i.e. WPF custom control -> Assembly 1 -> AutoMapper. The custom control assembly is one out of 18 in the solution. When MSBuild builds the custom control project alone it succeeds. When it builds the full solution, it always fails resolving System.Core 2.0.5.0, the minimal PCL version.

The problem can be circumvented completely by reducing the number of cores in the VM performing the build from 4 to 2, i.e. the working hypothesis is that there is a race condition in assembly resolution. Whether or not this has anything to do with WPF is uncertain.

Problem occurred in VS2013 Ultimate Update 4. I'll post resolution as available.

**Comment by jbogard** [comment]
4.0 will fix all of this because I'm going to just one assembly
