### ISSUE TITLE
Multiple identical calls to ReplaceMemberName break mapping

### ISSUE THREAD

**Issue by thingylab** [AutoMapper/AutoMapper#796]
Given the following classes:

```csharp
class ClassA
{
    public string Smthng { get; set; }
}

class ClassB
{
    public string Something { get; set; }
}
```

And this profile:

```csharp
class Prof : Profile
{
    protected override void Configure()
    {
        ReplaceMemberName("Smthng", "Something");
        ReplaceMemberName("Smthng", "Something");
        CreateMap<ClassA, ClassB>();
    }
}
```

The mapping from `ClassA` to `ClassB` fails (as in `AssertConfigurationIsValid` reports a missing mapping for the field). I know the profile is "wrong", but is that the expected behaviour? Shouldn't the second call be ignored, or `AssertConfigurationIsValid` report the duplicate call?

**Comment by lbargaoanu** [comment]
This seems to work now. I assume you're on an older version.
