### ISSUE TITLE
Question: Nested projections

### ISSUE THREAD

**Issue by ivaylokenov** [AutoMapper/AutoMapper#799]
Hi!
I want to use some of the properties after a nested projection in LINQ with AutoMapper but the compiler is not happy. Is there any solution/suggestion?

More details and code samples here: http://stackoverflow.com/questions/31502663/how-to-perform-linq-operation-after-nested-automapper-project-to

Thank you in advance!

**Comment by jbogard** [comment]
I *believe* this was a bug in AutoMapper - can you try 4.0?
