### ISSUE TITLE
AfterBatch idea

### ISSUE THREAD

**Issue by drusellers** [AutoMapper/AutoMapper#800]
I can see that AutoMapper supports [mapping lists and arrays](https://github.com/AutoMapper/AutoMapper/wiki/Lists-and-arrays) and it has support for [context before / after map](https://github.com/AutoMapper/AutoMapper/wiki/Before-and-after-map-actions). A feature request that I'd like to see is a `BeforeBatch` and `AfterBatch` type call back that can be used to handle issues like this one http://stackoverflow.com/questions/27341945/automapper-with-auto-incremented-values.

If I have a map `CreateMap<ShipmentUpdateItem, F47072>()` and I call it like `Mapper.Map<List<ShipmentUpdateItem>, IEnumerable<F47072>>(input.Lines)` - It would be awesome to have a Before/After that gave me access to the whole collection to do line numbers and such rather than having to embed it each time I call the mapping. 

Good Idea / Bad Idea?????

-d

**Comment by jbogard** [comment]
So you COULD try using a custom resolver, which includes an index https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/ResolutionContext.cs#L39. You might have to walk the parent context up, but it'll be there.

**Comment by jbogard** [comment]
Also you could create the map between the two lists.

**Comment by drusellers** [comment]
Ah, very true. Probably should just do that. :)
