### ISSUE TITLE
Where is the IPlatformSpecificMapperRegistry Interface for new version 4 beta

### ISSUE THREAD

**Issue by rabbal** [AutoMapper/AutoMapper#803]
hi.
I don't want to use static mapper so I should use like :

//var platformSpecificRegistry = PlatformAdapter.Resolve<IPlatformSpecificMapperRegistry>();
            //platformSpecificRegistry.Initialize();

but in this new version beta , I don't find the IPlatformSpecificMapperRegistry interface.

**Comment by jbogard** [comment]
Removed. Everything is collapsed into individual platform-specific assemblies.
