### ISSUE TITLE
Extension point for mapping

### ISSUE THREAD

**Issue by Bidou44** [AutoMapper/AutoMapper#805]
Does AutoMapper have an extension point like Map(PropertyInfo sourceProperty, PropertyInfo) ? I'm trying to achieve what I described  here:http://stackoverflow.com/questions/31706697/custom-mapping-with-automapper, but obviously that's not possible, or am I missing something?

**Comment by jbogard** [comment]
No, but I like this idea.

**Comment by lbargaoanu** [comment]
ForAllMaps+ForAllMembers could achieve that, but the problem is that the non generic IMappingExpression is not on par with the generic one.

**Comment by jbogard** [comment]
No and when I attempted to combine the two together, it was teh suck

**Comment by TylerCarlson1** [comment]
I should be able to add a convention to #793 to get this kind of functionality fairly easily

**Comment by lbargaoanu** [comment]
@jbogard Can you take a look at #861? Tests are coming :)
