### ISSUE TITLE
[3.3.1] Source & Symbols are not available on SymbolSource.org

### ISSUE THREAD

**Issue by daniellking** [AutoMapper/AutoMapper#806]
Nothing particularly killer but 3.3.1 source isn't available on symbolsource.org. As you can see here the sources skip from 3.3.0 to 4.0.0 https://www.symbolsource.org/Public/Metadata/NuGet/Project/AutoMapper

I ended up working around this by downloading the source from GitHub but it would be nice to have the 3.3.1 source on the server in addition to the old version and the prerelease version.

Thanks!
Feel free to close this any time (even if its just a comment saying the 3.3.1 source has to be downloaded from GitHub) I just wanted to make sure you were aware of the gap on the symbol server.

**Comment by jbogard** [comment]
3.3.1 is not, 4.0.0 is, yeah you have to download from GH. Occasionally the source publishing fails on my TeamCity build :(
