### ISSUE TITLE
Cannot add Automapper 4.0.3 to Xamarin Project causes error

### ISSUE THREAD

**Issue by danstraughn** [AutoMapper/AutoMapper#813]
No matter what i do i cannot get passed this when trying to update our Automapper to use the latest build.

'AutoMapper' already has a dependency defined for 'System.Collections'.

**Comment by jbogard** [comment]
Can you try 4.0.2?

**Comment by danstraughn** [comment]
I rolled back to the previous version and was getting the same error.  I saw that a previous poster had the same issue and you recommended 4.0.4 so i will try that.

**Comment by danstraughn** [comment]
Updating the nuget package to 4.0.4 solved our problems.  Thank you!

**Comment by jbogard** [comment]
WHEW

**Comment by nbelley** [comment]
It is not working for me for 4.0.4! Still complaining on System.Collections
