### ISSUE TITLE
AutoMapper already has a dependency defined for System.Collection

### ISSUE THREAD

**Issue by kevyaugusto** [AutoMapper/AutoMapper#814]
I've just created a MVC app and got this error after trying to install AutoMapper's package. Could you please take a look? 

![sem titulo](https://cloud.githubusercontent.com/assets/1820655/9102582/78f2dd56-3bca-11e5-9579-87e6f7e7ed4d.png)

**Comment by jbogard** [comment]
Try the 4.0.4 prerelease from MyGet:

https://www.myget.org/F/automapperdev/api/v2

**Comment by lbargaoanu** [comment]
@kevyaugusto Can you please close your issue?

**Comment by kevyaugusto** [comment]
Thanks @jbogard and @lbargaoanu
