### ISSUE TITLE
Failed to compile the generated registrar code - Automapper 4.0.4 - Xamarin in Release Mode

### ISSUE THREAD

**Issue by danstraughn** [AutoMapper/AutoMapper#817]
Since updating to the most recent Automapper version 4.0.4 available through Nuget everything seemed to be good until we switched to release mode.  Now we are getting "Failed to compile the generated registrar code."

**Comment by jbogard** [comment]
I've got Xamarin installed on my Mac, do you have a step-by-step repro?

**Comment by danstraughn** [comment]
Current Project is referencing AutoMapper 3.3.1

1) Update to latest version of Automapper 4.0.4
2) Build in Debug mode - Succeeds
3) Switch to Ad-Hoc Or Release mode - Fails with error above

**Comment by jbogard** [comment]
What kind of project is this? iOS/Android? Xamarin.Forms?

**Comment by danstraughn** [comment]
It's a Native Android/iOS/Shared project solution. We are targeting the iOS unified architecture and Android 4.4.4

**Comment by jbogard** [comment]
I don't think I've ever used a shared project solution vs. portable class library. One difference is I have consolidated the assemblies into one platform-specific assembly per platform. The PCL is totally separate.

So in Xamarin Studio, you create a "Shared Project" then two native projects, and have the native projects reference the shared project? And where is AutoMapper reference added, in both the native projects?

**Comment by danstraughn** [comment]
So from what i can gather,

When updating to the latest Automapper 4.0.4 the following is added to the project ----
---The References that are added are needed by Automapper but not available in Xamarin.IOS, which i think is causing the havoc.

 <Reference Include="AutoMapper">
      <HintPath>..\packages\AutoMapper.4.0.4\lib\Xamarin.iOS10\AutoMapper.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.Linq" />
    <Reference Include="System.Linq.Expressions" />
    <Reference Include="System.Linq.Queryable" />
    <Reference Include="System.Text.RegularExpressions" />
    <Reference Include="System.Reflection" />
    <Reference Include="System.Reflection.Extensions" />
    <Reference Include="System.Diagnostics.Debug" />
    <Reference Include="System.ObjectModel" />
    <Reference Include="System.Runtime.Extensions" />
    <Reference Include="System.Threading" />

Here is the error that happens if i deploy 
http://pastebin.com/4c6cqiXP

**Comment by danstraughn** [comment]
And yes each project references the libraries the shared project needs.

**Comment by jbogard** [comment]
I think this might be because Xamarin does not support NuGet 2.8.6

**Comment by jbogard** [comment]
This looks to be fixed in 4.1.1.
