### ISSUE TITLE
Mapping inheritance doesn't work in 4.0.4

### ISSUE THREAD

**Issue by thisispaulsmith** [AutoMapper/AutoMapper#819]
Just raising the issue as it was something I'd come across.

This code works in 3.3.1 but not in 4.0.4

```
[TestFixture]
public class UnitTest1
{
    [Test]
    public void TestMethod1()
    {
        Mapper.CreateMap<Order, OrderDto>()
            .Include<OnlineOrder, OnlineOrderDto>()
            .Include<MailOrder, MailOrderDto>();
        Mapper.CreateMap<OnlineOrder, OnlineOrderDto>();
        Mapper.CreateMap<MailOrder, MailOrderDto>();

        //Mapper.AssertConfigurationIsValid();

        var mailOrder = new MailOrder() { NewId = 1 };
        var mapped = Mapper.Map<OrderDto>(mailOrder);

        mapped.ShouldBeType<MailOrderDto>();
    }

    public abstract class Base<T>
    {
    }

    public class Order : Base<Order> { }
    public class OnlineOrder : Order { }
    public class MailOrder : Order
    {
        public int NewId { get; set; }
    }

    public class OrderDto { }
    public class OnlineOrderDto : OrderDto { }
    public class MailOrderDto : OrderDto
    {
        public int NewId { get; set; }
    }
}
```

Incidentally if you call  `Mapper.AssertConfigurationIsValid();` it works in 4.0.4

**Comment by jbogard** [comment]
Is it different if you use Mapper.Initialize instead of Mapper.CreateMap?

**Comment by thisispaulsmith** [comment]
Yes. This works....

```
[TestFixture]
public class UnitTest1
{
    [Test]
    public void TestMethod1()
    {
        Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<Order, OrderDto>()
                .Include<OnlineOrder, OnlineOrderDto>()
                .Include<MailOrder, MailOrderDto>();
            cfg.CreateMap<OnlineOrder, OnlineOrderDto>();
            cfg.CreateMap<MailOrder, MailOrderDto>();
        });

        var mailOrder = new MailOrder() { NewId = 1 };
        var mapped = Mapper.Map<OrderDto>(mailOrder);

        mapped.ShouldBeType<MailOrderDto>();
    }

    public abstract class Base<T>
    {
    }

    public class Order : Base<Order> { }
    public class OnlineOrder : Order { }
    public class MailOrder : Order
    {
        public int NewId { get; set; }
    }

    public class OrderDto { }
    public class OnlineOrderDto : OrderDto { }
    public class MailOrderDto : OrderDto
    {
        public int NewId { get; set; }
    }
}
```

**Comment by baltie** [comment]
I had the same problem. Configuring mappings within Initialize solved it. Thanks.

**Comment by azazi-sa** [comment]
Yup. Same is the case with me. Mapper.Create map simply does not identify mapping for derived classes whereas Mapper.Initialize works.

**Comment by queueit** [comment]
Same here.. If it was not for unit tests it would have been likely to end up in production. Pretty critical bug..

**Comment by vascorpfernandes** [comment]
I came across  the same problem.
We have this type of code in our application.

```csharp

class CustomerGroup {}
class CustomerGroupModel {}
class CustomerGroupDetailsModel : CustomerGroupModel {}

-------------------------

Mapper.CreateMap<CustomerGroup, CustomerGroupModel>();
Mapper.CreateMap<CustomerGroup, CustomerGroupDetailsModel>();

--------------------------
var customerGroup = .... from DB....
Mapper.Map<CustomerGroupDetailsModel>(customerGroup);

```
This worked on 3.x, but fails on 4.0.

Unable to cast object of type 'Customer.Models.CustomerGroupModel' to type 'Customer.Models.CustomerGroupDetailsModel'.

 Using Mapper.Initialize on 4.0 it works.

**Comment by jbogard** [comment]
One other thing you can do is seal the mappings (this figures out all the dependencies between maps and builds out a mapping plan).

`Mapper.Configuration.Seal();`

I'll make sure and document this.

**Comment by pYThMik** [comment]
Sorry but none of the suggested solutions worked for me. I had to downgrade to 3.3.1.

**Comment by XavierLluch** [comment]
Sorry but none of the suggested solutions worked. I had to downgrade to 3.0.0

3 classes plays in this mapping code:

    class Department :  basicStructureEntity { ... }
    class Account : basicStructureEntity { ... }
    class Client : IComparable, IEquatable<Client> 
    {
      public Client( Account client ) { ... }
      public Client( Department client ) { ... }
      public Client () { }
    }

... and i'm working with Enumerables of them ...

    List<Department> deptClients = ...
    List<Account> accClients = ...

----------------------------------------------------------------------------------------
mapper configuration for both:

    Mapper.Initialize(cfg => {
                cfg.CreateMap<Department, Client>()
                             .ForMember(dest => dest.attr_c1, orig => orig.MapFrom(dep => dep.attr_d1))
                             .ForMember(dest => dest.attr_c2, orig => orig.MapFrom(dep => dep.attr_d2))
                             .ForMember(dest => dest.attr_c3, opt => opt.UseValue(""));
                cfg.CreateMap<Account, Client>()
                             .ForMember(dest => dest.attr_c1, orig => orig.MapFrom(a => a.attr_a1))
                             .ForMember(dest => dest.attr_c2, orig => orig.MapFrom(a => a.attr_a2))
                             .ForMember(dest => dest.attr_c3, orig => orig.MapFrom(a => a.attr_a3));
    });

----------------------------------------------------------------------------------------
and map action where it breaks...

    IEnumerable<Client> clientList =
        Mapper.Map<IEnumerable<Department>, IEnumerable<Client>>(deptClients);


At this poin it breaks with ver.4.0.4 (doesn't break with ver. 3.0.0) and Exception Message : 
>"Trying to map Department_EA75AC67BA7938921E7B0E5912A9A9B53CE06D8D76789E8FA5A836C1B5892F2E to Account."

** It seems Mapper is trying to map **Department** to **Account** instead of map from **Department** to **Client**.


I hope it could be useful to resolve this bug (if you're considering it as a bug). And thanks for sharing AutoMapper code!!!!

**Comment by swilkos** [comment]
Seem to still have an issue with the latest build.  Am open to any suggestions!

Classes:
```
    public class ExampleContext : DbContext
    {
        public DbSet<TrainingCourse> TrainingCourses { get; set; }
        public DbSet<TrainingContent> TrainingContents { get; set; }
    }

    public class TrainingCourse
    {
        public TrainingCourse()
        {
            Content = new List<TrainingContent>();
        }

        public TrainingCourse(TrainingCourse entity)
        {

            Mapper.Map(entity, this);
        }

        [Key]
        public int CourseId { get; set; }

        public string CourseName { get; set; }

        public virtual ICollection<TrainingContent> Content { get; set; }
    }

    public class TrainingContent
    {
        public TrainingContent()
        {
        }

        [Key]
        public int ContentId { get; set; }

        public string ContentName { get; set; }

        public virtual TrainingCourse Course { get; set; }

        public int CourseId { get; set; }

    }

    public class TrainingCourseDto
    {
        public int CourseId { get; set; }

        public string CourseName { get; set; }

        public ICollection<TrainingContentDto> Content { get; set; }
    }

    public class ParentTrainingCourseDto : TrainingCourseDto
    {
        [IgnoreMap]
        public new ICollection<TrainingContentDto> Content { get; set; }
    }

    public class TrainingContentDto
    {
        public int ContentId { get; set; }

        public string ContentName { get; set; }

        public ParentTrainingCourseDto Course { get; set; }

        public int CourseId { get; set; }
    }
```

Initializer:
```
            Mapper.Initialize(
                cfg =>
                    {
                        cfg.CreateMap<TrainingCourse, TrainingCourseDto>()
                        .Include<TrainingCourse, ParentTrainingCourseDto>();
                        cfg.CreateMap<TrainingCourse, ParentTrainingCourseDto>();
                        cfg.CreateMap<TrainingContent, TrainingContentDto>();

                        
                    });

            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();
```

Code that throws an excption with Automapper 4.1.0
```
            ExampleContext context = new ExampleContext();
            var course = context.TrainingCourses.FirstOrDefault(n => n.CourseName == "Course 1");
            var dto = Mapper.Map<TrainingCourseDto>(course);
```

Error thrown:
```
AutoMapper.AutoMapperMappingException : 

Mapping types:
TrainingCourse -> TrainingCourseDto
AutoMapper.BugExample.TrainingCourse -> AutoMapper.BugExample.TrainingCourseDto

Destination path:
TrainingCourseDto.Content.Content.Content0[0].Course0[0].Course0[0]

Source value:
System.Data.Entity.DynamicProxies.TrainingCourse_1F4098BB48C8E550C9BD06AA4E5078C25E68A8F1D567EB1E395EAFE4C70847D6
  ----> System.InvalidCastException : Unable to cast object of type 'AutoMapper.BugExample.TrainingCourseDto' to type 'AutoMapper.BugExample.ParentTrainingCourseDto'.
```

**Comment by jbogard** [comment]
@swilkos This is a different issue with the proxies, can you open a GH issue?

**Comment by swilkos** [comment]
@jbogard Will do!  Thanks!
