### ISSUE TITLE
How to ignore an inner nested object when using AutoMapper

### ISSUE THREAD

**Issue by andreluisce** [AutoMapper/AutoMapper#820]
Hello I have the classes:

Class User

    public class User
    {
        public Int64 Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }        
        public Profile Profile { get; set; } //EF one to one
    }
Class Profile

    public class Profile 
    {
        public Int64 Id { get; set; }
        public string Skype { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual User User { get; set; } //This is because EF Mappings
    }
Class User DTO

    public class UserDTO
    {
        public string Name { get; set; }
        public string Email { get; set; }        
        public Profile Profile { get; set; }
    }
I did the configurations to Map User to UserDTO

    Mapper.CreateMap<User, UserDTO>();

I need to have the Profile.User because of the Entity Framework One to One Relationship but I don't want the Profile.User to be shown in the Mapping.

How can I ignore the Profile.User?

**Comment by TylerCarlson1** [comment]
You make ProfileDTO class and map the variables you need.
You shouldn't be mixing DTO's with EF items, cause it causes a lot of problems, like this.
