### ISSUE TITLE
IPlatformSpecificMapperRegistry issue, AutoMapper 4.0.4

### ISSUE THREAD

**Issue by MehdiDehghani** [AutoMapper/AutoMapper#821]
How I should change this to working with new version too?
var platformSpecificRegistry = PlatformAdapter.Resolve < IPlatformSpecificMapperRegistry > ();
platformSpecificRegistry.Initialize();

**Comment by jbogard** [comment]
Those two types were removed in 4.0. Their behavior was removed, too, as there are no "platform-specific" anything anymore, it's all done now with compiler directives to create one assembly per platform.
