### ISSUE TITLE
AutoMapper 4.0.4 - How to fix this breaking change: Base class mapping is now default for derived class mapping

### ISSUE THREAD

**Issue by jwu-au** [AutoMapper/AutoMapper#822]
Please see below code it is running ok in V3. But it throws error in V4.

*Exception:
```
            Unhandled Exception: System.InvalidCastException: Unable to cast object of type
'AutoMapperTest.Base' to type 'AutoMapperTest.DerivedB'.
   at AutoMapper.MappingEngine.Map[TDestination](Object source, Action`1 opts)
   at AutoMapper.MappingEngine.Map[TDestination](Object source)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at AutoMapperTest.Program.Main(String[] args) in D:\Backup\Data\Win8\Document
s\Visual Studio 2015\Projects\AutoMapperTest\AutoMapperTest\Program.cs:line 16
```

*Source:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.Mappers;

namespace AutoMapperTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            MapperRegistry.Mappers.Add(new MyObjectMapper());
            Mapper.CreateMap<Base, Base>(); // base class mapping, used in MyObjectMapper

            var derivedAInstance = new DerivedA {Name = "Bob Foo"};
            var derivedBInstance = Mapper.Map<DerivedB>(derivedAInstance); // exception throw here v4.0.4
            var shouldBeEqual = derivedBInstance.Name == derivedAInstance.Name;
            // Assert shouldBeEqual is true
        }

        public class MyObjectMapper : IObjectMapper
        {
            public object Map(ResolutionContext context, IMappingEngineRunner mapper)
            {
                var destinationValue = mapper.CreateObject(context);

                // using Base mapping
                var typeMapper = mapper.ConfigurationProvider.FindTypeMapFor(typeof (Base), typeof (Base));
                var typeContext = context.CreateTypeContext(typeMapper, context.SourceValue, destinationValue, typeof (Base), typeof (Base));
                destinationValue = mapper.Map(typeContext);

                // do other custom mapping
                // ...

                return destinationValue;
            }

            public bool IsMatch(ResolutionContext context)
            {
                return context.SourceType == typeof (DerivedA) && context.DestinationType == typeof (DerivedB);
            }
        }
    }

    public class Base
    {
        public string Name { get; set; }
    }

    public class DerivedA : Base
    {
        public string Gender { get; set; }
    }

    public class DerivedB : Base
    {
        public int Age { get; set; }
    }
}
```

**Comment by lbargaoanu** [comment]
Did you try the fix in #819?

**Comment by jwu-au** [comment]
@lbargaoanu 
Doesn't work. I don't think they are the same issue. You can run my sample code both in v3 and v4 to see the difference.

**Comment by lbargaoanu** [comment]
You're right. Your mapper isn't used, probably that's what changed.

**Comment by jwu-au** [comment]
I need to get the issue resolved or finding out a work around before upgrading to v4. Thanks.

**Comment by lbargaoanu** [comment]
@jbogard should weigh on this. But here is my take :). I would guess that changes to the algorithm used to find type maps broke your example. Now the Base->Base mapping is found by default and that's why your mapper is not invoked. You could use an [after map action](https://github.com/AutoMapper/AutoMapper/wiki/Before-and-after-map-actions) as a workaround coupled with virtual methods for customizing derived classes. Or perhaps special mappings for the derived classes.

**Comment by jbogard** [comment]
Yeah, that's almost certainly it - what are you trying to do here? It seems rather strange to create a map from one object to itself.

**Comment by jwu-au** [comment]
In my real case, the Base->Base mapping is useful as there are many private/public fields in the Base class. For one, when mapping two different derive types, Base->Base mapping is doing part of whole mapping (you can see in sample code MyObjectMapper "using Base mapping"). Secondly, my derived classes are generic in real case, I need to use a custom IObjectMapper to handle the mapping. That is why I need the Base->Base mapping.

So If I have the Base->Base mapping setup, I can't have the MyObjectMapper working in V4 because SourceType and DestinationType in  ResolutionContext in IsMatch method are both Base type. The original mapping type information is gone.

Make sense? Any clue?

You can reproduce what I said above by change sample code to below:
```
MapperRegistry.Mappers.Insert(0, new MyObjectMapper());
```

**Comment by lbargaoanu** [comment]
Yes, all that is true, but it doesn't mean it's a bug. AutoMapper also supports [generic mappings] (https://github.com/AutoMapper/AutoMapper/wiki/Open-Generics).

**Comment by jbogard** [comment]
So Insert(0) fixes it?

**Comment by lbargaoanu** [comment]
No :) It just crashes elsewhere.

**Comment by TylerCarlson1** [comment]
Have you tried Fix #819 and Insert(0) together?  Might have something to do with not sealing the typemap before using.

Or try Insert(0) and then use this code for your base message
```
var destinationValue = mapper.CreateObject(context);

// using Base mapping
Mapper.Map<Base, Base>(context.SourceValue, destinationValue);

// do other custom mapping
// ...
```

If destinationValue is Base and not DerivedB you might have to create an instance of the object yourself to get it to work.

**Comment by jwu-au** [comment]
@TylerCarlson1 
You are right that the destinationValue is Base. I cannot create the "real" destination instance in V4 for two reasons:
1. ResolutionContext doesn't contain the "real" source and destination type as they are both Base type.
2. Destination type is generic, the object mapper don't know the real type until runtime.

In my opinion, we are expecting ResolutionContext should contain the original mapping type information, aren't we? In above sample code, the mapping type information are overwritten by Base type as we CreateMap for base type only but not derived type.

**Comment by TylerCarlson1** [comment]
Ok I see the problem now.  That's an unusual scenario.

I would also agree with @lbargaoanu that generic mappings should work in this scenario
Something like `Mapper.CreateMap(typeof(Source<>), typeof(Destination<>));`
If you make Source and Destination both use the same properties there's no reason for a Base class and mapping to itself.  Also if you are doing something like `Mapper.Map<Source<RowA>,Destination<RowB>>` and you have a map between RowA and RowB it will use that type map for you.

**Comment by jwu-au** [comment]
I ended up with removing the Base->Base mapping. And handle the mapping manually in my custom object mapper.
But I still get a feeling that ResolutionContext should contain the original mapping type information regard less there is or isn't any base type mapping setup. It isn't a bug but a breaking change in my case.
Feel free to close the issue if no further actions.

**Comment by jbogard** [comment]
@jwu-au I think you're right there - there's no real reason why it shouldn't contain the original ones (at least not AFAIK).

**Comment by lbargaoanu** [comment]
@jbogard You mean in other properties? Because changing SourceType and DestinationType will break things.

**Comment by jbogard** [comment]
@lbargaoanu exactly, something like "RuntimeSourceType" etc

**Comment by lbargaoanu** [comment]
The name seems vague to me. Perhaps InitialSourceType, PassedSourceType or RootSourceType?

**Comment by lbargaoanu** [comment]
Went with InitialSourceType. Refactored the constructors, trying to avoid one with a gazillion parameters.
