### ISSUE TITLE
Overlapping assembly references after updating to 4.0.4

### ISSUE THREAD

**Issue by nelsonghezzi** [AutoMapper/AutoMapper#823]
I've updated from 3.3.1 to 4.0.4 and now I'm getting one of those overlapping references error:

*The type 'System.AggregateException' exists in both 'c:\<Solution path>\packages\AutoMapper.4.0.4\lib\portable-net45+win+wpa81+wp80+MonoAndroid10+Xamarin.iOS10+MonoTouch10\AutoMapper.dll' and 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.6\Profile\Profile32\System.Threading.Tasks.dll'*

The project is a PCL targeting Windows 8.1 and Windows Phone 8.1 (Profile32).

Any ideas what is going wrong and how I can fix it?

**Comment by jbogard** [comment]
Oversight on my part. Can you try the 4.1.0 pre-release on MyGet? https://www.myget.org/F/automapperdev/api/v2

**Comment by nelsonghezzi** [comment]
Hi Jimmy, I've tried the prerelease version and it worked, no compile-time error.

A brief smoke test have not shown any compatibility issues neither, but since it's my first time trying version 4.x, It would require some time 'til be sure.

Thanks for the help so far!

**Comment by jbogard** [comment]
Great, I'll close this then.
