### ISSUE TITLE
Overriding destination type with .As<> does not work as in 3.3.1.0

### ISSUE THREAD

**Issue by bluerobotch** [AutoMapper/AutoMapper#828]
We have a scenario where we map two base types and want to override the target type with .As<>(). The following example works with 3.3.1.0 but not with 4.0.4.0. In 4.0.4.0 AutoMapper tries to instantiate the ChildModelBase instead of ChildModel which leads to an exception because the type is abstract. The typeMapPlanCache in the ConfigurationStore seems to be correct, but the MappingEngine (IMappingEngineRunner.CreateObject()) does not take the destination type on the type map into account.

In real world we load an entity using NHibernate, which generates proxies for all entities.

```cs
using AutoMapper;
using FluentAssertions;
using Moq;
using Xunit;

public class OverrideDestinationMappingsTest
{
    [Fact]
    public void Map_WhenOverrideDestinationTypeAndSourceIsDerived_MustCreateOverriddenDestinationType()
    {
        InitializeMapper();

        Entity entity = LoadEntity();

        var model = Mapper.Map<Model>(entity);

        model.Child.Should().BeOfType<ChildModel>();
    }

    private static Entity LoadEntity()
    {
        return Mock.Of<Entity>(x => x.Child == Mock.Of<ChildEntiy>());
    }

    private static void InitializeMapper()
    {
        Mapper.Initialize(c =>
        {
            c.CreateMap<Entity, Model>();

            c.CreateMap<ChildEntiy, ChildModelBase>()
                .Include<ChildEntiy, ChildModel>()
                .ForMember(x => x.SomeValue, x => x.Ignore())
                .As<ChildModel>();

            c.CreateMap<ChildEntiy, ChildModel>();
        });
    }

    public class Entity
    {
        public ChildEntiy Child { get; set; }
    }

    public class ChildEntiy
    {
        public string SomeValue { get; set; }
    }

    public class Model
    {
        public ChildModelBase Child { get; set; }
    }

    public abstract class ChildModelBase
    {
        public string SomeValue { get; set; }
    }

    public class ChildModel : ChildModelBase
    {
    }
}
```

**Comment by lbargaoanu** [comment]
Same as #551 I suppose.

**Comment by nbelley** [comment]
Same problem with Entity Framework, I upgraded to Automapper 4 and all the .As from an interface to a concrete implementation are not working.

**Comment by TylerCarlson1** [comment]
Does `entitiesToMap.Select(e => Mapper.Map<IClientDTO>(e)).ToList();` work as an alternative?

**Comment by lbargaoanu** [comment]
@bluerobotch Can you please check that OverrideDestinationMappingsTest is your exact situation?
