### ISSUE TITLE
mapping object to dynamic

### ISSUE THREAD

**Issue by fastfasterfastest** [AutoMapper/AutoMapper#829]
I am mapping a object (which is a Newtonsoft.Json.Linq.JObject as returned by Newtonsoft.Json.JsonConvert.DeserializeObject) to a dynamic.

Using AutoMapper 3.3.1 and JSON.Net 7.0.1, the sample below works and maps the source object.
Using AutoMapper 4.0.4 and JSON.Net 7.0.1, the sample throws an AutoMapper.AutoMapperMappingException with the following message:
>Mapping types:
>JObject -> JObject
>Newtonsoft.Json.Linq.JObject -> Newtonsoft.Json.Linq.JObject
>
>Destination path:
>Destination.Foo.Foo
>
>Source value:
>{
>  \"prop1\": 123,
>  \"prop2\": 456
>}

Note, the destination path is `Destination.Foo.Foo`, not `Destination.Foo`.

```
public class Source
{
    public string JsonFoo { get; set; }
}

public class Destination
{
    public dynamic Foo { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        Mapper.CreateMap<Source, Destination>()
            .ForMember(dst => dst.Foo, opt => opt.ResolveUsing(src => Newtonsoft.Json.JsonConvert.DeserializeObject(src.JsonFoo)))
            ;
        Mapper.AssertConfigurationIsValid();

        try
        {
            var source = new Source() { JsonFoo = "{\"prop1\":123,\"prop2\":456}" };
            var destination = AutoMapper.Mapper.Map<Source, Destination>(source);
        }
        catch (Exception)
        {
        }
    }
}
```

**Comment by lbargaoanu** [comment]
@jbogard This crashes inside the DictionaryMapper but it works with the AssignableMapper. The problem is that moving the AssignableMapper before the DictionaryMapper breaks some tests, but I think that could be fixed. What do you think?

**Comment by jbogard** [comment]
Yeah, I don't remember why assignable was moved afterwards, assignable should basically trump all except type maps.

**Comment by jbogard** [comment]
Ah, I remember why. You don't want to copy collections over, just the things inside the collections. Gonna dig inside that exception to see more.

**Comment by lbargaoanu** [comment]
@jbogard Working on a test without Json.NET.

**Comment by lbargaoanu** [comment]
It looks a little weird, but here it is :).
