### ISSUE TITLE
Same field two conditions

### ISSUE THREAD

**Issue by acostaf** [AutoMapper/AutoMapper#834]
I am trying to use automapper conditions with two diff conditions pointing to the same field, but the second one overrides the first, any idea?

         Mapper.CreateMap<src, des>()
        .ForMember(x => x.Date, o =>
        {
            o.Condition(s => s.ContainsKey("DateTaxe"));
            o.ResolveUsing<DateTaxeResolver>();
        })
        .ForMember(x => x.Date, o =>
        {
            o.Condition(s => !s.ContainsKey("DateTaxe") && s.ContainsKey("DateValue"));
            o.ResolveUsing<DateValue

**Comment by jbogard** [comment]
Are you trying to conditionally use different resolvers? Conditions are applied to an overall member mapping, not to things like resolvers.

**Comment by acostaf** [comment]
I've got two different pieces of data that needed to be converted first before to be able to assing it to the same field on the destination.

Will be nice to do something like the above but it doesnt work for Resolvers
.ForMember(d => d.BusinessGroup_Id,
           o => o.MapFrom(s => s.BusinessGroup == null ? 0 : (int)s.BusinessGroup));

**Comment by jbogard** [comment]
So I think the way this would work is a condition *on* resolvers:

```
     Mapper.CreateMap<src, des>()
    .ForMember(x => x.Date, o =>
    {
        o.ResolveUsing<DateTaxeResolver>().Condition(s => s.ContainsKey("DateTaxe"));
        o.ResolveUsing<DateValueResolver>().Condition(s => !s.ContainsKey("DateTaxe") && s.ContainsKey("DateValue"));
    });
```

What do you think?

**Comment by jbogard** [comment]
Eh, this would be a bit too hard because you'd have to make sure *something* resolves. A bit too complex at the moment.
