### ISSUE TITLE
SqlDataReader does not work with AutoMapper 4.0.4

### ISSUE THREAD

**Issue by BQuig** [AutoMapper/AutoMapper#835]
I have a .NET 4.5 project that I upgraded from 3.3.1 to 4.0.4 and my data access classes that use AutoMapper to map SqlDataReader to my classes no longer works.  I am using generics, but even creating the explicit map does not work.

My Code:
Mapper.CreateMap<SqlDataReader, T>();
var result = Mapper.Map<List<T>>(_reader);

Exception:
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
DataRecordInternal -> MyClass
System.Data.Common.DataRecordInternal -> Namespace.My.Class

Destination path:
List`1[0]

Source value:
System.Data.Common.DataRecordInternal
Result StackTrace:	
...

**Comment by inforithmics** [comment]
I have the Same problem

In Automapper 3.3.1 this worked

dto = Mapper.DynamicMap<IDataReader, List<PocoObject>>(reader);

In Automapper 4.0.4 this doesn't seem to work no exception but reads 0 entries

dto = Mapper.DynamicMap<IDataReader, List<PreisberechnungRechnungenPocoObject>>(reader);

This works somehow better it reads the correct number of entries. But they are not mapped (No property gets set).

dto = Mapper.DynamicMap<SqlDataReader, List<PreisberechnungRechnungenPocoObject>>(reader);

I debugged it in 3.3.1 and 4.0.4 And in 3.3.1 There seems to be a DataReaderMapper that does the magic. Has this been removed or replaced with something different

**Comment by lbargaoanu** [comment]
Perhaps [this] (https://github.com/AutoMapper/AutoMapper.Data)?

**Comment by inforithmics** [comment]
Yes, you are right. There should be living the DataReaderMapper. I have extracted an old version from The DataReaderMapper (from Version 3.1) and Registered it and now it works.

Register Mapper:

MapperRegistry.Mappers.Add(new DataReaderMapper());     

Code of DataReaderMapper:

https://github.com/AutoMapper/AutoMapper/blob/v3.3.1/src/AutoMapper/Mappers/DataReaderMapper.cs

There is an exception in this Method.
 
        private static void MapPropertyValues(ResolutionContext context, IMappingEngineRunner mapper, object result)
        {
            if (context.TypeMap == null)
            {                
                throw new AutoMapperMappingException(context, "Missing type map configuration or unsupported mapping.");
            }

            foreach (var propertyMap in context.TypeMap.GetPropertyMaps())
            {
                MapPropertyValue(context, mapper, result, propertyMap);
            }
        }

So I changed it to:

    private static void MapPropertyValues(ResolutionContext context, IMappingEngineRunner mapper, object result)
        {
            if (context.TypeMap == null)
            {                
               return;
            }

            foreach (var propertyMap in context.TypeMap.GetPropertyMaps())
            {
                MapPropertyValue(context, mapper, result, propertyMap);
            }
        }

I have to investigate it further, why this exception happens.

**Comment by lbargaoanu** [comment]
Hold your horses :) I'm sure there is an easy way to use it. I'm sure @jbogard will chip in.

**Comment by rallister** [comment]
Same here. added a comment on issue  #715.

**Comment by jumas45** [comment]
I am having the same issue. Currently downgraded to 3.3.1 where there is an explicit mapper available for DataReaders.

I wonder whether the DataReaderMapperwas  dropped by accident or by design? If by design, we will need to know how to get it working in the current version.

**Comment by jbogard** [comment]
I took them out to move them to their own repo. Then I realized I hadn't finished the move. With AutoMapper 4.1 release, I'll get AutoMapper.Data pushed out too.

**Comment by jumas45** [comment]
Thanks @jbogard .

**Comment by MrChris123** [comment]
@jbogard - Is there an ETA for 4.1 so DataTables/IDataReader can be used again?

In the meantime do you recommend downgrading to 3.3.1 as an alternative?

**Comment by lbargaoanu** [comment]
@BQuig Can you close your issue?

**Comment by MrChris123** [comment]
I would say this can only be closed if @jbogard agrees the correct answer is to downgrade to 3.3.1 because at the moment AutoMapper 4 does not support DataReaders, and AutoMapper.Data is not yet available through NuGet.

**Comment by Kobus-Smit** [comment]
Hi @jbogard, now that 4.1 was release, any idea when AutoMapper.Data would be published on NuGet?

>>With AutoMapper 4.1 release, I'll get AutoMapper.Data pushed out too.

**Comment by ronald7** [comment]
Hi @jbogard , thank you for the latest release of AutoMapper, it has an impressive release note :)! 

Same question as Kobus-Smit. I saw your commit yesterday containing the data reader support, this is great. But do you have any idea when you will push AutoMapper.Data on Nuget ? 

Thanks!

**Comment by jbogard** [comment]
It's on NuGet now:
https://github.com/automapper/automapper.data
https://www.nuget.org/packages/automapper.data
