### ISSUE TITLE
StackOverflowException on « GetCustomAttributes » when mapping Enum to Enum

### ISSUE THREAD

**Issue by PaulAchess** [AutoMapper/AutoMapper#841]
Hi,
I'm having some troubles lately with the new automapper. Unfortunately, I tried to reproduce it on a smaller project and I couldn't reproduce at all the problem, even when using the exact same entities. I'm thinking something in my projects (arborescence ? namespaces ? class/enum names ?) causes the issue.

My issue comes out when I try to map two enum properties to each other. This happens even when the same type of enum is used, or when I try to map with .UseValue(MyEnum.MyValue).

The workarounds I found are either to change the type of one of the property from enum to an int, or to ignore the value and map it manually (target.MyProperty = source.MyProperty).

There seem to be an infinite loop with « GetCustomAttributes », but I can't figure why this happens. As I said, I could not reproduce on a smaller project, and I already tried for a few hours.

However, what I can do if you are interested is to try to understand the issue with you (I'm willing to spend some time on Skype even, if you want), as I have the reproduction case on my main project with unit tests (so I can also check if the issue is resolved, or help diagnose it).

This is completely non-blocking now (I have a few workarounds), so I'm just here to help for this issue, I'm not seeking support from you.

**Comment by lbargaoanu** [comment]
Somebody saw this [before] (https://github.com/AutoMapper/AutoMapper/issues/824), but I couldn't repro it. A crash dump might be helpful.

**Comment by PaulAchess** [comment]
I saw this issue, I was not sure if this was the same problem. I also can't repro. The issue happens on WP, Android and Unit Tests, so it's not specific to my unit tests but it indeed makes them crash (as any other stackoverflowexception).

As I see, there is a fix for the bug you mentioned that was committed. What I can do is try the new version when it's ready and tell you if the issue is gone. I'll leave you the choice to close or leave the issue open.

Regarding crash dumps, I'm unfortunately unaware how to do them :-/

**Comment by lbargaoanu** [comment]
That issue was closed for different reasons. There is no fix because we don't know how it happens. If it crashes on the desktop, [here](http://blogs.msdn.com/b/debugger/archive/2009/12/30/what-is-a-dump-and-how-do-i-create-one.aspx) is how you can make a crash dump.

**Comment by PaulAchess** [comment]
I should be able to make a console app that crashes on which you'll have the dump. Let me look at this and come back to you.

**Comment by lbargaoanu** [comment]
Thanks.

**Comment by PaulAchess** [comment]
Okay I was not able to reproduce from a console app (it's the exact same code as the unit test, what the heck…) but looking into Visual Studio I found the « save dump as » option which allowed me to put this dump from my unit test crash.

Here it is, I hope this helps :
https://drive.google.com/file/d/0B6kaeItD7VQ_bXczOUhBOXl1TDA/view?usp=sharing

**Comment by lbargaoanu** [comment]
Thanks for taking the time to do this, I'll take a look and let you know.

**Comment by PaulAchess** [comment]
Sure, no problem ! This is an amazing library and I'm glad to help you.

If anyone has the problem, the final workaround I am using is :
`.ForMember(target => target.MyEnumProperty, options => options.MapFrom(source => (int)source.MyEnumProperty))`

This is enough for automapper not to crash.

**Comment by lbargaoanu** [comment]
@jbogard The problem is with the PCL assembly. TypeExtensions.GetCustomAttributes calls itself and overflows the stack.

**Comment by TylerCarlson1** [comment]
I saw that too, but I couldn't figure out and prove which of the builds of Automapper the recursion was happening.  In VS 2015 It looked like instead of recursion it would call Type.GetCustomAttributes() and not the extention method recursively for Automapper.Net4 solution. (The one I do all my testing on)

**Comment by jbogard** [comment]
BLLLAAAAAAARRRGGGGGG

**Comment by jbogard** [comment]
@PaulAchess I just pushed a potential fix, the latest on the MyGet feed will have this change.

**Comment by PaulAchess** [comment]
I'm not sure how to help now, but if you need to test a fix don't hesitate to ask.

**Comment by PaulAchess** [comment]
AutoMapper **4.1.0-ci1007** (Prerelease) from the MyGet feed **has fixed the issue** on my unit tests and my projects.

Great job !

**Comment by PaulAchess** [comment]
I'm not sure: should I close this issue or should I leave it for you to close it? (for instance if you want to close it when you push a version, I don't know how this all works)

**Comment by lbargaoanu** [comment]
You can close it :+1:

**Comment by PaulAchess** [comment]
Thanks for the answer and for your quick fix :)
