### ISSUE TITLE
InvalidCastException when using mapping inheritance

### ISSUE THREAD

**Issue by sickboy** [AutoMapper/AutoMapper#842]
~~~
public class A {};

public class AModel {}
public class BModel : AModel {}

Mapper.CreateMap<A, AModel>()
            .Include<A, BModel>();
Mapper.CreateMap<A, BModel>();
~~~

~~~
Mapper.Map<A, BModel>(anInstanceOfA);
~~~ 

Resulting in:
~~~
System.InvalidCastException: Unable to cast object of type 'AModel' to type 'BModel'. at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)
~~~

**Comment by sickboy** [comment]
A similar issue seems to occur in EF6 projection:
~~~
System.ArgumentException: Expression of type 'System.Linq.Expressions.Expression`1[System.Func`2[SN.withSIX.Social.Post,SN.withSIX.App.ApiModel.Post]]' 
cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[SN.withSIX.Social.Post,SN.withSIX.App.ApiModel.PostEntry]]' 
of method 'System.Linq.IQueryable`1[SN.withSIX.App.ApiModel.PostEntry] 
Select[Post,PostEntry](System.Linq.IQueryable`1[SN.withSIX.Social.Post], System.Linq.Expressions.Expression`1[System.Func`2[SN.withSIX.Social.Post,SN.withSIX.App.ApiModel.PostEntry]])' 
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi) at
 System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments) at 
 System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments) at 
 AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, String[] membersToExpand)
~~~

**Comment by sickboy** [comment]
My workaround so far is to make a new abstract base class, which will contain the base mapping. Then inherit both the Entry, and full models off these, and add the Includes to the base mapping.

**Comment by lbargaoanu** [comment]
It seems to work on develop. About the EF isssue, a failing test would be nice :).

**Comment by lbargaoanu** [comment]
And a different github issue for the EF error. Just from that message, I couldn't say they are related.

**Comment by onionhammer** [comment]
+1 I'm also getting this

**Comment by lbargaoanu** [comment]
@onionhammer I still need a repro with the latest version :)

**Comment by onionhammer** [comment]
I'll see about getting that to you later tonight

**Comment by onionhammer** [comment]
Well, I was going to go ahead and do this, but it's a bit more difficult than cloning automapper if one doesn't have a xamarin license. I'll have to demonstrate it in a separate repo

**Comment by jbogard** [comment]
You don't need one, just unload those projects.

**Comment by onionhammer** [comment]
Yeah, but then it had me set up the DNX framework and doesnt automatically build without a lot of rigmarole that I dont want to invest my time into right now. 

Here's a demonstration of the crash

https://github.com/onionhammer/AutoCrasher

**Comment by MadBullfrog** [comment]
Hey!
I have same problem too. Here a repro:
```
    public class A {};

    public class B : A {};

    public class C : B {};

    public class AModel {}
    public class BModel : AModel {}

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<A, AModel>();
            Mapper.CreateMap<B, BModel>();

            C c = new C();
            Mapper.Map<A, AModel>(c);
            Mapper.Map<B, BModel>(c);

         }
    }
```

**Comment by lbargaoanu** [comment]
While this is surprising, I'm not sure it's a bug. The runtime type of source is what matters, so you map from C to AModel and then from C to BModel. The first map matches what you would expect but also creates related mappings, including from C to AModel. The next map matches what it thinks is the best choice, you would like that to be B to BModel, but it chooses C to AModel and breaks. @jbogard might disagree.

**Comment by MadBullfrog** [comment]
I think `Mapper.Map<B, BModel>` should force exactly map from Type B to Type BModel as long as this map registered. All other strategies should be specified explicitely.

Also this code works on 3.3.1 so I consider it's a bug in version 4.

**Comment by lbargaoanu** [comment]
Meanwhile you can use as a workaround 
      
       cfg.CreateMap<A, AModel>().Include<B, BModel>();

**Comment by jbogard** [comment]
So mapping inheritance was always wonky, the implementation was just crazy and didn't support a number of scenarios. I had to refactor it to calculate the different inherited options when configuration is complete. You have two options:

- Use Mapper.Initialize()
- Call Mapper.Configuration.Seal() when you're done with your mappings.

**Comment by lbargaoanu** [comment]
@jbogard Not so fast :) This is not the same issue everybody reports. It happens with Initialize too. I would say that the root of the issue is that we use the runtime type of the object when finding the map, not the type parameters. The rest happens because of the algorithm for the related maps. I'm not saying it's a bug, but the result is not what you might expect.

**Comment by onionhammer** [comment]
The type parameters should be the source of truth. If I *request* Mapper.Map<X>(value); why would automapper try to give me Mapper.Map<Y>(value) ?

**Comment by jbogard** [comment]
@onionhammer Not necessarily just abstract/interface, but base classes as well. If you do polymorphic mappings, you need to look at the runtime types.

**Comment by onionhammer** [comment]
Regardless, I don't think an invalid cast exception should be the expected behavior

**Comment by garora** [comment]
Would like to reproduce. Just hypothetically is it a issue with Automapper
or EF6

**Comment by vovikdrg** [comment]
@garora  I think issue is with Automapper since when i reverted it to version 3.3.1 issue is gone.

**Comment by Borgas77** [comment]
I also have same issu with inherite classes and DynamicMap. It started when we uppgraded from from 3.3.1.
It somtimes just not map correctly.
