### ISSUE TITLE
ResolveUsing in base TypeMap

### ISSUE THREAD

**Issue by schmuli** [AutoMapper/AutoMapper#843]
The <code>ResolveUsing(valueResolverInstance)</code> method in a base class' mapping are being ignored when mapping a derived class.

```
abstract class BaseModel
{
    public string Title { get; set; }
}

class DerivedModel : BaseModel
{
    public string Message { get; set; }
}

abstract class BaseViewModel
{
    public string Title { get; set; }
}

class DerivedViewModel : BaseViewModel
{
    public string Message { get; set; }
}

Mapper.Initialize(cfg =>
{
     var valueResolver = new ValueResolver();
     cfg.CreateMap<BaseModel, BaseViewModel>()
          .Include<DerivedModel, DerivedViewModel>()
          .ForMember(d => d.Title, m => m.ResolveUsing(valueResolver).FromMember(s => s.Title));

    cfg.CreateMap<DerivedModel, DerivedViewModel>()
          .ForMember(d => d.Message, m => m.ResolveUsing(valueResolver).FromMember(s => s.Message));
});

Mapper.AssertConfigurationIsValid() // All okay!

class Converter
{
      public BaseViewModel Convert(BaseModel instance)
      {
              return Mapper.Map<BaseViewModel>(instance);
      }
}
```

The <code>ValueResolver</code> is responsible for resolving a translated value based on a key in the model.

After calling Map, the result's <code>Message</code> property has been correctly resolved, however the base <code>Title</code> property contains the original key value from the Model instance and not the expected resolved value. A Breakpoint in the <code>ValueResolver</code>'s <code>Resolve</code> method only stops once for the <code>Message</code> property.

Is this a bug, or are <code>ResolveUsing</code> mapping configurations not inherited?

I am using the AutoMapper 4.0.4.

**Comment by lbargaoanu** [comment]
See #719, but it's a feature request. So don't close the issue, @jbogard will do it if he so pleases :).

**Comment by jbogard** [comment]
I don't like this feature because inheriting configuration is quite tricky. You can't override this for example.
