### ISSUE TITLE
RT error calling CreateMap: Cannot find a field or property named X

### ISSUE THREAD

**Issue by Xiard** [AutoMapper/AutoMapper#844]
I am trying to run my app under AutoMapper 4.0.4 for the first time.  Previously this code was working on 3.3.1.  This is a Windows UWP app (actually a UWP class lib that is part of a larger UWP app solution), VS2015, on Windows 10.

I am calling CreateMap<UserInfoDTO, UserInfo>(). My UserInfoDTO class is a bare-bones DTO, and UserInfo is more of my domain model.  UserInfo has properties that shouldn't be mapped. 

When I execute, I'm getting this exception:

Exception thrown: 'System.ArgumentOutOfRangeException' in AutoMapper.dll
System.ArgumentOutOfRangeException: Cannot find a field or property named Errors
Parameter name: name
   at AutoMapper.Internal.MappingExpression`2.ForMember(String name, Action`1 memberOptions)
   at AutoMapper.ConfigurationStore.CreateMappingExpression[TSource,TDestination](TypeMap typeMap)
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList)
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName)
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination]()
   at AutoMapper.Mapper.CreateMap[TSource,TDestination]()
   at Xiard.MVVM.Core.CoreDTOManager.InitializeMappings()

The class hierarchy for UserInfo is UserInfo <- DomainObject <- ModelBase. 

ModelBase has the following Errors property:

        ObservableCollection<string> _errors = new ObservableCollection<string>();
        [SQLite.Net.Attributes.Ignore, AutoMapper.IgnoreMap]
        public ObservableCollection<string> Errors { get { return _errors; } }

From the error, it sounds like AutoMapper may be looking for an Errors property on UserInfoDTO (which doesn't exist). But I would have thought the AutoMapper.IgnoreMap attrbute would have taken care of that.

I'm fairly new to AutoMapper, so I don't know if there is something I need to be doing to configure AutoMapper specifically to handle this case.

Any idea what I'm doing wrong?

**Comment by Xiard** [comment]
I downloaded the code and was able to add AutoMapper.WPA81 to my solution and debug it directly.  The issue appears to be related to the fact that AutoMapper.TypeInfo.GetAllPublicMembers gets public members for all types up the inheritance chain (adding BaseTypes to typesToScan).  That seems reasonable.
But then the code in AutoMapper.ConfigurationStore::CreateMappingExpression that handles IgnoreMapAttribute gets hit.  That code calls mappingExp.ForMember, which ultimately calls TypeExtensions.GetProperty on my destination type (UserInfo in this case).  Here's that function:

        public static PropertyInfo GetProperty(this Type type, string name)
        {
            return type.GetTypeInfo().GetDeclaredProperty(name);
        }

GetDeclaredProperty will only return properties declared on the actual type, not properties declared on base types.  So the ModelBase.Errors property is found in GetAllPublicMembers, but it isn't found when the code tries to ignore it.
Not sure exactly what to do about that...but I'll probably add a TypeExtensions.GetPropertyDeep method for now that will walk up the BaseType looking for the property being requested, and then modify MappingExpression.ForMember to use that instead.  That seems the least likely to cause unexpected side effects for me.

**Comment by Xiard** [comment]
Super quick and dirty, but it got me back up and running:
        public static PropertyInfo GetPropertyDeep(this Type type, string name) {
            PropertyInfo pi = null;
            var walker = type;
            while (pi == null && walker != null) {
                pi = walker.GetTypeInfo().GetDeclaredProperty(name);
                walker = walker.BaseType();
            }
            return pi;
        }
And in MappingExpression:
        public IMappingExpression<TSource, TDestination> ForMember(
            string name,
            Action<IMemberConfigurationExpression<TSource>> memberOptions)
        {
            IMemberAccessor destMember = null;
            var propertyInfo = TypeMap.DestinationType.GetPropertyDeep(name);

**Comment by jbogard** [comment]
I'm going to just make sure that I go off of runtime members instead of declared members, that should fix this issue.

**Comment by Xiard** [comment]
Good deal.  Danke mucho.

**Comment by jbogard** [comment]
I just pushed a change, MyGet will have this version soon if you wouldn't mind testing it.

**Comment by Xiard** [comment]
This is my first time doing anything like this...so I don't know what MyGet is.  I assume it's a repository similar to nuget but for code that hasn't been released yet, or something like that?  I'd be happy to test it if you can help me out with that.

**Comment by Xiard** [comment]
Added https://www.myget.org/F/automapperdev/api/v2 to my package sources in Visual Studio, so that it shows up in Package Manager Console.  I'm guessing that's the right way to start?  Not sure what to do from there; "install-package AutoMapper" gives an error:

PM> install-package AutoMapper
install-package : Unable to find package 'AutoMapper'
At line:1 char:1
+ install-package AutoMapper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by Xiard** [comment]
NM...found it as a prerelease when I looked in NuGet Package Manager.  4.1.0-ci1007?  Digging that MyGet.

**Comment by Xiard** [comment]
Looks good.  I'm up and running with that version.  Got an estimate on a release date?  I'm hoping to submit my app to the Windows 10 store in the next couple of weeks.  If it won't be out in that time frame, how confident are you in me using the prerelease in shipping code?

**Comment by jbogard** [comment]
Yep that's the one!
