### ISSUE TITLE
Typo in xml comment

### ISSUE THREAD

**Issue by mangelarilla** [AutoMapper/AutoMapper#845]
/// <summary>
        /// Execute a custom function to the source and/or destination types before member mapping
        /// </summary>
        /// <param name="beforeFunction">Callback for the source/destination types</param>
        void BeforeMap(Action<object, object> beforeFunction);

        /// <summary>
        /// Execute a custom function to the source and/or destination types before member mapping
        /// </summary>
        /// <param name="afterFunction">Callback for the source/destination types</param>
        void AfterMap(Action<object, object> afterFunction);

In IMappingOperationOptions, I guess that "before" in AfterMap should be "after".

**Comment by lbargaoanu** [comment]
You can try a pull request :)

**Comment by lbargaoanu** [comment]
@mangelarilla Can you close your issue?
