### ISSUE TITLE
Mapper.Initialize() uses its own instance of IConfiguration

### ISSUE THREAD

**Issue by abatishchev** [AutoMapper/AutoMapper#854]
I try to make AM ti play nicely with a dependency injection container (such as SImpleInjector) so have the following configuration:

```csharp
Container container = new Container();

container.RegisterSingle<ITypeMapFactory, TypeMapFactory>();
container.RegisterAll<IObjectMapper>(MapperRegistry.Mappers);

container.RegisterSingle<ConfigurationStore>();
container.Register<IConfiguration>(container.GetInstance<ConfigurationStore>);
container.RegisterSingle<IConfigurationProvider>(container.GetInstance<ConfigurationStore>);

container.RegisterSingle<IMappingEngine>(() => new MappingEngine(container.GetInstance<IConfigurationProvider>()));
```

when I call

```csharp
Mapper.Initialize(c =>
	{
		c.ConstructServicesUsing(container.GetInstance);
		c.AddProfile<CsvCategoryMappingProfile>();
	});
```

the instance of `x` is different from what I would get from `container.GetInstance<IConfiguration>()`. How to get them in sync?

See also [How to register AutoMapper 4 with SimpleInjector 3](http://stackoverflow.com/questions/32189014/how-to-register-automapper-4-with-simpleinjector-3).

**Comment by jbogard** [comment]
That's because IConfiguration isn't a service. Instead of calling Mapper.Initialize, call container.GetInstance (or whatever) of that IConfiguration object. To AutoMapper, IConfiguration isn't a service. It's things used *during* mapping that AutoMapper considers services, not configuration types.
