### ISSUE TITLE
Bug Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by utillity** [AutoMapper/AutoMapper#855]
Hi,

I have defined a mapping like below. When executing the mapping `var fdsFlight = Mapper.Map<DB.Flight>(saveCtx.SourceFlight, opt => opt.Items.Add(OptionSaveContext, saveCtx));` I get the exception listed below. 

As you can see, it is trying to map my source flight Int32, instead of the target type. So I added another mapping `Mapper.CreateMap<Contract.Models.Flight, Int32>();` and suddenly the mapping works as expected (again).

# Exception
```C#
AutoMapper.AutoMapperMappingException was unhandled by user code
  HResult=-2146233088
  Message=Missing type map configuration or unsupported mapping.

Mapping types:
Flight -> Int32
FM.Contract.Models.Flight -> System.Int32

Destination path:
Flight

Source value:
FM.Contract.Models.Flight
  Source=AutoMapper
  StackTrace:
       bei AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
       bei AutoMapper.ConstructorMap.ResolveValue(ResolutionContext context, IMappingEngineRunner mappingEngine)
       bei AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.CreateObject(ResolutionContext context)
       bei AutoMapper.Mappers.TypeMapObjectMapperRegistry.NewObjectPropertyMapMappingStrategy.GetMappedObject(ResolutionContext context, IMappingEngineRunner mapper)
       bei AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
       bei AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
       bei AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
       bei AutoMapper.MappingEngine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)
       bei AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType, Action`1 opts)
       bei AutoMapper.MappingEngine.Map[TDestination](Object source, Action`1 opts)
       bei AutoMapper.Mapper.Map[TDestination](Object source, Action`1 opts)
       bei FM.DP.Tests.FdsServiceTests.TestMapping() in c:\DEV\DPFM\FM.DP.Tests\FdsServiceTests.cs:Zeile 44.
  InnerException: 
```

# Mapping
```C#
static FdsService()
{
	EnsureInitialized();
}

public static void EnsureInitialized()
{
	if (_initialized)
		return;
	_initialized = true;
	Mapper.CreateMap<Contract.Models.Flight, DB.Flight>()
		.ForMember(t => t.FlightId, opt => opt.ResolveUsing<FlightIdResolver>())
		.ForMember(t => t.ChecklistItems, opt => opt.ResolveUsing<ChecklistItemsResolver>())
		.ForMember(t => t.Coordinates, opt => opt.MapFrom(s => s.LocationGps))
		.ForMember(t => t.AircraftId, opt => opt.MapFrom(s => s.AircraftConfigurationId.Value))
		.ForMember(t => t.Location, opt => opt.ResolveUsing<LocationNameResolver>())
		.ForMember(t => t.Timers, opt => opt.ResolveUsing<TimersResolver>())
		.ForMember(t => t.TelemetryEntries, opt => opt.ResolveUsing<TelemetryEntriesResolver>())
		.ForMember(t => t.Remarks, opt => opt.ResolveUsing<RemarksResolver>())
		.ForMember(t => t.Xml, opt => opt.Ignore())
		.ForMember(t => t.CreatedAt, opt => opt.Ignore())
		.ForMember(t => t.Timestamp, opt => opt.Ignore())
		.ForMember(t => t.Aircraft, opt => opt.Ignore())
		.AfterMap(EnsureCoordinates)
		.AfterMap(AddFlightPathsAsEvents)
		;
	Mapper.CreateMap<FlightTimer, DB.FlightTimer>()
		.ForMember(t => t.Id, opt => opt.Ignore())
		.ForMember(t => t.CreatedAt, opt => opt.Ignore())
		.ForMember(t => t.Timestamp, opt => opt.Ignore())
		.ForMember(t => t.Flight, opt => opt.Ignore())
		.ForMember(t => t.FlightId, opt => opt.Ignore())
		;
	Mapper.CreateMap<FlightEvent, DB.Event>()
		.ForMember(t => t.Id, opt => opt.Ignore())
		.ForMember(t => t.CreatedAt, opt => opt.Ignore())
		.ForMember(t => t.Timestamp, opt => opt.Ignore())
		.ForMember(t => t.Flight, opt => opt.Ignore())
		.ForMember(t => t.FlightId, opt => opt.Ignore())
		.ForMember(t => t.FlightState, opt => opt.Ignore())
		.ForMember(t => t.Message, opt => opt.MapFrom(s => string.IsNullOrEmpty(s.Message) ? s.ToString() : s.Message))
		.ForMember(t => t.EventUtc, opt => opt.MapFrom(s => s.EventOccuredUtc))
		.ForMember(t => t.FlightStateId, opt => opt.ResolveUsing<FlightStateIdResolver>())
		;
	Mapper.CreateMap<Location, GeoCoordinate>()
		;
	Mapper.CreateMap<Track, DB.Event>()
		.ForMember(t => t.Category, opt => opt.UseValue("Flight-Track"))
		.ForMember(t => t.EventUtc, opt => opt.MapFrom(s => s.StartedAtUtc))
		.ForMember(t => t.Message, opt => opt.MapFrom(s => s.TrackName))
		.ForMember(t => t.Id, opt => opt.Ignore())
		.ForMember(t => t.CreatedAt, opt => opt.Ignore())
		.ForMember(t => t.Timestamp, opt => opt.Ignore())
		.ForMember(t => t.Flight, opt => opt.Ignore())
		.ForMember(t => t.FlightId, opt => opt.Ignore())
		.ForMember(t => t.FlightState, opt => opt.Ignore())
		.ForMember(t => t.FlightStateId, opt => opt.Ignore())
		;
}
```

**Comment by jrtheurer** [comment]
I have received this same error but with a Guid type using the newest version of AutoMapper.

**Comment by utillity** [comment]
@jrtheurer: does adding an empty map to the Guid as target solve your problem, too?

**Comment by jrtheurer** [comment]
No, adding an empty map does not seem to solve the problem for me but I'm not sure we have exactly the same scenarios.  I have added my exception detail to my previous comment.

**Comment by lbargaoanu** [comment]
A simple failing test would help.

**Comment by utillity** [comment]
I have one, but in my project - I can't compile AutoMapper because it uses syntax not known to my VS edition. I guess some kind of Post-Processor or something.

**Comment by lbargaoanu** [comment]
Make a gist, perhaps I can run it.

**Comment by minhn** [comment]
here's a gist that will reproduce the bug
https://gist.github.com/minhn/f877294705fe5e7aa2c8

Automapper 4.0.4
.NET 4.5.2

**Comment by lbargaoanu** [comment]
@minhn I don't see the connection between your problem and the original one, so why comment here? You can open your own issue :) Anyway, this seems to work now.

**Comment by minhn** [comment]
sorry i think i have the same issue as jrtheurer above, i'll open a new issue

**Comment by lbargaoanu** [comment]
@minhn  :) What I meant was that your issue seems solved, I don't know what's the original issue.

**Comment by utillity** [comment]
here is a gist - https://gist.github.com/utillity/a6de80359d298027657d
the Unit-Test "Mapping" succeeds, while the Test "Log" fails:

Debug Trace:
08:53:45 [Unit-Test] Info: This is test log-entry 1
Test method Core.ElabLoggingServiceTests.Log threw exception: 
System.AggregateException: One or more errors occurred. ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
LogItem -> Int32
Core.LogItem -> System.Int32

Destination path:
LogEntry

Source value:
Core.LogItem
    at Core.ElabLoggingService.<>c__DisplayClass1d.<Log>b__1c() in ElabLoggingService.cs: line 101
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Core.ElabLoggingService.<Log>d__1f.MoveNext() in ElabLoggingService.cs: line 99
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ElabLoggingServiceTests.Log() in ElabLoggingServiceTests.cs: line 25

**Comment by lbargaoanu** [comment]
That's definitely not a simple test :) Anyway, it seems to work on develop.

**Comment by utillity** [comment]
:) it happens in other constellations as well, but it's hard to isolate. I hope you can find/confirm with the latest official release to ensure it's fixed for the next release

**Comment by jbogard** [comment]
Can you try the MyGet releases? I put the CI builds up there instead of on NuGet.

**Comment by voroninp** [comment]
Had the same issue. Downgraded back to 3.1.3 (undo pending changes) but tests keep failing.<br/>

However, all tests pass when run on machines of my colleagues where 4.5.2 or 4.6 is not installed.

**Comment by PJPollard** [comment]
Hi,

I think I have the same issue: The constructor selected is different between 3.3.1 and 4.0.4. In 3.3.1, it takes into account the ignored properties before selecting the constructor - in 4.0.4 it uses the constructor with most parameters, even if they are ignored in configuration. Here's a simple console app as an example of what I mean:

https://gist.github.com/PJPollard/261b727927ac4f9061ba

If this is by design, is there a setting for this to alter the behaviour?

**Comment by lbargaoanu** [comment]
@utillity Can you close your issue?

**Comment by utillity** [comment]
well, it's a bug, right? So if it has to be fixed it must be closed when it has been fixed (and a new release has been made on NuGet). Others have the same issue as well. So maybe getting an official build on NuGet is a good thing after all. A fix without it being released is only half the solution ;)

**Comment by lbargaoanu** [comment]
When we have a fix, the issue is no longer useful. But never mind me :)

**Comment by utillity** [comment]
I'll close it :) - please release on NuGet, though!

**Comment by ptpavankumar-myob** [comment]
Hi, the issue has been closed 3days ago but the package hasn't been release:( When can we get the latest package?
