### ISSUE TITLE
Incorrect validation of map created with MemberList.Source and using postfixes

### ISSUE THREAD

**Issue by tomaskovarik** [AutoMapper/AutoMapper#859]
When a map is created with *MemberList.Source* as a parameter, **validation fails** that  *A.EthnicityKey* is not mapped. However. the result variable contains **correctly mapped data**. 
When the same map is created with *MemberList.Destination*, validation does not complain.
This happens in AutoMapper 4.0.4

    public class A { public string EthnicityKey { get; set; }  }
    public class B { public string Ethnicity { get; set; } }
    ...
    Mapper.Initialize(configuration =>
    {
        configuration.RecognizePostfixes("Key");
        configuration.RecognizeDestinationPostfixes("Key");

        Mapper.CreateMap<A, B>(MemberList.Source);
    });

    var result = Mapper.Map<A, B>(new A { EthnicityKey = "aaa" });
    Mapper.AssertConfigurationIsValid();

**Comment by lbargaoanu** [comment]
This seems to work now.

**Comment by tomaskovarik** [comment]
You are right. When I took latest source and tried on that, it worked. Will there be a new release soon on nuget? Or should I go with my custom build for now? Thank you.

**Comment by lbargaoanu** [comment]
The latest is [here](https://www.myget.org/F/automapperdev/api/v2).

**Comment by tomaskovarik** [comment]
Thank you.
