### ISSUE TITLE
Mapping types: List´1 -> List'1 exeption

### ISSUE THREAD

**Issue by Borgas77** [AutoMapper/AutoMapper#860]
Efter update from 3.3.1 to version 4.0.4.0 we recive following error efter a while. The only way to reset the error is to restart applikation. Then i works for a while agin. 
When we degrade version to 3.3.1 it works fine.

Mapping types:
List`1 -> List`1
System.Collections.Generic.List`1[[BOB.DO.Response.Location.StocklocationByItem, QuickPick.One, Version=1.0.15222.6, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[BOB.DO.Response.Location.StocklocationByItem, QuickPick.One, Version=1.0.15222.6, Culture=neutral, PublicKeyToken=null]]

Destination path:
StocklocationsByItem.Stocklocations.Stocklocations

Source value:
System.Collections.Generic.List`1[BOB.DO.Response.Location.StocklocationByItem]    at Apollo13.DAL.Mapper.Map[F,T](F FromObj)
   at BOB.Modules.Location.GetStocklocationsByItem[T](ByItem RequestObj)

**Comment by lbargaoanu** [comment]
A simple failing test would help.

**Comment by Borgas77** [comment]
Sorry! I dont understand. Do you meen Try catch?
I am useing now Try and catch by still if Automapp craches even with in try and catch it wont recover untill I restart my application.
And this is only in version 4.0.4.0. After downgradning it works fine.

**Comment by lbargaoanu** [comment]
I mean a simple failing example that would be easy for us to run and see the problem.

**Comment by Borgas77** [comment]
This line is cousing the exeption after executing for 50-200times.

//This will mapp serverResponse object to Typeof respondning object in method.
T ResponseObjs = Apollo13.DAL.Mapper.Map<BOB.DO.Response.Location.StocklocationsByItem, T>(ServerResponsObjs);
In this case BOB.DO.Response.Location.StocklocationsByItem is same as T

This is my Mapper class
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Apollo13.DAL
{
    public class Mapper
    {
        /// <summary>
        /// Map from entity to entity
        /// </summary>
        /// <typeparam name="F">From Type</typeparam>
        /// <typeparam name="T">To Type</typeparam>
        /// <param name="FromObj">From object</param>
        /// <param name="ToObj">To Object</param>
        public static T Map<F,T>(F FromObj)
        {
            try
            {
                AutoMapper.Mapper.CreateMap<F, T>();
                return AutoMapper.Mapper.DynamicMap<F, T>(FromObj);

            }
            catch (Exception)
            {
                
                throw;
            }
            

        }


        /// <summary>
        /// Map from List entity to List entity
        /// </summary>
        /// <typeparam name="F">From Object</typeparam>
        /// <typeparam name="T">To object</typeparam>
        /// <param name="FromObjs">From List object</param>
        /// <returns>Retruns To list object</returns>
        public static IList<T> Map<F, T>(IList<F> FromObjs)
        {
            try
            {
                IList<T> ToObjs = new List<T>();
                foreach (F fromObj in FromObjs)
                {
                    ToObjs.Add(Map<F, T>(fromObj));
                }
                return ToObjs;
            }
            catch (Exception)
            {
                
                throw;
            }
        }
         
    }
}







My Do objects

 [DataContract(Name = "Response_Stocklocations_ByItem")]
    [ClassAttribute(DisplayName = "GetStocklocationsByItem")]
    public class StocklocationsByItem : DOResponseBase
    {

        [DataMember]
        public string ItemNo { get; set; }

        [DataMember]
        public string Barcode { get; set; } //2013-12-05

        [DataMember]
        public string ItemDescription { get; set; }

        [DataMember]
        public int ID { get; set; } 

        [DataMember]
        public List<StocklocationByItem> Stocklocations { get; set; }
        //List<StocklocationByItem> Items = new List<StocklocationByItem>();
    }



[DataContract(Name = "Response_Stocklocation_ByItem")]
    [ClassAttribute(DisplayName = "GetStocklocationByItem")]
    public class StocklocationByItem : DOResponseBase
    {
        [DataMember()]
        public int LocationID { get; set; }

        [DataMember()]
        public int ID { get; set; } //2014-08-25 Özlem 

        [DataMember]
        [PropertyAttribute(UseWhenLogging = true)]
        public string Stocklocation { get; set; }

        [DataMember]
        public string StocklocationRef { get; set; }

        [DataMember]
        public string StocklocationSize { get; set; }

        [DataMember]
        [PropertyAttribute(UseWhenLogging = true)]
        public string Warehouse { get; set; }

        [DataMember]
        [PropertyAttribute(UseWhenLogging = true)]
        public string Zone { get; set; }

        [DataMember]
        [PropertyAttribute(UseWhenLogging = true)]
        public string Site { get; set; }

        [DataMember()]
        public string Batch { get; set; }

        [DataMember()]
        public string Serial { get; set; }

        [DataMember()]
        public decimal Balance { get; set; }

        [DataMember()]
        public int Order { get; set; }

        [DataMember()]
        public DateTime UpdateDate { get; set; }

        [DataMember()]
        public DateTime CreateDate { get; set; }

        [DataMember()]
        public string FIFO { get; set; }

        [DataMember()]
        public string Barcode { get; set; }

        [DataMember()]
        public decimal Multiple { get; set; }

        [DataMember()]
        public decimal PricePerUnit { get; set; }

        [DataMember()]
        public string Currency { get; set; }

        [DataMember()]
        public string ItemDescription { get; set; }

        [DataMember()]
        public int ItemID { get; set; }

        [DataMember()]
        public string ItemNo { get; set; }

        [DataMember()]
        public string ClientViewObject { get; set; }

        [DataMember()]
        public string PackageUnits { get; set; }

        [DataMember()]
        public string PackageNames { get; set; }

        [DataMember()]
        public string PackageUnit { get; set; }

        [DataMember()]
        public string PackageName { get; set; }

        [DataMember()]
        public DateTime? LastInventoriedDate { get; set; }

        [DataMember()]
        public bool? IsRecommendedLocation { get; set; } // IsDefault Location

        [DataMember()]
        public string Key { get; set; }

        [DataMember()]
        public decimal MinValue { get; set; }//2015-04-07 Özlem ex: Coca Cola min :20 st max:100 st på plats 001 //min :50 st max:100 st på plats 002

        [DataMember()]
        public decimal MaxValue { get; set; }//2015-04-07 Özlem

        [DataMember()]
        public decimal AvailableQuantity { get; set; } //2015-07-21 Boris 
    }



[DataContract(Name = "Response_ResponseBase")]
    public class DOResponseBase: DOBase
    {
        public DOResponseBase()
        {
            Message = "OK";
            MessageType =  QPEnums.Enums.MessageType.NoError;
        }

        public DOResponseBase(string _message, string _exception, QPEnums.Enums.MessageType _MessageType)
        {
            Message = _message;
            MessageEx = _exception;
            MessageType = _MessageType;
        }

        public DOResponseBase(string _message, QPEnums.Enums.MessageType _MessageType)
        {
            Message = _message;
            MessageEx = _message;
            MessageType = _MessageType;
        }

        [DataMember()]
        public string MessageEx { get; set; }

        [DataMember()]
        public string Message { get; set; }

        [DataMember()]
        public QPEnums.Enums.MessageType MessageType { get; set; }

        
    }




[DataContract(Name = "Base")]
    public class DOBase
    {

    }

**Comment by lbargaoanu** [comment]
You can use either CreateMap or DynamicMap, not both. With CreateMap, you have to create the maps  once when you initialize your app and then call Mapper.Map whenever you need to. With DynamicMap, you simpy call DynamicMap when you need to, there is no need to create the maps beforehand.

**Comment by Borgas77** [comment]
Ok!

That i can current!
But is that realy the issu in My case?




8 sep 2015 kl. 21:12 skrev Lucian Bargaoanu <notifications@github.com<mailto:notifications@github.com>>:


You can use either CreateMap or DynamicMap, not both. With CreateMap, you have to create the maps once when you initialize your app and then call Mapper.Map whenever you need to. With DynamicMap, you simpy call DynamicMap when you need to, there is no need to create the maps beforehand.

**Comment by Borgas77** [comment]
Is there an performance issu between CreateMap and DynamicMap?

Från: Lucian Bargaoanu [mailto:notifications@github.com]
Skickat: den 8 september 2015 21:12
Till: AutoMapper/AutoMapper <AutoMapper@noreply.github.com>
Kopia: Boris Gasic <boris.gasic@qsys.se>
Ämne: Re: [AutoMapper] Mapping types: List´1 -> List'1 exeption (#860)


You can use either CreateMap or DynamicMap, not both. With CreateMap, you have to create the maps once when you initialize your app and then call Mapper.Map whenever you need to. With DynamicMap, you simpy call DynamicMap when you need to, there is no need to create the maps beforehand.

**Comment by lbargaoanu** [comment]
Well, yes. After you call Mapper.Initialize and config.CreateMap, the configuration is sealed. If you call DynamicMap this work is being done whenever a new type pair to map is found.

**Comment by jbogard** [comment]
Yes, DON'T use DynamicMap unless you actually don't know the types initially. Instead, call Mapper.Initalize once per app domain (use `Lazy<T>` to help if you need to call it on every service call).
