### ISSUE TITLE
when mapper   Expression<Func<UserInfo, UserInfo>>  have error

### ISSUE THREAD

**Issue by yangmail2002** [AutoMapper/AutoMapper#863]
I have three class

```
 public partial class DTOUserInfo
    {
        public int Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public int User_ID { get; set; }
        public string User_Account { get; set; }
        public string User_Name { get; set; }
        public string User_Spelling { get; set; }
        public string Sex { get; set; }

    }

    public partial class UserInfo
    {
        public int User_ID { get; set; }
        public Nullable<int> Organization_ID { get; set; }
        public string User_Account { get; set; }
        public string User_Pwd { get; set; }
        public string User_Name { get; set; }
        public string User_Spelling { get; set; }
        public Nullable<int> User_Sex { get; set; }
        public string User_Email { get; set; }
        public string User_Tel { get; set; }
        public string User_Telphone { get; set; }
        public Nullable<System.DateTime> User_CreatedTime { get; set; }
        public string User_Post { get; set; }
        public string User_PostRemark { get; set; }
        public string User_Operator { get; set; }
        public string User_RoleValue { get; set; }
        public string User_Remark { get; set; }
        public Nullable<int> User_Status { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int Organization_ID { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_User_Name { get; set; }
        public string Organization_Tel { get; set; }
        public string Organization_Telphone { get; set; }
        public string Organization_Fax { get; set; }
        public string Organization_Code { get; set; }
        public string Organization_Address { get; set; }
        public Nullable<int> Organization_PanelID { get; set; }
        public Nullable<int> Organization_Order { get; set; }
        public Nullable<System.DateTime> Organization_CreatedTime { get; set; }
        public string Organization_Remark { get; set; }
        public Nullable<int> Organization_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }


 Mapper.Initialize(cfg =>
                {
                    //Mapper.CreateMap<UserInfo, DTOUserInfo>()
                    //.ForMember(dto=>dto.
                    Mapper.CreateMap<UserInfo, DTOUserInfo>()
                          .ForMember(dto => dto.Organization_ID, conf => conf.MapFrom(ol =>ol.Organization.Organization_ID))
                          .ForMember(dto => dto.Organization_Name, conf => conf.MapFrom(ol =>ol.Organization.Organization_Name))
                          .ForMember(dto => dto.Sex, conf => conf.MapFrom(ol => (ol.User_Sex == null || ol.User_Sex == 0 ? "男" : "女")))   ;


                    Mapper.CreateMap<DTOUserInfo, UserInfo>()
                        .ForMember(u => u.Organization_ID, conf => conf.MapFrom(ol => ol.Organization_ID))
                        .ForMember(u => u.User_Sex, conf => conf.MapFrom(ol => (ol.Sex == null || ol.Sex == "女" ? 1 : 0))) ;
                });
```
i have a express:
```
   Expression<Func<DTOUserInfo, DTOUserInfo>> updateExp = c => new DTOUserInfo { User_Spelling = "UserSpelling" };
```
Where I execute the cmd
```
  Expression<Func<UserInfo, UserInfo>> updateExpT =
                    Mapper.Map<Expression<Func<UserInfo, UserInfo>>>(updateExp);
```

it have a error:
```
无法将类型为“System.Linq.Expressions.Expression`1[System.Func`2[YzDALLibsUnitTestProject3.YZ.DAL.UserInfo,
 YzDALLibsUnitTestProject3.YZ.DAL.DTOUserInfo]]”的对象强制转换为类型“System.Linq.Expressions.Expression`1[System.Func`2[YzDALLibsUnitTestProject3.YZ.DAL.UserInfo
,YzDALLibsUnitTestProject3.YZ.DAL.UserInfo]]"
```

**Comment by jbogard** [comment]
In your Initialize method, instead of calling Mapper.CreateMap, call "cfg.CreateMap".

**Comment by yangmail2002** [comment]
first ,thank your answer.
I Modify my code  as follow:
Mapper.Initialize(cfg =>
                {

                    //Mapper.CreateMap<UserInfo, DTOUserInfo>()
                    //.ForMember(dto=>dto.
                    cfg.CreateMap<UserInfo, DTOUserInfo>()
                          .ForMember(dto => dto.Organization_ID, conf => conf.MapFrom(ol => ol.Organization.Organization_ID))
                          .ForMember(dto => dto.Organization_Name, conf => conf.MapFrom(ol => ol.Organization.Organization_Name))
                          .ForMember(dto => dto.Sex, conf => conf.MapFrom(ol => (ol.User_Sex == null || ol.User_Sex == 0 ? "男" : "女")))
                          ;


                    cfg.CreateMap<DTOUserInfo, UserInfo>()
                        .ForMember(u => u.Organization_ID, conf => conf.MapFrom(ol => ol.Organization_ID))
                        .ForMember(u => u.User_Sex, conf => conf.MapFrom(ol => (ol.Sex == null || ol.Sex == "女" ? 1 : 0)))
                     ;
                });

the error  display too:

无法将类型为“System.Linq.Expressions.Expression`1[System.Func`2[YzDALLibsUnitTestProject3.YZ.DAL.UserInfo,
 YzDALLibsUnitTestProject3.YZ.DAL.DTOUserInfo]]”的对象强制转换为类型“System.Linq.Expressions.Expression`1[System.Func`2[YzDALLibsUnitTestProject3.YZ.DAL.UserInfo
,YzDALLibsUnitTestProject3.YZ.DAL.UserInfo]]"

**Comment by TylerCarlson1** [comment]
looks like code actually calls
```
Expression<Func<UserInfo, UserInfoDTO>> updateExpT =
                    Mapper.Map<Expression<Func<UserInfo, UserInfo>>>(updateExp);
```
or
```
Expression<Func<UserInfo, UserInfo>> updateExpT =
                    Mapper.Map<Expression<Func<UserInfo, UserInfoDTO>>>(updateExp);
```
needs to be more like
```
Expression<Func<UserInfo, UserInfo>> updateExpT =
                    Mapper.Map<Expression<Func<UserInfoDTO, UserInfoDTO>>>(updateExp);
```
If you are trying to convert UserInfo to UserInfoDTO.  I would suggest
`db.UserInfos.ProjectTo<UserInfoDTO>()` or `db.UserInfos.UseAsDataSource().For<UserInfoDTO>()`

**Comment by yangmail2002** [comment]
thanks very much
  i don't need convert userinfo to userinfodto

the param is Expression<Func<DTOUserInfo, DTOUserInfo>> 
but i need call  db.UserInfo.Update(updateExp);
updateExp is Expression<Func<UserInfo, UserInfo>> type
so i need to convert "
Expression<Func<DTOUserInfo, DTOUserInfo>> updateExp = c => new DTOUserInfo { User_Spelling = "UserSpelling" }  "   to  "Expression<Func<UserInfo, UserInfo>>"

when I execute follow cmd:

   Expression<Func<DTOUserInfo, DTOUserInfo>> updateExp = c => new DTOUserInfo { User_Spelling = "UserSpelling" };
                Expression<Func<UserInfo, UserInfo>> updateExpT =Mapper.Map<Expression<Func<UserInfo, UserInfo>>>(updateExp);

it show me errors as you see.

but the follow code works well:
  Expression<Func<DTOUserInfo, bool>> exp = c => c.Organization_Name.StartsWith("生产部");
 var expression = Mapper.Map<Expression<Func<UserInfo, bool>>>(condition)



is it bugs of automapper

**Comment by yangmail2002** [comment]
thanks very much
  i don't need convert userinfo to userinfodto

the param is  
Expression < Func < DTOUserInfo, DTOUserInfo > > 
but i need call  db.UserInfo.Update(updateExp);
updateExp is type of
 "Expression < Func < UserInfo, UserInfo > >" .

so i need to convert "
Expression< Func < DTOUserInfo, DTOUserInf o> > updateExp = c => new DTOUserInfo { User_Spelling = "UserSpelling" }  "   to  "Expression< Func< UserInfo, UserInfo > >"

when I execute follow cmd:

   Expression<Func<DTOUserInfo, DTOUserInfo>> updateExp = c => new DTOUserInfo { User_Spelling = "UserSpelling" };
                Expression< Func < UserInfo, UserInfo > > updateExpT =Mapper.Map< Expression< Func< UserInfo, UserInfo > > >(updateExp);

it show me errors as you see.

but the follow code works well:
  Expression< Func< DTOUserInfo , bool > > exp = c => c.Organization_Name.StartsWith("生产部");
 var expression = Mapper.Map< Expression< Func< UserInfo, bool > > >(condition)



is it bugs of automapper

**Comment by TylerCarlson1** [comment]
Ok I think I get it  now.

It's probably an AutoMapper Bug.
It doesn't know how to convert `new DTOUserInfo` to `new DTOUser`

Never seen any code use this.  Have no test case for this.

**Comment by jbogard** [comment]
I guess I'm confused here, I see configuration for mapping two entities, then the Mapper.Map is for mapping an expression that takes a DTO and returns a DTO to an expression that takes an entity and returns an entity.

How is this expression actually used?

**Comment by TylerCarlson1** [comment]
I'm confused as to how this is used as well.
My only guess would be to clone an object over with certain properties of the original to be reused.
Probably not showing the copy of properties from one object to another because they aren't needed to show the exception.

**Comment by yangmail2002** [comment]
Do you know about  "EntityFramework.Extended"
the link is https://github.com/loresoft/EntityFramework.Extended

it has "Batch Update and Delete" .

 
![image](https://cloud.githubusercontent.com/assets/7591969/9595655/9d74fba6-509b-11e5-9325-b0a97fcd72f1.png)


So I want to use these functions for Dto and Entity

**Comment by jbogard** [comment]
Ohhhhhhhhhh this is interesting, I've used that library but not this feature. I'll have to test this in an integration test with EF up and running to see what's going on here. For now - I don't think your scenario is supported today.

**Comment by yangmail2002** [comment]
thank you very ,

**Comment by TylerCarlson1** [comment]
It's definitely NewExpression not being translated.
Can translate the new expression by itself just fine, but translating the rest is tricky.
There's the possible translation of the constructor and it's arguments, and for arguments passed in to set the members.

**Comment by yangmail2002** [comment]
Will it be supported??? 
or is it a bug?

**Comment by jbogard** [comment]
It's not a bug, it's never been an intended scenario.

When will it be supported? Since it's not a scenario I need, when I get a pull request.
