### ISSUE TITLE
Support for a list of objects to DataTable

### ISSUE THREAD

**Issue by cknightdevelopment** [AutoMapper/AutoMapper#864]
I am not sure if this is the correct forum for this, so please redirect me as needed. I am curious if there are plans for support of dynamically mapping a list of objects to a datatable with AutoMapper? For example, taking a list of Person objects and mapping them to a DataTable in custom ways depending on a given mapping profile. If not, I am curious if you would consider adding this as a future pull request if I worked on it with your guidance. I have been working a separate project called TableTranslator (https://github.com/cknightdevelopment/TableTranslator) that does just this sort of thing. The more I think about it, the more I think this might be a nice addition or extension to AutoMapper. What are your thoughts? I would be happy to discuss this more with you.

**Comment by cknightdevelopment** [comment]
Should this be asked elsewhere?

**Comment by jbogard** [comment]
AutoMapper.Data I think is a better fit here?
