### ISSUE TITLE
I can not Map multi collection object  How to I do ?

### ISSUE THREAD

**Issue by yaochangyu** [AutoMapper/AutoMapper#865]
I have three DTO

```c#
public class People
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class Phone
{
    public string Number { get; set; }
}

public class PeoplePhoneDto
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string PhoneNumber { get; set; }
}
```
I can map single object
```c#
[TestMethod]
public void TestMethod1()
{
    var expected = new PeoplePhoneDto() { FirstName = "first", LastName = "last", PhoneNumber = "1234" };
    Mapper.CreateMap<People, PeoplePhoneDto>();
    Mapper.CreateMap<Phone, PeoplePhoneDto>().ForMember(d => d.PhoneNumber, a => a.MapFrom(s => s.Number));
    var people = new People() { FirstName = "first", LastName = "last" };
    var phone = new Phone() { Number = "1234" };
    var dto = new PeoplePhoneDto();
    Mapper.Map<People, PeoplePhoneDto>(people, dto);
    Mapper.Map<Phone, PeoplePhoneDto>(phone, dto);
    expected.ShouldBeEquivalentTo(dto);
}
```

But, I can not map multi collection object
```c#
[TestMethod]
public void TestMethod2()
{
    var expected = new List<PeoplePhoneDto>() { new PeoplePhoneDto() { FirstName = "first", LastName = "last", PhoneNumber = "1234" } };
    Mapper.CreateMap<People, PeoplePhoneDto>();
    Mapper.CreateMap<Phone, PeoplePhoneDto>().ForMember(d => d.PhoneNumber, a => a.MapFrom(s => s.Number));
    var peoples = new List<People>() { new People() { FirstName = "first", LastName = "last" } };
    var phones = new List<Phone>() { new Phone() { Number = "1234" } };
    var dtos = new List<PeoplePhoneDto>();
    Mapper.Map<List<People>, List<PeoplePhoneDto>>(peoples, dtos);
    //Mapper.Map<List<Phone>, List<PeoplePhoneDto>>(phones, dtos);
    dtos = Mapper.Map<List<Phone>, List<PeoplePhoneDto>>(phones);
    expected.ShouldBeEquivalentTo(dtos);
}
```

**Comment by lbargaoanu** [comment]
And how does it fail?

**Comment by yaochangyu** [comment]
HI,
first, the dtos success get peoples value
second, the dtos of people be clear

[TestMethod]
public void TestMethod2()
{
    var expected = new List<PeoplePhoneDto>() { new PeoplePhoneDto() { FirstName = "first", LastName = "last", PhoneNumber = "1234" } };
    Mapper.CreateMap<People, PeoplePhoneDto>();
    Mapper.CreateMap<Phone, PeoplePhoneDto>().ForMember(d => d.PhoneNumber, a => a.MapFrom(s => s.Number));
    var peoples = new List<People>() { new People() { FirstName = "first", LastName = "last" } };
    var phones = new List<Phone>() { new Phone() { Number = "1234" } };
    var dtos = new List<PeoplePhoneDto>();
    Mapper.Map<List<People>, List<PeoplePhoneDto>>(peoples, dtos);
    //Mapper.Map<List<Phone>, List<PeoplePhoneDto>>(phones, dtos);
    dtos = Mapper.Map<List<Phone>, List<PeoplePhoneDto>>(phones);
    expected.ShouldBeEquivalentTo(dtos);
}

**Comment by lbargaoanu** [comment]
Maybe it's not the right test :) Because you map from Phone which has only a Number to PeoplePhoneDto which also has names. So you get a number, but not the names. That makes sense to me.

**Comment by jbogard** [comment]
Yeah, AutoMapper can't merge three things, it's just for two objects.
