### ISSUE TITLE
Mapping Dynamic Object to an Entity Framework DataObject

### ISSUE THREAD

**Issue by tsramanathan** [AutoMapper/AutoMapper#866]
I am trying to perform an update action in which are using partial updates.  The Incoming object is a dynamic object with lesser properties compared to the EF Data object, when we try to use the DynamicMap, it nullfies the properties that are not being passed from dynamic request 

Here is the below example

dynamic  = {"prop1": "value1", 
                     "prop2":"value2"}
Account = {prop1,
                 prop2,
                 prop3,
                 prop4}

Dynamic dynamic = {incoming request} 
Account account = Get(id); (It has the original values)
Mapper.DynamicMap(dynamic, account); (Expected only to change the couple of properties)

In the above it nullifies prop3 & prop4. Is my usage of Dynamic Map correct?  or Is this not the expected functionality of DynamicMap?  

Thanks in Advance!

**Comment by lbargaoanu** [comment]
No, it's just similar names :) But sounds reasonable as a request for Mapper.Map.

**Comment by lbargaoanu** [comment]
@jbogard A [silly gist](https://gist.github.com/lbargaoanu/8cc2a4a7dd0e35b8ef21#file-dynamictoobject-cs). But I've heard the idea before. I think something like this could be useful. Perhaps a built in mapper.

**Comment by tsramanathan** [comment]
Thank you for your reply!  Is this something you think we could add perhaps to Automapper functionality? We have a great requirement in our projects.  

Thanks Again!

**Comment by jbogard** [comment]
@lbargaoanu Yeah, a custom IObjectMapper is likely here, to map from `IDictionary<string, object>` to object I think.

**Comment by lbargaoanu** [comment]
@jbogard Do we want to map only properties that exist on the dynamic source object?

**Comment by tsramanathan** [comment]
Yes that is correct.  So the workflow is:
1. Retrieve the existing data from DB
2. Map the source dynamic object with only incoming properties (Partial Update)
3. Then save the modified data back to DB

Thanks again! Ram

**Comment by jbogard** [comment]
@lbargaoanu Yeah I agree - that's why I wonder if this could be solved with simply some mapper that goes from `IDictionary<string, object>` -> `object`, pretty much how the MVC model binder works.

**Comment by tsramanathan** [comment]
I think we tried this approach.  But when I used the Automapper Map, it nullifies the original properties that is not being passed.  We are trying to avoid creating an custom mapping object using IDictionary as we use Automapper for every other scenario.  If we could get this feature from Automapper out of the box, that would be great.  

Thanks

**Comment by lbargaoanu** [comment]
@jbogard IDictionary helps only if ExpandoObject is our only concern. Dynamic objects in general have to implement just IDynamicMetaObjectProvider.

**Comment by lbargaoanu** [comment]
@jbogard So forget about the general case and just map from IDictionary?

**Comment by tsramanathan** [comment]
Jim -  I am attaching a code snippet below for your review.  This is the custom mapping extension I was mentioning to you earlier using the IMappingEngine interface.  Instead I am looking into using Mapper.Map object directly to have this functionality.

public static class AutomapperExtensions

    {

        public static T DynamicDTOMap<T>(this IMappingEngine mappingEngine, ExpandoObject source, T destination)

        {

            var propertyMap = typeof(T).GetProperties().ToDictionary(p => p.Name.ToLower(), p => p);

             if (source == null)
                    throw new ArgumentNullException("source");
                if (destination == null)
                    throw new ArgumentNullException("destination");

                // By iterating the KeyValuePair<string, object> of
                // source we can avoid manually searching the keys of
                // source as we see in your original code.
                foreach (var kv in source)
                {
                    PropertyInfo p;
                    if (propertyMap.TryGetValue(kv.Key.ToLower(), out p))
                    {
                        var propType = p.PropertyType;
                        if (kv.Value == null)
                        {
                            if (!propType.IsByRef && propType.Name != "Nullable`1")
                            {
                                // Throw if type is a value type 
                                // but not Nullable<>
                                throw new ArgumentException("not nullable");
                            }
                        }
                        else if (kv.Value.GetType() != propType)
                        {
                            // You could make this a bit less strict 
                            // but I don't recommend it.
                            throw new ArgumentException("type mismatch");
                        }
                        p.SetValue(destination, kv.Value, null);
                    }
                }

            return mappingEngine.Map<T>(destination);
        }
    }

**Comment by jbogard** [comment]
@lbargaoanu maybe, let's start with this though.

**Comment by tsramanathan** [comment]
Okay,  do you think this could be integrated with Automapper?
Thanks
