### ISSUE TITLE
Strange exceptions mapping enums

### ISSUE THREAD

**Issue by TioLuiso** [AutoMapper/AutoMapper#867]
Hello. First of all awesome work

Second. I have tried to check if this issue is reported. Haven't found anything.

Then the real thing. I am creating a UWP application. I am creating most of the applications as PCLs, and will create just the presentation with UWP Project.

The problem arose when I tried to call AssertConfigurationIsValid in my Brand new UWP Project. An StackOverflowException was thrown. Which was strange, because I have like 300 tests. They are .NET tests, not UWP, that's certain.

I have tried to remove and remove code until I found the problem. And it was an enum in one of the entities. If I remove it, it Works.
I have reduced it all to a simple test solution with 3 projects:
- A pcl with an entity with a single property that is an enum
- A regular .NET class library with a XUnit test that creates a map, seals the configuration and calls AssertConfigurationIsValid. It Works.
- A regular UWP class library with a XUnit test that creates a map, seals the configuration and calls AssertConfigurationIsValid. It throws an StackOverflowException.

In both cases the code is the same:

Mapper.CreateMap&lt;XElement, MyEntity&gt;().ForMember(dest => dest.MyEnum, opt => opt.UseValue(MyEnum.Value1));
            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();

**Comment by lbargaoanu** [comment]
#841?

**Comment by TioLuiso** [comment]
Looks like it should be it. Sorry for not finding it. Anyway, I entered the pachage source https://www.myget.org/F/automapperdev/api/v2, and visual studio tells me there is no package there.

**Comment by TioLuiso** [comment]
I have found the way. Looks like no package is listed, but using the console and specifying the versión Works. And yes, the problem is solved

Thanks a huge lot

**Comment by jbogard** [comment]
Make sure to check "prerelease"

**Comment by TioLuiso** [comment]
Even with it checked, it showed no package. Weird thing. However, the console did the trick :)
