### ISSUE TITLE
As<>() is completely ignored. Can't specify subtypes to use in mapping. 

### ISSUE THREAD

**Issue by martinlong1978** [AutoMapper/AutoMapper#868]
In a previous version we used to use "As" to specify subtypes to use when mapping to a base type (which could be abstract or an interface in some cases). 
```
            Mapper.CreateMap<SubA, SubB>();
            Mapper.CreateMap<SubA, BaseB>().As<SubB>();
```
However, why mapping field of the base type in a object (or directly, as in the example below), it ignores the "As" and just constructs the base type. 

This is quite a major regression for us as we use this pattern a lot. Full example below. 
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            //Mapper.CreateMap<BaseA, BaseB>();
            Mapper.CreateMap<SubA, SubB>();
            Mapper.CreateMap<SubA, BaseB>().As<SubB>();

            var mapped1 = Mapper.Map<SubB>(new SubA() { Name = "Martin", Description = "Hello" });
            Debug.WriteLine(mapped1.GetType());

            var mapped2 = Mapper.Map<BaseB>(new SubA() { Name = "Martin", Description = "Hello" });
            Debug.WriteLine(mapped2.GetType());
        }
    }

    public class BaseA
    {
        public string Name { get; set; }
    }

    public class BaseB
    {
        public string Name { get; set; }

    }

    public class SubA : BaseA
    {
        public string Description { get; set; }
    }

    public class SubB : BaseB
    {
        public string Description { get; set; }

    }
}
```

**Comment by lbargaoanu** [comment]
Did you try this on develop?

**Comment by martinlong1978** [comment]
Having trouble building develop, but I've been doing it on the latest nightly. 

Interestingly, using Mapper.Initialize works correctly. We use separate mapper instances with slightly different profiles loaded, and that also works correctly in my test app, but doesn't in my real app - I need to figure out why this is the case. 

Final point - is the method in the example above no longer supported, in favour of the Initialize method?  I guess my point is that if it is broken then it ought to be deprecated/removed or else fixed.

**Comment by lbargaoanu** [comment]
The docs say about Initialize, "This is the preferred means to configure AutoMapper". It usually works your way too :) About deprecating Mapper.CreateMap, @jbogard is in charge. But I would guess that a lot of people would be annoyed by the warnings. It's true that we've already annoyed a lot of people :)

**Comment by jbogard** [comment]
@martinlong1978 you can also use the MyGet pre-release instead of building from source

**Comment by jbogard** [comment]
@lbargaoanu Also I think the way we can handle this is do something like Mapper.Seal() or Mapper.Configuration.Seal(). All that inheritance junk was just too crazy to try and figure out on the fly.

**Comment by TylerCarlson1** [comment]
I think all that needs to be done is sealing the type map using the destination type override when sealing a type map.  I wasn't aware of that having a type map map used when I wrote the code to seal all type maps associated to a typemap before calling Map.

Thing is what's the best way to get the type map from the overrideType to seal it?  Mapper.Config.GetTypeMapFor(typemap)?

**Comment by jbogard** [comment]
@TylerCarlson1 Yep but you still can't call that until all CreateMap's are done.

**Comment by TylerCarlson1** [comment]
Well I can call it after the proper DestinationTypeOverride map is made and it should work.  I would get the type map from user defined type maps list, not the cached type maps that are sealed, so it would be defined but not sealed at that point.
I would assume you would define the type map of the derived type before you call Mapper.Map.
And if not then well it should not work anyways and the user has to fix the code so map what you want to use before calling map.

**Comment by martinlong1978** [comment]
@jbogard Yes, MyGet is what I meant by "latest nightly". So far I haven't been able to come up with a decent explanation why I can't reproduce the issue on the sample application when using: 

                        var configurationStore = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);

                        configurationStore.CreateMap<SubA, SubB>();
                        configurationStore.CreateMap<SubA, BaseB>().As<SubB>();
                        configurationStore.CreateMap<Container, Container2>();
                        configurationStore.Seal();

                        var engine = new MappingEngine(configurationStore);

This is the way our live application initialises mappers, and yet it does show the incorrect behaviour.

**Comment by martinlong1978** [comment]
Ok, Seal() works correctly so I'm happy to close this issue. 

I found the difference between my two projects was due to a DynamicProxy from EF, and this seems to have exposed another bug. I'll raise a new issue for that.

**Comment by wstaelens** [comment]
see comments on issue #999
