### ISSUE TITLE
Error when manually resolving collection elements with inheritance mapping defined

### ISSUE THREAD

**Issue by olegtarasov** [AutoMapper/AutoMapper#870]
Hi!

Consider the following code:

```csharp
public class Ancestor
{
	public int Prop { get; set; }
}

public class Foo : Ancestor
{
	public Foo(string a)
	{
		A = a;
	}

	public string A { get; set; }
}

public class Bar
{
	public IReadOnlyCollection<Foo> Foos { get; set; }
}

public class Baz
{
	public IReadOnlyCollection<Foo> Foos { get; set; }
}

[TestClass]
public class Test
{
	[TestMethod]
	public void Test1()
	{
		Mapper.CreateMap<Ancestor, Foo>();
		Mapper.CreateMap<Bar, Baz>()
			.ForMember(x => x.Foos, e => e.ResolveUsing(x => x.Foos));

		var ancestors = Enumerable.Range(0, 10).Select(x => new Ancestor {Prop = 42}).ToList();
		var bar = new Bar
				{
					Foos = ancestors.Select(x =>
					{
						var result = new Foo(Guid.NewGuid().ToString("N"));
						Mapper.Map(x, result);
						return result;
					}).ToList()
				};

		var t = Mapper.Map<Baz>(bar);
	}
}
```

As you can see, Foo inherits from Ancestor and requires some custom data to be passed to its constructor. I create those objects manually and then map values from Ancestor to Foo with AutoMapper. I also have two classes, both of them contain collections of Foos. As I'm aware of the fact that AutoMapper wouldn't be able to construct Foos on its own, I just want to copy those collections from one object to another. But when I try to map between Bar and Baz, I get an exception.
Here's what happens. Automapper does its magic and at some point arrives to `TypeMap ResolveTypeMap(TypePair typePair)` method. When there are no mappings defined that include type's ancestor (Ancestor in the case of Foo), AutoMapper will copy the value by reference. But when such mapping exists, AutoMapper searches for it with `IEnumerable<TypePair> GetRelatedTypePairs(TypePair root)`, finds a mapping from Ancestor to Foo, and tries to create new instance of Foo.

It would be nice to have a configuration switch to disable searching for related mappings. If you have some other solution to my problem, I will greatly appreciate it.

**Comment by svines** [comment]
I can attest this used to work as I just pulled a breaking change and had to rollback to 3.3.0 where it worked.

**Comment by lbargaoanu** [comment]
Did you try with Mapper.Initialize?

**Comment by olegtarasov** [comment]
@lbargaoanu yes, I just tried that with same result.

**Comment by lbargaoanu** [comment]
@olegtarasov As a workaround, did you try ConstructUsing?

**Comment by lbargaoanu** [comment]
@jbogard When we find some workaround, I think this can be closed. The explicit mapping should prevent using the AssignableMapper.

**Comment by olegtarasov** [comment]
@lbargaoanu Unfortunately, I can't use ConstructUsing because instances that should be passed into the constructor are resolved through DI container which I can't access at the time of mapping.

However, I used another workaround implementing FooDTO for Baz collection. The DTO is a POCO, so there's no need to resolve dependencies. This solution actually conforms to my whole architecture, so I consider this a permanent solution. However, this type of behavior should be emphasized in AutoMapper's documentation, or fixed if it's a bug.

**Comment by lbargaoanu** [comment]
@olegtarasov The documentation is on github, anyone can contribute :)

**Comment by olegtarasov** [comment]
@lbargaoanu So this is not a bug then? :)  If so, we can close this issue.
