### ISSUE TITLE
context.Parent.DestinationValue sometimes null.

### ISSUE THREAD

**Issue by kfhagedorn** [AutoMapper/AutoMapper#873]
I have upgraded Automapper to Version 4.0.4.0 and I use an ArrayToCollection-Mapper.

I need the parent Instance to set the constraints correctly for my domain entities.

To do this, I have inside my mapper a method they sets the given parent in my aggregate child entities.

With the latest Automapper version 3.x everthing works with this code:

                        SatifyRelations(mappedChild, (EntityBase)context.Parent.DestinationValue);

With version 4.0.4.0 I have some entities where the context.Parent.DestinationValue is null.

Currently I use the following workaround because only I can find the parent instance in the InstanceCache.

                        EntityBase parentInstance = null;

                        if (context.Parent.DestinationValue != null)
                            parentInstance = (EntityBase)context.Parent.DestinationValue;
                        else
                            parentInstance = (EntityBase)context.Parent.InstanceCache.FirstOrDefault().Value;

I have no idea why it currently now has stopped working for some entity aggregates.
Does anyone have the same problem and may already a solution?

**Comment by lbargaoanu** [comment]
Can you provide a simple failing test?

**Comment by kfhagedorn** [comment]
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Automapper_4._0._4._0_Issue
{
    [TestClass]
    public class Test
    {

        [TestMethod]
        public void TestMapper()
        {
            //Automapper init
            AutoMapper.Mapper.Initialize((cfg) =>
            {
                TranslationTextMapperConfiguration translationTextMapperConfiguration = new TranslationTextMapperConfiguration();
                translationTextMapperConfiguration.Configure();
            });
            AutoMapper.Mapper.AssertConfigurationIsValid();

            TranslationTextDto transientTranslationTextDto = new TranslationTextDto();
            transientTranslationTextDto.KeyText = "TEST";
            transientTranslationTextDto.Origin = "Unittest";
            transientTranslationTextDto.Translations = new TranslationTextTranslationDto[] 
            { 
                new TranslationTextTranslationDto() { Iso6391LanguageCode = "EN", TranslationText = "Test" },
                new TranslationTextTranslationDto() { Iso6391LanguageCode = "DE", TranslationText = "Test" }
            };

            var transientTranslationTextEntity = AutoMapper.Mapper.Map<TranslationTextDto, TranslationText>(transientTranslationTextDto);

            Assert.IsFalse(transientTranslationTextEntity.Translations.Any(t => t.Text == null));

        }

        public abstract class DtoBase { }

        public abstract class EntityBase { }

        public interface IAggregateChild
        {
            void SetAggregateParent(EntityBase parent);
        }

        public class TranslationTextDto : DtoBase
        {
            public TranslationTextDto()
            {
                Translations = new TranslationTextTranslationDto[] { };
            }

            public string KeyText { get; set; }
            public string Origin { get; set; }
            public TranslationTextTranslationDto[] Translations { get; set; }
        }

        public class TranslationTextTranslationDto : DtoBase
        {
            public string Iso6391LanguageCode { get; set; }
            public string TranslationText { get; set; }
        }

        public class TranslationText : EntityBase
        {
            public TranslationText()
                : base()
            {
                Translations = new HashSet<TranslationTextTranslation>();
            }

            public virtual string KeyText { get; set; }
            public virtual string Origin { get; set; }
            public virtual ICollection<TranslationTextTranslation> Translations { get; protected set; }
        }

        public class TranslationTextTranslation : EntityBase, IAggregateChild
        {
            public virtual TranslationText Text { get; set; }
            public virtual string Iso6391LanguageCode { get; set; }
            public virtual string TranslationText { get; set; }

            #region Implementation of the IAggregateChild-Interface
            public virtual void SetAggregateParent(EntityBase parent)
            {
                Text = (TranslationText)parent;
            }
            #endregion
        }

        public class TitleDto : DtoBase
        {
            public TitleDto()
            {
                Translations = new TitleTranslationDto[] { };
            }
            public long DataDomainAffiliationId { get; set; }
            public long DataDomainBranchAffiliationId { get; set; }
            public string Text { get; set; }
            public string ShortText { get; set; }
            //public Gender Gender { get; set; }
            public bool IsPerson { get; set; }
            public TitleTranslationDto[] Translations { get; set; }
        }

        public class TitleTranslationDto : DtoBase
        {
            public long LanguageId { get; set; }
            public string Text { get; set; }
            public string ShortText { get; set; }
        }

        public class Title : EntityBase
        {
            public Title()
                : base()
            {
                Translations = new HashSet<TitleTranslation>();
            }
            public virtual string Text { get; set; }
            public virtual string ShortText { get; set; }
            //public virtual Gender Gender { get; set; }
            public virtual bool IsPerson { get; set; }
            public virtual ICollection<TitleTranslation> Translations { get; protected set; }

        }

        public class TitleTranslation : GeneralTranslation, IAggregateChild
        {
            /// <summary>
            /// Gets or sets the title.
            /// </summary>
            public virtual Title Title { get; set; }

            #region Implementation of the IAggregateChild-Interface
            /// <summary>
            /// Private helper method to set all constraints. 
            /// </summary>
            public virtual void SetAggregateParent(EntityBase parent)
            {
                Title = (Title)parent;
            }

            public virtual IList<EntityBase> GetAggregateParents()
            {
                return new List<EntityBase>() { Title };
            }
            #endregion
        }

        public abstract class GeneralTranslation : EntityBase
        {
            /// <summary>
            /// Default c'tor.
            /// </summary>
            public GeneralTranslation()
            {
            }


            /// <summary>
            /// Gets or sets the text in a specific language.
            /// </summary>
            public virtual string Text { get; set; }

            /// <summary>
            /// Gets or sets the text in a specific language.
            /// </summary>
            public virtual string ShortText { get; set; }

        }

        public class TranslationTextMapperConfiguration
        {
            public void Configure()
            {
                ToBoTranslationTextConfiguration();
            }

            private static void ToBoTranslationTextConfiguration()
            {
                AutoMapper.Mapper.CreateMap<TranslationTextDto, TranslationText>()
                    .ForMember(dst => dst.Translations, opt =>
                    {
                        opt.UseDestinationValue();
                    });

                AutoMapper.Mapper.CreateMap<TranslationTextDto[], ICollection<TranslationText>>()
                    .ConvertUsing<ArrayToCollection<TranslationTextDto, TranslationText>>();

                AutoMapper.Mapper.CreateMap<TranslationTextTranslationDto, TranslationTextTranslation>()
                .ForMember(dst => dst.Text, opt => opt.Ignore());

                AutoMapper.Mapper.CreateMap<TranslationTextTranslationDto[], ICollection<TranslationTextTranslation>>()
                    .ConvertUsing<ArrayToCollection<TranslationTextTranslationDto, TranslationTextTranslation>>();
            }
        }

        public class TitleMapperConfiguration
        {
            public void Configure()
            {
                ToEntityTitleConfiguration();
            }

            private static void ToEntityTitleConfiguration()
            {
                AutoMapper.Mapper.CreateMap<TitleDto, Title>()
                    .ForMember(dst => dst.Translations, opt => opt.UseDestinationValue());

                AutoMapper.Mapper.CreateMap<TitleTranslationDto, TitleTranslation>()
                .ForMember(dst => dst.Title, opt => opt.Ignore());

                AutoMapper.Mapper.CreateMap<TitleDto[], ICollection<Title>>()
                    .ConvertUsing<ArrayToCollection<TitleDto, Title>>();

                AutoMapper.Mapper.CreateMap<TitleTranslationDto[], ICollection<TitleTranslation>>()
                    .ConvertUsing<ArrayToCollection<TitleTranslationDto, TitleTranslation>>();
            }
        }

        public class ArrayToCollection<TDto, TEntity> : ITypeConverter<TDto[], ICollection<TEntity>>
            where TDto : DtoBase
            where TEntity : EntityBase
        {
            public ICollection<TEntity> Convert(ResolutionContext context)
            {
                var destination = (ICollection<TEntity>)context.DestinationValue;
                var source = (TDto[])context.SourceValue;

                if (source == null)
                    source = new TDto[] { };

                // Add or Update to destination
                foreach (var child in source)
                {
                    var mappedChild = AutoMapper.Mapper.Map<TDto, TEntity>(child);
                    var targetChild = destination.SingleOrDefault(c => c.Equals(mappedChild)); //overwrite Equals or replace comparison with an Id comparison
                    if (targetChild == null)
                    {
                        EntityBase parentInstance = null;

                        //if (context.Parent.DestinationValue != null)
                        parentInstance = (EntityBase)context.Parent.DestinationValue;
                        //else
                        //parentInstance = (EntityBase)context.Parent.InstanceCache.FirstOrDefault().Value;

                        SatifyRelations(mappedChild, parentInstance);

                        destination.Add(mappedChild);
                    }
                    else
                        AutoMapper.Mapper.Map(child, targetChild);
                }
                return destination;
            }

            private void SatifyRelations(EntityBase aggregateChild, EntityBase aggregateParent)
            {
                IAggregateChild aggregateChildEntity = aggregateChild as IAggregateChild;
                if (aggregateChildEntity != null)
                    aggregateChildEntity.SetAggregateParent(aggregateParent);
            }
        }
    }
}

**Comment by lbargaoanu** [comment]
One way to look at it is that ResolutionContext.DestinationValue holds the destination value passed to Map, you don't pass any, so it's null (see #557 for details). On the other hand, apparently there is a need for the AutoMapper created destination value, so perhaps we should expose it somehow. @jbogard should decide.

**Comment by kfhagedorn** [comment]
Thank you for your fast answere. 

Okay, when I initialize the new instance manualy it works,
but in my opinion is it (was it) a great feature, that Automapper automatically 
creates a new instance for the target value. Sure, Automapper still creates the instance 
automatically, but I can not really understand why this self-instanciated object-instance 
is now never reachable in the DestinationValue.  
Whether I manually generating the instance, or if I leave out the destination parameter and  AutoMapper create it, makes no difference to me, why the parent value should not be filled.

To change my code in the array to collection mapper is not the problem. It is only one position, but 
to change in all my business object the Mapper.Map-Calls from 
        var transientEntity = AutoMapper.Mapper.Map<Dto, Entity>(transientDto);
to
        var transientEntity = AutoMapper.Mapper.Map<Dto, Entity>(transientDto, new Entity());
is not so nice :)

**Comment by lbargaoanu** [comment]
I think it's a matter of time before someone asks for the created destination again.

**Comment by jbogard** [comment]
Probably so. I've just changed that logic so much around mapping individual properties, I'm getting whiplash

**Comment by kfhagedorn** [comment]
Now, I refactored my project so, that I inject the new destination instance by my self. 
It work also in my ArrayToCollection-converter for mapping child objects (collection), but now I run into the same problem like lbargaoanu wrote. When I have a child element and a property of the child is also a object-type to map, is my only chance to use a ConstructUsing(...) method.

Jimmy, please give use a possiblity to get the destination value. 

Setting of the DestinationType or the hole ResolutionContext is unfortunately impossible in the ConstructUsingMethode.

I think, it would be nice to have a possiblity, to give into the MapperConfiguration a "DestinationObjectCreationFactory" for building the missing destination objects, and solve the bug of the unsetted DestinationValue while using the ConstructUsing(...) method.
