### ISSUE TITLE
Can't map DataTable to DTO?

### ISSUE THREAD

**Issue by syph424** [AutoMapper/AutoMapper#874]
I'm sure I'm missing something really silly here, but I've got a DataTable (the results of executing a legacy stored proc) and I'd like to AutoMap it to my DTO.  The field names are identical, I've confirmed that the proc is returning data and it's present in the DataTable, but:

```c# 
equity = AutoMapper.Mapper.DynamicMap<IDataReader, List<CurrentEquity>>(table.CreateDataReader());
```

returns null.  Can someone see what I'm missing here?

Thanks!

**Comment by syph424** [comment]
I recreated my problem this morning in a simple console app:

```c#
using System;
using System.Collections.Generic;
using System.Data;
using AutoMapper;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {      
            var dt = new DataTable();
            dt.Columns.Add("FirstName", typeof(string));
            dt.Columns.Add("LastName", typeof(string));
            dt.Columns.Add("Age", typeof(int));

            var dr = dt.NewRow();
            dr["FirstName"] = "Person";
            dr["LastName"] = "One";
            dr["Age"] = 23;
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr["FirstName"] = "Person";
            dr["LastName"] = "Two";
            dr["Age"] = 43;
            dt.Rows.Add(dr);
            
            Mapper.CreateMap<IDataReader, List<Person>>();            
            List<Person> People = Mapper.Map<IDataReader, List<Person>>(dt.CreateDataReader());

            for (int i = 0; i < People.Count; i++)
            {
                Console.WriteLine(People[i].FirstName + " " + People[i].LastName + " : " + People[i].Age.ToString());
            }

            Console.ReadLine();
        }
    }

    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
    }
}
```

If I use DynamicMap, I get the same behavior I'm seeing in my application.  If I use the above CreateMap / Map, I get the following exception when Map is called:

```
Missing type map configuration or unsupported mapping.

Mapping types:
DataTableReader -> Int32
System.Data.DataTableReader -> System.Int32

Destination path:
List`1

Source value:
System.Data.DataTableReader
```

Any ideas?

**Comment by syph424** [comment]
Based on the discussion over in https://github.com/AutoMapper/AutoMapper/issues/855, I tried adding:

```
Mapper.CreateMap<DataTableReader, Int32>();
```

to my console app - this makes the exception stop happening, but still no luck mapping the datatable to the DTO.

**Comment by jumas45** [comment]
syph424 - I dont think you are alone. I am having the same issue when I upgraded Automapper from 3.3.1 to the latest version. It appears that the structure has changed and I no longer see a Mapper class for DataReader. I do see on in Version 3.3.1 of the source code.

Let's hope that Jimmy gets a chance to look at it and perhaps the syntax has changed or maybe we need to add some additional configuration options.

**Comment by jbogard** [comment]
On NuGet:
https://github.com/automapper/automapper.data
https://www.nuget.org/packages/automapper.data
