### ISSUE TITLE
Automapper Error

### ISSUE THREAD

**Issue by kuttiram** [AutoMapper/AutoMapper#876]
I got this type of error from automapper can pls guide regarding this.

```
"Message": "An error has occurred.",
  "ExceptionMessage": "Missing type map configuration or unsupported mapping.

Mapping types:
OfficeCommunication -> OfficeCommunication
dashAPI.Models.Brokerage.OfficeCommunication -> RFG.Brokerage.Entities.OfficeCommunication

Destination path:
Office.CommunicationRestrictions.CommunicationRestrictions

Source value:
dashAPI.Models.Brokerage.OfficeCommunication",
  "ExceptionType": "AutoMapper.AutoMapperMappingException",
```

**Comment by jbogard** [comment]
Well, it looks like it's right there in the message. You need to create a map between those two types, `Mapper.CreateMap<dashAPI.Models.Brokerage.OfficeCommunication, RFG.Brokerage.Entities.OfficeCommunication>();`

**Comment by kuttiram** [comment]
I done this but same error occur now also can u pls help me

**Comment by jbogard** [comment]
Well there's not a lot of information here to go on. At the very least I'd need code for:
- Your source/destination types
- Code showing your configuration
- Code showing you executing the mapping

**Comment by kuttiram** [comment]
I done this but same error occur now also can u pls help me

**Comment by kuttiram** [comment]
how to map entity to IEnumerable entity

**Comment by kuttiram** [comment]
Mapper.CreateMap<testAPI.Models.Global.OfficeBasicInfo, IEnumerable<Test.Entities.OfficeBasicInfo>>();

**Comment by jbogard** [comment]
The same error? What's the error? Also you're trying to map a single DTO to a list of entities, that doesn't make sense.
