### ISSUE TITLE
AutoMapper.AutoMapperConfigurationException: property cannot be mapped when the properties have been mapped.

### ISSUE THREAD

**Issue by bebemau** [AutoMapper/AutoMapper#878]
Hi we are getting this error only in production and unable to reproduce in dev/qa environment :
```
09/08/2015 12:18:19
Type : AutoMapper.AutoMapperConfigurationException, AutoMapper, Version=2.2.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005
Message : The following property on Common.Account cannot be mapped: 
            Account
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type Common.Account.
Context:
            Mapping to property Account from Service.Account to Common.Account
            Mapping from type Service.AccountProfile to Common.AccountProfile
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
```
We have triple checked the mappings there are not really much to it and I have pasted below.  The Account property only has two fields in it both.  

Mappings:
```
Mapper.CreateMap (squareBracket)Proxy.AccountProfile, CommonDef.AccountProfile(squareBracket)();
Mapper.CreateMap(squareBracket)Proxy.Account, CommonDef.Account(squareBracket)();
Mapper.AssertConfigurationIsValid();
```
Both Services.Account and Common.Account looks like this:
```
public partial class Account
    {
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
    }
```
I also have unit test on mapping Service.AccountProfile  to Common.AccountProfile checking all properties and the unit test succeeded.  

Any pointers why this error and how to fix?  Thanks.

**Comment by jbogard** [comment]
AutoMapper 2.2.1 is oooooold, can you try the latest?

**Comment by bebemau** [comment]
Hi I realized that but it is a little late since the code is being released.   For now can you tell me if this error makes any sense?  Is it a known issue in 2.2.1 that it will randomly throw error when everything is setup correctly?  Any guidance how this can be fixed before updating the version?  Also about updating which version number is a stable version to upgrade to?  Thank you very much.

**Comment by lbargaoanu** [comment]
Are all your calls to CreateMap made during initialization and then only calls to Mapper.Map? Because otherwise you might have a threading issue.

**Comment by bebemau** [comment]
Calls to CreateMap are in the constructor of each class and will only be
called once since these are static classes.

**Comment by lbargaoanu** [comment]
@bebemau Then upgrade you must :)

**Comment by bebemau** [comment]
I understand and we will upgrade.  For now I need an explanation and dont
really have one.


@Lucian, based on the code I posted, do you see any issue?  Again I think
what needs to be done to map is pretty straight forward but maybe I have
missed something and that's why that error.  We didnt get just one error,
we got multiples of the same error.

**Comment by lbargaoanu** [comment]
@bebemau The code you posted doesn't help :) But I don't think it matters. If in a simple test, everything works, then I guess the bug is more subtle than that. You can try to make a gist with a simple, executable test, but I doubt it would make a difference. Because I would run it and see that everything is OK.

**Comment by bebemau** [comment]
Thanks Lucian for your responses.

Again we only get these errors in an environment that mirrors production,
no errors in dev/qa.

I understand we should upgrade but before I make that suggestion I really
would like to be able to give a better explanation than "we believe there
is a bug in this version and thus we need to upgrade" not knowing whether
the upgrade will actually fix the issue, also need to consider the qa
effort since this code is being used all over the places.

The decision of releasing this code to production is now pending and what I
really want to find out is if this is a known issue where an exception
throws without actually an underlying issue, and by upgrading this will be
fixed.  Everything seems to work fine, we are just seeing these in our
error log.

I understand I might not get all my questions answered, so any feedback is
much appreciated!!

**Comment by jbogard** [comment]
AutoMapper 2.2.1 had threading issues, so users saw things like the error you have.

**Comment by bebemau** [comment]
Thanks Jimmy for the confirmation.  Now it all makes sense!!

**Comment by bebemau** [comment]
Hi Jimmy, we have updated to the latest version and released to production since we did not see any error after updating the version.  After release, there were no error initially but since saturday lots of automapper errors have been reported.  Below is one of the error reported:

"Trying to map fieldName1 to fieldName1.", data="System.Collections.ListDictionaryInternal", fullname="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling_ Version=5.0.505.0_ Culture=neutral_ PublicKeyToken=31bf3856ad364e35", hresult="-2146233088", os_type="WinNT", page_id="/main/saml.axd", request_id="f79c76e0-afdd-491e-b33a-c4ad9a2cf133", session_id="d5rbglr3y1gi1x4ta31sduat", source="AutoMapper", stack_trace="at AutoMapper.ConfigurationStore.DryRunTypeMap(ICollection`1 typeMapsChecked_ ResolutionContext context)at AutoMapper.ConfigurationStore.DryRunTypeMap(ICollection`1 typeMapsChecked_ ResolutionContext context)at AutoMapper.ConfigurationStore.AssertConfigurationIsValid(IEnumerable`1 typeMaps)", targetsite="Void DryRunTypeMap(System.Collections.Generic.ICollection`1[AutoMapper.TypeMap]_ AutoMapper.ResolutionContext)", tealeaf_id="", threadidentity="investor", type="AutoMapper.AutoMapperConfigurationException_ AutoMapper_ Version=4.0.4.0_ Culture=neutral_ PublicKeyToken=be96cd2c38ef1005OfxEnrollmentAdd a custom mapping expression_ ignore_ add a custom resolver_ or modify the destination type Common.fieldName1."

This is really urgent since our customers are impacted.  The code has been tested in QA and we didnt see any error only after releasing to production.  I also checked the mapping for fieldName1 and all of its property has been mapped properly between the source and destination type.  

Could you kindly look at the error and any suggestion what is the issue and how to fix?

**Comment by jbogard** [comment]
Why are you doing AssertConfigurationIsValid in production?

**Comment by bebemau** [comment]
:)

I somehow got the impression AssertConfigurationIsValid needs to be called after all the CreateMap's, and since all the CreateMap code is in production, I also have AssertConfigurationIsValid in production.  

So.... are you implying AssertConfigurationIsValid is supposed to only be called in tests?

**Comment by jbogard** [comment]
Yes - AssertConfigurationIsValid will throw an exception if there's a mismatch - nothing you can fix in production, it should only be in a unit test.
