### ISSUE TITLE
Getter-only properties silently ignored

### ISSUE THREAD

**Issue by paranoidandroid522** [AutoMapper/AutoMapper#886]
It seems like properties in the target type that have no setter are silently ignored. AutoMapper should throw an exception in AssertConfigurationValid() in that case. Or is this intended behavior for some reason?

**Comment by jbogard** [comment]
It assumes that you've designed your destination types intentionally like that. The consensus from the AutoMapper community was that it shouldn't throw exceptions in this case. The behavior used to be like you described, but that bothered people who designed their DTOs like this intentionally.

I thought about adding a configuration value for this behavior, but it would be odd.

**Comment by paranoidandroid522** [comment]
I see. Well, the way I see it, that's a classic gotcha - suprising, somewhat inconsistent behavior that may lead to nasty bugs that are hard to track down. But that's a matter of opinion, I suppose.

By the way, have you thought about adding (optional) support for setting getter-only properties via their backing fields using reflection, analogous to NHibernate's support for accessing properties using their backing fields? This would be an extremely useful feature.

**Comment by jbogard** [comment]
I'm open to suggestions - are you supposed to add Ignore() to method that some folks think should be ignored in the first place? You can NEVER write to that property, why should I tell AutoMapper to ignore something that it could never map anyway? AutoMapper supports private setters, so a true readonly property is really just up to you at that point.

The fields thing - yes, I've never needed it so it'll need someone adding support via PR.

**Comment by paranoidandroid522** [comment]
Well, as I said, a matter of opinion. I respect yours - sorry if that came out wrong. For the standard use case of DTOs you are probably right, the problem came up in a project where I use AutoMapper in more creative ways.

As for configuring that behavior, may I make a suggestion: How about making an overload of AssertConfigurationValid() that that allows to pass the desired non-default behavior as parameter (wrapped in an options struct for extensibility?)

As for the PR hint - yes, I get that, I was in fact thinking about doing it myself - I was just mainly asking  because  I would like to know if there is even a chance for it to get accepted. The same applies for my AssertConfigurationValid() suggestion, of course.

**Comment by TylerCarlson1** [comment]
Maybe once conventions gets added you can make you own configuration handle this.  But definitely not the default
