### ISSUE TITLE
Issues after updating to Automapper 4

### ISSUE THREAD

**Issue by Nearga** [AutoMapper/AutoMapper#888]
Hi, i had updated from 3.3.1 to 4.0.4 ( targetFramework="portable-win81+wpa81") and faced some issues.

1. `System.AggregateException` was added to the lib, so it conflicted with the same exception from System.Threading.Threads. Solved it by adding `extern alias`. Not critical, but still.

2. Pretty critical. When running application, i've got `System.TypeInitializationException`. Output says
Exception thrown: 'System.ArgumentOutOfRangeException' in AutoMapper.ni.DLL
Exception thrown: 'System.TypeInitializationException' in App.Core.ni.DLL

It appears right before Mapper.AssertConfigurationIsValid();, which is called from OnLaunched().

**Comment by jbogard** [comment]
That first one is fixed in 4.1 (now in pre-release on NuGet, releasing in the next week or so).

That second issue, is it possible to get a list of steps to reproduce? I test on a variety of devices and platforms but it's always possible I missed something.

**Comment by Nearga** [comment]
That's a part of a pretty large project, but in a nutshell, usage is like: i have a static AutoMapperConfig, in ctor i'm setting all maps and profiles, and calling AssertConfigurationIsValid() from OnLaunched().

If to remove this assertion, i'm getting a common "map is not set in automapper" exception when it comes to real mapping.

**Comment by jbogard** [comment]
More looking at creating a dummy project on my side from scratch.

**Comment by Nearga** [comment]
I'll try to make it till the end of this week.
