### ISSUE TITLE
Mapping Queryable Expressions fails when using variable

### ISSUE THREAD

**Issue by simoco** [AutoMapper/AutoMapper#889]
Please, advice on how to fix this issue. This one works:

    Expression<Func<IQueryable<Dto>, IQueryable<Dto>>> expr = dtos => dtos.Where(dto => dto.A == "Test" && dto.Type == 1);
    var mappedExpr = Mapper.Map<Expression<Func<IQueryable<Model>, IQueryable<Model>>>>(expr);

while this one doesn't:

    Expression<Func<Dto,bool>> exprInVariable = dto => dto.A == "Test" && dto.Type == 1;
    Expression<Func<IQueryable<Dto>, IQueryable<Dto>>> expr = dtos => dtos.Where(exprInVariable);
    var mappedExpr = Mapper.Map<Expression<Func<IQueryable<Model>, IQueryable<Model>>>>(expr);

The only change is that I store expression in variable. It fails with exception:

>AutoMapper.AutoMapperMappingException: 
>Mapping types:
>Expression`1 -> Expression`1
>
>System.Linq.Expressions.Expression`1[[System.Func`2[[System.Linq.IQueryable`1[[Tests.Fake.Dto, Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Linq.IQueryable`1[[Tests.Fake.Dto, Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[System.Linq.IQueryable`1[[Tests.Fake.Model, Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Linq.IQueryable`1[[Tests.Fake.Model, Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
>
>Destination path:
>
>Expression`1
>Source value:
>dtos => >dtos.Where(value(Tests.Infrastructure.Mappers.ExpressionAutoMapperTests+<>c__DisplayClass21).exprInVariable) ---> System.ArgumentException: Expression of type 'System.Linq.Expressions.Expression`1[System.Func`2[Tests.Fake.Dto,System.Boolean]]' cannot be used for parameter of type 'System.Linq.Expressions.Expression`1[System.Func`2[Tests.Fake.Model,System.Boolean]]' of method 'System.Linq.IQueryable`1[Tests.Fake.Model] Where[Model](System.Linq.IQueryable`1[Tests.Fake.Model], System.Linq.Expressions.Expression`1[System.Func`2[Tests.Fake.Model,System.Boolean]])'
    at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ref ReadOnlyCollection`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Mappers.ExpressionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
 --- End of inner exception stack trace ---

My mappings are registered as follows:

    Mapper.CreateMap<Model, Dto>()
                .ForMember(dst => dst.A, opt => opt.MapFrom(src => src.Name))
                .ForMember(dst => dst.B, opt => opt.MapFrom(src => src.Foo.Name));

    Mapper.CreateMap<Dto, Model>()
                .ForMember(dst => dst.Name, opt => opt.MapFrom(src => src.A))
                .ForMember(dst => dst.Foo, opt => opt.MapFrom(src => new SubModel {Id = src.Id, Name = src.B}));

My model and dto classes are looks like:

    public class Model 
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public SubModel Foo { get; set; }
    }
    
    public class SubModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; } 
    }

    public class Dto 
    {
        public Guid Id { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public int Type { get; set; }
    }

So, how can I use Queryable Expression mapping with expression in variable?

**Comment by TylerCarlson1** [comment]
Are you suppose to go from DTO to DTO or is it DTO to Model?
Same thing with Model to Model.

**Comment by simoco** [comment]
Hi @TylerCarlson1 , I'm trying to create expression that transforms `IQueryable<Dto>` to  `IQueryable<Dto>` and after that map it to the expression that transforms `IQueryable<Model>` to  `IQueryable<Model>`. The thing is very similar to [the example described on your wiki page](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)). I know in this very simplified example I can directly map `Expression<Func<Dto,bool>>` to `Expression<Func<Model,bool>>` and use it, but in my real code I need to map `Expression<Func<IQueryable<Dto>, IQueryable<Dto>>>` to `Expression<Func<IQueryable<Model>, IQueryable<Model>>>`. So, do you have any ideas why it's not working when storing expression `Expression<Func<Dto,bool>>` in variable?

**Comment by TylerCarlson1** [comment]
I have to look at it in code.  This scenario was never accounted for Queryable translation.
UseAsDataSource() does translate `Expression<Func<IQueryable<Dto>, IQueryable<Dto>>>` to `Expression<Func<IQueryable<Model>, IQueryable<Model>>>` and should with passing in `Expression<Func<Dto,bool>>`

Can you give an example of your use case and why UseAsDataSource() is not an option?

**Comment by jbogard** [comment]
Closing until we get further updates.
