### ISSUE TITLE
Determining subclass to instanciate based from a property value using ConstructUsing/ConvertUsing not working after upgrading to v4

### ISSUE THREAD

**Issue by Dunge** [AutoMapper/AutoMapper#890]
Hello,

I'm not sure if this is the proper way to do it, honestly I just managed to get it working after trials and errors in the past, but it was working fine in AutoMapper3 and now won't work using AutoMapper4. If you have a proper solution of achieving the same result, you are welcome.

I have a single class type loaded from the database, and a application model abstract class of the same name, along with multiple derived classes. Depending on the value of a property on the database model, instantiate one type or another. I also want to be able to map back and forth with their own mapping rules.

Here's the code I was using (simplified to only two derived classes):

    Mapper.CreateMap<CommunicationSetting, Model.CommunicationSettings.CommunicationSetting>()
                .Include<CommunicationSetting, DialupCommunicationSetting>()
                .Include<CommunicationSetting, InputCommunicationSetting>()
                .ConstructUsing(CommunicationSettingsConstructor)
                .ConvertUsing(CommunicationSettingsMapper);

    Mapper.CreateMap<Model.CommunicationSettings.CommunicationSetting, CommunicationSetting>()
                .Include<DialupCommunicationSetting, CommunicationSetting>()
                .Include<InputCommunicationSetting, CommunicationSetting>()
                .IgnoreAllNonExisting();

    Mapper.CreateMap<CommunicationSetting, DialupCommunicationSetting>()
                .IgnoreAllNonExisting()
                .ReverseMap()
                .IgnoreAllNonExistingSource();

    Mapper.CreateMap<CommunicationSetting, InputCommunicationSetting>()
                .ForMember(dest => dest.InputType, opt => opt.MapFrom(t => (CommunicationInputType)t.SocketType))
                .IgnoreAllNonExisting()
                .ReverseMap()
                .ForMember(dest => dest.SocketType, opt => opt.MapFrom(t => (int)t.InputType))
                .IgnoreAllNonExistingSource();

        private static readonly Func<CommunicationSetting, Model.CommunicationSettings.CommunicationSetting> CommunicationSettingsConstructor =
            x =>
            {
                switch (x.Type)
                {
                    case CommunicationType.Dialup:
                        return new DialupCommunicationSetting();
                    case CommunicationType.Input:
                        return new InputCommunicationSetting();
                }
                return null;
            };

        readonly static Func<CommunicationSetting, Model.CommunicationSettings.CommunicationSetting> CommunicationSettingsMapper =
            x =>
            {
                switch (x.Type)
                {
                    case CommunicationType.Dialup:
                        return Mapper.Map<DialupCommunicationSetting>(x);
                    case CommunicationType.Input:
                        return Mapper.Map<InputCommunicationSetting>(x);
                }
                return null;
            };

So with AutoMapper3, it would check the "Type" property and instantiate the proper mapped type and use the proper mapping rules. With AutoMapper4, it always instantiate in the last type defined in the createmap rules.

**Comment by lbargaoanu** [comment]
Please try to isolate the problem to a simple failing test.

**Comment by lbargaoanu** [comment]
Probably the same as #924 and #910.

**Comment by jbogard** [comment]
Yep looks like you need to use Mapper.Initialize instead for the inheritance pieces here.
