### ISSUE TITLE
Unable to cast object of type 'ObjectShortEditView' to type 'ObjectEditView '.

### ISSUE THREAD

**Issue by vovikdrg** [AutoMapper/AutoMapper#895]
I have two classes Base short class

     public class ObjectShortEditView
     {
            public string FirstName { get; set; }
            public string LastName { get; set; }
     }

full view 

 

    public class ObjectEditView : ObjectShortEditView
     {
            public string Phone { get; set; }
    }

in automapper profile

    Mapper.CreateMap<Entity, ObjectShortEditView>().IgnoreAllNonExisting();
    Mapper.CreateMap<Entity, ObjectEditView >().IgnoreAllNonExisting();

IgnoreAllNonExistingExtension

    public static IMappingExpression<TSource, TDestination> IgnoreAllNonExisting<TSource, TDestination>
                (this IMappingExpression<TSource, TDestination> expression)
            {
                var flags = BindingFlags.Public | BindingFlags.Instance;
                var sourceType = typeof(TSource);
                var destinationProperties = typeof(TDestination).GetProperties(flags);
    
                foreach (var property in destinationProperties)
                {
                    if (sourceType.GetProperty(property.Name, flags) == null)
                    {
                        expression.ForMember(property.Name, opt => opt.Ignore());
                    }
                }
                return expression;
            }

Problem is when i try to map from entity to full edit view it fails

    var view = Mapper.Map<ObjectEditView>(entityFromDb);

And some times it fails with exception

    Unable to cast object of type 'ObjectShortEditView' to type 'ObjectEditView '.

Mean while i wrote this i got idea that it could be ignore all extension but why it even try to cast to short view when i ask map me to full view...

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/842#issuecomment-139104798).

**Comment by lbargaoanu** [comment]
@vovikdrg Can you please close your issue?
