### ISSUE TITLE
Use Automapper 4.0 on portable library with profile 92

### ISSUE THREAD

**Issue by tmm360** [AutoMapper/AutoMapper#896]
I've tried to use Automapper with a portable library using .net framework 4.0, and I got this error:
"Could not install package 'AutoMapper 4.0.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile92', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"
Because it is compatible with .net framework 4.0, I think that it could be compatible with this type of library.

**Comment by jbogard** [comment]
What is profile92? I haven't quite got them all memorized yet.

**Comment by tmm360** [comment]
Profile92 .NET Portable Subset (.NET Framework 4, Windows 8, Windows Phone 8.1)

**Comment by jbogard** [comment]
Soooooo I'm not planning on supporting .NET 4 any more, since MS is not supporting it any more either. There's just too many differences between 4 and 4.5+ to justify the effort to maintain that line.
