### ISSUE TITLE
Call IMappingExpression method to all created mappings

### ISSUE THREAD

**Issue by brenovieira** [AutoMapper/AutoMapper#897]
I'd like to call ```IgnoreAllPropertiesWithAnInaccessibleSetter()``` and/or ```IgnoreAllSourcePropertiesWithAnInaccessibleSetter()``` and a custom method to ignore properties in all my mappings.

I couldn't find a way to do this. Is it possible?
The main reason I call these is because some of my classes have read-only properties, like:
```
public string SomeProperty
{
	get
	{
		return string.Format("{0} - {1}", Id, Type);
	}
}
```
Even if both Source and Destination have the same read-only property, ```Mapper.AssertConfigurationIsValid();``` throw an Exception.

Could AutoMapper have something like ```IConfiguration.GetMaps()``` to let me iterate through maps I created ? or some method to apply directly to all created maps.

Since each mapping has different ```TSource``` and ```TDestination``` in ```IMappingExpression<TSource, TDestination>```, I don't know the type ```IConfiguration.GetMaps()``` could return, but I didn't put to much thought in it.

What do you think ?

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/blob/1e759c0e57c94bf9ec2d2224e557bd9a6c940d41/src/UnitTests/Bug/InternalProperties.cs).

**Comment by brenovieira** [comment]
@lbargaoanu, I think I get it.

For instance, applying ```IgnoreAllPropertiesWithAnInaccessibleSetter()``` to all mappings is the same of calling ```cfg.ShouldMapProperty = p => p.CanWrite == true;``` isn't it ? (since read-only properties have CanWrite == false).

My custom method is to ignore properties decorated with ```[NotMapped]```, so I could check this too in that lambda expression...

I think that solves my problem.
Thanks

**Comment by lbargaoanu** [comment]
:+1:
