### ISSUE TITLE
Missing SourceMember in PropertyMap

### ISSUE THREAD

**Issue by antidemon** [AutoMapper/AutoMapper#898]
I have a bool? mapped to a string property via two resolvers.
 Despite the apparently identical (but mirrored) CreateMap calls, when I retrieve the property maps the SourceMember property is only populated going in one direction.

I was relying upon these being populated for some generic code.

The following code will run as a LinqPad program and demonstrate the issue (you'll need to add refs to Automapper):

	void Main()
	{
		Mapper.CreateMap<Bar, Foo>()
			.ForMember(dest => dest.FooProperty, op => op.ResolveUsing<StringToNullableBoolResolver>().FromMember(source => source.BarProperty));
	
		Mapper.CreateMap<Foo, Bar>()
			.ForMember(dest => dest.BarProperty, op => op.ResolveUsing<NullableBoolToStringResolver>().FromMember(source => source.FooProperty));

		TypeMap map = Mapper.FindTypeMapFor<Foo, Bar>();
		map.GetPropertyMaps().ToList()[0].SourceMember.Dump();

		TypeMap map2 = Mapper.FindTypeMapFor<Bar, Foo>();
		map2.GetPropertyMaps().ToList()[0].SourceMember.Dump();
	}

	public class Foo
	{
		public bool? FooProperty { get; set; }
	}

	public class Bar
	{
		public string BarProperty { get; set; }
	}

	public class StringToNullableBoolResolver : ValueResolver<string, bool?>
	{
		protected override bool? ResolveCore(string source)
		{
			switch (source)
			{
				case "Y":
					return true;
				case "N":
					return false;
				default:
					return null;
			}
		}
	}

	public class NullableBoolToStringResolver : ValueResolver<bool?, string>
	{
		protected override string ResolveCore(bool? source)
		{
			switch (source)
			{
				case true:
					return "Y";
				case false:
					return "N";
				default:
					return null;
			}
		}
	}

**Comment by lbargaoanu** [comment]
As long as Mapper.Map does its job, I don't think you have a case :)

**Comment by antidemon** [comment]
My case is that Automapper is not just the Map method, it is an API which also offers the FindTypeMapFor method to return a TypeMap object, which in turn has a SourceMember property.
As a consumer of that contract I should expect to find the SourceMember property populated correctly.
The fact that this happens *sometimes* indicates that this is the intention.
The fact that this doesn't happen for seemingly identical code indicates a bug in the SourceMember population code.

If I were accessing private members using reflection then I wouldn't have a case.

**Comment by jbogard** [comment]
I'm confused - what's the output here? I missed what the actual problem is.

**Comment by lbargaoanu** [comment]
The problem is that PropertyMember.SourceMember sometimes is null, although the mapping works.

**Comment by antidemon** [comment]
The first SourceMember output should show FooProperty but is actually null.
The second SourceMember output correctly shows BarProperty.

**Comment by jbogard** [comment]
Can't reproduce :(

**Comment by lbargaoanu** [comment]
This reproduces all right :) I don't know if it's worth fixing, but that's something else.

**Comment by antidemon** [comment]
Repros ok for me using LinqPad referencing Automapper version 4.0.4. Trying to update to latest now.

**Comment by antidemon** [comment]
This repros no problem using latest Automapper.

Just create a new Console app, add a NuGet ref to Automapper and paste this in:
	using System;
	using System.Linq;
	using AutoMapper;

	namespace ConsoleApplication5
	{
		class Program
		{
			static void Main(string[] args)
			{
				Mapper.CreateMap<Bar, Foo>()
					.ForMember(dest => dest.FooProperty, op => op.ResolveUsing<StringToNullableBoolResolver>().FromMember(source => source.BarProperty));

				Mapper.CreateMap<Foo, Bar>()
					.ForMember(dest => dest.BarProperty, op => op.ResolveUsing<NullableBoolToStringResolver>().FromMember(source => source.FooProperty));

				TypeMap map = Mapper.FindTypeMapFor<Foo, Bar>();
				Console.Write("Foo --> Bar: ");
				Console.WriteLine(map.GetPropertyMaps().ToList()[0].SourceMember);

				TypeMap map2 = Mapper.FindTypeMapFor<Bar, Foo>();
				Console.Write("Bar --> Foo: ");
				Console.WriteLine(map2.GetPropertyMaps().ToList()[0].SourceMember);

				Console.ReadLine();
			}
		}

		public class Foo
		{
			public bool? FooProperty { get; set; }
		}

		public class Bar
		{
			public string BarProperty { get; set; }
		}

		public class StringToNullableBoolResolver : ValueResolver<string, bool?>
		{
			protected override bool? ResolveCore(string source)
			{
				switch (source)
				{
					case "Y":
						return true;
					case "N":
						return false;
					default:
						return null;
				}
			}
		}

		public class NullableBoolToStringResolver : ValueResolver<bool?, string>
		{
			protected override string ResolveCore(bool? source)
			{
				switch (source)
				{
					case true:
						return "Y";
					case false:
						return "N";
					default:
						return null;
				}
			}
		}
	}
