### ISSUE TITLE
How to skip null values for all classes

### ISSUE THREAD

**Issue by stenlytw** [AutoMapper/AutoMapper#899]
In Automapper we can configure to skip null value from source object like this:
```asp
Mapper.CreateMap<SourceType, DestinationType>()
  .ForAllMembers(opt => opt.Condition(srs => !srs.IsSourceValueNull));
```

I want to know can we configure the condition for all classes automatically? Thanks.

**Comment by lbargaoanu** [comment]
You can try with [ForAllMaps](https://github.com/AutoMapper/AutoMapper/blob/1e759c0e57c94bf9ec2d2224e557bd9a6c940d41/src/UnitTests/Bug/ForAllMaps.cs).

**Comment by stenlytw** [comment]
Hi, how to use it? Thanks.

**Comment by jbogard** [comment]
You can also use the new conventions.
