### ISSUE TITLE
AutoMapper unexpectedly mapping Name property to COMPANY_Name property

### ISSUE THREAD

**Issue by GauravKGoyal** [AutoMapper/AutoMapper#900]
Hi,
Mapping PersonViewModel to Person populates Person.COMPANY_Name property with the value of PersonViewModel.Name which i would NOT expect. 
Note if i change uppercase COMPANY to pascal case then mapping does not happen.

    public class PersonViewModel
    {
        public string Name { get; set; }
    }

    public class Person
    {
        public string Name { get; set; }
        public string COMPANY_Name { get; set; }

        public override string ToString()
        {
            return string.Format("Name:{0}, COMPANY_Name:{1}", Name, COMPANY_Name);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            AutoMapper.Mapper.CreateMap<PersonViewModel, Person>();
            var person = AutoMapper.Mapper.Map<Person>(new PersonViewModel() {Name = "Bob"});
            Console.WriteLine(person.ToString());
            Console.ReadKey();
        }
    }

Output -> Name:Bob, COMPANY_Name:Bob
Expected Output -> Name:Bob, COMPANY_Name:

Any thoughts would be appreciated. 
Thanks

**Comment by TylerCarlson1** [comment]
The regular expression for pascal is `(\p{Lu}+(?=$|\p{Lu}[\p{Ll}0-9])|\p{Lu}?[\p{Ll}0-9]+)` which breaks up strings pascal format.  Result with `COMPANY_Name` returns `Name`, so matches Name and gets mapping.

**Comment by GauravKGoyal** [comment]
Thanks for the info Tyler. Will do a workaround until there is a new update

**Comment by jbogard** [comment]
@GauravKGoyal so the existing regex matcher isn't perfect. You'd need to replace it with something that matches more specific for you. Here's the current one that allows for C# member naming possibilities and culture-sensitive casing:

`(\p{Lu}+(?=$|\p{Lu}[\p{Ll}0-9])|\p{Lu}?[\p{Ll}0-9]+)`

**Comment by lbargaoanu** [comment]
You can use no naming convention. Or the default one, Pascal. Or any other. But if you don't respect the convention, weird things will happen. Seems fair to me :) I don't think changing the default one for corner cases is the way to go.

**Comment by GauravKGoyal** [comment]
Thanks guys. 
I have resolved it by choosing to ignore the mapping for those properties as they are not many. And i do understand that we can not cater for all the cases.

**Comment by jbogard** [comment]
I'll close it, thanks!
