### ISSUE TITLE
ViewModel to LLBL Entity Mapping Errors

### ISSUE THREAD

**Issue by mhagesfeld** [AutoMapper/AutoMapper#904]
I am mapping from a ViewModel to LLBL Entity, and it is causing errors.  It worked in v3.3.1.  However, after the upgrade to 4.0.3.  I am not mapping the ID (identity int PK) and a CreatedDate (auto-generated current date, non-null) field. I got the following error when I did not have the ID:
Missing type map configuration or unsupported mapping.

Mapping types:
ContactViewModel -> Int32

Then when I added the ContactId but not the date field, I got the following:

Missing type map configuration or unsupported mapping.

Mapping types:
ContactViewModel -> IValidator
Arborwearv2.Web.Models.View.ContactViewModel -> SD.LLBLGen.Pro.ORMSupportClasses.IValidator

Destination path:
ContactEntity

Source value:
Arborwearv2.Web.Models.View.ContactViewModel

**Comment by lbargaoanu** [comment]
A failing test would help.

**Comment by snekbaev** [comment]
Same issue with 4.0.4 after upgrade from 3.x

**Comment by snekbaev** [comment]
I made VS'13 solution which demonstrates the problem, please let me know when I can remove the file
http://particlefusion.org/autoMapper_mapping_issue.zip

Thank you!

**Comment by lbargaoanu** [comment]
The link is dead (for me at least). But anyway, we don't need the whole solution. A gist with a failing test and no external dependencies (except AutoMapper) would do.

**Comment by snekbaev** [comment]
Strange, works for me. Re-uploaded to expire box and tested: http://expirebox.com/download/dac066f5ab1dbcc3e0f2c6fc92f69059.html

LLBLGen entities require external dlls and, imho, solution is the easiest way to start with.
Thank you!

**Comment by lbargaoanu** [comment]
It worked for me on develop. You can try with the MyGet build.

**Comment by snekbaev** [comment]
It does work with 4.1.0-ci1007. So I guess I will just wait for the 4.1 release then. Thank you!

**Comment by lbargaoanu** [comment]
@mhagesfeld  Can you close your issue?

**Comment by mhagesfeld** [comment]
OK - but when is the 4.1 schedule release?

**Comment by lbargaoanu** [comment]
I guess @jbogard makes a new release when he's good and ready :) But issues we already have a fix for are not useful.

**Comment by jbogard** [comment]
As soon as I fix the build server. It's having a problem with Xamarin licensing ATM.

**Comment by snekbaev** [comment]
Thank you :)

**Comment by mhagesfeld** [comment]
@lbargaoanu Understood, wasn't holding out on closing it, just hadn't been able to verify, and was traveling.
