### ISSUE TITLE
warning CS3001: Argument type 'AutoMapper.IConfiguration' is not CLS-compliant

### ISSUE THREAD

**Issue by eddiepaz** [AutoMapper/AutoMapper#905]
I'm creating an interface that takes IConfiguration as a parameter of a method in an MVC 5 application, and I'm getting this error with AutoMapper v4.0.4.0.

**Comment by jbogard** [comment]
Does CLS compliant matter?

**Comment by jbogard** [comment]
CLS compliant now. Hooray?

**Comment by ArieGato** [comment]
Hi,

I downloaded the latest nuget package of AutoMapper (4.2.0) to fix the ClsCompliant warning. The warning still persists, so used Reflector to analyse the assembly. The ClsCompliant attribute is not present in the dll from the nuget package. When I look in the source files the attribute is present. Am I missing something (besides the ClsCompliant attribute)?

Cheers,
Arie

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/AssemblyInfo.cs#L3 I don't know what else to do than this. Perhaps a PR?

**Comment by ArieGato** [comment]
Your code is 100% correct and when I compile the source code of 4.2.0 the ClsCompliant warning is gone. It would appear that the ClsCompliant attribute has not been included in the build. I don't know whether that's possible...

**Comment by jbogard** [comment]
Run the build locally and see what happens (not through Visual Studio).

**Comment by ArieGato** [comment]
I used psake to build the 4.2 version and the dll in the bin/debug/net45 folder does not hold the ClsCompliant attribute. I also tried building 5.0 version and that dll does contain the ClsCompliant attribute.

![automapper 4 2](https://cloud.githubusercontent.com/assets/1059562/13257920/2a748c1c-da51-11e5-9752-47124cc92613.jpg)
![automapper 5 0](https://cloud.githubusercontent.com/assets/1059562/13257919/2a735eb4-da51-11e5-945c-ba591683d05a.jpg)

**Comment by jbogard** [comment]
Ha, then I have no idea. Looks like it's fixed in 5.0 then.
