### ISSUE TITLE
Polymorphic issue with 4.x 

### ISSUE THREAD

**Issue by Serenyrddraig** [AutoMapper/AutoMapper#906]
May be related to #762. Sorry for the complexity, but this is drawn slightly modified from our production system. This problem showed up after conversion from 3.3.1 to 4.0.4. The test was compiled with VS2013 Ultimate.

Consider

using System;
using System.Linq;
using System.Runtime.Serialization;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using AutoMapper;
using Restrictions.From;
using Restrictions.To;
namespace Restrictions.To
{
    [DataContract(IsReference = true)]
    public abstract class LineItemRestriction : IExtensibleDataObject
    {
        [DataMember]
        public virtual bool IsSatisfied { get; set; }
        [DataMember]
        public Int32 RestrictionRuleId { get; set; }
        [DataMember]
        public string MessageText { get; set; }
       public ExtensionDataObject ExtensionData { get; set; }
    }

    [DataContract(IsReference = true)]
    public abstract class DecimalRestriction : LineItemRestriction
    {
        [DataMember]
        public decimal Value { get; set; }
    }

    [DataContract(IsReference = true)]
    public abstract class DecimalAccumulatorRestriction : DecimalRestriction
    {
       [DataMember]
        public decimal AccumulatedAmount { get; set; }
    }

    [DataContract(IsReference = true)]
    public class UnitQuantityRestriction : DecimalRestriction
    {
        [DataMember]
        public decimal? Units { get; set; }
        [DataMember]
        public BasketUnitQuantityRestriction BasketRestriction { get; set; }
    }

    [DataContract(IsReference = true)]
    public class BasketUnitQuantityRestriction : DecimalAccumulatorRestriction
    {
    }

}

namespace Restrictions.From
{
    [DataContract(IsReference = true)]
    public abstract class ItemRestriction : IExtensibleDataObject
    {
        [DataMember]
        public Int32 SequenceId { get; set; }
        [DataMember]
        public Int32 RestrictionRuleId { get; set; }
        [DataMember]
        public string MessageText { get; set; }

        public ExtensionDataObject ExtensionData { get; set; }
    }

    [DataContract(IsReference = true)]
    public abstract class DecimalRestriction : ItemRestriction
    {
        [DataMember]
        public decimal Value { get; set; }
    }

    [DataContract(IsReference = true)]
    public class UnitQuantityRestriction : DecimalRestriction
    {
        [DataMember]
        public decimal? Units { get; set; }
    }

}

namespace Restrictions
{
    [TestClass]
    public class UnitTest1
    {
        public void CreateMaps()
        {
            Mapper.CreateMap<ItemRestriction, LineItemRestriction>()
                .ForMember(d => d.MessageText, o => o.MapFrom(s => s.MessageText))
                .ForMember(d => d.RestrictionRuleId, o => o.MapFrom(s => s.RestrictionRuleId))
                .ForMember(d => d.IsSatisfied, o => o.UseValue(false))
                .Include<From.DecimalRestriction, To.DecimalRestriction>()
                ;
            Mapper.CreateMap<From.DecimalRestriction, To.DecimalRestriction>()
                .ForMember(d => d.Value, o => o.MapFrom(s => s.Value))
                .Include<From.UnitQuantityRestriction, To.DecimalRestriction>()
                ;

            Mapper.CreateMap<From.UnitQuantityRestriction, To.UnitQuantityRestriction>()
                .ForMember(d => d.BasketRestriction, o => o.Ignore())
                .ForMember(d => d.Units, o => o.MapFrom(s => s.Units))
                ;
        }

        [TestMethod]
        public void TestArray()
        {
            //Mapper.Initialize(cfg => CreateMaps());
            CreateMaps();
            var array = new From.UnitQuantityRestriction[] {new From.UnitQuantityRestriction()};
            var array1 = Mapper.Map<To.UnitQuantityRestriction[]>(array);
            Assert.IsNotNull(array1);
            Assert.IsTrue(array1.Count()==1);
            Assert.IsTrue(array1[0] is To.UnitQuantityRestriction);

            var itemarray = new From.ItemRestriction[] { new From.UnitQuantityRestriction() };

            var array2 = Mapper.Map<To.LineItemRestriction[]>(itemarray);
            Assert.IsNotNull(array2);
            Assert.IsTrue(array2.Count() == 1);
            Assert.IsTrue(array2[0] is To.UnitQuantityRestriction);

        }
    }
}

If this is linked with 3.3.1 it works as expected.

Uncomment the first line of the test, comment the second line, and rebuild with 4.0.4. The attempt to create the itemarray results in an exception.
Test method Restrictions.UnitTest1.TestArray threw exception: 

AutoMapper.AutoMapperMappingException: 

Mapping types:

ItemRestriction -> LineItemRestriction

Restrictions.From.ItemRestriction -> Restrictions.To.LineItemRestriction

Destination path:

LineItemRestriction[][0]

Source value:

Restrictions.From.UnitQuantityRestriction ---> System.InvalidOperationException: Instances of abstract classes cannot be created.
    at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at AutoMapper.Internal.DelegateFactory.<>c__DisplayClass7_0.<CreateCtor>b__0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.Internal.DictionaryFactoryOverride.ConcurrentDictionaryImpl`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.Internal.DelegateFactory.CreateCtor(Type type)
   at AutoMapper.Mappers.ObjectCreator.CreateObject(Type type)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.CreateObject(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.NewObjectPropertyMapMappingStrategy.GetMappedObject(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
 --- End of inner exception stack trace ---
    at Restrictions.UnitTest1.TestArray() in UnitTest1.cs: line 120

**Comment by lbargaoanu** [comment]
Did you try this with the [myget](https://www.myget.org/F/automapperdev/api/v2) version?

**Comment by Serenyrddraig** [comment]
Same result with 4.1 prototype

**Comment by TylerCarlson1** [comment]
After you create all maps can you try Mapper.Seal().  With 4.1 prototype of course.

Also you Create Map code isn't showing up with <> cause it's not recognized as a code snippet.  Hard to tell what map was included

**Comment by TylerCarlson1** [comment]
Another alternative is instead of 
`var array2 = Mapper.Map<To.LineItemRestriction[]>(itemarray);` 
is 
`var array2 = itemarray.Select(Mapper.Map<To.LineItemRestriction>).ToArray();`
If Seal() doesn't work.

**Comment by Serenyrddraig** [comment]
Mapper.Initialize() does an implicit Seal(). 

Behavior also changes when the abstract Destinations become concrete (remove all the abstracts in the To namespace). In this case, a DecimalRestriction (the Parent) is materialized in the array, not the UnitQuantity.

**Comment by lbargaoanu** [comment]
@Serenyrddraig Please make a gist with your test so it can be executed. Github messed up the code in your message.

**Comment by Serenyrddraig** [comment]
https://gist.github.com/Serenyrddraig/499aca29c00ada5eda56

Only difference here is I tried calling Seal() explicitly in the CreateMaps() function. Still no change in behavior, i.e. 3.3.1 works, 4.x throws exception

**Comment by lbargaoanu** [comment]
Change the destination type for the include with the concrete type and the test passes:

            Mapper.CreateMap<From.DecimalRestriction, To.DecimalRestriction>()
                .Include<From.UnitQuantityRestriction, To.UnitQuantityRestriction>()
                ;
Also, the MapFrom calls are redundant.

**Comment by Serenyrddraig** [comment]
Agreed (with embarrassment). Sorry. However, this gives we something for which to look in the production code that is causing the error.

**Comment by lbargaoanu** [comment]
No problem. More often than not, trying to isolate the error helps finding a solution.

**Comment by Serenyrddraig** [comment]
I'll pursue this into the production code. The error you found is my own from trying to simplify the production maps to isolate the problem; the production code is correct (in this instance). However, the production code is still faulting in the same manner so I've got some digging to do.

**Comment by Serenyrddraig** [comment]
My typo in the unit test must have been a subliminal catch of  the error in the production code. The error was that the Include<>s for the subclasses were in the grandparent rather than the parent of the subclasses, leaving the abstract parent with no concrete realizations.
