### ISSUE TITLE
Cannot build due to dependency problems.

### ISSUE THREAD

**Issue by martinlong1978** [AutoMapper/AutoMapper#907]
I cannot build from the current devel source, due to unresolved dependencies. 

Building from psake.cmd ultimately results in: 

C:\Source\AutoMapper\src\AutoMapper\project.json(0,0): error NU1001: The dependency Microsoft.NETCore.Platforms >= 1.0.0 could not be resolved.

See attached log (very large). It also has a lot of errors building for WindowsPhone, but I don't really care about that platform. 

I'm certain this is something to do with my environment (VS2015), but there are no build instructions. Could you add a build readme, or wiki documentation please?

Also, when do MyGet builds happen? The current one is quite old and doesn't include the most recent bug fixes. 

(Github wouldn't let me attach the logfile, so find it here on Dropbox: https://www.dropbox.com/s/u1n4ufe4ra8cnr6/ConEmu-2015-09-28-p9300.txt?dl=0 )

**Comment by jbogard** [comment]
Welp, it looks like that same build problem you have has been happening on the build server. I'll take a look.

**Comment by jbogard** [comment]
OK I figured this one out. You have to force beta 6:

```
dnvm use 1.0.0-beta6
dnvm alias default 1.0.0-beta6
```
