### ISSUE TITLE
DTOs with ctors issue when mapping ef models

### ISSUE THREAD

**Issue by mrahhal** [AutoMapper/AutoMapper#909]
Consider the following:

```c#
public class SemesterDto
{
    public SemesterDto()
    {
    }

    public SemesterDto(int key, string name)
    {
        Key = key;
        Name = name;
    }
    ...
}
```

Configuration:
```c#
Mapper.CreateMap<Semester, SemesterDto>().MaxDepth(1);
```

Using EntityFramework:

```c#
context.Semesters
    .ProjectTo<SemesterDto>()
    .FirstOrDefault();
```

This gives the following exception: `NotSupportedException: Only parameterless constructors and initializers are supported in LINQ to Entities.`

If I remove the second ctor on `SemesterDto` everything works. It seems AutoMapper is trying to use this ctor for some reason. The same thing causes another issue when I use `SemesterDto` as a nested object inside another dto.

So, is this a bug or is there something I misunderstood?

**Comment by mrahhal** [comment]
OK, so I've discovered that AutoMapper prefers ctors with parameters. I can get direct mapping to work by:

```c#
Mapper.CreateMap<Semester, SemesterDto>().MaxDepth(1)
      .ConstructProjectionUsing(sem => new SemesterDto());
```

But this also fails when the SemesterDto is nested in another dto but with the following exception: `System.InvalidOperationException: When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.`

For anyone interested: [so question](http://stackoverflow.com/questions/32873591/automapper-strange-iqueryable-projection-exception).

So where is the second exception coming from this time?

**Comment by lbargaoanu** [comment]
The constructor bug was fixed. Try the latest from NuGet (or MyGet if it still fails). If you still have issues, make a gist with a failing test.

**Comment by mrahhal** [comment]
I'm actually using the latest package: `4.0.4`.

**Comment by jbogard** [comment]
Ugh I need to get 4.1 released

**Comment by mrahhal** [comment]
Does that mean this is a confirmed bug?

**Comment by jbogard** [comment]
Yes.

**Comment by jbogard** [comment]
But for now you can get around this with ConstructProjectionUsing().

**Comment by mrahhal** [comment]
Ok, so we're talking about the first exception here. What about the second exception after using `ConstructProjectionUsing`? It works with direct mapping but the exception (`When called from 'VisitLambda'`...) occurs when I try to map to a dto with another nested dto. Any thoughts on that?

**Comment by jbogard** [comment]
Not sure, can you post your full type hierarchy?

**Comment by mrahhal** [comment]
Sure, just a moment.

**Comment by mrahhal** [comment]
I tested and repro'd with the following:
```c#
    public class Sem
	{
		[Key]
		public int Key { get; set; }
		public string Name { get; set; }

		public virtual ICollection<Art> Arts { get; set; }
	}

	public class Art
	{
		[Key]
		public int Key { get; set; }
		public string AName { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.ForeignKey("Sem")]
		public int? SemKey { get; set; }
		public virtual Sem Sem { get; set; }
	}

	public class SemDto
	{
		public int Key { get; set; }
		public string Name { get; set; }
	}

	public class ArtDto
	{
		public int Key { get; set; }
		public string AName { get; set; }

		public SemDto Sem { get; set; }
	}
```

Config:
```c#
Mapper.CreateMap<Sem, SemDto>().MaxDepth(1)
    .ConstructProjectionUsing(s => new SemDto());
Mapper.CreateMap<Art, ArtDto>().MaxDepth(1)
    .ConstructProjectionUsing(s => new ArtDto());
```

And the query:
```c#
// This works (direct mapping).
var s = context.Sems.ProjectTo<SemDto>().FirstOrDefault();

// This doesn't.
var a = context.Arts.ProjectTo<ArtDto>().FirstOrDefault();
````

The second query fails with the following: 
![capture](https://cloud.githubusercontent.com/assets/4404199/10220455/52087572-6850-11e5-828a-e4cea21693d1.PNG)

**Comment by lbargaoanu** [comment]
As a workaround, rename the property to other than its type name, Sem.

**Comment by mrahhal** [comment]
@lbargaoanu renamed it to `SemProp` in `Art` (with the foreign key attribute) and `ArtDto`, same result.

**Comment by lbargaoanu** [comment]
Yes, my bad :)

**Comment by mrahhal** [comment]
Don't worry about it. To be honest, I just want the second exception fixed by next release since it's fairly obvious it's a bug. At this point I won't try any more workarounds (if one does exist), I spent a lot of time on this already. I'll just avoid ctors in my DTOs until then!
