### ISSUE TITLE
Resolver is not inherited in some cases

### ISSUE THREAD

**Issue by mueblo** [AutoMapper/AutoMapper#911]
When doing 2 level of mapping inheritance, the custom resolver is not properly inherited in some cases.
Consider the following class diagram:

![automapper_bug](https://cloud.githubusercontent.com/assets/12763281/10242680/db4f6488-68f2-11e5-9a6e-dce89bd860db.png)
Note that the *SourceLevel2* declares a *DProperty0* property.
On each level, each *SProperty* is mapped on each *DProperty*.
Each mapping include the previous level one.

On the level 2 mapping, the *SProperty0* is not correctly mapped to the *DProperty0*. Instead, the convention property map is used and the *DProperty0* from the *SourceLevel2* is copied into the *DProperty0* of the *DestinationLevel2*.

Note: there is no problem with only one level of inheritance.

Here is a unit test to highlight the problem:
```csharp
    [TestFixture]
    public class InheritanceResolverTest
    {
        public class SourceLevel0
        {
            public string SPropertyLevel0 { get; set; }
        }

        public class SourceLevel1 : SourceLevel0
        {
            public string SPropertyLevel1 { get; set; }
        }

        public class SourceLevel2 : SourceLevel1
        {
            public string DPropertyLevel0 { get; set; }
            public string SPropertyLevel2 { get; set; }
        }

        public class DestinationLevel0
        {
            public string DPropertyLevel0 { get; set; }
        }

        public class DestinationLevel1 : DestinationLevel0
        {
            public string DPropertyLevel1 { get; set; }
        }

        public class DestinationLevel2 : DestinationLevel1
        {
            public string DPropertyLevel2 { get; set; }
        }

        [Test]
        public void Should_inherit_resolver_test()
        {
            Mapper.CreateMap<SourceLevel0, DestinationLevel0>()
                .ForMember(dest => dest.DPropertyLevel0, o => o.ResolveUsing(src => src.SPropertyLevel0));

            Mapper.CreateMap<SourceLevel1, DestinationLevel1>()
                .IncludeBase<SourceLevel0, DestinationLevel0>()
                .ForMember(dest => dest.DPropertyLevel1, o => o.ResolveUsing(src => src.SPropertyLevel1));

            Mapper.CreateMap<SourceLevel2, DestinationLevel2>()
                .IncludeBase<SourceLevel1, DestinationLevel1>()
                .ForMember(dest => dest.DPropertyLevel2, o => o.ResolveUsing(src => src.SPropertyLevel2));

            var source = new SourceLevel2
                         {
                             SPropertyLevel0 = "SPropertyLevel0",
                             SPropertyLevel1 = "SPropertyLevel1",
                             SPropertyLevel2 = "SPropertyLevel2",
                             DPropertyLevel0 = "DPropertyLevel0",
                         };
            var destination = Mapper.Map<DestinationLevel2>(source);

            Assert.AreEqual(source.SPropertyLevel0, destination.DPropertyLevel0);
        }
    }
```

The problem seems to lie in [TypeMap.ApplyInheritedTypeMap](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/TypeMap.cs#L372) or in the [PropertyMap constructor](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/PropertyMap.cs#L32).
On the first level of inheritance, the custom resolver in the parent property map is put in the *_sourceValueResolvers* (cf [PropertyMap constructor](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/PropertyMap.cs#L32)).
On the second level of inheritance, the convention property map exists but the inherited property map is not considered to have a custom value resolver (*HasCustomValueResolver* is false), so the convention property map is unchanged (cf [TypeMap.ApplyInheritedTypeMap](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/TypeMap.cs#L372)).

**Comment by lbargaoanu** [comment]
[By design.](https://github.com/AutoMapper/AutoMapper/issues/719#issuecomment-111556362) Why it almost works, I don't know.

**Comment by mueblo** [comment]
The problem remains if you replace *ResolveUsing* by *MapFrom*, which is supposed to be inherited if I understood correctly the documentation.

**Comment by lbargaoanu** [comment]
Apparently you're missing an Include in your initial test

            Mapper.CreateMap<SourceLevel2, DestinationLevel2>()
                .IncludeBase<SourceLevel0, DestinationLevel0>()
                .IncludeBase<SourceLevel1, DestinationLevel1>()
                .ForMember(dest => dest.DPropertyLevel2, o => o.ResolveUsing(src => src.SPropertyLevel2));
I would guess this is by design, but @jbogard should know.

**Comment by mueblo** [comment]
If I remove *DPropertyLevel0* on the *SourceLevel2*, everything works fine (so the custom resolver is correctly inherited from level 0 mapping to the level 2 mapping).
This indicates that the mapping inheritance seems to be transitive, the second include should not be necessary.

**Comment by jbogard** [comment]
Yep, for now you need the second include.
