### ISSUE TITLE
Cannot update to 4.0.4 on a Xamarin project (android)

### ISSUE THREAD

**Issue by nbelley** [AutoMapper/AutoMapper#915]
I'm using Visual Studio 2015, with latest Xamarin and mono releases, targeting android API 18 and I get this error trying to update to 4.0.4:

    Attempting to gather dependencies information for multiple packages with respect to project 'XService.Droid', targeting 'MonoAndroid,Version=v4.3'
    Attempting to resolve dependencies for multiple packages
    Resolving actions install multiple packages
    Removed package 'AutoMapper 3.3.1' from 'packages.config'
    Executing script file '...packages\AutoMapper.3.3.1\tools\MonoAndroid\uninstall.ps1'
    Successfully uninstalled 'AutoMapper 3.3.1' from XService.Droid
    Package 'AutoMapper.4.0.4' already exists in folder '...packages'
    Install failed. Rolling back...
    Package 'AutoMapper 4.0.4' does not exist in project 'XService.Droid'
    Package 'AutoMapper 3.3.1' already exists in folder '...packages'
    Added package 'AutoMapper 3.3.1' to 'packages.config'
    Executing script file '...AutoMapper.3.3.1\tools\MonoAndroid\Install.ps1'
    Update-Package : Failed to add reference to 'System.Collections'. Please make sure that it is in the Global Assembly Cache.
    At line:1 char:1
    + Update-Package AutoMapper -Project XService.Droid
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

**Comment by jbogard** [comment]
What does your project structure look like? I've tried to reproduce this on my local machine to no avail :(

**Comment by nbelley** [comment]
I have a PCL project on which the upgrade worked, and an Android one. What kind of informations can I give you to help you on this?

**Comment by jbogard** [comment]
I guess steps just starting from File->New project in Visual Studio? I have all the Xamarin stuff on my box.

**Comment by nbelley** [comment]
I tried creating a new solution with a new project:

- New project -> Templates -> Visual C# -> Android -> Blank App (Android)

Then I tried to install Automapper 4.0.4, and this project stops on System.Runtime instead of collections:

    Removing package 'AutoMapper 4.0.4' from folder 'c:\Users\Nicolas\documents\visual studio 2015\Projects\App1\packages'
    Removed package 'AutoMapper 4.0.4' from folder 'c:\Users\Nicolas\documents\visual studio 2015\Projects\App1\packages'
    Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.

**Comment by jbogard** [comment]
This is a malformed nuspec, fixed in the 4.1.1 release.
