### ISSUE TITLE
DynamicMap throws exception when using two derrived classes and an existing map between their base classes

### ISSUE THREAD

**Issue by tsebring** [AutoMapper/AutoMapper#917]
See failing unit test below. Is this a bug or?

```c#
using AutoMapper;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    /// <summary>
    /// .NET Framework 4.5
    ///  Using <package id="AutoMapper" version="4.0.4" targetFramework="net45" />
    /// </summary>
    [TestClass]
    public class UnitTest1
    {
        [TestCleanup]
        public void Cleanup()
        {
            Mapper.Reset();
        }

        [TestMethod]
        public void FailingTest()
        {
            Mapper.CreateMap<OneBase, TwoBase>();
            Mapper.DynamicMap<Two>(new One());
        }
        
        class OneBase { }
        class TwoBase { }
        class One : OneBase { }
        class Two : TwoBase { }
    }
}
```

**Comment by jbogard** [comment]
I don't think this is a valid scenario - DynamicMap is only intended for cases where you don't know the type at config time. Things like anonymous types. You're not really supposed to mix the two. If you called CreateMap on One -> Two, this would work.

**Comment by lbargaoanu** [comment]
@jbogard It fails without DynamicMap. Maybe it's missing the map One->Two, but it doesn't say so :)

     Mapper.Map<Two>(new One());

**Comment by tsebring** [comment]
The CreateMap just illustrate the problem. It was never explicitly created in our code rather AutoMapper created it through other calls to DynamicMap.

In our case DynamicMap was used to map two identical objects in different namespaces where the types were not known at compile time.

**Comment by tsebring** [comment]
Example:
```csharp
            Mapper.DynamicMap<TwoBase>(new OneBase());
            Mapper.DynamicMap<Two>(new One());
```

The objects are WCF generated proxys.

**Comment by TylerCarlson1** [comment]
Might want to look at adding a convention in AutoMapper 4.1 as explained in #793.
Maybe something like
```
public class ToWCFProxyProfile : Profile
        {
            protected override void Configure()
            {
                AddConditionalObjectMapper().Where((s, d) => d.Name.StartsWith(s.Name) && s.Namespace == "WCFSource" && d.Namespace == "WCFProxyNameSpace");
            }
        }
```
Shouldn't need AddMemberConfiguration() because identical names, but if so you can make rules for that as well.

**Comment by jbogard** [comment]
@tsebring Have you checked 4.1? The rules around this area were tightened up a bit

**Comment by lbargaoanu** [comment]
This fails on develop. Resolve return the base map, not null, and DynamicMap doesn't create the derived map.

**Comment by jbogard** [comment]
@tsebring @lbargaoanu gotcha. The original scenario passed in my tests I added.
