### ISSUE TITLE
Automapper 4 selects wrong type when using custom type converters

### ISSUE THREAD

**Issue by RobvanGeloven** [AutoMapper/AutoMapper#918]
The following code fails under Automapper 4 but worked in 3:
Basically it tries to use the nullable type converter where it can't (and shouldn't)

```cs
public class TestProfile : Profile
    {
        protected override void Configure()
        {
            base.Configure();

            CreateMap<DateTime, DateTime?>().ConvertUsing(source => source == new DateTime(1900, 1, 1) ? (DateTime?)null : source);

            CreateMap<A, B>();
        }
    }

    public class A
    {
        public DateTime Date { get; set; }
    }

    public class B
    {
        public DateTime Date { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {

            Mapper.AddProfile<TestProfile>();

            var a = new A { Date = DateTime.Now };

            var b = Mapper.Map<B>(a);

            a = new A { Date = new DateTime(1900, 1, 1) };

            b = Mapper.Map<B>(a);
        }
    }
```

**Comment by lbargaoanu** [comment]
The new algorithm to find type maps is a work in progress. A workaround:

    CreateMap<DateTime, DateTime>().ConvertUsing(source => source);

**Comment by RobvanGeloven** [comment]
Thanks for the workaround. We'll stick with version 3 for now. With all due
respect, but this sounds like a beta release and we'd rather not test drive
this in production just yet.
On 8 Oct 2015 1:10 pm, "Lucian Bargaoanu" <notifications@github.com> wrote:

The new algorithm to find type maps is a work in progress. A workaround:

CreateMap<DateTime, DateTime>().ConvertUsing(source => source);

—
Reply to this email directly or view it on GitHub
<https://github.com/AutoMapper/AutoMapper/issues/918#issuecomment-146506486>
.

**Comment by jbogard** [comment]
100s and 100s of tests, but always going to miss something. Nullables are going to be the death of me...

**Comment by RobvanGeloven** [comment]
If I can chip in I'd be more then happy to!

Any small stuff I can start working on?

**Comment by lbargaoanu** [comment]
Well, you can try the MyGet version :) Also feel free to browse the open issues and choose one you think is easy.
