### ISSUE TITLE
Solution messed up?

### ISSUE THREAD

**Issue by texavery77** [AutoMapper/AutoMapper#921]
Hello,
I just tried to load the master solution file AutoMapper.sln in the source root in VS 2012 (Pro) and apparently it is not even able to compile with 257 errors (wanted to debug it as the version 4.0.4 from nuget is not very stable and seems quite buggy to me). Am I missing any additional requirements?

Regards

**Comment by lbargaoanu** [comment]
VS 2015

**Comment by lbargaoanu** [comment]
@texavery77 Can you close your issue?
