### ISSUE TITLE
Derived type is created instead of requested type

### ISSUE THREAD

**Issue by strawd** [AutoMapper/AutoMapper#924]
After upgrading to AutoMapper 4 I noticed a change in behavior. If I have a class "BaseType" and a derived class "DerivedType", and the mapping for DerivedType calls IncludeBase&lt;BaseType&gt;, then a call to Mapper.Map&lt;BaseType&gt;() gives me an instance of the DerivedType class. This breaks some of our application's versioning functionality. Was this change intentional? If so how can I explicitly tell AutoMapper *not* to automatically map to a derived type?

**Comment by lbargaoanu** [comment]
The same as #912 and #910.

**Comment by lbargaoanu** [comment]
You can't. You can try not calling Seal (or Mapper.Initialize) but this might cause other problems.

**Comment by jbogard** [comment]
#910 is fixed now.
