### ISSUE TITLE
AutoMapper error while deploing to WinPhone

### ISSUE THREAD

**Issue by avorobjovs** [AutoMapper/AutoMapper#930]
Hi,

I have Visual Studio 2015 on Windows 10.
I have a Xamarin multiplatform project for Androd, iOS, WinPhone 8.1, and Windows 8.1.
And I have AutoMapper package of the latest 4.0.4 version in my PCL project.

But when I try to debug my project on the WinPhone device on ARM platform I get a deploying error:

> Deploying to Phone Internal Storage...
> Error : DEP6810 : MdilXapCompile.exe failed with error code 2001. See log file
> '...\obj\ARM\Debug\MDIL\MDILXapCompileLog.txt' for more details.

There is the following error in the log file:

> CrossGen failed
> Error processing assembly ...\obj\ARM\Debug\MSIL\AutoMapper.dll
> Raw error code: 2148733978

How can I fix this problem? Can you help me, please?

Best Regards,
Aleksandrs

**Comment by jbogard** [comment]
Not sure, I compile for AnyCPU which should work for you. How might I debug this locally?

**Comment by jbogard** [comment]
I found this? https://social.msdn.microsoft.com/Forums/windowsapps/en-US/d0b940d2-1c4e-4f28-9130-b45067088aa1/wp81-arm-deploying-to-device-problem-dep6810-in-release-mode?forum=wpdevelop

**Comment by avorobjovs** [comment]
Thanx!

I read this article
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/d0b940d2-1c4e-4f28-9130-b45067088aa1/wp81-arm-deploying-to-device-problem-dep6810-in-release-mode?forum=wpdevelop

and also this article
http://stackoverflow.com/questions/29753085/microsoft-band-sdk-deploy-error-to-arm-in-release-raw-error-code-2148733978

And it seems to me that sometimes nuget packages dll can get stuck in the obj directory. When I tried to clean my project I got an error something like a "File access to AutoMapper.dll is denied. This file is used by another process."
It not related to the AutoMapper.

And here are the steps to fix such problem:

1) Clean the solution in Visual Studio
2) Close the solution in Visual Studio
3) Delete all content from \bin and \obj directories of the WinPhone project
4) Open the solution in Visual Studio
5) Recompile it and start debug on the device

It works fine for me.

**Comment by jbogard** [comment]
Ah great! Can we close this one then?

**Comment by avorobjovs** [comment]
Yes, of course you can close it.

**Comment by avorobjovs** [comment]
You can also close https://github.com/AutoMapper/AutoMapper/issues/680 because it is the same.
