### ISSUE TITLE
ProjectUsing causes direct mappings to return an object with default values for its props

### ISSUE THREAD

**Issue by mrahhal** [AutoMapper/AutoMapper#931]
I faced a problem in a project and have successfully repro'd it in a bare test project.

Consider:
```c#
public class AppUser
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class AppUserDto
{
    public int Id { get; set; }
    public string Name { get; set; }
}

// In configure:
Mapper.CreateMap<AppUser, AppUserDto>().MaxDepth(1)
    .ProjectUsing(u => new AppUserDto { Id = u.Id, Name = u.Name });
```

I'm using `ProjectUsing` because of a problem when mapping to a dto that contains multiple dtos of the same type (the problem is caused by automapper not consistently generating the expressions for the same type multiple types in the same query).

Then, when doing direct mappings such as `context.Users.ProjectTo<AppUserDto>().First()`, the returned dto will contain defaults for all its properties as if all automapper did was call the default ctor on `AppUserDto`.
The mapping succeeds if `AppUserDto` is in another dto that is being mapped.

Is this a bug?
[A related so question + more info.](http://stackoverflow.com/questions/33144670/automapper-dto-with-nested-dtos-of-the-same-type-fails)

**Comment by lbargaoanu** [comment]
Try the workaround using the MyGet version. It worked for me on develop.

**Comment by lbargaoanu** [comment]
Now I see it. It works only when projecting Issue. It's a bug.

**Comment by mrahhal** [comment]
Yeah, the simplest direct mapping always fails. So this is not actually fixed in the latest develop package?

**Comment by lbargaoanu** [comment]
No, I got the Project from the SO question. I ran the Project with Issue and it worked :) The Project with AppUser fails.

**Comment by mrahhal** [comment]
Right, then all we have to do is wait for confirmation.
/cc @jbogard 

Is there a workaround for this? This is really frustrating, doing one thing breaks the other.

**Comment by lbargaoanu** [comment]
Apparently it's an off-by-one error :) The initial test works with MaxDepth(2).

**Comment by mrahhal** [comment]
Unfortunately this didn't work for me. For anyone interested, [this is a repo](https://github.com/mrahhal/automapper-repro-931) that reproduces the issue.

**Comment by lbargaoanu** [comment]
Passing [test](https://github.com/lbargaoanu/AutoMapper/blob/d989ee046659dddc57f9b17b55f800b6677f119b/src/IntegrationTests.Net4/RepeatingDto.cs). It should work for you too with the MyGet version.

**Comment by mrahhal** [comment]
**Correction:** this worked in the test project. On my real project I had to make it a `MaxDepth(3)` on one of my models. But then again, on a model that has a list this is still not working for whatever value I put on `MaxDepth`.

**Comment by lbargaoanu** [comment]
I don't see it. Copy the test I linked to. Change it as you need to, execute it and if it fails report back :)

**Comment by mrahhal** [comment]
So basically I have one more model to add to the mix:
```c#
public class Record
{
     public int Id { get; set; }
     public AppUser User { get; set; } // This is it.
}

public class RecordDto
{
     public int Id { get; set; }
     public AppUserDto User { get; set; }
}
```

And the issue has an additional list of records:
```c#
public class IssueDto
{
    public ICollection<RecordDto> Records { get; set; }
}

// Same thing with the model.
````

This is where no matter what I do it always fails (of course except for when I use ProjectUsing, but this causes a whole other problem with direct mapping).

**Comment by lbargaoanu** [comment]
Still no :) See my previous message.

**Comment by jbogard** [comment]
I don't understand why you have MaxDepth at all. Those are for recursive mappings, which I don't see in your examples.

**Comment by mrahhal** [comment]
In my real project I have a recursive mapping on `Issue`:
```c#
public class Issue
{
    ...
    public ICollection<Record> Records { get; set; }
}
```

The first example here didn't need `MaxDepth` that's right.

**Comment by jbogard** [comment]
Can you post your actual full model? It's really confusing to get only part of the picture here. Even your above example doesn't have recursion.

**Comment by mrahhal** [comment]
[Here it is](https://github.com/mrahhal/automapper-repro-931/blob/master/WebApplication1/Models/Stuff.cs) in the repo I created to test this.

**Comment by jbogard** [comment]
There's still no recursion in your repo. MaxDepth is for recursion. What behavior exactly are you trying to achieve here?

**Comment by lbargaoanu** [comment]
@jbogard I don't know about the rest, but the part about ProjectUsing for AppUserDto failing is correct. I'm not sure it's worth trying to fix it though. Doesn't seem useful.

**Comment by mrahhal** [comment]
Hey are there side effects to using `MaxDepth` at all? I took to putting `MaxDepth` on every mapping I create without actually thinking about recursion. I tried removing all `MaxDepth` calls on everything and it seems to be working now.

**Comment by jbogard** [comment]
Yes, MaxDepth is all about recursive models:
```
public class Employee {
    public Employee Manager { get; set; }
}
```
Maybe the docs aren't clear, but using it in other scenarios isn't tested.

**Comment by mrahhal** [comment]
So when you say recursion, you mean recursion on the objects you're projecting to and not on the models you're projecting from. I don't why I got it in reverse. And so if I have no recursion on my dtos (that's how I'm designing them for now) I don't need to put `MaxDepth` at all.

That's one thing out of the way. The problem with `ProjectUsing` remains but as @lbargaoanu said I'm not sure if that's really a bug now that the talk about `MaxDepth` has been cleared out.

Thanks.

**Comment by jbogard** [comment]
I think we can create a separate issue for the ProjectUsing stuff - I've never tried to reuse ProjectUsing on multiple properties and a collection.

**Comment by lbargaoanu** [comment]
That's not the issue. It fails when ProjectUsing is for the queried entity, so not for a property (in this case the binders are not searched). That's why I'm not sure it is very useful. But it shouldn't be difficult to fix.
