### ISSUE TITLE
Error in example: "https://github.com/AutoMapper/AutoMapper/wiki/Nested-mappings"

### ISSUE THREAD

**Issue by sboutzen** [AutoMapper/AutoMapper#932]
First of all, thx for a great tool!

In the above mentioned example, you call CreateMappers twice when determining if the type is generic.
In the first call you mean CreateNestedMappers, and in the second call you mean Mapper.CreateMap.

Keep up the good work =)

**Comment by jbogard** [comment]
The wiki can be edited by anyone, no need to open an issue!
