### ISSUE TITLE
Mapping inside nested collection is not working properly

### ISSUE THREAD

**Issue by TerraVenil** [AutoMapper/AutoMapper#934]
Hi, All.
For example we have such simple classes

    public class SimpleModel
    {
        public int PropertyId { get; set; }

        public ICollection<SimpleModelCollectionItem> SimpleCollection { get; set; }
    }

    public class SimpleModelCollectionItem
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
    }
    
    public class SimpleEntity
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }

        public virtual ICollection<SimpleEntityCollectionItem> SimpleCollection { get; set; }
    }

    public class SimpleEntityCollectionItem
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public int Property2Id { get; set; }
    }

and we have some configuration code

    AutoMapper.Mapper.CreateMap<SimpleModel, SimpleEntity>()
                .ForMember(dest => dest.Id, src => src.Ignore())
                .ForMember(dest => dest.SimpleCollection, src => src.UseDestinationValue());

    AutoMapper.Mapper.CreateMap<SimpleModelCollectionItem, SimpleEntityCollectionItem>()
                .ForMember(dest => dest.Property2Id, src => src.Ignore())
                .EqualityComparision((src, dest) => src.Id == dest.Id);

            AutoMapper.Mapper.AssertConfigurationIsValid();

and test data initialization

                var model = new SimpleModel
                            {
                                PropertyId = 2,
                                SimpleCollection =
                                    new List<SimpleModelCollectionItem>
                                        {
                                            new SimpleModelCollectionItem
                                                {
                                                    Id = 5,
                                                    PropertyId = 7
                                                }
                                        }
                            };
            var entity = new SimpleEntity
                             {
                                 Id = 1,
                                 PropertyId = 3,
                                 SimpleCollection =
                                     new List<SimpleEntityCollectionItem>
                                         {
                                             new SimpleEntityCollectionItem
                                                 {
                                                     Id = 5,
                                                     PropertyId = 4,
                                                     Property2Id = 6
                                                 }
                                         }
                             };
    var entitAfter = AutoMapper.Mapper.Map(model, entity);
and I expect to see

    var entityCollectionItemAfter = entitAfter.SimpleCollection.First();

    var isCollectionItemEquals = object.ReferenceEquals(entityCollectionItemBefore, entityCollectionItemAfter);

    Console.WriteLine(entity.Id); // 1
    Console.WriteLine(entity.PropertyId); // 2
    Console.WriteLine(entity.SimpleCollection.First().Id); // 5
    Console.WriteLine(entity.SimpleCollection.First().PropertyId); // 7
    Console.WriteLine(entity.SimpleCollection.First().Property2Id); // 6 but was 0
    Console.WriteLine(isCollectionItemEquals); // true but was false
Is it possible to set Property2Id for inner collection equals to 6 as it was initially?

**Comment by lbargaoanu** [comment]
The collection mapper doesn't consider the existing values in the destination collection (the collection is cleared first). Whether it should, I'm not sure, cc @jbogard.

**Comment by jbogard** [comment]
This is one of the things @TylerCarlson1 solved in a PR he had open, to consider existing values using equality comparers.

**Comment by TylerCarlson1** [comment]
https://github.com/TylerCarlson1/Automapper.Collection has this functionality.  There's also a NuGet with the same name.
If you want to use this dll you need to have Id's not be ignored, else it's not going to recognize equivalency between the two classes and know they map to each other.  It's designed to insert/update/delete based on if items are equivalent to each other or not, which in your case is Id property.
Can do equality comparison expressions or use the EF model to figure out the primary key and compare only on that.
This will go away whenever the PR gets merged.

**Comment by TerraVenil** [comment]
First of all please accept my apologies I am a little bit modify code example already with using Automapper.Collection. And as you can see is nothing changed in results compared initial code sample. Property Property2Id is setting up by default value 0 but should leave is at is and second point collection item is not equals by reference. May be I am not correct using this extension please correct me.

**Comment by TylerCarlson1** [comment]
Did you add `Mapper.AddProfile<CollectionProfile>();` when you created the maps?  It's required to make Automapper.Collection work.

**Comment by TerraVenil** [comment]
Thank you! Now it works as I want.

**Comment by TylerCarlson1** [comment]
If you are using it with Entity Framework you might want to look at AutoMapper.Collection.EntityFramework.
If you give SimpleModel an Id you can write
`dbContext.SimpleEntity.Persist<SimpleModel>().InsertOrUpdate(model);`
which will figure out by Equivalency Expression and will add Simple Entity or Map to existing item if Id matches.
