### ISSUE TITLE
IObjectMapper.IsMatch use TypeMap instead of ResolutionContext?

### ISSUE THREAD

**Issue by TylerCarlson1** [AutoMapper/AutoMapper#935]
In https://github.com/TylerCarlson1/Automapper.Collection/issues/1 it was made aware to me that I shouldn't be using SourceValue and DestinationValue in IsMatch function, because if the first time I call it the destination is null, it won't call the mapping ever again for that object.  Because it was cached based on type map and not resolution context, you can never use that mapping in the future.

I think GenericMap and my collection map are the only two that don't use just source type and dest type, but by in large I think IsMatch should be passing in TypePair, or some other class that matches the cached type.  This will prevent making people from making mistakes using properties and not knowing that if they change it will never call IsMatch again.

Not a high priority issue given how rare IObjectMappers change

**Comment by jbogard** [comment]
I think you're right here. It caches, so it should be completely obvious to the implementor (and me in the future), that you only should be looking at those two things.

**Comment by jbogard** [comment]
Well I found another one, AssignableArrayMapper. It checks to see if there's a `TypeMap` for the element types.

**Comment by TylerCarlson1** [comment]
So dynamic mapping fails if you do an array of an object to an array of itself?

**Comment by jbogard** [comment]
No clue. But it just needs access to the configuration provider, which could be easily done. You get the TypePair and the ConfigurationProvider. Looking more, even TypeMapMapper accesses the TypeMap in the resolution context.

**Comment by jbogard** [comment]
Now just using TypePair, hooray!
