### ISSUE TITLE
Derived source/destination types in collections not being used properly - 4.0.4

### ISSUE THREAD

**Issue by kordan11** [AutoMapper/AutoMapper#939]
This feature seems to have been broken in the latest version 4.0.4

The example described in the bottom of https://github.com/AutoMapper/AutoMapper/wiki/Lists-and-arrays (Polymorphic element types in collections) does not work currently. All objects in the array are mapped to the parent destination only.

Downgrading to version 3.3.1 fixes the problem.

**Comment by lbargaoanu** [comment]
This has been answered many times. Updated the example.

**Comment by kordan11** [comment]
Thanks for the reply, setting up with initialize does indeed fix the problem.
