### ISSUE TITLE
ReverseMap can open a hole in the AssertConfigurationIsValid source property check

### ISSUE THREAD

**Issue by pkpjpm** [AutoMapper/AutoMapper#940]
When mapping from a more specific class to a more general one, i.e. when there are extra destination properties, there is a scenario where the application of ReverseMap() produces inconsistent validation results. Here's an example:

    public class Foo
    {
        public int Eeney { get; set; }
        public int Meeney { get; set; }
    }

    public class Bar
    {
        public int Eeney { get; set; }
        public int Meeney { get; set; }
        public int Moe { get; set; }
    }

If a bidirectional mapping between this classes is defined with a Bar to Foo map that is reversed:

    Mapper.CreateMap<Foo, Bar>().ReverseMap();

then an error will be thrown by the _AssertConfigurationIsValid_ method as we would expect, since the _Moe_ property is unmapped. However, if we start with a Foo to Bar mapping instead:

    Mapper.CreateMap<Bar, Foo>().ReverseMap();

then there is no error.  It seems that _AssertConfigurationIsValid_ only checks the declared mapping; it doesn't check the mapping that is implied by _ReverseMap_. This seems wrong since one expects _ReverseMap_ to create a symmetrical map.

**Comment by jbogard** [comment]
No, not quite, when you reverse map, it actually checks the *source* members instead of the destination members. It creates a symmetrical map, including the member checks!
