### ISSUE TITLE
Dictionary to Object

### ISSUE THREAD

**Issue by GVX111** [AutoMapper/AutoMapper#942]
Hello,
Please help how to map this? Dict to Object with List Property
<pre>
 public Dictionary<string, object> Parameters => new Dictionary<string, object>()
        {
            {"Username", "{Username}"},
            {"FirstName", "{FirstName}"},
            {"LastName", "{LastName}"},
            {"AccountMeta[MetaKey]", "Pincode"},
            {"AccountMeta[MetaValue]", "150000"},
            {"AccountMeta[MetaKey]", "Amount"},
            {"AccountMeta[MetaValue]", "5000"},

        };
    public class Account
    {
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<AccountMeta> AccountMeta { get; set; }

    }
public class AccountMeta{
        public string MetaKey{ get; set; }
        public string MetaValue{ get; set; }
}
</pre>

**Comment by jbogard** [comment]
The first part of just properties is now available with AutoMapper 4.1 (on MyGet). The second one is weird. You're trying to map something that looks like a dictionary, but it's not really, to List? There's nothing "auto" about trying to do that.

**Comment by gvx111** [comment]
I'm using on ASPNET 5 4.0.0.
If you suggest some other format to Map to this object. I also can change format of second part.

**Comment by jbogard** [comment]
Wait - why do you need AutoMapper if you're using ASP.NET 5? Is this MVC?

**Comment by gvx111** [comment]
because i made Pluginable architecture and I'm using custom submit method where parameters of form are string and it is hard coded declared in Dictionary.
<pre>
 public Dictionary<string, object> Parameters => new Dictionary< string, object >()
        {
            {"Username", "{Username}"},
            {"FirstName", "{FirstName}"},
            {"LastName", "{LastName}"},
            {"AccountMeta[MetaKey]", "Pincode"},
            {"AccountMeta[MetaValue]", "150000"},
            {"AccountMeta[MetaKey]", "Amount"},
            {"AccountMeta[MetaValue]", "5000"},

        };
</pre>

**Comment by jbogard** [comment]
Well I guess I'm curious because MVC's model binder supports OOTB exactly what you're proposing here, have you tried calling it directly?

**Comment by gvx111** [comment]
Can you give me some example of that? thank you for help

**Comment by jbogard** [comment]
Oh I didn't mean to imply I had any idea on how to do that. Wave hands "i'm sure it's easy"

**Comment by lbargaoanu** [comment]
@GVX111 Can you please close your issue?
