### ISSUE TITLE
Interface implemented class mappings generates  proxy types

### ISSUE THREAD

**Issue by fduman** [AutoMapper/AutoMapper#943]
public interface IMyInterface
    {
        int MyProperty { get; set; }
    }

    public class ImplementedClass : IMyInterface
    {
        public int MyProperty
        {
            get;
            set;
        }
    }

    public class MyClass
    {
        public int MyProperty { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap<MyClass, IMyInterface>();
            Mapper.AssertConfigurationIsValid();

            var myClassInstance = new MyClass { MyProperty = 3 };

            var obj = Mapper.Map(myClassInstance, typeof(MyClass), typeof(ImplementedClass));

            Debug.Assert(!obj.GetType().Assembly.IsDynamic);
        }
    }

This generates Automapper's interface proxy class types but I think it should create ImplementedClass 's instance.

**Comment by jbogard** [comment]
This isn't configured properly. In order to achieve this (remember AutoMapper has no idea about `ImplementedClass`) You have two options:

- Create a map `MyClass` -> `ImplementedClass` and include the base using `IncludeBase`
- Configure the `IMyInterface` mapping to construct your `ImplementedClass`, `.ConstructUsing`

**Comment by fduman** [comment]
If AutoMapper has no idea about ImplementedClass how can it resolve the interface type and creates proxy type instance instead of throwing MappingException? 

I thought that Automapper resolves interface type from ImplementedClass and matches MyClass=>IMyInterface mapping.

In my project ImplementedClass is a dynamically generated class type which derives from IMyInterface. I inject my IProxyGenerator to AutoMapper. If I set the Mapper.Map function's destinationType with the interface type everything's fine. ProxyGenerator already resolves the dynamically generated class which implements the interface.

If this is the default behavior of Automapper, it's fine then. I don't know Automapper has a global ConstructUsing function which is injection friendly. It would be nice to have.

Thanks.

**Comment by jbogard** [comment]
Nope, at no point did you ever tell AutoMapper about ImplementedClass. If you did CreateMap with ImplementedClass then yes, but AutoMapper only ever tries to map types that you've told it about.

The interfaces are a feature - you can map to an interface and not ever define an implementation, and AutoMapper will create that implementation for you, just like mocking frameworks do.

**Comment by TylerCarlson1** [comment]
Think @fduman is talking about #927 not working.  Although the example provided doesn't have a custom IProxyGenerator class to make it generate ImplementedClass as a proxy of IMyInterface.

**Comment by jbogard** [comment]
Ohhhhh I missed that. Yeah, I think this might be taken care of with allowing custom PlatformAdapter extensions from #929

**Comment by fduman** [comment]
@TylerCarlson1 ProxyGenerator works fine and thanks for the #929 @lbargaoanu and @jbogard.

I didn't understand Automapper's mapping behaviours well . That's all.
