### ISSUE TITLE
Open generic mappings failed with derived types

### ISSUE THREAD

**Issue by fduman** [AutoMapper/AutoMapper#944]
public interface IMyInterface<T>
    {
        T Container { get; set; }
    }

    public class ContainerClass
    {
        public int MyProperty { get; set; }
    }

    public class ImplementedClass : IMyInterface<ContainerClass>
    {
        public ContainerClass Container
        {
            get;
            set;
        }
    }

    public class MyClass<T>
    {
        public T Container { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.CreateMap(typeof(MyClass<>), typeof(IMyInterface<>));

            Mapper.AssertConfigurationIsValid();

            var myClassInstance = new MyClass<ContainerClass>
            {
                Container = new ContainerClass { MyProperty = 3 }
            };

            var implementedClassInstance = new ImplementedClass();

            var obj1 = Mapper.Map(myClassInstance, implementedClassInstance, typeof(MyClass<ContainerClass>), typeof(IMyInterface<ContainerClass>));

            var obj2 = Mapper.Map(myClassInstance, typeof(MyClass<ContainerClass>), typeof(ImplementedClass));
        }
    }

obj1 mapped successfully but obj2 throws AutoMapperMappingException.
I wish that Automapper could also map derived types. 
Automapper version is 4.0.4.

**Comment by jbogard** [comment]
It does but you have to call CreateMap.

So, I use containers a lot. And what you *really* want is some sort of type scanning to scan through your assembly and line up implementations of your interface. It could do that, but it's never done anything of the sort. AutoMapper has only ever mapped types you've told it about.

Take the above example. How would AutoMapper know that ImplementedClass is a thing it should know about?

**Comment by fduman** [comment]
I expected more relaxed behavior. I didn't know that Automapper has strict mapping behavior.
Thanks @jbogard.

**Comment by jbogard** [comment]
I'm going to reopen this one, this might be a case that doesn't take any sort of scanning, since you're closing a type for an open generic map, right? It doesn't "know" about the implemented class, but it knows about the open generic interface.

**Comment by lbargaoanu** [comment]
@jbogard I think what we have now is the right behavior in this case. AutoMapper doesn't know about the derived type so it will have to create a proxy. If the destination type is the derived type and you use the generic Map you would get a cast error (Mapper.Map< ImplementedClass >). That's what happens now without generics, just a simple interface, and it seems wrong in [that case](https://gist.github.com/lbargaoanu/9b0af04f49d117c57ba9#file-derivedclassmappedinterface-cs).

**Comment by TylerCarlson1** [comment]
Can do this with a convention in 4.1.1

Add this after `Mapper.CreateMap(typeof(MyClass<>), typeof(IMyInterface<>));`
```
            Mapper.Configuration.AddConditionalObjectMapper().Where((s, d) =>
                    s.IsGenericType && d.GetInterfaces().FirstOrDefault() != null && d.GetInterfaces().First().IsGenericType
                    && (s.GetGenericTypeDefinition() != null)
                    && (d.GetInterfaces().First().GetGenericTypeDefinition() != null)
                    && Mapper.Engine.ConfigurationProvider.ResolveTypeMap(s, d.GetInterfaces().First()) != null);
```

One problem with this is you have to call the map to obj1 before calling obj2, because the base type map isn't cached. #960 Should fix this problem of having to use the base map first.

**Comment by TylerCarlson1** [comment]
Same basic rules apply to #943.  The convention is specifically tailored to type maps that inherit off the interface, and not base types.  If you want base types you change `d.GetInterfaces().First()` and `d.GetInterfaces().FirstOrDefault()` with `d.BaseType`
