### ISSUE TITLE
AutoMapper 4.1.0 Exception with Proxy on Inherited object with Entity Framework

### ISSUE THREAD

**Issue by swilkos** [AutoMapper/AutoMapper#945]
Seem to still have an issue with the latest build.  When creating an Entity Framework query and attempting to map the object over to a derived class causes a base object mapping exception.  Please let me know if more information is needed.

Classes:
```
    public class ExampleContext : DbContext
    {
        public DbSet<TrainingCourse> TrainingCourses { get; set; }
        public DbSet<TrainingContent> TrainingContents { get; set; }
    }

    public class TrainingCourse
    {
        public TrainingCourse()
        {
            Content = new List<TrainingContent>();
        }

        public TrainingCourse(TrainingCourse entity)
        {

            Mapper.Map(entity, this);
        }

        [Key]
        public int CourseId { get; set; }

        public string CourseName { get; set; }

        public virtual ICollection<TrainingContent> Content { get; set; }
    }

    public class TrainingContent
    {
        public TrainingContent()
        {
        }

        [Key]
        public int ContentId { get; set; }

        public string ContentName { get; set; }

        public virtual TrainingCourse Course { get; set; }

        public int CourseId { get; set; }

    }

    public class TrainingCourseDto
    {
        public int CourseId { get; set; }

        public string CourseName { get; set; }

        public ICollection<TrainingContentDto> Content { get; set; }
    }

    public class ParentTrainingCourseDto : TrainingCourseDto
    {
        [IgnoreMap]
        public new ICollection<TrainingContentDto> Content { get; set; }
    }

    public class TrainingContentDto
    {
        public int ContentId { get; set; }

        public string ContentName { get; set; }

        public ParentTrainingCourseDto Course { get; set; }

        public int CourseId { get; set; }
    }
```

Initializer:
```
            Mapper.Initialize(
                cfg =>
                    {
                        cfg.CreateMap<TrainingCourse, TrainingCourseDto>()
                        .Include<TrainingCourse, ParentTrainingCourseDto>();
                        cfg.CreateMap<TrainingCourse, ParentTrainingCourseDto>();
                        cfg.CreateMap<TrainingContent, TrainingContentDto>();

                        
                    });

            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();
```

Code that throws an excption with Automapper 4.1.0
```
            ExampleContext context = new ExampleContext();
            var course = context.TrainingCourses.FirstOrDefault(n => n.CourseName == "Course 1");
            var dto = Mapper.Map<TrainingCourseDto>(course);
```

Error thrown:
```
AutoMapper.AutoMapperMappingException : 

Mapping types:
TrainingCourse -> TrainingCourseDto
AutoMapper.BugExample.TrainingCourse -> AutoMapper.BugExample.TrainingCourseDto

Destination path:
TrainingCourseDto.Content.Content.Content0[0].Course0[0].Course0[0]

Source value:
System.Data.Entity.DynamicProxies.TrainingCourse_1F4098BB48C8E550C9BD06AA4E5078C25E68A8F1D567EB1E395EAFE4C70847D6
  ----> System.InvalidCastException : Unable to cast object of type 'AutoMapper.BugExample.TrainingCourseDto' to type 'AutoMapper.BugExample.ParentTrainingCourseDto'.
```

**Comment by jbogard** [comment]
Hmmm yeah, can you post what the source object types look like, in their full hierarchy? It looks like AutoMapper is going down the line here.

**Comment by lbargaoanu** [comment]
Same as #917.
LinqPad [example](https://gist.github.com/lbargaoanu/102001328d0b4546fe9c#file-efproxy-cs)

**Comment by swilkos** [comment]
The example @lbargaoanu did is spot on.   The context of the "ParentTrainingCourseDto" is a way to limit through Automapper how much is filled in and prevent recursion from happening.   We've gone a different route for the moment, but it seemed like a straight forward way to use the AutoMapper configuration vs. having to write a bunch of hand coded projections.

**Comment by lbargaoanu** [comment]
#917 still fails.

**Comment by jbogard** [comment]
So these are different issues then.

**Comment by lbargaoanu** [comment]
Well, they have the same root cause. Returning base destination types when we shouldn't. My fix may be arbitrary but it fixes both.

**Comment by jbogard** [comment]
What fix?

**Comment by lbargaoanu** [comment]
#923

**Comment by jbogard** [comment]
Jeez that took like 2 seconds for me to find it sigh. Marking for 4.1.1, I want to get this one out ASAP

**Comment by lbargaoanu** [comment]
Of course I replayed your last check in, but I don't know :) It feels like the source type should be the first. Not exactly an argument I know.

**Comment by jbogard** [comment]
No that was just a guess of a fix, I didn't really like it. It makes some assumptions on the order of a SelectMany. If yours works I'll just revert my """"fix""""

**Comment by jbogard** [comment]
@swilkos can you check the MyGet release? Just pushed a fix for this (and included integration tests to make sure this stays fixed).

**Comment by swilkos** [comment]
Will do and get back with you.

**Comment by swilkos** [comment]
My apologies, am new to working with MyGet.   Using the URL https://www.myget.org/F/automapperdev/api/v2, Get-Package -ListAvailable shows now packages.  Is there a different URL to work with?

Thanks!

**Comment by jbogard** [comment]
That's the right URL, are you showing pre-release packages?

**Comment by swilkos** [comment]
Imagine that!  Seems to be working as I'd expect it on my sample project.  Will plug the pre-release into our main application later today and test it on a larger scale then the small example project I put together when tracking down what was happening.

**Comment by Jerome2606** [comment]
Is this problem is fix for you ?

I have the same problem on my project with AutoMapper 4.1.1
