### ISSUE TITLE
Simple Issue: Ignore Exceptions

### ISSUE THREAD

**Issue by Michael-DST** [AutoMapper/AutoMapper#947]
This is more of a question than an issue.  Please feel free to close this upon answering.  I am basically wanting to use AutoMapper to map all properties from one type to another, and if an exception occurs during the mapping of any properties, continue on until the mapping is done.  Currently it is throwing an exception due to a business rule for a null value and I would like it to continue instead.

I did look online but didn't seen anything obvious, so here I am. :)  Thank you for any assistance/consideration!

**Comment by jbogard** [comment]
Have you looked at the code to see how this might be implemented?

**Comment by Michael-DST** [comment]
That sounds like a lot of work. ;)  Are you saying that this is currently not possible?  Seems like a common scenario to me, but what do I know. :)

**Comment by lbargaoanu** [comment]
Randomly catching exceptions... Sounds bad to me. Maybe gathering every exception and throw an AggregateException at the end. Still kind of bad. If any new feature starts with -100, I would give this one -200.

**Comment by jbogard** [comment]
Nah, I have no idea what it would take.

People asked for this for configuration validation, so I modified the process to aggregate exceptions.

**Comment by Michael-DST** [comment]
Ah well cool.  Thanks for insight.  I am digging through the code now.  Guess I like the work after all. :P  I was thinking this was a simple/accounted for scenario but apparently I'm on my own as usual, haha.

To be sure, @lbargaoanu it's not randomly catching exceptions, but catching random exceptions. :)  There is a difference in that.  I am looking for a general-purpose, easy mapper that says "try to copy data from one item to another, if it works, great, if not, provide me some way of seeing what went wrong, and if there is something I care about, then I will throw a subsequent relevant exception."

Thanks for any consideration.

**Comment by Michael-DST** [comment]
Thanks again for the consideration/dialogue.  FWIW, I got around this issue by only mapping properties that have values:
https://github.com/DragonSpark/Framework/blob/Multiversal/DragonSpark/Extensions/Mappings.cs#L12-L15
