### ISSUE TITLE
Inherited mapping in ProjectTo() not working.

### ISSUE THREAD

**Issue by JozefKulla** [AutoMapper/AutoMapper#948]
When I use ProjectTo<>(), then mapper ignore Inherited mapping. I try use Include<>() and IncludeBase<>(), but still not working.

**Comment by lbargaoanu** [comment]
We need a gist that we can run and see it fail.

**Comment by TylerCarlson1** [comment]
This doesn't work because Entity Framework can't support this scenario.  #570 and #701 explain this.
Has a request for EF 6 here https://entityframework.codeplex.com/workitem/2730.  It's up for grabs if someone wants to tackle it.

**Comment by JozefKulla** [comment]
Thanks for answer, I create simply solution for my case. 

```cs
public static void DbIncludeBase<TSource, TDestination, TDestinationBase>(this IMappingExpression<TSource, TDestination> mapper) where TDestination : TDestinationBase
        {
            var map = Mapper.FindTypeMapFor<TSource, TDestination>();
            var propertyMap = map.GetPropertyMaps();

            var mapForInclude = Mapper.FindTypeMapFor<TSource, TDestinationBase>();
            var propertyMapForInclude = mapForInclude.GetPropertyMaps();

            propertyMapForInclude.Where(i => !propertyMap.Any(j => j.DestinationProperty.Name == i.DestinationProperty.Name)).ToList().ForEach(i =>
            {
                map.AddPropertyMap(i);
            });
        }

```

**Comment by lbargaoanu** [comment]
@JozefKulla Did you try with Mapper.Initialize and the latest from NuGet?

**Comment by lbargaoanu** [comment]
@JozefKulla Can you please close your issue?
