### ISSUE TITLE
Breaking Change in 4.1.0 ProjectTo(IMappingEngine) overload

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#949]
At 4.0.4, there were two overloads for .ProjectTo:
* `.ProjectTo<TDest>()`
* `.ProjectTo<TDest>(mappingEngine)`

4.1.0 introduced `.ProjectTo<TDest>(object parameters, membersToExpand)`.  This breaks code written using the 4.0.4 overload, and it does so in a way which will not introduce any compile errors - the code will silently fail, trying to use the default mapper instead, as the new overload takes precedence.

The following code works fine in 4.0.4:

	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestMethod1()
		{
			var mapperConfig = new ConfigurationStore(new TypeMapFactory(), MapperRegistry.Mappers);
			mapperConfig.CreateMap<Foo, Bar>();
			var mapper = new MappingEngine(mapperConfig);

			IList<Foo> source = new List<Foo>();

			var result = source.AsQueryable().ProjectTo<Bar>(mapper).ToList();
		}

		public class Foo { }

		public class Bar { }
	}

In 4.1.0 it will fail because it falls back to using the default mapper.  The code has to be changed to work, from:

    var result = source.AsQueryable().ProjectTo<Bar>(mapper).ToList();

to

    var result = source.AsQueryable().ProjectTo<Bar>(null, mapper).ToList();

I appreciate it's a bit late to do anything about this change as people will already have begun upgrading - fortunately my unit tests caught this behaviour and I was able to spot it.  I think the release notes could do with mentioning this change however.

**Comment by jbogard** [comment]
Hmmm this was not intentional - I tried to keep the overloads consistent (and also get rid of the optional parameters, those are nothing but trouble). This reminds me of the errors I would get from MVC.

I wonder if I can throw an exception if the parameters object is IMappingEngine?

**Comment by richardlawley** [comment]
I guess that's a possibility, though probably only worthwhile if you were going to push out a fix soon - if it was being left for the next version then I would imagine most people would hit the problem and fix it - I raised this mostly so there would be a search hit if someone else came up on the problem.

**Comment by richardlawley** [comment]
Just so you're aware, 4.2.0 seems to have reverted this change, with the result that we have to go back to the single parameter, e.g.

    var result = source.AsQueryable().ProjectTo<Bar>(mapper.ConfigurationProvider).ToList()

As before, this is a silent error - the syntax which worked in 4.1.1 is still valid, but at runtime you get a null reference exception, because the overload this now matches (not 100% sure but I think it's configuration, parameters, membersToExpand) gets a null for configuration.

**Comment by lbargaoanu** [comment]
This should be fixed in 5.0
