### ISSUE TITLE
Automatically-mapped Properties are now case sensitive

### ISSUE THREAD

**Issue by richardlawley** [AutoMapper/AutoMapper#950]
I'm not sure if this is an intentional change, as I could find no mention of it in the 4.1.0 release notes or the titles of the fixed issues, but automatically mapped properties are now case sensitive.  The following code worked in 4.0.4, but fails in 4.1.0:

	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestMethod1()
		{
			Mapper.CreateMap<Foo, Bar>();
			Mapper.AssertConfigurationIsValid();
		}

		public class Foo
		{
			public int ID { get; set; }
		}

		public class Bar
		{
			public int id { get; set; }
		}
	}

**Comment by jbogard** [comment]
Ah, this one snuck in. @TylerCarlson1 I think this one was from the conventions PR, is the ToUpper in PascalCaseNamingConvention needed?

**Comment by TylerCarlson1** [comment]
It's used so that if you have foo_bar in one class map to a class with foobar and FooBar, it will pick FooBar consistantly instead of foobar or FooBar based on the position of the property in the code.

**Comment by TylerCarlson1** [comment]
DefaultName is where the case sensitivity code resides.

This code should work if you want it back through code.
Create this class and add it to the default member configuration.
```
Mapper.Initialize(cfg => cfg.DefaultMemberConfig.AddName<CaseInsensitiveName>());
```
```
public class CaseInsensitiveName : ISourceToDestinationNameMapper
    {
        public MemberInfo GetMatchingMemberInfo(IGetTypeInfoMembers getTypeInfoMembers, TypeDetails typeInfo, Type destType, string nameToSearch)
        {
            return
                getTypeInfoMembers.GetMemberInfos(typeInfo)
                    .FirstOrDefault(mi => string.Compare(mi.Name, nameToSearch, StringComparison.OrdinalIgnoreCase) == 0);
        }
    }
```

Can change DefaultName to have a case sensitivity option that defaults to off, that you can then later send to on.

**Comment by jbogard** [comment]
So I thiiiiiink I'm going to make the default to be case insensitive? Then add case sensitive if you need it?

**Comment by TylerCarlson1** [comment]
Sounds good, I guess.  If case insensitivity is the default that's fine.  Does Automapper need this kind of option in IConfiguration to set this, as well is having the option in DefaultName?

**Comment by TylerCarlson1** [comment]
If you want it out ASAP then you can just replace DefaultName's code with CaseInsensitiveName's for now.

**Comment by dittodhole** [comment]
:+1

**Comment by dittodhole** [comment]
:+1:

**Comment by dodgster02** [comment]
I may be wrong but this bug fix does not take into account when you have specified member prefixes or postfixes. 

I modified the test case above to do an integration test using 4.1.0, and 4.1.1 and the prefix and postfix matching is applied when the properties are spelt exactly the same (e.g. ID -> test_ID) but not when the properties are spelt differently (e.g ID -> test_Id)

Same functionality works fine in 4.0.4 though

**Comment by TylerCarlson1** [comment]
Did you change anything else besides adding prefix?  Like changing the Source or Destination name splitter from Pascal?   Was the prefix test or test_?

#900 Shows an issue with the Pascal Name Splitter and some weird edge cases.  This might be what's going on.

**Comment by ericleung15** [comment]
no, I just added strings for the prefix and postfixes to identify (in my test case I had "test_" as prefix and "_test" as postfix).

I also added some test cases for with postfix and prefix values excluding underscore but still no good.

Here's the test code I'm running with. I was running it in a console app so that I can switch automapper versions using nuget

```C#
static void Main(string[] args)
        {
            Mapper.Initialize(x =>
            {
                x.RecognizeDestinationPrefixes("test_", "test");
                x.RecognizeDestinationPostfixes("_test", "test");
                x.DisableConstructorMapping();
                x.AllowNullCollections = true;
                x.AllowNullDestinationValues = true;
                x.CreateMap<Test, OrderedTest>();
                x.CreateMap<Test, TestPrefix>();
                x.CreateMap<Test, TestAltPrefix>();
                x.CreateMap<Test, TestAltPrefixPascal>();
                x.CreateMap<Test, TestPrefixPascal>();
                x.CreateMap<Test, TestPascal>();
                x.CreateMap<Test, TestPostfix>();
                x.CreateMap<Test, TestPostfixPascal>();
                x.CreateMap<Test, TestAllPostfixPascal>();
            });

            var atest = new Test()
            {
                ID = 5,
                AString = "Testing"
            };

            var secondTest = new OrderedTest
            {
                ID = 10,
                AString = "Testing213234"
            };

            Console.WriteLine("About to map");
            var newversion = Mapper.Map<OrderedTest>(secondTest);
            secondTest = Mapper.Map<OrderedTest>(atest);
            var tPrefix = Mapper.Map<TestPrefix>(atest);
            var tAltPrefix = Mapper.Map<TestAltPrefix>(atest);
            var tAltPrefixFixPascal = Mapper.Map<TestAltPrefixPascal>(atest);
            var tPascalPrefix = Mapper.Map<TestPrefixPascal>(atest);
            var tPascal = Mapper.Map<TestPascal>(atest);
            var tPostFix = Mapper.Map<TestPostfix>(atest);
            var tPostFixPascal = Mapper.Map<TestPostfixPascal>(atest);
            var tAltPostFixPascal = Mapper.Map<TestAllPostfixPascal>(atest);            
            Console.WriteLine("Done Mapping");
            Console.ReadLine();
        }
    }

    public sealed class Test : ITest
    {
        public int ID
        {
            get;
            set;
        }

        public string AString
        {
            get;
            set;
        }
    }

    public interface ITest
    {
        int ID { get; }
        string AString { get; }
    }

    public class OrderedTest
    {
        public int ID { get; set; }
        public string AString { get; set; }
    }

    public class TestPrefix
    {
        public int test_ID { get; set; }
        public string test_AString { get; set; }
    }

    public class TestAltPrefix
    {
        public int testID { get; set; }
        public string testAString { get; set; }
    }

    public class TestAltPrefixPascal
    {
        public int testId { get; set; }
        public string testAstring { get; set; }
    }

    public class TestPrefixPascal
    {
        public int test_Id { get; set; }
        public string test_Astring { get; set; }
    }

    public class TestPascal
    {
        public int Id { get; set; }
        public string Astring { get; set; }
    }

    public class TestPostfix
    {
        public int ID_test { get; set; }
        public string AString_test { get; set; }
    }

    public class TestPostfixPascal
    {
        public int Id_test { get; set; }
        public string Astring_test { get; set; }
    }

    public class TestAllPostfixPascal
    {
        public int Idtest { get; set; }
        public string Astringtest { get; set; }
    }
}
```

**Comment by TylerCarlson1** [comment]
Prefixes and post fixes have their own string comparison function inside of it, and it's Case sensitive.

**Comment by ericleung15** [comment]
Ok, I'll open another issue for this as the bug is to do with the prefix/postfix matching specifically

**Comment by killergege** [comment]
I don't think this is fixed, is it ?
AutoMapper is still case sensitive. I see in the Release changelog for 4.2.0 "#955 Add case sensitivity option for DefaultName comparer" but I'm not sure how I can use this option.

And I can't do as suggested above :
`Mapper.Initialize(cfg => cfg.DefaultMemberConfig.AddName<CaseInsensitiveName>());`
There is no DefaultMemberConfig on cfg.

I tried with a profile, the property is there but it doesn't seem to do much.
Could you add something about case sensitivity in the wiki ?

**Comment by TylerCarlson1** [comment]
Which version are you using?

Also with case sensitivity #1141 might be relevant if you are using Prefixes and Postfixes.

**Comment by killergege** [comment]
I'm using the nuget version so 4.2.1
Right now I'm testing it, I don't use any fancy feature like prefixes... 
The target object has exactly the same columns as the source, except casing (source is all lower case), but I forgot to mention that the source object is a dynamic one (from a Dapper query), I'll submit code soon.

**Comment by dpwilson** [comment]
I am experiencing the same issue as @killergege when trying to map from a dynamic source object. The property names are the same between source and destination other than casing.

```
var account = await response.Content.ReadAsAsync<dynamic>();
var accountDTO = this.mapper.Map<Account.Api.Models.Account>(account);
```

I just realized as I was writing this that in my case I can map my object directly through the ReadAsAsync method without going through AutoMapper, but if that wasn't an option then I would be stuck.

`var account = await response.Content.ReadAsAsync<Account.Api.Models.Account>();`

**Comment by thtp** [comment]
Having same issue as @killergege .

```
var asExpando = value as ExpandoObject;
if (asExpando != null)
{
    var whatever = asExpando.Map(valueType);
}
```
This operation is case sensitive.

**Comment by TylerCarlson1** [comment]
@thtp @killergege @dpwilson For dynamic it's expected functionality.
All the rules of the member names, prefixes postfixs flattening, case insensitivity are not available in dynamic.  That's how it's been since the very beginning.

If you want said functionality I would suggest making a new Issue for it
