### ISSUE TITLE
GetUnmappedPropertyNames() seems broken in 4.1.0

### ISSUE THREAD

**Issue by skivsoft** [AutoMapper/AutoMapper#954]
Hello,

I have found a problem in `TypeMap.cs: GetUnmappedPropertyNames()` while debug [an issue in project which depends on AutoMapper](https://github.com/IdentityServer/IdentityServer3.EntityFramework/issues/72).

Here is [diff with previous release 4.0.4](https://github.com/AutoMapper/AutoMapper/compare/88be8a1feda45f5abecee875ff3c85d719bdb955...master?diff=unified&name=master#diff-30dcafc3d6228bf0b9da3da1dcc9b323R119) at `TypeMap.cs:119`.

The problem appears when `pm.SourceMember == null`.
```csharp
public string[] GetUnmappedPropertyNames()
{
    Func<PropertyMap, string> getFunc = 
        pm => ConfiguredMemberList == MemberList.Destination 
              ? pm.DestinationProperty.Name : pm.SourceMember.Name;
    ...
}
```

I'm not quite sure how to fix it, but I think it could be something like this

```csharp
public string[] GetUnmappedPropertyNames()
{
    Func<PropertyMap, string> getFunc;
    if (ConfiguredMemberList == MemberList.Destination)
        getFunc = pm => pm.DestinationProperty.Name;
    else
        getFunc = pm => pm.CustomExpression == null && pm.SourceMember != null 
           ? pm.SourceMember.Name : pm.DestinationProperty.Name;
    ...
}
```

**Comment by lbargaoanu** [comment]
A failing test would help.

**Comment by jbogard** [comment]
Yeah, I'm not sure what this issue has to do with the Identity Server one?

**Comment by skivsoft** [comment]
It appears in [IdentityServer3.EntityFramework](https://github.com/IdentityServer/IdentityServer3.EntityFramework) project after upgrading AutoMapper in this test [AutomapperTests.cs](https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework.IntegrationTests/AutomapperTests.cs).
