### ISSUE TITLE
ProjectTo only reading from type map cache and not trying to resolve.

### ISSUE THREAD

**Issue by TylerCarlson1** [AutoMapper/AutoMapper#957]
If use conventions for TypeMaps and don't map them, then ProjectTo will say there's no mapping and to create one.

If you map the types before you call project to it works fine, because the mapping has been cached and can be called by ProjectTo.

Will look into it more and get an example soon.

**Comment by TylerCarlson1** [comment]
Looks like IObjectMapper is a bad place to put convention logic.  ConfigurationStore.ResolveTypeMap is probably a more appropriate place, so it can handle finding type maps.
And possibly OpenGenericMapper should go in here as well.  It looks very out of place where it is now.

**Comment by jbogard** [comment]
Merged.
