### ISSUE TITLE
Issue with Datamember atribute on flatten property

### ISSUE THREAD

**Issue by forcewill** [AutoMapper/AutoMapper#959]
I have the following DTO

   
    [DataContract]
    public class PlanStudyDTO
    {   
        [DataMember]
        public long Id { get; set; }

        [DataMember(Name = "course_id")]
        public long CourseId { get; set; }

       // [DataMember(Name = "number_enrollements")]
        [DataMember]
        public Int64 UserCoursesCount { get; set; }
        
    }

And for brevity the following Entity class

    public partial class PlanStudy
    {
        ...
        public long Id { get; set; }
      
        public virtual ICollection<UserCours> UserCourses { get; set; }

    }

Since in my DTO i wanted to return the total of UserCourses i created the 
UserCoursesCount which works fine  mapping to UserCourses.Count 
as long as i don't uncomment  [DataMember(Name = "number_enrollements")]  
 how can i get this to work ? or is this in fact an issue as i suspect, since what i serialize from and to shouldn't affect the mapping

**Comment by lbargaoanu** [comment]
Most likely AutoMapper has nothing to do with your problem.

**Comment by forcewill** [comment]
@lbargaoanu  how it has nothing to do it 
it maps correctly when Name = "..." is comment on the DataMember attsibute and fails otherwise,
all other properties map correct this has to do with Flattening i don't see how it can be unrelated 
but we never know :smile:

**Comment by lbargaoanu** [comment]
Then try to make a gist with a failing test. I could be wrong. it happened before :)

**Comment by TylerCarlson1** [comment]
Stupid question, but are you talking about it not mapping correctly on the Client, or Server side?  If it's on the server, before you send it over the WCF service, then it's most likely Automapper.  If it's on the client side, after it's been sent, then it's most likely a WCF problem because your DataMember contracts are most likely out of sync.

**Comment by forcewill** [comment]
After a night sleep and a package update i don't have the issue anymore i bet it was the night sleep :smile:
