### ISSUE TITLE
Type to String mappings throwing errors since upgrade to 4.1.x

### ISSUE THREAD

**Issue by vobreshkov** [AutoMapper/AutoMapper#964]
Since upgrading to AutoMapper 4.1.1 all my mappings like Guid -> String, Enum -> String and even int -> string are failing.

Example:

    // TEntity.Status is an enum and TDto.StatusName is a string
    // This used to work before upgrading to 4.1.x
    Mapper.CreateMap<TEntity, TDto>().ForMember(m => m.StatusName, o => o.MapFrom(s => s.Status.ToString()) 

Also if I try to use `ConvertUsing<TSource, TDestination>()` I get an error as well.

Examples (all are failing):

    Mapper.CreateMap<Status, string>().ConvertUsing(c => c.ToString());
    Mapper.CreateMap<Guid, string>().ConvertUsing(c => c.ToString());
    Mapper.CreateMap<int, string>().ConvertUsing(c => c.ToString());

I get IntelliSense error stating that:

    The call is ambiguous between the following methods or properties: 'IMappingExpression<TSource, TDestination>.ConvertUsing(Func<TSource, TDestination>)' and 'IMappingExpression<TSource, TDestination>.ConvertUsing(Func<ResolutionContext, TDestination>)'

The exact same thing is happening when I try to map/convert from Guid to String:

    // TEntity.Id is Guid (MSSQL), TDocument.Id is a string (DocumentDB)
    Mapper.CreateMap<TEntity, TDocument>().ForMember(m => m.Id, o => o.MapFrom(s => s.Id.ToString())

I am now having to write type converters for everything that converts to a string, including basic types such as int->string.

Am I missing something new in the change logs? Is this a new behavior?

**Comment by jbogard** [comment]
Are you calling Mapper.Map or using LINQ projection? What was the version you were using before 4.1.x?

**Comment by vobreshkov** [comment]
Using LINQ projection but the errors I'm getting are in my AutoMapperConfig startup class where I define the mappings. I was on 3.3.x before.

**Comment by jbogard** [comment]
LINQ projection doesn't use ConvertUsing, it uses ProjectUsing. ConvertUsing is Func, ProjectUsing is "Expression". Also, you shouldn't need those Guid -> String methods, LINQ projections supports ToString() OOTB now.

**Comment by vobreshkov** [comment]
Didn't know that. Also if I use both methods (ProjectTo() and Mapper.Map()) do I need to define both ConvertUsing() and ProjectUsing() mappings?

**Comment by jbogard** [comment]
No you don't - ProjectUsing is compiled to ConvertUsing (so is MapFrom and all the expression-based methods). The reverse isn't true, though. You can't use ResolveUsing in LINQ.

**Comment by vobreshkov** [comment]
Great. All errors are gone now. Much cleaner too. Thank you so much!

**Comment by jbogard** [comment]
And for future folks, the ConvertUsing signature got an overload, where there could *potentially* be collisions. You'd just need to be more specific:

```
Mapper.CreateMap<Status, string>().ConvertUsing((Statuc c) => c.ToString());
Mapper.CreateMap<Guid, string>().ConvertUsing((Guid c) => c.ToString());
Mapper.CreateMap<int, string>().ConvertUsing((int c) => c.ToString());
```

**Comment by TylerCarlson1** [comment]
Saw this same situation with things like double?->double which worked in earlier versions, but not now.  Does that apply here with you have to call ConvertUsing in 4.1?

**Comment by jbogard** [comment]
God I don't know I just hate nullables, they lie with their GetType.

**Comment by TylerCarlson1** [comment]
So just use ConvertUsing gotcha.

**Comment by jbogard** [comment]
Well if you're using LINQ, ideally you could just only use ProjectUsing and catch both scenarios.

**Comment by TylerCarlson1** [comment]
That's what I had to do to get it to work with ProjectTo.

**Comment by jbogard** [comment]
Open an issue?
