### ISSUE TITLE
change Configuration wiki page

### ISSUE THREAD

**Issue by brenovieira** [AutoMapper/AutoMapper#965]
Can I change [this page](https://github.com/AutoMapper/AutoMapper/wiki/Configuration#profile-instances) on wiki ?

Since commit [Makeing Configurations multiLevel](https://github.com/AutoMapper/AutoMapper/commit/720b45e01d3d7105fb8ff5ec0a2a34a5967e46fd#diff-a040f1da85ea918e0c7af96e1cf54819R25) ProfileName  isn't virtual, so this example on wiki page doesn't compile:

````csharp
public class OrganizationProfile : Profile 
{
  protected override void Configure() 
  {
    //Put CreateMap... Etc.. here
  }

  public override string ProfileName  // <---- we can't override ProfileName
  { 
    get { return this.GetType().Name; } 
  } 
}
````

**Comment by jbogard** [comment]
Anyone can change the wiki, have at it!

**Comment by brenovieira** [comment]
Thanks. Done!

Only warning to document it.
This is one "breaking change" when upgrading to 4.1.1 ;)

**Comment by Datar89** [comment]
Why did you change the virtual for ProfileName? I just want to be clear about that. I upgraded from 3.3.1 to 4.1.1 and noticed the change

**Comment by brenovieira** [comment]
@Datar89 , I didn't do the change.
But I noticed the wiki page suggested to use 
```
public override string ProfileName
{ 
    get { return this.GetType().Name; } 
} 
```

But this is actually what the `Profile` parameterless constructor is doing [here](https://github.com/AutoMapper/AutoMapper/blob/720b45e01d3d7105fb8ff5ec0a2a34a5967e46fd/src/AutoMapper/Profile.cs#L22).

You can still use this constructor [here](https://github.com/AutoMapper/AutoMapper/blob/720b45e01d3d7105fb8ff5ec0a2a34a5967e46fd/src/AutoMapper/Profile.cs#L15) and pass `profileName` you want.

**Comment by Datar89** [comment]
Yes. I know that you didn't make the change, sorry for the misunderstanding. Thanks for the clarification. I think that it has a better implementarion now.
