### ISSUE TITLE
Prefix/Postfix property matching is now case sensitive

### ISSUE THREAD

**Issue by ericleung15** [AutoMapper/AutoMapper#967]
Between 4.04 and 4.1.0 the prefix and postfix property name matching algoithm changed from being case insensitive to case sensitive.

Using the test case shown in #950, I expanded the test cases into an integration test  (added as comment to same issue) to include prefix and postfix destination values, so that I could easily point to different versions of Automapper.

Perhaps we should be allowed to state whether to use Case sensitive or Case Insensitive matching when also using prefix and postfix property pattern matching.

**Comment by lbargaoanu** [comment]
I think this is fixed in 4.1.1 on nuget.

**Comment by ericleung15** [comment]
Should also have mentioned that I did the same test against 4.1.1 and it's still default case sensitive.

From @TylerCarlson1 in #950, prefix and postfix matching contains its own separate string comparison logic
