### ISSUE TITLE
ProjectTo is not including base mapings

### ISSUE THREAD

**Issue by cervengoc** [AutoMapper/AutoMapper#969]
Consider the following scenario:

```
public class DomainModel {
  public string A {get; set;}
  public IList<SomeOtherDomainClass> Children {get; private set;}
}

public class DtoBase {
  public string A {get; set;}
  public int ChildCount {get; set;} // mapped from Children.Count
}

public class Dto : DtoBase {
  public string C {get; set;} // not mapped from domain, but calculated at runtime, etc.
}

...

Mapper.CreateMap<DomainModel, DtoBase>()
    .ForMember(e => e.B, o => o.MapFrom(e => e.Children.Count())
    .Include<DomainModel, Dto>();

Mapper.CreateMap<DomainModel, Dto>();

...

var query = db.Query<DomainModel>().ProjectTo<Dto>().ToList();
// here all ChildCount is zero, and ChildCount member not even included in select statements
```

How could I get the DtoBase mappings applied to the inherited Dto too?

**Comment by TylerCarlson1** [comment]
I think you have to do `Mapper.CreateMap<DomainModel, Dto>().IncludeBase<DomainModel, DtoBase>();`  that way it will include and take all base Member mappings.  It has to happen after base map though cause if not it's not going to find base mappings and transfer them over.  What you have right now doesn't transfer over Member mappings.

**Comment by lbargaoanu** [comment]
Include and IncludeBase are symmetrical, either one should do the job. Did you try with Mapper.Initialize with the latest from NuGet? @TylerCarlson1 #948 is different?

**Comment by TylerCarlson1** [comment]
If I understood it right it is.  It's projecting with a collection of DtoBase and won't map the individual items to DtoA, DtoB, DtoC.

**Comment by cervengoc** [comment]
@TylerCarlson1 no, it's a different scenario. The source type is same, and I have two destination types in this case, one inherited from the other.

@lbargaoanu I am using the latest nuget package, but don't know what exactly you mean with Mapper.Initialize. Where and when should I call it?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Configuration

**Comment by TylerCarlson1** [comment]
@cervengoc was talking about #948 and how it's a different scenario from this one.

@lbargaoanu IncludeBase is symmetrical to Include, but has extra functionality.  It adds the base type map to it's included base type map list.  So when resolving property maps it checks this base map, and adds its property map.  Include doesn't do this step, and is why the base map property didn't come over from the base type map.

**Comment by lbargaoanu** [comment]
[Working example](https://gist.github.com/lbargaoanu/0ae26a08d1a7821c2c91#file-project-and-include-cs) with Include.

**Comment by lbargaoanu** [comment]
@cervengoc Can you please close your issue?

**Comment by cervengoc** [comment]
Sorry for forgetting about this issue. Actually after using `Mapper.Initialize` it works fine. Thank you all for your help.
