### ISSUE TITLE
Question about GenericTypeConverter

### ISSUE THREAD

**Issue by imperugo** [AutoMapper/AutoMapper#970]
Hi, 
in my domain I've some localised properties that looks very similar to this

```csharp
public class MyEntity : EntityBase
{
	public bool Enabled { get; set; }
	public string Name { get; set; }
	public double? Rating { get; set; }
	public string Url { get; set; }
	public Dictionary<CultureInfo, string[]> Tags { get; set; }
	public Dictionary<CultureInfo, Category[]> Categories { get; set; }
	public Dictionary<CultureInfo, Location> Location { get; set; }
	public Photo Logo { get; set; }
}
```

For my APIs the response is very similar except for the localised values that aren't a dictionary, but a single instance thanks to the ```Thread.CurrentThread.CurrentCulture``` 

```csharp
public class MyEntityResponse
{
	public string Id { get; set; }
	public bool Enabled { get; set; }
	public string Name { get; set; }
	public double? Rating { get; set; }
	public string Url { get; set; }
	public string[] Tags { get; set; }
	public Category[] Categories { get; set; }
	public Location Location { get; set; }
	public Photo Logo { get; set; }
}
```

I was thinking to use a ```CustomTypeConverter``` to copy the right localised value into the response and my code looks like this:

```csharp
public class LocalizedTypeConverter<T> : TypeConverter<Dictionary<CultureInfo, T>, T>
{
	protected override T ConvertCore(Dictionary<CultureInfo, T> source)
	{
		return source.SingleOrDefault(x => x.Key.Name == Thread.CurrentThread.CurrentCulture.Name).Value;
	}
}
```

The bad part is that I've no idea how to register it :(
[Here](https://github.com/AutoMapper/AutoMapper/wiki/Open-Generics) it says I can use something like this:

```csharp
Mapper.CreateMap(typeof(Source<>), typeof(Destination<>)).ConvertUsing(typeof(Converter<>));
```
but replacing ```Source<>```,```Destination<>``` and ```Converter<>``` with my classes it doesn't compile

```csharp
Mapper.CreateMap(typeof(Dictionary<CultureInfo,<>>), typeof(<>)).ConvertUsing(typeof(LocalizedTypeConverter<>));
```

Any hint?
Thanks

**Comment by lbargaoanu** [comment]
I think [ResolveUsing](https://github.com/AutoMapper/AutoMapper/wiki/Custom-value-resolvers) is a better fit here.

**Comment by imperugo** [comment]
mmm that means I've to specify a resolver for each property.
I've hundred classes with that properties, it will be longer

**Comment by lbargaoanu** [comment]
You can also use a converter for each property type.

**Comment by imperugo** [comment]
Is absolutely easier than a resolver for each property.
I was wondering if there was a way to do it one time for all, but it seems there's no way so ..... let's start to create a Converter for each property type

**Comment by lbargaoanu** [comment]
@imperugo Can you please close your issue?
