### ISSUE TITLE
Ignore Property if not found

### ISSUE THREAD

**Issue by Bhimisetty** [AutoMapper/AutoMapper#972]
Hello,
I would like to ignore specific property if the value not found while creating a mapping.
For example:
```
  Mapper.CreateMap<Source, Destination>()
                .ForMember(x => x.Property, map => map.MapFrom(options => options.Property.subProperty))
```
Here i am mapping the property which is model entity. If that object is not found then the "Propery" will be ignored.

Is this possible to achieve?

**Comment by jbogard** [comment]
If what object is not found? There is a Condition option in the ForMember declaration, but keep in mind it can't be used with ProjectTo.

**Comment by Bhimisetty** [comment]
Mapper.CreateMap()
.ForMember(x => x.NewObject, map => map.MapFrom(options => options.NewObject.NewProperty))

In this checks for "NewObject", if not found then need to ignore the property.

**Comment by jbogard** [comment]
Ah, then Condition will work just fine, it's on that "map" parameter you have.

**Comment by Bhimisetty** [comment]
No, It is not working. Getting the exception "no row found with the entity details having id #". Do I need to change any code in the above line?

**Comment by jbogard** [comment]
Are you using Condition? I didn't see that in your config.

**Comment by Bhimisetty** [comment]
Hey, I am asking that. How could I incorporate the condition in the mapping ForMember? Based on the condition the property need to be ignored? Is this achievable?

**Comment by jbogard** [comment]
```
Mapper.CreateMap<Source, Destination>()
    .ForMember(x => x.Property, map => { 
          map.MapFrom(options => options.Property.subProperty);
          map.Condition(src => src.Property != null);
});
```

**Comment by Bhimisetty** [comment]
Not working with the not null condition. Hope need to check with the object not found option. Will this be possible?
