### ISSUE TITLE
Upgrading to AutoMapper 4 add dependency on prerelease of .NET5 assemblies?

### ISSUE THREAD

**Issue by jordan112** [AutoMapper/AutoMapper#973]
We were on AutoMapper3 and are attempting to upgrade to Automapper4.  When we tried to upgrade to AutoMapper4, it has a dependency on .NET5 assemblies, which as far as I can tell are still pre-release.  Our solutions are all currently .NET4.

I think I'm missing something with PCL, but can't seem to find that on Nuget.  https://lostechies.com/jimmybogard/2013/09/04/automapper-3-0-portable-class-libraries-and-platformnotsupportedexception/

I do see that AutoMapper 4 supports .NET4.  https://lostechies.com/jimmybogard/2015/10/22/automapper-4-1-0-released/

```
Supports the following frameworks:

.NET 4.0
.NET 4.5
dotnet (all dnxcore/UWP targets)
MonoTouch
MonoTouch10
PCL profile 259
MonoDroid
WinRT/Windows Phone 8.1
Windows Phone 8.0
Silverlight 5
```

https://www.nuget.org/packages/AutoMapper/

```
DotNET 5.0
Microsoft.CSharp (≥ 4.0.0)
System.Collections (≥ 4.0.10)
System.Collections.Concurrent (≥ 4.0.10)
System.Diagnostics.Debug (≥ 4.0.10)
System.Dynamic.Runtime (≥ 4.0.10)
System.Linq (≥ 4.0.0)
System.Linq.Expressions (≥ 4.0.10)
System.Linq.Queryable (≥ 4.0.0)
System.ObjectModel (≥ 4.0.10)
System.Reflection (≥ 4.0.10)
System.Reflection.Extensions (≥ 4.0.0)
System.Reflection.TypeExtensions (≥ 4.0.0)
System.Runtime (≥ 4.0.20)
System.Runtime.Extensions (≥ 4.0.10)
System.Text.RegularExpressions (≥ 4.0.10)
System.Threading (≥ 4.0.10)
System.Threading.Tasks (≥ 4.0.10)
```

**Comment by jbogard** [comment]
The AutoMapper package itself is composed of several target-specific assemblies. There is a .NET 5 target that has dependencies on *released* versions of .NET Core packages. Not pre-release, otherwise I wouldn't be able to mark my package as pre-release.

The other targets don't have these dependencies, except for the .NET 4 which as a single dependency (that's what NuGet shows).

The 4.1.1 release fixed a problem in the .nuspec file that had some metadata that wasn't required any more and caused problems in some IDEs, these are the "reference assemblies" section. You might be having issues with that, so try 4.1.1.

**Comment by jordan112** [comment]
So the nuspec will determine which framework its being used with and bring in the proper version.  Gotcha.

We were trying a week or so go with 4.0.1.  Will try it again wth 4.1.1 and see if its all good and report back.  Thanks Jimmy!

**Comment by jordan112** [comment]
We tried it with the latest and the same issue, its downloading .net5 level assemblies.  However, we use a lot of internal Nuget stuff and we have internal custom packages that are marked as pre-release.  There could be some confusion with Nuget where it sees those pre-release marked packages and just assumed its all good to download the prerelease version of .NET5 as well.  We will test some more and report back.

**Comment by jordan112** [comment]
I need to figure out what makes it target this 

    <group targetFramework="dotnet">

versus this 

    <group targetFramework="net45"></group>

We want the net45 one and not all the additional dependencies that come with _dotNet_ target.

```xml
<dependencies>
      <group targetFramework="portable-net45+win+wpa81+wp80+MonoAndroid10+Xamarin.iOS10+MonoTouch10"></group>
      <group targetFramework="net45"></group>
      <group targetFramework="net40">
        <dependency id="Microsoft.Bcl" version="1.1.10" />
      </group>
      <group targetFramework="sl50"></group>
      <group targetFramework="wp80"></group>
      <group targetFramework="wpa81"></group>
      <group targetFramework="win80"></group>
      <group targetFramework="MonoAndroid10"></group>
      <group targetFramework="MonoTouch10"></group>
      <group targetFramework="Xamarin.iOS10"></group>
      <group targetFramework="dotnet">
        <dependency id="Microsoft.CSharp" version="4.0.0" />
        <dependency id="System.Collections" version="4.0.10" />
        <dependency id="System.Collections.Concurrent" version="4.0.10" />
        <dependency id="System.Diagnostics.Debug" version="4.0.10" />
        <dependency id="System.Dynamic.Runtime" version="4.0.10" />
        <dependency id="System.Linq" version="4.0.0" />
        <dependency id="System.Linq.Expressions" version="4.0.10" />
        <dependency id="System.Linq.Queryable" version="4.0.0" />
        <dependency id="System.ObjectModel" version="4.0.10" />
        <dependency id="System.Reflection" version="4.0.10" />
        <dependency id="System.Reflection.Extensions" version="4.0.0" />
        <dependency id="System.Reflection.TypeExtensions" version="4.0.0" />
        <dependency id="System.Runtime" version="4.0.20" />
        <dependency id="System.Runtime.Extensions" version="4.0.10" />
        <dependency id="System.Text.RegularExpressions" version="4.0.10" />
        <dependency id="System.Threading" version="4.0.10" />
        <dependency id="System.Threading.Tasks" version="4.0.10" />
      </group>
    </dependencies>
```

**Comment by jordan112** [comment]
temporary workaround until we can figure out the issue on our side.

    update-package -ignoreDependencies AutoMapper

**Comment by jbogard** [comment]
I'd check to make sure you have the latest NuGet client, too.

**Comment by jordan112** [comment]
On latest version.  Running Visual Studio 2013

     2.8.60723.765

**Comment by jordan112** [comment]
We finally got around this issue by removing this dependency in one of the packages and then added it back.  Must have been some Nuget oddity.  Closing this issue.

```xml
<dependency id="AutoMapper" version="4.1.1" />
```
