### ISSUE TITLE
ConvertUsing(Convert.ToInt32) doesn't work anymore

### ISSUE THREAD

**Issue by MichaelCsitkovics** [AutoMapper/AutoMapper#974]
This doesn't work in version 4.1.1 anymore:
`Mapper.CreateMap<string, int>().ConvertUsing(Convert.ToInt32)`

Regards

**Comment by lbargaoanu** [comment]
#964?

**Comment by lbargaoanu** [comment]
@MichaelCsitkovics Can you please close your issue?

**Comment by jbogard** [comment]
Closing.
