### ISSUE TITLE
DataTable and IDataReader stopped working with newest version.

### ISSUE THREAD

**Issue by OxEMoron** [AutoMapper/AutoMapper#975]
I have been loading up a DataTable with records, 
then using mapper to load them into list of objects.  
This was working great about 8 months ago... but now it will not load.

I am using DataTable.CreateDataReader() as the reader into Mapper and it loads 0 each time.
```
var reader = table.CreateDataReader();
Mapper.CreateMap<IDataReader, MyObject>();
var list = Mapper.Map<IDataReader, MyObject>(reader); 
```

**Comment by jbogard** [comment]
Install the AutoMapper.Data package, the IDataReader stuff was moved out in 4.0.

**Comment by lbargaoanu** [comment]
@OxEMoron Can you please close your issue?

**Comment by OxEMoron** [comment]
Yes.

On Thu, Nov 26, 2015 at 10:05 AM, Lucian Bargaoanu <notifications@github.com

**Comment by jsinh** [comment]
I can see this is still in beta - AutoMapper.Data - 1.0.0-beta1.
Any plans to make it official or make a stable release?

@jbogard 

https://www.nuget.org/packages/AutoMapper.Data

**Comment by jsinh** [comment]
Also tried install it with Automapper but still does not work for me.

```
Mapper.Initialize(cfg => cfg.CreateMap<IDataReader, List<Employee>>());
var datTable = dataSet.Tables[0];
var result = Mapper.Map<IDataReader, List<Employee>>(datTable.CreateDataReader());
```

Result give me nothing but empty list. is there anything more i need to configure other than installing the AutoMapper.Data (beta) package to make it work?

I am planning to update this blog post and its code sample (based on request from a reader). Thanks in advance.

http://blog.jsinh.in/how-to-convert-datatable-to-json-object-using-automapper-and-newtonsoft/#.V8hAGIZ96iM

**Comment by jsinh** [comment]
@jbogard 

Update:
I changed the code
https://github.com/jsinh-blog-code/convert-datatabe-to-json/tree/upgrade

based on your tests here
https://github.com/AutoMapper/AutoMapper.Data/blob/master/AutoMapper.Data.Tests/DataReaderMapping.cs

Now i am getting this weird error. Help requested, please!

![2016-09-01_20-39-40](https://cloud.githubusercontent.com/assets/1277539/18172804/95177cd6-7084-11e6-8260-5462e20259c8.png)

**Comment by jsinh** [comment]
@jbogard - Ping
Any chance you can publish the fixes for above issue?
Still waiting, thanks!
