### ISSUE TITLE
ResolutionResult.Context.DestinationValue is null -> cannot get value created by ConstructUsing(...) method

### ISSUE THREAD

**Issue by usarskyy** [AutoMapper/AutoMapper#976]
UPDATED version (I didn't properly copy-paste code from my project that gave me wrong impression of what caused my initial problem)

Here is link to repository that reproduces a bug: https://github.com/usarskyy/AutoMapperBug

II have the following mapping

```
Mapper.CreateMap<SourceA, DestinationA>()    
            .ConstructUsing(Construct)
            .ForMember(x => x.SomeDate, cfg => cfg.Ignore())
            .ForMember(x => x.OtheValue,
              cfg =>
              {
                cfg.ResolveUsing<ValueResolver>();
              });
```
and property value resolver

```
private class ValueResolver : IValueResolver
    {
      public ResolutionResult Resolve(ResolutionResult source)
      {
        var parentValue = (DestinationA) source.Context.DestinationValue;
        var sourceValue = (SourceA) source.Value;

        return source.New(sourceValue.Value.Label + " -> " + parentValue.SomeDate);
      }
    }
```

As I don't pass destination value, new destination value will be created by "Construct" method. Then the behavior is the following
1) version 3.* -> "source.Context.DestinationValue" contains value created by Construct(...) method
2) version 4.* -> "source.Context.DestinationValue" is null

I would be appreciated if somebody could take a look into this problem.

**Comment by lbargaoanu** [comment]
This is a [known issue](https://github.com/AutoMapper/AutoMapper/issues/873#issuecomment-150511101) :)

**Comment by usarskyy** [comment]
> I think it's a matter of time before someone asks for the created destination again.

14 days to the first request :) I think it makes sense to expose value created by AutoMapper.
In my case I get this value _sometimes_ from database and need one of the properties in value resolver to resolve a destination value properly.

BTW, what is the "official" workaround? I can use ResolutionResult.Context.InstanceCache[..] but I'd prefer not to.

**Comment by lbargaoanu** [comment]
I'm not sure whether there is a better way. You can try walking the contexts (through Parent) and look for a destination value, but I would say that's worse.

**Comment by kfhagedorn** [comment]
@usarskyy

This is in the moment my workaround to get the DestinationValue if context.parent.DestinationType is null. 

 ```
EntityBase parentInstance = (EntityBase)context.Parent.DestinationValue;
if (parentInstance == null)
parentInstance = (EntityBase)context.InstanceCache.FirstOrDefault(c => c.Key.SourceType == context.Parent.SourceType && ((DtoBase)c.Key.SourceValue).Id == ((DtoBase)context.Parent.SourceValue).Id).Value;
```
