### ISSUE TITLE
Display Type full name in exceptions

### ISSUE THREAD

**Issue by jimmyheaddon** [AutoMapper/AutoMapper#978]
After upgrading from 4.0.4 to 4.1.1 I've found that I require an empty, private constructor in one of my target classes which I didn't before the upgrade.  Unfortunately the error message "Type needs to have a constructor with 0 args or only optional args" is of little help for nested maps/objects.

Could any instances of "Type" throughout the source please be replaced with Type.GetFullName(), or better yet the Type extension method from [FakeItEasy - FullNameCSharp](https://github.com/FakeItEasy/FakeItEasy/blob/bd57a05c0de5ff37609230fd1b8bc4ec45bc9d4d/Source/FakeItEasy/TypeExtensions.cs).

If this isn't possible in the near future I'll try send a PR, if I can find time :(

**Comment by jbogard** [comment]
Well, before the PR, can you at least post your source/destination types, and how you're calling into AutoMapper to map first? It could be something completely obvious.

**Comment by jimmyheaddon** [comment]
I'll try get an example together in LinqPad, as the production code isn't really something I can post here.  Essentially I'm mapping some simple data types and a couple of enumerations which use type converters, such as:

Mapper.CreateMap<string, DestinationConversionType>()
                  .ConvertUsing<DestinationConversionTypeConverter>();

Mapper.CreateMap<SourceParameter, TargetParameter>()
                  .ForMember(destination => destination.ConversionType, opt => opt.MapFrom(source => source.ConversionType));
