### ISSUE TITLE
membersToExpand expression causes exception

### ISSUE THREAD

**Issue by ebussa** [AutoMapper/AutoMapper#979]
After ugprading to v4, the membersToExpand expression `accommodation => accommodation.Details.Select(detail => detail.Accommodation.Category)` causes the exception "Expected a property/field access expression"

Error message: "Expected a property/field access expression, not accommodation => accommodation.Details.Select(detail => detail.Accommodation.Category) Parameter name: expression"

StackTrace: " at AutoMapper.Internal.ReflectionHelper.GetFieldOrProperty(LambdaExpression expression) at System.Linq.Enumerable.WhereSelectArrayIterator'2.MoveNext() at System.Linq.Buffer'1..ctor(IEnumerable'1 source) at System.Linq.Enumerable.ToArray\[TSource\](IEnumerable'1 source) at AutoMapper.QueryableExtensions.ProjectionExpression.GetMembers\[TResult\](Expression'1\[\]membersToExpand) at AutoMapper.QueryableExtensions.ProjectionExpression.To\[TResult\](IDictionary'2 parameters, Expression'1\[\] membersToExpand) "

**Comment by lbargaoanu** [comment]
You're welcome to try the fix :)

**Comment by ebussa** [comment]
Any idea when there might be another dev build?

**Comment by lbargaoanu** [comment]
That's @jbogard's job :)

**Comment by shaneray** [comment]
I also get an exception when trying to expand with strings "Accommodation.Category" if Category is a collection.  @lbargaoanu your pull request does not resolve that also does it?

**Comment by shaneray** [comment]
I am not sure if its the best approch, but I have found updating the GetMemberType method in ReflectionHelper.cs to this resolves my issues....

```
public static Type GetMemberType(this MemberInfo memberInfo)
        {
            Type output = null;
            if (memberInfo is MethodInfo)
                output = ((MethodInfo) memberInfo).ReturnType;
            if (memberInfo is PropertyInfo)
                output = ((PropertyInfo) memberInfo).PropertyType;
            if (memberInfo is FieldInfo)
                output = ((FieldInfo) memberInfo).FieldType;

            if (output != null && output.IsCollectionType())
            {
                output = output.GetGenericArguments()[0];
            }

            return output;
        }

**Comment by shaneray** [comment]
So apparently that was not the best approach.. After doing more testing I have found the "solution" above is not working for nested collections. "ClassA.ClassB.ClassC" where ClassC is a collection still throws the exception "Sequence contains no elements."

**Comment by shaneray** [comment]
I deleted my previous comment as it was wrong, the fix above also works for nested collections.

**Comment by lbargaoanu** [comment]
I still see the comment, but I take it you mean my fix works as expected :)

**Comment by lbargaoanu** [comment]
I think I now see you point. I had no idea this used to work.

**Comment by lbargaoanu** [comment]
All this seems a little weird to me, but now it should work as before.

**Comment by shaneray** [comment]
Very nice... Thanks for the quick response.  I can't wait for @jbogard to merge this in and do a release.  This is the only thing stopping us from being able to upgrade to the latest version.

**Comment by ebussa** [comment]
Why does the dev build package target dotnet5.1?

**Comment by jbogard** [comment]
@ebussa I'm playing with the packages. It looks like dotnet5.1 won't work as a catch-all, I'm just going to revert all that. Trying to work towards this:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by ebussa** [comment]
After upgrading to nightly 1022 we're still getting error message:

Expected a property/field access expression, not accommodation => accommodation.Details.Select(detail => detail.Accommodation.Category)

**Comment by lbargaoanu** [comment]
It has to me merged in develop first. You'll get an email when that happens and the issue is closed.

**Comment by lbargaoanu** [comment]
@ebussa The fix should be in the daily build now. If everything is OK, you can close the issue.

**Comment by ebussa** [comment]
Looks good. Thank you.

**Comment by shaneray** [comment]
Any idea when this will be available via nuget?  Would really like to be able to upgrade from 3.1.1 but cannot do so until this is available.

**Comment by jbogard** [comment]
Well, today, from the nightly feed on MyGet.

**Comment by shaneray** [comment]
Great!  I'll look for it there.  Thanks @jbogard
