### ISSUE TITLE
(Option to) make enum mapping case insensitive

### ISSUE THREAD

**Issue by MDeSchaepmeester** [AutoMapper/AutoMapper#985]
I noticed that enum mapping is case sensitive, it's also hard-coded:

 [src/AutoMapper/Mappers/EnumMapper.cs#L36](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/Mappers/EnumMapper.cs#L36):

    return Enum.Parse(enumDestinationType, stringValue, true /*case sensitive*/)

Could we have an option to make it case insensitive? Preferrably per TypeMap of course.

**Comment by lbargaoanu** [comment]
This seems to work. A failing test would help. What version are you on?

**Comment by MDeSchaepmeester** [comment]
@lbargaoanu yeah I just remember we're stuck on 3.3 for the moment, we can't go to the required .NET 4.5 yet. Was a little too quick to open the issue, sorry.

**Comment by lbargaoanu** [comment]
No problem, but you can close it :)
