### ISSUE TITLE
.As<T>() no longer works for abstract classes

### ISSUE THREAD

**Issue by connelhooley** [AutoMapper/AutoMapper#986]
On version 3.3.1 I use the following mapping:

Mapper.CreateMap<InputClass, AbstractOutputBaseClass>().As<OutputClass>();
Mapper.CreateMap<InputClass, OutputClass>();

This allows me to map my abstract base class as my output class.

However I have just upgraded to 4.1.1 and this no longer works. I get the following exception:
InvalidOperationException => Instances of abstract classes cannot be created.

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/842#issuecomment-139104798).

**Comment by lbargaoanu** [comment]
@connelhooley Can you please close your issue?

**Comment by connelhooley** [comment]
Sorry forgot to close, thanks @lbargaoanu
