### ISSUE TITLE
ConstructorMappingEnabled has no effect?

### ISSUE THREAD

**Issue by Nebula83** [AutoMapper/AutoMapper#987]
I've set ConstructorMappingEnabled to false but I still get an error from Entity Framework:

 Only parameterless constructors and initializers are supported in LINQ to Entities.

Changing the names in my constructor fixes the issue. 

Setting ConstructorMappingEnabled  to true doesn't work either so I think it doesn't adhere the setting.

Btw, ConstructUsing(new Func<TSource, TDest>(p => new TDest())); yields the same result.

**Comment by lbargaoanu** [comment]
You tried to use ConstructorMappingEnabled as a workaround? If that's the case, what exactly didn't work as expected?

**Comment by lbargaoanu** [comment]
And about ConstructorMappingEnabled, there are a few passing tests (search for DisableConstructorMapping). So unless you can provide a failing test, there isn't much we can do.

**Comment by Nebula83** [comment]
Sorry, I was a bit vague in my description. Please check out the following reproduction scenario:

    //Automapper issue #987
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Configuration.ConstructorMappingEnabled = false;
            Mapper.CreateMap<LatLong, GpsPos>();
            new[] {new LatLong()}.AsQueryable().ProjectTo<GpsPos>().ToList();
        }
    }

    class LatLong
    {
        public double Latitude  { get; set; }
        public double Longitude { get; set; }
    }

    class GpsPos
    {
        public GpsPos()                                  { Console.WriteLine("Default constructor called"); }
        public GpsPos(double latitude, double longitude) { Console.WriteLine("Specific constructor called");}

        public double Latitude  { get; set; }
        public double Longitude { get; set; }
    }

Program output

    Specific constructor called

I think this is not correct; I'd expect a call to the default constructor followed by the copying of the properties.

The workaround I mentioned involves adjusting the GpsPos class like so:

    class GpsPos
    {
        public GpsPos()                       { Console.WriteLine("Default constructor called"); }
        public GpsPos(double Lat, double Lon) { Console.WriteLine("Specific constructor called");}

        public double Latitude  { get; set; }
        public double Longitude { get; set; }
    }

Then the default constructor is called.

**Comment by lbargaoanu** [comment]
Now I see it :)

**Comment by Nebula83** [comment]
//Automapper issue #987
    class Program
    {
        static void Main(string[] args)
        {
            Mapper.Configuration.ConstructorMappingEnabled = false;
            Mapper.CreateMap<LatLong, GpsPos>()
                .ConstructUsing(new Func<LatLong, GpsPos>(x => new GpsPos()));
            new[] {new LatLong()}.AsQueryable().ProjectTo<GpsPos>().ToList();
        }
    }

    class LatLong
    {
        public double Latitude  { get; set; }
        public double Longitude { get; set; }
    }

    class GpsPos
    {
        public GpsPos()                                  { Console.WriteLine("Default constructor called"); }
        public GpsPos(double latitude, double longitude) { Console.WriteLine("Specific constructor called");}

        public double Latitude  { get; set; }
        public double Longitude { get; set; }
    }

Program output

    Specific constructor called

**Comment by Nebula83** [comment]
@lbargaoanu Great =)

**Comment by lbargaoanu** [comment]
About that last bit, you should call ConstructProjectionUsing and it does the job.

**Comment by lbargaoanu** [comment]
And silly enough, a workaround is to call DisableConstructorMapping instead of setting the property.

**Comment by Nebula83** [comment]
Yes indeed! Great, thanks!
