### ISSUE TITLE
ConstructUsing throws error when returning null object

### ISSUE THREAD

**Issue by mmulhearn** [AutoMapper/AutoMapper#988]
When you return a null in the ConstructUsing method, an exception is thrown.  I assume this is because before and after mapping methods want a non-null value.  This shouldn't be.

If I use AutoMapper to make to, say, a database and I want item X with ID Y but it doesn't exist in the database, then null is an appropriate return.  

Currently, if I want to return a null, I have to either return an empty object or a NullObject or something else.  There should be checks for a null return and if it is null, before and after mapping methods should not be called and the mapping result should be a null.

**Comment by jbogard** [comment]
This....is going to need a pull request. It seems very odd that I ask something to construct an object, and it doesn't. Why not return a blank object?

**Comment by mmulhearn** [comment]
I'm not sure why I would want a blank object.

If I use my example above with the database pull and I have the following object definition:

    public class Foo {
        public int Id { get; set; }
    }

Now my code, instead of just doing a null comparison, has to do an Id comparison on a BS object.  Also, if it's an extensive object with nested objects and such, that's more expensive to pass around in memory than a null.  To me, and I'm sure it can be argued, returning a null is more correct in this scenario.

**Comment by jbogard** [comment]
I'm still confused, why is AutoMapper hitting the database at all? What exactly does your config look like, and your mapping?

**Comment by mmulhearn** [comment]
AutoMapper is not hitting the database (I'm not even sure how'd you do that).  There are loads of examples to use EF with AutoMapper, but I don't like EF.  It encapsulates way too much and I'm just not a fan.  So, what I have is a layered approach.  I have a layer that does business logic that talks to a data access layer.  To decouple these layers, I use AutoMapper and generics between these two layers, what I call (quite creatively) a "translation layer."  I actually have two of these but that's another story.  So, when my data access layer comes back with a DataSet, that DataSet is an instantiated object, but it may hold zero DataTables or DataTables with zero rows.  In this case, no data came back.  Therefore, in most cases, I want to return null back to my business layer indicating "I couldn't find anything."

To be clear, hitting a database is just the example I'm using. I've run into this issue before without hitting a database.

**Comment by AuthorProxy** [comment]
```
            CreateMap<TravelExpense, TravelExpenseViewDto>()
                .Include<TravelExpense, TravelExpenseDetailedViewDto>()
                .ForMember(dto => dto.TravelExpenseId, opt => opt.MapFrom(model => model.Id));

            CreateMap<FileStorage, TravelExpenseDetailedViewDto>()
                .ForMember(dto => dto.ReceiptFileId, opt => opt.MapFrom(model => model.Id))
                .ForMember(dto => dto.ReceiptFileName, opt => opt.MapFrom(model => model.FileName))
                .ForMember(dto => dto.ReceiptFileDescription, opt => opt.MapFrom(model => model.FileDescription))
                .ForSourceMember(model => model.Blob, opt => opt.Ignore());

            CreateMap<TravelExpense, TravelExpenseDetailedViewDto>()
                .ConstructUsing(model => Mapper.Map<TravelExpenseDetailedViewDto>(model.ReceiptData))
                .ForSourceMember(model => model.ReceiptData, opt => opt.Ignore());
```

The same error, when `model.ReceiptData` is null - throws error, need some way to cancel construction on condition
