### ISSUE TITLE
A strange issue

### ISSUE THREAD

**Issue by Farb** [AutoMapper/AutoMapper#989]
Here is my profile class:
```C#
public class ProvinceProfile : Profile
{
    protected override void Configure()
    {
        Mapper.Initialize(cfg => cfg.CreateMap<Provinces, ProvinceDto>()
            .ForSourceMember(src=>src.UpdatedDate,opt=>opt.Ignore())
        .ReverseMap());
    }
}
Then I add the profile class :
```

```C#
public static class AutoMapperWebConfig
{
    public static void Configure()
    {
        Mapper.Reset();
        Mapper.Initialize(cfg =>
        {
            cfg.AddProfile<ProvinceProfile>();

            cfg.AddProfile<CityProfile>();
            cfg.AddProfile<StationProfile>();

            cfg.AddProfile<TerminalDeviceProfile>();//TerminalDeviceProfile依赖ProvinceProfile

           
        });
        Mapper.AssertConfigurationIsValid();//验证所有的映射配置是否都正常
    }
}

```
Finally,I call the static Configure method when the app starts and I make sure it works.
Here is my Entity class and Dto class:
```C#
public class Provinces : Entity
{
    public virtual string Code{ get; set; }

    public virtual string Name{ get; set; }
    public virtual string UpdatedBy{ get; set; }
    public virtual DateTime? UpdatedDate{ get; set; }
    public Provinces(){}

```
```C#
public class ProvinceDto:EntityDto
{
    public string Code { get; set; }
    public string Name { get; set; }
}

```
The next is important!
When I use Mapper.Map,I got an error!
![image](https://cloud.githubusercontent.com/assets/7587900/11416080/3f909372-9445-11e5-8dfc-ccd9175e65e9.png)
However,when I use DynamicMap,I did it!Why?
![image](https://cloud.githubusercontent.com/assets/7587900/11416129/ba60074a-9445-11e5-8e06-2c54b919da2b.png)

I really got confused!I think I shoud use Mapper.Map.Could you give me an analysis?

**Comment by lbargaoanu** [comment]
You should use Mapper.Map because you know the types you're mapping. You need to isolate the issue. [This](https://github.com/AutoMapper/AutoMapper/blob/86d3019fd5b28aa15921517d0b128b152318747b/src/UnitTests/Bug/DestinationValueInitializedByCtorBug.cs) is a passing test using collections. Try to make it fail :)

**Comment by lbargaoanu** [comment]
On a second thought, I might know what's wrong. You need to call Profile.CreateMap in Configure, not Mapper.Initialize

public class ProvinceProfile : Profile
{
    protected override void Configure()
    {
        CreateMap<Provinces, ProvinceDto>()
            .ForSourceMember(src=>src.UpdatedDate,opt=>opt.Ignore())
            .ReverseMap();
    }
}

**Comment by Farb** [comment]
Thank you,lbargaoanu!I modified the code as you said,I did it finally!

**Comment by Farb** [comment]
The second thought is right!However,other profile class,like CityProfile,TerminalDeviceProfile,is okay in the my old wrong way before.

**Comment by lbargaoanu** [comment]
That's just an accident :)

**Comment by Farb** [comment]
All right!:sunglasses:
