### ISSUE TITLE
Async mapping operations

### ISSUE THREAD

**Issue by tmm360** [AutoMapper/AutoMapper#991]
Hi, I'm using an IValueResolver that has to perform into the Resolve(ResolutionResult) method an async call. This is used for a lazy loading and I can't move it out. Actually I'm running this call using AsyncHelper (https://gist.github.com/ChrisMcKee/6664438), but I'm worried about performance degeneration. I can't simply run the call blocking the main thread, it is used for a web service.
What I'd need is an async version of IValueResolver interface, and a MapAsync() method to perform mapping operations.
Can you see an other way or a temporary workaround? Did you ever have this need? Thanks

**Comment by lbargaoanu** [comment]
Workarounds: blocking, eager loading, caching. I don't think AutoMapper is designed for anything other than simple mapping operations, and even if @jbogard would agree with your view, async is not something that can be done overnight :) I think you'll have to use a workaround.

**Comment by tmm360** [comment]
I think that automapper is a fantastic instrument, and I really need to use this feature. Do you think that could be a possible feature?

A temporary workaround that I imagined is a 3-steps way:
1) I perform a first map, getting references to all unloaded objects
2) Load referenced objects into source with an async call (external to automapper)
3) Re-perform mapping operations as point 1, but with full loaded objects

If there are nested needed objects that after 2) are not loaded, it will require to loop until all objects are loaded, but this is. I could also re-map only reported objects and get performances near of async implementation, but this is still a tricky workaround.

**Comment by jbogard** [comment]
I just can't see doing this. Putting async everywhere would absolutely suck, you can use mapping parameters to do this instead and await before passing the parameters to `IMappingOperationOptions`.
