### ISSUE TITLE
aspnet5?

### ISSUE THREAD

**Issue by rhires** [AutoMapper/AutoMapper#992]
Has anyone tested AutoMapper with aspnet5/MVC6? Or anything cross platform? I'm running on Mac OS X rc-1 and I'm curious. I'm doubtful the nuget package will work for me, and I'm not totally sure where to look.

**Comment by jbogard** [comment]
Yes, I have. I test on roughly 13-14 target frameworks before a release. Should work just fine.

**Comment by rhires** [comment]
Cool! I'll try it out hopefully this week and let you know how I did :-)
