### ISSUE TITLE
Mapper.AssertConfigurationIsValid() throws NullReferenceException for Nullable -> Nullable property map

### ISSUE THREAD

**Issue by drewcasa** [AutoMapper/AutoMapper#993]
After upgrading to 4.1.1.0, validation of configuration throws a NullReferenceException when mapping a `Nullable<bool>` to a `Nullable<char>`.  

```csharp
[Fact]
public void ValidateMapOfNullableValueTypes_ThrowsNullRefException()
{
    var map = Mapper.CreateMap<BoolSource, CharDest>().TypeMap;
    Assert.Throws<NullReferenceException>(() => Mapper.AssertConfigurationIsValid(map));
}
```

With these Types:

```csharp
public class BoolSource
{
    public bool? Val { get; set; }
}

public class CharDest
{
    public char? Val { get; set; }
}
```

I stepped through the validation as well as actual mapping, and the problem seems to be in how the ResolutionContext is constructed if the source type is nullable.  

In ConfigurationStore.DryRunTypeMap(...) is this:

        if (mapperToUse == null && context.SourceType.IsNullableType())
        {
            var nullableContext = context.CreateValueContext(null, Nullable.GetUnderlyingType(context.SourceType));
            ...

The call to `ResolutionContext.CreateValueContext()` may be the culprit.  The chained constructor results in a context which has no DestinationType, and the following search for a matching Mapper will eventually fail when `context.DestinationType` is accessed.

**Comment by lbargaoanu** [comment]
My bad :)
