### ISSUE TITLE
Broken inheritance after upgrading to version 4.1.1 (in RELEASE mode only)

### ISSUE THREAD

**Issue by IT-CASADO** [AutoMapper/AutoMapper#999]
Hi,

I'm trying to upgrade from version 3.3.0 to latest version (4.1.1).

But version 4.1.1 doesn't work as expected. I have created a small repro (unit test) for this issue:
https://onedrive.live.com/redir?resid=9015906EEFE99AC3!112084&authkey=!AJrc4eTZUW0ho-w&ithint=file%2czip
(unfortunately I cannot upload ZIP files with this error: Unfortunately, we don’t support that file type.)

This unit test gives no error with version 3.3.0, but with 4.1.1)

Example code:
         Models.Action action = new Models.Actions.BusinessTransaction() { Name = "BT", PropertyBusinessTransaction = "My Property" };
         var result = Mapper.Map<Models.ActionDTO>(action);
         result.Should().BeOfType(typeof(Models.Actions.BusinessTransctionDTO));

As you can see, the expected type of result should be <Models.Actions.BusinessTransactionDTO>, but in 4.1.1 it is <Models.ActionDTO>. That is wrong!

What drives me really crazy is, that this only occurs on RELEASE build only. If you compile this in DEBUG mode the type of result is as expected <Models.Actions.BusinessTransactionDTO>.

This prevents me to upgrade to latest version.

Regards,
Daniel

**Comment by jbogard** [comment]
Just offhand, are you using Mapper.Initialize instead of Mapper.CreateMap?

**Comment by jbogard** [comment]
So I can say somewhat quickly it's that you're using Mapper.CreateMap instead of Mapper.Initialize.

Initialize is less prone to getting things out-of-order, so I'm moving the config logic into it.

**Comment by IT-CASADO** [comment]
Yes, I'm using Mapper.CreateMap. I have to look into the documentation for the difference between these two options...

**Comment by IT-CASADO** [comment]
BTW: This doesn't explain why I have different behavior/result between DEBUG and RELEASE mode.

**Comment by jbogard** [comment]
No, but it should fix things for you. I never use Mapper.CreateMap, only Mapper.Initialize, since I want maps created once at startup and referenced from there on out.

**Comment by IT-CASADO** [comment]
hmm...

I changed my code from this:

        Mapper.CreateMap<Models.Action, Models.ActionDTO>()
            .Include<Models.Actions.BusinessTransaction, Models.Actions.BusinessTransctionDTO>();

         Mapper.CreateMap<Models.ActionDTO, Models.Action>()
            .Include<Models.Actions.BusinessTransctionDTO, Models.Actions.BusinessTransaction>();

         Mapper.CreateMap<Models.Actions.BusinessTransaction, Models.Actions.BusinessTransctionDTO>();
				;
         Mapper.CreateMap<Models.Actions.BusinessTransctionDTO, Models.Actions.BusinessTransaction>();


to 


        Mapper.Initialize(cfg => {
            cfg.CreateMap<Models.Action, Models.ActionDTO>()
               .Include<Models.Actions.BusinessTransaction, Models.Actions.BusinessTransctionDTO>();

            cfg.CreateMap<Models.ActionDTO, Models.Action>()
               .Include<Models.Actions.BusinessTransctionDTO, Models.Actions.BusinessTransaction>();

            cfg.CreateMap<Models.Actions.BusinessTransaction, Models.Actions.BusinessTransctionDTO>();

            cfg.CreateMap<Models.Actions.BusinessTransctionDTO, Models.Actions.BusinessTransaction>();
         });


and now it works for version 4.1.1 too!

But why exists two ways of configuration? Particularly if one of this ways is error prone!?

(It is correct to close this issue? I think no!?)

Regards,
Daniel

**Comment by lbargaoanu** [comment]
You can close the issue. See [previous](https://github.com/AutoMapper/AutoMapper/issues/868#issuecomment-138480671) conversations.

**Comment by wstaelens** [comment]
I'm also facing a problem or bug that only exists in Release and not in Debug.
It has something about: Proxy<foo_...>' in Assembly 'AutoMapper.Proxies'
Everything works fine in Debug. (4.1.1).

I'm going to see if it has something to do with the .CreateMap as I also use it.

**Comment by wstaelens** [comment]
I had the problem that everything works in Debug but not in Release.
After +2 days I finally found this ticket and i think I have found a solution.

I had this bug: only in Release:
```
Exception thrown: 'System.Runtime.Serialization.SerializationException' in mscorlib.dll

Additional information: Type 'Proxy<IFooDto_Blabla_Version=1.2.3.4_Culture=neutral_PublicKeyToken=null>' in Assembly 'AutoMapper.Proxies, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' is not marked as serializable.
``` 

So there was something wrong with mapping my interface. I used AutoMapper.TypeConverter but that didn't solve the issue.

After finding this post I found a solution that doesn't give me the SerializationException anymore in Release mode:

Original code:
```csharp
public class AMConfig 
{
   public static void InitializeAutoMapper() 
   {
       Mapper.CreateMap<...>();
       Mapper.CreateMap<...>();
       // etc...
       Mapper.CreateMap<Foo, IFooDTO>().As(FooDTO);
   }
}
```

I had an interface and i was using .As().
If I comment the line .As() --> my code works:
https://github.com/AutoMapper/AutoMapper/issues/868#issuecomment-138480671 

**code that works in release: solution 1**
```csharp
public class AMConfig 
{
   public static void InitializeAutoMapper() 
   {
       Mapper.CreateMap<...>();
       Mapper.CreateMap<...>();
       // etc...
       //Mapper.CreateMap<Foo, IFooDTO>().As(FooDTO); // remove .As line.
   }
}
```

Other thing that works is still using .As but wrap everything in Initialize:

**code that works in release: solution 2**

```csharp
public class AMConfig 
{
   public static void InitializeAutoMapper() 
   { 
       Mapper.Initialize(cfg => 
       {
           Mapper.CreateMap<...>();
           Mapper.CreateMap<...>();
            // etc...
           Mapper.CreateMap<Foo, IFooDTO>().As(FooDTO);
      });
   }
}
```

So it looks like there is a bug in the .As and/or CreateMap  in release mode in automapper 4.1.1.

Hopefully this helps.

**Comment by jbogard** [comment]
In Mapper.Initialize, you should be calling cfg.CreateMap, not Mapper.CreateMap.

**Comment by IT-CASADO** [comment]
In my opinion this is a bug that should be investigate and fixed.
Using cfg.CreateMap is only way to configure AutoMapper. Mapper.CreateMap the other. If both are provided, both should be worked correctly.

**Comment by wstaelens** [comment]
indeed, I have seen this problem @jbogard  Thanks for the attention!

**Comment by jbogard** [comment]
Yeah, this is a bug, the trick will be to calculate all mappings on first call to Map, but only when you call `Mapper.CreateMap`.

**Comment by lbargaoanu** [comment]
So to call Seal if it was not called before the first Map?

**Comment by jbogard** [comment]
Yep exactly

**Comment by lbargaoanu** [comment]
That should work. But there would be some small overhead on each map (to check in a thread safe manner that Sealed was called). And, more important I think, a big overhead on the first Map call, not a good experience. Maybe throw if Seal was not called? It doesn't seem such a big deal to add a Seal call to an existing app.

**Comment by jbogard** [comment]
tbqh the *long* term fix is to obsolete the whole static API. Too many bugs that rely on the exact ordering of calls.

**Comment by TylerCarlson1** [comment]
So only Mapper.Initilize and Mapper.Map will be left, or are they obsolete too?

**Comment by jbogard** [comment]
So when I first created automapper my boss said "looks great Jimmy but have you thought about making the API instance-based and not static?" and I said "pfffffffft whatever".

It would have been nice to combine MappingEngine and Mapper, but the static/instance collisions would kill it.

**Comment by Cephei** [comment]
I'm trying to confirm this is the issue I'm running into as I'm attempting to migrate from v3.3.1 to 4.2.1.

Inheritence seems to still be broken.
```csharp
mapperConfiguration.CreateMap<File, FileDto>()
    .ForMember(dto => dto.CreatedByUserId, c => c.MapFrom(f => f.CreatedByUserId))
    .ForMember(dto => dto.CreatedOn, c => c.MapFrom(f => f.CreatedOn))
    .ForMember(dto => dto.Extension, c => c.MapFrom(f => f.Extension))
    .ForMember(dto => dto.Id, c => c.MapFrom(f => f.Id))
    .ForMember(dto => dto.Md5Hash, c => c.MapFrom(f => f.Md5Hash))
    .ForMember(dto => dto.Size, c => c.MapFrom(f => f.Size));

mapperConfiguration.CreateMap<DocumentRevisionFile, FileDto>()
    .IncludeBase<File, FileDto>(); // <<<< BREAKS! 
```

> System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.Profile.CreateMap(Type sourceType, Type destinationType)
   at AutoMapper.Internal.MappingExpression`2.IncludeBase(Type sourceBase, Type destinationBase)
   at AutoMapper.Internal.MappingExpression`2.IncludeBase[TSourceBase,TDestinationBase]()

I've tried both: `Mapper.Initialize()` & using `new MapperConfiguration(c => { });`

**Comment by jbogard** [comment]
This is now fixed!
